### ISSUE TITLE
Pulling timeout dial tcp 54.239.192.75:443: i/o timeout

### ISSUE THREAD

**Issue by Somebi** [docker/docker#20225] opened 2016-02-11 10:17 UTC
Using last version from your repo.
Would be nice to have a reconnect feature for pull.

**Comment by cpuguy83** [comment] 2016-02-11 15:25
Solved by #19840

Closing since the issue is not generally helpful and will be resolved by an open PR.

**Closed by cpuguy83** 2016-02-11 15:25 UTC
