### ISSUE TITLE
Vol mounted overlayfs directory in is invisible to container

### ISSUE THREAD

**Issue by suryagaddipati** [docker/docker#21739] opened 2016-04-04 00:04 UTC
` /cache/ssd/merged/6` is an overlayfs 'merged' directory

on the host machine 

```
# ls /cache/ssd/merged/6
saf.txt  sf.txt

```

```
docker run  -it -v /cache/ssd/merged/6:/images busybox sh
/ # ls /images/
/#
```
Expected:   ` ls /images ` should show contents of the mounted directory

I verified that this works with `runc` with the following config 

```
"mounts": [
                {
                       "destination": "/images/",
                        "type": "bind",
                        "source": "/cache/ssd/merged/6",
                        "options": ["bind","rw"]
}
....
```

Versions

```
docker --version
Docker version 1.10.3, build 20f81dd

docker info

Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.1-1.el6.elrepo.x86_64
Operating System: <unknown>
OSType: linux
Architecture: x86_64
```

**Comment by HackToday** [comment] 2016-04-04 13:27
Could you tell me what's OS do you use ?

I found it said `Operating System: <unknown>`

**Comment by suryagaddipati** [comment] 2016-04-04 15:07
hi @HackToday  its ,

```
CentOS release 6.5 (Final)
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
```

**Comment by cpuguy83** [comment] 2016-04-04 15:12
@suryagaddipati Is docker being started in it's own mount namespace?
Check the systemd unit file and see `MountFlags`.

**Comment by suryagaddipati** [comment] 2016-04-04 15:36
hi @cpuguy83 

No Docker is not being started in its own Mount namespace. I am not systemd to start docker.

**Comment by cpuguy83** [comment] 2016-04-04 15:47
@suryagaddipati How are you starting Docker?

I cannot reproduce this.
It looks like Docker is not able to see the mount, which is why it appears empty.

**Comment by suryagaddipati** [comment] 2016-04-04 15:52
@cpuguy83 
This is how docker is being started

```
/usr/local/bin/docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock  -s overlay -g=/var/docker
```

**Comment by cpuguy83** [comment] 2016-04-04 15:54
Are you doing this directly at the command line or from some init system?

**Comment by suryagaddipati** [comment] 2016-04-04 16:04
@cpuguy83 docker is being started by sysv init.

```
[root ~]# cat /etc/sysconfig/docker
# -*- mode: sh -*-
#
# Managed via ansible - manual changes WILL be lost!
#
# /etc/sysconfig/docker
#
# Other arguments to pass to the docker daemon process
# These will be parsed by the sysv initscript and appended
# to the arguments list passed to docker -d

other_args="-H tcp://0.0.0.0:2375 \
            -H unix:///var/run/docker.sock \
            -s overlay -g=/var/groupon/docker"

```

**Comment by cpuguy83** [comment] 2016-04-04 16:06
@suryagaddipati Can you provide the full script?

**Comment by suryagaddipati** [comment] 2016-04-04 16:11
@cpuguy83 

```
~]# cat /etc/init.d/docker
#!/bin/sh
#
#       /etc/rc.d/init.d/docker
#
#       Daemon for docker.com
#
# chkconfig:   2345 95 95
# description: Daemon for docker.com

### BEGIN INIT INFO
# Provides:       docker
# Required-Start: $network cgconfig
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: start and stop docker
# Description: Daemon for docker.com
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog="docker"
unshare=/usr/bin/unshare
exec="/usr/local/bin/$prog"
pidfile="/var/run/$prog.pid"
lockfile="/var/lock/subsys/$prog"
logfile="/var/log/$prog"

[ -e /usr/local/etc/sysconfig/$prog ] && . /usr/local/etc/sysconfig/$prog

prestart() {
    service cgconfig status > /dev/null

    if [[ $? != 0 ]]; then
        service cgconfig start
    fi

}

start() {
    [ -x $exec ] || exit 5
    check_for_cleanup

    if ! [ -f $pidfile ]; then
        prestart
        printf "Starting $prog:\t"
        echo "\n$(date)\n" >> $logfile
        "$unshare" -m -- $exec daemon $other_args &>> $logfile &
        pid=$!
        touch $lockfile
        # wait up to 10 seconds for the pidfile to exist.  see
        # https://github.com/docker/docker/issues/5359
        tries=0
        while [ ! -f $pidfile -a $tries -lt 10 ]; do
            sleep 1
            tries=$((tries + 1))
        done
        success
        echo
    else
        failure
        echo
        printf "$pidfile still exists...\n"
        exit 7
    fi
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile -d 300 $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


check_for_cleanup() {
    if [ -f ${pidfile} ]; then
        /bin/ps -fp $(cat ${pidfile}) > /dev/null || rm ${pidfile}
    fi
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac







```

**Comment by cpuguy83** [comment] 2016-04-04 16:11
`"$unshare" -m -- $exec daemon $other_args`
This is starting docker in a separate mount namespace.

**Comment by cpuguy83** [comment] 2016-04-04 16:19
Closing since this is most likely the cause of docker not being able to see the mount.
Please test w/o using `unshare -m` and let me know if you are still having a problem.

Thanks.

**Closed by cpuguy83** 2016-04-04 16:19 UTC

**Comment by suryagaddipati** [comment] 2016-04-04 16:20
@cpuguy83 ah I didn't notice that. Thank you for your quick response. I will update this issue once I get it working, for future reference.

**Comment by suryagaddipati** [comment] 2016-04-04 16:33
worked as expected without `$unshare` . Thanks again @cpuguy83 .

**Comment by cpuguy83** [comment] 2016-04-04 16:34
Glad to hear it!
