### ISSUE TITLE
ubuntu requires me to use sudo otherwise it wont do work.  How can i make it recognize docker without using sudo ?

### ISSUE THREAD

**Issue by jpca999** [docker/docker#27427] opened 2016-10-16 21:48 UTC
ubuntu requires me to use sudo otherwise it wont do work.  How can i make it recognize docker without using sudo ?

**Comment by thaJeztah** [comment] 2016-10-16 21:56
This is because the socket is owned by root. You can add your user to the `docker` group, as explained here; https://docs.docker.com/engine/installation/linux/ubuntulinux/#/create-a-docker-group

I'll close this issue because this is not a bug, but feel free to continue the conversation if you need additional information

**Closed by thaJeztah** 2016-10-16 21:56 UTC
