### ISSUE TITLE
curl: (56) Failure when receiving data from the peer

### ISSUE THREAD

**Issue by kps18** [docker/docker#12625] opened 2015-04-22 07:33 UTC
Hi 
We have some connection  isssue within containers.

1. Using curl we are downloading some contents from container running in 2.6 kernal and destination container running in kernel 3.8 

Is this is bug or we can fix. If there is any fix please help me.

Regards
Kps

**Comment by unclejack** [comment] 2015-04-23 12:25
@kps18 Kernel 3.8 is unsupported. You haven't provided any steps to reproduce this problem, nor any output from `docker info` and `docker version` from the two systems.

Please provide the exact steps to reproduce the problems you're seeing. I'm going to close this issue now as it lacks the required details.

This issue will be re-opened once the needed bits of information are provided. There is no need to open a new issue.

**Closed by unclejack** 2015-04-23 12:25 UTC

**Comment by kps18** [comment] 2015-04-24 03:06
@unclejack   destination container running in kernel 3.10 

Destination 

version 

Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2


info 

Containers: 8
Images: 113
Storage Driver: devicemapper
 Pool Name: docker-8:4-52035872-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 17.71 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 15.09 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.84-RHEL7 (2014-03-26)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)


Source'

info:-
Containers: 49
Images: 201
Storage Driver: devicemapper
 Pool Name: docker-8:5-28443042-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 18.02 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 28.48 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-431.20.3.el6.x86_64
Operating System: <unknown>
CPUs: 48
Total Memory: 62.87 GiB
Name: sdsdsd
ID: QRXA:OHBN:3B4N:J6V5:AGUF:3BWB:SW7W:BNNV:IJHA:JNAZ:26NB:NMFX
Username: sdsdd
Registry: [https://index.docker.io/v1/]
 version:-
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0

**Comment by jfrazelle** [comment] 2015-04-24 09:07
ping @rhatdan

**Comment by jfrazelle** [comment] 2015-04-24 09:08
Also I think you are confused. The container has the same kernel version as
the host.

**Comment by kps18** [comment] 2015-04-24 09:59
yes the container has the same kernel version as the host. But the problem is from different  host.
Source is 2.6.32-431.20.3.el6.x86_64 and the destination is 3.10.0-123.el7.x86_64.

Problem is,  If we download api content in container running in version 3.10.0-123.el7.x86_64. from the container running in 2.6.32-431.20.3.el6.x86_64  we faced curl: (56) Failure when receiving data from the peer

**Comment by rhatdan** [comment] 2015-04-24 14:34
I have no idea how curl would fail in a container for anything docker is doing.  I don't believe this has anything to do with the kernel.  Why would curl care about the kernel?

**Comment by kps18** [comment] 2015-04-24 15:03
Not also using curl it is failing, if we use wget  following error came 
      

 - "Read error at byte 55940/515487 (Connection reset by peer). Retrying."

**Comment by rhatdan** [comment] 2015-04-24 15:16
So it could be slowness.  If you try to wget/curl on the host running the containers, does it work?

I suppose their could be something about the network speed that is causing this problem.

You could also try to run a container with --net=host to see if the wget/curl works.

**Comment by kps18** [comment] 2015-04-24 15:44
Yes wget/curl is working in same kernel version between containers in same host and also in  different host.


if we use --net=host container should get same ip as the host so we did nt use.

**Comment by dinghyskipper** [comment] 2016-05-10 21:28
Hi,

This issue re-appeared in a CentOS7 node. It can be reproduced consistently, no matter whether http or https is used and impacts curl as well as wget. 

It does not happen when the container is started with the --net=host option.

Can you please re-open this issue/advise what is needed to fix this?

Thank you

[gf@e3003 ~]$ docker run -t -i centos:6.7 /bin/bash

[root@9e7a1cc0660b /]# curl -o cm.rpm https://archive.cloudera.com/cm5/redhat/6/x86_64/cm/5.7.0/RPMS/x86_64/cloudera-manager-daemons-5.7.0-1.cm570.p0.76.el6.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 82  538M   82  443M    0     0  9876k      0  0:00:55  0:00:45  0:00:10 11.0M
curl: (56) SSL read: errno -5961
[root@9e7a1cc0660b /]# exit

[gf@e3003 ~]$ docker run --net=host -t -i centos:6.7 /bin/bash

[root@e3003 /]# curl -o cm.rpm https://archive.cloudera.com/cm5/redhat/6/x86_64/cm/5.7.0/RPMS/x86_64/cloudera-manager-daemons-5.7.0-1.cm570.p0.76.el6.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  538M  100  538M    0     0  6686k      0  0:01:22  0:01:22 --:--:-- 5031k
[root@e3003 /]#

[gf@e3003 ~]$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

[gf@e3003 ~]$ docker info
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 3
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:3-33607636-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.752 GB
 Data Space Total: 107.4 GB
 Data Space Available: 6.638 GB
 Metadata Space Used: 4.301 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.38 GiB
Name: e3003
ID: HB64:KRDX:UMF6:3PM5:UXMS:IJAO:42M4:S25Y:ZJPK:6Z72:6P22:KFJT
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

[gf@e3003 ~]$ cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)

[gf@e3003 ~]$ uname -a
Linux e3003 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment] 2016-05-10 21:47
@dinghyskipper according to this http://serverfault.com/a/555336, this could be a MTU issue; docker defaults to 1500, but older versions of docker tried to autodetect the MTU size, which resulted in issues if there's multiple routes. You can try setting the MTU manually, using the `--mtu` daemon option https://docs.docker.com/engine/reference/commandline/daemon/

**Comment by dinghyskipper** [comment] 2016-05-10 23:18
@thaJeztah - thanks for your feedback. I tried to set the MTU to 1500 and then to 9000. I have not changed it earlier, because on docker0 bridge it was set to 1500 by default. Unfortunately the issue is the same for both options - please see logs below. 

I have added a further curl error when used with http:
[root@371ded19d58b /]# curl -o cparcel http://archive.cloudera.com/cdh5/parcels/5.7.0/CDH-5.7.0-1.cdh5.7.0.p0.45-el6.parcel
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 37 1378M   37  515M    0     0   9.9M      0  0:02:18  0:00:51  0:01:27 11.1M
curl: (56) Failure when receiving data from the peer
[root@371ded19d58b /]

MTU 1500
----------------------------------------------------------------------------------------------------------------------------------------------------
â docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-05-11 01:00:01 CEST; 11s ago
     Docs: https://docs.docker.com
 Main PID: 26268 (docker)
   Memory: 20.0M
   CGroup: /system.slice/docker.service
           ââ26268 /usr/bin/docker daemon -H fd:// --insecure-registry e3000:5000 --mtu 1500
           ââ26274 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc

8: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 02:42:f3:47:72:c7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:f3ff:fe47:72c7/64 scope link
       valid_lft forever preferred_lft forever
       
[gf@e3003 ~]$ docker run -t -i centos:6.7 /bin/bash
[root@371ded19d58b /]# curl -o cm.rpm https://archive.cloudera.com/cm5/redhat/6/x86_64/cm/5.7.0/RPMS/x86_64/cloudera-manager-daemons-5.7.0-1.cm570.                                          p0.76.el6.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 75  538M   75  404M    0     0  8025k      0  0:01:08  0:00:51  0:00:17 11.1M
curl: (56) SSL read: errno -5961

MTU 9000
----------------------------------------------------------------------------------------------------------------------------------------------------

â docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-05-11 01:06:48 CEST; 4s ago
     Docs: https://docs.docker.com
 Main PID: 27237 (docker)
   Memory: 21.0M
   CGroup: /system.slice/docker.service
           ââ27237 /usr/bin/docker daemon -H fd:// --insecure-registry e3000:5000 --mtu 9000
           ââ27247 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc


8: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9000 qdisc noqueue state DOWN
    link/ether 02:42:f3:47:72:c7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:f3ff:fe47:72c7/64 scope link
       valid_lft forever preferred_lft forever


[gf@3003 ~]$ docker run -t -i centos:6.7 /bin/bash
[root@9bec6f12d0ab /]# curl -o cm.rpm https://archive.cloudera.com/cm5/redhat/6/x86_64/cm/5.7.0/RPMS/x86_64/cloudera-manager-daemons-5.7.0-1.cm570.p0.76.el6.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 89  538M   89  482M    0     0  10.9M      0  0:00:49  0:00:44  0:00:05 11.0M
curl: (56) SSL read: errno -5961

**Comment by thaJeztah** [comment] 2016-05-10 23:31
You'll probably need lower, e.g. http://muzso.hu/2009/05/17/how-to-determine-the-proper-mtu-size-with-icmp-pings

**Comment by dinghyskipper** [comment] 2016-05-13 14:47
hi @thaJeztah, I tried to lower it without luck, however, pings shows that 1500 is supported all through the path.
