### ISSUE TITLE
Error response from daemon: No command specified after image shrinking

### ISSUE THREAD

**Issue by Somebi** [docker/docker#20923] opened 2016-03-03 21:10 UTC
After running this:
docker export <CONTAINER ID> | docker import - some-image-name:latest

Docker throws:
docker@default:/$ docker run some-repo/some-image-name
Error response from daemon: No command specified

Is there some solution/workaround for this?

**Comment by thaJeztah** [comment] 2016-03-04 00:40
This is expected; `docker export` only [exports the *filesystem* data](https://docs.docker.com/engine/reference/commandline/export/) of an image, but *not* its configuration  (labels, env-vars, command).

If you want to export images *including* their configuration/properties, use docker save and load 
https://docs.docker.com/engine/reference/commandline/save/
https://docs.docker.com/engine/reference/commandline/load/


Please be aware that the GitHub issue tracker is **not** a support forum, but intended for tracking bugs and feature requests, for other questions use one of;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

Which are more suitable for this

I'm closing this issue, because this is not a bug or feature request, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-03-04 00:40 UTC

**Comment by Somebi** [comment] 2016-03-04 06:36
But it does not shrink/flatten/lessen image after save/load. Would be nice to know what will not work on export/import. Some best practice info in docs ot notices, to avoid corrupting image. Warning while trying to do so would nice too.
