### ISSUE TITLE
containers/create endpoint allows container creation without an image

### ISSUE THREAD

**Issue by TJNII** [docker/docker#14342] opened 2015-07-02 03:33 UTC
In API v1.18 the container/create endpoint will allow a container to be created without an Image.  Using the docker-api Ruby gem which is a wrapper around the API:

```
[69] pry(main)> c = Docker::Container.create()
Docker::Error::ServerError: No command specified
from /var/lib/gems/2.1.0/gems/docker-api-1.21.4/lib/docker/connection.rb:50:in `rescue in request'

[70] pry(main)> c = Docker::Container.create(Cmd: 'foo')
=> #<Docker::Container:0x0000000251cf78                 
 @connection=#<Docker::Connection:0x0000000243d0f8 @options={:socket=>"/var/run/docker.sock"}, @url="unix:///">,
 @id="fe22f2cf547203936038681c966d376dc8a56ff5619bd83ca5c463e055e31c7e",
 @info={"Warnings"=>nil, "id"=>"fe22f2cf547203936038681c966d376dc8a56ff5619bd83ca5c463e055e31c7e"}>

[71] pry(main)> c.json['Image']
=> ""                          
```

Note that there is error checking on Cmd, but apparently not on Image.  This broken container shows in docker ps -a as ':latest':

```
$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS              PORTS               NAMES
fe22f2cf5472        :latest                        "foo"                  3 minutes ago                                               hungry_lovelace     
```

This also triggers the image removal bug fixed in 71a499022904e1da074ded3e1ed874c1b75ccf23 as long as the broken container is present:

```
$ docker rmi debian:wheezy
Error response from daemon: could not find image: Prefix can't be empty
FATA[0000] Error: failed to remove one or more images   
```

To the best of my knowledge the Image argument is mandatory for the container/create endpoint and should be enforced by the server.

Full version details:
```
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Comment by TJNII** [comment] 2015-07-02 03:57
Requested BUG REPORT INFORMATION:

```
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
$ docker info
Containers: 3
Images: 269
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 281
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-2-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 7.729 GiB
Name: st-b4ec4504-f5d5-11e3-8256-db3b01ecff15.cpstick.rshscp.local
ID: N76A:JP5U:ZZYG:IWA7:AFKN:MBYR:SONO:P7Y4:UHTL:G245:ABYC:YIUZ
WARNING: No memory limit support
WARNING: No swap limit support
$ uname -a
Linux (hostname removed) 3.16-2-amd64 #1 SMP Debian 3.16.3-2 (2014-09-20) x86_64 GNU/Linux
```
Environment: Physical

Steps to reproduce:

* Send a POST request to /containers/create without Image but otherwise properly formed:
```
$ ncat -U /var/run/docker.sock 
POST /containers/create HTTP/1.1
Content-Type: application/json
Content-Length: 16

{ "Cmd": "foo" }
HTTP/1.1 201 Created
Content-Type: application/json
Date: Thu, 02 Jul 2015 03:51:31 GMT
Content-Length: 90

{"Id":"16d6e50747a4295213ceca5f4a9c31debe1b3ca5679ef76b54d589fea8ad7c07","Warnings":null}
```

* A container without a image will be created:

```
$ docker inspect 16d6e50747a4295213ceca5f4a9c31debe1b3ca5679ef76b54d589fea8ad7c07
[{                           
    "AppArmorProfile": "",   
    "Args": [],              
    "Config": {              
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [             
            "foo"            
        ],                   
        "CpuShares": 0,      
        "Cpuset": "",        
        "Domainname": "",    
        "Entrypoint": null,  
        "Env": null,         
        "ExposedPorts": null,
        "Hostname": "16d6e50747a4",
        "Image": "",         
        "Labels": null,      
        "MacAddress": "",    
        "Memory": 0,         
        "MemorySwap": 0,     
        "NetworkDisabled": false,
        "OnBuild": null,     
        "OpenStdin": false,  
        "PortSpecs": null,   
        "StdinOnce": false,  
        "Tty": false,        
        "User": "",          
        "Volumes": null,     
        "WorkingDir": ""     
    },                       
    "Created": "2015-07-02T03:51:31.17262407Z",
    "Driver": "aufs",        
    "ExecDriver": "native-0.2",
    "ExecIDs": null,         
    "HostConfig": {          
        "Binds": null,       
        "CapAdd": null,      
        "CapDrop": null,     
        "CgroupParent": "",  
        "ContainerIDFile": "",
        "CpuShares": 0,      
        "CpusetCpus": "",
        "Devices": null,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkMode": "",
        "PidMode": "",
        "PortBindings": null,
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "SecurityOpt": null,
        "Ulimits": null,
        "VolumesFrom": null
    },
    "HostnamePath": "",
    "HostsPath": "",
    "Id": "16d6e50747a4295213ceca5f4a9c31debe1b3ca5679ef76b54d589fea8ad7c07",
    "Image": "",
    "LogPath": "",
    "MountLabel": "",
    "Name": "/furious_darwin",
    "NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",    
        "PortMapping": null, 
        "Ports": null        
    },                       
    "Path": "foo",           
    "ProcessLabel": "",      
    "ResolvConfPath": "",    
    "RestartCount": 0,       
    "State": {               
        "Dead": false,       
        "Error": "",         
        "ExitCode": 0,       
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,  
        "Paused": false,     
        "Pid": 0,            
        "Restarting": false, 
        "Running": false,    
        "StartedAt": "0001-01-01T00:00:00Z"
    },                       
    "Volumes": {},           
    "VolumesRW": {}          
}                            
]

  $ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS              PORTS                                              NAMES
16d6e50747a4        :latest                        "foo"                  2 minutes ago                                                                              furious_darwin                       
```

On releases without 71a499022904e1da074ded3e1ed874c1b75ccf23 docker rmi will now be broken as long as the image exists:

```
$ docker rmi centos:centos6
Error response from daemon: could not find image: Prefix can't be empty
FATA[0000] Error: failed to remove one or more images   
$ docker rm 16d6e50747a4295213ceca5f4a9c31debe1b3ca5679ef76b54d589fea8ad7c07
16d6e50747a4295213ceca5f4a9c31debe1b3ca5679ef76b54d589fea8ad7c07
$ docker rmi centos:centos6
Untagged: centos:centos6
Deleted: f6808a3e4d9e80a655ec625e38b869ed8a614611e4d0073aeff23be841c9fcff
```

Expected behavior: The POST to /containers/create should return a 400 Bad Request and not create a broken container.

**Comment by LK4D4** [comment] 2015-07-02 15:35
@TJNII Yup, you're right, thanks for report.
I think this was introduced by @jlhawn in "scratch as special word" PR.

**Comment by jlhawn** [comment] 2015-07-02 16:07
Yes, this is expected behavior (since I think Docker 1.5?). It allows you to create an image `FROM scratch` which means that the container should have an empty rootfs directory (aside from the host config layer that Docker sets up).

**Comment by jlhawn** [comment] 2015-07-02 16:11
As for the `docker ps` output and `docker rmi` issues you reported, those are things that should be fixed.

**Comment by jfrazelle** [comment] 2015-07-10 22:08
can you please change the title to more appropriately describe the problems with ps amd rmi

**Closed** 2016-03-03 23:14 UTC
