### ISSUE TITLE
Docker daemon crash - corrupted double-linked list

### ISSUE THREAD

**Issue by cen1** [docker/docker#31455] opened 2017-03-01 15:54 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**
Hard crash of dockerd

**Steps to reproduce the issue:**
Random crash, can't reproduce yet

**Additional information you deem important (e.g. issue happens only occasionally):**
Twice today out of nowhere after an hour of restart.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 35
 Running: 0
 Paused: 0
 Stopped: 35
Images: 52
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-40524435-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 27.45 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.23 GB
 Metadata Space Used: 30.38 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.117 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.7 GiB
Name: staging-internal-ccm.localdomain
ID: RNVN:UTPN:LR37:JCX6:MOEQ:V3DO:ABUV:INHB:KRIY:O4ZX:XUZP:EDLA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OVirt virtual machine, CentOS 7, install from docker repo
[docker_dump.txt](https://github.com/docker/docker/files/811236/docker_dump.txt)

**Comment by thaJeztah** [comment] 2017-03-01 16:29
Thanks for reporting! This looks like a duplicate of https://github.com/docker/docker/issues/30433 and https://github.com/docker/docker/issues/30564, and should be resolved by #31263 and #31231, which will be in the upcoming release (most likely this week)

**Comment by thaJeztah** [comment] 2017-03-01 16:30
I'll close this issue, because this is already fixed, but thanks again for reporting, and feel free to continue the conversation

**Closed by thaJeztah** 2017-03-01 16:30 UTC
Labels: area/daemon, kind/bug, version/1.13

**Comment by cen1** [comment] 2017-03-01 16:34
Sorry for duplicate, "docker corrupted double-linked list" returned nothing in my searches. Eagerly expecting the release.

**Comment by thaJeztah** [comment] 2017-03-01 17:14
Yes, GitHub search isn't great, especially with a big repo like this. No worries, it's good that you reported the issue, thanks for that!
