### ISSUE TITLE
Cannot destroy container - Driver vfs failed to remove root filesystem

### ISSUE THREAD

**Issue by MoshiBin** [docker/docker#12310] opened 2015-04-12 08:35 UTC
Description of problem:

My machine is doing lots of `docker run` and `docker rm`, and eventually It'll accumulate some containers that cannot be removed, due to errors like this:

```
Error: Cannot destroy container 3778547e1b5d: Driver vfs failed to remove root filesystem 3778547e1b5dd437fdd7c69373d887e729421ca05af470e27808fa42e3265039: stat /var/lib/docker/vfs/dir/3778547e1b5dd437fdd7c69373d887e729421ca05af470e27808fa42e3265039: no such file or directory
```

`docker version`:
```
Client version: 0.9.0
Go version (client): go1.2
Git commit (client): 2b3fdf2/0.9.0
Server version: 0.9.0
Git commit (server): 2b3fdf2/0.9.0
Go version (server): go1.2
```

`docker info`:
```
Containers: 1
Images: 183
Driver: vfs
Debug mode (server): false
Debug mode (client): true
Fds: 11
Goroutines: 12
Execution Driver: lxc-0.9.0
EventsListeners: 0
Kernel Version: 2.6.32-220.13.1.el6.centos.plus.x86_64
Init SHA1: 373c75490962701edf3a97ad89ef55f25f1cee7b
Init Path: /usr/libexec/docker/dockerinit
```

Environment details (AWS, VirtualBox, physical, etc.):
VM running on ESXi, CentOS 6.2. `uname -a`: `Linux 2.6.32-220.13.1.el6.centos.plus.x86_64 #1 SMP Wed Apr 18 02:32:59 BST 2012 x86_64 x86_64 x86_64 GNU/Linux`

How reproducible:
Happens over time, cannot reproduce a single case.

**Comment by thaJeztah** [comment] 2015-04-12 09:54
@MoshiBin you're running a really old version of docker (0.9). Could you please test if you're still able to reproduce this on the current 1.5 release or the 1.6 release candidate?  (https://github.com/docker/docker/pull/11635#issuecomment-90205104)

In addition, you're running on CentOS 6.2, which isn't supported (6.5 or higher is required, see https://docs.docker.com/installation/centos/)

And, finally, I see you're using the `vfs` driver, which isn't really recommended.

I hope you're able to resolve this with the instructions above.

I'm going to close this issue, because you're running Docker on an unsupported system, but feel free to comment after that and report if you were able to resolve your issue.

**Closed by thaJeztah** 2015-04-12 09:54 UTC
