### ISSUE TITLE
The info endpoint should export networking information

### ISSUE THREAD

**Issue by achanda** [docker/docker#10952] opened 2015-02-23 18:45 UTC
Currently, the `/info` endpoint exports compute and storage information, but no networking information. It should export all available network configurations like name of the bridge, CIDR being used etc. These should also be printed in the `docker info` command. A networking solution on top of Docker might find this information useful.

**Comment by jfrazelle** [comment] 2015-02-23 22:11
closing as duplicate of #3909, please continue the conversation there

**Closed by jfrazelle** 2015-02-23 22:11 UTC
