### ISSUE TITLE
Docker update memory constraints not honored

### ISSUE THREAD

**Issue by wouterhund** [docker/docker#20144] opened 2016-02-09 12:30 UTC
# BUG REPORT INFORMATION

`docker version`:
````
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.1.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   a0fd82b
 Built:        Thu Feb  4 08:55:18 UTC 2016
 OS/Arch:      linux/amd64
````
`docker info`:
````
Containers: 7
 Running: 5
 Paused: 0
 Stopped: 2
Images: 27
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 REDACTED: REDACTED:2376
  └ Status: Healthy
  └ Containers: 7
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 12 GiB / 8.174 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-71-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-02-09T12:34:01Z
Plugins: 
 Volume: 
 Network: 
Kernel Version: 3.13.0-65-generic
Operating System: linux
Architecture: amd64
CPUs: 8
Total Memory: 8.174 GiB
Name: REDACTED
````

Provide additional environment details (AWS, VirtualBox, physical, etc.): Using Docker Swarm, but Swarm contains only one node so far

List the steps to reproduce the issue:

1. Create container with memory constraint of 2g (`docker run -m 2g ...`)
2. Stop the container
3. `docker update -m 4m containerId`
4. `docker update -m 4g containerId`
5. `docker start containerId`
6. Repeat these steps until you have more containers running than your host can support. In my case 3*4g=12gb on a host with 8gb of memory.

Describe the results you received: Docker will start more containers than host has available memory

Describe the results you expected: Docker should not start more containers than the host has resources available for

**Comment by phemmer** [comment] 2016-02-09 13:21
This setting isn't supposed to prevent docker from launching containers once the cumulative total of memory limits exceeds the host's memory. Is there something in the documentation that gave you the idea otherwise?

Also:

> Create container with memory constraint of 2g (docker run -m 2g ...)
> Stop the container
> docker update -m 4m containerId
> docker update -m 2g containerId
> docker start containerId

You effectively didn't change anything. You started the container with a 2g limit, put it at 4m, and then put it back to 2g.

**Comment by wouterhund** [comment] 2016-02-09 13:22
@phemmer Right. You should repeat the entire steps three-four times until the cumulative total of memory exceeds my host memory. See the output of docker info above: `Reserved Memory: 12 GiB / 8.174 GiB`

**Comment by thaJeztah** [comment] 2016-03-01 23:42
This is not a bug; memory limits apply to containers individually, i.e., it only limits what a container is allowed to consume. The total limit of all containers can exceed the available of the system. I don't think the documentation suggests that this isn't possible, but perhaps a note can be added if you think that'd clarify this; https://docs.docker.com/engine/reference/run/#user-memory-constraints

I'll close this issue, because I think this works correctly, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-03-01 23:42 UTC

**Comment by wouterhund** [comment] 2016-03-03 20:46
@thaJeztah Ah! I was under the impression that the docker swarm spread strategy would refuse to pick nodes that were overloaded. I could have sworn it worked this way in the past, but perhaps I am mistaken.

**Comment by thaJeztah** [comment] 2016-03-03 20:53
@wouterhund point is there's no real memory *reservation* here, only a *limit*, so even though a container may use up-to the given amount, it is not guaranteed to *get* it. It's possible there's an issue with the way Swarm schedules containers here, so if you think there's an issue, please open a ticket in the Docker Swarm issue tracker https://github.com/docker/swarm/issues

**Comment by wouterhund** [comment] 2016-03-03 21:19
@thaJeztah Ah, docker info (when using swarm) calls it reserved memory, so that might also have thrown me off. I'll give it an extra hard look, but after your explanation I do not believe that any actual issues exist, since it works as you describe. Thank you.

**Comment by thaJeztah** [comment] 2016-03-03 23:32
You're welcome!
