### ISSUE TITLE
Docker 1.12.0 Swarm Networks Not Showing up on Worker Nodes

### ISSUE THREAD

**Issue by und1sk0** [docker/docker#25456] opened 2016-08-05 23:06 UTC
**Output of `docker version`:**

```
>>> Swarm Master
root@ip-10-12-8-111:~# docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

>>> Swarm "Worker"
root@ip-10-12-10-206:~# docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 42
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /docker/aufs
 Backing Filesystem: extfs
 Dirs: 51
 Dirperm1 Supported: false
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: active
 NodeID: d9v07hscnb3plwp2ud1yfb1we
 Is Manager: true
 ClusterID: 1zz46zkg8eu10row1fs3nyz3b
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 10.12.8.111
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-10-12-8-111
ID: E5IS:X3AR:V66J:4CDX:PGMI:XLAA:U725:S7FE:MBN2:B3HI:IDD5:IMBW
Docker Root Dir: /docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 registry.XXXXX
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS VPC, same AZ, same subnet, SG rules (relevant): permit TCP/UDP 2377 from same group, permit TCP/UDP 4789 from same group, permit TCP/UDP 7946 from same group.

**Steps to reproduce the issue:**
1. init a swarm and create an overlay network: ```docker swarm init && docker network create -d overlay --subnet 192.168.32.0/25 backend```
2. join two workers, ```docker network ls``` on those hosts does not see the backend network
3. promote works, network is now seen

**Describe the results you received:**
```
root@ip-10-12-8-111:~# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
3b643796f288        bridge              bridge              local               
c854daf36dc1        docker_gwbridge     bridge              local               
95m46i1zinny        epsilon-backend     overlay             swarm               
a3rkkw7mth7p        epsilon-swarm       overlay             swarm               
10b22c84d1fe        host                host                local               
61q0ybrjf2qy        ingress             overlay             swarm               
31ee8c6c7f7d        none                null                local                   
root@ip-10-12-8-111:~# docker node ls
ID                           HOSTNAME         STATUS  AVAILABILITY  MANAGER STATUS
2i549xsjeq09g6ylksl4ndrvd    ip-10-12-10-206  Ready   Active        
d9v07hscnb3plwp2ud1yfb1we *  ip-10-12-8-111   Ready   Active        Leader
eqwpaervcy2qfltqbsgw5zru6    ip-10-12-10-207  Ready   Active        
```

On the worker:
```
root@ip-10-12-10-206:~# bash -x join.sh 
+ docker swarm join --token SWMTKN-1-b00tsandcatsandb00tsandcatsandb00tsandcats 10.12.8.111:2377
This node joined a swarm as a worker.
root@ip-10-12-10-206:~# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
4905ac56d65a        bridge              bridge              local               
036f955f6627        docker_gwbridge     bridge              local               
10b22c84d1fe        host                host                local               
61q0ybrjf2qy        ingress             overlay             swarm               
31ee8c6c7f7d        none                null                local               
```

After promotion:
```             
root@ip-10-12-10-206:~# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
4905ac56d65a        bridge              bridge              local               
036f955f6627        docker_gwbridge     bridge              local               
95m46i1zinny        epsilon-backend     overlay             swarm               
a3rkkw7mth7p        epsilon-swarm       overlay             swarm               
10b22c84d1fe        host                host                local               
61q0ybrjf2qy        ingress             overlay             swarm               
31ee8c6c7f7d        none                null                local
```

**Describe the results you expected:**
I expect overlay networks in swarm to be available to workers.

**Additional information you deem important (e.g. issue happens only occasionally):**
```
root@ip-10-12-10-206:~# uname -a
Linux ip-10-12-10-206 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@ip-10-12-8-111:~# ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 06:5c:45:5f:d3:f5  
          inet addr:10.12.8.111  Bcast:10.12.11.255  Mask:255.255.252.0
          inet6 addr: fe80::45c:45ff:fe5f:d3f5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:1638513 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1158208 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1062424645 (1.0 GB)  TX bytes:696419586 (696.4 MB)
```

**Comment by prateek-1708** [comment] 2016-08-07 13:10
👍  facing the same issue ... seems as if the swarm cluster is unaware of the new overlay network.

**Comment by thaJeztah** [comment] 2016-08-07 13:59
This is expected; the network is automatically extended / becomes available automatically once a service using that network is deployed in a node. This is by design; the network is not extended to all nodes by default is not needed, this saves resources (imagine a 2000 node cluster, but a service using the network only being deployed on 2 nodes).

I'll close this issue because this is not a bug, but thanks for reporting, and happy to continue he conversation here

**Closed by thaJeztah** 2016-08-07 13:59 UTC
Labels: version/1.12

**Comment by und1sk0** [comment] 2016-08-11 07:33
Son of a gun, works for me. Thanks.

**Comment by bloo** [comment] 2016-09-30 20:20
I'm actually getting a similar error where running a container (via `run` or `service create` with a predefined overlay network fails because it can't find the network. I tried `service create` on the Swarm manager, and `docker run` on both manager and worker.

```
docker run --rm -it --network clusternet nginx:1.9.12 bash
docker: Error response from daemon: network clusternet not found.
```

From the manager:
```
docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
940b97960d6e        bridge              bridge              local
4atw75pcu2m4        clusternet          overlay             swarm
bc2d2761040d        docker_gwbridge     bridge              local
5c9d9e04aec0        host                host                local
0yvqng9w8c6v        ingress             overlay             swarm
6f4a96980cd4        none                null                local
```

and:

```
docker network rm clusternet
Error response from daemon: rpc error: code = 9 desc = network 4atw75pcu2m4o1g5q1k4jw29k is in use
```

.. so it exists, previously started (a week ago) services are running on it, but creating a new service on a week old Swarm can't access it.

**Comment by thaJeztah** [comment] 2016-09-30 20:29
@bloo in docker 1.12 with swarm mode enabled, "Swarm" scoped networks (see the "SCOPE" column) cannot be used for `docker run`, only for services. 

Allowing `docker run` to use swarm-scoped networks is being tracked by https://github.com/docker/docker/issues/23901, and is already implemented on "master" through https://github.com/docker/docker/pull/25962, which will be in the upcoming 1.13 release.

The error message is due to swarm-scoped networks working different than a "regular" network. With swarm-scoped networks, you create/define the network, but it is only expanded to those nodes that actually have a service running on _that_ node that is connected to it. There is a small bug in the way error messages are handled for that (I opened https://github.com/docker/docker/issues/27066 for this)

**Comment by bloo** [comment] 2016-09-30 20:39
@thaJeztah thanks for the background - `docker run` docs here https://docs.docker.com/engine/reference/run/#/network-settings - mention: `--network="bridge"` ... `'<network-name>|<network-id>': connect to a user-defined network` so I had assumed it could connect to a named network.

This doesn't explain why creating a new service on a worker node (one that was indeed part of the swarm) couldn't find the network either. Note - I'm using a `--constraint` to pick which node the service comes up on. I tore down my swarm and retrying it all from scratch..

**Comment by thaJeztah** [comment] 2016-09-30 20:43
> This doesn't explain why creating a new service on a worker node (one that was indeed part of the swarm) couldn't find the network either.

That's a good question; let us know starting from scratch works out.

**Comment by bloo** [comment] 2016-09-30 20:44
@thaJeztah still unable to find the network. Tips for debugging?

**Comment by bloo** [comment] 2016-09-30 20:54
@thaJeztah turns out my nginx conf couldn't find an upstream server by DNS name, and was failing to start. I was getting errors for both exit status code AND couldn't find `clusternet` network. Temporarily removing the upstream section of my nginx conf so that my container starts normally allowed it to start on the overlay network. Curious error messages (also time to investigate how to reference Swarm services by DNS) - looks like I'm ok for now.

**Comment by thaJeztah** [comment] 2016-09-30 20:58
Ok, for NGINX, take into account that the free version uses a DNS cache, and only resolves IP addresses upon start, so if an IP-address changes, it won't pick up those changes. Only the paid-for version does that (https://tenzer.dk/nginx-with-dynamic-upstreams/)

For further issues; I'm not the best at debugging the networking things, but at least make sure that;

- when initializing the swarm, to use the `--advertise-addr` option if your machine has multiple interfaces, or multiple IP-addresses
- try the release candidate for 1.12.2; https://github.com/docker/docker/releases/tag/v1.12.2-rc1, as it contains a lot of improvements related to networking
- make sure the nodes are able to communicate with each other; and the required ports are opened (TCP port 2377, TCP and UDP port 7946, TCP and UDP port 4789, see https://docs.docker.com/engine/swarm/swarm-tutorial/#/open-ports-between-the-hosts)

**Comment by adriano-fonseca** [comment] 2017-02-08 23:54
I am facing a similar issue, but working with 1.13 Docker Engine in swarm mode.

Client:
 Version:      1.13.0
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

I have created a overlay network and I try to create a service with some replicas in order to distribute some containers across my nodes. One in AWS and another in Digital Ocean.

```
adriano@adriano-LNX:~/aws$ docker-machine ls
NAME        ACTIVE   DRIVER         STATE     URL                         SWARM   DOCKER    ERRORS
swmaster1   *        amazonec2      Running   tcp://52.67.216.215:2376            v1.13.1   
swnode3     -        digitalocean   Running   tcp://138.197.34.228:2376           v1.13.1   

adriano@adriano-LNX:~/aws$ docker node ls
ID                           HOSTNAME   STATUS  AVAILABILITY  MANAGER STATUS
2v8m3bzb260taomn9a4sn0pwx *  swmaster1  Ready   Active        Leader
ps8dym7j3bcrjtc8604ejdnmy    swnode3    Ready   Active        
```


Master network list


```
adriano@adriano-LNX:~/aws$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
53955fb1b008        bridge              bridge              local
4f2926843b7f        docker_gwbridge     bridge              local
5c9a09df14de        host                host                local
yqfi000u93xb        ingress             overlay             swarm
9wmu9wdbwf76        multi-cloud         overlay             swarm
54367d9817ba        none                null                local
```

Worker network list (without multi-cloud)

```
adriano@adriano-LNX:~/aws$ docker-machine ssh swnode3 docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
756699a13d3a        bridge              bridge              local
5805fff938a3        docker_gwbridge     bridge              local
4bb6addf4664        host                host                local
yqfi000u93xb        ingress             overlay             swarm
7c4a7fa8a06d        none                null                local
```

I have read your considerations @thaJeztah, about the overlay network not being created  by default in all nodes. However, when I try to deploy my service:

```
docker service create --name croc -p 8080:8080 --replicas 4 adrianofonseca/croc-hunter --network multi-cloud
```

But ther service are not runnin by the follow error:

```
adriano@adriano-LNX:~/aws$ docker service ps croc 
ID            NAME        IMAGE                              NODE       DESIRED STATE  CURRENT STATE                    ERROR                             PORTS
mt11avw0jr80  croc.1      adrianofonseca/croc-hunter:latest  swnode3    Running        Starting less than a second ago                                    
9yroi9fl0z0e   \_ croc.1  adrianofonseca/croc-hunter:latest  swmaster1  Shutdown       Failed 5 seconds ago             "starting container failed: oc…"  
lkaq3i7gbyf8   \_ croc.1  adrianofonseca/croc-hunter:latest  swnode3    Shutdown       Failed 11 seconds ago            "starting container failed: oc…"  
t3llbv0o6dvy  croc.2      adrianofonseca/croc-hunter:latest  swnode3    Running        Starting 1 second ago                                              
y5uvydxjio6z   \_ croc.2  adrianofonseca/croc-hunter:latest  swmaster1  Shutdown       Failed 6 seconds ago             "starting container failed: oc…"  
xv3cshtr3vce   \_ croc.2  adrianofonseca/croc-hunter:latest  swmaster1  Shutdown       Failed 12 seconds ago            "starting container failed: oc…"  
jnzw0y4hhnh0  croc.3      adrianofonseca/croc-hunter:latest  swnode3    Ready          Ready 4 seconds ago                                                
59vst3scqvt7   \_ croc.3  adrianofonseca/croc-hunter:latest  swmaster1  Shutdown       Failed 4 seconds ago             "starting container failed: oc…"  
xpqfjobw2vwq   \_ croc.3  adrianofonseca/croc-hunter:latest  swnode3    Shutdown       Failed 10 seconds ago            "starting container failed: oc…"  
kcfw30tx3l33  croc.4      adrianofonseca/croc-hunter:latest  swnode3    Running        Ready 5 seconds ago                                                
xoi7zt6jvxma   \_ croc.4  adrianofonseca/croc-hunter:latest  swmaster1  Shutdown       Failed 5 seconds ago             "starting container failed: oc…"  
rs77w6jx3g1y   \_ croc.4  adrianofonseca/croc-hunter:latest  swmaster1  Shutdown       Failed 12 seconds ago            "starting container failed: oc…"  
```

If I get the logs in one of containers that ha 'not ran I got:

**container_linux.go:247: starting container process caused "exec: \"--network\": executable file not found in $PATH"**

Interesting enough, if do the same withou passing the network, I mean using ingress, which is the default, everything works fine.

Any Ideas?

**Comment by thaJeztah** [comment] 2017-02-09 01:38
@adriano-fonseca other than being on a different cloud provider, are the nodes exactly equal? (same docker version, same distro, storage driver, and SELinux/AppArmor configuration). Are tasks all failing on either DigitalOcean, AWS, or on both?

**Comment by adriano-fonseca** [comment] 2017-02-09 01:53
@thaJeztah, that are all really good questions, actually they were the same. However, I have decided put everything down and to start from begin and surprisingly, it works. Thank you to answer me so quickly. I have never spoken with you before, but I see how active you are in this community, something that I am really glad for. More than once, you have helped me, just I having read your answer for other users. Thank you again.

**Comment by thaJeztah** [comment] 2017-02-09 03:55
You're more than welcome! :blush:

**Comment by smnajjar** [comment] 2017-03-23 01:02
@adriano-fonseca The problem was with your command:

docker service create --name croc -p 8080:8080 --replicas 4 **adrianofonseca/croc-hunter** _--network multi-cloud_

You had your docker network argument after the image "adrianofonseca/croc-hunter" which also takes arguments.
