### ISSUE TITLE
Red-Black tree by Golang

### ISSUE THREAD

**Issue by HuKeping** [docker/docker#13872] opened 2015-06-11 01:44 UTC
Hi there,
 I make a RB tree implementation on https://github.com/HuKeping/rbtree 
and have made a simple test for inserting  and deleting  1,000.000 nodes and record the time it cost, seems quite good, FYI
Rbtree:1000000
Befor Insert:2015-06-03 05:36:38.202131403 +0800 CST
After Insert:2015-06-03 05:36:40.3821364 +0800 CST
After delete:2015-06-03 05:36:41.586501826 +0800 CST
time2 - time1: 2.180004997
time3 - time2: 1.204365426

Maybe Docker can use it on somewhere

**Comment by thaJeztah** [comment] 2015-06-11 18:39
Hi @HuKeping, I'm going to close this issue, because this is not a bug or feature request.

Feel free, however to discuss this in the #docker-dev IRC channel, to see if it's useful in Docker

Thanks!

**Closed by thaJeztah** 2015-06-11 18:39 UTC
