### ISSUE TITLE
Problem in Scripts/start.sh at OSX

### ISSUE THREAD

**Issue by theigel** [docker/docker#16479] opened 2015-09-22 10:44 UTC
At freshly installed Docker at OSX, running Quickstart Terminal app, I get an error at the very end:
```
/bin/bash: /bin/bash: cannot execute binary file
```

It is caused by the following code in the `/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh`:
```
USER_SHELL=$(dscl /Search -read /Users/$USER UserShell | awk '{print $2}')
```
the problem being that in my case there are two similar lines, not one, returned by `dscl`:
```
theigel$ dscl /Search -read /Users/$USER UserShell 
UserShell: /bin/bash
UserShell: /bin/bash
```
, so the USER_SHELL becomes `/bin/bash /bin/bash`.

A trivial fix (not sure if it is the best one) would be adding `head -1`:
```
USER_SHELL=$(dscl /Search -read /Users/$USER UserShell | head -1 | awk '{print $2}')
```

**Comment by haanns** [comment] 2015-09-23 16:59
@theigel that trivial fix was very helpful. Thank you so much for posting it!

**Comment by huguesfontenelle** [comment] 2015-09-25 13:36
@theigel useful for me too, thank you.

## key information

```
 $ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: QHDD:M7SJ:5GLH:4IAR:6NLJ:K7OK:WSU5:GLI6:AHU6:E35D:QNVM:3E73
Debug mode (server): true
File Descriptors: 11
Goroutines: 17
System Time: 2015-09-25T13:30:48.578814569Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
huguesfo@pcus392 ~
```

```
$ uname -a
Darwin pcus392.uio.no 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
```

## List the steps to reproduce the issue

1. fresh install
2. start `Docker Quickstart Terminal` from menu

##  Describe the results you received:

```
/bin/bash: /bin/bash: cannot execute binary file
```

And when trying to run docker commands:
```
$ docker images
Get http:///var/run/docker.sock/v1.20/images/json: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```
 
## Describe the results you expected:

Expecting to work out of the box without spending a day trying to figure it out.

**Comment by sirgoatofboy** [comment] 2015-09-29 08:55
Thanks again for the trivial fix @theigel

**Comment by davigge** [comment] 2015-09-30 03:31
The fix was not working for me but my issue is not the same but so looks similar.
Is there quick fix ?

 "/bin/tcsh: /bin/tcsh: cannot execute binary file

docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com

/bin/tcsh: /bin/tcsh: cannot execute binary file
me:~ me$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

**Comment by Baresse** [comment] 2015-09-30 12:01
@theigel, Thanks a lot for the fix.

**Comment by theigel** [comment] 2015-09-30 17:15
@davigge , it should work. If you run `dscl /Search -read /Users/$USER UserShell | head -1`, do you get one line or more? If you get one, then just re-check you've patched the right file. If you get two, hmmmm, try `head -n 1` instead, maybe.

**Comment by mrryanjohnston** [comment] 2015-09-30 22:59
A fix / pr was posted for this issue: https://github.com/docker/toolbox/issues/210

**Comment by davigge** [comment] 2015-10-01 03:28
@theigel, Thanks a lot it works for me at the end

**Comment by illern** [comment] 2015-10-01 09:32
Worked fine for me too, @theigel - thanks.

**Comment by jaydreyer** [comment] 2015-10-01 19:16
Worked for me, too. Thanks @theigel !

**Comment by thaJeztah** [comment] 2015-10-01 22:14
@theigel thanks for reporting! Because this really is an issue in docker toolbox, and already tracked by https://github.com/docker/toolbox/issues/210, I'm going to close this issue here

For those wanting to follow progress on this, please subscribe to https://github.com/docker/toolbox/issues/210 (using the subscribe button on that issue) thanks!

**Closed by thaJeztah** 2015-10-01 22:14 UTC
