### ISSUE TITLE
Docker freeze

### ISSUE THREAD

**Issue by ohade** [docker/docker#16245] opened 2015-09-11 20:48 UTC
the architecture is simple,
I have a small bash script that orchestrate two types of containers:
1 member of type "1" talks to another member of type "2". about 15 containers of each type.
When I detect that a member of type "2" (or "1") died, i kill the other one and raise them again.

the environment is Amazon ec2, 8 core, ubuntu 14.04.

After some period of time, when trying to do 'docker ps', i get no response. I think that the problem is the amount of times i issue 'docker stop' command. when i did 'docker kill' instead, the problem occurs faster.
Reading the documentation i see that 'docker stop' command coincide with what i see in the docker.log - which is a lot of docker kill (this is what happens when a container does not respond to a 'docker stop' command).

Is there a problem with the docker stop/kill - and the docker memory management?

I looked in the docker.log
and in the docker info - when it was still possible, and i don't see anything out of the ordinary.
could it be that i raised to many containers? i used to raise up to 60 containers and it worked great.

How can i debug this?

**Comment by thaJeztah** [comment] 2015-09-12 16:09
Could you;

- provide the information that @GordonTheTurtle requested
- provide a minimum test-case, describing the exact steps, so that we can try to reproduce your issue

Thanks!

**Comment by ohade** [comment] 2015-09-13 08:06
Hi @GordonTheTurtle and @thaJeztah,

I had the problem reproduce on version 1.8.1, i am now testing to see if it reproduce on 1.8.2, but the information you requested is:
docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
-------------------------------
docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
-------------------------------
uname -a
Linux ip-10-229-76-56 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
-------------------------------
Env:
amazon ec2, m3.xlarge, ubuntu 14.04


steps (as described in the first section):
the architecture is simple,
I have a small bash script that orchestrate two types of containers:
1 member of type "1" talks to another member of type "2". about 15 containers of each type.
When I detect that a member of type "2" (or "1") died, i kill the other one and raise them again.

After some period of time, when trying to do 'docker ps' (or 'docker info' or docker images'...), i get no response. I think that the problem is the amount of times i issue 'docker stop' command. when i did 'docker kill' instead, the problem occurs faster.
Reading the documentation i see that 'docker stop' command coincide with what i see in the docker.log - which is a lot of docker kill (this is what happens when a container does not respond to a 'docker stop' command).

I think a test case that start and stop containers for a few hours will reproduce what i am experiencing.

**Comment by thaJeztah** [comment] 2015-09-13 10:06
> When I detect that a member of type "2" (or "1") died, i kill the other one and raise them again.

Do you have any idea *why* those containers died? Is it possible that your system is running out of memory, and the containers get "oom" killed by the kernel? Have you put [memory constraints](https://docs.docker.com/reference/run/#memory-constraints) on the container?

To check if the container was "oom killed" by the kernel, you can `docker inspect` the container that died, and check for the `OOMKilled` field in the output.


> Is there a problem with the docker stop/kill - and the docker memory management?

Also, see the above; if there are no restrictions on the amount of memory the containers use, and your system is running out of memory, the kernel starts to kill random processes; one of those processes can be the docker daemon.

> Reading the documentation i see that 'docker stop' command coincide with what i see in the docker.log - which is a lot of docker kill (this is what happens when a container does not respond to a 'docker stop' command).

If a container does not respond to a `SIGTERM` within 10 seconds, docker will send a `SIGTERM` (see https://github.com/docker/docker/pull/2432) to the main process in the container. Ideally, your containers should respond to a `SIGTERM`; what's running in those containers? Does the main process also start new sub processes? If it does, there's also a chance that those processes don't get killed if the container receives a `SIGKILL`.

**Comment by ohade** [comment] 2015-09-14 12:19
Yes, I forgot to mention that, 
I use two containers that are not managing there memory usage, and so there recommendation is to limit there memory usage. That's why they are terminating pretty frequently.

**Comment by thaJeztah** [comment] 2015-09-14 16:08
> and so there recommendation is to limit there memory usage. That's why they are terminating pretty frequently.

Yes, that's really recommended; when setting a memory-limit, you make sure that the kernel will kill the *container*, and not the *daemon*. There are more options to restrict resources; see [Runtime constraints on resources](http://docs.docker.com/reference/run/#runtime-constraints-on-resources).


I'm going to close this issue, because I think this is not a bug in docker, but the result of not limiting the resources of containers, resulting in the daemon being killed by the kernel.

I *do* hope that my comments help you to resolve this issue; feel free to comment here after I've closed.

**Comment by ohade** [comment] 2015-09-14 18:05
I opened a issue on "Docker freeze" and you closed it on "result of not limiting the resources of containers, resulting in the daemon being killed by the kernel"

I don't have a problem with closing the issue, because my main problem is not being able to identify the problem, and that is what i really want.
I don't have a problem with containers dying on me.
I have a problem with the docker freezing on me and i don't have any indication why this thing is happening. 

htop command doesn't show any unusual strain on resources. 
df -h, doesn't show hard disc choking.
the docker client simply stuck.

**Comment by thaJeztah** [comment] 2015-09-14 18:11
Apologies; I mistakenly interpreted your last comment, that the daemon process was actually *killed* (because containers caused the machine to oom). I'll reopen :+1:

**Comment by ohade** [comment] 2015-09-16 08:36
thanks!
Do you have any diagnostics i can run to try and localise the problem?

**Comment by ohade** [comment] 2015-09-16 12:49
@thaJeztah you mentioned that if the main process in the container has spawned another process, it will not be killed ones a sigkill is send (if the builder of the image did not bother to catch that signal and clean up after him ), what happens to that other process? could it be that it linger on and they are all accumulating in the machine? is there a way to verify this?

**Comment by ohade** [comment] 2015-09-20 07:52
I found other issue that looks identical to my problem:
#13885

should you now close this issue?

**Comment by thaJeztah** [comment] 2015-09-20 13:14
@ohade if you think it's the same issue, I'll close this one, thanks! Feel free to comment here though, if it turns out to be a different problem, then I'll reopen

**Closed by thaJeztah** 2015-09-20 13:14 UTC
Labels: status/more-info-needed
