### ISSUE TITLE
docker ps and attach hang 

### ISSUE THREAD

**Issue by jeremy-rutman** [docker/docker#22488] opened 2016-05-03 22:41 UTC
this is similar to issue [12606](https://github.com/docker/docker/issues/12606) but it was suggested there to start a new thread for version 1.10
**Output of `docker version`:**  
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
root@braini2:~# uname -a
Linux braini2 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 111
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local nvidia-docker
 Network: bridge null host
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.8 GiB
Name: braini2
ID: DZAL:ZG3Z:OT6A:33IF:LSQP:B6ZA:R3AI:C3VF:X2HH:EGE3:NCEL:3HGM
WARNING: No swap limit support
Labels:
 provider=generic
```

ibm softlayer machine , ubuntu 
```
root@braini2:~# uname -a
Linux braini2 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Steps to reproduce the issue:**
A.fire up a container
```
nvidia-docker run -i -t -v /home/jeremy:/root/imgdbs --device /dev/nvidia0:/dev/nvidia0  /dev/nvidia1:/dev/nvidia1 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm 9632089ae495 /bin/bash
```

B. wait a couple days

Docker attach hangs, docker ps hangs after some days. Another container that was started with a similar command (but with --device gpu0 only , not both gpu0 and gpu1) is still running fine.  I guess i can avoid this being a showstopper by writing my periodic output to a linked directory, but its pretty annoying to not be able to use docker ps, and in any case has already lost a week of GPU work unless I can somehow get back into the stuck container...so if anyone has some ideas I'd appreciate it

**Comment by thaJeztah** [comment] 2016-05-03 23:37
I wonder if nvidia-docker plays a role here. do the daemon logs show anything useful?

**Comment by 3XX0** [comment] 2016-05-04 05:51
I really doubt it's caused by `nvidia-docker`, `docker` has full control when it comes to executing the command. If anything, you are using it incorrectly because devices are in fact injected by `nvidia-docker` itself (no need to pass the `--device` arguments).

Regarding the issue, we've seen something similar happening in the past both with `docker` and `nvidia-docker`.
We couldn't reproduce it but I suspect it might have something to do with the queries to the plugins.
If that's the case, it might be worth checking `/var/log/upstart/nvidia-docker.log` as well.

**Comment by jeremy-rutman** [comment] 2016-05-04 09:15
fwiw the latest nvidia log from apr 21 (docker container froze May 3)  looks like this:
```
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:22:02 Successfully terminated
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:24:57 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:00 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:00 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:00 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:00 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:00 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:02 Received activate request
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:02 Plugins activated [VolumeDriver]
```
The docker logfile (from May3 ) doesnt seem to have timestamps and is in this munged-up format:
```
^[[34mINFO^[[0m[1039443] Container 98fbc03c7428ca371fc7a33f1138d51b0f717e8d7036247006c957c7ce0a7014 failed to exit within 10 seconds of $
^[[31mERRO^[[0m[1046081] attach: stdout: write unix /var/run/docker.sock->@: write: broken pipe
```
Now I have the interesting problem that autocomplete of docker attach hangs, so I can't reattach to the remaining not-frozen container without knowing its full name, which was one of those autogeneterated ones, either 'mad_davinci' or the like, or 'condescending_something' where something is something i can't remember as i never had to type it...

**Comment by jeremy-rutman** [comment] 2016-05-04 09:23
ok by looking at the names generator i solved the proximate problem of 'whats the name of the non-stuck container', leaving me with the distal problem of 'how do i unstick the stuck container'

**Comment by jeremy-rutman** [comment] 2016-05-05 07:46
BTW it does not appear that one can get away with not using the -device arguments in nvidia-docker:

```
root@braini2:~# nvidia-docker run -i -t --name test -v /home/jeremy:/root/imgdbs  9632089ae495 /bin/bash
root@d15ec651f1fd:~/caffe# ls /dev
console  fd  full  fuse  kcore  mqueue  null  ptmx  pts  random  shm  stderr  stdin  stdout  tty  urandom  zero
root@d15ec651f1fd:~/caffe# nvidia-smi
Failed to initialize NVML: Unknown Error
```

**Comment by 3XX0** [comment] 2016-05-05 08:27
What images are you using?
Your image should be based on the [official images](https://hub.docker.com/u/nvidia/) NVIDIA provides.
For Caffe, you can use NVCaffe (`nvidia/caffe`) or the [official BVLC image](https://github.com/BVLC/caffe/blob/master/docker/standalone/gpu/Dockerfile)

**Comment by jeremy-rutman** [comment] 2016-05-05 13:16
my images are based on the nvidia images

**Comment by 3XX0** [comment] 2016-05-05 19:18
I suggest you open an issue against https://github.com/NVIDIA/nvidia-docker because there is definitely something wrong here

**Comment by jeremy-rutman** [comment] 2016-05-08 09:48
opened an issue here [nvidia-docker issue 93](https://github.com/NVIDIA/nvidia-docker/issues/93)

**Comment by flx42** [comment] 2016-05-08 18:22
Note that this issue is for debugging this problem:
https://github.com/docker/docker/issues/22488#issuecomment-217095332

The `docker ps` issue still needs to be troubleshooted, we don't think it is caused by `nvidia-docker`  because we are already past the point where it did his job, but we are happy to help until we know for sure.

**Comment by jeremy-rutman** [comment] 2016-05-26 05:32
The base nvidia image I have works as you describe , I imagine my variant was not constructed correctly - its been a while.  When I require it again I'll take care to base the ne image using nvidia-docker and not docker, that perhaps was the original problem.

**Comment by thaJeztah** [comment] 2016-05-26 09:02
@jeremy-rutman is it ok to close this issue?

**Comment by sandyskies** [comment] 2016-08-11 03:31
@thaJeztah  I found docker hang because of native process ,use high cpu.

**Comment by thaJeztah** [comment] 2016-08-11 08:36
looks like this issue went stale, and the original issue is no longer reproducible, so I'm closing

**Closed by thaJeztah** 2016-08-11 08:36 UTC
Labels: version/1.10
