### ISSUE TITLE
bash tail with * on exec -it fails

### ISSUE THREAD

**Issue by albertoRamon** [docker/docker#29103] opened 2016-12-03 18:52 UTC
Hello
Also detected on alpine: [Link](https://github.com/kost/docker-alpine/issues/3)
I reproduce this bug on Centos on Docker --> Isn't Alpine problem

The problem is use tail * from docker exec -it
`docker exec -it 14 bash -f /MyProyect/start.sh`

this not work
`tail -10 /var/log/hadoop/hdfs/hadoop-hdfs-namenode-*.out`
(but if you exec directly on bash container, works OK)

this work
`tail -10 /var/log/hadoop/hdfs/hadoop-hdfs-namenode-amb0.mycorp.kom.out`

the error is:
_tail: cannot open/var/log/hadoop/hdfs/hadoop-hdfs-namenode-*.out' for reading: No such file or directory`_

System
  Docker 1.12.3
  Host Ubuntu 16.04
  S.O Image Centos 6.6

**Comment by thaJeztah** [comment] 2016-12-03 22:47
This is expected. When specifying wildcards, your _local_ shell will try to expand the paths, but cannot find any files (because `/var/log/hadoop/hdfs/` is only present inside the container, not on your host).

For example, this will fail:

```bash
docker run -d --name test nginx:alpine

docker exec test tail -10  /usr/share/nginx/html/*
tail: can't open '/usr/share/nginx/html/*': No such file or directory
tail: no files
```

To have your _local_ shell ignore the wildcards, and have the wildcards expanded by the shell inside the container, use `sh -c` and provide the command to execute by the shell in quotes;

```
docker exec test sh -c 'tail -10  /usr/share/nginx/html/*'
==> /usr/share/nginx/html/50x.html <==
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>
<p><em>Faithfully yours, nginx.</em></p>
</body>
</html>

==> /usr/share/nginx/html/index.html <==
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

I'll close this issue because this is not a bug, but I hope this helps. Feel free to ask for more info if needed

**Closed by thaJeztah** 2016-12-03 22:47 UTC

**Comment by albertoRamon** [comment] 2016-12-03 22:56
hummm, yes and no

I'm agree with you in this will fail
*  docker exec -it . . .  tail path/*.txt*


*but I'm doing this:*




*echo " tail path/*.txt" > start.shdocker cp start.sh ...:/MyProyect/docker
exec -it 14 bash -f  /MyProyect/start.sh*
I'm copying sh file to docker and exec it sh







2016-12-03 23:49 GMT+01:00 Sebastiaan van Stijn <notifications@github.com>:

**Comment by thaJeztah** [comment] 2016-12-03 23:25
Have you tried without the `-f` option?

```bash
$ echo "tail -10 /usr/share/nginx/html/*" > test.sh
$ docker cp test.sh test:/

$ docker exec test sh -f /test.sh
tail: can't open '/var/cache/nginx/*': No such file or directory
tail: no files

$ docker exec test sh -f /test.sh
tail: can't open '/usr/share/nginx/html/*': No such file or directory
tail: no files
bash-4.3$ docker exec test sh /test.sh
==> /usr/share/nginx/html/50x.html <==
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>
<p><em>Faithfully yours, nginx.</em></p>
</body>
</html>

==> /usr/share/nginx/html/index.html <==
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by albertoRamon** [comment] 2016-12-04 08:42
yes, without -f works OK
thanks !

```
*echo " tail path/*.txt" > start.sh
docker cp start.sh ...:/MyProyect/
docker exec -it 14 bash /MyProyect/start.sh*
```
