### ISSUE TITLE
node-builder  Cannot create container for service node-builder: invalid bind mount spec 

### ISSUE THREAD

**Issue by TulsiRao** [docker/docker#31571] opened 2017-03-06 12:32 UTC
Hi All,

I'm getting following error,can anyone please help me installing this app.

```
$ docker-compose up
Creating stethoscopemaster_login_1
Creating stethoscopemaster_node-builder_1

ERROR: for login  Cannot create container for service login: invalid bind mount spec "C:\\Users\\````\\Desktop\\stethoscope-master\\logs:/logs:rw": invalid volume specification: 'C:\Users\``````\Desktop\stethoscope-master\logs:/logs:rw'

ERROR: for node-builder  Cannot create container for service node-builder: invalid bind mount spec "C:\\Users\\`````\\Desktop\\stethoscope-master\\stethoscope\\login:/code/stethoscope/login:rw": invalid volume specification: 'C:\Users\`````\Desktop\stethoscope-master\stethoscope\login:/code/stethoscope/login:rw'
[31mERROR[0m: Encountered errors while bringing up the project.
```
here is my docker-compose.yml content

```
$ cat docker-compose.yml
```
```yaml
version: '2'
services:
  login:
    extends:
      file: docker-compose.base.yml
      service: login
  api:
    extends:
      file: docker-compose.base.yml
      service: api
    links:
      - login
  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    links:
      - login
      - api
  node-builder:
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
     - ./stethoscope/ui/src:/code/stethoscope/ui/src
     - ./stethoscope/static:/code/stethoscope/static
     - ./stethoscope/login:/code/stethoscope/login
    command: ["npm", "run", "buildonly"]
```
can anyone please help me fixing this issue.

**Comment by thaJeztah** [comment] 2017-03-06 20:40
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-06 20:40 UTC
Labels: area/builder
