### ISSUE TITLE
exec not running

### ISSUE THREAD

**Issue by DEVELByte** [docker/docker#27540] opened 2016-10-19 12:36 UTC
**Description**
`docker exec -i -t <container_id> bash`
the above command giving me error that the image has run and stopped, but my image is still running.

Error:
`rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"`

I am running the Airflow Image from [this place](https://github.com/puckel/docker-airflow)
`docker pull puckel/docker-airflow`

I ran the Image with below command from [simple-docker-ui-app](https://github.com/felixgborrego/docker-ui-chrome-app)
`docker run -i -t -P --name airflow puckel/docker-airflow:latest docker-compose -f docker-compose-LocalExecutor.yml up -d`

**Steps to reproduce the issue:**
1. start the docker image 
2. run below command
`docker exec -i -t <container_id> bash`

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by oppianmatt** [comment] 2016-10-19 18:31
Confirm I'm getting the same, upgraded to docker 1.12 from 1.11. Rebooted, ran my containers. Then  the usual cron script that does a docker exec started reporting the same error. But the container is running:

```
> docker info
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 311
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1827
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-95-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.38 GiB
Name: pitchupdev2.dh.bytemark.co.uk
ID: J56X:YTNH:WGRQ:UWAV:PODL:VPXG:IHMC:MIQO:6SG2:RZ4G:6L5G:7NI7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

```
> docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
59add70392bf        pitchupmatt/pitchup:master   "gunicorn wsgi:applic"   25 minutes ago      Up 25 minutes                           pitchup_gunicorn
60ce7973a63d        pitchupmatt/pitchup:master   "single-beat python m"   25 minutes ago      Up 25 minutes                           pitchup_celery_beat
eb4066ec09f8        pitchupmatt/pitchup:master   "python manage.py cel"   25 minutes ago      Up 25 minutes                           pitchup_celery_dev
```

```
> docker exec pitchup_gunicorn python -u manage.py calc_pitch_lead_prices
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"
```

Can see the name `pitchup_gunicorn` in the running containers list, but the exec fails.

**Comment by oppianmatt** [comment] 2016-10-19 18:34
Using the short id doesn't help either:

```
> docker exec -it 59add70392bf bash -l
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"
```

**Comment by Nearhan** [comment] 2016-10-19 20:19
I can confirm having the same problem after having upgraded to 1.12

**Comment by ssuvasanth** [comment] 2016-10-19 20:29
The issue is 100% reproducible but with that particular image.

> $docker ps
> CONTAINER ID        IMAGE                          COMMAND                  CREATED              STATUS              PORTS                                                                       NAMES
> 5b41ccdc2e55        puckel/docker-airflow          "./entrypoint.sh"        About a minute ago   Up About a minute   5555/tcp, 8793/tcp, 0.0.0.0:8080->8080/tcp                                  happy_kalam
> 30a7f3168f07        oraclelinux                    "ping localhost"         10 minutes ago       Up 10 minutes                                                                                   mad_pike
> c5a77bb7483e        puckel/docker-airflow          "./entrypoint.sh"        10 minutes ago       Up 10 minutes       5555/tcp, 8080/tcp, 8793/tcp                                                small_payne
> 79cbd5738223        puckel/docker-airflow:latest   "./entrypoint.sh d..."   41 minutes ago       Up 41 minutes       0.0.0.0:32770->5555/tcp, 0.0.0.0:32769->8080/tcp, 0.0.0.0:32768->8793/tcp   airflow

> $ docker exec -it happy_kalam bash
> rpc error: code = 2 desc = oci runtime error: exec failed: cannot exec a container that has run and stopped
> 
> $ docker exec happy_kalam ls
> rpc error: code = 2 desc = oci runtime error: exec failed: cannot exec a container that has run and stopped

Checking more on this.

**Comment by justincormack** [comment] 2016-10-20 11:12
Ok, minimal repro is `docker run -d puckel/docker-airflow` and then try to `docker exec` into it.

This is a regression from 1.12.1 to 1.12.2. The error is from the Go http2 library, so probably related to the grpc/error handling changes in 1.12.2.

cc @crosbymichael

**Comment by justincormack** [comment] 2016-10-20 11:18
@DEVELByte reverting to 1.12.1 fixes the issue for me, you might want to do that until we release a fix.

**Comment by yongtang** [comment] 2016-10-20 15:17
The issue is that in `/proc/[pid]/stat`, the `pos 2` is the filename which could contain space.
The following are two examples. The first one is the normal case and the second one is the problem encounter with `puckel/docker-airflow`

```
ubuntu@ubuntu:~/runc$ cat /proc/90286/stat
90286 (bash) S 90271 90286 90286 34818 90286 4194560 1412 1130576 4 0 2 1 2334 438 20 0 1 0 3093098 20733952 823 18446744073709551615 1 1 0 0 0 0 0 3670020 1266777851 0 0 0 17 1 0 0 0 0 0 0 0 0 0 0 0 0 0
ubuntu@ubuntu:~/runc$ cat /proc/89653/stat
89653 (gunicorn: maste) S 89630 89653 89653 0 -1 4194560 29689 28896 0 3 146 32 76 19 20 0 1 0 2971844 52965376 3920 18446744073709551615 1 1 0 0 0 0 0 16781312 137447943 0 0 0 17 1 0 0 0 0 0 0 0 0 0 0 0 0 0
```

And `GetProcessStartTime` in `runc` didn't take that into consideration.

I created a PR in runc https://github.com/opencontainers/runc/pull/1136 to fix this issue.

**Comment by LK4D4** [comment] 2016-10-20 15:18
@yongshin so, it's not a regression?

**Comment by yongtang** [comment] 2016-10-20 15:24
@LK4D4 The `libcontainer/system/proc.go` has not been updated for quite some time. I don't know enough history of `runc` though.

I tend to think it might be something related to the changes in `libcontainer/container_linux.go` that caused the regression (if it is a regression).

**Comment by LK4D4** [comment] 2016-10-20 15:25
@yongtang thanks!
@justincormack would you mind to try runc patch?

**Comment by justincormack** [comment] 2016-10-20 15:34
Will do.

It did seem to be a regression, but will check again, perhaps there were
other system differences.

**Comment by justincormack** [comment] 2016-10-20 16:51
It is definitely a regression 1.12.1 vs 1.12.2, tested on Digital Ocean Debian VMs again.

**Comment by crosbymichael** [comment] 2016-10-20 17:33
@justincormack seems to be working on master for me

**Comment by crosbymichael** [comment] 2016-10-20 17:42
ok, on 1.12.2 it I can get the error but on master it works fine

**Comment by yongtang** [comment] 2016-10-20 17:59
@crosbymichael I am still seeing it on master, don't know if it is because of the `runc` version (I am not very familiar with docker and runc interaction):
```
bundles/1.13.0-dev already exists. Removing.

---> Making bundle: binary (in bundles/1.13.0-dev/binary)
Building: bundles/1.13.0-dev/binary-client/docker-1.13.0-dev
Created binary: bundles/1.13.0-dev/binary-client/docker-1.13.0-dev
Building: bundles/1.13.0-dev/binary-daemon/dockerd-1.13.0-dev
Created binary: bundles/1.13.0-dev/binary-daemon/dockerd-1.13.0-dev
Building: bundles/1.13.0-dev/binary-daemon/docker-proxy-1.13.0-dev
Created binary: bundles/1.13.0-dev/binary-daemon/docker-proxy-1.13.0-dev
Copying nested executables into bundles/1.13.0-dev/binary-daemon

ubuntu@ubuntu:~/docker$ sudo service docker stop
[sudo] password for ubuntu: 
ubuntu@ubuntu:~/docker$ sudo cp bundles/1.13.0-dev/binary-client/docker* /usr/bin/
ubuntu@ubuntu:~/docker$ sudo cp bundles/1.13.0-dev/binary-daemon/docker* /usr/bin/
ubuntu@ubuntu:~/docker$ sudo service docker start
ubuntu@ubuntu:~/docker$ docker info
Containers: 27
 Running: 0
 Paused: 0
 Stopped: 27
Images: 63
Server Version: 1.13.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.842 GiB
Name: ubuntu
ID: 2TTD:VJNB:L2WV:DVCF:PA7C:CFWS:DOJA:PLRX:X334:A43W:APEZ:WSZY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
ubuntu@ubuntu:~/docker$ docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   ffa0446
 Built:        Thu Oct 20 17:52:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   ffa0446
 Built:        Thu Oct 20 17:52:11 2016
 OS/Arch:      linux/amd64
ubuntu@ubuntu:~/docker$ docker-runc --version
runc version 1.0.0-rc2
commit: 02f8fa7863dd3f82909a73e2061897828460d52f
spec: 1.0.0-rc2-dev
ubuntu@ubuntu:~/docker$ 
ubuntu@ubuntu:~/docker$ docker run -d puckel/docker-airflow
cd3265be77dc4907984826dcd1fa2a787a462c69a5b906405dbc19df138c2c71
ubuntu@ubuntu:~/docker$ docker exec -i -t cd3 bash
rpc error: code = 2 desc = oci runtime error: exec failed: cannot exec a container that has run and stopped
```

**Comment by crosbymichael** [comment] 2016-10-20 18:05
@yongshin ok, i think i understand the problem now.  Thanks for your PR. I'm reviewing it now.

**Comment by crosbymichael** [comment] 2016-10-20 18:52
Ok so https://github.com/opencontainers/runc/pull/1136 does fix this issue.  The regression is that we call `container.Status()` on exec, state, etc in runc with the vendored version that was included in 1.12.2.  

The problem is that the parsing logic did not account for the space inside the `()`.  The bug was not a regression but a long standing issue that was always there just uncovered by the fact that when we try to exec, we check that status, which in turn, reads the process start time to verify we are interacting with the process that we thought we were.  This failed parsing so runc thinks that this is not the same process and the container was stopped.  @yongtang 's pr fixes this and I verified the fix with docker.

**Comment by yongtang** [comment] 2016-10-21 14:46
The PR https://github.com/opencontainers/runc/pull/1136 has been merged in runc, and @crosbymichael 👍  opened a PR  #27610 to update runc in docker. Once #27610 is merged this issue could be closed.

**Comment by vieux** [comment] 2016-10-24 17:21
Fixed by https://github.com/docker/docker/pull/27610

**Closed by vieux** 2016-10-24 17:21 UTC
Labels: kind/bug, priority/P1, version/1.12

**Comment by krunal24787** [comment] 2017-02-24 23:45
Can anyone summarize the final solution for this issue? 
I tried following the entire conversation but couldn't resolve my issue.

**Comment by yongtang** [comment] 2017-03-10 18:43
@krunal24787 The issue has been fixed in the latest docker release. If you update your docker version then the issue is addressed.

**Comment by tjboring** [comment] 2017-04-13 16:02
This still seems to be an issue in 1.12.6.

```
docker exec -it kickass_volhard /bin/bash
rpc error: code = 2 desc = containerd: container not started
```
I get the above on 2 different machines running same version of ubuntu (16.10) and same version of docker. Also same behavior regardless of container (i.e. happens for all containers running on the machines).

```
docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-41-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: prometheus01
ID: PVPE:VSEF:WIZD:PP7V:MZJC:E4BR:ME2H:PLUB:HKF6:AS5E:AFQV:YHZR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

```
# docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   78d1802
 Built:        Tue Jan 31 23:47:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   78d1802
 Built:        Tue Jan 31 23:47:34 2017
 OS/Arch:      linux/amd64
```

**Comment by tigerich** [comment] 2017-04-22 00:48
1.12.6 does have the problem remained to be solved...

**Comment by ahahu** [comment] 2017-05-22 20:28
It's still there in 1.12.6, please reopen.

**Comment by HaiNguyen007** [comment] 2017-06-18 15:53
+1, It's still in 1.12.6, please fix it

**Comment by yongtang** [comment] 2017-06-19 16:03
The latest docker version is `v17.05.0-ce`. Version `v1.12.6` was released in January. I think it probably makes sense to update the docker to a recent version.

**Comment by bopini** [comment] 2017-06-26 20:08
This issue exist in 17.05.0-ce as well. 

docker exec cmd gave in error:
rpc error: code = 2 desc = containerd: container not found

**Comment by yongtang** [comment] 2017-06-27 22:42
@bopini I tried with 10.05.0-ce and does not see the issue:
```
ubuntu@ubuntu:~$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:24:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:24:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
ubuntu@ubuntu:~$ docker run -d puckel/docker-airflow
Unable to find image 'puckel/docker-airflow:latest' locally
latest: Pulling from puckel/docker-airflow
9f0706ba7422: Pull complete 
36892ed76947: Pull complete 
499bf841fb29: Pull complete 
eb3ffaa2dac5: Pull complete 
fcb79a4e7773: Pull complete 
Digest: sha256:51f35e5664d8a1b5a81403ba85084f6977a29bacda00756d11f4f37a7aa1869a
Status: Downloaded newer image for puckel/docker-airflow:latest
7208d27ee041ee760f6903770e50cb4a28b493392aaca52e53f78c08785e5f20
ubuntu@ubuntu:~$ docker exec -i -t 720 bash
airflow@7208d27ee041:~$ exit
exit
ubuntu@ubuntu:~$
```

Can you take a look and see if you could provide the steps to reproduce?

**Comment by yongtang** [comment] 2017-06-27 22:42
@bopini Here is the output of docker info:
```
ubuntu@ubuntu:~$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 322
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-22-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.84GiB
Name: ubuntu
ID: HHTK:OKEW:QAJJ:O3ZF:LO7B:UPQC:EDN4:K7ST:RSLO:LSOI:DLXA:4ZIX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
ubuntu@ubuntu:~$ 

```
