### ISSUE TITLE
Docker corrupts output by converting \n to \r\n. 

### ISSUE THREAD

**Issue by soulne4ny** [docker/docker#29432] opened 2016-12-15 00:09 UTC
**Description**

Text files `cat`ed from inside docker to host got `\r\n` for newlines.  
Tar gets broken.

**Describe the results you received:**

```sh
$ docker run --rm -it alpine sh -c echo | od -cx
0000000   \r  \n
             0a0d
0000002

$ docker run --rm -it debian:jessie sh -c echo | od -cx
0000000   \r  \n
             0a0d
0000002

$ docker run --rm -it debian:jessie tar -cf- /etc/os-release | tar -tf-
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

**Describe the results you expected:**

```sh
$ docker run --rm -it alpine sh -c echo | od -cx
0000000   \n
             000a
0000001

$ docker run --rm -it debian:jessie sh -c echo | od -cx
0000000   \n
             000a
0000001

$ docker run --rm -it debian:jessie tar -cf- /etc/os-release | tar -tf-
tar: Removing leading `/' from member names
etc/os-release
```

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 56
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 106
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: 5GTA:PXIR:LUFZ:R4W5:KA27:MWLR:3VL4:ZNLF:F7B3:JMHP:VMIY:FM5H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 38
 System Time: 2016-12-15T00:07:43.184310177Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for Mac
```
Version 1.12.3 (13776)
Channel: Stable
583d1b8ffe
```

**Comment by thaJeztah** [comment] 2016-12-15 01:10
This is a duplicate of https://github.com/docker/docker/issues/6674. The `\r\n` line endings are not added by docker, but by the shell /  TTY; see https://github.com/docker/docker/issues/8513#issuecomment-216191236 (and the `-onlcr` option described here http://pubs.opengroup.org/onlinepubs/009696799/utilities/stty.html);

By default the TTY uses `\r\n` line endings, and translates `\n` into `\r\n`;

``` bash
$ docker run -t --rm debian sh -c "echo -n '\n'" | od -c
0000000   \r  \n
0000002
```

disabling "translate newline to carriage return-newline" with `stty -onlcr` disables this behavior and gives;

``` bash
$ docker run -t --rm debian sh -c "stty -onlcr && echo -n '\n'" | od -c
0000000   \n
0000001
```

I'll close this issue because this is not a bug in docker, but a standard behavior of Linux, but feel free to comment after I closed

**Closed by thaJeztah** 2016-12-15 01:10 UTC
Labels: platform/desktop, version/1.12

**Comment by soulne4ny** [comment] 2016-12-15 10:49
It should be reflected in the `run -t` docs because it is not obvious! And quite unexpected, I mean it breaks things far far away from the place `docker run -t` was used. It could cost couple of hours to find out side-effects.
Piping tar to tar this is quite common with ssh where ssh does not need any special keys!

**Comment by thaJeztah** [comment] 2016-12-15 11:23
If you're not running an interactive process, don't use `-i`, `-t`;

    docker run --rm debian:jessie tar -cf- /etc/os-release | tar -tf-
    tar: Removing leading `/' from member names
    etc/os-release

**Comment by soulne4ny** [comment] 2016-12-16 20:06
Yes, it is clear. I agree.
It is stated in the doc
> Specifying -t is forbidden when the client standard output is redirected or piped...
