### ISSUE TITLE
Proposal: Dockerfile BINDMOUNT for secure- and/or offline Dockerfile build environments

### ISSUE THREAD

**Issue by dagelf** [docker/docker#10199] opened 2015-01-19 21:19 UTC
Before you dismiss this off hand - there are legitimate use cases where this feature can save the user hours, and entice him to be a good Docker citizen - and I will list them.

I know the philosophy of Dockerfiles it to make them as portable as possible. But a bigger part of the philosophy is to "don't repeat yourself" and "don't reinvent the wheel". There are two use cases where the security concern for not having this becomes a moot point, and where a simple Dockerfile command can save a lot of complexity.

Case #1: You're in a secure enviroment, without internet access, and you have a complete local cache of an Ubuntu/CentOS/other repo, from which you'd like to build your docker images. 

Use case 1:
In your Dockerfile, you have easily removable lines:
BINDMOUNT yum.repos.d:/etc/yum.repos.d  # which contains the 3 lines necessary to install from CD
BINDMOUNT /media/CentOS-CD:/media/CentOS-CD (this is where your CD image is mounted - the / could even be relative from your current Dockerfile path, for security)
RUN yum -y install *lots of stuff*

Result: Your Dockerfile may not be portable, but you can use it to test locally in your offline environment. 

BUT - if you want to make your Dockerfile portable, you simply remove the two BINDMOUNT lines. In fact, if another environment ignores them altogether, your following commands will still work because the default repository config will not be overloaded with a config pointing to your locally mounted CD, but will still point to the default online sources, which will work as per normal. 

Current alternative: 
1) You have to change the repo config to pull from a non-standard DNS - MANUALLY - or you have to hijack DNS so it pulls from your local repo.
AND 2) You have to run a local webserver
AND 3) You have to expose the CD/offline repo files in a manner consistent with those of an on-line repository for the package mangement system in question

Footnotes: 
1) Additionally your image needs tools to download from a webserver, eg wget or equivalent built into it's package mangement system
2)AND the package mangement system needs to be part of the image 

With the suggested solution, you could potentially bind-mount an entire /usr/local/bin tree with package management tools that need not be present in the resulting image - yielding a smaller, and more secure image - as if and when compromised, a hacker won't have easy access to your package management system to load the tools he needs to compromise the host.

Use case 2:
You're on a terrible 3G connection, and you'd like to work on Dockerfiles in an offline enviroment, without the added burden of running your own DNS + Webserver + pristine offline copy of the whole online repo.

Motivation:
The current approach throws sand in the face of anyone trying to be a constructive citizen in the Docker commnity, from the confines or poor or offline connectivity... and forces them to use their own hacked-together solutions. 

You don't need to search far to find at least 5 much uglier solutions than the one proposed, that people are actively promoting. Those in secure/offline environments are left with no choice but to manually construct docker images from tar commands and shell files, while the whole Dockerfile infrastructure goes complete unused as it has no use to them, and consequently wouldn't see any contributions from them, unless the above could be supported. 

Alternately, the same could be accomplished had "docker build" supported the -v option from "docker run".

**Comment by krystism** [comment] 2015-01-20 01:30
:+1:  In fact, we can use one or more flags to tell the interpreter whether we are in local or not. If we are in local, we can use some special commands like @dagelf said, and if not, the interpreter can just ignore them.  But if so,this is equivalent to support condition sentence.

**Comment by smarterclayton** [comment] 2015-01-23 01:02
One note - you don't usually want a volume in the output containing your secrets, as discussed in a few other issues there's value in the bind mount being transient for the scope of the build and then omitted from the final metadata.

**Comment by bwthomson** [comment] 2015-02-04 18:59
Since there seems to be a concern about injecting arbitrary dependencies into docker builds, a compromise worth considering would be direct r/w access to the build context.  A new Dockerfile instruction
`    BUILDCONTEXT `*`path`*
bindmounts the host context directory at *path* in the container, but only during the build.
Combine it with a little creative in-container symlinking and it will address many of the scenarios around build-time tools and repository caches that seem to be driving this requirement.

If I understand the current implementation, today the context is copied into a volume that gets mounted in a secret place that only ADD and COPY can find.  This proposal rw mounts the host directory instead of a copy, and exposes the mount point where e.g. RUN can get at it.

So what makes it a compromise?  Builds are already context dependent, so this proposal is more consistent with established docker fu and the principle of self-containment than arbitrary build-time volumes would be.  On the other hand, although it allows a build to participate in the maintenance of its own context it still doesn't help you share data between builds like unrestricted volume access would.

**Comment by bjodah** [comment] 2015-03-10 11:26
+1, I have also been looking for a convenient way to easily and reproducibly build docker images from local cache without relying on an internet connection. (motivated by the need to archive a setup for reproducible research - I want the docker images to be able to build - say - 20 years from now when many archive mirrors may be offline). A convenient way to ensure not involuntarily relying on a internet connection would be also to allow ``--net='none'`` for ``docker build`` (#10324)

**Comment by yrro** [comment] 2015-03-22 11:31
Another use case for this feature: if I have a large `.deb` package that I want to be installed as part of a build, I currently have to use `COPY` to get the package into the container so that a subsequent `RUN` will install it. Logically speaking, I have no need for a separate layer containing _just_ the copied .deb, as it will just waste space. I would like to be able to install the package directly from the build context so as to avoid the deb being committed as part of my final image.

**Comment by Sirupsen** [comment] 2015-03-22 14:32
I think this proposal has merit: there's a real need for a way to build with out-of-band artifacts. This is one of the primary reasons we have a completely custom builder that bypasses Dockerfiles altogether (although there are other solutions to this problem a bind-mount is the most generic):

* **Secrets**. Many application builds need secrets available during build e.g. to upload assets to S3, fetch the database schema from production and dump it to a file, etc. These should not be in the final layer, and with Docker's current model of creating a FS layer for each command—this is impossible without major hacking.
* **More sophisticated caching**. For example, many dependency management systems (e.g. `bundler`, `npm`, and other package managers) take a long time to fetch from scratch due to extensive networking. With the current model, you can't really run the command from a cache unless you do hacking to embed the cache into an earlier layer—which means that unnecessary things end up in the final image, which in our experience in this specific case, is very costly. With out-of-band artifacts, we'd be able to manage and iterate on this cache living outside of the container and only copy in the result as the last step.

In general I think out-of-band artifacts are powerful, and there's currently not any support for it as far as I can tell. This is a shortcut to a much more extensible build system.

**Comment by thaJeztah** [comment] 2015-05-04 02:49
I'm going to close this issue, because I think this is a duplicate of https://github.com/docker/docker/issues/3056

Please continue the discussion on https://github.com/docker/docker/issues/3056.

If you think I incorrectly marked this issue as a duplicate, feel free to comment / ping me :)

**Closed by thaJeztah** 2015-05-04 02:49 UTC
Labels: kind/feature, kind/proposal
