### ISSUE TITLE
[Windows 7] crypto/x509: system root pool is not available on Windows

### ISSUE THREAD

**Issue by samukolov** [docker/docker#31573] opened 2017-03-06 13:09 UTC
When I enter **docker run -p 5023:5023 -p 8050:8050 -p 8051:8051 scrapinghub/splash**
I get **crypto/x509: system root pool is not available on Windows** error.
Also, system says that it is **unable to find image 'scrapinghub/splash:latest' locally**.
And **error response from daemon: repository scrapinghub\splash not found: does not exist or no pull access**

**Comment by thaJeztah** [comment] 2017-03-06 13:24
Looks like this is a duplicate of https://github.com/docker/docker/issues/30450. The `scrapinghub\splash not found` message (which shows a backslash instead of a slash) may be due to mingw trying to be smart though (see http://www.mingw.org/wiki/Posix_path_conversion)

I'll close this issue, because it's a duplicate

**Closed by thaJeztah** 2017-03-06 13:24 UTC
