### ISSUE TITLE
--dns option not considered during build

### ISSUE THREAD

**Issue by onip** [docker/docker#14357] opened 2015-07-02 15:21 UTC
PREAMBLE
as far as I can tell networkmanager-openvpn (or bare networkmanager) require dnsmasq to provide all features.

so my host resolv.conf has
> nameserver 127.0.0.1

I've read in many places (including closed github issues) that setting --dns daemon options would solve the problem and actually I see set dns (google public ones) if I run `/bin/bash` in an (official) ubuntu image and inspect the file.

The problem happens while in the build phase. As example with the Dockerfile from official doc
```
FROM ubuntu

# debugging
RUN /bin/cat /etc/resolv.conf

# install dependencies
RUN apt-get -y update && apt-get install -y fortunes cowsay

# the command that will be run
CMD /usr/games/fortune -a | /usr/games/cowsay
```

the resolv.conf is taken directly from host system, so using 127.0.0.1 as nameserver. Naturally apt-get fails to resolve hosts.

docker info
```
Containers: 0
Images: 12
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-41-generic
Operating System: Ubuntu 14.10
CPUs: 4
Total Memory: 7.7 GiB
Name: pinazzi-thinkpad
ID: QQF4:3VI3:A743:D7DH:42MO:77VY:WYV7:H36Q:NOIC:LTDD:BGGT:4SZN
WARNING: No swap limit support
```

docker version
```
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 5e06332
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 5e06332
OS/Arch (server): linux/amd64
```

Is there a known solution or, at least, a workaround?

Thanks

ps obiouvsly disabling NM dnsmasq makes things work, but dns are still not imported

**Comment by LK4D4** [comment] 2015-07-02 17:28
@onip There is `--dns` flag for daemon. You can specify dns server there directly.

**Comment by onip** [comment] 2015-07-03 07:54
@LK4D4 it is already running with those options set.

```
$ ps aux | grep docker
root      2167  0.0  0.2 295992 17056 ?        Ssl  09:41   0:00 /usr/bin/docker -d --dns 8.8.8.8 --dns 192.168.1.56
```

**Comment by peterrham** [comment] 2015-07-05 04:36
I have noticed the same symptoms. I just updated my version of docker for ubuntu today.  I have not figured out the work around mentioned above "disabling NM dnsmasq".

Is there a more stable version of docker that I should install?

i'm using:
docker --version
Docker version 1.7.0-dev, build 5e06332

**Comment by onip** [comment] 2015-07-06 10:05
@peterrham 
just comment out the dnsmasq setting in `/etc/NetworkManager/NetworkManager.conf`

```
#dns=dnsmasq
```

and restart both NetworkManager **and** docker daemon

**Comment by LK4D4** [comment] 2015-07-06 13:26
Oh, now I think this is a bug.

**Comment by LK4D4** [comment] 2015-07-06 15:25
We're not taking hostConfig in account in builder, but probably should.

**Comment by coolljt0725** [comment] 2015-07-13 11:03
Can't reproduce on master, but I can reproduce on `Version 1.7.0-dev Git commit 5e06332`. This probably  be fixed on master.

**Comment by calavera** [comment] 2015-07-15 22:14
I believe this was fixed when https://github.com/docker/docker/commit/d18919e304c240df84502cdcc5ed655d92d12d4f was merged in master, May 19.

It looks like you're using a version prior to that commit. I'm closing this as fixed. Please, don't hesitate to reopen if you have any further concerns.

**Closed by calavera** 2015-07-15 22:14 UTC
Labels: kind/bug
