### ISSUE TITLE
Docker embedded dns seems to ignore --dns

### ISSUE THREAD

**Issue by ByteFlinger** [docker/docker#20101] opened 2016-02-08 13:41 UTC
docker version:
```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64
```

docker info:
```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 343
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 355
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58 GiB
Name: myhostname
ID: BCKZ:2QNT:KCIO:3N4A:662P:P64V:7K4C:FP2X:4WZ3:2WFX:YFJZ:UKON
WARNING: No swap limit support
```
Environment:
Physical machine

My resolv.conf file
```
nameserver 127.0.1.1
search mycompany.se
```

I am sitting behind a corporate network and my machine has 127.0.0.1 in the resolv.conf therefore I need to configure the dns manually. Up until now I have just set --dns in the DOCKER_OPTS daemon configuration (/etc/default/docker) and this works just fine when using the legacy bridge network however I noticed that when I try to use a user-created network, it does not work, even though I have set the --dns in the daemon configuration

```
root@883f9af11cfa:/# ping www.google.com
ping: unknown host www.google.com
```

I cannot find any information regarding how to configure the embedded dns other than calling --dns flag when running "docker run" and that did not help eithert when I tried.

Am I missing something regarding how to use user-specific networks in such a setup?

I am able to ping the dns server without any problems
```
root@883f9af11cfa:/# ping 127.0.0.11
PING 127.0.0.11 (127.0.0.11) 56(84) bytes of data.
64 bytes from 127.0.0.11: icmp_seq=1 ttl=64 time=0.076 ms
64 bytes from 127.0.0.11: icmp_seq=2 ttl=64 time=0.070 ms
```

**Comment by thaJeztah** [comment] 2016-02-08 15:03
@mavenugo added this to the milestone so that we don't loose sight

**Comment by mavenugo** [comment] 2016-02-08 16:20
@ByteFlinger I couldnt reproduce this issue in the same setup as you suggested.
in my host machine 

```
$ cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
search mycompany.se
 
```

Starting the daemon with `--dns`

```
$ docker-1.10.0 daemon --dns=8.8.8.8
```

Create an user-defined network and run a container on that.

```
$ docker-1.10.0 network create test
517479204f1fc71c2a3f18b6574ac3663f9a2002d9c89bda5798156ab631bd6c

$ sudo docker run --net=test -it busybox sh
/ # ping www.google.com
PING www.google.com (216.58.192.4): 56 data bytes
64 bytes from 216.58.192.4: seq=0 ttl=61 time=39.559 ms
64 bytes from 216.58.192.4: seq=1 ttl=61 time=141.357 ms
64 bytes from 216.58.192.4: seq=2 ttl=61 time=38.703 ms
64 bytes from 216.58.192.4: seq=3 ttl=61 time=66.853 ms
^C
--- www.google.com ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 38.703/71.618/141.357 ms

/ # cat /etc/resolv.conf
search mycompany.se
nameserver 127.0.0.11
options ndots:0
/ #

```

What is the `--dns` parameter that you use when starting the daemon ?
Also, are you in a `dind` environment ?

**Comment by mavenugo** [comment] 2016-02-08 16:35
@ByteFlinger the only way I could reproduce it is by having a `--dns` entry pointing to an invalid DNS server. 

```
$ docker-1.10.0 daemon --dns=8.8.9.9
```

In this case, when the container tries to reach this invalid server, you can see the error logs in the daemon :

```
ERRO[0011] external resolution failed, read udp 10.0.2.15:55891->8.8.9.9:53: i/o timeout
```

Can you please confirm if you see such errors in the daemon logs when this happens ?

**Comment by mmarzantowicz** [comment] 2016-02-08 17:43
I can confirm mentioned problems with `--dns` being ignored. Here are more details about my env:
```
$ docker info 
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 74
Server Version: 1.10.0
Storage Driver: btrfs
 Build Version: Btrfs v4.3.1
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.1-2-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.784 GiB
Name: royalarch
ID: 4QHC:NNCF:4N6F:XAXA:CUXL:Y6ZX:YIW5:DPDJ:AXHI:5VPR:DFNZ:ZXV5
```

```
$ docker version 
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Sat Feb  6 18:04:28 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Sat Feb  6 18:04:28 2016
 OS/Arch:      linux/amd64
```

Here are steps that reproduce this error:
1.
```
$ docker network create my-net
e80c9c9d6d819e4616bfcd4c41f178463421b3b9c4d639932f4cd06c1c81b40d
```
2.
```
$ docker run --rm -it --dns=192.168.1.1 --net=my-net fedora:23 /bin/bash
[root@1d4ab1f20ed2 /]# cat /etc/resolv.conf 
search xxx.yyy.tld
nameserver 127.0.0.11
options ndots:0
```
or
```
$ docker run --rm -it --dns=192.168.1.1 --net=my-net debian:latest /bin/bash
root@a9ac7808822c:/# cat /etc/resolv.conf 
search xxx.yyy.tld
nameserver 127.0.0.11
options ndots:0
```
Here is resolv.conf on my host system:
```
$ cat /etc/resolv.conf 
# This file is managed by systemd-resolved(8). Do not edit.
#
# Third party programs must not access this file directly, but
# only through the symlink at /etc/resolv.conf. To manage
# resolv.conf(5) in a different way, replace the symlink by a
# static file or a different symlink.

nameserver 192.168.1.20
nameserver 192.168.1.1
search xxx.yyy.tld
```

Finally, when using old good bridge0, everything works.
```
$ docker run --rm -it --dns=192.168.1.1 debian:latest /bin/bash
root@1799c295148d:/# cat /etc/resolv.conf 
search xxx.yyy.tld
nameserver 192.168.1.1
```

**Comment by ByteFlinger** [comment] 2016-02-08 18:10
@mavenugo I tried your examples but no go

My docker configuration (/etc/default/docker) looks like this

DOCKER_OPTS="--dns XXX.XXX.XXX.XX --dns YYY.YYY.YY.YYY --dns ZZZ.ZZ.ZZZ.ZZ"

Where the values are 3 different dns within the company

Here's what I get on your own example
```

$ ping XXX.XXX.XXX.XX
PING XXX.XXX.XXX.XX (XXX.XXX.XXX.XX) 56(84) bytes of data.
64 bytes from XXX.XXX.XXX.XX: icmp_seq=1 ttl=63 time=0.524 ms
64 bytes from XXX.XXX.XXX.XX: icmp_seq=2 ttl=63 time=0.508 ms
64 bytes from XXX.XXX.XXX.XX: icmp_seq=3 ttl=63 time=0.517 ms
^C
--- XXX.XXX.XXX.XX ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.508/0.516/0.524/0.019 ms

$ sudo service docker restart
docker stop/waiting
docker start/running, process 1043

$ docker network create test
f330826c92a391c191519818fe6e3c28a195dcd5ff17f5d7859df7b041d5a833

$ docker run --net=test -it busybox sh
/ # cat /etc/resolv.conf 
search aa.bb.company.se dd.ff.company.se somestuff.company.se company.se some.other stuff.company.se
nameserver 127.0.0.11
options ndots:0
/ # ping www.google.com
ping: bad address 'www.google.com'
/ # ping XXX.XXX.XXX.XX
PING XXX.XXX.XXX.XX (XXX.XXX.XXX.XX): 56 data bytes
64 bytes from XXX.XXX.XXX.XX: seq=0 ttl=62 time=0.638 ms
64 bytes from XXX.XXX.XXX.XX: seq=1 ttl=62 time=0.674 ms
64 bytes from XXX.XXX.XXX.XX: seq=2 ttl=62 time=0.371 ms
^C
--- XXX.XXX.XXX.XX ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.371/0.561/0.674 ms
/ #
```

As you can see I am able to ping the dns address within the container and I also see nothing in the logs. To make sure I am not missing anything I started the daemon in debug mode and it did not spit out anything special when performing the same commands above

**Comment by mavenugo** [comment] 2016-02-08 18:30
@mmarzantowicz when using embedded DNS server (in user-defined networks), the dns-servers that are passed via `--dns` is managed internally by the embedded DNS and is not populated inside the `/etc/resolv.conf` of the container. So, your observation is expected and is unrelated to the issue that @ByteFlinger is seeing.

the actual issue is the resolution failure when trying to reach the external DNS server.

**Comment by dnephin** [comment] 2016-02-08 19:08
@mmarzantowicz based on the title of your issue on Compose, I believe you're also not able to ping the server that should be resolved by the `dns` entry, is that right?  Could you include that output as well?

**Comment by sanimej** [comment] 2016-02-08 19:52
@ByteFlinger Passing the external server through --dns has been well tested and it works ok. We have to understand what is different in your setup.

If you have the daemon running in debug you should see some logs when the embedded DNS server forwards a query to external servers..

For ex: in my working case I see..

DEBU[0095] To resolve: www.google.com in                
DEBU[0095] To resolve: www.google in com                
DEBU[0095] To resolve: www in google.com                
DEBU[0095] Querying ext dns udp:8.8.8.8 for www.google.com.[1] 

From the  ps output can you check if the daemon is indeed running in debug mode ?

**Comment by ByteFlinger** [comment] 2016-02-08 20:11
When running the daemon in debug more and calling ping within the container I do not see any debug messages or any activity in the logs.

```
$ ping XXX.XXX.XXX.XX
PING XXX.XXX.XXX.XX (132.196.7.75) 56(84) bytes of data.
64 bytes from XXX.XXX.XXX.XX: icmp_seq=1 ttl=63 time=0.544 ms
64 bytes from XXX.XXX.XXX.XX: icmp_seq=2 ttl=63 time=0.285 ms
^C
--- XXX.XXX.XXX.XX ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.285/0.414/0.544/0.131 ms
$ ps -ef|grep docker|grep -v grep
root      1367  1317  0 20:59 pts/9    00:00:00 sudo docker daemon -D --dns XXX.XXX.XXX.XX
root      1371  1367  0 20:59 pts/15   00:00:00 sudo docker daemon -D --dns XXX.XXX.XXX.XX
root      1372  1371  1 20:59 pts/15   00:00:00 docker daemon -D --dns XXX.XXX.XXX.XX

$ ping some.address.company.se
PING some.address.company.se (WWW.WW.WWW.WW) 56(84) bytes of data.
64 bytes from WWW.WW.WWW.WW: icmp_seq=1 ttl=53 time=8.65 ms
64 bytes from WWW.WW.WWW.WW: icmp_seq=2 ttl=53 time=8.74 ms
^C
--- some.address.company.se ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 8.652/8.697/8.742/0.045 ms

$ docker run --net=test -it busybox sh
/ # ping www.google.com
ping: bad address 'www.google.com'
/ # ping some.address.company.se
ping: bad address 'some.address.company.se'
```

@dnephin I am not using Compose but you can see that I am able to query an internal address from my machine yet not within the container

@sanimej From your comment it sounds as though the daemon is not performing any dns lookup at all, as if the embedded dns was not running. I simply see no activity in the logs when running ping within the container, only when starting and exiting the container

**Comment by aboch** [comment] 2016-02-08 21:02
@ByteFlinger 

By any chance, are you running more than one daemon on your machine ?
Asking becasue of this output:
```
root      1367  1317  0 20:59 pts/9    00:00:00 sudo docker daemon -D --dns XXX.XXX.XXX.XX
root      1371  1367  0 20:59 pts/15   00:00:00 sudo docker daemon -D --dns XXX.XXX.XXX.XX
root      1372  1371  1 20:59 pts/15   00:00:00 docker daemon -D --dns XXX.XXX.XXX.XX
```

**Comment by ByteFlinger** [comment] 2016-02-08 21:13
@aboch No. I was also surprised by the output of the ps command however the moment I stopped the docker daemon (Ctrl+C) another ps command revealed no more docker daemon processes. I figured it's something that the daemon is doing and forking a few processes though now that I pay more attention I see the first 2 sumo processes have a cyclic parentage where one is the parent of another, I am no Linux guru so I am uncertain if I should read something into that.

**Comment by aboch** [comment] 2016-02-08 21:19
@ByteFlinger 
Thanks for the info.

Can you please try to selectively kill the spurious `sudo daemon [...]` instance (The one for which is not the parent of the `docker daemon [...]`) and then try again the container run and ping  and check the daemon Debug logs ?

Just trying to see if that extra process is somehow an issue.

Thanks.

**Comment by sanimej** [comment] 2016-02-08 21:31
@aboch @ByteFlinger Its better to kill all the running instances of the daemon; start the daemon manually from a terminal in the debug mode and then try the ping from the container. This will help to confirm if there is any issue with --dns config.

Reason for multiple instances showing up can be dealt with separately.

**Comment by ByteFlinger** [comment] 2016-02-09 00:31
That's what I did. The ps output shown above is for when I had the docker daemon command, as shown in the ps output, running in the foreground on another terminal. Once I ctrl+C that process it killed all 3 processes.

**Comment by mavenugo** [comment] 2016-02-09 01:49
@ByteFlinger I have not seen a case where the docker daemon has parent-child relationship but they are in different psuedo terminals `pts/9` & `pts/15`. 

```
root      1367  1317  0 20:59 pts/9    00:00:00 sudo docker daemon -D --dns XXX.XXX.XXX.XX
root      1371  1367  0 20:59 pts/15   00:00:00 sudo docker daemon -D --dns XXX.XXX.XXX.XX
```

Since passing `--dns` such a fundamental configuration, it is hard to believe that it is failing in common case and the above scenario of multiple daemons process seems a suspect. 

In order to isolate this a little further, can you run a container in default bridge network and check the `/etc/resolv.conf` inside that container ?

```
$ docker run -it busybox sh
# cat /etc/resolv.conf
```

Also confirm if the connectivity works fine when using the default bridge network as above.

**Comment by thaJeztah** [comment] 2016-02-09 10:09
@ByteFlinger @mavenugo could those extra daemons be DIND? (which would explain them being started when the daemon is started)

**Comment by ByteFlinger** [comment] 2016-02-09 10:32
@mavenugo 

So I started docker with the following command

`sudo docker daemon -D --dns XXX.XX.XXX.XX`

Then I can confirm that the default bridge network is working

````
ps -ef|grep docker|grep -v grep
root      8967  1317  0 11:23 pts/9    00:00:00 sudo docker daemon -D --dns XXX.XX.XXX.XX
root      8969  8967  0 11:23 pts/15   00:00:00 sudo docker daemon -D --dns XXX.XX.XXX.XX
root      8970  8969  0 11:23 pts/15   00:00:00 docker daemon -D --dns XXX.XX.XXX.XX
$ docker run -it busybox sh
/ # cat /etc/resolv.conf 
search aa.bb.company.se cc.dd.company.se stuff.company.se company.se some.other.stuff.company.se
nameserver XXX.XX.XXX.XX
/ # ping www.google.com
PING www.google.com (173.194.116.145): 56 data bytes
64 bytes from 173.194.116.145: seq=0 ttl=41 time=31.885 ms
64 bytes from 173.194.116.145: seq=1 ttl=41 time=31.785 ms
^C
--- www.google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 31.785/31.835/31.885 ms
/ # ping internal.address.company.se
PING internal.address.company.se (aa.bbb.cc.d): 56 data bytes
64 bytes from aa.bbb.cc.d: seq=0 ttl=52 time=8.938 ms
64 bytes from aa.bbb.cc.d: seq=1 ttl=52 time=8.903 ms
^C
--- internal.address.company.se ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 8.903/8.920/8.938 ms
````

@thaJeztah Sorry, I am not sure what DIND is. Any way to perform a check?

**Comment by mavenugo** [comment] 2016-02-09 12:42
@ByteFlinger `dind` is Docker In Docker. where one can run Docker daemon in a container which in turn can launch containers inside. I dont think that is not the reason for your `ps` output. I suspect something to do with your terminal (such as `screen` or `tmux` or some other terminal emulation causing this). Is there anything special that we should be aware ?

Since you confirmed your observation with the `service` command, could you pls confirm the ip-address value used by the `--dns` option ? If it is private data, can you confirm if it is not `127.x.x.x` and not ipv6 resolvers ?

**Comment by sanimej** [comment] 2016-02-09 16:52
Can you do a docker service stop, edit /etc/default/docker and add -D to DOCKER_OPTS and start the docker service again. And send the debug logs when you try to ping an external site.

**Comment by mavenugo** [comment] 2016-02-09 18:30
@ByteFlinger since we are tracking this issue for 1.10.1 as P1 & none of us are able to reproduce this issue... the only way we could proceed at this point is to get more info from your side. If you prefer, we can chat live in IRC (ping us in #docker-network channel). That will enable us to debug it live & you wouldnt also have to share the details of the DNS IP in public :)

**Comment by ByteFlinger** [comment] 2016-02-09 19:20
Somehow I must have missed to press the comment button as I had already prepared this answer earlier. 

@mavenugo I am not running tmux or screen.  I have byob and tmux installed but using none of them. 

The dns is of type 132.196.xx.xx or 153.xx.xx.xx and it is not a `dind` environment nor ipv6

Using 8.8.8.8 as the dns does not work, probably due to some internal blocking within the company's network which is why I have to use a separate address. When trying with 8.8.8.8 it just takes 30 seconds before I get the same answer from ping I get when trying the embedded dns.

I will try to find some time to get into the irc channel tomorrow as I have already left the office so we can get this out of the way and try the -D flag in the configuration instead.

**Comment by mamciek** [comment] 2016-02-10 08:48
My problem is slightly different. I have used --dns options to set DNS to 127.0.0.1. In my containers I had dnsmasq running that forwarded DNS queries to consul agent or upstream.
1. How can I set resolv.conf to point to 127.0.0.1 ?
2. Alternativley how can I forward all dns queries to one of my containers?
I am using docker-compose so I cannot know IP of my consul container upfront.

**Comment by sanimej** [comment] 2016-02-10 11:45
@mamciek Since the embedded DNS server is running in the docker daemon having 127.0.0.1 as a dns server within the container is a bit complicated because the packet has to be sent back to the container's namespace. The PR for handling this is not merged yet.

couple of options you can consider are..
- run dnsmasq in a container with the port mapping and use the bridge ip as the --dns for other containers in the same network. @huguesb uses this approach as he explained in #20019

- directly pass the consul/upstream DNS server's IP through --dns

**Comment by mamciek** [comment] 2016-02-10 12:10
Unfortunatley I cannot use this options because id not know the consul dns ip and port when creating containers.

Can you point me to the PR you mentioned (the one that is not merged yet)?

**Comment by mavenugo** [comment] 2016-02-10 14:07
@mamciek running dnsmasq in each container and using 127.0.0.1 is something you should avoid. But, you can run dnsmasq in its own container and use that as your dns server in other containers. The easiest way to assign an ip-address to the container and make use of it. Since you are using compose ( i guess you are using v2 ). You can do the following -

1. Use the IPAM option to setup a subnet and gateway for your network
```
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.5.254
```

2. create a dnsmasq service and expose the port
3. Use `--dns` as `172.28.5.254` (the gateway that you specified above) in all other containers that wants to consume the dnsmasq service.

**Comment by mavenugo** [comment] 2016-02-10 14:09
@mamciek btw, if you are using compose v1 format, there shouldn't be any change. my comment above is purely for the newly introduced compose v2.

**Comment by mavenugo** [comment] 2016-02-10 14:13
@ByteFlinger do you have the debug logs as @sanimej requested ? Lets try and debug it live today if you can be available in IRC. Given that the issue is not reproducible (except in your environment) we cannot keep it as P1 and track it for 1.10.1 if we don't get a chance to debug it with you.

**Comment by mavenugo** [comment] 2016-02-10 16:39
@ByteFlinger thanks for sharing the logs (in IRC). It is clear from the logs that, you have `Firewalld` enabled in your ubuntu machine and that causes the issue.

It is a duplicate of https://github.com/docker/docker/issues/20026. It will be fixed in 1.10.1.
Closing the issue.

**Closed by mavenugo** 2016-02-10 16:39 UTC
Labels: group/networking, priority/P1, status/cannot-reproduce

**Comment by sanimej** [comment] 2016-02-10 18:22
@mamciek 

https://github.com/docker/libnetwork/pull/895

**Comment by mamciek** [comment] 2016-02-11 19:36
@mavenugo i cannot assign static ip address to dnsmasq container. I run containers in docker swarm and i am using docker-compose.yml to start many groups of containers (just changing project name for each group). So each group need its own dnsmasq container(with dynamic ip)  that is started together with the rest of containers in group. Is there a way to foward dns queried to one of the services defined in docker-compose. yml?  Will https://github.com/docker/libnetwork/pull/895 solve my issue?

**Comment by mavenugo** [comment] 2016-02-11 19:48
>> Is there a way to foward dns queried to one of the services defined in docker-compose. yml

@mamciek I think that will be a good feature to have in compose. Instead of relying on a static IP, pointing to a service, if compose gets the IP and use that in dependent services. We can discuss that in compose project.

**Comment by netroby** [comment] 2016-02-17 08:21
I can confirm this bug be here, it ignore my --dns specify with docker run argument.

**Comment by wrouesnel** [comment] 2017-04-05 06:04
Also confirming with 1.13. It seems like the resolver crashes internally, because a daemon restart usually fixes it.
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:50:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:50:18 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by Astridax** [comment] 2017-04-23 22:46
I can also confirm this is a major bug.

My current setup has dnsmasq set up in a container running on a user created network. 
The dnsmasq container has an IP of 172.42.0.2.
When running the other containers on the same network, I use the arguments --ip to set a static IP and --dns 172.42.0.2 to set the static dns entry to the dnsmasq contianer.

If I specifically set /etc/resolv.conf in one of the service containers (i.e. not dnsmasq) 
E.g. 
nameserver 172.42.0.2
#nameserver 127.0.0.11
#options ndots:0

doing dig +trace google.co.uk outputs:


`; <<>> DiG 9.10.4-P6 <<>> +trace google.co.uk
;; global options: +cmd
.			160971	IN	NS	h.root-servers.net.
.			160971	IN	NS	e.root-servers.net.
.			160971	IN	NS	j.root-servers.net.
.			160971	IN	NS	k.root-servers.net.
.			160971	IN	NS	g.root-servers.net.
.			160971	IN	NS	m.root-servers.net.
.			160971	IN	NS	c.root-servers.net.
.			160971	IN	NS	b.root-servers.net.
.			160971	IN	NS	l.root-servers.net.
.			160971	IN	NS	f.root-servers.net.
.			160971	IN	NS	a.root-servers.net.
.			160971	IN	NS	d.root-servers.net.
.			160971	IN	NS	i.root-servers.net.
.			160971	IN	RRSIG	NS 8 0 518400 20170505050000 20170422040000 14796 . QQE/XeixW1xZtSC/G7hyLSTVgIo3G4QKD+ohCHAheoKsbchSoEZepPuy +RTLTe9OTGIgT2WOQxKH+YaJcgmWEZJYKGujaN2+/P6gleV6r5fjqTcv s6wjib9g0sBuwmPvASMkF0gVzcgsxKT2DiCKE6Eh1qrkQPZ2zG7DaEFp 2v4Ympk3x0jvPcPQ4YV4ehUTVdh3u3CZJw51rWujogFZIn4yAFzBy39k pyWrDGzf6kpxibQIAP3vgvh4mIQ2wgE983XDQpVnRNe2mKZVgzXdVNcL fBN7ETPWwWzvMfaOJtMjj69f2XU88UCcYXNBIUkxu0/2OxwmGrr/+9es Bg2v5w==
;; Received 525 bytes from **172.42.0.2**#53(172.42.0.2) in 5 ms

uk.			172800	IN	NS	dns2.nic.uk.
uk.			172800	IN	NS	dns4.nic.uk.
uk.			172800	IN	NS	nsc.nic.uk.
uk.			172800	IN	NS	nsa.nic.uk.
uk.			172800	IN	NS	nsd.nic.uk.
uk.			172800	IN	NS	nsb.nic.uk.
uk.			172800	IN	NS	dns3.nic.uk.
uk.			172800	IN	NS	dns1.nic.uk.
uk.			86400	IN	DS	43876 8 2 A107ED2AC1BD14D924173BC7E827A1153582072394F9272BA37E2353 BC659603
uk.			86400	IN	RRSIG	DS 8 1 86400 20170506170000 20170423160000 14796 . BvvKEJ3iYvfLclB6xRshKMPlgNf1wQ/MkIHMCNHLj+70xdlGLlwKwht/ t3CqEsG7ttevcWqjAYHLk6wo2Zo1pnmkgFIOxCsVt5XDL4fCS8vqxXS+ YZTiFarQBA3inY5dBT7d3qX1R3rtqSApQIMKpxyPSrAeuI4Ffmp7tYz6 ATczSMY+i9+WveHE6I8Wat+JfeYjkZOZyZdTK4YRYmySPXfopfqr4PoA 1sd21xbR8ICzrusiK4bdFTcXSckh7X9XSf5U1rPrS2iwq+6Xardtgpyo WbyaDDaYUaue3NzzPdVog3NBVoLUvvSeZV1C83u+WrdZcYTMjNaVRIpd 2E8kaQ==
;; Received 796 bytes from 192.5.5.241#53(f.root-servers.net) in 6 ms

google.co.uk.		172800	IN	NS	ns2.google.com.
google.co.uk.		172800	IN	NS	ns1.google.com.
google.co.uk.		172800	IN	NS	ns3.google.com.
google.co.uk.		172800	IN	NS	ns4.google.com.
G9F1KIIHM8M9VHJK7LRVETBQCEOGJIQP.co.uk.	10800 IN NSEC3 1 1 0 - G9HKV8PHGJ1NMH94L9RMIQM0J64UCIPK  NS SOA RRSIG DNSKEY NSEC3PARAM TYPE65534
G9F1KIIHM8M9VHJK7LRVETBQCEOGJIQP.co.uk.	10800 IN RRSIG NSEC3 8 3 10800 20170526173935 20170421172818 33621 co.uk. TyzKkWqE/6oSF46oJXpWTkYo6lS/DQETIdotc9vbD9I9qTeWnG/N0ZnI mIn1PdJrsZfzfOxAh7KFyNLNqah/zcH1xgPvNFb2qo8e28fess8qUQ4C UXTRLIk2tKJEEoaBt58vBqNJUNw2kK2QqdWJFbkEWDAqIY3F+3orU2Cq 1Is=
6QBKBNAG7S31BK9GASHT6JNSE1METDMS.co.uk.	10800 IN NSEC3 1 1 0 - 6QFMQOSHM19DRDSSFVAAQI1R7UKV1LET  NS DS RRSIG
6QBKBNAG7S31BK9GASHT6JNSE1METDMS.co.uk.	10800 IN RRSIG NSEC3 8 3 10800 20170524162922 20170419160301 33621 co.uk. WKL+jHpeetpb4zoWGKURtG5K2onQRZbNjCdAZPnfYO7JmiNF0AyQq/GC rgzmVZbqJgUmO25ylRB9kOtl0ZSPn42weMuBprKFU1qr/spvnDBEbyce t9Q2aZWgniMboq8TckrYe/GbFCF1HbgZsIRXfcXGAUMF8YLhl9LFP1Yj yOM=
;; Received 646 bytes from 156.154.101.3#53(nsb.nic.uk) in 24 ms

google.co.uk.		300	IN	A	64.233.184.94
;; Received 46 bytes from 216.239.32.10#53(ns1.google.com) in 8 ms`

Notice the address in bold is correct here.

However if I leave resolv.conf set up as the default set by docker (which is to use the forwarding inbuilt DNS server), this is the result:


; <<>> DiG 9.10.4-P6 <<>> +trace google.co.uk
;; global options: +cmd
.			22459	IN	NS	e.root-servers.net.
.			22459	IN	NS	h.root-servers.net.
.			22459	IN	NS	l.root-servers.net.
.			22459	IN	NS	i.root-servers.net.
.			22459	IN	NS	a.root-servers.net.
.			22459	IN	NS	d.root-servers.net.
.			22459	IN	NS	c.root-servers.net.
.			22459	IN	NS	b.root-servers.net.
.			22459	IN	NS	j.root-servers.net.
.			22459	IN	NS	k.root-servers.net.
.			22459	IN	NS	g.root-servers.net.
.			22459	IN	NS	m.root-servers.net.
.			22459	IN	NS	f.root-servers.net.
.			22459	IN	RRSIG	NS 8 0 518400 20170503190000 20170420180000 14796 . L93H1JlYlso6aA5iPBmAWo1ZxMQJVtHruhWiZBTkKLO6OsH1JzvOOQOn LVK3c9gUdthwFTpkueC1qq5bzLqZamPPl4nmf5Frw6sI4oahN9UXOOez qwv/cW531FH6i+viBuVqhGl3f/9k5OooC6IPNsY7xQUkAoiGIY/x77SD atbN/GCpOLSRI3QdMf/OQ4Fon5LW89BZs38K1AZjdPC6vShAtfN1gEyf iYLymR9cLOry/XdaCiFNtz0G4OS3ZvRhLkAeXv8WLyo2/So35UD1HaIf rL3r0hjhubYJcTJnQnNOEFCsWz405vCTJ0juZO0tXrJx1LpUeJrB33i2 B5rf8g==
;; Received 525 bytes from **127.0.0.11**#53(127.0.0.11) in 4 ms

uk.			172800	IN	NS	nsc.nic.uk.
uk.			172800	IN	NS	nsd.nic.uk.
uk.			172800	IN	NS	dns4.nic.uk.
uk.			172800	IN	NS	dns3.nic.uk.
uk.			172800	IN	NS	nsb.nic.uk.
uk.			172800	IN	NS	dns1.nic.uk.
uk.			172800	IN	NS	nsa.nic.uk.
uk.			172800	IN	NS	dns2.nic.uk.
uk.			86400	IN	DS	43876 8 2 A107ED2AC1BD14D924173BC7E827A1153582072394F9272BA37E2353 BC659603
uk.			86400	IN	RRSIG	DS 8 1 86400 20170506170000 20170423160000 14796 . BvvKEJ3iYvfLclB6xRshKMPlgNf1wQ/MkIHMCNHLj+70xdlGLlwKwht/ t3CqEsG7ttevcWqjAYHLk6wo2Zo1pnmkgFIOxCsVt5XDL4fCS8vqxXS+ YZTiFarQBA3inY5dBT7d3qX1R3rtqSApQIMKpxyPSrAeuI4Ffmp7tYz6 ATczSMY+i9+WveHE6I8Wat+JfeYjkZOZyZdTK4YRYmySPXfopfqr4PoA 1sd21xbR8ICzrusiK4bdFTcXSckh7X9XSf5U1rPrS2iwq+6Xardtgpyo WbyaDDaYUaue3NzzPdVog3NBVoLUvvSeZV1C83u+WrdZcYTMjNaVRIpd 2E8kaQ==
;; Received 796 bytes from **192.228.79.201**#53(b.root-servers.net) in 139 ms

google.co.uk.		172800	IN	NS	ns1.google.com.
google.co.uk.		172800	IN	NS	ns2.google.com.
google.co.uk.		172800	IN	NS	ns3.google.com.
google.co.uk.		172800	IN	NS	ns4.google.com.
g9f1kiihm8m9vhjk7lrvetbqceogjiqp.co.uk.	10800 IN NSEC3 1 1 0 - G9HKV8PHGJ1NMH94L9RMIQM0J64UCIPK  NS SOA RRSIG DNSKEY NSEC3PARAM TYPE65534
g9f1kiihm8m9vhjk7lrvetbqceogjiqp.co.uk.	10800 IN RRSIG NSEC3 8 3 10800 20170526173935 20170421172818 33621 co.uk. TyzKkWqE/6oSF46oJXpWTkYo6lS/DQETIdotc9vbD9I9qTeWnG/N0ZnI mIn1PdJrsZfzfOxAh7KFyNLNqah/zcH1xgPvNFb2qo8e28fess8qUQ4C UXTRLIk2tKJEEoaBt58vBqNJUNw2kK2QqdWJFbkEWDAqIY3F+3orU2Cq 1Is=
6qbkbnag7s31bk9gasht6jnse1metdms.co.uk.	10800 IN NSEC3 1 1 0 - 6QFMQOSHM19DRDSSFVAAQI1R7UKV1LET  NS DS RRSIG
6qbkbnag7s31bk9gasht6jnse1metdms.co.uk.	10800 IN RRSIG NSEC3 8 3 10800 20170524162922 20170419160301 33621 co.uk. WKL+jHpeetpb4zoWGKURtG5K2onQRZbNjCdAZPnfYO7JmiNF0AyQq/GC rgzmVZbqJgUmO25ylRB9kOtl0ZSPn42weMuBprKFU1qr/spvnDBEbyce t9Q2aZWgniMboq8TckrYe/GbFCF1HbgZsIRXfcXGAUMF8YLhl9LFP1Yj yOM=
;; Received 646 bytes from 43.230.48.1#53(dns4.nic.uk) in 33 ms

google.co.uk.		300	IN	A	64.233.184.94
;; Received 46 bytes from 216.239.38.10#53(ns4.google.com) in 9 ms}


Notice the addresses in bold, it goes straight from the docker dns server of 127.0.0.11 to an external DNS at 192.228.79.201

As far as I can see it entirely bypasses my dnsmasq container. This sounds like a fairly serious flaw since I would have thought the internal docker server should pass any external request to the server mentioned in --dns. This doesn't seem to be the case.

**Comment by Astridax** [comment] 2017-04-23 23:00
Strangely enough setting --dns to something invalid such as the IP of a non-existent container totally breaks DNS resolution entirely. I thought the built in docker DNS was meant to forward to 8.8.8.8 as a fall back? 

On the topic of the main issue, possibly docker DNS server is forwarding to my dnsmasq container and it is somehow omitted on dig +trace?
