### ISSUE TITLE
docker pull does not work for full image IDs

### ISSUE THREAD

**Issue by stevenschlansker** [docker/docker#8720] opened 2014-10-22 23:36 UTC
```
[steven@Anesthetize:~]% docker inspect registry/myimage:ccc37e2cc08a61eb1a7b581961db648d936862cdd0b2246d1abd8cb754c9b258
[{
...
    "Created": "2014-10-21T17:22:52.457185801Z",
    "DockerVersion": "1.2.0",
    "Id": "ccc37e2cc08a61eb1a7b581961db648d936862cdd0b2246d1abd8cb754c9b258",
    "Os": "linux",
    "Parent": "2a7b229528cb79d8edb541cbac27cfecef5c75784bdeb67365527bb0634c3754",
    "Size": 0
}

[steven@Anesthetize:~]% docker pull registry/myimage:ccc37e2cc08a61eb1a7b581961db648d936862cdd0b2246d1abd8cb754c9b258
Pulling repository registry/myimage
2014/10/22 16:31:37 Tag ccc37e2cc08a61eb1a7b581961db648d936862cdd0b2246d1abd8cb754c9b258 not found in repository registry/myimage

[steven@Anesthetize:~]% docker run registry/myimage:ccc37e2cc08a61eb1a7b581961db648d936862cdd0b2246d1abd8cb754c9b258
<normal bootup>
```

**Comment by jfrazelle** [comment] 2015-02-26 01:34
closing as duplicate of https://github.com/docker/docker/issues/4106

**Closed by jfrazelle** 2015-02-26 01:34 UTC
