### ISSUE TITLE
[legal] What's about repository names for your open-source projects starting with 'docker'?

### ISSUE THREAD

**Issue by schmunk42** [docker/docker#26556] opened 2016-09-14 07:47 UTC
**Description**

Yesterday there was a blog posting about [Don't use "docker" in Github repo names or as Twitter handles](https://www.andreas-jung.com/contents/dont-use-docker-in-github-repo-names-or-as-twitter-handle), which got some real attention. I.e. it was [linked](https://blog.fefe.de/?ts=a926d889) on one of Germany's most read tech blogs.

I understand there there is a trademark for "Docker" and that this has to be enforced. 

But the posting states explicitly 

> In particular you are not allowed to use repository names for your open-source projects starting with 'docker'

I read through https://www.docker.com/trademark-guidelines but could not find a paragraph explicitly stating that, rather

> The Docker mark is used only in a referential context or for naming Docker or to indicate compatibility, and not in a title of a program, domain name, website, product or service

Could you please clarify that.

**Steps to reproduce the issue:**

1. Name an open-source repo on GitHub "docker-whatever" (*)

(*) to indicate that this is a build on DockerHub or a docker-compose setup for my "whatever" project.

**Describe the results you received:**

Hypothetically get sued by Docker Inc.

**Describe the results you expected:**

Helping the open-source community by sharing my code.

**Additional information you deem important (e.g. issue happens only occasionally):**

I did not mail this to legal@docker.com, since I think this is important for the community.

**Comment by nyanloutre** [comment] 2016-09-14 09:31
They will have some work with more than 100k [repositories with the name docker in the title](https://github.com/search?utf8=%E2%9C%93&q=docker)

**Comment by axzxc1236** [comment] 2016-09-14 11:27
I wonder if people just fork this repo (don't make any changes) are also affected.
Well, just forked to find out.

**Comment by nyanloutre** [comment] 2016-09-14 11:51
According to the Apache license : 

>    6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
origin of the Work and reproducing the content of the NOTICE file.

I think "describing the origin of the Work" is exactly what the devs are doing by naming their repositories docker-xxxx

**Comment by thaJeztah** [comment] 2016-09-15 10:39
@axzxc1236 

> I wonder if people just fork this repo (don't make any changes) are also affected. Well, just forked to find out.

That should not be a problem!

**Comment by thaJeztah** [comment] 2016-09-15 10:40
@schmunk42 thanks for opening this! I agree that some more information can be useful for people, so I asked the "trademark" / "legal" / "whatever" (I'm not a lawyer, bear with me :smile:) to provide a bit more information about what's "ok" and what not. First of all, in all cases that I'm aware of, Docker Inc. will **not** directly sue someone, and always open a conversation first ("Hey, we noticed that ..., could you change this or that"), so don't be afraid to find the police banging on your front door in the middle of night :wink:.

All jokes aside; I got an initial reply from Docker, Inc. that should give some more information. They're also working on a more extended description with "good" and "bad" examples, and once that's there, I think it'll be added to the website, and possibly copied (or linked to) from the GitHub repository and documentation.

Here's the "boring stuff":

> We want to clarify that Docker has no objection to you using “Docker” in your
> repo name. However, because of trademark legal requirements, we ask that it is
> not the first part of the name. For example, please do not use “Docker-xyz”,
> but Docker has no objection to “xyz-Docker” or “xyz for Docker”. Your repo can
> have Docker in the name, but the naming convention needs to be clear to avoid
> confusion.

> We appreciate the community’s concerns and we believe this policy strikes a
> fair balance between the needs of the open-source community and brand
> protection for Docker. It gives the community the ability to indicate
> compatibility or utility with Docker, while also allowing Docker to meet legal
> obligations relating to brand use.


Again, I appreciate you reaching out for more information; I'll close this issue here, because it's not really a bug / issue in this repository, but feel free to reply after I closed.

Also, if you're unsure if one of your projects / websites / repositories is not in compliance with the trademark guidelines, and you don't want to contact "legal" directly, feel free to send me a direct message on IRC (my handle is thaJeztah), or send me an e-mail (sebastiaan@docker.com), then I'll try to get in touch with the team to help out.

**Closed** 2016-09-15 10:41 UTC

**Comment by schmunk42** [comment] 2016-09-15 12:53
@thaJeztah 

> Hey, we noticed that ..., could you change this or that"

I want to refer to ["the kik-case"](https://medium.com/@mproberts/a-discussion-about-the-breaking-of-the-internet-3d4d2a83aa4d#.5251yc4zy) which occurred a few months ago - which is at least related to this issue.

Long story short, my concern is simply about breaking the infrastructure, if you change the name of a repo it might cause really big trouble and lots of wasted work hours. And I strongly assume the community would not like that at all.

The fact is there are 10.000s repos out there named "docker-blablabla". 

It's like not having "legal security" as a developer or user about the resources you use, if this might change anytime in the future. (For sure they can change also for other reasons, but the point is about the trademark). It's the same, when there is no absolutely clear policy about repo-names from Docker.

My opinion is, that it's simply too late for Docker to enforce this - for how long does this policy exist?

A viable solution would be, that you don't ask the developer to change the name, but to add a line stating "This repository is a community contribution for the Docker® ecosystem...." - something that sounds nice.

**Comment by thaJeztah** [comment] 2016-09-15 13:53
@schmunk42 I'll pass on your concerns, and will let you know if there's an additional response (sorry if I can't provide more information at this moment, hope you understand)

**Comment by schmunk42** [comment] 2016-09-15 20:56
What's about saying, that only a repo like "docker/compose" is starting starting with "docker" and "mycompany/docker-cooltool" is not 😺

**Comment by estesp** [comment] 2016-09-15 22:26
I needed an excuse to finally be one of the cool people and play with GH BigData Query. Thank you. :)

Interestingly, the search that shows any use of Docker from the GH search bar can be narrowed considerably in a few ways; one of which is to be more specific in where the use of "docker" lands in the repo name.  Take this GH Big Data Query:
```
SELECT repo_name, 
              REGEXP_EXTRACT(repo_name, '.*/(.*)$') AS afterslash
FROM [bigquery-public-data:github_repos.languages]
WHERE 
              Length(REGEXP_EXTRACT(repo_name, '.*/(.*)$')) > 6 AND Left(REGEXP_EXTRACT(repo_name, '.*/(.*)$'), 6) = 'docker' 
```

I want all repos that start with `docker` after the "slash", but aren't only "docker" as it appears that 40,000 of the 100k repos are called simply "docker" of language "Shell", which after inspection of a small sample, "docker" is most commonly used as a repository for the `Dockerfiles` of a project!  There are also 600+ repos simply named "dockerfile" or "dockerfiles" which you can expect you know what's in there. When you remove all those, you are left with about 15k repositories that are prefixed with `docker-`.

Interestingly a large number of them appear to be clones with changes of base DockerHub images (docker-mysql, docker-wordpress, etc.); as people have taken these and configured them with special settings, versions, etc; and then assuming they are building those and publishing to a private or public registry as their variant of a base image.  In the end, it seems like there is still potentially clarification for some uses, but it does not seem as large as one would suggest from a broad search of the word docker in any repo on GH.

**Comment by JonasT** [comment] 2016-09-16 14:54
Here is a source for this practice:

https://www.andreas-jung.com/contents/dont-use-docker-in-github-repo-names-or-as-twitter-handle

Could you imagine what happened if the Python Foundation started sending out legal letters to e.g. someone providing a python-irc module for internet relay chat use?
This practice is super silly and should be stopped. If you are really so super-worried about a few 100% open-source projects using "docker" in the name in a *purely descriptive manner*, write up proper guidelines and stop sending legal letters to everyone as if you had Oracle aspirations.

@thaJeztah also I suggest reopening this issue until this has been properly addressed by docker with an official response about this practice. Given the article above, we at least deserve a proper public statement on whether this has actually been going on, and how this is going to be addressed in the future.
