### ISSUE TITLE
Client Server Program each running as a Container Not Able to Communicate with each Other Using POSIX Socket API

### ISSUE THREAD

**Issue by vikasr04** [docker/docker#22904] opened 2016-05-23 12:06 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Issue Description with Steps to Reproduce:
I have a Server program written in C++ ,using posix Socket API. The Dockerfile used for building the Server image is:
```
$ cat Dockerfile
FROM gcc:4.9
WORKDIR /home/vikrana
COPY . .
EXPOSE 1001
RUN g++ -o testcplusplus testprogram.cpp
ENV PATH /home/vikrana:$PATH
ENTRYPOINT ["testcplusplus", "1001"]
```
Below is the link for the Server program written in C++.
[testprogram.txt](https://github.com/docker/docker/files/277384/testprogram.txt)

Following is the Docker command I am using to run my server program in the container:
```
$ docker run --net=user_def_nw -ti -P --name server1 my-server-app
```
On running above command the container gets attached with user_def_nw and an IP address "172.18.0.2" is assigned to the container, which is always is the case. The same IP address I have used in my server program cpp file. 

Command to  identify the host port where the container server1 is listening for any incoming request
```
$ docker port server1
1001/tcp -> 0.0.0.0:32768
```
On the other hand following are the details of my Client program written in C++ using posix Socket API.
DockerFile to create client image:
```
$ cat Dockerfile
FROM gcc:4.9
WORKDIR /home/vikrana
COPY . .
RUN g++ -o testcplusplus testclientprogram.cpp
ENV PATH /home/vikrana:$PATH
ENTRYPOINT ["testcplusplus", "172.18.0.2", "1001"]
```
Below is the link for the Client program:
[testclientprogram.txt](https://github.com/docker/docker/files/277390/testclientprogram.txt)

Following is the Docker command I am using to run my client program in the container:
```
$ docker run --net=user_def_nw -ti --name cli1 my-client-app
```
On running the above command it is noticed Client is not able to connect to the server at IP: 172.18.0.2 listening at port 1001.

The error code return my the connect API is "111" which means, connection refused.

My understanding is since both the containers namely server1 and cli1 are attached to the same user defined network "user_def_nw" bridge network, they should be able to communicate with each other over Socket. But here connect API itself is failing to establish connection with the Server.
Please help me out in solving this issue.

Note: My client and server program are written in C++.

**Output of `docker version`:**
```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```
**Output of `docker info`:**

```
$ docker info
Containers: 31
 Running: 0
 Paused: 0
 Stopped: 31
Images: 209
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 190
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10
22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: NKOP:JPNZ:6X7J:SZHG:YUNP:35JK:JWT5:4KME:ANGS:FJQD:I6RR:YO3L
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 22
 System Time: 2016-05-23T11:45:46.31574063Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**

I have setup a Docker in Windows 7 machine.
My Docker Host is running on VM installed in Windows as part of Docker installation setup.

Please help me out in solving this issue.
Let me know if any more additional information is required about my environment.

**Comment by thaJeztah** [comment] 2016-05-23 12:43
First of all, you should not rely on those ip-addresses as they are random. For user-defined networks, simply connect using the *name* of the container, or an alias if you provided this

For example

```bash
docker network create my-network
docker run -d --net my-network --name myserver nginx:alpine

docker run -it --rm --net my-network --name myclient alpine sh
/ # ping -c3 myserver
PING myserver (172.22.0.2): 56 data bytes
64 bytes from 172.22.0.2: seq=0 ttl=64 time=0.079 ms
64 bytes from 172.22.0.2: seq=1 ttl=64 time=0.094 ms
64 bytes from 172.22.0.2: seq=2 ttl=64 time=0.072 ms

--- myserver ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.072/0.081/0.094 ms

exit
```

You mentioned you're trying to connect using a *socket*. Containers have their own private filesystem, so if the server creates a socket somewhere in the server filesystem, the client won't be able to connect to that. You can possibly use a *volume* and use the same volume for both containers, so that the client can access the socket that the server created, something like;

```
docker run -d --volume shared:/sockets/ my-server
docker run -d --volume shared:/sockets/ my-client
```

Then both "client" and "server" share the "/sockets/" directory. However, doing this makes your containers non-portable, because they always have to be running on the same machine / host (which limits its use if you're running on multiple nodes, for example, on Swarm). I'd really recommend using a regular tcp connection, not sockets.

Finally, I noticed you're using the "legacy link" environment variables (e.g. `CLISERV_PORT_1001_TCP_ADDR`). These environment variables are deprecated, and only used for "legacy links" in the default network, not for user-defined networks. Just make your server listen on `0.0.0.0` and your client should be able to connect over tcp/ip.


I'm going to close this issue, because this is a support question, not a bug, and the GitHub issue tracker is not intended for that. Please use either one of:

- forums.docker.com
- the #docker IRC channel
- StackOverflow

As mentioned, I'll close this issue, but I hope the above helps you further. But feel free to comment after I closed

**Closed by thaJeztah** 2016-05-23 12:43 UTC
Labels: version/1.10

**Comment by vikasr04** [comment] 2016-05-23 17:48
Thanks for your comment. I have got more clear understanding on Container communication in Docker. In future I will raise such queries in forums.docker.com
I have few more queries, related to this for my better understanding:

1) In my Dockerfile for creating server image, I have exposed port 1001 and the same I am publishing while running the server image in my container. Below is the command again I am mentioning for reference:
$ docker run --net=user_def_nw -ti -P --name server1 my-server-app

When the server container starts;  the exposed port 1001 is mapped to a randomly chosen port in the host machine. Hence the actual port where the server is listening is different from the one which is exposed.
This I verified, by running the following Docker command: 
$ docker port server1
1001/tcp -> 0.0.0.0:32768

Now, it is Docker daemon responsibility to forward incoming connection request on a given exposed  port of a given network interface to actual listening port in a given user defined network. But I think that is not happening.

Based on your statement:
>> Just make your server listen on 0.0.0.0 and your client should be able to connect over tcp/ip.

Now, I am running my client container by linking it to the server container. Also I am no more using deprecated env variables in my program.
Modified version of client program:
[testclientprogram.txt](https://github.com/docker/docker/files/277934/testclientprogram.txt)

$ docker run --net=user_def_nw -ti --link server1:cliserv --name cli1 my-client
-app

And also in my client program, I am making specifying the usage of tcp protocol in socket API to establish the connection with the server program. Still I am getting connection refused error in my client program.

Note: I checked ping utility program, it also make use of socket API to establish connection with the target. Then why ping utility is able to establish connection and not my client program ?

**Comment by thaJeztah** [comment] 2016-05-23 18:19
>  I have exposed port 1001 and the same I am publishing while running the server image in my container. 

You only need to *publish* the port (`-p` / `-P`) if you need the port to be accessible on the public network interface of the docker host. If you want to connect between containers on the same ('container-container') network, you don't have to publish those ports. Container can directly access the other container, using the "regular" (non-random) port, so for example, a web server listening on port 80, can be accessed by other containers on port 80 (if they are in the same network)


> Note: I checked ping utility program, it also make use of socket API to establish connection with the target. Then why ping utility is able to establish connection and not my client program ?

Ok, perhaps I misunderstood your use case (and I'm not a C/C++ developer :D); I thought you wanted to use create a socket (similar to `/var/run/docker.sock`, and have the client connect to that socket)

**Comment by thaJeztah** [comment] 2016-05-23 18:20
You can find more info on networking in docker here; https://docs.docker.com/engine/userguide/networking/dockernetworks/

**Comment by vikasr04** [comment] 2016-05-24 03:35
>> Container can directly access the other container, using the "regular" (non-random) port, so for example, a web server listening on port 80, can be accessed by other containers on port 80 (if they are in the same network)

Then in my server program , I am using "listen" API of the socket library to **listen** for incoming request on port 1001. ( On similar line, in webserver source code written in any langugae, might  be using certain functions provided to listen on port 80 )

On the other side i.e on my client program, I am using "connect" API of the socket library to **connect** to port 1001. But the connection is getting refused.  ( On similar line, the client source code written in any language, might be using certain functions provided to connect to port 80 )

My question remains same, why by using C/C++ socket API, I am not able to establish the connection. Is there some limitation at Docker level, or my understanding is going wrong some where.
I sincerely and very curious  to know the reason for this behaviour of my programs in Docker.
My apologies, if I am missing anything to understand the Docker networking feature.

Thanks for sharing the link. I went through this documentation, but was not able to find an answer still for this behaviour.

**Comment by thaJeztah** [comment] 2016-05-24 09:31
Is the server listening on `0.0.0.0`, not just on a single IP address?

**Comment by vikasr04** [comment] 2016-05-24 10:12
Yes, the server is listening on 0.0.0.0
I ran the following command to verify, after my server container was up and running:

$ docker port server1
1001/tcp -> 0.0.0.0:32769

**Comment by thaJeztah** [comment] 2016-05-24 11:08
that can be misleading, because that only shows what port-mapping docker made. If the server itself doesn't listen on 0.0.0.0:1001, it would still show that. For example;

```bash
docker network create something
docker run -dit -p 1234:5678 --net=something --name not-a-server busybox sh
docker port not-a-server
5678/tcp -> 0.0.0.0:1234
```

So docker forwards connections from the "host" interface port 1234 to the container's 5678, but there's nothing listening in the container.

Same goes for connecting from another container on the container-container network;
```
docker run -it --rm --net=something alpine sh
/ # apk add --no-cache curl
(......)
/ # curl http://not-a-server:5678
curl: (7) Failed to connect to not-a-server port 5678: Connection refused
```

**Comment by vikasr04** [comment] 2016-05-24 17:39
To verify if my server container is actually listening on port 1001, I stopped , and then started my server  container again. This time the port mapping to host was:

$ docker port server1
1001/tcp -> 0.0.0.0:32770

Then I logged into into the VM which is acting as my DOCKER_HOST using the following command:
$ docker-machine ssh default

After logging into VM, I ran the netstat command to check the port status: 
docker@default:~$ sudo -s
root@default:/home/docker# netstat -tulpn
Active Internet connections (only servers)
Proto  Recv-Q  Send-Q     Local Address           Foreign Address         State   PID/Program name
tcp        0            0                 0.0.0.0:22              0.0.0.0:*               LISTEN     1243/sshd
tcp        0            0                  :::32770                 :::*                    LISTEN         2506/docker-proxy
tcp        0            0                  :::2376                   :::*                    LISTEN        1471/docker

The second entry indicates docker-proxy process is listening on port 32770.

My guess from this o/p is; any incoming request should be forwarded to the container running the server image by the docker-proxy process. I guess that is not happening here, and hence client is not able to establish the connection.

Another case, could be as my server and client image is build on the base image of gcc:4.9.
So running my server and client images, as a container, might not work properly with base image as gcc:4.9.  Better would have been, making my base image as ubuntu, or centos, or some linux flavour OS and then creating my client and sever images on these linux flavour images. But this will make my image size very huge.
Till now my understaning on Docker was, you create your own images, from those base images which are required by you to build and run your application as a container. Rest of the dependency stuff docker should take care.
Not sure, to resolve this issue, should I change my base image to some Linnux OS and then try and see ?

**Comment by thaJeztah** [comment] 2016-05-24 18:50
wrong assumption; the fact that the docker-proxy is listening, doesn't mean the server inside your container is working correctly. Same example as before;

```
docker run -dit -p 1234:5678 --name not-a-server busybox sh
netstat -tulpn

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:6000            0.0.0.0:*               LISTEN      9589/3
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      32344/sshd
tcp6       0      0 :::6000                 :::*                    LISTEN      9589/3
tcp6       0      0 :::80                   :::*                    LISTEN      17618/docker-proxy
tcp6       0      0 :::1234                 :::*                    LISTEN      9697/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      32344/sshd
```

The fact that port `1234` is opened here, doesn't guarantee that there's something inside the container that's listening, or accepting connections

**Comment by vikasr04** [comment] 2016-05-25 02:54
>  the fact that the docker-proxy is listening, doesn't mean the server inside your container is working correctly.

Then, what conclusion I am able to make it out is the C Socket library provided by POSIX for communicating over Socket using tcp protocol will not work when a given C/C++ program is run as a container in Docker.

**Comment by vikasr04** [comment] 2016-05-26 04:18
I would like to open this issue.
