### ISSUE TITLE
Add an option to docker rm to also stop the container if necessary

### ISSUE THREAD

**Issue by abhijitsarkar** [docker/docker#18934] opened 2015-12-28 09:41 UTC
`docker rm -s -f xxx yyy zzz` will stop and remove all specified containers. Currently I get by with the following:
`docker ps -a | awk '!/CONTAINER/ {system("docker stop "$1); system("docker rm -f "$1)}'`

Or better, make `-f` do it. Why is `-f` even there if the container removal cannot be forced?

**Comment by thaJeztah** [comment] 2015-12-28 11:23
> Or better, make -f do it. Why is -f even there if the container removal cannot be forced?

What issue are you seeing when you `docker rm -f` a running container? `docker rm -f` [should send a `SIGKILL` to stop/kill the container](https://docs.docker.com/engine/reference/commandline/rm/). Does this not work for you? What version of docker are you running?

**Comment by abhijitsarkar** [comment] 2015-12-28 11:33
`rm -f` won't remove a running container, only stopped ones. I'm proposing that there be an additional option to stop and remove at the same time or just make `-f` stop and remove. Regular `rm` could just remove stopped ones and leave running ones alone.

**Comment by cpuguy83** [comment] 2015-12-28 13:16
@abhijitsarkar `docker rm -f` will stop the container and then remove it.
If it's not, then something is wrong.

**Comment by thaJeztah** [comment] 2015-12-28 13:38
@cpuguy83 I actually just ran into this on an old ubuntu droplet. Possibly apparmor is at play here;

```
Dec 28 08:36:32 dockr kernel: [ 1672.784648] audit: type=1400 audit(1451309792.818:372): apparmor="DENIED" operation="signal" profile="docker-default" pid=21725 comm="docker" requested_mask="receive" denied_mask="receive" signal=kill peer="/usr/bin/docker"
```

Will try a fresh droplet to see if that's still the case

**Comment by thaJeztah** [comment] 2015-12-28 13:54
Wasn't able to reproduce that on other droplets, or on a fresh one. Looks like that droplet had an old app armor profile around (`docker-engine`). Removing it resolved it for me.

**Comment by unclejack** [comment] 2016-01-18 08:40
`docker rm -f` works as intended and expected for me - it removes a running container. Please keep your systems up to date by installing all system updates. This should make sure you have the latest Docker versio and the latest distribution provided packages.

I'm going to close this now. Please feel free to comment.

**Closed by unclejack** 2016-01-18 08:40 UTC
Labels: status/more-info-needed
