### ISSUE TITLE
Help for designing the network 

### ISSUE THREAD

**Issue by rakesh91** [docker/docker#22217] opened 2016-04-21 06:22 UTC
Hi,
I am planning to put my elasticsearch cluster using Docker. As far as I read  using overlay network is the best approach. There is a need to access all the docker containers publicly. Also I tried to give docker_gwbridge a publicly accessible address, I was not successful. Can any one suggest the best way to create elasticsearch cluster this, other than using the exposing the port in native bridge?

**Comment by unclejack** [comment] 2016-04-21 06:38
Hello @rakesh91 

This issue tracker is dedicated to tracking Docker bugs, proposals and pull requests to make changes to Docker's source code. This issue tracker isn't a general support forum.
Please keep in mind that opening issues to ask questions when getting started will make everyone who contributes to the project spend more time looking at issues.

This kind of question and general support questions are more adequate for the following:
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.
4) StackOverflow https://stackoverflow.com/questions/tagged/docker

I'm going to close this issue now because the discussion can continue even after the issue is closed and there's no need to keep this issue open. Please feel free to continue the discussion. There's no need to open a new issue on this topic.

**Closed by unclejack** 2016-04-21 06:38 UTC

**Comment by rakesh91** [comment] 2016-04-21 06:47
@unclejack sorry for posting it here and thanks for the tips. Are there any standard/ best network  practice while creating clusters using docker?
