### ISSUE TITLE
[1.10-rc1] volume and network CLI command do not respect server version

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19749] opened 2016-01-26 21:30 UTC
Running `docker ps` with a newer binaries than the server will give you the error message

    Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.20)

The `volume` and `network` commands to not do the same.  For example `docker network ls`

    Error response from daemon: 404 page not found

**Comment by thaJeztah** [comment] 2016-01-26 22:42
Alright, so those are endpoints that are not yet present in the old daemon, which will give a 404. [The mismatch error is returned by the daemon](https://github.com/docker/docker/blob/59231ea6d8bdff3d32140d7ab28aeb98fb93ebff/api/server/middleware.go#L139-L157), but there's no endpoint for those new features, so that error-message isn't returned.

Perhaps we should include the Daemon version / API version in a header (also on a 404), so that we can make a nicer error-message in the client?

I wonder if this is a regression; possibly for these particular commands, but my guess is that this has always been like this for older versions as well?

**Comment by thaJeztah** [comment] 2016-01-26 22:44
However, I don't think we can fix this in 1.10, because for this particular case this would mean making changes in the *old* daemon?

**Comment by ibuildthecloud** [comment] 2016-01-26 23:58
Ah, i see the problem.... Hmmm...

**Comment by thaJeztah** [comment] 2016-01-27 00:22
@ibuildthecloud we left it on the milestone, to see if we can find a solution, but it's not top on our list :smile:

**Comment by thaJeztah** [comment] 2016-01-27 01:06
Alright, we briefly discussed this; and we don't think it's a *bug*, more an *enhancement*, so no need to keep it on the milestone.

Improving the handing in the client would be a nice enhancement though, so contributions welcome :+1:

**Comment by HackToday** [comment] 2016-01-27 02:33
A regiression issue ?


I tried RC build 


```
ubuntu@proxyserver:~$ ./docker-1.10.0-rc1 network ls
Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.21)
ubuntu@proxyserver:~$ ./docker-1.10.0-rc1 network  create 
docker: "network create" requires 1 argument.
See './docker-1.10.0-rc1 network create --help'.

Usage:	docker network create [OPTIONS] NETWORK-NAME

Creates a new network with a name specified by the user
ubuntu@proxyserver:~$ ./docker-1.10.0-rc1 network  create ok
Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.21)

```

**Comment by HackToday** [comment] 2016-01-27 02:34
hi @ibuildthecloud  did you tried this on latest docker client binary ? I tried on RC1

**Comment by HackToday** [comment] 2016-01-27 02:56
Also tried latest build (build from local master branch)

```
ubuntu@proxyserver:~$ cp docker/bundles/1.10.0-dev/binary/docker  dockertest
ubuntu@proxyserver:~$ ./dockertest network ls
Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.21)
```

**Comment by HackToday** [comment] 2016-01-27 02:56
I could not reproduce it. @thaJeztah

**Comment by thaJeztah** [comment] 2016-01-27 03:00
@HackToday; @ibuildthecloud was testing against a docker 1.8 daemon, which does not have `docker network create`; `client API version: 1.22, server API version: 1.20`

Docker 1.9 (API v1.21) already does, so won't produce a 404 error

**Comment by HackToday** [comment] 2016-01-27 04:48
Then did you mean we need fix it docker 1.8 ? If I understand it correctly, that in git docker 1.8 or lower(< 1.8)  tag.

**Comment by thaJeztah** [comment] 2016-01-27 07:17
@HackToday no, we won't fix it in 1.8, because we don't do patch-updates for older versions, but we could consider using a friendlier message if the client tries to reach an endpoint and gets a 404 response. Given that this is probably a corner-case we need to look if we can implement that in a clean way; if that's not possible, I consider this a "won't fix"

**Comment by calavera** [comment] 2016-02-08 18:50
I'd say that we should close this issue, what do you think @ibuildthecloud?

Afaik, this is not a real issue, old servers don't have those routes, therefore the 404 responses are valid.

**Comment by LK4D4** [comment] 2016-09-14 18:48
I'm closing this issue as inactive. Feel free to open new issue.

**Closed by LK4D4** 2016-09-14 18:48 UTC
Labels: area/cli, kind/enhancement
