### ISSUE TITLE
It should be possible to set the propagation mode of a container's mnt namespace

### ISSUE THREAD

**Issue by pmorie** [docker/docker#14630] opened 2015-07-14 17:42 UTC
Propagation modes control how mount and umount events propagate between mount namespaces.  In order to enable use-cases like a container that performs mounts that are visible to other containers (such as containerized Kubernetes/OpenShift), it should be possible to control the mount propagation mode of a container.  There is already an issue for this in runc, and a corresponding PR:

https://github.com/opencontainers/specs/issues/56
https://github.com/opencontainers/runc/pull/77

...but those don't cover docker until runc is integrated.  This issue is to make this functionality available in docker before runc is integrated.

@mrunalp @rhatdan @crosbymichael

**Comment by phemmer** [comment] 2015-07-14 18:57
Duplicate of #10088 for which a PR can be found at #14097

**Comment by pmorie** [comment] 2015-07-14 19:00
@phemmer It is actually not a dupe -- #10088 is about controlling which mount namespace the container runs in -- which is orthogonal to controlling the propagation mode of the mount ns.

**Closed** 2015-12-15 17:14 UTC
Labels: area/runtime, kind/feature
