### ISSUE TITLE
[1.12.0-rc5] Swarm init/Machine Daemon complains about multiple IP addresses

### ISSUE THREAD

**Issue by liamawhite** [docker/docker#25117] opened 2016-07-27 08:50 UTC
**Output of `docker version`:**

```
Docker version 1.12.0-rc5, build a3f2063
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 1.12.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: active
 NodeID: 8yycyamqr9wacalh74a8d3ayz
 Is Manager: true
 Managers: 1
 Nodes: 1
 Node Address: 9.173.166.160
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.38 GiB
Name: liam-ThinkPad-W550s
ID: P3IG:TF47:VJIH:HNMY:LD37:525C:LZOP:CIDX:KHXG:FKJ7:VSTU:FC2M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: liamwhite
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. `docker-machine create -d virtualbox --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v1.12.0-rc5/boot2docker-experimental.iso node1`
2. `docker-machine ssh node1 docker swarm init --listen-addr $(docker-machine ip node1):2377`

**Describe the results you received:**
Swarn fails to initialise returning the following error:
`Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses - specify one with --advertise-addr
exit status 1`

**Describe the results you expected:**
A working swarm leader

**Additional information you deem important (e.g. issue happens only occasionally):**
This worked yesterday with rc4

**Comment by thaJeztah** [comment] 2016-07-27 09:52
This is something that changed in RC5; if the machine has multiple network interfaces, initializing swarm mode requires you to specify which network interface / IP-address swarm should use as advertise address.

This was done to prevent cases where either the wrong interface was selected (for example, a "private" interface instead of a "public" one).

To initialize your swarm, run:

```
docker-machine ssh node1 docker swarm init --advertise-addr $(docker-machine ip node1)
```

Note that you don't need to set the *listen address* in most cases; it defaults to `0.0.0.0:2377`, so automatically listens to all interfaces.

**Comment by thaJeztah** [comment] 2016-07-27 09:52
I'll close this issue, because it's not a bug, but feel free to continue the discussion here

**Closed by thaJeztah** 2016-07-27 09:52 UTC

**Comment by liamawhite** [comment] 2016-07-27 10:03
Thanks! I understand that it isn't an official release so I don't expect this information to be there yet but `--advertise-addr` isn't in the docs yet. (Just FYI)

**Comment by thaJeztah** [comment] 2016-07-27 10:08
Ah! yes, that could well be, I think the docs were not updated yet with those changes; you can find them on GitHub though; https://github.com/docker/docker/blob/v1.12.0-rc5/docs/reference/commandline/swarm_init.md

sorry for the inconvenience; we usually don't publish docs yet for release candidates; 1.12 is a bit of an exception

**Comment by rss04** [comment] 2016-07-27 20:46
I see the similar issue even for rc4 and it looks it does not have --advertise-addr flag.
Issue details:
Output of   ``` docker --version ```

```
Docker version 1.12.0-rc4, build e4a0dbc, experimental
```
Output of  ``` docker info ```

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc5
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-boot2docker
Operating System: Boot2Docker 1.12.0-rc5 (TCL 7.2); HEAD : 9b97e11 - Tue Jul 26 22:20:20 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: manager
ID: LLUN:4H5E:YNT5:X7FV:EQUT:P5RH:KHKU:BZH4:OJRQ:Z5QU:QXMK:A5Y5
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2016-07-27T20:33:47.839485375Z
 EventsListeners: 0
Username: rss04
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```
Receiving error when running initi command with --listen-addr in rc4

Output of  ```docker swarm init --listen-addr $(docker-machine ip manager):2377```
```
No --secret provided. Generated random secret:
	0b87y0fvbv0p8tbkb5jgi6k2d

Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses
```
Tried using --advertise-addr in rc4 and I guess the flag is only available from rc5.

Output of  ```docker swarm init --advertise-addr $(docker-machine ip manager):2377```
```
unknown flag: --advertise-addr
See 'docker swarm init --help'.
```

Can you please help on how to resolve this ? I am using Docker for mac 1.12 rc4-beta20.

Thanks
rss

**Comment by rss04** [comment] 2016-07-27 20:55
Another thing I have observed which could be the issue is that I have created hosts using docker-machine commands. docker-machine command created servers with 1.12-rc5 while the Docker for mac has the docker client with 1.12-rc4. I am not sure if this caused any incompatibility and led to issues that I am facing.

docker version
**Client:
 Version:      1.12.0-rc4**
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

**Server:
 Version:      1.12.0-rc5**
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        Tue Jul 26 13:12:18 2016
 OS/Arch:      linux/amd64

**Comment by thaJeztah** [comment] 2016-07-27 21:01
@rss04 yes; rc4 and rc5 cannot join the same swarm

**Comment by rss04** [comment] 2016-07-27 21:31
thank you. I figured that is the issue and was able to resolve it by pulling the 1.12-rc4 boot2docker. 
It was good learning for me. It would be nice if there is a way to set client and server versions to remain the same on the docker-machine command.

Used below command to pull the 1.12-rc4 boot2docker
```
docker-machine create --driver virtualbox --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v1.12.0-rc4/boot2docker-experimental.iso manager1
```
Then I was able to run swarm init successfully.
```
docker swarm init --listen-addr $(docker-machine ip manager1):2377
No --secret provided. Generated random secret:
	9psxnowo64018uigb37onb0or

Swarm initialized: current node (e2pe6lhtoqodvcbzxkkygp5uq) is now a manager.

To add a worker to this swarm, run the following command:
	docker swarm join --secret 9psxnowo64018uigb37onb0or \
	--ca-hash sha256:5a970a9806f281d4fef4027027730f641137782d806bae90608f84f4630b5266 \
	192.168.99.103:2377
```

**Comment by LongLiveCHIEF** [comment] 2016-07-29 00:07
If you aren't using `docker-machine` to create your node's, (for example, I'm using Vagrant), then I've found this works as well:

```bash
docker swarm init --listen-addr eth0:2377 --advertise-addr eth1
```

Conventiently, the `swarm init` command will take either an `IP` or and `interface`.
