### ISSUE TITLE
docker is corrupting images imported from a tbz

### ISSUE THREAD

**Issue by ipeoshir** [docker/docker#19781] opened 2016-01-27 15:18 UTC
I am having issues running docker on my openSUSE 13.2.

Here is the information from "docker info":

---
Containers: 0
Images: 1
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-254:1-2456518-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.469 GB
 Data Space Total: 107.4 GB
 Data Space Available: 37.04 GB
 Metadata Space Used: 1.79 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.03.01 (2011-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.6-2-default
Operating System: openSUSE 13.2 (Harlequin) (x86_64)
CPUs: 1
Total Memory: 7.814 GiB
Name: tpa-eld7000-CoprHDDevKit
ID: CVYT:WQXL:T4LP:ZOZC:BU74:IYNM:EFZS:5GX4:WFHH:HVMK:E7HB:INWT
WARNING: No swap limit support

---

I can download and import the TBZ like this:
"cat image-2.5.0.0.9.tbz | docker import - image:2.5.0.0.9"

I need this specific image as it has the tools and binaries I use to build Makefile targets. I am running containers like this:
"docker run --rm --privileged --net=host -w /workspace -v "/workspace:/workspace" -v "/disks:/disks" image:2.5.0.0.9 make -f Makefile target"

Everything works fine and I get the targets created for the first time and maybe second. However, after some time I start to get random errors, here are some of them:

1) Structure needs cleaning
2) An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.21/containers/create: EOF
3) Error response from daemon: Unknown filesystem type on /dev/mapper/docker-254:1-2456518-b4fdcd5906e9dc038b3c261c0dd95e6866405e58a0385f1ff1fc3f3f49e19537-init

And others.
Restarting docker does not work, rebooting the system does not work, the only way to have the system back to normal is if I remove all files:

1) service docker stop
2) rm -fr /var/lib/docker
3) service docker start

But then I have to import the image again and again and this is taking a lot of time. Also its removing all images just because one that for some reason got corrupted.

I need this to be fixed, as wiping data every time I get a failure and corrupted image does not work for me.

Thanks,
Rodrigo.

**Comment by thaJeztah** [comment] 2016-02-01 15:26
What exactly do you mean with "after some time"? Is this after repeated imports of the image?

**Comment by ipeoshir** [comment] 2016-02-01 16:46
No, its after running running containers on that same imported image.

I can spawn the container for the first time just fine, but after I start using too much of the same image I start having errors and I have to remove /var/lib/docker and import my images to make it work again.

I switched to btrfs and I don't have any problems related to this anymore, it's only when using
 > Storage Driver: devicemapper

This setup did not have issues related to this:
docker info
Containers: 0
Images: 1
Server Version: 1.9.1
Storage Driver: btrfs
 Build Version: Btrfs v3.16.2+20141003
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.6-2-default
Operating System: openSUSE 13.2 (Harlequin) (x86_64)
CPUs: 1
Total Memory: 7.814 GiB
Name: opensuse
ID: X6HZ:KZ6R:DR3E:O4UB:P4I3:NRCA:RF22:HENI:7X66:O4U6:MNQY:XBH5
WARNING: No swap limit support

**Comment by thaJeztah** [comment] 2016-02-01 17:32
Sounds like it doesn't have to do with the "import" then?

**Comment by ipeoshir** [comment] 2016-02-01 17:36
No, its more like how docker is handling images when using device-mapper I would say...

**Comment by thaJeztah** [comment] 2016-02-01 17:38
The EOF is sometimes an indication that the system / devicemapper is running out of disk-space, so I wonder if that's what the issue here

**Comment by ipeoshir** [comment] 2016-02-01 17:52
The VM had a thin provisioned disk, just deployed so there was space available for it and space on my storage...

Another thing I noticed was with versions >= 1.9.0 and <= 1.9.1. If I just reboot and type "docker info" there is an error 404 and if I start importing container images right away there are errors related to "docker.sock"... I had to rollback to version 1.8.3.

**Comment by unclejack** [comment] 2016-02-01 21:10
`Kernel Version: 3.16.6-2-default` is most likely not a good kernel for btrfs because I've seen a bunch of bug reports from many people who were having problems with kernel 3.16.x.

**Comment by ipeoshir** [comment] 2016-02-02 12:09
The version 3.16.7 is what I can find for openSUSE:
- https://software.opensuse.org/package/kernel-default.

The issue I mentioned was related to device-mapper. I already mentioned that btrfs seems to working fine (after the initial instability after boot/service restart, which was not like this on version 1.8.3).

Also, I thought docker shouldn't be "forcing" us to choose a particular distribution. So if the latest kernel update from openSUSE 13.2 is 3.16.7, I believe it should be working fine on it.

**Comment by unclejack** [comment] 2016-03-07 09:49
Docker isn't forcing anyone to choose a particular distribution. Having to choose one distribution over another one is related to the provided kernel and to the chosen storage driver. btrfs is known to be badly broken on some kernel versions and there's nothing which can be done to fix that.

We've seen some pretty ugly bugs on kernel 3.16 and I would never recommend btrfs to anyone who has to use kernel 3.16.

This issue is related to using btrfs on a kernel version which is known to have bugs. Please keep in mind this isn't meant to imply the openSUSE developers are doing a bad job. Kernel 3.16 just happened to not have stable btrfs code and that kernel has long been deprecated on the mainline.

Devicemapper might be better on kernel 3.16. I'll close this issue now because I can't reproduce these issues with a newer kernel and the latest Docker.

If anyone happens to run into these issues with a newer kernel and the latest released Docker, please comment.

**Closed by unclejack** 2016-03-07 09:49 UTC
