### ISSUE TITLE
[Swarm] Fatal error joining manager

### ISSUE THREAD

**Issue by samber** [docker/docker#26487] opened 2016-09-12 09:15 UTC
I am actively testing Docker Swarm mode 1.12.1 but just met a fatal error. Raft Etcd implementation could be the issue origin.

Commands:
```
docker@swarm3:~$ docker swarm leave
docker@swarm3:~$ docker swarm join --token #my-very-long-manager-token# swarm1:2377
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: read unix @->/var/run/docker.sock: read: connection reset by peer
```

Docker logs:
```
time="2016-09-12T08:24:25.562986665Z" level=debug msg="swarm3: joined network 2llio77ukpifpxaocfpjpx0sk"
time="2016-09-12T08:24:25.563035225Z" level=debug msg="swarm3: Initiating bulk sync with nodes [swarm3]"
time="2016-09-12T08:24:25.563693297Z" level=debug msg="2016/09/12 08:24:25 [DEBUG] memberlist: Initiating push/pull sync with: 192.168.99.100:7946\n"
time="2016-09-12T08:24:25.779817506Z" level=info msg="77fdd4c82ef21fd4 [term: 1] received a MsgHeartbeat message with higher term from 6b6752326ea027e8 [term: 3]"
time="2016-09-12T08:24:25.780065414Z" level=info msg="77fdd4c82ef21fd4 became follower at term 3"
time="2016-09-12T08:24:25.780114481Z" level=info msg="raft.node: 77fdd4c82ef21fd4 elected leader 6b6752326ea027e8 at term 3"
time="2016-09-12T08:24:25.783244341Z" level=debug msg="77fdd4c82ef21fd4 [logterm: 0, index: 80] rejected msgApp [logterm: 3, index: 80] from 6b6752326ea027e8"
time="2016-09-12T08:24:25.788912206Z" level=panic msg="tocommit(73) is out of range [lastIndex(47)]. Was the raft log corrupted, truncated, or lost?"
panic: (*logrus.Entry) (0x1dad400,0xc820d3ae40)

goroutine 2060 [running]:
panic(0x1dad400, 0xc820d3ae40)
       	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/Sirupsen/logrus.Entry.log(0xc8200461c0, 0xc820368030, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc821010240, ...)
       	/go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus/entry.go:113 +0x62c
github.com/Sirupsen/logrus.(*Entry).Panic(0xc820303840, 0xc820daa3b8, 0x1, 0x1)
       	/go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus/entry.go:158 +0x99
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc820303840, 0x2155340, 0x5d, 0xc8211eec40, 0x2, 0x2)
       	/go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus/entry.go:206 +0x139
github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc8207d7ce0, 0x49)
       	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/log.go:194 +0x1a6
github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc8207f23c0, 0x8, 0x26bd72412d746d95, 0x6b6752326ea027e8, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
       	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/raft.go:771 +0x44
github.com/coreos/etcd/raft.stepFollower(0xc8207f23c0, 0x8, 0x26bd72412d746d95, 0x6b6752326ea027e8, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
       	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/raft.go:736 +0x119c
github.com/coreos/etcd/raft.(*raft).Step(0xc8207f23c0, 0x8, 0x26bd72412d746d95, 0x6b6752326ea027e8, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
       	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0
github.com/coreos/etcd/raft.(*node).run(0xc820f10910, 0xc8207f23c0)
       	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/node.go:310 +0x90e
created by github.com/coreos/etcd/raft.StartNode
       	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/etcd/raft/node.go:203 +0x73b
```

Docker version:
```
docker@swarm3:~$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Comment by cpuguy83** [comment] 2016-09-12 13:58
ping @LK4D4

**Comment by aaronlehmann** [comment] 2016-09-13 18:55
Thanks for the report. This is the first time I've seen this problem.

Can you reproduce the panic at will, or did it only happen once? If you can reproduce it, it may be helpful if I could look at the files in `/var/lib/docker/swarm`. Note that these contain sensitive information like crypto keys, so if this isn't a one-off test cluster, let's find a way to transfer it privately.

I'm also interested in knowing whether you bootstrapped this node from scratch or copied/cloned items from another machine.

**Comment by thaJeztah** [comment] 2016-09-23 16:35
ping @samber could you answer @aaronlehmann's questions?

**Comment by thaJeztah** [comment] 2016-10-29 07:01
Closing, because we didn't receive more information, but happy to reopen once we received

**Closed by thaJeztah** 2016-10-29 07:01 UTC
Labels: area/swarm, kind/bug, status/more-info-needed, version/1.12

**Comment by fmaciask** [comment] 2016-11-08 17:11
Hello,
I'm experiencing the same issue. I'm in testing environment and I can't run docker on the node.
First, this node was a worker in swarm. As I'm doing some tests, I tried to leave the swarm doing `docker swarm leave --force`. (I had to use force as it didn't let me go on).
Then, I decided to reattach the node as a manager (just for testing and to see if it could handle multiple managers). I did the command `docker swarm join --token XXXXXX ip-host:2377`.
Nothing happened and started giving error about docker daemon as in the issue. Now, I can't recover this docker node. I'm stuck and I'm start thinking in reinstall it. Any help would be appreciate.
Thanks!

**Comment by thaJeztah** [comment] 2016-11-08 17:15
@fmaciask what version and distro are you running on? (output of `docker version` and `docker info`)? What is your setup (e.g. how many managers, and workers, are they running in the cloud, on bare metal, in a virtual machine?) Also do the logs give any information?

**Comment by fmaciask** [comment] 2016-11-08 17:23
`~]# docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?`
Distro is installed in VPS.
`Operating System: CentOS Linux 7 (Core)`

> ● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─docker.conf
   Active: failed (Result: exit-code) since mar 2016-11-08 18:19:30 CET; 9s ago
     Docs: https://docs.docker.com
  Process: 2727 ExecStart=/usr/bin/dockerd -H unix:///var/run/docker.sock -H tcp://x.x.x.x:2376 -s btrfs -g /mnt/vg-docker/images --tls=true --tlscert=/.../access.crt
 --tlskey=/.../access.key (code=exited, status=2)
 Main PID: 2727 (code=exited, status=2)

>nov 08 18:19:30 hostserver dockerd[2727]: github.com/coreos/etcd/raft.(*raft).Step(0xc82000a180, 0x8, 0xdaadb46109c4343, 0x1aaaff91f1bd18e, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
nov 08 18:19:30 hostserver dockerd[2727]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0
nov 08 18:19:30 hostserver dockerd[2727]: github.com/coreos/etcd/raft.(*node).run(0xc82081f220, 0xc82000a180)
nov 08 18:19:30 hostserver dockerd[2727]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/node.go:310 +0x90e
nov 08 18:19:30 hostserver dockerd[2727]: created by github.com/coreos/etcd/raft.RestartNode
nov 08 18:19:30 hostserver dockerd[2727]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4
nov 08 18:19:30 hostserver systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
nov 08 18:19:30 hostserver systemd[1]: Failed to start Docker Application Container Engine.
nov 08 18:19:30 hostserver systemd[1]: Unit docker.service entered failed state.
nov 08 18:19:30 hostserver systemd[1]: docker.service failed.

**Comment by thaJeztah** [comment] 2016-11-08 17:35
@fmaciask the `Built:` date is empty in the output; are you running an official build?

**Comment by fmaciask** [comment] 2016-11-08 17:50
I used the one in yum docker repository writting the following url in /etc/yum.repos.d/docker.repo inside the server:

>[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg

**Comment by aaronlehmann** [comment] 2016-12-17 01:49
There has been some recent progress on understanding this panic. https://github.com/docker/swarmkit/pull/1815#issuecomment-267703760 explains three cases which are thought to cause it. That PR fixes one of the cases, and https://github.com/docker/swarmkit/pull/1820 fixes another. The third case is downgrading from 1.13 to an earlier version, and that will be supported through a reverse migration tool.
