### ISSUE TITLE
docker stats all should use container names before falling back to guids

### ISSUE THREAD

**Issue by SamSaffron** [docker/docker#22021] opened 2016-04-14 06:50 UTC
per closed 

https://github.com/docker/docker/issues/10772

and this PR by @runcom 

https://github.com/docker/docker/pull/16742

`docker stats --all` now shows all the containers. This is a very welcome change. 

However it picks container guids as opposed to preferring `--name` of the container, which gives you a dashboard full of guids that is not that useful.

```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O             PIDS
2e2e44e2c8ae        3.93%               526.6 MB / 33.68 GB   1.56%               7.237 MB / 9.208 MB   6.078 MB / 4.723 MB   0
9fe24e42d7ff        0.00%               29.56 MB / 33.68 GB   0.09%               4.245 MB / 1.445 MB   22.36 MB / 0 B        0
b1f1d7f9246e        0.33%               24.83 MB / 33.68 GB   0.07%               0 B / 0 B             30.4 MB / 0 B         0
b05ed7914b0a        0.13%               12.66 MB / 33.68 GB   0.04%               0 B / 0 B             22.25 MB / 0 B        0
546d8519a85c        0.06%               1.425 GB / 33.68 GB   4.23%               3.257 GB / 5.984 GB   956.7 MB / 16.38 kB   0
7431d8898f86        0.83%               96.49 MB / 33.68 GB   0.29%               16.92 MB / 12.14 MB   102.8 MB / 258.6 MB   0
32812f50fff9        0.09%               76.23 MB / 33.68 GB   0.23%               4.859 MB / 1.623 MB   85.12 MB / 136.7 MB   0
8d70899f930b        0.14%               1.862 GB / 33.68 GB   5.53%               13.89 MB / 4.309 MB   423.6 MB / 22.68 MB   0
ea1273b7762f        0.13%               16.03 MB / 33.68 GB   0.05%               6.093 MB / 29.01 MB   14.73 MB / 0 B        0
```

Name should be preferred, if you want to be ultra fancy you can skip auto assigned names or use image name + guid for auto assigned names. Eg:

```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O             PIDS
awesome-container   3.93%               526.6 MB / 33.68 GB   1.56%               7.237 MB / 9.208 MB   6.078 MB / 4.723 MB   0
```

Simplest is just to change it so it always uses name for `--all`

**Comment by HackToday** [comment] 2016-04-14 09:41
if I remember clearly, one docker container can have multiple names,  so if you use names here, display we not be good, and multiple names for one field seems not good than ID.

Maybe other core developer can give more comments

**Comment by SamSaffron** [comment] 2016-04-14 12:45
@HackToday  perhaps there is some way of launching containers with multiple names but I just tried really hard and was not able to using `docker run` 

I think it would be fine to either

1. Pick first name if there are multiple names
2. Use container id if there are multiple names
3. Show all names if there are multiple names

Either of the 3 options would cater fine for the 0.001% of containers people manage to somehow launch with multiple names :)

**Comment by thaJeztah** [comment] 2016-04-14 17:06
this is a duplicate of https://github.com/docker/docker/issues/20973; also see the discussion on https://github.com/docker/docker/pull/21185, which proposes to add a `--format` option for `docker stats`, so that the columns that will be shown are configurable.

I'll close this in favor of https://github.com/docker/docker/issues/20973 - please continue the discussion there

**Closed by thaJeztah** 2016-04-14 17:06 UTC

**Comment by thaJeztah** [comment] 2017-09-28 19:24
I opened a new PR for changing the default format to show `CONTAINER ID` (truncated) and `NAME` by default, and add a `--no-trunc` flag to docker stats. The PR was just merged, so will be in an upcoming Docker release (17.10 or 17.11); https://github.com/docker/cli/pull/565
