### ISSUE TITLE
Docker for Mac - Error response from daemon: Bad response from Docker engine

### ISSUE THREAD

**Issue by bizmate** [docker/docker#24366] opened 2016-07-06 10:45 UTC
Docker for mac is not working anymore in the last release. I get the error shown on this page. 

https://forums.docker.com/t/docker-mac-beta-bad-response-from-docker-engine/16399

This is a show stopper because it does not even work for me despite resetting docker. Just to be clear, going to docker whale -> selecting reset does not work

Also tried to re-install but didnt work. I was looking for older docker for mac releases but cannot find them.

**Output of `docker version`:**

```
docker -v
Docker version 1.12.0-rc2, build 906eacd, experimental
```

**Output of `docker info`:**

```
docker info
Error response from daemon: Bad response from Docker engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for mac on El Capitan 10.11.1

**Steps to reproduce the issue:**
1. run any docker command like docker ps
2. see error

**Describe the results you received:**
see docker info step above, always get the same error

**Describe the results you expected:**
if running ps i would expect to see running containers

**Additional information you deem important (e.g. issue happens only occasionally):**
could not find any issue open for this or a separate repo for docker for mac. I hope this is fine

**Comment by jengo** [comment] 2016-07-06 22:17
Exact same issue for me .. it even managed to break my non-beta version from working.

**Comment by tomekcp** [comment] 2016-07-06 22:19
I have the same issue. 

When I check the Docker in the menu bar, the message appears that "Docker starting" but nothing happens. 

Version 1.12.0-rc2-beta17 (build: 9779)
ff18c0c63c5ff3c4a4a925d191d5592d655779d7

![vollbild_07_07_16__00_17](https://cloud.githubusercontent.com/assets/2247288/16636440/703e42d8-43d8-11e6-8365-59c8f9f91b8b.png)

**Comment by jengo** [comment] 2016-07-06 22:30
Doing the factory reset appears to have fixed it.

**Comment by tomekcp** [comment] 2016-07-06 22:37
yeah this solution I found in the docker forum and it works. Nevertheless thx for your help @jengo.

**Comment by smugcloud** [comment] 2016-07-07 19:53
I also started running into this issue today as well.  All Docker commands produce `Error response from daemon: Bad response from Docker engine`

Here are the details I can grab:
```
$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true
Error response from daemon: Bad response from Docker engine
```
OSX El Capitan 10.11.5 (15F34)

Docker for Mac Version: Version 1.12.0-rc2-beta17 (build: 9779)
ff18c0c63c5ff3c4a4a925d191d5592d655779d7

**Comment by tomekcp** [comment] 2016-07-07 20:02
smugcloud@ do you have installed both? docker toolbox and the docker for mac?

**Comment by smugcloud** [comment] 2016-07-07 20:21
@tomekcp It looks like there was some Toolbox elements laying around.  I removed all of the docker executables in /usr/local/bin, uninstalled/reinstalled Docker for Mac, and now those same Docker commands just hang.  That is very odd as all of those components were previously installed together and things worked fine.

**Comment by smugcloud** [comment] 2016-07-07 20:26
@tomekcp 
Hmm, something funky was going on...resetting Docker for Mac again seems to have done the trick.  Is there some debugging output I can capture for this in the future?

**Comment by tomekcp** [comment] 2016-07-07 20:34
I think both together make the trouble but im not sure. the docker for mac use different virtualization and not the virtualbox but the toolbox installed the virtualbox.

**Comment by xgt001** [comment] 2016-07-19 09:10
had this same issue. Doing a reset resolved this for me.

**Comment by samoht** [comment] 2016-07-27 14:49
This was an unfortunate hiccup due to non backward-compatible changes in the runtime format between 2 RC releases. The issue is now fixed so I think we should close that ticket.

**Comment by bizmate** [comment] 2016-07-27 15:30
hi @samoht thanks for the info, do you know the releases that had problems? I remember i did update my docker on mac last night. I can test and make sure i dont get the issue anymore and then close the ticket

**Comment by samoht** [comment] 2016-07-27 18:30
It was the upgrade between Beta17 and Beta18 which causes some problems. If you had containers created during Beta17 you will have to either delete them or run the ugrade script provided in https://github.com/docker/docker/issues/24343#issuecomment-230887236

**Comment by thaJeztah** [comment] 2016-07-27 19:15
There's also information in the troubleshooting section of the documentation; https://docs.docker.com/docker-for-mac/troubleshoot/#/recreate-or-update-your-containers-after-beta-18-upgrade

I'll close this issue, but feel free to continue the discussion

**Closed by thaJeztah** 2016-07-27 19:15 UTC
Labels: group/pinata

**Comment by zaojiao** [comment] 2016-08-10 07:31
Yes, Perferences...  then  select  "Reset to factory defaults".  
can solve the problem.

**Comment by ryangurn** [comment] 2016-08-26 17:26
Im having the same problem and when i go to reset to factory defaults the client freezes and dies. Please advise what to do.
![image](https://cloud.githubusercontent.com/assets/1297082/18014378/8b04f9a6-6b77-11e6-92d3-3977ebdb4edb.png)

**Comment by justincormack** [comment] 2016-08-26 17:30
You could uninstall and then reinstall. You  will get better support for
Mac specific issues in https://github.com/docker/for-mac

**Comment by clok** [comment] 2016-09-13 22:55
I have installed the most recent version of docker for mac and I am seeing this error. Is there a technical solution or do we need to reinstall?

**Comment by fanyer** [comment] 2016-09-19 06:09
docker preference rest solve this problem,thx

**Comment by elesueur** [comment] 2016-09-23 18:06
I just started getting this now, docker is up to date

% docker version                                                                                                                                                           14:04:48
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64
Error response from daemon: Bad response from Docker engine

every other command fails. Restarting does not resolve the issue. Have to completely reset.

**Comment by dcosson** [comment] 2016-10-05 05:31
I just got this as well, same versions and same output as @elesueur 

First I got the error sporadically a few times, once during docker build and once during an npm install in a container.  Maybe the VM ran out of memory and restarted or something? I got kicked out of the shell with Bad Response for Docker engine. 

Then I came back later and `docker ps` hung when I ran it, so I restarted docker from the taskbar gui. It seemed like it restarted fine, but now every command I run immediately fails with the `Bad response from Docker engine` error. Restarting docker again still appears to work from the gui, but i continue getting this error.

**Comment by justincormack** [comment] 2016-10-05 11:40
This issue is closed. Please open an issue at
https://github.com/docker/for-mac/issues for support.

**Comment by daveisfera** [comment] 2016-10-05 14:22
This appears to be the same or at least a similar issue in that repo:
https://github.com/docker/for-mac/issues/725

**Comment by majuansari** [comment] 2016-10-11 17:38
Getting the same issue any updates on this ?

**Comment by thaJeztah** [comment] 2016-10-11 17:41
As @justincormack above; this issue is closed, if you're still having this issue, or similar, please check the Docker for Mac issue tracker as this is specific to Docker for Mac https://github.com/docker/for-mac/issues

I'm locking this issue
