### ISSUE TITLE
Is possible run pppoe within docker?

### ISSUE THREAD

**Issue by bluebad** [docker/docker#23114] opened 2016-05-31 04:22 UTC
A CentOS as host run in WMWare, docker run in this host. I setup a bridge in host, then launch a container named test1. test1 can ping host.
Host can pppoe dialup, but test1 can not. --cap-add=NET_ADMIN added when run.
Someone can help me?

**Comment by phemmer** [comment] 2016-05-31 05:43
I would try the docker forums, IRC, or mailing list. The issue tracker is generally for bugs and feature requests. Meaning you'll likely have better luck over there.

**Comment by justincormack** [comment] 2016-05-31 09:36
You should `strace` the process and see where it fails. Not sure what pppoe needs, maybe access to the /dev/ppp` device?

**Comment by bluebad** [comment] 2016-05-31 09:49
pppd last ouput is: 5 terminated, seem to be timeout. pppoe just ppp proto on ethernet, container have mac and bridge to host, but still failed! So I think docker lacks support pppoe.

**Comment by justincormack** [comment] 2016-05-31 10:05
It may be `iptables` related at a guess. You could also try with `--net=host`, which would avoid some of the potential issues and make it easier to debug. Docker just uses Linux networking, so it should work.

**Comment by bluebad** [comment] 2016-05-31 10:25
Maybe not iptables. Because wireshark capure nothing. Thanks for helps.

**Comment by thaJeztah** [comment] 2016-05-31 12:03
@bluebad I'll close this issue, because it's a question, not a bug, but feel free to continue the discussion here

**Closed by thaJeztah** 2016-05-31 12:03 UTC

**Comment by bluebad** [comment] 2016-05-31 12:20
strace output:
socket(PF_NETLINK, SOCK_RAW, 9)         = 3
sendmsg(3, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(2)=[{" \0\0\0d\4\1\0\0\0\0\0\0\0\0\0", 16}, {"/sbin/ifup ppp0\0", 16}], msg_controllen=0, msg_flags=0}, 0) = -1 ECONNREFUSED (**Connection refused**)
Something went wrong?

**Comment by justincormack** [comment] 2016-05-31 12:50
I think that is trying to send a `udev` event to the kernel to bring the `ppp0` interface up. Even if you did not get a connection refused error, it would not bring the interface up in the container so it is not going to work.
