### ISSUE TITLE
Running one container from each image with one command

### ISSUE THREAD

**Issue by abdulrahim9** [docker/docker#26977] opened 2016-09-28 09:26 UTC
Hello,

I would like to run multiple images, each in a container. These images can depend on one another. Let's say that I already know how to link them. I still need to write multiple commands in my command line to run each container. What I want to do is to run all containers with one command. It is possible to write the commands in a file and use one command to execute that file. Yet is this the proper approach or not?

Thanks

**Comment by thaJeztah** [comment] 2016-09-28 12:32
Sure, you could use a shell script to run multiple commands, e.g.

```bash
docker run --name a foobar:latest && docker run --name b baz:latest
```

However, Docker Compose may be a better solution, as it is designed for that;
https://docs.docker.com/compose/overview/

I'll close this issue, because this is not a bug, and the GitHub issue tracker is not intended as a general support forum; https://forums.docker.com, the #docker IRC channel or StackOverflow may be better locations for that.

**Closed by thaJeztah** 2016-09-28 12:32 UTC
Labels: kind/question
