### ISSUE TITLE
On docker 1.13.1 Error response from daemon: rpc error: code = 3 desc = legacy plugin calico of type NetworkDriver is not supported in swarm mode

### ISSUE THREAD

**Issue by jonathan-kosgei** [docker/docker#31360] opened 2017-02-25 11:25 UTC
**Description**

Can't create a network using the calico plugin in swarm mode docker 1.13.1

**Steps to reproduce the issue:**
1. Setup calico on node
```
curl https://gist.githubusercontent.com/jonathan-kosgei/d9efafaa7fefae60bd94d0d56cb52ead/raw/74ccebe4ab88cff96baaa115c79c574e678bf8ea/installing_calico_for_docker_networking.sh | sh
```
2. 
```
docker swarm init
```
3.
```
docker network create --driver calico --ipam-driver calico-ipam --subnet=10.0.0.0/8 sc-network
```

**Describe the results you received:**
```
root@sc-swarm:~# docker network create --driver calico --ipam-driver calico-ipam --subnet=10.0.0.0/8 sc-network
Error response from daemon: rpc error: code = 3 desc = legacy plugin calico of type NetworkDriver is not supported in swarm mode
```

**Describe the results you expected:**
```
To be able to create a network with the calico plugin
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 9
 Running: 2
 Paused: 0
 Stopped: 7
Images: 8
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: kuqmagths0brhf1nqdwnqesdo
 Is Manager: true
 ClusterID: w4wxgnargspwwymgczug3eisr
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 100.108.150.45
 Manager Addresses:
  100.108.150.45:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.359 GiB
Name: sc-swarm
ID: A7XA:WSYE:PISZ:WADP:ZAOP:4L3A:7NXU:R65W:V4L5:SVBD:FGXS:KL7H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: jkosgei
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Azure

**Comment by mavenugo** [comment] 2017-02-25 19:54
This is a dupe of https://github.com/docker/docker/issues/24569. closing.

**Closed by mavenugo** 2017-02-25 19:54 UTC
Labels: area/networking, area/swarm, version/1.13

**Comment by mavenugo** [comment] 2017-02-25 19:57
Please open an issue in https://github.com/projectcalico/calico to support managed plugins.
