### ISSUE TITLE
docker top not working on openSUSE 13.1

### ISSUE THREAD

**Issue by srkunze** [docker/docker#7971] opened 2014-09-10 13:03 UTC
Using docker 1.2 on openSUSE 13.1 adhering to https://docs.docker.com/installation/openSUSE/ and https://news.opensuse.org/2014/08/07/official-docker-containers/ , we got this error:

```
>>> docker top nostalgic_bardeen
2014/09/10 14:57:35 Error response from daemon: open /sys/fs/cgroup/cpu,cpuacct/system.slice/system.slice/docker-e08ca95b184e820b52aafe60002c97deed85e13c91eec5dbc9d954e81ffc8da0.scope/cgroup.procs: no such file or directory
```

```
>>> docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
e08ca95b184e        opensuse:13.1       "/bin/sh -c 'while t   2 hours ago         Up About an hour                        nostalgic_bardeen   
```

**Comment by jfrazelle** [comment] 2015-02-26 01:04
closing as duplicate of https://github.com/docker/docker/issues/7205

**Closed by jfrazelle** 2015-02-26 01:04 UTC
