### ISSUE TITLE
Volumes broken in recent version

### ISSUE THREAD

**Issue by rlpowell** [docker/docker#10405] opened 2015-01-28 02:59 UTC
This issue is causing SERIOUS PRODUCTION PROBLEMS in those systems that have upgraded their docker versions.

We have a /scratch volume that gets mounted on our docker instances; all of a sudden, it's not getting mounted!  This failure is completely silent as far as I can tell!

Before:  https://gist.github.com/rlpowell/12a69e64c83ca933e09f

After:  https://gist.github.com/rlpowell/7d4f655de774655d0206

I'm still narrowing down exactly what version this happened in.  I have no idea how to work around it.

**Comment by rlpowell** [comment] 2015-01-28 03:12
Upgrading the system to 1.4.1 and restarting docker does *not* cause this bug to occur; I don't know what that means yet.

**Comment by rlpowell** [comment] 2015-01-28 03:16
Upgrading *plus rebooting* does, however, cause the bug to appear.

**Comment by rlpowell** [comment] 2015-01-28 03:21
And "sudo service docker restart" appears to make it go away.  The question is, if I do nothing but reboot and then restart, will that fix it?  Testing that now.

**Comment by LK4D4** [comment] 2015-01-28 04:27
ping @cpuguy83 
@rlpowell There is indeed was issues with upgrading volumes :/

**Comment by rlpowell** [comment] 2015-01-28 04:43
It's not just a live upgrade issue; once upgraded this happens on *every* reboot.  An early restart of docker (in my startup scripts) doesn't fix it, but a late restart seems to?

**Comment by rlpowell** [comment] 2015-01-28 05:28
AH-HA!

Everything works fine if I restart docker *AFTER* /scratch is mounted (it's mounted by a script after startup).

So.  Now that I have a workaround, how can I help you debug?

**Comment by phemmer** [comment] 2015-01-28 13:00
If you're saying that you have docker containers using `/scratch` from the host as a volume mount, and that they're starting before `/scratch` is mounted, then I don't see this as a docker issue. You would need to adjust your system's init scripts so that docker, or the containers that need `/scratch`, are started after the mount.

I'm guessing this just started breaking because docker & your containers are starting faster than before the upgrade.

**Comment by cpuguy83** [comment] 2015-01-28 13:17
For sure, 1.4.x has an issue with properly registering bind mounts for data-only containers (read: containers that don't get started) after a daemon restart.

If you are mounting something to /scratch on the host and then wanting to use that in Docker, you need to make sure /scratch is mounted first.

**Comment by rlpowell** [comment] 2015-01-28 18:50
No, of course the containers aren't trying to use the mount before it's mounted; I would have noticed that immediately.

What happens is docker runs on startup, as per normal.  Then a late startup script runs that mounts /scratch and then does the docker run -v /scratch:/scratch:rw.  The mount *is* up when the docker run is called.

The new behaviour is that this fails unless the *entire docker server* is restarted after /scratch is mounted.

More importantly, it fails *with no errors of any kind*.  That is, at the very least, a significant POLS violation.

**Comment by rlpowell** [comment] 2015-01-28 18:50
And no, the order is exactly the same on startup in both cases.

**Comment by cpuguy83** [comment] 2015-01-28 19:02
Ok, looking at the gists again, this looks like something with mounts in particular since "-v /scratch:/scrach" is just bind-mounting the host's /scratch into the container.

Also, most definitely is not the issue @LK4D4 is speaking of, since that would be specifically for a pre 1.3.x daemon upgrading to a post 1.3.x daemon, for bind-mounts in containers that have not been started yet (in the new daemon).

@rlpowell Can you paste your `docker info` output as well as your `docker version` output?  *Note that `docker --version` is not that same thing.

**Comment by crosbymichael** [comment] 2015-01-29 00:10
I'm looking into this.  @rlpowell can you post the mount options that you are using on the `/scratch` mount?  I think this has something to do with mount propagation and just want to make sure I can reproduce.  

Also, sorry if you already said this or not, what distro are you on?  Are you able to run `mount` on your host and post the output?

**Comment by rlpowell** [comment] 2015-01-29 01:30
Sorry for the delay.

All systems in question were Fedora 20 on AWS.

    rlpowell@ip-10-128-11-129> mount | grep -i xvdb
    /dev/xvdb on /mnt type ext3 (rw,relatime,seclabel,data=ordered)
    /dev/xvdb on /scratch type ext3 (rw,relatime,seclabel,data=ordered)
    rlpowell@ip-10-128-11-129>

The actual mount call in the script is:

    mkdir /scratch
    mount /dev/xvdb /scratch
    chown 4801:4801 /scratch

Other requested info:
    
    rlpowell@ip-10-128-11-129> sudo docker info
    Containers: 3
    Images: 13
    Storage Driver: devicemapper
     Pool Name: docker-202:1-751810-pool
     Pool Blocksize: 65.54 kB
     Data file: /var/lib/docker/devicemapper/devicemapper/data
     Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
     Data Space Used: 5.937 GB
     Data Space Total: 107.4 GB
     Metadata Space Used: 5.239 MB
     Metadata Space Total: 2.147 GB
     Library Version: 1.02.85 (2014-04-10)
    Execution Driver: native-0.2
    Kernel Version: 3.15.8-200.fc20.x86_64
    Operating System: Fedora 20 (Heisenbug)
    CPUs: 4
    Total Memory: 7.337 GiB
    Name: ip-10-128-11-129.us-west-1.compute.internal
    ID: PACO:GDX4:WT3Z:O43H:3ZNK:47WZ:45V7:MG3C:XO2Y:K5VW:TPKL:EXFK
    rlpowell@ip-10-128-11-129> sudo docker version
    Client version: 1.4.1
    Client API version: 1.16
    Go version (client): go1.3.3
    Git commit (client): 5bc2ff8/1.4.1
    OS/Arch (client): linux/amd64
    Server version: 1.4.1
    Server API version: 1.16
    Go version (server): go1.3.3
    Git commit (server): 5bc2ff8/1.4.1
    rlpowell@ip-10-128-11-129>

**Comment by crosbymichael** [comment] 2015-01-29 01:36
thanks, let me see if can can reproduce on a fedora machine.  I know they mount / as PRIVATE so I hope I'm on the right track

**Comment by wallrj** [comment] 2015-01-29 14:08
This may be related to https://github.com/docker/docker/issues/10419#issuecomment-71921086 and https://bugzilla.redhat.com/show_bug.cgi?id=1185423

Try upgrading to https://kojipkgs.fedoraproject.org//work/tasks/7645/8757645/docker-io-1.4.1-8.fc20.x86_64.rpm 

And note the change in http://pkgs.fedoraproject.org/cgit/docker-io.git/commit/?h=f21&id=99a6953366a8b74bcd33f04f8f4ce47b9c312e85

**Comment by wallrj** [comment] 2015-01-29 14:09
There's a good description of the problem here: http://blog.oddbit.com/2015/01/18/docker-vs-privatetmp/

**Comment by crosbymichael** [comment] 2015-01-29 18:45
thanks for the links @wallrj

**Comment by rlpowell** [comment] 2015-01-31 03:14
Hey, that seems to do it!  Thank you!

That explanation seems *amazingly* complicated.  Wow.

**Comment by crosbymichael** [comment] 2015-02-02 21:16
@rlpowell thanks for following up.  I'll close this one now as it's bug in packaging that we don't control.

**Closed by crosbymichael** 2015-02-02 21:16 UTC

**Comment by wallrj** [comment] 2015-02-03 11:44
FYI The new package has now made into Fedora 20 testing. 
 * https://admin.fedoraproject.org/updates/FEDORA-2015-1458/docker-io-1.4.1-8.fc20
