### ISSUE TITLE
Docker service in swarm 404 after reboot 

### ISSUE THREAD

**Issue by Pierpaolo1992** [docker/docker#30499] opened 2017-01-27 09:37 UTC
I've 3 VM created by docker-machine, for simulating a cluster with docker swarm. I have service on this cluster, and all worked well.
I've reboot my pc (and so my vm); then after my reboot, my service returns me 404 error for all request i do.

Can anyone helps me?

**Comment by thaJeztah** [comment] 2017-01-27 09:39
Hi @Pierpaolo1992, please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-01-27 09:39 UTC
Labels: area/swarm
