### ISSUE TITLE
cannot pull on zfs 

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#16313] opened 2015-09-15 18:51 UTC
Steps to reproduce:
```
truncate -s 70G /tmp/zfs.img
rm -rf /var/lib/docker
mkdir -p /var/lib/docker
zpool create zroot /tmp/zfs.img
zfs create -o com.sun:auto-snapshot=false -o dedup=off -o mountpoint=/var/lib/docker zroot/docker

# start docker
docker pull jess/consul

Using default tag: latest
latest: Pulling from jess/consul
31f630c65071: Extracting [>                                                  ] 32.77 kB/2.475 MB
31f630c65071: Error downloading dependent layers 
5cdea7f19a8e: Download complete 
62a42f4bf507: Download complete 
01af1efdec3d: Downloading [================================>                  ] 4.195 MB/6.384 MB
9cb78facf026: Download complete 
9cb78facf026: Error pulling image (latest) from docker.io/jess/consul, error creating zfs mount of zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8 to /var/lib/docker/zfsError pulling image (latest) from docker.io/jess/consul, error creating zfs mount of zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8 to /var/lib/docker/zfs/graph/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8: invalid argument
```

Daemon logs:
```
Sep 15 14:44:02 jenkins-zfs docker[1130]: time="2015-09-15T14:44:02.902358497-04:00" level=error msg="HTTP Error" err="No such image: jess/consul:latest" statusCode=404
Sep 15 14:44:02 jenkins-zfs docker[1130]: time="2015-09-15T14:44:02.903063105-04:00" level=debug msg="Calling POST /images/create"
Sep 15 14:44:02 jenkins-zfs docker[1130]: time="2015-09-15T14:44:02.903103703-04:00" level=info msg="POST /v1.21/images/create?fromImage=jess%2Fconsul&tag=latest"
Sep 15 14:44:02 jenkins-zfs docker[1130]: time="2015-09-15T14:44:02.903484148-04:00" level=debug msg="Trying to pull jess/consul from https://registry-1.docker.io v2"
Sep 15 14:44:03 jenkins-zfs docker[1130]: time="2015-09-15T14:44:02.999583316-04:00" level=debug msg="Pulling tag from V2 registry: \"latest\""
Sep 15 14:44:03 jenkins-zfs docker[1130]: time="2015-09-15T14:44:03.441157944-04:00" level=debug msg="Key check result: no graph"
Sep 15 14:44:03 jenkins-zfs docker[1130]: time="2015-09-15T14:44:03.443008987-04:00" level=debug msg="pulling blob \"sha256:c862d82a67a239544df3e99f3883decc2aa840d480daa269d33e35b2364eed58\" to 31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8"
Sep 15 14:44:03 jenkins-zfs docker[1130]: time="2015-09-15T14:44:03.443231178-04:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to 505093f91bbc9a181709c3b92a97f9387ca3d091409a308e3a8a8e3939ba6ace"
Sep 15 14:44:03 jenkins-zfs docker[1130]: time="2015-09-15T14:44:03.443375633-04:00" level=debug msg="pulling blob \"sha256:ef633be14a653a0add8262fd4190726567f1fd9e3954808a317359e2af89a1d4\" to 5cdea7f19a8e2cf207eb19893a48d37d837d43e419723fc2185750f2a539dc80"
Sep 15 14:44:03 jenkins-zfs docker[1130]: time="2015-09-15T14:44:03.443517184-04:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to 62a42f4bf5078867501bc941490bb19bd775329957019041474c1ef60f3794ca"
Sep 15 14:44:03 jenkins-zfs docker[1130]: time="2015-09-15T14:44:03.443637977-04:00" level=debug msg="pulling blob \"sha256:f45201b9cf70cecb4f818973990d583d15668cd8c1c8d1e3e7b4e7de027cb712\" to 01af1efdec3d8801df58b530f3c3b6e3de873f6b9e75f9c85a60d1b4f5268516"
Sep 15 14:44:03 jenkins-zfs docker[1130]: time="2015-09-15T14:44:03.443815343-04:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to 9cb78facf0261d4fdca10396bacfee826b33f663e1aa96b900a80986ea90e57a"
Sep 15 14:44:03 jenkins-zfs docker[1130]: time="2015-09-15T14:44:03.862574865-04:00" level=debug msg="Downloaded 9cb78facf0261d4fdca10396bacfee826b33f663e1aa96b900a80986ea90e57a to tempfile /var/lib/docker/tmp/GetImageBlob241151763"
Sep 15 14:44:03 jenkins-zfs docker[1130]: time="2015-09-15T14:44:03.863009206-04:00" level=debug msg="Downloaded 62a42f4bf5078867501bc941490bb19bd775329957019041474c1ef60f3794ca to tempfile /var/lib/docker/tmp/GetImageBlob272799353"
Sep 15 14:44:03 jenkins-zfs docker[1130]: time="2015-09-15T14:44:03.903993884-04:00" level=debug msg="Downloaded 505093f91bbc9a181709c3b92a97f9387ca3d091409a308e3a8a8e3939ba6ace to tempfile /var/lib/docker/tmp/GetImageBlob460595311"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.036021123-04:00" level=debug msg="Downloaded 5cdea7f19a8e2cf207eb19893a48d37d837d43e419723fc2185750f2a539dc80 to tempfile /var/lib/docker/tmp/GetImageBlob955775234"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.059692568-04:00" level=debug msg="Downloaded 31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8 to tempfile /var/lib/docker/tmp/GetImageBlob536430416"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.060022485-04:00" level=debug msg="[zfs] zfs destroy -r zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.063769005-04:00" level=debug msg="[zfs] zfs create -o mountpoint=legacy zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.139232347-04:00" level=debug msg="[zfs] zfs get -Hp all zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.160323295-04:00" level=debug msg="[zfs] mount(\"zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8\", \"/var/lib/docker/zfs/graph/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8\", \"\")"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.163673908-04:00" level=debug msg="[zfs] zfs destroy -r zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.208411722-04:00" level=debug msg="Error trying v2 registry: error creating zfs mount of zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8 to /var/lib/docker/zfs/graph/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8: invalid argument"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.208555032-04:00" level=debug msg="Trying to pull jess/consul from https://index.docker.io v1"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.208600317-04:00" level=debug msg="hostDir: /etc/docker/certs.d/docker.io"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.208956162-04:00" level=debug msg="[registry] Calling GET https://index.docker.io/v1/repositories/jess/consul/images"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.209909440-04:00" level=error msg="filesystem layer verification failed for digest sha256:f45201b9cf70cecb4f818973990d583d15668cd8c1c8d1e3e7b4e7de027cb712"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.356649446-04:00" level=debug msg="Retrieving the tag list"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.528290421-04:00" level=debug msg="Got status code 200 from https://registry-1.docker.io/v1/repositories/jess/consul/tags/latest"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.528520198-04:00" level=debug msg="Registering tags"
Sep 15 14:44:04 jenkins-zfs docker[1130]: time="2015-09-15T14:44:04.633704093-04:00" level=debug msg="Ancestry: [9cb78facf0261d4fdca10396bacfee826b33f663e1aa96b900a80986ea90e57a 01af1efdec3d8801df58b530f3c3b6e3de873f6b9e75f9c85a60d1b4f5268516 62a42f4bf5078867501bc941490bb19bd775329957019041474c1ef60f3794ca 5cdea7f19a8e2cf207eb19893a48d37d837d43e419723fc2185750f2a539dc80 505093f91bbc9a181709c3b92a97f9387ca3d091409a308e3a8a8e3939ba6ace 31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8]"
Sep 15 14:44:05 jenkins-zfs docker[1130]: time="2015-09-15T14:44:05.030656556-04:00" level=debug msg="server doesn't support resume"
Sep 15 14:44:05 jenkins-zfs docker[1130]: time="2015-09-15T14:44:05.030823809-04:00" level=debug msg="[zfs] zfs destroy -r zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8"
Sep 15 14:44:05 jenkins-zfs docker[1130]: time="2015-09-15T14:44:05.034633682-04:00" level=debug msg="[zfs] zfs create -o mountpoint=legacy zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8"
Sep 15 14:44:05 jenkins-zfs docker[1130]: time="2015-09-15T14:44:05.068412715-04:00" level=debug msg="[zfs] zfs get -Hp all zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8"
Sep 15 14:44:05 jenkins-zfs docker[1130]: time="2015-09-15T14:44:05.077335476-04:00" level=debug msg="[zfs] mount(\"zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8\", \"/var/lib/docker/zfs/graph/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8\", \"\")"
Sep 15 14:44:05 jenkins-zfs docker[1130]: time="2015-09-15T14:44:05.079174071-04:00" level=debug msg="[zfs] zfs destroy -r zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8"
Sep 15 14:44:05 jenkins-zfs docker[1130]: time="2015-09-15T14:44:05.104432682-04:00" level=debug msg="Not continuing with error: Error pulling image (latest) from docker.io/jess/consul, error creating zfs mount of zroot/docker/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8 to /var/lib/docker/zfs/graph/31f630c65071968699d327be41add2e301d06568a4914e1aa67c98e1db34a9d8: invalid argument"
```

```
uname -a
Linux jenkins-zfs 3.19.0-22-generic #22-Ubuntu SMP Tue Jun 16 17:15:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker info

Containers: 0
Images: 0
Storage Driver: zfs
 Zpool: zroot
 Zpool Health: ONLINE
 Parent Dataset: zroot/docker
 Space Used By Parent: 19456
 Space Available: 72292926464
 Parent Quota: no
 Compression: off
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-22-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 7.797 GiB
Name: jenkins-zfs
ID: INUN:LE22:RYGP:5VUW:2KHN:TRJW:NKHH:SKJH:LXNA:ZKJ5:45E3:KGBQ
Debug mode (server): true
File Descriptors: 14
Goroutines: 29
System Time: 2015-09-15T14:51:28.381969663-04:00
EventsListeners: 0
Init SHA1: 
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker

docker version

Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   59311fa
 Built:        Tue Sep 15 14:56:07 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   59311fa
 Built:        Tue Sep 15 14:56:07 UTC 2015
 OS/Arch:      linux/amd64

```

**Comment by jfrazelle** [comment] 2015-09-15 18:52
ping @Mic92 

also using zfs version 5

**Comment by jfrazelle** [comment] 2015-09-15 19:00
and if I use docker <=1.8.2 I get this everytime:

```

**Comment by jfrazelle** [comment] 2015-09-15 19:01
although I think this has something to do with the fact I updated the zfs ko

**Comment by aaronlehmann** [comment] 2015-09-15 19:02
This looks similar to #16300

**Comment by jfrazelle** [comment] 2015-09-15 19:04
hmm thats devmapper tho

aldo i get this on 1.7.7, which used to work before updatinng the zfs version:
```

**Comment by Mic92** [comment] 2015-09-15 19:23
duplicate of #16258 ?

**Comment by jfrazelle** [comment] 2015-09-15 19:34
Ah nice!

**Closed** 2015-09-15 19:48 UTC
Labels: area/storage/zfs, group/distribution, kind/bug
