### ISSUE TITLE
[Proposal] Log driver to elasticsearch

### ISSUE THREAD

**Issue by ael-g** [docker/docker#30529] opened 2017-01-28 13:56 UTC
Hi guys,

Now that we have ingest pipeline shipped with elasticsearch, wouldn't it be great to have a docker log driver directly pushing to Elasticsearch ?

**Comment by thaJeztah** [comment] 2017-01-28 14:53
this is a duplicate of https://github.com/docker/docker/issues/25694, also see https://github.com/docker/docker/pull/28403, which is relevant

I'll close this one, as it's a duplicate; please subscribe to the linked issues to keep informed on updates

**Closed by thaJeztah** 2017-01-28 14:53 UTC
Labels: area/logging, kind/enhancement

**Comment by rchicoli** [comment] 2018-01-02 20:33
@ael-g https://github.com/moby/moby/issues/25694
here is the first Alpha Release of [docker-log-elasticsearch](https://github.com/rchicoli/docker-log-elasticsearch/tree/alpha-0.5.x)

To install, run:
```
docker plugin install rchicoli/docker-log-elasticsearch:0.5.5 --alias elasticsearch
```
To test, use:
```
docker run --rm  -ti \
    --log-driver elasticsearch \
    --log-opt elasticsearch-address=http://127.0.0.1:9200 \
    --log-opt elasticsearch-index=docker \
    --log-opt elasticsearch-type=log \
        alpine echo this is a test logging message
```
Query Elasticsearch:
```
$ curl 127.0.0.1:9200/docker/_search\?pretty=true
```
Nothing forget to mention that MR are welcome. I am not so sure how long it will take to finish it and tag as stable, though I will be doing besides my actual work.

**Comment by ripcurld0** [comment] 2018-01-03 09:09
@rchicoli do you mind adding this to https://store.docker.com/search?type=plugin ?
Thanks so much for your contribution.

**Comment by rchicoli** [comment] 2018-01-05 15:11
@ripcurld0 I would like to, but somehow it does not work with my account, not even with a new organization. I sent an email to docker team, hopefully someone could guide. Thanks for info.
