### ISSUE TITLE
Vendor directory affects client library usability

### ISSUE THREAD

**Issue by piotrkowalczuk** [docker/docker#32375] opened 2017-04-05 09:35 UTC
Hi, small feature request. Keeping vendor directory makes client library quite hard to use. For example `nat.PortMap` creates compile time error.

Best

**Comment by thaJeztah** [comment] 2017-04-05 09:55
can you give some more information what exactly you're doing, and what error you get?

**Comment by piotrkowalczuk** [comment] 2017-04-05 10:10
In details I'm using `github.com/docker/docker/client` library in my project. 

Im trying to create a container and forward ports. Sadly if i do not remove `./vendor/github.com/docker/docker/vendor` from my project `./vendor` directory it cant compile. It's because `./vendor/github.com/docker/docker/client` imports `nat.Port` from `./vendor/github.com/docker/docker/vendor/github.com/go-connections/nat` while my app has it's own version in `./vendor/github.com/docker/go-connections/nat`. Since Go checks type quality based on path `nat.Port` is recognized as a different type.

Sadly im not able to provide logs atm.

**Comment by thaJeztah** [comment] 2017-04-05 11:23
What tool are you using for vendoring? The problem is that that tool appears to use "nested" vendor directories, which is what's causing the problem

**Comment by piotrkowalczuk** [comment] 2017-04-05 13:37
glide, but i doubt it has anything to do with it. This is simply how Go works.

**Comment by cpuguy83** [comment] 2017-04-05 13:47
You need to use the `-v` flag with glide so it removes nested vendors, and then vendor those packages into your project.

Closing as this is pretty much expected and is a bug in go that doesn't seem like it will ever be fixed. The solution is to make sure the vendoring tool can strip nested vendors.

**Closed by cpuguy83** 2017-04-05 13:47 UTC
Labels: area/project, kind/question

**Comment by punya-asapp** [comment] 2017-10-24 01:39
Note that this is also a problem when consuming the library with `go get`.
