### ISSUE TITLE
[Suggestion]  An advanced  and more realistic embedded DNS Service

### ISSUE THREAD

**Issue by BediarSofiane** [docker/docker#23370] opened 2016-06-08 10:50 UTC
Hi,
I'm a docker containers user (not a contributor)
I am wondering if it is possible to have an embedded DNS service not only for a single network but also between all the networks that are linked (a network service), so that all the nodes that are in the network service know each other.
for example: if we have three containers C1, C2 and C3. suppose C1 is linked to C2 withe the network net1 and C2 is linked to C3 with network net2. At the moment, C1 knows the name of C2 but not the name of C3. So only nodes that are in the single network can know each other. It will be interesting if C1 could know the name of C3 (as a real DNS server). In a more general and formal way, if we have a network service like this: C1--C2--C3--C4--C5--.....--Cn, so Ci knows the name of  Cj for each i,j.

I hope the proposition was clear.
Thank you.

**Comment by thaJeztah** [comment] 2016-06-08 11:05
This is by design, because `C1` and `C3` are not in the same network, only containers that are in the same network are allowed to communicate. This allows you to (for example) use `c2` to handle communication between `c1` and `c3` (it may be a proxy or something). See the following examples;

Create two networks;

- c1 is connected to net1
- c3 is connected to net2
- c2 is connected to both

```
docker network create net1
docker network create net2

docker run -d --net net1 --name c1 nginx:alpine
docker run -d --net net1 --name c2 nginx:alpine
docker run -d --net net2 --name c3 nginx:alpine

docker network connect net2 c2
```

```
# ping c1 -> c2 works because they're in the same network
docker exec -it c1 ping -c3 c2
PING c2 (172.24.0.3): 56 data bytes
64 bytes from 172.24.0.3: seq=0 ttl=64 time=0.076 ms
64 bytes from 172.24.0.3: seq=1 ttl=64 time=0.082 ms
64 bytes from 172.24.0.3: seq=2 ttl=64 time=0.077 ms

--- c2 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.076/0.078/0.082 ms


# but c3 isn't
docker exec -it c1 ping -c3 c3
ping: bad address 'c3'


# ping c2 <--> c3 works, because they're both in the same network
docker exec -it c2 ping -c3 c3
PING c3 (172.25.0.2): 56 data bytes
64 bytes from 172.25.0.2: seq=0 ttl=64 time=0.067 ms
64 bytes from 172.25.0.2: seq=1 ttl=64 time=0.090 ms
64 bytes from 172.25.0.2: seq=2 ttl=64 time=0.078 ms

--- c3 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.067/0.078/0.090 ms


docker exec -it c3 ping -c3 c2
PING c2 (172.25.0.3): 56 data bytes
64 bytes from 172.25.0.3: seq=0 ttl=64 time=0.081 ms
64 bytes from 172.25.0.3: seq=1 ttl=64 time=0.079 ms
64 bytes from 172.25.0.3: seq=2 ttl=64 time=0.077 ms

--- c2 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.077/0.079/0.081 ms

# ping c3 to c1 doesn't work as well, because theyre not in the same network
docker exec -it c3 ping -c3 c1
ping: bad address 'c1'

```

To allow c1 to connect to c3, they need to be in the same network;

```
# either connect c1 to "net2"
docker network connect net2 c1

# or connect c3 to "net1"
docker network connect net1 c3

# then it works
docker exec -it c1 ping -c3 c3

PING c3 (172.25.0.2): 56 data bytes
64 bytes from 172.25.0.2: seq=0 ttl=64 time=0.078 ms
64 bytes from 172.25.0.2: seq=1 ttl=64 time=0.082 ms
64 bytes from 172.25.0.2: seq=2 ttl=64 time=0.079 ms

--- c3 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.078/0.079/0.082 ms
```

**Comment by thaJeztah** [comment] 2016-06-08 11:06
I'm going to close this, because this is by design, but feel free to continue the discussion 👍

**Closed by thaJeztah** 2016-06-08 11:06 UTC

**Comment by BediarSofiane** [comment] 2016-06-08 11:22
Okay I understand,
But I am facing a scenario that is not as simple as this.
Let me explain:
I am trying to deploy a realistic network service, so it will not be realistic to have each two nodes linked by a network. I think in this case that adding a DNS server container will be a better solution. My problem is that I can't fix the IP address of a container from the API that I am using. So having a DNS server container (which needs a fixed IP address) does not resolve my problem. That's why I thought that having an embedded DNS server could help me.

**Comment by thaJeztah** [comment] 2016-06-08 11:53
Just a DNS server won't help in this case, even if you knew the IP address of C3, container C1 wouldn't be able to communicate with it, because it's not in the same network.

Note that you don't need the `--link` option to link containers, as long as they're in the same network, they can communicate with each other by "name" (or optionally, `--net-alias`). If your use case requires all containers to communicate with each other, then put them in the same network
