### ISSUE TITLE
Add implicit --net-aliases to tasks in a docker service

### ISSUE THREAD

**Issue by ktwalrus** [docker/docker#26247] opened 2016-09-01 13:47 UTC
I would like to be able to connect to a specific task in a service from some client containers rather than just using the load balanced service name.

I suggest that the tasks for a service have implicit aliases added in the internal DNS. Such an implicit alias should follow a pattern. I suggest `<service name>-<n>` where `<n>` is the task number (e.g. a service named `mysrv` with 3 replicas would have its tasks have aliases of `mysrv-1`, `mysrv-2`, `mysrv-3`.

Within the task container, the assigned task alias should be available via an ENV such as `SERVICE_TASK_NETWORK_ALIAS` so the container knows how others can reach it and to do specific task configurations (such as task 1 for a mysql service would configure itself as a Master and task 2 and 3 would configure themselves as Slaves of task 1).

**Comment by thaJeztah** [comment] 2016-10-19 16:55
Looks like this is a duplicate of https://github.com/docker/docker/issues/24787, so I'll close this one, but feel free to comment after I closed

**Closed by thaJeztah** 2016-10-19 16:55 UTC
Labels: area/networking, area/swarm, kind/feature

**Comment by ktwalrus** [comment] 2016-10-19 18:16
I don't think this is a duplicate of  #24787. My issue was to give each task/replica an alias in the internal DNS so I could reliably discover the individual task/replica from within a client. The referenced issue seems to be requesting a way to give the service an alias (not individual tasks/replicas).

**Comment by thaJeztah** [comment] 2016-10-19 18:37
You can query the DNS for `tasks.<service_name>`, which returns the IP addresses of all individual tasks.

However, your description of giving different "roles" to individual tasks may not be the best approach; tasks are considered exactly equal, so perhaps you should have different services for "master" and "slave" mysql servers

**Comment by thaJeztah** [comment] 2016-10-19 18:39
Also see the discussion on this PR https://github.com/docker/docker/pull/24973, which is probably related

**Comment by ktwalrus** [comment] 2016-10-19 19:07
PR #24973 is much closer to what I need. That is, a way to address each individual task in a service by a predictable name. Querying `tasks.<service_name>` is no sufficient since it gives a single DNS name for all the tasks in the service and not separate DNS names for each task (that can be known before the tasks have even started).

As for all tasks in a service are considered exactly equal, that model fits for when you are deploying stateless services (aka "cattle"). But, Docker services should also support the model that deploys stateful services (aka "pets") such as database clusters where each task auto configures itself to take on a "role" in the cluster. Even the Docker swarm mode uses "pets" to designate nodes that can be leaders/workers or is the current master. While a Docker swarm may dynamically change masters, a database cluster may run as a more static service where the replication topology is defined on service startup and might not change. Other database clusters with persistent data stored locally on the swarm node might be designed to change "roles" on individual task failure (promoting the master).

Anyway, the change to allow unmanaged containers to run on the same network as a managed service (not in 1.12) might mean that "pets" should always be run as unmanaged containers and not try to run them as a service. 

Still, I would like to have a DNS name for each possible task in a stateless service (like a PHP service) so I can configure my own proxy in front of the service and not be restricted to only the load balancer modes that swarm mode supports. That is, the proxy would be configured to reference each backend server using its unique task DNS name and not configured to reference only the service alias (which provides load balancing). I want my proxy to balance traffic using the load balancing method I choose.

Anyway, as long as 1.13 addresses the needs of "pets" and "cattle" with support for user provided service proxying, I'm happy. The 1.12 release was just too immature and deficient to use with my stateful backend services. I look forward to seeing how the Docker team "solves" this issue in the upcoming 1.13 release.
