### ISSUE TITLE
docker run with "--user nobody" which should have no ability to login system, however ,entered system with "-it" option

### ISSUE THREAD

**Issue by TheBeeMan** [docker/docker#23469] opened 2016-06-12 08:04 UTC
Output of docker version:
Client:
Version: 1.12.0-dev
API version: 1.24
Go version: go1.5.4
Git commit: 82141a2-unsupported
Built: Tue May 31 10:37:05 2016
OS/Arch: linux/amd64

Server:
Version: 1.12.0-dev
API version: 1.24
Go version: go1.5.4
Git commit: 82141a2-unsupported
Built: Tue May 31 10:37:05 2016
OS/Arch: linux/amd64

Containers: 16
Running: 1
Paused: 0
Stopped: 15
Images: 76
Server Version: 1.12.0-dev
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 189
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
Volume: local
Network: host bridge null
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.843 GiB
Name: thebeeman-vt
ID: TIJL:TE7H:57V2:JT6F:PK6M:YO56:FRAX:C3YP:JZYD:NMON:FM34:Q4OK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
File Descriptors: 14
Goroutines: 37
System Time: 2016-06-12T15:51:04.751837404+08:00
EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
127.0.0.0/8

**Comment by TheBeeMan** [comment] 2016-06-12 08:04
Steps to reproduce the issue:

1. On docker host: 
docker run --rm -it --user nobody debian:jessie /bin/bash
2. In the just-started container:
nobody@b9cb3ca:/$
nobody@b9cb3ca:/$ cat /etc/passwd | grep nobody
nobody:X:65534:65534:nobody:/nonexistent:/usr/sbin/nologin

it seems that user "nobody" has entered the system, which should have no ability to login the system

**Comment by justincormack** [comment] 2016-06-12 09:12
Setting the user on docker run simply sets the uid it does not try to run a
login shell - docker does not try to guess how the system inside the
container is set up.

**Comment by TheBeeMan** [comment] 2016-06-12 09:36
so, you think that's not a bug?

**Comment by justincormack** [comment] 2016-06-12 09:52
No, it is intentional. If you want to emulate your expected behaviour you
can do something like `docker run debian sh -c "su nobody ls"`

**Comment by TheBeeMan** [comment] 2016-06-12 10:45
yeah, i agree your opinion.
verifying whether a user has ability to login should do something like `docker run debian sh -c "su nobody ls"`.Only verify whether a user has ability to excute /bin/bash  could do something like `docker -it run debian /bin/bash`.
3ks.

**Comment by thaJeztah** [comment] 2016-06-12 15:25
Looks like we can close this issue, or is there anything left to be done?

**Comment by justincormack** [comment] 2016-06-14 15:40
I am going to close it as it is intentional. Feel free to discuss further though, if there are improvements we can make eg to documentation.

**Closed by justincormack** 2016-06-14 15:40 UTC
Labels: version/master
