### ISSUE TITLE
Container Lost Control after restart in service

### ISSUE THREAD

**Issue by yank1** [docker/docker#28739] opened 2016-11-23 07:30 UTC
**Description**

Container Lost Control after restart in service

**Steps to reproduce the issue:**
1. docker service create --name nginx nginx
2. docker ps # to find the container id 
3. docker restart <container-id>

**Describe the results you received:**

The service create a new container

**Describe the results you expected:**

The container is still in the service.
Or there is a way to restart container in service .

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 94
 Running: 10
 Paused: 0
 Stopped: 84
Images: 172
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1689
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: active
 NodeID: 80du319icpqvdylqcrehggfvo
 Is Manager: true
 ClusterID: 2mruzylxo37qo57a7bh2mu6qz
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.2.70
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.859 GiB
Name: yk-dev-1
ID: EDSN:P5RE:35RV:VEAW:FFUQ:EGWH:UKAQ:LKCK:JVPM:LDQY:OIMU:MPRQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
```

**Comment by allencloud** [comment] 2016-11-23 09:35
Yes, I think it  is an issue of swarm mode. In a word, if a user **restart** a task's container in a service, docker daemon loses control of this container. 

A `restart` action is separated into two parts `stop` and `start`. When stop action finished, swarmkit may lose the control of this task, the status of this task becomes shutdown, and the desired state is running, then swarm will start a new task.

However, since the task's next action is start. Docker will start the stopped container again. As a result, one more container exists in the cluster.

cc @aaronlehmann

**Comment by thaJeztah** [comment] 2016-11-24 20:19
Thanks for reporting! this is a duplicate of https://github.com/docker/docker/issues/23704, so to keep the conversation on a single place, I'll close this issue; feel free to continue the conversation there

**Closed by thaJeztah** 2016-11-24 20:19 UTC
Labels: area/swarm, kind/bug, version/1.12
