### ISSUE TITLE
Unable to start container after upgrading to Docker v1.7.0

### ISSUE THREAD

**Issue by borntorock** [docker/docker#14386] opened 2015-07-03 20:29 UTC
Hello All,

I have upgraded my Docker version from 1.0.1 to 1.7.0 after purging the previous version and then installing the latest version of Docker using the instructions mentioned here:
https://docs.docker.com/installation/ubuntulinux/

Before upgrading to Docker v1.7.0 I have removed the /var/lib/docker and /cgroup/docker folders and then searched using find command to check if there is something else related to Docker.

Then after restarting the host system, I installed the latest version of lxc-docker-1.7.0 on Ubuntu 14.04.2 LTS.

Now while testing to check if the docker has been installed properly or not, I ran the command:

docker run hello-world

Please see the below output, received after executing the above command.

Unable to find image 'hello-world:latest' locally
latest: Pulling from hello-world
a8219747be10: Pull complete
91c95931e552: Already exists
hello-world:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:aa03e5d0d5553b4c3473e89c8619cf79df368babd18681cf5daeb82aab55838d
Status: Downloaded newer image for hello-world:latest
Error response from daemon: Cannot start container 80d1d6270f109115c61a9561c359560b5a578f6d52ea8b62c8779f94149b33b9: [8] System error: write /cgroup/docker/80d1d6270f109115c61a9561c359560b5a578f6d52ea8b62c8779f94149b33b9/cgroup.procs: no space left on device

The version of docker installed is 1.7.0 checked using "docker version" command. previously I had no images and no containers on my system, checked using "docker info" command.

There is nothing present in the logs of the container. Also, I can view this container after executing the command: docker ps -a and the status is blank.

Though I have enough space on my host system around 285GB, still it is showing that there is no space left on device, on running the first container. I was able to launch the docker containers easily on v1.0.1

After restarting the docker service and trying this out for other images "Ubuntu" and looking at some references, I'm not able to resolve this issue.

Any suggestions on how to resolve this issue, Please do let me know.

Thanks,
Nitin Agarwal

**Comment by thaJeztah** [comment] 2015-07-03 23:09
Hi @borntorock could you provide the information as requested above? 

Also, have you tried using the uninstallation procedure as explained here; https://docs.docker.com/installation/ubuntulinux/#uninstallation?

**Comment by borntorock** [comment] 2015-07-04 17:10
@thaJeztah 

Please see the below information of the commands:

docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64


docker info 

Containers: 3
Images: 6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 5.725 GiB
Name: nitin
ID: TQCL:46GQ:LNQR:7GWE:JFZQ:HKHG:Q6TJ:4IYO:WDAN:APRZ:QBZ3:5QS6
Username: nitinagarwal
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

Please note that since I have tried to install hello-world image and Ubuntu:14.04 image, it is showing 6 images and 2 containers were started using hello-world image and other one using Ubuntu:14.04 image

uname -a

Linux nitin 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I hope I have mentioned about the steps followed, in my previous message. But Please feel free to let me know if you need any other information.

Yes, I have followed exactly the same steps as mentioned over here: https://docs.docker.com/installation/ubuntulinux/#uninstallation

**Comment by borntorock** [comment] 2015-07-07 18:13
Hi @thaJeztah, did you got some time to look at this. Please feel free to let me know if you need any other information or output / logs of any other command.

**Comment by thaJeztah** [comment] 2015-07-07 19:30
Not really had the time you could try the [contrib/check-config.sh](https://github.com/docker/docker/blob/master/contrib/check-config.sh) script just to check if everything is in order. I'm not really sure what the cause here is. I've seen some reports ranging from issues with a specific kernel, running out of inodes, also found [this on StackOverflow](http://stackoverflow.com/questions/29961584/docker-cgroup-procs-no-space-left-on-device)

**Comment by borntorock** [comment] 2015-07-07 19:38
Shall i try to execute the check-config.sh script file. Please see the logs, mentioned in my first message, which I'm getting while trying to pull image from the docker hub and while trying to launch containers. 

The error is:
Error response from daemon: Cannot start container 80d1d6270f109115c61a9561c359560b5a578f6d52ea8b62c8779f94149b33b9: [8] System error: write /cgroup/docker/80d1d6270f109115c61a9561c359560b5a578f6d52ea8b62c8779f94149b33b9/cgroup.procs: no space left on device

The issue is somewhat related to https://github.com/docker/docker/issues/13843
http://stackoverflow.com/questions/30604846/docker-error-no-space-left-on-device
But none of the solutions mentioned over here, resolved my issue.

**Comment by thaJeztah** [comment] 2015-07-07 20:15
Running the check-config script never hurts, but I'm not sure it will more insight here. I asked around, but no real answer. This really sounds like something specific to your system (or still some leftovers from the old installation).

Perhaps you could try the #docker IRC channel, if someone has ideas?

**Comment by borntorock** [comment] 2015-07-08 06:20
check-config  script doesn't give any insight on this issue. I did checked again if any thing related to docker is still present on my host system using find command after uninstalling lxc-docker as mentioned in the documentation.

After that I tried to install lxc-docker latest version again, still getting the same error.

**Comment by borntorock** [comment] 2015-07-21 19:38
Any suggestions on how shall I resolve this issue. Stuck on this for few weeks. 

I would highly appreciate with any kind of help provided to resolve this issue.

**Comment by thaJeztah** [comment] 2015-07-21 23:08
@borntorock hm, sorry, I don't have suggestions at this point, but no expert in this area. Perhaps you can try the IRC channel if someone has suggestions?

/cc @LK4D4 could you help out here, or have suggestions for useful information to help finding the cause or someone that might know?

**Comment by stevenschlansker** [comment] 2015-07-24 20:34
We just reproduced this error message on docker 1.7.1, Ubuntu 14.04.2, kernel 4.1.2, overlay storage backend.

**Comment by thaJeztah** [comment] 2015-07-24 21:50
@stevenschlansker FYI, You're running ubuntu 14.04.2 with a custom kernel (ubuntu 14.04 doesn't ship with kernel 4); we don't support that setup.

**Comment by stevenschlansker** [comment] 2015-07-24 22:43
Presumably you'd rather know that the problem both affects the distro kernel and a vanilla kernel.  The original ticket was from a distro kernel, so I don't see how the fact that we are running vanilla is super relevant...

**Comment by thaJeztah** [comment] 2015-07-24 22:50
@stevenschlansker alright, fair (sorry if I came across a bit harsh). Did you get this on a freshly installed machine, or also after updating an older version of docker?

**Comment by stevenschlansker** [comment] 2015-07-24 23:02
Also upgrade (most recently from 1.6.2)

**Comment by stevenschlansker** [comment] 2015-07-29 23:03
This state prevents any further containers from being created, a system reboot resolves the situation, at least for us.

**Comment by discordianfish** [comment] 2015-08-10 10:39
We see the same error on a large coreos cluster where about 5% of all systems show this behaviour even though they are all configured the same. #13843 seems to be a duplicate of this one and reporting the issue for 1.6.2.

**Comment by discordianfish** [comment] 2015-08-10 11:14
I found https://github.com/torvalds/linux/blob/de182468d1bb726198abaab315820542425270b7/kernel/cpuset.c#L499 which might be the origin of this error. So maybe Docker for some reasons didn't set the cpus or memory available to the process before moving the process to the cgroup?

```
cd /sys/fs/cgroup/cpuset
mkdir test
cd test
echo $$ > tasks
bash: echo: write error: No space left on device
echo 0 > cpuset.cpus
echo 0 > cpuset.mems
echo $$ > tasks
cat /proc/self/cpuset
/test
```

**Comment by discordianfish** [comment] 2015-08-10 11:19
Okay, I think this is a known issue in libcontainer: https://github.com/opencontainers/runc/issues/133

**Comment by borntorock** [comment] 2015-08-10 19:00
@stevenschlansker System reboot doesn't resolve this issue for me. 

@discordianfish Did you received any luck in resolving this issue on your systems.

**Comment by discordianfish** [comment] 2015-08-11 10:41
@borntorock Haven't yet implemented it, but running

    echo 0 >  /sys/fs/cgroup/cpuset/system.slice/cpuset.mems

before docker stats should solve it.

**Comment by borntorock** [comment] 2015-08-24 18:53
I tried to create the nested docker containers after building the docker images on a freshly created new VM with Ubuntu 14.04 OS. Hence while creating the docker containers, after building the docker images successfully, I got only one container out of seven docker containers created. Hence while got the same issue as mentioned above "Error response from daemon: Cannot start container.... System error...., no space left on device" while creating the other containers.

Any suggestions?

**Comment by PlugIN73** [comment] 2016-03-09 09:47
Happened to me on docker:
```
$ docker info
Containers: 4251
Images: 1408
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-31-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 29.96 GiB
Name: ip-10-0-1-222
ID: IOQM:NZQ2:3EJL:FVYH:Y42O:45OW:RZZC:Y26G:IBYO:MDTT:PMJE:7D5B
WARNING: No swap limit support
```
Docker restart didn't affect this error, but system restart did.

**Comment by mescanef** [comment] 2016-04-06 11:06
Folks, try installing 'lxc' package. Probably "/sys/fs/cgroup/cpuset/cgroup.clone_children" is set to 0 in your case, and it should be '1'.

# lxc-checkconfig 
(...)
Cgroup clone_children flag: enabled

**Comment by cpuguy83** [comment] 2017-03-06 05:00
Closing since this looks resolved in runc.

**Closed by cpuguy83** 2017-03-06 05:00 UTC
Labels: area/runtime, kind/bug
