### ISSUE TITLE
Question: Does docker keep the mount.ID same across container restarts?

### ISSUE THREAD

**Issue by krish7919** [docker/docker#24883] opened 2016-07-21 04:04 UTC
I am trying to maintain state across the container restarts and they persist data into a folder that is created when the container starts for the first time.
If the container restarts, I want to give the same dir path again to the container using my custom docker volume plugin.

My question is does docker provide the same mount.ID for the same container to a docker volume plugin?

**Comment by thaJeztah** [comment] 2016-07-21 11:56
If you do not provide a name for a volume, then docker will generate one when it's created. This name is stored in the container config, so will not change (also not between restarts). However, a volume that is *not* explicitly named, is considered "ephemeral" in some cases, for example:

start an interactive container with an "unnamed" volume for `/foobar`:

```bash
docker run -v /foobar -it --rm --name some-container alpine sh
```

In another shell:

```bash
docker inspect --format '{{ json .Mounts }}' some-container
[{"Name":"d88bccf10009985f9336278a8b1b44371ff7256da926ce16dd0e846e602ac77c","Source":"/var/lib/docker/volumes/d88bccf10009985f9336278a8b1b44371ff7256da926ce16dd0e846e602ac77c/_data","Destination":"/foobar","Driver":"local","Mode":"","RW":true,"Propagation":""}]

docker volume ls --filter name=d88bccf10009985f9336278a8b1b44371ff7256da926ce16dd0e846e602ac77c

DRIVER              VOLUME NAME
local               d88bccf10009985f9336278a8b1b44371ff7256da926ce16dd0e846e602ac77c
```

However, the moment the container is stopped, it will be removed *including* the volume:

```bash
docker kill some-container
some-container

docker volume ls --filter name=d88bccf10009985f9336278a8b1b44371ff7256da926ce16dd0e846e602ac77c

DRIVER              VOLUME NAME
```

To make sure a container persist, either name it explicitly, or create the volume first, and specify the automatically generated name for the container;

Example 1: explicitly name the volume:

```bash
docker run -it --rm -v my-volume:/foobar --name some-container alpine sh
```

Example 2: create the volume "out of bound", and use the generated (random) name:

```bash
docker volume create
3a975286dc446b51792c9b7ca95837408057f7852ba5c0555391e27ca8130712

docker run -it --rm -v 3a975286dc446b51792c9b7ca95837408057f7852ba5c0555391e27ca8130712:/foobar --name some-container nginx sh
```

you can do the above in one go, using:

```bash
docker run -it --rm -v $(docker volume create):/foobar --name some-container alpine sh
```

I'm closing this issue, because this is a question, not a bug report, and our GitHub issue tracker is not really intended for that, but feel free to continue the discussion

**Closed by thaJeztah** 2016-07-21 11:56 UTC

**Comment by cpuguy83** [comment] 2016-07-21 12:18
I'm believe we do provide the same opaque id, but will have to check the code, I can't remember... Or you could test it.

**Comment by thaJeztah** [comment] 2016-07-21 12:29
oh, wait, this is about mount id, not the volume name, sorry for the confusion on my side :smile:
