### ISSUE TITLE
COPY or ADD don't invalidate cache upon file change

### ISSUE THREAD

**Issue by collinjackson93** [docker/docker#17957] opened 2015-11-13 06:06 UTC
**Description of problem:**
It seems that changing a file within a directory that is being `COPY`-ed or `ADD`-ed to an image does not always invalidate the cache for that layer.

`docker version`:
 >Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64

`docker info`:
>Containers: 5
Images: 83
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 93
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: FDJI:ERKY:TGZG:3AQ3:V3LN:J43K:GK5A:EK2W:75BG:ATWV:YJFI:BOUO
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 19
 System Time: 2015-11-13T05:51:00.189355201Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

`uname -a`: 
>MINGW64_NT-10.0 ASUS 2.3.0(0.290/5/3) 2015-09-29 10:48 x86_64 Msys

**Environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox running on Windows 10

**How reproducible:**
Use a Dockerfile like [this](https://github.com/cs4278-2015/IronMail/blob/2d865b05df86654f457b715f9362685e7838c4de/server/Dockerfile) (main `ADD` occurs on line 16)

**Steps to Reproduce:**
1. Create file in directory referenced by `ADD` or `COPY`
2. Build image
3. Modify newly-created file
4. Re-build image

**Actual Results:**
The source files are copied over from the cache.

**Expected Results:**
The cache for that layer should be invalidated and the files should be copied over fresh

**Additional info:**
I have played around a little and found that it did not matter if I was using `ADD` or `COPY` or if the source was `.` or a child directory.

**Comment by LewisW** [comment] 2015-11-14 11:20
Same is happening for me. The time on the virtual machine appears to be off by a few minutes, so I wonder if that it is having any effect.

**Comment by collinjackson93** [comment] 2015-11-14 20:06
I'm glad to know I'm not the only one experiencing this issue. I haven't noticed the time synchronization problem, but I'm not sure it's related. From what I understand, Docker should compare checksums for each file against the files in existing images, so creation time isn't considered.

**Comment by zanemcca** [comment] 2015-11-16 16:35
I am having this issue if my file change is in a subdirectory of the one being copied.

**Comment by collinjackson93** [comment] 2015-11-16 16:40
I haven't experienced this issue for a couple of days now, which is a little bittersweet (I'm not sure how to reliably reproduce it).

**Comment by zanemcca** [comment] 2015-11-16 17:28
There is a bunch of discussion happening [here](17290) that is blaming cache invalidation issues on broken symlinks somewhere in your directory.
I found some broken links that I had and after removing them the invalidation started working properly.

**Comment by LewisW** [comment] 2015-11-16 18:11
Thank you so much, my problem was exactly that! Found with:

```
find . -type l -! -exec test -e {} \; -print
```

Probably safe to assume this is a duplicate of #17290.

**Comment by crosbymichael** [comment] 2015-11-16 23:52
Yes, this is a dup of #17290 and should be resolved in 1.9.1

Thanks for the report!

**Closed by crosbymichael** 2015-11-16 23:52 UTC
