### ISSUE TITLE
[1.10] Panic in JSON unmarshalling

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19178] opened 2016-01-08 04:03 UTC
Unfortunately I don't know the exact commit of the daemon running at the time.  It would have been from master within the last day, maybe two, but pretty sure it was from yesterday.  I really have no clue what would cause this panic.

```
fatal error: fault
[signal 0xb code=0x80 addr=0x0 pc=0x63e559]

goroutine 27190 [running]:
runtime.throw(0x15e05d8, 0x5)
	/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc8219eda78 sp=0xc8219eda60
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc8219edac8 sp=0xc8219eda78
encoding/json.unquoteBytes(0xc82109c918, 0x4b7, 0x1fac, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:1006 +0x119 fp=0xc8219edba0 sp=0xc8219edac8
encoding/json.(*decodeState).literalStore(0xc820b17860, 0xc82109c917, 0x4b7, 0x1fad, 0x1165860, 0xc8218a3338, 0xd8, 0x0)
	/usr/local/go/src/encoding/json/decode.go:738 +0xb4e fp=0xc8219ee048 sp=0xc8219edba0
encoding/json.(*decodeState).literal(0xc820b17860, 0x1165860, 0xc8218a3338, 0xd8)
	/usr/local/go/src/encoding/json/decode.go:646 +0xe9 fp=0xc8219ee0b0 sp=0xc8219ee048
encoding/json.(*decodeState).value(0xc820b17860, 0x1165860, 0xc8218a3338, 0xd8)
	/usr/local/go/src/encoding/json/decode.go:299 +0x397 fp=0xc8219ee188 sp=0xc8219ee0b0
encoding/json.(*decodeState).object(0xc820b17860, 0x1482500, 0xc8218a3310, 0xd9)
	/usr/local/go/src/encoding/json/decode.go:613 +0x1179 fp=0xc8219ee530 sp=0xc8219ee188
encoding/json.(*decodeState).value(0xc820b17860, 0x1482500, 0xc8218a3310, 0xd9)
	/usr/local/go/src/encoding/json/decode.go:296 +0x3bd fp=0xc8219ee608 sp=0xc8219ee530
encoding/json.(*decodeState).array(0xc820b17860, 0x112f460, 0xc821c84bb8, 0xd7)
	/usr/local/go/src/encoding/json/decode.go:447 +0xa6b fp=0xc8219ee810 sp=0xc8219ee608
encoding/json.(*decodeState).value(0xc820b17860, 0x112f460, 0xc821c84bb8, 0xd7)
	/usr/local/go/src/encoding/json/decode.go:293 +0x3dd fp=0xc8219ee8e8 sp=0xc8219ee810
encoding/json.(*decodeState).object(0xc820b17860, 0x149f420, 0xc821c84a00, 0xd9)
	/usr/local/go/src/encoding/json/decode.go:613 +0x1179 fp=0xc8219eec90 sp=0xc8219ee8e8
encoding/json.(*decodeState).value(0xc820b17860, 0x144c1c0, 0xc821c84a00, 0x16)
	/usr/local/go/src/encoding/json/decode.go:296 +0x3bd fp=0xc8219eed68 sp=0xc8219eec90
encoding/json.(*decodeState).unmarshal(0xc820b17860, 0x144c1c0, 0xc821c84a00, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:157 +0x196 fp=0xc8219eee40 sp=0xc8219eed68
encoding/json.Unmarshal(0xc82109c000, 0x26c4, 0x28c4, 0x144c1c0, 0xc821c84a00, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:85 +0x12b fp=0xc8219eeeb0 sp=0xc8219eee40
github.com/docker/docker/image.NewFromJSON(0xc82109c000, 0x26c4, 0x28c4, 0xc82109c000, 0x0, 0x0)
	/go/src/github.com/docker/docker/image/image.go:118 +0xaf fp=0xc8219eef40 sp=0xc8219eeeb0
github.com/docker/docker/image.(*store).Get(0xc8208bf700, 0xc820974dc0, 0x47, 0xc8219ef010, 0x0, 0x0)
	/go/src/github.com/docker/docker/image/store.go:186 +0xee fp=0xc8219eefd8 sp=0xc8219eef40
github.com/docker/docker/image.(*store).imagesMap(0xc8208bf700, 0x1, 0x0)
	/go/src/github.com/docker/docker/image/store.go:281 +0x1f6 fp=0xc8219ef0f8 sp=0xc8219eefd8
github.com/docker/docker/image.(*store).Map(0xc8208bf700, 0xc821465000)
	/go/src/github.com/docker/docker/image/store.go:268 +0x26 fp=0xc8219ef118 sp=0xc8219ef0f8
github.com/docker/docker/daemon.(*Daemon).SystemInfo(0xc820080840, 0xc821bf5980, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/info.go:60 +0x425 fp=0xc8219ef3f0 sp=0xc8219ef118
github.com/docker/docker/api/server/router/system.(*systemRouter).getInfo(0xc820a6cfc0, 0x7fec96d2b820, 0xc821bf5980, 0x7fec96d2b770, 0xc821a37970, 0xc820fa9960, 0xc821bf5890, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/router/system/system_routes.go:30 +0x53 fp=0xc8219ef460 sp=0xc8219ef3f0
github.com/docker/docker/api/server/router/system.(*systemRouter).(github.com/docker/docker/api/server/router/system.getInfo)-fm(0x7fec96d2b820, 0xc821bf5980, 0x7fec96d2b770, 0xc821a37970, 0xc820fa9960, 0xc821bf5890, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/router/system/system.go:26 +0x74 fp=0xc8219ef4b0 sp=0xc8219ef460
github.com/docker/docker/api/server.versionMiddleware.func1(0x7fec96d2b820, 0xc821bf5980, 0x7fec96d2b770, 0xc821a37970, 0xc820fa9960, 0xc821bf5890, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:142 +0x83a fp=0xc8219ef630 sp=0xc8219ef4b0
github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7fec995a0b40, 0xc82000fae0, 0x7fec96d2b770, 0xc821a37970, 0xc820fa9960, 0xc821bf5890, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:121 +0xfa fp=0xc8219ef690 sp=0xc8219ef630
github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7fec995a0b40, 0xc82000fae0, 0x7fec96d2b770, 0xc821a37970, 0xc820fa9960, 0xc821bf5890, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:104 +0x4be fp=0xc8219ef7a0 sp=0xc8219ef690
github.com/docker/docker/api/server.debugRequestMiddleware.func1(0x7fec995a0b40, 0xc82000fae0, 0x7fec96d2b770, 0xc821a37970, 0xc820fa9960, 0xc821bf5890, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware.go:52 +0x7ca fp=0xc8219ef970 sp=0xc8219ef7a0
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fec96d2b770, 0xc821a37970, 0xc820fa9960)
	/go/src/github.com/docker/docker/api/server/server.go:167 +0x2ad fp=0xc8219efa98 sp=0xc8219ef970
net/http.HandlerFunc.ServeHTTP(0xc8206c9d80, 0x7fec96d2b770, 0xc821a37970, 0xc820fa9960)
	/usr/local/go/src/net/http/server.go:1422 +0x3a fp=0xc8219efab8 sp=0xc8219efa98
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82083a1e0, 0x7fec96d2b770, 0xc821a37970, 0xc820fa9960)
	/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e fp=0xc8219efbd0 sp=0xc8219efab8
net/http.serverHandler.ServeHTTP(0xc8200188a0, 0x7fec96d2b770, 0xc821a37970, 0xc820fa9960)
	/usr/local/go/src/net/http/server.go:1862 +0x19e fp=0xc8219efc30 sp=0xc8219efbd0
net/http.(*conn).serve(0xc8216e7340)
	/usr/local/go/src/net/http/server.go:1361 +0xbee fp=0xc8219eff88 sp=0xc8219efc30
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc8219eff90 sp=0xc8219eff88
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by HackToday** [comment] 2016-01-08 05:07
hi @ibuildthecloud  do you know how to reproduce that ?

**Comment by MHBauer** [comment] 2016-01-08 05:09
This looks like a Remote API call to `/info`.

My guess is it's in this part of the stacktrace:
```
github.com/docker/docker/image.NewFromJSON(0xc82109c000, 0x26c4, 0x28c4, 0xc82109c000, 0x0, 0x0)
    /go/src/github.com/docker/docker/image/image.go:118 +0xaf fp=0xc8219eef40 sp=0xc8219eeeb0
github.com/docker/docker/image.(*store).Get(0xc8208bf700, 0xc820974dc0, 0x47, 0xc8219ef010, 0x0, 0x0)
    /go/src/github.com/docker/docker/image/store.go:186 +0xee fp=0xc8219eefd8 sp=0xc8219eef40
github.com/docker/docker/image.(*store).imagesMap(0xc8208bf700, 0x1, 0x0)
    /go/src/github.com/docker/docker/image/store.go:281 +0x1f6 fp=0xc8219ef0f8 sp=0xc8219eefd8
github.com/docker/docker/image.(*store).Map(0xc8208bf700, 0xc821465000)
    /go/src/github.com/docker/docker/image/store.go:268 +0x26 fp=0xc8219ef118 sp=0xc8219ef0f8
github.com/docker/docker/daemon.(*Daemon).SystemInfo(0xc820080840, 0xc821bf5980, 0x0, 0x0)
    /go/src/github.com/docker/docker/daemon/info.go:60 +0x425 fp=0xc8219ef3f0 sp=0xc8219ef118
```
And the only change there within the last two or three days is the switch to using docker/engine-api

It would be really good to have the server version to be sure.

**Comment by MHBauer** [comment] 2016-01-08 05:25
Next guess is there is something wonky with the image config that it tries to unmarshal. I am kind of surprised it _panics_ unmarshalling and doesn't return an error.

**Comment by cpuguy83** [comment] 2016-01-08 15:38
Really strange -- https://golang.org/src/encoding/json/decode.go#L1006
Compiled with Go 1.5.2?

**Comment by ibuildthecloud** [comment] 2016-01-21 17:12
I haven't seen this in awhile, should we close this?

**Comment by thaJeztah** [comment] 2016-02-02 14:32
@ibuildthecloud I'll close it, but ping me if you think it needs to be reopened

**Closed by thaJeztah** 2016-02-02 14:32 UTC
