### ISSUE TITLE
Same image & container has different behavior on different hosts

### ISSUE THREAD

**Issue by FelikZ** [docker/docker#26317] opened 2016-09-05 13:29 UTC
**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 26
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.3.el7.x86_64
Operating System: Scientific Linux 7.1 (Nitrogen)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.26 GiB
Name: tkt-jdevel-01.textkernel.local
ID: G4SU:OW44:CR44:RVBY:XLMD:SKPB:DNB2:SIRO:KWEF:D7AR:WUUZ:GMON
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 docker-reg.textkernel.local:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Affected instance running on VM, working on physical PC.

**Steps to reproduce the issue:**
1. `docker run --rm -ti php:5.6.14-fpm bash -ci 'gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 9554F04D7259F04124DE6B476D5A82AC7E37093B'`

**Describe the results you received:**
```
gpg: requesting key 7E37093B from hkp server ha.pool.sks-keyservers.net
gpg: renaming `/root/.gnupg/pubring.gpg' to `/root/.gnupg/pubring.gpg~' failed: Invalid argument
gpg: error writing keyring `/root/.gnupg/pubring.gpg': file rename error
gpg: key 7E37093B: public key "[User ID not found]" imported
gpg: error reading `[stream]': file rename error
gpg: Total number processed: 0
gpg:               imported: 1  (RSA: 1)
```

**Describe the results you expected:**
```
gpg: requesting key 7E37093B from hkp server ha.pool.sks-keyservers.net
gpg: key 7E37093B: public key "Christopher Dickinson <christopher.s.dickinson@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Running same container from same image with the same version of docker (both overlayfs) on different hosts causing different results.

```
# hostnamectl
   Static hostname: anonymous
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 8f378caacc1d4110867b064e0a722d3c
           Boot ID: dd2cfe9f9b6a4479893a8441668a0fa1
    Virtualization: kvm
  Operating System: Scientific Linux 7.1 (Nitrogen)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.1:GA
            Kernel: Linux 3.10.0-327.28.3.el7.x86_64
      Architecture: x86-64
```

**Output of `docker version` (working instance):**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info` (working instance):**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 54
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.58 GiB
Name: tk9
ID: CYDT:VFSD:2M77:W5P7:OQUD:J6G7:EWQR:KJWR:SOUX:JCLZ:2SBG:J7GX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 docker-reg.textkernel.local:5000
 127.0.0.0/8
```

Same happens during image build. On PC host everything okay but not on VM host.

**Comment by FelikZ** [comment] 2016-09-05 13:43
So it looks like the issue with filesystem:

```
root@7dfe5182a6ab:/var/www/html# mv /root/.gnupg/pubring.gpg /root/.gnupg/pubring_1.gpg                                                                                                                            
mv: cannot move '/root/.gnupg/pubring.gpg' to a subdirectory of itself, '/root/.gnupg/pubring_1.gpg'
```

This does not happen with PC, investigating more.

**Comment by FelikZ** [comment] 2016-09-05 14:02
Stopping docker service and clearing `/var/lib/docker` does not help to solve this issue.

I am not able to switch from `overlay` fs since all other complain that:
```
"Error starting daemon: error initializing graphdriver: driver not supported"
```

**Comment by FelikZ** [comment] 2016-09-05 14:13
It looks like that it is not possible to move files that being created during the base image build.

Look at `secring.gpg` date:

```bash
root@65102f89fd68:~# ls -l .gnupg
total 20
-rw-r--r-- 1 root root    0 Sep  5 14:07 1
-rw-r--r-- 1 root root    0 Sep  5 14:08 2
-rw------- 1 root root 9188 Oct 23  2015 gpg.conf
-rw------- 1 root root    0 Sep  5 14:08 pubring.gpg
-rw------- 1 root root 2060 Sep  5 14:08 pubring.gpg.tmp
-rw------- 1 root root    0 Oct 23  2015 secring.gpg
-rw------- 1 root root 1200 Sep  5 14:06 trustdb.gpg
root@65102f89fd68:~# mv .gnupg/pubring.gpg .gnupg/pubring.gpg~                                                                                                                                                     
mv: cannot move '.gnupg/pubring.gpg' to a subdirectory of itself, '.gnupg/pubring.gpg~'
root@65102f89fd68:~# cp -R .gnupg .gnupg_ok
root@65102f89fd68:~# mv .gnupg_ok/pubring.gpg .gnupg_ok/pubring.gpg~                                                                                                                                               
root@65102f89fd68:~# mv .gnupg_ok/pubring.gpg~ .gnupg/pubring.gpg~                                                                                                                                                 
root@65102f89fd68:~# ls -l .gnupg            
total 20
-rw-r--r-- 1 root root    0 Sep  5 14:07 1
-rw-r--r-- 1 root root    0 Sep  5 14:08 2
-rw------- 1 root root 9188 Oct 23  2015 gpg.conf
-rw------- 1 root root    0 Sep  5 14:08 pubring.gpg
-rw------- 1 root root 2060 Sep  5 14:08 pubring.gpg.tmp
-rw------- 1 root root    0 Sep  5 14:10 pubring.gpg~
-rw------- 1 root root    0 Oct 23  2015 secring.gpg
-rw------- 1 root root 1200 Sep  5 14:06 trustdb.gpg
```

**Comment by FelikZ** [comment] 2016-09-05 14:18
The problem is exactly with filename / path, since I can freely create and rename new files but not when filename are the same as it being created in image:

```
root@65102f89fd68:~# ls -la ~/.gnupg
total 12
drwx------ 1 root root 4096 Sep  5 14:15 .
drwx------ 1 root root 4096 Sep  5 14:15 ..
-rw-r--r-- 1 root root    0 Sep  5 14:15 2
-rw------- 1 root root    0 Sep  5 14:14 pubring.gpg
-rw------- 1 root root 2060 Sep  5 14:14 pubring.gpg.tmp
-rw------- 1 root root    0 Sep  5 14:14 secring.gpg
root@65102f89fd68:~# mv ~/.gnupg/pubring.gpg ~/.gnupg/pubring.gpg1
mv: cannot move '/root/.gnupg/pubring.gpg' to a subdirectory of itself, '/root/.gnupg/pubring.gpg1'
root@65102f89fd68:~# echo 1 > ~/.gnupg/pubring.gpg
root@65102f89fd68:~# mv ~/.gnupg/pubring.gpg ~/.gnupg/pubring.gpg1
mv: cannot move '/root/.gnupg/pubring.gpg' to a subdirectory of itself, '/root/.gnupg/pubring.gpg1'
root@65102f89fd68:~# rm ~/.gnupg/pubring.gpg
root@65102f89fd68:~# echo 1 > ~/.gnupg/pubring.gpg
root@65102f89fd68:~# mv ~/.gnupg/pubring.gpg ~/.gnupg/pubring.gpg1
mv: cannot move '/root/.gnupg/pubring.gpg' to a subdirectory of itself, '/root/.gnupg/pubring.gpg1'
root@65102f89fd68:~# echo 1 > ~/.gnupg/pubring_2.gpg
root@65102f89fd68:~# mv ~/.gnupg/pubring_2.gpg ~/.gnupg/pubring.gpg1
```

**Comment by FelikZ** [comment] 2016-09-05 14:20
Might be related to https://github.com/docker/docker/issues/25409

**Comment by FelikZ** [comment] 2016-09-05 16:10
Iteratively I have found that this not happen with `php:5.6.20-fpm` image, so maybe not all images from official docker registry compatible with overlay fs on centos 7.1?

```bash
$ docker run --rm -ti php:5.6.20-fpm bash -ci 'gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 9554F04D7259F04124DE6B476D5A82AC7E37093B'
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 7E37093B from hkp server ha.pool.sks-keyservers.net
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 7E37093B: public key "Christopher Dickinson <christopher.s.dickinson@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
$ docker run --rm -ti php:5.6.14-fpm bash -ci 'gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 9554F04D7259F04124DE6B476D5A82AC7E37093B'
gpg: requesting key 7E37093B from hkp server ha.pool.sks-keyservers.net
gpg: renaming `/root/.gnupg/pubring.gpg' to `/root/.gnupg/pubring.gpg~' failed: Invalid argument
gpg: error writing keyring `/root/.gnupg/pubring.gpg': file rename error
gpg: key 7E37093B: public key "[User ID not found]" imported
gpg: error reading `[stream]': file rename error
gpg: Total number processed: 0
gpg:               imported: 1  (RSA: 1)
```

**Comment by FelikZ** [comment] 2016-09-05 16:16
Tryied to build 5.6.18 from the source https://github.com/docker-library/php/blob/7bd5c38db974ee629a815896add1ec568a1cc88c/5.6/Dockerfile

Build failed with similar file system error:
```
Setting up ca-certificates (20141019+deb8u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up curl (7.38.0-4+deb8u4) ...
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for ca-certificates (20141019+deb8u1) ...
Updating certificates in /etc/ssl/certs... 174 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
rm: cannot remove '/var/lib/apt/lists/partial': Invalid argument
The command '/bin/sh -c apt-get update && apt-get install -y ca-certificates curl librecode0 libsqlite3-0 libxml2 --no-install-recommends && rm -r /var/lib/apt/lists/*' returned a non-zero code: 1
```

Now I am 100% sure that overlayfs is an issue. Will try to migrate to devicemapper instead.

**Comment by FelikZ** [comment] 2016-09-06 09:18
Solved by switching to `devicemapper` storage driver.

**Comment by cpuguy83** [comment] 2016-09-06 13:28
ping @dmcgowan

**Comment by dmcgowan** [comment] 2016-09-06 16:27
Renaming on lower directories is a known limitation of overlay which needs to get resolved in the kernel. Closing as a duplicate of #25409.

**Closed by dmcgowan** 2016-09-06 16:27 UTC
Labels: area/storage/overlay, version/1.12
