### ISSUE TITLE
1.12 rc3 load balancing findings

### ISSUE THREAD

**Issue by adrianovieira** [docker/docker#24417] opened 2016-07-07 15:12 UTC
Although so far I don't know what's the scope or your plans for "docker swarm mode", mainly for docker-1.12, I'll share with you my findings til now.

I've been trying some scenarios on your docker-1.12 since rc1 and for now on the latest  rc3 version release.

**Output of `docker version`:**

```
Docker version 1.12.0-rc3, build 91e29e8
```

**Output of `docker info`:**

```
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 1.12.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-253:0-2098525-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 204.1 MB
 Data Space Total: 107.4 GB
 Data Space Available: 38.26 GB
 Metadata Space Used: 905.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: active
 NodeID: df078qyxc20pi5874xkwukn1o
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:36f95d744ff15dc8fb9e8492df6b270aea3c3c20c9c09fdfba278b832988986f
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797 GiB
Name: manager1
ID: 4QYH:CBGZ:6RN3:27CC:V4OH:MFBS:RPHQ:A4LI:5YJZ:VJHJ:TRJR:XZKL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 48
 Goroutines: 160
 System Time: 2016-07-07T09:56:00.863680386-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I've noticed this behaviour on Centos-7, Debian-8 or even on Ubuntu-14 
VirtualBox-5.0.22
 - CentOS Linux release 7.2.1511 (Core)

**Steps to reproduce the issue:**
1. at first, setup 2 nodes (manager, worker1) only
2. create a simple service (e.g ping docker.com) with one replica
3. scale that service by 3 (or more) replicas (you also could do this on step 2, of course)
4. turn up one (or more) workers 

```
# docker node ls
ID                           HOSTNAME  MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
0ekt6mkv3wzfraideu254bb50    worker2   Accepted    Ready   Active        
aaalz5jo83po1j4iwfcnfi1p7    worker1   Accepted    Ready   Active        
df078qyxc20pi5874xkwukn1o *  manager1  Accepted    Ready   Active        Leader
```

**Describe the results you received:**
All tasks which was running on those first two nodes remain there even with the new node attached.

There is no automated load balancing (orchestration).

```
# docker service tasks ping-dtpnet 
ID                         NAME           SERVICE      IMAGE   LAST STATE        DESIRED STATE  NODE
5snx4jhvl3fa5sygdk3jn28a7  ping-dtpnet.1  ping-dtpnet  alpine  Running 16 hours  Running        manager1
akkkrivk6xvcb1ecfj5qu580e  ping-dtpnet.2  ping-dtpnet  alpine  Running 16 hours  Running        manager1
4e9uj3adz6hy6dlikbha70xxr  ping-dtpnet.3  ping-dtpnet  alpine  Running 15 hours  Running        worker1

# docker service tasks ping-git 
ID                         NAME        SERVICE   IMAGE   LAST STATE        DESIRED STATE  NODE
17kh15tjhoizsr4rlliyu0n8c  ping-git.1  ping-git  debian  Running 15 hours  Running        worker1
e1b8rxjdct87oznps4wdnclqh  ping-git.2  ping-git  debian  Running 15 hours  Running        worker2
409srti7xqeh988x0smbcjzrb  ping-git.3  ping-git  debian  Running 15 hours  Running        manager1
```

Those `ping-git` service tasks  are balanced only because I've created (or rescale manually) those ones after all nodes (manager and workers) have been setup and running.

**Describe the results you expected:**
It expected that all tasks (e.g ping-dtpnet) could be distributed on all new workers attached to swarm 

I intended after joining one or more new nodes to the swarm "farm"  all service
tasks could be distributed automatically on those all new nodes.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mavenugo** [comment] 2016-07-07 15:18
@adrianovieira As per terminology, this is not the `load-balancing` feature. This is more of `scheduling` and how swarmKit schedules the tasks on available nodes. As far as the behavior is concerned, this is expected. Swarmkit will reschedule the tasks of a running service on the newly available node only if an existing node goes down or if the user scales it (after the new node is made available).

**Comment by cpuguy83** [comment] 2016-07-07 15:25
Yes, as @mavenugo mentioned, swarmkit will (currently) only reschedule tasks for nodes that have gone down.

It does not automatically re-balance the cluster when a new node joins since this would mean taking down services that are currently running to move them to a new node.

If you have a service that you would like to run on all nodes all the time, you should use `--mode=global` instead of the default `--mode=replicated`

**Comment by adrianovieira** [comment] 2016-07-07 15:57
Thanks @mavenugo and @cpuguy83 

@cpuguy83 I don't want `global service` for now.

May be you know how I could re-balance all running tasks on the cluster, don't you?

**Comment by thaJeztah** [comment] 2016-07-08 06:28
Thanks for your feedback @adrianovieira! It looks like this is a duplicate of https://github.com/docker/docker/issues/24103, so I'll close this one. Please subscribe to the linked issue to keep up to date on progress

I'll close this issue, but feel free to comment after I closed

**Closed by thaJeztah** 2016-07-08 06:28 UTC
