### ISSUE TITLE
Abilitiy to limit network bandwidth

### ISSUE THREAD

**Issue by edivya** [docker/docker#7182] opened 2014-07-23 11:29 UTC
How can I limit network bandwidth and disk I/O bandwidth in docker? I can see options for cpu and memory . I tried --lxc-conf command but not getting the desired results.

**Comment by jfrazelle** [comment] 2015-02-25 23:29
closing as duplicate of https://github.com/docker/docker/issues/4763

**Closed by jfrazelle** 2015-02-25 23:29 UTC
Labels: feature
