### ISSUE TITLE
Docker swarm mode -  No installed keys could decrypt the message

### ISSUE THREAD

**Issue by lpakula** [docker/docker#30590] opened 2017-01-31 13:01 UTC
**Description**

Docker swarm stop working with no apparent reason, and all docker containers within the same network can't see each other. 

**Steps to reproduce the issue:**
1. Create docker swarm cluster

**Describe the results you received:**
Docker swarm crashed with:
`` [ERR] memberlist: failed to receive: No installed keys could decrypt the message from=172.168.6.11:43799`` 

**Describe the results you expected:**
Docker swarm is stable and working without interruption

**Additional information you deem important (e.g. issue happens only occasionally):**
The cluster is build of 3 manager nodes and 2 worker nodes. I'm using hashicorp vault for managing secret and consul as a backend. I know consul was used as docker cluser manager before docker swarm mode, and the simillar error i can find in consul issue tracker, however that break entire swarm cluster and consul is running in a container just to serve backend for vault. I'm not sure if that may be related.

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 13
 Running: 13
 Paused: 0
 Stopped: 0
Images: 18
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-202:1-528295-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.654 GB
 Data Space Total: 107.4 GB
 Data Space Available: 33.65 GB
 Metadata Space Used: 12.24 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.135 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: active
 NodeID: a6ud78xyqy5y1ozjg97czakqt
 Is Manager: true
 ClusterID: 8o2s7fmvqz5nxka36l29t8kjw
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.168.5.11
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: manager-1
ID: DXLI:OO5Z:TW77:ISKZ:B2UH:QD6Z:LWMI:V5OI:LTUO:LD2Z:P3CG:WI5W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: atheon
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 node.type=manager
 node.access=private
 node.subnet=private1
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by aluzzardi** [comment] 2017-01-31 22:32
@mavenugo @sanimej There seems to be a problem with the network encryption keys rotation

**Comment by deuch** [comment] 2017-02-06 08:18
Same issue here with DDC :

UCP 2.0.2
DTR 2.1.4

Client:
 Version:      1.12.6-cs6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   712e864
 Built:        Wed Jan 11 00:10:32 2017
 OS/Arch:      linux/amd64

(I know it's a CS issue, but the opensource version has the same problem. A support ticket is already raised too)

3 Nodes controllers, and the cluster is KO.

A lot of this message on controllers (2 of them) every seconds :

docker[7811]: time="2017-02-06T08:42:43.989516242+01:00" level=warning msg="2017/02/06 08:42:43 [ERR] memberlist: Decrypt packet failed: No installed keys could decrypt the message from=node1:7946
docker[7811]: time="2017-02-06T08:42:43.989516242+01:00" level=warning msg="2017/02/06 08:42:43 [ERR] memberlist: Decrypt packet failed: No installed keys could decrypt the message from=node2:7946
docker[7811]: time="2017-02-06T08:42:43.989516242+01:00" level=warning msg="2017/02/06 08:42:43 [ERR] memberlist: Decrypt packet failed: No installed keys could decrypt the message from=node3:7946

Please fix it asap, because our prod environment still not usable every day !

**Comment by thinkhard-j-park** [comment] 2017-02-21 03:48
I encountered same issue from version 1.13.1
...
 2월 21 12:43:19 worker01 dockerd[1089]: time="2017-02-21T12:43:19.096581826+09:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=192.168.0.30:56006"
 2월 21 12:43:18 worker01 dockerd[1089]: time="2017-02-21T12:43:18.111254446+09:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=192.168.0.30:56004"
 2월 21 12:43:14 worker01 dockerd[1089]: time="2017-02-21T12:43:14.106128116+09:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=192.168.0.30:55996"
 2월 21 12:43:10 worker01 dockerd[1089]: time="2017-02-21T12:43:10.095728684+09:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=192.168.0.30:55988"
 2월 21 12:43:09 worker01 dockerd[1089]: time="2017-02-21T12:43:09+09:00" level=info msg="Firewalld running: false"
 2월 21 12:43:09 worker01 dockerd[1089]: time="2017-02-21T12:43:09+09:00" level=info msg="Firewalld running: false"
 2월 21 12:43:09 worker01 dockerd[1089]: time="2017-02-21T12:43:09+09:00" level=info msg="Firewalld running: false"
 2월 21 12:43:09 worker01 dockerd[1089]: time="2017-02-21T12:43:09+09:00" level=info msg="Firewalld running: false"
 2월 21 12:43:09 worker01 dockerd[1089]: time="2017-02-21T12:43:09+09:00" level=info msg="Firewalld running: false"
 2월 21 12:43:09 worker01 dockerd[1089]: time="2017-02-21T12:43:09+09:00" level=info msg="Firewalld running: false"
 2월 21 12:43:09 worker01 dockerd[1089]: time="2017-02-21T12:43:09.111379889+09:00" level=warning msg="memberlist: failed to receive: No installed keys could decrypt the message from=192.168.0.30:55984"
...

**Comment by sanimej** [comment] 2017-02-21 07:00
@lpakula @thinkhard-j-park [Fix for this](https://github.com/docker/docker/pull/31091) has been merged in the docker master and will also be included in 1.13.2. Root cause and the fix is explained [here](https://github.com/docker/swarmkit/pull/1954)

**Closed** 2017-02-21 07:00 UTC
Labels: area/networking, area/swarm, version/1.12

**Comment by thaJeztah** [comment] 2017-02-21 07:38
Fix was cherry picked through https://github.com/docker/docker/pull/31030

**Comment by StefanScherer** [comment] 2017-03-08 12:01
@thaJeztah I encountered the same problem with 17.03.0-ce on a Raspberry Pi swarm. Are there ARM binaries available, can't find any on https://master.dockerproject.org?

**Comment by thaJeztah** [comment] 2017-03-08 12:10
@StefanScherer armhf packages are available in the apt.dockerproject.org repo http://apt.dockerproject.org/repo/pool/main/d/docker-engine/.

IIRC, https://master.dockerproject.org only has client binaries for ARM

**Comment by StefanScherer** [comment] 2017-03-08 12:37
Thanks @thaJeztah I first tried the test.docker.com script on ARM, but then I only get the 17.03.0-ce-rc1. So this will work with the next release candidate. So I'll compile ARM deb from master manually.

**Comment by StefanScherer** [comment] 2017-03-16 18:03
I still got these warnings in manager log as I often destroyed my swarm to reset a demo environment with `docker swarm leave -f` on all nodes and then created the swarm again. It turned out that even after the leave of the manager the docker engine still was listening on port 7946 and after the `docker swarm init` on the same manager node the log showed me "Error in agentInit : failed to create memberlist: Failed to start TCP listener. Err: listen tcp 0.0.0.0:7946: bind: address already in use"

**Comment by thaJeztah** [comment] 2017-03-16 23:49
> after the leave of the manager the docker engine still was listening on port 7946 a

@StefanScherer could you open an issue for that?

**Comment by StefanScherer** [comment] 2017-03-17 07:59
I found a way to reproduce it and opened #31913
