### ISSUE TITLE
All volumes, containers and images gone after update to 1.12.6-5 on Fedora 25

### ISSUE THREAD

**Issue by kelly-ann** [docker/docker#30539] opened 2017-01-29 02:38 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
-->

All volumes, containers and images gone after update to 1.12.6-5 on Fedora 25

**Steps to reproduce the issue:**
1. Create docker containers
2. Run "docker ps" to see created containers
2. Run "sudo dnf update"
3. Run "docker ps" again and there will be no containers there.

**Describe the results you received:**
My containers and information were all gone.

**Describe the results you expected:**
My container should be either left in its normal state when updating or program should create an auto-backup.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

~]$ sudo docker version
[sudo] password for ka: 
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-5.git037a2f5.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      037a2f5/1.12.6
 Built:           Wed Jan 18 12:11:29 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-5.git037a2f5.fc25.x86_64
 Go version:      go1.7.4
 Git commit:      037a2f5/1.12.6
 Built:           Wed Jan 18 12:11:29 2017
 OS/Arch:         linux/amd64

```

**Output of `docker info`:**

```
~]$ sudo docker info
[sudo] password for ka: 
Containers: 23
 Running: 0
 Paused: 0
 Stopped: 23
Images: 10
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:1-1442068-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.743 GB
 Data Space Total: 107.4 GB
 Data Space Available: 32.96 GB
 Metadata Space Used: 7.68 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.136 (2016-11-05)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Security Options: seccomp selinux
Kernel Version: 4.9.3-200.fc25.x86_64
Operating System: Fedora 25 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 7.682 GiB
Name: skb
ID: C2KR:WBGS:7HVV:X2CG:ATL4:VFKW:XJMT:EOJL:EEI4:FW2R:DHZL:PEAD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 25 workstation/desktop version.  DNF repo used to install updates.

**Comment by thaJeztah** [comment] 2017-01-29 05:37
Try `docker ps -a`, and you'll see your containers are there, but stopped; see the output;
```
~]$ sudo docker info
[sudo] password for ka:
Containers: 23
Running: 0
Paused: 0
Stopped: 23
Images: 10
Server Version: 1.12.6
Storage Driver: devicemapper
...
```

I'll close this issue as it's not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-01-29 05:37 UTC
Labels: version/1.12

**Comment by kelly-ann** [comment] 2017-01-31 13:41
Thanks for the prompt response!  Got it working now.

**Comment by thaJeztah** [comment] 2017-01-31 15:46
Great! Good to hear 👍
