### ISSUE TITLE
docker daemon option for -g (--graph) is broken in fedora docker-engine-1.7.0 rpm

### ISSUE THREAD

**Issue by stayclassychicago** [docker/docker#14149] opened 2015-06-24 03:12 UTC
Description of problem:
Docker daemon does not properly start when using the graph option after installing Docker 1.7 via the docker-engine rpm:
```    docker -d --graph=/data/docker  #or docker -d -g /data/docker```

Pre- docker 1.7 fedora installations honored this graph option:
```  -g, --graph="/var/lib/docker"          Root of the Docker runtime```

I suspect the issue is related to the initialization script provided in the rpm.  The init script, /etc/rc.d/init.d/docker, appears to have hard-code paths to /var:
```
    pidfile="/var/run/$prog.pid"
    lockfile="/var/lock/subsys/$prog"
    logfile="/var/log/$prog"
```

`docker version`:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

`docker info`:
Containers: 0
Images: 96
Storage Driver: devicemapper
Pool Name: docker-253:6-134527811-pool
Pool Blocksize: 65.54 kB
Backing Filesystem: xfs
Data file: /dev/loop2
Metadata file: /dev/loop3
Data Space Used: 4.169 GB
Data Space Total: 107.4 GB
Data Space Available: 25.01 GB
Metadata Space Used: 5.517 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.142 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Data loop file: /data/docker/devicemapper/devicemapper/data
Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.85 (2014-04-10)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.3-200.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)
CPUs: 12
Total Memory: 23.54 GiB
Name: wings
ID: RCGH:CNY4:65CI:GGV6:5MOW:I45Z:Y6SL:NISA:JE3U:P4VH:LK4P:CJ4N

`uname -a`:
Linux wings.trading.imc.intra 3.16.3-200.fc20.x86_64 #1 SMP Wed Sep 17 22:34:21 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical

How reproducible:
consistently reproducible

Steps to Reproduce:
1. Install docker-engine rpm, as described in https://docs.docker.com/installation/fedora/
2. Set graph option along with option to export tcp socket for DOCKER_HOST
3. restart docker
```
# cat /etc/sysconfig/docker 
    other_args=" -g /data/docker -H tcp://0.0.0.0:2375"
# service docker restart
```

Actual Results:
- Docker runtime socket and other runtime files are in `/var`.  
- Docker fails to start when the docker host (`-H` or `--host`) is specified with only tcp; 
```
    Get http:///var/run/docker.sock/v1.19/info: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

Expected Results:
- Docker daemon starts and all runtime files, logs, etc are found in the path specified in `--graph` option

Workaround:
Add option for unix socket:
```-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock```

Additional Info:
Docker fails with fatal error message "No sockets found" when starting with options:
``` -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -H fd:// ```

Logs:
>Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
>time="2015-06-23T22:04:29.453646685-05:00" level=error msg="ServeAPI error: No sockets found"
>time="2015-06-23T22:04:29.453680622-05:00" level=warning msg="Running modprobe bridge nf_nat failed with message: , error: exit status 1"
>time="2015-06-23T22:04:29.547512332-05:00" level=fatal msg="Shutting down due to ServeAPI error: No sockets found"

**Comment by stayclassychicago** [comment] 2015-06-24 03:18
# docker version
>Client version: 1.7.0
>Client API version: 1.19
>Go version (client): go1.4.2
>Git commit (client): 0baf609
>OS/Arch (client): linux/amd64
>Server version: 1.7.0
>Server API version: 1.19
>Go version (server): go1.4.2
>Git commit (server): 0baf609
>OS/Arch (server): linux/amd64

# docker info
>Containers: 0
>Images: 96
>Storage Driver: devicemapper
> Pool Name: docker-253:6-134527811-pool
> Pool Blocksize: 65.54 kB
> Backing Filesystem: xfs
> Data file: /dev/loop2
> Metadata file: /dev/loop3
> Data Space Used: 4.169 GB
> Data Space Total: 107.4 GB
> Data Space Available: 25.01 GB
> Metadata Space Used: 5.517 MB
> Metadata Space Total: 2.147 GB
> Metadata Space Available: 2.142 GB
> Udev Sync Supported: true
> Deferred Removal Enabled: false
> Data loop file: /data/docker/devicemapper/devicemapper/data
> Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
> Library Version: 1.02.85 (2014-04-10)
>Execution Driver: native-0.2
>Logging Driver: json-file
>Kernel Version: 3.16.3-200.fc20.x86_64
>Operating System: Fedora 20 (Heisenbug)
>CPUs: 12
>Total Memory: 23.54 GiB
>Name: wings
>ID: RCGH:CNY4:65CI:GGV6:5MOW:I45Z:Y6SL:NISA:JE3U:P4VH:LK4P:CJ4N

See first comment for steps to reproduce issue, along with expected and received results

**Comment by stayclassychicago** [comment] 2015-06-25 14:50
Hi-
I updated the original description with the BUG REPORT INFORMATION template.

**Comment by lahuman** [comment] 2015-07-06 08:36
I also same situation.

`docker version` : 
```
[root@localhost n001]# docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

`docker info` :

```
[root@localhost n001]# docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:0-2362814-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 47.79 GB
 Metadata Space Used: 733.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.4-202.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 4
Total Memory: 3.659 GiB
Name: localhost.localdomain
ID: SWPB:PL5A:SRDV:HB3T:XB7G:W7FF:GTIL:NQNT:3ELD:JMP2:6OOQ:R227
```

`uname -a` :
```
[root@localhost n001]# uname -a
Linux localhost.localdomain 4.0.4-202.fc21.x86_64 #1 SMP Wed May 27 22:28:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

When I used 1.6.0 then, I changed `/etc/sysconfig/docker`.  It's working.
(I follow this - http://stackoverflow.com/questions/24309526/how-to-change-the-docker-image-installation-directory)

But this time(1.7.0), It's not working.

I waiting for answer.

Thanks for read, Have a nice day.

**Comment by bacoboy** [comment] 2015-07-09 19:59
None of the docker options work under docker 1.7 on centos7.
In docker 1.6 the systemd service file (`/usr/lib/systemd/system/docker.service`) had this

    EnvironmentFile=-/etc/sysconfig/docker
    EnvironmentFile=-/etc/sysconfig/docker-storage
    EnvironmentFile=-/etc/sysconfig/docker-network
    ExecStart=/usr/bin/docker -d $OPTIONS \
          $DOCKER_STORAGE_OPTIONS \
          $DOCKER_NETWORK_OPTIONS \
          $ADD_REGISTRY \
          $BLOCK_REGISTRY \
          $INSECURE_REGISTRY

The 1.7 version of docker-engine rpm has this:

    ExecStart=/usr/bin/docker -d -H fd://

There is no reference to the sysconfig files.

This has been mentioned and closed on other issues but most of the fixes are around ubuntu packages.  No word yet on a PR that fixes this for centos7 rpms.  They keep closing them as dupes, but the problem is not solved yet AFAIK.

Such as:
#14323, #14319, #14130, #13923

**Comment by lahuman** [comment] 2015-07-10 03:53
Thank you! It's very helpful!

**Comment by abierbaum** [comment] 2015-07-10 17:32
@bacoboy Thanks.  This is hitting us as well.

**Comment by bacoboy** [comment] 2015-07-11 03:41
@abierbaum please jump in on the conversation about the PR #14513.  There is lots of pushback and I don't understand why.  I'm not sure what I'm missing, but I need more people to chime in who need this.

Thanks!

**Comment by peterpakos** [comment] 2015-07-16 19:13
I also have been hit by this issue on both Docker 1.7.0 and 1.7.1 under Centos 7.

It would be good to have this fixed in the next release.

**Comment by thaJeztah** [comment] 2015-08-15 22:41
The recommended way of customizing systemd options is to use drop-in files. This has now been added to the documentation; https://docs.docker.com/articles/systemd/#custom-docker-daemon-options

I'm closing this issue, because we won't be changing the default service file, but you should be able to achieve this using the instructions in the documentation.

Feel free to comment here after I closed this issue.

**Closed by thaJeztah** 2015-08-15 22:41 UTC

**Comment by bacoboy** [comment] 2015-08-16 20:28
Now THAT documentation makes sense.  Thanks!

**Comment by stayclassychicago** [comment] 2015-08-20 14:02
Documentation is helpful -- but can you please clarify a few things:

A) Is the suggested recommended for custom daemon options to use a native systemd service file with drop-in files -OR- use the INIT file provided in the docker-engine installation (`/etc/rc.d/init.d/docker`  ) ?

I'm not sure if the Systemd service file (docker.service) approach conflicts with the SysV init scripts, or if they can/should be used together?  Apologies for my linux/systemd ignorance, hope this makes sense.

B) Does the docker-engine installation provide a service file?
>I'm closing this issue, because we won't be changing the default service file, but you should be able to achieve this using the instructions in the documentation.

Specifically the Fedora 20 docker-engine RPM provides the INIT file  `/etc/rc.d/init.d/docker`.  However I didn't find a service file:

``` 
> rpm -ql docker-engine

/etc/rc.d/init.d/docker
/etc/sysconfig/docker
/etc/udev/rules.d/80-docker.rules
/usr/bin/docker
/usr/libexec/docker/dockerinit
/usr/share/bash-completion/completions/docker
/usr/share/fish/completions/docker.fish
/usr/share/man/man1/docker-attach.1.gz
/usr/share/man/man1/docker-build.1.gz
/usr/share/man/man1/docker-commit.1.gz
/usr/share/man/man1/docker-cp.1.gz
/usr/share/man/man1/docker-create.1.gz
/usr/share/man/man1/docker-diff.1.gz
/usr/share/man/man1/docker-events.1.gz
/usr/share/man/man1/docker-exec.1.gz
/usr/share/man/man1/docker-export.1.gz
/usr/share/man/man1/docker-history.1.gz
/usr/share/man/man1/docker-images.1.gz
/usr/share/man/man1/docker-import.1.gz
/usr/share/man/man1/docker-info.1.gz
/usr/share/man/man1/docker-inspect.1.gz
/usr/share/man/man1/docker-kill.1.gz
/usr/share/man/man1/docker-load.1.gz
/usr/share/man/man1/docker-login.1.gz
/usr/share/man/man1/docker-logout.1.gz
/usr/share/man/man1/docker-logs.1.gz
/usr/share/man/man1/docker-pause.1.gz
/usr/share/man/man1/docker-port.1.gz
/usr/share/man/man1/docker-ps.1.gz
/usr/share/man/man1/docker-pull.1.gz
/usr/share/man/man1/docker-push.1.gz
/usr/share/man/man1/docker-rename.1.gz
/usr/share/man/man1/docker-restart.1.gz
/usr/share/man/man1/docker-rm.1.gz
/usr/share/man/man1/docker-rmi.1.gz
/usr/share/man/man1/docker-run.1.gz
/usr/share/man/man1/docker-save.1.gz
/usr/share/man/man1/docker-search.1.gz
/usr/share/man/man1/docker-start.1.gz
/usr/share/man/man1/docker-stats.1.gz
/usr/share/man/man1/docker-stop.1.gz
/usr/share/man/man1/docker-tag.1.gz
/usr/share/man/man1/docker-top.1.gz
/usr/share/man/man1/docker-unpause.1.gz
/usr/share/man/man1/docker-version.1.gz
/usr/share/man/man1/docker-wait.1.gz
/usr/share/man/man1/docker.1.gz
/usr/share/man/man5/Dockerfile.5.gz
/usr/share/nano/Dockerfile.nanorc
/usr/share/vim/vimfiles/doc/dockerfile.txt
/usr/share/vim/vimfiles/ftdetect/dockerfile.vim
/usr/share/vim/vimfiles/syntax/dockerfile.vim
/usr/share/zsh/vendor-completions/_docker
```

**Comment by thaJeztah** [comment] 2015-08-20 20:53
@stayclassychicago good questions, I'm actually looking in the specs used to build the RPMs and this looks to indicate that RPM does not assume systemD on fedora 20 RPMs; https://github.com/docker/docker/blob/master/hack/make/.build-rpm/docker-engine.spec#L20
