### ISSUE TITLE
got "invalid tar header" error when I use docker remote API to load tar image file to docker 

### ISSUE THREAD

**Issue by JennyHuang8** [docker/docker#22002] opened 2016-04-13 15:58 UTC
docker version:
Docker version 1.8.2, build 0a8c2e3

Output for docker info:
Containers: 12
Images: 438
Storage Driver: devicemapper
 Pool Name: docker-8:3-2323415-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.829 GB
 Data Space Total: 107.4 GB
 Data Space Available: 18.05 GB
 Metadata Space Used: 23.73 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.124 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.703 GiB
Name: set5node1.internal.acp.arris.com
ID: PRTY:IGFL:2FNB:MEVB:NFHC:IAJP:ICIK:LS5A:QMWD:FFLE:7P65:IYHT

Steps to reproduce the issue:
1. run the following curl command:
curl  -v -X POST -H -i "http://localhost:4243/images/load" -d @arrs-acptestapp-b-1.0.5.tar

I got "invalid tar header" error in the result:

* About to connect() to localhost port 4243 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4243 (#0)
> POST /images/load HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:4243
> Accept: */*
> Content-Length: 101268586
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Server: Docker/1.8.2 (linux)
< Date: Wed, 13 Apr 2016 15:16:20 GMT
< Content-Length: 76
< Connection: close
< 
Untar re-exec error: exit status 1: output: archive/tar: invalid tar header
* we are done reading and this is set to close, stop send
* Closing connection 0

I can successfully run "tar tvf" on this tar file, run command "docker load -i arrs-acptestapp-b-1.0.5.tar" and "docker load < arrs-acptestapp-b-1.0.5.tar", they all success.

Is anything wrong with my curl command?

**Comment by HackToday** [comment] 2016-04-14 00:45
For curl, i think here tar should use this format
```
curl -v --request POST  "http://127.0.0.1:2375/images/load"  **--data-binary**  @my.tar 
```

**Comment by thaJeztah** [comment] 2016-04-14 22:51
@JennyHuang8 can you try with the command that @HackToday gave you? Also, I strongly advise you to upgrade to at least docker 1.8.3, which contains a fix for image layers.

I'll close this issue, because this is not a bug, but a question on how to use Docker. But feel free to continue the discussion

**Closed by thaJeztah** 2016-04-14 22:51 UTC

**Comment by Abdul-Rehman-yousaf** [comment] 2017-07-26 12:31
I'm trying to build a docker image from tar archive which include dockerfile using docker api python client.
Build as: `client.images.build(fileobj=deployment.archive, custom_context=True, tag='deployment', encoding='gzip')` 

But getting Invalid tar header apierror as:

> Request Method:	POST
Request URL:	http://127.0.0.1:8000/user/deployment/new/awd
Django Version:	1.11.3
Exception Type:	APIError
Exception Value:	
500 Server Error: Internal Server Error ("archive/tar: invalid tar header")
Exception Location:	/Users/abdul/IstioVirEnv/lib/python3.6/site-packages/docker/errors.py in create_api_error_from_http_exception, line 31
Python Executable:	/Users/abdul/IstioVirEnv/bin/python
Python Version:	3.6.1
