### ISSUE TITLE
docker info is using port 2375 although the DOCKER_HOST is explicitly forcing another port

### ISSUE THREAD

**Issue by mdelapenya** [docker/docker#31288] opened 2017-02-23 12:28 UTC
**Description**
When setting a remote docker host, where the default docker port is changed from 2375 to 3375 is not displaying the information of the remote servers. The remote host is running a container from swarm image, exposing container's 2375 port to host's 3375 port.

The `docker info` command is not able to connect to the different remote node. In this case, there is a swarm cluster, and none of the manager nodes are recognized by `docker info`.

**Steps to reproduce the issue:**
1. Configure client to the remote server: `export DOCKER_HOST=this.is.my.ip:3375`, where this.is.my.ip represents the IP address of the docker host that contains the leader of Docker Swarm managers
2. execute `docker info`

**Describe the results you received:**
The remote swarm nodes ARE NOT connected and their containers, CPU, Labels, etc ARE NOT retrieved and displayed.

**Describe the results you expected:**
The remote swarm nodes ARE connected and their containers, CPU, Labels, etc ARE retrieved and displayed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.24 (downgraded from 1.26)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.2.6
 API version:  1.22 (minimum version )
 Go version:   go1.7.1
 Git commit:   `git rev-parse --short HEAD`
 Built:        `date -u`
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: swarm/1.2.6
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint, whitelist
Nodes: 3
 (unknown): manager1:2375
  └ ID:
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels:
  └ Error: Cannot connect to the Docker daemon at tcp://manager1:2375. Is the docker daemon running?
  └ UpdatedAt: 2017-02-23T11:41:30Z
  └ ServerVersion:
 (unknown): manager2:2375
  └ ID:
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels:
  └ Error: Cannot connect to the Docker daemon at tcp://manager2:2375. Is the docker daemon running?
  └ UpdatedAt: 2017-02-23T11:41:30Z
  └ ServerVersion:
 (unknown): manager3:2375
  └ ID:
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels:
  └ Error: Cannot connect to the Docker daemon at tcp://manager3:2375. Is the docker daemon running?
  └ UpdatedAt: 2017-02-23T11:41:30Z
  └ ServerVersion:
Plugins:
 Volume:
 Network:
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Kernel Version: 3.16.0-4-amd64
Operating System: linux
Architecture: amd64
CPUs: 0
Total Memory: 0 B
Name: swarm-mgr1
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
Experimental: false
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
My docker client is a "Docker for Mac" client, but it also happens in a Debian 8 machine, with docker 1.13.1.

**Comment by mdelapenya** [comment] 2017-02-23 12:30
Related to https://github.com/docker/docker/issues/31287

**Comment by thaJeztah** [comment] 2017-02-23 13:13
I'm not able to reproduce this (using docker for mac 1.13.1);

```bash
bash-4.3$ export DOCKER_HOST=127.0.0.1:3375
bash-4.3$ docker info
Cannot connect to the Docker daemon at tcp://127.0.0.1:3375. Is the docker daemon running?
```

Is it possible you have created an alias for docker? For example;

```bash
bash-4.3$ alias docker="docker -H unix:///var/run/docker.sock"
bash-4.3$ export DOCKER_HOST=127.0.0.1:3375
bash-4.3$ docker info
Containers: 18
 Running: 8
 Paused: 0
 Stopped: 10
Images: 286
...
```

You can find if an alias is set using the `type` command;

```bash
bash-4.3$ type docker
docker is aliased to `docker -H unix:///var/run/docker.sock'
```

**Comment by mdelapenya** [comment] 2017-02-23 13:23
No, there is no alias for docker.

**Comment by thaJeztah** [comment] 2017-02-23 13:43
Actually, reading your issue again; the problem is not that the _client_ does not connect to the daemon (in your case `swarm`), but the `swarm` daemon not connecting to the nodes; the `DOCKER_HOST` environment variable only tells the client which host/port to use to connect to the remote API of the swarm daemon.

The _manager_ on it's hand, connects to each node with the address and port that was used to _join_ the cluster; see https://docs.docker.com/swarm/reference/join/. If a node joined the cluster (`swarm join`) with `this.is.my.ip:2375`, that configuration is stored in the discovery backend, and will be used by the swarm daemon.

**Comment by mdelapenya** [comment] 2017-02-23 13:45
I'm looking at that right now. Seems that my swarm nodes are not exposing 2375 port to their docker host, so as you said, seems related to how the nodes joined the swarm.

Please let me check it until closing the issue :)

Thanks for your help!

**Comment by thaJeztah** [comment] 2017-02-23 13:50
You're welcome! Let me know how it goes 👍

**Comment by thaJeztah** [comment] 2017-03-08 18:50
@mdelapenya I'll go ahead and close this issue, but feel free to comment

**Closed by thaJeztah** 2017-03-08 18:50 UTC
Labels: area/swarm, platform/desktop, status/more-info-needed
