### ISSUE TITLE
Unknown Runtime Specified Error when bringing up `docker-compose`

### ISSUE THREAD

**Issue by hahuang65** [docker/docker#24354] opened 2016-07-06 00:45 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:09:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   876f3a7
 Built:        Tue Jul  5 02:20:13 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 19
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 79
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.14-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: XOQD:TGSC:WT3Y:DPUJ:OLY6:ADSL:YWUS:6YTA:Y25W:CW4D:33HQ:DOHK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2016-07-06T00:43:44.933318158Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a `docker-compose.yml` file:
```
version: '2'
services:
  postgres:
    image: postgres:9.5
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
```
2. Run `docker-compose up`

**Describe the results you received:**
```
Starting tome_postgres_1

ERROR: for postgres  Unknown runtime specified default
ERROR: Encountered errors while bringing up the project.
```

**Describe the results you expected:**
Used to bring up the corresponding container/volume correctly in the last beta version.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by hahuang65** [comment] 2016-07-06 00:48
Once I did a `docker-compose up --force-recreate` it worked.
It still gave the error of
```
postgres_1  | jack is incompatible with use of CloseNotifier in same ServeHTTP call
``` 
But I suppose that's a separate issue.

**Comment by thaJeztah** [comment] 2016-07-06 08:32
This is a duplicate of https://github.com/docker/docker/issues/24343, please read that issue for more information. The "jack incompatible" issue is being tracked in https://github.com/docker/compose/issues/3685.

Closing this issue per https://github.com/docker/docker/issues/24343#issuecomment-230623542

**Closed by thaJeztah** 2016-07-06 08:32 UTC
Labels: version/1.12
