### ISSUE TITLE
Feature request: multiple compose files in docker stack deploy

### ISSUE THREAD

**Issue by andrewmilson** [docker/docker#31267] opened 2017-02-22 22:04 UTC
Would be nice to specify multiple docker compose files in a docker stack deploy. https://docs.docker.com/compose/production/#/modify-your-compose-file-for-production.

docker stack deploy -c docker-compose.yml -c production.yml newdeployment

**Comment by vingrad** [comment] 2017-02-22 22:36
+1

**Comment by yongtang** [comment] 2017-02-22 23:13
I think this issue might be a duplicate of #30504?

**Comment by thaJeztah** [comment] 2017-02-23 08:45
Yes this looks like a duplicate. let me close this one

**Closed by thaJeztah** 2017-02-23 08:45 UTC

**Comment by thanhson1085** [comment] 2017-04-18 08:01
+1
