### ISSUE TITLE
changed image ids when using registry v2

### ISSUE THREAD

**Issue by evlewt** [docker/docker#18179] opened 2015-11-24 00:37 UTC
Hi,

i updated my docker registry from v1 to v2 and noticed that the id of a pulled image is not the same as the source image. Using a registry v1 the id was always the same.
I tested it with two clean virtual machines and got the same results.

As i used the image ids to check if a newer image is available at my docker registry it would really great to know the reason why this was changed.

`docker version`:
<pre>
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
</pre>

`docker info`:
<pre>
Containers: 1
Images: 15
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 1.469 GiB
Name: vm-docker-server
</pre>

`uname -a`:
<pre>
Linux vm-docker-server 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
</pre>

Environment details (AWS, VirtualBox, physical, etc.):
- registry always a docker container
- client vm or native os

How reproducible:
Push an image to a v2 registry and pull at another client.

Steps to Reproduce:
I can support the script that i used in the virtual machines for testing.

Actual Results:
root@vm-docker-server:~/docker# docker images
<pre>
REPOSITORY                              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
myname/testimage                        latest              e23425232690        6 minutes ago       263.9 MB
127.0.0.1:5000/myname/testimage         latest              e23425232690        6 minutes ago       263.9 MB
registry
</pre>

root@vm-docker-client:~/docker# docker images
<pre>
REPOSITORY                                            TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker.mydomain.net:5000/myname/testimage             latest              8d5707405f97        7 minutes ago       263.9 MB
</pre>

Expected Results:
same "IMAGE ID"

Additional info:
The image id from the manifest is the same as the original image id.
wget --no-check-certificate --output-document=- https://docker.mydomain.net/v2/myname/testimage/manifests/latest | grep -m 1 'v1Compatibility'

The image ids of a docker history ... begin to differ at the point the testimage is customized.
[error_history.txt](https://github.com/docker/docker/files/42232/error_history.txt)

**Comment by amancevice** [comment] 2015-11-24 14:15
I'm having a similar issue, but I suspect it has something to do with Docker 1.9 vs 1.8, and not the registry. If you pull the image with Docker 1.8 do you get the expected ID?

**Comment by evlewt** [comment] 2015-11-24 20:23
You are right. The problem is the version of Docker that pulls the image. The image ID keeps the same using 1.8.2. I am using the repository "https://apt.dockerproject.org/repo debian-jessie main".
Every version since 1.8.2 (1.8.3, 1.9.0, 1.9.1) changes the image ID at the client.

**Comment by amancevice** [comment] 2015-11-24 20:36
This issue is especially odd when pulling tags that refer to the same image. For example, say `"latest"` is a synonym for `"5.4.3"`, I get two different IMAGE ID values when I pull:
```bash
docker pull myhost:5000/myimage:latest

# vs.

docker pull myhost:5000/myimage:5.4.3
```

**Comment by thaJeztah** [comment] 2015-11-24 21:24
This looks like a duplicate of https://github.com/docker/docker/issues/17749, could you check that issue (just to be sure) and close this one, so that we have the discussion in a single location? Thanks!

**Comment by evlewt** [comment] 2015-11-24 22:59
It seems to be a duplicate. At least the reason my problem is based on.

As tonistiigi wrote in the comment https://github.com/docker/docker/issues/17749#issuecomment-159008126 that after v1.8.3 a checksum based ID is used. Does he mead the image digests?
When i use docker images --digests=true i always get <none> in the digest field. And the sha256-digest shown after the push- and pull commands is also not available at "https://docker.mydomain.net:5000/v2/_catalog" or "https://docker.mydomain.net:5000/v2/myname/testimage/manifests/latest".

I need to check at a client if a newer version of a local image is available at my registry. Up to v1.8.2 i could use the local image ID and the ID from the v1Compatibility part of the manifest.

Is there a official way to notice that an update is available?

I read the changelog at https://github.com/docker/docker/blob/master/CHANGELOG.md but did not found and notice about the change of calculating the image ID. Is there another more detailed chanlog available?

**Comment by thaJeztah** [comment] 2015-11-24 23:13
I don't think there's an official way to detect if a newer image is available, apart from performing a "pull". (For Docker Hub, web hooks can be used https://docs.docker.com/docker-hub/webhooks/)

**Comment by thaJeztah** [comment] 2016-04-15 22:47
https://github.com/docker/docker/pull/17924 Was merged, so I'm closing this

**Closed by thaJeztah** 2016-04-15 22:47 UTC
