### ISSUE TITLE
exec: "/bin/sh": stat /bin/sh: no such file or directory

### ISSUE THREAD

**Issue by ConradIrwin** [docker/docker#5135] opened 2014-04-10 01:33 UTC
Since upgrading to 0.10 I see this error during build processes.

I'm not sure exactly what causes it, it always happens at the same point in a given Dockerfile, but I can't see the correlation between the failures in different Dockerfiles.

It may be to do with the depth of the aufs tree, as it only seems to happen on long dockerfiles.

**Comment by jfrazelle** [comment] 2015-01-14 21:53
I believe this is no longer an issue, or a misunderstand? is that true?

**Comment by omribahumi** [comment] 2015-01-19 17:13
Just got it:
```
# docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
# uname -a
Linux hostname.domain 3.8.0-44-generic #66~precise1-Ubuntu SMP Tue Jul 15 04:01:04 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.4 LTS"
```

It worked before. I have no idea what caused it to start breaking.

**Comment by sametmax** [comment] 2015-02-06 15:40
Still an issue for me. Got that today on an up to date Ubuntu 14.04 running : 

```
docker run -t -i 74fe38d11401 bash
2015/02/06 15:37:44 exec: "bash": executable file not found in $PATH
```

**Comment by cpuguy83** [comment] 2015-02-06 15:42
@sametmax `/bin/bash`

**Comment by sametmax** [comment] 2015-02-06 15:44
Same.

**Comment by sametmax** [comment] 2015-02-06 15:46
Eventually deleted all images and container, and now it works with a
fresh new one. It's on my dev machine, so it's ok. But for people with
containers in prod...

**Comment by mipearson** [comment] 2015-05-15 01:55
Just got bitten by this. "Docker will fail if you do too many things with docker" is not expected behaviour, is not documented except in this github issue.

What are the changes of getting docker to _warn_ if you start adding too many layers?

**Comment by blackibiza** [comment] 2015-05-31 11:30
I'm getting the same error with docker 1.6 and Ubuntu-Core armhf 15.04 image imported from a tar.gz file. Any kind of command fails with "no such file or directory" even if the files are all there

**Comment by martingartonft** [comment] 2015-07-09 15:53
We are seeing these symptoms too. I've tried reducing the number of layers but it doesn't solve the issue.
We're using the overlay driver on CoreOS fwiw.

**Comment by crosbymichael** [comment] 2015-07-10 17:55
I'm going to close this issue but please open a new one if you hit this issue with steps to reproduce and information.  Just saying that you encountered this is not going to help anyone fixing the problem.  We need to have the image/Dockerfile, etc, and your system information.  

This issue has become a catchall and there are not really any useful information in here to solve the problem.  So if you still have this problem, please open a new issue with all the information that you can.  if you cannot share the information like the image publicly you can email me personally and I can take a look at it.

**Closed by crosbymichael** 2015-07-10 17:55 UTC
Labels: exp/expert, kind/bug

**Comment by math3usmartins** [comment] 2015-07-22 05:07
**Dockerfile**
```
FROM node:0.12.7
EXPOSE 8080 443
RUN apt-get update
RUN apt-get install -y net-tools
RUN apt-get install -y git
RUN npm install -g pm2
CMD ["/bin/bash"]
```

**Save and import image works, but `docker run` fails:**
```
[ok] docker build myimage
[ok] docker save --output="myimage" myimage
[ok] docker rmi myimage
[ok] cat myimage.tar | docker import - myimage
[fail] docker run -tid --name myimagecontainer myimage 
exec: "/bin/sh": stat /bin/sh: no such file or directory
Error response from daemon: Cannot start container 017cec2fb...
[8] System error: exec: "/bin/sh": stat /bin/sh: no such file or directory
```

I've also tried `docker import --change "CMD ..."  - myimage` and `docker run -ti` (without -d). No success.

PS. I've adjusted the container ID in the error message above just to improve readability; the error message contains the full ID.

**Comment by thaJeztah** [comment] 2015-07-22 07:06
@math3usmartins you're combining `docker save` with `docker import`, which doesn't work. Either use `docker save` and `docker load` or `docker export` and `docker import`, depending what your goal is. See http://docs.docker.com/reference/commandline/save/ and http://docs.docker.com/reference/commandline/export/

**Comment by math3usmartins** [comment] 2015-07-22 11:42
thanks a lot @thaJeztah

**Comment by prashantabkari** [comment] 2015-11-11 05:36
I am facing the same problem when i try to create a base image from scratch
Following is the dockerfile
FROM scratch
ADD a.out /home/abkari/docker_file/server_docker/server.o
CMD ["/bin/bash"]

On running the container with the above image i get the following error
Error response from daemon: Cannot start container 29891a11a5915a3c81d9a3c4800c8a1b33ea32fad00da2335ece69e3dd856458: [8] System error: exec: "/bin/bash": stat /bin/bash: no such file or directory

**Comment by tcurdt** [comment] 2015-11-11 08:24
@prashantabkari it's not a real problem - read the above comments.
With that dockerfile that's expected - there is no shell in that empty image.

**Comment by colemickens** [comment] 2016-12-28 17:39
Is it expected that:

`CMD /static-binary` in my Dockerfile results in `CMD ["/bin/sh", "-c", "/static-binary"]` in the actual image?

In case anyone else is having issues, try specifically specifying `CMD ["/static-binary"]` in a scratch image.

Is this behavior documented?

**Comment by thaJeztah** [comment] 2016-12-28 17:41
@colemickens yes, see https://docs.docker.com/engine/reference/builder/#/exec-form-entrypoint-example

**Comment by david-vega** [comment] 2017-03-03 03:58
I just had this issue with the latest Docker version on a clean install of ubuntu-gnome 16.10, the reason was that `docker-compose` didn't like the `volumes:` definition on the `docker-compose.yml` file
```
volumes:
   - .:/data/app
```
My workaround was to delete that, as a side note I use the same files on my mac an they work perfectly fine. anyways leaving this comment if someone faces the same issue.

**Comment by fiantsev** [comment] 2018-11-28 09:55
guys, this error may be related to corrupted images (in my case there was shutdown of a build machine during build process). Subsequent attempt to build lead to this problem. So i fixed this by removing all images (including hidden ones) because i cant rely of them anymore. My save-day command was:
```
docker rmi -f $(docker images -aq)
```
**!!! be careful - it will remove all your images !!!**

**Comment by cowlinator** [comment] 2018-12-14 20:45
I am getting this error with the unmodified "hello-world" image:

```
$ docker run -it hello-world /bin/sh
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
d1725b59e92d: Pull complete
Digest: sha256:0add3ace90ecb4adbf7777e9aacf18357296e799f81cabc9fde470971e499788
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown.
```

**Comment by thaJeztah** [comment] 2018-12-14 20:53
@cowlinator the hello-world image is an image that's created "from scratch"; there's nothing in that image other than a single binary, so no `/bin/sh`.  https://github.com/docker-library/hello-world/blob/master/amd64/hello-world/Dockerfile


> and docker inspect hello-world reveals that the "Cmd" is indeed /bin/sh.

I think that may be a presentation issue; the image uses [the "exec-form"](https://docs.docker.com/engine/reference/builder/#cmd) for the `Cmd`;

```
CMD ["/hello"]
```

But the `docker inspect` may prepend the default entry point (`/bin/sh`) even though it's not used f the `Cmd` is using the exec-form 🤔 

Might be worth opening an new issue for that, so that we can discuss if that presentation can be changed
