### ISSUE TITLE
Cannot attach to a running container on Fedora 23

### ISSUE THREAD

**Issue by vfreex** [docker/docker#18823] opened 2015-12-21 11:16 UTC
Hi, I'm running Docker on my Fedora 23 laptop. Every time I run `docker attach` it hangs until I type something.
If I kill the running container and run `docker start -a`, I will get to the shell, but I will be unable to use arrow  keys and <kbd>Enter</kbd>.

Steps to reproduce:

``` bash
$ docker run -ti debian:8 /bin/bash
root@7bcaca9423f9:/# echo 'I can use the shell.'
I can use the shell.
root@7bcaca9423f9:/# (CTRL+P,Q)
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
7bcaca9423f9        debian:8            "/bin/bash"         37 seconds ago      Up 36 seconds                           jolly_wescoff

$ docker attach 7bcaca9423f95e4a40f58e90f180146602443d92350ff1706c15785bede91a29
# will hang forever
# (Press any key)
root@7bcaca9423f9:/# echo 'Then I get to the shell again'
Then I get to the shell again
root@7bcaca9423f9:/# exit

# restart
$ docker start 7bcaca9423f95e4a40f58e90f180146602443d92350ff1706c15785bede91a29 
7bcaca9423f95e4a40f58e90f180146602443d92350ff1706c15785bede91a29
$ docker attach 7bcaca9423f95e4a40f58e90f180146602443d92350ff1706c15785bede91a29
# still hang
# (Press any key)
root@7bcaca9423f9:/# echo 'It recovered.'
It recovered.
root@7bcaca9423f9:/# exit

# run `docker start -a`
$ docker start -a 7bcaca9423f95e4a40f58e90f180146602443d92350ff1706c15785bede91a29 
root@7bcaca9423f9:/# 
# cannot do anything because my Enter key is not working
```

My environment:

```
$ docker -v
Docker version 1.9.1, build a34a1d5

$ uname -a
Linux localhost.localdomain 4.2.7-300.fc23.x86_64 #1 SMP Wed Dec 9 22:28:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I tried the same operations on my friends' Fedora 23 computer, this issue can be reproduced.

**Comment by thaJeztah** [comment] 2015-12-21 13:22
Hi @vfreex, this looks to be a duplicate of https://github.com/docker/docker/issues/8521. That discussion also contains some information about "why".

I'll close this issue because it's a duplicate of https://github.com/docker/docker/issues/8521. Please subscribe to that issue to stay informed on updates. Feel free to comment here after I've closed this issue :+1:

**Closed by thaJeztah** 2015-12-21 13:22 UTC
