### ISSUE TITLE
"Unable to find user"

### ISSUE THREAD

**Issue by frioux** [docker/docker#12514] opened 2015-04-18 22:09 UTC
As far as I can tell you cannot pass a username, only a UID, even though --user is documented to work with a username:

```
$ whoami
frew
$ docker run --user frew frew/corn
Unable to find user frew
FATA[0000] Error response from daemon: Cannot start container 2b5f6b81c693364d39037868a1032244eab815968d1c4398d18fedfed98f245f: [8] System error: Unable to find user frew
```

**Comment by 3onyc** [comment] 2015-04-18 22:19
Works fine:
```
% docker run -it --user nobody --rm ubuntu:14.04 /bin/bash
nobody@23b2ae0d34a4:/$
```

Keep in mind that the user needs to exist in the docker image, host users won't work.

**Comment by frioux** [comment] 2015-04-18 22:55
Ah ok, I couldn't tell that from the docs, maybe I'll submit a patch to
clarify

-- 
sent from a rotary phone, pardon my brevity

**Comment by thaJeztah** [comment] 2015-04-18 23:17
@frioux I'm going to close this issue, because I think your question is answered. If you think the documentation can be improved, we welcome your pull request! Thanks in advance :)

**Closed by thaJeztah** 2015-04-18 23:17 UTC

**Comment by gflarity** [comment] 2015-11-15 17:14
I can reproduce this issue. It works for nobody, but it doesn't work when I created a user called 'dockroot'.

This works: 

```
docker -it -u nobody busybox sh
```

this works:
```
docker -it -u 1002 busybox sh
```

This does *not* work:
```
docker  -it -u dockroot busybox sh
```
Note that dockroot is userid 1002. So this should work? Not sure what makes nobody special. 

Here's the work around I'm going to use for now:

```
docker run -u `id -u dockroot` -it busybox sh
```

**Comment by LK4D4** [comment] 2015-11-15 17:17
@gflarity 
```
root:x:0:0:root:/root:/bin/sh
daemon:x:1:1:daemon:/usr/sbin:/bin/false
bin:x:2:2:bin:/bin:/bin/false
sys:x:3:3:sys:/dev:/bin/false
sync:x:4:100:sync:/bin:/bin/sync
mail:x:8:8:mail:/var/spool/mail:/bin/false
www-data:x:33:33:www-data:/var/www:/bin/false
operator:x:37:37:Operator:/var:/bin/false
ftp:x:83:83:ftp:/home/ftp:/bin/false
nobody:x:99:99:nobody:/home:/bin/false
```
There is no `dockroot` user in busybox, that's why it doesn't work.

**Comment by gflarity** [comment] 2015-11-15 18:25
Thanks @LK4D4

The reason I was confused is that -u 1002 works even though the user isn't even in there. I created the user on my host, then if I do a ps -ef | grep on the host i see the container process is owned by dockroot:
```
dockroot  3520  3504  0 18:18 pts/2    00:00:00 sleep 100
```

However, inside the actual container : 
```
/ $ whoami
whoami: unknown uid 1002
```

**Comment by thaJeztah** [comment] 2015-11-15 22:55
@gflarity the process just runs under id 1002. Linux doesn't actually care about the names, just the uid/gid (numeric). When running `ps`, your host is looking up the `uid` inside `/etc/passwd` on the *host* (not inside the container), and shows `dockroot`, which probably is inside that file.

**Comment by Soullivaneuh** [comment] 2015-12-07 07:07
> Keep in mind that the user needs to exist in the docker image, host users won't work.

@3onyc And what is the best way to do that?

I would like to sync file creation owner with the used system username to avoid right conflict. Do you have tips for that? Of course, this project will be run on different computers with different usernames.

**Comment by Soullivaneuh** [comment] 2015-12-07 07:09
I think I find a solution but not sure it's the proper way:

```yml
web:
  build: .
  user: sullivan
  command: php app/console server:run 0.0.0.0:9000
  links:
    - mysql
    - solr
    - redis
  ports:
    - '9000:9000'
  volumes:
    - .:/code
    - /etc/passwd:/etc/passwd
```

Basically, I synced my host `/etc/passwd` with the docker container `/etc/passwd` file.

Is that correct? Not risky?

**Comment by 3onyc** [comment] 2015-12-07 15:09
@Soullivaneuh Use the `useradd` command in your Dockerfile to create the user

**Comment by thaJeztah** [comment] 2015-12-07 16:18
@Soullivaneuh indeed, you need to add that user in your Dockerfile if you want to reference the user by name. Using numeric ids will work, even if no user is created prior.

I'd be careful bind-mounting `/etc/passwd` in your container, because by doing so, you're granting the processes in the container access to that file and modifying it. If you *really* want to do that, I'd suggest to mount it read-only, i.e. `/etc/passwd:/etc/passwd:ro`

**Comment by Soullivaneuh** [comment] 2015-12-08 09:31
The fact is, I want to have dynamic users in order to use same user as the host, that could be different between workstations (sullivan, brandon, jerome...).

I have to confess, I'm completely stuck. What is the best way?

> Use the useradd command in your Dockerfile to create the user

@3onyc Ok, but how to passes dynamic variable inside this Dockerfile?
