### ISSUE TITLE
Windows docker mount volume not work if path contains "conf.d"

### ISSUE THREAD

**Issue by sunhaolin** [docker/docker#18935] opened 2015-12-28 10:01 UTC
docker version: 1.9.1

docker info:
Containers: 1
Images: 28
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: 3DU4:VMID:KWRR:B2HN:N6VY:PWEV:YQPS:2VDX:2XKX:UI65:4N2N:6XSG
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 37
 System Time: 2015-12-28T10:06:01.592445021Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

uname -a:
MINGW64_NT-10.0 DESKTOP-DMMVIGQ 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys

steps :
1. docker run -p 888:80 -it -v //g/src/docker/rainloop/conf/rainloop.conf:/etc/nginx/conf.d/rainloop.conf --name nginxtest nginx
2.it raise exption:
[crit] 1#1: pread() "/etc/nginx/conf.c/rainloop.conf" failed (21: Is a directory)
3.os: windows 10, VirtualBox

results i received: 
[crit] 1#1: pread() "/etc/nginx/conf.c/rainloop.conf" failed (21: Is a directory)

when i cut "con.d" ,it works fine, but i dont knwon how to solve this problem
please let me know if you fix it.
thanks very much.
best regards.

**Comment by thaJeztah** [comment] 2015-12-28 11:12
The reason that fails, is related to what I commented on your question in https://github.com/boot2docker/boot2docker/issues/846#issuecomment-167531624. Because the boot2docker virtual machine cannot find the file, docker will create a directory named `rainloop.conf` inside the container.

Either put your files below the `c:\users` directory on your Windows machine, so that they are shared with VirtualBox, or manually add extra mounts to the virtual machine, as mentioned in the boot2docker [README](https://github.com/boot2docker/boot2docker/blob/master/README.md#virtualbox-guest-additions)

I'll close this issue here, because this is not a bug, and better discussed in the boot2docker or docker machine issue tracker

**Closed by thaJeztah** 2015-12-28 11:12 UTC
