### ISSUE TITLE
Missing command "watch"

### ISSUE THREAD

**Issue by AndrewBryukhov** [docker/docker#30133] opened 2017-01-13 15:10 UTC
Hello the command watch is missing.

In docker:
bash: watch: command not found

In container:
Error opening terminal: unknown.

**Comment by thaJeztah** [comment] 2017-01-13 15:24
Which commands are available depends on the image you're running; if you're running a container that doesn't have `watch` in it, you'll get such errors.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

If you still suspect there's a bug, please provide the information that was requested in [the issue template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) when you opened this issue. Be sure to at least provide;

- `docker info`
- `docker version`
- the _exact_ steps to reproduce

Otherwise we won't be able to look into your issue.

I'm closing this issue, because I don't think there's a bug at hand here, but let us know if you think it's a bug, and have more information available

**Closed by thaJeztah** 2017-01-13 15:24 UTC
