### ISSUE TITLE
why  are  there  so many "<none>"  TAGs  by run  with   sudo  docker  `images -a`  ?

### ISSUE THREAD

**Issue by everhopingandwaiting** [docker/docker#19285] opened 2016-01-13 04:01 UTC
why  are  there  so many "`<none>`"  TAGs  by run  with   `sudo  docker  images -a`  ?

also  , I see  the site of  http://www.projectatomic.io/blog/2015/07/what-are-docker-none-none-images/
and  http://jimhoskins.com/2013/07/27/remove-untagged-docker-images.html ,
but there  still  also cann't  to solve  my puzzle,
`sudo  docker  version`

```
root@john-inspiron-7420:/var/lib/docker/graph# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
root@john-inspiron-7420:/var/lib/docker/graph#
```
`uname  -a`

```
root@john-inspiron-7420:/var/lib/docker/graph# uname -a
Linux john-inspiron-7420 4.4.0-999-generic #201601082100 SMP Sat Jan 9 02:02:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@john-inspiron-7420:/var/lib/docker/graph#

```
```
root@john-inspiron-7420:/var/lib/docker/graph# docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
systemd/arch        latest              3833cd9cdb88        35 minutes ago      558.3 MB
tomcat8             latest              461026ae814c        About an hour ago   323.5 MB
<none>              <none>              16f3b86357f5        About an hour ago   323.5 MB
<none>              <none>              4c5e348705e5        About an hour ago   323.5 MB
<none>              <none>              f1042a9ac847        About an hour ago   310.5 MB
<none>              <none>              07ce869d7dff        About an hour ago   310.5 MB
<none>              <none>              e23112ea1789        About an hour ago   310.5 MB
<none>              <none>              9a5b1d2f6a50        About an hour ago   310.5 MB
<none>              <none>              37c4c7795fc7        About an hour ago   310.4 MB
<none>              <none>              782539a0d9c9        About an hour ago   310.4 MB
<none>              <none>              7e8aed306262        About an hour ago   310.4 MB
<none>              <none>              04b2530bb0bc        About an hour ago   310.4 MB
<none>              <none>              98ec7c558c22        2 hours ago         484.3 MB
<none>              <none>              779c15f86210        2 hours ago         484.3 MB
<none>              <none>              dd044fa96918        2 hours ago         221.8 MB
<none>              <none>              7d6fad14afda        2 hours ago         1.043 MB
<none>              <none>              f26bbf1bc21a        2 hours ago         12.18 MB
<none>              <none>              be42f758d9cf        2 hours ago         6.613 MB
<none>              <none>              297da4622aa2        2 hours ago         0 B
<none>              <none>              9c841634b779        2 hours ago         0 B
<none>              <none>              1295ecd8c341        2 hours ago         1.041 MB
java                8-jre               d2b6f59e4bb8        5 days ago          310.4 MB
<none>              <none>              4b29286e7d11        5 days ago          310 MB
<none>              <none>              54944597d1ce        5 days ago          170 MB
<none>              <none>              d4beccc5a9da        5 days ago          170 MB
<none>              <none>              21586b7d334c        5 days ago          170 MB
<none>              <none>              c00a3cf7975a        5 days ago          170 MB
<none>              <none>              c5093152b451        5 days ago          170 MB
<none>              <none>              45c22d93ef35        5 days ago          170 MB
<none>              <none>              d89d674b8e9d        5 days ago          170 MB
<none>              <none>              ded0014c43a5        5 days ago          170 MB
<none>              <none>              5c63804eac90        6 days ago          169.4 MB
<none>              <none>              140f9bdfeb97        6 days ago          125.1 MB
<none>              <none>              523ef1d23f22        6 days ago          125.1 MB
root@john-inspiron-7420:/var/lib/docker/graph#

```

```
4c5e348705e570323bbd9aed0957c166fa2100d57110fa2d228a3cffd0769896
523ef1d23f222195488575f52a39c729c76a8c5630c9a194139cb246fb212da6
54944597d1cea319c7a729e7de5f005bdb35f5ef7f71363d38c8cb673341914a
5c63804eac907f318d27728ed09d7ff2662c20e439282a5ca493e3e1779a575b
779c15f86210050a9fa9f72c411bbd047c69e9b0fb54161c526374a97dad164e
782539a0d9c913e40f405c0f58b68e69675f71cebd022e5ea797bcdc869c8eed
7d6fad14afda72cbcb69f29bb6776980dd9c4672455c5b3cf3553ac3ab698b91
7e8aed306262d37cefd994f259211fc033239ea04cf09dd0eeab384ecbd6d068
98ec7c558c22c289149de57b3bb85bf2ce27f55e242c048f3cdf2b1ddf35740c
9a5b1d2f6a50eb466843f082f2aac39b0f293d30a17a0cf0bf9f3ea175cb1aff
9c841634b77921a6215d766e3ea58d42eb2b00954c9762e378312a15ac2c3072
be42f758d9cfe7a7727213d88957ab0daae3ca6778c40025535203dc7f637b10
c00a3cf7975a2c8c8b9e9a35be980021f2d41de1af16153893bc2a932c3e9e3a
c5093152b4517aadddb488e65dd5f28855c3bc629ead647b231e1ac7971e01ae
d2b6f59e4bb8dd9445d442bc676fa625889b59b1146adda8e326435b3773018f
d4beccc5a9dab4354c95ebbade77b550bb93d5ba76d07a01e9537b0d73174904
d89d674b8e9d09f6bb0deb42d1dfe5ce36c65bab730abdf50b5b72c5984a89bb
dd044fa96918ad4fc4968c75fb677616e084bb17da0bbdb5163c4ec220205bf4
ded0014c43a59bce236bd0851a149503ddf40567a41539b954b8a561cafbe298
e23112ea17894504a7f51f35f09174a7efe435027e6f61b2183d040ca64f4e10
f1042a9ac847dfa8642956b63b65a05e15597b388faaa65ed09ad903191733c5
f26bbf1bc21a199a9c6564776a819ff8873b3de468de0ef2e104f026c3066cbe
_tmp
root@john-inspiron-7420:/var/lib/docker/graph# ls 4c5e348705e570323bbd9aed0957c166fa2100d57110fa2d228a3cffd0769896/                                                                                                                   
json              layersize         tar-data.json.gz                                                               
root@john-inspiron-7420:/var/lib/docker/graph# ls 4c5e348705e570323bbd9aed0957c166fa2100d57110fa2d228a3cffd0769896/json                                                                                                               
4c5e348705e570323bbd9aed0957c166fa2100d57110fa2d228a3cffd0769896/json                                              
root@john-inspiron-7420:/var/lib/docker/graph# cat  4c5e348705e570323bbd9aed0957c166fa2100d57110fa2d228a3cffd0769896/json                                                                                                             
{"id":"4c5e348705e570323bbd9aed0957c166fa2100d57110fa2d228a3cffd0769896","parent":"f1042a9ac847dfa8642956b63b65a05e15597b388faaa65ed09ad903191733c5","created":"2016-01-13T02:21:04.155754139Z","container":"a0ac53e49533e639521351fd47db3166103c9259d1db2d3c4c201a8753e3f922","container_config":{"Hostname":"30db80bfe262","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/tomcat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","LANG=C.UTF-8","JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre","JAVA_VERSION=8u66","JAVA_DEBIAN_VERSION=8u66-b17-1~bpo8+1","CA_CERTIFICATES_JAVA_VERSION=20140324","CATALINA_HOME=/usr/local/tomcat","TOMCAT_MAJOR=8","TOMCAT_VERSION=8.0.30","TOMCAT_TGZ_URL

```
with `docker rmi $(docker images -f "dangling=true" -q)` ,it's be ok. 
```
root@john-inspiron-7420:/var/lib/docker/graph# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
systemd/arch        latest              3833cd9cdb88        46 minutes ago      558.3 MB
tomcat8             latest              461026ae814c        About an hour ago   323.5 MB
java                8-jre               d2b6f59e4bb8        5 days ago          310.4 MB

```
last ,  how  could I  delete   those  `<none>`  image  TAG ?  or  why  they  come to  here  ?  thank you !

**Comment by HackToday** [comment] 2016-01-13 06:22
From guide, it said https://docs.docker.com/opensource/project/set-up-dev-env/


This host has no images. You may have one or more dangling images. A dangling image is not used by a running container and is not an ancestor of another image on your system. A fast way to remove dangling containers is the following:

$ docker rmi -f $(docker images -q -a -f dangling=true)

**Comment by thaJeztah** [comment] 2016-01-13 07:41
The `<none>` images that become visible when running `docker images -a` are the *intermediate* images. If you `docker build` a Dockerfile, each step in the Dockerfile is executed in a new container, and the result is committed as a new image (without a name). When running `docker image`, the intermediate  images are hidden, however, using the `-a` option, will reveal them.

Those images are harmless, and are needed to chain the layers together and produce the final image (this will change in docker 1.10, which will use content-addressable layers, that don't need an "image" for the intermediate layers - there will be a blog post on that soon).

I'm going to close this issue, because this is not a bug. However, I hope my additional information explains where they originate from.

**Closed by thaJeztah** 2016-01-13 07:41 UTC

**Comment by everhopingandwaiting** [comment] 2016-01-13 11:15
@thaJeztah  @HackToday   Thank  You  very  much!
