### ISSUE TITLE
`docker restart` causes unexpected creation of a container

### ISSUE THREAD

**Issue by npcode** [docker/docker#25256] opened 2016-07-30 13:32 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Fri Jul 29 03:37:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: active
 NodeID: 1zme5gy8bojg20s4t94q02yuy
 Is Manager: true
 ClusterID: ajbvxdltv5w7ooke4bm73b9xr
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 172.31.6.198
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: node1
ID: RPSY:ERMW:P2NB:UVKX:QJNW:LBVC:U3HR:BA6O:RBTD:OL5T:LAG3:BV2G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

A swarm cluster with 1 manager and 2 workers (aws ec2 instances)

**Steps to reproduce the issue:**
1. `docker service create --replicas=3 --name nginx nginx`
2. Restart a container of the nginx service. e.g. `docker restart nginx.2.9l6beh0o1wx9zuykb3hi4gj4t`
3. `docker service ps nginx`

**Describe the results you received:**

3 running tasks

```
ID                         NAME         IMAGE  NODE   DESIRED STATE  CURRENT STATE           ERROR
6q7rs86nk4kq8zaz7mfz1zyh0  nginx.1      nginx  node3  Running        Running 7 minutes ago   
9l6beh0o1wx9zuykb3hi4gj4t  nginx.2      nginx  node1  Running        Running 6 minutes ago  
9o9rqjcmkyegenhtd3fm3sdc3  nginx.3      nginx  node2  Running        Running 6 minutes ago 
```

**Describe the results you expected:**

3 running tasks and 1 complete task

```
ID                         NAME         IMAGE  NODE   DESIRED STATE  CURRENT STATE           ERROR
6q7rs86nk4kq8zaz7mfz1zyh0  nginx.1      nginx  node3  Running        Running 7 minutes ago   
cp10mit4y9rctlqlrvuzqvuk8  nginx.2      nginx  node1  Running        Running 6 minutes ago   
9l6beh0o1wx9zuykb3hi4gj4t   \_ nginx.2  nginx  node1  Shutdown       Complete 6 minutes ago  
9o9rqjcmkyegenhtd3fm3sdc3  nginx.3      nginx  node2  Running        Running 6 minutes ago 
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-08-01 14:34
I think this is closely related to https://github.com/docker/docker/issues/23704

**Comment by thaJeztah** [comment] 2016-11-24 20:23
Reading again, I think this is a duplicate of https://github.com/docker/docker/issues/23704 indeed. I'll close this issue to keep the conversation in a single place, please continue the discussion over there

**Closed by thaJeztah** 2016-11-24 20:23 UTC
Labels: area/swarm, version/1.12
