### ISSUE TITLE
Can we attach a volume to a running container?

### ISSUE THREAD

**Issue by sourav82** [docker/docker#10975] opened 2015-02-24 07:41 UTC
Is there any way to attach a volume (say, /opt/data) from the host machine to the running container?

**Comment by thaJeztah** [comment] 2015-02-24 08:35
This is currently not possible via the CLI, but it *is* possible via the API; https://github.com/docker/docker/issues/9849#issuecomment-68355285)

I think this is a duplicate of https://github.com/docker/docker/issues/9849. If you agree, can you close this issue to keep the issue tracker clean? Thanks!

**Comment by sourav82** [comment] 2015-02-24 11:16
@thaJeztah, What I actually look for is to mount a host directory into the running container. All the places I noticed volumes can be mounted at the time of container creation or at the time of starting the container. What I need, after the container has been started, mount a host directory to the container.

**Comment by coolljt0725** [comment] 2015-02-24 11:38
@sourav82 see this #8826

**Comment by thaJeztah** [comment] 2015-02-24 11:41
> What I actually look for is to mount a host directory into the running container.

Making modifications on running containers (including adding/removing/changing volumes) is not currently supported (You may be able to do some 'trickery' with `--priviledged`, but that's something better to ask in the `#docker` IRC channel) .

You can follow the linked issues to check progress.

**Comment by cpuguy83** [comment] 2015-02-24 13:30
You could certainly do it with nsenter.

**Comment by thaJeztah** [comment] 2015-02-24 15:40
@cpuguy83 do you have a basic example how to achieve that? Perhaps I can add something in the documentation somewhere?

**Comment by jfrazelle** [comment] 2015-02-25 17:58
Closing as duplicate of linked issues

**Closed by jfrazelle** 2015-02-25 17:58 UTC

**Comment by adriano-fonseca** [comment] 2017-05-03 13:45
@thaJeztah some news about attach a volume on running container?
I couldn't find anything relate to this even in new versions. It is already possible?

**Comment by cpuguy83** [comment] 2017-05-03 13:49
@adriano-fonseca There are no plans to support this currently.
Please see the linked issue just above your comment.

**Comment by thaJeztah** [comment] 2017-05-03 16:27
I'm locking this discussion to prevent the discussion from taking place at multiple issues; see the linked issues
