### ISSUE TITLE
`docker rmi ID` untags image even if there is a running container that is using it

### ISSUE THREAD

**Issue by rindek** [docker/docker#18873] opened 2015-12-23 12:42 UTC
## Description of problem:

1. Using `docker rmi` with ID as argument untags image even if there is a running container that is used by this image
2. As result it marks that image as dangling

## docker version:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64
```

## docker info:

```
Containers: 5
Images: 47
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 57
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 8
Total Memory: 31.35 GiB
Name: [... cut ...]
ID: BHQB:3N5X:46IT:BLJI:QQOA:IYVH:4H3K:CV57:VTT3:5S5W:U3NC:OJRK
WARNING: No memory limit support
WARNING: No swap limit support
```

## uname -a

```
Linux hostname 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1~bpo70+1 (2015-06-08) x86_64 GNU/Linux
```

## Steps to reproduce

1. run any container, ex: `docker run -it busybox`
2. run `docker rmi IMAGE_ID`

## Actual Results:

`docker images`:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              ac6a7980c6c2        2 weeks ago         1.113 MB
```

`docker ps`:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
3b46060d3c2f        ac6a7980c6c2        "sh"                     3 minutes ago       Up 3 minutes                                   trusting_raman
```

## Expected Results:

`docker images`:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
busybox             latest              ac6a7980c6c2        2 weeks ago         1.113 MB
```

`docker ps`:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
3b46060d3c2f        busybox             "sh"                     12 seconds ago      Up 11 seconds                                  trusting_raman
```

In my understanding running this command should return and error and do not untag the image.

## Additional info:

The error received while trying to remove the image by id is correct:

```
$ docker rmi ac6a7980c6c2
Error response from daemon: conflict: unable to delete ac6a7980c6c2 (cannot be forced) - image is being used by running container 3b46060d3c2f
Error: failed to remove images: [ac6a7980c6c2]
```

However - docker still untags this image making it dangling (which I believe shouldn't happen, because it's still used image) - it can be filtered by `docker images -f dangling=true`:

```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              ac6a7980c6c2        2 weeks ago         1.113 MB
```

This causes couple issues when cleaning up old non-used images by "well-known" script `docker rmi $(docker images -qf)`

Also: I found out that this is not happening when:
1. Using rmi with IMAGE_NAME
2. Having same image with multiple tags

**Comment by qq690388648** [comment] 2015-12-24 10:41
The code about this issue is here:https://github.com/docker/docker/blob/master/daemon/image_delete.go#L100.
We can discuss what behavior we want.

**Comment by rindek** [comment] 2015-12-24 11:06
What is the story behind the current behaviour? 

In my opinion it should just throw error and do not remove repository reference - this is still a used image and it should work the same as for multiple tags or given name instead of ID. 

Currently daemon detects such image as dangling, which is not true (dangling = unused, safe and ready to be removed)

Also since there is not good way to remove unused images (like docker rmi --unused or something) many articles suggests to use just docker rmi -q with comment "daemon will throw error if the image is used so it's safe to use it", well, true, it does, it throws error, but in addition it dereference the repository :) so I had to manually reference them back, which is not a good experience.

**Comment by runcom** [comment] 2015-12-24 11:16
Have you tried with latest master to see if this problem is still there? There has been quite some movement around images

**Comment by thaJeztah** [comment] 2015-12-24 11:28
I think there's two things to discuss here wrt behavior;

- should I be able to *untag* an image if it's still in use? Possibly, yes; the same will also happen if I `docker pull` and a newer version is downloaded. Open to suggestions though
- should it be regarded "dangling"? No, because it's still in use

Note; haven't checked what the behavior on master is

**Comment by fernandoneto** [comment] 2015-12-28 15:24
im having the same issue.

**Comment by tonistiigi** [comment] 2015-12-28 19:28
Could not reproduce on master

**Comment by alainbryden** [comment] 2016-01-12 00:06
+1 on latest release:
~~~
$ docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                      PORTS                                                  NAMES
3e95b2637d85        busybox:latest                  "/bin/true"              18 seconds ago      Exited (0) 16 seconds ago                                                          docker_datadisk_1
293838b8139b        rabbitmq:3.5.6                  "/docker-entrypoint.s"   19 seconds ago      Up 18 seconds               4369/tcp, 5671-5672/tcp, 25672/tcp                     docker_rabbitmq_1
33721c7b5fe4        mongo:3.0.7                     "/entrypoint.sh mongo"   21 seconds ago      Up 21 seconds               27017/tcp                                              docker_mongod_1
37b0bfb95e76        busybox:latest                  "/bin/true"              28 seconds ago      Exited (0) 28 seconds ago                                                          docker_datacachedisk_1
~~~

~~~
$ docker rmi $(docker images -a -q)
Error response from daemon: conflict: unable to delete ac6a7980c6c2 (must be forced) - image is being used by stopped container 3e95b2637d85
Error response from daemon: conflict: unable to delete 448afeda0388 (cannot be forced) - image is being used by running container 293838b8139b
Error response from daemon: conflict: unable to delete ca3cf1f47476 (cannot be forced) - image is being used by running container 33721c7b5fe4
...
Error response from daemon: conflict: unable to delete 0a85502c06c9 (cannot be forced) - image has dependent child images
Error: failed to remove images: [33852cf42860 35db777c89ce ... e9ae3c220b23 a6785352b25c 0998bf8fb9e9 0a85502c06c9]
$
~~~

~~~
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS                                                  NAMES
3e95b2637d85        ac6a7980c6c2        "/bin/true"              22 seconds ago      Exited (0) 20 seconds ago                                                          docker_datadisk_1
293838b8139b        448afeda0388        "/docker-entrypoint.s"   23 seconds ago      Up 22 seconds               4369/tcp, 5671-5672/tcp, 25672/tcp                     docker_rabbitmq_1
33721c7b5fe4        ca3cf1f47476        "/entrypoint.sh mongo"   25 seconds ago      Up 24 seconds               27017/tcp                                              docker_mongod_1
37b0bfb95e76        ac6a7980c6c2        "/bin/true"              32 seconds ago      Exited (0) 31 seconds ago                                                          docker_datacachedisk_1
~~~

~~~
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
~~~

**Comment by thaJeztah** [comment] 2016-01-12 01:40
According to @tonistiigi's comment, this should be fixed on master, so will be fixed in docker 1.10

@tonistiigi do you know which PR fixed this?

**Comment by tonistiigi** [comment] 2016-01-12 01:53
@thaJeztah Sorry, the issue still seems to be valid in master. Not sure what I did wrong the last time I tried to reproduce.

**Closed** 2016-01-12 23:56 UTC
Labels: priority/P1

**Comment by rindek** [comment] 2016-01-13 10:12
Thank you for fixing that!

**Comment by thaJeztah** [comment] 2016-01-13 17:44
@rindek thanks for reporting :smile:
