### ISSUE TITLE
Can't resolved with container name without --name option when docker run in swarm mode with docker 1.13

### ISSUE THREAD

**Issue by ziqingzhu** [docker/docker#30346] opened 2017-01-22 08:44 UTC
**Description**
When I want to run a container to work in swarm mode overlay network, I found that if not run `docker run --name ...`, it can't be resolved with container name

**Steps to reproduce the issue:**
1.create a swarm mode cluster and create an overlay network with option --attachable
2.create a service testA in swarm mode
3.create a container testB with command `docker run ...` without option --name, it will get a random name, such as `lucid_lumiere`
4.create a container testC with command `docker run --name testC ...`
5.run command `nslookup lucid_lumiere` and `nslookup testC ` in testA

**Describe the results you received:**
```style
[root@22ca477efa57 /]# nslookup lucid_lumiere
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
*** Can't find lucid_lumiere: No answer
```
```style
[root@22ca477efa57 /]# nslookup testC
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	testC
Address: 10.0.3.4
```

**Describe the results you expected:**
`nslookup lucid_lumiere` could get the right answer

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 98
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-8:5-59899908-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 53.69 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 17.3 GB
 Data Space Total: 107.4 GB
 Data Space Available: 90.08 GB
 Metadata Space Used: 33.28 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.114 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /data/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ye2ghne3j4rvmr5r7ljcq48vs
 Is Manager: true
 ClusterID: j7wn96ngop5xhxu6h333b7tdt
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 5000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.16.10.19
 Manager Addresses:
  172.16.10.19:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.10-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.11 GiB
Name: log.aispeech.com
ID: 4Y6T:NCRV:K7J7:WOKO:ZIZY:LXYQ:IQRL:FMNL:PH4E:BPBX:6VU6:Y3ZB
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 56
 Goroutines: 154
 System Time: 2017-01-22T16:43:58.12487325+08:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://33391a94.m.daocloud.io/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by SISheogorath** [comment] 2017-01-22 15:53
That should mainly caused by the fact that `_` is not a valid character for a domain name. See [RFC1035](https://tools.ietf.org/html/rfc1035) page 8.

Does it work if you are using any other network type? In general it shouldn't as I mentioned above.

**Comment by ziqingzhu** [comment] 2017-01-23 01:29
If create container with command `docker run -d --network mynet --name lucid_lumiere ...`, the `lucid_lumiere` could be resolved by service in swarm mode, but can't resolved without `--name`
```style
[root@22ca477efa57 /]# nslookup lucid_lumiere
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	lucid_lumiere
Address: 10.0.3.4
```

**Comment by mavenugo** [comment] 2017-01-23 01:34
@ziqingzhu this is as per design for the built-in SD. containers without `--name` were not added to the DNS lookup. Do you have a good reason to have this supported ?

**Comment by ziqingzhu** [comment] 2017-01-23 01:47
So if i want to access testB, only could use ip, then i should run `ifconfig` in testB first, any other suggest?
Thanks~

**Comment by jmzwcn** [comment] 2017-01-23 02:03
If you rename an anonymous container, you will find this DNS works.

**Comment by ziqingzhu** [comment] 2017-01-23 02:15
I will add --name or rename the container to make DNS work, but I think it could better support without --name in my opinion, as @mavenugo said, it is not bug

**Comment by SISheogorath** [comment] 2017-01-23 02:17
If you really want you can always use the container's id to get an IP.

**Comment by thaJeztah** [comment] 2017-01-23 16:29
As @mavenugo mentioned, this is by design; if you _don't_ name your container, you would still have to manually look up its name in order to get the IP-address. If this is for debugging, you can look up its IP-address instead of it's name.

Basically; if you want a container be looked up by name; _give_ it a name.

I'm going ahead and close this issue, because this works as designed, and so far, I haven't seen a clear use case why this _should_ be different, but feel free to comment if you have an important reason that requires this.

**Closed by thaJeztah** 2017-01-23 16:29 UTC
Labels: version/1.13
