### ISSUE TITLE
"invalid volume mount source, must not be an absolute path" occurred when using docker service create --mount type=volume

### ISSUE THREAD

**Issue by liuxiaopiao** [docker/docker#25912] opened 2016-08-22 04:44 UTC
**Output of `docker version`:**
docker --version
Docker version 1.12.1, build 23cf638, experimental

**Output of `docker info`:**
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: active
 NodeID: 451bgswzvxvhnmj1vmltjomaj
 Is Manager: true
 ClusterID: da0rtoysphkdgc3p0uo2ocvs8
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.245.251.124
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.1.12-37.5.1.el7uek.x86_64
Operating System: Oracle Linux Server 7.0
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 16.97 GiB
Name:  h1
ID: OFJZ:3THB:ZM76:5D4P:WLJG:D74G:COYF:B4NB:E37Q:MXAV:ZZGR:6S7X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OS: 
[root@generic]# uname -a
Linux  4.1.12-37.5.1.el7uek.x86_64 #2 SMP Thu Jun 9 16:01:20 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1.   Setup one swarm env using "docker swarm init"
2.  In the swarm manager node, run "docker service create --replicas 2 --name c2 --network ingress --publish 22 --mount type=volume,source=/run/systemd,target=/run/systemd  busybox ping docker.com"
3. Check the service status by "docker service  ps c2":
[root@h1 generic]# docker service ps c2
ID                         NAME      IMAGE    NODE                    DESIRED STATE  CURRENT STATE                    ERROR
b10zaq7rf2u3apmvsu2wwom4n  c2.1      busybox  h2  Ready          Assigned less than a second ago
5b27w4nimle3jmg6dde77poam   \_ c2.1  busybox  h1  Ready          Rejected less than a second ago  "invalid volume mount source, …"
86vjnjhcxlfoof1wleiu5y19s   \_ c2.1  busybox  h2  Shutdown       Rejected 5 seconds ago           "invalid volume mount source, …"
cdue3daq5qi4rum5kp51c1qdg   \_ c2.1  busybox  h1  Shutdown       Rejected 5 seconds ago           "invalid volume mount source, …"
457h3gto3ddoc2n4utiu70yyr   \_ c2.1  busybox  h2  Shutdown       Rejected 10 seconds ago          "invalid volume mount source, …"
6y2gfl7sgurwdety4t54xiabd  c2.2      busybox  h1  Ready          Rejected less than a second ago  "invalid volume mount source, …"
cpddx6r20dkd9sx3hg2898pz3   \_ c2.2  busybox  h1  Shutdown       Rejected 5 seconds ago           "invalid volume mount source, …"
dek1smzmechdedmjmbnk6u2jv   \_ c2.2  busybox  h1  Shutdown       Rejected 10 seconds ago          "invalid volume mount source, …"
61f7s8ke5grlhhocahie0lz0z   \_ c2.2  busybox  h1  Shutdown       Rejected 15 seconds ago          "invalid volume mount source, …"
5l39sq16xarmzzgjdcfozxjk2   \_ c2.2  busybox  h1  Shutdown       Rejected 20 seconds ago          "invalid volume mount source, …"

**Describe the results you received:**
From /var/log/messages, we can see the below error:
Aug 21 21:40:18 slc09woz dockerd: time="2016-08-21T21:40:18.256522939-07:00" level=error msg="failed to start taskManager" error="invalid volume mount source, must not be an absolute path: /run/systemd" module=agent
Aug 21 21:40:18 slc09woz dockerd: time="2016-08-21T21:40:18.282052878-07:00" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=bfo8245ks0t5sdsu8qntisjmz node.session=8hh95orw8jvx0rcdrxkhutbhj task.id=a01bs7w2lyk3isj6aie3js5w8

**Describe the results you expected:**
Why do we need the relative path in this command? I tried the same command in previous version of docker and it worked fine.

**Comment by garthk** [comment] 2016-08-22 05:55
Try `type=bind`, e.g. `--mount target=/tmp/docker.sock,source=/var/run/docker.sock,type=bind`.

**Comment by urlund** [comment] 2016-08-22 08:19
I have the same issue after upgrading to 1.12.1 

This works fine:
```docker run -v /foo:/bar ...``` 

but creating a service with:
```docker service create --mount source=/foo,target=/bar,type=volume ...``` 

gives me:
```invalid volume mount source, must not be an absolute path: /foo```

**Comment by cpuguy83** [comment] 2016-08-22 13:30
@urlund 1.12 is very much the broken one.
You don't want a `type=volume`, you want a `type=bind` as @garthk mentioned.

Closing because this is working as intended. Docs for this are here: #25776

**Closed by cpuguy83** 2016-08-22 13:30 UTC
Labels: area/swarm

**Comment by liuxiaopiao** [comment] 2016-08-23 00:27
Thanks all. type=bind works

**Comment by pacoxu** [comment] 2016-10-31 13:51
same issue with 'type=bind'

[root@localhost ~]# docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64
[root@localhost ~]# docker service create --mount source=/foo,target=/bar,type=bind redis
6oqvnzqm5e6r73f766ce6g7z6
[root@localhost ~]# docker service ps 6oqvnzqm5e6r73f766ce6g7z6
ID                         NAME                   IMAGE  NODE                   DESIRED STATE  CURRENT STATE                    ERROR
4xxuxc11hi1djivfaqygetsww  ecstatic_curran.1      redis  localhost.localdomain  Ready          Rejected less than a second ago  "invalid bind mount source, so…"
5tjri5dygi1emvtsxqf3w8knt   \_ ecstatic_curran.1  redis  localhost.localdomain  Shutdown       Rejected 5 seconds ago           "invalid bind mount source, so…"
8qyrb13zhhqm7u577gp509c4g   \_ ecstatic_curran.1  redis  localhost.localdomain  Shutdown       Rejected 6 seconds ago           "invalid bind mount source, so…"

**Comment by cpuguy83** [comment] 2016-10-31 13:57
@pacoxu The source must exist.

**Comment by pacoxu** [comment] 2016-10-31 13:58
BTW, according to https://github.com/docker/docker/pull/22373, 
bind: Paths on the host that get mounted into the container. Paths must exist prior to creating the container.

@cpuguy83 

Why not we create for the service? 

For a cluster, you have to create the path in every node, which is quite inconvenient.

**Comment by cpuguy83** [comment] 2016-10-31 14:00
@pacoxu Because this is a broken expectation for docker to do for you.
If you want docker to create a path for you, then use a volume.

**Comment by pacoxu** [comment] 2016-10-31 14:02
@cpuguy83  thanks a lot for your explanation.  Got it.

**Comment by sinkoneri** [comment] 2016-11-17 22:10
same issue with 'type=bind'
Docker version 1.12.3, build 6b644e
https://goo.gl/LNg3dt

**Comment by cpuguy83** [comment] 2016-11-17 22:25
@sinkoneri the error is because the source path doesn't exist on the node where the task is scheduled. Since you are using a vm, the path you are specifying from the client side does indeed not exist.

**Comment by sinkoneri** [comment] 2016-11-18 20:37
@cpuguy83 
Before creating the jenkins service i issued the eval ($(docker-machine env nodename) than the mkdir command which  creates the source dir.
I followed [this](https://www.youtube.com/watch?v=vLVwqPS8H_E#t=19m35s) video to create a failover jenkins config with docker swarm. Am i missing something or there is some preconfig steps,settings which isn`t in the video?

Sorry I'm a newb at docker/docker swarm.

**Comment by cpuguy83** [comment] 2016-11-18 20:39
@sinkoneri Yould have to ssh to the machine to create these host dirs, just setting the env is not going to do it.

**Comment by sinkoneri** [comment] 2016-11-20 19:51
@cpuguy83 Ok, thanks after creating the dirs it works!
