### ISSUE TITLE
Random BSOD on Windows 10 while using docker

### ISSUE THREAD

**Issue by joelcavarroc** [docker/docker#32043] opened 2017-03-23 15:12 UTC
**Description**
Windows 10 crashed while using docker. 
I am currently using docker 17.03 for testing purposes. I have a program that use docker API to create, run and delete a docker machine running ActiveMQ 6.2.1. The idea is to create a new clean machine for every tests and my tests are run in loop.
Briefly I do:

For each test
 Create a docker container
 Run the container
 Run the test
 Stop the container
 Delete the container
end for

**Describe the results you received:**
I get eventually get a random BSOD (not for a given test, but after some tests).

**Describe the results you expected:**
I would expect to be able to run all my tests without any crash.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, physical, etc.):**
systeminfo:
Host Name:                 JO-PC
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.15063 N/A Build 15063
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Original Install Date:     21/03/2017, 21:17:15
System Boot Time:          23/03/2017, 10:40:13
System Manufacturer:       System manufacturer
System Model:              System Product Name
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 42 Stepping 7 GenuineIntel ~3401 Mhz
BIOS Version:              American Megatrends Inc. 3603, 09/11/2012
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             fr;French (France)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16 351 MB
Available Physical Memory: 2 777 MB
Virtual Memory: Max Size:  22 410 MB
Virtual Memory: Available: 2 939 MB
Virtual Memory: In Use:    19 471 MB
Page File Location(s):     C:\pagefile.sys

The host is running on hyper-v

**Comment by AkihiroSuda** [comment] 2017-03-23 18:23
Linux docker on VM on Windows?
Windows docker on VM on Windows? (Which one of Windows crashed?)

This article might be useful (steps might be different for Win 10 though)
http://www.techrepublic.com/blog/windows-and-office/how-do-i-use-windbg-debugger-to-troubleshoot-a-blue-screen-of-death/

**Comment by AkihiroSuda** [comment] 2017-04-05 03:57
Let me close this issue, since this is unlikely to an issue of Docker

**Closed by AkihiroSuda** 2017-04-05 03:57 UTC

**Comment by marvinlange** [comment] 2017-05-24 20:49
I am having the same issue and it only happens wile running Docker  Linux docker on VM on Windows
Have reset container to default numerous times trying to run webodm if I get it installed it will run but id I have to restart docker I BSOD 
I am not 100% sure its docker but Machine will run for days without docker running
[docker-crash.txt](https://github.com/moby/moby/files/1027214/docker-crash.txt)

**Comment by marvinlange** [comment] 2017-05-24 20:57
Obviously were not alone 
https://github.com/docker/toolbox/issues/623

**Comment by Bonobomagno** [comment] 2017-06-05 12:08
got the same error. Also, if i go on hyper-v manag app i can read that there is a internet problem

**Comment by lanwin** [comment] 2017-06-25 14:04
Same here. The problems mostly happens when I use docker build after some time to build a *windows core image* on *Windows 10 creators update*. After restart the build command works. The other commands to like pull and remote management don't trigger the bsod.

**Comment by maarten-kieft** [comment] 2017-07-19 06:50
I have something similar as lanwin, context: 
I have windows 10 creators update
Running windows containers 
My docker file starts with pulling a nanoserver (but had the same with windowscore) and than simply copy a folder to the file. The bsos happens when I tries to copy the folder, the nano server image is already pullend

**Comment by AkihiroSuda** [comment] 2017-07-19 07:11
I think this issue should be reported to Microsoft.

Anyway, crashdump seems needed to analyze the issue.

**Comment by takekazuomi** [comment] 2017-07-19 07:42
To experts
A similar Issue is on here. https://github.com/Microsoft/mssql-docker/issues/88#issucomomment-314618471 
Someone MSFT  reproduced the BSOD.

I think the root cause is in WIndows.

**Comment by BringerOD** [comment] 2017-10-03 18:49
+1

**Comment by cocorossello** [comment] 2017-11-14 12:21
Also happens in my win10 pro fall update, 3 times in 2 days, since I started using docker (it never happened before)

**Comment by superzadeh** [comment] 2017-11-14 13:46
I can also reproduce this quite frequently (at least once every week, sometimes several times per day). Most of the time, it is a IRQL_NOT_LESS_OR_EQUAL stopcode. It seems to happen since I'm a using a mounted volume with MariaDB container and generate a lot of writes (ie: database restore).

**Comment by jondmcelroy** [comment] 2017-11-17 16:59
Started blue screening regularly after the win10 fall update as does everyone in my office with the same configuration. Do not have the issue with machines that are not running docker.

**Comment by rn** [comment] 2017-11-17 20:49
Could be dup of https://github.com/docker/for-win/issues/913 would be good to get a minidump and/or stack trace from it in windbg

**Comment by johnstep** [comment] 2017-11-17 23:26
@joelcavarroc Make sure you're reporting the issues to Microsoft, if possible.

Are you able to share any of the memory dumps, even mini dumps in `\Windows\Minidump`, or a stack trace, as @rn mentioned? I don't recommend sharing them publicly, but let me know if you have a way to share privately.

Docker does not install any kernel-mode components, so the root cause is outside of Docker (well, depending on the bug check code, but almost certainly), but we can forward to Microsoft.

**Comment by PatrickLang** [comment] 2017-11-17 23:47
Yes - if you have a support contract (eg through your company) please raise a case. That's the fastest way to get something fixed if its a bug in Windows.

If you look in the Application event log, you'll also find logs from "Windows Error Reporting". If there's a Cab Id, can you share it? If you have the customer experience improvement program turned on, these crashes are aggregated and bucketed with a Cab Id. 

Note - this crash was just one of many from a system with a bad DIMM. Fixed now :)

Fault bucket AV_BAD_IP_nt!MiPfnsWorthTrying, type 0
Event Name: BlueScreen
Response: Not available
**Cab Id: aa46d5cd-d395-4e8b-ab31-cbbbb90c31ae**

Problem signature:
P1: 1000007e
P2: ffffffffc000001d
P3: fffff803410f22ac
P4: ffff8207093df6e8
P5: ffff8207093def30
P6: 10_0_16299
P7: 0_0
P8: 256_1
P9: 
P10:

**Comment by masterkawaster** [comment] 2017-12-05 08:24
BSOD!

Windows 10 Pro 1703
Docker version 17.10.0-ce, build f4ffd25
Windows containers on Windows

every time when running latest microsoft/mssql-server-windows-developer image in about minute from starting the container.

**Comment by AkihiroSuda** [comment] 2017-12-05 08:33
@masterkawaster 

This doesn't seem an issue of Moby.
Please report your issue to Microsoft.

Either way, no one can investigate the issue without WinDBG backtrace: http://www.techrepublic.com/blog/windows-and-office/how-do-i-use-windbg-debugger-to-troubleshoot-a-blue-screen-of-death/

**Comment by gsfarm** [comment] 2021-03-08 08:01
Yes, Docker Desktop calls the BSOD. I've been watching this for six months now with different mainboards and Windows 10 installs: DRIVER_IRQL_NOT_LESS_OR_EQUAL on ntoskrnl.exe

**Comment by liquid-void** [comment] 2021-09-29 19:25
Finally found this thread after two months of BSODs, sometimes up to 4 times a day. So no update on this in 4 years?
I can confirm @gsfarm 's comment, that this crash is caused 99.9% by Docker Desktop, even though there is no reference to the Docker service in the Bugcheck analysis. After a clean reinstall the first time my system crashes is when Docker service starts.
BSOD appears when Docker service is running with WSL 2 Linux containers. Sometimes, when my laptop is "idle", sometimes when I'm working.
I have attached my system information export and 10 most recent WinDbg Bugchecks and their corresponding minidump files. Hope this helps in narrowing down the problem.

9/10 times  IRQL_NOT_LESS_OR_EQUAL (a)  ntoskrnl.exe
1/10 times  INTERRUPT_EXCEPTION_NOT_HANDLED (3d)

My system:
[sysinfo.txt](https://github.com/moby/moby/files/7254539/sysinfo.txt)


Bugchecks:
[20210924_1_bugcheck.txt](https://github.com/moby/moby/files/7254513/20210924_1_bugcheck.txt)
[20210924_2_bugcheck.txt](https://github.com/moby/moby/files/7254514/20210924_2_bugcheck.txt)
[20210921_1_bugcheck.txt](https://github.com/moby/moby/files/7254515/20210921_1_bugcheck.txt)
[20210921_2_bugcheck.txt](https://github.com/moby/moby/files/7254516/20210921_2_bugcheck.txt)
[20210921_3_bugcheck.txt](https://github.com/moby/moby/files/7254518/20210921_3_bugcheck.txt)
[20210929_1_bugcheck.txt](https://github.com/moby/moby/files/7254519/20210929_1_bugcheck.txt)
[20210929_2_bugcheck.txt](https://github.com/moby/moby/files/7254520/20210929_2_bugcheck.txt)
[20210928_bugcheck.txt](https://github.com/moby/moby/files/7254521/20210928_bugcheck.txt)
[20210927_bugcheck.txt](https://github.com/moby/moby/files/7254522/20210927_bugcheck.txt)
[20210926_bugcheck.txt](https://github.com/moby/moby/files/7254523/20210926_bugcheck.txt)

Minidumps:
[minidumps.zip](https://github.com/moby/moby/files/7254533/minidumps.zip)

**Comment by liquid-void** [comment] 2021-09-29 19:51
Not sure if this is an issue with Moby. I believe the BSODs started about the time, when I installed Docker Desktop. Multiple BSODs, about once a day, sometimes up to 4 times a day.
I believe this crash is caused by Docker Desktop, even though there is no reference to the Docker service in the Bugcheck analysis. After a clean Windows reinstall, the first time my system crashes is when I installed Docker again.
BSOD appears randomly when Docker service is running. After what I read in the previous comments, faulty hardware would be a weird coincidence.
I have attached my system information export (uninstalled Docker Desktop) and 10 most recent WinDbg Bugchecks  and their corresponding minidump files (all while Docker service was running). Hope this helps in narrowing down the problem.

9/10 IRQL_NOT_LESS_OR_EQUAL (a) ntoskrnl.exe
1/10 INTERRUPT_EXCEPTION_NOT_HANDLED (3d)

My system:
[sysinfo.txt](https://github.com/moby/moby/files/7254643/sysinfo.txt)

Bugchecks:
[20210921_1_bugcheck.txt](https://github.com/moby/moby/files/7254664/20210921_1_bugcheck.txt)
[20210921_2_bugcheck.txt](https://github.com/moby/moby/files/7254665/20210921_2_bugcheck.txt)
[20210921_3_bugcheck.txt](https://github.com/moby/moby/files/7254666/20210921_3_bugcheck.txt)
[20210924_1_bugcheck.txt](https://github.com/moby/moby/files/7254667/20210924_1_bugcheck.txt)
[20210924_2_bugcheck.txt](https://github.com/moby/moby/files/7254668/20210924_2_bugcheck.txt)
[20210926_bugcheck.txt](https://github.com/moby/moby/files/7254669/20210926_bugcheck.txt)
[20210927_bugcheck.txt](https://github.com/moby/moby/files/7254670/20210927_bugcheck.txt)
[20210928_bugcheck.txt](https://github.com/moby/moby/files/7254671/20210928_bugcheck.txt)
[20210929_1_bugcheck.txt](https://github.com/moby/moby/files/7254672/20210929_1_bugcheck.txt)
[20210929_2_bugcheck.txt](https://github.com/moby/moby/files/7254673/20210929_2_bugcheck.txt)

Minidumps:
[minidumps.zip](https://github.com/moby/moby/files/7254676/minidumps.zip)

**Comment by thaJeztah** [comment] 2021-09-29 19:53
Could you open a new ticket in https://github.com/docker/for-win ?

**Comment by thaJeztah** [comment] 2021-09-29 19:55
FWiw, that message is documented as related to hardware kernel drivers (which, afaik, Docker Desktop doesn't install, so curious how it could trigger this) https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xd1--driver-irql-not-less-or-equal

**Comment by liquid-void** [comment] 2021-09-29 20:03
Will post an issue there, thanks. I really don't know and I might be wrong. I'm not an experienced Windows debugger. It's very hard to pinpoint this issue. I only know that Docker service keeps crashing the first time I start Docker Desktop. Always have to start it at least twice. Then these BSODS keep happening randomly. There is also a possibilty, that my new Notebook got a faulty DIMM module, though. Hope I'm not misleading anyone. Does it interact in any meaningful way with ntoskrnl.exe?
