### ISSUE TITLE
Support --env-file flag in docker service create

### ISSUE THREAD

**Issue by tonysickpony** [docker/docker#27003] opened 2016-09-29 04:59 UTC
I noticed that `--env-file` flag has been removed from docker service. I believe there must be a reason behind it, maybe have something to do with service update concerns. However it makes it harder for me to migrate from docker-compose based configuration to docker service.
So is there any planning to move `--env-file` flag back ? or any suggestion on the alternative?

**Comment by thaJeztah** [comment] 2016-09-29 14:21
Thanks for suggesting, however it looks like this is a duplicate of https://github.com/docker/docker/issues/24712, and a pull request is already opened, and currently under review https://github.com/docker/docker/pull/24844

Note that we have a "tracking" issue for options that are not (or not yet) implemented for services; see https://github.com/docker/docker/issues/25303.

I'll close this issue, as it's a duplicate, but thanks again

**Closed by thaJeztah** 2016-09-29 14:21 UTC
Labels: area/swarm, kind/enhancement
