### ISSUE TITLE
docker-engine ignores /etc/default/docker content

### ISSUE THREAD

**Issue by alanfranz** [docker/docker#32397] opened 2017-04-06 08:15 UTC
**Description**

I'm using Ubuntu 16.04.2, kernel 4.8.0-46-generic on x86_64, ```docker-engine 17.03.1~ce-0~ubuntu-xenial```

It seems that **the docker daemon ignores the /etc/default/docker** file on my machine (I don't know since when; I know that older version worked properly), because even when I set DOCKER_OPTS, the storage driver doesn't get changed. This contradicts what it's expected to happen and what is told in the docs about /etc/default/docker:

https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#a-pluggable-storage-driver-architecture

**Steps to reproduce the issue:**

Use this /etc/default/docker:
```
root@amaranta:/etc/default# cat docker
# Docker Upstart and SysVinit configuration file

# Customize location of Docker binary (especially for development testing).
#DOCKER="/usr/local/bin/docker"

# Use DOCKER_OPTS to modify the daemon startup options.
#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"
DOCKER_OPTS="--storage-driver overlay2"

# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export TMPDIR="/mnt/bigdrive/docker-tmp"
```

launch:

```
service docker stop
service docker start
```

**Describe the results you received:**

dockerd is launched ignoring DOCKER_OPTS and uses aufs:

```
root@amaranta:/etc/default# ps -aux | grep dockerd
root     25889  0.5  0.2 562736 37540 ?        Ssl  10:08   0:00 /usr/bin/dockerd -H fd://
```
```
root@amaranta:/etc/default# cat /proc/mounts | grep aufs
/dev/sda1 /var/lib/docker/aufs ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
```

**Describe the results you expected:**

I'd expect docker to use overlay2.

**Additional information you deem important (e.g. issue happens only occasionally):**

**If I modify /lib/systemd/system/docker.service and I add the --storage-driver call, then I call systemctl daemon-reload, and I start docker, then the storage driver is correctly selected and used.**

There seem to be **multiple init scripts** (init.d, upstart, systemctl) in the package, which add complexity, and the while the first and the second seem to read the config file, there's no trace of systemctl employing it.

```
root@amaranta:/etc/default# dpkg -L docker-engine | grep init
/usr/share/man/man1/docker-swarm-init.1.gz
/usr/bin/docker-init
/etc/init.d
/etc/init.d/docker
/etc/init
/etc/init/docker.conf
root@amaranta:/etc/default# dpkg -L docker-engine | grep systemd
/lib/systemd
/lib/systemd/system
/lib/systemd/system/docker.service
/lib/systemd/system/docker.socket
root@amaranta:/etc/default# dpkg -L docker-engine | grep default
/etc/default
/etc/default/docker
```
**Output of `docker version`:**

```
root@amaranta:/etc/default# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-46-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.66 GiB
Name: amaranta
ID: G5XL:WF24:4AFG:U6HC:WT6X:NAJP:I4UQ:5PWX:S2R3:2YB6:CULJ:XZPD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical server on OVH.

**Comment by thaJeztah** [comment] 2017-04-06 08:26
Correct, that file is only used for systems running "Upstart" or "SysVinit" as an init system (see the [notice at the top of that file](https://github.com/docker/docker/blob/v17.03.1-ce/contrib/init/sysvinit-debian/docker.default#L1-L8)

If you're running on a system that uses systemd (which ubuntu 16.04 does), you can;

- Use [systemd drop-in files](https://docs.docker.com/v1.13/engine/admin/systemd/#/custom-docker-daemon-options). This is a bit complicated, and is specific to systemd
- The recommended approach is to use a `daemon.json` configuration file as described [in the dockerd reference](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file); this method works on any system, irregardless of the "init" system that's used

**Comment by thaJeztah** [comment] 2017-04-06 08:28
The reason for multiple init scripts and configuration files to be present is because you _can_ run a different init system on systems that run systemd (some people don't use systemd on ubuntu 16.04), in which case docker would fail to run, hence all the options being included in the package.

I'll close this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-04-06 08:28 UTC
Labels: version/17.03

**Comment by thaJeztah** [comment] 2017-04-06 08:30
Hm, we may have to update the docs to refer to the different ways of configuring though; could you open an issue for that in the https://github.com/docker/docker.github.io/issues issue tracker? (there may already be an issue for that, but not sure)

**Comment by alanfranz** [comment] 2017-04-06 08:40
@thaJeztah argh. Since I had already modified /etc/default/docker, such message wasn't included in my file, I needed to look in the dpkg dist. And since it used to work, I had no idea it could suddenly fail :-)

Also, AFAICR, ubuntu 16.04 has a "fallback" system which lets systemd use sysv and upstart scripts... so I assumed Docker would just leverage such compatibility layer :-/

About the "switching to different init systems..."... wow, I'd expect that somebody using a non-default init (which is quite a root part of what a distro does) could be expected to install docker manually, not a packaged version; but I won't question Docker's own choices, of course :-)

Tested with daemon.json. Works properly.

**Comment by thaJeztah** [comment] 2017-04-06 08:48
I _think_ the "fallback" allows you to keep using sysv (or just provides wrapper scripts to use the "regular" commands, which behind the scenes are aliases for `systemctl fooo...`)

I think the whole configuration section needs some attention. In a recent rewrite, the description for "drop in files" was removed from the systemd section; I think we should _keep_ that section in, but recommend people to use the `daemon.json` file (as it has various advantages, including "live" reloading some options)

**Comment by alanfranz** [comment] 2017-04-06 09:50
@thaJeztah I agree. The fact that ```/etc/default/docker``` exists but works only for *some* init systems, not including the default, is quite misleading and has no obvious reason to be; *daemon.json* would work for sysv and upstart as well, right?

By the way, I forgot: thanks for your support.
