### ISSUE TITLE
Cannot stop/kill/rm ghost container

### ISSUE THREAD

**Issue by allamand** [docker/docker#16628] opened 2015-09-28 13:07 UTC
BUG REPORT INFORMATION

docker version:

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

docker info:

```
Containers: 19
Images: 766
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 828
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-40-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 15.59 GiB
Name: usso-stargate-SG1
ID: O2N5:3ZXB:BGUJ:RMQM:AJ3D:GAX6:NFSG:5WQ2:EHME:JQ6R:ZKVO:UOR3
WARNING: No swap limit support
```

uname -a:
Linux star 3.16.0-40-generic #54~14.04.1-Ubuntu SMP Wed Jun 10 17:30:45 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Running in VirtualBox (Host ubuntu) on Windows 7

List the steps to reproduce the issue:
It's not systematic, sometimes a compilation layer of my Dockerfile get stuck un daemon.

Describe the results you received:

Describe the results you expected:
I am not able to delete the layer container

Provide additional info you think is important:

While running RUN command in my Dockerfile trying to install sybase ASE server, sometimes I got dead/zombie containers that I couldn't stop except with a system reboot...

docker rm/stop/kill are no effect (didnt giving the hand back).

Here is the docker inspect of my container 

```
docker inspect f8013de9aa63d82a393409824ee2105a81a7f6172323a90ca490d6b726c7d3c7
[
{
    "Id": "f8013de9aa63d82a393409824ee2105a81a7f6172323a90ca490d6b726c7d3c7",
    "Created": "2015-09-17T15:29:57.647840763Z",
    "Path": "/bin/sh",
    "Args": [
        "-c",
        "yum -y install libaio \u0026\u0026 mkdir -p /install/ \u0026\u0026 source /root/.bashrc \u0026\u0026     cd /install \u0026\u0026 curl -o ASE_15.7_SP134_LinX64_ASESERV1570134_0-20011142.TGZ \"http://stargate/ASE_15.7_SP134_LinX64_ASESERV1570134_0-20011142.TGZ\" \u0026\u0026     mkdir -p /tmp \u0026\u0026 ls -la \u0026\u0026 tar zxf ASE_15.7_SP134_LinX64_ASESERV1570134_0-20011142.TGZ \u0026\u0026     ls -la \u0026\u0026     cd ebf24647 \u0026\u0026 ./setup.bin -f /install/installation_ASE.properties -i silent -DAGREE_TO_SYBASE_LICENSE=true -DRUN_SILENT=true \u0026\u0026     yum clean all \u0026\u0026     rm -rf /install/ \u0026\u0026 rm -rf /tmp/* \u0026\u0026     . /opt/sybase/na/syb_serv64-15.7.0/SYBASE.sh \u0026\u0026     echo \"::1 sybaseserver\" \u003e\u003e /etc/hosts \u0026\u0026     srvbuildres -r /conf/authref_ase.rs \u0026\u0026     srvbuildres -r /conf/authref_ase_bs.rs"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 14364,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-09-17T15:29:57.856472766Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "d0170542d5ccd97676c564b5501e02a13f0449254affe7ea0cf9d6313c739012",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "c37aec68cbe0a9ab3ef6c2b37a14d481ae7ebace63a6ae70c3d4fdab0b5d2029",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.9",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:09",
        "NetworkID": "74866362417b7864ebe262d001359e5f0e5dc2777adc976acf8797a220ac31a3",
        "PortMapping": null,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/f8013de9aa63",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/f8013de9aa63d82a393409824ee2105a81a7f6172323a90ca490d6b726c7d3c7/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/f8013de9aa63d82a393409824ee2105a81a7f6172323a90ca490d6b726c7d3c7/hostname",
    "HostsPath": "/var/lib/docker/containers/f8013de9aa63d82a393409824ee2105a81a7f6172323a90ca490d6b726c7d3c7/hosts",
    "LogPath": "/var/lib/docker/containers/f8013de9aa63d82a393409824ee2105a81a7f6172323a90ca490d6b726c7d3c7/f8013de9aa63d82a393409824ee2105a81a7f6172323a90ca490d6b726c7d3c7-json.log",
    "Name": "/jolly_turing",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": null,
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": null,
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ]
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [],
    "Config": {
        "Hostname": "df10d6e2cabf",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": null,
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "PKG_BIN=W_Apache_v2.0.65",
            "PKG_NAME=W_Apache_v2.0.65"
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "yum -y install libaio \u0026\u0026 mkdir -p /install/ \u0026\u0026 source /root/.bashrc \u0026\u0026     cd /install \u0026\u0026 curl -o ASE_15.7_SP134_LinX64_ASESERV1570134_0-20011142.TGZ \"http://stargate/ASE_15.7_SP134_LinX64_ASESERV1570134_0-20011142.TGZ\" \u0026\u0026     mkdir -p /tmp \u0026\u0026 ls -la \u0026\u0026 tar zxf ASE_15.7_SP134_LinX64_ASESERV1570134_0-20011142.TGZ \u0026\u0026     ls -la \u0026\u0026     cd ebf24647 \u0026\u0026 ./setup.bin -f /install/installation_ASE.properties -i silent -DAGREE_TO_SYBASE_LICENSE=true -DRUN_SILENT=true \u0026\u0026     yum clean all \u0026\u0026     rm -rf /install/ \u0026\u0026 rm -rf /tmp/* \u0026\u0026     . /opt/sybase/na/syb_serv64-15.7.0/SYBASE.sh \u0026\u0026     echo \"::1 sybaseserver\" \u003e\u003e /etc/hosts \u0026\u0026     srvbuildres -r /conf/authref_ase.rs \u0026\u0026     srvbuildres -r /conf/authref_ase_bs.rs"
        ],
        "Image": "d0170542d5ccd97676c564b5501e02a13f0449254affe7ea0cf9d6313c739012",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": [],
        "Labels": {}
    }
}
]
```

sudo tail -f /var/log/upstart/docker.log | grep fecff03d9246

```
INFO[953505] Container fecff03d9246 failed to exit within 10 seconds of kill - trying direct SIGKILL 
INFO[953513] DELETE /v1.20/containers/fecff03d9246?force=1 
INFO[953513] GET /v1.18/containers/fecff03d9246fb0ef9151e65f3466a3dc5ca03eba898d136cf26886257c4e1d3/json 
INFO[953523] Container fecff03d9246 failed to exit within 10 seconds of kill - trying direct SIGKILL 
```

----------END REPORT ---------
Is there another way to kill it ?

my docker version
Docker version 1.8.1, build d12ea79

thanks

sebastien

**Comment by relgames** [comment] 2015-12-04 10:48
I have the same issue with Docker 1.9.1 running in a docker-machine:

```
$ uname -a
Linux apollo 4.1.13-boot2docker #1 SMP Fri Nov 20 19:05:50 UTC 2015 x86_64 GNU/Linux
```

```
$ docker info
Containers: 18
Images: 171
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 207
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: apollo
ID: ZOGY:FWTU:BEWH:DMPW:Y77F:RZEM:AQPW:DHSC:MQIM:VNUX:2RO7:JMTF
Debug mode (server): true
 File Descriptors: 22
 Goroutines: 41
 System Time: 2015-12-04T10:34:19.217314198Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
3dc78f76c0e5        composedepsonly_solr   "/opt/solr/bin/solr -"   17 hours ago        Up 14 minutes       0.0.0.0:8983->8983/tcp   composedepsonly_solr_1
```
docker inspect results http://pastebin.com/9UzCd1jc

docker stop 3dc78f76c0e5 just hangs.
sudo docker stop 3dc78f76c0e5 does not help.

Here is /var/log/docker.log:
```
time="2015-12-04T10:42:10.327585253Z" level=debug msg="Calling POST /v1.21/containers/3dc78f76c0e5/stop"
time="2015-12-04T10:42:10.327622228Z" level=info msg="POST /v1.21/containers/3dc78f76c0e5/stop?t=10"
time="2015-12-04T10:42:10.327785684Z" level=debug msg="Sending 15 to 3dc78f76c0e5ab4ab8d0faa1b75cbd4097a3345b217ecb7fa9695ffa1bea816b"
time="2015-12-04T10:42:20.328023906Z" level=info msg="Container 3dc78f76c0e5ab4ab8d0faa1b75cbd4097a3345b217ecb7fa9695ffa1bea816b failed to exit within 10 seconds of SIGTERM - using the force"
time="2015-12-04T10:42:20.328070842Z" level=debug msg="Sending 9 to 3dc78f76c0e5ab4ab8d0faa1b75cbd4097a3345b217ecb7fa9695ffa1bea816b"
time="2015-12-04T10:42:30.328326271Z" level=info msg="Container 3dc78f76c0e5 failed to exit within 10 seconds of kill - trying direct SIGKILL"
time="2015-12-04T10:43:15.134061722Z" level=debug msg="Calling POST /v1.21/containers/3dc78f76c0e5/stop"
time="2015-12-04T10:43:15.134102109Z" level=info msg="POST /v1.21/containers/3dc78f76c0e5/stop?t=10"
time="2015-12-04T10:43:15.134223185Z" level=debug msg="Sending 15 to 3dc78f76c0e5ab4ab8d0faa1b75cbd4097a3345b217ecb7fa9695ffa1bea816b"
time="2015-12-04T10:43:25.136188418Z" level=info msg="Container 3dc78f76c0e5ab4ab8d0faa1b75cbd4097a3345b217ecb7fa9695ffa1bea816b failed to exit within 10 seconds of SIGTERM - using the force"
time="2015-12-04T10:43:25.136250000Z" level=debug msg="Sending 9 to 3dc78f76c0e5ab4ab8d0faa1b75cbd4097a3345b217ecb7fa9695ffa1bea816b"
```

ps aux gives interesting results:
```
8983      1632  0.0  0.0      0     0 ?        Ss   10:22   0:00 [bash]
8983      1710 98.9  0.0      0     0 ?        Zl   10:22  21:39 [java] <defunct>
```
I think this is the container, because port 8983 is used by Solr.
And when I tried to sudo kill -9 1632 1710, nothing changed.

```
$ ps aux | grep 8983
root      1622  0.0  2.7 148180 28404 ?        Sl   10:22   0:00 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8983 -container-ip 172.17.0.5 -container-port 8983
8983      1632  0.0  0.0      0     0 ?        Ss   10:22   0:00 [bash]
8983      1710 99.0  0.0      0     0 ?        Zl   10:22  23:48 [java] <defunct>
docker    2588  0.0  0.0   9768   936 pts/0    S+   10:46   0:00 grep 8983
```

So the issue is somewhere in the kernel or (docker?) kernel module.

**Comment by relgames** [comment] 2015-12-04 10:51
http://askubuntu.com/questions/201303/what-is-defunct-for-a-process-and-why-it-doesnt-get-killed says those are zombie processes and are shown in a process table because parent process could not handle them properly. Parent process for my 2 zombies is docker daemon.

**Comment by candidtim** [comment] 2015-12-04 13:57
I have the same issue with Docker 1.9.1 (didn't observe it with 1.7 before). Same symptoms: `docker stop` on a container "hangs up", same thing with `docker rm -f` and same thing after I restart the docker service (while containers are reported as "Exited" I still cannot remove them). The only remedy is a system restart, after which the containers are in "Dead" status [and lose their original names] and I can remove them).

Please, let me know if you'd like additional info like `inspect` of a container or anything else (if I won't reinstall the whole thing before...)

**Comment by thaJeztah** [comment] 2015-12-05 18:42
@relgames based on the Java `<defunct>` and 99% cpu usage, that may be this issue; https://github.com/docker/docker/issues/18180. We're still looking into that, but it looks to be a kernel bug in the latest boot2docker version

**Comment by eryshev** [comment] 2015-12-30 15:38
Same issue with docker 1.7.1 of sbt on Ubuntu 15.10.
```json
docker inspect
[
{
    "Id": "292d007eb05d6544bb087c0d6ec97b33688faea7347bd61283b64900f173f52c",
    "Created": "2015-12-30T12:58:54.889493909Z",
    "Path": "/bin/docker-entrypoint.sh",
    "Args": [
        "zsh",
        "-l"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 21427,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-12-30T12:58:55.133130414Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "cc4b597e98075e65cfc86eb5cac07119c94042cfedfc12ca15811b8cd76403e5",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "911d35f62a128258d5f0df7bdfa587b0545a3e6a06a0114d7637627a56cfffa7",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.10",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:0a",
        "NetworkID": "68ca647b386e57935b556270a904bb0e6e6cf94c0fe2a56809beee7da8e749c7",
        "PortMapping": null,
        "Ports": {
            "9000/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "32769"
                }
            ],
            "9999/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/292d007eb05d",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/292d007eb05d6544bb087c0d6ec97b33688faea7347bd61283b64900f173f52c/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/292d007eb05d6544bb087c0d6ec97b33688faea7347bd61283b64900f173f52c/hostname",
    "HostsPath": "/var/lib/docker/containers/292d007eb05d6544bb087c0d6ec97b33688faea7347bd61283b64900f173f52c/hosts",
    "LogPath": "/var/lib/docker/containers/292d007eb05d6544bb087c0d6ec97b33688faea7347bd61283b64900f173f52c/292d007eb05d6544bb087c0d6ec97b33688faea7347bd61283b64900f173f52c-json.log",
    "Name": "/lib-listengine",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {
        "/data": "/home/xw/dev/xwing/lib-listengine",
        "/etc/profile.d/proxy.sh": "/etc/profile.d/proxy.sh",
        "/home/xw/.gitconfig": "/home/xw/.gitconfig",
        "/home/xw/.ivy2": "/home/xw/.ivy2",
        "/home/xw/.netrc": "/home/xw/.netrc"
    },
    "VolumesRW": {
        "/data": true,
        "/etc/profile.d/proxy.sh": true,
        "/home/xw/.gitconfig": true,
        "/home/xw/.ivy2": true,
        "/home/xw/.netrc": true
    },
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/etc/profile.d/proxy.sh:/etc/profile.d/proxy.sh",
            "/home/xw/dev/xwing/lib-listengine:/data",
            "/home/xw/.ivy2/:/home/xw/.ivy2",
            "/home/xw/.gitconfig:/home/xw/.gitconfig",
            "/home/xw/.netrc:/home/xw/.netrc",
        ],
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {
            "9000/tcp": [
                {
                    "HostIp": "",
                    "HostPort": ""
                }
            ]
        },
        "Links": [
            "/el:/lib-listengine/el",
            "/redis:/lib-listengine/redis"
        ],
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "Config": {
        "Hostname": "292d007eb05d",
        "Domainname": "",
        "User": "xw",
        "AttachStdin": true,
        "AttachStdout": true,
        "AttachStderr": true,
        "PortSpecs": null,
        "ExposedPorts": {
            "9000/tcp": {},
            "9999/tcp": {}
        },
        "Tty": true,
        "OpenStdin": true,
        "StdinOnce": true,
        "Env": [
            "HISTFILE=/data/.zsh_history",
            "DOCKER_NAME=lib-listengine",
            "DOCKER_PORT=",
            "PATH=/app/scala-2.11.6/bin:/app/sbt/bin:/app/sonar-runner-2.4/bin:/app/jdk1.8.0_51/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "http_proxy=http://bluecoatproxy.cpgrp.root.local:8080",
            "https_proxy=http://bluecoatproxy.cpgrp.root.local:8080",
            "LANGUAGE=en_US.utf8",
            "LC_ALL=en_US.utf8",
            "LC_CTYPE=en_US.utf8",
            "LC_COLLATE=en_US.utf8",
            "LC_TIME=en_US.utf8",
            "LC_NUMERIC=en_US.utf8",
            "LC_MONETARY=en_US.utf8",
            "LC_MESSAGES=en_US.utf8",
            "MM_CHARSET=en_US.utf8",
            "LANG=fr_FR.UTF-8",
            "TZ=Europe/Paris",
            "JAVA_HOME=/app/jdk1.8.0_51",
            "SCALA_HOME=/app/scala-2.11.6",
            "SBT_HOME=/app/sbt",
            "SONAR_RUNNER_HOME=/app/sonar-runner-2.4"
        ],
        "Cmd": [
            "zsh",
            "-l"
        ],
        "Image": "",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "/data",
        "Entrypoint": [
            "/bin/docker-entrypoint.sh"
        ],
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]
```


```bash
ps aux | grep 21427
xw       21427  0.0  0.0      0     0 ?        Ss   13:58   0:00 [zsh]
```

**Comment by robertfirek** [comment] 2016-01-05 12:31
It can be problem with AUFS. I had the similar problem with `[java] <defunct>`. I had to restart my machine to be able to control containers again.

**Comment by eryshev** [comment] 2016-01-05 13:17
I confirm a restart solves the problem but it still appear some times.

**Comment by marcbachmann** [comment] 2016-09-13 07:12
I just ran into a similar problem. But in my case the containers already got stopped and removed but some processes are still running. So it sounds more serious.

```
root@branches4:~# docker info
Containers: 15
 Running: 8
 Paused: 0
 Stopped: 7
Images: 14
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 164
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.5.7-docker-4
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.62 GiB
Name: branches4
ID: N5VB:74XK:VTTZ:NPJW:ZZLL:VSE2:CBZX:EFUM:V5KA:32MN:DPTS:FIY3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=scaleway(C2M)
Insecure Registries:
 127.0.0.0/8
```

**Comment by thaJeztah** [comment] 2016-09-14 12:11
@marcbachmann could you open a new issue for your case? Also, if possible, could you provide more information about the container you were running (what was running in the container, what options did you provide to start the container (e.g. privileged, etc)). I _do_ see that scalaway is using a custom kernel, which could play a factor in this.

**Comment by thaJeztah** [comment] 2016-12-15 11:33
Version 1.8.1 is very old now, this issue has been collecting various possibly unrelated comments. I'm going ahead and close this issue; please open a new issue if this is still a problem on the current (1.12) release. Docker 1.13 will also allow you to set `--init` on containers to automatically have an init / zombie reaper installed in the container.

**Closed by thaJeztah** 2016-12-15 11:33 UTC
Labels: area/runtime, kind/bug, version/1.8

**Comment by marcbachmann** [comment] 2016-12-15 14:49
👍 I'll create an issue when this problem occurs again.
