### ISSUE TITLE
SetNetworkBootstrapKeys: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker#24406] opened 2016-07-07 07:29 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   8b72f10-unsupported
 Built:        Wed Jun 29 06:15:22 2016
 OS/Arch:      linux/amd64
 Experimental: true
​
Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   ad44f49-unsupported
 Built:        Wed Jul  6 02:40:54 2016
 OS/Arch:      linux/amd64
 ```

Server: https://github.com/docker/docker/commit/ad44f49470bec84143ce73f51698bc9bbb501425

The client version should be unrelated to the issue

**Output of `docker info`:**
```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 137
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 163
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host null overlay bridge
Swarm: active
 NodeID: b5icgbjvy2bimk78g0wu65qwo
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:0654f9b254b966315063adc91d6ad298b8147c12a6184dfe5ad878a068241941
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: ws01
ID: SN3T:CNK6:JKQD:54CY:XKF2:BRX3:CIRU:DQBT:6DVZ:VWQ2:Q5ET:F23L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 119
 System Time: 2016-07-07T01:31:16.207468965Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. Create a swarm cluster (just single node is enough)
2. Wait for hours. 

When I hit the issue, I was not running any service, although perhaps running some non-service containers.

**Describe the results you received:**
```
DEBU[43206] Adding key 45455                             
DEBU[43206] Primary Key 9c664                            
DEBU[43206] (*Agent).run exited                           module=agent
panic: runtime error: index out of range

goroutine 77 [running]:
panic(0x1ae9c40, 0xc82000e0b0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/libnetwork.(*controller).getPrimaryKeyTag(0xc82029a690, 0x1f3a4e0, 0x10, 0x0, 0x0, 0x0, 0x3)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/agent.go:312 +0x2ab
github.com/docker/libnetwork.(*controller).handleKeyChange(0xc82029a690, 0xc82208a2a0, 0x3, 0x4, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/agent.go:141 +0x766
github.com/docker/libnetwork.(*controller).SetKeys(0xc82029a690, 0xc82208a2a0, 0x3, 0x4, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/controller.go:270 +0x35f
github.com/docker/docker/daemon.(*Daemon).SetNetworkBootstrapKeys(0xc82036da00, 0xc82208a2a0, 0x3, 0x4, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/network.go:175 +0x6d
github.com/docker/docker/daemon/cluster/executor/container.(*executor).SetNetworkBootstrapKeys(0xc8208dd980, 0xc822153ee0, 0x3, 0x4, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/cluster/executor/container/executor.go:136 +0x2e1
github.com/docker/swarmkit/agent.(*Agent).handleSessionMessage(0xc820430070, 0x7f428e563d98, 0xc820b695c0, 0xc820f0a280, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/agent/agent.go:265 +0x5ca
github.com/docker/swarmkit/agent.(*Agent).run(0xc820430070, 0x7f428e563d98, 0xc820b695c0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/agent/agent.go:170 +0xbe6
created by github.com/docker/swarmkit/agent.(*Agent).Start
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/agent/agent.go:81 +0x37d
```

**Describe the results you expected:**
It should not panic.

**Additional information you deem important (e.g. issue happens only occasionally):**
- I could not reproduce the issue.
- Maybe the discussion should be moved to docker/libnetwork or docker/swarmkit, but I am not sure yet.

**Comment by thaJeztah** [comment] 2016-07-12 00:27
ping @mavenugo PTAL

**Comment by mavenugo** [comment] 2016-07-12 01:00
@sanimej It seems the issue is seen during key rotation. Can you PTAL ?

**Comment by sanimej** [comment] 2016-07-12 17:29
@AkihiroSuda Did you initialize the cluster with a rc2 or older binary and then upgraded to the current version ? After RC2 one of the change was to generate separate keys for overlay data encryption. If the cluster was initialized with an earlier binary it won't have those keys and could cause this panic during key rotation.

Please create a new cluster with RC3 or the latest master docker and confirm this crash is not seen ?

**Comment by aaronlehmann** [comment] 2016-07-12 19:24
@sanimej: We should update the code to check for for this condition instead of panicing. Even though the keys should be created by default, I think robustness when dealing with objects created by a previous version is important.

**Comment by AkihiroSuda** [comment] 2016-07-13 09:44
@sanimej perhaps so, and I'm not seeing the issue after re-init.

**Comment by aaronlehmann** [comment] 2016-08-03 21:53
Merged a change in libnetwork that makes this code more defensive: docker/libnetwork#1371.

It shouldn't be possible to trigger the panic anyway with a cluster bootstrapped in Docker 1.12.0.

**Closed by aaronlehmann** 2016-08-03 21:53 UTC
Labels: area/swarm, group/networking, kind/bug, priority/P2, version/master
