### ISSUE TITLE
permission denied | Error response from daemon: Cannot start container 

### ISSUE THREAD

**Issue by Brandl** [docker/docker#18967] opened 2015-12-29 14:59 UTC
Description of problem:
I can't start any containers with the command docker run [...], even really simple one like:
`# docker run busybox`

Produce the following output:
`permission denied
Error response from daemon: Cannot start container beb4524b4f8a372d5eacdf6111d17053df0099d51f0824677fd137a97d277965: [8] System error: permission denied`

`docker version`:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Sun Nov 22 00:15:15 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Sun Nov 22 00:15:15 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 5
Images: 21
Server Version: 1.9.1
Storage Driver: btrfs
 Build Version: Btrfs v4.3.1
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.5-1-ARCH
Operating System: Arch Linux (containerized)
CPUs: 4
Total Memory: 7.679 GiB
Name: J3XYZ
ID: 7AQW:SMAM:NRQM:UU3P:FLJ2:XYUM:E66X:RPBS:BISE:4CDP:2NKB:GPBK
```

`uname -a`:
`Linux J3XYZ 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):
Lenovo X250

How reproducible:
docker run xyz

Steps to Reproduce:
1. sudo yaourt docker (->community/docker)
2. systemctl start docker
3. sudo docker run busybox

Actual Results:

```
permission denied
Error response from daemon: Cannot start container 03ffb7da4d1f0e5fa04d6e254d2aa67f0d36e31cab858a01c1f56f2bb165b97d: [8] System error: permission denied
```

Expected Results:
A running container, obviously :)

Additional info:
Arch, btrfs, luks filesystem

**Comment by maxmeyer** [comment] 2016-01-02 20:18
The same here. Only the underlying hardware is different. I also run Arch Linux, BTRFS on USB-HDDs.

Command

    docker run -it feduxorg/centos

Information

    $ docker version
    Client:
    Version:      1.9.1
    API version:  1.21
    Go version:   go1.5.1
    Git commit:   a34a1d5-dirty
    Built:        Sun Nov 22 00:15:15 UTC 2015
    OS/Arch:      linux/amd64
    
    Server:
    Version:      1.9.1
    API version:  1.21
    Go version:   go1.5.1
    Git commit:   a34a1d5-dirty
    Built:        Sun Nov 22 00:15:15 UTC 2015
    OS/Arch:      linux/amd64
  
    $ docker info
    Containers: 1
    Images: 63
    Server Version: 1.9.1
    Storage Driver: btrfs
    Build Version: Btrfs v4.3.1
    Library Version: 101
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.3.3-2-ARCH
    Operating System: Arch Linux (containerized)
    CPUs: 4
    Total Memory: 3.853 GiB
    Name: hostname
    ID: RDOC:QWIJ:4BXZ:PLAG:Z2PQ:RA2L:NPLD:OYK7:A2L5:3BKD:OJXG:DDYA
  
    $ uname -a
    Linux idefix.in.fedux.org 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux

Output

      Jan 02 19:42:28 hostname docker[454]: time="2016-01-02T19:42:28.956221642+01:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/b6abf4900b722556e7e2582119ebd61454564c1e2224a0634d3ad2ea066ecd38/shm: invalid argument\nfailed to umount /var/lib/docker/containers/b6abf4900b722556e7e2582119ebd61454564c1e2224a0634d3ad2ea066ecd38/mqueue: invalid argument"
    Jan 02 19:42:28 hostname docker[454]: time="2016-01-02T19:42:28.956808309+01:00" level=error msg="Handler for POST /v1.21/containers/b6abf4900b722556e7e2582119ebd61454564c1e2224a0634d3ad2ea066ecd38/start returned error: Cannot start container b6abf4900b722556e7e2582119ebd61454564c1e2224a0634d3ad2ea066ecd38: [8] System error: permission denied"

**Comment by maxmeyer** [comment] 2016-01-02 21:44
It helps. I started `docker daemon` manually. Here's the output.

~~~
INFO[0144] POST /v1.21/containers/create
DEBU[0146] Registering new volume reference: driver , name 258b2d337cb32804f5f19a5804496ce34e2056ba639c2c3549398b6958d11205
DEBU[0146] Incrementing volume reference: driver local, name 258b2d337cb32804f5f19a5804496ce34e2056ba639c2c3549398b6958d11205
DEBU[0146] Creating dest directory: /var/lib/docker/volumes/258b2d337cb32804f5f19a5804496ce34e2056ba639c2c3549398b6958d11205/_data
DEBU[0146] Calling TarUntar(/var/lib/docker/btrfs/subvolumes/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/var/ssh, /var/lib/docker/volumes/258b2d337cb32804f5f19a5804496ce34e2056ba639c2c3549398b6958d11205/_data)
DEBU[0146] TarUntar(/var/lib/docker/btrfs/subvolumes/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/var/ssh /var/lib/docker/volumes/258b2d337cb32804f5f19a5804496ce34e2056ba639c2c3549398b6958d11205/_data)
DEBU[0146] Registering new volume reference: driver local, name 2fb4efde15f7b00701911c4cf141d57b5bb2bf8e26deb521e6d91b5f3dc2794a
DEBU[0146] Incrementing volume reference: driver local, name 2fb4efde15f7b00701911c4cf141d57b5bb2bf8e26deb521e6d91b5f3dc2794a
DEBU[0146] Creating dest directory: /var/lib/docker/volumes/2fb4efde15f7b00701911c4cf141d57b5bb2bf8e26deb521e6d91b5f3dc2794a/_data
DEBU[0146] Calling TarUntar(/var/lib/docker/btrfs/subvolumes/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/run, /var/lib/docker/volumes/2fb4efde15f7b00701911c4cf141d57b5bb2bf8e26deb521e6d91b5f3dc2794a/_data)
DEBU[0146] TarUntar(/var/lib/docker/btrfs/subvolumes/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/run /var/lib/docker/volumes/2fb4efde15f7b00701911c4cf141d57b5bb2bf8e26deb521e6d91b5f3dc2794a/_data)
DEBU[0146] Registering new volume reference: driver local, name bc30f933b8c7f07d49027072389a14558111048fa590f975f71ef71098bdd426
DEBU[0146] Incrementing volume reference: driver local, name bc30f933b8c7f07d49027072389a14558111048fa590f975f71ef71098bdd426
DEBU[0146] Registering new volume reference: driver local, name e7413e6e150aa837cefb57828c987a1234a930ecaf9e630c7b5d1d6c3c699359
DEBU[0146] Incrementing volume reference: driver local, name e7413e6e150aa837cefb57828c987a1234a930ecaf9e630c7b5d1d6c3c699359
DEBU[0146] Creating dest directory: /var/lib/docker/volumes/e7413e6e150aa837cefb57828c987a1234a930ecaf9e630c7b5d1d6c3c699359/_data
DEBU[0146] Calling TarUntar(/var/lib/docker/btrfs/subvolumes/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/tmp, /var/lib/docker/volumes/e7413e6e150aa837cefb57828c987a1234a930ecaf9e630c7b5d1d6c3c699359/_data)
DEBU[0146] TarUntar(/var/lib/docker/btrfs/subvolumes/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/tmp /var/lib/docker/volumes/e7413e6e150aa837cefb57828c987a1234a930ecaf9e630c7b5d1d6c3c699359/_data)
DEBU[0146] Registering new volume reference: driver local, name 7b5b05b017767d51e16b12e1b8335f18e93d3678c3e24178f1bb61f99c024a7a
DEBU[0146] Incrementing volume reference: driver local, name 7b5b05b017767d51e16b12e1b8335f18e93d3678c3e24178f1bb61f99c024a7a
DEBU[0146] Calling POST /v1.21/containers/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/attach
INFO[0146] POST /v1.21/containers/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/attach?stderr=1&stdin=1&stdout=1&stream=1
DEBU[0146] attach: stdin: begin
DEBU[0146] attach: stdout: begin
DEBU[0146] attach: stderr: begin
DEBU[0146] Calling POST /v1.21/containers/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/start
INFO[0146] POST /v1.21/containers/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/start
DEBU[0146] Assigning addresses for endpoint berserk_mcclintock's interface on network bridge
DEBU[0146] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])
DEBU[0146] Assigning addresses for endpoint berserk_mcclintock's interface on network bridge
WARN[0146] exit status 1
DEBU[0146] attach: stdout: end
DEBU[0146] attach: stdin: end
DEBU[0146] attach: stderr: end
DEBU[0146] Closing buffered stdin pipe
DEBU[0146] Releasing addresses for endpoint berserk_mcclintock's interface on network bridge
DEBU[0146] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)
WARN[0146] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/shm: invalid argument
failed to umount /var/lib/docker/containers/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/mqueue: invalid argument
ERRO[0146] Handler for POST /v1.21/containers/50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879/start returned error: Cannot start container 50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879: [8] System error: permission denied
ERRO[0146] HTTP Error                                    err=Cannot start container 50d48d724880757d8ea971b142d74c706557f9c4e2711e6d3b7c22a14efc5879: [8] System error: permission denied statusCode=500
~~~

**Comment by maxmeyer** [comment] 2016-01-04 20:24
After switching the storage driver to `-s devicemapper` the container started. How can @Brandl and I help to find the underlying problem?

Sorry @thaJeztah to involving you directly, but that error was driving me crazy. Now I have a workaround using the `devicemapper` storage driver, but that does not really look like a solution for people using `docker` in production. Can you help us getting in touch with somebody who has the time/knowledge to dig deeper?

**Comment by thaJeztah** [comment] 2016-01-04 20:32
I think @vbatts runs on btrfs, perhaps he has some suggestions here

**Comment by maxmeyer** [comment] 2016-01-04 20:48
Thanks!

**Comment by vbatts** [comment] 2016-01-04 21:56
@maxmeyer for the sake of information, can you paste the output from running https://github.com/docker/docker/blob/master/contrib/check-config.sh ?
I'm not precisely sure where this EPERM or 'invalid argument' is bubbling up from

**Comment by maxmeyer** [comment] 2016-01-05 22:37
Here you are

~~~
info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: missing
- CONFIG_SECCOMP: enabled
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: missing
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled (as module)
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing
~~~

**Comment by ballPointPenguin** [comment] 2016-02-19 06:46
I believe I am seeing the same issue.
Arch linux. btrfs all the way down.

```
[root@TheBeast subvolumes]# docker info                                                                                                                                                        │··············································
Containers: 1                                                                                                                                                                                  │··············································
 Running: 0                                                                                                                                                                                    │··············································
 Paused: 0                                                                                                                                                                                     │··············································
 Stopped: 1                                                                                                                                                                                    │··············································
Images: 2                                                                                                                                                                                      │··············································
Server Version: 1.10.1                                                                                                                                                                         │··············································
Storage Driver: btrfs                                                                                                                                                                          │··············································
 Build Version: Btrfs v4.4                                                                                                                                                                     │··············································
 Library Version: 101                                                                                                                                                                          │··············································
Execution Driver: native-0.2                                                                                                                                                                   │··············································
Logging Driver: json-file                                                                                                                                                                      │··············································
Plugins:                                                                                                                                                                                       │··············································
 Volume: local                                                                                                                                                                                 │··············································
 Network: bridge null host                                                                                                                                                                     │··············································
Kernel Version: 4.4.1-2-ARCH                                                                                                                                                                   │··············································
Operating System: Arch Linux                                                                                                                                                                   │··············································
OSType: linux                                                                                                                                                                                  │··············································
Architecture: x86_64                                                                                                                                                                           │··············································
CPUs: 4                                                                                                                                                                                        │··············································
Total Memory: 15.37 GiB                                                                                                                                                                        │··············································
Name: TheBeast                                                                                                                                                                                 │··············································
ID: LAWN:HW5J:LSV6:T5Z4:7IK6:JOIS:T7WR:DQW7:36XT:KPOM:ZAHR:LSCW                                                                                                                                │··············································
Debug mode (server): true                                                                                                                                                                      │··············································
 File Descriptors: 11                                                                                                                                                                          │··············································
 Goroutines: 27                                                                                                                                                                                │··············································
 System Time: 2016-02-19T00:43:39.740323983-06:00                                                                                                                                              │··············································
 EventsListeners: 0                                                                                                                                                                            │··············································
 Init SHA1: f00b84100ee66b5f583bbc59f9359ec4492fb6b5                                                                                                                                           │··············································
 Init Path: /usr/lib/docker/dockerinit                                                                                                                                                         │··············································
 Docker Root Dir: /var/lib/docker                                                                                                                                                              │··············································
[root@TheBeast subvolumes]# docker run hello-world                                                                                                                                             │··············································
permission denied                                                                                                                                                                              │··············································
docker: Error response from daemon: Container command could not be invoked..
```

**Comment by ballPointPenguin** [comment] 2016-02-19 08:09
It seems we are all running arch linux on btrfs with 4.x kernels.
Can anyone confirm the absence or presence of this issue on any of those variables in isolation?
ie kernel 4.x, btrfs filesystems, or arch linux?

**Comment by ballPointPenguin** [comment] 2016-02-19 08:13
I just ran with
```
docker daemon -D -s devicemapper
```
and it seems to be working. Thanks @maxmeyer . That's good enough for me right now.
I am still interested in helping or at least learning more about this issue however.

**Comment by PhML** [comment] 2016-02-24 20:25
Same configuration, same issue and same solution here. If you need more information, just ask.

**Comment by 14rcole** [comment] 2016-05-27 00:49
I'm getting the same issue on Fedora 23.
`[14rcole@fedora docker] $ sudo docker info
[sudo] password for rycole: 
Containers: 10
Images: 15
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-293966-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.667 GB
 Data Space Total: 107.4 GB
 Data Space Available: 44.98 GB
 Metadata Space Used: 2.064 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107 (2015-09-05)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.3-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
CPUs: 4
Total Memory: 11.44 GiB
Name: 14rcole.fedora
ID: MXHU:25N2:RHTF:6EKP:JITG:BYBR:BTOV:G56F:CKBT:IQQJ:OCQ2:WCE2
Debug mode (server): true
 File Descriptors: 21
 Goroutines: 40
 System Time: 2016-05-26T20:46:47.774142101-04:00
 EventsListeners: 0
 Init SHA1: aedd0c57159cf055ee19eb48fb00402562460078
 Init Path: /usr/libexec/docker/dockerinit
 Docker Root Dir: /var/lib/docker
`
So I'm kernel 4.x but not arch or btrfs
The command
`docker daemon -D -s devicemapper`
solves the issue but I see it more as a temporary workaround than a fix

**Comment by thaJeztah** [comment] 2016-05-27 20:30
@14rcole your regular graph driver is also btrfs?

**Comment by wzxjohn** [comment] 2016-05-30 12:47
I'm trying to use docker on CentOS 7 and get the same question. It seems I have to disable seLinux in host os. Can I do something else to let my docker work without disable my seLinux?

**Comment by indiv0** [comment] 2016-07-03 03:49
Getting the same issue with btrfs, Arch Linux, and kernel 4.6.2-1-ARCH.

```
─── docker info
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 4
Server Version: 1.11.2
Storage Driver: btrfs
 Build Version: Btrfs v4.5.3
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.2-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.795 GiB
Name: pirate
ID: OWEL:KLST:3UQR:QISO:KOUT:36DM:72DQ:ZNNV:CONF:REX4:JVDE:QGEB
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Comment by sevagh** [comment] 2016-07-22 11:01
I'm having this same issue in Fedora 24 (RUN apt-get update -y - Permission denied). Following @14rcole's suggestion to run the daemon with allows it to work for now:

     docker daemon -D -s devicemapper

**Comment by indiv0** [comment] 2016-07-26 17:47
Docker started working for me a few days ago again. Not sure what I did to fix it. I re-installed it a few times and wiped `/var/lib/docker`, and it appears to have resolved itself.

**Comment by johnny1952** [comment] 2016-12-15 11:24
try close SELinux by:
setenforce 0

**Comment by aker** [comment] 2017-01-20 00:57
The same to me,i fixed it by the common:

# ls -aZ /usr/bin/docker*
-rwxr-xr-x. root root system_u:object_r:docker_exec_t:s0 /usr/bin/docker
-rwxr-xr-x. root root system_u:object_r:bin_t:s0 /usr/bin/docker-current
-rwxr-xr-x. root root system_u:object_r:bin_t:s0 /usr/bin/docker-storage-setup

# sudo chcon -t docker_exec_t /usr/bin/docker*
# sudo systemctl restart docker

**Comment by aCandidMind** [comment] 2017-02-23 16:22
@aker's chcon -t docker_exec_t fixed it for my VM which was cloned from another one. Maybe that's why this type was gone.

I'm not using btrfs. It's likely some people in this issue simply have SELinux problems.

I also tried running the docker daemon from outside the docker systemd unit which made it work prior to the SELinux fix. Got this from the likely [very related issue #17475 here](https://github.com/docker/docker/issues/17475#issuecomment-152103001). But since this wasn't a permant fix, I'm very happy to have found @aker's fix. May I ask where you got this from? Especially since you're saying it's common.

**Comment by cpuguy83** [comment] 2017-02-24 13:53
@aCandidMind How did you install docker?

The docker RPM's include an selinux policy that does exactly what you have done with the `chcon`. This should not be an issue with the official packages.

**Comment by cpuguy83** [comment] 2017-02-24 13:56
I see all these problems seem related to packaging with arch, which is non-official. This is not something that can be fixed here.

Docker supplies a policy here: https://github.com/docker/docker/tree/master/contrib/selinux/docker-engine-selinux
This is packaged as `docker-engine-selinux` on our yum repos for each supported platform.

Specifically with changes in 1.11, it was required to set `docker_exec_t` on `/usr/bin/dockerd` which was a new binary introduced by splitting the docker client (`docker`) and the docker daemon (`dockerd`).

Going to go ahead and close as this is not an issue that we can deal with here, but feel free to discuss.
Thanks all! 👼

**Closed by cpuguy83** 2017-02-24 13:56 UTC
Labels: area/storage/btrfs, version/1.9

**Comment by aCandidMind** [comment] 2017-03-14 10:30
Sorry for responding so late @cpuguy83.

I installed docker on my CentOS VM via ```yum install docker-engine*-1.9.1*``` from yum.dockerproject.org. ```yum list installed docker*``` yields:

	docker-engine.x86_64                   1.9.1-1.el7.centos            @dockerrepo
	docker-engine-selinux.noarch           1.9.1-1.el7.centos            @dockerrepo

So the 1.11 split of binaries wasn't the cause in my case.

As I said above, I guess some people in this issue here had problems with the systemd/SELinux  co-operation with docker rather than Arch or btrfs problems (because they said they're not using Arch) which makes this issue have two groups of setups. On the one hand Arch and/or btrfs and on the other hand systemd and/or SELinux not using Arch or btrfs (including me). See that @14rcole's [comment](https://github.com/docker/docker/issues/18967#issuecomment-222033890) and @sevagh's [comment](https://github.com/docker/docker/issues/18967#issuecomment-234516291) mention that they are using Fedora and not Arch. And you could read into their comments that running the daemon on their own without systemd resolved their problems. Same as the [related issue #17475](https://github.com/docker/docker/issues/17475#issuecomment-152103001) I mentioned above. Another CentOS user pointing in the SELinux direction can be found in our [current thread here](https://github.com/docker/docker/issues/18967#issuecomment-222485405). My cloned CentOS VM (cloned from an existing VirtualBox CentOS VM, maybe that caused my SELinux problem) is also not Arch.

Just putting this here for completeness for the next user that runs into that error response.

**Comment by cpuguy83** [comment] 2017-03-14 12:47
@aCandidMind I really can't speak for the 1.9 policies, it is very likely those policies failed to load and the rpm installation itself would not fail itself and only give a warning since the base packages, `selinux-policy`, have changed so much and centos is a rolling release.
