### ISSUE TITLE
stopping a docker run displays <none> image entries    

### ISSUE THREAD

**Issue by askb** [docker/docker#16812] opened 2015-10-07 09:32 UTC
Description of problem: 
Stopping a "docker run" with ctrl+c or sigint, causes incorrect entries output by "docker image". 

docker version:
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

docker info:
$ docker info
Containers: 6
Images: 123
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 135
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.689 GiB
Name: laptop-i5537
ID: Q7CC:FNYP:4OWW:Q4FW:HHVL:KORD:AS6L:6AGN:6I3D:LRZG:NBWO:ZDXC
WARNING: No swap limit support

$ uname -a
Linux laptop-i5537 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

How reproducible:
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz
Unable to find image 'nate/dockviz:latest' locally
Pulling repository docker.io/nate/dockviz
0806e484332b: Pulling dependent layers 
053471c3e570: Download complete 
ab97cd484443: Pulling metadata .... (SIGINT / ^c)

Steps to Reproduce:
1. docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz
(have experienced this issue while running different images, not limited to the above cmd or image)
2. ctrl+c ... sigint
3. docker images

Actual Results:
$ docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
devbox              1.0                 d17a89ba7b49        3 minutes ago       717.5 MB
<none>              <none>              ee137de878c7        18 minutes ago      717.5 MB
<none>              <none>              d43941007817        23 hours ago        1.911 GB
docs/base           latest              2b38a347c927        3 weeks ago         591.3 MB
ubuntu              14.04               91e54dfb1179        6 weeks ago         188.4 MB
<none>              <none>              ab97cd484443        7 weeks ago         5.873 MB

Expected Results:
The docker run command is interrupted, these entries in should not be displayed in docker images: <none> and date created is incorrect.

**Comment by duglin** [comment] 2015-10-07 11:52
@askb during a 'docker pull' if the cli loses connectivity with the daemon the pulled images are still downloaded. This is either a bug or a feature depending on your point of view. I can understand why some people might expect the ctrl-c to stop everything and roll it all back, but given that downloading images could be a long running task, its very possible that the CLI might not be able to keep its http connection open the entire time. So in this case continuing to download is probably the best option. 

As for the timestamp, its the timestamp of when the image was created not when it was downloaded.

I'm going to close this issue because, unless I'm not understanding your issue, I believe this is working as designed. Feel free to reopen if I didn't understand your concerns.

**Closed by duglin** 2015-10-07 11:52 UTC

**Comment by askb** [comment] 2015-10-07 12:12
@duglin - I mostly agree with your point on the client losing connectivity and roll-back issue not happening as docker daemon continues to downloading the image/layer. It would be nice to have feature. Maybe this could either be removed or at-least displayed correct with appropriate repository name and the tag from the CLI.

**Comment by duglin** [comment] 2015-10-07 12:19
@askb what do you mean by "display correct with appropriate repository name" ?  Which name isn't correct now?

**Comment by askb** [comment] 2015-10-07 12:44
@duglin sorry, I missed formatting the content while opening the issue, now it is updated. My question was more related to why "docker images" or CLI displays the image name as `<name>` instead of the correct name should be `nate/dockviz`, as the daemon would continue in the background.

**Comment by duglin** [comment] 2015-10-07 13:12
If you do "docker images" after the daemon has had time to download all of the layers then I would think that "0806e484332b" should have the tag "nate/dockviz", which is what I see. Can you verify that? 
As for the other layers, those are probably intermediate layers that were created during the building of "nate/dockviz" and where never given a formal tag.

**Comment by askb** [comment] 2015-10-07 13:54
@duglin Yes, the output of docker images show up as "nate/dockviz" image downloaded once its completed in the background. However from the output from dockviz indicates that image id `ab97cd484443` is seen as `<none>` and the output is persistent as a with separate entry in "docker images" 
 
```
$ dockviz images -t | grep --color -E "^|ee137de878c7|d43941007817|ab97cd484443"

└─053471c3e570 Virtual Size: 5.9 MB
  └─ab97cd484443 Virtual Size: 5.9 MB ===>  id is displayed as <none> below output
    └─0806e484332b Virtual Size: 5.9 MB Tags: nate/dockviz:latest

```

To resolve this I removed `d43941007817` and `ee137de878c7`  manually, using `docker rmi`. Please do let me know its an expected behavior, i'll will not re-open the issue.
 
```
$ docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
devbox              1.0                 d17a89ba7b49        3 hours ago         717.5 MB
<none>              <none>              ee137de878c7        3 hours ago         717.5 MB
dry-run-test        latest              94a2fae0b514        4 hours ago         1.911 GB
docker-dev          dry-run-test        94a2fae0b514        4 hours ago         1.911 GB
docs-base           dry-run-test        30ca5111a589        25 hours ago        634.2 MB
<none>              <none>              d43941007817        26 hours ago        1.911 GB
docs/base           latest              2b38a347c927        3 weeks ago         591.3 MB
ubuntu              14.04               91e54dfb1179        6 weeks ago         188.4 MB
<none>              <none>             ab97cd484443        7 weeks ago         5.873 MB
nate/dockviz        latest              0806e484332b        7 weeks ago         5.873 MB
```

**Comment by duglin** [comment] 2015-10-07 14:05
@askb if you do: `docker history 0806e484332b` you'll see that the image (or layer) `ab97cd484443` was created because of the `ENV` step in a Dockerfile. This means that its just an intermediate layer that was created during the build process and never given a formal tag - hence the "none" label you see. Docker will only persist tags if you explicitly give one to an image.  Try to do a build and look at all of the images/layers created - you'll see the same thing.

**Comment by askb** [comment] 2015-10-07 14:55
@duglin I agree that  image (or layer) `ab97cd484443` got created temporarily because of instruction in the Dockerfile, which is perfectly ok to be displayed temporarily, maybe its best to be removed or replaced with the updated id `0806e484332b` of the completed image (top layer) and the id `ab97cd484443` should not persist after in the output of `docker images` once the complete image is pulled, which could be potentially confusing for admins. 

I have removed the image id's manually and will redo the build tomorrow. Many thanks.
