### ISSUE TITLE
Docker pull performance issues

### ISSUE THREAD

**Issue by bobrik** [docker/docker#10140] opened 2015-01-16 12:15 UTC
I'm downloading layer from my local registry over http (https registry redirects to s3-like http service).

I ran `perf record` on docker daemon, here's what I've got in `perf report`:

![per report](http://i.imgur.com/I02jZiM.png)

42%+ of the time some crypto happens. Why do I need it?

Next, I noticed that after layer is fully downloaded, it takes a while for docker to return to shell prompt. I fired `strace` at docker daemon, here's what I've got (bazillions of lines like):

```
[pid  4905] lstat("/var/lib/docker/devicemapper/mnt/37974925ff2973a484752901638140597ee004ac3f9897c89739f4e1e1b53d87/rootfs/var/www/<redacted>/profile/like.png", {st_mode=S_IFREG|0644, st_size=732, ...}) = 0
[pid  4905] lstat("/var/lib/docker/devicemapper/mnt/37974925ff2973a484752901638140597ee004ac3f9897c89739f4e1e1b53d87/rootfs/var/www/<redacted>/profile/like.png", {st_mode=S_IFREG|0644, st_size=732, ...}) = 0
[pid  4905] lgetxattr("/var/lib/docker/devicemapper/mnt/37974925ff2973a484752901638140597ee004ac3f9897c89739f4e1e1b53d87/rootfs/var/www/<redacted>/profile/like.png", "security.capability", 0xc208ebbf80, 128) = -1 EOPNOTSUPP (Operation not supported)
[pid  4905] lstat("/var/lib/docker/devicemapper/mnt/37974925ff2973a484752901638140597ee004ac3f9897c89739f4e1e1b53d87/rootfs/var/www/<redacted>/profile/next.png", {st_mode=S_IFREG|0644, st_size=868, ...}) = 0
[pid  4905] lstat("/var/lib/docker/devicemapper/mnt/37974925ff2973a484752901638140597ee004ac3f9897c89739f4e1e1b53d87/rootfs/var/www/<redacted>/profile/next.png", {st_mode=S_IFREG|0644, st_size=868, ...}) = 0
[pid  4905] lgetxattr("/var/lib/docker/devicemapper/mnt/37974925ff2973a484752901638140597ee004ac3f9897c89739f4e1e1b53d87/rootfs/var/www/<redacted>/profile/next.png", "security.capability", 0xc208ae0000, 128) = -1 EOPNOTSUPP (Operation not supported)
[pid  4905] lstat("/var/lib/docker/devicemapper/mnt/37974925ff2973a484752901638140597ee004ac3f9897c89739f4e1e1b53d87/rootfs/var/www/<redacted>/profile-deleted.png", {st_mode=S_IFREG|0644, st_size=1329, ...}) = 0
[pid  4905] lstat("/var/lib/docker/devicemapper/mnt/37974925ff2973a484752901638140597ee004ac3f9897c89739f4e1e1b53d87/rootfs/var/www/<redacted>/profile-deleted.png", {st_mode=S_IFREG|0644, st_size=1329, ...}) = 0
[pid  4905] lgetxattr("/var/lib/docker/devicemapper/mnt/37974925ff2973a484752901638140597ee004ac3f9897c89739f4e1e1b53d87/rootfs/var/www/<redacted>/profile-deleted.png", "security.capability", 0xc208ae0080, 128) = -1 EOPNOTSUPP (Operation not supported)
[pid  4905] lstat("/var/lib/docker/devicemapper/mnt/37974925ff2973a484752901638140597ee004ac3f9897c89739f4e1e1b53d87/rootfs/var/www/<redacted>/restore-icon.png", {st_mode=S_IFREG|0644, st_size=911, ...}) = 0
[pid  4905] lstat("/var/lib/docker/devicemapper/mnt/37974925ff2973a484752901638140597ee004ac3f9897c89739f4e1e1b53d87/rootfs/var/www/<redacted>/restore-icon.png", {st_mode=S_IFREG|0644, st_size=911, ...}) = 0
```

Is there a point in doing this? Looks like noop to me. I have 65315 files in this layer.

```
web381 ~ # docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
web381 ~ # docker info
Containers: 3
Images: 64
Storage Driver: devicemapper
 Pool Name: docker-9:127-28311623-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 4.071 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 5.157 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.88 (2014-08-05)
Execution Driver: native-0.2
Kernel Version: 3.14.18-gentoo
Operating System: Gentoo/Linux
CPUs: 8
Total Memory: 7.791 GiB
Name: web381
ID: ISFY:2KV4:6HPK:Y3MD:LUCF:HKZN:LIRA:75ZN:MC35:FKE2:TBT4:EI7E
Debug mode (server): true
Debug mode (client): false
Fds: 12
Goroutines: 12
EventsListeners: 0
Init SHA1: b85dd0e9ff280256ab64d37b974a99e35976a109
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker
```

**Comment by bobrik** [comment] 2015-01-16 13:07
Btw, since we have pprof enabled via DEBUG flag, it could be useful to dump cpu profiles via api for further analysis.

**Comment by LK4D4** [comment] 2015-01-16 14:35
@bobrik `Lstats` was removed in master. There is significant performance boost in master now.
Some benchmarks here: #9445

**Comment by bobrik** [comment] 2015-01-16 14:44
Great, 1.4.2 should be much better then. But issue with crypto usage stays here.

**Comment by unclejack** [comment] 2015-01-16 17:35
@bobrik That's only sha256 hashing and it is required. Please provide the output of `cat /proc/cpuinfo` from that system where you're seeing this behavior.

This might be caused by the fact that the particular CPU you're using is missing some instructions. This could slow down the code significantly.

**Comment by bobrik** [comment] 2015-01-16 17:43
@unclejack why is it required?

```
processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Xeon(R) CPU E31230 @ 3.20GHz
stepping	: 7
microcode	: 0x14
cpu MHz		: 3192.844
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 6385.68
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

**Comment by unclejack** [comment] 2015-01-16 18:51
@bobrik Thanks for providing the cpuinfo output. Can you provide the pprof profiles, please?

**Comment by bobrik** [comment] 2015-01-16 20:02
@unclejack what exactly do you mean by pprof profiles? `/debug/pprof` http endpoints do not provide cpu profiling info as far as I know.

**Comment by bobrik** [comment] 2015-01-18 13:20
I hacked docker code to add endpoints to run `pprof.StartCPUProfile`:

* `/debug/pprof/cpu/start`
* `/debug/pprof/cpu/stop`

Results for the smaller image are here: http://bobrik.name/pprof001.svg
Results for the bigger image are here: http://bobrik.name/pprof002.svg

I also checked speed of my version (with profiling disabled) vs 1.4.1 for two images. The smaller is 477.7mb and the bigger is 1.766gb. Test was performed on the same bare metal machine.

|Image|Version|Try|Time|
|-----|-------|---|----|
|smaller|1.4.1|1|0m51.861s|
|smaller|1.4.1|2|0m51.986s|
|smaller|1.4.1|3|0m49.986s|
|smaller|master|1|0m30.426s|
|smaller|master|2|0m30.848s|
|smaller|master|3|0m28.736s|
|bigger|1.4.1|1|2m5.874s|
|bigger|1.4.1|2|2m11.110s|
|bigger|1.4.1|3|2m5.799s|
|bigger|master|1|1m35.189s|
|bigger|master|2|1m32.646s|
|bigger|master|3|1m30.214s|

**Comment by unclejack** [comment] 2015-02-02 08:41
@bobrik This seems to be fixed and pulls should be faster in Docker 1.5. I'll close the issue now.

Go 1.5 will also have improvements which will help speed up pulls.

Please feel free to comment.

**Closed by unclejack** 2015-02-02 08:41 UTC

**Comment by bobrik** [comment] 2015-02-03 08:02
1.5 is much better for pulls, thanks! :+1:

**Comment by l15k4** [comment] 2015-09-18 16:31
I'm using docker 1.6.2 and it takes 40 seconds to pull an image from a local docker-registry. The image is a `busybox + java + apache-spark` ... It has almost 700MB. But still, how come it can take so long?

```
FROM jeanblanchard/busybox-java:8

ENV SPARK_VERSION 1.5.0
ENV HADOOP_VERSION 2.6
ENV SPARK_PACKAGE ${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}
ENV SPARK_HOME /opt/spark-$SPARK_PACKAGE
ENV PATH $PATH:$SPARK_HOME/bin

RUN curl -jksL --retry 3 "http://www.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_PACKAGE}.tgz" | gunzip -c - | tar -xf - -C /opt

CMD ${SPARK_HOME}/bin/spark-class org.apache.spark.deploy.master.Master
```
