### ISSUE TITLE
Add ability to add multiple tags with docker build

### ISSUE THREAD

**Issue by niclashoyer** [docker/docker#863] opened 2013-06-09 20:03 UTC
I have some automated builds using `docker build` and a `Dockerfile`.

With `docker build -t <tag>` I can set a tag for a complete build, but it would be nice if it was possible to add multiple tags, so that one could add tags to commits after a `RUN` command.

~~Maybe a `TAG` command for the Dockerfile syntax?~~

**Comment by jfrazelle** [comment] 2015-02-26 03:06
https://github.com/docker/docker/issues/5603 https://github.com/docker/docker/issues/9641 https://github.com/docker/docker/issues/9844 are all duplicates of this

**Comment by Xerkus** [comment] 2015-04-26 23:34
@jfrazelle i fail to see how TAG directive in dockerfile is duplicate of multiple tags per image

**Comment by jesper** [comment] 2015-07-16 10:57
@jfrazelle - agreeing with @Xerkus, this is not a duplicate. I would like to see this feature as well.

**Comment by FnTm** [comment] 2015-08-03 10:20
Agree with @Xerkus , not a duplicate. +1 for this feature!

**Comment by thaJeztah** [comment] 2015-08-03 10:50
I agree that this is not a duplicate. I think the mention of a `TAG` instruction in the original description caused the confusion here. I'll strike that out for now and re-open.

Based on https://github.com/docker/docker/issues/863#issuecomment-50494032, I think the consensus was that multiple `-t` flags should be possible, thus `docker build -t image:foo -t image:bar -t image:latest .`

Note that the consensus was reached a *long* time ago; things may have changed, so me re-opening the issue is *no guarantee* that this will be implemented.

**Comment by crashvb** [comment] 2015-08-26 02:21
+1 for multiple `-t` flags

**Comment by mkubarycz** [comment] 2015-08-29 03:28
+1

**Comment by crashvb** [comment] 2015-08-29 23:35
I too would like multiple `-t` flags to be supported. I have a preference for specifying tags via arguments and would like to be able to do so in a single command call. I'm not sure that this issues directly relates to me, however, the solution proposed would seem to serve my needs.

**Comment by offlinehacker** [comment] 2015-10-21 00:20
Multiple tag support please

**Comment by thaJeztah** [comment] 2015-10-21 03:33
For those following this, theres an open pull request, that's currently being reviewed. It won't make it into the 1.9 release, but should be part of docker 1.10

https://github.com/docker/docker/issues/15780

**Closed** 2015-10-23 20:50 UTC
Labels: kind/feature
