### ISSUE TITLE
Is there some way to build the unique image?

### ISSUE THREAD

**Issue by allencloud** [docker/docker#12173] opened 2015-04-08 05:56 UTC
Hi,all

I wonder if two docker daemons on different hosts can build the same image with same image.ID when their Dockerfiles are exactly the same.

On a single docker daemon node, when docker build Dockerfile, docker daemon will check base_image_id and config information to  judge whether to use cache.

But on two nodes, docker daemons have no relationship with each other. Each one will generate image id when building the same Dockerfile.

I think unique image_ID is very useful in a cluster of docker registry which a lot of docker daemons need to access, especially in the aspect of disk space saving. 

Just a thought.

**Comment by thaJeztah** [comment] 2015-04-08 09:17
No, currently, I don't think that's possible. Image-ID's are a randomly generated, so won't match between hosts (see [graph/graph.go#L125](https://github.com/docker/docker/blob/72dfd6728fdba7b2a74d3a51de12806d2ec02697/graph/graph.go#L125))

There's work in progress for content-addressable, immutable digests (see https://github.com/docker/docker/issues/10740), as part of the new registry (https://github.com/docker/distribution), but (I think) those only apply to images *pushed* to a registry, not to locally built images that aren't pushed.

Docker save/load will preserve Image-ID's, so you should be able to save an image on one host (using [docker save](https://docs.docker.com/reference/commandline/cli/#save)) and [docker load](https://docs.docker.com/reference/commandline/cli/#load) that image on the other host.

However, I you're using a (private) registry, building the image on one host, "pushing" it to your registry and pulling the image on the other host would probably make more sense.

I'm going to close this issue, because this is not a bug. Feel free to continue the discussion here, on https://forums.docker.com/ or https://groups.google.com/forum/#!forum/docker-user.

**Closed by thaJeztah** 2015-04-08 09:17 UTC
Labels: kind/question
