### ISSUE TITLE
Watchtower cannot create container on more than 1 network: Container cannot be connected to network endpoints

### ISSUE THREAD

**Issue by dolanor** [docker/docker#29265] opened 2016-12-09 01:11 UTC
**Description**

I'm trying to patch watchtower to handle multiple networks on container update ( [My attempt](https://github.com/tuxago/watchtower/tree/net) ).
Once I had a "working" environment, the watchtower initiated the update of the image and then tried to launch a new container.

**Steps to reproduce the issue:**
1. Create a container  connected to more than 1 network based on an image from the hub you have write access to.
2. Update the image on the hub
3. Launch [tuxago/watchtower:net-bug](https://hub.docker.com/r/tuxago/watchtower/) container and check the logs

**Describe the results you received:**
```
watchtower_1  | time="2016-12-09T00:09:42Z" level=info msg="Stopping /projectweb_newimg_1 (e5821371721d080695b31c74694db15c2a200e1f0c35d92c6a6af7ebe052217f) with SIGTERM" 
watchtower_1  | time="2016-12-09T00:09:43Z" level=debug msg="Removing container e5821371721d080695b31c74694db15c2a200e1f0c35d92c6a6af7ebe052217f" 
watchtower_1  | time="2016-12-09T00:09:43Z" level=info msg="Starting /projectweb_newimg_1" 
watchtower_1  | time="2016-12-09T00:09:43Z" level=error msg="Error response from daemon: Container cannot be connected to network endpoints: projectweb_back, gate_front-tier" 
watchtower_1  | time="2016-12-09T00:14:43Z" level=info msg="Checking containers for updated images" 
```

**Describe the results you expected:** I shouldn't have any errors, and the new version of the container should be connected to both networks

**Additional information you deem important (e.g. issue happens only occasionally):**
It seems the message comes from https://github.com/docker/docker/blob/master/daemon/create.go#L293 , but before that, the code seems to indicate that it doesn't handle multiple network connections at all.
But it puzzles me, because launching a docker-compose with containers on multiple networks works. But maybe it doesn't use the same code path.

**Output of `docker version`:**
```Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Mon Dec  5 19:05:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Mon Dec  5 19:05:57 2016
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 19
 Running: 9
 Paused: 0
 Stopped: 10
Images: 244
Server Version: 1.13.0-rc3
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.662 GiB
Name: moondark
ID: X74M:MJKW:QVHL:Z5LC:O75P:HHZG:OY7T:CIC5:XHET:HBSJ:S7E3:FQGL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dolanor
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):** on my xps13 laptop

**Comment by thaJeztah** [comment] 2016-12-09 01:39
This is expected, when creating a container, you can only specify a single network. Subsequent networks can be attached after that (`docker network attach`, or the corresponding API call https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/connect-a-container-to-a-network)

If you check the daemon logs (in debug mode), you'll see that that is what docker-compose does as well.


Using this docker-compose.yml file;

```yaml
version: "2.1"
services:
  web:
    image: nginx:alpine
    networks:
      - network1
      - network2
networks:
  network1:
    external: true
  network2:
    external: true
```

These calls are made when running `docker-compose up`;

```
DEBU[0611] Calling GET /v1.24/info
DEBU[0611] Calling GET /v1.24/networks/network2
DEBU[0611] Calling GET /v1.24/networks/network1
DEBU[0611] Calling GET /v1.24/containers/json?all=0&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Ddocker%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
DEBU[0611] Calling GET /v1.24/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Ddocker%22%2C+%22com.docker.compose.service%3Dweb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
DEBU[0611] Calling GET /v1.24/images/nginx:alpine/json
DEBU[0611] Calling GET /v1.24/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Ddocker%22%2C+%22com.docker.compose.service%3Dweb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
DEBU[0611] Calling GET /v1.24/images/nginx:alpine/json
DEBU[0611] Calling GET /v1.24/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Ddocker%22%2C+%22com.docker.compose.service%3Dweb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
DEBU[0611] Calling GET /v1.24/images/nginx:alpine/json
DEBU[0611] Calling POST /v1.24/containers/create?name=docker_web_1
DEBU[0611] form data: {"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Env":[],"HostConfig":{"Binds":[],"Isolation":null,"Links":[],"LogConfig":{"Config":{},"Type":""},"NetworkMode":"network2","PortBindings":{},"VolumesFrom":[]},"Image":"nginx:alpine","Labels":{"com.docker.compose.config-hash":"2cbb121677126b3aefaa214218613c3b0754f5bafa8b310f137b11376f7a7bba","com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"docker","com.docker.compose.service":"web","com.docker.compose.version":"1.9.0"},"NetworkDisabled":false,"NetworkingConfig":{"EndpointsConfig":{"network2":{"Aliases":["web"],"IPAMConfig":{}}}},"OpenStdin":false,"StdinOnce":false,"Tty":false,"Volumes":{}}
DEBU[0611] container mounted via layerStore: /var/lib/docker/aufs/mnt/282a126333ca50f5d3cf88018815eb3f280deece2cf063780ba5eaff869dc4c7
DEBU[0611] Calling GET /v1.24/containers/ff20876f9f363f253a1135e54e9c591d8288707922ae9f0de26300c9753f5259/json
DEBU[0611] Calling POST /v1.24/networks/network2/disconnect
DEBU[0611] form data: {"Container":"ff20876f9f363f253a1135e54e9c591d8288707922ae9f0de26300c9753f5259"}
DEBU[0611] Calling POST /v1.24/networks/network2/connect
DEBU[0611] form data: {"Container":"ff20876f9f363f253a1135e54e9c591d8288707922ae9f0de26300c9753f5259","EndpointConfig":{"Aliases":["web","ff20876f9f36"]}}
DEBU[0611] Calling POST /v1.24/networks/network1/connect
DEBU[0611] form data: {"Container":"ff20876f9f363f253a1135e54e9c591d8288707922ae9f0de26300c9753f5259","EndpointConfig":{"Aliases":["web","ff20876f9f36"]}}
DEBU[0611] Calling POST /v1.24/containers/ff20876f9f363f253a1135e54e9c591d8288707922ae9f0de26300c9753f5259/start
```

I'm gonna close this issue, because this is a support question, not a bug report, so better suitable for forums.docker.com or the docker community slack channel, but feel free to comment after I closed

**Closed by thaJeztah** 2016-12-09 01:39 UTC
Labels: version/1.13

**Comment by dolanor** [comment] 2016-12-12 00:14
Thank you for this detail answer! Will save me some time of figuring out stuff.
In the log, if I understand well, it connects to the last network by default (`network2`), then it disconnects from it, and then connect, to both networks.
Have I understood it well?

Can I ask why is that? Wouldn't it be easier if all of that logic could be handled by the daemon itself?
It seems it would be an intuitive way to do it. Because, I just got very lucky you gave me that detailed answer of the current logic, which doesn't look intuitive to me, and I think it could be unintuitive to other people as well.
