### ISSUE TITLE
get.uber.com cert issue?

### ISSUE THREAD

**Issue by mantas-sidlauskas** [docker/docker#15950] opened 2015-08-31 13:51 UTC
wget https://get.docker.com/ubuntu/dists/docker/Release
    --2015-08-31 13:43:05--  https://get.docker.com/ubuntu/dists/docker/Release
    Resolving get.docker.com (get.docker.com)... 54.230.33.106, 216.137.39.59, 216.137.39.151, ...
    Connecting to get.docker.com (get.docker.com)|54.230.33.106|:443... connected.
    OpenSSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
    Unable to establish SSL connection.

wget version:  GNU Wget 1.13.4 built on linux-gnu.
OS: Ubuntu 12.04.5 LTS

**Comment by Evalle** [comment] 2015-08-31 15:04
Hello @mantas-sidlauskas it seems like the name of the issue should be "get.**docker**.com cert issue? :) 

BTW it works fine for me:
```
evgeny ~ $ wget https://get.docker.com/ubuntu/dists/docker/Release
--2015-08-31 17:02:16--  https://get.docker.com/ubuntu/dists/docker/Release
Resolving get.docker.com (get.docker.com)... 54.230.96.119, 54.230.96.43, 54.230.96.131, ...
Connecting to get.docker.com (get.docker.com)|54.230.96.119|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1525 (1.5K) [binary/octet-stream]
Saving to: ‘Release’

Release                  100%[====================================>]   1.49K  --.-KB/s   in 0s     

2015-08-31 17:02:16 (358 MB/s) - ‘Release’ saved [1525/1525]
```

**Comment by thaJeztah** [comment] 2015-08-31 17:00
I'm gonna close this issue, because this is not a bug in Docker, but I think the comment above should help you resolve your problem (thanks @Evalle!).

Thanks for taking the time to report this, though; it's appreciated :+1:

**Closed by thaJeztah** 2015-08-31 17:00 UTC
