### ISSUE TITLE
dockerd:flag provided but not defined: -shim

### ISSUE THREAD

**Issue by TheBeeMan** [docker/docker#24995] opened 2016-07-25 07:03 UTC
docker version is v1.12.0-rc4 of the latest one.

However, it failed to start with "dockerd" command and says that "flag provided but not defined: -shim"

How should I start a docker daemon with the latest version ?

**Comment by thaJeztah** [comment] 2016-07-25 11:16
How did you install RC4, and how did you start the daemon? Could it be you upgraded `dockerd`, but did not update `docker-containerd` ? What does `docker-containerd --version` show?

`docker-containerd` has a `--shim` option, but it needs *two* dashes (not one);

```
NAME:
   containerd - High performance container daemon

USAGE:
   docker-containerd [global options] command [command options] [arguments...]

VERSION:
   0.2.0 commit: 0ac3cd1be170d180b2baed755e8f0da547ceb267

COMMANDS:
   help, h	Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug							enable debug output in the logs
   --state-dir "/run/containerd"				runtime state directory
   --metrics-interval "5m0s"					interval for flushing metrics to the store
   --listen, -l "unix:///run/containerd/containerd.sock"	proto://address on which the GRPC API will listen
   --runtime, -r "runc"						name or path of the OCI compliant runtime to use when executing containers
   --runtime-args [--runtime-args option --runtime-args option]	specify additional runtime args
   --shim "containerd-shim"					Name or path of shim
   --pprof-address 						http address to listen for pprof events
   --start-timeout "15s"					timeout duration for waiting on a container to start before it is killed
   --retain-count "500"						number of past events to keep in the event log
   --graphite-address 						Address of graphite server
   --help, -h							show help
   --version, -v						print the version
```

**Comment by shivacherukuri** [comment] 2016-08-01 17:45
Hi,

 After doing $make binary from docker source, i tried to start docker daemon with newly build binary, but i get the following error, it seems like the issue mentioned in this thread... can you please let me know how to start docker daemon with new binary in the host. i Could start daemon inside a development container (result inside $make shell)without any issues but not in a host
-----------
root@dock1:~/siva_docker1/siva-docker-fork# bundles/1.12.0-dev/binary-daemon/dockerd
INFO[0000] New containerd process, pid: 24731
Incorrect Usage.

NAME:
   containerd - High performance container daemon
...
...
   --version, -v                                                print the version

FATA[0000] flag provided but not defined: -shim

**Comment by thaJeztah** [comment] 2016-08-01 17:59
@shivacherukuri looks like you did not build docker in a container; did you re-build `containerd`? using the correct commit? (see https://github.com/docker/docker/blob/master/Dockerfile#L246-L257)

After compiling, did you *install* `docker-containerd` in the right location? `dockerd` will look in your `$PATH` and if an older version is still present, it may use that version.

I just built docker from master, and it's working correctly; I'm closing this issue because this is not a bug, but feel free to continue the discussion

Also make sure to check the `docker-containerd --version`

**Closed by thaJeztah** 2016-08-01 17:59 UTC
Labels: status/more-info-needed

**Comment by shivacherukuri** [comment] 2016-08-03 12:43
Hi,
 Thanks for your reply. Yes i did build latest docker(1.13) in a container and i could start docker daemon inside a container but the same binaries after moving to a Host i couldn't start the daemon. I was having 1.11 docker version installed in my physical host.  with 1.11 i was hitting the above mentioned issue. after upgrading docker to 1.12 in my host, now i could run the dockerd( daemon) which was built from the latest source(1.13) without any issues. Thanks.

**Comment by vshlapakov** [comment] 2016-09-04 12:43
Hi @thaJeztah and all, I encountered with the mentioned issue recently, Linux Mint `17.3`, `docker-engine` upgraded from `1.11.2` -> `1.12.1`, with the following logs:
```
time="2016-09-04T14:18:27.636540235+03:00" level=info msg="libcontainerd: new containerd process, pid: 16776" 
Incorrect Usage.

NAME:
   containerd - High performance container daemon

USAGE:
   docker-containerd [global options] command [command options] [arguments...]
   
VERSION:
   0.2.2 commit: 9dc2b3273db42c75368988a3885a3afd770069d9
   
COMMANDS:
   help, h      Shows a list of commands or help for one command
   
GLOBAL OPTIONS:
   --debug                                                      enable debug output in the logs
   --state-dir "/run/containerd"                                runtime state directory
   --metrics-interval "5m0s"                                    interval for flushing metrics to the store
   --listen, -l "/run/containerd/containerd.sock"               Address on which GRPC API will listen
   --runtime, -r "runc"                                         name of the OCI compliant runtime to use when executing containers
   --runtime-args [--runtime-args option --runtime-args option] specify additional runtime args
   --pprof-address                                              http address to listen for pprof events
   --start-timeout "15s"                                        timeout duration for waiting on a container to start before it is kill
ed
   --retain-count "500"                                         number of past events to keep in the event log
   --graphite-address                                           Address of graphite server
   --help, -h                                                   show help
   --version, -v                                                print the version
   
FATA[0000] flag provided but not defined: -shim   
```
You can see there's no `--shim` option at all, though `containerd` version > your `0.2.0`.
I was able to fix everything with:
- getting latest containerd with `go get github.com/docker/containerd`
- cloning it's repository locally and creating binaries with `make` command
- replacing my system's binaries in `/usr/local/bin/docker-containerd*` with the ones from `/bin` folder with the original names

I guess it's not how it should work , and probably there's a problem somewhere. 
Current working `containerd` version is `0.2.3`.

**Comment by thaJeztah** [comment] 2016-09-12 16:31
@vshlapakov the official packages use a different version of containerd; see https://github.com/docker/docker/blob/v1.12.1/Dockerfile#L247, perhaps this is an issue with the containerd version packaged  by mint? On a clean ubuntu machine with docker 1.12.1 installed from apt.dockerproject.org, I get this;

```
root@dockr:~# docker-containerd --help
NAME:
   containerd - High performance container daemon

USAGE:
   docker-containerd [global options] command [command options] [arguments...]

VERSION:
   0.2.0 commit: 0ac3cd1be170d180b2baed755e8f0da547ceb267

COMMANDS:
   help, h	Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug							enable debug output in the logs
   --state-dir "/run/containerd"				runtime state directory
   --metrics-interval "5m0s"					interval for flushing metrics to the store
   --listen, -l "unix:///run/containerd/containerd.sock"	proto://address on which the GRPC API will listen
   --runtime, -r "runc"						name or path of the OCI compliant runtime to use when executing containers
   --runtime-args [--runtime-args option --runtime-args option]	specify additional runtime args
   --shim "containerd-shim"					Name or path of shim
   --pprof-address 						http address to listen for pprof events
   --start-timeout "15s"					timeout duration for waiting on a container to start before it is killed
   --retain-count "500"						number of past events to keep in the event log
   --graphite-address 						Address of graphite server
   --help, -h							show help
   --version, -v						print the version
```

**Comment by kaspersorensen** [comment] 2017-06-07 19:30
I experienced this after upgrading an old docker install (`1.11` I believe) to `1.17`. I eventually figured out that the old install still had `docker-containerd` executables in `/usr/local/bin`, whereas the new executable was in `/bin`. Deleting the old executables in `/usr/local/bin` fixed the issue:

```
sudo rm /usr/local/bin/docker*
```

**Comment by drubanov** [comment] 2017-12-02 12:07
I understand that Docker has changed how container manger and containerd/container-shim are related to each other starting with 1.11, but, as a general rule, if you ship a source tree which cannot run after being built, you need to report an error either during the build or during the installation.  If an error is reported after a successful build and installation, that's a bug.
