### ISSUE TITLE
Getting BADSIG on apt-get update on Ubuntu 14.04.2 LTS  x86_64

### ISSUE THREAD

**Issue by pocesar** [docker/docker#12461] opened 2015-04-16 22:24 UTC
# Solution

`deb https://get.docker.io/ubuntu docker main` needs to be changed to `deb https://get.docker.com/ubuntu docker main` in `/etc/apt/sources.list` or in `/etc/apt/sources.list.d/docker.list`.

After making this change, `apt-get update && apt-get install lxc-docker` needs to be run.

_______________________________________________________
## Initial bug report

apt-get yields:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://get.docker.io docker Release: The following signatures were invalid: BADSIG D8576A8BA88D21E9 Docker Release Tool (releasedocker) <docker@dotcloud.com>

W: Failed to fetch https://get.docker.io/ubuntu/dists/docker/Release

W: Some index files failed to download. They have been ignored, or old ones used instead.
```

is it a problem with my end or docker website?

**Comment by sstarcher** [comment] 2015-04-16 22:52
This looks to be a problem on dockers end.  We started seeing this about 5:30pm EST.

**Comment by sstarcher** [comment] 2015-04-16 22:54
The same issue happened a few months back.  If you want a quick fix update our sources.list for apt and change .io to .com
deb https://get.docker.io/ubuntu docker main
to
deb https://get.docker.com/ubuntu docker main

**Comment by pocesar** [comment] 2015-04-16 23:00
thanks, that worked

**Comment by Herkemer** [comment] 2015-04-17 03:19
Just to add another datapoint, I was seeing this also, change .io to .com and it started working.

**Comment by PlugIN73** [comment] 2015-04-17 12:04
Working for me! Thank you!

**Comment by unclejack** [comment] 2015-04-17 12:15
I've updated the original post to let others who will come across this problem know what to do.

@tianon Do you think we should detect this in the install script and overwrite the old apt repo with the new one?

**Comment by tianon** [comment] 2015-04-24 16:52
@unclejack that sounds sane yeah, although probably only for the file we created / recommended (`/etc/apt/sources.list.d/docker.list`), right? (so that we don't accidentally break unrelated configuration)

The way I read https://github.com/docker/docker/blob/310fc37fe76421109109c11c1181b97ce93b6c80/hack/install.sh#L191, that's basically what we already do if you run this script twice (since we use `>`, not `>>`).

**Comment by cpuguy83** [comment] 2015-09-14 16:08
Closing since this is no longer relevant with the new apt repos.
Thanks!

**Closed by cpuguy83** 2015-09-14 16:08 UTC

**Comment by mattmoor** [comment] 2015-11-03 20:29
@cpuguy83 
I am seeing this right now with `get.docker.com/ubuntu` intentionally installing older releases for compatibility testing.

@tcnghia FYI

**Comment by detro** [comment] 2015-11-04 12:09
Yeah, another breaking change!

So, no one forces you guys to stay on the same repository forever. But you have to understand that, unless we are Docker contributors, we don't spend our day checking out the LATEST DOCUMENTATION on how to install Docker. We write our script ones, and let them go.

Right now all my automated servers that auto-install Docker in the European Region are reporting the BADSIG error. Soon I suspect this is going to go global (just the time for some of your changes to fully propagate).

It turns out that HTTP protocol comes with a nice 3xx class of errors: use those to do REDIRECTS, and don't break our s**t every time you release something.

I had it with this technology.
As soon as I have enough time, I'll jump of this bandwagon of nonsense.
It's almost 2yy I have worked with Docker, and it's a constant disappointment in how the project is run, stuff is hosted and backward compatibility is disregarded.

**Comment by cheeryfella** [comment] 2015-11-04 13:59
I have encountered this recently..

What worked for me was:

apt-get update && apt-get -y install lxc-docker --force-yes

**Comment by detro** [comment] 2015-11-04 14:10
@cheeryfella yeah, I get that. It's easy to circumvent by forcing APT-GET to disregard the bad signature.
But this is not strictly my point.
My point is that those ppl at Docker just don't understand what it means to provide a tool that other ppl use to achieve a goal.

Docker is a tool. You install it, write your code to use it, deploy it and it has to keep working. Bugs happen. And we should keep an eye out for them and fixes if they happen. But making breaking changes to the hosting: that is immaturity (of the people involved). Immaturity in how they do their work. In how they don't understand the crucial role they now (wanting it or not) have.

As a matter of fact, on the new repository you can't even find `lxc-docker-1.5.0`. Your only hope is the PREVIOUS repository (the one I use) and finger crossed they don't ditch that too.

**Comment by cpuguy83** [comment] 2015-11-04 14:31
@detro I'm sorry that you've been affected by this change.
Unfortunately it was an incompatible change and not something that can just be redirected. These are completely new repos, with completely different packages... most importantly, they are proper apt repos with packages that fixed some (very) major issues with the old packages.

This change originally announced back in July: http://blog.docker.com/2015/07/new-apt-and-yum-repos/
Ultimately it was a much needed change, both for getting proper apt versioning, as well as fixing some major issues with the older packages that could only be fixed by providing new packages.
Both repos were maintained for from the original July announcement until now.

If you'd like to discuss other breaking changes, I'd love to hear it. Maybe you can hop on IRC for a chat, or open a separate issue for specific breaking examples?
Breaking changes are generally unexpected unless they are announced prior to the break, such as the blog post above, or in `docs/deprecation.md`, and we do work to make sure it doesn't happen, but they do make it through some times.
There's certainly some room for improvement in the testing infrastructure for backwards compatibility.

**Comment by detro** [comment] 2015-11-04 14:38
@cpuguy83 I have pointed out above: you guys should keep building, coding, improving and fixing. Migrate to a new repo as much as you want too. We don't mind to deal with "from 1.x onward, you need to install this other way".

But changing a running repo: that is what causes my anger. Once you release something, you can't take it away or change how it's hosted. Once something is "released" it stays fixed in stone. Don't move URLs or change signatures, unless you can handle redirects transparently.

This is done in the industry by... everybody.
Take the old Maven ecosystem: no one stops developers from delivering new awesome. But once something is on an official repo, it's fixed forever. No taking back. No changing URLs.

**Comment by mattmoor** [comment] 2015-11-04 15:06
@cpuguy83 Setting up a new repo for new releases is orthogonal from the fact that the legacy mirror got broken very recently.  

It's totally cool to make it a little more difficult to get the latest and greatest Docker (e.g. moving to a new mirror / package name), if that's what you need to do.  The change I'm talking about is **breaking** folks that are using a pinned docker version (intentionally trying to avoid this kind of disruption due to the client version changing), which is simply good sense.

@jfrazelle FYI, this is the same issue I pinged you about yesterday afternoon.

**Comment by cpuguy83** [comment] 2015-11-04 15:14
@mattmoor @detro I'm testing this now, as again this should not have broken.
I setup a new DO droplet in the London DC, did `curl https://get.docker.com | sh`, and everything worked out of the box.

Maybe I should try something else? Or maybe this was a caching problem?

**Comment by jfrazelle** [comment] 2015-11-04 15:15
The way apt repos work is you sign the release file, so everytime you have a release the signature is changed so I realize this is a huge inconvenience but it was not intentionally meant to break anyone. We are looking into the issue and if it's a cache problem or something else. We have not completely dismissed the old repos.

**Comment by mattmoor** [comment] 2015-11-04 15:18
@cpuguy83 We aren't talking about the `get.docker.com` shell script, we're talking about the `get.docker.com` debian package mirror, which the script used to use, and which allowed:
```
   apt-get install lxc-docker-{version}
```

**Comment by jfrazelle** [comment] 2015-11-04 15:20
But saying 
>  Don't move URLs or change signatures
Is completely unavoidable since we wanted to maintain this repo to _not break folks_ and still push releases here... you have to sign the file every release

**Comment by jfrazelle** [comment] 2015-11-04 15:22
Also yesterday after @mattmoor pinged me I installed 1.5 and 1.4 in a loop successfully so that's why I believe it's cache but we are still looking into it

**Comment by cpuguy83** [comment] 2015-11-04 15:28
And tested against `deb https://get.docker.com/ubuntu docker main`, it's working for me.
So sounds like a caching issue?

**Comment by jfrazelle** [comment] 2015-11-04 15:28
I have busted the cache on cloudfront, so I urge you all to try again..

**Comment by cpuguy83** [comment] 2015-11-04 15:28
Tested with lxc-docker-1.5.0 and lxc-docker-1.9.0, fyi.

**Comment by mattmoor** [comment] 2015-11-04 15:32
@jfrazelle I've kicked off some testing that's been reproducing this pretty consistently (probabilistically over a subset) for the last ~20 hours.  I'll let you know whether it still reproduces.

**Comment by jfrazelle** [comment] 2015-11-04 15:34
thanks!

**Comment by detro** [comment] 2015-11-04 15:48
So, just for giving more details about this.

1. Encountered this issue when running an EC2 boot script in EU_WEST_1 (AWS Ireland Data Center)
2. The script does the following:
```
echo "deb https://get.docker.io/ubuntu docker main" > /etc/apt/sources.list.d/docker.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 
36A1D7869245C8950F966E92D8576A8BA88D21E9
apt-get update
apt-get install lxc-docker-1.5.0
```
3. :boom: error `BADSIGN` thrown by `apt-get install`

The line that installs the key have changed recently (or not recently? It shouldn't matter...) to:
```
apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
```

I'll iterate for the last time: progress the software _at the speed of light_ if you can. Make it awesome. Do whatever the hell you need/want to do. Just make ALWAYS ADAMANTLY SURE that what's released, never EVER changes. Being it the key with which the package is signed, the url to the repo, the API protocol or whatever else is going to have anything to do with a `released` version.

Docker ppl, you have done this TOO MANY TIMES. If you look for my comments on this repo, you will find a plethora of places where I keep saying the same things (check particularly the `boot2docker` repo, that's one that gave me grief so many times...).

A question: do you guys really think that what you release it's adopted immediately? Any person employed in this industry that uses Docker will take months before they can upgrade to latest/greatest. And that's not laziness. It's because we got products to take care of. Docker is a tool. It's like `bash` or `apt-get` or `grep`.

**Comment by cpuguy83** [comment] 2015-11-04 16:08
@detro I used `apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9` to install on my droplet above.
This worked for me.
You are saying `36A1D7869245C8950F966E92D8576A8BA88D21E9` did not work for you?

**Comment by detro** [comment] 2015-11-04 16:16
I listed the steps above. The key that failed is `36A1D7869245C8950F966E92D8576A8BA88D21E9 ` yes. The addendum was to show that the key (and the repo where it's stored) also changed in the official doc. And I gather that stuff has got RE-SIGNED with that key. And that caused the issue: old script with old key, made incompatible with old package that uses new key.

**Comment by mattmoor** [comment] 2015-11-04 16:27
@jfrazelle Latest run has no mirror-related failures.

@detro Are things working for you again as well?

**Comment by detro** [comment] 2015-11-04 16:30
@mattmoor after installing the `58118E89F3A912897C070ADBF76221572C52609D` key it SEEMS to be ok, but I have added a `--force-yes` to my script when installing the docker package. Evidently I need to leverage things that are explicitly marked as "very dangerous" by `man apt-get` to be able to work with Docker...

**Comment by cpuguy83** [comment] 2015-11-04 16:32
@detro Again, the "old" key worked fine for me. So I'm not sure I understand the issue you are seeing.

**Comment by jfrazelle** [comment] 2015-11-04 16:36
The key starting with a 5 is incorrect for the old repo






On Wed, Nov 4, 2015 at 8:32 AM -0800, "Ivan De Marino" <notifications@github.com> wrote:












@mattmoor after installing the 58118E89F3A912897C070ADBF76221572C52609D key it SEEMS to be ok, but I have added a --force-yes to my script when installing the docker package. Evidently I need to leverage things that are explicitly marked as "very dangerous" by man apt-get to be able to work with Docker...

**Comment by jfrazelle** [comment] 2015-11-04 16:36
It is also literally impossible for the old repo to be signed by the key starting w a 5 because I am the only person w access to that key and I didn't release the debs 






On Wed, Nov 4, 2015 at 8:32 AM -0800, "Ivan De Marino" <notifications@github.com> wrote:












@mattmoor after installing the 58118E89F3A912897C070ADBF76221572C52609D key it SEEMS to be ok, but I have added a --force-yes to my script when installing the docker package. Evidently I need to leverage things that are explicitly marked as "very dangerous" by man apt-get to be able to work with Docker...

**Comment by detro** [comment] 2015-11-04 16:59
Well, given that now we can't reproduce it either, I assume something got fixed while we were here.

Unless we want to operate on the assumption that we have nothing best to do than yell at Docker developers...

**Comment by jfrazelle** [comment] 2015-11-04 17:03
WDYM? I thoroughly enjoyed all parts of this exchange 

Glad to see you all are no longer having issues, sorry again for the inconvienence

**Comment by detro** [comment] 2015-11-19 14:29
FYI, just had to remove:
```
apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
```

from our install script as we are getting:
```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.6ZnUcHyswm --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server pgp.mit.edu
gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D can't be retrieved
```

From all AWS regions, but `EU_WEST_1`.
Definitely some caching.

**Comment by shrmrf** [comment] 2016-06-17 14:44
I have 3 machines on Azure (in Netherlands) and it was happening on only one of those... I didn't have the time to investigate further so I did the unholy: went in and said yes! Now no problems.
