### ISSUE TITLE
--rm and -d concurrent support

### ISSUE THREAD

**Issue by magaal** [docker/docker#13256] opened 2015-05-15 18:27 UTC
Hi - for a Swarm use case, but specific to Docker functionality, I'd like to submit containers that have a specific purpose across my cluster nodes with affinity set so that only one container runs per node for an HPC workload; I'd like them to remove on task completion, freeing up the node for another container. --rm and -d supported simultaneously seems like it would help me out, otherwise I get a flood of output to where I launched my docker run commands.

**Comment by thaJeztah** [comment] 2015-05-17 20:24
Thanks for reporting this, but I think this is a duplicate of https://github.com/docker/docker/issues/10545. Also look at this comment: https://github.com/docker/docker/issues/10545#issuecomment-73827389 which explains the situation a bit more in depth.

I'm going to close this issue because it's a duplicate of https://github.com/docker/docker/issues/10545, please continue the discussion on that issue.

**Closed by thaJeztah** 2015-05-17 20:24 UTC
