### ISSUE TITLE
Ctrl-C issued on bash read command kills container

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [docker/docker#16134] opened 2015-09-08 09:07 UTC
I'm not sure if I'm just retarded here, it may very well be, but I'm experiencing the strangest behavior with some scripting I've done in a customized docker image.

In essence, I'm using a function like this ...

    function get_pwd {
        read -sp "Please provide password: " PWD
        echo $PWD
    }

... which is used in some configuration scripts included with my image like `PWD=$(get_pwd)`.

The funky thing is that if I do something like `docker run -d --name pg my_image` and then docker `exec -it pg script_that_requests_password` and then hit `Ctrl+C` when the `read` command is asking for the password, the container is immediately halted, without the entrypoint process even receiving a SIGTERM, such as it does with `docker stop`.

Same thing happens if I do a `docker exec -it pg bash` and run my script from in there. The script is exited (as expected), but then I get a black `%` char with white background (`root@e3418eba92fb:/# %`), and bash exits along with docker with the exit code 130.

I'm really puzzled by this... Any ideas? ~~I assume it's `read` actually reading the control code, and then its echoing of it somehow causes the environment to act upon it. But I don't understand how it propagates all the way to actually terminating the container~~ I tried testing my input for `[[:cntrl:]]` and `[^[:print:]]` and cancelling without echoing when matched, but it seems I never actually get there... The container is killed before I get back in my script...

Docker version:

    Client:
     Version:      1.8.1
     API version:  1.20
     Go version:   go1.5
     Git commit:   d12ea79
     Built:        Mon Aug 24 06:58:36 UTC 2015
     OS/Arch:      darwin/amd64

    Server:
     Version:      1.8.1
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   d12ea79
     Built:        Thu Aug 13 02:49:29 UTC 2015
     OS/Arch:      linux/amd64

Docker info

    Containers: 3
    Images: 24
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 30
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.0.9-boot2docker
    Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
    CPUs: 1
    Total Memory: 1.955 GiB
    Name: fusion
    ID: ROHC:GNAL:BUWE:P4A3:TY5U:CP2D:ZT4I:YQVH:QSPH:2YDT:IWUZ:3HRK
    Debug mode (server): true
    File Descriptors: 35
    Goroutines: 64
    System Time: 2015-09-08T09:09:17.706806956Z
    EventsListeners: 0
    Init SHA1: 
    Init Path: /usr/local/bin/docker
    Docker Root Dir: /mnt/sda1/var/lib/docker
    Labels:
     provider=vmwarefusion

`Darwin ether.local 15.0.0 Darwin Kernel Version 15.0.0: Mon Aug 10 17:09:09 PDT 2015; root:xnu-3247.1.99~3/RELEASE_X86_64 x86_64 i386 MacBookAir7,2 Darwin`

**Comment by phemmer** [comment] 2015-09-08 14:41
Can you provide a reproducible example? I am not able to reproduce this:

```
# cat Dockerfile
FROM ubuntu:trusty

ADD foo /foo
RUN chmod a+x /foo

CMD ["sleep", "inf"]

# cat foo
#!/bin/bash

function get_pwd {
	read -sp "Please provide foo: " FOO
	echo $FOO
}

get_pwd

# docker build -t test .
Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:trusty
 ---> 91e54dfb1179
Step 1 : ADD foo /foo
 ---> Using cache
 ---> 6f33835e86e1
Step 2 : RUN chmod a+x /foo
 ---> Using cache
 ---> 5ff0c4d0c383
Step 3 : CMD sleep inf
 ---> Using cache
 ---> 2653900e9850
Successfully built 2653900e9850

# docker run -d --name test test
f3f990738f93c82ea19f1a3b3aa18c36274b8fea4865f693a5c635ba72bfc417

# docker exec -it test /foo
Please provide foo: 
^C

# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
f3f990738f93        test                "sleep inf"              8 seconds ago       Up 8 seconds                            test
```

I am also using docker 1.8.1

**Comment by cpuguy83** [comment] 2015-10-01 01:55
Also can't repro.
Closing, but if you can provide a simple repro case, please post here and we can take a look.

Thanks!

**Closed by cpuguy83** 2015-10-01 01:55 UTC
