### ISSUE TITLE
ENTRYPOINT vs CMD differences

### ISSUE THREAD

**Issue by mattford63** [docker/docker#18859] opened 2015-12-22 21:25 UTC
A small twist on the normal ENTRYPOINT vs CMD questions - reporting as an issue as I think there should be a note in the docs about why the difference belows works as it seems unusual to me at least.  Makes me feel I'm missing some fundamental difference between the two options.

What I don't understand is why ENTRYPOINT let's me chown a bind mount whereas CMD doesn't?

This seems a popular pattern in the offical mirrors for say REDIS and POSTGRES as described here:

https://github.com/docker-library/redis/tree/master/3.0

And detailed here http://stackoverflow.com/a/29799703/5704917

**Comment by cpuguy83** [comment] 2015-12-24 13:32
1. If ENTRYPOINT is set, then CMD is passed as options to ENTRYPOINT.
2. If ENTRYPOINT is not set, and CMD is specified as a JSON array, then CMD is executed directly.
3. If ENTRYPOINT is not set and CMD is specified as a string, then ENTRYPOINT is set to `/bin/sh -c`, and rule 1 applies

**Comment by thaJeztah** [comment] 2015-12-24 16:15
Yup, there's a nice overview in this issue: https://github.com/docker/docker/issues/10084, and we probably should still improve the documentation on that (as mentioned in that issue). If you're interested in doing that, that'd be awesome :+1: 

I'll close this issue because I think it's a duplicate of https://github.com/docker/docker/issues/10084, but feel free to comment here after I've closed :smile:

**Closed by thaJeztah** 2015-12-24 16:15 UTC

**Comment by mattford63** [comment] 2016-01-04 12:53
Hi, I understand the differences between CMD and ENTRYPOINT in terms of what gets run.  What I don't understand is why I can `chown` a bind mount within an ENTRYPOINT script but not a CMD script (as per the common patterns)

**Comment by mattford63** [comment] 2016-01-04 13:12
It's weird though right?  Bind mounts should not be able to have their ownership changed.  It's like ENTRYPOINT happens at the host level somehow.

**Comment by cpuguy83** [comment] 2016-01-04 13:22
You can, it's all part of the same command.
If it's not working then happy to help.

**Comment by thaJeztah** [comment] 2016-01-04 13:51
This should be working, e.g.;

```bash
$ mkdir -p test && touch test/file1 test/file2 && sudo chown -R 456:789 test
$ ls -la test/
total 0
drwxr-sr-x    2 456      789             80 Jan  4 13:37 ./
drwxr-sr-x    3 docker   staff           80 Jan  4 13:37 ../
-rw-r--r--    1 456      789              0 Jan  4 13:37 file1
-rw-r--r--    1 456      789              0 Jan  4 13:37 file2
```

```bash
$ docker build -t foo - << EOF
FROM ubuntu
CMD chown -R 123:456 /test && ls -la /test
EOF
```

```bash
$ docker run -v $(pwd)/test:/test foo
total 4
drwxr-sr-x  2  123  456   80 Jan  4 13:37 .
drwxr-xr-x 33 root root 4096 Jan  4 13:48 ..
-rw-r--r--  1  123  456    0 Jan  4 13:37 file1
-rw-r--r--  1  123  456    0 Jan  4 13:37 file2
```

**Comment by mattford63** [comment] 2016-01-04 15:12
hmm - I most certainly can! :-)  Before Christmas I had a similar test that failed.  Apologies for raising a non-issue.  I think the issue I was seeing was related to using a remote docker host with odd storage.
