### ISSUE TITLE
Package docker for yakkety in https://apt.dockerproject.org/repo/dists/

### ISSUE THREAD

**Issue by zigarn** [docker/docker#28023] opened 2016-11-03 07:57 UTC
Ubuntu Yakkety (16.10) is available since 2016-10-13.
Docker is not yet packaged for this distribution: https://apt.dockerproject.org/repo/dists/

**Comment by thaJeztah** [comment] 2016-11-03 08:02
duplicate of https://github.com/docker/docker/issues/27521

**Closed by thaJeztah** 2016-11-03 08:02 UTC

**Comment by zigarn** [comment] 2016-11-03 09:34
Missed it, sorry.

**Comment by thaJeztah** [comment] 2016-11-03 21:15
no problem! :smile:
