### ISSUE TITLE
Allow containers to be connected to networks before it is started

### ISSUE THREAD

**Issue by rmb938** [docker/docker#17289] opened 2015-10-23 01:44 UTC
docker version: ```Docker version 1.9.0-dev, build 4816626```
docker into:
```
Containers: 13
Images: 9
Server Version: 1.9.0-dev
Storage Driver: devicemapper
 Pool Name: docker-253:0-33662528-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.595 GB
 Data Space Total: 107.4 GB
 Data Space Available: 10.87 GB
 Metadata Space Used: 2.691 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.797 GiB
Name: ccompute1.rmb938.com
ID: IAQS:6E74:7NGG:5JOG:JXFM:26VD:IAQV:FZNU:E23J:QUAA:NI4O:DI3S
```

uname -a ```Linux ccompute1.rmb938.com 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux```

Currently when creating (not running) a container you can assign it to a network. Either multiple ```--net=``` should be allowed when creating the container OR allowing ```docker network attach``` without the container being started.

**Comment by aboch** [comment] 2015-12-03 20:36
@rmb938  
It looks like https://github.com/docker/docker/issues/17750 which came in later got more attention and https://github.com/docker/docker/pull/17796 was opened to support multiple networks binding for `docker create` and `docker run`.

If you agree #17796 is a valid fix for your reported issue, we can update the PR description so that this issue will be closed when/if #17796 gets merged.

**Comment by rmb938** [comment] 2015-12-03 20:45
@aboch Yes #17796 does seem like a valid fix.

**Comment by aboch** [comment] 2015-12-03 21:06
Thanks @rmb938 

@coolljt0725 Can you please update your PR description to also include this issue. Thanks.

**Comment by coolljt0725** [comment] 2015-12-04 01:11
@aboch  sorry, very busy these these days. I'll update my PR on this weekend.

**Comment by thaJeztah** [comment] 2015-12-04 14:56
@aboch @coolljt0725 @rmb938 I'll close this issue as a duplicate of https://github.com/docker/docker/issues/17750, and add a mention in https://github.com/docker/docker/pull/17796

**Closed** 2015-12-04 14:56 UTC
Labels: group/networking, kind/enhancement
