### ISSUE TITLE
Configurable key bindings for detach in interactive mode

### ISSUE THREAD

**Issue by tjim** [docker/docker#12510] opened 2015-04-18 15:35 UTC
In interactive mode (docker run -it) the key sequence Control-P Control-Q causes a detach.

It's good that you can do this, but this conflicts with the use of Control-P to move backwards in the bash command history.

So, when running bash inside docker interactive mode, two Control-P's are necessary to move backwards in the command history, instead of just one as in an ordinary invocation of bash.

Rather than reprogramming my brain, I'd like to be able to change this key binding to something else. It seems to be hard-coded now.

**Comment by thaJeztah** [comment] 2015-04-19 17:26
Also, slightly related to the discussion around key bindings for attach; https://github.com/docker/docker/issues/2855

**Comment by thaJeztah** [comment] 2015-04-23 22:47
Hm, looks like this is a duplicate of #3519

I'm going to close this issue, because this is a duplicate. Please continue the discussion on #3519

(Sorry for not noticing this before but we've got quite a few issues in our tracker :))

**Closed by thaJeztah** 2015-04-23 22:47 UTC
Labels: kind/feature, kind/proposal, UX
