### ISSUE TITLE
Docker Hub handles multi-variable ENV statements incorrectly?

### ISSUE THREAD

**Issue by 7adietri** [docker/docker#9892] opened 2015-01-04 12:11 UTC
In my Dockerfile, I initially set multiple variables in one ENV statement:
https://github.com/7adietri/docker-murmur/blob/860ad2ef117dba156cefdc17f5841a95b623aeec/Dockerfile#L10

According to documentation, this should be valid and worked for me locally (Docker 1.4.1 on Ubuntu 14.04). But Docker Hub ran into a problem:
https://registry.hub.docker.com/u/7adietri/murmur/build_id/32923/code/bfxthtyizytrjxwr4bvepcg/

So I had to split up the variables into separate ENV statements:
https://github.com/7adietri/docker-murmur/blob/8cd500b87919cc81a4db01201ecad8115160e147/Dockerfile#L10

**Comment by thaJeztah** [comment] 2015-01-04 12:42
I suspect the registry is running an older version of docker (similar issues have come up in the past)

**Comment by SvenDowideit** [comment] 2015-01-04 23:59
@kencochrane ?

**Comment by kencochrane** [comment] 2015-01-20 15:56
@dustinlacewell

**Comment by gregsymons** [comment] 2015-01-21 19:36
I've seen the same problem. I've expanded my ENVs to one-per-line... but that's a lot of extra layers.

**Comment by jfrazelle** [comment] 2015-01-27 17:21
Hi all I hope you are not having this problem anymore. But since it is hub specific and not a bug with anything in this repo I am going to close this, but if you are still having issues please email support@docker.com and they can help! And please correct me if I am wrong and this is a bug with docker.

**Closed by jfrazelle** 2015-01-27 17:21 UTC
