### ISSUE TITLE
Set disc quota per container

### ISSUE THREAD

**Issue by kovacsa91** [docker/docker#17899] opened 2015-11-11 08:49 UTC
I have read several forum topics and also issues in this topic, but haven't find exact, working solution for this problem. Tried to use DeviceMapper storage plugin, but don't know exactly, how to use it. Maybe is there any 3rd party solution for this?

**Comment by kovacsa91** [comment] 2015-11-11 08:50
Docker info output:
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-253:1-16-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.209 GB
 Data Space Total: 268.4 GB
 Data Space Available: 11.27 GB
 Metadata Space Used: 2.454 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-22-generic
Operating System: Ubuntu 15.04

**Comment by unclejack** [comment] 2015-11-11 09:05
@kovacsa91 This issue is a duplicate of #3804. Please comment on #3804 if you happen to have some questions related to quotas for storage backends.

As a general rule, everyone should comment on the existing open issue if it discusses the exact same topic they're interested in.

I'm going to close this issue now because it's a duplicate of an existing open issue and we don't need two open issues for the exact same topic.

Please comment on #3804 if there's anything you'd like to discuss.

**Closed by unclejack** 2015-11-11 09:05 UTC
