### ISSUE TITLE
Display tags of the particular image searched via `docker search` command

### ISSUE THREAD

**Issue by borntorock** [docker/docker#31569] opened 2017-03-06 11:20 UTC
Would be great for users to see the available tags of the particular image searched via `docker search` command. 

Somewhat may be like `docker search tags ubuntu` should display all the tags of the ubuntu image present in docker hub.

**Comment by thaJeztah** [comment] 2017-03-06 11:49
Thanks for suggesting. This is a duplicate of https://github.com/docker/docker/issues/17238, so let me close this one. Please subscribe to that issue to keep informed on updates 👍

**Closed by thaJeztah** 2017-03-06 11:49 UTC
Labels: area/distribution
