### ISSUE TITLE
docker build overwrites resolve.conf

### ISSUE THREAD

**Issue by Vish0007** [docker/docker#20095] opened 2016-02-08 04:38 UTC
my /etc/resolve.conf entries are removed after docker build.
docker version: 1.8.x

**Comment by thaJeztah** [comment] 2016-02-08 14:55
Can you add more information; which `/etc/resolv.conf` ? inside the container, on your host? Can you show the steps how to reproduce? Which system you're running on etc.

**Comment by Vish0007** [comment] 2016-02-09 04:48
I am doing docker build on CoreOS and the /etc/resolv.conf of the coreos
host machine is getting overwritten.
These are simple steps : update /etc/resolv.conf; then do docker build -t
test-image . ; then check the resolve.conf file.

**Comment by thaJeztah** [comment] 2016-02-09 16:59
Docker doesn't modify `/etc/resolv.conf` **however** systemd is; you should not be editing that file, but follow the instructions here; https://coreos.com/os/docs/latest/configuring-dns.html


closing, because this is not a bug in docker, but the way systemd works

**Closed by thaJeztah** 2016-02-09 16:59 UTC
Labels: status/more-info-needed
