### ISSUE TITLE
"oci runtime error: no such file or directory."

### ISSUE THREAD

**Issue by grostim** [docker/docker#26893] opened 2016-09-25 14:19 UTC
**Description**

When creating a container, it fails with error 

> docker: Error response from daemon: oci runtime error: no such file or directory.

**Steps to reproduce the issue:**
1. exec  the following command line (or any other container)

> docker run --name new-jeedom --privileged -v /dev/tty*:/dev -v /media/f8d709d5-2536-494f-bceb-da463a46e3b8/DockerFolder/Jeedom:/var/www/html -v /var/run/dbus:/var/run/dbus -e ROOT_PASSWORD=jeedom -p 9080:80 -p 9022:22 -p 8083:8083 -p 51826:51826 jeedom/jeedom

2. enjoy the cryptic error message.

**Describe the results you received:**

> docker: Error response from daemon: oci runtime error: no such file or directory.

**Describe the results you expected:**

A working container ?

**Additional information you deem important (e.g. issue happens only occasionally):**

Here are the debug information i gathered : 
```
Sep 25 16:17:53 OMV docker[8571]: time="2016-09-25T16:17:53.413490525+02:00" level=debug msg="Calling DELETE /v1.24/containers/new-jeedom"
Sep 25 16:17:53 OMV docker[8571]: time="2016-09-25T16:17:53.413560140+02:00" level=error msg="Handler for DELETE /v1.24/containers/new-jeedom returned error: No such container: new-jeedom"
Sep 25 16:17:57 OMV docker[8571]: time="2016-09-25T16:17:57.680881413+02:00" level=debug msg="Calling POST /v1.24/containers/create?name=new-jeedom"
Sep 25 16:17:57 OMV docker[8571]: time="2016-09-25T16:17:57.681336642+02:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":null,\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[\"ROOT_PASSWORD=jeedom\"],\"ExposedPorts\":{\"22/tcp\":{},\"51826/tcp\":{},\"80/tcp\":{},\"8083/tcp\":{}},\"HostConfig\":{\"AutoRemove\":false,\"Binds\":[\"/dev/tty*:/dev\",\"/media/f8d709d5-2536-494f-bceb-da463a46e3b8/DockerFolder/Jeedom:/var/www/html\",\"/var/run/dbus:/var/run/dbus\"],\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{\"22/tcp\":[{\"HostIp\":\"\",\"HostPort\":\"9022\"}],\"51826/tcp\":[{\"HostIp\":\"\",\"HostPort\":\"51826\"}],\"80/tcp\":[{\"HostIp\":\"\",\"HostPort\":\"9080\"}],\"8083/tcp\":[{\"HostIp\":\"\",\"HostPort\":\"8083\"}]},\"Privileged\":true,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"jeedom/jeedom\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":{}
Sep 25 16:17:57 OMV docker[8571]: ,\"WorkingDir\":\"\"}"
Sep 25 16:17:57 OMV kernel: [1227534.645064] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.645784] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.646576] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.647278] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.647941] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.648611] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.649292] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.649984] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.650768] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.651488] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.652243] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.652989] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.653742] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.654543] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.655370] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.656163] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.656966] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.657779] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.658697] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.659537] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.660389] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.661248] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.662142] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.719301] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.720796] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.722346] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.723767] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.725187] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.726709] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.727725] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.728448] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.729161] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.729889] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.730729] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.731472] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.732225] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.732992] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.733768] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.734601] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.735434] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.736246] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.737102] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.737942] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV docker[8571]: time="2016-09-25T16:17:57.791954515+02:00" level=debug msg="container mounted via layerStore: /var/lib/docker/aufs/mnt/744601ea9604b5338b699bbc0d1801cbaf17c672f9f2b52931802db4166fc387"
Sep 25 16:17:57 OMV kernel: [1227534.738855] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.739726] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.740603] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:57 OMV kernel: [1227534.741490] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV docker[8571]: time="2016-09-25T16:17:58.290265909+02:00" level=debug msg="Calling POST /v1.24/containers/0a502a0222d5eb202e650dfc516adf2992693b9eed5e547f762140927943921b/attach?stderr=1&stdout=1&stream=1"
Sep 25 16:17:58 OMV docker[8571]: time="2016-09-25T16:17:58.290397221+02:00" level=debug msg="attach: stderr: begin"
Sep 25 16:17:58 OMV docker[8571]: time="2016-09-25T16:17:58.290400207+02:00" level=debug msg="attach: stdout: begin"
Sep 25 16:17:58 OMV docker[8571]: time="2016-09-25T16:17:58.290784579+02:00" level=debug msg="Calling POST /v1.24/containers/0a502a0222d5eb202e650dfc516adf2992693b9eed5e547f762140927943921b/start"
Sep 25 16:17:58 OMV kernel: [1227535.250045] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.250608] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.251129] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.251743] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.252354] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.253014] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.253608] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.254156] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.254856] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.255428] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.256004] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.256596] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.257211] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.257826] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.258437] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.259166] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.259887] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.261625] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.263292] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.264956] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.266590] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.268301] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.269993] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV docker[8571]: time="2016-09-25T16:17:58.322128621+02:00" level=debug msg="container mounted via layerStore: /var/lib/docker/aufs/mnt/744601ea9604b5338b699bbc0d1801cbaf17c672f9f2b52931802db4166fc387"
Sep 25 16:17:58 OMV docker[8571]: time="2016-09-25T16:17:58.322486910+02:00" level=debug msg="Assigning addresses for endpoint new-jeedom's interface on network bridge"
Sep 25 16:17:58 OMV docker[8571]: time="2016-09-25T16:17:58.322523959+02:00" level=debug msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])"
Sep 25 16:17:58 OMV kernel: [1227535.271791] aufs au_opts_verify:1570:dockerd[8591]: dirperm1 breaks the protection by the permission bits on the lower branch
Sep 25 16:17:58 OMV kernel: [1227535.295907] device veth5e168a5 entered promiscuous mode
Sep 25 16:17:58 OMV kernel: [1227535.295987] IPv6: ADDRCONF(NETDEV_UP): veth5e168a5: link is not ready
Sep 25 16:17:58 OMV docker[8571]: time="2016-09-25T16:17:58.668223174+02:00" level=debug msg="Assigning addresses for endpoint new-jeedom's interface on network bridge"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.507456024+02:00" level=debug msg="Programming external connectivity on endpoint new-jeedom (82cf6c0d2164866e940675210b6ee34f884023bcd00409996786325e95770270)"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.521280835+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 51826 -j DNAT --to-destination 172.17.0.2:51826 ! -i docker0]"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.524313438+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 51826 -j ACCEPT]"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.527031150+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 51826 -j MASQUERADE]"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.532885009+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8083 -j DNAT --to-destination 172.17.0.2:8083 ! -i docker0]"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.535967268+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 8083 -j ACCEPT]"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.538906739+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 8083 -j MASQUERADE]"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.545124603+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 9080 -j DNAT --to-destination 172.17.0.2:80 ! -i docker0]"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.548092701+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 80 -j ACCEPT]"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.550892232+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 80 -j MASQUERADE]"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.557130512+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 9022 -j DNAT --to-destination 172.17.0.2:22 ! -i docker0]"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.560167510+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 22 -j ACCEPT]"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.563779468+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 22 -j MASQUERADE]"
Sep 25 16:17:59 OMV avahi-daemon[742]: Withdrawing workstation service for vethc09cc34.
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.724190714+02:00" level=debug msg="sandbox set key processing took 62.612237ms for container 0a502a0222d5eb202e650dfc516adf2992693b9eed5e547f762140927943921b"
Sep 25 16:17:59 OMV kernel: [1227536.671267] IPv6: ADDRCONF(NETDEV_CHANGE): veth5e168a5: link becomes ready
Sep 25 16:17:59 OMV kernel: [1227536.671292] docker0: port 1(veth5e168a5) entered forwarding state
Sep 25 16:17:59 OMV kernel: [1227536.671311] docker0: port 1(veth5e168a5) entered forwarding state
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.806991062+02:00" level=error msg="containerd: start container" error="oci runtime error: no such file or directory" id=0a502a0222d5eb202e650dfc516adf2992693b9eed5e547f762140927943921b
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.814675394+02:00" level=error msg="Create container failed with error: oci runtime error: no such file or directory"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.814784977+02:00" level=debug msg="attach: stdout: end"
Sep 25 16:17:59 OMV docker[8571]: time="2016-09-25T16:17:59.815020573+02:00" level=debug msg="attach: stderr: end"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.202462130+02:00" level=debug msg="Revoking external connectivity on endpoint new-jeedom (82cf6c0d2164866e940675210b6ee34f884023bcd00409996786325e95770270)"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.203324200+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D DOCKER -p tcp -d 0/0 --dport 51826 -j DNAT --to-destination 172.17.0.2:51826 ! -i docker0]"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.206597212+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 51826 -j ACCEPT]"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.209625262+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 51826 -j MASQUERADE]"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.213263322+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D DOCKER -p tcp -d 0/0 --dport 8083 -j DNAT --to-destination 172.17.0.2:8083 ! -i docker0]"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.216311765+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 8083 -j ACCEPT]"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.219146529+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 8083 -j MASQUERADE]"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.222571077+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D DOCKER -p tcp -d 0/0 --dport 9080 -j DNAT --to-destination 172.17.0.2:80 ! -i docker0]"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.225599732+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 80 -j ACCEPT]"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.228463668+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 80 -j MASQUERADE]"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.241148966+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D DOCKER -p tcp -d 0/0 --dport 9022 -j DNAT --to-destination 172.17.0.2:22 ! -i docker0]"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.245197146+02:00" level=debug msg="/sbin/iptables, [--wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 22 -j ACCEPT]"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.248487521+02:00" level=debug msg="/sbin/iptables, [--wait -t nat -D POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 22 -j MASQUERADE]"
Sep 25 16:18:00 OMV avahi-daemon[742]: Withdrawing workstation service for vethc09cc34.
Sep 25 16:18:00 OMV kernel: [1227537.289940] docker0: port 1(veth5e168a5) entered disabled state
Sep 25 16:18:00 OMV kernel: [1227537.291234] device veth5e168a5 left promiscuous mode
Sep 25 16:18:00 OMV kernel: [1227537.291258] docker0: port 1(veth5e168a5) entered disabled state
Sep 25 16:18:00 OMV avahi-daemon[742]: Withdrawing workstation service for veth5e168a5.
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.364012818+02:00" level=debug msg="Releasing addresses for endpoint new-jeedom's interface on network bridge"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.364088702+02:00" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)"
Sep 25 16:18:00 OMV docker[8571]: time="2016-09-25T16:18:00.422164939+02:00" level=error msg="Handler for POST /v1.24/containers/0a502a0222d5eb202e650dfc516adf2992693b9eed5e547f762140927943921b/start returned error: oci runtime error: no such file or directory"
```

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 7
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 139
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.699 GiB
Name: OMV
ID: AYWJ:ZIOL:FHZH:IJ5H:SLNF:MRSM:CXB3:4PIO:O5MM:SS4V:DH66:2W5H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 27
 System Time: 2016-09-25T16:16:06.881727433+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am running on Debian:

> Linux OMV 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

**Comment by thaJeztah** [comment] 2016-09-25 15:26
I suspect this is because of `-v /dev/tty*:/dev`. The `-v` flag does not support wildcards, so looks like that will fail. Even if it _would_ work, you're bind-mounting `/dev/ttysomething` on top of `/dev` (for each `tty`). Also bind-mounting `/dev` sounds like a bad idea (not sure it actually works)

**Comment by grostim** [comment] 2016-09-25 15:37
I confirm that mounting a tty in /dev is working. I did it before. However, you're right, it seems that the wildcard might be the problem. Not sure i why i was convinced that i did it before too.

**Comment by thaJeztah** [comment] 2016-09-25 15:40
Is there a reason you need to run _privileged_ for a web server? It's _really_ insecure, basically running privileged would give the web server root access to your host (so there's no protection from the container)

**Comment by grostim** [comment] 2016-09-25 16:06
Yes, 
Jeedom is a Home Automation server. It needs access to hardware install on the host.

**Comment by mlaventure** [comment] 2016-09-26 16:04
@grostim in that case, you should just map the devices it need access to.

Unfortunately if you want to map all of your ttys, you are going to have to pass one `-v` for every single one of them.

Since the issue was caused by the wildcard, I'm closing this for now. 

Thanks.

**Closed by mlaventure** 2016-09-26 16:04 UTC
Labels: version/1.12
