### ISSUE TITLE
enable SECCOMP on CentOS 7.2

### ISSUE THREAD

**Issue by spwangbit** [docker/docker#22597] opened 2016-05-09 11:01 UTC
Hi Everyone

Has any one enable seccomp on centos7.2 with docker?

Bellow is what I meet:

[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# cat /boot/config-`uname -r` | grep CONFIG_SECCOMP=
CONFIG_SECCOMP=y
[root@localhost ~]# 

docker version is 1.11.1

the json file is 
[root@localhost ~]# cat mkdir.json 
{
    "defaultAction": "SCMP_ACT_ALLOW",
    "syscalls": [
        {
            "name": "mkdir",
            "action": "SCMP_ACT_ERRNO",
            "args": []
        }
    ]
}
[root@localhost ~]# 

But it doesn't work on centos7.2.(I get this work on ubuntu) Could anyone help?

Thanks,
Shengping

**Comment by thaJeztah** [comment] 2016-05-09 11:26
The seccomp feature also has to be enabled at compile time, otherwise you won't be able to use if. Also see the note in the documentation; https://docs.docker.com/engine/security/seccomp/

> Note: seccomp profiles require seccomp 2.2.1 and are only available starting with Debian 9 “Stretch”, Ubuntu 15.10 “Wily”, and Fedora 22. To use this feature on Ubuntu 14.04, Debian Wheezy, or Debian Jessie, you must download the latest static Docker Linux binary. This feature is currently not available on other distributions.

You can try running a static binary, but you cannot use those to run devicemapper. We did recently merge a pull request to enable this for CentOS https://github.com/docker/docker/pull/22344 (as the required version of seccomp is not available), so this will be available in the 1.12 release. Alternatively, you can install the current experimental builds, which probably have this change by now.


I'll close this issue because this is not a bug, and our issue tracker is not really for support questions; for these kind of questions, consider using;

- forums.docker.com
- the #docker IRC channel
- StackOverflow

But feel free to comment here after I closed

**Closed by thaJeztah** 2016-05-09 11:26 UTC

**Comment by spwangbit** [comment] 2016-05-10 03:32
@thaJeztah  Thanks for your quick respond.
BTW,  Where can I install he experimental builds on CentOS?

**Comment by thaJeztah** [comment] 2016-05-10 07:47
The "quick" install method is using the install script;

    curl -fsSL https://experimental.docker.com | sh

Or you can use the manual installation https://docs.docker.com/engine/installation/linux/centos/, but substitute the "main" repository with "experimental", so use;

    https://yum.dockerproject.org/repo/experimental/centos/$releasever/

In step 3 below the "Install with yum" section

**Comment by spwangbit** [comment] 2016-05-10 08:12
@thaJeztah  Thanks.
