### ISSUE TITLE
docker and systemd unit ordering

### ISSUE THREAD

**Issue by deltaskelta** [docker/docker#30859] opened 2017-02-09 08:27 UTC
I have made systemd services for some containers that each look something like this

container1.service
```
[Unit]
Description=docker container
After=network.target

[Service]
WorkingDirectory=/docker/path/
ExecStart=/usr/local/bin/docker-compose up
ExecStop=/usr/local/bin/docker-compose down
ExecReload=/usr/local/bin/docker-compose restart

[Install]
WantedBy=multi-user.target
```

container2.service

```
[Unit]
Description=docker container2
After=network.target
After=container1.service

[Service]
WorkingDirectory=/docker/path/2
ExecStart=/usr/local/bin/docker-compose up
ExecStop=/usr/local/bin/docker-compose down
ExecReload=/usr/local/bin/docker-compose restart

[Install]
WantedBy=multi-user.target
```

Now I have these in different compose files because I need to be able to take some down individually from time to time. `container2` is NGINX and if it doesn't find the port it wants to attach to (opened in container 1) then it fails to start. 

You can see I have stated that it should start in systemd after container 1, but it gets a bit confusing without specifying what [systemd type](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=) the service is. This is hard because most of the types seem to rely on the process forking or returning in some way, but `docker-compose up` attaches to the container and keeps the process running (it seems in most use cases). Currently, it just calls the `ExecStart=docker-compose up` and then moves on, not caring what happened after it was called. 

I could specify the `-d` option of `docker-compose up` but then I would lose the logging capabilities of systemd which is half the reason why I like using it.

[https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=](notify) seems like the service type I should be using, but the nature of docker makes that a little bit harder since it is not the host machine I am on. 

Is there a preferred way to accomplish this? or another solution I cannot see? So far I have resorted to adding `ExecStartPre=/bin/sleep 2` which delays execution for 2 seconds and gives the other units time to boot up properly.

**Comment by thaJeztah** [comment] 2017-03-21 12:49
In general, this is not something that `docker-compose` was designed for. It may work, but it's not where the focus of the project is. Controlling docker compose through systemd is adding a lot of extra moving parts to your system; systemd, monitoring docker compose, which is monitoring/managing the docker daemon over the remote API (and in its turn, controlling `containerd`, and `runc`). 

> I could specify the -d option of docker-compose up but then I would lose the logging capabilities of systemd which is half the reason why I like using it.

You can use the `journald` or `syslog` logging drivers for your container to have the containers directly log to journald or your syslog. (see https://docs.docker.com/engine/admin/logging/overview/).

If you set a restart policy on your containers, `dockerd` will automatically restart them on reboot of the system.

> container2 is NGINX and if it doesn't find the port it wants to attach to (opened in container 1) then it fails to start.

When designing your services, it's important to take failures into account; not just when _starting_ the container/service. Dependent services may not be available (yet), may be restarted, updated, or network-connectivity may fail out of control of docker. 

As a very basic example, the official WordPress image has a retry-loop that checks if the dependent service (MySQL in this case) is available, and accepting connections; https://github.com/docker-library/wordpress/blob/3a1ca61731e6070764d5b7235e3b6617798b8af8/php5.6/apache/docker-entrypoint.sh#L190-L201

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-21 12:49 UTC
Labels: area/systemd, kind/question

**Comment by deltaskelta** [comment] 2017-03-31 09:17
Thanks for your reply. I guess I didn't occur to me that docker offers nearly everything systemd would be giving me. Thank you for your detailed reply!
