### ISSUE TITLE
[v1.12.0-rc4] : SWARM expose port

### ISSUE THREAD

**Issue by Quentinvarquet** [docker/docker#25054] opened 2016-07-26 09:12 UTC
Hello, it's not a bug, just a question ! :-) 

I am using since 2 hours now the version v1.12.0-rc4 of Docker (Wanted to try swarm).

It's working well on 3 servers (really amazing !) but I have a question.

If I want to deploy a tomcat container, how can I expose in an easy way the port 8080 (for example)...

Thank you !

**Comment by thaJeztah** [comment] 2016-07-26 10:27
```
docker service create -p 8080:8080 .....
```

should do that, see https://docs.docker.com/engine/reference/commandline/service_create/

note, however, that those ports are *not* published for individual containers (i.e. in `docker ps`, you won't see that those ports are exposed), because swarm mode uses a built-in load balancer for services.

I'll close this issue, because this is a support question, not a bug, and our issue tracker is not intended for that, but feel free to continue the discussion

**Closed by thaJeztah** 2016-07-26 10:27 UTC

**Comment by Quentinvarquet** [comment] 2016-07-26 12:48
Perfect, it's working. Thank you ! :-)

**Comment by Quentinvarquet** [comment] 2016-07-26 13:13
Just one more question, the -p 8080:8080 is working well but when I update my service 

`docker service update --image tomcat:9-alpine tomcat `

The service is updated fine but... the exposed port (8080) is not working anymore.

I also tried : 

`docker service update -p 8080:8080 --image tomcat:9-alpine tomcat `

Any idea ?
