### ISSUE TITLE
Proposal: display container name in the stats command

### ISSUE THREAD

**Issue by ripcurld00d** [docker/docker#24543] opened 2016-07-12 16:44 UTC
Unless specified differently, show containers names.
Here are some examples:

## docker stats (displays containers names)
```bash
$ docker stats
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O           PIDS
crazy_yona          0.04%               42.64 MB / 12.28 GB   0.35%               7.66 kB / 1.102 kB    11.07 MB / 0 B      0
vivid_linus         0.15%               308.5 MB / 12.28 GB   2.51%               8.599 kB / 1.168 kB   59.48 MB / 0 B      0
```

## use the --show-id switch to display containers ids
```bash
$ docker stats --show-id
CONTAINER            CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O           PIDS
314839bc9181         0.04%               42.64 MB / 12.28 GB   0.35%               7.66 kB / 1.102 kB    11.07 MB / 0 B      0
77e4dedd37de         0.15%               308.5 MB / 12.28 GB   2.51%               8.599 kB / 1.168 kB   59.48 MB / 0 B      0
```

## specifying a particular container name with --show-id will display its ID
```bash
$ docker stats --show-id crazy_yona
CONTAINER            CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O           PIDS
314839bc9181         0.04%               42.64 MB / 12.28 GB   0.35%               7.66 kB / 1.102 kB    11.07 MB / 0 B      0
```

## specifying a container id w/o the --show-id switch will display its name
```bash
$ docker stats 314839bc9181
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O           PIDS
crazy_yona          0.04%               42.64 MB / 12.28 GB   0.35%               7.66 kB / 1.102 kB    11.07 MB / 0 B      0
```

**Comment by thaJeztah** [comment] 2016-07-12 18:07
Hi @ripcurld00d, looks like this is a duplicate of https://github.com/docker/docker/issues/20973. There was a PR for that, but instead of adding more columns, we decided to prefer a `--format` flag for `docker stats` to allow customizing the output; see https://github.com/docker/docker/pull/21185#issuecomment-196401469

I'll close this issue here, please continue the discussion on https://github.com/docker/docker/issues/20973.

**Closed by thaJeztah** 2016-07-12 18:07 UTC

**Comment by thaJeztah** [comment] 2017-09-28 19:24
I opened a new PR for changing the default format to show `CONTAINER ID` (truncated) and `NAME` by default, and add a `--no-trunc` flag to docker stats. The PR was just merged, so will be in an upcoming Docker release (17.10 or 17.11); https://github.com/docker/cli/pull/565
