### ISSUE TITLE
Mount volume from docker container at another location

### ISSUE THREAD

**Issue by JoyceBabu** [docker/docker#22102] opened 2016-04-17 08:29 UTC
Is it possible to mount a volume from a data container at a location other than the one specified in the data container?

If I create a data container with 
`docker create -v /data --name mydata alpine`

Can I mount the location `/data` from the `mydata` container at a location other than `/data` on the new new container?

**Comment by thaJeztah** [comment] 2016-04-17 09:43
Not if you're using `--volumes-from`; that option is just for convenience, so that you don't have to specify the path.

However, docker now has volume management functions (`docker volume create`, `docker volume ls`), so in many cases, creating data-only containers is no longer needed. For example;


    docker volume create --name=mydata

    docker run -d -v mydata:/var/lib/mysql mysql


I'm going to close this issue, because this is a question, not a bug, and the issue tracker is meant for tracking bugs. But I hope the above helps you further.

For questions like this, consider using;

- forums.docker.com
- the #docker-user IRC channel
- StackOverflow

Feel free to comment here after I've closed

**Closed by thaJeztah** 2016-04-17 09:43 UTC

**Comment by JoyceBabu** [comment] 2016-04-17 10:03
Thank you.
