### ISSUE TITLE
Removing Images Error

### ISSUE THREAD

**Issue by gjvoit** [docker/docker#15562] opened 2015-08-13 15:12 UTC
Hello,

Currently running Docker on AWS with Amazon Linux AMI. Docker is working perfectly fine, but I'm just having some issues with removing old / untagged images. I believe we had this working last week with the same commands, but now our old images are not being properly deleted. I've managed to delete some of them, but even going through by hand doesn't work.

I have searched around a fair amount and it seems that under normal circumstances I should be able to remove any images so long as they are not referenced in a container.

```shell
$docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2/1.6.2
OS/Arch (server): linux/amd64
```

```shell
$ docker info
Containers: 5
Images: 83
Storage Driver: devicemapper
 Pool Name: docker-202:1-263848-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.513 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.45 GB
 Metadata Space Used: 5.222 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.14.35-28.38.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.03
CPUs: 1
Total Memory: 996.3 MiB
```

Running docker ps -a returns the following:
```shell 
docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Running docker images -a returns the following:

```shell
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
gvoit/testimage     1.0                 a19781af8a99        19 hours ago        263 MB
gjvoit/testimage    1.0                 a19781af8a99        19 hours ago        263 MB
<none>              <none>              11d3e1492b84        19 hours ago        263 MB
<none>              <none>              8251da35e7a7        5 days ago          188.3 MB
<none>              <none>              e5855facec0b        5 days ago          188.3 MB
<none>              <none>              5bff21ba5409        5 days ago          188.3 MB
<none>              <none>              6071b4945dcf        5 days ago          188.1 MB
database            latest              730d1d72bda2        2 weeks ago         265.3 MB
postgres            latest              730d1d72bda2        2 weeks ago         265.3 MB
<none>              <none>              3e840dbb5474        2 weeks ago         265.3 MB
<none>              <none>              4df8a54cf33a        2 weeks ago         265.3 MB
<none>              <none>              09e02a9f8afe        2 weeks ago         265.3 MB
<none>              <none>              39172f8b90f2        2 weeks ago         265.3 MB
<none>              <none>              c5d75e7f9094        2 weeks ago         265.3 MB
<none>              <none>              3fa84fbfdec9        2 weeks ago         265.3 MB
<none>              <none>              a95070c23e86        2 weeks ago         265.3 MB
<none>              <none>              64957633c267        2 weeks ago         265.3 MB
<none>              <none>              a814508841fa        2 weeks ago         148.9 MB
<none>              <none>              49915906faae        2 weeks ago         148.9 MB
<none>              <none>              b41b53da5fba        2 weeks ago         148.9 MB
<none>              <none>              02fa71f1fa38        2 weeks ago         148.9 MB
<none>              <none>              0b82f508e063        2 weeks ago         148.9 MB
<none>              <none>              e07b5a739ed9        2 weeks ago         148.9 MB
<none>              <none>              c783ebe7a1d4        2 weeks ago         148.9 MB
<none>              <none>              8b6b2a3b7f9c        2 weeks ago         129.3 MB
<none>              <none>              22ed955cce18        4 weeks ago         125.6 MB
<none>              <none>              26a84c436db4        4 weeks ago         125.5 MB
<none>              <none>              9a61b6b1315e        4 weeks ago         125.2 MB
<none>              <none>              902b87aaaec9        4 weeks ago         125.2 MB
```

Attempting to remove any one of these untagged images by hand, e.g.:

```shell
docker rmi 11d3e1492b84
Error response from daemon: Conflict, 11d3e1492b84 wasn't deleted
FATA[0000] Error: failed to remove one or more images
```

I've also attempted the remove all strategy with 
```shell
docker rmi $(docker images | grep "^<none>" | awk '{print $3}')
docker rmi $(docker images -q --filter "dangling=true")
```

But these do not work either and it simply states that rmi requires 1 argument (presumably because grep returns no valid images which match these filters). These commands are the common solutions which have worked for others.

Not a particularly pressing issue, but I would like to know why this is happening.

**Comment by Pensu** [comment] 2015-08-14 05:56
@gjvoit Can you try 'docker rmi -f <image_id>'.

**Comment by thaJeztah** [comment] 2015-08-14 08:26
What you're seeing is **not a bug**; the "untagged" images are actually the "intermediate" layers of other images, and Docker refuses to remove those image because *they're still used by other images*. For example, image `11d3e1492b84` is probably a layer of the `gjvoit/testimage` above it (you can see what the command was that produced that image, using `docker inspect -f "{{ .ContainerConfig.Cmd }}" 11d3e1492b84`.

For that reason, `$(docker images -q --filter "dangling=true")` also doesn't return any images, because *none* of the images is "dangling" (unused/unreferenced).

In *general*, you should never need `docker images -a` in daily use; it's useful for debugging but the intermediate layers are basically an implementation detail of Docker (there's even some people that are in favor of removing the `-a` flag)

To remove images, simply remove the "tagged" images that you no longer need (e.g., `docker rmi gjvoit/testimage:1.0 gvoit/testimage:1.0` to remove the `gjvoit/testimage:1.0` and `gvoit/testimage:1.0` images), and Docker will also remove the layers that are no longer used.

To see if there are redundant ("dangling") images on your machine, you can find those with `docker images -q --filter "dangling=true"`, and clean them up using;

    # Cleanup (intermediate) images that are no longer used by any other image
    docker rmi $(docker images -q --filter "dangling=true")

And docker will remove those images (if any exist)

Hope this helps!

I'm going to close this issue, because this is not a bug, but feel free to comment here after I've closed this

**Closed by thaJeztah** 2015-08-14 08:26 UTC

**Comment by gjvoit** [comment] 2015-08-28 18:07
Thanks very much for the explanation!

**Comment by thaJeztah** [comment] 2015-08-28 21:17
You're welcome, @gjvoit
