### ISSUE TITLE
Links between to containers in different stack in Docker Swarm mode enabled

### ISSUE THREAD

**Issue by oliyavan** [docker/docker#31908] opened 2017-03-17 00:36 UTC
we are trying to create the swarm cluster with One Leader and Two workers.
it is done both nodes are up and running.
Requirement:
we try to create compose file(v3) with two images in it, when we run the docker stack deploy command it should deploy the containers with Links and communication between the container should happen via links.

Actual Result:
When we try to launch the two container via same compose file with swarm mode enabled it is not allowing us to launch two different containers as part of single Stack.
I tried one more thing like create two stack one for my web container and otheris db , but in that case also links are not working.

Need Solution:
In this cases i need to establish the communication between web container to DB container because of the link issue commication not happening.

Could you please check and let me if you any solution for that or any other work around.

Docker version: Latest
Docker Compose: Latest

**Comment by thaJeztah** [comment] 2017-03-17 00:43
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug.

If you think there's a bug, provide the information that's requested in the issue template (https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue; "latest version" is not sufficient to verify what you're running.

Also make sure to include the exact steps to reproduce, and, for example a docker-compose files to reproduce, and the commands you ran

**Closed by thaJeztah** 2017-03-17 00:43 UTC
Labels: area/swarm

**Comment by oliyavan** [comment] 2017-03-17 01:28
Thanks for your guidance.
