### ISSUE TITLE
Docker hangs on building image

### ISSUE THREAD

**Issue by verkholantsev** [docker/docker#21114] opened 2016-03-11 09:51 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# hangs for a lot of time
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Machine in OpenStack

**Steps to reproduce the issue:**
1. Create `package.json`
2. Add step `ADD ./package.json /var/www/` to `Dockerfile`
3. Run `docker build`

**Describe the results you received:**
Docker hangs

**Describe the results you expected:**
Docker does not hang

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment] 2016-03-11 15:24
Can you send the daemon a `SIGUSR1` while it's hanging and put the output in a gist?
This will allow us to see the stacktrace of the running daemon.

**Comment by verkholantsev** [comment] 2016-03-12 07:51
```bash
$ sudo cat /var/log/upstart/docker.log

INFO[0195] === BEGIN goroutine stack dump ===
goroutine 51 [running]:
github.com/docker/docker/pkg/signal.DumpStacks()
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:67 +0x98
github.com/docker/docker/daemon.setupDumpStackTrap.func1(0xc82000cd20)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:18 +0x5e
created by github.com/docker/docker/daemon.setupDumpStackTrap
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/debugtrap_unix.go:20 +0x12a

goroutine 1 [chan receive, 2 minutes]:
main.(*DaemonCli).CmdDaemon(0xc82032b8a0, 0xc82000a090, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/docker/daemon.go:305 +0x20a7
reflect.callMethod(0xc8205bade0, 0xc821311c78)
	/usr/local/go/src/reflect/value.go:628 +0x1fc
reflect.methodValueCall(0xc82000a090, 0x0, 0x0, 0x1, 0xc8205bade0, 0x0, 0x0, 0xc8205bade0, 0xc8205bc990, 0x47a034, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc8205bad50, 0xc82000a090, 0x1, 0x1, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/cli/cli.go:89 +0x383
main.main()
	/usr/src/docker/docker/docker.go:63 +0x43c

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 50 [select, 2 minutes, locked to thread]:
runtime.gopark(0x194b200, 0xc820027f28, 0x164adf0, 0x6, 0x441d18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820027f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820027f28)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 125 [chan receive, 2 minutes]:
main.setupConfigReloadTrap.func1(0xc8205b7080, 0x172a230, 0x17, 0xc820080700, 0xc8209a7540)
	/usr/src/docker/docker/daemon_unix.go:62 +0x68
created by main.setupConfigReloadTrap
	/usr/src/docker/docker/daemon_unix.go:67 +0x162

goroutine 157 [select]:
github.com/docker/docker/api/server/router/build.(*buildRouter).postBuild.func4(0xc8217c7b60, 0xc820bc9490, 0xc8212e0f70)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/build/build_routes.go:246 +0xfd
created by github.com/docker/docker/api/server/router/build.(*buildRouter).postBuild
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/build/build_routes.go:252 +0x14d1

goroutine 82 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd4cc0aca68, 0x72, 0xc82000e120)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820becae0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820becae0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readMsg(0xc820beca80, 0xc820f30bd0, 0x10, 0x10, 0xc820b52020, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:286 +0x33d
net.(*UnixConn).ReadMsgUnix(0xc820323038, 0xc820f30bd0, 0x10, 0x10, 0xc820b52020, 0x1000, 0x1000, 0xc81ffa56ff, 0x0, 0xc81ffa56ff, ...)
	/usr/local/go/src/net/unixsock_posix.go:150 +0x15f
github.com/godbus/dbus.(*oobReader).Read(0xc820b52000, 0xc820f30bd0, 0x10, 0x10, 0x88, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:21 +0xbf
io.ReadAtLeast(0x7fd4cc05c988, 0xc820b52000, 0xc820f30bd0, 0x10, 0x10, 0x10, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7fd4cc05c988, 0xc820b52000, 0xc820f30bd0, 0x10, 0x10, 0x51, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x62
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc820d56eb0, 0xc82138e060, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:85 +0x1bc
github.com/godbus/dbus.(*Conn).inWorker(0xc820ee27e0)
	/usr/src/docker/vendor/src/github.com/godbus/dbus/conn.go:248 +0x55
created by github.com/godbus/dbus.(*Conn).Auth
	/usr/src/docker/vendor/src/github.com/godbus/dbus/auth.go:118 +0xf50

goroutine 20 [select, 2 minutes]:
github.com/docker/libnetwork.(*controller).watchLoop(0xc82035c210)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/store.go:409 +0x140
created by github.com/docker/libnetwork.(*controller).startWatch
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/store.go:423 +0x100

goroutine 83 [chan receive, 2 minutes]:
github.com/godbus/dbus.(*Conn).outWorker(0xc820ee27e0)
	/usr/src/docker/vendor/src/github.com/godbus/dbus/conn.go:385 +0x55
created by github.com/godbus/dbus.(*Conn).Auth
	/usr/src/docker/vendor/src/github.com/godbus/dbus/auth.go:119 +0xf75

goroutine 84 [chan receive, 2 minutes]:
github.com/docker/libnetwork/iptables.signalHandler()
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/iptables/firewalld.go:92 +0x54
created by github.com/docker/libnetwork/iptables.FirewalldInit
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/iptables/firewalld.go:48 +0x17b

goroutine 110 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd4cc0ac9a8, 0x72, 0xc82000e120)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820bc8ae0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820bc8ae0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820bc8a80, 0x0, 0x7fd4cc0ab728, 0xc820b17960)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*UnixListener).AcceptUnix(0xc820a1cb00, 0x346c72756362696c, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:304 +0x53
net.(*UnixListener).Accept(0xc820a1cb00, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:314 +0x41
github.com/docker/libnetwork.(*controller).acceptClientConnections(0xc82035c210, 0xc820bc8a10, 0x63, 0x7fd4cc0abbf0, 0xc820a1cb00)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox_externalkey_unix.go:130 +0x45
created by github.com/docker/libnetwork.(*controller).startExternalKeyListener
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox_externalkey_unix.go:124 +0x28a

goroutine 134 [chan receive, 2 minutes]:
github.com/docker/docker/daemon.(*Daemon).execCommandGC(0xc82057cd80)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/exec.go:237 +0x8e
created by github.com/docker/docker/daemon.NewDaemon
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:807 +0x30f1

goroutine 133 [chan receive]:
github.com/docker/docker/daemon.(*statsCollector).run(0xc82127b880)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/stats_collector_unix.go:99 +0xcd
created by github.com/docker/docker/daemon.(*Daemon).newStatsCollector
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/stats_collector_unix.go:38 +0x1af

goroutine 126 [chan receive, 2 minutes]:
github.com/docker/docker/api/server.(*Server).serveAPI(0xc82000cc60, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:102 +0x1af
github.com/docker/docker/api/server.(*Server).Wait(0xc82000cc60, 0xc8205b70e0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:217 +0x2b
created by main.(*DaemonCli).CmdDaemon
	/usr/src/docker/docker/daemon.go:287 +0x1f7a

goroutine 127 [chan receive, 2 minutes]:
github.com/docker/docker/pkg/signal.Trap.func1(0xc8205b7140, 0xc8213503f0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:29 +0x71
created by github.com/docker/docker/pkg/signal.Trap
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/signal/trap.go:55 +0x21a

goroutine 129 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd4cc0acb28, 0x72, 0xc82000e120)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203934f0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203934f0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820393490, 0x0, 0x7fd4cc0ab728, 0xc820d8ce60)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*UnixListener).AcceptUnix(0xc82032bde0, 0xc8214a3dc8, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:304 +0x53
net.(*UnixListener).Accept(0xc82032bde0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:314 +0x41
net/http.(*Server).Serve(0xc82000ccc0, 0x7fd4cc0abbf0, 0xc82032bde0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/docker/docker/api/server.(*HTTPServer).Serve(0xc82032bee0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:121 +0x47
github.com/docker/docker/api/server.(*Server).serveAPI.func1(0xc820dfb500, 0xc82032bee0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:94 +0x13d
created by github.com/docker/docker/api/server.(*Server).serveAPI
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:98 +0x148

goroutine 162 [syscall]:
syscall.Syscall6(0xa5, 0xc820b7ec40, 0xc820b7ecb0, 0xc8208ee830, 0x0, 0x0, 0x0, 0x8771b2, 0xc8208ee820, 0x1)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.mount(0xc820b7eaf0, 0x65, 0xc820b7e7e0, 0x66, 0x1646ca0, 0x4, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:224 +0x158
syscall.Mount(0xc820b7eaf0, 0x65, 0xc820b7e7e0, 0x66, 0x1646ca0, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/syscall/syscall_linux.go:800 +0x95
github.com/docker/docker/pkg/mount.mount(0xc820b7eaf0, 0x65, 0xc820b7e7e0, 0x66, 0x1646ca0, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/mount/mounter_linux.go:8 +0x9c
github.com/docker/docker/pkg/mount.ForceMount(0xc820b7eaf0, 0x65, 0xc820b7e7e0, 0x66, 0x1646ca0, 0x4, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/mount/mount.go:49 +0xbb
github.com/docker/docker/pkg/mount.Mount(0xc820b7eaf0, 0x65, 0xc820b7e7e0, 0x66, 0x1646ca0, 0x4, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/mount/mount.go:40 +0x100
github.com/docker/docker/daemon/graphdriver/devmapper.(*DeviceSet).MountDevice(0xc820065d40, 0xc820e52c80, 0x45, 0xc820b7e7e0, 0x66, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/deviceset.go:2192 +0xa43
github.com/docker/docker/daemon/graphdriver/devmapper.(*Driver).Get(0xc820c095e0, 0xc820e52c80, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/graphdriver/devmapper/driver.go:168 +0x47a
github.com/docker/docker/daemon/graphdriver.(*NaiveDiffDriver).Get(0xc8209088c0, 0xc820e52c80, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:26 +0xa6
github.com/docker/docker/layer.(*layerStore).initMount(0xc8209089c0, 0xc820e07ac0, 0x40, 0xc820d17380, 0x40, 0x0, 0x0, 0xc820974ac0, 0x0, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/layer/layer_store.go:562 +0x267
github.com/docker/docker/layer.(*layerStore).CreateRWLayer(0xc8209089c0, 0xc820e07000, 0x40, 0xc820e52be0, 0x47, 0x0, 0x0, 0xc820974ac0, 0x0, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/layer/layer_store.go:454 +0x452
github.com/docker/docker/daemon.(*Daemon).setRWLayer(0xc82057cd80, 0xc8210c1dc0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/create.go:158 +0x1f9
github.com/docker/docker/daemon.(*Daemon).create(0xc82057cd80, 0x0, 0x0, 0xc82034a400, 0xc82170a900, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/create.go:87 +0x32a
github.com/docker/docker/daemon.(*Daemon).ContainerCreate(0xc82057cd80, 0x0, 0x0, 0xc82034a400, 0xc82170a900, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/create.go:42 +0x4a4
github.com/docker/docker/builder/dockerfile.(*Builder).runContextCommand(0xc8212e0f70, 0xc820fd83a0, 0x2, 0x2, 0x101, 0x163fc80, 0x3, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/builder/dockerfile/internals.go:187 +0xfd0
github.com/docker/docker/builder/dockerfile.add(0xc8212e0f70, 0xc820fd83a0, 0x2, 0x2, 0x0, 0xc820d604e0, 0x1c, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/builder/dockerfile/dispatchers.go:162 +0x27d
github.com/docker/docker/builder/dockerfile.(*Builder).dispatch(0xc8212e0f70, 0x7, 0xc820bc2850, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/builder/dockerfile/evaluator.go:198 +0x1261
github.com/docker/docker/builder/dockerfile.(*Builder).Build(0xc8212e0f70, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/builder/dockerfile/builder.go:136 +0x34b
github.com/docker/docker/api/server/router/build.(*buildRouter).postBuild(0xc8209a7520, 0x7fd4cf1a62c0, 0xc82138f2c0, 0x7fd4cf1a6190, 0xc82035dce0, 0xc820e562a0, 0xc82138f200, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/build/build_routes.go:255 +0x14e2
github.com/docker/docker/api/server/router/build.(*buildRouter).(github.com/docker/docker/api/server/router/build.postBuild)-fm(0x7fd4cf1a62c0, 0xc82138f2c0, 0x7fd4cf1a6190, 0xc82035dce0, 0xc820e562a0, 0xc82138f200, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/build/build.go:31 +0x74
github.com/docker/docker/api/server.versionMiddleware.func1(0x7fd4cf1a62c0, 0xc82138f2c0, 0x7fd4cf1a6190, 0xc82035dce0, 0xc820e562a0, 0xc82138f200, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7fd4cc0ab068, 0xc82000f4f0, 0x7fd4cf1a6190, 0xc82035dce0, 0xc820e562a0, 0xc82138f200, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7fd4cc0ab068, 0xc82000f4f0, 0x7fd4cf1a6190, 0xc82035dce0, 0xc820e562a0, 0xc82138f200, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fd4cf1a6190, 0xc82035dce0, 0xc820e562a0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
net/http.HandlerFunc.ServeHTTP(0xc820d8ca00, 0x7fd4cf1a6190, 0xc82035dce0, 0xc820e562a0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc821073a90, 0x7fd4cf1a6190, 0xc82035dce0, 0xc820e562a0)
	/usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc821321c50, 0x7fd4cf1a6190, 0xc82035dce0, 0xc820e562a0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc82000ccc0, 0x7fd4cf1a6190, 0xc82035dce0, 0xc820e562a0)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82133c790)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 156 [IO wait]:
net.runtime_pollWait(0x7fd4cc0ac8e8, 0x72, 0xc82000e120)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820a595d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820a595d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820a59570, 0xc821902000, 0x8000, 0x8000, 0x0, 0x7fd4cf171050, 0xc82000e120)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820a365e8, 0xc821902000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
io.copyBuffer(0x7fd4cf1a6898, 0xc820322588, 0x7fd4cf1a6098, 0xc820a365e8, 0xc821902000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:381 +0x247
io.Copy(0x7fd4cf1a6898, 0xc820322588, 0x7fd4cf1a6098, 0xc820a365e8, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:351 +0x64
net/http.(*conn).closeNotify.func1(0xc820322588, 0x7fd4cf1a6098, 0xc820a365e8, 0xc82133c790)
	/usr/local/go/src/net/http/server.go:182 +0x64
created by net/http.(*conn).closeNotify
	/usr/local/go/src/net/http/server.go:188 +0x361

=== END goroutine stack dump ===
```

**Comment by verkholantsev** [comment] 2016-03-12 10:42
I think I found a reason of the problem. Here is the output of `docker info` (it does not hang after reboot):

```bash
$ docker info
...
Storage Driver: devicemapper
 ...
 Data Space Used: 107.4 GB
 Data Space Total: 107.4 GB
 Data Space Available: 0 B
...
```

I think docker should handle this error in more explicit way.

There is still available space on machine:

```bash
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1       158G  104G   48G  69% /
none            4,0K     0  4,0K   0% /sys/fs/cgroup
udev            7,9G  8,0K  7,9G   1% /dev
tmpfs           1,6G  348K  1,6G   1% /run
none            5,0M     0  5,0M   0% /run/lock
none            7,9G     0  7,9G   0% /run/shm
none            100M     0  100M   0% /run/user
```

Why does not devicemapper use >40G of free space?

**Comment by thaJeztah** [comment] 2016-03-12 13:37
Thanks @verkholantsev I think this is a duplicate of https://github.com/docker/docker/issues/20707; there will be an option in Docker 1.11 that allows you to set a minimum amount of free space, see https://github.com/docker/docker/pull/20786.


> Why does not devicemapper use >40G of free space?

Devicemapper uses its own device, that is initialized with a specified amount of space (100GB in your case); for more information see https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/

Based on the above, I think this issue should be closed, as it's a duplicate (or closely related to #20707)

**Comment by verkholantsev** [comment] 2016-03-12 14:41
Thanks a lot!

**Closed** 2016-03-12 14:44 UTC
Labels: status/more-info-needed

**Comment by thaJeztah** [comment] 2016-03-12 14:45
Thanks for reporting @verkholantsev, it's appreciated!
