### ISSUE TITLE
Image does not work in a custom Linux

### ISSUE THREAD

**Issue by jvanz** [docker/docker#19341] opened 2016-01-14 19:53 UTC
Hi folks

I need your help to figured out what is exactly happening in my Docker environment. First of all, I have tried to post a doubt in forums but I could not log in it. https://twitter.com/vanzstuff/status/687708049918832641

Description of problem:

There are a image with [monasca demo](https://hub.docker.com/r/monasca/demo/). The script executed within it run all necessary applications, OpenStack, kafka, MySQL, influxdb and so on. I have two environments, one the container works and other one does not. In the problematic one (take a look in environment detail section below)some applications (MySQL) does not start.

I would like help to figure out why it happens. Until now, even if without trust it will work I have tried to fix the issue if like the issue is in MySQL configuration. But nothing works. As I said before, I do not believe the issue is in the MySQL configuration because the same image works in other environment. Before try to port the newest Docker version I would like to know what I can do to check if there are missing some Docker or kernel configurations. 

`docker version`:
```
root@localhost:~# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4
Git commit (client): INVALID
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4
Git commit (server): INVALID
OS/Arch (server): linux/amd64 
```

`docker info`:
```
root@localhost:~# docker info
Containers: 1
Images: 41
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 43
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.14.19-yocto-standard
Operating System: <unknown>
CPUs: 1
Total Memory: 7.791 GiB
Name: REDACTED
ID: UBUO:ZYMQ:KNW2:VIHA:U2AS:FU77:AYNC:FHHU:UYRN:TC4Z:P6TN:OBDX
```

`uname -a`:
```
root@localhost:~# uname -a
Linux nodegrid 3.14.19-yocto-standard #4 SMP PREEMPT Thu Jan 14 07:15:19 EST 2016 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):

Problematic one: It is a custom Linux running a compiled Docker 1.6.2.
Good one: Fedora 23 running Docker 1.9.1 installed from ordinary repositories

**Comment by dmcgowan** [comment] 2016-01-14 23:49
Hello @jvanz, I am not sure why you cannot access the hub forums, you should be able to log in with your hub account. If there was an intermittent problem it may be fixed by now, I seemed to be able to access just a moment ago. You can also ask questions like these on the Google group page at https://groups.google.com/forum/#!forum/docker-user and on the freenode irc #docker. 

Since this is not a describing a current bug in Docker I am going to close this issue. Feel free to reach out on one the forums for help resolving your issue. And of course if you do discover a bug in your testing, please open an issue with the unexpected behavior and any steps which would help us reproduce. Thanks.

**Closed by dmcgowan** 2016-01-14 23:49 UTC

**Comment by jvanz** [comment] 2016-01-15 02:02
Thanks, @dmcgowan. I did not remember mailing list. Sorry =/
