### ISSUE TITLE
Remote API on Fedora, Gets No response at all on requests.

### ISSUE THREAD

**Issue by yoieh** [docker/docker#29135] opened 2016-12-05 15:07 UTC
**Description**
Im trying to use the docker remote api to control the docker daemon.
Using Fedora 24 where systemd is in use. I have set it up as shown here:

[Enable Remote access to Docker API on Linux running systemd](http://stackoverflow.com/documentation/docker/3935/docker-remote-api/15951/enable-remote-access-to-docker-api-on-linux-running-systemd#t=201612051429565131415)

`# vim /etc/systemd/system/docker-tcp.socket`

```
[Unit]
Description=Docker HTTP Socket for the API

[Socket]
ListenStream=2375
BindIPv6Only=both
Service=docker.service

[Install]
WantedBy=sockets.target
```

Have tested with different ports and it still do not work.

When i try to send GET requests to the deamon it just get stuck and loads with outh no responce. In a rest client tool the requests gets timed out. 

I can see with `netstat` that a connection is `Established`

**Steps to reproduce the issue:**
1.  Setting up *docker-tcp.socket*
2. Stopping docker docker 
`# systemctl stop docker`
3. Starting docker-tcp.socket
`# systemctl start docker-tcp.socket`
4. Testing in browser on the same host as the docker daemon: 

`http://localhost:2375/_ping`

`http://127.0.0.1:2375/_ping`

`http://127.0.0.1:2375/containers/json`

In terminal:

`# curl -XGET http://127.0.0.1:2375/containers/json`

Have tested many more things but noting works.

**Describe the results you received:**

Just loading without any response at all.

**Describe the results you expected:**

200 OK with json objects?

Some sort of response at all.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
# docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-54.gite03ddb8.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      e03ddb8/1.10.3
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-54.gite03ddb8.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      e03ddb8/1.10.3
 Built:           
 OS/Arch:         linux/amd64

```

**Output of `docker info`:**

```
# docker info
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 32
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-2100931-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.203 GB
 Data Space Total: 107.4 GB
 Data Space Available: 38.63 GB
 Metadata Space Used: 6.656 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.122 (2016-04-09)
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.8.10-200.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 3.763 GiB
Name: ira
ID: VG32:L7WT:5Q5U:ESHB:LP63:4VJB:BUA5:NBRF:GFWW:6I7J:TGCG:QKVJ
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
# cat /etc/*-release
Fedora release 24 (Twenty Four)
NAME=Fedora
VERSION="24 (Workstation Edition)"
ID=fedora
VERSION_ID=24
PRETTY_NAME="Fedora 24 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:24"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=24
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=24
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 24 (Twenty Four)
Fedora release 24 (Twenty Four)
```

```
# uname -a
Linux ira 4.8.10-200.fc24.x86_64 #1 SMP Mon Nov 21 17:55:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment] 2016-12-05 15:52
To allow the daemon to be accessed remotely, you have to set the `-H` option accordingly, for example

```
docker daemon -H tcp://0.0.0.0:2375
```

or on current versions

```
dockerd -H tcp://0.0.0.0:2375
```

You can set this through a systemd drop-in file (and override the `ExecStart`); https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options

Or for the current version, use a `daemon.json` file, as described here; https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file

If you are going to make the API accessible remotely, _never_ do so without properly protecting it; https://docs.docker.com/engine/security/https/

Anyone that can access the remote API, effectively has **root access** on the host.

I'll close this issue, because this is not a bug, but feel free to ask for more information after I closed

**Closed by thaJeztah** 2016-12-05 15:52 UTC
Labels: version/1.10

**Comment by yoieh** [comment] 2016-12-05 17:34
Yes i see. Thank you sir. I have reed about the `-H` flag before and its use. I miss a explanation on where and how to implement it.

I'm suppose to control the docker daemon from inside of a container  using docker-php. My idea is to bind the socket to only listen on one local address from the container. If I'm right I would be able to do this with some help of the docker0 bridge?

This is instead of running root scripts directly on the server.

**Comment by thaJeztah** [comment] 2016-12-05 17:37
If you want to access the socket inside a container, you can use this (no changes to the daemon configuration is needed);

```
docker run -v /var/run/docker.sock:/var/run/docker.sock myimage
```

However, the same warning applies; by doing so, you give your PHP script **root** access to the host. If your container is compromised, the process inside the container can "escape" the container, and do damage on your host.

So be very careful if that container is accessible publicly

**Comment by yoieh** [comment] 2016-12-06 06:03
Yes i have also seen this  approach. But this sound even more insecure then using the docker remote API with a docker remote api client. 

It's not being accessible publicly rather a bakend system for setting up new containers throw a Administration Panel integrated with our systems.

**Comment by thaJeztah** [comment] 2016-12-06 08:55
It's not less secure, as you only allow a specific container to access the remote API (the socket exposes the same API as you would expose over tcp/ip), whereas exposing the API on 0.0.0.0:2375 would expose it to _any_ process / person that can access your docker hosts port 2375
