### ISSUE TITLE
Docker 1.12: DOCKER_OPTS in /etc/default/docker does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by ligc** [docker/docker#25357] opened 2016-08-03 07:03 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: c910f04x19k02
ID: LMTM:AZXH:4W3K:52KV:MXNO:NV6Y:YWB3:RK5B:LMWK:NIMQ:BAD4:DQLY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 9.186.91.246:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Install docker 1.12 on Ubuntu 16.04
2. Set DOCKER_OPTS in /etc/default/docker
3. service docker restart

**Describe the results you received:**

The DOCKER_OPTS in /etc/default/docker does not work

```
root@c910f04x19k02:~# cat /etc/default/docker | grep DOCKER_OPTS
# Use DOCKER_OPTS to modify the daemon startup options.
DOCKER_OPTS="--insecure-registry 9.186.91.246:5000"
root@c910f04x19k02:~# service docker restart
root@c910f04x19k02:~# ps -ef | grep -i dockerd
root      8275     1  3 02:58 ?        00:00:00 /usr/bin/dockerd -H fd:// ==========> DOCKER_OPTS does not work
root      8375 31788  0 02:58 pts/0    00:00:00 grep --color=auto -i dockerd
root@c910f04x19k02:~# 
```
I have also tried to use the file /etc/systemd/system/docker.service.d/docker.conf, as on RHEL/CentOS, but does not seem work either.

The only way that works is to modify the /lib/systemd/system/docker.service directory, to update the ExecStart to something like: ExecStart=/usr/bin/dockerd -H fd:// --insecure-registry 9.186.91.246:5000

**Describe the results you expected:**
On Ubuntu 16.04, should honor the /etc/default/docker, or /etc/systemd/system/docker.service.d/docker.conf. If needs to use /etc/systemd/system/docker.service.d/docker.conf, the documentation should be updated.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ligc** [comment] 2016-08-03 07:42
It works on Ubuntu 14.04, but not on Ubuntu 16.04

**Comment by thaJeztah** [comment] 2016-08-03 09:18
This is expected; the `/etc/default/docker` file is only used on systems running upstart and sysvinit, not on systems using systemd (see [the note at the top of that file](https://github.com/docker/docker/blob/master/contrib/init/sysvinit-debian/docker.default#L4))

To configure the daemon, either: 

- use a `/etc/docker/daemon.json` configuration file (see the [dockerd documentation for more info](https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file), which works on all systems, independent of the init system, and allows for live reloading some settings without a restart of the daemon
- use a systemd drop-in file to override the defaults on the systemd unit file; see the [systemd documentation section](https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options)

I'm closing this issue, because this is not a bug, but I hope this helps, and feel free to comment after I closed

**Closed by thaJeztah** 2016-08-03 09:18 UTC
Labels: version/1.12

**Comment by ligc** [comment] 2016-08-04 00:54
Thanks for the comment. 

If I remember correctly, the /etc/default/docker has been working correctly on my Ubuntu 16.04 with the previous Docker 1.12 RC builds, until it breaks in the 1.12 GA build.

The file /etc/docker/daemon.json does not exist on my node. do I need create it manually?

As I mentioned earlier, the systemd drop-in file does not work on my node. I created the file /etc/systemd/system/docker.service.d/docker.conf , ran systemctl deamon-reload, restart dockerd, but the option is not added to the dockerd parameter.  Did I miss something?

BTW, the doc https://docs.docker.com/engine/admin/systemd/ is difficult to follow. 

```
root@c910f04x19k02:~# cat /etc/systemd/system/docker.service.d/docker.conf 
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --insecure-registry 9.186.91.246:5000
root@c910f04x19k02:~# ps -ef | grep -i dockerd
root     11662     1  0 20:46 ?        00:00:00 /usr/bin/dockerd -H fd://
root     11783 10988  0 20:52 pts/0    00:00:00 grep --color=auto -i dockerd
root@c910f04x19k02:~# 
```

**Comment by sipicsg** [comment] 2016-08-31 13:33
As the systemd usually handles systemv type startup (/etc/init.d/docker start), it's a bit confusing if the variables from /etc/default/docker are not passed.

Preferred solution is

EnvironmentFile=/etc/default/docker
ExecStart=/usr/bin/docker daemon -H fd:// $DOCKER_OPTS

**Comment by ZanyXDev** [comment] 2017-02-05 00:58
Preferred solution is
EnvironmentFile=/etc/default/docker
ExecStart=/usr/bin/docker daemon -H fd:// $DOCKER_OPTS
work fine for me :+1
Linux ubn-300V3A 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Spritekin** [comment] 2017-05-04 02:52
This worked for me, I had to "clear" the ExecStart first.
```
[Service]
EnvironmentFile=/etc/default/docker
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// $DOCKER_OPTS
```

**Comment by shuklara** [comment] 2017-05-31 12:08
@Spritekin solution worked for me

**Comment by pranay-91** [comment] 2017-06-03 06:03
I have an aws ubuntu instance 14.04. I can login via the instance or host but cannot log in from outside.

http: server gave HTTP response to HTTPS client

Is this to do with docker?
Do i need to configure firewall and open ports in aws instance group policy? I have allowed 5000 http 80 and https 443.

`
[Service] EnvironmentFile=/etc/default/docker ExecStart= ExecStart=/usr/bin/docker daemon -H fd:// --insecure-registry ec2-35-160-82-207.us-west-2.compute.amazonaws.com:5000 35.160.82.207:5000
`

Ubuntu 16.04 aws instance
Docker version 17.03.1-ce, build c6d412e

By the way ubuntu does not has systemctl so i use its using systemd

**Comment by thaJeztah** [comment] 2017-06-05 22:43
@pranay-91 the recommended approach is to use a `daemon.json` configuration file (see the [`dockerd` reference documentation](https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file), for example;

```json
{
    "insecure-registries": ["ec2-35-160-82-207.us-west-2.compute.amazonaws.com:5000", "35.160.82.207:5000"]
}
```

However; it's strongly discouraged to use registries without TLS configured, as it's really insecure. [Getting a certificate](https://docs.docker.com/registry/deploying/#get-a-certificate) is really best.


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm locking the conversation on this issue, because this is not a bug, and this discussion is better done on one of the options above
