### ISSUE TITLE
`docker deploy` is experimental whereas `docker stack deploy` is not

### ISSUE THREAD

**Issue by albers** [docker/docker#28830] opened 2016-11-25 08:48 UTC
Is this intended?
According to https://github.com/docker/docker/blob/master/docs/reference/commandline/deploy.md, `docker deploy` is just an alias to `docker stack deploy`. IMHO, it makes no sense to keep it experimental.

Observed in current master.

**Comment by vdemeester** [comment] 2016-11-25 13:25
See https://github.com/docker/docker/pull/28839#issuecomment-262956917 :angel: This is by design :angel:

**Comment by vdemeester** [comment] 2016-11-25 13:39
I'll close this one for now too :angel:

**Closed by vdemeester** 2016-11-25 13:39 UTC

**Comment by albers** [comment] 2016-11-25 15:30
Ah, yes. Makes sense. Thanks very much for clarifying.
