### ISSUE TITLE
Docker unable to launch dynamic process from tomcat webapp

### ISSUE THREAD

**Issue by sridharratna** [docker/docker#13573] opened 2015-05-29 03:25 UTC
Problem Description:
Unable to launch processes dynamically from tomcat server installed on docker.

I have java web application running inside tomcat 6. And I am trying to launch another standard java utility application from my webapp class (a servlet class). But In docker container this process doesn't seem to work.

in my servlet class i have the code like
String command = "/usr/lib/jvm/java-7-oracle/jre/bin/java -Xbootclasspath/a:/usr/lib/jvm/java-7-oracle/jre/lib/jfxrt.jar -jar /var/lib/apache-tomcat-6.0.43/lib/speedtest.jar"
Runtime.getRuntime().exec(command)

When servlet is invoked speedtest application should be launched in another JVM. 
This web app is working fine in VMWare and KVM an doracle virtual box.

If the same command run on bash prompt it runs fine.

docker version : 
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0

Docker Info:
Containers: 1
Images: 26
Storage Driver: devicemapper
 Pool Name: docker-253:0-533526-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.428 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 2.535 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.16.2.el6.x86_64
Operating System: <unknown>
CPUs: 2
Total Memory: 3.732 GiB
Name: localhost.localdomain
ID: WMVL:G4KJ:XOQ4:IZ5R:EUJK:6YDI:TN3S:V3XN:OLE6:XDQK:WSCI:D7SL
Debug mode (server): false
Debug mode (client): true
Fds: 54
Goroutines: 46
EventsListeners: 0
Init SHA1: bd0359e86e0e97527aa6298afba8df863db179c8
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker

uname -a
Linux localhost.localdomain 2.6.32-504.16.2.el6.x86_64 #1 SMP Wed Apr 22 06:48:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details
Host Centos 6.5 minimal

Container environment:
Ubuntu 14.04 with GTK, Oracle JDK 7 update 80, Tomcat 6.43, xvfb, supervisor

Steps to reproduce:
Its bit tricky process so attaching the dockerfile and its supports. run the docker setup.
1) after install run the container daemon
2) connect to container and get its ip. and run the command
tail -f /var/lib/apache-tomcat-6.0.43/logs/catalina.out
3) from host call the url like "curl http://ipofcontainer:8080/Docker/SpeedTest"

Actual Results: no output

Expected Results:
After a 1-2 minutes you should something like below in tomcat log which tailed above
Xlib:  extension "RANDR" missing on display ":1".
download speed : 14.84
upload speed : 11.36
ping : 53
jitter : 4561
download speed : 14.84
upload speed : 11.36
ping : 53
jitter : 4561

Complete source code and docker setup file are available at
https://drive.google.com/folderview?id=0B5FsTXLdHXZRfjZGWHV2cDJSUDlrcVhwNDByaGlZUGZERFBvMlA3b0NqSi0zN0lwVG92Tkk&usp=sharing

**Comment by thaJeztah** [comment] 2015-05-31 21:11
No real idea here, some thoughts that may help

Have you checked `docker logs -f <your container>` to check if the containers logs contain anything useful?

Not sure, but this looked a bit odd;
```ini
[supervisord]
nodaemon=true

[program:xvfb]
command=service xvfb start

[program:tomcat]
command=service tomcat start
```

Not really sure, but am I right that you're using supervisor (a process manage), to start services (handled by another process manager)?

**Comment by sridharratna** [comment] 2015-06-01 06:13
I am using the supervisor two start tomcat and xvfb as startup process. Is there any other way to autorun multiple processes?.

I see the container log as below
[root@localhost ~]# docker logs -f f4f355720339
/usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2015-05-29 09:23:51,047 CRIT Supervisor running as root (no user in config file)
2015-05-29 09:23:51,048 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2015-05-29 09:23:51,084 INFO RPC interface 'supervisor' initialized
2015-05-29 09:23:51,085 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-05-29 09:23:51,085 INFO supervisord started with pid 1
2015-05-29 09:23:52,088 INFO spawned: 'xvfb' with pid 8
2015-05-29 09:23:52,090 INFO spawned: 'tomcat' with pid 9
2015-05-29 09:23:52,101 INFO exited: xvfb (exit status 0; not expected)
2015-05-29 09:23:52,101 CRIT reaped unknown pid 16)
2015-05-29 09:23:52,108 INFO exited: tomcat (exit status 0; not expected)
2015-05-29 09:23:53,110 INFO spawned: 'xvfb' with pid 41
2015-05-29 09:23:53,113 INFO spawned: 'tomcat' with pid 42
2015-05-29 09:23:53,141 INFO exited: xvfb (exit status 0; not expected)
2015-05-29 09:23:53,212 INFO exited: tomcat (exit status 0; not expected)
2015-05-29 09:23:55,216 INFO spawned: 'xvfb' with pid 63
2015-05-29 09:23:55,219 INFO spawned: 'tomcat' with pid 64
2015-05-29 09:23:55,227 INFO exited: xvfb (exit status 0; not expected)
2015-05-29 09:23:55,233 INFO exited: tomcat (exit status 0; not expected)
2015-05-29 09:23:58,239 INFO spawned: 'xvfb' with pid 78
2015-05-29 09:23:58,241 INFO spawned: 'tomcat' with pid 79
2015-05-29 09:23:58,250 INFO exited: xvfb (exit status 0; not expected)
2015-05-29 09:23:58,253 INFO gave up: xvfb entered FATAL state, too many start retries too quickly
2015-05-29 09:23:58,256 INFO exited: tomcat (exit status 0; not expected)
2015-05-29 09:23:59,257 INFO gave up: tomcat entered FATAL state, too many start retries too quickly
2015-06-01 06:00:47,206 CRIT reaped unknown pid 23)
2015-06-01 06:01:01,731 CRIT reaped unknown pid 18)
2015-06-01 06:01:21,999 CRIT reaped unknown pid 314)

**Comment by thaJeztah** [comment] 2015-06-01 06:56
> I am using the supervisor two start tomcat and xvfb as startup process. Is there any other way to autorun multiple processes?

Using supervisor is fairly standard for those cases, but I noticed you used it to run **service** xvfb start, which to me sounds your trying to control another process manager, which on its turn starts xvfb.

However, I've got absolutely *no* experience with Tomcat, so cannot help you further on *that* matter.

> I see the container log as below

Looking at those;

```
2015-05-29 09:23:53,110 INFO spawned: 'xvfb' with pid 41
2015-05-29 09:23:53,113 INFO spawned: 'tomcat' with pid 42
2015-05-29 09:23:53,141 INFO exited: xvfb (exit status 0; not expected)
2015-05-29 09:23:53,212 INFO exited: tomcat (exit status 0; not expected)
```

Supervisord (?) sees those processes exiting immediately. Given that they exit with a status 0, that could be caused by my earlier comment (another process manager being called); that process completes/exits as soon as xvfb/tomcat is started, causing supervisor to think it needs to be restarted.


Reading the above, this doesn't like like a bug in Docker, but in the way you're trying to run the processes. For that reason, I'm going to close this issue for now.

I suggest to;

- Look into the way you're starting the processes/services in your container
- Check if your services are actually running correctly in the container
- Look for examples (how do other users run Tomcat in Docker)
- There's also an official Tomcat image on Docker Hub; https://registry.hub.docker.com/u/library/tomcat/. You may find some examples there (or in the Dockerfiles for those images, for example, for the [Tomcat:6.0.44-jre7 image](https://github.com/docker-library/tomcat/blob/3b05667011a600a2f46422dd533467eff8e7fecf/6-jre7/Dockerfile)
- Ask your question in the #docker IRC channel on freenode, or the [docker-user](https://groups.google.com/forum/#!forum/docker-user) group.

Feel free to comment here after I closed this issue and ping me if you think I closed this by mistake.

**Closed by thaJeztah** 2015-06-01 06:56 UTC

**Comment by sridharratna** [comment] 2015-06-01 06:59
But when I see the process with ps -ax I see that the processes are running....

**Comment by thaJeztah** [comment] 2015-06-01 08:09
At this moment I'm not 100% sure what the cause of the problem is, but these

```
2015-05-29 09:23:58,250 INFO exited: xvfb (exit status 0; not expected)
2015-05-29 09:23:58,253 INFO gave up: xvfb entered FATAL state, too many start retries too quickly
2015-05-29 09:23:58,256 INFO exited: tomcat (exit status 0; not expected)
2015-05-29 09:23:59,257 INFO gave up: tomcat entered FATAL state, too many start retries too quickly
```

definitely don't look right. Apart from that, there are quite some moving parts in your repro case, that may be related or not. I'd like to be sure first that your *application* is running correctly and set-up correctly, before researching further if there's a bug in Docker / networking.

**Comment by sridharratna** [comment] 2015-06-01 09:57
I have tested the application and all modules are working fine except this particular piece of thing.
Even after removing the supervisor still I am having the same issue.
