### ISSUE TITLE
linux spec user: Unable to find user xxx

### ISSUE THREAD

**Issue by edannenberg** [docker/docker#22323] opened 2016-04-26 01:19 UTC
Since upgrading to Docker 1.11.0 the following won't work anymore:

    $ docker run -it --rm --user $(whoami) -v /etc/passwd:/etc/passwd:ro busybox
    docker: Error response from daemon: linux spec user: Unable to find user xxx

You also get some funny behavior when using a non root user that exists in the image's `/etc/passwd`:

    $ docker run -it --rm --user operator -v /etc/passwd:/etc/passwd:ro busybox whoami
    whoami: unknown uid 37

Depending on your system the above might actually work fine or output some other random user name, on my host `/etc/passwd` has no entry for uid 37.

Apparently `--user` is now set before the `/etc/passwd` file of the host is mounted in the container. Can this functionality be restored in a future release? If not, mounting the host's `/etc/passwd` should not be allowed as it will just lead to problems down the road.

The use case for this is mainly for local development, where, for example, you would like to run a css preprocesser watching your source files and want to avoid any file permission head aches.

**Comment by aaronlevin** [comment] 2016-04-26 10:39
I am also experiencing this:

```
$ docker run -it --rm --user $(whoami) -v /etc/passwd:/etc/passwd:ro busybox
docker: Error response from daemon: linux spec user: Unable to find user aaronlevin.
```

My system:

```
$ uname -a
Linux aaron-sc 4.2.0-35-generic #40~14.04.1-Ubuntu SMP Fri Mar 18 16:37:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pgracio** [comment] 2016-04-26 12:24
+1

**Comment by thaJeztah** [comment] 2016-04-26 12:44
Why not use the numeric ID of the user, instead of a user-name; doing so, you don't have to bind-mount `/etc/passwd`, because that file is only needed to convert the username to its uid/gid inside the container.

```bash
docker run -it --rm --user $(id -u) busybox
```

the only thing you'll miss is having a "nice" name visible inside the container, but I suspect the reason you're doing this is for setting the right permissions, and not to show a user's name.

**Comment by edannenberg** [comment] 2016-04-26 15:03
Interesting, I actually tried that, but with docker-compose only, which complained with a schema validation error as it expects `user:` to be a string. So I assumed it actually had to be a user name. Turns out putting the uid into quotes will do the trick.

@thaJeztah can we a expect a fix for this? I certainly can live without one for now but still it's somewhat ugly and might lead to unexpected behavior with some applications.

**Comment by thaJeztah** [comment] 2016-04-26 15:43
@edannenberg it would be good to know the reason this changed, it's possible this change is actually related to creating volumes with the right permissions (i.e., if I start a container as user 123, and create a volume, then the volume should be owned by 123). If that is the reason, then I'm not sure we'd be able to revert to the old behavior

**Comment by HackToday** [comment] 2016-04-27 02:53
It seems `docker master` not have such issue,
also  `1.11.1` not include such change in `oci` https://github.com/opencontainers/runc/commit/3cfff676b10eb618cca873159b7c277e89b3e593

**Comment by HackToday** [comment] 2016-04-27 02:53
```
root@5b451cfb7082:/go/src/github.com/docker/docker# docker run -it --rm --user daemon -v /etc/passwd:/etc/passwd:ro busybox
/ $ whoami
daemon
/ $ exit
root@5b451cfb7082:/go/src/github.com/docker/docker# docker run -it --rm --user daemondd  -v /etc/passwd:/etc/passwd:ro busybox
docker: Error response from daemon: linux spec user: unable to find user daemondd: no matching entries in passwd file.
```

**Comment by thaJeztah** [comment] 2016-04-27 15:10
@HackToday yeah, `daemon` is present by default in busybox, so in that case, it's using `/etc/passwd` from the busybox image, not the bind-mounted `/etc/passwd` file

**Comment by justincormack** [comment] 2016-04-28 14:46
The opencontainers specification requires that the user id passed to runc in Linux is a number, and resolving user names is left to the layers above, see https://github.com/opencontainers/runtime-spec/blob/master/config.md#linux-user

Therefore since we use `runc` the name has to be derived before the mounts take place, so bind mounting `/etc/passwd` will be too late. Although this used to work, I think that it was just because the ordering happened to be like that, and I don't think it can really be seen as a regression, and I don't think it is sensible to fix it, as numeric ids are what the kernel really uses.

**Comment by thaJeztah** [comment] 2016-04-28 14:55
Thanks for looking into that @justincormack. Given that information, this is not an easy fix, and not something worth changing. I'll close this.

**Closed by thaJeztah** 2016-04-28 14:55 UTC
Labels: area/runtime

**Comment by frncmx** [comment] 2016-05-06 18:01
@thaJeztah the `docker run -it --rm --user $(id -u) busybox` solution works. However, there is still 1 use case for `/etc/passwd`, if you don't mind I describe it below.

If you need to use SSH protocol inside a container (e.g., git clone), you will need the password file.

So, I've modified our build environment to something like:
`docker run --rm -it -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent -u $(id -u) -v /etc/passwd:/etc/passwd:ro <builder-image>`

That way I've my ssh-agent inside the container and my user is known by the contianer, which is a must for SSH.

**Comment by varunagrawal** [comment] 2018-02-02 22:09
The docs over at https://docs.docker.com/engine/reference/run/#user should be updated to reflect that only UIDs work and usernames don't.

**Comment by yuchengwu** [comment] 2019-05-22 04:18
When docker run with uid, it throws 

```
standard_init_linux.go:190: exec user process caused "exec format error"   
```

any thoughts? more detailed info: https://github.com/moby/moby/issues/39247

**Comment by RamBoddapati** [comment] 2019-05-26 11:52
> @edannenberg it would be good to know the reason this changed, it's possible this change is actually related to creating volumes with the right permissions (i.e., if I start a container as user 123, and create a volume, then the volume should be owned by 123). If that is the reason, then I'm not sure we'd be able to revert to the old behavior

@thaJeztah  Very thanskfull to you. when i used to create user with numeric values(UID), it worked well. But how to create user with alphabets by omitting error "linux spec user: Unable to find user xxx"? Please help  me.

**Comment by kingdonb** [comment] 2019-05-26 15:33
I think based on my understanding of this issue @RamBoddapati, that a `USER [username]` directive is simply not a supported mode of configuration to place in your Dockerfile, in Linux docker at least.  If it works sometimes for you on certain particular version, that's a happy accident and not a documented feature.  `USER [uid]` is the safe way to call this directive, with a numeric uid value.

This could be clearer in: https://docs.docker.com/engine/reference/builder/#user, but seems clearer in https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user where I find:

```
Consider an explicit UID/GID

Users and groups in an image are assigned a non-deterministic UID/GID in that the “next” UID/GID is assigned regardless of image rebuilds. So, if it’s critical, you should assign an explicit UID/GID.
```

This may also have changed since 2016, it may be safer to use a string username than it once was before, and the documentation could be clearer about it IMHO but it was made pretty clear on some forum threads I think that this would never be totally fixed.  If you switched from using numeric UID, to using a string-based username in your Dockerfiles, then you are going in the wrong direction.

I am not a maintainer here so happy to be corrected if anyone knows better. Thanks

**Comment by RamBoddapati** [comment] 2019-05-27 04:08
@kingdonb , thanks for providing such  references. This served my purpose.
