### ISSUE TITLE
Unable to find images in remote docker registry

### ISSUE THREAD

**Issue by annegi** [docker/docker#28379] opened 2016-11-14 07:21 UTC
I was able to configure docker registry successfully.I am able to push and pull a particular repository from remote docker registry but when I run docker search <remote registry>:5000, I am not able to see anything. Anyone facing the same issue?

docker push 10.2.0.10:5000/docker.io/mysql
The push refers to a repository [10.2.0.10:5000/docker.io/mysql]
dda5a64c9b27: Image successfully pushed
53ed9837cdc5: Image successfully pushed
b26238180bc8: Image successfully pushed
01e91410235e: Image successfully pushed
b610b16e919f: Image successfully pushed
1574ff8789b1: Image successfully pushed
e7048a1643a4: Image successfully pushed
1bc74a039df4: Image successfully pushed
6ebad06b3e49: Image successfully pushed
f1621398948b: Image successfully pushed
fe4c16cbf7a4: Image successfully pushed
Pushing tag for rev [cd88b71c6c8c] on {http://10.2.0.10:5000/v1/repositories/docker.io/mysql/tags/latest}

docker pull 10.2.0.10:5000/docker.io/mysql
Using default tag: latest
Trying to pull repository 10.2.0.10:5000/docker.io/mysql ...
Pulling repository 10.2.0.10:5000/docker.io/mysql
cd88b71c6c8c: Already exists
fe4c16cbf7a4: Already exists
e6261350fc40: Already exists
d3639d3b76cc: Already exists
af37e9492c41: Already exists
e91a78270995: Already exists
b44b8bdb0b85: Already exists
7ddf3d4ce9c7: Already exists
1c83626f4ec2: Already exists
a1125db48858: Already exists
21dbefa406d6: Already exists
Status: Image is up to date for 10.2.0.10:5000/docker.io/mysql:latest
10.2.0.10:5000/docker.io/mysql: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.

docker search 10.2.0.10:5000
INDEX     NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED

**Comment by thaJeztah** [comment] 2016-11-14 10:25
The current version of the open source registry (https://github.com/docker/distribution) does not have indexing / search built-in. Indexing/searching is separate from the actual registry.

The "legacy" registry (v1) https://github.com/docker/docker-registry did have search built-in, but is deprecated and no longer maintained.

Please keep in mind that the GitHub issue tracker is not a general discussion/support forum, but for reporting bugs and feature requests. For other topics, use https://forums.docker.com

Since this is not a bug, I'll close this issue, but feel free to comment after I closed

**Closed by thaJeztah** 2016-11-14 10:25 UTC
Labels: area/distribution
