### ISSUE TITLE
Feature request: Ability to ADD file temporarily without increasing image size

### ISSUE THREAD

**Issue by perwah** [docker/docker#5299] opened 2014-04-18 10:19 UTC
In a Dockerfile, I would like to be able to ADD a temporary file, say a .deb package, to install and then delete, so that the file itself does not increase the "virtual size" of my final image:
```
ADD very-large-file.deb /very-large-file.deb
RUN dpkg --install /very-large-file.deb && rm /very-large-file.deb
```
As it is now, the very-large-file.deb is still included in a AUFS layer, and making my final image unnecessarily large.

# docker version
Client version: 0.10.0
Client API version: 1.10
Go version (client): go1.2.1
Git commit (client): dc9c28f
Server version: 0.10.0
Server API version: 1.10
Git commit (server): dc9c28f
Go version (server): go1.2.1
Last stable version: 0.10.0

**Comment by thaJeztah** [comment] 2015-05-04 03:21
I'm going to close this issue, because I think this is a duplicate of https://github.com/docker/docker/issues/332.

If you think I incorrectly marked this as a duplicate, please leave a comment

**Closed by thaJeztah** 2015-05-04 03:21 UTC
Labels: Distribution, kind/feature

**Comment by swarren** [comment] 2024-07-22 17:03
A bit late to the game, but since this issue is returned by Google searches, here's a workaround at least for modern Docker:

```
FROM scratch as docker-context
COPY / /docker-context

FROM whatever as final
RUN \
    --mount=type=bind,from=docker-context,source=/docker-context,target=/docker-context \
    dpkg -i /docker-context/xxx.deb
```

It'd be really nice if the context were just directly available as some kind of bind mount automatically, but the WAR above isn't too much.
