### ISSUE TITLE
docker engine crashes with fluentd plugin when gelf endpoint is down 

### ISSUE THREAD

**Issue by wjimenez5271** [docker/docker#23826] opened 2016-06-21 19:52 UTC
We're using the fluentd plugin to ship to a Graylog (gelf) endpoint. Graylog crashed and subsequently several of the docker engines with those fluentd plugins crashed:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x74155c]

goroutine 1667535 [running]:
net.(*TCPConn).Write(0x0, 0xc822a3c000, 0x704, 0x50000, 0x0, 0x0, 0x0)
	<autogenerated>:75 +0x2c
github.com/fluent/fluent-logger-golang/fluent.(*Fluent).send(0xc821302420, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.11.1/vendor/src/github.com/fluent/fluent-logger-golang/fluent/fluent.go:265 +0x1ec
github.com/fluent/fluent-logger-golang/fluent.(*Fluent).PostRawData(0xc821302420, 0xc821a80000, 0x1fd, 0x229)
	/builddir/build/BUILD/docker-1.11.1/vendor/src/github.com/fluent/fluent-logger-golang/fluent/fluent.go:170 +0x189
github.com/fluent/fluent-logger-golang/fluent.(*Fluent).EncodeAndPostData(0xc821302420, 0xc820fcdec0, 0x13, 0xecefaa53d, 0xc801fe8cd2, 0x215bee0, 0x11fc7e0, 0xc821e9d2c0, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.11.1/vendor/src/github.com/fluent/fluent-logger-golang/fluent/fluent.go:161 +0x257
github.com/fluent/fluent-logger-golang/fluent.(*Fluent).PostWithTime(0xc821302420, 0xc820fcdec0, 0x13, 0xecefaa53d, 0x1fe8cd2, 0x215bee0, 0x11fcee0, 0xc821e9d290, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.11.1/vendor/src/github.com/fluent/fluent-logger-golang/fluent/fluent.go:153 +0x996
github.com/docker/docker/daemon/logger/fluentd.(*fluentd).Log(0xc82224d3c0, 0xc820ff3590, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.11.1/_build/src/github.com/docker/docker/daemon/logger/fluentd/fluentd.go:146 +0x414
github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc82224d640, 0x1706320, 0x6, 0x7fed331945d0, 0xc8212e23c0)
	/builddir/build/BUILD/docker-1.11.1/_build/src/github.com/docker/docker/daemon/logger/copier.go:59 +0x4f8
created by github.com/docker/docker/daemon/logger.(*Copier).Run
	/builddir/build/BUILD/docker-1.11.1/_build/src/github.com/docker/docker/daemon/logger/copier.go:40 +0x127
```

**Comment by mlaventure** [comment] 2016-06-22 15:17
Could you provide the docker version being used?

**Comment by wjimenez5271** [comment] 2016-06-22 15:23
Sorry, v1.11

**Comment by mlaventure** [comment] 2016-06-22 15:25
The bug is from the https://github.com/fluent/fluent-logger-golang repository

Someone already opened an issue over there to have it fixed https://github.com/fluent/fluent-logger-golang/issues/29

Once it is fixed, we will vendor in the new version of `fluent-logger-golang`

**Comment by thaJeztah** [comment] 2016-07-17 01:03
ping @tagomoris

**Comment by tagomoris** [comment] 2016-07-17 02:00
No progress - no one can provide how to reproduce it.

**Comment by cpuguy83** [comment] 2016-07-17 17:21
@tagomoris This looks like it could be a race condition in the vendored code's `send()` call:

```go
func (f *Fluent) send() (err error) {
	if f.conn == nil {
		if f.reconnecting == false {
			f.mu.Lock()
			f.reconnecting = true
			f.mu.Unlock()
			f.reconnect()
		}
		err = errors.New("fluent#send: can't send logs, client is reconnecting")
	} else {
                // f.conn made nil here, by call to close()
		f.mu.Lock()
		_, err = f.conn.Write(f.pending)
		f.mu.Unlock()
	}
	return
}
```

**Comment by EricFortin** [comment] 2016-09-20 12:00
I think #26740 will fix this issue.

**Comment by tagomoris** [comment] 2016-09-20 15:13
#26740 was merged.

**Comment by mlaventure** [comment] 2016-09-20 15:28
It was indeed, thanks for the ping @tagomoris !

**Closed by mlaventure** 2016-09-20 15:28 UTC
Labels: area/logging, kind/bug
