### ISSUE TITLE
[1.12.0-rc4] Unable to connect remotely to a swarm node with tls : malformed HTTP response

### ISSUE THREAD

**Issue by jggc** [docker/docker#24860] opened 2016-07-20 19:57 UTC
**Output of `docker version`:**

```
1.12.0-rc4
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc4
Storage Driver: devicemapper
 Pool Name: docker-253:1-198482-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 412.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 19.08 GB
 Metadata Space Used: 1.118 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: active
 NodeID: 5jafarjvvc41let676sctn8bz
 IsManager: Yes
 Managers: 2
 Nodes: 7
 CACertHash: sha256:25cba5e40efa22b215482ce72a52c0e29a7c39931438cbbac58c76f660f6ce71
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797 GiB
Name: swarm1.novalocal
ID: GREH:3Q4V:7O3D:CJWD:BM7Z:XTRQ:AVRY:7W5S:J6RT:K6M2:JRZ4:ZLO6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

3 similar fresh CentOS 7 vms on an OpenStack

**Steps to reproduce the issue:**
1. host1 $ docker swarm init
2. host2 $ docker swarm join --secret <secret> --ca-hash <sha256> <manager_ip>:2377
3. Add a dns entry (in /etc/host in my case) for `<manager_ip> swarm_manager`
4. Copy the ca cert from the swarm manager (/var/lib/docker/swarm/certificates/swarm-root-ca.crt) into ~/.docker/ca.pem
5. Execute any docker command on the swarm manager with --tlsverify
    Example : `docker --tlsverify -H swarm-manager:2377 images`

**Describe the results you received:**

An error occurred trying to connect: Get https://swarm-manager:2377/v1.23/images/json: malformed HTTP response "\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x04\b\x00\x00\x00\x00\x00\x00\x0e\xff\xf1"

**Describe the results you expected:**

I expected a docker images output

**Additional information you deem important (e.g. issue happens only occasionally):**

I checked the certificate sha256 sum agains the sha256 sum I get with `docker swarm inspect` and it matches, when I query with another name than swarm-manager it tells me that the certificate is not valid so I'm positive that I grabbed the right certificate.

I made a hex dump of what I get from `curl -v -k https://swarm-manager:2377/v1.23/images/json` here it is

```
00000000: 0000 0004 0000 0000 0000 0004 0800 0000
00000010: 0000 000e fff1
```

I get the exact same output no matter what command I try to run. I tried `ps` `images` `run -d -p 8080:8080 mongo` and I get the exact same hex output. I tried from a docker 1.12.0-rc4 client and also from a 1.11.2 client and got the exact same result.

Here is the full output of my curl command :

```
curl -v -k https://swarm-manager:2377/v1.23/images/json > /dev/null 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.20.11...
* Connected to swarm-manager (192.168.20.11) port 2377 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [49 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1046 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [147 bytes data]
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
{ [46 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
} [7 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=eg5zv0aoechvttu5bwml1w9bm; OU=swarm-manager; CN=5jafarjvvc41let676sctn8bz
*  start date: Jul 20 13:49:00 2016 GMT
*  expire date: Oct 18 13:49:00 2016 GMT
*  issuer: CN=swarm-ca
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
} [5 bytes data]
> GET /v1.23/images/json HTTP/1.1
> Host: swarm-manager:2377
> User-Agent: curl/7.49.1
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.2 (IN), TLS alert, Client hello (1):
{ [2 bytes data]
100    31    0    31    0     0    276      0 --:--:-- --:--:-- --:--:--   276
* Connection #0 to host swarm-manager left intact
```

**Comment by cpuguy83** [comment] 2016-07-20 20:17
The swarm port is not for client communications, only daemon<->daemon

Closing as this is as intended.

**Closed by cpuguy83** 2016-07-20 20:17 UTC
