### ISSUE TITLE
file system corruption with devicemapper/aufs

### ISSUE THREAD

**Issue by stevenschlansker** [docker/docker#7229] opened 2014-07-25 00:02 UTC
I am filing this issue to try to get a single place to document what I see as an extremely severe issue:  when using Docker, sometimes your container filesystems and/or files become seriously corrupted.

There are at least two mailing list threads pointing to the problem:
https://groups.google.com/forum/#!topic/docker-dev/Xzwm5GRYCLo
https://groups.google.com/forum/#!topic/docker-user/35Z0-g8sObY

And one previously filed issue (now closed) #6368 

The problem manifests itself in a few different ways.  It is unclear to me if these are all related.

Known symptoms:

* Corrupt files (`docker run myimage md5sum /some/file` returns different results on different hosts)
* Corrupt filesystems, example messages:
  * `EXT4-fs error (device dm-2): ext4_lookup:1437: inode #132310: comm docker: deleted inode referenced: 134547`
  * `[271394.160211] EXT4-fs warning (device dm-10): ext4_end_bio:317: I/O error writing to inode 402137 (offset 0 size 0 starting block 169271)
[271394.160214] Buffer I/O error on device dm-10, logical block 169271`
  * `htree_dirblock_to_tree: bad entry in directory #2: rec_len is smaller than minimal - offset=0, inode=0, rec_len=0, name_len=0`

So far this has only been reported against the devicemapper and aufs backends, not btrfs.
It is possible that this is a kernel bug but since it is so disastrous to Docker workloads I believe it deserves a bug here regardless of the root cause.

I have verified that this happens against Ubuntu 14.04 `3.13.0-24-generic` with Docker 1.0.0.

**Comment by unclejack** [comment] 2015-01-07 17:17
*devicemapper issues review session with @vbatts*

This issue was caused by a kernel bug which is now fixed. Currently supported kernels on CentOS, Debian, RHEL and Ubuntu shouldn't exhibit this problem any more.

We'll make sure include a note about this particular commit in the documentation around kernel requirements so that everyone is aware of this particular problem.

I'll close this now. Please feel free to comment if you run into something similar and you can already confirm that the fix is included in the kernel you're running.

**Closed by unclejack** 2015-01-07 17:17 UTC
Labels: /system/aufs, /system/devicemapper

**Comment by aurorafox1** [comment] 2015-06-15 11:26
我也出现类似的问题，日志报类似错误，然后发现是可用空间没有了
Data Space Used: 100.52 GB
Data Space Total: 100.52 GB
Data Space Available: 0 M

下面这个是我的解决方法，希望能帮助到你:
1. 备份docker运行目录.
2. 在/etc/sysconfig/docker配置文的OPTIONS参数中添加下面这一个选项:--storage-opt=dm.loopdatasize=500G(根据实际磁盘大小来分配)

**Comment by serussell** [comment] 2015-07-02 12:22
@unclejack, do you know in which version of the kernel this was fixed?

```
root@daztladm01:~# uname -a | awk '!($2="")'
Linux  3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
root@daztladm01:~# cat /etc/lsb-release | grep DESC
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"
```
