### ISSUE TITLE
How to run docker container on high available storage like NFS,EBS,flock etc

### ISSUE THREAD

**Issue by GuyCheung** [docker/docker#17201] opened 2015-10-20 03:24 UTC
I'm trying to do this like EC2, which run its root directory `/` on EBS. I want to run my docker container on high available storage driver.

At first, I tried use the docker volume to mount NFS mountpoint to container `/`, failed beacuse of mount to `/` will overwrite the entire container filesystem, mentioned in [How to mount the root directory of docker container as a NFS mount point](http://stackoverflow.com/questions/33164163/how-to-mount-the-root-directory-of-docker-container-as-a-nfs-mount-point/33173694)

I want to trying don't verify docker volume container path by update source, and I'll put docker image to local fs mounted with NFS or others via `docker save` at first time.

How about to do this? Or is there any other methods for the purpose?

**Comment by thaJeztah** [comment] 2015-10-20 03:43
Hi @GuyCheung, the GitHub issue tracker is not a general support forum, but meant for tracking bugs and feature requests for docker.

Could you ask this question on one of these channels instead?:

- in the #docker IRC channel on Freenode.
- the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
- on https://forums.docker.com/
- on StackOverflow http://stackoverflow.com/questions/tagged/docker

I'm going to close this issue because this is not a bug or a feature request, but feel free to comment here after I've closed

**Closed by thaJeztah** 2015-10-20 03:43 UTC

**Comment by GuyCheung** [comment] 2015-10-20 04:10
sorry for this, I'm new to docker and don't know where to ask the question~

**Comment by thaJeztah** [comment] 2015-10-20 04:38
@GuyCheung no problem!
