### ISSUE TITLE
Feature request: Configurable source for volume

### ISSUE THREAD

**Issue by yashgt** [docker/docker#29023] opened 2016-12-01 10:01 UTC
When I inspect a container, the named volumes appear to mount a location on the host to a location on the container:
"Mounts": [
            {
                "Type": "volume",
                "Name": "e1_serverlog",
                "Source": "/mnt/sda1/var/lib/docker/volumes/e1_serverlog/_data",
                "Destination": "/log",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
We need a way by which, docker can be told to use a custom directory from the host such as /usr/data/myvolumes as the Source for the named volumes.

**Comment by cpuguy83** [comment] 2016-12-02 14:13
Use a bind-mount?

**Comment by thaJeztah** [comment] 2016-12-02 14:34
This is a duplicate of https://github.com/docker/docker/issues/19990, and after that discussion, the author of that issue created a volume plugin that implements this; https://github.com/CWSpear/local-persist

I'll close this issue, because it's a duplicate, but feel free to comment after

**Closed by thaJeztah** 2016-12-02 14:34 UTC
