### ISSUE TITLE
docker-proxy high cpu load

### ISSUE THREAD

**Issue by hwongcom** [docker/docker#9814] opened 2014-12-26 01:57 UTC
Can you minimize it to... 20%? optimize this docker-proxy. high cpu is detected when doing ab test.

**Comment by jfrazelle** [comment] 2015-02-26 23:09
duplicate of https://github.com/docker/docker/issues/7857 https://github.com/docker/docker/issues/8356

**Closed by jfrazelle** 2015-02-26 23:09 UTC
