### ISSUE TITLE
why etcd or zk different from consul？

### ISSUE THREAD

**Issue by bobo200128docker** [docker/docker#29316] opened 2016-12-12 07:16 UTC
https://docs.docker.com/swarm/discovery/

Start the Swarm manager on any machine or your laptop.
Etcd:
 swarm manage -H tcp://<swarm_ip:swarm_port> etcd://<etcd_addr1>,<etcd_addr2>/<optional path prefix>
Consul:
 swarm manage -H tcp://<swarm_ip:swarm_port> consul://<consul_addr>/<optional path prefix>
ZooKeeper:
 swarm manage -H tcp://<swarm_ip:swarm_port> zk://<zookeeper_addr1>,<zookeeper_addr2>/<optional path prefix>

as the above, etcd have addr1 and addr2,zk also have addr1 and addr2. consul have only addr.
If the only one consul_addr failed, how to implement the HA of swarm manage.

Can consul have several addrs？

**Comment by thaJeztah** [comment] 2016-12-12 09:51
The consul client only allows for a single IP-address, see https://github.com/docker/swarm/pull/583 and https://github.com/hashicorp/consul/issues/849

I'll close this issue because this is not a bug report; please keep in mind that the GitHub issue tracker is for reporting bugs and feature requests, and not a general support forum. For other questions, use

- https://forums.docker.com
- the docker community slack channel https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/

Feel free to comment though, after I closed this issue

**Closed by thaJeztah** 2016-12-12 09:51 UTC

**Comment by thaJeztah** [comment] 2016-12-12 09:53
Also; the external key/value stores are only needed for "classic" Swarm (https://github.com/docker/swarm). The services feature ("swarm mode") introduced in docker 1.12 no longer needs an external key/value store, so may be of interest to you; https://docs.docker.com/engine/swarm/
