### ISSUE TITLE
Cannot start docker

### ISSUE THREAD

**Issue by qwerty2000** [docker/docker#32032] opened 2017-03-23 00:02 UTC
Hi

I'm a newbie to linux and docker, but I'm learning.

I installed docker on centos 7 according to the install instructions of the docker website. However, I cannot start docker. I receive the following message:

Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
Drop-In: /etc/systemd/system/docker.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Thu 2017-03-23 00:50:23 CET; 1min 44s ago
     Docs: https://docs.docker.com
  Process: 11222 ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 11222 (code=exited, status=1/FAILURE)

Mar 23 00:50:22 vps........................................nl docker[11222]: Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
Mar 23 00:50:23 vps.......................................nl docker[11222]: no sockets found via socket activation: make sure the service was started by systemd

Some more info:

Linux vps.................................nl 3.10.0-042stab117.16 #1 SMP Fri Sep 9 21:57:19 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

Anyone suggestions how to fix this problem?

Thx in advance!

**Comment by thaJeztah** [comment] 2017-03-23 00:33
It looks like you use using an override file to modify the default systemd unit file. The error is;

    Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run dockerd directly.

Change the ExecStart line in your unit file to;

     ExecStart=/usr/bin/dockerd --storage-driver=overlay -H fd://

Then reload systemd config (`systemctl daemon-reload`), and restart the docker service

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-23 00:33 UTC
