### ISSUE TITLE
my app's go process could'nt attach correctly to 127.0.0.1:port  

### ISSUE THREAD

**Issue by rahal** [docker/docker#27315] opened 2016-10-12 09:38 UTC
**Description**

I'm trying to publish my go app as a docker image, my app is using  : http.ListenAndServe("127.0.0.1:"+port, nil)  to start the server.
The application was running corretly in my environnement but not as a docker container.

**Steps to reproduce the issue:**
1. Build a simple go application that start a server on 127.0.0.1:port
2. Dockerise it
3. Start the container

**Describe the results you received:**
The container seems working but is not receiving any request

**Describe the results you expected:**
The container ( application ) should be working

**Additional information you deem important (e.g. issue happens only occasionally):**
I found a fix, I just started the server without specifying IP address like this : http.ListenAndServe(":"+port ) instead of http.ListenAndServe("127.0.0.1:"+port ) 
I just lost some good amount of time trying to undestand what was happening.
Hope this can help.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 68
 Running: 10
 Paused: 0
 Stopped: 58
Images: 2786
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2047
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: TS6H:7PR5:UDGI:ZYRD:BB7A:X3AP:XZZ3:YUPV:JNIK:PBHI:JYZX:TLGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 59
 Goroutines: 97
 System Time: 2016-10-12T09:41:40.660462571Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using docker for mac

**Comment by justincormack** [comment] 2016-10-12 11:05
`127.0.0.1` in a container is a special local interface within that container, that you can only reach from another process within the container.

For most use cases you want to listen on `0.0.0.0`.

**Comment by rahal** [comment] 2016-10-12 11:11
Thank you Justin for your clarification.

**Comment by justincormack** [comment] 2016-10-12 11:39
I am going to close this issue, as it is not a bug, but feel free to continue asking questions.

**Closed by justincormack** 2016-10-12 11:39 UTC
Labels: version/1.12
