### ISSUE TITLE
exec does not set TERM env when -t passed

### ISSUE THREAD

**Issue by bluepeppers** [docker/docker#9299] opened 2014-11-23 18:55 UTC
Passing `-t` to `docker run` will set the `TERM` environment variable. Doing so to `docker exec` will not. This causes things like `htop` to not work.

    $ docker run -d --name foo debian bash -c "while true; sleep 1; done"
    2fc4a0d2fc6d
    $ docker exec -ti foo env
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    HOSTNAME=2fc4a0d2fc6d

Or a case that the end user is more likely to experience:

    $ docker run -d --name foo debian bash -c "while true; sleep 1; done"
    2fc4a0d2fc6d
    $ docker exec foo "apt-get update && apt-get install -y htop"
    ....
    $ docker exec -ti foo htop
    Error opening terminal: unknown.

Versions and stuff:

    $ docker version
    Client version: 1.3.1
    Client API version: 1.15
    Go version (client): go1.3.3
    Git commit (client): 4e9bbfa
    OS/Arch (client): linux/amd64
    Server version: 1.3.1
    Server API version: 1.15
    Go version (server): go1.3.3
    Git commit (server): 4e9bbfa
    $ uname -a 
    Linux hostname 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
    $ docker -D info
    Containers: 186
    Images: 2828
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Dirs: 3206
    Execution Driver: native-0.2
    Kernel Version: 3.13.0-35-generic
    Operating System: Ubuntu 14.04.1 LTS
    Debug mode (server): false
    Debug mode (client): true
    Fds: 135
    Goroutines: 224
    EventsListeners: 1
    Init Path: /usr/bin/docker
    WARNING: illegal base64 data at input byte 4
    WARNING: No swap limit support

Apologies if this has already been reported/fixed (I didn't test against master, even though I know I should!)

**Comment by jfrazelle** [comment] 2015-02-26 23:43
closing as dup of https://github.com/docker/docker/issues/8755

**Comment by dashohoxha** [comment] 2015-09-03 13:15
Workaround:
```
docker exec -it $container /bin/bash -c "export TERM=xterm; exec bash"
```
Works very well.

**Comment by kramarama** [comment] 2015-09-21 07:53
I find it easier to remember:
```
docker exec -ti test env TERM=xterm bash -l
```

**Comment by dashohoxha** [comment] 2015-09-21 10:08
:+1:

**Comment by cyril-bouthors** [comment] 2015-10-22 15:34
👍

**Comment by peerasan** [comment] 2015-10-28 08:44
kramarama is very to remember

**Comment by aidanhs** [comment] 2015-10-29 18:06
@jfrazelle this isn't a duplicate, can you reopen?

#8755 is about a nasty issue to do with invalid file descriptor symlinks and mounting devpts, more fully discussed at #11462.

This issue is about an environment variable (`TERM`) differing inside docker exec depending on whether you initially started the container with `-t` or not.

**Comment by bhdrk** [comment] 2016-01-07 20:50
@samshiles's answer is worked for me.

**Comment by hervenicol** [comment] 2016-02-23 16:43
Just encountered the same issue.
At least the doc could mention that "**-t**" has a slightly different effect with "**run**" and with "**exec**".

What is misleading is that:
- both options have the same name (**-t, --tty**)
- both options descriptions are the same (**Allocate a pseudo-TTY**)

**Comment by freman** [comment] 2016-05-17 22:03
It would be nice if we could pass multiple environment variables (ala -e)

**Comment by vipseixas** [comment] 2016-05-20 18:50
@freman The production environment is the last step of a container workflow. Before you have your perfect black production box there's a lot of work you have to do with exec.

**Comment by freman** [comment] 2016-05-20 22:11
@vipseixas we've been doing this for almost two years, it's literally "let the devs tinker with their php in production" type work (because face it, it's easier to syntax error 30 live instances of the site in docker than it is to work offline, test, etc), the rest of everything is stable. The problem is as the exec api stands it's not suitable for doing that at least not on a production machine. No tidy way to clean up after someone that just closes their terminal instead of exiting properly, no tidy way to pass env, probably more I'm forgetting after so little sleep. I have been trying to write a tool that lets us exec right into a shell the thing remotely (ala ssh but reverse proxied so there's no ports exposed, with full session recording, and easier to integrate auth) but these issues make it un-appealing

**Comment by typekpb** [comment] 2016-06-24 07:27
any chance to get this one fixed, to make using `docker exec` more comfortable?

**Comment by grosser** [comment] 2016-09-01 21:49
FYI terminal copy + cols/rows fix

`kubectl exec -it $1 -- /bin/bash -c "stty rows $(tput lines) cols $(tput cols) && export TERM=$TERM && exec bash"`

https://github.com/grosser/dotfiles/commit/eca07c9c69deccdc19a5bcaf7b46b72f14577711

**Closed** 2016-09-12 21:57 UTC
Labels: area/runtime, kind/enhancement

**Comment by thaJeztah** [comment] 2016-09-13 13:51
We just merged a pull-request that automatically sets `TERM` if `docker exec` is started with a tty (`-t`) https://github.com/docker/docker/pull/26461

This change will go into the next release (1.13)

**Comment by bocharsky-bw** [comment] 2016-12-06 10:35
@thaJeztah Thanks! What about `docker-compose exec`? I can't use `-t` option there...

**Comment by thaJeztah** [comment] 2016-12-06 10:43
@bocharsky-bw docker-compose should use the same API, but if it's not working with the 1.13 daemon, it's best to open an issue in the docker-compose issue tracker; https://github.com/docker/compose/issues

**Comment by itbj** [comment] 2017-04-06 18:20
我今天也遇到这个问题，估计是TERM的问题。谢谢。

**Comment by thaJeztah** [comment] 2017-04-06 19:35
Google translate;

> I have encountered this problem today, it is estimated that the problem of TERM. Thank you.

**Comment by dasgoll** [comment] 2018-03-20 11:52
Works like a charm
kubectl exec -it kafka-kafka-0 -- bash -c "export TERM=xterm; exec bash"
or
kubectl exec -it kafka-kafka-0 -- bash -c "export TERM=xterm; bash"
docker exec -it $container /bin/bash -c "export TERM=xterm; exec bash"
