### ISSUE TITLE
Won't start after upgrade but says it starts

### ISSUE THREAD

**Issue by erinmcgill** [docker/docker#18729] opened 2015-12-16 23:45 UTC
Hello! 
We found we had to update our docker client after our pull from Docker Hub failed.
I went through the steps and the steps stated that docker started but it hadn't, no error message.

```
Setting up docker-engine (1.9.1-0~trusty) ...
Installing new version of config file /etc/init/docker.conf ...
Installing new version of config file /etc/init.d/docker ...
docker start/running, process 11444
Processing triggers for ureadahead (0.100.0-16) ...
$ ps -ef | grep docker
ubuntu   12604  1760  0 22:52 pts/0    00:00:00 grep --color=auto docker
$ sudo service docker start
docker start/running, process 11837
$ sudo docker ps -a
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
``` 

The start script doesn't bubble up any error and there is no way to switch on verbose mode and it doesn't create the docker log file.
So, ran the command itself to get it to throw an error:

```
# DOCKER_SSD_PIDFILE=/var/run/$BASE-ssd.pid; DOCKER_LOGFILE=/var/log/$BASE.log; touch "$DOCKER_LOGFILE" && chgrp docker "$DOCKER_LOGFILE" && start-stop-daemon --start --background --no-close --pidfile "$DOCKER_SSD_PIDFILE" --exec "/usr/bin/docker" --make-pidfile -- daemon -p "$DOCKER_PIDFILE"
root@svr# INFO[0000] API listen on /var/run/docker.sock
FATA[0000] Error starting daemon: error initializing graphdriver: "/var/lib/docker" contains other graphdrivers: devicemapper; Please cleanup or explicitly choose storage driver (-s <DRIVER>)
```

Is devicemapper no longer supported? 
How can I get the init script to show the errors when they come up instead of telling me that it's up when it's not?

Any help would be greatly appreciated.
Thanks!

**Comment by cpuguy83** [comment] 2015-12-17 01:01
The issue with it not actually starting is most likely because you have used multiple graph drivers (so multiple graph dirs in /var/lib/docker). Since the driver is not explicitly set in your daemon opts there is no way for Docker to know which driver to choose.
Should set this explicitly in your daemon opts.

**Comment by thaJeztah** [comment] 2015-12-17 13:13
Yes, looks like that. Given that you're running on "trusty", I think both `aufs` and `devicemapper` have been used (aufs is the default driver for ubuntu trusty).

The error message ;

`"/var/lib/docker" contains other graphdrivers: devicemapper` indicates that a "devicemapper" directory is also found, and `Please cleanup or explicitly choose storage driver (-s <DRIVER>)` explains that the unwanted directory should be removed, or the `-s` option should be set as a daemon option, to specify which driver you'd like to use.

Closing this issue, because it's not a bug, but feel free to comment here after I've closed

**Closed by thaJeztah** 2015-12-17 13:13 UTC

**Comment by erinmcgill** [comment] 2015-12-17 14:56
Yes, I read that error and the helpful message with the -s but my issue was that the start script doesn't say that it can't start - it indicates that it starts fine. 
Only after I pulled the start command from the init script was I able to get that error. It seems like a bug if the init script is not working properly.

**Comment by thaJeztah** [comment] 2015-12-17 15:37
the init script is located here; https://github.com/docker/docker/blob/master/contrib/init/upstart/docker.conf

After it failed, does `status docker` still output `start/running...`?

**Comment by erinmcgill** [comment] 2015-12-17 15:42
No, I think it tried to start, got a pid, found it couldn't start and died.

And that conf file is exactly what I needed! Added the -s and now it started.

Thanks for all the help!

**Comment by thaJeztah** [comment] 2015-12-17 17:04
You're welcome!
