### ISSUE TITLE
Docker hangs forever if a container is linked to itself

### ISSUE THREAD

**Issue by kelemen** [docker/docker#20271] opened 2016-02-12 12:49 UTC
By accident I passed the `--link` argument to the *run* command with the same container name what I was starting. The result of this action is that Docker hangs forever (also, every subsequent docker command will hang forever) and you have to restart the Docker machine.

My expectation is that it should either add a correct entry to the hosts file or fail starting the container due to illegal link.

**Comment by kelemen** [comment] 2016-02-12 12:57
This the output of `docker version`:

    Client:
     Version:      1.10.0
     API version:  1.22
     Go version:   go1.5.3
     Git commit:   590d5108
     Built:        Thu Feb  4 18:18:11 2016
     OS/Arch:      windows/amd64

    Server:
     Version:      1.10.1
     API version:  1.22
     Go version:   go1.5.3
     Git commit:   9e83765
     Built:        Thu Feb 11 20:39:58 2016
     OS/Arch:      linux/amd64

And this is the result of the `docker info` command:

    Containers: 2
     Running: 2
     Paused: 0
     Stopped: 0
    Images: 9
    Server Version: 1.10.1
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 15
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Plugins:
     Volume: local
     Network: bridge null host
    Kernel Version: 4.1.17-boot2docker
    Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11
    22:34:01 UTC 2016
    OSType: linux
    Architecture: x86_64
    CPUs: 1
    Total Memory: 996.2 MiB
    Name: default
    ID: N5LS:3MJZ:3MIL:OMDU:RCTB:ZY3Z:R4FP:OFMR:375N:KDWG:K5YB:U26Q
    Debug mode (server): true
     File Descriptors: 31
     Goroutines: 44
     System Time: 2016-02-12T12:56:27.9268536Z
     EventsListeners: 1
     Init SHA1:
     Init Path: /usr/local/bin/docker
     Docker Root Dir: /mnt/sda1/var/lib/docker
    Labels:
     provider=virtualbox

**Comment by cpuguy83** [comment] 2016-02-12 15:53
Confirmed, thanks!

**Comment by sanimej** [comment] 2016-02-12 16:37
Deadlock seems to be happening in containerStart() where container lock is taken and the child container (same in this case) tries to take the lock in IsRunning()

**Comment by cpuguy83** [comment] 2016-02-12 16:39
Yeah, we just need to add a check to make sure linked container is not self. I'm sure this must have been in there before...

**Comment by LK4D4** [comment] 2016-02-12 17:10
@cpuguy83 There definitely was something about prevention of recursive links.

**Comment by unclejack** [comment] 2016-02-15 08:56
@cpuguy83 You've probably thought about this already, but having a test for this would probably be a good idea.

**Comment by davidsiefert** [comment] 2016-04-07 20:53
Has anybody started working on a fix for this?  Would adding a simple arguments check be enough to solve this issue?

**Comment by cpuguy83** [comment] 2016-04-07 20:55
@davidsiefert I don't think anyone has.
And yes, a check on the daemon side to ensure that it's not linking to itself seems like a good way to go.

**Comment by AkihiroSuda** [comment] 2016-07-26 06:51
Is this closable as a dup of https://github.com/docker/docker/issues/21834

**Comment by thaJeztah** [comment] 2016-07-26 10:52
I'm no longer able to reproduce this on 1.12 (thanks @AkihiroSuda), so closing this

**Closed by thaJeztah** 2016-07-26 10:52 UTC
Labels: kind/bug
