### ISSUE TITLE
can't  define ulimit in "dockerd config"

### ISSUE THREAD

**Issue by sqleejan** [docker/docker#25560] opened 2016-08-10 06:15 UTC
**Output of `docker version`:**

```
Version:      1.12.0
```
**Steps to reproduce the issue:**
1.in /etc/docker/daemon.json:
     "default-ulimits": {
        "nofile": {
            "Name": "nofile",
            "Hard": 2048,
            "Soft": 1024
        }
    },
2.start dockerd 
3.output of docker log:
FATA[0000] unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: nofile

**Comment by allencloud** [comment] 2016-08-10 09:36
failed with 
```
{
"default-ulimits": {
	"nofile":{}
	}
}
```

**Comment by sqleejan** [comment] 2016-08-10 11:32
@allencloud ok ,but you should do it also.
```
type Config struct {
	CommonConfig

	// Fields below here are platform specific.
	CgroupParent         string                   `json:"cgroup-parent,omitempty"`
	ContainerdAddr       string                   `json:"containerd,omitempty"`
	EnableSelinuxSupport bool                     `json:"selinux-enabled,omitempty"`
	ExecRoot             string                   `json:"exec-root,omitempty"`
	RemappedRoot         string                   `json:"userns-remap,omitempty"`
-	Ulimits              map[string]*units.Ulimit `json:"default-ulimits,omit empty"`
+      Ulimits              map[string]*units.Ulimit `json:"default-ulimit,omitempty"`
	Runtimes             map[string]types.Runtime `json:"runtimes,omitempty"`
	DefaultRuntime       string                   `json:"default-runtime,omitempty"`
	OOMScoreAdjust       int                      `json:"oom-score-adjust,omitempty"`
}
```

**Comment by thaJeztah** [comment] 2016-08-10 13:03
@allencloud @sqleejan looks like this is a duplicate of https://github.com/docker/docker/issues/22309, which also reports this

**Comment by allencloud** [comment] 2016-08-10 13:43
@sqleejan @thaJeztah 
Updated my response. I think there are two kinds of problem in this issue.

**Comment by zzww** [comment] 2016-08-12 09:06
@sqleejan @allencloud 
1、In /etc/docker/daemon.json，my configuration is as follows：

```
......
"default-ulimits": {
    },
......

```

`systemctl status docker `

Docker Daemon start is ok .


2、In /etc/docker/daemon.json，my configuration is as follows：

```
......
"default-ulimit": {
    },
......

```

`systemctl status docker `

Docker Daemon start is ok too.

3、It does not care about “default-ulimit” or “default-ulimits”.

**Comment by allencloud** [comment] 2016-08-12 09:42
@zzww @thaJeztah @sqleejan
Thanks, I tried again. And I can not reproduce what I showed in the details above.
Sorry for the bothering I brought you.
I will try to update the PR maybe 2 days later.

**Comment by BrickXu** [comment] 2016-10-09 13:15
Still can reproduce in docker 1.12.1, any updates ?

**Comment by allencloud** [comment] 2016-10-10 08:24
Oh, @BrickXu, Thanks.  
I think it is in progress. Here is the PR #25566 
ping @vdemeester 
PTAL.

**Closed** 2016-10-17 16:58 UTC

**Comment by BrickXu** [comment] 2016-10-26 08:46
Thanks @allencloud !
