### ISSUE TITLE
Lookup index.docker.io on XXX.XXX.XXX.XXX:53: no such host

### ISSUE THREAD

**Issue by ktf** [docker/docker#20086] opened 2016-02-07 13:05 UTC
I've a problem with docker on a Centos7 machine after I upgraded to 1.10 yesterday. When I do either docker pull or docker search I now get:

```
$ docker search alisw/slc7-builder
Error response from daemon: Get https://index.docker.io/v1/search?q=alisw%2Fslc7-builder: dial tcp: lookup index.docker.io on XXX.XXX.XXX.XXX:53: no such host
```
Notice that everything is fine if on the same machine I do:

```
$ curl https://index.docker.io/v1/search?q=alisw%2Fslc7-builder
{"num_pages": 1, "num_results": 1, "results": [{"is_automated": false, "name": "alisw/slc7-builder", "is_trusted": false, "is_official": false, "star_count": 1, "description": ""}], "page_size": 25, "query": "alisw/slc7-builder", "page": 1}
```

any idea of what might be going wrong? I did restart docker after the update and it does work as expected when using images which have already been downloaded.

**Comment by mavenugo** [comment] 2016-02-07 17:00
@ktf thanks for reporting the issue. We have a couple of open issues -
https://github.com/docker/docker/issues/20037 (which is seen only in `dind` with custom network) and https://github.com/docker/docker/issues/20026 (which is seen only in `centos` with custom network).

Can you please confirm if either of this is true ?

**Comment by mavenugo** [comment] 2016-02-07 17:03
@ktf also, is there a reason why you you have masked out the DNS server ip - `XXX.XXX.XXX.XXX`. Is it `127.0.0.11` ?

**Comment by ktf** [comment] 2016-02-07 20:59
docker version:
```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64
```

docker info

```
# docker info
Containers: 12
 Running: 2
 Paused: 0
 Stopped: 10
Images: 112
Server Version: 1.10.0
Storage Driver: devicemapper
 Pool Name: docker-252:1-92301976-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 53.69 GB
 Backing Filesystem: xfs
 Data file: /dev/docker_vg/data
 Metadata file: /dev/docker_vg/metadata
 Data Space Used: 17.9 GB
 Data Space Total: 154.6 GB
 Data Space Available: 136.7 GB
 Metadata Space Used: 22.06 MB
 Metadata Space Total: 17.05 GB
 Metadata Space Available: 17.02 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-229.4.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.15 GiB
Name: alibuild13.cern.ch
ID: JSRI:LYJY:QIBP:VN3M:CNBJ:MV4C:HXQQ:K4YG:OZ5A:CY6K:6ARJ:6CGH
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by ktf** [comment] 2016-02-07 21:03
Thank you for your reply. I saw the bug reports you mention, but they do not seem to apply to my case. I do not run docker in docker and if I use the dns from inside the container everything works. What does not work is really just the downloading of new images. The `XXX.XXX.XXX.XXX` is simply an private address within our network where I run `mesos-dns`. As I said name resolution there works fine and if I do:

```
# dig index.docker.io +noall +answer +nocomments
```

I get:

```
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.2 <<>> index.docker.io +noall +answer +nocomments
;; global options: +cmd
index.docker.io.        140     IN      CNAME   elb-io.us-east-1.aws.dckr.io.
elb-io.us-east-1.aws.dckr.io. 740 IN    CNAME   us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com.
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 60 IN A 54.164.250.255
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 60 IN A 52.0.10.162
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 60 IN A 54.152.78.181
```

**Comment by ktf** [comment] 2016-02-07 21:05
Ah, I do not use custom network.

**Comment by ktf** [comment] 2016-02-07 21:07
Stopping IP tables has no effect.

**Comment by mavenugo** [comment] 2016-02-07 21:34
@ktf thanks for the info. I guess the `/etc/resolv.conf` in the host is updated with mesos-dns ip-address.
It is infact interesting that the container DNS resolution works, but it is failing only for the image download. this btw is very similar to https://github.com/docker/docker/issues/20037 (though it is seen in dind environment). 

>> Stopping IP tables has no effect.

Did you mean firewalld ?

**Comment by ktf** [comment] 2016-02-07 21:48
Correct. We have three mesos-dns ip addresses and the static DNS in /etc/resolv.conf. One thing I just noticed is that if I drop one (any of the three) of the mesos-dns IPs from resolv.conf, then it works again. Is there some sort of issue when too many IPs are listed in resolv.conf?

**Comment by ktf** [comment] 2016-02-07 22:13
Ok, I think I understand what is going on. Is it possible that name resolution only considers the first three DNS is resolv.conf? If I interleave the mesos-dns IPs with our primary DNS IPs things work again.

**Comment by mavenugo** [comment] 2016-02-07 23:07
@ktf thanks for the confirmation. It seems like a fundamental restriction in libc (as described in http://unix.stackexchange.com/questions/28004/how-to-overcome-libc-resolver-limitation-of-maximum-3-nameservers and other places). Since you are not in a dind environment, this seems to be a fundamental limitation in the way the host performs the name resolution. 

So, am curious to know if this worked for you in 1.9 and starts to fail in 1.10 ?

**Comment by ktf** [comment] 2016-02-08 08:24
@mavenugo yep, looks like it's a libc feature, but then I do not understand how come dig and wget  (and docker 1.9) actually work.

**Comment by ktf** [comment] 2016-02-08 08:26
Also, if I have an IPv6 DNS in resolv.conf, things are still broken.

**Comment by sanimej** [comment] 2016-02-08 10:11
@ktf  Can you share your complete resolv.conf file that worked in 1.9. Also, do you have IPv6 configured in the host and the interface that is sourcing the DNS queries ?

Between golang 1.4 and 1.5 there is a change in the way go resolves the names. In 1.5 golang tries to use a native resolver when possible. Depending on your configs its possible that go native resolver interprets the resolv.conf file differently compared to what libc resolver does.

**Comment by ktf** [comment] 2016-02-08 10:29
The resolv.conf which used to work is:

```
; generated by /usr/sbin/dhclient-script
nameserver XXX.XXX.XXX.XX
nameserver XXX.XXX.XXX.XX
nameserver XXX.XXX.XXX.XX
search cern.ch.
nameserver XXXX:XXXX:XXX:1100::5
nameserver XXXX:XXXX:XXX:1000::5
```

notice also that mesos-dns is configured with a fallback to the official DNS, so in principle already the first nameserver should have the correct answer to the query. IPv6 in principle is correctly configured, but I would need to check.

**Comment by ktf** [comment] 2016-02-08 15:34
Ok, forget about IPv6, that seems to be a separate issue.

**Comment by mavenugo** [comment] 2016-02-08 16:07
@ktf sorry. it is still not clear. in the resolv.conf that you provided above, I see only 3 nameservers.
(which seems to be acceptable by libc). I thought the problem is seen only when the number of  configured nameservers exceeds 3. Again, as @sanimej suggested, the `golang` update (1.5.3) could be the reason for the 1.9 vs 1.10 difference.
Since, you are not using user-defined networks & this seems to be a well known infra behavior (due to the libc limitation), I think we should close this issue. WDYT ?

**Comment by mavenugo** [comment] 2016-02-08 18:36
@ktf I built a 1.10.0 binary using 1.4.3 to confirm this theory. Could you pls give it a try ?
https://app.box.com/s/k5l6b38490bzlk8xq4pifnu0g89alkk9

**Comment by ktf** [comment] 2016-02-08 20:33
404. Do I need to register?

**Comment by ktf** [comment] 2016-02-08 20:37
There are 5 nameservers above. 3 IPv4 and 2 IPv6. IPv6 ones are the official cern ones, the 3 IPv4 are from mesos-dns. if this is a libc limitation, fine, but it does not explain why curl / wget (and docker 1.9)  works while docker 1.10 does not.

**Comment by mavenugo** [comment] 2016-02-08 21:26
@ktf can you try : https://app.box.com/s/k5l6b38490bzlk8xq4pifnu0g89alkk9 ?

**Comment by sanimej** [comment] 2016-02-08 21:54
@ktf  Earlier you said.. 

> We have three mesos-dns ip addresses and the static DNS in /etc/resolv.conf. One thing I just noticed is that if I drop one (any of the three) of the mesos-dns IPs from resolv.conf, then it works again

But in the resolv.conf output you provided there are only three IPv4 nameservers. Is one of them the static DNS ? 

you also said.. 

> notice also that mesos-dns is configured with a fallback to the official DNS, so in principle already the first nameserver should have the correct answer to the query

If the mesos-dns has the correct fallback configured then there is no need to have the static DNS server also listed in resolv.conf.

As per resolv.conf documentation the count of 3 nameservers includes v4 and v6..

```
nameserver Name server IP address
Internet address of a name server that the resolver should query, either an IPv4 address (in dot notation), or an IPv6 address in colon (and possibly dot) notation as per RFC 2373. Up to MAXNS (currently 3, see <resolv.h>) name servers may be listed, one per keyword.
```

**Comment by ktf** [comment] 2016-02-08 22:32
@sanimej Maybe there is some misunderstanding. As I said the issue is unrelated to IPv6 (there was a separate issue with IPv6 which is now solved on my side). 

While I also found some documentation saying that 3 nameservers are the limit for `resolv.conf`, I've not encountered such a limitation neither using dig, nor curl nor with the old docker.

Also I verified that mesos-dns does have the correct fallback, and using `dig @ip-of-mesos-dns index.docker.io`. IIUC, that should not work if the fallback was not enabled. So to summarise I see two potential issues:

1. docker 1.10 is not able to handle more than 3 nameservers in `resolv.conf`. This might or might not be desired behavior.
2. docker 1.10 is not able to understand mesos-dns replies for hostnames whose resolution is delegated to the external (official) DNS.

thinking about it, issue 2. could be the real culprit, which is also hiding the fact I've more than 3 nameservers in my resolv.conf for all the other cases (which work, because they are able to use mesos-dns reply for non mesos names).

Regarding your build. Could you please provide instructions on how to test? Can I use it client only?

**Comment by mavenugo** [comment] 2016-02-08 23:12
@ktf pls use the binary to run the daemon & possibly the client as well.

**Comment by sanimej** [comment] 2016-02-08 23:22
@ktf Please share your observations with the build @mavenugo provided (it has to be run as daemon; running as client is optional). Since it uses golang 1.4.3 we should see a behavior similar to 1.9

**Comment by ktf** [comment] 2016-02-09 10:36
@mavenugo I did the following:

```  
180  service docker stop
181  mv /usr/bin/docker /usr/bin/docker.safe
182  mv docker-1.10.0.go1.4.3 /usr/bin/docker
183  chmod +x /usr/bin/docker
184  service docker restart
185  docker ps
186  docker search alisw/slc7-builder
187  vim /etc/resolv.conf
188  docker search alisw/slc7-builder
189  vim /etc/resolv.conf
```

And it still behaves as before. This:

```
nameserver 192.168.0.1
nameserver 192.168.0.2
search cern.ch
nameserver 137.138.16.5
nameserver 137.138.17.5
```

works. While this:

```
nameserver 192.168.0.1
nameserver 192.168.0.2
nameserver 192.168.0.3
search cern.ch
nameserver 137.138.16.5
nameserver 137.138.17.5
```

does not.

Also:

```
# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   590d5108-unsupported
 Built:        Mon Feb  8 18:15:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   590d5108-unsupported
 Built:        Mon Feb  8 18:15:48 2016
 OS/Arch:      linux/amd64
```

**Comment by ktf** [comment] 2016-02-09 10:41
Also if I change resolv.conf to:

```
# Generated by NetworkManager
nameserver 192.168.0.1
nameserver 192.168.0.2
search cern.ch
```

i.e. mesos-dns only, dig still works, while `docker search` does not.

```
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.2 <<>> index.docker.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32796
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 4, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;index.docker.io.               IN      A

;; ANSWER SECTION:
index.docker.io.        154     IN      CNAME   elb-io.us-east-1.aws.dckr.io.
elb-io.us-east-1.aws.dckr.io. 317 IN    CNAME   us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com.
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 60 IN A 54.164.250.255
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 60 IN A 52.0.10.162
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 60 IN A 54.152.78.181

;; AUTHORITY SECTION:
us-east-1.elb.amazonaws.com. 2  IN      NS      ns-1119.awsdns-11.org.
us-east-1.elb.amazonaws.com. 2  IN      NS      ns-1793.awsdns-32.co.uk.
us-east-1.elb.amazonaws.com. 2  IN      NS      ns-934.awsdns-52.net.
us-east-1.elb.amazonaws.com. 2  IN      NS      ns-235.awsdns-29.com.

;; ADDITIONAL SECTION:
ns-235.awsdns-29.com.   815     IN      A       205.251.192.235

;; Query time: 14 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Tue Feb 09 11:40:17 CET 2016
;; MSG SIZE  rcvd: 739
```

**Comment by mavenugo** [comment] 2016-02-09 12:26
@ktf this looks a lot like the compression issue reported in https://github.com/docker/docker/issues/20132. But it is not a dupe since you are not using user-defined networks, I think this could be a client (docker daemon) behavior that causes the issue (since `docker search` fails).

As explained here : https://github.com/docker/docker/issues/20132#issuecomment-181648969,  this could be because of the way the upstream resolver works. Hence when you add the static resolver, it could be compressing the response while mesos-dns did not and hence the `docker search` succeeded. Can you check his behavior as explained in the above comment between these upstream DNS resolvers  (mesos-dns vs your static resolver) ?

**Comment by sanimej** [comment] 2016-02-09 17:12
@ktf Please take a look at the compression issue @mavenugo referred to (in #20132 and in #20037).  mesos-dns also is using the same DNS library (miekg/dns) Docker embedded DNS is using and most likely will have the same compression issue. The reason dig works is because it handles the uncompressed result correctly where as the golang net package doesn't seem to. You might want to check with the mesos-dns support on this.

Since the mesos-dns servers are not able to resolve the name correctly having some other upstream DNS server which does the compression correctly works. But it has to be one of the first three nameservers in resolv.conf.

**Comment by sanimej** [comment] 2016-02-09 18:39
@ktf mesos-dns issue with docker pull is already reported [here] (https://github.com/mesosphere/mesos-dns/issues/170)

**Comment by tiborvass** [comment] 2016-02-09 22:19
@sanimej is this confirmation that we can close this issue?

**Comment by mavenugo** [comment] 2016-02-10 01:45
@tiborvass yes. it is not our embedded DNS issue. But docker as a client is affected by the mesos-dns issue. Lets close this.

**Comment by tiborvass** [comment] 2016-02-10 01:46
Fine, thanks for confirming. Feel free to continue the discussions.

**Closed by tiborvass** 2016-02-10 01:46 UTC
Labels: group/networking

**Comment by ktf** [comment] 2016-02-10 09:00
Agreed this is a mesos-dns issue. I will try to move to a more recent version. Thank you for the support.

**Comment by sanimej** [comment] 2016-02-10 11:37
Here is one way to confirm the behavior change between golang 1.4.3 and 1.5.3 (the reason why it worked for you in docker 1.9).

I have two docker images sanimej/go143test and sanimej/go153test. These images run the same go code below with go 1.4.3 and 1.5.3 respectively..

```
package main

import (
        "fmt"
        "net"
)

func main() {
        addr, err := net.LookupHost("index.docker.io")
        if err == nil {
                fmt.Println(addr[0])
        } else {
                fmt.Println(err)
        }
}
```
In your host resolv.conf add the IP of the fallback DNS server used by the mesos-dns and start the containers on a bridge network..

docker run --net docker sanimej/go153test - will fail and
docker run --net docker sanimej/go143test - will work
