### ISSUE TITLE
"docker logs" omits partial lines such as prompts for running containers.

### ISSUE THREAD

**Issue by mvollmer** [docker/docker#18497] opened 2015-12-08 13:42 UTC
This is #8443, which I think was closed erroneously.

```
# docker pull fedora
# docker run --name=f-shell -t -i fedora /bin/bash
[root@c9218fc786ae /]# 
```

and in another terminal

```
# docker logs f-shell
<empty>
#
```

This is annoying for tools like Cockpit, see https://github.com/cockpit-project/cockpit/issues/1159.

Cockpit can show a fully functional terminal for a container that has been created with the "-t -i" options.  The terminal is initialized with the log of a container, and it is confusing if the prompt is missing.

**Comment by mvollmer** [comment] 2015-12-08 13:43
[root@f23 test]# docker version
Client:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64
[root@f23 test]# docker indo
docker: 'indo' is not a docker command.
See 'docker --help'.
[root@f23 test]# docker info
Containers: 1
Images: 2
Server Version: 1.9.1-fc23
Storage Driver: devicemapper
 Pool Name: docker-252:3-1526505-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.06 GB
 Data Space Total: 107.4 GB
 Data Space Available: 268.2 MB
 Metadata Space Used: 1.708 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 268.2 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.2.6-301.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
CPUs: 1
Total Memory: 1.954 GiB
Name: f23.mvo.lan
ID: MCUP:P6G4:4NEW:MU3E:FWVJ:NJGL:6ZAT:JXF6:6FJT:3HQ6:ZXND:5GA2
[root@f23 test]# uname -a
Linux f23.mvo.lan 4.2.6-301.fc23.x86_64 #1 SMP Fri Nov 20 22:22:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment] 2015-12-08 18:03
Yes, this is expected behavior.
Logs are done per line.

If you want the actual stream, use attach.

**Comment by mvollmer** [comment] 2015-12-09 08:47
> If you want the actual stream, you should use attach.

As far as I can see, `attach` doesn't give historical data.  So if you have a running container that sits at a "Are you sure? [Yn]" prompt, and you attach to it after it has printed that prompt, you wont see that prompt, right?

**Comment by cpuguy83** [comment] 2015-12-09 12:04
The attach API does give history if requested... And if you are using a log driver that supports reading.

**Comment by LK4D4** [comment] 2016-09-14 15:57
Closing this again because that's how logging works.

**Closed by LK4D4** 2016-09-14 15:57 UTC
Labels: area/logging
