### ISSUE TITLE
Docker daemon run failed with "error="oci runtime error: open /cgroups/cpuset/sys/cpuset.cpus: no such file or directory"

### ISSUE THREAD

**Issue by willstudy** [docker/docker#29018] opened 2016-12-01 07:57 UTC
#### docker info
```
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 2
Server Version: 1.11.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0_2-0-0-0
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.6 GiB
Name: gzns-dumi-boss2.gzns.baidu.com
ID: MC6X:U5IG:KXI7:MPMB:SY6O:47FB:7ETP:XJWE:WCNS:7YZT:4BCY:XK46
Docker Root Dir: /home/work/docker/runtime_1.11
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```
#### docker version
```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
```
#### uname -a
```Linux  3.10.0_2-0-0-0 #1 SMP Tue Sep 20 17:18:54 CST 2016 x86_64 x86_64 x86_64 GNU/Linux```

#### mount
```
/dev/sda2 on / type ext2 (rw)
proc on /proc type proc (rw)
sysfs on /sys type sysfs (rw)
devpts on /dev/pts type devpts (rw,gid=5,mode=620)
tmpfs on /dev/shm type tmpfs (rw)
/dev/sda3 on /var type ext2 (rw)
/dev/sda4 on /noah type ext2 (rw)
/dev/sda5 on /tmp type ext2 (rw)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw)
/dev/sda8 on /home type ext4 (rw)
cgroup on /sys/fs/cgroup type tmpfs (rw,uid=0,gid=0,mode=0755)
```
But the docker daemon output 
```
time="2016-12-01T14:35:05.411511614+08:00" level=info msg="Loading containers: done."
time="2016-12-01T14:35:05.411538637+08:00" level=info msg="Daemon has completed initialization"
time="2016-12-01T14:35:05.411569669+08:00" level=info msg="Docker daemon" commit=4dc5990 graphdriver=overlay version=1.11.0
time="2016-12-01T14:35:05.431040369+08:00" level=info msg="API listen on [::]:2375"
time="2016-12-01T14:35:05.431138080+08:00" level=info msg="API listen on /var/run/docker.sock"
time="2016-12-01T14:35:05+08:00" level=error msg="containerd: start container" error="oci runtime error: open /cgroups/cpuset/sys/cpuset.cpus: no such file or directory" id=7fb87c09fbeabc352e2a3d6805917d2fd53e3783a9df1d65bf5698a191e26272
time="2016-12-01T14:35:05.964405392+08:00" level=error msg="Handler for POST /containers/7fb87c09fbeabc352e2a3d6805917d2fd53e3783a9df1d65bf5698a191e26272/start returned error: Container command '/pause' not found or does not exist."
time="2016-12-01T14:35:17+08:00" level=error msg="containerd: start container" error="oci runtime error: open /cgroups/cpuset/sys/cpuset.cpus: no such file or directory" id=b53db009afcae81d0bb5ba1241725017557a0953741b44674154569c1d507e44
time="2016-12-01T14:35:17.599451111+08:00" level=error msg="Handler for POST /containers/b53db009afcae81d0bb5ba1241725017557a0953741b44674154569c1d507e44/start returned error: Container command '/pause' not found or does not exist."
```
What's wrong with my docker daemon ? Can anyone help me ? Thanks very much ~

**Comment by mlaventure** [comment] 2016-12-01 15:39
It looks like `runc` didn't detect the right path for cgroup

Could you provide the output of `cat /proc/self/mountinfo` since it's what `runc` uses to get the cgroup root path?

**Comment by willstudy** [comment] 2016-12-02 02:42
#### cat /proc/self/mountinfo 
```
17 22 0:3 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
18 22 0:16 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
19 22 0:5 / /dev rw,nosuid,relatime - devtmpfs devtmpfs rw,size=65836300k,nr_inodes=16459075,mode=755
20 19 0:11 / /dev/pts rw,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=000
21 19 0:17 / /dev/shm rw,nosuid,nodev,relatime - tmpfs tmpfs rw
22 1 8:2 / / rw,relatime - ext2 /dev/sda2 rw,errors=continue
15 22 8:3 / /var rw,relatime - ext2 /dev/sda3 rw,errors=continue
23 22 8:4 / /noah rw,relatime - ext2 /dev/sda4 rw,errors=continue
24 22 8:5 / /matrix rw,relatime - ext2 /dev/sda5 rw,errors=continue
25 22 8:6 / /has rw,relatime - ext2 /dev/sda6 rw,errors=continue
26 22 8:7 / /tmp rw,relatime - ext2 /dev/sda7 rw,errors=continue
27 17 0:14 / /proc/sys/fs/binfmt_misc rw,relatime - binfmt_misc none rw
28 23 0:18 / /noah/download rw,relatime - tmpfs none rw,size=819200k,mode=755
29 23 0:19 / /noah/modules rw,relatime - tmpfs none rw,size=819200k,mode=755
30 23 0:20 / /noah/tmp rw,relatime - tmpfs none rw,size=409600k,mode=755
31 23 0:21 / /noah/bin rw,relatime - tmpfs none rw,size=102400k,mode=755
32 24 0:22 / /matrix/run rw,relatime - tmpfs none rw,size=32768k
33 22 0:23 / /cgroups/cpu rw,relatime - cgroup cpu rw,cpu
34 22 0:24 / /cgroups/cpuacct rw,relatime - cgroup cpuacct rw,cpuacct
35 22 0:25 / /cgroups/freezer rw,relatime - cgroup freezer rw,freezer
36 22 0:26 / /cgroups/memory rw,relatime - cgroup memory rw,memory
37 22 8:8 / /home rw,relatime - ext4 /dev/sda8 rw,data=ordered
38 18 0:27 / /sys/fs/cgroup rw,relatime - tmpfs cgroup rw,mode=755
39 38 0:28 / /sys/fs/cgroup/cpuset rw,relatime - cgroup cgroup rw,cpuset
40 38 0:23 / /sys/fs/cgroup/cpu rw,relatime - cgroup cgroup rw,cpu
41 38 0:24 / /sys/fs/cgroup/cpuacct rw,relatime - cgroup cgroup rw,cpuacct
42 38 0:26 / /sys/fs/cgroup/memory rw,relatime - cgroup cgroup rw,memory
43 38 0:29 / /sys/fs/cgroup/devices rw,relatime - cgroup cgroup rw,devices
44 38 0:25 / /sys/fs/cgroup/freezer rw,relatime - cgroup cgroup rw,freezer
45 38 0:30 / /sys/fs/cgroup/net_cls rw,relatime - cgroup cgroup rw,net_cls
46 38 0:31 / /sys/fs/cgroup/blkio rw,relatime - cgroup cgroup rw,blkio
47 38 0:32 / /sys/fs/cgroup/perf_event rw,relatime - cgroup cgroup rw,perf_event
48 38 0:33 / /sys/fs/cgroup/hugetlb rw,relatime - cgroup cgroup rw,hugetlb
```

@mlaventure   Thanks a lot for your help.

**Comment by YummyPeng** [comment] 2016-12-02 06:35
This issue may be caused by the following mountpoints:
> 33 22 0:23 / /cgroups/cpu rw,relatime - cgroup cpu rw,cpu
34 22 0:24 / /cgroups/cpuacct rw,relatime - cgroup cpuacct rw,cpuacct
35 22 0:25 / /cgroups/freezer rw,relatime - cgroup freezer rw,freezer
36 22 0:26 / /cgroups/memory rw,relatime - cgroup memory rw,memory

Try to `umount` them to see if docker can work.

And could you provide the output of `docker-runc --version`? :wink:

**Comment by willstudy** [comment] 2016-12-02 07:37
@YummyPeng  Thank you very much, this works for me. ^_^
```
umount /cgroups/cpu
umount /cgroups/cpuacct
umount /cgroups/freezer
umount /cgroups/memory
```

**Comment by cprenzberg** [comment] 2016-12-02 09:49
@YummyPeng  maybe you have some quick insights into something slightly similar in #28962? :)

**Comment by mlaventure** [comment] 2016-12-02 16:42
thanks for having a look @YummyPeng , closing this, since the extra mounts where indeed the issue.

**Closed by mlaventure** 2016-12-02 16:42 UTC
Labels: area/runtime, version/1.11
