### ISSUE TITLE
ENV command set env var not accepted by CMD / ENTRYPOINT (exec format)

### ISSUE THREAD

**Issue by djsly** [docker/docker#4783] opened 2014-03-19 22:23 UTC
I was using the following

ENV MYPATH /usr/local/myPath
CMD [ "ls", "-la", "$MYPATH"]

and I get 
ls: cannot access $MYPATH: No such file or directory

But, if I used the other format
CMD ls -la $MYPATH

then the listing is correct.

CMD [ "ls", "-la", $NMMHOME ] simply doesn't work

Now I also was trying something like this.

ENTRYPOINT [ "$MYPATH/start.sh"]

doesn't work. Some problem : unable to locate $MYPATH/start.sh

But similarly to CMD 'shell version'

ENTRYPOINT $MYPATH/start.sh

works fine.

Also the start.sh is referencing the $MYPATH as well and it sees the correct value.

So I think there is still a bug in specifying the environment variables within the CMD / ENTRYPOINT commands when using the exec like way (preferred method)

**Comment by davealbert** [comment] 2015-02-17 10:49
I too am having trouble understanding when to use the exec format CMD [...] versus the shell format CMD ...  I understand the exec format is preferred, but I don't understand why because of the limitations.

**Comment by duglin** [comment] 2015-03-04 22:31
@tiborvass I know that we explicitly don't do env var substitutions for CMD and ENTRYPOINT, with the assumption that the shell will do it, but I'm wondering if we should do it *just* when the JSON format is used?  It won't be as full featured as the real shell (even with https://github.com/docker/docker/pull/11149 ) but it'll be better than what do today.  Thoughts?

**Comment by tianon** [comment] 2015-03-05 16:36
Please don't apply any processing to the JSON versions -- the whole point
of them is that it gives you, as the Dockerfile author, explicit control
over exactly what's passed to "execv".

**Comment by tiborvass** [comment] 2015-03-07 16:53
I'll just say that if there is an easy workaround (and in this case there is), let's keep the workaround for now. It shouldn't be a big pain and if it is we'll know it.

Maybe we could make sure the documentation is very explicit about this difference?
Ping @SvenDowideit @moxiegirl @fredlf 

Other than that, I'd be tempted to close this issue.

**Comment by moxiegirl** [comment] 2015-03-08 04:40
@tiborvass I think it makes sense to clarify this in the docs. I'll label it white-belt and if it doesn't get cleaned up by the birthday, I'll pick it up.

**Comment by duglin** [comment] 2015-03-08 14:04
Just checked and I think the docs are probably ok, both CMD and ENTRYPOINT have text like this:
- - - -
Note: Unlike the shell form, the exec form does not invoke a command shell. This means that normal shell processing does not happen. For example, ENTRYPOINT [ "echo", "$HOME" ] will not do variable substitution on $HOME. If you want shell processing then either use the shell form or execute a shell directly, for example: ENTRYPOINT [ "sh", "-c", "echo", "$HOME" ]. Variables that are defined in the Dockerfileusing ENV, will be substituted by the Dockerfile parser.
- - - -
which I think covers it.  But if you want it to say more let me know and I can tweak it.

**Comment by tiborvass** [comment] 2015-03-08 17:24
@duglin I think the confusion comes from the builder replacing variables, versus the shell replacing variables. The docs you referred to only address the shell substitution. Currently, we substitute `VOLUME $foo` as well as `VOLUME ["$foo"]` if `foo` was defined by an `ENV`. IOW there's `$HOME` from the shell, and there's `$HOME` if you used `ENV HOME`. That's where the confusion comes from. 

*Personal opinion*: At this point I don't know what to do to make this clearer, we keep digging a bigger hole with these tiny changes that seem to be fine and relieve an immediate pain only to later introduce more confusion :(

I would vote for discouraging replacing variables in the JSON format, and that for all commands, but I am afraid there is no good solution right now.

**Comment by duglin** [comment] 2015-03-08 20:35
@tiborvass there's also: https://docs.docker.com/reference/builder/#environment-replacement
IMO any confusion that might be there are when people expect it to act like it does on the shell, but sometimes doesn't, but we're getting closer. Its when we don't do what people expect, like substituting on the JSON form, that I think will confuse people - but I have a personal dislike for that form  :-)

**Comment by cpuguy83** [comment] 2015-09-15 00:22
Can we close this? This looks like well documented, expected behavior, unless you found somewhere the docs seem lacking?

**Comment by tiborvass** [comment] 2015-09-23 00:17
Agree with @cpuguy83. Closing.

Let us know if you think docs can improved. Feel free also to send a Pull Request to the documentation if you want to :)

**Closed by tiborvass** 2015-09-23 00:17 UTC
Labels: exp/beginner, kind/docs, status/more-info-needed

**Comment by djsly** [comment] 2015-09-23 00:48
Sorry for not responding before. This issue can be closed no problem. The doc is more clear indeed. 
Thanks ! 

Sent from Outlook on iPhone 




On Tue, Sep 22, 2015 at 5:19 PM -0700, "Tibor Vass" <notifications@github.com> wrote:












Closed #4783.

**Comment by apapanico** [comment] 2016-05-24 20:19
Hey, I just found this issue but I think it's pertinent.  Does the environment variable behavior also apply when launching a container using an entrypoint script:

`ENTRYPOINT ['./entrypoint.sh']`

I've been running into this problem where the dockerfile sets an environment variable and it carries over when doing a debug launch with bash but not when doing the full launch with the entrypoint script.  It seems likely it's the same thing.

If so, my struggle to understand this behavior for a while was I was looking under https://docs.docker.com/engine/reference/builder/#env and nothing there points out this issue of environment variables being lost because of the exec form of CMD and ENTRYPOINT.  Perhaps a reference like this in the ENV section of the builder reference.

> **Note**:
> As noted for `CMD` and `ENTRYPOINT`, the *exec* form for `CMD` and `ENTRYPOINT` does not invoke 
> a command shell. This means that normal shell processing does not happen and therefore 
> variable substitution will not be applied.  The consequence is that environment variables set here will 
> not available to the container when using the *exec* form.

**Comment by apapanico** [comment] 2016-05-24 20:41
Actually, I suspect the variable substitution will never work with an ENTRYPOINT script.  It seems that with both ENTRYPOINT and CMD, there is no variable substitution.  Perhaps it defaults to exec form because of the combination?  I found a workaround for myself.

**Comment by thaJeztah** [comment] 2016-05-24 21:06
Note that your example is not valid JSON;

    ENTRYPOINT ['./entrypoint.sh']

Should be

    ENTRYPOINT ["./entrypoint.sh"]

**Comment by duglin** [comment] 2016-05-24 21:25
env var are available in your script/environment - they're just not processed on the cmd line since there's no shell to parse/process them.

**Comment by apapanico** [comment] 2016-05-24 22:18
Okay.  I had a few things wrong above.  Here's a complete MWE that I think shows the full extent of the behavior.  (And in practice I was using proper JSON.  Just wrote it incorrectly here).

Each variable is meant to vary among user which created it (`VAR_1` vs `VAR_2`), where it was created (`VAR_1` and `VAR_2` created in `Dockerfile`; `VAR_3` in `docker-compose.yml`, and `VAR_4` and `VAR_5` in `entrypoint.sh`; and `VAR_4` and `VAR_5` with export or not).

The variables are present in the entrypoint script but none of them make it to the `exec` command (even the one that was exported).  I would like to be able to have the variables available for that final exec command.

**Dockerfile**
```
FROM debian:wheezy
ENV VAR_1 var1
RUN useradd -ms /bin/bash -d /myuser/ myuser
COPY entrypoint.sh /myuser/entrypoint.sh 
RUN chmod +x /myuser/entrypoint.sh
RUN chown -R myuser:myuser /myuser
USER myuser
ENV VAR_2 var2
ENTRYPOINT ["/myuser/entrypoint.sh"]
```

**entrypoint.sh**
```
CMD="echo"
export VAR_4=var4
VAR_5=var5
echo "Inside entrypoint.sh:" ${VAR_1} ${VAR_2} ${VAR_3} ${VAR_4} ${VAR_5}
exec $CMD "$@"
```

**docker-compose.yml**
```
example:
    image: varexample
    restart: always
    environment:
      - VAR_3=var3
    command: "docker-compose command: ${VAR_1} ${VAR_2} ${VAR_3} ${VAR_4} ${VAR_5}"
```

**Log output**
```
$ docker-compose logs example
WARNING: The VAR_1 variable is not set. Defaulting to a blank string.
WARNING: The VAR_2 variable is not set. Defaulting to a blank string.
WARNING: The VAR_3 variable is not set. Defaulting to a blank string.
WARNING: The VAR_4 variable is not set. Defaulting to a blank string.
WARNING: The VAR_5 variable is not set. Defaulting to a blank string.
Attaching to dockerexample_example_1
example_1  | Inside entrypoint.sh: var1 var2 var3 var4 var5
example_1  | docker-compose command:
...
```

**Comment by mNantern** [comment] 2016-10-11 06:04
I have the same problem as @apapanico . Is there a workaround or any news about that issue ?

Thank you !

**Comment by ORESoftware** [comment] 2016-12-01 04:29
Here is one solution to this type of problem:

http://stackoverflow.com/questions/40902445/using-variable-interpolation-in-string-in-docker/40902661#40902661

**Comment by slaout** [comment] 2018-11-28 14:31
Let's say our Dockerfile has:

    ENV VARIABLE=replaced

And we want to run this:

    docker run <image> arg1 arg2

I obviously wanted this output:

	# => replaced arg1 arg2

But no provided solution would allow both variable substitution and arguments passing.

Here are the options I tested (the one found on internet, plus a few others):

    ENTRYPOINT echo $VARIABLE
    # => replaced

	ENTRYPOINT [ "echo", "$VARIABLE" ]
	# => $VARIABLE arg1 arg2

	ENTRYPOINT [ "sh", "-c", "echo", "$VARIABLE" ]
	# =>

	ENTRYPOINT [ "sh", "-c", "echo $VARIABLE" ]
	# => replaced

	ENTRYPOINT [ "sh", "-c", "echo $VARIABLE $@" ]
	# => replaced arg2
	
	ENTRYPOINT [ "sh", "-c", "echo $@", "$VARIABLE" ]
	# => arg1 arg2

And FINALLY, I found this one:

	ENTRYPOINT [ "sh", "-c", "echo $VARIABLE $0 $@" ]
	# => replaced arg1 arg2

It works!!!
But I feel SOOOO dirty!

Obviously, in real life, I wanted to do something more useful:

    docker run <image> --app.options.additional.second=true --app.options.additional.third=false

    ENTRYPOINT [ "sh", "-c", "java -Xmx$XMX $0 $@", \
                 "-jar", \
                 "/my.jar", \
                 "--app.options.first=true" ]

**Comment by sumitkute** [comment] 2019-05-13 04:27
ENV QUEUENAME=sendQueue
ENTRYPOINT ["dotnet", "myproject.dll", "$QUEUENAME"]

not working

**Comment by mavencode01** [comment] 2019-08-03 15:56
You could create a script and run the command which should work.

```
ENTRYPOINT ["./bootstrap.sh"]
```

script file - bootstrap.sh
```
#!/usr/bin/env sh

dotnet  myproject.dll $QUEUENAME
```
