### ISSUE TITLE
Make test-integration-cli failed

### ISSUE THREAD

**Issue by zhanghuanzhong** [docker/docker#19151] opened 2016-01-07 03:56 UTC
Description of problem:
No change with the upstream code but the tests `DockerHubPullSuite.TestPullFromCentralRegistry` and  `DockerHubPullSuite.TestPullFromCentralRegistryImplicitRefParts` failed.

More info:
```
[root@localhost docker]# TESTFLAGS='-check.f DockerHubPullSuite.TestPullFromCentralRegistry' make test-integration-cli
docker run --rm -i --privileged -e BUILDFLAGS -e DOCKER_CLIENTONLY -e DOCKER_DEBUG -e DOCKER_EXPERIMENTAL -e DOCKER_FILE -e DOCKER_GRAPHDRIVER -e DOCKER_REMAP_ROOT -e DOCKER_STORAGE_OPTS -e DOCKER_USERLANDPROXY -e TESTDIRS -e TESTFLAGS -e TIMEOUT -v "/home/docker/bundles:/go/src/github.com/docker/docker/bundles" -t "docker-dev:master" hack/make.sh dynbinary test-integration-cli

bundles/1.10.0-dev already exists. Removing.

=====dynbinary====
---> Making bundle: dynbinary (in bundles/1.10.0-dev/dynbinary)
Created binary: bundles/1.10.0-dev/dynbinary/dockerinit-1.10.0-dev
Building: bundles/1.10.0-dev/dynbinary/docker-1.10.0-dev
Created binary: bundles/1.10.0-dev/dynbinary/docker-1.10.0-dev

=====test-integration-cli====
---> Making bundle: test-integration-cli (in bundles/1.10.0-dev/test-integration-cli)
---> Making bundle: .integration-daemon-start (in bundles/1.10.0-dev/test-integration-cli)
+++ exec docker daemon --debug --host unix:///go/src/github.com/docker/docker/bundles/1.10.0-dev/test-integration-cli/docker.sock --storage-driver vfs --pidfile bundles/1.10.0-dev/test-integration-cli/docker.pid --userland-proxy=true
---> Making bundle: .integration-daemon-setup (in bundles/1.10.0-dev/test-integration-cli)
---> Making bundle: .ensure-emptyfs (in bundles/1.10.0-dev/test-integration-cli)
++++ tar -cC bundles/1.10.0-dev/test-integration-cli/emptyfs .
++++ docker load
---> Making bundle: .ensure-frozen-images (in bundles/1.10.0-dev/test-integration-cli)
++++ tar -cC /docker-frozen-images .
++++ docker load
---> Making bundle: .ensure-httpserver (in bundles/1.10.0-dev/test-integration-cli)
+ go test -check.f DockerHubPullSuite.TestPullFromCentralRegistry -test.timeout=60m -check.v github.com/docker/docker/integration-cli
INFO: Testing against a local daemon

----------------------------------------------------------------------
FAIL: docker_cli_pull_test.go:20: DockerHubPullSuite.TestPullFromCentralRegistry

docker_cli_pull_test.go:26:
    c.Assert(out, checker.Contains, "Pulling from library/hello-world", check.Commentf("expected the 'library/' prefix to be automatically assumed"))
... obtained string = "" +
...     "Using default tag: latest\n" +
...     "Pulling repository docker.io/library/hello-world\n" +
...     "975b84d108f1: Pulling image (latest) from docker.io/library/hello-world\n" +
...     "975b84d108f1: Pulling image (latest) from docker.io/library/hello-world, endpoint: https://registry-1.docker.io/v1/\n" +
...     "975b84d108f1: Pulling dependent layers\n" +
...     "3f12c794407e: Pulling metadata\n" +
...     "3f12c794407e: Pulling fs layer\n" +
...     "3f12c794407e: Download complete\n" +
...     "975b84d108f1: Pulling metadata\n" +
...     "975b84d108f1: Pulling fs layer\n" +
...     "975b84d108f1: Download complete\n" +
...     "975b84d108f1: Download complete\n" +
...     "Status: Downloaded newer image for hello-world:latest\n" +
...     "docker.io/library/hello-world: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.\n"
... substring string = "Pulling from library/hello-world"
... expected the 'library/' prefix to be automatically assumed


----------------------------------------------------------------------
FAIL: docker_cli_pull_test.go:69: DockerHubPullSuite.TestPullFromCentralRegistryImplicitRefParts

docker_cli_pull_test.go:83:
    c.Assert(out, checker.Contains, "Image is up to date for hello-world:latest")
... obtained string = "" +
...     "Using default tag: latest\n" +
...     "Pulling repository docker.io/library/hello-world\n" +
...     "975b84d108f1: Pulling image (latest) from docker.io/library/hello-world\n" +
...     "975b84d108f1: Pulling image (latest) from docker.io/library/hello-world, endpoint: https://registry-1.docker.io/v1/\n" +
...     "975b84d108f1: Pulling dependent layers\n" +
...     "3f12c794407e: Pulling metadata\n" +
...     "3f12c794407e: Pulling fs layer\n" +
...     "3f12c794407e: Download complete\n" +
...     "975b84d108f1: Pulling metadata\n" +
...     "975b84d108f1: Pulling fs layer\n" +
...     "975b84d108f1: Download complete\n" +
...     "975b84d108f1: Download complete\n" +
...     "Status: Downloaded newer image for hello-world:latest\n" +
...     "docker.io/library/hello-world: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.\n"
... substring string = "Image is up to date for hello-world:latest"

OOPS: 0 passed, 2 FAILED
--- FAIL: Test (211.07s)
FAIL
coverage: 21.4% of statements
exit status 1
FAIL	github.com/docker/docker/integration-cli	211.438s
---> Making bundle: .integration-daemon-stop (in bundles/1.10.0-dev/test-integration-cli)
+++++ cat bundles/1.10.0-dev/test-integration-cli/docker.pid
++++ kill 5336
make: *** [test-integration-cli]
```

`docker version`:
```Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   e9f7241-dirty
 Built:        Wed Dec 30 08:12:05 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   e9f7241-dirty
 Built:        Wed Dec 30 08:12:05 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 5
Images: 2
Server Version: 1.10.0-dev
Storage Driver: devicemapper
 Pool Name: mydocker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 2.746 GB
 Data Space Total: 21.45 GB
 Data Space Available: 18.7 GB
 Metadata Space Used: 1.798 MB
 Metadata Space Total: 54.53 MB
 Metadata Space Available: 52.73 MB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.64 GiB
Name: localhost.localdomain
ID: 3QIL:6NMH:UT3P:7VAU:YJRR:QI25:KYFZ:BBPA:YJSJ:PTNZ:GFZS:YYCM
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

`uname -a`

```
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

How reproducible:
Git clone the upstream, running the command:

```
TESTFLAGS='-check.f DockerHubPullSuite.TestPullFromCentralRegistry' make test-integration-cli
```

**Comment by vdemeester** [comment] 2016-01-07 11:21
@zhanghuanzhong Cannot reproduce on master

```
TESTFLAGS='-check.f DockerHubPullSuite.TestPullFromCentralRegistry' make test-integration-cli
# […]
---> Making bundle: .ensure-httpserver (in bundles/1.10.0-dev/test-integration-cli)
---> Making bundle: .ensure-syscall-test (in bundles/1.10.0-dev/test-integration-cli)
+ go test -check.f DockerHubPullSuite.TestPullFromCentralRegistry -test.timeout=120m -check.v github.com/docker/docker/integration-cli
INFO: Testing against a local daemon
PASS: docker_cli_pull_test.go:16: DockerHubPullSuite.TestPullFromCentralRegistry        3.587s
PASS: docker_cli_pull_test.go:74: DockerHubPullSuite.TestPullFromCentralRegistryImplicitRefParts        20.471s
OK: 2 passed
PASS
coverage: 20.1% of statements
ok      github.com/docker/docker/integration-cli        27.504s
```

**Comment by thaJeztah** [comment] 2016-01-07 11:47
I think the `this image was pulled from a legacy registry` could be an issue with Docker Hub, if you're still able to reproduce that (i.e. by running `docker pull hello-world`), could you report that to support@docker.com ?

Note that (I think) this could also be caused by a proxy-server that removes some headers, causing the registry to fallback to the old protocol

**Comment by unclejack** [comment] 2016-01-24 11:19
`make test-integration-cli` is currently passing all tests for me and it's also passing on a multitude of pull requests which are tested on the CI.

Please keep in mind we don't provide support for running the tests. There are some aspects to be taken into account when running the tests:
1. install all system updates have been installed and that the system has been rebooted afterwards
2. check to make sure requirements are met using the check-config.sh script from contrib
3. make sure you're on a system which meets the requirements (CentOS 6 / RHEL 6 aren't supported)
4. make sure you're using at least kernel 3.10 or newer
5. in case of failures, try to run the tests on another machine with a different OS

Should you really want to discuss hacking on Docker, you're welcome to join #docker-dev on Freenode.

I'll close this now as there are no known issue at this time.

**Closed by unclejack** 2016-01-24 11:19 UTC
