### ISSUE TITLE
composition of dockerfiles

### ISSUE THREAD

**Issue by samsabed** [docker/docker#14124] opened 2015-06-23 15:04 UTC
It would be good to have composition of dockerfiles, something like an include keyword that would act like a sh "source", importing an image's files and it's configuration, collapsed to _1_ layer

e.g
```
#jboss.dockerfile
FROM scratch
ADD jboss /opt/
ADD secret /secret
VOLUME /logs
ONBUILD RUN git clone https://username:password@git/repository.git /src/
ONBUILD RUN something /secret # build it commands
ONBUILD RUN rm -rf /src/
ONBUILD RUN rm -rf /secret
```

`docker build -t include:jboss -f $jboss.dir/jboss.dockerfile  $jboss.dir `

```
# fronendFoo.dockerfile
FROM centos
INCLUDE include:jboss # <--- this is a tag
INCLUDE include:jdbc
ADD file /files
RUN ...
CMD ...
```

` docker build -f $frontendFoo/fronendFoo.dockerfile $frontendFoo`

The onbuild is run in the "outside" image (e.g. fronendFoo.dockerfile) 

something like this would 
a) reduce the complexity of ignore files and project layout, in the project{a,b,c} + common pattern, each included image is created in it's own context
b) enable some secret(s) and temp file erasing, they are not present in the final image
c) keep the history of how the final image was created, by having the included image's name and ID is in the history
d) layer reducing, everything in the included image is reduced to one layer
e) cache friendly and will download the sub images from a registry 

It's probably been discussed before but i can't find the issue, anyway here is poc PR to kick the proverbial tyres

**Comment by duglin** [comment] 2015-06-23 15:52
https://github.com/docker/docker/pull/12749

-Doug

**Comment by tiborvass** [comment] 2015-06-26 00:56
Closing for it is a duplicate of #735

**Closed by tiborvass** 2015-06-26 00:56 UTC
