### ISSUE TITLE
Folders prefixed with dot (.) not persisted in images built on Windows Server 2016 Technical Preview 3

### ISSUE THREAD

**Issue by follesoe** [docker/docker#17755] opened 2015-11-06 12:28 UTC
**Description of problem**:
Folders with a dot prefix (i.e. ``.dnx``) are not persisted in image when building Dockerfile on Windows Server 2016 Technical Preview 3.

`docker version`:
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   4376380
 Built:        Wed Aug 19 14:59:24 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   4376380
 Built:        Wed Aug 19 14:59:24 UTC 2015
 OS/Arch:      windows/amd64

`docker info`:
Containers: 1
Images: 2
Storage Driver: windowsfilter
 Windows:
Execution Driver: Windows 1854 1.9.0-dev 4376380
Logging Driver: json-file
Kernel Version: 10.0 10514 (10514.0.amd64fre.th2_release.150808-1529)
Operating System: Windows Server 2016 Technical Preview 3
CPUs: 1
Total Memory: 3.5 GiB
Name: BEKKDOCKERWIN06
ID: RTMM:PSDA:2II4:XMCU:XHNX:L3WR:TMAK:JQQW:TS3P:3WWU:WT4H:MIQM
Debug mode (server): true
File Descriptors: -1
Goroutines: 14
System Time: 2015-11-06T12:06:47.6047592Z
EventsListeners: 0
Init SHA1:
Init Path: C:\Windows\System32\docker.exe
Docker Root Dir: C:\ProgramData\Docker

`systeminfo`:
Host Name:                 BEKKDOCKERWIN06
OS Name:                   Microsoft Windows Server 2016 Technical Preview 3
OS Version:                10.0.10514 N/A Build 10514
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:
Product ID:                00133-32500-01425-AA253
Original Install Date:     11/5/2015, 9:25:01 PM
System Boot Time:          11/5/2015, 9:25:12 PM
System Manufacturer:       Microsoft Corporation
System Model:              Virtual Machine
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 45 Stepping 7 GenuineIntel ~2195 Mhz
BIOS Version:              American Megatrends Inc. 090006 , 5/23/2012
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC) Coordinated Universal Time
Total Physical Memory:     3,584 MB
Available Physical Memory: 2,687 MB
Virtual Memory: Max Size:  4,479 MB
Virtual Memory: Available: 3,556 MB
Virtual Memory: In Use:    923 MB
Page File Location(s):     D:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\BEKKDOCKERWIN06
Hotfix(s):                 1 Hotfix(s) Installed.
                           [01]: KB3081439
Network Card(s):           2 NIC(s) Installed.
                           [01]: Microsoft Hyper-V Network Adapter
                                 Connection Name: Ethernet 3
                                 DHCP Enabled:    Yes
                                 DHCP Server:     168.63.129.16
                                 IP address(es)
                                 [01]: 10.4.0.4
                                 [02]: fe80::7d11:b0d4:d6cb:2bfb
                           [02]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Virtual Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.16.0.1
                                 [02]: fe80::31a8:8ca8:cfe2:4b33
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Environment details:**
Windows Server 2016 Technical Preview 3 running on Windows Azure

**How reproducible:**
Consistently reproducible on a Windows Server 2016 Technical Preview 3 machine running in Azure (not tested when running in a local VM).

**Steps to Reproduce:**
1. `docker run -it windowsservercore cmd`
2. `cd c:\`
3. `mkdir .foo`
4. `mkdir foo`
5. `exit`
6. `docker commit CONTAINERID bugimage`
7. `docker run -it bugimage cmd`
6. `dir c:\`

**Actual Results:**
<pre>
C:\Windows\system32> dir c:\
 Volume in drive C has no label.
 Volume Serial Number is 3A34-B64A

 Directory of c:\

11/06/2015  12:22 PM                 0 bootmgr
11/06/2015  12:22 PM                 1 BOOTNXT
<b>11/06/2015  12:22 PM    <DIR>          foo</b>
08/09/2015  06:39 AM    <DIR>          PerfLogs
11/06/2015  12:23 PM    <DIR>          Program Files
08/09/2015  08:00 AM    <DIR>          Program Files (x86)
11/06/2015  12:23 PM    <DIR>          ProgramData
08/14/2015  03:47 PM    <DIR>          Users
11/06/2015  12:22 PM    <DIR>          Windows
               2 File(s)              1 bytes
               7 Dir(s)  21,224,800,256 bytes free
</pre>

**Expected Results:**
<pre>
C:\Windows\system32> dir c:\
 Volume in drive C has no label.
 Volume Serial Number is 3A34-B64A

 Directory of c:\

11/06/2015  12:22 PM                 0 bootmgr
11/06/2015  12:22 PM                 1 BOOTNXT
<b>11/06/2015  12:22 PM    <DIR>          foo</b>
<b>11/06/2015  12:22 PM    <DIR>          .foo</b>
08/09/2015  06:39 AM    <DIR>          PerfLogs
11/06/2015  12:23 PM    <DIR>          Program Files
08/09/2015  08:00 AM    <DIR>          Program Files (x86)
11/06/2015  12:23 PM    <DIR>          ProgramData
08/14/2015  03:47 PM    <DIR>          Users
11/06/2015  12:22 PM    <DIR>          Windows
               2 File(s)              1 bytes
               8 Dir(s)  21,224,800,256 bytes free
</pre>

**Additional info:**
The `.foo` folder is missing from the image. I discovered this bug while trying to build a ASP.NET vNext image for Windows Server Core, which installs dnvm and dnx. By default dnvm installs to USERPROFILE\.dnx folder, so when building the image dnvm and dnx is installed, but when running the image in a container, the `.dnx`-folder is missing.

**Comment by thaJeztah** [comment] 2015-11-11 14:31
ping @jhowardmsft any ideas?

**Comment by jhowardmsft** [comment] 2015-11-11 18:28
Can you verify if this still occurs on the latest build of docker? A lot has changed since August.  @swernli

**Comment by jhowardmsft** [comment] 2015-11-11 19:38
Actually, verified it still occurs. @swernli is going to take a look.

**Comment by swernli** [comment] 2015-11-11 22:09
Turns out this is a Windows bug... which means we will be stuck with it until either a servicing event (if it gets approved) or the next preview release :(.

**Comment by jhowardmsft** [comment] 2015-11-12 01:44
@thaJeztah We should probably tag it TP5....

**Comment by thaJeztah** [comment] 2015-11-12 09:31
@jhowardmsft is there a target date for TP5? (ballpark)

**Comment by jhowardmsft** [comment] 2015-11-12 14:35
Pah, absolutely no idea. Some time next year is really the closest I could say. Sorry!

**Comment by thaJeztah** [comment] 2015-11-12 16:15
np, just that it's used for sorting the milestones (which otherwise get a bit messy)

**Comment by jhowardmsft** [comment] 2016-04-20 21:58
Verified resolved in TP5. Closing.

```
PS E:\go\src\github.com\docker\docker> docker run john cmd /s /c dir \
 Volume in drive C has no label.
 Volume Serial Number is 1440-27FA

 Directory of C:\

04/20/2016  02:55 PM    <DIR>          .foo
04/20/2016  02:55 PM    <DIR>          foo
03/25/2016  05:28 AM    <DIR>          inetpub
03/25/2016  04:22 AM    <DIR>          PerfLogs
04/20/2016  02:57 PM    <DIR>          Program Files
03/25/2016  04:22 AM    <DIR>          Program Files (x86)
04/20/2016  02:57 PM    <DIR>          Users
04/20/2016  02:57 PM    <DIR>          Windows
               0 File(s)              0 bytes
               8 Dir(s)  21,242,904,576 bytes free
PS E:\go\src\github.com\docker\docker>
```

**Closed by jhowardmsft** 2016-04-20 21:58 UTC
Labels: group/windows, kind/bug

**Comment by axetroy** [comment] 2018-06-14 17:20
any update for this?

I still got this problem in MacOS with latest `Docker CE`

**Comment by thaJeztah** [comment] 2018-06-14 17:51
@axetroy this issue was specific to Docker on Windows; if you have exact steps to reproduce, please open a new ticket with details

**Comment by RichardSilveira** [comment] 2019-06-24 23:16
Any news on it?

**Comment by thaJeztah** [comment] 2019-06-24 23:19
@RichardSilveira read my comment above yours
