### ISSUE TITLE
Unable to delete files in container

### ISSUE THREAD

**Issue by vivekkodira1** [docker/docker#31445] opened 2017-03-01 10:07 UTC
The issue is also raised as a question on stackoverflow (http://stackoverflow.com/questions/42527413/docker-is-unable-to-delete-a-file-when-building-images)

**Steps to reproduce the issue:**
1. Bring up container
2. Navigate to folder
3. Try deleting the file

**Describe the results you received:**
No error is displayed. However listing contents of the folder after this command displays:

```
# ls -lrt
ls: cannot access plugins.7z: No such file or directory
total 0
??????????? ? ?          ?          ?            ? plugins.7z
```

**Describe the results you expected:**
The file should not be present anymore.

**Additional information you deem important (e.g. issue happens only occasionally):**
1. The issue occurs only in 1.13. The same Dockerfile and commands worked in 1.10
2. The issue occurs for all files/folders of this directory
3. The user performing the operation is root.

**Output of `docker version`:**

```
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: qualitest-instance
ID: F3ES:ONWV:FPJI:OHVQ:ZV4G:KPDO:KPX2:ZS64:66QY:Z6XS:V73E:XE66
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vivekkodira1** [comment] 2017-03-01 11:33
An update: Noticed that the change log for 1.13 says 

> On Linux distributions where devicemapper was the default storage driver, the overlay2, or overlay is now used by default (if the kernel supports it)."

So I tried putting back devicemapper and it is now working as expected.

**Comment by vivekkodira1** [comment] 2017-03-01 11:35
Leaving the issue open because I've not completely understood why it worked :). If possible, please add a note. Am also going through the storage driver documentation to try and figure it out myself.

**Comment by thaJeztah** [comment] 2017-03-01 14:06
Thanks for reporting; this is a duplicate of https://github.com/docker/docker/issues/27358
This problem occurs if `d_type` is not available, due to the backing xfs filesystem not being formatted with `ftype=1`. See https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html for more information.

For docker 1.13 a warning is logged in the daemon logs (see https://github.com/docker/docker/pull/27433), but since this may be missed, I recently opened a pull request to show this warning on the CLI output as well (https://github.com/docker/docker/pull/31290).

Given that the device mapper driver (when using loopback devices) is notoriously slow, you could consider re-formating the drive, so that overlay(2) can be used.

I'll close this issue, because this is a duplicate of https://github.com/docker/docker/issues/27358, but feel free to continue the discussion.

**Closed by thaJeztah** 2017-03-01 14:06 UTC
Labels: area/builder, version/1.13
