### ISSUE TITLE
Assigning public IP to application running in docker container 

### ISSUE THREAD

**Issue by jobins1** [docker/docker#19818] opened 2016-01-28 23:47 UTC
I have a docker container running on Linux server. I can get the response by a curl to the internal IP as below.
curl http://172.17.0.2:8080/greeting?name=jo
 
This Linux server's public IP is 199.231.191.106. How can I access the docker application by using this public IP?

**Comment by thaJeztah** [comment] 2016-01-29 00:07
You need to publish the container's port to the host, e.g. `docker run -d -p 8080:80 nginx` will publish the container's port 80 to port 8080 on the host.

However, the GitHub issue tracker is not a general support forum, but meant for reporting bugs and feature requests. For other questions, please use;

1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.
4) StackOverflow

I'm going to close this issue because this is not a bug, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-01-29 00:07 UTC
