### ISSUE TITLE
is --network-alias missing for services

### ISSUE THREAD

**Issue by fabio-barile** [docker/docker#31652] opened 2017-03-08 14:44 UTC
Hi 

I want to create a stackfile for all my services.
I have not been able to find how to define  network-aliases for my services.
Is the parameter '--network-alias' is missing for services ? 

Regards

**Comment by thaJeztah** [comment] 2017-03-08 14:47
Correct, not all options that are available for `docker run` are available to services yet. We keep track of missing options, through https://github.com/docker/docker/issues/25303, and there's an issue tracking this specific feature here; https://github.com/docker/docker/issues/24787

I'll close this issue because this is a duplicate of https://github.com/docker/docker/issues/24787, you can subscribe to that issue to stay informed on updates

**Closed by thaJeztah** 2017-03-08 14:47 UTC
