### ISSUE TITLE
Unable to start/stop already created service

### ISSUE THREAD

**Issue by aleksejlopasov** [docker/docker#25212] opened 2016-07-29 08:39 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        
 OS/Arch:      linux/amd64
```
Hi, although I don't think it's really an issue, but I am unable to restart already created service

I have one swarm-master and a couple of swarm-worker nodes. I've created a service with 'docker service create' command and it was deployed to one of the nodes as expected. But this task is a CentOS container with php script running inside. It has finished working in several hours and the container stopped working with exit status 0 (as expected).
What am I going to do if I want to start this task again? There is no any command like 'docker service (or task) start/stop/restart' or smth. If I try to print 'docker service create --name <the same name>', the command fails with error (as expected). After service finished his tasks, it still stays created and the container still stays at worker-node.
I'm need to run the same tasks every day/hour/minute, but how can I do it properly? Is there any way to remove service automatically after it's finished or start/restart it?
Is docker swarm a good solution for running apps (that are expected to exit) regularly (e.g. Linux crond).

**Comment by thaJeztah** [comment] 2016-07-29 11:47
You can set a restart policy on the service so that docker automatically restarts it when the service exits.

Swarm mode (services) currently doesn't have a concept of "batch" services, however, you could set a cronjob on the host that does a `docker service update` and changes something in the service (which forces the service to be redeployed), or do the same, but with a container (not a service).

theres an existing feature request for "batch" / "cron" services https://github.com/docker/docker/issues/23880, so please subscribe to that issue to keep informed on updates

I'm closing this issue, as it's a question, not a bug

**Closed by thaJeztah** 2016-07-29 11:47 UTC
Labels: version/1.12
