### ISSUE TITLE
Unintuitive / Buggy behaviour of internal DNS server.

### ISSUE THREAD

**Issue by TimWolla** [docker/docker#25730] opened 2016-08-15 21:25 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.1-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:41:09 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:41:09 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 79
Server Version: 1.12.1-rc1
Storage Driver: zfs
 Zpool: scratch
 Zpool Health: ONLINE
 Parent Dataset: scratch/docker
 Space Used By Parent: 7176159232
 Space Available: 29393547264
 Parent Quota: no
 Compression: on
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.773 GiB
Name: *snip*
ID: *snip*
Docker Root Dir: /scratch/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
My workstation

**Steps to reproduce the issue:**
1. `docker network create test1`
2. `docker network create test2`
3. `docker network create test3`
4. `docker run -it --rm --net=test1 --name=master dig bash` (the `dig` image is a Debian with `dnsutils` installed)
5. `docker network connect test2 master`
6. `docker network connect test3 master`
7. `docker run -it --rm --net=test2 --name=slave --network-alias=slave dig bash`
8. `docker run -it --rm --net=test3 --name=slave2 --network-alias=slave dig bash`
9. Now run the following commands inside the `master` container:
10. `ip a s` to check that the container is properly connected to every network
11. `dig A slave`

**Describe the results you received:**
```
root@09edf10b18fc:/# ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
118: eth0@if119: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:2/64 scope link 
       valid_lft forever preferred_lft forever
120: eth1@if121: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:15:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.21.0.2/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe15:2/64 scope link 
       valid_lft forever preferred_lft forever
122: eth2@if123: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:14:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.2/16 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe14:2/64 scope link 
       valid_lft forever preferred_lft forever
root@09edf10b18fc:/# dig A slave

; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> A slave
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27259
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;slave.				IN	A

;; ANSWER SECTION:
slave.			600	IN	A	172.21.0.3

;; Query time: 1 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Mon Aug 15 21:15:07 UTC 2016
;; MSG SIZE  rcvd: 44
```

Notice that only a single container is returned for the lookup to `slave`. If you stop that container the `slave` from the other network appears as the DNS result. If both slaves are connected to the same network both are returned.

**Describe the results you expected:**
I expected to receive two ip addresses (`172.21.0.3` and `172.20.0.3`) as the result to my DNS query.

**Additional information you deem important (e.g. issue happens only occasionally):**
n/a

**Comment by thaJeztah** [comment] 2016-08-15 23:25
ping @sanimej

**Comment by sanimej** [comment] 2016-08-16 02:06
@TimWolla This is not a bug. Its the intended behavior. Docker service discovery is network scoped; ie: services are discoverable within the network a container is connected to. When you have a container connected to multiple networks and a given service name exists on more than one network its not deterministic which IP will be returned.

The intended use of `network-alias` is to support a simple load balancing in pre 1.12 releases which didn't have the swarm service abstraction. For ex:

`docker run -d --net ov --name nginx1 --network-alias web nginx`
`docker run -d --net ov --name nginx3 --network-alias web nginx`
`docker run -d --net ov --name nginx3 --network-alias web nginx`

When a client container in `ov` network does a DNS lookup for the service `web` IPs of all the 3 nginx containers will be returned.

**Comment by icecrime** [comment] 2016-08-16 15:36
Tentatively closing this: let me know if it needs reopening.

**Closed by icecrime** 2016-08-16 15:36 UTC
Labels: group/networking, version/1.12
