### ISSUE TITLE
docker plugin enable cannot find the plugin's socket

### ISSUE THREAD

**Issue by rootsongjc** [docker/docker#31723] opened 2017-03-10 08:29 UTC
**Create a volume using docker plugin but no socket found**

1. I created a `sshfs` volume plugin flowing the docker official doc [developing a plugin](https://github.com/docker/docker/blob/17.03.x/docs/extend/index.md#developing-a-plugin)
2. Create a volume
```
docker volume create -d sshfs --name sshvolume -o sshcmd=1.2.3.4:/remote -o password=password
```
3. Got an error
```
Error response from daemon: create sshvolume: Post http://%2Frun%2Fdocker%2Fplugins%2F8f7b8f931b38a4ef53d0e4f8d738e26e8f10ef8bd26c8244f4b8dcc7276b685f%2Fsshfs.sock/VolumeDriver.Create: dial unix /run/docker/plugins/8f7b8f931b38a4ef53d0e4f8d738e26e8f10ef8bd26c8244f4b8dcc7276b685f/sshfs.sock: connect: no such file or directory
```
Directory `/run/docker/plugins/8f7b8f931b38a4ef53d0e4f8d738e26e8f10ef8bd26c8244f4b8dcc7276b685f` is empty.

`sshfs` plugin *config.json*
```
{
        "description": "sshFS plugin for Docker",
            "documentation": "https://docs.docker.com/engine/extend/plugins/",
                "entrypoint": ["/docker-volume-sshfs"],
                "network": {
                               "type": "host"                          
                },
                "interface" : {
                               "types": ["docker.volumedriver/1.0"],
                                          "socket": "sshfs.sock"           
                },
                "linux": {
                            "capabilities": ["CAP_SYS_ADMIN"]               
                }
}
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 44
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: flocker local
 Network: bridge contiv/v2plugin:latest host macvlan null overlay
Swarm: active
 NodeID: n2tuxvoib9yaz2uqj193u5kkd
 Is Manager: true
 ClusterID: 41ypi3l8xmpyah3p55zm0tiz0
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.20.0.113
 Manager Addresses:
  172.20.0.113:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 125.6 GiB
Name: sz-pg-oam-docker-test-001.tendcloud.com
ID: E3EW:5GDB:KB2E:JANJ:2HCQ:TROP:W3H5:ENQA:23FH:RJ5T:UX5T:O7M2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 sz-pg-oam-docker-hub-001.tendcloud.com
 127.0.0.0/8
Live Restore Enabled: false
```

**Physical machine**

**Comment by rootsongjc** [comment] 2017-03-14 11:16
`docker plugin enable` will find the plugin's socket at 
```
client, err := plugins.NewClientWithTimeout("unix://"+sockAddr, nil, c.timeoutInSecs)
```
Should the socket created when I create a plugin manually? However how the plugin know its ID before I enable it?

**Comment by anusha-ragunathan** [comment] 2017-03-14 17:21
The plugin should create the socket under `/var/run/docker`. It's clearly doc-ed in https://github.com/docker/docker/blob/master/docs/extend/index.md#developing-a-plugin

`Note: The /run/docker/plugins directory is mandatory inside of the plugin's filesystem for docker to communicate with the plugin.`

The plugin ID is created during create/install and enable happens after that.

**Comment by anusha-ragunathan** [comment] 2017-03-14 17:22
Closing the issue, since this is a question more than an issue and the question has been answered.

**Closed by anusha-ragunathan** 2017-03-14 17:22 UTC
Labels: area/plugins, version/1.13

**Comment by rootsongjc** [comment] 2017-03-15 02:08
@anusha-ragunathan I have read the doc and developing the plugin as the instructions but no socket appear in `/run/docker/plugin` directory.

**Comment by anusha-ragunathan** [comment] 2017-03-15 15:27
@rootsongjc : Are you creating a socket like so? https://github.com/vieux/docker-volume-sshfs/blob/b051239b05a9880fbb32742e2ed2c24e3ec998f0/main.go#L268

**Comment by savagecm** [comment] 2017-07-27 02:51
Hi @anusha-ragunathan 
I met the same issue.
`const socketAddress = "/run/docker/plugins/zmq.sock"

var logLevels = map[string]logrus.Level{
        "debug": logrus.DebugLevel,
        "info":  logrus.InfoLevel,
        "warn":  logrus.WarnLevel,
        "error": logrus.ErrorLevel,
}

func main() {
        levelVal := os.Getenv("LOG_LEVEL")
        if levelVal == "" {
                levelVal = "info"
        }
        if level, exists := logLevels[levelVal]; exists {
                logrus.SetLevel(level)
        } else {
                fmt.Fprintln(os.Stderr, "invalid log level: ", levelVal)
                os.Exit(1)
        }

        h := sdk.NewHandler(`{"Implements": ["LoggingDriver"]}`)
        zmgloggerr.Handlers(&h, zmgloggerr.NewDriver())
        if err := h.ServeUnix(socketAddress, 0); err != nil {
                panic(err)
        }
`
when I try to enable the plugin. I got the folloing output:
`root@max-VirtualBox:/run/docker/plugins# docker plugin enable zmq_002
Error response from daemon: dial unix /run/docker/plugins/7148073f6d0c859d597e90df1d2e59bf7f493f26700cb40ae9a3bc9c3f487c1f/zmq.sock: connect: no such file or directory
root@max-VirtualBox:/run/docker/plugins# ls
root@max-VirtualBox:/run/docker/plugins#
`
it seems there is no zmq.sock.

BTW: I am trying to create a log plugin

**Comment by savagecm** [comment] 2017-07-27 03:01
my machine:
```
root@max-VirtualBox:/run/docker/plugins# docker info
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 8
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-28-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990MiB
Name: max-VirtualBox
ID: YBHV:5TA4:EM7Y:HXSM:ZLSC:HDGO:ML2W:BNPV:JEBT:ZOPL:HTDD:ZE3H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
root@max-VirtualBox:/run/docker/plugins# docker --version
Docker version 17.06.0-ce, build 02c1d87
```

**Comment by govint** [comment] 2017-08-17 08:46
The socket is created by the plugin and once the plugin has started to run does it need to first create the socket before performing any other task as part of its startup?
It seems like that's expected (as part of plugin install), manager_linux.go:pluginPostStart() does a net.Dial() on what it _knows_ should be the plugin socket. But its not guaranteed that the plugin has as yet created the socket after it was started. Is there a reason why its expected that the plugin _must_ create the socket early enough so this check passes?

**Comment by grunenwflorian** [comment] 2017-08-24 13:55
Hi @anusha-ragunathan and @savagecm,

I think I found the reason why it's not working. 
Even if you follow the documentation https://github.com/moby/moby/blob/17.03.x/docs/extend/index.md#developing-a-plugin
It cannot work because the plugin is running inside a container so the daemon won't be able to find your socket unless you bind it (mount in the config.json).

**Comment by greenpau** [comment] 2018-07-15 14:21
> The plugin should create the socket under /var/run/docker. It's clearly doc-ed in

@anusha-ragunathan , imho, it is not as clear, because one may think that the `interface.socket` must be created under `/` (root) inside the container.

For example, provided `config.json` has:

```
    "interface": {
        "socket": "plugin.sock",
```

Once a user tries enabling the plugin, the user gets the following error:

```
Error response from daemon: dial unix /run/docker/plugins/1a3f916a1f6c5efa68cf78627cd8e353c7aae2910437d74f6f7f2d27fb54735c/plugin.sock: connect: no such file or directory
```

Is it reasonable to assume that Docker tries looking for the socket file inside the container?

**Comment by gmelikov** [comment] 2018-09-28 08:57
This may be helpful to someone - if you debug your brand new plugin, and you see such errors (`connect: no such file or directory`, or `connection refused`) - check for obsolete .sock plugin files and restart docker, otherwise it won't find your .sock file new location.

**Comment by zhwill** [comment] 2018-11-22 09:45
i have the same problem:
[root@cephnode1 ~]# docker plugin install rexray/ebs EBS_ACCESSKEY=access_key EBS_SECRETKEY=secret_key
Plugin "rexray/ebs" is requesting the following privileges:
 - network: [host]
 - mount: [/dev]
 - allow-all-devices: [true]
 - capabilities: [CAP_SYS_ADMIN]
Do you grant the above permissions? [y/N] y
latest: Pulling from rexray/ebs
d726edfb6c8d: Download complete 
Digest: sha256:b5b0680b6dd53a4c61bac21942738a69edfe3d6a6516acc13045d257889c9213
Status: Downloaded newer image for rexray/ebs:latest
Error response from daemon: dial unix /run/docker/plugins/432f4b002c54601215fbcc719efb8bae4e5a9c8a9c172e4a8709414ebb42cf23/rexray.sock: connect: no such file or directory

**Comment by fentas** [comment] 2019-03-26 10:30
Having the same issue https://github.com/fentas/docker-volume-davfs/issues/3
Does anyone know how to ensure that sock is created before docker is looking for it?

**Comment by eleaner** [comment] 2019-04-07 18:10
@fentas 
Did you figure out what's wrong?
Having the same issue

**Comment by naresh-chilukurthi** [comment] 2020-03-05 11:15
@eleaner did you find anything about the issue?

**Comment by fentas** [comment] 2020-03-24 21:32
@eleaner nope never figured it out. Sometimes it works sometimes it doesn't.. :/ :man_shrugging:

**Comment by 0x9060** [comment] 2020-04-30 03:20
Same problem here. Totally fresh VM and Docker install. Simply trying to install an AuthZ plugin from Docker Hub:

```
$ printf('y') | docker plugin install openpolicyagent/opa-docker-authz-v2:0.6
Plugin "openpolicyagent/opa-docker-authz-v2:0.6" is requesting the following privileges:
 - mount: [/etc/docker]
Do you grant the above permissions? [y/N] y
0.6: Pulling from openpolicyagent/opa-docker-authz-v2
19ad1cb286ca: Download complete 
Digest: sha256:5f32ec04f92a53434a94a5db10279f3d513b00d213e7878fee46a6e1b632701a
Status: Downloaded newer image for openpolicyagent/opa-docker-authz-v2:0.6
Error response from daemon: dial unix /run/docker/plugins/277fc1ca43069a4c20ff20b975ad1df580f6f9364b51f191cb8f28b4969dc77b/opa-docker-authz.sock: connect: no such file or directory
```

In case it's relevant: I am running Docker locally, with the server requiring TLS. I have the client and CA certificates appropriately placed, so I am running docker without using `sudo`. I have moved the `Docker Root Dir` to a separate partition. I am also enforcing `userns-remap`ing for user management, with strict file permissions locally. I suspect one of these settings may be the root cause. Here are my Docker details:

<details>
<summary> /etc/docker/daemon.json </summary>
<pre>
$ cat /etc/docker/daemon.json 
{
  "icc": false,
  "userns-remap": "default",
  "log-driver": "syslog",
  "live-restore": true,
  "userland-proxy": false,
  "no-new-privileges": true,
  
  "storage-driver": "overlay2",
  "storage-opts": [],
  "data-root": "/docker",

  "tls": true,
  "tlsverify": true,
  "tlscacert": "/certs/docker/ca.pem",
  "tlscert": "/certs/docker/server-cert.pem",
  "tlskey": "/certs/docker/server-key.pem"
}
</pre>
</details>

<details>
<summary> Docker Info </summary>
<pre>
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: syslog
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
  userns
 Kernel Version: 4.19.0-8-cloud-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.857GiB
 Docker Root Dir: /docker/165536.165536
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

WARNING: No swap limit support
</pre>
</details>


<details>
<summary> Docker Version </summary>
<pre>
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

</pre>
</details>

  [1]: https://hub.docker.com/r/openpolicyagent/opa-docker-authz-v2
