### ISSUE TITLE
Performance : tag and push

### ISSUE THREAD

**Issue by sylvainmouquet** [docker/docker#31778] opened 2017-03-13 09:45 UTC
Docker allows to tag and push only one image. 
For limiting the interactions between the server and the repository it's possible to add the possibility to push an image with multiple tag in one time ?

**Comment by thaJeztah** [comment] 2017-03-13 09:49
Thanks for opening, this is a duplicate of https://github.com/docker/docker/issues/7336, please subscribe to that issue to stay informed on updates

**Closed by thaJeztah** 2017-03-13 09:49 UTC
Labels: area/distribution, kind/enhancement
