### ISSUE TITLE
Files added or copied from subpaths in the Dockerfile can invalidate the cache if files in other parts of the same subtree are themselves modified

### ISSUE THREAD

**Issue by hookenz** [docker/docker#12421] opened 2015-04-15 23:40 UTC
Using either COPY or ADD in this form

COPY myfile /data/
or 
ADD myfile /data/

And then building it and pushing it to a remote repository, results in an entirely new image every single time.
I may not have noticed except for the fact that myfile is in the 100+MB range and the repository is remote.

myfile has not changed at all.  When is the hash calculated, and what metadata also affects whether it's new?  I don't have noatime on my ext4 volume containing /var/lib/docker

I can also verify that 
    find /var/lib/docker | grep myfile 

produces about 30 results.  So much for copying changes. 

And if I simply do a docker build each time, each time is a new result.  No changes to the Dockerfile whatsoever.  

 Is this a bug?

The version of docker I have is on Ubuntu 14.04.  Docker version 1.5.0, build a8a31ef
In case it's also relevant I have VOLUME /data in the dockerfile as well.

**Comment by hookenz** [comment] 2015-04-16 00:07
I have narrowed down the issue.  Basically I have build process that re-recreates some files under the relative directory named "data/profiles"

When any file is changed, time, date etc beneath data/profiles, it'll add a whole new coreos_production file etc.

From the outside, it looks to me as though docker build is checking the data directory mtime and deciding that it's changed so building it all again.  When in fact it should be examining data/profiles and data/images/607.0.0 separately since they are separate COPY operations. 

I think I can work around it by ensuring that profiles or data are not beneath the relative directory data.

This dockerfile reproduces it.

FROM ubuntu:14.04
COPY data/profiles/ /data/profiles
COPY data/images/607.0.0/coreos_production_pxe_image.cpio.gz data/images/607.0.0/
VOLUME /data

The problem will show up like follows

First run:

docker build -t test .
Sending build context to Docker daemon 129.8 MB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:14.04
 ---> b39b81afc8ca
Step 1 : COPY data/profiles/ /data/profiles
 ---> ae6eb10be027
Step 2 : COPY data/images/607.0.0/coreos_production_pxe_image.cpio.gz data/images/607.0.0/
 ---> 32d2b79fde7a
Step 3 : VOLUME /data
 ---> f5d493568149
Successfully built f5d493568149

Second run:

docker build -t hello .
Sending build context to Docker daemon 129.8 MB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:14.04
 ---> b39b81afc8ca
Step 1 : COPY data/profiles/ /data/profiles
 ---> Using cache
 ---> ae6eb10be027
Step 2 : COPY data/images/607.0.0/coreos_production_pxe_image.cpio.gz data/images/607.0.0/
 ---> Using cache
 ---> e9dc0eb1f50c
Step 3 : VOLUME /data
 ---> Using cache
 ---> ca646b74a76a
Successfully built ca646b74a76a

Now try this:
   echo hello > data/profiles/hello
docker build -t hello .
Sending build context to Docker daemon 129.8 MB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:14.04
 ---> b39b81afc8ca
Step 1 : COPY data/profiles/ /data/profiles
 ---> da45506874a0
Removing intermediate container 4acf7e9662cd
Step 2 : COPY data/images/607.0.0/coreos_production_pxe_image.cpio.gz data/images/607.0.0/
 ---> 3c8fab527cb9
Removing intermediate container 94a415db021b
Step 3 : VOLUME /data
 ---> Running in d0c3d63a3eec
 ---> f4230026947a
Removing intermediate container d0c3d63a3eec
Successfully built f4230026947a

Notice no "using cache" at step 2.  That's surely a bug.

**Comment by vdemeester** [comment] 2015-04-16 07:20
Hi,

I think it's by design. You change the content of the folder your adding in Step 1 so the resulting image won't be the same ; that's why it's not using cache. As the image generated is not the same at the end of step 1, it's not possible to use the cache for Step 2.

The cache take account the command (ADD, etc..) and the image the step is based on. If the image the step is based done changes (like yours). The cache is about the images generated, not about single files or commands. The cache is doing something like "ok I have this image, I'm doing that command and I got that result. oh it has already been done with this image and this command, so I know the result and I already have it somewhere, let's not re-do it" ; if the image changes (or the command) there is no way to predict the resulting image.

**Comment by vdemeester** [comment] 2015-04-16 07:47
Take a look at this : https://docs.docker.com/articles/dockerfile_best-practices/#build-cache

**Comment by unclejack** [comment] 2015-04-16 10:36
@hookenz Images are layered on top of each other. For a build involving layers A->B->C->D, if A is a cache hit and B is a miss, all steps following B will be a miss. C and D are built on top of B. These layers depend on B and they can't be assigned to B1 (the new layer B which results from building with a changed Dockerfile).

The cache is made up of layers, not out of cached files which are added via ADD or COPY. That's why it's not possible to re-use layers. Even if there would be some kind of `cache hit` on that file, it would still involve the creation of a new set of layers which have B1 as the parent and calling this `cache hit` wouldn't make sense at all.

**Closed by unclejack** 2015-04-16 10:36 UTC
