### ISSUE TITLE
Can't build a Dockerfile that is a symlink

### ISSUE THREAD

**Issue by LaurentGoderre** [docker/docker#32041] opened 2017-03-23 14:30 UTC
**Description**
When trying to build a Dockerfile that is a symlink, the build fails with `unable to prepare context: The Dockerfile () must be within the build context`

**Steps to reproduce the issue:**
1. Create a Dockerfile
2. Create symlink to that Dockerfile
3. Run `docker build .` in the directory where the symlink is

**Describe the results you received:**
I got `unable to prepare context: The Dockerfile () must be within the build context `. Replacing the symlink with the actual file fixes the issue

**Describe the results you expected:**
It should build with the symlink.

**Output of `docker version`:**

```
Docker version 17.03.0-ce, build 60ccb22
```

**Output of `docker info`:**

```
Containers: 47
 Running: 3
 Paused: 0
 Stopped: 44
Images: 149
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-41-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.765 GiB
Name: ubuntu
ID: YRAG:HOND:JAEU:JAQI:2BE5:6D4F:TETJ:DAYT:DNFD:NIM4:OULL:BPCG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://godelau:i68hHgdk@stcweb.statcan.ca:80/
Https Proxy: http://godelau:i68hHgdk@stcweb.statcan.ca:80/"
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment] 2017-03-23 14:38
I cannot reproduce this.
Is the symlink pointing to a path outside of the build context?
If so, that's the problem.

Closing, but let me know!

**Closed by cpuguy83** 2017-03-23 14:38 UTC
Labels: area/builder

**Comment by LaurentGoderre** [comment] 2017-03-23 14:41
I'm not familiar what the build context, how do I know if it's in the same context?

**Comment by cpuguy83** [comment] 2017-03-23 14:42
@LaurentGoderre in your example `.` is the build context.
So anything in `.` and everything underneath.

**Comment by LaurentGoderre** [comment] 2017-03-23 14:43
Ah ok then it is not. There's no way around that?

**Comment by cpuguy83** [comment] 2017-03-23 14:44
No, it must be within the passed in context.
