### ISSUE TITLE
install script not working on AWS ubuntu 14.04.2

### ISSUE THREAD

**Issue by scottdraves** [docker/docker#14658] opened 2015-07-15 18:15 UTC
If you create a fresh AWS instance of 64-bit Ubuntu 14.04.2, then apt-get update/upgrade, then try to run the install script (wget -qO- https://get.docker.com/ | sh), it fails right away with this error:
```
modprobe: FATAL: Module aufs not found.
```
The solution, which I found [here](https://meta.discourse.org/t/docker-install-module-aufs-not-found/18494) is to run
```
sudo apt-get install lxc wget bsdtar curl
sudo apt-get install linux-image-extra-$(uname -r)
sudo modprobe aufs
```
but really the script should do this for you automatically.  the kernel is
```
$ uname -a
Linux ip-10-0-0-96 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by scottdraves** [comment] 2015-07-15 19:33
all the requested info is in my report and i searched to see if it already existed.

**Comment by icecrime** [comment] 2015-07-16 15:31
Ping @jfrazelle: WDYT? I don't think we had any recent change to the install script.

**Comment by icecrime** [comment] 2015-07-16 15:34
Yep, as far as I can tell the [script is good](https://github.com/docker/docker/blob/master/hack/install.sh#L169-L172) and [nothing has changed](https://github.com/docker/docker/commits/master/hack/install.sh) on this regard since a while.

**Comment by scottdraves** [comment] 2015-07-16 16:42
Be that as it may, this happens to me every time and if you aren't able to reproduce I would be happy to look further into why it's happening.

**Comment by jfrazelle** [comment] 2015-07-16 18:28
I will spin up Amazon Linux and try

**Comment by jfrazelle** [comment] 2015-07-16 18:29
Oh it's not even Amazon Linux it's Ubuntu... Weird

**Comment by jfrazelle** [comment] 2015-07-16 21:29
I cannot reproduce :(

**Comment by jfrazelle** [comment] 2015-07-16 21:44
i get on a fresh amazon ubuntu 14.04 instance:
```
ubuntu@ip-172-31-36-147:~$ curl -sSL https://get.docker.com | sh
modprobe: FATAL: Module aufs not found.
+ sh -c sleep 3; apt-get update
Ign http://us-west-2.ec2.archive.ubuntu.com trusty InRelease
Ign http://us-west-2.ec2.archive.ubuntu.com trusty-updates InRelease
Hit http://us-west-2.ec2.archive.ubuntu.com trusty Release.gpg
Hit http://us-west-2.ec2.archive.ubuntu.com trusty-updates Release.gpg
Hit http://us-west-2.ec2.archive.ubuntu.com trusty Release
Hit http://us-west-2.ec2.archive.ubuntu.com trusty-updates Release             
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/main Sources                
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/universe Sources           
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/main amd64 Packages    
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/universe amd64 Packages
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/main Translation-en    
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/universe Translation-en
Hit http://us-west-2.ec2.archive.ubuntu.com trusty-updates/main Sources   
Hit http://us-west-2.ec2.archive.ubuntu.com trusty-updates/universe Sources
Hit http://us-west-2.ec2.archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://us-west-2.ec2.archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://us-west-2.ec2.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://us-west-2.ec2.archive.ubuntu.com trusty-updates/universe Translation-en
Ign http://us-west-2.ec2.archive.ubuntu.com trusty/main Translation-en_US 
Ign http://us-west-2.ec2.archive.ubuntu.com trusty/universe Translation-en_US
Ign http://security.ubuntu.com trusty-security InRelease                  
Hit http://security.ubuntu.com trusty-security Release.gpg                
Hit http://security.ubuntu.com trusty-security Release
Hit http://security.ubuntu.com trusty-security/main 
....
install all the things
```

so it continues after throwing that

**Comment by jrgifford** [comment] 2015-08-20 00:17
Any update on this?

**Comment by gdbtek** [comment] 2015-08-23 02:18
I can reproduce this error when running on Windows Azure Ubuntu x64 14.04.3 (release 8/6/2015). Adding `modprobe aufs` will make the error go away but I still think docker install script should handle automatically.

**Comment by clnperez** [comment] 2015-09-15 19:51
@gdbtek, can you try the bits in the install script manually that are there to get aufs (starting at line 254)? Maybe that would help to figure out what part of that block isn't working, etc.

**Comment by thaJeztah** [comment] 2015-10-18 05:07
Note that we also updated our installation documentation to move away from the automatic install script; https://docs.docker.com/installation/ubuntulinux/

**Comment by icecrime** [comment] 2016-09-10 02:38
Tentatively closing as the issue seems to be resolved: please let me know if it needs reopening! Thanks.

**Closed by icecrime** 2016-09-10 02:38 UTC
Labels: area/project, kind/bug
