### ISSUE TITLE
Error getting container from driver devicemapper during build

### ISSUE THREAD

**Issue by rednil** [docker/docker#10089] opened 2015-01-14 12:38 UTC
Trying to build from https://github.com/rednil/openstreetmap-tiles-docker, I am getting the following output:

Step 19 : RUN cd /usr/local/src/mapnik-style/inc && cp fontset-settings.xml.inc.template fontset-settings.xml.inc
 ---> Running in a464b257e6f9
 ---> 908810edf323
Removing intermediate container a464b257e6f9
Step 20 : COPY mapnik-style/inc/datasource-settings.sed /tmp/
 ---> a1c9d7174f01
Removing intermediate container 5803d4a43019
Step 21 : RUN cd /usr/local/src/mapnik-style/inc && sed --file /tmp/datasource-settings.sed  datasource-settings.xml.inc.template > datasource-settings.xml.inc
 ---> Running in 395637437e3b
 ---> 83b535bc37a1
Removing intermediate container 395637437e3b
Step 22 : COPY mapnik-style/inc/settings.sed /tmp/
 ---> fe01a8f86ecd
Removing intermediate container bb2e0579ea3f
Step 23 : RUN cd /usr/local/src/mapnik-style/inc && sed --file /tmp/settings.sed  settings.xml.inc.template > settings.xml.inc
 ---> Running in 9827ede1fbe2
INFO[1930] Error getting container 9827ede1fbe256ee46fc94334e021dae246a549f3e4757445dec5118eb0d0c59 from driver devicemapper: open /dev/mapper/docker-252:1-16193242-9827ede1fbe256ee46fc94334e021dae246a549f3e4757445dec5118eb0d0c59: no such file or directory 

When I log into fe01a8f86ecd and execute step 23 manually it works. Is this some race condition I am reading about elsewhere?

docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

docker info
Containers: 43
Images: 87
Storage Driver: devicemapper
 Pool Name: docker-252:1-16193242-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 10.96 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 17.84 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 3.468 GiB
Name: ThinkPad
ID: BGDR:G2CV:JKG6:2WA6:OQ2G:5FTX:2ISX:BO6W:DSLD:LEJ2:U7N3:F2UC
WARNING: No swap limit support

**Comment by gomes** [comment] 2015-01-14 17:17
Seems the same as https://github.com/docker/docker/issues/4036

**Comment by jfrazelle** [comment] 2015-01-14 19:32
ping @vbatts

**Comment by vbatts** [comment] 2015-01-14 20:56
duplicate of #4036

**Closed by vbatts** 2015-01-14 20:56 UTC
Labels: /system/devicemapper
