### ISSUE TITLE
How is possible to debug a goroutine leak?

### ISSUE THREAD

**Issue by aledbf** [docker/docker#13809] opened 2015-06-08 21:36 UTC
After 6 hours I see a leak but I don't know how to get a dump with information

docker version:1.6.2
docker info:
```
Client version: `1.6.2`
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2-dirty
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/amd64
```
uname:`Linux nodo-2 4.0.3 #2 SMP Thu May 28 00:30:15 UTC 2015 x86_64 Intel Xeon E312xx (Sandy Bridge) GenuineIntel GNU/Linux`
```
core@nodo-4 ~ $ top
top - 19:57:05 up  6:45,  1 user,  load average: 3.72, 3.41, 3.18
Tasks: 554 total,   3 running, 551 sleeping,   0 stopped,   0 zombie
%Cpu(s): 25.0 us,  1.0 sy,  0.0 ni, 72.9 id,  0.0 wa,  0.2 hi,  0.6 si,  0.3 st
KiB Mem:  46371184 total, 33756468 used, 12614716 free,   708068 buffers
KiB Swap:        0 total,        0 used,        0 free.  7144576 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  740 root      20   0 14.868g 4.257g  13976 S   0.3  9.6  35:25.37 docker
```

```
core@nodo-4 ~ $ docker --debug info
Containers: 247
Images: 660
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.3
Operating System: CoreOS 695.0.0
CPUs: 10
Total Memory: 44.22 GiB
Name: nodo-4
ID: C5W7:MT3O:3UDY:H6MN:GTTY:QSII:5VEM:45KG:D26E:JVYJ:3UFE:TRXG
Debug mode (server): false
Debug mode (client): true
Fds: 36975
Goroutines: 201482
System Time: Mon Jun  8 19:57:23 UTC 2015
EventsListeners: 2
Init SHA1: c99cce9a9442d108ef4f27f1159df9de1b0a724c
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker
```

Any advice?
Thanks

**Comment by LK4D4** [comment] 2015-06-08 21:41
@aledbf Send `SIGUSR1` to daemon, but be prepared for massive output.

**Comment by aledbf** [comment] 2015-06-09 12:50
@LK4D4 this is available in 1.6.2? I don't see any output from the kill command

**Comment by LK4D4** [comment] 2015-06-09 15:26
@aledbf Probably not :/ Only on master. But any issue is better to debug on master, because it can be already fixed.

**Comment by thaJeztah** [comment] 2015-06-09 17:25
@aledbf I'm going to close this issue, because this is not a bug in docker; feel free to continue the discussion here, or perhaps better, join the #docker-dev IRC channel

**Closed by thaJeztah** 2015-06-09 17:25 UTC
