### ISSUE TITLE
构建镜像双倍大小（Build Image Size Double）

### ISSUE THREAD

**Issue by lanmingle** [docker/docker#29970] opened 2017-01-07 19:44 UTC
In English? I do not understand, can will help translation, machine translation has a problem.

实例说明：

windows / mac - 1.12.5

在编写 Dockerfile 时，为了优化常常使用一条 RUN 语句运行，好了，现在就说我在 RUN 里面做的事，
下载一个 APP 包，这个包 1G 大小（随意说的），授权 APP 目录，好了到这来结束一层，现在这个构建后大小 1G ，这没有问题正常（注意这里都是 root 用户执行的）。
再之后在外边以 COPY / ADD 一个文件时（越大文件越易发现），这样也没有问题，大小就 1G 多（注意这里都是 root 用户执行的）。

再之后执行 RUN 创建一个运行 lanmingle 用户，并授权相关的目录和文件，构建到这部后发现镜像大小居然翻倍了（经过测试无论是先创建用户或者后创建用户都是出现这样的问题）

问题分析：
由于原文件是 root ，授权后 lanmingle ，docker 认为这两个层有差异，虽然是覆盖原来的，但是层之间会存储两份，一份是 root ，一份是 lanmingle 的，然而明示这是不是想要的，希望这个能忽略这个权限，同时保证也是想要的授权。

目前解决方案：

以 Dockerfile  编写全部一条 RUN 命令全部包括，如果 entrypoint 、配置文件、等都以网络下载的方式，但是这个虽然是非常之优化，可是这样不便于维护与开发。

编写 Dockerfile 时只允许 root 构建镜像，也就是不在 Dockerfile 中出现，允许时通过进入点脚本来控制。

虽然说现在官方的镜像，如 [jenkinsci](https://github.com/jenkinsci/docker/blob/c8ef1879caef495f692b8c46eeb1de88a3783886/Dockerfile)
看起来好像做到了优化，但是这个层还是存在两份。

发现问题的一个 Dockerfile ，无论是否是我编写这个 Dockerfile 不够完美还是怎么样的，这毕竟是不好的，太过容易犯错了，还有推送到私有的镜像库时也是两份。

```

FROM bestci/openjdk8-jre:latest

MAINTAINER lanmingle<lanmingle@qq.com>

ARG LOGSTASH_TAR_URL="http://192.168.1.200/docker-image-software/logstash/logstash-5.1.1.tar.gz"
ARG LOGSTASH_TAR_DIR_PATH="logstash-5.1.1"
ARG LOGSTASH_INSTALL_DIR="/usr/local/logstash"

ENV \
LS_HOME="$LOGSTASH_INSTALL_DIR" \
LOGSTASH_HOME="$LOGSTASH_INSTALL_DIR" \
LOGSTASH_DATA_PATH="/srv/docker/container/logstash/data" \
LOGSTASH_CONF_PATH="/srv/docker/container/logstash/config" \
LOGSTASH_LOGS_PATH="/srv/docker/container/logstash/logs" \
LOGSTASH_COPY_PATH="/srv/docker/container/logstash/copy"

RUN set -e \

apk add --no-cache \
libzmq \

&& curl -L -N -o /tmp/logstash.tar.gz $LOGSTASH_TAR_URL \

&& tar -zxf /tmp/logstash.tar.gz -C /tmp/ \
&& mv /tmp/$LOGSTASH_TAR_DIR_PATH/ $LOGSTASH_HOME/ \

&& rm -rf \
$LOGSTASH_HOME/LICENSE \
$LOGSTASH_HOME/CONTRIBUTORS \
$LOGSTASH_HOME/NOTICE.TXT \
$LOGSTASH_HOME/*.md \
$LOGSTASH_HOME/bin/*.bat \

&& ln -sf $LOGSTASH_HOME/bin/* /usr/local/bin/ \

&& mkdir -p $LOGSTASH_DATA_PATH/ \
&& mkdir -p $LOGSTASH_CONF_PATH/ \
&& mkdir -p $LOGSTASH_LOGS_PATH/ \
&& mkdir -p $LOGSTASH_COPY_PATH/ \

&& rm -rf $LOGSTASH_HOME/data/ \
&& ln -sf $LOGSTASH_DATA_PATH/ $LOGSTASH_HOME/ \

&& rm -rf $LOGSTASH_HOME/config/ \
&& ln -sf $LOGSTASH_CONF_PATH/ $LOGSTASH_HOME/ \

&& rm -rf $LOGSTASH_HOME/logs/ \
&& ln -sf $LOGSTASH_LOGS_PATH/ $LOGSTASH_HOME/ \

&& rm -rf /var/cache/apk/* /tmp/*

COPY ./docker-entrypoint.sh $LOGSTASH_HOME/docker-entrypoint.sh

COPY ./config/ $LOGSTASH_COPY_PATH/config/

RUN set -e \

&& chmod +x $LOGSTASH_HOME/*.sh \

&& addgroup -g 50 -S docker \
&& adduser -h /home/docker -g docker -s /bin/sh -u 1001 -G docker -S -D docker \

&& chown -hR docker:docker $LOGSTASH_HOME/ \

&& chown -hR docker:docker $LOGSTASH_DATA_PATH/ \
&& chown -hR docker:docker $LOGSTASH_CONF_PATH/ \
&& chown -hR docker:docker $LOGSTASH_LOGS_PATH/ \
&& chown -hR docker:docker $LOGSTASH_COPY_PATH/ \

&& rm -rf /var/cache/apk/* /tmp/*

VOLUME ["$LOGSTASH_DATA_PATH"]

EXPOSE 9600

USER docker

WORKDIR $LOGSTASH_HOME

ENTRYPOINT ["./docker-entrypoint.sh"]

CMD ["./bin/logstash"]




```

**Comment by lanmingle** [comment] 2017-01-08 07:41
目前我的解决方案：

alpine Dockerfile
```

FROM alpine:3.5

MAINTAINER lanmingle<lanmingle@qq.com>

ARG PRIVATE_CA_URL="http://192.168.1.200/docker-image-config/certs/ca-bestci.crt"
ARG REPOSITORIES_URL="http://mirrors.aliyun.com/alpine"
ARG REPOSITORIES_VERSION="v3.5"

RUN set -e \

&& echo -e "$REPOSITORIES_URL/$REPOSITORIES_VERSION/main" > /etc/apk/repositories \
&& echo -e "$REPOSITORIES_URL/$REPOSITORIES_VERSION/community" >> /etc/apk/repositories \
&& echo -e "$REPOSITORIES_URL/edge/main" >> /etc/apk/repositories \
&& echo -e "$REPOSITORIES_URL/edge/community" >> /etc/apk/repositories \
&& echo -e "$REPOSITORIES_URL/edge/testing" >> /etc/apk/repositories \

&& apk add --no-cache \
xz \
zip \
tar \

wget \
curl \
bash \
gzip \
unzip \
bzip2 \

openssl \
ca-certificates \

musl \
tzdata \
su-exec \
busybox \
linux-headers \

&& apk upgrade --no-cache \

&& apk update --no-cache \

&& cp -R /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo -e "Asia/Shanghai" > /etc/timezone \

&& curl -L -N -o /etc/ssl/certs/ca-bestci.crt $PRIVATE_CA_URL \

&& cat /etc/ssl/certs/ca-bestci.crt >> /etc/ssl/certs/ca-certificates.crt \

&& apk del --no-cache \
tzdata \

&& rm -rf /var/cache/apk/* /tmp/*

ENV \
CLICOLOR="1" \
CHARSET="UTF-8" \
LANG="zh_CN.UTF-8" \
LC_ALL="zh_CN.UTF-8" \
TERM="xterm-256color" \
LSCOLORS="gxfxcxdxbxegedabagacad" \
PS1="\033[01;32m\u@\h\033[00m : \033[01;36m\w\033[00m \$ "

WORKDIR /

USER root

CMD ["/bin/bash"]




```

logstash Dockerfile

```

FROM bestci/openjdk8-jre:latest

MAINTAINER lanmingle<lanmingle@qq.com>

ARG LOGSTASH_TAR_URL="http://192.168.1.200/docker-image-software/logstash/logstash-5.1.1.tar.gz"
ARG LOGSTASH_TAR_DIR_PATH="logstash-5.1.1"
ARG LOGSTASH_INSTALL_DIR="/usr/local/logstash"

ENV \
LS_HOME="$LOGSTASH_INSTALL_DIR" \
LOGSTASH_HOME="$LOGSTASH_INSTALL_DIR" \
LOGSTASH_DATA_PATH="/srv/docker/container/logstash/data" \
LOGSTASH_CONF_PATH="/srv/docker/container/logstash/config" \
LOGSTASH_LOGS_PATH="/srv/docker/container/logstash/logs" \
LOGSTASH_COPY_PATH="/srv/docker/container/logstash/copy"

RUN set -e \

&& addgroup -g 50 -S docker \
&& adduser -h /home/docker -g docker -s /bin/bash -u 1001 -G docker -S -D docker \

&& apk add --no-cache \
libzmq \

&& curl -L -N -o /tmp/logstash.tar.gz $LOGSTASH_TAR_URL \

&& tar -zxf /tmp/logstash.tar.gz -C /tmp/ \
&& mv /tmp/$LOGSTASH_TAR_DIR_PATH/ $LOGSTASH_HOME/ \

&& rm -rf \
$LOGSTASH_HOME/LICENSE \
$LOGSTASH_HOME/CONTRIBUTORS \
$LOGSTASH_HOME/NOTICE.TXT \
$LOGSTASH_HOME/*.md \
$LOGSTASH_HOME/bin/*.bat \

&& ln -sf $LOGSTASH_HOME/bin/* /usr/local/bin/ \

&& mkdir -p $LOGSTASH_DATA_PATH/ \
&& mkdir -p $LOGSTASH_CONF_PATH/ \
&& mkdir -p $LOGSTASH_LOGS_PATH/ \
&& mkdir -p $LOGSTASH_COPY_PATH/ \

&& rm -rf $LOGSTASH_HOME/data/ \
&& ln -sf $LOGSTASH_DATA_PATH/ $LOGSTASH_HOME/ \

&& rm -rf $LOGSTASH_HOME/config/ \
&& ln -sf $LOGSTASH_CONF_PATH/ $LOGSTASH_HOME/ \

&& rm -rf $LOGSTASH_HOME/logs/ \
&& ln -sf $LOGSTASH_LOGS_PATH/ $LOGSTASH_HOME/ \

&& rm -rf /var/cache/apk/* /tmp/*

COPY ./docker-entrypoint.sh $LOGSTASH_HOME/docker-entrypoint.sh

COPY ./config/ $LOGSTASH_COPY_PATH/config/

VOLUME ["$LOGSTASH_DATA_PATH"]

EXPOSE 9600

WORKDIR $LOGSTASH_HOME

ENTRYPOINT ["./docker-entrypoint.sh"]

CMD ["./bin/logstash"]


```

logstash docker-entrypoint.sh

```

#!/bin/bash

# ------------------------------------------------------------------------

set -e

# ------------------------------------------------------------------------

## 执行打印信息

echo -e "执行 logstash 进入点脚本 。。。" ;

## 脚本环境变量

LOGSTASH_COPY_CONF_PATH="$LOGSTASH_COPY_PATH/config" ;

## 复制备份配置

echo -e "检测 logstash 默认的配置文件。。。" ;
for FILE in $LOGSTASH_COPY_CONF_PATH/*
do
    if test -f $FILE && test ! -f $LOGSTASH_CONF_PATH/$(basename $FILE) ; then
        echo -e "不存在 logstash 默认的配置文件[$FILE]，拷贝至[$LOGSTASH_CONF_PATH]目录上。" ;
        cp -R $FILE $LOGSTASH_CONF_PATH ;
    fi
done

## 杀死之前运行

echo -e "强制杀死 logstash 运行进程 。。。" ;
echo -e "kill logstash ♂♂♂ $(ps | grep docker | grep java | awk '{print $1}' | xargs kill)" ;

## 授权执行用户

chown -hR docker:docker $LOGSTASH_HOME ;

chown -hR docker:docker $LOGSTASH_DATA_PATH/ ;
chown -hR docker:docker $LOGSTASH_CONF_PATH/ ;
chown -hR docker:docker $LOGSTASH_LOGS_PATH/ ;
chown -hR docker:docker $LOGSTASH_COPY_PATH/ ;

## 指定用户执行

su-exec docker $@ ;

# ------------------------------------------------------------------------


```

**Comment by jmzwcn** [comment] 2017-01-08 10:52
My god, maybe the boss does not get what you say.

**Comment by thaJeztah** [comment] 2017-01-09 11:10
Google translate;

Example:

Windows / mac - 1.12.5

In the preparation of Dockerfile, in order to optimize the operation often use a RUN statement, well, now that I do in the RUN things,
Download an APP package, the package 1G size (free to say), authorized APP directory, well to the end of this layer, and now the size of the building 1G, this is no problem normal (note here are the root user implementation).
And then outside in order to COPY / ADD a document (the larger the file easier to find), so there is no problem, the size of more than 1G (note here are the root user implementation).

And then run the RUN to create a run lanmingle users and authorize the relevant directories and files, built to this and found that the image size actually doubled (after testing whether to create a user or after the creation of the user is such a problem)

problem analysis:
As the original document is root, after the authorization lanmingle, docker think there are differences between the two layers, although it is covered by the original, but will be stored between the two layers, one is root, one is lanmingle, but expressly this is not Want, I hope this can ignore this authority, while ensuring that the authorization is also wanted.

The current solution:

Dockerfile all the preparation of a RUN order all included, if the entrypoint, configuration files, and so on to download the network, but this is a very optimized, but this is not easy to maintain and development.

Dockerfile only allows the preparation of the preparation of Dockerfile image, which is not in Dockerfile appear, allowing entry point script to control.

Although now the official mirror, such as jenkinsci
Looks like it seems to be optimized, but there are still two layers.

The problem is found in a Dockerfile, whether or not I write this Dockerfile is not perfect or how kind, which, after all, is not good, too easy to make mistakes, there are pushed to the private image library is also two.

**Comment by thaJeztah** [comment] 2017-01-09 11:23
If I understand your question correctly; _any_ modifications to files in a Dockerfile will increase the size of the final image. Each step (`RUN`, `COPY`, `ADD`) in a Dockerfile is run in a _new_ container, and the results of that step are committed to a new image / layer. This is inherent to Copy-on-Write filesystems.

For example;

```Dockerfile
FROM scratch

# Add a 1GB file to the image. Size of the image is now 1GB
COPY ./1-gigabyte-file /my-files

# Change permissions of the file. Previous image layer is immutable
# so the file is _copied_ to the new layer so that permissions can be changed
# after this step, the total size of the image is 2GB
RUN chown 123:456 /my-files/1-gigabyte-file

# Remove the file. Again, because previous layers are immutable,
# this will actually _add_ a "white-out" file to the image, which tells
# the copy-on-write filesystem that the file is "removed".
# After this step, the final image is 1Gb + 1 GB + the size of the "white-out" file
RUN rm /my-files/1-gigabyte-file
```

This is the expected behavior, so not a bug. However, if you want to shrink the final image (but loose the ability to share individual layers between images); docker 1.13 adds an option to "flatten" the image after it was built; https://github.com/docker/docker/pull/22641.

I don't think there's a bug here, so I'll close this issue, but please leave a comment if I misunderstood your issue (due to the translation)

**Closed by thaJeztah** 2017-01-09 11:23 UTC
Labels: area/builder

**Comment by lanmingle** [comment] 2017-01-10 05:15
Thank you very much! In fact, this I know, just want to ask about the solution. @thaJeztah
