### ISSUE TITLE
Better logging on the daemon side

### ISSUE THREAD

**Issue by ankushagarwal** [docker/docker#14300] opened 2015-06-30 19:50 UTC
The debug logs are not very useful on the docker daemon side. On the contrary, the `info` level log has more information than the debug logs. Quite often, I need the request payload on the daemon side to debug issues. So it would be very useful if we could start logging the request payloads for the `debug` option. I understand that there are concerns around logging the entire request payloads in the logs. Maybe we can have log verbosity levels like the ssh client does : `-v` `-vv` `-vvv`, etc

```
time="2015-06-30T18:29:20.942624045Z" level=debug msg="Calling POST /exec/{name:.*}/resize"
time="2015-06-30T18:29:20.942642020Z" level=info msg="POST /v1.19/exec/628828e6dbf54cf1ae13bca4686f752a3bc261da8929294f5ea9d986ce8fd8db/resize?h=29&w=118"
time="2015-06-30T19:13:42.135591688Z" level=debug msg="Calling POST /exec/{name:.*}/resize"
time="2015-06-30T19:13:42.135624001Z" level=info msg="POST /v1.19/exec/e9598da5d25abd0e1d786f1b2942e7d1f3a35deadd4b19735a563ff5482aa5bb/resize?h=28&w=118"
time="2015-06-30T19:13:42.135969931Z" level=debug msg="Calling POST /exec/{name:.*}/resize"
time="2015-06-30T19:13:42.136096583Z" level=info msg="POST /v1.19/exec/628828e6dbf54cf1ae13bca4686f752a3bc261da8929294f5ea9d986ce8fd8db/resize?h=28&w=118"
time="2015-06-30T19:13:42.136413742Z" level=debug msg="Calling POST /containers/{name:.*}/resize"
time="2015-06-30T19:13:42.136439762Z" level=info msg="POST /v1.19/containers/e3af39a2c720b4190000c28b9f3c6493a4cab54cadc3d5822c6b9de2f68468fb/resize?h=28&w=238"
```

`docker version`:
1.7

**Comment by thaJeztah** [comment] 2015-08-16 10:35
ping @LK4D4 @icecrime any thoughts on this? @icecrime also opened https://github.com/docker/docker/issues/11621 a while ago

**Comment by bfirsh** [comment] 2015-08-20 10:18
Thanks for the report @ankushagarwal. As @thaJeztah says, this is a dupe of #11621, so let's move the discussion there.

**Closed by bfirsh** 2015-08-20 10:18 UTC
Labels: kind/enhancement
