### ISSUE TITLE
A question regarding cpu usage percentage calculation.

### ISSUE THREAD

**Issue by pankit** [docker/docker#26711] opened 2016-09-19 16:35 UTC
Hi,

Can you please explain why in stats_helper.go, while caluclating cpu usage percentage, we have to take num of cpu cores into account as shown below.

```go
func calculateCPUPercent(previousCPU, previousSystem uint64, v *types.StatsJSON) float64 {
    var (
        cpuPercent = 0.0
        // calculate the change for the cpu usage of the container in between readings
        cpuDelta = float64(v.CPUStats.CPUUsage.TotalUsage) - float64(previousCPU)
        // calculate the change for the entire system between readings
        systemDelta = float64(v.CPUStats.SystemUsage) - float64(previousSystem)
    )

    if systemDelta > 0.0 && cpuDelta > 0.0 {
        cpuPercent = (cpuDelta / systemDelta) * float64(len(v.CPUStats.CPUUsage.PercpuUsage)) * 100.0
    }
    return cpuPercent
}
```  

As per my understanding, delta cpuacct.usage will give us the total usage in nanseconds by a cgroup. This number includes all the CPU's.

Thanks,
Pankit

**Comment by cpuguy83** [comment] 2016-09-19 19:48
I believe this normalises the percentage.
For instance if a process is using all resources of an 8 core CPU, this would look like 800%. Dividing by the number of cores makes it so it won't go over 100%.

**Comment by pankit** [comment] 2016-09-19 21:39
@cpuguy83 : Thanks for your response but the above logic will divide it by the number of cpu cores.

**Comment by thaJeztah** [comment] 2016-09-19 21:48
Actually `800%` is correct here, which is a standard notation for telling that 8 cores are 100% in use. See https://github.com/docker/docker/issues/18615, and https://github.com/docker/docker/pull/13627.

I'll close this issue, because this is not a bug, but feel free to continue the discussion

**Closed by thaJeztah** 2016-09-19 21:48 UTC
Labels: kind/question

**Comment by pankit** [comment] 2016-09-19 21:55
@thaJeztah Thanks for your response, the cpuDelta thing is where I get confused.

cpuDelta = difference in values in cpuacct.usage at two points in time. AFAIK, cpuacct.usage is total cpu nanoseconds for the cgroup. Correct me if I am wrong.

**Comment by thaJeztah** [comment] 2016-09-19 22:00
Isn't that whats discussed here? https://github.com/docker/docker/pull/13627#issuecomment-107415691 (perhaps I misunderstand as well :smile:)

**Comment by pankit** [comment] 2016-09-19 22:03
@thaJeztah : Yes, it explains the same thing, but I am trying to understand why the cpuDelta/systemDelta is the usage per CPU. As per my understanding, its the total usage and not per CPU.
May be I am missing very basic here.
