### ISSUE TITLE
Docker swarm mode service support local bridge network

### ISSUE THREAD

**Issue by rootsongjc** [docker/docker#28981] opened 2016-11-30 09:52 UTC
**Description**

In docker 1.12/1.13 docker swarm mode doesn't support node-local bridge network.
My custom network "mynet" works wonderful in docker1.11 with docker swarm, but not in docker 1.12+.

The networks I created in docker cluster.
myhost:/root]# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
53000ea97682        bridge              bridge              local
a5cc6b68aa89        docker_gwbridge     bridge              local
ed079ba7b63f        host                host                local
rbxdx40rwyiw        ingress             overlay             swarm
**85fec12c0870        mynet               bridge              local**
9edec16bc302        none                null                local
[https://github.com/rootsongjc/docker-ipam-plugin](url)
How can i use my custom bridge network in docker1.12+
Does it have any road map for this feature?
#27917 
As I know, docker service create now support ingress and host network.

**Comment by mavenugo** [comment] 2016-11-30 16:13
@rootsongjc do you have any problem using overlay driver instead of bridge driver ? Also you can change your `docker-ipam-plugin` as global scoped and allocate IP-addresses for your containers across multiple hosts easily. Just return the scope as `global` instead of `local` and use that in `docker network create -d overlay --ipam-driver docker-ipam-plugin mynet`. And use that network in `docker service create`. Will that work for you ?

**Comment by rootsongjc** [comment] 2016-12-05 03:20
@mavenugo Yes, I prefer to use bridge network rather than overlay, because I need to make the containers have solid IP address and accessalbe  with hosts directly.

**Comment by thaJeztah** [comment] 2016-12-05 16:57
@rootsongjc looks like this is a duplicate of https://github.com/docker/docker/issues/27082, and you were already in that discussion, so I'll close this issue here, otherwise the discussion is only diverging

**Closed by thaJeztah** 2016-12-05 16:57 UTC
Labels: area/networking, area/swarm
