### ISSUE TITLE
Files added, but user unable to access a directory within.

### ISSUE THREAD

**Issue by atrauzzi** [docker/docker#10340] opened 2015-01-26 01:43 UTC
I'm encountering a really odd issue with a specific directory out of a bunch of files I've `ADD`ed.

Please see: http://stackoverflow.com/questions/28139448/nginx-refusing-to-serve-files-403-despite-777-to-entire-filesystem for more information.

To briefly summarize: `www-data` doesn't have access to the path `/var/www/public` when the container is made.  Even if the permissions are `777`.

However!  When I rename the directory to something bogus and then back to what it's supposed to be, the user can now list the contents of the directory.

**Comment by thaJeztah** [comment] 2015-01-31 23:57
Are you using AUFS? Then this sounds like the issue described in the ["known issues" section](https://docs.docker.com/release-notes/#known-issues). This comment on the underlying issue describes quite clearly what the problem is there: https://github.com/docker/docker/issues/783#issuecomment-19237045

If that does indeed look like the issue you're having (and you're using AUFS), perhaps you could add/mention that on StackOverflow as well to assist other people running into that problem.

HTH!

**Comment by atrauzzi** [comment] 2015-02-01 14:59
No, interestingly this happens on OSX and Linux alike.

**Comment by thaJeztah** [comment] 2015-02-01 15:33
Those are the underlying filesystems of the *host*. Docker itself uses its own filesystem (aufs, device mapper, overlay, btrfs) to store containers.

(Also, note that when running Docker on OS X, Docker *itself* runs in boot2docker, a lightweight virtual machine that runs Linux).

To determine what filesystem/storage-driver Docker is using, run `docker info` and look at the *"Storage Driver"* in the output. In the example output below, you can see that Docker uses `auks`, but the *underlying* filesystem of the host ("Backing Filesystem") is `extfs`;

```
$ docker info
Containers: 12
Images: 672
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 697
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 994.1 MiB
Name: example.com
ID: RC3P:JTCT:32YS:XYSB:YUBG:VFED:AAJZ:W3YW:76XO:D7NN:TEVU:UCRW
WARNING: No swap limit support
```

**Comment by jfrazelle** [comment] 2015-02-28 03:35
closing as dup of https://github.com/docker/docker/issues/783#issuecomment-19237045

**Closed by jfrazelle** 2015-02-28 03:35 UTC
