### ISSUE TITLE
dockerignore does not respect the "special wildcard **"

### ISSUE THREAD

**Issue by ebr** [docker/docker#21433] opened 2016-03-23 16:45 UTC
As per documentation:
`Docker also supports a special wildcard string ** that matches any number of directories (including zero). For example, **/*.go will exclude all files that end with .go that are found in all directories, including the root of the build context`

Trying to use the special wildcard, and it seems to have no effect.

**Steps to reproduce the issue:**
1. Add the following to dockerignore:
  ``` .dockerignore
  **/*.log
  **/.DS_Store
  ```
2. `docker-compose build && docker-compose up`
3. attach to the container and `ls -alF`

**Describe the results you received:**

Both `.DS_Store` and some `test.log` files show up

**Describe the results you expected:**

These files shouldn't be in the image.

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Sat Mar 12 04:07:44 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 46
 Running: 2
 Paused: 0
 Stopped: 44
Images: 197
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 400
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: FANM:UYEH:36JH:QESC:PZJT:RYIK:ASW7:LASQ:JXIM:2COO:MDGX:VMED
Debug mode (server): true
 File Descriptors: 25
 Goroutines: 38
 System Time: 2016-03-23T16:38:43.303357697Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: ebr
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on OS X 10.11.2 in Virtualbox 5.0.14

**Comment by ernstp** [comment] 2016-05-31 08:54
I'm seeing the same issue. Linux client.

**Comment by thaJeztah** [comment] 2016-05-31 11:48
I'm not able to reproduce this on Docker 1.11; are you using Docker directly, or do you have this issue when starting containers with Docker Compose? (there was/is a bug in Docker Compose that did not parse the `.dockerignore` file correctly).

To test if this works as intended;

Create a directory, and `.go` and `.txt` files at several levels;

```bash
mkdir -p repro-21433/sub1/sub2 && cd repro-21444
touch foo0.go bar0.txt sub1/foo1.go sub1/bar1.txt sub1/sub2/foo2.go sub1/sub2/bar2.txt
```

created a `.dockerignore` file:

```gitignore
.dockerignore
Dockerfile
**/*.go
```

created a `Dockerfile`;

```Dockerfile
FROM alpine
RUN apk add --no-cache tree
COPY . /copied/
CMD tree /copied/
```

build an image, and run it;

```bash
docker build -t repro-21443 .

docker run -it --rm ignored
/copied/
├── bar0.txt
└── sub1
    ├── bar1.txt
    └── sub2
        └── bar2.txt

2 directories, 3 files
```

All `.go` files should be ignored, and only the `.txt` files are added to the image

**Comment by ernstp** [comment] 2016-05-31 12:06
I had an error in my first conclusion, ** worked in one case but not in another.

So adding a simple
**/__pycache__
worked exactly as intended, no __pycache__ directories from any level was included.

However a file that looked like this:
*
!django/**/*.py
!django/**/*.html

didn't work. Only *.py files from the first level was included, not from deeper levels.
So perhaps it was only a problem with the ! syntax.. ?

**Comment by thaJeztah** [comment] 2016-05-31 12:25
@ernstp hm could be, I'm not sure that is supported currently; I don't see a test-case covering that (https://github.com/docker/docker/commit/eddb14a44eb3ca6ba0b5e6906e21d767eba1af86), so it's possible it doesn't work. Feel free to open a separate issue for it if it doesn't work, then we can either discuss implementing it, or updating the documentation to explain it isn't supported

**Comment by thaJeztah** [comment] 2016-05-31 12:28
@ebr I suspect you're running into a bug in Docker Compose (see https://github.com/docker/compose/issues/1607, and https://github.com/docker/docker-py/pull/1065); it does look to be working correctly in Docker, so I'll close this issue, but feel free to comment after I closed

**Closed by thaJeztah** 2016-05-31 12:28 UTC
Labels: area/builder, status/more-info-needed, version/1.10

**Comment by samypr100** [comment] 2017-06-29 19:43
Same here (e.g.):
```
*
!**/*.go
```
Doesn't work (I would expect to ignore everything except .go files).
Only "exclusion" works like so:
```
**/*.go
```
This will ignore all .go files recursively properly.

Any particular reason why this is not supported for inclusion?

**Using docker command line directly**

**Comment by szczurmys** [comment] 2017-06-30 11:04
@samypr100 - I think, it is for performance reason, the same situation is in .gitignore https://git-scm.com/docs/gitignore 

> [...] It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, [...]
