### ISSUE TITLE
Docker restart an container after an rm

### ISSUE THREAD

**Issue by Marbellasaad** [docker/docker#31536] opened 2017-03-04 00:58 UTC
Hello i started an container and now i can't remove it.

Example : 
Here is the container : https://puu.sh/ut8do/7b8beb929f.png

Now i run the command "docker rm -f 9a0f59433517"
https://puu.sh/ut8h6/8dfe8904a6.png

And it come back with another name : https://puu.sh/ut8iW/8d333ec637.png

Thanks

**Comment by thaJeztah** [comment] 2017-03-04 01:02
that's because those containers are part of a service; see this comment for more information https://github.com/docker/docker/issues/31439#issuecomment-283216834

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-04 01:02 UTC
