### ISSUE TITLE
Status of docker stack rm command

### ISSUE THREAD

**Issue by gouravgupta92** [docker/docker#32552] opened 2017-04-12 10:16 UTC
Description
Currently, if I run docker stack deploy --compose-file STACKFILE.yml STACKNAME multiple times, 
and i am using docker stack rm STACKNAME to remove stack.
but sometimes if i am immediately deploying stack again after removing it.  
it gives error like network not available because previous stack is not removed completely and network of previous stack is also present.
please provide a way to check if services and network of stack are completely removed or not.

**Comment by dnephin** [comment] 2017-04-12 15:12
Duplicate of #29293

**Closed by dnephin** 2017-04-12 15:12 UTC
