### ISSUE TITLE
unable to prevent docker containers restarting

### ISSUE THREAD

**Issue by gzcwnk** [docker/docker#31439] opened 2017-03-01 00:52 UTC
================
```
root@debian8:/var/lib/docker/containers# docker ps
CONTAINER ID        IMAGE                                                                                                           COMMAND                  CREATED             STATUS              PORTS               NAMES
ff6638cd8bd3        dockersamples/examplevotingapp_result@sha256:9cbe68283fc56ac0d9b8c0f2656a4ae6df10e9a48956a48d0c9c6f230aea9374   "node server.js"         7 minutes ago       Up 7 minutes        80/tcp              vote_result.1.raya10ub3arjphexu7439ubve
db8480acd9c8        dockersamples/visualizer@sha256:f924ad66c8e94b10baeaf7bdb9cd491ef4e982a1d048a56a17e02bf5945401e5                "npm start"              7 minutes ago       Up 7 minutes        8080/tcp            vote_visualizer.1.knxobtehg4sacns7zihgx4osb
a962cd6844f7        ubuntu@sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950                                  "sleep infinity"         7 minutes ago       Up 7 minutes                            test.2.kqtqlxshs7knd80wzcc4ow2nb
144f635da813        postgres@sha256:c681c72ff62b637b9ad3806a946f14450f74ee0888ca70ec1472a4e0552054c2                                "docker-entrypoint..."   7 minutes ago       Up 7 minutes        5432/tcp            vote_db.1.vdhs4b4zbacu0gr39ec550zmc
df8dc0e0289a        nginx@sha256:4296639ebdf92f035abf95fee1330449e65990223c899838283c9844b1aaac4c                                   "nginx -g 'daemon ..."   7 minutes ago       Up 7 minutes        80/tcp, 443/tcp     objective_joliot.1.gk2v7iyklmryztoejm2thlqfa
1fc851a75071        nginx@sha256:4296639ebdf92f035abf95fee1330449e65990223c899838283c9844b1aaac4c                                   "nginx -g 'daemon ..."   7 minutes ago       Up 7 minutes        80/tcp, 443/tcp     objective_joliot.3.twf3xsf8f8d9b4cl3kmacswxc
507d5fac721c        nginx@sha256:4296639ebdf92f035abf95fee1330449e65990223c899838283c9844b1aaac4c                                   "nginx -g 'daemon ..."   7 minutes ago       Up 7 minutes        80/tcp, 443/tcp     objective_joliot.2.60o0sq5my2q28gn3d154tqk83
87c12cc2c9b5        alpine@sha256:dfbd4a3a8ebca874ebd2474f044a0b33600d4523d03b0df76e5c5986cb02d7e8                                  "ping docker.com"        7 minutes ago       Up 7 minutes                            helloworld.1.jr7g7ja2i0k165iiy64vz49ko
309bb24ddd94        redis@sha256:a1ccc6ff4e17e7e9ec0ba25dc9d99ca979171f4ef25d842baa835960b82322ae                                   "docker-entrypoint..."   7 minutes ago       Up 7 minutes        6379/tcp            redis.3.tkxcrbg48gq85axqskfckfc1p
39e6514f57bc        ubuntu@sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950                                  "sleep infinity"         7 minutes ago       Up 7 minutes                            test.3.j4qm2gc72lpj6m8mia7hxcxaj
97262b6e8fe3        redis@sha256:a1ccc6ff4e17e7e9ec0ba25dc9d99ca979171f4ef25d842baa835960b82322ae                                   "docker-entrypoint..."   7 minutes ago       Up 7 minutes        6379/tcp            redis.2.zgmdlzugpj2q2fuykb564tcir
6c4eadf431ae        ubuntu@sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950                                  "sleep infinity"         7 minutes ago       Up 7 minutes                            test.1.hkxk21ympyd72oqs48ffxuun1
ef98bd9b843c        redis@sha256:a1ccc6ff4e17e7e9ec0ba25dc9d99ca979171f4ef25d842baa835960b82322ae                                   "docker-entrypoint..."   7 minutes ago       Up 7 minutes        6379/tcp            redis.1.s07kxns23pi1ck4sogrc5sb2m
```

```
root@debian8:/var/lib/docker/containers# docker stop $(docker ps -a -q)
b72206e30f47

ff6638cd8bd3
db8480acd9c8
a962cd6844f7
144f635da813
df8dc0e0289a
1fc851a75071
507d5fac721c
87c12cc2c9b5
309bb24ddd94
39e6514f57bc
97262b6e8fe3
6c4eadf431ae
ef98bd9b843c
root@debian8:/var/lib/docker/containers# 
root@debian8:/var/lib/docker/containers# 
root@debian8:/var/lib/docker/containers# docker ps
CONTAINER ID        IMAGE                                                                              COMMAND                  CREATED             STATUS                  PORTS               NAMES
1287683464a8        postgres@sha256:c681c72ff62b637b9ad3806a946f14450f74ee0888ca70ec1472a4e0552054c2   "docker-entrypoint..."   5 seconds ago       Up Less than a second   5432/tcp            vote_db.1.wms8zmjictj3qtiwahiaw1ue8
418fc8430f55        ubuntu@sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950     "sleep infinity"         6 seconds ago       Up Less than a second                       test.3.8vj6c7zdq192bz9cba0grf1w5
f49a462bc3f7        ubuntu@sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950     "sleep infinity"         7 seconds ago       Up 1 second                                 test.2.yh65pntgsrjs8wqahgz24f30o
50048e811702        alpine@sha256:dfbd4a3a8ebca874ebd2474f044a0b33600d4523d03b0df76e5c5986cb02d7e8     "ping docker.com"        8 seconds ago       Up 2 seconds                                helloworld.1.r9885y5805yntjub56ijseib1
5eaca0fc1e60        nginx@sha256:4296639ebdf92f035abf95fee1330449e65990223c899838283c9844b1aaac4c      "nginx -g 'daemon ..."   16 seconds ago      Up 10 seconds           80/tcp, 443/tcp     objective_joliot.3.hnl005e0dfnokw4b7yi1xurhm
ef81327b0894        redis@sha256:a1ccc6ff4e17e7e9ec0ba25dc9d99ca979171f4ef25d842baa835960b82322ae      "docker-entrypoint..."   16 seconds ago      Up 10 seconds           6379/tcp            redis.3.13bsxuupslxcnv38nl5jwc3fo
37d14d345846        redis@sha256:a1ccc6ff4e17e7e9ec0ba25dc9d99ca979171f4ef25d842baa835960b82322ae      "docker-entrypoint..."   16 seconds ago      Up 10 seconds           6379/tcp            redis.1.iakcor7ae5jwigk80ulnocs1e
1ba0bce3fffc        redis@sha256:a1ccc6ff4e17e7e9ec0ba25dc9d99ca979171f4ef25d842baa835960b82322ae      "docker-entrypoint..."   16 seconds ago      Up 10 seconds           6379/tcp            redis.2.cuge0p4cgqomg2q2js2f1odd2
732f06483c43        nginx@sha256:4296639ebdf92f035abf95fee1330449e65990223c899838283c9844b1aaac4c      "nginx -g 'daemon ..."   17 seconds ago      Up 11 seconds           80/tcp, 443/tcp     objective_joliot.2.s58jeg1f18hhm9ls9g05g0nwr
44711f24a412        nginx@sha256:4296639ebdf92f035abf95fee1330449e65990223c899838283c9844b1aaac4c      "nginx -g 'daemon ..."   18 seconds ago      Up 12 seconds           80/tcp, 443/tcp     objective_joliot.1.e5kp2khzqqd06e58twf9951qy
root@debian8:/var/lib/docker/containers#
==============
```

<!--
Briefly describe the problem you are having in a few paragraphs.

I cannot keep containers stopped so I can delete (rm) them)

**Steps to reproduce the issue:**
no idea.  I simply installed docker and now find I cannot stop and rm containers.

**Describe the results you received:**

as above

**Describe the results you expected:**

docker containers should stop and get deleted.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time, unable to find solution via Google.

**Output of `docker version`:**

===============
root@debian8:/var/lib/docker/containers# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@debian8:/var/lib/docker/containers# uname -a
Linux debian8 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux
root@debian8:/var/lib/docker/containers# more  /etc/
Display all 240 possibilities? (y or n)
root@debian8:/var/lib/docker/containers# more  /etc/re
reportbug.conf  request-key.d/  resolvconf/     resolv.conf     
root@debian8:/var/lib/docker/containers# more  /etc/debian_version 
8.7
root@debian8:/var/lib/docker/containers#
===============

(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Debian 8 VM running on RHEL7 server KVM.

**Comment by thaJeztah** [comment] 2017-03-01 01:30
This is the intended behavior. You're trying to stop containers that are part of a service. When creating a service, docker will monitor the containers that are backing a service, and if a container fails, start a new container to ensure the service is "up".

To remove these containers, remove the service; to remove all services listed in your example above;

```
docker service rm vote test helloworld redis objective_juliot
```

read more about how services work in a swarm; https://docs.docker.com/engine/swarm/


I'll close this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-03-01 01:30 UTC
Labels: version/1.13

**Comment by gzcwnk** [comment] 2017-03-01 01:36
thanks that worked.
