### ISSUE TITLE
API: Service list/inspect does not return node

### ISSUE THREAD

**Issue by lukeescude** [docker/docker#31433] opened 2017-02-28 21:45 UTC
Working with the API and Swarm, inspecting a service or listing services on a swarm does not include the node that the service is currently running on.

Could this be included in a future update? Or is there already a mechanism for that, besides just running through all nodes and listing containers?

**Comment by thaJeztah** [comment] 2017-02-28 23:00
A service is not running on a specific node, but is backed by "tasks" (containers); for a service with multiple tasks (`--replicas`), each task can run on a different node. To find the tasks for a service, use the tasks endpoint; https://docs.docker.com/engine/api/v1.26/#tag/Task

**Comment by thaJeztah** [comment] 2017-02-28 23:01
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-02-28 23:01 UTC
Labels: area/api, area/swarm, kind/question
