### ISSUE TITLE
Run causes server to lock up

### ISSUE THREAD

**Issue by vchav73** [docker/docker#14990] opened 2015-07-25 14:42 UTC
Running the line below caused our CentOS 6.6 server to lock up, requiring a hard reset. We were able to replicate the problem on another CentOS 6.6 server.

docker run -t -i wordpress:latest /bin/bash

**Comment by thaJeztah** [comment] 2015-07-25 17:51
Could you please add the requested information? There are a number of issues with CentOS/RHEL 6, some of them depend on the kernel version being used.

Also, be aware that running Docker on CentOS/RHEL 6 is no longer supported by RedHat, and will also be removed from the list of supported systems with the next (1.8) release.

**Comment by vchav73** [comment] 2015-07-25 18:15
docker version:
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0

docker info:
Containers: 23
Images: 71
Storage Driver: devicemapper
 Pool Name: docker-252:1-85220-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.662 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 6.267 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.23.4.el6.x86_64
Operating System: <unknown>
CPUs: 2
Total Memory: 1.826 GiB
Name: Analytics
ID: Y7BO:KHWG:VQYL:B5CU:FF2L:2375:XCQJ:VWOL:Q7VC:BO7X:AIZU:MC5V

uname -a:
Linux Analytics 2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):
KVM

List the steps to reproduce the issue:
1.docker run -t -i wordpress:latest /bin/bash
2.
3.

Describe the results you received: Server locked up and required a hard reset

Describe the results you expected: Wordpress container starts

Provide additional info you think is important:

**Comment by unclejack** [comment] 2016-01-03 11:06
This issue is exactly the same as #15057. The kernel used by the person who has opened that issue is newer than this one.

Please keep in mind that CentOS 6.x and RHEL 6.x are unsupported when it comes to Docker. You might want to upgrade to CentOS 7.x / RHEL 7.x to move to a supported setup.

I'll close this issue now since it's a duplicate of a known to be fixed issue.

**Closed by unclejack** 2016-01-03 11:06 UTC
Labels: area/kernel
