### ISSUE TITLE
Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows.

### ISSUE THREAD

**Issue by laurencefass** [docker/docker#32179] opened 2017-03-28 14:57 UTC
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-03-28 15:15
Thanks for reporting, this looks to be a duplicate of https://github.com/docker/docker/issues/31863, so let me close the issue here

**Closed by thaJeztah** 2017-03-28 15:15 UTC
