### ISSUE TITLE
``Driver overlay failed to remove init filesystem`` error while destroying container

### ISSUE THREAD

**Issue by delcypher** [docker/docker#17661] opened 2015-11-03 19:47 UTC
I recently wrote a script that tries to stress the Docker daemon by doing the following in parallel "create container, start, destroy" where the container is very short lived ( < 1.0 second). it does this using the docker-py bindings.

This was an attempt to find an easy way to reproduce #14203. However I can't seem to reproduce the issue any more but the script seems to trigger another bug that's probably a race condition. Occasionally I will get responses like this from the Docker daemon

```
500 Server Error: Internal Server Error ("b'Cannot destroy container 90df3bce1393b7480e2a87010ad413cb07deb02b3aab536b58159408d760b2bb: Driver overlay failed to remove init filesystem 90df3bce1393b7480e2a87010ad413cb07deb02b3aab536b58159408d760b2bb-init: remove /home/dsl11/docker/overlay/90df3bce1393b7480e2a87010ad413cb07deb02b3aab536b58159408d760b2bb-init/merged: device or resource busy'"
```

The script can be found at  https://github.com/delcypher/docker_aggressive_spawn and can be invoked like this

```
$ ./aggressive_spawn.py 200 -j8 ubuntu:14.04
```

where ``200`` is the number of containers to create (and later destroy), ``8`` is how many jobs to do in parallel and ``ubuntu:14.04`` is the image to create the containers from. The containers simply run the ``sleep`` command for a short random amount of time so any image that has the ``sleep`` binary in it can be used.

Here's some information about my system

```
$ docker info
docker info
Containers: 0
Images: 389
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.3-1-ARCH
Operating System: Arch Linux (containerized)
CPUs: 8
Total Memory: 47.11 GiB
Name: REDACTED
ID: REDACTED
Username: delcypher
Registry: https://index.docker.io/v1/
```

```
$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7-dirty
 Built:        Wed Oct 14 11:17:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7-dirty
 Built:        Wed Oct 14 11:17:02 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ uname -a
Linux icarus.doc.ic.ac.uk 4.2.3-1-ARCH #1 SMP PREEMPT Sat Oct 3 18:52:50 CEST 2015 x86_64 GNU/Linux
````

**Comment by thaJeztah** [comment] 2015-11-05 13:00
Thanks @delcypher! I'll pass this on to the maintainers, perhaps it's useful for them :+1:

**Comment by calavera** [comment] 2015-12-29 23:49
I think this issue was fixed with #18351, we found a similar issue with another concurrent script.

**Comment by thaJeztah** [comment] 2015-12-30 09:31
@delcypher would you be able to test if you're still able to reproduce this on the current master? Note that, due to the new content-addressability changes in docker 1.10, docker will do a migration step of the graph store for existing images the first time it's run, so it's best to try this on a clean host. Also, master builds should not be used on production, just for testing :smile:

**Comment by thaJeztah** [comment] 2016-10-29 06:35
Closing because this should be resolved

**Closed by thaJeztah** 2016-10-29 06:35 UTC
Labels: status/more-info-needed, version/1.8
