### ISSUE TITLE
Will Docker think about adding zeromq support for client and daemon interaction?especially distributing environment

### ISSUE THREAD

**Issue by zhoumingchun** [docker/docker#10337] opened 2015-01-25 14:11 UTC
How about using zeromq for docker ipc and rpc? also support zero-copy ?
I had found the shm system not support persistent for container reboot or loss, as using swap, so how about using mmap alternative?
Thanks

**Comment by unclejack** [comment] 2015-02-02 09:00
@zhoumingchun There are no plans to implement zeromq support right now, but you should be able to write something which runs on the same host as the Docker daemon to do this.

The remote API will be improved in the future, but those improvements might not include zeromq support.

Since this was a question (not a bug) and I've tried to answer it, I'll close this issue now. Please feel free to comment.

**Closed by unclejack** 2015-02-02 09:00 UTC

**Comment by zhoumingchun** [comment] 2015-02-06 12:13
OK,I had got it
Then to the latter question,Did Docker can do something for shm system, for example using mmap?
Thanks
