### ISSUE TITLE
Cannot connect to my remote MySQL from docker

### ISSUE THREAD

**Issue by iori31** [docker/docker#29506] opened 2016-12-18 08:20 UTC
I have a java application which has a connection to remote MySQL DB:
1. The url, port, username, password of remote MySQL is clear.
2. The connection is JDBC and program use c3p0 pool in code.
2. The application is a JAR, it has all packages and CONFIG file inside. 
3. I had already ran it in some LINUX system successfully.

However, it just failed to connect to MySQL when i run it into docker.
1. The docker has the whole java environment. 
2. Other parts of program is fine(port mapping, receiving socket data, etc)
3. No exception about DB connection
4. It just stopped before the connection work(the first SQL execution).

No DB exception at all, so weird.
Could you guys help me?

**Comment by thaJeztah** [comment] 2016-12-18 13:22
The GitHub issue tracker is for reporting bugs and feature requests, and not intended as a general support forum for _using_ docker. For other questions, consider using

- The Docker Support Forums - https://forums.docker.com
- The Docker Community Slack Channel - https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/
- Post a question on StackOverflow, using the Docker tag

When asking the question there, I suggest to provide some more information, as it's not clear from your question what exactly fails, what IP-address/host your application is trying to connect to, etc.

Try to write down a minimal way to reproduce the situation, so that others can help answering your questions.

I'll close this issue here, because this is a support question on _using_ docker, not a bug report or feature request

**Closed by thaJeztah** 2016-12-18 13:22 UTC
