### ISSUE TITLE
how to generate core file in container?

### ISSUE THREAD

**Issue by YuleiXiao** [docker/docker#22897] opened 2016-05-23 08:00 UTC
I want to generate core file when program crash in container, but I can not modify "/proc/sys/kernel/core_pattern" and "/proc/sys/kernel/core_uses_pid".

my container start parameter:
docker run --ulimit core=-1 --privileged --security-opt apparmor:unconfined --cap-add SYS_PTRACE -v /mnt/hdd1:/mnt/hdd1 -h debian234 -u xiaoyulei -it -d --name=xiaoyulei --dns 10.72.255.100 --dns 10.72.55.103 --dns 10.98.48.39 debian:my /bin/bash

docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

**Comment by thaJeztah** [comment] 2016-05-23 09:29
Looks like this is a duplicate of https://github.com/docker/docker/issues/11740, please continue the discussion on that issue, thanks!

**Closed by thaJeztah** 2016-05-23 09:29 UTC
Labels: kind/question, version/1.11
