### ISSUE TITLE
Allow selection of network (--net=...) when building the image

### ISSUE THREAD

**Issue by padcom** [docker/docker#9805] opened 2014-12-24 10:53 UTC
In some rare circumstances it is required to bind the intermediate containers to the host network due to restrictions on network interfaces. For example when using ShrewSoft VPN client the tap0 interface does not route packets from other hosts for security reasons which basically makes Docker unusable in those kinds of corporate environments.

Allowing the container to use host network (--net=host) solves that problem.

**Comment by jfrazelle** [comment] 2015-02-26 23:04
duplicate of https://github.com/docker/docker/issues/10324

**Closed by jfrazelle** 2015-02-26 23:04 UTC
