### ISSUE TITLE
Cannot install 1.9.0~dev~git20151006 on Jessie

### ISSUE THREAD

**Issue by chanwit** [docker/docker#16847] opened 2015-10-08 12:33 UTC
I cannot install the following build on Debian Jessie (DigitalOcean image) 
(via `curl https//experimental.docker.com`).

http://apt.dockerproject.org/repo/pool/experimental/d/docker-engine/docker-engine_1.9.0~dev~git20151006.052310.0.1529343-0~jessie_amd64.deb

But everything is fine including network, after rolling back to 1.9.0~dev~git20151005:

http://apt.dockerproject.org/repo/pool/experimental/d/docker-engine/docker-engine_1.9.0~dev~git20151005.173956.0.0339ed7-0~jessie_amd64.deb

Cannot show any `docker info` because I just could not install it.

**Comment by thaJeztah** [comment] 2015-10-08 14:28
Was able to reproduce; copy/pasted some output/logs;
https://gist.github.com/thaJeztah/14f70a7b05d173a8bc52

/cc @jfrazelle

**Comment by jfrazelle** [comment] 2015-10-08 14:45
This looks to be a problem with experimental in general not the debs can you run the static binary

**Comment by thaJeztah** [comment] 2015-10-08 14:47
Hold on, think I've got that droplet still running

**Comment by thaJeztah** [comment] 2015-10-08 14:51
seems to do at least start
```
./docker -v
Docker version 1.9.0-dev, build 1529343, experimental

./docker daemon
WARN[0000] Running experimental build                   
INFO[0000] Option DefaultDriver: bridge                 
INFO[0000] Option DefaultNetwork: bridge                
WARN[0000] Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.
insmod /lib/modules/3.16.0-4-amd64/kernel/net/llc/llc.ko 
insmod /lib/modules/3.16.0-4-amd64/kernel/net/802/stp.ko 
insmod /lib/modules/3.16.0-4-amd64/kernel/net/bridge/bridge.ko 
, error: exit status 1 
INFO[0000] Firewalld running: false                     
WARN[0000] Your kernel does not support cgroup memory limit: mountpoint for memory not found 
WARN[0000] Your kernel does not support cgroup cfs period 
WARN[0000] Your kernel does not support cgroup cfs quotas 
INFO[0000] Loading containers: start.                   

INFO[0000] Loading containers: done.                    
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=1529343 execdriver=native-0.2 graphdriver=aufs version=1.9.0-dev
INFO[0000] API listen on /var/run/docker.sock           
^CINFO[0005] Processing signal 'interrupt'

**Comment by jfrazelle** [comment] 2015-10-08 14:51
Regardless there will be new debs in about 5 hours anyways :p

**Comment by jfrazelle** [comment] 2015-10-08 14:51
For experimental

**Comment by thaJeztah** [comment] 2015-10-08 14:52
:-) probably not worth the hassle for now

**Comment by jfrazelle** [comment] 2015-10-08 14:52
From the other logs it looks like the systemd service is hanging so maybe we changed something there :/

**Comment by jfrazelle** [comment] 2015-10-08 19:16
New debs were pushed can you try






On Thu, Oct 8, 2015 at 7:53 AM -0700, "Sebastiaan van Stijn" <notifications@github.com> wrote:












:-) probably not worth the hassle for now

**Comment by jfrazelle** [comment] 2015-10-08 19:16
Thanks !






On Thu, Oct 8, 2015 at 7:53 AM -0700, "Sebastiaan van Stijn" <notifications@github.com> wrote:












:-) probably not worth the hassle for now

**Comment by jfrazelle** [comment] 2015-10-08 20:11
ugh I hate the microsoft outlook app for doing emails to gh wrong, actually i bet i can file bug w github

**Comment by thaJeztah** [comment] 2015-10-08 21:29
\o/ just tested, installing experimental worked. Thanks!

Is it good, otherwise, the outlook app? (never used it on iOS) :smile:

@chanwit I'll proceed and close this issue, but ping us if it doesn't work for you

**Closed by thaJeztah** 2015-10-08 21:29 UTC

**Comment by jfrazelle** [comment] 2015-10-08 21:31
yeah its great I would fix the comments but i want to use them as an
example ;)

**Comment by chanwit** [comment] 2015-10-09 06:03
Thank you. I check it and get back to you if there is any problem.
