### ISSUE TITLE
snmpd service not running on Ubuntu when installed using docker 

### ISSUE THREAD

**Issue by HarshaYeluru** [docker/docker#32224] opened 2017-03-30 10:02 UTC
Hi,

I am trying to install snmpd service in Ubuntu OS using docker. This is my dockerfile:

```
From ubuntu
RUN apt-get -y update && apt-get install -y snmpd
CMD service snmpd restart
CMD service snmpd status
```

When I am building the docker file, it is built successfully but when I am running the image, the container created is showing that the service is not running.
However, when I tried restarting it manually, it's working fine. 

Below is the output for the file:

```
tcskvis@01HW735292 MINGW64 ~/ubuntu
$ docker build -t ubuntu_img .
Sending build context to Docker daemon 2.048 kB
Step 1/4 : FROM ubuntu
 ---> 0ef2e08ed3fa
Step 2/4 : RUN apt-get -y update && apt-get install -y snmpd
 ---> Using cache
 ---> 5f33942a2f8c
Step 3/4 : CMD service snmpd restart
 ---> Using cache
 ---> 6f3cf32978f8
Step 4/4 : CMD service snmpd status
 ---> Using cache
 ---> 56936e6a81a0
Successfully built 56936e6a81a0
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x'
permissions. It is recommended to double check and reset permissions for sensitive files and directories.

tcskvis@01HW735292 MINGW64 ~/ubuntu
$ docker run -it ubuntu_img /bin/bash
root@e36726bff9a6:/# service snmpd status
 * snmpd is not running
root@e36726bff9a6:/# service snmpd restart
 * Restarting SNMP services:                                                                                                                                    snmpd[30]:
 Created directory: /var/lib/snmp/mib_indexes

snmpd[30]: /etc/snmp/snmpd.conf: line 145: Warning: Unknown token: defaultMonitors.

snmpd[30]: /etc/snmp/snmpd.conf: line 147: Warning: Unknown token: linkUpDownNotifications.

snmpd[30]: Turning on AgentX master support.

snmpd[30]: Created directory: /var/agentx

root@e36726bff9a6:/# service snmpd status
 * snmpd is running
root@e36726bff9a6:/#

```

Am I doing something wrong here? Can someone please help me out?

Thanks in advance...!!!

**Comment by thaJeztah** [comment] 2017-03-30 11:16
containers are not VM's; a container is a "sandbox" to run a _single_ main process. That process is defined by the `CMD`, and is executed when the container is started.

In your case, the Dockerfile has multiple `CMD` lines, and the latter will overwrite the former, so when starting the container, `service snmpd status` is executed, and the container stops when that command completes.

If you want to run _multiple_ services in a single container (think if this is _really_ what you want, please read this blog https://blog.docker.com/2016/03/containers-are-not-vms/), you need to run an init / supervisor system in your container that acts as the main process, and starts sub-processes (e.g. https://docs.docker.com/engine/admin/using_supervisord/), if you want to run `systemd` as init system inside the container, you need a lot more configuration, because `systemd` requires additional privileges (which _is_ possible, but make your container less secure)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-30 11:16 UTC
Labels: area/builder

**Comment by HarshaYeluru** [comment] 2017-03-30 13:13
Hi @thaJeztah 

But when I remove the last line (i.e. service snmpd status) and keep service snmpd restart as my last command, from what you said, service should be restarted and be in running state. But even in that case, snmpd is showing not running. 

this is the output I get when running with service snmpd restart command:

```
tcskvis@01HW735292 MINGW64 ~/ubuntu
$ cat Dockerfile
From ubuntu
RUN apt-get -y update && apt-get install -y snmpd
CMD service snmpd restart
#CMD service snmpd status

tcskvis@01HW735292 MINGW64 ~/ubuntu
$ docker build -t ubuntu_img .
Sending build context to Docker daemon 2.048 kB
Step 1/3 : FROM ubuntu
 ---> 0ef2e08ed3fa
Step 2/3 : RUN apt-get -y update && apt-get install -y snmpd
 ---> Using cache
 ---> 5f33942a2f8c
Step 3/3 : CMD service snmpd restart
 ---> Using cache
 ---> 6f3cf32978f8
Successfully built 6f3cf32978f8
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x'
permissions. It is recommended to double check and reset permissions for sensitive files and directories.

tcskvis@01HW735292 MINGW64 ~/ubuntu
$ docker run -it ubuntu_img /bin/bash
root@284f1e2093e6:/# service snmpd status
 * snmpd is not running
root@284f1e2093e6:/#
```
