### ISSUE TITLE
Ubuntu deb doesn't start docker after installation

### ISSUE THREAD

**Issue by andrenarchy** [docker/docker#15620] opened 2015-08-16 15:37 UTC
When installing docker according to the [docs](https://docs.docker.com/installation/ubuntulinux/#installation) on Ubuntu 14.04, docker isn't started automatically and running `hello-world` fails. The problem is well-known and updates to the docs have been proposed in #15368, #14576, #14883, #12429 and #12427. All PRs have been closed with the argument that the issue cannot be reproduced. 

However, it can be reproduced easily with a fresh and up-to-date installation of Ubuntu 14.04.3 (64 bit) in a VM. Steps to reproduce after installing Ubuntu:
```
andre@andre-vm:~$ curl -sSL https://get.docker.com/ | sh
[...]
andre@andre-vm:~$ sudo docker run hello-world
Post http:///var/run/docker.sock/v1.20/containers/create: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```
The fix is simple:
```
andre@andre-vm:~$ sudo service docker start
docker start/running, process 6515
```
Then the `hello-world` image works:
```
andre@andre-vm:~$ sudo docker run hello-world
[...]
Hello from Docker.
This message shows that your installation appears to be working correctly.
[...] 
```
<hr>
**Note:** please merge #15368 (adds `sudo service docker start` to the docs) until the issue is actually fixed in the debs. Otherwise, users will continue to waste their time with the docker debs.
<hr>
Further information:
```
andre@andre-vm:~$ sudo docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
 
Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
andre@andre-vm:~$ sudo docker info
Containers: 1
Images: 2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 993.3 MiB
Name: andre-vm
ID: X3QR:KN7T:S3ME:HAP6:543E:RBXF:NAT7:E2VO:7BQ3:5UXS:QIKF:ASN7
WARNING: No swap limit support
andre@andre-vm:~$ uname -a
Linux andre-vm 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by etopian** [comment] 2015-08-17 08:19
It may be you are running the wrong kernel for AUFS which is not supported by your kernel version. Downgrade your kernel or switch to a different storage-driver

edit /etc/default/docker
DOCKER_OPTS="--userland-proxy=false --storage-driver=overlay"

Try restarting Docker. If it works, that's the problem

**Comment by rmurrish** [comment] 2015-08-21 04:43
Can reproduce in ubuntu 14.04 lts

Also, thx @andrenarchy for providing the fix. Helped me get an installation running :+1:

**Comment by MathiasRenner** [comment] 2015-08-22 11:58
Can confirm this issue and the solution with the easy fix as supposed by @andrenarchy (Thank you!)

**Comment by frehner** [comment] 2015-08-23 21:22
Reproduced this on a newly-upgraded 14.04 lts. Thanks for the solution. 

Honestly, is there any reason why this shouldn't be added to the docs?  As mentioned above, if it's already running it won't do anything, and if it's not then it'll save that person time.

**Comment by srikanteswartalluri** [comment] 2015-08-26 17:02
This info saved my time.

**Comment by martinhbramwell** [comment] 2015-08-28 13:52
4wiw ... ran into this in a KVM virtual machine running Xubuntu 14.04, with some other projects already installed.  Simply rebooting is another solution.  It also enabled me to run ```docker run hello-world``` **without** sudo.

**Comment by brunano21** [comment] 2015-08-30 10:07
thanks a lot! `sudo service docker start`

**Comment by saurabhmaurya06** [comment] 2015-09-02 07:24
Thanks a lot! I was having the same issue. It would be great if it's added to the documentation instead of us having to Google for it.

**Comment by shi2rs** [comment] 2015-09-02 17:40
Lucky to find this thread in few minutes of trying it out..

**Comment by gustavopolitano** [comment] 2015-09-03 00:31
Thanks for the info. I had the same problem here.

**Comment by jaimenadal** [comment] 2015-09-04 15:26
Thank you "andrenarchy". I had exactly the same issue with that. :+1:

**Comment by Goyusuf** [comment] 2015-09-05 07:27
Thank you perfecto!

**Comment by braniti** [comment] 2015-09-11 09:11
thank you , got same issue today .   You  saved me a lot  of time .

**Comment by vmishra705** [comment] 2015-09-11 13:32
I have installed Boot2Docker on Windows 8.1 VDI(Virtual System). However after that when I try to execute "Docker run hello-world" on the boot2docker instance, I get the following error

Post http://127.0.0.1:2375/v1.20/containers/create: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it..
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

I tried implementing the solution mentioned above. But none of the commands are available from the command prompt. For example - 

$ sudo
bash: sudo: command not found
$ service docker start
bash: service: command not found

**Comment by cpuguy83** [comment] 2015-09-11 14:00
I installed docker 1.8.2 on a fresh ubuntu VM this morning via `curl https://get.docker.com | sh` and docker was started automatically.
Closing. If you find there is still an issue please ping so we can address, but I think this is resolved.

@vmishra705 This is not related in any way. This issues is about the ubuntu deb package.
For support getting your setup working, please ping on #docker on IRC, forums.docker.com, or the docker-user mailing list. Thanks!

**Closed by cpuguy83** 2015-09-11 14:00 UTC

**Comment by dhbradshaw** [comment] 2015-09-13 02:29
Thank you so much andrenarchy.  Docker wouldn't start on Ubuntu 14.04 and this showed the way.

**Comment by Vivi-wu** [comment] 2015-09-15 03:40
Thank you very much. This fix my problem.
sudo service docker start
sudo docker run hello-world

And also thanks for your nice information:
sudo docker version
sudo docker info

**Comment by elanperach** [comment] 2015-09-15 05:37
+1

**Comment by sarjeet2013** [comment] 2015-09-18 20:10
+1. that fixed it. (sudo service docker start)

**Comment by truckingsim** [comment] 2015-09-19 20:36
Still not starting automatically for me after installing through curl.  Had to do `sude service docker start`.

**Comment by Sarseth** [comment] 2015-09-21 12:08
+1. But still instructions are missleading. Shouldnt be they fixed if ticket is closed?

**Comment by MathieuDreano** [comment] 2015-09-21 17:27
#### The fix doesn't work in my case : Windows10
    Mathieu@PORT-MATHIEU MINGW64 ~
    $ docker run hello-world
    Post http://127.0.0.1:2375/v1.20/containers/create: dial tcp 127.0.0.1:2375: ConnectEx tcp: Aucune     connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée..
    * Are you trying to connect to a TLS-enabled daemon without TLS?
    * Is your docker daemon up and running?

    Mathieu@PORT-MATHIEU MINGW64 ~
    $ sudo service docker start
    bash: sudo: command not found
@vmishra705 Did you fix it ?

**Comment by sexyHaxXx0rboi88** [comment] 2015-09-22 13:12
Same problem. Fix worked for me. Thank you.

**Comment by pkanane** [comment] 2015-09-26 18:46
Thank you. I believe this should be in the installation instructions. Very reproducible.. trust me

**Comment by paronsson** [comment] 2015-10-02 03:42
The problem still persist. Either the instructions or the installation should be changed. Why confuse new users of Docker for no reason?

**Comment by lexigen** [comment] 2015-10-03 04:20
Fix worked, thank you.

**Comment by andrenarchy** [comment] 2015-10-03 13:55
Please reopen the issue, it's not fixed.

@cpuguy83 what version of Ubuntu did you use?

**Comment by Fr0ntich** [comment] 2015-10-07 08:04
thx @andrenarchy for providing the fix. Helped me get an installation running :+1:

**Comment by shookees** [comment] 2015-10-07 09:04
Not fixed, did happen on updated Ubuntu 14.04.

**Comment by Larsouille** [comment] 2015-10-08 13:51
Thanks for the fix, work on Fedora 22.

**Comment by thaJeztah** [comment] 2015-10-28 09:23
For those following this, PR https://github.com/docker/docker/pull/15368 was merged, and updated docs will be published together with the 1.9 release

**Comment by hasanoruc** [comment] 2016-01-04 13:59
hello there.
i found my own solution.
maybe helps you.

first type sudo nano /etc/init/docker.conf
and enter docker configuration file.
and here two DOCKER_OPTS= line.
first is will be empty.

’-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock’
link is the second DOCKER_OPTS= line.

and docker run hello-world command is fine and output is..
Hello from Docker......

**Comment by thaJeztah** [comment] 2016-01-04 14:03
@hasanoruc please see the updated instructions in https://github.com/docker/docker/pull/15368/files

Also, port 4243 is the *old* port for docker (2375 and 2376 are the new ports), and you should *never* expose the API unprotected on a publicly accessible IP-address. Doing so is giving root access to your machine to anyone that's able to access that port.

**Comment by hasanoruc** [comment] 2016-01-04 14:09
@thaJeztah ok. i dont read this. thanks
