### ISSUE TITLE
Docker remote api (1.24)

### ISSUE THREAD

**Issue by geostant** [docker/docker#28979] opened 2016-11-30 08:12 UTC
**Steps to reproduce the issue:**
1. Send a REST API request to pull a non exist image from a private registry

**Describe the results you received:**
200 OK and raw response:
'''{"status":"Pulling repository nexus.example.com:5000/some_image"}
{"errorDetail":{"message":"Error: image some_image:1.0.0 not found"},"error":"Error: some_image:1.0.0 not found"}'''

**Describe the results you expected:**
HTTP 404 response

**Comment by cpuguy83** [comment] 2016-11-30 17:18
Can you provide more details?
The full issue template should be filled in.

At the moment I'm not 100% sure what the issue is.

**Comment by geostant** [comment] 2017-02-13 14:29
@cpuguy83 Where can I find the template ?

Our problem is that docker remote api always response with status code 200 to requests
we expect it to response with other response codes to specific situations - in example:
if I trying to pull an image with docker remote api and the image can't be found in the repository it would be great it it can response with status code 404 (not found) and not 200.

This will make our life much easier.


Thanks

**Comment by cpuguy83** [comment] 2017-02-13 14:30
**Description**



**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**


**Describe the results you expected:**


**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-03-21 16:44
Closing because we didn't receive the requested information

**Closed by thaJeztah** 2017-03-21 16:44 UTC
Labels: status/more-info-needed
