### ISSUE TITLE
Port conflict detection should be done synchronously on a manager

### ISSUE THREAD

**Issue by tiborvass** [docker/docker#24134] opened 2016-06-29 19:02 UTC
A specific issue for the more general https://github.com/docker/docker/issues/23706

**Comment by mrjana** [comment] 2016-06-29 19:12
@tiborvass https://github.com/docker/swarmkit/pull/1088 address this issue. The service will not be schedulable until the conflict is resolved. IMO we should not reject desired state mutations based on the current cluster state especially since it is not fatal. Once the conflict is resolved the service becomes schedulable. What we need  is probably a better state (than task state `NEW`) like `ALLOCATING` to address this

**Comment by stevvooe** [comment] 2016-06-29 21:27
@mrjana This has nothing to do with allocation. We can reject it because the desired state is irreconcilable without user action and detectable without querying cluster state.

cc @aanand

**Comment by mrjana** [comment] 2016-06-29 21:39
@stevvooe If the desired state is irreconcilable then yes. But if there is a `PublishedPort` conflict it is not entirely irreconcilable.

**Comment by stevvooe** [comment] 2016-06-29 22:25
> But if there is a PublishedPort conflict it is not entirely irreconcilable.

How?

**Comment by mrjana** [comment] 2016-06-29 22:37
When the service which was holding the port gets removed.

**Comment by aanand** [comment] 2016-06-29 22:48
Is that desirable behaviour, though? Considering the user experience, I'd much rather know that there's a conflict as soon as I try to create the second service. Currently (as I understand it), the service gets created but the containers don't start, and I have to go digging to find out what the problem is.

**Comment by cpuguy83** [comment] 2016-07-19 13:04
docker/swarmkit#1188

**Comment by mavenugo** [comment] 2016-07-25 04:20
Resolved via #24237

**Closed by mavenugo** 2016-07-25 04:20 UTC
Labels: area/swarm, priority/P1
