### ISSUE TITLE
Issue to build with docker for mac

### ISSUE THREAD

**Issue by matthieu-robin** [docker/docker#25947] opened 2016-08-23 06:01 UTC
**Output of `docker version`:**
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 23
 Running: 0
 Paused: 0
 Stopped: 23
Images: 34
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 78
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: HFPE:647P:UABP:374J:QOCP:4SZS:PVGQ:KMF2:SJMN:5ZDV:OJIX:ESJK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2016-08-23T05:57:02.418524691Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: matthieurobin
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

MacBookPro with Docker for Mac

**Steps to reproduce the issue:**
1. create a DockerFile
2. cd /Path/of/the/dockerfile/
3. docker build -t xxx
_Matthieu-Mac-8:dockerbuild matthieu$ docker build -t xxx
"docker build" requires exactly 1 argument(s).
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile_

or docker build -t xxx  DockerFile 
_unable to prepare context: context must be a directory: /Users/matthieu/dockerbuild/DockerFile_

this build command works:
docker build -t centreon - < Dockerfile

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment] 2016-08-23 08:28
You need to use `docker build .` or `docker build -t name .` The dot indixates the current directory. Or you can do `docker build path/to/dockerfile` (but not the Dockerfile itself, the directory it is in).

**Comment by justincormack** [comment] 2016-08-23 08:30
Closing this as it is not a bug, but you can continue to ask questions. You might want to read the getting started guides eg https://docs.docker.com/engine/userguide/intro/

**Closed** 2016-08-23 09:48 UTC
Labels: version/1.12

**Comment by matthieu-robin** [comment] 2016-08-24 06:31
Hi Justin,

Thanks for your answer, but it really doesn't work. Please have a look:
![cap 2016-08-24 a 08 30 10](https://cloud.githubusercontent.com/assets/10330979/17920473/0276b15e-69d5-11e6-94fd-5dc48a1d18d0.png)

And here is the Dockerfile content:
FROM centos:centos6
MAINTAINER matthieu-robin

# Update CentOS
RUN yum -y update
RUN yum -y install wget


# Install Centreon Repository
RUN wget http://yum.centreon.com/standard/3.0/stable/ces-standard.repo -O /etc/yum.repos.d/ces-standard.repo

# Install Maria-DB
RUN yum --nogpg -y install MariaDB-server
RUN /etc/init.d/mysql start

# Install ssh
RUN yum -y install openssh-server openssh-client
RUN mkdir /var/run/sshd
RUN echo 'root:centreon' | chpasswd
RUN sed -i 's/^#PermitRootLogin/PermitRootLogin/g' /etc/ssh/sshd_config
RUN /etc/init.d/sshd start && /etc/init.d/sshd stop

# Install Centreon
RUN yum --nogpg -y install centreon-base-config-centreon-engine centreon

# Install Supervisor
RUN /bin/rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
RUN yum -y install python-setuptools
RUN easy_install supervisor
RUN mkdir -p /var/log/supervisor
ADD scripts/supervisord.conf /etc/supervisord.conf

EXPOSE 22 80
CMD ['/usr/bin/supervisord', '--configuration=/etc/supervisord.conf']

If you could help me, thanks. (my Dockerfile is probably wrong, I'm making test)
