### ISSUE TITLE
Upgrade from 1.6.1 to 1.9.1 fails

### ISSUE THREAD

**Issue by noelmcgrath** [docker/docker#19919] opened 2016-02-02 13:37 UTC
I am upgrading from 1..6.1 to 1.9.1 on a ubuntu 12.04 host
Following are the steps
Check 1.9.1 in cache
  apt-cache showpkg lxc-docker
Upgrade
   apt-get install lxc-docker
Check running and version
  status docker
  docker --version
All good and version is 1.9.1
Check containers
  docker ps 
All back running

BUG REPORT INFORMATION
In my case I am running grafana, statsd and graphite and noticed no metrics being sent to statsd
So  I started by pinging the host and it is unreachable since upgrade
Reverted back to VM snapshot and host is ok
So it appears the upgrade is having an effect on the host
Any reason for this behaviour?

**Comment by programmerq** [comment] 2016-03-31 01:25
Is this issue something that is still affecting you? Can you include more details about how one might reproduce this? Specifically, how is your grafana/statsd/graphite setup affected after the upgrade?

**Comment by thaJeztah** [comment] 2016-10-27 01:10
I'm closing this, because we didn't receive more information to go on

**Closed by thaJeztah** 2016-10-27 01:10 UTC
Labels: kind/question
