### ISSUE TITLE
how to feed an "ENTER" to my RUN during an image build

### ISSUE THREAD

**Issue by kunapuli09** [docker/docker#12286] opened 2015-04-10 23:15 UTC
I have to do an install inside my docker container through a silent script, my install program expects user to enter an "F" Or "Enter" on the terminal at the end to finish the install. My docker build stops with printing line Enter:  [ F ] ?  and returns with return code of 1.

Here is my RUN inside my Dockerfile. 

RUN /bin/bash -c -l "cd $INSTALL_HOME \
                        && java -jar INSTALLER_LATEST.jar -console -readScript install.script -server xxx -installDir $INSTALL_HOME"

How do a feed F?

**Comment by duglin** [comment] 2015-04-10 23:21
Try
RUN echo F | bash ...

-Doug

**Comment by duglin** [comment] 2015-04-10 23:23
Actually wrap the entire bash with( )

-Doug

**Comment by thaJeztah** [comment] 2015-04-10 23:26
Hi, @kunapuli09 the GitHub issue tracker is meant for tracking bugs and feature requests, not for support questions. https://forums.docker.com, https://groups.google.com/forum/#!forum/docker-user and the #docker IRC channel are more suitable for that.

I'm gonna close this issue, because this is not a bug, but feel free to continue the discussion

**Closed by thaJeztah** 2015-04-10 23:26 UTC

**Comment by kunapuli09** [comment] 2015-04-10 23:28
ok..thanks. apologies for posting here. will chase it in forums..

**Comment by thaJeztah** [comment] 2015-04-10 23:43
@kunapuli09 no problem!  Mainly closing so that it's easier to track which issues needs to be resolved.

Hope you'll be able to get it working, good luck!
