### ISSUE TITLE
Markdown syntax problems in manpages

### ISSUE THREAD

**Issue by DanLipsitt** [docker/docker#10667] opened 2015-02-09 20:41 UTC
There are errors in the manpages because parameters in angle brackets aren't included in `md2man` output. For [example][], 
```
**ADD ["<src>"... "<dest>"]** This form is required for paths containing whitespace.
```
renders as
```
ADD [""... ""] This form is required for paths containing whitespace.
```
Note the missing `<src>` and `<dest>`.
This can also be seen in GitHub's rendering of the text:

**ADD ["<src>"... "<dest>"]** This form is required for paths containing whitespace.

[example]: https://github.com/docker/docker/blame/master/docs/man/Dockerfile.5.md#L137

--------------
**PROBLEM**: man docs are often imporoperly formatted, using quotes or bolds when code blocks/segments are required

**PROPOSED SOLUTION**: man docs should be updated to use appropriate backticks for either inline or blocked code.
The `dockerfile.5.md` has already been gone through, but wouldn't hurt another set of eyes.

**Comment by jfrazelle** [comment] 2015-02-09 21:02
ping @cpuguy83

**Comment by cpuguy83** [comment] 2015-02-09 21:08
Thanks, let me take a look.

**Comment by tianon** [comment] 2015-02-09 21:34
Since this isn't fixed in docker/docker yet, I think it's appropriate that we leave this open. :wink:

**Comment by cpuguy83** [comment] 2015-02-09 21:35
Sorry, didn't realize GH would auto-close :)

**Comment by cpuguy83** [comment] 2015-02-09 21:37
btw, I don't like the fix I put in since it's perfectly valid to use raw html in MD, but I think it's better than not rendering anything at all.

**Comment by DanLipsitt** [comment] 2015-02-09 21:45
What happens if you use backticks to protect the params (`<foo>`)? Sorry I don't have time to experiment right now.

**Comment by thaJeztah** [comment] 2015-02-09 21:45
Is using `<something>` the standard way to notate things in *man-pages*, or a convention that *Docker* uses?

Asking, because the same problem occurred on a couple of pages of the documentation as well; the values did not show up on GitHub when viewing the docs.

If it is not a standard notation in man-pages, perhaps Docker should use a different convention in stead of modifying md2man, because other MarkDown renderers have the same problem.

**Comment by cpuguy83** [comment] 2015-02-09 21:48
@thaJeztah It's pretty common when writing CLI docs to use `<something>` as a way to indicate a required argument (vs `[something]` as not required)

**Comment by duglin** [comment] 2015-02-09 22:25
can md2man be made to support \&lt; and \&gt; ?

**Comment by cpuguy83** [comment] 2015-02-09 22:30
@duglin Can you open an issue on the repo with what you expect it to output?

**Comment by thaJeztah** [comment] 2015-02-09 22:35
@cpuguy83 thanks for explaining.

> btw, I don't like the fix I put in since it's perfectly valid to use raw html in MD, but I think it's better than not rendering anything at all.

Looking at the [man-page](https://github.com/docker/docker/blob/master/docs/man/Dockerfile.5.md#L137) on GitHub, the pages look mangled as well. I think the problem overall is that they use a bit of a "MarkDown-*ish*" syntax; everything is assumed to be "`<pre>`" and only a sub-set of MarkDown (Head (`#`), bold and italic) is used. 

I think from that perspective, it's reasonable to not support HTML?

**Comment by tianon** [comment] 2015-02-09 22:39
Yeah, I tend to agree that this looks like a bug in our use of Markdown
here, not a bug in go-md2man.

**Comment by thaJeztah** [comment] 2015-02-09 22:54
Perhaps call it MarkDown-flavoured plain-text, and change the file extension to .txt, to make it better readable on GitHub as well.

**Comment by duglin** [comment] 2015-02-10 14:31
Opened issue in md2man: https://github.com/cpuguy83/go-md2man/issues/11

**Comment by jfrazelle** [comment] 2015-02-28 03:38
so what was the outcome here @cpuguy83 can you triage and add the right labels so someone can contribute it to fix it if they see this issue

**Comment by cpuguy83** [comment] 2015-02-28 12:12
Triaged

**Comment by cpuguy83** [comment] 2015-09-15 14:34
Closing since these man pages were updated.
If anyone sees a specific problem, please open a new issue with that specific problem.

Thanks!

**Closed by cpuguy83** 2015-09-15 14:34 UTC
Labels: exp/beginner, kind/docs
