### ISSUE TITLE
v2 auth fails if version check endpoint is unauthenticated

### ISSUE THREAD

**Issue by etuttle** [docker/docker#12972] opened 2015-05-04 21:37 UTC
I'm trying to set up a v2 repository which allows anonymous read access but requires basic auth for POST or PUT.  I set up an nginx proxy which sends a basic auth challenge depending on the $request_method.

When pushing to this repo, docker tries a PUT to `/v2/<name>/manifests/<ref>`, gets a 401 back, and prompt me for my credentials.  But after entering credentials, it hits `/v2/` with a GET and then fails because there was no auth challenge:

```
FATA[0012] Error response from daemon: no successful auth challenge for https://<repo>/v2/ - errors: [] 
```

The work-around is to manually create a ~/.dockercfg file for clients that need to push.

Docker version: 1.6.0
Registry version: distribution-2.0.0

**Comment by frconil** [comment] 2015-07-08 00:34
I seem to have a similar problem just trying to log to the server myself:

```
docker login contyard
Username: fconil
Password:
Email: fconil@
Error response from daemon: no successful auth challenge for https://contyard/v2/ - errors: []
```

**Comment by liubin** [comment] 2015-08-09 07:05
The same?


```
Username: testuser
Password: 
Email: aaa@aaa.net
Error response from daemon: no successful auth challenge for https://private-registry.com:5043/v2/ - errors: [Get https://private-registry.com:5043/v2/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"]
```

Docker 1.7.1 and Registry V2

**Comment by dylanvorster** [comment] 2015-08-20 09:08
Same problem here Docker version 1.8.1, build d12ea79 and V2 Registry

Cant use a dockercfg because it keeps complaining that the file is invalid, and it is 100% valid JSON.

@liubin the format i assume is like the one stipulated here https://coreos.com/os/docs/latest/registry-authentication.html

**Comment by dmp42** [comment] 2015-08-20 18:12
All: did you configure your registry using nginx or apache as a proxy?
If so, why disable auth for /v2?

**Comment by dylanvorster** [comment] 2015-08-20 18:34
update:
At first I was not using a proxy for the registry, and thats where the problem came in. After running it behind the proxy as suggested by one of the docker guides (as an alternative approach), then it works.

When I was still trying to run the auth through the registry itself (aka not using the proxy), I cannot recall disabling auth for V2 anywhere (is that even a configuration option?)

**Comment by dmp42** [comment] 2015-08-20 20:35
@dylanvorster https://github.com/docker/distribution/blob/master/docs/deploying.md#restricting-access should be working without issues.
If there is a problem with it, give me a ping so we fix it.

**Comment by rhansen** [comment] 2016-01-30 05:05
:+1:

**Comment by tallandtree** [comment] 2016-09-12 08:36
I have exactly the same issue as @etuttle. We run apache proxy in front of docker registry.
Docker 1.9.1, Docker API 1.21, registry 2.2.1, Apache 2.4.

If I want to allow anonymous pull access, I cannot push or login to the registry (via the apache proxy):

Part of my apache configuration:
```
       <Location /v2>
                ProxyPass        http://registry:5000/v2
                ProxyPassReverse http://registry:5000/v2
                # Read access to anonymous users
                <Limit GET HEAD>
                        Require all granted
                </Limit>
                # Write access to specific users only
                <Limit POST PUT DELETE PATCH>
                        Require user user1 user2 user3
                </Limit>
        </Location>
```
Error on login:
```
$ docker login myregistry1.mydomain.org
Username (user1): 
Error response from daemon: no successful auth challenge for https://myregistry.mydomain.org/v2/ - errors: []
```
Pull is successfull.
When I change 'Require all granted' to Require valid-user, I can push and pull, but always need to authenticate, even for pull. But we want to allow anonymous pull.

**Comment by thaJeztah** [comment] 2016-09-27 18:15
This is a duplicate of https://github.com/docker/docker/issues/17317, and (see https://github.com/docker/docker/issues/17317#issuecomment-248151923) this is being tracked in https://github.com/docker/distribution/issues/1028, so I'm closing the issue here

**Closed by thaJeztah** 2016-09-27 18:15 UTC
Labels: area/distribution
