### ISSUE TITLE
Unable to get Docker Server running again with Overlayfs "FATA[0001] is a directory"

### ISSUE THREAD

**Issue by pizzarabe** [docker/docker#23763] opened 2016-06-20 11:53 UTC
After restarting my docker deamon on Centos 7.2 I am not able to get the daemon running again..

```
docker daemon
INFO[0000] [graphdriver] using prior storage driver "overlay" 
INFO[0000] Firewalld running: false                     
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.1/16. Daemon option --bip can be used to set a preferred IP address 
INFO[0000] Loading containers: start.                   
.............WARN[0001] exit status 1                                
WARN[0001] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/62541cf723103426429d79edba68ca47844b805517842960e44c22d81978f637/shm: invalid argument
failed to umount /var/lib/docker/containers/62541cf723103426429d79edba68ca47844b805517842960e44c22d81978f637/mqueue: invalid argument 
ERRO[0001] Failed to start container 62541cf723103426429d79edba68ca47844b805517842960e44c22d81978f637: [8] System error: not a directory 

INFO[0001] Loading containers: done.                    
FATA[0001] is a directory                               
[root@ooffice-test ~]# man docker daemon 
[root@ooffice-test ~]# docker daemon -D
INFO[0000] [graphdriver] using prior storage driver "overlay" 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using default logging driver json-file       
DEBU[0000] Creating images graph                        
DEBU[0000] Restored 87 elements                         
DEBU[0000] Creating repository list                     
DEBU[0000] Option DefaultDriver: bridge                 
DEBU[0000] Option DefaultNetwork: bridge                
INFO[0000] Firewalld running: false                     
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D OUTPUT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -F DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -X DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -N DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[0000] Registering ipam provider: default           
DEBU[0000] Releasing addresses for endpoint mad_jepsen's interface on network bridge 
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.4) 
DEBU[0000] Releasing addresses for endpoint onlyoffice-document-server's interface on network bridge 
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.3) 
DEBU[0000] Releasing addresses for endpoint onlyoffice-mail-server's interface on network bridge 
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.5) 
DEBU[0000] releasing IPv4 pools from network bridge (3416b98f87cccf12ea19ce62a98ce0e1e42e437d7b36b37872b2c4f8234b5d81) 
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.1) 
DEBU[0000] ReleasePool(LocalDefault/172.17.0.0/16)      
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.1/16. Daemon option --bip can be used to set a preferred IP address 
DEBU[0000] Allocating IPv4 pools for network bridge (cab36df1a92c29385fc18b05d0475b1baaa3cd208b49e4935c70ce700fe41493) 
DEBU[0000] RequestPool(LocalDefault, 172.17.0.1/16, , map[], false) 
DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.0.1, map[]) 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0000] /usr/sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
DEBU[0000] Mount base: /var/lib/docker/containers/0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c/shm, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c/shm 
DEBU[0000] Mount base: /var/lib/docker/containers/0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c/mqueue, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c/mqueue 
DEBU[0000] Mount base: /var/lib/docker/containers/06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f/shm, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f/shm 
DEBU[0000] Mount base: /var/lib/docker/containers/06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f/mqueue, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f/mqueue 
DEBU[0000] Mount base: /var/lib/docker/containers/acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e/shm, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e/shm 
DEBU[0000] Mount base: /var/lib/docker/containers/acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e/mqueue, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e/mqueue 
DEBU[0000] Cleaning up old shm/mqueue mounts: done.     
DEBU[0000] Loaded container 06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f 
DEBU[0000] Loaded container 0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c 
DEBU[0000] Loaded container 62541cf723103426429d79edba68ca47844b805517842960e44c22d81978f637 
DEBU[0000] Loaded container 974d8082d034bf71571be5cc79dab13f49057f2d25cab5290dec5b6ff7d1f273 
DEBU[0000] Loaded container acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e 
DEBU[0000] killing old running container 06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f 
DEBU[0000] killing old running container 0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c 
DEBU[0000] Starting container 62541cf723103426429d79edba68ca47844b805517842960e44c22d81978f637 
DEBU[0000] Assigning addresses for endpoint onlyoffice-control-panel's interface on network bridge 
DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0000] Assigning addresses for endpoint onlyoffice-control-panel's interface on network bridge 
ERRO[0000] nosuchcontainer: no such id: 974d8082d034bf71571be5cc79dab13f49057f2d25cab5290dec5b6ff7d1f273 
DEBU[0000] killing old running container acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e 
DEBU[0001] Put on a non-mounted device 06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f 
DEBU[0001] Starting container 06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f 
DEBU[0001] Assigning addresses for endpoint mad_jepsen's interface on network bridge 
DEBU[0001] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0001] Assigning addresses for endpoint mad_jepsen's interface on network bridge 
DEBU[0001] Put on a non-mounted device 0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c 
DEBU[0001] Put on a non-mounted device acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e 
DEBU[0001] Starting container 0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c 
DEBU[0001] Assigning addresses for endpoint onlyoffice-document-server's interface on network bridge 
DEBU[0001] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0001] Starting container acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e 
DEBU[0001] Assigning addresses for endpoint onlyoffice-mail-server's interface on network bridge 
DEBU[0001] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
WARN[0001] exit status 1                                
DEBU[0001] Assigning addresses for endpoint onlyoffice-document-server's interface on network bridge 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 587 -j DNAT --to-destination 172.17.0.5:587 ! -i docker0] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.5 --dport 587 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.5 -d 172.17.0.5 --dport 587 -j MASQUERADE] 
DEBU[0001] Update /etc/hosts of 974d8082d034bf71571be5cc79dab13f49057f2d25cab5290dec5b6ff7d1f273 for alias document_server with ip 172.17.0.4 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 143 -j DNAT --to-destination 172.17.0.5:143 ! -i docker0] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.5 --dport 143 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.5 -d 172.17.0.5 --dport 143 -j MASQUERADE] 
DEBU[0001] Releasing addresses for endpoint onlyoffice-control-panel's interface on network bridge 
DEBU[0001] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2) 
WARN[0001] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/62541cf723103426429d79edba68ca47844b805517842960e44c22d81978f637/shm: invalid argument
failed to umount /var/lib/docker/containers/62541cf723103426429d79edba68ca47844b805517842960e44c22d81978f637/mqueue: invalid argument 
DEBU[0001] Put on a non-mounted device 62541cf723103426429d79edba68ca47844b805517842960e44c22d81978f637 
DEBU[0001] Failed to unmount 62541cf723103426429d79edba68ca47844b805517842960e44c22d81978f637 overlay: invalid argument 
ERRO[0001] Failed to start container 62541cf723103426429d79edba68ca47844b805517842960e44c22d81978f637: [8] System error: not a directory 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 25 -j DNAT --to-destination 172.17.0.5:25 ! -i docker0] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.5 --dport 25 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.5 -d 172.17.0.5 --dport 25 -j MASQUERADE] 
DEBU[0001] Assigning addresses for endpoint onlyoffice-mail-server's interface on network bridge 
DEBU[0001] Update /etc/hosts of 974d8082d034bf71571be5cc79dab13f49057f2d25cab5290dec5b6ff7d1f273 for alias mail_server with ip 172.17.0.5 
FATA[0001] is a directory
````

After moving the directory of the failing container I get 

```
docker daemon -D
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using default logging driver json-file       
DEBU[0000] Creating images graph                        
DEBU[0000] Restored 87 elements                         
DEBU[0000] Creating repository list                     
DEBU[0000] Option DefaultDriver: bridge                 
DEBU[0000] Option DefaultNetwork: bridge                
INFO[0000] Firewalld running: false                     
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D OUTPUT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -F DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -X DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -N DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[0000] Registering ipam provider: default           
DEBU[0000] Releasing addresses for endpoint onlyoffice-document-server's interface on network bridge 
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.3) 
DEBU[0000] Releasing addresses for endpoint mad_jepsen's interface on network bridge 
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.4) 
DEBU[0000] Releasing addresses for endpoint onlyoffice-mail-server's interface on network bridge 
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.5) 
DEBU[0000] releasing IPv4 pools from network bridge (e0dd4258d485434b3b969a613df29387db6e77d6990dac1650d2a94399a30456) 
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.1) 
DEBU[0000] ReleasePool(LocalDefault/172.17.0.0/16)      
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.1/16. Daemon option --bip can be used to set a preferred IP address 
DEBU[0000] Allocating IPv4 pools for network bridge (bf94f0818bd07342bcedb67dac9b32d75af98d07f5041523f743a39277ab39a9) 
DEBU[0000] RequestPool(LocalDefault, 172.17.0.1/16, , map[], false) 
DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.0.1, map[]) 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0000] /usr/sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
DEBU[0000] Mount base: /var/lib/docker/containers/0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c/shm, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c/shm 
DEBU[0000] Mount base: /var/lib/docker/containers/0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c/mqueue, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c/mqueue 
DEBU[0000] Mount base: /var/lib/docker/containers/06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f/shm, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f/shm 
DEBU[0000] Mount base: /var/lib/docker/containers/06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f/mqueue, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f/mqueue 
DEBU[0000] Mount base: /var/lib/docker/containers/acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e/shm, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e/shm 
DEBU[0000] Mount base: /var/lib/docker/containers/acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e/mqueue, repository /var/lib/docker/containers 
DEBU[0000] Unmounting /var/lib/docker/containers/acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e/mqueue 
DEBU[0000] Cleaning up old shm/mqueue mounts: done.     
DEBU[0000] Loaded container 06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f 
DEBU[0000] Loaded container 0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c 
DEBU[0000] Loaded container 974d8082d034bf71571be5cc79dab13f49057f2d25cab5290dec5b6ff7d1f273 
DEBU[0000] Loaded container acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e 
DEBU[0000] killing old running container 06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f 
DEBU[0000] killing old running container 0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c 
DEBU[0000] killing old running container acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e 
DEBU[0000] Put on a non-mounted device acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e 
DEBU[0000] Starting container acfcbfcaa48eb0080be1a0ac7194c109f005a009c7146c52c70909c628e8094e 
DEBU[0000] Assigning addresses for endpoint onlyoffice-mail-server's interface on network bridge 
DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 587 -j DNAT --to-destination 172.17.0.2:587 ! -i docker0] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 587 -j ACCEPT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 587 -j MASQUERADE] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 143 -j DNAT --to-destination 172.17.0.2:143 ! -i docker0] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 143 -j ACCEPT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 143 -j MASQUERADE] 
DEBU[0000] Put on a non-mounted device 06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f 
DEBU[0000] Starting container 06ae769181a8490ba171bd7e9aa1902e8ec7826759f6c862483ed0e14af7200f 
DEBU[0000] Assigning addresses for endpoint mad_jepsen's interface on network bridge 
DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 25 -j DNAT --to-destination 172.17.0.2:25 ! -i docker0] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 25 -j ACCEPT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 25 -j MASQUERADE] 
DEBU[0000] Assigning addresses for endpoint mad_jepsen's interface on network bridge 
DEBU[0000] Put on a non-mounted device 0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c 
DEBU[0000] Starting container 0ff04aa7281d3878faffa50052dc187ec841e692e636fa3316d7ef3d1d6ffe4c 
DEBU[0000] Assigning addresses for endpoint onlyoffice-document-server's interface on network bridge 
DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0001] Assigning addresses for endpoint onlyoffice-mail-server's interface on network bridge 
DEBU[0001] Assigning addresses for endpoint onlyoffice-document-server's interface on network bridge 
DEBU[0001] Update /etc/hosts of 974d8082d034bf71571be5cc79dab13f49057f2d25cab5290dec5b6ff7d1f273 for alias mail_server with ip 172.17.0.2 
DEBU[0001] Update /etc/hosts of 974d8082d034bf71571be5cc79dab13f49057f2d25cab5290dec5b6ff7d1f273 for alias document_server with ip 172.17.0.4 
FATA[0001] is a directory
``` 

```
systemctl status docker -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mo 2016-06-20 13:46:48 CEST; 5min ago
     Docs: http://docs.docker.com
  Process: 14851 ExecStart=/bin/sh -c /usr/bin/docker-current daemon $OPTIONS            $DOCKER_STORAGE_OPTIONS            $DOCKER_NETWORK_OPTIONS            $ADD_REGISTRY            $BLOCK_REGISTRY            $INSECURE_REGISTRY            2>&1 | /usr/bin/forward-journald -tag docker (code=exited, status=0/SUCCESS)
 Main PID: 14851 (code=exited, status=0/SUCCESS)

Jun 20 13:46:46 ooffice-test.rz.tu-bs.de systemd[1]: Starting Docker Application Container Engine...
Jun 20 13:46:46 ooffice-test.rz.tu-bs.de forward-journal[14854]: Forwarding stdin to journald using Priority Informational and tag docker
Jun 20 13:46:46 ooffice-test.rz.tu-bs.de forward-journal[14854]: time="2016-06-20T13:46:46.898746526+02:00" level=info msg="Firewalld running: false"
Jun 20 13:46:47 ooffice-test.rz.tu-bs.de forward-journal[14854]: time="2016-06-20T13:46:47.658775141+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.1/16. Daemon option --bip can be used to set a preferred IP address"
Jun 20 13:46:47 ooffice-test.rz.tu-bs.de forward-journal[14854]: time="2016-06-20T13:46:47.697529959+02:00" level=info msg="Loading containers: start."
Jun 20 13:46:48 ooffice-test.rz.tu-bs.de forward-journal[14854]: ............
Jun 20 13:46:48 ooffice-test.rz.tu-bs.de forward-journal[14854]: time="2016-06-20T13:46:48.309149139+02:00" level=info msg="Loading containers: done."
Jun 20 13:46:48 ooffice-test.rz.tu-bs.de forward-journal[14854]: time="2016-06-20T13:46:48.309238402+02:00" level=fatal msg="is a directory"
Jun 20 13:46:48 ooffice-test.rz.tu-bs.de systemd[1]: Started Docker Application Container Engine.

```

**Output of `docker version`:**

```
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-common-1.9.1-40.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      ab77bde/1.9.1
 Built:           
 OS/Arch:         linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

```

**Output of `docker info`:**

Server not running but I use Docker Version 1.9.1 (CentOS 7.2 repo) with overlayfs as a storage engine.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

-> Virtual Maschine on VMWare

**Comment by thaJeztah** [comment] 2016-07-06 06:39
Looks like you're running the Red Hat fork of Docker https://github.com/projectatomic/docker/commit/ab77bde. Would you be able to uninstall that version of Docker and see if you're still able to reproduce this with the official builds from our repository? https://docs.docker.com/engine/installation/linux/centos/

**Comment by xiaods** [comment] 2016-07-18 04:12
please upgrade to docker 1.11, have a try

**Comment by thaJeztah** [comment] 2016-07-18 13:00
I'm closing this issue for now, because we didn't get more information from the original reporter, but feel free to comment if you have more information

**Closed by thaJeztah** 2016-07-18 13:00 UTC

**Comment by pizzarabe** [comment] 2016-07-21 03:11
The Problem was resolved after installing the newest version of docker. It seems like this problem is indeed a atomic related problem, thank you guys!

**Comment by thaJeztah** [comment] 2016-07-21 09:33
Thanks @pizzarabe! Good to hear it's resolved
