### ISSUE TITLE
Docker registry behind Nginx Proxy issue

### ISSUE THREAD

**Issue by mtiadm** [docker/docker#8557] opened 2014-10-14 09:59 UTC
I there, 

I have a problem when i try to setup the Nginx frontend for auth. I don't know if it's a server side misconfiguration or a docker client issue.

When i run docker login myregistry:80 i can successfully login (Login Succeeded)
Then when i try a search, i have 401 error responses from Nginx

Here are the logs : 
```
192.168.122.1 - - [14/Oct/2014:11:25:02 +0200] "\x16\x03\x01\x00\x88\x01\x00\x00\x84\x03\x03\x83\xBC\x09\xCD6\xB6\x80H\x9F\xC3\xCB\xCD\xAED\xA6\xE7OFg\xCA\xD8P\x1C\x064\x89\xC7\x91\xF0\xF4,y\x00\x00\x1A\xC0/\xC0+\xC0\x11\xC0\x07\xC0\x13\xC0\x09\xC0\x14\xC0" 400 172 "-" "-"
192.168.122.1 - - [14/Oct/2014:11:25:02 +0200] "GET /v1/_ping HTTP/1.1" 200 4 "-" "Go 1.1 package http"
192.168.122.1 - - [14/Oct/2014:11:25:02 +0200] "GET /v1/search?q=ubuntu HTTP/1.1" 401 194 "-" "docker/1.2.0 go/go1.3.1 git-commit/fa7b24f kernel/3.8.0-44-generic os/linux arch/amd64"
```

If I try to connect via firefox to : http://myregistry/v1/search?q=ubuntu 

I can see the response : `{"num_results": 2, "query": "ubuntu", "results": [{"description": null, "name": "library/ubuntu"}, {"description": null, "name": "library/ubuntuone"}]}`

I followed all the guides here and looked at the issues, but i can't figure out why it's not working. A direct access to the registry is ok (without auth) but i'd like to use a proxy to limit the ability to push or delete images to authenticated users only.

Thanks for your help

**Comment by dkjer** [comment] 2015-01-12 20:04
This looks like a duplicate of #9922

**Comment by jfrazelle** [comment] 2015-01-12 20:05
closing as duplicate

**Comment by jfrazelle** [comment] 2015-01-12 20:06
thanks @dkjer for pointing these out

**Closed by jfrazelle** 2015-01-12 20:05 UTC
Labels: /project/doc, Distribution
