### ISSUE TITLE
1.12 docker service issue: service can't reach another service with internal dns name

### ISSUE THREAD

**Issue by sodre90** [docker/docker#23855] opened 2016-06-22 13:56 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.0-rc2
Storage Driver: devicemapper
 Pool Name: docker-253:1-50373608-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 296.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 41.2 GB
 Metadata Space Used: 1.114 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: 0cvppkel734omitklgpta1l9k
 IsManager: Yes
 Managers: 1
 Nodes: 2
 CACertHash: sha256:4acd2bf14e1745e0b8183e8fb8831509b715439d32e1bff992c020e2808ba266
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
Name: peti-test-1
ID: CFD3:Y722:6FPU:6J7T:SM6C:D5X4:YLBS:PDAR:XSON:ZWWR:OCEE:ZW3M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. machine-1: docker swarm init
2. machine-2: docker swarm join machine-1:2377
3. machine-1: docker network -d overlay test_network
4. machine-1: docker service create --name first_service --network test_network instavote/vote
5. machine-1: docker service create --name second_service --network test_network instavote/vote
6. machine-1: docker exec -it $(docker ps -q | awk 'NR==1{print $1}') ping first_service
 OR machine-1: docker exec -it $(docker ps -q | awk 'NR==1{print $1}') ping second_service

**Describe the results you received:**
TIMEOUT

**Describe the results you expected:**
successful ping

**Comment by johnston** [comment] 2016-06-22 15:22
I am experiencing a similar issue. From what I can tell the internal DNS name is resolving to the wrong IP address.

Here second_service resolves to **10.0.1.4**

```
docker exec -it 87055a2bf81a ping second_service
PING second_service (10.0.1.4): 56 data bytes
```

But inspecting the network lists it as **10.0.1.5**

```
docker network inspect test_network
[
    {
        "Name": "test_network",
        "Id": "75sik5dzqkdsz2jq8v8j2oqk1",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.1.0/24",
                    "Gateway": "10.0.1.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "3d19ff52bb73c2416429737f0e1ca5148b86ae066a53364cfd30a1e6d2077839": {
                "Name": "second_service.1.9umoi0f7nb6oftjjmgwo6yjsl",
                "EndpointID": "2e8862a4a903ccbb7a970bd1b05909271d1426f7677a42e4d7497165fde60ca6",
                "MacAddress": "02:42:0a:00:01:05",
                "IPv4Address": "10.0.1.5/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "258"
        },
        "Labels": {}
    }
]
```

Pinging from first_service using the actual IP works.

```
docker exec -it 87055a2bf81a ping 10.0.1.5
PING 10.0.1.5 (10.0.1.5): 56 data bytes
64 bytes from 10.0.1.5: seq=0 ttl=64 time=13.759 ms
```

**Comment by tonistiigi** [comment] 2016-06-22 17:10
cc @mavenugo @mrjana

**Comment by sodre90** [comment] 2016-06-23 07:12
I think the IP address is good, because it is the Virtual IP address of the service. But the problem is that the containers can not reach this IP address.

`docker service inspect test1

....
"Endpoint": {
            "Spec": {},
            "VirtualIPs": [
                {
                    "NetworkID": "8t19dljl9nmxz2mwk6rxkocss",
                    "Addr": "10.0.0.2/24"
                }
            ]
        }
...`

**Comment by jhorwit2** [comment] 2016-06-24 00:23
So, I followed the same steps and I'm seeing different ip address under network inspect than service inspect. When I ping the service I get the IP from the service inspect, which isn't able to be routed. However, if I curl the ip address from the network output I can reach the service. 

```
docker network create -d overlay test
docker service create --replicas 1 --name nginx --network test nginx:latest
docker service create --replicas 1 --name nginx1 --network test nginx:latest
```

```
root@500f22b2cf5a:/# ping nginx
PING nginx (10.0.0.2): 56 data bytes
92 bytes from 500f22b2cf5a (10.0.0.3): Destination Host Unreachable
```

As you can see below `10.0.0.3` matches the service inspect
```
$ docker service inspect nginx
[
    {
        "ID": "8ys321p8zmom9j889bc90sbwh",
        "Version": {
            "Index": 45
        },
        "CreatedAt": "2016-06-24T00:14:21.764392805Z",
        "UpdatedAt": "2016-06-24T00:14:21.767262769Z",
        "Spec": {
            "Name": "nginx",
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:latest"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "MaxAttempts": 0
                },
                "Placement": {}
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {},
            "Networks": [
                {
                    "Target": "959ryqkmzqluey68zdbrd00rg"
                }
            ],
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {},
            "VirtualIPs": [
                {
                    "NetworkID": "959ryqkmzqluey68zdbrd00rg",
                    "Addr": "10.0.0.2/24"
                }
            ]
        }
    }
]
```
but it does not match the network inspect

```
$ docker network inspect test
[
    {
        "Name": "test",
        "Id": "959ryqkmzqluey68zdbrd00rg",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/24",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "147cad002da4983294f282ce74c81b2e3fd19ec8e56e04267cd25c1d2e89e136": {
                "Name": "nginx1.1.427gkawey2g31xr57j0p8dgcd",
                "EndpointID": "a9a82184095d91b569c1ddc72f0eb9ae190c5df437151299a18a10511b06b0c8",
                "MacAddress": "02:42:0a:00:00:05",
                "IPv4Address": "10.0.0.5/24",
                "IPv6Address": ""
            },
            "500f22b2cf5a1a55c9366140fbba532341ea13f8cfc8f7523c97b49faaaff66c": {
                "Name": "nginx.1.4h7f8glz9d6oskq0mh7e9nmms",
                "EndpointID": "5ea48334c17881f6ff5416e0cd5a99bd0a08a90156aa8e653e917f35112da5a0",
                "MacAddress": "02:42:0a:00:00:03",
                "IPv4Address": "10.0.0.3/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "257"
        },
        "Labels": {}
    }
]
```

If I run `curl 10.0.0.3` inside the other service's container I hit nginx like expected.

**Comment by willrstern** [comment] 2016-06-24 20:46
Here's what I'm seeing
```
docker service create --name=hello --network=apps dockercloud/hello-world
# from another service
curl hello #works

# scale to 2
docker service scale hello=2
# from another service
curl hello #works - I get both containers round-robin

# scale to 1
docker service scale hello=1
# from another service
curl hello #could not resolve host

# scale back to 2
docker service scale hello=2
# from another service
curl hello #every other request fails now
```

**Comment by jhorwit2** [comment] 2016-06-27 18:35
I notice that pings fail, but I can curl the service name.

**Comment by thaJeztah** [comment] 2016-06-27 23:01
ping @mavenugo @mrjana PTAL

**Comment by mavenugo** [comment] 2016-06-27 23:22
@jhorwit2 @thaJeztah this is expected. The VIP that backs the service is not pingable. Its a L4 LB and hence one can try a L4ping like application or nc or ofcourse curl ;)

**Comment by mgoelzer** [comment] 2016-06-27 23:58
@sodre90 Can you try to reproduce this issue using `curl` or something different than ping? Thanks

**Comment by mgoelzer** [comment] 2016-06-27 23:59
@mavenugo For debugging purposes, could we respond to those pings anyway? I don't mean load balance them - just send an ICMP response back.

**Comment by thaJeztah** [comment] 2016-06-28 00:02
If we decide to not support ping, we need to update the documentation, first of all to explain it's not supported, but also update the examples in the "networking" docs, because all examples use "ping" to demonstrate how container networking works.

**Comment by mavenugo** [comment] 2016-06-28 00:27
ping @mrjana

**Comment by sodre90** [comment] 2016-06-28 13:23
@mgoelzer it works with curl, thanks :)

**Comment by sodre90** [comment] 2016-06-28 13:50
But I have some problem. If the first service is on node1 and the second service is on node2 then it does not works. 

Node 1:
`[root@peti-test-1 centos]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
28623fe07d5c        nginx:latest        "nginx -g 'daemon off"   25 minutes ago      Up 25 minutes       80/tcp, 443/tcp     third_service.1.caqdk6789e7ic24omeaiu7ff6
fa3d800440db        nginx:latest        "nginx -g 'daemon off"   26 minutes ago      Up 26 minutes       80/tcp, 443/tcp     second_service.1.1g0hcrd3a8lv26ua25g3bys3v
7d37c676f8bd        nginx:latest        "nginx -g 'daemon off"   33 minutes ago      Up 33 minutes       80/tcp, 443/tcp     test1.1.0vq9zbnpcqshtxtpgs24lbqkk`

Node 2:
`[root@peti-test-2 centos]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
6479648a6e9a        nginx:latest        "nginx -g 'daemon off"   30 minutes ago      Up 30 minutes       80/tcp, 443/tcp     first_service.1.a9pv25uiecjzsfovxjht9ifbp
ed00900d7f33        nginx:latest        "nginx -g 'daemon off"   34 minutes ago      Up 34 minutes       80/tcp, 443/tcp     test2.1.4ux4f5mxjthakt7mbhqzy7av3`

If I try on Node 1:
`[root@peti-test-1 centos]# docker exec -it test1.1.0vq9zbnpcqshtxtpgs24lbqkk bash
root@7d37c676f8bd:/# curl first_service
curl: (6) Could not resolve host: first_service
root@7d37c676f8bd:/# curl second_service
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>`

**Comment by mrjana** [comment] 2016-06-28 21:09
@sodre90 Is `test1` part of the same network as `first_service`?

**Comment by alon-totango** [comment] 2016-06-29 12:04
@mrjana I have 2 services running in the same default overlay network created by the swarm. The swarm consists of 3 nodes. One service is called serv1 and the other service is called serv2

All serv2 does is attempt to curl serv1, but it fails with the error `Could not resolve host: serv1`

Any ideas how I can try and debug this? Thanks

**Comment by willrstern** [comment] 2016-06-29 14:30
@mrjana same curl error in https://github.com/docker/docker/issues/23855#issuecomment-228457673 they're on the same network as well.  It generally works on first deploy until a scale down happens, then it's hit and miss what IP it will try to reach.  Every other may fail, all may fail, all may work.  It's different every time.

**Comment by mrjana** [comment] 2016-06-29 18:55
@willrstern Thanks for testing. I think your issues should be fixed in the next rc(rc3). Please verify whenever that comes out and provide feedback.

**Comment by mrjana** [comment] 2016-06-29 18:57
@alon-totango If you are testing in virtual-box or any host which has multiple host nics please make sure you initialized `swarm` by using a proper IP address as the `--listen-addr` option. If not please take a look at docker logs for any errors.

**Comment by ab666** [comment] 2016-06-29 18:57
I'm experiencing the same issue.  It appears that ip resolution is off by 1.

> docker network inspect dev
[...]
                "Name": "dev-db-alias.1.02211cdvntbri54ei5r19eba8",
                "EndpointID": "c7d100fce0eda69ccb13cd9e3ba10e3b58621def022dae543e32c595a0bf64a7",
                "MacAddress": "02:42:0a:00:00:05",
                "IPv4Address": "**10.0.0.5/24**",
                "IPv6Address": ""
[...]

> ping dev-db-alias
PING dev-db-alias (**10.0.0.4**): 56 data bytes
92 bytes from fe96b5589a01 (10.0.0.5): Destination Host Unreachable

**Comment by mrjana** [comment] 2016-06-29 19:00
@ab666 The name of the service resolves to the VIP. To confirm take a look at `docker service inspect <service_name>` and you should see the VIP listed there. Since it is a VIP it is not pingable. But you can access the VIP over TCP or UDP

**Comment by ab666** [comment] 2016-06-29 19:21
@mrjana: You are correct, Thank You!
It seems that I can only access containers in the same network and on the same node. 
Should I be able resolving containers from other nodes in the swarm as well?

**Comment by mrjana** [comment] 2016-06-29 19:27
@ab666 Yes you should be able to access all the containers in all nodes as long as they are in the same network. One reason this may not be working as intended is when `--listen-addr` is not configured properly or not configured at all and is causing a problem in your env(like you have multiple host nics)

**Comment by jswann** [comment] 2016-06-29 19:52
@mrjana I had resolution issues until i figured out I had to specify the listen-addr because the default 0.0.0.0 was mapping to the wrong interface. I'm now able to hit any container IP and resolve the service no matter which container the task is deployed.

However, on windows (boot2docker), if I run a container on the docker host separate from the service and try to curl my service http://web it won't resolve, while OSX (boot2docker) works as i hoped. It would seem that the windows version isn't resolving agains the internal DNS server.

**Comment by mrjana** [comment] 2016-06-29 20:26
@jswann When you said "if I run a container on a docker host separate from the service" did you run a separate service or directly start a container?

**Comment by jswann** [comment] 2016-06-29 20:47
@mrjana - Run a new container on one of the hosts that is also running the service. For example, i wanted to run an nginx container that can proxy to a service and I could route to the service name (much like i could container names).

**Comment by mrjana** [comment] 2016-06-29 22:54
@jswann to connect to a service on a network you need to start another service. Running a container directly on that network is not yet supported in swarm mode.

**Comment by sodre90** [comment] 2016-06-30 08:06
@mrjana - Yes they are in the same overlay network, if I run `docker inspect` they have the same NetworkID (8t19dljl9nmxz2mwk6rxkocss)

**Comment by mort1k** [comment] 2016-06-30 16:30
Hi, 
is there any hope to wait for the domain name resolution for simple containers on different swarm workers and different connected networks?

**Comment by mrjana** [comment] 2016-06-30 16:46
@sodre90 Not sure what your problem is if you did everything correct. Can you provide a simple repro of how you hit this issue so we can see if there is a problem or where the problem is?

**Comment by mrjana** [comment] 2016-06-30 16:46
@mort1k There may still be hope but no promises :-)

**Comment by mort1k** [comment] 2016-06-30 17:05
@mrjana =)
how variants expose internal embeded dns to external port on docker host?

**Comment by mort1k** [comment] 2016-06-30 17:24
what has caused the restriction resolving addresses only for containers on the same subnet?

**Comment by sodre90** [comment] 2016-06-30 19:05
@mrjana I started all over again, but with --listen-addr and now it's working! :) thank you for your help!

**Comment by mavenugo** [comment] 2016-07-23 11:54
@sodre90 Is this still an open issue ? or is it a candidate to be closed ?

**Closed** 2016-08-01 09:04 UTC
Labels: group/networking, priority/P2, version/1.12

**Comment by rajkumar49** [comment] 2016-09-12 06:38
I still face this issue. I can able to access container using service name in the Same host only . Accessing the another host containers is not working . i have even tried the --listen-addr method when launching the Swarm manger and Swarm Worker. please help

**Comment by vimagick** [comment] 2016-09-13 07:36
I cannot access same network service on another node.
Please help!

**Comment by rajkumar49** [comment] 2016-09-13 10:36
@vimagick please check this open issue : https://github.com/docker/docker/issues/26480

**Comment by jesuscript** [comment] 2016-11-07 19:41
having a similar issue. what should --listen-addr be set to?

**Comment by thaJeztah** [comment] 2016-11-07 22:12
@jesuscript no need to set listen-addr (it defaults to 0.0.0.0), `--advertise-addr` is the important one if your node has multiple interfaces / IP addresses

**Comment by ezeakeal-ps** [comment] 2016-11-08 20:25
I was coming across a similar issue to @ab666 where the IP was off by 1, and indeed I was finding the VIP on lookup. While this was correct, the VIP was not forwarding a HTTP request on port 80 to the container. Maybe I was doing something wrong here, but my setup had worked before. 

I was using docker 1.12.1, upgraded to docker 1.12.2 with no change. System/Service reboot did not change behavior.
I am using namespace remapping and LVM with devicemapper on RHEL 7

Anyway, I needed the resolution for Apache. I worked around my problem by prefixing the lookup name with 'tasks.' which gives the IP of the containers associated with a service rather than the VIP.

I will be revisiting the service configuration at a later date and will update if I come across something.

**Comment by Intellicode** [comment] 2017-01-16 22:34
@thaJeztah, I had a similar issue as described in the OP and setting --listen-addr resolved it, what reason could there be that it wouldn't work without specifying since it defaults to 0.0.0.0 by default? This was on docker 1.12.6.

**Comment by widgetpl** [comment] 2017-07-31 09:53
I have similar issue on docker `1.13.1` and compose `1.14.0`
Starting fluentd containers in one compose manifest they can't see each other. One fluentd container is restarting and I can notice that it creates new endpoint each time it restarts
```
        "Containers": {
            "2bc01721533b626021b374def53bac30a204000d461cde753d9a8424315da57c": {
                "Name": "fluentd-router",
                "EndpointID": "be690be7fa16430c13f954e1971891709b67bc81c7a4bdedfe2c444d10c96ca3",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
```
even updating docker to latest version dosen't help.

**Comment by thaJeztah** [comment] 2017-07-31 10:25
@widgetpl please open a new issue with details, and steps to reproduce instead of commenting on a closed one; comments on closed issues easily go overlooked, and there's a chance it's a different issue altogether.

I'll lock the conversation on this issue for the reason above
