### ISSUE TITLE
docker build add displaces context root subdirectories

### ISSUE THREAD

**Issue by cevich** [docker/docker#12380] opened 2015-04-14 20:51 UTC
Description of problem:
(Copied from  https://bugzilla.redhat.com/show_bug.cgi?id=1202849)

Not sure if this is a "feature" or a "bug".  If it's a feature, it's not very well documented and (IMHO) unexpected given behaviour compared to common tools (cp, mv, etc).

Essentially, the ADD instruction with a source of ``*`` operates on the files inside root-level context subdirectories, instead of the directories themselves.  This is a problem for any project that needs to includes a lot of root-level subdirectories, where filenames clash with other subdirectories.  Naming all the subdirectoires in ``ADD`` is not a practical solution.  e.g. nested Makefiles

`docker version`:
docker-1.5.0 and 1.6.0

`docker info`:
Containers: 4
Images: 61
Storage Driver: devicemapper
 Pool Name: docker-253:2-259788-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.049 GB
 Data Space Total: 107.4 GB
 Data Space Available: 4.148 GB
 Metadata Space Used: 2.601 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.1.2.el7.x86_64
Operating System: Employee SKU
CPUs: 1
Total Memory: 1.797 GiB
Name: dockertest.localdomain
ID: 5BS5:6XGS:ZX3S:4V65:LBRH:EYKK:D4MC:6EPI:A3KA:HKPA:ETJ6:BTJ2

`uname -a`:
Linux dockertest.localdomain 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 6 17:12:08 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
RHEL 7.1 OS running under QEMU KVM

How reproducible:
Always

Steps to Reproduce:
```
# mkdir context && cd context
# uuidgen > testfile
# mkdir subdir
# uuidgen > subdir/testfile
# vim Dockerfile
# cat Dockerfile
FROM registry.access.redhat.com/rhel7:latest
ADD testfile /testdir/
RUN echo "File contains: $(cat /testdir/testfile)" && ls -la /testdir
RUN rm -rf /testdir
ADD testfile subdir /testdir/
RUN echo "Now File contains: $(cat /testdir/testfile)" && ls -la /testdir
RUN rm -rf /testdir
ADD * /testdir/
RUN echo "finally File contains: $(cat /testdir/testfile)" && ls -la /testdir
# docker build -t test --no-cache .
```

Actual Results:
```
Sending build context to Docker daemon 4.608 kB
Sending build context to Docker daemon 
Step 0 : FROM registry.access.redhat.com/rhel7:latest
 ---> 10acc31def5d
Step 1 : ADD testfile /testdir/
 ---> f4e5c570a1db
Removing intermediate container 4a10404b3aff
Step 2 : RUN echo "File contains: $(cat /testdir/testfile)" && ls -la /testdir
 ---> Running in 594a0b7de3da
File contains: 610d5548-a1e5-4a52-bb84-b06fb0335575
total 12
drwxr-xr-x.  2 root root 4096 Apr 14 16:32 .
drwxr-xr-x. 18 root root 4096 Apr 14 16:32 ..
-rw-r--r--.  1 root root   37 Apr 14 15:55 testfile
 ---> 81386d19d2ee
Removing intermediate container 594a0b7de3da
Step 3 : RUN rm -rf /testdir
 ---> Running in 4dd17afd935a
 ---> a1ad4635c489
Removing intermediate container 4dd17afd935a
Step 4 : ADD testfile subdir /testdir/
 ---> b99ca1a05692
Removing intermediate container bbc75b2122e4
Step 5 : RUN echo "Now File contains: $(cat /testdir/testfile)" && ls -la /testdir
 ---> Running in 3b4896fa8d84
Now File contains: a1b57741-bbb4-4fee-925e-acbe4275ff0f
total 12
drwxr-xr-x.  2 root root 4096 Apr 14 16:32 .
drwxr-xr-x. 18 root root 4096 Apr 14 16:32 ..
-rw-r--r--.  1 root root   37 Apr 14 15:56 testfile
 ---> f4939e1121c3
Removing intermediate container 3b4896fa8d84
Step 6 : RUN rm -rf /testdir
 ---> Running in 57016888d4d8
 ---> 11b77be3beca
Removing intermediate container 57016888d4d8
Step 7 : ADD * /testdir/
 ---> 398ac1e6a04b
Removing intermediate container 7aa5c69bab56
Step 8 : RUN echo "finally File contains: $(cat /testdir/testfile)" && ls -la /testdir
 ---> Running in 3fd9c3eb7f46
finally File contains: 610d5548-a1e5-4a52-bb84-b06fb0335575
total 16
drwxr-xr-x.  2 root root 4096 Apr 14 16:32 .
drwxr-xr-x. 18 root root 4096 Apr 14 16:32 ..
-rw-r--r--.  1 root root  376 Apr 14 16:17 Dockerfile
-rw-r--r--.  1 root root   37 Apr 14 15:55 testfile
 ---> 29679d9b1e6f
Removing intermediate container 3fd9c3eb7f46
Successfully built 29679d9b1e6f
```

Expected Results:
```
...
Step 1 : ADD testfile /testdir/
...
File contains: 610d5548-a1e5-4a52-bb84-b06fb0335575
total 12
drwxr-xr-x.  2 root root 4096 Apr 14 16:32 .
drwxr-xr-x. 18 root root 4096 Apr 14 16:32 ..
-rw-r--r--.  1 root root   37 Apr 14 15:55 testfile
...
Step 4 : ADD testfile subdir /testdir/
 ---> b99ca1a05692
...
Now File contains: 610d5548-a1e5-4a52-bb84-b06fb0335575
total 12
drwxr-xr-x.  2 root root 4096 Apr 14 16:32 .
drwxr-xr-x. 18 root root 4096 Apr 14 16:32 ..
drwxr-xr-x.  2 root root 4096 Apr 14 16:56 subdir
-rw-r--r--.  1 root root   37 Apr 14 15:55 testfile
...
Step 7 : ADD * /testdir/
...
finally File contains: 610d5548-a1e5-4a52-bb84-b06fb0335575
total 16
drwxr-xr-x.  2 root root 4096 Apr 14 16:32 .
drwxr-xr-x. 18 root root 4096 Apr 14 16:32 ..
drwxr-xr-x.  2 root root 4096 Apr 14 16:56 subdir
-rw-r--r--.  1 root root  376 Apr 14 16:17 Dockerfile
-rw-r--r--.  1 root root   37 Apr 14 15:55 testfile
```

Additional info:
Docker build seems to completely ignore the fact ``subdir`` in the context is a directory, and assumes ``ADD testfile subdir /testdir/`` should add the contents of ``subdir`` instead of the directory itself.  However, it's actually **worse** because it replaces contents of files that happen to have the same name!

**Comment by cpuguy83** [comment] 2015-07-22 03:47
Hi, is this still a problem?
Ping @duglin

**Comment by cpuguy83** [comment] 2015-08-17 14:54
Closing due to no-response.
If you can reproduce on the latest docker version  please ping here so we can take a look.
Thanks!

**Closed by cpuguy83** 2015-08-17 14:54 UTC
Labels: status/more-info-needed
