### ISSUE TITLE
Unable to create new networks in Docker 1.10 (+ iptables weirdness)

### ISSUE THREAD

**Issue by delfuego** [docker/docker#20217] opened 2016-02-11 03:30 UTC
I upgraded one of my hosts to Docker 1.10, and found that the one container running on that host was no longer able to make network connections off-container. As step one of debugging it, I decided to remove the container, remove the user-created bridge network, recreate it, and re-launch the container... but this failed when I tried to recreate the network and received a `unable to insert jump to DOCKER-ISOLATION rule in FORWARD chain` error.

```
$ docker network create logging
Error response from daemon: unable to insert jump to DOCKER-ISOLATION rule in FORWARD chain:  (iptables failed: iptables --wait -I FORWARD -j DOCKER-ISOLATION: iptables v1.4.21: Couldn't load target `DOCKER-ISOLATION':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2))
```

I've tried everything I can think of to resolve this, all to no avail. Of note, on the host prior to the 1.10 upgrade, I had all the right iptables rules in the FORWARD chain that forwarded traffic to the DOCKER chain; since the 1.10 upgrade, none of these rules are there, and aren't getting created when I run the Docker daemon.

Help! As of now, this docker host is functionally offline... ugh.

```
$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 149
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 183
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: FR-S-CCR-DOCK3
ID: OM2G:5GWL:DR43:5ZS5:RBJF:6FBA:MV5U:AOTY:XJAH:6QI4:7AJM:T33R
```

Host OS: Ubuntu 14.04 LTS x64, running virtualized via vSphere infrastructure.

Thanks a ton in advance.

**Comment by aboch** [comment] 2016-02-11 09:13
@delfuego 

I think the chains were somehow removed after being created during daemon boot.

I know it is not common since you are on ubuntu, but are you using firewalld by any chance ? We are aware of issues there.
You may want to reboot the daemon after disabling it (or disabling ufw if running)

Are you passing any options when starting the daemon ? Any WARNING in the daemon logs ? If you start the daemon with DEBUG logs, do you see the iptables related logging about chain creations ? 

As a quick workaround, you can manually create the chain `iptables -t filter -N DOCKER-ISOLATION`. You will be able to create the network, assuming no other chains are missing.

**Comment by delfuego** [comment] 2016-02-11 14:49
@aboch Thanks for the info. This morning, despite me manually creating it, I still had the same error. So, I decided to take the scorched-earth approach, stopped the Docker daemon, and flushed and removed ALL Docker-created chains from both the `filter` and `nat` tables (so the `DOCKER` and `DOCKER-ISOLATION` chains, and any rules in the other chains that referenced these chains).

```
iptables -t filter -F DOCKER
iptables -t filter -X DOCKER
iptables -t filter -F DOCKER-ISOLATION
iptables -t filter -X DOCKER-ISOLATION
iptables -t nat -F DOCKER
iptables -t nat -X DOCKER-ISOLATION
```

Then I restarted the Docker daemon, and it re-created all the relevant chains in the right tables. And only **then** was I able to recreate my user-created network.

So, I'm back in business... but am baffled what happened. And I have two other Docker hosts in this cluster that I need to now upgrade to 1.10... so I'm dreading having to do all this manually, but we'll see.

**Comment by delfuego** [comment] 2016-02-11 14:49
Notably: is there **any** documentation anywhere about what the `DOCKER-ISOLATION` chain is intended to do?

**Comment by aboch** [comment] 2016-02-11 16:55
@delfuego 
Thanks for the update.

That chain is to block inter-network traffic, to provide isolation between bridge networks. Isolation was there in 1.9 as well, but rules were too restrictive and were also blocking traffic to exposed services and to other networks bridge.
In 1.10 we changed the rule to port-based and moved them to this a specific chain which can be skipped for exposed port traffic.

I suspect what you saw has to do with some module in your system which wipes out the chains or block their creation.

If you can reproduce running the daemon with the `-D` option and provide the logs, that would be helpful.

**Comment by delfuego** [comment] 2016-02-11 17:19
@aboch Well, things are now working — when I do the upgrade of one of the other two hosts later this weekend, I'll see how it goes and document with the logs accordingly.

Is there any good documentation that helps me understand best practices in terms of being able to set up iptables rules related to user-created networks and hosts **and have those rules restore on system restart**? This host is a good example — it has a single Docker container on it which is running one of three Elasticsearch cluster nodes, and the only other hosts that should be able to communicate with it are the other two nodes (which are also running in Docker containers on other Docker hosts, not that that intrinsically matters). I have a user-created network on this host (`logging`) to which the elasticsearch container is connected, and I need to be able to control access to that network and this container. (By default, it appears that all traffic from off the Docker host can connect to the `logging` network.)

Right now, I can set up four iptables rules — two allowing traffic from the other two ES nodes, and two denying any other traffic — but these rules have to be inserted into the `DOCKER` chain of the `filter` table at a specific location. And the rest of the rules in the `DOCKER` chain are auto-created by the Docker daemon on startup, so the insertion of the rules is something I have to literally do manually every time I restart this Docker host.

Am I missing something?

**Comment by delfuego** [comment] 2016-02-11 17:20
Oh, and I'm sorry for this taking a tangent; I'm happy to take this to another ticket, and/or to email, if needed.

**Comment by thaJeztah** [comment] 2016-02-16 10:26
@delfuego is this resolved, or still an issue?

**Comment by delfuego** [comment] 2016-02-16 13:50
@thaJeztah The underlying issue is resolved, but I'd **love** some guidance as to how I think about and resolve iptables issues (like the one [above](url)). This issue ticket doesn't have to be the place... but then where *is* the best place?

**Comment by thaJeztah** [comment] 2016-02-16 13:59
@delfuego for a direct discussion with the network team, try the #docker-network IRC channel on freenode. You can also use the [docker-user](https://groups.google.com/forum/#!forum/docker-user) Google Group.

**Comment by thaJeztah** [comment] 2016-02-16 13:59
I'll close this issue here, but feel free to continue the discussion

**Closed by thaJeztah** 2016-02-16 13:59 UTC
Labels: group/networking

**Comment by aboch** [comment] 2016-02-16 16:40
@delfuego 
At boot, docker daemon removes its iptables chains, and recreates them as you noticed. So at the moment I don't think it is possible for you to restore your manually created rules, other than manually recreate them. I think what you are looking for the ability to specify some sort of per-network access policies at network creation, so that libnetwork driver manages their lifecycle. We don't have that yet, sorry.

**Comment by sandys** [comment] 2016-03-19 10:28
Can someone explain what this is about - I just launched a new AWS instance with Debian 8.1 and installed docker version 1.10.3 . I have been unable to reach my docker instances from the outside world (can still reach them from the host using the 172.* address).
I removed the docker isolation iptables rule using "sudo iptables -t filter -F DOCKER-ISOLATION" and everything started working again. 
Am I doing something wrong or some new feature is causing this ?  P.S. I use docker compose to map ports.

**Comment by EugenMayer** [comment] 2019-02-27 09:41
For googlers, this can be related to your firewall, in my case shorewall. AFAICS it depends on the start-timing. 

```
service shorewall stop
service docker stop
service shorewall start
service docker start
```

Starting in this order will fix this again - this will most probably happen with other firewalls too. (i am using shorewall 5.x with `DOCKER=yes` so i am actually using the exact thing that should be used with docker)

**Comment by moovs** [comment] 2019-05-15 09:33
I'm just reboot docker daemon and it fixed this situation!
