### ISSUE TITLE
How to set up data volume containers with Docker compose?

### ISSUE THREAD

**Issue by anonmily** [docker/docker#30920] opened 2017-02-10 22:21 UTC
I'm taking a look through the documentation, and I can't seem to find anywhere that shows how we can specify where a data volume container is located on the host. 

Below is the example given (from: https://docs.docker.com/compose/compose-file/#/volume-configuration-reference)

```
version: "3"

services:
  db:
    image: db
    volumes:
      - data-volume:/var/lib/db
  backup:
    image: backup-service
    volumes:
      - data-volume:/var/lib/backup/data

volumes:
  data-volume:
```

However, although we can see that data-volume has been mounted into /var/lib/db in the db container and into /var/lib/backup/data for the backup container, where do we specify where the data-volume is actually located on the host?

**Comment by AkihiroSuda** [comment] 2017-02-10 23:27
You may want to use bind mount instead (`/foo/bar:/var/lib/db`).
If you have multiple nodes, you may want to specify node placement constraint as well.

**Comment by aruljothi** [comment] 2017-02-11 14:23
@anonmily 

`aruljothi@test-node:~$ docker inspect testvol
[
    {
        "Driver": "local",
        "Labels": {
            "com.docker.stack.namespace": "testprod"
        },
        "Mountpoint": "/var/lib/docker/volumes/testprod_testvol/_data",
        "Name": "testprod_testvol",
        "Options": {},
        "Scope": "local"
    }
]
`

**Comment by RotemEmergi** [comment] 2017-02-12 14:54
Did you run `docker  create volume testvol `?

**Comment by BarakA89** [comment] 2017-02-15 17:59
_Data volumes_ are mainly to share data between containers and not between a container and the host.
see @AkihiroSuda answer for how to bind to the host.

**Comment by thaJeztah** [comment] 2017-03-21 12:21
I don't see anything actionable here; `volume` are managed by the docker daemon, and by default store data inside `/var/lib/docker` (as pointed out above). It's possible to use a different volume driver, or use bind-mounted directories (although they're not "portable") if you want access to those files.

I'm closing this issue because this is not a bug.  Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

**Closed by thaJeztah** 2017-03-21 12:21 UTC
Labels: area/swarm, area/volumes, kind/question

**Comment by reetesh11** [comment] 2017-07-17 10:11
Can we mount the data volume to host machine ? That means, I wan to share the data between teh containers and then, I want to have a backup of data in the host machine also. Is it possible ?
