### ISSUE TITLE
Will not the install instruction be cached? 

### ISSUE THREAD

**Issue by innocentme1** [docker/docker#25261] opened 2016-07-30 21:09 UTC
This link - https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/apt-get says that apt-get install should be used with apt-get update for cache busting. Will not the install command also be cached along with update instruction?  I understand that version pinning will help but not sure how mixing the install and update commands will help the cache busting.

**Comment by thaJeztah** [comment] 2016-07-30 21:31
if you put them on separate lines, e.g.

    RUN apt-get update
    RUN apt-get install -y foobar

and change the install line, to, eg

    RUN apt-get install -y foobar baz

then the `apt-get update` will not be executed again, and use the cached version for that.

since "update" and "install" are tightly related, it's better to combine them, so that changing the "install" will run both the "update", and "install" again.

I'll close this issue because this is a question, not a bug report, but feel free to continue the discussion

**Closed by thaJeztah** 2016-07-30 21:31 UTC

**Comment by innocentme1** [comment] 2016-07-30 22:12
Hey, ya i understand that. Document says "Using RUN apt-get update && apt-get install -y ensures your Dockerfile installs the latest package versions with no further coding or manual intervention. This technique is known as cache busting" and this is giving not giving an essence that package names also should be changed for preventing cache busting.
