### ISSUE TITLE
ENV interpolation confusion

### ISSUE THREAD

**Issue by nickjbyrne** [docker/docker#30458] opened 2017-01-25 23:44 UTC
**Description**

Given a dockerfile such as 

```
FROM docker/whalesay

ENV a var_a
ENV b var_b
ENV c "${a} and ${b}"

CMD echo a is ${a} | cowsay \
    && echo b is ${b} | cowsay \
    && echo c is \(a and b\) is ${c} | cowsay
```
And a command line

`docker run -e "a=env_arg" whale-env`

**Describe the results you received:**

ENV var ${a} contains the expected value as passed to docker run, however ENV var ${c} contains the variables set in dockerfile and not the new value of ${a}

**Describe the results you expected:**

ENV  var ${c} should contain the updated variable value.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:31:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:31:39 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 22
 Running: 1
 Paused: 0
 Stopped: 21
Images: 31
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-8:6-661585-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.645 GB
 Data Space Total: 107.4 GB
 Data Space Available: 2.128 GB
 Metadata Space Used: 4.19 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.128 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.122 (2016-04-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.8.16-200.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.713 GiB
Name: plateau.digitalnative.net
ID: PTLB:XA4R:5YTS:GQOY:RHKM:77OV:LFTJ:KLAK:IZO3:ATXF:AKCL:HS4Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Output of command

```
 ______________ 
< a is env_arg >
 -------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
 ____________ 
< b is var_b >
 ------------ 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
 ___________________________________ 
< c is (a and b) is var_a and var_b >
 ----------------------------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
```

**Comment by thaJeztah** [comment] 2017-01-26 02:03
The `ENV` instructions in the Dockerfile are evaluated when building the image. During `docker build`, `a = env_a`, `b = env_b`, and `c = env_a and env_b`.

The `CMD` is the default command that's executed when _running_ the image. When docker starts the container, it takes the env-vars that were defined in the image (with the values set during `docker build`), and sets those in the container.

If you set an env-var during `docker run`, the value for _that_ environment variables is overridden, but the steps performed during `docker build` are not re-evaluated (as those are baked into the image you created).

Hope this makes it clearer!

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-01-26 02:03 UTC
Labels: area/builder, version/1.12

**Comment by nickjbyrne** [comment] 2017-01-26 08:47
Ah, so this is classed as a feature :) Unfortunately this sort of dockerfile implementation would be a very common pattern in many configuration management tools or shell scripts, using ENV variables and inheriting them from one to another is really so fundamental that i think docker build and docker run should alert the user at the very least that run time time overrides wont be honoured. A documentation update or warning would also be useful, I'll look into contributing that.

**Comment by thaJeztah** [comment] 2017-01-26 09:40
The problem here is that not only is the Dockerfile no longer known at runtime (i.e., if I `docker pull` an image, the contents of the `Dockerfile` that was used to build the image is not known), re-evaluating them at runtime (even without the substitution in `$c`) will not solve such issues, e.g.;

```Dockerfile
FROM foo
ENV major=1
ENV minor=1
RUN curl -o foo https://example.com/packages/foo-${major}.${minor}.tar.gz
```

```bash
docker build -t myapp .
docker run --env minor=2 
```

Would not execute the `RUN` command, unless the entire image is built again.

Improving the docs around this may be good though, given that it was not clear to you, so looking forward to a pull request.

**Comment by nickjbyrne** [comment] 2017-01-26 11:08
Using your example above, it is not the evaluation by RUN it would be evaluation by ENV that is not happening at run time 

`
FROM foo
ENV major=1
ENV minor=1
ENV version=${major}.${minor}
CMD curl -o foo https://example.com/packages/foo-${version}.tar.gz
`

`
docker build -t myapp .
docker run --env minor=2 
`

Is more indicative of the problem in my mind. RUN and similar declarative items are more obviously build time only options, but we are told environment variables are [settable](https://docs.docker.com/engine/reference/commandline/run/) but the above would fail to do expected.

Perhaps, a variable such as BUILDENV would have been a better name for this specific variable, perhaps ARG was introduced for this but the docs didn't reflect it. Unfortunately my knowledge of docker history is very limited.

**Comment by thaJeztah** [comment] 2017-01-26 12:48
> Is more indicative of the problem in my mind.

True, the basic problem would be the same though;

```bash
$ docker build -t repro-30458 -<<EOF
FROM busybox
ENV major=1
ENV minor=1
RUN echo \${major}.\${minor} > /version.txt
CMD echo "env says installed version is \${major}.\${minor}, but it actually is:" && cat /version.txt
EOF

$ docker run --rm repro-30458
env says installed version is 1.1, but actually it is:
1.1

$ docker run -e minor=2 --rm repro-30458
env says installed version is 1.2, but actually it is:
1.1
```

> Perhaps, a variable such as BUILDENV would have been a better name for this specific variable

I can see it being confusing, given that for _some_ commands, these variables are interpolated at build time (e.g, `ENV`), but for others they are interpolated at _runtime_. Interpolation of variables was an a later addition to the existing `ENV` command. Renaming that command would be too much of a breaking change, but improving the docs is a good suggestion.

`ARG` was introduced to set shell variables at build-time, but don't _persist_ them in the image as an environment variable. This allows you to, e.g.;

```Dockerfile
FROM foo
ARG major=1
ARG minor=1
RUN echo ${major}.${minor} > /version.txt
CMD echo "env says installed version is ${major}.${minor}, but it actually is:" && cat /version.txt
```

```bash
docker build --build-arg minor=2 -t myapp:1.1 .

docker run --rm myapp:1.1
env says installed version is ., but it actually is:
1.1
```
