### ISSUE TITLE
Cannot stop/rm container echoing null bytes, crashes docker

### ISSUE THREAD

**Issue by x64x6a** [docker/docker#20600] opened 2016-02-23 09:27 UTC
# BUG REPORT INFORMATION

`docker version`:
```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 27
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-76-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 31.42 GiB
Name: scoreboard
ID: BOYV:RGQ7:VTLY:TEOI:UBWO:VGPX:IFOK:NGMY:J3XE:NE3J:FP2K:PB6I
WARNING: No swap limit support
```

`uname -a`:
```
Linux scoreboard 3.13.0-76-generic #120-Ubuntu SMP Mon Jan 18 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
- Tested server is a vm hosting on VMware vSphere.

## Details

I was fiddling with a docker container, and naively had the container run `cat /dev/zero` as the run command.  When I tried to stop or forcefully remove the container, it would fail.  I ran the original container with --restart=unless-stopped, so I'm not sure how to remove the container from my system.  Here are some logs:

Stopping:
```
An error occurred trying to connect: Post http:///var/run/docker.sock/v1.21/containers/59bdbc7606dd/stop?t=10: EOF
Error: failed to stop containers: [59bdbc7606dd]
```
Forcely removing:
```
An error occurred trying to connect: EOF
Error: failed to remove containers: [59bdbc7606dd]
```

## Recreation

I can easily recreate the error with a Dockerfile such as:
```
FROM debian:jessie
CMD cat /dev/zero
```

Then the docker commands:
```bash
docker build -t testzero .
docker run -d testzero
```

I then stopped docker and ran `docker daemon -D` to further debug.  I attempted to stop the container, and docker failed and crashed.  On line 142, the stop command can be seen.  I pasted the log into a gist: [https://gist.github.com/x64x6a/d309dedce84a16149e57#file-docker-debug-log-L142](https://gist.github.com/x64x6a/d309dedce84a16149e57#file-docker-debug-log-L142)

---

Is there any way I could stop the original container and prevent it from restarting since I used `--restart=unless-stopped`?  Or a way to even more forcefully remove the container from my machine?

**Comment by x64x6a** [comment] 2016-02-23 09:44
I tried to forcefully remove the container again:
`docker rm -f <container id>` 
And it successfully removed the container.  I'm not sure why it worked now, instead of during one of my previous attempts.

I can still recreate the issue however.

**Comment by coolljt0725** [comment] 2016-02-23 14:41
The cmd `cat /dev/zero` will make docker keep on consuming the memory of your host until OOM, and then docker crash.

**Comment by AkihiroSuda** [comment] 2016-04-11 05:03
I'm hitting this issue as well, on Docker 1.11-rc4

**Comment by AkihiroSuda** [comment] 2016-04-11 06:42
Is this issue closable as a duplicate of #18057?
PTAL @thaJeztah

**Comment by thaJeztah** [comment] 2016-04-11 07:50
@AkihiroSuda oh, you may be right; this looks like a duplicate of https://github.com/docker/docker/issues/18057. I'll close this one to keep the discussion in a single place

**Closed by thaJeztah** 2016-04-11 07:50 UTC
