### ISSUE TITLE
docker pull  with long time end throw 

### ISSUE THREAD

**Issue by MABIY** [docker/docker#26851] opened 2016-09-23 07:40 UTC
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:  
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:  
 OS/Arch:      linux/amd64

when l pull a big images with long time  then throw  infomations like blow.
Error response from daemon: Get https://registry-1.docker.io/v2/library/ubuntu/manifests/latest: Get https://auth.docker.io/token?account=**=registry.docker.io: dial tcp 127.0.0.1:443: getsockopt: connection refused.

blow in debug model get information.
RRO[0016] Handler for POST /v1.24/images/create returned error: Get https://registry-1.docker.io/v2/library/ubuntu/manifests/latest: Get https://auth.docker.io/token?account=? 127.0.0.1:443: getsockopt: connection refused

**Comment by thaJeztah** [comment] 2016-09-23 08:08
Can you also give the output of `docker info`? Looking at your description "127.0.0.1:443: getsockopt: connection refused" - are you using a proxy server?

**Comment by MABIY** [comment] 2016-09-23 14:50
l not use proxy server, but docker throw this error. this make me Strange. so l run daemon on debug model, above information is l think  to achieve .

l'm sorry. when l from company to my home. l attempt pull images then docker pull is work.
this error

**Comment by thaJeztah** [comment] 2016-09-23 14:52
So you only have this problem at work? I really suspect there's something related to the network-setup there

**Comment by MABIY** [comment] 2016-09-23 15:27
l not sure only have this proble at work. before is working normal，today l am want to pull a big magic . l'm more then one ctrl+c to stop  docker pull  and  restart docker pull . l don't sure this operate make error throw.

**Comment by MABIY** [comment] 2016-09-23 15:32
throw this "127.0.0.1:443: getsockopt: connection refused"  information.
l'm not try use crul  try this request ,but l'm sure network is work.

**Comment by MABIY** [comment] 2016-09-23 16:07
interesting,l' meet this error just now.
l open A ternimal to docker build -t  jenkins . 
then open the B ternimal to docker pull  jenkins  then  B ternimal throw   dial tcp 127.0.0.1:443: getsockopt: connection refused.

l'm try to reappear but docker working fine.

**Comment by thaJeztah** [comment] 2017-03-22 16:40
Docker 1.12 is no longer maintained, and we're not able to reproduce, so I'll go ahead and close this issue, but let us know if you're still having issues.

**Closed by thaJeztah** 2017-03-22 16:40 UTC
Labels: area/distribution, status/more-info-needed, version/1.12

**Comment by ianrose14** [comment] 2017-05-23 14:11
fwiw I have hit this twice now.  Definitely not using a proxy server.  I fixed it the first time be restarting my machine.  Restarting the docker daemon just now did _not_ fix it.

**Comment by ianrose14** [comment] 2017-05-23 14:12
I do see this in my `docker info` output; no idea if that is relevant:
```
Insecure Registries:
 127.0.0.0/8
```

**Comment by thaJeztah** [comment] 2017-05-23 19:25
@ianrose14 looks like the daemon resolved `registry-1.docker.io` to 127.0.0.1 - possibly an etc/hosts file or local dns that's configured to prevent access to docker hub?

**Comment by thaJeztah** [comment] 2017-05-23 19:26
Maybe i read the message wrong, but it looks odd

**Comment by ianrose14** [comment] 2017-05-24 14:42
Defintely odd.  Also seems docker-specific.

```
> dig registry-1.docker.io

(snip)
;; ANSWER SECTION:
registry-1.docker.io.	49	IN	A	52.0.56.248
registry-1.docker.io.	49	IN	A	34.205.194.204
registry-1.docker.io.	49	IN	A	52.22.113.111
```
also
```
> curl -v https://registry-1.docker.io/v2/

*   Trying 52.0.56.248...
* Connected to registry-1.docker.io (52.0.56.248) port 443 (#0)
(etc, ending in 401 http error)
```
also
```
> ping registry-1.docker.io
PING registry-1.docker.io (52.22.113.111): 56 data bytes
```

and yet same response from `docker pull` or `docker build` (where the Dockerfile has `FROM bitnami/minideb:jessie`)

**Comment by thaJeztah** [comment] 2017-05-24 15:13
@ianrose14 can you post the output of your `docker version` and `docker info`?

**Comment by ianrose14** [comment] 2017-05-24 17:45
It is worth noting that I just changed networks (from home to work) and now everything is working.  I don't use a proxy or VPN or anything at home (just comcast cable modem connecting to a Google OnHub) so I can't imagine what would be different there.  I'll be curious if the error re-occurs when I go home tonight.  Regardless...

```
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 43
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 39
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: ZO5F:DGXS:YMT5:6VKH:S2X6:AVSE:YCKI:CRQT:A5E2:5CD6:R7WO:YTFX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 28
 Goroutines: 40
 System Time: 2017-05-24T17:44:31.599552251Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-05-24 19:30
@ianrose14 from that output I see this is on docker for mac. If you run into the issue again, it may be worth reporting in the docker for mac issue tracker (https://github.com/docker/for-mac/issues) I seem to recall there have been some issues around DNS resolution, but not sure exactly which version that was with

**Comment by ianrose14** [comment] 2017-05-24 19:32
Roger, will do.  Thanks!
