### ISSUE TITLE
docker-proxy does not die / hangs around / blocks port

### ISSUE THREAD

**Issue by coderlol** [docker/docker#7856] opened 2014-09-03 06:13 UTC
I killed/stopped one of my containers and could not restart because its port had been taken.  It happened for Jenkins running inside Tomcat 7.0.50 on Ubuntu 14.04.1

As it turned out, docker-proxy did not die or go away when I docker killed/stopped jenkins.

docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 65150 -container-ip 172.17.0.16 -container-port 8080 

Docker Info

Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f

**Comment by jfrazelle** [comment] 2015-02-25 22:29
@coderlol this should be fixed now, please ping me if you are able to reproduce on latest version and the exact steps for reproducing and i will be happy to reopen

**Closed by jfrazelle** 2015-02-25 22:29 UTC

**Comment by orodbhen** [comment] 2015-06-17 16:06
Still happening with 1.6.0 on CentOS 7.

**Comment by jgornowich** [comment] 2015-06-25 13:23
Seeing this on CentOS 7 as well, even after upgrading docker to version 1.6.2.

**Comment by amaczuga** [comment] 2016-04-14 07:48
Can anyone confirm this has been fixed? And what is the fix version of docker?

**Comment by typeundefined** [comment] 2016-08-11 07:22
I think I've just bumped into the same bug.

After a computer restart, I can't start any docker container with port bindings (it says that the port is already allocated). So the situation looks as follows:
`docker ps -a` doesn't show any container BUT the docker-proxy process already blocks the ports specified in the containers I want to run (8080, 8998).

I'm just curious how to reset docker's state so it frees all ports?
Neither system reboot or `service docker restart` helps.

OS: KUbuntu 14.04,
`docker -D info` output:

> Containers: 0
>  Running: 0
>  Paused: 0
>  Stopped: 0
> Images: 167
> Server Version: 1.12.0
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 178
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: null host overlay bridge
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Security Options: apparmor
> Kernel Version: 4.2.0-42-generic
> Operating System: Ubuntu 14.04.5 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 15.57 GiB
> Name: nekrasov-ubuntu
> ID: G5B2:YAU2:DPBU:DEK2:JG6Y:GXAY:P5MJ:YK3O:WQMB:CU4D:GM7Z:FKBS
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): true
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> WARNING: No swap limit support
> Insecure Registries:
>  127.0.0.0/8

**Comment by typeundefined** [comment] 2016-08-11 07:40
Curious, after disabling userland proxy, the port is still blocked (but now it is owned by `dockerd` process instead of `docker-proxy`):

```
$ sudo netstat -tulpn | grep 8998
tcp6       0      0 :::8998                 :::*                    LISTEN      4153/dockerd
```

So the question remains: how to tell docker to free those ports?

**Comment by himulawang** [comment] 2016-08-11 08:24
We met the same problem. Even if restart the docker daemon.

To fix this, stop the docker daemon and remove /var/lib/docker/network/files/local-kv.db
Then restart daemon again.

This problem comes out very often. Please fix it ASAP.

**Comment by duselbaer** [comment] 2016-08-23 14:28
We ran into the same issue today after starting and stopping a complex docker-compose application.

After removing all containers and stopping docker the docker-proxy taking the port was gone but after restarting docker (still with no containers - docker ps -a is empty) the docker-proxy process has been restarted.

After removing the network which has been created by docker-compose the proxy was gone and we managed to restart the application.

docker 1.12.0, ubuntu 16.04

**Comment by vingrad** [comment] 2016-08-23 22:53
I have the same issue. Please fix.

**Comment by peec** [comment] 2016-08-29 08:21
Same issue. 

Running docker multicontainer docker (AWS Beanstalk) latest 1.11.2.

In AWS context:

Happens when you want to e.g. mount EFS instances, because you have to restart docker after mounting. And when you run docker restart, the ports become locked to the previous docker instance. So bascially the fixes I am using now is:

```
commands:
  # Here i do mounts etc ...
  # ...
  06stopdocker:
    command: "service docker stop"
  07killallnetworkbindings:
    command: 'sudo killall docker  > /dev/null 2>&1 || /bin/true'
  08removenetworkinterface:
    command: "rm -f /var/lib/docker/network/files/local-kv.db"
    test: test -f /var/lib/docker/network/files/local-kv.db
  09restart:
    command: "service docker start && start ecs"
```

**Comment by pschmitt** [comment] 2016-08-30 11:12
Same issue with docker 1.12.1 on ArchLinux

Thanks @himulawang for the fix

**Comment by vingrad** [comment] 2016-08-30 11:30
@jfrazelle can you please open again this issue?

**Comment by justincormack** [comment] 2016-08-30 12:01
Please can you open a new issue, and give details of how to reproduce, (and link here). A lot of code has changed since the original issue, it is better to open a new one.

**Comment by Gilead** [comment] 2016-09-20 10:59
Same issue here. Stopped a container but docker-proxy didn't release the port. Killed the relevant docker-proxy process, netstat says the port is free now but can't start the container nevertheless:
```

$ docker start mycontainer && docker logs -f mycontainer
Error response from daemon: driver failed programming external connectivity on endpoint mycontainer
(9a1493d....2227d65): Bind for 0.0.0.0:443 failed: port is already allocated
Error: failed to start containers: mycontainer
```

This is clearly a lie as the port is not allocated.

**Comment by emk** [comment] 2016-11-15 16:48
I just reproduced this on Ubuntu 16.04.1 LTS with kernel `4.4.0-47-generic #68-Ubuntu` and Docker version 1.12.2, build bb80604. There were no containers at all, and the docker-proxy processes reappeared after shutting down Docker and restarting it. Wish I had more data, but I wanted to confirm that this could be reproduced.

**Comment by amalaowala** [comment] 2017-04-28 19:11
This issue still happens for us, mainly during continuous integration were we spin up/down test containers regularly on the same Vms. Currently happening on Ubuntu 14.0.4 with a recent docker-ce version

jenkins@ip-10-0-12-99:~/workspace/dockerdebug$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:40:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:40:33 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by thaJeztah** [comment] 2017-04-28 20:53
@amalaowala please open a new issue with details and steps to reproduce (e.g. how is docker started etc)

**Comment by thaJeztah** [comment] 2017-04-28 20:55
I am locking the conversation on this issue, because the original issue reported here was resolved over two years ago; many things have changed and any issue encountered with current releases is very unlikely related to the original issue reported here.
