### ISSUE TITLE
Where is parameter --add-registry?

### ISSUE THREAD

**Issue by Amet13** [docker/docker#31840] opened 2017-03-15 08:20 UTC
**Description**

Does not working option `--add-registry`.

**Steps to reproduce the issue:**
1. Adding to `/etc/systemd/system/multi-user.target.wants/docker.service`
```
ExecStart=/usr/bin/docker daemon -H tcp://%H:2375 -H  unix:///var/run/docker.sock -H fd:// --storage-opt dm.basesize=7G --insecure-registry docker-registry:5000
```
2. Trying to pull image from registry `docker pull docker-registry:5000/image1`, all ok
3. How can I pull image like a `docker pull image1`

**Describe the results you received:**
I have no `/etc/sysconfig/docker` or `/etc/default/docker` files

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 236
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-8:1-486539392-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 7.516 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 16.03 GB
 Data Space Total: 107.4 GB
 Data Space Available: 81.57 GB
 Metadata Space Used: 27.6 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.12 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-229.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.614 GiB
Name: docker-master
ID: TV3S:U7WK:MMDI:OGTK:T2N4:JHZF:HNIF:CI52:I4XK:R5MN:NGIY:6I77
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Comment by thaJeztah** [comment] 2017-03-15 09:00
There's no `--add-registry` flag. I think it's in Red Hat's fork of Docker, and there was a proposal once (https://github.com/docker/docker/pull/10411).

> How can I pull image like a docker pull image1

The registry name is part of the image resolution, so if your registry is named `foo.mycompany.com`, then the image name will be `foo.mycompany.com/image1`. 

A "top level" image (e.g. `ubuntu`) refers to the official images at Docker Hub, and is an shorthand for `docker.io/library/ubuntu`.

I'll close this issue because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2017-03-15 09:00 UTC
Labels: area/distribution, version/1.11
