### ISSUE TITLE
MAC  docker: '--insecure-registry' is not a docker-machine command.

### ISSUE THREAD

**Issue by Dreampie** [docker/docker#18422] opened 2015-12-04 04:37 UTC
```
$  sudo docker-machine --insecure-registry 192.168.60.41:5000
Incorrect Usage.
```

**Comment by Dreampie** [comment] 2015-12-04 04:39
```
➜  ~  docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
➜  ~  docker info
Containers: 7
Images: 88
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: OFA3:NTK3:B5PB:KEBQ:FM5U:ZJ7A:NHYN:PJUC:UIBS:ZQM5:LHM5:SKLD
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 19
 System Time: 2015-12-04T04:38:27.643062853Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: dreampie
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
➜  ~  uname -a
Darwin localhost 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 19:41:34 PDT 2015; root:xnu-3247.1.106~5/RELEASE_X86_64 x86_64
```

**Comment by thaJeztah** [comment] 2015-12-04 13:27
Correct; the `--insecure-registry` option is an option for the docker daemon ("engine"). Docker machine is software to create and provision machines/hosts where the docker engine runs on.

To pass configuration settings for the daemon ("engine") when creating a new machine, see this section; http://docs.docker.com/machine/reference/create/#specifying-configuration-options-for-the-created-docker-engine. In this case, you're looking for the `--engine-insecure-registry` option, and you can use it when running `docker-machine create` (see the example on that page).


I'm going to close this issue, because this is not a bug, but I hope that the information above helps you solve your problem. Feel free to comment here after I've closed this issue :+1:

**Closed by thaJeztah** 2015-12-04 13:27 UTC

**Comment by Dreampie** [comment] 2015-12-04 16:43
yeah，i found it，but only for create，can not with modify？
