### ISSUE TITLE
Ubuntu 15.04 vivid can not start docker 1.7.0

### ISSUE THREAD

**Issue by netroby** [docker/docker#14035] opened 2015-06-19 07:32 UTC
```
root@vagrant-ubuntu-vivid-64:/var/lib/docker/devicemapper# service docker status -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2015-06-19 07:31:16 UTC; 12s ago
     Docs: https://docs.docker.com
  Process: 6704 ExecStart=/usr/bin/docker -d -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 6704 (code=exited, status=1/FAILURE)

Jun 19 07:31:16 vagrant-ubuntu-vivid-64 systemd[1]: Started Docker Application Container Engine.
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 systemd[1]: Starting Docker Application Container Engine...
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 docker[6704]: time="2015-06-19T07:31:16.596667126Z" level=error msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.doc...age-driver-option"
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 docker[6704]: time="2015-06-19T07:31:16.596752652Z" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: driver not supported"
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 docker[6704]: time="2015-06-19T07:31:16.596788016Z" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 systemd[1]: Unit docker.service entered failed state.
Jun 19 07:31:16 vagrant-ubuntu-vivid-64 systemd[1]: docker.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

```
I am using vagrant , with ubuntu 15.04

**Comment by netroby** [comment] 2015-06-19 07:32
```
root@vagrant-ubuntu-vivid-64:/var/lib/docker/devicemapper# docker -d -D
DEBU[0000] Registering GET, /version                    
DEBU[0000] Registering GET, /containers/ps              
DEBU[0000] Registering GET, /containers/{name:.*}/changes 
DEBU[0000] Registering GET, /events                     
DEBU[0000] Registering GET, /images/search              
DEBU[0000] Registering GET, /images/get                 
DEBU[0000] Registering GET, /images/{name:.*}/get       
DEBU[0000] Registering GET, /images/{name:.*}/history   
DEBU[0000] Registering GET, /containers/json            
DEBU[0000] Registering GET, /containers/{name:.*}/export 
DEBU[0000] Registering GET, /containers/{name:.*}/json  
DEBU[0000] Registering GET, /info                       
DEBU[0000] Registering GET, /containers/{name:.*}/top   
DEBU[0000] Registering GET, /containers/{name:.*}/logs  
DEBU[0000] Registering GET, /containers/{name:.*}/stats 
DEBU[0000] Registering GET, /exec/{id:.*}/json          
DEBU[0000] Registering GET, /_ping                      
DEBU[0000] Registering GET, /images/json                
DEBU[0000] Registering GET, /images/{name:.*}/json      
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws 
DEBU[0000] Registering POST, /commit                    
DEBU[0000] Registering POST, /images/create             
DEBU[0000] Registering POST, /images/load               
DEBU[0000] Registering POST, /images/{name:.*}/push     
DEBU[0000] Registering POST, /images/{name:.*}/tag      
DEBU[0000] Registering POST, /containers/{name:.*}/pause 
DEBU[0000] Registering POST, /containers/{name:.*}/rename 
DEBU[0000] Registering POST, /containers/{name:.*}/unpause 
DEBU[0000] Registering POST, /containers/{name:.*}/restart 
DEBU[0000] Registering POST, /exec/{name:.*}/resize     
DEBU[0000] Registering POST, /containers/create         
DEBU[0000] Registering POST, /containers/{name:.*}/kill 
DEBU[0000] Registering POST, /containers/{name:.*}/start 
DEBU[0000] Registering POST, /containers/{name:.*}/stop 
DEBU[0000] Registering POST, /containers/{name:.*}/resize 
DEBU[0000] Registering POST, /auth                      
DEBU[0000] Registering POST, /build                     
DEBU[0000] Registering POST, /containers/{name:.*}/wait 
DEBU[0000] Registering POST, /containers/{name:.*}/attach 
DEBU[0000] Registering POST, /containers/{name:.*}/copy 
DEBU[0000] Registering POST, /containers/{name:.*}/exec 
DEBU[0000] Registering POST, /exec/{name:.*}/start      
DEBU[0000] Registering DELETE, /containers/{name:.*}    
DEBU[0000] Registering DELETE, /images/{name:.*}        
DEBU[0000] Registering OPTIONS,                         
DEBU[0000] docker group found. gid: 120                 
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] devicemapper: driver version is 4.30.0       
ERRO[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option 
ERRO[0000] [graphdriver] prior storage driver "devicemapper" failed: driver not supported 
FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported 

```

**Comment by andrea-spoldi** [comment] 2015-06-19 08:13
Same with 14.04 trusty and 3.13.0-29-generic #53-Ubuntu SMP x86_64

**Comment by unclejack** [comment] 2015-06-19 10:44
This is why the Docker 1.7.0 daemon isn't starting up:
`Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option`

You were using devicemapper with a statically linked Docker binary. This is known to cause errors of all kinds because devicemapper ends up using a libdevmapper library which isn't linked to udev.

**Comment by francisdb** [comment] 2015-06-19 10:48
Same here, just did a `apt-get update` and `apt-get dist-upgrade`

```
Linux 3.16.0-31-generic #41-Ubuntu SMP Tue Feb 10 15:24:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 15.04

docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64

DEBU[0000] Registering OPTIONS,
DEBU[0000] Registering GET, /containers/{name:.*}/top
DEBU[0000] Registering GET, /events
DEBU[0000] Registering GET, /info
DEBU[0000] Registering GET, /images/{name:.*}/get
DEBU[0000] Registering GET, /containers/ps
DEBU[0000] Registering GET, /containers/{name:.*}/json
DEBU[0000] Registering GET, /images/{name:.*}/history
DEBU[0000] Registering GET, /containers/json
DEBU[0000] Registering GET, /containers/{name:.*}/export
DEBU[0000] Registering GET, /containers/{name:.*}/logs
DEBU[0000] Registering GET, /exec/{id:.*}/json
DEBU[0000] Registering GET, /images/search
DEBU[0000] Registering GET, /images/get
DEBU[0000] Registering GET, /images/{name:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/stats
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws
DEBU[0000] Registering GET, /_ping
DEBU[0000] Registering GET, /version
DEBU[0000] Registering GET, /images/json
DEBU[0000] Registering GET, /containers/{name:.*}/changes
DEBU[0000] Registering POST, /build
DEBU[0000] Registering POST, /containers/{name:.*}/restart
DEBU[0000] Registering POST, /containers/{name:.*}/wait
DEBU[0000] Registering POST, /containers/{name:.*}/resize
DEBU[0000] Registering POST, /containers/{name:.*}/attach
DEBU[0000] Registering POST, /containers/{name:.*}/exec
DEBU[0000] Registering POST, /exec/{name:.*}/start
DEBU[0000] Registering POST, /images/load
DEBU[0000] Registering POST, /images/{name:.*}/tag
DEBU[0000] Registering POST, /containers/{name:.*}/pause
DEBU[0000] Registering POST, /commit
DEBU[0000] Registering POST, /images/create
DEBU[0000] Registering POST, /containers/{name:.*}/unpause
DEBU[0000] Registering POST, /containers/{name:.*}/stop
DEBU[0000] Registering POST, /containers/{name:.*}/copy
DEBU[0000] Registering POST, /exec/{name:.*}/resize
DEBU[0000] Registering POST, /containers/{name:.*}/rename
DEBU[0000] Registering POST, /auth
DEBU[0000] Registering POST, /images/{name:.*}/push
DEBU[0000] Registering POST, /containers/create
DEBU[0000] Registering POST, /containers/{name:.*}/kill
DEBU[0000] Registering POST, /containers/{name:.*}/start
DEBU[0000] Registering DELETE, /containers/{name:.*}
DEBU[0000] Registering DELETE, /images/{name:.*}
DEBU[0000] docker group found. gid: 120
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
FATA[0000] Error starting daemon: error initializing graphdriver: "/var/lib/docker" contains other graphdrivers: devicemapper; Please cleanup or explicitly choose storage driver (-s <DRIVER>)
```

How do I clean up these drivers?

**Comment by adamwalach** [comment] 2015-06-19 13:19
I have the same problem on ubuntu 14.04.02 LTS (on AWS).
I am using installation script from https://docs.docker.com/installation/ubuntulinux/ (wget -qO- https://get.docker.com/ | sh). Should I use some other installation method? Is this issue connected with running docker on ec2 instance?

**Comment by jfrazelle** [comment] 2015-06-19 14:22
can you apt-get install the Linux-image-extras and use aufs you should not be using a static binary with devmapper the error is desired behavior

**Comment by icecrime** [comment] 2015-06-19 14:40
Here's the explanation:
- `devicemapper` storage driver is now impossible to use with a static binary (the one you get on Ubuntu when installing from the script), as explained above https://github.com/docker/docker/issues/14035#issuecomment-113469709 (for reference, this was introduced by #11412)
- A change introduced by #11999 makes it that if you previously used a different storage driver that the one which is currently preferred, we used that older one instead.

The end result is that your system favors something else that `devicemapper`, but because `/var/lib/docker/devicemapper/` exists, we are trying to use it nevertheless and fail because the binary is statically link.

In the end, removing `/var/lib/docker/devicemapper/` will fix the issue, but I do think we need to patch that.

**Comment by icecrime** [comment] 2015-06-19 14:53
FYI I use Docker with overlay on Ubuntu with `--storage-driver=overlay`, yet `mkdir /var/lib/docker/devicemapper && systemctl restart docker` was sufficient to reproduce.

@jfrazelle has a point here: we should never even consider prior storage driver data when I ask for a specific `--storage-driver`.

**Comment by vbatts** [comment] 2015-06-19 14:59
@icecrime we don't need to patch that. This behavior was due to the storage driver guessing feature. There is a flag to override this devicemapper failure for those that need to migrate images before removing the devicemapper driver or specifying another driver. cc @tianon

**Comment by icecrime** [comment] 2015-06-19 15:02
@vbatts If not a patch, we probably need docs. Also, don't you agree that in my case `--storage-driver=overlay` should bypass the election logic entirely?

**Comment by vbatts** [comment] 2015-06-19 15:05
Absolutely. That is intentional.

**Comment by vbatts** [comment] 2015-06-19 15:20
For users blocked `Udev Suppport: false`, that need to start their daemon long enough to save or push images, they need to pass their daemon the flag `--storage-opt dm.override_udev_sync_check=true`.
It will still complain, but will actually start. 

If this flag is provided then users will still hit #4036 and other issues.

**Comment by hacklschorsch** [comment] 2015-06-19 15:47
The script on my ubuntu VM that auto installs security patches (`cron-apt`) upgraded `lxc-docker` from 1.5.0 to 1.7.0 last night and now two containers I rely on won't start. Is it safe to downgrade / version pin to 1.5.0 or what would you recommend me to get my containers running again?

**Comment by jfrazelle** [comment] 2015-06-19 15:50
Can we help you debug those containers? Are you seeing errors. Also I think
this should be a new issue then. And I recommend downgrading to 1.6.2 then
instead

**Comment by hacklschorsch** [comment] 2015-06-19 16:03
I get pretty much @netroby s output, only my device mapper is version `4.28.0`. I'm running Ubuntu 14.04.2 LTS.

**Comment by hacklschorsch** [comment] 2015-06-19 16:07
Please beg my pardon if I'm posting in the wrong thread? I came here by googling the error message.

**Comment by hacklschorsch** [comment] 2015-06-19 16:10
I can also build a dynamic docker binary if that helps, if you say that'll solve my problem. I don't understand why the apt-source (https://get.docker.com/ubuntu) is shipping a static binary in the first place.

Do I have to migrate to aufs or can I just switch in the config? As you're saying above this is desired behavior.

**Comment by jwthomp** [comment] 2015-06-19 16:15
@jfrazelle Is the standard Docker install (wget -qO- https://get.docker.com/ | sh) providing a static binary? If so, then is it correct that we cannot use devicemapper with the standard install, and instead must use aufs? (Ubuntu 14.04)

If the above are both true, are there any plans to support a dynamically linked binary through the standard install, or will we only be able to use a dynamically linked binary if we do our own private builds?

Thanks!

**Comment by tianon** [comment] 2015-06-19 16:39
@icecrime I'm definitely +1, but I thought that's how it was already working :disappointed:

In the case of autodetection, we get an error if the autodetector can't use the storage driver we already have data for (or if we have multiple sources of data), but an explicit `--storage-driver` should let you happily cut yourself. :confused:

**Comment by vbatts** [comment] 2015-06-19 17:01
Why frowny face? This is best effort. We're not providing magic and there
are provided workarounds because we knew this would impact folks.

**Comment by tianon** [comment] 2015-06-19 17:03
@vbatts frowny face isn't for the best-effort -- I applaud the
best-effort.  The frowny face is because @icecrime is reporting that an
explicit "--storage-driver" (which should trump and override any
autodetection) doesn't seem to be actually overriding properly and he's
getting it erroring out, so I think we need to investigate whether that
"force override" is working as it should and avoiding any autodetection;
sorry for the confusion.

**Comment by icecrime** [comment] 2015-06-19 17:10
My true embarassement right now is that besides the explicit `--storage-driver` being insufficient to bypass the detection logic, I can't tell how bad the issue is. What's the proportion of users relying on automatic storage driver election will fall into this? Do 5% or 95% of Ubuntu users have a `/var/lib/docker/devicemapper/`? Was `devicemapper` ever the default on Ubuntu? If it was, we're screwed.

**Comment by vbatts** [comment] 2015-06-19 17:13
wait wait wait. no where did I see that providing an explicit `-s <other_driver>` was _not_ working.

**Comment by icecrime** [comment] 2015-06-19 17:15
@vbatts https://github.com/docker/docker/issues/14035#issuecomment-113537107

**Comment by jfrazelle** [comment] 2015-06-19 17:15
That was what we were saying, if @icecrime makes the devmapper dir he
cannot run overlay with -s

**Comment by vbatts** [comment] 2015-06-19 17:16
http://pastebin.com/wp8QFWDi

**Comment by vbatts** [comment] 2015-06-19 17:18
^ that is where the existing `devicemapper` directory exists.
```bash
vbatts@valse ~/tmp/tmp.GONneTuYIq/docker ((v1.7.0)) $ sudo ls /home/docker/
containers  devicemapper  graph  init  linkgraph.db  overlay  repositories-overlay  tmp  trust  volumes
```

**Comment by vbatts** [comment] 2015-06-19 17:21
Between https://github.com/docker/docker/blob/master/daemon/daemon.go#L640 and https://github.com/docker/docker/blob/master/daemon/graphdriver/driver.go#L108
it bypasses the "autodetect" logic

**Comment by icecrime** [comment] 2015-06-19 17:23
My bad, you're right there is a bypass...

**Comment by adamwalach** [comment] 2015-06-19 17:39
To summarize:
If I use default  docker settings on Ubuntu 14 and I am migrating from 1.6.2 to 1.7.0:
- I loose all my containers
- I have to remove /var/lib/docker/devicemapper directory or add -s aufs parameter to make it work
Is that correct?

**Comment by vbatts** [comment] 2015-06-19 17:48
@adamwalach 

# Summary

If your docker binary is statically compiled, it is unsupported and prevented from launching (by default) in  1.7.0.
Prior versions have displayed warnings, that they ignored.

# Do I lose all my containers?

Containers do not have to be lost.

You can build a dynamically linked binary, and continue using your existing images, with no extra work.

or 

The follow flag can be added to your daemon flags: `--storage-opt dm.override_udev_sync_check=true`
Either in `/etc/default/docker` or `/etc/sysconfig/docker` or wherever for your distro.
This flag will bypass the denial, and allow you to `docker save ...` or `docker push ...` your images.
In this way preserving them.


# Switching storage driver

Once you have saved images, then you can `rm -rf /var/lib/docker` to start clean.
If your docker binary is _still_ statically linked, then `devicemapper` will be skipped as an option, as it does not support your current setup.

Otherwise, you can add the following flag to your docker daemon: `-s overlay` (or `aufs`, etc)
This will explicitly choose another driver.

# Saved images

Once you have a setup with a different storage driver, you can reload the images you saved or pushed, with `docker load ...` or `docker pull ...` respectively.

**Comment by adamwalach** [comment] 2015-06-19 18:02
Thank you for the explanation.

**Comment by hacklschorsch** [comment] 2015-06-19 20:26
Thank you @adamwalach and @vbatts.

**Comment by netroby** [comment] 2015-06-19 23:19
On the production server, we have no chance to stop service. so we have to pin on the 1.5.0 docker . Thanks for you guys.

**Comment by viranch** [comment] 2015-06-20 00:30
Why is (https://get.docker.io/ubuntu) shipping a static binary? Is this planned to be fixed for this/upcoming release?

**Comment by pjv** [comment] 2015-06-21 01:59
I just upgraded docker on a production Ubuntu server (apt-get upgrade) and now I have a couple services that are borked. Until I can understand this issue, I would like to try to temporarily downgrade docker back to 1.6.2 so I can have my services running again. When I tried to `apt-get install docker=1.6.2` I got `Unable to find a version "1.6.2" for the package "lxc-docker"`

Anybody know what I can bang onto the command line kinda quick to downgrade to 1.6.2 and get my services back online?

**Comment by hacklschorsch** [comment] 2015-06-21 13:31
@pjv TL;DR version: see here for a manual how to compile from source http://icarobichir.com.br/posts/building-a-dynamically-linked-docker-v-1-6-2/

--------------

It took me a while to find a recent and working manual to build docker on ubuntu after understanding that the docker-provided lxc-docker package does not have a source package that I can access through APT.

With above blog entry I finally have a dynamic 1.6.2 build running. I couldn't build 1.7.0 because of dependencies on a version of `golang` that's not in Ubuntu 14.04.

**Comment by mgcrea** [comment] 2015-06-22 21:04
I'm encountering issues as well, see #14108, but no `devicemapper` folder in `/var/lib/docker`.

**Comment by pjv** [comment] 2015-06-22 22:28
I don't mean this as a rant or a flame -- really just trying to understand, but can I second the question that @viranch posed above? 

Why did my install of Docker, which I accomplished by typing the following onto the command line of my Ubuntu 14.04 (LTS) VPS:

`wget -qO- https://get.docker.com/ | sh`

Install an unsupported, statically compiled binary?

This is the Linux install page of the Docker site:
![2015-06-22 at 5 22 pm](https://cloud.githubusercontent.com/assets/327716/8294638/6d5b94b8-1903-11e5-8d43-cea6c841be8c.png)

What does "supported" mean in that context?

And is it really true that the 1.7.0 update had a known breaking change for Ubuntu 14.04 (LTS) [which I would guess is probably the statistically largest population of servers out there running Docker] and 15.0x as well?

Sorry if this is the wrong place to ask these questions.

**Comment by vbatts** [comment] 2015-06-23 02:15
Olivier, please include output of the issue you are getting

**Comment by mgcrea** [comment] 2015-06-23 12:22
@vbatts The output is:
```
# docker start foo_backend.production
Error response from daemon: Cannot start container foo.backend.production: Unable to setup mount point, neither source nor volume defined
Error: failed to start containers: [foo_backend.production]
```

**Comment by vbatts** [comment] 2015-06-23 16:49
Olivier, thanks. there error you're seeing is not the same, and should be
investigated separately.

On Tue, Jun 23, 2015 at 8:22 AM, Olivier Louvignes <notifications@github.com

**Comment by jwthomp** [comment] 2015-06-23 23:01
Is there an answer to @pjv and @viranch that can be pointed to?

**Comment by villeapvirtanen** [comment] 2015-06-24 08:19
This also killed our environment in aws, running 14.04.2 Ubuntu. I guess we can't keep auto upgrades on anymore.

We ran 
```bash
rm -rf /var/lib/docker/devicemapper
```

and restarted the world an everything works. This is really bad from my point of view as our uptime really took a hit due to this.

**Comment by Thorndike** [comment] 2015-06-24 11:54
I am in a bit of trouble here on Ubuntu 14.04 LTS. It seems devicemapper is not working as a storage driver. Switching to AUFS brings me back to https://github.com/docker/docker/issues/6980#issuecomment-105575220 and ovarlay seems to be not supported:
ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded. 
FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported 

What is the suggested solution I can use as storage driver on Ubuntu?

Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

**Comment by Jaykah** [comment] 2015-06-24 16:54
@pjv @hacklschorsch I created a gist for a dynamic 1.7, here it is: https://gist.github.com/Jaykah/e0f8182710f1a21b5c99

**Comment by ferrouswheel** [comment] 2015-06-24 19:50
This hit us too after an apt-get upgrade. Ubuntu 14.04.2 LTS

Might be worth adding a note during the dpkg installation for 1.7. If system is already configured to use devicemapper, warn the user they'll break their install if they continue. Showing a link to a guide for how to force unsafe use of devicemanager, export, and then import into a new storage driver would be handy too.

**Comment by Stelminator** [comment] 2015-06-24 22:48
Just another anecdote:

I originally installed 14.04, and did a rather simple partition scheme at the time, so my whole drive is just etx4.  I've since upgraded through 14.10 to 15.04.  I am running a 4.0 kernel from http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.0-vivid/, and have an install of docker from https://get.docker.com/ubuntu for easy compatibility with nvidia drivers.  I am trying to build CentOS images.

Building CentOS images precludes using overlay (rpms don't play nice), devicemapper/aufs at best give "unsupported" errors, so, it seems, my choices are currently:
 * compile from source
 * repartition (btrfs)
 * downgrade

I'll probably compile it when I get a chance, but for today I'm just going to downgrade.  FWIW, my jenkins slaves and marathon hosts are all using btrfs, and so won't care.  I was glad to fine the answer to my problem.

**Comment by icecrime** [comment] 2015-06-25 20:13
I'm trying to get a clear idea about our next move here. My current feeling is that:

- We shouldn't break people who use `devicemapper` on Ubuntu with an explicit `--storage-driver=devicemapper`, *even* with a static binary (after all that's what you asked for)
- The automatic detection logic seems flawed as it ends up electing something it *can't* use: I'm thinking a better error message ("you have a prior `devicemapper` storage driver, use `--storage-driver` to use it") is a minimum.

**Comment by icecrime** [comment] 2015-06-25 20:31
Summing up my thoughts:

| Scenario | Behavior 1.7.0 | Proposal 1.7.1 |
|-------------|---------------------|---------------------|
| `--storage-driver=devicemapper` | Error: unsupported | Warning: unreliable setup |
| `--storage-driver=devicemapper -storage-opt dm.override_udev_sync_check=false` | Ok | Warning: unreliable setup |
| `--storage-driver=` with `devicemapper/` dir only | Error: unsupported | Error: unsupported (explain workaound) |
| `--storage-driver=` with `aufs/` and `devicemapper/` dirs | Error: unsupposed | Error: unsupported (explain workaound) |

**Comment by rtrauntvein** [comment] 2015-06-26 00:19
This was pretty ugly.  The rollback to 1.6.2 per @pjv seemed to work here. Ubuntu 14.04.2 LTS

**Comment by bberberov** [comment] 2015-06-26 13:42
@rtrauntvein If you succeed rolling back, please share how you did it.  My docker 1.6.2 is still broken on Ubuntu 14.04.2 LTS.

**Comment by igor-pinchuk** [comment] 2015-06-26 14:50
That hit me as well, fortunately on staging server only.
Docker was fixed by rolling back to 1.5.0 (apt-get install lxc-docker-1.5.0)

**Comment by Stelminator** [comment] 2015-06-26 15:27
@bberberov I ran `rm -rf /var/lib/docker` to nuke images/containers/metadata after downgrading to 1.6.2.

**Comment by rtrauntvein** [comment] 2015-06-26 16:55
I did this:

```
service docker stop
rm -rf /var/lib/docker/devicemapper
sudo apt-get install lxc-docker-1.6.2
service docker start
```

**Comment by viranch** [comment] 2015-06-26 18:01
Hey FYI @bberberov @rtrauntvein @Stelminator I didn't have to nuke `/var/lib/docker`. I just did:

```bash
service docker stop
apt-get install lxc-docker-1.6.2 # this replaces 1.7.0
service docker start
```

**Comment by fjmk** [comment] 2015-06-27 20:40
I ma running docker 1.7.0 build 0baf609 on my 14.04.2 LTS workstation now.

It was not starting with the message:
```bash
Error starting daemon: error initializing graphdriver: "/var/lib/docker" contains other graphdrivers: devicemapper; Please cleanup or explicitly choose storage driver```

Changed /etc/default/docker with the line:
```bash
DOCKER_OPTS="--storage-driver=aufs"
```
and it is working again.

Can I expect problems in the future?

**Comment by Thorndike** [comment] 2015-06-29 05:19
@fjmk: check for https://github.com/docker/docker/issues/6980#issuecomment-105575220

**Comment by frntn** [comment] 2015-06-29 09:59
@fjmk : I did the exact same thing and everything works fine.

The problem described in #6980 is related to AUFS itself and exists prior docker 1.4
So I would say we shouldn't expect any **new** problems.

**Comment by calavera** [comment] 2015-06-29 23:33
@icecrime I'm pretty sure `--storage-driver=overlay` bypasses the storage scan, regardless the directories you have in the host. This is the line of code where the driver you set in the cli is checked:

https://github.com/docker/docker/blob/master/daemon/graphdriver/driver.go#L108

I can see the message in my log:

```
DEBU[0000] [graphdriver] trying provided driver "aufs"
```

I'm going to modify the scan logic to fulfill what's in your table.

**Comment by bberberov** [comment] 2015-06-30 14:30
@Stelminator @rtrauntvein @viranch That is what I did and it did not work.  I tried 1.6.0, 1.6.1, and 1.6.0 on three separate kernels and still broken.  I did a fresh install of 14.04.1 in a VM, installed just docker-1.6.2, and that did not work either.

**Comment by vagifverdi** [comment] 2015-07-01 01:14
Any resolution on this?
I have the same problem, docker does not autostart. I'm on ubuntu 15.04.
Installed docker via wget -qO- https://get.docker.com/ | sh
my /var/lib/docker looks like this:
aufs  containers  graph  init  linkgraph.db  repositories-aufs  tmp  trust  volumes

As you see i do not use devicemapper. Yet the docker service still does not autostart.
When i tried manually enable it via systemctl enable, it did start upon restarting machine. But now autofs inside autostarted (--restart=always) containers is not working anymore. So i have to stop containers and run them again, and then autofs works fine inside containers.

Whats the solution for this?

**Comment by higkoo** [comment] 2015-07-01 04:41
Yes, thanks!

I meet this error when update docker 1.6.2 to 1.7.0, but not appear in new system.
So, I backup and remove devicemapper. Then it seems OK.

**Comment by rhvgoyal** [comment] 2015-07-01 17:49
Hi All,

This breakage is intentional. Those who are using statically linked docker 1.6 with devicemapper storage driver, they are already broken. It is an unreliable setup and there have been plenty of issues already raised.

So it was decided that in 1.7, we will fail to start if a user has a broken setup. I had raised the concern about upgrade case but people did not want broken setups to continue instead wanted users to make an informed decision.

https://github.com/docker/docker/pull/11412#issuecomment-82493921

So, now that you know using statically linked docker is broken with devicemapper you have two options.

- If you can live with devicemapper unreliability with static binary and just want your working setup as
you had in 1.6, simply specify --storage-opt dm.override_udev_sync_check=true and restart docker daemon and that should get you back your old behavior.

- Save your work and switch to a different storage driver.

In long term, ask distribution to ship dynamically linked docker so that devicemapper driver is properly supported.

**Comment by bitliner** [comment] 2015-07-01 18:13
same thing of @fjmk and now it works fine

**Comment by pjv** [comment] 2015-07-01 18:14
Thanks for the clear explanation @rhvgoyal. So here is my question re-posed again:

Given that I installed Docker by piping a wget from get.docker.com, my impression is that my "distribution" is docker.com. If that's a wrong assumption, it might be useful to say so and say why. If it's a right assumption, then consider this my request to Docker to stop distributing unsupported configurations from get.docker.com, or stop intentionally breaking what Docker is distributing (perhaps instead shipping something that will either do whatever the "right thing" is, or at the very least give a clear explanation of what the issue is and what the options for fixing or working around the issue for those sysadmins like myself that are not Docker devs, but are concerned with minimizing downtime on their systems).

**Comment by rhvgoyal** [comment] 2015-07-01 18:18
@pjv 

docker is already doing what you are asking. "Docker to stop distributing unsupported configurations".  Instead of removing the bits completely (as it works with dynamic build), it will fail to start at run time. And that's what is happening.

So in a way docker is doing right thing by not starting on wrong configurations and asking users to make right choices.

**Comment by viranch** [comment] 2015-07-01 18:23
@rhvgoyal Thanks for the response. Are you saying instead of shipping a linked docker that properly uses devicemapper with proper udev sync, you decided to keep shipping a static build _and_ intentionally break devicemapper?

> did not want broken setups to continue

The reason it was broken was due to static build being shipped, isn't that a problem on docker's side?

> ask distribution to ship dynamically linked docker

Why does [docker-managed repository](https://get.docker.com/ubuntu/) also ship a statically linked docker instead of shipping dynamically linked docker given it would actually fix udev sync support?

I'm not sure why its wrong to use devicemapper when udev sync support can be enabled with dynamic docker.

**Comment by rhvgoyal** [comment] 2015-07-01 18:26
I don't know why docker ships statically linked binary. I will let docker folks answer that. That's a separate conversation altogether.

**Comment by viranch** [comment] 2015-07-01 18:27
@rhvgoyal cool, just wanted to confirm again: there's no harm in using dynamic docker with devicemapper, is there?

**Comment by rhvgoyal** [comment] 2015-07-01 18:31
@viranch 

Dynamically linked docker should work well with devicemapper graph driver.

We at redhat support running dynamically linked docker with devicemapper driver and that's what we test and fix and it should work.

There might be cases where things are broken even on dynamic docker but those should be distribution specific issues, if any.

**Comment by vagifverdi** [comment] 2015-07-01 18:34
How would one get dynamically linked docker for ubuntu?

**Comment by viranch** [comment] 2015-07-01 18:37
@vagifverdi you can use this gist I wrote: https://gist.github.com/viranch/7d3495bfdc9e54b3d5ff

**Comment by vagifverdi** [comment] 2015-07-02 00:28
@viranch I used your script and it complied and installed dynamically linked docker.
But now when i try to start it i get this error:
Failed to start docker.service: Unit docker.socket failed to load: No such file or directory.

I checked the docker.service file and it does mention that docker requires docker.socket.
I restarted vm, still same error on trying to start docker.
Perhaps i'm missing something?

**Comment by LK4D4** [comment] 2015-07-02 15:30
@vagifverdi You can download systemd unit and socket here https://github.com/docker/docker/tree/master/contrib/init/systemd

**Closed** 2015-07-02 18:33 UTC

**Comment by viranch** [comment] 2015-07-04 08:13
@vagifverdi apologies, my gist is for ubuntu 14.04, might not work with systemd.

**Comment by baptistedonaux** [comment] 2015-07-08 08:28
@vbatts Thanks ! Solution describes works for me !

**Comment by cu** [comment] 2015-07-08 21:20
I installed docker 1.5.0 on debian jessie from the get.docker.com repository via apt-get. Today, I upgraded to docker 1.7.0 via apt-get and I get the error noted above when attempting to start the docker service.

I appreciate that docker is open source and all but reading through this thread, I get the impression that the docker folks don't really care about breaking people's production servers via what should have been a trivial upgrade. I don't know much about docker internals and didn't know I would be expected to in order to use docker. I don't know what a graphdriver is and I certainly did not chose one over any other when installing docker initially. If the previous configuration was unreliable or broken in some way, why was it ever used in the first place? There was not even so much as a mention of this in the either the release notes or the changelog. Even for an open source project, this is frankly quite unacceptable and speaks of poor QA, release management and leadership.

I downgraded to 1.6.2 via instructions found above and my configuration is working again. Looking forward to a fix for this in 1.7.1.

**Comment by caarlos0** [comment] 2015-07-23 13:32
I did `mv /var/lib/docker{,old}` and this fixed the problem

**Comment by jchannon** [comment] 2015-07-27 14:48
Thanks @caarlos0

**Comment by thaJeztah** [comment] 2015-07-27 22:01
In case you missed it; For those looking for dynamically linked binaries; official APT/YUM repositories are now live, and docker 1.7.1 can installed from that repository. Instructions and more information can be found in the blog post here: http://blog.docker.com/2015/07/new-apt-and-yum-repos/

**Comment by pjv** [comment] 2015-07-31 17:16
hey @viranch, have you converted from the compiled 1.7.0 docker you set up in your gist to the new dynamic binary apt repo for 1.7.1? if so, did you happen to note the steps you took to do so?

**Comment by viranch** [comment] 2015-08-01 06:24
@thaJeztah awesome!

@pjv I just upgraded to 1.7.1, and a simple `curl -sSL https://get.docker.com/ | sh` works without any extra effort. By "works" I mean, you don't lose your containers and get the upgraded docker engine to choose `devicemapper` as the storage driver (because there are containers that use it, I think) as opposed to the default `aufs` :)

**Comment by thaJeztah** [comment] 2015-08-01 12:06
@viranch be aware that the *default* devicemapper configuration is not intended for production use. The default settings are the "just works" configuration, but quite bad from a performance perspective. Tweaking those settings cannot be done automatically, because they depend on your use-case; One of the reasons AUFS is used as the default on Ubuntu (on a clean install)

**Comment by viranch** [comment] 2015-08-01 20:05
@thaJeztah I'm aware. Thanks for the heads up.

How feasible would it be to implement the feature of being able to select the storage driver per container in docker engine? That way older systems can move away from devicemapper more easily. Can the docker engine be run with AUFS but fallbacks to legacy storage driver for existing containers that use it and any new containers use AUFS?

**Comment by thaJeztah** [comment] 2015-08-01 21:29
@viranch I actually think I saw @rhvgoyal playing with that though on another PR; it may be technically possible, but it's not something with a high priority at the moment (at least, not something that's been actively worked on afaik)

**Comment by FelikZ** [comment] 2015-10-30 01:41
@fjmk thanks, aufs and removing devicemapper helps!
