### ISSUE TITLE
docker 1.6.0: --ulimit stack=32768:32768 sets the limit to 32

### ISSUE THREAD

**Issue by ramonvanstijn** [docker/docker#12957] opened 2015-05-04 11:30 UTC
Description of problem:
When --ulimit stack=32768:32768 is used as an argument for the docker run command the container is configured with the stack size set to 32.

docker version:
```
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): bdbc177
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): bdbc177
OS/Arch (server): linux/amd64
```
docker info:
```
Containers: 4
Images: 18
Storage Driver: devicemapper
 Pool Name: docker-253:0-36666502-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.365 GB
 Data Space Total: 107.4 GB
 Data Space Available: 954.3 MB
 Metadata Space Used: 2.474 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 954.3 MB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.1.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 3.696 GiB
Name: dockerdev
ID: OTYA:LAVJ:W6RM:7ZKW:EPEQ:IQIJ:LYYD:UFHS:CZLQ:R5MV:GG36:YHGU
```
uname -a:
```
Linux dockerdev 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 27 03:04:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
Environment details (AWS, VirtualBox, physical, etc.):
VMware virtual machine

How reproducible:

Steps to Reproduce:
1. ```docker run --rm -it --ulimit stack=32768:32768 busybox sh```
2. ```/ # ulimit -s```

Actual Results:
```
32
```
Expected Results:
```
32768
```
Additional info:
In order to rule out a problem with the busybox image I have also tried using the ubuntu and centos images and they have the same problem.

**Comment by cpuguy83** [comment] 2015-05-04 14:21
I think there's some serialization error on 1.6 that's causing this... can you check with a master binary?
I've also seen it, when using a really high number, go to 0 (which is definitely fixed on master).

**Comment by ramonvanstijn** [comment] 2015-05-04 15:07
The problem persists with today's master binary.

docker version
```
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 56f7da3
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 56f7da3
OS/Arch (server): linux/amd64
```

**Comment by dqminh** [comment] 2015-05-23 17:21
@ramonvanstijn I think the behavior is correct here. It sets the limit value as number of bytes, while ulimit reports the number of kb. So 32768 bytes == 32 kb

**Comment by ramonvanstijn** [comment] 2015-05-23 20:54
Why is it in bytes? In a shell you specify the value according to the unit,
Kb in this case. It would be good if docker handles the value in the same
way.

I ran some additional tests and it turns out the maximum value I can
specify for the stack size is 999999 bytes (roughly 976 Kb). A higher
number and the container will not start:

$ docker run --rm -it --ulimit stack=1000000:1000000 busybox sh
argument list too long
FATA[0000] Error response from daemon: Cannot start container
b3e961b3db7732213c7685140f65f31f606aeae1a06cd1f5765dca45f06ea3bc: [8]
System error: argument list too long

So in the end the stack size can't be changed beyond 976 Kb and I think
this should be fixed.

**Comment by cpuguy83** [comment] 2015-05-23 22:02
Pretty sure the max size issue is fixed on master, please test if you can.
Builds master.dockerproject.com

**Comment by ramonvanstijn** [comment] 2015-05-24 07:14
Tested with the master binary from May 16th (today's master binary fails to
start on my machine), the max size is indeed fixed in that version.

2015-05-24 0:03 GMT+02:00 Brian Goff <notifications@github.com>:

**Comment by thaJeztah** [comment] 2015-05-24 19:53
> today's master binary fails to start on my machine

There have been some big changes (integration of libnetwork and volume plugins), so it's possibly there are some temporary regressions, but don't hesitate to report any issue you encounter running those builds.

@ramonvanstijn I'm going to close this issue because it has been resolved on master, but feel free to comment after it has been closed.

(Wondering - You don't happen to be my cousin and born in Lisse? :smile:)

**Closed by thaJeztah** 2015-05-24 19:53 UTC

**Comment by ramonvanstijn** [comment] 2015-05-26 06:57
@thaJeztah I was born in Utrecht, we could still be cousins though :wink:
