### ISSUE TITLE
container failed to start with "invalid argument"

### ISSUE THREAD

**Issue by xingzhao-tt** [docker/docker#22330] opened 2016-04-26 09:22 UTC
Hi Docker professors,

I am trying to run docker on one ARM-based board, while I try to start my private image, docker failed to start the container, following is the detail information.

Looking forward to your help.

docker version:
```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   7fd53f7-unsupported
 Built:        Sat Apr 23 09:30:12 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   7fd53f7-unsupported
 Built:        Sat Apr 23 09:30:12 2016
 OS/Arch:      linux/arm
```
docker info:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.0-dev
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0
Operating System: <unknown>
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 1.966 GiB
Name: localhost
ID: KHZ7:BIXU:OX3I:ECGV:JQER:3LUG:HSCJ:YIUW:YO4F:V7X3:5OOA:4AJD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 32
 System Time: 2016-04-26T09:19:27.794175934Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure registries:
 127.0.0.0/8
```
Here is the debug log:

```
DEBU[7569] Calling GET /v1.24/version                   
DEBU[7575] Calling GET /v1.24/info                      
WARN[7575] Could not get operating system name: Error opening /usr/lib/os-release: open /usr/lib/os-release: no such file or directory 
DEBU[7690] Calling POST /v1.24/containers/create        
DEBU[7690] form data: {"AttachStderr":true,"AttachStdin":true,"AttachStdout":true,"Cmd":["/system/bin/sh"],"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"AutoRemove":false,"Binds":null,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"Cgroup":"","CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuCount":0,"CpuPercent":0,"CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DiskQuota":0,"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IOMaximumBandwidth":0,"IOMaximumIOps":0,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMaximumBandwidth":0,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"ShmSize":0,"StorageOpt":{},"UTSMode":"","Ulimits":null,"UsernsMode":"","VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"android_image","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":true,"StdinOnce":true,"Tty":true,"User":"","Volumes":{},"WorkingDir":""} 
DEBU[7690] Creating dest directory: /var/lib/docker/vfs/dir/a06a5b652de50cec60c6d79d19e2c2c7699c62de9acc75a970a265aa4e47eb82-init 
DEBU[7690] Calling TarUntar(/var/lib/docker/vfs/dir/dd4743cbe8ed54f70543b3e4a4bd68cef06ddd0ae1ff48cd6b8fd00fbb871782, /var/lib/docker/vfs/dir/a06a5b652de50cec60c6d79d19e2c2c7699c62de9acc75a970a265aa4e47eb82-init) 
DEBU[7690] TarUntar(/var/lib/docker/vfs/dir/dd4743cbe8ed54f70543b3e4a4bd68cef06ddd0ae1ff48cd6b8fd00fbb871782 /var/lib/docker/vfs/dir/a06a5b652de50cec60c6d79d19e2c2c7699c62de9acc75a970a265aa4e47eb82-init) 
DEBU[7690] Creating dest directory: /var/lib/docker/vfs/dir/a06a5b652de50cec60c6d79d19e2c2c7699c62de9acc75a970a265aa4e47eb82 
DEBU[7690] Calling TarUntar(/var/lib/docker/vfs/dir/a06a5b652de50cec60c6d79d19e2c2c7699c62de9acc75a970a265aa4e47eb82-init, /var/lib/docker/vfs/dir/a06a5b652de50cec60c6d79d19e2c2c7699c62de9acc75a970a265aa4e47eb82) 
DEBU[7690] TarUntar(/var/lib/docker/vfs/dir/a06a5b652de50cec60c6d79d19e2c2c7699c62de9acc75a970a265aa4e47eb82-init /var/lib/docker/vfs/dir/a06a5b652de50cec60c6d79d19e2c2c7699c62de9acc75a970a265aa4e47eb82) 
DEBU[7690] container mounted via layerStore: /var/lib/docker/vfs/dir/a06a5b652de50cec60c6d79d19e2c2c7699c62de9acc75a970a265aa4e47eb82 
DEBU[7690] Calling POST /v1.24/containers/fbeb5a71b415fd79a8d8f4567763be39780c1be90b78ff2ab455e831dec96d1b/attach?stderr=1&stdin=1&stdout=1&stream=1 
DEBU[7690] attach: stdin: begin                         
DEBU[7690] attach: stderr: begin                        
DEBU[7690] attach: stdout: begin                        
DEBU[7690] Calling POST /v1.24/containers/fbeb5a71b415fd79a8d8f4567763be39780c1be90b78ff2ab455e831dec96d1b/start 
DEBU[7690] container mounted via layerStore: /var/lib/docker/vfs/dir/a06a5b652de50cec60c6d79d19e2c2c7699c62de9acc75a970a265aa4e47eb82 
DEBU[7690] Assigning addresses for endpoint nostalgic_liskov's interface on network bridge 
DEBU[7690] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[7690] Assigning addresses for endpoint nostalgic_liskov's interface on network bridge 
INFO[7690] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4] 
INFO[7690] IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844] 
DEBU[7690] Programming external connectivity on endpoint nostalgic_liskov (49f2502140a748c8ecca09b4427430f2bf6c81c1c6927a0a084c125d4a76d1c6) 
DEBU[7690] attach: stdout: end                          
DEBU[7690] attach: stdin: end                           
DEBU[7690] attach: stderr: end                          
DEBU[7690] Revoking external connectivity on endpoint nostalgic_liskov (49f2502140a748c8ecca09b4427430f2bf6c81c1c6927a0a084c125d4a76d1c6) 
DEBU[7691] Releasing addresses for endpoint nostalgic_liskov's interface on network bridge 
DEBU[7691] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2) 
ERRO[7691] Handler for POST /v1.24/containers/fbeb5a71b415fd79a8d8f4567763be39780c1be90b78ff2ab455e831dec96d1b/start returned error: invalid argument 
DEBU[7691] Calling DELETE /v1.24/containers/fbeb5a71b415fd79a8d8f4567763be39780c1be90b78ff2ab455e831dec96d1b?force=1&v=1 
DEBU[7691] Closing buffered stdin pipe 
```

Thanks,
Felix

**Comment by thaJeztah** [comment] 2016-04-26 12:13
Is this just on that image, or on other images as well? Without a way to reproduce, it's hard for people to assist.

Given that we currently don't have official support yet for ARM based devices, and you're running a custom built docker daemon, I'm not sure there's much we can help here. Please keep in mind that the issue tracker is for tracking bugs, not a generic support forum. This question may be better suited on;

- the [docker-dev](https://groups.google.com/forum/#!forum/docker-dev) Google group
- the #docker-dev IRC channel on freenode

I'll close this issue here, for the reasons above, but feel free to comment here after

**Closed by thaJeztah** 2016-04-26 12:13 UTC

**Comment by xingzhao-tt** [comment] 2016-04-27 06:23
Hi Sebastiaan,

It have looked for help from docker-dev group, unfortunately not receive any response yet. So looking for help from the issue tracker.

Now this issue is blocking my project to go ahead. Could you help give me some hint what might be wrong, what does "invalid argument" mean, and how to debug it? 

I would really appreciate you spending precious time to help me.

Thanks,
Felix
