### ISSUE TITLE
docker swarm join swallows errors

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#26213] opened 2016-08-31 19:26 UTC
When joining as a manager, and the join fails (for example, when specifying an incorrect `--advertise-addr` value), `docker swarm join` does not report an error. Instead runs for awhile, and then exits silently, leaving the node in a bad state.

Example:

```
root@ip-172-31-12-164:~# docker swarm join --token <token> --advertise-addr 1.2.3.4 <manager addr>

root@ip-172-31-12-164:~# docker node ls


Error response from daemon: rpc error: code = 2 desc = raft: no elected cluster leader
```

cc @tonistiigi

**Comment by srodman7689** [comment] 2016-09-15 00:38
#dibs

**Comment by srodman7689** [comment] 2016-09-15 00:57
@aaronlehmann I am working to replicate this issue in my local environment. I have a few questions for you. First, is the ip address that you used for the --advertise-addr legitimate and just not for that host or on a different network that cant be reached by the rest of the swarm? Also, when you swarm join is that machine the first machine in the cluster?

**Comment by srodman7689** [comment] 2016-09-15 00:58
Sorry if I am stepping on toes here. Just trying to get my feet wet with the docker project. We use docker for our app at work so I felt like it would be really cool to be able to contribute to a product that we use.

**Comment by aaronlehmann** [comment] 2016-09-15 01:02
@srodman7689: Have a look at https://github.com/docker/docker/issues/26167, where this was first noticed. The symptoms in that issue were caused by the advertise address inadvertently getting set to an internal IP that the other managers couldn't reach.

**Comment by srodman7689** [comment] 2016-09-15 01:04
@aaronlehmann great, thanks man! I will start looking into that now.

**Comment by srodman7689** [comment] 2016-09-15 01:36
I reproduced the error specified above. Now just gotta figure out how to fix it lol.

**Comment by thaJeztah** [comment] 2016-09-20 13:12
@srodman7689 how's it going? Do you need help?

**Comment by srodman7689** [comment] 2016-09-20 13:17
@thaJeztah so far I haven't been able to pin point where I should add the error message. I suppose that I might have started on a issue that was too deep in the code base. Help would be greatly appreciated.

**Comment by thaJeztah** [comment] 2016-09-20 13:41
@aaronlehmann would you be able to give some pointers where to look in the code and/or possibly an example?

@srodman7689 also feel free to join the #docker-dev IRC channel on freenode, and ask for assistance (not sure I'm personally able to assist here, but there's usually a someone around to help out)

**Comment by srodman7689** [comment] 2016-09-20 13:45
@thaJeztah Thank you! I will check in with those guys after work and see if I can get any farther.

**Comment by aaronlehmann** [comment] 2016-09-20 18:48
It looks like this code path is followed in `Join` (`daemon/cluster/cluster.go`):

```go
        case <-n.Ready():
                go c.reconnectOnFailure(n)
                return nil
```

So the channel returned by `Ready()` gets closed, but that probably shouldn't be happening, because the new node doesn't join raft successfully.

Looking at what causes this channel to be closed, it's triggered by both the `agentReady` and `managerReady` channels being closed. In particular, `managerReady` is being closed prematurely. The `runManager` function in swarmkit's `agent/node.go` passes that channel to `initManagerConnection` 

`initManagerConnection` performs a health check, and closes the channel once the health check succeeds.

Next, I look at the server-side code for the health check, in `(*Manager).Run)`:

```go
        // Set the raft server as serving for the health server
        healthServer.SetServingStatus("Raft", api.HealthCheckResponse_SERVING)
        localHealthServer.SetServingStatus("ControlAPI", api.HealthCheckResponse_SERVING)

        defer func() {
                m.server.Stop()
                m.localserver.Stop()
        }()

        if err := m.RaftNode.JoinAndStart(); err != nil {
                return fmt.Errorf("can't initialize raft node: %v", err)
        }
```

The `ControlAPI` health check is set to `SERVING` status before raft is started, which looks wrong to me. This seems to be the source of the problem. It lets the code in `agent/node.go` believe the manager has initialized successfully when it has not even joined raft yet.

If I remove this `localHealthServer.SetServingStatus` call to just after `JoinAndStart`, it seems to fix the immediate problem. Instead of getting no error, I get:

```
Error response from daemon: Timeout was reached before node was joined. The attempt to join the swarm will continue in the background. Use the "docker info" command to see the current swarm status of your node.
```

So I think a PR to https://github.com/docker/swarmkit that moves the initialization of the `ControlAPI` health check later should fix this bug. Note that the `Raft` health check initialization needs to stay where it is, because that's necessary for joining the raft cluster.

Let me know if you want to submit such a PR, or if I've spoiled all the fun, I can do it.

**Comment by srodman7689** [comment] 2016-09-20 18:57
I can definitely do the PR. its the least I can do. Would it be ok to submit it after work tonight? It will be around 7 pm CST if that is ok.

**Comment by aaronlehmann** [comment] 2016-09-20 19:01
Yeah, no time limit :)

**Comment by srodman7689** [comment] 2016-09-20 19:09
Also, if raft isn't started yet, should we move the health setting
`healthServer.SetServingStatus("Raft", api.HealthCheckResponse_SERVING)`
to after the join and start as well?

**Comment by srodman7689** [comment] 2016-09-20 19:10
And thanks for that man. I am really excited to start contributing to docker and you guys are awesome!

**Comment by thaJeztah** [comment] 2016-09-20 19:18
@srodman7689 thank _you_ for contributing, it's really appreciated. Also, don't worry to make mistakes; we've all been there, and are there to help you (bear with us if it's busy and we don't respond in time :sweat_smile:)

**Comment by srodman7689** [comment] 2016-09-20 19:22
I definitely will. And thank you again.

**Comment by aaronlehmann** [comment] 2016-09-20 19:27
> Also, if raft isn't started yet, should we move the health setting
> healthServer.SetServingStatus("Raft", api.HealthCheckResponse_SERVING)
> to after the join and start as well?

Nah, it's a bit of a special case. `JoinAndStart` needs this health check to be initialized already so the other side can verify its reachability.

**Comment by srodman7689** [comment] 2016-09-20 19:36
Cool. thx.

**Comment by srodman7689** [comment] 2016-09-20 19:43
I was able to go ahead and create the pull request https://github.com/docker/swarmkit/pull/1555

**Comment by icecrime** [comment] 2016-09-26 20:21
Thanks @srodman7689! :+1:

@aaronlehmann Can we close this issue? I'm not sure the fix made it into a SwarmKit vendoring yet.

**Comment by aaronlehmann** [comment] 2016-09-26 21:17
> Thanks @srodman7689! :+1:
> 
> @aaronlehmann Can we close this issue? I'm not sure the fix made it into a SwarmKit vendoring yet.

Not yet.

**Comment by thaJeztah** [comment] 2016-11-17 01:21
Looks like this was vendored (but I don't recall which version)

**Closed by thaJeztah** 2016-11-17 01:21 UTC
Labels: area/swarm, exp/intermediate, kind/bug, status/claimed
