### ISSUE TITLE
docker run -t -i and NO option (-d), terminal closed -> container still lives

### ISSUE THREAD

**Issue by JonasT** [docker/docker#14391] opened 2015-07-04 11:58 UTC
When I run something with ```
docker run -t -i``` and NO option ```
-d```, if I close the terminal with the running thing in it the container still lives afterwards (confirmed with ```
docker ps```). This runs totally contrary to the intuition of a non-detached thing running in my terminal which behaves like its bound to it like a regular process - but then unexpectedly survives killing the terminal, which can lead to unexpected background stuff still running when a user would assume it to be terminated.

Remember the times when you ssh'ed into a server and ran ```
apt-get upgrade``` through the ssh session, but then you forgot to use ```
nohup``` and your session died due to connection problems and the upgrade process was instant-killed during the upgrade since it was bound to your ssh terminal? Yes, this is what I expected to happen here. But it's not what docker was doing.

This behavior is very useful when I *do* want a process to stop, and it's somewhat unexpected ```
docker run``` doesn't seem to be following this behavior since 99% of all other non-detached linux commands and processes do.

Is this intended? Is this a bug? Whatever it is, I think it should be changed.

**Steps to reproduce:**
1. Download http://www.homeofjones.de/temp/panda-fedora.zip and unzip
2. Make sure git is installed
3. Examine build.sh script and check the simple commands it does (basically git clone panda to a subfolder, then docker build of the Dockerfile, then docker run to build it)
4. Run build.sh and wait until it is in the panda3d build process (this might take a few minutes)
5. Close the terminal before the build completes (DO NOT CTRL+C, just use the close button and confirm any warnings that you might get about the terminal still running a process)
6. Type in ```docker ps```

Actual result: docker container is still running despite the terminal and .sh being terminated.

Expected result: docker container is turned off.

docker version:

```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

docker info:

```
Containers: 123
Images: 197
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 443
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-18-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 7.682 GiB
Name: cyberman
ID: JL55:4BBV:7VUZ:DBO2:NWVV:RE62:OQNK:IV75:THXS:SQL4:HLH3:FTIA
WARNING: No swap limit support
```

uname -a: ```
Linux cyberman 3.19.0-18-generic #18-Ubuntu SMP Tue May 19 18:31:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by vdemeester** [comment] 2015-07-05 08:20
Hi @JonasT,

This is intended and an expected behavior.  Docker is architectured in a Client/Server way, see [Understand the architecture](https://docs.docker.com/introduction/understanding-docker/). What this means is : when you do a ``docker run …`` the process launched will be run on the host part of Docker (which can be either on the same host or not). So with or without the -d option, in the point of view of the process, it's not attached to anything other than the docker daemon ; It's not attach to the *client* side, so it's not bound to you ssh connection, or your terminal, or ….

Now, when you run a Docker container using ``-ti`` you tell Docker you want to attach to it : with a *terminal* (``/dev/tty`` like) and with the standard input from your terminal forwarded to the container. That way, when you hit ``CTRL+C`` you can kill the process. But closing the terminal, or loosing the ssh connection, will not send any signal to the process — it will just finish the client part of the ``docker run`` command you issued, not the process launched inside your container. This also means, you can easily re-**attach** to the container (using ``docker attach …``).

```bash
# Run top in a container.
$ docker run -it ubuntu top
# It's running fine, now close the terminal.
# start another one and let's see if it's running
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
fe7a610a1cf4        ubuntu              "top"               7 seconds ago       Up 4 seconds                            naughty_kirch  
# It's still running, that's expected.
# Now we can re-attach to it
$ docker attach fe7a610a1cf4
# … Boom, you're in again :)
```

> Is this intended? Is this a bug? Whatever it is, I think it should be changed.

It's definitely not a bug, it's a feature (I like using this one but it's a true statement here). I'm pretty sure it's not a part that's gonna be changed :wink: (and you can re-attach to it so it's not really a big deal anyway).

**Comment by JonasT** [comment] 2015-07-05 11:15
This is a big deal for me, because we want to run a build in this and it isn't supposed to continue running if the shell script launching it is terminated by the build service.

Therefore, is there an option to change this behavior?

**Comment by phemmer** [comment] 2015-07-06 00:03
You say you are using a shell script to launch the container. If so, this is very easy to accomplish:

```
cid="$(docker run -tid foo)"
trap "docker kill $cid" EXIT
docker logs -f $cid
```
*(or `docker attach $cid` instead of `docker logs`)*

If the shell script exits for any reason, it runs `docker kill $cid`.

**Comment by JonasT** [comment] 2015-07-06 01:25
Even when the bash goes down with SIGKILL?

**Comment by phemmer** [comment] 2015-07-06 01:30
No. But if you're trying to protect against SIGKILL, your request is impossible. Even if  this feature were going to be added to docker, it would be a client side option (doesn't make sense server side).

I recommend opening separate issues if you wish to pursue this. A process being SIGKILLed is **very** different from closing a terminal window.

**Comment by JonasT** [comment] 2015-07-06 08:27
Since the docker daemon runs server-side and you kinda need some instance that checks if the terminal client is still alive, it seems to me that this would make more sense server-side (technically for the check, not where the option is specified of course - that should be for docker run). But I'm not a docker programmer or anything.

Also I don't see how it would be "impossible". Again, SSH does the same by simply doing something when the client goes away. Since the docker daemon needs to send me data over a socket to display the terminal output for -t -i, surely there is some way to tell if the client is no longer connected?

**Comment by phemmer** [comment] 2015-07-06 12:07
This would not work server side because of the way docker is designed. SSH is very different. With docker, when you create a container, you aren't attached to it. What happens if you never attach? How long should the daemon wait for an attach? What happens if multiple clients attach? When a client is lost, how long should the server wait before it considers the client dead (timeout)?

But again, this sounds like you're trying to handle SIGKILL, which is a different issue than handling a closed terminal window, and I would recommend opening a new issue for the subject.

**Comment by cpuguy83** [comment] 2015-09-15 01:13
Closing since this is expected behavior which we unfortunately cannot "protect" against.

**Closed by cpuguy83** 2015-09-15 01:13 UTC

**Comment by cserpell** [comment] 2016-05-16 15:14
I found very useful @phemmer trap's idea when running from bash. I am trying to accomplish the same behavior when running docker using a ssh connection, that would finish the process when ssh connection is closed. Using this idea, I would need to previously install a bash script in the host server, where I just wanted to run the docker container. I will see if I can accomplish something similar using just ssh, as I don't want to have additional files in the host server.

**Comment by hholst80** [comment] 2017-01-26 17:42
@JonssonT how did you solve this in the end?

**Comment by adirg** [comment] 2017-04-06 12:44
When using a shell script to run the container, we can give it a unique name and kill it when exiting the terminal using this name. 
For example - 
```
NAME=$(uuidgen)
trap "docker kill ${NAME}" 0
docker run -it --name ${NAME} foo
```
