### ISSUE TITLE
Error response from daemon: ApplyLayer exit status 1 stdout:  stderr: link / /var/log/boot.log: operation not permitted

### ISSUE THREAD

**Issue by gopal-gemini** [docker/docker#18255] opened 2015-11-26 06:44 UTC
I have tried to commit the centos desktop container from docker 1.7.1 installed host machine but received the following errors. Do you have any idea ?  I have used symlinks in that desktop container.

Error response from daemon: ApplyLayer exit status 1 stdout:  stderr: link / /var/log/boot.log: operation not permitted

**Comment by thaJeztah** [comment] 2015-11-27 00:01
could you provide more information on how to reproduce, because with the current information we don't have enough to debug. Also, please try if you're still able to reproduce this issue on the current (1.9.1) release.

I'll close this issue for now, but will reopen after you've provided more information. Thanks!

**Closed by thaJeztah** 2015-11-27 00:01 UTC
