### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by chovy** [docker/docker#27376] opened 2016-10-14 08:07 UTC
From your ubuntu docs for installing:

```
$ apt-get install linux-image-extra-$(uname -r)
E: Unable to locate package
               linux-image-extra-2.6.32-042stab117.14
```

I'm on ubuntu 16.04 LTS

**Comment by AkihiroSuda** [comment] 2016-10-14 08:26
The issue is very specific to your environment; you need to install the default kernel.

Why are you using a custom OpenVZ kernel for RHEL6 on Ubuntu?(http://cdimage.debian.org/mirror/openvz.org/kernel/branches/rhel6-2.6.32-testing/042stab117.14/)

**Comment by chovy** [comment] 2016-10-14 08:57
I don't know to be honest. Just bought a cheap VPS and re-installed Ubuntu 16.04 on it. They must have monkey patched the template. This certainly explains it. Is there anything I can do, like re-install an Ubuntu kernel?

**Comment by thaJeztah** [comment] 2016-10-14 23:00
I think this is something to discuss with your provider, or switch to a different provider (e.g. DigitalOcean is very cheap as well)


I'm closing this issue because this is not a bug, and we cannot support kernel 2.6 (which is ancient), but feel free to continue the discussion

**Closed by thaJeztah** 2016-10-14 23:00 UTC
