### ISSUE TITLE
pull from private registry returns 404 when not logged in.

### ISSUE THREAD

**Issue by bhanuvrat** [docker/docker#17721] opened 2015-11-05 13:10 UTC
pulling from a privately hosted registry instead should ask me to login if I am not.
instead it says the image is not present.
spent last 4 hours to discover this :(

**Comment by cpuguy83** [comment] 2015-11-05 14:13
This is common behavior, as it makes sure to not leak information about private things.
If it returned something like a `401 Unauthorized`, then this tells someone (ie, someone trying to skim information) that there is indeed an image there, where as `404` does not leak this information.

**Comment by bhanuvrat** [comment] 2015-11-05 18:54
as a corollary, if the user is not authenticated - irrespective of whether the file is there or not -> return a 401 ... 
so the server says authenticate yourself and then ask me if I have the file.

**Comment by thaJeztah** [comment] 2015-11-26 15:00
This sound like an issue that's better discussed in the https://github.com/docker/distribution repository, or in the #docker-distribution IRC channel.

Could you reopen this issue there, or discuss it on IRC?

I'm going to close the issue here, because this is not something that can be resolved in the docker client. Thanks for reporting though!

**Closed by thaJeztah** 2015-11-26 15:00 UTC

**Comment by sslavic** [comment] 2015-11-26 15:45
Still on docker-registry 1.0 - would need to migrate to Distribution (registry 2.0) first, to check if issue can be reproduced there too.

**Comment by thaJeztah** [comment] 2015-11-26 15:49
@sslavic I don't think registry 1.0 is still actively maintained, so if you want this changed, then registry 2.0 is the best choice. It will need to be discussed with the maintainers of that repository though, because this is by design (see the discussion above)

**Comment by sslavic** [comment] 2015-11-26 16:00
Strange design - not return 401 because that may signal image is there?! For me 401 means I do not have access to server, not to image. I authenticate myself to server, not to image.

After successful authentication, if I do not have privileges to access specific image/resource - then return 403.

Server/design should differentiate authentication and authorization.

**Comment by bmerry** [comment] 2016-10-09 11:31
I think this should possibly be reopened, unless it is a duplicate of #15759. The registry (v2.5) returns status 401 when querying /v2. The problem is that Docker Engine then tries again on /v1, gets a 404 error for that (since the private registry doesn't support v1), and reports that error.

**Comment by thaJeztah** [comment] 2016-10-10 11:18
@bmerry can you open a new issue, and exactly describe what you think needs to be fixed in the docker engine?
