### ISSUE TITLE
Unclear how to setup ports on Mac OS

### ISSUE THREAD

**Issue by geuis** [docker/docker#16749] opened 2015-10-04 04:40 UTC
I've been diving into Docker today and trying to get an existing app containerized.

I'm running into problems with getting port forwarding setup correctly. My dev machine is a Mac.

The app listens on 8080. In the dockerfile, I have "EXPOSE 8080" enabled. 

When I start the container, I use: 
    
    "docker run -d -p 8080:8080 appName".

However, I cannot access the server. I've verified the server is running via "docker top". 

When I "docker-machine ls" I see:

    default   *        virtualbox   Running   tcp://192.168.99.100:2376   

I've been reading various things for a few hours but every reference to ports refers to boot2docker, which according to the Docker site has been deprecated.

Not sure where to go next.

Thanks.

**Comment by thaJeztah** [comment] 2015-10-04 12:06
I think this section of the documentation describes what you're looking for; [Mac OS X - Access container ports](https://docs.docker.com/installation/mac/#access-container-ports)

Also, make sure that the service in your container is listening on 0.0.0.0, not 127.0.0.1

However, please be aware that the GitHub issue tracker is for reporting bugs and feature requests, and is not a support forum. It's better to ask this question; 

- in the #docker IRC channel on freenode
- in the docker-users Google Group
- in forums.docker.com

I'm going to close this issue, because this is not a bug or feature request, but I hope the hints above will help you further

**Closed by thaJeztah** 2015-10-04 12:06 UTC
