### ISSUE TITLE
service start error : could not open session

### ISSUE THREAD

**Issue by vmshah-github** [docker/docker#19026] opened 2016-01-01 18:27 UTC
I have built docker image with base centos and on top of the i installed cloudera 5.4.8 manually after starting docker container.
I am using mysql database for CDH cloudera.
Following are the steps
 
sudo yum -y install mysql-server
sudo service mysqld stop
sudo /sbin/chkconfig mysqld on
sudo service mysqld start
sudo mysqladmin -u root password password
sudo yum -y install mysql-connector-java
sudo yum -y install oracle-j2sdk1.7
sudo wget http://archive.cloudera.com/cm5/redhat/6/x86_64/cm/cloudera-manager.repo -P /etc/yum.repos.d
// Modify /etc/yum.repos.d/cloudera-manager.repo to install version 5.4.8
sudo yum clean all
sudo yum install cloudera-manager-agent cloudera-manager-server
sudo /usr/share/cmf/schema/scm_prepare_database.sh mysql cmf cmf cmf
 
I have configured following database in mysql
 
create database cmf;
create database metastore;
create database rman;
grant all on cmf. * to 'cmf'@'localhost' identified by 'cmf';
grant all on metastore. * to 'hive'@'localhost' identified by 'hive';
grant all on metastore. * to 'hive'@'%' identified by 'hive';
grant all on rman. * to 'rman'@'localhost' identified by 'rman';
flush privileges;
 
[root@cluster cloudera-scm-server]# /etc/init.d/cloudera-scm-server start
Starting cloudera-scm-server: [FAILED]
 
There is no log file at /var/log/cloudera-scm-server but only following file exist
/var/log/cloudera-scm-server/cloudera-scm-server.out
 
This file has only one line
[root@cluster cloudera-scm-server]# cat /var/log/cloudera-scm-server/cloudera-scm-server.out
could not open session
 
I do not file any other error.
Can someone help here where should i troubleshoot?
 

I am suspecting this is due to some docker issue as i found similar error while people using docker. But nothing worked for me.

Can someone help to troubleshoot the issue?
I installed cloudera manager 5.4.8 and agent with yum and using mysql as database
 
Following are the steps
 
sudo yum -y install mysql-server
sudo service mysqld stop
sudo /sbin/chkconfig mysqld on
sudo service mysqld start
sudo mysqladmin -u root password password
sudo yum -y install mysql-connector-java
sudo yum -y install oracle-j2sdk1.7
sudo wget http://archive.cloudera.com/cm5/redhat/6/x86_64/cm/cloudera-manager.repo -P /etc/yum.repos.d
// Modify /etc/yum.repos.d/cloudera-manager.repo to install version 5.4.8
sudo yum clean all
sudo yum install cloudera-manager-agent cloudera-manager-server
sudo /usr/share/cmf/schema/scm_prepare_database.sh mysql cmf cmf cmf
 
I have configured following database in mysql
 
create database cmf;
create database metastore;
create database rman;
grant all on cmf. * to 'cmf'@'localhost' identified by 'cmf';
grant all on metastore. * to 'hive'@'localhost' identified by 'hive';
grant all on metastore. * to 'hive'@'%' identified by 'hive';
grant all on rman. * to 'rman'@'localhost' identified by 'rman';
flush privileges;
 
[root@cluster cloudera-scm-server]# /etc/init.d/cloudera-scm-server start
Starting cloudera-scm-server: [FAILED]
 
There is no log file at /var/log/cloudera-scm-server but only following file exist
/var/log/cloudera-scm-server/cloudera-scm-server.out
 
This file has only one line
[root@cluster cloudera-scm-server]# cat /var/log/cloudera-scm-server/cloudera-scm-server.out
could not open session
 
I do not file any other error.
Can someone help here where should i troubleshoot?
 
OS : centos 6.7
BTW i am trying to install cloudera on base centos 6.7 image with docker.
Not sure if in case this error has to do anything due to docker

[root@mxtdbserver Desktop]$ docker --version
Docker version 1.7.1, build 786b29d

**Comment by thaJeztah** [comment] 2016-01-01 21:26
Sorry, @vmshah-github, this issue tracker is not a support forum, but meant for tracking bugs and feature requests in docker.

Please use;

- https://forums.docker.com
- StackOverflow
- the #docker IRC channel on freenode
- the docker-user Google Group; https://groups.google.com/forum/#!forum/docker-user

I'm going to close this issue, because this is not a bug or a feature request, but feel free to comment here after I've closed this issue

**Closed by thaJeztah** 2016-01-01 21:26 UTC
