### ISSUE TITLE
Issue on the new ulimit feature of the run command 1.6 RC4

### ISSUE THREAD

**Issue by botchagalupe** [docker/docker#12116] opened 2015-04-06 17:54 UTC
This is minor and probably won't be caught for some time but... 
See code command snippet

```
vagrant@ubuntu-1:~$ docker -v
Docker version 1.6.0-rc4, build e2e39fc
vagrant@ubuntu-1:~$ cid=$(docker run -itd --ulimit data=8192 ubuntu)
vagrant@ubuntu-1:~$ docker logs $cid
bash: xmalloc: .././locale.c:81: cannot allocate 2 bytes (0 bytes allocated)
```

**Comment by jfrazelle** [comment] 2015-04-06 18:02
ping @cpuguy83

**Comment by cpuguy83** [comment] 2015-04-06 18:03
I have a feeling this is due to the way the process in the container is started up.
If you up the ulimit value (ie, 819200) it works just fine.

We've also disbaled `as` from ulimit entirely because it causes a segv.

**Comment by cpuguy83** [comment] 2015-04-06 18:07
This probably just requires some additional documentation.

**Comment by jfrazelle** [comment] 2015-04-06 18:11
cool \o/ what i like to hear haha

**Comment by botchagalupe** [comment] 2015-04-06 19:39
Don't want to be a pest.. and like I said it's a minor issue.. however;  on the other ulimit (kbytes ) based values it looks like we default to zero or unlimited if the number calculates to low.  For example:
--ulimit memlock=8190.  

I agree that we should just update the doc for this release but eventually I think we should resolve the issue.  Some user is going to set it and not understand why the instance failed... my 2 cents...

**Comment by cpuguy83** [comment] 2015-04-06 20:02
Definitely not a pest :)

What's really happening is we are taking the user's value and doing the syscall to set that exact value, we aren't ever changing what the user has provided.

The issue is what is the actual minimum? It changes with each new commit since docker itself is execing these processes in the container, so there needs to be enough to be able to fire up a docker binary, basically.
Maybe there's some sort of runtime magic that we can do to say "hey, the value you entered isn't going to work"?

**Comment by jfrazelle** [comment] 2015-04-06 20:05
Ya or just explaining that.

**Comment by botchagalupe** [comment] 2015-04-06 20:17
Totally makes sense...   I'll try and update the doc in the next few days.

**Comment by thaJeztah** [comment] 2015-04-06 20:35
I labeled this with "writing", unless there are still plans to solve this in code, not sure if "proficient" applied here, but a proper understanding of the matter is required :smiley:

Marked this as "claimed" for you, @botchagalupe (thanks!)

**Comment by jfrazelle** [comment] 2015-04-14 19:57
can we get this in before thursday por favor

**Comment by PikachuEXE** [comment] 2015-04-20 05:59
Is this fixed? if not please update the milestone

**Comment by thaJeztah** [comment] 2015-05-20 11:25
Don't know if it's fixed yet. Moved the milestone for now

@botchagalupe are you / have you been working on this?

**Comment by calavera** [comment] 2015-05-28 19:07
do you mind to review #13558?

**Closed** 2015-05-28 22:51 UTC
Labels: exp/proficient, kind/writing, status/claimed
