### ISSUE TITLE
port number not updated in inspect

### ISSUE THREAD

**Issue by abilash222** [docker/docker#23233] opened 2016-06-03 12:21 UTC
after migrating to docker 1.10.3 upon docker service being restarted containers port forwarding details are not updated with new ports instead old port info is present in docker inspect output.
i am able to reproduce it.

Any idea why this issue? 

**Output of `docker version`:**
Client:
Version:      1.10.3
API version:  1.22
Go version:   go1.5.3
Git commit:   20f81dd
Built:        Thu Mar 10 15:39:25 2016
OS/Arch:      linux/amd64

Server:
Version:      1.10.3
API version:  1.22
Go version:   go1.5.3
Git commit:   20f81dd
Built:        Thu Mar 10 15:39:25 2016
OS/Arch:      linux/amd64
```
(paste your output here)
```

**Output of `docker info`:**
Containers: 177
Running: 5
Paused: 0
Stopped: 172
Images: 590
Server Version: 1.10.3
Storage Driver: devicemapper
Pool Name: docker-252:0-139-pool
Pool Blocksize: 65.54 kB
Base Device Size: 53.69 GB
Backing Filesystem: ext4
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 94.77 GB
Data Space Total: 1.611 TB
Data Space Available: 1.452 TB
Metadata Space Used: 129.4 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.018 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /home/sas/docker/devicemapper/devicemapper/data
WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
Metadata loop file: /home/sas/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
Volume: local
Network: bridge null host
Kernel Version: 3.10.0
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 251.6 GiB
Name: ceph-zclient1.zoholabs.com
ID: CAVN:4U7T:DVAF:YXKQ:NUUZ:2ABQ:7XYD:QBOM:5ABI:KMHQ:XMSX:BOTK
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-06-03 23:41
Can you try if you're still able to reproduce this on the current release (1.11.2)? We recently merged one fix in this area; https://github.com/docker/docker/pull/22997 and possibly others as well since 1.10.3

**Comment by thaJeztah** [comment] 2016-09-19 23:42
closing because there's no activity, but happy to reopen if you're still having this issue, and have more information

**Closed by thaJeztah** 2016-09-19 23:42 UTC
Labels: status/more-info-needed, version/1.10
