### ISSUE TITLE
"Port is already allocated" when connecting a container with a published port onto two user-defined networks

### ISSUE THREAD

**Issue by delfuego** [docker/docker#17970] opened 2015-11-13 17:10 UTC
I'm trying to understand and use the new Docker 1.9 networking features, and am running into an issue trying to connect a container that has an exposed/published port onto two different user-created networks — I run the container specifying the first network and all is OK, but then when I try to connect the container to the second network I receive the error `Error response from daemon: failed to create endpoint [container-name] on network [second-network-name]: Bind for 0.0.0.0:[exposed-port] failed: port is already allocated`.

To flesh out the example, using a tiny microbox image for testing's sake, I first create the two networks:

```
docker network create net1
docker network create net2
```

I then start my container, connected to the first network:

```
docker run --net net1 -d -p 6379:6379 --name redis microbox/redis:latest
```

I finally try to connect the container to the second network:

```
docker network connect net2 redis
```

and I receive the error:

```
Error response from daemon: failed to create endpoint redis on network net2: Bind for 0.0.0.0:6379 failed: port is already allocated
```

Do I misunderstand how the user-created networking works? Is this not a doable scenario, having a container with a listening daemon be able to participate on two different user-created networks?

Here's my setup:

```
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 2
Images: 343
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 347
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: FR-S-CCR-JEL1
ID: 3IEX:KIRE:V6SD:6HY4:MFOB:LUMT:HXTJ:XNDG:Q6JS:CFJF:UQQY:H3CA
WARNING: No swap limit support
```

```
$ uname -a
Linux FR-S-CCR-JEL1 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

This Docker server is running in a VSphere virtualized environment, nothing else special about it.

**Comment by mavenugo** [comment] 2015-11-13 17:25
@delfuego this is a dupe of #17824 and it is resolved via #17858.
The fix will be available in master and the upcoming 1.9.1 release.

**Closed by mavenugo** 2015-11-13 17:25 UTC
