### ISSUE TITLE
kernel panic when use wrong ‘docker run’ command

### ISSUE THREAD

**Issue by bjtulq** [docker/docker#16081] opened 2015-09-04 14:17 UTC
I just used the wrong command, however the result is the kernel panic. Below is my environment:
OS: Centos6.5， 2.6.32-431.el6.x86_64
docker-version：docker-io-1.7.1-2.el6.x86_64
command: docker run -P rhel6.5
vmcore-dmesg.txt:

<4>Pid: 1262, comm: docker Not tainted 2.6.32-431.el6.x86_64 #1 VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform
<4>RIP: 0010:[<ffffffff812943e0>]  [<ffffffff812943e0>] list_del+0x10/0xa0
<4>RSP: 0018:ffff88003cb6ddc8  EFLAGS: 00010092
<4>RAX: dead000000200200 RBX: ffff88003b3dded8 RCX: 0000000000000010
<4>RDX: 0000000000000000 RSI: 0000000000000003 RDI: ffff88003b3dded8
<4>RBP: ffff88003cb6ddd8 R08: 0000000000000010 R09: 0000000000000000
<4>R10: 0000000000000000 R11: 0000000000000246 R12: ffff88003b3ddec0
<4>R13: ffff88003cdd6d18 R14: 0000000000000010 R15: 0000000000000000
<4>FS:  00007fe351caa700(0000) GS:ffff88000b400000(0000) knlGS:0000000000000000
<4>CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
<4>CR2: 000000c2081b8000 CR3: 000000003d2eb000 CR4: 00000000001407f0
<4>DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
<4>DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
<4>Process docker (pid: 1262, threadinfo ffff88003cb6c000, task ffff88003d5a4080)
<4>Stack:
<4> 0000000000000011 ffff88003b3ddf00 ffff88003cb6de08 ffffffff810c9fe2
<4><d> 0000000100000004 ffff88003b7e66b8 0000000000000000 ffff88003b7e66d0
<4><d> ffff88003cb6de58 ffffffff81054839 ffff88003cb6df58 0000000300000001
<4>Call Trace:
<4> [<ffffffff810c9fe2>] cgroup_event_wake+0x42/0x70
<4> [<ffffffff81054839>] __wake_up_common+0x59/0x90
<4> [<ffffffff81058d48>] __wake_up+0x48/0x70
<4> [<ffffffff811d4d2d>] eventfd_release+0x2d/0x40
<4> [<ffffffff8118a725>] __fput+0xf5/0x210
<4> [<ffffffff8118a865>] fput+0x25/0x30
<4> [<ffffffff81185b8d>] filp_close+0x5d/0x90
<4> [<ffffffff81185c65>] sys_close+0xa5/0x100
<4> [<ffffffff8100b072>] system_call_fastpath+0x16/0x1b
<4>Code: 89 95 fc fe ff ff e9 ab fd ff ff 4c 8b ad e8 fe ff ff e9 db fd ff ff 90 90 90 90 55 48 89 e5 53 48 89 fb 48 83 ec 08 48 8b 47 08 <4c> 8b 00 4c 39 c7 75 39 48 8b 03 4c 8b 40 08 4c 39 c3 75 4c 48
<1>RIP  [<ffffffff812943e0>] list_del+0x10/0xa0
<4> RSP <ffff88003cb6ddc8>

**Comment by phemmer** [comment] 2015-09-04 16:43
You should file this on your distribution's bug tracker. Kernel panics are bugs within the kernel itself. While docker may have been the one to trigger the panic, the docker project can't do anything to fix the issue.

**Comment by thaJeztah** [comment] 2015-09-06 16:28
Especially with RHEL/CentOS 6 releases, make sure you've fully updated your system. There have been regressions in some versions of the 2.6.x kernel that resulted in kernel panics. These were not issues with Docker, but Docker *did* trigger them (as @phemmer mentioned).

Be aware that Docker dropped support for RHEL/CentOS 6 releases with Docker 1.8, so if you're able to, I'd *strongly* advise you to upgrade to a newer release (RHEL/CentOS 7)

I'm going to close this issue, because unfortunately, this is not something that Docker can solve, but I hope you are able to resolve this. Feel free to comment here after I've closed this issue

**Closed by thaJeztah** 2015-09-06 16:28 UTC
Labels: kernel
