### ISSUE TITLE
Swarm mode doesn't consider health:start status while updating from docker engine 1.12.3 version.

### ISSUE THREAD

**Issue by darkrasid** [docker/docker#27891] opened 2016-10-31 07:24 UTC
Hi. I have problem using healthcheck with swarm mode. 
This is may similar to #23962.

I make docker service from some_image:v1(this image has a healthcheck.) and scale out to 4.    
And I update it like this.
```
sudo docker service update --image some_image:v2 --update-delay 50s --update-parallelism 2 some-docker-service
```

And the result like this
```
452e1460f60b        some_image:v2                          "/sbin/entrypoint.sh "   9 seconds ago       Up Less than a second (health: starting)   8080/tcp                 some_docker_service.3.7w63khi2bj0r5f1id5u1s03dd
f2b36315d003        some_image:v2                          "/sbin/entrypoint.sh "   9 seconds ago       Up Less than a second (health: starting)   8080/tcp                 some_docker_service.4.22h0f3srvqlwsgui286yew71g
ea800b65a687        some_image:v1                          "/sbin/entrypoint.sh "   8 minutes ago       Up 8 minutes (healthy)                     8080/tcp                 some_docker_service.2.8no40j8fr2qiwzf1jdw1mymlw
5f506c6a5533        some_image:v1                          "/sbin/entrypoint.sh "   21 minutes ago      Up 20 minutes (healthy)                    8080/tcp                 some_docker_service.1.cbdfg3fvkva5m5e568hxylnap
```

As I understand from HEALTHCHECK when I try to access myip:8080, docker swarm should send my request to healthy container not to health:starting container.
And from #23962 issue, I think this feature already merged. 

However my swarm sends request all of containers.. so it has downtime when I try to rolling update. 
Am I missing something? Or shoud I use another docker version?

My docker version..
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:49:51 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:49:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by thaJeztah** [comment] 2016-11-01 02:20
Looks like this is a duplicate of https://github.com/docker/docker/issues/24092 and https://github.com/docker/docker/issues/26067, which are tracking this, so let me close this one.

Thanks for reporting @darkrasid !

**Closed by thaJeztah** 2016-11-01 02:20 UTC
Labels: area/swarm, kind/question, version/1.12
