### ISSUE TITLE
Dynamic Domain name or URL mapping to dynamically created containers

### ISSUE THREAD

**Issue by rajiff** [docker/docker#13793] opened 2015-06-07 14:23 UTC
Hi 

this is an enhancement request, sorry if this is a duplicate, but did search not found anything matching directly and useful (except few ngnix proxy suggestions, which i think is not dynamic) 

The host on which we spawn the containers has a domain name Eg: www.mydockerhost.com

Now each time, a new container is started, it has to be accessed as www.mydockerhost.com:$portnumber

Which is blocked if clients (users) are behind a proxy (especially corporate proxy) 

Hence can there be a service on Docker host, which can map or proxy URLs to its corresponding containers 

Eg: Let the client access www.mydockerhost.com/my_$portnumber which is mapped internally to the port  of the corresponding container

Key thing here is it has to be dynamic, i.e., if the container is stopped, the mapping too has to be automatically removed and visa-verse 

Pleas point me to right solution or tell us if something can be done to address this in the next release

**Comment by thaJeztah** [comment] 2015-06-07 14:34
As you mentioned, this is best addressed by a proxy. Various solutions exist and many of those actually *are* dynamic (but may need some extra params or environment variables added to the `docker run ...` statement when starting the container).

I personally like https://github.com/jwilder/nginx-proxy/, which is really easy to use, doesn't require much setup and dynamically adds/removes containers from the proxy configuration (by making use of start / stop events emitted by docker containers).

I'm going to close this issue, because this is not a bug in docker and implementing this is not something that belongs in the Docker core functionality. Also, there are too many different use-cases for a generic solution.

**Closed by thaJeztah** 2015-06-07 14:34 UTC
