### ISSUE TITLE
docker-engine-1.12.1-1.el7.centos.x86_64 wont start

### ISSUE THREAD

**Issue by marafa** [docker/docker#28816] opened 2016-11-24 22:32 UTC
**Description**
docker-engine-1.12.1-1.el7.centos.x86_64 fails to restart 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
[root@zenoss1 ~]# sestatus
SELinux status:                 disabled
[root@zenoss1 ~]# rpm -qa |grep -i docker
docker-engine-1.12.1-1.el7.centos.x86_64
docker-engine-selinux-1.12.3-1.el7.centos.noarch
[root@zenoss1 ~]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
 
Nov 24 23:38:55 zenoss1 docker: time="2016-11-24T23:38:55.561387242+02:00" level=fatal msg="no sockets found via socket activation: make sure the service was started by systemd"
Nov 24 23:38:55 zenoss1 systemd: docker.service: main process exited, code=exited, status=1/FAILURE
Nov 24 23:38:55 zenoss1 systemd: Unit docker.service entered failed state.
Nov 24 23:38:55 zenoss1 systemd: docker.service failed.
 
[root@zenoss1 docker]# cat /etc/sysconfig/docker
DOCKER_OPTS="-s btrfs --dns=172.17.0.1"
 
 
Nov 24 23:38:55 zenoss1.cloud.egit systemd[1]: Starting Docker Application Container Engine...
Nov 24 23:38:55 zenoss1.cloud.egit docker[2633]: time="2016-11-24T23:38:55.561387242+02:00" level=fatal msg="no sockets found via socket activation: make sure the service was started by systemd"
Nov 24 23:38:55 zenoss1.cloud.egit systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Nov 24 23:38:55 zenoss1.cloud.egit systemd[1]: Failed to start Docker Application Container Engine.
Nov 24 23:38:55 zenoss1.cloud.egit systemd[1]: Unit docker.service entered failed state.
Nov 24 23:38:55 zenoss1.cloud.egit systemd[1]: docker.service failed.
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2016-11-24 23:07
This is because 1.12 and above no longer use socket activation. This error is caused if you have either modified the default systemd unit file, or have a custom drop-in file that expects socket activation.

See the warning at the top of the release notes; https://github.com/docker/docker/releases/tag/v1.12.3

Also, its recommended to install 1.12.3 instead of 1.12.1, as it contains a lot of bug fixes.

I'll close this issue, because this is not a bug, but feel free to comment if you have questions

**Closed by thaJeztah** 2016-11-24 23:07 UTC
