### ISSUE TITLE
[1.10] Can't start container

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [docker/docker#20139] opened 2016-02-09 10:32 UTC
Physical server, Ubuntu 15.10

```
docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64

```

```
docker info
Containers: 24
 Running: 12
 Paused: 0
 Stopped: 12
Images: 1104
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1247
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-25-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.89 GiB
Name: services
ID: DVN6:Y4RS:IXJB:DSRP:OYAR:2ZB4:GJ75:5Y6O:NNXP:HID5:BDNF:Y4KT
WARNING: No swap limit support
```

I'm trying to run the new container
```
docker run --rm nginx
docker: Error response from daemon: internal failure while setting the bit: Key not found in store.
```

I've used the docker/dind image with linked /var/lib/docker volume before it.

**Comment by thaJeztah** [comment] 2016-02-09 16:11
ping @aboch looks like this error originates from libnetwork? https://github.com/docker/libnetwork/blob/15c9f4c6347a82db45d415585984a91fe476b96b/bitseq/sequence.go#L351-L358

**Comment by thaJeztah** [comment] 2016-02-09 16:13
@Ilya-Kuchaev how are you running the dind container, are you bind-mounting the `/var/lib/docker` directory in the dind container? (i.e. `docker run -v /var/lib/docker/:/var/lib/docker/ .....`)? Because if you do, effectively there's two docker daemons using the same graph-dir, which is asking for trouble

**Comment by aboch** [comment] 2016-02-09 16:39
Thanks @thaJeztah. Agree, looks like something weird is happening on the datastore.

**Comment by Ilya-Kuchaev** [comment] 2016-02-09 19:29
@thaJeztah Yes. I was trying to run the build server for docker images in a docker. It was a mistake as I can see. So how could I resolve it? Can `service docker restart` help me?

**Comment by thaJeztah** [comment] 2016-02-09 20:27
It's possible the `/var/lib/docker/network/files/local-kv.db` is corrupt; you can try to remove/rename it and restart docker.

Note that it's possible to run docker-in-docker, however, you should **never** have two daemons that use the same graph-dir (/var/lib/docker in this case).

For example, you can run `docker run -v dind-data:/var/lib/docker --privileged ...` to have the `/var/lib/docker` directory stored in a volume.

I'm going to close this issue, because I suspect this is caused by having two daemons trying to use the same graph-dir, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-02-09 20:27 UTC
Labels: group/networking, status/more-info-needed

**Comment by Ilya-Kuchaev** [comment] 2016-02-09 20:37
Thanks, @thaJeztah !
