### ISSUE TITLE
Service Create -- Environment variable is not setting 

### ISSUE THREAD

**Issue by getvivekv** [docker/docker#29811] opened 2017-01-01 22:55 UTC
I've been facing a problem with the `--env` argument in the `docker service create` command. I am setting an environment variable while creating the service. However these are not getting set in the container. 

Steps replicate issue.

1. Create a service 

> 
> docker service create --name vvasukut-soss --network soss --network proxy \
> --mount ype=bind,source=/mnt/efs/dev/vvasukut/authorized_keys,target=/root/.ssh/authorized_keys,readonly=false \
>  --env DEV_USERNAME=vvasukut \
>  --mount type=volume,source=vvasukut-soss-586984ca06d6e,target=/soss,readonly=false \
>  --publish 22001:22 --with-registry-auth --limit-memory 1G --label com.df.notify=true --label com.df.distribute=true  \
>  --label com.df.servicePath=/ --label com.df.serviceDomain=mydomain.com --label com.df.port=80  --label virtualhost=mydomain.com \
> --label volumeName=vvasukut-soss-586984ca06d6e --label sshport=22001 imagePath

2. Once the service is up and runing, login to the container.

`ssh root@containerip`

3. Type `printenv`

I am getting 

```
[root@75479997ff22 ~]# printenv
HOSTNAME=75479997ff22
TERM=xterm
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=10.255.0.4 65377 22
SSH_TTY=/dev/pts/1
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
MAIL=/var/spool/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
PWD=/root
LANG=en_US.UTF-8
HISTCONTROL=ignoredups
SHLVL=1
HOME=/root
LOGNAME=root
SSH_CONNECTION=10.255.0.4 65377 10.255.0.23 22
LESSOPEN=||/usr/bin/lesspipe.sh %s
_=/usr/bin/printenv
[root@75479997ff22 ~]# 

```

I was expecting `DEV_USERNAME` in addition to those above environment variables.

I also inspected the service using 

`# docker inspect 6m57y9yzt5u8xqlsxksq3lqia`

And I was able to see the `Env` variable there.
```

{
        "ID": "6m57y9yzt5u8xqlsxksq3lqia",
        "Version": {
            "Index": 10532
        },
        "CreatedAt": "2017-01-01T22:41:04.334813701Z",
        "UpdatedAt": "2017-01-01T22:41:11.281313273Z",
        "Spec": {
            "ContainerSpec": {
                "Image": "<image>",
                "Env": [
                    "DEV_USERNAME=vvasukut"
                ],

```

Why wouldn't docker set the variable inside the container? 

```
root@dev-swarm-1 ~]# docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64
[root@dev-swarm-1 ~]# 
```

```

[root@dev-swarm-1 ~]# docker info
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-253:3-8388663-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.155 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104.2 GB
 Metadata Space Used: 7.344 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /mnt/volume/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /mnt/volume/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: active
 NodeID: 6a5osqr5i2ymyjljlzkcy0zkc
 Is Manager: true
 ClusterID: 7eht9vr8hv79kqvr3ubtggmbc
 Managers: 4
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: xx.xx.xxx.xx
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: nodename
ID: CJG4:6FHN:ASMV:A5L2:QGZH:A6SY:7JED:ZZSF:XK35:HWTM:5QY2:K4OP
Docker Root Dir: /mnt/volume/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

```

**Comment by getvivekv** [comment] 2017-01-01 23:03
Another thing that I just noticed that if I remove all other arguments, I can see that the environment variable is getting set.

`docker service create --name vvasukut-soss1 --env DEV_USERNAME=vvasukut image`


```

[root@dev-swarm-2 ~]# docker exec -it 4e6e1d5954ac bash
[root@4e6e1d5954ac /]# printenv
HOSTNAME=4e6e1d5954ac
TERM=xterm
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
LANG=en_US.UTF-8
SHLVL=1
HOME=/root
DEV_USERNAME=vvasukut
LESSOPEN=||/usr/bin/lesspipe.sh %s
container=docker
_=/usr/bin/printenv
[root@4e6e1d5954ac /]# 


```

**Comment by getvivekv** [comment] 2017-01-01 23:12
Could it be because I am logging into ssh as 'root' instead of `docker exec` ?

**Comment by jmzwcn** [comment] 2017-01-02 02:32
I think so, "ssh root@containerip" will be a new shell.

**Comment by thaJeztah** [comment] 2017-01-02 10:28
Yes, this is not a bug in Docker, but the way SSH sessions work, also see http://stackoverflow.com/questions/216202/why-does-an-ssh-remote-command-get-fewer-environment-variables-then-when-run-man, and http://www.linux-pam.org/Linux-PAM-html/sag-pam_env.html

As you found out yourself, the environment variables are present when `docker exec` is used.

I'll close this issue, because this is not a bug, but feel free to continue the discussion

**Closed by thaJeztah** 2017-01-02 10:28 UTC
Labels: area/swarm, version/1.12
