### ISSUE TITLE
Howto build docker-engine (1.12.0-dev) from sources behind a http_proxy?

### ISSUE THREAD

**Issue by ifrh** [docker/docker#25116] opened 2016-07-27 08:32 UTC
Hi there, 
because of my posted problem #25052 
I wanted to compile docker-engine from source,
to check if merged code changes, mentioned here https://github.com/docker/docker/issues/23411#issuecomment-233337962 , bringing help for me.

I found an extern document [How-to build Docker from source - http://oyvindsk.com/writing/docker-build-from-source](http://oyvindsk.com/writing/docker-build-from-source) but it is not clear enough too me.

Okay and I read this document: [Work with a development container - https://docs.docker.com/opensource/project/set-up-dev-env/](https://docs.docker.com/opensource/project/set-up-dev-env/)

Cloning the repository works after setting `https_proxy` environment variable.

```
git clone https://github.com/docker/docker.git
Nach »docker« wird geklont
remote: Counting objects: 169016, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 169016 (delta 2), reused 0 (delta 0), pack-reused 169008
Objekte werden empfangen: 100% (169016/169016), 94.39 MiB | 1.84 MiB/s, done.
Unterschiede werden aufgelöst: 100% (111989/111989), done.
Verbundenheit wird überprüft … Fertig.
```

But following the documentaion  [Work with a development container - https://docs.docker.com/opensource/project/set-up-dev-env/](https://docs.docker.com/opensource/project/set-up-dev-env/)
faild in stepp **make shell** also calling **./hack/make.sh** directly failed. 

Is there a way to build docker from sources behind a http_proxy, https_proxy? 

**_Ouptput of `make shell`:**_

```
mkdir -p .go-pkg-cache/gopath .go-pkg-cache/vendor .go-pkg-cache/goroot-linux_amd64_netgo
docker build  -t "docker-dev:master" -f "Dockerfile" .
Sending build context to Docker daemon 144.2 MB
Step 1 : FROM debian:jessie
 ---> 1b088884749b
Step 2 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61  || apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
 ---> Running in 8a157222859c
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.gRNu7XCvEy --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server p80.pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.jOOMjH8VjE --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server pgp.mit.edu
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
The command '/bin/sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61       || apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61' returned a non-zero code: 2
make: *** [build] Fehler 1

```

**_Ouptput of `./hack/make.sh`**_

```
# WARNING! I don't seem to be running in a Docker container.
# The result of this command might be an incorrect build, and will not be
# officially supported.
#
# Try this instead: make all
#

---> Making bundle: validate-dco (in bundles/1.12.0-dev/validate-dco)
0 adds, 0 deletions; nothing to validate! :)

---> Making bundle: validate-default-seccomp (in bundles/1.12.0-dev/validate-default-seccomp)

---> Making bundle: validate-gofmt (in bundles/1.12.0-dev/validate-gofmt)
Congratulations!  All Go source files are properly formatted.

---> Making bundle: validate-lint (in bundles/1.12.0-dev/validate-lint)
Congratulations!  All Go source files have been linted.

---> Making bundle: validate-pkg (in bundles/1.12.0-dev/validate-pkg)
Congratulations! "./pkg/..." is safely isolated from internal code.

---> Making bundle: validate-test (in bundles/1.12.0-dev/validate-test)
Congratulations! No testing.T found.

---> Making bundle: validate-toml (in bundles/1.12.0-dev/validate-toml)
Congratulations!  All toml source files changed here have valid syntax.

---> Making bundle: validate-vet (in bundles/1.12.0-dev/validate-vet)
Congratulations!  All Go source files have been vetted.

---> Making bundle: binary-client (in bundles/1.12.0-dev/binary-client)
Building: bundles/1.12.0-dev/binary-client/docker-1.12.0-dev
go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
# github.com/docker/distribution/registry/api/errcode
vendor/src/github.com/docker/distribution/registry/api/errcode/register.go:74:24: error: reference to undefined identifier ‘http.StatusTooManyRequests’
   HTTPStatusCode: http.StatusTooManyRequests,

```

**Comment by thaJeztah** [comment] 2016-07-27 10:06
We recently merged some changes in the Makefile to make working with proxies easier (see https://github.com/docker/docker/pull/24280), but perhaps something like this is still needed; https://github.com/docker/docker/pull/23874/files

I don't work behind a proxy, so not sure if additional changes are needed

**Comment by ifrh** [comment] 2016-07-27 11:07
Hi, thanks ... after editing  `./Dockerfile` with 

```
ENV https_proxy=http://cache-server:8080/
ENV http_proxy=http://cache-server:8080/
ENV ftp_proxy=http://cache-server:8080/

ENV HTTPS_PROXY=http://cache-server:8080/
ENV HTTP_PROXY=http://cache-server:8080/
ENV FTP_PROXY=http://cache-server:8080/
```
where `cache-server` is the FQDN the development docker could be created.


But sadly my local Linux VM (running inside a Windows Virtualbox) ran out of memory,
so I am not able to create the docker executables inside the Linux VM. :-(

```
Successfully built a49561700b86
docker run --rm -i --privileged -e BUILDFLAGS -e KEEPBUNDLE -e DOCKER_BUILD_GOGC -e DOCKER_BUILD_PKGS -e DOCKER_DEBUG -e DOCKER_EXPERIMENTAL -e DOCKER_GITCOMMIT -e DOCKER_GRAPHDRIVER=aufs -e DOCKER_INCREMENTAL_BINARY -e DOCKER_PORT -e DOCKER_REMAP_ROOT -e DOCKER_STORAGE_OPTS -e DOCKER_USERLANDPROXY -e TESTDIRS -e TESTFLAGS -e TIMEOUT -e HTTP_PROXY -e HTTPS_PROXY -e NO_PROXY -e http_proxy -e https_proxy -e no_proxy -v "/home/praktomat/docker/bundles:/go/src/github.com/docker/docker/bundles"  -t "docker-dev:master" bash
root@23137ae226b7:/go/src/github.com/docker/docker# hack/make.sh binary

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# GITCOMMIT = 5d65ba4-unsupported
# The version you are building is listed as unsupported because
# there are some files in the git repository that are in an uncommited state.
# Commit these changes, or add to .gitignore to remove the -unsupported from the version.
# Here is the current list:
 M Dockerfile
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---> Making bundle: binary (in bundles/1.12.0-dev/binary)
Building: bundles/1.12.0-dev/binary-client/docker-1.12.0-dev
Created binary: bundles/1.12.0-dev/binary-client/docker-1.12.0-dev
Building: bundles/1.12.0-dev/binary-daemon/dockerd-1.12.0-dev
# github.com/docker/docker/cmd/dockerd
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory

root@23137ae226b7:/go/src/github.com/docker/docker# 

```

**Comment by thaJeztah** [comment] 2016-07-27 11:21
I think 2 Gigabyte is a minimum for building docker

**Comment by dineshputchala** [comment] 2016-11-25 09:22
I am behind  proxy and I see below errors while "make shell"

bash-4.1$ make shell
mkdir -p .go-pkg-cache/gopath .go-pkg-cache/vendor .go-pkg-cache/goroot-linux_amd64_netgo
docker build   -t "docker-dev" -f "Dockerfile" .
Sending build context to Docker daemon 42.76 MB
Step 1 : FROM debian:jessie
 ---> 73e72bf822ca
Step 2 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61        || apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
 ---> Running in 7c0769baa2ab
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.lcnaSHiwdx --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server p80.pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.rJU0FXsW3p --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server pgp.mit.edu
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
The command '/bin/sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61     || apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61' returned a non-zero code: 2
make: *** [build] Error 2

How to resolve them ?

**Comment by thaJeztah** [comment] 2016-11-25 12:14
I'll close this issue because this is a support question for building docker, and not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-11-25 12:14 UTC
Labels: area/project, kind/question
