### ISSUE TITLE
Docker Publish port mapping is reversed

### ISSUE THREAD

**Issue by yskrishnan** [docker/docker#9778] opened 2014-12-22 17:53 UTC
When I do docker run with '-p hostPort:containerPort' option, I guess internally the hostPort is wrongly taken as the containerPort and spits out an error message like below.

2014/12/22 17:49:56 Error response from daemon: Cannot start container e2ea7941d306a9570f31cb7a76d44fa9dd84cf77f8389b7b855330e063313f6f: Error starting userland proxy: listen tcp 0.0.0.0:2375: bind: address already in use

I tried mapping -p 2375:8181. My host port 2375 to be mapped with Application's 8181 in the container. But this does not work. Only when I specify the other way -p 8181:2375, I am able to start the container. But now, the App port 8181 is not accessible outside with this mapping as it is wrongly taken inside.

**Comment by dnephin** [comment] 2015-02-02 21:07
I think the issue is more likely #9047

**Comment by jfrazelle** [comment] 2015-02-26 23:27
closing as dup of https://github.com/docker/docker/issues/9047

**Closed by jfrazelle** 2015-02-26 23:27 UTC
