### ISSUE TITLE
start, restart, stop docker timeout on centos 7

### ISSUE THREAD

**Issue by vuhiep1694** [docker/docker#26315] opened 2016-09-05 10:54 UTC
**Output of `docker version`:**

```
Docker version 1.12.1, build 23cf638 (can not print version when docker running)
```

**Output of `docker info`:**

```
can not get docker info (waiting state)
```

**Steps to reproduce the issue:**
1.I running docker on centos 7: Linux WT_ZSL_Apps-46.17 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
2.using command: curl -fsSL https://get.docker.com/ | sh to install docker

**Describe the results you received:**
But when I run command: systemctl start docker , nothing return and system waiting forever
using command 'ps aux | grep docker' and result:
```
root      5037  0.0  0.0 1060572 23992 ?       Ssl  17:44   0:00 /usr/bin/dockerd
root      5079  0.0  0.0 349280  8640 ?        Ssl  17:44   0:00 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc
root     18209  0.0  0.0 112652   976 pts/2    S+   17:49   0:00 grep --color=auto docker
root     43672  0.0  0.0  62084  9652 pts/0    Sl+  17:45   0:00 docker version
```
and command start still not finish.

This is my log when restart docker:
```
Sep 05 17:32:33 WT_ZSL_Apps-46.17 systemd[1]: docker.service stop-sigterm timed out. Killing.
Sep 05 17:32:33 WT_ZSL_Apps-46.17 systemd[1]: docker.service: main process exited, code=killed, status=9/KILL
Sep 05 17:32:33 WT_ZSL_Apps-46.17 systemd[1]: Unit docker.service entered failed state.
Sep 05 17:32:33 WT_ZSL_Apps-46.17 systemd[1]: docker.service failed.
Sep 05 17:32:33 WT_ZSL_Apps-46.17 systemd[1]: Starting Docker Application Container Engine...
Sep 05 17:32:33 WT_ZSL_Apps-46.17 dockerd[10853]: time="2016-09-05T17:32:33.230050573+07:00" level=info msg="libcontainerd: new containerd process, pid: 10924"
Sep 05 17:32:34 WT_ZSL_Apps-46.17 dockerd[10853]: time="2016-09-05T17:32:34.240714430+07:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use 
Sep 05 17:32:34 WT_ZSL_Apps-46.17 dockerd[10853]: time="2016-09-05T17:32:34.287245176+07:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. User specified filesyste
Sep 05 17:32:34 WT_ZSL_Apps-46.17 dockerd[10853]: time="2016-09-05T17:32:34.318769885+07:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
Sep 05 17:32:34 WT_ZSL_Apps-46.17 dockerd[10853]: time="2016-09-05T17:32:34.320235240+07:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Sep 05 17:32:34 WT_ZSL_Apps-46.17 dockerd[10853]: time="2016-09-05T17:32:34.320581750+07:00" level=warning msg="mountpoint for pids not found"
Sep 05 17:32:34 WT_ZSL_Apps-46.17 dockerd[10853]: time="2016-09-05T17:32:34.320874251+07:00" level=info msg="Loading containers: start."
Sep 05 17:32:34 WT_ZSL_Apps-46.17 dockerd[10853]: time="2016-09-05T17:32:34.331258790+07:00" level=info msg="Firewalld running: false"
```

**Comment by LK4D4** [comment] 2016-09-13 17:21
Looks like it even not starting to listen on socket, hangs seems to be on systemd socket.
@vuhiep1694 Can you pls send SIGUSR1 to daemon and post logs here?

**Comment by LK4D4** [comment] 2016-09-13 18:53
Btw it looks like duplicate of #16249

**Comment by thaJeztah** [comment] 2016-09-23 12:51
looks like a duplicate yes. closing

**Closed by thaJeztah** 2016-09-23 12:51 UTC
Labels: area/daemon, version/1.12
