### ISSUE TITLE
Kernel Panic when build image

### ISSUE THREAD

**Issue by yongkangchen** [docker/docker#14033] opened 2015-06-19 04:12 UTC
#### Key information from my environment:
```
[server@ltserver ~]$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0
```
```
[server@ltserver ~]$ docker info
Containers: 0
Images: 4
Storage Driver: devicemapper
 Pool Name: docker-253:1-1966532-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 562.8 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 1.02 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.23.4.el6.x86_64
Operating System: <unknown>
CPUs: 4
Total Memory: 7.375 GiB
Name: ltserver
ID: WE6J:VLWN:Q7C7:EJWX:EVCW:IRGY:Z3NK:ARJP:3ED5:DWPA:TTSH:KWE2
```
```
[server@ltserver ~]$ uname -a
Linux ltserver 2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

#### Step to reproduce:
1、
```
[server@server test]$ cat Dockerfile
FROM centos:6.6
MAINTAINER yongkangchen lx1988cyk@gmail.com

RUN useradd game
RUN (su - game && echo "test" > test.txt)

RUN echo "test2" > test2.txt
```
2、
```
[server@server test]$ docker build -t test .
```

#### Result: Kernel Panic
![kernel](https://cloud.githubusercontent.com/assets/704762/8246987/db6f05b0-167a-11e5-9099-323c408307d8.jpg)

#### Other information after reboot:
```
[server@server test]$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              d8623cb63811        11 minutes ago      202.6 MB
centos              6.6                 8b44529354f3        8 weeks ago         202.6 MB
centos              centos6.6           8b44529354f3        8 weeks ago         202.6 MB
[server@server test]$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                         PORTS               NAMES
8b3b78953dd0        d8623cb63811        "/bin/sh -c 'useradd   11 minutes ago      Exited (-127) 8 minutes ago                        sad_swartz          
3a63b3688792        centos:6.6          "bash"                 18 hours ago        Exited (0) About an hour ago                       sleepy_hoover
```

And I am use CentOS release 6.6 (Final)  (upgrade from centos 6.4)

**Comment by phemmer** [comment] 2015-06-19 11:00
If you haven't, this issue should also be posted to the CentOS bug tracker. A kernel panic indicates an issue with the kernel, not really docker. While the docker project might be able to put in a workaround to avoid triggering the issue, the kernel itself is the thing that needs to be fixed.

**Comment by visualphoenix** [comment] 2015-06-25 14:07
@yongkangchen can you try 1.6.2 and see if the issue still happens?

```
sudo yum install -y http://mirror.centos.org/centos/6.6/os/x86_64/Packages/device-mapper-libs-1.02.90-2.el6.x86_64.rpm http://mirror.centos.org/centos/6.6/os/x86_64/Packages/device-mapper-1.02.90-2.el6.x86_64.rpm http://mirror.centos.org/centos/6.6/os/x86_64/Packages/device-mapper-event-1.02.90-2.el6.x86_64.rpm http://mirror.centos.org/centos/6.6/os/x86_64/Packages/device-mapper-event-libs-1.02.90-2.el6.x86_64.rpm https://dl.fedoraproject.org/pub/epel/testing/6/x86_64/docker-io-1.6.2-1.el6.x86_64.rpm
```

I'm wondering if this is related to #14181 and the resurfaced panic seen in #9856

**Comment by devnied** [comment] 2015-07-16 14:47
To fix it temporally, you can downgrade you rhel 6 kernel version to the version 2.6.32-504.16.2
```
$ yum install kernel-2.6.32-504.16.2.el6.x86_64
```

**Comment by felixb** [comment] 2015-07-17 08:18
@visualphoenix I'm running docker 1.6.2 having the same problems.

**Comment by tuesdaythefifth** [comment] 2015-07-24 16:42
does this still occur with 6.7?

https://access.redhat.com/articles/3078#RHEL6
RHEL 6 Update 7	2015-07-22	2015-07-22 RHEA-2015:1423	2.6.32-573

**Comment by hawkish** [comment] 2015-07-26 17:20
I'm also running docker 1.6.2 and 2.6.32-504.30.3.el6. I can confirm that downgrading the kernel to 16 works.

**Comment by felixb** [comment] 2015-08-12 06:08
We upgraded to `2.6.32-573.1.1.el6` and everything works fine again.

**Comment by hawkish** [comment] 2015-08-19 08:42
I can confirm that newer kernels seems to work again after upgrading.

**Comment by thaJeztah** [comment] 2015-08-19 18:30
Thanks! I'm going to close this issue, because upgrading the kernel to  `2.6.32-573.1.1.el6` should resolve this, but free to comment here if this is not resolved after upgrading the kernel :-)

**Closed by thaJeztah** 2015-08-19 18:30 UTC
Labels: kernel

**Comment by yongkangchen** [comment] 2015-08-28 05:03
Sorry for long time to reply, I upgraded to kernel-lt (3.10.87-1.el6.elrepo.x86_64) and works fine. Thanks

**Comment by thaJeztah** [comment] 2015-08-28 06:59
Thanks for reporting back @yongkangchen, and good to hear it's resolved for you!
