### ISSUE TITLE
Supporting a symlinked build context.

### ISSUE THREAD

**Issue by therealprologic** [docker/docker#7804] opened 2014-08-30 03:47 UTC
Hi,

This was discussed here: https://github.com/docker/fig/issues/381#issuecomment-53644349

Basically in our HMO(s) the following should be supported by ``docker build``:

```#!bash
ln -s ~/path/to/project .
docker build project
```

Where ``/path/to/project`` contains a valid ``Dockerfile`` and "source files".

That is to say that the ``docker`` client could and probably should perform a ``readlink`` on the target build directory/context before "packaging it up" and "sending it to the daemon" for "building".

To be clear -- No one is suggested that "Docker" support symlinks inside the build context in any way shape or form, but the above suggestion would allow (*for example*) developers to transition to "Docker" based development by symlinking their old source directories to a repository that contains a ``fig.yml`` spec file for building/development/testing.

To illustrate the point in this issue more clearly:

```#!bash
$ mkdir foo
$ cat - > foo/Dockerfile <<EOF
> FROM busybox
> CMD ["echo", "Hello World"]
> EOF
$ docker build foo
Sending build context to Docker daemon  2.56 kB
Sending build context to Docker daemon
Step 0 : FROM busybox
 ---> a9eb17255234
Step 1 : CMD ["echo", "Hello World"]
 ---> Running in e451dcf5f1eb
 ---> 1b7418490382
Removing intermediate container e451dcf5f1eb
Successfully built 1b7418490382
$ docker run --rm 1b7418490382
Hello World
$ ln -s foo bar
$ docker build bar
Sending build context to Docker daemon 1.536 kB
Sending build context to Docker daemon
2014/08/30 21:42:50 Error: Can't build a directory with no Dockerfile
```

**Comment by jfrazelle** [comment] 2015-02-25 22:21
we made some improvements to symlinks but I do not know if you can symlink the whole dir :/ @therealprologic I take this isn't fixed yet

**Comment by jfrazelle** [comment] 2015-02-26 19:14
closing as dup of https://github.com/docker/docker/issues/6094

**Closed by jfrazelle** 2015-02-26 19:14 UTC
Labels: feature

**Comment by dpisarewski** [comment] 2015-03-03 15:18
This issue is still not fixed.

**Comment by thaJeztah** [comment] 2015-03-03 16:07
@dpisarewski this issue is not closed as "resolved", but as a duplicate of https://github.com/docker/docker/issues/6094. You can check that issue for progress.
