### ISSUE TITLE
Able to remove the default bridge network

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#17255] opened 2015-10-22 00:44 UTC
* I was able to remove the default bridge network, now i can't run continers
* Trying to remove `null` says it can't be found but it clearly is found by `docker network ls`

```
buntu@ip-172-31-36-118:~$ docker network ls
NETWORK ID          NAME                DRIVER
a792d9893ebd        none                null                
37c1b62f7b40        host                host                
97ee5a4064f7        bridge              bridge              
ubuntu@ip-172-31-36-118:~$ docker network rm bridge
ubuntu@ip-172-31-36-118:~$ docker network ls
NETWORK ID          NAME                DRIVER
a792d9893ebd        none                null                
37c1b62f7b40        host                host                
ubuntu@ip-172-31-36-118:~$ docker network rm host
Error response from daemon: network of type "host" cannot be deleted
ubuntu@ip-172-31-36-118:~$ docker network rm null
Error response from daemon: network null not found
ubuntu@ip-172-31-36-118:~$ docker network ls
NETWORK ID          NAME                DRIVER
a792d9893ebd        none                null                
37c1b62f7b40        host                host                
ubuntu@ip-172-31-36-118:~$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
b901d36b6f2f: Pull complete 
0a6ba66e537a: Pull complete 
Digest: sha256:517f03be3f8169d84711c9ffb2b3235a4d27c1eb4ad147f6248c8040adb93113
Status: Downloaded newer image for hello-world:latest
Error response from daemon: Cannot start container da483ad019745e76834d1b2bd4be6b742367b5b53d985f306d5c596fa08a180b: network bridge not found
ubuntu@ip-172-31-36-118:~$ 

```

**Comment by mavenugo** [comment] 2015-10-22 00:51
@moxiegirl we shouldnt allow the user to remove the default `bridge` network. will fix it.
regarding the other issue, you are trying to remove the driver `null`. the network name is `none`.
can you try that ?

**Comment by moxiegirl** [comment] 2015-10-22 04:11
@mavenugo Yep, that time I got the right error.  Got a question how come the default bridge network is not name `bridge0` ?  I was expecting to see that. It would fit with your explanation to me and maybe provide a hint to users coming from the old 1.8 world

**Comment by mavenugo** [comment] 2015-10-22 19:59
@moxiegirl thats because docker0 is a bridge name and is an implementation detail. folks are familiar with `--net=bridge`, which is the network that people are used to.

**Comment by moxiegirl** [comment] 2015-10-22 20:05
@mavenugo your implementation detail is surfaced through `ifconfig` which shows `docker0`  on the host. Your dismissal doesn't jive with how you explained networks to me. There, you started by talking about the old `docker0` bridge as a means of conveying knowledge. By not using `docker0` as this default network name, you are denying existing customers the same clarity you delivered in your verbal explanation to me.

**Comment by mavenugo** [comment] 2015-10-22 20:12
@moxiegirl i see your point. but, that is a documentation thing to communicate to the user. as you know, the `--net` has been enhanced to support user-defined networks. If you look at the current --net option you can see they are `bridge`, `host`, `none`. They are mapped directly to the network names. docker0 is something that the user never configures or sees in this context. `ifconfig` is the implementation detail I was refering to. So, IMO, I think in order to provide proper compatibility with the existing UX and extending for the 1.9 features, the `--net` should be the reference point and not the bridge name that is created by the driver.

But I do agree that it was easy to explain on the whiteboard with docker0 because bridge is such a common word. Lets make sure we communicate the same in documentation.

**Comment by moxiegirl** [comment] 2015-10-22 20:31
@mavenugo It is a grave mistake to rely on documentation to convey what a UX can do more easily.  You yourself don't rely on documentation as you told me.  Rare is the person that reads something once and recalls it perfectly forever -- yet our implementation can do this forever by being consistent and thought in choosing things even as simple as the name of a single element.

Considering we are at RC1 and there is time, unless this is a major break or a major piece of work (over an hour), we should do it.

**Comment by mavenugo** [comment] 2015-10-22 20:40
@moxiegirl how about my explanation above ?
```
as you know, the --net has been enhanced to support user-defined networks. If you look at the current --net option you can see they are bridge, host, none. They are mapped directly to the network names. docker0 is something that the user never configures or sees in this context. ifconfig is the implementation detail I was refering to. So, IMO, I think in order to provide proper compatibility with the existing UX and extending for the 1.9 features, the --net should be the reference point and not the bridge name that is created by the driver.
```

**Comment by mavenugo** [comment] 2015-10-22 20:41
@moxiegirl and how about users who are used to `--net=bridge` , do you want to change that to `--net=docker0` ?

**Comment by moxiegirl** [comment] 2015-10-22 20:44
You don't give the default `null` network a name of `null` you call it none.  I'm just asking you to call the default bridge network `docker0` so that it matches what it was known as in the past.

```
NETWORK ID          NAME                DRIVER
0bad5fe884f2        none                null                
b06fb2876a91        host                host                
275ceccf4a8b        docker0              bridge     
```

The network driver name should remain `bridge` of course.

**Comment by mavenugo** [comment] 2015-10-22 20:57
@moxiegirl the network name is `none` as in --net=none. same as --net=bridge.
the driver names are entirely different from network names.

**Comment by icecrime** [comment] 2015-10-22 21:16
Bridge is the right name, especially as you can replace the actual bridge interface by something else and it's still `--net=bridge`.

**Comment by mavenugo** [comment] 2015-10-22 21:19
@icecrime good point. today the bridge network does take other bridges that are not docker0 using the -b option.

**Comment by moxiegirl** [comment] 2015-10-23 13:38
@mavenugo @icecrime Madhu sorted me in a convo yesterday.  I think I'm down to the original purpose of this issue, I was able to remove the default bridge. --- is that still valid?

**Comment by mavenugo** [comment] 2015-10-23 15:00
Thanks @moxiegirl. Yes the default bridge deletion will be addressed.

**Comment by vieux** [comment] 2015-10-28 04:41
I have the same issue with docker-1.9.0rc3:

```
$ docker version
Client:
 Version:      1.9.0-rc3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2100b94
 Built:        Wed Oct 28 01:29:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2100b94
 Built:        Wed Oct 28 01:29:10 UTC 2015
 OS/Arch:      linux/amd64

ubuntu@node-2:~$ docker network ls
NETWORK ID          NAME                DRIVER
fbe71653f1cc        swarm               overlay
5af18d78297b        host                host
c5e0bc826099        bridge              bridge
1991225575e0        none                null

# rm via ID
ubuntu@node-2:~$ docker network rm c5e0bc826099
ubuntu@node-2:~$ docker network ls
NETWORK ID          NAME                DRIVER
fbe71653f1cc        swarm               overlay
5af18d78297b        host                host
1991225575e0        none                null

ubuntu@node-2:~$ docker network create bridge
880c67cc889570fc39156eecdefee00a47877506f7e36ebb3b2a9be8e1839dc1
ubuntu@node-2:~$ docker network ls
NETWORK ID          NAME                DRIVER
fbe71653f1cc        swarm               overlay
880c67cc8895        bridge              bridge
1991225575e0        none                null
5af18d78297b        host                host

#rm via name
ubuntu@node-2:~$ docker network rm bridge
ubuntu@node-2:~$ docker network ls
NETWORK ID          NAME                DRIVER
fbe71653f1cc        swarm               overlay
5af18d78297b        host                host
1991225575e0        none                null
```

**Comment by mavenugo** [comment] 2015-10-28 13:10
@vieux can you pls confirm if you see this in master ?
@tiborvass i couldnt find https://github.com/docker/docker/issues/17351 as 1 of the patches in https://github.com/docker/docker/issues/17000 
Can you pls confirm ?

**Comment by vieux** [comment] 2015-10-28 18:04
I confirm, I cannot reproduce on master

**Comment by mavenugo** [comment] 2015-10-28 20:52
thanks @vieux at this point, we have to make sure #17351 is pulled in for the release.We can keep this issue open just to make sure

**Comment by mavenugo** [comment] 2015-10-31 13:25
Now that #17351 is pulled in for RC4, we can close this.

**Closed by mavenugo** 2015-10-31 13:25 UTC
Labels: group/networking
