### ISSUE TITLE
Regression error with docker 1.0.1

### ISSUE THREAD

**Issue by deniszgonjanin** [docker/docker#6800] opened 2014-07-01 20:51 UTC
Here is the simplest possible Dockerfile to reproduce the issue - a simple tomcat service
```
FROM ubuntu:14.04

RUN apt-get -q -y update
RUN DEBIAN_FRONTEND=noninteractive apt-get -q -y install tomcat6

RUN service tomcat6 start
```

This fails at the last step, because the service fails to start. However, tomcat does in fact run. If we start a container such as this (starting tomcat6 as entrypoint), and inspect the running processes, we can see that tomcat is indeed up and running. Exposing the tomcat port would show us that tomcat is alive and well, and fully useable. The system thinks the service failed to start, for reasons unknown to me. This is a big problem since we need to be able to rely on `service` working properly.

This problem appeared in docker 1.0.1, and this same Dockerfile worked perfectly in docker 0.8. Unfortunately I cannot tell which is the last docker version where this did work.

***************
Here is other relevant info:
```
$docker version
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
Server version: 1.0.1
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 990021a
```

```
$docker -D info
Containers: 7
Images: 81
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 95
Execution Driver: native-0.2
Kernel Version: 3.14.1-tinycore64
Debug mode (server): true
Debug mode (client): true
Fds: 11
Goroutines: 10
EventsListeners: 0
Init Path: /usr/local/bin/docker
```

```
$uname -a
Linux boot2docker 3.14.1-tinycore64 #1 SMP Mon Jun 2 04:19:19 UTC 2014 x86_64 GNU/Linux
```
Although I've reproduced the same problem on:
```
$uname -a
Linux peach 3.14-0.bpo.1-amd64 #1 SMP Debian 3.14.5-1~bpo70+1 (2014-06-05) x86_64 GNU/Linux
```

**Comment by mishak87** [comment] 2015-01-12 17:51
Has anything changed? Just stumbled upon the same problem even with `--cap-add SYS_PTRACE` I still get `Permission denied` for `/proc/{id}/exe`. (docker 1.4.1 5bc2ff8, image: debian:6.0.10, host: ubuntu 14.04 x86_64 3.13.0-43-generic).

**Comment by fvanderbiest** [comment] 2015-01-12 19:16
Same issue here (docker 1.4.1, image: debian jessie, host: ubuntu 14.04 x86_64 3.13.0-44-generic)

**Comment by mishak87** [comment] 2015-01-13 09:40
Status? Just stumbled upon the same problem even with `--cap-add SYS_PTRACE` I still get `Permission denied` for `/proc/{id}/exe`. (docker 1.4.1 5bc2ff8, image: debian:6.0.10, host: ubuntu 14.04)

**Comment by CCTJNII** [comment] 2015-01-22 00:47
This breaks sysvinitscripts in CentOS/RHEL as they call 'pidof -c' to check process status, which uses /proc/[pid]/root to detect chroots:

```
[root@c67c75b29a6d /]# strace pidof -c logger 2>&1 | grep '/proc/[0-9]\+/root'
stat("/proc/87/root", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/proc/29/root", 0x7fffc6552060)   = -1 EACCES (Permission denied)
```

Whereas outside of Docker stat does not return error:

```
[root@prod-po-tjniivm1 ~]# strace pidof -c logger 2>&1 | grep '/proc/[0-9]\+/root'
stat("/proc/4149/root", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/proc/3749/root", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
```

pidof -c failing in the container causes the __pids_pidof() function in /etc/init.d/functions to return no pids, even if the process is running.  This breaks the status() function as well as the killproc() function.  The latter may break stop functionality of an init script.

'--cap-add SYS_PTRACE' resolves this for me on 1.2.0.

**Comment by md-5** [comment] 2015-01-22 05:56
I really think this lack of SYS_PTRACE by default breaks a substantial use case for docker:
Pretty much everyone running an init script.


I urge the developers to give more thought to adding this as a capability.

**Comment by aboullaite** [comment] 2015-02-17 15:13
I had lately the same issue, but this time trying to provision a docker ubuntu image with puppet. Everything works just fine (the installation of java and Tomcat) until the last step: start the tomcat service, it fails:

```
Error: Could not start Service[tomcat7]: Execution of '/etc/init.d/tomcat7 start' returned 1: * Starting Tomcat serv
let engine tomcat7                                                                                                  
   ...fail!                                                                                                         
Wrapped exception:                                                                                                  
Execution of '/etc/init.d/tomcat7 start' returned 1: * Starting Tomcat servlet engine tomcat7                       
   ...fail!                                                                                                         
Error: /Stage[main]/Tomcat/Service[tomcat7]/ensure: change from stopped to running failed: Could not start Service[t
omcat7]: Execution of '/etc/init.d/tomcat7 start' returned 1: * Starting Tomcat servlet engine tomcat7              
   ...fail! 
```

**Comment by jsminet** [comment] 2015-02-19 10:03
1) Use ** RUN service tomcat7 start && tail -f /var/lib/tomcat7/catalina.out ** in your Dockerfile
2) Add **--privileged=true** parameter with docker run command. Tomcat need extended privileges.
Example: $ docker run --privileged=true --it -p 8080:8080 tomcat7-image-name

**Comment by cpuguy83** [comment] 2015-02-19 15:06
@jsminet tomcat itself does **not** need privileged, it's the startup script which is calling start-stop-daemon that needs it, and it's completely pointless.

**Comment by jfrazelle** [comment] 2015-02-26 19:12
We can close this, there is an official tomcat image and that works perfectly

**Comment by jfrazelle** [comment] 2015-02-26 19:12
see https://registry.hub.docker.com/_/tomcat/

**Closed by jfrazelle** 2015-02-26 19:12 UTC
Labels: Runtime

**Comment by CCTJNII** [comment] 2015-02-26 19:24
This regression is bigger than just Tomcat, has the "pidof -c" error documented above which breaks sysvinit scripts been fixed?

**Comment by jfrazelle** [comment] 2015-02-26 19:29
@CCTJNII I think this issue is a bit confusing can we move just that part of it to a new one, can you point me to that comment

**Comment by CCTJNII** [comment] 2015-02-26 19:35
@jfrazelle https://github.com/docker/docker/issues/6800#issuecomment-70951948

**Comment by mkostrikin** [comment] 2015-03-20 07:19
under ubuntu worked so:
```shell
docker run -itd --cap-add=SYS_PTRACE --security-opt=apparmor:unconfined mytomcat7image
```

**Comment by ThomasSteinbach** [comment] 2015-04-17 08:55
Am I happy to find at least an explanation of the _service tomcat7 start_ behavior. I tried to install and run tomcat on different versions of ubuntu containers, I installed tomcat inside a vagrant ubuntu where everything runs fine, I compared the configuration (which was obvious equal), I ran the startup script with _sh -x_ where I got to the command that fails, which slowly took my after several other investigations and google searches to this issue.

@jfrazelle Even though there is an official tomcat, why shouldn't I am be able to create my own tomcat image? I am playing around with building images by running Ansible playbooks during the build, which are much more appealilng than loads of scripts. Now I got some playbooks running inside a container started with ```--cap-add=SYS_PTRACE``` but build them with ```docker build``` because there is no such option.

After I had read all the previous comments I hear the voice that there should be no concerns by allowing _SYS_PTRACE_ by default. Shouldn't it be considered to save others the troubles I and some others had, by allowing _SYS_PTRACE_ by default? Or could it be possible to inform users, when an action (during the build) needs one of those 'caps' (I haven't fully got what caps are) so that he can at least find faster solutions on the internet?

And finally, is there a possibility to run something like
```
docker build --cap-add=SYS_PTRACE ...
```
?

**Comment by md-5** [comment] 2015-04-17 09:24
@ThomasSteinbach might wanna try posting to #11049, this issue is closed

**Comment by msmuenchen** [comment] 2017-10-20 11:41
Hi, I have hit the same issue when trying to do a `/etc/init.d/tomcat6 start` in the debian-eol/squeeze image with sun-java6-jdk and tomcat6 installed - I have solved it by running the container in privileged mode, but that shouldn't be neccessary.

**Comment by thaJeztah** [comment] 2017-10-20 12:58
@msmuenchen see the comment above https://github.com/moby/moby/issues/6800#issuecomment-75066781 ; also you may find some hint sin the official Tomcat image's Dockerfile; https://hub.docker.com/_/tomcat/

**Comment by interone-ms** [comment] 2020-03-18 12:17
@thaJeztah this impacts everything to this day that tries to use start-stop-daemon with --exec, including Ubuntu 18.04's tomcat init script.

I understand that either `--cap-add=SYS_PTRACE` or modifying the Ubuntu init script works to fix the issue, but honestly both should not be necessary - common software installed in OSes should work out of the box.

What I don't get is why it's `SYS_PTRACE` that is required. According to the [manual page](http://man7.org/linux/man-pages/man7/capabilities.7.html), `CAP_SYS_PTRACE` doesn't do anything regarding `/proc/<pid>/exe`, so this is either a kernel bug/documentation issue (which would be a WTF on its own), or some fuckup inside Docker itself. Also, why is `/proc/<pid>/exe` access restricted anyway? It's only a symbolic link and should not open anything dangerous.

**Comment by thaJeztah** [comment] 2020-03-18 12:56
@interone-ms this is a 6 year old ticket; please open a new ticket with the details requested in the issue template when you open the ticket.
