### ISSUE TITLE
default restart policy of service is ambiguous

### ISSUE THREAD

**Issue by allencloud** [docker/docker#27018] opened 2016-09-29 10:07 UTC
**Description**
I think swarm service api is ambiguous in the respect of restart policy.

When we create service via `docker service create ubuntu:14.04 sleep 10000`, docker cli will construct an api request. At last engine creates a service(for instance ServiceA). When we `docker service inspect ServiceA`, we will find 
```
"RestartPolicy": {
                    "Condition": "any",
                    "MaxAttempts": 0
                },
```
It makes me feel that the default restartPolicy of service is any.

While when I call the api call `POST 192.168.59.103:2375/services/create` with request body like below:
```
{
        "Mode": {
            "Replicated": {
                "Replicas": 1
            }
        },
        "TaskTemplate": {
            "Placement": {
                "Constraints": []
            },
            "ContainerSpec": {
                "Command": [],
                "User": "",
                "Image": "ubuntu:14.04",
                "Args": [
                    "sleep",
                    "100000"
                ],
                "Dir": ""
            }
        }
}
```
No field `RestartPolicy` input in filed `TaskTemplate`. We call the created service `ServiceB`. When we `docker service inspect ServiceB`, we got no `RestartPolicy` in response.

**What is more**
I was thinking that restart policy can not empty, even if it is none, it still can be regarded as an action facing task stop. So it is usable for us to have a default restart policy.

Further, when we created service using the api call with `nil` RestartPolicy, then what will the task do facing failure. Not sure about it via the api understanding.

Open for any input.
Please correct me if I missed something important.

Another issue, in container restart policy there is `no`, while service restart policy is `none`, maybe some incompatibility occurs.

**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 21
 Running: 9
 Paused: 0
 Stopped: 12
Images: 63
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 491
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: bq7s60u2mvmcqgc6grxqsx4rm
 Is Manager: true
 ClusterID: dxatb9esopzk5md71b8yfr6as
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.59.103
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 68
 Goroutines: 213
 System Time: 2016-09-28T09:22:33.078936348+08:00
 EventsListeners: 9
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 a=b
 c=d
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2016-09-29 10:35
Yes, @aaronlehmann mentioned this earlier this week; basically thought is (IIRC) to merge the defaults with the user-specified parameters, and set _that_ as the service definition/spec. Currently I think the defaults are merged at "runtime", which could be a potential issue if defaults change.

Also see https://github.com/docker/docker/pull/25697 


> Another issue, in container restart policy there is no, while service restart policy is none, maybe some incompatibility occurs.

That's not consistent, indeed. Possibly we need an alias (either on `docker run` or on `docker service`)

**Comment by aaronlehmann** [comment] 2016-09-29 10:42
I think of this as a duplicate of #24959.

The behavior I would like to see is: When the user does not specify a parameter such as "restart condition", that parameter is not included in the spec. Then the manager can control the default behavior, instead of having a default hardcoded by the CLI.

**Comment by thaJeztah** [comment] 2016-09-29 10:44
Ah, yes! GitHub search failed me this time. Lets close this one in favor of https://github.com/docker/docker/issues/24959

**Closed by thaJeztah** 2016-09-29 10:44 UTC
Labels: area/swarm, kind/enhancement, version/1.12

**Comment by allencloud** [comment] 2016-09-29 10:48
Oh, Sorry for my bothering. 
> Another issue, in container restart policy there is no, while service restart policy is none, maybe some incompatibility occurs.

Maybe such situation is not so user-friendly.
