### ISSUE TITLE
Docker : spin multiple containers using curl

### ISSUE THREAD

**Issue by prabalghosh** [docker/docker#20809] opened 2016-03-01 09:31 UTC
Hi,
 I am trying to spin multiple containers using curl.
For example ,
i have the following sample config.json file.
{ #1st redis container
      "name" : "redis1",
      "Hostname" : "",
      "Domainname" : "",
      "User" : "",
      "AttachStdin" : false,
      "AttachStdout" : true,
      "AttachStderr" : true,
      "Tty" : false,
      "OpenStdin" : false,
      "StdinOnce" : false,
      "Env" : [],
      "Cmd" : [],
      "Entrypoint" : [],
      "Image" : "redis:latest",
      "Labels" : {},
      "Volumes" : {},
      "WorkingDir" : "",
      "NetworkDisabled" : false,
      "ExposedPorts" : {},
      "HostConfig" : {
        "Binds" : ["/tmp1:/tmp1"],
        "Memory" : 0,
        "MemorySwap" : 0,
        "CpuShares" : 0,
        "RestartPolicy": {
            "MaximumRetryCount": 2,
            "Name": "always"
        },
        "PublishAllPorts" : false,
        "Privileged" : false
      },
     { #2nd redis container 
      "name" : "redis2",
      "Hostname" : "",
      "Domainname" : "",
      "User" : "",
      "AttachStdin" : false,
      "AttachStdout" : true,
      "AttachStderr" : true,
      "Tty" : false,
      "OpenStdin" : false,
      "StdinOnce" : false,
      "Env" : [],
      "Cmd" : [],
      "Entrypoint" : [],
      "Image" : "redis:latest",
      "Labels" : {},
      "Volumes" : {},
      "WorkingDir" : "",
      "NetworkDisabled" : false,
      "ExposedPorts" : {},
      "HostConfig" : {
        "Binds" : ["/tmp1:/tmp1"],
        "Memory" : 0,
        "MemorySwap" : 0,
        "CpuShares" : 0,
        "RestartPolicy": {
            "MaximumRetryCount": 2,
            "Name": "always"
        },
        "PublishAllPorts" : false,
        "Privileged" : false
      }

Then using docker HTTP API end point to create the conatiners by passing the above json file.

curl -X POST --header "Content-Type: application/json" http://localhost:2375/containers/create --data @config.json 

But unfortunately , containers are not created.

Is it really possible to spin up multiple containers using the method above???

Output of `docker version`:
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Regards,
Prabal

**Comment by thaJeztah** [comment] 2016-03-01 13:43
The create endpoint creates a *single* container, not multiple; https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container. If you want to script creating containers from the shell, perhaps just use the docker binary (`docker create ..`), or you may be interested in Docker compose, which allows you to define all the containers for your project in a single docker-compose.yml file https://docs.docker.com/compose/compose-file/

Please keep in mind that the GitHub issue tracker is not a general support forum for working with docker, but for reporting bugs and feature requests. For other type of questions, consider using:

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

I'm going to close this issue, because this is not a bug report, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-03-01 13:43 UTC
