### ISSUE TITLE
can't Mount a Host Directory as a Data Volume to container  using  training/webapp image

### ISSUE THREAD

**Issue by DanielYuan2012** [docker/docker#12956] opened 2015-05-04 10:32 UTC
my environment:

ubuntu  on VMPlayer:

daniel@ubuntu:~$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

Daniel@ubuntu:~$ docker -D info
Containers: 19
Images: 143
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 181
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 1.941 GiB
Name: ubuntu
ID: 2ELS:FM2V:KTA7:AY3L:MRFH:SFHC:IPRT:J5EZ:GENT:Z7UB:DMVN:A2RS
Debug mode (server): false
Debug mode (client): true
Fds: 11
Goroutines: 16
System Time: Mon May  4 04:12:44 PDT 2015
EventsListeners: 0
Init SHA1: 9145575052383dbf64cede3bac278606472e027c
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: eaglehenley
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
daniel@ubuntu:~$ uname -a
Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
daniel@ubuntu:~$ 

run the command ：

docker run -d -P --name web11  -v /src/webapp:/opt/webapp  training/webapp  python app.py
25c331cc25a0d35c3b572e42a614c3425d395af9de4bb2efcccb7334b523ae47

the web11 container exited immediately

check the container log:
daniel@ubuntu:~$ docker logs web11
python: can't open file 'app.py': [Errno 2] No such file or directory

when not mount a host directory, 
run this command:
sudo docker run -d -P --name web -v /webapp training/webapp python app.py

container can be created  and run in daemon  mode successfully.

There should be some issue when analyse the arguments when mount a directory to a
 container using training/webapp image.

**Comment by cpuguy83** [comment] 2015-05-04 14:24
is `/src/webapp` on the fs local to the docker daemon?
Was it mounted into the host after the docker daemon was started?

**Comment by DanielYuan2012** [comment] 2015-05-06 02:21
/src/webapp is folder on host and it existed before docker container was started, even thought i restart docker service, the same issue still exists.

**Comment by calavera** [comment] 2015-06-01 22:28
I just double checked this issue and I could not reproduce it with docker `1.6.2`. This is my output:

```
vagrant@vagrant:/vagrant$ sudo docker run -d -P --name web11 -v /home/vagrant/src/webapp:/opt/webapp training/webapp python app.py
a927c85eee5752f2272ce27d4b842ca8bf77acb094dbbf96f6b2c2ae9b180ba7
vagrant@vagrant:/vagrant$ docker logs web11
vagrant@vagrant:/vagrant$ sudo docker logs web11
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
vagrant@vagrant:/vagrant$
```

And this is the content of `/home/vagrant/src/webapp`:

```
vagrant@vagrant:/vagrant$ ls /home/vagrant/src/webapp/
app.py
vagrant@vagrant:/vagrant$
```

I'm going to close this issue since it looks like it's related to your host. Please, feel free to reopening it if you find more information that might be related with being a problem mounting volumes within docker.

**Closed by calavera** 2015-06-01 22:28 UTC
