### ISSUE TITLE
Network problem when using a second eth interface that have a bloc IP on it. (config included)

### ISSUE THREAD

**Issue by Xoib** [docker/docker#7807] opened 2014-08-30 12:40 UTC
Hello,

One problem is that containers can't reach each other, when I ping from one to the other via the public ip redirected to them, it doesn't pass (see iptables problem below).

The other problem is that every time I docker stop on a container, before I start it again I have to restart the whole docker (the daemon), if not, there is the port already binded error. Even if I lsof, I don't see it bind, but docker think it is...

Also if I want to access the container from outside, I have to delete nat rule within DOCKER statement in iptables -L -t nat.

I have a bloc IP from OVH bind on eth1 of my server. It has been a few weeks I run with that, I guess now I have to share it here so we can find how to solve the problem and stop the workarounds. I only have one container that use the address on eth0, all the others is using an IP of the bloc on eth1.

Kernel:
```
Linux 3.14-0.bpo.1-amd64 #1 SMP Debian 3.14.12-1~bpo70+1 (2014-07-13) x86_64 GNU/Linux
```

Docker:
```
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): d84a070
```

Here is my /etc/network/interfaces :
```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
        address 38.58.18.236
        netmask 255.255.255.0
        network 38.58.18.0
        broadcast 38.58.18.255
        gateway 38.58.18.254

iface eth0 inet6 static
        address 2001:41D0:8:65ec::
        netmask 64
        post-up /sbin/ip -f inet6 route add 2001:41D0:8:65ff:ff:ff:ff:ff dev eth0
        post-up /sbin/ip -f inet6 route add default via 2001:41D0:8:65ff:ff:ff:ff:ff
        pre-down /sbin/ip -f inet6 route del default via 2001:41D0:8:65ff:ff:ff:ff:ff
        pre-down /sbin/ip -f inet6 route del 2001:41D0:8:65ff:ff:ff:ff:ff dev eth0

auto eth1
iface eth1 inet static
     address 38.58.252.224
     netmask 255.255.255.224
     post-up /sbin/ip route add default via 38.58.252.254 dev eth1 table 125
     post-up /sbin/ip rule add from 38.58.252.224/27 table 125
     pre-down /sbin/ip rule del from 38.58.252.224/27 table 125
     pre-down /sbin/ip route del default via 38.58.252.254 dev eth1 table 125
     post-up /sbin/ip addr add 38.58.252.225/27 dev eth1
     post-down /sbin/ip addr add 38.58.252.225/27 dev eth1
     post-up /sbin/ip addr add 38.58.252.226/27 dev eth1
     post-down /sbin/ip addr add 38.58.252.226/27 dev eth1
     post-up /sbin/ip addr add 38.58.252.227/27 dev eth1
     post-down /sbin/ip addr add 38.58.252.227/27 dev eth1
     post-up /sbin/ip addr add 38.58.252.228/27 dev eth1
     post-down /sbin/ip addr add 38.58.252.228/27 dev eth1
```
	 
Here is the ip addr:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:25:90:dd:32:0c brd ff:ff:ff:ff:ff:ff
    inet 38.58.18.236/24 brd 38.58.18.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:41d0:8:65ec::/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::225:80ff:fedd:320c/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:25:90:dd:32:0d brd ff:ff:ff:ff:ff:ff
    inet 38.58.252.225/27 scope global eth1
       valid_lft forever preferred_lft forever
    inet 38.58.252.226/27 scope global secondary eth1
       valid_lft forever preferred_lft forever
    inet 38.58.252.227/27 scope global secondary eth1
       valid_lft forever preferred_lft forever
    inet 38.58.252.228/27 scope global secondary eth1
       valid_lft forever preferred_lft forever
    inet 38.58.252.224/27 brd 38.58.252.255 scope global secondary eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::225:80ff:fedd:320d/64 scope link
       valid_lft forever preferred_lft forever
267: veth49fb: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master docker0 state UP qlen 1000
    link/ether 52:3a:a2:ce:19:06 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::503a:a2ff:fece:1906/64 scope link
       valid_lft forever preferred_lft forever
277: veth9707: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master docker0 state UP qlen 1000
    link/ether 4e:19:2f:c7:26:db brd ff:ff:ff:ff:ff:ff
    inet6 fe80::4c19:2fff:fec7:26db/64 scope link
       valid_lft forever preferred_lft forever
53: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::5484:7aff:fefe:9799/64 scope link
       valid_lft forever preferred_lft forever
329: veth66fa: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master docker0 state UP qlen 1000
    link/ether d2:06:6c:c8:de:09 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::d006:6cff:fec8:de09/64 scope link
       valid_lft forever preferred_lft forever
185: veth652d: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master docker0 state UP qlen 1000
    link/ether 8a:f9:3a:e4:27:2e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::88f9:3aff:fee4:272e/64 scope link
       valid_lft forever preferred_lft forever
191: veth3dbb: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master docker0 state UP qlen 1000
    link/ether f6:d2:d5:91:b2:d0 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::f4d2:d5ff:fe91:b2d0/64 scope link
       valid_lft forever preferred_lft forever
193: vethe287: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master docker0 state UP qlen 1000
    link/ether fe:42:2b:b5:eb:25 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc42:2bff:feb5:eb25/64 scope link
       valid_lft forever preferred_lft forever
207: veth9f71: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master docker0 state UP qlen 1000
    link/ether de:d5:4b:b9:0a:f1 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::dcd5:4bff:feb9:af1/64 scope link
       valid_lft forever preferred_lft forever
```

iptables -L -t nat :
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  172.17.0.0/16       !172.17.0.0/16

Chain DOCKER (2 references)
target     prot opt source               destination
DNAT       tcp  --  anywhere             alpha.xoib.com    tcp dpt:63389 to:172.17.0.60:389
```

I kept the last one because it is on the adress of eth0, the others for eth1 I had to delete them for the container to be reachable from outside

I changed all the dns name and adresses to keep the server private.

Thanks,

**Comment by jfrazelle** [comment] 2015-02-26 19:26
closing as duplicate of https://github.com/docker/docker/issues/2801, it is really a effect caused by that issue

**Closed by jfrazelle** 2015-02-26 19:26 UTC
