### ISSUE TITLE
task numbers is more then replicas

### ISSUE THREAD

**Issue by bridgeunions** [docker/docker#27769] opened 2016-10-26 07:13 UTC
when I create a service which replicas is 1, it create 6 tasks

[root@myhost:~]# docker service ls
ID            NAME              REPLICAS  IMAGE                                            COMMAND
6gfawkrtuzvi  nostalgic_fermat  6/1       hub.xxx.com/apps/mms-webapp-read  
9ch5s6hhld4q  awesome_dubinsky  1/1       hub.xxx.com/apps/mms-webapp-read  

how to reproduct this:
1: I create a service but the worker node is not work well, when a task is create then it reject because of some error
   [root@sa-swarm0-cnc0.hlg01:~]# docker service ps nostalgic_fermat
ID                         NAME                    IMAGE                                            NODE                   DESIRED STATE  CURRENT STATE           ERROR
35jwskt0puhclfup54q3xm4ky  nostalgic_fermat.1      hub.xxx.com/apps/mms-webapp-read  sa-docker0-cnc1.hlg01  Ready          Rejected 1 seconds ago  "SELinux relabeling of /var/li…"
bg129rq2nobamqr86ihus8nzi   \_ nostalgic_fermat.1  hub.xxx.com/apps/mms-webapp-read  sa-docker0-cnc1.hlg01  Ready          Rejected 2 seconds ago  "SELinux relabeling of /var/li…"
dcp0ydp6kc7q5lio86pxzk8j9   \_ nostalgic_fermat.1  hub.xxx.com/apps/mms-webapp-read  sa-docker0-cnc1.hlg01  Ready          Rejected 2 seconds ago  "SELinux relabeling of /var/li…"
3xrz5nd204wi961yq3uiqbgsl   \_ nostalgic_fermat.1  hub.xxx.com/apps/mms-webapp-read  sa-docker0-cnc1.hlg01  Ready          Rejected 1 seconds ago  "SELinux relabeling of /var/li…"
ad0c8su9muir70kae9hzp9c10   \_ nostalgic_fermat.1  hub.xxx.com/apps/mms-webapp-read  sa-docker0-cnc1.hlg01  Ready          Rejected 4 seconds ago  "SELinux relabeling of /var/li…"

2.then  I fix one node, it like this
[root@sa-swarm0-cnc0.hlg01:~]# docker service ps nostalgic_fermat
ID                         NAME                    IMAGE                                            NODE                   DESIRED STATE  CURRENT STATE                     ERROR
axivol94n6bhw1c0vggdm15bq  nostalgic_fermat.1      hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc0.hlg01  Ready          Preparing less than a second ago  
6flvk5gw3p5ga2ebzdy91fm2z   \_ nostalgic_fermat.1  hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc0.hlg01  Ready          Preparing less than a second ago  
2i7n1oosfonzmunimz127ohut   \_ nostalgic_fermat.1  hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc0.hlg01  Ready          Preparing less than a second ago  
b6fv953pv6fdwyvsdual2exxm   \_ nostalgic_fermat.1  hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc1.hlg01  Ready          Rejected 1 seconds ago            "SELinux relabeling of /var/li…"
5j6edduvau1k6w8b323ic85i3   \_ nostalgic_fermat.1  hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc1.hlg01  Ready          Rejected 2 seconds ago            "SELinux relabeling of /var/li…"
8yuyqagd5manrp0zfrip9pjt8   \_ nostalgic_fermat.1  hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc1.hlg01  Ready          Rejected 3 seconds ago            "SELinux relabeling of /var/li…"
[root@sa-swarm0-cnc0.hlg01:~]#

3. then I fix another
[root@sa-swarm0-cnc0.hlg01:~]# docker service ps nostalgic_fermat
ID                         NAME                    IMAGE                                            NODE                   DESIRED STATE  CURRENT STATE           ERROR
8xqtw0i30gguqlq2nsangi0tb  nostalgic_fermat.1      hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc1.hlg01  Ready          Assigned 2 seconds ago  
8phczh3091i8s7nixbdi9mdya   \_ nostalgic_fermat.1  hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc1.hlg01  Ready          Assigned 2 seconds ago  
cs1a30srokdptkbybkw3vnjzj   \_ nostalgic_fermat.1  hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc1.hlg01  Ready          Assigned 4 seconds ago  
axivol94n6bhw1c0vggdm15bq   \_ nostalgic_fermat.1  hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc0.hlg01  Running        Running 35 seconds ago  
6flvk5gw3p5ga2ebzdy91fm2z   \_ nostalgic_fermat.1  hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc0.hlg01  Running        Running 35 seconds ago  
2i7n1oosfonzmunimz127ohut   \_ nostalgic_fermat.1  hub.internal.wandoujia.com/apps/mms-webapp-read  sa-docker0-cnc0.hlg01  Running        Running 7 seconds ago

then I got what I have

docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-144735-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.272 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.23 GB
 Metadata Space Used: 2.15 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: active
 NodeID: 7y98mueh7qojrugn2sityx1z1
 Is Manager: true
 ClusterID: 750w4cbchgc1hn6f6b69zr1b1
 Managers: 5
 Nodes: 9
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.19.29.12
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
Name: sa-swarm0-cnc0.hlg01
ID: GQYK:LD57:TCAA:DEB3:FA63:QZ2S:DN7N:W23E:ODEB:FEBM:J4T2:OV5E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 58
 Goroutines: 135
 System Time: 2016-10-26T15:13:26.681290012+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 hub.internal.wandoujia.com
 127.0.0.0/8

**Comment by thaJeztah** [comment] 2016-10-26 07:20
Looks like this is a duplicate of https://github.com/docker/docker/issues/27382, which will be fixed in docker 1.12.3. If you want to test that release, a release candidate is available for testing https://github.com/docker/docker/releases/tag/v1.12.3-rc1

I'll close this issue, as it should be resolved, but feel free to continue the conversation

**Closed by thaJeztah** 2016-10-26 07:20 UTC
