### ISSUE TITLE
https://docs.docker.com/engine/reference/builder/  --> Sorry, we can't find that page

### ISSUE THREAD

**Issue by rst0git** [docker/docker#30301] opened 2017-01-20 03:37 UTC
Seems like the Dockerfile reference web-page does not exist anymore or if the url has been changed google does not find it for some reason.

The page is still on github https://github.com/docker/docker/blob/master/docs/reference/builder.md

**Comment by NavinF** [comment] 2017-01-20 05:44
Yeah, I'm seeing "Sorry, we can't find that page" too on the following URLs:

1. https://docs.docker.com/sorry/#/engine/reference/commandline/cli/
1. https://docs.docker.com/sorry/#/engine/reference/run/
1. https://docs.docker.com/sorry/#/engine/reference/builder/

Who runs the website?

**Comment by r17n** [comment] 2017-01-22 04:18
I am able to access https://docs.docker.com/engine/reference/builder/ right now.  @rst0git , are you still seeing the problem?

**Comment by thaJeztah** [comment] 2017-01-23 16:32
Yes, this issue was caused by a switch in the way the "reference" docs were published for the 1.13 release, and should be fixed now. There are still some issues to work out, but this one is fixed, so let me close this.

If you see additional issues in the documentation, please report them in the documentation issue tracker; https://github.com/docker/docker.github.io/issues

**Closed by thaJeztah** 2017-01-23 16:32 UTC
Labels: area/docs
