### ISSUE TITLE
How to open a port from a running docker conatiner

### ISSUE THREAD

**Issue by vasantivmahajan** [docker/docker#27586] opened 2016-10-20 16:24 UTC
I am running a docker container and I am running my image in the container. I need to connect to Jupyter notebook's web application in a browser. I am able to run the Jupyter notebook in docker but I am unable to run it in the browser. I assume it is because I have not exposed the port with which I am trying to access the notebook in the browser. However, I cannot rebuild my image from scratch, so I am looking for an option to open the port from my running container.

Any help for the same is appreciated.

**Comment by thaJeztah** [comment] 2016-10-21 07:07
Please keep in mind that the github issue tracker is for reporting bugs and feature requests, and is not a general support forum. Consider using;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

For questions on running docker


Since this is not a bug, or feature request, I'll close this issue here

**Closed by thaJeztah** 2016-10-21 07:07 UTC
Labels: kind/question

**Comment by vasantivmahajan** [comment] 2016-10-21 15:59
@thaJeztah: I apologize for the inconvenience caused. I would open my issue on the above forums for assistance.

**Comment by thaJeztah** [comment] 2016-10-21 16:08
Thanks @vasantivmahajan! Make sure to include the exact steps you're using, to make it easier for others to help out

**Comment by vasantivmahajan** [comment] 2016-10-21 16:11
@thaJeztah Sure, will do that.
