### ISSUE TITLE
ContainerInspect output returns bool instead of string for Path if its value is "true"

### ISSUE THREAD

**Issue by ncdc** [docker/docker#6312] opened 2014-06-09 19:26 UTC
If you create a container like this:

`docker run centos true`

and then inspect the container, the json returned for remote API < 1.12 will have this:

`"Path": "true"`

If you inspect with 1.12, however, you get back this:

`"Path": true`

Path should always be a string, and not converted to a boolean. I believe the issue comes from a combination of Env.Encode, and more specifically from https://github.com/dotcloud/docker/blob/master/engine/env.go#L206, where it unmarshals "true" into a bool when it should remain a string.

**Comment by cpuguy83** [comment] 2015-02-20 20:38
Closing since this currently shows "true" as a string in 1.5.
Please ping here if you can reproduce, thanks!

**Closed by cpuguy83** 2015-02-20 20:38 UTC
