### ISSUE TITLE
Install of docker-engine-1.12.0-0.5.rc5.el7.centos fails to start docker.socket

### ISSUE THREAD

**Issue by hekaldama** [docker/docker#25136] opened 2016-07-27 17:48 UTC
# Description of problem:
I have 1.12.0-0.4.rc4 installed, running in swarm mode as manager, with three workers, and one alpine image running `ping host`. If I stop docker, yum remove rc4, then yum install rc5, I cannot restart the daemon with `sudo systemctl start docker`. Instead I get a failure of `Failed to start docker.service: Unit docker.socket failed to load: No such file or directory.`. Output from `sudo systemctl status docker` is:

````
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://docs.docker.com

Jul 26 22:49:15 server dockerd[22662]: time="2016-07-26T22:49:15Z" level=info msg="Firewalld running: false"
Jul 26 22:54:49 server systemd[1]: Stopping Docker Application Container Engine...
Jul 26 22:54:49 server dockerd[22662]: time="2016-07-26T22:54:49.102616962Z" level=info msg="Processing signal 'terminated'"
Jul 26 22:54:49 server dockerd[22662]: time="2016-07-26T22:54:49.104058944Z" level=info msg="Stopping manager"
Jul 26 22:54:49 server dockerd[22662]: time="2016-07-26T22:54:49.104540636Z" level=info msg="Manager shut down"
Jul 26 22:54:49 server dockerd[22662]: time="2016-07-26T22:54:49.106788777Z" level=error msg="container status unavailable" error="context canceled" module=taskmanager task.id=e2mjbekcnf3qsml0oabty06on
Jul 26 22:54:59 server dockerd[22662]: time="2016-07-26T22:54:59.109528320Z" level=info msg="Container 40a543be5d72c608464c98c3e9cd7618aa72387853b2734006ca3b7a9041792c failed to exit within 10 seconds of signal 15 - using the force"
Jul 26 22:55:04 server dockerd[22662]: time="2016-07-26T22:55:04.107655550Z" level=error msg="Force shutdown daemon"
Jul 26 22:55:04 server dockerd[22662]: time="2016-07-26T22:55:04.108847823Z" level=info msg="stopping containerd after receiving terminated"
Jul 26 22:55:05 server systemd[1]: Stopped Docker Application Container Engine.
````

Output from `sudo systemctl status docker.socket` is:
````
● docker.socket
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

Jul 19 18:35:33 server systemd[1]: Starting Docker Socket for the API.
Jul 19 18:35:33 server systemd[1]: Listening on Docker Socket for the API.
Jul 26 22:20:13 server systemd[1]: Closed docker.socket.
Jul 26 22:20:13 server systemd[1]: Stopping docker.socket.
Jul 26 22:47:39 server systemd[1]: Starting Docker Socket for the API.
Jul 26 22:47:39 server systemd[1]: Listening on Docker Socket for the API.
Jul 26 22:55:05 server systemd[1]: Closed Docker Socket for the API.
Jul 26 22:55:05 server systemd[1]: Stopping Docker Socket for the API.
````

````
Client:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        
 OS/Arch:      linux/amd64
 Experimental: true





Linux server 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
````

## Environment details (AWS, VirtualBox, physical, etc.):
CentOS Linux release 7.2.1511 (Core) - Virtual machine

## How reproducible:
Every time.

## Steps to Reproduce:
1. sudo yum install -y docker-engine-1.12.0-0.5.rc5.el7.centos
2. sudo systemctl start docker

## Actual Results:
"Failed to start docker-engine.service: Unit docker-engine.service failed to load: No such file or directory."

## Expected Results:
Docker would start.

**Comment by gaga-github** [comment] 2016-07-27 18:07
I have the same issue, here is the missing file: /usr/lib/systemd/system/docker.socket

````
[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
```

systemctl daemon-reload

Then Docker will start.  It looks like the install removes that file and doesn't replace it.

**Comment by hekaldama** [comment] 2016-07-27 18:36
@gaga-github nice! Maybe do a PR if you want to?

**Comment by gaga-github** [comment] 2016-07-27 18:55
@hekaldama Looks like it was removed on purpose [for SELinux errors](https://github.com/docker/docker/commit/14aee340f88b2aa736eb51b60f281d9a50f15647)

**Comment by thaJeztah** [comment] 2016-07-27 19:01
This is a duplicate of https://github.com/docker/docker/issues/25098, and is fixed on master; see https://github.com/docker/docker/issues/25098#issuecomment-235545856, and https://github.com/docker/docker/pull/25094 for how to fix this.

After updating your unit file, be sure to `sudo systemctl daemon-reload`

I'm closing this as a duplicate of https://github.com/docker/docker/issues/25098, but feel free to continue the discussion

**Closed by thaJeztah** 2016-07-27 19:01 UTC

**Comment by hekaldama** [comment] 2016-07-27 19:14
Great. Thanks all!

**Comment by thaJeztah** [comment] 2016-07-27 19:22
Sorry for the inconvenience, this one slipped through :blush:

**Comment by hekaldama** [comment] 2016-07-27 19:31
No inconvenience. Happy to report the bug.

**Comment by pzxwhc** [comment] 2016-12-06 08:57
@gaga-github Thanks. It works.
