### ISSUE TITLE
No command to check if the image with particular tag exists in the repository

### ISSUE THREAD

**Issue by hrishikesh988** [docker/docker#27257] opened 2016-10-10 16:16 UTC
Hi Guys,

In my code, I want to take image tag as an input from user and then validate the tag against images present in my private repository. Unfortunately, I do not find any command which does that for me. I need do a docker pull and then check if that fails to know the provided image tag was correct or not. Can we have some kind of facility to check if the image tag is present before we try  to pull the image directly.

**Comment by justincormack** [comment] 2016-10-10 20:11
There has been a  suggestion that there should be a seperate CLI tool for interacting with registries, but generally probably not part of the `docker` cli.

**Comment by thaJeztah** [comment] 2016-10-16 22:33
Looks like a duplicate of https://github.com/docker/docker/issues/14254, so I'll close this one

**Closed by thaJeztah** 2016-10-16 22:33 UTC
Labels: area/distribution, kind/feature
