### ISSUE TITLE
After copying docker image, the image is not working.

### ISSUE THREAD

**Issue by IvRRimum** [docker/docker#23216] opened 2016-06-02 19:52 UTC
So basicly i copied [this](https://hub.docker.com/r/commonsearch/local-elasticsearch/) repo and i created my [own](https://hub.docker.com/r/outdream1337/local-elasticsearch/)( based on it )

Previously when i started commonsearch/elasticsearch container it worked perfecly, but after the copy outdream1337@elasticsearch container doesnt work any more. it produces no errors:

```
karlis@karlis-SATELLITE-L750 ~/Projects/search/cosr-back $ docker run -d -p 39200:9200 -p 39300:9300 outdream1337/local-elasticsearch
c2bc8fb75cb1df09ef4b87890fa1ec22760659aa4deed42c5f2cb89f3891bf60
dkarlis@karlis-SATELLITE-L750 ~/Projects/search/cosr-back $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
karlis@karlis-SATELLITE-L750 ~/Projects/search/cosr-back $
```
and logs doesnt say anything ussfull too( because my other repo preduces same errors and everything works ):

```
time="2016-06-02T22:27:58.848821703+03:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]" 
time="2016-06-02T22:27:58.848865787+03:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
ideas ?
```

Also: I did not edit anything, literary copied it and tried to use( i did the same for one other repo and it worked, but for this it doesnt ).

I disabled -d - no errors... really no idea...

ideas ?

**Comment by justincormack** [comment] 2016-06-02 20:16
Those two images are not exactly identical, perhaps you had downloaded an older version that didnt work? It is much easier if you use an image with a Dockerfile available as then it is easier to make modifications and see what is going on.

**Comment by thaJeztah** [comment] 2016-06-02 23:16
I see you also asked this question on StackOverflow, which is a more appropriate place for this question (as it's a support question, not a bug in docker) http://stackoverflow.com/questions/37600561/cant-start-docker-container, So I'll close this issue here

**Closed by thaJeztah** 2016-06-02 23:16 UTC
