### ISSUE TITLE
[integration-cli] [--net none] Fix TestPullImageFromCentralRegistry

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#10966] opened 2015-02-23 22:44 UTC
Fix TestPullImageFromCentralRegistry so it will still be a functional test, but will pass when the test container has --net none.

Use the local registry in the container to pull an image. Change the name of the test to reflect it is no longer pulling from the central registry.

Error output when tests are run with --net none:

```
--- FAIL: TestPullImageFromCentralRegistry (0.13s)
	docker_cli_pull_test.go:92: pulling the hello-world image from the registry has failed: Pulling repository hello-world
		time="2015-02-11T23:21:38Z" level="fatal" msg="Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp: lookup index.docker.io on 8.8.8.8:53: dial udp 8.8.8.8:53: network is unreachable" 
		, exit status 1

```

**Comment by brahmaroutu** [comment] 2015-02-26 19:15
@jfrazelle  Using private registry defeat the purpose of the test, I have the fix anyways. This is where I want to conditionally use private/public registry with a env switch(like in #10963 earlier)? Let me know your thoughts. It effects #10967 and #10968 too in the same way.

**Comment by jfrazelle** [comment] 2015-02-26 19:17
we don't actually need to test that pulling from the central registry works we can pull locally :)

**Comment by estesp** [comment] 2015-02-26 20:09
The only thing we might be losing once we get all these tests moved to only using the local, in-container registry--even when the test container does have network access--is that code coverage on any paths talking to "real" DockerHub (which from what I understand is not running the real v2 registry yet).  Not sure how important that is.  But, if that's OK (which it may be--I just want us to consider it), then why would we keep a test called `PullImageFromCentralRegistry` when it becomes a duplicate of other pull tests already existing that pull from the local registry?

**Comment by jfrazelle** [comment] 2015-02-26 20:47
we could always run a v1 registry locally.....

**Comment by dmp42** [comment] 2015-03-07 02:03
@jfrazelle errrr, no we couldn't :)

**Closed** 2015-03-25 16:27 UTC
Labels: exp/beginner, kind/enhancement
