### ISSUE TITLE
Prompt of "docker attach" is not clear

### ISSUE THREAD

**Issue by cxxly** [docker/docker#18033] opened 2015-11-17 06:32 UTC
Using command of "docker attach" to attach a container will not output any successful prompt until pressing "Enter" key,  which firstly make me consider it getting stuck. 

    [root@localhost ~]# docker run -itd --name container1 busybox
    [root@localhost ~]# docker attach container1
    

It have not any output.
After I press "Enter"

    [root@localhost ~]# docker attach container1

    / # 

 I think it should give some prompt after exec docker attach command :)

**Comment by duglin** [comment] 2015-11-17 06:41
This is because you're attaching to the current input/output streams in their current state.  Meaning, the prompt has already been printed and "sh" is waiting for input, then you attach so you missed the prompt. Hitting enter then causes another prompt to be shown.  We can't show a prompt (or anything else) because that wouldn't be part of the output stream, nor do we know what should be shown - it could be a command line prompt, or something from some other executable.   I understand why it may be confusing but its important to realize that this isn't creating a new shell (sh) in the container, its attaching to the current one - which mean there's already some output that you've missed.

Going to close this since its working as designed.

**Closed by duglin** 2015-11-17 06:41 UTC

**Comment by cxxly** [comment] 2015-11-17 08:44
@duglin get it , thanks
