### ISSUE TITLE
link metadata removed when remove nested container whas restarted

### ISSUE THREAD

**Issue by tclavier** [docker/docker#13176] opened 2015-05-13 09:08 UTC
Description of problem:
When we remove a container, that remove this container from links in metadata of linked containers

`docker version`:
```
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): linux/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd073
OS/Arch (server): linux/amd64
```

`docker info`:
```
Containers: 46
Images: 988
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux stretch/sid
CPUs: 4
Total Memory: 7.673 GiB
Name: azae02
ID: F3W4:FHMW:WO7H:AUPJ:SOSS:ZDPB:74L5:FCWQ:6KLV:M34Q:MK6C:23YX
Username: tclavier
Registry: [https://index.docker.io/v1/]
```

`uname -a`:
    Linux azae02 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3 (2015-04-23) x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical, but it's true on all environments.

How reproducible:
Always 

Steps to Reproduce:
```
docker run -d --name db deliverous/blog
docker run -d --name front --link db:db deliverous/blog

docker inspect --format '{{.HostConfig.Links}}' front
[/db:/front/db]

docker stop db
docker inspect --format '{{.HostConfig.Links}}' front
[/db:/front/db]

docker rm db
docker inspect --format '{{.HostConfig.Links}}' front
<no value>

docker run -d --name db deliverous/blog
docker inspect --format '{{.HostConfig.Links}}' front
<no value>

sudo grep db /var/lib/docker/containers/b518f031659680e47410faf2b184ceb6eb8a1e201a5bfef1dcd1c4fe37264da2/hosts
172.17.0.113	db 84fa62a731fb

docker inspect --format {{.NetworkSettings.IPAddress}} db
172.17.0.115
```

Actual Results:
We have an incoherence : 
- docker inspect say they are no link name DB
- inside the container DB point on old IP 

Expected Results:
I don't know what it's the good results : 
- no link in metadata of front container and no entry in hosts file 
- or link in metadata of front container and good IP in hosts file

Additional info:

**Comment by tclavier** [comment] 2015-05-14 19:56
I rebuild my report with the template ... Hay Robot, that match for you ?

**Comment by thaJeztah** [comment] 2015-05-26 12:55
Heh, yes Gordon can be quite a PITA, sorry for that, but he can be helpful :smile: 

(Part of) this is expected behavior. Links in docker are not "dynamic" and are established between a specific *instance* of a container, and not based on the container *name*.

This means that, when the linked container is removed, the link is removed with it, and a new container created with the same name is not automatically linked. If you need to be able to "dynamically" establish links, using a discovery-service might be a better approach, but requires more work.

Libnetwork (https://github.com/docker/libnetwork) is currently being integrated into Docker and will add more options in the future (which will be introduced in "experimental builds" first). I'm not sure if this will include a discovery mechanism, but I will ask the libnetwork team.

This is largely a duplicate of this issue; https://github.com/docker/docker/issues/3155, the discussion on that issue may give some useful information as well.

What I *do* think should change, is that the entry for the linked container should be removed from `/etc/hosts` as soon as that container is removed. I seem to remember some changes were made in that area, but I'm not entirely sure.

@estesp I don't recall clearly; did you make changes so that entries were also *removed* from `/etc/hosts`?

**Comment by estesp** [comment] 2015-05-26 20:51
No--last change I know if there had to do with making the alias **and** name available in `/etc/hosts`,  but I agree that this appears to be a synchronization issue with the link behavior, and seems the least we could do is remove entries for containers which don't exist anymore.

**Comment by azurezk** [comment] 2015-07-28 12:59
Is this has been fixed?

**Comment by pydima** [comment] 2015-10-15 20:49
#dibs

**Comment by icecrime** [comment] 2016-09-10 02:10
I'm going to tentatively close this as links are going away in favor of top level networks and network attachments. Please let me know if you'd like to see it reopened.

**Closed by icecrime** 2016-09-10 02:10 UTC
Labels: exp/beginner, kind/enhancement, version/1.6
