### ISSUE TITLE
docker run --device does not preserve group

### ISSUE THREAD

**Issue by zoowar** [docker/docker#9058] opened 2014-11-10 01:06 UTC
The "docker run" command flag "device" does not preserve the localhost device group when copied into the docker container.

```
docker run --device=/dev/snd/timer:/dev/snd/timer -p 2222:22 -dt sound/example

# On my local system
[localhost]$ ls -l /dev/snd/timer
crw-rw----+ 1 root audio 116, 33 Oct 25 23:16 /dev/snd/timer

# Inside the docker instance
[user@2ecae939d223 ~]$ ls -l /dev/snd/timer
crw-rw----. 1 root root 116, 33 Nov 10 00:52 /dev/snd/timer
```

**Comment by jfrazelle** [comment] 2015-02-26 02:59
cannot reproduce on latest closing
```
$ ls -l /dev/snd/timer
crw-rw----+ 1 root audio 116, 33 Feb 25 09:34 /dev/snd/timer

jessie at debian in ~
$ docker run --rm -it --device /dev/snd/timer ubuntu:14.04 bash
root@cd8e23f8e72f:/# ls -l /dev/snd/timer
crw-rw---- 1 root audio 116, 33 Feb 26 03:02 /dev/snd/timer
root@cd8e23f8e72f:/# 

```

**Closed by jfrazelle** 2015-02-26 02:59 UTC

**Comment by beatkyo** [comment] 2018-02-16 13:59
This is happening again with docker 18.02

```
kyo@archibald ~ $ docker version
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.4
 Git commit:	fc4de447b5
 Built:	Tue Feb 13 15:28:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	fc4de447b5
  Built:	Tue Feb 13 15:28:34 2018
  OS/Arch:	linux/amd64
  Experimental:	false
kyo@archibald ~ $ ls -l /dev/snd/timer
crw-rw---- 1 root audio 116, 33 Feb 16  2018 /dev/snd/timer
kyo@archibald ~ $ docker run --rm -it --device /dev/snd/timer alpine
/ # ls -l /dev/snd/timer 
crw-rw----    1 root     root      116,  33 Feb 16 13:57 /dev/snd/timer
```
