### ISSUE TITLE
Docker does not expand variables in Docker file with quotes.

### ISSUE THREAD

**Issue by envygeeks** [docker/docker#15429] opened 2015-08-08 23:25 UTC
```dockerfile
FROM envygeeks/alpine
MAINTAINER Jordon Bedwell <jordon@envygeeks.io>
COPY copy/ /
ENV REPODEST /var/repo
RUN mkdir -p "$REPODEST" /home/builder
```

Fails... however, removing the quotes makes it succeed. Error output:

```
Sending build context to Docker daemon 18.59 MB
Sending build context to Docker daemon 
Step 0 : FROM envygeeks/alpine
 ---> e788f820ae9e
Step 1 : MAINTAINER Jordon Bedwell <>
 ---> Using cache
 ---> a339c47ee9a1
Step 2 : COPY copy/ /
 ---> Using cache
 ---> cdb4ba17ad06
Step 3 : ENV REPODEST /var/repo
 ---> Using cache
 ---> 7e0e1c83af78
Step 4 : RUN mkdir -p "$REPODEST" /home/builder
 ---> Running in 1f01f5b3b49d
mkdir: can't create directory '': No such file or directory
The command '/bin/sh -c mkdir -p "$REPODEST" /home/builder' returned a non-zero code: 1
```

Docker info

```
Containers: 5
Images: 68
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 78
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-45-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 6.941 GiB
Name: envygeeks
ID: XXG4:IO4W:B7LJ:LFWQ:KOA7:WHSR:OFHB:2CSK:PDPT:V2M3:RROP:WS7E
```

**Comment by duglin** [comment] 2015-08-09 00:06
What version of Docker are you using?  It appears to work for me using the latest.

**Comment by envygeeks** [comment] 2015-08-09 00:08
@duglin 

```
docker --version
Docker version 1.7.1, build 786b29d
```

**Comment by Pensu** [comment] 2015-08-10 06:49
@envygeeks I am using Docker 1.7.1 with aufs and it's working for me.

**Comment by thaJeztah** [comment] 2015-08-10 07:11
Unable to reproduce with this dockerfile;

```
FROM ubuntu:14.04
ENV REPODEST /var/repo
RUN mkdir -p "$REPODEST" /home/builder
```

Both `/var/repo/` and `/home/builder/` were succesfully created

**Comment by cpuguy83** [comment] 2015-08-10 14:53
Yes, this should be totally handled by the shell provided by `RUN`

**Comment by thaJeztah** [comment] 2015-08-10 15:49
@envygeeks I'm going to close this issue, because we are unable to reproduce. I did *not* try to repro with the `envygeeks/alpine` image, so it's possible there's something in that image that's causing this problem (I *did* try `alpine:edge`).

Are you able to reproduce this with a standard image (e.g. `ubuntu:14.04` or `alpine:edge`)?

**Closed** 2015-08-10 15:50 UTC
