### ISSUE TITLE
`docker service create` does not fetch image tags

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker#29582] opened 2016-12-20 08:45 UTC
**Description**

`docker service create` does not fetch image tags

**Steps to reproduce the issue:**

1. Create a swarm cluster. Only a single node is enough.
2. Do `docker service create nginx:latest` and make sure the image is pulled and the service is created.
3. Do `docker images | grep nginx`

**Describe the results you received:**

The image itself is pulled but the tag is not fetched.

```
nginx                  <none> ...
```

**Describe the results you expected:**

The tag should be fetched as well (as in `docker run`).

```
nginx                  latest ...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   2cf32ee
 Built:        Tue Dec 20 06:31:26 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   2cf32ee
 Built:        Tue Dec 20 06:31:26 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 152
Server Version: 1.14.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: dwbro2r4r28kjov8vkdpc0rw6
 Is Manager: true
 ClusterID: ob7adda1s0jgp13u8jgxq2mfv
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.146.0.2
 Manager Addresses:
  10.146.0.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: ws01
ID: SN3T:CNK6:JKQD:54CY:XKF2:BRX3:CIRU:DQBT:6DVZ:VWQ2:Q5ET:F23L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 36
 Goroutines: 130
 System Time: 2016-12-20T08:38:32.848334921Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2016-12-22 16:45
Oh! This is a duplicate of https://github.com/docker/docker/issues/28908. See that issue for background. I'll close this one 👍

**Closed by thaJeztah** 2016-12-22 16:45 UTC
Labels: area/swarm, kind/enhancement, version/master
