### ISSUE TITLE
Should docker daemon cleanup its unix socket?

### ISSUE THREAD

**Issue by shykes** [docker/docker#3349] opened 2013-12-26 06:44 UTC
The docker daemon doesn't cleanup its unix socket when it exits or is killed. On the one hand it seems logical to clean up behind yourself. On the other, there is no way to *reliably* cleanup, because the daemon might be sigkill-ed. So cleaning up only some of the time might be worse than never cleaning up, because it would allow clients to implement incorrect behavior that would work most of the time: the presence of a socket on the filesystem might be (incorrectly) interpreted as indicating the presence of a running daemon.

I'm filing this on behalf of a third-party project which criticized the behavior in their source but didn't file an issue (that I could find).

**Comment by cpuguy83** [comment] 2015-02-20 19:50
Closing since this was resolved in #6962

**Comment by tiborvass** [comment] 2015-02-23 22:09
@cpuguy83 there was a regression then. It does not cleanup its socket anymore.

**Comment by cpuguy83** [comment] 2015-02-24 00:29
@tiborvass hmm, you are right.

**Comment by jfrazelle** [comment] 2015-02-24 00:31
closing we have a new one https://github.com/docker/docker/issues/10969 sorry for the confusion @cpuguy83

**Closed by jfrazelle** 2015-02-24 00:31 UTC
Labels: /core/runtime
