### ISSUE TITLE
Can't cd into directory even though it has a+rx permissions?

### ISSUE THREAD

**Issue by marius311** [docker/docker#14651] opened 2015-07-15 09:05 UTC
If a directory has a+rx permissions, any user should be able to cd into it, right? 

Easy to reproduce this not being the case inside Docker:

```
docker run -it ubuntu /bin/bash
$ chmod 755 /root
$ useradd test
$ su test
$ ls -lhd /root     
drwxr-xr-x 2 root root 4.0K Jun 15 18:32 /root
$ cd /root
sh: 1: cd: can't cd to /root
```

Replace ubuntu with e.g. debian or busybox above, same result. Attempt to do this on my host (Ubuntu), works fine as expected. Is this a Docker issue or something else?

**Comment by marius311** [comment] 2015-07-15 09:11
```
docker version:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

```
docker info:
Containers: 27
Images: 368
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 422
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.507 GiB
Name: martop
ID: C2XU:CDAF:KKCB:AI62:LWL2:O7YS:OYBD:MZ4C:I6XQ:TU5M:RINM:SAUK
Username: marius311
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

```
uname -a:
Linux martop 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by unclejack** [comment] 2015-07-15 09:55
@marius311 This is caused by the problems aufs has with permissions. https://github.com/docker/docker/pull/11799 fixed this by adding dirperm1 to the mount options when the kernel has been patched with a version of aufs with dirperm1 support.

I can confirm that this isn't a problem on other storage backends.

I'm going to close this issue now as it's been fixed through a PR, but the fix still relies on having the kernel sources patched with dirperm1 enabled aufs patches.

**Closed by unclejack** 2015-07-15 09:55 UTC

**Comment by marius311** [comment] 2015-07-15 10:14
I see, thanks. 

Also fyi, removing and remaking the `/root` directory was a workaround for me.
