### ISSUE TITLE
CentOS 7.1 won't run ubuntu containers with overlayfs

### ISSUE THREAD

**Issue by vbtnickn** [docker/docker#15668] opened 2015-08-18 18:44 UTC
Couldn't find this issue filed elsewhere, could be related to [10294](https://github.com/docker/docker/issues/10294), but it doesn't seem to have anything to do with XFS.

When running docker 1.8 on CentOS 7.1 with the overlay storage driver, it won't start any ubuntu containers.  This is always the output:

 Error response from daemon: mkdir /var/lib/docker/overlay/935550f5b524ff8835c5a6c1512cd1d5cf4a43125fd6da9c50361ce888908dd1-init/merged/dev/shm: invalid argument

Tried ubuntu:14.04 and phusion/baseimage which is based on that, both have the same error.  CentOS 6 and 7 containers seem to run fine.  I tried with both an ext4 and an xfs filesystem, and they both have the same error.

Docker info:

    docker version
    Client:
     Version:      1.8.1
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   d12ea79
     Built:        Thu Aug 13 02:19:43 UTC 2015
     OS/Arch:      linux/amd64
     
    Server:
     Version:      1.8.1
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   d12ea79
     Built:        Thu Aug 13 02:19:43 UTC 2015
     OS/Arch:      linux/amd64
    
    docker info
    Containers: 4
    Images: 17
    Storage Driver: overlay
     Backing Filesystem: xfs
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.10.0-229.7.2.el7.x86_64
    Operating System: CentOS Linux 7 (Core)
    CPUs: 4
    Total Memory: 15.52 GiB
    Name: vcp-centos7
    ID: F5GZ:V72D:2KI6:3HXS:SAGQ:VFYV:SLYQ:IDGE:LEBE:XOP7:DCGC:ZJQF

**Comment by tonistiigi** [comment] 2015-08-19 20:52
Overlay seems broken in `CentOS 7.1`. Same error in `docker 1.7.1` as well.

Simple reproducer:

```
mkdir lower upper work merged
mount -t overlay overlay -olowerdir=lower,upperdir=upper,workdir=work merged
touch lower/foo
rm merged/foo
mkdir merged/foo <- Invalid argument
```

**Comment by tonistiigi** [comment] 2015-08-19 20:57
I see no differences from #10294, I think we can close this.

**Comment by thaJeztah** [comment] 2015-08-19 21:00
Agreed. I'm going to close this issue as it is a duplicate of https://github.com/docker/docker/issues/10294. @vbtnickn you can subscribe to that issue (using the subscribe button), to get notified of changes there

**Closed by thaJeztah** 2015-08-19 21:00 UTC

**Comment by vbtnickn** [comment] 2015-08-19 22:12
I have subscribed to the other issue.  The only reason I had filed this one is that 10294 seemed to be about overlay not working with xfs.  But it doesn't seem to be about xfs at all.  Overlay does work in some situations, but not others.  Like I said, I can run and remove CentOS containers on CentOS with overlay just fine.

**Comment by kervinpierre** [comment] 2015-08-25 21:48
I am seeing this on Ext4 as well.  So it seems as if 10294 should be merged into here, instead of the other way around.

**Comment by slayercat** [comment] 2015-12-03 10:36
https://bugzilla.kernel.org/show_bug.cgi?id=108811
