### ISSUE TITLE
 Error getting container from driver devicemapper.

### ISSUE THREAD

**Issue by kalesastha** [docker/docker#14523] opened 2015-07-10 09:07 UTC
We had restarted the docker service in centos 6.4 due to docker command haged. Before that we stopped all the running containers . After restarting the docker service , i just start the stopped container , but i won't start throws an below error .

sudo docker start 3ae0a3c3a6b2
Error response from daemon: Cannot start container 3ae0a3c3a6b2: Error getting container 3ae0a3c3a6b275e9635fbb278e65c7a412ecaac3b51413359d66ada02d607a8d from driver devicemapper: Error mounting '/dev/mapper/docker-8:2-7471603-3ae0a3c3a6b275e9635fbb278e65c7a412ecaac3b51413359d66ada02d607a8d' on '/var/lib/docker/devicemapper/mnt/3ae0a3c3a6b275e9635fbb278e65c7a412ecaac3b51413359d66ada02d607a8d': device or resource busy
2015/07/10 14:13:25 Error: failed to start one or more containers

My docker version :-

sudo docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.2
Git commit (client): d84a070/1.1.2
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.2
Git commit (server): d84a070/1.1.2

My docker info :-

sudo docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.2
Git commit (client): d84a070/1.1.2
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.2
Git commit (server): d84a070/1.1.2
[build@integ-ci-1 ~]$ sudo docker info
Containers: 689
Images: 524
Storage Driver: devicemapper
 Pool Name: docker-8:2-7471603-pool
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 71155.8 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 124.7 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: lxc-1.0.5
Kernel Version: 2.6.32-431.29.2.el6.x86_64

uname -a 

Linux build 2.6.32-431.29.2.el6.x86_64 #1 SMP Tue Sep 9 21:36:05 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Any Idea .???

**Comment by vbatts** [comment] 2015-07-10 13:12
Closing as a duplicate of #5684 
See this comment for troubleshooting tips https://github.com/docker/docker/issues/5684#issuecomment-120047852

**Closed by vbatts** 2015-07-10 13:12 UTC
