### ISSUE TITLE
Erroneous output from 'docker rm *' command

### ISSUE THREAD

**Issue by zerofoxtrots** [docker/docker#32241] opened 2017-03-30 22:14 UTC
**Description**

When attempting to remove all existing containers using the "docker rm *" command, erroneous output is listed as if the application were trying to remove system files and directories.

**Steps to reproduce the issue:**
1. Create 1 or more containers.
2. Attempt to remove all containers with wildcard (*).

**Describe the results you received:**
```
# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                       PORTS               NAMES
bf0fe0373c51        jpetazzo/clock      "/bin/sh -c 'while..."   2 minutes ago       Exited (0) 2 minutes ago                         musing_dubinsky
d0741735d025        ubuntu              "bash"                   3 minutes ago       Exited (130) 3 minutes ago                       quizzical_ardinghelli
aaa856a215d8        hello-world         "/hello"                 8 minutes ago       Exited (0) 8 minutes ago                         determined_beaver
# docker rm *
Error response from daemon: No such container: Desktop
Error response from daemon: No such container: Documents
Error response from daemon: No such container: Downloads
Error response from daemon: No such container: Music
Error response from daemon: No such container: Pictures
Error response from daemon: No such container: Public
Error response from daemon: No such container: Templates
Error response from daemon: No such container: Videos
# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS               NAMES
bf0fe0373c51        jpetazzo/clock      "/bin/sh -c 'while..."   24 minutes ago      Exited (0) 24 minutes ago                         musing_dubinsky
d0741735d025        ubuntu              "bash"                   26 minutes ago      Exited (130) 25 minutes ago                       quizzical_ardinghelli
aaa856a215d8        hello-world         "/hello"                 30 minutes ago      Exited (0) 30 minutes ago                         determined_beaver

```

**Describe the results you expected:**
I would expect to see either the help menu as if this were an invalid command, or preferably have the application remove all containers then display a list of removed container ID's, which would be consistent with the behavior of the application when removing a single container.

**Additional information you deem important (e.g. issue happens only occasionally):**
When attempting to remove a single container instance with the docker rm command, an id of the removed container is listed. If a wildcard is allowed, it should behave in a consistent way. If it is not, the system should output the help text of the docker rm command.

**Output of `docker version`:**
`Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
`

**Output of `docker info`:**
`# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@docker-VirtualBox:~# ^C
root@docker-VirtualBox:~# ^C
root@docker-VirtualBox:~# ^C
root@docker-VirtualBox:~# docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 5
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 19
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.6 MiB
Name: docker-VirtualBox
ID: EGBQ:KZP5:6RBU:4D4Y:OHOH:IJW5:M4CK:LSIC:BAAN:RIPL:RZNE:MCMU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
`

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Guest OS Information: 
Linux docker-VirtualBox 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Oracle VirtualBox Information:
Version 5.1.18 r114002 (Qt5.6.2)

**Comment by thaJeztah** [comment] 2017-03-30 22:20
`docker rm` does not use wildcards; to remove all containers, either combine commands, e.g.

```bash
docker rm $(docker ps -aq)
```

or to remove all stopped containers, use;

```bash
docker container prune
```


What you're seeing is the _shell_ expanding `*`, which returns all directories and files in your working directory (in your case, your home directory); as a result, you're running this as a command;

```bash
docker rm Desktop Documents Downloads Music Pictures Public Templates Videos
```

This is not a bug, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2017-03-30 22:20 UTC
Labels: version/17.03
