### ISSUE TITLE
dockerfile instruction for running script from temporary location

### ISSUE THREAD

**Issue by accursoft** [docker/docker#18332] opened 2015-12-01 11:46 UTC
My Dockerfile runs several temporary scripts in the container, and thus looks like:
```
COPY script1 /tmp/
RUN /tmp/script1

COPY script2 /tmp/
RUN /tmp/script2

COPY script3 /tmp/
RUN /tmp/script3

COPY script4 /tmp/
RUN /tmp/script4

COPY script5 /tmp/
RUN /tmp/script5

RUN rm /tmp/script*
```
I would like a single instruction which copies a script into the container, executes it, then removes it in a single layer. This would have a number of advantages:

 - Cleaner dockerfiles
 - Cleaner `docker history`
 - Faster builds, as committing layers is expensive on some platforms

**Comment by phemmer** [comment] 2015-12-01 13:00
See #332 & #6906

**Comment by thaJeztah** [comment] 2015-12-01 15:35
Yes, this looks like a duplicate of those (and some others), however, there's currently a "freeze" on the Dockerfile syntax, because the "builder" will moved out of the daemon and moved client side. After that has been done, we can look into improvements in this area. See https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

I'm going to close this issue, because we cannot currently accept changes to the Dockerfile. Thanks for suggesting though!

**Closed by thaJeztah** 2015-12-01 15:35 UTC

**Comment by accursoft** [comment] 2015-12-01 15:47
#332 & #6906 might fix 2., but they'll make 1. and probably 3. worse. They're addressing different problems.

**Comment by thaJeztah** [comment] 2015-12-01 16:35
This looks like a more similar issue; https://github.com/docker/docker/issues/18184
