### ISSUE TITLE
execute docker-compose to set up containers in swarm mode: xxx uses an undefined network xxx

### ISSUE THREAD

**Issue by lorenzvth7** [docker/docker#27159] opened 2016-10-05 13:58 UTC
I try to deploy 2 containers with docker-compose on 2 swarm hosts

Can't find overlay network:

```
$ docker-compose up --build -d
ERROR: Service "jenkins-slave" uses an undefined network "jenkins_swarm"
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
c91bc26a3551        bridge              bridge              local
8472d6b1e948        docker_gwbridge     bridge              local
0c7217ae7f07        host                host                local
6g02319eja24        jenkins_swarm             overlay             swarm
030452ac3918        none                null                local

```

**Describe the results you received:**
Network is not found

**Describe the results you expected:**
Network is found

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-33642596-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.691 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.21 GB
 Metadata Space Used: 3.24 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: 8bq62u6t1bswt5wihpd7xckju
 Is Manager: true
 ClusterID: dvua53e9uxml9gr3ie3wi12f0
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 137.74.33.194
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.3 MiB
Name: evolaneciserver
ID: A3IS:XAGE:XQI6:KLAJ:HZMM:3KDC:FTAT:3WBB:6MRZ:CDIF:EWWK:DQKB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2016-10-31 17:00
This is currently expected; docker compose does not support swarm mode, and trying to attach a container to a Swarm scoped / managed (see the `scope` column) therefore doesn't work.

We're working on improvements in this area for docker 1.13, so stay tuned.

I'll close this issue because this is currently the expected behavior, and we're tracking this functionality through other issues

**Closed by thaJeztah** 2016-10-31 17:00 UTC
Labels: version/1.12
