### ISSUE TITLE
No available IPv4 addresses on this network's address pools: bridge

### ISSUE THREAD

**Issue by Soulou** [docker/docker#18527] opened 2015-12-09 09:08 UTC
Hi there, one of my production host encountered the following error when starting a new container (creation when well, POST /start request failed):

```
no available IPv4 addresses on this network's address pools: bridge 
```

The bridge network is the default one giving IPs on 172.17.0.0/16

There are not so many containers on the host (70, see docker info output below) So I suppose there are plenty of available addresses.

In the complete log I've a warning about umount ipc, but I suppose it's related to the cleaning of the container start after the IP allocation error.

What could be the source of that? Thank you very much.

Complete error log
```
time="2015-12-09T05:11:25.189277559+01:00" level=info msg="POST /v1.12/containers/8071fd471587152b90353bcdcc182d5609094123c1c1bc48c8ec0c68617b0a7a/start
time="2015-12-09T05:11:25.190917242+01:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/8071fd471587152b90353bcdcc182d5609094123c1c1bc48c8ec0c68617b0a7a/shm: no such file or directory\nfailed to umount /var/lib/docker/containers/8071fd471587152b90353bcdcc182d5609094123c1c1bc48c8ec0c68617b0a7a/mqueue: no such file or directory"
time="2015-12-09T05:11:25.191040536+01:00" level=error msg="Handler for POST /v1.12/containers/8071fd471587152b90353bcdcc182d5609094123c1c1bc48c8ec0c68617b0a7a/start returned error: Cannot start container 8071fd471587152b90353bcdcc182d5609094123c1c1bc48c8ec0c68617b0a7a: no available IPv4 addresses on this network's address pools: bridge (1a238bd06bf71115861570f9a62ae5d047334adc12899f0810d31109836071cd)"
time="2015-12-09T05:11:25.191097543+01:00" level=error msg="HTTP Error" err="Cannot start container 8071fd471587152b90353bcdcc182d5609094123c1c1bc48c8ec0c68617b0a7a: no available IPv4 addresses on this network's address pools: bridge (1a238bd06bf71115861570f9a62ae5d047334adc12899f0810d31109836071cd)" statusCode=500
```

docker version
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

docker info
```
Containers: 70
Images: 254
Server Version: 1.9.1
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-21-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 6
Total Memory: 31.42 GiB
Name: <hostname>
ID: 5GQY:KHCJ:3Z7I:EFGX:YAI5:IA4B:56FT:RXFD:WWSM:F7XV:WVKG:2J6D
```

**Comment by Soulou** [comment] 2015-12-09 11:01
```
    {
        "Name": "bridge",
        "Id": "1a238bd06bf71115861570f9a62ae5d047334adc12899f0810d31109836071cd",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Config": [
                {
                    "Subnet": "172.17.42.1/16",
                    "Gateway": "172.17.42.1"
                }
            ]
        },
```

More information about current network

**Comment by Soulou** [comment] 2015-12-09 11:12
List of allocated IP according to `docker network inspect bridge`

```
"IPv4Address": "172.17.0.1/16"
"IPv4Address": "172.17.0.2/16"
"IPv4Address": "172.17.0.3/16"
"IPv4Address": "172.17.0.4/16"
"IPv4Address": "172.17.0.5/16"
"IPv4Address": "172.17.0.6/16"
"IPv4Address": "172.17.0.7/16"
"IPv4Address": "172.17.0.8/16"
"IPv4Address": "172.17.0.9/16"
"IPv4Address": "172.17.0.10/16"
"IPv4Address": "172.17.0.11/16"
"IPv4Address": "172.17.0.12/16"
"IPv4Address": "172.17.0.13/16"
"IPv4Address": "172.17.0.14/16"
"IPv4Address": "172.17.0.15/16"
"IPv4Address": "172.17.0.16/16"
"IPv4Address": "172.17.0.17/16"
"IPv4Address": "172.17.0.18/16"
"IPv4Address": "172.17.0.19/16"
"IPv4Address": "172.17.0.20/16"
"IPv4Address": "172.17.0.21/16"
"IPv4Address": "172.17.0.22/16"
"IPv4Address": "172.17.0.23/16"
"IPv4Address": "172.17.0.24/16"
"IPv4Address": "172.17.0.25/16"
"IPv4Address": "172.17.0.26/16"
"IPv4Address": "172.17.0.27/16"
"IPv4Address": "172.17.0.28/16"
"IPv4Address": "172.17.0.29/16"
"IPv4Address": "172.17.0.30/16"
"IPv4Address": "172.17.0.31/16"
"IPv4Address": "172.17.0.32/16"
"IPv4Address": "172.17.0.33/16"
"IPv4Address": "172.17.0.34/16"
"IPv4Address": "172.17.0.35/16"
"IPv4Address": "172.17.0.36/16"
"IPv4Address": "172.17.0.37/16"
"IPv4Address": "172.17.0.38/16"
"IPv4Address": "172.17.0.39/16"
"IPv4Address": "172.17.0.40/16"
"IPv4Address": "172.17.0.41/16"
"IPv4Address": "172.17.0.42/16"
"IPv4Address": "172.17.0.43/16"
"IPv4Address": "172.17.0.44/16"
"IPv4Address": "172.17.0.45/16"
"IPv4Address": "172.17.0.46/16"
"IPv4Address": "172.17.0.47/16"
"IPv4Address": "172.17.0.48/16"
"IPv4Address": "172.17.0.49/16"
"IPv4Address": "172.17.0.50/16"
"IPv4Address": "172.17.0.51/16"
"IPv4Address": "172.17.0.52/16"
"IPv4Address": "172.17.0.53/16"
"IPv4Address": "172.17.0.54/16"
"IPv4Address": "172.17.0.55/16"
"IPv4Address": "172.17.0.56/16"
"IPv4Address": "172.17.0.57/16"
"IPv4Address": "172.17.0.58/16"
"IPv4Address": "172.17.0.59/16"
"IPv4Address": "172.17.0.60/16"
"IPv4Address": "172.17.0.61/16"
"IPv4Address": "172.17.0.62/16"
"IPv4Address": "172.17.0.63/16"
"IPv4Address": "172.17.0.64/16"
"IPv4Address": "172.17.0.65/16"
"IPv4Address": "172.17.0.66/16"
"IPv4Address": "172.17.0.67/16"
"IPv4Address": "172.17.0.68/16"
"IPv4Address": "172.17.0.69/16"
"IPv4Address": "172.17.0.70/16"
"IPv4Address": "172.17.0.71/16"
"IPv4Address": "172.17.0.72/16"
"IPv4Address": "172.17.0.73/16"
"IPv4Address": "172.17.0.75/16"
"IPv4Address": "172.17.0.77/16"
"IPv4Address": "172.17.0.80/16"
"IPv4Address": "172.17.0.81/16"
"IPv4Address": "172.17.0.82/16"
"IPv4Address": "172.17.0.83/16"
```

Definitely not all of them

**Comment by thaJeztah** [comment] 2015-12-09 11:59
Are you using docker-in-docker or running more than one daemon? If you do, this may be a duplicate of https://github.com/docker/docker/issues/17939

**Comment by Soulou** [comment] 2015-12-09 13:04
No I'm not doing that, I've seens the issue, but have not detected any similarity

**Comment by thaJeztah** [comment] 2015-12-09 13:07
ping @aboch (sorry I'm kinda loosing track which network issues are still being tracked) :smile:

**Comment by aboch** [comment] 2015-12-09 18:38
@Soulou 
If your system is still in this state, can you please post the o/p of:
strings /var/lib/docker/network/files/local-kv.db

**Comment by Soulou** [comment] 2015-12-09 18:49
The system is not in the state but I can reproduce it super easyly @aboch output is coming.

**Comment by Soulou** [comment] 2015-12-09 19:04
[output.txt](https://github.com/docker/docker/files/57223/output.txt)

Output is attached to the post

**Comment by feisuzhu** [comment] 2015-12-14 10:46
@Soulou 
same issue, mark here
can you provide the way to reproduce?

**Comment by thaJeztah** [comment] 2015-12-14 12:00
ping @aboch did you have time to look at the output @Soulou provided? https://github.com/docker/docker/issues/18527#issuecomment-163358987

**Comment by Soulou** [comment] 2015-12-14 13:22
@feisuzhu No way to reproduce on another host. The host which has this problem is still running and I can reproduce it. (I just have to run a few more containers until hitting this *weird* limit

**Comment by mavenugo** [comment] 2015-12-14 17:01
@aboch do you think this is also related to #18145 ?

**Comment by aboch** [comment] 2015-12-14 17:25
@mavenugo 
I don't think so. I think this is more related to the local store file getting somehow messed up, but I was not able to confirm either of the twos, @Soulou's file has quite a number of configurations.

What I can tell is that it is not the same issue hit in https://github.com/docker/docker/issues/18113#issuecomment-161765181

@Soulou In order to debug more deeper what is going on, would it be ok for you to send me (privately) your full `/var/docker/network/files/local-kv.db` file so that I can analyze it with some instrumented code ?

**Comment by Soulou** [comment] 2015-12-15 09:38
@aboch no problem, please send me an email at leo [ at ] scalingo [ dot ] com, I'll send you the file back.

I suppose it's related to some kind of corruptions of the allocator, a bit the opposite of https://github.com/docker/docker/issues/18535, IPs are considered taken but are not or something like this.

**Comment by psviderski** [comment] 2015-12-23 21:41
I have the same issue on my production server that has occurred twice already. The number of running containers was 216 and it wasn't possible to start a new one. I was able to remove some of running containers and the issue gone.
When the system was in a stuck state I made a copy of `/var/lib/docker/network/files/local-kv.db` file which I can share if that helps fix the issue.

**Comment by aboch** [comment] 2015-12-23 22:06
@psviderski 
Please send me the copy of the file at aboch [at] docker.com

@Soulou 
Your mail server has been blocking my email.

**Comment by psviderski** [comment] 2015-12-23 23:01
@aboch I've just sent you a letter with the db file. Please let me know if I need to provide something else that probably can help you.

**Comment by Soulou** [comment] 2015-12-24 12:18
@aboch I had to reset the node (as it was one of our production servers) and I forgot to backup the db file :-( If the situation appears again, I'll send it to you directly!

**Comment by beetree** [comment] 2016-01-02 18:30
I believe I'm having the same issue:

Command:
```
# docker start d25760b692490b43ba0925ee472bb74a6fa39a0330d06b41e3e09c7ed959e723
Error response from daemon: Cannot start container d25760b692490b43ba0925ee472bb74a6fa39a0330d06b41e3e09c7ed959e723: no available IPv4 addresses on this network's address pools: bridge (562b4a92aede2ec01b0797fdf20ebca7121cd1695000de11b47cbfa7108bc062)
Error: failed to start containers: [d25760b692490b43ba0925ee472bb74a6fa39a0330d06b41e3e09c7ed959e723]
```

Docker log:
```
Jan 02 19:26:33 Ubuntu-1510-wily-64-minimal docker[3999]: time="2016-01-02T19:26:33.965622536+01:00" level=info msg="POST /v1.21/containers/d25760b692490b43ba0925ee472bb74a6fa39a0330d06b41e3e09c7ed959e723/start"
Jan 02 19:26:33 Ubuntu-1510-wily-64-minimal docker[3999]: time="2016-01-02T19:26:33.974207730+01:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/d25760b692490b43ba0925ee472bb74a6fa39a0330d06b41e3e09c7ed959e723/shm: no such file or directory\nfailed to umount /var/lib/docker/containers/d25760b692490b43ba0925ee472bb74a6fa39a0330d06b41e3e09c7ed959e723/mqueue: no such file or directory"
Jan 02 19:26:34 Ubuntu-1510-wily-64-minimal docker[3999]: time="2016-01-02T19:26:34.005211348+01:00" level=error msg="Handler for POST /v1.21/containers/d25760b692490b43ba0925ee472bb74a6fa39a0330d06b41e3e09c7ed959e723/start returned error: Cannot start container d25760b692490b43ba0925ee472bb74a6fa39a0330d06b41e3e09c7ed959e723: no available IPv4 addresses on this network's address pools: bridge (562b4a92aede2ec01b0797fdf20ebca7121cd1695000de11b47cbfa7108bc062)"
Jan 02 19:26:34 Ubuntu-1510-wily-64-minimal docker[3999]: time="2016-01-02T19:26:34.005272128+01:00" level=error msg="HTTP Error" err="Cannot start container d25760b692490b43ba0925ee472bb74a6fa39a0330d06b41e3e09c7ed959e723: no available IPv4 addresses on this network's address pools: bridge (562b4a92aede2ec01b0797fdf20ebca7121cd1695000de11b47cbfa7108bc062)" statusCode=500
Jan 02 19:26:47 Ubuntu-1510-wily-64-minimal docker[3999]: time="2016-01-02T19:26:47.632223089+01:00" level=info msg="POST /v1.21/containers/9e53cf34454b562883f814826cc5d826f3bb18f6889ca650305414728cab9c6a/exec"
Jan 02 19:26:47 Ubuntu-1510-wily-64-minimal docker[3999]: time="2016-01-02T19:26:47.632635812+01:00" level=info msg="POST /v1.21/exec/674132a729976e13a86d58df839e7b07735605bf03f563042c8caacb1af8e74e/start"
Jan 02 19:26:47 Ubuntu-1510-wily-64-minimal docker[3999]: time="2016-01-02T19:26:47.675101492+01:00" level=info msg="GET /v1.21/exec/674132a729976e13a86d58df839e7b07735605bf03f563042c8caacb1af8e74e/json"
```

System info:
```
# docker info
Containers: 134
Images: 186
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 454
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-21-generic
Operating System: Ubuntu 15.10
CPUs: 12
Total Memory: 125.9 GiB
Name: Ubuntu-1510-wily-64-minimal
ID: 4ZRV:LJBE:5ACK:TH4J:5LQW:OELG:JP27:AGRH:R22R:H6HX:UNR3:T46C
WARNING: No swap limit support

# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

# uname -a
Linux Ubuntu-1510-wily-64-minimal 4.2.0-21-generic #25-Ubuntu SMP Wed Dec 2 18:42:25 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

@aboch I'll send you the full local-kv.db on your email.

**Comment by Soulou** [comment] 2016-01-03 11:44
@beetree if it's the same issue as me, the issue will appear again at 250 containers, it was highly reproducible until I've restarted the docker daemon.

**Comment by aboch** [comment] 2016-01-03 14:48
Thanks @beetree for the file. 
Had some time to decode the inner bitsequence structure from it. I can confirm it is corrupted with similar pattern that also caused #18535 (See https://github.com/docker/docker/issues/18535#issuecomment-164494430).

Bug will not always occur,only some address release/re-allocate patterns will expose the issue.

As you found, you may be able to keep it working decreasing the number of containers. But unfortunately you will hit it again on some n-th container creation, as @Soulou already mentioned.
 
This is now fixed in master.

**Comment by Soulou** [comment] 2016-01-03 18:08
Great, can be close then? :)

**Comment by thaJeztah** [comment] 2016-01-03 18:35
I'll close this issue, as it should be resolved on master, and will be in 1.10, but feel free to comment if you're still able to reproduce this on the current master, or in the 1.10 release

**Closed by thaJeztah** 2016-01-03 18:35 UTC
Labels: group/networking, kind/bug

**Comment by aboch** [comment] 2016-01-03 18:57
@Soulou @psviderski 
With the instrumented code I checked your files as well. Thanks for sending them.
Same corruption pattern as in @beetree's case.
Thanks @thaJeztah for closing the issue.

**Comment by beetree** [comment] 2016-01-04 01:38
Thanks @aboch and @thaJeztah for helping us out with this. Knowing that this gets fixed in 1.10 gives a lot of comfort. Keep the improvements coming...!

**Comment by psviderski** [comment] 2016-01-08 05:27
@aboch @thaJeztah: Thanks! :+1:

**Comment by beetree** [comment] 2016-01-16 17:22
Restarting the daemon solves this, but restarting the daemon can result in the error `Error starting daemon: Error initializing network controller: could not delete the default bridge network`. If this happens, just delete /var/lib/docker/network. See this issue for more info: https://github.com/docker/docker/issues/17083

**Comment by beetree** [comment] 2016-01-18 22:22
@aboch @thaJeztah I don't see any mentioning of this having been fixed in https://github.com/docker/docker/releases/tag/v1.10.0-rc1 Are you sure it is in?

**Comment by mavenugo** [comment] 2016-01-18 22:31
@beetree yes. this is resolved.
I think the changelog is used to communicate important features and enhancements. 
Being a bug fix, this would have been left out of changelog.

**Comment by thaJeztah** [comment] 2016-01-18 23:00
@mavenugo perhaps we can add a mention of "stability improvements to ....", open to suggestions if you have them

**Comment by jtangelder** [comment] 2016-03-09 15:09
I had the same issue, with only 10 machines running. Fixed it by removing the network and creating it again.

**Comment by wsw70** [comment] 2016-03-22 15:14
@jtangelder how exactly did you "remove the network and created it again"? (I have the same issue)

**Comment by jtangelder** [comment] 2016-03-24 17:09
Something with `docker machine network remove `. Not behind my machine at the moment...

**Comment by AndrewGuenther** [comment] 2016-04-11 17:09
@aboch Could you point me to the commit in libnetwork which fixed this?

**Comment by aboch** [comment] 2016-04-11 18:20
@AndrewGuenther https://github.com/docker/libnetwork/pull/771
