### ISSUE TITLE
Can't fetch IP of container on RC3

### ISSUE THREAD

**Issue by tomdee** [docker/docker#17494] opened 2015-10-29 17:49 UTC
```
docker inspect --format '{{ .NetworkSettings.IPAddress }}' workload1' 
Template parsing error: template: :1:19: executing "" at <.NetworkSettings.IPA...>: IPAddress is not a field of struct type *types.NetworkSettings
```

```
 "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "be0dc9c1631d5024164dfab1adb339708efffa141cd71161195f616ae1176d18",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/be0dc9c1631d",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "Networks": {
            "calnet": {
                "EndpointID": "266aa806f0138f29960982702694c61c11b17563d3a03b9bd8e73ef94b265d04",
                "Gateway": "\u003cnil\u003e",
                "IPAddress": "10.0.0.2",
                "IPPrefixLen": 24,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": ""
            }
        }
    }
```

```
$ docker version
Client:
 Version:      1.9.0-rc3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2100b94
 Built:        Wed Oct 28 01:32:55 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2100b94
 Built:        Wed Oct 28 01:32:55 UTC 2015
 OS/Arch:      linux/amd64

$ uname -a
Linux gulfstream 3.19.0-31-generic #36-Ubuntu SMP Wed Oct 7 15:04:02 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ docker info
Containers: 4
Images: 50
Server Version: 1.9.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 58
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-31-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 3.86 GiB
Name: gulfstream
ID: DMI2:W6NH:AFHI:6YWS:PEND:LXD7:3GDL:YK62:4437:EATW:DW2R:AF6X
Debug mode (server): true
 File Descriptors: 38
 Goroutines: 78
 System Time: 2015-10-28T14:41:37.005300886-07:00
 EventsListeners: 0
 Init SHA1: 5e8a6db3eec2807593ebd7797fb153c6b3c331ef
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
Username: tomdee
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: etcd://127.0.0.1:2379

```

**Comment by cpuguy83** [comment] 2015-10-30 00:06
It's correct that you don't get the IPAddress in NetworkSettings's root anymore, unless you use an earlier API version.

What's a bit off is the error that is thrown.

**Comment by cpuguy83** [comment] 2015-10-30 00:07
Actually looking at it, I think the error is correct to.

**Comment by cpuguy83** [comment] 2015-10-30 00:09
@tomdee Can you explain what the issue is?
The IPAddress is in the "Networks" -> <network name>

**Comment by calavera** [comment] 2015-10-30 00:16
The error is correct. IPAdress doesn't leave in the main `NetworkSettings` struct anymore because there can be more than 1 addresses attached to the container.

You can get the old struct if you send requests to the previous version of the api, inserting `/v1.20` at the beginning of the request path. If you want to get the IP in the new api you have to know the name of the network you want to check, `calnet` in your example and do some golang template incantation:

```
{{ (index .NetworkSettings "calnet").IPAddress }}
```

PS: That's probably not the right template, because I never remember the right syntax, sorry.

**Comment by calavera** [comment] 2015-10-30 00:20
To clarify, because I know this is confusing as hell, this functionality was removed between RC2 and RC3. We weren't displaying all the networks a container was connected, but only the last one it was attached too. This was consider a bug because it's very inconsistent, you only were getting the right address because the last network was attached to was calico's. But that behavior was very fragile.

Unfortunately, the right solution is to display all the networks and let you navigate the one you want, and that's what we did. If you use an old api you won't get the right network either, because there was not networking before 1.9. You'll get the container's default driver, `bridge` in 1.8.

**Comment by calavera** [comment] 2015-10-30 00:22
@tomdee do you mind closing this issue? I know this cannot sound like the solution you expected, but it's not a bug.

**Comment by bmangold** [comment] 2015-10-30 00:47
Probably most people want this:
`docker inspect --format '{{.NetworkSettings.Networks.bridge.IPAddress}}' container_name`

Note: this assumes you are running bridge and have one network (simple defaults).  Please be aware of @calavera has said.

**Comment by thaJeztah** [comment] 2015-10-30 01:02
@calavera @tiborvass I probably won't make myself popular suggesting, but should we keep the "old" top-level information around for the 1.9 release (if a container is using "bridge")? I suspect this is going to trip a lot of people. I.e., if a container uses the bridge network, have the information in both places; as a top level, and inside the "networks" list. idk, just thinking out loud here. We can then remove it in the next release.

**Comment by bmangold** [comment] 2015-10-30 01:12
[+1](https://github.com/search?q=.NetworkSettings.IPAddress&type=Code&utf8=%E2%9C%93)

**Comment by tiborvass** [comment] 2015-10-30 01:15
@thaJeztah no, sorry but it doesn't make sense. What we should do is document better the API change in the changelog, and possibly in the api docs too. I'm closing this.

**Comment by rade** [comment] 2015-10-30 15:11
@tiborvass Please reconsider. IMO @thaJeztah's suggestion is a reasonable compromise in the interest of compatibility.

I reckon this change will break tons of tools and applications. Most code I've seen that interacts with docker either uses the docker CLI (and hence will break with the new version) or uses the API at the version supplied by the remote (and hence will break too). The latter behaviour is codified in popular Docker API clients, like [go-dockerclient](https://github.com/fsouza/go-dockerclient), where it is the default.

**Comment by cpuguy83** [comment] 2015-10-30 15:23
@rade While I tend to agree with making upgrades as easy as possible, people using the API version supplied by the remote is just absolutely the wrong thing to do and breaks the purpose of API versioning.

**Comment by rade** [comment] 2015-10-30 15:32
> people using the API version supplied by the remote is just absolutely the wrong thing to do and breaks the purpose of API versioning.

Absolutely, but we cannot escape the fact that this is precisely what many people *are* doing.

There is a trade-off here of course, e.g. if the required change to retain compatibility was hideously complex, or the resulting output was highly misleading then it wouldn't be worth doing. I don't think that is the case here though.

**Closed** 2015-10-30 23:03 UTC
