### ISSUE TITLE
docker outputs to standard out with added carriage return character

### ISSUE THREAD

**Issue by itsafire** [docker/docker#8513] opened 2014-10-11 10:35 UTC
Running `docker run -ti --rm ubuntu:12.04 cat /etc/passwd >passwd.txt` will result in a passwd file with added carriage return character at the end of each line. What is the rationale of this behavior ? Or is this to be considered a bug ?

My current Docker environment is:

```
docker@thor:~$ docker info
Containers: 4
Images: 179
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 187
Execution Driver: native-0.2
Kernel Version: 3.14.0-2-amd64
Operating System: Debian GNU/Linux jessie/sid
```

**Comment by jfrazelle** [comment] 2015-02-26 04:50
I cannot reproduce on the latest version, please let me know if you can and I will reopen

**Comment by md5** [comment] 2015-02-26 05:03
@jfrazelle I just did exactly the same commands as https://github.com/docker/docker/issues/8513#issuecomment-65359848 and got the same results. I tried it both from my OS X terminal and from inside `boot2docker ssh`.

**Comment by jfrazelle** [comment] 2015-02-26 05:06
ping @icecrime what was the stuff with hijack and cat that was fixed, @md5 i have reopened

**Comment by jfrazelle** [comment] 2015-02-26 05:09
I dont see what you are talking about tho

```
root@aa6c3c3e9164:/# cat /etc/nsswitch.conf 
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
root@aa6c3c3e9164:/# cat /etc/nsswitch.conf > test
root@aa6c3c3e9164:/# cat test
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
root@aa6c3c3e9164:/# 
```

**Comment by jfrazelle** [comment] 2015-02-26 05:14
ohhhh i see its this
```
jessie at debian in ~/docker on skip-lxc-remaining-tests
$ docker run -ti --rm ubuntu:14.04 cat /etc/nsswitch.conf > test

jessie at debian in ~/docker on skip-lxc-remaining-tests [?]
$ cat test 
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis

jessie at debian in ~/docker on skip-lxc-remaining-tests [?]

```
this is not something that can be fixed you see docker run performs a new line and the file itself was adding a new line so then you get two, does that make sense

**Comment by md5** [comment] 2015-02-26 05:25
@jfrazelle Did you try my command? The echo inside the container is only sending a single byte to stdout, i.e. `\n`. When it comes out of `docker run` with `-t`, it has an extra `\r` in front of the `\n`.

**Comment by md5** [comment] 2015-02-26 05:26
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by jfrazelle** [comment] 2015-02-26 05:40
ya checkout my comment here https://github.com/docker/docker/issues/8513#issuecomment-76123655

**Comment by mmb** [comment] 2015-04-07 20:04
I'm also seeing these extra carriage returns in my output when `docker run --tty`. I'm on Linux so I should not be getting DOS line endings ("\r\n").

When I remove the --tty they aren't there.

```
user@host:/tmp# docker run --tty=true --interactive=true ruby:2.2.1 echo hi > out
user@host:/tmp# file out
out: ASCII text, with CRLF line terminators
```

```
user@host:/tmp# docker run --interactive=true ruby:2.2.1 echo hi > out
user@host:/tmp# file out
out: ASCII text
```

```
user@host:/tmp# docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by scr4bble** [comment] 2015-10-05 13:58
@jfrazelle Did you try original reproducer https://github.com/docker/docker/issues/8513#issuecomment-65359848 ? I didn't get your explanation. Please can you provide some additional information about solution of this issue ? I would be very happy, if you can explain reason, why is this issue closed and not fixed - preferably on original reproducer. Thanks in advance :)

RedHat Bugzilla tracker:
https://bugzilla.redhat.com/show_bug.cgi?id=1260111

**Comment by pmbauer** [comment] 2015-10-09 14:17
Ran into this issue today as well.
a `docker run --tty=true ...` outputs `\r\n` instead of `\n` on linux
```
$ docker version && docker info
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
Containers: 18
Images: 255
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 291
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.19.0-16-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 7.336 GiB
Name: 52.8.43.233
ID: S7PT:QYA4:VVEE:Z2ZJ:IWL2:GPNQ:QNZB:VTVA:GRUJ:EEBL:CVWH:5NFK
Username: pmbauer
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

**Comment by pupssman** [comment] 2015-10-22 22:16
Folks, what's up on that?
Still looks like a great deal of a bug to me.

**Comment by Globidev** [comment] 2015-11-12 00:42
Still getting this weird behavior with docker 1.9

```sh
> docker run --rm busybox echo "Hello World" | cat -e
Hello World$

> docker run --rm -t busybox echo "Hello World" | cat -e
Hello World^M$
```

```sh
> docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

> docker info
Containers: 18
Images: 176
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 212
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-33-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.781 GiB
Name: ubuntu
ID: CJNC:AI5U:HIYG:X4VN:IVWT:YSFE:HCTL:VQXH:EMP3:CMJN:UODG:CAYV
Username: globidocker
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

**Comment by KholdStare** [comment] 2015-12-02 23:58
I have the same issue still. Can this be reopened please?

**Comment by thaJeztah** [comment] 2015-12-03 00:14
@KholdStare reading back the discussion it looks like this couldn't be fixed in docker; https://github.com/docker/docker/issues/8513#issuecomment-76123655 but perhaps I've misunderstood @jfrazelle ?

**Comment by KholdStare** [comment] 2015-12-03 18:54
@thaJeztah I'm sorry if I sound rude, but that referenced comment does not make any sense. @Globidev has an easily reproducible case where `-t` affects output, and it has been mentioned multiple times throughout the thread. Unfortunately, it does not look like @jfrazelle ran the suggested test case.

**Comment by pauldorn** [comment] 2016-01-18 22:38
The misunderstanding appears to be that @jfrazelle has assumed you mean trailing linefeeds only.
It is affecting ALL linefeeds including embedded.

This is reproducible in 1.9.1 build a34a1d5

My use case is a dockerized script that produces a PDF.  
When run inside the container for consumption in the container it works as expected.
When the container output is redirected to a file on the host with `docker run -it --rm genpdf > broken.pdf` it comes out with all embedded linefeeds converted to cr/lf.
This is clearly wrong.

**Comment by cpuguy83** [comment] 2016-01-19 01:34
I am not seeing the extra carriage returns described.
Is there a simple repro other than `docker run --rm busybox echo "Hello World" | cat -e`?

Also, what platform is the docker client running on?

**Comment by ace13** [comment] 2016-01-19 01:39
@cpuguy83 
`docker run -t --rm busybox echo "Hello World" | cat -e`
It only happens when a tty is assigned.

This issue has been wrecking havoc for me on one of my newly dockerized personal projects, even managing to fit carriage returns into the log messages. Makes it rather impossible to access the tty for the project, as the terminals I have access to (PuTTY, MSYS) break when fed carriage returns.

**Comment by cpuguy83** [comment] 2016-01-19 01:41
Aha, thanks!

**Comment by Globidev** [comment] 2016-01-19 13:17
One of the easiest reproducible case is to just run the official `hello-world` image with and without the `--tty (-t)` flag
Since the default command of that image outputs several lines to stdout, this will easily highlight the fact that every linefeed is indeed affected.

Just compare the output of:
`docker run --rm hello-world | cat -e` 
with:
`docker run --rm --tty hello-world | cat -e`

Here `cat -e` shows newlines with a `$` and carriage returns with a `^M`
You can also count the carriage returns with `grep -o $'\r' | wc -l`

**Comment by generalov** [comment] 2016-01-22 06:32
Yet another tooling to visualize that :)
```
$ docker run --rm  busybox echo "Hello World" | xxd
00000000: 4865 6c6c 6f20 576f 726c 640a            Hello World.
$ docker run --rm -t busybox echo "Hello World" | xxd
00000000: 4865 6c6c 6f20 576f 726c 640d 0a         Hello World..
```

**Comment by frankcarey** [comment] 2016-01-26 21:44
I started on a test for this in a PR, but got stuck dealing with getting it to work..

However, I just figured out a workaround for bash scripts. If you set the command's stdin to /dev/null, then you can avoid the extra CR / `\r` / `^M` / `0d`

`docker exec -it ... < /dev/null | cat -e`

**Comment by generalov** [comment] 2016-01-27 05:40
Hm.. stdin redirection may be the some sort of disabling the terminal support. 
As it is written above the docker doesn't append CR then terminal doen't enabled.

**Comment by caioalvs** [comment] 2016-04-08 22:07
Folks,

I managed to workaround this issue by pipeline output to `sed -e "s/\r//"` to replace the carriage returns.

Using the official `hello-world` image for example, if output is redirected to a file the content appears with the `^M`character.

`docker run --rm --tty hello-world > /tmp/hello-world.txt`

Applying `sed -e "s/\r//"` using a pipeline, the file content is clear of carriage returns.

`docker run --rm --tty hello-world | sed -e "s/\r//" > /tmp/hello-world.txt`

**Comment by thaJeztah** [comment] 2016-05-02 10:25
Looks like this is indeed TTY by default translates newlines to CRLF

```bash
$ docker run -t --rm debian sh -c "echo -n '\n'" | od -c
0000000   \r  \n
0000002
```

disabling "translate newline to carriage return-newline" with `stty -onlcr` correctly gives;

```bash
$ docker run -t --rm debian sh -c "stty -onlcr && echo -n '\n'" | od -c
0000000   \n
0000001
```

So, not sure what should be done here; the default line-endings used by TTY is CRLF, and that's what is visible here

@md5 @cpuguy83 wdyt?

**Comment by cpuguy83** [comment] 2016-05-02 15:36
Moral of the story, don't use `-t` unless you want a TTY.
TTY line endings are CRLF, this is not Docker's doing.

**Comment by thaJeztah** [comment] 2016-05-06 22:46
Given https://github.com/docker/docker/issues/8513#issuecomment-216191236, I agree, this is not something in Docker, but the way TTY's work. I'll close this issue.

**Closed by thaJeztah** 2016-05-06 22:46 UTC

**Comment by scr4bble** [comment] 2016-05-09 14:34
@thaJeztah Thanks for nice explanation.

**Comment by Globidev** [comment] 2016-05-10 02:09
I tried to understand how default TTY options were set but Google didn't help me very much
If anyone is knowledgeable on the subject I would love to hear an explanation

Also, if anyone is able to explain to me why on a gnome terminal (default one on Ubuntu distros) and with a recent bash, when you run `stty -a` you see that the `onlcr` flag **is set** yet the terminal doesn't show carriage returns.

I made a simple version of  `stty` to display `stdout`'s terminal attributes
If you compile it statically, you can make an image from `scratch` only containing the resulting binary and run a container from it to see the default TTY attributes (I didn't want to run say `stty` on a `busybox` because I wasn't sure if the filesystem had an impact on the default TTY options).

[code here](https://gist.github.com/Globidev/bbbe1ad1b08804cb8a3f5b2f671c400d)
You can even compile it with docker:
```sh
docker run --rm -v $PWD:/app -w /app gcc:5.3 gcc -static -o tiny-stty main.c
```

Make a image from scratch:
```Dockerfile
FROM scratch

ADD tiny-stty /
ENTRYPOINT ["/tiny-stty"]
```

build and run it:
```sh
docker build -t tiny-stty .
docker run --rm -t tiny-stty
```

**Comment by Globidev** [comment] 2016-05-10 02:34
Just found out about `<sys/ttydefaults.h>`

which on my linux has something like:
```c
/*
 * Defaults on "first" open.
 */
#define TTYDEF_IFLAG    (BRKINT | ISTRIP | ICRNL | IMAXBEL | IXON | IXANY)
#define TTYDEF_OFLAG    (OPOST | ONLCR | XTABS)
#define TTYDEF_LFLAG    (ECHO | ICANON | ISIG | IEXTEN | ECHOE|ECHOKE|ECHOCTL)
#define TTYDEF_CFLAG    (CREAD | CS7 | PARENB | HUPCL)
#define TTYDEF_SPEED    (B9600)
```

`ONLCR` is indeed there

So yeah, I guess if you wanted to change the default TTY attributes of your containers run with `-t` transparently (without using @thaJeztah method), you would have to use a docker daemon on a linux compiled with different values for the flags above.
Seems a bit far fetched though. Time to go to bed now :)

**Comment by dragon788** [comment] 2017-10-14 21:10
Just ran into this when using tab completion on a command that runs from within a container (a la @jessfraz 's awesome .dockerfunc stuff). I am using @tianon 's github-hub, and I couldn't figure out when trying to `hub add somefile<Tab>` it was appending `^M` after the filename. Looking here I was able to drop the `-t` from my `docker run -i <lotsOstuff>` and it still functions for `hub push` et al, so I'm happy, but confused why this behavior can't seem to be overridden.

**Comment by StayPirate** [comment] 2021-03-16 13:59
Any idea why Docker acts weird with pipes when both `-t` and `-i` options are set?
```bash
> docker container run --rm -t alpine:latest sh -c "echo" | cat -A
^M$
> # pressed enter here
> docker container run --rm -ti alpine:latest sh -c "echo" | cat -A
^M$
   > # pressed enter here
>
```
The same happens with Podman, but in this case `-t` is enough to trigger this misbehavior
```bash
> podman container run --rm -t alpine:latest sh -c "echo" | cat -A
^M$
   > # pressed enter here
> podman container run --rm -ti alpine:latest sh -c "echo" | cat -A
^M$
   > # pressed enter here
```
This is quite annoying since it breaks some pipelines I daily use, additional info can be found at https://github.com/containers/podman/issues/9718.
