### ISSUE TITLE
Debian jessie repository hash sum mismatch error

### ISSUE THREAD

**Issue by mihalski** [docker/docker#27477] opened 2016-10-18 05:37 UTC
Hi,

I have followed the install instructions for docker-engine on the latest Raspbian Jessie running on a Raspberry Pi 3.

Upon running sudo apt-get update I get the following error:

```
pi@homepi:~ $ sudo apt-get update
Hit https://deb.nodesource.com jessie InRelease
Hit https://apt.dockerproject.org debian-jessie InRelease
Get:1 https://deb.nodesource.com jessie/main Sources [763 B]
Get:2 http://mirrordirector.raspbian.org jessie InRelease [14.9 kB]
Get:3 https://apt.dockerproject.org debian-jessie/main armhf Packages [1,384 B]
Hit http://repo.mosquitto.org jessie InRelease
Get:4 https://deb.nodesource.com jessie/main armhf Packages [967 B]
Get:5 https://apt.dockerproject.org debian-jessie/main Translation-en_GB [454 B]
Hit https://openhab.ci.cloudbees.com  InRelease
Get:6 https://deb.nodesource.com jessie/main Translation-en_GB [162 B]
Get:7 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:8 http://mirrordirector.raspbian.org jessie/main armhf Packages [8,981 kB]
Hit https://openhab.ci.cloudbees.com  InRelease
Hit http://archive.raspberrypi.org jessie InRelease
Get:9 https://deb.nodesource.com jessie/main Translation-en_GB [162 B]
Get:10 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:11 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]
Hit https://openhab.ci.cloudbees.com  Packages
Get:12 https://deb.nodesource.com jessie/main Translation-en_GB [162 B]
Get:13 https://openhab.ci.cloudbees.com  Translation-en_GB [367 B]
Get:14 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:15 https://apt.dockerproject.org debian-jessie/main Translation-en_GB [454 B]
Get:16 https://deb.nodesource.com jessie/main Translation-en_GB [162 B]
Hit http://repo.mosquitto.org jessie/main armhf Packages
Get:17 https://openhab.ci.cloudbees.com  Translation-en [364 B]
Get:18 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:19 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]
Hit https://openhab.ci.cloudbees.com  Packages
Get:20 https://apt.dockerproject.org debian-jessie/main Translation-en_GB [454 B]
Get:21 https://deb.nodesource.com jessie/main Translation-en_GB [162 B]
Ign https://deb.nodesource.com jessie/main Translation-en_GB
Get:22 https://deb.nodesource.com jessie/main Translation-en [162 B]
Ign https://deb.nodesource.com jessie/main Translation-en
Get:23 https://openhab.ci.cloudbees.com  Translation-en_GB [366 B]
Get:24 https://openhab.ci.cloudbees.com  Translation-en [363 B]
Get:25 https://openhab.ci.cloudbees.com  Translation-en_GB [367 B]
Get:26 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]
Get:27 https://openhab.ci.cloudbees.com  Translation-en [364 B]
Get:28 https://apt.dockerproject.org debian-jessie/main Translation-en_GB [454 B]
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Get:29 https://openhab.ci.cloudbees.com  Translation-en_GB [366 B]
Get:30 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Get:31 https://openhab.ci.cloudbees.com  Translation-en [363 B]
Ign http://repo.mosquitto.org jessie/main Translation-en_GB
Get:32 https://openhab.ci.cloudbees.com  Translation-en_GB [367 B]
Ign http://repo.mosquitto.org jessie/main Translation-en
Get:33 https://openhab.ci.cloudbees.com  Translation-en [364 B]
Get:34 https://apt.dockerproject.org debian-jessie/main Translation-en_GB [454 B]
Ign https://apt.dockerproject.org debian-jessie/main Translation-en_GB
Get:35 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]
Ign https://apt.dockerproject.org debian-jessie/main Translation-en
Get:36 https://openhab.ci.cloudbees.com  Translation-en_GB [366 B]
Get:37 https://openhab.ci.cloudbees.com  Translation-en [363 B]
Get:38 https://openhab.ci.cloudbees.com  Translation-en_GB [367 B]
Get:39 https://openhab.ci.cloudbees.com  Translation-en [364 B]
Get:40 https://openhab.ci.cloudbees.com  Translation-en_GB [366 B]
Get:41 https://openhab.ci.cloudbees.com  Translation-en [363 B]
Get:42 https://openhab.ci.cloudbees.com  Translation-en_GB [367 B]
Ign https://openhab.ci.cloudbees.com  Translation-en_GB
Get:43 https://openhab.ci.cloudbees.com  Translation-en [364 B]
Ign https://openhab.ci.cloudbees.com  Translation-en
Get:44 http://mirrordirector.raspbian.org jessie/contrib armhf Packages [37.5 kB]
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Get:45 https://openhab.ci.cloudbees.com  Translation-en_GB [366 B]
Ign https://openhab.ci.cloudbees.com  Translation-en_GB
Get:46 https://openhab.ci.cloudbees.com  Translation-en [363 B]
Ign https://openhab.ci.cloudbees.com  Translation-en
Get:47 http://mirrordirector.raspbian.org jessie/non-free armhf Packages [70.3 kB]
Get:48 http://mirrordirector.raspbian.org jessie/rpi armhf Packages [1,356 B]
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Fetched 9,109 kB in 30s (297 kB/s)
W: Failed to fetch https://apt.dockerproject.org/repo/dists/debian-jessie/main/binary-armhf/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

This seems like a recurrence of earlier issue https://github.com/docker/docker/issues/23203

Regards,
Michal

**Comment by thaJeztah** [comment] 2016-10-18 05:50
Looks like a duplicate of https://github.com/docker/docker/issues/25879; TL;DR there's no packages for debian-jessie, only for raspbian-jessie (but read the discussion on the linked issue for more details)

I'll close this issue, as this looks like a duplicate, but feel free to comment if I closed by mistake

**Closed by thaJeztah** 2016-10-18 05:50 UTC

**Comment by mihalski** [comment] 2016-10-18 06:04
Correct me if I'm wrong but the problem in the other issue is that they're NOT using raspbian jessie and the packages don't work with other distributions?

Meanwhile I AM using raspbian-jessie and am still having a hash mismatch error. It SEEMS like a different problem but I don't fully understand the intricacies involved in the apt packaging system.

**Comment by thaJeztah** [comment] 2016-10-18 06:09
Perhaps I misunderstood, but in your output, it's trying to fetch from the debian-jessie repo, not raspbian-jessie http://apt.dockerproject.org/repo/dists/raspbian-jessie/main/

**Comment by mihalski** [comment] 2016-10-18 06:33
Touche!

I'm rarely so happy to realise I've been an idiot. You are completely right. The problem was the docker documentation referred me back to the debian installation instructions without mentioning the existence of raspbian-jessie and I was totally blind to it.

Once I made the change to the sources.list file the update and install worked perfectly.

Thank you! :)

**Comment by thaJeztah** [comment] 2016-10-18 06:59
*phew* happy I didn't make a fool of myself (as I haven't run docker on a rPi myself 😅 )

We need to improve the documentation around this, and (hopefully) will be able to build both raspbian and debian without them conflicting again soon.

Happy to hear it's resolved, and glad I was able to help!
