### ISSUE TITLE
How to connect a Docker container to a local network?

### ISSUE THREAD

**Issue by diogojesus95** [docker/docker#32220] opened 2017-03-30 08:38 UTC
So i've googled a lot for the past 3 days but still cannot find a valid answer for my problem.

I'm running Docker on a Raspberry Pi 3 using Raspbian (jessie). So far everything is great, did some containers etc, etc. Problem now is to access the containers from other PCs on the same network. Can someone explain how can I make containers to show under my router list as an independent machine? Port Forwarding is useless because we are using few ports and sometimes if we need to add some new function to it, we must commit the container, delete the container, create a new container under the image created and add the new ports to forward. I googled a lot for a few days now, and this is driving me insane. I also had to learn a lot about docker for the last 3.

Thank you.

System: Raspberry Pi3 | Raspbian (Jessie)

PS: If more info is needed i'll be happy to give it under the comments, thank you

**Comment by thaJeztah** [comment] 2017-03-30 11:55
Possibly the MacVlan (https://docs.docker.com/engine/userguide/networking/get-started-macvlan/) or the (still experimental) IPVlan (https://github.com/docker/docker/blob/v17.03.1-ce/experimental/vlan-networks.md) drivers could help with this.

> Port Forwarding is useless because we are using few ports and sometimes if we need to add some new function to it, we must commit the container, delete the container, create a new container under the image created and add the new ports to forward.

Best practice is for your containers to be "ephemeral" and stateless; build images from a Dockerfile so that they are reproducible, and keep any stateful data out of the container (for example, by storing it in a volume). This is actually one of the biggest advantages of using Docker, because having your containers fully reproducible. Instead of upgrading software _in_ the container, rebuild the image, and replace the container, this allows you to test _exactly_ the same code as you'll be _deploying_, and allows rolling back a deploy to an older version of the image.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-30 11:55 UTC
Labels: platform/arm
