### ISSUE TITLE
Allow ability to limit disk space available to a container

### ISSUE THREAD

**Issue by jamshid** [docker/docker#16670] opened 2015-09-30 02:01 UTC
docker version: 1.8.2 client / 1.8.2 server
docker info: local virtualbox (boot2docker) created by docker-machine
uname -a: OSX

List the steps to reproduce the issue:

1. I expect to be able to set a disk volume memory limit, e.g. -v '/var/elasticsearch-data(5gb)' to create a volume that can only use 5gb of disk space.

Describe the results you received:

It's not possible to set a limit/quota on a docker volume. There are suggested workarounds (see below), but require special docker server configuration and manual host directory management.

Describe the results you expected:

It would work similarly to setting the `--cpu-quota` or `--memory`.

Provide additional info you think is important:

It seems like it would be useful and consistent to allow docker volumes to be limited in size, similar to the way cpu can be limited when running a container.

I see the suggestions here for limiting the disk space available to a container:
https://groups.google.com/d/msg/docker-user/jo1Muu7FXg4/5pIAz7nPHo8J

>- use the devicemapper driver; then the limit will be the size of the filesystem (10 GB by default; which is maybe a lot compared to what you really want!)

I use docker-machine/boot2docker, devicemapper is not enabled by default afaik, is it safe? I have very bad memories of docker on on CentOS / devicemapper.

>- use USER (or another mechanism) to make sure that the process in the container runs a specific UID, then bind-mount a volume of a limited size from the host, and make it so that's the only place where this UID can write

Does that imply docker's "automatic" volumes can't be used, a fixed directory on the docker host must be used instead? I currently rely on docker managing the volumes.

**Comment by thaJeztah** [comment] 2015-10-13 00:15
Thanks for suggesting, @jamshid. I think this is a duplicate of https://github.com/docker/docker/issues/3804.

Are you okay with closing this one?

**Comment by tjdett** [comment] 2015-10-14 04:03
@thaJeztah #3804 doesn't mention volumes, but does mention storage backends (ie. storage drivers).

Given storage drivers aren't used with volumes (that's what the [volume plugin support](https://docs.docker.com/extend/plugins_volume/) is for) I don't think this is a duplicate.

**Comment by tjdett** [comment] 2015-10-14 04:14
@jamshid Some of the existing [volume plugins](https://github.com/docker/docker/blob/master/docs/extend/plugins.md) have the ability to create fixed size volumes out-of-band, which can then be mounted on container run. Alternately you could consider writing your own volume plugin which allows you to embed the filesize into the volume name.

I think that would look something like: `--volume-driver=volquotaplugin -v myelasticsearchdata(5g):/var/elasticsearch-data`

**Comment by LK4D4** [comment] 2016-09-13 23:39
@thaJeztah do you think we can say that it's task of volume driver and close this? I'm not sure that it's easy task to bring this to default driver.

**Comment by thaJeztah** [comment] 2016-09-14 08:22
I agree; this is now possible through volume driver plugins, and we want to keep the default volume driver simple, and not overload it with features.

I'm closing this issue, for the above reasons, but we can reconsider in future if there's strong arguments for having this in the default driver (and it's technically possible)

**Closed by thaJeztah** 2016-09-14 08:22 UTC
Labels: area/volumes, kind/feature

**Comment by mydockergit** [comment] 2019-03-13 08:28
Now it possible with: ` docker create -it --storage-opt size=1G alpine sh -c 'df -h'`
But you should have xfs, otherwise you will get the error:  

> Error response from daemon: --storage-opt is supported only for overlay over xfs with 'pquota' mount option

**Comment by shubhammicrosoft1** [comment] 2020-06-16 19:08
> docker create -it --storage-opt size=1G alpine sh -c 'df -h'

I received below error when implementing above approach

Error response from daemon: --storage-opt is supported only for overlay over xfs with 'pquota' mount option
