### ISSUE TITLE
Mounted from contianer glusterfs volume is not accessible after container stopped.

### ISSUE THREAD

**Issue by liubin** [docker/docker#25472] opened 2016-08-07 09:40 UTC
What I want do is to mount a glusterfs volume to host from in a container. And then other containers can use the volume by `-v /foo/mnt-2:/somewhere-else`.

I just tried:

### Step 0:

Install glusterfs 3.8 in host.

### Step 1:

In host:

```
mkdir /foo
mount -o bind /foo /foo
mount --make-shared /foo
```

### Step 2:

Start a new container:

```
docker run -ti  --rm --privileged=true -v /foo:/foo:rshared -v /var/run/glusterd.socket:/var/run/glusterd.socket gfs bash 
```

In container, mount the volume:

```
# mount | grep foo
/dev/disk/by-uuid/8ea401db-b84b-4cd6-a628-d72f30bbf1e5 on /foo type ext4 (rw,relatime,discard,data=ordered)

# mkdir /foo/mnt-2
# mount -t glusterfs 172.21.12.10:/vol-1 /foo/mnt-2

# mount | grep foo
/dev/disk/by-uuid/8ea401db-b84b-4cd6-a628-d72f30bbf1e5 on /foo type ext4 (rw,relatime,discard,data=ordered)
172.21.12.10:/vol-1 on /foo/mnt-2 type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
# date > /foo/mnt-2/date.txt
```

### Step 3:

In **HOST** Verify that the file is created in the dir:

```
# cat /foo/mnt-2/date.txt
Sun Aug  7 08:56:47 UTC 2016

```

This will print the file's content.

### Step 4:

Stop the container:

```
# exit from container
```

### Step 5:

In **HOST** Verify that the file in the dir:

```
cat /foo/mnt-2/date.txt
```

This will show a error:

```
cat: /foo/mnt-2/date.txt: Transport endpoint is not connected
```

### Step 6:

Start another new container and run the `mount` command:

```
# mount | grep foo
/dev/disk/by-uuid/8ea401db-b84b-4cd6-a628-d72f30bbf1e5 on /foo type ext4 (rw,relatime,discard,data=ordered)
172.21.12.10:/vol-1 on /foo/mnt-2 type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)

```

Here, I can **still** see the `/foo/mnt-2` mountpoint.

### Step 7:

If I want to view the content, I must start a new container and in it run `umount` and `mount` commands again.

## My question:

- 1. Is this is a bug or not?
- 2. If 1's answer is true, whose bug? Glusterfs or Docker?
- 3. If 1's answer is false, is there any workaround to do step 7 automatically?
- 4. In host, I can't find the entry of `/foo/mnt-2` mounted in the container by `mount` command. Is this right?

In step 4, I found these logs:

```
./bricks/glusterfs-data-vol-1.log:[2016-08-08 06:20:12.592344] I [MSGID: 115036] [server.c:548:server_rpc_notify] 0-vol-1-server: disconnecting connection from 172.21.12.10-14245-2016/08/08-06:18:12:965080-vol-1-client-0-0-0
./bricks/glusterfs-data-vol-1.log:[2016-08-08 06:20:12.592395] I [MSGID: 101055] [client_t.c:415:gf_client_unref] 0-vol-1-server: Shutting down connection 172.21.12.10-14245-2016/08/08-06:18:12:965080-vol-1-client-0-0-0
```

###  `docker info`

```
# docker info
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 171
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 190
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: 172.21.12.10
ID: GDAE:QRED:R2VE:UHJI:HR7L:VKW6:GYQJ:7BUD:VVBF:75TP:RE7S:RELZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

### `docker version`

```
# docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

### Other info:

```
root@172:~# uname -a
Linux 172.21.12.10 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@172:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

Dockerfile to build `gfs` image:

```
Dockerfile 
FROM ubuntu:trusty

RUN apt-get update -y

RUN apt-get install -y software-properties-common \
  && add-apt-repository -y ppa:gluster/glusterfs-3.8 && apt-get update \
  && apt-get install -y glusterfs-server
```

**Comment by cpuguy83** [comment] 2016-08-08 13:56
I don't think this is a docker bug.

While you are using the `mount` command, this is really going to use the gluster client (because of the `-t glusterfs` to connect to the gluster service.
I'm not sure if it's a bug in gluster, but it could be. It may just be expected behavior.

I would recommend using the gluster volume driver rather than manually mounting yourself in a container.

Again, don't believe this is a Docker bug so closing.

**Closed by cpuguy83** 2016-08-08 13:56 UTC
Labels: version/1.12
