### ISSUE TITLE
Pulling image from V1 registry with Docker 1.10 and then pushing to a V2 registry (or running docker save) sometimes results in error: "could not verify layer data" 

### ISSUE THREAD

**Issue by dnwake** [docker/docker#26434] opened 2016-09-09 01:05 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   20f81dd
 Built:        Thu Jun 30 21:32:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   20f81dd
 Built:        Thu Jun 30 21:32:57 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 39
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-252:2-6817609-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.188 GB
 Data Space Total: 107.4 GB
Data Space Available: 98.19 GB
 Metadata Space Used: 15.41 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.132 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.117-RHEL6 (2016-08-15)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 10
Total Memory: 19.45 GiB
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Pull image from a V1 Docker registry
2. Tag and push the image to a V2 Docker registry with Content Trust enabled

**Describe the results you received:**
Push fails with an error such as the following in /var/log/docker:

```
Upload failed: could not verify layer data for: sha256:a566d6467316a731f621511e8b3095449404392c6a3260695bea1f37b6e24a63. This may be because internal files in the layer store were modified. Re-pulling or rebuilding this image may resolve the issue
```

**Describe the results you expected:**
Successful push.  

**Additional information you deem important (e.g. issue happens only occasionally):**
Push fails only on certain image layers.

Push ~~succeeds~~ also fails if Content Trust is not enabled.  

Images relying on the problematic layers appear to function fine when run in a container.

**Comment by TanmayaA** [comment] 2016-09-13 09:54
Output of **docker version**:
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

Output of **docker info**
```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 8912
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10387
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 19.61 GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 v2.registry
 v1.registry
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. Pull image from a V1 Docker registry
2. Tag and push the image to a V2 Docker registry with/without Content Trust enabled

**Describe the results you received:**
```
could not verify layer data for: sha256:5054260950ae3bc9p76c6697241ba75b0584b48023b780d8e79d58668394bb2d. This may be because internal files in the layer store were modified. Re-pulling or rebuilding this image may resolve the issue
```

**Describe the results you expected:**
Successful push

**Additional information you deem important (e.g. issue happens only occasionally):**
- Push fails only on certain image layers.
- Push fails even if **Content Trust is not enabled**, which is **not** the case with OP
```
docker push --disable-content-trust registryv2/some/image
```
- Images relying on the problematic layers appear to function fine when run in a container.

**Comment by LK4D4** [comment] 2016-09-13 15:34
ping @aaronlehmann @stevvooe @tonistiigi

**Comment by tonistiigi** [comment] 2016-09-13 17:39
@dnwake @TanmayaA Can you share any of these v1 images, or does it happen with all the v1 images for you? I assume you get the same error on `docker save`?

**Comment by aaronlehmann** [comment] 2016-09-13 17:40
@dnwake @TanmayaA: Are there any particular images that trigger this problem? I tried with a few images and couldn't reproduce it - but I don't know whether this is related to the images themselves, or the version of Docker that pushed the images to the v1 registry originally.

**Comment by dnwake** [comment] 2016-09-14 03:51
@TanmayaA On rechecking I am also experiencing the problem, at least on some images, even without Content Trust.  I've amended the initial problem description.

@tonistiigi @aaronlehmann It is only certain image layers that trigger the problem.  Most image layers work fine, but any images that contain the problematic layers fail to push.

@tonistiigi Yes, I get the same error with "docker save".  I will have to check with my team to see whether there are any objections to sharing a problematic image.  Since "docker save" doesn't work, how should I share it?

**Comment by dnwake** [comment] 2016-09-14 06:02
A couple of other observations:

- If I run "docker history --no-trunc" on the bad image, the image digests in the first column are all given as "<missing>" except for the very first row.  However, every other column of output -- "CREATED", "CREATED BY", "SIZE" and "COMMENT" -- appears (at least at first glance) to be correct, compared to a "good" version of the same image I found on another machine.

- When I pull from the V1 registry, I get intermittent 502 errors.  However, these don't seem to be the cause of the problem -- I tried stopping docker, wiping out the /var/lib/docker directory, restarting docker, and then doing an apparently "clean" pull with no 502, and still saw the same problem with the image.

**Comment by tonistiigi** [comment] 2016-09-14 22:21
@dnwake You can use our old frozen images pull script https://gist.github.com/tonistiigi/6ca815205b8c8213dc58086b703c26d6 and then extract the output folder.

**Comment by tonistiigi** [comment] 2016-09-14 22:24
@dnwake Parents marked as "<missing>" is correct behavior. Docker doesn't pull parent images in `v1.10+`, you will only see them on the machine that built time image.

**Comment by dnwake** [comment] 2016-09-15 23:40
I've managed to work around this issue finding good copies (on other machines) of the problematic images.

My best guess is that the V1 registry has become corrupted somehow, but it seems problematic that this is discovered only on push or save rather than on pull.

I'm not currently able to share the problematic images.

**Comment by thaJeztah** [comment] 2016-09-20 12:24
@dnwake let me close this issue for now, but happy to reopen if we have a way to reproduce

**Comment by TanmayaA** [comment] 2016-09-21 12:41
@thaJeztah I was not available to respond. Sorry for the delay.
@tonistiigi @aaronlehmann May have get a direct docker.com email, or location to send the image tar?

**Comment by aaronlehmann** [comment] 2016-09-21 22:10
@TanmayaA: Feel free to send it to aaron.lehmann (at) docker.com.

**Comment by sabretus** [comment] 2016-09-22 14:00
Have the same issue, download from V1 and push to V2 fails with the same error, docker version 1.11.2. Unfortunately can't send image to analyze.

**Comment by TanmayaA** [comment] 2016-09-22 14:44
@aaronlehmann sent. Please confirm

**Comment by aaronlehmann** [comment] 2016-09-22 17:20
Received the file. I'll take a look.

**Comment by aaronlehmann** [comment] 2016-09-23 01:45
@TanmayaA: This has been tracked down to a bug in the `tar-split` library. We're working on a fix for `tar-split` and should submit it upstream soon.

Thanks again for providing an image that exhibited the problem.

**Comment by TanmayaA** [comment] 2016-09-23 07:09
@aaronlehmann Thanks for the quick work! May I have an ETA on this if possible? I'm blocked due to this, and have more than 30k images to migrate :(

**Comment by aaronlehmann** [comment] 2016-09-23 17:21
@TanmayaA: We have the first release candidate of Docker 1.12.2 scheduled for release in a few days. I can't promise that the fix will make it into 1.12.2 (especially the initial release candidate), but that's a possibility.

Otherwise, the fix should become available in nightly builds from the master branch at https://master.dockerproject.org once it's merged into Docker. This will hopefully happen within the next few days. It would be great if you could test one of these builds once it incorporates the fix.

cc @dmcgowan @vbatts

**Comment by TanmayaA** [comment] 2016-09-26 06:03
@aaronlehmann Since this docker build only has to run on a docker migrator, I think I'm good using the nightly build. Will be great if you can update here, along with usage instructions, when this fix is available there.

**Closed** 2016-10-05 20:45 UTC
Labels: area/distribution, kind/bug, version/1.10, version/1.12

**Comment by aaronlehmann** [comment] 2016-10-06 13:45
@TanmayaA: The PR to update tarsplit got merged to master. Within a day or so, it will be included in the nightly build. Please let us know if the nightly build fixes these problems.

**Comment by zachwalton** [comment] 2016-10-12 21:34
I'm getting this too with the current experimental train:

```
$ docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true
$ cat rhel6_8.x86_64.tgz | sudo docker import - rhel68:base
sha256:d7ca94ad002eaee1d1a4ff147dd6c426766b824892d03d82f6ca632a3de93536
$ docker save rhel68:base > rhel68-base.tar
Error response from daemon: could not verify layer data for: sha256:cd8506ee956b460e2b8cbf6734242481bc9e6951549a44bf24e81fae5f8124b2. This may be because internal files in the layer store were modified. Re-pulling or rebuilding this image may resolve the issue
```

I am unfortunately unable to provide the image; are there logs or anything else that could help further diagnose?

**Comment by tonistiigi** [comment] 2016-10-12 21:39
@zachwalton Unfortunately the fix here didn't make into `v1.12.2`. Can you test with the master build from https://master.dockerproject.org/

**Comment by zachwalton** [comment] 2016-10-12 21:51
Same issue with `1.13.0-dev@32f93fd`:

```
$ docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   32f93fd
 Built:        Wed Oct 12 20:49:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   32f93fd
 Built:        Wed Oct 12 20:49:42 2016
 OS/Arch:      linux/amd64
$ cat rhel6_8.x86_64.tgz | docker import - rhel68:base
sha256:d96e99859f0ef93702b3d7e01ebcd05988d09877b6b35d9c193ef34b6b51cfc2
$ docker save oel68:base > oel68.tar
Error response from daemon: could not verify layer data for: sha256:cd8506ee956b460e2b8cbf6734242481bc9e6951549a44bf24e81fae5f8124b2. This may be because internal files in the layer store were modified. Re-pulling or rebuilding this image may resolve the issue
```

**Comment by tonistiigi** [comment] 2016-10-12 22:03
@TanmayaA Have you been able to test your images so we could see if the new report is something different

**Comment by tonistiigi** [comment] 2016-10-13 20:47
@dmcgowan Could we put together a binary that just extracts a tar with tar-split and then tries to compress it back, logging out metadata for both steps so we see there the error happens. Note that the last example doesn't even use load/save format but just creates a layer from user provided tar.

**Comment by dmcgowan** [comment] 2016-10-13 21:41
@tonistiigi tar-split already has a utility to disassemble and assemble, I used it to test and verify the update for tar-split. It would not be difficult to create an update which adds more metadata for each step, what type of information would you be looking for though? The most useful output is the binary diff of the original tar to the disassembled-reassembled tar.

**Comment by tonistiigi** [comment] 2016-10-13 21:46
@dmcgowan Yes, binary diff is useful. I was thinking about list of files, after every file checksum for header, contents and the full checksum up to that point. Mainly something @zachwalton could run if he can't share us the original tar.

**Comment by TanmayaA** [comment] 2016-10-18 12:22
@tonistiigi I'll try to give an update by tomorrow

**Comment by TanmayaA** [comment] 2016-10-18 13:44
@tonistiigi no go, still same error:
```
FATA[0051] could not verify layer data for: sha256:xxxxxxxxx. This may be because internal files in the layer store were modified. Re-pulling or rebuilding this image may resolve the issue 
```

**Comment by tonistiigi** [comment] 2016-10-18 21:51
@TanmayaA I tried the load/save cycle on master build with the image you sent us and didn't have any problems. Did you re-pull/load the image as the fix applies during storing the data. Or does it appear with some other image now.

**Comment by stevvooe** [comment] 2016-10-18 21:55
@tonistiigi Is it possible that registry or its proxy is decompressing the layer content before it can be verified?

**Comment by tonistiigi** [comment] 2016-10-18 22:01
@stevvooe No, this happens on layerstore TarStream level. It verifies that bytes coming out of layerstore are the same that were used in `layerstore.Register`. Compression and talking with registry is outside layerstore. This can only be 1) bug in tar-split 2) bug in layerstore 3) external modification of data on disk.

**Comment by TanmayaA** [comment] 2016-10-20 11:31
@tonistiigi I tried at it failed on same image, just a different layer. However, I noticed that I didn't pull the image again, so going to retry. Will let you know how it goes
