### ISSUE TITLE
Flush command to delete images and containers

### ISSUE THREAD

**Issue by zotherstupidguy** [docker/docker#25655] opened 2016-08-12 09:41 UTC
I usually use `docker rm $(docker ps -a -q)` to delete containers and `docker rmi $(docker images -q)` to delete images. 

It would be a lot easier of if we have something like `docker flush containers `, `docker flush images` and `docker flush` that removes both.

**Comment by thaJeztah** [comment] 2016-08-12 10:10
Looks like this is a duplicate of https://github.com/docker/docker/issues/22871, which we are planning to work on in a future release. Please subscribe to that issue to stay up to date on progress 👍

**Closed by thaJeztah** 2016-08-12 10:10 UTC
