### ISSUE TITLE
incomplete /build response payload for non-cached /build

### ISSUE THREAD

**Issue by proppy** [docker/docker#10364] opened 2015-01-26 22:45 UTC
With docker 1.5.0-rc1 (mentioned in https://github.com/docker/docker/pull/10286) the response payload for /build seems incomplete w/ an empty cache:
```
>>> cli = docker.Client(**docker.utils.kwargs_from_env(assert_hostname=False)); cli.version()
{u'KernelVersion': u'3.16.7-tinycore64', u'Arch': u'amd64', u'ApiVersion': u'1.17', u'Version': u'1.5.0', u'GitCommit': u'7e803ba', u'Os': u'linux', u'GoVersion': u'go1.4.1'}
>>> print [x for x in cli.build(path='/tmp/context')]
['{"stream":"Step 0 : FROM busybox\\n"}\r\n', '{"status":"Pulling repository busybox"}\r\n', '{"status":"Pulling image (latest) from busybox","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Pulling image (latest) from busybox, endpoint: https://registry-1.docker.io/v1/","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Pulling dependent layers","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Pulling metadata","progressDetail":{},"id":"511136ea3c5a"}', '{"status":"Pulling fs layer","progressDetail":{},"id":"511136ea3c5a"}', '{"status":"Downloading","progressDetail":{"current":3646,"total":10240,"start":1422312173},"progress":"[=================\\u003e                                 ] 3.646 kB/10.24 kB 0","id":"511136ea3c5a"}', '{"status":"Download complete","progressDetail":{},"id":"511136ea3c5a"}', '{"status":"Pulling metadata","progressDetail":{},"id":"df7546f9f060"}', '{"status":"Pulling fs layer","progressDetail":{},"id":"df7546f9f060"}', '{"status":"Downloading","progressDetail":{"current":180,"total":180,"start":1422312175},"progress":"[==================================================\\u003e]    180 B/180 B","id":"df7546f9f060"}', '{"status":"Download complete","progressDetail":{},"id":"df7546f9f060"}', '{"status":"Pulling metadata","progressDetail":{},"id":"ea13149945cb"}', '{"status":"Pulling fs layer","progressDetail":{},"id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":13686,"total":1141531,"start":1422312177},"progress":"[\\u003e                                                  ] 13.69 kB/1.142 MB 1m8s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":33958,"total":1141531,"start":1422312177},"progress":"[=\\u003e                                                 ] 33.96 kB/1.142 MB 27s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":50342,"total":1141531,"start":1422312177},"progress":"[==\\u003e                                                ] 50.34 kB/1.142 MB 19s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":68710,"total":1141531,"start":1422312177},"progress":"[===\\u003e                                               ] 68.71 kB/1.142 MB 14s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":85094,"total":1141531,"start":1422312177},"progress":"[===\\u003e                                               ] 85.09 kB/1.142 MB 11s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":101478,"total":1141531,"start":1422312177},"progress":"[====\\u003e                                              ] 101.5 kB/1.142 MB 9s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":117862,"total":1141531,"start":1422312177},"progress":"[=====\\u003e                                             ] 117.9 kB/1.142 MB 7s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":134246,"total":1141531,"start":1422312177},"progress":"[=====\\u003e                                             ] 134.2 kB/1.142 MB 6s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":150630,"total":1141531,"start":1422312177},"progress":"[======\\u003e                                            ] 150.6 kB/1.142 MB 6s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":167014,"total":1141531,"start":1422312177},"progress":"[=======\\u003e                                           ]   167 kB/1.142 MB 5s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":183398,"total":1141531,"start":1422312177},"progress":"[========\\u003e                                          ] 183.4 kB/1.142 MB 4s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":199782,"total":1141531,"start":1422312177},"progress":"[========\\u003e                                          ] 199.8 kB/1.142 MB 4s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":216166,"total":1141531,"start":1422312177},"progress":"[=========\\u003e                                         ] 216.2 kB/1.142 MB 3s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":232550,"total":1141531,"start":1422312177},"progress":"[==========\\u003e                                        ] 232.6 kB/1.142 MB 3s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":248934,"total":1141531,"start":1422312177},"progress":"[==========\\u003e                                        ] 248.9 kB/1.142 MB 3s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":265318,"total":1141531,"start":1422312177},"progress":"[===========\\u003e                                       ] 265.3 kB/1.142 MB 3s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":281702,"total":1141531,"start":1422312177},"progress":"[============\\u003e                                      ] 281.7 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":298086,"total":1141531,"start":1422312177},"progress":"[=============\\u003e                                     ] 298.1 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":314470,"total":1141531,"start":1422312177},"progress":"[=============\\u003e                                     ] 314.5 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":330854,"total":1141531,"start":1422312177},"progress":"[==============\\u003e                                    ] 330.9 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":347238,"total":1141531,"start":1422312177},"progress":"[===============\\u003e                                   ] 347.2 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":363622,"total":1141531,"start":1422312177},"progress":"[===============\\u003e                                   ] 363.6 kB/1.142 MB 2s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":380006,"total":1141531,"start":1422312177},"progress":"[================\\u003e                                  ]   380 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":396390,"total":1141531,"start":1422312177},"progress":"[=================\\u003e                                 ] 396.4 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":412774,"total":1141531,"start":1422312177},"progress":"[==================\\u003e                                ] 412.8 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":429158,"total":1141531,"start":1422312177},"progress":"[==================\\u003e                                ] 429.2 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":445542,"total":1141531,"start":1422312177},"progress":"[===================\\u003e                               ] 445.5 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":461926,"total":1141531,"start":1422312177},"progress":"[====================\\u003e                              ] 461.9 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":478310,"total":1141531,"start":1422312177},"progress":"[====================\\u003e                              ] 478.3 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":494694,"total":1141531,"start":1422312177},"progress":"[=====================\\u003e                             ] 494.7 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":511078,"total":1141531,"start":1422312177},"progress":"[======================\\u003e                            ] 511.1 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":527462,"total":1141531,"start":1422312177},"progress":"[=======================\\u003e                           ] 527.5 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":543846,"total":1141531,"start":1422312177},"progress":"[=======================\\u003e                           ] 543.8 kB/1.142 MB 1s","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":560230,"total":1141531,"start":1422312177},"progress":"[========================\\u003e                          ] 560.2 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":576614,"total":1141531,"start":1422312177},"progress":"[=========================\\u003e                         ] 576.6 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":592998,"total":1141531,"start":1422312177},"progress":"[=========================\\u003e                         ]   593 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":609382,"total":1141531,"start":1422312177},"progress":"[==========================\\u003e                        ] 609.4 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":625766,"total":1141531,"start":1422312177},"progress":"[===========================\\u003e                       ] 625.8 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":642150,"total":1141531,"start":1422312177},"progress":"[============================\\u003e                      ] 642.1 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":658534,"total":1141531,"start":1422312177},"progress":"[============================\\u003e                      ] 658.5 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":674918,"total":1141531,"start":1422312177},"progress":"[=============================\\u003e                     ] 674.9 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":691302,"total":1141531,"start":1422312177},"progress":"[==============================\\u003e                    ] 691.3 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":707686,"total":1141531,"start":1422312177},"progress":"[==============================\\u003e                    ] 707.7 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":724070,"total":1141531,"start":1422312177},"progress":"[===============================\\u003e                   ] 724.1 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":740454,"total":1141531,"start":1422312177},"progress":"[================================\\u003e                  ] 740.5 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":756838,"total":1141531,"start":1422312177},"progress":"[=================================\\u003e                 ] 756.8 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":773222,"total":1141531,"start":1422312177},"progress":"[=================================\\u003e                 ] 773.2 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":789606,"total":1141531,"start":1422312177},"progress":"[==================================\\u003e                ] 789.6 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":805990,"total":1141531,"start":1422312177},"progress":"[===================================\\u003e               ]   806 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":822374,"total":1141531,"start":1422312177},"progress":"[====================================\\u003e              ] 822.4 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":838758,"total":1141531,"start":1422312177},"progress":"[====================================\\u003e              ] 838.8 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":855142,"total":1141531,"start":1422312177},"progress":"[=====================================\\u003e             ] 855.1 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":871526,"total":1141531,"start":1422312177},"progress":"[======================================\\u003e            ] 871.5 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":887910,"total":1141531,"start":1422312177},"progress":"[======================================\\u003e            ] 887.9 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":904294,"total":1141531,"start":1422312177},"progress":"[=======================================\\u003e           ] 904.3 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":920678,"total":1141531,"start":1422312177},"progress":"[========================================\\u003e          ] 920.7 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":937062,"total":1141531,"start":1422312177},"progress":"[=========================================\\u003e         ] 937.1 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":953446,"total":1141531,"start":1422312177},"progress":"[=========================================\\u003e         ] 953.4 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":969830,"total":1141531,"start":1422312177},"progress":"[==========================================\\u003e        ] 969.8 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":986214,"total":1141531,"start":1422312177},"progress":"[===========================================\\u003e       ] 986.2 kB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1002598,"total":1141531,"start":1422312177},"progress":"[===========================================\\u003e       ] 1.003 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1018982,"total":1141531,"start":1422312177},"progress":"[============================================\\u003e      ] 1.019 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1035366,"total":1141531,"start":1422312177},"progress":"[=============================================\\u003e     ] 1.035 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1051750,"total":1141531,"start":1422312177},"progress":"[==============================================\\u003e    ] 1.052 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1068134,"total":1141531,"start":1422312177},"progress":"[==============================================\\u003e    ] 1.068 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1084518,"total":1141531,"start":1422312177},"progress":"[===============================================\\u003e   ] 1.085 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1100902,"total":1141531,"start":1422312177},"progress":"[================================================\\u003e  ] 1.101 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1117286,"total":1141531,"start":1422312177},"progress":"[================================================\\u003e  ] 1.117 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1133670,"total":1141531,"start":1422312177},"progress":"[=================================================\\u003e ] 1.134 MB/1.142 MB 0","id":"ea13149945cb"}', '{"status":"Downloading","progressDetail":{"current":1141531,"total":1141531,"start":1422312177},"progress":"[==================================================\\u003e] 1.142 MB/1.142 MB","id":"ea13149945cb"}', '{"status":"Download complete","progressDetail":{},"id":"ea13149945cb"}', '{"status":"Pulling metadata","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Pulling fs layer","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Downloading","progressDetail":{"current":32,"total":32,"start":1422312179},"progress":"[==================================================\\u003e]     32 B/32 B","id":"4986bf8c1536"}', '{"status":"Download complete","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Download complete","progressDetail":{},"id":"4986bf8c1536"}', '{"status":"Status: Downloaded newer image for busybox:latest"}\r\n']
```

Wheras cached build would produce:
```
>>> print [x for x in cli.build(path='/tmp/context')]
['{"stream":"Step 0 : FROM busybox\\n"}\r\n', '{"stream":" ---\\u003e 4986bf8c1536\\n"}\r\n', '{"stream":"Step 1 : ADD true /true\\n"}\r\n', '{"stream":" ---\\u003e Using cache\\n"}\r\n', '{"stream":" ---\\u003e 13d576188811\\n"}\r\n', '{"stream":"Step 2 : CMD /true\\n"}\r\n', '{"stream":" ---\\u003e Using cache\\n"}\r\n', '{"stream":" ---\\u003e e2791e1d42aa\\n"}\r\n', '{"stream":"Successfully built e2791e1d42aa\\n"}\r\n']
```

This could break third-party integration that assume on a stable json schema from `/build` api call.

**Comment by proppy** [comment] 2015-01-27 00:10
Same issue with the CLI:
```
/tmp/context$ docker-1.5.0 --log-level=debug build .
Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon 
Step 0 : FROM busybox
Pulling repository busybox
4986bf8c1536: Download complete 
511136ea3c5a: Download complete 
df7546f9f060: Download complete 
ea13149945cb: Download complete 
Status: Downloaded newer image for busybox:latest
/tmp/context$ docker-1.5.0 --log-level=debug build .
Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon 
Step 0 : FROM busybox
 ---> 4986bf8c1536
Step 1 : ADD true /true
 ---> Using cache
 ---> d538750642b4
Step 2 : CMD /true
 ---> Using cache
 ---> 6f753613ffcc
Successfully built 6f753613ffcc
/tmp/context$ docker-1.5.0 --log-level=debug version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): 7e803ba
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): 7e803ba
```

**Comment by crosbymichael** [comment] 2015-01-27 00:16
ping @jlhawn

**Comment by proppy** [comment] 2015-01-27 00:19
It worth pointing that the daemon does run the build steps the first time, even if it doesn't log them back to the client:

From the daemon logs:
```
time="2015-01-27T00:10:11Z" level="info" msg="-job log(pull, busybox:latest, ) = OK (0)" 
time="2015-01-27T00:10:11Z" level="info" msg="-job pull(busybox, latest) = OK (0)" 
time="2015-01-27T00:10:11Z" level="debug" msg="[BUILDER] Cache miss" 
time="2015-01-27T00:10:11Z" level="debug" msg="CopyFileWithTar(/mnt/sda1/var/lib/docker/tmp/docker-build164672680/true, /mnt/sda1/var/lib/docker/aufs/mnt/36f7ae31a826a1f5ae195f31057191d6f1138e74e809819570c57def78fe702a/true)" 
time="2015-01-27T00:10:11Z" level="debug" msg="[tar autodetect] n: [116 114 117 101 0 0 0 0 0 0]" 
time="2015-01-27T00:10:11Z" level="debug" msg="Skipping excluded path: .wh..wh.aufs" 
time="2015-01-27T00:10:11Z" level="debug" msg="Skipping excluded path: .wh..wh.orph" 
time="2015-01-27T00:10:11Z" level="debug" msg="Skipping excluded path: .wh..wh.plnk" 
time="2015-01-27T00:10:11Z" level="debug" msg="[tar autodetect] n: [116 114 117 101 0 0 0 0 0 0]" 
time="2015-01-27T00:10:11Z" level="debug" msg="[tar autodetect] n: [116 114 117 101 0 0 0 0 0 0]" 
time="2015-01-27T00:10:11Z" level="debug" msg="[BUILDER] Cache miss" 
time="2015-01-27T00:10:12Z" level="debug" msg="Skipping excluded path: .wh..wh.aufs" 
time="2015-01-27T00:10:12Z" level="debug" msg="Skipping excluded path: .wh..wh.orph" 
time="2015-01-27T00:10:12Z" level="debug" msg="Skipping excluded path: .wh..wh.plnk" 
time="2015-01-27T00:10:12Z" level="debug" msg="[tar autodetect] n: [0 0 0 0 0 0 0 0 0 0]" 
time="2015-01-27T00:10:12Z" level="debug" msg="[tar autodetect] n: [0 0 0 0 0 0 0 0 0 0]" 
time="2015-01-27T00:10:12Z" level="info" msg="-job build() = OK (0)" 
```

**Comment by crosbymichael** [comment] 2015-01-27 01:13
@proppy do you have any dockerfiles that we can use as a base for reproducing?

**Comment by proppy** [comment] 2015-01-27 01:26
@crosbymichael yes, it's in the log.
```
FROM busybox
ADD true /true
CMD ["/true"]
```

**Comment by crosbymichael** [comment] 2015-01-27 01:29
Sorry, i didn't see it down at the bottom

**Comment by crosbymichael** [comment] 2015-01-27 01:37
Going to bring @duglin and @erikh in on this.  If you to have any ideas off the top of your head then that would be great, if not i'll continue to look into this and see what is going on.

**Comment by vieux** [comment] 2015-01-27 01:41
I can confirm, I have the same issue: look a this `Dockerfile`

```
FROM busybox
RUN ls
```

If you have busybox already pulled, everything is fine.
If you don't, the `ls` will never be displayed (but executed)

I my guess is, with the new pull code, the build is closed at the end of the pull, so all the writes after fail.

ping @dmcgowan

**Comment by icecrime** [comment] 2015-01-27 01:43
FYI, I tried with #10327 (revert defer close of the progressreader) thinking it might somewhat be related, but it doesn't fix the issue.

Also it's clear that the builder does execute all instructions, only the output is broken.

**Comment by jlhawn** [comment] 2015-01-27 02:32
I've been looking in to this, and I'm testing out a  fix for this now. I think it's due to @dmcgowan's recent change with closing the `engine.Output`.

Here's my theory - cascading close:

The Build job's stdout is used as the stdout to the pull job. A job's stdout is added in a wrapper object (`engine.Output`) and when a job ends `close` is called on this `engine.Output` object which calls `Close()` on the underlying writer if it is a `io.Closer` which *it is* because it is also another `engine.Output` object! This calls `engine.(*Output).Close()` again. This has always happened in the past, but the difference now is that calling `engine.(*Output).Close()` sets the underlying writers list to `nil`. Writes to this `engine.Output` object will now silently fail! Oh man...

**Closed** 2015-01-27 23:09 UTC
Labels: Distribution
