### ISSUE TITLE
no "tag" field for the image when using docker inspect cmd

### ISSUE THREAD

**Issue by meirwah** [docker/docker#9894] opened 2015-01-04 16:20 UTC
When i do "docker inspect" on a contianer , lets say MySql container, with tag of "mysql:5.6.22".
i get in the result , under "Config"/"Image" the image name (mysql).

But i can not find the tag of it's image (5.6.22), any reason why this info is not part of "docker inspect" cmd result ?

**Comment by jfrazelle** [comment] 2015-02-26 23:59
duplicate of https://github.com/docker/docker/issues/5904

**Closed by jfrazelle** 2015-02-26 23:59 UTC
