### ISSUE TITLE
no network access after reboot when iptables=false

### ISSUE THREAD

**Issue by or-shachar** [docker/docker#28811] opened 2016-11-24 19:17 UTC
docker info:
```
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.5 MiB
Name: image-base
ID: 2473:FGJQ:MEEC:CEWY:BSLR:SYB5:EXMO:WJBE:7MMM:DIZH:NJQF:L5NA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

```

I'm trying to run docker with iptables=false (the only configuration I have in daemon.json).
I stop docker daemon and added the daemon configuration, the started the docker daemon.
running the following command worked:
`docker run -it --rm python ping www.google.com`
( so I confirmed I had internet connection).

I took a snaphsot of my iptables (`iptables-save`) and rebooted the system.

Then I ran it again
`docker run -it --rm pyton ping www.google.com`
I failed to get outside network.

I performed `diff` over iptables rules and found the following rules were gone:
```
:PREROUTING ACCEPT [8:496]      
:INPUT ACCEPT [0:0]     
:OUTPUT ACCEPT [0:0]        
:POSTROUTING ACCEPT [0:0]       
:DOCKER - [0:0]     
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER        
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER       
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE      
-A POSTROUTING -s 172.18.0.0/16 ! -o br-a0b355ce53ac -j MASQUERADE      
-A DOCKER -i docker0 -j RETURN      
-A DOCKER -i br-a0b355ce53ac -j RETURN
 # same
:DOCKER - [0:0]     
:DOCKER-ISOLATION - [0:0]
# same
    -A FORWARD -j DOCKER-ISOLATION      
-A FORWARD -o docker0 -j DOCKER     
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT      
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT        
-A FORWARD -i docker0 -o docker0 -j ACCEPT      
-A FORWARD -o br-a0b355ce53ac -j DOCKER     
-A FORWARD -o br-a0b355ce53ac -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT      
-A FORWARD -i br-a0b355ce53ac ! -o br-a0b355ce53ac -j ACCEPT        
-A FORWARD -i br-a0b355ce53ac -o br-a0b355ce53ac -j ACCEPT
# same
    -A DOCKER-ISOLATION -i br-a0b355ce53ac -o docker0 -j DROP       
-A DOCKER-ISOLATION -i docker0 -o br-a0b355ce53ac -j DROP       
-A DOCKER-ISOLATION -j RETURN
```

Even if I restarted docker deamon the rules didn't pop back.
The only way to fix that (while keeping the iptables=false one) was to: 
1.  remove the iptables=false configuration 
1.  restart the daemon
1.  add the configuration back 
1.  restart the daemon yet again. 

I bet this is not an expected behavior.

When I set the iptables to false I want docker to not open the ports of my containers to the outside network (I want the ports to be available to the host as localhost and also to private network (eth1) - rules which I define manually on ufw.

**Comment by thaJeztah** [comment] 2016-11-24 19:52
When setting `--iptables=false` you're telling the docker daemon to not touch your IPTables configuration, because you want to manually manage IPTables rules.

As far as I can see, this is working as designed, but /cc @aboch @mavenugo

**Comment by thaJeztah** [comment] 2016-11-25 12:31
Actually, looks like this is a duplicate of https://github.com/docker/docker/issues/28241, which confirms that this is the correct behavior.

I'll close this issue, but feel free to comment after I closed

**Closed by thaJeztah** 2016-11-25 12:31 UTC
Labels: area/networking, kind/question
