### ISSUE TITLE
Docker image from Dockerfile with war deployed on Tomcat Root Context

### ISSUE THREAD

**Issue by sudhakarbetha** [docker/docker#31380] opened 2017-02-27 11:42 UTC
**Description**
I want to create a Docker image out of Tomcat, by deploying my war (myapp.war) at the Root Context. I dont want to delete the ROOT.war or rename my app to ROOT.war.
Instead if I define the context in tomcat/conf/server.xml as below 

    <Context path="" docBase="myapp"  override="true" reloadable="true" />

It works in a standalone Tomcat Deployment.
However, when I build my Docker image using Dockerfile, it shows me a Tomcat page upon http://localhost:8080/
The context is not getting reloaded upon Running the container.
docker run -p 8080:8080 myapp
Below is my Docker file.

**Steps to reproduce the issue:**
1. Have server.xml as attached in the docker context location, only diff is the addition of the line 
<Context path="" docBase="cloud"  override="true" reloadable="true" />
2. Have myapp.war in the Docker context location
3.Build docker image  using below Dockerfile with the command , `docker build -t myapp:latest .`

```dockerfile
#Dockerfile starts

FROM tomcat:8
COPY ["myapp.war","/usr/local/tomcat/webapps/"]
COPY ["server.xml","/usr/local/tomcat/conf/server.xml"]
CMD ["catalina.sh","run"]
```

**Describe the results you received:**

[server.txt](https://github.com/docker/docker/files/803497/server.txt)
Upon accessing http://localhost:8080/  I am greeted with the Tomcat HomePage rather than the "myapp" page

**Describe the results you expected:**
expected "myapp" home page since the tomcat/conf/server.xml contained 
<Context path="" docBase="myapp"  override="true" reloadable="true" />

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried to start/stop & start tomcat again in the Dockerfile, but that did not help either 
**Output of `docker version`:**
docker -v
Docker version 1.9.1, build a34a1d5

**Output of `docker info`:**
docker info
```
Containers: 1
Images: 39
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:16-9700292-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.377 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105 GB
 Metadata Space Used: 3.125 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /scratch/sbetha/Dockers/images/devicemapper/devicemapper/data
 Metadata loop file: /scratch/sbetha/Dockers/images/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.8.13-44.1.1.el6uek.x86_64
Operating System: <unknown>
CPUs: 4
Total Memory: 14.07 GiB
Name: den00rni
ID: J3V3:45ZX:W4FX:SAGY:2Y6L:NKI6:F3VO:O4Y7:KRKT:LFX6:VPXJ:SE4L
Username: sudhakarbetha
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-02-27 11:51
@sudhakarbetha thanks for opening, but please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For questions about _running_ docker, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

Also note that;

- docker 1.9.1 is EOL, and no longer maintained
- you're running docker on a 3.8 kernel; the minimum kernel version required to run docker is 3.10

I'm going to close this issue because this is a support question, not a bugreport, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-02-27 11:51 UTC
Labels: area/builder, kind/question
