### ISSUE TITLE
[1.8.1]: ^C on pull broken

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#15589] opened 2015-08-14 17:08 UTC
^C on a pull is unrecoverable, and does not even show the message "layer being pulled by another client"

**Comment by andyh2** [comment] 2015-08-14 20:17
I think this is a dupe of #6928

**Comment by jfrazelle** [comment] 2015-08-14 20:20
this is a regression

**Comment by hekaldama** [comment] 2015-08-17 17:47
Is this a "good first bug"?

**Comment by calavera** [comment] 2015-08-17 18:02
@hekaldama probably not. The distribution code is rather tricky.

**Comment by hekaldama** [comment] 2015-08-17 20:08
@calavera okay. Thanks for the reply. Will keep looking for stuff to work on.

**Closed** 2015-08-27 15:54 UTC
Labels: group/distribution, kind/bug
