### ISSUE TITLE
manually stopping a container should invalidate auto-restart policy

### ISSUE THREAD

**Issue by avinson** [docker/docker#13275] opened 2015-05-16 10:44 UTC
When a container is manually stopped, it should invalidate the auto-restart policy. This is an operational headache that we have encountered many times. 

The typical scenario is as follows: a container is manually stopped (likely to push a new version) and then, sometime later, the host is rebooted for a kernel upgrade or the docker daemon is upgraded. As an unintended result, these containers get automatically started. The intention of the operator is to stop the container forever or until it is manually started again. As such, the auto-restart policy should be invalidated in these cases.

**Comment by thaJeztah** [comment] 2015-05-16 11:19
@avinson thanks for reporting. I think this is a duplicate of https://github.com/docker/docker/issues/11008 so I'm going to close this issue.

Please continue the discussion on https://github.com/docker/docker/issues/11008

**Closed by thaJeztah** 2015-05-16 11:19 UTC
