### ISSUE TITLE
Error restoring container from checkpoint: "No parent found for mountpoint"

### ISSUE THREAD

**Issue by tswift242** [docker/docker#31663] opened 2017-03-08 21:55 UTC
**Description**

Very sporadically, I get the following type of error when trying to restore a container from a checkpoint, which causes the restore to fail:

"Error (criu/mount.c:360): mnt: No parent found for mountpoint 574 (@./var/lib/docker/checkpoints/test_cp/criu.work/restore-2017-03-08T15:12:42Z/.criu.cgyard.fnEP8f/systemd)"

The full criu restore.log is attached.

[restore.txt](https://github.com/docker/docker/files/829057/restore.txt)

It seems to sporadically happen when I restore several containers from the same checkpoint at the same time. The issue reproduced 8/720 times when I ran the following script, which just starts and stops a bunch of simple Ubuntu containers over and over (renamed to satisfy github):

[stress_cr_simple_start_stop.txt](https://github.com/docker/docker/files/829065/stress_cr_simple_start_stop.txt)

I gave the script the following parameters: ```./stress_cr_simple_start_stop.sh 10 720```; this will go through 720 rounds of restoring 10 containers at a time from the same checkpoint.

I wonder if this has anything to do with the way docker assigns the criu work dir for each restore. Docker creates a separate work directory for each restore; the directory names are differentiated with a datetimestamp with second precision. So, this means that if docker makes 2+ restore calls to criu within a second, the work dir for those restores could be the same. As an example, when I ran the script above for 720 runs with 10 concurrent restores at a time (7200 restores total), there were only 1087 different work directories created. The path that the criu error cites appears to be an ephemeral path that is created during the restore and which sits inside the work dir. If there are multiple concurrent restores happening for the same checkpoint, it therefore seems possible that they could be stepping on each others' toes if they are using the same work dir.

**Steps to reproduce the issue:**
1. ```./stress_cr_simple_start_stop.sh 10 720``` (can be a smaller number than 720, but should probably be at least 100)
2. Observe restore failures during script execution, or grep for them afterward: ```grep -l "Error" /var/lib/docker/checkpoints/test_cp/criu.work/**/*```

**Describe the results you received:**

Restore fails with message like "Error (criu/mount.c:360): mnt: No parent found for mountpoint 574 (@./var/lib/docker/checkpoints/test_cp/criu.work/restore-2017-03-08T15:12:42Z/.criu.cgyard.fnEP8f/systemd)"

**Describe the results you expected:**

Restores should always succeed, especially for a basic Ubuntu container.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:57:58 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:57:58 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 27
Server Version: 17.03.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.10.1-041001-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 120.1 GiB
Name: ip-10-97-0-35
ID: PBSJ:KR3H:XP7F:KQMN:CFJS:J75A:ZGUM:ZSC3:5DUR:MCZJ:5ACD:CXM7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using AWS and criu 2.11.

**Comment by tswift242** [comment] 2017-03-08 21:57
cc @boucher and @xemul

**Comment by tswift242** [comment] 2017-03-09 16:29
Something interesting to note is that every time I've seen this failure, it always complains about a systemd path, i.e. the path in the criu error is always of the form /var/lib/docker/checkpoints/test_cp/criu.work/restore-<timestamp>/.criu.cgyard.<id>/systemd

**Comment by boucher** [comment] 2017-03-09 16:37
We should probably change the naming strategy to eliminate the concurrency issue, regardless of whatever else might be causing this. 

I did notice that there are 2 other failures in that log file as well, I'm not sure which are the most relevant:

```
(00.972837) Error (criu/mount.c:2798): mnt: Can't remount root with MS_PRIVATE: Invalid argument
```

```
(00.972861) Error (criu/mount.c:2808): mnt: Can't unmount /tmp/.criu.mntns.eFYx0x: Invalid argument
```

As an aside, I see a higher rate of failure than this in my current production setup, but haven't spent much time digging into the issues.

**Comment by tswift242** [comment] 2017-03-09 16:40
Yea I think we should definitely change the naming strategy for the work dir. Seems like a low effort, low risk change. If we gave the name's timestamp precision a couple more orders of magnitude, that might be good enough. Possibly something in the 1-100 microsecond range; nanoseconds might be overkill.

**Comment by boucher** [comment] 2017-03-09 16:48
Here's the line that generates the path:
https://github.com/docker/containerd/blob/docker-1.13.x/containerd-shim/process.go#L141

There's no real reason not to just use something like a uuid, or even just this plus a random number, if that's easy to generate in this context.

**Comment by tswift242** [comment] 2017-03-09 16:56
Yea those are both good ideas. The timestamp information in the name can be helpful, especially cause criu logs only have relative timestamps. So I think the latter option might be better.

**Comment by boucher** [comment] 2017-03-09 16:59
Yeah, though the timestamp is ultimately also in the filesystem metadata.

**Comment by tswift242** [comment] 2017-03-09 17:00
That's true. Either suggestion works for me. Just some way to prevent collisions between concurrent restores.

**Comment by krasi-georgiev** [comment] 2017-03-12 12:35
@boucher , @tswift242 I will try to troubleshoot this one and submit a pull request.

**Comment by tswift242** [comment] 2017-03-13 13:17
Thanks @krasi-georgiev!

**Comment by krasi-georgiev** [comment] 2017-03-21 15:47
I tried with the extended naming, but seems the problem is a bit deeper so now reading more how criu and runc works.

the error is different , but seems that it is hitting the same bug



```
(00.370975)      1: 	type aufs source none mnt_id 618 s_dev 0x51 / @ ./run/runc/ac919d200cc07801fce44794c2da8e6b2745c0feb91b2d6ebb722de1a9f46c03/criu-root flags 0x200000 options si=641a382974da1e24,dio,dirperm1
(00.370995)      1: mnt: Building mountpoints tree
(00.371003)      1: mnt: 	Building plain mount tree
(00.371008)      1: mnt: 		Working on 618->246
(00.371012)      1: mnt: 		Working on 617->246
(00.371017)      1: mnt: 		Working on 616->246
(00.371026)      1: mnt: 		Working on 615->246
(00.371030)      1: mnt: 		Working on 614->246
(00.371034)      1: mnt: 		Working on 613->246
(00.371039)      1: mnt: 		Working on 612->246
(00.371043)      1: mnt: 		Working on 611->246
(00.371046)      1: mnt: 		Working on 610->246
(00.371054)      1: mnt: 		Working on 609->246
(00.371057)      1: mnt: 		Working on 608->594
(00.371060)      1: mnt: Mountpoint 608 (@./var/lib/docker/checkpoints/test_cp/criu.work/restore-2017-03-21T15:05:45.15958466Z/.criu.cgyard.Nur73w/systemd) w/o parent 594
(00.371063)      1: Error (criu/mount.c:414): mnt: No root found for mountpoint 608 (@./var/lib/docker/checkpoints/test_cp/criu.work/restore-2017-03-21T15:05:45.15958466Z/.criu.cgyard.Nur73w/systemd)
(00.430835) Error (criu/cr-restore.c:1018): 30973 killed by signal 9: Killed
(00.540756) mnt: Switching to new ns to clean ghosts
(00.540806) Error (criu/cr-restore.c:1895): Restoring FAILED.
```

**Comment by xemul** [comment] 2017-03-21 16:32
Ccing @avagin

**Comment by krasi-georgiev** [comment] 2017-03-21 22:13
full log here
https://gist.github.com/krasi-georgiev/9acd66fa2dbdc6249d7383f62a2416fa

**Comment by avagin** [comment] 2017-03-22 22:32
It's a known criu issue. When you run two criu-s concurrently, one of them collects mounts, but another one umounts a temporary mount, so the first one can't build a mount tree. We will fix it in a near future.

**Comment by xemul** [comment] 2017-03-23 03:54
@avagin would you create an issue on xemul/criu for that and add a link here?

**Comment by tswift242** [comment] 2017-03-23 13:40
Thanks @avagin. It'd be awesome it this got fixed soon.

@krasi-georgiev Even though the root cause of this issue may be a criu bug, it still seems like we should change the work dir naming scheme to make sure the dir is unique for each restore, to ensure that restores are isolated. Would you minding submitting a PR for that?

**Comment by krasi-georgiev** [comment] 2017-03-23 20:42
@tswift242 good idea , here it is

https://github.com/docker/containerd/pull/657

**Comment by xemul** [comment] 2017-03-27 18:51
Should be fixed in 2.12.1 (released today)

**Comment by tswift242** [comment] 2017-03-27 19:37
Thanks for the quick turnaround @xemul @avagin !

And thanks for opening that PR @krasi-georgiev

**Comment by tswift242** [comment] 2017-03-31 13:26
@krasi-georgiev Looks like that PR got merged. Thanks! Any chance you'd be willing to help get the containerd change into docker?

**Comment by krasi-georgiev** [comment] 2017-03-31 21:53
@tswift242 good new I upgraded criu to 2.12.1 and updated containerd and now your script runs without any errors.

**Closed** 2017-04-02 09:02 UTC
Labels: kind/bug, kind/experimental, version/17.03

**Comment by tswift242** [comment] 2017-04-03 13:44
Thanks for all your help @krasi-georgiev !

**Comment by krasi-georgiev** [comment] 2017-04-03 23:02
@tswift242 thanks , I will keep it coming :)
