### ISSUE TITLE
aufs fails with large log files

### ISSUE THREAD

**Issue by mohan08p** [docker/docker#19922] opened 2016-02-02 15:37 UTC
aufs is not mainstream with the kernel and it doesn't tackle the changes into the kernel. So, the large packs of submission is broken, huge, and did not cope with the base. 
The problem is why the aufs is not good to add into the large log files ? I been playing with the situations where I make changes to the log files and commit them back. Once, committed.. they no longer be a read only layer. And, when I restart the container, the write layer gets added onto the top again. I need to copy that file again. So, that the copying essentially kills the process. In larger log files, even these bunch of copying spawn out. 
Is there better solution or alternative for the certain environment ? I am running on my ubuntu machine.

Sign-off by : Mohan Pawar
mohanpawary1990@gmail.com

**Comment by thaJeztah** [comment] 2016-02-02 18:31
Please keep in mind that the github issue tracker is not a general support forum, but meant for tracking bugs and feature requests in docker.

Please use one of the below;
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.
4) StackOverflow (https://stackoverflow.com)


I'm going to close this issue, because this is not a bug or feature request, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-02-02 18:31 UTC

**Comment by mohan08p** [comment] 2016-02-03 10:21
Alright. Thanks @thaJeztah .
