### ISSUE TITLE
Docker ps slow to return for 50 containers

### ISSUE THREAD

**Issue by icecrime** [docker/docker#13864] opened 2015-06-10 22:25 UTC
Feedback received by mail:

> After running for about 2 days, 1.7.0-RC2 takes about 8 seconds to return from docker ps with 50 containers running.

**Comment by jfrazelle** [comment] 2015-06-10 22:59
ya im seeing if this is the case for our servers

**Comment by jfrazelle** [comment] 2015-06-10 23:02
ya its not :(

**Comment by icecrime** [comment] 2015-06-11 00:07
Getting back to the tester for more information: it's not easily reproduced, and `ps` had no significant changes since 1.6.0.

**Comment by cpuguy83** [comment] 2015-06-11 01:06
@icecrime other than engine removal :trollface:

**Comment by icecrime** [comment] 2015-06-11 02:16
![image](https://cloud.githubusercontent.com/assets/1564054/8098460/2c0d7df8-0fa5-11e5-99de-3935c96ff05b.png)

**Comment by LK4D4** [comment] 2015-06-11 03:03
Anything could slow ps, ps is like indicator that something wrong. I think it should be reproducible by hour of docker-stress with right arguments. Maybe our sqlite db grows uncontrollably, who knows...

**Comment by icecrime** [comment] 2015-06-12 17:54
Removing from milestone until (if) we get more information.

**Comment by unclejack** [comment] 2015-06-15 11:45
This issue is very hard to look into without the usual information we request: `docker info`, `docker version` and `uname -a`.

There could be multiple causes behind Docker becoming slow and 99% of those have nothing to do with Docker.

**Comment by jfrazelle** [comment] 2015-07-10 21:52
should we even still keep this open

**Comment by cpuguy83** [comment] 2015-08-17 14:31
Closing since there isn't anything we can do with this w/o more detailed info.

**Closed by cpuguy83** 2015-08-17 14:31 UTC
Labels: status/more-info-needed
