### ISSUE TITLE
Offtopic: invitation to gentoobb project discussion, which uses Docker as engine

### ISSUE THREAD

**Issue by UralZima** [docker/docker#31770] opened 2017-03-12 20:45 UTC
Hello guys. I am sorry about a bit of offtopic, but if everyone is interested, I am inviting anyone into https://github.com/edannenberg/gentoo-bb project discussion thread here: https://github.com/edannenberg/gentoo-bb/issues/102, where we user Docker as engine, that powers everything. We have some ideas on (possibly) the best server and LAMP/LEMP management using Docker and GentooBB for High-Load secure servers. Thanks

**Comment by thaJeztah** [comment] 2017-03-12 21:17
Please keep in mind that the GitHub issue tracker is not intended as a general support or discussion forum, but for reporting bugs and feature requests. For other type of discussions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack

I'm going to close this issue because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2017-03-12 21:17 UTC

**Comment by UralZima** [comment] 2017-03-12 21:49
Sorry, continuing here: https://forums.docker.com/t/invitation-to-gentoobb-project-and-a-success-story/29667
