### ISSUE TITLE
Can't free space for files used COPY or ADD in Dockerfile

### ISSUE THREAD

**Issue by gavincook** [docker/docker#17855] opened 2015-11-10 06:19 UTC
When use `COPY` or `ADD` instruction in Dockerfile to copy files from host to images.  But when removed the copied file, it would not free the space.

I tested this in two ways:

### 1. do `rm` in Dockerfile
* Dockerfile
```
FROM ubuntu:14.04

MAINTAINER gavincook <swbyzx@gmail.com>

COPY jdk.tar.gz test.tar.gz

RUN rm -f jdk.tar.gz
```
_Comment: the jdk.tar.gz in my local is 154MB_
Then i build image based on this Dockerfile, then the image size is: 349.3MB, while the ubuntu:14.04 image only 188.4MB. So it not free the space really when do `rm` operation.

### 2. do `rm` in interactive container
* Dockerfile
```
FROM ubuntu:14.04

MAINTAINER gavincook <swbyzx@gmail.com>

COPY jdk.tar.gz jdk.tar.gz
```
build image in `docker build -t test .`, then run interactive container: `docker run --rm -it test /bin/bash`, i typed `df -h` in the interactive container, got:
```
Filesystem      Size  Used Avail Use% Mounted on
rootfs          9.8G  7.2G  2.1G  78% /
none            9.8G  7.2G  2.1G  78% /
tmpfs           3.9G     0  3.9G   0% /dev
shm              64M     0   64M   0% /dev/shm
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/xvdb1      9.8G  7.2G  2.1G  78% /etc/hosts
tmpfs           3.9G     0  3.9G   0% /proc/kcore
tmpfs           3.9G     0  3.9G   0% /proc/latency_stats
tmpfs           3.9G     0  3.9G   0% /proc/timer_stats
```
`ls -Shall` got:
```
-rw-r--r--   1 root root 154M Sep  2 10:43 jdk.tar.gz
drwxr-xr-x  34 root root 4.0K Nov 10 06:07 .
drwxr-xr-x  34 root root 4.0K Nov 10 06:07 ..
drwxr-xr-x   2 root root 4.0K Aug 14 08:34 bin
drwxr-xr-x   2 root root 4.0K Apr 10  2014 boot
drwxr-xr-x  64 root root 4.0K Nov 10 06:07 etc
drwxr-xr-x   2 root root 4.0K Apr 10  2014 home
drwxr-xr-x  12 root root 4.0K Aug 14 08:33 lib
drwxr-xr-x   2 root root 4.0K Aug 14 08:33 lib64
drwxr-xr-x   2 root root 4.0K Aug 14 08:32 media
drwxr-xr-x   2 root root 4.0K Apr 10  2014 mnt
drwxr-xr-x   2 root root 4.0K Aug 14 08:32 opt
drwx------   2 root root 4.0K Aug 14 08:34 root
drwxr-xr-x   7 root root 4.0K Aug 14 08:33 run
drwxr-xr-x   2 root root 4.0K Aug 20 20:21 sbin
drwxr-xr-x   2 root root 4.0K Aug 14 08:32 srv
drwxrwxrwt   2 root root 4.0K Aug 14 08:34 tmp
drwxr-xr-x  11 root root 4.0K Aug 20 20:21 usr
drwxr-xr-x  12 root root 4.0K Aug 20 20:21 var
drwxr-xr-x   5 root root  380 Nov 10 06:07 dev
-rwxr-xr-x   1 root root    0 Nov 10 06:07 .dockerenv
-rwxr-xr-x   1 root root    0 Nov 10 06:07 .dockerinit
dr-xr-xr-x 158 root root    0 Nov 10 06:07 proc
dr-xr-xr-x  13 root root    0 Nov 10 06:07 sys
```
Then use `rm -f jdk.tar.gz` to delete the jdk.tar.gz, use `ls -Shall`, got:
```
drwxr-xr-x  34 root root 4.0K Nov 10 06:10 .
drwxr-xr-x  34 root root 4.0K Nov 10 06:10 ..
drwxr-xr-x   2 root root 4.0K Aug 14 08:34 bin
drwxr-xr-x   2 root root 4.0K Apr 10  2014 boot
drwxr-xr-x  64 root root 4.0K Nov 10 06:07 etc
drwxr-xr-x   2 root root 4.0K Apr 10  2014 home
drwxr-xr-x  12 root root 4.0K Aug 14 08:33 lib
drwxr-xr-x   2 root root 4.0K Aug 14 08:33 lib64
drwxr-xr-x   2 root root 4.0K Aug 14 08:32 media
drwxr-xr-x   2 root root 4.0K Apr 10  2014 mnt
drwxr-xr-x   2 root root 4.0K Aug 14 08:32 opt
drwx------   2 root root 4.0K Aug 14 08:34 root
drwxr-xr-x   7 root root 4.0K Aug 14 08:33 run
drwxr-xr-x   2 root root 4.0K Aug 20 20:21 sbin
drwxr-xr-x   2 root root 4.0K Aug 14 08:32 srv
drwxrwxrwt   2 root root 4.0K Aug 14 08:34 tmp
drwxr-xr-x  11 root root 4.0K Aug 20 20:21 usr
drwxr-xr-x  12 root root 4.0K Aug 20 20:21 var
drwxr-xr-x   5 root root  380 Nov 10 06:07 dev
-rwxr-xr-x   1 root root    0 Nov 10 06:07 .dockerenv
-rwxr-xr-x   1 root root    0 Nov 10 06:07 .dockerinit
dr-xr-xr-x 158 root root    0 Nov 10 06:07 proc
dr-xr-xr-x  13 root root    0 Nov 10 06:07 sys
```
It seems the jdk.tar.gz already deleted, but when i use `df -h`, i got:
```
Filesystem      Size  Used Avail Use% Mounted on
rootfs          9.8G  7.2G  2.1G  78% /
none            9.8G  7.2G  2.1G  78% /
tmpfs           3.9G     0  3.9G   0% /dev
shm              64M     0   64M   0% /dev/shm
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/xvdb1      9.8G  7.2G  2.1G  78% /etc/hosts
tmpfs           3.9G     0  3.9G   0% /proc/kcore
tmpfs           3.9G     0  3.9G   0% /proc/latency_stats
tmpfs           3.9G     0  3.9G   0% /proc/timer_stats
```
The space status is same before we do rm jdk.tar.gz , Why the space for jdk.tar.gz file space not freed?

BTW, here are something about my enviroment:

`docker version`:
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 8
Images: 185
Storage Driver: aufs
 Root Dir: /mnt/docker/aufs
 Backing Filesystem: extfs
 Dirs: 201
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 7.797 GiB
Name: iZ238zkde0vZ
ID: PBCE:ENDQ:IBFB:IEN5:SEWL:44WY:NDTP:T7D6:I5MV:X2ZZ:DPEQ:HNFS
Username: gavincook
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

`uname -a`:
```
Linux iZ238zkde0vZ 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by phemmer** [comment] 2015-11-10 13:29
See https://docs.docker.com/engine/introduction/understanding-docker/#how-does-a-docker-image-work

Once an image layer is created, you can't modify it. Modifying the contents of the filesystem just creates a new layer on top of the old one.

**Comment by thaJeztah** [comment] 2015-11-10 13:38
Yes, this is expected behavior, but I understand it's confusing if you're unfamiliar with the way the layers work in Docker.

I'm closing this issue, because it's not a bug, but feel free to comment her after I've closed.

**Closed by thaJeztah** 2015-11-10 13:38 UTC
