### ISSUE TITLE
docker volume inspect doesn't do partial ID matching

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#26346] opened 2016-09-06 20:52 UTC
This may be entirely by design, but I noticed it a year or so back when implementing volume support on Windows, made a note of it, then forgot about it :blush:. However, someone else just pointed it out to me. Turns out it's not Windows specific - just tried on Ubuntu 16.04 running docker master.

For example, `docker volume create john`, followed by `docker volume inspect jo` won't match `john`. Similarly, `docker run -it -v /something ubuntu sh`, then `docker volume ls` to get the volume ID, and `docker volume inspect <first few characters>` will fail.

Unless completely by design, there's a couple of solutions. One is to do exactly as the daemon does for completion of container IDs. The second is to add a parameter to docker volume inspect such as `-match` to do regex/starting-with type matching on the volume ID.

Happy to do the work if it's something not explicitly by design. @cpuguy83 WDYT? Thx.

**Comment by cpuguy83** [comment] 2016-09-06 20:58
AFAIK not by design, just not implemented.

Definitely would prefer to keep consitency with the daemon in terms of implementation...
However, I'd prefer to not use the go-patricia stuff like we do for containers since I'm planning on removing it: https://github.com/docker/docker/compare/master...cpuguy83:container_memdb#diff-a37b8575a56776d92490e19c7381a379R90

**Comment by icecrime** [comment] 2016-09-07 16:55
In an ideal world, containers, images, network, and volumes would only have ID, and some centralized subsystem would take care of naming, partial ID matching, and possibly even labeling, in a consistent and localized way. *\</IHaveADream\>*

**Comment by bbayani** [comment] 2016-09-22 13:46
#13697 Can I take this issue up? Just a beginner, looks like its a low impact, beginner-level issue. Can I give it a try to fix it?

**Comment by thaJeztah** [comment] 2016-09-22 13:50
@bbayani sure, go ahead!

**Comment by bbayani** [comment] 2016-10-12 13:05
Raised PR#27317. Can someone please review? Thanks!

**Comment by thaJeztah** [comment] 2016-12-15 20:25
Closing this one per https://github.com/docker/docker/pull/27317#issuecomment-267414178

Thanks so much @bbayani, and apologies that your PR got closed

**Closed by thaJeztah** 2016-12-15 20:25 UTC
Labels: area/cli, exp/intermediate, kind/enhancement
