### ISSUE TITLE
Error image operating system "linux" cannot be used on this platform on Windows 10

### ISSUE THREAD

**Issue by happysysadm** [docker/docker#27668] opened 2016-10-23 14:08 UTC
I am unable to run a linux container (like Ubuntu) on a windows 10 host.

`docker run ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
C:\Program Files\Docker\docker.exe: image operating system "linux" cannot be used on this platform.
See 'C:\Program Files\Docker\docker.exe run --help'.`

**docker version**
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   95c36b3
 Built:        Fri Oct 21 17:13:27 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   95c36b3
 Built:        Fri Oct 21 17:13:27 2016
 OS/Arch:      windows/amd64

**docker info**
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 2
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: l2bridge l2tunnel nat nat null null transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows 10 Enterprise N 2016 LTSB
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.88 GiB
Name: win10pc
ID: PAU2:6PDB:FU47:KCOP:XDWO:EZ3B:KD3E:26HQ:FLY3:EI23:AWLU:SFO7
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**
My environment is a physical Windows 10 version 1607 (build 14393.321).

**Comment by thaJeztah** [comment] 2016-10-23 19:16
This is expected, but I can see the confusion.

On Windows, you can either run _native_ Windows containers (e.g. to run IIS inside a container), or Linux containers. Docker Containers are not a virtualization technology, I.e, containers are not Virtual Machines, and should be seen as isolated _processes_. Containers share the kernel of the host, so if you're running native Windows containers, it allows you to run _Windows_ processes, and Linux containers allow you to run _Linux_ processes.

Having said that; If you install "Docker for Windows", that software installs a thin VM that allows you to run Linux containers, on Windows. https://docs.docker.com/docker-for-windows/. Docker for Windows also has a beta feature that allows you to switch between "Linux" containers and "Native Windows" containers if your host supports native Windows containers; https://docs.docker.com/docker-for-windows/#/switch-between-windows-and-linux-containers-beta-feature

Docker for Windows (which is not installed by default on Windows, but follow those links for installation instructions) therefore give you the best of both worlds; you can use both, depending on your use case.

I'll close this issue, as it's not a bug, but feel free to continue the conversation, perhaps you have suggestions how we can improve the documentation to make this less confusing!

**Closed by thaJeztah** 2016-10-23 19:16 UTC
Labels: version/master

**Comment by thaJeztah** [comment] 2016-10-23 19:18
Let me /cc @londoncalling @mstanleyjones for the documentation

**Comment by happysysadm** [comment] 2016-10-23 21:01
@thaJeztah I am aware of the difference between VMs and containers and I am also aware of the 'kernel matching' requirement. I was just under the wrong impression that running a container in hyper-v isolation mode on my Windows 10 allowed to me to run a different kernel, probably because I read that hyper-v container = "highly optimized virtual machine" (see 2. Windows Containers Types [here](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start)). The bad habit of thinking that everything is a VM is hard to dismiss. Sorry for opening an issue here.

**Comment by thaJeztah** [comment] 2016-10-23 21:05
No problem at all, we clearly need to improve the docs on this one, as it's confusing people. It's a tough one to describe properly though

**Comment by mstanleyjones** [comment] 2016-10-24 21:16
I'm confused by your environment. Are you running Docker for Windows or some other Docker daemon binary?

**Comment by thaJeztah** [comment] 2016-10-24 21:20
@mstanleyjones this is on Windows (not "Docker for Windows"), so `docker run` expects a Windows image

**Comment by andreibaptista** [comment] 2018-01-29 14:15
Run 

> & 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon
