### ISSUE TITLE
In run command, ro option in --volume doesn't work in the sub-directory which is existing before mount

### ISSUE THREAD

**Issue by zhjunwei** [docker/docker#9722] opened 2014-12-18 07:11 UTC
Here is the scenario:
1) On one node, some sub-directories and files are already put under one dir: dir1;
2) On that node, a container is created, and the dir1 is attached as a volume ( --volume /dir1:/dir1:ro) into the container, for security reason, read only mode is set so the application inside the container should not be able to do any modification or deletion under /dir1 and its sub-directories;

But I find, inside the container, readonly only takes effective under /dir1, if I goes into the sub-directories (which is created on host) of /dir1, readonly doesn't work.

I am not sure if this is by design or a bug, but in some scenarios, it's really useful to forbid any change to the directory and its sub-directories attached into the container. Or maybe it's better to offer another option ro(--recursive).

**Comment by jfrazelle** [comment] 2015-02-26 05:54
can you give the exact commands you run thanks

**Comment by cpuguy83** [comment] 2015-02-26 15:53
I can repro, this seems to be how rbinds work and is reproducible as such:

```bash
~/: mkdir test
~/: mkdir test2
~/: mkdir test3
~/: mkdir test/test2
~/: sudo mount --bind test2 test/test2
~/: sudo mount --rbind test test3
~/: sudo mount -o remount,ro test3
~/: touch test3/foo
touch: cannot touch ‘foo’: Read-only file system
~/: touch test3/test2/foo
~/:
```

**Comment by cpuguy83** [comment] 2015-02-26 15:56
I'm not sure this is something we can really fix.
If you want the sub-mounts to be ro, you'll need to do it on the host.

**Comment by jfrazelle** [comment] 2015-02-28 03:17
if its not something we can fix can we close this :/

**Comment by cpuguy83** [comment] 2015-02-28 13:00
Yes I think let's close this.
If someone is seeing this they'll come to this issue. If we can find a good way to resolve this without disabling rbinds please post here and we'll discuss.

**Closed by cpuguy83** 2015-02-28 13:00 UTC
