### ISSUE TITLE
Error: no available IPv6 addresses on this network's address pools

### ISSUE THREAD

**Issue by alpo** [docker/docker#21967] opened 2016-04-12 20:59 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 222
Images: 36
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.6-coreos
Operating System: CoreOS 899.15.0
CPUs: 16
Total Memory: 31.47 GiB
Name: something
ID: 5GNN:MBJE:VTQ6:AUVN:CWMI:FKEH:NWZ7:C3OA:3GST:6E6A:RCD4:NW3V
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

DOCKER_OPTS=--ipv6=true --fixed-cidr-v6=something/80 --userland-proxy=false

Unit files (nothing special)
```
[Unit]
Description=blah
After=docker.service
Requires=docker.service
[Service]
TimeoutStartSec=0
RestartSec=60
Restart=always
ExecStartPre=-/usr/bin/docker kill blah1
ExecStartPre=-/usr/bin/docker rm blah1
ExecStart=/usr/bin/docker run --name blah1 --dns blabla --publish blabla ownimages/blablabla
ExecStop=/usr/bin/docker stop blah1
[Install]
WantedBy=agents.target
```

**Steps to reproduce the issue:**
1. Create ~200 containers with launch via systemd units.
2. Launch containers

**Describe the results you received:**

Part of containers failed to launch with error message 
```
Error: no available IPv6 addresses on this network's address pools
```

**Describe the results you expected:**

Successful launch

**Additional information you deem important (e.g. issue happens only occasionally):**

```docker ps``` hangs. After command ```sudo systemctl restart docker``` the docker daemon becomes a zombie process and only reboot helps to restore docker 'working'.

```docker network inspect bridge``` sometime works, sometime gives error: "An error occurred trying to connect: Get http:///var/run/docker.sock/v1.21/networks/bridge: EOFnull"

**Comment by aboch** [comment] 2016-04-12 21:10
Likely a duplicate of #18527

**Comment by thaJeztah** [comment] 2016-04-15 23:10
@alpo this issue should be resolved in docker 1.10.x and above. Can you test if you're still able to reproduce this on docker 1.10 or 1.11?

**Comment by alpo** [comment] 2016-04-17 19:23
@thaJeztah After migration to CentOS 7 with  docker 1.9.1 and CoreOS alpha 1010.1.0 with docker 1.10.3 no more weird messages and deadlocks in both cases.

**Comment by mavenugo** [comment] 2016-10-19 18:42
Closing this based on the above comment.

**Closed by mavenugo** 2016-10-19 18:42 UTC
Labels: area/networking, status/more-info-needed, version/1.9
