### ISSUE TITLE
tup - fuse: failed to open /dev/fuse: Operation not permitted

### ISSUE THREAD

**Issue by JendaPlhak** [docker/docker#13287] opened 2015-05-17 21:03 UTC
Hi, 
I would like to use tup to build my project in docker. Bud when docker build executes `RUN tup build/f` I obtain error message 

    fuse: failed to open /dev/fuse: Operation not permitted
    tup error: Timed out waiting for the FUSE file-system to be ready.
    tup error: Unable to mount FUSE on .tup/mnt

The build command I use `sudo docker build --file Dockerfile.search -t bileto/jp-search:production .`. I am unable to find anything useful on this topic. So my question is, is this a bug? Or am I doing it wrong?

**Comment by thaJeztah** [comment] 2015-05-17 22:49
Could you add the requested information above, also some more information on the Dockerfile you're trying to build could be useful.

However, there are actually a number of existing issues on this: https://github.com/docker/docker/issues?utf8=✓&q=is%3Aissue+fuse+in%3Atitle

So this could well be a duplicate of an existing issue (also see https://github.com/docker/docker/issues/10184)

IIRC, using Fuse requires additional privileges, which are not available during build (see https://github.com/docker/docker/issues/1916), which could be the cause of this particular problem

**Comment by cpuguy83** [comment] 2015-05-18 13:56
You can't mount any filesystems during `docker build`, and it looks like you are trying to do a `mount -t fuse`.
The `mount` command requires `CAP_SYS_ADMIN` which is not available during build.

**Comment by JendaPlhak** [comment] 2015-05-19 19:51
Actually I use Tup, which uses fuse somehow. I don't really know how. However, issue #1916 seems to address this problem and as I understood there is pull request pending fixing this issue. I will therefore just wait for it to be approved.

Though being unable to use fuse (mount) during build seems to be a bit... Unnecessary.

**Comment by cpuguy83** [comment] 2015-05-19 19:55
Unfortunately linux caps are not the most granular. In order to mount you need CAP_SYS_ADMIN, which  is like 60% of all root privileges on a host. One could easily break out of a container with it.

I'm going to close this since it's not really a docker issue and is covered by other issues, such as the one you mentioned.

**Closed by cpuguy83** 2015-05-19 19:55 UTC
