### ISSUE TITLE
creating custom image from local installation

### ISSUE THREAD

**Issue by itsdpk** [docker/docker#19016] opened 2015-12-31 12:07 UTC
Hi i am trying to create a new image from my local jboss wildfly installation, can i tar it up and import as a docker image ? or how should this be made possible.

I had tried to tar and import, though the image was created i was getting error while running the image.
Error response from daemon: could not find command

Tried creating a dockerfile from scratch but while i build the same it was breaking on RUN with
[8] System error: exec: "/bin/sh": stat /bin/sh: no such file or directory
contents of dockerfile added below
FROM scratch 
RUN 	tar xf ./wildfly.tar \
   		 && mv wildfly  /opt/jboss/wildfly 
ENV LAUNCH_JBOSS_IN_BACKGROUND true
EXPOSE 8080
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]

any help would be much appreciated

thanks

**Comment by itsdpk** [comment] 2015-12-31 12:13
docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

docker info
Containers: 2
Images: 0
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-22-generic
Operating System: Ubuntu 15.10
CPUs: 1
Total Memory: 1.954 GiB
Name: Lubuntu-VirtualBox
ID: MG4O:PTR3:43RJ:GC53:FRTK:IPHF:DQTM:DU7L:NH64:2C32:NQ5W:NMHU
WARNING: No swap limit support

i am running this in virtualbox v 5.0.8

**Comment by thaJeztah** [comment] 2015-12-31 13:23
Looks like you're missing some steps; `FROM scratch` literally means; start with an empty directory, no bin/sh etc. `FROM scratch` can be useful to create a minimal image (e.g., only containing a statically linked binary, such as the [hello-world](https://github.com/docker-library/hello-world) image). Things get a [lot more complicated](https://github.com/tianon/docker-brew-ubuntu-core/blob/8af9ba31ba5d204717f9aff66c9c033454d72ba5/xenial/Dockerfile) if you want to use it for something like wildly, which will depend on other things to exist in the image. (I see you're also trying to extract a `wildfly.tar`, without adding it to the image first).

Using the official Wildfly image: https://hub.docker.com/r/jboss/wildfly/ as a base, sounds like a far better approach here (also read the instructions and linked documentation on that page).

However, I'm going to close this issue, because this is not a bug, but a support question, and the GitHub issue tracker is not intended for that. Consider asking this question on;

- https://forums.docker.com
- StackOverflow
- the #docker IRC channel on freenode

I also suggest to read the documentation and getting started guides, to get a feel for the "basics" before going to more advanced topics.

I hope the above information will help you further, feel free to comment here after I've closed!

**Closed by thaJeztah** 2015-12-31 13:23 UTC

**Comment by itsdpk** [comment] 2016-01-01 06:15
@thaJeztah Thanks much, i shall take it forward through the forums.
