### ISSUE TITLE
docker build failed on windows 10

### ISSUE THREAD

**Issue by dattatrayakumbhar04** [docker/docker#27739] opened 2016-10-25 13:40 UTC
**Description**
Started docker build command on failed with error "**Error checking context: 'can't stat '\\?\C:\Users\datkumbh\AppData\Local\Application Data''.**"

I have installed docker on windows and trying to create image with docker build command from commandline.

**Steps to reproduce the issue:**
1. Have valid dockerfile in any directory
2. Start docker build command as "docker build -f  dkfile "C:\Users\datkumbh""

**Describe the results you received:**
Docker build failed with error "**Error checking context: 'can't stat '\\?\C:\Users\datkumbh\AppData\Local\Application Data''.**"

**Describe the results you expected:**
Docker should get build successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
Always

**Output of `docker version`:**
C:\Users\datkumbh>docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**
C:\Users\datkumbh>docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.942 GiB
Name: moby
ID: E7EV:QN6U:UXT2:E4UB:IB3L:Q47N:UUV7:NO24:7LV2:XOE7:P2SH:XWG3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 22
 System Time: 2016-10-25T13:39:51.0753431Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows10

**Comment by thaJeztah** [comment] 2016-10-28 04:35
If I'm not mistaken, it's not possible to use a path containing a space as build context on Windows; can you try building from a different path (without a space)?

/cc @jhowardmsft @londoncalling

**Comment by jhowardmsft** [comment] 2016-10-28 05:21
Ah, it's not the space. This came up a little time back. It's the fact there's symlinks which we can't follow under that path (e.g. Music). I did put in a PR around a year back to ignore them but it got rejected. Just create a directory under there and use that as your build context. You probably don't want to send your entire user folder as a tat to the daemon anyway...  Shorter answer,  by design. Hence closing.

**Closed by jhowardmsft** 2016-10-28 05:21 UTC
Labels: platform/windows, version/1.12

**Comment by AshMcConnell** [comment] 2016-11-07 14:15
This happens on a clean installation if you try and do any docker build.  Without any configuration it gives the error : - 

Error checking context: 'can't stat '\\?\C:\Users\Ash\AppData\Local\Application Data''.

This is because Application Data is a symlink to C:\Users\Ash\AppData\Roaming 

Surely a default config that avoids these symlinks would be preferable? *Note* I didn't configure `C:\Users\Ash\AppData\Local\Application Data` to be the context.  How do I set the context to work around this problem?

**Comment by AshMcConnell** [comment] 2016-11-07 14:27
**Update** - The issue for me is that I was running docker in c:\Users\Ash (i.e. my home folder in git bash).  For some reason, running it from Documents `C:\Users\Ash\Documents\` fixed the problem.  I'm thinking that docker thinks it can't write to `C:\Users\Ash` and tries to write to `C:\Users\Ash\AppData\Local\Application Data` instead.

A possible fix would be to default to the %APPDATA% env variable as it's where the `C:\Users\Ash\AppData\Local\Application Data` symlink points to (i.e. `APPDATA=C:\Users\Ash\AppData\Roaming`

Hope this helps some googlers :)

**Comment by thaJeztah** [comment] 2016-11-07 14:36
@AshMcConnell no, the reason is that the "build context" is the directory from within you are building. `docker build` is performed by the _daemon_. Given that the _daemon_ may be on a different machine,  it doesn't have access to the files you _may_ need in your Dockerfile. So what happens is that the docker client will create an archive of the current directory, including all subdirectories, and uploads that to the daemon (also see https://docs.docker.com/engine/reference/builder/#/usage)

Best practice is to create an _empty_ directory and only put the Dockerfile, and any file/directory that's needed for the Dockerfile inside that directory. Doing so speeds up the build (as it only will send the files you actually _need_ to the daemon), and also prevents the cache from being invalidated due to unrelated changes.

**Comment by AshMcConnell** [comment] 2016-11-07 14:44
Ah I see, that makes perfect sense now.  Thanks for the clarification.
