### ISSUE TITLE
Cannot read data from a bound file

### ISSUE THREAD

**Issue by andr2k** [docker/docker#31689] opened 2017-03-09 10:42 UTC
Cannot read data while following an example from docker documentation. Possibly, something is wrong with my docker configuration?

1. Install Docker for Ubuntu
2. Create a container in accordance with this: https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume
`docker run --rm -it -v ~/.bash_history:/root/.bash_history ubuntu /bin/bash`
3. Do `cat ~/.bash_history ` inside the container

**Describe the results you received:**
The result is: `cat: /root/.bash_history: Permission denied`

I see that the problem is with file access rights/attributes. When I change my .bash_history's attributes in order to allow reading for everybody, docker containers can access it. Is there a way to share my file access rights with containers I run?

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 8
 Running: 4
 Paused: 0
 Stopped: 4
Images: 182
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/296608.296608/aufs
 Backing Filesystem: extfs
 Dirs: 191
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.10.0-9-generic
Operating System: Linux Mint 18.1
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55 GiB
Name: a-dell
ID: IEJP:6N34:GFBS:VIOM:HDBW:NVOF:BH3E:HZFO:3SOE:AACN:VZCV:FSWZ
Docker Root Dir: /var/lib/docker/296608.296608
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```
I am on Linux Mint 18.1.

**Comment by thaJeztah** [comment] 2017-03-09 10:56
This is expected if you are running with user-namespaces enabled. From the output of your `docker info` it looks like you have user-namespaces enabled;

```
/var/lib/docker/296608.296608/aufs
```

When running with userns enabled, the `root` user inside the container is a non-privileged user "outside" the container. Producing an error ("Permission denied") is _exactly_ what user-namespaces is designed for; if a process inside the container (for whatever reason) manages to "escape" the container, if should not have permissions to do anything on the host.

In this case, you bind-mounted a file from the host inside the container, giving the container access to those files on the host. When bind-mounting files (or directories), those files are mounted as-is; no mapping is done of "uid:gid" on the host to the remapped "uid:gid" inside the container, hence the process inside the container is not allowed to access those file.

This _may_ become possible in future, but requires features to be added in the kernel (see this [proposal for `shiftfs`](https://lwn.net/Articles/687354/). Also see https://github.com/docker/docker/issues/28593, and @estesp's [blog post](https://integratedcode.us/2015/10/13/user-namespaces-have-arrived-in-docker/);

> the critical missing functionality at this point is the ability to mount filesystems on Linux with a “shift offset” for the ownership information of each filesystem entry. 

I'm closing this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-03-09 10:56 UTC
Labels: version/17.03
