### ISSUE TITLE
docker run leaves directories owned by root after exit

### ISSUE THREAD

**Issue by mephi42** [docker/docker#22145] opened 2016-04-19 09:51 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 450
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 495
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.13 GiB
Name: q
ID: 73ZX:K7JO:LKAW:VKLY:5ERR:7ULP:XAO3:L7BX:CDWI:5ZFC:MJCT:F4ZW
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. mkdir foo
2. mkdir bar
3. docker run -i -t -v $PWD/foo:$PWD/foo -v $PWD/bar:$PWD/foo/bar busybox
4. ^D

**Describe the results you received:**
ls -l foo
total 4
drwxr-xr-x 2 **root root** 4096 Apr 19 12:47 bar

**Describe the results you expected:**
Directory foo should have been empty.

**Additional information you deem important (e.g. issue happens only occasionally):**
100% reproducible.

**Comment by cpuguy83** [comment] 2016-04-19 12:00
This is how bind mounts work.
The target must exist, so therefore the directory must be created before doing the mount.
Since you've monted `$PWD/foo` and then mounted `$PWD/bar` into `$PWD/foo/bar`, the first mount already exists when setting up the 2nd mount, as such the dir is created inside `$PWD/foo`

This is expected behavior and I'm not sure that there is anything we can do to change it.

**Comment by thaJeztah** [comment] 2016-04-19 14:52
Yes, I don't think there's much we can do here to change that. Also, by bind-mounting a directory from your host, you explicitly give the container permission to write in that directory. Depending on your use-case, you may consider using a named volume (`docker volume create --name some-volume`) instead of a bind-mounted directory.

I'll close this for the reasons above, but feel free to comment after that

**Closed by thaJeztah** 2016-04-19 14:52 UTC

**Comment by mephi42** [comment] 2016-04-19 16:49
Isn't it possible to remember that such a directory was created, and remove it during container destruction?

**Comment by thaJeztah** [comment] 2016-04-19 16:52
The directory could contain files created by the container, so I don't think we should do that

**Comment by mephi42** [comment] 2016-04-19 17:00
Wouldn't files end up in bind-mounted directory $PWD/bar, and not $PWD/foo/bar, on container exit?

P.S. I'm using "mkdir foo/bar" workaround now, so I no longer end up with root:root directories, that I cannot get rid of as a regular user.

**Comment by cpuguy83** [comment] 2016-04-19 17:06
@mephi42 It's impossible to know how every user wants to handle this situation.
In general I'd say it's bad that we create host directories at all, but we're stuck with that.
It's best for us to leave the host side alone as much as possible and know that when you bring host resources into a container like this there can be unexpected side-effects.
