### ISSUE TITLE
snytax err occurs compiling docker source

### ISSUE THREAD

**Issue by TheBeeMan** [docker/docker#22496] opened 2016-05-04 08:01 UTC
compiling docker source followed a syntax err:
useragent.go:18: undefined: Version
useragent.go:20: undefined: GitCommit

**Comment by justincormack** [comment] 2016-05-04 09:32
That is not a syntax error, it looks like you are not building it in a way that those are defined. If you do not use the official build process, such as using `make` which sets everything up correctly then it is going to be difficult, it is not the simplest product to build.

**Comment by thaJeztah** [comment] 2016-05-04 11:58
Please read the contributors guide as well, which may contain useful information; https://docs.docker.com/opensource/project/who-written-for/

I'll close this issue, because this is not a bug; if you have questions on how to contribute or how to build docker yourself, feel free to join the #docker-dev IRC channel for help (or have a look at https://github.com/docker/docker/blob/master/CONTRIBUTING.md#talking-to-other-docker-users-and-contributors)

**Closed by thaJeztah** 2016-05-04 11:58 UTC

**Comment by andschwa** [comment] 2016-11-15 23:00
@TheBeeMan is there any chance you figured out what was going wrong with your environment? I'm all of a sudden running into this when using `./hack/make.sh` on Windows. I've had previously working... so it seems that it has to be a change to my environment, but I'm having trouble tracking down *what* changed to break this.

I can't find anything in `Makefile` that sets these up.
