### ISSUE TITLE
A volume without a host mount loses data upon a new layer in a Dockerfile

### ISSUE THREAD

**Issue by rokcarl** [docker/docker#19292] opened 2016-01-13 09:37 UTC
If you use a `VOLUME /path` in the `Dockerfile` and then write to it in the same `Dockerfile`, the changes will not persist. Check the bug report two comments down.
Check [this shell session](https://gist.github.com/r4um/54cc40b2686fd8ccecdd). I was told this is a duplicate of #14080, but I disagree.

**Comment by rokcarl** [comment] 2016-01-13 09:42
# Bug report

## Docker version

    docker version
    Client:
     Version:      1.9.0
     API version:  1.21
     Go version:   go1.4.3
     Git commit:   76d6bc9
     Built:        Tue Nov  3 19:20:09 UTC 2015
     OS/Arch:      darwin/amd64
    
    Server:
     Version:      1.9.0
     API version:  1.21
     Go version:   go1.4.3
     Git commit:   76d6bc9
     Built:        Tue Nov  3 19:20:09 UTC 2015
     OS/Arch:      linux/amd64

## Docker info

    docker info
    Containers: 40
    Images: 1282
    Server Version: 1.9.0
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 1362
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.1.12-boot2docker
    Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
    CPUs: 1
    Total Memory: 1.956 GiB
    Name: default
    ID: NQ7Z:4RMN:4DXI:KNU7:AVXL:G6PS:6ERP:M6OO:3XQH:F4H7:UYSJ:RZB2
    Debug mode (server): true
     File Descriptors: 14
     Goroutines: 26
     System Time: 2016-01-13T09:38:57.801234638Z
     EventsListeners: 0
     Init SHA1:
     Init Path: /usr/local/bin/docker
     Docker Root Dir: /mnt/sda1/var/lib/docker
    Username: rokcarl
    Registry: https://index.docker.io/v1/
    Labels:
     provider=virtualbox

## Reproduce

1. Create the file structure as [here](https://gist.github.com/r4um/54cc40b2686fd8ccecdd).
2. Build with `docker build --no-cache .`.

## Received

I got a `No!` on the step 6 of the build.

## Expected

`Yes!`.

**Comment by phemmer** [comment] 2016-01-13 10:39
This is expected behavior, and covered in the documentation: https://docs.docker.com/engine/reference/builder/#volume

> Note: If any build steps change the data within the volume after it has been declared, those changes will be discarded.

**Comment by vdemeester** [comment] 2016-01-13 10:39
@rokcarl as @phemmer says, it is by design, *Host mount* in `Dockerfile` is not supported. When you specify `VOLUME /foo/bar:/tmp`, it will create a folder `/foo/bar:/tmp` in the container, it's not bind mounting anything. 
And as `/foo/bar` folder is different than `/foo/bar:` your tests work because `/foo/bar` is not a volume anymore (`/foo/bar:`).

**Comment by rokcarl** [comment] 2016-01-13 10:45
Understood. Is there a reason this happens, i.e. why is this a "feature"?

**Comment by cpuguy83** [comment] 2016-01-13 14:30
Closing since this is really a dup of #3639

**Closed by cpuguy83** 2016-01-13 14:30 UTC

**Comment by cpuguy83** [comment] 2016-01-13 14:33
@rokcarl The builder intentionally is not allowed access to host-level resources which means mounting a host directory is a no-go.
On the point of having changes persist to the image's FS after volume, see the discussion in the referenced issue... and the multiple PR's I've attempted to resolve the issue.

Maybe once the builder is spun out (which is imminent, I think), we can look at addressing the issue again.
