### ISSUE TITLE
Volume mount options keep reverting to earlier options when creating a service

### ISSUE THREAD

**Issue by mojavezax** [docker/docker#31627] opened 2017-03-07 23:49 UTC
**Description**

I'm seeing some strange behavior while trying to mount an NFS volume when
creating a service. It appears that the `--mount` options keep reverting back
to previously used options.

Note that I'm only seeing this problem because I can't get the NFS mount to work at all.
But that's another issue.

**Steps to reproduce the issue:**
1.  Create a service with a `--mount` option that references an NFS share.
2.  List the service with `docker service ps --no-trunc`
3.  Create another service with a `--mount` option referencing a _different server and share_
4.  List this service in the same way.

**Describe the results you received:**
Running two tests with different NFS servers and shares, I got the same error message _with the same details_ each time:

The first test goes like this:
```
$ docker service create --mount 'type=volume,source=sw,target=/mnt,volume-driver=local,volume-opt=type=nfs,volume-opt=device=10.30.216.38:/sw' --name fedora1 fedora /bin/bash
l7r04fk3m38znmgk7brvoqzjd

$ docker service ps --no-trunc fedora1
ID                         NAME           IMAGE                                                                                  NODE                        DESIRED STATE  CURRENT STATE            ERROR                                                                                                                             PORTS
y82mciumek6f5dlfausxdymnc  fedora1.1      fedora:latest@sha256:8d3f642aa4d3fa8f9dc52ab0e3bbbe8bc2494843dc6ebb26c4a6958db888e5a2  beryllium.example.com  Ready          Rejected 5 seconds ago   "error while mounting volume with options: type='nfs' device=':/sw' o='addr=strontium.example.com': protocol not supported"
leqzzempzukf8xjjlg9in44jt   \_ fedora1.1  fedora:latest@sha256:8d3f642aa4d3fa8f9dc52ab0e3bbbe8bc2494843dc6ebb26c4a6958db888e5a2  beryllium.example.com  Shutdown       Rejected 10 seconds ago  "error while mounting volume with options: type='nfs' device=':/sw' o='addr=strontium.example.com': protocol not supported"

$ docker service rm fedora1
fedora1
```

The error message (which is another matter) shows the correct host name associated with the given address.

Next, I try another test, _using a different NFS host and share_:
```
$ docker service create --mount 'type=volume,source=sw,target=/mnt,volume-driver=local,volume-opt=type=nfs,volume-opt=device=10.30.216.171:/shares/sw' --name fedora1 fedora /bin/bash
xdj6rw1q8uaqarnwi4iqlpvai

$ docker service ps --no-trunc fedora1
ID                         NAME           IMAGE                                                                                  NODE                        DESIRED STATE  CURRENT STATE           ERROR                                                                                                                             PORTS
2zj602q63m5dclofhx2q2mtua  fedora1.1      fedora:latest@sha256:8d3f642aa4d3fa8f9dc52ab0e3bbbe8bc2494843dc6ebb26c4a6958db888e5a2  beryllium.example.com  Ready          Rejected 4 seconds ago  "error while mounting volume with options: type='nfs' device=':/sw' o='addr=strontium.example.com': protocol not supported"
ddm6t162vdebyb0bsztrr6kx1   \_ fedora1.1  fedora:latest@sha256:8d3f642aa4d3fa8f9dc52ab0e3bbbe8bc2494843dc6ebb26c4a6958db888e5a2  beryllium.example.com  Shutdown       Rejected 4 seconds ago  "error while mounting volume with options: type='nfs' device=':/sw' o='addr=strontium.example.com': protocol not supported"
```

Notice that the error message is exactly the same as the first! It still shows the host and share from the previous command.

**Swarm environment**
The manager is a VM and the workers are physical servers:
```
$ docker node ls
ID                           HOSTNAME               STATUS  AVAILABILITY  MANAGER STATUS
0m73f50mpyhrrwmm60g7z0rr3    magnesium.example.com  Ready   Active
j8iw5acnxhyowqh0heqawe8cz    beryllium.example.com  Ready   Active
mtfevwhyxvgr1rphssv9ysi9p *  astatine.example.com   Ready   Drain         Leader
```

**Describe the results you expected:**
The error messages should be different  ;-)

**Additional information you deem important (e.g. issue happens only occasionally):**
I restarted the docker engine, and also rebooted the machine. No change.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 17.03.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: mtfevwhyxvgr1rphssv9ysi9p
 Is Manager: true
 ClusterID: rxne8yabccuskutu23dy40m9a
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.30.217.85
 Manager Addresses:
  10.30.217.85:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797 GiB
Name: astatine.example.com
ID: C3YM:WNQU:66FU:QC26:HNFQ:3BCR:EK5S:H7IX:7JIR:NCX3:2YUD:CPEV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 silver.example.com:5005
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by tiborvass** [comment] 2017-03-08 01:32
Ping @dperny @aaronlehmann @nishanttotla ?

**Comment by cpuguy83** [comment] 2017-03-08 01:39
This is because you specified the `source=sw`
It sounds like you don't want to specify a source in this case.

**Comment by mojavezax** [comment] 2017-03-08 02:40
Interesting; I do get different results when leaving off the `source`:

If I try the first test again without the source option, I get the same error.
Note that this is an NFSv4 server.
```
$ docker service create --mount 'type=volume,dst=/mnt,volume-driver=local,volume-opt=type=nfs,volume-opt=device=10.30.216.38:/sw,"volume-opt=o=addr=10.30.216.38"' --name fedora1 fedora /bin/bash
yq84zyfcj3ntcqkqmwhvkq86g

$ docker service ps --no-trunc fedora1
ID                         NAME           IMAGE                                                                                  NODE                        DESIRED STATE  CURRENT STATE           ERROR                                                                                                                           PORTS
p2ks0bcs320qpeabzerjaqgnl  fedora1.1      fedora:latest@sha256:8d3f642aa4d3fa8f9dc52ab0e3bbbe8bc2494843dc6ebb26c4a6958db888e5a2  beryllium.example.com  Ready          Rejected 2 seconds ago  "error while mounting volume with options: type='nfs' device='10.30.216.38:/sw' o='addr=10.30.216.38': protocol not supported"
zxoje19nbwbetnf7lry2mxyn4   \_ fedora1.1  fedora:latest@sha256:8d3f642aa4d3fa8f9dc52ab0e3bbbe8bc2494843dc6ebb26c4a6958db888e5a2  beryllium.example.com  Shutdown       Rejected 2 seconds ago  "error while mounting volume with options: type='nfs' device='10.30.216.38:/sw' o='addr=10.30.216.38': protocol not supported"
```

If I do the second test again without the source, I get a new error.
The NFS server in this case is a NAS box, and I believe it's NFS 3.
```
$ docker service create --mount 'type=volume,dst=/mnt,volume-driver=local,volume-opt=type=nfs,volume-opt=device=10.30.216.171:/shares/sw,"volume-opt=o=addr=10.30.216.171"' --name fedora1 fedora /bin/bash
nszbya4hf1ur4yfnis9wv3xeh

$ docker service ps --no-trunc fedora1
ID                         NAME           IMAGE                                                                                  NODE                        DESIRED STATE  CURRENT STATE           ERROR                                                                                                                          PORTS
v8qjufdjizp4dra5zfrbt6w8q  fedora1.1      fedora:latest@sha256:8d3f642aa4d3fa8f9dc52ab0e3bbbe8bc2494843dc6ebb26c4a6958db888e5a2  beryllium.example.com  Ready          Rejected 3 seconds ago  "chown /var/lib/docker/volumes/197e85b712c9cf1b348e0c180315877ffc65a96815688c03dbd094ddab60c739/_data: read-only file system"
0lcgv4vp455bz32b0gibm64dd   \_ fedora1.1  fedora:latest@sha256:8d3f642aa4d3fa8f9dc52ab0e3bbbe8bc2494843dc6ebb26c4a6958db888e5a2  beryllium.example.com  Shutdown       Rejected 3 seconds ago  "chown /var/lib/docker/volumes/9d8b68c309704f5787c78d107c72240f7edc0d566436e704387403cac6335719/_data: read-only file system"
```

For NFS volumes, I thought the `source` parameter was arbitrary text,
and probably ephemeral; i.e. disappearing when the service was removed.
But it must be associating that name with the volume it implicitly creates?

**Comment by cpuguy83** [comment] 2017-03-08 02:42
It's specifically the name of the volume that gets created.

**Comment by mojavezax** [comment] 2017-03-08 02:48
I'm a bit confused then - when I `docker volume inspect` the volume, I see only the SHA value, and no reference to the source name. E.g.,

```{
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/fc6080c3932ff9334b9b11f6ca28144de178fa5899c2d35b1835b82f98987c2b/_data",
        "Name": "fc6080c3932ff9334b9b11f6ca28144de178fa5899c2d35b1835b82f98987c2b",
        "Options": {},
        "Scope": "local"
    }
```

Am I looking in the wrong place?

**Comment by cpuguy83** [comment] 2017-03-08 03:00
When there is no source specified, the name is generated, it's not really a sha.

**Comment by mojavezax** [comment] 2017-03-08 04:03
I see. Thank you for the clarification!

**Comment by tiborvass** [comment] 2017-03-08 04:13
@cpuguy83 @mojavezax so can we close this issue then?

**Comment by thaJeztah** [comment] 2017-03-08 14:14
Yes, I think we can close this, as it's not a bug. Thanks for reporting @mojavezax, feel free to continue the conversation if needed

**Closed by thaJeztah** 2017-03-08 14:14 UTC
Labels: area/swarm, kind/bug, version/17.03

**Comment by mojavezax** [comment] 2017-03-08 16:22
Confusing, but I agree, not a bug. Thanks @cpuguy83 for explaining this.
One more question and comment –
If I understand this correctly, the `source` parameter has a different semantic meaning when using a bind mount vs. an NFS mount? If that is true, it would be helpful to note that in the docs. Maybe here: https://docs.docker.com/engine/swarm/services/#configure-mounts

**Comment by cpuguy83** [comment] 2017-03-08 16:24
@mojavezax Do you have a specific section in mind?

I see:

>  --mount src=\<VOLUME-NAME>

and

> --mount type=bind,src=\<HOST-PATH>

**Comment by mojavezax** [comment] 2017-03-08 16:32
Ah, I think I see your meaning.
As a newbie, I was confused by the purpose of VOLUME-NAME since it was tied to `source`, and what value I should use. In other words, it's not really a source the way I think of it. I understand now, but maybe a sentence describing it would keep someone else from tripping over the same thing? Perhaps:
“... where VOLUME-NAME is an arbitrary name that will be used as the name of the created volume”

**Comment by cpuguy83** [comment] 2017-03-09 15:07
Makes sense. In this case "source" is really in terms of the `mount(2)` syscall.
Docs are in github.com/docker/docker.github.io if you want to add a blurb about this.

Probably best to come from someone who isn't neck deep in it all the time ;)
