### ISSUE TITLE
Proposal: Dockerfile ADD IMMUTABLE for URLs

### ISSUE THREAD

**Issue by drewcrawford** [docker/docker#7748] opened 2014-08-26 21:03 UTC
I have a lot of statements in my Dockerfiles like this:

```
ADD https://www.python.org/ftp/python/3.4.1/Python-3.4.1.tgz python.tgz
```

And now, multiple times a day (sometimes multiple times an hour) Docker downloads large tarballs only to verify, indeed, Python 3.4.1 is the same Python 3.4.1 as it was 10 minutes ago.  This is bad news for hosts like Python.org and it is also bad news for my build times and bandwidth usage.

Instead I'd like some syntax for solemnly swearing that Python 3.4.1 will be the same Python 3.4.1 every time:

```
ADD IMMUTABLE https://www.python.org/ftp/python/3.4.1/Python-3.4.1.tgz python.tgz
```

When `IMMUTABLE` is used, instead of downloading and hashing the file contents to determine if the cached result is ok to use, Docker would use the URL alone.  Thus as long as the URL in my Dockerfile doesn't change I can rebuild without pulling large tarballs from Python.org.

**Comment by dreamcat4** [comment] 2015-03-04 11:00
+1

This seems like a very good feature. We certainly need it for s6-overlay. I recommend we should think to be adding it as a new `ADD --option` control knob, after #10775 is merged.

**Comment by duglin** [comment] 2015-03-04 12:51
@drewcrawford rather than counting on the URL itself, what if there was a --option that said it should just check the mtime (for files) or Last-Modified HTTP header (for remote resources)?  Or is even doing an HTTP HEAD on the URL too much?

**Comment by dreamcat4** [comment] 2015-03-04 13:31
@drewcrawford - I was under the impression (reading elsewhere) that docker already used the Last-Modified HTTP header to be the `mtime`. *If that's true the caching mechanism either does not work properly and / or is not sufficient for downloading tarballs from github releases (e.g. not a consistent `Last-Modified` HTTP header).*

**Comment by cpuguy83** [comment] 2015-03-04 13:32
@dreamcat4 It does not use the last modified header, but has been discussed before.

**Comment by duglin** [comment] 2015-03-04 13:45
actually, its supposed to use it as the mtime - if its not then there's a bug.  I'll take a look at it. 
https://github.com/docker/docker/blob/master/builder/internals.go#L278

**Comment by duglin** [comment] 2015-03-04 14:41
From my quick test it does appear to work. I see the modified time set properly:
```
Step 1 : ADD http://soaphub.org/files/abc /tmp/abc
Downloading      5 B/5 B
 ---> Using cache
 ---> 73b078da70f9
Step 2 : RUN ls -l /tmp/abc
 ---> Running in 94a5c5040155
-rw------- 1 root root 5 Nov  6 01:37 /tmp/abc
 ---> 54816f0b85f4
Removing intermediate container 94a5c5040155
Step 3 : RUN stat /tmp/abc
 ---> Running in 7f6dd076293d
  File: '/tmp/abc'
  Size: 5         	Blocks: 8          IO Block: 4096   regular file
Device: 30h/48d	Inode: 55          Links: 1
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-03-04 14:38:28.038591064 +0000
Modify: 2014-11-06 01:37:50.000000000 +0000
Change: 2015-03-04 14:38:28.038591064 +0000
 Birth: -
```
Notice its just the mtime not the ctime tho.  @dreamcat4 do you have a small testcase that shows how it fails for you?  Also, I'm using the latest docker, which version are you on?


(note I touched the 'abc' file on soaphub.org so if you try this you'll see a newer time)

**Comment by cpuguy83** [comment] 2015-03-04 16:51
Oh nice... you are right. I guess the other discussions around last-modified were to use it before attempting to actually download the file.

**Comment by duglin** [comment] 2015-03-04 16:52
yup - and if we add support for --options then we can give people the choice.

**Comment by duglin** [comment] 2015-03-04 17:19
Added a testcase to make sure we don't regress:  https://github.com/docker/docker/pull/11159

**Comment by dreamcat4** [comment] 2015-03-04 18:53
*Great guys. I'm glad you are also expressing an interest in this aspect of the `ADD` command. @duglin As requested, here is a simple test case that should reproduce my issue. My local installation was `lxc-docker-1.5.0` on `ubuntu-14.10`.*

Just put this in a Dockerfile, then build twice over, 3x times etc.:

```sh
FROM busybox
ADD https://github.com/glerchundi/container-s6-overlay-builder/releases/download/v1.4.0/s6-overlay-1.4.0-linux-amd64.tar.gz /s6-overlay.tar.gz
RUN gunzip -c /s6-overlay.tar.gz | tar -xf - -C / && rm /s6-overlay.tar.gz
```

What you aught to see is that this same tarball from the above ^^ **"github releases"** url is being downloaded every time. Once it is downloaded, then sure enough docker subsequently checks the full file and concludes `using cache...`. By which time it is too late.

*So if we assume that the `mtime` setting from the `Last-Modified:` http header is indeed working (as per the documentation). Then it would appear that method is simply not up to scratch for any such files publically hosted on Github. Please also feel free to cross-check with any other "Github-releases" URLs and compare the result. It is my understanding that they are all backed onto amazon s3 with a session key that very quickly expires. You may also wish to try other *types* of github download URL such as the `.*/latest/master.tar.gz` URL link. Since they are quite popular also.*

**Comment by duglin** [comment] 2015-03-04 19:15
@dreamcat4 ok, that's different.  :-)   If I'm following, the issue isn't that its not using the cache, its that its still doing the download.  That's known and working as designed.  If we can get the --option stuff added then we can add a flag to tell Docker that its ok to just check the mtime/last-modified value and skip the download.

**Comment by duglin** [comment] 2015-03-04 19:23
See:  https://github.com/docker/docker/issues/3672

**Comment by hookenz** [comment] 2015-04-15 23:34
Can't you do a partial download and verify the first 10K as the hash to make doubly sure.

**Comment by jfrazelle** [comment] 2015-07-10 19:00
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Closed by jfrazelle** 2015-07-10 19:00 UTC
Labels: kind/feature, kind/proposal, tools/build
