### ISSUE TITLE
docker build slow causes

### ISSUE THREAD

**Issue by joliejuke** [docker/docker#27828] opened 2016-10-27 16:27 UTC
Hi,

**I have another issue, I'm unable to build again images, since few hours. Today I build a lot of images ( ~15, in order to test docker), I also created a new local docker-machine (using vm).**

Now build is really slow, install and download of packages take hours instead of minutes. What can cause a build to be slower?

`Step 4 : WORKDIR /usr/src/app`
` ---> Using cache`
` ---> 28c550e7a3fa`
`Step 5 : COPY . /usr/src/app`
` ---> fe88999907b0`
`Removing intermediate container 74c1cb4c1444`
`Step 6 : RUN cat /usr/src/app/.heroku_cred | heroku login`
 `---> Running in ace5497db42a`
`heroku-cli: Installing CLI... 16.85MB/22.45MB`

thanks guys.

**Comment by thaJeztah** [comment] 2016-10-28 00:56
This looks like a question for _running_ docker, not a bug report. Also there's really more info needed, such as `docker version` and `docker info` as is requested in the bug report template.

I'll close this issue, and suggest to open a topic on forums.docker.com, which is a more suitable location

**Closed by thaJeztah** 2016-10-28 00:56 UTC
Labels: kind/question, status/more-info-needed
