### ISSUE TITLE
Mounting folder on windows into docker container

### ISSUE THREAD

**Issue by tomitrescak** [docker/docker#12673] opened 2015-04-23 06:14 UTC
Hi, I search rigidly for the solution to the obvious problem, but cannot find it.
I am trying to mount a folder from my host (windows 8.1) into my docker containers folde '/mnt/src'.

Running following command produces error:

$ docker run -v /c/Users/Tomi/src:/mnt/src tomitrescak/meteor
invalid value "c:\\Users\\Tomi;C:\\Program Files (x86)\\Git\\mnt" for flag -v: \Users\Tomi;C:\Program Files (x86)\Git\mnt is not an absolute path

Any idea?

**Comment by UserTaken** [comment] 2015-04-23 06:34
Any command you give to the Docker daemon is relative the server it's running on. As in you can not mount a local directory to a remote container. The limitation is being worked on with projects like Flocker to allow volumes and containers to be across hosts.

**Comment by cpuguy83** [comment] 2015-04-23 15:07
As @UserTaken said, you cannot mount folders from a different machine into the container.
If you are using boot2docker + virtualbox you may be able to share folders with the boot2docker VM and mount them into the container that way.

Closing since this is a non-issue.

**Closed by cpuguy83** 2015-04-23 15:07 UTC

**Comment by tomitrescak** [comment] 2015-04-23 21:26
Ok, I misunderstood the concept then. Sorry. If would spare a little help, how can I copy files to to VM then and access them from the host then? Thanks. I will write a blogpost so that other lame people won't have to deal with it anymore.

**Comment by mlapierre** [comment] 2015-04-27 18:59
@tomitrescak it looks like you're using msys or cygwin. Try //c/Users instead of /c/Users eg:

> docker run -v //c/Users/Tomi/src:/mnt/src tomitrescak/meteor

Alternatively, use Powershell or cmd.exe

See https://github.com/docker/docker/issues/12590#issuecomment-96767796

**Comment by eliezeralmeida** [comment] 2015-12-09 00:32
@mlapierre It worked to me. Thank you!

**Comment by AwokeKnowing** [comment] 2016-07-15 06:02
this is not a 'non issue'.   This is an issue with the implementation of Docker on Windows.  by choosing to do it through a boot2docker vm and other tricks, one of the key use cases of docker is discarded.  This is a very REAL issue, and the issue is that "Docker for Windows" doesn't really exist yet.  It's a little like saying MS Word for Mac, but it runs on a Windows VM so of course it can't automatically browse your host files.  Well, that's a HUGE issue, and it means there is not MS Word for Mac.   If Docker for Windows is to succeed as in Linux, it has to be able mount volumes from Windows.  as in, I have  index.html in c:\ and I want to run it as a website without installing WAMP etc.  The whole promise of docker is packaging an application (like php-apache) into a single container and being able to just edit your source without installing and managing the environment. 

Pretending the issue doesn't exist is lame.

**Comment by vgoncharenko** [comment] 2016-10-04 07:38
Also help replace all '/' to '//'.
//c//Users//Tomi//src://mnt//src tomitrescak//meteor
