### ISSUE TITLE
docker 1.9.0 `docker build` caching ignores changed file contents.

### ISSUE THREAD

**Issue by jperville** [docker/docker#17827] opened 2015-11-09 13:58 UTC
# Description of problem

As of docker 1.9.0, `docker build` incorrectly reuses a cached layer even when the content of a file which should be part of that layer has modified contents.

This is important regression, because it results in broken images; versions 1.8.3 and earlier of docker-engine do not suffer from the issue.

## Context

`docker version`: `Docker version 1.9.0, build 76d6bc9`

`docker info`:

```
Containers: 2
Images: 2286
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 2290
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-32-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 15.58 GiB
Name: jp440p
ID: CB5Z:P7RF:RIET:BEGL:XC55:566P:2VWO:GL6X:GU75:5ZZN:66WM:SOAH
Http Proxy: http://10.0.3.84:3128
Https Proxy: http://10.0.3.84:3128
No Proxy: localhost,127.0.0.1,192.168.33.1,192.168.122.1,192.168.33.1,192.168.33.10.xip.io,10.0.2.15,/var/run/docker.sock
WARNING: No swap limit support
```

`uname -a`: `Linux jp440p 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.): physical x86/64 workstation running Ubuntu 14.04.3 (with kernel 3.19)

## Reproducing the issue

How reproducible: 100% (under docker 1.9.0; 1.8.3 and earlier versions do not have the problem)

Steps to Reproduce:
1. create a test directory and cd to it
2. create the `docker-build-caching-bug.sh` file with the contents below and make it `chmod +x`
3. run `docker-build-caching-bug.sh orig` # with `orig` as argument
4. run `docker-build-caching-bug.sh updated` # with `updated` as argument

```sh
#!/bin/sh

set -e

SUFFIX=${1:-orig} # pass any other value on 2nd invocation

cat <<EOF > Dockerfile
FROM busybox:ubuntu-14.04
ADD / /data
CMD ["/bin/cat", "/data/volatilefile.txt"]
EOF

cat <<EOF > volatilefile.txt
volatile-${SUFFIX}
EOF

docker build -t test .

# now the test. should work on docker < 1.9.0 and break with docker = 1.9.0
output=`docker run --rm test || true`

if [ "${output}" != "volatile-${SUFFIX}" ]
then
  echo "BUG: output was '${output}', expected 'volatile-${SUFFIX}'"
  exit 1
else
  echo "OK: output was '${output}', same as expected"
  exit 0
fi
```

Actual Results: the result displayed at the end of step 4 is `BUG: output was 'volatile-orig', expected 'volatile-updated'`.

Expected Results: the result displayed at the end of step 4 should be `OK: output was 'volatile-updated', same as expected`.

Additional info:
 - I have tested docker 1.8.3 and docker 1.7.1 which do NOT suffer from this problem.

**Comment by runcom** [comment] 2015-11-09 14:28
This is not happening on latest master:
```
runcom @ fedora koding/docker/test ‹test*› » ./test.sh orig   
Sending build context to Docker daemon 4.608 kB
Step 1 : FROM busybox:ubuntu-14.04
 ---> 1356831708f4
Step 2 : ADD / /data
 ---> Using cache
 ---> b3225073d237
Step 3 : CMD /bin/cat /data/volatilefile.txt
 ---> Using cache
 ---> f6a96c21d1f5
Successfully built f6a96c21d1f5
OK: output was 'volatile-orig', same as expected
runcom @ fedora koding/docker/test ‹test*› » ./test.sh updated
Sending build context to Docker daemon 4.608 kB
Step 1 : FROM busybox:ubuntu-14.04
 ---> 1356831708f4
Step 2 : ADD / /data
 ---> Using cache
 ---> a3a101097dad
Step 3 : CMD /bin/cat /data/volatilefile.txt
 ---> Using cache
 ---> 980db6ff861b
Successfully built 980db6ff861b
OK: output was 'volatile-updated', same as expected
runcom @ fedora koding/docker/test ‹test*› » 
```
Looking for what fixed it though

**Comment by runcom** [comment] 2015-11-09 14:29
I'm leaving kind/bug cause maybe the fix could go into 1.9.1 (I'm testing it btw)

**Comment by jperville** [comment] 2015-11-09 14:35
Can you confirm that the issue reproduces on your 1.9.0 @runcom and that it is not just the docker on my workstation?

**Comment by cpuguy83** [comment] 2015-11-09 14:36
Hmm, I think this is because you are doing `ADD / /data` instead of `ADD . /data`

**Comment by cpuguy83** [comment] 2015-11-09 14:37
I'm not saying that's correct... but if I change to `.` it's fine.

**Comment by luhn** [comment] 2015-11-09 18:17
I am experiencing this issue as well.  Interestingly, it only is happening on one of my two workstations, even though they're mostly identical (same version of Mac OS X, same version of Docker Toolbox, same version of Virtualbox, building the same dockerfiles.)

**Comment by luhn** [comment] 2015-11-09 18:41
@jperville's shows a failure on both machine (including the working one).

@cpuguy83's patch shows a success on both machines (including the broken one).  Not sure why the test script is working when my actual projects are not.

**Comment by luhn** [comment] 2015-11-09 19:05
I was able to reproduce it by creating a Python virtualenv (`virtualenv env`) in the docker build context.  Not sure what about a virtualenv is breaking it.

**Comment by cpuguy83** [comment] 2015-11-09 19:07
There's a known issue with symlinks, which is fixed on master and should be in 1.9.1 once it's out.

**Comment by luhn** [comment] 2015-11-09 19:12
Ah, that would be it.

Making sure symlinks aren't in the build context fixes my builds.  :+1:

**Comment by pbitty** [comment] 2015-11-10 04:15
I'm also having this issue.

```
$ docker info
Containers: 0
Images: 0
Server Version: 1.9.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-32-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 993.2 MiB
Name: vagrant-ubuntu-trusty-64
ID: XRJB:2P54:OO2B:UWYB:I5L2:POAV:HQXJ:4SOP:H7FW:ARPV:X5QL:S7XJ
Debug mode (server): true
 File Descriptors: 17
 Goroutines: 21
 System Time: 2015-11-10T04:09:58.510165056Z
 EventsListeners: 0
 Init SHA1: 787da34bb103f11fd6114d8782217bc4f7032e3e
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

Dockerfile:
```
FROM scratch
COPY /  /some_folder
```

Simple test:
```
$ echo "foo" > some_file && \
> docker build -t test . && \
> echo "bar" > some_file && \
> docker build -t test .

Sending build context to Docker daemon 3.072 kB
Step 1 : FROM scratch
 --->
Step 2 : COPY / /some_folder
 ---> ab8ec20b08d4
Removing intermediate container d5433605c363
Successfully built ab8ec20b08d4
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM scratch
 --->
Step 2 : COPY / /some_folder
 ---> Using cache
 ---> ab8ec20b08d4
Successfully built ab8ec20b08d4
```

You can see the 2nd build uses the cache even though `some_file` has changed.

If I update the Dockerfile to use `COPY . /some_folder`, it does not use cache, and builds a new image.

**Closed** 2015-11-10 23:20 UTC
Labels: kind/bug
