### ISSUE TITLE
[feature-request]display a process bar when loading an image

### ISSUE THREAD

**Issue by redhatlinux10** [docker/docker#18493] opened 2015-12-08 08:08 UTC
usually it takes a long period of time to run `docker load -i foo.bar`, sometimes this situation makes me to doubt that if the load operation has already died. i think it's better to have an option(for example `-vh` ,similar with `rpm -ivh foo.rpm`) to display a process bar when loading an image.
in fact there are some other docker operations taking a long period of time too. for example `docker attach`,`docker stop`

uname -a:
`Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

docker version:
>Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

docker info:
>Containers: 15
Images: 89
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 119
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: VNFK:3L2W:JOFP:6L3B:FN6Y:JVDN:QSGJ:N4IJ:6JOE:M57L:J4SX:LHCT
WARNING: No swap limit support

**Comment by thaJeztah** [comment] 2015-12-08 11:20
Thanks for suggesting; this is a duplicate of https://github.com/docker/docker/issues/8298, so I'm going to close this one. Please subscribe to that issue to stay informed.

w.r.t. `docker attach` or `docker stop`; that really depends on the process inside the container. For example, `docker stop` sends a signal to the container's main process to stop it, but if that process does not properly handle the signal, docker will kill the process after 10 seconds.

**Closed by thaJeztah** 2015-12-08 11:20 UTC
