### ISSUE TITLE
Get ID container while building (for puppet master)

### ISSUE THREAD

**Issue by SivaIntegrator** [docker/docker#22071] opened 2016-04-15 14:50 UTC
Hi people,

The context of my case is:
Deploy a software with puppet directly at the building of my Dockerfile.
During the building there are several containers used and one of them is suposed to deploy the software with the command line `puppet agent -t`
The problem is how to get the ID container concerned (while the building) in order to set up my node in the site.pp file of my puppet master?

Thanks for your help

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 5
Images: 41
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 52
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-18-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.797 GiB
Name: mcp-50-50-1-11
ID: IBMP:3HPS:BMOV:2XI6:TJNY:46L5:3TYP:2YNL:SERM:IXC3:OPFP:22XW
WARNING: No swap limit support

```

**Steps to reproduce the issue:**
1. Build Dockerfile

**Comment by justincormack** [comment] 2016-04-15 15:04
You should not be doing a deploy in the build stage. There is no way to get any container IDs while they are being built, and if there was there is still a  problem as the build may still fail in which case puppet would fail. You should build first (then test) and then deploy.

**Comment by thaJeztah** [comment] 2016-04-15 22:58
@SivaIntegrator please keep in mind that the GitHub issue tracker is meant for reporting bugs, and feature request,  not a general support forum. Consider using;

- forums.docker.com
- the #docker IRC channel
- StackOverflow

Which are more suitable for this kind of questions.

I'll close this issue, because this is not a bug, but feel free to continue the discussion

**Closed by thaJeztah** 2016-04-15 22:58 UTC

**Comment by SivaIntegrator** [comment] 2016-04-18 08:16
@justincormack , 
Yes it's what I thought ,
And if I deploy the software in a new container after the building, is it possible to build an image from it where the software will be already installed? 
Because I need to mechanise the installation like the client should just have to launch one command and get the software in its container (without deploying it by itself)

@thaJeztah thanks for your advice.

**Comment by thaJeztah** [comment] 2016-04-18 08:26
You can commit a container to an image using [`docker commit`](https://docs.docker.com/engine/reference/commandline/commit/), and use the `--change` flag to set a new `CMD`. However, the regular approach is to use a Dockerfile to build your images; this makes your images reproducible, and allows you to take advantages, such as automated builds on Docker Hub. https://docs.docker.com/engine/userguide/intro/

**Comment by SivaIntegrator** [comment] 2016-04-19 14:22
Ok so what I've done is, I have now my docker container within puppet installed. 
To create my new image, I try for now a simple command line like:  `docker commit --change= 'CMD ["cp", "etc/yum.conf", "/etc/yumtest"] IDcontainer nameofnewimage`

For me it means in the new container runned from the commited image, I will have this yumtest file in etc folder, is it right?

The problem is also that when I try to run this new image or start it (`docker start -i -a idcontainer`), it's impossible to enter in the container, do you know why? (the container is well created fater checking with `docker ps -a`)

Thanks

**Comment by SivaIntegrator** [comment] 2016-04-22 16:16
@thaJeztah , can you please give some help about my last comment, the problem of entering in the container is fixed (forget to use `/bin/bash` command)
But I'm not able to make this copy of file

**Comment by thaJeztah** [comment] 2016-04-22 20:10
@SivaIntegrator not sure why you'r change the CMD to copy a file here; you'd probably have to make sure the file is copied, before committing the container (or `docker exec -it <container> bash` inside the container to copy it to the right location, manually). However, it's really hard to assist without knowing the full situation / code you're running, and what you're trying to achieve. The GitHub issue tracker really isn't the place for this.
