### ISSUE TITLE
Cannot resolve container's hostname on overlay network

### ISSUE THREAD

**Issue by gabekahen** [docker/docker#32149] opened 2017-03-27 20:58 UTC
**Description**

Newly created containers from a Docker swarm service definition on a single-node swarm with a published port are unable to resolve their own hostnames to an IP address.

This is in contrast to service containers created without any published ports, which are assigned to the 'bridge' network by default, and are able to resolve their own hostnames.

**Steps to reproduce the issue:**
1. Create a new docker service with a published port
```
docker service create --publish 80:80 nginx
```
2. Run `hostname -i` in the newly created container.
```
docker exec $(docker ps --quiet --last 1) hostname -i
```

**Describe the results you received:**
The output I received from `hostname -i` was:
```
hostname: Name or service not known
```

**Describe the results you expected:**
`hostname -i` should resolve the container's hostname to its IP address (in this case, a 10.255.0.0/16 address).

**Additional information you deem important (e.g. issue happens only occasionally):**
It didn't appear to matter which Docker container image was used, though all the images I used were based on Debian.

The issue _does not_ occur when no ports are published (Docker swarm then selects the network as 'bridged' by default).

I could not replicate this issue outside of docker swarm (publishing ports with `docker run` and then running `hostname -i` resolves to the container's IP), however I suspect this is because `docker run` with `--publish` still places the container into the bridged network. 

**Output of `docker version`:**

```
root@vagrant-ubuntu-trusty-64:~# docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
root@vagrant-ubuntu-trusty-64:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: wnfnd0jj964rh2z6zkdhr2zxi
 Is Manager: true
 ClusterID: r3176fohawxcku6bn7azkqrcl
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.2.15
 Manager Addresses:
  10.0.2.15:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-112-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.861 GiB
Name: vagrant-ubuntu-trusty-64
ID: E3BI:XQZK:JM73:SBPG:DVUI:QDEV:33BT:JQHL:RKEP:PONO:SZWI:4SSQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-03-28 17:05
Seems to only be for containers that are part of a service

ping @aboch @mavenugo

**Comment by sanimej** [comment] 2017-03-28 17:55
@gabekahen What you are seeing is the expected behavior with services. When the service has a port published and no explicit network attachment is specified its connected only to the `ingress' network. Its infra network provisioned only for the purpose of routing mesh functionality. When you have multiple services they can't communicate with each other (ie: east west traffic) using the ingress network IPs. For this reason docker Service Discovery is disabled in the ingress network and also the ingress network IP won't be added to the /etc/hosts.

If you can create an overlay network and attach the service to that (`--network` in service create), `hostname -i` would return that IP within the container.

**Comment by thaJeztah** [comment] 2017-03-28 19:29
Ah, understood, yes, I thought I missed something.

I'll go ahead and close this one, as it's not a bug, but feel free to continue the discussion

**Closed by thaJeztah** 2017-03-28 19:29 UTC
Labels: area/networking, area/swarm, kind/bug, version/17.03

**Comment by gabekahen** [comment] 2017-03-28 19:58
@sanimej Creating a new overlay network with `docker network create --driver overlay NETWORK_NAME` and starting the service with the `--network NETWORK_NAME` argument resolved my issue - thanks!
