### ISSUE TITLE
dm.basesize not showing in docker info

### ISSUE THREAD

**Issue by hamiltino** [docker/docker#24622] opened 2016-07-14 04:12 UTC
docker info output as follows:

```
Containers: 0
Images: 4
Storage Driver: devicemapper
 Pool Name: docker-8:4-1073741920-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.032 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.3 GB
 Metadata Space Used: 1.72 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.127 (2016-06-11)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.6.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid (containerized)
CPUs: 6
Total Memory: 15.59 GiB
Name: debian
ID: UV2L:CG6Y:NQ4W:K7KY:6VN5:DIMN:SYED:BIQK:ZYBZ:HH4I:NE5Y:4ACN
Username: hamiltino
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
```

Where is dm.basesize???

**Comment by thaJeztah** [comment] 2016-07-14 12:09
hm, should be there (was added in https://github.com/docker/docker/pull/16303), but I'll need to check. What version of Docker are you running?

**Comment by hamiltino** [comment] 2016-07-14 12:12
Docker version 1.8.3, build f4bf5c7

**Comment by thaJeztah** [comment] 2016-07-14 12:19
That explains; it was added in Docker 1.9, so you need to upgrade docker for that.

I'm closing this because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-07-14 12:19 UTC
Labels: area/storage/devicemapper, status/more-info-needed

**Comment by hamiltino** [comment] 2016-07-14 12:54
followed the installation guide on the docker site and now my new version is:
Docker version 1.11.2, build b9f10c9
docker base size now shows but did i downgrade my docker?

**Comment by thaJeztah** [comment] 2016-07-14 13:25
Great!
