### ISSUE TITLE
Add log rotation signal handling to docker daemon

### ISSUE THREAD

**Issue by kuon** [docker/docker#7333] opened 2014-07-30 18:08 UTC
When docker runs in daemon mode, send kill -HUP to it restarts all the container.

While the logging driver is in the work #7195, and for simple setup, it would help considerably to be able to use logrotate with something like `/var/lib/docker/containers/*/*.log` to rotate the log. This path works fine with log rotate, but the missing thing is to be able to signal docker to reopen the xxx-json.log.

Sending SIGHUP or SIGUSR1 should reopen all log files.

**Comment by mindscratch** [comment] 2015-01-06 13:58
:+1:

**Comment by rqc** [comment] 2015-01-07 19:09
:+1: I am also interested in Docker supporting a log rotation/file size limits through its API. I am using Docker as a Mesos container for running my apps in my data center. I am running into issues with the Mesos slave nodes in which their disks are getting full because of the size of the `/var/log/upstart/docker.log` file. This file can grow quickly into the gigabyte range when running containers using Chronos and/or Marathon.

**Comment by tomfotherby** [comment] 2015-01-09 10:38
:+1:

**Comment by gniewkos** [comment] 2015-01-15 10:04
:+1: Frankly I'm a little surprised that it does not have this functionality yet

**Comment by pmoosh** [comment] 2015-01-15 20:54
Reading through all the threads about logging. I think the way upstart handles log rotation seems like a good idea.

**Comment by silarsis** [comment] 2015-01-15 21:00
So, we solved this with a partial side-step.

We log to splunk, so we built a splunkforwarder container that takes a container name (or names) as command line arguments, and runs “docker logs -f <container>” on startup, feeding the results up to splunk. There’s some small tweaks to make it behave properly with multi-line log entries and ensure it doesn’t restart (and re-log everything) of something goes wrong, and to split stdout and stderr and apply source types - but `docker logs -f` works right through a log rotation, so we can then rotate the main docker daemon log file without concern. That container could also be made cleverer (watch for new containers, for instance), but we don’t have the need in our environment.

That has meant the lack of other logging options in docker hasn’t been an issue for us.

KJL

**Comment by cpuguy83** [comment] 2015-01-15 21:03
We're having a discussion on this on this PR: #9753

**Comment by ankushagarwal** [comment] 2015-01-26 03:18
:+1:

**Comment by ryan-stateless** [comment] 2015-01-30 15:22
:+1:

**Comment by pykiss** [comment] 2015-02-10 10:30
what is `/usr/bin/docker restart forwarder` ? 

I use `docker restart $(docker ps -q)`


		/var/lib/docker/containers/*/*.log {
			rotate 7
			daily
			compress
			delaycompress
			copytruncate
		       sharedscripts
		       postrotate
		          /usr/bin/docker restart docker restart $(docker ps -q)
		      endscript
		}

**Comment by unclejack** [comment] 2015-04-06 14:53
The final actual implementation of this feature remains to be decided. Since #8911 is only asking for log rotation to be implemented, I'm going to close this issue in favor of that one.

**Closed by unclejack** 2015-04-06 14:53 UTC

**Comment by shazow** [comment] 2015-04-11 22:07
@unclejack This issue is proposing something very different than building log rotation into docker. 

This issue is proposing a signal (or perhaps API call) which tells docker to re-open all of the log files it's writing to. This allows us to use logrotate the way we've always used it for everything else: Have it rename the current log, then trigger a signal to tell the process to re-start writing to the original name, then handle whatever compression/backup/rotating policy we'd like.

On the other hand, #8911 is proposing adding (a far more limited) logrotate functionality into docker itself. This is way more work and still not as powerful as what this issue proposes.

Perhaps this issue's title should be more: "Add signal/API to re-open logs for writing (for external log rotation support)"

**Comment by LK4D4** [comment] 2015-04-13 00:55
@shazow I agree with you.
But how we can be sure that log won't be lost in gap between rename and SIGHUP?
And there is already implementation of rollover logging #11485

**Comment by mrkschan** [comment] 2015-04-13 02:11
@LK4D4 Try this gist using Python ^^? https://gist.github.com/mrkschan/200eca6e33aac3682c42 It simulates the gap between rename (logrotate) and SIGHUP.

IIRC, any content written to opened FD would keep writing to its inode. Any "concurrent" rename event would not make changes to opened FD. So, the gap between rename and SIGHUP would not have much downside.

But, when handling the SIGHUP log reopen, it should be atomic.

**Comment by shazow** [comment] 2015-04-13 02:12
Yup, moving the file does not change the file descriptor. You can keep writing to it. Reloading the writers will cause them to re-open the file and thus write to a fresh file descriptor.

**Comment by mrkschan** [comment] 2015-04-13 02:23
in my 2cents, log rotation itself can be very complicated due to usage of logs. e.g. you may gzip the rotated log, send it to somewhere, or even process it right after rotation. sending a signal to docker to reopen the log file and let external daemon to handle the heavy liftings would be great.

**Comment by christianparpart** [comment] 2015-04-13 08:49
i don't get your big buzz around. What is so difficult in adding a trap to SIGHUP and re-open all log files the docker process is writing to. Let the admin handle the rest, that is, invoking logrotate daily on those log files and invoke `kill -HUP $(pidof docker)` inside the logrotate config script. keep it simple.

**Comment by cpuguy83** [comment] 2015-04-13 11:16
This is just the wrong approach.
Docker 1.6 includes support for syslog, this is what you should be using in production if you care about your logs.
The json log file is more for dev.

The enhancements in the mentioned PR above solves this issue quite well when you are using the json log (which again should not be relied on for prod environments)

**Comment by mrkschan** [comment] 2015-04-13 11:19
Good to here syslog adoption in docker :)

**Comment by shazow** [comment] 2015-04-14 03:46
Syslog support is lovely, but is that what we're talking about? This issue was closed because it was claimed to be obsoleted by #8911 which is not true.

> Docker 1.6 includes support for syslog, this is what you should be using in production if you care about your logs.

Why? Is that the official docker stance now? Are json logs going to be deprecated and syslog is going to become the default? (I haven't seen any discussion to this effect.)

> The enhancements in the mentioned PR above solves this issue quite well when you are using the json log

It doesn't solve it as well as logrotate, and with more complexity.

**Comment by cpuguy83** [comment] 2015-04-15 20:06
@shazow json logs will not be deprecated. They provide a really great developer experience, IMO.
Using syslog solves the problem without having to implement this. Something like this is not something most developers would ever use.
#8911 obsoletes this because it seems this proposal is generally undesirable by the maintainers.

> It doesn't solve it as well as letting logrotate do what it does best, and with more complexity.

I don't agree that that the proposed log rotation is more complex than what this is asking for.
Also If you want to use logrotate you can pause the container that you are wanting to rotate the logs for, copy/truncate, then unpause to ensure you don't lose any logging (which arguably may be safer than re-opening every single log file just because you needed to rotate one).

**Comment by shazow** [comment] 2015-04-15 20:18
> I don't agree that that the proposed log rotation is more complex than what this is asking for.

More complex than re-opening the log files on signal and letting logrotate do the rest (rather than having numerous log driver opts trying to replicate a subset of the logrotate configuration).

> Also If you want to use logrotate you can pause the container that you are wanting to rotate the logs 
for, copy/truncate, then unpause to ensure you don't lose any logging

This yields needless downtime.

> (which arguably may be safer than re-opening every single log file just because you needed to rotate one).

What's unsafe about re-opening log files?

With logrotate, you can rotate all the logs at the same time and add a post-rotate hook to re-open them, rather than one at a time. Unix services have been doing this for decades, it's not a new invention and as safe as anything.

> #8911 obsoletes this because it seems this proposal is generally undesirable by the maintainers.

If that's the case then this discussion is moot. :)

Either way, if you feel it's worth talking about it more, feel free to ping me out of band too.

**Comment by cpuguy83** [comment] 2015-04-15 20:29
unix processes may do this for a few log files at a time, but docker is not a typical unix process. There can be hundreds/thousands of containers running all with their own log file.

From my perspective, a developer would not use this, and json log is not really suitable for production (and is actually pretty hefty on resources).

**Comment by PicoCreator** [comment] 2017-02-26 05:17
@cpuguy83 : While I agree that an experienced devops / infra team should not let this happen.

I have lost count the number of times I had to help a client / friend / fellow startup / enterprise. In the past 2 year on this issue in production, who are new to docker.

Usually by then, when I tell them they need to to setup ELK to keep things running smoothly. Saying they need to reconfigure every single container (most of which was done by "someone else"), quickly becomes a nightmare situation.

If the issue is having too many file handlers open/close concurrently. Having it done gracefully, one at a time across an hour. Would still be a godsend for those in such situations. Or even renewing the file handler every hour.

Sure it does not logrotate perfectly like we would want it to. But it is at-least it gives us an option, after a 1000 containers been deployed, on handling the logs, without reconfiguring everything.

For now, I simply advice using COPYTRUNCATE, when faced with such situation. Which is known to make logs go missing, until (which is sometimes never) they migrate all their containers to a new logging setup. A few even abandoned Docker migration after facing this. Because they were a lot more used to the process flows in VM. And rejected ELK.

**Comment by cpuguy83** [comment] 2017-02-26 10:41
@PicoCreator docker supports log rotation.
`--log-opt max-size=<size string> --log-opt max-file=<number of files to keep>`

**Comment by PicoCreator** [comment] 2017-03-07 18:54
@cpuguy83 : Changing another department container config as infra admin, is tied with red-tape sadly =( Ironically. This happens when they transfer over their VM practises.

Note: I do web apps for banking and insurance. In many cases we cant even see those config, let alone adjust them. Its also why I would understand why such cases is a non-priority feature. As the problem is niche.

**Comment by cpuguy83** [comment] 2017-03-07 18:56
@PicoCreator You can set these options at the daemon level where it is applied as a default.

**Comment by PicoCreator** [comment] 2017-03-07 19:09
@cpuguy83 : Hmm that ironically is less red-tape. I will give it a try the next time round we face this. But cheers! Glad to hear that, i was assuming its container level only.
