### ISSUE TITLE
Network Connect command closes exposed port if network name is not valid

### ISSUE THREAD

**Issue by zepouet** [docker/docker#21654] opened 2016-03-30 13:15 UTC
**Output of `docker version`:**
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
root@sandbox:~# docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: sandbox
ID: KUMJ:7K6Z:MWRI:CAC7:L5ME:MXI6:3C66:H5U3:OTDA:W6S4:TGL5:WUUW
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Tested on Digital Ocean, official droplet with docker pre-installed but too with manual installation elsewhere.

**Steps to reproduce the issue:**
```
#!/usr/bin/env bash

#set -x

# Reinit the environnement
docker rm -f felix1 felix2 felix3
docker network rm application1
docker network rm monreseau

# Create a new network application
docker network create application1
docker network create monreseau

# Run a new container tomcat
docker run -d -P --name felix1 --net=application1 tomcat:8.0.32-jre8
# All is good. We can reach the exposed port 8080

# Run a second container and connect it to the wrong network
docker run -d -P --name felix2 tomcat:8.0.32-jre8
docker network connect application1 felix2
# No way to reach the exposed port :-(

# Run a third container and connect it to the good network
docker run -d -P --name felix3 tomcat:8.0.32-jre8
docker network connect monreseau felix3
# All is good. We can reach the exposed port 8080

# Display info
docker ps
```

**Describe the results you received:**

No way to reach the exposed port for **felix2** without a ```docker network disconnect application1 felix2```

The name **application1** is not valid for creating a network.
It is strange because it is not a keyword for **docker**

**Describe the results you expected:**

I hope the have the same behaviour that with **felix1** or **felix3** : use the exposed port normally.
We can run a container with a not valid name for network as **application1** without problem but we cannot connect the container to a such named network.

**Additional information you deem important (e.g. issue happens only occasionally):**

I think it is not the length of the keywork **application1** but the term **application**.
Always reproduced. I will try to inspect the source code between libnetwork and docker engine.
Thanks a lot. Best regards,
Nicolas

**Comment by mavenugo** [comment] 2016-03-30 15:08
@zepouet can you please try the RC image of the upcoming 1.11 release and confirm if you still see this issue ? https://github.com/docker/docker/releases/tag/v1.11.0-rc2 ?

**Comment by zepouet** [comment] 2016-03-30 20:19
@mavenugo Thanks but no I just try but always the problem.

**docker info**

```
root@sandbox:~# docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: sandbox
ID: KUMJ:7K6Z:MWRI:CAC7:L5ME:MXI6:3C66:H5U3:OTDA:W6S4:TGL5:WUUW
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**docker version**
```
root@sandbox:~# docker version
Client:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   388f544
 Built:        Fri Mar 25 19:53:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   388f544
 Built:        Fri Mar 25 19:53:02 2016
 OS/Arch:      linux/amd64
```

**Comment by aboch** [comment] 2016-09-27 21:39
@zepouet 

I followed the reproduction steps you reported (thanks for that) using the latest docker image from master.
I no longer see the problem. Things seems to work as expected now.

```
$ docker ps
CONTAINER ID        IMAGE                COMMAND             CREATED             STATUS              PORTS                     NAMES
0279ecd06559        tomcat:8.0.32-jre8   "catalina.sh run"   3 minutes ago       Up 3 minutes        0.0.0.0:32771->8080/tcp   felix3
9aef263e80b1        tomcat:8.0.32-jre8   "catalina.sh run"   4 minutes ago       Up 4 minutes        0.0.0.0:32770->8080/tcp   felix2
befd28d1c256        tomcat:8.0.32-jre8   "catalina.sh run"   5 minutes ago       Up 5 minutes        0.0.0.0:32768->8080/tcp   felix1
$
$ docker port felix1
8080/tcp -> 0.0.0.0:32768
$ docker port felix2
8080/tcp -> 0.0.0.0:32770
$ docker port felix3
8080/tcp -> 0.0.0.0:32771
$
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
c2e8929e7b87        application1        bridge              local
a306b727db25        bridge              bridge              local
a0dd2c482ce4        host                host                local
dc5823f8e9c9        monreseau           bridge              local
2de0510ceb5c        none                null                local
$ docker network inspect application1  --format='{{range .Containers}}{{.Name}}{{end}}'
felix2felix1
$ docker network inspect monreseau  --format='{{range .Containers}}{{.Name}}{{end}}'
felix3
$ curl localhost:32768 | grep Copyright
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11230    0 11230    0     0  1275k      0 --:--:-- --:--:-- --:--:-- 1370k
            <p class="copyright">Copyright &copy;1999-2016 Apache Software Foundation.  All Rights Reserved</p>
$ 
$ curl localhost:32770 | grep Copyright
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11230    0 11230    0     0   824k      0 --:--:-- --:--:-- --:--:--  843k
            <p class="copyright">Copyright &copy;1999-2016 Apache Software Foundation.  All Rights Reserved</p>
$ 
$ curl localhost:32771 | grep Copyright
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11230    0 11230    0     0   839k      0 --:--:-- --:--:-- --:--:--  843k
            <p class="copyright">Copyright &copy;1999-2016 Apache Software Foundation.  All Rights Reserved</p>
$
```

Can you please take a look and confirm.
Thanks

**Comment by mavenugo** [comment] 2016-10-22 17:52
ping @zepouet

**Comment by thaJeztah** [comment] 2016-10-29 08:08
closing because we didn't get a reply, but feel free to comment if this is still an issje

**Closed by thaJeztah** 2016-10-29 08:08 UTC
Labels: area/networking, version/1.10

**Comment by zepouet** [comment] 2016-10-29 08:15
Hello

Sorry I will test and comme back in few days

Thanks
Le 29 oct. 2016 10:09, "Sebastiaan van Stijn" <notifications@github.com> a
écrit :
