### ISSUE TITLE
Can't write to /etc/hosts in my Dockerfile

### ISSUE THREAD

**Issue by sheetweaver** [docker/docker#11950] opened 2015-03-31 06:06 UTC
I have 

    RUN echo '184.73.202.13 git.spindle.factfiber.com' >> /etc/hosts

but it doesn't actually "take". When I add:

    RUN cat /etc/hosts

(and subsequent examination of the layer confirms), I see:

    Step 15 : RUN cat /etc/hosts
     ---> Running in b0da676a8508
    172.17.1.137	feec6e4827bc
    127.0.0.1	localhost
    ::1	localhost ip6-localhost ip6-loopback 
    fe00::0	ip6-localnet
    ff00::0	ip6-mcastprefix
    ff02::1	ip6-allnodes
    ff02::2	ip6-allrouters

No sign of what I added. What is going on?

**Comment by sheetweaver** [comment] 2015-03-31 06:08
So it seems that it does the operation then immediately throws out my /etc/hosts changes:

Step 14 : RUN echo '192.30.252.130 github.com' >> /etc/hosts && cat /etc/hosts
 ---> Running in 34172f32dd38
172.17.1.140	feec6e4827bc
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.30.252.130 github.com
 ---> dd66a262de15
Removing intermediate container 34172f32dd38
Step 15 : RUN cat /etc/hosts
 ---> Running in 4ebf9c89fe7e
172.17.1.141	feec6e4827bc
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters

**Comment by ankushagarwal** [comment] 2015-03-31 06:30
I am not sure, why this happens, but here's a way you can add entries to /etc/hosts during runtime : https://docs.docker.com/reference/run/#managing-etchosts

**Comment by sheetweaver** [comment] 2015-03-31 06:42
I am trying to workaround strange (seemingly) dns-related delays and timeouts using npm.

(https://github.com/npm/npm/issues/3468#issuecomment-87915603)

I was able to speed up npm by running a instance in state just before build failure due to timeout in resolution, and adding to /etc/hosts, but can't do it in the docker file so I can use it at build time. Even better would be to know what is going on with npm. :)

**Comment by dqminh** [comment] 2015-03-31 07:15
I think `/etc/hosts` is mounted by docker so changes will not be persisted across different steps in build time. You can either
- combined the changes into 1 single step `RUN echo entry >> /etc/hosts && do_something`
- or rely on the build cache to cache the installation, hence speed up the next builds if the dependencies do not change i.e.,
```
COPY package.json /app/package.json
RUN install dependencies
```

**Comment by coolljt0725** [comment] 2015-03-31 09:32
`/etc/hosts` is a bind mount from host during starting, it will cover the `/etc/hosts` of image, if you want to setup the `/etc/hosts` you can use `--add-host` on creation

**Comment by feiyang21687** [comment] 2015-03-31 13:04
We face the same problem.

Because docker will mount /etc/hosts on the runtime, so your modification on docker file will be erased. And volume to /etc/hosts will be erased too. Our solution is to modify /etc/hosts on ENTRY POINT. It's so ugly, ```--add-host``` may be a good idea, but we have many hosts to be config, so you will have an ugly docker run command.

**Comment by cpuguy83** [comment] 2015-03-31 13:14
Closing since this is by design. We can't really keep an /etc/hosts around in the image since this tends to be extremely host specific.

You can write to `/etc/hosts` but it only persists for 1 container. Each of your Dockerfile commands run in their own container.

**Closed by cpuguy83** 2015-03-31 13:14 UTC

**Comment by sheetweaver** [comment] 2015-03-31 14:47
Thanks for the info.. hmm.. @cpuguy83 guy83 couldn't you use `git merge` or similar to sort out my changes and your changes? A recursive merge with "ours" as resolution should insure that your changes get in across layers... ?

**Comment by cpuguy83** [comment] 2015-03-31 14:51
We don't want them across layers, otherwise someone would be able to modify /etc/hosts in their image and then distribute that to people where that modification just doesn't make sense.
And generally it doesn't make sense even just changing to a new host.

**Comment by jamshid** [comment] 2020-05-24 16:54
Is there any way to allow `DOCKER_BUILDKIT=1 docker build .` with below Dockerfile to succeed, so the package installation does not have to be rewritten? 

It's okay if the `/etc/hosts` changes are thrown away (pre-DOCKER_BUILDKIT behavior), the package installer just can't get the `Read-only file system` error.

I tried `RUN --mount=type=tmpfs ...` but that needs to replace the entire `/etc` directory and I don't want to lose other changes made by the legacy package installation.

```
FROM centos:6.10 as intermediate

# A legacy package installation tries something like this, which fails with DOCKER_BUILDKIT=1
#     /bin/sh: /etc/hosts: Read-only file system
#
RUN echo 127.0.0.1 foo >> /etc/hosts
```

**Comment by thaJeztah** [comment] 2020-05-26 17:44
@jamshid this is quite an old ticket; could you open a ticket in the buildkit repository so that it doesn't get lost? https://github.com/moby/buildkit/issues
