### ISSUE TITLE
Windows Container port binding not working on Windows Server 2016 TP4 (using Docker)

### ISSUE THREAD

**Issue by mathiasconradt** [docker/docker#21558] opened 2016-03-27 18:44 UTC
### Environment:
Windows Server 2016 TP4
Docker version `1.10.0-dev, build 18c9fe0`

### Original detailed problem description:
http://superuser.com/questions/1057223/windows-container-port-binding-on-windows-server-2016-not-working

### Issue:

I am running a Windows container using Docker on a Windows host (Windows Server 2016 TP4).

> Note that I am using Windows Server 2016 (not any prior Windows version), where Windows Containers can run natively without an intermediate VM (no docker machine there) using Docker.
> 
> I followed the instructions on https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/inplace_setup to setup the Windows container host (bare metal host, no Hyper-V, no VM).
> 
> Specifically, this powershell script provided by Microsoft was executed to setup the Windows 2016 container host https://aka.ms/tp4/Install-ContainerHost, where it seems that all prerequisites regarding networking seem to be done.
> Inside the container runs an IIS web server on the internal port 80.

I want to bind it to the host port 8800.

I followed the instruction as per:

https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/manage_docker#create-iis-image-1-

and ran the container like this:

`docker run --name iisdemo -it -p 8800:80 windowsservercoreiis cmd`

and had also added the firewall rules as per https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/manage_docker#configure-network for ports 80 and 8800 beforehand. But I also turned off the Windows Firewall on the host entirely for testing purposes, just to be sure it's not conflicting.

As you can see from above docker call, I just made a slight change to the example given on the documentation page and changed the bound host port from 80 to 8800, so instead of -p 80:80 I run -p 8800:80.

When I run "ipconfig" on both host and container, I get:

- Host IP: 172.16.0.1
- Container IP: 172.16.0.2

I am either having a misunderstanding what the host is or something does not work right.

The documentation says:

> When the container has been created, open a browser, and browse to the IP address of the container host. Because port 80 (in my case it's 8800) of the host has been mapped to port 80 of the container, the IIS splash screen should be displayed.
> Unfortunately, this does not work.

I can reach the IIS via the container IP: http://172.16.0.2:80 **but not via the host IP address http://172.16.0.1:8800.**

(I also tried -p 80:80, and also that does not work; I cannot reach 172.16.0.1:80).

Running a `docker port iisdemo` returns nothing:

```
PS C:\Windows\system32> docker port iisdemo
PS C:\Windows\system32>
```

and also docker ps does not show anything under "ports".

`docker inspect iisdemo` shows me:

    "PortBindings": {
        "80/tcp": [
            {
                "HostIp": "",
                "HostPort": "8800"
            }
        ]
    },
    ...
    "ExposedPorts": {
        "80/tcp": {}
    },

From my understanding, since I run docker "natively" from a Windows server with a Windows container, there is no intermediate VM (no docker machine) in between, so the "host" is the actual Windows Server that I run docker on.

So my question is, why does the host port binding not work? Why can I not reach the host as per Microsoft documentation?

What I also find confusing is that when I run netstat on both the host and the container, I get the same results! netstat on the host does not show port 8800, but it does show port 80, which should imho only appear when running netstat in the container.

**netstat on Host:**

```
C:\>netstat -ab | findstr ":80"
  TCP    0.0.0.0:80             test2016:0             LISTENING
C:\>netstat -ab | findstr ":8800"
C:\>
```

**netstat on Container:**

```
C:\>netstat -ab | findstr ":80"
  TCP    0.0.0.0:80             test2016:0             LISTENING
  TCP    [::]:80                test2016:0             LISTENING
C:\>netstat -ab | findstr ":8800"
C:\>
```

And when I stop the container, the port 80 does not show anymore when I run netstat on the host. Why? It seems as if the network interfaces of host and container are the same.

I also read the documentation about NAT networking mode, although I must say, I am not a network expert. https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/container_networking#port-mapping

I am not sure though whether this is relevant or not regarding the "Getting started: IIS demo", since it's not mentioned there or linked to at all. (I did not run any configuration commands mentioned there.) From my understanding, it should only be relevant for port forwarding when requesting from the host from an external IP address.

FYI - this is what I get when I run some Powershell commands about the virtual switch information on my host:

```
PS C:> Get-VMSwitch

Name           SwitchType NetAdapterInterfaceDescription
----           ---------- ------------------------------
Virtual Switch NAT

PS C:> Get-NetNatStaticMapping

StaticMappingID               : 16
NatName                       : ContainerNAT
Protocol                      : TCP
RemoteExternalIPAddressPrefix : 0.0.0.0/0
ExternalIPAddress             : 0.0.0.0
ExternalPort                  : 80
InternalIPAddress             : 172.16.0.2
InternalPort                  : 80
InternalRoutingDomainId       : {00000000-0000-0000-0000-000000000000}
Active                        : True
and this is what I get with ipconfig on host and container:
```

**ipconfig (Container):**

```
PS C:\Windows\system32> ipconfig

Windows IP Configuration

Ethernet adapter vEthernet (Virtual Switch-897f61a2cf88f8403d2e1bc946ef76710ac2540882b31b030445781fcf5eca25-0):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::944:73e2:2d58:7c33%26
   IPv4 Address. . . . . . . . . . . : 172.16.0.2
   Subnet Mask . . . . . . . . . . . : 255.240.0.0
   Default Gateway . . . . . . . . . : 172.16.0.1
```

**ipconfig (Host):**

```
PS C:\Windows\system32> ipconfig

Windows IP Configuration

Ethernet adapter Ethernet0:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::19a9:f8bf:6e6d:5544%4
   IPv4 Address. . . . . . . . . . . : 10.10.0.79
   Subnet Mask . . . . . . . . . . . : 255.255.254.0
   Default Gateway . . . . . . . . . : 10.10.0.1

Ethernet adapter vEthernet (Virtual Switch):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::cc17:6b74:4fab:ecce%3
   IPv4 Address. . . . . . . . . . . : 172.16.0.1
   Subnet Mask . . . . . . . . . . . : 255.240.0.0
   Default Gateway . . . . . . . . . :

Tunnel adapter isatap.{0DADB974-F583-4B51-B4B0-C7526A8BABAD}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Tunnel adapter isatap.{0D2767F2-FF2B-4D79-B338-94722C2CF8F9}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
```

For testing purposes, I just installed an Apache httpd server on the Windows 2016 host and let it run on port 80, in order to block port 80 there.

Then I run

`docker run --name iisdemo -it -p 80:80 windowsservercoreiis cmd`

to see if it conflicts (which I expected) due to the port 80 already being in use, but it does not!

**Comment by jhowardmsft** [comment] 2016-03-27 22:51
This should work, but at this point with the imminent TP5 release, and the entire networking codebase having moved to libnetwork, there seems little point investigating this on TP4.

**Comment by mathiasconradt** [comment] 2016-03-28 14:53
@jhowardmsft I updated the original [posting on StackExchange/SuperUser](http://superuser.com/questions/1057223/windows-container-port-binding-on-windows-server-2016-not-working/1057894?noredirect=1#comment1485728_1057894) with all the steps in details that I did, following all the steps exactly from the Microsoft documentation.

**Comment by StefanScherer** [comment] 2016-03-28 19:15
I can reproduce the problems of @mathiasconradt. Played with the [voting-app](https://github.com/StefanScherer/docker-birthday-3/tree/windows/example-voting-app) last week with TP4, I have the same workaround: Opening firewall ports on the host, opening the web server url with container's IP addresses.
Can't wait to test the voting-app on TP5.

**Comment by jhowardmsft** [comment] 2016-04-25 23:24
Closing. This should be fixed with TP5.

**Closed by jhowardmsft** 2016-04-25 23:24 UTC
Labels: group/windows

**Comment by arnodenuijl** [comment] 2016-05-10 19:27
Has anyone verified this works with tp5. I'm running 2016 TP 5 with Docker version 1.12.0-dev, build 2b97201 but i can't get any ports mapped to the host.

**Comment by mathiasconradt** [comment] 2016-05-10 19:32
@arnodenuijl Port binding in TP5 works fine for me, but just make sure that you're making the requests from outside the container host, not from/to itself. See https://github.com/Microsoft/Virtualization-Documentation/issues/253

**Comment by sjey** [comment] 2016-06-16 02:20
Port binding is not working for me in TP5. Tried from a different host and same issue. Not sure whats wrong

**Comment by sitano** [comment] 2016-07-21 12:07
Plz, reopen this issue as this is not working in TP5 as well.

>@arnodenuijl Port binding in TP5 works fine for me, but just make sure that you're making the requests from outside the container host, not from/to itself. See Microsoft/Virtualization-Documentation#253

Yes, but this is not a solution.

It is not possible to use local healthchecks outside of container networking on the host machine with nomad / kubernetes

**Comment by sitano** [comment] 2016-07-22 14:21
https://github.com/Microsoft/Virtualization-Documentation/issues/181#issuecomment-234321612

> I checked with the devs and they're aware of the issue. It will be fixed before Windows Server 2016 is shipped, but unfortunately I don't have a workaround for TP5.

**Comment by ahmadrezamin** [comment] 2016-10-07 21:25
looks like issue still exists with the Windows Server 2016 released a few days ago. I still can't use port mapping while accessing the container directly via it's IP works fine.

**Comment by scrambledheads** [comment] 2016-10-19 09:14
Still an issue Windows 10 Version 1607  / os.Build 14931.1000 / Docker Version: 1.12.2-beta28 (7813)

**Comment by orianbsilva** [comment] 2016-10-22 18:32
docker run -d -p 80:80 microsoft/iis

netstat on host
 netstat -ab | findstr ":80"
""

netstat on container 
PS C:\> netstat -ab | findstr ":80"
  TCP    0.0.0.0:80             7caab1657fa9:0         LISTENING
  TCP    [::]:80                7caab1657fa9:0         LISTENING


network mode Bridge!

**Comment by rayterrill** [comment] 2016-10-24 19:48
I'm also still seeing this issue in the Windows10 latest builds. Not creating the firewall rules on the fly for the port mapping.

**Comment by panmanphil** [comment] 2016-11-02 18:44
I am also seeing this on Windows 10. I can access the port inside the container with Invoke-Webrequest but on the host nothing. Netstat shows nothing on the host.

**Comment by friism** [comment] 2016-11-06 11:16
@rayterrill @panmanphil Yeah, I think this is a known limitation of the current implementation: https://blog.sixeyed.com/published-ports-on-windows-containers-dont-do-loopback/

**Comment by rayterrill** [comment] 2016-11-06 14:41
It doesn't work remotely either. It just flat out isn't working.




On Sun, Nov 6, 2016 at 4:17 AM -0700, "Michael Friis" <notifications@github.com> wrote:












@rayterrill @panmanphil Yeah, I think this is a known limitation of the current implementation: https://blog.sixeyed.com/published-ports-on-windows-containers-dont-do-loopback/

**Comment by drnybble** [comment] 2017-02-22 15:53
Is anyone investigating this? 
docker run -d --name iis -p 8888:80 microsoft/iis
docker inspect iis:
          "Ports": {
              "80/tcp": [
                  {
                      "HostIp": "0.0.0.0",
                      "HostPort": "8888"
                  }
              ]
          },
netstat -na | sls 8888
-> nothing

**Comment by friism** [comment] 2017-02-22 18:55
@drnybble it's tracked here: https://github.com/docker/docker/issues/30300#issuecomment-274152103

**Comment by SwethaRavichandran** [comment] 2017-03-03 05:48
I am running a Windows container using Docker on a Windows host (Windows Server 2016 latest build). I am still seeing the issue. Netstat shows nothing on the host.

**Comment by pcgeek86** [comment] 2017-03-07 20:23
I'm also running into this problem. I can `docker exec` into an IIS container and run `Invoke-WebRequest` against IIS, but I can't hit the website from the host. I've tried all sorts of different port mapping combinations, accessing the website from a remote system, accessing it from the Docker Host itself, and nothing works.

**Comment by panmanphil** [comment] 2017-03-07 22:38
From the host you can hit the container with the private ip of the
container along with the port the container exposes. You can get that ip
with docker inspect. From the host you cannot reach the container the
host's ip even if the container is host mapped. However externally you can
access the container on the host's ip and the host mapped port. Do this all
the time.

**Comment by jnardiello** [comment] 2017-03-15 11:02
+1 on this issue. Any solution yet working? What is the point of encouraging the usage of docker on windows when it just does NOT let you expose a port on Windows Server 2016?

**Comment by panmanphil** [comment] 2017-03-15 11:27
To be clear on this, you CAN expose a port with docker on a Windows 2016 host, we are doing this on hundreds of them every day running at AWS. You just can't access that port when running a request on that box without using the private IP you retrieve from docker inspect.

**Comment by cxadmin** [comment] 2017-03-29 05:47
Same issue. Just installed latest windows server 2016.
running: `docker run -d -P 8000:8000 microsoft/iis`
`netstat -an | find ":8000"`
showing nothing

Windows version
Microsoft Windows [Version 10.0.14393]

Docker engine
PS C:\Users\Administrator> docker version
Client:
 Version:      17.03.0-ee-1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 00:49:51 2017
 OS/Arch:      windows/amd64

is any workaround ?

**Comment by StefanScherer** [comment] 2017-03-29 05:58
@cxadmin Exposed ports cannot be listed with `netstat -an`, but they work from outside of the Docker host using its external IP address.
Notice, the iis container listens on port 80, not 8000, so exposing port 8000 won't work.
I tested with 
```
docker run -d -p 80:80 microsoft/iis:nanoserver
```
and can reach the IIS welcome page from another machine.

**Comment by cxadmin** [comment] 2017-03-29 12:51
Thanks for fast responding.
You right the port is 80. 
But why it is not marked as opened port while running "netstat -an" command ?
Now I started with random port allocation.
`bc993a645511        microsoft/iis       "C:\\ServiceMonitor..."   22 hours ago        Up 28 minutes       0.0.0.0:63417->80/tcp   admiring_sinoussi`
I started my container again with random (-P) port, and yes it is accessible from outside but not in localhost.
I can't understand what happening here. Why in Linux it is so simple an in Microsoft it is so so complicated ????

**Comment by DOMZE** [comment] 2017-04-28 16:03
@StefanScherer is there a reason why `docker run -d -p 80:80 microsoft/iis:nanoserver` works but` docker run -d -p 8000:80 microsoft/iis:nanoserver` does not? That is that I can't access port 8000 on the NAT IP, but i can access it on port 80

I have EXPOSE 80 in my Dockerfile which lists the available ports in my container but the port mapping doesn't seem to work.

**Comment by StefanScherer** [comment] 2017-04-28 16:22
@DOMZE What exactly do you mean with NAT IP? The IP of the container? You can access http://containerip:80 and from another machine http://dockerhostip:8000, but only have a Win2016 at hand.

**Comment by DOMZE** [comment] 2017-04-28 17:16
@StefanScherer Correct the IP of the container. I am able to do http://containerip:80 on my machine (which is the host) but not http://containerip:8000

**Comment by StefanScherer** [comment] 2017-04-28 18:46
@DOMZE but that is normal, same behaviour as on Linux. The process in the container listens at port 80. Only difference between Linux and Windows right now is that on Linux you can curl http://localhost:8000.

**Comment by kallie-b** [comment] 2017-12-19 21:59
Hi all,

We now have support for using localhost/loopback to access your container's published ports on Windows! Here's [the announcement for this support](https://blogs.technet.microsoft.com/networking/2017/11/06/available-to-windows-10-insiders-today-access-to-published-container-ports-via-localhost127-0-0-1/), which is available starting with Windows 10 [Insider](https://insider.windows.com/en-us/) build 17025.

**Have any of you been able to try this already?** If so, we'd love to hear your feedback. Let us know whether or not this support is meeting your needs. Feel free to comment here or email our team at sdn_feedback@microsoft.com.

--Kallie Bracken
PM, Windows Core/Container Networking at Microsoft
