### ISSUE TITLE
Proposal:sometime we should mount the container rootfs with slave flag。

### ISSUE THREAD

**Issue by cc272309126** [docker/docker#15685] opened 2015-08-19 05:45 UTC
Description of problem:
Hi
I want implement the feature that when we mount some network file system like nfs, glusterfs on the host, and bind mount to container, I want  the host's mount event can propagate to the container which mean when umount/mount the glusterfs or nfs on the host, the container should umount/mount the glustefs or nfs too.

`docker version`:

`docker info`:

`uname -a`:

Environment details (AWS, VirtualBox, physical, etc.):

How reproducible:

Steps to Reproduce:
1.mount the glusterfs/nfs or other on the host and setting the host's root mount point with rshared
2.bind mount the moun tpoint in the step 1.
3.mount/umount the glusterfs/nfs on the host
4.check the mount event in the container.  

Actual Results:
the container can't get the mount event

Expected Results:
the container should get the mount even.

Additional info:

**Comment by phemmer** [comment] 2015-08-19 11:47
duplicate of #10088 and #14630, for which a pr is up at #15648

**Closed** 2015-08-19 13:14 UTC
