### ISSUE TITLE
Container name completion in exec command with flags

### ISSUE THREAD

**Issue by rahilb** [docker/docker#31216] opened 2017-02-21 12:18 UTC
**Description**

Zsh completion used to complete container names. This still works, however only if you try to complete when your command is exactly `docker exec`. 

i.e. 
`docker exec [TAB]` shows running containers and you may select one.
`docker exec -it [TAB]` does not show running containers, and you're on your own. 

Once upon a time this worked, and it was very handy. 

**Steps to reproduce the issue:**
1. Install shell completion
2. Try to tab complete after passing options to exec i.e. `docker exec -it [TAB]`
3. Container name/id options are not offered to you. 

**Describe the results you received:**
```
 rahil@Rahils-MacBook-Pro> docker exec -it [TAB]
zsh: do you wish to see all 3743 possibilities (3746 lines)?
```
**Describe the results you expected:**
```
 rahil@Rahils-MacBook-Pro> docker exec -it [TAB]
dynamodb_dyanmodev_1  2d43aa1d6a61  --       8 minutes, dynamodb_dyanmodev
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 46
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: RVCK:PUTJ:223U:OGPH:CQYL:X4RE:ECBM:LTJ6:ENMU:KSLV:ZNLI:427X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 49
 System Time: 2017-02-21T12:14:40.742342925Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I tried this using the oh-my-zsh plugin to install completion and also with the [official instructions for zsh](https://docs.docker.com/compose/completion/#/zsh), both produce exactly the same results.

**Comment by cpuguy83** [comment] 2017-02-21 15:49
Yep, reproduced.

Ping @sdurrheimer

**Comment by sdurrheimer** [comment] 2017-02-21 16:11
Options stacking (`-ti` instead of `-t -i`) is not enabled by default, ref. https://github.com/docker/docker/issues/27744

**Comment by rahilb** [comment] 2017-02-21 16:31
Thanks, just incase anyone finds this issue and doesn't want to click around, the 'fix' is to add the following to your zshrc

```
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes
```

**Comment by thaJeztah** [comment] 2017-02-22 00:21
Looks like this is clarified, so let me close this

**Closed by thaJeztah** 2017-02-22 00:21 UTC
Labels: kind/bug, version/1.13
