### ISSUE TITLE
save image as tar problem

### ISSUE THREAD

**Issue by cwerner1** [docker/docker#20324] opened 2016-02-15 09:50 UTC
Description of problem:
I can't save an image into an tar file

`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

```

`docker info`:
```
Containers: 14
Images: 691
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-6687415-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 26.12 GB
 Data Space Total: 107.4 GB
 Data Space Available: 81.25 GB
 Metadata Space Used: 47.85 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.1 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 12
Total Memory: 62.95 GiB
Name: work
ID: O77A:LBQL:BLUG:ELNE:JHXB:FB3I:HJMC:KGVO:CZCO:JVYE:CSKP:4JLQ
WARNING: No memory limit support
WARNING: No swap limit support

```

`uname -a`:
`Linux work 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
`

Environment details (AWS, VirtualBox, physical, etc.):
physical, Debian 8.3 

How reproducible:
docker save -o /tmp/apache2.tar f29b4736e1ab

Actual Results:
`Error response from daemon: chtimes /var/lib/docker/tmp/docker-export-007920740/04ad7245f09b8ca034adcf7b837d8a9b55ae88e4416fcf17d5d1060c803b1bf1: invalid argument`

Expected Results:
should create an tar file of the image

Additional info:
`mount`:
`/dev/mapper/vg0-lv0 on /var type ext4 (rw,noatime,nodiratime,data=ordered)`

**Comment by flavius** [comment] 2016-02-15 09:51
:+1:

**Comment by thaJeztah** [comment] 2016-02-15 11:04
Are you having this issue with all images, or just that one? I just tried to reproduce, but wasn't able to on my machine

**Comment by cwerner1** [comment] 2016-02-15 11:37
I have the issue with all images.

**Comment by unclejack** [comment] 2016-02-15 11:39
That system most likely lacks the required kernel fixes for devicemapper and it's also using an old version of the devicemapper libraries.

**Comment by albers** [comment] 2016-02-16 17:05
I also have an issue, but I'm using aufs:

    root@docker1:~# docker save nginx > /dev/null
    Error response from daemon: unexpected EOF

I'm using Docker 1.10.1 on a physical Ubuntu 14.04 with current updates.

    root@docker1:~# docker info
    Containers: 0
     Running: 0
     Paused: 0
     Stopped: 0
    Images: 242
    Server Version: 1.10.1
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 244
     Dirperm1 Supported: false
    Execution Driver: native-0.2
    Logging Driver: json-file
    Plugins:
     Volume: local
     Network: bridge null host
    Kernel Version: 3.13.0-77-generic
    Operating System: Ubuntu 14.04.3 LTS
    OSType: linux
    Architecture: x86_64
    CPUs: 4
    Total Memory: 11.73 GiB
    Name: docker1
    
    root@docker1:~# uname -a
    Linux docker1 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment] 2016-02-16 17:40
@albers not getting that, although my 14.04.3 is running on the 3.19 kernel; I'll try to reproduce on a 3.13 kernel

**Comment by albers** [comment] 2016-02-16 18:00
@thaJeztah I got it after updating the OS today.

**Comment by thaJeztah** [comment] 2016-02-16 18:07
Hm same on 3.13 kernel (on DigitalOcean);

```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: fresh-1404
ID: KQ3X:NNHT:GYBD:4YZ2:4HKN:TJCT:FPDO:QAWG:BLLH:3RDH:6B3R:JFFV
```

**Comment by albers** [comment] 2016-02-16 18:09
@thaJeztah Same _having issue_ or same _not having issue_?

**Comment by thaJeztah** [comment] 2016-02-16 18:16
Oh, sorry, not able to reproduce

**Comment by albers** [comment] 2016-02-16 18:23
I just found that whether or not I can save the image depends on the image. Ubuntu is OK, Nginx (and all my custom images) not:

    root@docker1:~# docker save nginx:1.9.3 > nginx.tar
    Error response from daemon: unexpected EOF
    root@docker1:~# docker save ubuntu:14.04 >ubuntu.tar
    root@docker1:~# ls -l *.tar
    -rw-r----- 1 root root         0 Feb 16 19:19 nginx.tar
    -rw-r----- 1 root root 197043712 Feb 16 19:19 ubuntu.tar

**Comment by albers** [comment] 2016-02-16 18:25
corresponding daemon log for the nginx export:

> DEBU[0031] Assembling tar data for 902b87aaaec929e80541486828959f14fa061f529ad7f37ab300d4ef9f3a0dbf from /var/lib/docker/aufs/diff/902b87aaaec929e80541486828959f14fa061f529ad7f37ab300d4ef9f3a0dbf
ERRO[0034] Handler for GET /v1.22/images/get returned error: unexpected EOF

**Comment by thaJeztah** [comment] 2016-02-16 18:30
Was that image present before updating 1.9 -> 1.10? Wondering if there's something related to the content-addressable migration

**Comment by albers** [comment] 2016-02-16 18:58
All images were present before updating Docker. Maybe the file system is corrupt. I had some trouble with unstoppable zombie containers after the OS update (which at that point did not include the kernel), which might have harmed the fs. 
After the OS update,`docker save` still worked. This stopped after updating the kernel and Docker.

I will investigate further tomorrow.

**Comment by albers** [comment] 2016-02-21 14:13
@thaJeztah thanks for trying to reproduce the issus.
I also was not able to reproduce the issue on other machines, so I think it is specific to my installation.
As I already replaced the problematic installation, I won't be able to investigate further. For me, the issue is no longer relevant.

**Comment by thaJeztah** [comment] 2016-02-21 19:38
@cwerner1 are you still having this issue on a fully up to date system and kernel?

**Comment by tonistiigi** [comment] 2016-03-30 17:14
@cwerner1 This error could appear if there was no `created` timestamp in the image and was fixed with #20130 that adds validation of timestamps.

@albers Most likely this was #20458

**Comment by albers** [comment] 2016-03-30 21:04
@tonistiigi Yes, that sounds convincing. Thanks.

**Comment by thaJeztah** [comment] 2016-03-30 21:13
Let me close this issue, but @cwerner1 ping me if you're still able to reproduce on 1.10.3 or later. Thanks for reporting!

**Closed by thaJeztah** 2016-03-30 21:13 UTC

**Comment by helloxingjun** [comment] 2016-05-05 05:48
I have the same problem like @cwerner1. Have you solved the problem?

**Comment by helloxingjun** [comment] 2016-05-05 06:09
Error response from daemon: chtimes /home/docker/tmp/docker-export-109066946/d97cd7b7d1883e72c1e40980907480d42b4b8133d192a727bb43a8ec3e37b11f: invalid argument  @thaJeztah @cwerner1

**Comment by cwerner1** [comment] 2016-05-05 08:11
@helloxingjun 
I did not solve the problem, I moved the build process to another machine

**Comment by helloxingjun** [comment] 2016-05-05 08:36
@cwerner1 So you can save it in another machine? Or you build the image in another machine?

**Comment by cwerner1** [comment] 2016-05-05 08:52
@helloxingjun I did build the images in another machine.

**Comment by helloxingjun** [comment] 2016-05-05 09:09
Do you know the diff between these two machine?

**Comment by thegenius314** [comment] 2017-11-19 15:24
For some reason this issue still occurs when running the docker save command with powershell but works perfectly using cmd
