### ISSUE TITLE
overlayfs fails to run container with a strange file checksum error

### ISSUE THREAD

**Issue by tatsuya6502** [docker/docker#10180] opened 2015-01-19 11:16 UTC
I started to use "overlay" driver today and seeing odd behaviors in my containers (CentOS 6).

1. `yum install <pkg>` in Dockerfile always fails, but running it again in the same container always succeeds.
2. `tail -f <file>` doesn't show appended contents

For 1, this simple Dockerfile always fails at second `yum install` (for perl)

```
FROM centos:centos6

RUN yum install -y sudo
RUN yum install -y perl
```

with this error:

```
Step 2 : RUN yum install -y perl
 ---> Running in 21669e152088
...
Rpmdb checksum is invalid: dCDPT(pkg checksums): perl-version.x86_64 3:0.77-136.el6_6.1 - u

INFO[0018] The command [/bin/sh -c yum install -y perl] returned a non-zero code: 1
```

However, running the same command twice in **the same container** always succeeds.

```
FROM centos:centos6

RUN yum install -y sudo 
RUN (yum install -y perl || yum install -y perl)
```

```
Step 2 : RUN (yum install -y perl || yum install -y perl)
 ---> Running in 5bf1177b4437
...

Rpmdb checksum is invalid: dCDPT(pkg checksums): perl-version.x86_64 3:0.77-136.el6_6.1 - u
  Installing : 4:perl-5.10.1-136.el6_6.1.x86_64                             6/6
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.vastspace.net
 * extras: mirror.vastspace.net
 * updates: mirror.vastspace.net
Package 4:perl-5.10.1-136.el6_6.1.x86_64 already installed and latest version
Nothing to do
 ---> 2671034175e9
Removing intermediate container 5bf1177b4437
Successfully built 2671034175e9
```

Even though I change `perl` to something else, I get the same behavior.

For 2, I noticed that doing `tail -f <application.log>` first shows last 10 lines of the log file, then it doesn't show any appended contents. If I press Ctrl+C and redo, it will show the most recent contents.

I have only tried the official centos:centos6 image so far, and the above behavior is 100% reproducible. I didn't try other images.

**Docker Host:**

CoreOS latest alpha with ext4 root file system and "overlay" driver. I'm running it on EC2, and recreated it once but the problem persists.

```
core@core-01 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=561.0.0
VERSION_ID=561.0.0
BUILD_ID=
PRETTY_NAME="CoreOS 561.0.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Docker Version and Info:**

```
core@core-01 ~ $ docker --version
Docker version 1.4.1, build 5bc2ff8-dirty

core@core-01 ~ $ docker info
Containers: 1
Images: 4
Storage Driver: overlay
Execution Driver: native-0.2
Kernel Version: 3.18.2
Operating System: CoreOS 561.0.0
CPUs: 1
Total Memory: 3.68 GiB
Name: core-01
ID: TM2L:NIZI:CUGT:EUKX:ACP3:EOFX:YQVR:CTL7:R7L2:ILQF:6E3H:HAHQ
```

**Kernel Config:**

```
core@core-01 ~ $ wget https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh
...
2015-01-19 11:09:00 (133 MB/s) - 'check-config.sh' saved [4476/4476]

core@core-01 ~ $ chmod a+x check-config.sh
core@core-01 ~ $ ./check-config.sh
info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_MACVLAN: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_NF_NAT_IPV4: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_CGROUP_PERF: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled
    - CONFIG_EXT4_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled
```

**Comment by jfrazelle** [comment] 2015-01-19 17:32
I was under the impression coreos used btrfs as the backing filesystem.

**Comment by unclejack** [comment] 2015-01-19 17:43
Overlay is currently experimental and not officially supported.

CentOS 6.x has user space tooling and configuration that's only supported with the provided kernel, 2.6.32. We can't provide support for custom kernels on this distribution - nor on RHEL or any other RHEL/CentOS derived distribution.

Please take a look at these comments for more information:
comment from me on the matter: https://github.com/docker/docker/issues/9696#issuecomment-68745351
official comment from jperrin who works on CentOS: https://github.com/docker/docker/issues/9696#issuecomment-68748357

Overlay has some known problems and I wouldn't be surprised to track down these problems to the following overlay related problems:
https://github.com/docker/docker/issues/9572
https://github.com/docker/docker/issues/9874
https://github.com/docker/docker/issues/10169

I'm going to close this issue now because 1) we're tracking overlay issues in multiple other issues already 2) this overlay problem is reported on an unsupported setup - CentOS 6 with custom kernel

Debian jessie with kernel 3.18.x, Ubuntu 14.04/14.10 with kernel 3.18.x and Fedora with kernel 3.18.x would be better setups for testing overlay.

**Comment by tatsuya6502** [comment] 2015-01-19 21:31
>> I was under the impression coreos used btrfs as the backing filesystem.

Here is the release notes of the CoreOS release I'm using.

> Release notes: https://coreos.com/releases/#561.0.0
> - Linux 3.18.2
> - Switch to ext4 as the default root filesystem. Existing systems using btrfs are unaffected.

More info will be found here.

[CoreOS looks to move from Btrfs to overlayfs](https://lwn.net/Articles/627232/)

**Comment by unclejack** [comment] 2015-01-19 21:33
@tatsuya6502 I apologize, I was under the impression you're on CentOS.

**Comment by tatsuya6502** [comment] 2015-01-19 21:37
@unclejack That's ok. I think the issue title I put was confusing.

**Comment by jfrazelle** [comment] 2015-01-19 21:38
So overlay is currently an experimental graphdriver, there are some known issues with tests failing we are working on see https://github.com/docker/docker/issues/9874.
I wonder if this has anything to do with those.

**Comment by tatsuya6502** [comment] 2015-01-19 21:39
@unclejack btw, thanks for the pointers for these issues. I'll take a look.

**Comment by tatsuya6502** [comment] 2015-01-19 21:49
@jfrazelle Thanks for the info. I think this issue may be related to the following test case as my problem only happens after switching containers. (Run a container, modify the image, stop the container, run a new container with the image, try to modify the image -> error)

#9874 
```
--- FAIL: TestSaveAndLoadRepoFlags (0.47s)
    docker_cli_save_load_test.go:266: inspect is not the same after a save / load
```

**Comment by porjo** [comment] 2015-02-27 06:51
I use CoreOS and have just switched from Btrfs to Ext4 and I having the same issue.

**Comment by marineam** [comment] 2015-02-27 21:56
iirc Linux 3.19 or 4.0 adds support for multiple read-only layers in overlayfs which could allow using overlayfs to handle stacking layers instead of re-copying the whole filesystem tree in every layer.

**Comment by Nightling** [comment] 2015-03-01 05:16
I also have this issue with CoreOS 598 and Fedora Rawhide containers.

**Comment by orzel** [comment] 2015-03-03 00:23
I have the same problem here on two servers. It works well on two others.. can't find anything different between those. The common setup is : gentoo, kernel 3.18.8, overlay storage backend (over ext4 on dedicated partition), go 1.4.1 and docker 1.5.0

check-config reports everything ok/'enabled'.

I tried adding "--dns 8.8.8.8 --dns 8.8.4.4" but this doesn't change anything.

**Comment by wuxxin** [comment] 2015-03-08 20:25
same issue with: bare metal ubuntu trusty with:
   kernel 3.18.8 and 3.19.1 both with overlay fs and ext4 
   docker 1.5 and 1.5.0-dev, build a78ce5c
container is fedora 21

**Comment by vaijab** [comment] 2015-03-10 23:59
Same issue here as well on CoreOS with 3.18.4 kernel.

**Comment by t0mk** [comment] 2015-03-12 09:12
same issue I guess, coreos 607,  kernel 3.18.6, docker 1.5.0, trying to build image from centos:6

Rpmdb checksum is invalid: dCDPT(pkg checksums): php-pdo.x86_64 0:5.3.3-40.el6_6 - u

**Comment by charliedrage** [comment] 2015-03-22 14:40
Same issue too. Coreos 607. Trying to build a CentOS container.

**Comment by lypanov** [comment] 2015-03-24 12:47
Same issue using out of box Google Compute Engine CoreOS stable images.... :( Wasted all morning on this. Never could have guessed it would be CoreOS itself.

**Comment by t0mk** [comment] 2015-03-24 13:50
Actually, at least in my case, the yum command quite succeeds, just the rpmdb checksum is invalid... A consequent yum install _pkg_ tells me that _pkg_ is already installed.  I then suppress the error with " || true" after each in the RUN in Dockerfile. That way I can build the CentOS on CoreOS 607+.

**Comment by hany** [comment] 2015-03-30 18:00
Experiencing the same issue with CoreOS 607.0.0 and CentOS 7 image:

```
Rpmdb checksum is invalid: dCDPT(pkg checksums): perl-HTTP-Tiny.noarch 0:0.033-3.el7 - u
```

I'm having the same issue with tailing the log as originally described. File system is ext4.

**Comment by vaijab** [comment] 2015-03-30 21:40
Looks like Linux kernel 4.0 is shipping with multi read-only layers support in overlayfs.

**Comment by crosbymichael** [comment] 2015-03-30 23:51
Does anyone know that kernel patch that fixes this?

**Comment by wuxxin** [comment] 2015-03-31 01:50
tested with kernel 4.0-rc5 ,  docker-1.5-dev build f0ddbba (downloaded an hour ago), overlay fs, ext4 backend: still same problem.

if you follow the commits of the overlay graphdriver, beside 35a22c9e12c05e2a0a205964702ced78ea39d7a1
nothing serious has changed in the overlay graphdriver since 
the  source drop of the overlayfs graphdriver which happened on 19. August 2014

since December (around arriving of 3.18 and integrating overlay fs into kernel) it did not work with any of the following combination:
overlay, kernel: 3.18, 3.19, 4.0-rc5, docker 1.4.1, docker 1.5, docker 1.5-dev (up to current), with ext4, container: centos 6, fedora:21
 
so in essence, the graphdriver code is still the code from Aug.2014 and this was before the new overlay fs was integrated in the kernel (which also changed some semantics within overlay fs)

the possibilities i found:
* maybe there is a bug in the kernel module of overlay since 3.18, including 4.0rc5, 
* maybe docker is using the semantics of the old overlayfs module so there was no bug in docker until usage of new overlay fs, 
* maybe the old overlayfs module and the first docker overlayfs implementation also did not work for redhat container in the first place since the first source drop,

**Comment by ronin13** [comment] 2015-05-04 15:05
Hitting this issue on CentOS 7.1 with overlayfs storage-drive and docker 1.6.0 for a mkdir which is failing with EINVAL.

**Comment by jvinod** [comment] 2015-05-26 05:29
The original "Rpmdb checksum is invalid" occurs because of an overlayfs limitation. 

In general,  data inconsistency can be demonstrated by doing the following:
- pick a file that has not yet been copied up to the upper layer
- open it twice: once in O_RDONLY (fd-ro) and once in O_RDWR (fd-rw)
==> Writing to fd-rw, and reading from fd-ro results in data mismatch.

The problem with yum occurs because a file is opened from /var/lib/rpm in RO mode (from 'lower' layer), the same file is subsequently opened in r/w mode (resulting in a copy up to 'upper') and is updated with new data. The contents of the file when read from the RO fd don't match the new data resulting in the 'checksum is invalid' complaint. Subsequent operations with yum work because /var/lib/rpm files how exist in the 'upper' layer and all the fds come from the 'upper' layer.

We've created a kernel patch for overlayfs to solve this problem and are currently testing it. Please give it a whirl and see if it solves your problem - appreciate your feedback.

The source is here: https://github.com/portworx/overlayfs

**Comment by cgwalters** [comment] 2015-06-28 00:33
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1213602

**Comment by rhvgoyal** [comment] 2015-06-29 12:21
@cgwalters IIUC, we are fixing yum/rpm to be able to work with overlay. Essentially force a copy up of the relevant file. But that does not fix the generic problem with overlay and we don't know how many more applications will run into issues.

**Comment by charliedrage** [comment] 2015-06-29 14:27
@cgwalters @rhvgoyal anyway to show the bug to non-redhat employees?

**Comment by rhvgoyal** [comment] 2015-06-29 15:02
@charliedrage Eric Paris opened the bug. Try accessing it now.

**Comment by charliedrage** [comment] 2015-06-29 16:06
@rhvgoyal Works, thanks. Glad to see that this is being worked on.

**Comment by bchecketts** [comment] 2015-07-10 01:25
Confirmed issue still occurring on CoreOS version 668.2.0.  A workaround is to format the filesystem to btrfs when a container starts according to instructions at https://coreos.com/docs/cluster-management/setup/mounting-storage/

**Comment by ricardobranco777** [comment] 2015-07-21 23:05
A temporary fix is described here:

https://bugzilla.redhat.com/show_bug.cgi?id=1213602#c13

**Comment by bradfordcp** [comment] 2015-07-22 23:17
@ricardobranco777 that fix did not work for me (when placed on its own `RUN` line). Although I did not test putting the `touch` command at the end of my `yum install` `RUN` entries.

**Comment by coolljt0725** [comment] 2015-11-25 03:50
meet this issue on `Linux fedora 4.0.4-301.fc22.x86_64`

**Comment by jeremyeder** [comment] 2015-11-25 13:51
The dnf/yum case wrt overlay fs is resolved in RHEL 7.2-based container images.

**Comment by zekiunal** [comment] 2015-12-13 17:00
I am trying to run :

```
FROM centos:latest
RUN yum -y install gcc libtool make git-core
```
then I am getting error : 

```
Rpmdb checksum is invalid: dCDPT(pkg checksums): perl-HTTP-Tiny.noarch 0:0.033-3.el7 - u
````

# BUT

If i run like this; its working successful

```
FROM centos:latest
RUN yum -y install php56w gcc libtool make git-core
```

I only added php56w


## System Information
```
cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=835.9.0
VERSION_ID=835.9.0
BUILD_ID=
PRETTY_NAME="CoreOS 835.9.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

```
Docker version 1.8.3, build cedd534-dirty
```

```
Containers: 10
Images: 32
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.2-coreos-r1
Operating System: CoreOS 835.9.0
CPUs: 1
Total Memory: 997.6 MiB
Name: image.coreos.latest
ID: LKUN:7LJB:SZVK:WMWC:IPGZ:V6QU:Q57F:ATCY:EFNY:PQMP:SVOZ:KV2Z
```

**Comment by oszi** [comment] 2015-12-13 18:18
This is fixed  in `yum-utils-1.1.31-33.el7` which is still not stable...
See: https://bugzilla.redhat.com/show_bug.cgi?id=1213602

**Comment by ptrj** [comment] 2015-12-18 16:13
```[devkube:/data/etc/docker]$ docker build -t dev/tokyo:latest tokyo
Sending build context to Docker daemon 405.5 kB
Step 0 : FROM docker-registry.modrykonik.com/base
 ---> c889cb5f18e6
Step 1 : COPY files/tokyotyrant-libs-1.1.41-3.el7.centos.x86_64.rpm files/tokyotyrant-1.1.41-3.el7.centos.x86_64.rpm /tmp/
 ---> Using cache
 ---> 2f3af6cbe0d1
Step 2 : RUN yum install -y -q tokyocabinet-1.4.48 /tmp/tokyotyrant-libs-1.1.41-3.el7.centos.x86_64.rpm /tmp/tokyotyrant-1.1.41-3.el7.centos.x86_64.rpm && yum clean all
 ---> Running in aacf7d1ff3b1


Rpmdb checksum is invalid: dCDPT(pkg checksums): libnfnetlink.x86_64 0:1.0.1-4.el7 - u
The command '/bin/sh -c yum install -y -q tokyocabinet-1.4.48 /tmp/tokyotyrant-libs-1.1.41-3.el7.centos.x86_64.rpm /tmp/tokyotyrant-1.1.41-3.el7.centos.x86_64.rpm && yum clean all' returned a non-zero code: 1
```

```
[devkube:/data/etc/docker]$ cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core) 
```
```
[devkube:/data/etc/docker]$ docker info
Containers: 3
Images: 21
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: none
Kernel Version: 3.10.0-327.3.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 32
Total Memory: 46.93 GiB
Name: devkube.devel
ID: WBVV:GGDM:URCV:D72L:SJCL:7LPH:RNPM:AOYV:6GKP:AJTZ:IEBB:CNZT
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
```
[devkube:/data/etc/docker]$ rpm -qa | grep yum-utils
yum-utils-1.1.31-34.el7.noarch
```

**Comment by jeremyeder** [comment] 2015-12-18 16:52
I assume your base image is not built on the rhel-7.2 images.  Your base image has to include the later version of yum-utils. Try a rhel-7.2 image as your base please.

**Comment by ptrj** [comment] 2015-12-18 16:57
I do, thank you

**Comment by ptrj** [comment] 2015-12-19 11:15
I build all my images from official centos:7 
```
[devkube:/data/etc/docker]$ docker run -it docker.io/centos:7
[root@c93b1aa38500 /]# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core) 
```

Is any different between centos7.2 and rhel7.2 ?

**Comment by jeremyeder** [comment] 2015-12-19 17:28
I guess there is, they don't yet have the version of yum-utils in the base image that would resolve this.  I'll see about fixing that...until then, options are to use the device mapper backend for Docker, or use a RHEL-7.2 docker image as your base.

**Comment by jperrin** [comment] 2015-12-21 02:15
We originally excluded yum-utils from the base container for size/usage reasons. If it's required for overlayfs to work, we can certainly add it in. I'll track this in the bug opened by @jeremyeder and should have a new image out in time for Christmas.

**Comment by akaihola** [comment] 2016-02-12 08:02
I'm having this problem as well. I'm running:
- CoreOS alpha (942.0.0, kernel 4.4.0)
- Docker images based on CentOS 6.7

Unfortunately we can't upgrade to CentOS 7 yet, and none of the work-arounds seemed to help (`yum clean all`, `touch /var/lib/rpm/*`). It seems I can't change the storage driver to aufs either since it's not included in this CoreOS version.

My work-around is to build images on a Fedora box instead of CoreOS. I'll look into downgrading CoreOS or upgrading CentOS later.

I also found this issue clearly explained on the [Docker OverlayFS page](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/):
>**RPMs and Yum.** OverlayFS only implements a subset of the POSIX standards. This can result in certain OverlayFS operations breaking POSIX standards. One such operation is the copy-up operation. Therefore, using yum inside of a container on a Docker host using the overlay storage driver is unlikely to work without implementing workarounds.

**Comment by jakirkham** [comment] 2016-02-29 20:30
Also, seeing this with docker-machine 0.6.0, boot2docker/docker version 1.10.1, OS X 10.9.5, with CentOS 6.6 images on OverlayFS.

**Comment by jakirkham** [comment] 2016-02-29 22:31
Found that running `rpm --rebuilddb` before any `yum install`s is a decent workaround for this issue as @porjo has mentioned [above]( https://github.com/docker/docker/issues/10180#issuecomment-76347566 ). Also, using AUFS I have not seen this problem.

**Comment by AkihiroSuda** [comment] 2016-03-01 05:20
The latest CentOS 7 image includes the workaround `yum-plugin-ovl`:

```
$ docker run -it --rm library/centos@sha256:8dcd2ec6183f3f4a94d4f9552ce76091624760edefcaa39a9e04441f9e2ad9f6 sh -c "rpm -qa | grep yum"
yum-plugin-fastestmirror-1.1.31-34.el7.noarch
yum-utils-1.1.31-34.el7.noarch
yum-metadata-parser-1.1.4-10.el7.x86_64
yum-3.4.3-132.el7.centos.0.1.noarch
yum-plugin-ovl-1.1.31-34.el7.noarch
```

Note that the latest tagged image not:
```
$ docker run -it --rm centos:centos7.2.1511 sh -c "rpm -qa | grep yum"
yum-metadata-parser-1.1.4-10.el7.x86_64
yum-3.4.3-132.el7.centos.0.1.noarch
yum-plugin-fastestmirror-1.1.31-34.el7.noarch
```

I'll open a PR that adds a note to the documentation.

@thaJeztah Do you think this issue is closable after that PR?

**Comment by jakirkham** [comment] 2016-03-01 05:24
Unfortunately, I really need to use CentOS 6 to stay compatible with OS versions on our cluster. Is there a workable solution for them or am I SOOL?

**Comment by AkihiroSuda** [comment] 2016-03-01 05:50
@jakirkham Please try this.
```python
#!/usr/bin/env python
# Workaround for CentOS 6 yum overlay issue (docker/docker#10180)
# Based on yum-utils-1.1.31-34.el7 (GPLv2+)
#
# Example Dockerfile:
#  FROM: centos:centos6
#  ADD this.py /
#  RUN /this.py && yum install -y pkg1
#  RUN /this.py && yum install -y pkg2

from os import walk, path, fstat

def _stat_ino_fp(fp):
    """
    Get the inode number from file descriptor
    """
    return fstat(fp.fileno()).st_ino


def get_file_list(rpmpath):
    """
    Enumerate all files in a directory
    """
    for root, _, files in walk(rpmpath):
        for f in files:
            yield path.join(root, f)


def for_each_file(files, cb, m='rb'):
    """
    Open each file with mode specified in `m`
    and invoke `cb` on each of the file objects
    """
    if not files or not cb:
        return []
    ret = []
    for f in files:
        with open(f, m) as fp:
            ret.append(cb(fp))
    return ret


def do_detect_copy_up(files):
    """
    Open the files first R/O, then R/W and count unique
    inode numbers
    """
    num_files = len(files)
    lower = for_each_file(files, _stat_ino_fp, 'rb')
    upper = for_each_file(files, _stat_ino_fp, 'ab')
    diff = set(lower + upper)
    return len(diff) - num_files

def main():
    rpmdb_path = '/var/lib/rpm'
    try:
        files = list(get_file_list(rpmdb_path))
        copied_num = do_detect_copy_up(files)
        print("ovl: Copying up (%i) files from OverlayFS lower layer" % copied_num)
    except Exception as e:
        print("ovl: Error while doing RPMdb copy-up:\n%s" % e)

if __name__ == '__main__':
    main()
```

**Comment by jakirkham** [comment] 2016-03-01 05:59
Thanks for this @AkihiroSuda. I'll give this a try and let you know my results. If it does work, do you think it would be worthwhile to include it CentOS 6.x images?

**Comment by AkihiroSuda** [comment] 2016-03-01 06:10
@jakirkham 
I believe it should be included in CentOS 6 only if it can also get included in RHEL 6.
Could you please ping Red Hat? https://bugzilla.redhat.com/show_bug.cgi?id=1213602#c0

**Comment by jamshid** [comment] 2016-03-01 22:57
@AkihiroSuda just curious, is there any reason to use your script instead of `rpm --rebuilddb`? That also works around the failure when using CentOS 6 `yum install` on "overlay".

**Comment by AkihiroSuda** [comment] 2016-03-02 01:25
@jamshid 
If `rpm --rebuilddb` takes a long time, it might be the reason to use my script.
But basically `rpm --rebuilddb` is fast enough

**Comment by jakirkham** [comment] 2016-03-02 03:32
Another trick that is mentioned in the bug report as recommendable workaround is simply running the following `touch /var/lib/rpm/*` before `yum install` or similar. I can confirm this worked for me and is pretty simple. Though @AkihiroSuda's solution is a more clever version of this.

**Comment by AkihiroSuda** [comment] 2016-03-29 02:32
Linux 4.6 rc1 prints a warning about the issue on dmesg: https://github.com/torvalds/linux/commit/fb5bb2c3b73df060d588b6521de5ab03589283f7

```
ovl: Warn on copy up if a process has a R/O fd open to the lower file
Print a warning when overlayfs copies up a file if the process that
triggered the copy up has a R/O fd open to the lower file being copied up.

This can help catch applications that do things like the following:

	fd1 = open("foo", O_RDONLY);
	fd2 = open("foo", O_RDWR);

where they expect fd1 and fd2 to refer to the same file - which will no
longer be the case post-copy up.

With this patch, the following commands:

	bash 5</mnt/a/foo128
	6<>/mnt/a/foo128

assuming /mnt/a/foo128 to be an un-copied up file on an overlay will
produce the following warning in the kernel log:

	overlayfs: Copying up foo129, but open R/O on fd 5 which will cease
	to be coherent [pid=3818 bash]

This is enabled by setting:

	/sys/module/overlay/parameters/check_copy_up

to 1.

The warnings are ratelimited and are also limited to one warning per file -
assuming the copy up completes in each case.

Signed-off-by: David Howells <dhowells@redhat.com>
Signed-off-by: Miklos Szeredi <mszeredi@redhat.com>
```

**Comment by jasonmp85** [comment] 2016-06-02 05:38
So what's the current guidance for fixing this? Still `touch /var/lib/rpm/*`?

It's one thing when I'm building images on my local box, but for automated builds in Docker Hub, this is _really_ annoying, and I have no clue how to fix it.

**Comment by jeremyeder** [comment] 2016-06-02 11:14
@jperrin is the overlay plugin not in the c6 base image?

**Comment by jperrin** [comment] 2016-06-02 12:47
the overlay plugin wasn't available in EL-6 until 6.8. I'm building the container updates today with the ovl plugin included. Hopefully they'll hit the docker registry today or early tomorrow.

**Comment by jperrin** [comment] 2016-06-02 17:00
@jeremyeder the overlay plugin will be baked into the c6 container as soon as https://github.com/docker-library/official-images/pull/1800 lands.

**Comment by jeremyeder** [comment] 2016-06-02 17:05
Thanks Jim! /cc @jasonmp85 if you can test out that new image once it's built.

**Comment by jasonmp85** [comment] 2016-06-02 18:07
@jperrin @jeremyeder — I've been fortunate enough to that my CentOS builds have yet to be bit by this; however, this problem _also_ affects the Oracle Linux images. I'm not sure their response to this will be nearly as speedy, so I was kind of hoping there was a surefire workaround.

Until then, my Oracle Linux automated builds on Docker Hub are stale and I can't even push up locally-built images to remedy it (since automated builds don't permit any sort of push as a workaround).

Does anyone know the prognosis for the Oracle Linux images? Is there one?

**Comment by Djelibeybi** [comment] 2016-07-20 00:21
@jasonmp85 I've just pushed an updated for the OL6 and OL7 latest images. In future, ping me if you have any issues with the OL base and I can address them. Usually our turnaround time is pretty quick, if we're made aware of an issue. :)

**Comment by AkihiroSuda** [comment] 2016-07-28 08:46
I think the `kind/bug` label should be removed because it is an "expected" behavior of the kernel.
I think it is even ok to close this issue.

**Comment by AkihiroSuda** [comment] 2016-08-16 02:10
Considering the discussion at https://github.com/docker/docker/pull/25705, I think the issue is closable
WDYT @thaJeztah

**Comment by thaJeztah** [comment] 2016-08-16 10:13
I agree, since this this the expected behavior for overlay, and it's now properly documented in https://github.com/docker/docker/pull/25705

**Closed by thaJeztah** 2016-08-16 10:13 UTC
Labels: area/kernel, area/storage/overlay, exp/expert

**Comment by xavierbaude** [comment] 2016-10-10 08:48
There is a yum patch, simply add this in your Dockerfile  : 

`RUN yum install -y yum-plugin-ovl`

Tested in Centos 7/6 + RHEL 7/6

http://man7.org/linux/man-pages/man1/yum-ovl.1.html

Enjoy Docker/overlay :)

**Comment by popomore** [comment] 2016-11-25 09:42
@xavierbaude I also get the checksum error when install yum-plugin-ovl 😢

**Comment by Stelminator** [comment] 2016-11-25 17:09
@popomore you'll probably have to build that layer on something else before moving it to overlayfs.  If it works after that, I'd build it into a base image.

**Comment by jperrin** [comment] 2016-11-25 19:40
@popomore the CentOS 6 base containers have had yum-plugin-ovl in them for several months now. perhaps you need to update, or are you using something other than centos?

**Comment by popomore** [comment] 2016-11-25 20:06
I have try the way in https://github.com/docker/docker/issues/10180#issuecomment-190429512 , it works for me, but I don't know why.

**Comment by alanfranz** [comment] 2016-12-02 22:13
I'm experiencing the issue with the very latest centos 7 image.

https://hub.docker.com/r/alanfranz/drb-epel-7-x86-64/builds/byquwcmv6kmzxt2wwdvkswb/

I have just forced the sha256 for what is currently (December 2nd) tagged with centos:7, I have forced the install of yum-plugin-ovl (by the way it's already installed) but I still get the error.

**Comment by thaJeztah** [comment] 2016-12-02 22:29
@dmcgowan any ideas? ^^

**Comment by dmcgowan** [comment] 2016-12-05 19:59
@alanfranz  running `rpm --rebuilddb` before the failing commands seems to make it work. Would have to investigate why running it in a previous command still causes it to fail.

**Comment by alanfranz** [comment] 2016-12-06 10:46
I confirm everything is working properly for both centos 6 and 7 if ```plugins=1``` is enabled in yum.conf.

**Comment by xiaoshengaimm** [comment] 2016-12-10 02:31
i got this issue too. however `plugins=1` in `/etc/yum.conf` and `RUN yum install -y yum-plugin-ovl` both not work for me.

my host system is `7.2.1511` with ` 4.4.9-1.el7.elrepo.x86_64`

docker version `1.11.1` with overlayfs

build image from centos 6.6.....

**Comment by alanfranz** [comment] 2016-12-10 13:27
@xiaoshengaimm post your Dockerfile. Also, please be advised that plugins=1 and yum-plugin-ovl must be employed together, not alternatively. The first command enables plugins, the second installs the plugin to support overlay.

centos 6.6 is an old centos release (two years old, I think?) and most probably the fix is not baked in already. Use the latest centos:6 release and most probably you won't experience any issue out of the box, as long as plugins=1 is in yum.conf.

**Comment by jamshid** [comment] 2016-12-23 07:36
@jperrin did something change recently with the centos builds? I swear the "yum" checksum problem with overlay2 was fixed before I made a recent docker pull of centos. 

Maybe yum-utils used to include yum-plugin-ovl but it no longer does?

This is necessary for overlayfs to work, please add yum-plugin-ovl back in. I guess I should file another bug please let me know what project.

```
# docker info
Containers: 48
 Running: 38
 Paused: 0
 Stopped: 10
Images: 81
Server Version: 1.12.4
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.31 GiB
Name: 63
ID: AUQE:OS5D:5RNW:SBMA:ZMSP:M5PG:7URM:5XTE:CSN2:4JVM:5C6E:JPYG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
Insecure Registries:
 127.0.0.0/8
```
```
# cat | docker build -
FROM centos:7.2.1511
RUN yum update -y && yum install -y curl which initscripts net-tools bind-utils
RUN yum install -y openssh-server

Sending build context to Docker daemon 2.048 kB
Step 1 : FROM centos:7.2.1511
7.2.1511: Pulling from library/centos
a2392627bec4: Pull complete 
Digest: sha256:2632572665fc957592ae2332662c11a380fdb869eec172eaa0fa25d673a82ac6
Status: Downloaded newer image for centos:7.2.1511
 ---> feac5e0dfdb2
Step 2 : RUN yum update -y && yum install -y curl which initscripts net-tools bind-utils
...
Step 3 : RUN yum install -y openssh-server
Running transaction
  Installing : fipscheck-lib-1.4.1-5.el7.x86_64                             1/5 
  Installing : fipscheck-1.4.1-5.el7.x86_64                                 2/5 
  Installing : openssh-6.6.1p1-31.el7.x86_64                                3/5 
  Installing : tcp_wrappers-libs-7.6-77.el7.x86_64                          4/5 
  Installing : openssh-server-6.6.1p1-31.el7.x86_64                         5/5

Rpmdb checksum is invalid: dCDPT(pkg checksums): openssh.x86_64 0:6.6.1p1-31.el7 - u
 
The command '/bin/sh -c yum install -y openssh-server' returned a non-zero code: 1
```

**Comment by MattGat** [comment] 2017-04-25 09:44
I have the same issue with Docker version 17.03.1-ce, build c6d412e.

RUN **rpm --rebuilddb** && yum install -y XXX => **This solution has resolved this issue**

**Comment by orodbhen** [comment] 2018-04-02 18:39
If you're unable to install the `yum` plugin because of dependency conflicts (e.g. an older base image), You can work around this with `touch /var/lib/rpm/*`. See the [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1213602) for details.
