### ISSUE TITLE
Stdout / Stderr output in docker run command.

### ISSUE THREAD

**Issue by imrenagi** [docker/docker#26986] opened 2016-09-28 16:21 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**
* Docker version 1.12.1, build 6f9534c
* base image: alpine with perl installed.

I tried to run a container to compile and run perl script. If I run it directly in bash of the container, I can get correct stdout and stderr output. However, when I tried to run `docker run` from my host, I get the output is shown in the wrong order. 

**Steps to reproduce the issue:**
1. Create a perl script named `test.pl`.
```
print STDOUT "Hello from stdout again\n";
print STDERR "Hello from stderr\n";
print STDOUT "Hello from stdout\n";
```
2. run `docker run -v /path/to/perl/:/path/in/container/ the_image:latest perl /path/in/container/test.pl`

**Describe the results you received:**
I got the output in the random order. 

**Describe the results you expected:**
```
Hello from stdout again
Hello from stderr
Hello from stdout
```

**Additional information you deem important (e.g. issue happens only occasionally):**
It is also happen on the other compiler such as lua. python etc.

**Output of `docker version : 1.12.1`:**
the order of the ourput is random. sometimes I got:
```
Hello from stderr
Hello from stdout again
Hello from stdout
```
sometimes i got:
```
Hello from stderr
Hello from stdout
Hello from stdout again
```
and sometimes, i got it right.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I just run it on my local computer.

**Comment by justincormack** [comment] 2016-09-28 17:54
This is normal. `stderr` is not buffered by default, while `stdout` is line buffered, and then they will be interleaved based on timing. This will also happen outside Docker, but may be less visibly non deterministic.

**Comment by imrenagi** [comment] 2016-09-28 19:08
@justincormack  Hoo I see. Should I close this issue or what?

**Comment by thaJeztah** [comment] 2016-09-28 20:15
Let me close the issue yes, as this is not something we can fix (I didn't know about that difference between stdout and stderr, so learned something today as well :tada:)

Thanks for a clear bug report @imrenagi, that's appreciated! And thanks @justincormack for answering

**Closed by thaJeztah** 2016-09-28 20:15 UTC
Labels: area/runtime

**Comment by tianon** [comment] 2017-01-13 01:56
@justincormack any ideas for how to work around this issue?  @yosifkit and I have been playing with solutions for this issue in a `Dockerfile`'s `RUN` line, and even `fflush` in the right places doesn't seem to do the trick :confused:

Is Docker doing any mixed buffering when reading these?

```dockerfile
FROM perl:5.24
RUN ["perl", "-e", "$| = 1; print STDOUT \"this should be first\\n\"; print STDERR \"this should be second\\n\"; print STDOUT \"this should be third\\n\";"]
```

(using the JSON syntax for `RUN` so that we can be sure we've got literally just Perl and nothing else -- no possibility of shell interference)

```console
$ docker build --no-cache .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM perl:5.24
 ---> 9e4b9ea89028
Step 2 : RUN perl -e $| = 1; print STDOUT "this should be first\n"; print STDERR "this should be second\n"; print STDOUT "this should be third\n";
 ---> Running in 440b05094c20
this should be second
this should be first
this should be third
 ---> 4fa185e67644
Removing intermediate container 440b05094c20
Successfully built 4fa185e67644

$ docker build --no-cache .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM perl:5.24
 ---> 9e4b9ea89028
Step 2 : RUN perl -e $| = 1; print STDOUT "this should be first\n"; print STDERR "this should be second\n"; print STDOUT "this should be third\n";
 ---> Running in bcb65a81db02
this should be first
this should be third
this should be second
 ---> 98580ab270ed
Removing intermediate container bcb65a81db02
Successfully built 98580ab270ed

$ docker build --no-cache .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM perl:5.24
 ---> 9e4b9ea89028
Step 2 : RUN perl -e $| = 1; print STDOUT "this should be first\n"; print STDERR "this should be second\n"; print STDOUT "this should be third\n";
 ---> Running in 3fd0d9b94ef4
this should be second
this should be first
this should be third
 ---> 4b83e48efcd8
Removing intermediate container 3fd0d9b94ef4
Successfully built 4b83e48efcd8
```

**Comment by tianon** [comment] 2017-01-13 01:58
Quoted block from [perlvar](http://perldoc.perl.org/perlvar.html) regarding what `$|` is, for reference:

> `$|`
>
> > If set to nonzero, forces a flush right away and after every write or print on the currently selected output channel. Default is 0 (regardless of whether the channel is really buffered by the system or not; $| tells you only whether you've asked Perl explicitly to flush after each write). STDOUT will typically be line buffered if output is to the terminal and block buffered otherwise. Setting this variable is useful primarily when you are outputting to a pipe or socket, such as when you are running a Perl program under rsh and want to see the output as it's happening. This has no effect on input buffering. See getc for that. See select on how to select the output channel. See also IO::Handle.
>
> > Mnemonic: when you want your pipes to be piping hot.

**Comment by tianon** [comment] 2017-01-13 02:01
And again with just `docker run` to show a simpler method of reproduction:
```console
$ docker run -it --rm perl:5.24 perl -e '$| = 1; print STDOUT "this should be first\n"; print STDERR "this should be second\n"; print STDOUT "this should be third\n";'
this should be first
this should be second
this should be third
$ docker run -it --rm perl:5.24 perl -e '$| = 1; print STDOUT "this should be first\n"; print STDERR "this should be second\n"; print STDOUT "this should be third\n";'
this should be first
this should be second
this should be third
$ docker run -it --rm perl:5.24 perl -e '$| = 1; print STDOUT "this should be first\n"; print STDERR "this should be second\n"; print STDOUT "this should be third\n";'
this should be first
this should be second
this should be third

$ docker run --rm perl:5.24 perl -e '$| = 1; print STDOUT "this should be first\n"; print STDERR "this should be second\n"; print STDOUT "this should be third\n";'
this should be first
this should be third
this should be second
$ docker run --rm perl:5.24 perl -e '$| = 1; print STDOUT "this should be first\n"; print STDERR "this should be second\n"; print STDOUT "this should be third\n";'
this should be second
this should be first
this should be third
$ docker run --rm perl:5.24 perl -e '$| = 1; print STDOUT "this should be first\n"; print STDERR "this should be second\n"; print STDOUT "this should be third\n";'
this should be first
this should be third
this should be second
```

(it works with `-it` because with `-t` we get TTY muxing, which seems to work properly, rather than Docker muxing, which appears to have some buffering somewhere still)
