### ISSUE TITLE
Open SuSe 13.1 : "Unable to find image 'opensuse:latest' locally

### ISSUE THREAD

**Issue by phamhp** [docker/docker#15158] opened 2015-07-30 16:38 UTC
Hi guys,
 i followed the installation for OpenSuSE on : "http://docs.docker.com/installation/SUSE/". 
But when I ran the command : "sudo docker run --rm -i -t opensuse /bin/bash" , i got the error: 

---------------------------------------------------------------------------------------
abc--------------:~ #  sudo docker run --rm -i -t opensuse /bin/bash
Unable to find image 'opensuse:latest' locally
latest: Pulling from opensuse

5b8dd08af89b: Pulling fs layer
5b8dd08af89b: Error pulling dependent layers
d6b241b32a2d: Error pulling image (latest) from opensuse, endpoint: https://registry-1.docker.io/v1/, Server error: Status 0 while fetching image layer (5b8dd08af89b84564b09fc0dfe96cfdfee0ff650d50cf4f3683c6367a1295d6b241b32a2d: Error pulling image (latest) from opensuse, Server error: Status 0 while fetching image layer (5b8dd08af89b84564b09fc0dfe96cfdfee0ff650d50cf4f3683c6367a1295317)
Error pulling image (latest) from opensuse, Server error: Status 0 while fetching image layer (5b8dd08af89b84564b09fc0dfe96cfdfee0ff650d50cf4f3683c6367a1295317)
------------------------------------------------------------------------------------------------------------------
docker version : 
abc----------------:~ # docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

abc---------------:~ # docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-8:2-1182468-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 15.81 GB
 Metadata Space Used: 733.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.03.01 (2011-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.11.6-4-desktop
Operating System: openSUSE 13.1 (Bottle) (x86_64) (containerized)
CPUs: 2
Total Memory: 7.814 GiB
Name: vmdur-ave20
ID: 3CRQ:DPNW:RYJW:IGBY:GABW:ZURT:TTKJ:B3G4:IBKC:QBUX:QNX7:SDSF

abc-----------:~ # uname -a
Linux abc---------- 3.11.6-4-desktop #1 SMP PREEMPT Wed Oct 30 18:04:56 UTC 2013 (e6d4a27) x86_64 x86_64 x86_64 GNU/Linux
----------------------------------------------------------------------------------------------------------------
Steps to Reproduce:
1) Installed OpenSuse 13.1 on Vmware VM.
2) configure network, disable OS's firewall , start SSH service
3) follow exactly steps on : http://docs.docker.com/installation/SUSE/

Additional info: I installed docker at work using my company's infrastructure. I'm not sure the company's firewall causing the issue. Also, I installed docker on VMware VM (8GB ram, 60GB HDD, 2CPUs).

**Comment by Evalle** [comment] 2015-07-31 06:17
Hello @phamhp I followed installation instructions and it works pretty great for me. 

evalle:~> sudo docker run --rm -it opensuse /bin/bash
Unable to find image 'opensuse:latest' locally
latest: Pulling from opensuse

5b8dd08af89b: Pull complete 
d6b241b32a2d: Already exists 
opensuse:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.

Digest: sha256:d1e63126409bb816d11891776c9315f6432f66102825cde6a0055e2cfddcd3a4
Status: Downloaded newer image for opensuse:latest
bash-4.2#

**Comment by phamhp** [comment] 2015-07-31 15:36
Thannks @Evalle for the answer. I think the my company's firewall blocks it. I'll try it again at home.

**Comment by thaJeztah** [comment] 2015-08-02 14:52
I'm going to close this issue, because I suspect this is not a bug in Docker, but feel free to comment here if you think I closed this by mistake.

@phamhp please let us know if running Docker from home resolved your problem :-)

**Closed by thaJeztah** 2015-08-02 14:52 UTC
