### ISSUE TITLE
Docker rmi unable to remove images

### ISSUE THREAD

**Issue by TheBeeMan** [docker/docker#22178] opened 2016-04-20 02:35 UTC
I have  a bunch of test images on my host i use.
**docker rmi `docker images |grep "hello-world" | awk '{print $1}'**` to delete one image.on excution, i got error.
Error response from docker daemon :Error response from daemon: conflict: unable to remove repository reference "hello-world" (must force) - container 3061de2e8c9c is using its referenced image 690ed74de00f
docker  ps | grep 3061de2e8c9c 
on which i got nothing.
docker attach 3061de2e8c9c 
on which i got error: You cannot attach to a stopped container, start it first.
So there is no active containers, then why i could not delete the image?

**Comment by HackToday** [comment] 2016-04-20 03:13
because you have stopped container, please use
`docker ps -a` to see all containers

maybe https://docs.docker.com/ is good place for you learn

**Comment by thaJeztah** [comment] 2016-04-20 14:33
closing, because (as @HackToday explained), this is not a bug

**Closed by thaJeztah** 2016-04-20 14:33 UTC

**Comment by linyuanpeng** [comment] 2017-05-12 09:07
you can remove it force
such as 
docker rmi -f 2234oi23u4io2

**Comment by thaJeztah** [comment] 2017-05-12 09:15
Using `--force` to remove an image that's in use by a container is not really recommended. Remove the container if it's no longer needed.

**Comment by ljavierrivera** [comment] 2017-05-12 18:56
@thaJeztah - I'm getting similar myself (found this thread via google search).

Please see steps to diagnose after attempting docker rmi IMAGENAME and receiving message:

~$ docker rmi e5d9538a77db
Error response from daemon: conflict: unable to delete e5d9538a77db (must be forced) - image is referenced in multiple repositories
~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
~$ docker ps -a -q
~$

As you can see no running containers yet the images can't be deleted. I'm on a Mac running Docker Toolbox

**Comment by thaJeztah** [comment] 2017-05-15 13:00
@ljavierrivera different error message;

```
image is referenced in multiple repositories
```

Which means you're trying to remove an image by its `ID`, however the image is tagged under multiple names. Docker then refuses to remove the image, because it would remove _multiple_ image in a single  remove. You can still remove the individual images by name. If you don't have containers running, you can `--force` delete the image in that case.

**Comment by jiangbingo** [comment] 2017-06-06 07:04
get it.

**Comment by djangofan** [comment] 2017-10-24 19:38
Yes, the command `docker image prune` worked for me followed by  `docker rmi ...`

**Comment by nitish-nyllabs** [comment] 2018-04-10 14:38
I receive this error `Error response from daemon: conflict: unable to delete b472d6a9286d (cannot be forced) - image is being used by running container 8c2009966994` . 

If I stop all the containers built on this image and then they spin up again very fast due to my `docker-compose.yml`.

`version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ndabas333/hola:newtest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
` 
This image doesn't exist on my registry now so help me to delete it along with the containers.

**Comment by MahmoodKamali** [comment] 2018-12-15 12:05
Use the below command to remove it:

"docker rmi --force DOCKER_IAMGE_NAME"

It works 100%

**Comment by thaJeztah** [comment] 2018-12-15 12:11
Related: https://github.com/moby/moby/issues/30722
