### ISSUE TITLE
docker pull works but docker-compose pull doesn't

### ISSUE THREAD

**Issue by DreamFlasher** [docker/docker#25230] opened 2016-07-29 14:00 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.95 GiB
Name: moby
ID: KN65:HRHW:EFIE:IYKF:EOLD:2P2G:UZX3:5LAT:UZUX:7LIP:3XCF:F3KI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical, Windows 10 x64, docker beta, cygwin

**Steps to reproduce the issue:**
Docker compose file contains private image
1. In Cygwin `docker-compose pull`

**Describe the results you received:**
```
Pulling redis (redis:latest)...
latest: Pulling from library/redis
Digest: sha256:b50f15d427aea5b579f9bf972ab82ff8c1c47bffc0481b225c6a714095a9ec34
Status: Image is up to date for redis:latest
Pulling mysql (mysql:latest)...
latest: Pulling from library/mysql
Digest: sha256:a9a5b559f8821fe73d58c3606c812d1c044868d42c63817fa5125fd9d8b7b539
Status: Image is up to date for mysql:latest
Pulling delivery_worker (private/image:latest)...
Pulling repository docker.io/private/image
Error: image private/image:latest not found
```

**Describe the results you expected:**
The same as `docker pull private/image`, which outputs:
```
Using default tag: latest
latest: Pulling from private/image
1bb8eaf3d643: Download complete
...
```
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by icecrime** [comment] 2016-07-29 17:00
Ping @aanand @dnephin!

**Comment by aanand** [comment] 2016-08-01 12:09
Looks like a duplicate of https://github.com/docker/compose/issues/3683. @DreamFlasher, could you go to that issue and paste the output of `docker-compose --verbose pull`?

**Comment by thaJeztah** [comment] 2016-08-01 12:27
Thanks @aanand 

@DreamFlasher let me close this issue here, because this looks like an issue with docker-compose, but please add the requested information to https://github.com/docker/compose/issues/3683

**Closed by thaJeztah** 2016-08-01 12:27 UTC
Labels: version/1.12
