### ISSUE TITLE
`docker cp container:path/to/file host_path` creates spurious directory on host

### ISSUE THREAD

**Issue by exarkun** [docker/docker#9747] opened 2014-12-19 14:37 UTC
```
user@host:~/path# docker run --name target -d busybox sh -c 'sleep 1000'
076a3d139d2d864b4a2574a6b3e689125a8b7a4b16f53e44d983f5971ce90dc5
user@host:~/path# docker exec target sh -c 'touch foo'
user@host:~/path# docker cp target:foo container_foo
user@host:~/path# ls
container_foo
user@host:~/path# ls container_foo/
foo
user@host:~/path# 
```

This is surprising.  One would expect that this would create a regular (non-directory) file on `host` at `~/path/container_foo` with the contents of `/foo` from the container.  Instead a directory is created on `host` at `~/path/container_foo` containing the `foo` file.

**Comment by jfrazelle** [comment] 2015-02-26 22:14
closing as duplicate of https://github.com/docker/docker/issues/4272

**Closed by jfrazelle** 2015-02-26 22:14 UTC
