### ISSUE TITLE
Provide TO syntax to the Dockerfile

### ISSUE THREAD

**Issue by warden** [docker/docker#13774] opened 2015-06-05 18:44 UTC
Currently building an arbitrary Dockerile results in an image that does not have a repository nor a tag name.
It would be useful to have a syntax similar to FROM that is defining the base image, to actualy provide the *default* repository and tag name, so that they do not have to be passed with -t flag to the docker build command.
This will make it easier to create new images from new versions of software, just by bumping some number that will be for both, installing the actual package and for the tag name of the docker build.

Example:

```
FROM repository/base-linux:latest
ENV PKG_VERSION 2.3.4
TO repository/jenkins:$PKG_VERSION
...
...
RUN apt-get install jenkins=$PKG_VERSION

```

**Comment by rysiekpl** [comment] 2015-06-05 22:48
This would also seem to allow to inherit (via `FROM`) easily from new Dockerfiles, so that it would be possible to have a directory with a Dockerfile that builds a "parent" image, and another directory with a Dockerfile that uses that image as the base image, without a). having to manually set image names while building; b). publishing on the hub.

This would be great for more advanced uses, as it would allow for building a whole infrastructure of related images easily.

**Comment by thaJeztah** [comment] 2015-06-06 22:12
Hi @warden, I'm going to close this issue, because I think this is a duplicate of https://github.com/docker/docker/issues/5603. Please continue the discussion on https://github.com/docker/docker/issues/5603.

Feel free to comment here if you think I closed this by mistake

**Closed by thaJeztah** 2015-06-06 22:12 UTC
