### ISSUE TITLE
git ls-remote fails on volume with .git

### ISSUE THREAD

**Issue by ain** [docker/docker#14594] opened 2015-07-13 16:06 UTC
Description of problem: following command fails on mounted volumes with a project that has `.git/`:

```
git ls-remote --tags --heads https://github.com/BeSite/jQuery.mmenu.git
```

`docker version`: 

```
Docker version 1.6.2, build 7c8fca2
```

`docker info`: 

```
Containers: 6
Images: 120
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 132
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 4
Total Memory: 1.957 GiB
Name: boot2docker
ID: VVFX:YQ6A:S2NQ:LGR4:32O6:2V5Z:UGH6:UQGP:IT7J:TSFY:MQAA:OLGX
Debug mode (server): true
Debug mode (client): false
Fds: 36
Goroutines: 83
System Time: Mon Jul 13 15:58:17 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: sennheiser
Registry: [https://index.docker.io/v1/]
```

`uname -a`: 

```
Darwin Ains-MacBook-Pro.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
```

Environment details (AWS, VirtualBox, physical, etc.): VirtualBox

How reproducible: always.

Steps to Reproduce:

1. Create Docker Compose file of several containers, the main container being Ubuntu 14.04
2. Mount a Github-cloned project with `.git` under `/docker`
3. Access the container
4. Go to `/docker`
5. Run 
```
git ls-remote --tags --heads https://github.com/BeSite/jQuery.mmenu.git
```

Actual Results:
```
deploy@e9ee597cb797:/docker$ git ls-remote --tags --heads https://github.com/BeSite/jQuery.mmenu.git
fatal: Invalid gitfile format: .git
```

Expected Results:
```
$ git ls-remote --tags --heads https://github.com/BeSite/jQuery.mmenu.git
ccfca8a3e0e1f9c0057609db194c8ddb3d4b828b	refs/heads/master
...
ccfca8a3e0e1f9c0057609db194c8ddb3d4b828b	refs/tags/v5.3.2
```

Additional info: 
-  `git version 2.4.5`
- same command succeeds outside of the mounted volume, e.g. `/tmp`

**Comment by phemmer** [comment] 2015-07-13 17:58
Works for me. This is likely an issue with docker compose. I'd file an issue [over there](https://github.com/docker/compose/issues)

```
# mkdir /tmp/docker

# cd /tmp/docker

# git clone https://github.com/BeSite/jQuery.mmenu.git
Cloning into 'jQuery.mmenu'...
remote: Counting objects: 2656, done.
remote: Total 2656 (delta 0), reused 0 (delta 0), pack-reused 2656
Receiving objects: 100% (2656/2656), 1.07 MiB | 581.00 KiB/s, done.
Resolving deltas: 100% (1705/1705), done.
Checking connectivity... done.

# docker run -ti --rm -v /tmp/docker:/docker ubuntu:14.04 bash -c '( apt-get update && apt-get -y install git ) &>/dev/null && cd /docker && git ls-remote --tags --heads https://github.com/BeSite/jQuery.mmenu.git'
ccfca8a3e0e1f9c0057609db194c8ddb3d4b828b	refs/heads/master
c18123bf7b1a8f293b75c89f7ae28f67a28085fb	refs/tags/v4.0.3
d7ab7b02293650d8b091b766f0c45549934724af	refs/tags/v4.0.3^{}
fc74c1d8c9c6c2c259f3c8ee26d027a9abd56e2e	refs/tags/v4.0.4
0f776f8d622a56ef8c608af889e58119b92f8926	refs/tags/v4.0.4^{}
2ef16d3549d3c1695f7ae699090b4f429eaa6ad5	refs/tags/v4.1.0
c6f0eb510bc6e317bc6cc641813a57eb67a9121c	refs/tags/v4.1.0^{}
98dbccc84bd735a083504f718dd73bfb83e5daa1	refs/tags/v4.1.1
bbe4083799fb3e21f1cfbeee64b03abe57c10c1d	refs/tags/v4.1.1^{}
ada8323c019a455b0bc76f3e8fde1639ba1282b1	refs/tags/v4.1.2
e36390944de92d9b2fd65dd34283f1c3c6037e8a	refs/tags/v4.1.2^{}
75e1cc8d067a5b435833d4b4de45d764bcea3514	refs/tags/v4.1.3
c9f7976229abe8a445e5a45c79bd83bb5740de1c	refs/tags/v4.1.3^{}
cf014a858772f29b945369d76184db0a114c5a67	refs/tags/v4.1.4
939f7782e1e0ab23cb3b529c1b1d642a49c93c60	refs/tags/v4.1.4^{}
a3f419ff62c03cf2780b34e95a918e7314eb1c1f	refs/tags/v4.1.5
90fd8bb69c88b975af4710d8e8dc6c7bb8902df4	refs/tags/v4.1.5^{}
609d7b8faed11bf97a0d82c8311ac0f702e6d793	refs/tags/v4.1.6
1d11df4e990a6d6c6db80002c4000ebf8bd48e59	refs/tags/v4.1.6^{}
2281f1e3fd553d00c81b951445e9ecb7d609bab0	refs/tags/v4.1.7
072d0268dc4cb290695ede78b709432cd0556bb3	refs/tags/v4.1.7^{}
b72fb23df621a8d18f72a7da610a5b7891354fc5	refs/tags/v4.1.8
acaaec60cac382f6f090e74704b0c2e4b432f041	refs/tags/v4.1.8^{}
1a5de6f051690b4943829aafd5c366c622354958	refs/tags/v4.1.9
437fa1c450faac25265cc3727be7172bf9e3dc5f	refs/tags/v4.1.9^{}
f8352e9f565976353a28e518c2ece0483593c0f6	refs/tags/v4.2.0
4d536fa2e51ac09a98f6845a627dfaaf781145d2	refs/tags/v4.2.0^{}
d05642329ecb4614b228fdfc68ce5840e9a61550	refs/tags/v4.2.1
86d903636ae71d4afa5af6ec7c7c817b031f9ff8	refs/tags/v4.2.1^{}
dd0d76c391b4978b5a9d8692063ceb4d01c35216	refs/tags/v4.2.2
6b1855790f3a87bff0d6c0cbbd30ee39243c2153	refs/tags/v4.2.2^{}
398b729c1bb419150a5a99bc2eb3c2995e369a5b	refs/tags/v4.2.3
afcb6482701b02e40156c87d9d25cd83a841ad97	refs/tags/v4.2.3^{}
1d501a7a3083b07b10518cff279be666d8017d22	refs/tags/v4.2.4
48b5dbed0051d990285f17a0713c3ed9b8957e9b	refs/tags/v4.2.4^{}
1ceb1bf419ef97e2a5b9813a28e1e49ab0d7a6a7	refs/tags/v4.2.5
703ef2959fe19233b24b21ffa6f5869cceb8f075	refs/tags/v4.2.6
a866792aa45d4dcc96e18c9f31e7423472026fbe	refs/tags/v4.2.7
b8a8f42dddccb30df12d8a89344b4bfe2c03d082	refs/tags/v4.3.0
73584b4b8267526d98085489a8b31c2f34155427	refs/tags/v4.3.1
65e3a6b43a2e8c77abaeae7c86ccc53bc57cd1ee	refs/tags/v4.3.2
7d8b00a21bdd85aaa0e4cc27cff06c78d5bb6d64	refs/tags/v4.3.3
170b14bd27e6369e05c1e87ad0f1f63027d5bd40	refs/tags/v4.3.4
43946cb74ea4be98b1e422e2063e47ec9fa710ca	refs/tags/v4.3.5
fdf1e3086cb4521d3c8397c2d8a4b81479a80bae	refs/tags/v4.3.6
3f915ff5bb480e89aacd5465dea35793becf18e8	refs/tags/v4.4.0
407ba4ccb79f808ccbfbecc0b8a198f834569533	refs/tags/v4.4.1
0cbaa6fc8f91b14265330878eae46da50a5bc933	refs/tags/v4.4.2
d25f0532685ba4280582908f1416bf8699b08238	refs/tags/v4.5.0
ceb0168f34709f2ba0436f14ece2fc710772e34f	refs/tags/v4.5.1
87a6d0f7d0b213cfd0090dd0c0848050813c0040	refs/tags/v4.5.2
e8b3ba084aaface176b866a8e1fec871d725370d	refs/tags/v4.5.3
d0384b86278db1107281fa65e683a410477b7122	refs/tags/v4.5.4
dde1b7072c842ac778ce9d6cf1ffeaef98b3078a	refs/tags/v4.5.5
c22b5f76e392ad0e776e6fc0bf95475acf9158ad	refs/tags/v4.5.6
ac79b660e3cea46a45ea98c46d97878a25d8d02c	refs/tags/v4.5.7
3d3fe88d0e05601607c34cdac730ec6c96206258	refs/tags/v4.6.0
480c0fb4f95dc31657192674cd76facce0a9a628	refs/tags/v4.6.1
cb2828e072b180bd0976da2e427f6e556cd16421	refs/tags/v4.6.2
5b57fa8e0a9414d008efc5b9cad4a1b646f944e7	refs/tags/v4.6.3
40388923ae545ac982ca2933047e28d6c1366eaa	refs/tags/v4.6.4
6faf95633469b35d45f84b09aead604329c193db	refs/tags/v4.7.0
f065f8410e692b9c1217830ca97f9f722c4e8526	refs/tags/v4.7.1
34eb2e70f95f90044f74a537c364bf6c338abc3e	refs/tags/v4.7.2
c7133dc69f6f24e8fd9b8b9d33023d4dc59555c0	refs/tags/v4.7.3
8269682e244706c7dc62831bc3d36358db7d6b5d	refs/tags/v4.7.4
156d89f47543e79073fe089093e21abe9d999a8b	refs/tags/v4.7.5
abc8b1219372a99329987f4446111ba27fd4277a	refs/tags/v5.0.0
925266190d43a295935247e8883bf8c3af397ffe	refs/tags/v5.0.1
3eb25cd80d47ee996f7b3dec1f9b8221fbfdf6e1	refs/tags/v5.0.2
0ba1478eeba0499452a5284a757e7c4019f8147f	refs/tags/v5.0.3
c8349e6306372a3be61a578536c098999057ee41	refs/tags/v5.0.4
c3b53f82792e56665badc0f4c6cc5f0e62261899	refs/tags/v5.1.0
9992f684b8e2ab806cc3359525782bdaba3b1b52	refs/tags/v5.1.1
33af90874aa279e505ea65ef79e31022bc36d30d	refs/tags/v5.1.2
0472961e5966a64d7abce3139a15c3c61bc28165	refs/tags/v5.2.0
04485a52b39b9bcb60527a278024a47659583bcf	refs/tags/v5.3.0
150f24dacb2fe9f45fd7ead69a8e4c4f230ba55e	refs/tags/v5.3.1
ccfca8a3e0e1f9c0057609db194c8ddb3d4b828b	refs/tags/v5.3.2
```

**Comment by thaJeztah** [comment] 2015-07-13 18:10
I'm also unable to reproduce. This could be related to boot2docker / VirtualBox Guest Additions ; is the Git clone on your Mac, and inside your /Users/ directory?

I'm going to close this issue, because I don't think this is a bug in Docker, but feel free to comment here if you think I closed this by mistake. If you think this is a bug in Docker, could you provide a minimal repro-case, describing the exact steps to reproduce this issue (if possible without using docker-compose)

**Closed by thaJeztah** 2015-07-13 18:10 UTC
