### ISSUE TITLE
stdin is not tty causes container to exit

### ISSUE THREAD

**Issue by DrakeW** [docker/docker#14277] opened 2015-06-30 06:38 UTC
`docker version:
Docker version 1.6.2, build 7c8fca2`
`uname -a: Linux ip-xx-x-x-xxx 3.14.44-32.39.amzn1.x86_64 #1 SMP Thu Jun 11 20:33:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

We are starting a container and run task using aws ecs service, the image got pulled successfully according to the task definition but when the container trying to run the task it exited because of "stdin is not tty". We manually reproduced that error by running `docker run {image_name}` but didn't figure out a way to fix it. Here's the output:

    Initializing built-in extension Generic Event Extension
    Initializing built-in extension SHAPE
    Initializing built-in extension MIT-SHM
    Initializing built-in extension XInputExtension
    Initializing built-in extension XTEST
    Initializing built-in extension BIG-REQUESTS
    Initializing built-in extension SYNC
    Initializing built-in extension XKEYBOARD
    Initializing built-in extension XC-MISC
    Initializing built-in extension SECURITY
    Initializing built-in extension XINERAMA
    Initializing built-in extension XFIXES
    Initializing built-in extension RENDER
    Initializing built-in extension RANDR
    Initializing built-in extension COMPOSITE
    Initializing built-in extension DAMAGE
    Initializing built-in extension MIT-SCREEN-SAVER
    Initializing built-in extension DOUBLE-BUFFER
    Initializing built-in extension RECORD
    Initializing built-in extension DPMS
    Initializing built-in extension Present
    Initializing built-in extension DRI3
    Initializing built-in extension X-Resource
    Initializing built-in extension XVideo
    Initializing built-in extension XVideo-MotionCompensation
    Initializing built-in extension SELinux
    Initializing built-in extension GLX
    stdin: is not a tty

We are using Xvfb to run tests and here are the related dependencies in our dockerfile

    # install virtual display 
    RUN apt-get -qy install xvfb
    RUN apt-get -qy install x11-xkb-utils
    RUN apt-get -qy install xserver-xorg-core
    RUN apt-get -qy install xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic

Does anyone happen to know how to fix this? Thanks a lot.

**Comment by phemmer** [comment] 2015-06-30 11:32
I believe you want the `-t` argument for `docker run`.

For example:

```
# docker run ubuntu tty 
not a tty

# docker run -t ubuntu tty 
/dev/console

```

**Comment by Munchery-JunyuWang** [comment] 2015-06-30 17:00
thanks for your response, but the problem is we create the task by clicking the run task button on the task definition page of amazon ecs, so that we can't append options to the docker run command.

**Comment by phemmer** [comment] 2015-06-30 17:04
This sounds like an issue with AWS ECS. I would recommend opening a ticket with them.

**Comment by cpuguy83** [comment] 2015-06-30 17:41
Closing since this is specifically an issue with how ECS is shelling out to the docker CLI.

**Closed by cpuguy83** 2015-06-30 17:41 UTC
