### ISSUE TITLE
BUG Report "cannot enable tty mode on non tty input"

### ISSUE THREAD

**Issue by edpichler** [docker/docker#16089] opened 2015-09-04 19:15 UTC
List the steps to reproduce the issue:
1. docker pull ubuntu
2. docker run -it ubuntu /bin/bash

Describe the results you received:
```
>docker run -it ubuntu /bin/bash
cannot enable tty mode on non tty input
```
Describe the results you expected:
Acess thecontainer bash.

Provide additional info you think is important:
Doing the same on the VirtualBox created VM (default), it works perfectly.

My Docker version:

```
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

```

```
$ docker info
Containers: 16
Images: 16
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: HSOL:VFS6:IY4W:NHGZ:2WTW:WYXL:KASF:DRXH:RJFL:VC6R:RFNX:DVQ2
Debug mode (server): true
File Descriptors: 9
Goroutines: 20
System Time: 2015-09-04T19:16:44.413936375Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```
```

$ uname -a
MINGW64_NT-6.1 SOFT020-183 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys
```

**Comment by thaJeztah** [comment] 2015-09-05 23:58
Thanks for reporting @edpichler, however, this is a duplicate of https://github.com/docker/docker/issues/12469. Also see this comment on that issue for more information; https://github.com/docker/docker/issues/12469#issuecomment-137161775

I'm going to close this issue, please subscribe to https://github.com/docker/docker/issues/12469 to stay informed on progress

**Closed by thaJeztah** 2015-09-05 23:58 UTC
