### ISSUE TITLE
Cannot mount local file to container: oci runtime error

### ISSUE THREAD

**Issue by wmorrell** [docker/docker#23920] opened 2016-06-24 00:27 UTC
**Output of `docker version` (broken case):**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu Jun  2 03:53:12 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker version` (working case):**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu Jun  2 03:53:12 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info` (broken case):**

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 30
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 106
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.755 GiB
Name: public-edd
ID: VSBG:VK4J:BSRK:3HV5:AH64:FL5J:UOGK:AWR4:5Q2T:UR67:B2DY:HIHD
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Labels:
 provider=generic
```

**Output of `docker info` (working case):**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 125
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 221
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: default
ID: Y77V:FBLF:LBXY:FN5L:FOCA:3I3K:XBBC:G4AW:HUF2:EMFV:PYKX:75IW
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 31
 System Time: 2016-06-24T00:23:49.261112917Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Local (client) machine is OS X 10.11.5, daemon (server) is Debian jessie. Configured with docker-machine using generic driver.

**Steps to reproduce the issue:**
1. Have a local (client) file located at ./docker_services/nginx/nginx.conf
2. ```docker run -it --rm -v `pwd`/docker_services/nginx/nginx.conf:/etc/nginx/nginx.conf --name temp_nginx nginx:1.9 /bin/bash```

**Describe the results you received:**
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: not a directory".

**Describe the results you expected:**
Should get a bash shell, be able to `cat /etc/nginx/nginx.conf` and see same contents of file on local system.

**Additional information you deem important (e.g. issue happens only occasionally):**
While there are a few other tickets with this oci runtime error, several of the "me toos" appear to be different problems. This one seems specific to using the generic docker-machine driver, as it works when I use the virtualbox driver to a VM running on my own machine.

**Comment by vdemeester** [comment] 2016-06-24 09:06
@wmorrell although the error is not really *speaking*, this is expected to fail.

When you use `-v` to setup a volume, the format is `-v host:container`, and the host is the machine where the daemon runs, not the client. So, on your host machine, the `$(pwd)/docker_services/nginx/nginx.conf` is more likely to not exists (folders and file). 

It's is most of the time *working* with the virtualbox driver because it sets up shared folder between the *client* (the mac in that case) and the *host* (the virtualbox machine).

**Comment by wmorrell** [comment] 2016-06-24 18:35
Aha. I got used to working with the virtualbox driver, and did not realize I was taking advantage of special magic. It may be useful to have the client detect when a path is missing on the host, but exists on the client, and issue a warning.

I think this may still be a bug, as even if the volume mount fails, the container should still launch and present a shell? I'm seeing the docker client exit, without the container starting at all.

**Comment by jmtuley** [comment] 2016-07-06 15:33
@vdemeester I've been having an issue with Docker for Mac where mounted files appear as directories inside the container. Would the underlying cause be the same – “the host is the machine where the daemon runs, not the client,” as you say above?

**Comment by dsheets** [comment] 2016-07-06 22:34
@jmtuley please see [the Docker for Mac documentation](https://docs.docker.com/docker-for-mac/osxfs/#namespaces) for more information about what various paths do when you attempt to bind mount them. In Beta 17, if a bind mount path was under `/Users`, `/Volumes`, `/tmp`, or `/private` it would mount from OS X and, if it was not, it would mount from the Linux VM. In Beta 18 (partially released pending hotfix), these export paths are user-configurable in the GUI and attempting to mount a non-existent but unexported path would create a new empty directory in the VM. This situation now results in an error message in Beta 18 telling you to either export the path or create the directory.

**Comment by thaJeztah** [comment] 2016-07-07 22:46
@jmtuley the reason it doesn't fail is that the daemon will create a new directory, and use that as a bind-mount if the path if it is not found. We wanted to deprecate that behavior (exactly for this reason), but unfortunately it was too much of a breaking change, so we decided to keep it (see https://github.com/docker/docker/pull/19953#issuecomment-198024624).

I'm going to close this issue, because this is not a bug, but I know it can be confusing

**Closed by thaJeztah** 2016-07-07 22:46 UTC
Labels: version/1.11
