### ISSUE TITLE
`docker build` fails to pull base image from private repository

### ISSUE THREAD

**Issue by pfaffle** [docker/docker#31072] opened 2017-02-16 02:38 UTC
**Description**

A Dockerfile which specifies a base image that comes from a private Docker repository fails to build with an 'image not found' error if the image is not already locally cached. However, if you first `docker pull` the image and then attempt a `docker build`, the build succeeds. Below is a quick -slightly sanitized- transcript showing the issue (I've already authenticated with my private repo at this point):

```
C:\Users\pfaffle\git\activemq> docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
C:\Users\pfaffle\git\activemq> docker build -t myproject/activemq .
Sending build context to Docker daemon 10.75 kB
Step 1/2 : FROM 10.x.y.z/rmohr/activemq:5.14.0-alpine
Pulling repository 10.x.y.z/rmohr/activemq
Error: image rmohr/activemq:5.14.0-alpine not found
C:\Users\pfaffle\git\activemq> docker build -t myproject/activemq .
Sending build context to Docker daemon 10.75 kB
Step 1/2 : FROM 10.x.y.z/rmohr/activemq:5.14.0-alpine
Pulling repository 10.x.y.z/rmohr/activemq
Error: image rmohr/activemq:5.14.0-alpine not found
C:\Users\pfaffle\git\activemq> docker pull 10.x.y.z/rmohr/activemq:5.14.0-alpine
5.14.0-alpine: Pulling from rmohr/activemq
3690ec4760f9: Pull complete
cfdb77eb56b4: Pull complete
b8876cfd96b2: Pull complete
3c5963244339: Pull complete
Digest: sha256:c91f2419d5d501b8636d5c7c36b7bfc12604e0742b5675673a5dd139352e364c
Status: Downloaded newer image for 10.x.y.z/rmohr/activemq:5.14.0-alpine
C:\Users\pfaffle\git\activemq> docker build -t myproject/activemq .
Sending build context to Docker daemon 10.75 kB
Step 1/2 : FROM 10.248.93.25/rmohr/activemq:5.14.0-alpine
 ---> 7b65c454d1c3
Step 2/2 : COPY activemq.xml /opt/activemq/conf/activemq.xml
 ---> Using cache
 ---> 1b195a49bcba
Successfully built 1b195a49bcba
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```

My Dockerfile:
```
FROM 10.x.y.z/rmohr/activemq:5.14.0-alpine
COPY activemq.xml /opt/activemq/conf/activemq.xml
```

**Steps to reproduce the issue:**
1. `docker pull rmohr/activemq:5.14.0-alpine` (or some other image)
2. `docker tag rmohr/activemq:5.14.0-alpine [your_private_repo]/rmohr/activemq:5.14.0-alpine`
3. `docker push [your_private_repo]/rmohr/activemq:5.14.0-alpine`
4. Create a simple Dockerfile which starts with `FROM [your_private_repo]/rmohr/activemq:5.14.0-alpine`
5. `docker build .` in that directory

**Describe the results you received:**
Got an error:
```
Error: image rmohr/activemq:5.14.0-alpine not found
```

**Describe the results you expected:**
Docker should have pulled the base image down and built my Docker image.

**Additional information you deem important (e.g. issue happens only occasionally):**
I'm building this on Windows, as you can tell from the transcript above. My private repo is an insecure one, and I've configured the Docker service to ignore that according to the documentation.

I found a few previously filed issues that appear to be the same problem, but they were supposed to be fixed in earlier versions of Docker. Here's one: #14249
**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: GNQI:4BTO:YTL2:2A5F:QAR4:YSQI:QP7W:ID5T:R2VU:AJWM:ALXX:WH4J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 10.x.y.z
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker is running on a physical Windows desktop machine.

**Comment by tonistiigi** [comment] 2017-02-18 00:18
Could not reproduce. Can you provide daemon logs and logs from the registry?

**Comment by pfaffle** [comment] 2017-02-23 22:16
I don't see a lot of useful stuff in the daemon logs, sadly. Here's what I got:

```
[13:43:54.157][ApiProxy       ][Info   ] proxy >> GET /_ping
[13:43:54.157][ApiProxy       ][Info   ] Dial Hyper-V socket bacbefb9-6813-4280-899a-63dab3552723:23a432c2-537a-4291-bcb5-d62504644739
[13:43:54.158][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket bacbefb9-6813-4280-899a-63dab3552723:23a432c2-537a-4291-bcb5-d62504644739
[13:43:54.159][ApiProxy       ][Info   ] proxy << GET /_ping
[13:43:54.159][ApiProxy       ][Info   ] proxy >> GET /v1.26/info
[13:43:54.159][ApiProxy       ][Info   ] Dial Hyper-V socket bacbefb9-6813-4280-899a-63dab3552723:23a432c2-537a-4291-bcb5-d62504644739
[13:43:54.168][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket bacbefb9-6813-4280-899a-63dab3552723:23a432c2-537a-4291-bcb5-d62504644739
[13:43:54.175][ApiProxy       ][Info   ] proxy << GET /v1.26/info
[13:43:58.890][ApiProxy       ][Info   ] proxy >> POST /v1.26/auth
[13:43:58.891][ApiProxy       ][Info   ] Dial Hyper-V socket bacbefb9-6813-4280-899a-63dab3552723:23a432c2-537a-4291-bcb5-d62504644739
[13:43:58.891][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket bacbefb9-6813-4280-899a-63dab3552723:23a432c2-537a-4291-bcb5-d62504644739
[13:43:59.035][ApiProxy       ][Info   ] proxy << POST /v1.26/auth
[13:44:10.182][ApiProxy       ][Info   ] proxy >> GET /_ping
[13:44:10.182][ApiProxy       ][Info   ] Dial Hyper-V socket bacbefb9-6813-4280-899a-63dab3552723:23a432c2-537a-4291-bcb5-d62504644739
[13:44:10.182][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket bacbefb9-6813-4280-899a-63dab3552723:23a432c2-537a-4291-bcb5-d62504644739
[13:44:10.183][ApiProxy       ][Info   ] proxy << GET /_ping
[13:44:10.213][ApiProxy       ][Info   ] proxy >> POST /v1.26/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=myproject%2Factivmeq&ulimits=null
[13:44:10.213][ApiProxy       ][Info   ] Dial Hyper-V socket bacbefb9-6813-4280-899a-63dab3552723:23a432c2-537a-4291-bcb5-d62504644739
[13:44:10.214][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket bacbefb9-6813-4280-899a-63dab3552723:23a432c2-537a-4291-bcb5-d62504644739
[13:44:11.532][ApiProxy       ][Info   ] proxy << POST /v1.26/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=myproject%2Factivmeq&ulimits=null
```

On the registry side:
```
time="2017-02-23T21:43:57Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"Registry Realm\": invalid authorization credential" go.version=go1.6.3 http.request.host=10.x.y.z http.request.id=2ec0550f-6177-4ea4-bd2a-4d632f79eb2e http.request.method=GET http.request.remoteaddr="10.a.b.c:61385" http.request.uri="/v2/" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/4.9.8-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(windows\\))" instance.id=753ad1f1-baec-49f7-b8d9-44d03870041a version=v2.5.1
10.x.y.z - - [23/Feb/2017:21:43:57 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/4.9.8-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(windows\\))"
time="2017-02-23T21:43:57Z" level=info msg="response completed" go.version=go1.6.3 http.request.host=10.x.y.z http.request.id=32c8b20e-9679-40d6-9da8-3d458646e736 http.request.method=GET http.request.remoteaddr="10.a.b.c:61386" http.request.uri="/v2/" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/4.9.8-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(windows\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=4.602503ms http.response.status=200 http.response.written=2 instance.id=753ad1f1-baec-49f7-b8d9-44d03870041a version=v2.5.1
10.x.y.z - - [23/Feb/2017:21:43:57 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/4.9.8-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(windows\\))"
time="2017-02-23T21:44:09Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"Registry Realm\": invalid authorization credential" go.version=go1.6.3 http.request.host=10.x.y.z http.request.id=d24a9272-1357-4954-8c84-9ba5245ce74d http.request.method=GET http.request.remoteaddr="10.a.b.c:61403" http.request.uri="/v2/" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/4.9.8-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(windows\\))" instance.id=753ad1f1-baec-49f7-b8d9-44d03870041a version=v2.5.1
10.x.y.z - - [23/Feb/2017:21:44:09 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/4.9.8-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(windows\\))"
10.x.y.z - - [23/Feb/2017:21:44:10 +0000] "GET /v1/_ping HTTP/1.1" 404 19 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/4.9.8-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(windows\\))"
10.x.y.z - - [23/Feb/2017:21:44:10 +0000] "GET /v1/repositories/rmohr/activemq/images HTTP/1.1" 404 19 "" "docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/4.9.8-moby os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(windows\\))"
```

**Comment by rkpatel33** [comment] 2017-03-16 06:32
Having the same issue with a newly create private repo. `docker pull meetalbert/base:test` works fine, but the line `FROM meetalbert/base:test` from my Dockerfile fails.

**Comment by thaJeztah** [comment] 2017-03-16 09:37
@rkpatel33 can you add the output of `docker version` and `docker info`?

**Comment by rkpatel33** [comment] 2017-03-16 19:08
```
⇒  docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
⇒  docker info
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 29
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 93
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.47-boot2docker
Operating System: Boot2Docker 1.13.1 (TCL 7.2); HEAD : b7f6033 - Wed Feb  8 20:31:48 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: default
ID: DQEP:QRE7:3NUN:4XDQ:DEJP:K7C7:LHHE:F3H6:OT6Y:MFRC:2SOG:X4V7
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2017-03-16T19:08:01.071449915Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-03-20 13:17
@rkpatel33 can you try upgrading your boot2docker instance? I see it's still on docker 1.13.1, and docker 17.03.0 (which is what 1.13.2 would've been) contains some bugfixes, possibly

**Comment by rkpatel33** [comment] 2017-03-21 17:37
That seems to have fixed it, thanks! Though I would have expected boot2docker to be upgraded when I upgraded my OSX Docker app, which was up to date. Is this not the case?

**Comment by thaJeztah** [comment] 2017-03-21 18:20
No, it only updates Docker for Mac itself; if you're running docker for mac, you basically won't need boot2docker / VirtualBox anymore. `docker-machine` is included in the installation though, which _allows_ you to create a boot2docker machine in VirtualBox.

Let me go ahead and close this issue; good to hear it's resolved, and feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-21 18:20 UTC
Labels: area/builder, area/distribution, status/more-info-needed

**Comment by rkpatel33** [comment] 2017-03-22 03:28
Thanks for this. Finally led me down the path of realizing I was not using the Docker for Mac, and removed it completely. Thx!

**Comment by dieterdemeyer** [comment] 2017-05-17 14:25
I'm still having this issue on the latest Docker for Mac version (edge 17.05.0-ce).
Using a Dockerfile which pulls a base image from our private registry fails during `docker build` but doesn't fail when pulling the image beforehand.

Can we look into this again ?
Happy to provide any feedback or details if required..

**Comment by smartinov** [comment] 2017-11-01 08:09
Also having the problems, since the docker build can't pull images which are located in the private repository. The workaround would be to pull the private image before the build, but that just isn't right.

Is there any other viable work-around for the docker build to take the default docker credentials?

**Comment by tonistiigi** [comment] 2017-11-01 17:02
@smartinov Please post `docker version`, `docker info` and logs if you can.

@simonferquel Assuming this is Docker for Mac related, is there anything specific to check.

**Comment by simonferquel** [comment] 2017-11-02 08:58
@tonistiigi, I'll check it with docker for Windows (I suppose it is a bug related to build w/ credential helpers), and if I can reproduce, I'll try on mac, and debug it.

**Comment by smartinov** [comment] 2017-11-02 09:21
@tonistiigi can do!

uname -a 
```
Darwin mbp.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

docker build ...
```
docker build -t xxx.bestbytes.net/yyy/adproxy:master docker/adproxy
Step 1/5 : FROM xxx.bestbytes.zznet/yyy/service-base:latest
Get https://xxx.bestbytes.net/v2/yyy/service-base/manifests/latest: no basic auth credentials
```

docker pull
```
docker pull xxx.bestbytes.net/yyy/service-base
Using default tag: latest
latest: Pulling from yyy/service-base
Digest: sha256:bad8abe6f6d61f83c1af78ae7550733c25dfc1e00c53cf8fbe05260d25aa81c4
Status: Downloaded newer image for xxx.bestbytes.net/yyy/service-base:latest
```

After the pull, when I have the image locally, I can run the docker build.

docker version
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

docker info

```
Containers: 160
 Running: 32
 Paused: 0
 Stopped: 128
Images: 654
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 11.71GiB
Name: moby
ID: 4XUF:YNHO:3K4X:EY2M:O5SS:5DBL:NK3E:ZPWR:7T7F:OHNQ:K4R2:KN67
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 279
 Goroutines: 229
 System Time: 2017-11-02T09:04:27.991638744Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by simonferquel** [comment] 2017-11-02 10:53
@smartinov can you give me the version of docker for mac you are using ? also, what is the output of `which docker-credential-osxkeychain` and `docker-credential-osxkeychain version` ?

**Comment by smartinov** [comment] 2017-11-02 10:59
```
Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c
```

**Comment by simonferquel** [comment] 2017-11-02 15:20
ok, your docker-credential-osxkeychain seem valid.
@n4ss any quick idea about the issue (still build w/ osx credential helper) in with latest version of the helper.

**Comment by dieterdemeyer** [comment] 2018-12-03 09:37
I'm still facing this issue using the latest version of Docker for Mac.

We have set up an ECR repository with an nginx using ALB in front of it.
Pushing and pulling using the custom URL works fine, after making some changes to `amazon-ecr-credentials-helper`.

When using a private repository in the FROM of a Dockerfile, Docker for Mac just crashes.
When doing a `docker pull` before `docker build`, everything works fine.
