### ISSUE TITLE
DockerSwarmSuite.TestSwarmContainerAutoStart is flaky

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#26588] opened 2016-09-15 05:14 UTC
Noticed in https://github.com/docker/docker/pull/26584 on experimental CI.

```
01:14:43 ----------------------------------------------------------------------
01:14:43 FAIL: docker_cli_swarm_test.go:246: DockerSwarmSuite.TestSwarmContainerAutoStart
01:14:43 
01:14:43 [d20f68f1ba9c8] waiting for daemon to start
01:14:43 [d20f68f1ba9c8] daemon started
01:14:43 [d20f68f1ba9c8] exiting daemon
01:14:43 [d20f68f1ba9c8] waiting for daemon to start
01:14:43 [d20f68f1ba9c8] daemon started
01:14:43 docker_cli_swarm_test.go:265:
01:14:43     c.Assert(strings.TrimSpace(out), checker.Not(checker.Equals), "")
01:14:43 ... obtained string = ""
01:14:43 ... expected string = ""
01:14:43 
01:14:43 [d20f68f1ba9c8] exiting daemon
01:14:45 
01:14:45 ----------------------------------------------------------------------
```

**Comment by xiaods** [comment] 2016-09-19 11:45
```
----------------------------------------------------------------------
FAIL: docker_cli_swarm_test.go:246: DockerSwarmSuite.TestSwarmContainerAutoStart

[d4f8197a8140c] waiting for daemon to start
[d4f8197a8140c] daemon started
docker_cli_swarm_test.go:254:
    c.Assert(err, checker.IsNil)
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420250c40), Stderr:[]uint8(nil)} ("exit status 125")

[d4f8197a8140c] exiting daemon
OOPS: 0 passed, 1 FAILED
--- FAIL: Test (17.16s)
FAIL
---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-dev/test-integration-cli)
+++++ cat bundles/1.13.0-dev/test-integration-cli/docker.pid
++++ kill 8058
make: *** [test-integration-cli] Error 1
```
testing in macos

**Comment by LK4D4** [comment] 2016-09-22 21:58
@mrjana Some suspicious lines from logs: https://gist.github.com/tonistiigi/00de73e9a25bf7f404ec8cc563a03429#file-docker-log-L517-L565

**Comment by mrjana** [comment] 2016-09-22 23:05
It exposes a iptable rule plumbing race in overlay driver in kernels < 3.16. Will fix it libnetwork.

**Comment by tonistiigi** [comment] 2016-09-23 22:01
@mrjana failed again in https://jenkins.dockerproject.org/job/Docker-PRs-experimental/24208/console

**Comment by mrjana** [comment] 2016-09-23 22:03
@tonistiigi How do I get the daemon logs for the above run?

**Comment by tonistiigi** [comment] 2016-09-23 22:08
@mrjana Copied them out https://gist.github.com/tonistiigi/979c41d5977766ddf5a5cb9167abb49f It seems to go to a pretty bad loop there. Logs can be pulled by clicking on build number in menu and then there is a link to download artifacts.

**Comment by mrjana** [comment] 2016-09-23 22:13
Ok. But this one looks like a very different problem. After restart the agent is not able to setup a session successfully with manager.

**Comment by aaronlehmann** [comment] 2016-09-26 09:19
Can this be closed now that #26879 was merged? Not sure why it didn't get closed automatically. Perhaps GitHub doesn't let a reopened issue get closed automatically by a PR.

**Comment by xiaods** [comment] 2016-09-26 12:25
Cool

**Comment by tonistiigi** [comment] 2016-09-26 17:01
@aaronlehmann #26879 was against `v1.12.x`. I think same fix was already posted against master but didn't fix it for the ci.

@mrjana Fresh logs from this morning https://jenkins.dockerproject.org/job/Docker%20Master/label=fedora23%20&&%20devicemapper/6961/console same loop in the logs https://gist.github.com/tonistiigi/48e1be9075865ba85d50ede015c6718f after the restart.

**Comment by mrjana** [comment] 2016-09-26 17:08
@tonistiigi This flakiness is due to a different reason. So even though the previous fix, fixed the previous issue it still looks like there are some more issues. But this one doesn't reveal too much information. The agent session handling code goes wild. I am not sure if manager/dispatcher is stuck or not. @LK4D4 Do you have any clues looking at the logs?

**Comment by LK4D4** [comment] 2016-09-26 18:52
@mrjana Looks like agent somehow can't properly register and forever uses a wrong session. However, the code is quite mysterious for me. Maybe @stevvooe can help us.
My theory is that probably `UpdateTaskStatus` in `agent/agent.go` shouldn't close a session, but instead send error to `session.errs`, then backoff will work and sessionq will be set to nil. But I'm not sure.

**Comment by aluzzardi** [comment] 2016-09-27 21:31
@stevvooe Can you take a look at the logs?

**Comment by LK4D4** [comment] 2016-10-05 20:15
I believe this was fixed with recent swarmkit update.

**Comment by tonistiigi** [comment] 2016-10-06 16:53
@mrjana @LK4D4 Failed again today https://jenkins.dockerproject.org/job/Docker%20Master/label=ubuntu-1404%20&&%20zfs/7051/ `network foo not found` in logs https://gist.github.com/tonistiigi/871e626e36044fb297a5e6b5b39914d3#file-docker-log-L588

**Comment by LK4D4** [comment] 2016-10-06 19:44
:/

**Comment by aluzzardi** [comment] 2016-10-13 21:47
@LK4D4 @tonistiigi Do we know what's the root cause?

**Comment by mrjana** [comment] 2016-10-14 19:21
I think I know the root cause. It is because the Agent cleanup of old tasks is happening concurrently with the container getting restarted when daemon starts and sometimes the Agent might cleanup the network that was just created locally for the container starting phase. Working on a fix for this.

**Comment by stevvooe** [comment] 2016-10-17 20:16
@tonistiigi @LK4D4 @mrjana @aluzzardi Looks like we fixed one issue and introduced another. Any way we can more reliably propagate removal?

**Closed** 2016-11-08 17:25 UTC
Labels: area/networking, area/swarm, area/testing, priority/P2
