### ISSUE TITLE
docker system df display may give bad value for reclaimable images

### ISSUE THREAD

**Issue by iay** [docker/docker#30465] opened 2017-01-26 12:01 UTC
**Description**

I'm seeing very strange results from `docker system df` on a recently installed 1.13.0 system after deleting some images.

**Steps to reproduce the issue:**
1. `docker system df`
2.
3.

**Describe the results you received:**

```
root@srv-ut01:/# docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              18                  7                   4.056 GB            -4.685e+08 B (-11%)
Containers          7                   6                   67.35 MB            0 B (0%)
Local Volumes       8                   4                   541.4 kB            440.9 kB (81%)
```

**Describe the results you expected:**

I'd never expect to see a negative amount of reclaimable space.

**Additional information you deem important (e.g. issue happens only occasionally):**

Here's the images section of the `docker system df -v` output:

```
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE                SHARED SIZE         UNIQUE SIZE         CONTAINERS
shibboleth-idp            9.3.16              d4a1f28e325f        17 hours ago        653.7 MB            631.2 MB            22.47 MB            1
iay/java                  oracle-8            f954cf0d9914        17 hours ago        631.2 MB            631.2 MB            0 B                 0
gitlab/gitlab-ce          8.16.1-ce.0         be7119e23918        2 days ago          1.174 GB            129.5 MB            1.045 GB            1
ubuntu                    16.04               f49eec89601e        5 days ago          129.5 MB            129.5 MB            0 B                 0
bash                      latest              276fc986168f        4 weeks ago         12.33 MB            0 B                 12.33 MB            0
sonatype/nexus            2.14.2-01           00ff3a8e4732        5 weeks ago         459 MB              0 B                 459 MB              1
deliverous/certbot        latest              467bf13c81d7        8 weeks ago         377.7 MB            0 B                 377.7 MB            0
nginx                     1.10                5acd1b9bc321        2 months ago        180.7 MB            0 B                 180.7 MB            1
jekyll/jekyll             stable              707458c0f5e0        5 months ago        123.8 MB            0 B                 123.8 MB            0
iay/mdq-server-incommon   latest              6b614c932aad        10 months ago       685.7 MB            685.7 MB            13.12 kB            1
iay/mdq-server-ukf        latest              09a71e42d04c        10 months ago       685.7 MB            685.7 MB            46.62 kB            1
iay/mdq-server-static     latest              5c2367e9ca3a        10 months ago       685.7 MB            685.7 MB            46.83 kB            1
iay/mdq-server-base       latest              3914f652be96        10 months ago       685.7 MB            685.7 MB            0 B                 0
java                      openjdk-8           f298aed75633        10 months ago       642.9 MB            642.9 MB            0 B                 0
ubuntu                    14.04               3876b81b5a81        12 months ago       187.9 MB            0 B                 187.9 MB            0
busybox                   latest              0cb40641836c        12 months ago       1.114 MB            0 B                 1.114 MB            0
centos                    7                   61b442687d68        13 months ago       196.6 MB            0 B                 196.6 MB            0
centurylink/image-graph   latest              cd32805b2f74        18 months ago       132.9 MB            0 B                 132.9 MB            0
```
**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 53
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 104
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-107-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.816 GiB
Name: srv-ut01
ID: MSUE:A24V:DSKB:6RIA:NCFW:KV75:BQDP:XTYI:FLZ7:2SSA:HGKR:Q5R4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-01-26 12:16
Thanks for reporting! This is a duplicate of https://github.com/docker/docker/issues/30257, and has been fixed on master through https://github.com/docker/docker/pull/30378, which will be in a 1.13.1 patch release

I'll close this issue, because this is already fixed, but feel free to continue the conversation!

**Closed by thaJeztah** 2017-01-26 12:16 UTC
Labels: area/cli, kind/bug, version/1.13

**Comment by iay** [comment] 2017-01-26 12:27
Thanks! I did search for the issue before reporting, but I didn't think to search closed issues. Good to see it is already dealt with.
