### ISSUE TITLE
How old a Linux kernel can I run/reference inside a docker container?

### ISSUE THREAD

**Issue by slmingol** [docker/docker#11446] opened 2015-03-17 17:04 UTC
I googled a bit to try an ascertain this and came up empty. Is there a specific version of the Linux kernel that cannot run inside a container? This is purely an academic question, but was wondering.

**Comment by unclejack** [comment] 2015-03-17 17:09
@slmingol The Linux kernel doesn't run in the container. Did you mean to ask what's the oldest kernel which can run Docker and Docker containers?

**Comment by slmingol** [comment] 2015-03-17 17:15
@unclejack - yeah I realize that it's not actually a VM with a full install inside the container, forgive my ignorance, I wasn't really sure how to ask the question. Ultimately if I had an application that would only run within say a CentOS 3 environment, and I was able to install it into such an environment, could I run this application within a container? The docker install would be running on CentOS 6 or 7 with the latest docker version on it.

**Comment by unclejack** [comment] 2015-03-17 17:29
@slmingol It's OK, I just wanted to make sure I understand your question to try to help.

You could produce tarballs with your desired CentOS version (3, 4, 5) to produce Docker images to run them as containers on CentOS 6.

There's no reason why that wouldn't work - as long as the binaries running in the container (libc, ABI compatibility, sycalls, etc) are still compatible with the 2.6.32 kernel on CentOS 6. You might encounter problems trying to run CentOS 3 or 4 on CentOS 6. The compatibility problems are the only kind of problem you'd have trying to do this for other systems as well.

We know for a fact there are people out there who are running CentOS 5 containers on CentOS 6. You can even search GitHub to find older discussions from 2013 and 2014 regarding that.

Since this question has been answered and there are also some issues on GitHub, I'll close this. The discussion can continue, but there's no need to keep the issue open for that as it's not a bug.

@jperrin, could you comment on this, please?

**Closed by unclejack** 2015-03-17 17:29 UTC

**Comment by jperrin** [comment] 2015-03-17 17:36
Officially we'll only deal with centos5 or higher, as it's still supported, while the others are EOL. 

Realistically, I've blogged about running centos-4 in a container

http://jperrin.github.io/2015/01/19/i-do-terrible-things-sometimes

The same procedure for 4 will work for CentOS 3 as well(I know. I did it). I didn't do overly extensive testing, but the basics (apache, yum, etc) worked fine.
