### ISSUE TITLE
Feature Request: Allow modification of connected networks for services via `service update`

### ISSUE THREAD

**Issue by matthanley** [docker/docker#29781] opened 2016-12-29 19:29 UTC
**Description**

Looking to run docker swarm with an HAProxy load balancer as a service for SSL termination. This will be a common load balancer, shared between multiple apps. As such, when deploying a new app into a new network it would be a requirement to redeploy the load balancer service with a connection to an additional network. This is currently not possible with `service update` as documented:
https://docs.docker.com/engine/reference/commandline/service_update/

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:21:54 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:21:54 2016
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment] 2016-12-29 19:42
Thanks for suggesting; looks like this is a duplicate of https://github.com/docker/docker/issues/28247. I'll close this one to keep the discussion in a single place, but feel free to add your use case on the linked issue

**Closed by thaJeztah** 2016-12-29 19:42 UTC
Labels: area/swarm, version/1.12
