### ISSUE TITLE
Need to set source IP address for connections originating from a particular container.

### ISSUE THREAD

**Issue by xb** [docker/docker#8519] opened 2014-10-12 09:12 UTC
## Problem

Suppose a docker host has 4 public IP addresses:

1.1.1.1
1.1.1.2
1.1.1.3
1.1.1.4

It is currently possible to "publish" a particular docker container at a certain IP address and host combination using e.g. "docker run --name foo_container --publish 1.1.1.3::80 foo/foo_image".

## Expected 

If that docker container by itself initiates UDP or TCP traffic towards the internet, the source IP address of that traffic should be 1.1.1.3.

## Observed

The observed source IP address of that traffic is 1.1.1.1.

## Analysis

Docker seems to currently use the "MASQUERADE" iptables target, while it should use the "SNAT --to-source 1.1.1.3" iptables target. The IP address used as SNAT source (as well as whether or not SNAT should be used instead of MASQUERADE) could be determined as follows:

1. If there is a "--publish 0.0.0.0" command line argument (note the absence of a port), then use MASQUERADE.
2. If there is a "--publish ipAddress" command line argument (note the absence of a port) and that ipAddress is not 0.0.0.0, then use SNAT and this IP address.
3. If there is no "--publish ipAddress" command line argument, but one or more "--publish ipAddress:hostPort:containerPort" or "--publish ipAddress::containerPort" command line arguments where the ipAddress is consistent, then use SNAT and this consistent IP address.
4. If there is no "--publish ipAddress" command line argument, but one or more "--publish ipAddress:hostPort:containerPort" or "--publish ipAddress::containerPort" command line arguments where the ipAddress is not consistent, then fail with an error.
5. Else use MASQUERADE.

**Comment by jfrazelle** [comment] 2015-02-26 00:55
closing as duplicate of https://github.com/docker/docker/issues/6743

**Closed by jfrazelle** 2015-02-26 00:55 UTC
Labels: /system/networking, feature
