### ISSUE TITLE
images/layer almost all lost in docker

### ISSUE THREAD

**Issue by Johnsmith1111** [docker/docker#10342] opened 2015-01-26 05:40 UTC
Ok,When I get up after weekend and restart the physcial machine and virtual machine,oh,and docker,Things seems impossible appear:

<h3>Almost all images/layer lost !<h3>

this is my environment:

<pre>
cat /etc/issue
CentOS release 6.5 (Final)
Kernel \r on an \m
</pre>
<pre>
docker info
Containers: 4
Images: 5
Storage Driver: devicemapper
 Pool Name: docker-253:0-525029-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 6.356 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 7.102 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-431.el6.x86_64
Operating System: <unknown>
</pre>

And this is the relation among the images in my error

<pre>
centos:6-->my/java:7-->my/tomcat:7
</pre>
And,this is 
<pre>
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
my/tomcat        7                   d3812da49d93        44 hours ago        426.9 MB
my/java          7                   21a5c0fcfa33        46 hours ago        413.3 MB
</pre>
and when I want to run a container as my/tomcat,It can`t run it ,beacuse the layer below tomcat is unavailable.And there is so many **No such id** error
<pre>
2015/01/26 11:48:31 Warning: couldn't load ae0c2d0bdc100993f7093400f96e9abab6ddd9a7c56b0ceba47685df5a8fe906 from docker.cn/docker/centos/latest: No such id: ae0c2d0bdc100993f7093400f96e9abab6ddd9a7c56b0ceba47685df5a8fe906
2015/01/26 11:48:31 Warning: couldn't load 601884ab154296f60c6b00b68f9c507fdd29c8f40d9e7d96079eb2334a236495 from docker.cn/docker/mysql/latest: No such id: 601884ab154296f60c6b00b68f9c507fdd29c8f40d9e7d96079eb2334a236495
2015/01/26 11:48:31 Warning: couldn't load 601884ab154296f60c6b00b68f9c507fdd29c8f40d9e7d96079eb2334a236495 from docker.cn/docker/mysql/5: No such id: 601884ab154296f60c6b00b68f9c507fdd29c8f40d9e7d96079eb2334a236495
</pre>

But when I enter the /var/lib/docker,the data and metadata file are still there and the size is also so big

<pre>
ls -lh
total 6.0G
-rw------- 1 root root 100G Jan 26 11:41 data
-rw------- 1 root root 2.0G Jan 26 13:17 metadata
</pre>
I think it may be a **devicemapper error** as logs say
<pre>
dmsetup status | grep docker
docker-253:0-525029-pool: 0 209715200 thin-pool 716 1734/524288 96992/1638400 - rw discard_passdown
docker-253:0-525029-f1635d05cc31476c4027fe671209b67b8cb18bc172d5c7edf644a72c347995c8: 0 20971520 thin 1456256 20971519
</pre>

and in my dmesg the error is also devicemapper
<pre>
device-mapper: thin: Creation of new thinly-provisioned device with id 0 failed.
device-mapper: thin: Creation of new thinly-provisioned device with id 1 failed.
device-mapper: thin: Creation of new thinly-provisioned device with id 2 failed.
device-mapper: thin: Creation of new thinly-provisioned device with id 3 failed.
device-mapper: thin: Creation of new thinly-provisioned device with id 4 failed.
device-mapper: thin: Creation of new thinly-provisioned device with id 5 failed.
device-mapper: thin: Creation of new thinly-provisioned device with id 6 failed.
</pre>

<pre>
device-mapper: thin: Creation of new snapshot 38 of device 11 failed.
device-mapper: thin: Creation of new snapshot 39 of device 11 failed.
device-mapper: thin: Creation of new snapshot 40 of device 11 failed.
device-mapper: thin: Creation of new snapshot 41 of device 11 failed.
</pre>

So,I wanna to know **why I encounter this critical error**,Is my kernel should update or change to centos7? why in centos 6.5 it use devicemapper but not AUFS?
 
However,as I pull the centos again in my computer,it seems resloved except the data and metadata increase。

**Comment by unclejack** [comment] 2015-01-27 16:02
ping @vbatts

**Comment by vbatts** [comment] 2015-01-27 17:44
@shi154462671 what is the output of `docker version`?

Had the VM been halted abruptly?

**Comment by shi154462671** [comment] 2015-01-28 05:42
@vbatts Here is the docker version
<pre>
docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2
</pre>

my vm is ok  last weekend,physical machine sleep about 36 hours yet,and a reboot both vm and physical.
Am I should try a 3.8+ kernel as recommended for less such error?

**Comment by rhvgoyal** [comment] 2015-01-28 21:20
These device mapper errors were present in older version of docker as docker did not know what device Id is already in use and will try everything starting from 0. So after a fresh start of docker, one would see lots of error messages like that when docker tried to create a new thin device or snapshot device.

**Comment by shi154462671** [comment] 2015-01-29 06:16
@rhvgoyal ok,I got it,It seems that some error message above useless.older version of docker? not kernel? I think 1.3.2 is not so old.

**Comment by rhvgoyal** [comment] 2015-01-29 19:09
@shi154462671 

Some of these messages are generated by kernel but are initiated because of user space action and they are fixed in newer docker.

Can you try latest docker 1.4.1 and see if you still can reproduce the issue.

**Comment by shi154462671** [comment] 2015-01-30 02:49
@rhvgoyal ,Oh,I know,but where is the layers? they were almost lost,Although I  resolved it but the data and metadata increase.Now all I wanna to know is why they were lost? and is there any way to release the disk space?Since the layers is lost,data and metadata is not expected so big.

**Comment by shi154462671** [comment] 2015-03-05 05:06
<h3>TODAY I ENCOUNTER THIS PROBLEM AGAIN

After I change  port forwarding network mode to bridge mode,**IMAGES LOST AGAIN** 

I feel not so good to see the output below again.

As you can see the *docker ps* has some output:

<pre>
# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                      PORTS               NAMES
df7b90f3ebfe        me/tomcat:7      "/bin/bash"         23 hours ago        Exited (-1) 6 minutes ago                       angry_lovelace      
73404e4cbc82        me/tomcat:7      "/bin/bash"         23 hours ago        Exited (-1) 23 hours ago                        nostalgic_wright
</pre>

But there is nothing in *docker images*

<pre>
# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
</pre>

HOWEVER,**the disk space is not release in the loop file**

<pre>
[root@docker devicemapper]# du -sh *
1.3G	data
2.0M	metadata
[root@docker devicemapper]# pwd
/var/lib/docker/devicemapper/devicemapper
</pre>

**this is the result after I delete all containers**
<pre>
# docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:0-920533-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1.381 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 1.442 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-431.17.1.el6.x86_64
Operating System: <unknown>
</pre>

the images I create in it via **docker save** and **docker load**

the environment is the same as I mention before.

**Comment by rhvgoyal** [comment] 2015-06-08 18:44
@Johnsmith1111 

Can you start using lvm thin pool on top of real block devices (instead of loop devices) and see if this still happens. Using thin pool over loop devices in not recommended.

**Comment by Johnsmith1111** [comment] 2015-06-09 04:18
default is not recommended? OK.
I abort docker last year.
DO NOT ask me why.

**Comment by rhvgoyal** [comment] 2015-06-09 14:33
@vbatts 

Can you please close this issue. Reporter is no longer is using docker.

**Closed** 2015-06-09 14:35 UTC
Labels: /system/devicemapper
