### ISSUE TITLE
How to Run elasticsearch service while starting the docker image using docker run command?

### ISSUE THREAD

**Issue by Pratap6** [docker/docker#11365] opened 2015-03-13 09:22 UTC
Hi, I have created one elastisearch image with docker commands. when i run that image every time I need to start elasticsearch service  manually inside container. How can we run this service as a daemon when we run the docker image?

Basically i am doing the below process to start Elasticsearch image
$ docker run - i -t -p 9200:9200 -p 9300:9300 <elasticsearch> 
$ service elasticsearch start

Note: Inside container elasticsearch located in /etc/init.d/ . Can we pass like this to start as a service

$ docker run - i -t -p 9200:9200 -p 9300:9300 <elasticsearch> /etc/init.d/elasticsearch 

! thanks.

**Comment by RickWieman** [comment] 2015-03-13 09:32
Did you know that there already exists an [official elasticsearch repository](https://registry.hub.docker.com/u/library/elasticsearch/) on Docker Hub?

That being said, according to the [Command line documentation](https://docs.docker.com/reference/commandline/cli/#run):

> The `docker run` command can be used in combination with `docker commit` to change the command that a container runs.

This also makes sense, as `docker run` creates a new container. (Quoting the documentation again:  `docker run` is equivalent to the API `/containers/create` then `/containers/(id)/start`)

Hope this helps. Good luck!

**Comment by Pratap6** [comment] 2015-03-13 12:12
Yes @RickWieman it is there, but we are manually creating elasticsearch image using command prompt with all required installations, and also elasticsearch run as a service script is there inside init.d directory.
Here I'm running image like this
$ docker run - i -t -p 9200:9200 -p 9300:9300 

but elasticsearch service is not starting default..After that when I run the below command then only it is starting, 
$ service elasticsearch start

Please suggest me how to start elasticsearch as a service, At the time of starting the docker Image .

**Comment by RickWieman** [comment] 2015-03-13 12:19
You might want to reconsider running elasticsearch as a service. The main idea of Docker containers is that you only run one foreground task inside it. If you look at the [official Dockerfile](https://github.com/docker-library/elasticsearch/blob/03a5bda1ff2d27b000e5236082b26975a6a44c2e/1.4/Dockerfile), you see that elasticsearch also does this: they run elasticsearch as a foreground process.

Do you have a specific reason for running elasticsearch as a service?

**Comment by thaJeztah** [comment] 2015-03-15 15:17
It looks like this is not a bug in Docker, but a "support" question. The issue tracker is not really the right place for support questions. Could you close this issue and use one of the following;

- the `#docker` IRC channel on freenode
- [docker-user](https://groups.google.com/forum/#!forum/docker-user) on Google Groups
- [forums.docker.com](https://forums.docker.com)
- [StackOverflow](http://stackoverflow.com/search?q=docker)

Thanks!

**Closed** 2015-03-22 07:00 UTC
Labels: kind/question, status/closed/invalid
