### ISSUE TITLE
--fixed-cidr does not work with pre-existing bridge interface

### ISSUE THREAD

**Issue by candlerb** [docker/docker#11336] opened 2015-03-11 21:39 UTC
This is on ubuntu 14.04 with lxc-docker-1.5.0 from the docker repo. I want to use an existing bridge interface "br-lan"

~~~
root@kit1:~# ifconfig br-lan
br-lan    Link encap:Ethernet  HWaddr 3a:c3:df:70:eb:e6
          inet addr:10.10.0.241  Bcast:10.10.0.255  Mask:255.255.255.0
          inet6 addr: fe80::38c3:dfff:fe70:ebe6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:35 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:340 (340.0 B)  TX bytes:2903 (2.9 KB)
~~~

However when I try to start docker with `--fixed-cidr`:

~~~
root@kit1:~# docker -d -b br-lan --dns 10.10.0.241 -g /data/docker --fixed-cidr 10.10.0.0/25 --ip-masq=false --iptables=false
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] +job init_networkdriver()
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
network does not contain specified subnet
INFO[0000] -job init_networkdriver() = ERR (1)
FATA[0000] network does not contain specified subnet
~~~

My reading of <https://docs.docker.com/articles/networking/#customizing-docker0> is that the `--fixed-cidr` parameter is supposed to give the IP allocator a subnet which is contained within the bridge subnet - and clearly 10.10.0.0/25 is contained within 10.10.0.0/24.

Could it be because the 10.10.0.241 address is not within 10.10.0.0/25? No, because it also doesn't work if I give `--fixed-cidr` covering the whole range:

~~~
oot@kit1:~# docker -d -b br-lan --dns 10.10.0.241 -g /data/docker --fixed-cidr 10.10.0.0/24 --ip-masq=false --iptables=false
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] +job init_networkdriver()
network does not contain specified subnet
INFO[0000] -job init_networkdriver() = ERR (1)
FATA[0000] network does not contain specified subnet
~~~

So my only option to get docker running was to omit `--fixed-cidr` altogether:

~~~
root@kit1:~# docker -d -b br-lan --dns 10.10.0.241 -g /data/docker --ip-masq=false --iptables=falseINFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] +job init_networkdriver()
INFO[0000] -job init_networkdriver() = OK (0)
INFO[0000] WARNING: Your kernel does not support cgroup swap limit.
INFO[0000] Loading containers: start.

INFO[0000] Loading containers: done.
INFO[0000] docker daemon: 1.5.0 a8a31ef; execdriver: native-0.2; graphdriver: aufs
INFO[0000] +job acceptconnections()
INFO[0000] -job acceptconnections() = OK (0)
~~~

However this means the allocator is free to allocate addresses anywhere from the 10.10.0.0/24 subnet and stomp over other devices I have in that range.

Supplementary issue 1: it would be more flexible if the allocator could be given start and end addresses for its pool, rather than a subnet. Then I could tell it to use 10.10.0.100 to 10.10.0.199, say.

Supplementary issue 2: I would like to tell the allocator which address to use when I create a container

**Comment by aboch** [comment] 2015-08-04 05:37
@candlerb This is a genuine issue, but I cannot reproduce it with 1.6.2, 1.7.0, 1.7.1 or 1.8.0-rc1. 
Most likely it got fixed in 1.6.x 

My custom bridge:
`$ ifconfig br-lan
br-lan    Link encap:Ethernet  HWaddr 7e:e5:be:56:68:bc  
          inet addr:10.10.0.241  Bcast:10.10.0.255  Mask:255.255.255.0
          inet6 addr: fe80::7ce5:beff:fe56:68bc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:56 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:8557 (8.5 KB)
`

Output with 1.6.2:
`$ sudo ./docker-1.6.2 -d -b br-lan --dns 10.10.0.241 --fixed-cidr 10.10.0.0/25  --ip-masq=false --iptables=false
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
WARN[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors 
WARN[0000] Graphdriver devicemapper selected. Your graphdriver directory /var/lib/docker already contains data managed by other graphdrivers: overlay,aufs 
INFO[0000] +job init_networkdriver()                    
INFO[0000] -job init_networkdriver() = OK (0)           
WARN[0000] Your kernel does not support cgroup swap limit. 
INFO[0000] Loading containers: start.                   
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
INFO[0000] Loading containers: done.                    
INFO[0000] docker daemon: 1.6.2 7c8fca2; execdriver: native-0.2; graphdriver: devicemapper 
INFO[0000] +job acceptconnections()                     
INFO[0000] -job acceptconnections() = OK (0)            
INFO[0000] Daemon has completed initialization          
`

Output with 1.7.1:
`$ sudo ./docker-1.7.1 -d -b br-lan --dns 10.10.0.241 --fixed-cidr 10.10.0.0/25 --ip-masq=false --iptables=false -s overlay
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
WARN[0000] Your kernel does not support swap memory limit. 
INFO[0000] Loading containers: start.                   
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
INFO[0000] Loading containers: done.                    
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=786b29d execdriver=native-0.2 graphdriver=overlay version=1.7.1
`

Can you please verify so that we can close this issue.
Thanks.

**Comment by candlerb** [comment] 2015-08-04 09:28
I can confirm that docker 1.7.1 *does* start correctly:

~~~
root@brian:~# docker -d -b br-lan --dns 10.10.0.241 -g /data/docker --fixed-cidr 10.10.0.192/28 --ip-masq=false --iptables=false
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] [graphdriver] using prior storage driver "aufs"
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1
WARN[0000] Your kernel does not support swap memory limit.
INFO[0000] Loading containers: start.

INFO[0000] Loading containers: done.
INFO[0000] Daemon has completed initialization
INFO[0000] Docker daemon                                 commit=786b29d execdriver=native-0.2 graphdriver=aufs version=1.7.1
~~~

And it does allocate address out of the given range:

~~~
root@brian:~# docker run -d --name host1 --hostname host1 student
...
root@brian:~# docker exec host1 ifconfig -a
eth0      Link encap:Ethernet  HWaddr 02:42:0a:0a:00:c1
          inet addr:10.10.0.193  Bcast:0.0.0.0  Mask:255.255.255.0...
...
~~~

So this ticket can be closed. I will open new feature request tickets for the supplementary issues.

**Comment by thaJeztah** [comment] 2015-08-04 18:07
Thanks for reporting back @candlerb! closing

**Closed by thaJeztah** 2015-08-04 18:07 UTC
Labels: status/more-info-needed, system/networking

**Comment by mgmax** [comment] 2016-02-20 17:49
workaround for those on legacy systems: `.--fixed-cidr=$CIDR --bip=$CIDR` to also specify the bridge interface IP address
