### ISSUE TITLE
Docker: HTTP code 403 while uploading metadata: “invalid character '<' looking for beginning of value”

### ISSUE THREAD

**Issue by andorp** [docker/docker#16746] opened 2015-10-03 20:53 UTC
I have the same issue as in:
http://stackoverflow.com/questions/32900830/docker-http-code-403-while-uploading-metadata-invalid-character-looking-f but deleting the repository does not help.

    d3a1f33e8a5a: Pushing
    HTTP code 403 while uploading metadata: "invalid character '<' looking for beginning of value"

    docker --version
    Docker version 1.8.2, build 0a8c2e3

    docker-machine --version
    docker-machine version 0.4.1 (e2c88d6)

    Kitematic: 0.8.5
    VirtualBox: 5.0.4

    MacOSX: 10.9.5

Please advise.

**Comment by andorp** [comment] 2015-10-03 20:54
docker info
Containers: 1
Images: 9
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: tmpfs
 Dirs: 11
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: EBYD:UEEX:VEHE:DHDJ:7VUV:OHTS:XWYR:GWTT:CMQ4:47CX:5HK6:BPPD
Debug mode (server): true
File Descriptors: 13
Goroutines: 26
System Time: 2015-10-03T20:54:04.495813577Z
EventsListeners: 1
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: andorp
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

**Comment by thaJeztah** [comment] 2015-10-04 00:36
Are you trying to push to the Docker Hub, or a private registry?

**Comment by thaJeztah** [comment] 2015-10-04 00:40
Also, could you add the output of `docker version`? This looks similar to https://github.com/docker/docker/issues/15612, where the docker daemon was not update in the virtual machine

**Comment by andorp** [comment] 2015-10-04 13:33
docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

**Comment by andorp** [comment] 2015-10-04 13:34
I would like to push to the Docker Hub

**Comment by andorp** [comment] 2015-10-04 13:35
docker-machine upgrade default
    Stopping machine to do the upgrade...
    Upgrading machine default...
    Get https://api.github.com/repos/boot2docker/boot2docker/releases: dial tcp: i/o timeout

**Comment by Josh-a-e** [comment] 2015-10-04 15:50
@andorp I get the same up until the failed upgrade - worked fine for me. How did it work out for you: did you find a solution?

**Comment by andorp** [comment] 2015-10-05 10:33
Coming to office today and trying to upgrade docker machine worked. It is only a coincidence, or change of network, as we use docker in corporate env. Trying the same from home again.

**Comment by andorp** [comment] 2015-10-05 10:33
From my part this issue can be closed.

**Comment by ain** [comment] 2015-10-05 10:42
Not on my part. Still getting the error.

**Comment by thaJeztah** [comment] 2015-10-05 10:51
@ain are you trying to push to Docker Hub or a private repository? I see you also opened another issue; https://github.com/docker/machine/issues/1937 which sounds like the VM may be having networking issues, which could be related to https://github.com/boot2docker/boot2docker/issues/776.

**Comment by stevengonsalvez** [comment] 2015-10-05 10:52
Having the same problem  and when trying to upgrade

MB536:~ b8886963$ docker-machine upgrade default
Stopping machine to do the upgrade...
Upgrading machine default...
Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.8.2/boot2docker.iso to /Users/b8886963/.docker/machine/cache/boot2docker.iso...
Get https://github.com/boot2docker/boot2docker/releases/download/v1.8.2/boot2docker.iso: dial tcp: i/o timeout

**Comment by ain** [comment] 2015-10-05 10:59
I now upgraded manually by replacing the ISO at `~/.docker/machine/<name>/boot2docker.iso` with `1.8.2` so client and server are having exactly the same version, but the problem persists. I can not push. I even killed the private image on Docker Hub, still the same. Terrible.

Unfortunately it has grown into a __blocker-grade issue__ that is currently killing our whole dev environment.

**Comment by Josh-a-e** [comment] 2015-10-05 11:29
I've had this solved by coming into work too actually, I'm not sure if something has changed with the registry (I find this unlikely?) or it's the result of using a different internet connection (although I find it equally unlikely that this would solve the issue). I plan on pushing again just before I leave and then again when I get home to see if it is related to my connection.

**Comment by ain** [comment] 2015-10-05 12:03
Changing connection did not help. Restart did not help either. I left last week having with this issue and I'm experiencing it again today, on every push.

**Comment by thaJeztah** [comment] 2015-10-05 12:09
does your daemon log give any useful information? if possible, add the `-D` (debug) option to your daemon options

**Comment by ain** [comment] 2015-10-05 12:19
@thaJeztah where exactly should I define the debug option while running on OS X?

**Comment by ain** [comment] 2015-10-05 12:25
What I can currently see in the log is 
```
time="2015-10-05T12:22:10.040068077Z" level=debug msg="[registry] Calling PUT https://cdn-registry-1.docker.io/v1/images/511136ea3c5a64f...2c158/json" 
time="2015-10-05T12:22:20.636703927Z" level=debug msg="Not continuing with error: HTTP code 403 while uploading metadata: \"invalid character '<' looking for beginning of value\"" 
```
So could be a CDN issue?

**Comment by thaJeztah** [comment] 2015-10-05 12:31
@ain it's possible, you could try opening an issue via support@docker.com, which handles Docker Hub. They may have more insight in your specific situation.

**Comment by ain** [comment] 2015-10-05 12:48
Thanks, just did it. 

For the record: logging out and logging in again also had no effect.

Since others reported it starting working after a while, I have a reason to believe it's a CDN re-evaluation issue.

**Comment by thaJeztah** [comment] 2015-10-05 13:02
Thanks @ain. please keep us posted if that was the case. I added the "more-info-needed" label; we check those labels once in a while for issues that can possibly be closed

**Comment by ain** [comment] 2015-10-05 13:17
Will do, surely. Docker Toolbox reinstall didn't help either, docker/machine#1937 peristed.

**Comment by atd** [comment] 2015-10-05 17:56
Same problem here on Debian GNU/Linux. Upgrading to 1.8.2 and restarting did not help. Opening an issue via support@docker.com

**Comment by ain** [comment] 2015-10-05 18:25
Also reproduced on `1.8.1` on another OS X El Capitan Mac:
```
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by xrow** [comment] 2015-10-07 08:25
Hi,

I have the same issue. 

´´´
The push refers to a repository [registry.hub.docker.com/xrow/centos7] (len: 1)
Sending image list
Pushing repository registry.hub.docker.com/xrow/centos7 (1 tags)
8ad16af9bad9: Pushing 
HTTP code 403 while uploading metadata: "invalid character '<' looking for beginning of value"
[root@vmbuilder packer]# docker version
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-115.el7.x86_64
Go version (client): go1.4.2
Git commit (client): 446ad9b/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-115.el7.x86_64
Go version (server): go1.4.2
Git commit (server): 446ad9b/1.7.1
OS/Arch (server): linux/amd64
[root@vmbuilder packer]# uname -a
Linux vmbuilder.xrow.lan 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@vmbuilder packer]# cat /etc/re
redhat-release    request-key.conf  request-key.d/    resolv.conf       
[root@vmbuilder packer]# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 
´´´

**Comment by thaJeztah** [comment] 2015-10-07 11:27
ping @jlhawn @dmp42 any suggestions here? is this an authentication issue, fallback to v1?

**Comment by ain** [comment] 2015-10-07 12:35
It is auth issue AFAICT. 

       $ curl https://registry-1.docker.io/v2/
       {"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":null}]}

**Comment by atd** [comment] 2015-10-07 13:44
I don't know if it helps, but we first experienced the problem at October 2th, 1:30 PM CEST, before https://twitter.com/dockerstatus/status/649955838912675840

**Comment by ain** [comment] 2015-10-07 14:08
This coincides with the current ticket and has been up there for 5 days already, unfortunately.

**Comment by dmp42** [comment] 2015-10-07 17:18
@ain getting a 401 status code on `/v2` is expected.

Others: if you are having issues pulling from the hub, please open a support ticket  on https://support.docker.com

**Comment by ain** [comment] 2015-10-08 11:12
Resorted to using save/load as workaround. Worked seamlessly.

**Comment by xrow** [comment] 2015-10-08 11:16
@ain Can you explain your workaround with an conrete example?

**Comment by ain** [comment] 2015-10-08 11:33
On the machine where the image is on:

        docker save 'some/image:tag' > /a/nice/location/on/network/drive/some_image_tag.tar

and on a machine the image is desired on:

        docker load < /a/nice/location/on/network/drive/some_image_tag.tar

**Comment by xrow** [comment] 2015-10-08 15:08
I think the workaround from @ain will not work for me since I try to push to docker registry. I also did try the proposal from @bensinover, but the also didn`t work for me either.

**Comment by ain** [comment] 2015-10-08 15:10
Yup, Benjamin's idea with login isn't working. Login works fine, the push fails.

For me it was about distributing the image to local team, yes. Sharing a tarball over network would indeed be even more clumsy.

**Comment by atd** [comment] 2015-10-08 16:31
I finally managed to push to the registry from another server in a different country

**Comment by dmp42** [comment] 2015-10-08 17:30
All: a 403 status code can be encountered for a number of different reasons.

One of them is country based access restriction (Docker being a US based company, it has to comply with us export control regulations).

If you are blocked, please open an issue to https://support.docker.com providing your IP and where your system is located.

Other reasons for a 403:

 * running docker 1.8.0
 * networking issues making a push fail in the middle

**Comment by ain** [comment] 2015-10-08 18:39
@dmp42 you must be kidding me. Export Control Regulations? I pushed my images originally from Germany, to an account registered in US, so I believe I could be subjected to such restrictions. Which would be completely crazy as I have had no such legislation change alert from you and we got a hiccup of several days now.

The whole point of Docker for many teams, incl. ours, is to support distributed teams, seamlessly, across the globe. If we will get stuck with national restrictions, we'd have no chance but to leave the Docker Hub for good.

**Comment by dmp42** [comment] 2015-10-08 20:04
@ain Like I said:

 * getting a 403 is triggered by different conditions - geoip restriction is just one of them - might or might not be your problem here
 * either way, this here the bugtracker for the docker engine - issues with the hub have a dedicated support channel here: https://support.docker.com so please reach out to them so they figure out what's wrong for you and they can fix it
 * I'm not a lawyer, I'm a dev, and I don't feel legit in commenting on whether export regulations are sane or not (I believe these terms are outlined here:  https://www.docker.com/docker-terms-service section 19.8)

I really am sorry for the inconvenience but again suggest you reach out to support if you want to bring concerns forward.

Hope that helps.

**Comment by bensinober** [comment] 2015-10-08 20:17
actually, as @ain pointed out, the problem is probably authentication issues. docker login to https://index.docker.io/v1/ works but a push is followed by a `Error in LookupRemoteImage: HTTP code 401` which means failed auth. Docker login directly to https://registry.hub.docker.com/v1/ however works.

If we suffer from the same problem, it's more likely an API issue

**Comment by dmp42** [comment] 2015-10-08 20:27
@bensinober the OP and other people on this ticket reported a 403, not a 401. Furthemore, @ian pointed out that a curl on /v2 ends-up with a 401 - this is expected and is part of the API.

I know this is frustrating, but if we want resolution on this, we need to address separate issues one by one, and have a clear view of what the symptoms are (and 401 on /v2 is not a symptom).

Once again: hub issues are better resolved through the dedicated support (https://support.docker.com)

If there is an API issue, I would be happy to look into it, but I need a clear scenario to reproduce, specific docker version, and docker daemon logs (ran in debug).

**Comment by ain** [comment] 2015-10-08 20:50
@dmp42 I appreciate your feedback a lot, thanks. 

I have now tested geoip restriction and I have every reason to believe that this is not the cause. I wasn't able to push with US VPN either. I'd speculate some sort of auth split that appeared with the v2 API.

**Comment by dmp42** [comment] 2015-10-08 20:58
@ain then let's dig into it. Can you provide me with your complete docker *daemon* (not cli) logs, ran in debug mode (`-D`), when the failure happens?
That would help a lot.

**Comment by ain** [comment] 2015-10-09 08:57
@dmp42 [here you have a log](https://dl.dropboxusercontent.com/u/2994788/docker.log) for following process:

1. `docker logout` (succeeds)
2. `docker login` (succeeds)
3. `docker push <image>` (fails)

**Comment by xrow** [comment] 2015-10-09 09:23
I can confirm that I have the same problem as @ain. I can add some details maybe. As a thesis: the problem might  be a routing problem caused by 54.240.229.74. For me 54.240.229.74 has high package loss. @ain can you confirm that you have the same router with package loss in your route to docker.io? I have written an email to ipmanagement@amazon.com.

```bash
[root@192-168-0-107 ~]# mtr registry-1.docker.io
                                                                                                                     My traceroute  [v0.85]
192-168-0-107 (0.0.0.0)                                                                                                                                                                                                                Fri Oct  9 11:11:51 2015
Resolver: Received error response 2. (server failure)0.0.2.2ields   quit
                                                                                                                                                                                                                       Packets               Pings
 Host                                                                                                                                                                                                                Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. 10.0.2.2                                                                                                                                                                                                          0.0%   200    0.4   0.9   0.3   7.4   0.5
 2. ???
 3. 217.0.117.225                                                                                                                                                                                                     0.0%   200   24.0  26.7  22.3  67.2   7.9
 4. 217.237.155.58                                                                                                                                                                                                    0.0%   200   25.5  29.0  23.8  67.9   7.3
 5. 217.239.37.126                                                                                                                                                                                                    0.5%   200   40.3  43.7  37.3  81.6   6.4
 6. 87.128.238.198                                                                                                                                                                                                    0.0%   200   38.2  40.3  37.0  83.4   6.7
 7. ae-8.r23.londen03.uk.bb.gin.ntt.net                                                                                                                                                                               0.5%   200   43.3  49.1  41.3 113.2  11.1
 8. ae-0.r22.londen03.uk.bb.gin.ntt.net                                                                                                                                                                               0.0%   200   43.2  47.3  41.2  92.3   9.1
 9. ae-4.r22.nycmny01.us.bb.gin.ntt.net                                                                                                                                                                               0.0%   200  117.3 122.9 115.2 179.5  10.2
10. ae-2.r05.nycmny01.us.bb.gin.ntt.net                                                                                                                                                                               0.0%   200  118.6 120.6 115.4 165.0   7.3
11. ae-6.amazon.nycmny01.us.bb.gin.ntt.net                                                                                                                                                                            0.0%   200  120.6 115.3 110.2 156.7   7.2
12. 54.240.229.74                                                                                                                                                                                                    31.7%   200  118.7 121.5 116.7 171.1   7.2
13. ???
14. ???
15. ???
16. ???
17. ???
18. 205.251.245.230                                                                                                                                                                                                   0.0%   199  123.2 124.5 118.2 170.2   6.9
    205.251.245.65
19. ???
```

**Comment by ain** [comment] 2015-10-09 09:41
Nope, no packet loss for me. 

![screen shot 2015-10-09 at 11 40 33](https://cloud.githubusercontent.com/assets/370576/10390713/a5595bb2-6e7a-11e5-80a6-8695d50477fe.png)

**Comment by rafriki** [comment] 2015-10-09 15:42
I'm having this error whilst following the tutorial also:

```
$ docker push rafriki/docker-whale
The push refers to a repository [docker.io/rafriki/docker-whale] (len: 1)
Sending image list
Pushing repository docker.io/rafriki/docker-whale (1 tags)
e9e06b06e14c: Pushing
HTTP code 403 while uploading metadata: "invalid character '<' looking for beginning of value"
```

**Comment by dmp42** [comment] 2015-10-09 17:09
@ain `time="2015-10-09T08:49:51.577452478Z" level=debug msg="Error getting v2 registry: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection"` is the culprit here.

Your docker engine failed to establish a connection with the Hub.

My suggestion:
 * `curl -iv https://registry-1.docker.io/v2` <- run that a dozen times, from the same host where your docker daemon lives
 * `mtr registry-1.docker.io` <- on the same host where your docker daemon lives, run it for 5/10 minutes, then screenshot
 * send the above information to https://support.docker.com - since this is definitely a hub connectivity issue, and not a docker or registry issue

**Comment by dmp42** [comment] 2015-10-09 17:10
@xrow same thing, please reach out to the hub support and have them look into it with the requested info.

**Comment by dmp42** [comment] 2015-10-09 17:11
@rafriki where are you located?

Also, please provide at least your docker daemon logs. If you are in the same case as other people here (failure to establish a connection with the hub), then pleasereach out to support.

**Comment by gondor** [comment] 2015-10-12 19:50
@dmp42 I've been seeing this non-stop from our Jenkins slaves the past 2 weeks.  They are running Docker 1.8.2 and are pushing from AWS EC2 on us-west region.  We've made no changes to our slaves and it just randomly started 2 weeks ago.  I have to remove all images and inherited images from local cache before it can successfully go through.   It's starting to impact us now.

**Comment by dmp42** [comment] 2015-10-12 20:17
@gondor and everybody else:

docker daemon logs (in debug mode preferably) are *essential* - without them, there is no way to guess what the issue is in your case.

Thanks.

**Comment by ain** [comment] 2015-10-13 07:35
I'd guess it's all the same as me currently, for people involved here. Support desk is managing it, I just delivered another set of logs yesterday, unfortunately without improvement, but let's see.

**Comment by ain** [comment] 2015-10-13 08:11
Just tried `1.8.3`, issue is still there.

**Comment by atd** [comment] 2015-10-13 08:13
@gondor do you mean that cleaning the cache solves the issue?

**Comment by mghazizadeh** [comment] 2015-10-13 08:48
@gondor @atd et al, I lead the engineering team for DockerHub registry and infrastructure services and we're looking into this intermittent issue. please stay tuned and thanks for sending us the logs. Apologies for the issues your'e experiencing with push.

**Comment by gondor** [comment] 2015-10-13 15:27
@atd Sorry, wrong term cache.  We are building the images on the jenkins slave and then pushing.  If I remove all images from the slaves local storage then re-push it works.  It also works if I remove the HUB repo and re-create a new one.  

@mghazizadeh I have fresh logs from the failure from an EC2 instance in US-WEST-2.  It appears to be happening continuous with the "nginx:latest" official.  Where should I send the logs?

**Comment by mghazizadeh** [comment] 2015-10-13 16:58
@gondor thank you. We have engineers looking into this now. We believe the issue to be somewhere in the networking layer but needs further investigation. We will definitely look at your logs. I am pining support to get them.

**Comment by bensinober** [comment] 2015-10-14 23:12
@ain: not sure if it is related, but we solved our issue with the 403 invalid metadata , which was triggered by a 401 Auth issue as seen in the logs you provided (msg="Error in LookupRemoteImage: HTTP code 401").

The culprit was a running registry container on one of our servers used for mirroring docker registry hub. The docker image used was https://github.com/docker/docker-registry which is now deprecated, as it is part of docker core. Stopping it made it all work again, so pushing to dockerhub through this mirror container with v1 stopped working somewhere along API v19

**Comment by ain** [comment] 2015-10-14 23:30
Thanks @bensinober. It comes a bit too late as we've installed our own registry that works seamlessly with the same images.

**Comment by ain** [comment] 2015-10-15 09:01
Docker support alerted me today of a fix that had landed and it works! So guys, please test and I'd propose closing this ticket thereafter :)

**Comment by xrow** [comment] 2015-10-15 10:04
Confirmed. Works now.

**Comment by gondor** [comment] 2015-10-15 15:24
Confirmed: appears to be working now.   Thank you

**Comment by thaJeztah** [comment] 2015-10-15 18:19
Thanks all! Happy to see this is resolved; I'll go ahead and close this issue, but feel free to comment here after I've closed.

**Closed by thaJeztah** 2015-10-15 18:19 UTC
Labels: group/distribution

**Comment by timgriffiths** [comment] 2015-10-20 02:38
So i see this same issue using a private registry, i am using the docker registry image 2.1.1 with a 1.8.3 client? and i can get it to happen with every image i push for some reason??

I am getting the impression the problem is registry problem? What do i need to do to resolve this?
