### ISSUE TITLE
docker commit loses entrypoint of original image

### ISSUE THREAD

**Issue by TMiguelT** [docker/docker#26479] opened 2016-09-12 06:47 UTC
Basically, if you commit a running docker container to an image, and then run that image, it will have lost the entrypoint information the original image had.

This can be easily tested using the following commands (note these aren't one shell script, many will have to be run one at a time):

```bash
# Build a basic image that prints 'Normal Entrypoint'
echo $'FROM ubuntu\nENTRYPOINT echo Normal Entrypoint' | docker build -t commit-test -

# Run the image to prove it uses the entrypoint
docker run commit-test
> Normal Entrypoint

# Start container with TTY
docker run --entrypoint=bash -it commit-test
>root@<docker container id>:/# 

# Change terminal by starting another SSH session or with screen/tmux

# Commit the running image
docker commit <docker container id>

# Run the committed container
docker run <committed image id>

# Nothing is echoed
```

Am I going about this wrong, or is this a genuine bug?

**Comment by TMiguelT** [comment] 2016-09-12 07:02
This might be a duplicate of #4362?

**Comment by mountkin** [comment] 2016-09-12 07:50
It's the expected behavior. The entrypoint was not "lost", but reset to "bash" after the commit because you created the container with `--entrypoint=bash`.
You can check that by `docker inspect <committed image id>|grep -i entrypoint`

**Comment by cpuguy83** [comment] 2016-09-12 14:07
@mountkin Is correct.
You can change this by using `--change ENTRYPOINT foo` on `docker commit`

**Closed by cpuguy83** 2016-09-12 14:07 UTC
