### ISSUE TITLE
Network traffic control of docker

### ISSUE THREAD

**Issue by cxxly** [docker/docker#16477] opened 2015-09-22 09:32 UTC
I have come across many situation in which  limiting the bandwidth of docker is necessary, but I can't find a effective  tools  to  control docker network traffic. 
Therefore, I have implemented a scripts in my project to control docker network traffic by using Linux TC. I want merge it to docker so that we can implement docker traffic control  conveniently, just like use cgroup to  limit the resource utilization of CPU,memory and disk in start a container with flag --cpuset-cpus, --memory, etc.
I want to know if docker maintainers want to add this function or is this function necessary? Why or not?

**Comment by xiaods** [comment] 2015-09-23 03:07
feel a tc plugin can do that.

**Comment by cxxly** [comment] 2015-10-15 14:25
cgroup net_cls is a better option, I have not  find code about net_cls on libcontainer

**Comment by thaJeztah** [comment] 2015-10-18 06:59
Closing, because this looks like a duplicate of https://github.com/docker/docker/issues/4763

Also, some prior discussions on this subject; https://github.com/docker/docker/issues/9607, and  https://github.com/docker/docker/issues/37

**Closed by thaJeztah** 2015-10-18 06:59 UTC
Labels: group/networking
