### ISSUE TITLE
dockerd -g is ignored

### ISSUE THREAD

**Issue by SiKing** [docker/docker#25554] opened 2016-08-09 22:05 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56 GiB
Name: lambert
ID: KG53:LZK4:LZFD:G6JG:J2IJ:GTEO:3G33:R5NT:5ST5:FIDP:WK26:UJMP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical, running Linux Mint 18 == Ubuntu 16.04 LTS

**Steps to reproduce the issue:**
1. Following instructions at https://github.com/docker/docker/issues/3127
2. Modify /etc/defaults/docker, such that DOCKER_OPTS="-g /home/docker/".
2.1 I also tried all the following: DOCKER_OPTS="-g=/home/docker/", DOCKER_OPTS="--graph /home/docker/", DOCKER_OPTS="--graph=/home/docker/".
3. Restart docker using `sudo service docker restart`.
3.1 I also tried first `sudo service docker stop`, make the change, then `sudo service docker start`.
4. See which runtime is Docker using.
5. I also tried to make the change directly in /etc/init.d/docker (line 31), with the same results.

**Describe the results you received:**
Docker always uses /var/lib/docker.

**Describe the results you expected:**
I would like Docker to use whatever I specify in my DOCKER_OPTS.

**Additional information you deem important (e.g. issue happens only occasionally):**
Using the procedure from https://github.com/docker/docker/issues/3127 to move the location, and then create a soft-link works fine. However, some users reported various issues with this solution - in that same issue description.

**Comment by thaJeztah** [comment] 2016-08-09 22:50
Ubuntu 16.04 uses systemd, and the `/etc/default/docker` file is only used for systems running upstart and sysvinit (see the comment in that file: https://github.com/docker/docker/blob/v1.12.0/contrib/init/sysvinit-debian/docker.default#L3-L8)

You can configure the daemon by using a `daemon.json` configuration file, which works independent of the process manager in use, and also allows you to live-reload certain settings.

See https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file for details

Alternatively, if you want to configure through systemd, you can create a drop-in (override file), as is explained in https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options

I'll close this issue, because this is not a bug, but hope the information above helps. Feel free to comment after I closed

**Closed by thaJeztah** 2016-08-09 22:50 UTC
Labels: version/1.12

**Comment by SiKing** [comment] 2016-08-10 02:15
Proof positive: systemd is a pain in the {end}. :p 
The drop-in file seems to work. Thanx!
