### ISSUE TITLE
Error running command in existing container with exec

### ISSUE THREAD

**Issue by ruffsl** [docker/docker#15214] opened 2015-07-31 22:45 UTC
Provide additional environment details (AWS, VirtualBox, physical, etc.):
> Desktop installation with Ubuntu 14.04 LTS on physical workstation

List the steps to reproduce the issue:
> When attempting to debub networking issues in https://github.com/ros2/ros2/issues/79 , I tried to `docker exec` into `talker` container to inspect the network interface. However attaching an additional bash session into the container is not working for this scenario:

    $ docker network create foo
    $ docker run --rm \
        --publish-service=talker.foo \
        --name talker \
        osrf/ros2 \
        /root/ros2_ws//install/bin/talker
    $ docker exec -it talker bash

Describe the results you received:  
> The daemon log is listed here:
http://pastebin.com/NGRXLUy2
Relevant output for `docker exec` command starts at line 120.

`docker version`:
```
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   a2ea8f2
 Built:        Sat Jul 25 22:03:05 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   a2ea8f2
 Built:        Sat Jul 25 22:03:05 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```
`docker info`:
```
Containers: 2
Images: 120
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 135
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 15.63 GiB
Name: eve
ID: YDOY:4L4P:RWPC:FQOA:O7IS:LOZR:26TA:6P72:U2WT:Y5QU:5PDN:LUPO
Debug mode (server): true
File Descriptors: 10
Goroutines: 15
System Time: 2015-07-31T15:10:53.824492791-07:00
EventsListeners: 0
Init SHA1: b76fde836d83edef4fee74bbf1d0946c811150c4
Init Path: /usr/lib/docker/dockerinit
Docker Root Dir: /var/lib/docker
Username: ruffsl
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
```
`uname -a`:
```
Linux eve 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by FrenchBen** [comment] 2015-07-31 23:22
Without doing the network swap can you `exec` into the containers?

**Comment by ruffsl** [comment] 2015-07-31 23:30
No, just executing the first three commands I referenced:
```
$ docker network create foo
$ docker run --rm \
    --publish-service=talker.foo \
    --name talker \
    osrf/ros2 \
    /root/ros2_ws//install/bin/talker
$ docker exec -it talker bash
``` 
is enough to produce this symptom, even before I begin to detach anything.

**Comment by cpuguy83** [comment] 2015-08-01 13:06
Is the talker container exiting?

**Comment by ruffsl** [comment] 2015-08-01 23:10
Nope, the example process continues to "chatter" away until you explicitly stop it with a SIGINT or `^C` if you started the container interactively with `-it` flag. Though, I've never seen the example prematurely exit either way I start the container.

**Comment by cpuguy83** [comment] 2015-08-03 14:07
Running with master I cannot reproduce. Can you try with a master build?
Is the network you are creating a bridge network or something else?

**Comment by ruffsl** [comment] 2015-08-03 17:11
@cpuguy83 , the experimental build cited above was in fact creating a network of type `bridge`.

```
$ docker network ls
NETWORK ID          NAME                TYPE
20008b2f57d6        foo                 bridge              
3ac33f0f66db        none                null                
a0facfd11b48        host                host                
b227dc024748        bridge              bridge 
```

I just tried the available [master binaries](https://master.dockerproject.org/), but it does not have the network command. Is there something I need to do to enable the experimental features. Prior, I had just installed experimental versions of docker via the [experimental READ.ME](https://github.com/docker/docker/blob/master/experimental/README.md). My understands was that is to be a nightly build. Version info on used master build:

```
$ docker version 
Client:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   637cf3a
 Built:        Mon Aug  3 16:49:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   637cf3a
 Built:        Mon Aug  3 16:49:08 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by cpuguy83** [comment] 2015-08-03 17:14
Yes, it should be nightly from the experimental.docker.com repos.

**Comment by ruffsl** [comment] 2015-08-03 17:28
I just reinstalled docker from the experimental source and reproduced the same behavior, but it looks the build the scripts install is from Jul 30:

```
$ docker version 
Client:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   bfccd32
 Built:        Thu Jul 30 19:25:53 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   bfccd32
 Built:        Thu Jul 30 19:25:53 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by cpuguy83** [comment] 2015-08-03 17:32
I'm a little weary of running other people's images. Are you able to repro with the busybox image?

**Comment by ruffsl** [comment] 2015-08-03 17:59
I just tried busybox and got the same result. Note that this is still the Jul 30 build.

```
$ docker network create foo
$ docker run --rm \
    --publish-service=talker.foo \
    --name talker \
    busybox \
    ping localhost
$ docker exec -it talker sh
```
How can I enable the experimental commands from the master binaries? Should I just build from source, is there Dockerfile that does this already?

**Comment by aboch** [comment] 2015-08-03 18:09
@ruffsl In order to build the experimental version from master, run
`sudo make DOCKER_EXPERIMENTAL=true`

**Comment by ruffsl** [comment] 2015-08-03 20:23
Thanks @aboch , just tried the building from source with the `DOCKER_EXPERIMENTAL` flag, and the error behavior has ceased. So I guess one thing remaining is why the experimental debs from the install script are no longer "nightly"?

**Comment by cpuguy83** [comment] 2015-08-03 20:39
@ruffsl Glad it's resolved!
Pinging @jfrazelle (sorry!) regarding exp builds

Closing this issue since it looks like it is resolved.

**Closed by cpuguy83** 2015-08-03 20:39 UTC
Labels: status/more-info-needed
