### ISSUE TITLE
Set a reasonable value for TERM when exec’ing

### ISSUE THREAD

**Issue by dato** [docker/docker#20891] opened 2016-03-03 02:12 UTC
Currently, if one creates a container interactively, TERM is set to something reasonable:

```
$ docker run --rm -ti busybox
# echo $TERM
xterm
# exit
```

However, when one runs `exec -ti` into a container that was started in detached mode, TERM is not set. This is understandable, given that TERM is not set in the running container at all.

But it might be a good idea setting TERM for the exec’d process, without modifying the container itself. In this example, setting TERM for _/bin/sh_ only:

```
$ docker run -d --name test_term busybox sleep 3600
$ docker exec -ti test_term /bin/sh
# echo $TERM

# exit
```

**Comment by thaJeztah** [comment] 2016-03-03 13:59
I think this is a duplicate of https://github.com/docker/docker/issues/9299, please continue the discussion there

**Closed by thaJeztah** 2016-03-03 13:59 UTC
