### ISSUE TITLE
docker 1.6.2: pull race condition eats dependent layers

### ISSUE THREAD

**Issue by aaron42net** [docker/docker#13971] opened 2015-06-16 15:33 UTC
Description of problem:

Multiple simultaneous docker pulls that depend on the same underlying layers will corrupt them. 
I've created a simplified test case and steps to reproduce.  See: https://github.com/aaron42net/dockertest

`docker version`:

Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/amd64

`docker info`:

Containers: 0
Images: 4
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.3
Operating System: CoreOS 681.0.0
CPUs: 1
Total Memory: 1.959 GiB
Name: coreos-local
ID: WCR6:W542:LTOR:YK4T:4CVB:M55V:ZEO6:KGYF:DJ3H:22XX:OTTD:S3ZS
Username: aaron42net
Registry: [https://index.docker.io/v1/]

`uname -a`:

Darwin ip-172-22-48-131.ec2.internal 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.):

Both VirtualBox and EC2

How reproducible:

Reliably on the environments I've tested.  You may need a slower net connection, as the images must take enough to time to download that they overlap.

Steps to Reproduce:

```
docker ps -aq | xargs docker rm -f
docker images -q | xargs docker rmi
seq 1 25 | awk '{print "aaron42net/dockertest:app-"$0}' | xargs -n 1 -P 25 docker run
```

Actual Results:

```
FATA[0084] Error pulling image (app-15) from aaron42net/dockertest, Driver overlay failed to create image rootfs e8d7ddc9a499bd28ecdd5c12bf0b38ed3f247b46b10673fc5061f659f73740cc: lstat /var/lib/docker/overe8d7ddc9a499: Error downloading dependent layers 
```

Expected Results:

Test apps running 25 times and printing "Hello, World!"

Additional info:

If you do them sequentially (change the "-P 25" to "-P 1"), it works fine.

**Comment by thaJeztah** [comment] 2015-06-16 20:47
ping @stevvooe this looks very much like what you were describing in https://github.com/docker/docker/issues/9718#issuecomment-112518555. Possibly a dup of that one, but perhaps the repro case here can help you resolving the cause.

Thanks for reporting this, and providing a repro-case @aaron42net!

**Comment by aaron42net** [comment] 2015-06-16 21:01
I see https://github.com/docker/docker/issues/9718 mentions DeviceMapper, which I don't use.  But I've hit this issue with both overlayfs and btrfs atop CoreOS 681.0.0, so I don't think it is specific to a filesystem.

I've worked around the issue by wrapping flock around my docker pulls to serialize them by adding the following to my Fleet units, which is suboptimal:

```
ExecStartPre=-/usr/bin/flock /home/core/pull.lock /usr/bin/timeout 5m /usr/bin/docker pull ...
```

It took me a few days of experimenting to reproduce cleanly, so I hope this helps.

**Comment by thaJeztah** [comment] 2015-06-16 21:20
Going by https://github.com/docker/docker/issues/9718#issuecomment-68762458 it's not related to a specific graph driver, so this issue could well be the same.

> It took me a few days of experimenting to reproduce cleanly, so I hope this helps.

It sure doesn't hurt having a reproducible case :-), thanks so much :+1:

**Comment by stevvooe** [comment] 2015-06-16 21:47
@aaron42net Thank you! This looks like a duplicate of #9718. Here is me "whining" about getting a reproduction: https://github.com/docker/docker/issues/9718#issuecomment-112518555. Now, we have no excuse but to fix this. ;)

A few questions:

1. How did you create the image originally? Was this created initially with 1.6.2?
2. If you recreate the image, can you reproduce this? (trying to eliminate v1/v2 cross-over problems).
3. Does it only happen with `docker run` or can you reproduce with `docker push`?

**Comment by aaron42net** [comment] 2015-06-16 23:45
They were built on docker 1.6.2 on CoreOS 681.0.0 this morning, but I just noticed that I had a typo in the one of my layers that was depending on a private repo that might've been a few weeks old and built on docker 1.5.0.

After fixing the typo and re-pushing-the images all built on docker 1.6.2, I can no longer reproduce using the above steps.

I'm going to try building the base image again on 1.5.0 and pushing those, then building the upper layers on 1.6.2 and see if the problem comes back.

**Comment by stevvooe** [comment] 2015-06-17 00:48
@aaron42net Interesting. I will be excited to hear your result. Thank you for the continuing thorough investigation.

**Comment by aaron42net** [comment] 2015-06-17 02:00
Okay, so building on 1.6.2 is fine.  It's just that on my faster Mac on a faster 'net connection at work, I can't seem to reproduce the pull bug.

I updated the README.md in https://github.com/aaron42net/dockertest to match what I just did to build on Docker 1.6.2 on my work machine.  All of the Dockerfiles and such are in that repo, if you want to play with building your own. After doing that, I can reproduce on my home machine running Docker 1.6.2.

I have previously tried pull instead of run.  All of the pulls may finish, but trying to run them will often claim that /bin/bash is missing or similar.  The last time I looked at the list of missing files, the whole debian:jessie layer was missing.

Do you know how debian:jessie is built?  Is that on 1.5.0 or 1.6.2?

**Comment by stevvooe** [comment] 2015-06-17 23:19
@aaron42net Actually, `debian:jessie` was the same image we had seen this issue with. We were not able reproduce the error when _only_ pulling, but would generally encounter it on a run on a corrupt image without a pull.

debian:jessie was built with the automated builder for the official repositories. @cpuguy83 @tianon any idea here? If you're having trouble reproducing the issue now, I suspect the image has been updated and no longer has whatever conflict caused the original corruption.

**Comment by tianon** [comment] 2015-06-19 21:25
The most recent build of `debian:jessie` was built on 1.6.0, and would've happened roughly 4 days ago (latest commit on https://github.com/docker-library/official-images/blob/master/library/debian).  This information should also be able to be scraped from the layer itself:

```console
$ docker inspect -f '{{.Created}} - Docker {{.DockerVersion}}' debian:jessie
2015-06-15 22:44:39.555142548 +0000 UTC - Docker 1.6.0
```

What's reported here definitely sounds like a strange bug, though. :confused:

**Comment by stevvooe** [comment] 2015-06-19 23:12
@tianon Oddly, that is around the time when this was no longer reproducible...

**Comment by andytinycat** [comment] 2015-06-22 18:23
I am absolutely encountering this bug. I have a number of images built from the same base image, which is built from upstream `ubuntu:12.04`.

When my Mesos slaves start, they may pull several images, depending on the jobs they are handling. With newly-booted Mesos slaves (i.e. they have no images), I encounter this bug 100% of the time.

My internal registry is v2. No idea if the Ubuntu images are coming from v2, but I would expect so. I'm encountering this on 1.6.0, 1.6.2 and 1.7.0, and it is actually a complete showstopper bug.

**Comment by aaron42net** [comment] 2015-06-23 13:53
@stevvooe I just rebuilt the aaron42net/dockertest images with the latest debian:jessie and I can still reproduce.

**Comment by andytinycat** [comment] 2015-06-23 17:07
A dirty hack you can use is to "shim" Docker to do a lock before pulling. This is what I'm doing.

I create a shell script called `docker` earlier in $PATH (so it will be called before the actual Docker binary), with the following contents:

```bash
if [ "$1" == "pull" ]; then
  (
    flock 9 || exit 1
    /usr/bin/docker "$@"
  ) 9>/tmp/docker_pull_shim_lock
else
  exec /usr/bin/docker "$@"
fi
```

Now this will be invoked before the Docker binary. If the first argument is `pull`, then it takes a lock and does the pull; otherwise it simply replaces itself with the actual Docker binary.

A hack, yes, but necessary until this bug is triaged and fixed.

**Comment by stevvooe** [comment] 2015-06-25 00:28
@andytinycat We know this is a nasty issue. We've added the 1.7.1 milestone and are working towards a fix.

**Comment by stevvooe** [comment] 2015-06-25 17:19
@andytinycat @aaron42net 

I have a [patch][1] that replicates the flock solution at an image granularity. This should prevent the image from getting corrupted but won't correct existing corrupted images. Inspection of that code shows a few other issues we need to address in that function (there is come variable shadowing @vbatts).

@aaron42net If you could build my branch and give it a try, it would be a big help. We are having trouble reliably reproducing and would feel better if we could get some validation on your end.

@dmcgowan PTAL

[1]: https://github.com/docker/docker/compare/master...stevvooe:concurrent-pull-fix

**Comment by aaron42net** [comment] 2015-06-25 20:44
I've spun up an EC2 instance that's detached from the rest of my infrastructure, has ssh available globally, and has a new SSH key.  I'm happy to share it with you if you can tell me how to get you the key privately.

Alternatively, you can spin up an m3.large EC2 instance in us-east-1a using AMI ami-79ad4712, attach the 32G instance storage to /dev/xvdb and use this for user-data: https://www.die.net/tmp/82ffab2a7418a7b4/coreos-test.userdata

I did that and logged in and ran the following and it broke right away:

 ```
seq 1 25 | awk '{print "aaron42net/dockertest:app-"$0}' | xargs -n 1 -P 25 docker run
```

**Comment by dmcgowan** [comment] 2015-06-26 00:05
The patch posted by @stevvooe solved the issue in my testing. I used the testing process described by @aaron42net

**Comment by stevvooe** [comment] 2015-06-26 03:39
@aaron42net We've built you a version with the patch. Please give it a try:

https://docs.google.com/a/docker.com/uc?authuser=0&id=0BxIgF_yUbnRkdjNCZXV2eWU0V1k&export=download

**Closed** 2015-06-29 17:28 UTC
Labels: Distribution

**Comment by aaron42net** [comment] 2015-06-29 20:30
@stevvooe: I've dropped that image on to my test instance, written a replacement systemd unit to /etc/systemd/system/docker.service and run `systemctl daemon-reload` and `systemctl restart docker` and see the new one running in ps:

```
root       809 12.7  0.5 1307056 44796 ?       Ssl  20:21   0:58 /home/core/docker-1.7.1-pr14193 --daemon --host=fd://
```
I then ran `seq 1 25 | awk '{print "aaron42net/dockertest:app-"$0}' | xargs -n 1 -P 25 docker run` again and had the same result:

```
c7044d50a3f3: Error pulling image (app-16) from aaron42net/dockertest, endpoint: https://registry-1.docker.io/v1/, Driver overlay failed to create image rootfs a9dc0db39add6e28f009a128fe5efa4bdc021ee3b14dec3e6590b879ad339950: write /var/lib/docker/ovc
7044d50a3f3: Error pulling image (app-16) from aaron42net/dockertest, Driver overlay failed to create image rootfs a9dc0db39add6e28f009a128fe5efa4bdc021ee3b14dec3e6590b879ad339950: write /var/lib/docker/overlay/a9dc0db39add6e28f009a128fe5efa4bdc021ec1eb8b260132: Error downloading dependent layers 
```

**Comment by stevvooe** [comment] 2015-06-29 20:44
@aaron42net Did you clear out the images from `/var/lib/docker` before running the test? The PR does not correct existing corruption.

**Comment by aaron42net** [comment] 2015-06-29 20:58
On Mon, 29 Jun 2015, Stephen Day wrote:

> @aaron42net Did you clear out the images from `/var/lib/docker` before running the test? The PR does not correct existing corruption.

I did.  I also terminated the instance and re-created from a fresh instance.

Would running docker in debug mode help? How do I get you more information?

This is running on the instance that I can share the key to, if you want to
mess with it yourself.  If so, how do I get an ssh private key to you?

                                    -- Aaron

**Comment by vbatts** [comment] 2015-07-06 20:14
(one race cleanup here -->  #14413 )

**Comment by stevvooe** [comment] 2015-07-07 16:56
@aaron42net Not sure if this will change anything but give the 1.7.1 rc a try: https://test.docker.com/builds/Linux/x86_64/docker-1.7.1-rc1.

We may have a completely different root cause if this isn't working.
