### ISSUE TITLE
docker service unpublish seems to assume bridge driver

### ISSUE THREAD

**Issue by tomdee** [docker/docker#14084] opened 2015-06-22 00:23 UTC
docker service ls lists some services (I didn't create them explicitly, I just did docker run --net=host)

I can't get rid of them - I get an error about the bridge network.

```
gulfstream@gulfstream:~/calico-docker$ docker service ls
SERVICE ID          NAME                NETWORK             CONTAINER
ca710a00b887        /calico-node        host                47d07c7ddf73
7b03dd066bdc        /calico-etcd        host                ea4776fa0424
0ec4b3a5a512        /calico-consul      host                6dc8271bb6b9
gulfstream@gulfstream:~/calico-docker$ docker service unpublish 7b03dd066bdc
Service 7b03dd066bdc not found on network bridge
gulfstream@gulfstream:~/calico-docker$ docker service unpublish /calico-etcd
Service /calico-etcd not found on network bridge
```

**Comment by mavenugo** [comment] 2015-06-22 00:47
@tomdee can you please try `docker service unpublish <service>.<network>` ?
in your case `docker service unpublish /calico-consul.host`

Also, unpublish must fail your case since there is an attached container.
Please first detach the container before unpublishing it.

Service  name is unique only within a network. And if it is not qualified by the network name, the unpublish assumes the user intent to be default-network, which is a bridge.

This is an expected behavior.

**Comment by tomdee** [comment] 2015-06-22 05:45
OK, I'll give that a go.
- Do you know where the / at the start of the service name is coming from?

**Comment by tomdee** [comment] 2015-06-22 06:14
No, that's still broken. Though a think it's a problem with the delete processing. Should I raise this as another issue?
```
gulfstream@gulfstream:~/calico-docker$ docker ps -a
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS                   PORTS               NAMES
68586e7e6036        progrium/consul               "/bin/start -server    5 minutes ago       Up 5 minutes                                 calico-consul       
2a541ac808e5        quay.io/coreos/etcd:v2.0.11   "/etcd --advertise-c   5 minutes ago       Up 5 minutes                                 calico-etcd         
8ff4048bb8ce        busybox                       "/bin/sh"              5 hours ago         Exited (0) 5 hours ago                       ecstatic_lumiere    
9ae3a522b588        busybox                       "/bin/sh"              5 hours ago         Exited (0) 5 hours ago                       fervent_lalande     
gulfstream@gulfstream:~/calico-docker$ docker service ls
SERVICE ID          NAME                NETWORK                                CONTAINER
913a8b795123        /calico-etcd        host                                   2a541ac808e5
d2a9c994a4f2        /calico-consul      host                                   68586e7e6036
3a231382affa        /calico-node        host                                   71548e4cf984
4448ec070b67        node1               645458dc-71ff-45b6-af02-31bc9ada09a2   
753a9845f092        node2               645458dc-71ff-45b6-af02-31bc9ada09a2   
gulfstream@gulfstream:~/calico-docker$ docker service unpublish /calico-node.host
Error response from daemon: service with name /calico-etcd id 913a8b7951233a6a6812a6167ede1a07cbd0b4c2931bf5a0b92eb1a51af356ad has active containers
```

**Comment by tomdee** [comment] 2015-06-22 06:16
Oh, actually I just noticed that the error response from the daemon talks about a different container! Definitely something broken here.

I would give you the logs but there are none. I'm running the daemon with debugging logging turned on and the failing service unpublish doesn't log anything.

**Comment by tomdee** [comment] 2015-06-22 06:18
When I shut down the daemon I saw:

```
ERRO[0571] Leave all failed for  2a541ac808e5f27cd058f7c7bb3c31a2df0462742b5bb4c515ca1cf83737292c: could not find sandbox for container id 2a541ac808e5f27cd058f7c7bb3c31a2df0462742b5bb4c515ca1cf83737292c 
ERRO[0571] Leave all failed for  68586e7e6036adc0962a20dd2402eeaa68b608ca052124b1e9ee049526d6fc9c: could not find sandbox for container id 68586e7e6036adc0962a20dd2402eeaa68b608ca052124b1e9ee049526d6fc9c 
```

**Comment by mavenugo** [comment] 2015-06-22 11:07
@tomdee as per @mrjana, its due to the graphdb. I haven't digged into it myself. But in one of the open PRs, I removed any `/` from the service name as it is not user-friendly and also causes trouble with service discovery.
The unpublish is failing for a good reason that the service is connected to another backend/container, somewhere in the cluster. You would have to first `detach` the container out of the service on the appropriate host.

Maybe it is good to document this fact clearly that `attach` and `detach` are local events and cannot be executed as a cluster-wide operation, because container is a local concept. In the context of Swarm the master knows the location of each container in the cluster. But when docker is used natively with multi-host networking, it becomes the user's responsibility to execute the command in the correct host.

I think we should close this issue as the behavior of `docker service unpublish` is expected and working just as designed. For any other issues, we can debug it further and open issues if any.

**Comment by tomdee** [comment] 2015-06-22 17:53
So I was only hitting this issue because of the same problem that was just hit in the demo. I'm sure there is or soon will be an issue for that, so I'm happy to close this issue.

BTW - I was hitting this on the branch from #14071 - I see that's now merged so this problem is probably now on master...

**Closed** 2015-07-09 23:45 UTC
Labels: kind/experimental
