### ISSUE TITLE
Network Inspect Format Template Error - Single vs Double Quotes

### ISSUE THREAD

**Issue by dsanders11** [docker/docker#22385] opened 2016-04-28 05:41 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 203
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-152181-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 GB
 Data Space Total: 107.4 GB
 Data Space Available: 4.946 GB
 Metadata Space Used: 17.1 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.13 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.3.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.447 GiB
Name: vm-dsanders
ID: LRMI:EGFK:I6LK:6DEG:C2Z6:4AJO:CRWH:HH7R:NVXZ:ZU6B:UF2M:N4E6
Username: dsanders11
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OS X, but also replicates on CentOS 7.2

**Steps to reproduce the issue:**

Simply run `docker network inspect --format="{{range $container, $conf := .Containers}}{{$conf.IPv4Address}}{{end}}" foo`. The network doesn't have to exist to replicate.

**Describe the results you received:**

Template parsing error: template: :1: unexpected "," in range

**Describe the results you expected:**

Expect to see an IPv4Address such as `172.17.0.9`.

**Additional information you deem important (e.g. issue happens only occasionally):**

It works if you use single quotes around the format instead of double quotes. Using double quotes on both OS X and CentOS 7.2 produce the template error, using single quotes does not. I don't think it's a shell issue since that's two fairly different environments.

**Comment by justincormack** [comment] 2016-04-28 11:37
That is a shell issue - any shell will replace `$container` and `$conf` with the values of the variables (probably empty) if they are in double quotes.

**Comment by thaJeztah** [comment] 2016-04-28 12:10
Yes, basically this is the same as doing;

    echo "{{range $container, $conf := .Containers}}{{$conf.IPv4Address}}{{end}}"

Which results in this (if the `$container` and `$conf` environment variables are not set);

    {{range ,  := .Containers}}{{.IPv4Address}}{{end}}

Due to those values missing; the template is invalid, so docker complains about that.


I'll close this issue, because it's not a bug, but I hope the comments above help you figure out how to fix your use case 👍  feel free to comment after I closed :)

**Closed by thaJeztah** 2016-04-28 12:10 UTC

**Comment by dsanders11** [comment] 2016-04-28 17:34
Thanks. That's a bummer, the error message that comes out is quite unhelpful for figuring out why it is failing. Could it at least be mentioned in the docs as a potential gotcha? The docs in various places show using double quotes [like on `docker ps` formatting](https://docs.docker.com/engine/reference/commandline/ps/#formatting) or [in the usage block for `docker inspect`](https://docs.docker.com/engine/reference/commandline/inspect/) (but then uses single quotes in the examples). Since it's not immediately clear from the error what the gotcha is it'd be nice if the docs were at least consistent and perhaps had a warning on the examples with range.
