### ISSUE TITLE
docker mount issue after migration

### ISSUE THREAD

**Issue by abilash222** [docker/docker#22067] opened 2016-04-15 13:20 UTC
Hi,
We  migrated to docker version 1.10.3 from 1.6.2. after migration mounted path is empty in all previously created containers. For newly created containers it is working fine.

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 209
 Running: 4
 Paused: 0
 Stopped: 205
Images: 978
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-252:0-139-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 53.69 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 80.75 GB
 Data Space Total: 1.611 TB
 Data Space Available: 1.48 TB
 Metadata Space Used: 138.5 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.009 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/sas/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /home/sas/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 251.6 GiB
Name: test-lab
ID: CAVN:4U7T:DVAF:YXKQ:NUUZ:2ABQ:7XYD:QBOM:5ABI:KMHQ:XMSX:BOTK

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

please help at the earliest.

@thaJeztah

**Comment by cpuguy83** [comment] 2016-04-15 13:37
Really need some more details here.
What are the "mounted paths"?
How were these containers set up, etc.

**Comment by abilash222** [comment] 2016-04-15 13:45
sudo docker run -d --name=eclipse -p 4445:4445 -v /home/sas/cide:/home/sas/cide -v /home/sas/eclipseide:/home/sas/eclipseide --env USERID=$(id -u sas) --env GROUPID=$(id -g sas) dockerregistry/abilash/eclipse

**Comment by thaJeztah** [comment] 2016-04-15 14:01
Is this similar to / the same as https://github.com/docker/docker/issues/20079 ?

**Comment by abilash222** [comment] 2016-04-15 14:48
@thaJeztah yes similar to it. any solution for this.

**Comment by thaJeztah** [comment] 2016-04-15 15:13
@abilash222 looks like someone used a script to fix https://github.com/docker/docker/issues/20079#issuecomment-181991147

**Comment by jdoose** [comment] 2016-06-07 08:05
Same happened here, when CoreOS upgraded from 899.17.0 (including Docker 1.9.1) to 1010.5.0 (including Docker 1.10.3).
it looks to me that this is a duplicate of #20079

**Comment by thaJeztah** [comment] 2016-06-07 09:39
Yes I think this is a duplicate of https://github.com/docker/docker/issues/20079. Let's close this one to keep the discussion in a single place. Please continue the discussion on https://github.com/docker/docker/issues/20079

**Closed by thaJeztah** 2016-06-07 09:39 UTC
Labels: version/1.10
