### ISSUE TITLE
unregister_netdevice: waiting for lo to become free. Usage count = -1

### ISSUE THREAD

**Issue by d11wtq** [docker/docker#18156] opened 2015-11-23 03:55 UTC
Docker version: 1.9.0
Operating System: Ubuntu 14.04
Kernel info: 3.13.0-68-generic

On one of our CI servers, which uses docker, we started to see process hangs inside of docker. On `docker ps`, we just got a hang, and then eventually (within a couple of minutes), the entire server started to hang for SSH access. It was still responding to pings, however.

We noticed this in the docker log right before the system locked up:

```
Nov 23 14:32:51 ci3 kernel: [387120.141130] unregister_netdevice: waiting for lo to become free. Usage count = -1
Nov 23 14:33:01 ci3 kernel: [387130.308772] unregister_netdevice: waiting for lo to become free. Usage count = -1
```

Any ideas?

**Comment by phemmer** [comment] 2015-11-23 10:11
see #5618

**Comment by thaJeztah** [comment] 2015-11-23 12:06
Closing as duplicate of https://github.com/docker/docker/issues/5618. Thanks for reporting @d11wtq (and for looking up the duplicate, @phemmer :+1: )

**Closed by thaJeztah** 2015-11-23 12:06 UTC
