### ISSUE TITLE
Base Device UUID and Filesystem verification failed.exit status 2 Centos 7

### ISSUE THREAD

**Issue by mahmedmostafa** [docker/docker#19055] opened 2016-01-04 18:04 UTC
Hello 

docker version: 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

docker info: can not get information docker is down
uname -a:

3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

steps to reproduce the issue 

1 . install docker 1.8.1
2 . start a new container 
3 . stop docker
4 . Attach a new disk
5 . Move the /var/lib/docker to the new disk
6 . Re-mount /var/lib/docker to the new disk
7 . Start docker

I have tried to upgrade it to 1.9.1 , and it does not work

I am using devicemapper on loop files not on lvm/block devices

Please help

**Comment by mahmedmostafa** [comment] 2016-01-04 18:09
This is the result of status on systemctl

[root@NLAMSS03 ~]# journalctl -xn
-- Logs begin at Mon 2016-01-04 19:06:58 CET, end at Mon 2016-01-04 19:07:43 CET. --
Jan 04 19:07:43 NLAMSS03.eunetworks.com docker[2208]: time="2016-01-04T19:07:43.449059264+01:00" level=warning msg="Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man
Jan 04 19:07:43 NLAMSS03.eunetworks.com kernel: Buffer I/O error on device dm-3, logical block 26214367
Jan 04 19:07:43 NLAMSS03.eunetworks.com kernel: Buffer I/O error on device dm-3, logical block 26214367
Jan 04 19:07:43 NLAMSS03.eunetworks.com kernel: Buffer I/O error on device dm-3, logical block 26214367
Jan 04 19:07:43 NLAMSS03.eunetworks.com kernel: Buffer I/O error on device dm-3, logical block 26214367
Jan 04 19:07:43 NLAMSS03.eunetworks.com docker[2208]: time="2016-01-04T19:07:43.521334425+01:00" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: Base Device UUID and Filesystem verification failed.exit status 2
Jan 04 19:07:43 NLAMSS03.eunetworks.com docker[2208]: time="2016-01-04T19:07:43.521389384+01:00" level=fatal msg="Error starting daemon: error initializing graphdriver: Base Device UUID and Filesystem verification failed.exit status 2"
Jan 04 19:07:43 NLAMSS03.eunetworks.com systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jan 04 19:07:43 NLAMSS03.eunetworks.com systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.

```
ls -al /dev/dm*
brw-rw---- 1 root disk 253, 0 Jan  4 19:07 /dev/dm-0
brw-rw---- 1 root disk 253, 1 Jan  4 19:07 /dev/dm-1
brw-rw---- 1 root disk 253, 2 Jan  4 19:07 /dev/dm-2
```

**Comment by ztetfger** [comment] 2016-01-19 10:59
I meet the same question, anyone can help us?

**Comment by thaJeztah** [comment] 2016-02-16 12:37
I'm not sure if moving /var/lib/docker actually works with device mapper, see https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configuring-docker-with-device-mapper

@rhvgoyal perhaps you can shed some light on this?

**Comment by rhvgoyal** [comment] 2016-02-16 15:04
I tried this on latest upstream docker and it worked for me. So either there is a problem with older version of docker or there is a problem with the way you have moved files.

**Comment by LK4D4** [comment] 2016-10-18 17:47
Closing as nobody confirmed bug since Vivek tried.

**Closed by LK4D4** 2016-10-18 17:47 UTC
Labels: area/storage/devicemapper
