### ISSUE TITLE
How to update stateful services with swarm mode

### ISSUE THREAD

**Issue by jimmycmh** [docker/docker#31175] opened 2017-02-20 03:52 UTC
When updating a swarm mode service, new containers will be created without taking over the previous volumes, so that the state will lost.

Do you have any plan to solve this issue?

**Comment by gianarb** [comment] 2017-02-20 08:59
Hello

You can still mount a volume as you do in Docker. You just need to be sure that your containers are in the right hosts.
https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#add-bind-mounts-or-volumes

There are different projects that help you to solve persistent problem in distributed containarized application. One of them is https://infinit.sh/ . Docker supports also volume plugins that allow you to extend the normal capabilities if you need to use a particular distributed storage.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other types of questions, consider using one of:

* https://forums.docker.com
* the docker community slack channel (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
* StackOverflow

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by gianarb** 2017-02-20 08:59 UTC
