### ISSUE TITLE
Rootfs in docker 1.10

### ISSUE THREAD

**Issue by PRADEEPKJ** [docker/docker#26566] opened 2016-09-14 13:02 UTC
Hi All,

Could you please tell me where will be the rootfs of the docker image in docker 1.10.3

I tried in /var/lib/docker. Dint find 
Please let me know how it will get stored.

Regards,
Pradeep

**Comment by unclejack** [comment] 2016-09-14 13:19
Hello 

This issue tracker is dedicated to tracking Docker bugs, proposals and pull requests to make changes to Docker's source code. This issue tracker isn't a general support forum.
Please keep in mind that opening issues to ask questions when getting started will make everyone who contributes to the project spend more time looking at issues.


This kind of question and general support questions are more adequate for the following:
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.
4) StackOverflow https://stackoverflow.com/questions/tagged/docker

I'm going to close this issue now because the discussion can continue even after the issue is closed. Please feel free to continue the discussion. There's no need to open a new issue on this topic.

**Closed by unclejack** 2016-09-14 13:19 UTC
