### ISSUE TITLE
docker networking

### ISSUE THREAD

**Issue by NikolaMandic** [docker/docker#18833] opened 2015-12-21 21:14 UTC
hey everyone I hope you do not mind this issue
but did anyone bumped into this 
http://blog.viktorpetersson.com/post/101707677489/the-dangers-of-ufw-docker
it just happened to me

**Comment by cpuguy83** [comment] 2015-12-24 14:04
Closing as this is not an issue.

UFW stores it's own state rather than use what's actually set in iptables, which is likely the cause of any issue you see with UFW and Docker.

**Closed by cpuguy83** 2015-12-24 14:04 UTC
