### ISSUE TITLE
Last item in response stream is empty when pulling an image with Docker 1.8+

### ISSUE THREAD

**Issue by AdamWill** [docker/docker#17031] opened 2015-10-14 17:35 UTC
Hi, Docker folks. Ran into this while debugging an ansible-docker issue: https://github.com/ansible/ansible-modules-core/issues/2043 . I got a hack merged to ansible-docker for now, but the real issue seems to be in Docker.

It seems then when doing an image pull using docker-py , with `stream=True`, the last item in the response stream (which is a sequence of JSON dict strings, it seems) is empty. ansible actually prints the entire stream in the error. The very end of it - the last two items - looks like this:

    "{\"status\":\"Status: Downloaded newer image for docker.io/mesoscloud/mesos-master:0.23.0-centos-7\"}\r\n", "{}\r\n"]

So the second-to-last item is a dict containing the final status message, but the very last item is simply an empty dict.

This broke ansible-docker because it expected the last item in the stream to contain the status message.

AFAICT nothing has changed in docker-py to cause this, and indeed you can turn the bug 'on' and 'off' by simply switching between Docker 1.7 and Docker 1.8 without changing ansible or docker-py versions. So it seems the issue is in Docker, but I couldn't manage to work out where, it's pretty hard to just dive in and spot what would be causing this.

Here's a relatively simple reproducer ansible playbook:

    - hosts: 192.168.1.*
      user: root
      tasks:
      - name: deploy test container
        docker:
          name: "test"
          image: busybox
          state: started
          privileged: true

obviously you need a 192.168.1.(something) host in `/etc/ansible/hosts`, or adjust the `hosts` line as necessary. That just deploys the busybox image (I used that because it's small). If you run it with Docker 1.7, it'll work fine. With Docker 1.8 the *first* time you run the playbook you should see the failure, if you run the playbook a *second* time it will succeed (as the image is now downloaded and it seems this bug doesn't hit the 'image downloaded already' case). To bring the bug back you can just `docker rm` the container and `docker rmi` the image so it has to download it again. Of course, use an ansible version which doesn't have the workaround applied (e.g. current stable, not current git head).

-----------------------------
BUG REPORT INFORMATION
-----------------------------
Use the commands below to provide key information from your environment:

`docker version`: 
    Client:
     Version:      1.8.2-fc23
     API version:  1.20
     Package Version: docker-1.8.2-7.gitcb216be.fc23.x86_64
     Go version:   go1.5.1
     Git commit:   77d0d91-dirty
     Built:        Mon Oct 12 16:58:35 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.8.2-fc23
     API version:  1.20
     Package Version: 
     Go version:   go1.5.1
     Git commit:   77d0d91-dirty
     Built:        Mon Oct 12 16:58:35 UTC 2015
     OS/Arch:      linux/amd64
`docker info`:
    Containers: 4
    Images: 25
    Storage Driver: devicemapper
     Pool Name: docker-253:0-25942647-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: xfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 3.856 GB
     Data Space Total: 107.4 GB
     Data Space Available: 4.109 GB
     Metadata Space Used: 3.723 MB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.144 GB
     Udev Sync Supported: true
     Deferred Removal Enabled: false
     Data loop file: /var/lib/docker/devicemapper/devicemapper/data
     Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
     Library Version: 1.02.107 (2015-09-05)
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.2.3-300.fc23.x86_64
    Operating System: Fedora 23 (Twenty Three)
    CPUs: 1
    Total Memory: 3.86 GiB
    Name: openqa-dev.happyassassin.net
    ID: F4JF:5KWV:QO2F:BMPW:MHBC:7AYQ:URQ4:QPHI:XOQN:DKOA:YM54:7I5Z
`uname -a`:
    Linux openqa-dev.happyassassin.net 4.2.3-300.fc23.x86_64 #1 SMP Mon Oct 5 15:42:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Provide additional environment details (AWS, VirtualBox, physical, etc.):
    KVM.

List the steps to reproduce the issue:
1. Please
2. See
3. All the damn steps I already wrote above.

Describe the results you received:
All the ones I already wrote above.

Describe the results you expected:
All the ones I already wrote above.

Provide additional info you think is important:
Sure, because this isn't long enough already!

----------END REPORT ---------

**Comment by AdamWill** [comment] 2015-10-14 18:10
Sigh, idiotic bots are idiotic. Fine, I'll repeat all the information I already provided, thus making this report longer and harder to read! Let's call it progress.

**Comment by thaJeztah** [comment] 2015-10-18 22:30
Heh, yeah @GordonTheTurtle can be a PITA. Feel free to ignore him if you already provided the information, or it doesn't make sense for the type of issue.

**Comment by thaJeztah** [comment] 2015-10-18 22:32
Just to be sure, would you be able to test if you're still able to reproduce this on the 1.9-RC? https://github.com/docker/docker/pull/17000#issuecomment-147926878

**Comment by thaJeztah** [comment] 2016-05-02 09:46
I'll close this, because there's been a lot of changes in this area since 1.8, but feel free to comment if you're still having this issue in the current release

**Closed by thaJeztah** 2016-05-02 09:46 UTC

**Comment by AdamWill** [comment] 2016-05-02 15:57
sorry, in the end Docker turned out to be causing more problems than it was solving for this particular thing I was working on so we stopped using it, thus I don't know if this is still happening. The ansible module folks might, though, I guess. @abadger any idea if this is still going on?
