### ISSUE TITLE
1.12rc2: Cannot create containers with overlay network.

### ISSUE THREAD

**Issue by sdemura** [docker/docker#23901] opened 2016-06-23 14:35 UTC
**Output of `docker version`:**

```
~$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: active
 NodeID: dajmc033h7dlq7ckrb3lrvs73
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:a66134e21db54aece05e342480dddf6eebcf7f369399daa79558c5bc32affe81
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-boot2docker
Operating System: Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: YROR:XV6G:I5E5:JZCH:ED37:I36J:TQA4:GWOE:VCQM:KBSX:CB44:L6YG
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 112
 System Time: 2016-06-23T14:31:01.553076833Z
 EventsListeners: 1
Username: sdemura
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker Toolbox 1.12rc2 for Mac.

**Steps to reproduce the issue:**
1. Launch docker vm
2. Initialize a swarm
3. Create an overlay network
4. Attempt to run a container with new network

```
$ docker swarm init --listen-addr 192.168.99.100:2377
Swarm initialized: current node (dajmc033h7dlq7ckrb3lrvs73) is now a manager.
~$ docker network create test_network -d overlay
e4n63vh4t0z8142kp2j0jbsiq
~$ docker run --net test_network hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
a9d36faac0fe: Pull complete
Digest: sha256:e52be8ffeeb1f374f440893189cd32f44cb166650e7ab185fa7735b7dc48d619
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: network test_network not found.
See 'docker run --help'.
~$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
8625ea168e65        bridge              bridge              local
3a9b6494bc4a        docker_gwbridge     bridge              local
189fe6f3aa0e        host                host                local
dlursqan326x        ingress             overlay             swarm
2a9e2cefe947        none                null                local
e4n63vh4t0z8        test_network        overlay             swarm
```
**Describe the results you received:**
I was not able to create a container with the overlay network I created.

**Describe the results you expected:**
I would expect to be able to run a container with the overlay network I created.

**Additional information you deem important (e.g. issue happens only occasionally):**
This is consistently reproducible.

**Comment by kelseyhightower** [comment] 2016-06-23 15:23
I can confirm the same issue in my environment. I'm running on GCE with a fresh install of `1.12.0-rc2` with swarm mode enabled.

**Comment by sodre90** [comment] 2016-06-23 16:29
You can not use swarm network with 'docker run' command. I got this error message:
`docker: Error response from daemon: swarm-scoped network (test_network) is not compatible with docker create or docker run. This network can be only used docker service.`

**Comment by IevgenKabanets** [comment] 2016-06-23 18:02
Experimental release, 1.12rc2 on Ubuntu 14.04.
Same here. What's strange, is that if you have cluster, you create custom overlay network, it's not seen on workers.
Either something is wrong or we're doing it wrong (what's there to do apart from join cluster, right?). Example:

` docker network create -d overlay --subnet=10.0.9.0/24 int_network `
```
docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
afda0267a3ff        bridge              bridge              local
b399e53285fe        docker_gwbridge     bridge              local
454cc5397d51        host                host                local
0gz8194kgkjf        ingress             overlay             swarm
5awrivl7hwnk        int_network         overlay             swarm
fbbd1287a4ef        none                null                local
```

List of nodes:
```
docker node list
ID                           NAME              MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
4hfyd4i7cdzp0wma5p1bqn9ky *  vamsdocker03      Accepted    Ready   Active        Leader
7pd9i94u2tq7le1zwqhp8iofu    kabae-sandbox-01  Accepted    Ready   Active
avo1ghl7yefo9g77emhavbxdn    vamsdocker04      Accepted    Ready   Active
```

Inspect from Master node into any worker shows 2 overlays (one default of Swarm, another freshly created):

`docker node inspect 7pd9i94u2tq7le1zwqhp8iofu`
```
[
...

...

            "Engine": {
                "EngineVersion": "1.12.0-rc2",
                "Plugins": [
                    {
                        "Type": "Volume",
                        "Name": "local"
                    },
                    {
                        "Type": "Network",
                        "Name": "overlay"
                    },
                    {
                        "Type": "Network",
                        "Name": "bridge"
                    },
                    {
                        "Type": "Network",
                        "Name": "null"
                    },
                    {
                        "Type": "Network",
                        "Name": "host"
                    },
                    {
                        "Type": "Network",
                        "Name": "overlay"
                    }
                ]
            }
        },
        "Status": {
            "State": "ready"
        }
    }
]
```

Workers have no idea about it though:
```
docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
d259a12c39e1        bridge              bridge              local
b399e53285fe        docker_gwbridge     bridge              local
454cc5397d51        host                host                local
fbbd1287a4ef        none                null                local
```

**Comment by sdemura** [comment] 2016-06-23 18:03
@IevgenKabanets -- I've noticed the same thing. If you promote a worker to a manager then the network shows up, but it's still unusable.

**Comment by mrjana** [comment] 2016-06-23 18:07
@sdemura @kelseyhightower @sodre90 @levgenKabanets Yes, `docker run --net` on an overlay network created in swarm mode is not supported in 1.12-rc2. It can only be used with a `service`. If you want to run a simple container you still need to use the external k/v store and not use `swarm mode`

**Comment by IevgenKabanets** [comment] 2016-06-23 18:16
Hey @mrjana, will it stay like that? 
I'm afraid it was not how many might have understood from DockerCon.

**Comment by mrjana** [comment] 2016-06-23 18:21
@IevgenKabanets It probably will not stay like that. The support for that just did not make it into 1.12

**Comment by sdemura** [comment] 2016-06-23 18:21
@mrjana -- I hope these limitations will be noted in the documentation, but I do hope this will change in future updates.

@levgenKabantes -- I have the same sentiments. 

I was very much under the impression I wouldn't have to deal with a 3rd party K/V store, which would have vastly simplified my (automated) infrastructure.

**Comment by cpuguy83** [comment] 2016-06-24 14:24
@sdemura @levgenKabanets swarm mode, services, etc requires no external k/v, old functionality continues to work as it always has.

**Comment by IevgenKabanets** [comment] 2016-06-24 14:41
@cpuguy83 thanks Brian, it's more of a question about leveraging new functionality (aka built-in KV) for that. Or question of overkill of having 2 K/V stores. It's not a question of compatibility. But, I hope what @mrjana said about making it in next release - is true, user-experience wise it makes all the sense (I know docker service is the way to go, but it's not always what might be needed). Thanks a lot for sharing info.

**Comment by cpuguy83** [comment] 2016-06-24 14:45
@IevgenKabanets I've added to the 1.12 milestone to discuss the usability concerns around this for 1.12 at least.
It seems like if the user has not specified any of the `--cluster-*` options we should be able to assume the built-in cluster store.... but there may be usability issues around this as well.

**Comment by IevgenKabanets** [comment] 2016-06-24 17:52
@cpuguy83 perfect. I think many would appreciate to have this limitations in documents somehow. Would definitely be less issues created. For all I know, there will be a big amount of ppl, that will assume this functionality present.

**Comment by ajeetraina** [comment] 2016-07-04 00:15
What I see is whenever you create user defined overlay on the master node, it is not reflected on the worker node. But when you try creating services and then assigning the task or scaling it out, the overlay network gets automatically created and now it shows up on the worker nodes.

**Comment by IevgenKabanets** [comment] 2016-07-07 10:25
@cpuguy83 @mrjana 

Kind of revisiting topic. So, supposedly, after 2 services are created within the same overlay network (classical web app), DB tier can be reached from Web using embedded DNS? 

So, let's say if:
`docker service create --name tutum --network=mynet -p 80:80 --replicas 5 tutum/apache-php`
`docker service create --name bbox --network=mynet postgres`
then any given container on web-app tier can reach db? 

How can that be verified? Cause `ping bbox` does not succeed, while `ping db_container_name` works fine. But then, what should be put into _web-app_ tier configs in order to reach _db-tier_? We can't hardcode names of containers, right? 

Any help appreciated, as always, thanks.

**Comment by mavenugo** [comment] 2016-07-08 11:10
@IevgenKabanets 

> How can that be verified? Cause ping bbox does not succeed, while ping db_container_name works fine. But then, what should be put into web-app tier configs in order to reach db-tier? We can't hardcode names of containers, right? 

You should be able to use the service name in your web-app tier configs. `ping service-name` not succeeding is unrelated.

Infact ping to a `service-name` with a VIP will not succeed and that is currently expected. Being a VIP, the  ICMP traffic must be load-balanced by IPVS to underlying containers in order for ping to VIP to succeed. But that is currently not possible with IPVS (being a L4 Load-balancer). But the ping to container works because it is bypassing the IPVS.

> Kind of strange, that 2 containers same IP address, while being on the same overlay net.

Yes. that is strange and unexpected. If you have a consistent way to reproduce it, can you please open an issue ?

**Comment by mavenugo** [comment] 2016-07-08 11:14
@sdemura @IevgenKabanets @kelseyhightower regarding the original intent of this issue (supporting `docker run` to accept network managed by swarm), we are actively working on supporting that functionality. Lets use this issue to track that functionality.

**Comment by aboch** [comment] 2016-09-14 05:47
What asked here is now possible in master after #25962 was merged.
This issue should be closed.

**Comment by mrjana** [comment] 2016-09-14 05:56
Closing as fixed.

**Closed by mrjana** 2016-09-14 05:56 UTC
Labels: area/networking, area/swarm, kind/bug, priority/P2, version/1.12
