### ISSUE TITLE
docker inspect shows odd CMD in ContainerConfig

### ISSUE THREAD

**Issue by bdanofsky** [docker/docker#18880] opened 2015-12-23 19:09 UTC
docker inspect shows random line executed in a DOCKERFILE for a container created with an ENTRYPOINT but no CMD.  This information is placed in the ContainerConfig section.  The Config section of the docker inspect output looks correct (CMD is null).

The output from inspect looks like:

        "Cmd": [
            "/bin/sh",
            "-c",
            "#(nop) ADD file:56b23cd6c66a5207b7777b5a9f79693f696223a03ed0e9a190b3cdf55d40cba0 in /etc/supervisor/conf.d/userapp.conf"
        ],

another example

        "Cmd": [
            "/bin/sh",
            "-c",
            "#(nop) EXPOSE 22222/tcp"
        ],

docker client and daemon information:

Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

**Comment by duglin** [comment] 2015-12-23 21:19
@bdanofsky what you're seeing there is related to the history of how the image was created. Try running `docker history ...` on your image and you'll see the complete history. Docker will place the Dockerfile commands into the CMD section as a way of keeping track of how that layer/container was created. Its really only used for cache-lookup purposes (internal docker processing) and not meant to be used by the user.

Going to close this because this is working as designed and not really a bug.

**Closed by duglin** 2015-12-23 21:19 UTC

**Comment by numberZero** [comment] 2022-03-31 18:01
> Docker will place the Dockerfile commands into the CMD section as a way of keeping track of how that layer/container was created. Its really only used for cache-lookup purposes (internal docker processing) and not meant to be used by the user.

Where is that documented?

**Comment by n0099** [comment] 2025-01-06 16:01
https://stackoverflow.com/questions/66638179/docker-image-command-starts-with-bin-sh-c-nop-cmd
https://stackoverflow.com/questions/41298934/what-does-nop-mean-in-docker-history
