### ISSUE TITLE
[1.12.2-beta28 (12906)] Docker exec fails to find `cd`

### ISSUE THREAD

**Issue by wulftone** [docker/docker#27479] opened 2016-10-18 06:28 UTC
Ran into this error today with something wrong with `$PATH` (wasn't happening yesterday):

```bash
$ docker exec -it myapp-dev cd /app; pwd
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"cd\\\": executable file not found in $PATH\"\n"
/Users/me/work/myapp

$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
ebc5d4dcde86        myapp-hhvm/hhvm:wip      "/app/entrypoint.sh"     49 minutes ago      Up 49 minutes       80/tcp, 0.0.0.0:8999-9000->8999-9000/tcp   myapp-dev

$ docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

`docker exec -it myapp-dev bash` works fine though.

**Comment by AkihiroSuda** [comment] 2016-10-18 06:54
This is not an issue because cd is shell's built-in command.

You can try `sh -c "cd /app; pwd"` instead

**Comment by thaJeztah** [comment] 2016-10-18 07:17
@AkihiroSuda beat me to it :smile: I'll close this issue, as this is not a bug, but feel free to continue the conversation if you need more info

**Closed by thaJeztah** 2016-10-18 07:17 UTC
Labels: version/1.12
