### ISSUE TITLE
Create deb package for ubuntu 16.04

### ISSUE THREAD

**Issue by HackToday** [docker/docker#23509] opened 2016-06-14 09:21 UTC
Follow this script:
https://github.com/docker/docker/tree/master/contrib/builder/deb/amd64/ubuntu-xenial

I run 
```
docker build -t  xenial_deb .
```

It only create an image, but I did not where can I get the deb package. 

Sorry to ask here, but really very difficult to catch that, or what we have docs for that to refer?

**Comment by HackToday** [comment] 2016-06-14 09:22
@thaJeztah  do you know this details ? I remembered you talked this before general steps, now, I tried to build one deb master package for ubuntu 16.04, But I did not know where can find that deb ?

**Comment by thaJeztah** [comment] 2016-06-14 11:36
You can build deb or rpm packages using `make deb` / `make rpm`. By default,
all supported distros are built (see
https://github.com/docker/docker/tree/master/contrib/builder/rpm/amd64 and
https://github.com/docker/docker/tree/master/contrib/builder/deb/amd64).

If you want to build only for specific distro, use the `DOCKER_BUILD_PKGS`
env-var, for example, to build a `deb` package for Ubuntu Xenial;

```bash
DOCKER_BUILD_PKGS=ubuntu-xenial make deb
```

or, outside a container (not using docker-in-docker)

```bash
DOCKER_BUILD_PKGS=ubuntu-xenial hack/make.sh dynbinary build-deb
```

Those builds are run in a container (so you should have docker running), but
the results are put in the `bundles` directory on your host;

```
tree bundles/
bundles/
├── 1.12.0-dev
│   ├── build-deb
│   │   ├── docker.log
│   │   ├── test.log
│   │   └── ubuntu-xenial
│   │       ├── Dockerfile.build
│   │       ├── docker-engine_1.12.0~dev~git20160518.202625.0.1691fe6-0~xenial.dsc
│   │       ├── docker-engine_1.12.0~dev~git20160518.202625.0.1691fe6-0~xenial.tar.gz
│   │       ├── docker-engine_1.12.0~dev~git20160518.202625.0.1691fe6-0~xenial_amd64.changes
│   │       └── docker-engine_1.12.0~dev~git20160518.202625.0.1691fe6-0~xenial_amd64.deb
│   ├── dynbinary
│   ├── dynbinary-client
│   │   ├── docker -> docker-1.12.0-dev
│   │   ├── docker-1.12.0-dev
│   │   ├── docker-1.12.0-dev.md5
│   │   └── docker-1.12.0-dev.sha256
│   └── dynbinary-daemon
│       ├── dockerd -> dockerd-1.12.0-dev
│       ├── dockerd-1.12.0-dev
│       ├── dockerd-1.12.0-dev.md5
│       └── dockerd-1.12.0-dev.sha256
└── latest -> 1.12.0-dev
```

**Comment by thaJeztah** [comment] 2016-06-14 12:23
I'll close this issue, because this is not a bug, but feel free to continue the discussion

**Closed by thaJeztah** 2016-06-14 12:23 UTC

**Comment by HackToday** [comment] 2016-06-15 01:53
hi @thaJeztah  I tried following instruction and hit this:(run build with docker-in-docker ways)

```
 Built:        Wed Jun 15 01:46:11 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
---> Making bundle: .integration-daemon-stop (in bundles/1.12.0-dev/build-deb)
++++ /etc/init.d/apparmor stop
Clearing AppArmor profiles cache:.
All profile caches have been cleared, but no profiles have been unloaded.
Unloading profiles will leave already running processes permanently
unconfined, which can lead to unexpected situations.

To set a process to complain mode, use the command line tool
'aa-complain'. To really tear down all profiles, run the init script
with the 'teardown' option."
Makefile:86: recipe for target 'deb' failed
make: *** [deb] Error 1
```

**Comment by HackToday** [comment] 2016-06-15 01:54
maybe @justincormack  knows more why failed with that

**Comment by HackToday** [comment] 2016-06-17 05:50
ping @justincormack  and @thaJeztah  Could you help ?

**Comment by thaJeztah** [comment] 2016-06-17 06:31
hm, strange; I just tried, and it worked for me; did it complete building the binaries before it exited? Was platform are you running on?

**Comment by HackToday** [comment] 2016-06-17 06:39
hi @thaJeztah  I tried on ubuntu 14.04, The only different I used in host docker is docker static binary, (I think it had apparmor enabled).

For build deb docker-in-docker ways. I double checked `bundles/1.12.0-dev/` have `dynbinary-client` and `dynbinary-daemon`(`daemon` directory only had `dockerd`, it not have `runc` and `contained` etc.)

**Comment by thaJeztah** [comment] 2016-06-17 06:46
I know we had an issue once with static binaries and apparmor, if the static binary was not installed in the default path, wondering if that can be an issue here?

**Comment by HackToday** [comment] 2016-06-17 08:38
@thaJeztah  do you mean ask question to me ?  😆  I am not sure about that.

Or ping @justincormack  I knew you know much about apparmor/secomp related
