### ISSUE TITLE
Docker images command isn't filtering images with custom port correctly

### ISSUE THREAD

**Issue by orkaa** [docker/docker#18292] opened 2015-11-28 23:59 UTC
```
Docker version 1.9.1, build a34a1d5
```

```
Containers: 7
Images: 229
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 243
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 2
Total Memory: 1.963 GiB
Name: dev
ID: XBL2:2X5B:6R3T:QBZV:AIDQ:INN3:QLIT:OBKR:5APD:GSLN:OBD6:JYVX
WARNING: No memory limit support
WARNING: No swap limit support
```

```
Linux celtra-dev 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt2-1~bpo70+1 (2014-12-08) x86_64 GNU/Linux
```

This should pretty much point out the issue:

```
root@dev# docker images | grep lala
test:4000/lala      latest                                     ce3e63034b09        2 minutes ago       474.2 MB
test4000/lala       latest                                     ce3e63034b09        2 minutes ago       474.2 MB
root@dev# curl http://172.17.42.1:2375/images/json?filter="test:4000/lala"
[]
root@dev# curl http://172.17.42.1:2375/images/json?filter="test4000/lala"
[{"Id":"ce3e63034b0940729c6e208c87ce5028c2b6fe6abb0e2a5d0715207be35c4651","ParentId":"973bec2aaff33d0ab02ee5701d9a69a36f16fe4eaf1841a62dae30a8d6074a09","RepoTags":["test4000/lala:latest"],"RepoDigests":[],"Created":1448700606,"Size":24410985,"VirtualSize":474190804,"Labels":{}}]
```

I created two images, one with and one without a colon. A colon is used to specify a custom port when using a private repository. As can be seen, filter isn't working correctly when searching for images that include a colon in the name. 

This can be reproduced by either calling the json api or using docker client.

**Comment by thaJeztah** [comment] 2015-11-29 00:08
Thanks for reporting, it looks like this is a duplicate of https://github.com/docker/docker/issues/18181 and resolved by https://github.com/docker/docker/pull/18215

I just added that PR to the 1.9.2 milestone, but it's not decided yet if we'll be releasing a 1.9.2 release before docker 1.10 is released.

You should be able to test using our nightly builds from master; https://master.dockerproject.org (but don't use those on production, just for testing :smile:)

I'm going to close this issue, because it should be resolved, but feel free to comment here after I've close or if I close by mistake :+1:

**Closed by thaJeztah** 2015-11-29 00:08 UTC

**Comment by orkaa** [comment] 2015-11-29 00:18
Ahhh, I'm always too late. :)

Good to see it's already fixed, thanks!

**Comment by thaJeztah** [comment] 2015-11-29 00:19
Haha, no problem, thanks for reporting, it's much appreciated!
