### ISSUE TITLE
docker exec -it lead to container hang up

### ISSUE THREAD

**Issue by blackfader** [docker/docker#9965] opened 2015-01-08 05:24 UTC
hi all
I find a docker exec bug
when i do this：
```
docker exec -it 9b120801425d bash
```
and I dont't quite "docker exec"

someone exec "/etc/init.d/docker restart" in another terminal in this host machine。

"docker restart" will hang up ,docker process was killed，but can't start docker daemon process

cat /var/log/docker

```
time="2015-01-08T12:53:15+08:00" level="error" msg="Handler for GET /exec/{id:.*}/json returned error: engine is shutdown"
time="2015-01-08T12:53:15+08:00" level="error" msg="HTTP Error: statusCode=500 engine is shutdown"
..time="2015-01-08T12:53:43+08:00" level="error" msg="Warning: error unmounting device 026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92: UnmountDevice: device not-mounted id 026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92\n"
time="2015-01-08T12:54:03+08:00" level="error" msg="Warning: error unmounting device 026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92: UnmountDevice: device not-mounted id 026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92\n"
time="2015-01-08T12:54:03+08:00" level="error" msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container 026f: Error getting container 026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92 from driver devicemapper: Error mounting '/dev/mapper/docker-253:1-1310734-026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92' on '/usr/local/docker/devicemapper/mnt/026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92': device or resource busy"
time="2015-01-08T12:54:03+08:00" level="error" msg="HTTP Error: statusCode=500 Cannot start container 026f: Error getting container 026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92 from driver devicemapper: Error mounting '/dev/mapper/docker-253:1-1310734-026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92' on '/usr/local/docker/devicemapper/mnt/026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92': device or resource busy"
```

when i exec "/etc/init.d/docker start" ,docker daemon process can start up.

but this container was dead! .

I can't stop or rm -f or start this container !

error:
```
time="2015-01-08T12:54:35+08:00" level="error" msg="Handler for DELETE /containers/{name:.*} returned error: Cannot destroy container 026f1dab924b: Driver devicemapper failed to remove root filesystem 026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92: Device is Busy"
time="2015-01-08T12:54:35+08:00" level="error" msg="HTTP Error: statusCode=500 Cannot destroy container 026f1dab924b: Driver devicemapper failed to remove root filesystem 026f1dab924bbd3829f8cc3c7fced664bd2a8967fd7ebd14b961b7e8cb8fdd92: Device is Busy"
time="2015-01-08T12:54:54+08:00" level="error" msg="daemon.driver.Cleanup(): device or resource busy"
time="2015-01-08T12:57:46+08:00" level="error" msg="Handler for GET /exec/{id:.*}/json returned error: engine is shutdown"
time="2015-01-08T12:57:46+08:00" level="error" msg="HTTP Error: statusCode=500 engine is shutdown"
..time="2015-01-08T12:58:45+08:00" level="error" msg="Warning: error unmounting device 2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff: UnmountDevice: device not-mounted id 2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff\n"
time="2015-01-08T12:59:25+08:00" level="error" msg="Warning: error unmounting device 2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff: UnmountDevice: device not-mounted id 2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff\n"
time="2015-01-08T12:59:25+08:00" level="error" msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container 2db3b02c1f7c: Error getting container 2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff from driver devicemapper: Error mounting '/dev/mapper/docker-253:1-1310734-2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff' on '/usr/local/docker/devicemapper/mnt/2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff': device or resource busy"
time="2015-01-08T12:59:25+08:00" level="error" msg="HTTP Error: statusCode=500 Cannot start container 2db3b02c1f7c: Error getting container 2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff from driver devicemapper: Error mounting '/dev/mapper/docker-253:1-1310734-2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff' on '/usr/local/docker/devicemapper/mnt/2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff': device or resource busy"
time="2015-01-08T13:00:41+08:00" level="error" msg="Handler for DELETE /containers/{name:.*} returned error: Cannot destroy container 2db3: Driver devicemapper failed to remove root filesystem 2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff: Device is Busy"
time="2015-01-08T13:00:41+08:00" level="error" msg="HTTP Error: statusCode=500 Cannot destroy container 2db3: Driver devicemapper failed to remove root filesystem 2db3b02c1f7cd712cb4db015002472ccb87df2eb8c10462cb875c214d40426ff: Device is Busy"
time="2015-01-08T13:03:20+08:00" level="error" msg="daemon.driver.Cleanup(): device or resource busy"
```

is this a bug ?

docker version
```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

**Comment by LK4D4** [comment] 2015-01-08 06:01
@blackfader Thanks for report! Your issue duplicate of #9699 and was fixed in master.

**Closed by LK4D4** 2015-01-08 06:01 UTC
