### ISSUE TITLE
Docker Save Command Issue

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#10592] opened 2015-02-05 16:28 UTC
Description of problem:

When saving a repo, if you specify the image by ID, then the FQIN is discarded.  On load, the result is a '<none>' name '<none>' tag repo which isn't very user-friendly.  However, saving by FQIN does preserve the repo. name/tag, such that loading the tarball restores them.

`docker version`:

Client version: 1.4.1-dev
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): e1b875c
OS/Arch (client): linux/amd64
Server version: 1.4.1-dev
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): e1b875c

`docker info`:

Containers: 93
Images: 59
Storage Driver: devicemapper
 Pool Name: docker-253:2-2766409-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.006 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 10.06 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.17.7-300.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 4
Total Memory: 11.43 GiB
Name: dhcp-10-19-62-194.boston.devel.redhat.com
ID: R54O:3ZKE:PREZ:FO6U:C36U:TN45:4VVI:B5O3:OZXT:O5QG:OWTE:47IR
Debug mode (server): true
Debug mode (client): false
Fds: 12
Goroutines: 17
EventsListeners: 0
Init SHA1: 1b7372ffe99bf1de06bef70cd8f2108335de676a
Init Path: /home/shishir/docker/src/github.com/docker/docker/bundles/1.4.1-dev/dynbinary/dockerinit
Docker Root Dir: /var/lib/docker

`uname -a`:
Linux dhcp-10-19-62-194.boston.devel.redhat.com 3.17.7-300.fc21.x86_64 #1 SMP Wed Dec 17 03:08:44 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Physical, Fedora 21

How reproducible:
100%

Steps to Reproduce:
1. docker save -o <image name>.tar <image name>
2. docker save -o <image ID>.tar <image ID>
3. docker rmi <image name>
4. docker load -i <image ID>.tar
5. docker images
6. docker load -i <image name>.tar
7. docker images

Actual Results:

[root@dockertest ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker_testimage    test_tag            9e4968c9710f        18 minutes ago      499.5 MB
[root@dockertest ~]# docker save -o docker_testimage:test_tag.tar docker_testimage:test_tag
[root@dockertest ~]# docker save -o 9e4968c9710f.tar 9e4968c9710f
[root@dockertest ~]# docker rmi docker_testimage:test_tag
Untagged: docker_testimage:test_tag
Deleted: 9e4968c9710f332e416307a1ac25cc80c5c2a85271234e38022ce300fa966c34
...cut...
Deleted: bef54b8f8a2fdd221734f1da404d4c0a7d07ee9169b1443a338ab54236c8c91a
[root@dockertest ~]# docker load -i 9e4968c9710f.tar
[root@dockertest ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              9e4968c9710f        23 minutes ago      499.5 MB
[root@dockertest ~]# docker load -i docker_testimage\:test_tag.tar 
[root@dockertest ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker_testimage    test_tag            9e4968c9710f        23 minutes ago      499.5 MB

Expected Results:

[root@dockertest ~]# docker load -i 9e4968c9710f.tar
[root@dockertest ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker_testimage    test_tag            9e4968c9710f        23 minutes ago      499.5 MB
[root@dockertest ~]# docker load -i docker_testimage\:test_tag.tar 
[root@dockertest ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker_testimage    test_tag            9e4968c9710f        23 minutes ago      499.5 MB

Additional info:
In the case of saving by ID, all the FQIN's which point at that ID should be recorded.  On load, only the non-conflicting names should be restored, preferably issuing a warning about any name conflicts

**Comment by shishir-a412ed** [comment] 2015-02-05 16:32
Additional Information:
http://pastebin.com/BwYJB9dS

Saving by ID doesn't generate the repositories JSON file, while saving by image name generates the JSON.

**Comment by estesp** [comment] 2015-02-05 21:39
This is exactly how the code is designed, and I'm not sure there is an easy fix given the daemon controls the tagstore (repository of image<-->id metadata) where a reverse lookup might be performed, but the graph code is (by design) not dependent on daemon and doesn't have access to that information.

You can see where it defaults to "this must just be a plain ID" here: https://github.com/docker/docker/blob/master/graph/export.go#L74-L77

Given it won't have gone through any repo data, there will be nothing to export as far as repository data, so it won't write that file.

**Comment by jfrazelle** [comment] 2015-02-10 18:00
Closing as described above

**Comment by shishir-a412ed** [comment] 2015-02-10 18:45
@jfrazelle just because it is designed this way, doesn't mean it's not an issue. 
we should be able to do `docker save using ID` and if it is tagged to multiple FQINs (image names) it should save all that information by generating the repositories JSON file.

So that later on if I do a `docker load < ***.tar` it should populate the non conflicting ones, and not a <none> image: <none> tag.

<NONE> image: <NONE> tag looks like it's broken.

I ll take a look into the issue, and see if we can fix this.

**Comment by jfrazelle** [comment] 2015-02-10 18:50
I reopened, sorry, thanks for clarifying

**Comment by richardcrichardc** [comment] 2015-03-04 21:31
I have noticed this problem when working on #11104 and have spent some time investigating the cause and have a fairly good idea what needs to be changed to fix this. If no one else is working on this I would be happy to work up a fix.

FQINs are also not exported for the lower exported layers. I take it this should also be improved.

**Comment by shishir-a412ed** [comment] 2015-03-04 23:08
@richardcrichardc I have not started working on this, if you want to give it a shot, you are more than welcome !

**Comment by richardcrichardc** [comment] 2015-03-05 23:59
I've worked up a [fix](https://github.com/richardcrichardc/docker/tree/saveAllFQINs), no doc changes etc yet. @shishir-a412ed, do you think I should create a pull request.

Some observations:
* This is a breaking change!
* [API](https://docs.docker.com/reference/api/docker_remote_api_v1.17/#get-a-tarball-containing-all-images-in-a-repository) docs are pretty clear that the current behaviour is correct, [`docker save`](https://docs.docker.com/reference/commandline/cli/#save) docs are a bit more vague.
* Probably need some focus on different use cases. From my current use case of transferring a working image between two Docker instances, the current implementation does not seem quite right.
* When a repo name but no tag is specified, all images in the repo are exported. After getting used to `docker pull repo-name` doing the same as `docker pull repo-name:latest`, I expected `docker export repo-name` to do the same as `docker export repo-name:latest`. Then I read the manual and discovered this is the documented behaviour. It is worth pointing out people don't read and that is why I would argue all the Docker commands should treat repo names consistently.
* There seems to be some tension in the design/terminology with repositories being named repositories, some commands treating them like repositories and others treating them like 'package names'. I.e.`docker pull` behaving like package managers, taking a 'package name' as it's main argument and pulling the latest version if no version is specified.  I am not suggesting either behaviour is better.
* Need to check how `docker load` handles the 'latest' tag, potential for conflicts here. I don't yet have a clear idea in my head what `latest` really means, so am unsure what the 'right' behaviour is.

**Comment by shishir-a412ed** [comment] 2015-03-09 16:33
@richardcrichardc I would open a pull request and start a discussion.
by 'breaking change' if you mean it's broken, you would need to fix that to get the attention of the maintainers.

Jenkins should run successfully for them to take a look.

Shishir

**Comment by richardcrichardc** [comment] 2015-03-09 19:50
@shishir-a412ed thanks for the advice. 

By 'breaking change' I mean it changes the interface, which will potentially break clients. I am being cautious here, it extends the behaviour.

**Comment by shishir-a412ed** [comment] 2015-03-09 19:53
@richardcrichardc okay got it :) 
I would say discuss on the docker-dev channel about your implementation strategy, before making major changes.

**Comment by termie** [comment] 2015-03-10 21:09
+1

**Comment by rhatdan** [comment] 2015-04-14 19:43
Any movement on this?

**Comment by shishir-a412ed** [comment] 2015-04-16 16:25
@richardcrichardc were you able to make any progress on this?

**Comment by richardcrichardc** [comment] 2015-04-16 20:57
@shashir-a1412ed @rhatdan 

No progress whatsoever. I posted a couple of different things on the docker-dev mailing list but did not get any response from the maintainers of docker save.

 I did get a somewhat over the top response on the related and less controversial (not breaking) pull request #11104. A core contributor to docker distribution thinks this sort of thing should come under that project. However docker distribution seems to have considerable scope and be at the spec stage. I am not really up for getting involved with that.

I will bump the [mailing list thread](https://groups.google.com/forum/#!topic/docker-dev/TAg5C9FI3hY) and see if I get any more traction. Feel free to chime in. It might also be worth posting something to the regular docker mailing list where more people lurk to see if more users are finding this a problem..

**Comment by estesp** [comment] 2015-04-16 21:22
@richardcrichardc the distribution project went GA today (https://github.com/docker/distribution/releases/tag/v2.0.0) so it's a little bit past the spec stage :)  

This new registry, and specifically the "v2" API, are supported in DockerHub as well, so definitely anything registry-related should be done in the context of the that project as anything of importance to registry has to be done there.  The docker daemon can speak both v1 and v2 API, given there are still v1 registries all over the place, and even DockerHub still supports the v1 API as fallback for all older clients.

I would strongly suggest continuing discussions on the features you think are lacking or specifics around load/save/export/import .. if you can get on IRC, the #docker-distribution channel is open discussion on all things registry and may have better response time, especially given the release has caused a lot of the team to be pretty heads-down.

**Comment by richardcrichardc** [comment] 2015-04-16 21:38
@estesp That may be where the confusion is arising. This is not registry related. This is image import/export related. 

From the top of this thread:

> Description of problem:
> 
> When saving a repo, if you specify the image by ID, then the FQIN is discarded. On load, the result is a > '' name '' tag repo which isn't very user-friendly. However, saving by FQIN does preserve the repo. > name/tag, such that loading the tarball restores them.

When you look at it in more detail you see, the FQIN for the parent images is never exported. 

It would seem reasonable to expect name/tags to be preserved when doing a save then a load.

**Comment by shishir-a412ed** [comment] 2015-04-16 22:24
@estesp 
I would agree with @richardcrichardc This is not a registry related change.

@richardcrichardc I don't know if you have already tried this, but `#docker-dev` irc channel is pretty active for such discussions.

Just PM me on freenode with a half n hour notice, and I ll join you on the discussion on irc.
my irc alias: shishir-a412ed

**Comment by richardcrichardc** [comment] 2015-04-16 22:39
@shishir-a412ed No, just the docker-dev mailing list. 

I have just taken on a three month contract so don't really have the brain space to drive this forward right now. If you can get some attention from the docker devs I will chip in though. Happy to join an IRC chat. My timezone is UTC+12, I am in the office 9-5.

**Comment by estesp** [comment] 2015-04-17 02:23
Hey guys, sorry if I added confusion, but both your responses were why I specifically said "distribution".  While you are both correct that changes around save/load are not registry-specific, they are "image distribution" specific, and the distribution project is named as such, instead of "docker-registry" because "all things image distribution"-related need to be discussed in light of how the docker client, daemon, and registry work together to utilize images.  That project (docker/distribution) may contain the v2 registry specifically, but it is tightly bound to how the daemon interacts with the registry and how it interacts with the image and manifest formats between client, daemon, and registry.

That said, I looked at your branch @richardcrichardc and I think it might be worth pursuing for the save/load by-id-only use case.  It would have to be discussed as it changes current behavior, as you mentioned, but without a proposal/PR that discussion probably won't happen.  If you guys want help from a docker dev, then I can help bring it forward if necessary with the appropriate folks.  Thanks for your patience.

**Comment by richardcrichardc** [comment] 2015-04-17 02:39
@estesp Also probably did not help that I linked to a whole repo rather than a (diff)[https://github.com/docker/docker/compare/master...richardcrichardc:saveAllFQINs]. I will make sure it merges cleanly and turn in into a PR.

**Comment by richardcrichardc** [comment] 2015-05-07 04:34
Just checking to see if the issue exist on the latest version before creating a pull request and I noticed that when pulling repositories from the registry, FQINs are only added for the name images. This is the same behaviours as is occuring with docker save. Does anyone know if this is considered a feature?

**Comment by shishir-a412ed** [comment] 2015-05-07 13:27
@richardcrichardc can you give an example ?

**Comment by richardcrichardc** [comment] 2015-05-07 21:58
shishir-a412ed  If I start with a server with no images:
```
root@5a1e2cf46aab:/go/src/github.com/docker/docker# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
```

Then pull an image:
```
root@5a1e2cf46aab:/go/src/github.com/docker/docker# docker pull openshift/busybox-http
Pulling repository openshift/busybox-http
faa6bb60018a: Download complete 
511136ea3c5a: Download complete 
b35a85c6432e: Download complete 
1ea703a65bda: Download complete 
24110dba3fdf: Download complete 
70ee67c19ade: Download complete 
e848148546bb: Download complete 
61ac3da04c45: Download complete 
e99669bab669: Download complete 
25de5aab7dcf: Download complete 
e0bfe564e79b: Download complete 
Status: Downloaded newer image for openshift/busybox-http:latest
```

Then list the images:
```
root@5a1e2cf46aab:/go/src/github.com/docker/docker# docker images -a
REPOSITORY               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
openshift/busybox-http   latest              faa6bb60018a        6 weeks ago         2.441 MB
<none>                   <none>              25de5aab7dcf        6 weeks ago         2.441 MB
<none>                   <none>              e99669bab669        6 weeks ago         2.441 MB
<none>                   <none>              e0bfe564e79b        6 weeks ago         2.441 MB
<none>                   <none>              e848148546bb        6 weeks ago         2.441 MB
<none>                   <none>              61ac3da04c45        6 weeks ago         2.441 MB
<none>                   <none>              70ee67c19ade        6 weeks ago         2.441 MB
<none>                   <none>              24110dba3fdf        11 months ago       2.438 MB
<none>                   <none>              1ea703a65bda        11 months ago       2.438 MB
<none>                   <none>              b35a85c6432e        11 months ago       0 B
<none>                   <none>              511136ea3c5a        23 months ago       0 B
```

The FQIN has only been set for the image I named. 

This is consistent with the behaviour we are seeing for `docker save`. I personally do not find this helpful, but the consistency suggests there is some method to this, i.e. the maintainers may consider this to be a feature.

If the maintainers believe this is a feature, then a pull request that changes this behaviour is likely to be dead in the water. I just don't want to waste time bringing my patch up to date with master if it is a non-starter.

@estesp, any thoughts?

**Comment by shishir-a412ed** [comment] 2015-05-08 04:01
@richardcrichardc I have seen this behavior at atleast 2 places. N This is what I understand.
Don't quote me on this :)

1) If a docker load is loading an existing image (rhel7) with new content ... the old one gets renamed to <none> : <none> 
2) Another example I have seen is with docker commit. If I commit the contents of a running container to an existing image, the existing one gets renamed to <none> : <none> , the commit gets the name.

Shishir

**Comment by shishir-a412ed** [comment] 2015-07-16 20:39
@richardcrichardc for the two points I mentioned above:

1) `docker load`: We have already added a warning message to atleast notify the user which image is getting renamed to <none\>:<none\>.
2) `docker commit`: This is fixed in docker upstream. this doesn't result in <none\>:<none\> images.

The reason why you see a lot of <none\>:<none\> images when you do `docker images -a` is because they are intermediate images.
I wrote a blog post giving more details about this behavior. Feel free to check it out.

http://www.projectatomic.io/blog/2015/07/what-are-docker-none-none-images/

Coming back to my original `docker save` issue resulting in <none\>:<none\> images. Were you able to open a PR for this ? if I not I ll start working on this now.

Shishir

**Comment by richardcrichardc** [comment] 2015-07-16 20:45
@shishir-a412ed. 
Hi Shishir,
No, I have not progressed this. I have been busy working on a contract and will not have time to get my head back in this any time soon. Feel free to make use of anything I have done to date. Richard

**Comment by tiborvass** [comment] 2015-07-20 17:49
After discussing with @shishir-a412ed I think the best solution here would be to be conservative and disallow saving images by ID. This is also in light of the new distribution effort of what an "image" is. Layers are low-level implementation details, and low-level plumbing tools could help with managing that, but from `docker save`'s perspective it makes sense to only talk about images and not layers (even if currently image = layer). It should help us to start making that distinction early.

This also raises the question of what `docker images -a` is for and whether we should deprecate it once we have a plumbing tool for image distribution / image layers.

@docker/core-maintainers let me know what you think. Do you think it is a painful breaking change?

If anybody has use-cases with `docker save $IMG_ID` we'd be interested to hear about it.

**Comment by ncdc** [comment] 2015-07-20 17:58
+1 to disallowing saving by v1 ID.

cc @stevvooe @dmcgowan @vbatts

**Comment by stevvooe** [comment] 2015-07-20 22:29
Part of the issue is the duality of image id/layer id that makes this model confusing and inflexible. The other interesting aspect is that the the layer ID may be valid only on a single instance. Moving the same id to another host could have a collision. A maliciously constructed `docker save` file could overwrite other layers with the same ID.

@richardcrichardc @shishir-a412ed As I've advocated before, we should support import/export of individual layers, which meets most of the described use cases. This is a small, non-controversial API change. The identifiers reflect the internals and it will work well.

@tiborvass The only thing that makes sense for `docker save` is to allow export by image name or digest, so I agree. Using the layer/image id as the primary identifier leads to other problems.

**Comment by shishir-a412ed** [comment] 2015-07-20 23:10
> Part of the issue is the duality of image id/layer id that makes this model confusing and inflexible. 
+1 Completely agree on this.

The other interesting aspect is that the the layer ID may be valid only on a single instance. Moving the same id to another host could have a collision. A maliciously constructed docker save file could overwrite other layers with the same ID.  +1 for this, hence the layer ID should be a cryptographic checksum and not just a unique ID. Not sure if this is already true.

@stevvooe Can you elaborate on a use-case for import/export of individual layers. In my opinion layers are low level concepts which should not be exposed to a docker user.

Are you okay for throwing an error message for now, if someone tries to do a `docker save $IMD_ID` ?

**Comment by stevvooe** [comment] 2015-07-20 23:13
> Are you okay for throwing an error message for now, if someone tries to do a docker save $IMD_ID ?

Yes.

**Comment by crosbymichael** [comment] 2015-07-27 20:17
This is not an issue with save, it's working exactly like it should minus the fact that it does not contain repo (name) information if using the ID.  This is something that should be fixed with load if overwriting is a concern.  You cannot protect the loading of the image by breaking save because I can just craft my own tarballs and load them in docker daemons.  If something needs to be fixed or have a warning/confirmation it should be docker load before it overwrites something that you are unaware of.  Alot of this depends on the image format and signature being used as IDs.

**Comment by aidanhs** [comment] 2015-08-05 03:59
@tiborvass

> After discussing with @shishir-a412ed I think the best solution here would be to be conservative and disallow saving images by ID.

I've read this issue three times and I can't see where this suggestion has come from. The problem being describer is: exporting by ID does not export image names. If exporting by image name is acceptable (i.e. your proposal of disallowing export by ID isn't a problem) then why can't @shishir-a412ed just do that in the first place?

> It should help us to start making that distinction early.

You end up crippling anyone trying to do manipulate layers via docker save because 1) the plumbing commands don't exist yet and 2) this removes one of the workarounds people have. Wanting to nail down distribution before adding plumbing is completely reasonable, but continuing to remove features in the meantime is a bit unfriendly. 

> If anybody has use-cases with docker save $IMG_ID we'd be interested to hear about it.

I stumbled across this issue by chance - wouldn't it be appropriate to ask this kind of question on one of the Docker mailing lists? The concrete use case at the moment is using it as a workaround for exporting individual layers. Tagging these layers isn't really an option given removing the tag potentially triggers layer deletion (unless you resort to some sneaky tricks)!

----

@stevvooe 

> we should support import/export of individual layers [...] This is a small, non-controversial API change.

Great! Can I raise an issue for this now then? Previous tickets were closed while distribution was in progress. I'm very keen for this to land, especially before more handling of image ID is removed.

----

@shishir-a412ed 

As noted above, I don't really understand what you're trying to solve here. Originally you wanted saves by image id to include image names...but later you're happy with saves by image id to be disabled completely?

> Can you elaborate on a use-case for import/export of individual layers. In my opinion layers are low level concepts which should not be exposed to a docker user.

What about people who want to develop on top of the concepts Docker provides without needing to get something into Docker core? Similar to how git users don't need to know about git blobs, but it's a useful thing for developers. My use case is better low bandwidth syncing of large images - layering is good, but it's possible to do much much better if you look at similarities between layers themselves.

**Comment by shishir-a412ed** [comment] 2015-08-05 13:20
@aidanhs 
The use-case was since `docker save by IMG_ID` does not preserve names, the load creates an untagged image. Which can be confusing for user as he doesn't know which image got loaded.

Check this: https://github.com/docker/docker/pull/15263

**Comment by aidanhs** [comment] 2015-08-05 14:27
You could just save by name instead? Or are you saying this difference in behaviour is too confusing? I don't have strong feelings on whether export by image ID should include names or not, so if that solves your use case then great. However, I do have strong feelings that disabling export by image ID is not the correct solution for reducing confusion given the price!

(though it doesn't completely solve your problem, you could tell the user which image has been loaded in the same way we inform them which container has been started with `docker run -d` - just print the ID)

**Comment by shishir-a412ed** [comment] 2015-08-05 14:54
@aidanhs 
I am talking about an image which has 3 tags. And I want to export that image using IMG_ID.
On doing the load I should see all the 3 tags the way it was during save, but What I see is an untagged image.

Moreover other docker save options like `docker save by name` does create the `repositories` JSON.
So why not keep it in sync for all options. 

For example;
`docker save d2a0ecffe6fa > ubuntu.tar`

REPOSITORY   TAG        IMAGE ID
ubuntu:                latest       d2a0ecffe6fa
ubuntu:                14.04       d2a0ecffe6fa
ubuntu:                 12.02      d2a0ecffe6fa

**Comment by aidanhs** [comment] 2015-08-05 15:25
Fair enough, PR sounds reasonable, like I said I have no strong feelings about adding the tags if it helps.
(I have some implementation comments but will wait for design review)

**Comment by thaJeztah** [comment] 2015-10-21 20:22
Closing per https://github.com/docker/docker/pull/15263#issuecomment-150010636, but feel free to comment here if there are still unresolved issues :+1:

**Closed by thaJeztah** 2015-10-21 20:22 UTC
Labels: exp/expert, group/distribution, kind/enhancement
