### ISSUE TITLE
dnsmasq for docker

### ISSUE THREAD

**Issue by kayrus** [docker/docker#12179] opened 2015-04-08 09:04 UTC
Are there any plans to integrate docker with dnsmasq like it is done in libvirt? I suppose everybody would like to see that functionality instead of writing scripts with "docker inspect" and putting that information into custom dnsmasq manually.

**Comment by thaJeztah** [comment] 2015-04-08 09:40
No, there currently aren't plans to integrate this, and I don't think this will be part of the docker "core" functionality.

There are however various projects that automatically manage DNS-entries for containers using the docker "events" API. A quick search for some examples (for inspiration, as they may not match your exact use case);

https://www.npmjs.com/package/docker-dns
https://github.com/tonistiigi/dnsdock
http://wiredcraft.com/blog/dns-and-docker-containers/
https://registry.hub.docker.com/u/skynetservices/skydns/


I'm going to close this issue as it's a question and not a bug. Feel free to continue the discussion here, on https://forums.docker.com/ or on https://groups.google.com/forum/#!forum/docker-user

**Closed by thaJeztah** 2015-04-08 09:40 UTC
Labels: kind/question
