### ISSUE TITLE
17.03.1-ce on deb : 'docker build' fails when http_proxy build arg is not predefined in environment

### ISSUE THREAD

**Issue by keyidentity-simon** [docker/docker#32526] opened 2017-04-11 14:16 UTC
`docker build --build-arg=http_proxy` fails, if `http_proxy` is not pre-defined in the environment.

Same problem for:

```
https_proxy
no_proxy
```

**Steps to reproduce the issue:**

debian stretch
docker 17.03.1-ce

```
> cat Dockerfile 
FROM debian:stretch
```

Without `build-arg=http_proxy` it is fine
`> docker build . > /dev/null`

With `build-arg=http_proxy` and **no pre-define** of `http_proxy` it fails
```
> docker build --build-arg=http_proxy . > /dev/null
error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.27/build?buildargs=%7B%22http_proxy%22%3Anull%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&ulimits=null: read unix @->/var/run/docker.sock: read: connection reset by peer
```
`build-arg` with pre-defined `http_proxy` is running well
`> http_proxy=foo docker build --build-arg=http_proxy . > /dev/null`

**Additional information you deem important (e.g. issue happens only occasionally):**

Working fine with older docker version 1.12

**Output of `docker version`:**

`Docker version 17.03.1-ce, build c6d412e`

**Output of `docker info`:**

```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 54
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-2-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58 GiB
Name: nb03
ID: J7F7:V5TY:VBPB:XQZE:VU32:YFRF:IJPI:IMDS:SJYP:ZJMF:6JJK:ZWR2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-04-11 14:20
This looks like a duplicate of https://github.com/docker/docker/issues/31990, which is fixed in 17.04.0 through https://github.com/docker/docker/pull/31351

/cc @dnephin

**Comment by dnephin** [comment] 2017-04-11 14:46
Interesting, I didn't realize that my PR had fixed anything, I'll test it out and confirm

**Comment by dnephin** [comment] 2017-04-11 16:04
Confirmed it's fixed

**Closed by dnephin** 2017-04-11 16:04 UTC
Labels: area/builder

**Comment by keyidentity-simon** [comment] 2017-04-11 16:22
thanks for the fast response. Also verified and tested with 17.05 master.
