### ISSUE TITLE
Docker start times out if firewalld is started

### ISSUE THREAD

**Issue by clnperez** [docker/docker#13019] opened 2015-05-06 15:05 UTC
Description of problem:
Starting docker as usual (systemctl start docker) fails after a timeout. If I stop firewalld, then I can start docker. But as long as firewalld is running, I can't start docker.

`docker version`:
  Docker version 1.7.0-dev, build b5d6894

`docker info`:
(Docker isn't starting, but I'm making the turtle happy:)
FATA[0000] Get http:///var/run/docker.sock/v1.19/info: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 

`uname -a`:
- Linux host 3.19.5-200.fc21.x86_64 #1 SMP Mon Apr 20 19:51:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

And because I saw  libvirt error messages:
libvirt-1.2.9.2-1.fc21.x86_64

Environment details:
Physical (laptop) 
Running Fedora 21 x86_64

How reproducible:
Reliably.

Steps to Reproduce:
1. git checkout master
2. ./hack/make.sh dynbinary
3. cp new docker binary and dockerinit to /usr/bin/docker and /var/lib/docker/init/
4. sudo systemcl start docker

Actual Results:
$ sudo systemctl start docker
Job for docker.service failed. See "systemctl status docker.service" and "journalctl -xe" for details.

Expected Results:
docker starts

Additional info:
git bisect narrowed it down to commit 8301dcc6d702a97feeb968ee79ae381fd8a4997a (as I mentioned in Issue 9395). Here's some more debug information. There are many more of the same kinds of errors from /var/log/firewalld, but I'm only pasting a few here.

From  systemctl status docker:

```
-- Unit UNIT has begun starting up.
May 05 18:30:02 host systemd[8653]: Received SIGRTMIN+24 from PID 8775 (kill).
May 05 18:30:02 host systemd[8657]: pam_unix(systemd-user:session): session closed for user root
...skipping...
May 05 18:22:00 host libvirtd[2082]: operation failed: filter 'no-mac-spoofing' already exists with uuid 3bb1297f-f8e1-46cc-a863-809d737514b3
May 05 18:22:00 host libvirtd[2082]: operation failed: filter 'no-arp-mac-spoofing' already exists with uuid 16045c07-ce58-400b-a4d1-187ca35abd
May 05 18:22:00 host libvirtd[2082]: operation failed: filter 'allow-incoming-ipv4' already exists with uuid 74050bd5-9089-4f20-8a4e-42181d40fb
May 05 18:22:00 host libvirtd[2082]: operation failed: filter 'no-mac-broadcast' already exists with uuid 439f5d63-3bb0-4d32-815b-f37732454c99
May 05 18:22:00 host libvirtd[2082]: operation failed: filter 'allow-dhcp-server' already exists with uuid dd2d1d3c-4744-42b7-95f4-2394b53bf84b
May 05 18:22:00 host libvirtd[2082]: operation failed: filter 'no-other-l2-traffic' already exists with uuid 108dd102-eef0-49da-a366-55ece767a6
May 05 18:22:00 host libvirtd[2082]: operation failed: filter 'no-ip-spoofing' already exists with uuid 9e688028-a748-4b64-b802-752019c332cb
May 05 18:22:01 host sudo[7393]: christy : TTY=pts/3 ; PWD=/home/christy/git/go-workspace/src/github.com/docker/docker ; USER=root ; COMMAND=/b
May 05 18:22:01 host sudo[7393]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 05 18:22:01 host docker[7396]: time="2015-05-05T18:22:01.511157548-05:00" level=info msg="[graphdriver] using prior storage driver \"device
May 05 18:23:31 host systemd[1]: docker.service start operation timed out. Terminating.
May 05 18:23:31 host systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 05 18:23:31 host systemd[1]: Failed to start Docker Application Container Engine.
```

From /var/log/firewalld:

```
2015-05-06 09:29:20 DEBUG1: direct.passthrough('ipv4', '--table','nat','--delete','POSTROUTING','--source','192.168.122.0/24','!','--destination','192.168.122.0/24','--jump','MASQUERADE')
2015-05-06 09:29:20 ERROR: COMMAND_FAILED: '/sbin/iptables -w --table nat --delete POSTROUTING --source 192.168.122.0/24 ! --destination 192.168.122.0/24 --jump MASQUERADE' failed: iptables: No chain/target/match by that name.
2015-05-06 09:29:20 DEBUG1: direct.passthrough('ipv4', '--table','filter','--delete','FORWARD','--destination','192.168.122.0/24','--out-interface','virbr 0','--match','conntrack','--ctstate','ESTABLISHED,RELATED','--jump','ACCEPT')
2015-05-06 09:29:20 ERROR: COMMAND_FAILED: '/sbin/iptables -w --table filter --delete FORWARD --destination 192.168.122.0/24 --out-interface virbr0 --match conntrack --ctstate ESTABLISHED,RELATED --jump ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
```
-- 

All the errors there have the same "Bad rule" description attached, and every time there's a failure, it was for a 'delete' operation. The immediately following 'insert' operations all succeed.

**Comment by clnperez** [comment] 2015-05-06 15:48
@jpopelka

**Comment by jpopelka** [comment] 2015-05-07 11:19
@clnperez thanks. I'm still not able to reproduce it. I think I'm doing the same steps, I have libvirtd & firewalld running. The only difference is that I run Fedora22 now, but I was running F21 when I was preparing 8301dcc and I haven't seen such issue.

Not sure whether the libvirtd's "operation failed" messages can be any clue, but the firewalld's alerts about deleting non-existing rules seem to be harmless and at least we know that docker can communicate with firewalld (I had previously thought that there might be some sort of problem with establishing D-Bus connection).

**Comment by jcajka** [comment] 2015-05-11 09:07
@jpopelka @clnperez  Might be the issue I'm hitting in Fedora 23, https://bugzilla.redhat.com/show_bug.cgi?id=1219082, it seems that selinux is denying dbus access.

I'm able to work around it using:
audit2allow -a -M tdocker (should allow all denied operations, so be careful)
semodule -i tdocker.pp

**Comment by jpopelka** [comment] 2015-05-11 12:29
Yes, that's it - I had SELinux in Permissive mode. I can reproduce it in Enforcing mode.

**Comment by thaJeztah** [comment] 2015-05-11 12:57
Hm, bit confused now, so I might have added the wrong labels; is this an issue in Docker (not being tested with SELinux properly, or incorrectly configured), or an issue upstream in Fedora?

**Comment by jpopelka** [comment] 2015-05-11 13:31
I'd say it's an issue upstream in Fedora - in SELinux policy.

**Comment by thaJeztah** [comment] 2015-05-11 14:12
Bit unsure how to proceed. Technically it's a problem upstream, but we don't want everyone's setup to break after upgrading to 1.7 when it's released. If upstream doesn't fix it before 1.7, it should be documented, I think?

/cc @rhatdan @lsm5 (sorry if I'm mis-using you here, thought it would be in your interest as well)

**Comment by rhatdan** [comment] 2015-05-11 14:47
We are working on an update to the docker-selinux package to allow this.  It should be in the next docker update.

**Comment by clnperez** [comment] 2015-05-11 15:45
Thanks everyone. senenforce 0 also gets me around the hang. I'm not sure how the firewalld bits relate, though. Can anyone enlighten me there?

**Comment by thaJeztah** [comment] 2015-05-11 16:32
@rhatdan that would be the docker package as distributed by RedHat? Is there anything to do "here", i.e. Will users installing Docker via get.docker.io still run into this problem (and do we need to adjust the install script and/or documentation around this)?

Sorry if these are silly questions, I'm not a RedHat user myself, so trying to get clear what the situation is and what needs to be done.

**Comment by rhatdan** [comment] 2015-05-12 15:36
Any time we add new features to docker, SELinux has to react.  The docker-selinux package is shipped by Red Hat/Fedora to solve these issues.  The problem is the F21 version is out of date.  I have asked @lsm5 to update this.

Nothing docker can do about it currently other then run docker in permissive mode.   This is a hazard of any users downloading upstream code directly rather then using the code from the distribution.

**Comment by clnperez** [comment] 2015-05-14 16:48
I added some rules to get around this for now. Fine with me if we close it since a new upstream policy is in the works and it's not a Docker problem. Glad it wasn't a firewalld issue!

**Comment by thaJeztah** [comment] 2015-05-14 17:50
@clnperez hm, although I agree docker cannot do anything about it, closing it would make it harder for other users to find, and this may help them getting informed on the situation.

It would sure help if you are able to inform me/us when the issue is resolved so that we can actually close it.

@vbatts I saw in an (unrelated) discussion that @lsm5 is currently away, do you know if this gets picked up by someone else?

**Comment by clnperez** [comment] 2015-05-14 19:29
@thaJeztah Sure! Some teams/projects hate keeping issues open if they aren't theirs to fix (just noise to track). Good to know how this community works. Also, if someone will update this issue when the policy is available, I'll remove my workaround one and test the official solution out.

**Comment by thaJeztah** [comment] 2015-05-15 01:58
@clnperez generally, we do (close them), and perhaps we still should, but I also know not many people search the closed issues, so... if it prevents them from creating new issues... :)

**Comment by mavenugo** [comment] 2015-08-15 03:19
This issue is being handled via #15498. Closing it.

**Closed by mavenugo** 2015-08-15 03:19 UTC
Labels: kind/regression, os/linux/fedora, system/networking
