### ISSUE TITLE
Container status is out of sync with actual processes

### ISSUE THREAD

**Issue by sadovnikov** [docker/docker#19850] opened 2016-01-30 07:08 UTC
This issues is based on https://github.com/docker/docker/issues/1906#issuecomment-167095820

Container, which image is based on `ubuntu:14.04`, starts with Java process as an entry point. Based on logs from the process, it completes. However the container, according to `docker ps`, remains `Up`. Attempts to execute any commands in the running container by `docker exec` return without doing anything. Attempts to kill the container hang. 

From SSH of docker-machine VM

```
docker@minimesos:~$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

docker@minimesos:~$ docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS               NAMES
43a263b7dc87        containersol/minimesos:latest   "java -Dminimesos.hos"   16 minutes ago      Up 16 minutes                           backstabbing_brattain
docker@minimesos:~$ ps -eaf | grep lxc
docker   12769 12421  0 11:25 pts/0    00:00:00 grep lxc
```

What should I do to get some useful debug information?

```
MacBook-Pro:mesos-logstash vik$ docker --version
Docker version 1.9.1, build a34a1d5
MacBook-Pro:mesos-logstash vik$ docker-machine --version
docker-machine version 0.5.1 (7e8e38e)
```

**Comment by thaJeztah** [comment] 2016-01-30 07:22
I think this is the same issue as https://github.com/docker/docker/issues/18180, and is caused by a aufs bug in the kernel. You can either temporarily switch to a different storage driver (e.g. overlay), or tryout the new release candidate of boot2docker https://github.com/tianon/boot2docker-legacy/releases/tag/v1.10.0-rc2 or docker toolbox (which also contains the boot2docker rc) https://github.com/docker/toolbox/releases/tag/v1.10.0-rc2

**Comment by thaJeztah** [comment] 2016-01-30 07:23
Closing this issue, but feel free to comment if you think I closed this by mistake

**Closed by thaJeztah** 2016-01-30 07:22 UTC

**Comment by sadovnikov** [comment] 2016-02-01 08:55
I would never guess #18180 has the same cause ;-) However I'll give a try using https://github.com/docker/toolbox/releases/tag/v1.10.0-rc2. Thank you
