### ISSUE TITLE
docker top hangs

### ISSUE THREAD

**Issue by sandyskies** [docker/docker#30026] opened 2017-01-10 12:28 UTC
**Description**

docker top container  hangs， and this is the traceback , it seems it hangs at chan send and receive

https://raw.githubusercontent.com/sandyskies/test/master/top-traceback

```
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.13.0-rc4
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: xfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Kernel Version: 3.10.104-1-
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.659 GiB
Name: 
ID: 6CTP:WCAQ:DYIQ:WVUW:PI4T:GHFD:6ZTU:TSEM:4YQ5:EMFJ:IUXU:ZTVW
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

centos 6 with 3.10.x kernel version.

**Comment by sandyskies** [comment] 2017-01-10 12:52
@mlaventure  see if this is same as https://github.com/docker/containerd/pull/290

**Comment by mlaventure** [comment] 2017-01-10 16:59
@sandyskies 1.13 already has this fix in, and unless you used `--pid` on any of your containers it shouldn't occur anyway.

From the logs, it looks like we have a contention on the monitor lock

**Comment by mlaventure** [comment] 2017-01-10 22:45
@sandyskies If you still have the machine running or if it happens again, could you please provide me with the following:

- `cat /sys/fs/cgroup/memory/docker/<containerd-id>/memory.oom_control`
- `wc -l /sys/fs/cgroup/memory/docker/<containerd-id>/tasks`

With the stacktrace if it's a different run to confirm we're analyzing the same issue.

Thanks

**Comment by sandyskies** [comment] 2017-01-11 08:12
@mlaventure  It seems monitor has a deadlock between chan buffer full and lock , which become looks like daedlock .   Do u have a issue or pr reference to this fix?

**Comment by mlaventure** [comment] 2017-01-11 15:42
@sandyskies yes, that's correct. My question above are to trying to confirm the root cause of it so we can properly fix it.

If you could provide those answer, then I'll make the appropriate PR to fix it.

**Comment by sandyskies** [comment] 2017-01-11 16:27
I have been confuse, as u have said ： "  1.13 already has this fix in, and unless you used --pid on any of your containers it shouldn't occur anyway"  . So I don't know if this have been fixed or not.  Anyway, I will provide those info for u once it hangs again. @mlaventure

**Comment by sandyskies** [comment] 2017-01-14 13:07
@mlaventure  indeed ,it is related to oom event ,from our monitor we can find out that docker
top hangs after some contianers report a oom event .

**Comment by mlaventure** [comment] 2017-01-16 07:06
@sandyskies Have  you been able to execute the 2 commands I provided in my earlier comment? Can you share their outputs?

**Comment by sandyskies** [comment] 2017-01-16 12:59
@mlaventure  cat /cgroup/memory/docker/31ee5c98de13d710c254de915ca185676fd177ae58403d6d36fb5dbd48604254/tasks  |wc -l 
30291
cat /cgroup/memory/docker/31ee5c98de13d710c254de915ca185676fd177ae58403d6d36fb5dbd48604254/memory.oom_control 
oom_kill_disable 0
under_oom 0

**Comment by sandyskies** [comment] 2017-01-16 13:59
@mlaventure    /cgroup/memory/docker/31ee5c98de13d710c254de915ca185676fd177ae58403d6d36fb5dbd48604254/tasks |wc -l
30291
cat /cgroup/memory/docker/31ee5c98de13d710c254de915ca185676fd177ae58403d6d36fb5dbd48604254/memory.oom_control
oom_kill_disable 0
under_oom 0

**Comment by mlaventure** [comment] 2017-01-16 15:59
@sandyskies are you starting new tasks within this containers with `docker exec` or are they just created by the normal process running within the container?

**Comment by sandyskies** [comment] 2017-01-16 17:39
@mlaventure I starting new tasks with docker exec , in fact I run docker exec to run a bash script ,and the bash will run the process.

**Comment by sandyskies** [comment] 2017-01-16 17:40
Anyway , I would try to explain why I create a PR. I found it works fine for me.
This is a bug between different type of task handling , polling the memory.oom_control file can sometimes return thousands of event, hence https://github.com/docker/containerd/blob/v0.2.x/supervisor/monitor_linux.go#L130 m.ooms could be full. This is because m.m.Lock() was executed before send the oom event to m.ooms chan. In the same time https://github.com/docker/containerd/blob/v0.2.x/supervisor/supervisor.go#L380 and AddProcessTask heppened, and finally come to https://github.com/docker/containerd/blob/v0.2.x/supervisor/monitor_linux.go#L49 here , m.m.Lock(), but the lock is held by what I mentioned about. Unfortunately https://github.com/docker/containerd/blob/v0.2.x/supervisor/supervisor.go#L282 there is only one routine can hanle tasks. So chan was full and lock was unable to accquire ,deadlock it 's.

**Comment by mlaventure** [comment] 2017-01-16 17:44
@sandyskies I pasted a diff for a possible fix to the issue on your PR.

The way you try to fix it doesn't make sense with the current design of the code.

**Comment by sandyskies** [comment] 2017-01-16 17:46
@mlaventure  Maybe we should create another mutex in supervisor for the task handling.

**Comment by mlaventure** [comment] 2017-01-16 17:48
@sandyskies the channel acts as a natural mutex. 

Please try the diff that I posted on your PR (https://github.com/docker/containerd/pull/433#issuecomment-272923000). It should fix the issue.

Today is a public holiday here, so I'll probably be off for the rest of the day, but that change should fix your issue.

Also, it is generally not recommended to run several long running processes within a container via `docker exec`.

**Comment by sandyskies** [comment] 2017-01-16 17:54
@mlaventure  I will test you fixed-code ,and  if it works fine, should I create another pr later or u will create it ?

**Comment by mlaventure** [comment] 2017-01-16 18:05
Thanks for testing, I'll create it later. I'm trying to think of a nice way
of fixing this 😀

**Comment by sandyskies** [comment] 2017-01-16 18:11
Ok it 's midnight in China. I will test it in the morning and will inform u the result.  Keep following up ur nice way .@mlaventure

**Comment by thaJeztah** [comment] 2017-01-18 00:44
opened https://github.com/docker/docker/pull/30226 to bump containerd version

**Comment by sandyskies** [comment] 2017-01-22 02:40
time="2017-01-22T10:38:13.520879232+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:13.520891399+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:13.520901035+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:13.520910686+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:13.520919922+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.548875214+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.548932706+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.548948733+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.548966296+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.548981012+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.548993217+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549005865+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549023268+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549035261+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549048994+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549061742+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549074111+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549086443+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549098782+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549114846+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549127625+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549140183+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549152211+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549164398+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549178996+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549191813+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549207213+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 
time="2017-01-22T10:38:28.549219629+08:00" level=warning msg="containerd: event not sent to subscriber" event=oom 

 grep "event=oom" demon.log  |wc -l 
487088
------------------------------------------------------------------------------------------------------------
@mlaventure  I think , the root cause is why a single oom can report so much event .

**Comment by vieux** [comment] 2017-02-01 01:57
closed by https://github.com/docker/docker/pull/30610

**Closed by vieux** 2017-02-01 01:57 UTC
Labels: version/1.13
