### ISSUE TITLE
Incorrect docker-proxy behavior

### ISSUE THREAD

**Issue by michalmedvecky** [docker/docker#16029] opened 2015-09-02 21:19 UTC
Hello,

I have following config:

coreos machine with IP 10.240.135.37 with access to internet

container with my internal recursive dns service residing at 10.1.0.189/28, but with -p 53:53/udp published to 10.240.135.37 (so it can be used by external hosts)
container with my app at 10.1.0.188/28
docker0 interface at 10.1.0.177/28

When I send DNS query from my app container (10.1.0.188) to the recursive dns service (10.240.135.37) and it does not have the response cached, it contacts upstream DNS server at 169.254.169.254, but the response comes to myapp container with incorrect source address - 10.1.0.177 instead of 10.240.135.37. 

Tcpdump output:

21:00:54.788937 IP *10.1.0.188.37530* > 10.240.135.37.domain: 1142+ A? www.sme.sk. (28)
21:00:54.789097 IP 10.1.0.177.52152 > 10.1.0.189.domain: 1142+ A? www.sme.sk. (28)
21:00:54.789801 IP 10.1.0.189.48871 > 169.254.169.254.domain: 1142+ A? www.sme.sk. (28)
21:00:54.908371 IP 169.254.169.254.domain > 10.1.0.189.48871: 1142 6/0/0 CNAME www.sme.sk.cdn.cloudflare.net., A 162.159.254.47, A 162.159.254.46, A 162.159.255.46, A 162.159.252.47, A 162.159.253.47 (151)
21:00:54.908764 IP 10.1.0.189.domain > 10.1.0.177.52152: 1142 6/0/0 CNAME www.sme.sk.cdn.cloudflare.net., A 162.159.254.47, A 162.159.254.46, A 162.159.255.46, A 162.159.252.47, A 162.159.253.47 (151)
21:00:54.908874 IP *10.1.0.177.domain* > 10.1.0.188.37530: 1142 6/0/0 CNAME www.sme.sk.cdn.cloudflare.net., A 162.159.254.47, A 162.159.254.46, A 162.159.255.46, A 162.159.252.47, A 162.159.253.47 (151)

I believe the final response should come with source IP 10.240.135.37.

# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2-dirty
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/amd64

# docker info
Containers: 6
Images: 57
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.5
Operating System: CoreOS 723.3.0
CPUs: 2
Total Memory: 7.31 GiB
Name: core-001.c.lofty-outcome-860.internal
ID: 5CGT:ONVF:DO6T:PVH6:KOSJ:BV53:W4ZR:AJVA:V4Y2:474M:FIQR:JZGV

# uname -a
Linux core-001.omited.internal 4.0.5 #2 SMP Fri Jul 10 01:01:50 UTC 2015 x86_64 Intel(R) Xeon(R) CPU @ 2.50GHz GenuineIntel GNU/Linux

**Comment by cpuguy83** [comment] 2015-09-12 03:24
Closing since this would be expected behavior since it's going through a proxy.
Docker 1.8 allows you to disable the proxy, docker 1.9 will have it disabled by default and instead use hairpin nat.

Thanks for the report!

**Closed by cpuguy83** 2015-09-12 03:24 UTC
Labels: group/networking
