### ISSUE TITLE
Orphaned and unstoppable (superhuman strength?) containers with --pid=host

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#11087] opened 2015-02-28 17:19 UTC
I've ran into an issue that is easily reproducible that puts a container into a state that can not be stopped and if you restart the Docker daemon it will also loose track of the existing container and spawn a new one.

The issue happens when you are running with `--pid=host` and you do a SIGKILL but that process has children that don't terminate when its parent dies.  Docker never seems to see that the SIGKILL worked and will hang forever.  The SIGKILL worked, but the container PID is gone.  Now you do a `docker stop` or any action and Docker will complain that it can't find the process.

Now if you restart the Docker daemon, Docker thinks the container is gone (I assume because the PID is gone) and then it will start a new one but the old container cgroup still exists.

I haven't dug yet into the Docker code to see what is happening (I assume Docker thinks the SIGKILL isn't done because processes in the cgroup still exist), but here is a simple way to reproduce this issue.

```bash
#!/bin/bash

ID=$(docker run -d --pid=host ubuntu bash -c "sleep 300; echo hi")

docker kill $ID &
sleep 1
docker stop $ID
```

Running the above will result in

```
Error response from daemon: Cannot stop container 8af7796dff4df03686342f3a7b618fe5f1830ab89c0c158817acb332cac3e9f8: no such process
FATA[0000] Error: failed to stop one or more containers 
```

Seems like there are two things that should be addressed.

1. Make SIGKILL work properly in this situation
2. On restart check the cgroup for processes and freeze/kill those

Obligatory docker info/version

```
$ docker version; docker info
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
Containers: 51
Images: 366
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.18.1-031801-generic
Operating System: Ubuntu 14.10
CPUs: 4
Total Memory: 7.496 GiB
Name: inotmac
ID: FPSO:Z7SO:BZJ3:IXH4:DNKV:UPZQ:KLP2:IRXW:5CBY:PBDM:HAKO:UOC7
Username: ibuildthecloud
Registry: [https://index.docker.io/v1/]
```

**Comment by ibuildthecloud** [comment] 2015-02-28 17:58
Started reading through the code but I think I need to enlist the real experts.  ping @crosbymichael @rhatdan

**Comment by rhatdan** [comment] 2015-03-02 14:09
The code is supposed to notice that PID 1 died and then kill all of the processes within the CGroup.  I have been hearing from Steve Dake about similar problems in 1.5 that he says were not there in our version of 1.4.1, but I have not found the problem.

**Comment by ibuildthecloud** [comment] 2015-03-02 19:08
@rhatdan My assumption (again, haven't understood the code fully) is that this isn't so much of a libcontainer issue (as I saw your tests for freeze/kill) but instead a conflict between docker and libcontainer.  It seems to be that when PID 1 dies whatever callback that exists to tell docker that the container is dead, is not getting invoked.  Again my assumption (I'm making an ass of myself) is that it's because the cgroup doesn't die and the container still has live processes, where in the non-pid host namespace situation when PID 1 is dead, Linux will naturally kill all the processes.

If I have some time today or tomorrow I'll dig more into this.

**Comment by LK4D4** [comment] 2015-03-02 19:50
We had similar issue. It was because of not closed streams and `cmd.Wait` just hanged forever, we can test this with simple logging around. Also there was issue with cgroups not properly removed.
Actually all processes in cgroup should be killed if main process was killed :/ But seems there is some bug about it.

**Comment by LK4D4** [comment] 2015-03-02 19:52
docker/libcontainer#349 for reference

**Comment by ibuildthecloud** [comment] 2015-03-02 19:57
@LK4D4 are you saying if the child is using the parents FDs, wait won't exit?

**Comment by LK4D4** [comment] 2015-03-02 19:59
@ibuildthecloud Yes, if it not dies with parent. And also if you try just `cat` in `exec.Cmd` for example it won't exit too, but `cat` will become a zombie.

**Comment by rhatdan** [comment] 2015-03-02 20:00
@sdake here is the reference to the problem you are seeing.  I have no idea why the Wait4 call was removed?  @crosbymichael ???

**Comment by ibuildthecloud** [comment] 2015-03-02 20:00
Cool.  This fails.

    docker run -d --pid=host ubuntu bash -c "sleep 300; echo hi"

This good.

    docker run -d --pid=host ubuntu bash -c "sleep 300 >/dev/null 2>&1; echo hi"

**Comment by LK4D4** [comment] 2015-03-02 20:03
@rhatdan Wait a minute. In docker used old verson of libcontainer, where `os.Process.Wait` used which is just wrapper for `Wait4`. In new version we still not figured out what we should do.
Also @sdake confirmed that patch fixed his problem.
docker/libcontainer#396 for reference

**Comment by rhatdan** [comment] 2015-03-02 20:12
Right but now it is breaking in docker-1.5.

**Comment by LK4D4** [comment] 2015-03-02 20:17
weird :/ It was merged only in docker-1.5

**Comment by rhatdan** [comment] 2015-03-02 20:17
Ok, I game him a version with docker-1.4.1 in devel branch.  Which worked and now he says it is broken. in 1.5

**Comment by rhatdan** [comment] 2015-03-02 20:18
I don't see anything that is different.

**Comment by LK4D4** [comment] 2015-03-02 20:23
@sdake @rhatdan I rechecked example from #10303 and it works for me (maybe lines in your script changed). Can you provide non-working command and I'll try to debug issue.

**Comment by LK4D4** [comment] 2015-03-02 20:24
Actually I have command from @ibuildthecloud :)

**Comment by sdake** [comment] 2015-03-02 21:15
@lk4d4 I'm on the road ATM and don't have good access to my system.  I'll post an update on Thursday when I'm back in the office.  Thanks for being responsive - I'll find the example I am using that is broken.  Note I am using fedora 21's docker 1.5 version which may or may not have the fix.  I can't get master to compile - it fails and I'm not sure how to fix it.

**Comment by jfrazelle** [comment] 2015-03-23 19:56
So was this fixed by something else or does it still exist

**Comment by sdake** [comment] 2015-03-23 21:27
I can confirm this works in docker master, but does not work in fedora 21 docker 1.5.

**Comment by LK4D4** [comment] 2015-03-23 21:28
@sdake That's superweird, but I'm glad that it works in master :D

**Comment by rhatdan** [comment] 2015-03-24 12:53
Steven, we are about to start pushing a docker-1.6 pre release into Fedora 22.  Could you check there when it gets released.

**Comment by sdake** [comment] 2015-03-24 14:15
@rhatdan sure when I get to a good stopping point I'll ugprade my dev environments to fedora 22 and test docker-1.6 pre.  Just ping me on irc when its pushed.  Also feel free to call me steve :)

Regards
-steve

**Comment by rhatdan** [comment] 2015-03-24 15:04
:^)

**Comment by LK4D4** [comment] 2015-03-31 16:30
This is still an issue in master.

**Comment by jfrazelle** [comment] 2015-03-31 18:22
so the weird thing about this is, each of the windows remote hosts build docker in docker for the remote daemon and run in a container with `--pid host` and I have never seen this, we are spinning them up and tearing them down for every PR

**Comment by jfrazelle** [comment] 2015-03-31 18:22
so maybe its only certain ones, or something else is at play here

**Comment by ibuildthecloud** [comment] 2015-04-02 01:01
@jfrazelle the issue only happens when the children process are holding open fd's from PID 1.  I doubt that is the case in dind.

**Comment by jfrazelle** [comment] 2015-04-02 01:03
ahhh i see

**Comment by ibuildthecloud** [comment] 2015-04-10 15:17
@LK4D4 @jfrazelle I'm not trying to annoy, but just curious.  Is this issue being actively worked on?  Is there anything I can do to help?  Is there some blocker that was encountered when investigating this?

**Comment by rhatdan** [comment] 2015-04-10 15:32
@ibuildthecloud Not sure anyone is actively investigating.

**Comment by LK4D4** [comment] 2015-04-10 15:41
@ibuildthecloud Sorry, I'll fix it soon.

**Comment by LK4D4** [comment] 2015-04-10 15:42
Have no idea how we missed it for milestone.

**Closed** 2015-04-13 18:50 UTC
Labels: exp/expert, kind/bug, kind/regression
