### ISSUE TITLE
Expose a range of ports in docker service

### ISSUE THREAD

**Issue by rsabir** [docker/docker#30560] opened 2017-01-30 15:36 UTC
Is there any way to expose a range of ports in the creation of a swarm service ( for instance: -p `1024-2000:1024-2000`)? I know that it's possible for a container, but is it also possible for a Swarm Service? If yes, I can't find how to do that in the documentation.

I need this functionality for exposing a service that contains vsftpd.

**Comment by gianarb** [comment] 2017-01-30 18:42
Hello @rsabir yes I tried now and it's working. You can do that. The real problem is that with big range your service will require a lot of time to start up. If it's fit good with your use case no problem.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other types of questions, consider using one of:

* https://forums.docker.com
* the docker community slack channel (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
* StackOverflow

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by gianarb** 2017-01-30 18:42 UTC
Labels: area/swarm, kind/question

**Comment by rsabir** [comment] 2017-01-31 09:01
Thank you @gianarb for your response but can you tell me which version did you use to do that? My version of docker is **1.12.3**. Also, can you please specify the _command_ that you run to do that?

**Comment by gianarb** [comment] 2017-01-31 09:29
Sure, I am using docker 1.13 and I did
```
docker service create -p 100-120:100-120 alpine sleep 10
```
I tried yesterday but know I have not access to my cluster and I can not retry.. but That was the command

**Comment by rsabir** [comment] 2017-01-31 10:00
ok, so I have to upgrade to 1.13.

**Comment by port22** [comment] 2017-09-07 10:21
although I do `service create -p 65000-65100:65000-65100` docker is not publishing the ports, just exposing .. ?!

**Comment by thaJeztah** [comment] 2017-09-16 00:58
@port22 when publishing ports for a _service_. the ports for the containers backing the service are not published directly, but through the ingress network, so when running `docker ps` the published ports aren't shown, but if you run `docker service ls`, you'll see which ports are published;

```bash
docker ps

CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                    NAMES
f29fea6df5d3        nginx:alpine        "nginx -g 'daemon ..."   About a minute ago   Up About a minute   80/tcp                   foo.1.uykxp4raxtocikirin7d9p419
```

docker service ps

ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
nj2wppuneknc        foo                 replicated          1/1                 nginx:alpine        *:85->85/tcp,*:80->80/tcp,*:81->81/tcp,*:84->84/tcp,*:86->86/tcp,*:87->87/tcp,*:88->88/tcp,*:89->89/tcp,*:90->90/tcp,*:82->82/tcp,*:83->83/tcp
```

**Comment by port22** [comment] 2017-09-18 06:25
Thanks, ok but that leads to the problem that these ports are not reachable on the host ip.
So, when `-p 65000-65100:65000-65100` does not work that way for a service like it works with docker run,  how do I host-publish a port rage in swarm like `--publish mode=host,target=65000-65100,published=65000-65100` ?

**Comment by BaliStarDUT** [comment] 2018-06-26 03:39
- I need this feature.but I don't find this config on docker API:
![image](https://user-images.githubusercontent.com/8566219/41887884-4c6eb024-7935-11e8-8e19-13545e3199b3.png)
- And if the random port conflicts with swarm port 2357 and 7946，this may cause a big problem.

**Comment by thaJeztah** [comment] 2018-06-26 05:43
> don't find this config on docker API

At the API level, each port in the range is a separate port publish.

> And if the random port conflicts with swarm port 2357 and 7946，this may cause a big problem.

Random ports are selected from the ephemeral port range (32xxx), so won't overlap

**Comment by juangps96** [comment] 2019-02-05 21:30
Any Solution to this question, about Random ports?
We need to create a service with replicas in a range of ports (8081 - 8084) for example, --publish mode=host,target=80  but  we need to define a range like:  --replicas 4 --publish mode=host,target=80,publish=8081,8082,8083,8084
