### ISSUE TITLE
Convert commands to spf13/cobra

### ISSUE THREAD

**Issue by dnephin** [docker/docker#23211] opened 2016-06-02 17:36 UTC
This is a checklist for tracking which commands are being worked on or are complete:

* [x] attach - #23274 @WeiZhang555 
* [x] build - https://github.com/docker/docker/pull/23343 @vdemeester
* [x] commit - https://github.com/docker/docker/pull/23309 @yongtang
* [x] cp - https://github.com/docker/docker/pull/23348 @vdemeester
* [x] create - #23159 / https://github.com/docker/docker/issues/23253 @dnephin 
* [x] diff- https://github.com/docker/docker/pull/23283 @yongtang
* [x] events - https://github.com/docker/docker/pull/23334 @WeiZhang555 
* [x] exec #23759 @AkihiroSuda  
* [x] export - #23267 
* [x] history - https://github.com/docker/docker/pull/23291 @yongtang
* [x] images - https://github.com/docker/docker/pull/23292 @yongtang
* [x] import - #23269 @vdemeester
* [x] info #23399 @tkopczynski
* [x] inspect #23902 @dnephin
* [x] kill - https://github.com/docker/docker/issues/23297 @WeiZhang555 
* [x] load - #23412 @vdemeester 
* [x] login - #23265
* [x] logout - #23265
* [x] logs - https://github.com/docker/docker/pull/23284 @yongtang 
* [x] network - #23210
* [x] pause - https://github.com/docker/docker/pull/23285 @yongtang
* [x] port - https://github.com/docker/docker/issues/23286 @yongtang
* [x] ps - https://github.com/docker/docker/pull/23373 @capkurmagati
* [x] pull #23256
* [x] push #23256
* [x] rename - https://github.com/docker/docker/pull/23290 @yongtang
* [x] restart - https://github.com/docker/docker/issues/23307 @WeiZhang555 
* [x] rm - https://github.com/docker/docker/pull/23311 @WeiZhang555 
* [x] rmi - #23242
* [x] run - #23159
* [x] save - #23412 @vdemeester
* [x] search - #23241
* [x] start - #23268
* [x] stats - https://github.com/docker/docker/pull/23334 @WeiZhang555 
* [x] stop - #23276 @yongtang 
* [x] tag - #23278 @yongtang 
* [x] top - https://github.com/docker/docker/pull/23306 @yongtang
* [x] unpause - #23279 @yongtang
* [x] update - https://github.com/docker/docker/pull/23281  @yongtang
* [x] version - https://github.com/docker/docker/pull/23333 @yongtang
* [x] volume - #22769
* [x] wait - https://github.com/docker/docker/pull/23287 @yongtang
* [ ] daemon / dockerd #25354 @dnephin

**Comment by WeiZhang555** [comment] 2016-06-05 15:31
Oh, so we have a list! Thank you @vdemeester for directing me here :sunglasses:

**Comment by yongtang** [comment] 2016-06-05 15:34
@dnephin @vdemeester Would you mind if I work on several of the items as well?

I think I can start with simple ones like `stop` and `tag`, and will try to help more if I can get them done earlier.

**Comment by vdemeester** [comment] 2016-06-05 15:43
@yongtang yay :tada: noted :wink:

**Comment by yongtang** [comment] 2016-06-05 18:15
Thanks @vdemeester. Pull request for both `tag` and `stop` have been created.

Next I think I can pick up `unpause` and `update` if no one is working on them yet.

**Comment by yongtang** [comment] 2016-06-05 21:42
Thanks @vdemeester again. The pull request for both `unpause` and `update` have been submitted.

I think I can pick up `diff`, `logs`, `pause` and `port` next if not one is working on those yet.

**Comment by yongtang** [comment] 2016-06-06 04:05
@vdemeester I added three more `rename`, `history` and `images`. Here is the list of related pull request:
#23283 diff
#23284 logs
#23285 pause
#23286 port
#23287 wait
#23290 rename
#23291 history
#23292 images
Please let me know if there are any issues.

**Comment by capkurmagati** [comment] 2016-06-06 09:36
@WeiZhang555 @vdemeester 
Do you mind if I also work on this issue.
I can start with the `ps` command.

**Comment by vdemeester** [comment] 2016-06-06 09:47
@capkurmagati cool, go ahead :wink:

**Comment by yongtang** [comment] 2016-06-06 13:41
Added one more command `top`:
#23306 top

**Comment by tkopczynski** [comment] 2016-06-06 15:28
@vdemeester I could take on simple info command if that's ok?

**Comment by thaJeztah** [comment] 2016-06-06 15:30
@tkopczynski I'll put your name behind it, thanks!

**Comment by WeiZhang555** [comment] 2016-06-06 15:50
I'll take one more - `stats`, and leave others to whom interested in this too. :smile:

**Comment by yongtang** [comment] 2016-06-07 02:20
Create another PR #23333 for version.

**Comment by pdalpra** [comment] 2016-06-07 06:37
I'd like to help on this one and  take `exec` and/or `inspect` if you don't mind :)

**Comment by vdemeester** [comment] 2016-06-07 08:30
That is awesome ! It's gonna be migrated really quick and will let use have more time to make sure there is no regression 😇. Thanks u all so much 😇

**Comment by pdalpra** [comment] 2016-06-17 18:38
really sorry, but I won't get enough free time to migrate `exec` and `inspect` in time for 1.12...

**Comment by vdemeester** [comment] 2016-06-17 18:47
@pdalpra no worries :wink:

**Comment by tkopczynski** [comment] 2016-06-17 18:48
@pdalpra I can do it tomorrow if you don't mind

**Comment by vdemeester** [comment] 2016-06-17 18:55
@tkopczynski we're probably gonna wait until the 1.12 release to review cobra switch PRs (to limit rebased on possible regression) so there is plenty of time for the ones that are still not migrated :wink:

**Comment by tkopczynski** [comment] 2016-06-17 19:25
Ok, so I'm leaving this for @pdalpra :)

**Comment by AkihiroSuda** [comment] 2016-06-20 10:58
@pdalpra @tkopczynski @vdemeester migrated exec https://github.com/docker/docker/pull/23759

**Comment by dnephin** [comment] 2016-06-23 15:00
@pdalpra I'm going to pickup inspect right now

**Comment by thaJeztah** [comment] 2016-07-18 22:02
Looks like we still need to do `docker daemon` / `dockerd` (couldn't find a PR for that). I also "unchecked" PR's that aren't merged yet

**Comment by dnephin** [comment] 2016-07-18 22:10
I have a branch all ready for that! I'm just waiting for the other commands to merge before opening the PR:

https://github.com/docker/docker/compare/master...dnephin:remove-mflag-from-dockerd

**Comment by thaJeztah** [comment] 2016-07-18 22:21
@dnephin oh, thanks! I thought we overlooked it, I'll put your name behind it

**Closed** 2016-08-25 21:19 UTC
Labels: area/cli

**Comment by charrywanganthony** [comment] 2017-09-28 05:59
Excuse me, I‘m a newbee. Can anyone tell me where are these printers in the latest branch? I can't even find `fmt.Fprintf(w, "NAME\tDESCRIPTION\tSTARS\tOFFICIAL\tAUTOMATED\n")` (from `docker search`)or sth like this by `grep` command under moby folder.

**Comment by thaJeztah** [comment] 2017-09-28 06:15
CLI code moved to https://github.com/docker/cli
