### ISSUE TITLE
[1.7.0-rc3] docker stop and start, container has different IP address

### ISSUE THREAD

**Issue by huikang** [docker/docker#13932] opened 2015-06-14 18:03 UTC
Hi,
According to the libnetwork design, a container's endpoint should be re-used after stop and restart. Specifically, the doc says " endpoint.Leave() can be invoked when a container is stopped.. But LibNetwork keeps hold of the IP addresses as long as the endpoint is still present and will be reused when the container(or any container) joins again."

However, using the 1.7.0-rc3 release, after stop and start (or use the restart command), the IP address of a container will change. Is this a bug or the current docker engine delete the endpoint on each stop intentionally? Thanks.

Hui

**Comment by huikang** [comment] 2015-06-14 18:16
@mavenugo do you think this is a bug? Thanks.

**Comment by mavenugo** [comment] 2015-06-14 21:15
@huikang this is not a bug. The design goal of libnetwork is as you stated. But we wanted to keep the Docker behavior as close as possible with 1.6 and hence we retained the functionality. But, with the upcoming functionality as described in #13441, this behavior will change. But that is not targeted for 1.7.

I think we should close this issue. @mrjana, pls share your inputs.

**Comment by huikang** [comment] 2015-06-14 21:31
cool. I will read that long PR. Thanks.                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Madhu VenugopalSent: Sunday, June 14, 2015 5:16 PMTo: docker/dockerReply To: docker/dockerCc: huikangSubject: Re: [docker] [1.7.0-rc3] docker stop and start, container has different IP address (#13932)@huikang this is not a bug. The design goal of libnetwork is as you stated. But we wanted to keep the Docker behavior as close as possible with 1.6 and hence we retained the functionality. But, with the upcoming functionality as described in #13441, this behavior will change. But that is not targeted for 1.7.

I think we should close this issue. @mrjana, pls share your inputs.

—Reply to this email directly or view it on GitHub.

**Comment by cpuguy83** [comment] 2015-06-14 22:48
Closing since this is a non-issue.

**Closed by cpuguy83** 2015-06-14 22:48 UTC
