### ISSUE TITLE
Proposal: expand ENV value when i build image

### ISSUE THREAD

**Issue by krystism** [docker/docker#10172] opened 2015-01-19 03:22 UTC
Assume I have those two instructions in my Dockerfile ,
```
ENV VERSION 1.4.1
RUN curl -sSL https://something-${VERSION}.tar.gz | ...
```
When i build it in my local host, the process of work will be showed in stdout, like 
```
Step xx : RUN curl -sSL https://something-${VERSION}.tar.gz | ...
```
As we can see from the output, the ENV  *VERSION* won't  be expanded, I think it may be better to expand the value of ENV for tracking some problems. So, I'd like to output like this:
```
Step xx: RUN curl -sSL https://some-1.4.1.tar.gz | ...
```
If I make a mistake, like spelling mistake,should output blank string or warn me i ref a undefined ENV. 
```
ENV VERSION 1.4.1
RUN curl -sSL https://something-${VRESION}.tar.gz | ...
```
Should output
```
Step xx: RUN curl -sSL https://something-.tar.gz | ...
```
So I can easily find my error above!
I know it's not a easy work, because when docker interpreter read a Dockerfile instruction, it can not get  the env in the container interval,but it can easily record the ENV defined in the Dockerfile.

**Comment by phemmer** [comment] 2015-01-19 06:58
I'm assuming you're just asking about the build output that is shown on your console, as the build does actually substitute the variable.
If this is indeed the case, what you're asking isn't possible. The primary reason is that `${VERSION}` is shell syntax. Docker is simply passing the text `curl -sSL https://something-${VERSION}.tar.gz | ...`, to `/bin/sh`, and letting the shell interpret it. Docker has no clue that the text `${VERSION}` will be substituted with the value of the environment variable `VERSION`.

**Comment by krystism** [comment] 2015-01-19 07:19
@phemmer  I know Docker cann't not get any value from the container, I just want to expand the ENV defined in my Dockerfile, it may be excess feature, but sometimes useful for us to debug.In fact, sometimes, I  insert  'set -x' to track it.

**Comment by thaJeztah** [comment] 2015-01-19 07:31
@krystism the issue is that docker just send that line to*a* shell, and that shell happens to do something if it sees `${FOO}`. Docker itself makes no assumptions here, and doesn't parse that instruction.

**Comment by duglin** [comment] 2015-02-12 13:44
@phemmer I think I understand what you're saying... for the envs that Docker knows about, go ahead and do the substitutions prior to sending it to the shell.  While this may be possible, I think it might actually lead to more confusion than help people.  As an end user (newbie) I would find it really confusing to look have a Dockerfile with:
```RUN echo $FOO $BAR```
and then see:
```Step 2 : RUN echo $FOO hello```
in the output.  Having Docker only do a partial substitution could look like an error and make people wonder why it didn't do the others.
I think its better to not do 1/2 the job and simply let the shell do it all.

Gonna close this one for now - if you feel there may be a better solution you can re-open.

**Closed by duglin** 2015-02-12 13:44 UTC

**Comment by phemmer** [comment] 2015-02-12 14:24
@duglin Eh? I'm opposed to doing this substitution. Did you mistake me for the author?

**Comment by duglin** [comment] 2015-02-12 14:25
Oops  :-)  yup - fixed comment to point to the right person. Sorry.
