### ISSUE TITLE
Panic while updating node key

### ISSUE THREAD

**Issue by evanp** [docker/docker#26692] opened 2016-09-19 02:57 UTC
**Description**

Node in swarm crashes and does not automatically restart.

**Steps to reproduce the issue:**
1. Add a node to a swarm
2. Wait ~24 hours

**Describe the results you received:**

The docker daemon goes down and stays down. "panic" referenced in syslog for docker, with an index error, somewhere involved with updating keys.

[dockerfail.txt](https://github.com/docker/docker/files/479181/dockerfail.txt)

**Describe the results you expected:**

Docker daemon stays up (yay) or restarts on a panic.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: aeucpb3v91ixseupjqa78gtm3
 Is Manager: false
 Node Address: 10.134.17.87
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: db3
ID: XXD3:BFVR:UO4W:6KYQ:O7JQ:5ELC:USIV:NLI3:XDJB:JNM3:2CXA:TVZX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: evanp
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Digital Ocean, Ubuntu 16.04.1.

**Comment by evanp** [comment] 2016-09-19 02:59
In the attached log file, it's worth noting that there appears to have been a failure earlier in the day, related to node key indices.

**Comment by aboch** [comment] 2016-09-19 04:10
Thanks for the report.
This is a duplicate of #25608

**Comment by thaJeztah** [comment] 2016-09-19 09:00
Let me close this as duplicate of https://github.com/docker/docker/issues/25608. Thanks for reporting @evanp!

**Closed by thaJeztah** 2016-09-19 09:00 UTC
Labels: version/1.12
