### ISSUE TITLE
docker 1.10 embedded DNS doesn't work as documented

### ISSUE THREAD

**Issue by edwintorok** [docker/docker#20026] opened 2016-02-05 13:54 UTC
Description of problem:

I installed Docker engine 1.10 from the repository in a CentOS 7 VM, and followed the steps here: https://docs.docker.com/engine/userguide/networking/work-with-networks/

However this step doesn't work: `/ # ping -w 4 container3`, in fact name resolution doesn't work at all with user defined networks, and I get some iptables errors from docker when creating the user-defined network.

What am I doing wrong?

`docker version`:
```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 13
 Running: 4
 Paused: 0
 Stopped: 9
Images: 8
Server Version: 1.10.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-18908918-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/vg-docker/data
 Metadata file: /dev/vg-docker/metadata
 Data Space Used: 625.3 MB
 Data Space Total: 10.74 GB
 Data Space Available: 10.11 GB
 Metadata Space Used: 1.282 MB
 Metadata Space Total: 1.074 GB
 Metadata Space Available: 1.072 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 7
Total Memory: 7.639 GiB
Name: localhost.localdomain
ID: PVJM:C6JB:LAFE:PURU:4HQI:23E6:DS22:7J2O:3XT3:VTZJ:A33N:NYZC
Debug mode (server): true
 File Descriptors: 54
 Goroutines: 85
 System Time: 2016-02-05T15:49:00.057923818+02:00
 EventsListeners: 0
 Init SHA1: 6ad5ded80380758740d165409e0c26db46e05a9f
 Init Path: /usr/libexec/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
x86_64 x86_64 GNU/Linux
[root@localhost ~]# getenforce
Enforcing
```

Environment details:
Virtual:
```
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 
```

How reproducible: always

Steps to Reproduce:
1.  docker run -itd --name=container1 busybox
2. docker run -itd --name=container2 busybox
3. docker network create -d bridge --subnet 172.25.0.0/16 isolated_nw
4. docker run --net=isolated_nw --ip=172.25.3.3 -itd --name=container3 busybox
5.  docker attach container2
6. ping -w 4 container3
7. ping -w 4 google.com

Actual Results:
```
ping: bad address 'container3'
ping: bad address 'google.com'
```

Expected Results:
Able to ping container3 and google

Additional info:
The DNS server is reachable from inside the container with ping, it just doesn't seem to answer DNS requests properly:
```
/ # cat /etc/resolv.conf 
nameserver 127.0.0.11
options ndots:0
/ # ping -w 4 127.0.0.11
PING 127.0.0.11 (127.0.0.11): 56 data bytes
64 bytes from 127.0.0.11: seq=0 ttl=64 time=0.141 ms
64 bytes from 127.0.0.11: seq=1 ttl=64 time=0.066 ms
64 bytes from 127.0.0.11: seq=2 ttl=64 time=0.127 ms
64 bytes from 127.0.0.11: seq=3 ttl=64 time=0.059 ms

--- 127.0.0.11 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.059/0.098/0.141 ms
```

I enabled -D and I get some iptables errors from docker in the journal:
```
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.739603897+02:00" level=debug msg="Calling POST /v1.22/networks/create"
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.739656325+02:00" level=debug msg="POST /v1.22/networks/create"
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.739757830+02:00" level=debug msg="form data: {\"CheckDuplicate\":true,\"Driver\":\"bridge\",\"IPAM\":{\"Config\":[{\"Subnet\":\"172.25.0.0/16\"}],\"Driver\":\"default\",\"Options\":{}},\"Internal\":false,\"Name\":\"isolated_nw\",\"Options\":{}}"
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.740009686+02:00" level=debug msg="Allocating IPv4 pools for network isolated_nw (b0f784c11c0d2301b7d0f1bc5dd9f4500b823425e61687fd7c21dd9319fb5146)"
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.740035294+02:00" level=debug msg="RequestPool(LocalDefault, 172.25.0.0/16, , map[], false)"
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.772306044+02:00" level=debug msg="RequestAddress(LocalDefault/172.25.0.0/16, <nil>, map[RequestAddressType:com.docker.network.gateway])"
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.787453719+02:00" level=debug msg="Setting bridge mac address to 02:42:32:28:d2:1b"
Feb 05 15:45:49 localhost.localdomain NetworkManager[793]: <info>  (br-b0f784c11c0d): new Bridge device (carrier: OFF, driver: 'bridge', ifindex: 152)
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.787602151+02:00" level=debug msg="Assigning address to bridge interface br-b0f784c11c0d: 172.25.0.1/16"
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.787968759+02:00" level=debug msg="Firewalld passthrough: ipv4, [-t nat -C POSTROUTING -s 172.25.0.0/16 ! -o br-b0f784c11c0d -j MASQUERADE]"
Feb 05 15:45:49 localhost.localdomain firewalld[711]: 2016-02-05 15:45:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -C POSTROUTING -s 172.25.0.0/16 ! -o br-b0f784c11c0d -j MASQUERADE' failed: iptables: No chain/target/match by that name.
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.803047278+02:00" level=debug msg="Firewalld passthrough: ipv4, [-t nat -I POSTROUTING -s 172.25.0.0/16 ! -o br-b0f784c11c0d -j MASQUERADE]"
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.813140080+02:00" level=debug msg="Firewalld passthrough: ipv4, [-t nat -C DOCKER -i br-b0f784c11c0d -j RETURN]"
Feb 05 15:45:49 localhost.localdomain firewalld[711]: 2016-02-05 15:45:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -C DOCKER -i br-b0f784c11c0d -j RETURN' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.826083377+02:00" level=debug msg="Firewalld passthrough: ipv4, [-t nat -I DOCKER -i br-b0f784c11c0d -j RETURN]"
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.835311082+02:00" level=debug msg="Firewalld passthrough: ipv4, [-D FORWARD -i br-b0f784c11c0d -o br-b0f784c11c0d -j DROP]"
Feb 05 15:45:49 localhost.localdomain firewalld[711]: 2016-02-05 15:45:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D FORWARD -i br-b0f784c11c0d -o br-b0f784c11c0d -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.844823744+02:00" level=debug msg="Firewalld passthrough: ipv4, [-t filter -C FORWARD -i br-b0f784c11c0d -o br-b0f784c11c0d -j ACCEPT]"
Feb 05 15:45:49 localhost.localdomain firewalld[711]: 2016-02-05 15:45:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -C FORWARD -i br-b0f784c11c0d -o br-b0f784c11c0d -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.856573443+02:00" level=debug msg="Firewalld passthrough: ipv4, [-I FORWARD -i br-b0f784c11c0d -o br-b0f784c11c0d -j ACCEPT]"
Feb 05 15:45:49 localhost.localdomain docker[4175]: time="2016-02-05T15:45:49.865931993+02:00" level=debug msg="Firewalld passthrough: ipv4, [-t filter -C FORWARD -i br-b0f784c11c0d ! -o br-b0f784c11c0d -j ACCEPT]"
```

**Comment by cpuguy83** [comment] 2016-02-05 14:40
container1 and container2 are on the default bridge network, docker does not handle DNS on this and only uses the resolvers either defined by `--dns` or from /etc/resolve.conf on the host.

Because container1 and container2 are not on the same network as container3, they will not be able to reach it (and likewise, container3 won't be able to reach container1 or container2).

**Comment by cpuguy83** [comment] 2016-02-05 14:42
You are missing `docker network connect isolated_nw container2` from the example in the docs.

**Comment by thaJeztah** [comment] 2016-02-05 14:44
Yup, that looks like the issue here; I'm closing this issue, but feel free to comment here after I've closed, @edwintorok

**Comment by edwintorok** [comment] 2016-02-05 14:51
Tried to connect but it didn't help:
```
[root@localhost ~]#  docker network connect isolated_nw container2
[root@localhost ~]# docker attach container2

/ # ping container3
ping: bad address 'container3'
```

How about those iptables errors in the journal?

**Comment by edwintorok** [comment] 2016-02-05 15:09
FWIW on Debian 8 with Docker 1.10.0 the embedded DNS seems to work, I can ping `container3` from `container2` and I can ping `google.com` too, it is just CentOS 7 that I'm having troubles with.

**Comment by mavenugo** [comment] 2016-02-05 15:52
@edwintorok please also connect `container3` to `isolated_nw` for the name-resolution to work.

**Comment by huadong** [comment] 2016-02-05 15:58
the embedded DNS not work for centos7!
using docker-compose:
`version: '2'
services:
  registry:
    image: registry:2
    ports:
     - "127.0.0.1:5000:5000"
    volumes:
     - /data/docker/registry/conf/config.yml:/etc/docker/registry/config.yml
     - /data/docker/registry/data:/var/lib/registry
    restart: always
  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    depends_on:
     - registry
    links:
     - registry:docker-hub
    ports:
     - "127.0.0.1:8001:80"
    environment:
     - ENV_DOCKER_REGISTRY_HOST=docker-hub
     - ENV_DOCKER_REGISTRY_PORT=5000
    restart: always`

docker exec -it registry_registry-ui_1 /bin/bash
root@58cef0750f3e:/# ping www.google.com
ping: unknown host
root@58cef0750f3e:/# ping registry
ping: unknown host
root@58cef0750f3e:/# ping docker-hub
ping: unknown host

docker -v
Docker version 1.10.0, build 590d5108

docker-compose -v
docker-compose version 1.6.0, build d99cad6

uname -a
Linux office-backend 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

docker network ls
NETWORK ID          NAME                DRIVER
6e499c8070fe        registry_default    bridge              
c6b42b67abfe        bridge              bridge              
44a4b31240a2        none                null                
8cb6cccb1a5a        host                host

**Comment by edwintorok** [comment] 2016-02-05 15:59
Ok attach both, but no luck:
```
[root@localhost ~]# docker network inspect isolated_nw
[
    {
        "Name": "isolated_nw",
        "Id": "c8226ec88a78520545127b590745593d25ec631d28a7ece1859c09674e877414",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.25.0.0/16"
                }
            ]
        },
        "Containers": {
            "6a25cd358ca3427c5d674a445a23744b7f2a538c5a62000c992f21cac600bb48": {
                "Name": "container3",
                "EndpointID": "9b433342aa50558ebcfef06c86155c3d8f0f404bba3be1134e34b3156d47f649",
                "MacAddress": "02:42:ac:19:00:03",
                "IPv4Address": "172.25.0.3/16",
                "IPv6Address": ""
            },
            "cfbe50069760cd253012f6f118306317290e77c6008823068ff53b72ea0a2b22": {
                "Name": "container2",
                "EndpointID": "2385128cb4b7451568bfad40c28cc25ac57875e86aac0d9be2c6baaf8a40435b",
                "MacAddress": "02:42:ac:19:00:02",
                "IPv4Address": "172.25.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {}
    }
]
[root@localhost ~]# docker attach container2

/ # ping container3
ping: bad address 'container3'
```

**Comment by mruckli** [comment] 2016-02-05 16:06
Having the same issue on my fedora 23 installation... Also found this on stackoverflow which seems related: http://stackoverflow.com/questions/35221821/cant-reach-containers-with-new-1-10-dns-sd

**Comment by huadong** [comment] 2016-02-05 16:19
@mruckli It works after stopped firewalld in centos 7!

**Comment by mavenugo** [comment] 2016-02-05 16:22
@edwintorok @mruckli @huadong thanks for the feedback. Yes, it seems to be an issue in centOS7.
Workaround is to stop firewalld.

We will get this fixed asap.

**Comment by tunh** [comment] 2016-02-06 11:07
I have the same problem, I use Fedora 23 host. I described here http://stackoverflow.com/questions/35238690/can-not-resolve-hostname-in-docker-1-10

**Comment by deitch** [comment] 2016-02-06 16:21
@mavenugo is there an architectural write-up? I have waded through the Issues and PR and documentation, but would really love a clean, "this is how the new DNS structure works under the covers." What does it do with each network and each type, where does it go, what does it add to iptables, etc? 

I think it would help those of us "out in the wild" greatly if we really knew how this works, what to look for, and how to leverage it.

Or maybe I am the only one and everyone else understands it sufficiently from the existing docs? (in which case, feel free to shut me down, but politely :-) )

**Closed** 2016-02-08 03:06 UTC
Labels: group/networking, priority/P0

**Comment by easyrasta** [comment] 2016-02-10 15:38
I am on centos7. I haven't test fixed version, But I tried mentionned workaround (stopping firewalld). In my container ping work now, but I continue to receive error with my nodejs program: 
```
Could not connect to server: Error: getaddrinfo ENOTFOUND nats-main nats-main:4222 
```
I use a private bridge network

this PR would also fixed this ?

**Comment by mschristiansen** [comment] 2016-02-10 16:11
You must disable, not just stop, firewalls. E.g. `systemctl disable
firewalld`.

**Comment by easyrasta** [comment] 2016-02-10 16:29
ok thanks, I also rm image to and rerun again to work

**Comment by thaJeztah** [comment] 2016-02-11 00:47
We made a release candidate for docker 1.10.1 https://github.com/docker/docker/releases/tag/v1.10.1-rc1; if people are willing to test if this issue is resolved, that would be great! (note: although we don't anticipate the release candidate bringing new bugs, it *is* a pre-release, so should not be used in production)

**Comment by svenio** [comment] 2016-02-13 20:14
Greetings everyone.  I've been lurking this issue since its creation because I had the same issue on my home server.  I just updated to the new version and gave it a shot.  Here's what happened after I re-enabled firewalld:

`# systemctl start firewalld`
`# docker start owncloud`
`Error response from daemon: failed to create endpoint owncloud on network bridge: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -A DOCKER -p tcp -d 0/0 --dport 443 -j DNAT --to-destination 172.17.0.3:443 ! -i docker0' failed: iptables: No chain/target/match by that name.
Error: failed to start containers: owncloud`

Is there something I'm doing wrong here?  I've gone back to running without firewalld in the meantime.  Some environment details if it helps:

'# docker version

Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64'

`# docker info

Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 39
Server Version: 1.10.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-268657317-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.213 GB
 Data Space Total: 107.4 GB
 Data Space Available: 87.07 GB
 Metadata Space Used: 5.984 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.532 GiB
Name: server
ID: ZFOJ:7WGH:XM7Y:F2QS:HKT6:GHWO:6BCY:HVYF:JH4B:7VYG:Y6XY:RY5T
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
`

`#uname -a
Linux server 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mruckli** [comment] 2016-02-13 22:26
@svenio did you restart you docker daemon after enabling firewalld? That might fix it...

**Comment by svenio** [comment] 2016-02-14 15:26
@mruckli *Sigh* Talk about missing the obvious.  It's the network admin equivalent of "did you plug it in?"  :)  

It works now.

**Comment by mavenugo** [comment] 2016-02-14 15:39
@SvenDowideit @mruckli we fixed the issue faced due to firewalld restart case (without the daemon restart) in https://github.com/docker/libnetwork/pull/947. It will be made available in the next release.

**Comment by apsega** [comment] 2016-03-22 22:42
Docker containers cannot reach each other via names/hostnames after upgrading to 1.10.

    docker --version
    Docker version 1.10.3, build 20f81dd

Pinging Jekins container via name does not work:

    docker exec -ti proxy ping jenkins
    ping: unknown host jenkins

Pinging Jenkins container via IP works:

    docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' jenkins
    172.17.0.11
    docker exec -ti proxy ping 172.17.0.11
    PING 172.17.0.11 (172.17.0.11) 56(84) bytes of data.
    64 bytes from 172.17.0.11: icmp_seq=1 ttl=64 time=0.243 ms
    64 bytes from 172.17.0.11: icmp_seq=2 ttl=64 time=0.062 ms
    64 bytes from 172.17.0.11: icmp_seq=3 ttl=64 time=0.063 ms

Linking containers is not an options as I'm having Nginx container reverse proxying to lots of other containers. Is there any other way of solving this? Using anything else than IPs for inter-container communication?

**Comment by Morpheu5** [comment] 2016-03-24 09:32
I have nginx reverse-proxy to lots of containers, and I manage the whole thing via docker-compose, so that works: I can ping containers from within other containers and all that. However, I'm not able to ping containers via their names from the host machine. I tried pretty much every advice given in this discussion.

**Comment by cpuguy83** [comment] 2016-03-24 11:22
Container names are not available from the host.

**Comment by Morpheu5** [comment] 2016-03-24 12:15
Not even the embedded DNS? For now I worked around this with a custom script that edits `/etc/hosts`…

**Comment by apsega** [comment] 2016-03-24 18:13
@Morpheu5 have you tried running all containers in one bridged docker network? I've created one by running ``docker network create --driver bridge network1`` and then ran all containers in it, and everything works perfectly fine.

**Comment by Garreat** [comment] 2016-03-25 19:19
Hitting the wall here. CentOS7, Swarm and overlay networks.
`3.10.0-327.10.1.el7.x86_64`
`# docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:16:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:16:33 2016
 OS/Arch:      linux/amd64`
`# docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.10.2
Storage Driver: devicemapper
 Pool Name: docker-253:3-17700697-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.601 GB
 Data Space Total: 107.4 GB
 Data Space Available: 22.19 GB
 Metadata Space Used: 3.092 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: overlay bridge null host
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.797 GiB
Name: n1
ID: WP23:YQON:7YTL:WFXI:WFWM:JL65:7GOA:FUKP:PISL:3IQ3:S3AH:VPBZ
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 role=node
Cluster store: consul://127.0.0.1:8500
Cluster advertise: x.x.x.x:2375`
Created Swarm cluster:
`# docker -H :3375 info
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 13
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3`
All healthy.
`# docker -H :3375 network create back`
(...)
`# docker -H :3375 inspect nginx
(...)
"Networks": {
                "back": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "d19de8c0c094736867cc31bef04835ff5c7bdca60e9718e742bb0fdd20c3a0ab",
                    "EndpointID": "cc80db1d3f4344199ae1aad935af5e407f037078458dbf912e873a34ef6e8746",
                    "Gateway": "",
                    "IPAddress": "10.0.0.2",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:00:02"
                }`
`# docker -H :3375 inspect test2
(...)
 "Networks": {
                "back": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "d19de8c0c094736867cc31bef04835ff5c7bdca60e9718e742bb0fdd20c3a0ab",
                    "EndpointID": "4e42570aff2a6b9a0501f29aa3d65814c40baa57505c474c30db0ad941f7c71b",
                    "Gateway": "",
                    "IPAddress": "10.0.0.4",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:00:04"
                }`
Ping container test2 from container nginx living on different node (same overlay network 'back'):
`[root@nginx /]# ping 10.0.0.4
PING 10.0.0.4 (10.0.0.4) 56(84) bytes of data.
64 bytes from 10.0.0.4: icmp_seq=1 ttl=64 time=0.777 ms
64 bytes from 10.0.0.4: icmp_seq=2 ttl=64 time=0.389 ms`
`[root@nginx /]# ping test2
ping: unknown host test2`
`[root@nginx /]# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
10.0.0.2	nginx
172.18.0.2	nginx`
`[root@nginx /]# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0`
`[root@nginx /]# ping 127.0.0.11
PING 127.0.0.11 (127.0.0.11) 56(84) bytes of data.
64 bytes from 127.0.0.11: icmp_seq=1 ttl=64 time=0.055 ms
64 bytes from 127.0.0.11: icmp_seq=2 ttl=64 time=0.041 ms`

firewalld and selinux on all hosts are off:
`# systemctl status firewalld; echo; sestatus
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28`

Should I disable selinux completely?
Or maybe it's time to go Debian / more fresh kernel?

**Comment by bbnnt** [comment] 2016-04-18 16:30
@Morpheu5 you say it works okay for nginx right (nginx can reach other containers) ? At least that work for me, i can get lost to connect to some redis or postgres containers, nothing to do

I'm quite new to docker, but i can't yet understand how stable it is, so with this kind of troubles i'm concerned. clearly stated in the docs, links should work without as expected but it seems "random"

**Comment by Morpheu5** [comment] 2016-04-19 12:57
@bbnnt Yes, I can ping (and connect to) the other containers from within a given container. I bring everything up with Docker Compose, so I guess that's what takes care of correctly creating the network. The issue I'm having is I'd like to use the embedded DNS server from the host, so I can ping/connect to the containers from the host by calling them with their hostnames. That is not working for me.

**Comment by ninchan8328** [comment] 2016-05-11 05:02
Just update docker and docker-compose and bring up two containers using v2 format, container are up but not pingable to other container using hostname, or container name, ping ip works.

Can some give me a working docker-compose as an example? Following some online doc don't resolve my problem.


>>docker --version
Docker version 1.10.1, build 9e83765
>>docker-compose --version
docker-compose version 1.7.0, build 0d7bf73

**Comment by thaJeztah** [comment] 2016-05-11 14:10
@ninchan8328 simple test-file for docker-compose;

```yaml
version: '2'
services:
  one:
    image: nginx:alpine
  two:
    image: nginx:alpine
    command: "sh -c 'ping one'"
```


```
docker-compose up
Creating network "repro_default" with the default driver
Creating repro_one_1
Creating repro_two_1
Attaching to repro_one_1, repro_two_1
two_1  | PING one (172.23.0.2): 56 data bytes
two_1  | 64 bytes from 172.23.0.2: seq=0 ttl=64 time=0.123 ms
two_1  | 64 bytes from 172.23.0.2: seq=1 ttl=64 time=0.101 ms
two_1  | 64 bytes from 172.23.0.2: seq=2 ttl=64 time=0.176 ms
two_1  | 64 bytes from 172.23.0.2: seq=3 ttl=64 time=0.075 ms
two_1  | 64 bytes from 172.23.0.2: seq=4 ttl=64 time=0.084 ms
two_1  | 64 bytes from 172.23.0.2: seq=5 ttl=64 time=0.053 ms
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by ninchan8328** [comment] 2016-05-17 04:34
that works fine. however when i use my own image with privilege: true, containers cannot ping each other; but if i take out privilege:true, it works again. Any idea why? I dont see the same with the nginx:alpine image.

Unfortunately, in my environment , i need to use privileged: true, and it worked fine in the old docker engine pre version 1.8.

**Comment by thaJeztah** [comment] 2016-05-17 09:14
@ninchan8328 Even when adding "privileged" to my example file, it works. Keep in mind that, when running a container "privileged", basically you're giving it root access on your host. I don't know what's running in your container, but it's likely that it's making changes that cause the networking to fail. Those steps are normally blocked, but by adding "privileged", you're allowing the container to make those changes. I'd investigate *why* your container needs `--privileged` (privileged is almost *never* the answer). If it needs some capabilities beyond the standard ones, only add *those* capabilities (or check if it can run without).

Based on the above - it's not a bug in Docker, but an issue with the image/container you're running.

**Comment by ninchan8328** [comment] 2016-05-17 15:01
@thaJeztah  thanks for your response, and I agree this may be something specific to my image, however, I also try to do the same with our base image which has serviceability tools installed like rsyslog, collectd, lumberjack, etc... and still dont work with privileged:true. Do you have any suggestion how i can troubleshoot further?

**Comment by thaJeztah** [comment] 2016-05-17 15:05
> and it worked fine in the old docker engine pre version 1.8.

Version 1.8 did not use an embedded DNS server; perhaps you should check if your container tries to modify `/etc/resolv.conf` inside the container, and update it to use a different DNS

**Comment by mimousewu** [comment] 2017-08-30 10:04
I met this problem in docker 1.11.1 1.11.2 in Ubuntu in last year. Now I met it again in 1.12.6 in CentOS 7.3.
@thaJeztah you will not met this problem if run a new environment. It always happens after few days successful running. 
I found a few issues related to this problem and last 2 years. I can not imaging that one issue can last 2 years. I never found the root cause, I have not confident on the work rounds. Sometimes, it will happened again in the future.
Issues:
https://github.com/moby/moby/issues/23855
https://github.com/moby/moby/issues/13381
https://github.com/docker/libnetwork/pull/947

Anyone know could confirm this issue resolve in what version of docker?

**Comment by JithinPavithran** [comment] 2017-11-14 08:27
I have this issue with Ubuntu 16.04. As mimousewu said, sad that it's not fixed even after 2 years.

**Comment by vladsol** [comment] 2017-12-05 15:55
CentOS Linux release 7.4.1708
Docker version 17.09.0-ce, build afdb6d4

Two containers (busybox) - cont1 and cont2 connected to intnet network.
FirewallD is stopped.
from container cont1:
```
/ # ping cont2
ping: bad address 'cont2'
```

From container cont2:
```
/ # ping cont1
ping: bad address 'cont1'

```

But!
```
/ # ping google.com
PING google.com (216.58.214.206): 56 data bytes
64 bytes from 216.58.214.206: seq=0 ttl=56 time=28.284 ms
```
is ok)
So only container names resolution is not working.

**Comment by localsnet** [comment] 2018-03-23 10:44
@Morpheu5 , have you any changes in solution in DNS containers from host? Have a new Docker support some  DNS sync/sharing with hosts file/DNS server of the host?

**Comment by redmosaic** [comment] 2020-04-23 19:00
Is it possible to whitelist something in firewalld without disabling it altogether?
