### ISSUE TITLE
Docker not mounting file using -v

### ISSUE THREAD

**Issue by ezjacob-maheim** [docker/docker#25670] opened 2016-08-12 17:19 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 23
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 226
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.16-boot2docker
Operating System: Boot2Docker 1.12.0 (TCL 7.2); HEAD : e030bab - Fri Jul 29 00:29:14 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.79 GiB
Name: default
ID: MZAC:5BPF:O3WE:RBOA:BEGQ:J3T4:WIBA:KZQ7:FW7Y:MZMK:SASY:BG22
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 24
 System Time: 2016-08-12T17:12:39.409416142Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox Version 5.0.24 r108355

**Steps to reproduce the issue:**
1. If I initial run the following command in maven project without building the war first it runs successfully and I can see that the *.war file is a folder in the container since there was nothing in the host.

```
docker run -ti -v "$PWD/target/description-api-dev.war":/test/root.war centos:centos7 bash
```

2. Now if I exit the container remove it and then build the *.war on the host I can see that the file exists on both the host and the VM. So I run the command again and I get the following error

```
docker: Error response from daemon: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/da04aa2043c876b7a14a859a72a2752bf45548280360863f31b0290e95b0be99/test/root.war" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/da04aa2043c876b7a14a859a72a2752bf45548280360863f31b0290e95b0be99" caused "not a directory".
```

3. If I restart the virtual vm though and then run the command again. It starts successfully and I now see that /test/root.war is the actually file. For some reason if I run the docker first without the file I have to restart the whole VM to remove it from cache. Now I thought it was VirtualBox but I've tested the scenario where  cleaned the project, restart the VM, build the project and then ran the command everything happened as expected and the file exists. But if you run the command first before building, you'll have to restart the vm to be able to run the container again.

Is there something I'm doing wrong?

**Comment by cpuguy83** [comment] 2016-08-12 18:13
This is because docker automatically creates a dir when it can't find the source path.
When you restart boot2docker the host FS is reset as well (except /var/lib/docker and /var/lib/boot2docker).

Basically, if you want a file, make sure the file exists or you are in for a bad time.

**Comment by justincormack** [comment] 2016-08-12 20:18
Generally, avoid bind mounting files if at all possible, there are many unexpected side effects, eg with update.

**Comment by thaJeztah** [comment] 2016-08-13 15:49
There's some warning about mounting files in the docs as well https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-file-as-a-data-volume

I'll close this issue, because this is not a bug in docker, but feel free to comment after I closed

**Closed by thaJeztah** 2016-08-13 15:49 UTC
Labels: version/1.12
