### ISSUE TITLE
--link issue for hand-made images

### ISSUE THREAD

**Issue by estarter** [docker/docker#25662] opened 2016-08-12 13:08 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 55
 Running: 4
 Paused: 0
 Stopped: 51
Images: 91
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 251
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 27.39 GiB
Name: osboxes
ID: JWJV:CIYI:4DPQ:MOFU:IPXH:3BIS:GJEF:UUPY:QIH5:243U:SE4X:QEWS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Run a container for linking
```
docker run --rm --name one -ti ubuntu:14.04 /bin/bash
```
2. Run second container with the link to the first one, create a new image manually based on the second container.
```
docker run --name two --link one:ONE -ti ubuntu:14.04 /bin/bash
    echo xx > xx
    ping -c 1 one # OK
    ping -c 1 ONE # OK
    exit
docker commit two two-image
```
3.Run a new container from hand-made image and check the link
```
docker run --rm --link one:ONE -ti two-image /bin/bash
    ls xxx # OK
    ping -c 1 one # OK
    ping -c 1 ONE # OK
    exit
```
4. Run another container for linking
```
docker run --rm --name three -ti ubuntu:14.04 /bin/bash
```
5. Run a new container from hand-made image and check the link
```
docker run --rm --link three:ONE -ti two-image /bin/bash
    ls xxx # OK
    ping -c 1 three # FAIL
    ping -c 1 ONE # FAIL
    exit
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-08-12 13:56
I'm not able to reproduce this; is the *original* container `one` still running?

Note that using classic `--link` does have many limitations. For example, the "classic" links (on the default "bridge" network) establish a link between a specific *instance* of a container, and not based on the "name" of that container.

In case a container is removed, and replaced with a new one (with the same name), no new link is created between those containers. I think that even a `docker restart <container>` (which could potentially result in `<container>` getting a new IP address) can result in the link being broken.

Instead, you can use a custom network, and use that for your containers. Doing so will use DNS-based discovery, based on the *name* of the container. In many cases you then no longer need to use `--link` at all (only if you need to have "container scoped" aliases), alternatively, you can set a "network scoped" alias (`--network-alias`), if you want a container to be accessible by a hostname other than the name of the container.

For example:

```bash
docker network create my-network

docker run -dit --name one --network-alias ONE --network my-network ubuntu:14.04

docker run -it --rm --name two --network my-network  ubuntu:14.04

root@7870d57de095:/# ping -c1 one
PING one (172.23.0.2) 56(84) bytes of data.
64 bytes from one.my-network (172.23.0.2): icmp_seq=1 ttl=64 time=0.068 ms

--- one ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.068/0.068/0.068/0.000 ms
root@7870d57de095:/# ping -c1 ONE
PING ONE (172.23.0.2) 56(84) bytes of data.
64 bytes from one.my-network (172.23.0.2): icmp_seq=1 ttl=64 time=0.050 ms

--- ONE ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.050/0.050/0.050/0.000 ms
```

**Comment by estarter** [comment] 2016-08-12 16:45
Thanks for the fast answer Sebastiaan!
I start to use network instead  of list and it does the job.

**Comment by thaJeztah** [comment] 2016-08-12 16:55
Let me close this issue; I couldn't reproduce, and it looks like my suggestion resolved your use case.

Feel free to comment though if you're still having issues :+1:

**Closed by thaJeztah** 2016-08-12 16:55 UTC
Labels: version/1.12
