### ISSUE TITLE
the icc is disabled for docker_gwbridge network

### ISSUE THREAD

**Issue by hehailong5** [docker/docker#30128] opened 2017-01-13 12:52 UTC
I am running docker service via overlay network. when I look into the container, I found there are two ips:

21: eth0@if22: mtu 1450 qdisc noqueue state UP 
inet 10.0.0.7/24 scope global eth0
inet 10.0.0.6/32 scope global eth0

23: eth1@if24: mtu 1500 qdisc noqueue state UP 
link/ether 02:42:ac:12:00:03 brd ff:ff:ff:ff:ff:ff
inet 172.18.0.3/16 scope global eth1

the 10.0.0.x is the overlay ip and the other one 172.18.0.3 I found is attached to the docker_gwbridge network on the host machine:

9: docker_gwbridge: mtu 1500 qdisc noqueue state UP group default 
link/ether 02:42:a8:dc:8a:38 brd ff:ff:ff:ff:ff:ff
inet 172.18.0.1/16 scope global docker_gwbridge

and using "docker network inspect" I also found the icc is disabled for this network:

    "Options": {
        "com.docker.network.bridge.enable_icc": "false",
        "com.docker.network.bridge.enable_ip_masquerade": "true",
        "com.docker.network.bridge.name": "docker_gwbridge"
    }

Here comes my problem:
I have another container which is running under docker0:

4: docker0: mtu 1500 qdisc noqueue state DOWN group default 
link/ether 02:42:8d:ec:39:7a brd ff:ff:ff:ff:ff:ff
inet 172.17.0.1/16 scope global docker0

my target is to access the docker_gwbridge ip 172.18.0.3 from within this docker0 container. as you can guess, I can't make it. I am wondering if that icc:false option should be blamed for this? and how to make it work?

Thanks,
Allen

**Comment by thaJeztah** [comment] 2017-01-13 14:05
First note that the `docker_gwbridge` and `ingress` networks are "special" networks that should not be used to manually attach a container or service. The `docker_gwbridge` network, by design, has `icc` disabled; the `gwbridge` network is automatically attached to containers on an overlay network, to allow them to have external connectivity. The same `gwbridge` is used for all overlay networks, and having `icc=false` makes sure that containers connected to different networks are kept isolated.

To allow containers to communicate with each other, they need to be part of the same network. On docker 1.12, swarm managed networks can only be used by services, so if you want to `docker run` a container and attach it to a swarm-managed overlay network, you won't be able to.

In docker 1.13, a `--attachable` option is added, which allows you to create a swarm-managed overlay network that can be used both by _services_ and _containers_ (started with `docker run`).

For example;

```bash
$ docker network create -d overlay --attachable my-overlay
$ docker service create --network my-overlay --name web nginx:alpine
$ docker run --rm --network my-overlay busybox sh -c 'ping -c3 -W3 web'

PING web (10.0.1.2): 56 data bytes
64 bytes from 10.0.1.2: seq=0 ttl=64 time=0.028 ms
64 bytes from 10.0.1.2: seq=1 ttl=64 time=0.063 ms
64 bytes from 10.0.1.2: seq=2 ttl=64 time=0.060 ms

--- web ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.028/0.050/0.063 ms
```

If this is for debugging; there are some options to attach a container to a swarm-managed network on docker 1.12, but not something for "production" :smile:

Please keep in mind that the github issue tracker is not intended as a general support forum, but for  reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the docker community slack channel (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- StackOverflow


I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-01-13 14:05 UTC
Labels: area/networking

**Comment by hehailong5** [comment] 2017-01-13 14:56
Hi,

thanks for the quick response.
I'm using the version 1.12.x, and yes, I am not able to connect the container to the swarm-managed network via --network, both give me errors:

root@paas-controller-1affc02d-c46a-46dd-a241-f22ae284811e:~# docker run --net=docker_gwbridge -p 10080:80 -p 10443:443  -d apigateway:ha
d67dff3abb2dce2a780662d9fdb39f7fa645a0732f34b43acc625a4952a4867e
docker: Error response from daemon: Updating join info failed: could not find endpoint 843865b67665f548880982cf86b353fb17fda3c28fea23c1913f03d262bff469: [].

root@paas-controller-1affc02d-c46a-46dd-a241-f22ae284811e:~# docker run --net=consul-net -p 10080:80 -p 10443:443 -d apigateway:ha               
docker: Error response from daemon: swarm-scoped network (consul-net) is not compatible with `docker create` or `docker run`. This network can only be used by a docker service.

but I would like to hear the other options you mentioned that could work around this in 1.12.
appreciate your help!

Allen

**Comment by thaJeztah** [comment] 2017-01-13 15:16
First option is to create a custom `bridge` network on the node that the task is running on;

Find a task for the service, and which host it's running on;

```bash
ID            NAME         IMAGE         NODE  DESIRED STATE  CURRENT STATE         ERROR  PORTS
j7nbqov733ml  myservice.1  nginx:alpine  moby  Running        Running 28 hours ago         *:8080->80/tcp
```

Also find the ID of the container for the task;

```bash
docker inspect j7nbqov733ml --format '{{ .Status.ContainerStatus.ContainerID }}'
acca053effcc451195c735d18f4b056cf3b3f75953134e77ef4c412add1b9645
```


Log in on that node, and create a custom bridge network;

```bash
docker network create inspect-net
```

Connect the task container to that network;

```bash
docker network connect inspect-net acca053effcc451195c735d18f4b056cf3b3f75953134e77ef4c412add1b9645
```

And start your container on the same network;

```bash
$ docker run --rm --net=inspect-net busybox sh -c 'ping -c3 -W3 myservice.1.j7nbqov733mlo9hf160ssq8wd'

PING myservice.1.j7nbqov733mlo9hf160ssq8wd (172.21.0.2): 56 data bytes
64 bytes from 172.21.0.2: seq=0 ttl=64 time=0.091 ms
64 bytes from 172.21.0.2: seq=1 ttl=64 time=0.086 ms
64 bytes from 172.21.0.2: seq=2 ttl=64 time=0.086 ms

--- myservice.1.j7nbqov733mlo9hf160ssq8wd ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.086/0.087/0.091 ms
```

Alternatively, use a container that joins the network namespace of a task;

```bash
$ docker run --rm --net=container:acca053effcc451195c735d18f4b056cf3b3f75953134e77ef4c412add1b9645 -it alpine sh -c 'apk add --no-cache curl && curl localhost'
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ca-certificates (20161130-r0)
(2/4) Installing libssh2 (1.7.0-r2)
(3/4) Installing libcurl (7.52.1-r0)
(4/4) Installing curl (7.52.1-r0)
Executing busybox-1.25.1-r0.trigger
Executing ca-certificates-20161130-r0.trigger
OK: 5 MiB in 15 packages
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

Again; these are just for quick debugging; keep in mind that any update to a service will cause tasks to be stopped and new tasks to be created, so you have to repeat the steps above in all those cases.
