### ISSUE TITLE
Driver devicemapper failed to create image rootfs , device already exists

### ISSUE THREAD

**Issue by debianmaster** [docker/docker#9600] opened 2014-12-10 20:05 UTC
I'm get following error message when i build an image

#### `$ docker build .`

`
125a2ed26782: Error pulling image (latest) from cjonagam/centos-nodejs-0.10.33, Driver devicemapper failed to create image rootfs 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: device 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158 already exists 03b4d4702f3ba7d4d2698e22c158 already exists
2014/12/10 12:00:04 Error pulling image (latest) from cjonagam/centos-nodejs-0.10.33, Driver devicemapper failed to create image rootfs 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: device 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158 already exists
`

#### `docker version`
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.3.1
Git commit (client): d84a070/1.1.2
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.3.1
Git commit (server): d84a070/1.1.2

#### `uname -a`
Linux sv2lxrampuat03.corp.equinix.com 3.10.0-123.el7.x86_64 #1 SMP Mon May 5 11:16:57 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

#### `docker -D info `
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:0-1180047-pool
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 293.0 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 0.7 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Debug mode (server): false
Debug mode (client): true
Fds: 10
Goroutines: 12
EventsListeners: 0
Init SHA1: 367758319db3ba405f40bf00af36d004657377a9
Init Path: /usr/libexec/docker/dockerinit
Sockets: [fd://]

**Comment by vbatts** [comment] 2015-01-07 19:37
@debianmaster  we are presently thinking this is not specific to devicemapper, but for whatever reason is expressed easier on the devicemapper driver. See https://github.com/docker/docker/issues/9718#issuecomment-68762458 for those comments, and largely I think this issue is a duplicate of #9718 

@chenchun your issue of device or resource busy seems vague compared to the error of "file exists"

Can both of you update to the latest versions available? even for rhel7, the latest rpm is docker-1.3.2 which has a number of fixes.

**Closed by vbatts** 2015-01-07 19:37 UTC
Labels: /system/devicemapper

**Comment by daniellingo** [comment] 2015-05-07 15:14
```
umount /var/lib/docker/devicemapper/mnt/dccefe7f76ee932a2d10b7737de4c5a4a64e7fa7337e968b0eb0a83d369d923b
```
and run again

**Comment by kermit666** [comment] 2015-05-27 17:32
```
# docker --version
Docker version 1.6.2, build 7c8fca2
```

and still happening.

**Comment by radiumx3** [comment] 2015-07-07 10:13
still happening on 1.6.2

**Comment by zanella** [comment] 2015-07-30 18:58
[root@kubernetes ~]# docker pull centos:7
7: Pulling from centos
f1b10cd84249: Download complete 
f1b10cd84249: Error downloading dependent layers 
c852f6d61e65: Downloading [=====================>                             ] 26.47 MB/62.89 MB
7322fbe74aa5: Error pulling image (7) from centos, endpoint: https://registry-1.docker.io/v1/, Driver devicemapper f7322fbe74aa5: Error pulling image (7) from centos, Driver devicemapper failed to create image rootfs f1b10cd842498c2Error pulling image (7) from centos, Driver devicemapper failed to create image rootfs f1b10cd842498c23d206ee0cbeaa9de8d2ae09ff3c7af2723a9e337a6965d639: Error running DeviceCreate (createSnapDevice) dm_task_run failed
[root@kubernetes ~]# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
[root@kubernetes ~]#

**Comment by MiguelPF** [comment] 2015-09-07 14:33
is happening to me also
> docker version
```
INFO[0770] GET /v1.19/version
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

**Comment by pehrlich** [comment] 2015-09-28 22:34
This was caused by insufficient disk space for me.  (!)
