### ISSUE TITLE
Red Hat installation

### ISSUE THREAD

**Issue by javixeneize** [docker/docker#32139] opened 2017-03-27 13:43 UTC
Hi

I am trying to install Docker in a RHEL7 but i am having some problems with dependencies

** Found 3 pre-existing rpmdb problem(s), 'yum check' output follows:
docker-engine-1.10.0-1.el7.centos.x86_64 has missing requires of libdevmapper.so.1.02(DM_1_02_97)(64bit)
docker-engine-1.10.0-1.el7.centos.x86_64 has missing requires of libsystemd.so.0()(64bit)
docker-engine-1.10.0-1.el7.centos.x86_64 has missing requires of libsystemd.so.0(LIBSYSTEMD_209)(64bit)

Those libraries are provided by device-mapper package. I have this package already installed

Package 7:device-mapper-1.02.93-3.el7_1.2.x86_64 already installed and latest version

I have seen several issues raised similar to this, but doesnt seem to be a clear solution to this problem

What should i do?

Thanks

**Comment by thaJeztah** [comment] 2017-03-27 14:21
Docker 1.10.0 is quite old now, and no longer maintained. Can you try installing the current version? If you need offline install, you can try the packages from here http://yum.dockerproject.org/repo/main/centos/7/Packages/

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-27 14:21 UTC
