### ISSUE TITLE
docker doesn't understand 'x-gzip' encoding and thus fails to pull images

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#17595] opened 2015-11-01 18:50 UTC
If we have a docker v2 registry service (not distribution but pulp) behind httpd, httpd sends blobs with header specifying "x-gzip". Unfortunately docker engine doesn't understands this and fails to verify the blobs:

http://pastebin.com/SxLLfR9V

Relevant line from /etc/httpd/conf/magic
0       string          \037\213        application/octet-stream        x-gzip

With curl, this works just fine and one can download and verify all blobs.

Version-Release number of selected component (if applicable):

docker-1.9.0-5.git11b81f9.fc24.x86_64

it also fails with 1.8 docker
This is the response from server:

HTTP/1.1 200 OK
Date: Mon, 26 Oct 2015 13:30:22 GMT
Server: Apache/2.2.15 (Red Hat)
Last-Modified: Fri, 23 Oct 2015 12:13:20 GMT
ETag: \"43c38-11736-522c48997e618\"
Accept-Ranges: bytes
Content-Length: 71478
Docker-Distribution-API-Version: registry/2.0
Connection: close
Content-Type: application/x-tar
Content-Encoding: x-gzip

When getting rid of the "x-gzip", docker succeeds to pull the image.

**Comment by phemmer** [comment] 2015-11-01 19:25
RFC2616 does not list `x-gzip` as a valid content-encoding. It does however list `gzip`.
`x-` prefix is usually used to designate non-standard things. Thus compatibility with them cant be relied upon.

**Comment by TomasTomecek** [comment] 2015-11-02 08:45
@phemmer The RFC *does* list it:

    For compatibility with previous implementations of HTTP,
    applications SHOULD consider "x-gzip" and "x-compress" to be
    equivalent to "gzip" and "compress" respectively.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.5

**Comment by unclejack** [comment] 2015-11-02 08:53
From what I recall, the client registry code doesn't set the accepted encoding header to gzip. The server shouldn't serve gzip compressed content to a client if the client doesn't tell it that it accepts such an encoding.

**Comment by TomasTomecek** [comment] 2015-11-02 09:24
Yes, what I understand is happening is that httpd figures out (using magic from its config) that layers are gzipped tarballs, so it sets encoding to `Content-Encoding: x-gzip`. Then after transfer is over, digest of pulled layer is different than it should be. With `curl` this works just fine (does `curl` decompress and `go` does not? I'm not sure if digest should be computed from gzipped or not gzipped archive, or if it should be computed from archive at all)

**Comment by metasim** [comment] 2015-11-16 18:05
I'm wondering if I'm having a similar problem. For some (but not all) images I'm getting the following log message from the daemon:

```
filesystem layer verification failed for digest sha256...
```

This is with Docker  version 1.9.0 on RHEL 7.

**Comment by jefby** [comment] 2015-11-23 07:40
Yes, i am having a simliar problem in ARM64 centos7.1 

```
filesystem layer verification failed for digest sha256...
```

**Comment by rhatdan** [comment] 2016-01-06 20:48
Any update on this issue?

**Comment by thaJeztah** [comment] 2016-01-06 21:06
ping @aaronlehmann @tonistiigi any thoughts on this?

**Comment by aaronlehmann** [comment] 2016-01-06 21:15
I suspect that Go's HTTP client is automatically decompressing the content based on the `Content-Encoding` header. This breaks the digest verification.

I think it's fundamentally wrong for the HTTP server to be adding this header. It tells the client that the HTTP stream is compressed. In this case, it's not the HTTP stream that's compressed, but the actual payload. The distinction matters a lot.

So I would argue that this is not a Docker bug.

**Comment by dmcgowan** [comment] 2016-01-06 21:31
The digest being verified is likely on a compressed blob. If the transport layer is instructed to decompress then the wrong bytes are delivered to the application for digest verification. Currently docker will always construct blobs compressed and use the digest of that compressed blob. While pulling uncompressed blobs is supported if the digest in the manifest is of the uncompressed data, this will not be supported for push.

I suggest we close this issue unless a specific feature or bug can be defined.

**Comment by stevvooe** [comment] 2016-01-06 21:53
@aaronlehmann @dmcgowan Your assessment is correct.

@shishir-a412ed It is incorrect behavior for the http server to detect the content compression and indicate that it has applied a content coding to the entity. The `Content-Encoding` header should only be used when the server applies to an encoding to the content, indicating that the consumer must unpack it to get the original entity. In addition, setting `Content-Length` when the entity-length and transfer-length are different, which is the case in this example, is invalid.

The fact that `curl` is able download this doesn't tell us much, since `curl` isn't verifying the content against the requested digest. If you do, you will see that the digest is of the unpacked content, rather than the packed, unmodified content.

Looking at this another way, the actual mimetype is something like `application/x-tar+gzip`. Unpacking this in the http stream violates the content addressability guarantee, by stripping it to `application/x-tar` and thus changing the content. Effectively, docker engine is behaving exactly as intended by catching content that has been modified by a middleman and rejecting. Unfortunately, that middleman is apache. :smile_cat:

The fix here is to disable content sniffing for the blob urls in apache. They are already compressed anyways, so there is no benefit to supporting this header.

**Closed by stevvooe** 2016-01-06 21:53 UTC
Labels: group/distribution, kind/enhancement

**Comment by TomasTomecek** [comment] 2016-01-07 12:06
Fair enough, thanks for update.

**Comment by notroj** [comment] 2016-01-08 11:51
httpd is accurate in describing the media type as a tar file with a gzip content-coding applied; that's exactly what this combination of Content-Type and Content-Encoding headers tells you.  It is correct that you would have to ungzip the message body to get a tar file back (matching the "original entity" - that with the given content-type).   If you don't want the HTTP library to strip content-codings, don't tell the HTTP library to do to that - or fix the HTTP library if it does that by default; it's certainly a client bug not a server bug.

It's also correct that Content-Length, if present, must match the message body length ("transfer-length"), and in RFC 2616 terms the entity-length (the use of "entity" is gone in RFC 7230 et al because it was confusing).

**Comment by aaronlehmann** [comment] 2016-01-08 18:40
> It is correct that you would have to ungzip the message body to get a tar file back (matching the "original entity" - that with the given content-type).

This is where I disagree. The HTTP server errs in declaring that the original entity is a tar. The original entity is in fact a tar.gz.

**Comment by notroj** [comment] 2016-01-08 19:48
"original entity" is not my wording; but we're into semantics.  tar.gz is a filename extension - again, the data is a gzipped tarball and is accurately described as such by the Content-* headers.

Looking at:

https://github.com/golang/go/blob/master/src/net/http/transport.go#L1103
https://github.com/golang/go/blob/master/src/net/http/transport.go#L1365

the HTTP client is trying to treat Content-Encoding like a transfer-coding (transparent transport-level message compression) which it can handle automagically. I'd say that is an (understandable) design error, but it looks like you can work around it by flipping that DisableCompression boolean.

**Comment by aaronlehmann** [comment] 2016-01-08 21:01
@notroj: It seems like turning on `DisableCompression` wouldn't hurt. Feel free to submit a PR to do this. The relevant transport is created at https://github.com/docker/docker/blob/master/distribution/registry.go#L61

**Comment by notroj** [comment] 2016-01-11 11:53
I have know idea whether disabling that flag globally is a good idea, so I wouldn't want to propose that with basically zero knowledge of docker internals.  e.g. are there other cases where the server is compressing normal HTTP responses and the client needs to uncompress them on the fly?
