### ISSUE TITLE
docker 1.10 master doesn't close stats stream when container is removed

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#19750] opened 2016-01-26 23:01 UTC
Steps to reproduce:

```
docker run -d --name broken busybox sleep 1000000
nc -U /var/run/docker.sock
GET /v1.18/containers/broken/stats HTTP/1.1


docker rm -f broken
```

Expected: the connection is closed with 400 bad request
Actual: the connection stays open

The Expected case happens on docker 1.9.1

```
docker version
Client:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   ae8f7c6
 Built:        Fri Jan 22 18:34:29 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   ae8f7c6
 Built:        Fri Jan 22 18:34:29 2016
 OS/Arch:      linux/amd64
```

**Comment by duglin** [comment] 2016-01-27 01:22
I believe this is working as designed. When you do "docker stats" w/o specifying any container it will act like "top" and show the stats for all containers - and it'll remain there showing you nothing even after all containers have died because as new ones start it'll show them.

However, if you specified "broken" on the stats command then you'll see that the connection will close once that container stops.

**Comment by duglin** [comment] 2016-01-27 01:25
Remove old comment - sorry, I missed the "broken" on the URL  :-)
I do think it working in 'master' tho - so we need to move something over to the RC....

**Comment by tiborvass** [comment] 2016-01-27 01:27
@vikstrous confirmed with your build of docker (using commit `ae8f7c6`) however it's fixed in master, but not in the rc2 bump branch. So I'm closing this, but we need to find the commit that fixed it.

**Comment by vikstrous** [comment] 2016-01-27 02:08
I just tried it on master and it doesn't seem fixed.

```
docker version
Client:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7992b35
 Built:        Wed Jan 27 02:05:03 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7992b35
 Built:        Wed Jan 27 02:05:03 2016
 OS/Arch:      linux/amd64
```

**Comment by duglin** [comment] 2016-01-27 02:13
@vikstrous if you use "docker stats broken" instead of nc does it still fail?

**Comment by tiborvass** [comment] 2016-01-27 02:21
Huh, i have no idea what's going on, now it fails on master :S

**Comment by vikstrous** [comment] 2016-01-27 02:25
@duglin somehow `docker status broken` works as expected.

**Comment by duglin** [comment] 2016-01-27 02:30
https://www.youtube.com/watch?v=GRWbIoIR04c

**Comment by crosbymichael** [comment] 2016-01-27 02:37
This is because in the `nc` example you are not passing `stream=1` in the query params so it expects the client to only receive one object and close the connection.  If you set it to streaming if that is what you want it should do that right thing and we can look at fixing this on the server side as well.

**Comment by duglin** [comment] 2016-01-27 02:38
even w/o the stream=1 param I was seeing the correct results - weird

**Comment by vikstrous** [comment] 2016-01-27 02:40
I tried that.

```
GET /v1.23/containers/broken/stats?stream=1 HTTP/1.1
```

logs from trying `docker stats broken` and then nc right after it:
```
Jan 26 18:38:40 compooter docker[15018]: time="2016-01-26T18:38:40.977700349-08:00" level=debug msg="Calling GET /v1.23/containers/broken/stats"
Jan 26 18:38:40 compooter docker[15018]: time="2016-01-26T18:38:40.977732917-08:00" level=debug msg="GET /v1.23/containers/broken/stats?stream=1"
Jan 26 18:38:44 compooter docker[15018]: time="2016-01-26T18:38:44.849335368-08:00" level=debug msg="Calling GET /v1.23/containers/broken/stats"
Jan 26 18:38:44 compooter docker[15018]: time="2016-01-26T18:38:44.849369656-08:00" level=debug msg="GET /v1.23/containers/broken/stats?stream=1"
```

same result. nc hangs.

**Comment by crosbymichael** [comment] 2016-01-27 02:41
ok

**Comment by crosbymichael** [comment] 2016-01-27 02:43
Can you use something like curl or anything but nc because it maybe sepecifc to netcat and how the request is made and nothing wrong with the server

**Comment by vikstrous** [comment] 2016-01-27 02:47
It seems to close this way:

socat TCP-LISTEN:1234,reuseaddr,fork UNIX-CLIENT:/var/run/docker.sock
curl 'localhost:1234/v1.23/containers/broken/stats?stream=1'

**Comment by crosbymichael** [comment] 2016-01-27 02:47
ok, i'll keep looking into what nc is doing

**Comment by vikstrous** [comment] 2016-01-27 02:51
In netcat you can see that then last chunk sent using chunked encoding was of size 0. Could curl be interpreting that as the end and closing the connection? For some reason our Go code didn't seem to detect the end of the stream, so that's why I tried netcat and saw this behaviour.

**Comment by cpuguy83** [comment] 2016-01-27 02:51
@vikstrous Are you using a stream decoder?

**Comment by crosbymichael** [comment] 2016-01-27 02:51
Ya, nc is a little weird.  with 1.9 it does not disconnect, i have to hit Enter to get: 

```
0


HTTP/1.1 400 Bad Request
```

I also had to hit enter twice to get nc to start streaming

**Comment by duglin** [comment] 2016-01-27 02:52
when you use 'nc' and it fails, what do you see on the 'nc' side?  If you hit 'enter' after you kill 'broken' does it return the 400?

**Comment by duglin** [comment] 2016-01-27 02:52
ah, crossed messages - yes I had to hit enter at the end too

**Comment by vikstrous** [comment] 2016-01-27 02:54
This is the go code we are using: https://github.com/donhcd/dockerclient/blob/master/dockerclient.go#L250

**Comment by crosbymichael** [comment] 2016-01-27 03:02
ok, i'll try it with the client code

**Comment by vikstrous** [comment] 2016-01-27 19:04
I just confirmed with wireshark that in curl's case the client closes the connection. It's possible that curl doesn't support the `trailer` part of the spec: https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.6.1 but maybe Go does? I'm still investigating...

**Comment by crosbymichael** [comment] 2016-01-27 19:08
The default docker client uses Go and works so it would be either in your lib or the higher level code blocking on something because from the server side it seems to be working.  

I don't see anything in the client code that stands out as an issue but it is kinda complicated so I'll have to write a little example to test it.

**Comment by vikstrous** [comment] 2016-01-27 19:12
This works as expected. Go seems to be closing the connection from the client side the same way as curl. I'll have to test this out with docker 1.9 because I don't see why this would be any different there.

```go
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
)

func main() {
	resp, err := http.Get("http://localhost:1234/v1.23/containers/broken/stats?stream=1")
	if err != nil {
		fmt.Printf("%v\n", err)
		return
	}
	out, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		fmt.Printf("%v\n", err)
		return
	}
	fmt.Printf("%s\n", out)
}
```

**Comment by vikstrous** [comment] 2016-01-27 19:28
I reproduced the same behaviour with docker 1.9. I don't know why I thought it was different there. It seems like this is a bug in our code. I think we can close this.

**Comment by crosbymichael** [comment] 2016-01-27 19:29
No problem, thanks for helping debug it.

**Closed by crosbymichael** 2016-01-27 19:29 UTC
Labels: priority/P3
