### ISSUE TITLE
IPv6 addresses not available for a brief period after container start

### ISSUE THREAD

**Issue by mpalmer** [docker/docker#18871] opened 2015-12-23 09:24 UTC
When using IPv6 addresses on a Docker container, there is a brief(ish) period during which the address assigned to the container is not available, either to bind to or as a source address.  The symptoms I saw were that attempts to connect to external IPv6 addresses from within the container would fail, and the network traffic had a source address of `::1`, but there are any number of other symptoms that could occur.  Debugging this is made somewhat more difficult by the fact that, by the time you `docker exec -it` into the container, everything seems to work quite nicely.

As an example, here is some output from a startup script which basically does `ip ad sh eth0; sleep 5; ip ad sh eth0` immediately after starting:

```
113: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.4/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001db8::4/64 scope global tentative
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:4/64 scope link tentative
       valid_lft forever preferred_lft forever
Pausing to remember that things are not always as they seem...
113: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.4/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:db8::4/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:4/64 scope link
       valid_lft forever preferred_lft forever
```

Note that before the sleep, the GUA address (`2001:db8::4`) is marked as being "tentative", whereas afterwards it is OK.  Take careful note, you will see this material again... (grin)

The root cause of the problem is IPv6's duplicate address detection logic: a brief period when the kernel is trying to work out if someone else might have the same address, by sending some neighbour solicitation packets (IPv6-speak for ARP) and seeing if anyone replies.  When nobody does after a brief pause, the address is marked as good to use, and we're away.

However, until that "tentative" flag comes down, nothing can bind to the address, and -- more importantly in my case -- it will never be selected as the source address for an outgoing connection.

There are two possible solutions I can think of.  Both will require changes to the vendored `netlink` library, I think, because it lacks the necessary plumbing already to implement either of them.

The first is to make the (not unreasonable) assumption that, since Docker controls (or *should* control) allocation of all addresses within the netblock that has been given to it, we can skip the duplicate address detection phase, and just immediately mark the address as available.  For that, the `netlink` library needs to be taught how to set the `nodad` flag when adding an IPv6 address.

The other way is to play it safe, and let duplicate address detection do its thing, and poll until the new address is properly available.  For that, the `Addr` struct needs to be extended to hold the `tentative` flag, and the `AddrList` function needs to be modified to fill that flag out.  Then, you loop on `AddrList` after `AddrAdd`, until the `tentative` flag goes away.

**Comment by thaJeztah** [comment] 2015-12-23 10:59
ping @aboch; I think you're currently working on improvements to IPv6, so this may be of interest to you

also, a friendly ping to @vishvananda for the netlink library :+1: 

Thanks for the awesome bug report and research, @mpalmer, it's really appreciated!

**Comment by thaJeztah** [comment] 2015-12-23 11:02
I'll tentatively add this to the 1.10 milestone, as I think "more stable IPv6 support" was one of the goals for that release, but let me know if this should not be on there, @aboch

**Comment by aboch** [comment] 2015-12-23 18:03
Thanks @mpalmer for the great investigation. Big help.

@thaJeztah It's fine but I doubt we will have time to look into this special issue by 1.10. I am currently taking care of other more basic ipv6 issues in multi bridge networks, along with allowing the user to choose the ip addresses to assign to the container.

**Comment by thaJeztah** [comment] 2015-12-23 18:22
@aboch alright, let's keep it on the milestone, and if we don't make it for 1.10, we can move it to 1.11.

Having said that, @mpalmer perhaps you have thoughts on this, and want to help out in this area in libnetwork? (speaking on my own term here, I'm not a libnetwork maintainer, haha)

**Comment by mpalmer** [comment] 2015-12-23 23:55
@thaJeztah well, netlink scares the willies out of me, but if someone within the project wants to make a call as to whether to go `nodad` or "poll until ready", I'll give it a shot.

**Comment by icecrime** [comment] 2015-12-29 19:31
IPv6 needs some attention, but unfortunately we won't have the time to fix those by 1.10.

**Comment by mpalmer** [comment] 2015-12-29 23:56
@icecrime OK, pick one of the solutions I gave (or another one, if you've got one) and I'll put it together, hopefully before 1.10 releases (this problem is kind of a blocker for us for a wider-scale IPv6-centric deployment).

**Comment by aboch** [comment] 2015-12-30 00:20
@mpalmer 
I would go for the first solution, setting the `nodad` flag during programming.
(I've seen netlink PR be merged reasonably fast). 

Anyway, whatever solution you are going to choose, thank you for your help.

**Comment by thaJeztah** [comment] 2015-12-30 11:01
Thanks @mpalmer that'd be great! Just a friendly heads-up; code freeze for docker 1.10 will be on January 14th, and take into account that not all maintainers are available because of the holidays/new year.

**Comment by aboch** [comment] 2016-01-04 18:27
@mpalmer 
I am not sure, but I think the support for interface address flags has now been added to netlink lbrary.

Can you please check if https://github.com/vishvananda/netlink/pull/72 is enough to allow caller to pass `IFA_F_NODAD` as a flag ?

**Comment by aboch** [comment] 2016-01-04 19:55
@mpalmer 

I verified with the new netlink and corresponding libnetwork changes it works for user defined IPv6 address (not merged yet):

```
 $ docker run --rm --ip6 2001:df8::5555 --net n0 ubuntu ip addr sh eth0
206: eth0@if207: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:df8::5555/64 scope global nodad     <===
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe13:2/64 scope link tentative 
       valid_lft forever preferred_lft forever
```

This will work also with the current way of setting a deterministic IPv6 address on the default "bridge" network (start daemon with --ip6 --fixed-cidr-v6=<...>, run container with --mac-address option)

The link scope address instead it is not being added explicitly by libnetwork, I am not sure we will be able to set the NODAD there.

@mrjana has some reserves in disable the DAD. 
I will check if I can get the polling changes work.

**Comment by mpalmer** [comment] 2016-01-04 22:57
@aboch: I doubt the link-local address being tentative is as big a problem; nothing should be binding to it.  I'm not surprised @mrjana has reservations about `nodad`, I'm a little wary of it, myself.  However, if it is clearly documented that Docker must be the sole administrator of the v6 range allocated to it, and there's no way for Docker to explode and leave addresses configured but unmanaged, then the risks are... acceptable.

**Comment by aboch** [comment] 2016-01-05 02:04
@mpalmer 
I tried the polling changes while doing some packet captures on the bridge,.
It is not a good solution at it delays the container start of a good second and a half...

Problem is that negative DAD will be resolved by timeout and that takes anytime between one and two seconds.

Looked at the Optimistic DAD, but at first glance it seems it had to be enabled as kernel config first, then you can control it with  `/proc/sys/net/ipv6/conf/eth0/optimistic_dad`

So following @mrjana's suggestion, @mrjana and I played with the container's `/proc/sys/net/ipv6/conf/eth0/router_solicitation_delay`. Setting it to 0 will make the IPv6 address exit the tentative state after 1 second, consistently.

Do you think this deterministic second delay would be ok for your application ?
Otherwise the only option is to disable the DAD by default.
(In future if need arises, we could provide an option to restore the DAD).

Before proceeding further, on disabling the DAD, I wanted to check with you why the "ipv6 ready to use" check cannot be done at the application level. I am thinking you are binding to the specific IPv6 address and not to all addresses. Can anything be derived from the socket bind returned error ?

**Comment by mpalmer** [comment] 2016-01-05 06:19
The application isn't ours to control -- we're containerising existing third-party applications (PostgreSQL, specifically, in this case, but there's lots of other things we'll be working on in the future).

Honestly, checking that *networking* is active in the container feels to me like it should be unnecessary. By the time the container starts, it should be reasonable to assume that all OS-level configuration is completed.  Otherwise, we can't make *any* assumptions about what might be available when the application is started, and we should include application-level checks polling for everything we need -- like filesystems.  Sure, filesystems are available immediately *now*, but since no explicit guarantees are made, we can't make that assumption!

How about this as an alternative: people can either accept the second or two delay in container start, or else specify `--no-dad` to the daemon and make their own guarantees regarding Docker's exclusivity over the CIDR block managed.  Is that a workable tradeoff between performance and correctness?

**Comment by aboch** [comment] 2016-01-05 18:43
>How about this as an alternative: people can either accept the second or two delay in container start, or else specify --no-dad to the daemon and make their own guarantees regarding Docker's exclusivity over the CIDR block managed. Is that a 
workable tradeoff between performance and correctness?

That would be my preferred solution as well, but we need to see if such cli option `--no-dad` for `docker run` and `docker network connect` is going to be accepted by docker maintainers.

**Closed** 2016-01-10 19:46 UTC
Labels: group/networking

**Comment by narqo** [comment] 2016-04-19 15:16
It feels that this behaviour was reverted in docker 1.11, isn't it?

~~~
  › sudo docker version
Client:
 Version:      1.11.0-rc5
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   6178547
 Built:        Mon Apr 11 21:07:24 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc5
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   6178547
 Built:        Mon Apr 11 21:07:24 2016
 OS/Arch:      linux/amd64

  › sudo docker run --rm -i debian ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
20: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:db8:1::242:ac11:2/64 scope global tentative
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link tentative
       valid_lft forever preferred_lft forever
~~~

**Comment by aboch** [comment] 2016-04-19 15:34
@narqo No, that was not intentional. Will look into it.

**Comment by thaJeztah** [comment] 2016-04-19 15:38
@aboch @narqo I opened a separate issue to track the possible regression in 1.11.x https://github.com/docker/docker/issues/22157
