### ISSUE TITLE
Allow multiple log drivers

### ISSUE THREAD

**Issue by phlegx** [docker/docker#32429] opened 2017-04-07 07:38 UTC
Dear all,

I'd like to raise a feature request regarding the logging/log driver. Since I find the json logger very valuable for having a quick look at what is going on, but on the same time for digging trough the logs I prefer to have a log server, it would be really nice to have somehow both. 

This means that docker would need to allow to have multiple logging driver for a container at the same time.

What do you think about this? Would it be possible and valuable to implement this in a future version?

best
p

**Comment by thaJeztah** [comment] 2017-04-07 07:45
Thanks for suggesting; this is a duplicate of https://github.com/docker/docker/issues/17910, and still being looked into. Current thoughts are to have a local "ring buffer" that keeps the last x messages available for viewing the logs through `docker logs`, but send logs to the specified (remote) aggregator. Work on implementing a "plugin" interface for logging drivers is also well underway, which would possibly allow implementing this as a plugin (see https://github.com/docker/docker/pull/28403)

I'll close this issue, because it's a duplicate, but thanks again for opening

**Closed by thaJeztah** 2017-04-07 07:45 UTC
Labels: area/logging, kind/feature

**Comment by thaJeztah** [comment] 2020-11-03 10:35
Just a short update: the upcoming Docker 20.10 release will come with the feature described above ("dual logging"), which uses the `local` logging driver as a ring-buffer, which makes `docker logs` work when using a logging driver that does not have "read" support (for example, logging drivers that send logs to a remote logging aggregator).

This feature was previously available in Docker Enterprise, but has been open-sourced in https://github.com/moby/moby/pull/40543
