### ISSUE TITLE
Checksum mismatch Debian 8.4

### ISSUE THREAD

**Issue by ivanfeob** [docker/docker#23202] opened 2016-06-02 11:52 UTC
I'm trying to install the docker on a Debian 8.4 , follow the tutorial usually after adding the repository:

deb https://apt.dockerproject.org/repo debian- jessie main

When I run apt- get update I get the sum hash mismatch error in :

https://apt.dockerproject.org/repo/dists/debian-jessie/main/binary-amd64/Packages

Already removed the gpg key and imported again , I did not have any result .

**Comment by guewen** [comment] 2016-06-02 12:02
I confirm. On Travis I get a:

```
W: There is no public key available for the following key IDs:

1397BC53640DB551

W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  Hash Sum mismatch
```

And if I run `apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D`, the output is:

```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.TvDyIyxqai --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: error writing keyring `/etc/apt/trusted.gpg': file write error
gpg: key 2C52609D: "Docker Release Tool (releasedocker) <docker@docker.com>" 2 new signatures
gpg: error reading `[stream]': file write error
gpg: Total number processed: 0
gpg:         new signatures: 2

The command "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D" failed and exited with 2 during .
```

**Comment by francisdb** [comment] 2016-06-02 12:09
Same on ubuntu 14.04 LTS

```
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  Hash Sum mismatch
```

**Comment by ahmadsafar** [comment] 2016-06-02 12:10
Has same OS and error like @francisdb

**Comment by pward123** [comment] 2016-06-02 12:25
Same on xenial

**Comment by tanmayambre** [comment] 2016-06-02 13:27
+1 Debian 8.3

**Comment by ThomasSteinbach** [comment] 2016-06-02 13:30
This ticket could be closed. The issue is actively discussed in issue https://github.com/docker/docker/issues/23203

**Comment by thaJeztah** [comment] 2016-06-02 13:54
I'll close this issue. I'll also post the workaround here for the time being;

To give an update; I raised this issue internally, but the people needed to fix this are in the San Francisco timezone, so they're not present yet.

As a temporary workaround, you can install docker 1.11.2-rc1 from the "test" repository; 1.11.2-rc1 is almost the same as the current release, apart from these three changes;
https://github.com/docker/docker/pull/23164, https://github.com/docker/docker/pull/23169, and https://github.com/docker/docker/pull/23176

Those changes should not make a functional difference (and the last change only affects some corner-cases)

You can install the RC, either by changing the "main" to "test" repository for APT, or using the install script;

    curl -fsSL https://test.docker.com | sh

Hoping to get this fixed ASAP

**Closed by thaJeztah** 2016-06-02 13:54 UTC
