### ISSUE TITLE
How to encrypt image

### ISSUE THREAD

**Issue by Wizzercn** [docker/docker#23200] opened 2016-06-02 09:47 UTC
How to encrypt image, in the image operation, must be through the user name and password to access the contents of the container.

I do not want the contents of the container, by others to obtain, play the role of source code protection.

thank you.

**Comment by Vanuan** [comment] 2016-06-02 12:14
It's pointless. Read this question: http://stackoverflow.com/questions/834177/foolproof-trial-strategy
If you don't control the system which runs an image, you can't protect it.

**Comment by unclejack** [comment] 2016-06-02 12:27
Images can't be executed if they're encrypted. In order to run something, that must be mounted somewhere and the operating system will have access to all those files in order to run that. Docker and Linux can't make impossible things possible, nor can it be used as DRM.

You really need to compile your code if you're looking to protect the source code. That's the most you can do.

I'll close this now as it's not a bug. Please feel free to comment. There's no need to open another issue on this topic.

**Closed by unclejack** 2016-06-02 12:27 UTC
