### ISSUE TITLE
"cannot enable tty mode on non tty input" in Cygwin in Windows

### ISSUE THREAD

**Issue by elrac** [docker/docker#12469] opened 2015-04-17 06:17 UTC
When attempting to run docker in Cygwin(Babun) in Windows if the command uses the -t flag I receive the message:

    >>docker run -ti ubuntu bash
    time="2015-04-16T22:49:12-07:00" level=fatal msg="cannot enable tty mode on non tty input"

it seems like it isn't correctly passing the -t option to the underlying ssh call, but I don't know why that would be seeing as the ssh installed with git seems to have the same arguments as the one installed with Babun.

**Comment by ahmetalpbalkan** [comment] 2015-04-17 07:04
@elrac looks like a bug. I'll take a look soon. Can you please try on cmd.exe/powershell or msysgit (git bash for windows) to unblock yourself?

**Comment by ahmetalpbalkan** [comment] 2015-04-17 07:05
I'm actually aware of this. This showed up in my testing before. If we ask Win32 API if the stdout/stderr handles Cygwin passes are terminals or not, it says they're not. mSysgit or ConEmu doesn't do this nor does conhost based terminals (cmd.exe/powershell)

**Comment by elrac** [comment] 2015-04-17 16:41
Figures that it would be a Cygwin issue. I'll probably go back to SSHing into the VM with Putty. Thank you for looking into it.

**Comment by ahmetalpbalkan** [comment] 2015-04-17 16:43
@elrac hmm interesting. Why do you really want to `ssh` into the VM? You can use mingw/conemu/powershell/cmd.exe.

**Comment by elrac** [comment] 2015-04-17 18:50
@ahmetalpbalkan The problem with switching to another shell is that I already have my development environment set up the way I like it. I did try running Cygwin through conemu and I found that the terminal detection issue seems to be due to MinTTY, the terminal program that Cygwin uses. When I run the cygwin shell directly through conemu docker is able enable TTY mode.

**Comment by ahmetalpbalkan** [comment] 2015-04-17 19:10
@elrac I see. Let's keep the issue open, we'll probably need to add a hack to fix this behavior of Cygwin.

**Comment by suminb** [comment] 2015-04-21 02:45
I'm having this issue as well... (Windows 7, Cygwin)

**Comment by rweng** [comment] 2015-04-22 09:36
+1

**Comment by Ulimn** [comment] 2015-05-03 11:20
+1

**Comment by kskalvar** [comment] 2015-05-05 18:56
+1

**Comment by Andarius** [comment] 2015-05-13 09:48
+1

**Comment by mcmil** [comment] 2015-05-20 12:41
:+1: Same on Babun + Win 7

**Comment by kuc** [comment] 2015-05-20 13:14
:+1:

**Comment by Si-Stone** [comment] 2015-05-21 03:58
+1

**Comment by ravetdavid** [comment] 2015-06-03 14:15
+1

**Comment by kuril** [comment] 2015-06-15 16:36
+1

**Comment by jianyunet** [comment] 2015-06-16 07:53
+1 same on win 7 / cygwin

**Comment by stas410** [comment] 2015-06-25 04:32
+1 same problem on windows 8.1 / cygwin

**Comment by jdmswong** [comment] 2015-07-01 04:08
+1 same issue please fix!

**Comment by johnecon** [comment] 2015-07-05 15:15
+ 1

**Comment by gidikern** [comment] 2015-07-06 09:31
+1 same same

**Comment by c3c** [comment] 2015-07-09 17:13
+1

**Comment by setrar** [comment] 2015-07-11 11:52
+1

**Comment by SlyDen** [comment] 2015-07-13 09:29
+1

**Comment by r4fek** [comment] 2015-07-17 17:00
+1

**Comment by elrac** [comment] 2015-07-17 18:37
I'm still seeing this issue in version 1.7.1

**Comment by nonsequitur** [comment] 2015-07-18 20:40
+1

**Comment by ccottet** [comment] 2015-07-20 16:55
+1

**Comment by ryanmaclean** [comment] 2015-07-22 23:07
+1 here as well... thanks guys!

**Comment by tawan** [comment] 2015-07-24 12:36
+1

**Comment by absolom** [comment] 2015-08-04 13:53
+1

**Comment by sirgoatofboy** [comment] 2015-08-05 07:45
+1

**Comment by PhilCorney** [comment] 2015-08-05 09:27
Also have this issue

**Comment by bobfields** [comment] 2015-08-07 21:29
This is an issue when running 'docker -it' command (interactive terminal) when attempting to debug a Dockerfile. Yes we can use the host OS instead of the cygwin/Babun tty terminal, but most/all of the docs written for docker assume a Linux prompt/terminal. Is there a $TERM setting which will work correctly?

**Comment by siripuramrk** [comment] 2015-08-09 07:01
+1

**Comment by thaJeztah** [comment] 2015-08-09 11:01
ping @ahmetalpbalkan do you know if there's any progress here in finding a hack/workaround?

**Comment by ahmetalpbalkan** [comment] 2015-08-10 17:28
@thaJeztah Not really, last time I checked, Cygwin was passing stdout/stderr descriptors that look just like actual files (it creates an effect like `docker run -i -t busybox sh > out.txt`) that's why this error is happening. I haven't had a chance to dig into this. @jstarks any ideas?

**Comment by elrac** [comment] 2015-08-10 18:33
The problem isn't with Cygwin directly, but with the terminal app Mintty. Here is more information about the problem https://code.google.com/p/mintty/issues/detail?id=56 . A workaround would be to run Cygwin in a different command line app.

**Comment by ahmetalpbalkan** [comment] 2015-08-10 18:43
@elrac do you know if msys also uses mintty? This problem doesn't happen on msys bash.

**Comment by nonsequitur** [comment] 2015-08-10 21:24
This isn't directly related to Cygwin.
For example, the issue also appears when docker is called from a `cmd.exe` shell within Emacs. (`Emacs 24.5.1 (i686-pc-mingw32)`)
But it works just fine in a Cygwin bash shell running inside a windowed top-level `cmd.exe` process.

**Comment by tdeheurles** [comment] 2015-08-10 23:05
I reproduce the problem with ConEmu with bash/zsh.
I think mintty is here too.

**Comment by achekulaev** [comment] 2015-08-12 16:59
+1
Having the same problem with bash/zsh on Babun

**Comment by SebNickel** [comment] 2015-08-20 13:20
+1 on babun

**Comment by msieper** [comment] 2015-08-22 19:50
Using Git for Windows 2.5.0:

$ docker run -it rhel6 bash
cannot enable tty mode on non tty input

$ winpty docker run -it rhel6 bash
[root@81af5f9ae1c0 /]#

winpty works, but slows down startup considerably.

**Comment by qinwf** [comment] 2015-08-29 14:03
+1 on babun

**Comment by avelinos** [comment] 2015-09-01 00:38
I'm seeing this now with DockerTools 1.8.1c.  It did not happen with 1.8.1b.

I was able to reproduce it with:
```bash
 docker run -it ubuntu bash
```

**Comment by cliffom** [comment] 2015-09-01 04:39
Same here: Windows 10 with Docker Toolbox 1.8.1c which uses Git 2.5.

**Comment by ahmetalpbalkan** [comment] 2015-09-01 05:08
Folks this never worked on Cygwin. I doubt if it suddenly showed up in 1.8.1c. Can you please reinstall 1.8.1b and verify that was working?

**Comment by avelinos** [comment] 2015-09-01 05:40
My apologies.  It's not with Cygwin.  I'm seeing it with the new MINGW64 that's installed with 1.8.1c.  1.8.1b works and it's using MINGW32.  I'll open up a separate bug in DockerTools against 1.8.1c.

**Comment by cliffom** [comment] 2015-09-01 18:15
@avelinos @ahmetalpbalkan Yes, the issue with 1.8.1c was the move towards Git 2.5 with MINGW64 that uses mintty - 1.8.1b installed MINGW32 which worked fine where tty input was required.

**Comment by apobekiaris** [comment] 2015-09-02 16:16
$ docker run -it -p 3000:3000 cantino/huginn
cannot enable tty mode on non tty input

**Comment by cliffom** [comment] 2015-09-02 16:36
@apobekiaris Again, Docker Toolbox 1.8.1c includes Git 2.5. Git 2.5 now uses mintty which does not allow for tty input. Because of this you will not be able to use docker in interactive mode with the -t (Allocate a pseudo-tty).

The reason this worked fine in 1.8.1b was due to the inclusion of an older version of Git for windows that used MINGW32. mintty was not used in that version. If you must use the -it parameter, you have a few options - cmd, powershell, or download the github windows app that includes MINGW32.

To all posting - I don't think this will ever be 'resolved' unless mintty ever supports tty input. @avelinos opened a separate bug against Docker Tools 1.8.1c (https://github.com/docker/toolbox/issues/136) but again, this isn't related to docker but rather the tools that are included.

**Comment by elrac** [comment] 2015-09-02 16:39
Since I'm seeing a lot of other people trying to deal with this issue the easiest workaround I have found has been to ssh into the VM with `boot2docker ssh` then run your docker command. I have found it to be easier than installing a completely different command line program.

**Comment by cliffom** [comment] 2015-09-02 16:40
@elrac or `docker-machine ssh <machine name>`

**Comment by emsi** [comment] 2015-09-03 09:41
+1

Would it be possible to distribute two alternative docker toolboxes for windows?
The MinGW based and Cygwin based.
I understand the reasons for using MinGW for a "regular" windows users but having a Cygwin based build would be really cool for those tech savvy users that already relay on Cygwin :)

**Comment by raavee** [comment] 2015-09-06 16:20
Issue still persists with the latest Aug 13, 2015 build... 

rprasad@rprasad-W530 MINGW64 ~
$ docker run -it ubuntu bash
cannot enable tty mode on non tty input

rprasad@rprasad-W530 MINGW64 ~
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

rprasad@rprasad-W530 MINGW64 ~

**Comment by thaJeztah** [comment] 2015-09-06 16:32
@raavee see https://github.com/docker/docker/issues/12469#issuecomment-137161775

**Comment by marc** [comment] 2015-09-08 04:17
I hope this does not get too off topic but maybe this summary will be helpful for anyone else who ended up here looking for a better terminal experience with docker on Windows and running into the "cannot enable tty mode on non tty input" error along the way.

I started with docker on Windows with the Docker Quickstart Terminal but noticed some terminal oddities like the docker progress bars scrolling into new lines instead of animating in a single line. The default tmux status bar also showed an extra line and top seemed to show some extra empty lines as well.

Then I tried using the babun shell and also ran into the "cannot enable tty mode on non tty input" error when running `docker run -ti ubuntu bash`.

@elrac and @cliffom mentioned sshing into the VM to run the docker commands as a workaround and it works well.

When I use `docker-machine ssh default` from babun, the docker progress bars that show up when downloading and extracting images look right.
Running tmux and top from inside a docker container also works as expected.
You can also maximize or resize the terminal window without a problem.

If you want to use docker on Windows with the babun shell, just start the shell and from there start the VM and ssh in before running your docker commands:
```
{ ~ }  » docker-machine start default                                                                                                            ~
Starting VM...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
{ ~ }  » docker-machine ssh default                                                                                                              ~
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.8.1, build master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
Docker version 1.8.1, build d12ea79
docker@default:~$ docker run -it ubuntu bash
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu

d3a1f33e8a5a: Pull complete
c22013c84729: Pull complete
d74508fb6632: Pull complete
91e54dfb1179: Already exists
library/ubuntu:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.

Digest: sha256:fde8a8814702c18bb1f39b3bd91a2f82a8e428b1b4e39d1963c5d14418da8fba
Status: Downloaded newer image for ubuntu:latest
root@fcbee221b3f2:/#```

**Comment by michalpristas** [comment] 2015-09-08 05:30
hey @marc thanks for workaround works well for me.

**Comment by tdeheurles** [comment] 2015-09-08 05:58
Thank you (@marc @elrac @cliffom).

Just a little addition, remind that your home folder : `c:\Users\yourname\` is automatically shared in the `default VM`.  
The path is `/c/Users/yourname/`

So you can work as if you're on the host.

**Comment by PhilCorney** [comment] 2015-09-09 14:24
+1 same issue

**Comment by achekulaev** [comment] 2015-09-09 16:31
To this comment https://github.com/docker/docker/issues/12469#issuecomment-137161775
I don't really get why it will never get resolved unless shell provides "full tty". I mean other interactive programs work just fine. SSH works just fine for instance. Why is it possible for ssh client to work while docker needs something more that ssh client needs?

**Comment by tdeheurles** [comment] 2015-09-09 17:25
@achekulaev : I'm not sure the problems comes from here, I have problem too with some vagrant image ...

**Comment by cliffom** [comment] 2015-09-09 19:21
@achekulaev This does a far better job explaining than I can muster up here: http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/#

**Comment by deepak643** [comment] 2015-09-10 05:25
I am facing the same issue with Docker Quickstart Terminal. Any updates on what could be done?

**Comment by lawrencemq1992** [comment] 2015-09-10 06:18
Same! Need updates to fix it!

**Comment by tdeheurles** [comment] 2015-09-10 07:15
What is your error message @deepak643 ? 
`cannot enable tty mode on non tty input` ?
or
`Get http://127.0.0.1:2375/v1.19/containers/json: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.. Are you trying to connect to a TLS-enabled daemon without TLS?`

I just tried that from `Docker Quick Start Terminal` and I have no poblem : `docker run -ti busybox sh`

The second one is a VM problem (env) :

```bash
C:\Users\username>docker ps                                                                                        
Get http://127.0.0.1:2375/v1.19/containers/json: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made b
ecause the target machine actively refused it.. Are you trying to connect to a TLS-enabled daemon without TLS?        
                                                                                                                      
C:\Users\username>docker-machine env default --shell cmd                                                               
set DOCKER_TLS_VERIFY=1                                                                                               
set DOCKER_HOST=tcp://192.168.99.100:2376                                                                             
set DOCKER_CERT_PATH=C:\Users\username\.docker\machine\machines\default                                                
set DOCKER_MACHINE_NAME=default                                                                                       
# Run this command to configure your shell:                                                                           
# copy and paste the above values into your command prompt                                                            
                                                                                                                      
C:\Users\username>set DOCKER_TLS_VERIFY=1                                                                              
C:\Users\username>set DOCKER_HOST=tcp://192.168.99.100:2376                                                            
C:\Users\username>set DOCKER_CERT_PATH=C:\Users\username\.docker\machine\machines\default                               
C:\Users\username>set DOCKER_MACHINE_NAME=default                                                                      
C:\Users\username>docker ps                                                                                            
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS             
  NAMES                                                                                                               
                                                                                                                      
```

**Comment by tdeheurles** [comment] 2015-09-10 07:28
## I found a way to run docker -ti from bash in windows :
start a cmd.exe (it works with ConEMU for better GUI, copy/paste etc ...)

**First `enable docker` in your cmd.exe :**
```bash
C:\Users\username>docker ps                                                                       
Get http://127.0.0.1:2375/v1.19/containers/json: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made b
ecause the target machine actively refused it.. Are you trying to connect to a TLS-enabled daemon without TLS?        
                                                                                                                      
C:\Users\username>docker-machine env default --shell cmd                                                               
set DOCKER_TLS_VERIFY=1                                                                                               
set DOCKER_HOST=tcp://192.168.99.100:2376                                                                             
set DOCKER_CERT_PATH=C:\Users\shinmox\.docker\machine\machines\default                                                
set DOCKER_MACHINE_NAME=default                                                                                       
# Run this command to configure your shell:                                                                           
# copy and paste the above values into your command prompt                                                            
                                                                                                                      
C:\Users\username>set DOCKER_TLS_VERIFY=1                                                                              
C:\Users\username>set DOCKER_HOST=tcp://192.168.99.100:2376                                                            
C:\Users\username>set DOCKER_CERT_PATH=C:\Users\username\.docker\machine\machines\default                               
C:\Users\username>set DOCKER_MACHINE_NAME=default                                                                      
                                                                                                                      
C:\Users\username>docker ps                                                                                            
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS             
  NAMES                                                                                                                                                                                                                   
```

Then start yout bash :
```bash
C:\Users\username>bash
➜  username  docker run -ti busybox sh
/ # echo coooool !!
coooool !!
/ # %
➜  username  docker run busybox sh -c "echo cooooool"
cooooool
➜  username
```

**Comment by tdeheurles** [comment] 2015-09-10 08:19
Some ad : I propose a tutorial to configure your windows environment (with bash/zsh/Oh-My-Zsh, ConEMU etc)
http://tdeheurles.github.io/How-to-install-docker-on-windows/

^^

**Comment by deepak643** [comment] 2015-09-10 09:59
@tdeheurles this was my error message "cannot enable tty mode on non tty input". But however as @marc mentioned when I use ssh, I do not see any problem.

**Comment by edpichler** [comment] 2015-09-10 19:26
Are this problem planned to be solved in some release? I ask because I'm not able to use Docker.

**Comment by tdeheurles** [comment] 2015-09-10 19:29
Why not use ssh or the solution I propose ?

**Comment by edpichler** [comment] 2015-09-10 19:51
@tdeheurles I just installed all the toolbox, started Docker Quickstarter Terminal and did "docker-machine ssh default".

After this, I can run the images bash. Thank you.

**Comment by debovema** [comment] 2015-09-13 17:16
+1

"winpty" is my altenative but I'm waiting for a solution too.

**Comment by sathyaprasad** [comment] 2015-09-21 22:57
+1 Windows 7

**Comment by dkop** [comment] 2015-09-22 12:45
+1 Windows 7 on Babun
**But** docker-compose works ok. In some cases you can use it instead docker.

**Comment by tiangolo** [comment] 2015-09-24 21:36
I wrote a simple workaround / quick fix to allow using Docker Toolbox from Babun, it may help some of you:

https://github.com/tiangolo/babun-docker

With that you can keep using your ```docker``` commands as normal.

And if you are using Cygwin, you should use Babun, a very improved version of Cygwin.

-----

You just have to run one command to setup everything. Although I encourage you to check the source code before running any script (including mine) in your terminal.

Inside, it installs and sets up winpty, and tries to start your default docker-machine VM and set up its environment.

Maybe it gets more relevant now since newer versions of Docker Toolbox come with Git 2.5, which uses mintty and has the same problem of "cannot enable tty mode on non tty input" as in Babun.

**Comment by tdeheurles** [comment] 2015-09-25 06:05
hi @tiangolo, thank you, it works fine. 
babun is great and I didn't how to with it.

**Comment by tiangolo** [comment] 2015-09-25 15:49
I'm glad it helped @tdeheurles.
BTW, I wrote a guide on how to share folders to be used with Docker Volumes that work with Babun, to allow using commands like:
```
docker run -it -v $(pwd):/var/www ubuntu bash
```

The guide is here: https://github.com/tiangolo/babun-docker/wiki/Docker-Volumes-with-Babun

**Comment by stayclassychicago** [comment] 2015-10-30 18:25
I'm not running Windows, but I'm seeing this issue running docker via maven-ant-plugin.  I'm posting this here since https://github.com/docker/docker/issues/16089 was closed 

> Mac OSX 10.10.5

> docker-machine version 0.4.1 (HEAD)
> docker version
> Client:
> Version:      1.8.3
> API version:  1.20
>  Go version:   go1.5.1
>  Git commit:   f4bf5c7
>  Built:        Thu Oct 15 09:12:56 UTC 2015
>  OS/Arch:      darwin/amd64

> Server:
>  Version:      1.8.3
>  API version:  1.20
>  Go version:   go1.4.2
>  Git commit:   f4bf5c7
>  Built:        Mon Oct 12 18:01:15 UTC 2015
>  OS/Arch:      linux/amd64


Steps to reproduce
1. Start docker-machine, eval, etc...
2. Run maven to execute maven-antrun-plugin
-antrun has step to exec:  docker run -ti ${docker.mac.env} ${docker.image} ${docker.command}

Expected result
Docker run is executed with --tty and --interactive

Observed result
Command fails to execute with error message:
>     [exec] cannot enable tty mode on non tty input

Additional info
Running with *either* `--tty` or `--interactive` is successful, however the combination fails -- thus I'm not able to interactively pass the SIGINT signal to terminate the docker run command.

**Comment by dieh1984** [comment] 2015-11-04 15:36
I'm use this command to interactive with my container:

winpty docker exec -it mysqldb bash

It's works for me

**Comment by seregasheypak** [comment] 2015-11-26 21:05
@stayclassychicago, have same on MacOS using gradle exec:
```groovy
task startDocker(type:Exec){
        commandLine "./test-in-docker.sh", uid //fails here: cannot enable tty mode on non tty input
}
```
If I run `test-in-docker.sh docker_uid` in console, it works fine.

**Comment by endosynth** [comment] 2016-03-28 17:51
same problem under cygwin under windows 10 64-bit 

+1

**Comment by tdeheurles** [comment] 2016-03-28 17:58
The docker quickstart terminal seems to work without any issue for a long
time now. Maybe look if cygwin is mandatory ... As you have some linux tool
with the git bash ... Maybe it will do the work.

Le lun. 28 mars 2016 19:54, Andrew Proper <notifications@github.com> a
écrit :

**Comment by endosynth** [comment] 2016-03-28 17:59
thanks @tdeheurles I have a path problem running docker.exe from the docker quickstart terminal but I'll work on fixing that to see if it will work once I have that fixed

**Comment by tiangolo** [comment] 2016-03-28 18:51
@endosynth If you are using Cygwin you may well try **babun-docker**. 

Babun is an improved Cygwin. 

And babun-docker might be what you need: https://github.com/tiangolo/babun-docker

It's just a little program that works on top of Docker in the Babun Terminal (via Winpty), but makes the usage of Docker in Windows a lot simpler and closer to what was intended. Without having to SSH, adding and mounting shared volumes in your Virtual Machine, using Winpty directly and other things.

**Comment by endosynth** [comment] 2016-03-28 19:41
I fixed my problem with the quickstart terminal by doing the following, so now it works OK for me:

  1. uninstalled docker
  2. re-installed docker
  3. docker quickstart wouldn't run so I rebooted PC (Win 10 x64)
  4. ran docker quickstart and now it works OK

Note that I also tried installing babun but it wasn't running properly for me so I removed it. I could have tried harder but wanted to try the quickstart terminal again first.

thanks!

**Comment by Rabbit52** [comment] 2016-05-20 09:50
@tiangolo thank you very much!

**Comment by jhowardmsft** [comment] 2016-05-24 23:53
See https://github.com/docker/docker/issues/15272 and https://github.com/docker/docker/pull/22956. Closing.

**Closed by jhowardmsft** 2016-05-24 23:53 UTC
Labels: group/windows, kind/bug

**Comment by jhowardmsft** [comment] 2016-05-25 17:11
For completeness, you can use winpty to present a TTY-style input to mintty - it's even in the git for Windows installer. Couple of screenshots below - one for the installer, other showing an interactive docker attach and docker login from mintty, both not using (error case) and using (success case) winpty.
![minttywinpty](https://cloud.githubusercontent.com/assets/10522484/15549332/ee1a99a2-2260-11e6-83f1-f3698ce47f2a.JPG)
![winpty](https://cloud.githubusercontent.com/assets/10522484/15549334/f0bbc49c-2260-11e6-8ac5-e943aaa8e970.JPG)

**Comment by vickoman** [comment] 2017-03-15 20:23
This works for me:

winpty docker run -it name-container-running bash

**Comment by rahmanya** [comment] 2017-09-08 22:55
I was having the same issue when I tried to run "docker run -it ubuntu bash" from cygwin.
here is what I did to resolve the issue:
Aparently, this problem is to do with MinTTY being implemented as pipes
instead of something that directly encapsulates a Windows console.

so the work around for this (after digging around some resources which I will reference below)
was to install WinPTY. This is a tool that launches a program in a typical Windows console,
captures the data, and forwards it to MinTTY seamlessly.

so I followed the guide from this website:
https://github.com/rprichard/winpty
after understanding that i needed to have the following cygwin packages:
-mingw64-x86_64-gcc-g++
-gcc-g++
-make

I decided to re-install the version of my installed cygwin (this is not actually necessary, but I just wanted to start
on a clean slate)
I decided to have the follwong packages installed with my fress install of cygwin:
lynx, wget, curl, rsync
-python, python3
-bzip, tar
-Bash-completion
-vim, vim-common
-tmux
-git
-diffutils
-make
-gcc-c, gcc-g++
-openssh
-ncurses

after installing cygwin, I ran:
cd /bin
then clone the repo from like thus:

git clone https://github.com/rprichard/winpty.git
then cd into the winpty directory and ran:
./configure, make and make install to setup the winpty package.

after that i tested my installtion from the cygein terminal: by entering the command:
$ winpty powershell
the result was success ! I got windows powershell propmt on cygwin

then i ran the docker exec command
$ winpty docker run -it ubuntu bash
and it worked !

but now i have some issues with my cygwin installation !
I keep getting " permission denied" error when I tried to
run ' apt-cyg' install command.

i get a permission denied message also when I tried to start a 'Dockerized webserver'
using the command:
docker run -d -p 80:80 --name webserver nginx from cygwi
