### ISSUE TITLE
error pulling

### ISSUE THREAD

**Issue by aakash17** [docker/docker#15197] opened 2015-07-31 09:52 UTC
336ea692b64d: Error pulling dependent layers 
Error pulling image (latest) from greenqloud/varnish-nginx, HTTP code 401
how to resolve it

**Comment by cpuguy83** [comment] 2015-07-31 13:00
Please provided the requested details.
401 == unauthorized, so maybe the image layer is now private? This is of course assuming you have looked at other connectivity issues (such as issues from a proxy server).

**Comment by thaJeztah** [comment] 2015-08-02 13:40
unable to reproduce this issue, pulling this image with docker 1.7.1 worked for me. I suggest checking if there are general connection issues, as @cpuguy83 commented

**Comment by cpuguy83** [comment] 2015-08-17 14:46
Closing since we need more information.
If you can provide repro steps please ping here with the info and we can take a look.
Thanks!

**Closed by cpuguy83** 2015-08-17 14:46 UTC
Labels: status/more-info-needed
