### ISSUE TITLE
Resuming Image Layers Downloads

### ISSUE THREAD

**Issue by zotherstupidguy** [docker/docker#25866] opened 2016-08-19 07:09 UTC
On unstable internet connections `docker pull user\image` fails to download image layers fast enough before connection dropouts, should resume form previously attempted download of each layer by default.

**Comment by thaJeztah** [comment] 2016-09-27 19:48
This was implemented in docker 1.11 (see https://github.com/docker/docker/pull/19840); what version are you running on?

**Comment by zotherstupidguy** [comment] 2016-09-28 16:47
@thaJeztah docker -v returns 1.12.1 build 23cf638

**Comment by thaJeztah** [comment] 2016-09-28 17:10
Thanks @zotherstupidguy, I think there were some (corner) cases where this would still be an issue; perhaps @aaronlehmann or @tonistiigi have more information on that

**Comment by aaronlehmann** [comment] 2016-09-28 17:52
Docker does save layers while it's downloading them, but once you cancel the pull, it deletes those layers to avoid keeping temporary downloads around indefinitely. There have been some requests to keep these temporary files around longer-term so pulls can be resumed later: https://github.com/docker/docker/issues/26146

Do I understand correctly that you're asking for the same thing here?

**Comment by zotherstupidguy** [comment] 2016-09-28 18:14
My case while using an unstable internet connection, I have to try to download each layer and if line drops before a layer is fully downloaded, I HAVE to try to restart its download the next time I am running docker. Thats the case I am having.

**Comment by thaJeztah** [comment] 2016-09-28 18:32
Thanks for the extra info; I think this is a duplicate of https://github.com/docker/docker/issues/26146 then. I'll close this issue so that we can keep the discussion central on https://github.com/docker/docker/issues/26146.

thanks for opening this enhancement  request

**Closed by thaJeztah** 2016-09-28 18:32 UTC
Labels: area/distribution, kind/enhancement
