### ISSUE TITLE
Swarm stack API

### ISSUE THREAD

**Issue by WTFKr0** [docker/docker#31420] opened 2017-02-28 13:48 UTC
Hi
Do you know if there is issue/PR on stack API implementation ?
I can't find it

Today docker cli is doing all work for creating network/services/secrets from a composefile
I imagine a /stack api for listing / updating / remove stacks
It would be awesome for UI tools

Thanx for reading

**Comment by thaJeztah** [comment] 2017-02-28 14:19
The stack deploy feature is currently purely implemented in the client, and uses the regular services API. This may change in future (i.e., make "stacks" a daemon-side feature), but no ETA on that.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-02-28 14:19 UTC
