### ISSUE TITLE
curl cannot save file to data volume folder

### ISSUE THREAD

**Issue by sunshineo** [docker/docker#13117] opened 2015-05-11 08:33 UTC
If a folder is a volume, curl cannot save file to it. ADD local file works

FROM ubuntu:14.10
RUN sudo apt-get update
RUN sudo apt-get install -qq curl
VOLUME /data # If comment this out everything works
WORKDIR /data
RUN curl http://www.google.com > google.txt # This fails to save
RUN pwd
RUN ls # Shows nothing

**Comment by sunshineo** [comment] 2015-05-11 09:00
Description of problem:
In docker file, if a folder is a volume, curl cannot save file to the folder.

`docker version`:
$ docker --version
Docker version 1.4.1, build 5bc2ff8

`docker info`:
$ docker info
Containers: 2
Images: 138
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 142
Execution Driver: native-0.2
Kernel Version: 3.18.5-tinycore64
Operating System: Boot2Docker 1.5.0 (TCL 5.4); master : a66bce5 - Tue Feb 10 23:31:27 UTC 2015
CPUs: 8
Total Memory: 1.961 GiB
Name: boot2docker
ID: 7LUE:WZJL:RTMS:QNDJ:2VLV:6YT5:TDIH:FRFJ:VLVF:XFJK:YEEI:5BVK
Debug mode (server): true
Debug mode (client): false
Fds: 26
Goroutines: 25
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: sunshineo
Registry: [https://index.docker.io/v1/]

`uname -a`:
My Mac
$ uname -a
Darwin MacBook-Pro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
Boot2Docker VM
$ uname -a
Linux boot2docker 3.18.5-tinycore64 #1 SMP Sun Feb 1 06:02:30 UTC 2015 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Mac -> VirtualBox -> Boot2Docker

How reproducible:


Steps to Reproduce:
1. Create a Docker file with following content
FROM ubuntu:14.10
RUN sudo apt-get update
RUN sudo apt-get install -qq curl
VOLUME /data # If comment this out everything works
WORKDIR /data
RUN curl http://www.google.com > google.txt # This fails to save
RUN pwd
RUN ls # Shows nothing
2. docker build -t test/test .


Actual Results:
Step 5 : RUN curl http://www.google.com > google.txt
 ---> Running in c65e0154fade
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17739    0 17739    0     0   136k      0 --:--:-- --:--:-- --:--:--  137k
 ---> 80975ed04d51
Removing intermediate container c65e0154fade
Step 6 : RUN pwd
 ---> Running in d86e1210d0f1
/data
 ---> 9ff7cdad6447
Removing intermediate container d86e1210d0f1
Step 7 : RUN ls # Shows nothing
 ---> Running in 424005d8b6eb
 ---> b2d515930eb6
Removing intermediate container 424005d8b6eb
Successfully built b2d515930eb6

Expected Results:
Step 4 : RUN curl http://www.google.com > google.txt
 ---> Running in 41ae301f8bc3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17731    0 17731    0     0  67907      0 --:--:-- --:--:-- --:--:-- 68196
 ---> 4b2769562ea6
Removing intermediate container 41ae301f8bc3
Step 5 : RUN pwd
 ---> Running in 65219edb3adc
/data
 ---> bc66d9fa2b1a
Removing intermediate container 65219edb3adc
Step 6 : RUN ls # Shows nothing
 ---> Running in 0d912c3221f9
google.txt
 ---> 88de7d62e59c
Removing intermediate container 0d912c3221f9
Successfully built 88de7d62e59c

Additional info:
To get to the expected result, all you need to to is to comment out the command
VOLUME /data # If comment this out everything works

**Comment by sunshineo** [comment] 2015-05-11 09:28
I confirm rm does not work either on data volume

Status: Downloaded newer image for tutum/wordpress-stackable:latest
 ---> e112a0b37471
Step 1 : RUN sudo rm -Rf /app/wp-content/plugins/akismet
 ---> Running in 76c3a46e786c
 ---> 50f80878e3fa
Removing intermediate container 76c3a46e786c
Step 2 : RUN sudo rm /app/wp-content/plugins/hello.php
 ---> Running in b0afb07158c6
 ---> 5fcda5799754

**Comment by phemmer** [comment] 2015-05-11 11:57
This is expected behavior. See https://docs.docker.com/userguide/dockervolumes/

* Changes to a data volume will not be included when you update an image.

**Comment by cpuguy83** [comment] 2015-05-11 12:28
Closing since this is expected (and already captured in a separate issue) behavior.

**Closed by cpuguy83** 2015-05-11 12:28 UTC

**Comment by sunshineo** [comment] 2015-05-11 17:01
Could you provide a link to the other issue?

**Comment by cpuguy83** [comment] 2015-05-11 17:06
#3639
