### ISSUE TITLE
Docker inspect command does not work with task name

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#26441] opened 2016-09-09 09:25 UTC
Docker 1.12.1-beta24 (build: 11525)

`docker service ps db` shows:

```
ID                         NAME  IMAGE                NODE  DESIRED STATE  CURRENT STATE          ERROR
8rtvhdx1jo1dz44zuf9v4e12t  db.1  arungupta/couchbase  moby  Running        Running 7 minutes ago  
```

`docker inspect 8rtvhdx1jo1dz44zuf9v4e12t` works but `docker inspect db.1` gives the error message:

```
[]
Error: No such image, container or task: db.1
```

`docker inspect` should work with both id and name.

**Comment by yongtang** [comment] 2016-09-09 17:31
The issue is the same as #24108 and #24790.

The PR #24850 will fix it and it is being reviewed at the moment.

**Comment by thaJeztah** [comment] 2016-09-15 15:23
closing as duplicate of https://github.com/docker/docker/issues/24790 / https://github.com/docker/docker/issues/24108

**Closed by thaJeztah** 2016-09-15 15:23 UTC
Labels: area/swarm, version/1.12
