### ISSUE TITLE
Docker uses cache and not picking up new changes.  If a link is created to non existing file.

### ISSUE THREAD

**Issue by yevgeniyr** [docker/docker#19686] opened 2016-01-25 22:30 UTC
using Red Hat Enterprise Linux Server release 7.1 (Maipo)
building from nginx 

1) Create following structure
./Dockerfile.nginx <- docker file
./common <- directory
./common/inside_common <- directory
./testdir <- directory
./testdir/newfile <- file

2) cd into ./common/inside_common
and create a link
ln -s ../../nothere nothere

./Dockerfile.nginx  contains

FROM nginx:1.9.9
COPY testdir /usr/share/nginx/html

3) now build the image
4) then create a new file in ./testdir
5) and build the image again <---  Docker will not pick up changes.

**Comment by akatrevorjay** [comment] 2016-01-29 23:58
This was a problem with 1.9.0 release and was fixed in 1.9.1, can you post docker info?

**Comment by thaJeztah** [comment] 2016-01-30 02:18
> there still isn't any public note about this in the 1.9.0 release notes even though I suggested it, unsure as to why?

@tiborvass think we should add a mention of that in the GitHub release notes? It's this issue https://github.com/docker/docker/issues/17290

@yevgeniyr this issue was fixed in Docker 1.9.1; I tried to reproduce (just to be sure) but was not able to.


I'm going to close this issue, because it's been resolved in docker 1.9.1, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-01-30 02:18 UTC
