### ISSUE TITLE
Docker 1.9.1 unable to run container

### ISSUE THREAD

**Issue by awasilyev** [docker/docker#19586] opened 2016-01-22 14:16 UTC
I have a complex app, consisted of ~10 containers.
This containers are configured via env variables, about 15-30 variables per container.
Sometimes container can't start with following message:

failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/50fbd48156f40ea4b72419c869b3f9c390e69a2f0818150542b2c3664a10be8f/shm: invalid argument\nfailed to umount /var/lib/docker/containers/50fbd48156f40ea4b72419c869b3f9c390e69a2f0818150542b2c3664a10be8f/mqueue: invalid argument

after hours of different experiments I found, that broken container can be started if add or remove just one symbol from env variables value. no matter what variable changed, just remove one byte - and it works. if i return deleted symbol - container can't start again.

here is example of config.json from broken container: http://pastebin.com/ZPNa36fn
here is a 'docker export'-et brocker container: http://wasilyev.ru/mq.tar.gz

Downgrading to the docker 1.8.3 fix this situation.

[root@ba0 ~]# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

[root@ba0 ~]# docker info
Containers: 1
Images: 15
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-16830920-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.168 GB
 Data Space Total: 107.4 GB
 Data Space Available: 30.57 GB
 Metadata Space Used: 2.171 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 7.389 GiB
Name: ba0.s22091621.dev.qubell.com
ID: UJNO:KNEN:5BKJ:BBFC:XLVU:UCZR:RJTZ:MJOS:4AYS:F5FN:UQMW:CVCZ

[root@ba0 ~]# uname -a
Linux ba0.s22091621.dev.xxxxxx.com 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

It is centos 7 on aws (ami-61bbf104)

Reproduced several times on different vms.
Steps to reproduce: import container, run it with parameters from config.json
Actual result: containter can't start
Expected result: container up and running

**Comment by wallnerryan** [comment] 2016-01-22 17:12
Hit this same issue on an Amazon AMI just now, for some reason running with devicemapper solved my issue. 

Tried from the below issue.
https://github.com/docker/docker/issues/18967

**Comment by cpuguy83** [comment] 2016-01-22 20:15
The log messages you mentioned are not errors, just messages in the daemon logs that it couldn't cleanup, and that's ok.
Do you have the error message provided from the CLI?
This is eerily similar to #14203

**Comment by awasilyev** [comment] 2016-01-23 06:23
[root@ba0 ~]# docker start mq
Error response from daemon: Cannot start container mq: [8] System error: read parent: connection reset by peer
Error: failed to start containers: [mq]
[root@ba0 ~]#

Jan 23 06:21:10 localhost docker: time="2016-01-23T06:21:10.344047433Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/d39516dfc91ede7ab79750a91b1df7092dc6498a0a171b36d50f7f8e598ac010/shm: invalid argument\nfailed to umount /var/lib/docker/containers/d39516dfc91ede7ab79750a91b1df7092dc6498a0a171b36d50f7f8e598ac010/mqueue: invalid argument"
Jan 23 06:21:10 localhost docker: time="2016-01-23T06:21:10.344088277Z" level=error msg="Error unmounting device d39516dfc91ede7ab79750a91b1df7092dc6498a0a171b36d50f7f8e598ac010: UnmountDevice: device not-mounted id d39516dfc91ede7ab79750a91b1df7092dc6498a0a171b36d50f7f8e598ac010"
Jan 23 06:21:10 localhost docker: time="2016-01-23T06:21:10.344200992Z" level=error msg="Handler for POST /v1.17/containers/d39516dfc91ede7ab79750a91b1df7092dc6498a0a171b36d50f7f8e598ac010/start returned error: Cannot start container d39516dfc91ede7ab79750a91b1df7092dc6498a0a171b36d50f7f8e598ac010: [8] System error: read parent: connection reset by peer"
Jan 23 06:21:10 localhost docker: time="2016-01-23T06:21:10.344223913Z" level=error msg="HTTP Error" err="Cannot start container d39516dfc91ede7ab79750a91b1df7092dc6498a0a171b36d50f7f8e598ac010: [8] System error: read parent: connection reset by peer" statusCode=500

**Comment by thaJeztah** [comment] 2016-01-24 03:07
Yup, I think this is a duplicate of https://github.com/docker/docker/issues/14203

    Error response from daemon: Cannot start container mq: [8] System error: read parent: connection reset by peer

But, thanks to awesome work by Shopify investigating that issue https://github.com/docker/docker/issues/14203#issuecomment-174177790, it looks like we may be able to resolve that issue :+1: 

I'm gonna close this issue, because I think this is a duplicate. Please subscribe to the linked issue (using the "subscribe" button on that page) to stay informed on updates.

Feel free to comment here after I've closed, and thanks so much for reporting!

**Closed by thaJeztah** 2016-01-24 03:07 UTC
