### ISSUE TITLE
flag provided but not defined: --format

### ISSUE THREAD

**Issue by navinas33** [docker/docker#30273] opened 2017-01-19 10:31 UTC
docker ps --format "{{.Names}}"
flag provided but not defined: --format
See 'docker ps --help'.

**Comment by AkihiroSuda** [comment] 2017-01-19 11:35
The flag appeared in 1.8.0 https://github.com/docker/docker/blob/master/CHANGELOG.md#180-2015-08-11

Seems you are using older client?

**Comment by gianarb** [comment] 2017-01-19 11:48
@navinas33 can you give us more info?
Can you copy paste the output of 
```
docker version
```
```
docker info
```
Thanks

**Comment by navinas33** [comment] 2017-01-20 12:45
@ AkihiroSuda 
@gianarb
Thanks for reply ya i use older docker version so that it not supported .
Thanks..

**Comment by thaJeztah** [comment] 2017-01-20 18:33
Le me close this issue, as it's not a bug; for your other question, I suggest asking on forums.docker.com or the Docker community slack channel, which are better suited for that

**Closed by thaJeztah** 2017-01-20 18:33 UTC
Labels: status/more-info-needed
