### ISSUE TITLE
Getting WARNING: bridge-nf-call-iptables is disabled with overlay storage driver 

### ISSUE THREAD

**Issue by alfredcs** [docker/docker#24809] opened 2016-07-19 18:56 UTC
[root@dcosa12 ~]# docker info
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 3
Server Version: 1.12.0-rc4
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 11.43 GiB
Name: dcosa12
ID: XON7:NI34:SW5V:YACY:S7UI:4RJT:YWAJ:PG7W:XG4N:T7NC:AGLK:UQJR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

[root@dcosa12 ~]# uname -a
Linux dcosa12 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@dcosa12 etc]# more centos-release
CentOS Linux release 7.2.1511 (Core) 
[root@dcosa12 etc]#

**Comment by cpuguy83** [comment] 2016-07-19 19:06
This is not related to anything with storage, and is just because either `/proc/sys/net/bridge/bridge-nf-call-iptables` doesn't exist or is set to 0.

Closing since this is not a real issue.
Thanks!

**Closed by cpuguy83** 2016-07-19 19:06 UTC

**Comment by jodumont** [comment] 2016-10-16 18:22
I had this issue : 
Obviously like CPUGuy it's not link to your Device Storage
I run my Docker on CentOS with **SELinux enforcing** and **FirewallD on**
To resolve this _Warning_ I add those two lines info my **/etc/sysctl.conf**
```
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1

```
ref: http://wiki.libvirt.org/page/Net.bridge.bridge-nf-call_and_sysctl.conf

**Comment by frankruizhi** [comment] 2017-04-27 06:40
I solve this problem by execting two commands:
sysctl net.bridge.bridge-nf-call-iptables=1
sysctl net.bridge.bridge-nf-call-ip6tables=1

**Comment by bravist** [comment] 2017-10-12 02:23
@frankruizhi is right, using the command

```bash
$sudo sysctl net.bridge.bridge-nf-call-iptables=1

$sudo sysctl net.bridge.bridge-nf-call-ip6tables=1
```

**Comment by dream-blue** [comment] 2019-04-17 00:41
> execting

hello there executing

**Comment by oangit** [comment] 2020-07-09 07:46
Source: https://docs.oracle.com/en/operating-systems/oracle-linux/docker/issue-iptables-warning.html

This is expected behavior. These settings control whether packets traversing a network bridge are processed by iptables rules on the host system. Typically, enabling these options is not desirable as this can cause guest container traffic to be blocked by iptables rules that are intended for the host. This could cause unpredictable behavior for containers that do not expect traffic to be firewalled at the host level.

If you accept and understand the implications of enabling these options or you have no iptables rules set on the host, you can enable these options to remove the warning messages.

**Comment by matbillo** [comment] 2020-10-19 17:38
Hi!
I get the following docker info 

PS C:\Users\user> docker info
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 1
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 6.092GiB
 Name: docker-desktop
 ID: JVKD:HJXP:DYEM:EEHM:4KEV:VVLI:R56P:ABRQ:YMN7:ZHQE:ZMH6:6CG3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

where could I find the /etc/sysctl.conf in Windows so that I can write the two commands

net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1

Thanks!

**Comment by konstapascal** [comment] 2020-11-20 01:18
@matbillo The docker server and that directory are obviously not on the Windows file system but inside a WSL distribution as you can see from the command output you posted. The distro is called docker-desktop.

The way i reached that config file was by opening command prompt and using `wsl -d docker-desktop` to enter the distro, then `cd /etc` to go to the directory where the file is. From there you can open and edit the file with `vi sysctl.conf`.

Helpful screenshot if you prefer visuals:

![Screenshot_1](https://user-images.githubusercontent.com/49447502/99743757-a1bfc680-2ad6-11eb-942f-2c7d8bf47d7d.png)

**Comment by tobia** [comment] 2022-04-21 13:14
> This is expected behavior. [...] Typically, enabling these options is not desirable [...]

Then what is the correct way to suppress the warnings if one does not want to enable those two options?

**Comment by idc77** [comment] 2024-10-06 13:50
On arch setting the 2 sysctl options to 1 does nothing.
The warnings are still there

**Comment by luckman212** [comment] 2025-04-24 18:08
For me, on Alpine 3.21.3. I had to do:

```bash
cat <<EOF >/etc/sysctl.d/99-docker.conf
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF
```

```bash
echo br_netfilter >> /etc/modules
modprobe br_netfilter
sysctl -p /etc/sysctl.d/99-docker.conf
reboot
```
