### ISSUE TITLE
ONBUILD needs syntax check.

### ISSUE THREAD

**Issue by omeid** [docker/docker#8148] opened 2014-09-20 08:17 UTC
When building an image that has a base with say  `ONBUILD UNICORNS fly` , we get a 
```bash
# Skipping unknown instruction UNICORNS
```
Now this is fine, considering that the instructions are stored in the image manifest and could be changed/corrupted after the base is built.

But that is not enough, I think it makes no sense to allow building an image with invalid `ONBUILD` instructions. 

As such, when building say: 

```Dockerfile
FROM scratch
ONBUILD MAGIC walk
``` 
on build, it should be complaining about `MAGIC`. being an invalid instruction.

**Comment by jfrazelle** [comment] 2015-02-26 01:36
@duglin @tiborvass will this be fixed by the patch to error out https://github.com/docker/docker/pull/10591

**Comment by duglin** [comment] 2015-02-26 17:48
@jfrazelle I can't double-check at the moment, but yes I believe it will be fixed once #10591 is merged.

**Comment by jfrazelle** [comment] 2015-02-26 17:54
perfect no worries, just making sure we didnt leave a dangling issue

**Comment by duglin** [comment] 2015-02-26 18:08
@jfrazelle assigned this one to myself to help ensure I don't forget about it.

**Comment by omeid** [comment] 2015-02-26 21:21
I don't see why this is being added as a Daemon flag while it has little to nothing with it.
Any reason why this isn't added as a build flag?

**Comment by duglin** [comment] 2015-03-01 22:47
@jfrazelle I just confirmed that https://github.com/docker/docker/pull/10591 will generate an error for bad ONBUILD commands

**Comment by duglin** [comment] 2015-03-02 20:48
@omeid a fair number of people don't want the flag at all. Personally, I like having it just as a nicety so that if someone does run into a situation where they have a ton of Dockerfiles that have unknown commands then they can still use them but fix them at their own pace.  But I wouldn't want to force all clients to have to add a new flag to each "docker build" command to get the old behavior. And, yes I do think the default should be to generate an error.

**Comment by duglin** [comment] 2015-03-04 18:02
@omeid I'm going to close this because I think https://github.com/docker/docker/pull/10591 will cover it.  Please reopen it if you think I'm missing something.

**Closed by duglin** 2015-03-04 18:02 UTC
Labels: bug, white-belt
