### ISSUE TITLE
Network-wide container aliases problem

### ISSUE THREAD

**Issue by irsl** [docker/docker#20073] opened 2016-02-06 14:10 UTC
# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

# docker info
Containers: 30
 Running: 13
 Paused: 0
 Stopped: 17
Images: 217
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 293
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.985 GiB
Name: builder
ID: DJQ3:G446:H6DX:GRRV:YTTX:EKUF:HUB2:UFUO:MFVA:G3EB:XPOU:PIAM
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

Let's create two networks:
```
docker network create test1
docker network create test2
```

Then we start two containers on the same network, the second one with an alias to the first:

```
# docker run --rm -it --net=test1 --name=x1 debian:jessie
root@9c92c94fcb6a:/#

# docker run --rm -it --net=test1 --name=x2 --link x1:x1_alias.tld debian:jessie
root@e50820db34a9:/# ping x1
PING x1 (172.28.0.2): 56 data bytes
64 bytes from 172.28.0.2: icmp_seq=0 ttl=64 time=0.262 ms
^C--- x1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.262/0.262/0.262/0.000 ms
root@e50820db34a9:/# ping x1_alias.tld
PING x1_alias.tld (172.28.0.2): 56 data bytes
64 bytes from 172.28.0.2: icmp_seq=0 ttl=64 time=0.084 ms
^C--- x1_alias.tld ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.084/0.084/0.084/0.000 ms
```

Everything works as expected, x2 is able to resolve both x1 and its alias x1_alias.tld.

Then we start another container on the other test network, but still linking to x1:

```
root@builder:/opt/docker# docker run --rm -it --net=test2 --name=x3 --link x1:x1_alias.tld debian:jessie
root@34103bbf751b:/# ping x1
ping: unknown host
root@34103bbf751b:/# ping x1_alias.tld
ping: unknown host
```

This is still reasonable, since they are on different networks.
But then we connect x3 to test1 network in the background:

```
docker network connect test1 x3
```

x1 becomes available for x3 immediately:

```
root@34103bbf751b:/# ping x1
PING x1 (172.28.0.2): 56 data bytes
64 bytes from 172.28.0.2: icmp_seq=0 ttl=64 time=0.163 ms
^C--- x1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.163/0.163/0.163/0.000 ms
```

But x3 is still not able to resolve the alias: x1_alias.tld 

```
root@34103bbf751b:/# ping x1_alias.tld
ping: unknown host
```

Is this by design or a bug?

**Comment by mavenugo** [comment] 2016-02-06 16:33
@irsl This is not a bug. Couple of things to point out here.

1. `--link` is not a `Network-wide container alias`. Link is a container-scoped alias for a `parent` container and is bound to a network. So, when you run `docker run --rm -it --net=test1 --name=x2 --link x1:x1_alias.tld debian:jessie`, the alias `x1_alias.tld` is scoped to container x2 and  bound to network `test1`.
2. If you want a similar alias to work for container `x3` in network `test1`, then you must use the `--link` option in `docker network connect  --link x1:x1_alias.tld test1 x3`. This will enable the alias `x1_alias` to work for container x3 in network `test1`.

If you truly want a `Network-wide` alias, then you must use the `--net-alias`  in `docker run` or `--alias` in `docker network connect`. So in your case, it would be `docker run --rm -it --net=test1 --name=x1 --net-alias=x1_alias.tld debian:jessie`. This will make the alias `x1_alias.tld` available to all the containers in network `test1` automatically.

Please refer to the documentation for more information : https://github.com/docker/docker/blob/master/docs/userguide/networking/work-with-networks.md#network-scoped-alias

**Comment by mavenugo** [comment] 2016-02-06 16:35
will close the issue now. pls feel free to open if you still have a question on link vs alias.

**Closed by mavenugo** 2016-02-06 16:35 UTC
Labels: group/networking
