### ISSUE TITLE
Docker breaks autofs directory in V1.5, used to work in V1.3.3

### ISSUE THREAD

**Issue by christina57** [docker/docker#13376] opened 2015-05-21 04:56 UTC
Today I tried to install and start Docker 1.5. It works at the beginning. Then after about 1 hour, I cannot access autofs directories on the host any more. Get error "Too many levels of symbolic links.". And I cannot do unlink and relink autofs directories for some reason. So no way out now.

$ cd /usr/local/packages/
/usr/local/packages/: Too many levels of symbolic links.

Anyone get similar issue?

And I used Docker version 1.3.3 for several months. It works perfectly. So any change after 1.3.3 may causing this issue?

BTW, I cannot find a older version Docker rpm. If you have one, please let me know. Thanks.

**Comment by thaJeztah** [comment] 2015-05-23 18:38
@christina57 could you provide the information that's requested above, and if possible a way to reproduce? The current version is docker 1.6.2, so it might be worth checking if the issue is resolved on that release as well

**Comment by sudhanshu-garg** [comment] 2015-06-29 18:40
I am running into exactly the same issue when using Docker 1.6.2

**Comment by kipz** [comment] 2015-07-03 09:04
Me too:

kernel: 3.8.13-16.2.1.el6uek.x86_64
docker: 1.6.2

Restarting the docker daemon seems to temporarily resolve the issue (as does a reboot of course).

**Comment by garthy** [comment] 2015-07-03 10:13
This is because of an unshare in the init script that starts docker. 
Not sure why it is there. 

Change the line 

 "$unshare" -m -- $exec -d $other_args &>> $logfile &

to 

$exec -d $other_args &>> $logfile &

**Comment by thaJeztah** [comment] 2015-07-03 13:43
@garthy I see that was changed in https://github.com/docker/docker/pull/10225

@vbatts are you able to have a look here? It looks like you needed to add that comment to the script after all (https://github.com/docker/docker/pull/10225#issuecomment-70735962) :wink:

**Comment by garthy** [comment] 2015-07-03 14:06
Using unshare means docker can't access any FS mounted after docker starts.

**Comment by garthy** [comment] 2015-07-03 14:09
This thread is describes why it happens

http://lists.wpkg.org/pipermail/autofs/2014-March/000454.html

**Comment by vbatts** [comment] 2015-07-06 20:58
i see how that is the case, though there are reasons needing the daemon's mount namespace to be unshared. for your usecase, you could just update the init script to not unshare.

**Comment by thaJeztah** [comment] 2015-07-06 21:26
@christina57 I'm going to close this issue because this was changed on purpose (as can be read in https://github.com/docker/docker/pull/10225) and helped solved many cases where the old behavior caused problems.

To revert to the old behavior, you can change the init scripts (as suggested), which should get you what you want.

I'm sorry for the inconvenience this has caused you, but, given that this (to my knowledge) is the first time this was reported, this is really a corner case.

Thanks for reporting this, it's much appreciated. If you encounter other issues when working with Docker, don't hesitate to report them!

**Closed by thaJeztah** 2015-07-06 21:26 UTC

**Comment by garthy** [comment] 2015-07-07 10:53
I'm not sure this is a really corner case and it's not fixed so why close?
It's was actually quite hard to track the symptoms down to docker involving cloning of processes with CLONEFS. 

The work around just brings back other broken behaviour.

It causes two issues.

1) It breaks Volumes mounted by AutoFS when docker starts.
2) It also stops being able to mount any volume mounted after docker starts.

These are two behaviours that have been introduced to work around another issue with mount name spaces. 

A fix would be for docker to not use unshare but spawn a small helper that does use CLONEFS which then pivot_root to a private root to drop all mount points. This small helper process that could do mount and launch of processes not polluting the global namespaces while not holding onto mounts from the global namespace it doesn't care about.

**Comment by thaJeztah** [comment] 2015-07-07 12:22
@garthy the reason I think this can be closed, is that the original issue describes "used to work in V1.3.3", and the discussion above explains how the old behavior can be restored by changing the init-scripts and reverting the changes in https://github.com/docker/docker/pull/10225.

*However*, based on your comment, it looks like you have given this some thought already and have ideas how the current situation can be improved.

Would you be interested in rewriting your comment above into a "proposal"? That way it can be discussed separately and we can see if there's interest in making that change.

**Comment by vbatts** [comment] 2015-07-07 13:20
@rhvgoyal are you in brainstorming a feature to push the mount namespace all the way to `docker run ...` ?

**Comment by gratiartis** [comment] 2016-02-29 09:18
I don't suppose there's a workaround for Debian / Ubuntu? The `unshare` in the init script relates to the `sysvinit-redhat` init script. As far as I can tell, the `sysvinit-debian` init script doesn't contain an `unshare`;  just a call to `start-stop-daemon`, which seems to invoke an executable.

Alternatively, is there a more docker-friendly mechanism for connecting to remote Windows shares?

**Comment by rhvgoyal** [comment] 2016-02-29 15:58
Have not gone through the whole thread but I think with volume propagation patches in 1.10, it should be possible to access autofs mounts inside container. Say autofs volumes are under /mnt. Then following should work.

- Make sure source mount dir is shared.
$ mount --make-shared /mnt

- Launch container with slave volume

$ docker run -ti -v /mnt:/volumes:slave fedora bash

Now when container steps into /volumes/foo then /mnt/foo should get mounted and be visible inside container.
