### ISSUE TITLE
{"message":"json: cannot unmarshal string into Go value of type []string"}

### ISSUE THREAD

**Issue by erxian** [docker/docker#27573] opened 2016-10-20 03:07 UTC
I use Docker Remote API to create container, the command is: 
`curl -XPOST -H "Content-Type: application/json"  http://0.0.0.0:4243/containers/create -d '{
 "Hostname":"", 
     "User":"", 
     "Memory":0, 
     "MemorySwap":0, 
     "AttachStdin":false, 
     "AttachStdout":true, 
     "AttachStderr":true, 
     "PortSpecs":null, 
     "Privileged": false, 
     "Tty":false, 
     "OpenStdin":false, 
     "StdinOnce":false, 
     "Env":null, 
     "Dns":null, 
     "Image":"ubuntu", 
     "Volumes":{}, 
     "VolumesFrom":"", 
     "WorkingDir":"" 
}'`

but it returns the error _{"message":"json:** cannot unmarshal string into Go value of type []string"}_, my docker version info is ：
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

**Comment by justincormack** [comment] 2016-10-20 10:39
That error means it is expecting an array not a string. I think the culprit is `VolumesFrom` which should take a list of volumes, see the API spec https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/

**Comment by thaJeztah** [comment] 2016-10-21 07:23
Looks like there's an error in the JSON you're sending, as @justincormack mentioned. This is not a bug, so I'll close this issue, but feel free to continue the discussion

**Closed by thaJeztah** 2016-10-21 07:23 UTC
Labels: kind/question, version/1.12
