### ISSUE TITLE
Error when try to start nginx container (Bind for 0.0.0.0:80 failed: port is already allocated.)

### ISSUE THREAD

**Issue by Furdarius** [docker/docker#25877] opened 2016-08-19 10:21 UTC
**Output of `docker version`:**

```bash
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```bash
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 96
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 265
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.698 GiB
Name: flaker-Lenovo-G580
ID: MJHR:SASW:4PLV:Z6UN:2CGY:UYUX:PNMK:GR4A:UMT4:QMAL:N553:QMT3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: furdarius
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Native on Ubuntu 16.04.1

**Steps to reproduce the issue:**

This behavior appears after updating docker-engine on 1.12.1

1. After starting the OS *docker-proxy* listen 80 and 443 ports (IS IT RIGHT BEHAVIOR???)

```bash
$ sudo netstat -nlp | grep 80
tcp6       0      0 :::80                   :::*                    LISTEN      5059/docker-proxy
$ sudo netstat -nlp | grep 443
tcp6       0      0 :::443                  :::*                    LISTEN      4901/docker-proxy
```
2. So, when i try to start nginx, get error:

```bash
$ docker run -d -p 80:80 nginx:lateste5649c0a87d8b65a453dad0d6ed1d47333d8b12ddfe69d1069efac5a2d71a305
docker: Error response from daemon: driver failed programming external connectivity on endpoint loving_shockley (19e43dd9ead43ab52bd15e548d3f9fd62d88955da2acff50b92316306245fdee): Bind for 0.0.0.0:80 failed: port is already allocated.
```
3. Okay, let's try to kill *docker-proxy*
4. Now, ports (80 and 443) aren't listening
```bash
$ sudo netstat -nlp | grep 443
$ sudo netstat -nlp | grep 80
```
5. But, when i trying to start nginx again, same result
```bash
$ docker run -d -p 80:80 nginx:latest
70e5868169349d1f0a25f54d08e37f7f80f36cc8ad5ce30eae5c0e5808b15027
docker: Error response from daemon: driver failed programming external connectivity on endpoint sharp_bose (70766b94e756ead0efafd508a6465cb00267a942318db78e6398d5a966834d24): Bind for 0.0.0.0:80 failed: port is already allocated.
```

**Comment by tusuzu** [comment] 2016-08-21 07:01
I upgraded Discourse today, which included an upgrade for Docker.
Discourse is running on a DigitalOcean droplet, with Ubuntu 14.04.
Now cannot access this Discourse forum due to 502 Bad Gateway nginx error. This forum is down.
The/var/log/nginx/error.log message says My error log shows that the docker-proxy is already listening on port 80, so nginx can't start.
[emerg] 21412#0: bind() to 0.0.0.0:80 failed (98:Address already in use)

**Comment by trunneml** [comment] 2016-08-21 13:48
Same here. Since the docker update port 80 and 443 are used. netstat shows docker-proxy on both ports.

**Comment by trunneml** [comment] 2016-08-21 14:01
Same problem here. Can't start nginx container. netstat shows docker-proxy is already listening on port 80 and port 443.

[root@server2 system]# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Comment by thaJeztah** [comment] 2016-08-21 14:17
docker-proxy should only be using that port if there's a service (on any host), or container that published that port, do you have any container or service running (or a stopped / exited container) that publishes port 80/443?

**Comment by trunneml** [comment] 2016-08-21 14:27
No removed all containers (exept stoped data containers). docker-proxy only runs on tcp6.

[root@server2 system]# netstat -lnp | grep docker
tcp6       0      0 :::80                   :::*                    LISTEN      26531/docker-proxy
tcp6       0      0 :::443                  :::*                    LISTEN      26524/docker-proxy

**Comment by trunneml** [comment] 2016-08-21 14:31
Downgrade to docker 1.11.2 didn't help. Any idea?

**Comment by trunneml** [comment] 2016-08-21 14:34
Tried to start an apache httpd, same problem. So I don't think it is only a nginx problem.

**Comment by trunneml** [comment] 2016-08-21 14:51
Managed to reinstall 1.12.0 and container starts without a problem now. I added 0.0.0.0 to the port binding and the container started again. I didn't try 1.12.1 because my system is working now.

**Comment by tusuzu** [comment] 2016-08-21 16:50
Michael,

To recap, you

rolled back to Docker 1.11.2,

reinstalled 1.12.0 (not 1.12.1),
added 0.0.0.0 to the port binding,
retarted your system,

and everything is working now?

**Comment by trunneml** [comment] 2016-08-24 15:13
@tusuzu 

Yes that's what I did. Even an upgrade to 1.12.1 worked yesterday. I think there is some kind of deadlock/corner case in the upgrade process or something like that.

**Comment by netroby** [comment] 2016-08-26 08:12
Had the same issue

**Comment by cpuguy83** [comment] 2016-08-26 14:27
ping @justincormack

**Comment by foxos42** [comment] 2016-09-07 09:51
same here:
```
docker -v
Docker version 1.12.1, build 23cf638

docker ps -a
<empty>

netstat -tulpen | grep docker
tcp6 0 0 :::443 :::* LISTEN 0 73786 27279/docker-proxy
```
try:
- "--userland-proxy=false" at dockerd   -> dockerd then bind 443
- purge and reinstall of docker-engine
- trunneml's method   -> the problem appears with version 1.12.0

On another machine, same hardware, same docker version, same containers, no docker-proxy at all.

**Comment by foxos42** [comment] 2016-09-07 10:23
In my case this was the problem:
`/var/lib/docker/network/files/local-kv.db`:
```
{"Addr":"172.18.0.4/16","Config":{"MacAddress":null},"ContainerConfig":null,"ExternalConnConfig":
{"PortBindings":[{"Proto":6,"IP":"","Port":3000,"HostIP":"","HostPort":443,"HostPortEnd":443}],"ExposedPorts":
[{"Proto":6,"Port":3000}]},"MacAddress":"02:42:ac:12:00:04","PortMapping":
[{"Proto":6,"IP":"172.18.0.4","Port":3000,"HostIP":"0.0.0.0","HostPort":443,"HostPortEnd":443}],
"SrcName":"vethe1ee9c1","id":"c099e0880287083ba2a9678a915b72efca997db86d8b7f2d695b21d4dd68b204",
"nid":"3543e5b37785cf766e387b41a30ed1c3ca8305504eee65655da8480d1bb19858"}docker/network/v1.0/bridge/00ef1612b73778e777b02e64df27961f514bd0467c70cb3ab53dea3e99ea921e/
```
Remains of an old dead container. Removed it. Problem gone.

**Comment by justincormack** [comment] 2016-09-22 08:43
Can other people check if they had the same issue as @foxos42 - an old kv db - it seems like certainly one way this could happen.

**Comment by ianneub** [comment] 2016-09-29 20:00
@justincormack I am also experiencing this issue. There is an entry in `/var/lib/docker/network/files/local-kv.db` that mentions the `"HostPort":80` (the same port I can no longer launch new containers on.

Is there a procedure to cleaning up the `/var/lib/docker/network/files/local-kv.db` file? Is it safe to simply delete with running containers?

**Comment by foxos42** [comment] 2016-09-30 09:07
@ianneub 
My rough procedure:
- run containers on another machine
- purge docker-engine
- removed /var/lib/docker
- reinstalled docker-engine

Hope there is a softer one. ;)

**Comment by alirezaDavid** [comment] 2016-10-08 06:31
same problem here.
I removed all container (even stop container) and didn't work.

**Comment by Luzifer** [comment] 2016-10-13 10:28
Same problem here…

# What I saw at my host

```bash
# uname -a
Linux docker01 3.13.0-98-generic #145-Ubuntu SMP Sat Oct 8 20:13:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

# docker info
Containers: 47
 Running: 47
 Paused: 0
 Stopped: 0
Images: 111
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1431
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-98-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.29 GiB
Name: docker01
ID: QE6C:ZNQX:BADL:4BTY:7AK5:274U:7B7N:EUS7:FGYI:TE5Q:JPXI:FBK6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

## Error on starting container
```
driver failed programming external connectivity on endpoint lightpos (6580229bcb52c7a1506930546b1f0db371e28e2c58e7670906a142ee845085f4): Bind for 0.0.0.0:1330 failed: port is already allocated
```

## Searching for the ports
```bash
# netstat -tulpen | grep 1330
tcp6       0      0 :::1330                 :::*                    LISTEN      0          38316       17452/docker-proxy
```

Looked up what is answering (web browser) on that port, found a container which should be listening on another port:

```bash
# netstat -tulpen | grep 1240
tcp6       0      0 :::1240                 :::*                    LISTEN      0          3008270     24795/docker-proxy
```

```json
            "Ports": {
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "1240"
                    }
                ]
            },
```

Only port-binding for that container is `1240` but it answers on `1330` and `1240`…

## Trying to solve

- Kill docker-proxy on that port `kill 17452`
  - Container still answers on port `1330`
- Try to start hanging container `docker start lightpos`
  - Still above mentioned error
- Restart container with wrong bind `docker restart planbac`
  - It still answers on `1240` and `1330`
- Remove container entirely and create it again `docker rm -f planbac` (create executed via API)
  - Still not able to start container because of above error
- Stop every container, remove it, restart docker  
`docker ps -a | awk '{print $1}' | xargs docker rm -f && restart docker`
  - Port binds cleared, all containers listening on their own configured ports (create executed via API)

**Comment by justincormack** [comment] 2016-10-13 11:29
@Luzifer interesting. Can you look at the `docker-proxy` arguments when this is happening? (`ps auxww | grep proxy` should show them). Is there anything else unusual about the container that has listening on the wrong port? Has it been restarted before or anything?

**Comment by Luzifer** [comment] 2016-10-13 11:35
Will do as soon as I do have the issue again… (Probably next time when Ubuntu pushes updates requiring reboot…)

**Comment by aboch** [comment] 2016-10-13 16:02
@ianneub

> Is there a procedure to cleaning up the /var/lib/docker/network/files/local-kv.db file? Is it safe to simply delete with running containers?

It is safe to delete if you did not start the daemon with --live-restore.
But be aware it would remove all the local scope networks. You would need to recreate them.

@Luzifer 
I am not sure the requests being sent to the wrong container (This was reported in another issue as well) is related to the phantom mapped port issue reported here.

When that happens, can you take a look at the conntrack table if there is any corresponding entry for that wrong flow. If you can experiment on the host, you can also try flush the whole table
with `conntrack -F`

**Comment by aboch** [comment] 2016-10-18 23:15
With all likelihood the issue discussed here is the same being discussed in #25981.
This one was opened first, but I happened to add a comment about what I think is the root cause with some workarounds to try in that issue instead. 
So I am suggesting to close this one as duplicate of #25981.

**Comment by thaJeztah** [comment] 2016-10-19 01:15
Thanks for looking into the @aboch and thanks for reporting @Furdarius (and others). I'll close this as a duplicate of https://github.com/docker/docker/issues/25981 so that the discussion takes place in a single location

**Closed by thaJeztah** 2016-10-19 01:15 UTC
Labels: area/networking, kind/bug, version/1.12
