### ISSUE TITLE
Basic volume mount fails with windows docker client

### ISSUE THREAD

**Issue by Avinash-Setty** [docker/docker#21253] opened 2016-03-16 14:03 UTC
I'm just trying to do the most basic volume mount. Something like.... Can anyone help to resolve this issue?

```
avina@avinash-laptop MINGW64 ~
$ ll /c/development/phase2/Experiments/SimpleApp/src/SimpleApp
total 872
-rw-r--r-- 1 avina 197611    412 Mar 15 17:44 appsettings.json
-rw-r--r-- 1 avina 197611    207 Mar 15 17:43 bower.json
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Controllers/
-rw-r--r-- 1 avina 197611   1249 Mar 15 17:43 gulpfile.js
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Migrations/
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Models/
drwxr-xr-x 1 avina 197611      0 Mar 15 17:43 node_modules/
-rw-r--r-- 1 avina 197611    213 Mar 15 17:43 package.json
-rw-r--r-- 1 avina 197611   1809 Mar 15 17:44 project.json
-rw-r--r-- 1 avina 197611 840603 Mar 15 17:50 project.lock.json
-rw-r--r-- 1 avina 197611   7006 Mar 15 17:43 Project_Readme.html
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Properties/
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Services/
-rw-r--r-- 1 avina 197611   1332 Mar 15 17:43 SimpleApp.xproj
-rw-r--r-- 1 avina 197611    241 Mar 15 18:05 SimpleApp.xproj.user
-rw-r--r-- 1 avina 197611   3928 Mar 15 17:44 Startup.cs
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 ViewModels/
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Views/
drwxr-xr-x 1 avina 197611      0 Mar 15 17:43 wwwroot/

avina@avinash-laptop MINGW64 ~
$ docker run -v /c/development/phase2/Experiments/SimpleApp/src/SimpleApp:/SimpleApp -p 5000:5000 -it microsoft/aspnet
root@112446af63af:/# cd SimpleApp/
root@112446af63af:/SimpleApp# ls -al
total 4
drwxr-xr-x  2 root root   40 Mar 16 13:36 .
drwxr-xr-x 60 root root 4096 Mar 16 13:36 ..
root@112446af63af:/SimpleApp# exit
```

Using Docker version 1.10.3, build 20f81dd
Windows Client / Boot2Docker Host

**Comment by HackToday** [comment] 2016-03-17 01:39
Not sure if what's your MINGW64 environment look like ? is it a VirtualBox VM on WIndows?

Check this issue if same 
https://github.com/docker/docker/issues/19111

**Comment by thaJeztah** [comment] 2016-03-18 12:30
This is expected; by default, only the c:\Users directory is shared with the Virtual Machine that the daemon runs on. Anything outside c:\Users is not shared, so not accessible. See https://github.com/boot2docker/boot2docker#folder-sharing

Hope that answers your question.

I'll close this issue, because this is not a bug, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-03-18 12:30 UTC

**Comment by Avinash-Setty** [comment] 2016-03-18 18:11
I tried again mounting by moving the sample project to C:/Users folder, still I am getting the same issue. I am not sure what I am missing,

`$ docker run -v /C/Users/avina/Desktop/Experiments/SimpleApp/src/SimpleApp:/Doc
kerWebApp -p 5000:5000 -it microsoft/aspnet
root@1471ceec9e02:/# cd DockerWebApp/
root@1471ceec9e02:/DockerWebApp# ls
root@1471ceec9e02:/DockerWebApp# ls -al
total 4
drwxr-xr-x  2 root root   40 Mar 18 18:08 .
drwxr-xr-x 60 root root 4096 Mar 18 18:08 ..
root@1471ceec9e02:/DockerWebApp#`

**Comment by Avinash-Setty** [comment] 2016-03-18 18:13
Code was not formatted properly, I pasting this code again here,

`
$ docker run -v /C/Users/avina/Desktop/Experiments/SimpleApp/src/SimpleApp:/Doc
kerWebApp -p 5000:5000 -it microsoft/aspnet
root@cb6db732d618:/# cd DockerWebApp/
root@cb6db732d618:/DockerWebApp# ls -al
total 4
drwxr-xr-x  2 root root   40 Mar 18 18:08 .
drwxr-xr-x 60 root root 4096 Mar 18 18:12 ..
root@cb6db732d618:/DockerWebApp#
`

**Comment by Avinash-Setty** [comment] 2016-03-18 18:14
```

$ docker run -v /C/Users/avina/Desktop/Experiments/SimpleApp/src/SimpleApp:/Doc
kerWebApp -p 5000:5000 -it microsoft/aspnet
root@cb6db732d618:/# cd DockerWebApp/
root@cb6db732d618:/DockerWebApp# ls -al
total 4
drwxr-xr-x  2 root root   40 Mar 18 18:08 .
drwxr-xr-x 60 root root 4096 Mar 18 18:12 ..
root@cb6db732d618:/DockerWebApp#
```

**Comment by thaJeztah** [comment] 2016-03-18 18:24
Looking at your first comment, it looks like you're running boot2docker, which is in a VM. If you `docker inspect` that container, can you see if it the volume-paths are properly set?

**Comment by Avinash-Setty** [comment] 2016-03-18 18:29
I am getting below output,

```
$ docker inspect
docker: "inspect" requires a minimum of 1 argument.
See 'C:\Program Files\Docker Toolbox\docker.exe inspect --help'.

Usage:  docker inspect [OPTIONS] CONTAINER|IMAGE [CONTAINER|IMAGE...]

Return low-level information on a container or image
```

**Comment by Avinash-Setty** [comment] 2016-03-18 18:30
```
$ docker inspect microsoft/aspnet
[
    {
        "Id": "sha256:3f9fb7bae5fa5328a9c7a539dca80e9e47b0604cb7c4b4b4eecc270f24364def",
        "RepoTags": [
            "microsoft/aspnet:latest"
        ],
        "RepoDigests": [],
        "Parent": "",
        "Comment": "",
        "Created": "2016-03-15T05:18:19.834673264Z",
        "Container": "f60595fadc9c245d37b2e4cca66eed433f8f95ae10a2e36bdfad28a107859d63",
        "ContainerConfig": {
            "Hostname": "f259a376263c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/dnx/runtimes/default/bin",
                "DNX_VERSION=1.0.0-rc1-update1",
                "DNX_USER_HOME=/opt/dnx",
                "DNX_RUNTIME_ID=ubuntu.14.04-x64",
                "MONO_THREADS_PER_CPU=50"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ENV MONO_THREADS_PER_CPU=50"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:c8e2c3e2cf64203418d12a1a6a150d014577ed6f9ed5fa8d1a84efc049e0d5ed",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.10.2",
        "Author": "",
        "Config": {
            "Hostname": "f259a376263c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/dnx/runtimes/default/bin",
                "DNX_VERSION=1.0.0-rc1-update1",
                "DNX_USER_HOME=/opt/dnx",
                "DNX_RUNTIME_ID=ubuntu.14.04-x64",
                "MONO_THREADS_PER_CPU=50"
            ],
            "Cmd": [
                "/bin/bash"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:c8e2c3e2cf64203418d12a1a6a150d014577ed6f9ed5fa8d1a84efc049e0d5ed",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 815162360,
        "VirtualSize": 815162360,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        }
    }
]
```

**Comment by Avinash-Setty** [comment] 2016-03-18 18:38
```
$ docker inspect 2e923fe43afd
[
    {
        "Id": "sha256:2e923fe43afd6d9aaa670643bc8a3bd859fd440d21aa5520921f03b30b2d5064",
        "RepoTags": [],
        "RepoDigests": [],
        "Parent": "sha256:ff320dff9ee814c5c5234e0fb7efbfc78e60c79d0e8d6d1fe575c011bb0c34f1",
        "Comment": "",
        "Created": "2016-03-15T20:00:52.417534899Z",
        "Container": "2ed47c95f3838a288a655aae16c4777a980f979b344c4f0d1303a0cdaa494977",
        "ContainerConfig": {
            "Hostname": "f259a376263c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5004/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/dnx/runtimes/default/bin",
                "DNX_VERSION=1.0.0-rc1-update1",
                "DNX_USER_HOME=/opt/dnx",
                "DNX_RUNTIME_ID=ubuntu.14.04-x64",
                "MONO_THREADS_PER_CPU=50"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ENTRYPOINT \u0026{[\"dnx\" \"kestrel\"]}"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:ff320dff9ee814c5c5234e0fb7efbfc78e60c79d0e8d6d1fe575c011bb0c34f1",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "dnx",
                "kestrel"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.10.3",
        "Author": "",
        "Config": {
            "Hostname": "f259a376263c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5004/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/dnx/runtimes/default/bin",
                "DNX_VERSION=1.0.0-rc1-update1",
                "DNX_USER_HOME=/opt/dnx",
                "DNX_RUNTIME_ID=ubuntu.14.04-x64",
                "MONO_THREADS_PER_CPU=50"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "sha256:ff320dff9ee814c5c5234e0fb7efbfc78e60c79d0e8d6d1fe575c011bb0c34f1",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "dnx",
                "kestrel"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1310378065,
        "VirtualSize": 1310378065,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        }
    }
]
```
