### ISSUE TITLE
FOR REFERENCE :: ENV evaluation anomalies (shell/bash)

### ISSUE THREAD

**Issue by blaggacao** [docker/docker#10503] opened 2015-02-02 03:16 UTC
I just run over a rather undokumented behaviour from a docker ecosystem viewpoint.
I needed to figure out, how ENV are processed (if in single or double quoted notion by default, which implies caution about escaping.)

So I would love to see a hint on the docs to clarify the point.
http://docs.docker.com/reference/builder/#env

***Suggestion:***
"ENV are processed in the double quoted notion by default which makes strings subject to shell escaping acording to the shell used in the target image. You can use the alternative declaration with single quotes instead."

**Comment by blaggacao** [comment] 2015-02-02 04:25
Still there is strange behaviour:
```
ENV CLEANUP="apt-get autoremove && apt-get clean"
RUN $CLEANUP
```
breakes with: ```/bin/sh: 1: "apt-get=autoremove: not found```
```
ENV CLEANUP apt-get autoremove && apt-get clean
RUN $CLEANUP
 ```
breakes with 
```
Unable to locate package &&
Unable to locate package apt-get
Unable to locate package clean
```

**Comment by duglin** [comment] 2015-02-02 16:18
I'm not seeing the exact same results when I try it but I do see that the env var substitution is happening _after_ we break things up into words.  @erikh seems like we could do the env var processing prior to the splitting and then it might solve this.  Haven't tried it out yet, but if that does seem to work (w/o breaking stuff) does that seem ok to you?

**Comment by blaggacao** [comment] 2015-02-02 20:22
As to:
>`ENV CLEANUP="apt-get autoremove && apt-get clean"`
>`RUN $CLEANUP`
>breakes with: `/bin/sh: 1: "apt-get=autoremove: not found`

It seemd that I've been on an old CoreOS with docker 1.2.0 (I didn't think it was possible to be on an old CoreOS, but it was newl spun up and based on an old image). Sry.

The second part still holds true on 1.4.1, and I could not figure out why.. Somehow `&&` and all that follow get's interpreted as a arguement to `apt-get install` and looses it's special meaning. This is awkward and not fully transparent behaviour of `ENV`. Thanks @duglin for picking this up.

**Comment by erikh** [comment] 2015-02-02 21:22
In this case I’m pretty sure it’s becasue ENV FOO=bar isn’t supported right now and you’re seeing a bug in the parser.

@duglin I think 1.5 will fix this.

-Erik

**Comment by duglin** [comment] 2015-02-02 21:31
@erikh part of it yes, but I do see an issue even in v1.5.  The word splitting is happening before we do the env var replacement, which means for this Dockerfile:
```
FROM ubuntu
ENV CLEANUP echo hi && echo bye
RUN $CLEANUP
RUN echo hi && echo bye
```
You'll see:
```
 ---> Running in a3bb6eaf8e41
hi && echo bye
...
 ---> Running in c110bd1fcd23
hi
bye
```
Notice the first echo didn't treat the && properly.  I think doing the env var substitution prior to running the cmd-specific parser (except for ENV) should fix this.
thoughts?

**Comment by erikh** [comment] 2015-02-02 21:41
We’re not doing ENV replacement there though; we’re passing $CLEANUP directly to RUN, as it’s blacklisted from env replacement.

Looking at the code now, however.

-Erik

**Comment by blaggacao** [comment] 2015-02-03 00:45
Useful Entropy to the Problem: :+1:

```
localhost ~ # docker run -ti --rm 603e7d3657de /bin/sh
$ export CLEANUP="echo hi && echo bye"
$ $CLEANUP
hi && echo bye
$

```

**Comment by blaggacao** [comment] 2015-02-03 01:21
`/bin/bash` does cuase problems as well... This definitively looks like a more basic thing about shells. So maybe we could only isolate the root cause and document it better...
```
$ export CLEANUP='/bin/bash -c "echo \"hi\" && echo \"bye\"";'
$ $CLEANUP
\"hi\": -c: line 0: unexpected EOF while looking for matching `"'
\"hi\": -c: line 1: syntax error: unexpected end of file
$ echo $CLEANUP
/bin/bash -c "echo \"hi\" && echo \"bye\"";
$ /bin/bash -c "echo \"hi\" && echo \"bye\"";
hi
bye
```

**Comment by duglin** [comment] 2015-02-03 02:51
What's odd is that as I was testing this I could have sworn that I got it to do the substitution and then deal with the && properly but I guess I was mistaken since I can't reproduce it now.  If this really is just a shell thing then I'm not sure we need to say anything about it in the docs - I'm not keen on repeating sh/bash documentation.  At least not unless we think this is really a common situation that people will hit often, which I don't think it is.

**Comment by erikh** [comment] 2015-02-03 04:23
+1 to leaving this alone. Example:

```
[61] erikh@devenv ~% foo="echo this && echo works"
[62] erikh@devenv ~% sh -c "$foo"
this
works
```

I’m not sure where this anomaly comes from. Let’s leave this ticket open so that others can comment on it if it becomes a problem for them too.

**Comment by blaggacao** [comment] 2015-02-03 06:01
:+1: thanks.

**Comment by blaggacao** [comment] 2015-02-03 06:20
Adding some search tags in the hope it auments the persistent usefulness of this issue.
environment variables evaluation problem anomaly chaining && command shell bash

**Comment by tianon** [comment] 2015-02-03 06:30
You can also use `eval`:
```console
$ docker run -it --rm busybox
/ # a='echo hi && echo bye'
/ # eval "$a"
hi
bye
```

**Comment by LK4D4** [comment] 2016-09-14 21:49
Going to close this because it's not active. Feel free to open new issue.

**Closed by LK4D4** 2016-09-14 21:49 UTC
Labels: area/docs, exp/beginner, kind/enhancement
