### ISSUE TITLE
Strange behaviour with overlay network and AWS

### ISSUE THREAD

**Issue by adamlc** [docker/docker#21926] opened 2016-04-11 10:32 UTC
I seem to be having a weird issue with my overlay network on AWS. I created an overlay network with the range 192.168.0.0/16, which is working great! But for some reason when a container gets assigned the IP `192.168.0.21` nothing can communicate with it, it doesn't seem to make a difference what server its on in the docker swarm. I'll be honest I don't really know here to begin debugging this or how to replicate this. Can anyone help? This could be fixed on 1.10 but AWS are still on 1.9.1 😢 

**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
Images: 112
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-263652-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.876 GB
 Data Space Total: 107.4 GB
 Data Space Available: 44.78 GB
 Metadata Space Used: 8.409 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.17-22.30.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
CPUs: 2
Total Memory: 3.862 GiB
Name: swarm-node-eu-west1-1c-1
ID: F5EH:BZNO:6HR5:MSTB:EYE3:MPBD:GKRX:RM7J:OSIB:ALF7:C4YU:C3RR
Cluster store: consul://127.0.0.1:8500
Cluster advertise: 10.0.2.26:2375
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
We're on an AWS VPC in EU-West1

**Comment by thaJeztah** [comment] 2016-04-11 11:16
> But for some reason when a container gets assigned the IP 192.168.0.21

So it only fails for *that* IP address?

**Comment by adamlc** [comment] 2016-04-11 13:58
@thaJeztah weirdly yes!

**Comment by krish7919** [comment] 2016-04-11 18:33
My hunch is it's iptable rules or routing entries being wrong. Can you double check these?

**Comment by adamlc** [comment] 2016-04-12 07:18
Thanks for the suggest, unfortunately there doesn't seem to be anything in iptables. If I have some time later I'll go through some of the logs and see if I can figure it out. This is on a production cluster so I don't want to tinker too much!

```
[ec2-user@swarm-node-eu-west1-1a-1 ~]$ sudo iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

**Comment by thaJeztah** [comment] 2016-11-30 16:09
Closing because we probably need more info to look into this, but let me know if you're still having this issue, or found the cause

**Closed by thaJeztah** 2016-11-30 16:09 UTC
Labels: area/networking, version/1.9

**Comment by adamlc** [comment] 2016-11-30 16:14
@thaJeztah sorry I didn't close this. I actually recreated the network and not had the problem since 😄

**Comment by thaJeztah** [comment] 2016-11-30 16:23
Good to hear, thanks!
