### ISSUE TITLE
Error starting daemon: layer does not exist

### ISSUE THREAD

**Issue by neconano** [docker/docker#27371] opened 2016-10-14 01:50 UTC
please help

**Comment by samprog1** [comment] 2016-10-14 09:09
How are you trying to start the daemon?

What version are you using on what OS?

**Comment by ibrokethecloud** [comment] 2017-01-09 02:50
I am also having the same issue, with docker 1.12.5 and using btrfs as the storage driver on rhel 7.2

I am just trying out a move from 1.10.3 to 1.12.5 and have build a new environment, however scheduling multiple containers with mem_limit enforced caused the linux vm to reboot, and now docker doesn't start up.

I am using rancher with cattle as the scheduler.

**Comment by cpuguy83** [comment] 2017-01-09 14:24
@ibrokethecloud Have you tried to manually mount the layer (or the btrfs partition in general)?
Do you have any more details?

**Comment by coolzilj** [comment] 2017-01-17 14:24
Same issue. 
Docker version 1.12.6, build 78d1802
3.10.0-327.22.2.el7.x86_64
CentOS 7.2 64bit
Docker daemon crashed after adding a host in rancher, and can't start the service now.

**Comment by AkihiroSuda** [comment] 2017-03-03 08:57
https://github.com/docker/docker/issues/31506 seems a dupe of this issue.

Since #31506 has more detailed information than this issue, I'm closing this issue.

**Closed by AkihiroSuda** 2017-03-03 08:57 UTC
Labels: status/more-info-needed

**Comment by sev7nf** [comment] 2019-02-26 01:05
> Same issue.
> Docker version 1.12.6, build [78d1802](https://github.com/moby/moby/commit/78d18021ecba00c00730dec9d56de6896f9e708d)
> 3.10.0-327.22.2.el7.x86_64
> CentOS 7.2 64bit
> Docker daemon crashed after adding a host in rancher, and can't start the service now.

have you fix this problem?
