### ISSUE TITLE
error writing FROZEN to freezer.state: open /sys/fs/cgroup/freezer/system.slice/docker-b5ee ... 9c67.scope/freezer.state: no such file or directory

### ISSUE THREAD

**Issue by rubentrancoso** [docker/docker#22923] opened 2016-05-23 23:35 UTC
Could not find a way to have docker running on a VirtualBox to keep working after shutdown.
The hosts agent get lost, docker do not start again and the docker installation need to be reinitialized.

   # systemctl stop docker.service
   # rm -rf /var/lib/docker
   # shutdow -r now

**Output of `docker version`:**

```
# docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-common-1.9.1-40.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      ab77bde/1.9.1
 Built:
 OS/Arch:         linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox 4.3.30  on Win7 running Centos 7 minimal ( .vdi disk dynamically allocated 32GB - using only 4GB )
+ yum update
+ yum -y install docker docker-registry
+ agent installed from rancher URL

**Steps to reproduce the issue:**
1. Centos7 fresh install + yum update + yum -y install docker docker-registry
2. Add host on Cattle environment
3. Shutdown the Host VM with ACPI, turn-off, shutdown or docker stop + shutdown
4. Start VM again

**Describe the results you received:**

next time the VM is up, Docker is no longer running

# systemctl status docker.service > result

```
â— docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mon 2016-05-23 19:18:59 EDT; 9min ago
     Docs: http://docs.docker.com
  Process: 2630 ExecStart=/bin/sh -c /usr/bin/docker-current daemon $OPTIONS            $DOCKER_STORAGE_OPTIONS            $DOCKER_NETWORK_OPTIONS            $ADD_REGISTRY            $BLOCK_REGISTRY            $INSECURE_REGISTRY            2>&1 | /usr/bin/forward-journald -tag docker (code=exited, status=0/SUCCESS)
 Main PID: 2630 (code=exited, status=0/SUCCESS)

May 23 19:18:59 sg-pocsgr-hstc.sigres.dev forward-journal[2632]: ........time="2016-05-23T19:18:59.312057284-04:00" level=warning msg="exit status 1"
May 23 19:18:59 sg-pocsgr-hstc.sigres.dev forward-journal[2632]: time="2016-05-23T19:18:59.312434552-04:00" level=warning msg="error writing FROZEN to freezer.state: open /sys/fs/cgroup/freezer/system.slice/docker-b5ee2208dd1de3291d90c334a7d8f16fd2b97f64b684b82b823100dc9fe19c67.scope/freezer.state: no such file or directory"
May 23 19:18:59 sg-pocsgr-hstc.sigres.dev forward-journal[2632]: time="2016-05-23T19:18:59.312998824-04:00" level=warning msg="error writing THAWED to freezer.state: open /sys/fs/cgroup/freezer/system.slice/docker-b5ee2208dd1de3291d90c334a7d8f16fd2b97f64b684b82b823100dc9fe19c67.scope/freezer.state: no such file or directory"
May 23 19:18:59 sg-pocsgr-hstc.sigres.dev forward-journal[2632]: time="2016-05-23T19:18:59.742792901-04:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/b5ee2208dd1de3291d90c334a7d8f16fd2b97f64b684b82b823100dc9fe19c67/shm: invalid argument\nfailed to umount /var/lib/docker/containers/b5ee2208dd1de3291d90c334a7d8f16fd2b97f64b684b82b823100dc9fe19c67/mqueue: invalid argument"
May 23 19:18:59 sg-pocsgr-hstc.sigres.dev forward-journal[2632]: time="2016-05-23T19:18:59.742837106-04:00" level=error msg="Error unmounting device b5ee2208dd1de3291d90c334a7d8f16fd2b97f64b684b82b823100dc9fe19c67: UnmountDevice: device not-mounted id b5ee2208dd1de3291d90c334a7d8f16fd2b97f64b684b82b823100dc9fe19c67"
May 23 19:18:59 sg-pocsgr-hstc.sigres.dev forward-journal[2632]: time="2016-05-23T19:18:59.743030616-04:00" level=error msg="Failed to start container b5ee2208dd1de3291d90c334a7d8f16fd2b97f64b684b82b823100dc9fe19c67: [8] System error: not a directory"
May 23 19:18:59 sg-pocsgr-hstc.sigres.dev forward-journal[2632]:
May 23 19:18:59 sg-pocsgr-hstc.sigres.dev forward-journal[2632]: time="2016-05-23T19:18:59.743063003-04:00" level=info msg="Loading containers: done."
May 23 19:18:59 sg-pocsgr-hstc.sigres.dev forward-journal[2632]: time="2016-05-23T19:18:59.743143359-04:00" level=fatal msg="is a directory"
May 23 19:18:59 sg-pocsgr-hstc.sigres.dev systemd[1]: Started Docker Application Container Engine.
```

**Describe the results you expected:**

The VM should start normally anda the Rancher agent should notify rancher server that it's ACTIVE

**Comment by thaJeztah** [comment] 2016-05-24 14:46
This could well be an issue with `systemd` cgroups. I see you're installing a version of docker that's packaged by Red Hat (https://github.com/projectatomic/docker/commit/ab77bde), and contains quite some modifications that can affect this. We can't give support for those versions here (you can report issues through https://bugzilla.redhat.com)

Are you able to reproduce this on the current release from the official repositories? https://docs.docker.com/engine/installation/linux/centos/ we made quite some changes related to systemd in releases after 1.9

**Comment by rubentrancoso** [comment] 2016-05-30 22:06
The current release works well, the only problem is with HTT_PROXY.
With version 1;11;1 I'm unable to go through the company proxy.

```
May 30 17:44:21 localhost.localdomain docker[9859]: time="2016-05-30T17:44:20.999809333-04:00" level=error msg="Handler for POST /v1.23/containers/create returned error: No such image: hello-world:latest"
May 30 17:44:21 localhost.localdomain docker[9859]: time="2016-05-30T17:44:21.035926401-04:00" level=warning msg="Error getting v2 registry: Get https://registry-1.docker.io/v2/: dial tcp 52.203.89.113:443: getsockopt: connection refused"
May 30 17:44:21 localhost.localdomain docker[9859]: time="2016-05-30T17:44:21.036017644-04:00" level=error msg="Attempting next endpoint for pull
after error: Get https://registry-1.docker.io/v2/: dial tcp 52.203.89.113:443: getsockopt: connection refused"
May 30 17:44:21 localhost.localdomain docker[9859]: time="2016-05-30T17:44:21.089330094-04:00" level=error msg="Not continuing with pull after error: Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp 52.72.231.247:443: getsockopt: connection refused"
```

I'm loocked:
with 1.9 proxy is ok but I lost my data
with 1.11 data is ok but proxy is not.

**Comment by thaJeztah** [comment] 2016-05-30 22:16
How did you configure the `HTTP_PROXY` for the daemon? Note that the package you has installed may use configuration files in `/etc/default`. Those files are not used by the systemd unit-file from the official packages. You can read this section on how to configure a proxy using a systemd drop-in file; https://docs.docker.com/engine/admin/systemd/#http-proxy

**Comment by rubentrancoso** [comment] 2016-05-30 22:22
I could make it work thanks.
found this:
http://hasis053341.blogspot.com.br/2014/08/use-docker-search-over-proxy-on-centos-7.html

my proxy is on /etc/sysconfic/docker
and I had addded the line

EnvironmentFile=/etc/sysconfig/docker

to /usr/lib/systemd/system/docker.service
so know  i'm uptodate again

**Comment by thaJeztah** [comment] 2016-05-30 22:47
Nice! Note that it's not recommended to update the docker.service file directly; doing so may cause issues when updating docker, and a new/updated docker.service file is available. Using a drop-in file prevents this, as you keep your modifications out of the docker.service file.

Looks like your issue is resolved, is it ok to close this issue?

**Comment by rubentrancoso** [comment] 2016-05-31 19:17
Thanks for the note, just did that.
all done, you can close it.

**Comment by thaJeztah** [comment] 2016-05-31 20:37
Alright, happy to hear it worked. Closing this issue 👍

**Closed by thaJeztah** 2016-05-31 20:37 UTC
