### ISSUE TITLE
Weird volume permission in centos (different then ubuntu)

### ISSUE THREAD

**Issue by meirwah** [docker/docker#22946] opened 2016-05-24 16:41 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 18
 Running: 0
 Paused: 0
 Stopped: 18
Images: 12
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-50332508-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.343 GB
 Data Space Total: 107.4 GB
 Data Space Available: 18.42 GB
 Metadata Space Used: 4.17 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.7 MiB
Name: ip-172-31-23-183.eu-central-1.compute.internal
ID: QJYC:2TEL:BYBZ:TZ22:FWZG:KQY7:GXCI:2EBX:H3YS:2PAD:FL6S:X7DK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS
Centos 7

**Steps to reproduce the issue:**
1. run volume like : docker run -v /var/lib/demisto/tenants/acc_test:/var/lib/demisto/:Z demisto ls -ll /var/lib/ 

**Describe the results you received:**
on ubuntu :
```drwxr-xr-x  4 demisto     998 4096 May 24 16:10 demisto```

in Centos:
```drwxr-xr-x  2     995     991   26 May 24 14:39 demisto```

**Describe the results you expected:**
on centos, should be same permission as ubuntu (Demisto user)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-05-24 17:12
When using bind-mounts, the host directory is not altered by docker, but literally just "mounted" inside the container. The permissions/owner (uid/gid) of the files on the host are therefore the same as the permissions/owner on the host.

In this case, I suspect the files on the CentOS host have a different owner than the files on the Ubuntu host. Note that the username you're seeing in the container is coming from the `/etc/passwd` file inside the container. That file translate the numeric uid to a name (e.g, uid 123 = username foobar).

This is not a bug in docker, but an issue with the file permissions on the host (which are bind-mounted in the container), so I'll close this issue, but feel free to comment after I closed

**Closed by thaJeztah** 2016-05-24 17:12 UTC
Labels: version/1.11

**Comment by meirwah** [comment] 2016-05-24 20:31
In both ubuntu and centos , the folder permission are the same:
drwxr-xr-x 4 demisto demisto 4096 May 24 16:10 acc_test

drwxr-xr-x  2 demisto demisto 26 May 24 14:39 acc_test

When I look inside the container (``` docker run demisto cat /etc/passwd ```) I get:
demisto:x:999:999::/home/demisto:

If I run ``` cat /etc/passwd ``` in the OS level I get:
for ubuntu:
``` demisto:x:999:998::/home/demisto: ```

for Centos:
``` demisto:x:995:991::/home/demisto:/bin/bash ```

This may be the issue? different username in OS level? that does not map well inside the container?

**Comment by thaJeztah** [comment] 2016-05-24 21:37
Yup, I think that's the issue; if you do `chown demisto:demisto` on the Ubunto host, you're basically doing `chown 999:998` whereas on the CentOS host, you're doing `chown 995:991`. Usually that's not a problem (it's just a number), but if you're sharing that with a different environment (in this case, the container), it doesn't match what's in the `/etc/passwd` there.

So, there's two options;

- chown the files, using the uid/gid that the container expects (`999:999`) - this always works, and doesn't require you to have a "demisto" user and group on your host
- if you like to have a "demisto" name visible on the host, make sure that the demisto user and group's uid/gid match the ones inside the container, http://askubuntu.com/questions/312919/how-to-change-user-gid-and-uid-in-ubuntu-13-04
