### ISSUE TITLE
Send stderr and stdout to different awslogs log groups

### ISSUE THREAD

**Issue by CameronGo** [docker/docker#24386] opened 2016-07-06 20:36 UTC
I've hunted for a way to accomplish this, and have seen several mentions of similar interests, but no current solution.

In my case, I am primarily thinking of apache logs, but if the option were available I would likely use this with other applications as well.  I can create symlinks for my apache log files to direct the error and access logs to stderr and stdout, but I do not have a way to distinguish between the two when directing the output to either awslogs or syslog.

I would ideally, as an example, like to send apache error logs from stderr to a log group named apache_error and then the stdout to a log group named apache_access.

I am using docker v1.11.2 on Ubuntu 14.x in an AWS ECS cluster if any of that is helpful.

**Comment by styfle** [comment] 2016-07-07 14:57
There are remote api parameters when retrieving the logs to get only `stderr` or `stdout` however there appears to be a bug for me that causes `stdout` to report both. See [docker-remote-api#2](https://github.com/mafintosh/docker-remote-api/issues/2).

**Comment by CameronGo** [comment] 2016-07-07 20:28
I think the main issue with using the API for this is that it is not supported via the docker run command.  So when I issue a docker run command I can specify where I want my logs to be sent (awslogs) and with what tags and log-opt.  So any tagging or log groups I specify apply to all logs and I cannot differentiate between the stderr and stdout.

**Comment by samuelkarp** [comment] 2016-07-13 23:52
@CameronGo The awslogs driver today combines `stdout` and `stderr` into the same log stream.  However, the driver could be updated to send to separate log streams (in separate log groups too) based on the [`Message.Source`](https://github.com/docker/docker/blob/378f065/daemon/logger/logger.go#L32) of each log line.

I think this is a good feature request, but it also looks like a duplicate of https://github.com/docker/docker/issues/17959.

**Comment by thaJeztah** [comment] 2016-07-13 23:55
Agreed that this looks like a duplicate; let me close those one and please continue the discussion on https://github.com/docker/docker/issues/17959 (thanks @samuelkarp )

**Closed by thaJeztah** 2016-07-13 23:55 UTC
Labels: area/logging, kind/enhancement

**Comment by styfle** [comment] 2016-07-14 16:00
@samuelkarp @thaJeztah Is separating `stdout` and `stderr` supported using the default json driver?

It wasn't working for me when using the remote api. See [docker-remote-api#2](https://github.com/mafintosh/docker-remote-api/issues/2) for more details.

**Comment by thaJeztah** [comment] 2016-07-14 16:46
@styfle no, afaik, that's not possible with the default JSON driver

**Comment by styfle** [comment] 2016-07-14 18:14
@thaJeztah Do any drivers support this?
