### ISSUE TITLE
FATA[0000] Error response from daemon: v1 ping attempt failed with error: Get http://x.x.x.x:5000

### ISSUE THREAD

**Issue by zxlzh2015** [docker/docker#18983] opened 2015-12-30 05:21 UTC
I just tried to gem install fpm from inside a container and don't have this issue. Are you using a proxy? I see you're also running into problems when not running inside a container (rubygems/rubygems#1426), so I highly suspect this is an issue in your net

**Comment by thaJeztah** [comment] 2015-12-30 11:27
Looks like a duplicate of https://github.com/docker/docker/issues/18913. Feel free to comment on that issue if you think I closed that one by mistake

**Closed by thaJeztah** 2015-12-30 11:27 UTC
