### ISSUE TITLE
Broken pipe with docker login

### ISSUE THREAD

**Issue by ianbytchek** [docker/docker#14286] opened 2015-06-30 12:15 UTC
I've seen a few issues like that, but didn't find an answer why this happens and how to solve this. In my case I'm trying to run `docker login` as an ansible script and it fails with the following message. When I manually / directly run the script, it works as expected.

```sh
mux_client_read_packet: read header failed: Broken pipe
```

I asked around at ansible irc but didn't get a full answer. Other docker commands work fine. Why does docker fails? How to avoid this?

```sh
# docker --version
Docker version 1.6.2, build 7c8fca2-dirty

# docker info
Containers: 13
Images: 19
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.5
Operating System: CoreOS 723.1.0
CPUs: 1
Total Memory: 996.3 MiB
Name: …compute.internal
ID: RAFS:R2HG:GX32:Z3DD:54DH:2ONQ:YVYR:4YBX:G4JY:CXS5:MRE5:O23K

# uname -a
Linux …compute.internal 4.0.5 #2 SMP Sat Jun 27 01:21:24 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux
```

**Comment by thaJeztah** [comment] 2015-07-26 22:38
This issue tracker is not meant as a general support forum, and reading this, this looks like a question, not a bug in Docker.

I think this question is better asked on the #docker IRC channel, the [docker-user](https://groups.google.com/forum/#!forum/docker-user) Google Group or https://forums.docker.com

I'm going to close this issue, but feel free to comment here if you think I closed this by mistake.

**Closed by thaJeztah** 2015-07-26 22:38 UTC
