### ISSUE TITLE
Can not start docker 1.10.1 on Debian with kernel 4.4.2

### ISSUE THREAD

**Issue by dodiak** [docker/docker#20489] opened 2016-02-19 09:40 UTC
I am newbie in docker and I was following the tutorial step by step. After installation I am trying to start the docker daemon. It says: [ ok ] Starting Docker: docker.   
But the docker does not start. In /var/log/docker is:
time="2016-02-18T19:35:38.071941209+01:00" level=info msg="[graphdriver] using prior storage driver \"overlay\"" 
time="2016-02-18T19:35:38.072402194+01:00" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2016-02-18T19:35:38.077121935+01:00" level=info msg="Firewalld running: false" 
time="2016-02-18T19:35:38.123266732+01:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address" 
time="2016-02-18T19:35:38.163126043+01:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: Failed to program NAT chain: Failed to inject docker in PREROUTING chain: iptables failed: iptables --wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER: iptables: No chain/target/match by that name.\n (exit status 1)" 

Google did not help me too much with the issue. Any hint is welcome

thanks

Dodo

**Comment by HackToday** [comment] 2016-02-19 10:46
Could you add your `docker info` ? And 'uname -a' info

**Comment by HackToday** [comment] 2016-02-19 10:48
And how did you install docker ? which tutorial guide you follow ? Which can help us to know if doc issue or other docker code issue

**Comment by dodiak** [comment] 2016-02-19 10:51
docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:09:42 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

uname -a
Linux opahapaka 4.4.2 #1 SMP Thu Feb 18 16:33:38 CET 2016 x86_64 GNU/Linux

I followed the: https://docs.docker.com/engine/installation/linux/debian/

**Comment by HackToday** [comment] 2016-02-19 10:58
hi @dodiak  Could you possible manual start docker with  `docker daemon -D`  to add debug log here ?

**Comment by dodiak** [comment] 2016-02-19 11:02
Here you go. I do not think I have any strange network configuration.

DEBU[0000] Using graph driver overlay                   
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
DEBU[0000] Option DefaultDriver: bridge                 
DEBU[0000] Option DefaultNetwork: bridge                
INFO[0000] Firewalld running: false                     
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]    
DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t filter -F DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -X DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -N DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -t filter -N DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -j RETURN] 
DEBU[0000] /sbin/iptables, [--wait -I DOCKER-ISOLATION -j RETURN] 
DEBU[0000] Registering ipam driver: "default"           
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
DEBU[0000] Allocating IPv4 pools for network bridge (a70f3d56d3be98f68e66d9f6e9b13ff7110d7044ade9cf65a4ee31418cb74733) 
DEBU[0000] RequestPool(LocalDefault, 172.17.0.0/16, , map[], false) 
DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.0.1, map[RequestAddressType:com.docker.network.gateway]) 
DEBU[0000] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0000] /sbin/iptables, [--wait -t nat -C DOCKER -i docker0 -j RETURN] 
DEBU[0000] /sbin/iptables, [--wait -t nat -I DOCKER -i docker0 -j RETURN] 
DEBU[0000] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] releasing IPv4 pools from network bridge (a70f3d56d3be98f68e66d9f6e9b13ff7110d7044ade9cf65a4ee31418cb74733) 
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.1) 
DEBU[0000] ReleasePool(LocalDefault/172.17.0.0/16)      
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: Failed to program NAT chain: Faile
d to inject docker in PREROUTING chain: iptables failed: iptables --wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER: iptables: No c
hain/target/match by that name.
 (exit status 1)

**Comment by HackToday** [comment] 2016-02-19 11:13
please input your

`iptables -t nat -L`

**Comment by dodiak** [comment] 2016-02-19 11:19
iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            

Chain DOCKER (0 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere

**Comment by phemmer** [comment] 2016-02-19 13:30
Is this a custom kernel? Sounds like you're missing `CONFIG_NETFILTER_XT_MATCH_ADDRTYPE`.
You can check that you have all the requisite kernel options by running this script: https://github.com/docker/docker/blob/master/contrib/check-config.sh

**Comment by dodiak** [comment] 2016-02-19 13:41
Thanks, that could be the problem ... The script is very useful :)

**Comment by dodiak** [comment] 2016-02-19 14:39
Confirmed. My minimalistic kernel did not have all the needed features enabled. Thanks!

**Comment by thaJeztah** [comment] 2016-02-20 00:01
Thanks all for helping out. I'm going to close this issue, because this looks to be resolved. Feel free to continue the discussion after I've closed

**Closed by thaJeztah** 2016-02-20 00:01 UTC

**Comment by AJNOURI** [comment] 2016-02-23 12:50
**BUG REPORT INFORMATION**

**docker version:**

> Docker version 1.10.1, build 9e83765

**docker info:**

> Containers: 5
>  Running: 0
>  Paused: 0
>  Stopped: 5
> Images: 81
> Server Version: 1.10.1
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 102
>  Dirperm1 Supported: false
> Execution Driver: native-0.2
> Logging Driver: json-file
> Plugins: 
>  Volume: local
>  Network: bridge null host
> Kernel Version: 3.13.0-75-generic
> Operating System: Ubuntu 14.04.4 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 7.798 GiB
> Name: gns3-iouvm
> ID: B3ZB:OWZQ:4HE6:MNIU:6XDT:TZSO:FOUP:C7KG:M2IL:7RAF:C4IK:3BTV
> Username: ajnouri
> Registry: https://index.docker.io/v1/
> WARNING: No swap limit support

Provide additional environment details (AWS, VirtualBox, physical, etc.):
**Physical machine**

> Distributor ID:	Ubuntu
> Description:	Ubuntu 14.04.4 LTS
> Release:	14.04
> Codename:	trusty
> Linux gns3-iouvm 3.13.0-75-generic #119-Ubuntu SMP Mon Jan 11 13:49:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**List the steps to reproduce the issue:**

1.**docker network create --driver bridge mynet1**
Error response from daemon: unable to insert jump to DOCKER-ISOLATION rule in FORWARD chain:  (iptables failed: iptables --wait -I FORWARD -j DOCKER-ISOLATION: iptables v1.4.21: Couldn't load target `DOCKER-ISOLATION':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2))

Describe the results you expected:
Create a user-defined bridge network, so I can connect containers to.
Provide additional info you think is important:

**iptables -t nat -L**

> Chain PREROUTING (policy ACCEPT)
> target     prot opt source               destination         
> DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
> 
> Chain INPUT (policy ACCEPT)
> target     prot opt source               destination         
> 
> Chain OUTPUT (policy ACCEPT)
> target     prot opt source               destination         
> DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
> 
> Chain POSTROUTING (policy ACCEPT)
> target     prot opt source               destination         
> MASQUERADE  all  --  172.18.0.0/16        anywhere            
> MASQUERADE  all  --  172.18.0.0/16        anywhere            
> MASQUERADE  all  --  172.18.0.0/16        anywhere            
> MASQUERADE  all  --  172.18.0.0/16        anywhere            
> MASQUERADE  all  --  172.18.0.0/16        anywhere            
> MASQUERADE  all  --  172.18.0.0/16        anywhere            
> MASQUERADE  all  --  172.17.0.0/16        anywhere            
> MASQUERADE  all  --  10.0.3.0/24         !10.0.3.0/24         
> 
> Chain DOCKER (2 references)
> target     prot opt source               destination         
> RETURN     all  --  anywhere             anywhere            
> RETURN     all  --  anywhere             anywhere            
> RETURN     all  --  anywhere             anywhere            
> RETURN     all  --  anywhere             anywhere            
> RETURN     all  --  anywhere             anywhere            
> RETURN     all  --  anywhere             anywhere    

        


./check-config.sh

> warning: /proc/config.gz does not exist, searching other paths for kernel config ...
> info: reading kernel config from /boot/config-3.13.0-75-generic ...
> 
> Generally Necessary:
> - cgroup hierarchy: properly mounted [/sys/fs/cgroup]
> - apparmor: enabled and tools installed
> - CONFIG_NAMESPACES: enabled
> - CONFIG_NET_NS: enabled
> - CONFIG_PID_NS: enabled
> - CONFIG_IPC_NS: enabled
> - CONFIG_UTS_NS: enabled
> - CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
> - CONFIG_CGROUPS: enabled
> - CONFIG_CGROUP_CPUACCT: enabled
> - CONFIG_CGROUP_DEVICE: enabled
> - CONFIG_CGROUP_FREEZER: enabled
> - CONFIG_CGROUP_SCHED: enabled
> - CONFIG_CPUSETS: enabled
> - CONFIG_MEMCG: enabled
> - CONFIG_MACVLAN: enabled (as module)
> - CONFIG_VETH: enabled (as module)
> - CONFIG_BRIDGE: enabled (as module)
> - CONFIG_BRIDGE_NETFILTER: enabled
> - CONFIG_NF_NAT_IPV4: enabled (as module)
> - CONFIG_IP_NF_FILTER: enabled (as module)
> - CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
> - CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
> - CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
> - CONFIG_NF_NAT: enabled (as module)
> - CONFIG_NF_NAT_NEEDED: enabled
> - CONFIG_POSIX_MQUEUE: enabled
> 
> Optional Features:
> - CONFIG_USER_NS: enabled
> - CONFIG_SECCOMP: enabled
> - CONFIG_MEMCG_KMEM: enabled
> - CONFIG_MEMCG_SWAP: enabled
> - CONFIG_MEMCG_SWAP_ENABLED: missing
>     (note that cgroup swap accounting is not enabled in your kernel config, you can enable it by setting boot option "swapaccount=1")
> - CONFIG_RESOURCE_COUNTERS: enabled
> - CONFIG_BLK_CGROUP: enabled
> - CONFIG_IOSCHED_CFQ: enabled
> - CONFIG_BLK_DEV_THROTTLING: enabled
> - CONFIG_CGROUP_PERF: enabled
> - CONFIG_CGROUP_HUGETLB: enabled
> - CONFIG_NET_CLS_CGROUP: enabled (as module)
> - CONFIG_NETPRIO_CGROUP: enabled (as module)
> - CONFIG_CFS_BANDWIDTH: enabled
> - CONFIG_FAIR_GROUP_SCHED: enabled
> - CONFIG_RT_GROUP_SCHED: missing
> - CONFIG_EXT3_FS: missing
> - CONFIG_EXT3_FS_XATTR: missing
> - CONFIG_EXT3_FS_POSIX_ACL: missing
> - CONFIG_EXT3_FS_SECURITY: missing
>     (enable these ext3 configs if you are using ext3 as backing filesystem)
> - CONFIG_EXT4_FS: enabled
> - CONFIG_EXT4_FS_POSIX_ACL: enabled
> - CONFIG_EXT4_FS_SECURITY: enabled
> - Storage Drivers:
>   - "aufs":
>     - CONFIG_AUFS_FS: enabled (as module)
>   - "btrfs":
>     - CONFIG_BTRFS_FS: enabled (as module)
>   - "devicemapper":
>     - CONFIG_BLK_DEV_DM: enabled
>     - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
>   - "overlay":
>     - CONFIG_OVERLAY_FS: missing
>   - "zfs":
>     - /dev/zfs: missing
>     - zfs command: missing
>     - zpool command: missing



----------END REPORT ---------

#ENEEDMOREINFO
