### ISSUE TITLE
An error occurred trying to connect

### ISSUE THREAD

**Issue by qtisan** [docker/docker#25351] opened 2016-08-03 00:25 UTC
when i finished the installation following the instruction, got this:

```
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: read unix @->/var/run/docker.sock: read: connection reset by peer
```

**and i tried:**
`sudo apt-get install apparmor`

**and tried:**
> 1. Stop docker daemon
> 2. sudo rm /var/lib/docker/network/files/local-kv.db
> 3. Start docker daemon

**i have created the group named `docker`, and the current user in it.**

**i repeated the service status, and found:**
```
root@iZ256kqlmnaZ:~# service docker status
docker start/running, process 25992
root@iZ256kqlmnaZ:~# 
root@iZ256kqlmnaZ:~# service docker status
docker start/running, process 26140
root@iZ256kqlmnaZ:~# service docker status
docker start/running, process 26217
root@iZ256kqlmnaZ:~# service docker status
docker start/running, process 26217
root@iZ256kqlmnaZ:~# service docker status
docker start/running, process 26300
root@iZ256kqlmnaZ:~# service docker status
docker start/running, process 26377
root@iZ256kqlmnaZ:~# service docker status
docker start/running, process 26525
```

**i checked the log, and found it repeated...the service did not started..but i didn't know why.**
```
tail -f /var/log/upstart/docker.log 
```
-
```
time="2016-08-03T08:22:46.683913961+08:00" level=info msg="libcontainerd: new containerd process, pid: 31893" 
time="2016-08-03T08:22:47.767436388+08:00" level=info msg="[graphdriver] using prior storage driver \"aufs\"" 
time="2016-08-03T08:22:47.771668316+08:00" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2016-08-03T08:22:47.771982169+08:00" level=warning msg="Your kernel does not support swap memory limit." 
time="2016-08-03T08:22:47.772253016+08:00" level=warning msg="mountpoint for pids not found" 
time="2016-08-03T08:22:47.772767778+08:00" level=info msg="Loading containers: start." 
time="2016-08-03T08:22:47.779680819+08:00" level=info msg="Firewalld running: false" 
time="2016-08-03T08:22:47.844739059+08:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: failed to parse pool request for address space \"LocalDefault\" pool \"\" subpool \"\": could not find an available predefined network" 
/var/run/docker.sock is up
time="2016-08-03T08:22:47.893837777+08:00" level=info msg="libcontainerd: new containerd process, pid: 31965" 
time="2016-08-03T08:22:48.973301302+08:00" level=info msg="[graphdriver] using prior storage driver \"aufs\"" 
time="2016-08-03T08:22:48.979844036+08:00" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2016-08-03T08:22:48.980343452+08:00" level=warning msg="Your kernel does not support swap memory limit." 
...
...
...
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Output of `docker info`:**

```
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**`uname -a`**
```
Linux iZ256kqlmnaZ 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment] 2016-08-03 09:57
This looks like a duplicate of https://github.com/docker/docker/issues/22204, https://github.com/docker/docker/issues/24738, and possibly others; when starting, docker tries to find an available network range to run on, and depending on your local network, it's possible it's not able to find an available range.

More info can be found in the linked issues, which may help you resolve this issue.

I'll close this because it's a duplicate, but hope you find a solution

**Closed by thaJeztah** 2016-08-03 09:57 UTC

**Comment by asmodehn** [comment] 2016-08-04 01:39
Same error here : 
```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: read unix @->/var/run/docker.sock: read: connection reset by peer
```

```
alexv@asmodehn:~$ uname -a
Linux asmodehn 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I had a look at the related issues, but couldn't solve the problem yet.

I had previously an old version installed, so I did a complete purge to avoid any previous config to be the problem.
```
apt-get purge docker-engine
```

I also checked that I got my packages from the right place
```
alexv@asmodehn:~$ apt-cache policy docker-engine 
docker-engine:
  Installed: 1.12.0-0~trusty
  Candidate: 1.12.0-0~trusty
  Version table:
 *** 1.12.0-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     1.11.2-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
[...]
```

My routing table looks like

```
alexv@asmodehn:~$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.10.1    0.0.0.0         UG    0      0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 eth1
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth1
192.168.3.0     0.0.0.0         255.255.255.0   U     9      0        0 wlan0
192.168.10.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
```

I tried to remove these docker routes, and see them recreated when restarted the docker service, but the issue is still there.

I tried to bring interfaces up and down
```
alexv@asmodehn:~$ sudo ifconfig docker0 down
alexv@asmodehn:~$ sudo ifconfig docker0 up
alexv@asmodehn:~$ sudo service docker restart
```
but I still get the same error.

After I finally dig out the log, I see this logspam : 
```
alexv@asmodehn:~$ sudo tail -f /var/log/upstart/docker.log
time="2016-08-04T10:28:55.361825285+09:00" level=info msg="libcontainerd: new containerd process, pid: 15714" 
time="2016-08-04T10:28:56.403639633+09:00" level=fatal msg="Error starting daemon: error initializing graphdriver: \"/var/lib/docker\" contains several valid graphdrivers: aufs, devicemapper; Please cleanup or explicitly choose storage driver (-s <DRIVER>)" 
/var/run/docker.sock is up
time="2016-08-04T10:28:56.422735450+09:00" level=info msg="libcontainerd: new containerd process, pid: 15819" 
time="2016-08-04T10:28:57.465010062+09:00" level=fatal msg="Error starting daemon: error initializing graphdriver: \"/var/lib/docker\" contains several valid graphdrivers: aufs, devicemapper; Please cleanup or explicitly choose storage driver (-s <DRIVER>)" 
/var/run/docker.sock is up
time="2016-08-04T10:28:57.484758772+09:00" level=info msg="libcontainerd: new containerd process, pid: 15932" 
time="2016-08-04T10:28:58.528007455+09:00" level=fatal msg="Error starting daemon: error initializing graphdriver: \"/var/lib/docker\" contains several valid graphdrivers: devicemapper, aufs; Please cleanup or explicitly choose storage driver (-s <DRIVER>)" 
/var/run/docker.sock is up
time="2016-08-04T10:28:58.548040975+09:00" level=info msg="libcontainerd: new containerd process, pid: 16063" 
time="2016-08-04T10:28:59.590962642+09:00" level=fatal msg="Error starting daemon: error initializing graphdriver: \"/var/lib/docker\" contains several valid graphdrivers: aufs, devicemapper; Please cleanup or explicitly choose storage driver (-s <DRIVER>)" 
/var/run/docker.sock is up
[...]
```

After all, in my case at least, it was related to https://github.com/docker/docker/issues/14088
somehow the docker daemon kept restarting, even though there was no way it could properly start...

So I removed the directory containing my old images (devicemapper) and restarted the docker service, and now all works well :  
```
alexv@asmodehn:~$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Comment by qtisan** [comment] 2016-08-05 17:09
i comment `up route add -net 172.16.0.0 netmask 255.240.0.0 gw 10.44.207.247 dev eth0` in `/etc/network/interfaces`, and `route del` it..
it works...
@thaJeztah thx...

**Comment by PrimeByDesign** [comment] 2016-12-22 17:08
This is getting ridiculous, There are so many duplicates of this question and it appears that none of them have an answer that works for me. I'm honestly losing the will to live. Surely if this problem is so widespread the mechanism responsible should be altered.

**Comment by thaJeztah** [comment] 2016-12-22 17:34
@PrimeByDesign what error are you getting, just "failing to connect" or is the error due to docker not able to find an available IP range? For "failing to connect" we made one more improvement in the error message; see https://github.com/docker/docker/pull/26797. In general though, there are so many possible reasons for the client not being able to connect to the daemon, especially if the daemon is "remote"; we won't be able to cover all those in an error message (remote daemon not running, VPN in use, proxy, firewall blocked, network issues in general, etc.)

For the IP ranges, there is an open pull request to allow customising the ranges that docker tries to use; see https://github.com/docker/docker/pull/29376

**Comment by brikeyes** [comment] 2017-05-25 19:59
same issue here , I have had this happen over 6 times now , if the instances are shut off for an extended time I will get this 

n error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer
