### ISSUE TITLE
Reverse dns inconsistencies causes issues

### ISSUE THREAD

**Issue by F21** [docker/docker#21562] opened 2016-03-28 05:13 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   388f544
 Built:        Fri Mar 25 19:58:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   388f544
 Built:        Fri Mar 25 19:58:22 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 8
Server Version: 1.11.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 63
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-34-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 19.61 GiB
Name: ubuntu
ID: B7GA:45KQ:KPGO:WK62:PRQ6:2DQU:6GP2:CRY6:W6IM:VGJY:3OS7:XOBM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker runs in Ubuntu 15.10 64-bit which is a VirtualBox VM running on Windows 10 64-bit.

**Steps to reproduce the issue:**
1. docker network create testnet
2. docker run -it --net=testnet --hostname=go1 --name=golang_1 --net-alias=go1 golang
3. apt-get update
4. apt-get install dnsutils
5. dig -x go1
6. dig -x 172.18.0.2

**Describe the results you received:**
This is the forward dns, which works correctly:

```
; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> -x go1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 30765
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;go1.in-addr.arpa.		IN	PTR

;; AUTHORITY SECTION:
in-addr.arpa.		1799	IN	SOA	b.in-addr-servers.arpa. nstld.iana.org. 2015073231 1800 900 604800 3600

;; Query time: 561 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Mon Mar 28 05:10:46 UTC 2016
;; MSG SIZE  rcvd: 113
```

This is the reverse-dns, which is inconsistent and will break things such as hdfs and hbase:
```
; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> -x 172.18.0.2
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13901
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;2.0.18.172.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
2.0.18.172.in-addr.arpa. 600	IN	PTR	golang_1.testnet.

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Mon Mar 28 05:10:56 UTC 2016
;; MSG SIZE  rcvd: 102
```

**Describe the results you expected:**
It would be much more consistent if the reverse-dns' PTR record returned `go1` which is the hostname or a net-alias rather than `golang_1.testnet.` which is the `container_name.network_name`.

**Comment by mavenugo** [comment] 2016-03-28 05:27
@F21 this is the expected behavior and is as per design. Also returning `container_name.network_name` for reverse dns query is a consistent behavior if a `conatiner_name` is provided. Also, `hostname` is not considered for DNS resolution.

--net-alias is considered for the reverse-dns query only if the corresponding container-name is NOT specified.

Also as discussed in https://github.com/docker/docker/issues/20847#issuecomment-191850085, returning multiple PTR record isnt advised and hence when there is a Reverse lookup request, docker consistently go through the priority logic of container-name followed by alias-name (if container-name isnt specified).

If your request is to change the priority to use `--net-alias` above `container-name`, then we have to also answer which of the multiple `--net-alias` to give the top priority ?

**Comment by F21** [comment] 2016-03-28 05:51
Hey @mavenugo, thanks for the quick reply to my issue!

Here are my observations with 1.11.0-rc2.

If I only have 1 `--net-alias`, `docker run -it --net=compose_default --hostname=go2 --net-alias=go2 golang`, this is the result of my reverse lookup:

```
dig -x 172.18.0.2

; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> -x 172.18.0.2
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45000
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;2.0.18.172.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
2.0.18.172.in-addr.arpa. 600	IN	PTR	go2.compose_default.

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Mon Mar 28 05:39:54 UTC 2016
;; MSG SIZE  rcvd: 97
```

If I have 2 `--net-aliases`, `docker run -it --net=testnet --hostname=go2 --net-alias=go2 --net-alias=two golang`, it seems the first `net-alias` is prioritized, but the result contains a `g=` (not too sure what that means:

```
root@go2:/go# dig -x 172.19.0.2

; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> -x 172.19.0.2
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4026
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;2.0.19.172.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
2.0.19.172.in-addr.arpa. 600	IN	PTR	g=go2.testnet.

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Mon Mar 28 05:41:38 UTC 2016
;; MSG SIZE  rcvd: 91
```

It looks like if there are multiple `net-aliases`, the first one is prioritized, so if one were to give `--net-alias` priority over `container-name`, then the first `net-alias` should receive top priority.

I thought I would go into my use-case as well. I use docker and docker-compose heavily for building POC and small production clusters of containers with their own bridged networks. I am also building a tool to automate all of this.

I like to prefix my container names with a project name to avoid naming conflicts with other containers running in the daemon: `myproject_someservice`. However, within my containers, I set my hostname to `someservice` and would like to access other containers via `someservice` as well. All of this works correctly and the forward dns is also resolvable.

However, when it comes to reverse dns, I am receiving a result like `container_name.network_name`, which causes issues with things like hbase and hdfs which relies heavily on the reverse dns. Being able to use the `net-alias` and being able to drop the network name as the reverse dns would extremely useful for this use case.

**Comment by sanimej** [comment] 2016-03-28 07:02
@F21 service discovery in docker has always been  based on `--name` and the FQDN of a container is container_name.network_name. ie: for forward lookup you can either use the short form, just the container name or the full form. 

DNS PTR records typically return the fqdn. Thats the reason you see container_name.network_name in reverse dns. But looks like this doesn't work for Hadoop/HDFS which expects the reverse lookup to be in a different format.

Can you please try the following work around 
```
docker network create testnet
docker run -it --net=testnet --hostname=go1.testnet --name=go1 golang
```
This basically sets your hostname to be same as what reverse DNS returns.

**Comment by F21** [comment] 2016-03-28 09:36
@sanimej I tried using docker-compose to bring up the cluster, but it's failing:

```
Error response from daemon: Cannot start container 353dc194a5cf9b34d9653b9828aa101f8f598fd2b91c4f3633ac1b5d86f4a72d: [9] System error: invalid argument
```

This is the a `docker-compose.yml` that reproduces the issue:

```yaml
app:
  image: golang
  hostname: f826338a441f2f8a4685630e4fd83ad3af78c0fc_app.f826338a441f2f8a4685630e4fd83ad3af78c0fc
  container_name: f826338a441f2f8a4685630e4fd83ad3af78c0fc_app
  tty: true
  stdin_open: true
zookeeper:
  image: f21global/zookeeper
  hostname: f826338a441f2f8a4685630e4fd83ad3af78c0fc_zookeeper.f826338a441f2f8a4685630e4fd83ad3af78c0fc
  container_name: f826338a441f2f8a4685630e4fd83ad3af78c0fc_zookeeper
  environment:
    CONFIGTYPE: file
  tty: true
```

**Comment by sanimej** [comment] 2016-03-28 15:30
@F21 Your hostname is too long; I think it has to be 64 characters or less. Try a shorter hostname..

for example, this works..

`docker run -it --net=f826338a441f2f8a4685630e4fd83ad3af78c0fc --hostname=go1.f826338a441f2f8a4685630e4fd83ad3af78c0fc --name go1 busybox sh`

**Comment by F21** [comment] 2016-03-28 21:15
@sanimej Thanks, that works! Also noticed that it's safer to have dashes rather than underscores in the hostname, otherwise hdfs complains.

**Comment by icecrime** [comment] 2016-03-28 23:12
- Should we close this one?
- Should we file an issue to make sure `docker` restricts the hostname to 64 characters?

**Comment by sanimej** [comment] 2016-03-28 23:41
`Should we close this one?`

Yes.

`Should we file an issue to make sure docker restricts the hostname to 64 characters?`

I think its better to error out (which we do already) rather than implicitly truncating the hostname to 64 characters.

**Comment by icecrime** [comment] 2016-03-28 23:50
It's pretty clear that _something_ allows to submit a hostname of > 64 characters, or the user would not have received the `System error: invalid argument` error in return...

It seems to be a discrepancy between the API and the CLI, as the verification is done in [`runconfig/opts/parse.go`](https://github.com/docker/docker/blob/master/runconfig/opts/parse.go#L249). So yes, there's an issue to be filed here.

**Closed** 2016-03-28 23:54 UTC
