### ISSUE TITLE
Intermittent failure connecting to port

### ISSUE THREAD

**Issue by ajl** [docker/docker#25698] opened 2016-08-15 05:19 UTC
If I run a global nginx (or tomcat, doesn't matter) service in a swarm, exposing a port on each node (I am load balancing to my cluster and need the same port open everywhere)

docker service create  --name my-nginx --with-registry-auth --mode global -p 7011:7011 -p 7010:7010 my-nginx:0.3

The service starts on every node fine. (yay)

On any node I try to connect to the port and sometimes it works
```# nc -zv localhost 7010
Connection to localhost 7010 port [tcp/http-alt] succeeded!```

and sometimes it doesn't"
```
# nc -zv localhost 7010
nc: connect to localhost port 7010 (tcp) failed: Connection refused
```
If I curl, I get similar results, but sometimes it seems to timeout.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```


**Output of `docker info`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
root@ip-172-31-35-10:/home/ubuntu/setup/nginx# docker info
Containers: 12
 Running: 4
 Paused: 0
 Stopped: 8
Images: 12
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: active
 NodeID: bd2rri2d7heioizz6ti7fs14o
 Is Manager: true
 ClusterID: 6poe5sl596j8c233f77da4vjt
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 172.31.35.10
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-172-31-35-10
ID: MUUA:UEUC:CC7V:WNU7:6SCE:JLD4:ULVI:YYH3:6R3D:EZI4:XIGW:F3QX
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am on AWS

**Steps to reproduce the issue:**
1. Deploy global service opening port N
2.try to connect to port N on any box (it fails intermittently)
3.


**Describe the results you received:**
```
# nc -zv localhost 7010
Connection to localhost 7010 port [tcp/http-alt] succeeded!
# nc -zv localhost 7010
nc: connect to localhost port 7010 (tcp) failed: Connection refused
```

**Describe the results you expected:**
```
# nc -zv localhost 7010
Connection to localhost 7010 port [tcp/http-alt] succeeded!
```
All the time

**Additional information you deem important (e.g. issue happens only occasionally):**

it happens every time I start a service, but intermittently. Maybe 50% failures.

**Comment by mrjana** [comment] 2016-08-15 05:37
@ajl We fixed a bunch of issue in 1.12.1-rc1. Can you please give that a try and see how if goes? https://github.com/docker/docker/releases/tag/v1.12.1-rc1

**Comment by ajl** [comment] 2016-08-15 12:03
Thanks Jana. However, we were planning to go into production with this. I am concerned about moving to a test branch of docker for our production environment. It looks like the impact of this is that we need to move all our applications that listen on a port outside the swarm but can safely leave the processors that simply listen to events on a queue and process them inside?

Do you know a date for 1.12.1 to go into production?

**Comment by 0bp** [comment] 2016-08-15 12:27
I'm having the same issue with 1.12.1-rc1. After restarting all nodes it works for a short period and after scaling containers a few times it gets more and more unresponsive and requests fail.

    Containers: 14
     Running: 1
     Paused: 0
     Stopped: 13
    Images: 25
    Server Version: 1.12.1-rc1
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 83
     Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
     Volume: local
     Network: host overlay bridge null
    Swarm: active
     NodeID: 9xo0g3x6xhuf463fce2id8rqz
     Is Manager: true
     ClusterID: 53o2y4krknobp898po4deem34
     Managers: 2
     Nodes: 6
     Orchestration:
      Task History Retention Limit: 5
     Raft:
      Snapshot Interval: 10000
      Heartbeat Tick: 1
      Election Tick: 3
     Dispatcher:
      Heartbeat Period: 5 seconds
     CA Configuration:
      Expiry Duration: 3 months
     Node Address: 138.201.195.222
    Runtimes: runc
    Default Runtime: runc
    Security Options:
    Kernel Version: 3.16.0-4-amd64
    Operating System: Debian GNU/Linux 8 (jessie)
    OSType: linux
    Architecture: x86_64
    CPUs: 8
    Total Memory: 62.88 GiB
    Name: docker-master-1
    ID: MFIR:Z2PP:IEBD:23SC:SCKV:KOHC:GCNO:V5K2:S23A:LJAD:LVAE:6EK5
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): false
    Debug Mode (server): false
    Username: borispenck
    Registry: https://index.docker.io/v1/
    WARNING: No memory limit support
    WARNING: No swap limit support
    WARNING: No kernel memory limit support
    WARNING: No oom kill disable support
    WARNING: No cpu cfs quota support
    WARNING: No cpu cfs period support
    Insecure Registries:
     127.0.0.0/8

**Comment by mrjana** [comment] 2016-08-15 16:45
@ajl Not suggesting to run test code in production. But since you are testing I thought it would be better to test on top of 1.12.1-rc1 since it has more fixes so that we don't chase old issues. Nevetheless I wanted to know a bit more about your environment. You mentioned you are on AWS. Did you open up the required ports(2377/tcp, 7946/tcp, 7946/udp and 4789/udp) in the security port? You have to do that before creating a swarm cluster. Also when you said you are having intermittent issues is this transient? I.e if it fails does it succeed again?

BTW, 1.12.1 will be released in a few days time.

@0bp Same set of questions as above applies to you as well? Could you clarify?

**Comment by jmcdonagh** [comment] 2016-08-16 21:29
Having the same exact issue as OP. Port will be open then boom suddenly can't connect. If I go onto the machine and look at netstat -tnlp i see the port is open but even get connection refused trying to connect from localhost!

**Comment by alontorres** [comment] 2016-08-17 12:46
Same issue as described in #24789 
I've also tried 1.12.1 rc1 and the issue hasn't been solved for me.

**Comment by jmcdonagh** [comment] 2016-08-17 13:34
here's some more information guys...

So this morning I went in and removed the service, then I said, ok this service stuff isn't ready for prime-time and went to run the containers by hand on each node, and it looks like the socket is in some kind of hung state:

```
[aws:~/docker-config/aws] > docker run -p 8025:3000 imagename:testing testing
docker: Error response from daemon: driver failed programming external connectivity on endpoint sick_roentgen (b39337f748d50b9edd77d688e7c43bba90d410fc096c2b98d15865495b97486f): Error starting userland proxy: listen tcp 0.0.0.0:8025: bind: address already in use.
```

Weird:

```
ubuntu@larryland:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ubuntu@larryland:~$ sudo netstat -tnlp | grep 8025
tcp6       0      0 :::8025                 :::*                    LISTEN      1563/dockerd
```

And just for posterity here are the iptables rules for the regular filter table and the nat table:

```
ubuntu@larryland:~$ sudo iptables -nvL
Chain INPUT (policy ACCEPT 2597 packets, 947K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 24 packets, 1440 bytes)
 pkts bytes target     prot opt in     out     source               destination
30418 1717K DOCKER-ISOLATION  all  --  *      *       0.0.0.0/0            0.0.0.0/0
22779 1288K DOCKER     all  --  *      docker_gwbridge  0.0.0.0/0            0.0.0.0/0
10882  574K ACCEPT     all  --  *      docker_gwbridge  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 7639  429K ACCEPT     all  --  docker_gwbridge !docker_gwbridge  0.0.0.0/0            0.0.0.0/0
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  docker_gwbridge docker_gwbridge  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 2769 packets, 963K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER-ISOLATION (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  docker0 docker_gwbridge  0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  docker_gwbridge docker0  0.0.0.0/0            0.0.0.0/0
30418 1717K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
ubuntu@larryland:~$ sudo iptables -nvL -t nat
Chain PREROUTING (policy ACCEPT 20 packets, 1200 bytes)
 pkts bytes target     prot opt in     out     source               destination
27831 2078K DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
23512 1819K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 20 packets, 1200 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 24 packets, 1740 bytes)
 pkts bytes target     prot opt in     out     source               destination
    1    60 DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 30 packets, 2100 bytes)
 pkts bytes target     prot opt in     out     source               destination
    1    60 MASQUERADE  all  --  *      docker_gwbridge  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match src-type LOCAL
   26  1430 MASQUERADE  all  --  *      !docker_gwbridge  172.18.0.0/16        0.0.0.0/0
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  docker_gwbridge *       0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-INGRESS (2 references)
 pkts bytes target     prot opt in     out     source               destination
 2185  131K DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8025 to:172.18.0.2:8025
22067 1732K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
ubuntu@larryland:~$
```

**Comment by alexlokshin** [comment] 2016-08-18 14:51
Same issue here. A three node cluster running 1.12, intermittent connectivity issues, but containers are running (as their logs indicate). Is there a way to disable load balancing?

**Comment by mrjana** [comment] 2016-08-18 15:28
@jmcdonagh @alexlokshin Do you mind trying out 1.12.1-rc2 and provide your feedback? Some of the issues that you report have been fixed there.

**Comment by alexlokshin** [comment] 2016-08-19 02:17
@mrjana Thank you for your feedback, I will give it a try.

**Comment by grimabe** [comment] 2016-08-19 09:14
I am using 12.1 and I have the same behaviour.

**Comment by alexlokshin** [comment] 2016-08-19 13:11
@mrjana Got 1.12.1-1.el7.centos installed, running for the past 20 minutes, so far seems to work.

**Comment by ajl** [comment] 2016-08-19 19:25
12.1-rc2 seems to have solved the issue for me.  I will let you know about the stability, but looks good for me so far! Thanks @mrjana

**Comment by ajl** [comment] 2016-08-20 15:30
Next day tried to docker rm a service and now receive:
```
docker service rm ftw-nginx
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```

Cluster looks OK still:
```
docker node ls
ID                           HOSTNAME          STATUS  AVAILABILITY  MANAGER STATUS
05qbgwu04lmg7yduayqhzerte *  ip-172-31-43-171  Ready   Active        Reachable
3in4tlun2nf2ec3wkjxnjz22d    ip-172-31-43-172  Ready   Active        Leader
daz1sogbu0o7oh5i94i45lkbb    ip-172-31-43-173  Ready   Active        Reachable
```

docker ps works:
```
docker service ps ftw-nginx
ID                         NAME         IMAGE                                                       NODE              DESIRED STATE  CURRENT STATE         ERROR
21hjw2lfg4whifekols1ayee6  ftw-nginx.1  410099135227.dkr.ecr.eu-west-1.amazonaws.com/ftw-nginx:0.5  ip-172-31-43-173  Running        Running 18 hours ago  
atvyos8f36d2m6y1tg8xt0cxf  ftw-nginx.2  410099135227.dkr.ecr.eu-west-1.amazonaws.com/ftw-nginx:0.5  ip-172-31-43-173  Running        Running 18 hours ago  
```

docker info is same as above, except:
```
Server Version: 1.12.1-rc2
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.5 LTS
```

I am not sure if this is related to the original problem or not.

**Comment by joekohut** [comment] 2016-08-22 13:58
Experiencing same intermittent load balancer response using lastest version:
[root@ip-10-97-96-93 logs]# docker --version
Docker version 1.12.1, build 23cf638, experimental

Manager is ip-10-97-96-93 and container id on manager is  a1522e4ced99:
localhost does not respond at all:
[root@ip-10-97-96-93 logs]# curl localhost:8077
^C
[root@ip-10-97-96-93 logs]# curl localhost:8077
^C
[root@ip-10-97-96-93 logs]# curl localhost:8077
^C
Intermittent behavior:
[root@ip-10-97-96-93 logs]# curl 10.97.96.93:8077
Hello from [ a1522e4ced99 ] and container [ undefined ] (v0.6.2)
[root@ip-10-97-96-93 logs]# curl 10.97.96.93:8077
^C
[root@ip-10-97-96-93 logs]# curl 10.97.96.93:8077
^C
[root@ip-10-97-96-93 logs]# curl 10.97.96.93:8077
Hello from [ a1522e4ced99 ] and container [ undefined ] (v0.6.2)
[root@ip-10-97-96-93 logs]# curl 10.97.96.93:8077
^C
[root@ip-10-97-96-93 logs]# curl 10.97.96.93:8077
^C
[root@ip-10-97-96-93 logs]# curl 10.97.96.93:8077
Hello from [ a1522e4ced99 ] and container [ undefined ] (v0.6.2)

[root@ip-10-97-96-93 logs]# docker service ps moby
ID                         NAME    IMAGE                                      NODE                           DESIRED STATE  CURRENT STATE           ERROR
7hbi79r1ra8tfhdi80cu2nnjd  moby.1  private/moby-dock  ip-10-97-96-93.ec2.internal    Running        Running 30 seconds ago
bdnh2ppttwtd2gjt89065gcf7  moby.2  private/moby-dock  ip-10-97-101-150.ec2.internal  Running        Running 29 seconds ago
dktsehyzghspxu7912kjiwrkn  moby.3  private/moby-dock  ip-10-97-100-190.ec2.internal  Running        Running 30 seconds ago

Launched:
[root@ip-10-97-96-93 logs]# docker service create --replicas 3 --name moby  --network mynetwork ...
Using:
co8ic92tg58r        mynetwork           overlay             swarm

**Comment by ajl** [comment] 2016-08-22 15:29
Cluster is stable after a couple days. Listening to ports is still working. Is there a latest build I can install for continued testing? Is the rc2 link the latest?

**Comment by joekohut** [comment] 2016-08-22 16:58
experimental.docker.com now has Docker version 1.12.1, build 23cf638, experimental as of 8-18

**Comment by sdlevi27** [comment] 2016-08-22 18:05
Seeing the same behavior on 1.12.1 (build 23cf638).  I have a 3 master/5 worker cluster with a service published on port 30000 with a scale of 1.  Running a netstat on each worker shows port 30000 listening. 

The only machine which consistently works is the worker (WKR1) with the container running.  I tried a "nc -zv [eth0 IP] 30000" and "nc -zv 172.18.0.2 30000" and both consistantly worked on WKR1.  Inspecting the other workers, I can see the DOCKER-INGRESS chain shows the correct routing for the published port.  Running the same "nc -zv 172.18.0.2 30000" command times out on WKR2.  However, I can ping 172.18.0.2.

This is happening with 2 different containers.  Can not reproduce the issue by running in non-Swarm mode.

**Comment by eran-totango** [comment] 2016-08-28 12:15
@mrjana @thaJeztah @mavenugo 
any update on this issue?

**Comment by miadabrin** [comment] 2016-08-29 16:08
Having the same issue with a 3 master setup. connections freeze every fourth time. with the katest 1.12.1 build

**Comment by docwhat** [comment] 2016-08-29 20:30
You can make it worse by, for example, scaling up to 100 and then scaling back to 1 or 2.  Then you get failures for almost all.

**Comment by mrjana** [comment] 2016-08-29 23:29
Anybody who is having issues after running 1.12.1, can you please let me know if these issues started after one of the nodes is restarted?

**Comment by miadabrin** [comment] 2016-08-30 07:51
I was able to remedy the issue by downgrading to one swarm and 2 workers architecture the connections seems to be solid now . Although I have tested it on `1.12.0` and I had to recreate the overlay network since service name lookup didn't work initially. it seems to have held up for several hours now and the connections are fast and solid. I am going to test it on 1.12.1 version as well and will let you know the results.

**Comment by alon-totango** [comment] 2016-08-30 08:09
@mrjana these issues happen without restarting any node. They do sometimes get resolved by restarting the daemon.

**Comment by alontorres** [comment] 2016-08-30 08:13
@mrjana Running 1.12.1, can confirm issues happen without any nodes being restarted. Restarting the daemon after the issue occurs helps sometimes, though.

**Comment by mrjana** [comment] 2016-09-20 23:49
@alontorres If you are still having issues can you please post daemon logs? I suspect there is some gossip failures but would like to confirm

**Comment by docwhat** [comment] 2016-09-22 03:47
@mrjana:

I'm still having issues.  Here is my dockerd logs:

```
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.468759445-04:00" level=info msg="Listening for local connections" addr="/var/lib/docker/swarm/control.sock" proto=unix
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.469588964-04:00" level=info msg="Listening for connections" addr="[::]:2377" proto=tcp
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.476561863-04:00" level=info msg="5c854e0577789f20 became follower at term 0"
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.476933033-04:00" level=info msg="newRaft 5c854e0577789f20 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]"
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.476962125-04:00" level=info msg="5c854e0577789f20 became follower at term 1"
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.477185848-04:00" level=info msg="5c854e0577789f20 is starting a new election at term 1"
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.477375127-04:00" level=info msg="5c854e0577789f20 became candidate at term 2"
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.477412576-04:00" level=info msg="5c854e0577789f20 received vote from 5c854e0577789f20 at term 2"
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.477431640-04:00" level=info msg="5c854e0577789f20 became leader at term 2"
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.477442708-04:00" level=info msg="raft.node: 5c854e0577789f20 elected leader 5c854e0577789f20 at term 2"
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.478723319-04:00" level=info msg="Initializing Libnetwork Agent Local-addr=173.255.230.223 Adv-addr=173.255.230.223 Remote-addr ="
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.515479935-04:00" level=info msg="Initializing Libnetwork Agent Local-addr=173.255.230.223 Adv-addr=173.255.230.223 Remote-addr ="
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.526537911-04:00" level=error msg="Failed to delete stale ingress sandbox: another sandbox delete in progress"
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.634103656-04:00" level=warning msg="could not cleanup sandbox properly: failed to find interface with name vx-000100-5e8ym: Link not found"
Sep 21 23:19:49 gerf.org dockerd[25673]: time="2016-09-21T23:19:49.692591295-04:00" level=error msg="Could not delete state for endpoint ingress-endpoint from cluster: cannot delete entry as the entry in table endpoint_table with network id 5e8ym9gi2zdi2bdrzgdsh1hjc and key de3c3993cca845e8f6488a7471c58c8c133a4096e09d95ef675bdeff0cdd5784 does not exist"
Sep 21 23:19:50 gerf.org dockerd[25673]: time="2016-09-21T23:19:50-04:00" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.6.3-x86_64-linode70/modules.dep.bin'\nmodprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.6.3-x86_64-linode70`, error: exit status 1"
Sep 21 23:19:50 gerf.org dockerd[25673]: time="2016-09-21T23:19:50-04:00" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.6.3-x86_64-linode70/modules.dep.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.6.3-x86_64-linode70`, error: exit status 1"
Sep 21 23:19:50 gerf.org dockerd[25673]: time="2016-09-21T23:19:50-04:00" level=info msg="Firewalld running: false"
Sep 21 23:20:33 gerf.org dockerd[25673]: time="2016-09-21T23:20:33-04:00" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.6.3-x86_64-linode70/modules.dep.bin'\nmodprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.6.3-x86_64-linode70`, error: exit status 1"
Sep 21 23:20:33 gerf.org dockerd[25673]: time="2016-09-21T23:20:33-04:00" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.6.3-x86_64-linode70/modules.dep.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.6.3-x86_64-linode70`, error: exit status 1"
Sep 21 23:20:33 gerf.org dockerd[25673]: time="2016-09-21T23:20:33-04:00" level=info msg="Firewalld running: false"
Sep 21 23:20:33 gerf.org dockerd[25673]: time="2016-09-21T23:20:33-04:00" level=error msg="Failed to write to /proc/sys/net/ipv4/vs/conntrack: open /proc/sys/net/ipv4/vs/conntrack: no such file or directory"
Sep 21 23:20:33 gerf.org dockerd[25673]: time="2016-09-21T23:20:33.785190755-04:00" level=error msg="Failed to add firewall mark rule in sbox /var/run/docker/netns/494b9c13c504: reexec failed: exit status 8"
Sep 21 23:20:34 gerf.org dockerd[25673]: time="2016-09-21T23:20:34-04:00" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.6.3-x86_64-linode70/modules.dep.bin'\nmodprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.6.3-x86_64-linode70`, error: exit status 1"
Sep 21 23:20:34 gerf.org dockerd[25673]: time="2016-09-21T23:20:34-04:00" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.6.3-x86_64-linode70/modules.dep.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.6.3-x86_64-linode70`, error: exit status 1"
Sep 21 23:20:34 gerf.org dockerd[25673]: time="2016-09-21T23:20:34-04:00" level=info msg="Firewalld running: false"
```

This is after doing these steps:

```
$ docker swarm init
Swarm initialized: current node (9urcgm10z1edbqqo04zdskgfe) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-6b5ji6t4wnjb3g5s5fxtdh4r1bn6ecu7evai30xc2xwzkwtkvk-behpmly6m50gq4wz99j41jsmz \
    173.255.230.223:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

$ docker service create --replicas=1 --name=hello --publish=8080:80/tcp dockercloud/hello-world
f4iohh4s0y2rfx5n0iy6kgv7d
$ nc -zv localhost 8080
```

I'm on Linode, as you can probably tell, and it has `nf_nat` and `xt_conntrack` compiled in. I can post the `/proc/config.gz` if you want.

However, `CONFIG_IP_VS` is not set...

**Comment by ajl** [comment] 2016-09-22 03:50
12.1 eventually failed for me. 2 of my services did not respond even without scaling up and down. I'll try the next version when available.

**Comment by mrjana** [comment] 2016-09-22 03:59
@docwhat What issues are you having? If `CONFIG_IP_VS` is not set in your kernel config then load balancing is not going to work for you. You need to fix the kernel config.

**Comment by mrjana** [comment] 2016-09-22 04:01
@ajl Just to make sure all issues are fixed can you please provide daemon logs so that I can confirm(or not) that the issue that you are having is already fixed? Without that we won't know for sure if your issue is fixed in the next version.

**Comment by docwhat** [comment] 2016-09-22 04:08
Oh, bite me... I used [these instructions] to switch to Ubuntu's 16.04 distributed kernel and lo-and-behold... it works.

*sigh* Hopefully this helps someone.  It would be nice if `docker swarm init` and maybe `docker service create` printed a warning/error about not having ipvs, since it is a featured selling feature of the new swarm stuff.

**Comment by mrjana** [comment] 2016-09-22 04:13
Good to hear things work for you now. 

The problem with printing an error message during swarm init or service create is that we don't at that time where your tasks are going to run. If it is scheduled on a worker node which doesn't have ipvs then it won't work. But we don't know that during service creation for example. But there should be error logs in the problem node's daemon. 

But I do agree it would make a good user experience to know about this more quickly and more explicitly.

**Comment by ajl** [comment] 2016-09-22 04:14
@mrjana I needed to shut down the cluster for unrelated reasons and just tested prior to doing so. Please pardon my ignorance, but if I start it up again will the logs you need still be there?

**Comment by mrjana** [comment] 2016-09-22 04:17
@ajl Yeah if your cluster is simply powered down as opposed to destroyed then yeah the logs should still be there. It would greatly help to take a look at the logs. Thanks.

**Comment by thaJeztah** [comment] 2016-09-22 09:51
@mrjana perhaps something to include in `docker node inspect`? (if `CONFIG_IP_VS` is not set)?

**Comment by mrjana** [comment] 2016-09-22 20:17
@thaJeztah Yeah we can piggy back on `NodeDescription` state and provide more state about this. In fact we can even avoid scheduling on nodes which lack ip_vs the services which are have attached networks. We just need to identify the type definitions for that model since we can't clearly be exposing ip_vs in the model as it is too internal and too low level and should be replaceable.

**Comment by docwhat** [comment] 2016-09-23 06:25
Well, it isn't really whether it has ipvs. It is that the node isn't ready or able to handle services. Specifically services that match that network.  So maybe a list of the created networks it cam handle?

That would allow smart service scheduling across a heterogeneous swarm of nodes where some are on one subnet or a second network.

**Comment by mrjana** [comment] 2016-09-27 23:39
@ajl Since I did not hear from you I am going to assume that you haven't seen the problem. Please feel free to retest with 1.12.2-rc1 and let us know. I am going to close this issue now. Feel free to reopen if you see the problem again.

**Closed by mrjana** 2016-09-27 23:39 UTC
Labels: area/networking, area/swarm, priority/P1, status/more-info-needed, version/1.12

**Comment by cvuijst** [comment] 2016-09-28 05:06
@mrjana I'm sorry to hear this topic is closed. I've referred to it from the **Docker for AWS (beta)** forum, see my post: **Scaling a service down causes ports to ‘hang’** at: [(https://forums.docker.com/t/scaling-a-service-down-causes-ports-to-hang/21384/2)]. According to me, it is related and it is still an issue. Would you think it is possible to get follow-up?

**Comment by mrjana** [comment] 2016-09-28 05:15
@cvuijst The reason it is closed is because we reasonably believe that this is fixed in master as well as the just now released 1.12.2-rc1. If you are facing similar problem would you be able to test 1.12.2-rc1 from https://github.com/docker/docker/releases/tag/v1.12.2-rc1 and let us know if it fixes your problem?

**Comment by cvuijst** [comment] 2016-09-28 05:24
@mrjana Thanks for your response; much appreciated. The cluster on AWS is generated by using the AWS CloudFormation stack and the pre-baked Docker AMI as provided by the team that created the Docker for AWS beta program. Is there a way to get the new engine in the Docker for AWS beta as well? I think it would be great to test that.

**Comment by mrjana** [comment] 2016-09-28 05:26
Ah. Missed the fact that your using Docker for AWS. There would be an update to Docker for AWS with a 1.12.2-rc1 engine version shortly. Stay tuned.
