### ISSUE TITLE
named data volume instead of data container

### ISSUE THREAD

**Issue by amirabiri** [docker/docker#18034] opened 2015-11-17 07:23 UTC
(This is a **feature request**)

Perhaps this was discussed somewhere, but I couldn't find something with a quick search.

I was under the impression that the new volume subsystem in 1.9 would replace the need for data-only containers. There are a couple of issues with the data-only containers approach. Basically the need is for a persistent named set of data volumes which are initialised with the contents of respective dirs in the base image. However data-only containers add noise to both the list of containers and the list of images, and prevent me from assigning meaningful names to data volumes.

Consider these two scenarios:

1. I need a persistent volume for storing uploaded images or I want to deploy my app code/jars somewhere but still be able to re-tweak the container using it.
2. I need a persistent volume for my mysql's `/var/lib/mysql`.

Unless I missed something, in the first case I can:

1. Create a named data volume.
2. Mount it when creating a container using the notation <volume name>:<path inside container>

In this case:
 * `docker ps` will not show any redundant never-to-be-run containers.
 * `docker volume ls` will be easy to interpret - I gave a name to this particular volume when I created it.
 * `docker inspect` will easily show me that a container is using my named volume.
 * `docker images` will remain clean and not retain unnamed images after retagging.

However now consider scenario no. 2, all that has really changed is that when I create this volume, I want it initialised from `/var/lib/mysql` of a particular image. However I am forced to do the following:

1. Create a "data only container".
2. Use the `--volumes-from` option when creating the app container.

In this case:
 * `docker ps` shows x2 number of containers, and unless I choose a good naming scheme could end up very messy.
 * `docker volume ls` shows a bunch of random ids that tell me nothing about what's inside those volumes or where I've mounted them.
 * `docker inspect` again shows the random ids which are less helpful.
 * `docker images` will show unnamed images, since if I make changes to the base image, I can't easily re-create the data-only container to use the new image with the existing volumes. This container sticks around pointing to the old image.

----

There are a couple of ways I can think of that can help here:

1. Simplest option IMO - provide a `volume rename` verb. This isn't the ideal solution, but I can easily script the rest. However even if using a different solution, I think this operation should be available regardless.
2. Add some option to initialise a new volume from a declared volume of some image. The problem here is that an image can declare several volumes and they have no names, so will have to be referred to by path. Not as convenient as the `--volumes-from` switch.
3. Add or tweak existing options to `run` or `create` to give names to certain volumes when they are auto-created and initialised just as they are now. This will replace the need for `--volumes-from` and data-only containers altogether. For example:

        docker run -d --name us.mysql -v us.data:/var/lib/mysql mysql 
        docker run -d --name eu.mysql -v eu.data:/var/lib/mysql mysql 

    Will result in the creation of two data volumes named `us.data` and `eu.data` *and* their init from the contents of `/var/lib/mysql` of the `mysql` image *if* they don't exist, or mount the existing ones if they already exist.
4. Another option I thought of is declaring "data volume sets" or "groups". Which basically completely replace data-only containers. In this case the commands might look something like:

        docker volume create-set --name us.mysql.data mysql
        docker run -d --name us.mysql --volumes-from us.mysql.data mysql

    In this case the `--volumes-from` refers to the set of data volumes which are collectively named rather than individually named. The only problem here is that it creates possible clashes between volume names and container names, perhaps a solution to that is a new `--volume-set` option instead.

**Comment by cpuguy83** [comment] 2015-11-18 13:33
So the issue is you want a named volume to be pre-populated with the data from the container?
I think there is already an issue for this, if only GH search was not useless.

**Comment by amirabiri** [comment] 2015-11-18 13:43
Well that's one way to look at it. Another way to look at it is that I want to use volumes instead of data-only containers (performing the same role). And yet another way to look at it is that I want to be able to name volumes automatically created by docker.

**Comment by cpuguy83** [comment] 2015-11-18 13:50
Named volumes are specifically to be able to use it instead of data-only containers.
The one thing that it doesn't do is populate the volume.

How would you propose naming volumes that were automatically created by docker? (I assume you mean for images that have a volume specification?)

**Comment by amirabiri** [comment] 2015-11-18 14:13
Well I proposed a few ideas in my feature request above (see at the bottom).

In a nutshell, I think the ideal solution is to declare a 'volume group'. The name goes to the group, which can include a few volumes auto-created and auto-populated by docker based on image volume specification), and it is this name that is used in the run command.

Failing that, alternatives go through ability to rename volumes and/or specify how to pre-populate the volume upon creation. In the latter case the user would have to specify image:path, repeating what's already in the image volume spec. hence my view that this is the suboptimal solution.

There might be a hybrid solution, using a "namespace" like solution, i.e:

    # docker volume create --name data.app1 --from image-app1
    # docker volume ls
    DRIVER              VOLUME NAME
    local               data.app1:/var/lib/mysql
    local               data.app1:/var/www/html
    # docker run ... --volumes=data.app1:* image-app1

**Comment by LK4D4** [comment] 2016-09-16 19:00
this was fixed in #19175

**Closed by LK4D4** 2016-09-16 19:00 UTC
Labels: kind/feature
