### ISSUE TITLE
empty VOLUME is very restricted: root:root 700

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#2969] opened 2013-11-30 09:31 UTC
Is there really no way to set ownership and permissions of a VOLUME?

```
~ $ docker build -t test -
FROM ubuntu
RUN mkdir /data ; chmod 777 /data
VOLUME ["/data"]
RUN chmod 755 /data

Uploading context 2048 bytes
Step 1 : FROM ubuntu
 ---> 8dbd9e392a96
Step 2 : RUN mkdir /data ; chmod 777 /data
 ---> Using cache
 ---> 5e2d567c32ef
Step 3 : VOLUME ["/data"]
 ---> Using cache
 ---> d2832c4afd2c
Step 4 : RUN chmod 755 /data
 ---> Running in 34b05587ce60
 ---> 7c4d94ba6eed
Successfully built 7c4d94ba6eed
~ $ docker run -t -i test ls -la /data
total 8
drwx------  2 root root 4096 Nov 30 09:25 .
drwxr-xr-x 37 root root 4096 Nov 30 09:25 ..
```

I'm making a container which will run something that does not want to run as root, so 700 is particularly frustrating.

somewhat related to #1742 and #2088

**Comment by cpuguy83** [comment] 2015-02-20 19:46
So this was definitely fixed way back, I cannot reproduce.
Closing, but if you can provide a way to repro this (prefferably with a Dockerfile + run command), please ping here!

```Dockerfile
FROM busybox
RUN mkdir -p /data && chmod 777 /data && chown 1000:1000 /data
VOLUME /data
CMD ls -lh /
```

```bash
docker run -it --rm test
total 52
drwxrwxr-x    2 root     root        4.0K Feb 20 19:43 bin
drwxrwxrwx    2 default  default     4.0K Feb 20 19:43 data
drwxr-xr-x    5 root     root         380 Feb 20 19:43 dev
drwxr-xr-x    1 root     root        4.0K Feb 20 19:43 etc
drwxrwxr-x    4 root     root        4.0K Feb 20 19:43 home
drwxrwxr-x    2 root     root        4.0K Feb 20 19:43 lib
lrwxrwxrwx    1 root     root           3 May 22  2014 lib64 -> lib
lrwxrwxrwx    1 root     root          11 May 22  2014 linuxrc -> bin/busybox
drwxrwxr-x    2 root     root        4.0K Feb 27  2014 media
drwxrwxr-x    2 root     root        4.0K Feb 27  2014 mnt
drwxrwxr-x    2 root     root        4.0K Feb 27  2014 opt
dr-xr-xr-x  125 root     root           0 Feb 20 19:43 proc
drwx------    2 root     root        4.0K Feb 20 19:43 root
lrwxrwxrwx    1 root     root           3 Feb 27  2014 run -> tmp
drwxr-xr-x    2 root     root        4.0K Feb 20 19:43 sbin
dr-xr-xr-x   13 root     root           0 Feb 20 19:43 sys
drwxrwxrwt    3 root     root        4.0K Feb 20 19:43 tmp
drwxrwxr-x    6 root     root        4.0K Feb 20 19:43 usr
drwxrwxr-x    4 root     root        4.0K Feb 20 19:43 var
```

**Closed by cpuguy83** 2015-02-20 19:46 UTC
