### ISSUE TITLE
ADD command does not follow file  directory structure when copying current directory

### ISSUE THREAD

**Issue by jtoy** [docker/docker#18396] opened 2015-12-03 17:39 UTC
docker -v
Docker version 1.9.1, build a34a1d5
on mac:
docker-machine -v
docker-machine version 0.5.1 (7e8e38e)

uname -a
Darwin MacBook-Pro.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

when running:
ADD * /home/ubuntu/experiment/

I also tried with:
 ADD ./* /home/ubuntu/experiment/

if the current directory has:
folder1/file1
folder1file2
file3

the docker container will create:
/home/ubuntu/experiment/folder1
/home/ubuntu/experiment/file1
/home/ubuntu/experiment/file2
/home/ubuntu/experiment/file3

instead of (expected results):
/home/ubuntu/experiment/folder1
/home/ubuntu/experiment/folder1/file1
/home/ubuntu/experiment/folder/1file2
/home/ubuntu/experiment/file3

**Comment by thaJeztah** [comment] 2015-12-04 14:44
Thanks for reporting @jtoy, this looks like a duplicate of https://github.com/docker/docker/issues/15858, and that issue contains an explanation (and the reason we cannot fix it without breaking backwards compatibility).

If you agree this is a duplicate, could you close this issue?

**Comment by LK4D4** [comment] 2016-09-14 15:48
Closing this for lack of activity. Feel free to open new!

**Closed by LK4D4** 2016-09-14 15:48 UTC
