### ISSUE TITLE
[ASK] Pull from Docker Hub - tls: oversized record

### ISSUE THREAD

**Issue by lgas** [docker/docker#23847] opened 2016-06-22 08:56 UTC
Hi,

I try to pull an image from docker hub and get an error 
-> tls: oversized record received with length 20527.

I work behind a corporate proxy and I think that might be in relation, but can't figure out how to parametrize it. I tried to set env variable (HTTP_PROXY, etc) without succes.

So questions are : 
- Is this error caused by Proxy ? 
- If so, how can I make this work ? 

I work with Docker Toolbox on windows, 
Client :
  Version 1.11.1.
  API 1.23.
Server:
  Version 1.11.2
  API 1.23

Thanks in advance.

**Comment by thaJeztah** [comment] 2016-07-06 08:06
please keep in mind that the github issue tracker is not a general support forum, but for tracking bugs and feature requests; please consider using either one of;

- forums.docker,com
- the #docker IRC channel on freenode
- StackOverflow

I'll close this issue here, because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-07-06 08:06 UTC
