### ISSUE TITLE
start panic

### ISSUE THREAD

**Issue by cucyzrd** [docker/docker#27940] opened 2016-11-01 09:42 UTC
```
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x7e9de0, 0xc820117f10)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200ef2e8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7e9de0, 0xc820117f10)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200eebf8, 0xc82001a0c8, 0xc8200eed08)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820051630, 0x7fb85c367728, 0xc820117f10)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82006ea00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74e5e0, 0x8ffda0, 0x13, 0x846308, 0x4, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74e5e0, 0x8ffda0, 0x13, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74e5e0, 0x8ffda0, 0xc82006ea00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x8491b8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8df0e0, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001800, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x7e9de0, 0xc820117f10)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200ef2e8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7e9de0, 0xc820117f10)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200eebf8, 0xc82001a0c8, 0xc8200eed08)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820051630, 0x7f7ebb059728, 0xc820117f10)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82006ea00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74e5e0, 0x8ffda0, 0x13, 0x846308, 0x4, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74e5e0, 0x8ffda0, 0x13, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74e5e0, 0x8ffda0, 0xc82006ea00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x8491b8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8df0e0, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001500, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

**Comment by mlaventure** [comment] 2016-11-01 15:56
@cucyzrd 

I would need more detail if possible:
 - output of `docker info`
 - output of `docker-runc --version`
 - what command where you running when it happened
 - more of the daemon logs

**Comment by conversica-aaronpa** [comment] 2016-11-01 22:43
I've got this mystery as well, and very little relevant debugging experience (daemon logs?).
```
aaronpa@aaronpa-VirtualBox:~$ docker-runc --version
runc version 1.0.0-rc2
commit: f59ba3cdd76fdc08c004f42aa915996f6f420899
spec: 1.0.0-rc2-dev
aaronpa@aaronpa-VirtualBox:~$ docker info
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 6
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859 GiB
Name: aaronpa-VirtualBox
ID: 57KY:LO2B:N63M:F3LH:GVNC:3HCT:644L:KFPQ:M3WG:ZGRZ:V5BJ:5N57
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
aaronpa@aaronpa-VirtualBox:~$ docker-runc --version
runc version 1.0.0-rc2
commit: f59ba3cdd76fdc08c004f42aa915996f6f420899
spec: 1.0.0-rc2-dev
```

**Comment by mlaventure** [comment] 2016-11-01 22:51
You should be able to get the docker daemon logs via: `journalctl -u docker.service`

If you could also specify which command resulted in this panic, it'll be helpful.

Thanks!

**Comment by conversica-aaronpa** [comment] 2016-11-01 23:16
I'm able to get into the image if I override my ENTRYPOINT script. Here are the last several lines of output from the daemon logs:
```
Nov 01 15:28:54 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:28:54.126685209-07:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Nov 01 15:28:54 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:28:54.126706578-07:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Nov 01 15:29:16 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:29:16.640449413-07:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Nov 01 15:29:16 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:29:16.640471821-07:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Nov 01 15:29:16 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:29:16.833586280-07:00" level=error msg="Handler for POST /v1.24/containers/b969a481a677d41ec0564343506cf74e2c3f9ac641d14a5f0777084910b0c235/resize returned error: rpc error: code = 2 desc = containerd: container not found"
Nov 01 15:29:32 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:29:32.639225294-07:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Nov 01 15:29:32 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:29:32.639248925-07:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Nov 01 15:29:32 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:29:32.977472336-07:00" level=error msg="Handler for POST /v1.24/containers/40ed72f67032ce745b950058403ef94b8b23c425e131a62949a438275b477909/resize returned error: Container 40ed72f67032ce745b950058403ef94b8b23c425e131a62949a438275b477909 is not running"
Nov 01 15:29:43 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:29:43.635384519-07:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Nov 01 15:29:43 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:29:43.635620721-07:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Nov 01 15:29:43 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:29:43.817897378-07:00" level=error msg="Handler for POST /v1.24/containers/213b7f582bddf979efa85c0032e95155ebea6c4fa8fcc87f2496b63c342fcf79/resize returned error: rpc error: code = 2 desc = containerd: container not found"
Nov 01 15:29:57 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:29:57.612063595-07:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Nov 01 15:29:57 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:29:57.612390992-07:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Nov 01 15:31:01 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:31:01.416603119-07:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]"
Nov 01 15:31:01 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:31:01.416966617-07:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
Nov 01 15:31:01 aaronpa-VirtualBox dockerd[1029]: time="2016-11-01T15:31:01.788956035-07:00" level=error msg="Handler for POST /v1.24/containers/97a01a2500bd474b871b2e39096be61cd5bbcf68374b1e46db1cd130b1263217/resize returned error: Container 97a01a2500bd474b871b2e39096be61cd5bbcf68374b1e46db1cd130b1263217 is not running"
aaronpa@aaronpa-VirtualBox:~$ 

```

**Comment by mlaventure** [comment] 2016-11-01 23:29
@conversica-aaronpa You still haven't provided what command(s) lead to this panic :sweat_smile:

**Comment by conversica-aaronpa** [comment] 2016-11-01 23:30
Example of how I'm seeing what I think is the same problem:
```
aaronpa@aaronpa-VirtualBox:/media/sf_git/qa/messaging/yii-client$ docker run -it -v $(pwd):/src --entrypoint /src/passthrough_entrypoint.sh test-runner-yii-client-suite /bin/echo foo bar roo
Passthrough
foo bar roo
aaronpa@aaronpa-VirtualBox:/media/sf_git/qa/messaging/yii-client$ docker run -it -v $(pwd):/src test-runner-yii-client-suite echo foo bar roopanic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x7ea960, 0xc820128070)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200ef2e8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ea960, 0xc820128070)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200eebf8, 0xc82001a0d0, 0xc8200eed08)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820051630, 0x7f3db730f728, 0xc820128070)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82006ea00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74f160, 0x900ae8, 0x13, 0x846e88, 0x4, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74f160, 0x900ae8, 0x13, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74f160, 0x900ae8, 0xc82006ea00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x849d38, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8dfde0, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001500, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
aaronpa@aaronpa-VirtualBox:/media/sf_git/qa/messaging/yii-client$ 
```
Content of the Dockerfile entrypoint scripts:
```
aaronpa@aaronpa-VirtualBox:/media/sf_git/qa/messaging/yii-client$ cat rfgrid_entrypoint.sh 
#!/bin/bash
echo "rfgrid_entrypoint.sh starting"
PATH=$PATH:/srv
export PATH
heads=${@:1:$(($# - 1))}
tail=${@:$#}
rfcall="$heads -v remote_url:http://$HUB_PORT_4444_TCP_ADDR:$HUB_PORT_4444_TCP_PORT/wd/hub $tail"
eval $rfcall
```
and
```
aaronpa@aaronpa-VirtualBox:/media/sf_git/qa/messaging/yii-client$ cat passthrough_entrypoint.sh 
#!/bin/bash
echo Passthrough
exec "$@"
aaronpa@aaronpa-VirtualBox:/media/sf_git/qa/messaging/yii-client$ 
```

**Comment by conversica-aaronpa** [comment] 2016-11-02 18:31
I think the problem as I'm experiencing it may be related to Windows (CRLF) vs Linux (LF) line endings in my entrypoint script. Changing to Linux style (didn't mean to go to Windows at all) seems to have resolved my problem.

**Comment by mlaventure** [comment] 2016-11-02 22:22
Oh, I see.

It makes sense. Linux doesn't know how to take care of `CRLF` so it didn't find a binary called `/bin/bash\r` (which is correct).

This [PR](https://github.com/opencontainers/runc/pull/1117) removed the panic.

**Comment by ironsmile** [comment] 2016-12-01 11:17
I am able to reproduce this without involving any fancy new line endings. This leads me to believe that the problem is general and is not limited to use case of @conversica-aaronpa.

I have a very simple script

```
$ cat test-ha
#!/bin/bash
echo HA
```

which has its executable flag set. Then the familiar panic happens when trying to execute it in a container:

```
$ docker run --rm -v "`pwd`:/opt" alpine:3.4 /opt/test-ha
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x88f8a0, 0xc820143a40)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8201112e8)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x88f8a0, 0xc820143a40)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc820110bf8, 0xc82001a088, 0xc820110d08)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc8200587d0, 0x7fb719549428, 0xc820143a40)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc820076780, 0x0, 0x0)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x7f45a0, 0x9a4d88, 0x13, 0x8ebac8, 0x4, 0xc820111268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x7f45a0, 0x9a4d88, 0x13, 0xc820111268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x7f45a0, 0x9a4d88, 0xc820076780, 0x0, 0x0)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x8ee970, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x984240, 0x51, 0x0, ...)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001980, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

**System Information**

My docker info:

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 45
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 85
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: ZJZF:33JT:3225:NPWU:LWPM:WIET:FRBV:2I4P:T2MT:NLJO:TAGL:X6Z2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 40
 System Time: 2016-12-01T11:09:25.858337518Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

I am running this on OSX 10.11.6. I've also tested the same thing on docker 1.12.1 running on CentOS 7.2.1511 and the result is the same.

**Comment by cpuguy83** [comment] 2016-12-01 13:23
@ironsmile This is because alpine doesn't contain `/bin/bash`, and runc is panicing with the error that it couldn't find `/bin/bash` to execute.

The actual panic was removed in opencontainers/runc#1117 which now just returns an error instead of panicing.

I'm going to close this since it looks like a non-issue.

**Closed by cpuguy83** 2016-12-01 13:23 UTC
Labels: area/runtime, kind/bug

**Comment by mcandre** [comment] 2017-04-10 19:33
Which part of the system is depending on `/bin/bash` rather than `/bin/sh`?

My Go application was working in Alpine just fine, until today, when I see these weird error traces.

**Comment by cpuguy83** [comment] 2017-04-10 19:44
@mcandre Nothing in docker relies on `/bin/bash`. It's wholly dependent on the image.
If you have a particular problem please open a new... or it might be better to discuss on slack first.

@cyberbeast Not sure why you thumbs-downed my comment
Feel free to comment, open a new issue, or discuss on slack if you have a problem.
