### ISSUE TITLE
How to force docker daemon use `DOCKER_OPTS`

### ISSUE THREAD

**Issue by jas0n1ee** [docker/docker#18377] opened 2015-12-02 21:13 UTC
I set `DOCKER_OPTS="-g /data/docker"` in /etc/default/docker on a Ubuntu machine to force docker build and store images on certain disk. 

When I run `docker run` or `docker build` it seems the`DOCKER_OPTS` method works fine. But when I run `sudo docker daemon -H tcp://0.0.0.0:2375 &` to start a daemon, it will got empty list with `GET /images/json` . Then I found if I add `-g /data/docker` after daemon command, it works. 

So how can I set something like `DOCKER_OPTS` in `/etc/default/docker` to force docker daemon search that folder for images?

**Comment by thaJeztah** [comment] 2015-12-02 22:37
the `DOCKER_OPTS` variable is used when running the daemon via the init system (sysvinit or upstart), see https://github.com/docker/docker/blob/master/contrib/init/upstart/docker.conf#L42

If you're manually starting the daemon, you'll have to provide those options on the command line

I'm closing this issue because this is a question, not a bug or feature request, but feel free to comment here after I've closed this issue

**Comment by thaJeztah** [comment] 2015-12-02 22:39
So basically, if you're starting the docker via upstart/sysvinit; `sudo start docker`, it should use those settings

**Closed by thaJeztah** 2015-12-02 22:39 UTC
