### ISSUE TITLE
Debian library has issues

### ISSUE THREAD

**Issue by wikier** [docker/docker#19880] opened 2016-02-01 09:45 UTC
As discussed at issue #19757, there is something wrong in the last build 6 days ago of the [Debian library](https://hub.docker.com/r/library/debian/tags/).

It doe snot matter the tag or changing the mirror, on `apt-get upgrade` you always get that the index file is corrupted, for instance:

```E: The package index files are corrupted. No Filename: field for package ucf.```

**Comment by wikier** [comment] 2016-02-01 09:47
```$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64```

```$ docker info
Containers: 4
Images: 84
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 96
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
CPUs: 4
Total Memory: 15.57 GiB
Name: wolfcastle
ID: HZT2:T5QM:L72S:WQG6:2ZIV:TJ7X:P4CJ:6T3U:2VMO:LIFJ:33PO:SVT5
Username: wikier
Registry: https://index.docker.io/v1/
WARNING: No swap limit support```

**Comment by wikier** [comment] 2016-02-01 10:00
Unless there is a detail I'm not aware, I can say there is an issue on those images. If I base my container on an old built image ([wikier/base-dev](https://hub.docker.com/r/wikier/base-dev/)) the issue disappears.

**Comment by thaJeztah** [comment] 2016-02-01 10:24
@wikier could you open this issue in the issue tracker for the official images? Since this is not a bug in docker (the software), but an issue with an official image, that would be the right location to report this; https://github.com/docker-library/official-images/issues

I'll close this issue here, but feel free to comment here after I've closed this issue

**Closed by thaJeztah** 2016-02-01 10:24 UTC

**Comment by wikier** [comment] 2016-02-01 10:36
Sure, sorry.
