### ISSUE TITLE
expose docker build content to the RUN command

### ISSUE THREAD

**Issue by ibukanov** [docker/docker#22273] opened 2016-04-23 17:56 UTC
Currently the only way to expose a file from the build source content that is sent to the docker daemon during the build is to use COPY or ADD command in the Dockerfile to copy the file into the image. When the file is only used as a source for the compiler that is run in a subsequent RUN command this inevitably results in the image bloat as the file is stuck committed to the image as intermediate layer even if the RUN command removes it.

To avoid such bloat it would be nice if the RUN command could access the build content directly without the need to use intermediate COPY or ADD. For example, the content could be exposed over HTTP over some unix socket so the RUN command could use curl or similar to access the files either individually or as a tar file. Alternatively the content could be mounted as a directory. 

With such access the compiler after it generated the binaries could just remove any temporaries leaving the image with the minimum number of files. In addition the RUN command could perform arbitrary tree refactoring/filtering without keeping the original source tree as a useless layer.

**Comment by thaJeztah** [comment] 2016-04-23 18:03
Think this is a duplicate of https://github.com/docker/docker/issues/3056

**Closed** 2016-04-23 21:00 UTC
Labels: area/builder, kind/feature
