### ISSUE TITLE
Space Exhaustion on 1.11 Container Mounts?

### ISSUE THREAD

**Issue by steve-gray** [docker/docker#22677] opened 2016-05-11 22:23 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-662217-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/vgDocker/lvData
 Metadata file: /dev/vgDocker/lvMetadata
 Data Space Used: 303.2 MB
 Data Space Total: 112.7 GB
 Data Space Available: 112.4 GB
 Metadata Space Used: 1.024 MB
 Metadata Space Total: 5.365 GB
 Metadata Space Available: 5.363 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.26 GiB
Name: dev
ID: UHUM:JHO5:LIMR:BBW7:3RLF:VECQ:VO2W:Q32W:VGKJ:FJIX:454P:G2GV
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 7 running in VM. 

**Steps to reproduce the issue:**
1. docker run --rm -it centos:7 df -h

**Describe the results you received:**
When running various operations inside the container, it seems that a huge amount of space is consumed on the /etc/hosts mount. For example:

````
[root@dev sgray]# docker run --rm -it centos:7 df -h
Filesystem                                                                                        Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:0-662217-97b5ea95167e5f153339f7489d101cd0216fb6cf35ac4d0aa075db0ee65ad52a   10G  241M  9.8G   3% /
tmpfs                                                                                              16G     0   16G   0% /dev
tmpfs                                                                                              16G     0   16G   0% /sys/fs/cgroup
/dev/mapper/centos-root                                                                            12G  1.9G  8.8G  18% /etc/hosts
shm                                                                                                64M     0   64M   0% /dev/shm
[root@dev sgray]#
````

**Describe the results you expected:**
The /etc/hosts mount should not be showing so much used space. Specifically if I do cat /etc/hosts - it shows 3 lines, which doesnt quite add up to nearly 2GB. 

**Additional information you deem important (e.g. issue happens only occasionally):**

The reason this is problematic is that when I run docker-in-docker type CI testing, we've got issues where even though we mount a volume to hold /var/lib/docker content - the /etc/hosts mount just fills up almost immediately and dies. For example, here's another machine, here's the output from the most affected machine we have. Note I'm literally just starting up a blank container and running the command to show free space. 

````
[sgray@build ~]$ docker run --rm -it centos:7 df -h
Filesystem                                                                                        Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:0-662217-c65cb6b4ab5c21adb37aa84505e2b7ab4653580238f5ddd06c4cc6e131368781   10G  241M  9.8G   3% /
tmpfs                                                                                              24G     0   24G   0% /dev
tmpfs                                                                                              24G     0   24G   0% /sys/fs/cgroup
/dev/mapper/centos-root                                                                            12G   10G  651M  95% /etc/hosts
shm                                                                                                64M     0   64M   0% /dev/shm
[sgray@build ~]$
````

**Comment by thaJeztah** [comment] 2016-05-11 22:28
Thanks for reporting, and for the detailed description. This looks like a duplicate of https://github.com/docker/docker/issues/22677. Given that you're also running on devicemapper, I'm wondering if this is an issue there.

I'll close this issue, because it's a duplicate, please continue the discussion in https://github.com/docker/docker/issues/22677

**Closed by thaJeztah** 2016-05-11 22:28 UTC

**Comment by steve-gray** [comment] 2016-05-11 22:31
@thaJeztah - You've closed it as a duplicate of itself?

**Comment by thaJeztah** [comment] 2016-05-11 22:42
Oh boy, me and clipboards ... Here's the right issue; https://github.com/docker/docker/issues/22610

**Comment by justincormack** [comment] 2016-05-12 16:42
I think its actually a dup of #18867

**Comment by thaJeztah** [comment] 2016-05-12 16:47
Actually looking at the report above, it's also checking using `df -h`. And that is showing the size on the host?

```
docker run --rm -it alpine df -h
Filesystem                Size      Used Available Use% Mounted on
none                     59.0G     20.6G     35.4G  37% /
tmpfs                  1000.8M         0   1000.8M   0% /dev
tmpfs                  1000.8M         0   1000.8M   0% /sys/fs/cgroup
/dev/vda2                59.0G     20.6G     35.4G  37% /etc/resolv.conf
/dev/vda2                59.0G     20.6G     35.4G  37% /etc/hostname
/dev/vda2                59.0G     20.6G     35.4G  37% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                  1000.8M         0   1000.8M   0% /proc/kcore
```

In the above output, you can see that `/etc/resolv.conf`, `/etc/hostname` and `/etc/hosts` all seem to use a lot of space, but that's just the disk that docker is running on?

**Comment by justincormack** [comment] 2016-05-12 16:50
Oh yes you are right, sorry, yes it is the host space that is measured.
