### ISSUE TITLE
Docker container increasing size by 1gig everyday

### ISSUE THREAD

**Issue by wattletimber** [docker/docker#23303] opened 2016-06-06 10:33 UTC
I have installed mongodb and meteor on an Amazon Instance EC2. my main challenge is that the container is increasing in size everyday and am running in short of disk space. I really need your assistance here, am running in short of disk space now.
![compined screen shot](https://cloud.githubusercontent.com/assets/19662899/15819324/d3535146-2be2-11e6-9ad3-23107ab3a0cd.png)

**Comment by thaJeztah** [comment] 2016-06-06 12:46
@wattletimber I gave a suggestion on https://github.com/docker/docker/issues/7758#issuecomment-223905181, but I see you posted the same question in 10 different locations; please note that the GitHub issue tracker is for tracking bugs and feature requests, not a support forum, for questions about using docker, please use either one of:

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

I'll close this issue because this is a support question, not a bug

**Closed by thaJeztah** 2016-06-06 12:46 UTC
