### ISSUE TITLE
RUN apt-get update too slow during building an image, on EC2

### ISSUE THREAD

**Issue by bitliner** [docker/docker#9766] opened 2014-12-21 16:35 UTC
I am building an image on AWS EC2 (xlarge instance) but it is too slow, running `RUN apt-get update` takes like hours. The image is based on `ubuntu:14.04` image or `dockerfile/python` image.

Running apt-get update at OS level is normally fast.

I followed this [post](http://www.danstutzman.com/blog) trying to make it faster, but nothing changes.

The bottleneck looks to be when apt-get logs `12% [Waiting for headers]`. Running it from inside the container, this is the output:
```
$ apt-get -o Debug::pkgProblemResolver=true -o Debug::Acquire::http=true update 
0% [Working]GET /ubuntu/dists/trusty/InRelease HTTP/1.1
Host: archive.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.0.1ubuntu2)


HTTP/1.1 404 Not Found
Date: Mon, 22 Dec 2014 05:57:36 GMT
Connection: keep-alive
Transfer-Encoding: chunked

Ign http://archive.ubuntu.com trusty InRelease
12% [Working]GET /ubuntu/dists/trusty-updates/InRelease HTTP/1.1
Host: archive.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.0.1ubuntu2)


12% [Waiting for headers]
```

Furthermore, the file /etc/apt/source.list of the container is different (pointing to archive.ubuntu.com) compared to the one on the host machine (whose urls point to ec2 servers for ubuntu).
But substituting the file /etc/apt/source.list of the host machine with the one from the container, `apt-get update` on the host machine is still fast. 

It looks like there are problems regarding the network, couldn't find them until now.
/etc/resolve.conf of docker container is the same of the host machine. 

Suggestions?

**Comment by unclejack** [comment] 2015-01-05 16:01
@bitliner Please provide the full output of `docker info`, `docker version`, `uname -a` and the type of EC2 instance you've used.

**Comment by erikh** [comment] 2015-01-05 18:17
Have you tried doing this on the same host as the containers you are 
running? There could be a lot of issues here.

On Mon, Jan 5, 2015 at 8:01 AM, unclejack <notifications@github.com> 
wrote:
> @bitliner Please provide the full output of docker info, docker 
> version, uname -a and the type of EC2 instance you've used.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
=

**Comment by bitliner** [comment] 2015-01-06 19:31
Well, I've solved changing the image the Dockerfile was based on.

**Comment by bitliner** [comment] 2015-01-28 11:36
I posted here some other detail.
It looks like my ec2 instance has problems to validate SSL certificate, that could be the reason why `apt-get update` takes forever...
For example python pip fails to install each python module, because the verification of ssl fails. The problem is only inside containers, on the host all works fine.

output of `docker info`

```
Containers: 137
Images: 277
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 551
Execution Driver: native-0.2
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 29.96 GiB
Name: ip-172-32-2-166
ID: E5EA:XLKE:4DPU:V5PJ:YVDS:J2KY:XCNR:AU4U:XR2D:II52:2TXA:WFUI
WARNING: No swap limit support

``` 

output of `docker version`

```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

output of `uname -a`

```
Linux ip-172-32-2-166 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by unclejack** [comment] 2015-02-02 09:34
@bitliner Please ensure that your system is fully patched and up to date. You're running an outdated kernel and that's never a good thing. Please run `apt-get update && apt-get dist-ugprade` to update your system.

You might also want to pull those images again to ensure it's not an issue with an older version of an image.

Are you using `ufw`, `firewalld` or some other type of custom netfilter (iptables) firewall? Have you installed anything not usually found on a default install of Ubuntu which touches the firewall?

**Comment by bitliner** [comment] 2015-02-02 10:10
Thanks for your suggestions.

I will update the kernel. I will try to pull again the image.

About the firewall, I have the AWS EC2 security groups installed, but the outbound traffic is allowed at all, while the inbound traffic only for interesting ports.

**Comment by bitliner** [comment] 2015-02-04 13:38
Updated and restarted the machine, but still same problem.

**Comment by unclejack** [comment] 2015-02-04 13:41
@bitliner I'll have to try this myself to see if I can reproduce this. Can you tell me what's the exact AMI you've used, please?

**Comment by bitliner** [comment] 2015-02-04 23:36
I realized the kernel was not updated yet. Let me test after reboot, hope with the new kernel this issue is going to be solved. I have also tested on a very similar machine, but with the kernel updated, and it was fixed

**Comment by tiborvass** [comment] 2015-02-08 00:40
@bitliner so did the kernel update fix your issue?

**Comment by thaJeztah** [comment] 2015-03-05 23:01
ping @bitliner, have you been able to test yet?

**Comment by neofreko** [comment] 2015-03-06 07:12
I was having similar issue (debian jessie on boot2docker) and was suspecting DNS and mirroring stuff. However, ulimit might be a factor here, as this bug states: https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1332440

I changed my boot2docker ulimit from "unlimited" to 2048, and apt-get started moving noticeably faster.

**Comment by thaJeztah** [comment] 2015-03-06 07:54
@bitliner @neofreko docker 1.6.0 will add support for setting `ulimits` per container (https://github.com/docker/docker/pull/9437), so that would help?

**Comment by bitliner** [comment] 2015-03-06 09:04
Sorry, I did not test it yet. I am not managing that machine anymore, on the new machines all work like a charm.

**Comment by tiborvass** [comment] 2015-03-06 17:02
Thanks @bitliner !

I'm gonna close this issue since the OP could not reproduce it, and @neofreko mentioned he could fix his issue by changing ulimit on boot2docker to 2048. Please continue the discussion if needed.

**Closed by tiborvass** 2015-03-06 17:02 UTC
