### ISSUE TITLE
Cannot install from Linux binary

### ISSUE THREAD

**Issue by alanhdu** [docker/docker#15569] opened 2015-08-13 19:14 UTC
When I try to install Docker from the binary at https://get.docker.com/builds/Linux/x86_64/docker-1.8.1, I get:

```bash
root@grader:~# wget https://get.docker.com/builds/Linux/x86_64/docker-1.8.1
root@grader:~# chmod 775 docker-1.8.1 

root@grader:~# ./docker-1.8.1 version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)
```

I'm running this on Ubuntu 14.04 64-bit on a Digital Ocean droplet:
```bash
root@grader:~# uname -a
Linux grader 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment] 2015-08-13 20:03
This is expected, because you didn't update the running daemon; to do that, stop the daemon, and find where it's installed (`which docker`), then replace the old binary with the new binary.

However, we now have a new APT/YUM repository, that provides dynamically linked binaries; see the blog and install instructions here; https://blog.docker.com/2015/07/new-apt-and-yum-repos/

I'm going to close this issue, because this is not a bug

**Closed by thaJeztah** 2015-08-13 20:03 UTC

**Comment by alanhdu** [comment] 2015-08-13 21:07
I don't think there's actually a running daemon here. I've been provisioning fresh Digital Ocean droplets from https://github.com/bflad/chef-docker, which AFAIK grabs the corresponding binary and plops it in place (I could be wrong though... my chef-and-docker-fu are pretty underdeveloped) 

So:
```bash
root@grader:~# which docker
/usr/bin/docker

root@grader:~# /usr/bin/docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)
```

**Comment by phemmer** [comment] 2015-08-14 02:53
> I don't think there's actually a running daemon here.

There is, note the last line in that `docker version` output:

    Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)

This shows that the server responded, but the server doesn't support the API version the client is using.
