### ISSUE TITLE
docker build --net=host

### ISSUE THREAD

**Issue by jacky68147527** [docker/docker#21568] opened 2016-03-28 09:09 UTC
docker -g /data/docker -H unix:///var/run/docker.sock -H tcp://127.0.0.1:14040 -b none

docker build can't use host network, how to resolve it

**Comment by coolljt0725** [comment] 2016-03-28 09:33
This is a duplicate of #10324 
And there is a pr #20987 work on this

**Closed** 2016-03-28 14:15 UTC
