### ISSUE TITLE
Can't stop containers (rpc error: code = 14 desc = grpc: the connection is unavailable)

### ISSUE THREAD

**Issue by CrimsonGlory** [docker/docker#31498] opened 2017-03-02 21:49 UTC
**Description**
Can't stop containers. 
```
docker-compose stop
ERROR: for backupdbsystem_db_1  Cannot stop container 869ccc14268f0c1db0b4fa5b0cfdcb5385ecfb3c86ef6c936c096e3625c348c8: Cannot kill container 869ccc14268f0c1db0b4fa5b0cfdcb5385ecfb3c86ef6c936c096e3625c348c8: rpc error: code = 14 desc = grpc: the connection is unavailable
```

**Steps to reproduce the issue:**
1. System is under heavy load (right now: "load average: 22.22, 22.30, 23.15", but was about 35 when things started to go wrong)
2. docker stop <any container>
3. error

**Additional information you deem important (e.g. issue happens only occasionally):**
Complete docker.log file
[docker.log file](http://www.mediafire.com/file/ru58oxpfr8w3nga/complete_logs.log)

Relevant:
```
time="2017-03-01T18:12:29.611724770-05:00" level=error msg="Handler for POST /v1.26/containers/backupdbsystem_db1/exec returned error: No such container: backupdbsystem_db1" 
time="2017-03-02T14:15:36.045669576-05:00" level=error msg="attach: stdout: write unix /var/run/docker.sock->@: write: broken pipe" 
time="2017-03-02T14:15:36.045723534-05:00" level=error msg="Error running exec in container: exec attach failed with error: write unix /var/run/docker.sock->@: write: broken pipe" 
ESC[34mINFOESC[0m[0014] Firewalld running: false                     
panic: close of nil channel

goroutine 206231 [running]:
panic(0x8082e0, 0xc420664f50)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/containerd/supervisor.(*Supervisor).execExit.func1(0xc4205cc960, 0xc420153110, 0x0)
        /tmp/tmp.ezSaVZlwBZ/src/github.com/docker/containerd/supervisor/exit.go:90 +0x10c
created by github.com/docker/containerd/supervisor.(*Supervisor).execExit
        /tmp/tmp.ezSaVZlwBZ/src/github.com/docker/containerd/supervisor/exit.go:91 +0xee
time="2017-03-02T14:25:02.716919328-05:00" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 13 desc = transport is closing" 
time="2017-03-02T14:25:12.171328514-05:00" level=warning msg="failed to retrieve containerd version: rpc error: code = 14 desc = grpc: the connection is unavailable" 
```

docker-containerd-shim seems running
```
# ps aux | grep docker-containerd | grep 869ccc
root      2548  0.0  0.0 413292   904 ?        Sl   Mar01   0:00 docker-containerd-shim 869ccc14268f0c1db0b4fa5b0cfdcb5385ecfb3c86ef6c936c096e3625c348c8 /var/run/docker/libcontainerd/869ccc14268f0c1db0b4fa5b0cfdcb5385ecfb3c86ef6c936c096e3625c348c8 docker-runc
```

But sending SIGUSR1 to process does not produce any output on docker.log
```
# kill -SIGUSR1 2548
```

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 33
 Running: 12
 Paused: 0
 Stopped: 21
Images: 229
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 1058
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ra5qlktmfa1am2u830g715tp4
 Is Manager: true
 ClusterID: ol2zwaybi9d0mx2js74u3rkbf
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.20.46
 Manager Addresses:
  192.168.20.46:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: N/A (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f 
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 61.05 GiB
Name: codexServer
ID: I3P4:SLVS:BBBQ:SBVF:3XLC:CWAY:3RCM:EFNR:TJPK:RRU7:6WJO:C43J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: crimsonglory
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by cpuguy83** [comment] 2017-03-03 15:29
ping @mlaventure 
Looks like containerd panic'd here.

**Comment by CrimsonGlory** [comment] 2017-03-03 16:16
(rebooting the server fixed the issue)
These two issues #31383 #30984 were also under heavy load.

**Comment by mlaventure** [comment] 2017-03-03 18:17
@CrimsonGlory Yes, this is a duplicate of the #31383 issue you mentioned in your last comment 

Going to close this one as duplicate.

Thanks for the report

**Closed by mlaventure** 2017-03-03 18:17 UTC
Labels: area/runtime, kind/bug, version/1.13
