### ISSUE TITLE
Windows volumes : getting an "Invalid bind mount spec "...": invalid mode: \app." error

### ISSUE THREAD

**Issue by Zeychiel** [docker/docker#27587] opened 2016-10-20 16:31 UTC
**Description**
Hi,
I am running into troubles  trying to create a tinny container running Goang code. This used to work, but an error appeared after updating docker.
It seems like with Docker supporting Windows, the -v opt converts :/gopath which should be the destination, into something different.
Thanks for the advises,

**Steps to reproduce the issue:**
The command generating the error is : 
docker run --rm -it -v "$GOPATH":/gopath -v "$(pwd)":/app -e "GOPATH=/gopath" -w /app golang:latest sh -c 'CGO_ENABLED=0 go build -a --installsuffix cgo --ldflags="-s" -o bin/gameblr beebetApp' 

**Describe the results you received:**
Error response from daemon: Invalid bind mount spec "D:\\Dev\\GameBlr.gg\\DevBack\\gameblr.gg:\\gopath": invalid mode: \gopath.
See 'docker run --help'.

**Describe the results you expected:**
Again, this used to create a really tiny container running Go code.

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried using gitBash (which I usually use) and cmd.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
$ docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 153
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 164
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.24-boot2docker
Operating System: Boot2Docker 1.12.2 (TCL 7.2); HEAD : 9d8e41b - Tue Oct 11 23:40:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: I4B7:IQ34:6TKO:VSDE:JGY5:6XJB:7U7W:NIG2:QN2S:IDCR:D3BI:GBN4
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 36
 System Time: 2016-10-20T16:21:35.230735543Z
 EventsListeners: 0
Username: zedd
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

```

**Comment by Zeychiel** [comment] 2016-10-21 22:02
This actually works like a charm using Linux instead of Windows. Did I miss something on the usage of volumes on Windows ?!

**Comment by jhowardmsft** [comment] 2016-10-22 05:35
The semantics are no different between a remote linux daemon from a remote Windows client. The volume spec is local to the daemon, not the client, and must be provided in the file system semantics of the daemon.

So for example: If /share exists on the Linux daemon host, and you are using a remote Windows client, and want to bind mount /share from the linux host into the container you would run something similar to `docker run -it --rm -v /share:/containerdestination imagename command`.

You cannot use -v c:\somepath\on\the\windowsdaemon:/pathonalinuxhost. Bind mounts originate from the target host, not the client.

Hence closing this 'by design'.

**Closed by jhowardmsft** 2016-10-22 05:35 UTC
Labels: version/1.12
