### ISSUE TITLE
Error response from daemon: Cannot start container ... invalid argument

### ISSUE THREAD

**Issue by CGavrila** [docker/docker#14819] opened 2015-07-21 18:03 UTC
I am trying to run a simple "Hello world" example with docker, but all I get is this error:

```
$ sudo docker run ubuntu ls
Error response from daemon: Cannot start container 5bdd2cc7e430fde99ad30fba4c72bd3c62507f75f2581721e5c3172364f41364: invalid argument
```

Docker/system info:

```
$ uname -a
Linux fatcat 3.13.0-57-generic #95~precise1-Ubuntu SMP Mon Jun 22 09:43:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ docker info
Containers: 13
Images: 14
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 40
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 8
Total Memory: 15.32 GiB
Name: fatcat
ID: D4YA:R437:TXWY:LNJ3:OEMZ:232K:HSTB:HVX5:NDU7:H5XP:UX3B:TA6B
WARNING: No swap limit support

$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

I've tried a couple of things that I've seen in other issues, but it didn't get me anywhere.

**Comment by pl33g0r** [comment] 2015-07-21 23:34
I am hitting the same issue here 

Use the commands below to provide key information from your environment:

docker version: 
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

docker info:
Containers: 4
Images: 31
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 39
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 31.34 GiB
Name: dock01
ID: BGPT:QL3L:VFWB:XVAF:IUEX:BB3G:KNYR:D7P6:ZMIH:QBF5:7CGD:BXUV
WARNING: No swap limit support
uname -a: 

Linux dock01 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):
physical
List the steps to reproduce the issue:
1. pulled docker image (pl33g0r/ubu-slave
2.
3.

Describe the results you received:
I am trying to run container I pulled from my dockerhub repo. 
 docker run pl33g0r/ubu-slave:latest
exec: "": executable file not found in $PATH
Error response from daemon: Cannot start container 4a802c6c77a796312e71bbcc85c210fd1bee43acb355ed6d4878c92243c5fb8f: [8] System error: exec: "": executable file not found in $PATH
Describe the results you expected:

Provide additional info you think is important:

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by hqhq** [comment] 2015-07-22 01:48
Probably you have short support from kernel, what does `./contrib/check-config.sh` say?

**Comment by pl33g0r** [comment] 2015-07-22 02:12
I am not able to find contrib (find -name gave me no results).

**Comment by cpuguy83** [comment] 2015-07-22 02:13
@pl33g0r Your error is completely different.

**Comment by pl33g0r** [comment] 2015-07-22 02:28
@cpuguy83 could you elaborate a bit more?

**Comment by cpuguy83** [comment] 2015-07-22 02:31
@pl33g0r your error :`exec: "": executable file not found in $PATH`, is a completely different error from the OP: `invalid argument`
These are not related.

**Comment by hqhq** [comment] 2015-07-22 02:33
@pl33g0r Sorry I was talking about @CGavrila 's error, not sure about your problem. Maybe you can open a separate issue.

**Comment by cpuguy83** [comment] 2015-07-22 02:35
@pl33g0r I would also guess that either your image has a bad configuration or you were hit by #14578 (also just guessing).

**Comment by mountkin** [comment] 2015-07-22 06:31
@pl33g0r The `CMD` of your Dockerfile in https://registry.hub.docker.com/u/pl33g0r/ubu-slave/dockerfile/ is an empty string. It should be an executable file (or command arguments if the `ENTRPOINT` is specified).

**Comment by CGavrila** [comment] 2015-07-22 10:10
@hqhq: where is `check-config.sh` supposed to located? I can't seem to find it.

**Comment by hqhq** [comment] 2015-07-22 10:17
It's in the source code, you can copy from:
https://github.com/docker/docker/blob/master/contrib/check-config.sh

**Comment by CGavrila** [comment] 2015-07-22 10:19
@hqhq: Thanks for the help!

Here is check-config's output:
```
$ ./check-config.sh 
warning: /proc/config.gz does not exist, searching other paths for kernel config...
info: reading kernel config from /boot/config-3.13.0-57-generic ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: missing
    (note that cgroup swap accounting is not enabled in your kernel config, you can enable it by setting boot option "swapaccount=1")
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled (as module)
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
    - CONFIG_EXT4_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
    - CONFIG_EXT4_FS_SECURITY: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing
```

**Comment by hqhq** [comment] 2015-07-22 10:50
kernel config seems good, since you are using 12.04 and with kernel 3.13, I assume you updated your kernel, probably you enabled some config as modules and somehow it wasn't loaded to kernel, like CONFIG_VETH and other configs show as (as module), you can check that.

**Comment by CGavrila** [comment] 2015-07-23 13:38
@hqhq: Thanks for the help! Could you be a bit more specific as to what I could do to check that? I don't really know what I should be looking for.

**Comment by hqhq** [comment] 2015-07-24 08:06
Similar issues here: #14904

**Comment by Maple123** [comment] 2015-09-07 19:43
@hqhq : i also trying to run a simple "hello world" program. I am facing the same issue Like can't start conatainer. i just tried to run the shell script as mentioned by you(./check-config.sh) but its showing like:

./check-config.sh: line 4: syntax error near unexpected token `newline'
./check-config.sh: line 4: `<!DOCTYPE html>'

& what could be the best solution to resolve this issue? Please suggest to find a solution to run a sample program under docker. Thanks in advance.

**Comment by hqhq** [comment] 2015-09-08 01:32
@Maple123 It's wired, there is no such thing in check-config.sh: line 4, did you get the right file?

And if you are not using a customized kernel, kernel config usually wouldn't be the problem, better see #14904 , maybe you'll get answer there.

**Comment by Maple123** [comment] 2015-09-08 05:41
@maple123: i got the shell script from "https://github.com/docker/docker/blob/master/contrib/check-config.sh" then i tried to run it.

**Comment by mountkin** [comment] 2015-09-08 06:00
@Maple123 if you got the script via `wget https://github.com/docker/docker/blob/master/contrib/check-config.sh`  then it should be an HTML page.
You should run `wget https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh` to get the script.

**Comment by Maple123** [comment] 2015-09-08 06:28
@maple123: yeah now i can see the details, but everything seems to be fine.

warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-3.16.0-30-generic ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: missing
    (note that cgroup swap accounting is not enabled in your kernel config, you can enable it by setting boot option "swapaccount=1")
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled (as module)
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

I don't know then how to move forward to run my simple "hello-world" program under docker. could you please give some hint.

**Comment by mountkin** [comment] 2015-09-08 06:42
@Maple123 please try  `docker run --net=none hello-world` 
If it doesn't work ether, please provide the log file of the docker daemon in `/var/log/upstart/docker.log` and the output of `docker info`

**Comment by Maple123** [comment] 2015-09-08 07:23
Thanks all, i got it. It was a path issue while adding the executable file.

**Comment by djaed** [comment] 2015-10-25 06:11
@Maple123 please elaborate. I'm new to docker and been running into various difficulties, including  'docker run hello world' with same errors as above. My upstart/docker.log:

````
^[[34mINFO^[[0m[1916] POST /v1.20/containers/create
^[[34mINFO^[[0m[1916] POST /v1.20/containers/33fad1b252b0e41ffd7937daec78adbce9687595a4ba75e9d89917597035104f/attach?stderr=1&stdout=1&stream=1
^[[34mINFO^[[0m[1916] POST /v1.20/containers/33fad1b252b0e41ffd7937daec78adbce9687595a4ba75e9d89917597035104f/start
^[[34mINFO^[[0m[1916] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]
^[[33mWARN^[[0m[1916] exit status 1
^[[31mERRO^[[0m[1916] Handler for POST /containers/{name:.*}/start returned error: Cannot start container 33fad1b252b0e41ffd7937daec78adbce9687595a4ba75e9d89917597035104f: [8] System error: no such file or directory
^[[31mERRO^[[0m[1916] HTTP Error                                    ^[[31merr^[[0m=Cannot start container 33fad1b252b0e41ffd7937daec78adbce9687595a4ba75e9d89917597035104f: [8] System error: no such file or directory ^[[31mstatusCode^[[0m=404
````

**Comment by djaed** [comment] 2015-10-25 15:54
**Problem solved!**

Appears to be mostly related to **AppArmor installation on Ubuntu**. First followed [instructions to disable AppArmor profile](https://help.ubuntu.com/community/AppArmor#Disable_one_profile), which didn't work. Then after various other failed attempts, finally completely uninstalled AppArmor and deleted all AppArmor folders and also did same for docker-engine, i.e

    sudo apt-get purge docker-engine
    sudo apt-get autoremove --purge docker-engine
    rm -rf /var/lib/docker

then finally after all that, i could `sudo apt-get install docker-engine` and `sudo docker run hello-world` ....

**Comment by ankurVirtual** [comment] 2016-02-10 12:18
Folks i am having the same error and below the config check status

This is what i get when i try running the container

[root@localhost /]# docker images
REPOSITORY TAG IMAGE ID CREATED VIRTUAL SIZE
debian latest 5eb1402f0414 2 weeks ago 125.1 MB
ubuntu latest 8693db7e8a00 3 weeks ago 187.9 MB
hello-world latest 975b84d108f1 3 months ago 960 B

So when i try to run it gives below error

[root@localhost /]# docker run -t -i debian /bin/bash
Error response from daemon: Cannot start container ea7428e5832b4be98b2819b2ff7fec3d2d4eb0a5702e10d5af2824b0ee3d36e6: no such file or directory


version information is below:

[root@localhost /]# docker info
Containers: 4
Images: 8
Storage Driver: devicemapper
Pool Name: docker-253:0-1575720-pool
Pool Blocksize: 65.54 kB
Backing Filesystem: extfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 697.7 MB
Data Space Total: 107.4 GB
Data Space Available: 34.53 GB
Metadata Space Used: 1.241 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.146 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.95-RHEL6 (2015-09-08)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 2.6.32-279.9.1.el6.centos.plus.x86_64
Operating System: 
CPUs: 2
Total Memory: 489.6 MiB

docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64


i ran a config check and it gives below results.can any one figure out what is wrong

[root@localhost /]# ./check-config.sh
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-2.6.32-279.9.1.el6.centos.plus.x86_64 ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: missing
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: missing
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: missing
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: missing
- CONFIG_MEMCG_KMEM: missing
- CONFIG_MEMCG_SWAP: missing
- CONFIG_MEMCG_SWAP_ENABLED: missing
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: enabled
- CONFIG_NETPRIO_CGROUP: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_EXT3_FS: enabled (as module)
- CONFIG_EXT3_FS_XATTR: enabled
- CONFIG_EXT3_FS_POSIX_ACL: enabled
- CONFIG_EXT3_FS_SECURITY: enabled
- CONFIG_EXT4_FS: enabled (as module)
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Storage Drivers:
- "aufs":
- CONFIG_AUFS_FS: missing
- "btrfs":
- CONFIG_BTRFS_FS: enabled (as module)
- "devicemapper":
- CONFIG_BLK_DEV_DM: enabled (as module)
- CONFIG_DM_THIN_PROVISIONING: enabled (as module)
- "overlay":
- CONFIG_OVERLAY_FS: missing
- "zfs":
- /dev/zfs: missing
- zfs command: missing
- zpool command: missing

Any help on this will be appreciated. Thanks in advance

**Comment by thaJeztah** [comment] 2016-02-16 13:32
@ankurVirtual RHEL/CENTOS 6 is no longer supported (last version of docker for those platforms are 1.7.1, but we won't be releasing patch updates for 1.7.1). Best advice I can give is to make sure your system and kernel is fully up-to-date. If possible, upgrade to CentOS 7.x, which has a more recent kernel, and is still supported.

**Comment by ankurVirtual** [comment] 2016-02-16 13:36
@thaJeztah thanks for confirming it.Any guide for troubleshooting on other flavours

**Comment by thaJeztah** [comment] 2016-02-16 13:41
@ankurVirtual there are some similar issues linked that may give some information; https://github.com/docker/docker/issues/14904, https://github.com/docker/docker/issues/14160 - in some cases those were related to having Symantec AntiVirus installed on the host

**Comment by ankurVirtual** [comment] 2016-02-16 13:45
@thaJeztah thanks sir for prompt response.

**Comment by icecrime** [comment] 2016-09-10 02:44
Tentatively closing as the issue seems to be resolved: please let me know if it needs reopening! Thanks.

**Closed by icecrime** 2016-09-10 02:44 UTC
Labels: kind/bug, version/1.7
