### ISSUE TITLE
Weird volume mounting behavior on OS X with latest docker(-machine)

### ISSUE THREAD

**Issue by 4lex1v** [docker/docker#20100] opened 2016-02-08 12:45 UTC
The Basics:

**docker version**
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   a34a1d5
 Built:        Sun Jan 17 16:14:45 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        2016-02-04T19:55:25.696148927+00:00
 OS/Arch:      linux/amd64
```

**docker info**
```
Containers: 33
Images: 112
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 202
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
CPUs: 4
Total Memory: 7.79 GiB
Name: universe
ID: XT2V:OBG4:RP2J:33XO:EKJR:BDTY:P6QF:MXI3:HAE7:VGC4:IUDN:IFSK
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 25
 System Time: 2016-02-08T12:34:08.870847725Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: 4lex1v
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**uname -a**
```
Darwin MacBook-Pro-Aleksandr.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
```

So i have the simplest `Dockerfile`:

```
FROM python:3.4
RUN pip install Flask==0.10.1
```

and the following folder structure:

**find .**
```
.
./app
./app/identidock.py
./app/text.txt
./Dockerfile
```

Running a container with `docker run -v /Users/4lex1v/Sandbox/Projects/identidock/app:/app -ti -w /app identidock bash` gives a strange result:

```
root@77edb067e41c:/app# ls -la
total 4
drwxr-xr-x  3 root root   60 Feb  8 12:21 .
drwxr-xr-x 56 root root 4096 Feb  8 12:38 ..
drwxr-xr-x  2 root root   40 Feb  8 12:21 identidock.py
```
There's no `text.txt` file and python script is a folder. Then if i rename the folder on the host, e.g:

**find .**
```
.
./Dockerfile
./play
./play/identidock.py
./play/text.txt
```

And run it as `docker run -v /Users/4lex1v/Sandbox/Projects/identidock/play:/test -ti identidock bash`, i can't see anything at all:

```
root@79d2d98e1d9d:/# find /test/
/test/
```

I read the documentation for mounting files and folders, but it seems that i'm doing it as it should be done, is there any OS X specific issue, docker or i'm simply doing something wrong?

**Comment by thaJeztah** [comment] 2016-02-08 15:58
I wonder if VirtualBox filesharing is not properly working; in that case, docker would be creating an empty directory inside the VM, which could explain what's happening.


How did you upgrade to 1.10? Wondering, because the client is still at 1.9 in your setup

**Comment by 4lex1v** [comment] 2016-02-08 17:46
@thaJeztah Regarding the version, sorry, i was messing with `brew switch`, changing versions, because before the update, i didn't have this issue. I've switched it back, but the issue remains:

```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d510
 Built:        Fri Feb  5 08:21:41 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

As for VirtualBox, maybe that explains empty directory, but what about the fact, that the python script becomes a directory within the container?

**Comment by cornelf** [comment] 2016-02-08 18:30
@4lex1v  Did you upgrade through this: https://github.com/docker/toolbox/releases/download/v1.10.0/DockerToolbox-1.10.0.pkg
Your client looks a bit ahead of the server which tells me that they are not installed through the same method. 
This is what I have and works fine:

```
docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

**Comment by 4lex1v** [comment] 2016-02-08 19:17
@cornelf Not sure how that happened, i've used [Homebrew](http://brew.sh/) to install and update everything

**Comment by 4lex1v** [comment] 2016-02-08 19:48
So i recreated docker machine and it seems that now everything works. I don't know what was the problem, probably issue happened during `docker-machine upgrade`. My current stats are the following:

docker version
```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d510
 Built:        Fri Feb  5 08:21:41 UTC 2016
 OS/Arch:      darwin/amd64
Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

docker info
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.79 GiB
Name: universe
ID: KW3F:AM4V:JTXQ:QSRN:237F:MP2H:7UBX:JI7K:CDH6:DZNH:JADA:23OW
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 25
 System Time: 2016-02-08T19:46:42.7503595Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: 4lex1v
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Comment by thaJeztah** [comment] 2016-02-08 23:36
> but what about the fact, that the python script becomes a directory within the container?

Actually, that's explainable if the VirtualBox file sharing wasn't working; if docker doesn't find the file specified, it assumes you want to mount a directory, and (currently), creates that directory, if it doesn't exist.

Note that the auto-creation of directories has been marked deprecated, and will be removed in the next docker release; https://github.com/docker/docker/pull/19953

Happy to hear it's resolved, I'm not sure what caused the VirtualBox sharing to not function, but feel free to ping if you encounter this again.

I'm going to close this issue for now, because we don't have a reproducible case

**Closed by thaJeztah** 2016-02-08 23:36 UTC
