### ISSUE TITLE
embedded dns abruptly terminates TCP connection when resolving MX or CAA records

### ISSUE THREAD

**Issue by ibukanov** [docker/docker#28136] opened 2016-11-07 22:48 UTC
**Description**

If a container on a custom network uses DNS over tcp, then resolving MX and CAA records fails with typical error messages indicating end-of-file problem.

**Steps to reproduce the issue:**

1. Create a custom network: `docker network create bugtest`
2. Run a container on it with software that uses DNS over TCP:
```
$  docker run -ti --rm --net=bugtest ubuntu 
root@d6ba214d3c37:/# apt update && apt -y install dnsutils
root@d6ba214d3c37:/# dig +tcp google.com mx     
;; communications error to 127.0.0.11#53: end of file
```

**Describe the results you received:**

The error is caused by DNS server abruptly closing the connection instead of returning the proper answer.

**Describe the results you expected:**

The expected output should be the same as for UDP:
```
root@d6ba214d3c37:/# dig +notcp google.com mx

; <<>> DiG 9.10.3-P4-Ubuntu <<>> +notcp google.com mx
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8932
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 4, ADDITIONAL: 10

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.                    IN      MX

;; ANSWER SECTION:
google.com.             600     IN      MX      20 alt1.aspmx.l.google.com.
google.com.             600     IN      MX      50 alt4.aspmx.l.google.com.
google.com.             600     IN      MX      40 alt3.aspmx.l.google.com.
google.com.             600     IN      MX      30 alt2.aspmx.l.google.com.
google.com.             600     IN      MX      10 aspmx.l.google.com.

;; AUTHORITY SECTION:
google.com.             156804  IN      NS      ns1.google.com.
google.com.             156804  IN      NS      ns2.google.com.
google.com.             156804  IN      NS      ns3.google.com.
google.com.             156804  IN      NS      ns4.google.com.

;; ADDITIONAL SECTION:
aspmx.l.google.com.     279     IN      A       64.233.162.26
alt1.aspmx.l.google.com. 281    IN      A       74.125.203.26
alt2.aspmx.l.google.com. 275    IN      A       74.125.28.26
ALT3.aspmx.l.google.com. 277    IN      A       74.125.30.26
ALT4.aspmx.l.google.com. 293    IN      A       74.125.201.26
ns1.google.com.         335957  IN      A       216.239.32.10
ns2.google.com.         342296  IN      A       216.239.34.10
ns3.google.com.         342296  IN      A       216.239.36.10
ns4.google.com.         342296  IN      A       216.239.38.10

;; Query time: 94 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Mon Nov 07 22:43:44 UTC 2016
;; MSG SIZE  rcvd: 373
```
**Output of `docker version`:**
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 41
 Running: 32
 Paused: 0
 Stopped: 9
Images: 357
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.7.3-coreos-r2
Operating System: CoreOS 1185.3.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.046 GiB
Name: thip
ID: AQKH:JESB:XWHG:VEIF:BZIX:IQNL:Q7UH:PBS3:KRCT:4W72:OCNM:TAOU
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

This is under CoreOS running inside VirtualBox on MacBook.

**Comment by AkihiroSuda** [comment] 2016-11-08 04:28
Could not reproduce in master
```console
$ docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   69efb46
 Built:        Tue Nov  8 04:09:05 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   69efb46
 Built:        Tue Nov  8 04:09:05 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

cc @aboch @mavenugo @mrjana

**Comment by mavenugo** [comment] 2016-11-08 04:52
@ibukanov This seems like a forked version of Docker and not an official build of docker/docker project. Please reproduce the issue in an official build of docker/docker (preferably a released version 1.12.3 being the latest stable release) and get back to us.

**Comment by aboch** [comment] 2016-11-08 04:54
I cannot reproduce with 1.11.2:

```
$ docker version | grep Version
 Version:      1.11.2
 Version:      1.11.2
$
$docker run -ti --rm --net=bugtest ubuntu 
root@4e12c1dd7157:/# apt update && apt -y install dnsutils
<snip>

root@4e12c1dd7157:/# dig +tcp google.com mx

; <<>> DiG 9.10.3-P4-Ubuntu <<>> +tcp google.com mx
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7117
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	MX

;; ANSWER SECTION:
google.com.		535	IN	MX	30 alt2.aspmx.l.google.com.
google.com.		535	IN	MX	40 alt3.aspmx.l.google.com.
google.com.		535	IN	MX	10 aspmx.l.google.com.
google.com.		535	IN	MX	20 alt1.aspmx.l.google.com.
google.com.		535	IN	MX	50 alt4.aspmx.l.google.com.

;; Query time: 73 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Tue Nov 08 04:52:17 UTC 2016
;; MSG SIZE  rcvd: 147

root@4e12c1dd7157:/#

**Comment by thaJeztah** [comment] 2016-11-26 22:26
I'm closing this issue because we are not able to reproduce this on the official builds, but feel free to comment with more information if you think there's a bug at hand

**Closed by thaJeztah** 2016-11-26 22:26 UTC
Labels: area/networking, version/1.11

**Comment by jizhilong** [comment] 2020-03-24 09:05
Hi guys and googlers, I think we reproduced this issue on our  docker installation, and it is highly possible related to dnsmasq's  validating on incoming request's interface:

```
[root@ba432a724da0 app]# time dig +tcp google.com mx 
;; communications error to 127.0.0.11#53: end of file

real    0m8.068s
user    0m0.008s
sys     0m0.004s
```

and  I think the root cause is not  much to docker itself, but to the dnsmasq on our host server.
We configured the hosts `/etc/resolv.conf` like this:

```
nameserver 127.0.0.1
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by salt-ssh (1)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
```
in which `127.0.0.1` is where dnsmasq listening on.

So a dns query from within a container will be routed to `127.0.0.1::53`,  which is docker's embedding dns server, the embedding dns server will lookup the host's `/etc/resolv.conf`, and determine this request to dnsmasq. While dnsmasq will accept docker embedding dns server's  connection, it wont pass the incoming interface checking(the incoming interface would have a `calixxxx` like name), so  dnsmasq will shutdown the connection egarly.

To workaround this issue, you can turn on dnsmasq's  `--bind-interfaces` option,  which is available only on Linux though.
