### ISSUE TITLE
Docker Remote API 1.25 - Service Logs follow option seems to be allways set as true

### ISSUE THREAD

**Issue by brunovale91** [docker/docker#30463] opened 2017-01-26 10:06 UTC
**Description**

 Curl command "curl -i --unix-socket /var/run/docker.sock -H "Content-Type: application/json"   -X GET http:/v1.25/services/{id}/logs?stdout=true",  "curl -i --unix-socket /var/run/docker.sock -H "Content-Type: application/json"   -X GET http:/v1.25/services/{id}/logs?stdout=true&follow=true"  and "curl -i --unix-socket /var/run/docker.sock -H "Content-Type: application/json"   -X GET http:/v1.25/services/{id}/logs?stdout=true&follow=false" execute in the same way (keeping the TCP connection opened).

**Steps to reproduce the issue:**

1. Execute "curl -i --unix-socket /var/run/docker.sock -H "Content-Type: application/json"   -X GET http:/v1.25/services/{id}/logs?stdout=true"
2. Execute "curl -i --unix-socket /var/run/docker.sock -H "Content-Type: application/json"   -X GET http:/v1.25/services/{id}/logs?stdout=true&follow=true"
3. Verify that the execution is the same.

**Describe the results you received:**
TCP connection says opened for service logs call using remote api 1.25.

**Describe the results you expected:**
TCP connection closed after request when follow=false or not supplied using remote api 1.25.

**Additional information you deem important (e.g. issue happens only occasionally):**
It works from the command line. "docker service logs <service>"

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 14
 Running: 5
 Paused: 0
 Stopped: 9
Images: 16
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-8:3-1392-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 81.41 GB
 Data Space Total: 107.4 GB
 Data Space Available: 25.97 GB
 Metadata Space Used: 58.39 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.089 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: d8qt42gr29mnadexje7vops7y
 Is Manager: true
 ClusterID: etvbduoyjp3cdod92i0vqc7qq
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.2.4.205
 Manager Addresses:
  10.2.4.205:5002
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.28.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.52 GiB
Name: docker01.td.mxdata.co.uk
ID: CULF:XUOG:MDZH:FMQY:WX7I:T7MF:4UOH:BK7R:GHFA:BEWZ:TSJO:V7KP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-01-26 13:46
ping @aluzzardi - looks related to https://github.com/docker/docker/pull/28691

**Comment by brunovale91** [comment] 2017-01-30 16:16
After doing more tests I now believe that the query parameters are not being passed correctly. I've tried to track the implementation of service logs "ServiceLogs(context.Context, string, *backend.ContainerLogsConfig, chan struct{}) error" and I could find the function ServiceLogs on "daemon/cluster/cluster.go" that doesn't use any parameters of backend.ContainerLogsConfig apart from "follow".

**Comment by aluzzardi** [comment] 2017-01-30 23:18
/cc @dperny 

I believe #28691 should have fixed this

**Comment by dperny** [comment] 2017-01-30 23:37
I'm working on this bug right now, actually, tho I didn't realize this issue was open (it's a pretty apparent problem)

**Comment by dperny** [comment] 2017-01-30 23:39
I'm still investigating the problem (I just started working on logs late last week) and it looks like you're a little further ahead than I am, so if you're working on a fix, @brunovale91, let me know and I'll let you finish it out.

**Comment by brunovale91** [comment] 2017-01-30 23:52
I'm not working on the issue @dperny, I don't know enough about go and docker yet. I was just trying to help to find the issue.

**Comment by dperny** [comment] 2017-01-31 00:40
Thanks for your help so far then!

**Comment by thaJeztah** [comment] 2017-02-20 11:39
ping @dperny any news on this one?

**Comment by dperny** [comment] 2017-02-21 17:45
I feel like it might be related to the thing I'm working on right now, but no updates.

**Comment by dperny** [comment] 2017-02-22 18:12
I'm having trouble reproducing this, partly because I'm struggling a bit with wrangling `curl` to reproduce this exact behavior. However, @aluzzardi's change was on version 1.26, I think, of the API? And now we're on 1.27. So I think he was right the whole time and this is not a bug.

@brunovale91 would you mind trying to reproduce on API version 1.27 to verify that for me?

/cc @thaJeztah

**Comment by brunovale91** [comment] 2017-02-28 16:37
Hi @dperny, I've test with version 1.13.1 and API 1.26 and this doesn't happen anymore.

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by dperny** [comment] 2017-02-28 20:25
thanks so much for checking that for me @brunovale91 

@thaJeztah we can close this now.

![](http://1.bp.blogspot.com/-mlzxRZudNEs/U2DeUZgtzoI/AAAAAAAAZNs/nTNS8QoHac4/s1600/done.jpg)

**Comment by thaJeztah** [comment] 2017-02-28 22:34
Cool, glad to!

**Closed by thaJeztah** 2017-02-28 22:34 UTC
Labels: area/swarm, kind/experimental, version/1.13

**Comment by tianon** [comment] 2017-03-28 16:40
This should be fixed on 17.03.1-ce-rc1, shouldn't it?  (still seeing it on 17.03.1-ce-rc1)

**Comment by thaJeztah** [comment] 2017-03-28 16:51
ping @dperny ^^

**Comment by dperny** [comment] 2017-03-28 16:57
@tianon are the logs actually FOLLOWING or are they just hanging? There is an outstanding hang #31625 that LOOKS like `follow` is stuck but no following occurs.

**Comment by tianon** [comment] 2017-03-28 17:20
Hmm, good question -- the daemon was definitely not restarted since the service had been created (it was a brand new service), but no matter what value `--follow` has, it hangs for sure.  I'll do a little more testing and either comment again here or there with the results.  Thanks! :+1: :heart:

**Comment by dperny** [comment] 2017-03-28 17:21
The way you tell the difference between `follow` and a hang is whether you get new log lines or not.

**Comment by tianon** [comment] 2017-03-28 17:22
Yeah, going to use `bash -c 'i=0; while true; do echo "$(( ++i ))"; sleep 1; done'` to help me verify that. :innocent: (the service that was running wasn't creating any new output)

**Comment by dperny** [comment] 2017-03-28 17:23
I've been using `flyinprogrammer/logtester` for testing logs (thanks @flyinprogrammer you are hero even if you never realized it).

**Comment by tianon** [comment] 2017-03-28 17:24
With a brand new service I simply cannot reproduce, so it must just be https://github.com/docker/docker/issues/31625 on that other service and I'm going crazy.  Sorry for the noise and thanks for the pointer! (hopefully this will help future travellers find https://github.com/docker/docker/issues/31625 instead :+1: :heart: :heart: :heart:)

**Comment by brunovale91** [comment] 2017-03-28 18:08
@dperny I forgot to mention here but I think that the problem is that in the service logs we don't filter by running tasks and when we restart the service we get the first "non running tasks" making the logs hang. I've actually tested filtering by running tasks and it solves #31625.
