### ISSUE TITLE
Suspected race conditions in daemon/attach.go

### ISSUE THREAD

**Issue by jim-minter** [docker/docker#29285] opened 2016-12-09 18:36 UTC
**Description**

I ran into a sporadic API consumer hang when reading stdout/stderr from a very short-executing container.  The API consumer calls ContainerCreate, ContainerAttach, ContainerStart, ContainerWait in order.  When the problem occurs, the server does not write the container stdout/stderr to the ContainerAttach connection, and after the ContainerWait call completes, the server does not close the ContainerAttach connection, causing the API consumer to hang. 

By inspection I found the following suspected race conditions in https://github.com/docker/docker/blob/master/daemon/attach.go:

1. ContainerAttach returns "200 OK" to the caller at https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L37 before the stdout/stderr streams are actually attached to the container at https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L61.

   During this window, it is actually possible for a container to be started and to run to completion.  If this happens, the API consumer doesn't receive the container stdout/stderr, and the consumer also misses its connection being closed as part of the container teardown in https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/container/stream/streams.go#L90.

   The easiest way I've found to reproduce this requires modifying the server: insert `time.Sleep(10 * time.Second)` before https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L61 and then compile and run the test program below.

   _Note: as an additional protection measure IMO it would be worth making broadcaster.Unbuffered stateful and unreusable to protect against new Writers being `Add()`ed after `Clean()` has been called._

2. I suspect `containerAttach` (https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L76) to be racy: logs are harvested and returned at https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L77-L106, then I believe there is a window during which any new logs would be lost to the consumer before `Attach` succeeds at https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L131.  At the moment, I believe a caller who sets logs = true and stream = true is not guaranteed not to lose logging data.

3. I suspect the invocation of `container.IsPaused()` at https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L32 must be racy because I don't see any protection against the container state changing in parallel before the containerAttach completes.

I believe that if these issues are valid, they indicate that overall the attach and logging logic needs some rework to be more closely integrated into pre-existing container state / synchronisation primitives, and consideration also needs to be given about if/how to atomically read past logs and start streaming without missing data.

**Steps to reproduce the issue:**
1. Insert `time.Sleep(10 * time.Second)` before https://github.com/docker/docker/blob/9d884986f5c001cacb60aa3c50036575ed2dd22d/daemon/attach.go#L61; compile and run Docker server
2. `docker pull busybox`
3. Compile and run the following golang program:
```golang
package main

import (
	"context"
	"os"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/network"
	"github.com/docker/docker/client"
	"github.com/docker/docker/pkg/stdcopy"
)

func main() {
	ctx := context.Background()

	cli, err := client.NewEnvClient()
	if err != nil {
		panic(err)
	}

	c, err := cli.ContainerCreate(ctx, &container.Config{Image: "busybox", Entrypoint: []string{"sh", "-c", "echo hello world"}}, &container.HostConfig{}, &network.NetworkingConfig{}, "")
	if err != nil {
		panic(err)
	}

	hi, err := cli.ContainerAttach(ctx, c.ID, types.ContainerAttachOptions{Stream: true, Stdout: true})
	if err != nil {
		panic(err)
	}

	ch := make(chan error, 1)
	go func() {
		_, copyerr := stdcopy.StdCopy(os.Stdout, os.Stdout, hi.Reader)
		ch <- copyerr
	}()

	err = cli.ContainerStart(ctx, c.ID, types.ContainerStartOptions{})
	if err != nil {
		panic(err)
	}

	code, err := cli.ContainerWait(ctx, c.ID)
	if err != nil {
		panic(err)
	}

	err = <-ch
	if err != nil {
		panic(err)
	}

	os.Exit(int(code))
}
```

**Describe the results you received:**
no output; hang

**Describe the results you expected:**
output "hello world", exit 0.

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   9d88498
 Built:        Fri Dec  9 20:01:40 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   9d88498
 Built:        Fri Dec  9 20:01:40 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.14.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.2.3-300.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.797 GiB
Name: openshiftdev
ID: YHFD:22Z2:JM6H:AUT2:XA72:6POC:DFYQ:JTFZ:KE3Y:QPUM:ZY33:DOVO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by jim-minter** [comment] 2016-12-09 18:36
@runcom

**Comment by runcom** [comment] 2016-12-09 18:42
@jim-minter thanks for this - you're running projectatomic/docker version of Docker. Could you retest this with the official docker/docker source? We didn't change anything in the code paths you've highlighted but still, to remove any doubts of projectatomic/docker being the cause of this, please do re-run the test with the official Docker source.

**Comment by jim-minter** [comment] 2016-12-09 20:04
@runcom good point, thanks - retested and confirmed with official docker/docker master.  `docker info` and `docker version` clauses in description updated to reflect this.

**Comment by runcom** [comment] 2016-12-09 20:18
@tonistiigi @cpuguy83 @LK4D4 ptal

**Comment by cpuguy83** [comment] 2016-12-09 20:41
Switching from logs to stdio stream is always going to be racey, I would just recommend not using the attach endpoint for getting historical data (and this would only work for certain log drivers anyway).

One issue with your client code above is there is no guarantee that your `stdcopy` goroutine has even started by the time you hit `ContainerStart`.
One way to minimize this is to do:
```go
	ch := make(chan error, 1)
        started := make(chan, struct{})
	go func() {
                close(started)
		_, copyerr := stdcopy.StdCopy(os.Stdout, os.Stdout, hi.Reader)
		ch <- copyerr
	}()
        <-started
```

**Comment by tonistiigi** [comment] 2016-12-10 01:23
At least first 2 seem to be valid. The first one is quite unlikely so I wouldn't set it to very high priority. @cpuguy83 For the second, shouldn't we just deprecate `logs` from `/attach`. The cli doesn't expose it and like you said, everyone should just use `/logs`.

The third one I don't quite get. `IsPaused()` is a best effort. If a container is paused during that function it behaves the same as if container had been called after attach already happened.

**Comment by cpuguy83** [comment] 2016-12-14 14:04
While I generally don't like the feature, I'd prefer not to break people unless there's a really good reason. If people are using attach with logs while the container is stopped, there is no race.

**Comment by jim-minter** [comment] 2017-01-20 09:28
> One issue with your client code above is there is no guarantee that your stdcopy goroutine has even started by the time you hit ContainerStart.

@cpuguy83 this comment is spurious - a) it doesn't matter because the pipe is created and ready, and will be read in due course; and b) your code doesn't ensure that stdcopy is running either.

**Comment by jim-minter** [comment] 2017-01-20 09:32
@tonistiigi I'm finding case 1 isn't that uncommon if the container is very short-lived, and the consequences are grave (hang of the API consumer).

**Comment by cpuguy83** [comment] 2017-01-20 16:25
@jim-minter It does matter (again not saying there is not a chance of a race with 1), because the streams can be closed before your copier goroutine has even started.

Yes technically there is no guarantee that the copy has started when the channel close is read, but it's a much higher guarantee since you know at least the goroutine is scheduled. The goroutine is not running when `go blah()` returned and can happen much later.

That is not to say that all races a fixed by such a change, but you are at much lower risk of running into a problem with such a change.

**Comment by jim-minter** [comment] 2017-01-20 17:39
> the streams can be closed before your copier goroutine has even started

@cpuguy83 please could you explain how?

**Comment by cpuguy83** [comment] 2017-01-20 17:41
@jim-minter If the container has started and stopped before the copy routine has even been scheduled to actually run.

**Comment by jim-minter** [comment] 2017-01-20 19:51
@cpuguy83 in this case (excluding the problem raised in this issue!), the container starts, its output gets written to the tcp (http) connection, the container exits and the container host closes the connection.  Viewed from the api client's point of view, the connection is open since the ContainerAttach call.  The output arrives at the client concurrently but sits waiting in an OS buffer.  The notification that the container host closed the connection ditto.  At some indefinite time later, the copy goroutine runs, reads the data from the OS buffer, and deals with the remote close (io.EOF) afterwards by exiting stdcopy.StdCopy.  It is not necessary for the copy goroutine to be running at the same time as the container is running.

**Comment by jim-minter** [comment] 2017-01-23 15:30
@tonistiigi @cpuguy83 looking at this a bit more.  The key part of the necessary fix involves not sending the HTTP 200 OK until after the streamConfig.{Stdin,Stdout,Stderr}Pipe() calls in AttachStreams() have succeeded.

So: the logs option to ContainerAttach presents a problem: if prior logs are to be streamed, at the moment this is done before AttachStreams() is called.  The 200 OK would have to be sent to the client before the logs are streamed.  This is incompatible with fixing the race condition as defined above.

I can see three options:
1) do the streamConfig.{Stdin,Stdout,Stderr}Pipe() before streaming logs.  Now no log items will be lost from the response, but instead it's possible that items will be duplicated instead (any new logs output by the container while the log streaming takes place).

2) if logs are requested, maintain existing (broken imo) behaviour: there is a race between logs finishing and attach starting, and 200 OK is returned before the attach completes.  Too bad for the client.  But: if logs is not requested, then we can delay sending the 200 OK until the streamConfig.{Stdin,Stdout,Stderr}Pipe() calls have succeeded, and at least in this case this race is fixed.

3) remove the logs streaming functionality from attach and provide an API without races.

My questions to you:

- do you see any other alternatives?

- which of the three options above is acceptable to you?  Aesthetically I think 3 is best, but perhaps you'll choose 2) even though it's somewhat broken, to support existing clients?  Does your API versioning help with removal of functionality like this at all?

**Comment by cpuguy83** [comment] 2017-01-23 15:34
@jim-minter I was looking at it, and likely indeed we need to have some way to signal to callers of `AttachStreams` that the streams are all ready, which would then trigger the 200 response.
Especially since there are other places for error in there where something other than a `200 OK` would be prefered.

I think, though, that unless you are using stdin you probably just need to use the logs endpoint rather than attach.

**Closed** 2017-02-01 15:20 UTC
Labels: area/distribution, version/1.12, version/master
