### ISSUE TITLE
Device or Resource busy when restart docker daemon v1.11

### ISSUE THREAD

**Issue by sqleejan** [docker/docker#22286] opened 2016-04-25 05:39 UTC
Docker Version

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
```

**Steps to reproduce the issue:**
1. docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc
2. docker daemon --containerd /var/run/docker/libcontainerd/docker-containerd.sock -D
3. start a container
4. kill -9 ${docker_daemon_PID}
5. docker daemon --containerd /var/run/docker/libcontainerd/docker-containerd.sock -D

ERRO[0002] Error during layer Store.Cleanup(): device or resource busy 
FATA[0002] Error starting daemon: timeout

**Comment by HackToday** [comment] 2016-04-25 06:17
Tried above can did not reproduce that.
Tried on ubuntu 14.04, on docker  `1.11.0`

**Comment by sqleejan** [comment] 2016-04-25 08:16
I also did not reproduce that After I restart my computer Now ; Mybe  due to other cause

**Comment by thaJeztah** [comment] 2016-04-25 08:49
@sqleejan also note that you don't need to manually start containerd; simply running `docker daemon` should also start containerd.


I'll close this issue, because it looks to be resolved, but feel free to continue the discussion

**Closed by thaJeztah** 2016-04-25 08:49 UTC
