### ISSUE TITLE
why are there 2 commands for the same thing? `docker info`/ `docker system info`

### ISSUE THREAD

**Issue by codevulture** [docker/docker#30700] opened 2017-02-03 06:28 UTC
**Description**

**Steps to reproduce the issue:**
1.docker info
2.docker system info

**Describe the results you received:**
Same results

**Describe the results you expected:**
Why 2 commands for same thing

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
vagrant@devstack:~$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
vagrant@devstack:~$ docker info
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 7
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: b94bct7xm12dkipyewor2ddpf
 Is Manager: true
 ClusterID: tsz8xbhf8zle5un985sxx606e
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.121.26
 Manager Addresses:
  192.168.121.26:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 11.6 GiB
Name: devstack
ID: BDOM:OAON:WWEP:2L4Z:P7T5:VBRD:4G3N:W6BZ:334F:2EMU:PLAH:2KJH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vagrant

**Comment by thaJeztah** [comment] 2017-02-03 06:46
Since the original version of docker, docker has gained a lot of new "object" types; where docker 1.0 only had "images" and "containers", docker 1.13 has containers, images, volumes, networks, services, nodes, secrets, and more.

As a result, the original commands became very confusing, and inconsistent with other object types (`docker rm` to remove a container `docker rmi` to remove an image, but `docker network rm`, `docker volume rm`, `docker service rm` etc).

Docker 1.13 therefore adds a new aliases for those original commands to have a consistent user interface, for example, `docker image pull` as an alias for `docker pull`.

Both the original commands and the new commands are shown in docker 1.13, but in future, the less frequently used commands will be hidden.

To enable the hiding in 1.13, use the `DOCKER_HIDE_LEGACY_COMMANDS` environment variable; for example;

    DOCKER_HIDE_LEGACY_COMMANDS=1 docker help


I'll close this issue because this is a question, not a bug report, but I hope the above helps; also feel free to continue the conversation here

**Closed by thaJeztah** 2017-02-03 06:46 UTC
Labels: version/1.13

**Comment by codevulture** [comment] 2017-02-03 06:59
yes this was a question though I could assign a question tag to this issue, Thanks for clearing my doubt.
