### ISSUE TITLE
Sharing Docker build cache through an image registry?

### ISSUE THREAD

**Issue by itamaro** [docker/docker#22600] opened 2016-05-09 14:09 UTC
Hi,

I was wondering what information from the Dockerfile is stored in each layer of the resulting Docker image, and whether this information can be used to practically "share" the build cache between machines that share Dockerfiles and Docker images.

Here's a simple Dockerfile to illustrate what I mean:

    FROM ubuntu:15.10
    ARG DEBIAN_FRONTEND=noninteractive
    RUN apt-get update -y
    RUN apt-get install -y --no-install-recommends curl wget autoconf

Now, I build an image from this Dockerfile on host A using `docker build -t silly/image:foo`, which does a full build, naturally. If I run the build command again on host A, all layers will be cached, as expected.

Now, on host B, say I have an identical Dockerfile, and I do:

    host A> docker push silly/image:foo
    host B> docker pull ubuntu:15.10
    host B> docker pull silly/image:foo
    host B> docker build -t silly/image:bar .

(in both cases the current directory contains only the Dockerfile)

Trying this out with Docker 1.11.1 and a private registry (DTR), the docker build on host B ran a full build.

I hoped that pulling `silly/image:foo` on host B would tell Docker that the layers from ubuntu:15.10 to the target image are also available on the host, so there's no need to rebuild them locally, but it didn't.

Is this a reasonable expectation?

If it isn't - why not?

If it is - is there a bug, or I misused / misconfigured something? (or is it something that isn't implemented yet?)

Thanks :-)

**Comment by thaJeztah** [comment] 2016-05-09 14:14
The build cache is not pushed to the registry, only the layers that were produced by the build, a textual representation of the "history", and the manifest/metadata of the image is is pushed.

Having said that, I think this is a duplicate of https://github.com/docker/docker/issues/20316, which contains more background information about this.

I'll close this issue for that reason, but feel free to comment here after I closed

**Closed by thaJeztah** 2016-05-09 14:14 UTC
