### ISSUE TITLE
Using R and rpy2 in docker but the program is killed when importing rpy2.robjects

### ISSUE THREAD

**Issue by lichgo** [docker/docker#15281] opened 2015-08-04 03:45 UTC
Installed R and rpy2 in docker:

```
FROM    docker.io/centos
RUN     yum install -y lapack lapack-devel blas blas-devel gcc gcc-c++ python-devel automake autoconf libtool make readline-devel R

RUN     pip install rpy2 (pip is already installed)
```

Run a container and inside it:
```
# test_rpy2.py
from rpy2 import robjects

python test_rpy2.py
```

Then the test_rpy2.py is killed.

I guest docker has limits something. Or does it lack some essential packages?
Is there someone who has such experience?

**Comment by unclejack** [comment] 2015-08-04 08:44
That's pretty much expected. Simply importing something without any code usually means python will do what it's been told to do: import the module(s) and exit.

As long as there are no import side effects such as launching something immediately upon import, this makes sense.

The example Dockerfile you've provided doesn't have pip installed, so trying your example end to end isn't possible.

What you're describing in your `test_rpy2.py` examples seems to be pretty normal and expected behavior for Python.

This isn't a general support forum. This is an issue tracker for Docker bugs, features and pull requests. Please take this into account when opening an issue.

This isn't a Docker bug, this is a question which is more appropriate for
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.

1) and 2) should be better for longer conversations.

Since this isn't a bug, I'm going to close this now. Please feel free to comment.

**Closed by unclejack** 2015-08-04 08:44 UTC
