### ISSUE TITLE
OSX native docker - Change default bridge ip network. In conflict with local network

### ISSUE THREAD

**Issue by bancuadrian** [docker/docker#25064] opened 2016-07-26 12:45 UTC
Hi,

After our network has changed, we now have a network of 172.17.0.0/16 . This interferes with docker0 bridge, and now we get "no route to host" when we try to push/pull from our private repository which has an IP of 172.17.4.62.

1. Is there a way to change docker bridge on OSX native ??
2. how can you start/stop docker daemon on OSX native ( and with params if needed. for example to start docker daemon - DOCKER_OPTS="-H tcp://0.0.0.0:5000 -H unix:///var/run/docker.sock --bip=172.20.1.1/16" - where can I set this on OSX ? )

Is this a issue/bug with native docker for osx ?

When we used docker-machine 0.6.0 the docker bridge is set to 172.18.0.0 and everything was ok.

Please help! 

Regards,
Adrian

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: YIBL:DLTH:7IIO:NSMT:7FA3:OVLK:EGDT:5AZT:SIYD:UNGJ:3E7Q:3VNU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2016-07-26T12:38:29.320601725Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running native on OSX 10.11.6

**Comment by cpuguy83** [comment] 2016-07-26 14:26
There is no UI for this yet, but you can change it.

In `/Users/bgoff/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux` is a git database.
The daemon configuration is under `etc/docker/daemon.json`, which just uses the config from: https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file

You'd want to set `bip` to whatever subnet you like, but note that you need to use a real IP, not a `.0` one... for instance... `192.168.0.1/24`, not `192.168.0.0/24`

You need to change the config and then do a `git commit`, docker should restart automatically at that point (if not, restart it) with the new configuration.

Closing since this isn't really an engine issue and is known by the docker4mac team.
In the future the docker4mac forums would probably be a better place to interact about these types of problems: https://forums.docker.com/c/docker-for-mac

Thanks!

**Closed by cpuguy83** 2016-07-26 14:26 UTC
Labels: group/pinata, version/1.12

**Comment by thomandre** [comment] 2016-08-29 08:37
On the last beat (Version 1.12.1-beta24 -build: 11525), this is not working anymore: `~/Library/Containers/com.docker.docker/Data/database/` does not contain `com.docker.driver.amd64-linux` anymore.

Steps to reproduce: 
`cd ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux`
`-bash: cd: /Users/yourname/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux: No such file or directory`

Thanks for the help.

**Comment by justincormack** [comment] 2016-08-29 10:04
Go into that directory and do git reset --hard

**Comment by xiaods** [comment] 2016-10-14 06:23
not found DOCKER_HOST setting in this config file. anyone can do me a favor?

**Comment by whiteadam** [comment] 2016-11-23 17:32
Just FYI: this doesn't work for me anymore either on `Docker version 1.12.3, build 6b644ec`

**Comment by thaJeztah** [comment] 2016-11-25 00:26
This issue is specific to Docker for Mac, and cannot be resolve in this repository.

I see there is an issue to track it in the docker for mac issue tracker; https://github.com/docker/for-mac/issues/218 (possibly others as well), so I am locking this issue. Please continue the conversation on the linked issue.
