### ISSUE TITLE
docker error "/proc/self/exe: too many open files" (results in docker ps hang)

### ISSUE THREAD

**Issue by mkanade** [docker/docker#27140] opened 2016-10-04 11:16 UTC
Description

In a mesos cluster with docker running on each of the nodes, and a certain mesos docker task failing and restarting continuously, a docker error "too many files open" is observed.

This is possible similar to other docker issue which was closed without any solutions/workarounds: https://github.com/docker/docker/issues/8693

The workaround is to set the open FD limit for docker to some higher value. But that is not a complete fix. Docker migth not be closing all the open FDs for failed tasks

**Steps to reproduce the issue:**
1. To reproduce this issue, I set the open FD limit for docker process to a very small number 128 
2. As soon as a one of the app container failed multiple times on the node, the no of open file descriptors scaled above 128
sh-4.2# lsof -p 6525  |wc -l
161
3. docker ps hangs and any further mesos docker tasks go to failed state

**Describe the results you received:**
sh-4.2# lsof -p 6525  |wc -l
lsof: WARNING: can't stat() xfs file system /mnt/docker/devicemapper/mnt/2e68e91e68d55b392da19918fe886d17da1216927737c36982d86fa03666cc08
      Output information may be incomplete.
lsof: WARNING: can't stat() xfs file system /mnt/docker/devicemapper/mnt/60a350751af409047e4e3e92b8843078347f4d67712c180e62242fdd01541a2f
      Output information may be incomplete.
lsof: WARNING: can't stat() xfs file system /mnt/docker/devicemapper/mnt/8784f479605c8d0fccd9142388df7a041a95160fff71414c883778cc5e140756
      Output information may be incomplete.
161

Docker logs which have the too many open files error:
fa37f74f1b79f7013ff3805040196061" statusCode=500
Oct  4 10:03:53 docker: time="2016-10-04T10:03:53.952732346Z" level=info msg="GET /v1.21/images/mesos-9d0369d2-b2b5-4d84-9927-846a1cf45837-S1.73e97f4c-efab-4043-ab1a-5297d5354532/json"
Oct  4 10:03:53 docker: time="2016-10-04T10:03:53.952989384Z" level=error msg="Handler for GET /v1.21/images/mesos-9d0369d2-b2b5-4d84-9927-846a1cf45837-S1.73e97f4c-efab-4043-ab1a-5297d5354532/json returned error: No such image: mesos-9d0369d2-b2b5-4d84-9927-846a1cf45837-S1.73e97f4c-efab-4043-ab1a-5297d5354532"
Oct  4 10:03:53 docker: time="2016-10-04T10:03:53.953013770Z" level=error msg="HTTP Error" err="No such image: mesos-9d0369d2-b2b5-4d84-9927-846a1cf45837-S1.73e97f4c-efab-4043-ab1a-5297d5354532" statusCode=404
Oct  4 10:03:54 : time="2016-10-04T10:03:54.433975183Z" level=info msg="POST /v1.21/containers/6b26db7338c31714fc78f12ef232987afa37f74f1b79f7013ff3805040196061/attach?stderr=1&stdout=1&stream=1"
Oct  4 10:03:54 docker: time="2016-10-04T10:03:54.435068716Z" level=info msg="POST /v1.21/containers/6b26db7338c31714fc78f12ef232987afa37f74f1b79f7013ff3805040196061/start"
Oct  4 10:03:54 docker: time="2016-10-04T10:03:54.577552213Z" level=info msg="GET /v1.21/containers/mesos-9d0369d2-b2b5-4d84-9927-846a1cf45837-S1.73e97f4c-efab-4043-ab1a-5297d5354532/json"
Oct  4 10:03:54 docker: time="2016-10-04T10:03:54.595877879Z" level=warning msg="Failed to allocate and map port 31968-31968: fork/exec /proc/self/exe: too many open files"

Systemd docker service errors: 

Oct 04 11:13:35 docker[6525]: 2016/10/04 11:13:35 http: Accept error: accept unix /var/run/docker.sock: too many open files; retrying in 1s
Oct 04 11:13:36 docker[6525]: 2016/10/04 11:13:36 http: Accept error: accept unix /var/run/docker.sock: too many open files; retrying in 1s
Oct 04 11:13:37 docker[6525]: 2016/10/04 11:13:37 http: Accept error: accept unix /var/run/docker.sock: too many open files; retrying in 1s
Oct 04 11:13:37 docker/ee61337c29a6[6525]: time="2016-10-04T11:13:37Z" level=info msg="response completed" go.version=go1.6.2 http.re...ent="sp
Oct 04 11:13:37 docker/ee61337c29a6[6525]: 192.168.0.2 - - [04/Oct/2016:11:13:37 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "spray-can/1.3.2"
Oct 04 11:13:37 docker/ee61337c29a6[6525]: time="2016-10-04T11:13:37Z" level=info msg="response completed" go.version=go1.6.2 http.re...tp.requ
Oct 04 11:13:37 docker/ee61337c29a6[6525]: 192.168.10.4 - - [04/Oct/2016:11:13:37 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.9.1 g.../amd64"
Oct 04 11:13:37 docker/ee61337c29a6[6525]: time="2016-10-04T11:13:37Z" level=info msg="response completed" go.version=go1.6.2 http.re...p/gwaas
Oct 04 11:13:37 docker/ee61337c29a6[6525]: 192.168.10.4 - - [04/Oct/2016:11:13:37 +0000] "GET /v2/iotsp/gwaas-portal/manifests/develo.../amd64"
Oct 04 11:13:38 docker[6525]: 2016/10/04 11:13:38 http: Accept error: accept unix /var/run/docker.sock: too many open files; retrying in 1s
Hint: Some lines were ellipsized, use -l to show in full.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker --version
Docker version 1.9.1

```

**Output of `docker info`:**

```
Docker info has also hung: but pasting docker info from a different node which does not have the same issue but from the same cluster:

sh-4.2# docker info
Containers: 16 
Images: 119
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:32-16777344-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.483 GB
 Data Space Total: 107.4 GB
 Data Space Available: 7.4 GB
 Metadata Space Used: 8.024 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /mnt/docker/devicemapper/devicemapper/data
 Metadata loop file: /mnt/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: syslog
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 7.797 GiB
Name: xxxxxxxxxx
ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is reproduced on a cluster of Centos VMs

**Comment by cpuguy83** [comment] 2016-10-04 13:16
@mkanade There have been some issues with not closing FD's in various places. I see you are running docker 1.9. Please try with docker 1.12 and see if you still see a problem.

Going to close this for now unless we get a real reproducible case on the current release... in which case it's probably best to open an issue about the specific reproducible case rather than a generic one which would otherwise just stay open forever.

Happy to discuss here even though it's closed.

**Closed by cpuguy83** 2016-10-04 13:16 UTC

**Comment by milindchawre** [comment] 2016-10-28 12:43
@manuwelakanade 
@cpuguy83 Can you please reopen this issue.

I tried this with latest docker release 1.12 and observed the same issue.
This is what I tried :
1. Written a shell script that run containers in loop.
----------------------------------------
#!/bin/bash -eux

i=0
while [ $i -lt 500 ]
do
  sudo docker run -d busybox sh -c "while true; do echo alive; sleep 60000; done"
  i=`expr $i + 1`
  echo $i
done
----------------------------------------
2. Set FD limit to 128 in docker daemon
3. Ran the script and observed FD limit errors
-----------------------------------------------------------------------------
4b01cfbe4b3d171016fe5c929a6f7418dfc819acf5258a38631edfb04df28d48
25
9fe5ec3b99e8630681d332567ab2d256c2c61d5c263fa507e7473361f409f41d
26
ae70dbb618f3007511bdd37f39c85e7adec1807063f6f92feb9c6d00e9b3344e
docker: Error response from daemon: oci runtime error: process_linux.go:334: running prestart hook 0 caused "exit status 1: time=\"2016-10-28T12:28:38Z\" level=fatal msg=\"failed to create a netlink handle: too many open files\" \n".
27
5eca3c4144b53b1fde2556a05e957a06e11e6bf4c387d85db4ff4d396e89a06b
docker: Error response from daemon: oci runtime error: process_linux.go:334: running prestart hook 0 caused "exit status 1: time=\"2016-10-28T12:28:39Z\" level=fatal msg=\"failed to create a netlink handle: could not get current namespace while creating netlink socket: too many open files\" \n".
28
b721ef7dcb5ed56b49b14a4b8f89ce6a9146eb23f3f70f5de72f9d3bb6463352
docker: Error response from daemon: oci runtime error: process_linux.go:334: running prestart hook 0 caused "exit status 1: time=\"2016-10-28T12:28:40Z\" level=fatal msg=\"open /var/run/docker/netns/7941a78ae371: too many open files\" \n".
-----------------------------------------------------------------------------
4. The open FD count
[cloud-user@mckernel-worker-0 ~]$ sudo lsof -p 21736 | wc -l
158
[cloud-user@mckernel-worker-0 ~]$

**Comment by cpuguy83** [comment] 2016-10-28 12:46
@milindchawre Please open a new issue with the specific case, thanks!

**Comment by milindchawre** [comment] 2016-11-02 10:08
@cpuguy83 
I try to repro the same issue with infinite FD limit and I was not able.

Observed few things :
1. Exited containers do not occupy FD.
2. Ran into ipv4 address limit issue after creating 253 running containers with /24 bridge ip so switched to /16
3. Same with /16, ran into veth exchange full issue. Since I hit the 1023 max network interface limit.
4. Tweak the script to exit containers in 60 seconds and I was able to create and delete containers simultaneously at very high speed, where I was not able to hit the FD limit issue.

So is setting FD limit as infinite is OK? Is it a standard practice? or Is there any risk in it?

**Comment by cpuguy83** [comment] 2016-11-02 14:52
@milindchawre Docker does need to have open files.
There's stdin,stdout,stderr fifos and the container logs at the very least per container.

**Comment by milindchawre** [comment] 2016-11-03 05:11
@cpuguy83 So its ok to set FD limit to infinity. I see its mentioned here https://docs.docker.com/engine/admin/systemd/#/runtime-directory-and-storage-driver

**Comment by subbu05** [comment] 2017-01-18 19:15
Hello,

I am also facing same issues.
cat /proc/36718/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             unlimited            unlimited            processes
Max open files            65536                65536                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       63392                63392                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited



issue with Max open files            65536                65536                files

Unable to create containers beyond 117. 

I see ~500+ openfiles per container. Its a golang application server running as container.

**Comment by cpuguy83** [comment] 2017-01-18 19:17
> I see ~500+ openfiles per container

What has 500 open files? What files are they?

**Comment by subbu05** [comment] 2017-01-18 22:12
FIFO, a_inode files

**Comment by singhmal** [comment] 2017-10-30 11:16
"Set FD limit to 128 in docker daemon"

How to increase FD limit on Centos? 
`cat /proc/<docker-pid>/limits | grep Max open files` gives 
`Max open files            1024                 4096                 files`

Where as ulimit -n is 70000

**Comment by gerardo8a** [comment] 2018-03-20 18:23
I do have the same issue, we run it with a limit of
Max open files            65536                65536                files
-bash-4.2$ sudo ls -l /proc/3359/fd|wc -l
65537

Is there a way to configure docker to close the connections? or timeout connections?

My docker version 
Docker version 1.12.6, build ec8512b/1.12.6

if some one have any idea on how to debug what is hanging the connections it will also helpful, but I prefer to docker to take care of this kind of issues, this is an ongoing issue that even after upgrading to this version I still get this behavior.

**Comment by harryge00** [comment] 2018-06-25 09:14
@gerardo8a I have the same issue and am trying to debug. The 3359 is the Pid of your docker daemon?
