### ISSUE TITLE
Docker Stats Improvement: Exit on "q" keystroke.

### ISSUE THREAD

**Issue by iMerica** [docker/docker#12464] opened 2015-04-17 01:54 UTC
The monitoring tools `top` and `htop` both use "q" to signal a graceful exit. Docker stats could benefit from having this same interface instead of control-c (SIGINT) which A) isn't a graceful and B) exits with status 2.

**Comment by iMerica** [comment] 2015-04-17 01:58
Steps to Reproduce (I use Docker Compose):
1) `docker stats $(docker-compose ps | awk '{print $1}' | tail -n+3 | tr '\n' ' ')`
2) Enter `q`.
3) Observe nothing happens.
4) Enter `Control-C`
5) Observe Docker stats has closed forcefully and the exit status is 2.

**Comment by phemmer** [comment] 2015-04-17 02:06
dup of #12393
Though this does have the additional note of the exit code. That bit wasn't mentioned over there.

**Comment by thaJeztah** [comment] 2015-04-17 06:27
Thanks @phemmer

I'm going to close this issue because it's a duplicate of #12393, please continue the discussion in that ticket. Thanks for reporting @iMerica!

**Closed by thaJeztah** 2015-04-17 06:27 UTC

**Comment by Hicsy** [comment] 2021-12-04 00:40
how is this still not resolved? `q` does nothing. `ctrl+c` does nothing. Why doesnt even the web-manual say how to exit?
https://docs.docker.com/engine/reference/commandline/stats/

**Comment by HammyHavoc** [comment] 2022-05-19 01:48
> how is this still not resolved? `q` does nothing. `ctrl+c` does nothing. Why doesnt even the web-manual say how to exit? https://docs.docker.com/engine/reference/commandline/stats/

`CTRL+C` works. But I do agree, `q` would be ideal. I spent 2 minutes just now figuring this out.
