### ISSUE TITLE
Config to control the defaults for new custom bridge networks

### ISSUE THREAD

**Issue by far-blue** [docker/docker#22804] opened 2016-05-18 09:50 UTC
It would be very helpful to have config parameters or settings within the daemon.json config file to control some of the default parameters when a new bridge network is created. At the moment, the default appears to be to create a /16 network on the next available class B range in 172.n.0.0/16. I realise this is configurable when manually creating bridge networks on the cli and it is configurable within the docker-compose file if using docker-compose but I don't think the docker-compose file is the right place to be putting such default config - it's more for when you wish to define an exception.

It would be very helpful to have control over the IP ranges used - such as using /24 rather than /16 and moving the range from 172.x.0.0 to something else.

**Comment by shane-axiom** [comment] 2016-05-19 08:29
+1

In my case, I need to disallow Docker from using certain subnets. Docker is creating a bridge network using `192.168.0.0/20`, which conflicts with a range I use for an ipsec VPN connection.

I agree that it would be helpful to set the default subnet size as the current `/16` and `/20` are much larger than needed for most projects.

**Comment by nschoe** [comment] 2016-05-20 13:46
I'll +1 this too. On my machine, it seems I can't spawn more than 25 stacks created with docker-compose. This is a huge problem for me :/

**Comment by nschoe** [comment] 2016-05-23 13:45
I have been scouting through `libnetwork` code for the last couple of days, hoping to find some way to customize this behavior.

I have found where the pools get initialized, and I've pinpointed the location where it defaults to `/16`, [here](https://github.com/docker/libnetwork/blob/eac8b773b4690bfbdfef9598dc95af6ae93a46df/ipamutils/utils.go#L30).

So my initial thought was that we could provide some sort of argument to `InitNetworks()` (same file, line 21).

I searched where `InitNetworks()` was called, I think I found it [here](https://github.com/docker/docker/blob/14b5a50f0a95a2b8f3ed7ab7469bbab02189a09c/vendor/src/github.com/docker/libnetwork/ipams/builtin/builtin_unix.go#L33).

This happens inside an `Init()` function. So I tried to find where it was called, but I could not find anything... so maybe someone more knowledgeable about the code can pinpoint the location?

Unfortunately, I don't know Go at all, I can only read it a bit, so I don't know the structure of Go programs: is there a custom entrypoint? Is there a main function? etc.

Anyway, the feeling I have is that we could make `Init()` accept an argument to be passed to `InitNetworks()` to set the Global network's subnet's size.

What do you think?

**Comment by cpuguy83** [comment] 2016-05-23 13:52
I would rather not have this as a daemon argument as it will affect portability. (ie, app works perfectly on one daemon but not another).

Instead a more portable configuration at the network level seems to be a better approach, by (e.g.) setting the subnet size rather than the actual range.

**Comment by nschoe** [comment] 2016-05-23 13:58
@cpuguy83 yeah, that would make more sense to set this up at the network-level.

I think I'm in for another dive into libnetwork's code. Any idea where to start?

**Comment by far-blue** [comment] 2016-05-23 14:00
I don't think it's an issue of an app working on one daemon or another. Apps should exist in containers and containers are already allocated dynamic private network ranges so shouldn't be making assumptions. If a specific network configuration is required then the docker-compose or docker run parameters should still override the defaults. But what we are looking for here is the ability for a system administrator to control docker's default behaviour when allocating private bridge networks by limiting those subnets available to it (preventing collision with existing networks) and limiting the size of the private network.

To my knowledge there isn't an equiv. of the daemon.json config file for libNetwork - it is expected to be configured programatically by the apps using the lib. So the only place to do this is via the daemon. However, I do suggest it need not be something passed on the daemon launch command - it could quite happily be something only controllable via daemon.json config file.

**Comment by nschoe** [comment] 2016-05-23 14:08
@far-blue I think we are dealing with two different problems here:

- what @cpuguy83  is saying (I've just confirmed this with him on IRC, because I was not sure) is that suppose you deploy an app with docker-compose that makes use of > 255 containers in a single bridge network. Then if your target user configured his docker daemon to only allocate `/24` subnets, then it will fail because your stack could not find IPs for all containers. (This actually works with less than 255 containers, if the target user configured his daemon with `/28` for instance).
So I agree with the fact that it breaks portability.
- the second issue you raised is: there should be a way to **exclude** some subnets so that docker doesn't try to allocate networks in excluded subnets. I think this is valid too, but maybe a different problem.

**Comment by far-blue** [comment] 2016-05-23 14:18
I think the problem here is that it seems totally fine to allow the person using `docker run` or the person writing a docker-compose yml file to customise the networks being created but the same level of trust is not available to the system administrator to setup sensible defaults for their particular environment.

**Comment by cpuguy83** [comment] 2016-05-23 14:20
@far-blue This could be handled at the authorization layer... e.g deny a request because it's using a subnet that is not allowed.

**Comment by far-blue** [comment] 2016-05-23 14:23
I'm not really thinking about preventing customisations applied via cli (docker network create) or via a docker-compose file. But I do want the ability to set sensible defaults because it's much easier and less hassle than having to train users to add non-portable blocks to the bottom of their docker-compose files to prevent the system breaking in unexpected ways - and then answer all the issues generated when things do break.

**Comment by mavenugo** [comment] 2016-05-23 15:45
@cpuguy83 @far-blue @nschoe I do see the point @far-blue is raising here. If a particular compose application (or CLI driven) requires 255 IPs but relies on the default IP-Address allocation policy, its the applications fault. Rather the application must use the provided `--subnet` option to make sure the app is portable regardless of how the defaults are set.  OTOH, it can impact portability in some scenarios such as address overlap. 

So, having configurable defaults isn't a bad thing or the only cause for portability issues. just my 2c.

**Comment by aboch** [comment] 2016-05-25 01:00
Same was requested in  https://github.com/docker/docker/issues/21776#issuecomment-206133109
We should probably close this as duplicate of #21776.

**Comment by nschoe** [comment] 2016-05-25 08:08
Yeah, agreed.

**Comment by LukasBacigal** [comment] 2016-05-25 12:09
It was requested as a response to problem, I think this can address just this specific feature request, so I am against close.

**Comment by vdemeester** [comment] 2016-05-25 12:18
Closing this then, feel free to continue the discussion on #21176 😇

**Comment by LukasBacigal** [comment] 2016-05-25 12:23
You link to pull instead of issue :innocent:

**Comment by vdemeester** [comment] 2016-05-25 12:27
Damn phone.. 😑 😫 😱

**Comment by vdemeester** [comment] 2016-05-25 12:28
#21776 it is 😂

**Closed** 2016-05-25 12:28 UTC
Labels: group/networking, kind/feature
