### ISSUE TITLE
-restcomm docker image on windows 8.1

### ISSUE THREAD

**Issue by Prefer2Watch** [docker/docker#17784] opened 2015-11-07 14:04 UTC
I am trying to install Docker image of Restcomm on my windows 8.1 laptop by following http://www.telestax.com/rapid-webrtc-application-development-with-restcomm-and-docker/. I am able to install DOCKER and run the container Hello-world properly.

But when i run the command to create container... "docker run –name=restcomm -d -e STATIC_ADDRESS=”YOUR_HOST_IP_ADDRESS_HERE” -p 8080:8080 -p 5080:5080 -p 5082:5082 -p 5080:5080/udp -p 65000-65535:65000-65535/udp gvagenas/restcomm"

i am getting the following error... Error response from daemon: Cannot start container c88fcab56034096e98ddcd71d1d2db17e5858b88c64b1859efcb86d740e3972c: failed to create endpoint restcomm on network bridge: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 65116 -j DNAT --to-destination 172.17.0.2:65116 ! -i docker0: (fork/exec /usr/local/sbin/iptables: cannot allocate memory)

Request for your help and suggestion and thanks in advance

Rgds Ias

**Comment by Prefer2Watch** [comment] 2015-11-07 14:08
PLs. find below some more information about our docker env...
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 1
Images: 48
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 50
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: 26VR:H6QC:RRWB:HI5Y:ALJW:TEJ7:5YVG:TYBP:X7WE:XPOA:FTXG:UREX
Debug mode (server): true
 File Descriptors: 46
 Goroutines: 224
 System Time: 2015-11-07T14:07:57.578235433Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

$ uname -a
MINGW64_NT-6.3 Sai-P2W 2.3.0(0.290/5/3) 2015-09-16 19:07 x86_64 Msys

**Comment by Prefer2Watch** [comment] 2015-11-08 13:51
Hello 
I have also tried to start the RESTCOMM Container through kitematic and still the same issue and for more details pls. refer to the screen links below.
Request for our help and suggestion as  in what i am i missing and i can't find similar issues in documentation or forum links as well.

![screenshot 2015-11-08 13 48 45](https://cloud.githubusercontent.com/assets/4687273/11020708/8ffb6e92-861f-11e5-925c-5eb816f77f53.png)

thanks in advance
Ias

**Comment by thaJeztah** [comment] 2015-11-11 20:31
> `fork/exec /usr/local/sbin/iptables: cannot allocate memory`

It wouldn't surprise me if this is the problem you're running into and the virtual machine is running out of memory, causing it to fail.

**Comment by thaJeztah** [comment] 2015-11-11 20:32
You could try to give the virtual box virtual machine more memory, or set memory constraints on the container; http://docs.docker.com/engine/reference/run/#user-memory-constraints to prevent it from using too much memory.

**Comment by unclejack** [comment] 2016-01-24 11:04
This issue seems to involve multiple open source components from various Docker projects. This makes it a whole lot more complex to debug on an issue tracker. This is an issue to be discussed on a forum, not on the Docker engine issue tracker.

This kind of question and general support questions are more adequate for the following:
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.
4) StackOverflow https://stackoverflow.com/questions/tagged/docker

I'm going to close this issue now because this doesn't seem to be a Docker issue and the discussion can continue and assistance can be provided even if the issue is in closed state. Please feel free to continue the discussion. There's no need to open a new issue on this topic.

For everyone who's getting started, please consider starting a discussion on the forums if you're getting started and you need help. Thank you for understanding.

**Closed by unclejack** 2016-01-24 11:04 UTC
