### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by SimonWang2014** [docker/docker#10915] opened 2015-02-20 12:27 UTC
I found when use Dockerfile to build a image, if the Dockerfile is large, the docker often occurs error -->   "no space left on device" , it turns that the inode has been used up, but the storage is enough, How to resolve?

**Comment by thaJeztah** [comment] 2015-02-22 00:04
Based on just this information, this could be a duplicate of https://github.com/docker/docker/issues/9755,  https://github.com/docker/docker/issues/5900 or https://github.com/docker/docker/issues/10613

Would you be able to provide the output of `docker info`, `docker version` and `uname -a`?

**Comment by dmp42** [comment] 2015-02-23 23:18
cc @crosbymichael

**Comment by jfrazelle** [comment] 2015-02-28 03:50
closing as dup of  #5900 or #10613

**Closed by jfrazelle** 2015-02-28 03:50 UTC
