### ISSUE TITLE
Docker panic upon error 429 during pull

### ISSUE THREAD

**Issue by bcwalrus** [docker/docker#16198] opened 2015-09-09 23:39 UTC
docker version: 1.7.1

My test registry throws 429 for rate-limiting. Apparently that's not handled very well:

```
Test docker pull & push. ... panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x641d2c]

goroutine 138 [running]:
net/http.(*chunkWriter).flush(0xc2083876a0)
        /usr/local/go/src/net/http/server.go:283 +0x5c
net/http.(*response).Flush(0xc208387680)
        /usr/local/go/src/net/http/server.go:1048 +0x66
github.com/docker/docker/pkg/ioutils.(*WriteFlusher).Write(0xc2083f5e60, 0xc20839e780, 0xbb, 0x140, 0xbb, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/ioutils/writeflusher.go:21 +0x145
github.com/docker/docker/pkg/progressreader.(*Config).Read(0xc2083c04d0, 0xc2086c2000, 0x8000, 0x8000, 0x3f70, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/progressreader/progressreader.go:37 +0x2e5
io.Copy(0x7f34804d72a8, 0xc2080392b8, 0x7f34804f1280, 0xc2083c04d0, 0x951b58, 0x0, 0x0)
        /usr/local/go/src/io/io.go:362 +0x1f6
github.com/docker/docker/graph.func��008(0xc20800f8c0, 0x0, 0x0)
        /go/src/github.com/docker/docker/graph/pull.go:602 +0xd42
github.com/docker/docker/graph.func��009(0xc20800f8c0)
        /go/src/github.com/docker/docker/graph/pull.go:626 +0x2f
created by github.com/docker/docker/graph.(*TagStore).pullV2Tag
        /go/src/github.com/docker/docker/graph/pull.go:627 +0x2671
```

See the full output at https://gist.github.com/bcwalrus/b8eb7ece04a8235e3aa1

**Comment by cpuguy83** [comment] 2015-09-10 01:41
I feel like this was fixed in 1.8, but may be difficult to pinpoint what PR.

**Comment by thaJeztah** [comment] 2015-12-18 12:53
@bcwalrus have you reproduced this on docker 1.8+, shall I close this issue?

**Comment by LK4D4** [comment] 2016-09-14 15:56
Closing because code changed drastically and nobody reported this again.

**Closed by LK4D4** 2016-09-14 15:56 UTC
Labels: status/more-info-needed
