### ISSUE TITLE
Can not use dynbinary on ubuntu 14.04

### ISSUE THREAD

**Issue by hqhq** [docker/docker#12535] opened 2015-04-20 08:35 UTC
There is a long story in: https://github.com/docker/docker/issues/4036
In short, if we want to use devicemapper on ubuntu 14.04, we should use dynbinary instead of directly `make binary`. But in my experience, dynbinary can't be used directly even we installed `libdevmapper-dev` and `libdevmapper1.02.1` on ubuntu 14.04.

After some digging, I found in build container, device-mapper was installed from source code:
```
 55 # Get lvm2 source for compiling statically
 56 RUN git clone -b v2_02_103 https://git.fedorahosted.org/git/lvm2.git /usr/local/lvm2
 57 # see https://git.fedorahosted.org/cgit/lvm2.git/refs/tags for release tags
 58
 59 # Compile and install lvm2
 60 RUN cd /usr/local/lvm2 \
 61         && ./configure --enable-static_link \
 62         && make device-mapper \
 63         && make install_device-mapper
 64 # see https://git.fedorahosted.org/cgit/lvm2.git/tree/INSTALL
```
In this way, the name of so file is `libdevmapper.so.1.02`, but on ubuntu 14.04, the so file name in package `libdevmapper1.02.1` is `libdevmapper.so.1.02.1`, see http://packages.ubuntu.com/trusty/amd64/libdevmapper1.02.1/filelist

So if we use `./hack/make.sh dynbinary` in build image, then copy `docker` and `dockerinit` to `/usr/bin`, it's not usable because it tried to find `libdevmapper.so.1.02`, but we only have `libdevmapper.so.1.02.1`.

I tried to change Dockerfile to use libdevmapper package instead of build form source code, but I can't make binary with error `/usr/bin/ld: cannot find -ldevmapper`, seems a bug from libdevmapper package that it failed to link `/usr/lib/libdevmapper.so`, is this why we build devicemapper from source code in the first place? ping @tianon 

A quick fix would be setup a soft link named `libdevmapper1.02` to `libdevmapper1.02.1`, but I wonder if we have a real fix, dynamic binary built from ubuntu14.04 should be usable on ubuntu14.04 directly.

**Comment by unclejack** [comment] 2015-04-20 10:32
@hqhq The solution to this problem is to actually build distribution specific Docker packages and provide repositories. Dynamic binaries built from the main Dockerfile are only supposed to be used for testing dynamic Docker binaries within the Docker container.

What you're looking for is `AUTO_GOPATH=1 ./project/make.sh dynbinary`, not `make dynbinary`. This actually builds dynamic binaries which use your system's libraries because the build takes place on your host, not in a container.

**Comment by hqhq** [comment] 2015-04-21 11:06
@unclejack But I'm talking about build Ubuntu 14.04 specific Docker packages with Ubuntu 14.04 repository, so we already have a distribution specific Dockerfile for Ubuntu 14.04.
I do build dynamic binaries with `./hack/make.sh dynbinary`, add `AUTO_GOPATH=1` still not fix the problem.
I think the problem is why device-mapper build from source code generates different .so file from the official repository?

**Comment by chrissnell** [comment] 2015-04-30 22:12
Any chance we could get some Ubuntu packages built with dynbinary?   #4036 is causing us a lot of pain right now.   We deploy Docker through Chef and it uses the package to install.  Building Docker by hand for dynbinary is going to be very painful in our environment.   Thanks.

**Comment by virtuald** [comment] 2015-05-05 16:02
+1 on dynamic ubuntu packages, #4036 is also a problem for us, and aufs isn't cutting it.

**Comment by chrissnell** [comment] 2015-05-05 18:13
@virtuald @hqhq - I have made some progress on this issue and #12925 (which appears to be a dupe of  #12535).     Reading @unclejack's comments more closely, I realized that I should try building docker on my actual Ubuntu 14.04 system and not within the dockercore/docker container in order to get the proper libraries linked.   So, here's what I did on the Ubuntu host (not the container):

```
% sudo apt-get install build-essential libdevicemapper-dev btrfs-tools libsqlite3-dev

[next, install Go 1.4.2 from source or binary]

% git clone https://github.com/docker/docker.git

% cd docker

% AUTO_GOPATH=1 ./hack/make.sh dynbinary

% sudo service docker stop

[next, move /usr/bin/docker and /var/lib/docker/init/docker* out of the way to a temp directory for safekeeping in case this doesn't work for you]

% sudo cp bundles/1.7.0-dev/dynbinary/dockerinit-1.7.0-dev /var/lib/docker/init/
% sudo cp bundles/1.7.0-dev/dynbinary/docker-1.7.0-dev /usr/bin/docker
```
And now, Docker should start properly:
```
% sudo service docker start
% sudo tail -f /var/log/upstart/docker.log
```

**Comment by chrissnell** [comment] 2015-05-05 18:17
This leaves me in a quandary, though: should I try to figure out how to assemble my own .deb package of this custom-compiled binary or should I wait for the Docker team to build an official one?

I'm certain that #4036 is affecting a lot of Ubuntu 14.04 folks and I humbly beg the Docker team to make a dynamic binary package for us.   If they don't fill the need, some non-affiliated person will probably make an unofficial package and that's no good for anyone.

**Comment by tianon** [comment] 2015-05-05 18:45
https://github.com/docker/docker/blob/6bb596219f8c852cd48322ac9a4a4f605d29c6b8/hack/make/build-deb
is the latest in us actively working on exactly that :+1:

**Comment by chrissnell** [comment] 2015-05-05 18:47
Thanks @tianon.  Is there an issue I can follow to track the progress?  This has ground my project to a halt.  Thanks.

**Comment by tianon** [comment] 2015-05-05 18:50
We don't have a single issue tracking it, but @jfrazelle and I are working on solving it as quickly as we can (hopefully for 1.7, but we'll see).  You can test that script from a clone of master right now by doing `make shell` and then something like `./hack/make.sh build-deb`, which will spit out `.deb` files into `bundles/latest/build-deb/`.

**Comment by thaJeztah** [comment] 2015-05-05 18:55
Perhaps this issue should be renamed and used as a tracker-issue? @tianon are there currently blocking issues with creating the .debs, or other issues that can be linked here? (thinking "checkboxes" with issue numbers)

**Comment by chrissnell** [comment] 2015-05-06 18:54
So ```./hack/make.sh build-deb``` runs for a long time and seems to build packages but dies with this:

https://gist.github.com/chrissnell/d0dc8fe4c0e41aecb71e

I poked around in the directory structure and found this package:

```
bundles/1.7.0-dev/build-deb/ubuntu-debootstrap-trusty/docker-engine_1.7.0~dev~git20150505.174315.0.6bb5962-0~trusty_amd64.deb
```

This package does indeed install and it does function but the package is missing some important things like the Upstart configuration/init script.  I don't know if the early termination of ```build-deb``` left me with this incomplete package.   

Is there a way to generate a package that's functionally equivalent to the packages distributed by get.docker.io?

**Comment by thaJeztah** [comment] 2015-05-07 01:52
Looks like a fix is in the making for the issue reported by @chrissnell; see https://github.com/docker/docker/pull/13038 (not merged yet)

**Comment by chrissnell** [comment] 2015-05-07 04:06
Nice!  Thanks @tianon!!  Guys, would it be possible to get an official "pre-release" 1.7.0-dev Ubuntu (trusty) package put up on get.docker.io?   I'm going to bake my own deb using your fixes to keep my project moving along but I know that there are quite a few folks out here that are encountering this issue w/ Ubuntu 14.04.  Your fixes are the only way to have a Registry 2.0-compatible Docker on Ubuntu 14.04 right now.   Thanks again!

**Comment by chrissnell** [comment] 2015-05-07 18:16
```./hack/make.sh dynbinary build-deb``` is failing now:

```
 ---> Running in 639f36e33c03
docker-engine (1.7.0/home/cjsdev~git20150507.163859.0.d78755d-0~jessie) jessie; urgency=low

  * Version: 1.7.0-dev

 -- Docker <support@docker.com>  Thu, 07 May 2015 18:11:34 +0000
 ---> 78994fd083c8
Removing intermediate container 639f36e33c03
Step 5 : RUN dpkg-buildpackage -uc -us
 ---> Running in c4739b886713
parsechangelog/debian: warning:     debian/changelog(l1): version '1.7.0/home/cjsdev~git20150507.163859.0.d78755d-0~jessie' is invalid: version number contains illegal character `/'
LINE: docker-engine (1.7.0/home/cjsdev~git20150507.163859.0.d78755d-0~jessie) jessie; urgency=low
dpkg-buildpackage: error: version number contains illegal character `/'
dpkg-buildpackage: source package docker-engine
dpkg-buildpackage: source version 1.7.0/home/cjsdev~git20150507.163859.0.d78755d-0~jessie
time="2015-05-07T18:13:10Z" level=info msg="The command \"/bin/sh -c dpkg-buildpackage -uc -us\" returned a non-zero code: 255"
+++++ cat /home/cjs/docker/bundles/1.7.0-dev/build-deb/docker.pid
++++ kill 1165
```

**Comment by tianon** [comment] 2015-05-07 18:26
Are you building that on your host, or inside the container from `make shell`?

**Comment by chrissnell** [comment] 2015-05-07 18:33
I tried both ways.  Same result.

**Comment by tianon** [comment] 2015-05-07 18:34
Gah.  Ok, looking into it. :heart:

**Comment by tianon** [comment] 2015-05-07 20:01
Yeesh, in Bash 4.2.53 on my host, `\~` becomes a literal `\~`.  In Bash 4.3.11 inside the container though, `\~` works fine (just like `'~'` did before, but on my host, no dice).

Looks like this is going to be our only way to win:
```bash
	tilde='~' # ouch Bash 4.2 vs 4.3, you keel me
	debVersion="${VERSION//-/$tilde}" # using \~ or '~' here works in 4.3, but not 4.2; just ~ causes $HOME to be inserted, hence the $tilde
```

**Comment by chrissnell** [comment] 2015-05-07 21:48
Excellent, it works now!   The .debs are good and have all of the required files.   Daemon seems to start up and function properly, though I need to do more testing.   In the meantime, I've put unofficial .debs up on my site if anybody needs them:

(http://chrissnell.com/docker/)[http://chrissnell.com/docker/]

If the Docker folks object, I will take them down.   This will not be a nightly thing...just a one-time deal.

**Comment by tianon** [comment] 2015-05-07 21:50
:+1:

**Comment by chrissnell** [comment] 2015-05-08 04:08
Me building the debs is a pretty ugly hack.  I'm going to have to set up my own signed apt repo just to get these installed correctly across my cluster.   Sure would be nice to have them up on get.docker.io, just sayin'.  :wink: 

Thanks again for your efforts.

**Comment by thaJeztah** [comment] 2015-05-08 04:28
@chrissnell absolutely! also see: https://github.com/docker/docker/pull/13038#issuecomment-99721834

**Comment by thaJeztah** [comment] 2015-06-07 16:12
@hqhq @chrissnell is this issue resolved now that https://github.com/docker/docker/issues/13038 and https://github.com/docker/docker/issues/13065 are merged?

**Comment by chrissnell** [comment] 2015-06-07 16:38
Yes, we can resolve this one.   Still hoping for some official deb 1.7.0-dev packages but perhaps we can start a new issue to track that.

**Comment by thaJeztah** [comment] 2015-06-07 17:09
@chrissnell absolutely, I think it would make sense to create a "Provide dynamic builds on master.dockerproject.org" or something along that. Feel free to create it and you can add a link referring to https://github.com/docker/docker/pull/13038#issuecomment-99721834 (Just my opinion here :)). Perhaps it's already implemented, but I don't know (in which case it can be closed quickly)


I'm going to close this issue, because the problem described here should be solved, but feel free to comment if you think I closed this by mistake.

**Closed by thaJeztah** 2015-06-07 17:09 UTC
