### ISSUE TITLE
Implement log file location parameter on docker run

### ISSUE THREAD

**Issue by chicoandrade** [docker/docker#29680] opened 2016-12-23 21:13 UTC
We have several logging options, but we can't change the log file location.

Using the **json-file** driver we can find the file at /var/lib/docker/<container_id>/<container_id>-json.log (default), but it would be useful to set the log file name and path as we can set the max-size and max-file on json-file.
https://docs.docker.com/engine/admin/logging/overview/#/json-file-options

e.g.: *docker run -d --log-driver=json-file --log-opt max-file=5 **--log-opt file-path=/var/log/my-container.log** my-image*

**Comment by thaJeztah** [comment] 2016-12-23 22:17
The file written by the `json-file` logging driver are not intended for consumption by external software, and should be regarded the "internal storage mechanism" for the JSON logging driver. For that reason, the location is not configurable.

If you want to have the logs written to a different location, consider using (e.g.) the `syslog` driver, `journald`, or one of the drivers that allow sending the logs to a central log aggregator.

**Comment by stanleyk** [comment] 2017-03-30 08:43
@thaJeztah Please, what is then the proposed and desired way of consuming the `json-file` logging driver produced logs? Since the file itself is just "internal storage mechanism" (i.e. we shouldn't access and read them directly), what other ways of obtaining the produced logs can we use in this case (other than `docker logs CONTAINER`)? Thank you.

**Comment by thaJeztah** [comment] 2017-03-30 10:27
`docker logs <container>`, or using the Docker API is the way

**Comment by cpuguy83** [comment] 2017-04-10 21:27
Log plugin support is now merged and should be part of 17.05.
I do not think it makes sense to implement this in docker core, however can be implemented via plugins. 
Here is a reference plugin that just wraps jsonfilelog: https://github.com/cpuguy83/docker-log-driver-test

If anyone wants to discuss this feel free to ping me on Slack, or come see me @ DockerCon!

**Closed by cpuguy83** 2017-04-10 21:27 UTC
Labels: area/logging, kind/enhancement

**Comment by Nastradamus** [comment] 2020-09-17 10:39
@thaJeztah  It's very strange, because Kubernetes consumes Docker's _LogPath_.

I want to move all Docker logs into tmpfs due to reduce disk I/O, but... I can't. Very painful.

**Comment by thaJeztah** [comment] 2020-09-17 11:06
> because Kubernetes consumes Docker's LogPath.

Yes, the `LogPath` should (IMO) never have been part of the information returned by the API, or at least have been documented as an internal implementation details (not for external consumption). It's quite unfortunate that Kubernetes chose to consume those files directly instead of using the API; it's one of the consequences of Docker ever having been designed as a runtime for Kubernetes.

Generally, as a runtime for Kubernetes, running Kubernetes directly on containerd (which supports the  container runtime interface (CRI)) https://github.com/containerd/containerd. Containerd was designed from the ground up to be used as a runtime for Kubernetes (removing parts that are not needed for that purpose); in that setup, `dockerd` (through  `docker-shim`) is taken out as intermediate daemon between kubernetes and containerd.

From that perspective, I don't think we want to implement this feature

**Comment by Nastradamus** [comment] 2020-09-17 11:27
@thaJeztah  
Thank you for the detailed explanation!

I opened _fatrace_ tool: Now I see that only Docker daemon is accessing json log file (now I have Kubernetes 1.16). Maybe it was a problem in later k8s releases.

Now I'd like to examine docker's json driver code to understand how it interracts with write() system calls and ring buffer.
Trying to find workaround: don't want to lose logs in a non-blocking mode.

**Comment by thaJeztah** [comment] 2020-09-17 11:33
If you don't need the JSON files, I would also recommend having a look at the `local` logging driver https://docs.docker.com/config/containers/logging/local/, which should be more performant than the json-file driver, and defaults to use log-rotation.

**Comment by Fuseteam** [comment] 2025-03-13 13:10
@thaJeztah the local logging driver doesn't seem to have an option for a file-path
my goal is have a container write logs for external consumption, is there a driver that i can use that allows for this?
