### ISSUE TITLE
docker swarm restart-condtion is not adpated

### ISSUE THREAD

**Issue by Namsulee** [docker/docker#32321] opened 2017-04-03 15:14 UTC
**Description**
After creation docker service with option which is '--restart-condition any'. If I kill dockerd after running the service, the container should be restarted if I start dockerd again. --restart-condition is only for service abstraction that I create? every time service which is created re create container again. Therefore the containers are still in the list with exited(137) code. Is it right behavior or a bug?

**Steps to reproduce the issue:**
1. Create service
$ docker service create --name test --restart-condition any busybox tail -f /dev/null
2. Check service and container whether it runs or not
3. Kill dockerd
4. Start dockerd
5. Check container

CONTAINER ID        IMAGE                                                                             COMMAND               CREATED             STATUS                       PORTS               NAMES
b7f05b1d1c05        busybox@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f   "tail -f /dev/null"   6 minutes ago       Up 6 minutes                                     test.1.pra8lelu4szo9do8ch8gmjgtk
3f0282124045        busybox@sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f   "tail -f /dev/null"   7 minutes ago       Exited (137) 6 minutes ago                       test.1.rk9f49fi7rxuyzcf4pl4emhx6

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 29
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: u3alux6p8rvzqwt0ugcs3a2if
 Is Manager: true
 ClusterID: sjp6h4vgfa457rcfojvpcmy1s
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.0.6
 Manager Addresses:
  192.168.0.6:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.763 GiB
Name: namsu-H81H3-M4
ID: 6VSX:3RD6:BYDG:HGXJ:YINK:RADA:E6K7:RPVV:SGXV:LI56:OEDH:7JTI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: namsulee
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 13.124.64.10:80
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-04-03 15:33
This is by design; in swarm mode, docker manages _services_, not individual "containers" (tasks). When you define a service, docker will make sure that the specified number of instances of that service are running. If one of those tasks fails, docker creates a new one to replace it. The "old" (failed) task is kept around to allow you to investigate _why_ the task failed. The number of "old" tasks to preserve is configurable through the `--task-history-limit` option on `docker swarm update`. Once there are more than "`--task-history-limit`" tasks, older tasks (containers) are removed.

I'll close this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-04-03 15:33 UTC
Labels: area/swarm, version/1.13
