### ISSUE TITLE
broken link to install instructions for version 1.9 

### ISSUE THREAD

**Issue by SCBuergel** [docker/docker#20974] opened 2016-03-05 14:33 UTC
I dont know where else to post this issue: Trying to install version 1.9 following [the website](https://docs.docker.com/v1.9/), I noticed a dead link in `docker engine` -> `ubuntu` sending me to https://docs.docker.com/v1.9/installation/ubuntulinux/ which gives a 404.

**Comment by SCBuergel** [comment] 2016-03-05 14:53
since this is related to the website I do not know what docker version / info I should supply here and hence omitted it.

**Comment by clinty** [comment] 2016-03-05 22:59
You might find the links on the left sidebar to be less broken.

**Comment by thaJeztah** [comment] 2016-03-05 23:23
Also, be aware that the install instructions always install the latest version; you should be able to follow the regular instructions, but when installing (`apt-get install`) provide the version you want to install. For example;

First check the available versions:

```
apt-cache policy docker-engine
docker-engine:
  Installed: 1.10.2-0~trusty
  Candidate: 1.10.2-0~trusty
  Version table:
 *** 1.10.2-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     1.10.1-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.10.0-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.9.1-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.9.0-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.8.3-0~trusty 0....
```

And install that version;

```
apt-get install docker-engine=1.9.1-0~trusty
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be DOWNGRADED:
  docker-engine
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 16 not upgraded.
Need to get 7,486 kB of archives.
After this operation, 5,193 kB disk space will be freed.
Do you want to continue? [Y/n]
```

**Comment by Samurais** [comment] 2016-04-06 05:47
get the same issue.
```
The following package was automatically installed and is no longer required:
  libsystemd-journal0
Use 'apt-get autoremove' to remove it.
The following NEW packages will be installed:
  docker-engine
0 upgraded, 1 newly installed, 0 to remove and 133 not upgraded.
Need to get 7486 kB of archives.
After this operation, 38.0 MB of additional disk space will be used.
Err https://apt.dockerproject.org/repo/ ubuntu-trusty/main docker-engine amd64 1.9.1-0~trusty
  Failed to connect to apt.dockerproject.org port 443: Connection refused
E: Failed to fetch https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.9.1-0~trusty_amd64.
deb  Failed to connect to apt.dockerproject.org port 443: Connection refused

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by thaJeztah** [comment] 2016-04-06 06:04
@Samurais I'm unable to reproduce; could there be a firewall blocking requests for apt.dockerproject.org?

**Comment by Samurais** [comment] 2016-04-06 06:08
I disable the firewall by ufw. But nothing changes. The installation hangs for requesting files from apt.dockerproject.org. Since this machine is running in China, if requesting to google endpoints, it fails.
I think it is caused by GFW in China.

**Comment by thaJeztah** [comment] 2016-04-06 06:30
@Samurais yes, I suspect the same. Unfortunately, I can't help you with that

**Comment by calavera** [comment] 2016-04-14 23:34
I'm closing this issue since there is nothing we can do about the GFW, sorry about that.

Refer to this guide to install Ubuntu: https://docs.docker.com/engine/installation/linux/ubuntulinux/
v1.9 is obsolete.

**Closed by calavera** 2016-04-14 23:34 UTC
