### ISSUE TITLE
Mounts using the :z or :Z mode don't create the folder on the Docker host

### ISSUE THREAD

**Issue by alvaroaleman** [docker/docker#17240] opened 2015-10-21 14:35 UTC
As disovered in https://github.com/ansible/ansible-modules-core/pull/2312:

``docker run -it -v /nonexistant:/tmp:Z debian:jessie bash``

causes a 

``Error response from daemon: no such file or directory``.

This is different from a mount using ``:ro`` or ``:rw`` mode which both cause the folder on the host to be created.

**Comment by cpuguy83** [comment] 2015-10-21 16:07
Cannot reproduce this, though I don't have selinux setup.
Also note that host paths are auto-created on container start regardless of options: https://github.com/docker/docker/blob/master/daemon/volumes.go#L51

... and also note that this is deprecated in 1.9, with removal scheduled for 1.11


What is the output of `docker version` and `docker info`?

**Comment by alvaroaleman** [comment] 2015-10-21 18:22
> BUG REPORT INFORMATION

> Use the commands below to provide key information from your environment:

```
docker version
Client:
 Version:      1.8.2-fc23
 API version:  1.20
 Package Version: docker-1.8.2-7.gitcb216be.fc23.x86_64
 Go version:   go1.5.1
 Git commit:   77d0d91-dirty
 Built:        Mon Oct 12 16:58:35 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-fc23
 API version:  1.20
 Package Version: 
 Go version:   go1.5.1
 Git commit:   77d0d91-dirty
 Built:        Mon Oct 12 16:58:35 UTC 2015
 OS/Arch:      linux/amd64
```

```
docker info
Containers: 3
Images: 94
Storage Driver: devicemapper
 Pool Name: docker-253:1-3151512-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.002 GB
 Data Space Total: 107.4 GB
 Data Space Available: 41.98 GB
 Metadata Space Used: 4.198 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107 (2015-09-05)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.3-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
```
```
uname -a
Linux $hostname 4.2.3-300.fc23.x86_64 #1 SMP Mon Oct 5 15:42:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

> Provide additional environment details (AWS, VirtualBox, physical, etc.):
Phsysical

List the steps to reproduce the issue:
1. ``sudo rm -rf /nonexistant``
2. ``sudo docker run -it -v /nonexistant:/tmp:Z debian:jessie bash``

> Describe the results you received:

``Error response from daemon: no such file or directory``

> Describe the results you expected:

Me beeing in a container

> Provide additional info you think is important:

* This is reproducible in my F23 host described above
* This is reproducible in the centos/7 vagrant box (``vagrant init centos/7 && vagrant up --provider libvirt``)
* This is  not reproducible on the ubuntu/trusty64 vagrant box using the ``docker.io`` package from the official repos (``vagrant init ubuntu/trusty64 && vagrant up --provider virtualbox``)

**Comment by cpuguy83** [comment] 2015-10-21 18:24
Can you try with the offical rpm package?

**Comment by alvaroaleman** [comment] 2015-10-21 18:28
> Can you try with the offical rpm package?

What do you mean by that? Official as in maintained by docker.inc? I can only find instructions for Ubuntu on the [Docker website](http://docs.docker.com/linux/step_one/)

**Comment by cpuguy83** [comment] 2015-10-21 18:30
https://docs.docker.com/installation/fedora/

**Comment by alvaroaleman** [comment] 2015-10-21 18:37
**Fedora 23:**

```
yum update
Yum command has been deprecated, redirecting to '/usr/bin/dnf update'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'

Docker Repository                                                                                                                                                                                               10 kB/s | 2.9 kB     00:00    
Last metadata expiration check performed 0:00:00 ago on Wed Oct 21 20:31:04 2015.
Dependencies resolved.
Nothing to do.
Complete!
```

 **CentOS 7:**

it doesn't install from your repo either, since the docker in ``@extras`` repo is apparently newer. Thus no change in behaviour.

**Comment by thaJeztah** [comment] 2015-10-22 01:10
@alvaroaleman perhaps you can try performing an uninstall first; https://docs.docker.com/installation/fedora/#uninstall

**Comment by alvaroaleman** [comment] 2015-10-22 07:04
Oh my bad, your package is called ``docker-engine``, not ``docker``.

Well, using ``docker-engine``, the issue is not reproducable. On the other hand, using your package no selinux labels get changed at all and anything can be mounted inside the container without causing an AVC denial:

```bash
sudo docker run -it -v /etc/passwd:/etc/passwd:Z debian:jessie bash
root@d4f71a568697:/# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
[...]

# On other term
getenforce
Enforcing
ls -lZ /etc/passwd
-rw-r--r--. 1 root root system_u:object_r:passwd_file_t:s0 942 May 22 00:01 /etc/passwd
```

So in short: Your package doesn't have the issue because it seems to use an  'allow all' SELinux policy for its containers and apart from that not do anything related to SELinux.

Do you actually maintain the ``:z``  and ``:Z`` volume parameter implementation or is this done by RedHat and you just keep your stuff compatible by mapping those two to ``:rw``?

**Comment by thaJeztah** [comment] 2015-10-22 07:48
We maintain that parameter; it was originally contributed by Red Hat, and carried in this PR; https://github.com/docker/docker/pull/12572

**Comment by thaJeztah** [comment] 2015-10-22 08:01
However, we don't have a selinux-policy in docker 1.8 (you can install "docker-selinux" separately). Docker 1.9 does bundle a selinux-policy. For testing, you can find release-candidates here: https://github.com/docker/docker/pull/17000#issuecomment-147926878

**Comment by alvaroaleman** [comment] 2015-10-22 09:00
> However, we don't have a selinux-policy in docker 1.8 (you can install "docker-selinux" separately). 

Installing docker-selinux doesn't make Docker label anything

> Docker 1.9 does bundle a selinux-policy. [...]

Tried the ``curl -sSL https://test.docker.com/ | sh`` on both the centos/7 and the Fedora box, still Docker works but doesn't label, even thought the package ``docker-engine-selinux-1.9.0-0.1.rc1.el7.centos.noarch `` is present.

**Comment by cpuguy83** [comment] 2015-10-22 10:40
you have to set "--selinux-enabled" on the daemon.

**Comment by alvaroaleman** [comment] 2015-10-22 11:06
Oh okay, assumed that to be the default.

CentOS 7 using docker-engine 1.9.0-0.1.rc1.el7.centos:

```bash
docker run -it -v /nonexistant:/tmp:Z debian:jessie bash
An error occurred trying to connect: Post http:///var/run/docker.sock/v1.21/containers/create: EOF
ls -ldZ /nonexistant
ls: cannot access /nonexistant: No such file or directory
```

CentOS 7 using docker-engine 1.8.3-1.el7.centos:

```bash
docker run -it -v /nonexistant:/tmp:Z debian:jessie bash
Error response from daemon: no such file or directory
ls -ldZ /nonexistant
ls: cannot access /nonexistant: No such file or directory
```

**Comment by rhatdan** [comment] 2015-10-22 12:50
There would be no difference between the versions.  But from above, the SELinux behaviour is correct going forward.

BTW doing something like `-v /etc/passwd:/etc/passwd:Z` is a BAD idea.  Since it will break all confined domains on your system that attempt to read /etc/passwd.

I guess we can close this issue.

**Comment by thaJeztah** [comment] 2015-10-22 14:30
Thanks for chiming in @rhatdan, and yes, I think this issue can be closed.

Thanks for reporting @alvaroaleman, happy to hear it's resolved for you

**Closed by thaJeztah** 2015-10-22 14:30 UTC
