### ISSUE TITLE
Docker run + docker rm gets frequent "no such container" daemon error

### ISSUE THREAD

**Issue by pkpp1233** [docker/docker#10562] opened 2015-02-04 19:53 UTC
I'm doing a simple test of Docker run and Docker rm. Here's how it works, in one process I enter:

    watch -n0 sudo docker run -t -i busybox echo 'hi'

In another process I enter:
    
    watch -n0 "sudo docker ps -f status=exited -a -q | sudo xargs docker rm"

Theoretically containers should be opening and deleting on exit. However, I frequently get the following errors (due to race) in the docker run process:

error-type 1:

    No such container: 2a569995c303b901e7bc4254673c271af4344e560b08d4e233a082d5a31fcd38 
    time="2015-02-04T19:03:54Z" level="fatal" msg="Error response from daemon: No such container: 2a569995c303b901e7bc42546 73c271af4344e560b08d4e233a082d5a31fcd38"

error-type 2:

    time="2015-02-04T19:05:17Z" level="fatal" msg="Error response from daemon: Cannot start container e22fb573e780824aabe54
    43220ee71c5634be5d40ee4e3adb597bb92435d7e41: Error getting container e22fb573e780824aabe5443220ee71c5634be5d40ee4e3adb5
    97bb92435d7e41 from driver devicemapper: open /dev/mapper/docker-8:1-262148-e22fb573e780824aabe5443220ee71c5634be5d40ee 4e3adb597bb92435d7e41: no such file or directory"

error-type 3:

    FATA[0000] Error response from daemon: Cannot start container 
    83e66df41f74fdd5299577d672ca8ea01bb88e3477b791a8d4cae7db0f1f3039: Error getting container 
    83e66df41f74fdd5299577d672ca8ea01bb88e3477b791a8d4cae7db0f1f3039 from driver devicemapper: Error mounting '/dev/mapper/docker-8:1-262148-83e66df41f74fdd5299577d672ca8ea01bb88e3477b791a8d4cae7db0f1f3039' on '/var/lib/docker/devicemapper/mnt/83e66df41f74fdd5299577d672ca8ea01bb88e3477b791a8d4cae7db0f1f3039': no such file or directory 

I found this issue somewhat related b/c of devicemapper: https://github.com/docker/docker/issues/4036.
I'm on ubuntu trusty.

**update** - we're using aufs now and error is still popping up.

**Comment by jaytaylor** [comment] 2015-02-04 22:55
I am also hitting this issue.  Host OS is Ubuntu trusty 14.04.1.

Here is a Dockerfile which reliably reproduces the issue:

    FROM ubuntu
    
    RUN bash -c 'echo hi $(date)'
    RUN bash -c 'echo hi $(date)'
    RUN bash -c 'echo hi $(date)'
    RUN bash -c 'echo hi $(date)'
    RUN bash -c 'echo hi $(date)'
    RUN bash -c 'echo hi $(date)'
    RUN bash -c 'echo hi $(date)'
    RUN bash -c 'echo hi $(date)'
    RUN bash -c 'echo hi $(date)'
    
    CMD /bin/bash -c 'for true; do date; sleep 5; done'

Sample session output:

    root@buildbox:/tmp/1-my-test-app.git728540307# docker build .
    Sending build context to Docker daemon 53.25 kB
    Sending build context to Docker daemon
    Step 0 : FROM ubuntu
     ---> 5ba9dab47459
    Step 1 : RUN bash -c 'echo hi $(date)'
     ---> Running in ee5c0bfeab95
    INFO[0000] Error getting container ee5c0bfeab957f18e43edadc2576f54b8a9956ea647cb1d19915251a4cd0b00e from driver devicemapper: open /dev/mapper/docker-8:1-268784-ee5c0bfeab957f18e43edadc2576f54b8a9956ea647cb1d19915251a4cd0b00e: no such file or directory

This sort of error is generated anytime I attempt to build from a Dockerfile containing more than around 3-5 stanzas in it.

**Comment by jaytaylor** [comment] 2015-02-04 23:31
@pkpp1233 you may also be interested in this comment on #4036: https://github.com/docker/docker/issues/4036#issuecomment-65622899

Seems to be along the same vein as what you're dealing with.

**Comment by pkpp1233** [comment] 2015-02-04 23:41
Good find. That's the same problem. Thanks @jaytaylor.

**Comment by tiborvass** [comment] 2015-02-08 00:36
@unclejack is this a dupe of #4036 ?

**Comment by unclejack** [comment] 2015-02-08 09:52
@pkpp1233 Have you wiped out your `/var/lib/docker` directory after switching to aufs?
Also, please provide the full output of `docker info`, `docker version` and `uname -a`. These bits of information are required in order to investigate and try to help.

**Comment by pkpp1233** [comment] 2015-02-09 02:37
@unclejack yup wiped out <code>/var/lib/docker</code> after switching to aufs.

<b>docker info</b>
```
Containers: 0
Images: 175
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 4071
Execution Driver: native-0.2
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 14.69 GiB
Name: {{ ip }}
ID: {{ id }}
```

<b>docker version</b>
```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

<b>uname -a</b>
```
Linux {{ ip }} 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by wyaeld** [comment] 2015-03-24 03:41
I'm also seeing a lot of the type2 errors @pkpp1233 is talking about during builds.  Particulary on low-resource cloud environments.  It seems like it hasn't finished writing/releases 1 layer and then tries to access it and fails.  Rerunning the build again fastforwards to the failure point because of cached layers, and always passed the 2nd time.

```
ubuntu@sot-prod:~$ docker info
Containers: 23
Images: 483
Storage Driver: devicemapper
 Pool Name: docker-253:32-3014657-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 24.14 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 28.99 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /mnt/docker-vol/devicemapper/devicemapper/data
 Metadata loop file: /mnt/docker-vol/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.861 GiB
Name: sot-prod
ID: B4IG:EZZQ:FYM5:CNML:AGDI:MYOY:GOGZ:MOIC:G2MG:WJ7J:JJHR:DAJ5
Username: wyaeld
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
ubuntu@sot-prod:~$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by rhvgoyal** [comment] 2015-06-12 13:54
I believe these issues are happening because of statically built docker where libdm does not sync with udev. 

Please obtain a dynamically built docker from distribution or build it yourself. 

@vbatts 

Can we please close this issue.

**Comment by vbatts** [comment] 2015-06-12 22:05
Ah yeah. This is a duplicate of #4036

**Closed by vbatts** 2015-06-12 22:05 UTC
Labels: /system/devicemapper
