### ISSUE TITLE
Fedora 24 f24 support (packages, config)

### ISSUE THREAD

**Issue by westurner** [docker/docker#25095] opened 2016-07-26 22:51 UTC
**Output of `docker version`:**

- not relevant

**Output of `docker info`:**

- not relevant

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Fedora 24

**Steps to reproduce the issue:**
1. https://docs.docker.com/engine/installation/linux/fedora/#/install
2. (``$releasever`` = 24) ``dnf update``
3. https://yum.dockerproject.org/repo/main/fedora/24/ -> 403 Forbidden

**Describe the results you received:**

- There is no f24 package

**Describe the results you expected:**

- ``dnf install docker`` would install docker

**Additional information you deem important (e.g. issue happens only occasionally):**

- This is a workstation which has been upgraded from f22->f23->f24.
  - Post-upgrade, docker is broken (``AVC denial`` errors; I'd rather avoid one-off ``audit2allow``)

**Comment by thaJeztah** [comment] 2016-07-26 22:53
This is a duplicate of https://github.com/docker/docker/issues/24495 and https://github.com/docker/docker/issues/24785; see those issues for more information

**Closed by thaJeztah** 2016-07-26 22:53 UTC

**Comment by westurner** [comment] 2016-07-26 22:59
```bash
sudo service docker start
journalctl -xe | pbcopy
```

```
# [...]
Jul 26 17:52:36 mb1 sudo[22624]:  username : TTY=pts/0 ; PWD=/home/username/-wrk/-ve27/djangotestapp/src/djangotestapp ; USER=root ; COMMAND=/sbin/service docker start
Jul 26 17:52:36 mb1 audit[22624]: USER_CMD pid=22624 uid=1000 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='cwd="/home/username/-wrk/-ve27/djangotestapp/src/djangotestapp" cmd=7365727669636520646F636B6572207374617274 terminal=pts/0 res=success'
Jul 26 17:52:36 mb1 audit[22624]: CRED_REFR pid=22624 uid=0 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Jul 26 17:52:36 mb1 audit[22624]: USER_START pid=22624 uid=0 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Jul 26 17:52:36 mb1 sudo[22624]: pam_systemd(sudo:session): Cannot create session: Already occupied by a session
Jul 26 17:52:36 mb1 sudo[22624]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 17:52:36 mb1 polkitd[1001]: Registered Authentication Agent for unix-process:22637:37388640 (system bus name :1.426 [/usr/bin/pkttyagent --notify-fd 4 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.utf8)
Jul 26 17:52:36 mb1 audit[1]: AVC avc:  denied  { create } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=unix_stream_socket permissive=0
Jul 26 17:52:36 mb1 systemd[1]: docker.socket: Failed to listen on sockets: Permission denied
Jul 26 17:52:36 mb1 systemd[1]: Failed to listen on Docker Socket for the API.
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has failed.
-- 
-- The result is failed.
Jul 26 17:52:36 mb1 systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is dependency.
Jul 26 17:52:36 mb1 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Jul 26 17:52:36 mb1 audit[22624]: USER_END pid=22624 uid=0 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Jul 26 17:52:36 mb1 sudo[22624]: pam_unix(sudo:session): session closed for user root
Jul 26 17:52:36 mb1 audit[22624]: CRED_DISP pid=22624 uid=0 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Jul 26 17:52:36 mb1 polkitd[1001]: Unregistered Authentication Agent for unix-process:22637:37388640 (system bus name :1.426, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.utf8) (disconnected from bus)
Jul 26 17:52:39 mb1 dbus[930]: [system] Activating service name='org.fedoraproject.Setroubleshootd' (using servicehelper)
Jul 26 17:52:40 mb1 dbus[930]: [system] Successfully activated service 'org.fedoraproject.Setroubleshootd'
Jul 26 17:52:40 mb1 setroubleshoot[22691]: SELinux is preventing systemd from create access on the unix_stream_socket Unknown. For complete SELinux messages. run sealert -l dbe8f5d2-c62e-4bc1-9dbc-a9ee200ed374
Jul 26 17:52:40 mb1 python3[22691]: SELinux is preventing systemd from create access on the unix_stream_socket Unknown.
                                    
                                    *****  Plugin catchall (100. confidence) suggests   **************************
                                    
                                    If you believe that systemd should be allowed create access on the Unknown unix_stream_socket by default.
                                    Then you should report this as a bug.
                                    You can generate a local policy module to allow this access.
                                    Do
                                    allow this access for now by executing:
                                    # ausearch -c 'systemd' --raw | audit2allow -M my-systemd
                                    # semodule -X 300 -i my-systemd.pp
                                    
Jul 26 17:53:02 mb1 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=fprintd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

# ... #

Jul 26 17:54:17 mb1 sudo[22779]:  username : TTY=pts/0 ; PWD=/home/username/-wrk/-ve27/djangotestapp/src/djangotestapp ; USER=root ; COMMAND=/sbin/service docker start
Jul 26 17:54:17 mb1 audit[22779]: USER_CMD pid=22779 uid=1000 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='cwd="/home/username/-wrk/-ve27/djangotestapp/src/djangotestapp" cmd=7365727669636520646F636B6572207374617274 terminal=pts/0 res=success'
Jul 26 17:54:17 mb1 audit[22779]: CRED_REFR pid=22779 uid=0 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_fprintd acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Jul 26 17:54:17 mb1 audit[22779]: USER_START pid=22779 uid=0 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Jul 26 17:54:17 mb1 sudo[22779]: pam_systemd(sudo:session): Cannot create session: Already occupied by a session
Jul 26 17:54:17 mb1 sudo[22779]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 26 17:54:17 mb1 polkitd[1001]: Registered Authentication Agent for unix-process:22780:37398699 (system bus name :1.429 [/usr/bin/pkttyagent --notify-fd 4 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.utf8)
Jul 26 17:54:17 mb1 audit[1]: AVC avc:  denied  { create } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=unix_stream_socket permissive=0
Jul 26 17:54:17 mb1 systemd[1]: docker.socket: Failed to listen on sockets: Permission denied
Jul 26 17:54:17 mb1 systemd[1]: Failed to listen on Docker Socket for the API.
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has failed.
-- 
-- The result is failed.
Jul 26 17:54:17 mb1 systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is dependency.
Jul 26 17:54:17 mb1 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Jul 26 17:54:17 mb1 audit[22779]: USER_END pid=22779 uid=0 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Jul 26 17:54:17 mb1 audit[22779]: CRED_DISP pid=22779 uid=0 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_fprintd acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
Jul 26 17:54:17 mb1 sudo[22779]: pam_unix(sudo:session): session closed for user root
Jul 26 17:54:17 mb1 polkitd[1001]: Unregistered Authentication Agent for unix-process:22780:37398699 (system bus name :1.429, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.utf8) (disconnected from bus)
Jul 26 17:54:20 mb1 dbus[930]: [system] Activating service name='org.fedoraproject.Setroubleshootd' (using servicehelper)
Jul 26 17:54:20 mb1 dbus[930]: [system] Successfully activated service 'org.fedoraproject.Setroubleshootd'
```

**Comment by westurner** [comment] 2016-07-26 23:01
@thaJeztah this issue also contains information regarding AVC denial messages with f23.

- I'll try the testing/ packages linked here: https://github.com/docker/docker/issues/24495#issuecomment-231772810

**Comment by westurner** [comment] 2016-07-26 23:05
```
$ sudo dnf update
Docker Repository                                                                                                              22 kB/s | 6.6 kB     00:00    
Dependencies resolved.

==============================================================================================================================================================
 Package                                     Arch                         Version                                      Repository                        Size
==============================================================================================================================================================
Upgrading:
 docker-engine                               x86_64                       1.12.0-0.5.rc5.fc24                          dockerrepo                        19 M
 docker-engine-selinux                       noarch                       1.12.0-0.5.rc5.fc24                          dockerrepo                        32 k
Skipping packages with broken dependencies:
 docker-engine-selinux                       src                          1.12.0-0.5.rc5.fc24                          dockerrepo                        23 k

Transaction Summary
==============================================================================================================================================================
Upgrade  2 Packages
Skip     1 Package

Total download size: 19 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): docker-engine-selinux-1.12.0-0.5.rc5.fc24.noarch.rpm                                                                   100 kB/s |  32 kB     00:00    
(2/2): docker-engine-1.12.0-0.5.rc5.fc24.x86_64.rpm                                                                           642 kB/s |  19 MB     00:30    
--------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                         643 kB/s |  19 MB     00:30     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Upgrading   : docker-engine-selinux-1.12.0-0.5.rc5.fc24.noarch                                                                                          1/4 
Re-declaration of boolean virt_sandbox_use_fusefs
Failed to create node
Bad boolean declaration at /var/lib/selinux/targeted/tmp/modules/100/virt/cil:148
/usr/sbin/semodule:  Failed!
  Upgrading   : docker-engine-1.12.0-0.5.rc5.fc24.x86_64                                                                                                  2/4 
  Cleanup     : docker-engine-1.11.2-1.fc23.x86_64                                                                                                        3/4 
  Cleanup     : docker-engine-selinux-1.11.2-1.fc23.noarch                                                                                                4/4 
  Verifying   : docker-engine-1.12.0-0.5.rc5.fc24.x86_64                                                                                                  1/4 
  Verifying   : docker-engine-selinux-1.12.0-0.5.rc5.fc24.noarch                                                                                          2/4 
  Verifying   : docker-engine-1.11.2-1.fc23.x86_64                                                                                                        3/4 
  Verifying   : docker-engine-selinux-1.11.2-1.fc23.noarch                                                                                                4/4 

Upgraded:
  docker-engine.x86_64 1.12.0-0.5.rc5.fc24                                  docker-engine-selinux.noarch 1.12.0-0.5.rc5.fc24                                 

Complete!
#  sudo dnf update
```

**Comment by westurner** [comment] 2016-07-26 23:13
```
$ dnf remove -y docker-engine
# ...
$ dnf install -y docker-engine
```

Still shows:
```bash
# ...
Re-declaration of boolean virt_sandbox_use_fusefs
Failed to create node
Bad boolean declaration at /var/lib/selinux/targeted/tmp/modules/100/virt/cil:148
/usr/sbin/semodule:  Failed!
# ...
```

And then

```bash
$ sudo systemctl enable docker.socket
Failed to execute operation: No such file or directory
$ sudo systemctl start docker
Failed to start docker.service: Unit docker.socket not found.

```

**Comment by westurner** [comment] 2016-07-26 23:37
@thaJeztah

- Should I create another issue for these errors re: docker 1.12? Or rename this ticket and ask you to re-open it?

**Comment by thaJeztah** [comment] 2016-07-26 23:39
I think that issue is fixed on master; see https://github.com/docker/docker/pull/25094
can you try updating your unit file with that change?

**Comment by westurner** [comment] 2016-07-26 23:50
Thanks, that should work for now.
https://github.com/docker/docker/pull/25094/files#diff-3bd6288c24a051bde82fbfbc48b5c016L5
