### ISSUE TITLE
Flaky test: DockerSuite.TestLogsSince

### ISSUE THREAD

**Issue by calavera** [docker/docker#17221] opened 2015-10-20 21:55 UTC
Encountered on:

#17136 
#17213

```
----------------------------------------------------------------------
FAIL: docker_cli_logs_test.go:169: DockerSuite.TestLogsSince

docker_cli_logs_test.go:183:
    c.Assert(out, checker.Not(checker.Contains), v, check.Commentf("unexpected log message returned, since=%v", since))
... value string = "" +
...     "2015-10-17T15:06:58.004736043Z 1445094417 log2\n" +
...     "2015-10-17T15:07:00.006619695Z 1445094420 log3\n"
... substring string = "log2"
... unexpected log message returned, since=1445094418


----------------------------------------------------------------------
```

**Comment by runcom** [comment] 2015-11-30 09:48
duplicate of #16599 keeping track there

**Closed by runcom** 2015-11-30 09:48 UTC
Labels: kind/flakytest
