### ISSUE TITLE
During building dockerfile, build files gets not written if they write after command exits

### ISSUE THREAD

**Issue by kevinsimper** [docker/docker#12051] opened 2015-04-03 08:54 UTC
I have step in my dockerfile where i concat and uglify my javascript. I am using gulp.js for that and it streaming the files, so it exits before the file is finishes writing, because the bottleneck is the harddrive.

So the problem is that because the command exit before the file is finished create, the files does not get commited to the docker image.

This does not work, the ls will return a empty folder:
```
FROM node:wheezy

RUN apt-get update -y && apt-get upgrade -y

WORKDIR /app

VOLUME /app

COPY . /app

RUN npm install

ENV NODE_ENV production

RUN npm run build && ls -alF public/build/

EXPOSE 9000

CMD NODE_ENV=production npm start
```

```
Step 7 : RUN npm run build
 ---> Running in ca23524f39da

> blackbeardapp@1.0.0 build /app
> gulp build

[08:46:17] Using gulpfile /app/gulpfile.js
[08:46:17] Starting 'browserify'...
[08:46:17] Starting 'browserify-admin'...
[08:46:23] Finished 'browserify' after 5.29 s
[08:46:25] Finished 'browserify-admin' after 7.63 s
[08:46:25] Starting 'build'...
[08:46:25] Finished 'build' after 24 μs
 ---> b8a744b92c7b
Removing intermediate container ca23524f39da
Step 8 : RUN ls -alF public/build/
 ---> Running in b7e3db63b293
total 12
drwxr-xr-x 2 root root 4096 Apr  3 08:33 ./
drwxr-xr-x 6 root root 4096 Mar 29 17:03 ../
-rw-rw-r-- 1 root root    7 Mar 11 21:00 .exists
 ---> 3da00e862513
```

The build/build is empty, but there should be a `bundle.js` and `admin.js` file.

But if i run the build step like this:

```
RUN npm run build && ls -alF public/build/
```
the output is this
```
Step 7 : RUN npm run build && ls -alF public/build/
 ---> Running in 5167f738d001

> blackbeardapp@1.0.0 build /app
> gulp build

true
[08:50:07] Using gulpfile /app/gulpfile.js
[08:50:07] Starting 'browserify'...
[08:50:07] Starting 'browserify-admin'...
levom /app/app/index.js
/app/app/admin/index.js
[08:50:12] Finished 'browserify' after 5.38 s
[08:50:15] Finished 'browserify-admin' after 7.87 s
[08:50:15] Starting 'build'...
[08:50:15] Finished 'build' after 25 μs
total 308
drwxr-xr-x 2 root root   4096 Apr  3 08:50 ./
drwxr-xr-x 6 root root   4096 Mar 29 17:03 ../
-rw-rw-r-- 1 root root      7 Mar 11 21:00 .exists
-rw-r--r-- 1 root root 142854 Apr  3 08:50 admin.js
-rw-rw-r-- 1 root root 155797 Apr  3 08:50 bundle.js
 ---> afca23c83836
```

See here is `admin.js` and `bundle.js`.
So that extra command, lets the files get finished writing and committed right into the dockerfile.

But when i then go into the container manually, the files is not there even through seeing it just in the docker buildstep

```
$ docker run -i -t --rm -P 664fad2625ce /bin/bash
root@04655c082a27:/app# ls -alF public/build/
total 12
drwxr-xr-x 2 root root 4096 Apr  3 08:33 ./
drwxr-xr-x 6 root root 4096 Mar 29 17:03 ../
-rw-rw-r-- 1 root root    7 Mar 11 21:00 .exists
```

This really weirded me out!

**Comment by cstpdk** [comment] 2015-04-03 09:15
Hmm, best bet is that the exit code of the build command is something that docker interprets as "ok, done", but that the shell operator "&&" knows to wait for. What is the exit code of the npm command?

**Comment by phemmer** [comment] 2015-04-05 09:49
Your issue is this:

    VOLUME /app

You've told docker that `/app` is to be stored outside the container. Thus when the container runs `npm run build`, the files aren't inside the container, and don't get stored in the image.

Solution, remove that line :-)

**Comment by thaJeztah** [comment] 2015-04-07 22:18
@phemmer is correct here. Volumes are also applied during the build process and a new volume is created for each step; everything performed on the `/app` dir (after the `VOLUME` instruction), will be done in a new volume.

Either remove the `VOLUME` instruction, or move it to the end of the Dockerfile.

I'm closing this issue, as it looks like this is not a bug in Docker, but feel free to continue the discussion.

**Closed by thaJeztah** 2015-04-07 22:18 UTC
