### ISSUE TITLE
EOF error when removing image

### ISSUE THREAD

**Issue by Soulou** [docker/docker#12050] opened 2015-04-03 08:37 UTC
Hi there,

I just encountered a new bug when deleting images on one of my host. I'm using the BTRFS storage backend, and when I try to remove an image (which is not used by any container), I get the following error:

It applies to any image of the host, not only `myimage:latest` I've used as a test. I can't remove any image.

Any idea? Thanks!

Client side:

```
$ docker rmi myimage:latest
Error response from daemon: EOF
FATA[0000] Error: failed to remove one or more images  
```

Server side:

```
^[[34mINFO^[[0m[42698] DELETE /v1.17/images/myimage:latest
^[[34mINFO^[[0m[42698] +job image_delete(myimage:latest)
EOF
^[[34mINFO^[[0m[42699] -job image_delete(myimages:latest) = ERR (1)
^[[31mERRO^[[0m[42699] Handler for DELETE /images/{name:.*} returned error: EOF
^[[31mERRO^[[0m[42699] HTTP Error: statusCode=500 EOF
```

Docker image:
```
myimage                  latest     42dbfabfe2bff94daf4b4dc126fc6804c699f33480c874eb2c9fa4cc83a387b5   10 days ago         911.4 MB
```

Docker version:

```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

Docker info

```
Containers: 303
Images: 555
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 6
Total Memory: 31.42 GiB
Name: <hostname>
ID: AZNH:RYE6:EPU2:OM3H:RQGL:E6GL:3PCA:BJJP:JVQO:ILYS:G7B4:TWOZ
```

**Comment by Soulou** [comment] 2015-04-08 14:19
It is apparently linked to the BTRFS partition itself, I ran a btrfschk which fixed some incorrect data. But without success. Finally I has to format the partition to make it work again.

**Comment by thaJeztah** [comment] 2015-04-08 16:04
@Soulou thanks for reporting back; I'll close this issue because there's probably no way to reproduce it now. Feel free to "ping" me if you encounter this problem again. Thanks!

**Closed** 2015-04-08 16:05 UTC

**Comment by Soulou** [comment] 2015-12-21 10:05
It seems to happen when the partition get full.

The file /var/lib/docker/repositories-btrfs get truncated.

Then Docker tries to read its content without success because it's not a valid JSON file anymore (it's empty) There are two ways to fix that.

* If the docker daemon is stopped: Write `{}` in the file, then your daemon will start correctly but you will have lost all the repositories/tag of your images.

* If the docker daemon is running: Use the following gist to restore the `repositories-btrfs` file: https://gist.github.com/Soulou/ab3d8ff1c26312d7bc91

**Comment by thaJeztah** [comment] 2015-12-21 10:11
@Soulou hm, yes, I think there are existing issues around better handling of "running out of disk space", don't have them at hand, but you can search for them :smile:

**Comment by cheesang** [comment] 2016-04-13 08:23
i use the go file from https://gist.github.com/Soulou/ab3d8ff1c26312d7bc91 and executed then
sudo vi /var/lib/docker/repositories-btrfs and place in the json content but still facing EOF issue.

questions:
1) the steps i did correct?
2) should i restart docker service after above steps?

afraid after restart all my containers and images gone. how to fix if that happen?
