### ISSUE TITLE
kernel: auplink segmentation fault

### ISSUE THREAD

**Issue by itsafire** [docker/docker#10595] opened 2015-02-05 17:55 UTC
I'm getting segmentation faults while building docker images. I suspect this to happen, when building in parallel.

Feb  3 10:09:47 debian kernel: [ 6638.841106] auplink[87016]: segfault at 7fff826e0198 ip 00007f2c91285a16 sp 00007fff826e01a0 error 6 in libc-2.13.so[7f2c911b3000+182000]
Feb  3 10:14:08 debian kernel: [ 6899.660189] auplink[88007]: segfault at 7fff1bd66a38 ip 00007f12a6eb5a16 sp 00007fff1bd66a40 error 6 in libc-2.13.so[7f12a6de3000+182000]
Feb  5 18:37:05 debian kernel: [95481.670375] auplink[8927]: segfault at 7fff233365f8 ip 00007f926c277a16 sp 00007fff23336600 error 6 in libc-2.13.so[7f926c1a5000+182000]
Feb  5 18:38:31 debian kernel: [95566.662136] auplink[10082]: segfault at 7fffe00d22e8 ip 00007f200ace2a16 sp 00007fffe00d22f0 error 6 in libc-2.13.so[7f200ac10000+182000]

uname -a
Linux debian 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt2-1~bpo70+1 (2014-12-08) x86_64 GNU/Linux

df -h
root@debian:/home/andreas# df -h
Filesystem                                              Size  Used Avail Use% Mounted on
rootfs                                                   19G  2.1G   16G  12% /
udev                                                     10M     0   10M   0% /dev
tmpfs                                                    99M  256K   99M   1% /run
/dev/disk/by-uuid/0728a376-0dbb-4f19-8a3e-d311a2232070   19G  2.1G   16G  12% /
tmpfs                                                   5.0M     0  5.0M   0% /run/lock
tmpfs                                                   374M     0  374M   0% /run/shm
cgroup                                                  494M     0  494M   0% /sys/fs/cgroup
/dev/disk/by-uuid/0728a376-0dbb-4f19-8a3e-d311a2232070   19G  2.1G   16G  12% /var/lib/docker/aufs

docker --version
Docker version 1.4.1, build 5bc2ff8

andreas@debian:~$ docker info
Containers: 0
Images: 10
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 10
Execution Driver: native-0.2
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 1
Total Memory: 986.8 MiB
Name: debian
ID: UCC5:UZDR:M3KU:3WGY:73I4:OQAW:DKKF:KJX2:EY5F:QCOX:EZHB:USYF
WARNING: No memory limit support
WARNING: No swap limit support

**Comment by jfrazelle** [comment] 2015-02-05 17:56
we need more information than this....

**Comment by itsafire** [comment] 2015-02-05 18:00
I wasn't finished with the comment when you closed the ticket.

**Comment by jfrazelle** [comment] 2015-02-05 18:01
Please give more information and I will reopen, as it stands now this issue is just a segfault with no details.

**Comment by jfrazelle** [comment] 2015-02-05 18:05
Thank you, sorry if this seemed blunt, if you look through the issue history you will see people have opened issues in the past with empty comments either by mistake or to troll. Thanks for providing the relevant information.

**Comment by jfrazelle** [comment] 2015-02-05 18:07
I think the first thing to try since this seems to be a kernel level issue would be to curl and run this shell script https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh It will check your kernel config to make sure all the necessary configurations are in place.

**Comment by itsafire** [comment] 2015-02-05 18:08
I'm running docker inside a vmware fusion 7.1. 

Testscript output:

root@debian:/home/andreas# bash test.sh
warning: /proc/config.gz does not exist, searching other paths for kernel config...
info: reading kernel config from /boot/config-3.16.0-0.bpo.4-amd64 ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_MACVLAN: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_NF_NAT_IPV4: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_CGROUP_PERF: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled
    - CONFIG_EXT4_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: missing

**Comment by phemmer** [comment] 2015-02-05 18:17
Why do we think this is a kernel issue? Whatever `auplink` is, it's a userspace application, not in the kernel. The kernel is simply the one logging the message.

**Comment by thaJeztah** [comment] 2015-02-05 18:50
@phemmer I did a quick Google on auplink; and it seems to be part of AUFS.

This comment; https://github.com/docker/docker/issues/915#issuecomment-19803326 seems to indicate it's used (by docker?) to allow hard-links between layers. 

I haven't looked deeply into it though, not my expertise as well, LOL

**Comment by thaJeztah** [comment] 2015-02-05 18:55
Ok, it's part of `aufs-tools` and a requirement to use aufs in docker; https://github.com/docker/docker/issues/4946#issuecomment-39230292

I'll stop further now, because I'm probably just making noise here :)

**Comment by estesp** [comment] 2015-02-05 20:34
Do you have a repro scenario?  You mention building "parallel"? What does that mean?

And why does it scare me that the same disk appears mounted as `/` and as `/var/lib/docker/aufs` in your `df -h` output?

Finally, what is the physical disk that your Fusion VM is located on (e.g. could it be an external HDD over USB?) and do you have any strange driver setup for your debian VM? (I don't know Fusion that well, but other hypervisor platforms sometimes have "faster" but experimental driver settings on the VM disk)

**Comment by itsafire** [comment] 2015-02-06 09:50
I am using a docker build tool which uses python doit. doit -n4  <target> will start 4 builds in parallel. But if  this parallel building is causing the segfauls is only speculation on my side. 

For the mount entry you mentioned: I did a clean debian wheezy + docker install. I did not touch /etc/fstab. I'm not familiar with aufs.

The VM ist running on an internal SSD. The VM is running with open-vm-tools provided by debian wheezy.

My Host is a Macbook Pro which runs sans flaws. I have other VMs running on that host which also expose no faults whatsoever. I trust my host system.

**Comment by itsafire** [comment] 2015-02-06 10:11
The last non parallel build spilled lots of segfaults. I purged docker and "rm -rf /var/lib/docker", re-installed docker, still I get segfaults. The underlying ext4 is fschecked ok. Next: install a clean wheezy and re-try.

**Comment by itsafire** [comment] 2015-02-06 17:15
ok.. uplink still segfaults.

**Comment by itsafire** [comment] 2015-02-08 13:46
On latest debian jessie:

debian docker[8349]: time="2015-02-08T14:43:19+01:00" level="error" msg="[warning]: couldn't run auplink before unmount: signal: segmentation fault"
Feb  8 14:43:19 debian kernel: [ 1227.245003] auplink[41852]: segfault at 7fffe6933058 ip 00007f02d86ca479 sp 00007fffe6933060 error 6 in libc-2.19.so[7f02d85ef000+19f000]

**Comment by itsafire** [comment] 2015-02-09 09:19
This is a bug in aufs-tools. Even this erroneous command will segfault.

    # auplink / flush
    auplink:plink.c:341: no aufs mount point
    Segmentation fault

**Comment by estesp** [comment] 2015-02-09 13:44
So, sounds like this is something to report as a debian bug?  Doesn't sound like anything the Docker community can help with unless there are some `aufs-tools` experts around.

**Comment by itsafire** [comment] 2015-02-09 13:52
Yes. Please close the issue.

**Comment by edwintorok** [comment] 2015-02-09 21:20
Just noticed these crashes in my dmesg on jessie, and opened a bugreport here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=777559

**Comment by crosbymichael** [comment] 2015-02-23 20:05
@itsafire @edwintorok thanks for reporting the issue here and also opening one for debian.  I'll close this on docker and we can track any progress on the debian issue for the aufs-tools

**Closed by crosbymichael** 2015-02-23 20:05 UTC

**Comment by lgierth** [comment] 2015-10-13 00:05
@edwintorok did the patch which was provided in the Debian bugtracker go anywhere? It doesn't look like it -- I'm also getting bitten by this.

**Comment by edwintorok** [comment] 2015-10-13 07:07
@lgierth for me the crashes went away when upgrading the Debian kernel to `jessie-backports` which doesn't have AUFS support anymore. AUFS support is present only in the `jessie` kernel, and I'm not sure if that'll get updated given that `docker.io` itself is only part of `jessie-backports` and not `jessie` itself ...

**Comment by wyaeld** [comment] 2015-12-05 23:26
That doesn't solve the problem of it happening in Ubuntu Trusty/Vivid etc kernels.  The only version of aufs-tools seems to be the 2013 one, and no-one appears to be maintaining.  The patch [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=777559) didn't go anywhere

**Comment by ra2637** [comment] 2016-04-26 03:20
Prove comment of @wyaeld. Got the same issue in Ubuntu Wily.

**Comment by hxw** [comment] 2016-04-26 05:54
There is also a bug filed on ubuntu https://bugs.launchpad.net/ubuntu/+source/aufs-tools/+bug/1442568 wher I added a comment containing a fix for `au_util.h` which I will ad here:

I looked at aufs_utils, and it look like the problem is with the AUFin macro (au_util.h)which is
```
#define AuFin(fmt, ...) \
        error_at_line(errno, errno, __FILE__, __LINE__, fmt, ##__VA_ARGS__)
```
I think this should be:
```
#define AuFin(fmt, ...) \
        error_at_line(1, errno, __FILE__, __LINE__, fmt, ##__VA_ARGS__)
```
The value 1 for the status parameter would always ensure program termination rather than the
current situation where it will continue (if errno == 0) and proceed to segfault or some other crash.

**Comment by ra2637** [comment] 2016-04-26 10:21
I found one interesting thing, if you kill PID 1 or stop in the container, you will get the same error like this:
```
Apr 26 10:08:55 docker-1 docker[4260]: time="2016-04-26T10:08:55.220632762Z" level=error 
msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt 
/26b5b4106ffb65efadf867c8bd8d491b8d575163de00b84eea9d3c2be27179f6: signal:  
segmentation fault (core dumped)"
Apr 26 10:08:55 docker-1 kernel: auplink[21519]: segfault at 7ffe8cb08c98 ip 
00007fe9ed290709 sp 00007ffe8cb08ca0 error 6 in libc-2.21.so[7fe9ed197000+1c0000]
```
This is pretty confusing because it might be failed from the command append to starting the container but not the auplink's problem.

**Comment by ChipmunkV** [comment] 2017-08-30 09:16
I've taken `aufs-tools` 1:4.1+20161219-1 deb (currently in sid: https://packages.debian.org/sid/aufs-tools) and installed it on Ubuntu 16.04. It has fixed some kind of `auplink` crash that was occurring during the `docker build`.

**Comment by scottstensland** [comment] 2017-09-20 20:44
this error is still happening using latest docker  

```
apt-cache policy docker-engine
docker-engine:
  Installed: 17.05.0~ce~rc3-0~ubuntu-zesty
  Candidate: 17.05.0~ce~rc3-0~ubuntu-zesty
  Version table:
 *** 17.05.0~ce~rc3-0~ubuntu-zesty 100
        100 /var/lib/dpkg/status
```

on latest Ubuntu laptop  

```
 uname -m && uname -r && cat /etc/os-release
x86_64
4.13.0-11-generic
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Artful Aardvark (development branch)"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

```

which is using default aufs-tools

```
apt-cache policy aufs-tools
aufs-tools:
  Installed: 1:3.2+20130722-1.1ubuntu1
  Candidate: 1:3.2+20130722-1.1ubuntu1

```

```
dmesg
...
[73677.129969] auplink[978]: segfault at 7ffdfc350738 ip 00007fccee59c638 sp 00007ffdfc350740 error 6 in libc-2.26.so[7fccee496000+1d6000]
[73677.269197] aufs au_plink_put:434:dockerd[3006]: pseudo-link is not flushed
[73679.825490] auplink[1025]: segfault at 7ffdf6d41d78 ip 00007f6b18cef638 sp 00007ffdf6d41d80 error 6 in libc-2.26.so[7f6b18be9000+1d6000]
[73682.861152] docker0: port 1(veth71269f0) entered blocking state

```

**Comment by almiroshnich** [comment] 2017-12-28 10:58
@ChipmunkV [thank you!](https://github.com/moby/moby/issues/10595#issuecomment-325933070)
```
sudo apt-get purge -y aufs-tools
TEMP_DEB="$(mktemp)" && wget -O "$TEMP_DEB" 'http://http.us.debian.org/debian/pool/main/a/aufs-tools/aufs-tools_4.9+20170918-1_amd64.deb'
sudo dpkg -i "$TEMP_DEB" && rm -f "$TEMP_DEB"
```
^ this helped me to get rid of `segmentation fault`s errors (Ubuntu 16.04 / docker-ce 17.06.2)

**Comment by rboy1** [comment] 2019-01-15 21:07
Thanks @almiroshnich 
The above package is no longer available, the new link to the package and commands for Ubuntu 16.04 is
```
sudo apt-get purge -y aufs-tools
TEMP_DEB="$(mktemp)" && wget -O "$TEMP_DEB" 'http://http.us.debian.org/debian/pool/main/a/aufs-tools/aufs-tools_4.9+20170918-2_amd64.deb'
sudo dpkg -i "$TEMP_DEB" && rm -f "$TEMP_DEB"
```
