### ISSUE TITLE
[1.12.0-rc] some weird deadlocks

### ISSUE THREAD

**Issue by tiborvass** [docker/docker#25100] opened 2016-07-27 00:31 UTC
https://jenkins.dockerproject.org/job/Docker%20Master/label=ubuntu%20&&%20btrfs/6275/console
https://jenkins.dockerproject.org/job/Docker%20Master/label=fedora%20&&%20devicemapper/6275/console
https://jenkins.dockerproject.org/job/Docker%20Master/label=fedora%20&&%20devicemapper/6274/console

**Comment by vdemeester** [comment] 2016-07-27 09:51
@tiborvass this is kinda related to #25028 too

**Comment by dnephin** [comment] 2016-07-27 15:12
Ya, closing as duplicate of #25028

**Closed by dnephin** 2016-07-27 15:12 UTC
Labels: priority/P1
