### ISSUE TITLE
Cannot install docker-engine-1.7.0-0.1.el6.x86_64.rpm on RHEL 6.6

### ISSUE THREAD

**Issue by petejcullen** [docker/docker#14250] opened 2015-06-29 12:45 UTC
The RPM for the x86_64 RHEL 6.6 version of docker (docker-engine-1.7.0-0.1.el6.x86_64.rpm) does not appear to have been packaged correctly, as it is not recognised by yum.

$ sudo yum localinstall --nogpgcheck docker-engine-1.7.0-0.1.el6.x86_64.rpm
Loaded plugins: product-id, refresh-packagekit, rhnplugin, security, subscription-manager
This system is receiving updates from RHN Classic or RHN Satellite.
Setting up Local Package Process
Cannot open: docker-engine-1.7.0-0.1.el6.x86_64.rpm. Skipping.
Nothing to do

$ cat /etc/*release*
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
cat: /etc/lsb-release.d: Is a directory
Red Hat Enterprise Linux Server release 6.6 (Santiago)
Red Hat Enterprise Linux Server release 6.6 (Santiago)
cpe:/o:redhat:enterprise_linux:6server:ga:server
[peterc@kingeric ~]$ uname -a
Linux kingeric 2.6.32-504.8.1.el6.x86_64 #1 SMP Fri Dec 19 12:09:25 EST 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jasonamyers** [comment] 2015-06-29 13:30
same issue here RHEL 7

**Comment by jasonamyers** [comment] 2015-06-29 13:39
that url is actually 404ing and that's why it can't read it

**Comment by jasonamyers** [comment] 2015-06-29 13:52
It's working now.

**Comment by fjoseph1313** [comment] 2015-06-29 14:51
I have the same issue, my linux kernel is 2.6.32-504.16.2.el6.x86_64 i hope docker can work with this version

**Comment by hansloven** [comment] 2015-06-29 17:55
Same exact problem as Pete.

**BUG REPORT INFORMATION**

**docker version:**
    n/a - docker does not install
**docker info:**
    n/a - docker does not install
**uname -a:**
    Linux iamcdcdvap510 2.6.32-504.23.4.el6.x86_64 #1 SMP Fri May 29 10:16:43 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**additional environment details (AWS, VirtualBox, physical, etc.):**
    RHEL 6.6 on a VM, but I'm not the lab manager... probably run on whatever the official RedHat virtualization product is

**List the steps to reproduce the issue:**

just follow the instructions on https://docs.docker.com/installation/rhel/

1.    Log into your machine as a user with sudo or root privileges.

2.    Download the Docker RPM to the current directory.
$ curl -O -sSL http://get.docker.com/docker/1.7.0/rpms/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.1.el6.x86_64.rpm

3.    Use yum to install the package.
$ sudo yum localinstall --nogpgcheck docker-engine-1.7.0-0.1.el6.x86_64.rpm

**Describe the results you received:**
Cannot open: ./docker-engine-1.7.0-0.1.el6.x86_64.rpm. Skipping.
Nothing to do

**Describe the results you expected:**
package should have installed

**Provide additional info you think is important:**
n/a
**----------END REPORT ---------**

**Comment by hansloven** [comment] 2015-06-30 13:25
...and on a related note -- since the 1.7 rpm is broken, and I'm looking for alternatives here...  Why is it that all of the fedora/rhel repositories seem to have only Docker 1.5??  Was Docker 1.6 scrapped/'overwritten' by 1.7??

**Comment by hansloven** [comment] 2015-06-30 16:10
And now it works :smile_cat: 
Has the RPM been updated since this morning?  I cannot be certain since I scrapped the one that did not work, but that is what I suspect.

**Comment by dave-miles** [comment] 2015-06-30 22:29
Not for me :sob:

The download results in an image file (which I assume matches the one I see when I visit https://get.docker.com/docker/1.7.0/rpms/centos-6/RPMS/x86_64/):

```
[root@ovirt Downloads]# curl -O -sSL http://get.docker.com/docker/1.7.0/rpms/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.1.el6.x86_64.rpm
[root@ovirt Downloads]# file docker-engine-1.7.0-0.1.el6.x86_64.rpm
docker-engine-1.7.0-0.1.el6.x86_64.rpm: JPEG image data, JFIF standard 1.01
```
Re-download with verbose reporting shows why:
```
[root@ovirt Downloads]# curl -O -vvvSL http://get.docker.com/docker/1.7.0/rpms/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.1.el6.x86_64.rpm
* About to connect() to get.docker.com port 80 (#0)
*   Trying 162.242.195.82... connected
* Connected to get.docker.com (162.242.195.82) port 80 (#0)
> GET /docker/1.7.0/rpms/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.1.el6.x86_64.rpm HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: get.docker.com
> Accept: */*
> 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< HTTP/1.1 301 Moved Permanently
< Content-length: 0
< Location: https://get.docker.com/docker/1.7.0/rpms/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.1.el6.x86_64.rpm
< Connection: close
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Closing connection #0
* Issue another request to this URL: 'https://get.docker.com/docker/1.7.0/rpms/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.1.el6.x86_64.rpm'
* About to connect() to get.docker.com port 443 (#0)
*   Trying 162.242.195.82... connected
* Connected to get.docker.com (162.242.195.82) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_DHE_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
* 	subject: CN=*.docker.com,OU=Domain Control Validated - RapidSSL(R),OU=See www.rapidssl.com/resources/cps (c)13,OU=GT68254618
* 	start date: Oct 29 21:14:42 2014 GMT
* 	expire date: Nov 13 14:19:33 2017 GMT
* 	common name: *.docker.com
* 	issuer: CN=RapidSSL SHA256 CA - G3,O=GeoTrust Inc.,C=US
> GET /docker/1.7.0/rpms/centos-6/RPMS/x86_64/docker-engine-1.7.0-0.1.el6.x86_64.rpm HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: get.docker.com
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Server: nginx/1.6.2
< Date: Tue, 30 Jun 2015 22:28:28 GMT
< Content-Type: image/jpeg
< Content-Length: 76963
< Connection: close
< Last-Modified: Wed, 10 Sep 2014 20:23:00 GMT
< ETag: "6a4ed3c0b45f43636a8f2f5472aa1fa9"
< x-amz-error-code: AccessDenied
< x-amz-error-message: Access Denied
< x-amz-request-id: 16558A8B4E784690
< x-amz-id-2: hRzFnMRkrOU0/PieIk1Z606qWLLUBcL+OY+Zw3ud8SzhuNm9VQHDRkU41hP5/ZwvDYiNVtshuq8=
< Strict-Transport-Security: max-age=31536000
< 
{ [data not shown]
100 76963  100 76963    0     0  62382      0  0:00:01  0:00:01 --:--:--  303k* Closing connection #0
```

**Comment by hansloven** [comment] 2015-07-01 11:59
corroborated - I GET https://get.docker.com/docker/1.7.0/rpms/centos-6/RPMS/x86_64/docker-engine-1.7.0-1.el6.x86_64.rpm and am returned 403 (along with the *404* image)

**Comment by LK4D4** [comment] 2015-07-01 17:41
Looks like duplicate of #14042

**Comment by fregienj** [comment] 2015-07-02 14:33
I have the same issue with getting the image file as stated above trying to install on a virtual google cloud image -- 2.6.32-504.16.2.el6.x86_64. 

@LK4D4 How is this the same issue as #14042?  This issue is for 6.6+ and that one is for 7, and has a  completely different error.   That one actually recognizes the rpm and tries to resolve dependencies.  That is not the case with this issue.

**Comment by citostyle** [comment] 2015-07-02 14:55
@LK4D4 Agree with @fregienj here, not a duplicate. The file is just not available at that URL :/

Is there maybe a mirror for the docker-engine-1.7.0-1.el6.x86_64.rpm? Or can anyone who was able to download it share it somewhere? /cc @jasonamyers @hansloven

**Comment by LK4D4** [comment] 2015-07-02 17:27
Okay, I'm reopening.

**Comment by tom-canova** [comment] 2015-07-02 18:46
try this URL
https://get.docker.com/rpm/1.7.0/centos-6/RPMS/x86_64/docker-engine-1.7.0-1.el6.x86_64.rpm

**Comment by fregienj** [comment] 2015-07-02 18:51
that URL worked for me.  thanks!

**Comment by tom-canova** [comment] 2015-07-02 19:23
btw - After I pulled it down, I discovered there are issues with docker 1.7.0 on RHEL 6.6 
See https://github.com/docker/docker/issues/14024
You may want track the release candidate for 1.7.1 which should be out soon, purportedly with a fix for RHEL 6.6
https://github.com/docker/docker/pull/14264

**Comment by jfrazelle** [comment] 2015-07-10 21:47
ok this seems to be resolved

**Closed by jfrazelle** 2015-07-10 21:47 UTC

**Comment by mansurali901** [comment] 2016-07-14 11:09
I would suggest for longer term to upgrade the kernel to 3.1x.

Here what i have done to get kernel 3.1x on my CentOS Box.
[root@ruta ~]# uname -a
Linux ruta.etilizepak.com 2.6.18-371.4.1.el5.centos.plus #1 SMP Thu Jan 30 06:16:27 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
You have new mail in /var/spool/mail/root

[root@ruta ~]# yum install -y centos-release-xen

[root@ruta ~]# echo includepkgs=kernel kernel-firmware >> /etc/yum.repos.d/CentOS-Xen.repo
[root@ruta ~]# yum update -y kernel
[root@ruta ~]# reboot
[root@ruta ~]# yum install -y https://get.docker.com/rpm/1.7.0/centos-6/RPMS/x86_64/docker-engine-1.7.0-1.el6.x86_64.rpm
[root@ruta ~]# service docker start

Docker worked fine – I gave it a solid run-through using this slick kubernetes-in-containers walkthrough and it performed as expected.

**Comment by hansloven** [comment] 2016-07-14 11:21
Well, sure... if you're free to do so.  Some customers, however, may be
unwilling to upgrade from RHEL 6.x to RHEL 7.x -- particularly, since the
administration is very different, and investment in sys admin training
isn't an easy sell.

Pardon the brevity,
