### ISSUE TITLE
docker 1.12 change container dns config 

### ISSUE THREAD

**Issue by tiny1990** [docker/docker#25576] opened 2016-08-10 17:40 UTC
my env is :
mesos-1.0.0 +marathon-1.1.1  + mesos-dns + calico

I post json to run a container ,by my container dns is

search cn-north-1.compute.internal 31.1.128
nameserver 127.0.0.11
options ndots:0

json:
`
{
  "id": "zookeeper-1",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "debezium/zookeeper:0.2",
      "parameters": [
          {"key": "net", "value": "datapipeline"}
      ]
    },
     "privileged": true
  },
  "instances": 1,
  "cpus": 1,
  "mem": 500,
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "env": {
    "LOG_LEVEL": "WARN"
  }
}
`
I change my local but not work

**Comment by sanimej** [comment] 2016-08-10 17:50
@tiny1990 127.0.0.11 is the address of Docker embedded DNS server. From 1.10 for user defined networks service discovery is provided through the embedded DNS server. Your external DNS servers (from host's `/etc/resolv.conf` or `--dns` config) will be maintained by the DNS server and queries that can't be resolved by the embedded DNS server will be forwarded to the external servers.

**Comment by cpuguy83** [comment] 2016-08-10 19:37
@tiny1990 Thanks for the report, closing since this is expected behavior that should not be breaking your existing tooling unless of course you are relying on the values in /etc/resolv.conf.

**Closed by cpuguy83** 2016-08-10 19:37 UTC

**Comment by tiny1990** [comment] 2016-08-11 00:29
@cpuguy83 thinks for ur reply ,but I change /etc/resolv.conf , it's not work, if I change network "BRIDGE" is ok
