### ISSUE TITLE
Container command '/src/local/scripts/php-fpm.sh' not found or does not exist.

### ISSUE THREAD

**Issue by sandipsclarion** [docker/docker#24438] opened 2016-07-08 05:07 UTC
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
 v0.12.0-beta1 on Windows 8.1 Eternprise*
64 Bit 
DockerToolbox-1.11.2

Have you previously installed Kalabox? If so, what version?

Yes, I've installed kalabox-v0.12.0-beta.1*

**Tell us about your bug**

I am trying to use docker project with kalabox.
my docker repo structure is as per screenshot
![codeace-folder-structure](https://cloud.githubusercontent.com/assets/16461960/16677834/6c0e88ba-448e-11e6-905a-3dd51bb4baa7.png)

**when i enter to api directory and run the command kbox start, some process is working, but after some time it shows me an error as per below**

![kbox-start-codeace](https://cloud.githubusercontent.com/assets/16461960/16677852/9283fb56-448e-11e6-9f6e-f34bb43b30da.png)

![codeace-error](https://cloud.githubusercontent.com/assets/16461960/16677855/9836191c-448e-11e6-9d0b-10f0684ab1a5.png)

**i have mention this path in kalabox-compose-override.yml file as per below**

![kalabox-compose-codeace](https://cloud.githubusercontent.com/assets/16461960/16677873/b08367b8-448e-11e6-9e98-879ca44ce4f0.png)

**as per the screen shot there is file is exist but why this is error coming.Please help me.
I stuck here from 1 week.**

**Comment by thaJeztah** [comment] 2016-07-08 05:46
I have no experience with "kalabox", so don't know how it works (I see you created an issue in that issue tracker as well https://github.com/kalabox/kalabox/issues/1437)

Could you check if the `php-fpm.sh` uses Linux line endings (CR), not Windows line endings (CRLF)? If it has Windows line endings, that may be the cause; Linux doesn't handle that for shell-scripts, and will give this message

**Comment by thaJeztah** [comment] 2016-07-18 14:09
We merged a change for docker 1.12 that returns a better error message, instead of masking it as "command not found"; https://github.com/docker/docker/pull/22983/files#diff-3cb140026df40998ea29c5bcb6bb292eR150

I'm closing this issue, because the error message should be more descriptive in 1.12, but if you're able to the 1.12 release candidate a spin to verify, that would be great http://github.com/docker/docker/releases

**Closed by thaJeztah** 2016-07-18 14:09 UTC
Labels: status/more-info-needed
