### ISSUE TITLE
Docker volumes not mounting on osx?

### ISSUE THREAD

**Issue by jedahan** [docker/docker#18284] opened 2015-11-27 21:49 UTC
So, I am using this Makefile https://gist.github.com/f88f2ad844a13e3e3577 , and it looks like the volume is mounted, but no files are inside $(TMP). Is there something I am missing regarding `run -v` on osx?

**Comment by thaJeztah** [comment] 2015-11-28 09:16
This is because (by default) only the `/Users` directory on the host (OS X) is shared with the boot2docker virtual machine that the docker daemon runs in. Either make sure the "tmp" directory is in a subdirectory of `/Users`, or mount the directory inside the virtual machine.

For reference, see https://github.com/boot2docker/boot2docker#virtualbox-guest-additions

Hope this helps! I'm going to close this issue, because this is not a bug, but feel free to comment here after I've closed :+1:

**Closed by thaJeztah** 2015-11-28 09:16 UTC

**Comment by jedahan** [comment] 2015-11-29 06:28
Yeah I worked around this by doing a little scp dance, took a while for me to figure out. Not sure if it makes sense to have more proactive documentation on using docker on osx ...

**Comment by thaJeztah** [comment] 2015-11-29 11:17
@jedahan we're open to suggestions; the Markdown files used to generate the documentation can be found in this repository, for example, the Mac install guide is here; https://github.com/docker/docker/blob/master/docs/installation/mac.md, and for docker-machine (which sets up the Virtual Machine), here: https://github.com/docker/machine/tree/master/docs

Good to hear you got it working!
