### ISSUE TITLE
No Option to Specify Name/Tag in Dockerfile, we have to pass it in Cli only

### ISSUE THREAD

**Issue by codevulture** [docker/docker#26131] opened 2016-08-30 06:07 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 19
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.8 GiB
Name: janonymous
ID: MOM4:ICMJ:RC7F:MJPI:K35I:64VL:2CD6:LADA:2B6E:FLCQ:QAAK:JB46
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 32
 System Time: 2016-08-30T11:25:25.255022521+05:30
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine

**Steps to reproduce the issue:**
1.   Make a Dockerfile
2.   docker build .

**Describe the results you received:**
Make a docker file:
_Dockerfile_
FROM alpine:3.3
MAINTAINER Jaivish
WORKDIR /
RUN apk add --no-cache \
        bash

CMD ["ls"]

_Commads_:
$ docker build .
Sending build context to Docker daemon 8.704 kB
Step 1 : FROM alpine:3.3
 ---> 47cf20d8c26c
Step 2 : MAINTAINER Jaivish
 ---> Running in afc90b4e39bd
 ---> 4d0a4153ef49
Removing intermediate container afc90b4e39bd
Step 3 : WORKDIR /
 ---> Running in 094fb47c755c
 ---> 8dc7c8d84681
Removing intermediate container 094fb47c755c
Step 4 : RUN apk add --no-cache         bash
 ---> Running in 9965699efe14
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/5) Installing ncurses-terminfo-base (6.0-r6)
(2/5) Installing ncurses-terminfo (6.0-r6)
(3/5) Installing ncurses-libs (6.0-r6)
(4/5) Installing readline (6.3.008-r4)
(5/5) Installing bash (4.3.42-r3)
Executing bash-4.3.42-r3.post-install
Executing busybox-1.24.2-r0.trigger
OK: 13 MiB in 16 packages
 ---> c3cbb0a8fe7a
Removing intermediate container 9965699efe14
Step 5 : CMD ls
 ---> Running in 3daea69b0ae0
 ---> 7afa38ea3317
Removing intermediate container 3daea69b0ae0
Successfully built 7afa38ea3317

**_Output_**
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              7afa38ea3317        2 minutes ago       8.239 MB
<none>              <none>              85f0fa9f1190        28 minutes ago      158.7 MB
ubuntu              latest              f8d79ba03c00        2 weeks ago         126.4 MB
alpine              3.3                 47cf20d8c26c        9 weeks ago         4.797 MB
hello-world         latest              94df4f0ce8a4        4 months ago        967 B
larsks/thttpd       latest              a31ab5050b67        20 months ago       1.058 MB

**Describe the results you expected:**
Instead of REPOSITORY+TAG getting none there should be an option to specify it within dockerfile itself if command line arguments are not passed.

**Additional information you deem important (e.g. issue happens only occasionally):**
**If someone can confirm that this issue is valid i would like to solve this.**

**Comment by thaJeztah** [comment] 2016-09-27 10:36
This is a duplicate of https://github.com/docker/docker/issues/5603, and https://github.com/docker/docker/pull/886, and adding this option has been rejected (see https://github.com/docker/docker/issues/5603#issuecomment-115434824, and https://github.com/docker/docker/pull/886#issuecomment-21167265).

As explained there, this could open up the possibility of a Dockerfile overwriting existing images, without the user knowing. The person _performing_ the build should stay in control over the naming of the produced image.

For CI, it should be really easy to automate setting an image/tag (see, for example; https://github.com/docker/docker/blob/v1.12.1/Makefile#L42-L44), so I don't see a compelling reason to implement this.

I'm going to close this issue, but thanks for suggesting, and feel free to comment after I closed

**Closed by thaJeztah** 2016-09-27 10:36 UTC
Labels: area/builder, kind/feature, version/1.11
