### ISSUE TITLE
[1.12.0-rc3 docker for mac] overlay network with jwilder/nginx-proxy

### ISSUE THREAD

**Issue by llitfkitfk** [docker/docker#24440] opened 2016-07-08 07:37 UTC
```
$ docker swarm init
$ docker network create -d overlay overlaynet
$ docker service create --replicas 1 --name whoami  --network overlaynet -e VIRTUAL_HOST=whoami.localhost  emilevauge/whoami 
$ docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro --name nginx jwilder/nginx-proxy
$ docker network connect overlaynet nginx
```
But, cannot access  http://whoami.localhost (504 Gateway Time-out)

**Comment by cpuguy83** [comment] 2016-07-08 13:33
Can you provide more details? Reproducible steps with simpler images? Why would you be able to access this hostname?

**Comment by llitfkitfk** [comment] 2016-07-08 17:01
@cpuguy83 

```
$ docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro --name nginx jwilder/nginx-proxy
$ docker run --name whoami   -e VIRTUAL_HOST=whoami.localhost  emilevauge/whoami 
```
open browser,  http://whoami.localhost can get whoami container info

but when using overlay network, http://whoami.localhost cannot access( finally, will get 504 Gateway Time-out)

**Comment by thaJeztah** [comment] 2016-07-09 00:41
I suspect this is a duplicate of https://github.com/docker/docker/issues/24362; containers started with `docker run` cannot join a "swarm-scoped" network

In this case, I think it would make sense to deploy nginx-proxy as a service; that way you can also deploy a proxy on each node. The syntax for bind-mounting `/var/run/docker.sock` on a service is a bit different though (using the `--mount` option)

**Comment by mavenugo** [comment] 2016-07-09 01:39
This is a dupe of https://github.com/docker/docker/issues/23901 and my response (https://github.com/docker/docker/issues/23901#issuecomment-231335297) is applicable here as well

**Comment by thaJeztah** [comment] 2016-07-09 04:24
Thanks @mavenugo, let's close this one

Thanks for reporting @llitfkitfk

**Closed by thaJeztah** 2016-07-09 04:24 UTC

**Comment by llitfkitfk** [comment] 2016-07-09 04:53
@thaJeztah @mavenugo Thanks

**Comment by llitfkitfk** [comment] 2016-07-09 05:56
```
$ docker network create -d overlay overlaynet
$ docker service create --mount target=/tmp/docker.sock,source=/var/run/docker.sock,type=bind --name nginx -p 80:80 --network overlaynet jwilder/nginx-proxy
$ docker service create --replicas 1 --name whoami  --network overlaynet -e VIRTUAL_HOST=whoami.localhost  emilevauge/whoami
```
access http://whoami.localhost :502 Bad GateWay

**Comment by llitfkitfk** [comment] 2016-07-09 06:53
It works, after I restart nginx container
