### ISSUE TITLE
docker container filesystem became `read-only` after running 5 months

### ISSUE THREAD

**Issue by chengweiv5** [docker/docker#18010] opened 2015-11-16 12:18 UTC
BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version

```
# docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.2.2
Git commit (client): a43e801
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.2.2
Git commit (server): a43e801
```

docker info

```
# docker info
Containers: 1
Images: 76
Storage Driver: devicemapper
 Pool Name: docker-252:16-524291-pool
 Pool Blocksize: 65.54 kB
 Data file: /data/docker/devicemapper/devicemapper/data
 Metadata file: /data/docker/devicemapper/devicemapper/metadata
 Data Space Used: 7.292 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 6.828 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-431.el6.x86_64
Operating System: <unknown>
```

uname -a

```
# uname -a
Linux localhost 2.6.32-431.el6.x86_64 #1 SMP Fri Mar 14 11:51:38 CST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Provide additional environment details (AWS, VirtualBox, physical, etc.): KVM

List the steps to reproduce the issue:
1. start a container with below command

```
# docker run -d --name graphite --net=host -v /data/graphite/storage:/data/graphite/storage local-registry/chengweiv5/graphite:0.2-dev-2da77a3
```

2. wait for 5 months

Describe the results you received: the container `/` filesystem became Read-only

Describe the results you expected: the container `/' filesystem is still Read-write

Provide additional info you think is important:

I have a graphite container started 5 months ago and I suddenly it doesn't work anymore because the host data partition is full which I mounted to docker container.

From the graphite log, it says below:

~~~
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 101, in get_response
    request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 252, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 158, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 164, in _get_callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 124, in wrapper
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 91, in get_callable
    lookup_view = getattr(import_module(mod_name), func_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/browser/views.py", line 20, in <module>
    from graphite.util import getProfile, getProfileByUsername, defaultUser, json
  File "/opt/graphite/webapp/graphite/util.py", line 31, in <module>
    from graphite.logger import log
  File "/opt/graphite/webapp/graphite/logger.py", line 75, in <module>
    log = GraphiteLogger() # import-shared logger instance
  File "/opt/graphite/webapp/graphite/logger.py", line 40, in __init__
    self.infoHandler = Rotater(self.infoLogFile,when="midnight",backupCount=1)
  File "/usr/lib/python2.7/logging/handlers.py", line 171, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 30] Read-only file system: '/var/log/graphite/info.log'
~~~

it's quite interesting because I didn't mount any thing as RO to /var or its subdirectory.

So I'm trying to create a file in `/` of the container

```
# docker exec -it graphite /bin/touch /file
/bin/touch: cannot touch '/file': Read-only file system
```

below are more details.

```
# docker ps
CONTAINER ID        IMAGE                                                                COMMAND             CREATED             STATUS              PORTS               NAMES
38a6d1080f40        local-registry/chengweiv5/graphite:0.2-dev-2da77a3   "/sbin/my_init"     5 months ago        Up 5 months                             graphite            
```

I started this container with command

```
# docker run -d --name graphite --net=host -v /data/graphite/storage:/data/graphite/storage local-registry/chengweiv5/graphite:0.2-dev-2da77a3
```

It was works fine, but now has a `Read-only` root filesystem, weird!

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by chengweiv5** [comment] 2015-11-16 12:49
@GordonTheTurtle thks, updated.

**Comment by phemmer** [comment] 2015-11-16 13:34
I would check the output of `dmesg`. I think the mostly likely solution is that the filesystem somehow was corrupted, and the kernel remounted it read-only to protect it.

**Comment by chengweiv5** [comment] 2015-11-16 14:28
thanks @phemmer , I'll check it.

**Comment by crosbymichael** [comment] 2015-11-16 23:11
@phemmer ya, it looks like LVM is doing this on some type of failure

**Comment by chengweiv5** [comment] 2015-11-17 01:44
@crosbymichael is there any way to remount the rootfs as read-write again? without recreate a container?

**Comment by phemmer** [comment] 2015-11-17 01:51
I'm not sure the kernel will let you remount it read-write until you do a filesystem check/repair. And if it did, it would not be a good idea, as it stands a good chance of corrupting the filesystem further.

**Comment by ivokotev** [comment] 2015-11-17 05:27
Simple way to reproduce the issue is execution of below script. It turns read/write FS mode 
to read-only.The idea of script is to simulate mass writing of files to FS of the container (in this case it creates 50000 text files each one having 100 lines) on file system. After a while FS of the container stands read-only and script stops working. By the way similar failure is observed if you just echo some text many times (50000) on the console.

Here is script source.

#!/bin/bash 
for (( c=1; c<=5000000; c++ )) 
do 
echo "Some text $c" >> outfile$(( c / 100 )).out 
done

**Comment by ivokotev** [comment] 2015-11-20 09:32
@crosbymichael @chengweiv5 do you know for some workaround about this problem? any way to proceed further?

**Comment by geletok** [comment] 2015-11-23 09:47
Hi Guys,

I am researching docker for usage in developing of our new application. I found this issue and to me it sounds little bit disquieting. Application will have a lot IO operation and will work a lot with FS, so can I rely on the docker or I have to consider application development with this issue? 
 
Regards

**Comment by phemmer** [comment] 2015-11-23 10:07
@geletok This isn't a docker issue. It's a kernel or hardware issue.
Docker doesn't sit between your application and the kernel. All it does is set things up. Once the container is set up it steps out of the way.

If you have questions about how docker works, I'd recommend the docker-user mailing list, the forums, or IRC.

**Comment by unclejack** [comment] 2016-01-03 10:10
```
Kernel Version: 2.6.32-431.el6.x86_64
Server version: 1.3.2
```
RHEL 6.x and CentOS 6.x are unsupported. That Docker version is also extremely old and many fixes have gone into Docker since that Docker version was released.

The RHEL 6.x / CentOS 6.x kernel has also received many fixes and the issue you've experienced is most likely no longer relevant.

This issue most likely needs to be closed right away, but I'll ping @rhvgoyal so he has a chance to comment on this first.

**Comment by rhvgoyal** [comment] 2016-01-04 14:30
One possibility is that thin pool got full. In that case ext4 will remount container rootfs read only. You will have to grow the size of loop back files and restart docker and that should grow the thin pool and that should get you going again.

But as @unclejack said that docker is not supported on RHEL 6.x. So it is better to move to RHEL7 and use docker there.

**Comment by unclejack** [comment] 2016-01-04 22:35
@rhvgoyal Thank you.

Based on what @rhvgoyal, I'll close this now. 
@chengweiv5 Please do the following to fix the problem:
1. make sure to keep your system fully patched with all updates installed
2. use the latest Docker version
3. check if you've got enough free space on the devicemapper thin pool
4. if all of this fails to fix your problem, please upgrade to CentOS 7 / RHEL 7 as those are actually supported when it comes to running Docker

**Closed by unclejack** 2016-01-04 22:35 UTC
Labels: area/kernel

**Comment by dkastner** [comment] 2016-08-31 02:34
FWIW this happened for me on amazon linux 4.4.5-15.26.amzn1.x86_64 with docker 1.9.1 using the devicemapper filesystem. I had hundreds of stopped containers. Once I deleted them, new containers were able to write properly.

**Comment by trungie** [comment] 2017-09-26 01:53
FWIW also, i encountered this issue running on amazon linux elastic beanstalk with platform `64bit Amazon Linux 2017.03 v2.7.3 running Docker 17.03.1-ce`, also on devicemapper filesystem, only 1 running container and very little images. 

I think i've fixed it now but i was writing files to the container and it was using up Data space, switching to using a volume solved our issues. 

We initially thought writing to the container was ok, since all these files were ephemeral and temporary but it manifests this problem and puts the file system into read only mode when it fills up all available data space, even without the host file system filling up it's mounted partitions.

**Comment by zebehringer** [comment] 2017-09-27 12:56
I switched to volumes and so far no more issues, knock on wood. Many thanks @trungie I am also running the same AMI as you.

**Comment by mastef** [comment] 2017-11-03 07:44
Seem to be running into same issues on AWS Batch, which uses AWS ECR. Mostly thin pool + read-only errors.

For reference - since this is a top hit on Google for this issue and Amazon containers/services seem to be affected - cleaning up old images with lifecycle policies might help as well : 
https://aws.amazon.com/blogs/compute/clean-up-your-container-images-with-amazon-ecr-lifecycle-policies/
http://docs.aws.amazon.com/AmazonECR/latest/userguide/lp_creation.html

Need to see if switching to volume would work for us as well.

**Comment by papauschek** [comment] 2018-11-05 18:13
We also ran into this issue on AWS Beanstalk using Docker (`64bit Amazon Linux/2.12.4`).

It happened on two different EC2 instances within 4 days. We're now switching to mounting the working directory as volume and see if that improves things.

**Comment by matthiasha** [comment] 2019-01-02 00:47
I ran into this one when ``/var/lib/docker`` ran out of disk space.

**Comment by ggregoire** [comment] 2020-06-30 23:53
Very old topic, but I found it while investigating the issue, so sharing here the info.

FYI, AWS ElasticBeanstalk released 2 months ago a new type of Docker environment based on Amazon Linux 2, which uses OverlayFS instead of DeviceMapper: https://aws.amazon.com/blogs/compute/introducing-a-new-generation-of-aws-elastic-beanstalk-platforms

> The Docker AL2 platform is rewritten internally, but provides largely the same customer experience. It does offer improved I/O performance by using the OverlayFS storage driver. This is a change from the previous Docker platform, which used the older and slower Device Mapper storage driver and required an extra Amazon EBS volume.

The option is now visible in the console:

![Screen Shot 2020-06-30 at 6 41 33 PM](https://user-images.githubusercontent.com/591804/86187722-13847d00-bb02-11ea-9539-884c2530e442.png)

I guess OverlayFS doesn't have the same issue than DeviceMapper, so hopefully I'll fix the issue without having to mount an EBS volume.

**Comment by tubbo** [comment] 2020-10-09 18:19
I'm running Docker Desktop v2.4.0.0 (the latest, apparently) and this just happened to me when I ran out of disk space. I was using BuildKit to build my image. Freeing up more disk space did not solve the problem, but restarting the Docker VM did. Not sure what happened, but if anyone gets into this issue, it was fixed for me by freeing up a few GB of disk space and restarting Docker Desktop.

**Comment by Hammond95** [comment] 2020-12-16 10:16
Just writing here about a similar error, maybe this can help someone else.

Restarting docker solved the problem.

### Error
```
failed to register layer: Error processing tar file(exit status 1): write /home/hadoop/.pyenv/versions/anaconda3-5.1.0/pkgs/qt-5.6.2-h974d657_12/lib/pkgconfig/Qt5Xml.pc: read-only file system
```

### Env Info

`> docker info`

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: QVCA:I3TU:WQG6:SHUG:6AZO:JDRB:3DCS:KLGQ:NQ36:NFYU:VQ36:3FMK
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 45
  System Time: 2020-12-16T10:08:43.11578384Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### OS info

```
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
MacOS Catalina 10.15.3
```

**Comment by ryantupo** [comment] 2021-07-13 14:54
> Hi!
> 
> Please read this important information about creating issues.
> 
> If you are reporting a new issue, make sure that we do not have any duplicates already open. You can ensure this by searching the issue list for this repository. If there is a duplicate, please close your issue and add a comment to the existing issue instead.
> 
> If you suspect your issue is a bug, please edit your issue description to include the BUG REPORT INFORMATION shown below. If you fail to provide this information within 7 days, we cannot debug your issue and will close it. We will, however, reopen it if you later provide the information.
> 
> This is an automated, informational response.
> 
> Thank you.
> 
> For more information about reporting issues, see https://github.com/docker/docker/blob/master/CONTRIBUTING.md#reporting-other-issues
> 
> ## BUG REPORT INFORMATION
> Use the commands below to provide key information from your environment:
> 
> `docker version`:
> `docker info`:
> `uname -a`:
> 
> Provide additional environment details (AWS, VirtualBox, physical, etc.):
> 
> List the steps to reproduce the issue:
> 1.
> 2.
> 3.
> 
> Describe the results you received:
> 
> Describe the results you expected:
> 
> Provide additional info you think is important:
> 
> ----------END REPORT ---------
> 
> #ENEEDMOREINFO

if your telling someone off for repeating an issue best link to that original issue only makes sense thanks.
