### ISSUE TITLE
Build on Docker Hub fails without error message (works locally)

### ISSUE THREAD

**Issue by arabold** [docker/docker#9872] opened 2015-01-02 14:02 UTC
I've setup a new Dockerfile to create an Android build and test environment in docker. Everything works flawlessly on my local machine, but after I've pushed the repository to GitHub and created an [automated build in the Docker Hub](https://registry.hub.docker.com/u/neroinc/fedora-android/), I get an obscure _Build Error_.

Here're the build results:
https://registry.hub.docker.com/u/neroinc/fedora-android/build_id/32532/code/by8ztdthdvqo3ws8g5h9bsd/

The _Error_ status shows a very long string seemingly caused by the `unzip` command. However, I have no explanation what exactly is going wrong. Maybe an exit code or the formatting of the strings?

Finally the log concludes with `Successfully built 1c290fae4b0a`. So shouldn't the overall result be _successful_ as well?

I have solved (worked around) this by using `unzip -q` to suppress output. But I wonder if this is expected behavior? Especially as there's no _obvious_ indication that anything went wrong when running locally.

**Comment by SvenDowideit** [comment] 2015-01-05 06:09
I suspect that its just some output to stdout, but y, v odd - @kencochrane maybe you can help?

**Comment by kencochrane** [comment] 2015-01-20 15:56
@dustinlacewell has this been fixed?

**Comment by jfrazelle** [comment] 2015-01-27 17:20
Hi @arabold I sincerely hope you are not having this problem anymore. But since it is hub specific and not a bug with anything in this repo I am going to close this, but if you are still having issues please email support@docker.com and they can help!

**Closed by jfrazelle** 2015-01-27 17:20 UTC
