### ISSUE TITLE
compile docker-1.8.2 for mips64el fails on fedora 21

### ISSUE THREAD

**Issue by vanloswang** [docker/docker#21955] opened 2016-04-12 06:51 UTC
The error info is as follow:
# rpmbuild -bb docker-io.spec 
execute (%prep): /bin/sh -e /var/tmp/rpm-tmp.VrJOId
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd /root/rpmbuild/BUILD
+ rm -rf docker-cb216bee4d723fe967345a2b11a02cd7d7d2fdd5
+ /usr/bin/gzip -dc /root/rpmbuild/SOURCES/cb216bee4d723fe967345a2b11a02cd7d7d2fdd5.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd docker-cb216bee4d723fe967345a2b11a02cd7d7d2fdd5
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/git init -q
+ /usr/bin/git config user.name rpm-build
+ /usr/bin/git config user.email '<rpm-build>'
+ /usr/bin/git add .
+ /usr/bin/git commit -q -a --author 'rpm-build <rpm-build>' -m 'docker-io-1.8.2 base'
+ /usr/bin/cat /root/rpmbuild/SOURCES/libcontainer.patch
+ /usr/bin/git apply --index -
+ /usr/bin/git commit -q -m libcontainer.patch --author 'rpm-build <rpm-build>'
+ /usr/bin/cat /root/rpmbuild/SOURCES/dev.patch
+ /usr/bin/git apply --index -
+ /usr/bin/git commit -q -m dev.patch --author 'rpm-build <rpm-build>'
+ cp /root/rpmbuild/SOURCES/README.docker-logrotate .
+ sed -i 's/$/.nd7/' VERSION
+ tar zxf /root/rpmbuild/SOURCES/docker-storage-setup-6898d43.tar.gz
+ tar zxf /root/rpmbuild/SOURCES/docker-selinux-44abd21.tar.gz
+ exit 0
execute (%build): /bin/sh -e /var/tmp/rpm-tmp.Qs4kKL
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd docker-cb216bee4d723fe967345a2b11a02cd7d7d2fdd5
  mkdir -p ./_build/src/github.com/docker
++ pwd
+ ln -s /root/rpmbuild/BUILD/docker-cb216bee4d723fe967345a2b11a02cd7d7d2fdd5 ./_build/src/github.com/docker/docker
+ export DOCKER_GITCOMMIT=cb216be/1.8.2
+ DOCKER_GITCOMMIT=cb216be/1.8.2
+ export DOCKER_BUILDTAGS=selinux
+ DOCKER_BUILDTAGS=selinux
++ pwd
++ pwd
+ export GOPATH=/root/rpmbuild/BUILD/docker-cb216bee4d723fe967345a2b11a02cd7d7d2fdd5/_build:/root/rpmbuild/BUILD/docker-cb216bee4d723fe967345a2b11a02cd7d7d2fdd5/vendor:/usr/share/gocode
+ GOPATH=/root/rpmbuild/BUILD/docker-cb216bee4d723fe967345a2b11a02cd7d7d2fdd5/_build:/root/rpmbuild/BUILD/docker-cb216bee4d723fe967345a2b11a02cd7d7d2fdd5/vendor:/usr/share/gocode
+ DEBUG=1
+ hack/make.sh dynbinary
# WARNING! I don't seem to be running in the Docker container.
# The result of this command might be an incorrect build, and will not be
#   officially supported.
#
# Try this instead: make all
#
---> Making bundle: dynbinary (in bundles/1.8.2.f21/dynbinary)
_build/src/github.com/docker/docker/daemon/execdriver/native/exec.go:13:2: no buildable Go source files in /root/rpmbuild/BUILD/docker-cb216bee4d723fe967345a2b11a02cd7d7d2fdd5/vendor/src/github.com/opencontainers/runc/libcontainer/nsenter

Could some one give me some suggestion to resolve it ?

**Comment by vanloswang** [comment] 2016-04-12 07:40
I also tried the srpm golang-github-docker-libcontainer-2.1.1-0.2.gitc964368.fc21.src.rpm, it report as follow:
# rpmbuild -bb golang-github-docker-libcontainer.spec 
execute (%prep): /bin/sh -e /var/tmp/rpm-tmp.NGPcNw
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd /root/rpmbuild/BUILD
+ rm -rf libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ /usr/bin/gzip -dc /root/rpmbuild/SOURCES/libcontainer-c964368.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
execute (%build): /bin/sh -e /var/tmp/rpm-tmp.iRtJx2
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f
+ export CGO_ENABLED=1
+ CGO_ENABLED=1
+ mkdir -p ./_build/src/github.com/docker
++ pwd
+ ln -s /root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f ./_build/src/github.com/docker/libcontainer
+ mkdir bin
++ pwd
+ export GOPATH=/root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f/_build:/usr/share/gocode
+ GOPATH=/root/rpmbuild/BUILD/libcontainer-c9643688cb73c2588a9c9b14357bda6c3a9df67f/_build:/usr/share/gocode
+ gobuild -o bin/nsinit github.com/docker/libcontainer/nsinit
+ go build -o bin/nsinit github.com/docker/libcontainer/nsinit
# github.com/docker/docker/pkg/system
/usr/share/gocode/src/github.com/docker/docker/pkg/system/stat_linux.go:13: cannot use s.Rdev (type uint32) as type uint64 in field value
# github.com/docker/libcontainer/cgroups/systemd
_build/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:86: not enough arguments in call to theConn.StartTransientUnit
_build/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:101: not enough arguments in call to theConn.StopUnit
_build/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:120: not enough arguments in call to theConn.StartTransientUnit
_build/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:129: not enough arguments in call to theConn.StopUnit
_build/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go:190: not enough arguments in call to theConn.StartTransientUnit

maybe some package miss match?

**Comment by thaJeztah** [comment] 2016-04-12 09:59
Yeah, building docker on mips64 is not supported. Also, it looks you're building using source from the Red Hat / Project Atomic repository, so may be better to ask in that repository; https://github.com/projectatomic/docker/commit/cb216bee4d723fe967345a2b11a02cd7d7d2fdd5.

Any way, this is not a bug in docker, but a question on how to build docker, and the issue tracker is not for that, so I'll close this issue. You can try asking on the docker-dev Google group https://groups.google.com/forum/m/#!forum/docker-dev, or the #docker-dev IRC channel if someone has tried building on mips64

Feel free to comment after I've closed this issue

**Closed by thaJeztah** 2016-04-12 09:59 UTC
