### ISSUE TITLE
shm-size to be configurable

### ISSUE THREAD

**Issue by NIWAHideyuki** [docker/docker#16164] opened 2015-09-09 06:13 UTC
I hope for the function that the shm memory of a size that is bigger than 64MB can be set.
I paid attention to #2606 , #3505 and #4981 . However, it has not been it yet.
And, I tried to make it.

Addition of "--shm-size" to which size of /dev/shm is changed when container is made.

- Optional "--shm-size=" was added to the run sub-command.
- The size of /dev/shm in the container can be changed when container is made.
- Being able to specify is a numerical value that applies number, b, k, m, and g.
- The default value is 64MB, when this option is not set.
- It deals with both native and lxc drivers.

Example)
\# docker run -it --shm-size=256m centos /bin/sh

Signed-off-by: NIWA Hideyuki <niwa.hiedyuki@jp.fujitsu.com>

**Comment by jfrazelle** [comment] 2015-09-09 19:46
this is a duplicate of the issues you mentioned so closing

**Closed by jfrazelle** 2015-09-09 19:46 UTC
