### ISSUE TITLE
Swarm mode : network scoped DNS entries for a service

### ISSUE THREAD

**Issue by sbrattla** [docker/docker#30708] opened 2017-02-03 11:35 UTC
We run a lot of applications, and we are about to move them over to a swarm. Some of these applications use host names (for accessing external services such as a REST APIs or a databases) we cannot change (for different reasons). Different applications use the same host name to access different external resource. 

What we have done up until now is to run each application in its own network and in its own DNS zone. It could also just have been as simple as editing the /etc/hosts file on the service that application runs on to make sure that a given host name resolves to the correct external resource.

It seems this is not that easy in swarm mode. At first, we though it would be as easy as just creating services (for the REST APIs or databases) with names that corresponds to the host name which the application expect to find any given external resource on. However; we then realize that service names are unique. After having looked into this issue, we also realize that it is impossible to alias a given service (representing a REST API or a database) in the scope of a single overlay network. Maybe we could do some sort of DNS trickery with our own DNS service for each overlay network...but then again; I can't stop thinking that network scoped DNS entries for services would be a very useful thing not only for us.

Short story : swarm mode requires that all service names (aka host names) are unique. Different applications in our stack expects to be able to resolve external resources (REST APIs or databases) using host names which would not be "globally" unique within the swarm.

Example:

**Overlay Network 1**

- **Application A** resolves Database A with host name `db` and REST API with host name `api`.
- Database A
  - service name = `dbA` becomes host name = `dbA`. 
  - wanted : network scoped alias = `db`
- REST API A
  - service name = `restapiA` becomes host name = `restapiA`. 
  - wanted : network scoped alias = `api`

**Overlay Network 2**

- **Application B** resolves Database B with host name `db`
- Database B
  - service name = `dbB` becomes host name = `dbB`
  - wanted : network scoped alias = `db`

**Overlay Network 3**

- **Application C** resolves REST API with host name `api`
- REST API C
  - service name = `restapiC` becomes host name = `restapiC`
  - wanted : network scoped alias = `api`

First of all; have I missed something? Is this doable with Docker Swarm mode as it is now (1.13.0)? If not, would this be something worth looking into?

**Comment by sbrattla** [comment] 2017-02-04 22:22
Seems that this is very much related to https://github.com/docker/docker/issues/24787

**Comment by sbrattla** [comment] 2017-02-06 09:17
It seems that I've managed to achieve this using the API. That is, I created service aliases which are network scoped (for a specific overlay network) using the API. The below guide takes you through this and assumes you've got a running swarm.

1. Proxy all HTTP requests on port 80 on one of your swarm hosts to the Docker socket. I'm just doing this for the sake of simplicity as we go through this small guide. On one of your Docker hosts run
  
   `sudo ncat -vlk 80 -c 'ncat -U /var/run/docker.sock'`

2. Create a new overlay network which we will be using.
   
   `docker network create --driver overlay --subnet 10.0.100.0/24 test_net`

3. Pull the nginx:latest image down to all hosts participating in the swarm

   `docker pull nginx:latest`

4. Open your favourite REST client on your own computer. I'm using Postman.

     Create a new `POST` request to `http://[SWARM_HOST]/v1.25/services/create` with the following payload / body :

```
  {
    "Name": "webservice",
    "TaskTemplate": {
      "ContainerSpec": {
        "Image": "nginx:latest"
      }
    },
    "Mode": {
      "Replicated": {
        "Replicas": 2
      }
    },
    "EndpointSpec": {
      "Ports": [
        {
          "Protocol": "tcp",
    	  "PublishedPort": 8080,
    	  "TargetPort": 80
        }
      ]
    },
    "Networks": [
      {
        "Target": "test_net",
  	"Aliases": ["web", "frontend"]
      }
    ]
  }
```

5. Repeat the previous step, but change `"Name"` to `"appservice"`, `"Port"` to `"8181"` and `"Aliases"` to `["app", "backend"]`     
     
6. You should now have two services (`webservice` and `appservice`) on the `test_net` overlay network. Validate that these two services are running by doing a `docker service ls` on one of your docker hosts.

7. Now, log in to a webservice container. Do a `docker ps` on one of your hosts, and find the ID for one of the webservice containers. Then do `docker exec -ti [ID] bash`

8. When inside the container, execute `ping app` or `ping backend`. You should now hit the `appservice` service. 

You have now started two services with additional network scoped aliases. That is, the aliases only work within the test network. 

This functionality works well when you create services using the API. It would be very handy if this could be incorporated into the CLI client. As others have pointed out, there [should be ways to do this](https://github.com/docker/docker/issues/24787#issuecomment-233853394).

**Comment by mostolog** [comment] 2017-02-21 17:22
Maybe related: https://github.com/docker/swarmkit/issues/1242

**Comment by thaJeztah** [comment] 2017-03-16 23:25
Thanks @mostolog, I think it's _related_ but should not be a show-stopper for this feature.

I _do_ think this is a duplicate of https://github.com/docker/docker/issues/24787, so let me close this issue to prevent the discussion from diverging

**Closed by thaJeztah** 2017-03-16 23:25 UTC
Labels: area/swarm

**Comment by billryan** [comment] 2017-03-17 03:15
We can create service with network alias, but it seems impossible to update service with network alias, right? I tried but it prompts `rpc error: code = 2 desc = update out of sequence`.

**Comment by thaJeztah** [comment] 2017-03-17 11:32
Are you updating through the API? `update out of sequence` is if the `?version=` number doesn't match the version of the service you're updating. For example, when updating this service;

```bash
$ docker service inspect web --format '{{ json .Version}}'
{"Index":1028}
```

The API call needs to use `/v1.26/services/{service-id}/update?version=1028` (see
https://docs.docker.com/engine/api/v1.26/#operation/ServiceUpdate)
