### ISSUE TITLE
volume path contain ~ or / is expanded to local windows path in git-bash

### ISSUE THREAD

**Issue by ztou** [docker/docker#31370] opened 2017-02-26 14:11 UTC
**Description**

volume path contain ~ or / is expanded to local windows path in git-bash, such as: ~/data will be converted to C:/Users/huangjoh/data, /data will be converted to C:/Dropbox/opt/Git/data

**Steps to reproduce the issue:**

I have Docker for Windows installed on my WIN 10 machine and I have git-for-windows installed under C:\Dropbox\opt\Git

Then I am using the git-bash.exe as the shell for Docker, following the commands below:

```
huangjoh@SHAH024F22 MINGW64 /
$ echo ~
/c/Users/huangjoh

huangjoh@SHAH024F22 MINGW64 /
$ docker run --name vol-test -v ~/data centos:7

huangjoh@SHAH024F22 MINGW64 /
$ docker inspect -f "{{json .Mounts}}" vol-test
[{"Type":"volume","Name":"bae1c3a56c2afe11778d9bcb1bb06b2c41757aa2c6bcdf67abe7fbdcb8946a6f","Source":"/var/lib/docker/volumes/bae1c3a56c2afe11778d9bcb1bb06b2c41757aa2c6bcdf67abe7fbdcb8946a6f/_data","Destination":"C:/Users/huangjoh/data","Driver":"local","Mode":"","RW":true,"Propagation":""}]

```

**Describe the results you received:**

volume path ~/data is converted to C:/Users/huangjoh/data ( if I set volume path to /data, it will also converted to C:/Dropbox/opt/Git/data)

**Describe the results you expected:**

expect ~/data as the volume path

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
$ docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 5
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.769 GiB
Name: moby
ID: 7RV6:Z557:G6MX:XDR2:4G32:FVGA:VC6W:LBRN:L33A:2EVZ:5GQM:IZPH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 22
 System Time: 2017-02-26T14:08:39.5027629Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by friism** [comment] 2017-02-26 15:09
I don't think it's Docker doing the expansion, it's MinGW/git-bash. This is clear from your example too:

```
$ echo ~
/c/Users/huangjoh
```

Can you detail what you're trying to achieve?

**Comment by ztou** [comment] 2017-02-27 14:33
@friism : thanks, I was trying to setup a dedicated data volume containers with volume path under "/data" or "~/data" (without expanding).

unfortunately, it took me long time to know that, the volume path has been converted to "C:/Users/huangjoh/data" in the new container ( I am new to docker).

I am not able to achieve that in the git-bash (using powershell works fine), do you know how to fix this issue in the git-bash?

**Comment by friism** [comment] 2017-02-27 14:46
@ztou http://stackoverflow.com/a/34386471/2942

**Comment by thaJeztah** [comment] 2017-02-27 15:50
That's a known issue ("feature") of mingw. mingw is trying to be smart. See https://github.com/docker/docker/issues/13741#issuecomment-128893740, and http://www.mingw.org/wiki/Posix_path_conversion

you can also try using a double-slash for paths;  `-v //foo/bar/`

Note that the mount-path inside the container must be an _absolute_ path, so using `~/` or `./` is not a valid format. You need to specify an absolute path inside the container (e.g. `/home/foo/something`).

I'll go ahead and close this issue, because this is not a bug in docker, but feel free to continue the conversation

**Closed by thaJeztah** 2017-02-27 15:50 UTC
Labels: platform/desktop, version/1.13
