### ISSUE TITLE
Can't curl to service host ip:port from container by IPVS

### ISSUE THREAD

**Issue by yank1** [docker/docker#26098] opened 2016-08-29 08:32 UTC
Steps to reproduce the issue:
1. Init swarm (node a)
3. docker service create --name nginx --publish 8081:80 nginx
4. Exec bash into the container
5. curl -v host-ip:8081
->  fails, 

Describe the results you received:
Can curl to the container IP from itself, but can't curl to the IPVS ...

Describe the results you expected:
Should be able to curl to the IP ...

Additional information you deem important (e.g. issue happens only occasionally):
100% reproducible. What am I missing?

**Comment by cpuguy83** [comment] 2016-08-29 14:13
What environment are you running on?
Can you provide all the details requested from the issue template? (output of `docker info`, and `docker version`)

**Comment by yank1** [comment] 2016-08-29 16:11
It's a normal Docker 1.12.1 on Ubuntu 16.04.

**Comment by cpuguy83** [comment] 2016-08-29 16:12
@yank1 Can you please provide the full details?

**Comment by yank1** [comment] 2016-08-30 09:17
root@dhp-ov-dev-2:~# docker info
Containers: 52
 Running: 3
 Paused: 0
 Stopped: 49
Images: 26
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 227
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge macvlan
Swarm: pending
 NodeID: 0ef22zeau5pms76jx53np2m73
 Is Manager: true
 ClusterID: 0eiomtfpbxxrtvlso0g6gac0m
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 192.168.2.125
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 3.859 GiB
Name: dhp-ov-dev-2
ID: BFAY:CNHQ:IRMR:PP4B:UVDM:XCYD:AAE7:AYZH:Q3JQ:EPHG:TSIN:IAWI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8

**Comment by yank1** [comment] 2016-08-30 09:25
root@dhp-ov-dev-2:/# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: active
 NodeID: aepauk62yds5jkzb12vxe4k6n
 Is Manager: true
 ClusterID: 1apvcv9mhiq0i5oyjfyfmq350
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.2.125
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 3.859 GiB
Name: dhp-ov-dev-2
ID: GBON:XLJA:4GCU:TWSD:VDBB:U66Z:CUEQ:J27N:KBTG:GYVC:E7XD:MNTV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Comment by yank1** [comment] 2016-08-30 09:25
root@dhp-ov-dev-2:/# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

**Comment by mrjana** [comment] 2016-08-30 17:53
@yank1 This is a known issue. There is a PR in libnetwork already open to fix it: https://github.com/docker/libnetwork/pull/1398

**Comment by yank1** [comment] 2016-09-04 16:26
Thanks

**Comment by thaJeztah** [comment] 2016-09-26 14:25
duplicate of https://github.com/docker/docker/issues/25463, and it's on the 1.12.2 milestone

**Comment by thaJeztah** [comment] 2016-09-26 14:25
I'll close this one, as we have https://github.com/docker/docker/issues/25463 for tracking

**Closed by thaJeztah** 2016-09-26 14:25 UTC
Labels: area/networking, area/swarm, kind/bug, version/1.12
