### ISSUE TITLE
Website has no "Feedback" link

### ISSUE THREAD

**Issue by davidmichaelkarr** [docker/docker#23905] opened 2016-06-23 16:00 UTC
I know that everything here is open source, but what is a naive user supposed to do when they see issues with a website, and there is no "Feedback" link on the page?  The only thing that comes close is a sales inquiry.

**Comment by hansfrederickbrown** [comment] 2016-06-24 18:32
Hi David,

the "contact" link in the WWW footer now goes too: https://www.docker.com/company/contact

This should help triage the traffic to the right locations

**Comment by thaJeztah** [comment] 2016-06-28 15:19
Thanks @davidmichaelkarr! Let me close this issue, because it's not a bug in "docker", but please continue the conversation if needed :+1:

**Closed by thaJeztah** 2016-06-28 15:19 UTC
