### ISSUE TITLE
docker stop $(docker ps -a) --> does not work

### ISSUE THREAD

**Issue by shashidesai** [docker/docker#26614] opened 2016-09-15 22:32 UTC
**Description**
Docker version --> Docker version 1.12.0, build 8eab29e

When we run:
docker stop $(docker ps -a)
unknown shorthand flag: '"' in -"
See 'docker stop --help'.

but if we use docker stop $(docker ps -a -q)
it works fine
**Steps to reproduce the issue:**
1.docker stop $(docker ps -a)
2.error seen:  unknown shorthand flag: '"' in -"

**Describe the results you received:**
docker stop $(docker ps -a)
unknown shorthand flag: '"' in -"
See 'docker stop --help'.

**Describe the results you expected:**
We should not see any error for "docker stop $(docker ps -a)"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 43
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 123
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: 2FZC:7PNB:Q3J6:V2DF:EFCI:SG7W:HJDC:KCDA:UWQK:G32J:W5V2:UALB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 52
 System Time: 2016-09-15T22:32:02.019882417Z
 EventsListeners: 7
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using docker on mac

**Comment by thaJeztah** [comment] 2016-09-15 22:37
You need to add `-q` so that only the container ID's are returned;

```bash
docker stop $(docker ps -a -q)
```

And because you want to *stop* running containers only, you can remove the `-a` (as that will make it return *stopped* containers, and there's no use to stop those again.

I'll close this issue, because this is not a bug, but I hope the above helps

**Closed by thaJeztah** 2016-09-15 22:37 UTC
Labels: version/1.12

**Comment by sk97045** [comment] 2019-12-25 07:03
docker stop $(docker ps -a -q) also giving "unknown shorthand flag: 'a' in -a
See 'docker stop --help'."

docker stop $(docker ps -q) throwing "unknown shorthand flag: 'q' in -q)
See 'docker stop --help'."

**Comment by thaJeztah** [comment] 2019-12-26 11:06
> "unknown shorthand flag: 'a' in -a
See 'docker stop --help'."
> "unknown shorthand flag: 'q' in -q)
See 'docker stop --help'."

Did you perhaps try to add the `-q` or `-a` flag on the `docker stop` command itself, instead of in the subshell executing `docker ps` ?

**Comment by ahmed82** [comment] 2020-07-21 20:44
I guess you used CMD it wont work 
!!. Use Windows Power-Shell to combined the return result of the $(docker ps -q)
