### ISSUE TITLE
docker overlay network ping failed when the container ip is same with host ip

### ISSUE THREAD

**Issue by LionHeartFXCX** [docker/docker#21357] opened 2016-03-21 04:20 UTC
**Describe**
I create an overylay network with Docker-toolbox,but when the container's ip is same with host's ip, the container can't ping each other.
I have try another container ip addresses that are not same with the machine's ip, succeed. So I am confused that is Docker's overylay network does not support the same ip with the host ip? or I can do other things to solve the problem? or the virtualbox's version is too old?

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: overlay bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: node1
ID: TR2A:PW42:XWNX:JPSJ:MOJL:D6EH:YO6N:DDY4:4PCG:U7XY:LTPP:I44F
Debug mode (server): true
 File Descriptors: 45
 Goroutines: 86
 System Time: 2016-03-21T03:16:08.063964088Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
Cluster store: consul://192.168.99.101:8500
Cluster advertise: 192.168.99.103:2376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I am using docker-toolbox 1.10.3 with VirtualBox4.3.36 .
few days ago, I am using VirtualBox 5.0.16,but it suddenly can not work, I found many ways to slove the problem,but no result. So I change the version of VB, it work normally.
the above content I paste is one of my virtual machines. I create 4 machines, one as a discovery service machine, one as a swarm manager,and others are nodes.

Steps :
1.Create a container test1 on machine 192.168.99.103 with --ip option and --net option, the container ip address is the same with the host ip address.(the container is created successfully)
2.Create a container test2 on machine 192.168.99.102 with --ip option and --net option, the container ip address is the same with the host ip address.(the container is created successfully)
3.test1 ping test2 or test2 ping test1

 received:
ping of both failed

 expected:
ping of both succeed

Additional :
forgive me my poor english, please help me, I'm running out of time.
@thaJeztah @mavenugo

**Comment by mavenugo** [comment] 2016-03-21 05:54
@LionHeartFXCX As per your expectations, the subnet used inside of the overlay network should not ideally overlap with that of the other overlay network or the host subnet for that matter. But I believe the vtep-endpoint address could be the exception (I have to try it myself to confirm). My immediate guess is that since the ip-addresses `192.168.99.102` and `192.168.99.103` are vtep endpoints (`--cluster-advertise`), it is possible that the ip->mac is resolved to the host-namespace and it might conflict with the container space.

Since you are using the `--ip`, I assume that you are intentionally using the `--subnet=192.168.99.0/24` while creating the overlay network. Is there a specific reason that you have such a requirement to have the same subnet as that of the host ? And if so, is there a reason to have the same ip-address as that of the VTEP endpoint ?

I will try and confirm the above observation myself.

**Comment by LionHeartFXCX** [comment] 2016-03-21 06:36
@mavenugo
thanks for your answer. I indeed have the requirement to let the container's ip address be same with the host's ip address.I am using Docker to build the FastDFS environment.
https://github.com/happyfish100/fastdfs.git
![image](https://cloud.githubusercontent.com/assets/11309761/13911891/af8ad9e4-ef71-11e5-814d-dbabda89314e.png)

As you can see,FastDFS's nodes have to use the real ip address to provide upload service. I also get the idea that use `--net=host`,but I prefer to have a try on overlay network. So when I encounter this problem, I am crashed.....

**Comment by mavenugo** [comment] 2016-03-21 21:02
@LionHeartFXCX I don't understand the use-case clearly. And it seems like a workaround/hack to overcome some requirement to overload the host-ip as the container-ip to trick the Storage to behave in a particular way.

Regardless of the use-case, am actually intrigued by the scenario and technically this is something that should have worked. But, there seem to be something involved which needs some investigation.

Having said that, pls check if the following workaround works for you.

Can you create the container test1 on machine 192.168.99.103 with --ip=192.168.99.102 and create test2 container on machine 192.168.99.102 with --ip=192.168.99.103 ? and see if that satisfies your use-case ?

**Comment by LionHeartFXCX** [comment] 2016-03-22 01:13
@mavenugo
test1 on machine 192.168.99.103 with --ip=192.168.99.102 and create test2 container on machine 192.168.99.102 with --ip=192.168.99.103 can ping each other successfully.But it will cause the FastDFS's upload service failed, and I'm going to use the `--net=host` option to solve the problem.At last, generally speaking, is this situation should have worked successfully on Docker? Or maybe this is a bug?   thanks again, it's my first time to ask for a question on github, and pls ignore my poor english
![image](https://cloud.githubusercontent.com/assets/11309761/13939229/21b0035e-f00e-11e5-94d0-ce676ce59775.png)

**Comment by LionHeartFXCX** [comment] 2016-03-22 12:20
@mavenugo
I have found that when the overlay network's subnet ip ranges include the host ip address, ping will fail.
For example
If I have an overlay network ip ranges from `192.168.99.2` to `192.168.99.254`.Then a container in the overlay network has a ip address `192.168.99.5`.And the host ip address is `192.168.99.7`.
When I attach the container,and ping `192.168.99.7`,it will fail. and the logs show `Destination Host Unreachable `
But in the FastDFS use-case, the container shows nothing.

**Comment by mavenugo** [comment] 2016-03-22 17:25
@LionHeartFXCX that is expected behavior. the subnets in overlay network is isolated from other networks (including the host subnet). Hence any routing or bridging that happens in the overlay network is only within the isolated segment. But, for any other subnet, it will use the default route via the `default_gwbridge` and hence it can reach the external world. Since you are purposefully overloading the subnet in the overlay network to be same as the host subnet, you cannot expect the host-ip to be reachable from within the overlay network.

The only issue I see so far is the fact that a container cannot reuse the exact same vtep IP of host. It could very well be the vxlan driver limitation.

Regarding your use-case, I don't think you should make any such assumption and also recommend against the trick that you are trying to deploy (overloading container-ip as host-ip just to trick the storage application, while the actual container is not globally routable).

**Comment by LionHeartFXCX** [comment] 2016-03-23 01:58
@mavenugo Ok, i got it. i'm going to deploy it with`--net=host`,i think it will work well.

**Comment by LionHeartFXCX** [comment] 2016-03-24 12:33
@mavenugo em.... i'm back again. These two days, i have learned what is vxlan and docker's network namespace.I have come to understand the data transfer in vxlan. Then i make an experiment. 

> overlay network:
   name is test, network namespace 1-bed2efe2a1
   machine:
   machine1 with ip 192.168.99.102
   machine2 with ip 192.168.99.103
   container:
   test1 on machine1 with ip 192.168.99.2 and mac 02:42:c0:a8:63:02 
   test4 on machine1 with ip 192.168.99.102 and mac 02:42:c0:a8:63:66 
   test2 on machine2 with ip 192.168.99.3 and mac 02:42:c0:a8:63:03
   test3 on machine2 with ip 192.168.99.103 and mac 02:42:c0:a8:63:67
   test5 on machine2 with ip 192.168.99.105 and mac 02:42:c0:a8:63:69

before i make them ping each other, i check the five container's arp cache and the test's arp cache an have a look at the forwarding entries, it looks like this on machine2:
```
docker@machine2:~$ sudo ip netns exec 1-bed2efe2a1 arp
? (192.168.99.2) at 02:42:c0:a8:63:02 [ether] PERM on vxlan1
? (192.168.99.102) at 02:42:c0:a8:63:66 [ether] PERM on vxlan1
docker@machine2:~$ sudo ip netns exec 1-bed2efe2a1 bridge fdb show dev vxlan1
6a:dc:76:f2:c5:ac permanent
02:42:c0:a8:63:02 dst 192.168.99.102 self permanent
```
and machine2:
```
docker@machine1 :~$ sudo ip netns exec 1-bed2efe2a1 arp
? (192.168.99.105) at 02:42:c0:a8:63:69 [ether] PERM on vxlan1
? (192.168.99.3) at 02:42:c0:a8:63:03 [ether] PERM on vxlan1
? (192.168.99.103) at 02:42:c0:a8:63:67 [ether] PERM on vxlan1
docker@machine1 :~$ sudo ip netns exec 1-bed2efe2a1 bridge fdb show dev vxlan1
7a:96:e8:bd:6b:68 permanent
02:42:c0:a8:63:03 dst 192.168.99.103 self permanent
02:42:c0:a8:63:69 dst 192.168.99.103 self permanent
```
**and there is noting in container's arp cache.**

now, i learn that the vxlan1(VTEP)'s forwarding entries does not have the test4 and test3's mac addr, hence they can not ping each other.But i am confused with this issue:

**why the vxlan1(VTEP) will get arp cache and forwarding entries as soon as i create the container in overlay network?  the container even have no time to communicate with each other.**

i found a fig that shows vxlan's data transfer:
![overlay](https://cloud.githubusercontent.com/assets/11309761/14016596/9db64c20-f1fc-11e5-9966-410d20f97731.PNG)
as you can see, this fig shows the data transfer in vxlan's Discoveries and Tenant Address Learning.
hosts don't know each other until they try to communicate(ping).

**So how does docker implement the vxlan? what is the data transfer in docker's overlay network?  i think it has some difference with the original vxlan.**
 i have found many documents, but there seems no document that explain the data transfer in docker's overlay network.
looking forward to your answer. And do you have some articles explain this? pls tell me.

**Comment by mavenugo** [comment] 2016-03-24 16:59
@LionHeartFXCX Good work on performing the deep dive. Let me answer your questions.

> why the vxlan1(VTEP) will get arp cache and forwarding entries as soon as i create the container in overlay network? the container even have no time to communicate with each other.

That's because, the docker vxlan driver avoids flood and learn. Even the very first packet from a container to another container is properly resolved using the ARP cache and mac-address lookup. It avoids BUM traffic.

> So how does docker implement the vxlan? what is the data transfer in docker's overlay network? i think it has some difference with the original vxlan.

The picture that you pointed to is using VXLAN-Multicast group which we dont use in the docker vxlan driver. The VXLAN tunnels are p2mp between the VTEPs across the hosts.

As I explained to you earlier,
> The only issue I see so far is the fact that a container cannot reuse the exact same vtep IP of host. It could very well be the vxlan driver limitation.

Are you facing any other issue ?

**Comment by LionHeartFXCX** [comment] 2016-03-25 02:35
@mavenugo Is the p2mp tec is `p2mp nonbroadcast`? if so, i have learned that the p2mp needs 
manual config, but in docker i think i do not have configed it. So, is the vxlan driver get the config information from the distributed discovery service such as consul,and then it config himself?
and if it is right, i guess the process is like that:

1. container join the overlay network, consul found that container and record the container's information(mac and ip). if the container's vxlan driver is new, consul also record the vxlan driver's information.
2. all the vxlan drivers in the same overlay network get the updated information from consul quickly.
3. vxlan drivers update its own arp cache and mac-address lookup(container mac and its vxlan driver's ip).
4. container communicate with each other using the vxlan driver's arp cache and mac-address lookup.

Is the process right? if not, how can the vxlan driver cofing itself?

**Comment by mavenugo** [comment] 2016-03-25 05:39
@LionHeartFXCX am writing a doc page to explain the overlay driver architecture and I think that will answer all your questions. stay tuned. Though it is great to know these details, the issue that we are discussing in this thread :

> The only issue I see so far is the fact that a container cannot reuse the exact same vtep IP of host. It could very well be the vxlan driver limitation.

Is nothing to do with the architecture. It is low-level linux vxlan driver implementation and we have to check the behavior. It is such a corner-case that no one has actually seen this (until now). Lets try and concentrate on this and find a solution. Even though am not worried even if we end up not solving this particular case.

**Comment by LionHeartFXCX** [comment] 2016-03-25 10:19
@mavenugo yeah, you are right. I think the problem i meet is very special, and i am not going to spend too much time on it. Thanks a lot, without your help, i will not get so much knowledge about the vxlan driver.

**Comment by mavenugo** [comment] 2016-03-25 16:05
@LionHeartFXCX sure. it is infact very refreshing to see your effort to understanding the deep internals. If you like to learn more PTAL at the code https://github.com/docker/libnetwork/tree/master/drivers/overlay. There is no better doc than the code itself.

**Comment by thaJeztah** [comment] 2016-09-20 18:50
I don't think there's anything actionable here, so I'll close this issue, but feel free to continue the discussion (it's interesting!)

**Closed by thaJeztah** 2016-09-20 18:50 UTC
Labels: area/networking, version/1.10
