### ISSUE TITLE
AutoRemove always false

### ISSUE THREAD

**Issue by JensPiegsa** [docker/docker#28747] opened 2016-11-23 11:01 UTC
**Description**

`docker inspect` does not reflect the presence of the `docker run` flag `--rm`.

**Steps to reproduce the issue:**

1. `$ docker run --rm --name RMTEST alpine sleep 30 &`
2. `$ docker inspect RMTEST | grep AutoRemove`

**Results in:**

                "AutoRemove": false,

**But is expected to result in:**

                "AutoRemove": true,

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 46
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-27-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 5.827 GiB
Name: ubuntu
ID: ZV7B:4QI6:RY76:FIYD:MOQO:ZARK:5Q3X:JOHH:XGZP:NF3N:EZLU:J2YO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by thaJeztah** [comment] 2016-11-23 12:27
That's correct; daemon-side "AutoRemove" is added in docker 1.13 (see https://github.com/docker/docker/pull/20848), so not yet in the 1.12.3 release.

In 1.12.3, the `--rm` is performed client-side.

If you have a machine to test on, you can try running the 1.13 release candidate (https://github.com/docker/docker/releases). RC1 is available, but we'll be releasing RC2 today (if all goes well; it's currently being built and tested)

I'll close this issue, because this is expected, but feel free to comment if you have questions

**Closed by thaJeztah** 2016-11-23 12:27 UTC
Labels: version/1.12

**Comment by thaJeztah** [comment] 2016-11-23 12:31
Note that the `AutoRemove` property is not part of the 1.24 API (which is the version used for 1.12.x); the API uses an open schema, which in some cases results in additional fields to be present in endpoints; https://docs.docker.com/engine/reference/api/docker_remote_api/

> Docker’s Remote API uses an open schema model. In this model, unknown properties in incoming messages are ignored. Client applications need to take this behavior into account to ensure they do not break when talking to newer Docker daemons.

**Comment by 907th** [comment] 2017-08-01 11:28
@thaJeztah it is still the issue on `Docker version 17.03.1-ce, build c6d412e`

**Comment by thaJeztah** [comment] 2017-08-01 11:39
@907th I'm not able to reproduce on docker 17.03.1;

```bash
$ docker run -dit --rm --name test busybox

$ docker inspect test | grep AutoRemove
            "AutoRemove": true,
```

This is on;

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 16:58:30 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 16:58:30 2017
 OS/Arch:      linux/amd64
 Experimental: false
 ```
 
 Make sure your daemon is also running docker 17.03, and that there's no override for the API version (e.g. a `DOCKER_API_VERSION` environment variable set)

**Comment by 907th** [comment] 2017-08-01 11:41
@thaJeztah I'm using `docker-compose run --rm`, not `docker run`.

**Comment by 907th** [comment] 2017-08-01 11:46
```
$ docker-compose run --rm --name multi_unicorn_222 unicorn  bash -i &
[1] 3524
$ docker inspect multi_unicorn_222 | grep AutoRemove
            "AutoRemove": false,
```

**Comment by 907th** [comment] 2017-08-01 11:49
@thaJeztah so, this results in leaking containers on my server 😢  (we start containers -> connection losts -> containers still running).

**Comment by 907th** [comment] 2017-08-01 12:01
@thaJeztah Is this problem related to this repo? Should I report it somewhere else? Thank you!

**Comment by thaJeztah** [comment] 2017-08-01 12:26
@907th docker compose 1.6.2 is [more than a year old](https://github.com/docker/compose/releases/tag/1.6.2), and uses the API version for docker 1.9 or earlier, which did not support this. Upgrade to the current version of docker compose (which at time of writing is 1.15; https://github.com/docker/compose/releases/tag/1.15.0)

**Comment by 907th** [comment] 2017-08-01 13:13
@thaJeztah Thank you very much! `docker-compose run` handles `--rm` completely differently from `docker run`. My issue is not related to `docker run`. I opened an issue in the compose repo.

**Comment by masaeedu** [comment] 2018-01-30 02:32
Hi @thaJeztah. With the following versions:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:05:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I ran:

```bash
docker run -it --rm ubuntu bash
```

Then killed the `docker.exe` process using task manager. The container however remains alive. When I check `docker inspect <container id> | grep AutoRemove`, I get:

```
          "AutoRemove": true,
```

and yet the container is alive despite the client being dead.

**Comment by thaJeztah** [comment] 2018-01-30 03:21
Killing the client will be the same as detaching from the container, so the containers process keeps running, and won’t be removed, so that’s expected

**Comment by masaeedu** [comment] 2018-01-30 03:27
Ok, I ended up here by following links from #22425. There you mentioned:

> There's currently work in progress to improve that, and move the --rm to the daemon, so that **even if the client gets killed**, the daemon can remove the container (directly, or in a later garbage-collect round). You can track progress of that in the PR; docker#20848.

That PR is also closed now it looks like. Is there some other issue that tracks killing a container when the client session that started it with `--rm` is no longer active (for whatever reason, including the client process being `kill`ed)?
