### ISSUE TITLE
Could I run an android system in docker?

### ISSUE THREAD

**Issue by seafooler** [docker/docker#22150] opened 2016-04-19 13:38 UTC
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by HackToday** [comment] 2016-04-19 13:41
Please specify what's the issue is, and what the error info about that(related docker info, version)
and how to reproduce that

**Comment by thaJeztah** [comment] 2016-04-19 13:51
I'm closing this, as the GitHub issue tracker is not a general support forum, but for tracking bugs and reviewing PR's. Please use either;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

I'll close this issue, because this is not a bug report

**Closed by thaJeztah** 2016-04-19 13:51 UTC

**Comment by Yuanxiangz** [comment] 2019-02-01 10:40
I have the same question, could I run an android system in docker? or can you add this support?
