### ISSUE TITLE
Docker still uses /var/lib/docker for network when using -g to specify an alternate location

### ISSUE THREAD

**Issue by aanc** [docker/docker#21988] opened 2016-04-13 09:30 UTC
BUG REPORT INFORMATION

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:52:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:52:22 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-8:17-9437188-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.4 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /media/ssd2/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /media/ssd2/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.6-301.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.55 GiB
Name: 38qcty1.domain.net
ID: 2L7E:E5D6:ZJDA:OBZV:AREK:JHY7:G5AJ:36EC:KNHG:SW4N:MGOR:VIC3

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical (laptop), fedora 23

**Steps to reproduce the issue:**
1. Stop Docker
2. Reconfigure daemon start config to use an alternate lib location with `-g`, `-g /media/ssd2/docker` in my case
3. Remove `/var/lib/docker`
4. Start Docker

**Describe the results you received:**
`/media/ssd2/docker` is created with all the expected content, however `/var/lib/docker` is also re-created, and contains only a network socket file:

```
root /var/lib/docker
 # tree
.
└── network
    └── files
        └── 4a4034abeb8a8581483bc35a38b9b425a12af063b714746d779e75806610f9df.sock

2 directories, 1 file
```

```
# lsof | grep /var/lib/docker
zsh        3300           root  cwd       DIR              253,1      4096    1575227 /var/lib/docker
docker    16875           root    8u     unix 0xffff8803c4bbfc00       0t0      96149 /var/lib/docker/network/files/4a4034abeb8a8581483bc35a38b9b425a12af063b714746d779e75806610f9df.sock type=STREAM
docker    16875 16878     root    8u     unix 0xffff8803c4bbfc00       0t0      96149 /var/lib/docker/network/files/4a4034abeb8a8581483bc35a38b9b425a12af063b714746d779e75806610f9df.sock type=STREAM
docker    16875 16879     root    8u     unix 0xffff8803c4bbfc00       0t0      96149 /var/lib/docker/network/files/4a4034abeb8a8581483bc35a38b9b425a12af063b714746d779e75806610f9df.sock type=STREAM
docker    16875 16880     root    8u     unix 0xffff8803c4bbfc00       0t0      96149 /var/lib/docker/network/files/4a4034abeb8a8581483bc35a38b9b425a12af063b714746d779e75806610f9df.sock type=STREAM
docker    16875 16882     root    8u     unix 0xffff8803c4bbfc00       0t0      96149 /var/lib/docker/network/files/4a4034abeb8a8581483bc35a38b9b425a12af063b714746d779e75806610f9df.sock type=STREAM
docker    16875 16886     root    8u     unix 0xffff8803c4bbfc00       0t0      96149 /var/lib/docker/network/files/4a4034abeb8a8581483bc35a38b9b425a12af063b714746d779e75806610f9df.sock type=STREAM
docker    16875 16887     root    8u     unix 0xffff8803c4bbfc00       0t0      96149 /var/lib/docker/network/files/4a4034abeb8a8581483bc35a38b9b425a12af063b714746d779e75806610f9df.sock type=STREAM
docker    16875 16901     root    8u     unix 0xffff8803c4bbfc00       0t0      96149 /var/lib/docker/network/files/4a4034abeb8a8581483bc35a38b9b425a12af063b714746d779e75806610f9df.sock type=STREAM
docker    16875 16903     root    8u     unix 0xffff8803c4bbfc00       0t0      96149 /var/lib/docker/network/files/4a4034abeb8a8581483bc35a38b9b425a12af063b714746d779e75806610f9df.sock type=STREAM
docker    16875 16907     root    8u     unix 0xffff8803c4bbfc00       0t0      96149 /var/lib/docker/network/files/4a4034abeb8a8581483bc35a38b9b425a12af063b714746d779e75806610f9df.sock type=STREAM
lsof      20219           root  cwd       DIR              253,1      4096    1575227 /var/lib/docker
grep      20220           root  cwd       DIR              253,1      4096    1575227 /var/lib/docker
lsof      20221           root  cwd       DIR              253,1      4096    1575227 /var/lib/docker

```

**Describe the results you expected:**
Expected result is that Docker does not use `/var/lib/docker` anymore

**Additional information you deem important (e.g. issue happens only occasionally):**

```
# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─exec.conf, proxy.conf
   Active: active (running) since Wed 2016-04-13 11:16:43 CEST; 4min 32s ago
     Docs: https://docs.docker.com
 Main PID: 16875 (docker)
   CGroup: /system.slice/docker.service
           └─16875 /usr/bin/docker daemon -H fd:// -s devicemapper -dns 10.194.5.11 --dns 8.8.8.8  -g /media/ssd2/docker

Apr 13 11:16:43 38qcty1.domain.net docker[16875]: time="2016-04-13T11:16:43.528613187+02:00" level=info msg="Loading containers: done."
Apr 13 11:16:43 38qcty1.domain.net docker[16875]: time="2016-04-13T11:16:43.528633094+02:00" level=info msg="Daemon has completed initialization"
Apr 13 11:16:43 38qcty1.domain.net docker[16875]: time="2016-04-13T11:16:43.528655554+02:00" level=info msg="Docker daemon" commit=20f81dd execdriver=native-0.2 graphdriver=devicemapper version=1.10.3
Apr 13 11:16:43 38qcty1.domain.net systemd[1]: Started Docker Application Container Engine.
Apr 13 11:16:43 38qcty1.domain.net docker[16875]: time="2016-04-13T11:16:43.539732048+02:00" level=info msg="API listen on /var/run/docker.sock"
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by thaJeztah** [comment] 2016-04-13 16:36
Hi @aanc, thanks or reporting; this is a duplicate of https://github.com/docker/docker/issues/18508. Please subscribe to that issue to stay informed on progress

**Closed by thaJeztah** 2016-04-13 16:36 UTC

**Comment by aanc** [comment] 2016-04-14 08:08
Oh, thanks! Sorry for the duplicate :(

**Comment by thaJeztah** [comment] 2023-09-15 08:14
Yes, correct. storage drivers used to be referred to as graph drivers. It was later changed to a more generic "storage drivers", because the "graph driver" name was based on how they were _implemented_, not what they did (and there were already plans to change the implementation; which is what became `snapshotters` in containerd.
