### ISSUE TITLE
Docker Hub Autobuild used wrong value for tag

### ISSUE THREAD

**Issue by sirkkalap** [docker/docker#10271] opened 2015-01-22 11:32 UTC
For some reason new build used branch name as tag, not the value "latest" that was specified in Build Details.

I am very sorry, if this is improper forum for Docker Hub issues, but I am new to Docker and confused.

The build is bnysvsomxwdishjhqlbwrwg (https://registry.hub.docker.com/u/sirkkalap/nginx-proxy/build_id/36304/code/bnysvsomxwdishjhqlbwrwg/)

**Comment by sirkkalap** [comment] 2015-01-22 11:41
I have forked nginx-proxy (jwilder/nginx-proxy) there. So this may be self inflected.

**Comment by sirkkalap** [comment] 2015-01-22 11:46
For those who do not have account in Docker Hub, here is what I see

![nayttokuva 2015-01-22 kello 12 43 03](https://cloud.githubusercontent.com/assets/703699/5855091/fd7dcc20-a23c-11e4-89a4-e698614ef15b.png)

![nayttokuva 2015-01-22 kello 12 43 14](https://cloud.githubusercontent.com/assets/703699/5855094/042d56f8-a23d-11e4-8b6b-0634cc3a3932.png)

**Comment by sirkkalap** [comment] 2015-01-22 11:48
Source code for the build is at https://github.com/sirkkalap/nginx-proxy

**Comment by sparklyballs** [comment] 2015-01-22 14:51
this is also happening to me. any automated builds that are updated or added are being tagged as master.

**Comment by sirkkalap** [comment] 2015-01-22 14:55
Maybe the data bindings are mixed somewhere?

**Comment by sirkkalap** [comment] 2015-01-22 14:56
As a workaround I can now make a branch called "latest" in GitHub.

**Comment by zdm** [comment] 2015-01-22 16:15
Confirmed.

This is a major problem. All new automated builds come with invalid tags, so all our deployment process is corrupted.

**Comment by zdm** [comment] 2015-01-22 16:27
Can somebody from staff tell - is this is a temporary or persistent behavior?
Do I need to rename all "latest" tag to "default" now?

Also, It is mandatory to inform your customers about such incompatible changes.

**Comment by jfrazelle** [comment] 2015-01-22 16:31
No this is wrong and it needs to be fixed on the hub side ping @kencochrane

**Comment by kencochrane** [comment] 2015-01-22 16:44
@dustinlacewell can you take a look

**Comment by metalivedev** [comment] 2015-01-22 17:40
We are currently tracking progress on this via [status.docker.com](http://status.docker.com/pages/incident/533c6539221ae15e3f000031/54c135bce0354e3856000229)

**Comment by jfrazelle** [comment] 2015-01-22 17:49
Is there a place for Hub related issues so we don't flood the docker/docker
issues :)

**Comment by kencochrane** [comment] 2015-01-22 17:51
@jfrazelle sorry for the clutter, the best place right now is to send an email to support@docker.com, hopefully we will have a better place in the future.

**Comment by sparklyballs** [comment] 2015-01-22 22:45
the change of status to green on this might be a little premature, new builds are getting tagged correctly, but triggering an update to an existing build is still resulting in the build being tagged incorrectly.

![screen shot 2015-01-22 at 22 42 29](https://cloud.githubusercontent.com/assets/4343808/5866355/5742d188-a288-11e4-8135-920ae9f25cfd.png)

**Comment by jfrazelle** [comment] 2015-01-27 17:17
Hi all, sorry considering this is not a bug with anything in this repo specifically I am going to close this. But this doesn't mean this is not a real issue. It is :) but it is best handled by the folks at support@docker.com

**Closed by jfrazelle** 2015-01-27 17:17 UTC
