### ISSUE TITLE
Docker daemon stuck (docker ps, docker exec)

### ISSUE THREAD

**Issue by belovanton** [docker/docker#26883] opened 2016-09-24 14:04 UTC
docker ps -a - stuck
docker exec - stuck too
```
[root@storage ~]# docker info
Containers: 11
 Running: 9
 Paused: 0
 Stopped: 2
Images: 30
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.3-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: storage.corp.ru
ID: 757S:4HSF:Q7I5:U4SF:P2ER:APNC:SKIE:AFIV:5QMV:MNNL:LMT4:MVRQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

How I can make it work without restart running containers?

**Comment by cpuguy83** [comment] 2016-09-24 14:42
Can you send `SIGUSR1 to the docker daemon and collect the stack trace from the daemon logs?

**Comment by belovanton** [comment] 2016-09-24 18:12
I did that you can look at my logs there https://dpaste.de/P8Z3

**Comment by belovanton** [comment] 2016-09-25 11:19
Any luck with reading logs?

**Comment by cpuguy83** [comment] 2016-09-26 15:50
@mlaventure This is another one it looks like it's getting stuck in libcontainerd waiting on a response maybe?

@belovanton Only way to get this unstuck will be to restart the daemon.

**Comment by mlaventure** [comment] 2016-09-26 16:08
Re-opening, since we haven't found the root cause of what seems to be a deadlock :)

**Comment by mlaventure** [comment] 2016-09-26 16:19
The daemon looks to be stuck on a Resize call indeed:
```
goroutine 146690 [select, 453 minutes]:
google.golang.org/grpc/transport.(*Stream).Header(0xc821ae7a40, 0xc821ae7a40, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-e
ngine/vendor/src/google.golang.org/grpc/transport/transport.go:221 +0x242
google.golang.org/grpc.recvResponse(0x7efbfbf951f0, 0x2ab5d80, 0x0, 0x0, 0x0, 0x0, 0x7efbfbf95228, 0xc82041e380, 0x7efbfbf95250, 0xc82041e3a0, ...)
	/root/rpmbuild/BUILD/docker-engine/vendor/src/google.golang.org/grpc/call.go:54 +0x4e
google.golang.org/grpc.Invoke(0x7efbfbf8b918, 0xc820058770, 0x1eede80, 0x18, 0x1b649c0, 0xc820de82d0, 0x1b64b00, 0x2ab5d80, 0xc82031a4d0, 0x0, ...)
	/root/rpmbuild/BUILD/docker-engine/vendor/src/google.golang.org/grpc/call.go:178 +0xae6
github.com/docker/containerd/api/grpc/types.(*aPIClient).UpdateProcess(0xc82007a560, 0x7efbfbf8b918, 0xc820058770, 0xc820de82d0, 0x0, 0x0, 0x0, 0xc82011b0e0, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/containerd/api/grpc/types/api.pb.go:954 +0xec
github.com/docker/docker/libcontainerd.(*client).Resize(0xc82040bda0, 0xc82047dcc0, 0x40, 0xc8217c02c0, 0x40, 0x62, 0x13, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/libcontainerd/client_linux.go:219 +0x23f
github.com/docker/docker/daemon.(*Daemon).ContainerExecResize(0xc820400d00, 0xc820a680f1, 0x40, 0x13, 0x62, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/resize.go:39 +0x101
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainerExecResize(0xc820886740, 0x7efbfbfcb4b8, 0xc820de81b0, 0x7efbfbfc0088, 0xc8208284e0, 0xc821ae7960, 0xc820de8030, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router/container/exec.go:133 +0x26f
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainerExecResize)-fm(0x7efbfbfcb4b8, 0xc820de81b0, 0x7efbfbfc0088, 0xc8208284e0, 0xc821ae7960, 0xc820de8030, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:68 +0x74
github.com/docker/docker/api/serve
r/middleware.VersionMiddleware.WrapHandler.func1(0x7efbfbfcb4b8, 0xc820de81b0, 0x7efbfbfc0088, 0xc8208284e0, 0xc821ae7960, 0xc820de8030, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7efbfbfcb4b8, 0xc820de8120, 0x7efbfbfc0088, 0xc8208284e0, 0xc821ae7960, 0xc820de8030, 0x0, 0x0)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7efbfbfc0088, 0xc8208284e0, 0xc821ae7960)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x138
net/http.HandlerFunc.ServeHTTP(0xc820188f00, 0x7efbfbfc0088, 0xc8208284e0, 0xc821ae7960)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82038c5a0, 0x7efbfbfc0088, 0xc8208284e0, 0xc821ae7960)
	/root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820a8d5b0, 0x7efbfbfc0088, 0xc8208284e0, 0xc821ae7960)
	/root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc8202b5480, 0x7efbfbfc0088, 0xc8208284e0, 0xc821ae7960)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82032da00)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

@belovanton do you know if you had `docker exec` that would start long living process in the background?

**Comment by edannenberg** [comment] 2016-09-26 16:52
Same problem here since 1.11 or 1.12, so far it only happened occasionally on my local box, which I chalked off as being a devicemapper issue. It only seems to happen after rebooting the system.

Today however 3 out of 4 production VM had the same problem after the VM host got restarted. Those are all running with the btrfs backend. Only solution I found so far is killing the daemon process and deleting the docker data dir. Boy was I happy I never trusted docker data volumes or this would have been one hell of a monday.

Docker log from shutting down yesterday into booting into stuck daemon today on my local box (did signal  `SIGUSR1` before grabbing the log): http://pastebin.com/WanXNPP0

**Comment by mlaventure** [comment] 2016-09-26 17:20
@edannenberg can you post which version of `dockerd` and `containerd` you are actually using?

You have a few `"libcontainerd: failed to convert event timestamp: \"timestamp: nil Timestamp\""` in your logs, which should never happen

**Comment by edannenberg** [comment] 2016-09-26 17:52
dockerd --version
    Docker version 1.12.1, build 23cf638
    
    containerd --version
    containerd version 0.2.0 commit: 14e7949

This is on Gentoo.

**Comment by mlaventure** [comment] 2016-09-26 18:05
@edannenberg your `containerd` version should be commit: `0ac3cd1be170d180b2baed755e8f0da547ceb267`

You have a mismatch, I seem to remember another gentoo user having the same issue before where their `containerd` got out of sync too but I haven't been able to find the comment.

**Comment by edannenberg** [comment] 2016-09-26 18:34
Interesting, looks like a weird dependency issue with the docker ebuild. Installed containerd version according to portage: `0.2.2_p20160622::gentoo`.

```
emerge -pv containerd

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U ~] app-emulation/containerd-0.2.3::gentoo [0.2.2_p20160622::gentoo] USE="seccomp" 974 KiB

Total: 1 package (1 upgrade), Size of downloads: 974 KiB

The following keyword changes are necessary to proceed:
 (see "package.accept_keywords" in the portage(5) man page for more details)
# required by app-emulation/docker-1.12.1::gentoo
# required by @selected
# required by @world (argument)
=app-emulation/containerd-0.2.3 ~amd64

emerge -pv docker

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   ~] app-emulation/docker-1.12.1::gentoo  USE="device-mapper seccomp -apparmor -aufs -btrfs -experimental -overlay" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB
```

Updated to 0.2.3 manually, now at `973f21fcadedf70c032554ba43622f857496f886` or tag v0.2.3. Lets see if that helps. :)

/cc @tianon

**Comment by belovanton** [comment] 2016-09-26 21:22
@mlaventure I think in my case its stuck when I run docker exec bash and run mysqld.

**Comment by mlaventure** [comment] 2016-09-26 21:26
@belovanton ok, in that case it's the exec's children issue.

When you exit the bash from the exec, containerd waits for the output data to be completely flushed, but mysqld would be retaining a reference on those preventing the close and any new events from containerd to be processed.

1.12.2 should come with a version of containerd that addresses this issue.

Please give the rc a try when it comes out this week, it should fix your issue, I'll close this meanwhile.

Thanks!

**Closed by mlaventure** 2016-09-26 21:26 UTC
Labels: area/runtime, kind/bug, version/1.12
