### ISSUE TITLE
[Feature request] Dockerfile ARG before FROM

### ISSUE THREAD

**Issue by wontonst** [docker/docker#21001] opened 2016-03-07 18:09 UTC
In my Dockerfile, I'd like to do something like

```
ARG $img_tag
FROM myimage:$img_tag
```

Right now I have to generate the Dockerfile on the fly which is cumbersome.

**Comment by thaJeztah** [comment] 2016-03-07 18:32
Thanks for suggesting @wontonst. This is a duplicate of https://github.com/docker/docker/issues/18119, so I'll close this one; please continue the discussion on that issue :+1:

**Closed by thaJeztah** 2016-03-07 18:32 UTC
