### ISSUE TITLE
Internal DNS resolver failing on one node but working on another

### ISSUE THREAD

**Issue by mgoelzer** [docker/docker#24614] opened 2016-07-14 01:01 UTC
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:39:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:39:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
[ec2-user@ip-192-168-33-201 ~]$ docker info
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 5
Server Version: 1.12.0-rc4
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: active
 NodeID: 3t6pxnbg99au4s4bnbx8vihsk
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:db346c871dc3d415a67b92fe8e3bdd960a395d9610775858890017f2800ab355
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.7 MiB
Name: ip-192-168-33-201.us-west-1.compute.internal
ID: C4TZ:WMHY:3D6K:RKFG:ZIQS:5SQ5:IFZM:LCTV:JPJU:FTXD:QYNK:WWH3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 136
 System Time: 2016-07-13T21:02:16.748244686-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
3-node swarm on AWS running RHEL 7.2 (3.10.0 kernel)

**Steps to reproduce the issue:**

Test scenario is like this:
1.  Bring up three RHEL 7.2 machines running 1.12-rc4.
2.  On manager:  `docker swarm init --listen-addr 192.168.33.201:2377`
3.  On the other two:  `docker swarm join --listen-addr <IP>:2377 --secret whatever 192.168.33.201:2377`
4.  Create the voting app services:
```
docker network create -d overlay mynetwork

docker service create --replicas 5 --name frontend --env QUEUE_HOSTNAME=redis --env OPTION_A=Kats --env OPTION_B=Doggies --network mynetwork --publish 80/tcp --label=docker.swarm.lb.port=80/http mikegoelzer/s2_frontend:latest
docker service create --name redis --network mynetwork redis:latest
docker service create --replicas 3 --name worker --network mynetwork mikegoelzer/s2_worker:latest
docker service create --name results --publish 8080/tcp --network mynetwork --label=docker.swarm.lb.port=81/http mikegoelzer/s2_results:latest
docker service create --name pg --env POSTGRES_PASSWORD=pg8675309 --network mynetwork postgres:latest
```
5.  Voting app should work
6.  Reboot one or both workers
7.  Eventually get into a state where `worker` replicas are spread across two machines:

```
[ec2-user@ip-192-168-33-201 ~]$ docker node ls
ID                           HOSTNAME                                      MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
0rz64sd6o8gp4gbgbgcjirdg9    ip-192-168-33-211.us-west-1.compute.internal  Accepted    Ready   Active        
2t7ytjfii6cvod5yxgkbknoq9    ip-192-168-33-212.us-west-1.compute.internal  Accepted    Ready   Active        
3t6pxnbg99au4s4bnbx8vihsk *  ip-192-168-33-201.us-west-1.compute.internal  Accepted    Ready   Drain         Leader
[ec2-user@ip-192-168-33-201 ~]$ docker node tasks ip-192-168-33-211.us-west-1.compute.internal
ID                         NAME        SERVICE   IMAGE                           LAST STATE              DESIRED STATE  NODE
1earfxrm60ivzt5z14sl2r4uh  redis.1     redis     redis:latest                    Running 48 minutes ago  Running        ip-192-168-33-211.us-west-1.compute.internal
eosq87rxsishoa8akbixe50n9  pg.1        pg        postgres:latest                 Running 51 minutes ago  Running        ip-192-168-33-211.us-west-1.compute.internal
2ej98rig4g070236i9ie3r22q  worker.2    worker    mikegoelzer/s2_worker:latest    Running 43 minutes ago  Running        ip-192-168-33-211.us-west-1.compute.internal
1p9klmouyuswtmcpb71b48dve  worker.3    worker    mikegoelzer/s2_worker:latest    Running 43 minutes ago  Running        ip-192-168-33-211.us-west-1.compute.internal
bvnedsxl8qf2722p82snxdnzn  frontend.4  frontend  mikegoelzer/s2_frontend:latest  Running 48 minutes ago  Running        ip-192-168-33-211.us-west-1.compute.internal
[ec2-user@ip-192-168-33-201 ~]$ docker node tasks ip-192-168-33-212.us-west-1.compute.internal
ID                         NAME        SERVICE   IMAGE                           LAST STATE                       DESIRED STATE  NODE
2k1wpyunptmky64m0z7a813ri  results.1   results   mikegoelzer/s2_results:latest   Accepted less than a second ago  Accepted       ip-192-168-33-212.us-west-1.compute.internal
4fea8k8kfbdeqs77o78q6p83w  worker.1    worker    mikegoelzer/s2_worker:latest    Running 43 minutes ago           Running        ip-192-168-33-212.us-west-1.compute.internal
8oqyby1a8nsb2a7rvequ0kamk  frontend.1  frontend  mikegoelzer/s2_frontend:latest  Running 48 minutes ago           Running        ip-192-168-33-212.us-west-1.compute.internal
8xd9ucbjciyva3a5xhqqkzhn6  frontend.2  frontend  mikegoelzer/s2_frontend:latest  Running 48 minutes ago           Running        ip-192-168-33-212.us-west-1.compute.internal
asqzhtgs9kvg8mn14lfl6vqvd  frontend.3  frontend  mikegoelzer/s2_frontend:latest  Running 48 minutes ago           Running        ip-192-168-33-212.us-west-1.compute.internal
2osjf2hyawi5427cjdubn7iwn  frontend.5  frontend  mikegoelzer/s2_frontend:latest  Running 48 minutes ago           Running        ip-192-168-33-212.us-west-1.compute.internal
```

Now `docker exec` into each replica from the appropriate node.  For the replicas running on `.33.211`, `nslookup pg.mynetwork` from inside a container correctly returns service VIP of postgres:
 
```
[ec2-user@ip-192-168-33-211 ~]$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS               NAMES
e30770edd759        mikegoelzer/s2_worker:latest     "/usr/lib/jvm/java-7-"   5 minutes ago       Up 5 minutes                            worker.3.1p9klmouyuswtmcpb71b48dve
6d4190e1bc8d        mikegoelzer/s2_worker:latest     "/usr/lib/jvm/java-7-"   5 minutes ago       Up 5 minutes                            worker.2.2ej98rig4g070236i9ie3r22q
003652e2b082        postgres:latest                  "/docker-entrypoint.s"   12 minutes ago      Up 12 minutes       5432/tcp            pg.1.eosq87rxsishoa8akbixe50n9
[ec2-user@ip-192-168-33-211 ~]$ docker exec -it e30770edd759 sh
# nslookup pg.mynetwork
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	pg.mynetwork
Address: 10.0.0.16
```

But from the replica running on `.33.212`, the same `nslookup pg.mynetwork` from inside the replica fails:

```
[ec2-user@ip-192-168-33-212 ~]$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS               NAMES
d95cf53b7ebb        mikegoelzer/s2_worker:latest     "/usr/lib/jvm/java-7-"   48 minutes ago      Up 48 minutes                           worker.1.4fea8k8kfbdeqs77o78q6p83w
[ec2-user@ip-192-168-33-212 ~]$ docker exec -it d95cf53b7ebb sh
# nslookup pg
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
*** Can't find pg: No answer

# nslookup pg.mynetwork
Server:		127.0.0.11
Address:	127.0.0.11#53
```

**Describe the results you received:**
Shown above.  Internal DNS resolver is failing on one node, but working on the other.

**Describe the results you expected:**
The names `pg` and `pg.mynetwork` should be resolvable from within any replica of `worker` service.  Each replica should see the same view of the network.

**Additional information you deem important (e.g. issue happens only occasionally):**
RHEL 7.2, kernel `3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 9 10:09:10 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by aluzzardi** [comment] 2016-09-14 22:57
@sanimej Has this been fixed?

#26323 was opened a few days ago and seems to be related to this.

/cc @mrjana @mavenugo

**Comment by dperny** [comment] 2016-09-14 22:58
Related to swarmkit/#1419 perhaps?

**Comment by aluzzardi** [comment] 2016-09-14 23:01
@mgoelzer @mavenugo Hey, is this the issue you've trying to reproduce on RHEL? Can you still reproduce it with the latest version?

**Comment by sanimej** [comment] 2016-09-15 01:30
@aluzzardi @mgoelzer This was reported in RC4. many fixes related to network state has gone in since. I think the best would be to try the latest docker master (1.12.2 will have the same set of fixes).

**Comment by icecrime** [comment] 2016-09-19 22:44
@mgoelzer Can you please try to reproduce on master, and either add more details here or close the issue? Thanks!

**Closed** 2016-09-20 21:52 UTC
Labels: area/networking, area/swarm, kind/bug, version/1.12
