### ISSUE TITLE
How to pass secret on POST /services/create ?

### ISSUE THREAD

**Issue by s101d1** [docker/docker#30147] opened 2017-01-14 00:06 UTC
I'm using Docker v1.3, I want to pass secret on `POST /services/create` remote API.

In docker command line, it will be equal to `docker service create --secret login-password  ubuntu`.

However [documentation on the website](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/) is only showing for v1.2. 

So how to pass secret on  `POST /services/create` remote API?

**Comment by thaJeztah** [comment] 2017-01-14 01:54
The API documentation for 1.13 has not been published yet, because 1.13 is not released yet. See https://github.com/docker/docker/tree/v1.13.0-rc7/api#updating-the-api-documentation on how to view the API docs (which is not generated using swagger)

However, the easiest way to learn how the API calls look is to start the daemon (dockerd) in debug mode, and run the command with the CLI. API requests are visible in the daemon logs (or printed to stdout/stderr if you manually run the daemon in the foreground).

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-01-14 01:54 UTC
