### ISSUE TITLE
Windows 7 not finding files on drive

### ISSUE THREAD

**Issue by FahdW** [docker/docker#32510] opened 2017-04-11 03:59 UTC
**Description**
Trying to run a simple script in a container. Using Windows 7 and docker toolbox in docker quickstart terminal. 

**Steps to reproduce the issue:**
1. Created simple hello.rb in my pwd.
2. Run docker run --rm -v "$(pwd)":/app -w /app iron/ruby sh -c 'ruby hello.rb' in quickstart terminal

**Describe the results you received:**
```
time="2017-04-11T00:05:52-04:00" level=info msg="Unable to use system certificat
e pool: crypto/x509: system root pool is not available on Windows"
ruby: No such file or directory -- hello.rb (LoadError)
```

**Describe the results you expected:**
```
Hello World!
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
(paste your output here)
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
(paste your output here)
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.59-boot2docker
Operating System: Boot2Docker 17.04.0-ce (TCL 7.2); HEAD : c69677f - Thu Apr  6
16:26:16 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: QCRZ:ECXL:I6FL:ZBI3:JYMO:NEEN:NNKA:LDSK:XSGX:4LKF:3EGK:XF4K
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 23
 System Time: 2017-04-11T03:56:22.145670566Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Output of `docker inspect mount`:**

```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/k/programming/Projects/playground",
                "Destination": "/app",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
```

**Comment by jaschweder** [comment] 2017-04-13 20:29
I've some similar problems running docker on Windows 10, maybe you can change the $('pwd') who is specific for Linux platform to full path like K:\... and report if this resolve

**Comment by FahdW** [comment] 2017-04-13 20:47
@jaschweder I was using powershell and it has pwd support. It has most Linux commands available to it. I'll give hard linking the directory, although I vaguely remember doing it.

**Comment by thaJeztah** [comment] 2017-04-15 05:18
This is expected. When using Docker Toolbox / VirtualBox, only the `C:\Users` directory by default is shared with the VirtualBox VM (through VirtualBox guest additions). Any directory or drive outside of that is not shared with the VM. As a result, docker creates an empty directory in the given location, and bind-mounts that in the container 

See the "folder sharing" section in the boot2docker readme; https://github.com/boot2docker/boot2docker/#folder-sharing

I'll close this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-04-15 05:18 UTC
