### ISSUE TITLE
Error: Status 403 trying to pull repository

### ISSUE THREAD

**Issue by Carracer66** [docker/docker#32097] opened 2017-03-24 20:06 UTC
I have inherited a local Docker repository and after setting up a new client machine, I am unable to run existing Dockerfiles because I can't pull from the local repo.
I'm new at this, so not sure how to troubleshoot.  What's more scary is that, although I see similar problems, I don't see that anyone is running into this one.  Please Help.

When I attempt to build a Dockerfile with it's first line being: 
```
FROM IP.OF.LOCAL.REPO:5000/consul
```

```
Pulling repository IP.OF.LOCAL.REPO:5000/consul
Error: Status 403 trying to pull repository consul: `<HEAD><TITLE>Access Y BGCOLOR=\"white\" FGCOLOR=\"black\"><H1>Access Denied</H1><HR>\n<FONT F\nDescription: You are not allowed to access the document at location <em2\" cols=\"75\">http://IP.OF.LOCAL.REPO:5000/v1/repositories/consul/images<n<HR>\n<!-- default \"Access Denied\" response (403) -->\n</BODY>\n`
```
And when I attempt a search:

```
$ docker search IP.OF.LOCAL.REPO:5000/swarm
Error response from daemon: Unexpected status code 403

$ docker search IP.OF.LOCAL.REPO:5000
NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED
```
Server hosting the repo:

```
 ~]$ ps -aef | grep docker
jshanno+   420 29481  0 13:58 pts/0    00:00:00 grep --color=auto docker
root     31251     1  0 12:20 ?        00:00:07 /usr/bin/docker daemon -H fd:// --insecure-registry IP.OF.LOCAL.REPO:5000 -H tcp://IP.OF.LOCAL.REPO:2375 --cluster-store=consul://IP.OF.LOCAL.REPO:8500 --cluster-advertise=eth0:2375 --bip=10.0.18.1/24 --ip-masq=true --mtu=1450
root     31590 31251  0 12:29 ?        00:00:00 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5000 -container-ip 10.0.18.2 -container-port 5000
root     31616 31251  0 12:29 ?        00:00:00 registry serve /etc/docker/registry/config.yml
```

```
~]$ docker info
Containers: 2
Images: 139
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-103563254-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.048 GB
 Data Space Total: 107.4 GB
 Data Space Available: 6.988 GB
 Metadata Space Used: 6.578 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.954 GiB
Name: dtcrevere3
ID: NJFU:XVBW:KHTD:G6RT:XWFV:3Q3L:F4FX:YUVL:2IOY:VOKX:JH7P:IBGO
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: consul://IP.ADDRESS.OF.REPO:8500
Cluster advertise: IP.ADDRESS.OF.REPO:2375
```

```
Client:
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 27
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-134399500-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 695.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 47.59 GB
 Metadata Space Used: 1.638 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.64 GiB
Name: centos7-myName
ID: ZAHL:BW2A:JKTP:WBDJ:IJWB:H3O5:ASPV:5GXR:AXQ6:VROJ:K2X6:GPTW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: IP.OF.HTTP.PROXY:80/
Registry: https://index.docker.io/v1/
Insecure Registries:
 IP.OF.LOCAL.REPO:5000
 127.0.0.0/8
```

**Comment by Carracer66** [comment] 2017-03-31 15:12
What did I do wrong?  Why no responses?

**Comment by thaJeztah** [comment] 2017-03-31 15:51
This really looks like a configuration issue of the local registry;

```
Error: Status 403 trying to pull repository consul: `<HEAD><TITLE>Access Y BGCOLOR=\"white\" FGCOLOR=\"black\"><H1>Access Denied</H1><HR>\n<FONT F\nDescription: You are not allowed to access the document at location <em2\" cols=\"75\">http://IP.OF.LOCAL.REPO:5000/v1/repositories/consul/images<n<HR>\n<!-- default \"Access Denied\" response (403) -->\n</BODY>\n`
```

That "access denied" page is coming from the local registry; by default the registry does not have access control enabled (and only "basic" options are available). The documentation for deploying a registry is located here; https://docs.docker.com/registry/deploying/, but may be different depending on the version of the registry that's deployed (or even if it's a "docker" registry, or another registry)

```
$ docker search IP.OF.LOCAL.REPO:5000/swarm
Error response from daemon: Unexpected status code 403
```

That's expected if the registry is the "open source" registry (https://github.com/docker/distribution/); the registry itself does not have indexing / "search" capabilities, which is something that needs to be implemented separately (I _think_ Docker Trusted Registry _does_ have search capabilities https://docs.docker.com/datacenter/dtr/2.2/guides/)

Based on this in your output of the server;

```
registry serve /etc/docker/registry/config.yml
```

It could also be a legacy (V1) registry; https://github.com/docker/docker-registry. That's very old, not maintained, and insecure

Note that `Server Version: 1.9.0` is an old, EOL version of docker as well, and no longer maintained.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-31 15:51 UTC
Labels: area/builder, area/distribution

**Comment by Carracer66** [comment] 2017-03-31 23:31
Thank You.  Upgraded client and server to the latest version.  No change.
I have updated the post and moved it to •https://forums.docker.com
Any other ideas???
