### ISSUE TITLE
Docker ignores memory limits set through remote API

### ISSUE THREAD

**Issue by Slix** [docker/docker#13954] opened 2015-06-15 23:42 UTC
Docker is ignoring memory limits set via `POST /containers/create`. Memory limits set via command-line work fine.

The following ignores swap, as my kernel does not support swap limits.

Command-line works:
```sh
$ docker run --memory=5m -ti ubuntu:14.04 /bin/bash
WARNING: Your kernel does not support swap limit capabilities. Limitation discarded.
...
$ docker stats condescending_fermi
CONTAINER             CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
condescending_fermi   0.00%               3.402 MiB/5 MiB     68.05%              648 B/648 B
```

But fails with HTTP:
```py
config = """
{
     "Tty": true,
     "OpenStdin": true,
     "StdinOnce": true,
     "Cmd": [
             "/bin/bash"
     ],
     "Image": "ubuntu:14.04",
     "Memory": 5242880,
     "HostConfig": {
       "Memory": 5242880
    }
}
"""
config = json.loads(config)
d = docker.Client("unix://var/run/docker.sock")
id = d._post_json(d._url("/containers/create"), data=config).json()['Id']
d._post(d._url("/containers/{}/start".format(id)))
print id
>>> 50203efe2cf228f02317eb123e0d0c297f712bf428e73409c2173152c3c75ad8
```
```sh
$ docker stats 50203efe2cf2
CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
50203efe2cf2        0.00%               612 KiB/364.1 MiB   0.16%               648 B/648 B
```

Environment details:
```sh
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

$ docker info
Containers: 12
Images: 29
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 53
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 364.1 MiB
Name: vagrant
ID: HU5J:KGXX:BPUT:ONPJ:TRRK:63SN:PYPZ:XS54:2HUO:3U3O:KAMU:VKFL
WARNING: No swap limit support

$ uname -a
Linux vagrant 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Here are more verbose inspects. First the command-line, then the HTTP. Note that the second HTTP one has memory 0.

```sh
$ docker inspect condescending_fermi 
[{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
        "AttachStderr": true,
        "AttachStdin": true,
        "AttachStdout": true,
        "Cmd": [
            "/bin/bash"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": null,
        "Env": null,
        "ExposedPorts": null,
        "Hostname": "72bf21497fa5",
        "Image": "ubuntu:14.04",
        "Labels": {},
        "MacAddress": "",
        "Memory": 5242880,
        "MemorySwap": -1,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": true,
        "PortSpecs": null,
        "StdinOnce": true,
        "Tty": true,
        "User": "",
        "Volumes": null,
        "WorkingDir": ""
    },
    "Created": "2015-06-15T23:03:00.258470277Z",
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "CapAdd": null,
        "CapDrop": null,
        "CgroupParent": "",
        "ContainerIDFile": "",
        "CpuShares": 0,
        "CpusetCpus": "",
        "Devices": [],
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": [],
        "Memory": 5242880,
        "MemorySwap": -1,
        "NetworkMode": "bridge",
        "PidMode": "",
        "PortBindings": {},
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "no"
        },
        "SecurityOpt": null,
        "Ulimits": null,
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/72bf21497fa584414b308398971267e472a12fce568d60511417fb8a89fe3320/hostname",
    "HostsPath": "/var/lib/docker/containers/72bf21497fa584414b308398971267e472a12fce568d60511417fb8a89fe3320/hosts",
    "Id": "72bf21497fa584414b308398971267e472a12fce568d60511417fb8a89fe3320",
    "Image": "6d4946999d4fb403f40e151ecbd13cb866da125431eb1df0cdfd4dc72674e3c6",
    "LogPath": "/var/lib/docker/containers/72bf21497fa584414b308398971267e472a12fce568d60511417fb8a89fe3320/72bf21497fa584414b308398971267e472a12fce568d60511417fb8a89fe3320-json.log",
    "MountLabel": "",
    "Name": "/condescending_fermi",
    "NetworkSettings": {
        "Bridge": "docker0",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.22",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "fe80::42:acff:fe11:16",
        "LinkLocalIPv6PrefixLen": 64,
        "MacAddress": "02:42:ac:11:00:16",
        "PortMapping": null,
        "Ports": {}
    },
    "Path": "/bin/bash",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/72bf21497fa584414b308398971267e472a12fce568d60511417fb8a89fe3320/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 23897,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2015-06-15T23:03:00.387429361Z"
    },
    "Volumes": {},
    "VolumesRW": {}
}
]

$ docker inspect 50203efe2cf2
[{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "/bin/bash"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": null,
        "Env": null,
        "ExposedPorts": null,
        "Hostname": "50203efe2cf2",
        "Image": "ubuntu:14.04",
        "Labels": {},
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": true,
        "PortSpecs": null,
        "StdinOnce": true,
        "Tty": true,
        "User": "",
        "Volumes": null,
        "WorkingDir": ""
    },
    "Created": "2015-06-15T23:34:56.469669573Z",
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "CapAdd": null,
        "CapDrop": null,
        "CgroupParent": "",
        "ContainerIDFile": "",
        "CpuShares": 0,
        "CpusetCpus": "",
        "Devices": null,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkMode": "",
        "PidMode": "",
        "PortBindings": null,
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "SecurityOpt": null,
        "Ulimits": null,
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/50203efe2cf228f02317eb123e0d0c297f712bf428e73409c2173152c3c75ad8/hostname",
    "HostsPath": "/var/lib/docker/containers/50203efe2cf228f02317eb123e0d0c297f712bf428e73409c2173152c3c75ad8/hosts",
    "Id": "50203efe2cf228f02317eb123e0d0c297f712bf428e73409c2173152c3c75ad8",
    "Image": "6d4946999d4fb403f40e151ecbd13cb866da125431eb1df0cdfd4dc72674e3c6",
    "LogPath": "/var/lib/docker/containers/50203efe2cf228f02317eb123e0d0c297f712bf428e73409c2173152c3c75ad8/50203efe2cf228f02317eb123e0d0c297f712bf428e73409c2173152c3c75ad8-json.log",
    "MountLabel": "",
    "Name": "/condescending_ardinghelli",
    "NetworkSettings": {
        "Bridge": "docker0",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.24",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "fe80::42:acff:fe11:18",
        "LinkLocalIPv6PrefixLen": 64,
        "MacAddress": "02:42:ac:11:00:18",
        "PortMapping": null,
        "Ports": {}
    },
    "Path": "/bin/bash",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/50203efe2cf228f02317eb123e0d0c297f712bf428e73409c2173152c3c75ad8/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 24822,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2015-06-15T23:35:03.286946229Z"
    },
    "Volumes": {},
    "VolumesRW": {}
}
]
```

**Comment by cpuguy83** [comment] 2015-06-16 01:39
Closing since this is most definitely not a docker issue.
The CLI uses the Docker API.
This is likely an issue with your docker client lib.
Confirmed with a local docker daemon:
`curl -XPOST -H 'Content-Type: application/json' localhost/containers/create -d '{"Image": "busybox", "HostConfig": { "Memory": 5242880 }}'`

**Closed by cpuguy83** 2015-06-16 01:39 UTC

**Comment by Slix** [comment] 2015-06-16 16:32
Edited the issue with curl-based reproduction steps (**without docker-py**). Still failing on my machine.

If you can't reproduce this, I'm thinking this is something particular to my machine or Ubuntu 14.04.1. Maybe it's because my kernel doesn't support swap limits?

**Comment by cpuguy83** [comment] 2015-06-16 16:34
@Slix Could be, but I'd expect CLI and API to behave the same way in that regard.
Maybe you can check the daemon logs on startup? It should throw a warning.

**Comment by Slix** [comment] 2015-06-16 18:29
The daemon does warn me about cgroup swap limits:
```         
WARN[0000] Your kernel does not support cgroup swap limit. 
```

However, there appears to be a **difference in log behaviors** between command-line and HTTP. The "swap limit capabilities" warning does not appear when initiated from HTTP. See missing **WARN**. I'm not sure if this is related to the issue.

Command-line:
```
INFO[10080] POST /v1.18/containers/create?name=cmdline   
INFO[10080] +job create(cmdline)                         
Your kernel does not support swap limit capabilities. Limitation discarded.
INFO[10080] +job log(create, f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe, busybox:latest) 
INFO[10080] -job log(create, f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe, busybox:latest) = OK (0) 
INFO[10080] -job create(cmdline) = OK (0)                
INFO[10080] POST /v1.18/containers/f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe/attach?stderr=1&stdout=1&stream=1 
INFO[10080] +job container_inspect(f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe) 
INFO[10080] -job container_inspect(f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe) = OK (0) 
INFO[10080] POST /v1.18/containers/f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe/start 
INFO[10080] +job start(f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe) 
INFO[10080] +job allocate_interface(f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe) 
INFO[10080] -job allocate_interface(f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe) = OK (0) 
WARN[10080] Your kernel does not support swap limit capabilities. Limitation discarded. 
INFO[10080] +job attach(f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe) 
INFO[10080] +job log(start, f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe, busybox:latest) 
INFO[10080] -job log(start, f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe, busybox:latest) = OK (0) 
INFO[10080] -job start(f3de4d9039060657bece489ea8942cfc9f8fdebc3bb9bafb640472d79763d3fe) = OK (0)
```
HTTP:
```
INFO[10681] POST /v1.18/containers/create?name=fromhttp  
INFO[10681] +job create(fromhttp)                        
INFO[10681] +job log(create, f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a, busybox:latest) 
INFO[10681] -job log(create, f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a, busybox:latest) = OK (0) 
INFO[10681] -job create(fromhttp) = OK (0)               
INFO[10855] POST /v1.18/containers/f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a/attach?stderr=1&stdout=1&stream=1 
INFO[10855] +job container_inspect(f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a) 
INFO[10855] -job container_inspect(f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a) = OK (0) 
INFO[10855] +job attach(f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a) 
INFO[11049] POST /v1.18/containers/f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a/start 
INFO[11049] +job start(f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a) 
INFO[11049] +job allocate_interface(f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a) 
INFO[11049] -job allocate_interface(f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a) = OK (0) 
INFO[11049] +job log(start, f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a, busybox:latest) 
INFO[11049] -job log(start, f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a, busybox:latest) = OK (0) 
INFO[11049] -job start(f3a3a1826c57ef7144410771fb604d6d03eef95bccc46cd39f4dd482e220057a) = OK (0)
```

The latter log was made with:
```sh
$ curl -XPOST -H 'Content-Type: application/json' localhost/v1.18/containers/create?name=fromhttp -d '{
"Image": "busybox",
"HostConfig": { "Memory": 5242880 },
"Cmd": [
    "/bin/sleep",
    "9999999"
]
}'
$ curl -XPOST "localhost/v1.18/containers/IDHERE/attach?stderr=1&stdout=1&stream=1
$ curl -XPOST localhost/v1.18/containers/IDHERE/start
```

**Comment by julien-sarazin** [comment] 2016-05-13 14:43
Hi, 

I'm facing the same issue. I tried different ways to set the limitations, works well with the CLI, same with the standard Remote API, but it does not work with dockerode. I must have missed something.   

I've created a repository that describe my problem.
Would you please take a look to this repository: https://github.com/julien-sarazin/docker-playground.git
And tell me where i'm missing something.

Thanks a lot, for your library and your help!
