### ISSUE TITLE
Docker hangs badly when doing a python install

### ISSUE THREAD

**Issue by waynew** [docker/docker#10025] opened 2015-01-10 17:37 UTC
I have the following dockerfile:

```
# Base python 3.4 build, inspired by
# https://github.com/crosbymichael/python-docker/blob/master/Dockerfile
# Originally from https://github.com/micktwomey/docker-python3.4/blob/master/Dockerfile
FROM ubuntu:14.04
MAINTAINER Wayne Werner <waynejwerner@gmail.com>

RUN echo "deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu trusty main" > /etc/apt/sources.list.d/deadsnakes.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DB82666C

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    python3.4 \
    && apt-get autoremove \
    && apt-get clean

ADD https://github.com/pypa/pip/raw/645180e2714b4ffcf40363a608239e089c9dafab/contrib/get-pip.py /root/get-pip.py
RUN python3.4 /root/get-pip.py
RUN pip3.4 install -U "setuptools"
RUN pip3.4 install -U "pip"
ADD dist/scheduler-0.1.0.tar.gz /scheduler
RUN python3.4 /scheduler/scheduler-0.1.0/setup.py install

#ENTRYPOINT ["/usr/bin/python3.4"]
```

Scheduler consists of the following files:

```
scheduler/Dockerfile
scheduler/setup.py
scheduler/README
scheduler/scheduler/__init__.py
scheduler/scheduler/server.py
scheduler/scripts/scheduler
```

all of the files are empty except setup.py and scripts/scheduler

**setup.py**
```
import os
from setuptools import setup

# Utility function to read the README file.
# Used for the long_description.  It's nice, because now 1) we have a top level
# README file and 2) it's easier to type in the README file than to put a raw
# string in below ...
def read(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()

setup(
    name = "scheduler",
    version = "0.1.0",
    author = "Wayne Werner",
    author_email = "waynejwerner@gmail.com",
    description = ("Breaking docker"),
    url = "",
    packages=['scheduler'],
    scripts=['scripts/scheduler'],
    long_description=read('README'),
    install_requires=['Flask', 
                      'flask-login',
                      'flask-wtf',
                      'sqlalchemy',
                      'click',
                      ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Topic :: Applications",
    ],
)
```

**scripts/scheduler**:
```
#!/usr/bin/env python

import click
import sys
#from scheduler import server

@click.command()
@click.option('--name', default='World', help="Name to greet")
def main(name):
    print("Hey {}!".format(name), sys.executable)


if __name__ == '__main__':
    main()
```

When I run `$ docker build --tag="wayne/scheduler:latest" .` then it gets as far as this:

```
 ---> Running in 64df88c57386
running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python3.4 -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating scheduler.egg-info
writing top-level names to scheduler.egg-info/top_level.txt
writing dependency_links to scheduler.egg-info/dependency_links.txt
writing requirements to scheduler.egg-info/requires.txt
writing scheduler.egg-info/PKG-INFO
writing manifest file 'scheduler.egg-info/SOURCES.txt'
```

And then it hangs - but it's a very *very* busy hang. This is the output of `ps aux | grep scheduler` on my host box:

```
root      5419  0.1  0.0   4452   752 ?        Ss   11:19   0:00 /bin/sh -c python3.4 /scheduler/scheduler-0.1.0/setup.py install
root      5436 96.0  0.6  72396 30296 ?        R    11:19   0:15 python3.4 /scheduler/scheduler-0.1.0/setup.py install
```

The only thing I can do is `kill -9` either of these processes. 

Now, if I skip the `RUN` step and then boot into the box with 

`$ docker run --rm -it wayne/scheduler /bin/bash`

then I can do a `python3.4 setup.py install` just fine.

My host box is Arch Linux.

Let me know if you have any questions!

**Comment by waynew** [comment] 2015-01-10 19:10
As an update - apparently `pip3.4 install scheduler/scheduler-0.1.0` works just fine, which is what I'll be using.

**Comment by jfrazelle** [comment] 2015-01-14 19:37
Closing then as it is a python version issue.

**Closed** 2015-01-14 19:37 UTC

**Comment by Tim-Clifford** [comment] 2015-09-24 20:34
Running into this on Docker 1.6.2 with Python-2:latest using a home rolled package.

**Comment by jseabold** [comment] 2016-01-06 17:44
I can replicate this issue. The above resolution does not suggest that changing Python versions fixed anything. It's the writing of files by setuptools that's causing it, though I don't know why. Sometimes it hangs for me when writing `dependency_links.txt` and sometimes `SOURCES.txt`. Will see if I can investigate further.

**Comment by jseabold** [comment] 2016-01-06 18:20
Haha, ok, the issue is that you're calling setup.py from `/` and distutils does a listdir('.') from the calling directory, so I assume it's walking the entire filesystem. So I guess, don't do that.

https://github.com/python/cpython/blob/master/Lib/distutils/filelist.py#L245

**Comment by waynew** [comment] 2016-01-06 23:48
@jseabold well, that makes sense. And kind of the worst, lol.

I guess the sensible thing to do would be to change the run line to this:

    RUN cd /scheduler/scheduler-0.1.0 && python3.4 setup.py install

**Comment by rayohauno** [comment] 2016-06-29 15:17
It seems I have a similar issue. But, I don't know how to solve it. I am working in my own package. First, I build with
`python setup.py build_ext --inplace`
and everything goes fine. Then, I try to install with
`python setup.py install`
and then, it hangs at
```
running install
running bdist_egg
running egg_info
writing ColoredHRG.egg-info/PKG-INFO
writing top-level names to ColoredHRG.egg-info/top_level.txt
writing dependency_links to ColoredHRG.egg-info/dependency_links.txt
```

**Comment by jseabold** [comment] 2016-06-29 15:20
Does the above not help you? Don't put your package in the root of the image. It will walk the entire directory.

**Comment by rayohauno** [comment] 2016-06-29 15:25
I am sorry, perhaps I made a mistake posting here (I don't have much experience posting). I am not working with docker. I just found this post googling and found my problem is similar to the one reported above. The code above does not make sense in my case. I don't understand why 
`python setup.py install `
search the whole tree (I am calling the python from the virtualenv, as the virtualenv is activated) .

**Comment by jseabold** [comment] 2016-06-29 15:52
I would ask on stackoverlow then. This is a docker issue tracker.

**Comment by habemusne** [comment] 2017-07-31 07:40
I put `pip install -r requirements.txt` in Dockerfile and `docker build` hangs. I restarted docker and then everything is fine

**Comment by mwcm** [comment] 2017-08-03 19:34
getting the exact same `docker build` hang as @habemusne right now

**Comment by kbiernat** [comment] 2017-08-17 13:28
@mwcm did you try restarting docker as suggested?

**Comment by pedro2555** [comment] 2020-09-06 13:43
> @mwcm did you try restarting docker as suggested?

I did.....

**Comment by mwcm** [comment] 2020-09-15 06:08
@pedro2555 was just reporting it, restart worked
