### ISSUE TITLE
Su system error in ubuntu:14.04

### ISSUE THREAD

**Issue by domq** [docker/docker#10642] opened 2015-02-07 21:57 UTC
Moving to reopen #6792, as I'm pretty sure it's not a kernel problem.

```shell
root@cmigevm2:/# useradd foo
root@cmigevm2:/# su -c id foo
su: System error
root@cmigevm2:/# sudo -u foo id
uid=1000(foo) gid=1000(foo) groups=1000(foo)
root@cmigevm2:/# uname -r
3.13.0-44-generic
```
My Dockerfile starts with `FROM ubuntu`

`strace` (from outside the container of course) is of little help in telling what is wrong with `su`.

**Comment by jfrazelle** [comment] 2015-07-10 21:30
are you still able to reproduce this on latest

**Comment by cpuguy83** [comment] 2015-08-17 14:30
Closing since this is both a dup, and not really a valid issue as it is an issue which is host-specific.
If you run with `--pid=host` su will work as expected.
`sudo` should work without `--pid=host`.

**Closed by cpuguy83** 2015-08-17 14:30 UTC
Labels: status/more-info-needed
