### ISSUE TITLE
HOW TO CONNECT SQL docker database engine from another SSMS

### ISSUE THREAD

**Issue by ravindravv** [docker/docker#23928] opened 2016-06-24 09:46 UTC
Hello All,

I have successfully install IIS , .net 3.5, SQL containers successfully. I can able to browse IIS website. Now I am trying to access SQL docker from another sql server by giving my server IP with port number. But I could not able to establish SQL connection . Requesting to all, Could you please let me know how to access the DB from sql management studio by using the container’s IP Address along with the sql authentication credentials stored in the Dockerfile ?

**Comment by unclejack** [comment] 2016-06-24 10:19
Hello @ravindravv 

This issue tracker is dedicated to tracking Docker bugs, proposals and pull requests to make changes to Docker's source code. This issue tracker isn't a general support forum.
Please keep in mind that opening issues to ask questions when getting started will make everyone who contributes to the project spend more time looking at issues.

The documentation found at https://docs.docker.com/ has many examples and use cases; it also explains what the various flags and options do.

This kind of question and general support questions are more adequate for the following:
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.
4) StackOverflow https://stackoverflow.com/questions/tagged/docker

I'm going to close this issue now because the discussion can continue even after the issue is closed. Please feel free to continue the discussion. There's no need to open a new issue on this topic.

**Closed by unclejack** 2016-06-24 10:19 UTC
