### ISSUE TITLE
Issue to mount storage in usb. symlink hostname /bin/dnsdomainname: operation not permitted

### ISSUE THREAD

**Issue by thcavalieri** [docker/docker#32482] opened 2017-04-10 18:56 UTC
Hello,

I'm trying do change the docker storage to point to usb(fat32). I created this file:
/etc/docker/daemon.json
{
	"graph": "/mnt/usb"
}

When I pull some image this issue happens:
failed to register layer: Error processing tar file(exit status 1): symlink hostname /bin/dnsdomainname: operation not permitted

Can someone help me with it?

**Comment by thaJeztah** [comment] 2017-04-10 19:45
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to comment after I closed 👍

**Closed by thaJeztah** 2017-04-10 19:45 UTC
