### ISSUE TITLE
PATH doesn't seem to be loaded when I try to run a command via docker run

### ISSUE THREAD

**Issue by JikkuJose** [docker/docker#17103] opened 2015-10-16 07:24 UTC
I have an image I have built with Ruby in it. I am able to run Ruby commands, `irb` and `install gems` in the image while running by:

    docker run -it jikkujose/apple

I can also do this to list the files in the container:

    docker run -it jikkujose/apple ls

But when I try to run Ruby commands, it fails:

    docker run -it jikkujose/apple ruby -e "puts 'Hello'"

Error: 

    Error response from daemon: Cannot start container c888aa8d2c7510a672608744a69f00c5feda4509742d54ea2896b7ebce76c16d: [8] System error: exec: "ruby": executable file not found in $PATH

It seems like `PATH` variable isn't getting loaded; am I missing something?

**Comment by phemmer** [comment] 2015-10-16 12:27
You are setting the variable in your `.bashrc` file.

See `man bash` and the **Invocation** section:

> An interactive shell is one started without non-option arguments
...
> When an interactive shell that is not a login shell is started, bash reads and executes commands from ~/.bashrc


Also, for help using docker, I would recommend the mailing list, the forums, or irc. The issue tracker is generally for bugs and feature requests.

**Comment by JikkuJose** [comment] 2015-10-16 13:19
I am sorry, I didn't know where to ask. So did you mean sourcing `.bashrc` as the last line in `Dockerfile` should solve this?

**Comment by phemmer** [comment] 2015-10-16 21:16
No, you need to add a `ENV PATH=...` line to your `Dockerfile`.

**Comment by thaJeztah** [comment] 2015-10-17 08:27
thanks @phemmer!

I'm going to close this issue, because this is not a bug, but I think you should be able to resolve your issue with the excellent hints that @phemmer gave above.

**Closed by thaJeztah** 2015-10-17 08:27 UTC

**Comment by JikkuJose** [comment] 2015-10-17 10:22
@thaJeztah sorry to mess the issue tracker. I will find a solutio; But I wasn't using a `Dockerfile` to use your suggestion, anyways thanks @phemmer for your time.

**Comment by thaJeztah** [comment] 2015-10-17 15:19
@JikkuJose no problem!
