### ISSUE TITLE
Windows CLI - Off by one terminal size

### ISSUE THREAD

**Issue by icecrime** [docker/docker#12147] opened 2015-04-07 17:05 UTC
It seems that the buffer wraps one character "too late", see below visual explanation:

![screen shot 2015-04-07 at 10 00 21](https://cloud.githubusercontent.com/assets/1564054/7028822/649e721e-dd0d-11e4-8e02-230558bde72d.png)

Terminal size: `100x52`
Associated API call: `POST /v1.19/containers/ab.../resize?h=52&w=100`

Cf. my earlier comment https://github.com/docker/docker/pull/12127#discussion_r27835726

Ping @ahmetalpbalkan @brendandixon @jfrazelle!

**Comment by ahmetalpbalkan** [comment] 2015-04-07 17:21
@icecrime I can repro this.

When I removed those `+1`s used in `GetWinsize`, it gets rid of those removes the empty lines we get here and there but then it wraps too early now (and obviously gets window size wrong for the `/resize` call. It appears this issue is caused by something else.

**Comment by cpuguy83** [comment] 2015-08-26 20:19
Was this fixed in the windows term re-write?

cc @jhowardmsft

**Comment by jhowardmsft** [comment] 2015-08-26 20:39
Yup. 
![capture](https://cloud.githubusercontent.com/assets/10522484/9505521/ce179cb2-4bf7-11e5-9c2e-abd61d58bf24.JPG)

**Comment by ahmetalpbalkan** [comment] 2015-08-26 20:41
Awesome. :clap:

**Comment by thaJeztah** [comment] 2015-08-26 20:42
Thanks @jhowardmsft, I'll close this one then

**Closed by thaJeztah** 2015-08-26 20:42 UTC
Labels: group/windows, kind/bug
