### ISSUE TITLE
docker failed to start in container

### ISSUE THREAD

**Issue by Mashimiao** [docker/docker#17010] opened 2015-10-14 07:59 UTC
according to https://docs.docker.com/project/set-up-dev-env/, I build my branch's image and run it.
But, the docoker always failed. Please see the following logs:

root@eb1d9acd3ed2:/var/lib/docker/network/files# go version
go version go1.4.3 linux/amd64
root@eb1d9acd3ed2:/var/lib/docker/network/files# docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   30d0144-dirty
 Built:        Wed Oct 14 07:03:00 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
root@eb1d9acd3ed2:/var/lib/docker/network/files# docker daemon -D
DEBU[0000] devicemapper: driver version is 4.31.0       
WARN[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option 
DEBU[0000] Generated prefix: docker-8:6-2244636         
DEBU[0000] devmapper: Checking for existence of the pool docker-8:6-2244636-pool 
DEBU[0000] Pool doesn't exist. Creating it.             
DEBU[0000] [deviceset] loadDeviceFilesOnStart()         
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/base 
DEBU[0000] Skipping file /var/lib/docker/devicemapper/metadata/deviceset-metadata 
DEBU[0000] Skipping file /var/lib/docker/devicemapper/metadata/transaction-metadata 
DEBU[0000] [deviceset] loadDeviceFilesOnStart() END     
DEBU[0000] [deviceset] constructDeviceIDMap()           
DEBU[0000] Added deviceId=1 to DeviceIdMap              
DEBU[0000] [deviceset] constructDeviceIDMap() END       
WARN[0000] Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section. 
DEBU[0000] activateDeviceIfNeeded()                     
DEBU[0000] UUID for device: /dev/mapper/docker-8:6-2244636-base is:9b9f8c07-b95b-4ec2-a7a4-65aaf7b94ebb 
DEBU[0000] [devmapper] deactivateDevice()               
DEBU[0000] [devmapper] removeDevice START(docker-8:6-2244636-base) 
DEBU[0000] [devmapper] removeDevice END(docker-8:6-2244636-base) 
DEBU[0000] [devmapper] deactivateDevice END()           
INFO[0000] [graphdriver] using prior storage driver "devicemapper" 
DEBU[0000] Using graph driver devicemapper              
DEBU[0000] Using default logging driver json-file       
DEBU[0000] Creating images graph                        
DEBU[0000] Restored 0 elements                          
DEBU[0000] Creating repository list                     
INFO[0000] Option DefaultDriver: bridge                 
INFO[0000] Option DefaultNetwork: bridge                
WARN[0000] Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.1.6-201.fc22.x86_64/modules.dep.bin'
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.1.6-201.fc22.x86_64/modules.dep.bin'
, error: exit status 1 
WARN[0000] Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.1.6-201.fc22.x86_64/modules.dep.bin'`, error: exit status 1 
DEBU[0000] Fail to initialize firewalld: Failed to connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: no such file or directory, using raw iptables instead 
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]    
DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[0000] Failed to Initialize Datastore due to globalstore initialization requires a valid configuration. Operating in non-clustered mode 
DEBU[0000] Failed to Initialize Discovery : invalid discovery watcher 
DEBU[0000] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0000] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0000] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
DEBU[0000] Cleaning up old shm/mqueue mounts: done.     
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=30d0144-dirty execdriver=native-0.2 graphdriver=devicemapper version=1.9.0-dev
DEBU[0000] starting clean shutdown of all containers... 
DEBU[0000] [deviceset docker-8:6-2244636] Shutdown()    
DEBU[0000] [devmapper] Shutting down DeviceSet: /var/lib/docker/devicemapper 
DEBU[0000] Unix socket /var/lib/docker/network/files/c84548b3f815a983aadd26d94a9a34370c7b5f09debad678ff3df696b57562ea.sock doesnt exist. cannot accept client connections 
DEBU[0000] [devmapper] deactivateDevice()               
DEBU[0000] [devmapper] deactivateDevice END()           
DEBU[0000] [devmapper] deactivatePool()                 
DEBU[0000] [devmapper] deactivatePool END               
DEBU[0000] [deviceset docker-8:6-2244636] Shutdown() END 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
DEBU[0000] Cleaning up old shm/mqueue mounts: done.     
DEBU[0000] Clean shutdown succeeded

**Comment by coolljt0725** [comment] 2015-10-14 08:46
@Mashimiao  this is caused by #15753  and it's fixed by #16927 
the latest master branch has fixed this

**Comment by cpuguy83** [comment] 2015-10-14 14:37
Yep, closing.
If you re-pull from master you should be fine.

**Closed by cpuguy83** 2015-10-14 14:37 UTC
