### ISSUE TITLE
docker-compose build struggles with with large volumes in build directory

### ISSUE THREAD

**Issue by sllawap** [docker/docker#16671] opened 2015-09-30 06:19 UTC
It seems to be a bottleneck streaming the files to the docker daemon.

I have not yet established whether this has to do with number of files or total size.

Interestingly, this only seems to happen when the volume is in the build directory.

For example:

    $ cat docker-compose.yml
    example:
      build: example
      volumes: [ "./example/volumes/a:/a" ]

    $ find example/volumes
    example/volumes/a/1/a100000
    example/volumes/a/1/a100001
    example/volumes/a/1/a100002
    [snip]

    $ docker-compose build example
    [minutes elapse]
    Building example ...

If we move the directory out of the build folder:

    $ cat docker-compose.yml
    example:
      build: example
      volumes: [ "./other/volumes/a:/a" ]

    $ mv example/volumes other/volumes

    $ find other/volumes
    other/volumes/a/1/a100000
    other/volumes/a/1/a100001
    other/volumes/a/1/a100002
    [snip]

    $ docker-compose build example
    [milliseconds elapse]
    Building example ...

The usual details:

    # docker info
    Containers: 13
    Images: 96
    Storage Driver: overlay
     Backing Filesystem: extfs
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.1.6-coreos-r1
    Operating System: CoreOS 766.3.0
    CPUs: 1
    Total Memory: 3.618 GiB

    # docker version
    Client version: 1.7.1
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 2c2c52b-dirty
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 2c2c52b-dirty
    OS/Arch (server): linux/amd64

I will provide more detail and a reproduction case in the morning.

**Comment by vdemeester** [comment] 2015-09-30 06:44
Hi @sllawap,

It's more or less what's supposed to do. In you first example, the content of your volumes is also in the build context, and so when doing docker-compose built, it will tar it and transfert it to the daemon.. If the content of the volume is big, this would explained the minutes elasping..

The way to fix that, would be to use the `.dockerignore`, but you'll have to check how compose handles/support it though.

**Comment by duglin** [comment] 2015-09-30 11:57
Yup, plus there's some work gong on to move docker build to the CLI which **might** mean we no longer move the build context over to the daemon unless you explicit ask for us to via some 'copy into the container' type of operation, but its still being designed.

Closing because, as @vdemeester said, its basically working as designed.

**Closed by duglin** 2015-09-30 11:57 UTC
