### ISSUE TITLE
docker load doesn't prevent docker pull of the same image in Docker 1.8.3

### ISSUE THREAD

**Issue by ricardobranco777** [docker/docker#17410] opened 2015-10-27 19:26 UTC
Something changed with the handling of images ID on Docker because, previously, I could save an image with "docker save" and load it.  A docker pull of the same image wouldn't waste network I/O.

To quickly reproduce this issue:

```
$ # Stop Docker service
$ sudo service docker stop
docker stop/waiting

$ # Save current Docker graph
$ sudo mv /var/lib/docker /var/lib/docker-

$ # Start Docker daemon (creates a new /var/lib/docker)
$ sudo service docker start
docker start/running, process 14021

$ # Pull Busybox image
$ sudo docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox

ab2b8a86ca6c: Pull complete 
2c5ac3f849df: Pull complete 
Digest: sha256:5551dbdfc48d66734d0f01cafee0952cb6e8eeecd1e2492240bf2fd9640c2279
Status: Downloaded newer image for busybox:latest

$ # Save Busybox image
$ sudo docker save -o busybox.tar busybox

$ # Stop Docker service
$ sudo service docker stop
docker stop/waiting

$ # Remove Docker graph directory
$ sudo rm -rf /var/lib/docker

$ # Start Docker daemon
$ sudo sudo service docker start
docker start/running, process 14161

$ # Load busybox.tar
$ sudo docker load -i busybox.tar

$ # Pull Busybox image
$ sudo docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
91d73071be07: Pull complete 
0efa57931dab: Pull complete 
Digest: sha256:5551dbdfc48d66734d0f01cafee0952cb6e8eeecd1e2492240bf2fd9640c2279
Status: Downloaded newer image for busybox:latest

$ # Verify images
$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
busybox             latest              0efa57931dab        6 days ago          1.113 MB
<none>              <none>              2c5ac3f849df        6 days ago          1.113 MB

$ sudo docker history busybox
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
0efa57931dab        6 days ago          /bin/sh -c #(nop) CMD ["sh"]                    0 B                 
91d73071be07        6 days ago          /bin/sh -c #(nop) ADD file:566aa8660b389e4f82   1.113 MB

$ sudo docker history 2c5ac3f849df
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
2c5ac3f849df        6 days ago          /bin/sh -c #(nop) CMD ["sh"]                    0 B                 
ab2b8a86ca6c        6 days ago          /bin/sh -c #(nop) ADD file:566aa8660b389e4f82   1.113 MB            
```

docker info:
```
Containers: 0
Images: 4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-31-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 15.64 GiB
Name: ighighix
ID: XVRI:CLJT:Q2MB:N27X:YM7W:ZVGA:DHCD:G3XM:QYSX:6ERT:PYTW:JWMX
```

docker version:
```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64
```

uname -a:
```
Linux ighighix 3.19.0-31-generic #36~14.04.1-Ubuntu SMP Thu Oct 8 10:21:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by aaronlehmann** [comment] 2015-10-27 20:51
This change was made intentionally in Docker 1.8.3 to improve `docker pull` security. Docker used to rely on image IDs to know whether it already had the data. Since an attacker can create malicious images with arbitrary IDs, they can force collisions with other images, and force images to wrongly share layers. 1.8.3 fixes this by calculating reliable IDs when it pulls data from a registry. A side effect of this approach is images created with `docker load` and those created from `docker pull` end up with different IDs.

A more comprehensive fix is planned for Docker 1.10. It will use the same ID scheme for `docker pull`, `docker load`, and all other mechanisms.

**Comment by ricardobranco777** [comment] 2015-10-27 22:38
Thanks.  I could confirm that this issue doesn't happen on 1.8.2.  In my setup I should downgrade Docker Engine to 1.8.2 and repopulate the Registry to avoid this problem.

**Comment by thaJeztah** [comment] 2015-10-27 23:12
Thanks for the explanation @aaronlehmann !

I'm going to close this issue because this is not a bug, but thanks for reporting @ricardobranco777, it's appreciated!

**Closed by thaJeztah** 2015-10-27 23:12 UTC

**Comment by mrlamroger** [comment] 2016-01-21 01:28
@thaJeztah I noticed 
```
Use content-addressable storage for images and layers #17924
Note that a migration is performed the first time docker is run; it can take a significant amount of time depending on the number of images and containers present.
Images no longer depend on the parent chain but contain a list of layer references.
docker load/docker save tarballs now also contain content-addressable image configurations.
```
is included in the 1.10 rc release notes. Does this mean we will be able to `docker save`, `docker load` and not need to redownload similar images?

**Comment by ricardobranco777** [comment] 2016-02-04 22:58
This issue is not fixed in Docker 1.10

**Comment by tonistiigi** [comment] 2016-02-05 00:55
@mrlamroger `docker save` and `docker load` now produce the same images that both have IDs that are the checksums of their data. So there will be no duplicate images. If you only have the loaded version, this only contained the uncompressed data and we can't match it with a compressed blob in the registry. So you would have to pull once and we would add a mapping from compressed to uncompressed to skip further downloads. If your image is pushed with `v1.10` to registry `v2.3.0` (released also today) then we already store the uncompressed checksum in manifest and all downloads are always skipped.

**Comment by mrlamroger** [comment] 2016-02-05 17:51
Awesome. Thanks @tonistiigi !
