### ISSUE TITLE
restart policy exponential backoff never resets

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#22283] opened 2016-04-24 19:13 UTC
I have a container with a restart policy ("always") and an application that runs for X seconds, then it dies. Every time it dies docker takes 2x longer to be restarted even if it's been running happily for a day. I expected the exponential backoff to reset if the application starts up successfully. This might require some sort of health check though. I'm not sure what the best solution to this issue is, but the restart policies are really impractical for actually keeping an app going if it tends to crash randomly sometimes.

**Output of `docker version`:**

```
Client:
 Version:      1.11.0-rc5
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   6178547
 Built:        Tue Apr 12 06:13:18 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc5
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   6178547
 Built:        Tue Apr 12 06:13:18 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 14
 Running: 10
 Paused: 0
 Stopped: 4
Images: 912
Server Version: 1.11.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1042
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.5-1-docker-aufs
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.709 GiB
Name: compooter
ID: GKSI:YHZC:YPNI:PAGO:EYPD:AYME:K6BY:BAIH:EBKQ:SOAK:WUFP:6MJM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 50
 Goroutines: 125
 System Time: 2016-04-24T12:10:48.33852432-07:00
 EventsListeners: 1
Username: viktorstanchev
Registry: https://index.docker.io/v1/
Cluster store: etcd://172.17.0.1:12379
Cluster advertise: 172.17.0.1:12376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine

**Steps to reproduce the issue:**
1. docker run --restart=always --name weee -d alpine sh -c 'sleep 5; exit 1'
2. watch -n 0.1 docker ps
3. 

**Describe the results you received:**
The exponential backoff is always slowing down restarts for no reason

**Describe the results you expected:**
The exponential backoff should reset if the application has started successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-04-24 19:55
duplicate of https://github.com/docker/docker/issues/22159, and https://github.com/docker/docker/issues/22113, and will be fixed by https://github.com/docker/docker/pull/22125

I'll close this, but let me know if it's not a duplicate

**Closed by thaJeztah** 2016-04-24 19:55 UTC
