### ISSUE TITLE
Error response from daemon: Cannot start container c4262f07e8511b8fd988cc5f61072c9c5141dd86afeef09c80760108e5aa302b: device or resource busy

### ISSUE THREAD

**Issue by themooer1** [docker/docker#14541] opened 2015-07-10 23:16 UTC
Description of problem:  I was running an openmediavault server and I thought that it would be a nice platform for docker also, so I installed it a per the instructions on this page.(http://docs.docker.com/linux/started/).  After following all of the steps exactly I went to execute "docker run hello-world", and while it seemed to download fine it gives me the below error.

---
Error response from daemon: Cannot start container c4262f07e8511b8fd988cc5f61072c9c5141dd86afeef09c80760108e5aa302b: device or resource busy
---

`docker version`:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

`docker info`:
Containers: 6
Images: 2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.2.0-4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 4
Total Memory: 3.627 GiB
Name: SuperServer
ID: ELVA:EM5W:ZA3Q:DDLP:H73K:A2MU:PGNH:BNLY:AMGD:RTVA:JO4Y:DPBE
WARNING: No memory limit support
WARNING: No swap limit support

`uname -a`:
Linux SuperServer 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u2 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.): Physical, AMD PhenomII Desktop

How reproducible:  As said above I did not do anything outside of the initial setup and a basic test.  Other than openmediavault/nginx itself I am running and AFP server, an Apache2 server on port 8000, a tftp server, and a Samba server.

Steps to Reproduce:  I simply followed the tutorial on the step where you attempt to run the hello-world docker program it fails.

Actual Results:
Error response from daemon: Cannot start container c4262f07e8511b8fd988cc5f61072c9c5141dd86afeef09c80760108e5aa302b: device or resource busy

Expected Results: No error and the hello-world package to proceed normally

Additional info:

**Comment by hqhq** [comment] 2015-07-13 01:24
dup of https://github.com/docker/docker/issues/14540 ?

**Comment by thaJeztah** [comment] 2015-07-13 07:08
Yes, or very close to that issue.

I'm going to close this issue as a duplicate of https://github.com/docker/docker/issues/14540. Please read the comment on that issue; https://github.com/docker/docker/issues/14540#issuecomment-120549968 for more info

**Closed by thaJeztah** 2015-07-13 07:08 UTC
