### ISSUE TITLE
[1.10-rc1]  --ip does not work with bridge network

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19505] opened 2016-01-20 18:26 UTC
Running the below gives me an error saying `network default not found`

```
docker run -it --ip 1.1.1.1 ubuntu
docker: Error response from daemon: network default not found.
```

Here's my networks

```
docker network ls
NETWORK ID          NAME                DRIVER
15ba85a9d9de        host                host                
e44d9e10357d        foo                 bridge              
5b8f7bc8d142        bridge              bridge              
d43bbd8245e5        none                null
```

**Comment by aboch** [comment] 2016-01-20 18:32
@ibuildthecloud 
Besides the error you reported (it is a genuine issue), please be aware the `--ip` and `--ipv6` options are accepted only when container will run on networks which subnet cannot change across daemon and host restart.
This means you will be able to specify the IP addresses only for containers running on user-defined networks which were created with the `--subnet` option.

**Comment by thaJeztah** [comment] 2016-01-20 18:33
Yes, the incorrect error message is a duplicate of https://github.com/docker/docker/issues/19417, the error should be: 


    docker: Error response from daemon: User specified IP address is supported on user defined networks only.

**Comment by ibuildthecloud** [comment] 2016-01-20 18:41
@aboch Yeah, i just figured that out.  Why would the subnet change on restart for a network.  That seems a bit odd.  So the only way to use `--ip` is to do `network create --subnet ...`?

**Comment by mavenugo** [comment] 2016-01-20 18:46
@ibuildthecloud because of this : https://github.com/docker/docker/pull/19001#issuecomment-168227418

**Comment by aboch** [comment] 2016-01-20 18:51
@ibuildthecloud 
Also because, regarding the user-defined networks, there is no guarantee that after a host reboot docker will recreate them in the same order they were created during the previous daemon instance, therefore picking the same subnet from the predefined list.

So the only way is to create them with the `--subnet` option.

> So the only way to use --ip is to do network create --subnet ...?

Yes

**Comment by tiborvass** [comment] 2016-01-20 19:11
Closing as duplicate of #19417 

@ibuildthecloud speak up if you disagree

**Closed by tiborvass** 2016-01-20 19:11 UTC
