### ISSUE TITLE
du fails with overlay storage backend

### ISSUE THREAD

**Issue by orzel** [docker/docker#11362] opened 2015-03-13 04:42 UTC
I have an image whose size is roughly 800M. I start a container on it using
`docker run -i -t <myimage>`
Then i do `du -shx /` inside.

On one system, I use the btrfs storage backend and i have
`44c68d5b5ac4 / # du -shx /`
`789M /`

On another one, using the overlay storage backend, I have :
`e38c8dc904fd / # du -shx /`
`11M     /`

It's really weird, as ls -l does report the right size.

**Comment by cpuguy83** [comment] 2015-03-13 14:58
I cannot reproduce this.

**Comment by orzel** [comment] 2015-03-13 15:06
On one failing system :

orzel@berlioz /home/orzel% docker info                                                                                                                        
Containers: 24                                                                                                                                                
Images: 69                                                                                                                                                    
Storage Driver: overlay                                                                                                                                       
 Backing Filesystem: extfs                                                                                                                                    
Execution Driver: native-0.2
Kernel Version: 3.19.1
Operating System: Gentoo/Linux
CPUs: 4
Total Memory: 11.22 GiB
Name: berlioz
ID: 5OJK:MJFE:GNJB:2VOX:Z27H:BVXL:HPMB:N7AP:NYOO:5AW6:6JQX:XSGG
Username: orzel
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

orzel@berlioz /home/orzel% docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.2
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.2
Git commit (server): a8a31ef

**Comment by jfrazelle** [comment] 2015-03-27 17:59
you can download the binaries here
https://github.com/docker/docker/pull/11635#issuecomment-86198821

**Comment by orzel** [comment] 2015-04-24 12:20
Tested with 1.6 final, the problem is still there:
% docker run -t -i orzel/php-5.5
184ae3b63dba / # dju -^C
184ae3b63dba / # du -shx / 
12M     /

The image contains a full gentoo install among other thing.
The image size as reported by 'docke images' is 758 MB.

@GordonTheTurtle which change/ticket did you think would solve the problem ?

**Comment by nixun** [comment] 2015-04-28 07:35
is that a parameter problem for du? In my experiment:
root@cb3492630815:/# du -mhs /
209M    .
root@cb3492630815:/# du -shx /
1.5M    /

it looks different...

**Comment by orzel** [comment] 2015-04-28 11:56
At least you can reproduce it, cpuguy83 said he could not.
Nice catch though, the problem seems related to '-x', which is "skip directories on different file systems". 

But still the whole / is supposed to be one filesystem, isn't it ?

**Comment by cpuguy83** [comment] 2015-07-22 14:32
Closing since indeed `/` is not necessarily 1 filesystem and works the same way on other graph drivers as well (tested specifically with aufs).

**Closed by cpuguy83** 2015-07-22 14:32 UTC
Labels: system/overlay
