### ISSUE TITLE
Fresh install on OS X 10.10.5 fails

### ISSUE THREAD

**Issue by hlship** [docker/docker#16685] opened 2015-09-30 21:58 UTC
Just moved to a fresh new computer, running OS X 10.10.5.

Download Docker Toolbox 1.8.2c and performed the install.

Ran Kitematic, which spent some time setting up the Docker machine, but hung at 99%.

```
L-SB861GQG8W-M:~ hship$ docker ps
Get http:///var/run/docker.sock/v1.20/containers/json: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
L-SB861GQG8W-M:~ hship$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
L-SB861GQG8W-M:~ hship$
```

and

```
L-SB861GQG8W-M:~ hship$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default            virtualbox   Running   tcp://192.168.99.100:2376
L-SB861GQG8W-M:~ hship$
```

I killed Kitematic, and ran it again. It offered to delete the prior VM and create a new one.

Again, hung at 99% with same results as above.

**Comment by hlship** [comment] 2015-09-30 21:59
```
L-SB861GQG8W-M:~ hship$ ls -la /var/run/
total 104
drwxrwxr-x  33 root  daemon  1122 Sep 30 14:49 .
drwxr-xr-x  26 root  wheel    884 Sep 24 12:08 ..
dr-x------   2 root  wheel     68 Sep 29 11:13 .vfs_rsrc_streams_0x23c05b367aa928ab0
-rw-r--r--   1 root  daemon     6 Sep 30 14:49 appfwd.pid
-rw-------   1 root  daemon     0 Sep 28 13:55 automount.initialized
----------   1 root  daemon     0 Sep 28 13:55 com.apple.WindowServer.didRunThisBoot
-r--------   1 root  daemon     0 Sep 28 13:55 com.apple.loginwindow.didRunThisBoot
-rw-r--r--   1 root  daemon     0 Sep 28 16:15 com.apple.softwareupdate.availableupdatesupdated
srwxrwxrwx   1 root  daemon     0 Sep 28 13:55 cupsd
drwxr-xr-x   6 root  daemon   204 Sep 28 13:55 diagnosticd
-rw-r--r--   1 root  daemon     3 Sep 28 13:55 diskarbitrationd.pid
-rw-r--r--   1 root  daemon     6 Sep 29 13:24 hdiejectd.pid
drwx------   2 root  admin     68 Sep 28 13:55 jamf
-rw-r--r--   1 root  daemon     2 Sep 28 13:55 kdc.pid
srw-rw-rw-   1 root  daemon     0 Sep 28 13:55 mDNSResponder
drwx------   3 root  daemon   102 Sep 29 11:13 mds
-rw-r--r--   1 root  daemon     3 Sep 28 13:55 mds.pid
-rw-r--r--   1 root  daemon     3 Sep 28 13:55 ntpd.pid
srwxrwxrwx   1 root  daemon     0 Sep 28 13:55 portmap.socket
srwxrwxrwx   1 root  daemon     0 Sep 28 13:56 pppconfd
drwxr-xr-x   4 root  daemon   136 Sep 28 17:43 racoon
-rw-r--r--   1 root  daemon     5 Sep 28 17:43 racoon.pid
-rw-r--r--   1 root  daemon   417 Sep 30 12:53 resolv.conf
-rw-r--r--   1 root  daemon    55 Sep 28 13:55 sntp.log
-r--------   1 root  daemon     0 Sep 28 13:55 socketfilterfw.launchd
srw-rw-rw-   1 root  daemon     0 Sep 28 13:55 syslog
-rw-r--r--@  1 root  daemon     3 Sep 28 13:55 syslog.pid
-r--r--r--   1 root  daemon     0 Sep 28 13:55 systemkeychaincheck.done
srw-rw-rw-   1 root  daemon     0 Sep 28 13:55 systemkeychaincheck.socket
srwxrwxrwx   1 root  daemon     0 Sep 28 13:55 usbmuxd
-rw-r--r--@  1 root  daemon  6280 Sep 30 14:49 utmpx
-rw-r--r--   1 root  daemon     3 Sep 28 13:55 vpnagentd.pid
srw-------   1 root  daemon     0 Sep 28 13:55 vpncontrol.sock
```

**Comment by hlship** [comment] 2015-09-30 22:12
Trying a reboot right now ...

Going through the "delete vm and recreate it" cycle again.

It makes it past 100%, allows me to create a Docker container (from Kitematic), but I still get the same error when I run "docker ps".

**Comment by hlship** [comment] 2015-09-30 22:17
I think the restart of my MacBookPro fixed half the problem, and https://github.com/docker/docker/issues/16479#issue-107688329 fixed the other half.

**Comment by ElaineRichards** [comment] 2015-09-30 22:32
Same thing here and the restart did not help:

Here's screen output. I did replace the corporate identification in the output (my host name) with (REDACTED). I took no other liberties.

bash-3.2$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
bash-3.2$ exit
exit

Script done, output file is dockerproblem
(REDACTED)-C02LRJ57FD57:~ elaine_richards$ !!
script dockerproblem
Script started, output file is dockerproblem
bash-3.2$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
bash-3.2$ docker info
Get http:///var/run/docker.sock/v1.20/info: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
bash-3.2$ uname -a
Darwin (REDACTED)-C02LRJ57FD57 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64


Steps to reproduce the issue:
1. Go to the docker site and follow the instructions in the tutorial to the letter.
2. Have to go to github to solve the first bug (mentioned in this thread) so I can start
3. Try to do docker ps , thusly
bash-3.2$ docker ps
Get http:///var/run/docker.sock/v1.20/containers/json: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
bash-3.2$ 
4. Go to github, find this very same article and reboot my MacBookPro in the hopes that it solves the problem.
5. Be disappointed and file this bug with the screen output above.

The results I received are outlined in ample detail above.
The results I expected were to show the status of my docker containers as shown in the tutorial.

Question: Is this really a valid URL? http:///var/run/docker.sock/v1.20/containers/json It looks like it's missing something, like, oh, a hostname or IP number.

Also the file /var/run/docker.sock does not exist on my Macbook. What steps not outlined in the tutorial would put this file on my computer?

**Comment by calavera** [comment] 2015-09-30 23:29
Thanks for the report. It looks like you're having issues with https://github.com/docker/toolbox. Unfortunately, the team that develops the toolbox doesn't check the issues in this repo very often. I think you'll get better answers if you redirect your questions there.

Sorry for making you moving all this, but I'm going to close this issue. I really appreciate that you took your time giving good information about your problem.

**Closed by calavera** 2015-09-30 23:29 UTC
