### ISSUE TITLE
Registry mirrors config loss when docker update

### ISSUE THREAD

**Issue by fewspider** [docker/docker#31838] opened 2017-03-15 05:42 UTC
```
Version 17.03.0-ce-mac2 (15654)
Channel: stable
1d7d97bbbd
```
![2017-03-15 13 40 55](https://cloud.githubusercontent.com/assets/3256161/23935137/1465819c-0985-11e7-9738-3ad77bf3343d.png)

**Comment by vdemeester** [comment] 2017-03-15 09:32
@fewspider I think the issue should belong to https://github.com/docker/for-mac/ 👼 
/cc @jeanlaurent @ebriney

**Comment by djs55** [comment] 2017-03-15 09:50
I believe this is a duplicate of https://github.com/docker/for-mac/issues/1354

The fix is in master and so future upgrades shouldn't have this problem -- I'm sorry for the inconvenience. Thanks for your report!

**Comment by thaJeztah** [comment] 2017-03-15 10:08
Let me go ahead and close this one, as we have https://github.com/docker/for-mac/issues/1354 for tracking

**Closed by thaJeztah** 2017-03-15 10:08 UTC
Labels: kind/bug, platform/mac

**Comment by fewspider** [comment] 2017-03-16 01:35
thanks
