### ISSUE TITLE
NetworkSettings.IPAddress can only obtain ip addr from default bridge but not user-defined

### ISSUE THREAD

**Issue by wenchma** [docker/docker#18563] opened 2015-12-10 07:19 UTC
**Description of problem**:

When run `docker inspect -f '{{json .NetworkSettings.IPAddress}}' ...` , it can nly obtain ip addr from default bridge but not user-defined network.
Actually, the containers within user-defined network  have ip addresses.

**Steps to reproduce**:

    $ docker run -itd --name test1 --net net1 busybox sh
    6ab8c8a2663ba31a54ac50bdeb9f8c0fefddfc765e058d0ab194783ec1d6c75c
    $ docker run -itd --name test2 --net net1 busybox sh
    e57b4bade6949458872382ca8853804bde6680a449cb050cb6ef5ed184205e2d
    docker run -itd --name test3 busybox sh
    c5c9c42c4a37cd6085fd47a708769f709d0dc991ef666d38efafcc7f386c9637
    docker inspect -f '{{json .NetworkSettings.IPAddress}}' test1 test2 test3
    ""
    ""
    "172.18.0.2"

`docker version`

        Client:
	 Version:      1.9.1
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   a34a1d5
	 Built:        Fri Nov 20 13:12:04 UTC 2015
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.9.1
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   a34a1d5
	 Built:        Fri Nov 20 13:12:04 UTC 2015
	 OS/Arch:      linux/amd64

`docker info`

        Containers: 21
	Images: 82
	Server Version: 1.9.1
	Storage Driver: aufs
	 Root Dir: /var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 124
	 Dirperm1 Supported: false
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.13.0-43-generic
	Operating System: Ubuntu 14.04.1 LTS
	CPUs: 4
	Total Memory: 15.67 GiB
	Name: docker
	ID: UT5D:M5ZY:IEXQ:6LCU:YX6J:ZMWM:BLNJ:MTXH:PRHO:ETVF:3FHH:6LC4
	WARNING: No swap limit support

`uname -a`

    Linux docker 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):OpenStack Cloud instance

**Comment by coolljt0725** [comment] 2015-12-10 08:08
@wenchma  You should use `docker inspect -f '{{.NetworkSettings.Networks.net1.IPAddress}}` to get the user defined network ip address

**Comment by wenchma** [comment] 2015-12-10 08:24
@coolljt0725 yep, you are right, but  NetworkSettings.Networks also has the default network info, I think it is duplicated with NetworkSettings.IPAddress. wdyt ?

**Comment by coolljt0725** [comment] 2015-12-10 08:33
@wenchma  It's used for backward compatibility.

**Comment by thaJeztah** [comment] 2015-12-10 12:58
Correct, these `NetworkSettings.IPAddress` is only there for backwards compatibility. Because the "old" networking only propagated this with the "bridge"/"default" network, we will only use that information. The `NetworkSettings.IPAddress` field will be removed in a future version, so you should use the new `NetworkSettings.Networks` for inspecting to be future-proof.

See this PR for more information; https://github.com/docker/docker/pull/17538

I'm going to close this issue, because this is not a bug, but thanks for reporting @wenchma!

**Closed by thaJeztah** 2015-12-10 12:58 UTC

**Comment by wenchma** [comment] 2015-12-10 13:49
@thaJeztah got it, thanks for your explanation :+1:

**Comment by thaJeztah** [comment] 2015-12-10 14:08
@wenchma you're welcome, thanks for paying attention, it could've been a bug.
