### ISSUE TITLE
service update --image needs force option

### ISSUE THREAD

**Issue by BryanHunt** [docker/docker#27264] opened 2016-10-10 22:06 UTC
We have two swarms set up: one for staging and one for production.  When we do a release build, we build an image and automatically deploy it to staging using `service update --image`.  This works fine until you find a problem on staging and need to re-build the image.  The image gets tagged with the same tag as the previous build and `service update --image` is a no-op.  This problem only occurs on staging since we are trying to qualify the release build.  Once the release build is deployed on production, it requires a new tag for another deploy to production.  Having some way to force the pull of the new image would make automating multiple release builds a whole lot easier.

**Comment by thaJeztah** [comment] 2016-10-10 22:14
@BryanHunt thanks for reporting. This is a duplicate of https://github.com/docker/docker/issues/24066, please subscribe to that issue to keep up to date on that issue

**Closed by thaJeztah** 2016-10-10 22:14 UTC
