### ISSUE TITLE
Docker cannot pull nginx

### ISSUE THREAD

**Issue by dbrgn** [docker/docker#16300] opened 2015-09-15 11:24 UTC
Description of problem:

When pulling the nginx image, I always get the message "Layer already being pulled by another client. Waiting.", even after restarting the docker daemon or the entire server.

```
$ sudo service docker restart
docker stop/waiting
docker start/running, process 5349
ubuntu@ip-172-31-11-248:~$ docker images -a -q | wc -l
0
ubuntu@ip-172-31-11-248:~$ docker pull nginx
Using default tag: latest
latest: Pulling from library/nginx
843e2bded498: Download complete  ============================================>] 51.36 MB/51.36 MB
8c00acfb0175: Download complete  ============================================>]     32 B/32 B
426ac73b867e: Download complete  ============================================>]     32 B/32 B
d6c6bbd63f57: Download complete  ============================================>] 2.232 kB/2.232 kB
4ac684e3f295: Download complete  ============================================>]    245 B/245 B
93f81de2705a: Download complete  ============================================>]     32 B/32 B
3a6a1b71b6e0: Download complete  ============================================>] 3.385 MB/3.385 MB
4f7e3e7c2546: Download complete  ============================================>]    173 B/173 B
b0d40bad0b2b: Download complete  ============================================>]    172 B/172 B
bfd040d9aed8: Download complete  ============================================>]     32 B/32 B
cc72ca035672: Download complete  ============================================>]     32 B/32 B
0b354d33906d: Download complete  ============================================>]     32 B/32 B
Pulling repository docker.io/library/nginx
0b354d33906d: Layer already being pulled by another client. Waiting. 
```

As you can see, the image ID on the last line is the same as the one on the previous (successful) line. To me it looks like some kind of deadlock situation, it tries to re-download the same image again, but can't because it already did.

`docker version`:

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-202:80-4571139-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.099 GB
 Data Space Total: 107.4 GB
 Data Space Available: 106.3 GB
 Metadata Space Used: 1.266 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /mnt/data/docker/devicemapper/devicemapper/data
 Metadata loop file: /mnt/data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-172-31-11-248
ID: HAFV:XGUP:6BS2:OQXH:5YNP:2MKK:V3UW:UNW6:YKVO:UNCZ:XVVN:KAMB
WARNING: No swap limit support
```

`uname -a`:

```
Linux ip-172-31-11-248 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.): EC2 instance on Amazon AWS

How reproducible:

I cannot reproduce this issue on my local dev machine (Docker version 1.8.1, build d12ea79).

Steps to Reproduce:
1. `docker pull nginx`
2. Wait

Actual Results:

The pull gets stuck with the error message `Layer already being pulled by another client. Waiting.`.

Expected Results:

It works.

**Comment by cpuguy83** [comment] 2015-09-15 12:40
ping @stevvooe @aaronlehmann Looks like there's still an issue with layer pulls in 1.8.2

**Comment by aaronlehmann** [comment] 2015-09-15 16:38
@tonistiigi: do you think https://github.com/docker/docker/pull/15728 would fix this?

I thought this had been included in 1.8.2, but I don't see it in the 1.8.2 tag.

**Comment by tonistiigi** [comment] 2015-09-15 17:55
@aaronlehmann not sure, hard to figure out what is going on in this case by the client output only. `Pulling repository docker.io/library/nginx` line shoud mean its falling back to 'v1'. That fix was not included in `1.8.2` because it wasn't a regression.

@dbrgn Any chance you can send us the daemon debug log? Or is there a way to reproduce it after a clean daemon restart?

**Comment by tonistiigi** [comment] 2015-09-15 21:27
This should be fixed in master with #15545

**Comment by dbrgn** [comment] 2015-09-16 08:05
Here's the debug log:

```
DEBU[0022] Calling POST /images/create                  
INFO[0022] POST /v1.20/images/create?fromImage=nginx%3Alatest 
DEBU[0022] Trying to pull nginx from https://registry-1.docker.io v2 
DEBU[0023] Fetched 1 base graphs at 2015-09-16 10:02:44.201632216 +0200 CEST 
DEBU[0023] Reloaded graph with 3 grants expiring at 2017-03-22 19:04:46.713978458 +0000 UTC 
DEBU[0023] Pulling tag from V2 registry: "latest"       
DEBU[0024] Key check result: verified                   
INFO[0024] Image manifest for nginx:latest has been verified 
DEBU[0024] pulling blob "sha256:f8efbffe7b954b520805da80ce0cce94e3834482c384c25c8851db98696e7f70" to 843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba 
DEBU[0024] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to 8c00acfb017549e44d28098762c3e6296872a1ca9b90385855f1019d84bb0dac 
DEBU[0024] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to 426ac73b867e7b17208d55c2bcc6ba9bd81ae4aff1ad79106e63fc94d783f27f 
DEBU[0024] pulling blob "sha256:c2cdaa18ccc4d1b51ea91441fc4ef3dee35b553f5fa07ca6fc4d1726e5b7957d" to d6c6bbd63f57240b4d7a3714f032004b1ed0aa1b9761778f9a2a8632e0c5efd1 
DEBU[0024] pulling blob "sha256:84756f2904cc14c1f03955a70d60565049314ba489d08ccd2a110b80df7ff92b" to 4ac684e3f295443f69e92c60768b1052ded4aac3a54466c2debf66de35a479e9 
DEBU[0024] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to 93f81de2705a3caf7ffd22347c5768b5169c6d037e3867825a4ab7cdd9a7de99 
DEBU[0024] pulling blob "sha256:647f1544775d424618d5ed76003ecc6930ed944e265471dd83f84a5c12f8a6b9" to 3a6a1b71b6e021df3abda9f223b016a8bc018c27785530d4af69ada52cac404a 
DEBU[0024] pulling blob "sha256:8ef57435642445a15ecde7c46bcd3e83e32e3b7ee50f57a2a9ad4105f37614cc" to 4f7e3e7c25464989f847bb9a1d1f3d4c479d12137b44ed5c8b8d83bcf67f4d4b 
DEBU[0024] pulling blob "sha256:4fd310f87ecb9c655531f7b41bc6c2967974367c3b09357ca59a14d51cbd0112" to b0d40bad0b2b521174cf3ee2f4e74d889561a7c5e2c9c85167978de239bc1c97 
DEBU[0024] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to bfd040d9aed8c694585cfa02bb711f8a93f9fd1d6c8920b89b0030b2017c0b5b 
DEBU[0024] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to cc72ca0356723a8008c5e8fe0118700aee1153930e16877560db58a0121757f0 
DEBU[0024] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to 0b354d33906d30ac52d2817ea770ddce18c7531e58b5b3ca0ae78873f5d2e207 
DEBU[0025] Downloaded 93f81de2705a3caf7ffd22347c5768b5169c6d037e3867825a4ab7cdd9a7de99 to tempfile /mnt/data/docker/tmp/GetImageBlob168270817 
DEBU[0025] Downloaded 4ac684e3f295443f69e92c60768b1052ded4aac3a54466c2debf66de35a479e9 to tempfile /mnt/data/docker/tmp/GetImageBlob817977866 
DEBU[0025] Downloaded cc72ca0356723a8008c5e8fe0118700aee1153930e16877560db58a0121757f0 to tempfile /mnt/data/docker/tmp/GetImageBlob655398336 
DEBU[0025] Downloaded 8c00acfb017549e44d28098762c3e6296872a1ca9b90385855f1019d84bb0dac to tempfile /mnt/data/docker/tmp/GetImageBlob034366301 
DEBU[0025] Downloaded d6c6bbd63f57240b4d7a3714f032004b1ed0aa1b9761778f9a2a8632e0c5efd1 to tempfile /mnt/data/docker/tmp/GetImageBlob850110359 
DEBU[0025] Downloaded 4f7e3e7c25464989f847bb9a1d1f3d4c479d12137b44ed5c8b8d83bcf67f4d4b to tempfile /mnt/data/docker/tmp/GetImageBlob578470075 
DEBU[0025] Downloaded bfd040d9aed8c694585cfa02bb711f8a93f9fd1d6c8920b89b0030b2017c0b5b to tempfile /mnt/data/docker/tmp/GetImageBlob897090213 
DEBU[0025] Downloaded 0b354d33906d30ac52d2817ea770ddce18c7531e58b5b3ca0ae78873f5d2e207 to tempfile /mnt/data/docker/tmp/GetImageBlob940983327 
DEBU[0025] Downloaded b0d40bad0b2b521174cf3ee2f4e74d889561a7c5e2c9c85167978de239bc1c97 to tempfile /mnt/data/docker/tmp/GetImageBlob456339166 
DEBU[0025] Downloaded 426ac73b867e7b17208d55c2bcc6ba9bd81ae4aff1ad79106e63fc94d783f27f to tempfile /mnt/data/docker/tmp/GetImageBlob120195352 
DEBU[0026] Downloaded 3a6a1b71b6e021df3abda9f223b016a8bc018c27785530d4af69ada52cac404a to tempfile /mnt/data/docker/tmp/GetImageBlob041364940 
DEBU[0028] Downloaded 843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba to tempfile /mnt/data/docker/tmp/GetImageBlob911818870 
DEBU[0028] [deviceset] AddDevice(hash=843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba basehash=) 
DEBU[0028] registerDevice(387, 843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba) 
DEBU[0028] [deviceset] AddDevice(hash=843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba basehash=) END 
DEBU[0028] activateDeviceIfNeeded(843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba) 
DEBU[0028] activateDeviceIfNeeded(843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba) 
DEBU[0030] [devmapper] removeDevice START(docker-202:80-4571139-843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba) 
DEBU[0030] [devmapper] removeDevice END(docker-202:80-4571139-843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba) 
DEBU[0030] unregisterDevice(387, 843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba) 
DEBU[0030] Error trying v2 registry: Error mounting '/dev/mapper/docker-202:80-4571139-843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba' on '/mnt/data/docker/devicemapper/mnt/843e2bded49837e4846422f3a82a67be3ccc46c3e636e03d8d946c57564468ba': invalid argument 
DEBU[0030] Trying to pull nginx from https://index.docker.io v1 
ERRO[0030] error copying from layer download progress reader: download canceled 
DEBU[0030] Fetched 1 base graphs at 2015-09-16 10:02:51.308436233 +0200 CEST 
DEBU[0030] hostDir: /etc/docker/certs.d/docker.io       
DEBU[0030] [registry] Calling GET https://index.docker.io/v1/repositories/library/nginx/images 
DEBU[0030] Reloaded graph with 3 grants expiring at 2017-03-22 19:04:46.713978458 +0000 UTC 
DEBU[0030] Retrieving the tag list                      
DEBU[0031] Got status code 200 from https://registry-1.docker.io/v1/repositories/library/nginx/tags/latest 
DEBU[0031] Registering tags                             
```

**Comment by unclejack** [comment] 2016-01-03 10:44
I'll close this now since it seems to be fixed now. Please comment if this is still an issue with the latest release.

**Closed by unclejack** 2016-01-03 10:44 UTC
Labels: group/distribution
