### ISSUE TITLE
Can't install httpd on fedora (cpio: cap_set_file), fixed somewhere or not?

### ISSUE THREAD

**Issue by jamshid** [docker/docker#8966] opened 2014-11-05 00:47 UTC
I see some references to this being fixed in either docker (https://github.com/docker/docker/issues/5928) or by redhat/fedora https://major.io/2014/03/26/docker-trusted-builds-and-fedora-20/, but it's still failing for me.

I'm using docker 1.3.1 with boot2docker on oSX. Is there a workaround, or some magic I should be using to avoid this?

```
$ docker run -ti fedora bash
[root@1aaa13234c91 /]# yum install -y httpd
...
  Installing : httpd-2.4.10-1.fc20.x86_64                                                                                                                                                       6/6 
Error unpacking rpm package httpd-2.4.10-1.fc20.x86_64
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file
...
```
I know I could run --privileged, but trying to get this working in a Dockerfile. 

It appears to have worked at some point (https://github.com/fedora-cloud/Fedora-Dockerfiles/issues/38), either with an older docker version or maybe it works on docker server itself running under Fedora?

**Comment by ondrejhlavacek** [comment] 2015-01-13 04:52
+1 here :-(
```
➜  docker  docker run -i --privileged -t centos:centos7 /bin/bash
[root@f965252ddd96 /]# yum -y install httpd
...
Error unpacking rpm package httpd-2.4.6-19.el7.centos.x86_64
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file
error: httpd-2.4.6-19.el7.centos.x86_64: install failed
```

**Comment by PositiveAlex** [comment] 2015-02-02 13:26
Same problem with several packages on redhat. as a result I cannot bulid my dockerfile when there are `yum update` command. using devicemapper is workaround for this but it's slow.

**Comment by morucci** [comment] 2015-02-09 16:39
Hi,
Same problem from my side :

  Installing : httpd-2.4.6-19.el7.centos.x86_64                           12/13 
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file

This is a bit frustrating :) any solutions using the default aufs ?

**Comment by PositiveAlex** [comment] 2015-02-09 17:57
Fabien, I had to remove systemd and one another package while updateting
with --exclude-packages. But then I removed an update command at all. I
replaced it with

yum clean expire-cache

Then I installed only that components what I need to. In fact if you use
docker or vm with several programs, you dont need to update all stuff in
the system.

Mon Feb 09 2015 at 19:40:40, Fabien Boucher <notifications@github.com>:

**Comment by PositiveAlex** [comment] 2015-02-09 17:58
Moreover, if you update everything, you get 200mb or more data in your
image which is not so cool.

Mon Feb 09 2015 at 20:57:27, Александр Илюшкин <positivealex@gmail.com>:

**Comment by jefferai** [comment] 2015-04-17 17:26
Only if you don't then clean things up. But updating what's in the base image is often necessary to keep up with security updates.

**Comment by thaJeztah** [comment] 2015-04-18 22:55
Basically, this is a duplicate of https://github.com/docker/docker/issues/6980. This is an issue with (older versions of) AUFS, see https://github.com/docker/docker/issues/6980#issuecomment-94032305:

> You need a newer version of AUFS with support for `CONFIG_AUFS_XATTR`, and that kernel config option must be enabled. That fixes the `cpio: cap_set_file` on boot2docker (boot2docker/boot2docker#818), and should fix it on any Linux using AUFS.

I just tested this issue and was able to reproduce it on a DigitalOcean droplet using AUFS. Switching to BTRFS as storage driver resolved the problem.

I also spotted an external issue being linked to this, and there seems to be a 'workaround' here
https://github.com/owncloud/core/issues/12967#issuecomment-83064397 which I haven't tested.

This is not a bug in Docker, but an issue with older AUFS versions missing `CONFIG_AUFS_XATTR` support. To resolve the issue, update the AUFS version and enable the CONFIG_AUFS_XATTR attribute, or switch to another storage driver.

I'm going to close this issue, because this is a duplicate of #6980 and (unfortunately) nothing Docker itself can resolve.

Feel free to continue the discussion, perhaps someone is able to add additional tips.

**Closed by thaJeztah** 2015-04-18 22:55 UTC
Labels: /system/aufs
