### ISSUE TITLE
Error response from daemon: devmapper: Error mounting '/dev/mapper/docker-253:2-8652374-' on '/var/lib/docker/devicemapper/mnt/': invalid argument

### ISSUE THREAD

**Issue by stefiane** [docker/docker#29622] opened 2016-12-21 03:45 UTC
**Description**
docker version 1.10；when I want to restart the "Exited" container,the error occured.

**Steps to reproduce the issue:**
1.docker start daac860b966e

**Describe the results you received:**
Error response from daemon: devmapper: Error mounting '/dev/mapper/docker-253:2-8652374-26976c619a077edf5b5f064ee6f8218221ae3a6875e6f05255eb7277a8f35cc3' on '/var/lib/docker/devicemapper/mnt/26976c619a077edf5b5f064ee6f8218221ae3a6875e6f05255eb7277a8f35cc3': invalid argument

**Additional information you deem important (e.g. issue happens only occasionally):**
the file /var/lib/docker/devicemapper/mnt/26976c619a077edf5b5f064ee6f8218221ae3a6875e6f05255eb7277a8f35cc3  is existed .
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 9
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:2-8652374-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.488 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.9 GB
 Metadata Space Used: 2.634 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 251.4 GiB
Name: jxetlsrv-agent-78.docker.org
ID: VFUN:I3X5:3SOK:WVPG:PD7A:HA4N:ERCI:IE6A:L5MK:FTU4:5J33:FJ52
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: etcd://10.226.19.76:4001
Cluster advertise: 10.226.19.78:2375

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Thanks!

**Comment by cpuguy83** [comment] 2016-12-21 11:18
Yes, looks like it's already mounted.
Can you explain the steps that lead to this?
Can you reproduce on a newer version of Docker?

**Comment by quoing** [comment] 2016-12-24 13:57
Had same issue today, it was caused by disabling of SELinux + reboot.. docker container start was stuck because mount tried to use selinux labels..

I had to remove selinux labels from config.v2.json files (var/lib/docker/containers/<CID>/config.v2.json..
        "MountLabel": "system_u:object_r:svirt_sandbox_file_t:s0:c12,c257",
        "ProcessLabel": "system_u:system_r:svirt_lxc_net_t:s0:c12,c257",

dmesg shows:
[  450.397058] XFS (dm-4): unknown mount option [context="system_u:object_r:svirt_sandbox_file_t:s0:c12].

**Comment by cen1** [comment] 2017-02-22 14:43
Same problem here after disabling selinux +1

**Comment by denysvitali** [comment] 2017-03-21 09:01
I solved with a reboot. Btw, disabling SELinux is the worst decision one could make to solve an issue like this

**Comment by thaJeztah** [comment] 2017-03-21 12:09
I'm closing this issue, because we didn't hear back from the original reporter. Keep in mind that docker 1.10.3 is no longer maintained, and a lot of changes (some of which, unfortunately _breaking_) went into recent CentOS patch releases, and may require a more recent version of Docker, which has changes to account for those changes

**Closed by thaJeztah** 2017-03-21 12:09 UTC
Labels: status/more-info-needed, version/1.10

**Comment by limited1010** [comment] 2017-05-18 16:16
Thank you, I have encountered the same problem.

**Comment by Sid666999** [comment] 2017-06-28 11:11
same problem + 1, my docker server is 1.12.6

**Comment by moshemarciano** [comment] 2017-08-27 04:32
same here, Server Version: 1.12.6, Centos 7

**Comment by Idanatcox** [comment] 2018-01-30 00:04
I got the same issue on RHEL 7 Docker version 1.12.6, build ec8512b/1.12.6
the root mount ran out of space so I cleaned it up and rebooted.
Then trying to start the container didn't resolve it and this container can't be deleted(not even -f) getting:
`Error response from daemon: Driver devicemapper failed to remove root filesystem 4dc9faa1f33c506b754a6a52487ed23cf74633dd84dd9a622447c5f3045ad632: failed to remove device 5f2fd415123817c9325fc229ed8418320d69c7419c28f12f61c15f099e445f7c:devicemapper: Error running DeleteDevice dm_task_run failed`

**Comment by LspV5** [comment] 2018-05-21 08:40
same here, Server Version: 1.12.6, Centos 7.3
Ask, how did you solve it before? Is there an impression now? Thank you.

error response from daemon: devmapper: Error mounting '/dev/mapper/docker-253:0-89399-9f70a6b3c0885bb38a001a6ae2468c86e00bc156be11f98f17525278a47c49fa' on '/var/lib/docker/devicemapper/mnt/9f70a6b3c0885bb38a001a6ae2468c86e00bc156be11f98f17525278a47c49fa': input/output error
Error: failed to start containers: portainer

**Comment by tmjordan** [comment] 2019-06-28 17:11
@Idanatcox @LspV5 @moshemarciano hi guys i'm stuck with that problem, and i didn't find any working solution. I even rebooted my server, but the problem still persists.
Please help me

**Comment by stefiane** [comment] 2019-07-03 02:37
@tmjordan my problem is caused by selinux. after turn off selinux,must restart machine.fix this situation,remove all container,then restart machine

**Comment by irbian** [comment] 2020-09-14 14:53
Check this, it worked for me https://stackoverflow.com/a/36346893

**Comment by igor-podpalchenko** [comment] 2022-07-28 00:50
for f in /var/lib/docker/containers/*/config.v2.json; do jq 'del(.MountLabel, .ProcessLabel)' $f > /tmp/containter-cfg-tmp && mv -f /tmp/containter-cfg-tmp $f; done
