### ISSUE TITLE
File content not changed but COPY command invalidates cache!

### ISSUE THREAD

**Issue by svenkroll** [docker/docker#10336] opened 2015-01-25 11:07 UTC
## How to reproduce:

* Create new Dockerfile using COPY command and commit to GIT repository
* Checkout GIT repository and run Docker build on machine A
* Push created images to private registry or export it
* Pull image from private registry or import on machine B
* Checkout the same commit from GIT repository and run Docker build on machine B 

#### First run on machine A:
    build	24-Jan-2015 22:58:16	Step 8 : RUN cd /usr/local/src/APC-3.1.13;     /usr/local/bin/phpize;     ./configure --with-php-config=/usr/local/bin/php-config;     make;     make install
    build	24-Jan-2015 22:58:16	 ---> Using cache
    build	24-Jan-2015 22:58:16	 ---> 1358556ef4ad
    build	24-Jan-2015 22:58:16	Step 9 : COPY ./templates/php_modules/20-apc.ini /etc/php5/conf.d/20-apc.ini
    build	24-Jan-2015 22:58:16	 ---> 4b21637fa55b
    build	24-Jan-2015 22:58:16	Removing intermediate container 3c2658197f2b

#### Second run on machine B:
    build	25-Jan-2015 09:35:24	Step 8 : RUN cd /usr/local/src/APC-3.1.13;     /usr/local/bin/phpize;     ./configure --with-php-config=/usr/local/bin/php-config;     make;     make install
    build	25-Jan-2015 09:35:24	 ---> Using cache
    build	25-Jan-2015 09:35:24	 ---> 1358556ef4ad
    build	25-Jan-2015 09:35:24	Step 9 : COPY ./templates/php_modules/20-apc.ini /etc/php5/conf.d/20-apc.ini
    build	25-Jan-2015 09:35:24	 ---> f77fe0b46890
    build	25-Jan-2015 09:35:24	Removing intermediate container 473b3e831c87

## Expected behaviour:

When file content not changed (as example md5 sum is the same) Docker has to use cached image.

**Comment by thaJeztah** [comment] 2015-01-25 12:04
I think this is a dup of https://github.com/docker/docker/issues/9391 (among others); the issue is that the `mtime` is taken into account when determining if the cache is used or not. 

There's a workaround mentioned here; https://github.com/docker/docker/issues/9391#issuecomment-68894441 that changes the mtime of all files to the date/time of the last change in git.

**Comment by unclejack** [comment] 2015-02-02 09:12
I'm going to close this as a duplicate of #9391. This issue has come up a bunch of times and workarounds have also been provided.

Until a solution is implemented, the workaround mentioned by @thaJeztah should be used.

**Closed by unclejack** 2015-02-02 09:12 UTC
