### ISSUE TITLE
Docker process hangs on CentOS

### ISSUE THREAD

**Issue by BirknerAlex** [docker/docker#9696] opened 2014-12-16 20:36 UTC
Hello,

we are currently using the Linux Kernel version 3.14.17 with CentOS 6.6 and 
running the Docker version 1.3.2, build 39fa2fa/1.3.2. 

The docker process was freezing (zombie) after sending a docker stop command.
There was no chance to kill the docker process.

> killall -s 9 docker
> killall -s 9 docker
> killall -s 9 docker

Running "zombie" processes: 
ps Haxwwo stat,pid,ppid,user,wchan:25,command | grep -e "^STAT" -e "^D" -e "^Z"
> D     1296     1 root     sleep_on_page             /usr/bin/docker -d --selinux-enabled --iptables=false --graph=/games/docker
> Zl   12987     1 root     exit                      [docker] <defunct>
> Dl   12987     1 root     sleep_on_page             [docker]
> Zl   32313     1 root     exit                      [docker] <defunct>
> Dl   32313     1 root     sleep_on_page             [docker]

Also no chance to strace the process:
> strace -p 12987
> attach: ptrace(PTRACE_ATTACH, ...): Operation not permitted

Some proc output:
> cat /proc/1296/syscall 
> 162 0x0 0x0 0x0 0x0 0x0 0x0 0x7fff39701df0 0x5b8c44
> cat /proc/1296/syscall 
> 162 0x0 0x0 0x0 0x0 0x0 0x0 0x7fff39701df0 0x5b8c44
> cat /proc/1296/syscall 
> 162 0x0 0x0 0x0 0x0 0x0 0x0 0x7fff39701df0 0x5b8c44

Looks like the docker daemon was waiting for a file handle? 
Only a reboot of the complete server helped me with that issue. 

Process dump: https://www.dropbox.com/s/duuid5fbqey33rs/docker.dump?dl=0
Maybe anyone has an good idea. :)

Thank you very much.

Best regards,
Alexander

**Comment by BirknerAlex** [comment] 2015-01-05 17:38
Hello,

I hope you guys had a great start into the new year. Is there any update on this case or do you need more informations? We are running 1000+ servers with docker and every week we have around 2-3 servers with this issue. Sadly I can`t reproduce it.

Regards,
Alexander

**Comment by unclejack** [comment] 2015-01-05 17:44
@BirknerAlex Kernel 3.14 isn't the kernel provided by CentOS 6, RHEL 6, nor any other distribution based on RHEL 6. Only kernel 2.6.32 is officially supported on these distributions.

This is a custom setup and we don't support such setups. The main issue is that there's no easy way to duplicate these setups, nor is there an easy way to tell how to get the exact same kernel with the exact same configuration. Providing support for such setups is also extremely difficult because of the endless number of possible setups: 1) custom built kernels vs packaged kernels from repositories 2) various kernel configs 3) various kernel versions 4) patched vs unpatched kernels

I can tell you right now that kernel 3.14 doesn't have such problems on other distributions, but those distributions weren't shipped with kernel 2.6.32. These distributions running 2.6.32 have had a lot of changes made to them to support 2.6.32 and be compatible with 2.6.32 (plus its countless backports from newer kernels).

Furthermore, kernel 3.14.17 is also old and I know there were some bugs in 3.14.16-3.14.17-3.14.18.

Should you want a modern system with a more recent kernel, please upgrade to CentOS 7 and see if you're still running into problems. 

Please keep in mind that upgrading the kernel to a 3.10+ version on CentOS 6/RHEL 6 based distributions can lead to unexpected behavior due to potential incompatibilities between the system's user space tools (including their configuration and the configuration of the kernel done by these tools) and the newer kernel. This is a serious issue and I've seen similar reports from SuSE installs which had an even newer kernel by default - kernel 3.0

I'm going to close this issue now. Please comment on this issue if you manage to reproduce this with 2.6.32 on CentOS 6.6, CentOS 7 with 3.10 or another supported setup.

**Closed by unclejack** 2015-01-05 17:44 UTC

**Comment by jperrin** [comment] 2015-01-05 18:03
Correct. Currently We (CentOS) will only support docker via EPEL package on the 2.6.32-xx kernels shipped by the distribution. There are things like namespace changes which will cause issues if one decides to step outside that box and run non-distro kernel packages.

**Comment by tobowers** [comment] 2015-11-03 02:33
centos 7 on kernel 3.10.0-229.7.2.el7.x86_64 has the same behavior using docker 1.8.2

**Comment by thaJeztah** [comment] 2015-11-04 15:29
@tobowers if the daemon refuses to start, this could also be related to https://github.com/docker/docker/issues/16763#issuecomment-145488297

**Comment by tobowers** [comment] 2015-11-04 15:36
@thaJeztah the docker daemon always starts. It's when you "use docker a lot" it will end up freezing. Happens a decent amount in our system... we can replicate it by doing a "docker build" over and over again.

**Comment by thaJeztah** [comment] 2015-11-04 15:44
@tobowers thanks, just checking! Can you open a new ('fresh") issue, if possible with logs and ways to reproduce. You can add a link to this issue to explain it may be related
