### ISSUE TITLE
[1.6.0][graphdriver] prior storage driver "devicemapper" failed: error intializing graphdriver

### ISSUE THREAD

**Issue by infoslack** [docker/docker#13008] opened 2015-05-06 00:00 UTC
Hi,
Running Docker `1.6.0` on Slackware 14.1 (kernel-3.18.11-x86_64) local machine:
```
$ uname -a
Linux infoslack 3.18.11 #2 SMP Tue Apr 7 13:09:53 CDT 2015 x86_64 Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz GenuineIntel GNU/Linux
```
```
$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```
```
$ docker -D info
Containers: 7
Images: 29
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.18.11
Operating System: Slackware 14.1
CPUs: 4
Total Memory: 7.686 GiB
Name: infoslack
ID: 7V7Y:YELO:XDMW:IF3R:DEDK:C5FA:HSIH:HOFW:LKCH:NEVD:6SQB:JWPH
Debug mode (server): true
Debug mode (client): true
Fds: 10
Goroutines: 15
System Time: Tue May  5 21:04:10 BRT 2015
EventsListeners: 0
Init SHA1: 78411382de1b3838ed8f519e914ea9dc8c1053c4
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker
Username: infoslack
Registry: [https://index.docker.io/v1/]
```
```
$ docker -d -D
DEBU[0000] waiting for daemon to initialize             
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm version   OF   [16384] (*1) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm version   OF   [16384] (*1) 
DEBU[0000] devicemapper: udev sync support: true        
DEBU[0000] Generated prefix: docker-252:2-3147207       
DEBU[0000] Checking for existence of the pool 'docker-252:2-3147207-pool' 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm info docker-252:2-3147207-pool  OF   [16384] (*1) 
DEBU[0000] Pool doesn't exist. Creating it.             
DEBU[0000] libdevmapper(6): libdm-common.c:2304 (4) Udev cookie 0xd4d6876 (semid 1441792) created 
DEBU[0000] libdevmapper(6): libdm-common.c:2324 (4) Udev cookie 0xd4d6876 (semid 1441792) incremented to 1 
DEBU[0000] libdevmapper(6): libdm-common.c:2196 (4) Udev cookie 0xd4d6876 (semid 1441792) incremented to 2 
DEBU[0000] libdevmapper(6): libdm-common.c:2446 (4) Udev cookie 0xd4d6876 (semid 1441792) assigned to CREATE task(0) with flags DISABLE_SUBSYSTEM_RULES DISABLE_DISK_RULES DISABLE_OTHER_RULES         (0xe) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm create docker-252:2-3147207-pool  OF   [16384] (*1) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm reload docker-252:2-3147207-pool  OF   [16384] (*1) 
DEBU[0000] libdevmapper(3): ioctl/libdm-iface.c:1813 (-1) device-mapper: reload ioctl on docker-252:2-3147207-pool failed: Invalid argument 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1401 (0) <backtrace> 
DEBU[0000] libdevmapper(6): libdm-common.c:2231 (4) Udev cookie 0xd4d6876 (semid 1441792) decremented to 1 
DEBU[0000] libdevmapper(6): libdm-common.c:2196 (4) Udev cookie 0xd4d6876 (semid 1441792) incremented to 2 
DEBU[0000] libdevmapper(6): libdm-common.c:2446 (4) Udev cookie 0xd4d6876 (semid 1441792) assigned to REMOVE task(2) with flags DISABLE_SUBSYSTEM_RULES DISABLE_DISK_RULES DISABLE_OTHER_RULES         (0xe) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm remove docker-252:2-3147207-pool  OF   [16384] (*1) 
DEBU[0000] libdevmapper(6): libdm-common.c:1396 (4) docker-252:2-3147207-pool: Stacking NODE_DEL [verify_udev] 
DEBU[0000] libdevmapper(6): libdm-common.c:2231 (4) Udev cookie 0xd4d6876 (semid 1441792) decremented to 0 
DEBU[0000] libdevmapper(6): libdm-common.c:2496 (4) Udev cookie 0xd4d6876 (semid 1441792) waiting for zero 
DEBU[0000] libdevmapper(6): libdm-common.c:2246 (4) Udev cookie 0xd4d6876 (semid 1441792) destroyed 
DEBU[0000] libdevmapper(6): libdm-common.c:1396 (4) docker-252:2-3147207-pool: Processing NODE_DEL [verify_udev] 
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Registering GET, /containers/ps              
DEBU[0000] Registering GET, /containers/json            
DEBU[0000] Registering GET, /containers/{name:.*}/json  
DEBU[0000] Registering GET, /version                    
DEBU[0000] Registering GET, /images/json                
DEBU[0000] Registering GET, /images/viz                 
DEBU[0000] Registering GET, /images/{name:.*}/get       
DEBU[0000] Registering GET, /images/{name:.*}/history   
DEBU[0000] Registering GET, /containers/{name:.*}/top   
DEBU[0000] Registering GET, /info                       
DEBU[0000] Registering GET, /images/{name:.*}/json      
DEBU[0000] Registering GET, /containers/{name:.*}/stats 
DEBU[0000] Registering GET, /containers/{name:.*}/export 
DEBU[0000] Registering GET, /containers/{name:.*}/logs  
DEBU[0000] Registering GET, /exec/{id:.*}/json          
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws 
DEBU[0000] Registering GET, /_ping                      
DEBU[0000] Registering GET, /events                     
DEBU[0000] Registering GET, /images/search              
DEBU[0000] Registering GET, /images/get                 
DEBU[0000] Registering GET, /containers/{name:.*}/changes 
DEBU[0000] Registering POST, /containers/{name:.*}/start 
DEBU[0000] Registering POST, /containers/{name:.*}/rename 
DEBU[0000] Registering POST, /images/create             
DEBU[0000] Registering POST, /images/load               
DEBU[0000] Registering POST, /images/{name:.*}/tag      
DEBU[0000] Registering POST, /containers/{name:.*}/kill 
DEBU[0000] Registering POST, /containers/{name:.*}/copy 
DEBU[0000] Registering POST, /exec/{name:.*}/resize     
DEBU[0000] Registering POST, /build                     
DEBU[0000] Registering POST, /images/{name:.*}/push     
DEBU[0000] Registering POST, /containers/{name:.*}/unpause 
DEBU[0000] Registering POST, /containers/{name:.*}/restart 
DEBU[0000] Registering POST, /exec/{name:.*}/start      
DEBU[0000] Registering POST, /auth                      
DEBU[0000] Registering POST, /containers/{name:.*}/pause 
DEBU[0000] Registering POST, /containers/{name:.*}/stop 
DEBU[0000] Registering POST, /containers/{name:.*}/exec 
DEBU[0000] Registering POST, /containers/{name:.*}/attach 
DEBU[0000] Registering POST, /commit                    
DEBU[0000] Registering POST, /containers/create         
DEBU[0000] Registering POST, /containers/{name:.*}/wait 
DEBU[0000] Registering POST, /containers/{name:.*}/resize 
DEBU[0000] Registering DELETE, /containers/{name:.*}    
DEBU[0000] Registering DELETE, /images/{name:.*}        
DEBU[0000] Registering OPTIONS,                         
DEBU[0000] docker group found. gid: 281                 
FATA[0000] Shutting down daemon due to errors: error intializing graphdriver: Error running DeviceCreate (CreatePool) dm_task_run failed 
```
But when using the overlay driver works:
```
$ docker -d -s overlay -D
...
INFO[0000] -job init_networkdriver() = OK (0)           
DEBU[0000] Restarting containers...                     
INFO[0000] docker daemon: 1.6.0 4749651; execdriver: native-0.2; graphdriver: overlay 
INFO[0000] +job acceptconnections()                     
INFO[0000] -job acceptconnections() = OK (0)            
INFO[0000] Daemon has completed initialization
```
What am I forgetting?

**Comment by infoslack** [comment] 2015-05-06 00:08
@GordonTheTurtle sorry, my fault!
I made the correction.

**Comment by petarov** [comment] 2015-05-12 11:38
I've got pretty much the same issue, but I get 2 more errors ([DEBUG]) when running in debug mode.

This is a physical machine. SSD drive + LVM.

```
Linux xxx 3.19.7-1-ck #1 SMP PREEMPT Wed May 6 18:44:31 EDT 2015 x86_64 GNU/Linux
```
```
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): linux/amd64
```
```
DEBU[0000] waiting for daemon to initialize             
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm version   OF   [16384] (*1) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm version   OF   [16384] (*1) 
DEBU[0000] devicemapper: udev sync support: true        
DEBU[0000] Generated prefix: docker-254:1-10519         
DEBU[0000] Checking for existence of the pool 'docker-254:1-10519-pool' 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm info docker-254:1-10519-pool  OF   [16384] (*1) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm status docker-254:1-10519-pool  OF   [16384] (*1) 
DEBU[0000] [deviceset] constructDeviceIdMap()           
DEBU[0000] Skipping file /var/lib/docker/devicemapper/metadata/.tmp227912077 
DEBU[0000] Skipping file /var/lib/docker/devicemapper/metadata/.tmp984809436 
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/transaction-metadata 
DEBU[0000] Added deviceId=1 to DeviceIdMap              
DEBU[0000] [deviceset] constructDeviceIdMap() END       
DEBU[0000] Rolling back open transaction: TransactionId=2 hash= device_id=1 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm message docker-254:1-10519-pool  OF  delete 1 [16384] (*1) 
DEBU[0000] libdevmapper(3): ioctl/libdm-iface.c:1813 (-1) device-mapper: message ioctl on docker-254:1-10519-pool failed: Invalid argument 
ERRO[0000] Unable to delete device: Error running DeleteDevice dm_task_run failed 
DEBU[0000] Initializing base device-mapper thin volume  
DEBU[0000] [devmapper] CreateDevice(poolName=/dev/mapper/docker-254:1-10519-pool, deviceId=1) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm message docker-254:1-10519-pool  OF  create_thin 1 [16384] (*1) 
DEBU[0000] libdevmapper(3): ioctl/libdm-iface.c:1813 (-1) device-mapper: message ioctl on docker-254:1-10519-pool failed: Invalid argument 
DEBU[0000] Error creating device: Error running CreateDevice dm_task_run failed 
DEBU[0000] Error device setupBaseImage: Error running CreateDevice dm_task_run failed 
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Registering GET, /containers/{name:.*}/logs  
DEBU[0000] Registering GET, /_ping                      
DEBU[0000] Registering GET, /images/json                
DEBU[0000] Registering GET, /containers/{name:.*}/changes 
DEBU[0000] Registering GET, /containers/{name:.*}/top   
DEBU[0000] Registering GET, /images/{name:.*}/json      
DEBU[0000] Registering GET, /containers/ps              
DEBU[0000] Registering GET, /containers/{name:.*}/export 
DEBU[0000] Registering GET, /containers/{name:.*}/json  
DEBU[0000] Registering GET, /events                     
DEBU[0000] Registering GET, /version                    
DEBU[0000] Registering GET, /images/get                 
DEBU[0000] Registering GET, /images/{name:.*}/get       
DEBU[0000] Registering GET, /info                       
DEBU[0000] Registering GET, /images/viz                 
DEBU[0000] Registering GET, /images/search              
DEBU[0000] Registering GET, /images/{name:.*}/history   
DEBU[0000] Registering GET, /containers/json            
DEBU[0000] Registering GET, /containers/{name:.*}/stats 
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws 
DEBU[0000] Registering GET, /exec/{id:.*}/json          
DEBU[0000] Registering POST, /auth                      
DEBU[0000] Registering POST, /images/{name:.*}/tag      
DEBU[0000] Registering POST, /containers/{name:.*}/unpause 
DEBU[0000] Registering POST, /containers/{name:.*}/attach 
DEBU[0000] Registering POST, /containers/{name:.*}/copy 
DEBU[0000] Registering POST, /commit                    
DEBU[0000] Registering POST, /images/load               
DEBU[0000] Registering POST, /images/{name:.*}/push     
DEBU[0000] Registering POST, /containers/{name:.*}/pause 
DEBU[0000] Registering POST, /containers/{name:.*}/start 
DEBU[0000] Registering POST, /containers/{name:.*}/resize 
DEBU[0000] Registering POST, /exec/{name:.*}/resize     
DEBU[0000] Registering POST, /build                     
DEBU[0000] Registering POST, /containers/create         
DEBU[0000] Registering POST, /containers/{name:.*}/kill 
DEBU[0000] Registering POST, /containers/{name:.*}/wait 
DEBU[0000] Registering POST, /containers/{name:.*}/exec 
DEBU[0000] Registering POST, /exec/{name:.*}/start      
DEBU[0000] Registering POST, /containers/{name:.*}/rename 
DEBU[0000] Registering POST, /images/create             
DEBU[0000] Registering POST, /containers/{name:.*}/restart 
DEBU[0000] Registering POST, /containers/{name:.*}/stop 
DEBU[0000] Registering DELETE, /containers/{name:.*}    
DEBU[0000] Registering DELETE, /images/{name:.*}        
DEBU[0000] Registering OPTIONS,                         
DEBU[0000] docker group found. gid: 997                 
FATA[0000] Shutting down daemon due to errors: error intializing graphdriver: Error running CreateDevice dm_task_run failed 
```

**Comment by daccle** [comment] 2015-05-12 23:18
@petarov I have a very similar error with Debian Stable and lxc-docker-1.6.1
    
```
docker version
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): linux/amd64
FATA[0000] Get http:///var/run/docker.sock/v1.18/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

I know that the kernel is way too old, but it was running fine and the reboot for the update is already sheduled

```
docker -D  -d
DEBU[0000] waiting for daemon to initialize
WARN[0000] You are running linux kernel version 3.2.0-4-amd64, which might be unstable running docker. Please upgrade your kernel to 3.8.0.
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
DEBU[0000] Registering GET, /containers/json
DEBU[0000] Registering GET, /containers/{name:.*}/stats
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws
DEBU[0000] Registering GET, /exec/{id:.*}/json
DEBU[0000] Registering GET, /events
DEBU[0000] Registering GET, /containers/ps
DEBU[0000] Registering GET, /version
DEBU[0000] Registering GET, /containers/{name:.*}/json
DEBU[0000] Registering GET, /images/search
DEBU[0000] Registering GET, /images/get
DEBU[0000] Registering GET, /images/{name:.*}/history
DEBU[0000] Registering GET, /containers/{name:.*}/export
DEBU[0000] Registering GET, /containers/{name:.*}/changes
DEBU[0000] Registering GET, /containers/{name:.*}/logs
DEBU[0000] Registering GET, /_ping
DEBU[0000] Registering GET, /images/viz
DEBU[0000] Registering GET, /images/{name:.*}/get
DEBU[0000] Registering GET, /images/{name:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/top
DEBU[0000] Registering GET, /info
DEBU[0000] Registering GET, /images/json
DEBU[0000] Registering POST, /containers/{name:.*}/copy
DEBU[0000] Registering POST, /containers/{name:.*}/exec
DEBU[0000] Registering POST, /exec/{name:.*}/resize
DEBU[0000] Registering POST, /containers/{name:.*}/kill
DEBU[0000] Registering POST, /containers/{name:.*}/restart
DEBU[0000] Registering POST, /containers/{name:.*}/attach
DEBU[0000] Registering POST, /containers/create
DEBU[0000] Registering POST, /containers/{name:.*}/pause
DEBU[0000] Registering POST, /auth
DEBU[0000] Registering POST, /commit
DEBU[0000] Registering POST, /build
DEBU[0000] Registering POST, /images/create
DEBU[0000] Registering POST, /images/load
DEBU[0000] Registering POST, /images/{name:.*}/tag
DEBU[0000] Registering POST, /containers/{name:.*}/stop
DEBU[0000] Registering POST, /exec/{name:.*}/start
DEBU[0000] Registering POST, /containers/{name:.*}/rename
DEBU[0000] Registering POST, /images/{name:.*}/push
DEBU[0000] Registering POST, /containers/{name:.*}/unpause
DEBU[0000] Registering POST, /containers/{name:.*}/start
DEBU[0000] Registering POST, /containers/{name:.*}/wait
DEBU[0000] Registering POST, /containers/{name:.*}/resize
DEBU[0000] Registering DELETE, /containers/{name:.*}
DEBU[0000] Registering DELETE, /images/{name:.*}
DEBU[0000] Registering OPTIONS,
DEBU[0000] docker group found. gid: 999
FATA[0000] Shutting down daemon due to errors: error intializing graphdriver: invalid argument
```

**Comment by petarov** [comment] 2015-05-14 18:31
I managed to resolve this on my side by deleting **/var/lib/docker** and restarting the docker service. I'm really not sure what caused it and it may be due to packaging issue in my case. [Reference](https://bbs.archlinux.org/viewtopic.php?pid=1475716#p1475716).

**Note:** Removing /var/lib/docker will delete all your downloaded images!

**Comment by lpgpa** [comment] 2015-05-31 01:13
petarov tks!

**Comment by ernoaapa** [comment] 2015-06-01 17:42
Same! Clearing the /var/lib/docker help! Thanks @petarov !

**Comment by rhvgoyal** [comment] 2015-06-08 17:43
@infoslack I suspect that pool somehow reached into a bad state. Can you reproduce this problem and give me exact step on how to do it. And next time this happens also paste the output of "dmsetup table" and "dmsetup status".

**Comment by rhvgoyal** [comment] 2015-06-16 14:45
@vbatts 

Ok, this issue is resolved by cleaning up /var/lib/docker/. I suspect this is just a configuration issue and nothing more then that.

I have opened a PR to catch some of these configuration issues during startup.

https://github.com/docker/docker/pull/13896

I think it will be good to get this PR in. It will detect issues related to pool early and make sure metadata in /var/lib/docker/ matches with that of pool.

So I think we should close this issue.

**Closed** 2015-06-16 17:22 UTC
Labels: /system/devicemapper

**Comment by branderxero** [comment] 2015-06-19 14:25
sorry to bump a closed issue, but i has having a similar issue:

`docker[8237]: time="2015-06-19T10:17:36-04:00" level=fatal msg="Shutting down daemon due to errors: error intializing graphdriver: invalid character '\\x00' looking for beginning of value"`

and removing `/var/lib/docker` and restarting the service fixed this issue as well. thanx @petarov !

**Comment by rhvgoyal** [comment] 2015-06-22 15:24
@branderxero 

Are you able to reproduce the problem? Can you give me steps to reproduce it.

Did you change either thin pool or any of the metadata files or anything else?

**Comment by rhvgoyal** [comment] 2015-06-22 15:26
@branderxero 

Does it happen on latest docker?

**Comment by branderxero** [comment] 2015-06-22 16:01
@rhvgoyal i'm using `Docker version 1.6.2, build 7c8fca2` from the arch repos. i had been using it fine for months. based on my pacman logs it appears to be:

`[2015-05-15 10:07] [ALPM] upgraded docker (1:1.6.1-1 -> 1:1.6.2-2)`

which broke my setup. after removing `/var/lib/docker` and disabling and renabling the `docker.service` via systemctrl everything started working again. i have had no issues since.

**Comment by rhvgoyal** [comment] 2015-06-22 16:06
@branderxero 

So looks like some kind of incompatibility between two versions which shows up over upgrade. Are you running docker daemon in debug mode by any chance? I am wondering if there are any debug logs, it might help narrowing down the problem a bit.

**Comment by branderxero** [comment] 2015-06-22 16:17
@rhvgoyal sorry no. i had about 150 images on my machine, and have since rebuilt 25-30 with no new issues.

**Comment by mbektchiev** [comment] 2015-12-28 13:56
I stumbled upon the same issue with v1.9.1. Removing `/var/lib/docker` fixed it. I think that the reason for the corruption was that I attempted to run the service without previously installing `linux-image-extra-`

**Comment by sgnn7** [comment] 2016-03-15 15:54
The issue is closed but I might as well post my findings here. The underlying problem is the `devicemapper` storage driver that gets into an inconsistent state which was pretty much every time we ran Docker-in-Docker setup on Ubuntu hosts.

The fix (using overlayfs storage driver):
- Stop the docker service with `sudo systemctl stop docker.service`
- Remove broken `devicemapper` data - this is easiest with `rm -rf /var/lib/docker/*`
- Install `overlayroot` from apt-get which will get you that kernel module
- Add `overlay` to `/etc/modules-load.d/overlayfs.conf` so that it loads on boot
- Run `sudo modprobe overlay` to load the module for your current session if you won't restart the machine.
- (this step might not be needed) Add `-s overlay` to `DOCKER_OPTS` in `/etc/default/docker` to force overlayfs to be used instead of `devicemapper`/`aufs`/etc.
- Restart the machine or start the docker service with `sudo systemctl restart docker.service`

**Comment by kephas** [comment] 2018-08-03 21:21
Can data in /var/lib/docker be recovered?
