### ISSUE TITLE
dind overlay backend: pip cleanup fails due to delete of non-empty directory

### ISSUE THREAD

**Issue by stevenschlansker** [docker/docker#13411] opened 2015-05-22 19:21 UTC
We recently switched to overlay backend, and are now having trouble with our Docker-in-Docker based builds that include PIP packages.

Reproduction case here:
https://github.com/stevenschlansker/docker-pip-overlay-bug

If you `run-dm.sh`, you see the expected case: the build completes and prints `success`
If you `run-overlay.sh`, you see the broken case: the build fails due to
```
OSError: [Errno 39] Directory not empty: '/tmp/pip-Yy1p3Z-uninstall/usr/lib/python2.7/dist-packages'
```

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

Containers: 41
Images: 65
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.4
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 7.335 GiB
ID: HOR6:EU3X:O254:JXLS:6K3B:K75R:S6HM:GPL6:H4SU:B6PU:HTSL:DRCQ
WARNING: No swap limit support
```

**Comment by thaJeztah** [comment] 2015-05-24 11:50
Thanks for reporting and adding a repro-case, @stevenschlansker 

I'm not on overlay myself, but to clarify; Are you only seeing this problem when running DIND, or also without?

**Comment by thaJeztah** [comment] 2015-05-25 12:57
Looking at this again, I think this actually is a duplicate of https://github.com/docker/docker/issues/12327

I'm going to close this issue because I think this is a duplicate of https://github.com/docker/docker/issues/12327. Please continue the discussion in that issue.

If you think this is not a duplicate and I closed this by mistake, feel free to comment here and I'll reopen.

**Closed by thaJeztah** 2015-05-25 12:57 UTC
Labels: /system/overlay
