### ISSUE TITLE
[Question] Docker PID 1 zombie processes

### ISSUE THREAD

**Issue by EMChamp** [docker/docker#29238] opened 2016-12-08 07:32 UTC
I would like to gain some insight into the docker zombie process. Is there a simple way to produce a zombie in a docker container to see if it is reaped or not?

I am trying to create a zombie process that will persist even after the container is closed (that's what I understand the problem is in any case) so I can prove that using dumb-init as my ENTRYPOINT will fix the problem. However I haven't been able to show that the zombie process I created will stay no matter how I terminate my container or no matter how i terminate the parent of the zombie process.

I'm running nvidia/cuda:7.5-devel for the base image and docker v1.12.3. I've created a zombie in my container by having this script run as PID 1 in my dockerfile via CMD:

```
#!/bin/bash
# Spawn a zombie process whose parent is this script which is PID 1 in a container.
(sleep 1 & exec /bin/sleep 200000) &

tail -f /dev/null 
```

I started my test by launching 2 containers, 1 with dumb init as PID 1 (which launches my script) and 1 with the script as PID 1.

I can see the zombies here

```
:~/dockerfiles$ ps -ef | grep sleep
root     30599 30597  0 16:24 ?        00:00:00 /bin/sleep 200000
root     30600 30599  0 16:24 ?        00:00:00 [sleep] <defunct>
root     30746 30722  0 16:24 ?        00:00:00 /bin/sleep 200000
root     30747 30746  0 16:24 ?        00:00:00 [sleep] <defunct>
```

but when I try to kill the parents either outside of inside of the container, the zombies are reaped even in the container not running dumb-init.

I'm looking for a way to reproduce this PID1 problem so I can show that dumb-init is doing its job because so far I haven't been able to show that zombies will stick to the host OS after the containers are killed, on the contrary the zombie processes are immediately reaped when I kill their parent process even if the container is still running.

**Comment by justincormack** [comment] 2016-12-08 16:59
Zombies will not survive container shutdown. They can remain inside the container which causes a resource leak in some cases, hence the reason for an `init` (note that Docker 1.13 will have a `docker run --init` option to add one automatically.

**Comment by cmluciano** [comment] 2017-01-06 19:40
@justincormack Can you link the relevant PR+issue for the --init flag ?

**Comment by cmluciano** [comment] 2017-01-06 20:06
NVM, I found in in the [release notes](https://github.com/docker/docker/blob/master/CHANGELOG.md#runtime)

**Comment by thaJeztah** [comment] 2017-01-07 01:38
Let me close this issue, as it's not a bug report or feature request, but feel free to continue the conversation

**Closed by thaJeztah** 2017-01-07 01:38 UTC
Labels: area/builder, kind/question
