### ISSUE TITLE
Private registry auth broken for "docker build" in 1.7

### ISSUE THREAD

**Issue by marcust** [docker/docker#14092] opened 2015-06-22 11:23 UTC
Basically, I can pull an IMAGE but not build FROM this image:

```
(master) marcus@lindan:~/proj/feed-aggregator/feed-aggregator/src/main/docker/feed-es: docker build .
Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon 
Step 0 : FROM docker.myregistry.io/external/elasticsearch
Pulling repository docker.myregistry.io/external/elasticsearch
Authentication is required.
(master) marcus@lindan:~/proj/feed-aggregator/feed-aggregator/src/main/docker/feed-es: docker pull docker.myregistry.io/external/elasticsearch
Pulling repository docker.myregistry.io/external/elasticsearch
747b2d1d5216: Download complete 
3cb35ae859e7: Download complete 
41b730702607: Download complete 
e66a33f451f4: Download complete 
fdb90580e4de: Download complete 
e475d8c85f58: Download complete 
d998fe3b44f5: Download complete 
ba74b76dec9e: Download complete 
0f20d9f5a3aa: Download complete 
ef0d8e7a8fb7: Download complete 
abe96ca03b53: Download complete 
90560bf2888f: Download complete 
b060405f5878: Download complete 
a3b5d709cfe1: Download complete 
20739d5e6c65: Download complete 
2dc75a0316d5: Download complete 
de18fc2382d9: Download complete 
9ab73fb8659d: Download complete 
fb3e6ab9246b: Download complete 
e5a0c8b9054a: Download complete 
8160ff423fa4: Download complete 
20df9361edfc: Download complete 
636f8b746f82: Download complete 
1a1d552e754b: Download complete 
e89b4c9cdf1c: Download complete 
Status: Downloaded newer image for docker.myregistry.io/external/elasticsearch:latest
```

**Comment by jarischaefer** [comment] 2015-06-22 12:00
Looked through the issues and did not find something describing exactly the problems @marcust is facing.
I am facing the same issue using Docker 1.7.0 on Ubuntu 15.04 Linux 3.19.0-21-generic x86_64. The docker daemon's start parameters include --insecure-registry. Pulling the referenced image manually works fine. The system runs within VirtualBox 4.3.28.

### Reproducing:
* Setup a 2.0 registry with an authenticating reverse proxy like jwilder's nginx-proxy.
* docker login foo should work
* Push a random image foo/bar
* Create a Dockerfile referencing the aforementioned image (FROM foo/bar)
* docker build . should fail on authentication
* docker pull foo/bar should work as expected

I would expect the docker build command to utilize the config from ~/.docker/config.json for authentication. Instead, an authentication error pops up.

### System info
VirtualBox 4.3.28, Ubuntu 15.04

docker version:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

docker info:
Containers: 0
Images: 13
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 13
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-21-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 1.954 GiB
Name: Docker-Development
ID: C2AT:5PEU:UZL6:NCJE:3IR5:J4OF:JAKX:IHZI:V4WS:WHDQ:XLUE:IMB4
WARNING: No swap limit support

uname -a:
Linux Docker-Development 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dmp42** [comment] 2015-06-22 16:57
@marcust likely a dupe of #14065

**Comment by marcust** [comment] 2015-06-22 17:15
I wasn't sure because I have no hyphens in my names

**Comment by dmp42** [comment] 2015-06-22 17:54
@marcust yay, it still need to be investigated - not closing it yet as dupe for this reason.
Definitely a problem there, anyhow...

**Comment by aoiHikari** [comment] 2015-06-23 15:26
I am having the same issue since the update to Docker 1.7.0. Basically ```docker pull <image-name>``` works but ```FROM <image-name>```  in the Dockerfile does not.

Also the image that is to be pulled contains a hyphen, if that is even relevant. Here is some more info:

docker version:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

docker info:
Containers: 159
Images: 236
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 554
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 12
Total Memory: 31.33 GiB
Name: PC192
ID: Z6TM:SMWF:JYK4:JHAA:SN3M:O6UV:NBHO:WCLK:6V3X:GSDZ:PHIR:PS5P
WARNING: No swap limit support

**Comment by jbiel** [comment] 2015-06-23 17:48
Same issues are occurring for me with "latest" registry (python) version. The issue is not with the registry, but with docker itself. It is not attempting to use auth when FROM in a docker file is used, when pushes are attempted, etc. @jarischaefer's report is spot on.

Here's what haproxy responds with when I try to do a push (auth is done at haproxy):

```
registry/<NOSRV> -1/-1/-1/-1/11 401 252 - - PR-- 0/0/0/0/3 0/0 "GET /v2/ HTTP/1.1"
registry/<NOSRV> -1/-1/-1/-1/12 401 252 - - PR-- 0/0/0/0/3 0/0 "GET /v1/_ping HTTP/1.1"
registry/<NOSRV> -1/-1/-1/-1/11 401 252 - - PR-- 0/0/0/0/3 0/0 "GET /v1/_ping HTTP/1.1"'
```
It is sending 401s because docker is not including auth for certain actions. I don't think hyphens have anything to do with the issue.

**Closed** 2015-06-26 00:39 UTC
Labels: Distribution

**Comment by kcraft** [comment] 2015-12-02 16:39
I am having this exact same issue with Docker 1.9. Manually pulling an image from my private repo works. Building a Dockerfile with a FROM that references the private repo does not. I have an nginx LDAP proxy sitting in front of my private repo. The issue is closed but it doesn't seem like it is fixed? Has anyone verified the fix?

**Comment by jbiel** [comment] 2015-12-02 16:47
It's been working for me.

**Comment by marcust** [comment] 2015-12-02 16:50
@kcraft works for me as well. Are you just issuing a "docker build" or using something else?

**Comment by kcraft** [comment] 2015-12-02 17:00
I am using docker build:

```
$ docker login mydomain.com
Username: kcraft
Password: 
Email: 
WARNING: login credentials saved in /Users/kcraft/.docker/config.json
Login Succeeded

$ docker pull mydomain.com/my-image
Using default tag: latest
swarm-node0: Pulling mydomain.com/my-image:latest... : downloaded 
swarm-node1: Pulling mydomain.com/my-image:latest... : downloaded 

$ docker build .
Sending build context to Docker daemon 9.216 kB
Step 1 : FROM mydomain.com/my-image
Pulling repository mydomain.com/my-image
Authentication is required.
```

Here are the logs from the nginx proxy after running ```docker build```:

```
10.2.10.67 - - [02/Dec/2015:16:53:27 +0000] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.9.1 go/go1.4.3 git-commit/a34a1d5 kernel/4.1.13-boot2docker os/linux arch/amd64"
10.2.10.67 - - [02/Dec/2015:16:53:27 +0000] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.9.1 go/go1.4.3 git-commit/a34a1d5 kernel/4.1.13-boot2docker os/linux arch/amd64"
10.2.10.67 - - [02/Dec/2015:16:53:27 +0000] "GET /v1/repositories/my-image/images HTTP/1.1" 401 194 "-" "docker/1.9.1 go/go1.4.3 git-commit/a34a1d5 kernel/4.1.13-boot2docker os/linux arch/amd64"
```

Note that I am using a swarm cluster, although I doubt that is related. I think it just runs the same command on each node in the cluster.

**Comment by kcraft** [comment] 2015-12-02 17:16
After thinking about this further, I bet that I am logged into one of the swarm nodes but not the other, so the command is failing on the node I am not logged into. Seems like a swarm bug after all. I will verify and edit my comment with an update shortly.
