### ISSUE TITLE
Creating a network using the remote API requires IPAM field and gives incorrect error

### ISSUE THREAD

**Issue by manast** [docker/docker#26580] opened 2016-09-14 19:44 UTC
**Description**

When trying to create a network using the remote API, according to the documentation 1.24 (https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-network)
the IPAM field is an optional parameter, but if not provided, the following error is returned:
"rpc error: code = 3 desc = driver name: if driver is specified name is required" which does not seem correct either.

**Steps to reproduce the issue:**
Just use the remote API to create a network, using curl or whatever you feel comfortable with.
**Describe the results you received:**
"rpc error: code = 3 desc = driver name: if driver is specified name is required"

**Describe the results you expected:**
status = 201

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 158
 Running: 8
 Paused: 0
 Stopped: 150
Images: 258
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 577
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: active
 NodeID: cbq5d7h0cigpzulcfyqvaomlq
 Is Manager: true
 ClusterID: 070qemaxhu18hg3tvatjlh602
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 138.201.132.20
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.75 GiB
Name: caturra
ID: 46TP:5YN6:AVJS:7CAZ:JZJO:SFJY:H5R7:JVJR:OCQU:NW4Y:5WL7:UDLX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: manast
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
Insecure Registries:
 127.0.0.0/8
```

**Comment by aboch** [comment] 2016-09-14 22:12
This happens when swarm is active, correct ?
I think this was fixed recently on master. Will look for the PR.

**Comment by manast** [comment] 2016-09-14 22:18
yes. using swarm mode

**Comment by aboch** [comment] 2016-09-14 22:18
Hmm, looks like the fix is not merged yet.
Nevertheless I think this issue is a duplicate #25735

**Comment by manast** [comment] 2016-09-14 22:19
looks like it :)

**Comment by thaJeztah** [comment] 2016-09-15 16:58
Closing as duplicate of https://github.com/docker/docker/issues/25735, thanks for reporting @manast!

**Closed by thaJeztah** 2016-09-15 16:58 UTC
Labels: area/api, area/networking, area/swarm, version/1.12
