### ISSUE TITLE
VMware 5.5 snapshot with quiescing kill/hang VM with docker devicemapper

### ISSUE THREAD

**Issue by krumli** [docker/docker#10264] opened 2015-01-22 06:54 UTC
VMware ESXi 5.5U2
VMtools  9.4.10.37835 (build-2068191)
Centos 7.0 up2date (3.10.0-123.13.2.el7.x86_64)
Docker 1.3.2
Storage Driver: devicemapper

Hello,
When we try to do snapshot with quiescing of the VM, it always freeze the FS and the VM become irresponsive. It's no more possible to log into it or to do any writes to the FS.
It seems like the FS is freezed.

We think it's more a linux/CentOS/RH issue, but maybe you have some hints.

Thank you.
Krumli

**Comment by unclejack** [comment] 2015-01-27 13:57
@krumli This doesn't sound like it has anything to do with Docker. After having suspended and restored successfully VMs running Docker, and containers, I don't think there's any reason to think such a crash would be caused by Docker itself.

I really think this might be a problem with ESXi or with the CentOS/RHEL kernel. You probably want to make sure you open a bug for this.

I've marked this as a bug for RHEL since it's likely it's also affecting RHEL.

ping @vbatts

**Comment by unclejack** [comment] 2015-01-27 16:17
I'm going to close this issue as it's not a Docker bug.

**Closed by unclejack** 2015-01-27 16:17 UTC
Labels: /os/linux/rhel

**Comment by vishramachandran** [comment] 2015-09-19 05:56
@krumli Did you ever solve this issue? We are seeing the same. Any pointers would be helpful.

**Comment by krumli** [comment] 2015-09-19 15:56
Nop, we used ext4 and overlay (kernel 4.0).
Regards

Le samedi 19 septembre 2015, vishramachandran <notifications@github.com> a
écrit :

**Comment by hauihau** [comment] 2016-12-13 10:17
We're currently facing this issue with docker 1.12.3 under openSUSE LEAP 42.2 when VMware VDP creates the snapshot. Docker 1.9.1 didn't show this issue.
