### ISSUE TITLE
Add a raw-file logging driver

### ISSUE THREAD

**Issue by akshayjshah** [docker/docker#25814] opened 2016-08-17 19:24 UTC
Are you open to a PR which adds a simple pass-through logging driver? The driver would push an application's standard out and standard error to files without any formatting or modification whatsoever.

I've followed as much of the logging and plugin discussion as I can find (especially #18001 and #18604), and I realize that you don't want to support every logging format under the sun. However, this seems like a useful escape hatch for logging systems that don't have a dedicated driver; it allows developers to log to standard out/err in their organization's preferred format (JSON, msgpack, Splunk, etc.) and lets operators configure local persistence, post-processing, and forwarding.

**Comment by cpuguy83** [comment] 2016-08-17 19:30
A bit -1 on this myself.
I'd rather solve the problem with logging rather than copping out with something like this.
Something similar was recently suggested, but using fifo's.

**Comment by thaJeztah** [comment] 2016-08-18 17:22
Yes, this is a duplicate of https://github.com/docker/docker/issues/17020, and https://github.com/docker/docker/issues/24898, so sorry, I'll have to close this one per https://github.com/docker/docker/pull/17582#issuecomment-157544082

**Closed by thaJeztah** 2016-08-18 17:22 UTC
Labels: area/logging, kind/feature
