### ISSUE TITLE
docker push ....wh..wh.plnk/51.1512629: operation not permitted

### ISSUE THREAD

**Issue by astropanic** [docker/docker#15643] opened 2015-08-17 20:12 UTC
### BUG REPORT INFORMATION

```
docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

```
docker info
Containers: 0
Images: 12
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 994 MiB
Name: dtr
ID: AC43:FJTX:XCJ7:N55B:MHKA:V3SI:56PY:ZTSZ:GR6G:HW3U:BFDV:P3B3
Username: astropanic
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

```
uname -a
Linux dtr 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

To reproduce (pushing to hub.docker.com):

```
docker pull grafana/grafana
docker tag grafana/grafana XXXX/grafana
docker login...
docker push XXXX/grafana
```

To reproduce (pushing to own trusted registry):

```
docker tag grafana/grafana dtr.yoururl.com/user/grafana
docker push dtr.yoururl.com/user/grafana
```

Results received:

```
docker push astropanic/grafana
The push refers to a repository [docker.io/astropanic/grafana] (len: 1)
2d36fa5a39c0: Image successfully pushed
b058f5658ab3: Image already exists
0c990b75b82b: Image already exists
2a9f5f2836c5: Image already exists
993af6b30ef3: Image already exists
2bde92bd6428: Image already exists
480b6c2dc6ea: Buffering to Disk
open /var/lib/docker/aufs/mnt/480b6c2dc6eaa2c3b1bce9e75f8aea1eaf6872bcc6eb52e030e7033062a93615/.wh..wh.plnk/51.1512629: operation not permitted
```

Results expected:

### Be able to push to remote registry

This happens on three machines, all running docker 1.8.1, DigitalOcean, XenVM, Virtualbox

**Comment by rsslldnphy** [comment] 2015-08-24 13:37
I have also just run into this issue. Running `docker-machine` on OSX.

```
docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

```
docker info
Containers: 1
Images: 88
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 90
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: DD42:AZSY:AXFU:4CZ2:5FNZ:HG4A:OOR3:UGTJ:Z7HC:F5MH:CG3K:4LHP
Debug mode (server): true
File Descriptors: 11
Goroutines: 18
System Time: 2015-08-24T13:35:46.589911826Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

```
docker push registry.bugsbio.org/cps-predict
The push refers to a repository [registry.bugsbio.org/cps-predict] (len: 2)
b57c7af21524: Image successfully pushed
2fbc88214f7f: Image successfully pushed
4b2645758ba1: Image successfully pushed
3b532afd5313: Image successfully pushed
ebc0d6d6c79f: Image successfully pushed
a5325033a3c8: Image already exists
0a2a239b8f1a: Image already exists
876cda20d69c: Image already exists
1a3d1eda1448: Image already exists
70d63d94c075: Image already exists
9ab57b617739: Image already exists
aa13d4b87ff1: Image already exists
b3b41ff44ee7: Image already exists
9edb8a7f2b2b: Image already exists
26102afff102: Image already exists
154591ba95a5: Image already exists
701f67ef90e6: Image already exists
36ab072b9789: Image already exists
a14d23d55076: Image already exists
5bbbf3ad0dfc: Image already exists
1eba9d32e081: Image already exists
06b29ea310e8: Image already exists
0bea6d812f47: Image already exists
b6df8e2efdbb: Image already exists
c21983148e65: Image already exists
814c3fe85833: Buffering to Disk
open /mnt/sda1/var/lib/docker/aufs/mnt/814c3fe8583359f058e9bcff30347945c8cadabca1b58c7e35d26a2415bacb60/.wh..wh.plnk/356.920430: operation not permitted
```

**Comment by itatabitovski** [comment] 2015-08-28 07:07
I have also encountered this problem when using docker 1.8.1 and registry 2.1. Downgrading to version 1.7.1 seems to work fine with registry 2.1.

**Comment by wwwtyro** [comment] 2015-09-01 17:44
Also seeing this issue. Docker 1.8.1 and registry 2.0.1 & 2.1.1.

**Comment by crosbymichael** [comment] 2015-09-01 18:59
ping @docker/distribution-maintainers

**Comment by wwwtyro** [comment] 2015-09-01 21:05
FWIW, I've found a couple workarounds for this issue. If you can get away with rebuilding your image, rebuilding it with >= v1.5.0 of Docker seems to make the image well-behaved in v1.8.1. You might get away with a lower version - not sure, didn't check - but v1.3.0 definitely breaks it for me.

If you can't get away with a rebuild (I couldn't), exporting and importing the image under Docker v1.8.1 appears to repair whatever discrepancy there is in the handling of .wh..wh.* files, and the image is well-behaved.

**Comment by jalmansor** [comment] 2015-09-15 17:48
I'm seeing this as well using overlay, docker 1.8.2, on ubuntu 14.04.3 (HWE 3.19 kernel).

**Comment by xuebinglee** [comment] 2015-09-16 01:39
I'm having the same issue. Unfortunately, the workarounds do not work for me.

**Comment by falmp** [comment] 2015-09-21 21:18
Also seeing this issue here:

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by shouze** [comment] 2015-09-22 09:24
I have the issue too... no files in `.wh..wh.plnk` directory! So I can't push my image, too bad :scream_cat: 

Rebuilding the image didn't worked. Exporting it... wait... I've just built it, I'm not running it! So I've tried to save it but save looks broken.

```
Containers: 0
Images: 22
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-253
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 1.974 GiB
Name: focused-meitner
ID: 3ID5:KU2Y:62RX:MHY6:KRM5:BOKY:LT7L:TMVG:O52W:YTBD:J2NU:EGXD
Username: shouze
Registry: https://index.docker.io/v1/
Labels:
 provider=scaleway
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:        15.04
Codename:       vivid
```

**Comment by shouze** [comment] 2015-09-22 09:31
Oops... I have the same issue with **save** command BTW in fact, it was just pretty... long to execute:
```
docker save 4f9dc8dc1fc9 > image.tar
Error response from daemon: open /var/lib/docker/overlay/e687a2747bd66b9f9c25ce62ae14d1667fda8b38db5db6f9d9c590d9864fc7ad/root/.wh..wh.plnk/1001.38819: no such file or directory
``` 

So it looks like the diff process is looking for something that should exist but... no?

**Comment by shouze** [comment] 2015-09-22 10:06
Ok guys :+1: for the exporting image (temporary) fixup... but it's a real pain in the ass!

**Comment by nethibernate** [comment] 2015-09-25 07:26
@shouze how did you fix it??

**Comment by moul** [comment] 2015-09-25 08:17
@nethibernate, we downgraded Docker to the 1.7.1 version

**Comment by nethibernate** [comment] 2015-09-25 11:11
@moul But we have already been using the version 1.7.1, what should we do now?:(

**Comment by shouze** [comment] 2015-09-25 11:19
@nethibernate with docker 1.7.1 all is working perfectly for me, I can push. Be careful to stop your docker service & restart from scratch (rm -rf /var/lib/docker) if you downgraded docker from 1.8.x to 1.7.1 otherwise you will probably still have some inconsistencies I guess.

**Comment by nethibernate** [comment] 2015-09-25 11:33
OK, I will reset the docker 1.7.1 and try it again, thank you @shouze !

**Comment by tonistiigi** [comment] 2015-09-28 23:16
This is caused by `tar-split` not finding the plink file on disk on recreating the tar in  `graph/assembleTarLayer`. These files are stored in the `tar-split` json file on extraction but because they are not visible(and also temporary) in mounted system, error appears on accessing their contents again.

Ideally these files should not appear in the tar at all(#8813), so I'm not sure if these are very old base layers that have this problem(pre v1.4). But even if they are in the tar push seems quite a bad place to fail. It would be much better to ignore these or at least fail on pull when we first see the incompatible file inside the tar. This would mean either making `tar-split` aware of these special files or having some blacklist scanning on extraction.

cc @vbatts

**Comment by shouze** [comment] 2015-09-29 12:54
@tonistiigi yup, should be better at least to fail on pull as there's no particular reason to build artifacts with a docker version such different from production or whatever other docker deployed version.

**Comment by jyoo123** [comment] 2015-10-01 23:05
Guys, how do you downgrade from 1.8.1 to 1.7.1?

**Comment by jelis** [comment] 2016-03-04 15:59
Same issue

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

**Comment by itatabitovski** [comment] 2016-03-04 16:18
@jelis I believe docker 1.10 solved this issue.

**Comment by thaJeztah** [comment] 2016-03-05 00:54
Yes, this should be fixed now, so closing

**Closed by thaJeztah** 2016-03-05 00:54 UTC
Labels: group/distribution

**Comment by vicctor** [comment] 2016-04-20 14:06
I have similar issue with the following setup:

Private registry:2 running on:

```
docker@docker-repo:~$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```



Docker client where I'm preparing images Windows10:

```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

When I'm going to push my images to our repo, I have an error in the registry log:

```
time="2016-04-20T13:41:37Z" level=error msg="response completed with error" err.code=unsupported err.message="The operation is unsupported." go.version=go1.5.3 http.request.host="docker-repo.mycompanyinternalnet:5000" http.request.id=1c3267d2-c42c-4c65-9c7c-d59e91da4bd5 http.request.method=POST http.request.remoteaddr="192.168.200.162:62951" http.request.uri="/v2/bussybox/blobs/uploads/" http.request.useragent="docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/4.1.19-boot2docker os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=4.805766ms http.response.status=405 http.response.written=78 instance.id=5857839c-cc3c-4a82-ab08-5dcf1049c0dd vars.name=bussybox version=v2.3.1
192.168.200.162 - - [20/Apr/2016:13:41:37 +0000] "POST /v2/bussybox/blobs/uploads/ HTTP/1.1" 405 78 "" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/4.1.19-boot2docker os/linux arch/amd64"
```

**Comment by thaJeztah** [comment] 2016-04-20 14:20
@vicctor looks like a different issue; "The operation is unsupported"

**Comment by aaronlehmann** [comment] 2016-04-20 16:31
@vicctor: This looks like a possible registry configuration issue. Is it set up as a proxy? Which storage driver are you using? Do any other images or Docker setups push successfully?

**Comment by tjrivera** [comment] 2016-04-20 16:44
@vicctor couldn't help but notice in your error `/v2/bussybox/blobs/uploads/` should it be `busybox`?

**Comment by vicctor** [comment] 2016-04-20 16:54
Yes I pushed for testing purposes bussybox.

Yes you right the repository is configured as a proxy. I will double check
configuration and give you feedback on Monday.

Thanks for advice.
20 kwi 2016 18:46 "Tyler Rivera" <notifications@github.com> napisał(a):

@vicctor <https://github.com/vicctor> couldn't help but notice in your
error /v2/bussybox/blobs/uploads/ should it be busybox?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/docker/docker/issues/15643#issuecomment-212508318>
