### ISSUE TITLE
after docker login a private registry. the other docker op still require auth

### ISSUE THREAD

**Issue by cc272309126** [docker/docker#9609] opened 2014-12-11 09:28 UTC
Hi,
I use docker to login a nginx+docker-registry+ldap service. when I use "docker login -u xxx -p xxx -e xxx xxx", it report succeed. but after this, I use docker search/pull/push, it still require me to auth. 
reproduce
1.docker login -u xxx -p xxx -e xxx privete-registry
2.docker search privete-registry/tomcat
3.docker pull privete-registry/tomcat
it return "Error response from daemon: Unexepected status code 401".

**Comment by dkjer** [comment] 2015-01-12 20:02
This looks like a duplicate of #9922 ?

**Comment by jfrazelle** [comment] 2015-01-12 20:03
closing as duplicate

**Closed by jfrazelle** 2015-01-12 20:03 UTC
Labels: Distribution
