### ISSUE TITLE
Share directory between windows and docker container 

### ISSUE THREAD

**Issue by deadliving** [docker/docker#19225] opened 2016-01-11 05:31 UTC
Hi,everyone,
     I want mount folder on windows into docker container,follow the article"https://github.com/docker/docker/issues/12590#issuecomment-96767796",I excuse my command like this:
           docker run -v //d/study/visallo/code/visallo:/opt/source visallo-dev
      but it works wrong:
$ docker run -v //d/study/visallo/code/visallo:/opt/source visallo-dev
An error occurred trying to connect: Post http://localhost:2375/v1.21/containers/create: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.

      Anyone who can give me some suggests?  thanks

**Comment by thaJeztah** [comment] 2016-01-13 03:49
@deadliving looks like your environment variables are not properly set, so the docker client cannot connect to the daemon. Try running `docker-machine env default`, and follow the instructions.

However, keep in mind that GitHub is not a generic support forum, but for tracking bugs and feature requests. I'll close this issue, because this is not a bug or a feature request. Feel free to comment here after I've closed this issue

**Closed by thaJeztah** 2016-01-13 03:49 UTC
