### ISSUE TITLE
Can not connect via http to remote host

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [docker/docker#22796] opened 2016-05-17 18:09 UTC
**Output of `docker version`:**
Local machine:

> Client:
>  Version:      1.11.1
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   5604cbe
>  Built:        Tue Apr 26 23:44:17 2016
>  OS/Arch:      windows/amd64
> 
> Server:
>  Version:      1.11.1
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   5604cbe
>  Built:        Wed Apr 27 00:34:20 2016
>  OS/Arch:      linux/amd64

Remote Machine:

> Client:
>  Version:      1.11.1
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   5604cbe
>  Built:        Wed Apr 27 00:34:42 2016
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.11.1
>  API version:  1.23
>  Go version:   go1.5.4
>  Git commit:   5604cbe
>  Built:        Wed Apr 27 00:34:42 2016
>  OS/Arch:      linux/amd64

**Output of `docker info`:**

Local Machine:

> Containers: 6
>  Running: 0
>  Paused: 0
>  Stopped: 6
> Images: 37
> Server Version: 1.11.1
> Storage Driver: aufs
>  Root Dir: /mnt/sda1/var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 53
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: null host bridge
> Kernel Version: 4.4.8-boot2docker
> Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
> OSType: linux
> Architecture: x86_64
> CPUs: 1
> Total Memory: 995.9 MiB
> Name: default
> ID: ZEUM:GEUJ:33UD:BTIU:7Y5L:VCP5:GH47:Z3M7:4E4O:W5AD:JVET:IUIN
> Docker Root Dir: /mnt/sda1/var/lib/docker
> Debug mode (client): false
> Debug mode (server): true
>  File Descriptors: 12
>  Goroutines: 29
>  System Time: 2016-05-17T17:57:22.278166553Z
>  EventsListeners: 0
> Username: 
> Registry: https://index.docker.io/v1/
> Labels:
>  provider=virtualbox

Remote machine:

> Containers: 1
>  Running: 1
>  Paused: 0
>  Stopped: 0
> Images: 2
> Server Version: 1.11.1
> Storage Driver: devicemapper
>  Pool Name: docker-253:0-892-pool
>  Pool Blocksize: 65.54 kB
>  Base Device Size: 10.74 GB
>  Backing Filesystem: xfs
>  Data file: /dev/loop0
>  Metadata file: /dev/loop1
>  Data Space Used: 485.4 MB
>  Data Space Total: 107.4 GB
>  Data Space Available: 12.96 GB
>  Metadata Space Used: 1.081 MB
>  Metadata Space Total: 2.147 GB
>  Metadata Space Available: 2.146 GB
>  Udev Sync Supported: true
>  Deferred Removal Enabled: false
>  Deferred Deletion Enabled: false
>  Deferred Deleted Device Count: 0
>  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
>  WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
>  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
>  Library Version: 1.02.107-RHEL7 (2015-12-01)
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: host bridge null
> Kernel Version: 3.10.0-327.13.1.el7.x86_64
> Operating System: CentOS Linux 7 (Core)
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 5.671 GiB
> Name: remoteserver
> ID: LQZS:VL5N:P3NM:YHFR:7IBM:TGLA:OCNR:LBGT:LB3X:VCQ6:OJK6:WQOA
> Docker Root Dir: /var/lib/docker
> Debug mode (client): false
> Debug mode (server): false
> Registry: https://index.docker.io/v1/
> WARNING: bridge-nf-call-iptables is disabled
> WARNING: bridge-nf-call-ip6tables is disabled

**Additional environment details (AWS, VirtualBox, physical, etc.):**
remote machine service ExecStart

> ExecStart=/usr/bin/docker daemon --insecure-registry servername:5000 -H fd:// -H tcp://0.0.0.0:2375

**Steps to reproduce the issue:**
1. setup as above
2. docker -H **remotehostname**:2375 images

**Describe the results you received:**

> An error occurred trying to connect: Get **https**://**remotehostname**:2375/v1.23/images/json: tls: oversized record received with length 20527

**Describe the results you expected:**

Expected to see the list of remote machines.

**Additional information you deem important (e.g. issue happens only occasionally):**

I attempted setting DOCKER_TLS=no on local docker machine and still received the same issue.

I am able to call curl **http**://**remotehostname**:2375/v1.23/images/json with no problems and receive output.

Is there an option to force plain http in the client per run?

**Comment by thaJeztah** [comment] 2016-05-17 18:36
I suspect you have other environment variables set, for example `DOCKER_CERT_PATH`;

```
docker -H 192.168.178.47:2377 run -it --rm hello-world
docker: An error occurred trying to connect: Post https://192.168.178.47:2377/v1.23/containers/create: tls: oversized record received with length 20527.
```

checking if there's env variables set;
```
env | grep DOCKER
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/sebastiaan/.docker/machine/machines/default
```

And unsetting those variables

```bash
unset DOCKER_HOST DOCKER_CERT_PATH DOCKER_TLS_VERIFY
```

And try again;

```bash
docker -H 192.168.178.47:2377 images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
hello-world         latest              94df4f0ce8a4        2 weeks ago         967 B
```

I'll close this issue, because this is not a bug, but I hope the above helps you

**IMPORTANT** I hope your "remote" host is a machine inside your private network, and NOT somewhere on the internet. Exposing the Docker API is equivalent to giving root access to your machine, so anyone that can get access to the API is able to take full control of that machine, not just docker!

**Closed by thaJeztah** 2016-05-17 18:36 UTC

**Comment by jonl-percsolutions-com** [comment] 2016-05-17 19:55
Yes, the "remote host" is on the internal network. Thanks, I was confused as to where these environment variables were set.  It appears that they are set in the mingw environment, which wasn't clear as I thought that the docker executable actually ran in the default docker machine as it appears to.  Was trying to diagnose why I could not connect the remote machine as a "docker-machine" using the generic driver.  After unsetting these and confirming the regular docker command could connect I now have a better understand as to how the docker command is running in Windows.  IE docker runs against a machine but still uses some local environment variables, which was the confusing part because I kept running into DNS issues when pushing to my internal private remote repo due to the DNS settings inside the default docker container causing issues and having to add it as an "insecure" server option which made the distinction not so clear.

**Comment by thaJeztah** [comment] 2016-05-17 19:59
Yes, the docker *daemon* runs inside the VM, but the client runs locally. The environment variables locally, are used by the client
