### ISSUE TITLE
Permission denied on /dev/stderr

### ISSUE THREAD

**Issue by pditommaso** [docker/docker#6880] opened 2014-07-07 15:33 UTC
The following Docker run command returns the showed error message: 

    docker run -u $(id -u) -v $PWD:$PWD -w $PWD ubuntu sh -c 'echo Hola > /dev/stderr'  
    sh: 1: cannot create /dev/stderr: Permission denied

Removing the `-u` command option it works fine. 

This issue make impossible to run that apps that use the `/dev/stderr` output stream to report warning messages or other info.

**Comment by jfrazelle** [comment] 2015-02-26 04:58
can you give exact steps to reproduce with latest docker

**Comment by znerol** [comment] 2015-02-26 07:42
@jfrazelle see the original report.

    docker run -u $(id -u) -v $PWD:$PWD -w $PWD ubuntu sh -c 'echo Hola > /dev/stderr'  
    sh: 1: cannot create /dev/stderr: Permission denied

This will try to run the `echo` command in an ubuntu container in the current working directory with the current user.

**Comment by jfrazelle** [comment] 2015-02-26 08:24
yep can reproduce

**Comment by CorbanR** [comment] 2015-06-10 21:26
any headway on this? I seem to also be running into this issue with docker 1.6 and kernel 3.13.0

**Comment by degano** [comment] 2015-07-02 08:30
@jfrazelle Any news on this? Perhaps has been fixed in 1.7? Thanks.

**Comment by LK4D4** [comment] 2015-07-02 16:29
It is not fixed in 1.7

**Comment by dbrgn** [comment] 2015-08-11 13:54
I'm also affected by this, also trying to redirect nginx (as non-root) access logs to /dev/stdout or /dev/stderr.

**Comment by samnf** [comment] 2015-08-11 23:02
Same here, using Docker version 1.6.2 and the php:5.4-apache image.

**Comment by jamesmoey** [comment] 2015-08-13 05:35
Using Docker version 1.7 also experience this issue.

**Comment by piti118** [comment] 2015-08-17 19:27
Depending on your usage of stdout. If you just want to print it to terminal so you can watch, you can workaround it by using

`/dev/tty` 

instead.

**Comment by IPvFletch** [comment] 2015-08-17 20:30
Does /dev/tty output it to the docker logs like other stdout text does?

**Comment by piti118** [comment] 2015-08-18 17:06
I just checked and it does.

**Comment by IPvFletch** [comment] 2015-08-18 17:35
piti118, you're right, it works!! I wonder if it only works when we allocate a tty. I will have to try it out some more. Thanks for the tip, you rock!!

**Comment by blueimp** [comment] 2015-08-19 09:59
Thanks for the tip @piti118.

It works well, when a terminal is allocated:
```sh
docker run --rm -t busybox su nobody -c 'whoami > /dev/tty'
# nobody
```

It won't work without the "-t" option, though:
```sh
docker run --rm busybox su nobody -c 'whoami > /dev/tty'
# sh: can't create /dev/tty: No such device or address
```

What should work would be the following, but it doesn't:
```sh
docker run --rm busybox su nobody -c 'whoami > /dev/stdout'
# sh: can't create /dev/stdout: Permission denied
```

This only works as root:
```sh
docker run --rm busybox sh -c 'whoami > /dev/stdout'
# root
```

The issue is still present on docker 1.8.1:
```sh
docker version
# Client:
#  Version:      1.8.1
#  API version:  1.20
#  Go version:   go1.4.2
#  Git commit:   d12ea79
#  Built:        Thu Aug 13 19:47:52 UTC 2015
#  OS/Arch:      darwin/amd64
# 
# Server:
#  Version:      1.8.1
#  API version:  1.20
#  Go version:   go1.4.2
#  Git commit:   d12ea79
#  Built:        Thu Aug 13 02:49:29 UTC 2015
#  OS/Arch:      linux/amd64
```

**Comment by devurandom** [comment] 2015-09-09 16:07
Does anyone know the cause of this? Why are the stdout and stderr FDs of a non-root process owned by root? When I list `/proc/self/fd` in a "normal" environment (i.e. outside of a Docker container), the files are owned by `$USER`.

**Comment by pwaller** [comment] 2015-09-09 16:26
@devurandom the root cause is discussed in more detail over here: https://github.com/docker/docker/issues/11462

It's not to do with ownership, it's that the target the target `pts` is not visible from the `/dev/pts` mount in the container:

```
$ docker exec -ti tmp bash
root@7699358d2400:/# ls -l /dev/stdout
lrwxrwxrwx 1 root root 15 Sep  9 16:20 /dev/stdout -> /proc/self/fd/1
root@7699358d2400:/# ls -la /proc/self/fd/1
lrwx------ 1 root root 64 Sep  9 16:21 /proc/self/fd/1 -> /dev/pts/10
root@7699358d2400:/# ls -l /dev/pts/10
ls: cannot access /dev/pts/10: No such file or directory
```

The error message when you do `echo foo > /dev/stderr` is actually that it cannot create `/dev/pts/10`. This is equivalent behaviour if you had tried to `echo > /dev/pts/thisdoesnotexist` because `/dev/pts` is not somewhere you are allowed to write, even as root.

**Comment by devurandom** [comment] 2015-09-09 20:02
Is there any workaround? A valid device representing `stdin`, `stdout`, `stderr`?

**Comment by pwaller** [comment] 2015-09-10 08:03
As far as I can see, you're welcome to modify what those point at inside your container or image, if you're willing to cope with the fallout. I doubt docker will be adopting such a workaround though… The problem generally is that those symlinks have to point to `/proc/self/fd/{0,1,2}`. If they pointed at anything else, then as soon as you invoke another program modifying `stdout`, `/dev/stdout` would be incorrect. So `run-foo > log` would not do the right thing if `run-foo` refers to `/dev/stdout`, for example. Doing this could lead to weird bugs where the output does not end up where you expect.

As far as I can tell, the only reasonable thing here is to fix #11462, but it seems architecturally complicated.

**Comment by daiyam** [comment] 2015-09-10 09:43
The new command `logs` promotes the use of `/dev/stdout` but only `root` can write there. But, for security, the use of `root` is not recommended. It's kinda problematic, isn't it.

**Comment by cpuguy83** [comment] 2015-09-10 14:36
Redirecting to /dev/stdout and /dev/stderr doesn't work, but you can still use stdout/stderr in your applications.

For instance `>&2 echo 'this goes to stderr'` works.

**Comment by devurandom** [comment] 2015-09-10 15:26
@cpuguy83 My case is `php5-fpm`, where I need to set `error_log = /some/file` in the config. There is no more direct way to make it output to stderr.

**Comment by daiyam** [comment] 2015-09-10 15:43
@devurandom Same here. That's why I'm thinking to move to `Fluentd`.

**Comment by crosbymichael** [comment] 2015-09-18 21:20
Fix is here and I'll update docker after it's merged in runc/libcontainer

https://github.com/opencontainers/runc/pull/280

**Closed** 2015-09-24 23:53 UTC
Labels: exp/expert, kind/bug

**Comment by Flavien** [comment] 2015-10-10 12:39
So is the fix shipped as part of the next Docker release?

**Comment by thaJeztah** [comment] 2015-10-10 12:57
@Flavien yes, that's the plan :-) if you want to try it, static builds can be found on https://master.dockerproject.org (don't use it in production, builds from master may contain bugs)

**Comment by ibukanov** [comment] 2016-01-09 09:27
As a workaround for docker versions before 1.9 I start an application when running non-root container from a wrapper shell script that does the following:
```
# Create a named pipe and redirect anything that comes to it
# to stderr connected to Docker.
mkfifo -m 600 /tmp/logpipe
cat < /tmp/logpipe 1>&2 &
exec original app command line 
```
Then I instruct the app (`php5-fpm` in my case) to log to `/tmp/logpipe`.

**Comment by luispabon** [comment] 2016-02-25 18:25
This is still an issue on 1.10.2. www-data cannot write to /dev/std* even though permissions are crazy permissive.

**Comment by luispabon** [comment] 2016-02-25 18:26
Also, cannot write to /dev/tty as "file not found" even though it's definitely there.

**Comment by willydee** [comment] 2016-05-20 13:39
Same issue hit me on docker 1.11.1 when running *lighttpd* and trying to redirect its access log to `/dev/stderr`. No way, since it starts as root, then drops privileges, and `/dev/std{in|out|err}` are not accessible any longer. See discussion at [https://redmine.lighttpd.net/issues/2731](url)

@ibukanov Thank you so much for the named pipe hint! Works like a charm.

**Comment by ibukanov** [comment] 2016-05-20 15:27
@willydee I have found that the above named pipe code may deadlock on a busy system. The fix was to change it into:
```
mkfifo -m 600 /tmp/logpipe
cat <> /tmp/logpipe 1>&2 &
```
where `<>` opens the pipe both for reading and writing before setting it as fd 0 for the cat. This way there is always a writer to the pipe and the cat never see EOF from the pipe due to absence of writers. Another improvement was to move `mkfifo` into the image to minimize container startup time.

**Comment by willydee** [comment] 2016-05-20 17:14
@ibukanov Thanks again for the update.

**Comment by eduncan911** [comment] 2017-01-05 18:48
Docker 1.12.5 - this is still is an issue?  non-root cannot write to /dev/stdout or /dev/stderr?

I read this thread twice and didn't see it "dismissed".  Just a work around script for:

    mkfifo -m 600 /tmp/logpipe
    cat <> /tmp/logpipe 1>&2 &

And while this does work, it's hacky and not documented.

**Comment by cpuguy83** [comment] 2017-01-05 19:20
@eduncan911 Yes, fixed some time ago by #16468

**Comment by nathanielks** [comment] 2017-11-14 01:21
For those coming here trying to figure out how to write access to `/dev/stderr` after having dropped privileges with `gosu`/`su-exec`/etc, I've added the following to my entrypoint script:
```
# Allow `nobody` user to write to /dev/stderr
mkfifo -m 600 /tmp/logpipe
chown nobody:nobody /tmp/logpipe
cat <> /tmp/logpipe 1>&2 &
```

The only difference from @ibukanov's version is that I'm changing the owner of `/tmp/logpipe` to `nobody` as opposed to it being `root` (as the container starts as a privileged user and will create `/tmp/logpipe` with `root` as the owner). I'm using the `nobody` user in my container, but it could just as easily be `www-data`, `nginx`, etc. Thanks again, @ibukanov!

**Comment by penguinwan** [comment] 2020-09-07 07:57
> As a workaround for docker versions before 1.9 I start an application when running non-root container from a wrapper shell script that does the following:
> 
> ```
> # Create a named pipe and redirect anything that comes to it
> # to stderr connected to Docker.
> mkfifo -m 600 /tmp/logpipe
> cat < /tmp/logpipe 1>&2 &
> exec original app command line 
> ```
> 
> Then I instruct the app (`php5-fpm` in my case) to log to `/tmp/logpipe`.

For those coming here tried FIFO but container crashed due to big blob of log, changing to `unbuffer` will prevent container from crashing
```
mkfifo -m 600 /tmp/logpipe
unbuffer cat /tmp/logpipe &
```
`unbuffer` from [expect package](https://pkgs.alpinelinux.org/package/v3.3/main/x86/expect)
