### ISSUE TITLE
Unable to chmod 755 for a file that should be created on an external volume.

### ISSUE THREAD

**Issue by icy** [docker/docker#12779] opened 2015-04-25 05:58 UTC
I have a volume from a base image. In new Dockerfile for new image, I use `ADD` to add a script to that volume, and then use `chmod 755` to fix the permission. However, the final image stills has permission 644 for the file.

Also note that the symlink will not work. All details can be found here https://github.com/icy/docker/tree/master/bugs/chmod_bug

I am not sure how Docker volume works, so this may not be a bug. But it's quite annoyed.

Thank you.

**Comment by icy** [comment] 2015-04-25 13:28
Dockerfile for new image. On the base-image (icy/empty), `/empty/` is a volume. When new image is built and a new container is created, in the `/empty/` there is only the file `/empty/chmod.sh` with `644` mode (this is wrong, it should be `755`; and there should be another file `fail.sh`.)

````
FROM icy/empty

MAINTAINER Anh K. Huynh "kyanh@theslinux.org"

# empty is a volume from `empty` container

ADD chmod.sh /empty/
RUN ln -s /empty/chmod.sh /empty/fail.sh
RUN chmod 755 -c /empty/chmod.sh

ADD chmod.sh /
RUN chmod 755 /chmod.sh

CMD ["/chmod.sh"]
````

**Comment by thaJeztah** [comment] 2015-04-25 14:03
The problem here is that Docker creates a *new* volume for each step in your Dockerfile, so each change you make to files/folders inside the volume will be "un-done" in the next build step.

If you are also the maintainer of the `icy/empty` image, remove the volume there and move the `VOLUME` to the end of your Dockerfile. If you're not the maintainer and it's a mistake in the image, you should contact the maintainer of that image.

Another solution could be to set the permissions in an "entrypoint" script, because that is executed when the actual container is launched (see, for example, the [entrypoint-script for the official MySQL image](https://github.com/docker-library/mysql/blob/1f430aeee538aec3b51554ca9fc66955231b3563/5.5/docker-entrypoint.sh#L57)). Hope this helps!

I'm going to close this issue, because this is not a bug in Docker, but feel free to comment after the issue is closed.

**Comment by icy** [comment] 2015-04-25 22:52
> The problem here is that Docker creates a new volume for each step in your Dockerfile, so each change you make to files/folders inside the volume will be "un-done" in the next build step.

If that's so true, why the permission is "un-done" but the file contents are not? And why the "ADD" file almost works by holding the file contents, but "RUN ln -s"  not? 

Is the feature documented some place ?

> If you are also the maintainer of the icy/empty image, remove the volume there and move the VOLUME to the end of your Dockerfile

Nice idea, but that's against the logic. A VOLUME is created commonly for different secondary images, not each secondary image creates its own VOLUME with the same name /empty/, that leads to a mess.

> Another solution could be to set the permissions in an "entrypoint" script, because that is executed when the actual container is launched

Nice idea. But the script has permission 644, how is it *executed*? The question is to write another script. 

A final question: Docker just makes simple thing complex, doesn't it?

**Comment by thaJeztah** [comment] 2015-04-25 23:10
Perhaps I'm missunderstanding the problem; the `VOLUME` is defined in the `icy/empty` base image and there's already a `chmod.sh` in there?

Also *which* `chmod.sh` is added successfully (because you're now adding it twice in your Dockerfile)

I'll re-open for now, so that we can discuss further

**Comment by icy** [comment] 2015-04-25 23:25
Sorry for my bad explanation because I created a Docker file to reproduce the problem (linked provided in the first post.) Here it is again :)

1. In the base image `icy/empty`, I create `/empty/` volume. (I can put some files there.)
2. In the new image `icy/chmod_bug`, I add a local file `chmod.sh` into `/empty/`, then use `RUN chmod 755` to make sure it's executable.
3. I don't expect the file `chmod.sh` exists the the `chmod_bug` container. But it's true that the file can be seen in `icy/chmod_bug`. Unfortunately, it's permission is now `644`; that means that the `ADD` command works, but `RUN chmod` didn't.

I have to add `chmod.sh` twice _(as you suggest)_; because the file `/empty/chmod.sh` is not executable and I have to use another one `/chmod.sh`.

**Comment by thaJeztah** [comment] 2015-04-26 04:47
Thanks for the extra explanation, I'm wondering if the permissions problem is related to AUFS, could you add the output of `docker version`, `docker info` and `uname -a`?

Also, I'm currently traveling and don't have access to my docker host, which makes it difficult to try and reproduce your issue.

/cc @cpuguy83 perhaps you can have a quick look? (bit difficult from my phone :))

**Comment by icy** [comment] 2015-04-26 06:06
The output of those commands are here https://raw.githubusercontent.com/icy/docker/master/bugs/chmod_bug/docker.info.txt. (I don't post here to make this post clean.)

Have a nice travel and weekend!

**Comment by icy** [comment] 2015-04-27 09:08
Actually, the problem is that after a `VOLUME` command, the `COPY/ADD` copy works, but the `RUN` command doesn't work. This is an inconsistent behavior.

Details are also explained in https://github.com/icy/docker/tree/master/bugs/volume_bug

**Comment by cpuguy83** [comment] 2015-04-27 13:30
Yes, there is currently no way around this other than don't use VOLUME in your Dockerfile (or at least not in your base images).
I've tried several times to fix this in the builder and none of the approaches were acceptable.

Closing since this is a dup of #3639

**Closed by cpuguy83** 2015-04-27 13:30 UTC

**Comment by icy** [comment] 2015-05-02 05:21
Thank you @cpuguy83  for the link and your confirmation. That saves a lot of time. Now I change my workflow and it works, though it's quite agaisnt the logic ;)

I hope you would find the best solution for that soon.
