### ISSUE TITLE
Docker cannot bind volumes with -v /d:/d syntax

### ISSUE THREAD

**Issue by ykzk** [docker/docker#20764] opened 2016-02-28 20:08 UTC
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:16:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:16:33 2016
 OS/Arch:      linux/amd64

```

Output of `docker info`:

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 304
Server Version: 1.10.2
Storage Driver: devicemapper
 Pool Name: docker-8:4-4458302-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.356 GB
 Data Space Total: 107.4 GB
 Data Space Available: 92.88 GB
 Metadata Space Used: 18.35 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.129 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51 GiB
Name: pt.64.re
ID: HUOH:JNP7:IZBC:DZRL:2GBC:SNKV:G5VH:34DZ:7JXY:MS4Y:IULX:AC5S
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. Partition mounted on /d on host
2. `docker run --name lighttpd -v /etc/localtime:/etc/localtime:ro -v /var/log/lighttpd:/var/log/lighttpd -v /d:/d -p 50003:80/tcp -p 55003:443/tcp -d lighttpd`
3.

Describe the results you received:
```
# docker inspect lighttpd
...
        "Mounts": [
            {
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/log/lighttpd",
                "Destination": "/var/log/lighttpd",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Name": "f5b778b83e61fd4d75bcce19ba48b658266d3df338257e2c7bf425c1438c4b6c",
                "Source": "/var/lib/docker/volumes/f5b778b83e61fd4d75bcce19ba48b658266d3df338257e2c7bf425c1438c4b6c/_data",
                "Destination": "/d:/d",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Name": "7f9863b0f1222f265af496c01bed1d2a23526973ab1b6360140d639d8b5b9246",
                "Source": "/var/lib/docker/volumes/7f9863b0f1222f265af496c01bed1d2a23526973ab1b6360140d639d8b5b9246/_data",
                "Destination": "/d",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
...
            "Volumes": {
                "/d": {},
                "/d:/d": {},
                "/var/log/lighttpd": {}
            },
```
In the container, I have empty `/d` and `/d:/d` folders

Describe the results you expected:
A working /d mount in the container, without a `/d:/d` folder.

Provide additional info you think is important:
Creating a symbolic link in the host from /data to /d and exporting /data in the container through `-v /data:/d` solves the issue.

**Comment by thaJeztah** [comment] 2016-02-28 22:36
Thanks for reporting @ykzk, however, this is a duplicate of https://github.com/docker/docker/issues/20122, so I'll close this one; please continue the discussion on that issue, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-02-28 22:36 UTC
