### ISSUE TITLE
Docker images/containers gone (devicemapper)

### ISSUE THREAD

**Issue by kapolos** [docker/docker#21718] opened 2016-04-01 11:17 UTC
I have been running a few sites inside containers  on an Azure VM, but and the images/containers are gone after a host reboot. Any idea what could be wrong or how I could retrieve the data?

This used to be an aufs installation that was at some point converted to devicemapper.

````
root@boxbox:/datadrive/dockerstore# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
root@boxbox:/datadrive/dockerstore# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
````

````
root@boxbox:/datadrive/dockerstore# docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-8:1-655364-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 59.54 GB
 Metadata Space Used: 733.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /datadrive/dockerstore/devicemapper/devicemapper/data
 Metadata loop file: /datadrive/dockerstore/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.16.0-29-generic
Operating System: Ubuntu 14.04.4 LTS
CPUs: 1
Total Memory: 3.362 GiB
Name: boxbox
ID: STRT:7755:73RU:BJ6W:3OKG:OUP4:6DGY:Z7O5:QPWF:HYKY:FC5W:KITI
WARNING: No swap limit support
root@boxbox:/datadrive/dockerstore# ls -l datadrive/dockerstore/devicemapper/devicemapper/data
ls: cannot access datadrive/dockerstore/devicemapper/devicemapper/data: No such file or directory
root@boxbox:/datadrive/dockerstore# ls -l /datadrive/dockerstore/devicemapper/devicemapper/data
-rw------- 1 root root 107374182400 Mar 27 05:00 /datadrive/dockerstore/devicemapper/devicemapper/data
root@boxbox:/datadrive/dockerstore# ls -l /datadrive/dockerstore/devicemapper/devicemapper/metadata
-rw------- 1 root root 2147483648 Mar 27 05:00 /datadrive/dockerstore/devicemapper/devicemapper/metadata
root@boxbox:/datadrive/dockerstore# 
````

````
root@boxbox:/datadrive/dockerstore# cat /etc/default/docker 
# Docker Upstart and SysVinit configuration file

# Customize location of Docker binary (especially for development testing).
#DOCKER="/usr/local/bin/docker"

# Use DOCKER_OPTS to modify the daemon startup options.
#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"
DOCKER_OPTS="-g /datadrive/dockerstore --storage-driver=devicemapper"

# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export TMPDIR="/mnt/bigdrive/docker-tmp"
````

**Comment by cpuguy83** [comment] 2016-04-01 12:05
"udev sync supported: false" could very likely be the cause.
This can cause data loss.
Also, did someone change the daemon opts to point to a new data dir?
Was it aufs before reboot and now it's devmapper?

**Comment by kapolos** [comment] 2016-04-01 12:22
@cpuguy83 Thank you for the response!

The new data dir was set by me when first setting up the server so that the data would be saved on a mounted "persistent" volume instead of the instance's "scratch" disk, so that was there from the beginning.

> Was it aufs before reboot and now it's devmapper?

I am not sure about this. I remember that during a docker upgrade (while still on aufs), the containers where "lost" and then I followed the migration to devmapper procedure found on the relevant Github issue and at that point everything was back to normal. I do not remember if I had rebooted it the machine after that though and I did not upgrade docker since then.

**Comment by unclejack** [comment] 2016-04-11 19:08
@kapolos I'm sorry to hear you're run into this issue. Your volumes should be available as directories under `/var/lib/docker/volumes`.

Based on the fact that `udev sync: false` shows up in your `docker info` output, your setup is unsupported. You need to install Docker using the recommended procedure provided in the official documentation for your distribution to ensure everything runs fine with devicemapper.

Please take a look at this page to get a supported setup: https://docs.docker.com/engine/installation/linux/ubuntulinux/

Since this question has been answered and the setup is unsupported, I'll close this now. Please feel free to comment.

**Closed by unclejack** 2016-04-11 19:08 UTC
Labels: area/runtime, kind/question

**Comment by omar7c1** [comment] 2018-06-04 15:02
You need add { "storage-driver": "devicemapper" } inside /etc/docker/daemon.json  and systemctl restart docker
