### ISSUE TITLE
docker failed to run

### ISSUE THREAD

**Issue by ekasatria** [docker/docker#19799] opened 2016-01-28 04:48 UTC
hi, im trying to run docker, but it shows these error

`FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?`

docker version shows this message
`Client version: 1.6.2`
`Client API version: 1.18`
`Go version (client): go1.2.1`
`Git commit (client): 7c8fca2`
`OS/Arch (client): linux/amd64`
`FATA[0000] Get http:///var/run/docker.sock/v1.18/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?`

i've try to solution that is mentioned here
`http://stackoverflow.com/questions/29294286/fata0000-get-http-var-run-docker-sock-v1-17-version-dial-unix-var-run-doc`
that are installing apparmor and adding user to docker group but dont work either

please help me thank you very much :)

**Comment by thaJeztah** [comment] 2016-01-28 06:13
Thanks for reporting @ekasatria, however, the GitHub issue tracker is for tracking bugs and feature request, and not meant for general support questions

Could you use one of the below;

1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.
4) StackOverflow

I'm going to close this issue, because this is not a bug, but a support question, but feel free to comment here after i've closed

**Closed by thaJeztah** 2016-01-28 06:13 UTC
