### ISSUE TITLE
how to support japanese or chinese in docker container

### ISSUE THREAD

**Issue by hordemark** [docker/docker#17198] opened 2015-10-20 02:46 UTC
I have a html include japanese that should be rendered in docker container and output to a image. But when I interview the image in browser. The japanese font was missing.  It seems that the centos7 images don't have support these fonts. 

Somebody help me

**Comment by hordemark** [comment] 2015-10-20 02:48
1. docker version

Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8/1.4.1
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8/1.4.1


2. docker info

Containers: 1
Images: 125
Storage Driver: devicemapper
 Pool Name: docker-253:0-1177445-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 16.13 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 14.21 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.8.1.el6.x86_64
Operating System: <unknown>
CPUs: 4
Total Memory: 3.743 GiB
Name: DLN-VM-CV14
ID: YT6U:YLFL:4OUG:TGUB:C5CR:RPH4:7BTR:LKS7:4ALN:RKRZ:PW2D:EOD7

3. uname -a

Linux DLN-VM-CV14 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hordemark** [comment] 2015-10-20 02:50
![image](https://cloud.githubusercontent.com/assets/3655955/10596593/641b749a-7718-11e5-8ec7-3480065a68e3.png)

**Comment by hordemark** [comment] 2015-10-20 02:51
![image](https://cloud.githubusercontent.com/assets/3655955/10596603/7d3a2ce6-7718-11e5-8e4b-99757b6b4875.png)

this is render in docker container

**Comment by thaJeztah** [comment] 2015-10-20 03:48
Hi @hordemark, the GitHub issue tracker is not a general support forum, but meant for tracking bugs and feature requests for docker.

Could you ask this question on one of these channels instead?:

- in the #docker IRC channel on Freenode.
- the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
- on https://forums.docker.com/
- on StackOverflow http://stackoverflow.com/questions/tagged/docker

I'm going to close this issue because this is not a bug or a feature request, but feel free to comment here after I've closed

**Closed by thaJeztah** 2015-10-20 03:48 UTC
