### ISSUE TITLE
Bind mount has wrong path in container if host directory name length is 1

### ISSUE THREAD

**Issue by khirbat** [docker/docker#21025] opened 2016-03-08 08:16 UTC
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 9
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 975.4 MiB
Name: virgo
ID: SCSO:PAMG:GSHD:HRWJ:3ZUZ:GUY5:O767:NBNW:7HJS:YU76:66VE:H2JM
WARNING: No swap limit support
```

List the steps to reproduce the issue:
1. Use host directory name of length 1 in bind mount 

> docker run -it -v /tmp/q:/tmp/foo debian

I expected /tmp/foo in the container, but got /tmp/q:/tmp/foo instead

Describe the results you received:
```
root@d2a093a55b9d:/# find /tmp
/tmp
/tmp/q:
/tmp/q:/tmp
/tmp/q:/tmp/foo
```

Describe the results you expected:
```
root@7317284dbcd9:/# find /tmp
/tmp
/tmp/foo
```

Provide additional info you think is important:

This looks like a bug in [splitVolumesN()](../blob/master/runconfig/opts/parse.go#L698)
volumeSplitN("/tmp/q:/tmp/foo", 2) does not split into two parts
volumeSplitN("/tmp/qq:/tmp/foo", 2) splits into two parts

Visit http://play.golang.org/p/N1ZAuqORou and click on Run.

**Comment by thaJeztah** [comment] 2016-03-08 11:19
Thanks for reporting @khirbat, looks like this is a duplicate of https://github.com/docker/docker/issues/20122. I'll close this one, please continue the discussion on https://github.com/docker/docker/issues/20122

**Closed by thaJeztah** 2016-03-08 11:19 UTC
