### ISSUE TITLE
when using custom CA for registry, docker doesn't use root store

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#22409] opened 2016-04-29 06:43 UTC
I don't know if this is a bug or a feature, but it took me a lot of debugging to understand what's going on.

**Output of `docker version`:**

```
Client:
 Version:      1.11.0-rc5
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   6178547
 Built:        Tue Apr 12 06:13:18 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc5
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   6178547
 Built:        Tue Apr 12 06:13:18 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 23
 Running: 15
 Paused: 0
 Stopped: 8
Images: 179
Server Version: 1.11.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 348
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.5-1-docker-aufs
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.709 GiB
Name: compooter
ID: GKSI:YHZC:YPNI:PAGO:EYPD:AYME:K6BY:BAIH:EBKQ:SOAK:WUFP:6MJM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 78
 Goroutines: 161
 System Time: 2016-04-28T23:34:34.88060447-07:00
 EventsListeners: 1
Username: viktorstanchev
Registry: https://index.docker.io/v1/
Cluster store: etcd://172.17.0.1:12379
Cluster advertise: 172.17.0.1:12376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine

**Steps to reproduce the issue:**
1. Have a custom registry with a private CA
2. Use S3 as your storage backend
3. Add your private CA to `/etc/docker/certs.d/$HOST/ca.crt`
4. Try to push

**Describe the results you received:**
Push goes through part of the way, and maybe uploads some layers, but fails at the end and gets into a retry loop. The daemon throws an unknown certificate error.

```
Apr 28 23:03:45 compooter docker[15542]: time="2016-04-28T23:03:45.582908585-07:00" level=debug msg="Calling POST /v1.23/images/xxx.us-west-2.compute.amazonaws.com/admin/repo/push?tag="
Apr 28 23:03:45 compooter docker[15542]: time="2016-04-28T23:03:45.637190954-07:00" level=debug msg="hostDir: /etc/docker/certs.d/xxx.us-west-2.compute.amazonaws.com"
Apr 28 23:03:45 compooter docker[15542]: time="2016-04-28T23:03:45.637266773-07:00" level=debug msg="crt: /etc/docker/certs.d/xxx.us-west-2.compute.amazonaws.com/ca.crt"
Apr 28 23:03:45 compooter docker[15542]: time="2016-04-28T23:03:45.664975110-07:00" level=debug msg="hostDir: /etc/docker/certs.d/xxx.us-west-2.compute.amazonaws.com"
Apr 28 23:03:45 compooter docker[15542]: time="2016-04-28T23:03:45.665052450-07:00" level=debug msg="crt: /etc/docker/certs.d/xxx.us-west-2.compute.amazonaws.com/ca.crt"
Apr 28 23:03:45 compooter docker[15542]: time="2016-04-28T23:03:45.665259710-07:00" level=debug msg="Trying to push xxx.us-west-2.compute.amazonaws.com/admin/repo to https://ec2-52-38-113-199.us-west-2.compute.amazonaws.com v2"
Apr 28 23:03:45 compooter docker[15542]: time="2016-04-28T23:03:45.915992125-07:00" level=debug msg="Pushing repository: xxx.us-west-2.compute.amazonaws.com/admin/repo:latest"
Apr 28 23:03:45 compooter docker[15542]: time="2016-04-28T23:03:45.916295502-07:00" level=debug msg="Pushing layer: sha256:c56b7dabbc7aa730eeab07668bdcbd7e3d40855047ca9a0cc1bfed23a2486111"
Apr 28 23:03:46 compooter docker[15542]: time="2016-04-28T23:03:46.634459263-07:00" level=debug msg="Assembling tar data for 09465c15837d65b27d6e1bd95a9301ac03ad442389a4131973bc7e63cf95d231"
Apr 28 23:03:49 compooter docker[15542]: time="2016-04-28T23:03:49.158102445-07:00" level=error msg="Upload failed, retrying: x509: certificate signed by unknown authority"
Apr 28 23:03:53 compooter docker[15542]: time="2016-04-28T23:03:53.158291643-07:00" level=info msg="Pull session cancelled"
```

**Describe the results you expected:**
I expected either a more graceful failure or for the docker daemon to use the root store AND the custom CA for the registry AND S3. It seems to get until the end of pushing the layers and then fail. I'm not sure exactly what I should expect though. I can understand people wanting to not include the root store when specifying a CA. It just needs to be more clear what's going on.

**Additional information you deem important (e.g. issue happens only occasionally):**
Some registry logs of this happening:
https://gist.github.com/vikstrous/0b4c806c9268f6646167bfa3d062edb5

**Comment by thaJeztah** [comment] 2016-04-29 11:29
Looks like a duplicate of https://github.com/docker/docker/issues/12756, so I'll close this, but let me know if this is different

**Closed by thaJeztah** 2016-04-29 11:29 UTC
