### ISSUE TITLE
Cannot start service nginx: oci runtime error: caused "not a directory"

### ISSUE THREAD

**Issue by dev6** [docker/docker#26822] opened 2016-09-22 14:46 UTC
**Mounting files or volumes from Linux host to container in docker-machine**

I have this user rights problem which I think is an issue with the docker itself and user rights assigned to it in Ubuntu version of Linux.
I first installed `docker engine, docker compose` and created basic Nginx, PHP containers. I used sudo privileges when creating and running these containers with no issues using `docker-compose` commands. The below error shows up when tried to up the containers without sudo privilege. But with sudo privilege, it goes just fine.

Then I had to install `docker-machine` on the same host for a different project with profiling tools in another container of the same machine. I have used docker compose for multiple containers inside default docker machine and this error shows up again. and if I use the sudo privilege to up the machines with `docker-compose`, it starts the previously created machines but not the ones from docker machine.

`ERROR: for nginx2  Cannot start service nginx2: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/6b530a05f392226181b788163191f813676f15e093f6118428c6b8f170966dad/etc/nginx/conf.d/default.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/6b530a05f392226181b788163191f813676f15e093f6118428c6b8f170966dad" caused "not a directory"`

**Steps to reproduce the issue:**
1. Install docker engine and docker compose and create basic LEMP machines using compose with sudo privileges.
2. Install docker machine on the same host and create a new project for LEMP using compose 2 without sudo privileges.
3. Try to up the containers from docker machine both with and without sudo privileges using compose version 2.

**Additional information important:**
All other containers are created successfully without sudo privileges except nginx2 service which has a mounting file option. The composer file looks like this:

```
version: '2'

volumes:
    database_data:
        driver: local

services:
  nginx2:
      image: nginx:latest
      ports:
          #- 8080:80
          - 8000:80
      volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      volumes_from:
          - phphalcon
  phphalcon:
      #container_name: phalcon
      #image: mileschou/phalcon
      #used dockerfile from phalcon repository defined above.
      build: ./php/
      expose:
          - 9000
      volumes:
          - .:/home/arch/Projects/Imgcs/docker/app2/app
  mysql2:
      image: mysql:latest
      expose:
          - 3306
      volumes:
          - database_data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: project
          MYSQL_USER: project
          MYSQL_PASSWORD: project
```
and if I am commenting out the volumes option from the nginx2 service, the container is created successfully without any requirement of sudo privileges.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 9
 Running: 3
 Paused: 0
 Stopped: 6
Images: 9
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: MUKX:D7B5:6G3Z:KD7W:TCX3:MUEO:5DP4:ZDIA:IB6P:PPDR:EYA5:AL3S
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 42
 Goroutines: 72
 System Time: 2016-09-22T14:45:20.667103537Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

```

**Comment by thaJeztah** [comment] 2016-09-23 09:25
This looks like a user error. Because you're running Docker in a Virtual Machine, the docker _daemon_ does not have access to your local files. Bind-mounted files are mounted from the host that the _daemon_ runs on (in your case, inside a Virtual Machine).

Although docker-machine / boot2docker has partial support for accessing files on the host (through VirtualBox guest additions) on Windows and Mac, this is _not_ supported on Linux.

If you specify a bind-mount (`-v <host-path>:<container-path>` or through the docker-compose file `volumes: -<host-path>:<container-path>`), the daemon checks if the file or directory at `<host-path>` exists, and if not, creates a _directory_ at that location.

In your example, you're trying to bind-mount a configuration file (`./nginx/default.conf`) from the host. Since that file is not present inside the VM, the daemon creates an empty _directory_ at that location, and bind-mounts it at `/etc/nginx/conf.d/default.conf` inside the container.

However, at that location, a _file_ exists, and bind-mounting a directory on top of a file fails, and produces the error.

Wondering; _why are you using a virtual machine to run docker in?_ Ubuntu supports running docker without the need for a Virtual Machine, and will give you _native_ performance, without the overhead of a Virtual Machine (see https://docs.docker.com/engine/installation/linux/ubuntulinux/), or VirtualBox guest additions (which has extremely poor performance)

I'm closing this issue, because this is not a bug, but I hope this helps

**Closed by thaJeztah** 2016-09-23 09:25 UTC
Labels: version/1.12

**Comment by dev6** [comment] 2016-09-27 10:49
I am sure this is something which leads to a bug in the docker engine core as I have seen it behaving in different ways with different user privileges. But I will dig more into it later when the bug is found with more proof to bring attention here.

I guess I was not clear in my first post here. I am not using Docker in a Virtual Machine. It is installed in native machine OS of Ubuntu Trusty Distribution. If anyone kind enough to follow the steps of creating this error described in the first post of this thread, they will see that it creates this weird error which is a leading direction to a potential bug in Docker Engine.

> However, at that location, a file exists, and bind-mounting a directory on top of a file fails, and produces the error.

Doesn't matter if the file exists at that location or not, the same error shows up as I have tried both with and without the file existence at that location.

I hope this gives the idea to devs here of what I am talking about on Ubuntu. If not, I can try to explain in a different way.

**Comment by thaJeztah** [comment] 2016-09-27 10:59
@dev6 your output of `docker info` shows that the daemon is running on a boot2docker Linux, not on Ubuntu;

```
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
```

What does `docker-machine ls` show?

**Comment by dev6** [comment] 2016-09-27 11:06
The `docker-machine ls` shows this:

```
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default   -        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.1   
```

I had to install docker-machine after the installation of docker-engine as I needed to have an IP address for one of the profiling tools to work with curl. And the curl was failing to get it from localhsot:PORT.

**Comment by thaJeztah** [comment] 2016-09-27 11:14
So in that case, the docker daemon is running in a VirtualBox VM (see my comment before I closed the issue)

> had to install docker-machine after the installation of docker-engine as I needed to have an IP address for one of the profiling tools to work with curl. And the curl was failing to get it from localhsot:PORT.

This _should_ work, if the container has its port published. Is the profiling tool running in a container, or on the host? Also, make sure to check there isn't a firewall rule that block it, and, it may be worth using `curl -4 ...` in case the machine has IPv6 enabled, and curl tries to use an IPv6 address for localhost

**Comment by dev6** [comment] 2016-09-27 13:45
Yes, the profiling tool is running in a container. Tried disabling firewall and IPv6 as well but same error where curl can't find the host at localhost:Port.

**Comment by thaJeztah** [comment] 2016-09-27 15:20
That's expected. `localhost` in a container is the localhost of the container itself, so if you try to use `localhost:port`, curl is trying to connect to the localhost of the container it is running in.

You can either change this to `<public-ip-of-the-docker-host>:<port>` or, to prevent going "outside" of the host just to connect to another container, use a container-container network and directly connect to the other container.

For example:

```bash
# create your custom network
docker network create my-network

# run the web server, and connect it to the network
# also publish port 80 of the container at 8080 on the host
# give the container a name, so that you can connect to it
# using its "name" as hostname from another container
docker run -d --network=my-network --name web -p 8080:80 nginx:alpine

# run another container, and connect to the "web" container
# note that on the container-container network, you connect
# to the _regular_ port of the container (port 80 in this case)
docker run -it --rm --network=my-network alpine sh

/ # wget -qO- web
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```


Read about networking here; https://docs.docker.com/engine/userguide/networking/

**Comment by dev6** [comment] 2016-09-28 14:37
I guess that is already taken care when you are using compose to build and start the containers. They are all attached to a new custom network. Here is my `docker network ls`

```
NETWORK ID          NAME                DRIVER              SCOPE
fa15b06ef3aa        app2_default        bridge              local               
1a297b1e6ec8        bridge              bridge              local               
04bc689b678f        docker_default      bridge              local               
f7e82e4bfc2b        host                host                local               
47347dc570c0        none                null                local
```

And `docker network inspect docker_default` gives all the containers linked together.
```
[
    {
        "Name": "docker_default",
        "Id": "04bc689b678fb1d036c72a69eb4aea4b86f9716881b623babf98d066842a4332",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "1992a97d22675c21c1a29e1b9d7de40b375817864082146544d7a57c32999b2c": {
                "Name": "docker_mysql_1",                                                                                                                 
                "EndpointID": "9eaaa16d9e58883d3aca94016367b015b4f438256d7f02b64cb34b343c61baa5",                                                         
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "303c25b6e74bba6cf9eb62a40b61e872093a4106d349ae5eecd39ff83888a608": {
                "Name": "docker_php_1",
                "EndpointID": "5174b700e4c7f84115b5389b98e85a55904f28efaba6bf77ff6706be0f3d05de",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },
            "6afdc60ef0771a0f7955de6507ea9d029f6849996a3f9c22e0a4af638e899520": {
                "Name": "docker_blackfire_1",
                "EndpointID": "5bb534140405754a4fa0db1d901813b886f2daec2afecddfa89cfaa5a2980ac4",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "7de81c23de087d79c9b513b6f6f75a0f14b940d8e2a33524e020c7d294fecb08": {
                "Name": "docker_nginx_1",
                "EndpointID": "769be3ad76b4a0ea6f581ca734b78fe6f55a1e3d89f4759135cc7154c452ade2",
                "MacAddress": "02:42:ac:12:00:05",
                "IPv4Address": "172.18.0.5/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

**Comment by Pakito83** [comment] 2016-10-28 13:37
On Windows maybe "shared drives" on app's settings works.
![capture](https://cloud.githubusercontent.com/assets/1780906/19808198/ea22eb7c-9d23-11e6-8adf-92857a0f3f45.PNG)

**Comment by michaelstoiber** [comment] 2017-01-16 10:55
I'm not sure, if you found already a solution for your problem, but by the way, you find the problem named in the error message: caused "not a directory"
This is because you try to mount a file "default.conf" to a file, but you can only mount directories...
So try:
`./nginx:/etc/nginx/conf.d:rw`

**Comment by MikeMcTiernan** [comment] 2017-02-08 20:17
@michaelstoiber:

> This is because you try to mount a file "default.conf" to a file, but you can only mount directories..

This is incorrect. You can mount files directly. The issue is what others have pointed out in this thread, that if you try to mount a file that does not exist, the container will create an empty directory at that location. If you then try to mount the file after it exists on your host, it throws an error because an empty directory exists at that location on the container. But there's no issue with mounting individual files from the host machine to the container.

**Comment by thaJeztah** [comment] 2017-02-08 21:10
@MikeMcTiernan one pitfall is that on native Windows containers, bind-mounting single files is not possible

**Comment by cian0** [comment] 2017-10-30 06:25
I was on a Windows machine when this happened. I used Laradock's pre-made containers, what happened was our organization forced our PCs to change passwords so I did. I didn't know that Docker stores credentials as well, I updated it at **Docker > Shared Drives > Reset credentials... > Apply**

I'm no longer getting the php-fpm permissions denied error.
