### ISSUE TITLE
Docker should use the host network DNS server

### ISSUE THREAD

**Issue by nottrobin** [docker/docker#23910] opened 2016-06-23 19:58 UTC
# Summary

In networks where external DNS servers are blocked, Docker containers running on Ubuntu hosts can't resolve DNS at all because they are trying to use `8.8.8.8` as their DNS server. Docker should detect the network DNS server.
# Detail

When spinning up a container, [Docker will by default](https://docs.docker.com/engine/userguide/networking/configure-dns/) check for a DNS server defined in `/etc/resolv.conf` in the host OS, and if it doesn't find one, or finds only `127.0.0.1`, will opt to use [Google's public DNS server](https://developers.google.com/speed/public-dns/) `8.8.8.8`.

My development machine is running [Ubuntu 16.04](http://releases.ubuntu.com/16.04/) which uses [dnsmasq](https://wiki.debian.org/HowTo/dnsmasq) by default, so `/etc/resolv.conf` is always set to `127.0.0.1`, even though it is usually actually getting its DNS settings from whatever network its connected to:

``` bash
$ cat /etc/resolv.conf | grep nameserver  # What Docker sees
nameserver 127.0.1.1
$ nmcli dev show | grep IP4.DNS  # My actual DNS server
IP4.DNS[1]:                             10.1.1.3
```

and so Docker containers always default to using `8.8.8.8` rather than using the same DNS server as the host OS.

In my office network external DNS servers are blocked, and so me and my whole team are finding docker containers failing with obscure errors which result from failing to resolve DNS.

There is [a workaround](https://robinwinslow.uk/2016/06/23/fix-docker-networking-dns/#the-permanent-system-wide-fix), which I help walk all my team members through so they can still use Docker. Although it's frustrating that whenever Docker gets updated, it seems the daemon config file is overwritten and we have to implement the fix all over again. This is less of a problem for me, but is causing significant trouble for our less systems-focused developers.

Is there any hope that Docker might be able to intelligently pick up the network's DNS server in the future?
## Steps to reproduce the issue
1. Use a host OS that makes use of `dnsmasq` (e.g. Ubuntu since `12.04`)
2. Connect to a network that blocks access to external DNS servers like `8.8.8.8`
3. Try to resolve DNS with Docker (`docker run busybox nslookup google.com`)
## What I get

``` bash
$ docker run busybox nslookup google.com
Server:    8.8.8.8
Address 1: 8.8.8.8

nslookup: can't resolve 'google.com'
```
## What I expected

``` bash
$ docker run busybox nslookup google.com
Server:    10.1.1.3
Address 1: 10.1.1.3

Name:      google.com
Address 1: 2a00:1450:4009:811::200e lhr26s02-in-x200e.1e100.net
Address 2: 216.58.198.174 lhr25s10-in-f14.1e100.net
```
## System information

I'm running Xenial natively on a Dell XPS 13 9350.

``` bash
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 61
 Running: 3
 Paused: 0
 Stopped: 58
Images: 421
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 441
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.54 GiB
Name: xps
ID: G4MN:GTXD:4KZP:PTZC:DBYK:WOLA:R3GF:TKLW:ZOOX:NXZT:ALNG:F22D
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: nottrobin
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Comment by nathanleclaire** [comment] 2016-06-23 21:03
@mavenugo @mrjana FYI

**Comment by cpuguy83** [comment] 2016-06-24 14:14
The systemd unit file should not be edited directly.
Systemd has a facility called "drop-ins" that allow you to override/augment the unit file.
https://docs.docker.com/engine/admin/systemd/

In addition, it would probably be best to configure the docker daemon via it's config file rather than the systemd unit file. By default docker reads config from `/etc/docker/daemon.json`. https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file

**Comment by nottrobin** [comment] 2016-06-24 17:48
Ah! Wonderful suggestions. Thanks @cpuguy83, I'll update my blog post.

**Comment by ovidiub13** [comment] 2016-06-30 14:12
I've solved this by adding a daemon configuration file. But I would sure love for this to be implemented.

**Comment by iflowfor8hours** [comment] 2016-08-20 08:35
@cpuguy83 Nice one, I didn't know about the `/etc/docker/daemon.json`. Might that file get created in a default install to signal to users this is where configuration should live? I went straight for the systemd drop-ins.

**Comment by justincormack** [comment] 2016-08-20 10:22
It is not very easy to implement this as docker has no way to know the
upstream servers. If you set your local DNS relay on localhost to also
listen on the docker0 IP and put that address in resolv.conf that would
also work.

On 30 Jun 2016 3:12 p.m., "Ovidiu-Florin BOGDAN" <notifications@github.com>
wrote:

I've solved this by adding a daemon configuration file. But I would sure
love for this to be implemented.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/issues/23910#issuecomment-229670387>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAdcPFlthUzL2cze4iV_wGe0xRFhQPRpks5qQ87WgaJpZM4I9Lm8>
.

**Comment by nottrobin** [comment] 2016-09-09 08:24
@justincormack I can discover the DNS servers by doing `nmcli dev show | grep DNS`. Couldn't docker do something similar? I mean, more generally, if the system knows its DNS servers (which it must) then surely docker can discover them somehow.

**Comment by awilkins** [comment] 2016-09-19 10:59
On Ubuntu, I settled on doing this ( as @justincormack describes)  by...

* Adding a `/etc/docker/daemon.json` that passed in the `docker0` bridge IP as a DNS server
* Adding a `/etc/NetworkManager/dnsmasq.d/docker-bridge.conf` file that directs the NM-managed DNS cache to listen to the `docker0` bridge IP as well as 127.0.1.1

Now container DNS lookups go through your local `dnsmasq` instance, so DNS in the container should work just as well as DNS on the host.

@nottrobin - my problem specifically was that my system *did* know it's DNS servers and *was* passing them to the container - but because those servers were on a VPN, there was no route to them from inside the container, hence all DNS lookups failed.

**Comment by justincormack** [comment] 2016-09-20 15:05
@nottrobin `nmcli` only applies to systems running `NetworkManager`, there is not an equivalent for other setups.

**Comment by iraadit** [comment] 2016-10-10 13:55
Thank you A LOT for the workaround @nottrobin, working great even when doing "docker build"
It had been three days of looking for a solution without success before finding your post

**Comment by bsingr** [comment] 2016-11-23 17:35
@awilkins solution works.

Additionally it requires to allow port 53 traffic on the ubuntu firewall for the `docker0` bridge ip.

Quick test: disable the ubuntu firewall completely with `sudo ufw disable`

**Comment by krak3n** [comment] 2016-12-01 13:24
@bsingr what rule did you use? I've tried loads and can't get it to work on Ubuntu 16.04 - i've resorted to `host` network mode 😭

**Comment by sanimej** [comment] 2016-12-19 08:46
@nottrobin Instead of trying to detect the external resolver used by the host resolver the better approach is to allow the containers' DNS queries to be forwarded to the host resolver if the `resolv.conf` has a loopback address. Using the host resolver [has other use cases](https://github.com/docker/docker/issues/14627) as well. Its doable with the docker embedded DNS server which is used by default for user defined networks. I pushed a PR in libnetwork for this.

**Comment by butlermd** [comment] 2017-01-09 17:39
@awilkins or @bsingr, do either of you have more details about how you configured `docker-bridge.conf`? The `daemon.json` file seems like it should be simple enough:

```json
{
  "dns": [
    "172.17.0.1"
  ]
}
```

But I'm unclear on how you configured dnsmasq.

**Comment by awilkins** [comment] 2017-01-09 17:47
On ubuntu, add a file `/etc/NetworkManager/dnsmasq.d/docker-bridge.conf`

```
listen-address=172.17.0.1
```

**Comment by butlermd** [comment] 2017-01-09 17:48
@awilkins Thanks for the clarification!

**Comment by awilkins** [comment] 2017-01-09 17:54
Also looks like a PR with support for doing this less cryptically landed a few days ago

https://github.com/docker/libnetwork/commit/1ed42d1d80df69f348f0a2bf503e16deba69d4f4

**Comment by sanimej** [comment] 2017-01-09 17:58
@awilkins Yes, it doesn't work for `docker0` bridge because the Docker DNS server is used only for the user created networks. The fix to forward the queries to host loopback resolver relies on the embedded DNS server.

**Closed** 2017-01-11 18:55 UTC
Labels: area/networking, version/1.11

**Comment by dqminh** [comment] 2017-01-16 11:37
@sanimej just to make sure i understand the patch correctly, it only allows docker embedded DNS server to forward queries to the local nameserver ?

We are using https://github.com/gliderlabs/hostlocal, which will still be required if we dont want to use docker embedded DNS server, is that correct ?

**Comment by sanimej** [comment] 2017-01-17 08:08
@dqminh Yes, this patch essentially differentiates between loopback IP in the container namespace vs host namespace. This allows the embedded DNS server to forward the queries appropriately. From a quick glance it looks like `hostlocal` package is intended to be used with containers in `net=host` mode. This patch is not relevant in that case.

**Comment by dqminh** [comment] 2017-01-17 15:57
@sanimej i think hostlocal should work in bridge mode as well since it adds a route in the host. Thanks for the confimation about the embedded DNS server.

**Comment by setiseta** [comment] 2017-01-30 21:10
hm, just to ask, is it possible to setup a dnsmasq in a container as default dns for other dockers in any way?
i just cant find a description about this on the internet.
is this not possible?

**Comment by webdobe** [comment] 2017-06-14 22:30
I ended up resolving this by adding the following to my php container: 
`extra_hosts:
     - "mycustomdomain.whatever:172.17.0.1"`

Since it is my dev this was an easy enough fix.

**Comment by xenithorb** [comment] 2017-06-14 22:34
I resolved it in the following manner @webdobe https://opsech.io/posts/2017/May/23/docker-dns-with-firewalld-on-fedora.html

**Comment by alu** [comment] 2017-08-29 11:18
@sanimej 

Hi. I have a question that is How resolve 127.0.0.1 in container.
I read around [here](https://github.com/docker/libnetwork/blob/master/sandbox_dns_unix.go#L222-L269) and my answer is below.

1. If `--dns` option apply when docker run or stack deploy, 127.0.0.1 refer to container self.
2. if `/etc/resolv.conf` includes `127.0.0.x` nameserver, 127.0.0.1 refer to host that is running it.

Is it right?

Thanks.

**Comment by zanaca** [comment] 2017-12-22 19:24
Guys, for that "problem"  I have made [docker-dns](/zanaca/docker-dns).

**Comment by mimousewu** [comment] 2018-01-25 13:34
@zanaca Realy Thanks! This DNS issue last for years. I don't know why the official guys seem bland for this. And even you can not find any detail about how it implements.

**Comment by akravetz** [comment] 2018-02-26 16:35
+1 surprised this is still an issue.  Really complicates our dev process using ubuntu on vmware.

**Comment by nileio** [comment] 2018-03-09 12:07
+1 still an issue and it is annoying!!

**Comment by nottrobin** [comment] 2018-03-12 18:03
Yes I'm not quite sure why this is closed. A new team member in our team just installed docker fresh and ran into this problem all over again, and had to follow [my blog post](https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/) to fix it, and I'm frequently getting pings on Twitter because random strangers have similarly had to use my blog post to get Docker working.

I am quite amazed that over a year and a half later it hasn't been deemed important enough to find a proper fix for Ubuntu users - even though it may be a tough problem.

**Comment by ericparton** [comment] 2018-03-24 19:01
@nottrobin I'm still running into this problem as well, but oddly enough it only seems to affect containers on user defined bridge networks. 

So this command will succeed:
`docker run busybox nslookup google.com`

..but this command won't:
`docker run --network my_bridge_network busybox nslookup google.com`

I do have other name servers in the resolv.conf in addition to the loopback address, but I don't know if that's a factor.

**Comment by moy** [comment] 2018-04-24 12:56
I tried summarizing the possible solutions here: https://stackoverflow.com/questions/49998099/dns-not-working-within-docker-containers-when-host-uses-dnsmasq-and-googles-dns

Feel free to add or edit answers there.

**Comment by dashesy** [comment] 2018-05-02 17:09
@moy your answer [here](https://stackoverflow.com/a/50001940/311567) is the cleanest way to handle this. I wonder why installing docker does not just drop a `/etc/NetworkManager/dnsmasq.d/docker-bridge.conf` and fix daemon.json to fix the problem for all.

**Comment by nottrobin** [comment] 2018-05-18 14:16
@moy that did not work at all for me or by boss, both on Ubuntu 18.04. Shame, I was excited about it.

**Comment by moy** [comment] 2018-05-18 15:27
@nottrobin : any detail on what did not work? I tested my answer on a Ubuntu 16.04 virtual machine (to start from a clean install) and on my laptop (was still Ubuntu 16.04 at the time, but I can re-test with 18.04 when I get it into a network where public DNS are filtered).

**Comment by nottrobin** [comment] 2018-05-18 16:56
@moy I'm afraid I don't have very deep knowledge of what didn't work, all I can tell you is the steps I took:

- Check `ip addr` to confirm that `docker0` is mentions `inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0`
- Add `listen-address=172.17.0.1` to `/etc/NetworkManager/dnsmasq.d/docker-bridge.conf`
- `sudo service network-manager restart`
- Tried `sudo docker run -ti --dns 172.17.0.1 mmoy/ubuntu-netutils ping www.example.com`, which couldn't find the host
- Added `{"dns": ["172.17.0.1"]}` to `cat /etc/docker/daemon.json`
- `sudo service docker restart`
- `sudo docker run -ti mmoy/ubuntu-netutils ping www.example.com` still couldn't find the host
- I also tried the method of host lookups used in my blog post: `docker run --dns 172.17.0.1  busybox nslookup google.com` or `docker run busybox nslookup google.com`, they didn't work either

If you let me know something I can do to debug this, I'll try to find time to look into it further.

**Comment by moy** [comment] 2018-05-18 17:12
Make sure dnsmasq is actually running on your machine (it wasn't on my Ubuntu 18.04, not sure whether I removed it or the upgrade did).

From the host, try:

    host www.google.com 127.0.0.1

This should work, and should force querying the dnsmasq server.

**Comment by moy** [comment] 2018-05-21 08:20
Check that it's actually dnsmasq. Google suggests that this IP is used by systemd-resolved, and systemd-resolved was installed on my ubuntu 18.04. If this is the case, then my instructions will have to be adapted to systemd.

**Comment by jerrac** [comment] 2018-07-24 21:17
I just spent a long time trying to figure out why my containers couldn't resolve any domains. This issue is the closest I found to an answer.

I'm on Ubuntu 18.04. Docker version 18.06.0-ce, build 0ffa825.

Ubuntu is not using dnsmasq, at least I think. Judging from the comments in this issue and [the SO post](https://stackoverflow.com/questions/49998099/dns-not-working-within-docker-containers-when-host-uses-dnsmasq-and-googles-dns/50001940#50001940) my system is using systemd-resolved.

My host can find google.com, etc, just fine.

If I run a container, the container cannot resolve any domains unless I use `--network host`. 

I double checked that my docker daemon service file was told to load the daemon.json file. Note, I have stopped docker from managing the firewall. 

I also flushed iptables just to make sure the firewall wasn't in the way.

I've modified my daemon.json file so that it contains my workplaces dns ip's, as well as 1.1.1.1 and 8.8.8.8.

I tried disabling /lib/systemd/system/resolveconf.service and /lib/systemd/system/systemd-resolved.service using systemctl. That ended up breaking dns for my whole system.

I tried creating a custom bridge network and using that when running my containers, the container was still unable to resolve domain names.

Is there anything else I can try?

**Comment by denji** [comment] 2018-07-25 05:37
@jerrac resolve via `ipv6` or `ipv4`?

**Comment by jerrac** [comment] 2018-07-25 16:55
@denji  My workplace network is `ipv4` only. My host is not configured to use `ipv6` on any network. (It's a laptop.)

**Comment by awilkins** [comment] 2018-07-25 18:25
As someone else who's run into this : (see my answer on [askubuntu](https://askubuntu.com/questions/475764/docker-io-dns-doesnt-work-its-trying-to-use-8-8-8-8/826894)... 

Ubuntu 18.04 exacerbates this by replacing the NetworkManager managed instance of dnsmasq with `systemd-resolved`.

`systemd-resolved` doesn't listen to the `docker0` network bridge adapter - and can't be configured to do so, it will only listen on it's hardcoded loopback address.

I worked around this on Ubuntu 18.04 by

* Disabling the local UDP server on `systemd-resolved`
* Installing the NetworkManager dnsmasq support again
* Reconfiguring it as described in my answer but also 
* Reconfiguring it's primary listen address to 127.0.0.53 (because something in systemd still writes this to `/etc/resolvconf` and I couldn't work out how to disable that)

**Comment by dashesy** [comment] 2018-07-25 18:44
@awilkins this sounds like a bug, in systemd. Have you tried opening a bug with them? sure there are more people who use docker and want to try Ubuntu 18 host!

**Comment by awilkins** [comment] 2018-07-25 20:04
It appears to be a design choice, rather than a bug : 

[It deliberately only binds to the loopback adapter](https://github.com/systemd/systemd/blob/4d09e1c8bab1d684172b1f277f3213825b30d2d9/src/resolve/resolved-dns-stub.c#L425-L427)

This seems to work properly now ... if you [don't use the default network](https://github.com/docker/libnetwork/issues/1654). Have just tested this and using a non-default network results in `/etc/resolv.conf` in the container using `127.0.0.11` - which is docker's [embedded DNS resolver](https://docs.docker.com/v17.09/engine/userguide/networking/configure-dns/).

While this is a PITA it's work-around-able, by specifying a non-default network. Mostly I use `docker-compose` with networks defined in my compose files so this will happen by default. `docker build` and other ad-hoc docker commands accept --net params.

If you want the total convenience of it Just Working™, there's still the option of turning off that `systemd-resolved` stub and installing dnsmasq (using the NetworkManager one is still easiest for me on 18.04)

**Comment by jerrac** [comment] 2018-07-25 23:51
@awilkins I did try `docker network create ...` and then using that custom bridge network when I used `docker run`. I still ran into the dns issues.

Oddly, if I try the same thing using docker-compose, and a named network, the dns issues go away.

So, what's the different between a docker-compose named network and a `docker network create` network?

**Comment by awilkins** [comment] 2018-07-26 19:39
That seems to work fine for me. Is the problem docker's excruciating pickiness about argument order?

```
$ docker network create cheese
db2e8491afea95700120a3615d01e7507c45cfe2b34397641eb286a1de4ed44c
$ docker run --net cheese bash cat /etc/resolv.conf
nameserver 127.0.0.11
$ docker run  bash cat /etc/resolv.conf
nameserver 172.17.0.1
```

**Comment by venkat-koppisetti** [comment] 2018-08-20 09:59
**Docker container should not resolve DNS in Ubuntu 18.04** 
**I want to access server with name from inside container**
Am running a container with --dns flag with host's DNS server IP 
docker run -itd  --dns 127.0.0.53 --name test_img

But from inside container am not able access google server

[root@0b86fa7dde50 scripts]# curl google.com
curl: (6) Could not resolve host: google.com; Unknown error
[root@0b86fa7dde50 scripts]#


**Host DNS details:**
root@rebaca# nslookup google.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   google.com
Address: 216.58.194.206
Name:   google.com
Address: 2607:f8b0:4005:805::200e

without that --dns flag in docker run command, am bale to access google.com as because by default container is running with 8.8.8.8 dns server

But am  not able to access my consul server with Domain name.

**How would i access consul server and google server with domain names without adding details in /etc/hosts file**


**docker info:**
root@rebaca:~# docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1012-azure
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.768GiB
Name: azuki-container-test-ehesste
ID: CRS6:TA4X:OTTN:X6TW:GCW5:D5U5:KUTH:JFFB:OF24:FAJ7:WOMF:YIJH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**root@rebaca:~# cat /etc/os-release**
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by alexsuter** [comment] 2018-08-20 12:18
Same problem here. I use docker containers to build my software. They need access to internal build repository, which are not accessible, without an internal name server. How to setup docker properly which uses an internal nameserver?

**Comment by awilkins** [comment] 2018-08-20 16:53
For Ubuntu and now even worse on Ubuntu 18.04 ; 

Short answer : don't use the default network.
Longer answer : you can reconfigure your way around this if you want everything to Just Work™

As per my [AskUbuntu answer](https://askubuntu.com/questions/475764/docker-io-dns-doesnt-work-its-trying-to-use-8-8-8-8/826894#826894) ; the way around this is to tell docker to use your local DNS service for lookups.

**BUT** Ubuntu 18.04 has moved from a NetworkManager managed instance of `dnsmasq` to `systemd-resolved` for DNS. And `systemd-resolved` won't listen to requests coming through your `docker0` bridge - the bridge for the default network.

Docker does this *correctly* in user-defined networks - it configures the container to use it's own DNS proxy on `127.0.0.11` in `/etc/resolv.conf`, and those lookups go through whatever your system is configured to use (confirmed by disabling `systemd-resolved` and watching lookups time out).

For reasons of legacy compatibility, it doesn't do this correctly in the default network. The developers have indicated to me they are not opposed to adding a config parameter to replicate the user-defined network behaviour in the default network, and that would seem to be the easiest path in the future. For now....

So my workaround is now to disable `systemd-resolved`, and to re-enable the NetworkManager managed instance of `dnsmasq`, configure it to listen on 127.0.0.53, rather than it's default (to match the new default `/etc/resolv.conf`), and then effect the changes from my answer linked above.

This is not perfect, I'm sure.

**Comment by jcberthon** [comment] 2018-08-23 21:26
I have read the Docker documentation on DNS and containers. So if the `/etc/resolv.conf` contains only localhost IPs (like `127.0.0.53` when one uses `systemd-resolved` which seems default on Ubuntu 18.04 at least), Docker will drop those and not have any localhost IP, so defaulting to 8.8.8.8 (btw not the best solution in terms of privacy...).

However reading the documentation of `systemd-resolved` one can see that they are maintaining another file `/run/systemd/resolve/resolv.conf` (at least that's the path on Ubuntu) with all known DNS server. They do not recommend using it directly as it by-passes their service. But what would be reasonable algorithm for Docker would be:

1. Read `/etc/resolv.conf` and list all non-localhost IP
2. If the list of DNS resolver is empty, then check file `/run/systemd/resolve/resolv.conf` and list all non-localhost IP
3. If the list is empty use 9.9.9.9 or 1.1.1.1 or 8.8.8.8

That way on Ubuntu (and other systems using systemd-resolved) Docker will still find the right DNS server to use.

**Comment by dashesy** [comment] 2018-08-23 22:59
@jcberthon if it is a symlink [/run/systemd/resolve/resolv.conf](https://github.com/systemd/systemd/issues/9450] it should already work. Why is it not recommended to use it?

**Comment by awilkins** [comment] 2018-08-24 09:09
@dashesy Because `systemd` doesn't want you to read `/etc/resolv.conf` either because it implies you're doing your own DNS lookups. It wants all DNS lookups to use either the the NSS glibc `getaddrinfo()` call, [or use it's dbus API](https://www.freedesktop.org/wiki/Software/systemd/resolved/).

I would honestly prefer (especially on my workstation) all DNS lookups from docker containers to be proxied through the host, because it means that if I e.g. sign into a VPN with it's own search domain and DNS service, then docker containers will just be able to resolve names in there without any additional effort.

e.g. the scenario where you sign into a VPN and it splats your `/etc/resolv.conf` with the DNS server inside the VPN. (this is a badly behaved VPN client that doesn't integrate with NetworkManager).

* My host can now correctly do lookups of host names inside the VPN
* Docker containers in the default network will receive the VPN's DNS server in their `/etc/resolv.host` because it's not a localhost address
* **BUT** Because there is no route from the `docker0` bridge network to the VPN, all DNS lookups will now timeout inside containers in a default network
* Containers in a user network will work properly because DNS lookups are proxied through Docker and looked up on the host

My suggested solution to this would be

* A flag for the docker daemon that switches on the DNS proxy for default networks as well as user-defined ones

My comments on docker's libnetwork reflect this and hopefully someone will implement it (if I had time, I probably would have a stab at it, but my Golang is not strong and I'm busy... ).

**Comment by danger89** [comment] 2019-01-12 00:20
Example of using a `/etc/docker/daemon.json` file:
https://gitlab.melroy.org/snippets/19

**Comment by ImTheDeveloper** [comment] 2019-03-05 07:03
I believe I'm seeing the same issues here. Ubuntu 18.04 with a slow dns resolution first time round https://forums.docker.com/t/docker-dns-resolution-slow-for-http-calls-ipv6-bridge-network-issue/70390  I posted my findings here so far.

**Comment by daveneeley** [comment] 2019-07-20 17:42
Seeing this on all docker bridge networks on Centos 7 (7.6.1810), docker 18.09.8
- do not have dnsmasq
- do not have systemd-resolved
- configured /etc/docker/daemon.json with custom nameservers, validated they appear in /etc/resolv.conf within the container
- host has custom search domain in /etc/resolv.conf, which is passed along to containers

```
docker run --rm alpine cat /etc/resolv.conf
search mydomain
nameserver 1.1.1.1
nameserver 8.8.8.8

docker run --rm alpine ping google.com
ping: bad address 'google.com'

docker run --net=myexternal --rm alpine ping google.com
ping: bad address 'google.com'

docker run --net=host --rm alpine ping google.com
PING google.com (216.58.194.174): 56 data bytes
64 bytes from 216.58.194.174: seq=0 ttl=53 time=36.909 ms
```

**Comment by rulatir** [comment] 2021-05-10 13:41
This bug has delayed our project by a whopping 1.5 years. One release criteria that we have is that the tests must run all green on ALL development machines before we deploy. One development machine is a Ubuntu. Scenario tests that involve making requests to domains resolved by host dnsmasq fail. We have never solved it. We are completely stuck. The corona bug will probably be fixed sooner than this.

**Comment by rulatir** [comment] 2021-05-10 17:16
None of those work for me.

**Comment by awilkins** [comment] 2021-06-07 15:33
@rulatir

1. Disable `systemd-resolved`
1. Enable `dnsmasq`
1. Configure `dnsmasq` to listen to the Docker network bridge
1. Configure Docker to use the network bridge as it's DNS service in default network

---

1.
```sh
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
sudo rm /etc/resolv.conf
```
2.
Edit `/etc/NetworkManager/NetworkManager.conf` to add the `dns` setting to `[main]`

e.g.
```ini
[main]
plugins=ifupdown,keyfile
dns=dnsmasq
```

3.
Add this file @ `/etc/NetworkManager/dnsmasq.d/docker-bridge.conf`

```ini
listen-address=172.17.0.1
```
4.

Add this setting to `/etc/docker/daemon.json`
```json
{
	"dns": [
		"172.17.0.1"
	]
}
```
5.

Restart stuff.
```
sudo systemctl restart docker
sudo systemctl restart network-manager
```
6.

Check you didn't break DNS.

```sh
nslookup www.bbc.co.uk
```

7.

Check you fixed your problem

```
docker run -it tutum/dnsutils nslookup <my.special.domain>
```

**Comment by rulatir** [comment] 2021-06-09 11:34
I ended up doing something similar and it seems to work, but it does require that dnsmasq.service be `After=docker.service`, otherwise dnsmasq tries to listen on an interface that hasn't been created yet, and fails to start.

**Comment by awilkins** [comment] 2021-06-10 08:33
I don't have that problem here with the instance of `dnsmasq` that NetworkManager manages, rather than one managed by `systemd`, I don't know whether this is down to service start ordering, or whether NetworkManager will restart `dnsmasq` if it fails.

**Comment by rfay** [comment] 2021-09-04 15:28
A warning: If you change the `dns` setting to something other than the default, host.docker.internal does not resolve.

**Comment by Huweicai** [comment] 2022-11-02 08:49
If you are using custom installed dnsmasq, such as OS like CentOS/RHEL do not have dnsmasq built-in: 
1. edit `/etc/dnsmasq.conf`, append 172.17.0.1 to listen-address
```
listen-address=127.0.0.1,172.17.0.1
```
2. `systemctl restart dnsmasq.service`
3. edit `/etc/docker/daemon.json`, append dns config:
```
"dns": [
   "172.17.0.1"
]
```
4. `systemctl restart docker`
