### ISSUE TITLE
Upgrade of Docker broke awsebcli

### ISSUE THREAD

**Issue by bitbytedog** [docker/docker#31637] opened 2017-03-08 08:28 UTC
EB cli was broken by docker version Version 17.03.0-ce-mac2 (15654)

~~~~
+ eb local run
ERROR: ValueError :: Invalid leading zero in minor: u'17.03.0-ce'
~~~~~

It is the leading zero in the minor number

The line that blows up is in the semantic_version project, here -
https://github.com/rbarrois/python-semanticversion/blob/master/semantic_version/base.py#L211

~~~~
if _has_leading_zero(minor):
    raise ValueError("Invalid leading zero in minor: %r" % version_string)
~~~~

**Comment by thaJeztah** [comment] 2017-03-08 08:42
can you open an issue with AWS for this? it looks like their CLI is attempting to parse the docker version string and does not yet take the YY.MM version scheme into account.

I don't think there's anything actionable in this repository

**Comment by yongtang** [comment] 2017-03-08 16:53
This looks like a duplicate of #31633.

**Comment by thaJeztah** [comment] 2017-03-08 16:57
Yeah, the other one is a bit different, but both cannot be resolved in this repository, so let me go ahead and close this one at least

**Closed by thaJeztah** 2017-03-08 16:57 UTC

**Comment by bitbytedog** [comment] 2017-03-09 00:51
[Reported to AWS](https://forums.aws.amazon.com/thread.jspa?threadID=251051)

**Comment by shanestevens** [comment] 2017-03-27 23:36
Still broken :(

**Comment by hackjutsu** [comment] 2017-04-01 07:04
This becomes a blocker for us. Is there any way to install an older version on Ubuntu? For example, v1.13.1?

**Comment by philippeluickx** [comment] 2017-04-03 08:11
Fixed now - https://pypi.python.org/pypi/awsebcli

Changelog

3.10.1 (2017-03-30)
Fixed python 3.x bug for eb local run
Fixed eb local docker version check failure for leading zeros
Fixed eb init to not create an application when picking an existing app
Fixed eb local run to accept volumes defined that are not prefixed with /var/app/current/
