### ISSUE TITLE
docker run ubuntu:14.04 /bin/echo 'Hello world' fails on new Wndows boot2docker install

### ISSUE THREAD

**Issue by lwlsonjlg** [docker/docker#13741] opened 2015-06-04 13:55 UTC
initializing...
Virtual machine boot2docker-vm already exists

starting...
Waiting for VM and Docker daemon to start...
............ooo
Started.
Writing C:\Users\lwilson\.boot2docker\certs\boot2docker-vm\ca.pem
Writing C:\Users\lwilson\.boot2docker\certs\boot2docker-vm\cert.pem
Writing C:\Users\lwilson\.boot2docker\certs\boot2docker-vm\key.pem

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH='C:\Users\lwilson\.boot2docker\certs\boot2docker-vm'
    export DOCKER_TLS_VERIFY=1

IP address of docker VM:
192.168.59.103

setting environment variables ...
Writing C:\Users\lwilson\.boot2docker\certs\boot2docker-vm\ca.pem
Writing C:\Users\lwilson\.boot2docker\certs\boot2docker-vm\cert.pem
Writing C:\Users\lwilson\.boot2docker\certs\boot2docker-vm\key.pem
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH='C:\\Users\\lwilson\\.boot2docker\\certs\\boot2docker-vm'
    export DOCKER_TLS_VERIFY=1

You can now use `docker` directly, or `boot2docker ssh` to log into the VM.
Welcome to Git (version 1.9.5-preview20150319)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

lwilson@LENOVO-LAPTOP ~
$ docker run ubuntu:14.04 /bin/echo 'Hello world' 
FATA[0000] Error response from daemon: Cannot start container 5ecfa25102f612cad0208ecc0a0a18507279bce72ef313ff5a9bc7cf786c11b: [8] System error: exec: "C:/Program Files (x86)/Git/bin/echo": stat C:/Program Files (x86)/Git/bin/echo: no such file or directory

lwilson@LENOVO-LAPTOP ~

YES, the folder exists ...

lwilson@LENOVO-LAPTOP ~
$ "C:/Program Files (x86)/Git/bin/echo" hi
hi

**Comment by lwlsonjlg** [comment] 2015-06-04 13:57
lwilson@LENOVO-LAPTOP ~
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): windows/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

lwilson@LENOVO-LAPTOP ~
$ docker info
Containers: 9
Images: 4
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 2
Total Memory: 3.388 GiB
Name: boot2docker
ID: 6JWW:SOVO:Y4VV:YQG2:LPXL:APH7:K3P4:WW5Y:QYFW:ICPT:FBFS:JOLH
Debug mode (server): true
Debug mode (client): false
Fds: 12
Goroutines: 16
System Time: Thu Jun  4 13:56:54 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

lwilson@LENOVO-LAPTOP ~
$ uname -a
MINGW32_NT-6.1 LENOVO-LAPTOP 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown

**Comment by thaJeztah** [comment] 2015-06-07 15:15
> YES, the folder exists ...
> `lwilson@LENOVO-LAPTOP ~`
> `$ "C:/Program Files (x86)/Git/bin/echo" hi`
> `hi`

But that's a folder on you laptop, *not* inside the container; the container is running ubuntu, and there's no `C:\Program Files (x86)\` on ubuntu.

However, I think this is a duplicate of https://github.com/docker/docker/issues/12590, especially look at https://github.com/docker/docker/issues/12590#issuecomment-95370211. 

To quote;

> If you're using git bash on windows, msysgit converts paths like /c/users to c:\users (not something you want because the path inside the boot2docker VM is /c/Users)

> Try surrounding -v value with single quotes like:

> `... -v '/c/Users:/path' ...`
> On `cmd.exe/powershell` you shouldn't be having this problem.

I'm going to close this issue, because I think this is a duplicate, but let me hear if that solved your issue!

Also, feel free to comment if you think I closed this by mistake

**Comment by saras-vijay** [comment] 2015-06-09 07:33
This issue is not solved even after following the comment

**Comment by thaJeztah** [comment] 2015-06-09 08:04
Have you tried running the same in `cmd.exe` or `powershell` (trying to narrow down things).

Given the `stat C:/Program Files (x86)/Git/bin/echo: no such file or directory` error, this really looks like the shell is converting `bin/echo` to an absolute path nefore sending it to docker.

**Comment by lwlsonjlg** [comment] 2015-06-09 11:13
What I did to solve the issue was to open a putty terminal on the Ubuntu vm; then run the command ...

The tutorial is simply not specific ...
It makes it seem like the window started by boot2docker is the one to use when it isn't ...

**Comment by thilgen** [comment] 2015-06-12 14:44
Appears as though a leading double-slash for the Linux path (when referenced in Windows boot2docker client) works.

https://github.com/docker/docker/issues/12590#issuecomment-96767796

**Comment by lwlsonjlg** [comment] 2015-06-12 14:59
Yes ... that works ... why?

lwilson@LENOVO-LAPTOP ~
$ docker run ubuntu:14.04 //bin/echo 'Hello world'
Hello world

lwilson@LENOVO-LAPTOP ~
$

**Comment by thilgen** [comment] 2015-06-12 15:12
Seems to be particular to the way the Windows boot2docker terminal interprets command line parameters - which is why it also works well without modification (from the example) for cmd.exe and powershell (which have different command line stacks). Command line parsing is tough :D.

**Comment by greysAcademicCode** [comment] 2015-06-17 11:56
I ran into this today. Adding an extra `/` before my command fixed it for me. This feels to me like a pretty important issue. I generally use Docker in Linux and coming to an understanding of this "caveat" while trying to get my stuff working in Windows wasted a fair bit of my time today. 

If this is going to stay this way, it should probably be documented somewhere (my apologies if that's already done and I missed it).

**Comment by iainsproat** [comment] 2015-07-11 15:30
Just confirming that I experienced this exact same issue.

The workaround to include the additional `/` before the command also worked for me.

`docker run ubuntu:14.04 //bin/echo 'Hello world'`

My version information for reference:

```
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): windows/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

**Comment by skain** [comment] 2015-07-13 20:50
Double-slash worked for me as well. Someone should really change the tutorial...

**Comment by andy4545** [comment] 2015-07-14 16:59
Double slash also worked for me - spent 5 hours trying to work it out . Thanks @iainsproat .

**Comment by ningliu** [comment] 2015-07-17 00:37
Double slash also worked for me.  I am glad I found this post after only 10 minutes trying.  Thanks!

**Comment by gmanfunky** [comment] 2015-08-08 03:16
This is due to [msys-git](https://github.com/msysgit/msysgit) trying to be smart and fixing up windows path and linux paths with all sorts of voodoo before passing them as process parameters. 

Using a double forward-slash bypasses much of this voodoo.

It is a pretty aggravating problem to me too. I have to fixup various things to attempt docker development on windows. 

For example, in bash on windows
```
$ docker run --privileged --rm -ti -v `pwd`:/go/src/github.com/docker/docker dry-run-test /bin/bash
```
Will fail. 

```
$ docker run --privileged --rm -ti -v /`pwd`:/go/src/github.com/docker/docker dry-run-test //bin/bash
```
Will work. 



I think I'll make an issue for it. Some stuff has changed in this msys voodoo in the last year. I'm wondering if it messed us up, or if we just need to work around it.

**Comment by gmanfunky** [comment] 2015-08-08 03:33
The rules: http://www.mingw.org/wiki/Posix_path_conversion

**Comment by bastula** [comment] 2015-08-31 16:32
I just ran into this today as well. The double slash fixed it.
The docs (https://docs.docker.com/userguide/dockerizing/) should have an alternate command for Windows, especially if msys-git is being bundled with the Docker Toolbox.

**Comment by justincormack** [comment] 2016-04-28 16:35
Does having `MSYS_NO_PATHCONV=1` set in your environment help here?

**Comment by icecrime** [comment] 2016-09-10 02:17
I'm closing this as it's most likely not a Docker issue. Please let me know if I should reopen!

**Closed by icecrime** 2016-09-10 02:17 UTC
Labels: platform/windows
