### ISSUE TITLE
1.12.1 Crash

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#26619] opened 2016-09-16 06:13 UTC
No clue what I was doing, but it crashed.
```
docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

```
unexpected fault address 0x0
fatal error: fault
[signal 0xb code=0x80 addr=0x0 pc=0x76e4d9]

goroutine 10821 [running]:
runtime.throw(0x1dfe8b0, 0x5)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820ef1918 sp=0xc820ef1900
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc820ef1968 sp=0xc820ef1918
encoding/json.unquoteBytes(0xc8222ecef7, 0x20, 0x2984, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:1080 +0x119 fp=0xc820ef1a40 sp=0xc820ef1968
encoding/json.(*decodeState).literalStore(0xc82219bef0, 0xc8222ecef6, 0x20, 0x2985, 0x178bf00, 0xc82181af40, 0x198, 0x174da00)
	/usr/local/go/src/encoding/json/decode.go:809 +0xb4f fp=0xc820ef1f18 sp=0xc820ef1a40
encoding/json.(*decodeState).literal(0xc82219bef0, 0x178bf00, 0xc82181af40, 0x198)
	/usr/local/go/src/encoding/json/decode.go:717 +0xe9 fp=0xc820ef1f80 sp=0xc820ef1f18
encoding/json.(*decodeState).value(0xc82219bef0, 0x178bf00, 0xc82181af40, 0x198)
	/usr/local/go/src/encoding/json/decode.go:370 +0x37b fp=0xc820ef2058 sp=0xc820ef1f80
encoding/json.(*decodeState).array(0xc82219bef0, 0x174dac0, 0xc8210700a0, 0x197)
	/usr/local/go/src/encoding/json/decode.go:518 +0xa6b fp=0xc820ef2260 sp=0xc820ef2058
encoding/json.(*decodeState).value(0xc82219bef0, 0x174dac0, 0xc8210700a0, 0x197)
	/usr/local/go/src/encoding/json/decode.go:364 +0x3c1 fp=0xc820ef2338 sp=0xc820ef2260
encoding/json.(*decodeState).object(0xc82219bef0, 0x1d917c0, 0xc821070058, 0x199)
	/usr/local/go/src/encoding/json/decode.go:684 +0x116a fp=0xc820ef26e0 sp=0xc820ef2338
encoding/json.(*decodeState).value(0xc82219bef0, 0x1d917c0, 0xc821070058, 0x199)
	/usr/local/go/src/encoding/json/decode.go:367 +0x3a1 fp=0xc820ef27b8 sp=0xc820ef26e0
encoding/json.(*decodeState).object(0xc82219bef0, 0x1cc05e0, 0xc821070000, 0x199)
	/usr/local/go/src/encoding/json/decode.go:684 +0x116a fp=0xc820ef2b60 sp=0xc820ef27b8
encoding/json.(*decodeState).value(0xc82219bef0, 0x1c364a0, 0xc821070000, 0x16)
	/usr/local/go/src/encoding/json/decode.go:367 +0x3a1 fp=0xc820ef2c38 sp=0xc820ef2b60
encoding/json.(*decodeState).unmarshal(0xc82219bef0, 0x1c364a0, 0xc821070000, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:168 +0x196 fp=0xc820ef2d10 sp=0xc820ef2c38
encoding/json.Unmarshal(0xc8222ec000, 0x367b, 0x387b, 0x1c364a0, 0xc821070000, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:96 +0x12b fp=0xc820ef2d80 sp=0xc820ef2d10
github.com/docker/docker/image.NewFromJSON(0xc8222ec000, 0x367b, 0x387b, 0xc8222ec000, 0x0, 0x0)
	/go/src/github.com/docker/docker/image/image.go:130 +0xb4 fp=0xc820ef2e10 sp=0xc820ef2d80
github.com/docker/docker/image.(*store).Get(0xc82030dbc0, 0xc8200d7720, 0x47, 0xc820ef2ee0, 0x0, 0x0)
	/go/src/github.com/docker/docker/image/store.go:189 +0xee fp=0xc820ef2ea8 sp=0xc820ef2e10
github.com/docker/docker/image.(*store).imagesMap(0xc82030dbc0, 0x5c1901, 0x0)
	/go/src/github.com/docker/docker/image/store.go:287 +0x1ec fp=0xc820ef2fc8 sp=0xc820ef2ea8
github.com/docker/docker/image.(*store).Map(0xc82030dbc0, 0x0)
	/go/src/github.com/docker/docker/image/store.go:274 +0x26 fp=0xc820ef2fe8 sp=0xc820ef2fc8
github.com/docker/docker/daemon.(*Daemon).SystemInfo(0xc8203c31e0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/info.go:88 +0x79d fp=0xc820ef3320 sp=0xc820ef2fe8
github.com/docker/docker/api/server/router/system.(*systemRouter).getInfo(0xc8207b3410, 0x7efeed1e1ba0, 0xc821832270, 0x7efeed1f2a00, 0xc821fc1520, 0xc821118d20, 0xc8218321e0, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/router/system/system_routes.go:32 +0x67 fp=0xc820ef35b8 sp=0xc820ef3320
github.com/docker/docker/api/server/router/system.(*systemRouter).(github.com/docker/docker/api/server/router/system.getInfo)-fm(0x7efeed1e1ba0, 0xc821832270, 0x7efeed1f2a00, 0xc821fc1520, 0xc821118d20, 0xc8218321e0, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/router/system/system.go:27 +0x74 fp=0xc820ef3608 sp=0xc820ef35b8
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7efeed1e1ba0, 0xc821832270, 0x7efeed1f2a00, 0xc821fc1520, 0xc821118d20, 0xc8218321e0, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa fp=0xc820ef3780 sp=0xc820ef3608
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7efeed1e1ba0, 0xc821832240, 0x7efeed1f2a00, 0xc821fc1520, 0xc821118d20, 0xc8218321e0, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e fp=0xc820ef3900 sp=0xc820ef3780
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7efeed1f2a00, 0xc821fc1520, 0xc821118d20)
	/go/src/github.com/docker/docker/api/server/server.go:139 +0x138 fp=0xc820ef39f8 sp=0xc820ef3900
net/http.HandlerFunc.ServeHTTP(0xc82027fe40, 0x7efeed1f2a00, 0xc821fc1520, 0xc821118d20)
	/usr/local/go/src/net/http/server.go:1618 +0x3a fp=0xc820ef3a18 sp=0xc820ef39f8
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820158690, 0x7efeed1f2a00, 0xc821fc1520, 0xc821118d20)
	/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e fp=0xc820ef3b30 sp=0xc820ef3a18
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820a4b490, 0x7efeed1f2a00, 0xc821fc1520, 0xc821118d20)
	/go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72 fp=0xc820ef3b60 sp=0xc820ef3b30
net/http.serverHandler.ServeHTTP(0xc8203d6b80, 0x7efeed1f2a00, 0xc821fc1520, 0xc821118d20)
	/usr/local/go/src/net/http/server.go:2081 +0x19e fp=0xc820ef3bc0 sp=0xc820ef3b60
net/http.(*conn).serve(0xc821be7080)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e fp=0xc820ef3f88 sp=0xc820ef3bc0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820ef3f90 sp=0xc820ef3f88
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 1 [chan receive, 92 minutes]:
main.(*DaemonCli).start(0xc8203cbd40, 0x0, 0x0)
	/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:308 +0x2274
main.main()
	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:68 +0x491

goroutine 17 [syscall, 92 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
```

**Comment by homerakshay** [comment] 2016-09-16 06:56
@ibuildthecloud Hey Darren, could you put more light on what went wrong.. 

Also i would suggest u restart your docker service on the ec2's where they are running.. Let me know if it helps. 

Regards,
Akshay

**Comment by thaJeztah** [comment] 2016-09-16 09:24
@tonistiigi @mlaventure any idea?

**Comment by ibuildthecloud** [comment] 2016-09-16 13:04
There's not too much information to share, the stack should really be enough.  I wasn't really do anything at the time, but I was running Rancher.  Rancher will periodically call `docker info` and you can see from that stack that that is what crashed the system.  On a side note, `docker info` is crazy slow if you have a lot of images.  As such we stopped really ever calling `docker info` in our latest dev builds of Rancher.

This issue has been seen in the past and was a case in which two goroutines were accessing the same object that was in a partially unmarshaled state.

**Comment by thaJeztah** [comment] 2016-09-16 13:36
> On a side note, docker info is crazy slow if you have a lot of images. As such we stopped really ever calling docker info in our latest dev builds of Rancher.

I think over time, too many things have been added to `docker info` - I've mentioned adding more fine-grained (API) access at some point; @ibuildthecloud can you open an issue, and describe your use-case a bit more in-depth (e.g. what information does Rancher need), perhaps you have thoughts on making the `/info` endpoint more flexible as well?

`</sidenote>`

**Comment by tonistiigi** [comment] 2016-09-16 17:24
dupe of #23158

**Closed by tonistiigi** 2016-09-16 17:24 UTC
Labels: area/daemon, kind/bug, version/1.12
