### ISSUE TITLE
BUG: Cannot start container device or resource busy

### ISSUE THREAD

**Issue by intval** [docker/docker#14540] opened 2015-07-10 22:37 UTC
`dodocker run -ti oraclelinux:latest`

```
Error response from daemon: Cannot start container b49a23366eb18fdc3f7206431090f894341473bbb3740f5687f2ca37d07e28a0: dev
ice or resource busy
```

```
DEBU[0142] Calling POST /containers/create
INFO[0142] POST /v1.19/containers/create
DEBU[0142] Calling POST /containers/{name:.*}/attach
INFO[0142] POST /v1.19/containers/b49a23366eb18fdc3f7206431090f894341473bbb3740f5687f2ca37d07e28a0/attach?stderr=1&stdin
=1&stdout=1&stream=1
DEBU[0142] attach: stdin: begin
DEBU[0142] attach: stdout: begin
DEBU[0142] attach: stderr: begin
DEBU[0142] Calling POST /containers/{name:.*}/start
INFO[0142] POST /v1.19/containers/b49a23366eb18fdc3f7206431090f894341473bbb3740f5687f2ca37d07e28a0/start
ERRO[0142] Handler for POST /containers/{name:.*}/start returned error: Cannot start container b49a23366eb18fdc3f7206431
090f894341473bbb3740f5687f2ca37d07e28a0: device or resource busy
ERRO[0142] HTTP Error                                    err=Cannot start container b49a23366eb18fdc3f7206431090f8943414
73bbb3740f5687f2ca37d07e28a0: device or resource busy statusCode=500
DEBU[0142] Closing buffered stdin pipe
DEBU[0142] attach: stdin: end
DEBU[0142] attach: stdout: end
DEBU[0142] attach: stderr: end
```

```
➜  vagrant  docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
➜  vagrant  uname -a
Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

➜   docker info
Containers: 15
Images: 12
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.2.0-23-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 2
Total Memory: 3.862 GiB
Name: precise64
ID: BNXR:HCOL:KJUN:OIXR:5OG3:KOA3:PFC4:P4TK:OJ2D:6CGF:VGJP:ATXM
Debug mode (server): true
File Descriptors: 10
Goroutines: 14
System Time: 2015-07-10T22:39:55.088570732Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
```

Docker host is ubuntu12.04_x64 inside virtual box on win8_x64.

**Comment by thaJeztah** [comment] 2015-07-10 23:27
You're trying to run docker on an unsupported kernel; see the prerequisites for ubuntu 12.04 here; https://docs.docker.com/installation/ubuntulinux/

If possible, I would advise you to upgrade the VM to a more recent ubuntu version (e.g. 14.04 LTS)

I'm going to close this issue, because you're running docker on an unsupported configuration, but ping me if you're still able to reproduce after updating your system

**Closed by thaJeztah** 2015-07-10 23:27 UTC

**Comment by intval** [comment] 2015-07-11 09:27
Thanks. Indeed upgrading to 14.04 solved the issue.

**Comment by thaJeztah** [comment] 2015-07-11 09:31
@intval great! Thanks for reporting back!
