### ISSUE TITLE
loop device mounted on container contents are not visible from the host on a shared volume

### ISSUE THREAD

**Issue by dbremmen** [docker/docker#15548] opened 2015-08-13 04:51 UTC
I'm trying to create a loop device in the container inside a shared volume with the host and create a loop device inside. But the loop device contents are not visible from the host. 
Maybe is there a better way to achieve this or a workaround.

These are the steps that I followed. 

a) start a docker container with a volume shared between the container and the host
sudo docker run -it -v /home/test:/home/test ubuntu:latest bash

b) On the container, created a loop device in the shared path
cd /home/test
dd if=/dev/zero of=./file.ext4 bs=1K count=1024
mkfs.ext2 -F file.ext4
mkdir myLoopPath
sudo mount -v ./file.ext4 ./myLoopPath/

c) Create a file in ./myLoopPath in the container
cd ./myLoopPath
echo "test" > ./file.txt

d) In the container /home/test/myLoopPath has the file.txt but in the host /home/test/myLoopPath is empty

**Comment by phemmer** [comment] 2015-08-13 11:23
This is currently the expected behavior, and is not supported.

There are 2 open feature requests which would add support for this, #10088 and #14630
There is an open PR at #14097

**Comment by thaJeztah** [comment] 2015-08-13 23:21
thanks for reporting, @dbremmen, I'm going to close this issue, because this is covered by the issues @phemmer mentioned. Please continue the discussion on those issues thanks!

**Closed by thaJeztah** 2015-08-13 23:21 UTC
