### ISSUE TITLE
[Swarm] Manager and Workers in the same node

### ISSUE THREAD

**Issue by Pierpaolo1992** [docker/docker#29817] opened 2017-01-02 08:50 UTC
Hi everyone, my goal is to setup a CDN using nginx container as proxy cache, so i looked for docker swarm for containers clustering.

For testing, i'd like using one only node, within 1 manager and some workers with nginx container replicas. 

But, when i init swarm (`docker swarm init`) and created manager, then, when i try to create a worker on the same node, there is this problem:

```
Error response from daemon: This node is already part of a swarm cluster. Use "docker swarm l
eave" to leave this cluster and join another one
```

So, for using docker swarm, i need at least two nodes? (1 with manager inside and one with workers) or there is a way to using only one node?

**Comment by thaJeztah** [comment] 2017-01-02 09:09
In a Swarm, each "node" is a "machine", this can be either a physical machine, or a "virtual machine".
You can run Swarm mode with a single node (single master), but if you want to try running with multiple nodes, you either need to have multiple machines, or start multiple virtual machines. For "testing" you could run `docker in docker` to mimic multiple nodes (see https://github.com/docker/swarm/issues/2327#issuecomment-267815173), but that's really experimental and only for "playing around".

You can learn about Swarm key concepts here;

- https://docs.docker.com/engine/swarm/ 
- https://docs.docker.com/engine/swarm/swarm-tutorial/

Please keep in mind that the GitHub issue tracker is for reporting bugs and feature requests, and not intended as a general support forum. For other types of questions, consider using;

- https://forums.docker.com
- the docker community slack channel; https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/

I'll close this issue because this is not a bug report of a feature request, but feel free to ask for more info after I closed

**Closed by thaJeztah** 2017-01-02 09:09 UTC
Labels: area/swarm

**Comment by clement-igonet** [comment] 2017-12-02 19:54
And so, does a manager is also a worker?

**Comment by thaJeztah** [comment] 2017-12-02 22:43
A manager is also a worker, unless its availability is set to "drain".

But please take time to read the docs, and understand the whole concept.

**Comment by clement-igonet** [comment] 2017-12-03 05:37
Thanks.
It's just this basical info is not clear. I had to deep into details to get it.😀
-- 
Sent from my mobile. It explains my brevity.
