### ISSUE TITLE
docker run hello-world

### ISSUE THREAD

**Issue by mjaifar** [docker/docker#17871] opened 2015-11-10 16:05 UTC
An error occurred trying to connect: Post http://localhost:2375/v1.21/containers/create: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.

**Comment by yoanisgil** [comment] 2015-11-10 17:47
@mjaifar looks like the docker daemon is not running. See if you can:

    telnet localhost 2375

Also, please try to provide a minimum description to your problem so others can help. Pasting the raw error is not much of a help  ;)

**Comment by thaJeztah** [comment] 2015-11-10 20:45
I'm closing this for now, but happy to reopen if we received more information.

If you need assistance running docker, also feel free to ask for help in the #docker IRC channel

**Closed by thaJeztah** 2015-11-10 20:45 UTC

**Comment by shiulid** [comment] 2015-11-17 00:51
Hello, I am getting same error.

More information:
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://localhost:2375/v1.21/version: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.

$ docker info
An error occurred trying to connect: Get http://localhost:2375/v1.21/info: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.

$ uname -a
MINGW64_NT-10.0 A 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys

**Comment by thaJeztah** [comment] 2015-11-17 11:24
@shiulid it looks like you've configured your client to connect to "localhost", but seeing that you're using Windows, this probably not right, because the daemon is not running on localhost, but inside a virtual machine.

You should probably use `docker-machine env` to set the environment variable for the machine you're trying to connect to.

**Comment by mjaifar** [comment] 2015-11-17 12:02
Thanks a lot.

On Tue, Nov 17, 2015 at 12:26 PM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> @shiulid <https://github.com/shiulid> it looks like you've configured
> your client to connect to "localhost", but seeing that you're using
> Windows, this probably not right, because the daemon is not running on
> localhost, but inside a virtual machine.
>
> You should probably use docker-machine env to set the environment
> variable for the machine you're trying to connect to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/17871#issuecomment-157342235>.
>



-- 
JAIFAR Mohammed Reda.
Software Development Engineer.
https://fr.linkedin.com/in/mjaifar
+33 06 95 78 04 12 <http://jaifar.tk>

**Comment by zettabox-bohdan** [comment] 2015-12-15 13:10
Hi, also make sure you have telnet client installed on your Windows machine. I was getting same message and installing telnet client seems to resolve the issue. docker info is now working as it should.

Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015

**Comment by kkarakk** [comment] 2016-02-13 10:42
This error also seems to happen if the machine does not exist (again, on windows).  
This [link]( https://docs.docker.com/machine/get-started/) has the tutorial for creating a machine

**Comment by kkarakk** [comment] 2016-02-13 10:52
Another reason for this bug is if you're running Docker commands in the default cmd shell instead of the docker bash shell. the commands work but not completely. Weird gotcha

**Comment by anvikakumar93** [comment] 2016-03-14 01:49
Hi,
My computer was statically configured before which docker was functioning smoothly, after which i am getting the following error:
 An error occurred trying to connect: Post http://localhost:2375/v1.21/containers/create: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.
All the work which I had done has also vanished. Please help me rectify this error.

**Comment by HunterHan** [comment] 2016-03-15 02:42
Hi all,
I can solve this problem after executing the following command "docker-machine ssh default". Then rerun "docker run hello-world", it will display successfully. But i don't know why it works cause I am beginner on docker. If anyone knows root cause, please let me know. Thanks in advance.

**Comment by crowne** [comment] 2016-03-22 08:24
I get this same issue just after starting up.
When I work at a client site I need to go through a corporate proxy, to do this I am using the docker image btrepp/cntlm
The first few times trying to start the image fails, then after waiting a while and closing the initial Docker Quickstart Command Line window and opening a new one, I am able to start the container.

---
## Stats from the original window:
**$ docker version**
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/version: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

**$ docker info**
An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/info: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

**$ uname -a**
MINGW64_NT-6.3 crowne-zbook 2.4.0(0.292/5/3) 2016-01-05 14:13 x86_64 Msys

---
## Stats from a new window:
**$ docker version**
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

**$ docker info**
Containers: 14
 Running: 1
 Paused: 0
 Stopped: 13
Images: 31
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 105
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: BEJY:R7BX:RG27:GLKD:OBRB:IOT6:CYRH:T3YZ:PJGF:25L7:KYSS:NDVC
Debug mode (server): true
 File Descriptors: 19
 Goroutines: 35
 System Time: 2016-03-22T08:20:07.541257931Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**$ uname -a**
MINGW64_NT-6.3 crowne-zbook 2.4.0(0.292/5/3) 2016-01-05 14:13 x86_64 Msys

**Comment by rodrigogs** [comment] 2016-04-05 11:08
Same issue here. Already tryied lastest version.

I think I'm going to abandon Docker for Windows, as it never works since it's installation... And nobody seems to care.

**Comment by thaJeztah** [comment] 2016-04-05 15:35
@rodrigogs how do you get to the conclusion that "nobody cares?". The issue on this page is actually multiple independent issues (misconfiguration, VirtualBox loosing network connection, a corporate proxy server), so reopening this issue doesn't help (there's no *single* solution)

Also note that issues related to docker machine / docker toolbox should be reported in the https://github.com/docker/machine and https://github.com/docker/toolbox repositories.

You may be interested in https://blog.docker.com/2016/03/docker-for-mac-windows-beta/, which resolves many issues that people encountered when using Docker Toolbox

**Comment by rodrigogs** [comment] 2016-04-05 15:42
I didn't know about Docker beta, thanks for the information. I'm gonna try it.

**Comment by srihari-sridharan** [comment] 2016-04-08 06:43
@HunterHan your suggestion worked. Thanks. Got connected to the default machine and then executed the command.

**Comment by poldixd** [comment] 2016-04-08 11:43
Did you used the **Docker Quickstart Terminal**? When i installed the docker toolbox and tried to start a container i got the same error. Than i started **Docker Quickstart Terminal** on windows and all was fine.

**Comment by jorgejeferson** [comment] 2016-04-11 19:46
I had the same problem.
I managed to solve the following:

1. Remove default `$ docker-machine rm default`
2. rerun the `start.sh`

**Comment by wrender** [comment] 2016-04-16 23:52
I had the same error when starting docker in Windows 10.  To get it working:  

1. Right clicking on the "Docker Quickstart Terminal" then "Run as administrator". 

2. Close the terminal window, and open the program as a regular user.

After that it seems to run fine.

**Comment by Aziris** [comment] 2018-01-25 14:22
Hi,
I have another case of same problem, in my case the culprit was installation in non-standard location.
I installed both the Git and Docker Toolkit on drive E.
When I checked the Quickstart Terminal shortcut details, Target line was referring to wrong GIT installation location. 
This is how it looks if you install everything in default locations : 
"C:\Program Files\Git\bin\bash.exe" --login -i "C:\Program Files\Docker Toolbox\start.sh"

Check that the right locations are reflected here.
