### ISSUE TITLE
Provide a --restart=always for the "docker start" command

### ISSUE THREAD

**Issue by arthurlogilab** [docker/docker#13743] opened 2015-06-04 14:44 UTC
For an already running instance (with it's port mapping configuration and data stored inside of it) I can't go back to doing a "docker run --restart=always", so it would be nice to have a way of setting the RestartPolicy on start also, not only on run.

**Comment by arthurlogilab** [comment] 2015-06-04 14:53
This is a UI feature request, I'm not sure you need the details of my docker installations, but here goes anyway. 

```
# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
root@hostname:~# docker info
Containers: 19
Images: 229
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 267
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 871.7 MiB
Name: hostname
ID: ISNM:MEC6:GGHE:FEZ2:5P6W:J5VG:CBGI:KXYS:7LLI:F4KV:N5DN:EHOB
WARNING: No memory limit support
WARNING: No swap limit support
root@hostname:~# uname -a
Linux hostname 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment] 2015-06-04 17:17
Hi,

I don't really see the advantage of this since the container is already stopped, you can just create a new one with the desired restart policy.

**Comment by arthurlogilab** [comment] 2015-06-05 07:36
@cpuguy83 maybe I'm missing some knowledge about docker commands. Can I restart a stopped container using run ? From my understanding docker run works on images. I would have to do a docker commit then run that image ? In that case would I not loose the port forwarding settings ?

**Comment by thaJeztah** [comment] 2015-06-07 13:05
Ideally, containers should be stateless and not be used to persist data (use volumes to persist data). Containers can then be thought of as being "disposable", which has many advantages, such as being able to update a container, simply by replacing it with a new container.

For example;

```bash
docker stop my-container
docker rename my-container my-old-container
docker run --volumes-from=my-old-container --restart always myimage
docker rm my-old-container
```

This will move the old container out of the way by renaming it, start a new container (but attach the existing volumes of the old container), and remove the old container now that it's no longer needed.

If your container **does** contain data / modifications, then (as you mentioned), you'll need to commit the container to an image first, and start the new container from that image.


Having said the above, I personally *do* see some value in being able to change the restart policy of a container, because it's a better/easier UX than taking the steps above. Removing a restart policy (`restart:none`) can be useful, to prevent a manually stopped container being automatically started again upon daemon restart.

**Comment by duglin** [comment] 2015-06-07 16:07
This touches on a more generic topic that I’d like to see discussed during the next maintainers meeting.  There are times when design decisions are made based on how people think containers should be used.  For example: treat containers like cows not pets.  And: containers are meant to be transient.  In a conceptual sense I agree, these are all part of good cloud design.  However, I think its important to distinguish “recommendations” from “mandates”.  While its good to recommend that you keep data in a volume (or DB) and not in the container, there are time when that may not be practical for some people. It may be cleaner to just kill and recreate a container, but again, that may not be practical for all cases.

So, the topic I’d like to discuss is whether our recommended good cloud practices should preclude these other cases?  I’m not suggesting that we add hacks to support them but there have been cases where it feels like we didn’t need to do a lot more than enable it via a new API/CLI-command but we resisted due to our preferred approach to how Docker should be used, and I tend to think that when we do that we hurt our users more than help them because I want people to push the boundaries of how/when to use Docker into new/exciting usecases.

**Comment by thaJeztah** [comment] 2015-06-07 16:42
@duglin agreed; I think the difference is "in what kind of situation" is Docker used?  Although showing/advocating best-practices is important, there's a big difference between a company using docker on a multi-node swarm cluster, and a developer using Kitematic / B2D, bind-mounting a local directory to work on a WordPress site (just for illustration).

IMO, both are valid use-cases for Docker, but both have different requirements (not just *scale*). So being able to serve both (without, as you mentioned, bad hacks), will be a good thing. :+1:

**Comment by arthurlogilab** [comment] 2015-06-09 08:00
@thaJeztah thanks for you comments. Indeed ``--volumes-from`` looks pretty useful for the "recommended" process. In that case, I would argue that adding something like ``--publish-rules-from`` would be needed or a more general ``--configuration-from`` that includes "everything". 

Maybe another tooling that is needed for this is some documentation or tool that provides a way to "extract" the data from a running docker to make it runnable with volumes. So that one can iterate over the process of "data inside the docker", "data outside the docker with clean restart of images". 

@duglin glad to see that this question could be discussed in a maintainer meeting. I understand that it is not a easy UX decision.

**Comment by thaJeztah** [comment] 2015-06-09 08:19
> Maybe another tooling that is needed for this is some documentation or tool

Docker Compose (https://github.com/docker/compose) sounds like a good option there; Compose allows you to define the settings to use for your containers and "re-create" those containers after changing the settings. Be aware though, that Compose will *not* try to preserve modifications you made inside a container

(just to add a suggestion for your current workflow)

**Comment by anthonygreen** [comment] 2015-08-04 08:22
run isn't idempotent, so when my Ansible playbook succeeds in creating the container by fails to start it I have to delete the container before I can rerun the playbook. Separating out the tasks to create and start works but now I can't use --restart=always. Adding --restart=alway to create or start would give flexibility, flexibility allows patterns/anti-patterns to emerge and it's the emergence use you should react to.

**Comment by praveennous** [comment] 2015-08-11 10:08
Hello All,

Could some one give me steps how to set existing container to restart=always to autostart.Please find my image id and guide me on this.

Image ID :e0418b2f81b4

**Comment by thaJeztah** [comment] 2015-08-11 15:45
@praveennous the GitHub issue tracker is not a general support forum; please ask your question in a [more suitable location](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#talking-to-other-docker-users-and-contributors), for example:

- the `#docker` IRC channel on freenode
- the [docker-user](https://groups.google.com/forum/#!forum/docker-user) google group
- [forums.docker.com](https://forums.docker.com/)

**Comment by praveennous** [comment] 2015-08-11 16:52
Hi Sebastiaan,

Thanks for update. when I googled I found this page. thought it will give
me solution for my query as I saw the discussion about same as my issue.

On Tue, Aug 11, 2015 at 4:46 PM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> @praveennous <https://github.com/praveennous> the GitHub issue tracker is
> not a general support forum; please ask your question in a more suitable
> location
> <https://github.com/docker/docker/blob/master/CONTRIBUTING.md#talking-to-other-docker-users-and-contributors>,
> for example:
>
>    - the #docker IRC channel on freenode
>    - the docker-user <https://groups.google.com/forum/#!forum/docker-user>
>    google group
>    - forums.docker.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/13743#issuecomment-129937324>.
>



-- 
Thanks,
Praveen Kumar.A
+91-8971969716

**Comment by sxiii** [comment] 2016-05-12 12:21
I would be happy if this feature will be implemented, too.

**Comment by thaJeztah** [comment] 2016-05-12 12:28
We now have `docker update`, which allows changing the restart policy of a running container, so this is actually resolved, albeit in a slightly different way. See https://docs.docker.com/engine/reference/commandline/update/#update-a-container-s-restart-policy

Basically:

    docker run -d --name web nginx:alpine

Then update the restart-policy;

    docker update --restart=always web


I'm closing this issue, because I think this is resolved, but feel free to continue the discussion

**Closed by thaJeztah** 2016-05-12 12:28 UTC
Labels: kind/feature

**Comment by elduddz** [comment] 2018-01-08 15:36
mine was fixed by reordering the variables and ask for the image last.

docker run -d -p 80:80 --restart always --name web **[insert image:tag here]**

**Comment by andrewb-ms** [comment] 2018-01-18 18:06
I disagree this is "solved".  The "run" and "start" commands do not provide the same parameter --restart, which is highly inconsistent.  That is the bug here.

**Comment by thaJeztah** [comment] 2018-01-18 18:52
It's not a bug. `docker run` is a combination of `docker create` and `docker start`; the restart policy is a property of the container that is created, thus part of `docker create`. `docker start` is designed to not modify the container, only move it to the `running` state.

**Comment by Rajamallareddys** [comment] 2018-02-10 07:49
@thaJeztah I have followed this way but once i stop container it doesn't start automically

here is how I have run and updated the container
docker run -d -p 4200:4200 --name web client:latest
docker update --restart=always web
