### ISSUE TITLE
Docker daemon panic when external registry auth service returns 401

### ISSUE THREAD

**Issue by Soulou** [docker/docker#21027] opened 2016-03-08 11:25 UTC
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 66
 Running: 0
 Paused: 0
 Stopped: 66
Images: 63
Server Version: 1.10.2
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-36-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: <edited>
ID: C7NK:RNIQ:BYLM:I52O:EZAK:O7JP:XFZ2:7EPS:SZ4S:3GVO:E6YK:DZWO
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

**VirtualBox VM**

List the steps to reproduce the issue:
1. Setup distribution/docker version 2.3 with token authentication
2. Start a push/pull
3. When the docker daemon tries to get the authentication token, if the service returns the following response:

HTTP 401
ContentType: application/json

```json
{"error": "unauthorized"}
```

Describe the results you received:

**Docker daemon crashes**

Describe the results you expected:

It should log an error saying what is wrong with th response

Provide additional info you think is important:

Panic stack:

```
panic: runtime error: index out of range

goroutine 176 [running]:
github.com/docker/docker/distribution.retryOnError(0x7f44f1ad06b8, 0xc820d65b40, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/registry.go:143 +0x138
github.com/docker/docker/distribution.retryOnError(0x7f44f1ad06e0, 0xc820d41bc0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/registry.go:150 +0x530
github.com/docker/docker/distribution.(*v2PushDescriptor).Upload(0xc820904f00, 0x7f44f1266420, 0xc820905280, 0x7f44f1266460, 0xc820a381e0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/push_v2.go:335 +0x12fb
github.com/docker/docker/distribution/xfer.(*LayerUploadManager).makeUploadFunc.func1.1(0xc820a381e0, 0xc820a38060, 0x7f44f1266810, 0xc820904f00, 0xc820a9f7a0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/xfer/upload.go:108 +0x1a6
created by github.com/docker/docker/distribution/xfer.(*LayerUploadManager).makeUploadFunc.func1
        /usr/src/docker/.gopath/src/github.com/docker/docker/distribution/xfer/upload.go:150 +0x13e
```

**Comment by thaJeztah** [comment] 2016-03-08 12:44
Looking for related issues, I found https://github.com/docker/docker/issues/18569, which isn't panicking, but I spotted that the response that's  returned in that case is different; 

```json
{"message":"Unauthorized","details":null}
```

**Comment by Soulou** [comment] 2016-03-08 13:12
Thanks @thaJeztah for your answer, actually Docker is still panicking when changing the response to that

**Comment by thaJeztah** [comment] 2016-03-08 13:15
@Soulou it's being looked into while we speak; see the conversation on IRC here; https://botbot.me/freenode/docker-maintainers/2016-03-08/?msg=61733440&page=1

**Comment by Soulou** [comment] 2016-03-08 13:17
Ok got it, I'm in the channel, thanks for notifying me

**Comment by Soulou** [comment] 2016-03-08 13:19
Tell me if I can do anything to help/give more info

**Comment by runcom** [comment] 2016-03-08 13:22
> If an attempt to authenticate to the token server fails, the token server should return a 401 > > Unauthorized response indicating that the provided credentials are invalid.

Quoting from https://docs.docker.com/registry/spec/auth/token/

@Soulou this clearly seems your case I suppose. I don't see anywhere any reference about how those *errors* should be returned to the docker daemon but I believe the format should be:
```
{
	"errors": [{
		"code": "UNAUTHORIZED",
		"message": "a message",
		"detail": []
	}]
}
```
I don't know which token service you're using (I suppose it's a custom one), so could you provide with format I gave above?

**Comment by runcom** [comment] 2016-03-08 13:22
I got that format from reading the code, I believe the code needs a proper check instead of panicing though

**Comment by Soulou** [comment] 2016-03-08 13:31
Perfect:

```
354ec3d6a342: Preparing 
52d7ef0f0957: Waiting 
17191cd7bd3d: Waiting 
f4288da73a4c: Waiting 
62429a5c28dd: Waiting 
5f70bf18a086: Waiting 
e8061ac24ae3: Waiting 
3c84ae1bbde2: Waiting 
b5f05191d11d: Waiting 
unauthorized: no authorization provided
```

**Comment by runcom** [comment] 2016-03-08 13:38
great, let's see if this is reproducible in 1.9 also, I believe now that it's up to the token service to comply with the format docker/distribution expects but I see docs lack wrt this kind of documentation. I'm not sure it's up to docker/docker to handle this - but I believe we could handle this better

**Comment by Soulou** [comment] 2016-03-08 13:43
distribution config.yml

```
version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
auth:
  token:
    realm: "http://localhost:5001"
    service: "registry"
    issuer: "auth-registry"
    rootcertbundle: /cert.pem
http:
  addr: 0.0.0.0:5000
  secret: thisisasecret
```

self signed Cert generation

```
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.pem
```

**Comment by runcom** [comment] 2016-03-08 13:46
https://github.com/docker/docker/issues/21027#issuecomment-193788160 /cc @aaronlehmann does it needs to be documented or we could just check if `v[0]` in retry error is actually filled?

**Comment by Soulou** [comment] 2016-03-08 13:52
(or both) ;-)

**Comment by runcom** [comment] 2016-03-08 14:37
@Soulou I cannot reproduce the panic when *pulling* could you double check it's an issue at pull time? I reproduced and I'm about to make a PR

**Comment by Soulou** [comment] 2016-03-08 14:41
I've to try with the pull operation, only tried when pushing so far. (I needed to get a first image in before pulling it ;-) )

**Comment by thaJeztah** [comment] 2016-03-08 15:07
@Soulou could you send me an e-mail at sebastiaan@docker.com? Wondering if you'd be interested to be added to our "testers" mailinglist

**Comment by runcom** [comment] 2016-03-08 15:48
> I've to try with the pull operation, only tried when pushing so far. (I needed to get a first image in before pulling it ;-) )

talked on IRC, the panic is only in push (not also pull)
pulls die with:
```
Error response from daemon: Get http://localhost:5005/v2/busybox/manifests/latest: <nil>
```
w/o panicing

**Comment by thaJeztah** [comment] 2016-03-08 18:00
This is resolved by https://github.com/docker/docker/pull/21030, but will have to be merged back to master after 1.10.3 has been released

**Comment by runcom** [comment] 2016-03-14 19:02
@thaJeztah has this been merged back into master? does it need a label?

**Comment by thaJeztah** [comment] 2016-03-14 19:26
@runcom oh, good one; I think this was the only PR directly against the bump branch; can you open a PR to cherry-pick it back to master?

**Comment by runcom** [comment] 2016-03-15 08:37
sure!

**Comment by runcom** [comment] 2016-03-16 10:16
reopening for master

**Closed** 2016-03-16 20:44 UTC
Labels: group/distribution, kind/bug, priority/P1
