### ISSUE TITLE
Dockerfile - ADD url and ADD local_file behaves differently for archives

### ISSUE THREAD

**Issue by TZer0** [docker/docker#11174] opened 2015-03-05 15:13 UTC
Description of problem:
When using ADD in a Dockerfile to fetch an url, archive extracting is not performed.

`docker version`:

```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

`docker info`:

```
Containers: 17
Images: 89
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 155
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.706 GiB
Name: ###
ID: VOGC:OEM2:U2C3:LKFR:QFD6:VVRF:WTSI:HUFY:SRRD:X5S5:VBAE:PF6H
Debug mode (server): false
Debug mode (client): true
Fds: 60
Goroutines: 56
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

`uname -a`:

```
Linux ### 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Physical (and probably irrelevant).

How reproducible:
Happens every time.

Steps to Reproduce:
Make a folder with the following:
Dockerfile:
```
FROM debian:latest

ADD http://ftp.gnu.org/gnu/tar/tar-1.28.tar.gz /dltar
ADD tar-1.28.tar.gz /localtar
```
script.sh:
```
wget http://ftp.gnu.org/gnu/tar/tar-1.28.tar.gz

docker build .
```
Run the script.

Actual Results:
ls -lah in the container yields:
```
root@6bbcaa62ebe5:/# ls -lah
...
-rw-------   1 root root 3.7M Jul 27  2014 dltar
...
drwxr-xr-x   3 root root 4.0K Mar  5 15:00 localtar
...
```

Expected Results:
dltar and localtar should be identical (folders).

Additional info:
Also occurs in version 1.5.0 on another machine.
`docker version`:
```
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by cpuguy83** [comment] 2015-03-05 15:19
Closing since this is expected behavior and is documented here: https://docs.docker.com/reference/builder/#add

**Comment by duglin** [comment] 2015-03-05 15:20
See: https://docs.docker.com/reference/builder/#add
and in particular where it says "Resources from remote URLs are not decompressed."

I can't explain why this is but sadly changing it would break backwards compatibility.
Once we have https://github.com/docker/docker/pull/10775 we can look at adding options to control stuff like this.

**Closed by cpuguy83** 2015-03-05 15:19 UTC

**Comment by TZer0** [comment] 2015-03-05 20:05
Whoops, managed to miss that. Sorry about that.

I'm not sure if the current solution is optimal in any case. What if I want to add a specific tar to my docker image but not extract it?

**Comment by duglin** [comment] 2015-03-05 20:08
Try COPY for local files instead of ADD
