### ISSUE TITLE
docker 1.8.2 `docker attach some specific container` hangs, no response

### ISSUE THREAD

**Issue by yjhjstz** [docker/docker#18904] opened 2015-12-25 07:04 UTC
```sh
[root@centos7-x64 ~]# docker -v
Docker version 1.8.2-el7.centos, build a01dc02/1.8.2
```
Use `pstack ` trace stack below:
```sh
[root@centos7-x64 ~]# pstack 16958
Thread 4 (Thread 0x7f3127af3700 (LWP 16959)):
#0  runtime.futex () at /usr/lib/golang/src/runtime/sys_linux_amd64.s:278
#1  0x000000000043c9c6 in runtime.futexsleep () at /usr/lib/golang/src/runtime/os_linux.c:55
#2  0x00000000004199e4 in runtime.notetsleep_internal (n=0x1779320 <runtime.sched+128>, ns=60000000000, ~r2=96) at /usr/lib/golang/src/runtime/lock_futex.go:170
#3  0x0000000000419af7 in runtime.notetsleep (n=0x1779320 <runtime.sched+128>, ns=60000000000, ~r2=false) at /usr/lib/golang/src/runtime/lock_futex.go:190
#4  0x00000000004442de in sysmon () at /usr/lib/golang/src/runtime/proc.c:2899
#5  0x000000000043f6b1 in mstart () at /usr/lib/golang/src/runtime/proc.c:859
#6  0x000000000043f5c4 in runtime.mstart () at /usr/lib/golang/src/runtime/proc.c:836
#7  0x00000000004044c4 in crosscall_amd64 () at /usr/lib/golang/src/runtime/cgo/gcc_amd64.S:35
#8  0x0000000000000000 in ?? ()
Thread 3 (Thread 0x7f31272f2700 (LWP 16960)):
#0  runtime.futex () at /usr/lib/golang/src/runtime/sys_linux_amd64.s:278
#1  0x000000000043c957 in runtime.futexsleep () at /usr/lib/golang/src/runtime/os_linux.c:49
#2  0x000000000041992d in runtime.notetsleep_internal (n=0x1785740 <runtime.sig>, ns=-1, ~r2=false) at /usr/lib/golang/src/runtime/lock_futex.go:157
#3  0x0000000000419b7a in runtime.notetsleepg (n=0x1785740 <runtime.sig>, ns=-1, ~r2=true) at /usr/lib/golang/src/runtime/lock_futex.go:202
#4  0x0000000000426915 in runtime.signal_recv (~r0=0) at /usr/lib/golang/src/runtime/sigqueue.go:109
#5  0x00000000008839ef in os/signal.loop () at /usr/lib/golang/src/os/signal/signal_unix.go:21
#6  0x000000000044bc41 in runtime.goexit () at /usr/lib/golang/src/runtime/asm_amd64.s:2232
#7  0x0000000000000000 in ?? ()
Thread 2 (Thread 0x7f3126af1700 (LWP 16961)):
#0  runtime.futex () at /usr/lib/golang/src/runtime/sys_linux_amd64.s:278
#1  0x000000000043c957 in runtime.futexsleep () at /usr/lib/golang/src/runtime/os_linux.c:49
#2  0x000000000041987e in runtime.notesleep (n=0xc2080fe0d8) at /usr/lib/golang/src/runtime/lock_futex.go:145
#3  0x000000000043fe29 in stopm () at /usr/lib/golang/src/runtime/proc.c:1178
#4  0x0000000000440c82 in findrunnable () at /usr/lib/golang/src/runtime/proc.c:1487
#5  0x0000000000441041 in schedule () at /usr/lib/golang/src/runtime/proc.c:1575
#6  0x00000000004412c3 in runtime.park_m () at /usr/lib/golang/src/runtime/proc.c:1654
#7  0x000000000044973a in runtime.mcall () at /usr/lib/golang/src/runtime/asm_amd64.s:186
#8  0x000000c208012000 in ?? ()
#9  0x000000000043f5c4 in runtime.mstart () at /usr/lib/golang/src/runtime/proc.c:836
#10 0x00000000004044c4 in crosscall_amd64 () at /usr/lib/golang/src/runtime/cgo/gcc_amd64.S:35
#11 0x000000c208034ae8 in ?? ()
#12 0x00007f3126af1700 in ?? ()
#13 0x00007f3126af19c0 in ?? ()
#14 0x0000000000000000 in ?? ()
Thread 1 (Thread 0x7f3129c16800 (LWP 16958)):
#0  runtime.epollwait () at /usr/lib/golang/src/runtime/sys_linux_amd64.s:400
#1  0x000000000041fad3 in runtime.netpoll (block=true, gp=0x0) at /usr/lib/golang/src/runtime/netpoll_epoll.go:68
#2  0x0000000000440ba5 in findrunnable () at /usr/lib/golang/src/runtime/proc.c:1472
#3  0x0000000000441041 in schedule () at /usr/lib/golang/src/runtime/proc.c:1575
#4  0x000000000044152e in goexit0 () at /usr/lib/golang/src/runtime/proc.c:1717
#5  0x000000000044973a in runtime.mcall () at /usr/lib/golang/src/runtime/asm_amd64.s:186
#6  0x00000000017797b0 in runtime.g0 ()
#7  0x000000000043f5c4 in runtime.mstart () at /usr/lib/golang/src/runtime/proc.c:836
#8  0x000000000044963c in runtime.rt0_go () at /usr/lib/golang/src/runtime/asm_amd64.s:106
#9  0x0000000000000003 in ?? ()
#10 0x00007fffeeb0dc48 in ?? ()
#11 0x0000000000000003 in ?? ()
#12 0x00007fffeeb0dc48 in ?? ()
#13 0x0000000000000000 in ?? ()
```

Is it fixed in 1.9.x?

**Comment by thaJeztah** [comment] 2015-12-25 12:18
Could you provide some more information on how to reproduce? Is this the same issue as described in https://github.com/docker/docker/issues/8521?

> Is it fixed in 1.9.x?

Have you tried? Docker 1.9.1 is available for a while now..

**Comment by yjhjstz** [comment] 2015-12-26 01:08
yes, the same, and docker exec -it [container-id] bash worked for me.

**Comment by thaJeztah** [comment] 2015-12-26 01:11
Thanks @yjhjstz I'll close this issue as a duplicate of https://github.com/docker/docker/issues/8521. Please continue the discussion there, or subscribe to that issue using the "subscribe" button

**Closed by thaJeztah** 2015-12-26 01:11 UTC
Labels: status/more-info-needed
