### ISSUE TITLE
CONFIG_CGROUP_NSmissing

### ISSUE THREAD

**Issue by aerodame** [docker/docker#10543] opened 2015-02-04 02:48 UTC
Just performing a basic vanilla install of Debian Jessie according to the Docker website.  First problem is that the Jessie release doesn't contain lxc.  So that must be loaded.  But once that is loaded and running lxc-checkconfig we get: (all other checks are enabled and green)
Cgroup namespace: CONFIG_CGROUP_NSmissing

Also, after installing lxc... we then 
$ apt-get install docker.io
Reading package lists... Done
...
E: Unable to locate package docker.io
E: Couldn't find any package by regex 'docker.io'

So... googled around and resorted to the docker notes here:
https://www.debian-administration.org/article/696/A_brief_introduction_to_using_docker

$ wget https://get.docker.io/builds/Linux/x86_64/docker-latest -O /usr/local/bin/docker
$ chmod 755 /usr/local/bin/docker

So, this works until we try to run a docker shell 

$ docker run -it ubuntu /bin/bash
...
ERRO[0062] Handler for POST /containers/{name:.*}/start returned error: Cannot start container 49b7cbe11a84a83ee1b61dd8a82036875f89081a253ed333bfa15454a3b61397: failed to find the cgroup root

**Comment by unclejack** [comment] 2015-02-04 16:14
@aerodame LXC isn't required for Docker. the `lxc-docker` name of the package has been chosen because there was already a `docker` package on Debian and Ubuntu.

`lxc-checkconfig` was outdated the last time I checked and it didn't actually check if the right kernel config options are enabled properly. This might still be the case today. This isn't a big deal, it's just a shell script and LXC works just fine, even if lxc-checkconfig complains.

There were problems with using LXC for Docker and some of these were extremely difficult to solve at the time. For example, there wasn't an easy way to use the system's LXC without shelling out to the LXC tools.
There were also problems caused by the fact that different distributions had different versions of LXC and coding against the quirks of each and every version would have been difficult.

The current execution driver is the native one and that's based on libcontainer. This driver is the default one and there's no need to have lxc installed.

This script https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh should be used to verify that your system has all the required kernel config dependencies enabled.

I'm going to close this issue now since it's not a real bug and both Docker, and LXC work properly when that error is printed by `lxc-checkconfig`. Please feel free to comment.

**Closed by unclejack** 2015-02-04 16:14 UTC

**Comment by aerodame** [comment] 2015-02-04 19:31
OK, I ran this and it has multiple failures.

Before I get into this, can you explain what things need to be installed for Debian 7.8?  I have started from a very simple baseline by downloading the latest (as of 2/3/15) stable release of Debian (debian-7.8.0-amd64-netinst.iso installed into VirtualBox).  Your instructions do not work on the Docker website.

# apt-get install docker.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker.io
E: Couldn't find any package by regex 'docker.io'

Am I missing a more fundamental apt-get sources-list dependency?
Does fixing the apt-get above fix the problems and dependencies below?

I really became confused when trying to follow the instructions from Debian.  Someone should reach out to them and have them put up a big disclaimer that all of their information needs to be deprecated. ( I will try to log a note to them)
https://www.debian-administration.org/article/696/A_brief_introduction_to_using_docker

Here's the output from check-config.sh...
warning: /proc/config.gz does not exist, searching other paths for kernel config...
info: reading kernel config from /boot/config-3.2.0-4-amd64 ...

Generally Necessary:
- cgroup hierarchy: nonexistent??
    (see https://github.com/tianon/cgroupfs-mount)
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_MACVLAN: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_NF_NAT_IPV4: missing
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_SWAP: missing
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_CGROUP_PERF: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled
    - CONFIG_EXT4_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: missing

**Comment by unclejack** [comment] 2015-02-04 21:19
@aerodame That kernel is unsupported. Please install a kernel from debian wheezy backports.

**Comment by aerodame** [comment] 2015-02-06 03:42
For whatever reason I seemed to get 7.8 to now work with Docker... is there something specifically not supported in 7.8 that was in 7.7?  I was under a misconception that 7.8 was actually Jessie 8.0 which was caused by the way the install packages are organized on the Debian downloads pages.  Probably a dumb mistake, but never-the-less Docker is working on 7.8 for now.

This is probably a new topic I should log, but I'm very keen on getting a cluster of Debian CuBox (i.MX6) microservers up and running.  Problem is they are all ARM A9 32-bit Linux machines with the following configuration...
# uname -a
=> Linux cubox-i 3.14.14-cubox #1 SMP Thu Dec 18 13:19:43 CET 2014 armv7l armv7l armv7l GNU/Linux

Can you help direct me to some specific instructions on how to cross compile Docker for operation on this platform?  Something similar to what the Resin.io guys did for Raspberry PI, but for a much more powerful ARM A9 processor.
