### ISSUE TITLE
Limit Dockerfile to a specific version ID

### ISSUE THREAD

**Issue by 1605200517** [docker/docker#19050] opened 2016-01-04 14:36 UTC
FEATURE REQUEST

As Dockerfile build instructions are still changing, I miss the possibility to tag somehow the minimal supported version to clearly state minumum requirements on the building system. - as we know it from Maven. (Yes after all the system would spit buckets of ambigous errors, so I thought a more declarative style might be a benefit)

Something like

LANGUAGE_VERSION=1.9 

would me in my opinion really helpful!

thanks. :)

**Comment by thaJeztah** [comment] 2016-01-04 18:47
I think this is a duplicate of an issue I opened a long time ago; https://github.com/docker/docker/issues/4907.

However, the Dockerfile syntax is currently frozen, so we currently cannot accept changes to the Dockerfile syntax; https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

**Comment by MHBauer** [comment] 2016-01-05 19:25
I understand maven so I instantly understand what this could do for us. If it were easier to change the builder, and we weren't in a freeze, I think it would help solve a lot of problems that require us to have the freeze. I think having a version that is respected by the builder, it becomes easy to do a clean split of previous functionality to new functionality (Not that a refactor or rewrite of the builder would be easy, this would isolate any effects). This could be a really good first steep to allowing experimentation with builder changes.

**Comment by LK4D4** [comment] 2016-09-14 17:56
Closing this issue as inactive in efforts to make issue list cleaner. Feel free to open new proposal.

**Closed by LK4D4** 2016-09-14 17:56 UTC
Labels: area/builder, kind/feature
