### ISSUE TITLE
docker exec not work while the command include '<' character

### ISSUE THREAD

**Issue by Leo-Lei** [docker/docker#32261] opened 2017-03-31 12:02 UTC
For example, I have a container which is running a mysql server, and I want to use the following command to import some data to mysql. But it failed...
`docker exec some-mysql mysql -uroot < /opt/hello.sql`
returns 
`-bash: /opt/rds-common-dump.sql: No such file or directory`

The '<' character is interpreted to the Linux shell redirection command.

What should I do if I want to execute a command which include '<', in the docker exec command?

**Comment by thaJeztah** [comment] 2017-03-31 12:18
This is expected; as you mentioned, the `<` is redirected in the _local_ shell, so effectively, you're trying to pipe a local `/opt/hello.sql` file to the "remote" (container) `docker exec some-mysql mysql -uroot`.

If `/opt/hello.sql` is inside the container, you can run it like this;

```bash
docker exec some-mysql sh -c 'mysql -uroot < /opt/hello.sql'
```

Note that if you're using the official MySQL image, you can have it automatically import a dump when it's started, see https://hub.docker.com/_/mysql/ (underneath the "Initializing a fresh instance" section);

> When a container is started for the first time, a new database with the specified name will be created and initialized with the provided configuration variables. Furthermore, it will execute files with extensions `.sh`, `.sql` and `.sql.gz` that are found in `/docker-entrypoint-initdb.d`. Files will be executed in alphabetical order. You can easily populate your mysql services by mounting a SQL dump into that directory and provide custom images with contributed data. SQL files will be imported by default to the database specified by the `MYSQL_DATABASE` variable.

I'll close this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-03-31 12:18 UTC

**Comment by Leo-Lei** [comment] 2017-03-31 12:44
Hi, thaJeztah, many thanks for giving me so much help. Yes, it works very well.
Also, as you mentioned, I use the official mysql engine. But my requirement is not simply import a mysql dump, actually, I am setting up a mysql master-slave solution by docker. The dump file is dynamic produced by other application, and after the mysql started, I need to execute some sql query dynamically, which depend on the output of other application and may need to restart the mysql server. So I tend to use a Python script and run the mysql command by docker exec functionality, which I think is more flexible.
Finally, the most important, thank you for spending time on replying my question, really helpful, really thanks.
