### ISSUE TITLE
Ability to limit a container's disk space usage

### ISSUE THREAD

**Issue by jamshid** [docker/docker#12462] opened 2015-04-17 00:11 UTC
There doesn't seem to be a way to limit a containers disk usage, like there is with memory/cpu (https://docs.docker.com/reference/run/#runtime-constraints-on-cpu-and-memory). 

Was wanting to do this to test my container in "out of disk space" scenarios, though seems useful in general.

I see the server options `--storage-opt` for changing basesize but that is a global setting https://docs.docker.com/reference/commandline/cli/ ?

**Comment by thaJeztah** [comment] 2015-04-17 00:22
Hi, @jamshid, thanks for proposing this!

However, I think this is a duplicate of https://github.com/docker/docker/issues/3804.

I'm going to close this issue so that the discussion will take place on a single location in https://github.com/docker/docker/issues/3804. Feel free to comment on this issue after closing.

Thanks again for giving your input, it's really appreciated!

**Closed by thaJeztah** 2015-04-17 00:22 UTC
Labels: kind/feature
