### ISSUE TITLE
docker images with tag fails to list image

### ISSUE THREAD

**Issue by dhbaird** [docker/docker#10830] opened 2015-02-16 18:08 UTC
Is there a way to get the imageid for a given repository+tag? Thanks.

Desired new behavior:

```
# docker images ubuntu:14.04
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
ubuntu              14.04               5ba9dab47459        2 weeks ago         188.3 MB
```

Actual behavior right now:

```
# docker images ubuntu:14.04
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<...empty...>
```

Versions:
```
# docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by dhbaird** [comment] 2015-02-16 18:13
I figured out an answer to my question, which solves my issue. However, this still seems like an inconsistency in the CLI (it should be possible to specify a tag anywhere, no?)- if you disagree, please close the ticket, as I am satisfied with the solution below. Thanks!

Workaround solution:
```
# docker images ubuntu:14.04
[{
    "Architecture": "amd64",
    "Author": "",
    "Checksum": "tarsum.dev+sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "Comment": "",
    "Config": {
....
```

**Comment by jfrazelle** [comment] 2015-02-17 00:36
closing as duplicate of #8048 please comment there so the threads in one place

**Closed by jfrazelle** 2015-02-17 00:36 UTC
