### ISSUE TITLE
docker pull error

### ISSUE THREAD

**Issue by mahsa-frj** [docker/docker#13103] opened 2015-05-09 13:14 UTC
hi, i install docker-io on fedora, start it, but when execute this command:
docker pull fedora
i get this output:
Pulling repository fedora
93be8052dfb8: Error pulling image (latest) from fedora, ApplyLayer exit status 1 stdout:  stderr: unexpected EOF 
ected EOF cf: Download complete 
FATA[0109] Error pulling image (latest) from fedora, ApplyLayer exit status 1 stdout:  stderr: unexpected EOF

**Comment by mahsa-frj** [comment] 2015-05-10 06:19
1. docker version:
     Client version: 1.5.0
     Client API version: 1.17
     Go version (client): go1.3.3
     Git commit (client): a8a31ef/1.5.0
     OS/Arch (client): linux/amd64
     Server version: 1.5.0
     Server API version: 1.17
     Go version (server): go1.3.3
     Git commit (server): a8a31ef/1.5.0

2. docker info:
    
Containers: 0
Images: 1
Storage Driver: devicemapper
 Pool Name: docker-253:1-1444602-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 306.4 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 757.8 kB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.85 (2014-04-10)
Execution Driver: native-0.2
Kernel Version: 3.19.5-100.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)
CPUs: 8
Total Memory: 7.49 GiB
Name: fedora1.osslab.com
ID: QI3W:7DV2:WGNI:Q65V:LA4A:FWS7:QJCC:KENU:MMVB:WLOP:C56U:ZKYZ

3. uname -a:
Linux fedora1.osslab.com 3.19.5-100.fc20.x86_64 #1 SMP Mon Apr 20 19:51:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

4. Environment details: 
 Physical

5. Steps to Reproduce:
   1. install docker-io on fedora
   2. service docker start
   3. docker run -i -t fedora /bin/bash

6. Actual result:
Unable to find image 'fedora:latest' locally
Pulling repository fedora
93be8052dfb8: Error pulling image (latest) from fedora, ApplyLayer exit status 1 stdout:  stderr: unexpected EOF it status 1 stdout:  stderr: unexpected EOF 
FATA[0187] Error pulling image (latest) from fedora, ApplyLayer exit status 1 stdout:  stderr: unexpected EOF 

7.Expected result:
run without any error.

thanks for your reply.

**Comment by shishir-a412ed** [comment] 2015-05-11 13:02
@mahsa-frj Works fine for me.

1) uname -a 
Linux localhost.localdomain 3.19.5-200.fc21.x86_64 #1 SMP Mon Apr 20 19:51:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

2) docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 3eac457/1.6.0
OS/Arch (client): linux/amd64

3) docker info
Containers: 256
Images: 99
Storage Driver: devicemapper
 Pool Name: docker-253:0-262217-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.797 GB
 Data Space Total: 107.4 GB
 Data Space Available: 35.78 GB
 Metadata Space Used: 20.47 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.127 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Kernel Version: 3.19.5-200.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 4
Total Memory: 11.43 GiB
Name: localhost.localdomain
ID: YLV3:6DD2:IKHU:CICI:SBHM:BF3A:UPWK:YEN3:LVWP:ZORB:3KEQ:OOIZ

Do you face the same issue with Fedora 21 and Docker 1.6 too ?

Shishir

**Comment by thaJeztah** [comment] 2015-05-11 22:49
@mahsa-frj are you able to test this on docker 1.6.1, are you still able to reproduce it on that version?

**Comment by mahsa-frj** [comment] 2015-05-12 05:10
thanks @shishir-a412ed and @thaJeztah, i should try this version. i face this problem with a lot of images in docker reposiory, but some of them pull true and can work with. 
e.x: 
docker pull  mattdm/fedora, works fine, but i want to pull other version...

**Comment by arpras** [comment] 2015-06-04 00:53
@mahsa-frj Did updating to 1.6 fix the problem for you ?

**Comment by thaJeztah** [comment] 2015-06-07 08:37
@mahsa-frj I'm going to close this issue, because we cannot reproduce this issue and this might be solved in the current release.

Feel free to comment if you think I close this by mistake and you're still able to reproduce this on a fully updated system and docker version.

**Closed by thaJeztah** 2015-06-07 08:37 UTC

**Comment by keithyau** [comment] 2015-08-11 04:29
same issue here on CentOS 7 + Docker 1.6.2 with image docker / whalesay


Unable to find image 'docker/whalesay:latest' locally
Trying to pull repository docker.io/docker/whalesay ...
fb434121fc77: Error pulling image (latest) from docker.io/docker/whalesay, ApplyLayer exit status 1 stdout:  stderr: unexpected EOF it status 1 stdout:  stderr:FATA[1278] Error pulling image (latest) from docker.io/docker/whalesay, ApplyLayer exit status 1 stdout:  stderr: unexpected EOF 
[keithyau@localhost ~]$ docker -v
Docker version 1.6.2, build ba1f6c3/1.6.2
