### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by tianke0711** [docker/docker#32658] opened 2017-04-17 09:09 UTC
after I run the command: docker info, there is error:

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

there is error: do guys know how to solve it:

**Comment by athulk1994** [comment] 2017-04-17 09:32
Did you  try running the command as superuser?

**Comment by xiaods** [comment] 2017-04-17 09:42
your docker daemon is not working?

**Comment by athulk1994** [comment] 2017-04-17 09:50
Try  running systemctl status docker to check  whether daemon is running or not

**Comment by tianke0711** [comment] 2017-04-17 09:55
thanks for your comments.
$ systemctl status docker t

● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Mon 2017-04-17 18:45:50 JST; 8min ago
     Docs: https://docs.docker.com
  Process: 15556 ExecStart=/usr/bin/dockerd -H fd:// ^[[0;1;31m(code=exited, status=1/FAILURE)^[[0m
 Main PID: 15556 (code=exited, status=1/FAILURE)
~
~
~
~

**Comment by athulk1994** [comment] 2017-04-17 10:03
Daemon is down it seems. Run systemctl start docker and see whether is starts up

**Comment by tianke0711** [comment] 2017-04-17 10:13
thanks @athulk1994  for your comments!
$ systemctl start docker

==== AUTHENTICATION COMPLETE ===
Job for docker.service failed because the control process exited with error code                                 . See "systemctl status docker.service" and "journalctl -xe" for details.

**Comment by athulk1994** [comment] 2017-04-17 10:21
Run systemctl status docker.service and see what the error is

**Comment by tianke0711** [comment] 2017-04-17 10:22
thanks @athulk1994 

$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Mon 2017-04-17 19:15:33 JST; 6min ago
     Docs: https://docs.docker.com
  Process: 15730 ExecStart=/usr/bin/dockerd -H fd:// ^[[0;1;31m(code=exited, status=1/FAILURE)^[[0m
 Main PID: 15730 (code=exited, status=1/FAILURE)

**Comment by tianke0711** [comment] 2017-04-17 10:26
$ sudo journalctl -xe
-- Logs begin at Mon 2017-04-03 23:52:44 JST, end at Mon 2017-04-17 19:25:39 JST. --
Apr 17 18:02:41 NVIDIA2.cs179idcfcloud.internal sudo[83155]: ^[[0;1;39mchallenge98 : TTY=pts/6 ; PWD=/data/home2/
challenge98 ; USER=root ; COMMAND=/usr/bin/docker info^[[0m
Apr 17 18:02:41 NVIDIA2.cs179idcfcloud.internal sudo[83155]: pam_unix(sudo:session): session opened for user root
 by challenge98(uid=0)
Apr 17 18:02:41 NVIDIA2.cs179idcfcloud.internal sudo[83155]: pam_unix(sudo:session): session closed for user root

Apr 17 18:03:16 NVIDIA2.cs179idcfcloud.internal sudo[83161]: ^[[0;1;39mchallenge98 : TTY=pts/6 ; PWD=/data/home2/
challenge98 ; USER=root ; COMMAND=/usr/sbin/usermod -aG challenge98^[[0m
Apr 17 18:03:16 NVIDIA2.cs179idcfcloud.internal sudo[83161]: pam_unix(sudo:session): session opened for user root
 by challenge98(uid=0)
Apr 17 18:03:16 NVIDIA2.cs179idcfcloud.internal sudo[83161]: pam_unix(sudo:session): session closed for user root

Apr 17 18:03:35 NVIDIA2.cs179idcfcloud.internal sudo[83163]: ^[[0;1;39mchallenge98 : TTY=pts/6 ; PWD=/data/home2/
challenge98 ; USER=root ; COMMAND=/usr/sbin/usermod -aG docker^[[0m
Apr 17 18:03:35 NVIDIA2.cs179idcfcloud.internal sudo[83163]: pam_unix(sudo:session): session opened for user root
 by challenge98(uid=0)
Apr 17 18:03:35 NVIDIA2.cs179idcfcloud.internal sudo[83163]: pam_unix(sudo:session): session closed for user root

Apr 17 18:04:49 NVIDIA2.cs179idcfcloud.internal sudo[83177]: ^[[0;1;39mchallenge98 : TTY=pts/6 ; PWD=/data/home2/
challenge98 ; USER=root ; COMMAND=/usr/sbin/usermod -aG docker^[[0m
Apr 17 18:04:49 NVIDIA2.cs179idcfcloud.internal sudo[83177]: pam_unix(sudo:session): session opened for user root
 by challenge98(uid=0)
Apr 17 18:04:49 NVIDIA2.cs179idcfcloud.internal sudo[83177]: pam_unix(sudo:session): session closed for user root

Apr 17 18:05:01 NVIDIA2.cs179idcfcloud.internal CRON[83184]: pam_unix(cron:session): session opened for user root
 by (uid=0)
Apr 17 18:05:01 NVIDIA2.cs179idcfcloud.internal CRON[83185]: (root) CMD (command -v debian-sa1 > /dev/null && deb
ian-sa1 1 1)
Apr 17 18:05:01 NVIDIA2.cs179idcfcloud.internal CRON[83184]: pam_unix(cron:session): session closed for user root

Apr 17 18:12:29 NVIDIA2.cs179idcfcloud.internal sudo[83194]: ^[[0;1;39mchallenge98 : TTY=pts/6 ; PWD=/data/home2/
challenge98 ; USER=root ; COMMAND=/usr/bin/docker -d^[[0m
Apr 17 18:12:29 NVIDIA2.cs179idcfcloud.internal sudo[83194]: pam_unix(sudo:session): session opened for user root
 by challenge98(uid=0)
Apr 17 18:12:29 NVIDIA2.cs179idcfcloud.internal sudo[83194]: pam_unix(sudo:session): session closed for user root
(stdin):

**Comment by tianke0711** [comment] 2017-04-18 01:46
hi @athulk1994  are you online? could you help me how to solve it, thanks!

**Comment by athulk1994** [comment] 2017-04-18 04:56
Can you  run journalctl -u docker.service and give me the output

**Comment by thaJeztah** [comment] 2017-04-18 05:11
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the discussion 👍

**Closed by thaJeztah** 2017-04-18 05:11 UTC

**Comment by tianke0711** [comment] 2017-04-18 08:14
I have solved it, just restart the ubuntu server: sudo shutdown -r now

**Comment by phroiland** [comment] 2017-04-26 21:11
Not sure what happened with my setup, but I'm running on **Ubuntu 16.04**, I've had a number of problems not limited to just docker. 

I ultimately purged and reinstalled everything from the **docker-ce** install. I mean everything. Still not working...

Through my internet wizardry I was able to find an article mentioning that the file located at:

**$ sudo nano /etc/systemd/system/docker.service**

Had a -d in the place of the daemon at Execstart. That wasn't the case for me. I had ...daemon -D..., but I did notice that it was pointing to **/usr/bin/local/docker**. That didn't exist, but what does exist is **/usr/bin/docker**. In that location you will also find docker-containerd, dockerd, etc...

Anyway, I made the change to the docker.service file--simply dropping **/local** out of there. Saved.
Then:

**$ systemctl daemon-reload
$ sudo service docker restart
$ sudo service docker status (should see active (running))
$ sudo docker run hello-world**

Success!

**Comment by sgalinma** [comment] 2017-09-19 12:06
@athulk1994 thank you a lot, I've tried a lot of things but any of them worked except your solution! May God bless you haha

**Comment by hansamann** [comment] 2017-11-05 09:25
Hi all,

I've installed docker on a raspi 3 / raspbian lite and after a restart I was able to build and run a docker image yesterday. Today restarted, logged in and it seems the docker daemon is no longer running. Tried most of the commands above, but it won't start.

systemctl start docker

results in a ton of kernel messages like

Message from syslogd@bacon at Nov  5 09:23:54 ...
 kernel:[ 1713.914068] ffa0: 801080c0 801a4044 430cc600 00000000 00000000 0002cd30 00000000 012f1900

Message from syslogd@bacon at Nov  5 09:23:54 ...
 kernel:[ 1713.926859] ffc0: 430cc600 00000000 00000000 0000017b 00040000 00000000 00000000 012f1900

Message from syslogd@bacon at Nov  5 09:23:54 ...
 kernel:[ 1713.941403] ffe0: 7eea9a70 7eea9a60 0002212c 76f03590 60000010 00000000 00000000 00000000

Message from syslogd@bacon at Nov  5 09:23:54 ...
 kernel:[ 1713.992748] Code: e89da800 e1a0c00d e92dd800 e24cb004 (e5d02000) 


the installation of docker was done via 

curl -sSL https://get.docker.com | sh
sudo usermod -aG docker pi

Is there a current issue with latest raspbian?

**Comment by thaJeztah** [comment] 2017-11-05 12:04
@hansamann the `Cannot connect to the Docker daemon at unix:///var/run/docker.sock` is a very generic error; it simply means the client wasn't able to connect to the daemon (which can be either a permissions issue, a configuration issue (client attempting to connect to a local daemon, but the daemon is running remotely), or the daemon is not running at all.

The error messages you showed all originate from the kernel, and by itself don't provide a lot of information (could be part of a stack dump, segfault).

As mentioned in my comment above https://github.com/moby/moby/issues/32658#issuecomment-294681444, keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

If, after discussing, you suspect there's a bug in docker, please open a new issue in the https://github.com/docker/for-linux/issues issue tracker, and provide the information that was requested in the issue template.

I'm locking the conversation on this issue, because the `Cannot connect to the Docker daemon` error in itself is not a bug, and I'd like to prevent this issue from collecting unrelated issues (which all result in the same error message from the client)
