### ISSUE TITLE
Hostname should not have domainname appended

### ISSUE THREAD

**Issue by thockin** [docker/docker#20180] opened 2016-02-10 05:39 UTC
Issue #7851, fixed in #8208 worked around the lack of a `domainname` field in libcontainer by joining the `hostname` and `domainname` API fields in the container.  I want to make the case that this is wrong and should be undone.

First, the API has 2 fields.  It stands to reason that if I specified both fields, I probably don't want them just smooshed back into one field.  I expect to get back what I put in.

Second, Linux has a limit of 64 characters for hostname, but the limit for DNS domains is 253 characters (a set of tokens <= 63 characters each).  Smooshing the domainname into the hostname means my whole host+domain has to be less than 64.  As far as I can tell there is no real workaround for this - it is just not possible to use longer domainnames.

Third, standard tools like `hostname` and `dnsdomainname` already operate correctly on docker, which populates the /etc/hosts file properly for the hostname.  There's not actually any reason to smoosh them together.

I think the fix is relatively simple, but it might be surprising to people who depend on the current behavior.  We could ad a flag to choose "force discrete hostname" or something...

@artfulcoder

docker version: 1.10
docker info: Containers: 0
Images: 63
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /usr/local/google/docker/aufs
 Backing Filesystem: extfs
 Dirs: 115
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 15.38 GiB
Name: thockin-glaptop2
ID: JUYZ:74UK:6ZUU:JTPY:SK5F:RMQ7:7GBQ:3X44:XCR4:O3LK:MSYB:34FK
WARNING: No swap limit support

Provide additional environment details (AWS, VirtualBox, physical, etc.): bare metal

List the steps to reproduce the issue:
1. using the API, pass `hostname` and `domainname` fields, such that the total length is > 64
2. observe failure

Describe the results you received:

failure to create container

Describe the results you expected:

non-failure

**Comment by awh** [comment] 2016-02-10 09:28
@thockin #14282

**Comment by thaJeztah** [comment] 2016-02-10 09:44
Yes, this looks like a duplicate of #14282. I'll close this one, please continue the discussion in #14282

**Closed by thaJeztah** 2016-02-10 09:44 UTC
Labels: group/networking
