### ISSUE TITLE
Daemon won't start when ipv6 is set

### ISSUE THREAD

**Issue by MihaMarkic** [docker/docker#29443] opened 2016-12-15 09:29 UTC
**Description**
Docker daemon won't start when daemon.json contains ipv6: true.
The error is:

> Error starting daemon: Error initializing network controller: Error creating default "bridge" network: failed to parse pool request for address space "LocalDefault" pool " subpool ": could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network

It was working just fine before the today's apt-get update.

**Steps to reproduce the issue:**
1. Add daemon.json to /etc/docker/ with { "ipv6": true }
2. Restart docker deamon.

**Describe the results you received:**
Daemon starting fails with error
> Error starting daemon: Error initializing network controller: Error creating default "bridge" network: failed to parse pool request for address space "LocalDefault" pool " subpool ": could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network

**Describe the results you expected:**
Daemon should start just fine.

**Additional information you deem important (e.g. issue happens only occasionally):**
It worked before the latest update with a bunch of containers running.

**Output of `docker version`:**

```
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 15
 Running: 3
 Paused: 0
 Stopped: 12
Images: 22
Server Version: 1.12.4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 150
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 983.8 MiB
Name: kauchuk
ID: ROJ7:X3EK:6OVR:LI3P:TMVE:W44H:DLHN:SIGT:M6TN:O2OJ:3NQC:5FUG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker is running on Ubuntu 16.04. Nothing else is installed.

**Comment by thaJeztah** [comment] 2016-12-15 18:07
@aboch is this the same issue as https://github.com/docker/docker/issues/29411#issuecomment-267083699, and https://github.com/docker/docker/issues/28055#issuecomment-258473730, which will be fixed by https://github.com/docker/docker/pull/29416 ?

**Comment by aboch** [comment] 2016-12-15 18:20
@MihaMarkic

Before the fix for the issue @thaJeztah referenced, user was allowed to create a network , or start the daemon, without specifying the an IPv6 `--subnet`, or `--fixed-cidr-v6` respectively, even when using the default builtin IPAM driver, which does not support auto allocation of IPv6 pools.

In other words that was an incorrect configurations, which had no effects on ipv6 stuff.

The fix, cleared that so that docker will now correctly consult with the IPAM driver to acquire an IPv6 subnet for the bridge network, when user did not supply one.

If the IPAM driver in use is not able to provide one, network creation would fail (in this case the default `bridge` network).

So what you see now id the expected behavior. You need to remove the `--ipv6` flag when you start the daemon. We should probably clarify this somewhere.

**Comment by aboch** [comment] 2016-12-15 18:25
Also reported in #29386

**Comment by MihaMarkic** [comment] 2016-12-15 18:28
OK, thanks. I wish it was made clear before I upgraded :) Should I close it?

**Comment by aboch** [comment] 2016-12-15 18:49
@MihaMarkic 

@thaJeztah was in fact suggesting me we should mention it in the release note. We''l take care of it.
I am now thinking something on this line:

Docker 1.12.4 no longer allows user to start the daemon with `--ipv6` option for the default `bridge` network, unless user also specifies the IPv6 subnet for the default `bridge` network via `--fixed-cidr-v6`. Otherwise daemon start would fail with the following message:

```
Error starting daemon: Error initializing network controller: Error creating default "bridge" network: failed to parse pool request for address space "LocalDefault" pool " subpool ": could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network
```

Similarly, network creation will fail if `--ipv6` is passed but no IPv6 `--subnet` is specified and the default IPAM driver is used.
Failure message will be:

```
$ docker network create --ipv6 incorrect_nw
Error response from daemon: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network
```

Above command will instead succeed if an external IPAM driver which supports auto allocation of IPv6 address pool is used.


Before, even though `--ipv6` was accepted, it was effectively a no-op.

**Comment by MihaMarkic** [comment] 2016-12-15 18:56
Yes, that's make sense. I could solve it immediately if that info was available. I guess mine was an edge case :)

**Comment by aboch** [comment] 2016-12-15 19:04
Sorry for that @MihaMarkic

**Comment by MihaMarkic** [comment] 2016-12-15 19:07
@aboch No worries. I know that you can't think of *all* situations, specially ones that one wouldn't even expect :). Furthermore help provided here is just great. Kudos.

**Comment by aboch** [comment] 2016-12-16 01:13
@MihaMarkic 1.12.4 release notes were updated: https://github.com/docker/docker/releases/tag/v1.12.4
Hopefully this will spare others from the pain. Closing this issue.

**Closed by aboch** 2016-12-16 01:13 UTC
Labels: area/networking, version/1.12

**Comment by jankeromnes** [comment] 2017-11-16 15:27
@aboch This hit me again, because I read on the [IPv6 with Docker](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/#how-ipv6-works-on-docker) page that:

> By default, containers that are created will only get a link-local IPv6 address. To assign globally routable IPv6 addresses to your containers you have to specify an IPv6 subnet to pick the addresses from. Set the IPv6 subnet via the `--fixed-cidr-v6` parameter when starting Docker daemon

Which makes it sound like `--ipv6` enables IPv6 with link-local addresses only, and that you *can* use `--fixed-cidr-v6` or `--subnet` to make them globally routable.

Since your comment indicates that you *must* specify a subnet with `--ipv6`, does that mean that it's not / no longer possible to have IPv6 link-local addresses?

Context: I'm simply trying to enable IPv6 in my containers to work around a `EADDRNOTAVAIL` error in Redis (it just fails when IPv6 is disabled), but I don't want these addresses to be globally routable. Is there something like a `local-only IPv6 subnet`?

**Comment by schmunk42** [comment] 2017-12-05 10:22
> Above command will instead succeed if an external IPAM driver which supports auto allocation of IPv6 address pool is used.

@aboch Is there a driver which supports that, found nothing while asking Google?

**Comment by matthuisman** [comment] 2018-03-28 23:55
@jankeromnes 
I was wondering the same...

Maybe this?
```
{
    "ipv6": true,
    "fixed-cidr-v6": "fe80::1/64"
}
```

**Comment by hr1232** [comment] 2019-05-24 22:56
As this was never really clarified and the "problem" people were having was never solved, here is the solution:

Docker IPv6 is working perfectly, it's just the documentation that doesn't tell people what to do in order to set it up correctly.

Docker will not do SLAAC (Stateless Address Autoconfiguration), not will it use DHCPv6. As it also won't do NATv6 (thank god!), you will have to assign ipv6 prefixes to your networks manually. the default bridge network has to be assigned a network, you can do this by adding the following to daemon.json:
{
"ipv6": true,
"fixed-cidr-v6": "2001:db8::/64",
}

For any other network you might have, you can decide wether or not it will be ipv6 capable. To create an IPv6 capable network, do the following:
docker network create --ipv6 --subnet "2001:db8:1::/64" testnet

Also remember, that this is not NATv6 (thank god!). Therefor you will have to have a route from your router to your docker host!

**Comment by trisimix** [comment] 2019-05-27 17:10
what a headache

**Comment by GF-Huang** [comment] 2022-05-21 11:14
Shxt, how to solve this. I think I configured it correctly as well as following the damn documentation.

![image](https://user-images.githubusercontent.com/4510984/169649109-79c1508c-68bd-4082-a6a5-c8bec90b70ae.png)

![image](https://user-images.githubusercontent.com/4510984/169649057-4cb540f4-d119-437e-841c-8993baf3114b.png)

![image](https://user-images.githubusercontent.com/4510984/169649142-84e837e3-ec2f-422e-8727-563210f6d5d0.png)

![image](https://user-images.githubusercontent.com/4510984/169649150-26c69db5-81f0-4b27-918f-9b8e4679dee1.png)

![image](https://user-images.githubusercontent.com/4510984/169649171-158363b5-98ed-489b-aa0d-08ee959b7f8f.png)
