### ISSUE TITLE
Can't get docker to forward ports

### ISSUE THREAD

**Issue by hoshsadiq** [docker/docker#23087] opened 2016-05-29 12:09 UTC
I've been following a [tutorial](http://prakhar.me/docker-curriculum/) to try and learn docker, however, for some reason I can't seem to access any of the ports it's meant to be opening. For some reason it just times out. Where can I look to get more details on why I'm not able to access this, or otherwise what can I do to access the docker container's server?

Steps done so far:

    $ docker run hello-world # works fine
    $ docker run -d -P --name static-site prakhar1989/static-site # works and returns a docker container id
    $ docker port static-site
    443/tcp -> 0.0.0.0:32768
    80/tcp -> 0.0.0.0:32769

Then I access one of the host through `http://localhost:32768/` or `http://localhost:32769/` but nothing.

Also, I tried accessing the container directly on those ports but without any success.

Any help would be appreciated

**Comment by thaJeztah** [comment] 2016-05-29 22:18
You didn't provide any information about your setup; are you running docker on Mac, Windows, Linux? Using Docker Toolbox?

The `-p` / `-P` options publish the container ports on the public interface of the host that the docker daemon runs on, This can be the local machine (if you're running on Linux), a VM (for example, if you run on Docker Toolbox), or perhaps a server in the cloud.

To access the container on the port that was assigned, try to access it through the IP-address of the host that the daemon runs on.

Please be aware that the GitHub issue tracker is not a general support forum, but for reporting bugs and feature requests. For questions on how to *use* docker, please consider using;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

Given that this is not a bug report, I'll close this issue, but hope that the above information helps you further

**Closed by thaJeztah** 2016-05-29 22:18 UTC
