### ISSUE TITLE
File added to volume directory in the DockerFile doesn't exist if added after volume is created.  

### ISSUE THREAD

**Issue by DanielCaldwell** [docker/docker#14385] opened 2015-07-03 19:32 UTC
### Description of Problem: 

I add a file to a volume in my dockerfile after creating the volume. Upon running a container with the image I created, the files added after the volume was created are missing, where the files before are there. 

### Docker Version:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/home/docker/nginx$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

### Docker info: 

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/home/docker/nginx$ docker info
Containers: 1
Images: 117
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 119
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 1.955 GiB
Name: vagrant-ubuntu-trusty-64
ID: GJIM:FZZG:5K4L:VNKX:GAM4:73W4:C2B2:JBH3:IT64:J67V:ASJH:GBAL
WARNING: No swap limit support
```

### uname info:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/home/docker/nginx$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:32:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### Environment Details:
Running on a vagrant machine made from ubuntu 14.04 image. Here's the box: 
https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

I installed docker and docker composer and nsenter. 

### How to reproduce: 

I have a docker file with the contents here: 

```
FROM nginx
RUN rm /var/log/nginx/*.log
RUN touch /var/log/nginx/beforevolume.txt
VOLUME /var/log/nginx/
RUN touch /var/log/nginx/aftervolume.txt
CMD ls -larh /var/log/nginx
```

I build it with this command: 

```
docker build --tag "my_nginx_data" .
```

When it runs, I see this output:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/home/docker/nginx$ docker run --rm my_nginx_data
total 8.0K
-rw-r--r--  1 root root    0 Jul  3 05:37 beforevolume.txt
drwxr-xr-x 10 root root 4.0K Jul  3 05:37 ..
drwxr-xr-x  2 root root 4.0K Jul  3 19:12 .
```

### Expected Behavior:

What happened to the "aftervolume.txt"? I expected to see them both there. I'm not mapping the volume to a host directory.

**Comment by phemmer** [comment] 2015-07-04 01:17
This is expected behavior. See https://docs.docker.com/userguide/dockervolumes/

* Changes to a data volume will not be included when you update an image.

Also dup of #13117 and #14122

**Comment by DanielCaldwell** [comment] 2015-07-04 03:02
I totally missed that each line in the Dockerfile is updating the image. My understanding was that updating the image came when you rebuilt the whole thing creating a new image. However, with the way the layering works, I'm guessing that there is no difference? 

When I build it I see this output: 

```
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon
Step 0 : FROM nginx
 ---> 319d2015d149
Step 1 : RUN rm /var/log/nginx/*.log
 ---> Running in fb3507657296
 ---> 627d83c567e4
Removing intermediate container fb3507657296
Step 2 : RUN touch /var/log/nginx/beforevolume.txt
 ---> Running in 6029a371bac2
 ---> afde50603c7d
Removing intermediate container 6029a371bac2
Step 3 : VOLUME /var/log/nginx/
 ---> Running in 9905cd836755
 ---> c6b3528e497d
Removing intermediate container 9905cd836755
Step 4 : RUN touch /var/log/nginx/aftervolume.txt
 ---> Running in de1b86a47546
 ---> ffb593c78f4c
Removing intermediate container de1b86a47546
Step 5 : CMD ls -larh /var/log/nginx
 ---> Running in cbacbfb06ff7
 ---> b7b871f58ed2
Removing intermediate container cbacbfb06ff7
Successfully built b7b871f58ed2
```

In my thinking the image wasn't created until the last line. Is it just bad practice to do anything to volumes when you are writing a Dockerfile?

**Comment by thaJeztah** [comment] 2015-07-05 22:46
@phemmer is correct, this is expected behavior (but it is confusing if you're not aware of it). Basically, adding a `VOLUME` declaration to your Dockerfile, makes everything inside the volume's path "immutable", because a (new) volume is created for each build step after that.

Each build step is running in a new container, and committed as a new ("intermediate") image / layer.

If you really need a path to be a volume, it's best to move the `VOLUME` instruction to the end of your Dockerfile or, alternatively, don't use `VOLUME`, but specify the volume at run time, using the `-v/--volume` option.

I'm going to close this issue for the reasons mentioned above, but feel free to comment her after I've closed it.

**Closed by thaJeztah** 2015-07-05 22:46 UTC
