### ISSUE TITLE
how to solve it? docker: error creating overlay mount to invalid argument

### ISSUE THREAD

**Issue by juaby** [docker/docker#23930] opened 2016-06-24 11:00 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.6.2-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.61 GiB
Name: juaby.com
ID: YWHY:CGJF:MVTA:PKZJ:YYOU:52Q6:6Q36:DVY7:HZUP:IGS5:A2GC:BOE6
Docker Root Dir: /export/docker-data
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)

**Steps to reproduce the issue:**
1.docker pull registry
2.sudo docker run -d -p 5000:5000 -v /export/docker-data/registry:/tmp/registry registry
3.

**Describe the results you received:**

docker: Error response from daemon: error creating overlay mount to /export/docker-data/overlay/e86c5ccec4b435b048c3d64753a8dbcedc8655753ee18f256f0800fdedb783c6-init/merged: invalid argument.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment] 2016-06-24 13:10
This is a very strange error.
Can you provide daemon logs when this happens?
Do you get any errors if you don't use `-v`?

Is CentOS really shipping a 4.6 kernel?

**Comment by unclejack** [comment] 2016-06-24 13:18
@cpuguy83 CentOS 7 ships with kernel 3.10.

This setup is unsupported because it's not supported by the distribution itself either.

**Comment by juaby** [comment] 2016-06-27 03:14
all env :
```
$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)
```
```
$ uname -r
4.6.2-1.el7.elrepo.x86_64
```
```
$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since 一 2016-06-27 11:01:13 CST; 6min ago
     Docs: https://docs.docker.com
 Main PID: 5451 (docker)
   Memory: 51.1M
   CGroup: /system.slice/docker.service
           ├─5451 /usr/bin/docker daemon -H fd:// --graph="/export/docker-data" --storage-driver=overlay
           └─5503 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc --start-timeout 2m

6月 27 11:01:11 juaby.com docker[5451]: time="2016-06-27T11:01:11.111564104+08:00" level=info msg="New containerd process, pid: 5503\n"
6月 27 11:01:12 juaby.com docker[5451]: time="2016-06-27T11:01:12.686650122+08:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
6月 27 11:01:12 juaby.com docker[5451]: time="2016-06-27T11:01:12.702360431+08:00" level=info msg="Firewalld running: true"
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.028720270+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can...ed IP address"
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.287069806+08:00" level=info msg="Loading containers: start."
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.287127148+08:00" level=info msg="Loading containers: done."
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.287137808+08:00" level=info msg="Daemon has completed initialization"
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.287148785+08:00" level=info msg="Docker daemon" commit=b9f10c9 graphdriver=overlay version=1.11.2
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.307339714+08:00" level=info msg="API listen on /var/run/docker.sock"
6月 27 11:01:13 juaby.com systemd[1]: Started Docker Application Container Engine.
Hint: Some lines were ellipsized, use -l to show in full.
```
```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.2-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.61 GiB
Name: juaby.com
ID: YWHY:CGJF:MVTA:PKZJ:YYOU:52Q6:6Q36:DVY7:HZUP:IGS5:A2GC:BOE6
Docker Root Dir: /export/docker-data
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
```
$ sudo docker run -d -p 5000:5000 -v /export/docker-data/registry:/tmp/registry registry
docker: Error response from daemon: error creating overlay mount to /export/docker-data/overlay/698a7403b74400b667e1d0b5e25a54d38b69bebf22e405f0638bb44b708b702d-init/merged: invalid argument.
See 'docker run --help'.
```
```
sudo docker run -d -p 5000:5000 registry
docker: Error response from daemon: error creating overlay mount to /export/docker-data/overlay/cbdfb827e59e6c393f0eb24736168e4ea256eab9be80e665696492710e23354b-init/merged: invalid argument.
See 'docker run --help'.
```
```
$ sudo journalctl -u docker.service
-- Logs begin at 一 2016-06-27 10:53:37 CST, end at 一 2016-06-27 11:12:43 CST. --
6月 27 11:01:10 juaby.com systemd[1]: Starting Docker Application Container Engine...
6月 27 11:01:11 juaby.com docker[5451]: time="2016-06-27T11:01:11.111564104+08:00" level=info msg="New containerd process, pid: 5503\n"
6月 27 11:01:12 juaby.com docker[5451]: time="2016-06-27T11:01:12.686650122+08:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
6月 27 11:01:12 juaby.com docker[5451]: time="2016-06-27T11:01:12.702360431+08:00" level=info msg="Firewalld running: true"
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.028720270+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a 
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.287069806+08:00" level=info msg="Loading containers: start."
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.287127148+08:00" level=info msg="Loading containers: done."
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.287137808+08:00" level=info msg="Daemon has completed initialization"
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.287148785+08:00" level=info msg="Docker daemon" commit=b9f10c9 graphdriver=overlay version=1.11.2
6月 27 11:01:13 juaby.com docker[5451]: time="2016-06-27T11:01:13.307339714+08:00" level=info msg="API listen on /var/run/docker.sock"
6月 27 11:01:13 juaby.com systemd[1]: Started Docker Application Container Engine.
6月 27 11:10:22 juaby.com docker[5451]: time="2016-06-27T11:10:22.833506945+08:00" level=error msg="Clean up Error! Cannot destroy container f992d30f84f24c28657d8450d7506920d099ecbea2df507b84efcf34870bfd7a: No s
6月 27 11:10:22 juaby.com docker[5451]: time="2016-06-27T11:10:22.834928527+08:00" level=error msg="Handler for POST /v1.23/containers/create returned error: error creating overlay mount to /export/docker-data/o
6月 27 11:10:34 juaby.com docker[5451]: time="2016-06-27T11:10:34.816428047+08:00" level=error msg="Clean up Error! Cannot destroy container 5beb5e37769226256cad64fdc3721a7d3be1d7a9e5bcbe7dd1f88c98f6364c77: No s
6月 27 11:10:34 juaby.com docker[5451]: time="2016-06-27T11:10:34.816473750+08:00" level=error msg="Handler for POST /v1.23/containers/create returned error: error creating overlay mount to /export/docker-data/o
lines 1-16/16 (END)
```

**Comment by juaby** [comment] 2016-06-27 08:56
```
$ sudo sh check-config.sh 
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-4.6.2-1.el7.elrepo.x86_64 ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled (as module)
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
    Optional (for secure networks):
    - CONFIG_XFRM_ALGO: enabled
    - CONFIG_XFRM_USER: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000
```

**Comment by juaby** [comment] 2016-06-28 05:19
change xfs to ext4 and done

**Comment by thaJeztah** [comment] 2016-07-01 00:18
Looking at this issue and kernel version; could this be a duplicate of https://github.com/docker/docker/issues/22937? See this comment: https://github.com/docker/docker/issues/22937#issuecomment-229807934

**Comment by thaJeztah** [comment] 2016-07-01 00:21
I'll close this issue for now, as it looks like it's resolved for @juaby

**Closed by thaJeztah** 2016-07-01 00:21 UTC
Labels: area/storage/overlay, version/1.11

**Comment by AndresArboleda** [comment] 2017-10-17 23:55
You can change the storage driver in docker to avoid overlay fs.

As per docker documentation: "To set the storage driver, you can use the --storage-driver flag when starting the Docker daemon manually, or (recommended) set the option in the daemon.json file, which is located in /etc/docker/"

daemon.json content:

`{
  "storage-driver": "devicemapper"
}`

**Comment by bochen2014** [comment] 2017-12-05 12:38
I changed my docker storage location to a different drive , because I'm running out of space with my `/`;
I did that by udpating `/etc/docker/daemon.json` and add 
```json
{
   "graph":"/media/bochen2014/NTFSDrive/docker",
   "storage-drive":"overlay2"
}
```
I'm able to `docker pull busybox`, but when I run `docker run -it busyobx` I'm getting the `docker: Error response from daemon: error creating overlay mount to /media/bochen2014/NTFSDrive/docker`

is it because my external drive of NTFS format?

**Comment by cpuguy83** [comment] 2017-12-05 15:13
@bochen2014 Correct, NTFS is not supported with overlayfs, and in a future release (change is already in master), attempting to start docker with ntfs as the backing fs for overlay will be blocked.

**Comment by bochen2014** [comment] 2017-12-05 23:10
cool, that's what I thought. thanks for the updates

**Comment by whenyd** [comment] 2017-12-14 15:34
@bochen2014 @cpuguy83 This is also my problem, hope the release coming soon

**Comment by cpuguy83** [comment] 2017-12-14 15:58
@whenyd There is no release that will allow overlayfs to run on NTFS but rather will explicitly error out saying it's not supported.

**Comment by whenyd** [comment] 2017-12-14 16:05
To create a new mount point with enough space for docker maybe ok.


| |
阿克顿
|
|
邮箱：whenyd@126.com
|

签名由 网易邮箱大师 定制

On 12/15/2017 00:01, Brian Goff wrote:

@whenyd There is no release that will allow overlayfs to run on NTFS but rather will explicitly error out saying it's not supported.

**Comment by mairabay** [comment] 2018-01-17 16:20
>  Correct, NTFS is not supported with overlayfs

@cpuguy83  
So what do I do if I want to run docker, don't have enough space on my / and the only other available partition is NTFS??? Does this mean I can't use docker???

**Comment by thaJeztah** [comment] 2018-01-17 16:24
re-format that drive to use a different filesystem, or possibly devicemapper on loop devices could work (but definitely not recommended)

**Comment by mairabay** [comment] 2018-01-17 16:29
Yeah, I can't do that since I have to share that partition with files read and created on windows. Is there really no way to run docker in this scenario?

**Comment by cpuguy83** [comment] 2018-01-17 16:49
The `vfs` driver might work, but is not generally ideal since it will use significantly more space and be much slower at creating containers.

**Comment by mairabay** [comment] 2018-01-18 15:45
Thanks @cpuguy83 , that worked! It is very slow but I can live with that for now.

**Comment by gustavorochel** [comment] 2020-12-15 17:35
> You can change the storage driver in docker to avoid overlay fs.
> 
> As per docker documentation: "To set the storage driver, you can use the --storage-driver flag when starting the Docker daemon manually, or (recommended) set the option in the daemon.json file, which is located in /etc/docker/"
> 
> daemon.json content:
> 
> `{ "storage-driver": "devicemapper" }`

YOU ARE THE TRUE MASTER THANK YOU SO MUCH! WITH LOVE FROM BRASIL!

**Comment by leechor** [comment] 2021-08-18 02:08
maybe SELinux problem
