### ISSUE TITLE
Device files in privileged mode are not updated automatically

### ISSUE THREAD

**Issue by paralin** [docker/docker#15270] opened 2015-08-03 20:56 UTC
Introduction
=========

When you run a container in `--privileged` mode, the device files are created as expected in `/dev`. However, if udev adds / removes device files in the host system while the container is running, these changes do not propagate into the container. Thus, connecting a device which adds `ttyACM0` to /dev/ does not work with a container, because the container will not see the new device file.

Reproduce
========

1. Run a container with `--privileged`` mode. 
2. Connect a device that results in a new block device file
3. Check if the new block device file is visible in the container.

Or vise versa, any removed device files still exist within the container.

**Comment by ewindisch** [comment] 2015-08-03 21:02
This is by design. Options for users include bind-mounting /dev into a container or running udev inside the container.

**Comment by paralin** [comment] 2015-08-03 21:25
Why is this by design? It doesn't make too much sense to *snapshot* /dev/ at the start. I think if anything it is the way it is because it's more complex to make something that watches for changes in that tree.

**Comment by calavera** [comment] 2015-08-03 21:45
As @ewindisch mentions, this is intentionally caused by the way we create the rootfs for the container. If you want to get `/dev` updated when a new device is added to the host, you can mount it into the container with `--volume /dev:/dev`.

Thanks for your report. Closing since it's not an issue.

**Closed by calavera** 2015-08-03 21:45 UTC
