### ISSUE TITLE
[1.10] Pushing large layers results in a no such host error but works with 1.9.1 

### ISSUE THREAD

**Issue by nickjj** [docker/docker#20103] opened 2016-02-08 14:16 UTC
**Description of problem:**

I'm unable to push layers that aren't extremely tiny using 1.10. A 180mb layer failed for me 5 times in a row, and in all cases it got to about 80% finished before failing with:

_dial tcp: lookup XXX.dkr.ecr.us-east-1.amazonaws.com on 127.0.1.1:53: no such host_

`docker version`: 1.10

`docker info`: Unable to supply this in full because I already reverted 1.10 back to 1.9.1, you'll just have to trust me I was running 1.10. Here's the Storage Driver component:

```
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 208
 Dirperm1 Supported: false
```

`uname -a`: Linux oriath 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

`Environment details (AWS, VirtualBox, physical, etc.)`: Pushing from a VMWare based virtual machine (this is where `uname -a` was ran on) to an AWS ECR private repository.

`How reproducible`:

Unfortunately I can't share the image because it contains private code, but a typical Ruby on Rails application with a few gems should do the trick. I am pretty sure the 180mb layer was the point where it was trying to install a bunch of gems but it's hard to say for sure.

`Additional info`:

If I build the same exact image using Docker 1.9.1 then it pushes successfully. I also deleted the image from the private repo to test it multiple times and it worked 100% of the time.

---

It's also worth mentioning that my workstation is always a bit weird when I'm maxing out my bandwidth. My internet connection is about 30mb down and 5mb up.

During the push (or any other activity where I saturate my upstream), my network connection tends to be nearly unusable for any other tasks on this machine.

For example, during this push, I couldn't visit a website without it timing out. Even my IRC client will timeout sometimes. I understand this isn't related to Docker and this is the only workstation I've ever used in my entire life that this happens on, but I wanted to add this because maybe 1.10 needs to be a little more robust when it comes to handling this because 1.9.1 works flawlessly.

**Comment by mavenugo** [comment] 2016-02-08 16:23
@thaJeztah @icecrime replaced the tag to `networking` as the issue seems to be DNS related : `127.0.1.1:53: no such host`.

We will try and get more information on this before associating it to another tag based on our investigation.

**Comment by mavenugo** [comment] 2016-02-08 16:29
@nickjj Since the lookup happens in `127.0.1.1:53`, can you please share with us your DNS configurations ? 

* ` cat /etc/resolv.conf` in the host
* any docker specific `--dns` configuration ?
* do you run any local dns server which proxies the request to external DNS servers ? If yes, some details on that will help.
* is this a dind environment ?

**Comment by nickjj** [comment] 2016-02-08 16:37
@mavenugo,

The workstation (host)'s `resolv.conf` file is:

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
search home
```

No specific `--dns` configuration. My Docker client has the stock settings too.

Local DNS server? Nope, I'm not running one.

---

I'm not quite sure what you mean by dind environment, but Google hints this might be running Docker inside of Docker. Nope, I'm not doing this.

My workstation's set up is:

- Main OS: Windows 8.1
- Running VMWare to run a graphical xubuntu virtual machine (uname info is listed above)
- Docker is running natively inside of this xubuntu instance

**Comment by mavenugo** [comment] 2016-02-08 16:55
@icecrime based on the above responses, it doesnt seem to be docker related.
(The failure is happening in `push`, which uses the native host networking stack).

@sanimej earlier suggested that there has been some DNS specific changes in golang 1.5.x that could be impacting here.

**Comment by nickjj** [comment] 2016-02-08 17:19
@mavenugo It might not be, but 1.9.1 handles pushing perfectly well while 1.10 does not.

**Comment by mavenugo** [comment] 2016-02-08 17:36
@nickjj PTAL https://github.com/docker/docker/issues/20086#issuecomment-181289558 @sanimej will be able to shed light on that.
The Go version used to build docker 1.10 is go1.5.3, whereas 1.9 is go1.4.3. 

Since, `docker push` uses the host networking stack, it is not related to docker networking stack per-se (which operates inside the container launched using the docker daemon). 

Since the nameserver points to 127.0.1.1, there must be some DNS server running locally. am curious to know if a service like `dnsmasq` is running in your host and if yes, what are the recursive DNS servers that are used by `dnsmasq` (or) any other DNS proxy server ?

**Comment by nickjj** [comment] 2016-02-08 17:42
@mavenugo Thanks. When you wrote that initially it sounded like maybe you were going to drop the ticket because it was something related on my end.

`dnsmasq` is running, confirmed with `ps aux | grep dnsmasq`:

```
nobody     2621  0.0  0.0  38212  1436 ?        S    Jan28   0:56 /usr/sbin/dnsmasq --no-resolv --keep-in-foreground --no-hosts --bind-interfaces --pid-file=/run/sendsigs.omit.d/network-manager.dnsmasq.pid --listen-address=127.0.1.1 --conf-file=/var/run/NetworkManager/dnsmasq.conf --cache-size=0 --proxy-dnssec --enable-dbus=org.freedesktop.NetworkManager.dnsmasq --conf-dir=/etc/NetworkManager/dnsmasq.d
```

`/etc/NetworkManager/dnsmasq.d` is an empty directory.
`/var/run/NetworkManager/dnsmasq.conf` is an empty file.

I'm 99.9% sure this isn't something I ever configured manually.

**Comment by sanimej** [comment] 2016-02-08 18:28
@nickjj Can you please confirm pushing smaller (or tiny) layer works ok ? If it does it has to go through the same DNS resolutions.

When pushing large images you said you are not able to access other websites. So if the network bandwidth or cpu usage is getting maxed out for other reasons it can result in DNS failures too. But that is not the root cause for the large image push failing.

**Comment by nickjj** [comment] 2016-02-08 18:33
@sanimej Smaller layers work fine. It's only when it reached that 180mb layer that it became an issue. Tens of megabytes seems ok.

**Comment by mavenugo** [comment] 2016-02-08 18:40
@nickjj thanks for the confirmation. this doesnt seem to be a name resolution issue. It could be related to pushing larger layers. tagging it appropriately.

**Comment by aaronlehmann** [comment] 2016-02-08 19:59
Were you running the final release of 1.10.0 or a -rc version? Some of the `-rc` versions were prone to timeouts when pushing large layers.

**Comment by nickjj** [comment] 2016-02-08 20:00
@aaronlehmann I was using http://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.10.0-0~trusty_amd64.deb

**Comment by tiborvass** [comment] 2016-02-10 01:03
@nickjj would be great if you could provide a reproducible case with an image from the hub or a dockerfile.

**Comment by nickjj** [comment] 2016-02-10 11:48
The problem with reproducing it is it's going to vary between systems.

For example, if I upload at 500kb/s and you upload at 1.5mb/s then you'll never be able to reproduce this with a 180mb layer because it will complete before timing out.

Since I am able to reproduce this 5/5 times and it always times out at the same point then it seems plausible that the issue might be related to time. Maybe it happens after 90 seconds or something (I didn't time it exactly).

I recommend building an image where you stuff one of the layers with 5GB+ or some amount that won't upload quickly when you push it.

**Comment by aaronlehmann** [comment] 2016-02-10 18:00
The main difference between 1.9 and 1.10 that comes to mind here is that 1.10 uploads multiple layers in parallel, but 1.9 only uploads one at a time. Since your workstation apparently suffers connectivity issues with heavy upstream bandwidth usage, perhaps one of the layer uploads gets going, and this bandwidth usage prevents other uploads from getting started.

1.10 will retry these individual uploads a few times before failing the push. It could be that your network situation causes all of these retries to fail, which would take about 90 seconds. Then the push would fail.

When you tried this push with 1.10, did you see messages like "Retrying in 5 seconds" for some layers?

**Comment by nickjj** [comment] 2016-02-10 18:07
@aaronlehmann In the specific image I was pushing, there were 3 or 4 "Retrying in 5 seconds" messages above the larger layer. They kept retrying on their own, and it seemed like the Docker client tried to back off and add more delay in between each attempt.

Eventually the large layer fails with the error reported in the issue.

**Comment by aaronlehmann** [comment] 2016-02-10 21:07
It sounds like DNS resolution doesn't succeed while an upload is running, because of the extreme packet loss on your network during heavy upload traffic. Since the whole push is failing, the DNS lookup is failing repeatedly over the course of several retries (in both the DNS client and the push logic).

I don't think this is a Docker bug. Docker fails to look up a hostname, it retries repeatedly over the course of about 90 seconds, and eventually it gives up. It seems like the underlying issue is your network problem.

So I'm closing this issue for now, but please reopen it if you can reproduce the issue with a stable network connection.

**Closed by aaronlehmann** 2016-02-10 21:07 UTC
Labels: group/distribution, priority/P2, status/cannot-reproduce

**Comment by nickjj** [comment] 2016-02-10 21:11
@aaronlehmann My connection is stable. I've uploaded dozens of gigs without it timing out using other tools that aren't Docker. In fact, I just uploaded 3 gigs last night as 1 big zip file with no issues.

This is a serious set back for me because I'm a content creator for Docker and I can't use anything beyond Docker 1.9.1 in my courses since I can't even successfully push a small Rails app with 1.10+.

**Comment by aaronlehmann** [comment] 2016-02-10 21:46
@nickjj: I sympathize, but I don't know what change we could make to Docker to work around this, other than going back to only uploading one layer at a time, which was a big performance bottleneck.

While you do a push with Docker 1.10, does doing a DNS lookup from a different tool (i.e. `host docker.io` from the command line) work, or does it time out? Because if DNS requests are consistently timing out while the connection is under load, I'm just not sure what Docker can do about it.

**Comment by nickjj** [comment] 2016-02-10 22:05
Wouldn't just raising the time-out on the retry fix it? This way as soon as it finishes the big layer, the others will resume. This wouldn't be a real fix, but if there were a 10 minute time-out then there's a good chance that will never be reached for a majority of people.

I haven't re-installed 1.10 but I'll say this. If I upload a large file to let's say Google Drive and run `host docker.io` it will time-out.

```
nick@oriath:~ ⚡ host docker.io
;; connection timed out; no servers could be reached
;; connection timed out; no servers could be reached
```

Here's the output of running it without uploading anything:

```
nick@oriath:~ ⚡ host docker.io
docker.io has address 54.164.250.255
docker.io has address 52.0.10.162
docker.io has address 54.152.78.181
docker.io mail is handled by 10 aspmx.l.google.com.
docker.io mail is handled by 20 alt1.aspmx.l.google.com.
docker.io mail is handled by 30 aspmx2.googlemail.com.
docker.io mail is handled by 30 aspmx3.googlemail.com.
docker.io mail is handled by 30 aspmx4.googlemail.com.
docker.io mail is handled by 30 aspmx5.googlemail.com.
```

If I use a bandwidth shaping tool to limit FireFox's upload to 400kb/s (about 80% of my total upload speed) then `host docker.io` works but it's pretty laggy.

**Comment by nickjj** [comment] 2016-02-17 23:29
For the record, I upgraded to 1.10.1 and with bandwidth shaping tools in place things upload successfully.

**Comment by thaJeztah** [comment] 2016-02-17 23:31
Thanks @nickjj, good to hear you managed to get it working

**Comment by hookenz** [comment] 2016-02-18 20:35
I've been having the exact same issue but with the docker login to an Amazon ECS registry endpoint and Ubuntu 14.04.  If I changed /etc/resolv.conf from:

    `nameserver 127.0.1.1`

to

   `nameserver 192.168.0.1`

It uses my local router directly, rather the the dnsmasq cache that Ubuntu desktop uses by default.  However, the issue remains.  

Next I tried:

    `nameserver 8.8.8.8`

Then instead of 127.0.1.1:53: no such host or 192.168.0.1:53 no such host errors, I now get
`Login succeeded.`

However, pushing fails at the end with unexpected EOF.  This is with docker 1.10.1
