### ISSUE TITLE
Xenial repo doesn't contain docker-engine

### ISSUE THREAD

**Issue by nazar-pc** [docker/docker#22182] opened 2016-04-20 04:16 UTC
Ubuntu 16.04 is going to be released soon.
There is https://apt.dockerproject.org/repo/dists/ubuntu-xenial/ already, but package is not there.

**Comment by HackToday** [comment] 2016-04-20 04:19
Same issue as

https://github.com/docker/docker/issues/22132

**Comment by nazar-pc** [comment] 2016-04-20 04:26
Apparently no. Looks like it is what others also encounter in comments in #21461

**Comment by HackToday** [comment] 2016-04-20 04:39
@nazar-pc  my comment about issue is that link same issue #21461 as #22132 opened for that for same reason

**Comment by thaJeztah** [comment] 2016-04-20 13:26
Yes, I think @tiborvass was already looking into this

**Comment by Someguy123** [comment] 2016-04-20 18:33
Can confirm this issue.

Xenial is coming out in ~24 hours, or so #ubuntu+1 IRC tells me, and there's still no packages.

**Comment by killarny** [comment] 2016-04-21 22:14
Chiming in.. I'm seeing this as well. The package doesn't appear to be properly listed for apt to find, but I am able to download the deb manually and install it:

```bash
$ wget -q https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.11.0-0~xenial_amd64.deb
$ sudo dpkg -i docker-engine_1.11.0-0-xenial_amd64.deb 
Selecting previously unselected package docker-engine.
(Reading database ... 169961 files and directories currently installed.)
Preparing to unpack docker-engine_1.11.0-0-xenial_amd64.deb ...
Unpacking docker-engine (1.11.0-0~xenial) ...
Setting up docker-engine (1.11.0-0~xenial) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for ureadahead (0.100.0-19) ...
ureadahead will be reprofiled on next reboot
Processing triggers for systemd (229-4ubuntu4) ...
$ docker --version
Docker version 1.11.0, build 4dc5990
```

**Comment by tiborvass** [comment] 2016-04-21 22:36
@nazar-pc @killarny @ajsb85 @jaytheking @danbeaulieu @thuandt @eliezedeck @Someguy123 @Mellnik @icewheel 

Please try installing docker on xenial now, it should work.

**Comment by vshvedov** [comment] 2016-04-21 22:38
@tiborvass xenial, amd64 - it works now :+1:

**Comment by tiborvass** [comment] 2016-04-21 22:40
Thanks, I have other reports as well that it seems to work now, so i'm going to close this. Feel free to comment if you see something weird.

**Closed by tiborvass** 2016-04-21 22:40 UTC
Labels: kind/bug, priority/P2

**Comment by bhaskarpalit** [comment] 2016-05-08 18:51
xenial, i386 doesn't work

**Comment by bhaskarpalit** [comment] 2016-05-08 18:55
I tried xenial i386 main. It does't work. 
sudo apt-get update
sudo apt-get install docker-engine
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker-engine

**Comment by thaJeztah** [comment] 2016-05-08 21:36
@bhaskarpalit that's expected; docker requires a 64 bit kernel to run, only the client is able to run on 32 bit. See https://docs.docker.com/engine/installation/linux/ubuntulinux/#prerequisites

**Comment by hwinkel** [comment] 2016-05-12 20:15
is there any option to install a particular version of docker. as far I know rancher does not support version 1.11 (yet)

**Comment by thaJeztah** [comment] 2016-05-12 20:48
@hwinkel if you follow the manual procedure, you can use `apt-get install docker-engine=<package-version>`

For example

    apt-get install docker-engine=1.10.3-0~trusty


However, for Xenial, there's no 1.10, so you may have to either run on Ubuntu 14.04 if you want a LTS version, or use the "wily" repository, which works for xenial

**Comment by Arcrammer** [comment] 2016-06-05 14:15
The guide says it's available for Xenial but it's not so shouldn't it be removed from the guide? Has this issue been resolved yet? I just tried a fresh installation and still nothing.

![Misleading Guide Screenie](http://s33.postimg.org/fjkbjkv0d/Screen_Shot_2016_06_05_at_10_12_00.png "Why Docker!? WHYYYYYYYYY???")

**Comment by thaJeztah** [comment] 2016-06-05 14:44
@Arcrammer it's available; http://apt.dockerproject.org/repo/dists/ubuntu-xenial/. Did you run into issues when installing? Are you perhaps running a 32-bit version or different architecture?

**Comment by Arcrammer** [comment] 2016-06-05 14:51
@thaJeztah Yes, it's 32 bit —_______—.

Sorry about that. I could have sworn I installed 64 bit. Thank you!

**Comment by gfauredumont** [comment] 2016-06-07 15:20
Hi,

Sorry to bother here but, following the same steps as @Arcrammer, I cannot `apt-get update` from the docker source, I get
`Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/InRelease  Connection timed out after 120000 milliseconds`
each time I try it (even if all other sources work great).
Any `apt-cache policy docker-engine` returns
`N: Unable to locate package docker-engine`

I'm using a fresh new Ubuntu Xenial on x86_64...

Any suggestion ?

**Comment by thaJeztah** [comment] 2016-06-07 15:36
@gfauredumont we don't have an InRelease file in the main repository; 
https://apt.dockerproject.org/repo/dists/ubuntu-xenial/,
https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/, so it's strange it keeps trying to fetch that. Let me try with a fresh machine

**Comment by gfauredumont** [comment] 2016-06-07 15:40
As instructed in th docker doc, my docker.list file contains 
`deb https://apt.dockerproject.org/repo ubuntu-xenial main`

**Comment by thaJeztah** [comment] 2016-06-07 15:43
Hm, strange, I'm not able to reproduce;

```
mkdir -p /etc/apt/sources.list.d
echo deb [arch=amd64] https://apt.dockerproject.org/repo ubuntu-xenial main > /etc/apt/sources.list.d/docker.list
apt-get update && apt-get install -y -q docker-engine
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Ign:3 https://apt.dockerproject.org/repo ubuntu-xenial InRelease
Get:4 https://apt.dockerproject.org/repo ubuntu-xenial Release [19.7 kB]
Hit:2 http://ams2.mirrors.digitalocean.com/ubuntu xenial InRelease
Hit:5 http://ams2.mirrors.digitalocean.com/ubuntu xenial-updates InRelease
Get:6 https://apt.dockerproject.org/repo ubuntu-xenial Release.gpg [801 B]
Hit:7 http://ams2.mirrors.digitalocean.com/ubuntu xenial-backports InRelease
Get:8 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 Packages [1,719 B]
Fetched 22.2 kB in 0s (38.2 kB/s)
Reading package lists... Done
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  aufs-tools cgroupfs-mount libltdl7
Suggested packages:
  mountall
The following NEW packages will be installed:
  aufs-tools cgroupfs-mount docker-engine libltdl7
0 upgraded, 4 newly installed, 0 to remove and 37 not upgraded.
Need to get 14.6 MB of archives.
After this operation, 73.8 MB of additional disk space will be used.
Get:2 https://apt.dockerproject.org/repo ubuntu-xenial/main amd64 docker-engine amd64 1.11.2-0~xenial [14.5 MB]
Get:1 http://ams2.mirrors.digitalocean.com/ubuntu xenial/universe amd64 aufs-tools amd64 1:3.2+20130722-1.1ubuntu1 [92.9 kB]
Get:3 http://ams2.mirrors.digitalocean.com/ubuntu xenial/universe amd64 cgroupfs-mount all 1.2 [4,970 B]
Get:4 http://ams2.mirrors.digitalocean.com/ubuntu xenial/main amd64 libltdl7 amd64 2.4.6-0.1 [38.3 kB]
Fetched 14.6 MB in 0s (25.4 MB/s)
```

**Comment by gfauredumont** [comment] 2016-06-07 15:52
ok, just to be sure, I added the `[arch=amd64]` in my source file but no change.
It seems that your distro switches from InRelease to Release after ignoring the latter but in my case it just  timeouts...
Would you know how this behavior is configured ?

**Comment by thaJeztah** [comment] 2016-06-07 16:01
No, I would have to search for that as well, but I'm interested to hear if you found, so that we can see if our installation instructions need to be updated; it may be a configuration indeed (something like "always use `InRelease`, don't skip").

**Comment by gfauredumont** [comment] 2016-06-07 16:09
OK, I'll post this issue on StackExchange
Thanks for trying ;)
(As I'm way over my knowledge on this matter, if you have any significant information, please share ;)  )

**Comment by gfauredumont** [comment] 2016-06-08 16:05
Hi again,

I've created a [question on AskUbuntu](http://askubuntu.com/questions/784094/skipping-the-inrelease-step-when-apt-get-update-and-go-directly-to-release) but I'm not sure I've indicated all the necessary information.

**If anyone has a clue or even an idea so I could dig on, please answer here or as a comment/answer to [my question](http://askubuntu.com/questions/784094/skipping-the-inrelease-step-when-apt-get-update-and-go-directly-to-release)...**

**Comment by gfauredumont** [comment] 2016-06-08 16:22
(cross)[asked it on ServerFault](http://serverfault.com/questions/782737/skipping-the-inrelease-step-when-apt-get-update-and-go-directly-to-release), just to catch any ideas...

**Comment by gfauredumont** [comment] 2016-06-09 15:48
OK, so turns out that some updates are made through http (all official Ubuntu packages) when other use https (Docker for instance).
My firewall wasn't configured to accept port 443 requests (I could test that out with `curl`).
I've modified my IpTables configuration and now `apt-get update` goes through Docker's server without problem !

**Comment by HackToday** [comment] 2016-06-11 00:28
Glad to know  it works. 😄

**Comment by suwey** [comment] 2016-11-23 00:54
@gfauredumont I encounted a similar problem today: 

`https://apt.dockerproject.org/repo ubuntu-xenial Release
  Connection timed out after 120001 milliseconds`

And I tested with curl and it's ok: 

`curl https://apt.dockerproject.org/repo/dists/ubuntu-xenial/Release`

Now `apt update` will never try `https://apt.dockerproject.org/repo ubuntu-xenial Release` even if I delete and create`/etc/apt/source.list.d/docker.list` again, do yout know how can I enable it?

**Comment by vimagick** [comment] 2017-01-12 11:12
@suwey Please delete `/etc/apt/apt.conf`. I guess you're using aliyun vps.

**Comment by gfauredumont** [comment] 2017-01-12 14:46
@vimagick, I woundn't recommend that, please see my answer on [ServerFault](http://serverfault.com/questions/782737/skipping-the-inrelease-step-when-apt-get-update-and-go-directly-to-release/825817#comment1053326_825817)
@suwey Sorry, I must have missed the notification of your question.
Unfortunately, I'm not a good sysadmin so I cannot answer you. I would recommend asking on ServerFault as I did... ;)

**Comment by suwey** [comment] 2017-01-13 02:39
@vimagick @gfauredumont thank you, the situation is still the same as I described in my question, but I found out that docker update is still work fine, and I will try to ask about it on ServerFault because I am curious about it.

**Comment by jeff-kilbride** [comment] 2017-01-20 06:59
I'm also having issues with a brand new 16.04 installation on AWS. I followed the instructions on the [Get Docker for Ubuntu page](https://docs.docker.com/engine/installation/linux/ubuntu/):
```
$ sudo apt-get install apt-transport-https \
>                        ca-certificates
Reading package lists... Done
Building dependency tree
Reading state information... Done
ca-certificates is already the newest version (20160104ubuntu1).
apt-transport-https is already the newest version (1.2.18).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ curl -s http://yum.dockerproject.org/gpg | sudo apt-key add
OK

$ apt-key fingerprint 58118E89F3A912897C070ADBF76221572C52609D
pub   4096R/2C52609D 2015-07-14
      Key fingerprint = 5811 8E89 F3A9 1289 7C07  0ADB F762 2157 2C52 609D
uid                  Docker Release Tool (releasedocker) <docker@docker.com>

$ sudo add-apt-repository \
>        "deb https://apt.dockerproject.org/repo/pool/ \
>        $(lsb_release -cs) \
>        main"
```
But I'm getting an error using `apt-get update`:
```
$ apt-get update
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Ign:5 https://apt.dockerproject.org/repo/pool xenial InRelease
Ign:6 https://apt.dockerproject.org/repo/pool xenial Release
Ign:7 https://apt.dockerproject.org/repo/pool xenial/main amd64 Packages
Ign:8 https://apt.dockerproject.org/repo/pool xenial/main all Packages
Ign:9 https://apt.dockerproject.org/repo/pool xenial/main Translation-en_US
Ign:10 https://apt.dockerproject.org/repo/pool xenial/main Translation-en
Ign:7 https://apt.dockerproject.org/repo/pool xenial/main amd64 Packages
Ign:8 https://apt.dockerproject.org/repo/pool xenial/main all Packages
Ign:9 https://apt.dockerproject.org/repo/pool xenial/main Translation-en_US
Ign:10 https://apt.dockerproject.org/repo/pool xenial/main Translation-en
Ign:7 https://apt.dockerproject.org/repo/pool xenial/main amd64 Packages
Ign:8 https://apt.dockerproject.org/repo/pool xenial/main all Packages
Ign:9 https://apt.dockerproject.org/repo/pool xenial/main Translation-en_US
Ign:10 https://apt.dockerproject.org/repo/pool xenial/main Translation-en
Ign:7 https://apt.dockerproject.org/repo/pool xenial/main amd64 Packages
Ign:8 https://apt.dockerproject.org/repo/pool xenial/main all Packages
Ign:9 https://apt.dockerproject.org/repo/pool xenial/main Translation-en_US
Ign:10 https://apt.dockerproject.org/repo/pool xenial/main Translation-en
Ign:7 https://apt.dockerproject.org/repo/pool xenial/main amd64 Packages
Ign:8 https://apt.dockerproject.org/repo/pool xenial/main all Packages
Ign:9 https://apt.dockerproject.org/repo/pool xenial/main Translation-en_US
Ign:10 https://apt.dockerproject.org/repo/pool xenial/main Translation-en
Err:7 https://apt.dockerproject.org/repo/pool xenial/main amd64 Packages
  403  Forbidden
Ign:8 https://apt.dockerproject.org/repo/pool xenial/main all Packages
Ign:9 https://apt.dockerproject.org/repo/pool xenial/main Translation-en_US
Ign:10 https://apt.dockerproject.org/repo/pool xenial/main Translation-en
Fetched 102 kB in 1s (54.1 kB/s)
Reading package lists... Done
W: The repository 'https://apt.dockerproject.org/repo/pool xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt.dockerproject.org/repo/pool/dists/xenial/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
And I can't install `docker-engine`:
```
$ apt-get install -y docker-engine
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package docker-engine
```
Any help would be appreciated! I have previously installed `docker-engine` on  14.04 on AWS and have been running the beta Mac native docker for about a year locally. First time trying to install on 16.04...

**Comment by thaJeztah** [comment] 2017-01-20 08:23
Thanks for reporting, the installation docs were updated just before the release, and it looks like an error may have slipped in; I'll open a pull request to fix this

**Comment by Lawri-van-Buel** [comment] 2017-01-20 16:48
I can Confirm that @jeff-kilbride's solution works as a hot-fix

**Comment by gaboesquivel** [comment] 2017-01-20 20:57
`deb https://apt.dockerproject.org/repo/ ubuntu-xenial main` works

**Comment by thaJeztah** [comment] 2017-01-20 23:22
docs should be fixed now 👍

**Comment by jschill** [comment] 2017-01-29 20:40
Should this work now?

> sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Hit:5 https://apt.dockerproject.org/repo ubuntu-xenial InRelease
Fetched 306 kB in 1s (252 kB/s)
Reading package lists... Done

and then..

> sudo apt-get install docker-engine
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package docker-engine

and...

> apt-cache policy docker-engine
N: Unable to locate package docker-engine

I'm on Ubuntu 16.04.1 LTS

**Comment by masbenx** [comment] 2017-03-04 16:14
it's error on ubuntu 16.04

> W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/InRelease  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

> E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by thaJeztah** [comment] 2017-03-04 17:17
@masbenx what does your `/etc/apt/sources.list` and `/etc/apt/source.list.d/docker.list` contain? Also, what kernel, and architecture are you running on?

**Comment by masbenx** [comment] 2017-03-06 04:30
@thaJeztah 

this is my docker source on  /etc/apt/source.list 

> deb https://apt.dockerproject.org/repo ubuntu-xenial main
deb-src https://apt.dockerproject.org/repo ubuntu-xenial main

and there is empty file on /etc/apt/source.list.d/docker.list

I'am using Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment] 2017-03-06 06:52
@masbenx can you remove the line for `deb-src` and try again? Looks like it's trying to install src packages

**Comment by thaJeztah** [comment] 2017-03-06 06:54
@masbenx also; that kernel is ancient and looks to be the kernel for ubuntu 12.04. Docker requires kernel 3.10 as minimum; and ubuntu 16.04 ships with kernel 4.4, so you need to have that updated as well

**Comment by masbenx** [comment] 2017-03-06 07:32
@thaJeztah thanks alot, it resolve after kernel updated.

**Comment by thaJeztah** [comment] 2017-03-06 11:55
Great!

**Comment by zbam** [comment] 2017-04-09 13:37
Well it's my turn having this issue on Xenial too.
My /etc/apt/sources.list looks like this:
```
deb http://archive.ubuntu.com/ubuntu xenial main universe
deb http://archive.ubuntu.com/ubuntu xenial-updates main universe
deb https://apt.dockerproject.org/repo ubuntu-xenial main
# deb-src https://apt.dockerproject.org/repo ubuntu-xenial main
# deb-src https://apt.dockerproject.org/repo ubuntu-xenial main
deb http://archive.ubuntu.com/ubuntu xenial-security main universe
```
uname -a spits out this:
`Linux scw-5de468 4.4.38-std-1 #1 SMP Mon Dec 12 10:45:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Any idea on this welcome !
