### ISSUE TITLE
ENH: List `docker build` context

### ISSUE THREAD

**Issue by jakirkham** [docker/docker#16056] opened 2015-09-03 18:33 UTC
It would be good when trying to improve the performance of a build to be able to see what is included in the context. A simple listing of the directories/files would be sufficient. This way we could see if we missed something in `.dockerignore` and add it or see that we added something we didn't expect.

**Comment by jakirkham** [comment] 2015-09-03 18:34
Not a bug so ignore bug info. Also, already hunted through the issue tracker.

**Comment by Pensu** [comment] 2015-09-07 06:29
@jakirkham Have a look at #14298. They are working on getting the builder out of engine, should be up by 1.9.

**Comment by jakirkham** [comment] 2015-10-22 15:23
@Pensu, I have heard of this before. Is that still planned for 1.9? It looks like there is already a release candidate for 1.9.0. Or is this meant for another release in 1.9.x? Is there a roadmap for when this change is planned?

**Comment by thaJeztah** [comment] 2015-10-23 03:10
Breaking out the builder will not be in 1.9, but it's actively being worked on

**Comment by LK4D4** [comment] 2016-09-13 23:53
Builder is still here. But! I think this can be achieved with `tree`, `find` or `ls` in Dockerfile. Given that context can be millions of files I'm not sure that it worth to implement this.
I'm closing this because of lack of interest from the community. Feel free to open new proposal if you'll find more cases.

**Closed by LK4D4** 2016-09-13 23:53 UTC
Labels: area/builder, kind/enhancement

**Comment by MichaelJCole** [comment] 2016-11-16 16:04
How can I ls the context?

```
RUN ls 
```

Shows the contents of the container, not the context.  I'm debugging a COPY that's not working and this is really annoying.

**Comment by LK4D4** [comment] 2016-11-16 16:07
@MichaelJCole just `COPY . ` somewhere. Sounds like reasonable for debugging.

**Comment by thaJeztah** [comment] 2016-11-16 16:08
@MichaelJCole There's no "direct" way to see what's sent as build context, other than (e.g.) doing `COPY . /build-context` and seeing what's in there. It's better to open a new issue with more information, information about your setup (`docker version`, `docker info`, etc.), and steps to reproduce (a minimal `Dockerfile`, possibly the `.dockerignore` file you're using)

**Comment by labianchin** [comment] 2016-11-22 09:23
Another option is: `ag --path-to-ignore .dockerignore --files-with-matches`.

But some `**` patterns do not work properly: https://github.com/ggreer/the_silver_searcher/wiki/Advanced-Usage

**Comment by mbana** [comment] 2018-09-25 09:53
@labianchin thanks.

**Comment by letmaik** [comment] 2019-07-10 21:01
I found `rg -uuu --ignore-file .dockerignore --files --sort path .` more useful. This uses [ripgrep](https://github.com/BurntSushi/ripgrep).
