### ISSUE TITLE
docker cve

### ISSUE THREAD

**Issue by keloyang** [docker/docker#17292] opened 2015-10-23 03:25 UTC
where can I find a way to search docker cve and the solutions ?

**Comment by thaJeztah** [comment] 2015-10-23 06:39
Which CVE's were resolved in a release can be found in the release notes (e.g. https://github.com/docker/docker/releases/tag/v1.8.3)

the solutions can be found in the commit history of the branch, for example: https://github.com/docker/docker/commits/v1.8.3

@keloyang thanks for asking! I'm going to close this issue because this is not a bug or a feature request, but feel free to comment here after I've closed

**Closed by thaJeztah** 2015-10-23 06:39 UTC

**Comment by keloyang** [comment] 2015-10-23 06:48
@thaJeztah Thank you very much.

**Comment by thaJeztah** [comment] 2015-10-23 06:57
@keloyang if you need more information, or your company requires early access to security notices, feel free to get in contact via security@docker.com to ask what the options are
