### ISSUE TITLE
docker push always fails with "push my-repo/my-app is already in progress"

### ISSUE THREAD

**Issue by dirkmc** [docker/docker#5113] opened 2014-04-09 13:29 UTC
After doing a push and then pressing ctrl-c before it had completed I got into this state:
docker push "my-repo/my-app"
2014/04/09 09:19:26 Error: push my-repo/my-app is already in progress
It was still in the same state a day later.
The workaround was to restart the docker server.

**Comment by henriquemelhado** [comment] 2015-01-12 14:12
@Vad1mo +1

**Comment by omribahumi** [comment] 2015-01-27 11:19
1.4.1, still there.

**Comment by dsjoerg** [comment] 2015-02-11 18:58
+1

**Comment by futurechan** [comment] 2015-02-19 15:25
:+1:

**Comment by termie** [comment] 2015-03-10 21:00
+1

**Comment by mcandre** [comment] 2015-03-19 23:40
@orcaman Same fix for me on Mac: `boot2docker restart`.

**Comment by shimont** [comment] 2015-03-30 08:43
+1

**Comment by mathieuruellan** [comment] 2015-03-30 08:46
+1. I have jenkins build that are pushing in a private repo for a test team, and that's a major issue.

**Comment by markeijsermans** [comment] 2015-03-31 03:10
:+1: Restarting the daemon for a stalled push (and killing all running containers) is an unacceptable workaround in many situations. For my setup of Jenkins on Mesos building containers, it's a big issue as well. I have no idea what other containers are running on the slave. 

A bit off topic, but perhaps this highlights the larger issue of when the daemon itself gets into a pathological state. Checkpointing would be nice http://criu.org/

**Comment by cdancy** [comment] 2015-04-03 16:49
+1. We've got Bamboo builds pushing to a registry and can't have more than 1 push happening at any given time.

**Comment by alexanderververis** [comment] 2015-04-06 06:22
+1

**Comment by tj** [comment] 2015-04-07 00:46
derp, just ^C'd one by accident and now I get this haha

**Comment by FossiFoo** [comment] 2015-04-09 10:18
+1

**Comment by colegatron** [comment] 2015-04-22 09:01
+1. Docker 1.6.0. Error stills there at least if you cancel the push process. Waiting a couple minutes it seems to free the lock. 
If pushes were fast I do not care about the 1 push-at-a-time limit, but it takes soooooo long to push.

**Comment by joelpresence** [comment] 2015-04-23 00:55
I am seeing this error when pushing to DockerHub itself.  My upload speed is a rock solid 20 Mbps.  The issue is not my network, the issue is DockerHub.  Why is DockerHub so slow?  We're paying for private repos ...

`docker restart` failed on OS X but `docker stop` then `docker start` allowed the push to finally succeed.

**Comment by bonzofenix** [comment] 2015-05-07 01:01
`boot2docker restart` on my dev environment worked for me.

**Comment by ohadpartuck** [comment] 2015-05-10 07:18
@bonzofenix  worked for me too, thanks.

**Comment by wzpan** [comment] 2015-06-02 01:02
@orcaman :+1:

**Comment by kumavis** [comment] 2015-06-16 01:49
`boot2docker restart`

**Comment by cage1016** [comment] 2015-07-14 05:22
@orcaman :+1:
 `boot2docker restart` save me

**Comment by KostyaSha** [comment] 2015-08-25 18:36
+1

**Comment by juandiegoh** [comment] 2015-08-26 12:02
```shell docker-machine restart default ``` worked for me in Max OS X

**Comment by harishkashyap** [comment] 2015-08-27 15:12
boot2docker restart worked for me.

**Comment by oryband** [comment] 2015-09-03 13:11
:+1: this is a big issue

**Comment by cpuguy83** [comment] 2015-09-03 13:26
So this is most likely fixed on master.
There have been lots of fixes under the hood to how pulls are handled. In addition if you do `ctrl-c` out of a pull you can now run `docker pull` again to see the actual status of the pull that is in progress.

I will keep this open for now because there can be many things causing this issue that are difficult to pin-point.

ping @aaronlehmann who has been doing a lot of this work on the pull code.

**Comment by mathieuruellan** [comment] 2015-09-03 13:41
I've not anymore this bug since a few months (version 1.6 debian packages).

**Comment by apaatsio** [comment] 2015-10-27 08:49
I had this problem with docker 1.8.3 on linux. `docker restart {containerId}` helped.

**Comment by mateusnava** [comment] 2015-10-27 13:57
**service docker restart** +1

**Comment by sunocean** [comment] 2015-11-04 09:29
docker-machine restart default worked for me in Max OS X+1
@juandiegoh thank you very much.

**Comment by j-mcnally** [comment] 2015-11-17 20:18
is there a way to clear the lock without rebooting. Taking all the containers down to handle this is a major pain.

**Comment by neildeng** [comment] 2015-11-27 13:30
<code>systemctl restart docker</code> worked for me in CentOS7

**Comment by j-mcnally** [comment] 2015-11-27 17:48
@neildeng that has the unfortunate side effect of restarting docker and all running containers.........

**Comment by cpuguy83** [comment] 2015-11-27 18:00
This should be fixed in 1.9

**Comment by thaJeztah** [comment] 2015-11-28 12:01
To all following this; If you're still able to reproduce this on docker 1.9, please comment here, otherwise I think this can be closed \o/

**Comment by hollinwilkins** [comment] 2015-12-01 16:03
I have this issue right now. It is a problem too, because I'm not sure what to restart in order to fix it.

**Comment by hollinwilkins** [comment] 2015-12-01 16:04
% docker --version
Docker version 1.9.1, build a34a1d5

Not sure what version the server is running

**Comment by thaJeztah** [comment] 2015-12-01 17:08
@hollinwilkins on what version did you have the issue? 1.9?

**Comment by kcraft** [comment] 2015-12-01 22:35
I am having this issue as well with docker 1.9. I was in the middle of pushing an image to my private docker registry when my internet connection dropped. Now it gives me this error when I try again. Unfortunately I can't verify that restarting the docker daemon fixes the problem since I am now having other issues. My guess is that it did fix the problem just like everyone else.

**Comment by hollinwilkins** [comment] 2015-12-01 23:10
@thaJeztah It is docker 1.9

**Comment by thaJeztah** [comment] 2015-12-01 23:27
Thanks @kcraft @hollinwilkins!

**Comment by thaJeztah** [comment] 2015-12-01 23:33
ping @aaronlehmann I think you were working on rewriting this part, so perhaps you can have a look? thanks!

**Comment by aaronlehmann** [comment] 2015-12-01 23:42
@kcraft @hollinwilkins How long does the problem persist if you wait before trying to pull again? I would expect the stalled push to time out after a few minutes.

I'm going to open a PR soon that makes transfers cancellable and removes this lock completely.

**Comment by hollinwilkins** [comment] 2015-12-01 23:53
It was stalled for well over 45 minutes. We restarted the registry and got rid of a web hook, then the pushes stopped stalling.

**Comment by thaJeztah** [comment] 2015-12-02 00:35
Looks like the PR is up; see https://github.com/docker/docker/pull/18353 (nice!)

**Comment by dhlwing** [comment] 2015-12-03 07:38
docker-machine restart default worked for me in Mac OS X
thx @juandiegoh

**Comment by thaJeztah** [comment] 2015-12-11 01:05
@aaronlehmann should this be resolved now that #18353 is merged?

For people that want to test that; builds from master are available at https://master.dockerproject.org for testing

**Comment by aaronlehmann** [comment] 2015-12-11 01:08
Yes, this can be closed.

**Closed** 2015-12-11 01:34 UTC
Labels: group/distribution

**Comment by Bosn** [comment] 2016-01-18 05:48
I also got this problem, I just downloaded the latest docker...
Trying to push an image, and Ctrl + C.

Since I'm using Mac, solved this problem by:

* Open VirtualBox
* Restart the "default" VM

Than got back to normal.

**Comment by thaJeztah** [comment] 2016-01-18 06:57
@Bosn this fix will be in docker 1.10, which is not yet released

**Comment by homerjam** [comment] 2016-02-06 17:38
Same problem here, fixed by restarting docker VM...

```
$ docker-machine restart default

**Comment by schmunk42** [comment] 2016-02-06 18:06
@homerjam Which docker version do you use?

**Comment by MatthewHerbst** [comment] 2016-03-25 10:07
Same problem for me. I was uploading a large layer (270MB) and my connection dropped. When my connection came back up tried to re-push but it just got stock thinking it had already uploaded half of that layer.

OSX 10.10.5
```
$ docker --version
Docker version 1.10.0, build 590d5108
```

As per others, restarting using `$ docker-machine restart default` solved the issue.

**Comment by sub2u** [comment] 2016-05-05 02:37
docker-machine restart default  worked on mac, and now i can able to push new images to my repo

**Comment by mrhwick** [comment] 2016-05-14 14:02
:+1: `docker-machine restart default` helped me get past this on mac

**Comment by cdancy** [comment] 2016-05-14 15:55
@sub2u @mrhwick do we know the reason behind why the restart works? I can venture a guess just wondering if you guys knew anything more concrete.

**Comment by rishiloyola** [comment] 2016-05-31 19:19
Just stop your docker-machine and restart it, it will automatically stop down all your processes.

**Comment by lizrice** [comment] 2016-06-06 16:35
Seems like a shame to have to spend ages waiting for a docker-machine stop & start; surely a better fix would  be for the push / pull process to cleanly abort when it gets the Ctrl-C signal?

**Comment by cpuguy83** [comment] 2016-06-06 16:38
@lizrice This is long fixed.
Disconnecting the client will trigger a pull cancellation.
You can also attach multiple clients to the same pull.

**Comment by eljobe** [comment] 2016-06-09 09:36
I'm actually still seeing this in docker 1.11.2 on the mac OS X.

I started a push using this command:
```shell
$> gcloud docker push gcr.io/$PROJECT_ID/hello-node:v1
The push refers to a repository [gcr.io/kubernetes-hello-world-1336/hello-node]
1a6c40e0a657: Waiting 
5f70bf18a086: Waiting 
f407bcb66017: Pushing [====================================>              ]  27.1 MB/37.26 MB
42d0ce0ecf27: Waiting 
6ec10d9b4afb: Pushing [======>                                            ] 40.93 MB/317.9 MB
a80b5871b282: Pushing [========>                                          ] 21.99 MB/122.6 MB
d2c5e3a8d3d3: Pushing [======================>                            ] 19.76 MB/44.3 MB
4dcab49015d4: Pushing [===========>                                       ] 27.85 MB/125.1 MB
^C

Command killed by keyboard interrupt
```

When I got back to my laptop in the morning, it wasn't working, so I `Ctrl-C`'d the process, and ran the command again. But, it just gets to the same place and stops uploading. No bytes are sent.

I'm trying the `docker-machine restart default` workaround, but wanted to let you know that there may have been a regression.

**Comment by isaaccp** [comment] 2016-07-12 03:17
Just saw this on Mac OS X with 1.10.3

**Comment by merlinnot** [comment] 2016-07-25 18:21
Same here, `docker-machine restart default` doesn't work for me.

`Darwin merlinnot-3.local 16.0.0 Darwin Kernel Version 16.0.0: Sat Jul  9 23:23:38 PDT 2016; root:xnu-3777.0.0.0.1~27/RELEASE_X86_64 x86_64
Docker version 1.11.2, build b9f10c9
docker-machine version 0.7.0, build a650a40`

**Comment by jeremywadsack** [comment] 2016-08-08 21:41
@cpuguy83 If this is fixed is there another issue causing the push command to fail. I continue to get this (about every two or three days) on docker 1.12. Restarting the docker machine causes it to lose all local caches of the images which means that I have to pull/build/push everything from scratch again.

**Comment by cpuguy83** [comment] 2016-08-11 20:08
There is absolutely no way anyone that is on >= docker 1.10 is hitting this issue.
You may have something where your push/pull is getting stuck, but that does not mean it is this issue.

This issue is about the error `push or pull <foo> is already in progress`. The issues causing this are fixed and the error doesn't even exist in the codebase any more (since 1.10.0).

Please, if you are seeing an issue in your environment, let's open a separate issue with the error you are seeing (if there is a message, please post it).
