### ISSUE TITLE
Swarm Service: connection from Slave to Spark Master fails when a port is exposed.

### ISSUE THREAD

**Issue by laugimethods** [docker/docker#27292] opened 2016-10-11 16:49 UTC
**Description**

Exposing a port of a Spark Master running as a Swarm Service prevents the connections from the Spark Slaves (also running as a Service) to that Spark Master.
 
**Steps to reproduce the issue:**
```
> docker service create --name spark-master -e SERVICE_NAME=spark-master --network spark-net -p 8080:8080  gettyimages/spark:1.6.2-hadoop-2.6
> docker service create --name spark-slave -e SERVICE_NAME=spark-slave --network spark-net --replicas=2  gettyimages/spark:1.6.2-hadoop-2.6 bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
```

**Describe the results you received:**
The connection from the Slave to the Master fails:
```
> docker ps
> docker logs spark-slave.1.xxxxxxxxxx
16/10/11 16:26:45 INFO worker.Worker: Registered signal handlers for [TERM, HUP, INT]
16/10/11 16:26:46 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/11 16:26:46 INFO spark.SecurityManager: Changing view acls to: root
16/10/11 16:26:46 INFO spark.SecurityManager: Changing modify acls to: root
16/10/11 16:26:46 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
16/10/11 16:26:46 INFO util.Utils: Successfully started service 'sparkWorker' on port 33463.
16/10/11 16:26:47 INFO worker.Worker: Starting Spark worker 10.0.0.5:33463 with 4 cores, 6.8 GB RAM
16/10/11 16:26:47 INFO worker.Worker: Running Spark version 1.6.2
16/10/11 16:26:47 INFO worker.Worker: Spark home: /usr/spark-1.6.2
16/10/11 16:26:47 INFO server.Server: jetty-8.y.z-SNAPSHOT
16/10/11 16:26:47 INFO server.AbstractConnector: Started SelectChannelConnector@0.0.0.0:8081
16/10/11 16:26:47 INFO util.Utils: Successfully started service 'WorkerUI' on port 8081.
16/10/11 16:26:47 INFO ui.WorkerWebUI: Started WorkerWebUI at http://10.0.0.5:8081
16/10/11 16:26:47 INFO worker.Worker: Connecting to master spark-master:7077...
16/10/11 16:26:47 WARN worker.Worker: Failed to connect to master spark-master:7077
java.io.IOException: Failed to connect to spark-master/10.0.0.2:7077
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:216)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:167)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:200)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:187)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:183)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: spark-master/10.0.0.2:7077
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	... 1 more
16/10/11 16:26:58 INFO worker.Worker: Retrying connection to master (attempt # 1)
```

**Describe the results you expected:**
```
> docker service create --name spark-master -e SERVICE_NAME=spark-master --network spark-net  gettyimages/spark:1.6.2-hadoop-2.6
> docker service create --name spark-slave -e SERVICE_NAME=spark-slave --network spark-net --replicas=2  gettyimages/spark:1.6.2-hadoop-2.6 bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
> docker logs spark-slave.1.xxxxxxxxxxx
16/10/11 12:48:02 INFO worker.Worker: Registered signal handlers for [TERM, HUP, INT]
16/10/11 12:48:03 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/11 12:48:03 INFO spark.SecurityManager: Changing view acls to: root
16/10/11 12:48:03 INFO spark.SecurityManager: Changing modify acls to: root
16/10/11 12:48:03 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
16/10/11 12:48:04 INFO util.Utils: Successfully started service 'sparkWorker' on port 45899.
16/10/11 12:48:05 INFO worker.Worker: Starting Spark worker 10.0.0.8:45899 with 4 cores, 6.8 GB RAM
16/10/11 12:48:05 INFO worker.Worker: Running Spark version 1.6.2
16/10/11 12:48:05 INFO worker.Worker: Spark home: /usr/spark-1.6.2
16/10/11 12:48:05 INFO server.Server: jetty-8.y.z-SNAPSHOT
16/10/11 12:48:05 INFO server.AbstractConnector: Started SelectChannelConnector@0.0.0.0:8081
16/10/11 12:48:05 INFO util.Utils: Successfully started service 'WorkerUI' on port 8081.
16/10/11 12:48:05 INFO ui.WorkerWebUI: Started WorkerWebUI at http://10.0.0.8:8081
16/10/11 12:48:05 INFO worker.Worker: Connecting to master spark-master:7077...
16/10/11 12:48:06 INFO worker.Worker: Successfully registered with master spark://10.0.0.7:7077
```

**Additional information you deem important (e.g. issue happens only occasionally):**

That kind of cluster with the Spark Master's 8080 port exposed works fine when based on [Docker-Compose](https://github.com/Logimethods/docker-nats-connector-spark/tree/master/compose).

The Docker Image's Dockerfile used is [gettyimages/spark:1.6.2-hadoop-2.6](https://github.com/gettyimages/docker-spark/blob/spark-1.6.2-hadoop-2.6/Dockerfile) (which contains no `EXPOSE`).

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 9
 Running: 3
 Paused: 0
 Stopped: 6
Images: 7
Server Version: 1.12.2-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 41
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: active
 NodeID: diok2cmz0j2qnik4qz7vfsagu
 Is Manager: true
 ClusterID: 41p013kakqt5265t6safu1x5e
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.22-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.787 GiB
Name: moby
ID: KCCS:H6PI:SQMH:NWJ4:NYGF:FI2E:SWGC:YVG5:HJGE:D6ZQ:LXFQ:MWPX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 56
 Goroutines: 164
 System Time: 2016-10-11T16:40:59.448187411Z
 EventsListeners: 4
No Proxy: *.local, 169.254/16
Username: lmagnin
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by aboch** [comment] 2016-10-11 21:46
I think it is related to #24637

The master is actually listening on 10.255.x.x:7077

**Comment by aboch** [comment] 2016-10-11 21:58
Can reproduce the issue with latest master:

```
16/10/11 21:43:33 INFO worker.Worker: Retrying connection to master (attempt # 1)
16/10/11 21:43:33 INFO worker.Worker: Connecting to master spark-master:7077...
16/10/11 21:43:33 WARN worker.Worker: Failed to connect to master spark-master:7077
java.io.IOException: Failed to connect to spark-master/10.0.0.2:7077
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:216)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:167)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:200)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:187)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:183)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: spark-master/10.0.0.2:7077
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	... 1 more
```
Confirmed the master was binding to the ingress network interface address 10.255.x.x

Verified the change in https://github.com/docker/libnetwork/pull/1494 (although not complete yet) fixes the issue:

```
16/10/11 21:53:29 INFO worker.Worker: Registered signal handlers for [TERM, HUP, INT]
16/10/11 21:53:30 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/11 21:53:30 INFO spark.SecurityManager: Changing view acls to: root
16/10/11 21:53:30 INFO spark.SecurityManager: Changing modify acls to: root
16/10/11 21:53:30 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
16/10/11 21:53:31 INFO util.Utils: Successfully started service 'sparkWorker' on port 37855.
16/10/11 21:53:31 INFO worker.Worker: Starting Spark worker 10.0.0.6:37855 with 4 cores, 6.4 GB RAM
16/10/11 21:53:31 INFO worker.Worker: Running Spark version 1.6.2
16/10/11 21:53:31 INFO worker.Worker: Spark home: /usr/spark-1.6.2
16/10/11 21:53:32 INFO server.Server: jetty-8.y.z-SNAPSHOT
16/10/11 21:53:32 INFO server.AbstractConnector: Started SelectChannelConnector@0.0.0.0:8081
16/10/11 21:53:32 INFO util.Utils: Successfully started service 'WorkerUI' on port 8081.
16/10/11 21:53:32 INFO ui.WorkerWebUI: Started WorkerWebUI at http://10.0.0.6:8081
16/10/11 21:53:32 INFO worker.Worker: Connecting to master spark-master:7077...
16/10/11 21:53:37 INFO worker.Worker: Retrying connection to master (attempt # 1)
16/10/11 21:53:37 INFO worker.Worker: Connecting to master spark-master:7077...
16/10/11 21:53:37 INFO worker.Worker: Successfully registered with master spark://10.0.0.3:7077
```
 

I think we should close this issue as duplicate of  #24637

**Comment by thaJeztah** [comment] 2016-10-11 22:04
Thanks for checking @aboch, let's close this one, as we're tracking the issue through https://github.com/docker/docker/issues/24637

Thanks for reporting @laugimethods

**Closed by thaJeztah** 2016-10-11 22:04 UTC
Labels: area/networking, area/swarm, version/1.12
