### ISSUE TITLE
在A容器里面重启docker导致B的Daemon里面的容器不能对A容器进行ssh操作-显示：*** no route to host

### ISSUE THREAD

**Issue by doungni** [docker/docker#17354] opened 2015-10-26 03:29 UTC
root@********:~# docker -v
Docker version 1.6.2, build 7c8fca2

root@********:~# docker info
FATA[0000] Get http:///var/run/docker.sock/v1.18/info: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

root@********:~# uname -a
Linux ******** 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

会不会是 Iptables被篡改了？

**Comment by cxxly** [comment] 2015-10-26 06:21
This description is not clear. could you list the steps to reproduce this issue

**Comment by unclejack** [comment] 2016-01-03 10:27
`service docker start` may be needed in some cases to start the Docker daemon.

I'll close this issue now since there doesn't seem to be an actual issue, just a configuration or the absence of the Docker daemon. Please feel free to comment.

**Closed by unclejack** 2016-01-03 10:27 UTC
Labels: status/more-info-needed
