### ISSUE TITLE
Docker 1.5 Memory Leak

### ISSUE THREAD

**Issue by witoff** [docker/docker#13470] opened 2015-05-26 00:31 UTC
Running docker 1.5 on CoreOS Stable 633.1.0 causes us to lose a node (or restart the docker daemon) repeatably, at least once per week within a fleet cluster.  Information on our system is below, where you can see ~18GB mapped by the docker daemon on a 15GB machine.  Swap is intentionally turned off.  Similar issues have been filed and closed #8502, #8539, #9139 without clear resolution.  

In case it helps:
* Some of our containers do output heavily to stdout/stderr and we're `truncate -s 0`  our logs regularly.
* Some of our containers also move quite a lot of data on disk.
* Manually restarting the docker daemon gets us back into a healthy state

```bash
$ docker --debug info
Containers: 15
Images: 451
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.19.0
Operating System: CoreOS 633.1.0
CPUs: 2
Total Memory: 14.94 GiB
Name: MACHINE.internal
ID: NCJK:EP3U:4ZVM:MVNR:NNAS:Y4YK:XQZJ:TTUN:HLNU:W4QJ:PQTM:BFDB
Debug mode (server): false
Debug mode (client): true
Fds: 122
Goroutines: 321
EventsListeners: 0
Init SHA1: d38cc73fea843c7e1bad0118cf99c61061254a72
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker

$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=633.1.0
VERSION_ID=633.1.0
BUILD_ID=
PRETTY_NAME="CoreOS 633.1.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

$ free
             total       used       free     shared    buffers     cached
Mem:      15670088    7374708    8295380        932    1658556    1034660
-/+ buffers/cache:    4681492   10988596
Swap:            0          0          0


$ ps -aux | grep "docker --"
root      7792  0.8 18.4 18606464 2892732 ?    Ssl  May20  59:42 docker --daemon --host=fd://

$ docker ps
CONTAINER ID        IMAGE                                COMMAND                CREATED             STATUS              PORTS               NAMES
88a18168eac9        IMAGE    "sh -c 'ruby /opt/st   5 days ago          Up 5 days                               NAME
8538955d9c99        IMAGE   "/bin/sh -c 'rake ru   5 days ago          Up 5 days                               NAME


$ fleetctl list-units | grep MY_IP
UNIT.service		595ed27f.../MY_IP	activating	auto-restart
UNIT.service		595ed27f.../MY_IP	activating	auto-restart
TIMER.timer		  595ed27f.../MY_IP	active		  waiting
UNIT.service	  595ed27f.../MY_IP	activating	auto-restart
UNIT.service	  595ed27f.../MY_IP	activating	auto-restart
UNIT.service	  595ed27f.../MY_IP	activating	auto-restart
UNIT.service	  595ed27f.../MY_IP	activating	auto-restart
UNIT.service	  595ed27f.../MY_IP	activating	auto-restart
UNIT.service		595ed27f.../MY_IP	active		  running
UNIT.service		595ed27f.../MY_IP	activating	auto-restart
UNIT.service	  595ed27f.../MY_IP	activating	auto-restart
UNIT.service		595ed27f.../MY_IP	active		  running

$ journalctl -f -u UNIT
-- Logs begin at Mon 2015-05-25 17:37:10 UTC. --
May 26 00:27:47  systemd[1]: Started UNIT
May 26 00:27:47 docker[22467]: time="2015-05-26T00:27:47Z" level="fatal" msg="Error response from daemon: Cannot start container 888: fork/exec /var/lib/docker/init/dockerinit-1.5.0: cannot allocate memory"

$ docker run --rm -it debian bash
FATA[0000] Error response from daemon: Cannot start container ccd1b1814d0a770be5e2487bd67291b438b07d0f7253be12354f942d7dc0ff50: fork/exec /var/lib/docker/init/dockerinit-1.5.0: cannot allocate memory
```

**Comment by mc0e** [comment] 2015-05-26 07:02
I also have a current memory leak issue, with docker 1.6.2, which is not otherwise covered by an open ticket.  It's on a low priority personal server, and for the time being I'm keeping it up by restarting docker twice a day.  I haven't yet gotten to putting much time into trying to track down what the cause is, but I'm happy to run diagnostics suggested here and maybe we're looking at the same issue.

**Comment by thaJeztah** [comment] 2015-05-26 07:59
@witoff so Docker *is* rocket science after all! 😀

All jokes aside, I think most memory leaks / high memory uses in Docker evolve around high volume logging and the user land proxy.

Docker 1.6 added the option for different logging drivers, which may help in some cases to offload the logging from the docker daemon, and disabling the userland proxy will be possible in the next release.

Having said that, @unclejack is the maintainer that has been most involved in optimizing these areas, and he might be interested to see if there are ways to improve the situation.

If needed, are you able to run a more recent version of Docker, and change other settings for debugging?

ping @unclejack for additional thoughts :)

**Comment by unclejack** [comment] 2015-05-26 08:59
@thaJeztah Thank you for the ping.

Docker 1.7 will have the fixes for these problems. Those who are eager to check if the problems they were seeing are fixed can try nightly binaries built from master: https://master.dockerproject.com/
Docker 1.6.x doesn't have the fixes and it won't have them.

@witoff You should be able to see exactly what changes have been made to help with #9139 by looking at that issue. Two of the fixes I mention below are listed on #9139 below "This was referenced on Mar 29". If you take a look at some of the other issues which reference #9139, you will see that they state quite explicitly what I'm writing below.

@mc0e Perhaps you could try the binaries from https://master.dockerproject.com/ to see if your problems are solved by these changes.

Here are the changes which have been made to help with memory usage problems:
https://github.com/docker/docker/pull/11898
https://github.com/docker/docker/pull/11930
https://github.com/docker/docker/pull/11994
https://github.com/docker/docker/pull/13246

These changes have fixed all the issues I've seen so far. Should you still have problems with the binaries from https://master.dockerproject.com/, please comment.

Since this issue is considered fixed and the next release (1.7.0) will ship the fixes, I'm going to close it.

**Closed by unclejack** 2015-05-26 08:59 UTC

**Comment by witoff** [comment] 2015-05-26 17:27
@thaJeztah thanks for the good info!  This is a big help.  I'm still collecting oscope dumps for the next issue around running Docker on rad hardened FPGAs ;)

@unclejack thanks for breaking down and linking to other issues.  this is a big help and does look like you're covering the source, not just symptoms of this issue.  we'll try to give a go on latest 1.7's and look forward to the 1.7 stable release.

**Comment by oncletom** [comment] 2015-06-30 06:32
Sadly I still encounter errors with Docker 1.7.0 and syslog driver enabled on an EC2 t2.micro instance.

Recurrent error is: *Error response from daemon: Cannot start container 5cbc9625e9d954ebc6115e955de528617ca59d841e05b22a2f7b7e33e9e8120e: namespace creation reexec command failed: fork/exec /usr/bin/docker: cannot allocate memory*

The containers are chatty log-wise, we have 3 long-running one spawning ~500 ephemeral ones per hour.

```bash
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

```bash

 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 125
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: syslog
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 992.5 MiB
Name: ip-10-0-0-192
ID: L3LB:QZSG:F6GO:KSSJ:MJFJ:N7TV:ALPX:OHTN:JWXH:TEBP:AASQ:37FJ
WARNING: No swap limit support
```

```bash
$ free
             total       used       free     shared    buffers     cached
Mem:       1016340     921332      95008        860      58864     134856
-/+ buffers/cache:     727612     288728
Swap:            0          0          0
```

**Comment by thaJeztah** [comment] 2015-06-30 09:45
@oncletom not sure if it's related, but you might want to watch https://github.com/docker/docker/pull/14268 (and https://github.com/docker/docker/issues/12848)

**Comment by oncletom** [comment] 2015-06-30 10:01
Thanks @thaJeztah, I have reported the informations on #12848 as well.

**Comment by unclejack** [comment] 2015-06-30 10:06
@oncletom Your problem is caused by https://github.com/docker/docker/issues/13552.

**Comment by mc0e** [comment] 2015-07-03 04:58
I'm not sure if the later docker resolves my issue, but I seem to have corrected what was causing it, and that cause may be useful to others to know about since I expect it is easy to reproduce:  just fire up logspout as first shown on it's README page, without customizing a sensible target:

    docker run --name="logspout" \
        --volume=/var/run/docker.sock:/tmp/docker.sock \
        gliderlabs/logspout \
        syslog://logs.papertrailapp.com:55555

It's entirely reasonable that logspout should fail here, but not that the main docker process should leak memory.

**Comment by unclejack** [comment] 2015-07-03 08:34
@mc0e Multiple memory usage fixes have gone into Docker 1.7. Using Docker 1.7 with the default jsonlog logging driver shouldn't cause any more problems.

**Comment by esatterwhite** [comment] 2016-02-18 18:46
I know this issue has been close, but I'm still experiencing this problem, even for apps that don't log to stdout

running on aws ECS instances
```
Linux west-2.compute.internal 4.3.3-coreos-r2 #2 SMP Fri Jan 22 10:57:46 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux

Containers: 1
Images: 30
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.3-coreos-r2
Operating System: CoreOS 899.5.0
CPUs: 1
Total Memory: 1.957 GiB

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64
```

```
free
            total       used       free     shared    buffers     cached
Mem:       2051772    1731896     319876        520     522692     572016
-/+ buffers/cache:     637188    1414584
Swap:            0          0          0
```

```
cat /etc/os-release

NAME=CoreOS
ID=coreos
VERSION=899.5.0
VERSION_ID=899.5.0
BUILD_ID=2016-01-22-1100
PRETTY_NAME="CoreOS 899.5.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues
```

As for steps to reproduce:

We effectively run a single container on a single VM and do
```
1. docker stop containername
2. docker pull imagename
3. docker run ...
```

at least once a day. It doesn't seem too matter how much memory is on the VM, docker used almost all of it leaving ~200-400mb on the machine.

**Comment by thaJeztah** [comment] 2016-02-19 13:06
@esatterwhite hard to tell; could also be an issue with the container?

**Comment by esatterwhite** [comment] 2016-02-19 13:15
That's possible, but its happening on all of them. We have 30 VMs. Containers have different Apps written in different languages, doing different things.

Docker is showing this behavior on all of them, using upwards of 8G on some machines.

What kind of an issue in the container would cause this problem with the docker daemon? I'm not sure what to look for.
