### ISSUE TITLE
FATAL 4215 error on push

### ISSUE THREAD

**Issue by Sentimentron** [docker/docker#13472] opened 2015-05-26 08:07 UTC
Hi, new to Docker so it's probably something obvious. I've committed and I'm ready to push my (rather large) image, but it fails with a 4215 error.
```
rtownsend@HP:/$ docker push sentimentron/hefner-postgis-v1
The push refers to a repository [sentimentron/hefner-postgis-v1] (len: 1)
Sending image list

Please login prior to push:
Username: sentimentron
Password: 
Email: richard@sentimentron.co.uk
Login Succeeded
The push refers to a repository [sentimentron/hefner-postgis-v1] (len: 1)
Sending image list
Pushing repository sentimentron/hefner-postgis-v1 (1 tags)
9802b3b654ec: Image already pushed, skipping 
14975cc0f2bc: Image already pushed, skipping 
8d07608668f6: Image already pushed, skipping 
d191563ad36b: Image already pushed, skipping 
79661f49a588: Image successfully pushed 
5c297e6eb96f: Image successfully pushed 
a25b1d241851: Image successfully pushed 
104b9efccbe9: Image successfully pushed 
53509de88104: Image successfully pushed 
44517d70236c: Image successfully pushed 
ae299e6d07d5: Image successfully pushed 
03ed5350cb71: Image successfully pushed 
795be6c05eff: Image successfully pushed 
c77b18aca8c8: Pushing [==================================================>] 17.21 GB/17.21 GB
FATA[4215]
```
Any thoughts on what the problem might be, or is the image simply too large to be pushed?

**Comment by Sentimentron** [comment] 2015-05-26 23:09
```
Description of problem: Docker fails with a 4215 error when pushing large image.

`docker version`: 
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

`docker info`:
Containers: 38
Images: 67
Storage Driver: aufs
 Root Dir: /home/docker/data/aufs
 Backing Filesystem: extfs
 Dirs: 143
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 15.61 GiB
Name: HP
ID: 7NOU:BHQ6:XTMX:FW4N:3RC4:LZ3T:WAWX:7UPI:VSS5:MRRT:M6YM:YVTM
Username: sentimentron
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

`uname -a`: 
Linux HP 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

How reproducible: Unknown 

Steps to Reproduce: 
1. [Presumption] Prepare 17.65 GB Docker image
2. Push to Docker Hub

Actual Results:
Fails with 4215 FATAL error message after uploading the image.

Expected Results:
Push completes and becomes visible in Docker Hub.

Additional info:
I'm trying to replicate the problem on a different machine, will update.
```

**Comment by jmakanjuola** [comment] 2015-05-27 06:34
Is this from a new build?

**Comment by Sentimentron** [comment] 2015-05-27 12:10
The actual image is newly built (uses an Ubuntu 14.10 base image) but the Docker installation is from the standard Ubuntu 14.04 LTS repositories.

**Comment by cpuguy83** [comment] 2015-09-15 00:24
If I had to guess there is some issue with the size of the image.
Did you check the daemon logs? Can you enable debug mode?
The "4215" is a time code and not an error code.

Also, can you reproduce on docker 1.8.2?

**Comment by thaJeztah** [comment] 2015-10-14 02:27
closing because OP didn't respond, but I'm happy to reopen after

**Closed by thaJeztah** 2015-10-14 02:27 UTC
Labels: status/more-info-needed
