### ISSUE TITLE
Unable to enable experimental mode in Mac Os

### ISSUE THREAD

**Issue by manast** [docker/docker#32037] opened 2017-03-23 11:23 UTC
For some reason experimental mode does not get enabled. Check this out:

![image](https://cloud.githubusercontent.com/assets/95200/24245501/6344ec0a-0fc3-11e7-9100-135c3db4ddd6.png)

![image](https://cloud.githubusercontent.com/assets/95200/24245515/6cea74f0-0fc3-11e7-9c4b-f147d40d0cee.png)

```
$ docker version -f '{{.Server.Experimental}}'
false
```

```
$ docker info
Containers: 14
 Running: 6
 Paused: 0
 Stopped: 8
Images: 657
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 399
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: reyziqzvf60iyknikuby1v0g9
 Is Manager: true
 ClusterID: 7xoli7hddgqhfgyjl8gbhnbsj
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.100
 Manager Addresses:
  192.168.99.100:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.52-boot2docker
Operating System: Boot2Docker 17.03.0-ce (TCL 7.2); HEAD : f11a204 - Thu Mar  2 00:14:47 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: 7KPT:J7DV:2ESY:KRYQ:ZSXF:PWHB:IYUY:QBQ6:TLBJ:5SHX:CHKE:QTOG
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 314
 Goroutines: 658
 System Time: 2017-03-23T11:23:12.482339158Z
 EventsListeners: 2
Username: manast
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-03-23 11:29
It looks like you also have VirtualBox installed, and are connecting to a docker daemon running in VirtualBox / Boot2Docker, not Docker 4 Mac

I'll close this issue, because it's not a bug, but feel free to continue the conversation if you need help

**Closed by thaJeztah** 2017-03-23 11:29 UTC

**Comment by manast** [comment] 2017-03-23 11:55
all right, I definitely need help then :) kind of you. It must be that I have been upgrading since old versions based in boot2docker and it keeps using it.  So what are the steps to migrate to docker 4 mac? My virtualbox is managed by docker-machine, so I thought i was already using docker 4 mac.

**Comment by manast** [comment] 2017-03-23 12:01
Creating a new local machine still uses boot2docker, I cannot find any information how to upgrade it so that it does not use boot2docker anymore:
```
$ dm create --driver "virtualbox" local
Running pre-create checks...
Creating machine...
(local) Copying /Users/manuel/.docker/machine/cache/boot2docker.iso to /Users/manuel/.docker/machine/machines/local/boot2docker.iso...
(local) Creating VirtualBox VM...
(local) Creating SSH key...
(local) Starting the VM...
(local) Check network to re-create if needed...
(local) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
```

**Comment by manast** [comment] 2017-03-23 12:23
ok, got it and it works. Thanks once again.

**Comment by thaJeztah** [comment] 2017-03-24 16:13
great!

**Comment by eyalyoli** [comment] 2020-12-31 07:59
For the ones that must stick with Virtualbox docker - you should connect to the running machine via ```docker-machine ssh [MACHINE_NAME]``` and configure ```/etc/docker/daemon.json``` file to include:
```json
{
  "experimental" : true
}
```
Finally, restart the docker daemon.

If you forgot your machine name just run ```docker-machine ls```
