### ISSUE TITLE
docs/man completely messed up

### ISSUE THREAD

**Issue by aanm** [docker/docker#12866] opened 2015-04-29 03:34 UTC
Some of docker man pages are completely messed up (e.g. docker-cp and docker-run)
`Docker version 1.6.0, build 3eac457/1.6.0`

For example `man docker cp` results in
```
NAME
       docker-cp - Copy files or folders from a container's PATH to a HOSTDIR or to STDOUT.

SYNOPSIS
       docker cp [--help] CONTAINER:PATH HOSTDIR|-

DESCRIPTION
       Copy files or folders from a CONTAINER:PATH to the HOSTDIR or to STDOUT.  The CONTAINER:PATH is relative to the root of the container's filesystem. You can copy from either a running or stopped container.

       The  PATH  can  be  a  file  or  directory.  The  docker  cp  command  assumes  all  PATH values start at the / (root) directory. This means supplying the initial forward slash is optional; The command sees compassionate_dar‐
       win:/tmp/foo/myfile.txt and compassionate_darwin:tmp/foo/myfile.txt as identical.

       The HOSTDIR refers to a directory on the host. If you do not specify an absolute path for your HOSTDIR value, Docker creates the directory relative to where you run the docker cp command. For example, suppose you want to copy
       the /tmp/foo directory from a container to the /tmp directory on your host. If you run docker cp in your   (home) directory on the host:

                  docker cp compassionate_darwin:tmp/foo /tmp

              Docker creates a /tmp/foo directory on your host. Alternatively, you can omit the leading slash in the command. If you execute this command from your home directory:

                         docker cp compassionate_darwin:tmp/foo tmp

                     Docker creates a  /tmp/foo subdirectory.

                     When copying files to an existing HOSTDIR, the cp command adds the new files to the directory. For example, this command:

                                docker cp sharp_ptolemy:/tmp/foo/myfile.txt /tmp

                            Creates a /tmp/foo directory on the host containing the myfile.txt file. If you repeat the command but change the filename:

                                       docker cp sharp_ptolemy:/tmp/foo/secondfile.txt /tmp

                                   Your host's /tmp/foo directory will contain both files:

                                              ls /tmp/foo
                                              myfile.txt secondfile.txt

                                          Finally, use '-' to write the data as a tar file to STDOUT.

```
and should be
```
NAME
       docker-cp - Copy files or folders from a container's PATH to a HOSTDIR or to STDOUT.

SYNOPSIS
       docker cp [--help] CONTAINER:PATH HOSTDIR|-

DESCRIPTION
       Copy files or folders from a CONTAINER:PATH to the HOSTDIR or to STDOUT.  The CONTAINER:PATH is relative to the root of the container's filesystem. You can copy from either a running or stopped container.

       The  PATH  can  be  a  file  or  directory.  The  docker  cp  command  assumes  all  PATH values start at the / (root) directory. This means supplying the initial forward slash is optional; The command sees compassionate_dar‐
       win:/tmp/foo/myfile.txt and compassionate_darwin:tmp/foo/myfile.txt as identical.

       The HOSTDIR refers to a directory on the host. If you do not specify an absolute path for your HOSTDIR value, Docker creates the directory relative to where you run the docker cp command. For example, suppose you want to copy
       the /tmp/foo directory from a container to the /tmp directory on your host. If you run docker cp in your   (home) directory on the host:

                  docker cp compassionate_darwin:tmp/foo /tmp

       Docker creates a /tmp/foo directory on your host. Alternatively, you can omit the leading slash in the command. If you execute this command from your home directory:

                  docker cp compassionate_darwin:tmp/foo tmp

       Docker creates a  /tmp/foo subdirectory.

       When copying files to an existing HOSTDIR, the cp command adds the new files to the directory. For example, this command:

                  docker cp sharp_ptolemy:/tmp/foo/myfile.txt /tmp

       Creates a /tmp/foo directory on the host containing the myfile.txt file. If you repeat the command but change the filename:

                  docker cp sharp_ptolemy:/tmp/foo/secondfile.txt /tmp

       Your host's /tmp/foo directory will contain both files:

                  ls /tmp/foo
                  myfile.txt secondfile.txt

       Finally, use '-' to write the data as a tar file to STDOUT.
```

**Comment by jfrazelle** [comment] 2015-04-29 21:01
do you want to make a PR to fix?

**Comment by aanm** [comment] 2015-04-29 22:28
@jfrazelle I was about to start but then I realize it would be pointless. I believe we need to tackle the script that generates the man pages and we should ping @cpuguy83 to take a look at https://github.com/cpuguy83/go-md2man
;-)

**Comment by thaJeztah** [comment] 2015-04-29 23:48
Looking at the source https://github.com/docker/docker/blob/9a78ed8f48f2d1404c4fadcb6116ffd46cd335f5/docs/man/docker-cp.1.md, I do see that the code-blocks are indented too far (two tabs or 8 spaces), I wonder if reducing the indentation fixes it?

(I agree that the script should be able to handle that)

**Comment by WeiZhang555** [comment] 2015-04-30 03:15
I just fix some man page issues and have a little experience about this, maybe I can help fix this. 
Maybe I help do this? @thaJeztah

**Comment by cpuguy83** [comment] 2015-04-30 12:08
Hmmm, the man docs I see don't look like this.
Here's what I get on a fresh docker 1.6 install
![screen shot 2015-04-30 at 8 07 14 am](https://cloud.githubusercontent.com/assets/799078/7412356/fd3b297c-ef0f-11e4-8c7a-8bb211979618.png)

**Comment by bcexelbi** [comment] 2015-06-08 09:20
@cpuguy83 where did you get this install from?  It appears the repo is still using v1 of your go-md2man repo which has the indention bug.

**Comment by cpuguy83** [comment] 2015-06-08 12:37
@bcexelbi This is from the official repo @ get.docker.com
See the repo Dockerfile, it's been using v 1.0.1 for quite some time which has issues fixed.
Beyond that, the actual md for the man pages was just flat out wrong.

I'm going to close this.
If someone can point out a specific doc that is still non-functional (and make sure your man docs are up to date) please open a separate issue so either the doc can be updated or deal with a potential parser bug.

**Closed by cpuguy83** 2015-06-08 12:37 UTC
Labels: exp/beginner, status/docs-help

**Comment by bcexelbi** [comment] 2015-06-08 12:47
@cpuguy83 https://github.com/docker/docker/blob/master/docs/man/Dockerfile still seems to be referencing v1

am I looking at the wrong file?

**Comment by cpuguy83** [comment] 2015-06-08 12:51
Oh... there's a separate Dockerfile... that's helpful.
Yeah, I suppose we'll need to update that.

**Comment by aanm** [comment] 2015-06-08 13:48
Is this fixed? Because I'm still having this issue.

**Comment by bcexelbi** [comment] 2015-06-08 15:14
@aanm what is the source of your docker install?  I was still seeing this on F21 so that prompted my PR

**Comment by aanm** [comment] 2015-06-08 15:30
@bcexelbi I'm trying it sources

**Comment by bcexelbi** [comment] 2015-06-08 16:20
@aanm the indention bug is fixed if you build with the Dockefile in the root directory (not confirmed by me, but reported by @cpuguy83).  If you use the Dockerfile in the docs/man/ directory it is not fixed.  I believe PR #13801 fixes it.

**Comment by aanm** [comment] 2015-06-08 20:48
@bcexelbi Ah I see, yep it is fixed, thanks for take a look at it ;-)
