### ISSUE TITLE
Upgrade from 1.11 to 1.12 - docker service start - mount: permission denied

### ISSUE THREAD

**Issue by rhpaiva** [docker/docker#25687] opened 2016-08-13 19:24 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 37
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 202
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.649 GiB
Name: note
ID: JVMA:EL4M:MW5L:I5T4:DUGB:DSXE:BL6W:RTX7:FXA7:4W2Y:ETBD:UBUF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Local machine. I'm installing docker in a docker image (Jenkins) for CI purposes.

**Steps to reproduce the issue:**
1. Try to build the image from Dockerfile below.
2. 
3.

**Describe the results you received:**
With docker 1.11 I could build this image, but with 1.12 I get this error when the build gets to "RUN service docker start" and the build stops.

mount: permission denied
rmdir: failed to remove ‘cpu’: Read-only file system
mount: permission denied
rmdir: failed to remove ‘cpuacct’: Read-only file system
mount: permission denied
rmdir: failed to remove ‘net_cls’: Read-only file system
mount: permission denied
rmdir: failed to remove ‘net_prio’: Read-only file system
/etc/init.d/docker: 96: ulimit: error setting limit (Operation not permitted)

**Describe the results you expected:**
With docker version 1.11 the build runs through, although with the same error, but it finishes. What am I missing now with the version 1.12? What changes could lead this to break now?

**Additional information you deem important (e.g. issue happens only occasionally):**

Dockerfile

FROM jenkins:2.7.2
MAINTAINER Rodrigo Paiva

USER root

RUN apt-get update && apt-get install --assume-yes \
      apt-transport-https \
      ca-certificates \
      make \
      rsync \
      sudo \
    && apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D \
    && echo deb https://apt.dockerproject.org/repo debian-jessie main > /etc/apt/sources.list.d/docker.list \
    && apt-get update \
    && echo "\n>>> Installing docker-engine\n" \
    && apt-get --assume-yes install docker-engine \
    && rm -rf /var/lib/apt/lists/*

RUN usermod --append --groups docker jenkins

RUN service docker start

USER jenkins

**Comment by thaJeztah** [comment] 2016-08-13 21:07
I doubt this ever worked, because running docker in a container requires the container to be started with `--privileged`, which is not the default and cannot be done during `docker build`. In addition, `service docker start` requires a process manager (such as upstart or systemd) to be running, which also isn't the case.

What are you trying to achieve in this image? Even if this *would* work, using `RUN service docker start` would only start docker once during build, (in that build step), but it would not be running in the next step, nor would it be running when starting a container from the image that's built.

Given the above, I don't think there's a regression or a bug here, so I close this issue, but feel free to continue the discussion if you have questions

**Closed by thaJeztah** 2016-08-13 21:07 UTC
Labels: version/1.12

**Comment by thaJeztah** [comment] 2016-08-13 21:08
You may also be interesting in reading this article; https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
