### ISSUE TITLE
ERROR: Container command not found or does not exist.

### ISSUE THREAD

**Issue by seanauriti** [docker/docker#20789] opened 2016-02-29 16:49 UTC
Summary: 
On Windows: when something goes wrong like a missing file or similar, the output of docker's error can be more explanatory.

Output of `docker version`:

```
$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 12
 Running: 6
 Paused: 0
 Stopped: 6
Images: 42
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 170
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: AMDN:EJZ3:24NZ:6PET:A3ZB:SRAR:MKLG:IYP2:CWAC:PIXJ:YFKL:ZJYW
Debug mode (server): true
 File Descriptors: 52
 Goroutines: 70
 System Time: 2016-02-29T16:46:15.919696262Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Virtualbox

List the steps to reproduce the issue:
1. Docker run image
2.
3.

Describe the results you received:
Getting the error: ERROR: Container command not found or does not exist.

Describe the results you expected:
Expected the image to run

Provide additional info you think is important:
Related to this link - https://github.com/docker/compose/issues/2950

**Comment by seanauriti** [comment] 2016-02-29 16:55
Similar issue: https://github.com/docker/docker/issues/20376

**Comment by thaJeztah** [comment] 2016-02-29 17:14
@seanauriti thanks for opening this issue; what do you think would be a better error message? This error is already an attempt to make the error that's returned by the system a bit more friendly, so interested to hear what you think would make a good error :+1: 

For reference, see: https://github.com/docker/docker/blob/df2b74188ec51422e84ec1dbdc58abf08c215019/container/monitor.go#L186-L194

**Comment by thaJeztah** [comment] 2016-02-29 17:16
Oh, and https://github.com/docker/docker/blob/df2b74188ec51422e84ec1dbdc58abf08c215019/api/client/run.go#L24 :smile:

**Comment by seanauriti** [comment] 2016-02-29 17:25
Is there a way to return the command name?  

Maybe if there is a way to run in a more verbose mode to say which commands were running and / or which section of the docker-compose file was being run, that would be a huge help in tracing down where the error is coming from.  Thanks for the quick reply @thaJeztah

**Comment by seanauriti** [comment] 2016-02-29 17:56
One way to help debug the issue is to run
docker-machine ssh [machine-name]
and tail -f /var/log/docker.log  while you are starting the container.  Here is the output I saw for this error:

`time="2016-02-29T17:51:30.464189301Z" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.9)"
time="2016-02-29T17:51:30.470394694Z" level=error msg="error locating sandbox id 232155e69307b7dd9a5c2e5408d3fcd9d6ed4b3d6eaedd884891262ab83eb39c: sandbox 232155e69307b7dd9a5c2e5408d3fcd9d6ed4b3d6eaedd884891262ab83eb39c not found"
time="2016-02-29T17:51:30.470439375Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /mnt/sda1/var/lib/docker/containers/847abf893e4e5c1cad35f5104784e258fecd4d4d6d10cc462ed6403c6b096b32/shm: invalid argument"
time="2016-02-29T17:51:30.470453358Z" level=error msg="Error unmounting container 847abf893e4e5c1cad35f5104784e258fecd4d4d6d10cc462ed6403c6b096b32: not mounted"
time="2016-02-29T17:51:30.470516269Z" level=error msg="Handler for POST /v1.21/containers/847abf893e4e5c1cad35f5104784e258fecd4d4d6d10cc462ed6403c6b096b32/start returned error: Container command not found or does not exist."`

**Comment by thaJeztah** [comment] 2016-02-29 18:48
> which commands were running and / or which section of the docker-compose file was being run

The original error is basically the error that occurred inside a container (e.g. the container had a `CMD run-me`, and `run-me` was not found inside the container)

**Comment by maltyxx** [comment] 2016-03-01 15:06
I have the same problem.

**Comment by gigidwan** [comment] 2016-03-01 15:12
I think it would be descriptive enough if we would print the `cmd` that could not be run with proper error message, so that its easier to trace down the exact issue.
e.g. cannot start container: command `cmd` was not found or does not exist

`Container command not found` seems to be ambiguous one.

For that matter, I think it would be good if this could also be modified to show proper error, like `cannot start container, command 'cmd' could not be invoked: permission denied`
https://github.com/docker/docker/blob/v1.10.2/errors/daemon.go#L952-L959

**Comment by doungni** [comment] 2016-03-02 07:33
问题：
	root@do:~# docker run -td --privileged --name "n1" -h "n1" -p 10022:22 ubuntu /usr/sbin/sshd -D
	720537133a6ece469fc1aeeb49f2561de2f874fdb491e671756ed17d096b3363
	docker: Error response from daemon: Container command not found or does not exist..
	root@do:~# echo $?
	127
	root@do:~# ls /usr/sbin/sshd
	/usr/sbin/sshd
	
	环境：
		root@do:~# uname -a
		Linux do 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
		root@do:~# docker --version
Docker version 1.10.2, build c3959b1

解决：
	start3
	root@ubuntu:~# docker run -td --privileged --name "start3" -h "start3" -P ubuntu/full_package /usr/sbin/sshd -D
	1215c900d8f44b1370669101f9b9596938475c04df00bc67e01477388490f250
	root@ubuntu:~# docker stop start3
	start3

	说明：
		这个与环境无关，docker run cmd，执行的命令必须是镜像里面支持的命令，如果镜像里面没有该命令，则会出现这个错误
		
		root@do:~# docker run -td --privileged --name "n1" -h "n1" -p 10022:22 ubuntu /bin/bash
		be8440d87af0c6372a54cf4e817d0d06f8e40d106c416479c23eeae49773924c
		root@do:~# docker exec -it n1 bash
		root@n1:/# ll /usr/sbin/sshd
		ls: cannot access /usr/sbin/sshd: No such file or directory
		
所以在 使用 docker run cmd执行命令的时候，需要考虑命令是否被镜像支持

**Comment by thaJeztah** [comment] 2016-03-02 11:33
@doungni could you try and explain your question in English? Willing to help, but I'm not sure what your question/comment is

**Comment by doungni** [comment] 2016-03-02 11:44
@thaJeztah Thx u point, Has changed

**Comment by DaveStein** [comment] 2016-03-13 01:36
I have `command: /app/compose.sh` in my YML which works fine on a Mac. In Windows I get an error nearly identical to the above: `"Handler for POST /v1.21/containers/7c889d3e71bf9b7059b5cd3faaf8f43490df22aaaa15aa3efb62f5597363242d/start returned error: Container command could not be invoked.`

Note that even if my `compose.sh` is nuked to be an empty file with just `#!/bin/bash` at the top, I get the same error.

**Comment by seanauriti** [comment] 2016-03-13 20:50
Turns out my issue was the volumes section was not mounting properly because on the windows version only the C:\Users directory gets mounted.  Moving the project into that directory solved the issue.  There were also a few executable +x issues on two files and some files had Windows style carriage returns at the end of the line that needed to be converted.  Still would be nice to know which command cannot be found.

**Comment by kklepper** [comment] 2016-03-14 17:38
On AWS EC2/ubuntu, I tried to transform a Dockerfile setup from ``phusion/baseimage`` to ``gliderslabs/alpine``. Turns out that those shell scripts use ``bash`` -- of course! Simply change to ``sh``, as bash is not present, resulting in the above error..

**Comment by dimasch** [comment] 2016-03-16 16:56
+1 The same issue

**Comment by duglin** [comment] 2016-03-20 01:10
See #21345

**Comment by seanauriti** [comment] 2016-03-20 02:29
Thanks for the fix @duglin

**Comment by gittycat** [comment] 2016-04-05 03:17
Could we re-open this issue?

I'm also hitting this same error message when a volume doesn't exist but is referenced by a service. The message is very misleading which translates into hours of frustration.

I can reproduce the error in a small docker swarm of two nodes using docker-compose.

My compose file specifies a volume `beanstalkd_volume`. Typically this means that it gets created on both nodes but it sometimes doesn't (which is another issue by itself). So when the volume exists on node02 but not node01 and I constraint the service to start only on node01, I get the same error `ERROR: 500 Internal Server Error: Container command not found or does not exist.`. 

```
services:
  beanstalkd:
    image: schickling/beanstalkd
    environment:
      "constraint:node": "=node01"
    volumes:
      - "beanstalkd_volume:/var/lib/beanstalkd/data"
    networks:
      - backbone
    expose:
      - "11300"
    command: ["beanstalkd", "-V", "-p", "11300"]

volumes:
    beanstalkd_volume:
```

If I change the constraint to ` "constraint:node": "=node02"` the container is created. No error is displayed.

**Comment by n1t1nv3rma** [comment] 2016-04-14 08:27
Running in verbose mode (docker-compose -f test.yml -p testproj --verbose up) and looking into the (tail -f /var/log/docker.log) helps. For me the problem was entrypoint was missing.

**Comment by troef** [comment] 2016-04-14 12:43
More on the same issue, I just spend a nice amount of time debugging the `"Container command not found or does not exist." ` error message. It turned my entrypoint file contained windows line-endings. 

The problem is that the error message supplied by docker isn't informative enough in this case. The original error inside the container looked like this and is just a crucial bit more helpful:

`bash: /docker-entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory`

Before seeing this it took me lots of debugging to verify that the file was 
a: present
b: executable
c: not containing any errors (except for those freaking line endings)
d: and even more time to figure out that I has to test the file inside the container as an executable and not using a "sh" prefix.

**Solution 1**
In my case raising the original error is an option or would that lead to confusing output in other usecases? How often does this error occur? Maybe it is an option to run a few helpful checks for common causes:

- Does the entrypoint exist?
- Is it executable?
- Does it contain Windows line-endings

**Comment by jeacott1** [comment] 2016-05-16 03:00
I had this, turned out to be something messed up with -s overlay.
removed the overlay option, and the existing docker directory, restarted with aufs, all good. 
did the same thing restoring overlay, and still all good. 

so for me it was something with the overlay driver messing things up for just one image on just one box (it ran fine elsewhere, as did other images on the same box), and no amount of deleting/pulling fresh images would help, only starting fresh. 
hope this helps someone.

**Comment by gizmonicus** [comment] 2016-06-09 21:40
Not sure if this helps anyone, but I recently ran into this issue after upgrading Docker to 1.11.2, build b9f10c9. I had failed to restart the daemon after the update. Fortunately, restarting Docker was all that was required.

**Comment by albertsj1** [comment] 2016-07-05 16:34
In case anyone else hits this error message, like I did, after upgrading ubuntu to 16.04, the cause of the error for me was apparmor.  The appropriate solution would be to update the apparmor profile for docker so things work properly.  For me, on my personal server, I just disabled and deleted apparmor.

**Comment by Nathre2501** [comment] 2016-07-07 22:31
I have this problem trying to run an interpreter from PyCharm. This is the error: 

Can't run remote python interpreter: Container command 'python' not found or does not exist.

I'm using El Capitan

**Comment by thaJeztah** [comment] 2016-07-07 23:05
@Nathre2501 are you using Docker for Mac, or Docker Machine / Toolbox (VirtualBox)?

**Comment by Nathre2501** [comment] 2016-07-08 00:01
@thaJeztah i installed both, just now uninstalled both and now im trying to set it up using toolbox but i still have the same problem

**Comment by thaJeztah** [comment] 2016-07-08 00:23
@Nathre2501 what image is it running? Is `python` actually installed in the container? Or is PyCharm installing it?

**Comment by Nathre2501** [comment] 2016-07-08 15:57
@thaJeztah 
It's installed in my system and pycharm is able to list the modules inside de container. Do i necessarily need to install python in the container?

**Comment by Nathre2501** [comment] 2016-07-11 17:35
@thaJeztah The problem was that pycharm needs the project to be located in the main unit. I had the project in some other volume so it couldn't run python. Moving the project fixed the problem.

**Comment by thaJeztah** [comment] 2016-07-18 14:07
We merged a change for docker 1.12 that returns a better error message, instead of masking it as "command not found"; https://github.com/docker/docker/pull/22983/files#diff-3cb140026df40998ea29c5bcb6bb292eR150

I'm closing this issue, because this should be resolved in 1.12, but if anyone is able to give the 1.12 release candidate a spin to verify, that would be great http://github.com/docker/docker/releases

**Closed by thaJeztah** 2016-07-18 14:07 UTC
Labels: kind/enhancement, version/1.10

**Comment by jlndk** [comment] 2016-07-28 23:25
I had the same problem, but solved it by reinstalling docker-engine (if it's any help to someone)

**Comment by zotherstupidguy** [comment] 2016-08-18 13:30
Please reopen this issue i am getting `container command '/bin/sh' not found` even with `FROM ubuntu:latest `

**Comment by thaJeztah** [comment] 2016-08-18 15:14
@zotherstupidguy could you please provide some more information? Output of `docker version`, `docker info`, and steps to reproduce?

**Comment by zotherstupidguy** [comment] 2016-08-18 15:55
`Docker version 1.11.2, build b9f10c9`

`Containers: 63
 Running: 0
 Paused: 0
 Stopped: 63
Images: 144
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-254:0-1712742-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.718 GB
 Data Space Total: 107.4 GB
 Data Space Available: 16.7 GB
 Metadata Space Used: 7.483 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.133 (2016-08-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.7.0-1-ARCH
Operating System: Antergos Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.633 GiB
Name: zzz
ID: 3YXK:JET5:6GP7:BB4W:RQB2:G3TD:5AX7:OIXW:OXM6:XTDJ:XCDL:XHJI
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
`

Steps to reproduce:
- `git clone https://github.com/zotherstupidguy/airtime.git`
- `cd docker-airtime`
- `docker build -f Dockerfile -t airtime . `

**Comment by duglin** [comment] 2016-08-18 16:31
I think you meant: `https://github.com/zotherstupidguy/docker-airtime.git`.
Can you show the output of `docker history ubuntu:latest` ?

**Comment by duglin** [comment] 2016-08-18 16:34
does `docker run -ti ubuntu:latest /bin/sh` work for you?

**Comment by thaJeztah** [comment] 2016-08-18 16:50
@zotherstupidguy how did you install docker? from our apt repository, or from packages provided by Antergos Linux? I noticed the kernel version says `-arch`; is Antergos based on Arch linux? I recently saw a discussion that 1.11.2 doesn't work on recent versions or Arch, and upgrading to 1.12 fixed that

**Comment by zotherstupidguy** [comment] 2016-08-18 17:34
@thaJeztah Yes Antergos is Arch-based distro; sorry but i really don't remember much about the setup as this was some time ago, and it was working perfectly before!  shall look into reinstalling or upgrading and report!

**Comment by zotherstupidguy** [comment] 2016-08-19 07:26
I did the following to reinstall docker on Arch-linux and remove that error, got another error from the image but I think it is image specific not related to this issue.

- `sudo pacman -Rns docker`
- `sudo pacman -S docker`

**Comment by Mangirdaz** [comment] 2016-08-20 15:25
Had same failure IF:
```
CMD ["/main -runmode server"]
```
Else for success: 
```
CMD ["/main"]
```
all works just fine.  Suspect some parsing "magic".

**Comment by duglin** [comment] 2016-08-20 15:27
`CMD ["/main -runmode server"]` isn't valid unless your exe is called `main -runmode server` - which I doubt.

**Comment by Mangirdaz** [comment] 2016-08-20 15:38
By bad. Copy paste.

**Comment by adolphlwq** [comment] 2016-09-01 10:40
+1
- docker version
```
docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

- docker info
```
Containers: 38
 Running: 6
 Paused: 0
 Stopped: 32
Images: 53
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-8:1-234881221-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 32.89 GB
 Data Space Total: 107.4 GB
 Data Space Available: 68.8 GB
 Metadata Space Used: 43.63 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.104 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm$no_warn_on_loop_devices=true` to suppress this warning.
Metadata Space Available: 2.104 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: e5876c17-8860-48d8-9742-cfea5e952642.bigdata.sysadmin
ID: I7DX:J6UJ:5N3J:S5MV:XB2H:HPW7:Q3R3:RZTY:LR63:CK6A:H4UK:6SAX
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 slave=true
 LINKER_MESOS_ATTRIBUTE=lb:enable
 provider=generic
Cluster store: zk://10.140.0.14:2181
Cluster advertise: 10.140.0.15:2376
```

- error info when start cadvisor
```
sudo docker run \
>   --volume=/:/rootfs:ro \
>   --volume=/var/run:/var/run:rw \
>   --volume=/sys:/sys:ro \
>   --volume=/var/lib/docker/:/var/lib/docker:ro \
>   --publish=8080:8080 \
>   --detach=true \
>   --name=cadvisor \
>   google/cadvisor:latest
c698691a1995a208d238875a9e3b8a751634ba4a6633581b5a6fd25e02d4266e
docker: Error response from daemon: Container command '/usr/bin/cadvisor' not found or does not exist..
```

**Comment by vnalla** [comment] 2017-03-28 18:23
I have the same problem, and could not find any solution yet. The run.sh script included in Dockefile is not getting executed when the container started all three of the following has the issue:

- CMD ["./run.sh"]
- CMD ["run.sh"]
- CMD ["/opt/myapp/run.sh"]

**docker run -it --name test1 test:1.0**
time="2017-03-28T14:20:07-04:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Container command '/opt/myapp/run.sh' not found
or does not exist..

** docker info**
time="2017-03-28T14:15:48-04:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Containers: 21
 Running: 10
 Paused: 0
 Stopped: 11
Images: 20
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Init Binary:
containerd version:
runc version:
init version:
Kernel Version: 4.7.2
Operating System: Buildroot 2016.08
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: minikube
ID: CLUS:65CW:5GME:SKDK:KM4Y:2QIB:CUDE:NVRW:ZOZU:5ECA:G4PI:SLN2
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://one.proxy.att.com:8080
Https Proxy: http://one.proxy.att.com:8080
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 192.168.99.100:5000
 127.0.0.0/8
Live Restore Enabled: false

**docker version**
time="2017-03-28T14:17:46-04:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Client:
 Version:      17.03.0-ce
 API version:  1.23
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Mar  2 01:11:00 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.1
 API version:  1.23 (minimum version )
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
 Experimental: false

**Dockerfile**
FROM java:8
RUN mkdir /opt/myapp
COPY ./run.sh /opt/myapp/
COPY ./e911test.jar /opt/myapp/
WORKDIR /opt/myapp/
RUN chmod +x ./run.sh
CMD ["/opt/myapp/run.sh"]

**run.sh**
#!/bin/sh

java -version

**Comment by thaJeztah** [comment] 2017-03-28 18:59
@vnalla given that you're on Windows, make sure that the script has the right (Linux) line endings; if it's using Windows line endings, Linux will give a cryptic error message (like the one you got)

**Comment by vnalla** [comment] 2017-03-28 20:07
I have edited that file in CentOS VM. Here is od -c run.sh output:

[vn2158@njcdtl01vn2158 docker-images]$ od -c run.sh
0000000   #   !   /   b   i   n   /   s   h  \r  \n  \r  \n   j   a   v
0000020   a       -   v   e   r   s   i   o   n  \r  \n  \r  \n  \r  \n
0000040

**Comment by thaJeztah** [comment] 2017-03-28 20:24
Yup, the one that doesn't work has `\r\n` (Windows line endings). If you run that on any Linux machine, it will say "command not found" (also if it's not in a docker container)
