### ISSUE TITLE
docker run failed: Error response from daemon: unexpected end of JSON input

### ISSUE THREAD

**Issue by phuongnd08** [docker/docker#10553] opened 2015-02-04 13:02 UTC
I tried some clean up on a machine in our CoreOS cluster by 
```
docker rmi $(docker images -q --filter "dangling=true")
docker rm `docker ps --no-trunc -aq`
```
(Running docker 1.3.3)

After that running new container throwing this:
```
$ docker run busybox
2015/02/04 13:00:08 Error response from daemon: unexpected end of JSON input
```

Thoughts?

**Comment by phuongnd08** [comment] 2015-02-05 05:24
Reboot solves my problem. Holy!

**Comment by phuongnd08** [comment] 2015-02-05 15:23
Now restarted server and get this:

```
$ sudo /usr/bin/docker --daemon --storage-driver=btrfs --host=fd:// $DOCKER_OPTS
2015/02/05 15:19:18 docker daemon: 1.3.3 54d900a; execdriver: native; graphdriver: btrfs
[a4411f84] +job serveapi(fd://)
2015/02/05 15:19:18 Couldn't create Tag store: unexpected end of JSON input
```

What should I do?

**Comment by phuongnd08** [comment] 2015-02-05 16:44
Remove `/var/lib/docker/repositories-btrfs` seems to fix the problem for me now.

**Comment by tiborvass** [comment] 2015-02-07 22:09
@phuongnd08 would you mind trying with docker 1.4.1 ? https://get.docker.com/builds/Linux/x86_64/docker-1.4.1

I'm closing it for now, because I believe this was fixed. If you still see this with 1.4.1 let us know in the comments and we'll reopen the issue.

**Closed by tiborvass** 2015-02-07 22:09 UTC

**Comment by muuki88** [comment] 2015-02-17 11:53
I had a similar issue. My computer crash during a build. I removed

```bash
sudo su
cd /var/lib/docker
rm -rf graph/
rm -rf trust/official.json
rm -rf volumes/
rm -rf containers/
rm -rf aufs/layers/
```

one of them did the trick.

**Comment by balboah** [comment] 2015-03-20 08:13
Time to open this ticket again.

```
Mar 20 08:12:15 ip-10-0-3-20.eu-west-1.compute.internal dockerd[980]: time="2015-03-20T08:12:15Z" level="info" msg="+job serveapi(fd:
Mar 20 08:12:15 ip-10-0-3-20.eu-west-1.compute.internal dockerd[980]: time="2015-03-20T08:12:15Z" level="fatal" msg="Couldn't create
Mar 20 08:12:15 ip-10-0-3-20.eu-west-1.compute.internal systemd[1]: docker.service: main process exited, code=exited, status=1/FAILUR
Mar 20 08:12:15 ip-10-0-3-20.eu-west-1.compute.internal systemd[1]: Unit docker.service entered failed state.
```

```
docker -v
Docker version 1.5.0, build a8a31ef-dirty
```

CoreOS "stable"

**Comment by balboah** [comment] 2015-03-20 08:21
Oh and doing what @phuongnd08 said made docker start properly again.
`rm -rf /var/lib/docker/repositories-btrfs`

**Comment by hyperbolic2346** [comment] 2015-06-04 23:24
I just hit this as well:
```
docker --version
Docker version 1.6.2, build 7c8fca2-dirty
```

**Comment by srobertson** [comment] 2015-06-08 23:18
Same
docker -v
Docker version 1.6.0, build 4749651

**Comment by srobertson** [comment] 2015-06-08 23:18
```
docker -v
Docker version 1.6.0, build 4749651
```

**Comment by andrewmichaelsmith** [comment] 2015-06-09 18:24
Hit this

$ docker -v
Docker version 1.6.2, build 7c8fca2

Our /var/lib/docker partition filled up. Restarting docker gave the "unexpected end of JSON input" error and @phuongnd08's fix of deleting `/var/lib/docker/repositories-btrfs ` did the trick.

**Comment by stapelberg** [comment] 2015-10-27 19:04
Hit the same issue when the VM’s disk was full. A better error message would be appreciated.

**Comment by kopax** [comment] 2015-10-29 03:06
Hit the same issue when the VM's disk was full.

Docker version 1.8.2, build 0a8c2e3

**Comment by willberriss** [comment] 2015-11-10 20:12
When I ended up getting this error message (after a docker run failed badly)
    Error response from daemon: EOF

The fix was similar to the above, it was to do this:
    service docker stop
    rm /var/lib/docker/repositories-devicemapper
    service docker start

It's happy again now :)

**Comment by MrMMorris** [comment] 2016-02-11 20:37
getting this constantly with 1.6.2.

removing `/var/lib/docker/repositories-aufs` fixes it, but it keeps cropping up. 

@tiborvass is someone looking into this? I am upgrading to 1.9.1 soon, but I want to make sure this has a fix already.

**Comment by tiborvass** [comment] 2016-02-11 21:06
@MrMMorris feel free to open a new issue with daemon logs and ways to reproduce.

**Comment by esnunes** [comment] 2016-03-03 13:14
I got the same error today, I fixed it removing `/var/lib/docker/repositories-btrfs` however before doing that I've identified that this file was empty, for some weird reason this file got empty and this was causing the issue

**Comment by vorakl** [comment] 2016-04-08 09:58
I had the same issue and fixed in the same way! The version of Docker was 1.8.3 and a storage driver - overlay. So, I removed an empty file /var/lib/docker/repositories-overlay

**Comment by rippinrobr** [comment] 2016-04-26 23:29
Docker wouldn't restart - saw this in the log file

time="2016-04-26T23:18:07.693559169Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
time="2016-04-26T23:18:07.720426991Z" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
time="2016-04-26T23:18:07.756221100Z" level=fatal msg="Error starting daemon: Couldn't create Tag store: `EOF"`

Docker version 1.7.1, build 786b29d/1.7.1

rm /var/lib/docker/devicemapper

and that did the trick

**Comment by Vanuan** [comment] 2016-11-24 14:54
Removing repositories-devicemapper file did the trick. This happened when disk run out of space.

**Comment by symantec-shailendersingh** [comment] 2018-12-21 13:35
I faced same issue on Centos with old kernel and it got fixed after deleting
rm /var/lib/docker/repositories-devicemapper
