### ISSUE TITLE
File descriptor leak when mounting OS X directories in containers (Docker for Mac)

### ISSUE THREAD

**Issue by GuillaumeDerval** [docker/docker#25079] opened 2016-07-26 17:05 UTC
When creating a lot of containers, OS X eventually starts to complain about errors with FDs: "too many open files in system".

It seems that when a file located on the OS X filesystem is open via a bind mount in a container (so, through osxfuse), a particular FD is opened, but never closed. 

Moreover, if multiple containers open the same file, multiple FDs will be used.

The issue is particularly problematic when using long OS X file path, as one FD is created for each directory on the path.

Example 1: FD leak
==============

Let's create a very long filepath, with a file inside, and mount it in a container
```bash
#! /bin/bash

demopath="demo/1/2/3/4/5/6/7/8/9"
mkdir -p $demopath
cd $demopath
echo 1 > demo
docker run -ti --rm -v `pwd`/demo:/demo centos cat /demo
docker run -ti --rm -v `pwd`/demo:/demo centos cat /demo # second time to show duplicates
```
Now, in the output of `lsof -n`:
```
[...]
com.docke 17689 dervalguillaume   21r     REG                1,4          2 69609670 /Users/dervalguillaume/demo/1/2/3/4/5/6/7/8/9/demo
com.docke 17689 dervalguillaume   22r     DIR                1,4        102 69609667 /Users/dervalguillaume/demo/1/2/3/4/5/6/7/8/9
com.docke 17689 dervalguillaume   23r     DIR                1,4        102 69609666 /Users/dervalguillaume/demo/1/2/3/4/5/6/7/8
com.docke 17689 dervalguillaume   24r     DIR                1,4        102 69609665 /Users/dervalguillaume/demo/1/2/3/4/5/6/7
com.docke 17689 dervalguillaume   25r     DIR                1,4        102 69609664 /Users/dervalguillaume/demo/1/2/3/4/5/6
com.docke 17689 dervalguillaume   26r     DIR                1,4        102 69609663 /Users/dervalguillaume/demo/1/2/3/4/5
com.docke 17689 dervalguillaume   27r     DIR                1,4        102 69609662 /Users/dervalguillaume/demo/1/2/3/4
com.docke 17689 dervalguillaume   28r     DIR                1,4        102 69609661 /Users/dervalguillaume/demo/1/2/3
com.docke 17689 dervalguillaume   29r     DIR                1,4        102 69609660 /Users/dervalguillaume/demo/1/2
com.docke 17689 dervalguillaume   30r     DIR                1,4        102 69609659 /Users/dervalguillaume/demo/1
com.docke 17689 dervalguillaume   31r     DIR                1,4        102 69609658 /Users/dervalguillaume/demo
com.docke 17689 dervalguillaume   32r     DIR                1,4       5100   603949 /Users/dervalguillaume
com.docke 17689 dervalguillaume   33r     DIR                1,4        204   157433 /Users
[...]
com.docke 17689 dervalguillaume   35r     REG                1,4          2 69609670 /Users/dervalguillaume/demo/1/2/3/4/5/6/7/8/9/demo
com.docke 17689 dervalguillaume   36r     DIR                1,4        102 69609667 /Users/dervalguillaume/demo/1/2/3/4/5/6/7/8/9
com.docke 17689 dervalguillaume   37r     DIR                1,4        102 69609666 /Users/dervalguillaume/demo/1/2/3/4/5/6/7/8
com.docke 17689 dervalguillaume   38r     DIR                1,4        102 69609665 /Users/dervalguillaume/demo/1/2/3/4/5/6/7
com.docke 17689 dervalguillaume   39r     DIR                1,4        102 69609664 /Users/dervalguillaume/demo/1/2/3/4/5/6
com.docke 17689 dervalguillaume   40r     DIR                1,4        102 69609663 /Users/dervalguillaume/demo/1/2/3/4/5
com.docke 17689 dervalguillaume   41r     DIR                1,4        102 69609662 /Users/dervalguillaume/demo/1/2/3/4
com.docke 17689 dervalguillaume   42r     DIR                1,4        102 69609661 /Users/dervalguillaume/demo/1/2/3
com.docke 17689 dervalguillaume   43r     DIR                1,4        102 69609660 /Users/dervalguillaume/demo/1/2
com.docke 17689 dervalguillaume   44r     DIR                1,4        102 69609659 /Users/dervalguillaume/demo/1
com.docke 17689 dervalguillaume   45r     DIR                1,4        102 69609658 /Users/dervalguillaume/demo
com.docke 17689 dervalguillaume   46r     DIR                1,4       5100   603949 /Users/dervalguillaume
com.docke 17689 dervalguillaume   47r     DIR                1,4        204   157433 /Users
[...]
``` 

Example 2 Too many open files
========
Copy-paste and enjoy (OS X do not like this at all, you've been warned ;-) )
```bash
#! /bin/bash

# create a very long path to speedup the process
demopath="demo/1/2/3/4/5/6/7/8/9/0/1/2/3/4/5/6/7/8/9/0/1/2/3/4/5/6/7/8/9/0/1/2/3/4/5/6/7/8/9"
mkdir -p $demopath
cd $demopath

# make sure it breaks
for i in {1..1000}
do
  echo '-----'
  echo $i > $i
  # run the container
  docker run -ti --rm -v `pwd`/$i:/demo centos cat /demo
  # then show the number of FD opened by Docker for Mac
  lsof -n | grep dock | wc -l
done
```

Expected output:
```
-----
1
     272
-----
2
     316
-----
3
     359
-----
4
     403
[................]
-----
168
    7450
-----
169
    7493
-----
170
    7536
-----
docker: Error response from daemon: dial unix /Users/dervalguillaume/Library/Containers/com.docker.docker/Data/*00000003.00000948: socket: too many open files in system.
Error response from daemon: dial unix /Users/dervalguillaume/Library/Containers/com.docker.docker/Data/*00000003.00000948: socket: too many open files in system
zsh: pipe failed: too many open files in system
VCS_INFO_realpath:7: pipe failed: too many open files in system
prompt_status:5: pipe failed: too many open files in system
```

Sometimes, the docker process restarts, and sometimes not.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 59
 Running: 0
 Paused: 0
 Stopped: 59
Images: 155
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 270
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 5
Total Memory: 1.954 GiB
Name: moby
ID: JFFG:F45W:YXSV:5PGY:7DHD:74A7:Y37E:URMN:FYQC:P2NX:DWIW:T34U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2016-07-26T16:34:09.381432547Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

I'm on the latest version of OS X (10.11.6).

**Comment by cpuguy83** [comment] 2016-07-26 17:12
ping @dsheets

**Comment by dsheets** [comment] 2016-07-26 17:14
I can confirm, this is a known issue. I believe that the cause is that the Linux VFS is slow to release directory nodes and we retain a directory fd for each active directory node. The fix is to cache directory entries in the server and not keep an fd open in OS X for active directory nodes. This is a high priority defect. Thanks for reporting it!

**Comment by Plippe** [comment] 2016-08-11 09:39
For anyone blocked by this issue, here is a [temporary / hacky fix][1]. 

[1]: https://gist.github.com/Plippe/f7f140608aec139a8c3bb40cf46059a9

**Comment by dsheets** [comment] 2016-08-17 11:12
Beta 23 has now been released which should fix this issue.

**Comment by thaJeztah** [comment] 2016-09-27 22:21
closing, as this should be fixed

**Closed by thaJeztah** 2016-09-27 22:21 UTC
Labels: platform/desktop, version/1.12
