### ISSUE TITLE
Docker on Ubuntu 14, just can't get it up and running

### ISSUE THREAD

**Issue by jeroenjacobs1205** [docker/docker#14732] opened 2015-07-18 21:30 UTC
Hello everyone,

After trying to get Docker up and running for more than # hours, I am throwing in the towel. I really tried everything now, but I assume I've hit some weird kind of bug, as no amount of googling and troubleshooting was able to save the day (or my sanity).

uname -r : 3.13.0-57-generic

docker version: 1.6.2, build 7c8fca2

docker info:

Containers: 1
Images: 22
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 24
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: docker01
ID: X6JB:IH7Z:OK5O:II5I:OJ6V:OERE:IPEM:PN6S:HDDM:G2J7:HRB2:4ZKO
WARNING: No swap limit support

Every time I try to run a container, I'm greeted with the following message:

FATA[0025] Error response from daemon: Cannot start container 35025befefbb3a6425497c32a5bfe4f001132b2c283b92ff777ef40a7079eff4: [8] System error: invalid argument

Docker was installed from the official docker.io repos. I installed 1.6.2, as the 1.7 branch causes even more issues for Ubuntu users, if I can believe everything I've read so far.

**Comment by jeroenjacobs1205** [comment] 2015-07-18 21:49
docker version => provided in ticket
docker info => provided in ticket
uname -a : Linux docker01 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Hypervisor: VMWare ESX 5.5

steps to reproduce the problem:

sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
sudo sh -c "echo deb http://get.docker.io/ubuntu docker main\ > /etc/apt/sources.list.d/docker.list"
sudo aptitude update
sudo apt-get install lxc-docker-1.6.2
<rebooted server here just to be sure>
sudo docker run -d hello-world

Then got error:

FATA[0003] Error response from daemon: Cannot start container e9a207258b7a80a8db8a9001783432f548b55fabee5da2fe0814caf9f3f52c79: [8] System error: invalid argument

**Comment by rtrauntvein** [comment] 2015-07-20 23:45
Hi @jeroenjacobs1205 - Sorry you are have having difficulty getting started with Docker.

What does running: `docker run hello-world` produce? (remove the -d flag)

**Comment by jeroenjacobs1205** [comment] 2015-07-21 10:52
Hi,

Thanks for responding. It has the same result :

    jeroen@docker01:~$ docker run hello-world
    invalid argument
    FATA[0000] Error response from daemon: Cannot start container a0a32d129a8a3c2b056c3f951b159d80c1a65d84421c9e0ba3529646c0facd99: [8] System error: invalid argument

**Comment by thaJeztah** [comment] 2015-08-04 23:23
@jeroenjacobs1205 just informing if you managed to resolve this issue, or still have this problem.

If you're still having this problem, could you download and run the [contrib/check-config.sh](https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh) script, to check if something is missing on your host.

Also, we recently installed official APT and YUM repos, which install a dynamically linked docker binary, this may resolve some issue. Information on this can be found in the blog post here; https://blog.docker.com/2015/07/new-apt-and-yum-repos/

**Comment by jeroenjacobs1205** [comment] 2015-08-17 13:43
Hi,

I tried the new packages, but now I get another error:

    jeroen@docker01:~$ sudo docker run hello-world
    Error response from daemon: Cannot start container 1b0ddaf70ea98f8cb43093b329a53e9e92e5f1292ea56f393c98a98d2f8bf3af: failed sandbox add: failed to set gateway while updating gateway: invalid argument

**Comment by jeroenjacobs1205** [comment] 2015-08-17 13:48
And this is the output of the check-config script:
```
jeroen@docker01:~$ sudo ./check.sh
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-3.13.0-57-generic ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: missing
    (note that cgroup swap accounting is not enabled in your kernel config, you can enable it by setting boot option "swapaccount=1")
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_NETPRIO_CGROUP: enabled (as module)
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled (as module)
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing
```

**Comment by thaJeztah** [comment] 2015-08-17 14:37
Thanks! Could you also provide updated information output of `docker version` and `docker info` (just in case it's needed)

The `failed sandbox add: failed to set gateway while updating gateway: invalid argument` looks to come from here; [libnetwork/sandboxdata.go](https://github.com/docker/docker/blob/9e9f3aa36b5286556c8f99557d8bcc66946598d3/vendor/src/github.com/docker/libnetwork/sandboxdata.go#L64-L66), which is part of libnetwork.

I'll ask @mavenugo or @mrjana to have a quick look for suggestions, they're probably faster to track this down than I am :smile:

ping @mavenugo @mrjana if you have time, could you have a look?

**Comment by jeroenjacobs1205** [comment] 2015-08-19 09:24
As requested:

    jeroen@docker01:~$ docker --version
    Docker version 1.8.1, build d12ea79

and docker info:

```
jeroen@docker01:~$ docker info
Containers: 1
Images: 2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: docker01
ID: X6JB:IH7Z:OK5O:II5I:OJ6V:OERE:IPEM:PN6S:HDDM:G2J7:HRB2:4ZKO
WARNING: No swap limit support
```

**Comment by jeroenjacobs1205** [comment] 2015-08-19 09:26
And the output of ifconfig, in case you need that too:

```
jeroen@docker01:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:b0:fa:42:f7
          inet addr:192.168.11.0  Bcast:0.0.0.0  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 00:0c:29:86:01:ef
          inet addr:192.168.10.21  Bcast:192.168.10.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fe86:1ef/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1028050 errors:0 dropped:0 overruns:0 frame:0
          TX packets:866808 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:348146482 (348.1 MB)  TX bytes:174566022 (174.5 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Comment by mavenugo** [comment] 2015-08-19 10:09
@jeroenjacobs1205  trying to understand the issue. You were trying Docker 1.6.2 and 1.8.1, and you were running into problems on both version. Both are triggered by the `invalid argument` errors (possibly from netlink).

Can you please share your docker daemon config ?

Also, we identified a netlink library issue recently, which got resolved few days ago and the fix for it is still in master & targeted for 1.8.2. https://github.com/docker/docker/pull/15601. Can you try a docker build from the master ? https://master.dockerproject.org/ and confirm if you still see this issue ?

**Comment by timothysparg** [comment] 2015-10-15 21:20
Hi all

I've also run into this problem. What I did notice is that like @jeroenjacobs1205  I have changed the netowork that the `docker0` interface listens to.

In my case I used `DOCKER_OPTS="--bip=192.168.0.0/24"` in the `etc/default/docker` file

The moment I commented out the `DOCKER_OPTS` , and the network reverted to the `172.17.42.1` IP the hello-world sample started working again.

 `Docker version 1.8.3, build f4bf5c7`

**Comment by timothysparg** [comment] 2015-10-17 10:34
As a follow up to the above,  although the Hello-world sample now worked, I was not able to connect to any apps running within the container. 
So I could get [Jenkins](https://hub.docker.com/_/jenkins/) up and running but couldn't connect to it on port 8080

My workaround was to follow the [Bridge building](https://docs.docker.com/articles/networking/#bridge-building) docs in Docker, and now I can connect to apps running with the container

**Comment by cpuguy83** [comment] 2015-10-17 11:45
@timothysparg The issue is here that you can't use `0` as the last octet as it will try to set that as the IP address of the bridge.
This should be (probably) `--bip 192.168.0.1/24`

@jeroenjacobs1205 this looks like your issue as well. Notice the IP address of docker0 is set to a `.0` which is indeed invalid.

Closing since this seems to be the issue.
Please update your `-bip`'s to not use `.0` and test again, I believe this will resolve the problem.
If not ping here.

Thanks!

**Closed by cpuguy83** 2015-10-17 11:45 UTC

**Comment by timothysparg** [comment] 2015-10-17 12:39
Urgh that seems painfully obvious now. I deleted the bridge that I'd manually created and set `bip` as you suggested and Voila. 

Thanks for the assistance, hopefully somebody else will find this useful

**Comment by dhasenancyngn** [comment] 2016-08-04 18:19
I spent a fair bit of time tracking down this problem myself. Can this have a better error message than "System error: invalid argument" ?
