### ISSUE TITLE
Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows

### ISSUE THREAD

**Issue by Neelerak** [docker/docker#31457] opened 2017-03-01 16:10 UTC
**Resubmitting:**
https://github.com/docker/for-win/issues/422

This issue was a problem with Go and should be resolved as of 14 days ago, any chance to get a hotfix?

https://github.com/golang/go/issues/16736

**Comment by justincormack** [comment] 2017-03-01 23:02
@Neelerak the issue has not been resolved in Go, the fix was reverted and the issue is still in Go 1.8 apparently, according to the issue you linked to.

**Comment by thaJeztah** [comment] 2017-03-02 00:48
We're currently tracking this message through https://github.com/docker/docker/issues/30450, so let me close this one to keep the discussion in a single place

**Closed by thaJeztah** 2017-03-02 00:48 UTC
