### ISSUE TITLE
bind: address already in use in 1.5.0

### ISSUE THREAD

**Issue by citywander** [docker/docker#12144] opened 2015-04-07 15:08 UTC
Just single thread, and docker version is 1.5.0, OS: ubuntu 14.04.01
We have applied docker to Test Environment.
For every test, system will request VM, The VM is restored from vmware snapshot, so it was sure that every test run in the same environment. But we found sometimes error is thrown: Can not start docker container: 500 Server Error: Internal Server Error ("Cannot start container 4811691c18f03d2da63b5cfaa79921aba74eba4e8800eede77a3f635a7eba086: Error starting userland proxy: listen tcp 0.0.0.0:49197: bind: address already in us. Then retry, but error again.
Everyone know why?
We have used docker on production.

**Comment by thaJeztah** [comment] 2015-04-08 19:13
Hi @citywander, thanks for reporting this, but I think this is a duplicate of https://github.com/docker/docker/issues/9047. I'll close this issue, if you have additional information, please add this to https://github.com/docker/docker/issues/9047.

**Closed by thaJeztah** 2015-04-08 19:13 UTC
