### ISSUE TITLE
running docker overwrites host machine /etc/hosts to point to 172.17.0.1 on OEL6u7

### ISSUE THREAD

**Issue by AnishKhandelwal06** [docker/docker#22224] opened 2016-04-21 11:04 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 16:08:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 16:08:02 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 1.10.3
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.12-32.2.3.el6uek.x86_64
Operating System: Oracle Linux Server 6.7
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.09 GiB
Name: den00oxl
ID: Y3IT:UOME:VXII:SABF:AZNH:N7OD:XOH4:JLFM:DVM4:LAG5:LC4K:24UL
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OEL6 update 7

**Steps to reproduce the issue:**
1. Install docker engine and start docker service
2. run some docker commands like docker pull etc.
3. check the host machine /etc/hosts file
It gets modified to point to 172.17.0.1

**Describe the results you received:**
127.0.0.1       localhost.localdomain   loghost localhost
172.17.0.1      den00oxl.us.oracle.com  den00oxl

**Describe the results you expected:**
127.0.0.1       localhost.localdomain   loghost localhost
10.196.13.244      den00oxl.us.oracle.com  den00oxl

**Additional information you deem important (e.g. issue happens only occasionally):**
Even if I update /etc/hosts to point to actual ip, it gets update after a while

**Comment by thaJeztah** [comment] 2016-04-21 13:08
ping @Djelibeybi any ideas? Possibly this is related to https://github.com/docker/docker/issues/10216, which (I think) was due to an old version of BTRFS being used to initialize BTRFS

**Comment by Djelibeybi** [comment] 2016-04-21 20:42
I'm not sure #10216 is related, because this machine is running a 4.1.12 kernel, which has a fairly modern btrfs codebase. However, I also have no idea. 

Though, I notice that the user is using one of our internal Oracle hostnames, so I'd also suggest they open an internal bug for this. That way, we can investigate internally as well.

**Comment by thaJeztah** [comment] 2016-04-21 20:47
@Djelibeybi it's still possible if an old version of btrfs was used during creation, and the kernel updated afterwards

**Comment by Djelibeybi** [comment] 2016-04-21 20:52
@thaJeztah perhaps, though even our UEK3 has a more modern version of `btrfs` than referenced in that other issue. I've sent some internal mails to see if we can reproduce it internally.

**Comment by thaJeztah** [comment] 2016-04-21 20:58
@Djelibeybi thanks!

**Comment by phemmer** [comment] 2016-04-22 00:13
> Even if I update /etc/hosts to point to actual ip, it gets update after a while

This smells like NetworkManager. I think it unlikely that docker is the culprit here. Especially if it changes without you doing anything with docker (starting/stopping containers).

I'd take a look at the mtime of the file, and then look through your logs, and see what was happening at the exact time the file was modified.

**Comment by thaJeztah** [comment] 2016-11-30 15:49
This looks to be something external to docker indeed; each container gets it's own `/etc/hosts`, and does not share with the host. I'll close this issue, because this does not look like a bug in docker, but perhaps @phemmer's suggestion helps you further

**Closed by thaJeztah** 2016-11-30 15:49 UTC
Labels: version/1.10
