### ISSUE TITLE
Have Docker check iptables for return code and retry

### ISSUE THREAD

**Issue by jeid64** [docker/docker#30379] opened 2017-01-23 22:07 UTC
**Description**

Iptables can return "Resource temporarily unavailable.\n (exit status 4)" when it receives an EAGAIN from the kernel, mostly from concurrency issues of multiple iptables processes attempting to alter the table. The Docker daemon should check the return code and if it's 4, retry the iptables command again. 

**Steps to reproduce the issue:**
1. Start up a privileged container
2. Inside of it, make a while loop of executing any iptables add or drop rule repeatedly.
3. Instruct Docker daemon to start or stop a container that has a port mapping

**Describe the results you received:**
msg="Error on iptables delete: iptables failed: iptables --wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.4 --dport 80 -j ACCEPT: iptables: Resource temporarily unavailable.\n (exit status 4)"

**Describe the results you expected:**
Docker daemon should see the return code of 4 and retry deleting/adding the iptables rule.

**Additional information you deem important (e.g. issue happens only occasionally):**
Iptables binaries on the host have a lock that they try to get (/run/xtables.lock or a unix socket) and will wait until it's grabbed. However, inside of a container that lock will be different, so iptables on the host and the container will both attempt to run at the same time, causing this issue.
https://patchwork.ozlabs.org/patch/287955/
^ shows that iptables should return exit code 4 to indicate when an EAGAIN is returned by the kernel.

**Output of `docker version`:**

```
core@ip-10-0-4-216 ~ $ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   3cd164c
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   3cd164c
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 12
 Running: 11
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.3-coreos
Operating System: CoreOS 1068.9.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: ip-10-0-4-216.us-west-2.compute.internal
ID: KM3E:O5RO:B7FD:JB5L:AU4L:5QAM:LN2N:BRXM:L4YC:HF4E:3G7O:LES3
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by fntlnz** [comment] 2017-01-23 23:00
Closing as duplicate of https://github.com/docker/docker/issues/12547
Please feel free to continue the discussion there, this bug needs some love to get fixed

**Closed by fntlnz** 2017-01-23 23:00 UTC
Labels: version/1.10
