### ISSUE TITLE
prune commands defaults don't work

### ISSUE THREAD

**Issue by mmlb** [docker/docker#31297] opened 2017-02-23 17:51 UTC
**Description**

Running `docker image prune` and `docker container prune` and just pressing enter at the prompt `... continue? [y/N]` does nothing. Presumably the default `N` should be selected and nothing happens. Instead it seems as if the cli is waiting for an actual character to by typed, without prompting again.

**Steps to reproduce the issue:**
1. run `docker image prune`
2. press the enter key
3. nothing happens

**Describe the results you received:**
docker prune command seemed to just hang.

**Describe the results you expected:**
I expected to either be prompted again (possibly with a message), or for the command to return as if I had typed `N` or any other character but `y`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
❯ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3727
 Built:        Sun Feb 12 02:40:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3727
 Built:        Sun Feb 12 02:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false  
```

**Output of `docker info`:**

```
❯ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 27
Server Version: 1.13.1
Storage Driver: zfs
 Zpool: error while getting pool information strconv.ParseUint: parsing "": inval
id syntax
 Zpool Health: not available
 Parent Dataset: zroot/docker
 Space Used By Parent: 90112
 Space Available: 150361333760
 Parent Quota: no
 Compression: lz4
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.17 GiB
Name: manny
ID: NUPW:OELY:QYZZ:OVHQ:QLUK:MY5Z:K5TE:FCCI:2JM5:LUQG:GDTM:XUQV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false  
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-02-24 14:20
Thanks for reporting! This is a duplicate of https://github.com/docker/docker/issues/31187, and already fixed on "master" through https://github.com/docker/docker/pull/30769, but that fix is not her in a release.

I'll close this issue because of that, but feel free to continue the conversation

**Closed by thaJeztah** 2017-02-24 14:20 UTC
Labels: area/cli, kind/bug, version/1.13
