### ISSUE TITLE
internal Additional property internal is not allowed (docker stack deploy with compose v3 file)

### ISSUE THREAD

**Issue by hairyhenderson** [docker/docker#30284] opened 2017-01-19 16:58 UTC
**Description**

The `internal` key doesn't seem to work when creating a network with `docker stack deploy` and a docker-compose file (v3 format).

**Steps to reproduce the issue:**
1. create a `docker-compose.yml` file with this content:
```yaml
version: '3.0'

networks:
  foo:
    driver: overlay
    internal: true
```
2. deploy it:
```console
$ docker stack deploy -c docker-compose.yml foo
```
3. watch it fail 💥:
```console
$ docker stack deploy -c docker-compose.yml foo
internal Additional property internal is not allowed
```

**Describe the results you received:**

(see above)

**Describe the results you expected:**

An internal network to be created :)

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.13.0-rc7
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc7
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 606
Server Version: 1.13.0-rc7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 62ji4rbm9cp6lluyrz7acl00y
 Is Manager: true
 ClusterID: ap5aksi3rjbalc5zvhrut4rf7
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.3-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: 5OHX:44FP:GRVY:CK7Y:J7R5:P7YY:YMZB:JN4G:HN2G:IWIE:L742:SHNP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 67
 Goroutines: 353
 System Time: 2017-01-19T16:56:58.766066099Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Username: hairyhenderson
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for Mac 1.13.0-rc7-beta37 (15013)

**Comment by hairyhenderson** [comment] 2017-01-19 16:59
Note: this is similar to docker/docker#30191, but for a different property.

**Comment by mvdstam** [comment] 2017-01-20 08:24
@hairyhenderson I have the same issue with the keys `mode` and `placement`.

**Comment by thaJeztah** [comment] 2017-01-20 09:39
It seems to not be part of the 3.0 schema; comparing the json-schema for 2.1 and 3.0;

```patch
diff --git a/config_schema_v2.1.json b/config_schema_v3.0_2.json
index 7a05156..817a7df 100644
--- a/config_schema_v2.1.json
+++ b/config_schema_v3.0_2.json
@@ -1,7 +1,8 @@
 {
   "$schema": "http://json-schema.org/draft-04/schema#",
-  "id": "config_schema_v2.1.json",
+  "id": "config_schema_v3.0.json",
   "type": "object",
+  "required": ["version"],
 
   "properties": {
     "version": {
@@ -50,6 +51,7 @@
       "type": "object",
 
       "properties": {
+        "deploy": {"$ref": "#/definitions/deployment"},
         "build": {
           "oneOf": [
             {"type": "string"},
@@ -74,31 +76,7 @@
           ]
         },
         "container_name": {"type": "string"},
-        "cpu_shares": {"type": ["number", "string"]},
-        "cpu_quota": {"type": ["number", "string"]},
-        "cpuset": {"type": "string"},
-        "depends_on": {
-          "oneOf": [
-            {"$ref": "#/definitions/list_of_strings"},
-            {
-              "type": "object",
-              "additionalProperties": false,
-              "patternProperties": {
-                "^[a-zA-Z0-9._-]+$": {
-                  "type": "object",
-                  "additionalProperties": false,
-                  "properties": {
-                    "condition": {
-                      "type": "string",
-                      "enum": ["service_started", "service_healthy"]
-                    }
-                  },
-                  "required": ["condition"]
-                }
-              }
-            }
-          ]
-        },
+        "depends_on": {"$ref": "#/definitions/list_of_strings"},
         "devices": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
         "dns": {"$ref": "#/definitions/string_or_list"},
         "dns_search": {"$ref": "#/definitions/string_or_list"},
@@ -121,31 +99,12 @@
           "uniqueItems": true
         },
 
-        "extends": {
-          "oneOf": [
-            {
-              "type": "string"
-            },
-            {
-              "type": "object",
-
-              "properties": {
-                "service": {"type": "string"},
-                "file": {"type": "string"}
-              },
-              "required": ["service"],
-              "additionalProperties": false
-            }
-          ]
-        },
-
         "external_links": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
         "extra_hosts": {"$ref": "#/definitions/list_or_dict"},
         "healthcheck": {"$ref": "#/definitions/healthcheck"},
         "hostname": {"type": "string"},
         "image": {"type": "string"},
         "ipc": {"type": "string"},
-        "isolation": {"type": "string"},
         "labels": {"$ref": "#/definitions/list_or_dict"},
         "links": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
 
@@ -154,15 +113,17 @@
 
           "properties": {
             "driver": {"type": "string"},
-            "options": {"type": "object"}
+            "options": {
+              "type": "object",
+              "patternProperties": {
+                "^.+$": {"type": ["string", "number", "null"]}
+              }
+            }
           },
           "additionalProperties": false
         },
 
         "mac_address": {"type": "string"},
-        "mem_limit": {"type": ["number", "string"]},
-        "memswap_limit": {"type": ["number", "string"]},
-        "mem_swappiness": {"type": "integer"},
         "network_mode": {"type": "string"},
 
         "networks": {
@@ -178,8 +139,7 @@
                       "properties": {
                         "aliases": {"$ref": "#/definitions/list_of_strings"},
                         "ipv4_address": {"type": "string"},
-                        "ipv6_address": {"type": "string"},
-                        "link_local_ips": {"$ref": "#/definitions/list_of_strings"}
+                        "ipv6_address": {"type": "string"}
                       },
                       "additionalProperties": false
                     },
@@ -191,14 +151,6 @@
             }
           ]
         },
-        "oom_score_adj": {"type": "integer", "minimum": -1000, "maximum": 1000},
-        "group_add": {
-          "type": "array",
-          "items": {
-            "type": ["string", "number"]
-          },
-          "uniqueItems": true
-        },
         "pid": {"type": ["string", "null"]},
 
         "ports": {
@@ -243,14 +195,8 @@
         "user": {"type": "string"},
         "userns_mode": {"type": "string"},
         "volumes": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
-        "volume_driver": {"type": "string"},
-        "volumes_from": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
         "working_dir": {"type": "string"}
       },
-
-      "dependencies": {
-        "memswap_limit": ["mem_limit"]
-      },
       "additionalProperties": false
     },
 
@@ -271,10 +217,65 @@
         "timeout": {"type": "string"}
       }
     },
+    "deployment": {
+      "id": "#/definitions/deployment",
+      "type": ["object", "null"],
+      "properties": {
+        "mode": {"type": "string"},
+        "replicas": {"type": "integer"},
+        "labels": {"$ref": "#/definitions/list_or_dict"},
+        "update_config": {
+          "type": "object",
+          "properties": {
+            "parallelism": {"type": "integer"},
+            "delay": {"type": "string", "format": "duration"},
+            "failure_action": {"type": "string"},
+            "monitor": {"type": "string", "format": "duration"},
+            "max_failure_ratio": {"type": "number"}
+          },
+          "additionalProperties": false
+        },
+        "resources": {
+          "type": "object",
+          "properties": {
+            "limits": {"$ref": "#/definitions/resource"},
+            "reservations": {"$ref": "#/definitions/resource"}
+          }
+        },
+        "restart_policy": {
+          "type": "object",
+          "properties": {
+            "condition": {"type": "string"},
+            "delay": {"type": "string", "format": "duration"},
+            "max_attempts": {"type": "integer"},
+            "window": {"type": "string", "format": "duration"}
+          },
+          "additionalProperties": false
+        },
+        "placement": {
+          "type": "object",
+          "properties": {
+            "constraints": {"type": "array", "items": {"type": "string"}}
+          },
+          "additionalProperties": false
+        }
+      },
+      "additionalProperties": false
+    },
+
+    "resource": {
+      "id": "#/definitions/resource",
+      "type": "object",
+      "properties": {
+        "cpus": {"type": "string"},
+        "memory": {"type": "string"}
+      },
+      "additionalProperties": false
+    },
 
     "network": {
       "id": "#/definitions/network",
-      "type": "object",
+      "type": ["object", "null"],
       "properties": {
         "driver": {"type": "string"},
         "driver_opts": {
@@ -288,7 +289,14 @@
           "properties": {
             "driver": {"type": "string"},
             "config": {
-              "type": "array"
+              "type": "array",
+              "items": {
+                "type": "object",
+                "properties": {
+                  "subnet": {"type": "string"}
+                },
+                "additionalProperties": false
+              }
             }
           },
           "additionalProperties": false
@@ -300,8 +308,6 @@
           },
           "additionalProperties": false
         },
-        "internal": {"type": "boolean"},
-        "enable_ipv6": {"type": "boolean"},
         "labels": {"$ref": "#/definitions/list_or_dict"}
       },
       "additionalProperties": false
@@ -324,9 +330,9 @@
             "name": {"type": "string"}
           },
           "additionalProperties": false
+        }
       },
-        "labels": {"$ref": "#/definitions/list_or_dict"}
-      },
+      "labels": {"$ref": "#/definitions/list_or_dict"},
       "additionalProperties": false
     },
 
```


Also looks like there's a couple of changes in the json-schema for 3.0 upstream (in docker-compose) that are not (yet) in the docker/docker repository;

```patch
diff --git a/config_schema_v3.0_2.json b/config_schema_v3.0.json
index 817a7df..520e57d 100644
--- a/config_schema_v3.0_2.json
+++ b/config_schema_v3.0.json
@@ -167,10 +167,9 @@
         "restart": {"type": "string"},
         "security_opt": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
         "shm_size": {"type": ["number", "string"]},
-        "sysctls": {"$ref": "#/definitions/list_or_dict"},
         "stdin_open": {"type": "boolean"},
-        "stop_grace_period": {"type": "string", "format": "duration"},
         "stop_signal": {"type": "string"},
+        "stop_grace_period": {"type": "string", "format": "duration"},
         "tmpfs": {"$ref": "#/definitions/string_or_list"},
         "tty": {"type": "boolean"},
         "ulimits": {
@@ -193,7 +192,6 @@
           }
         },
         "user": {"type": "string"},
-        "userns_mode": {"type": "string"},
         "volumes": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
         "working_dir": {"type": "string"}
       },
@@ -202,11 +200,10 @@
 
     "healthcheck": {
       "id": "#/definitions/healthcheck",
-      "type": "object",
-      "additionalProperties": false,
+      "type": ["object", "null"],
       "properties": {
-        "disable": {"type": "boolean"},
-        "interval": {"type": "string"},
+        "interval": {"type":"string"},
+        "timeout": {"type":"string"},
         "retries": {"type": "number"},
         "test": {
           "oneOf": [
@@ -214,8 +211,9 @@
             {"type": "array", "items": {"type": "string"}}
           ]
         },
-        "timeout": {"type": "string"}
-      }
+        "disable": {"type": "boolean"}
+      },
+      "additionalProperties": false
     },
     "deployment": {
       "id": "#/definitions/deployment",
@@ -328,8 +326,7 @@
           "type": ["boolean", "object"],
           "properties": {
             "name": {"type": "string"}
-          },
-          "additionalProperties": false
+          }
         }
       },
       "labels": {"$ref": "#/definitions/list_or_dict"},
```

**Comment by thaJeztah** [comment] 2017-01-20 09:40
I'm not sure which of those changes are deliberate (but undocumented), and which not.

ping @dnephin @vdemeester PTAL

**Comment by dnephin** [comment] 2017-01-20 14:56
#29883 fixes a couple of those differences. The others must have come up in the last couple weeks, after I opened that PR.

I don't remember much discussion about `internal`, I think it might have been dropped by accident.

**Comment by thaJeztah** [comment] 2017-01-20 16:46
@dnephin can we actually _vendor_ those files into the repository? i.e. specify a git-sha to verify / pull it in? Would be good if we keep a single "canonical" location for those specs

**Comment by dnephin** [comment] 2017-01-20 16:51
vendoring doesn't really fix the issue. We actually have to update the implementation as well.

I think we just need a better process for accepting updates to the format.

**Comment by galindro** [comment] 2017-03-08 11:08
@dnephin @thaJeztah could you please check if this was really fixed in most recent docker stable version? I'm using 17.03.0-ce and the error is still ocurring:

```bash
$ docker deploy --compose-file docker-compose.yml infra
internal Additional property internal is not allowed

$ docker version 
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

docker-compose.yml
```yml
version: "3"

services:

  portainer:
    image: portainer/portainer
    deploy:
      placement:
        constraints:
          - engine.labels.infra == true
    networks:
      - ext
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docker.infra.portainer:/data
    command: -H unix:///var/run/docker.sock

  registry:
    image: registry:2.5.1
    deploy:
      placement:
        constraints:
          - engine.labels.infra == true
    networks:
      - int
    volumes:
      - docker.global.ssl:/ssl
      - docker.infra.registry.config:/etc/registry
      - docker.infra.registry.images:/var/lib/registry

  proxy:
    image: openresty/openresty:alpine
    deploy:
      placement:
        constraints:
          - engine.labels.infra == true
    networks:
      - ext
      - int
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - docker.global.ssl:/ssl
      - docker.infra.proxy:/usr/local/openresty/nginx/conf

volumes:
  docker.global.ssl:
    external: true
  docker.infra.proxy:
    external: true
  docker.infra.registry.config:
    external: true
  docker.infra.registry.images:
    external: true
  docker.infra.portainer:
    external: true

networks:
  ext:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/16
  int:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.101.0.0/16
    internal: true
```

**Comment by adzil** [comment] 2017-03-08 15:04
@galindro I can confirm the bug still exists, got the same error using `17.03.0-ce` running on virtualbox with `docker-machine` for service orchestration testing.

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment] 2017-03-08 15:07
Let me reopen the issue 😢

**Comment by dnephin** [comment] 2017-03-08 15:10
Thanks for the report. The code was fixed, and the generated bindata is correct in master, but it looks like the bindata is wrong in the release branch for some reason. Maybe a bad merge?

I opened a PR to fix the release branch #31653

**Comment by thaJeztah** [comment] 2017-03-13 13:01
https://github.com/docker/docker/pull/31653 was merged and will be in 17.03.1, so let me close this again, thanks!

**Closed by thaJeztah** 2017-03-13 13:01 UTC
Labels: area/bundles, kind/bug, platform/desktop, version/1.13

**Comment by hairyhenderson** [comment] 2017-03-14 00:18
🎉

**Comment by hairyhenderson** [comment] 2017-12-26 14:15
@maoueh probably best to open a new issue 🙂 - also may want to test with the latest RC (17.12.0-ce-rc4), and use the latest schema version (3.5, I think?)

**Comment by maoueh** [comment] 2018-01-09 16:01
Updating to `17.12.0` led to the same problem.

However, changing the version to `3.5` did fix the error I had. So, might be how things work. It's good enough for me anyway.

Thanks for the answer.

**Comment by hairyhenderson** [comment] 2018-01-09 16:39
@maoueh that makes sense - the file is parsed according to the schema version specified
