### ISSUE TITLE
Docker swarm mode rebalancing |  Resurrection

### ISSUE THREAD

**Issue by viveky4d4v** [docker/docker#30666] opened 2017-02-02 07:03 UTC
Swarm mode 
------------------

Rebalancing containers automatically when the node comes back in life . Kind of Resurrection .

Let's say if i have one manager & one worker .-

If worker dies , manager will schedule all containers on itself .
Worker comes back in life & manager doesn't rebalance containers & all containers sit on manager .
Now if manager dies , our stack goes down even if worker is up & running .
Ideally manager should automatically balance the containers when worker comes back in life by moving the oldest container back to the worker . I don't know how this can be done without downtime ( in case you have just one application container ) .
OR
if the scheduler makes some decision like in case of a single application container it should not move it back to worker to remove downtime but it should do it if we have multiple replicas.

PS - I understand it's not efficient way to use swarm, we should use at least 3 managers but i caught up in this situation so i thought to get some ideas from community.

**Comment by thaJeztah** [comment] 2017-02-02 07:27
This is a duplicate of https://github.com/docker/docker/issues/24103; the reason behind this is that rebalancing actually can cause service interruption (i.e., why kill a healthy container?)

> I don't know how this can be done without downtime ( in case you have just one application container ) .

Currently not, but there's some improvements made here; https://github.com/docker/docker/pull/30261

Even in that case, killing a task (container), and starting a new one may not always be seamless, depending on "what" is running in the container.

> Now if manager dies , our stack goes down even if worker is up & running .

Your application would still fail if _one_ of your containers is running on the manager; if the manager dies, no new containers will be started.

I'll close this issue, because it's a duplicate of https://github.com/docker/docker/issues/24103, but I hope the above explains a bit better why this is not implemented.

Feel free to continue the discussion after I closed

**Closed by thaJeztah** 2017-02-02 07:27 UTC
Labels: area/swarm
