### ISSUE TITLE
How to change the file permission in volume mapping?

### ISSUE THREAD

**Issue by dewang-agrawal** [docker/docker#32348] opened 2017-04-04 13:26 UTC
**Description:**
I have a file abc.txt on host machine with permissions 400. I am mapping this file inside container using volumes. I want to change the permission of file inside the container as 777 **but the permissions of the file at host should be 400** only.

**Describe the results you received:**
Currently permission of the file abc.txt inside container is 400 .

**Output of `docker version`:**
1.13.0

**Comment by thaJeztah** [comment] 2017-04-04 13:37
That's currently not possible, and would require new features to be added to the Linux kernel. When bind-mounting a file from your host, the files you see inside the container _are_ the files that are present on the host. There's nothing "in between" that allows to "remap" the permissions to another owner/permissions. The same functionality (`shiftfs`) is needed to implement "phase 2" of "user namespaces", see the discussion in this issue https://github.com/docker/docker/issues/28593

When using Docker for Mac, there _is_ some tooling in between, which makes the container "ignore" ownership, thus any user can access a file when mapped from the host.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-04-04 13:37 UTC
