### ISSUE TITLE
Docker stack - add support of compose override files (proposal)

### ISSUE THREAD

**Issue by eyal-lupu** [docker/docker#30504] opened 2017-01-27 14:47 UTC
hello,

Docker compose documentation suggests the support of override files [here](https://docs.docker.com/compose/extends/#/multiple-compose-files) but I cannot find any support for that in 'docker stack' command (neither in the docs, not when trying, and nor for dab files). 

Integrating compose as part of Docker Swarm is a huge step forward but for real life environment overriding is absolutely a must otherwise managing the diff between dev, test, prod and various size deployments becomes too much of a mess.

**Comment by brycejacobs** [comment] 2017-03-14 16:34
Is there any plan to implement this in the near future?

**Comment by composer22** [comment] 2017-03-23 17:37
+1 
Agree totally. I'm in a blocker for this

Specifically need to deploy to different environments for different contraint's using 

```
version: "3.1"
services:
  service:
    deploy:
      placement:
        constraints:
          - node.role == worker
          - etc...
```

And docker stack deploy -c <etc>

**Comment by teohhanhui** [comment] 2017-04-12 08:06
Duplicate of #30127

**Comment by dnephin** [comment] 2017-04-12 14:28
Closing as duplicate

**Closed by dnephin** 2017-04-12 14:28 UTC
Labels: area/bundles, area/runtime, kind/enhancement
