### ISSUE TITLE
Document log-opt behavior

### ISSUE THREAD

**Issue by chiefy** [docker/docker#16453] opened 2015-09-21 14:53 UTC
docker version: Docker version 1.8.2, build 0a8c2e3
uname: Linux 13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I have added the following to my `/etc/init/docker`:
```bash
DOCKER_OPTS="-H unix:///var/run/docker.sock --log-opt max-size=25m --log-opt max-file=2"
```

output of ps:
```
root       928  0.0  0.1 2019352 33980 ?       Ssl  Sep16   4:18 /usr/bin/docker daemon -H unix:///var/run/docker.sock --log-opt max-size=25m --log-opt max-file=2
```

```
root@[redacted]:/var/lib/docker/containers/4ca6a18d58bb6df9d77d30d64f17d208f3e02b3018888143f51522f2dcf8ddff# ls -lah
total 30M
drwx------ 2 root root 4.0K Sep 16 19:47 .
drwx------ 9 root root 4.0K Sep 16 18:51 ..
-rw------- 1 root root  30M Sep 21 14:40 4ca6a18d58bb6df9d77d30d64f17d208f3e02b3018888143f51522f2dcf8ddff-json.log
-rw-r--r-- 1 root root 3.4K Sep 16 19:47 config.json
-rw-r--r-- 1 root root  764 Sep 16 19:47 hostconfig.json
-rw-r--r-- 1 root root   13 Sep 16 19:47 hostname
-rw-r--r-- 1 root root  638 Sep 16 19:47 hosts
-rw-r--r-- 1 root root  248 Sep 16 19:47 resolv.conf
-rw------- 1 root root   71 Sep 16 19:47 resolv.conf.hash
```

```
root@[redacted]:/var/lib/docker/containers/4ca6a18d58bb6df9d77d30d64f17d208f3e02b3018888143f51522f2dcf8ddff# docker ps | grep 4ca6a18d58bb
4ca6a18d58bb        my-app     "npm start"   4 days ago          Up 4 days           3001/tcp, 0.0.0.0:32779->3000/tcp            my_app_1
```

**Comment by cpuguy83** [comment] 2015-09-21 14:55
Can you provide the inspect output of the container, as well as the output of `docker info` and `docker version`?
Also note that if you created the container w/ docker < 1.8.2 these opts may have been ignored to a bug.

**Comment by chiefy** [comment] 2015-09-21 15:14
> Also note that if you created the container w/ docker < 1.8.2 these opts may have been ignored to a bug.

this is really important information I don't see mentioned in the docs?

docker version is above.
docker info:
```
Containers: 7
Images: 68
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 82
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 29.96 GiB
Name: xxxxxx
ID: XSYC:3C7A:AFD5:2HCL:YYVV:3IK5:OLT5:BBZU:KNTB:YAOS:W4M5:7YPT
WARNING: No swap limit support
```

inspect:
```json
root@[redacted]:/# docker inspect 4ca6a18d58bb
[
{
    "Id": "4ca6a18d58bb6df9d77d30d64f17d208f3e02b3018888143f51522f2dcf8ddff",
    "Created": "2015-09-16T18:51:27.359011117Z",
    "Path": "npm",
    "Args": [
        "start"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 6675,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-09-16T19:47:19.797924446Z",
        "FinishedAt": "2015-09-16T19:47:19.54529044Z"
    },
    "Image": "2e290e5eb0639f71a88643dbd24b1ff445c439222e279ca5f7bbae5e356d5afd",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "ce6b1338aaca8357bc94177509fd5e544f5879edef917f68d0c0cb091a860fc6",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.16",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "xxxx",
        "NetworkID": "50e50f7a1b711a291aab9dfd0bd686cec2b7c5ddc4e675f8553b3d3d972d35da",
        "PortMapping": null,
        "Ports": {
            "3000/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "32779"
                }
            ],
            "3001/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/4ca6a18d58bb",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/4ca6a18d58bb6df9d77d30d64f17d208f3e02b3018888143f51522f2dcf8ddff/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/4ca6a18d58bb6df9d77d30d64f17d208f3e02b3018888143f51522f2dcf8ddff/hostname",
    "HostsPath": "/var/lib/docker/containers/4ca6a18d58bb6df9d77d30d64f17d208f3e02b3018888143f51522f2dcf8ddff/hosts",
    "LogPath": "/var/lib/docker/containers/4ca6a18d58bb6df9d77d30d64f17d208f3e02b3018888143f51522f2dcf8ddff/4ca6a18d58bb6df9d77d30d64f17d208f3e02b3018888143f51522f2dcf8ddff-json.log",
    "Name": "/rso_app2_1",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {
            "3000/tcp": [
                {
                    "HostIp": "",
                    "HostPort": ""
                }
            ]
        },
        "Links": [
         "REDACTED": true
        ],
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": [],
        "VolumesFrom": [
            "23aac103e139a81a87f94c7d3cc703f0b98655ba63ee4809174db53c6348ce4a"
        ],
        "Devices": null,
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ]
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [
        {
            "Source": "/var/local/ddd",
            "Destination": "/var/www/sites/ddd/config",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "4ca6a18d58bb",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "3000/tcp": {},
            "3001/tcp": {}
        },
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
         "REDACTED": true
        ],
        "Cmd": [
            "npm",
            "start"
        ],
        "Image": "xx.d.xx.com/xxx/xx:0.2.4",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "/srv/www",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {
            "com.docker.compose.config-hash": "eb3c55ce915541df94f969258759e04019aaa983d96202f9a21631394e25ede1",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "ddd",
            "com.docker.compose.service": "ddd",
            "com.docker.compose.version": "1.3.3"
        }
    }
}
]
```

Fairly certain that this particular image was created w/ docker 1.7.x, so I will re-try w/ 1.8.2 and report back.

**Comment by cpuguy83** [comment] 2015-09-21 15:17
Also yes, I don't think 1.7 supported these options.

Note your logopts on the container:
```json
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
```

These are generated only on container create.

**Comment by chiefy** [comment] 2015-09-21 17:11
@cpuguy83 can you re-open this and tag it w/ needs-docs or something.

As it turns out, you have to build the image w/ a daemon that has the --log-opts set. We're using CI/CD and our Jenkins build box is now using Docker 1.8.2 but doesn't have the --log-opts set and I just tried running an image built on that box w/ a daemon that *does* have the --log-opts set and it doesn't take them.

Maybe I am stupid, but this behavior is extremely confusing and should be documented somewhere on the website.

**Comment by cpuguy83** [comment] 2015-09-21 17:24
You're right, this does seem to be poorly documented.
But what you have said here is not quite right.

The container needs to be created with the log opts set. Which can be set on the daemon and overwritten on `docker run`. Once these are set for a container, they cannot be changed.

**Comment by chiefy** [comment] 2015-09-21 17:40
@cpuguy83 OK, we are running our orchestrations w/ docker-compose 1.3.x I think this is the other part of the issue apparently?

**Comment by cpuguy83** [comment] 2015-09-21 17:41
@chiefy I'm not sure what compose supports here.

**Comment by thaJeztah** [comment] 2015-09-21 17:45
I think various log features were only recently added to docker compose, and are in compose 1.4, or even the next release. Not sure if these are one of them by head

/cc @dnephin

**Comment by dnephin** [comment] 2015-09-21 17:55
I believe the json-file option has been ok since 1.3, we were missing support for other drivers, which will be in 1.5

**Comment by chiefy** [comment] 2015-09-21 18:11
```yaml
app:
  image: chiefy/alpine-node-static:latest
  log_opt:
    "max-size": "25m"
    "max-file": "2"
  volumes:
    - ".:/var/www"
  ports:
    - "8080:3000"
```

```
❯ docker --version && docker-compose --version && docker-compose up -d
Docker version 1.8.2, build 0a8c2e3
docker-compose version: 1.3.3
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zg 14 July 2015
Unsupported config option for app service: 'log_opt'
```

**Comment by dnephin** [comment] 2015-09-21 18:21
hmm, I guess I was wrong. The `log_opt` was added in 1.4.0, only `log_driver` was in 1.3

**Comment by chiefy** [comment] 2015-09-21 18:25
Ok, thanks @dnephin  - going to install 1.4.1 & 1.8.2 on our AMIs and hopefully it works.

**Comment by pkieltyka** [comment] 2015-09-21 21:40
I have the exact same problem with docker 1.8.2. I set `--log-opt max-size=100m --log-opt max-file=5` via docker run and expected that the default json logger would consume a maximum of 500m worth of logs and roll around in that.. but, I looked now and its consumed my entire disk aka 90GB.

**Comment by pkieltyka** [comment] 2015-09-21 21:48
To be clear.. 

The container is started by: `docker run -d -p 4446:4446 -v /etc/imgry.conf:/etc/imgry.conf -v /data:/data --memory-swappiness=0 --restart=always --log-opt max-size=100m --log-opt max-file=5 --name imgry pressly/imgry`

```
# docker info
Containers: 1
Images: 96
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 98
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-62-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.305 GiB
Name: ip-172-30-0-173
ID: TU6C:YQO7:DUMU:PKTS:43QF:OUDB:E2G3:GFAJ:3P3D:OUHF:LLBA:CFZ5
```

```
# docker inspect imgry
[
{
    "Id": "38a64adb9f089921897bcecb61aba67e272f954902095547233231590d446175",
    "Created": "2015-09-21T21:41:20.034930904Z",
    "Path": "/bin/imgry-server",
    "Args": [
        "-config=/etc/imgry.conf"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 4079,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-09-21T21:41:20.193460295Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "4c973d4d1f6c0fd368aea4ad24fa072992199a3e6bf9724e04cf7c5f6382924a",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "8ff4a9f6310e18f12cc66dca12bc7561f6b76416411ec6501b504c6f55cfdebd",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.3",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:03",
        "NetworkID": "100c18076f59ce4db93be75abed4c1bf3082d75e5c222990e01333b329ecff74",
        "PortMapping": null,
        "Ports": {
            "4446/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "4446"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/38a64adb9f08",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/38a64adb9f089921897bcecb61aba67e272f954902095547233231590d446175/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/38a64adb9f089921897bcecb61aba67e272f954902095547233231590d446175/hostname",
    "HostsPath": "/var/lib/docker/containers/38a64adb9f089921897bcecb61aba67e272f954902095547233231590d446175/hosts",
    "LogPath": "/var/lib/docker/containers/38a64adb9f089921897bcecb61aba67e272f954902095547233231590d446175/38a64adb9f089921897bcecb61aba67e272f954902095547233231590d446175-json.log",
    "Name": "/imgry",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/etc/imgry.conf:/etc/imgry.conf",
            "/data:/data"
        ],
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": 0,
        "Privileged": false,
        "PortBindings": {
            "4446/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "4446"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "always",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ]
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [
        {
            "Source": "/etc/imgry.conf",
            "Destination": "/etc/imgry.conf",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/data",
            "Destination": "/data",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "38a64adb9f08",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "4446/tcp": {}
        },
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "GOLANG_VERSION=1.5.1",
            "GOLANG_DOWNLOAD_URL=https://golang.org/dl/go1.5.1.linux-amd64.tar.gz",
            "GOLANG_DOWNLOAD_SHA1=46eecd290d8803887dec718c691cc243f2175fe0",
            "GOPATH=/go"
        ],
        "Cmd": [
            "/bin/imgry-server",
            "-config=/etc/imgry.conf"
        ],
        "Image": "pressly/imgry",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "/go/src/github.com/pressly/imgry",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]
```

```
# docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by cpuguy83** [comment] 2015-09-22 00:09
@pkieltyka This is a bug in 1.8, it's fixed on master.
You have to specify the log driver on run.
So `docker run --log-driver json-file --log-opt max-size=5m --log-opt max-file=5` should do the trick.

**Comment by pkieltyka** [comment] 2015-09-22 13:27
thank you @cpuguy83, I will try this

**Comment by pkieltyka** [comment] 2015-09-28 18:50
@cpuguy83 I checked after a few days, and it didn't make a difference, on 1.8.2 even passing `--log-driver json-file` along with other params, docker logs still ate up all of my disk space and ignored the --log-opt rules.

**Comment by cpuguy83** [comment] 2015-09-28 18:54
@pkieltyka Please paste the inspect output and the command that you actually ran because I cannot reproduce.

**Comment by pkieltyka** [comment] 2015-09-28 19:11
@cpuguy83 I took a closer look, and it looks like the container's log files were being rotated properly with `--log-driver json-file`.

I had assumed it was the same bug, but this must be another bug that is eating up the space. I need to look closer if its in my app or something else related in docker.

**Comment by pkieltyka** [comment] 2015-09-28 19:18
@cpuguy83 I am finding my /var/lib/docker/aufs folder to be > 100G, where I expect the problem to be. If I rm the container and start it again, /var/lib/docker/aufs goes back down to 3.5GB. 

To run the container, I mount a volume that contains a rolling leveldb for an on-disk LRU cache around 1.5GB, and at times, my application will crash related to high load or panics (working that out), and since I start docker with restart always it brings the app right back up. Could it be possible for the volume layers to be cached somewhere in /var/lib/docker during this cycle?

**Comment by chiefy** [comment] 2015-09-28 19:21
@pkieltyka could be wrong, but unless you run your container with `--rm` I do believe it will get cached in `/var/lib/docker`

**Comment by cpuguy83** [comment] 2015-09-28 19:22
@pkieltyka volumes are stored in `/var/lib/docker/volumes`
If the aufs dir is growing and then shrinking, it would seem you are writing to the container's write layer rather than to the volume.

When you say `start it again`, does that mean a whole new container, or `docker start`?
Seems like you are having a different problem than described by the OP and not related to logging based on your last comment.

**Comment by pkieltyka** [comment] 2015-09-28 19:31
@cpuguy83 I will double check about the write layer -- but from what I can see, it is writing to the volume as the host OS directory shows the contents changing. 

Re: starting again, I mean a `stop`, `rm`, and `run`. The rm is necessary to get back my diskspace. I need to exec into the running container and check the container contents... maybe something else is eating up the diskspace... hmm, this reminds me, it could be Imagemagick leaving artifacts in /tmp on a crash. The server running is https://github.com/pressly/imgry (its open).

**Comment by pkieltyka** [comment] 2015-09-28 19:39
@cpuguy83 @chiefy yes - /tmp crashes leaving artifacts. sorry for hijacking this issue. Hope it helps highlight other notes / debugging for future users though, this is something I didn't consider. Would be nice to have a self-destructive mountable volume or something like in this case. I guess I can run the container and do rm /tmp/* at the entrypoint as well.

**Comment by LK4D4** [comment] 2016-09-16 03:48
Issue is quite old and cool docs were added to logging since.

**Closed by LK4D4** 2016-09-16 03:48 UTC
Labels: area/docs
