### ISSUE TITLE
Container does not run consistently across host/docker versions

### ISSUE THREAD

**Issue by ahawkins** [docker/docker#8910] opened 2014-11-02 10:22 UTC
Hello, I've run into a strange and somewhat troubling problem. I've managed (accidentally) to build an image that does not behave same when run. You can find the source for the image on my [github account](https://github.com/ahawkins/docker-rebar-bug). The repo contains the source & docker file used to create the image. The running the image will create a container that either exists or hangs indefinitely. I have not been able to reproduce it 100% of the time. The same `docker run` command may succeed the first time, then fail on the second. It may fail consistently, or it may pass consistently. I've tried the image on different docker versions & different hosts OS. The results vary which is quite concerning to me.

You can test your setup by running: `docker run --rm -it ahawkins/rebar-bug` and see what happens.

I've tried this image on:

* Ubuntu 14.04 hosts
* Docker 1.2.0
* Docker 1.3.1
* With & without the `--rm` flag
* With * without the `-i` & `-t` flag
* Combinations of the above

All of these have different results. The image runs differently inside the same virtual machine as well.

**Comment by jfrazelle** [comment] 2015-02-26 02:30
what storage driver are you using, it is the same across hosts

**Comment by jfrazelle** [comment] 2015-03-02 17:25
closing as stale please ping me with exact steps to reproduce on the latest version and I will reopen

**Comment by olof** [comment] 2015-05-10 10:11
Hi,

I'm hit with the same bug. I'm happy to help out with steps to reproduce. I tested both aufs storage backend and devicemapper. With aufs I experienced this issue consistently, but switching to devicemapper I only experienced it ~2/10 times.

I posted additional details in ahawkins/docker-rebar-bug#1, including my Dockerfile and logs. I'm using

    $ docker --version
    Docker version 1.6.1, build 97cd073

as packaged by Debian (`1.6.1+dfsg1-1`). Is there anything else I can supply to help in investigating this?

**Comment by jfrazelle** [comment] 2015-07-10 21:59
we need clear steps to reproduce, docker version, and docker info

**Comment by olof** [comment] 2015-07-13 17:22
I currently don't have access to the host I used to play around with this, so
the info is somewhat stale, but as described in [ahawkins' reproducer
repo](https://github.com/ahawkins/docker-rebar-bug/issues/1), here's the steps I
was triggered the issue with:

Dockerfile:

    FROM debian:jessie
    RUN apt-get update
    RUN apt-get install --no-install-recommends -y git make vim
    
    RUN apt-get install --no-install-recommends -y \
        erlang-base \
        erlang-eunit \
        rebar
    RUN groupadd ertorrent && useradd -g ertorrent ertorrent
    RUN mkdir -p /home/ertorrent && chown ertorrent:ertorrent /home/ertorrent
    USER ertorrent
    RUN git clone git://github.com/orzen/ertorrent.git /home/ertorrent/src
    WORKDIR /home/ertorrent/src
    RUN git fetch -p
    RUN git checkout topic/rebar
    CMD /bin/bash

Building that docker image as `ertorrent` and running the following

  sudo docker run ertorrent rebar compile eunit

triggered the issue every time for me when using aufs. When using devicemapper it went down to about 20% of the times.

I'll add `docker version` and `docker info` output as requested within a couple of days.

Thanks,

**Comment by olof** [comment] 2015-07-17 22:36
I noticed that the branch I mentioned in the above Dockerfile was removed from the
example repo, so I made a fork that I'll keep static for this issue:

    FROM debian:jessie
    RUN apt-get update && apt-get install --no-install-recommends -y \
        git \
        erlang-base \
        erlang-eunit \
        rebar
    RUN mkdir -p /home/ertorrent
    RUN groupadd ertorrent && useradd -g ertorrent ertorrent
    RUN chown -R ertorrent:ertorrent /home/ertorrent
    USER ertorrent
    RUN git clone git://github.com/olof/ertorrent-rebar-docker-issue.git /home/ertorrent/src
    WORKDIR /home/ertorrent/src
    CMD /bin/bash

As I stated earlier, with devicemapper I do get this to pass the majority of
the times.

Noticed how I specified /bin/bash as CMD? I now tried changing that to rebar eunit,
and I fail to reproduce when running as `docker run ertorrent` (with `ertorrent`
being my tag for the image). But if I run it as `docker run ertorrent rebar eunit`
I can still trigger it.

And, as promised, here's my `docker version`:

    $ sudo docker version
    Client version: 1.6.2
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): 7c8fca2
    OS/Arch (client): linux/amd64
    Server version: 1.6.2
    Server API version: 1.18
    Go version (server): go1.4.2
    Git commit (server): 7c8fca2
    OS/Arch (server): linux/amd64

(as supplied by Debian, 1.6.2~dfsg1-2)

... and `docker info`:

    $ sudo docker info
    Containers: 131
    Images: 111
    Storage Driver: devicemapper
     Pool Name: docker-254:1-7079811-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: extfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 3.525 GB
     Data Space Total: 107.4 GB
     Data Space Available: 103.8 GB
     Metadata Space Used: 13.69 MB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.134 GB
     Udev Sync Supported: true
     Data loop file: /var/lib/docker/devicemapper/devicemapper/data
     Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
     Library Version: 1.02.90 (2014-09-01)
    Execution Driver: native-0.2
    Kernel Version: 4.0.0-1-amd64
    Operating System: Debian GNU/Linux stretch/sid
    CPUs: 4
    Total Memory: 3.75 GiB
    Name: bohr
    ID: NAEM:E5GA:HLKG:URE4:Z2K7:TGWW:AX4E:MKJH:JPFO:4LNB:F6QM:YYDO
    WARNING: No memory limit support
    WARNING: No swap limit support

**Comment by driver2000** [comment] 2015-12-04 15:05
I've found a dirty workaround for this issue, try in this way : 
`docker run -ti ertorrent bash -c "rebar compile 1>&1"`

**Comment by olof** [comment] 2015-12-04 16:57
Yeah, I can confirm that your workaround doesn't trigger the problem. Interesting.

**Comment by edevil** [comment] 2015-12-15 16:47
I have this same problem. This seems related to: http://erlang.org/pipermail/erlang-questions/2013-September/075385.html

Ports don't get the :exit_status message and just hang there.

**Comment by edevil** [comment] 2015-12-16 11:25
I've setup an image (https://hub.docker.com/r/edevil/docker-erlang-bug/) to demonstrate the problem and the Dockerfile is here: https://github.com/edevil/docker-erlang-bug.

Can someone else test to see if the problem also happens for them?

    $ docker run edevil/docker-erlang-bug erl -noshell -s test run -s init stop
    FAILED # after 5 seconds

If you run the code inside the container via bash:

    $ docker run edevil/docker-erlang-bug bash -c "erl -noshell -s test run -s init stop"
    FAILED

However, if you redirect stdout to stdout (?) it works:

    $ docker run edevil/docker-erlang-bug bash -c "erl -noshell -s test run -s init stop 1>&1"
    SUCCESS

What is happening here is that the Erlang code calls an external executable, (ls) that finishes, but Erlang does not get notified for some reason. I have used both Docker 1.7.1 and 1.9.1. My Docker engine runs on Ubuntu 14.04.1 LTS. I don't even know where to start, is this an Erlang problem or a Docker problem?

I'm using the aufs driver.

**Comment by olof** [comment] 2015-12-16 20:43
Hi @edevil, really nice work. With devicemapper, I got two failures out of ten attempts, which is consistent with what I saw when I compared switching from aufs to devicemapper as described above. So, we have a much simpler way to reproduce now :)!

I don't know if this [recent mail](http://erlang.org/pipermail/erlang-questions/2015-October/086590.html) sent to the erlang-questions list is related, but sounds like it could be...

> Today I observed that the processes spawned by RabbitMQ (like for
> example EPMD in non-detached mode, system supervisor processes like
> disk, etc.) are put in different process sessions / groups than the
> "parent" Erlang VM process.

**Comment by edevil** [comment] 2015-12-16 23:41
It could be related, anything that would cause a parent process to not be aware that a child has died can be related to this problem. It's a shame the email did not get any answers...

**Comment by therazor** [comment] 2016-03-17 15:36
Possibly related issue: docker image has [different behaviour when ran in ubuntu or mac](https://github.com/sitespeedio/sitespeed.io-docker/issues/5#issuecomment-169522140)

**Comment by thaJeztah** [comment] 2016-09-14 16:24
@edevil are you still having this issue? I'm unable to reproduce with your  on Docker 1.12.1, both on Docker for Mac, and on Ubuntu 14.04 (with aufs)

**Comment by thaJeztah** [comment] 2016-09-14 20:25
ping @justincormack any idea if there's anything to do here?

**Comment by justincormack** [comment] 2016-09-20 16:12
Sounds to me like the reparenting bug was fixed in Erlang 19 then, and it was a bug in the runtime. Grandchildren can get lost, and become zombies. 1.13 will have an optional `init` which might help by reaping them, or it might not make a difference for this case.

I don't think there is anything Docker can do for this, so I am going to close this, but feel free to continue discussion.

**Closed by justincormack** 2016-09-20 16:12 UTC
Labels: area/runtime, status/more-info-needed
