### ISSUE TITLE
Create the possibility to install a specific version of docker through get.docker.io

### ISSUE THREAD

**Issue by MetalArend** [docker/docker#13822] opened 2015-06-09 08:46 UTC
Updating docker to 1.6.2 is giving a lot of trouble with containers and images, with bugs already reported elsewhere (I checked). As I installed docker through the get.docker.io script, it would be useful to be able to add a version of docker to the url, and use for example https://get.docker.io/1.6.0 to install a specific version.
Also, having a combined resource with all the possible ways to use get.docker.io would be very useful.

**Comment by thaJeztah** [comment] 2015-06-15 16:08
There's updated documentation for obtaining a specific version of docker that can be found here; http://docs.master.dockerproject.org/installation/binaries/#get-the-linux-binary. Keep in mind that these are *static* builds; depending on the distro and graphdriver you're using (e.g. devicemapper), you may need a dynamically linked build in stead.

**Comment by daviddyball** [comment] 2015-06-22 16:45
What about using bash variables in the script to allow the setting of a desired docker version? e.g.

```
if [[ -n "$DOCKER_VERSION" ]]; then
    apt-get install lxc-docker-${DOCKER_VERSION}
else
    apt-get install lxc-docker
fi
```

That way you could do this to install `1.6.2`

```
wget https://get.docker.io/ | DOCKER_VERSION=1.6.2 sh
```

**Comment by thaJeztah** [comment] 2015-06-28 19:02
@tianon @jfrazelle any thoughts on that?  https://github.com/docker/docker/issues/13822#issuecomment-114175396

**Comment by mvanholsteijn** [comment] 2015-11-12 05:57
@thaJeztah: Sounds like a great idea!  It is vital to be able to control the version of Docker that we install on our machines. We build our machine images with packer and just recently  a "free" upgrade which broke my code. Please met me specify which version I get. @daviddyball  suggestion would work for me.

**Comment by mvanholsteijn** [comment] 2015-11-12 06:12
I found this solution on https://forums.docker.com/t/how-can-i-install-a-specific-version-of-the-docker-engine/1993/3


```bash
wget -O docker.deb https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.3-0~trusty_amd64.deb
 sudo dpkg -i docker.deb
```

**Comment by thaJeztah** [comment] 2015-11-12 09:47
@mvanholsteijn glad you found it, and we also move to a new apt repository (the old repository is still getting the current release, but (iirc) 1.9 will be the last release for the old repo.

[this comment](https://forums.docker.com/t/how-can-i-install-a-specific-version-of-the-docker-engine/1993/8) (copied here) describes the usual way of specifying a version

```
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
mkdir -p /etc/apt/sources.list.d
echo deb https://apt.dockerproject.org/repo3 ubuntu-trusty main > /etc/apt/sources.list.d/docker.list
apt-get update;
apt-get install -y -q docker-engine=1.x.x~
```

w.r.t changing the install-script; we're moving away from the `curl | sh` approach in our documentation in favor of instructing users on how to perform the installation. The install-script is doing a lot of things to try to detect the platform that is installed on, and this sometimes leads to incomplete installs.

Finally, I agree that (although it may be considered general knowledge on apt/yum/dnf) we need to provide more information on how to install a specific version of docker from our apt/yum repos. I'll create an issue for that; perhaps you are interested in contributing changes to the documentation for that?

**Comment by thaJeztah** [comment] 2015-11-12 09:55
Looks like this is actually a duplicate of https://github.com/docker/docker/issues/9697 which was rejected, and (given that we are trying to move away from the `curl | sh` install, especially for advanced installations), I think this should be closed.

ping @tianon @jfrazelle do you think we should close this, or are you okay with adding the proposed change?

**Closed** 2016-04-29 14:23 UTC
Labels: kind/feature
