### ISSUE TITLE
command not found: dockerd

### ISSUE THREAD

**Issue by villins** [docker/docker#25949] opened 2016-08-23 08:20 UTC
docker version:
```
Version 1.12.0-a (build: 11213)
ad6ab836187e4111082447b7c0a6a74d01929a5c
```

error info 
```
`docker daemon` is not supported on Darwin. Please run `dockerd` directly
```

**Comment by justincormack** [comment] 2016-08-23 08:26
There is no support to run Docker natively on OSX, so there is no server (dockerd) only the client.

Here are the instructions for Mac installation https://docs.docker.com/engine/installation/mac/

**Comment by justincormack** [comment] 2016-08-23 08:28
Closing this as it is not a bug, but feel free to continue asking questions.

**Closed by justincormack** 2016-08-23 08:28 UTC

**Comment by villins** [comment] 2016-08-23 08:39
@justincormack i comply all the Requirements，as follow:
OSX 10.10.4 (14E46)
Machine Mac mini (Late 2012)
RAM 8 GB 1600 MHz DDR3
and then VirtualBox is version 5.0.20
