### ISSUE TITLE
Hash Sum mismatch on Ubuntu 16.04 apt-get update

### ISSUE THREAD

**Issue by RichardJECooke** [docker/docker#30207] opened 2017-01-17 10:47 UTC
**Description**

apt-get update fails on fresh Ubuntu image

**Steps to reproduce the issue:**
1. create the following dockerfile:
```
FROM ubuntu:16.04
MAINTAINER b@example.com
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get update -y 
```
2. Run it: `docker build .`

**Describe the results you received:**
Error:
```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/source/by-hash/SHA256/50ccff6c903e98e2e52c1ab6dae4a85d23a84369325fd971c4bfc3752e6a7ede  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Describe the results you expected:**
No error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Docker version 1.12.6, build 78d1802
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: ubuntu16vm
ID: OHBW:TZ6D:RDGR:LMIR:NJTP:76J6:3PUF:FFJ2:GT4C:SDRI:CND5:RW5H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04 VirtualBox VM on Windows 10 host

**Comment by RichardJECooke** [comment] 2017-01-17 10:51
Additionally, 14.04 works fine. I'll use that as a workaround for now.

**Comment by thaJeztah** [comment] 2017-01-17 12:47
This does not look like a bug in docker, but either a networking issue, or possibly a mirror of `archive.ubuntu.com` being out of date. Are you possibly behind a caching proxy? (also see http://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error)

I am not able to reproduce this issue, and given that you are successfully able to run `apt-get` in an ubuntu 14.04 container, I don't suspect there's a bug at hand here, so I'll close this issue, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-01-17 12:47 UTC
Labels: area/builder

**Comment by RichardJECooke** [comment] 2017-01-17 13:10
Thanks. 

I've tried adding all 3 solutions in that question below (and deleting all Docker images every time) but I still get the same error. I'm not behind any proxy I'm aware of. I guess it must be a bug in Ubuntu, I'll log it there.

```
FROM ubuntu:16.04
MAINTAINER b@example.com
RUN touch /etc/apt/apt.conf.d/99fixbadproxy \
    && echo "Acquire::http::Pipeline-Depth 0;" >> /etc/apt/apt.conf.d/99fixbadproxy \
    && echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99fixbadproxy \
    && echo "Acquire::BrokenProxy true;" >> /etc/apt/apt.conf.d/99fixbadproxy \
    && apt-get update -o Acquire::CompressionTypes::Order::=gz \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get update -y
```

**Comment by RichardJECooke** [comment] 2017-01-19 13:35
For anyone else trying to solve this, the problem was due to how I installed Docker: http://askubuntu.com/questions/872933/how-to-fix-hash-sum-mismatch-error-on-fresh-docker-image-update/873697#873697

`sudo curl -sSL https://get.docker.com | bash` - works fine

`sudo apt-get install docker-engine=1.11.2-0~xenial` - causes hash mismatch errors.

**Comment by aftabnaveed** [comment] 2017-02-15 23:20
That did not fix issue for me, and able to reproduce it. 

> E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64/by-hash/SHA256/d0e9f7fa794a04e2ec39d028da3ef13dd13b067c4cc48ea1c294bab2925e6678  Hash Sum mismatch
> E: Some index files failed to download. They have been ignored, or old ones used instead.
>

**Comment by thaJeztah** [comment] 2017-02-16 03:21
@aftabnaveed http://archive.ubuntu.com/ is a repository managed by ubuntu, so if there's issues with that repository, either report with Ubuntu, or check if there's not VPN / Caching Proxy involved

**Comment by venkatesh0349** [comment] 2017-09-17 03:55
hi Richard please that its really solve the issue by

FROM ubuntu:16.04
MAINTAINER b@example.com
RUN touch /etc/apt/apt.conf.d/99fixbadproxy \
    && echo "Acquire::http::Pipeline-Depth 0;" >> /etc/apt/apt.conf.d/99fixbadproxy \
    && echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99fixbadproxy \
    && echo "Acquire::BrokenProxy true;" >> /etc/apt/apt.conf.d/99fixbadproxy \
    && apt-get update -o Acquire::CompressionTypes::Order::=gz \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get update -y

**Comment by varsha6319** [comment] 2018-01-18 00:07
# This resolves the issue for Ubuntu 16.04 hash sum mismatch:
sudo apt-get update -o Acquire::CompressionTypes::Order::=gz
sudo apt-get upgrade -y
sudo apt-get update

**Comment by kayz5ive** [comment] 2018-03-14 11:55
worked for me. thanks!

**Comment by indradhanush** [comment] 2018-05-13 03:40
I had the same problem on *Ubuntu 16.04* but under Vagrant. Thanks so much. :+1:

**Comment by utsinha12** [comment] 2018-06-26 09:49
@varsha6319's solution works. thanks! I first tried putting just the upgrade step, but that doesn't work alone. You gotta add the first 'apt-get update -o Acquire::CompressionTypes ...' too.

**Comment by var23rav** [comment] 2018-07-20 11:33
@RichardJECooke Solution works for me.
But make sure you don't have any other config file there with **Acquire::** related issue. 
I have another file in **/etc/apt/apt.conf.d** with the proxy settings I had to remove the file to make it works.

**Comment by giang-nguyentbk** [comment] 2025-11-10 09:35
If you are building docker images based on Ubuntu 22.04. Probably try adding this at the beginning of the Dockerfile:
```Dockerfile
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates
RUN sed -i 's|http://|https://|g' /etc/apt/sources.list
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN apt-get update
```
