### ISSUE TITLE
remote calls of docker image result in images returned with version and also with <none>

### ISSUE THREAD

**Issue by IngoS11** [docker/docker#25725] opened 2016-08-15 17:37 UTC
**Output of `docker version`:**

```
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
i809781@mo-d6c40141a:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 215
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 134
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.851 GiB
Name: mo-d6c40141a
ID: 7SCG:FJK3:BLDB:4EEO:3UIQ:MBOM:LF7K:SZ4H:HWIV:5HHP:EZOB:DG5Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.wdf.sap.corp:8080
Https Proxy: http://proxy.wdf.sap.corp:8080
No Proxy: localhost,sap.corp
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Steps to reproduce the issue:**
1. on machine 1 configure docker listening TCP port
2. on machine 2 set DOCKER_HOST to point to machine 1
3. on machine 2 call docker images

**Describe the results you received:**
A list where each container has 2 entries one with a version number and one with version `<none>`

**Describe the results you expected:**
Only the ones with version numbers should be returned

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2017-01-04 16:05
This is not a bug; images without a `tag` are shown if an image is pulled by _digest_ If you use `docker images --digests`, you'll see that the `DIGEST` column is not empty for those images;

```
docker images --digests
REPOSITORY          TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
nginx               <none>              sha256:30e3a72672e4c4f6a5909a69f76f3d8361bd6c00c2605d4bf5fa5298cc6467c2   f1fae62370b4        7 days ago          54.3 MB
```

Given that an image with a specific digest can be tagged under multiple names/tags, those images can be shown separately.

Docker 1.13 improves this though; if only a single image is present for a digest, the images are combined on a single line;

```
docker images --digests
REPOSITORY          TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
nginx               alpine              sha256:30e3a72672e4c4f6a5909a69f76f3d8361bd6c00c2605d4bf5fa5298cc6467c2   f1fae62370b4        7 days ago          54.3 MB
```

Related issue; https://github.com/docker/docker/issues/15508, and pull request https://github.com/docker/docker/pull/23996

I'll close this issue, because this will be improved in 1.13, but feel free to comment after I closed

**Closed by thaJeztah** 2017-01-04 16:05 UTC
Labels: version/1.12
