### ISSUE TITLE
Chown doesn't work in Docker 1.8.3

### ISSUE THREAD

**Issue by gibbster** [docker/docker#21237] opened 2016-03-16 03:06 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 51
Images: 346
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 448
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 8
Total Memory: 1.955 GiB
Name: default
ID: PJ2N:XOGL:5SLF:C3QZ:GLJ5:32HL:3G57:GT3W:6K6G:EVSD:ST5U:O3PU
Debug mode (server): true
File Descriptors: 16
Goroutines: 26
System Time: 2016-03-16T03:03:07.357815758Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Use this Dockerfile:
```
FROM jenkins:1.596
 
USER root
COPY jenkins_config/. /var/jenkins_home/
RUN chown -Rv jenkins:jenkins /var/jenkins_home/
RUN ls -l /var/jenkins_home/
```
2. Run `docker build -t chown-error`

**Describe the results you received:**
```
tep 0 : FROM jenkins:1.596
 ---> 5368c4eb049a
Step 1 : USER root
 ---> Using cache
 ---> 8842bc23d114
Step 2 : COPY jenkins_config/. /var/jenkins_home/
 ---> bfd98187d773
Removing intermediate container 50fd51823914
Step 3 : RUN chown -Rv jenkins:jenkins /var/jenkins_home/
 ---> Running in bb8712a7e611
ownership of '/var/jenkins_home/.bashrc' retained as jenkins:jenkins
changed ownership of '/var/jenkins_home/nodeMonitors.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/hudson.tasks.Ant.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/hudson.triggers.SCMTrigger.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/jenkins.model.JenkinsLocationConfiguration.xml' from root:root to jenkins:jenkins
ownership of '/var/jenkins_home/.bash_logout' retained as jenkins:jenkins
changed ownership of '/var/jenkins_home/jobs/hello-world/config.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/jobs/hello-world' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/jobs' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/hudson.plugins.git.GitTool.xml' from root:root to jenkins:jenkins
ownership of '/var/jenkins_home/.profile' retained as jenkins:jenkins
changed ownership of '/var/jenkins_home/jenkins.model.DownloadSettings.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/hudson.model.UpdateCenter.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/config.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/hudson.plugins.git.GitSCM.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/jenkins.model.ArtifactManagerConfiguration.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/hudson.scm.CVSSCM.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/hudson.tasks.Mailer.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/hudson.maven.MavenModuleSet.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/org.jenkinsci.plugins.gitclient.JGitTool.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/hudson.tasks.Maven.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/hudson.scm.SubversionSCM.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/hudson.tasks.Shell.xml' from root:root to jenkins:jenkins
changed ownership of '/var/jenkins_home/jenkins.mvn.GlobalMavenConfig.xml' from root:root to jenkins:jenkins
ownership of '/var/jenkins_home/' retained as jenkins:jenkins
 ---> c6114d0a1917
Removing intermediate container bb8712a7e611
Step 4 : RUN ls -l /var/jenkins_home/
 ---> Running in 567fa53c3088
total 76
-rw-r--r-- 1 root root 1290 Mar 16 00:58 config.xml
-rw-r--r-- 1 root root  809 Mar 15 06:21 hudson.maven.MavenModuleSet.xml
-rw-r--r-- 1 root root  159 Mar 16 01:02 hudson.model.UpdateCenter.xml
-rw-r--r-- 1 root root  320 Mar 15 06:21 hudson.plugins.git.GitSCM.xml
-rw-r--r-- 1 root root  371 Mar 15 06:21 hudson.plugins.git.GitTool.xml
-rw-r--r-- 1 root root  481 Mar 15 06:21 hudson.scm.CVSSCM.xml
-rw-r--r-- 1 root root  350 Mar 15 06:21 hudson.scm.SubversionSCM.xml
-rw-r--r-- 1 root root  145 Mar 15 06:21 hudson.tasks.Ant.xml
-rw-r--r-- 1 root root  188 Mar 15 06:21 hudson.tasks.Mailer.xml
-rw-r--r-- 1 root root  319 Mar 16 00:58 hudson.tasks.Maven.xml
-rw-r--r-- 1 root root   76 Mar 15 06:21 hudson.tasks.Shell.xml
-rw-r--r-- 1 root root  215 Mar 15 06:21 hudson.triggers.SCMTrigger.xml
-rw-r--r-- 1 root root  159 Mar 15 06:21 jenkins.model.ArtifactManagerConfiguration.xml
-rw-r--r-- 1 root root  137 Mar 15 06:21 jenkins.model.DownloadSettings.xml
-rw-r--r-- 1 root root  253 Mar 15 06:21 jenkins.model.JenkinsLocationConfiguration.xml
-rw-r--r-- 1 root root  247 Mar 15 06:21 jenkins.mvn.GlobalMavenConfig.xml
drwxr-xr-x 3 root root 4096 Mar 16 01:12 jobs
-rw-r--r-- 1 root root  907 Mar 16 01:02 nodeMonitors.xml
-rw-r--r-- 1 root root  244 Mar 15 06:21 org.jenkinsci.plugins.gitclient.JGitTool.xml
 ---> ee1725b3cd8b
Removing intermediate container 567fa53c3088
Successfully built ee1725b3cd8b
```

**Describe the results you expected:**
I would expect the results of `RUN ls -l /var/jenkins_home` would show that all the files in the directory are owned by jenkins.

**Additional information you deem important (e.g. issue happens only occasionally):**

Thanks for your help! Really appreciate any pointers.

**Comment by gibbster** [comment] 2016-03-16 03:22
I also tried upgrading to 1.10.3, with the same results

**Comment by thaJeztah** [comment] 2016-03-16 07:14
yes, this is expected; the reason here, is that the Jenkins image marks that directory as a `VOLUME`; https://github.com/jenkinsci/docker/blob/e7d56fa71d44ace1f1d8258ef216bba64f266cca/Dockerfile

As a result, Docker creates a new volume for each step in your Dockerfile, copying the original files from the image to that Volume. Any change you make to that directory will thus be made in a Volume, so won't be saved in the image.

If I remember correctly, you can specify a `JENKINS_HOME` env-var to have the Jenkins image to copy files from a different location at runtime; that way you can add your custom content to a different path, with the right permissions. Please check the documentation for the Jenkins image https://hub.docker.com/_/jenkins/

I'm going to close this issue, because this is not a bug, but feel free to comment here after I've closed the issue :+1:

**Closed by thaJeztah** 2016-03-16 07:14 UTC

**Comment by gibbster** [comment] 2016-03-16 13:51
Ah, that makes sense. Thanks for your help!
