### ISSUE TITLE
run docker in Container

### ISSUE THREAD

**Issue by pengwugithub** [docker/docker#32323] opened 2017-04-03 15:49 UTC
can i  install docker in Container with image Centos or ubuntu?

**Comment by thaJeztah** [comment] 2017-04-03 15:57
Yes, it's possible to run docker-in-docker (docker running inside a docker container), but you'll likely need;

- to run the container with `--privileged` (be aware that this disables all security that containers provide, so processes _can_ escape the container and take control of the host)
- for graph-drivers (copy-on-write) to work, the `/var/lib/docker` directory should use a volume.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-04-03 15:57 UTC

**Comment by pengwugithub** [comment] 2017-04-05 12:47
thanks， i use the offical image docker.i works on my pc.
i want to run it on Bluemix,but Bluemix container doesn't support --privileged.
can i run an image of centos,and install  docker in it?

**Comment by thaJeztah** [comment] 2017-04-05 12:50
Without `--privileged` it won't be able to run (same for a `centos` image). I can imagine BlueMix doesn't allow setting privilege for the reason I mentioned (i.e., with `--privileged`, you can take control of the host), which likely not what they want 😇

**Comment by pengwugithub** [comment] 2017-04-05 13:20
I see, thank you very much.
it's sad.
