### ISSUE TITLE
Files are created "behind" a bind mount. 

### ISSUE THREAD

**Issue by rlewkowicz** [docker/docker#24757] opened 2016-07-18 15:31 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Output of `docker version`:**
```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:
```
 OS/Arch:      linux/amd64(paste your output here)
```
CentOS Linux release 7.2.1511 (Core)
Linux hostname 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
**Output of `docker info`:**

```
Containers: 12
 Running: 4
 Paused: 0
 Stopped: 8
Images: 6
Server Version: 1.12.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-253:1-134271986-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.166 GB
 Data Space Total: 107.4 GB
 Data Space Available: 38.28 GB
 Metadata Space Used: 3.588 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
ID: P7TW:SN6P:6PE2:K6S4:JFTE:IW5R:SVAM:UCKT:36YU:MBCJ:GR5E:HNZS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Openstack

**Steps to reproduce the issue:**
Create a bindmount eg: 'mount -o bind /app/parsoid /etc/parsoid' 
/app is an attached volume. I have various directories mounted on system folders from this app directory.

```
[root@wiki app]# ll
total 28
drwx------.  2 root              root     16384 Jul 11 19:51 lost+found
drwxr-xr-x. 15 nginx             nginx     4096 Jul 11 20:25 mediawiki
drwxr-xr-x.  5 systemd-bus-proxy ssh_keys  4096 Jul 18 14:51 mysql
drwxr-xr-x.  2 root              root      4096 Jul 18 14:11 parsoid
-rw-r--r--.  1 root              root         0 Jul 18 14:10 THESE_ARE_ALL_BINDMOUNTS
```
These are mounted in various locations. The folders work as intended. So /etc/mysql, /var/www/mediawiki. These work fine with:

/etc/mysql:/etc/mysql/conf.d/.my.cnf
/var/www/mediawiki:/var/www/mediawiki

but with the parsoid service, I'm only looking to mount 2 files. 

/etc/parsoid/config.yaml:/parsoid/config.yaml
/etc/parsoid/localsettings.js:/parsoid/localsettings.js

It will create a folder called /etc/parsoid/localsettings.js behind the mount, and mount that. 

I can mount /app/parsoid/localsettings.js without issue.

**Comment by cpuguy83** [comment] 2016-07-18 15:35
Can you provide the full details of how the container is created?

**Comment by rlewkowicz** [comment] 2016-07-18 15:44
Sure! @cpuguy83 

This particular container is created using the following Docker file:

```
FROM alpine:3.4

# ENV VERSION=v0.10.46 CFLAGS="-D__USE_MISC" NPM_VERSION=2
# ENV VERSION=v0.12.15 NPM_VERSION=2
# ENV VERSION=v4.4.7 NPM_VERSION=2
# ENV VERSION=v5.12.0 NPM_VERSION=3
ENV VERSION=v6.3.0 NPM_VERSION=3

# For base builds
# ENV CONFIG_FLAGS="--without-npm" RM_DIRS=/usr/include
ENV CONFIG_FLAGS="--fully-static" DEL_PKGS="libgcc libstdc++" RM_DIRS=/usr/include

RUN apk add --no-cache curl make gcc g++ python linux-headers paxctl libgcc libstdc++ gnupg git && \
  gpg --keyserver ha.pool.sks-keyservers.net --recv-keys \
    9554F04D7259F04124DE6B476D5A82AC7E37093B \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93 \
    FD3A5288F042B6850C66B31F09FE44734EB7990E \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
    B9AE9905FFD7803F25714661B63B535A4C206CA9 && \
  curl -o node-${VERSION}.tar.gz -sSL https://nodejs.org/dist/${VERSION}/node-${VERSION}.tar.gz && \
  curl -o SHASUMS256.txt.asc -sSL https://nodejs.org/dist/${VERSION}/SHASUMS256.txt.asc && \
  gpg --verify SHASUMS256.txt.asc && \
  grep node-${VERSION}.tar.gz SHASUMS256.txt.asc | sha256sum -c - && \
  tar -zxf node-${VERSION}.tar.gz && \
  cd node-${VERSION} && \
  export GYP_DEFINES="linux_use_gold_flags=0" && \
  ./configure --prefix=/usr ${CONFIG_FLAGS} && \
  NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
  make -j${NPROC} -C out mksnapshot BUILDTYPE=Release && \
  paxctl -cm out/Release/mksnapshot && \
  make -j${NPROC} && \
  make install && \
  paxctl -cm /usr/bin/node && \
  cd / && \
  if [ -x /usr/bin/npm ]; then \
    npm install -g npm@${NPM_VERSION} && \
    find /usr/lib/node_modules/npm -name test -o -name .bin -type d | xargs rm -rf; \
  fi && \
  apk del curl make gcc g++ python linux-headers paxctl gnupg ${DEL_PKGS} && \
  rm -rf /node-${VERSION}.tar.gz /SHASUMS256.txt.asc /node-${VERSION} ${RM_DIRS} \
    /usr/share/man /tmp/* /var/cache/apk/* /root/.npm /root/.node-gyp /root/.gnupg \
    /usr/lib/node_modules/npm/man /usr/lib/node_modules/npm/doc /usr/lib/node_modules/npm/html

RUN cd / && \
git clone https://gerrit.wikimedia.org/r/p/mediawiki/services/parsoid && \
cd parsoid && \
```

I deploy it using chef, but the results can be replicated via the command line (the container matches the one above):

docker run -it -v /etc/parsoid/localsettings.js:/parsoid/localsettings.js rlewkowicz/parsoid /bin/sh

The files in question are just the ones from /parsoid in the container with the example extensions.

**Comment by cpuguy83** [comment] 2016-07-18 15:49
@rlewkowicz And what is happening with `/parsoid/localsettings.js` in the container?

**Comment by rlewkowicz** [comment] 2016-07-18 15:54
In the container, that file does not exist. It's mounted as a folder if I mount via the bind mount. /etc/parsoid/localsettings.js. It's mounted as a file if I mount it directly from it's source folder /app/parsoid/localsettings.js

**Comment by justincormack** [comment] 2016-07-19 12:17
What does `mount` say on the host? It sounds like one of the issues with mounts needing to be shared or being private at a guess, so the process doing the bind to make the contaienr is not seeing the bind mount.

**Comment by rlewkowicz** [comment] 2016-07-19 13:17
@justincormack mount doesn't show any of the mounts I am creating via the -o bind method. 

Just to strip out the guff, I ran this as a quick test and got similar results:

mkdir source
touch source/file
mkdir mount
mount -o bind source mount
ls -lah mount
docker run -v $(pwd)/mount/file:/mount/file alpine ls -lah /mount/file

```
[root@wiki ~]# docker run -v $(pwd)/mount/file:/mount/file alpine ls -lah /mount/file
total 0
drwxr-xr-x    2 root     root           6 Jul 19 13:05 .
drwxr-xr-x    3 root     root          17 Jul 19 13:13 ..
```

The information for this system is as listed in my first comment. I ran it on a similar system, this one running :

[root@wiki ~]# docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:
 OS/Arch:      linux/amd64
 Experimental: true

It works as expected:
[root@wiki ~]# docker run -v $(pwd)/mount/file:/mount/file alpine ls -lah /mount/file
-rw-r--r--    1 root     root           0 Jul 19 13:07 /mount/file


The only differences between the two systems I can think is one has drives mounted to it (not working), the other does not (working). I'll try to pin down the system differences today, see if I can't produce some better information.

**Comment by thaJeztah** [comment] 2016-09-19 23:40
ping @justincormack what's the status here?

**Comment by justincormack** [comment] 2016-09-20 14:58
@rlewkowicz I think this depends on whether your root filesystem is mounted as `shared` or not. The behaviour is non obvious. There is an article explaining it here https://lwn.net/Articles/689856/ that is pretty good. Many distros mount `/` as `rshared` now, so your expected behaviour will happen by default, but otherwise you need to `mount --bind --shared ...`.

**Comment by thaJeztah** [comment] 2016-09-20 16:24
Looks like this is a configuration issue then, and not a bug in docker. I'll close this issue, but feel free to comment if you think there's something left to be done

**Closed by thaJeztah** 2016-09-20 16:24 UTC
Labels: status/more-info-needed, version/1.12
