### ISSUE TITLE
rejoin node cause duplicate entries in 'docker node ls'

### ISSUE THREAD

**Issue by wayerr** [docker/docker#30059] opened 2017-01-11 14:28 UTC
**Description**

If node leave cluster - it remain record, when join again with same token it cause second record.

**Steps to reproduce the issue:**
1. deploy `docker-exp` node with docker (v 1.13.0-rc5) as manager in swarm-mode
2. obtain tokens:
```root@docker-exp ~ # docker swarm join-token worker
To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-1h4iqopyn0u7xa0x2ciayzxp466oqs3rzaz4iux7c5kqhyu8dk-5n7iwx0pwytopw98nwng7cb7p \
    172.31.0.12:4375
```
3.  deploy `nb` node with docker (v 1.13.0-rc5) 
4. join `nb` into cluster:
```r@nb ~ % docker swarm join \
    --token SWMTKN-1-1h4iqopyn0u7xa0x2ciayzxp466oqs3rzaz4iux7c5kqhyu8dk-5n7iwx0pwytopw98nwng7cb7p \
    172.31.0.12:4375
```
5. leave `nb` from cluster:
```r@nb ~ % docker swarm leave
Node left the swarm.
```
6. repeat steps 4 - 5

**Describe the results you received:**
```
root@docker-exp ~ # docker node ls
ID                           HOSTNAME    STATUS  AVAILABILITY  MANAGER STATUS
6qyfxfjw8hufsw4e64hkm0m56 *  docker-exp  Ready   Active        Leader
9uni3fxfkdl0beidvpvo03b9u    nb      Ready   Active        
jhvdz7aav45zbgluhwa7v0228    nb      Down   Active        
u4vuirdgwmivsw8jz793i610k    nb      Down    Active     
```

**Describe the results you expected:**

```
root@docker-exp ~ # docker node ls
ID                           HOSTNAME    STATUS  AVAILABILITY  MANAGER STATUS
6qyfxfjw8hufsw4e64hkm0m56 *  docker-exp  Ready   Active        Leader
9uni3fxfkdl0beidvpvo03b9u    nb      Ready   Active        
```

**Additional information you deem important (e.g. issue happens only occasionally):**

It happens any time, also on 1.12 version, and as i understand it design 'feature'.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971d7
 Built:        Thu Jan  5 00:49:22 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc5
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   43cc971d7
 Built:        Thu Jan  5 00:49:22 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.13.0-rc5
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 6qyfxfjw8hufsw4e64hkm0m56
 Is Manager: true
 ClusterID: 7tsqg8qdswyekk6ezrfkdm1bk
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.0.12
 Manager Addresses:
  172.31.0.12:4375
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.0-2-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 4.73 GiB
Name: docker-exp
ID: NBZW:2NVA:OYEW:GT4O:LULS:KFJZ:X463:7FJG:6FPU:3YDA:4OPG:2AO3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

nb - notebook,  docker-exp - virtualbox, all them has same docker and debian version.

**Comment by thaJeztah** [comment] 2017-01-11 14:37
Thanks for reporting! This looks to be a duplicate of https://github.com/docker/docker/issues/24088. Basically a worker can "leave" the swarm, but does not have permissions to make changes to the raft (i.e. remove itself from that). `docker swarm leave` only removes the swarm related information from the node itself, but does not de-register it from the swarm.

The only way to _remove_ a node from the swarm, is to run `docker node rm <some node>` on a manager.

When re-joining a node again, a new cryptographic identity is created for the node; therefore the same node appears under a new ID in `docker node ls`.

I'll close this issue, because it's a duplicate of https://github.com/docker/docker/issues/24088, but you can stay informed on updates by subscribing to that issue. Also feel free to comment here after I closed the issue 👍

**Closed by thaJeztah** 2017-01-11 14:37 UTC
Labels: area/swarm, version/1.13

**Comment by wayerr** [comment] 2017-01-11 15:35
> a new cryptographic identity is created for the node;

why not using ID from docker key file as node identifier (or as base for it):

```root@docker-exp ~ # cat /etc/docker/key.json 
{
...
    "kid": "NBZW:2NVA:OYEW:GT4O:LULS:KFJZ:X463:7FJG:6FPU:3YDA:4OPG:2AO3",
...
```
Or detect on master that  we have node duplicates by node address, because cluster can not has multiple nodes with same 'ip:port' pair.

**Comment by thaJeztah** [comment] 2017-01-11 17:55
The `key.json` is not managed by swarm, and not part of the raft data, so will not be used for that, but let's take the discussion to the linked issue, so that it's taking place in a single place
