### ISSUE TITLE
attach to a container via a TCP proxy

### ISSUE THREAD

**Issue by binocarlos** [docker/docker#11714] opened 2015-03-24 16:55 UTC
Hi,

If I do this command directly against the unix socket - it works:

```bash
$ docker run ubuntu echo hello
hello
```

I then start a socat container - one that forwards TCP traffic onto the UNIX socket.

```
$ docker run -d \
   -p 2375:2375 \
   -v /var/run/docker.sock:/var/run/docker.sock \
   sequenceiq/socat
```

The socat command this is doing:

```
socat -d -d TCP-L:2375,fork UNIX:/var/run/docker.sock
```

I can do `docker ps` no problems via the TCP proxy:

```bash
$ DOCKER_HOST=tcp://localhost:2375 docker ps
```

However - when I try to attach to a container via the TCP proxy - I get no return value:

```bash
$ DOCKER_HOST=tcp://localhost:2375 docker run ubuntu echo hello
```

When I run `socat` on the host and not in a container - it works fine.

Does anyone have any ideas what is going on here?  It is causing some problems developing [powerstrip](https://github.com/clusterhq/powerstrip)

**Comment by binocarlos** [comment] 2015-03-24 17:18
I've just tried a similar thing on boot2docker and the socat container works.

It's worth noting the example above was on an ubuntu 14 machine:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
$ uname -a
Linux node1 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ docker info
Containers: 2
Images: 115
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 119
Execution Driver: native-0.2
Kernel Version: 3.13.0-45-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: node1
ID: 4JUO:6BWB:72BR:UNTU:JUAA:TUVV:6BQ6:HJUA:OEYU:3RTB:5ANV:ONER
Username: binocarlos
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

**Comment by guildencrantz** [comment] 2015-03-26 02:07
I'm unable to reproduce this (echo comes through fine) on a _slightly_ updated system:

    $ cat /etc/lsb-release                                                                                                                              
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=14.04
    DISTRIB_CODENAME=trusty
    DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

    $ uname -a                                                                                                                                          
    Linux rpco-mhenk1410 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    $ docker info                                                                                                                                      
    Containers: 24
    Images: 169
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 217
    Execution Driver: native-0.2
    Kernel Version: 3.13.0-48-generic
    Operating System: Ubuntu 14.04.2 LTS
    CPUs: 4
    Total Memory: 15.58 GiB

**Comment by cpuguy83** [comment] 2015-07-22 03:15
Closing as I can't reproduce and the issue seems quite dead.

**Comment by cpuguy83** [comment] 2015-07-22 03:16
Also note, this could be something like apparmor interfering.

**Closed by cpuguy83** 2015-07-22 03:15 UTC
