### ISSUE TITLE
Potential docker service "--dns" flag for custom service discovery resolution?

### ISSUE THREAD

**Issue by samholmes1337** [docker/docker#25477] opened 2016-08-07 23:48 UTC
For internal network applications I like to be able to namespace internal services with DNS (such as `front-end.project.service`). Of course due to the limitations of service names (namely that they can't contain `.`s) this ends up either being impossible or inelegant, such as using hyphens instead.

I'm sure there are other use cases where the option to specify a custom DNS address would be useful. I have searched the issues and docs so my apologises if this has been suggested before, looking forward to your thoughts!

**Comment by thaJeztah** [comment] 2016-08-08 19:24
I think what you're looking for is `--network-alias` (which currently isn't available for services), there's an open issue for that here: https://github.com/docker/docker/issues/24787

Basically, similar to `docker run --network=my-network --network-alias=foo.bar.com --name foo ....`

I'll close this issue, because I think this is a duplicate of https://github.com/docker/docker/issues/24787, but feel free to comment if you think I closed this by mistake. Thanks for reporting!

**Closed by thaJeztah** 2016-08-08 19:24 UTC

**Comment by samholmes1337** [comment] 2016-08-09 16:18
Ah wonderful, thank you very much this is exactly what I was looking for!
