### ISSUE TITLE
Docker 1.7.1 --dns-search

### ISSUE THREAD

**Issue by k2xl** [docker/docker#15238] opened 2015-08-02 20:17 UTC
--dns-search Doesn't seem to be passing thru to the /etc/resolv.conf on 1.7.1. On 1.7.0 it appears to be working.

Trying to use consul:
```echo "DOCKER_OPTS='--dns $DOCKER_BRIDGE_IP --dns 8.8.8.8 --dns-search service.consul'" >> /etc/default/docker```

The etc/resolv.conf looks to be the default. On 1.7.0 I see "search service.consul"

Also using host networking

**Comment by aboch** [comment] 2015-08-03 19:47
@k2xl I tried 1.6.2, 1.7.0, 1.7.1 and 1.8.0-rc1 with `--dns-search` and `--net=host`

I see the dns-search parameter appended to /etc/resolv.conf only in 1.7.0

This makes me think it should not be there (as this was the behavior in 1.6.2) and got fixed in 1.7.1

**Comment by aboch** [comment] 2015-08-03 20:19
@k2xl What you see in 1.7.1 is the expected behavior.
Looks like this was a bug in 1.7.0. The fix that went in 1.7.1 is from [here](https://github.com/docker/libnetwork/pull/351)

Basically in host networking mode the expected behavior is that in the container both `/etc/hosts` and `/etc/resolv.conf` files should be copies from the host's corresponding files, and specifying the `--dns-search` should have no effect.

**Comment by thaJeztah** [comment] 2015-08-03 22:27
I'm going to close this issue, because this looks to be the expected behavior, but feel free to ping me if you think I closed this by mistake. Thanks for reporting, @k2xl !

**Closed by thaJeztah** 2015-08-03 22:27 UTC
