### ISSUE TITLE
devicemapper: Can't set cookie dm_task_set_cookie failed

### ISSUE THREAD

**Issue by marburger93** [docker/docker#30990] opened 2017-02-13 23:57 UTC
**Description**

Docker will not start. I have a debian 8 server from ovh with the newest packets. I have many servers and on all other servers docker is running fine.

Linux SERVERNAME 3.14.32-xxxx-grs-ipv6-64 #1 SMP Tue Jun 30 18:50:21 CEST 2015 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1. sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
2. echo "deb https://apt.dockerproject.org/repo debian-jessie main" > /etc/apt/sources.list.d/docker.list
3. apt-get install apt-transport-https ca-certificates && sudo apt-get update && apt-get install docker-engine
4. sudo systemctl start docker

**Describe the results you received:**

```
Feb 14 00:34:51 srv05 dockerd[27789]: time="2017-02-14T00:34:51.453387525+01:00" level=info msg="libcontainerd: new containerd process, pid: 27796"
Feb 14 00:34:52 srv05 dockerd[27789]: time="2017-02-14T00:34:52.455454964+01:00" level=error msg="[graphdriver] prior storage driver devicemapper failed: devicemapper: Can't set cookie dm_task_set_cookie failed"
Feb 14 00:34:52 srv05 dockerd[27789]: Error starting daemon: error initializing graphdriver: devicemapper: Can't set cookie dm_task_set_cookie failed
Feb 14 00:34:52 srv05 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Feb 14 00:34:52 srv05 systemd[1]: Failed to start Docker Application Container Engine.
Feb 14 00:34:52 srv05 systemd[1]: Unit docker.service entered failed state.
Feb 14 00:34:52 srv05 systemd[1]: Starting Docker Application Container Engine...
Feb 14 00:34:52 srv05 systemd[1]: docker.service start request repeated too quickly, refusing to start.
Feb 14 00:34:52 srv05 systemd[1]: Failed to start Docker Application Container Engine.
Feb 14 00:34:52 srv05 systemd[1]: Unit docker.socket entered failed state.
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Not installed, clean debian 8 server without virtualization or other changes.

**Comment by thaJeztah** [comment] 2017-03-21 12:28
OVH is using custom kernels, and those have led to various issues / incompatibilities. The default kernel version for Debian Jessie (Debian 8) is 3.16; https://wiki.debian.org/DebianJessie.

I suggest trying to get a machine with a default kernel version for Debian Jessie, and see if you're still able to reproduce.

I'm closing this issue, because of the above, and because custom kernel versions are not supported, but feel free to continue the conversation

**Closed by thaJeztah** 2017-03-21 12:28 UTC
Labels: area/storage/devicemapper

**Comment by toravir** [comment] 2017-07-22 05:31
I get the same error when doing a "make BIND_DIR=. shell" - while going through: https://docs.docker.com/opensource/project/set-up-dev-env/#task-2-start-a-development-container

My Kernel is : 
$ uname -a
Linux centos-master 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Do i need to get to ubuntu ??
