### ISSUE TITLE
rmi - "unexpected end of JSON input"

### ISSUE THREAD

**Issue by klochner** [docker/docker#8640] opened 2014-10-17 20:10 UTC
$ docker images | head -n 2 
REPOSITORY                     TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
myuser/myproject               latest              b64cde03d220        13 hours ago        1.013 GB

$ docker rmi b64cde03d220 
Error response from daemon: unexpected end of JSON input 
2014/10/17 13:05:07 Error: failed to remove one or more images

$ uname -a
Darwin klochner.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64

$ docker version
Client version: 1.3.0
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f
OS/Arch (client): darwin/amd64
Server version: 1.3.0
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): c78088f

$ docker -D info
Containers: 3
Images: 129
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 138
Execution Driver: native-0.2
Kernel Version: 3.16.4-tinycore64
Operating System: Boot2Docker 1.3.0 (TCL 5.4); master : a083df4 - Thu Oct 16 17:05:03 UTC 2014
Debug mode (server): true
Debug mode (client): true
Fds: 11
Goroutines: 11
EventsListeners: 0
Init Path: /usr/local/bin/docker

**Comment by jfrazelle** [comment] 2015-02-26 01:38
I canno reproduce, closing but if you are able to reproduce please give us all logs and the exact steps to reproduce

**Closed by jfrazelle** 2015-02-26 01:38 UTC

**Comment by arthurk** [comment] 2015-02-28 10:53
@jfrazelle after posting above i've never ran into the same error again and cannot reproduce it anymore. I'm ok with closing it.

**Comment by ibuildthecloud** [comment] 2015-02-28 15:02
@jfrazelle while building RancherOS we found its pretty easy to run into similar errors as this by doing a lot of abusive reboots.  Since there is no sync to disk when Json files are written it easy to get corrupted json files if you reboot while things are still buffered.  I can open a seperate issue to talk about this, but just giving you a heads up.
