### ISSUE TITLE
docker does not remove btrfs subvolumes when destroying container

### ISSUE THREAD

**Issue by phemmer** [docker/docker#9939] opened 2015-01-07 03:50 UTC
I receive the following error when deleting a container which created a btrfs subvolume (as happens when you run docker in docker).

```
# docker run --rm fedora:20 sh -c 'yum -y -q install btrfs-progs && btrfs subvolume create /test'
Public key for lzo-2.08-1.fc20.x86_64.rpm is not installed
Public key for e2fsprogs-libs-1.42.8-3.fc20.x86_64.rpm is not installed
Importing GPG key 0x246110C1:
 Userid     : "Fedora (20) <fedora@fedoraproject.org>"
 Fingerprint: c7c9 a9c8 9153 f201 83ce 7cba 2eb1 61fa 2461 10c1
 Package    : fedora-release-20-3.noarch (@fedora-updates/$releasever)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-20-x86_64
Create subvolume '//test'
FATA[0033] Error response from daemon: Cannot destroy container c9badf5fc87bb9bfb50a3ee6e5e7c840476bd704e62404c9136aab4d27239d1e: Driver btrfs failed to remove root filesystem c9badf5fc87bb9bfb50a3ee6e5e7c840476bd704e62404c9136aab4d27239d1e: Failed to destroy btrfs snapshot: directory not empty 
```

Info:

```
# docker info
docContainers: 22
Images: 47
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.13.2-gentoo
Operating System: Gentoo/Linux
CPUs: 8
Total Memory: 15.64 GiB
Name: whistler
ID: RL3I:O6RS:UJRN:UU74:WAGE:4X5B:T2ZU:ZRSU:BN6Q:WN7L:QTPM:VCLN
Username: phemmer
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

# docker version
Client API version: 1.16
Go version (client): go1.3.3
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

**Comment by tianon** [comment] 2015-01-07 03:55
@jfrazelle didn't you look into this?  Did you get anywhere good? :)

**Comment by jfrazelle** [comment] 2015-01-07 04:01
still looking i really want to fix this, but it is a permissions thing, because we are making the same exact syscall as `btrfs-tools`

**Comment by jfrazelle** [comment] 2015-01-07 04:01
but this is a duplicate issue

**Comment by jfrazelle** [comment] 2015-01-07 04:03
duplicate of https://github.com/docker/docker/issues/7773, closing, lmk tho if you believe differently

**Comment by jfrazelle** [comment] 2015-01-07 04:04
actually I like your better, I'm going to close the other

**Comment by tianon** [comment] 2015-01-09 04:48
This is something else, @jfrazelle. :smile:

This is sub-subvolumes with BTRFS (ie, docker-in-docker artifacts, etc).  This is why we had to add `sort -r` to our nuke script (so that it'd delete the inner subvolumes before the outer ones).

**Comment by jfrazelle** [comment] 2015-01-13 01:19
pretty sure we need this but in go lol https://lists.linuxcontainers.org/pipermail/lxc-devel/2014-July/009881.html

**Comment by jfrazelle** [comment] 2015-01-13 01:20
working on a port

**Comment by jfrazelle** [comment] 2015-01-13 02:13
but if someone else who is super good at C wants to do it go ahead :P

**Comment by rgbkrk** [comment] 2015-03-03 15:58
@tianon What are you using for a nuke script now?

**Comment by tianon** [comment] 2015-03-05 16:29
@rgbkrk https://github.com/docker/docker/blob/620339f166984540f15aadef2348646eee9a5b42/contrib/nuke-graph-directory.sh :wink:

**Comment by rgbkrk** [comment] 2015-03-06 23:19
Awesome, thank you!

**Comment by TomasTomecek** [comment] 2015-07-20 13:01
Still hitting this. Are you planning to address this anytime soon?

**Closed** 2015-08-26 21:00 UTC
Labels: exp/expert, kind/bug, status/help-wanted, system/btrfs

**Comment by pkajaba** [comment] 2016-03-03 13:13
I had problem with this today (BTRFS seemed out of space because of it) with version 1.9.1

Any progress?

**Comment by TomasTomecek** [comment] 2016-03-07 17:18
I had to manually remove the nested subvolumes using `$ btrfs` directly.

**Comment by pkajaba** [comment] 2016-03-07 21:18
@TomasTomecek me too

**Comment by santosh0705** [comment] 2016-04-26 05:49
I'm having this problem too.

**Comment by prateeksahu** [comment] 2016-05-05 10:00
Does any one know of any workaround for it? the btrfs seems to be corrupted for me and somehow i need to make atleast the machine filesystem work.

**Comment by InAnimaTe** [comment] 2016-06-01 16:18
To anyone else having to derp with this, I had to do similar to @TomasTomecek 

```
┌[root@lovell] 
└[/var/lib/docker]> btrfs subvolume delete btrfs/subvolumes/*
```

^that worked for me ;)

**Comment by thechane** [comment] 2016-07-06 21:28
Anyone know a way to distinguish the orphan subvolumes? I don't want to blow away my running containers.

**Comment by RomainVernoux** [comment] 2017-02-15 09:27
I encountered the issue in v1.13 in my CI environment. I eventually figured out that it occured when multiple Jenkins jobs were doing `docker system prune` simultaneously on a btrfs filesystem. Is there any doc or information regarding thread-safety of the docker daemon?

**Comment by hipposareevil** [comment] 2017-03-06 12:44
@thechane 
I wrote a script that traverses the docker structures and finds what directories are orphaned and optionally deletes them. If it'd be useful to people I can put up on github and share here. I've only done basic testing on oraclelinux but it should apply to other OSes.

**Comment by justincormack** [comment] 2017-03-06 13:08
Can you open a new issue for the multiple prune on btrfs issue?

**Comment by julienlau** [comment] 2017-08-22 07:21
Fix embedded in "docker clean" would be nice

**Comment by huegelc** [comment] 2017-09-21 19:47
still hitting this bug. btrfs/subvolumes grows very fast.

**Comment by johnharris85** [comment] 2017-09-25 18:22
@hipposareevil if you can post that script it would be super useful please :)

**Comment by hipposareevil** [comment] 2017-09-25 18:27
@johnharris85   Turns out that my script would negatively affect the system as it was deleting subvolumes that were tied to images. So if you tried to remove an image, it would be broken.  It would work while you were running things, but then later when manipulating images you'd be hosed. :|

**Comment by johnharris85** [comment] 2017-09-25 18:38
OK thanks @hipposareevil, anyway to filter out those volumes that were being used by images as well? Mind posting the script anyway (even as a gist) so I can hack on it?

**Comment by hipposareevil** [comment] 2017-10-03 17:23
@johnharris85 Shoot me an email at dockergist@mailinator.com

**Comment by einyx** [comment] 2017-11-06 02:10
This is *still* an issue :cry:

**Comment by piahoo** [comment] 2017-11-28 10:02
my subvolumes on btrfs grows to 222gb

**Comment by huegelc** [comment] 2017-11-28 12:51
I´ve deactivated btrfs for now and I´m using overlay2

**Comment by julienlau** [comment] 2017-12-04 11:29
with docker 1.13+ you have the command below that can help:
docker system prune -f

**Comment by JonasT** [comment] 2018-02-03 14:54
Since people here say this still happens, maybe it might be a good idea to reopen this ticket?

**Comment by beerendlauwers** [comment] 2018-03-21 13:18
@huegelc Does the overlay2 driver work on a `btrfs` file system? The [documentation](https://docs.docker.com/storage/storagedriver/overlayfs-driver/) says only `ext4` and `xfs` are supported.

**Comment by devopxy** [comment] 2018-08-14 16:01
Using btrfs commands I could remove those sub-volumes  e.g. : 
```
btrfs subvolume delete eb669bae4f4aa17f3c432d956f481146e4ac77e3f1803fee15e1f2b17787510d-init

```

**Comment by StefanTT** [comment] 2018-08-21 06:56
It still happens for me.
Docker version 18.06.0-ce, build 0ffa8257ec

**Comment by JonasT** [comment] 2018-08-21 20:12
@devopxy yea that works, but it doesn't solve the underlying problem...

**Comment by tmalavash** [comment] 2018-09-18 13:09
> Using btrfs commands I could remove those sub-volumes e.g. :
> 
> ```
> btrfs subvolume delete eb669bae4f4aa17f3c432d956f481146e4ac77e3f1803fee15e1f2b17787510d-init
> ```

Thx devopxy, that work for me to...
This command delete all sub-volumes present is the current directory :
btrfs subvolume delete *

**Comment by t3kka** [comment] 2018-11-08 03:34
Just ran into this today and had to clean it out. There doesn't appear to be any real solution...is there?

**Comment by mwaeckerlin** [comment] 2019-11-21 11:38
Loop:
- #9939 closed as duplicate of #7773
- #7773 closed as duplicate of #9939

Please reopen and fix #9939!

I just had to cleanup due to the same reason!

**Comment by Primetalk** [comment] 2021-07-21 08:06
Experiencing the same issue.

```
# docker system prune -f
Total reclaimed space: 0B
# du -sh /var/lib/docker/btrfs/subvolumes
16G	/var/lib/docker/btrfs/subvolumes
```
The following helps:
```
pushd /var/lib/docker/btrfs/subvolumes/
btrfs subvolume delete *
popd
```

**Comment by Primetalk** [comment] 2021-07-21 08:20
Experiencing the same issue.

```
# docker system prune -f
Total reclaimed space: 0B
# du -sh /var/lib/docker/btrfs/subvolumes
16G	/var/lib/docker/btrfs/subvolumes
```
The following helps:
```
pushd /var/lib/docker/btrfs/subvolumes/
btrfs subvolume delete *
popd
```

**Comment by atk91** [comment] 2021-08-04 11:01
> The following helps:
> 
> ```
> pushd /var/lib/docker/btrfs/subvolumes/
> btrfs subvolume delete *
> popd
> ```

This may break your `docker build` cache and other stuff

**Comment by Primetalk** [comment] 2021-08-06 11:21
> This may break your docker build cache and other stuff

What would you suggest?

**Comment by hcoin** [comment] 2021-08-11 13:59
ONLY WHEN ceph -s reports 'totally normal, everything you care about is running and all is perfect' -- do
docker system prune -a --volumes
If you do it under any other ceph operating condition -- not good.

**Comment by jaz000** [comment] 2022-01-22 23:30
Is there a reason why I can't just delete the unused subvolumes (apart from perhaps identifying them) manually executing the step that docker failed to do?

I'm thinking: 
touch a given file in in root of each running container manually in the containers shell (maybe other partitions as well if configured? mine don't)
look in docker/btrfs/subvolumes for the entries that have most recent timestamps and check the file in in there
remove all the rest with "btrfs subvolume delete btrfs/subvolumes/<id of each>"

is that a safe way to clean up the unused subvolumes?

uninstalling and re-installing docker seems like a lot of extra hard work ...

thanks

**Comment by Primetalk** [comment] 2022-02-21 16:13
@hcoin, This indeed helps:
```shell
docker system prune -a --volumes
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all volumes not used by at least one container
  - all images without at least one container associated to them
  - all build cache

Are you sure you want to continue? [y/N] y
Deleted Volumes:
...
Deleted Images:
...
Total reclaimed space: 5.033GB
```

**Comment by hcoin** [comment] 2022-02-21 16:16
On 2/21/22 10:13, Arseniy Zhizhelev wrote:
> docker system prune -a --volumes

Thanks!  That probably should be included in the 'official' documentation.

**Comment by cooperaj** [comment] 2023-10-15 15:59
`docker system prune -a --volumes`

does nothing for me and reports 0GB cleaned up. I have 22GB of subvolumes on a system with 16 running containers. It's a very low storage RPi system and I'm not sure what to do here without just nuking the /var/lib/docker folder and starting again.

**Comment by Torxed** [comment] 2024-07-18 13:45
> `docker system prune -a --volumes`
> 
> does nothing for me and reports 0GB cleaned up. I have 22GB of subvolumes on a system with 16 running containers. It's a very low storage RPi system and I'm not sure what to do here without just nuking the /var/lib/docker folder and starting again.

Can second this:
![screenshot](https://github.com/user-attachments/assets/0b8c33f3-44a8-4f6c-be47-54fb719ca482)

However, following [another advice](https://superuser.com/a/1741982/155171), this worked:
```console
cd /var/lib/docker/btrfs/subvolumes
ls /var/lib/docker/btrfs/subvolumes | xargs btrfs subvolume delete
```

**Comment by joelhinch** [comment] 2024-10-07 10:47
Having this issue too. My Images are about 10 GB and docker reports total used space at 11GB. My subvolumes folder is 190GB. Ridiculous that theres no way to clean this up.
