### ISSUE TITLE
Pushing to docker hub. Error: Index response didn't contain any endpoints

### ISSUE THREAD

**Issue by fustbariclation** [docker/docker#27736] opened 2016-10-25 12:52 UTC
**Description**

When pushing to docker hub, it starts the push, but, before it can get anywhere, it gives this error.

**Steps to reproduce the issue:**
1. docker login
```
docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: fustbariclation
Password: 
Login Succeeded
```
2. docker push 
```
docker push hub.docker.com/fustbariclation/blue:latest
```

**Describe the results you received:**
```
Tue 25 Oct 2016 14:16:19 SAST
The push refers to a repository [hub.docker.com/fustbariclation/blue]
d46afcd68ca7: Preparing 
a2eb9966230c: Preparing 
c2ade7efa02d: Preparing 
c998354a0a8a: Preparing 
67aca2b232ea: Preparing 
b0afbd3c7b31: Waiting 
38ece981f0d9: Waiting 
3ac0d1046245: Waiting 
4ce5da20b321: Waiting 
a0dc2eaec3c3: Waiting 
ca20b906b87c: Waiting 
30596d6a4f4c: Waiting 
ec96d31f8eaf: Waiting 
e3ac10d00c60: Waiting 
2c2153fbd032: Waiting 
d9a069c1d0fc: Waiting 
a5eb0fc1decb: Waiting 
b2ac5371e0f2: Waiting 
142a601d9793: Waiting 
Index response didn't contain any endpoints
```
**Describe the results you expected:**

I expected it to push the segments.

**Additional information you deem important (e.g. issue happens only occasionally):**

It happens consistently. I've seen some reports of other people having this issue, but not any fixes. On report said it was a problem with DNS - but that seems to be working OK:

```
ping index.docker.io
PING index.docker.io (52.73.159.23): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
```

I'm not sure if that host is supposed to have icmp enabled, so I don't know if there's any significance in it not responding to a 'ping'.
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 43
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 10.73 GiB
Name: moby
ID: 6DPA:LPBI:N7WO:W26J:36TZ:6AKY:QHNS:LQYI:4IQE:UUKR:OEWV:XLBH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 99
 System Time: 2016-10-25T12:47:17.232063687Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OS/X - 10.12

**Comment by thaJeztah** [comment] 2016-10-28 05:19
ping @dmp42 any ideas?

**Comment by dmp42** [comment] 2016-10-30 10:01
Yes.

Don't:

`docker push hub.docker.com/fustbariclation/blue:latest`

Do:

`docker push fustbariclation/blue:latest`

**Comment by thaJeztah** [comment] 2016-10-30 20:36
Oh, gee, I should learn to read. Thanks @dmp42 

I'll close this issue as this is not a bug but I think the above should help you get your issue sorted

**Closed by thaJeztah** 2016-10-30 20:36 UTC
Labels: area/distribution, version/1.12

**Comment by DrStrangepork** [comment] 2017-03-30 17:14
I am having this same issue, and the work-around also fails. Here's my first attempt (like the OP's problem):

    $ docker login -u drstrangepork -p $DOCKERHUB_PASSWORD hub.docker.com
    Login Succeeded
    $ docker tag drstrangepork/awscli-runner hub.docker.com/drstrangepork/awscli-runner
    $ docker push hub.docker.com/drstrangepork/awscli-runner
    The push refers to a repository [hub.docker.com/drstrangepork/awscli-runner]
    Index response didn't contain any endpoints

Then I followed your advice and got this:

    $ docker login -u drstrangepork -p $DOCKERHUB_PASSWORD hub.docker.com
    Login Succeeded
    $ docker push drstrangepork/awscli-runner
    The push refers to a repository [docker.io/drstrangepork/awscli-runner]
    denied: requested access to the resource is denied

Not using _hub.docker.com_ with `docker login` doesn't work either:

    $ docker login -u drstrangepork -p $DOCKERHUB_PASSWORD
    Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

**Comment by akunaatrium** [comment] 2017-04-17 19:27
I wonder why is it closed. I have exactly the same issue.

Docker version is this:
```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by PMExtra** [comment] 2017-06-23 17:28
This issue is caused by `daocloud.io` (It's a docker mirror in China).

Please try to tag your image like

```
docker tag daocloud.io/[daocloud_id]/[image_name] [dockerhub_id]/[image_name]
```

to make a new tag without the `daocloud.io` part.

Then try `docker push [dockerhub_id]/[image_name]`.

**Comment by peterwillcn** [comment] 2017-10-08 12:49
Yes
