### ISSUE TITLE
Volume mounted :ro  loses restriction when crossing a host mount point?

### ISSUE THREAD

**Issue by davidraila** [docker/docker#10714] opened 2015-02-11 21:58 UTC
Mapping a host volume ro, where host has mounts within the
mapped path, the ro restriction is not applied once the hosts mount-point is crossed from within the container, as demonstrated when I thought I might map my entire host read-only:

Host:
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/sda3      460030500 307655252 152375248  67% /
tmpfs            8220152       536   8219616   1% /tmp

docker run -it -v /:/host:ro ubuntu bash
root@62b3edab74c6:/# touch /host/#asdf
touch: cannot touch '/host/#asdf': Read-only file system
root@62b3edab74c6:/# touch /host/tmp/#asdf
root@62b3edab74c6:/# ls -l !$
ls -l /host/tmp/#asdf
-rw-r--r-- 1 root root 0 Feb 11 21:50 /host/tmp/#asdf

**Comment by thaJeztah** [comment] 2015-02-14 22:22
I was able to reproduce this with docker 1.5.0 with AUFS, running on ubuntu 14.04.1;

```bash
$ mkdir /foo
$ mount -t tmpfs -o size=1M,mode=0744 tmpfs /foo
$ docker run --rm -it -v /:/host:ro ubuntu bash

$ touch /host/asdf
touch: cannot touch '/host/asdf': Read-only file system

$ touch /host/foo/asdf
$ ls -la /host/foo                                                                                                           
total 4                                                                                                                                        
drwxr--r--  2 root root   60 Feb 14 22:06 .                                                                                                    
drwxr-xr-x 25 root root 4096 Feb 14 22:02 ..                                                                                                    
-rw-r--r--  1 root root    0 Feb 14 22:06 asdf
```

Not sure if this is "by design" or a "bug". Either way, (IMO) this is something that should be documented.

/cc @cpuguy83 think this is you area :)

**Comment by cpuguy83** [comment] 2015-02-15 12:51
I suspect that this is how recursive bind-mounts work, will have to do some tests.

**Comment by cpuguy83** [comment] 2015-03-19 14:22
Yes, I can confirm this is just how bind mounts work.
Closing since this is not really something we can fix.

If someone has an idea of what we can do here, please ping.
Thanks.

**Closed by cpuguy83** 2015-03-19 14:22 UTC

**Comment by davidraila** [comment] 2015-03-20 14:34
Could look at the mount tree, and bind mount everything that's mounted 
underneath a ro volume
as ro as well.   This would not catch if something else on the system 
inserted a bind mount that would fall logically
underneath any of the ro mounts.... but I would expect that this is not 
a typically occuring event.

**Comment by cgb** [comment] 2015-04-16 14:05
I hit this today with 1.5.0.  /data1/media/{tv_shows,movies,music} are all NFS mounts.  I passed /data1/media into a plex container with ro flag and was surprised to see ro only applies to the /data1/media location.  At the very least, documentation (e.g. http://docs.docker.com/userguide/dockervolumes/) should be updated to reflect this gotcha so users are at least warned of the side effect.
