### ISSUE TITLE
Flag to avoid hardcoding -v /var/run/docker.sock:/var/run/docker.sock

### ISSUE THREAD

**Issue by lool** [docker/docker#28953] opened 2016-11-29 22:04 UTC
Hi,

Some Docker workloads expect to spin new Docker instances by talking to the daemon over /var/run/docker.sock from within an image. These are typically run with:
`-v /var/run/docker.sock:/var/run/docker.sock`

This is a bother when trying to run multiple daemons or have multiple versions of Docker installed on the same host as the original images will only work if the socket is at the right location.

This could be avoided with a flag to express sharing the docker daemon connection with the image, e.g. something like:
`--share-docker-sock`

Sadly, it will take some time for images and scripts authors to adopt such a flag, so this will only be useful on the long run but it's definitely worth providing a solution to harcoded pathnames in people's code.

Cheers,
-Loïc Minier

**Comment by thaJeztah** [comment] 2016-11-29 22:38
Thanks for suggesting; it looks like this is a duplicate of https://github.com/docker/docker/issues/27261, but there's no consensus yet (there's two PR's that implemented this; https://github.com/docker/docker/pull/25347, https://github.com/docker/docker/pull/9135 (https://github.com/docker/docker/pull/9135#issuecomment-67427605)).

I'll close this because this is a duplicate of https://github.com/docker/docker/issues/27261, you can subscribe to that issue to keep up to date on updates

**Closed by thaJeztah** 2016-11-29 22:38 UTC
Labels: area/cli, kind/enhancement
