### ISSUE TITLE
cannot connect to a container via docker host IP 

### ISSUE THREAD

**Issue by bitliner** [docker/docker#18337] opened 2015-12-01 14:16 UTC
I have 2 containers, the first one is a webserver api, the second is a frontend app.

the frontend can't connect to the api.

The frontend, to connect to API, uses the IP 172.17.0.1 (got with `ifconfig docker0 | grep 'inet addr'` on my host) and the related port (33018) where the webserver is .

The container, where the webserver is, exposes the port (33018) to allow connnections to it.

But the frontend can't connect to the api.

If I access the api via host machine IP (because the port 33018 is bound also to the host not only to container) they are accessible.

It looks like docker network don't expose the api container to other containers, it exposes it only outside of docker containers.

Indeed, if I run the container `sudo docker run -it ubuntu:14.04 /bin/bash` and I run the command to check if the port of API is accessible -  `nc 172.17.0.1 33018 &> /dev/null; echo $?` - then the result is 1, like if the port is closed.

**Comment by bitliner** [comment] 2015-12-01 14:19
output of `docker info`

```
Containers: 51
Images: 481
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 583
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-66-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 3.86 GiB
Name: vagrant-ubuntu-trusty-64
ID: YHAN:XVK7:RR4B:WXVG:6A4S:7QXW:REMV:FTS3:PKKU:MFAB:TBJZ:GBXG
Username: bitliner
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

output of docker version

```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment] 2015-12-01 14:41
I think this is a duplicate of another issue, but I'll have to look for that one.

Out of interest, why are you using the external IP to make a connection between containers, and not the (internal) container-container network?

**Comment by bitliner** [comment] 2015-12-01 20:47
Now I am using links, but still there is some issue.

If I try to connect from the host to the container exposing the API, then the API are reachable.

If I try to connect from a container to the container exposing the API, using as IP address the IP taken from file `/etc/host`, then `nc 172.17.0.3 33018 &> /dev/null && echo $?` keeps waiting like the interesting port is closed.

If I have time I will try to use a sniffer to see what fails inside the network.

**Comment by grantford** [comment] 2015-12-04 14:41
Check two things:
- Is ICC set to false for the docker daemon? (Unlikely, true is the default)
- Make sure iptables doesn't have a REJECT line that's blocking communication between the containers

**Comment by LK4D4** [comment] 2016-09-14 15:48
Going to close this issue for lack of activity. Feel free to open new!

**Closed by LK4D4** 2016-09-14 15:48 UTC
Labels: area/networking
