### ISSUE TITLE
"docker rm -v" doesn't remove volume

### ISSUE THREAD

**Issue by jl-yang-arm** [docker/docker#25747] opened 2016-08-16 08:08 UTC

**Comment by thaJeztah** [comment] 2016-08-16 10:32
only volumes that were not given a name are automatically removed; volumes with a name are not removed; https://docs.docker.com/engine/reference/commandline/rm/

for example;

    docker run -v /some/path myimage

Creates an "anonymous" / "unnamed" volume. This volume is considered "ephemeral", and removed when running `docker rm -v <container>`

 whereas;

    docker run -v my-volume:/some/path myimage


Creates (or uses the existing) volume named "my-volume". This volume is not considered "ephemeral", because you explicitly gave it a name. This volume is *not* removed when running `docker rm -v <container>`.

I'll close this issue, because this is not a bug, but I hope this helps, and feel free to continue the discussion.

**Closed by thaJeztah** 2016-08-16 10:32 UTC

**Comment by jl-yang-arm** [comment] 2016-08-16 10:41
Sorry my bad, reference clarifies well. Thanks a lot!
