### ISSUE TITLE
Postgres data volume is mounted with wrong permissions in Docker OSX beta

### ISSUE THREAD

**Issue by esbenp** [docker/docker#22075] opened 2016-04-15 15:06 UTC
I just installed Docker OSX Beta on my local machine. I have two containers: a postgres container and a data container. The compose file is something along the lines of

```yml
postgres:
  image: traede/postgres
  ports:
    - "5432:5432"
  volumes_from:
    - postgres_data
postgres_data:
  image: busybox
  volumes:
    - /var/lib/postgresql/data
```

This works when I use compose within a machine VM. However, in the OSX beta I get the following output from

`docker logs localservers_postgres_1`
```
FATAL:  data directory "/var/lib/postgresql/data" has group or world access
DETAIL:  Permissions should be u=rwx (0700).
```

`docker logs localservers_postgres_data_1` returns nothing

I am unsure as to why there is a difference between the Machine environment and my OSX environment?

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   a5315b8
 Built:        Thu Apr 14 10:19:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 52
 Running: 7
 Paused: 0
 Stopped: 45
Images: 181
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 282
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.6
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.956 GiB
Name: docker
ID: IJCB:W5BI:RIKS:IGUJ:26HW:D355:MZ3Q:ULJV:LB2L:4PJD:V7IP:3HGQ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 35
 Goroutines: 74
 System Time: 2016-04-15T14:59:16.465993504Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Local Macbook Pro machine, OSX version 10.11

**Steps to reproduce the issue:**
1. `docker-compose up -d`
2. `docker logs localservers_postgres_1`
3.

**Comment by icecrime** [comment] 2016-04-15 15:23
Cc @jeanlaurent

**Comment by dsheets** [comment] 2016-04-15 15:31
The directory `/var/lib/postgresql/data` doesn't exist in the VM because only certain host first-level directories are available: right now, `/Users`, `/Volumes`, `/tmp`, and `/private`. See *Namespaces* on https://beta.docker.com/docs/mac/osxfs/ for the full details. We're currently considering changing the bind mount namespace behavior but this is how it works currently. Solutions for right now are either:

1. Prepending `/Mac` to the path
2. Using a path under one of the above first-level directories

Finally, you may run into further issues running postgres on a shared bind mount as we don't currently support `fallocate` or `[f]stat[v]fs` but will in a Beta Coming Soon.

**Comment by cpuguy83** [comment] 2016-04-15 15:42
@dsheets This shouldn't be binding to anything on OSX, just a normal volume.

**Comment by thaJeztah** [comment] 2016-04-15 15:42
@dsheets in this case, it's not a bind-mounted directory, so `- /var/lib/postgresql/data` should create a new, "anonymous" volume.

@esbenp is there a reason you're using a data-only container? docker now has volume management functions (`docker volume ls`, `docker volume create`). In this case, I suggest to use a named volume for your postgres data, e.g.

```yaml

postgres:
  image: traede/postgres:0.1
  ports:
    - "5432:5432"
  volumes:
    - postgres_data:/var/lib/postgresql/data
```

You can find that volume with `docker volume ls`;

```
docker volume ls                                                                                                                                               DRIVER              VOLUME NAME
local               postgres_data
```

**Comment by thaJeztah** [comment] 2016-04-15 15:45
When I ran that (on Docker for Mac), it ran without issues;

```
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  |
postgres_1  | Data page checksums are disabled.
postgres_1  |
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok

....

```

**Comment by esbenp** [comment] 2016-04-15 15:59
@thaJeztah No I was not aware of such feature. As far as I remember I think I just followed [Creating and mounting a data volume container](https://docs.docker.com/engine/userguide/containers/dockervolumes/). 

I just tried using a named volume as you suggest, however I am still getting the same error. How can I provide further information to find cause?

**Comment by thaJeztah** [comment] 2016-04-15 18:55
@esbenp you used the exact docker-compose file I posted above?

**Comment by thaJeztah** [comment] 2016-04-15 18:58
Oh, perhaps `docker-compose down` first to be sure the old containers and volumes of the project are removed (assuming there's no important data in there)

**Comment by esbenp** [comment] 2016-04-15 19:06
@thaJeztah it worked after running `docker-compose down` first!

I am not sure I understand why though. I assume it worked because and old failing volume was removed. However, I changed the compose file to use the new named volume, so why would the old volume still matter? Do you have any insight into this?

**Comment by thaJeztah** [comment] 2016-04-15 19:39
@esbenp I'm not sure, I know docker-compose attempts to reuse volumes (i.e., so if I do `docker-compose up` it reuses the previous volume), but agreed that for *named* volumes in this case, it shouldn't make a difference. 

@aanand @dnephin (compose maintainers) any idea?

I'm glad it's working now, but interested to hear why it still used parts of the old volume :-)

(Note that you should also try to upgrade your docker-compose.yml to the new "version 2" format; that way you can take advantage of the new stuff, such as custom networks etc. see [this section of the documentation](https://docs.docker.com/compose/compose-file/#versioning) about the differences, and how to upgrade))

**Comment by esbenp** [comment] 2016-04-15 19:49
@thaJeztah perhaps it is because the old data container I used was also named `postgres_data` like the named volume?

Thanks for the tip!

**Comment by duykhoa** [comment] 2016-05-04 07:59
I still wonder if we can use a path, like `/Users/bar/docker_dir/postgres_data`:`/var/lib/postgresql/data` @thaJeztah 

But your solution is great, I faced the same issue with `mysql` and `elasticsearch` as well.

**Comment by thaJeztah** [comment] 2016-05-04 11:32
@esbenp @duykhoa is this still an issue for you on the latest Docker for Mac beta?

Just ran this;

```bash
mkdir postgres && cd postgres
docker run --rm -v `pwd`:/var/lib/postgresql/data -p 5432:5432 postgres
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
....
....
LOG:  database system is ready to accept connections
```

**Comment by duykhoa** [comment] 2016-05-04 15:05
@thaJeztah Confirmed it works. I will raise another issue for `elasticsearch` image.

**Comment by thaJeztah** [comment] 2016-05-04 15:33
@duykhoa oh, just got notified that there's still an issue when bind-mounting a local directory for postgresql; https://forums.docker.com/t/beta-9-postgres-stat-files-corrupted-when-data-stored-on-host-mapped-volume/10819

So, yes (also for performance), using a volume instead of a bind-mounted host-directory is still the preferred approach

**Comment by duykhoa** [comment] 2016-05-05 10:41
@thaJeztah That's true. For the Elasticsearch image (elasticsearch:2.2.0 or above), I still get the same issue. So using the volume may be the best approach for now :+1:

**Comment by iMerica** [comment] 2016-06-08 03:35
I'm still seeing the Postgres fatal error using the latest Docker toolbox (not Mac beta). It might be good to update the title of this issue to reflect both OS X beta + Toolbox.

```
db_1        | FATAL:  data directory "/var/lib/postgresql/data" has group or world access
db_1        | DETAIL:  Permissions should be u=rwx (0700).
db_1        | FATAL:  data directory "/var/lib/postgresql/data" has group or world access
db_1        | DETAIL:  Permissions should be u=rwx (0700).
```

**Comment by thaJeztah** [comment] 2016-06-24 18:54
@iMerica permissions for Docker Toolbox bind-mounts are really a separate thing, it's a known issue, and due to the way VirtualBox guest additions  / filesharing works. See for example https://github.com/boot2docker/boot2docker/issues/581

**Comment by samoht** [comment] 2016-07-27 14:27
We have reworked the way volumes are shared on the latest Betas of Docker for Mac, so I think we can close this issue. Please see https://docs.docker.com/docker-for-mac/osxfs/

**Comment by thaJeztah** [comment] 2016-07-27 15:30
thanks @samoht!

closing this issue, but feel free to comment here if you still run into this issue

**Closed by thaJeztah** 2016-07-27 15:30 UTC
Labels: group/pinata, version/1.11

**Comment by bernex** [comment] 2016-08-24 09:44
Not working, 1.12 version.

`db:
        container_name: "db"
        image: postgres
        ports: [ "5433:5432" ]
        volumes:
          - /tmp:/tmp_host
          - /Users/ss/postgresql-data2/:/var/lib/postgresql
```

Docker create
/Users/ss/postgresql-data2/
and empty directory /Users/ss/postgresql-data2/data/

No files there.

```
db         | fixing permissions on existing directory /var/lib/postgresql/data ... ok
...
creating template1 database in /var/lib/postgresql/data/base/1 ... ok
```

**Comment by bernex** [comment] 2016-08-24 09:49
Update!

```
volumes:
          - /tmp:/tmp_host
          - /Users/ilya/postgresql-data2/:/var/lib/postgresql/**data**
```

Works!

**Comment by liviucmg** [comment] 2016-12-19 18:27
Can someone shed some light as to _why_ using `/var/lib/postgresql` as a volume doesn't work, but `/var/lib/postgresql/data` does? This is exactly what @bernex described above. Many thanks.

**Comment by sda399** [comment] 2017-01-13 13:34
@liviucmg  /var/lib/postgresql/data is the correct and declared volume in Dockerfile

**Comment by shabbirkagalwala** [comment] 2017-02-02 03:26
Hi, 
I am trying to set up a solarwinds whd container and trying to mount a volume using this command:
docker run -d -p 8081:8081 --name=whdinstance -v `pwd`:/usr/local/webhelpdesk/bin/pgsql/var/lib/pgsql/9.2/data  solarwinds/whd-embedded:latest


This starts the container and the volume is mounted but as soon as go to localhost:8081 to login to the webhelpdesk it asks me to select the database and then says "Connection refused" (see attached image)

can someone please help, if this might be an issue with the way I am mounting the volume?
<img width="1025" alt="screen shot 2017-02-01 at 9 24 28 pm" src="https://cloud.githubusercontent.com/assets/17373413/22536127/0e288b2a-e8c5-11e6-9636-d5987b53de50.png">

**Comment by thaJeztah** [comment] 2017-02-02 04:34
@shabbirkagalwala Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

**Comment by garysdevil** [comment] 2019-04-28 07:41
> When I ran that (on Docker for Mac), it ran without issues;
> 
> ```
> postgres_1  | The files belonging to this database system will be owned by user "postgres".
> postgres_1  | This user must also own the server process.
> postgres_1  |
> postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
> postgres_1  | The default database encoding has accordingly been set to "UTF8".
> postgres_1  | The default text search configuration will be set to "english".
> postgres_1  |
> postgres_1  | Data page checksums are disabled.
> postgres_1  |
> postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
> 
> ....
> ```



> ```shell
> this database system will be owned by user "postgres"
> ```

![image](https://user-images.githubusercontent.com/41293784/56860685-eacb9980-69cb-11e9-8692-af6846cebb60.png)
But, I have this problem.

**Comment by maxmunzel** [comment] 2021-09-08 04:51
For all the lost souls landing here... I fixed this problem using:
```
docker compose down
docker volumes prune # be sure you know what this does and that this is acceptable for you
docker compose up
```
