### ISSUE TITLE
`docker info` unmarshal error (1.12.1 client talking to 1.13-rc1 server)

### ISSUE THREAD

**Issue by jpetazzo** [docker/docker#28449] opened 2016-11-15 17:55 UTC
**Description**

`docker info` yields the following error message, and doesn't display the info:
```
Error reading remote info: json: cannot unmarshal object into Go value of type string
```

Also, pulling an image yields the following warning (but the pull proceeds anyway):
```
Warning: failed to get default registry endpoint from daemon (Error reading remote info: json: cannot unmarshal object into Go value of type string). Using system default: https://index.docker.io/v1/
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:32:35 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:47:07 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Error reading remote info: json: cannot unmarshal object into Go value of type string
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

FWIW I provisioned the Engine with `docker-machine` 0.9.0-rc1 on AWS.

**Comment by vieux** [comment] 2016-11-16 01:19
@jpetazzo can you please paste the curl on what `/info` returns ? I cannot reproduce on my machine.

**Comment by jlhawn** [comment] 2016-11-16 02:04
I've got a PR which fixes the reverse situation where you've got a 1.13 client talking to a 1.12 or earlier deamon: #28460

**Comment by jlhawn** [comment] 2016-11-16 18:22
Specifically, here's the setup I am running:

```
Client:
 Version:      1.13.0-rc1
 API version:  1.24 (downgraded from 1.25)
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 22:32:34 2016
 OS/Arch:      darwin/amd64

Server:
 Version:             1.12.3-cs4
 API version:         1.24
 Minimum API version: 
 Go version:          go1.6.3
 Git commit:          65c6c4c
 Built:               Fri Nov 11 16:02:12 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

and the error I'm getting:

```
$ docker info
Error reading remote info: json: cannot unmarshal string into Go value of type types.SecurityOpt
```

**Comment by jlhawn** [comment] 2016-11-16 18:29
I think changing the structure of the `SecurityOptions` field in the `docker info` API response was a bad move which very clearly violates semantic versioning. We should keep that field the way it was, add a deprecation note, and add a *different* field name for the new structure.

cc @runcom since you made this change in https://github.com/docker/docker/pull/26276

**Comment by vikstrous** [comment] 2016-11-16 18:49
I'm also not very happy with this change because existing UCP versions that have been released don't specify the API version, so they will be given the latest struct and will not work on docker 1.13. This introduces a pretty big limitation for such a trivial change.

**Comment by cpuguy83** [comment] 2016-11-16 21:59
@vikstrous Why doesn't it specify an API version (or negotiate one)?

Side note, yes there's an API change here for something so trivial it's probably not worth the change even with a versioned API.

**Comment by vikstrous** [comment] 2016-11-16 22:45
According to @dhiltgen specifying an API version didn't make a difference in the past and this backwards compatibility behaviour is new. If that's the case, I think it'll take time for things that use the docker API to be updated to use the versioned APIs. If not, this is just a UCP issue and hopefully we can make sure we are explicit about the client version in the future.

**Comment by justincormack** [comment] 2016-11-17 11:49
Fixed in https://github.com/docker/docker/pull/28504

**Comment by thaJeztah** [comment] 2016-11-23 00:33
https://github.com/docker/docker/issues/28504 was merged, so closing this

**Comment by thaJeztah** [comment] 2016-11-23 00:33
but please confirm after 1.13.0-rc2 is released 👍

**Closed by thaJeztah** 2016-11-23 00:33 UTC
Labels: area/api, priority/P0, version/1.13
