### ISSUE TITLE
docker exec -it returns with a rpc error

### ISSUE THREAD

**Issue by eean** [docker/docker#22119] opened 2016-04-18 18:02 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   9e83765
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   9e83765
 Built:        
 OS/Arch:      linux/amd64
```
This corresponds to `docker-rc                 | package    | 1.11.0-1.1 | x86_64 | Virtualization:containers`, so it's a fresh build from the openSUSE Virtualization repo. I had the same issue with 1.11 rc5.

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 44
Server Version: 1.11.0
Storage Driver: btrfs
 Build Version: Btrfs v4.1.2+20151002
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.15-8-default
Operating System: openSUSE Leap 42.1 (x86_64)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.61 GiB
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
```

So I have a docker image running, one I use as a build environment. I wish to have a second console attached to the same running image. With 1.10 (and maybe into 1.11, regardless it stopped working last week) I could do `docker exec -it image_name_11 /bin/bash` and it would bring up a shell prompt. Now it error out with the following:

```
rpc error: code = 2 desc = "exec failed: [10] System error: read parent: connection reset by peer"
```

From systemctl status:
```
Apr 18 10:59:30 linux-vfob docker[6931]: time="2016-04-18T10:59:30.373182229-07:00" level=error msg="Error running exec in container: rpc error: code = 2 desc = \"exec failed: [10] System error: read parent: connection reset by peer\"\n"
Apr 18 10:59:30 linux-vfob docker[6931]: time="2016-04-18T10:59:30.373213618-07:00" level=error msg="Handler for POST /v1.23/exec/62be3f5062aaf967feb95fa70a7e810b44ed7e4f9648357149fa9f4b6a1c5b27/start returned error: rpc error: code = 2 desc = \"exec failed: [10] System error: read parent: connection reset by peer\""
Apr 18 10:59:30 linux-vfob docker[6931]: 2016/04/18 10:59:30 http: response.WriteHeader on hijacked connection
Apr 18 10:59:30 linux-vfob docker[6931]: 2016/04/18 10:59:30 http: response.Write on hijacked connection
Apr 18 10:59:30 linux-vfob docker[6931]: time="2016-04-18T10:59:30.373421752-07:00" level=error msg="Handler for POST /v1.23/exec/62be3f5062aaf967feb95fa70a7e810b44ed7e4f9648357149fa9f4b6a1c5b27/resize returned error: rpc error: code = 2 desc = \"containerd: processs not found for container\""
```

**Comment by thaJeztah** [comment] 2016-04-18 19:32
I'm a bit confused by that version, because the Git commit says its built from https://github.com/docker/docker/commit/9e83765, which is 1.10.3, but the version is 1.11.0. Have you reported this issue with the maintainers of that package in the OpenSUSE repo?

**Comment by thaJeztah** [comment] 2016-04-18 19:40
Similar issue, but in 1.10 (fixed in libcontainer) https://github.com/docker/docker/pull/19751

**Comment by eean** [comment] 2016-04-18 21:11
Hm strange. This build system is east to poke at https://build.opensuse.org/package/show/Virtualization:containers/docker-rc
I downloaded the tarballs from build.opensuse.org and github.com and they are the same, the latter just has more .gitignore files.

**Comment by eean** [comment] 2016-04-18 21:29
Ah so docker-rc is still using containerd 0.1.0. Does docker 1.11 depend on libcontainer 0.2.0? Anyways I'll try bumping libcontainer.

**Comment by cyphar** [comment] 2016-04-21 08:52
@eean I've removed docker-rc, since the docker package is now in maintenance for releasing Docker 1.11. Can you please update your system completely (so you have containerd 0.2.0)? Here's the versions of the relevant packages:

```
rpm -q docker containerd runc
docker-1.11.0-103.1.x86_64
containerd-0.2.0-1.1.x86_64                                                                                                            
runc-0.1.0-3.1.x86_64                                 
```

I'm on Tumbleweed at the moment, and I can't reproduce the issue. I'll check on Leap soon.

**Comment by cyphar** [comment] 2016-04-21 08:59
> I'm a bit confused by that version, because the Git commit says its built from 9e83765, which is 1.10.3, but the version is 1.11.0. Have you reported this issue with the maintainers of that package in the OpenSUSE repo?

Yes, I'm the maintainer. I'm not really sure why that might've happened (we pulled the tag `v1.11.0` from our mirror repo). It's possible that might've happened on our experimental builds (which are in a different place, so @eean wasn't using those). But since that package no longer exists (it was mainly for my own testing in anticipation for the 1.11 release), it shouldn't be an issue anymore.

**Comment by thaJeztah** [comment] 2016-04-21 10:27
Thanks all for clearing up 👍, I'm going to close this issue, because this was probably due to an "incomplete" build being installed, and the SUSE build is still in "testing".

**Closed by thaJeztah** 2016-04-21 10:27 UTC

**Comment by eean** [comment] 2016-04-21 17:05
Thanks, discussion continues at https://bugzilla.opensuse.org/show_bug.cgi?id=976496

**Comment by eean** [comment] 2016-04-21 17:07
Actually it just works now. :)
