### ISSUE TITLE
BUG? can't set `--cpu-quota` flag

### ISSUE THREAD

**Issue by erik-landvall** [docker/docker#22668] opened 2016-05-11 15:23 UTC
First time screwing around with the resource restrictions, so figured it's probably me who missed something.. but I can't find any other information on how to do this differently then what I tried, so here it goes:

**Output of `docker version`:**

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
Images: 170
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 180
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.19.0-59-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 15.62 GiB
Name: work
ID: WHKM:OMPO:DBD3:L3BI:74VQ:36OR:LATF:M7EF:SGKQ:UQW6:UPD6:KQHH
WARNING: No swap limit support
```

**Steps to reproduce the issue:**
1. set `--cpu-quota=50000`

**Describe the results you received:**
`flag provided but not defined: --cpu-quota`

**Describe the results you expected:**
I expected it to set the container to limit it's CPU usage to 50%

**Comment by erik-landvall** [comment] 2016-05-11 15:29
Same with `--memory-reservation 500M`

**Comment by thaJeztah** [comment] 2016-05-11 15:48
You're running quite an old version of docker; support for `--cpu-quota` was added in docker 1.7.0; https://github.com/docker/docker/blob/master/CHANGELOG.md#170-2015-06-16 through this PR https://github.com/docker/docker/pull/10736, so isn't available yet on docker 1.6.2.


i'll close this issue, because this is not a bug, but feel free to comment here after I closed

**Closed by thaJeztah** 2016-05-11 15:48 UTC

**Comment by erik-landvall** [comment] 2016-05-11 15:54
Makes better sense then, I read it as it wasn't recognizing the value. But ofc now I understand it didn't recognize the flag...

**Comment by thaJeztah** [comment] 2016-05-11 16:02
I see you're running ubuntu 15.04, which is EOL (and we're no longer publishing packages for that), so I would also recommend upgrading to a more recent version of ubuntu (you're currently not receiving security updates as well).

To get the most up-to-date version of docker installed, be sure to install from our apt repository, not the one provided by ubuntu (which may be out of date); https://docs.docker.com/engine/installation/linux/ubuntulinux/

**Comment by erik-landvall** [comment] 2016-05-11 16:12
Yhea, I'm already on it as we speak :) thanks though :)
