### ISSUE TITLE
Internal server error when stopping an exiting / exited container

### ISSUE THREAD

**Issue by wallrj** [docker/docker#9379] opened 2014-11-27 12:25 UTC
When using the Docker API, the server sometimes responds with an Internal Server Error (500) when stopping a container.

It occurs with short lived `busybox` containers which may be exiting or which may already have exited by the time we make a `stop` API call.

The error does not occur if the container's init process is still running when the `stop` call is issued. 
You can change the container command to `/bin/usleep 5000` to see this.

Here's a test case that reproduces the problem.
 * https://github.com/ClusterHQ/flocker/pull/1002

The test fails intermittently, so you'll have to repeat the tests. 
The failure usually occurs within 10 cycles.

```
$ trial --until-failure flocker.node.functional.test_race.DockerClientTests.test_add_and_stop
...
Test Pass 8
flocker.node.functional.test_race
  DockerClientTests
    test_add_and_stop ...                                               [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/vagrant/flocker/node/functional/test_race.py", line 69, in test_add_and_stop
    self.client.stop(container=self.container_name)
  File "/home/vagrant/.virtualenvs/940/lib/python2.7/site-packages/docker/client.py", line 904, in stop
    self._raise_for_status(res)
  File "/home/vagrant/.virtualenvs/940/lib/python2.7/site-packages/docker/client.py", line 88, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot stop container 328548961102: no such process")

flocker.node.functional.test_race.DockerClientTests.test_add_and_stop
-------------------------------------------------------------------------------
Ran 1 tests in 0.266s
```

A variant of this error can be seen when attempting to forcefully remove a container.

```
$ trial --until-failure flocker.node.functional.test_race.DockerClientTests.test_add_and_remove_force
...
Test Pass 3
flocker.node.functional.test_race
  DockerClientTests
    test_add_and_remove_force ...                                       [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/vagrant/flocker/node/functional/test_race.py", line 75, in test_add_and_remove_force
    self.client.remove_container(container=self.container_name, force=True)
  File "/home/vagrant/.virtualenvs/940/lib/python2.7/site-packages/docker/client.py", line 793, in remove_container
    self._raise_for_status(res)
  File "/home/vagrant/.virtualenvs/940/lib/python2.7/site-packages/docker/client.py", line 88, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Could not kill running container, cannot remove - no such process")

flocker.node.functional.test_race.DockerClientTests.test_add_and_remove_force
-------------------------------------------------------------------------------

```

System information:

```
[vagrant@localhost vagrant]$ docker info
Containers: 252
Images: 25
Storage Driver: devicemapper
 Pool Name: docker-253:0-277038-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 597.2 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 11.49 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.85 (2014-04-10)
Execution Driver: native-0.2
Kernel Version: 3.16.2-201.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)

```

```
[vagrant@localhost vagrant]$ docker version
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa/1.3.1
OS/Arch (client): linux/amd64
Server version: 1.3.1
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 4e9bbfa/1.3.1
```

**Comment by dnephin** [comment] 2015-02-12 16:28
We're seeing the same issue while running the `fig` test suite on jenkins.  All the integration tests run `docker kill` to stop running containers, but pretty frequently (80% of test runs) one test will fail during `tearDown` with

```
Cannot kill container ea41d130: no such process 
```

log
```
POST /v1.14/containers/ea41d130422bc918bd7ee40c08c43140293fd102e09eb3b54967446a197644fe/kill
+job kill(ea41d130422bc918bd7ee40c08c43140293fd102e09eb3b54967446a197644fe)
Cannot kill container ea41d130422bc918bd7ee40c08c43140293fd102e09eb3b54967446a197644fe: no such process
-job kill(ea41d130422bc918bd7ee40c08c43140293fd102e09eb3b54967446a197644fe) = ERR (1)
```

Docker version 1.3.1

**Comment by cpuguy83** [comment] 2015-02-12 17:34
Pretty sure this is fixed in libcontainer and part of 1.5.0.
Can you verify?

**Comment by dustinlacewell** [comment] 2015-03-04 17:20
I'm not sure if this is related but I'm getting similar behavior on 1.5 My application attempts to kill the container before removing it. Everytime the kill fails in this manner, the API also subsequently refuses to delete the container leaving dangling containers. It seems like the container process has exited, but the container has yet to be considered 'stopped' so both the kill and subsequent removal fail. Just guessing though:


2015-03-04 13:46:35 - Assertion failure: 404: Cannot kill container 9d2f39fab6863d958f85bc7bc0c604d589b65b701b68d7bd329958b5f6ab96b5: no such process

2015-03-04 13:46:35 - Assertion failure: 409:Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f

**Comment by LK4D4** [comment] 2015-03-04 18:44
@dustinlacewell Could you provide example of containers which you run? Thanks!

**Comment by dustinlacewell** [comment] 2015-03-04 18:46
I'm not exactly sure what you're asking. We run containers running a python process.

**Comment by LK4D4** [comment] 2015-03-04 18:48
@dustinlacewell With what flags and if this is simple app or have some "fork" magic? I would be happy to help if we'd have exact reproduction case.

**Comment by cpuguy83** [comment] 2015-08-18 02:44
ping @dustinlacewell is this still an issue?

**Comment by thaJeztah** [comment] 2016-05-27 21:36
closing because this went stale, and the runtime is now moved to RunC

**Closed by thaJeztah** 2016-05-27 21:36 UTC
Labels: status/more-info-needed, version/1.3
