### ISSUE TITLE
panic in swarmkit  on 1.13.0 (maybe related to invalid bind mounts?)

### ISSUE THREAD

**Issue by samoht** [docker/docker#30711] opened 2017-02-03 14:17 UTC
@ingshtrom reported an issue on https://github.com/docker/for-mac/issues/1255 that seems to be related to invalid bind mounts and swarkit:

```
Feb  3 12:58:30 moby root: time="2017-02-03T12:58:30.117022997Z" level=error msg="failed to start taskManager" error="invalid bind mount source, source path not found: /olympia" module="node/agent"
Feb  3 12:58:30 moby root: panic: runtime error: invalid memory address or nil pointer dereference
Feb  3 12:58:30 moby root: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xfc0854]
Feb  3 12:58:30 moby root: goroutine 39774 [running]:
Feb  3 12:58:30 moby root: panic(0x176af20, 0xc4200120a0)
Feb  3 12:58:30 moby root: ^I/usr/local/go/src/runtime/panic.go:500 +0x1a1
Feb  3 12:58:30 moby root: github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*taskManager).Logs(0x0, 0x250f8e0, 0xc422b3eff0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x24fc4e0, ...)
Feb  3 12:58:30 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/task.go:68 +0xa4
Feb  3 12:58:30 moby root: created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*worker).Subscribe
Feb  3 12:58:30 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/worker.go:511 +0x54c
Feb  3 12:58:30 moby root: panic: runtime error: invalid memory address or nil pointer dereference
Feb  3 12:58:30 moby root: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xfc0854]
Feb  3 12:58:30 moby root: goroutine 39773 [running]:
Feb  3 12:58:30 moby root: panic(0x176af20, 0xc4200120a0)
Feb  3 12:58:30 moby root: ^I/usr/local/go/src/runtime/panic.go:500 +0x1a1
Feb  3 12:58:30 moby root: github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*taskManager).Logs(0x0, 0x250f8e0, 0xc421884720, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x24fc4e0, ...)
Feb  3 12:58:30 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/task.go:68 +0xa4
Feb  3 12:58:30 moby root: created by github.com/docker/docker/vendor/github.com/docker/swarmkit/agent.(*worker).Subscribe
Feb  3 12:58:30 moby root: ^I/go/src/github.com/docker/docker/vendor/github.com/docker/swarmkit/agent/worker.go:511 +0x54c
```

See https://github.com/docker/for-mac/issues/1255 for more details.

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment] 2017-02-03 15:39
ping @stevvooe @dnephin PTAL; i'm not actually sure we can validate this before the service is created, because we don't know where a task lands

Ironically, in https://github.com/docker/docker/issues/30327#issuecomment-274631754 we seem to be doing to _much_ validation

> Looking at https://github.com/docker/docker/blob/master/daemon/cluster/executor/container/container.go#L63, we see that we are validating mounts. https://github.com/docker/docker/blob/d6be0e98027611cfb14a3246ca797bee0936e649/daemon/cluster/executor/container/validate.go#L28 has a Stat to the filesystem, which should not exist. Remove that stat and this will work.

**Comment by stevvooe** [comment] 2017-02-04 00:47
@thaJeztah The issue is that the controller is validating the bind mounts regardless of the state of the task manager. There _is_ an error that gets eaten, leading to this panic, but the mounts need to be validated where they are used, before the prepare step.

Do you need a PR for this fix? This really should land in a 1.13.1 release.

**Comment by thaJeztah** [comment] 2017-02-04 01:01
@stevvooe yes please 👍

**Comment by vieux** [comment] 2017-02-04 01:29
@stevvooe yes please a PR asap, we will take it for 1.13.1

**Comment by stevvooe** [comment] 2017-02-04 01:37
So, this is fixed by the swarmkit fix. This panic is from a nil controller on the taskManager. We now throw a proper error and propagate status. I'll follow up with another PR that properly fixes validation.

**Comment by thaJeztah** [comment] 2017-02-18 08:43
@stevvooe https://github.com/docker/docker/pull/30732 was merged, is there more to be done here, or should we close this issue?

**Closed** 2017-02-28 17:52 UTC
Labels: area/swarm, kind/bug, priority/P1
