### ISSUE TITLE
[1.10-rc1] issues w/ quay.io?

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19691] opened 2016-01-25 23:40 UTC
The following does not work in 1.10

```
$ docker pull quay.io/coreos/etcd
Using default tag: latest
Error response from daemon: unsupported manifest mediatype: text/html; charset=utf-8
```

Whats up, where do I point the finger?  quay.io or Docker 1.10

**Comment by vikstrous** [comment] 2016-01-25 23:47
Duplicate of #19526, already fixed.

**Closed** 2016-01-25 23:52 UTC
