### ISSUE TITLE
Docker install dependencies issue with glibc in Centos 7.3

### ISSUE THREAD

**Issue by Damodharanv** [docker/docker#30056] opened 2017-01-11 11:32 UTC
The issue seems to be strange when the server is updated to latest centos version

Below is the error:

+ sh -c 'sleep 3; yum -y -q install docker-engine'
Error: Package: glibc-2.17-106.el7_2.4.i686 
           Requires: glibc-common = 2.17-106.el7_2.4
           Installed: glibc-common-2.17-157.el7_3.1.x86_64 
               glibc-common = 2.17-157.el7_3.1
           Available: glibc-common-2.17-105.el7.x86_64 
               glibc-common = 2.17-105.el7
           Available: glibc-common-2.17-106.el7_2.1.x86_64 
               glibc-common = 2.17-106.el7_2.1
           Available: glibc-common-2.17-106.el7_2.4.x86_64 
               glibc-common = 2.17-106.el7_2.4
Error: Package: policycoreutils-python-2.2.5-20.el7.x86_64 
           Requires: policycoreutils = 2.2.5-20.el7
           Installed: policycoreutils-2.5-9.el7.x86_64 
               policycoreutils = 2.5-9.el7
           Available: policycoreutils-2.2.5-20.el7.x86_64 
               policycoreutils = 2.2.5-20.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

glibc package exist on the server is shown below:

glibc-2.17-157.el7_3.1.x86_64
glibc-common-2.17-157.el7_3.1.x86_64

Please suggest on fixing the issue.

Thanks

**Comment by thaJeztah** [comment] 2017-01-11 12:30
I'm not able to reproduce this; I tried installing docker on a 7.2 host, then updating (`yum update`) to 7.3. Also tried creating a new 7.2 host, then updating (`yum update`) and _then_ installing docker, both worked for me.

Could it be that the update from 7.2 to 7.3 was interrupted (outstanding transactions)? Did you reboot the host after upgrading?

During the update process, I see that both `glibc` and `glibc-common` are updated;

```
  Updating   : glibc-common-2.17-157.el7_3.1.x86_64                                                                                             8/349
  Updating   : glibc-2.17-157.el7_3.1.x86_64                                                                                                    9/349
```

@runcom @andrewhsu any other suggestions?

**Comment by thaJeztah** [comment] 2017-01-11 12:35
Just to check; which repository are you installing from? What does; `cat /etc/yum.repos.d/docker*` show? And `yum list docker-engine` ?

**Comment by Damodharanv** [comment] 2017-01-11 17:06
Find the repo details below and yum list

[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Available Packages
docker-engine.x86_64                                                           1.12.6-1.el7.centos                                                            dockerrepo

Kernel version is : 3.10.0-514.2.2.el7.x86_64

There is no interruption or outstanding transaction and rebooted the host after upgrade as well.

**Comment by thaJeztah** [comment] 2017-01-11 19:08
does `yum update glibc` update the package? Or is something blocking it from being updated?

**Comment by Damodharanv** [comment] 2017-01-12 06:17
No, There is no package available for update or there is no blocker or outstanding transaction in yum.

Loading mirror speeds from cached hostfile
No packages marked for update

**Comment by jlerny** [comment] 2017-02-01 14:46
I have the exact same problem when trying to install gcc :
- glibc 2.17-106 is required
- glibc 2.17-157 is installed
The reason is:
- the version 2.17-157 was installed by then "FROM centos:7" of the Dockerfile that as Centos version 7 points to version 7.3.1611 (that is correct)
- the version 2.17-106 is the version available on a local mirror at my company that has a deprecated version (http://<mycompany>/centos/7.2.1511/updates/x86_64/Packages/)
I warned my administrator that the local mirrors are not beeing updated.
Conclusion: one of your yum repository is probably not pointing to the Centos version 7.3.1611 as it should be.

**Comment by jlerny** [comment] 2017-02-01 14:51
I mean: http:///mycompany/7.2.1511/updates/x86_64/Packages/
(text has been modified after post)

**Comment by thaJeztah** [comment] 2017-02-02 01:05
I agree with @jlerny, and highly suspect this is something in your setup. Since we're not able to reproduce, I'm going ahead and close this issue, but feel free to continue the conversation.

**Closed by thaJeztah** 2017-02-02 01:05 UTC
Labels: area/project, kind/question, status/more-info-needed
