### ISSUE TITLE
Exposed ports become unresponsive after heavy load

### ISSUE THREAD

**Issue by micdah** [docker/docker#30400] opened 2017-01-24 09:36 UTC
**Description**

I am are running a few (4) containers via Docker-Compose (mssql-server-linux, redis, mongodb and elasticsearch) to have a development environment matching our production environment.

Normally this works fine, but whenever I put the containers under heavy load (by running our suite of services which use these services heavily) the exposed ports will abruptly stop responding. I cannot make any new connections from the host side.

Although the containers are no longer responding on their exposed ports, I can still interact with them via docker - I can exec into the containers as well as run new containers in the same docker network and do a ping to the other containers (which responds).

So it seems to be something with the exposed ports that goes wrong.

If i stop the containers and try to start them again, I get the following error:
```
> docker start serverogweb_linuxsql_1
Error response from daemon: driver failed programming external connectivity on endpoint serverogweb_linuxsql_1 (dd9583a179a8932d65655dde3936bd19325587f8fa7ba6c055d193e5a2856978): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:1433:tcp:172.18.0.2:1433: input/output error
Error: failed to start containers: serverogweb_linuxsql_1
```

**Steps to reproduce the issue:**
1. Start compose of aforementioned services
2. Start suite of services which puts these under heavy load
3. Observe that after some time, connections from the host are refused

**Describe the results you received:**
As mentioned, when the error condition occurrs all connections on the exposed ports are refused as if nothing is listening on the port.

Running a ```netstat``` also shows that nothing is listening on the exposed ports.

**Describe the results you expected:**
I expect the exposed ports to keep responding (and listening) even under heavy load. If a connection pool limit is reached, I would expect connections to be refused until the connection count lowers at which point new connections should be able to be made.

**Additional information you deem important (e.g. issue happens only occasionally):**
In order to recover from this state, I have to restart docker before I can run the containers once more.

This happens quite consistently whenever I try to run our service suite.

**Diagnostic ID**
```
30667474-C49F-4185-B957-3A7AE1F38393/2017-01-24_10-31-11
```

**Output of `docker version`:**

```
> docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
> docker info                                                         
Containers: 4                                                         
 Running: 0                                                           
 Paused: 0                                                            
 Stopped: 4                                                           
Images: 6                                                             
Server Version: 1.13.0                                                
Storage Driver: overlay2                                              
 Backing Filesystem: extfs                                            
 Supports d_type: true                                                
 Native Overlay Diff: true                                            
Logging Driver: json-file                                             
Cgroup Driver: cgroupfs                                               
Plugins:                                                              
 Volume: local                                                        
 Network: bridge host ipvlan macvlan null overlay                     
Swarm: inactive                                                       
Runtimes: runc                                                        
Default Runtime: runc                                                 
Init Binary: docker-init                                              
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e          
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e                
init version: 949e6fa                                                 
Security Options:                                                     
 seccomp                                                              
  Profile: default                                                    
Kernel Version: 4.9.4-moby                                            
Operating System: Alpine Linux v3.5                                   
OSType: linux                                                         
Architecture: x86_64                                                  
CPUs: 2                                                               
Total Memory: 3.837 GiB                                               
Name: moby                                                            
ID: K5TH:J5EJ:UQHH:2AH4:JDUM:QJFS:5NRQ:URAV:6N66:RW5S:FIFF:EZCL       
Docker Root Dir: /var/lib/docker                                      
Debug Mode (client): false                                            
Debug Mode (server): true                                             
 File Descriptors: 13                                                 
 Goroutines: 22                                                       
 System Time: 2017-01-24T09:30:01.5771338Z                            
 EventsListeners: 0                                                   
Registry: https://index.docker.io/v1/                                 
Experimental: true                                                    
Insecure Registries:                                                  
 127.0.0.0/8                                                          
Live Restore Enabled: false                                           
```

**Dump of ```netstat -an``` showing nothing is occupying port 1433**
```
Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:623            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1096           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1536           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1537           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1538           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1539           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1540           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1545           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:2179           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:16992          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49153          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49154          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49155          0.0.0.0:0              LISTENING
  TCP    10.0.75.1:139          0.0.0.0:0              LISTENING
  TCP    10.0.75.1:445          10.0.75.2:42826        ESTABLISHED
  TCP    127.0.0.1:944          0.0.0.0:0              LISTENING
  TCP    127.0.0.1:944          127.0.0.1:32407        TIME_WAIT
  TCP    127.0.0.1:944          127.0.0.1:32419        TIME_WAIT
  TCP    127.0.0.1:944          127.0.0.1:32432        TIME_WAIT
  TCP    127.0.0.1:944          127.0.0.1:32443        ESTABLISHED
  TCP    127.0.0.1:1024         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:1025         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:1026         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:1026         127.0.0.1:32411        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32412        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32414        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32415        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32416        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32417        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32418        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32421        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32423        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32424        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32425        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32426        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32427        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32428        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32429        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32430        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32431        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32433        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32434        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32435        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32436        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32437        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32438        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32439        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32440        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32442        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32444        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32445        TIME_WAIT
  TCP    127.0.0.1:1026         127.0.0.1:32446        TIME_WAIT
  TCP    127.0.0.1:1199         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:1203         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:1203         127.0.0.1:1206         ESTABLISHED
  TCP    127.0.0.1:1206         127.0.0.1:1203         ESTABLISHED
  TCP    127.0.0.1:1541         127.0.0.1:1542         ESTABLISHED
  TCP    127.0.0.1:1542         127.0.0.1:1541         ESTABLISHED
  TCP    127.0.0.1:1570         127.0.0.1:1571         ESTABLISHED
  TCP    127.0.0.1:1571         127.0.0.1:1570         ESTABLISHED
  TCP    127.0.0.1:1572         127.0.0.1:1573         ESTABLISHED
  TCP    127.0.0.1:1573         127.0.0.1:1572         ESTABLISHED
  TCP    127.0.0.1:1577         127.0.0.1:1578         ESTABLISHED
  TCP    127.0.0.1:1578         127.0.0.1:1577         ESTABLISHED
  TCP    127.0.0.1:1580         127.0.0.1:1581         ESTABLISHED
  TCP    127.0.0.1:1581         127.0.0.1:1580         ESTABLISHED
  TCP    127.0.0.1:1585         127.0.0.1:1586         ESTABLISHED
  TCP    127.0.0.1:1586         127.0.0.1:1585         ESTABLISHED
  TCP    127.0.0.1:1588         127.0.0.1:1589         ESTABLISHED
  TCP    127.0.0.1:1589         127.0.0.1:1588         ESTABLISHED
  TCP    127.0.0.1:1593         127.0.0.1:1594         ESTABLISHED
  TCP    127.0.0.1:1594         127.0.0.1:1593         ESTABLISHED
  TCP    127.0.0.1:1596         127.0.0.1:1597         ESTABLISHED
  TCP    127.0.0.1:1597         127.0.0.1:1596         ESTABLISHED
  TCP    127.0.0.1:1602         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:1715         127.0.0.1:1716         ESTABLISHED
  TCP    127.0.0.1:1716         127.0.0.1:1715         ESTABLISHED
  TCP    127.0.0.1:1730         127.0.0.1:1731         ESTABLISHED
  TCP    127.0.0.1:1731         127.0.0.1:1730         ESTABLISHED
  TCP    127.0.0.1:2375         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:18104        127.0.0.1:18105        ESTABLISHED
  TCP    127.0.0.1:18105        127.0.0.1:18104        ESTABLISHED
  TCP    127.0.0.1:32443        127.0.0.1:944          ESTABLISHED
  TCP    127.0.0.1:49152        0.0.0.0:0              LISTENING
  TCP    127.94.0.1:946         0.0.0.0:0              LISTENING
  TCP    127.94.0.2:946         0.0.0.0:0              LISTENING
  TCP    192.168.1.22:139       0.0.0.0:0              LISTENING
  TCP    192.168.1.22:1028      40.101.60.18:443       ESTABLISHED
  TCP    192.168.1.22:1029      40.96.21.2:443         ESTABLISHED
  TCP    192.168.1.22:1092      192.30.253.124:443     ESTABLISHED
  TCP    192.168.1.22:1551      192.168.1.202:445      ESTABLISHED
  TCP    192.168.1.22:1554      40.77.229.56:443       ESTABLISHED
  TCP    192.168.1.22:1640      192.168.1.202:6690     ESTABLISHED
  TCP    192.168.1.22:1691      40.96.39.178:443       ESTABLISHED
  TCP    192.168.1.22:1710      52.214.66.57:443       ESTABLISHED
  TCP    192.168.1.22:6846      40.96.28.66:443        ESTABLISHED
  TCP    192.168.1.22:12653     40.77.229.51:443       ESTABLISHED
  TCP    192.168.1.22:15583     131.253.163.87:443     ESTABLISHED
  TCP    192.168.1.22:18682     74.125.133.188:5228    ESTABLISHED
  TCP    192.168.1.22:18703     192.241.190.55:443     ESTABLISHED
  TCP    192.168.1.22:18817     65.52.0.51:5671        ESTABLISHED
  TCP    192.168.1.22:32237     212.10.41.91:443       ESTABLISHED
  TCP    192.168.1.22:32406     192.30.253.112:443     CLOSE_WAIT
  TCP    192.168.1.22:32441     40.96.6.82:443         ESTABLISHED
  TCP    192.168.1.22:37387     23.78.46.182:443       CLOSE_WAIT
  TCP    192.168.1.22:37613     68.232.34.82:443       CLOSE_WAIT
  TCP    192.168.1.22:37614     68.232.34.82:443       CLOSE_WAIT
  TCP    192.168.1.22:37815     159.20.4.143:80        ESTABLISHED
  TCP    192.168.1.22:38104     23.78.46.182:443       CLOSE_WAIT
  TCP    192.168.1.22:38187     34.248.52.45:80        CLOSE_WAIT
  TCP    192.168.1.22:38188     104.20.32.39:80        CLOSE_WAIT
  TCP    192.168.1.22:38189     88.198.114.198:80      CLOSE_WAIT
  TCP    [::]:135               [::]:0                 LISTENING
  TCP    [::]:445               [::]:0                 LISTENING
  TCP    [::]:623               [::]:0                 LISTENING
  TCP    [::]:1536              [::]:0                 LISTENING
  TCP    [::]:1537              [::]:0                 LISTENING
  TCP    [::]:1538              [::]:0                 LISTENING
  TCP    [::]:1539              [::]:0                 LISTENING
  TCP    [::]:1540              [::]:0                 LISTENING
  TCP    [::]:1545              [::]:0                 LISTENING
  TCP    [::]:2179              [::]:0                 LISTENING
  TCP    [::]:16992             [::]:0                 LISTENING
  TCP    [::]:49153             [::]:0                 LISTENING
  TCP    [::]:49154             [::]:0                 LISTENING
  TCP    [::]:49155             [::]:0                 LISTENING
  TCP    [::1]:1599             [::]:0                 LISTENING
  TCP    [::1]:1605             [::1]:1607             ESTABLISHED
  TCP    [::1]:1607             [::1]:1605             ESTABLISHED
  TCP    [::1]:18749            [::1]:49155            ESTABLISHED
  TCP    [::1]:18814            [::1]:49155            ESTABLISHED
  TCP    [::1]:32227            [::1]:49155            TIME_WAIT
  TCP    [::1]:32238            [::1]:49155            TIME_WAIT
  TCP    [::1]:32247            [::1]:49155            TIME_WAIT
  TCP    [::1]:32249            [::1]:49155            TIME_WAIT
  TCP    [::1]:32402            [::1]:49155            ESTABLISHED
  TCP    [::1]:32413            [::1]:49155            ESTABLISHED
  TCP    [::1]:32420            [::1]:49155            ESTABLISHED
  TCP    [::1]:32422            [::1]:49155            ESTABLISHED
  TCP    [::1]:49155            [::1]:18749            ESTABLISHED
  TCP    [::1]:49155            [::1]:18814            ESTABLISHED
  TCP    [::1]:49155            [::1]:32402            ESTABLISHED
  TCP    [::1]:49155            [::1]:32413            ESTABLISHED
  TCP    [::1]:49155            [::1]:32420            ESTABLISHED
  TCP    [::1]:49155            [::1]:32422            ESTABLISHED
  UDP    0.0.0.0:5050           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5355           *:*
  UDP    10.0.75.1:137          *:*
  UDP    10.0.75.1:138          *:*
  UDP    10.0.75.1:1900         *:*
  UDP    10.0.75.1:59454        *:*
  UDP    127.0.0.1:1900         *:*
  UDP    127.0.0.1:59456        *:*
  UDP    192.168.1.22:137       *:*
  UDP    192.168.1.22:138       *:*
  UDP    192.168.1.22:1900      *:*
  UDP    192.168.1.22:59455     *:*
  UDP    [::]:5353              *:*
  UDP    [::]:5353              *:*
  UDP    [::]:5353              *:*
  UDP    [::]:5355              *:*
  UDP    [::1]:1900             *:*
  UDP    [::1]:59453            *:*
  UDP    [fe80::5564:f70d:b587:c403%20]:1900  *:*
  UDP    [fe80::5564:f70d:b587:c403%20]:59452  *:*
  UDP    [fe80::e94a:b95c:fec6:c364%16]:1900  *:*
  UDP    [fe80::e94a:b95c:fec6:c364%16]:59451  *:*
```

**Comment by friism** [comment] 2017-01-24 14:28
This is probably a Docker for Windows issue. Unless you can reproduce on a stand-alone Linux box, could I get you to run diagnostics after things are stuck and open an issue here: https://github.com/docker/for-win/issues/new

It would also be extremely helpful if you could share sample code that demonstrates the problem - it doesn't have to be the code you're working on, just a minimal script that reproduces what you're seeing.

**Comment by micdah** [comment] 2017-01-24 21:01
I have created a new issue as requested over on docker for windows. https://github.com/docker/for-win/issues/426

I was able to create a sample program that can trigger the issue (_altough it might take some time, as I also show in the linked video_), over on https://github.com/micdah/DockerBomb/

**Comment by widgetpl** [comment] 2017-02-13 09:17
I have similar problem on linux, after influxdb image ate whole RAM it become zombie container and after that I am not able to run it again. I have tried docker service restart but it won't helped.


```
# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
```
# docker-compose version
docker-compose version 1.11.1, build 7c5d5e4
docker-py version: 2.0.2
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```
```
# docker-compose -f /etc/docker/docker-compose.yml up -d
Starting influxdb1

ERROR: for influxdb  Cannot start service influxdb: driver failed programming external connectivity on endpoint influxdb1 (447540e84e41d63d6c98c301133bd0cc155aabdd3b274aee6c98e68dcfb1d199): Bind for 0.0.0.0:8086 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

```
# netstat -nap | grep -E "8086|8083"
```

```
# sudo lsof -i -P -n
COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
sshd    1002     root    3u  IPv4  17097      0t0  TCP *:22 (LISTEN)
ntpd    1040     ntpd    7u  IPv4  32262      0t0  UDP 172.16.224.208:55035->94.154.96.7:123 
ntpd    1040     ntpd    8u  IPv4  34259      0t0  UDP 172.16.224.208:50802->95.158.95.123:123 
ntpd    1040     ntpd   11u  IPv4  34739      0t0  UDP 172.16.224.208:41573->193.70.94.182:123 
ntpd    1040     ntpd   12u  IPv4  34787      0t0  UDP 172.16.224.208:60293->46.250.172.2:123 
ntpd    1040     ntpd   13u  IPv4  28695      0t0  UDP 172.16.224.208:48855->193.219.28.2:123 
ntpd    1040     ntpd   14u  IPv4  34376      0t0  UDP 172.16.224.208:55738->194.177.4.1:123 
ntpd    1040     ntpd   15u  IPv4  34788      0t0  UDP 172.16.224.208:35219->188.165.17.91:123 
ntpd    1040     ntpd   16u  IPv4  34789      0t0  UDP 172.16.224.208:60390->193.25.222.240:123 
ntpd    1040     ntpd   17u  IPv4  34804      0t0  UDP 172.16.224.208:56387->195.46.37.22:123 
ntpd    1040     ntpd   18u  IPv4  34805      0t0  UDP 172.16.224.208:56833->194.29.130.252:123 
ntpd    1040     ntpd   19u  IPv4  34806      0t0  UDP 172.16.224.208:52284->91.212.242.21:123 
sshd    8662     root    3u  IPv4  34023      0t0  TCP 172.16.224.208:22->10.122.17.123:49864 (ESTABLISHED)
sshd    8772 michadzi    3u  IPv4  34023      0t0  TCP 172.16.224.208:22->10.122.17.123:49864 (ESTABLISHED
```

**Comment by widgetpl** [comment] 2017-02-13 09:27
Just ignore previous entry as it was my fault ( typo )

**Comment by thaJeztah** [comment] 2017-03-29 08:09
closing, because this is now tracked through https://github.com/docker/for-win/issues/426

**Closed by thaJeztah** 2017-03-29 08:09 UTC
Labels: area/networking, version/1.13
