### ISSUE TITLE
docker logout from registry not responding with proper error messages 

### ISSUE THREAD

**Issue by rayeesnp** [docker/docker#21826] opened 2016-04-06 23:07 UTC
**Output of `docker version`:**

docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

```
Containers: 9
 Running: 6
 Paused: 0
 Stopped: 3
Images: 260
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 330
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.797 GiB
Name: xxxx
ID: XXXXX
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. logging to image registry > docker login host:port
2. logout by entering > docker logout 
3.

**Describe the results you received:**

Getting below result 
# docker logout
Not logged in to https://index.docker.io/v1/

**Describe the results you expected:**
# docker logout should give response to provide, image registry name to logout , since i am using different image registry not   https://index.docker.io/v1/

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by dmcgowan** [comment] 2016-04-11 18:04
Logout is designed to work similar to login. If a server is provided on login then a server must be provided on logout. When no server is provided login and logout will use hub endpoint given from the deamon. Since multiple servers can be logged into, it would be confusing behavior to default to any other value as login could not do the same.

Logout usage:
```
Usage:	docker logout [OPTIONS] [SERVER]

Log out from a Docker registry.
If no server is specified, the default is defined by the daemon.
```

Login usage:
```
Usage:	docker login [OPTIONS] [SERVER]

Register or log in to a Docker registry.
If no server is specified, the default is defined by the daemon.
```

You mention that your issue only occurs occasionally, could this behavior change be related to whether you have logged in to the default registry or not? If you are not able to reproduce any buggy behavior I would suggest closing this issue. Logout is not intended to infer anything about which server to logout from the auth configuration or prompt a user for a server.

**Comment by thaJeztah** [comment] 2016-04-12 10:46
I'll go ahead and close this, but feel free to comment if you think there's still an issue

**Closed by thaJeztah** 2016-04-12 10:46 UTC
Labels: kind/enhancement
