### ISSUE TITLE
[1.12-rc4] Updating --publish ports on global service brings down swarm

### ISSUE THREAD

**Issue by mike-hearn** [docker/docker#24726] opened 2016-07-16 20:28 UTC
**Output of `docker version`:**

```
root@master1:~# docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 04:00:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 04:00:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@master1:~# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: active
 NodeID: dcpfy7dzxozgdhoo95ax0ywqx
 IsManager: No
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.9 MiB
Name: master1
ID: EY3Q:MOLM:UCZ7:ORGP:LGGU:7HQ5:ERL2:ZXUP:YLY4:SHQW:FFRC:LQOI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using docker-machine to create droplets on Digital Ocean.

**Steps to reproduce the issue:**

1. Create three droplets on Digital Ocean using the latest `docker-machine` (docker-machine version 0.8.0-rc2, build 4ca1b85)

	```
	docker-machine create -d digitalocean --engine-install-url "https://test.docker.com" master1;
	docker-machine create -d digitalocean --engine-install-url "https://test.docker.com" server1;
	docker-machine create -d digitalocean --engine-install-url "https://test.docker.com" server2;
	```

2. SSH into all three machines. Make `master1` a swarm manager. `server1` and `server2` are standard nodes.

	```
	root@master1:~# docker node ls
	ID                           HOSTNAME  MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
	42u1teml1i8f4u3yu9dvg4j7i    server2   Accepted    Ready   Active
	9qlyoammwuhp936kpgruvztrc    server1   Accepted    Ready   Active
	dcpfy7dzxozgdhoo95ax0ywqx *  master1   Accepted    Ready   Active        Leader
	```

3. Create a global service, `nginxtest`, which simply runs the standard `nginx` container. Assign it to the ingress network.

	```
	root@master1:~# docker service create --network ingress --mode global --name nginxtest nginx
	4r1kb6i4u9gbeed4yff3lmkhe
	root@master1:~# docker service ls
	ID            NAME       REPLICAS  IMAGE  COMMAND
	4r1kb6i4u9gb  nginxtest  global    nginx
	```

4. Update the `nginxtest` service to expose port 80 on all nodes:

	```
	root@master1:~# docker service update --publish "80:80" nginxtest
	```

**Describe the results you received:**

5. Attempt to remove the service:

	```
	root@master1:~# docker service rm nginxtest
	Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
	```

6. Attempt to force leave the swarm, or re-init, as a manager:

	```
	root@master1:~# docker swarm leave --force
	Error response from daemon: context deadline exceeded

	root@master1:~# docker swarm init --force-new-cluster
	No --secret provided. Generated random secret:
	        d52nkvio2w2nbjrpgm4h9w0lb

	Error response from daemon: context deadline exceeded
	```

**Describe the results you expected:**

I expected the service to open the ports and continue to respond to requests (e.g. `docker service rm`).

**Additional information you deem important (e.g. issue happens only occasionally):**

I can consistently reproduce this. I also made a screencast of creating the droplets, creating `nginxtest`, and the various errors I got: [https://streamable.com/ht4w](https://streamable.com/ht4w)

**Comment by thaJeztah** [comment] 2016-07-16 20:55
ping @mrjana

**Comment by thaJeztah** [comment] 2016-07-16 21:36
Could be a duplicate of / related to https://github.com/docker/docker/issues/24557 ?

**Comment by mavenugo** [comment] 2016-07-17 01:43
@thaJeztah @mrjana this could be related to https://github.com/docker/swarmkit/pull/1176 . I tried to reproduce this issue along with the fix for https://github.com/docker/swarmkit/pull/1176  and I hit the error `time="2016-07-17T01:38:49.009804130Z" level=error msg="Failed allocation during update of service 6haqehxwc730fzg5tehbvte2x: could not allocate VIP from IPAM: Address already in use"`. But didn't see the `context deadline exceeded` issue as mentioned in this issue.

I guess this could be related to https://github.com/docker/swarmkit/pull/1176, but not fixed by it.

**Comment by mrjana** [comment] 2016-07-17 03:08
@mavenugo This issue is probably not related to docker/swarmkit#1176 but it certainly is affecting service update because of VIP reallocation problem. Fixed it in https://github.com/docker/swarmkit/pull/1186.

**Comment by mavenugo** [comment] 2016-07-17 04:40
@mrjana thanks for the fix. Atleast with this fix (https://github.com/docker/swarmkit/pull/1186), I am unable to reproduce this bug or the `could not allocate VIP from IPAM` issue.

I will work on vendoring in swarmkit to master and pick it up for RC5

**Comment by aaronlehmann** [comment] 2016-07-20 23:20
docker/swarmkit#1186 has been vendored. Closing.

**Closed by aaronlehmann** 2016-07-20 23:20 UTC
Labels: area/swarm, group/networking, version/1.12

**Comment by mike-hearn** [comment] 2016-07-21 00:44
FYI I tried this again today using the nightly binaries from July 20, and was still able to reproduce it. I'll report back once RC5 (if that is a thing) is released.
