### ISSUE TITLE
command 'docker image' list wrong item

### ISSUE THREAD

**Issue by scsi** [docker/docker#18713] opened 2015-12-16 16:46 UTC
Use the commands below to provide key information from your environment:

docker version:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        
 OS/Arch:      linux/amd64
```
docker info:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        
 OS/Arch:      linux/amd64
```
uname -a:
```
Linux srissrv 4.1.12-gentoo #4 SMP Thu Nov 19 17:25:57 CST 2015 x86_64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz GenuineIntel GNU/Linux
```
Provide additional environment details (AWS, VirtualBox, physical, etc.):
no
List the steps to reproduce the issue:
1.
```
docker pull registry:2
```
2.
```
docker registry:2 registry:1512100650
```
3.
```
docker images registry:2
```
Describe the results you received:
I found that it list all of repository named 'registry' but not only tag '2'
```
$ docker images registry:2
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry            2                   5dfdbfb4ed57        6 days ago          224.5 MB
registry            1512100650          5dfdbfb4ed57        6 days ago          224.5 MB
```

Describe the results you expected:
This expect result should like below
```
$ docker images registry:2
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry            2                   5dfdbfb4ed57        6 days ago          224.5 MB
```

Provide additional info you think is important:
any suggest? 
Thinks

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by thaJeztah** [comment] 2015-12-16 17:08
Looks like this should be fixed on 'master', thus in the 1.10 release; this PR was created to fix this https://github.com/docker/docker/pull/18187, but from this comment; https://github.com/docker/docker/pull/18187#issuecomment-159472109 it should be fixed in 1.10.

Can you try if you're still able to reproduce this on master? You can download builds from https://master.dockerproject.org, but keep in mind those should only be used for testing, and not in production or on critical data. It's also best to do a "clean" install, 1.10 has a big change in the way images are stored, and the migration of the existing images-store can be time consuming :smile:

**Comment by scsi** [comment] 2015-12-17 02:14
Thank you for your reply and I will wait for 1.10 release and I will try to build docker in master and test.

thanks again :)

**Comment by thaJeztah** [comment] 2015-12-17 12:27
I'll go ahead and close this issue, but feel free to comment here if you're still having this issue on 1.10!

**Closed by thaJeztah** 2015-12-17 12:27 UTC
