### ISSUE TITLE
Downloads do not function properly in China

### ISSUE THREAD

**Issue by globalcitizen** [docker/docker#28791] opened 2016-11-24 05:48 UTC
**Description**

Attempt to update a popular docker image to the latest revision. Fails.

**Steps to reproduce the issue:**
1. `docker pull sameersbn/gitlab:8.13.6`

**Describe the results you received:**

`Error response from daemon: Get https://registry-1.docker.io/v2/sameersbn/gitlab/manifests/8.13.6: Get https://auth.docker.io/token?scope=repository%3Asameersbn%2Fgitlab%3Apull&service=registry.docker.io: net/http: TLS handshake timeout`

...or...

`8.13.6: Pulling from sameersbn/gitlab
bf5d46315322: Already exists
9f13e0ac480c: Already exists
e8988b5b3097: Already exists
40af181810e7: Already exists
e6f7c7e5c03e: Already exists
5dc85c5ddcbb: Already exists
84132dd79ea7: Pulling fs layer
c8a0c863ea6c: Pulling fs layer
2343d2e7f699: Pulling fs layer
4cab2e0db682: Waiting
7aaea05d8343: Waiting
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/c6/c6b284db0904c015482479059ab8f151d5414d400726f58dd6341d5038744459/data?Expires=1479967399&Signature=arv7zfJK5TreRmc5Yzpb8DNOxOIqkcB7CKdLAQtvO2H-YrkfQNug9fbpLyCkp27WmKONfxA5trvjtZHohXwo1ZHI-CmTIZikcOZP3mJ~~1JpW06Dpl6H8MojRl~P8N45A18SnUlhalISFK~vBO~RP0XupAol-8qaHR9T2Ifk~Ik_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 114.114.115.115:53: read udp 61.166.155.11:38925->114.114.115.115:53: i/o timeout`

Note that 114.114.115.115 is my DNS server, highly reliable, and in-country.

**Describe the results you expected:**

Download completes successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a 100Mbps connection on a co-located server with China Telecom (the major national provider) in the middle of a provincial capital city (Kunming). Therefore, any issues it encounters regarding connectivity are far lesser than most users, who would have these problems many times more frequently and/or to a worse extent. 

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.13.0-rc1
Storage Driver: zfs
 Zpool: pool
 Zpool Health: ONLINE
 Parent Dataset: pool/docker-images
 Space Used By Parent: 19456
 Space Available: 1864800050688
 Parent Quota: no
 Compression: off
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: v0.2.4 (expected: 8517738ba4b82aff5662c97ca4627e7e4d03b531)
runc version: N/A (expected: ac031b5bf1cc92239461125f4c1ffb760522bbf2)
init version: N/A (expected: v0.13.0)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.8
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 15.55 GiB
Name: vciserver
ID: LEBY:ELPX:7PH3:OSQB:5FEA:BCQF:ZRSC:7LRI:TLOU:QTZY:KVSL:23UO
Docker Root Dir: /pool/docker-images
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

40 logical core dual Intel(R) Xeon(R) CPU E5-2652 v3 @ 2.30GHz with 16GB DDR4.

**Comment by globalcitizen** [comment] 2016-11-24 05:53
On further investigation the cloudfront domain `dseasb33srnrn.cloudfront.net` does not seem to resolve from within China. However, I can resolve it using a server in Hong Kong. I manually added it to `/etc/hosts` (52.85.151.216 dseasb33srnrn.cloudfront.net) and the download appears to be progressing, albeit very slowly.

You may wish to review whether using servers that cannot resolve in China is a good strategy for distribution.

**Comment by thaJeztah** [comment] 2016-11-24 09:21
This issue tracker is for the open source Docker project, not the distribution of images on docker hub. You can send an email to support@docker.com for Docker Hub issues.

In this case, however, I suspect this is due to the GFW throttling traffic to these servers, and I'm not sure that can be resolved.

I'll close this issue here, because this is not a bug in the software in this repository, but feel free to comment after i closed

**Comment by globalcitizen** [comment] 2016-11-24 09:22
What fantastic customer service. I'll be taking my infrastructure elsewhere.

**Closed by thaJeztah** 2016-11-24 09:21 UTC
Labels: area/distribution, version/1.13

**Comment by thaJeztah** [comment] 2016-11-24 09:29
There's nothing we can do in this repository; contacting support@docker.com brings you in contact with people that _may_ be able to help you; this issue tracker just isn't the right location to report issues related to Docker Hub

**Comment by globalcitizen** [comment] 2016-11-29 18:51
FYI... I did email but no response at all to date. Great job guys.

**Comment by globalcitizen** [comment] 2016-12-09 00:45
I did get a response today, but it was "sorry for the lack of response, we'll send a response soon". Meanwhile, I'm now in Australia and still getting...

```
$ docker pull sameersbn/gitlab:8.14.3
Error response from daemon: Get https://registry-1.docker.io/v2/sameersbn/gitlab/manifests/8.14.3: Get https://auth.docker.io/token?scope=repository%3Asameersbn%2Fgitlab%3Apull&service=registry.docker.io: net/http: TLS handshake timeout
```

**Comment by slang800** [comment] 2016-12-16 23:50
@globalcitizen - For the record, you don't need to use the Docker Hub... That's just a service that the Docker company maintains to help make it easier to work with / share images. If you have a faster connection, you can use `docker save` to export an image, rsync the tarball to your server, and then import it with `docker load`. Or, if you want to be really fancy, you can [run your own registry](https://docs.docker.com/registry/).

**Comment by globalcitizen** [comment] 2016-12-18 16:02
Yes, in theory I could work around the issue by making custom massive files and shoving them around the internet but it removes most of the convenience of docker in the first place. Therefore, I still think it's ridiculous to ignore the issue as out of scope or non-critical for the docker project as a whole. It's really sad.

**Comment by mrksdiehl** [comment] 2018-05-04 02:54
Since google took me here, I want to provide a solution for others to follow (even though this is a closed issue). Docker now provides a Chinese mirror at `registry.docker-cn.com`. You can either use it before every pull call like this:
```
$ docker pull registry.docker-cn.com/myname/myrepo:mytag
```
or you can save the option at startup like this:
```
$ docker --registry-mirror=https://registry.docker-cn.com daemon
```
or you can make it a presistent change in the daemon.json (on linux in /etc/docker/daemon.json - create if not exist) by adding this:
```
{
  "registry-mirrors": ["https://registry.docker-cn.com"]
}
```
After that pulling works fine. Source (Chinese): [https://www.docker-cn.com/registry-mirror](https://www.docker-cn.com/registry-mirror)
