### ISSUE TITLE
API /services/[SERVICE]/update Endpoint Broken with Custom Network

### ISSUE THREAD

**Issue by afrazkhan** [docker/docker#29880] opened 2017-01-04 13:31 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

When using the `/services/[SERVICE_NAME]/update` endpoint, it fails with "changing network in service is not supported" if the service being updated is using a custom network. If the service was created without specifying the `--network` option however, it succeeds.

**Steps to reproduce the issue:**
1. Create a service with the option `--network` set to a user created overlay network
2. Try to send a POST to change something about the service. e.g.
```
{
  "TaskTemplate": {
    "ContainerSpec": {
      "Image": "busybox"
    }
  }
}
```

**Describe the results you received:**
`{"message":"rpc error: code = 2 desc = changing network in service is not supported"}`

**Describe the results you expected:**
Same as when the service is created without specifying `--network`: 200 response, and service update successful.

**Additional information you deem important (e.g. issue happens only occasionally):**
The endpoint works correctly if the service is not using a custom network.

**Output of `docker version`:**
```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 1
 Paused: 0
 Stopped: 10
Images: 160
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 394
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: active
 NodeID: 4oh2xqqiexi4rk8julf5o9rj6
 Is Manager: true
 ClusterID: a6h0antslmorusyo7dx1z3fph
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.39-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: HC4B:YUGH:5UQ2:C2C3:O6BD:PH5P:MVDJ:UFCC:OA3S:VZUS:R4EX:F7WX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 51
 Goroutines: 195
 System Time: 2017-01-04T13:30:39.75392208Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 0.0.0.0:5000
 127.0.0.0/8
```

**Comment by thaJeztah** [comment] 2017-01-04 14:39
This is expected. The services API expects the full definition of the service to be sent on update. If the service was _created_ with a custom network, but the _update_ does not contain that network, then effectively, the "update" is trying to change the network from "my-custom-network" to the "default" network. Given that changing networks (currently) isn't supported, this produces an error.

You can see this if you enable debugging on your daemon, and check the requests that the docker CLI is making;

Create service `myservice` using the `mynet` network;

```bash
$ docker service create --name myservice --network mynet nginx:alpine

DEBU[0045] Calling POST /v1.25/services/create
```

Formdata:
```json
{
  "EndpointSpec": {},
  "Mode": {
    "Replicated": {}
  },
  "Name": "myservice",
  "Networks": [
    {
      "Target": "mynet"
    }
  ],
  "TaskTemplate": {
    "ContainerSpec": {
      "DNSConfig": {},
      "Image": "nginx:alpine"
    },
    "ForceUpdate": 0,
    "Networks": [
      {
        "Target": "mynet"
      }
    ],
    "Placement": {},
    "Resources": {
      "Limits": {},
      "Reservations": {}
    },
    "RestartPolicy": {}
  },
  "UpdateConfig": {
    "FailureAction": "pause",
    "MaxFailureRatio": 0,
    "Parallelism": 1
  }
}
```

Update the service and add a label;

```bash
$ docker service update --label-add foo=bar myservice

DEBU[0289] Calling GET /v1.25/services/myservice
DEBU[0289] Calling POST /v1.25/services/w0kx7dp6t219toab49gc0aai6/update?registryAuthFrom=spec&version=14
```
Formdata:

```json
{
  "EndpointSpec": {
    "Mode": "vip"
  },
  "Labels": {
    "foo": "bar"
  },
  "Mode": {
    "Replicated": {
      "Replicas": 1
    }
  },
  "Name": "myservice",
  "Networks": [
    {
      "Target": "mynet"
    }
  ],
  "TaskTemplate": {
    "ContainerSpec": {
      "DNSConfig": {},
      "Image": "nginx:alpine@sha256:30e3a72672e4c4f6a5909a69f76f3d8361bd6c00c2605d4bf5fa5298cc6467c2"
    },
    "ForceUpdate": 0,
    "Networks": [
      {
        "Target": "ig5repexm5l2kd2wpef0pm092"
      }
    ],
    "Placement": {},
    "Resources": {
      "Limits": {},
      "Reservations": {}
    },
    "RestartPolicy": {
      "Condition": "any",
      "MaxAttempts": 0
    }
  },
  "UpdateConfig": {
    "FailureAction": "pause",
    "MaxFailureRatio": 0,
    "Parallelism": 1
  }
}
```

You can see that both the `create` _and_ `update` API calls contain the full spec for the service. The `update` API call first fetches the current service spec, applies the changes (adding a label), and then sends back the modified spec to the daemon.


I'll close this issue, because this is not a bug, but feel free to comment. Note that allowing networks to be updated is something that will be added in a future release, and being tracked in https://github.com/docker/docker/issues/28247. Initial changes for this are worked on in https://github.com/docker/docker/issues/29463 and https://github.com/docker/swarmkit/issues/1813

**Closed by thaJeztah** 2017-01-04 14:39 UTC
Labels: area/api, area/swarm, version/1.12

**Comment by afrazkhan** [comment] 2017-01-04 14:54
Aha, I thought it might be something like that.

Are you then saying that services that have a custom network can not be updated via the API (since that endpoint does not take the full spec)?

**Comment by thaJeztah** [comment] 2017-01-04 15:12
Services with a custom network can be updated, but the name/ID of the network cannot be changed; so as long as you provide the same network-id, when _updating_ the service, the other properties of the service can be updated.

An easy way to see how things work is to run the daemon in debug mode. In debug mode, the daemon logs show the requests that are made on the API. For testing, you can do this inside a container;


```
$ docker run -it --rm --privileged --volume=/var/lib/docker --name testing docker:1.12 sh
```

Inside the container;

```bash
/ # dockerd --debug --iptables=false
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock)
INFO[0000] libcontainerd: new containerd process, pid: 17
DEBU[0000] libcontainerd: containerd connection state change: CONNECTING
DEBU[0000] libcontainerd: containerd connection state change: TRANSIENT_FAILURE
...
DEBU[0001] Registering POST, /networks/{id:.*}/connect
DEBU[0001] Registering POST, /networks/{id:.*}/disconnect
DEBU[0001] Registering DELETE, /networks/{id:.*}
INFO[0001] API listen on /var/run/docker.sock
DEBU[0003] libcontainerd: containerd connection state change: READY
``

Now open a new shell, and exec into the docker container;

```bash
$ docker exec -it testing sh
/ # docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64
```

And in the first shell (where the daemon runs), you'll see the API request coming by;

```
DEBU[0127] Calling GET /v1.24/version
```

**Comment by afrazkhan** [comment] 2017-01-06 10:54
Thanks, appreciate the help. Maybe this isn't the best place to ask, but I'll risk it ;)

I see that the output of `GET /v1.24/services/[SERVICE]` is very different to what is subsequently posted to `services/[SERVICE_ID]/update`:

GET /v1.24/services/[SERVICE]: **N.B. Does not match the details in the POST below, because it's from another service, just pasting here for example of the format**
```
{"ID"=>"a8u61zvdqn3vet7bxvjtjuls5",
 "Version"=>{"Index"=>624678},
 "CreatedAt"=>"2017-01-04T13:20:57.535551842Z",
 "UpdatedAt"=>"2017-01-06T09:51:22.712903497Z",
 "Spec"=>
  {"Name"=>"mail",
   "TaskTemplate"=>
    {"ContainerSpec"=>{"Image"=>"https://docker.starred.com/mail:0.0.15", "Env"=>["destination=afraz", "maildomain=starred.com"]},
     "Resources"=>{"Limits"=>{}, "Reservations"=>{}},
     "RestartPolicy"=>{"Condition"=>"any", "MaxAttempts"=>0},
     "Placement"=>{}},
   "Mode"=>{"Replicated"=>{"Replicas"=>2}},
   "UpdateConfig"=>{"Parallelism"=>1, "FailureAction"=>"pause"},
   "Networks"=>[{"Target"=>"1l04lgeqkej2gf4xvt4zxv68c"}],
   "EndpointSpec"=>{"Mode"=>"vip"}},
 "Endpoint"=>{"Spec"=>{"Mode"=>"vip"}, "VirtualIPs"=>[{"NetworkID"=>"1l04lgeqkej2gf4xvt4zxv68c", "Addr"=>"10.0.9.2/24"}]},
 "UpdateStatus"=>{"StartedAt"=>"0001-01-01T00:00:00Z", "CompletedAt"=>"0001-01-01T00:00:00Z"}}
```

POST /services/[SERVICE_ID]/update?version=[SERVICE_VERSION]
```
{"EndpointSpec":{"Mode":"vip"},"Mode":{"Replicated":{"Replicas":1}},"Name":"foo","Networks":[{"Target":"6hf3hk1jl3vk3ztzk4zaceq2y"}],"TaskTemplate":{"ContainerSpec":{"Args":["sleep","100000"],"Image":"busybox:1.26"},"Placement":{},"Resources":{"Limits":{},"Reservations":{}},"RestartPolicy":{"Condition":"any","MaxAttempts":0}},"UpdateConfig":{"FailureAction":"pause","Parallelism":1}}
```

Am I right in presuming that I have to create the POST data from scratch? I thought I could just use the output of the GET from the service, but that doesn't match what `update` expects, and I get `{"message":"rpc error: code = 3 desc = ContainerSpec: image reference must be provided` (presumably because the format is wrong).

Not to excuse my ignorance, but the [documentation](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/update-a-service) is pretty sketchy here. It makes it look like the POST to `update` accepts something that it doesn't.

**Comment by afrazkhan** [comment] 2017-01-06 11:07
Thanks! I get it now. Documentation on this is a bit wonky though ;) I'll put in a PR if I get time.

**Comment by thaJeztah** [comment] 2017-01-06 11:10
Yes, documentation can be improved on this, also to explain the functionality of the "version" number. Be aware that for the next (1.13) release, the API documentation will be generated using Swagger (https://github.com/docker/docker/tree/master/api#updating-the-api-documentation) so both the 1.24 (markdown), and the Swagger YAML may need to be updated.
