### ISSUE TITLE
Question about environment transportation

### ISSUE THREAD

**Issue by rhuab** [docker/docker#22432] opened 2016-04-30 08:54 UTC
I have a program running in the docker image but it needs compilation environment of the host. How to use the environment in the host while the program runs in the image? -v option does not work because the path related to compilation environment may contains multiple possibilities even the user does not know where it is.
I want to deploy my program on any platform so I choose Docker to solve this problem but Docker cannot solve that problem when the program runs as I mentioned before. My question is whether docker can transplant compilation environment of the host so that the program that runs in the image can make use of the environment of the host. If not, is there any substitute solution?

**Comment by fntlnz** [comment] 2016-04-30 11:24
Take a look here https://docs.docker.com/engine/reference/run/#env-environment-variables

**Comment by thaJeztah** [comment] 2016-04-30 13:28
It's not entirely clear to me what you're asking

> -v option does not work because the path related to compilation environment may contains multiple possibilities even the user does not know where it is.

Where do these files come from? What are they generated by? Could you provide a practical example here?

> I want to deploy my program on any platform so I choose Docker to solve this problem

It depends; in an ideal situation, a container should not rely on anything from the host; bind-mounting a host directory makes the container depending on the host / environment it runs in, so the container is no longer portable.

However, without some more information, it's difficult to give a good answer.


Also, keep in mind that the GitHub issue tracker is not a general support forum; the issue tracker is meant to report bugs and feature requests; for other questions please use either of these;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

Since this is not a bug report or feature request, I'll close this issue, but feel free to comment after I closed

**Closed by thaJeztah** 2016-04-30 13:28 UTC
