### ISSUE TITLE
Flaky test: TestRunPidHostWithChildIsKillable (on ARM, Power?)

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24863] opened 2016-07-20 20:36 UTC
https://jenkins.dockerproject.org/job/Docker-PRs-arm/284/console

```
16:01:42 FAIL: docker_cli_run_test.go:2999: DockerSuite.TestRunPidHostWithChildIsKillable
16:01:42 
16:01:42 docker_cli_run_test.go:3018:
16:01:42     c.Fatal("Kill container timed out")
16:01:42 ... Error: Kill container timed out
16:01:42 
```

**Comment by thaJeztah** [comment] 2016-07-20 20:36
Noticed on https://github.com/docker/docker/pull/24835#issuecomment-234055539

**Comment by tophj-ibm** [comment] 2016-07-20 20:45
looks to be caused by #24648 which also re-vendored in containerd. 

@mlaventure looks like the test was failing at one point on that pr, you have any idea what's going on / how you fixed it?

**Comment by tophj-ibm** [comment] 2016-07-20 20:45
also thanks for opening @thaJeztah 😄

**Comment by mlaventure** [comment] 2016-07-20 21:53
It was failing on my PR because with the changed it introduces all the container processes where not killed.

I'll try to reproduce it on master now that my PR is merged, I thought I had fixed that issue since I couldn't reproduce it on my PR.

The fact that it's on ARM suggest it may be exposing a race I didn't see.

**Closed** 2016-07-21 21:18 UTC
Labels: kind/flakytest
