### ISSUE TITLE
ExportImage tarball doesn't contain manifest.json

### ISSUE THREAD

**Issue by jgsqware** [docker/docker#31250] opened 2017-02-22 10:13 UTC
**Description**

When I try to save an image with the go client `dockerclient.ExportImage()` method (`GET /images/get`), 
for some image, eg. nginx:2.11.5, I don't received in the tarball the `manifest.json` file.

However, it's working with `docker save nginx:2.11.5 > output.tar` 
If I try with `registry:2.2.1`, it's working, I got the `manifest.json`.

**Steps to reproduce the issue:**
1. Call `docker save nginx:2.11.5 > output.tar`, tarball *contains* `manifest.json`
2. Call the api `https://192.168.99.101:2376/images/get?names=nginx%3A1.11.5`, tarball *NOT* contains `manifest.json`
3. Call the api `https://192.168.99.101:2376/images/get?names=registry%3A2.2.1`, tarball *contains* `manifest.json`

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 54
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.47-boot2docker
Operating System: Boot2Docker 1.13.1 (TCL 7.2); HEAD : b7f6033 - Wed Feb  8 20:31:48 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: clairctl-box
ID: XAPH:4I2K:QD7Z:IC4O:CJXO:EIEU:TAVA:OEXZ:JM7H:U2ZF:7P6W:DKIF
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 46
 Goroutines: 47
 System Time: 2017-02-22T10:14:37.944970568Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by runcom** [comment] 2017-02-22 11:03
@jgsqware : 
```
$ docker pull nginx:2.11.5
Error response from daemon: manifest for nginx:2.11.5 not found
```
how did you build that image?

**Comment by runcom** [comment] 2017-02-22 11:10
Assuming you meant 1.11.5, I cannot reproduce on docker 1.13.1:
```
$ curl -onginx.tar -X GET --unix-socket /var/run/docker.sock http:/1.26/images/get\?names\=nginx%3A1.11.5

$ tar tvf nginx.tar
-rw-r--r-- 0/0            3703 2016-11-08 23:41 05a60462f8bafb215ddc5c20a364b5fb637670200a74a5bb13a1b23f64515561.json
drwxr-xr-x 0/0               0 2016-11-08 23:41 151dd5483fe4b33cdb79f5e06a6bb4f469416fec025fe8498bd8902d0c6fb24b/
-rw-r--r-- 0/0               3 2016-11-08 23:41 151dd5483fe4b33cdb79f5e06a6bb4f469416fec025fe8498bd8902d0c6fb24b/VERSION
-rw-r--r-- 0/0            1511 2016-11-08 23:41 151dd5483fe4b33cdb79f5e06a6bb4f469416fec025fe8498bd8902d0c6fb24b/json
-rw-r--r-- 0/0            3584 2016-11-08 23:41 151dd5483fe4b33cdb79f5e06a6bb4f469416fec025fe8498bd8902d0c6fb24b/layer.tar
drwxr-xr-x 0/0               0 2016-11-08 23:41 dbe8aa4010990f22d2dec731c5274405e2bfd8f83374e34329676832a1a287c4/
-rw-r--r-- 0/0               3 2016-11-08 23:41 dbe8aa4010990f22d2dec731c5274405e2bfd8f83374e34329676832a1a287c4/VERSION
-rw-r--r-- 0/0             474 2016-11-08 23:41 dbe8aa4010990f22d2dec731c5274405e2bfd8f83374e34329676832a1a287c4/json
-rw-r--r-- 0/0        60569088 2016-11-08 23:41 dbe8aa4010990f22d2dec731c5274405e2bfd8f83374e34329676832a1a287c4/layer.tar
drwxr-xr-x 0/0               0 2016-11-08 23:41 dec519b4a29b7780ba6a2fa0f14ef6ecc40f55ae432ab3c1c5f4621a78790e13/
-rw-r--r-- 0/0               3 2016-11-08 23:41 dec519b4a29b7780ba6a2fa0f14ef6ecc40f55ae432ab3c1c5f4621a78790e13/VERSION
-rw-r--r-- 0/0             398 2016-11-08 23:41 dec519b4a29b7780ba6a2fa0f14ef6ecc40f55ae432ab3c1c5f4621a78790e13/json
-rw-r--r-- 0/0       128877056 2016-11-08 23:41 dec519b4a29b7780ba6a2fa0f14ef6ecc40f55ae432ab3c1c5f4621a78790e13/layer.tar
-rw-r--r-- 0/0             355 1970-01-01 01:00 manifest.json
-rw-r--r-- 0/0              88 1970-01-01 01:00 repositories

**Comment by jgsqware** [comment] 2017-02-22 11:14
Ok will try that locally, but with the Docker client go it's not working as
expected

Le mer. 22 févr. 2017 12:12, Antonio Murdaca <notifications@github.com> a
écrit :

**Comment by thaJeztah** [comment] 2017-02-22 11:16
I think that was a typo indeed, because `nginx:2.11.5` does not exist on Docker Hub. Given that the docker client is also used in Docker itself, I'm not sure there's a bug at hand here.

What version of Go are you using?

**Comment by jgsqware** [comment] 2017-02-22 14:16
@thaJeztah here is my go version, `go version go1.7.4 darwin/amd64`

Ok with the `curl`command @runcom sent, it works also for me. 

Bu when I use the docker client lib from here: https://github.com/docker/docker/blob/master/client/image_save.go

it doesn't contains the manifest.json file

**Comment by thaJeztah** [comment] 2017-02-22 14:22
I don't see what that would be doing different; it's literally calling the `/images/get` endpoint and outputs the data that was sent by the daemon.

**Comment by runcom** [comment] 2017-02-22 14:25
I can't reproduce either using the client and `ImageSave`:
```
15:25:13 [github.com/docker/docker] ‹092cba3*› tar tvf nginx.tar
-rw-r--r-- 0/0            3703 2016-11-08 23:41 05a60462f8bafb215ddc5c20a364b5fb637670200a74a5bb13a1b23f64515561.json
drwxr-xr-x 0/0               0 2016-11-08 23:41 151dd5483fe4b33cdb79f5e06a6bb4f469416fec025fe8498bd8902d0c6fb24b/
-rw-r--r-- 0/0               3 2016-11-08 23:41 151dd5483fe4b33cdb79f5e06a6bb4f469416fec025fe8498bd8902d0c6fb24b/VERSION
-rw-r--r-- 0/0            1511 2016-11-08 23:41 151dd5483fe4b33cdb79f5e06a6bb4f469416fec025fe8498bd8902d0c6fb24b/json
-rw-r--r-- 0/0            3584 2016-11-08 23:41 151dd5483fe4b33cdb79f5e06a6bb4f469416fec025fe8498bd8902d0c6fb24b/layer.tar
drwxr-xr-x 0/0               0 2016-11-08 23:41 dbe8aa4010990f22d2dec731c5274405e2bfd8f83374e34329676832a1a287c4/
-rw-r--r-- 0/0               3 2016-11-08 23:41 dbe8aa4010990f22d2dec731c5274405e2bfd8f83374e34329676832a1a287c4/VERSION
-rw-r--r-- 0/0             474 2016-11-08 23:41 dbe8aa4010990f22d2dec731c5274405e2bfd8f83374e34329676832a1a287c4/json
-rw-r--r-- 0/0        60569088 2016-11-08 23:41 dbe8aa4010990f22d2dec731c5274405e2bfd8f83374e34329676832a1a287c4/layer.tar
drwxr-xr-x 0/0               0 2016-11-08 23:41 dec519b4a29b7780ba6a2fa0f14ef6ecc40f55ae432ab3c1c5f4621a78790e13/
-rw-r--r-- 0/0               3 2016-11-08 23:41 dec519b4a29b7780ba6a2fa0f14ef6ecc40f55ae432ab3c1c5f4621a78790e13/VERSION
-rw-r--r-- 0/0             398 2016-11-08 23:41 dec519b4a29b7780ba6a2fa0f14ef6ecc40f55ae432ab3c1c5f4621a78790e13/json
-rw-r--r-- 0/0       128877056 2016-11-08 23:41 dec519b4a29b7780ba6a2fa0f14ef6ecc40f55ae432ab3c1c5f4621a78790e13/layer.tar
-rw-r--r-- 0/0             355 1970-01-01 01:00 manifest.json
-rw-r--r-- 0/0              88 1970-01-01 01:00 repositories
```

**Comment by jgsqware** [comment] 2017-02-22 14:26
@runcom what's your go code?

**Comment by runcom** [comment] 2017-02-22 14:30
@jgsqware 
```go
package main

import (
	"context"
	"io/ioutil"
	"os"

	"github.com/docker/docker/client"
)

func main() {
	defaultHeaders := map[string]string{"User-Agent": "engine-api-cli"}
	cli, err := client.NewClient("unix:///var/run/docker.sock", "v1.26", nil, defaultHeaders)
	if err != nil {
		panic(err)
	}
	r, err := cli.ImageSave(context.Background(), []string{"nginx:1.11.5"})
	if err != nil {
		panic(err)
	}
	all, err := ioutil.ReadAll(r)
	if err != nil {
		panic(err)
	}
	r.Close()
	f, err := os.Create("nginx.tar")
	if err != nil {
		panic(err)
	}
	if _, err := f.Write(all); err != nil {
		panic(err)
	}
}
```

**Comment by jgsqware** [comment] 2017-02-22 14:32
thanks

here is mine that's not working:

```
package main

import (
	"context"
	"os"

	"bufio"

	"io"

	"github.com/docker/docker/client"
)

func main() {
	cli, err := client.NewEnvClient()
	if err != nil {
		panic(err)
	}

	img, err := cli.ImageSave(context.Background(), []string{"nginx:1.11.5"})
	if err != nil {
		panic(err)
	}

	fo, err := os.Create("output.tar")
	if err != nil {
		panic(err)
	}
	w := bufio.NewWriter(fo)

	_, err = io.Copy(w, img)

	if err != nil {
		panic(err)
	}
}
```

**Comment by runcom** [comment] 2017-02-22 14:42
@jgsqware the issue is your `bufio.NewWriter/io.Copy` somehow....swapping just that with my code exposes the same situation.

**Comment by runcom** [comment] 2017-02-22 14:43
closing since this doesn't sound like a docker issue.

**Closed by runcom** 2017-02-22 14:43 UTC
Labels: version/1.13

**Comment by jgsqware** [comment] 2017-02-22 14:45
ok thanks you @runcom 
your version help to understand why mine was not working:

I wasn't flushing the writer. I don't get why specifically but it fix my problem! thanks again
