### ISSUE TITLE
docker cp : copy to assumed root directory '/' fails: 'no such directory'

### ISSUE THREAD

**Issue by WhisperingChaos** [docker/docker#20926] opened 2016-03-03 22:19 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Output of `docker version`:
```
Docker version 1.10.2, build c3959b1
```

Output of `docker info`:

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 14
Server Version: 1.10.2
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-74-generic
Operating System: Alpine Linux v3.3 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.704 GiB
Name: 97b6482c3a10
ID: XUPJ:VGFT:2B7I:HOQU:BJQ7:3L4S:SGTL:ZAOO:Q57R:WXHL:BFKY:UWQ2
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1.  Create file in current working directory
``` > touch 'file.txt'```
2.  Create container from any runnable image.
```>docker create ubuntu```
3. Attempt to copy file to root **'/'** directory:
```>docker cp    file.txt   <ubuntuContainerID>:```

Describe the results you received:
```'no such directory'```

Describe the results you expected:
```file.txt``` should have been successfully created in ubuntu container's root directory.

Provide additional info you think is important:
As stated by [docker cp documentation](https://docs.docker.com/engine/reference/commandline/cp/):
*"The docker cp command assumes container paths are relative to the container’s / (root) directory."*

Workaround: 
Specify '/' as containers filepath:
```>docker cp    file.txt   <ubuntuContainerID>:/```

**Comment by vdemeester** [comment] 2016-10-27 01:35
I couldn't reproduce using latest stable version of docker, I'll close this 👼

**Closed by vdemeester** 2016-10-27 01:35 UTC

**Comment by thelinuxfaq** [comment] 2019-01-03 12:42
Hi,
I'm getting same error  when I execute in Bash script,

Error: No such container:path: e2af354a0a49:/app//logs/info1.log
Error: No such container:path: e2af354a0a49:/app//logs/info2.log
```
#!/bin/bash

LOG_FILE="logfiles.txt"
LOG_DIR=`mkdir $(pwd)/LogDir`
CONTAINER="e2af354a0a49"
while IFS= read -r line
do
        printf '%s\n' "$line"
    docker cp $CONTAINER:$line .
done <"$LOG_FILE"
```
The below command is working fine, If I run the command directly in both shell and command,
docker cp e2af354a0a49:/app//logs/info1.log
docker cp e2af354a0a49:/app//logs/info2.log
....

What was the issues?
