### ISSUE TITLE
"500 internal server error" on push to Docker Hub

### ISSUE THREAD

**Issue by Bert-R** [docker/docker#19191] opened 2016-01-08 20:11 UTC
# Problem description
Once in a while, we get an internal server error on a ``docker push``.

This is a fragment from the [latest log](https://yonadev.ci.cloudbees.com/job/build-yonadev-master/100/console):
```
Step 1 : FROM java:8
 ---> d4849089125b
Step 2 : WORKDIR /opt/app
 ---> Using cache
 ---> 9808f32c4d88
Step 3 : EXPOSE 8080
 ---> Using cache
 ---> 19d54358b1de
Step 4 : VOLUME /tmp
 ---> Using cache
 ---> 6dc1e19f5b38
Step 5 : ADD adminservice.jar app.jar
 ---> 0e57f85ebe6f
Removing intermediate container fb89e62db261
Step 6 : RUN bash -c 'touch /app.jar'
 ---> Running in 9438f216f446
 ---> 57cd9b604fd2
Removing intermediate container 9438f216f446
Step 7 : ENTRYPOINT java -Djava.security.egd=file:/dev/urandom -jar app.jar
 ---> Running in ac3cd0fba8b1
 ---> 59ac6de7b2b3
Removing intermediate container ac3cd0fba8b1
Successfully built 59ac6de7b2b3

:adminservice:buildDocker FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':adminservice:buildDocker'.
> Docker execution failed
  Command line [docker push yonadev/adminservice:0.0.8-SNAPSHOT] returned:
  Received unexpected HTTP status: 500 Internal Server Error
```

If I retrigger the build, the issue does not occur again. 

About 35 builds back, we had that error too, though [the output](https://yonadev.ci.cloudbees.com/job/build-yonadev-master/65/console) differed, as Docker did not output anything except for the error.

# Environment information
`docker version`: Docker version 1.9.1, build a34a1d5
`docker info`: 
```
Containers: 22
Images: 275
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:2-130779-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.441 GB
 Data Space Total: 107.4 GB
 Data Space Available: 18.05 GB
 Metadata Space Used: 15.76 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.132 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 7.64 GiB
Name: nl-dev-yon01.localdomain
ID: Z4EX:NNYR:ZKP7:FQEX:HLGJ:6RRY:SF4X:HPSS:6GZ5:THOZ:MYUK:I6BF
Username: yonabuild
Registry: https://index.docker.io/v1/
```

`uname -a`: Linux nl-dev-yon01.localdomain 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

# Reproduction
This issue occurs sporadically. As it results in a broken build, its quite inconvenient.

**Comment by HackToday** [comment] 2016-01-11 03:57
Not stable issue or something else ? Could it be possible to enable details logging in the server in docker side ?

**Comment by Bert-R** [comment] 2016-01-11 17:40
How should I do that?

**Comment by HackToday** [comment] 2016-01-12 00:33
@Bert-R  did you try get daemon -D  debug logging enabled? It may have additional message to help understand. 

Also besides that, you hit it  sporadically, I am considering if network issue between docker hub. Is it possible to test curl related command to call docker Hub(like write a loop), and see is it possible sometime to get 500 error ?

**Comment by Bert-R** [comment] 2016-01-12 06:56
You mean the docker registry daemon, right? That runs at https://hub.docker.com, so I can't change the configuration there.

The 500 error indicates an issue at the server side, not a network issue. Running curl in a loop against Docker Hub doesn't sound like a good idea, as that'll be considered a DOS attack. Also: the issue only occurs on docker push. I can't mimic that in a loop through curl.

Matching my log with that's logged at Docker Hub sounds to me like a more promising approach to analyze the issue.

**Comment by HackToday** [comment] 2016-01-12 15:05
No @Bert-R  I mean enable debug level in docker side.

Besides 500 error sometimes, means docker hub can not handle that.  As you said hit is not often.

My suggestion make you first check docker debug levels.  If it not help you , and then you can use others way like curl to make sure it is not docker hub stability issue. My loop not means you loop very fast, not think it is DOS attack. As user can push at their rate just like your use case, you push that and reported that issue :)

**Comment by thaJeztah** [comment] 2016-01-13 03:46
@Bert-R have you contacted support@docker.com? If this is an issue with Docker Hub, they should be able to look into that, and possibly trace back why a particular push was failing.

**Comment by Bert-R** [comment] 2016-01-13 07:20
@HackToday: Sorry. I'm pretty new to Docker, so please forgive me. I have enabled it on the daemon. I also checked the journal for the event reported above, but there is nothing about the error.

@thaJeztah: I didn't do that yet, but I will do it now.

**Comment by owaaa** [comment] 2016-02-01 13:16
+1 we get this all the time

**Comment by thaJeztah** [comment] 2016-02-01 13:30
@owaaa please report to support@docker.com as well, they should be able to check into the logs for Docker Hub for your repository.

**Comment by aboutvale** [comment] 2016-02-01 14:27
+1 we get this frequently

**Comment by dmp42** [comment] 2016-02-10 19:37
From a cursory look at the logs, there is about five hundred 500s errors a day, out of 35 millions requests (this is about 1 in 100,000, which seems low).

The most affected ip I can spot faced it 10 times today, out of 10000 requests (still low, at 1 in 1000).

If you see this "frequently" / "all the time", then please reach out to support@docker.com with your ip, docker daemon logs, and linking to this ticket here so that the Hub team can investigate further.

**Comment by Bert-R** [comment] 2016-02-10 20:11
Some are apparently less lucky than others. We had it three times now in 130 builds.

**Comment by thaJeztah** [comment] 2016-02-11 00:42
@Bert-R please don't see my response as denying there's an issue; the maintainers of this repository just don't have direct access to the Docker Hub logs; reaching out to support@docker.com may help you further (or help narrow down the issue / determine if there's an issue in docker engine that needs fixing) :heart:

**Comment by Bert-R** [comment] 2016-02-11 07:45
I understand. It was a reaction on @dmp42, who found out that only 1 in 100,000 requests fail. Two days ago, I sent our logs to Docker support. It has their attention.

**Comment by Bert-R** [comment] 2016-02-11 17:51
Today, I got this reply from Docker Support:

> The issue has been identified on our end and a ticket has been created in our internal ticketing system the devs use. This should get scheduled in one of our next sprints.
> I'll go ahead and close ticket but if you have any further questions/comments you can respond and it will reopen - You can keep track of the status at the Github URL: https://github.com/docker/docker/issues/19191

That looks good.
@kizbitz: Thanks!

**Comment by thaJeztah** [comment] 2016-02-11 21:36
Looks promising indeed! Do you want to keep this issue open, or close (since, iiuc, it's not a bug in docker-engine); you can still comment if it's closed

**Comment by Bert-R** [comment] 2016-02-12 07:29
They said "You can keep track of the status" referring to this issue, so it looks like they are going to close it when it's done. I'm equally fine, as long as it's being addressed and somehow communicated.

**Comment by ttrahan** [comment] 2016-02-29 23:10
Any update on this issue?  I'm receiving similar "docker.io request failed with status: 500 Internal Server Error" messages repeatedly today.

**Comment by sheki** [comment] 2016-02-29 23:14
We just saw this. Bump

**Comment by burtsevyg** [comment] 2016-02-29 23:22
sudo docker run -p 8080:8080 -p 50000:50000 jenkins
Unable to find image 'jenkins:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/jenkins/manifests/latest: Received unexpected HTTP status: 500 Internal Server Error.
See 'docker run --help'.

**Comment by burtsevyg** [comment] 2016-02-29 23:22
Now it work.

**Comment by lynchc** [comment] 2016-03-30 01:27
+1 this is brutal. we experience this all the time. Especially when pushing images sequentially

**Comment by thaJeztah** [comment] 2016-03-30 01:33
@lynchc if you're seeing "error 500" messages on Docker Hub, can you please send an e-mail to support@docker.com? They should be able to look into individual cases and have access to logs

**Comment by pwaller** [comment] 2016-04-05 14:44
I just saw a 500 error, pushing to a local docker instance running a local registry (latest version running from (`/_/registry`](https://hub.docker.com/_/registry/)) instance. The registry is backed by S3.

The local docker log shows no evidence of the 500 error, nor does the registry log.

The last docker log message is a `HEAD /v2/[repo]/blobs/sha256:[sha]` with a 307 response. The 500 Internal Server error is encountered 5 seconds later.

I'm using (`fsouza/go-dockerclient`](https://github.com/fsouza/go-dockerclient/blob/2a6ea763685a27b8546b6ccdfee7b9e226afb3b4/image.go#L249-L266) to send the push.

I've encountered this a few times but can't easily reproduce it.

**Comment by thaJeztah** [comment] 2016-04-05 17:52
@pwaller could this be S3 being slow? I think there have been some issues with S3 storage for registries and performance (check in the https://github.com/docker/distribution/issues issue tracker)

**Comment by pwaller** [comment] 2016-04-05 18:02
I've looked through the distribution tracker and didn't find anything which matched as closely as this issue. What's particularly weird is that there is no evidence of any error in the docker nor registry logs, only in the docker client. I should also mention that the **server version is running docker 1.9**.

**Comment by thaJeztah** [comment] 2016-04-05 22:39
@aaronlehmann any ideas?

**Comment by aaronlehmann** [comment] 2016-04-05 22:52
@pwaller: Please file an issue at https://github.com/docker/distribution/issues.

**Comment by thaJeztah** [comment] 2016-04-06 00:44
Let me close this issue, because reading back, there's nothing we can fix in this repository

**Closed by thaJeztah** 2016-04-06 00:44 UTC
Labels: group/distribution

**Comment by pwaller** [comment] 2016-04-06 08:06
Filed at  https://github.com/docker/distribution/issues/1603.
