### ISSUE TITLE
permissions broken after chown

### ISSUE THREAD

**Issue by ccp0101** [docker/docker#24913] opened 2016-07-22 00:06 UTC
Similar to this https://github.com/docker/docker/issues/20240 but overlayfs instead of aufs.

**Output of `docker version`:**
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   3be27b1
 Built:        Wed Jul 13 22:20:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   3be27b1
 Built:        Wed Jul 13 22:20:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
Containers: 20
 Running: 0
 Paused: 0
 Stopped: 20
Images: 63
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.303 GiB
Name: ip-10-0-2-155
ID: 7BJE:QA52:2TZC:5PIV:P4AX:XCKT:ZBFF:7TYV:KS5M:TIUC:TTC4:NAQL
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 30
 System Time: 2016-07-21T22:50:31.603455433Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker is running on a lightly customized Ubuntu Xenial (based on ami-ddf13fb0). Kernel is up-to-date.
`Linux ip-10-0-2-155 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Steps to reproduce the issue:**
Make a Dockerfile template:
```
FROM ubuntu:xenial

RUN groupadd --gid 1000 ubuntu && \
    useradd -u 1000 -g 1000 --home-dir /home/ubuntu --create-home ubuntu

RUN mkdir /test && \
    mkdir /test/subdir && chmod PERM /test/subdir

RUN chown -R 1000:1000 /test && \
    su ubuntu -c 'touch /test/subdir/xx'
```

`perl -pe 's/PERM/777/' Dockerfile | docker build --no-cache -` succeeds:

```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:xenial
 ---> ac526a356ca4
Step 2 : RUN groupadd --gid 1000 ubuntu &&     useradd -u 1000 -g 1000 --home-dir /home/ubuntu --create-home ubuntu
 ---> Running in 395d10d8cd10
 ---> ff18ac26f284
Removing intermediate container 395d10d8cd10
Step 3 : RUN mkdir /test &&     mkdir /test/subdir && chmod 777 /test/subdir
 ---> Running in 32ff8df6daf4
 ---> c082a205b422
Removing intermediate container 32ff8df6daf4
Step 4 : RUN chown -R 1000:1000 /test &&     su ubuntu -c 'touch /test/subdir/xx'
 ---> Running in 8e1073bdb89d
 ---> 700e3a617b48
Removing intermediate container 8e1073bdb89d
Successfully built 700e3a617b48
```

`perl -pe 's/PERM/700/' Dockerfile | docker build --no-cache -` throws permission error:

```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:xenial
 ---> ac526a356ca4
Step 2 : RUN groupadd --gid 1000 ubuntu &&     useradd -u 1000 -g 1000 --home-dir /home/ubuntu --create-home ubuntu
 ---> Running in 440243108cc6
 ---> 820e9093c6ea
Removing intermediate container 440243108cc6
Step 3 : RUN mkdir /test &&     mkdir /test/subdir && chmod 700 /test/subdir
 ---> Running in 8ad779bffbd0
 ---> a2bd48ae03e2
Removing intermediate container 8ad779bffbd0
Step 4 : RUN chown -R 1000:1000 /test &&     su ubuntu -c 'touch /test/subdir/xx'
 ---> Running in 7c7b352fed1e
touch: cannot touch '/test/subdir/xx': Permission denied
The command '/bin/sh -c chown -R 1000:1000 /test &&     su ubuntu -c 'touch /test/subdir/xx'' returned a non-zero code: 1
```

**Describe the results you received:**
See above. `test -w` calls succeed as expected, but `touch` that follows fails, unless writable is set for other (o+w)?  

**Describe the results you expected:**
Expected both to succeed because the owner has full access to `/test` folder. 

**Additional information you deem important (e.g. issue happens only occasionally):**
Was able to reproduce in boot2docker too.

**Comment by glasser** [comment] 2016-07-22 00:30
Specifically the boot2docker mentioned above was running with aufs with Dirperm1 supported. Probably a different bug. This feels a lot like #783 but that was aufs specific.

We noted that recent Linux kernels had seemingly relevant bug fixes like https://lkml.org/lkml/2016/1/31/82 but our kernel appears to already have that fix despite not being 4.4.6 yet.

(I work with @ccp0101.)

**Comment by dmcgowan** [comment] 2016-08-13 00:36
Not seeing this behavior on 4.6.4, going to add the kernel flag since this looks like it is kernel dependent.

**Comment by AkihiroSuda** [comment] 2016-08-18 09:07
Bisecting, using my "Latest-Docker-on-Latest-Kernel" script https://github.com/AkihiroSuda/latest-docker-on-latest-kernel
* v4.6.1: reproducible
* v4.5.2: not reproducible

```
$ git log --oneline v4.5.2...v4.6.1 fs/overlayfs
38b78a5 ovl: ignore permissions on underlying lookup
0a20aea fs: add file_dentry()
d101a12 fs: add file_dentry()
6986c01 ovl: cleanup unused var in rename2
56656e9 ovl: rename is_merge to is_lowest
f134f24 ovl: fixed coding style warning
45aebea ovl: Ensure upper filesystem supports d_type
fb5bb2c ovl: Warn on copy up if a process has a R/O fd open to the lower file
07f2af7 ovl: honor flag MS_SILENT at mount
11f3710 ovl: verify upper dentry before unlink and rename
```

Maybe [38b78a5](http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=38b78a5) has fixed the issue. I'll try to confirm that.

**Comment by glasser** [comment] 2016-08-18 17:35
@AkihiroSuda Thanks, that's really helpful!

**Comment by AkihiroSuda** [comment] 2016-08-19 04:34
Confirmed, it has been solved in v4.6(38b78a5)
* 38b78a5: reproducible
* 38b78a5~1: not reproducible


I suggest closing the issue

**Comment by glasser** [comment] 2016-08-19 05:20
Thanks. Just to clarify: when you say "reproducible" above you mean "bug is fixed" and "not reproducible" you mean "there is the bug"?

**Comment by AkihiroSuda** [comment] 2016-08-19 05:51
Uh, terrible typo
reproducible --> not reproducible (bug is fixed)
not reproducible --> reproducible (there is the bug)

Sorry and thank you for pointing out 😃

**Comment by dmcgowan** [comment] 2016-08-22 19:13
thanks @AkihiroSuda, closing this issue

**Closed by dmcgowan** 2016-08-22 19:13 UTC
Labels: area/kernel, area/storage/overlay, version/1.11
