### ISSUE TITLE
unless-stopped restart policy doesn't work well with docker kill --signal

### ISSUE THREAD

**Issue by realcr** [docker/docker#26087] opened 2016-08-28 15:15 UTC
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 592
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 421
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: test_droplet
ID: UUQD:WUZC:OVOM:J47K:BO2R:YT4W:IWAM:46SB:SPYE:JCKG:CZDB:A56O
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean

```

**Steps to reproduce the issue:**
(1) Start a docker container with:
```
docker run --name nginx_cont --restart unless-stopped -d nginx
```
(2) Send a SIGHUP signal to the container (This is used to reload nginx configuration which has changed on some volumes).
```
docker kill --signal="HUP" nginx_cont
```

(3) Restart the machine:
```
sudo restart
```

The nginx_cont container will not be running after the restart. 

I expect nginx_cont to be running, because I have never stopped it. I think that docker mistakenly thinks that the kill --signal command was an attempt to stop the container. 

Thank you for your help!

**Comment by thaJeztah** [comment] 2016-09-28 15:00
Thanks for reporting! Looks like this is a duplicate of https://github.com/docker/docker/issues/11065, which is being addressed by https://github.com/docker/docker/pull/26464

I'll close this issue, because we're already tracking this through https://github.com/docker/docker/issues/11065, but thanks again for reporting

**Closed by thaJeztah** 2016-09-28 15:00 UTC
Labels: area/runtime, kind/bug, version/1.11

**Comment by realcr** [comment] 2016-09-28 16:36
My pleasure. Keep up the good work, docker saved my life!
