### ISSUE TITLE
Docker for mac kills my containers upon OS X wake up

### ISSUE THREAD

**Issue by husnoo** [docker/docker#22745] opened 2016-05-15 08:20 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   8b63c77
 Built:        Tue May 10 10:39:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.9-moby
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: moby
ID: IT5A:GUHO:FDDZ:WEXT:FWKW:T4EG:3K7Q:6XZF:6ND7:WDL6:O4PI:D2U2
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 16
 Goroutines: 35
 System Time: 2016-05-15T08:18:00.852673952Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS X xhyve thing (Docker for Mac beta)

**Steps to reproduce the issue:**
1. Install docker, run an image
2. Shut laptop
3. Open laptop

**Describe the results you received:**
My containers exit at the time I open my laptop.
```
$docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
4b5628307072        sebp/lighttpd       "lighttpd -D -f /etc/"   10 hours ago        Exited (0) 15 minutes ago                       ecstatic_snyder
```

**Describe the results you expected:**
I expect my containers to keep running

**Additional information you deem important (e.g. issue happens only occasionally):**
Console.app log:
```
15/05/2016 09:00:06.531 Docker[38275]: Creating resource Entry(tcp:0.0.0.0:80)
15/05/2016 09:00:06.533 Docker[38275]: Write offset=0 data=[tcp:0.0.0.0:80:00010050] to file
15/05/2016 09:00:06.534 Docker[38662]: Client reports version 1, commit 0123456789012345678901234567890123456789
15/05/2016 09:00:06.535 Docker[38275]: Client.negotiate: received ((magic VMN3T)(version 14)(commit 37559e5f6acd56a4810963acc7001e88f2d88017))
15/05/2016 09:00:06.535 Docker[38662]: sendmsg ok
15/05/2016 09:00:06.535 Docker[38275]: Created instance tcp:0.0.0.0:80:00010050
15/05/2016 09:00:42.773 Docker[38276]: System wants to go to sleep
15/05/2016 09:00:42.773 Docker[38276]: Asking com.docker.hyperkit to freeze vcpus
15/05/2016 09:00:42.875 Docker[38276]: vcpu freeze complete: allowing sleep
15/05/2016 09:00:42.000 kernel[0]: PM response took 106 ms (38276, com.docker.drive)
15/05/2016 09:00:42.972 Docker[38276]: vcpu 1 waiting for signal to resume
15/05/2016 09:00:43.388 Docker[38276]: vcpu 0 waiting for signal to resume
15/05/2016 09:03:20.691 Docker[38276]: System wants to wake up
15/05/2016 09:03:20.691 Docker[38276]: Asking com.docker.hyperkit to thaw vcpus
15/05/2016 09:03:20.692 Docker[38276]: vcpu 1 received signal, resuming
15/05/2016 09:03:20.698 Docker[38276]: vcpu 0 received signal, resuming
15/05/2016 09:03:20.762 Docker[38276]: vm exit[1]
15/05/2016 09:03:20.762 Docker[38276]: virtio-net-ipc: initialising uuid=0837feff-ca24-42c9-a654-4117ed2cc4df,path=/var/tmp/com.docker.slirp.socket,macfile=/Users/nawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0
15/05/2016 09:03:20.762 Docker[38276]: 	reason		VMX
15/05/2016 09:03:20.762 Docker[38276]: Interface will have uuid 0837feff-ca24-42c9-a654-4117ed2cc4df
15/05/2016 09:03:20.762 Docker[38276]: 	rip		0xffffffff81095a35
15/05/2016 09:03:20.762 Docker[38276]: Connection established with MAC=c0:ff:ee:c0:ff:ee and MTU 1500
15/05/2016 09:03:20.762 Docker[38276]: 	inst_length	3
15/05/2016 09:03:20.762 Docker[38276]: 	status		0
15/05/2016 09:03:20.762 Docker[38276]: virtio-9p: initialising path=/var/tmp/com.docker.db.socket,tag=db
15/05/2016 09:03:20.762 Docker[38276]: 	exit_reason	2
15/05/2016 09:03:20.762 Docker[38276]: virtio-9p: initialising path=/var/tmp/com.docker.port.socket,tag=port
15/05/2016 09:03:20.762 Docker[38276]: 	qualification	0x0000000000000000
15/05/2016 09:03:20.762 Docker[38276]: linkname /Users/nawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
15/05/2016 09:03:20.763 Docker[38276]: 	inst_type		0
15/05/2016 09:03:20.763 Docker[38276]: COM1 connected to /dev/ttys001
15/05/2016 09:03:20.763 Docker[38276]: 	inst_error		0
15/05/2016 09:03:20.763 Docker[38276]: COM1 linked to /Users/nawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
15/05/2016 09:03:20.763 Docker[38276]: received sigusr1, pausing
15/05/2016 09:03:20.763 Docker[38276]: received sigusr2, unpausing
15/05/2016 09:03:22.119 Docker[38275]: PPP.listen: closing connection
15/05/2016 09:03:22.119 Docker[38274]: Fatal unexpected exception: Transfuse.Socket_closed
15/05/2016 09:03:22.121 Docker[30472]: Reap com.docker.osxfs (pid 38274): exit status 1
15/05/2016 09:03:22.165 Docker[30477]: VM has shutdown at 2016-05-15 09:03:22 +0100 BST
15/05/2016 09:03:22.168 Docker[30472]: Reap com.docker.driver.amd64-linux (pid 38276): exit status 0
15/05/2016 09:03:22.172 Docker[30458]: dockerState = starting
15/05/2016 09:03:22.187 ReportCrash[38706]: Saved crash report for com.docker.hyperkit[38278] version 0 to /Users/nawal/Library/Logs/DiagnosticReports/com.docker.hyperkit_2016-05-15-090322_Nawals-MacBook-Air.crash
15/05/2016 09:03:23.122 Docker[30472]: Stop 1 children with order 1: com.docker.driver.amd64-linux (pid 38276)
15/05/2016 09:03:23.123 Docker[30472]: Stop 2 children with order 2: com.docker.osxfs (pid 38274), com.docker.slirp (pid 38275)
15/05/2016 09:03:23.123 Docker[30472]: Signal terminated to com.docker.slirp (pid 38275)
15/05/2016 09:03:23.126 Docker[30472]: Reap com.docker.slirp (pid 38275): signal: terminated
15/05/2016 09:03:23.226 Docker[30472]: Starting com.docker.osxfs, com.docker.slirp, com.docker.driver.amd64-linux
15/05/2016 09:03:23.230 Docker[30472]: Start com.docker.osxfs (pid 38709)
15/05/2016 09:03:23.234 Docker[30472]: Start com.docker.slirp (pid 38710)
15/05/2016 09:03:23.239 Docker[30472]: Start com.docker.driver.amd64-linux (pid 38711)
15/05/2016 09:03:23.244 Docker[38709]: Logging to Apple System Log
15/05/2016 09:03:23.250 Docker[38710]: Logging to Apple System Log
15/05/2016 09:03:23.250 Docker[38710]: Setting handler to ignore all SIGPIPE signals
15/05/2016 09:03:23.250 Docker[38710]: starting port_forwarding port_control_path:fd:4 vsock_path:/var/tmp/com.docker.vsock/connect
15/05/2016 09:03:23.250 Docker[38710]: attempting to reconnect to database on unix /var/tmp/com.docker.db.socket
15/05/2016 09:03:23.251 Docker[38710]: reconnected transport layer
15/05/2016 09:03:23.252 Docker[38710]: allowing binds to any IP addresses
15/05/2016 09:03:23.254 Docker[38710]: Starting slirp server pcap_settings:disabled peer_ip:192.168.65.2 local_ip:192.168.65.1
15/05/2016 09:03:23.262 Docker[38711]: Acquired hypervisor lock
15/05/2016 09:03:23.265 Docker[38711]: Docker is not responding: waiting 0.5s
15/05/2016 09:03:23.337 Docker[38711]: hypervisor: native
15/05/2016 09:03:23.337 Docker[38711]: filesystem: osxfs
15/05/2016 09:03:23.338 Docker[38709]: Using protocol TwoThousand msize 16384
15/05/2016 09:03:23.338 Docker[38711]: Hypervisor: native; BootProtocol: direct; UefiBootDisk: /Users/nawal/UefiBoot.qcow2
15/05/2016 09:03:23.339 Docker[38711]: Launching: /Users/nawal/000_Level_1/086_Applications/Docker.app/Contents/MacOS/com.docker.hyperkit -A -m 2G -c 2 -u -s 0:0,hostbridge -s 31,lpc -s 2:0,virtio-ipc,uuid=0837feff-ca24-42c9-a654-4117ed2cc4df,path=/var/tmp/com.docker.slirp.socket,macfile=/Users/nawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0 -s 3,virtio-blk,file:///Users/nawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2,format=qcow -s 4,virtio-9p,path=/var/tmp/com.docker.db.socket,tag=db -s 5,virtio-rnd -s 6,virtio-9p,path=/var/tmp/com.docker.port.socket,tag=port -s 7,virtio-sock,guest_cid=3,path=/var/tmp/com.docker.vsock,guest_forwards=2376;1525 -l com1,autopty=/Users/nawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty,log=/Users/nawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring -f kexec,/Users/nawal/000_Level_1/086_Applications/Docker.app/Contents/Resources/moby/vmlinuz64,/Users/nawal/000_Level_1/086_Applications/Docker.app/Contents/Resources/moby/initrd.img,earlyprintk=serial console=ttyS0 com.docker.driverDir="/Users/nawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux", com.docker.database="com.docker.driver.amd64-linux" -F /Users/nawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/hypervisor.pid
15/05/2016 09:03:23.375 Docker[38713]: Starting xhyve
15/05/2016 09:03:23.376 Docker[38711]: May 15 09:03:23 Nawals-MacBook-Air.local Docker[38713] <Notice>: Starting xhyve
15/05/2016 09:03:23.376 Docker[38710]: PPP.negotiate: received ((magic VMN3T)(version 14)(commit 37559e5f6acd56a4810963acc7001e88f2d88017))
15/05/2016 09:03:23.376 Docker[38710]: PPP.negotiate: received (Ethernet 0837feff-ca24-42c9-a654-4117ed2cc4df)
15/05/2016 09:03:23.376 Docker[38710]: PPP.negotiate: sending ((mtu 1500)(max_packet_size 1550)(client_macaddr c0:ff:ee:c0:ff:ee))
15/05/2016 09:03:23.377 Docker[38710]: PPP.listen: called a second time: doing nothing
15/05/2016 09:03:23.377 Docker[38711]: mirage_block_open file:///Users/nawal/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 buffered = true
15/05/2016 09:03:23.377 Docker[38710]: TCP/IP ready
15/05/2016 09:03:23.377 Docker[38711]: mirage_block_open returning 0
15/05/2016 09:03:23.378 Docker[38711]: mirage_block_stat
15/05/2016 09:03:23.378 Docker[38711]: vsock init 7:0 = /var/tmp/com.docker.vsock, guest_cid = 3
15/05/2016 09:03:25.556 Docker[38711]: 
rdmsr to register 0x34 on vcpu 0
15/05/2016 09:03:25.659 Docker[38711]: Docker is not responding: waiting 0.5s
15/05/2016 09:03:26.164 Docker[38711]: Docker is not responding: waiting 0.5s
15/05/2016 09:03:26.667 Docker[38711]: Docker is not responding: waiting 0.5s
15/05/2016 09:03:27.169 Docker[38711]: Docker is not responding: waiting 0.5s
15/05/2016 09:03:27.674 Docker[38711]: Docker is not responding: waiting 0.5s
15/05/2016 09:03:28.176 Docker[38711]: Docker is not responding: waiting 0.5s
15/05/2016 09:03:28.681 Docker[38711]: Docker is not responding: waiting 0.5s
15/05/2016 09:03:29.080 Docker[38709]: transfused: mount 
15/05/2016 09:03:29.080 Docker[38709]: transfused: /bin/fusermount 
15/05/2016 09:03:29.081 Docker[38709]: transfused: -o 
15/05/2016 09:03:29.081 Docker[38709]: transfused: allow_other,max_read=1048576,subtype=osxfs 
15/05/2016 09:03:29.081 Docker[38709]: transfused: /Mac 
15/05/2016 09:03:29.082 Docker[38709]: transfused: 
15/05/2016 09:03:29.085 Docker[38709]: osxfs tracing: OFF 
15/05/2016 09:03:29.107 Docker[38710]: Using protocol TwoThousand msize 8192
15/05/2016 09:03:30.999 Docker[38711]: Docker is responding
15/05/2016 09:03:31.019 Docker[30477]: VM has started at 2016-05-15 09:03:31 +0100 BST
15/05/2016 09:03:31.077 Docker[30458]: dockerState = running
```

**Comment by husnoo** [comment] 2016-05-15 08:23
Attachment for crash log.
[com.docker.hyperkit_2016-05-15-090322_Nawals-MacBook-Air.crash.txt](https://github.com/docker/docker/files/264882/com.docker.hyperkit_2016-05-15-090322_Nawals-MacBook-Air.crash.txt)

**Comment by unclejack** [comment] 2016-05-15 08:47
@husnoo What version of OS X are you using?

**Comment by thaJeztah** [comment] 2016-05-15 13:35
ping @MagnusS @justincormack could you have a look?

**Comment by husnoo** [comment] 2016-05-15 13:37
@unclejack `10.10.5 (14F1713)`

**Comment by justincormack** [comment] 2016-05-15 13:46
Hi, does this always happen? There are definitely more bugs in OSX `10.10` than `10.11` in this area, if you can upgrade it would be interesting to know if this solves the issue for you, but we are still working to improve these issues that some people see.

**Comment by husnoo** [comment] 2016-05-15 15:07
@justincormack It is quite consistent, I have not noticed it not happening so far. But then I could have missed it!

I might upgrade some time soon. Will keep you posted!

**Comment by husnoo** [comment] 2016-05-21 19:09
@justincormack, upgrading to El Capitain appears to have solved this as you suggested.

**Comment by unclejack** [comment] 2016-05-22 08:33
Mac OS X 10.10 won't be receiving any more updates and it's very likely 10.10 will still have these problems. I've also reproduced this issue on OS X 10.10.5.

I'll close this issue now since a solution has been found.

Please keep in mind that the Docker for Mac beta provides some means to submit feedback from the application and via email. There are forums for Docker for Mac where issues encountered with the beta can be discussed as well. Those three means of providing feedback and getting help are more adequate for Docker for Mac beta. Thank you for understanding.

**Closed by unclejack** 2016-05-22 08:33 UTC
Labels: version/1.11

**Comment by ericb** [comment] 2016-08-04 14:15
I also experienced this issue, and the upgrade to 10.11.x solved it for me as well. Thanks!

**Comment by elyulka** [comment] 2016-11-11 09:24
I had this issue on 10.10 long time. I've just upgraded to 10.12 and issue is still present.

```
eugene-mac-lan:~ eugenework$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

```
eugene-mac-lan:~ eugenework$ docker info
Containers: 71
 Running: 0
 Paused: 0
 Stopped: 71
Images: 327
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 541
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.30-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: 6UPF:EGCF:DUVL:X5IA:YB2F:QWCM:KZL6:VEAQ:72CC:G35N:WFGB:5DOU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 27
 System Time: 2016-11-11T09:21:11.576874038Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Comment by justincormack** [comment] 2016-11-11 09:31
Please open an issue on https://github.com/docker/for-mac/issues with the
diagnostics id.
