### ISSUE TITLE
Deploying a stack from compose file does no variable substitution

### ISSUE THREAD

**Issue by tevjef** [docker/docker#30175] opened 2017-01-15 22:43 UTC
Docker 1.13 will allow users to define a stack with a compose file with `docker stack deploy -c docker-compose.yml <stack>` . 

If the compose file contains any variables they will not be substituted.

.env
```
SOME_ENV=myenv
```
docker-compose.yml
```
version: '3'
services:
   redis:
     image: redis
     environment:
       SOME_ENV: ${SOME_ENV}
```

`docker inspect -f '{{.Config.Env}}' $CONTAINER_ID`
```
[SOME_ENV= ]
```

**Comment by vdemeester** [comment] 2017-01-16 07:39
@tevjef Yes, this is not currently supported by `docker stack deploy` in 1.13 (ref feature in compose docs is [here](https://docs.docker.com/compose/environment-variables/#/the-env-file)).
/cc @dnephin

**Comment by dnephin** [comment] 2017-01-16 14:38
Variable substitution works, but `.env` files are not supported.  Closing as duplicate of #29133

**Closed by dnephin** 2017-01-16 14:38 UTC
Labels: area/bundles
