### ISSUE TITLE
Unable to change user id inside Docker image

### ISSUE THREAD

**Issue by fjammes** [docker/docker#15631] opened 2015-08-17 13:06 UTC
# BUG REPORT INFORMATION

docker version:

Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

docker info:

Containers: 49
Images: 305
Storage Driver: aufs
 Root Dir: /space/docker-img/aufs
 Backing Filesystem: extfs
 Dirs: 403
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 7.799 GiB
Name: clrinfopc04
ID: SAK3:M3NE:QOW4:Y6RL:53OP:JSP3:DPLJ:3D73:IQN5:G2IA:KUZ2:PU3G
Username: fjammes
Registry: [https://index.docker.io/v1/]
WARNING: No memory limit support
WARNING: No swap limit support

uname -a:

Linux clrinfopc04 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

Host is Debian jessie on a physical machine.

# Steps to reproduce the issue:

Dockerfile is:
```bash
1 qserv@clrinfopc04:~/src/qserv/admin/tools/docker (u/fjammes/DM-3199)$ cat test/Dockerfile 
FROM centos:centos7
MAINTAINER Fabrice Jammes <fabrice.jammes@in2p3.fr>

RUN adduser dev
RUN usermod -u 1004 dev
```
Image creation command is:
```bash
qserv@clrinfopc04:~/src/qserv/admin/tools/docker (u/fjammes/DM-3199)$ docker build --tag="fjammes/qserv:test" test
Sending build context to Docker daemon 12.29 kB
Sending build context to Docker daemon 
Step 0 : FROM centos:centos7
 ---> 7322fbe74aa5
Step 1 : MAINTAINER Fabrice Jammes <fabrice.jammes@in2p3.fr>
 ---> Using cache
 ---> f063582765db
Step 2 : RUN adduser dev
 ---> Running in e4b8669cdb01
 ---> 5b8c5f9e9404
Removing intermediate container e4b8669cdb01
Step 3 : RUN usermod -u 1004 dev
 ---> Running in 96d99c800314
 ---> cd2c3f9a362e
Removing intermediate container 96d99c800314
Successfully built cd2c3f9a362e
```

# Results received:

Error is:
```bash
qserv@clrinfopc04:~/src/qserv/admin/tools/docker (u/fjammes/DM-3199)$ docker run -it --rm  fjammes/qserv:test bash
[root@1d4b99293106 /]# su - dev
[dev@1d4b99293106 ~]$ ls -rtla
total 20
-rw-r--r-- 1 dev  dev   231 Mar  5 22:06 .bashrc
-rw-r--r-- 1 dev  dev   193 Mar  5 22:06 .bash_profile
-rw-r--r-- 1 dev  dev    18 Mar  5 22:06 .bash_logout
drwxr-xr-x 4 root root 4096 Aug 17 13:00 ..
drwx------ 2 dev  dev  4096 Aug 17 13:00 .
[dev@1d4b99293106 ~]$ touch foo
touch: cannot touch 'foo': Permission denied
```

# Results expected:

Creation of file named 'foo' should be successful.

**Comment by fjammes** [comment] 2015-08-17 13:14
Thanks, I've updated my comment.

**Comment by fjammes** [comment] 2015-08-17 13:29
Please note that this problem doesn't occur with next Dockerfile, so the problem seems to come from CentOS:

```bash
qserv@clrinfopc04:~/src/qserv/admin/tools/docker (u/fjammes/DM-3199)$ cat test/Dockerfile 
#FROM debian:latest
FROM centos:centos7
MAINTAINER Fabrice Jammes <fabrice.jammes@in2p3.fr>

RUN groupadd dev
RUN useradd -m -g dev dev
RUN usermod -u 1004 dev
```

**Comment by cpuguy83** [comment] 2015-08-17 20:21
I cannot reproduce this even with the centos image.

**Comment by fjammes** [comment] 2015-08-18 05:22
Ok, could you please tell me which distrib in running your host machine and which Docker version do you use?
On my side I tried this code for more than 10 times, and it never works.

**Comment by cpuguy83** [comment] 2015-08-18 14:58
@fjammes This is boot2docker with docker 1.8

**Comment by fjammes** [comment] 2015-08-18 15:36
Ok I use docker 1.6 on Debian:jessie, so the issue might have been solved in next Docker version, thanks :+1:

**Comment by cpuguy83** [comment] 2015-09-15 18:07
Closing, but please ping if you can reproduce on the latest engine version.

**Closed by cpuguy83** 2015-09-15 18:07 UTC
