### ISSUE TITLE
Upgrade from 1.7.1 to 1.8.1 incomplete bridge settings

### ISSUE THREAD

**Issue by Zenithar** [docker/docker#15630] opened 2015-08-17 12:47 UTC
Maybe it's only on Archlinux but I have updated my distribution and docker this morning, and I had lost any bridge (docker0) settings.

docker0 was present but no IP assigned, this command fix the problem :
#> ip addr add 172.17.42.1/16 dev docker0

Thanks.

**Comment by Zenithar** [comment] 2015-08-17 14:05
docker version :
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Sat Aug 15 17:29:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Sat Aug 15 17:29:10 UTC 2015
 OS/Arch:      linux/amd64
```

docker info :
```
Containers: 80
Images: 1477
Storage Driver: btrfs
 Build Version: Btrfs v4.1.2
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.5-1-ARCH
Operating System: Arch Linux
CPUs: 4
Total Memory: 7.625 GiB
Name: *******
ID: ICKU:HVPK:Y3RI:HBYT:KUOW:67DR:5PLY:3OEQ:TCXC:MEWD:VNJT:AEHO
```

uname -a : 
```
Linux ******** 4.1.5-1-ARCH #1 SMP PREEMPT Tue Aug 11 15:41:14 CEST 2015 x86_64 GNU/Linux
```

Details environment: 
  * Running on physical Archlinux, previously using docker 1.7.1.

**Comment by klingtnet** [comment] 2015-08-17 20:26
Same problem here. My docker containers had lost their network connection after upgrading to docker 1.8.1 on my Arch Linux machines. I can't say what exactly the problem was, but restarting the docker service some times seems to have fixed the issue.

**Comment by andrewstuart** [comment] 2015-08-18 15:28
Yep, just discovered this problem yesterday. Arch Linux and Docker v1.8.1.

For what it's worth a workaround is `sudo systemctl restart docker`. The bridge comes up with the correct IP address after that.

**Comment by andrewstuart** [comment] 2015-08-18 15:43
I disabled docker on startup and when I tried to manually start it (via systemd) I got an error from systemd and these logs:
```
Aug 18 08:36:14 astuart docker[2061]: time="2015-08-18T08:36:14.466766687-07:00" level=info msg="Option DefaultDriver: bridge"
Aug 18 08:36:14 astuart docker[2061]: time="2015-08-18T08:36:14.466859605-07:00" level=info msg="Option DefaultNetwork: bridge"
Aug 18 08:36:14 astuart docker[2061]: time="2015-08-18T08:36:14.471006056-07:00" level=info msg="Firewalld running: false"
Aug 18 08:36:14 astuart docker[2061]: time="2015-08-18T08:36:14.549109778-07:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: Failed to setup IP tables, cannot acquire Interface address: Interface docker0 has no IPv4 addresses"
Aug 18 08:36:14 astuart systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Aug 18 08:36:14 astuart systemd[1]: Failed to start Docker Application Container Engine.
```

**Comment by mavenugo** [comment] 2015-08-18 16:00
@andrewstuart @Zenithar thanks for reporting the issue. @jfrazelle was facing the exact same issue and we were suspecting kernel 4.1.4+ specific issue (and/or also maybe systemd related). We fixed a few netlink related issues in docker master recently. Can you try the latest master from https://master.dockerproject.org/ and let us know if it helps ?

**Comment by andrewstuart** [comment] 2015-08-18 16:18
@mavenugo Yes, the latest master does appear to have fixed the issue. :-)

**Comment by mavenugo** [comment] 2015-08-18 16:26
@andrewstuart https://github.com/docker/docker/pull/15601 is marked for 1.8.2 release and please try out the 1.8.2 RC when it is out.

**Comment by vikstrous** [comment] 2015-08-18 21:18
FYI: another workaround I've been using is to start docker with:

```
docker -d --bip=172.17.42.1/16
```

**Comment by t-richards** [comment] 2015-08-19 16:36
None of the above workarounds corrected the problem for me. Here's the workaround that fixed `172.` address properly on my machine:

```bash
$ sudo systemctl stop docker

# Consider doing a "watch ip addr" to see the magic happen
$ sudo docker daemon -D
^C
```

**Comment by mavenugo** [comment] 2015-08-19 16:47
@t-richards can you please confirm if you still see the issue using the latest master ? My earlier comment on this : https://github.com/docker/docker/issues/15630#issuecomment-132258988

**Comment by t-richards** [comment] 2015-08-19 16:57
@mavenugo Having trouble building the latest master at this exact moment in time. Probably a PEBKAC error. I'll report back if I manage to get it working :smile:

**Comment by t-richards** [comment] 2015-08-19 17:04
@mavenugo The latest master appears to configure the `docker0` device properly.

```bash
$ docker --version
Docker version 1.9.0-dev, build 7f46dc0
```

**Comment by mavenugo** [comment] 2015-08-19 17:07
@t-richards thanks for the confirmation. https://github.com/docker/docker/pull/15601 will be included in 1.8.2 and this issue will be taken care of.

**Comment by mavenugo** [comment] 2015-08-19 17:08
@icecrime Given that the issue is resolved in the master and https://github.com/docker/docker/pull/15601 is planned for 1.8.2, should we close this issue now ?

**Comment by icecrime** [comment] 2015-08-19 17:40
@mavenugo Sure, thanks.

**Closed by icecrime** 2015-08-19 17:40 UTC
Labels: group/networking, system/networking

**Comment by jfrazelle** [comment] 2015-08-21 17:15
this worked for me too!

**Comment by gngeorgiev** [comment] 2015-09-23 22:34
@andrewstuart restarting the docker service worked for me too. Everyone should keep in mind that I enabled port forwarding in my systemd-networkd service:

```bash
[Network]
IPForward=yes
```

**Comment by alexnguyen91** [comment] 2015-09-28 07:26
@gngeorgiev Thank you very much, I should have read systemd.network more carefully

**Comment by joelwurtz** [comment] 2015-10-08 08:53
I'm facing the same problem but adding the IPForward=yes does not resolve my issue,

Actually every time a container is stopped the bridge lost his ip and i have to manually restart docker / re add ip addr to the bridge :/

**Comment by mavenugo** [comment] 2015-10-08 08:56
@joelwurtz are you seeing it in 1.8.2 ? if not, I would strongly advice you to move to 1.8.2.

**Comment by joelwurtz** [comment] 2015-10-08 09:13
Yes i am on 1.8.2, with more search this may come from another bug with a conflict with "wicd" (as seen in http://stackoverflow.com/questions/28923743/dockers-docker0-device-dies-repeatedly-inet-addr-disappears), i have disable it for the moment and no problems occurs so far

**Comment by terlar** [comment] 2015-12-02 07:40
I am running 1.9.1 and I am still experiencing this. I wonder if it is due to the systemd-networkd starting after docker and setting the flags. For now I can resolve it by restarting the docker service but that isn't very neat.
