### ISSUE TITLE
why is osxkeychain access for v4.services.acrobat necessary

### ISSUE THREAD

**Issue by mko-x** [docker/docker#31814] opened 2017-03-14 09:35 UTC
**Description**
During the build of a docker image I get a popup in OSX to allow keychain access from docker-credential-osxkeychain to v4.services.acrobat. Why does Docker need Acrobat credentials for a build?

**Steps to reproduce the issue:**
1. Start a new build on CLI within OSX

**Describe the results you received:**
Question for accessing the osx-keychain to load v4.services.acrobat

**Describe the results you expected:**
No try to access the keychain for an x.x.acrobat key.

**Additional information you deem important (e.g. issue happens only occasionally):**
The credential popup rises anytime I start a docker build.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 25
 Running: 0
 Paused: 0
 Stopped: 25
Images: 175
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 350
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: 4LYA:ZEAV:VXQX:QUVE:FL4W:NXPE:SZAQ:OXRC:INDL:ZJLA:GKW4:SCN2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2017-03-14T09:31:05.110455941Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

On the machin runs Docker Community Edition Version from beta channel.

**Comment by thaJeztah** [comment] 2017-03-14 09:59
Thanks for reporting; this is a duplicate of https://github.com/docker/for-mac/issues/1371, and https://github.com/docker/docker/issues/31517, which contains more information about this issue. I'll close this issue to prevent the discussion from diverging, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-14 09:59 UTC
Labels: area/builder, version/17.03
