### ISSUE TITLE
New feature: support cpu time

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker#7877] opened 2014-09-04 03:49 UTC
Right now docker have been support memory limit and cpu weight settings.

Is it possible to support cpu time in the future?

**Comment by jfrazelle** [comment] 2015-01-19 23:22
why not just put in a process to watch and kill it after a certain time?

**Comment by cpuguy83** [comment] 2015-01-20 02:03
This would be enabled by adding support for ulimit here: #9437
But yes, there are also a few images out there that do just this.

**Comment by mjsalinger** [comment] 2015-01-23 11:56
@jfrazelle I don't think that's enough.  When orchestrating a bunch of Docker containers, it would be useful to set the CPU quota and period.  As far as I understand https://github.com/docker/docker/pull/5381 adds this support to cgroups but it has not yet been exposed to users via docker run in order to throttle cpu usage per container.

**Comment by jfrazelle** [comment] 2015-01-23 17:49
you can use `--cpuset=""` to set the cap

**Comment by mjsalinger** [comment] 2015-01-23 20:19
Doesn't --cpuset just set the specific processors to use, rather than the quota and period, which are different things that control the quota per period (by setting cpu quota and cpu period) which can throttle individual docker containers?

**Comment by gdm85** [comment] 2015-01-31 15:06
yes I think it's covered nicely by #9437

**Comment by jfrazelle** [comment] 2015-02-28 03:09
duplicate of https://github.com/docker/docker/pull/9437

**Closed by jfrazelle** 2015-02-28 03:09 UTC
