### ISSUE TITLE
Iptables within a container

### ISSUE THREAD

**Issue by auzias** [docker/docker#18230] opened 2015-11-25 14:28 UTC
*I did not know where to report this issue. [docker/docker](https://github.com/docker/docker) or [docker/libnetwork](https://github.com/docker/libnetwork) or [docker/swarm](https://github.com/docker/swarm), sorry if it's not the right place*

Hi everyone,

I'm running an application over a swarm cluster but when I wanted to stress it I came across the fact that **`iptables` does not work** within a container.
I somehow do understand that I may not even be possible as `iptables` works on a kernel level, and that the rules would then also affect the host but I do not want to. Note that it does not make sense neither as I use a **swarm overlay network** and would like to block IP (or MAC) addresses.

My questions are:
 - What solution can be deploy to dynamically [dis]connect containers?
 - Does `iptables` using the `veth*` could work instead?
 - Is there some other solutions?
 - How can I match the host's `veth*` with the info shown by `swarm-docker network inspect <NETWORK ID>` ?

How to reproduce the issue:
````
$docker run --rm -it debian:latest
root@492f87eabddd:/#apt-get update -y && apt-get install -y iptables && iptables -L
[ .. ]
iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
````

**`docker version`**
````
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64
````
**`docker info`**
````
Containers: 66
Images: 12
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 144
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 12
Total Memory: 47.25 GiB
Name: bugs20
ID: DVQZ:XBAT:IN4R:VLTP:2B4H:J4LX:4TDT:HXL7:U6QT:O3IQ:MB6E:XSRP
WARNING: No memory limit support
WARNING: No swap limit support
Cluster store: consul://127.0.0.1:8500
Cluster advertise: 192.168.196.20:2375
````
**`uname -a`**
````
Linux bugs20 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
````

Have a nice day!

**Comment by thaJeztah** [comment] 2015-11-25 15:49
You'll probably have to run the container in `--priviledged` mode, but the GitHub issue tracker is not the best location to discuss this. The GitHub issue tracker is for tracking bugs and feature requests in Docker, not for general support questions, please use one of these;

1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.
4) stackoverflow: http://stackoverflow.com/questions/tagged/docker

I'm going to close this issue because this is not a bug or a feature request, but feel free to continue the discussion :-)

**Comment by auzias** [comment] 2015-11-25 16:18
Hi @thaJeztah and thanks a lot ! `--privileged` [0] works well !
(At least I don't have the error anymore, I did not test forward, gotta go)


** [0]: note your typo in your answer :wink: **

**Comment by thaJeztah** [comment] 2015-11-25 16:25
> note your typo in your answer

oh! LOL, yup typing in a hurry never works

**Closed** 2015-11-26 07:49 UTC
Labels: group/networking, kind/question

**Comment by sanimej** [comment] 2015-11-26 21:09
@auzias Just curious, how does your application use the iptables within the container ?

**Comment by auzias** [comment] 2015-11-26 21:39
Hi @sanimej, I'm not sure to understand your question.
My application uses `iptables` through `/sbin/iptables`.

**Comment by sanimej** [comment] 2015-11-26 21:50
@auzias My question was what is your use case that requires iptable rules to be setup within the container.

**Comment by auzias** [comment] 2015-11-27 08:10
Oh, the use-case!
I'm teaching networking, and I wanted to create a practical experiment for the students. It's not about deployment, just educational.

**Comment by Janpot** [comment] 2017-08-03 10:28
@sanimej In case you're still interested, I ran in a use-case: Suppose you want something like a screenshot service, or a pdf rendering service. Which receives a url provided by a user, fetches 
and renders it, and sends the result back. You'd want to protect it from accessing internal IPs, since that could potentially expose internal information.

**Comment by thaJeztah** [comment] 2017-08-03 11:02
For those interested, Jerôme Petazzoni provided more information on running IPTables inside a container here; https://github.com/moby/moby/issues/33605#issuecomment-307361421

**Comment by geretz** [comment] 2019-02-22 19:54
My use case would be to support traffic that needs to flow  to a process running inside a Docker for Mac container that is attached to a bridge network and has mapped ports. The packets appear to be coming from an unexpected address, iptables would hopefully allow me to make them look as coming from an expected source.
