### ISSUE TITLE
Docker daemon can not start in RHES 7.1

### ISSUE THREAD

**Issue by yingfeng** [docker/docker#21882] opened 2016-04-08 11:21 UTC
**Output of `docker version`:**
Docker 1.10_1

**Output:**
```
bjs0-3a4:root ~ $ service docker start
Redirecting to /bin/systemctl start  docker.service
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

bjs0-3a4:root ~ $ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 五 2016-04-08 19:09:33 CST; 53s ago
     Docs: https://docs.docker.com
  Process: 17652 ExecStart=/usr/bin/docker daemon -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 17652 (code=exited, status=1/FAILURE)

4月 08 19:09:33 bjs0-3a4 systemd[1]: Starting Docker Application Container Engine...
4月 08 19:09:33 bjs0-3a4 docker[17652]: time="2016-04-08T19:09:33.404019330+08:00" level=error msg="There are no more loopback de...lable."
4月 08 19:09:33 bjs0-3a4 docker[17652]: time="2016-04-08T19:09:33.404135518+08:00" level=error msg="[graphdriver] prior storage d...failed"
4月 08 19:09:33 bjs0-3a4 docker[17652]: time="2016-04-08T19:09:33.404188107+08:00" level=fatal msg="Error starting daemon: error ...failed"
4月 08 19:09:33 bjs0-3a4 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
4月 08 19:09:33 bjs0-3a4 systemd[1]: Failed to start Docker Application Container Engine.
4月 08 19:09:33 bjs0-3a4 systemd[1]: Unit docker.service entered failed state.
4月 08 19:09:33 bjs0-3a4 systemd[1]: docker.service failed.

bjs0-3a4:root ~ $ journalctl -xe
-- The start-up result is done.
4月 08 19:10:01 bjs0-3a4 systemd[1]: Starting Session 14568 of user root.
-- Subject: Unit session-14568.scope has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-14568.scope has begun starting up.
4月 08 19:10:01 bjs0-3a4 CROND[17895]: (root) CMD (/usr/sbin/ntpdate time1.wanda.cn time2.wanda.cn; )
4月 08 19:10:01 bjs0-3a4 CROND[17896]: (root) CMD (/usr/lib64/sa/sa1 1 1)
4月 08 19:10:01 bjs0-3a4 crond[12483]: postdrop: warning: unable to look up public/pickup: No such file or directory
4月 08 19:10:01 bjs0-3a4 postfix/postdrop[17901]: warning: unable to look up public/pickup: No such file or directory
4月 08 19:11:13 bjs0-3a4 polkitd[3091]: Registered Authentication Agent for unix-process:18069:423404317 (system bus name :1.34468 [/usr/bin
4月 08 19:11:13 bjs0-3a4 systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has begun starting up.
4月 08 19:11:13 bjs0-3a4 docker[18084]: time="2016-04-08T19:11:13.319196047+08:00" level=error msg="There are no more loopback devices avail
4月 08 19:11:13 bjs0-3a4 docker[18084]: time="2016-04-08T19:11:13.319269791+08:00" level=error msg="[graphdriver] prior storage driver \"dev
4月 08 19:11:13 bjs0-3a4 docker[18084]: time="2016-04-08T19:11:13.319313403+08:00" level=fatal msg="Error starting daemon: error initializin
4月 08 19:11:13 bjs0-3a4 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
4月 08 19:11:13 bjs0-3a4 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
4月 08 19:11:13 bjs0-3a4 systemd[1]: Unit docker.service entered failed state.
4月 08 19:11:13 bjs0-3a4 systemd[1]: docker.service failed.
4月 08 19:11:13 bjs0-3a4 polkitd[3091]: Unregistered Authentication Agent for unix-process:18069:423404317

bjs0-3a4:root ~ $ docker daemon
ERRO[0000] There are no more loopback devices available.
ERRO[0000] [graphdriver] prior storage driver "devicemapper" failed: loopback attach failed
FATA[0000] Error starting daemon: error initializing graphdriver: loopback attach failed

```

**Output of `check-config.sh`:**

```
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-3.10.0-229.el7.x86_64 ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
  (RHEL7/CentOS7: User namespaces disabled; add 'user_namespace.enable=1' to boot command line)
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled
- CONFIG_NETPRIO_CGROUP: enabled (as module)
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled (as module)
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

```

**Steps to reproduce the issue:**
1. Start a gitlab container using:
```
docker run --detach --publish 443:443 --publish 80:80 --restart always --volume /srv/gitlab/config:/etc/gitlab --volume /srv/gitlab/logs:/var/log/gitlab --volume /srv/gitlab/data:/var/opt/gitlab gitlab/gitlab-ce

```
2. Kill that container

3. Restart docker daemon, report the above error

4. After remove the directory of '/var/lib/docker', the same error appears

5. The docker daemon could be started using 'docker daemon -D -s vfs'

**Comment by cpuguy83** [comment] 2016-04-08 13:46
Errors indicate there are no available loopback devices.
If this is a prod system, it is not recommended to use loopback devices.

**Comment by yingfeng** [comment] 2016-04-08 14:12
@cpuguy83 What do I need to do then ? thank you~

**Comment by cpuguy83** [comment] 2016-04-08 14:16
https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production

**Comment by thaJeztah** [comment] 2016-04-09 00:03
I'll close this issue, because this is not a bug, but a configuration issue, but feel free to comment after I've closed

**Closed by thaJeztah** 2016-04-09 00:03 UTC
Labels: area/storage/devicemapper
