### ISSUE TITLE
Error initializing graphdriver while starting daemon by systemd on CentOS 7.2

### ISSUE THREAD

**Issue by npcode** [docker/docker#22685] opened 2016-05-12 08:09 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Install docker-engine on CentOS 7.2: `yum install docker-engine`
2. Start it: `sudo systemctl start docker`

**Describe the results you received:**

docker engine didn't start.

**Describe the results you expected:**

docker engine starts.

**Additional information you deem important (e.g. issue happens only occasionally):**

`journalctl --no-pager -u docker` shows this error:
```
 5월 12 17:02:38 test-swarm-master docker[95311]: time="2016-05-12T17:02:38.861386736+09:00" level=info msg="New containerd process, pid: 95314\n"
 5월 12 17:02:38 test-swarm-master docker[95311]: time="2016-05-12T17:02:38.893688865+09:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
 5월 12 17:02:38 test-swarm-master docker[95311]: time="2016-05-12T17:02:38.924229703+09:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored."
 5월 12 17:02:38 test-swarm-master docker[95311]: time="2016-05-12T17:02:38.931908074+09:00" level=fatal msg="Error starting daemon: error initializing graphdriver: \"/var/lib/docker\" contains several valid graphdrivers: devicemapper, overlay; Please cleanup or explicitly choose storage driver (-s <DRIVER>)"  
 5월 12 17:02:38 test-swarm-master systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
```

yum repository:
```
$ cat /etc/yum.repos.d/docker-main.repo 
[docker-main-repo]
name=Docker main Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
```

yum package info:
```
$ yum info docker-engine
Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
Installed Packages
Name        : docker-engine
Arch        : x86_64
Version     : 1.11.1
Release     : 1.el7.centos
Size        : 54 M
Repo        : installed
From repo   : docker-main-repo
Summary     : The open-source application container engine
URL         : https://dockerproject.org
License     : ASL 2.0
Description : Docker is an open source project to build, ship and run any application as a
            : lightweight container.
            : 
            : Docker containers are both hardware-agnostic and platform-agnostic. This means
            : they can run anywhere, from your laptop to the largest EC2 compute instance and
            : everything in between - and they don't require you to use a particular
            : language, framework or packaging system. That makes them great building blocks
            : for deploying and scaling web apps, databases, and backend services without
            : depending on a particular stack or provider.
```

**Comment by thaJeztah** [comment] 2016-05-12 13:36
It looks like you previously ran docker on this host with a different graph-driver;

```
Error starting daemon: error initializing graphdriver: \"/var/lib/docker\" contains several valid graph drivers:
devicemapper, overlay; Please cleanup or explicitly choose storage driver (-s <DRIVER>)"
```

Because of that, docker refuses to start, because it cannot automatically choose which graph-driver it should use. You need to set the `-s` daemon option, for example `-s=overlay` or `-s=devicemapper` to pick which one you want to use.

You can use a daemon configuration file (`/etc/docker/daemon.json`)

https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file

Or a systemd drop-in configuration file;
https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

To set daemon options.

I'll close this issue, because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-05-12 13:36 UTC

**Comment by npcode** [comment] 2016-05-13 01:19
Thanks, @thaJeztah. I agree with this:

> It looks like you previously ran docker on this host with a different graph-driver;

Another docker daemon was installed but uninstalled incompletely in the machine. I guess it caused the problem.

**Comment by RRAlex** [comment] 2017-02-20 19:51
I've hit this issue by doing the following:

- upgrading a 1.12.3 that was using `--live-restore` to 1.13.1 (no issue)
- moving from a docker.service to a docker.service.d/override.conf file (Both file had the same ExecStart with the "-s devicemapper" option set.)
- systemctl daemon-reload (no error)
- rebooting to upgrade the kernel

dockerd didn't start and I had this partition that I needed to `umount /var/lib/docker/aufs && rm -rf !$` by hand after seeing that `journalctl -xe` said the same thing about graphdriver choices:

`/dev/mapper/delve--vg-root on /var/lib/docker/aufs type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)`


This should not have happened with the `-s devicemapper` being explicitly set...

**Comment by thaJeztah** [comment] 2017-02-20 23:04
@RRAlex did you verify the service actually saw the `-s` option? Note that when using an override / drop-in to override `ExecStart`, you have to explicitly _reset_ the `ExecStart`, then set the new value, otherwise the value is _appended_, e.g.;

    [Service]
    ExecStart=
    ExecStart=/usr/bin/dockerd -s=devicemapper

**Comment by RRAlex** [comment] 2017-02-27 16:32
@thaJeztah I'm pretty sure it was running with the right options because, afterwards, docker was running with devicemapper without any further modifications to systemd.

Though I've only tested this once, I'll come back if it happens again... cheers!

**Comment by 88plug** [comment] 2018-03-03 09:06
Simple fix : 
nano /etc/docker/daemon.json

add:
{ "storage-driver": "devicemapper" } for example 

Save - restart Docker.

**Comment by penguinpages** [comment] 2018-11-11 15:51
I am having same issue of starting docker.  What I don't follow is on three nodes.. via various steps that I did of restart or re-run install steps.. it works.. but the other four it does not..  but I have tried now for a few days and not been able to repeat success.. or better yet.. root cause.

Error:  systemctl start docker  ->  /var/log/messages
Nov 11 11:30:45 icpworker01 dockerd: time="2018-11-11T11:30:45.802366532-05:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 11 11:30:45 icpworker01 dockerd: Error starting daemon: error initializing graphdriver: overlay2: unknown option dm.thinpooldev
Nov 11 11:30:45 icpworker01 systemd: docker.service: main process exited, code=exited, status=1/FAILURE



disk setup 
[root@icpworker01 ~]# lvs
  LV           VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root         centos -wi-ao---- <21.97g
  swap         centos -wi-ao----   2.50g
  thinpool     docker twi-a-t--- 379.98g             0.00   0.04
  thinpoolmeta docker -wi-a-----  <4.00g
[root@icpworker01 ~]# cat /etc/docker/daemon.json
{
   "storage-opts": [
     "dm.thinpooldev=/dev/mapper/docker-thinpool",
     "dm.fs=xfs",
     "dm.basesize=20G",
     "dm.min_free_space=5%",
     "dm.use_deferred_deletion=true",
     "dm.use_deferred_removal=true"
   ]
}
[root@icpworker01 ~]# rpm -qa |grep docker
docker-ce-cli-18.09.0-3.el7.x86_64
docker-ce-18.09.0-3.el7.x86_64

I guess I am just not seeing and understanding the root cause here.

**Comment by thaJeztah** [comment] 2018-11-11 16:04
@penguinpages looks like you configured options for the `devicemapper` storage-driver, but did not specify that the daemon should use the devicemapper storage driver.

So, what happens is that (if no storage-driver is specified), the daemon automatically selects the best available driver, which is "overlay2" on most current distros.

However, since the options you specified are specific for `devicemapper`, the daemon refuses to start, because those options are not valid for the `overlay2` storage driver.

If possible, I would also _recommend_ using `overlay2` instead of `devicemapper` (the devicemapper storage driver is marked "deprecated", so will be removed in a future release).

To resolve your problem;

### Option 1. (recommended) use the `overlay2` storage driver, and remove the devicemapper configuration

Also the easiest approach; given that you have no other options configured in your `daemon.json`, you can simply remove the `daemon.json` file, and start the docker service.

If you _do_ have other options set in your `daemon.json`; remove the `storage-opts` from your daemon.json

### Option 2. Override the automatic storage-driver selection, and specify that "devicemapper" should be used

If you have a specific reason to use devicemapper, and want to continue using it; Add `"storage-driver": "devicemapper"` to your `daemon.json` (see the example in the [`dockerd reference documentation`](https://docs.docker.com/engine/reference/commandline/dockerd/#options-per-storage-driver)). 

In your case, the `daemon.json` then should look like this;

```json
{
  "storage-driver": "devicemapper",
   "storage-opts": [
     "dm.thinpooldev=/dev/mapper/docker-thinpool",
     "dm.fs=xfs",
     "dm.basesize=20G",
     "dm.min_free_space=5%",
     "dm.use_deferred_deletion=true",
     "dm.use_deferred_removal=true"
   ]
}
```

**Comment by penguinpages** [comment] 2018-11-11 16:32
.. interesting .. I did not that in the OS matrix: https://success.docker.com/article/compatibility-matrix 

I am new to docker.. so trying to wrap my head around referance design best practices.
What I undestand is their are two volumes needed for docker.. one is for docker deployment of containers (tear down file space). Where containers are deployed.. have scratch but no other real write capabilties (and so IO and capacity sizing is lower for this/these volumes).  They are dedicated and mapped to each individual worker or master.  And I was using the IBM noted guide that underpinned these as LVM so I could as needed inject more "disk" to underpin more IO as customer would have scale up needs.

The second peice of any docker disk subsystem is the "persistant disk".  I have an actual customer where they migrated a datawhere house to containerized version and performance was TERRIBLE.. so much they scrapped the project and moved back to physical systems.  But looking at the design it was all about this persitent disk component.  A heavy IO, container, and one needing capacity, lives and dies by this design component.   

I am still stuck on step one of "What to do for best practice of tear down container volume"  but was heading down the path of iSCSI (via the free product [IBM Spectrum Control](https://www.ibm.com/us-en/marketplace/spectrum-control?S_PKG=-&cm_mmc=Search_Google-_-IBM+Systems_WW_Always+On+Digital_Storage-_-WW_NA-_-+spectrum++control_Broad_-&cm_mmca1=000009SA&cm_mmca2=10005033&cm_mmca7=9010798&cm_mmca8=aud-328707907826:kwd-325594722621&cm_mmca9=_k_Cj0KCQiAw5_fBRCSARIsAGodhk8Ts0j4kmQuVBvoWC36jBu_-1KykPkBac9wXsPanGbiLz_V6RzlChQaAo3kEALw_wcB_k_&cm_mmca10=281580087566&cm_mmca11=b&mkwid=_k_Cj0KCQiAw5_fBRCSARIsAGodhk8Ts0j4kmQuVBvoWC36jBu_-1KykPkBac9wXsPanGbiLz_V6RzlChQaAo3kEALw_wcB_k_%7C503%7C273883&cvosrc=ppc.google.%2Bspectrum%20%2Bcontrol&cvo_campaign=000009SA&cvo_crid=281580087566&Matchtype=b&gclid=Cj0KCQiAw5_fBRCSARIsAGodhk8Ts0j4kmQuVBvoWC36jBu_-1KykPkBac9wXsPanGbiLz_V6RzlChQaAo3kEALw_wcB))  to automate this and provide performance (in conjunction with iSER for iSCSI).  But.. still wrapping head around things so open to constructive redirection of methodology.

My goal is 
1)	Easy deployment with maximum automation
2)	Scaleability without destroy and rebuild
3)	Flexability to deploy both nonpersistent containers and persistent storage containers
4)	Persistent storage that can be scaled up in performance

**Comment by Leo7654** [comment] 2019-07-24 03:35
Try run dockerd with various storage driver to find correct option.
`# dockerd --storage-driver={DRIVER}`
https://docs.docker.com/storage/storagedriver/select-storage-driver/
In my case, it worked with 'vfs'. (AWS RHEL7)
`# mkdir  /etc/docker && vi  /etc/docker/daemon.json`
Set found storage option.
`
{
  "storage-driver": "{DRIVER}"
}
`
And try again without --storage-driver option.
` # dockerd `
If it works, start docker service.
` # systemctl start docker`

**Comment by sebastian-serfe** [comment] 2020-03-20 17:23
> add:
> { "storage-driver": "devicemapper" } for example

This solved my issue. Thanks!
