### ISSUE TITLE
Windows CLI - Inline mage download progress

### ISSUE THREAD

**Issue by icecrime** [docker/docker#12150] opened 2015-04-07 17:21 UTC
When I pull an image and that my buffer is already filled in with things, the display is messed up.

Here you can see that the `"4f9...: Downloading 22.68MB.."` progress indicator is appearing right in the middle of my earlier `docker ps -a` output:

![screen1](https://cloud.githubusercontent.com/assets/1564054/7029079/7742b662-dd0f-11e4-88aa-b76b84440237.png)

Here you can see after pull completed that the "image has been verified" text is also overriding what was previously in my terminal buffer:

![screen2](https://cloud.githubusercontent.com/assets/1564054/7029080/77446458-dd0f-11e4-862e-b9a39ec72596.png)

Ping @ahmetbalkan @brendandixon @jfrazelle!

**Comment by ahmetalpbalkan** [comment] 2015-04-07 17:25
Ooops this used to work. Must be a regression.

**Comment by jfrazelle** [comment] 2015-04-07 18:02
I have seen this as well yesterday, but was unsure if it used to work..

**Comment by jfrazelle** [comment] 2015-04-07 18:03
I have also seen things with clear-ing after stuff I think this is related
to. I will post about it

**Comment by brendandixon** [comment] 2015-04-07 18:12
I am heavily reviewing / rewriting the code. I’ve corrected a few things already. Addressing the sizing problems is on my list, I’ve not yet attacked them. I hope to be (mostly?) done by EOD today. We’ll see. If not today, then likely tomorrow for sure.

Thank you for your patience. Please continue to note problems and I’ll include them (if not otherwise fixed).

Brendan
brendandixon@me.com
425.922.8798

**Comment by icecrime** [comment] 2015-04-07 20:23
@brendandixon To simplify our release (and for @jfrazelle's sake), please try to submit localized fixes to the existing codebase as much as you can. I understand the need for the broader rework, but we are very far in 1.6.0 release process, and I don't think we'd be confortable merging heavy patches at that point.

**Comment by brendandixon** [comment] 2015-04-07 22:49
Will do. Since some of the issues will require the rewrite, we will not be able to address all problems.

**Comment by icecrime** [comment] 2015-04-07 22:52
I think that's an acceptable tradeoff, I'm afraid we can't risk to shake to much code and introduce new problems so far down the release process.

**Comment by cpuguy83** [comment] 2015-09-14 15:33
Is this still a problem?

**Comment by brendandixon** [comment] 2015-09-14 15:43
@ahmetalpbalkan Did Gabe's changes correct this?

**Comment by ahmetalpbalkan** [comment] 2015-09-14 17:29
I think this is also fixed with the rewrite. We can close.

**Closed** 2015-09-14 17:39 UTC
Labels: group/windows, kind/bug
