### ISSUE TITLE
Edit configuration.yml file

### ISSUE THREAD

**Issue by ankurgla22** [docker/docker#19991] opened 2016-02-04 07:06 UTC
I have installed REDMINE using docker and I have to edit configuration.yml file inside container.
I am to edit it but while I am restarting container, all file edited data is lost.
Is there any way to permanently edit the file of docker container?

$ docker exec -it redmine /bin/bash
$ vim config/configuration.yml

**Comment by qq690388648** [comment] 2016-02-04 12:06
What is the version of your docker and os?
My docker 1.9.1 on Ubuntu 12.04.2 work well following below steps:
1 Run a container with Ubuntu image.
2 Edit file /tmp/abc.txt and save it.
3 Stop the container.
4 Start the container.
5 Cat the file /tmp/abc.txt, the content still exists.

**Comment by ankurgla22** [comment] 2016-02-04 13:37
Docker version 1.9.1 & OS is Linux version 4.1.10-17.31.amzn1.x86_64

Yes, above process is also working in my case also.
I can edit any text file & while restarting it still exists.

But to configure SMPT mailing server in Redmine container. I have to edit config/configuration.yml file.
But After editing this file when I restart the container, everything gets lost.
Please help me.

**Comment by thaJeztah** [comment] 2016-02-04 15:39
I cannot reproduce, so I guess this is something in your setup. Are you running the container through systemd? Are you sure the container is only restarted, and not re-created?

Please be aware that the GitHub issue tracker is not a support forum; forums.docker.com, the #docker IRC channel are better channels for support.

I'm going to close this issue, because I don't think this is a bug, but feel free to continue the discussion after I've closed

**Closed by thaJeztah** 2016-02-04 15:39 UTC

**Comment by qq690388648** [comment] 2016-02-05 00:00
What is the image you use? Give me a docker hub link, I will try it on my machine.

**Comment by ankurgla22** [comment] 2016-02-05 00:59
Docker hub link is https://hub.docker.com/r/sameersbn/redmine/#linking-to-postgresql-container

Please have a look what i have done till now:
$ docker pull sameersbn/redmine:latest
$ docker pull sameersbn/mysql:latest
$ docker run --name=mysql -d -e 'DB_NAME=redmine_production' -e 'DB_USER=redmine' -e 'DB_PASS=password' sameersbn/mysql:latest

$ docker run --name=redmine -d -p 80:80 --link mysql:mysql sameersbn/redmine:latest

But to configure SMPT mailing server in Redmine container. I have to edit config/configuration.yml file. So,

$ docker exec -it redmine /bin/bash
$ vi config/configuration.yml
After editing and saving it.
$ exit 

$ docker restart <redmine-docker-id>

**Comment by thaJeztah** [comment] 2016-02-05 01:25
Haven looked really deep into this, but this could be an issue with that image's entrypoint overwriting the configuration file. See; 
https://github.com/sameersbn/docker-redmine/blob/ec75b1a6bb372ae82b64197ff09d677c10bbda05/entrypoint.sh#L10-L12

Which ends up here; https://github.com/sameersbn/docker-redmine/blob/master/assets/runtime/functions#L73-L99

According to the readme, you should NOT edit that file, but pass environment variables to configure mail; https://hub.docker.com/r/sameersbn/redmine/#mail then the entrypoint will automatically generate the configuration file and apply your settings

**Comment by ankurgla22** [comment] 2016-02-08 02:55
Thanks 
It works.
