### ISSUE TITLE
docker login fails when password contains non-alphanumeric characters

### ISSUE THREAD

**Issue by reavowed** [docker/docker#14326] opened 2015-07-01 17:22 UTC
Just ran a docker login command with password "3[00<Suolw$x43;xz/qK" (mildly permuted) and got an HTML error documented vomited into my terminal. Error disappeared when I changed to a purely alphanumeric password.

Two issues:
* This fails when it really shouldn't
* Given that it fails, it should print a reasonable error message instead of drowning my terminal in a 15,000-character HTML document.

Docker version:
>Client version: 1.7.0
>Client API version: 1.19
>Go version (client): go1.4.2
>Git commit (client): 0baf609
>OS/Arch (client): windows/amd64
>Server version: 1.7.0
>Server API version: 1.19
>Go version (server): go1.4.2
>Git commit (server): 0baf609
>OS/Arch (server): linux/amd64

msysgit version:
>git version 1.9.5.msysgit.0

Windows version:
>Windows 8.1 Enterprise

Command output (with most annoying elements removed):
>Error response from daemon: Login: \<!doctype html\>
>\<html class="no-js" lang=""\>
>    \<head\>
>	  REDACTED
>    \</head\>
>    \<body\>
>        \<!--[if lt IE 8]\>
>            \<p class="browserupgrade"\>You are using an \<strong\>outdated\</strong\> browser. Please \<a href="http://browsehappy.com/"\>upgrade your browser\</a\> to improve your experience.\</p\>
>        \<![endif]--\>
>\<div class="svg"\>
>    REDACTED
>\</div\>
>        \<h1\>Oops, there was an error!\</h1\>
>        \<p\>We have been contacted of this error, feel free to check out \<a href="http://status.docker.com/"\>status.docker.com\</a\>
>           to see if there is a bigger issue.\</p\>
>
>    \</body\>
>\</html\> (Code: 500; Headers: map[Strict-Transport-Security:[max-age=31536000] Server:[nginx/1.6.2] Date:[Wed, 01 Jul 2015 17:14:08 GMT] Content-Type:[text/html; charset=utf-8] Vary:[Cookie] X-Frame-Options:[SAMEORIGIN]])

**Comment by ankushagarwal** [comment] 2015-07-01 17:27
status.docker.com shows problems in Docker Hub Oauth and Accounts API
It _could_ be related
![image](https://cloud.githubusercontent.com/assets/796949/8460700/ae718514-1fdb-11e5-8d45-923e6cb01ea7.png)

**Comment by ankushagarwal** [comment] 2015-07-01 20:10
I diagnosed this issue. The real problem is with the v1 registry api endpoint. Here if the password is complicated like `3[00<Suolw$x43;xz/qK`, then the server returns a 500

```
curl -v --user 'username:password' https://index.docker.io/v1/users/
```
Tagging a couple of people who work on registry : @stevvooe @dmp42

Meanwhile, I am pushing a fix to `docker/docker` where you don't get a huge HTML dump from the registry when the server returns a 500, which is happening in this case. 

@calavera  Maybe this fix can be released in 1.7.1?

**Comment by stevvooe** [comment] 2015-07-02 00:02
@reavowed Had this ever worked before? It might be a good idea to file a ticket at support.docker.com as this might be a Hub problem. Looks like @ankushagarwal's fix is part of the solution here. Restricting to alpha-numeric characters in a password is another.

@kencochrane @bcwalrus PTAL

@ankushagarwal Thank you for letting us know. The PR looks okay, but I added a comments.

**Comment by stevvooe** [comment] 2015-07-02 00:04
@ankushagarwal Small clarification: this is not actually the registry. This is a service called the "index", which is commonly confused with the registry. This doesn't change my recommendation above and I'm glad to help.

**Comment by bcwalrus** [comment] 2015-07-15 21:52
I can't reproduce. I changed my test account's password on Hub to be exactly `3[00<Suolw$x43;xz/qK`. I managed to:
* Logout of Hub and log back in.
* Perform `docker login` on docker 1.6.

I started trying it on 1.7.1, but ran into some cert issues.

**Comment by bcwalrus** [comment] 2015-07-15 22:00
Just tested on 1.7.1 successfully as well. Did both `docker login` and the `curl`. Works for me.

**Comment by stevvooe** [comment] 2015-07-15 22:18
@reavowed Are you still seeing the problem? It looks like it has been fixed on the hub.

**Comment by calavera** [comment] 2015-07-15 22:21
Closing to do some house keeping. @reavowed please, feel free to reopen the issue if the problem persists.

**Closed by calavera** 2015-07-15 22:21 UTC
Labels: kind/bug
