### ISSUE TITLE
For scripting, allow disabling verbose "ansi animation" output from CLI

### ISSUE THREAD

**Issue by guss77** [docker/docker#13792] opened 2015-06-07 08:34 UTC
Some commands, such as `docker build` and `docker pull` output ANSI controlled progress reports, which causes automation tools (such as Jenkins) to collect each "frame" as a distinct output lines and as a result there is a lot of verbose and mostly useless noise in the reported output.

The best way to handle this is for docker to detect if a TTY is attached (which is trivial) and if not, limit the verbosity of the output  and disable ANSI progress reports (e.g. output only one "Sending build context" line from `docker build` with the sum of data sent). 

If this can't be detected automatically, please add a feature to disable the ANSI animated progress reports manually.

**Comment by thaJeztah** [comment] 2015-06-07 08:53
@guss77 thanks for reporting, this looks to be a duplicate of https://github.com/docker/docker/issues/3694.

Please make sure to run a recent version of docker, because this issue has come up a couple of times, and I think improvements were made in this area at some point, but perhaps not for this case. (For reference; https://github.com/docker/docker/issues/8342, https://github.com/docker/docker/pull/8150)

I'm going to close this issue, because I think this is a duplicate of https://github.com/docker/docker/issues/3694, please continue the discussion over there.

**Closed by thaJeztah** 2015-06-07 08:53 UTC
