### ISSUE TITLE
Can't destroy container on btrfs: Failed to destroy btrfs snapshot: device or resource busy

### ISSUE THREAD

**Issue by discordianfish** [docker/docker#4897] opened 2014-03-28 17:49 UTC
Hi,

running ubuntu/precise with 3.8 kernel on docker 0.8.1 and got the following when removing a container:

    $ docker rm docker-lloyd-service
    Error: container_delete: Cannot destroy container docker-lloyd-service: Driver btrfs failed to remove root filesystem 7fe9601292d1538b21d82dccfac8bb1715beacb8c48384eb023dff246ea64653: Failed to destroy btrfs snapshot: device or resource busy

Nothing in dmesg. This might be related to/symptom of #4766

**Comment by jfrazelle** [comment] 2015-01-14 21:31
closing as duplicate of https://github.com/docker/docker/issues/9939, the fix is listed there, we need to recursively remove the subvolumes and children subvolumes. help wanted for fix!

**Closed by jfrazelle** 2015-01-14 21:31 UTC

**Comment by rosenfeld** [comment] 2016-06-21 20:29
I experienced this just now but running the command as root completed successfully for some reason...
