### ISSUE TITLE
Unable to use variables in FROM

### ISSUE THREAD

**Issue by Sodki** [docker/docker#18633] opened 2015-12-14 14:55 UTC
In order to provide a better experience for my developers, I have a set of base images that are pre-prepared for them, with different versions of the tools. But I cannot reuse my code properly when dealing with multiple versions of Docker containers. Let's take a look at a small example with Ruby:

This Dockerfile doesn't work, because `VERSION` is only defined after `FROM`:

```
FROM ruby:$VERSION
ARG VERSION
```

This Dockerfile doesn't work, because `FROM` needs to be the first instruction:

```
ARG VERSION
FROM ruby:$VERSION
```

An alternative would be to use a combination of the first one, plus reading the Dockerfile from `stdin`:

`cat Dockerfile | sed "s/\$VERSION/$VERSION/" | docker build --build-args VERSION=$VERSION -`

But this is ugly and creates a Dockerfile with no context, which means I cannot use `COPY` with it, which also defeats my purpose.

I believe ARG should be able to be used before FROM, as some sort of Dockerfile pre-processor.

**Comment by phemmer** [comment] 2015-12-14 19:05
Looks like a dup of #18119

**Comment by thaJeztah** [comment] 2015-12-14 20:40
Oh, yes! I thinks it's close enough to be marked a duplicate (but feel free to add the extra info for using a `ARG` for it)

Closing as duplicate of https://github.com/docker/docker/issues/18119, please continue the discussion there. Thanks!

**Closed by thaJeztah** 2015-12-14 20:40 UTC
Labels: area/builder, kind/enhancement
