### ISSUE TITLE
does docker embedded swarm support "affinity" filter as swarm kit provides?

### ISSUE THREAD

**Issue by hehailong5** [docker/docker#28787] opened 2016-11-24 03:16 UTC

**Comment by thaJeztah** [comment] 2016-11-24 23:23
No. Swarm mode, nor SwarmKit support affinity. Only ["classic" Swarm](https://github.com/docker/swarm) has this option. Only constraints are currently supported; https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#specify-service-constraints---constraint


It's still under discussion if affinity will be added again, because experience with "classic" Swarm has learned there are quite some implications in having it work correctly.

See https://github.com/docker/swarmkit/issues/1442 for a discussion on the implementation for SwarmKit


I'll close this issue, because this is a question, not a bug report. For questions, forums.docker.com, or the Community Slack Channel (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) are the best location, but feel free to continue the conversation here.

**Closed by thaJeztah** 2016-11-24 23:23 UTC
Labels: area/swarm, kind/question

**Comment by hehailong5** [comment] 2016-11-29 13:08
So, what's the current solution for the case that's in need of container affinity?
Say I have service-1, service-2 and service-3 to deploy on a 5-nodes cluster, how to make each running on a separate node? in other words, no more than one service running on the same node?

**Comment by thaJeztah** [comment] 2016-11-29 13:24
There is an open discussion on that here; https://github.com/docker/docker/issues/26259, but it would be useful to explain your _use case_ there, instead of the _solution_. (i.e. what's the reason you want to prevent those services from being on the same node)
