### ISSUE TITLE
wifi dropping when docker starts on RPi

### ISSUE THREAD

**Issue by stevef1uk** [docker/docker#10678] opened 2015-02-10 09:02 UTC
I know I am running docker in a completely unsupported configuration: Raspberry Pi 2 with Rasbian 32bit on arm (Linux rpi2 3.18.6-v7+ #3 SMP PREEMPT Mon Feb 9 15:39:54 UTC 2015 armv7l GNU/Linux). 

Basically, whenever I start docker I loose wifi and therefore connectivity (DHCP) with my RPi. I can manually bring up wifi again but when starting to build docker on the RPi the link goes when a wget is being performed. The only real work around it to plug in an ethernet cable.

I am only raising here in case this is not just a 'funny' with my setup.

I am using docker version:
Client version: 1.3.2-dev
Client API version: 1.16
Go version (client): go1.2.1
Git commit (client): 7ebcdad-dirty
OS/Arch (client): linux/arm
Server version: 1.3.2-dev
Server API version: 1.16
Go version (server): go1.2.1
Git commit (server): 7ebcdad-dirty

The dmesg logs look interesting.

[  385.647211] device veth376436e entered promiscuous mode
[  385.653259] IPv6: ADDRCONF(NETDEV_UP): veth376436e: link is not ready
[  385.735321] eth0: renamed from veth12bc030
[  385.783293] IPv6: ADDRCONF(NETDEV_CHANGE): veth376436e: link becomes ready
[  385.783488] docker0: port 1(veth376436e) entered forwarding state
[  385.783545] docker0: port 1(veth376436e) entered forwarding state
[  386.967902] wlan0: deauthenticating from 74:44:01:fb:ac:dc by local choice (Reason: 3=DEAUTH_LEAVING)
[  387.014634] cfg80211: Calling CRDA to update world regulatory domain
[  387.984311] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready

**Comment by SvenDowideit** [comment] 2015-02-10 12:34
mmm, can you also give us the `docker info` output? (I'm curious about kernel and other versioning)

Hopefully one of the others that work with ARM will see it, as its not mainstream (and 1.3.2? darn, 1.5.0 is happening this week)

**Comment by stevef1uk** [comment] 2015-02-10 12:43
Sure (see below).

I have just built 1.4.1 and the problem is still there.

pi@rpi2 ~ $ docker version
Client version: 1.4.1-dev
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): 918b06f-dirty
OS/Arch (client): linux/arm
Server version: 1.4.1-dev
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): 918b06f-dirty

pi@rpi2 ~ $ docker info
Containers: 2
Images: 36
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 40
Execution Driver: native-0.2
Kernel Version: 3.18.6-v7+
Operating System: Raspbian GNU/Linux 7 (wheezy)
CPUs: 4
Total Memory: 744.5 MiB
Name: rpi2
ID: AKXE:Z7LE:AVBW:PI7V:SR6R:MAAH:M75V:B274:NVKC:MENS:ZZKN:AXA3
Debug mode (server): true
Debug mode (client): false
Fds: 10
Goroutines: 14
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No memory limit support
WARNING: No swap limit support

**Comment by unclejack** [comment] 2015-02-10 13:17
The wifi dongle is connected via USB and the ethernet NIC is also on the USB bus on the Raspberry Pi.
I wouldn't be surprised to find out that there's some kind of system configuration problem on raspbian which is causing these problems.

Is the kernel a vanilla kernel downloaded from kernel.org and compiled for RPi? As far as I know, the RPi requires kernels with custom patches and that frequently leads to all sorts of unique bugs which can't be reproduced on x86_64, i386 and other architectures.

Have you tried other kernels? Can you also try 3.19 or 3.17?

**Comment by stevef1uk** [comment] 2015-02-10 14:57
You are right they are almost certainly on the same USB bus. 

The kernel source code I cloned from here: http://github.com/raspberrypi/linux.git
I have no idea how it may differ from the kernel.org one and as I am not a kernel developer (or even a developer anymore) I am not going to be able to look into that one.

No, I haven't tried on 3.19 as 3.18 seems to be the latest available version. I may have built on 3.17 earlier  but then I wasn't using wifi so I don't know whether I had that problem then.

Sorry I can't be more helpful & thanks for responding.

**Comment by djmaze** [comment] 2015-02-18 00:14
I was experiencing similar problems with Arch Linux ARM on an ODROID-C1. Will see if I can reproduce the case.

**Comment by jfrazelle** [comment] 2015-02-26 17:11
Having Docker run on ARM devices is a planned feature, but keeping this issue open isn't necessary since we do not current support them.

I'll close this issue now since it's not an immediately actionable issue. However, this doesn't mean that this isn't going to be implemented any more. Please feel free to continue to discuss here, we love the discussion!

**Closed by jfrazelle** 2015-02-26 17:11 UTC
Labels: /ecosystem/rasberrypi

**Comment by Mf65** [comment] 2020-12-06 12:31
> I know I am running docker in a completely unsupported configuration: Raspberry Pi 2 with Rasbian 32bit on arm (Linux rpi2 3.18.6-v7+ #3 SMP PREEMPT Mon Feb 9 15:39:54 UTC 2015 armv7l GNU/Linux).
> 
> Basically, whenever I start docker I loose wifi and therefore connectivity (DHCP) with my RPi. I can manually bring up wifi again but when starting to build docker on the RPi the link goes when a wget is being performed. The only real work around it to plug in an ethernet cable.
> 
> I am only raising here in case this is not just a 'funny' with my setup.
> 
> I am using docker version:
> Client version: 1.3.2-dev
> Client API version: 1.16
> Go version (client): go1.2.1
> Git commit (client): [7ebcdad](https://github.com/moby/moby/commit/7ebcdad03043a5cb423aaecbc7932fea76a2f7db)-dirty
> OS/Arch (client): linux/arm
> Server version: 1.3.2-dev
> Server API version: 1.16
> Go version (server): go1.2.1
> Git commit (server): [7ebcdad](https://github.com/moby/moby/commit/7ebcdad03043a5cb423aaecbc7932fea76a2f7db)-dirty
> 
> The dmesg logs look interesting.
> 
> [ 385.647211] device veth376436e entered promiscuous mode
> [ 385.653259] IPv6: ADDRCONF(NETDEV_UP): veth376436e: link is not ready
> [ 385.735321] eth0: renamed from veth12bc030
> [ 385.783293] IPv6: ADDRCONF(NETDEV_CHANGE): veth376436e: link becomes ready
> [ 385.783488] docker0: port 1(veth376436e) entered forwarding state
> [ 385.783545] docker0: port 1(veth376436e) entered forwarding state
> [ 386.967902] wlan0: deauthenticating from 74:44:01:fb:ac:dc by local choice (Reason: 3=DEAUTH_LEAVING)
> [ 387.014634] cfg80211: Calling CRDA to update world regulatory domain
> [ 387.984311] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready

Any idea to fix this Problem? I just run into ist yesterday.
