### ISSUE TITLE
docker exec doesn't work

### ISSUE THREAD

**Issue by chengyli** [docker/docker#29939] opened 2017-01-06 08:38 UTC
I noticed that all containers running on my machine can't be accessed by `docker exec` today, but `docker attach` works. However `docker exec` worked well days ago.
In docker log, it shows a error when `exec resize`, anyone knows the reason?

```
-bash-4.3# docker ps | grep busybox
7fa7f77da7d3        busybox                                              "sh"                     22 hours ago        Up 25 minutes                           high_hamilton
-bash-4.3# docker exec -it 7fa7f77da7d3 sh
-bash-4.3# docker attach 7fa7f77da7d3
/ # ls
bin   dev   etc   home  proc  root  run   sys   tmp   usr   var
/ #
```

```
forward-journal[25209]: time="2017-01-06T07:10:37.423829161Z" level=debug msg="Calling POST /v1.22/containers/7fa7f77da7d3/exec"
 forward-journal[25209]: time="2017-01-06T07:10:37.424028623Z" level=debug msg="POST /v1.22/containers/7fa7f77da7d3/exec"
 forward-journal[25209]: time="2017-01-06T07:10:37.424210608Z" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":[\"sh\"],\"Container\":\"7fa7f77da7d3\",\"Detach\":false,\"DetachKeys\":\"\",\"Privileged\":false,\"Tty\":true,\"User\":\"\"}"
 forward-journal[25209]: time="2017-01-06T07:10:37.424581955Z" level=info msg="{Action=exec, ID=7fa7f77da7d3a57c0d86a4eb178f736ce304b18784c55e2cfc03b0e6ff429c6e, Username=fedora, LoginUID=1000, PID=10577}"
 forward-journal[25209]: time="2017-01-06T07:10:37.426206884Z" level=debug msg="Calling POST /v1.22/exec/9bcd7e55a990c75741f3b3eac710aa38d5737442b289216ffcfea2a0bb991f0f/start"
 forward-journal[25209]: time="2017-01-06T07:10:37.426291469Z" level=debug msg="POST /v1.22/exec/9bcd7e55a990c75741f3b3eac710aa38d5737442b289216ffcfea2a0bb991f0f/start"
 forward-journal[25209]: time="2017-01-06T07:10:37.426439077Z" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":[\"sh\"],\"Container\":\"7fa7f77da7d3\",\"Detach\":false,\"DetachKeys\":\"\",\"Privileged\":false,\"Tty\":true,\"User\":\"\"}"
 forward-journal[25209]: time="2017-01-06T07:10:37.426673537Z" level=info msg="{Action=start, Username=fedora, LoginUID=1000, PID=10577}"
 forward-journal[25209]: time="2017-01-06T07:10:37.426986017Z" level=debug msg="starting exec command 9bcd7e55a990c75741f3b3eac710aa38d5737442b289216ffcfea2a0bb991f0f in container 7fa7f77da7d3a57c0d86a4eb178f736ce304b18784c55e2cfc03b0e6ff429c6e"
 forward-journal[25209]: time="2017-01-06T07:10:37.427438293Z" level=debug msg="Calling POST /v1.22/exec/9bcd7e55a990c75741f3b3eac710aa38d5737442b289216ffcfea2a0bb991f0f/resize"
 forward-journal[25209]: time="2017-01-06T07:10:37.427486477Z" level=debug msg="POST /v1.22/exec/9bcd7e55a990c75741f3b3eac710aa38d5737442b289216ffcfea2a0bb991f0f/resize?h=69&w=272"
 forward-journal[25209]: time="2017-01-06T07:10:37.431768794Z" level=info msg="{Action=resize, Username=fedora, LoginUID=1000, PID=10577}"
 forward-journal[25209]: time="2017-01-06T07:10:37.432198178Z" level=debug msg="attach: stdin: begin"
 forward-journal[25209]: time="2017-01-06T07:10:37.432542652Z" level=debug msg="attach: stdout: begin"
 forward-journal[25209]: time="2017-01-06T07:10:37.433389282Z" level=error msg="Error running command in existing container 7fa7f77da7d3a57c0d86a4eb178f736ce304b18784c55e2cfc03b0e6ff429c6e: [9] System error: fork/exec /proc/self/exe: no such file or directory"
 forward-journal[25209]: time="2017-01-06T07:10:37.433470177Z" level=debug msg="Exec task in container 7fa7f77da7d3a57c0d86a4eb178f736ce304b18784c55e2cfc03b0e6ff429c6e exited with code -1"
 forward-journal[25209]: time="2017-01-06T07:10:37.433610122Z" level=debug msg="attach: stdout: end"
 forward-journal[25209]: time="2017-01-06T07:10:37.433653473Z" level=debug msg="attach: stdin: end"
 forward-journal[25209]: time="2017-01-06T07:10:37.433723516Z" level=error msg="Error running exec in container: Cannot run exec command 9bcd7e55a990c75741f3b3eac710aa38d5737442b289216ffcfea2a0bb991f0f in container 7fa7f77da7d3a57c0d86a4eb178f736ce304b18784c55e2cfc03b0e6ff429c6e: [9] System error: fork/exec /proc/self/exe: no such file or directory\n"
 forward-journal[25209]: time="2017-01-06T07:10:37.433884462Z" level=debug msg="Closing buffered stdin pipe"
 forward-journal[25209]: time="2017-01-06T07:10:37.712857817Z" level=debug msg="Calling GET /containers/json"
 forward-journal[25209]: time="2017-01-06T07:10:37.712893431Z" level=debug msg="GET /containers/json?all=1&limit=0"
 forward-journal[25209]: time="2017-01-06T07:10:37.713004133Z" level=debug msg="{Action=json, LoginUID=4294967295, PID=8797}"
 forward-journal[25209]: time="2017-01-06T07:10:37.973794200Z" level=debug msg="Calling GET /containers/json"
 forward-journal[25209]: time="2017-01-06T07:10:37.973824594Z" level=debug msg="GET /containers/json?limit=0"
 forward-journal[25209]: time="2017-01-06T07:10:37.973938437Z" level=debug msg="{Action=json, LoginUID=4294967295, PID=8797}"
 forward-journal[25209]: time="2017-01-06T07:10:37.976409614Z" level=debug msg="Calling GET /containers/json"
 forward-journal[25209]: time="2017-01-06T07:10:37.976439199Z" level=debug msg="GET /containers/json?limit=0"
 forward-journal[25209]: time="2017-01-06T07:10:37.976528891Z" level=debug msg="{Action=json, LoginUID=4294967295, PID=8797}"
 forward-journal[25209]: time="2017-01-06T07:10:38.433832324Z" level=error msg="Handler for POST /v1.22/exec/9bcd7e55a990c75741f3b3eac710aa38d5737442b289216ffcfea2a0bb991f0f/resize returned error: Exec 9bcd7e55a990c75741f3b3eac710aa38d5737442b289216ffcfea2a0bb991f0f is not running, so it can not be resized."
 forward-journal[25209]: time="2017-01-06T07:10:38.434510112Z" level=debug msg="Calling GET /v1.22/exec/9bcd7e55a990c75741f3b3eac710aa38d5737442b289216ffcfea2a0bb991f0f/json"
 forward-journal[25209]: time="2017-01-06T07:10:38.434552574Z" level=debug msg="GET /v1.22/exec/9bcd7e55a990c75741f3b3eac710aa38d5737442b289216ffcfea2a0bb991f0f/json"
```

```
Containers: 44
 Running: 11
 Paused: 0
 Stopped: 33
Images: 110
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: atomicos-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 11.86 GB
 Data Space Total: 16.64 GB
 Data Space Available: 4.782 GB
 Metadata Space Used: 5.8 MB
 Metadata Space Total: 209.7 MB
 Metadata Space Available: 203.9 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.5.7-202.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 0
CPUs: 16
Total Memory: 57.01 GiB
```

**Comment by gianarb** [comment] 2017-01-06 08:47
Thanks for your report @chengyli .
Can you copy paste the result of the command `docker version`? 
Thanks as lot

**Comment by chengyli** [comment] 2017-01-06 10:17
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-44.git8b7fa4a.fc23.x86_64
 Go version:      go1.5.4
 Git commit:      8b7fa4a/1.10.3
 Built:
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-44.git8b7fa4a.fc23.x86_64
 Go version:      go1.5.4
 Git commit:      8b7fa4a/1.10.3
 Built:
 OS/Arch:         linux/amd64

**Comment by thaJeztah** [comment] 2017-01-06 10:35
@chengyli it looks like you are running a Red Hat fork of Docker (https://github.com/projectatomic/docker/commit/8b7fa4ae473db8400e7a7253965525e5961c45c4). Those versions contain a lot of changes from the official version (https://github.com/docker/docker/compare/v1.10.3...projectatomic:fedora-1.10.3), which may be related. Docker 1.10.3 is no longer maintained; can you try if you're able to reproduce this with the current (1.12.5) version of the official packages? https://docs.docker.com/engine/installation/linux/fedora/

I'll close this issue because this is not a supported version, but happy to help if this issue is reproducible on the current version.

**Closed by thaJeztah** 2017-01-06 10:35 UTC
