### ISSUE TITLE
Error: Driver aufs failed to get image rootfs

### ISSUE THREAD

**Issue by UnderGreen** [docker/docker#7554] opened 2014-08-13 07:31 UTC
Hello.

I can't pull image from docker hub. How to reproduce:
1. Stop docker service
2. Drop all folder recursively in /var/lib/docker/
3. Create symlink /var/lib/docker to directory in $HOME(mounted as ecryptfs, type ext4 same as /)
4. Start docker service
5. Try to pull any image

System info:
```
greenday@ufo:~$ sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```
```
greenday@ufo:~$ sudo docker info
Containers: 0
Images: 1
Storage Driver: aufs
 Root Dir: /home/greenday/Work/var-lib-docker/aufs
 Dirs: 1
Execution Driver: native-0.2
Kernel Version: 3.13.0-29-generic
WARNING: No swap limit support
```
```
greenday@ufo:~$ sudo docker version 
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): d84a070
```
And error:
```
greenday@ufo:~$ sudo docker pull mongo
Pulling repository mongo
c35c0961174d: Error pulling image (latest) from mongo, endpoint: https://cdn-registry-1.docker.io/v1/, Driver aufs failed to get image rootfs ec3443b7b0680b1398205cb8a41cc35c0961174d: Error pulling image (latest) from mongo, Driver aufs failed to get image rootfs ec3443b7b0680b1398205cb8a41cf92ed585204bf48556ab5ac29a0accfdc5de: invalid argument 7b068: Error downloading dependent layers 


2014/08/13 14:06:55 Error pulling image (latest) from mongo, Driver aufs failed to get image rootfs ec3443b7b0680b1398205cb8a41cf92ed585204bf48556ab5ac29a0accfdc5de: invalid argument

```

**Comment by mitar** [comment] 2015-01-11 12:16
I am getting a similar error, no encryption, but also non-standard Docker path, but using `-g` to move it to `/srv`. Started happening after upgrade to 1.4.1:

```
Unable to find image 'mitar/peerdb-benchmark:latest' locally
Pulling repository mitar/peerdb-benchmark
d6eb7da1ba25: Error pulling image (latest) from mitar/peerdb-benchmark, endpoint: https://registry-1.docker.io/v1/, Driver aufs failed to create image rootfs 2770b62fd2142b9e8b1e009521a65771c44bf35a89b4cbee50663035d6eb7da1ba25: Error pulling image (latest) from mitar/peerdb-benchmark, Driver aufs failed to create image rootfs 2770b62fd2142b9e8b1e009521a65771c44bf35a89b4cbee50663035ba2225b5: open /srv/docker/aufs/layers/d37658fba382e41ed0c9700a50fd4fe9132b17378176e5412afc626294ef3e2c: no such file or directory 
607c5d1cca71: Download complete 
f62feddc05dc: Download complete 
8eaa4ff06b53: Download complete 
edad789b7c82: Download complete 
835d903809cb: Download complete 
202d738a9f97: Download complete 
60d87b098c02: Download complete 
aaf9b901cb9b: Download complete 
826c2a881bda: Download complete 
cf42442a2586: Download complete 
0400eaaf6fa2: Download complete 
cba09ece9c2c: Download complete 
0fdc2ea97669: Download complete 
8bd99a5e0387: Download complete 
683d79a3aa23: Download complete 
c3f6c3e0ade0: Download complete 
d37658fba382: Download complete 
2770b62fd214: Error downloading dependent layers 


FATA[0037] Error pulling image (latest) from mitar/peerdb-benchmark, Driver aufs failed to create image rootfs 2770b62fd2142b9e8b1e009521a65771c44bf35a89b4cbee50663035ba2225b5: open /srv/docker/aufs/layers/d37658fba382e41ed0c9700a50fd4fe9132b17378176e5412afc626294ef3e2c: no such file or directory 
```

**Comment by bubuntux** [comment] 2015-03-03 15:19
Having the same issue here, any workaround?

**Comment by schmunk42** [comment] 2015-03-20 20:36
Same here after upgrade from 1.4 to 1.5.0 on an iSCSI volume.

**Comment by schmunk42** [comment] 2015-03-20 21:01
After downgrading to 14.1 I got this error message:

```
c912f2bfb081: Error pulling image (latest) from sameersbn/redis, endpoint: https://registry-1.docker.io/v1/, Driver aufs failed to create image rootfs 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: open /Volumes/iscsi.fuji-1.data/docker/aufs/layers/511136ea3c5a64f264b78b54c912f2bfb081: Error pulling image (latest) from sameersbn/redis, Driver aufs failed to create image rootfs 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: open /Volumes/iscsi.fuji-1.data/docker/aufs/layers/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: no such file or directory
```

I was able to "fix" it by manually creating `[...]/docker/aufs/layers`.
But the following complains about a missing `[...]/docker/repositories-aufs`.

Strange this is, that I wiped and reinstalled docker, but still getting the error?!

**Comment by schmunk42** [comment] 2015-03-20 21:34
Looks to me like docker does not initialize the aufs correctly on service restart or even reinstallation.
My setup was based on https://groups.google.com/forum/#!topic/docker-user/AKqf_qIhFL4 which initializes docker on the host. Then stop the daemon, unmount, move contents and restart.

From looking into my manually specified data directory, I could see that a lot of files which are usually in /var/lib/docker are missing.

**Comment by fermayo** [comment] 2015-05-14 16:20
We are also seeing it when upgrading from docker 1.5.0 to 1.6.0 and try to pull an image:
`Driver aufs failed to create image rootfs d497ad3926c8997e1e0de74cdd5285489bb2c4acd6db15292e04bbab07047cd0: open /var/lib/docker/aufs/layers/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: no such file or directory`

Trying to pull again after a while seemed to work.

**Comment by hugocruz** [comment] 2015-07-09 20:28
After upgrading docker , I have the same issue... Any workarounds ? 
docker version:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

docker info:
Containers: 0
Images: 0
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 3.676 GiB
Name: ip-10-142-173-200
ID: WXU2:NB6M:PLBN:KDRF:3E2X:PBRQ:FUYV:IXTP:WB2I:LLT4:NX22:IMW3
WARNING: No swap limit support

Error message, after while image: 

0e283c6d7b4c: Error downloading dependent layers
0d3bcb8f50b7: Error pulling image (latest) from hugocruz/v3_agent, endpoint: https://registry-1.docker.io/v1/, Driver vfs failed to create image rootfs

**Comment by sroze** [comment] 2015-08-31 13:24
I'm experiencing the same strange issue. @fermayo how did you solve it ?

**Comment by Krijger** [comment] 2015-11-15 09:49
I'm having the same (or at least similar) on a completely new VM (ubuntu 15.10) with 1.8.2 installed.

    Pulling repository docker.io/library/java
    89fa32035323: Error pulling image (openjdk-8u66-jre) from docker.io/library/java, Driver aufs failed to create image rootfs   682fbb572e2e724d9a89a4fd91fa9ed8561eba2f1bc3a55d45d7719781caf5ed: open /var/lib/docker    /aufs/layers/b38503f73b4124ea05d847e89cbaa179636af5c7feb2a6850f1e79ff660faab8: no such file or directory 0f1e79ff660faab8: no such file or directory 
    371b8d572221: Download complete 
    b8546f1ef72a: Download complete 
    682fbb572e2e: Error downloading dependent layers 
    Error pulling image (openjdk-8u66-jre) from docker.io/library/java, Driver aufs failed to create image rootfs 682fbb572e2e724d9a89a4fd91fa9ed8561eba2f1bc3a55d45d7719781caf5ed: open /var/lib/docker/aufs/layers/b38503f73b4124ea05d847e89cbaa179636af5c7feb2a6850f1e79ff660faab8: no such file or directory

**Comment by sroze** [comment] 2015-11-15 10:01
Try with 1.9.0, the problem should be solved. It least it is for me.

**Comment by Krijger** [comment] 2015-11-15 10:28
I was mistaken. I'm running `Docker version 1.9.0, build 76d6bc9`. Mixed it up with Travis, which is running 1.8.2.

`docker pull hello-world` is fine. `docker pull java:openjdk-8u66-jdk` or `docker pull java:openjdk-8u66-jre` not. 
Apparently, it's an issue with the java images. Ubuntu:latest and ubuntu:15.10 also work fine... weird.

**Comment by sroze** [comment] 2015-11-15 10:33
Did you upgrade to 1.9.0? It appears that before this release, concurrent
pulls sometimes were breaking the AUFS tree for some images.

So you should the Docker var, and restart it, everything should be fine!

**Comment by mountwe** [comment] 2015-11-15 15:16
I'm having this problem, also. @sroze, the comment says "So you should the Docker var, and restart it..." 

Can you clarify? I should what the Docker var? Thanks!

**Comment by sroze** [comment] 2015-11-15 15:58
@mountwe basically stopping Docker, removing the directory `/var/lib/docker/` (FYI, it'll remove all the containers and volume you can already have!) and then starting Docker again.

**Comment by mountwe** [comment] 2015-11-15 16:24
@sroze thank you for clarifying. I am running OS X Yosemite 10.10.5. I don't have a /var/lib/docker/ directory.

Did a quick google, found this - a snippet from a StackOverflow  post. The entire conversation is here 
http://stackoverflow.com/questions/19234831/where-are-docker-images-stored-on-the-host-machine

>In the special case of Mac OS X or Windows, using boot2docker, your Docker images are stored within a VirtualBox VM managed by boot2docker.

>This VM will be stored in normal place of VirtualBox images:

      OS X: ~/VirtualBox VMs/boot2docker-vm

      Windows: %USERPROFILE%/VirtualBox VMs/boot2docker-vm

>You can reset it by running (WARNING: This will destroy all images you've built and downloaded so far):
```
boot2docker down
boot2docker destroy
boot2docker init
boot2docker up
```

I did this. It didn't help. I still can't pull Python 2.7 down. I tested. I CAN pull hello-world; presumably I can pull other images. I just can't pull the one I want!

**Comment by mountwe** [comment] 2015-11-15 21:03
@sroze et al. I solved it on my end. I was running Docker v1.5. I upgraded to the new version (1.9). Ran the command again and it worked without a hitch.

In case anyone doesn't know - I was reminded just today by an email from Docker Team - after Nov. 19, v1.5 and earlier will not be able to push to Docker Hub. After Dec. 7, v1.5 and earlier will not be able to push to Docker Hub. 

Thanks for the help!

**Comment by thaJeztah** [comment] 2015-11-26 23:23
@UnderGreen is this resolved for you as well with docker 1.9.1?

**Comment by UnderGreen** [comment] 2015-12-01 08:22
@thaJeztah I changed my Lenovo laptop to Macbook Pro and can't test configuration with encrypted disk.

**Comment by thaJeztah** [comment] 2015-12-01 10:14
@UnderGreen no problem, thanks!

**Comment by thaJeztah** [comment] 2015-12-01 10:16
@schmunk42 @fermayo are you still seeing this on 1.9.1? Otherwise we may need to close this issue by lack of a repro case (we can always reopen if needed)

**Comment by schmunk42** [comment] 2015-12-01 13:10
@thaJeztah haven't seen this for months

**Comment by thaJeztah** [comment] 2015-12-01 13:14
Thanks @schmunk42!

I'm going ahead and close this issue, but anyone feel free to comment here if this is still an issue

**Closed by thaJeztah** 2015-12-01 13:14 UTC
Labels: area/storage/aufs, exp/expert, kind/bug

**Comment by tolmasky** [comment] 2016-02-01 19:32
If I can't get off Docker 1.7, is there any solution to this?

**Comment by dvapelnik** [comment] 2016-02-16 19:51
Same error even on https://hub.docker.com 
Just look at logs:
https://hub.docker.com/r/dvapelnik/docker-lap/builds/bynfidfwd8mzklynzivurv9/
https://hub.docker.com/r/dvapelnik/docker-lap/builds/bxoqydnw2wrumdrstp3hcel/

**Comment by thaJeztah** [comment] 2016-02-16 20:51
@dvapelnik can you contact support@docker.com for that; perhaps the Docker Hub team can look into your situation

**Comment by dvapelnik** [comment] 2016-02-17 00:06
Hi, @thaJeztah 
Thanks for reply
After repeated build the problem does not repeat itself. It looks like no problem but error was
Is seems strange

**Comment by ByteFlinger** [comment] 2016-05-07 20:29
I am having the same issue.

**Output of `docker version`:**
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64
```


**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: <unknown>
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58 GiB
Name: mymachine
ID: GKGG:HESC:P6F2:KQZK:TH2L:ZEFS:KCFG:SWVA:NIL4:SXI4:SCQG:XQT2
Docker Root Dir: /home/byteflinger/.docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Steps to reproduce the issue:**
1. sudo mkdir /etc/systemd/system/docker.service.d
2. sudo vim /etc/systemd/system/docker.service.d/docker.conf
3. Insert the following data
````
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon --graph="/home/byteflinger/.docker" --dns 192.168.9.1 -H fd://
````
4. sudo systemctl daemon-reload
5. sudo systemctl restart docker

**Describe the results you received:**
I have changed dockers root dir from /var/lib/docker to a directory under my home folder due to space issues and then when I restarted docker and tried to pull an image I got the following error

````
$ docker build -t myimage .
Sending build context to Docker daemon 1.728 GB
Step 1 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
6599cadaf950: Pull complete 
23eda618d451: Pull complete 
f0be3084efe9: Pull complete 
52de432f084b: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:15b79a6654811c8d992ebacdfbd5152fcf3d165e374e264076aa435214a947a3
Status: Downloaded newer image for ubuntu:14.04
 ---> 90d5884b1ee0
Step 2 : RUN apt-get update && apt-get -y install 	git 	rsync 	cmake 	lib32z1 	lib32ncurses5 	lib32bz2-1.0
error creating aufs mount to /home/byteflinger/.docker/aufs/mnt/23ba485d147d0a5fdfdd257a4f5216de6331cd529c706e8a8bf37303c730b31b-init: invalid argument
````

**Additional information you deem important (e.g. issue happens only occasionally):**
My home drive is encrypted with eCryptFs like the original poster
