### ISSUE TITLE
Docker daemon failing to push (trying to write 8.8.8.8:53?)

### ISSUE THREAD

**Issue by hamiltont** [docker/docker#9399] opened 2014-11-28 16:30 UTC
I'm trying to push a number of images like this: 

    docker images | grep ^hamiltont/tf | awk '{print $1}' | xargs docker --debug=true push

And I get this output

```
The push refers to a repository [hamiltont/tfb-python-falcon] (len: 1)
Sending image list
Pushing repository hamiltont/tfb-python-falcon (1 tags)
511136ea3c5a: Pushing
2014/11/28 11:21:09 Failed to upload metadata: Put https://cdn-registry-1.docker.io/v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json: dial tcp: write udp 8.8.8.8:53: operation not permitted
```

My setup:

    DOCKER_OPTS="--exec-driver=lxc -H=unix:///var/run/docker.sock -H=0.0.0.0:4243"

and
```
root@3:/home/hamiltont# docker info
Containers: 1813
Images: 323
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 3949
Execution Driver: lxc-1.0.6
Kernel Version: 3.13.0-39-generic
Operating System: Ubuntu 14.04.1 LTS
Username: hamiltont
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
root@3:/home/hamiltont# docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f
```

**Comment by unclejack** [comment] 2015-01-05 16:14
@hamiltont You're using an old version of Docker. Please upgrade.

**Comment by unclejack** [comment] 2015-02-02 10:14
This issue has been reported a long time ago against Docker 1.2.0. Since then, Go has been upgraded and many other changes have been made to Docker itself.

Errors such as this one are usually caused by network problems and there's not much to be done when it comes to Docker itself.

I'm going to close this issue. If anyone runs into this again, please comment on this issue and we'll open it again.

**Closed by unclejack** 2015-02-02 10:14 UTC
