### ISSUE TITLE
docker-for-mac volumes mount failed by 1.12.0-rc2

### ISSUE THREAD

**Issue by MarkThink** [docker/docker#24267] opened 2016-07-02 14:57 UTC
Hi - 
I am using the new version of the native [docker for mac](https://docs.docker.com/docker-for-mac/osxfs/), check the next question of the competence shared data volumes, the default is to load the current user directory, create a subdirectory in the root directory, giving the current user and group rights, data volume failed to load.
Use mysql to reproduce the process:
```
docker run -d -v ~/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD = 123456 mysql: 5.6
```
Everything is normal, the data volumes can load properly

```
docker run -d -v /works/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD = 123456 mysql: 5.6
```
Error, failed to load data volumes

Compare directory permissions
```
➜  ~ ll | grep mysql
drwxr-xr-x@  8 dxwsker  staff   272B  7  2 18:14 mysql
➜  ~ ll /works | grep mysql
drwxr-xr-x   2 dxwsker  staff    68B  7  2 13:43 mysql
```

I also try to restart the machine, or can not be loaded / works / mysql data volume, I know virtualbox virtual machine is only loaded User directory, you can share data directories way to uid, gid privileges docker users mount to a virtual machine, you can to mount the specified data volumes. Since docker 1.12.0-rc2 based HyperKit, it seems to be no way to mount data volume.

Expecting a reply, Thanks!

**Comment by thaJeztah** [comment] 2016-07-03 06:01
The difference is, that in your first example, you're bind-mounting a directory that's within your home directory (`/Users/<yourusername>/`), whereas in the second example, it's a directory outside of that.

By default, only certain directories on OS X can be used for bind mounting, see https://docs.docker.com/docker-for-mac/osxfs/#/namespaces

For the beta, you can prefix the path with `/Mac` to use it, but that option may be removed in the final release, so use;

    docker run -d -v /Mac/works/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD = 123456 mysql: 5.6

This is not a bug, and documented (see the link above), so I'll close this issue, but feel free to comment after I closed

**Closed by thaJeztah** 2016-07-03 06:01 UTC
Labels: group/pinata

**Comment by MarkThink** [comment] 2016-07-03 15:08
I did not carefully read the documents, thank you very much..

**Comment by thaJeztah** [comment] 2016-07-03 17:42
No worries!
