### ISSUE TITLE
Out-of-band volume driver deletions prevents recreation of volume

### ISSUE THREAD

**Issue by jessesuen** [docker/docker#23367] opened 2016-06-08 08:50 UTC
We are using flocker storage driver to manage our volumes across multiple docker hosts. When deleting a volume out-of-band from a docker daemon (which is very common when there are multiple docker hosts using centralized storage driver), then any docker daemon which did not witness the deletion will fail to re-create the volume using the same name. It seems to be that docker daemon is keeping some internal in-memory cache of the state of the volumes, which becomes inconsistent when a volume is deleted from a different docker host.

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64```
```

**Output of `docker info`:**

```
Containers: 11
 Running: 1
 Paused: 0
 Stopped: 10
Images: 1477
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-202:1-272855-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 21.47 GB
 Backing Filesystem: ext4
 Data file: /dev/vg-docker/data
 Metadata file: /dev/vg-docker/metadata
 Data Space Used: 15.36 GB
 Data Space Total: 47.24 GB
 Data Space Available: 31.89 GB
 Metadata Space Used: 58.39 MB
 Metadata Space Total: 4.295 GB
 Metadata Space Available: 4.237 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: syslog
Plugins:
 Volume: local flocker
 Network: bridge null host
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-172-31-250-185
ID: RUXL:5HW4:ASAS:6XK5:TX6A:L5R2:GAGO:OIJO:WD4X:JCF6:BLVL:7LGE
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS
flocker

**Steps to reproduce the issue:**
You do not actually need multiple docker hosts to reproduce the issue. If the storage driver supports it, simply remove the volume out of band, then try to recreate the volume using the same name:

1. docker volume create -d flocker --name jesse
2. HTTP DELETE http://flocker_ip/v1/configuration/datasets/dataset_id
3. docker volume ls (volume will not be shown in list)
4. docker volume create -d flocker --name jesse

**Describe the results you received:**

Step 4 fails to create the volume. 

If docker-daemon is restarted, then step 4 will succeed.
If step 2 is modified to remove the volume in-band (i.e. replace step 2 with 'docker volume rm jesse'), then step 4 succeeds.

**Describe the results you expected:**

In a distributed environment involving multiple docker daemons, an out-of-band volume deletion (from the perspective of a single docker-daemon) is very common. The result of this bug is that some hosts will be able to recreate the volume (those which never seen the volume from 'docker volume ls'), whereas other hosts will be unable to recreate the volume (since from their perspective, the volume disappears from underneath the daemon)

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue is 100% reproducible.

**Comment by thaJeztah** [comment] 2016-06-08 10:41
Are you able to reproduce this on docker 1.11? IIRC, some changes were made in this area

**Comment by jessesuen** [comment] 2016-06-08 17:53
@thaJeztah I will give it a shot.

**Comment by jessesuen** [comment] 2016-06-08 18:03
I just tried with version 1.11.2 and the issue still occurs.

```
root@ip-172-31-250-184:~# docker volume create -d flocker --name jesse
jesse
root@ip-172-31-250-184:~# docker volume ls
DRIVER              VOLUME NAME
local               0ad11cfd0df27f40d256edb6ecd9b94921fe175af2d8f86b65ba036835203a76
local               37e0d063109dd619deefc84656679e1a175faa01bf565b6a35bddeba868fdb73
local               5b17c1fa4b3ce535b6929cd2f909394e10117e668c31411ee1eccf527a862558
local               5f7cc21600753f6271de72d01c373f5dae41d9077ebcf0693fe4701749a12c06
local               eda81824ba2eab0fa8780c106e282d6b3204c376421111121e5fe6f48e1c174a
flocker             jesse

(out of band deletion happens here)

root@ip-172-31-250-184:~# docker volume ls
DRIVER              VOLUME NAME
local               0ad11cfd0df27f40d256edb6ecd9b94921fe175af2d8f86b65ba036835203a76
local               37e0d063109dd619deefc84656679e1a175faa01bf565b6a35bddeba868fdb73
local               5b17c1fa4b3ce535b6929cd2f909394e10117e668c31411ee1eccf527a862558
local               5f7cc21600753f6271de72d01c373f5dae41d9077ebcf0693fe4701749a12c06
local               eda81824ba2eab0fa8780c106e282d6b3204c376421111121e5fe6f48e1c174a
root@ip-172-31-250-184:~# docker volume create -d flocker --name jesse
jesse
root@ip-172-31-250-184:~# docker volume ls
DRIVER              VOLUME NAME
local               0ad11cfd0df27f40d256edb6ecd9b94921fe175af2d8f86b65ba036835203a76
local               37e0d063109dd619deefc84656679e1a175faa01bf565b6a35bddeba868fdb73
local               5b17c1fa4b3ce535b6929cd2f909394e10117e668c31411ee1eccf527a862558
local               5f7cc21600753f6271de72d01c373f5dae41d9077ebcf0693fe4701749a12c06
local               eda81824ba2eab0fa8780c106e282d6b3204c376421111121e5fe6f48e1c174a
root@ip-172-31-250-184:~# docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 638
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-202:1-272855-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 21.47 GB
 Backing Filesystem: ext4
 Data file: /dev/vg-docker/data
 Metadata file: /dev/vg-docker/metadata
 Data Space Used: 12.97 GB
 Data Space Total: 47.24 GB
 Data Space Available: 34.27 GB
 Metadata Space Used: 41.78 MB
 Metadata Space Total: 4.295 GB
 Metadata Space Available: 4.253 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local flocker
 Network: null host bridge
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-172-31-250-184
ID: RUXL:5HW4:ASAS:6XK5:TX6A:L5R2:GAGO:OIJO:WD4X:JCF6:BLVL:7LGE
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Comment by cpuguy83** [comment] 2016-06-08 18:43
Yes, we need a `docker volume rm -f <name>` option.

**Comment by cpuguy83** [comment] 2016-06-08 18:44
@jessesuen Would you have time to do this one?

**Comment by jessesuen** [comment] 2016-06-08 20:45
I'm unfamiliar with both golang and docker source base, so I won't be able to help at least in the short term. That said, I'm not quite sure how a force option (`docker volume rm -f <name>`) would help in this situation. When the daemon gets into this state, the volume does not appear from the list of `docker volume ls`. So in that regard, the volume appears to be gone (and should be recreatable). But it appears there is some other internal state in the docker-daemon (not visible from CLI commands), which is preventing the recreation of the volume.

The `docker volume rm` behaves differently depending on whether the daemon believes the volume should exist or not. In contrary, `docker volume ls` is always accurate to the true state of the volumes. Your suggestion implies there is some `<name>` that is visible and can be `rm`'ed.

I also traced the API calls to the flocker docker plugin. There's definitely a difference in behavior for `docker volume rm` between the two scenarios (out-of-band volume deletion vs. in-band volume deletion).

During the out-of-band volume deletion, the daemon will make a call to `/VolumeDriver.Path` but does not follow it up with anything else.

During the in-band volume deletion, the daemon makes a call to `/VolumeDriver.Get`, then `/VolumeDriver.Create`, and then `/VolumeDriver.Path`.

**Comment by yongtang** [comment] 2016-06-10 14:56
@jessesuen @cpuguy83 @thaJeztah I take a look at this issue. It seems that during the flocker deletion, the `purge()` is not invoked:
https://github.com/docker/docker/blob/v1.11.2/daemon/delete.go#L139-L157
https://github.com/docker/docker/blob/v1.11.2/volume/store/store.go#L418-L421
https://github.com/docker/docker/blob/v1.11.2/volume/store/store.go#L92-L100

From that standpoint I think it probably makes sense to add a `--force` option in `docker volume rm` to invoke the `purge()` and clean up the flocker deleted volumes.

I created a pull request #23436 to try to address this issue. Please take a look and let me know if there are any issues.

(Don't know if `--force` is the best name, maybe `--purge`?)

**Comment by moypray** [comment] 2016-06-29 01:29
Why not remove the cache memory in docker daemon for volumes?  And we have a API VolumeDriver.Get,  to get volume status, and every time we need to operate on a volume, send "GET" operation first to get Volume Status to make sure docker has the latest status of volume.  

And I think the cache in docker is useless and sometimes will bring trouble here.

And GET operation has "status" segment in response. why not use this status to determine whether need recreation of the volumes.

**Comment by moypray** [comment] 2016-07-01 03:15
Hi all, I have a fix for this issue. #24205 

the main idea is:

 When creating a volume in docker, will check the memory cache in docker.  I just step over it and use "VolumeDriver.Get" API to check the volume status.

**Comment by moypray** [comment] 2016-07-01 03:16
ping  @jessesuen   @thaJeztah  @yongtang   @cpuguy83 
Please have a look thanks.

**Comment by erikh** [comment] 2016-07-01 09:56
the problem is here: https://github.com/docker/docker/blob/master/volume/store/store.go#L259. I tweeted this to @cpuguy83 but he must have missed it.

This should be calling getVolume() instead.

**Comment by erikh** [comment] 2016-07-01 09:57
fwiw, `docker volume rm` exhibits the behavior I am prescribing, it calls the `Get` endpoint instead of `Path` which is causing the trouble.

**Closed** 2016-08-19 20:09 UTC
Labels: version/1.10
