### ISSUE TITLE
Docker 1.12.2 grants too much capabilities to unprivileged users

### ISSUE THREAD

**Issue by leonardoce** [docker/docker#27689] opened 2016-10-24 16:24 UTC
**Description**

Docker 1.12.2 grants too much capabilities to unprivileged users, while 1.12.1 was working fine.

**Steps to reproduce the issue:**

1. Test the effective capabilities for a unprivileged user with `docker run --rm -u nobody -it ubuntu:14.04 /bin/bash -c 'cat /proc/self/status |grep CapEff'`

2. Test the effective capabilities for a privileged user with `docker run --rm -it ubuntu:14.04 /bin/bash -c 'cat /proc/self/status |grep CapEff'`

3. Try to setuid root from an unprivileged user

**Describe the results you received:**

```
$ docker run --rm -u nobody -it ubuntu:14.04 /bin/bash -c 'cat /proc/self/status |grep CapEff'
CapEff:	00000000a80425fb

$ docker run --rm -it ubuntu:14.04 /bin/bash -c 'cat /proc/self/status |grep CapEff'
CapEff:	00000000a80425fb

$ docker run --rm -u nobody -it ubuntu:14.04 /bin/bash -c 'python3 -c "import os; os.system(\"id\"); os.setuid(0); os.system(\"id\"); os.system(\"bash\")"'
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)
uid=0(root) gid=65534(nogroup) groups=0(root)
root@c119328b354e:/# exit
```

**Describe the results you expected:**

```
$ docker run --rm -u nobody -it ubuntu:14.04 /bin/bash -c 'cat /proc/self/status |grep CapEff'
CapEff:	0000000000000000

$ docker run --rm -it ubuntu:14.04 /bin/bash -c 'cat /proc/self/status |grep CapEff'
CapEff:	00000000a80425fb

$ docker run --rm -u nobody -it ubuntu:14.04 /bin/bash -c 'python3 -c "import os; os.system(\"id\"); os.setuid(0); os.system(\"id\"); os.system(\"bash\")"'
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
PermissionError: [Errno 1] Operation not permitted
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Docker 1.12.1 works correctly:

```
$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 124
Server Version: 1.12.1
Storage Driver: aufs
[...]

$ docker run --rm -u nobody -it ubuntu:14.04 /bin/bash -c 'cat /proc/self/status |grep CapEff'
CapEff:	0000000000000000

$ docker run --rm -it ubuntu:14.04 /bin/bash -c 'cat /proc/self/status |grep CapEff'
CapEff:	00000000a80425fb

$ docker run --rm -u nobody -it ubuntu:14.04 /bin/bash -c 'python3 -c "import os; os.system(\"id\"); os.setuid(0); os.system(\"id\"); os.system(\"bash\")"'
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
PermissionError: [Errno 1] Operation not permitted
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Thu Aug 18 22:35:21 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 124
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 192
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.24-boot2docker
Operating System: Boot2Docker 1.12.2 (TCL 7.2); HEAD : 9d8e41b - Tue Oct 11 23:40:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: ZTLH:UVL2:NZII:U73A:4SW6:DOLR:KERZ:WKOO:ZBLB:GFHS:67CH:Z7JX
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 24
 System Time: 2016-10-24T16:08:32.607431281Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Comment by justincormack** [comment] 2016-10-24 16:32
Hi, this is a duplicate of #27590 and will be fixed in 1.12.3-rc1 which should be out today. Closing as duplicate.

**Closed by justincormack** 2016-10-24 16:32 UTC
Labels: version/1.12
