### ISSUE TITLE
Tag latest not found in repository docker.io/ahazem/android

### ISSUE THREAD

**Issue by EMart002** [docker/docker#18221] opened 2015-11-25 10:32 UTC
$ docker pull ahazem/android
Using default tag: latest
Pulling repository docker.io/ahazem/android
Tag latest not found in repository docker.io/ahazem/android

I cannot pull this via docker. Pls help

**Comment by thaJeztah** [comment] 2015-11-25 10:42
That looks to be a "problem" with that repository, as can be seen on docker hub, that repository doesn't have a "latest" tag; https://hub.docker.com/r/ahazem/android/tags/

You can either use `docker pull ahazem/android:v0.7.6`, or try to contact the author of that repository and ask to create a `:latest` tag.

I'm going to close this issue, because this is not a bug, and nothing we can do here to solve that issue.

Thanks for reporting though!

**Closed by thaJeztah** 2015-11-25 10:42 UTC
