### ISSUE TITLE
Feature request : give users more control on image dependencies

### ISSUE THREAD

**Issue by TristanCP** [docker/docker#31598] opened 2017-03-07 08:24 UTC
Is there a plan to give users full control on the dependency hierarchy like in Maven (Where you can fix explicitly the version of any transitive dependencies), or is it a non-sense to allow this with Docker images ?

If it's not a plan, it means the upper image (golang for example) has to keep its dependencies for ever (at least no change of major version) as suggest [above ](https://github.com/docker-library/golang/pull/131): "golang:1.7.x-alpine on alpine:3.4 and only replaced alpine:3.5 when golang:1.8.x is out".

Moreover, it means as an operator, you can break your production installation based on Docker images at any point by pulling the exact same tag you had pulled the day before but whose dependency have changed in an uncontrollable way. For example, I pull a tomcat:8.5.11-jre8-alpine based on alpine 3.4 which is the maximum precision I can give to this tag and allows me to set precisely tomcat version and jre major version which is appropriate for a production installation. But tomorrow, with no warning, this same tag could pull an other version of Alpine which breaks my installation.

copied from : https://github.com/docker-library/golang/pull/131 which shows some serious problems can occur with the actual dependency mangement.

**Comment by thaJeztah** [comment] 2017-03-07 09:23
This is already possible, if you use an image _digest_ (immutable identifier), see https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier

So, instead of

```Dockerfile
FROM tomcat:8.5.11-jre8-alpine
```

You use its digest; 

```Dockerfile
FROM tomcat@sha256:b6ebef7ad83492c0437b4cbc84e8a0f6c9a22909c294391ef449e56ed1e30c0c
```

You'll always get exactly the same image, even if the `8.5.11-jre8-alpine` tag is updated in future. For example, the Dockerfile in this repository [pins several images to a specific version](https://github.com/docker/docker/blob/b6e2703230c9262b14df22d4a865f140a897740d/Dockerfile#L230-L234), so that integration tests are reproducible, and don't fail if those images are updated (e.g. https://github.com/docker/docker/pull/31125)

Using digests is the recommended approach for reproducibility (but of course, you won't automatically receive updates for images when they are published).

Docker Content Trust may also be relevant here; https://docs.docker.com/engine/security/trust/content_trust/

**Comment by thaJeztah** [comment] 2017-03-07 11:28
I'll go ahead and close this issue, because I think pulling by digest fits your use-case, and description above, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-07 11:28 UTC
Labels: area/images, kind/question

**Comment by TristanCP** [comment] 2017-03-07 19:56
Ok thanks, this is an interesting feature which maybe makes more sense than allowing any untested dependency hierarchy (like Maven does) for docker images. I'll look into it.
