### ISSUE TITLE
Docker Pull throws Could not reach any registry endpoint error

### ISSUE THREAD

**Issue by kgrvamsi** [docker/docker#15442] opened 2015-08-10 08:57 UTC
BUG REPORT INFORMATION
--

Hello,

i was been trying to fetch some of the base images from the registry and its throwing a error saying the registry endpoint is not reachable .

Docker Version

    vagrant@vagrant-ubuntu-trusty-64:~$ sudo docker version
    Client version: 1.7.1
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 786b29d
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 786b29d
    OS/Arch (server): linux/amd64

Output

    vagrant@vagrant-ubuntu-trusty-64:~$ sudo docker pull mysql:latest
    Pulling repository mysql
    Could not reach any registry endpoint

Some Errors to add

    Get https://registry-1.docker.io/v1/repositories/library/mysql/tags: read tcp 52.7.235.159:443: i/o timeout
    Get https://registry-1.docker.io/v1/repositories/library/mysql/tags: read tcp 54.208.130.47:443: i/o timeout

**Comment by vany-egorov** [comment] 2015-08-10 09:17
**docker version**:
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

**docker info**:
```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 2.95 GiB
Name: debian-800-jessie
ID: BF22:LGJ3:52XO:5UZN:KGI3:UIF3:MM5H:FRT4:XLUQ:IL5Z:5KJC:72EN
Debug mode (server): true
File Descriptors: 13
Goroutines: 19
System Time: 2015-08-10T09:13:46.933865948Z
EventsListeners: 0
Init SHA1: 058b27dcc82371ab0de0834e30ce0ab167e43bc6
Init Path: /usr/lib/docker/dockerinit
Docker Root Dir: /var/lib/docker
WARNING: No memory limit support
WARNING: No swap limit support
```

**uname -a**:
```
Linux debian-800-jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13) x86_64 GNU/Linux
```

**error**
```
ERRO[0125] unable to get remote tags: Get https://registry-1.docker.io/v1/repositories/library/debian/tags: read tcp 54.152.161.54:443: i/o timeout

docker pull debian
Pulling repository debian
Get https://registry-1.docker.io/v1/repositories/library/debian/tags: read tcp 54.152.161.54:443: i/o timeout
```

**Comment by kyndtp** [comment] 2015-08-10 09:18
I think I am having related issues when attempting to push and pull to or from a private repo, and am getting timeout or 500 errors:
```
Error pushing to registry: Server error: unexpected 500 response status trying to initiate upload of togger/entry-layer 
```
**Docker version**
1.7.1, build 786b29d

**Docker info**
Containers: 0
Images: 475
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 475
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.7-boot2docker
Operating System: Boot2Docker 1.7.1 (TCL 6.3); master : c202798 - Wed Jul 15 00:16:02 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: dev
ID: ECHX:RVAJ:PXMF:2NDF:J4EY:5SUD:FGPN:Y43L:TMVK:JS6W:A4OS:X4K5
Debug mode (server): true
File Descriptors: 9
Goroutines: 17
System Time: 2015-08-10T09:16:21.429711564Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: togger
Registry: https://index.docker.io/v1/

**uname -a**
Darwin Pauls-MacBook-Pro.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

**Comment by rwatts3** [comment] 2015-08-10 09:32
I'm receiving the same issues as well connection returns timeout. Although I can search and view the images just fine.

**Comment by eliecharra** [comment] 2015-08-10 09:37
https://status.docker.com/

**Comment by xkidro** [comment] 2015-08-10 09:39
+1

**Comment by letusfly85** [comment] 2015-08-10 09:39
+1

**Comment by albertinisg** [comment] 2015-08-10 09:39
+1

**Comment by balmukund1** [comment] 2015-08-10 09:43
+1

**Comment by arnklint** [comment] 2015-08-10 09:45
+1

**Comment by wildsurfer** [comment] 2015-08-10 09:50
+1

**Comment by shizonic** [comment] 2015-08-10 09:51
+1

**Comment by vilsbole** [comment] 2015-08-10 09:52
+1

**Comment by genggjh** [comment] 2015-08-10 09:58
+1

Get https://registry-1.docker.io/v1/repositories/library/debian/tags: read tcp 54.208.130.47:443: i/o timeout

**Comment by vdemeester** [comment] 2015-08-10 09:59
@kgrvamsi and all others : This is a *service* issue, not related to the docker engine project (it does its work and when the service is down). At the time of my comment, even Github has some degraded response time (https://status.github.com/)

> 11:47 CEST
We're continuing to monitor a known issue with an upstream provider.
10:45 CEST
We've identified an issue with a provider and are continuing to monitor the situation.
09:30 CEST
We are investigating increased error rates on repository release downloads and issue image uploads. 

And Amazon S3 is experiencing some problems :

> 
12:36 AM PDT We are investigating elevated errors for requests made to Amazon S3 in the US-STANDARD Region.
1:00 AM PDT We are working to determine root cause of the elevated error rates and latencies for Amazon S3 in the US-STANDARD Region.
1:08 AM PDT We believe we have identified the root cause of the elevated error rates and latencies for requests to the US-STANDARD Region and are working to resolve the issue.
1:52 AM PDT We are actively working on the recovery process, focusing on multiple steps in parallel. While we are in recovery, customers will continue to see elevated error rate and latencies.
2:38 AM PDT We continue to execute on our recovery plan and have taken multiple steps to reduce latencies and error rates for Amazon S3 in US-STANDARD. Customers may continue to experience elevated latencies and error rates as we proceed through our recovery plan.

Anyway, this is **not a bug** of this project, so this one should probably be closed. The way to bring up an issue of this type is through the support channels (support@docker.com, #docker on irc freenode, etc..)

**Comment by eternaltyro** [comment] 2015-08-10 10:05
Yes. Amazon is experiencing problems: http://status.aws.amazon.com/

**Comment by rwatts3** [comment] 2015-08-10 10:08
Good call.  Figured it had something to do with Amazon.  I tried to
download the latest version of kitematic and Amazon kept failing half way
through.

On Monday, August 10, 2015, eternaltyro <notifications@github.com> wrote:

> Yes. Amazon is experiencing problems: http://status.aws.amazon.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/15442#issuecomment-129393390>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by albers** [comment] 2015-08-10 10:11
As a side effect, building the development environment fails:

    Step 39 : RUN ./contrib/download-frozen-image.sh
    [...]
    curl: (52) Empty reply from server

**Comment by archielc** [comment] 2015-08-10 10:13
We are experiencing the same problem from Rackspace machines.

**Comment by unclejack** [comment] 2015-08-10 10:16
This has nothing to do with Docker itself, it's a problem with the Docker Hub. As has been stated above, the right thing to do is reach out to support@docker.com to let them know about this and any other issue with the Hub.

I'm going to close this now as it's not a bug and keeping this open won't help get the issue fixed any faster.

This is an outage affecting everyone. Please go to https://status.docker.com/ for the latest status updates for this outage.

**Please don't post comments such as "me too", "+1" or anything along those lines. This issue will remain unlocked and everyone will be able to comment. Please comment only if you have something important to add to the discussion.**

**Closed by unclejack** 2015-08-10 10:16 UTC

**Comment by robertoandrade** [comment] 2016-01-27 13:36
I started getting this on all my cloud hosted machines and started looking at logs and everything, realized Docker Hub was spitting back some 403 responses and status was all ok.

Looking at the requests from newer clients I noticed they were performing requests under a different API version, so went back on some previous communication I had received from Docker via email to notice [clients version 1.5 and before were deprecated](https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/), so guessing Docker Hub won't support them anymore.

Thought I'd document it here in case other people come across the same issue.

**Comment by mplewis** [comment] 2016-01-29 03:18
Thanks for the tip @robertoandrade. I fixed this by upgrading my local docker-machine VM:

```sh
docker-machine upgrade YOUR_VM_NAME_HERE
```

**Comment by mluis** [comment] 2016-02-29 14:59
Just installed docker on RPi Zero now and is having the same issue.

**Comment by thinkhy** [comment] 2016-04-16 13:55
Thanks for @robertoandrade 's answer. I resolved the problem on Centos by issuing command:

     sudo yum upgrade docker

"docker pull" works well after upgrading to v1.9

**Comment by sswater** [comment] 2016-07-08 05:12
"docker pull" works well after I "yum upgrade docker-io" to "1.7.1" on "CentOS 6"

**Comment by mdziczkowski** [comment] 2022-06-19 16:18
I get same error message (19 Jun 2022). Maybe it would be best to switch to a region with faster servers that have load ballancing ?
