### ISSUE TITLE
Cant start dockerd on gentoo with zfs (error initializing graphdriver: no such file or directory)

### ISSUE THREAD

**Issue by vnpavanelli** [docker/docker#24704] opened 2016-07-15 23:44 UTC
**Output of `docker version`:**

```
Docker version 1.12.0-rc4, build e4a0dbc
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm running Gentoo with root on ZFS, on a physical machine, my uname -a is:
```
Linux horus 4.4.6-gentoo #1 SMP PREEMPT Fri Jun 24 09:50:03 2016 x86_64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz GenuineIntel GNU/Linux
```

Installed with emerge -av docker, tried too using "curl -sSL https://get.docker.com" without success.

I'm using OpenRC, so "/etc/init.d/docker start" didnt start the daemon, checking more I tried to run dockerd with debug:

```
horus docker # dockerd -D
DEBU[0000] docker group found. gid: 206                 
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] New containerd process, pid: 13386           
DEBU[0000] containerd connection state change: TRANSIENT_FAILURE 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=8 memory=7963 runtime=docker-runc runtimeArgs=[] stateDir=/var/run/docker/libcontainerd/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[0001] Using default logging driver json-file       
DEBU[0001] Golang's threads limit set to 57240          
DEBU[0001] received past containerd event: &types.Event{Type:"live", Id:"", Status:0x0, Pid:"", Timestamp:0x578973c9} 
DEBU[0001] [zfs] ID:fd791c68-b942-4065-815a-3f7f0523ae20 START zfs list -rHp -t filesystem -o name,origin,used,available,mountpoint,compression,type,volsize,quota,written,logicalused,usedbydataset zroot/docker 
DEBU[0001] [zfs] ID:fd791c68-b942-4065-815a-3f7f0523ae20 FINISH 
DEBU[0001] Cleaning up old mountid : start.             
FATA[0001] Error starting daemon: error initializing graphdriver: no such file or directory 
```

I've already create a /var/lib/docker, thats zroot/docker in the above output.
The /var/lib/docker is initialized when I run dockerd -D, tried to clean it but didn't change, it contains 2 empty directories:

```
drwx------ 2 root root 2 Jul 15 20:07 containers
drwx------ 2 root root 2 Jul 15 20:07 tmp
```

I searched for it a couple of days, got some results but are about other problems, like wrong device driver, AFAIK docker got the zfs driver working in my situation.
If this is a duplicate please point me to the correct place and sorry for it.

Thanks for your help

**Comment by dsau** [comment] 2016-07-18 00:11
@vnpavanelli This may be related to 5ec8441, try 'mkdir /var/lib/docker/zfs' then attempt to start the docker daemon.

Also, keep an eye out for 'dataset is busy' errors, which I've started to see after 1.12.rc3, issue is #24403

**Comment by thaJeztah** [comment] 2016-07-18 00:13
@dsau is a change needed in dockerd to create that directory if it doesn't exist?

**Comment by dsau** [comment] 2016-07-18 00:31
@thaJeztah yep, I would say so. Sorry, I should have brought that up earlier, was focused on the other issues.

**Comment by thaJeztah** [comment] 2016-07-18 00:33
@dsau are you interested in contributing, and opening a pull request for that?

**Comment by dsau** [comment] 2016-07-18 00:35
@thaJeztah sure, a nice and easy one to get started in go :)

**Comment by vnpavanelli** [comment] 2016-07-18 00:53
Thank you @dsau it seems to work, I know have other problems with cgroups and my kernel, will check how to fix these!

```
DEBU[0000] docker group found. gid: 206                 
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] New containerd process, pid: 24870           
DEBU[0000] containerd connection state change: TRANSIENT_FAILURE 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=8 memory=7963 runtime=docker-runc runtimeArgs=[] stateDir=/var/run/docker/libcontainerd/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[0001] received past containerd event: &types.Event{Type:"live", Id:"", Status:0x0, Pid:"", Timestamp:0x578c27dd} 
DEBU[0001] Using default logging driver json-file       
DEBU[0001] Golang's threads limit set to 57240          
DEBU[0001] [zfs] ID:180e672f-b3bc-423c-8656-b3b61cf4fc38 START zfs list -rHp -t filesystem -o name,origin,used,available,mountpoint,compression,type,volsize,quota,written,logicalused,usedbydataset zroot/docker 
DEBU[0001] [zfs] ID:180e672f-b3bc-423c-8656-b3b61cf4fc38 FINISH 
INFO[0001] [graphdriver] using prior storage driver "zfs" 
DEBU[0001] Using graph driver zfs                       
DEBU[0001] Max Concurrent Downloads: 3                  
DEBU[0001] Max Concurrent Uploads: 5                    
INFO[0001] Graph migration to content-addressability took 0.00 seconds 
WARN[0001] Your kernel does not support cgroup memory limit 
WARN[0001] Your kernel does not support cgroup cfs period 
WARN[0001] Your kernel does not support cgroup cfs quotas 
WARN[0001] Unable to find blkio cgroup in mounts        
WARN[0001] mountpoint for pids not found                
DEBU[0001] Cleaning up old mountid : start.             
FATA[0001] Error starting daemon: Devices cgroup isn't mounted 
```

**Comment by dsau** [comment] 2016-07-18 01:29
@vnpavanelli no problem, check out https://wiki.gentoo.org/wiki/LXC#Mounted_cgroup_filesystem and https://wiki.gentoo.org/wiki/OpenRC/CGroups

Seems like it should be enabled by default, but if not, try adding rc_controller_cgroups="YES" to /etc/rc.conf

**Comment by dsau** [comment] 2016-07-18 01:29
#dibs

**Comment by vnpavanelli** [comment] 2016-07-18 02:16
It's working now! 
Had to compile and install a new kernel, but that was expected.

Thank you very much @dsau and @thaJeztah !

**Comment by thaJeztah** [comment] 2016-07-18 12:53
reopening, because the issue is not resolved yet (but will be by https://github.com/docker/docker/issues/24741, once merged)

**Closed** 2016-07-19 12:22 UTC
Labels: area/storage/zfs, kind/bug, status/claimed, version/1.12
