### ISSUE TITLE
[support] cannot expose service with the new docker networking feature

### ISSUE THREAD

**Issue by sameersbn** [docker/docker#18238] opened 2015-11-25 17:12 UTC
I am experimenting with the new `docker network` feature to deploy a gitlab service on a single host. In my deployment there are 3 components: postgresql, redis and a gitlab container.

I created a backend network for the postgresql and redis containers:

```bash
docker network create backend
```

Start postgresql container on the `backend` network

```bash
docker run -itd --net=backend --name postgresql \
-e DB_USER=gitlab -e DB_PASS=password -e DB_NAME=gitlab_production \
sameersbn/postgresql
```

Start redis container on the `backend` network

```bash
docker run -itd --net=backend --name redis \
sameersbn/redis
```

Next I started the gitlab container on default docker bridge network,

```bash
docker run -itd --net=bridge --name gitlab \
-p 10080:80 \
-e DB_TYPE=postgres -e DB_HOST=postgresql.backend \
-e DB_USER=gitlab -e DB_PASS=password -e DB_NAME=gitlab_production \
-e REDIS_HOST=redis.backend \
-e GITLAB_SECRETS_DB_KEY_BASE=ghWwd4sFksChP4gK3MbbWCpdFPXWHN \
sameersbn/gitlab
```

and used `docker network connect` so the gitlab container could talk to the containers on the backend network

```bash
docker network connect backend gitlab
```

Once the gitlab container has started I can connect to it using the bridge ip `curl http://172.17.0.1:10080/users/sign_in` but I cannot connect using the host ip, i.e. `curl http://192.168.1.100:10080/users/sign_in`.

> Note:
>  
> - Tests performed on the docker host itself
> - 192.168.1.100 is the ip address of docker host eth0 interface
>

I am unable to expose the gitlab service (10080/tcp) on the host network so that it is accessible to the outside world which basically means being able to access the gitlab server at `http://192.168.1.100:10080/users/sign_in`. Any pointers on this would be helpful.

As an aside, if I run all the above components on the default docker bridge, everything works as expected. i.e.

```bash
# start portgresql
docker run -itd --net=bridge --name postgresql \
-e DB_USER=gitlab -e DB_PASS=password -e DB_NAME=gitlab_production \
sameersbn/postgresql

# start redis
docker run -itd --net=bridge --name redis \
sameersbn/redis

# start gitlab
docker run -itd --net=bridge --name gitlab -p 10080:80 \
--link redis:redisio --link postgresql:postgresql \
-e DB_USER=gitlab -e DB_PASS=password -e DB_NAME=gitlab_production \
-e GITLAB_SECRETS_DB_KEY_BASE=ghWwd4sFksChP4gK3MbbWCpdFPXWHN \
sameersbn/gitlab
```

Docker info:

```bash
# docker info 
Containers: 3
Images: 39
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 993.1 MiB
Name: ubuntu-m1
ID: ZY6G:W4TR:VFG6:G73Z:WHW2:52A4:WQRZ:7ECP:7ADG:MJRB:S6LP:TIQK
Http Proxy: http://192.168.1.93:3128/
WARNING: No swap limit support
```

**Comment by matglas** [comment] 2015-12-07 07:46
I see that you run the gitlab container with -p 10080:80. That means that you should be able to access it on the host ip on the 80 port. But write that you try to curl it on http://192.168.1.100:10080/users/sign_in. That looks like the wrong port.

**Comment by sameersbn** [comment] 2015-12-10 15:39
@matglas I am forwarding host port `10080` to container port `80`. 192.168.1.100 is the host ip, which means that to access the gitlab http interface I need to connect to port `10080` of the 192.168.1.100. As mentioned in the report i can access the http server at `http://172.17.0.1:10080` but for some reason (iptables i guess) the same does not work with 192.168.1.100 (ip address of my physical network interface)

I tested this further using docker-machine and it seems to work fine, that is I can access the http interface using the VMs IP on port 10080 from the docker-machine host.

I see this issue if I run the commands directly on my ubuntu:14.04 host.

**Comment by thaJeztah** [comment] 2015-12-23 22:47
@sameersbn this may be a duplicate of https://github.com/docker/docker/issues/18354, can you check if it is?

**Comment by sameersbn** [comment] 2015-12-24 05:30
@theJeztah no, this is not the same issue. Here the gitlab container is able to talk to the containers connected to the backend network after doing `docker network connect backend gitlab`. The issue here is that the port 10080 exposed by the gitlab container (which is connected to the default bridge interface) cannot be accessed using the ip address of the physical interface, eg. http://182.168.1.1:10080. Having said that, it all works fine when docker-machine is used.

**Comment by rysiekpl** [comment] 2016-03-15 18:37
Is it perhaps related to this `docker-compose` bug? https://github.com/docker/compose/issues/3055

**Comment by thaJeztah** [comment] 2016-10-19 21:23
This is a really old issue now, and there's no activity for a while. I'm closing this issue, but let me know if this is still a problem

**Closed by thaJeztah** 2016-10-19 21:23 UTC
Labels: area/networking
