### ISSUE TITLE
`sudo service docker restart` often fails on debian wheezy due to long termination time

### ISSUE THREAD

**Issue by a-robinson** [docker/docker#11181] opened 2015-03-05 19:36 UTC
I've encountered this on Google Compute Engine using the backports-debian-7-wheezy-v20150226 VM image, and have verified that it breaks both with both of the following versions of Docker:
`Docker version 1.4.1, build 5bc2ff8`
`Docker version 1.5.0, build a8a31ef`

The gist of the problem is that if I have a few containers running, docker is slow to terminate. Because of this, using `sudo service docker restart` sometimes fails because it doesn't wait long enough after stopping docker before trying to start it again.

My apologies if this is a duplicate!

To reproduce:

1. Install docker on your VM
$ sudo apt-get update
$ curl -sSL https://get.docker.com/ | sh

2. Schedule a bunch of containers. This is really hacky, but to reproduce this I just ran this 5 times:
$ sudo docker run nginx:latest &

3. Try restarting docker:
$ sudo service docker restart
[ ok ] Stopping Docker: docker.
[FAIL] Starting Docker: docker failed!

4. Confirm that it didn't work
$ sudo docker ps
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 
$ sudo service docker status
[FAIL] Docker is not running ... failed!

5. Look at the docker logs:
time="2015-03-05T18:54:36Z" level="info" msg="Received signal 'terminated', starting shutdown of docker..."
/usr/bin/docker already running.

**Comment by thaJeztah** [comment] 2015-03-15 16:17
> Schedule a bunch of containers. This is really hacky, but to reproduce this I just ran this 5 times:

    $ sudo docker run nginx:latest &

Is there a specific reason to run the containers in foreground and not in detached (`-d`) mode? I.e.;

    $ sudo docker run -d nginx:latest

Is the issue reproducible if the containers are running detached?

**Comment by unclejack** [comment] 2015-03-18 16:30
@a-robinson Can you provide the full output from `uname -a` from that system, please?

**Comment by naksu** [comment] 2015-04-14 11:31
I'm also seeing this issue, when running just the official docker registry image with -d.  

- Debian wheezy on Virtualbox
- ```Docker version 1.5.0, build a8a31ef```

```$ uname -a```
```Linux rd2.rd 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt7-1~bpo70+1 (2015-04-07) x86_64 GNU/Linux```

**Comment by qingfeng-fy** [comment] 2015-06-09 06:37
may be you can use service docker stop and service docker start instead of service docker restart

**Comment by cpuguy83** [comment] 2015-09-15 00:59
@a-robinson Most likely docker is slow to terminate because your containers are not handling sigterm.
On exit, docker sends sigterm to all containers and waits for them to stop, up to 10 seconds, then proceeds to shutdown.
If it is taking a long time, it is because the containers are not exiting.

I do not think we can really speed up the shutdown process here, however you can send 2 more subsequent SIGTERM's to the daemon and it will exit immediately... note that docker will SIGKILL all containers which are still running when it comes back up.

Closing since I don't think there is anything that can really be done to speed this up other than ensuring the containers are exiting with SIGTERM.

**Closed by cpuguy83** 2015-09-15 00:59 UTC
