### ISSUE TITLE
Swarm service update with new latest tag doesn't work

### ISSUE THREAD

**Issue by tsoikkel** [docker/docker#26978] opened 2016-09-28 10:33 UTC
**Description**

Pulling the latest image and updating service with ```docker service update --image``` doesn't work. 

**Steps to reproduce the issue:**

````
$ docker service ls
ID            NAME                  REPLICAS  IMAGE                                            COMMAND
5ci1j2as5xmu  app  3/3       registry:5000/app:latest

docker pull registry:5000/app:latest
latest: Pulling from app
c0cb142e4345: Already exists
ecd0e3dcad75: Already exists
930b604a99db: Already exists
fa995e374003: Already exists
9ef50a1b05b4: Pull complete
2b88d8930699: Pull complete
Digest: sha256:7a6b2e02a277ead194e679c486f3e4298f567a9f8b9a2b58a1f58696552f904c
Status: Downloaded newer image for registry:5000/app:latest

$ docker service update --image registry:5000/app:latest app
app


```

**Describe the results you received:**

swarm service image doesn't update as expected

**Describe the results you expected:**

swarm service image should be updated to the newest latest


**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker --version
Docker version 1.12.1, build 23cf638
```

**Output of `docker info`:**

```
[descom@MAZWSTEUPRA030 ~]$ docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-127332-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 171 MB
 Data Space Total: 107.4 GB
 Data Space Available: 30.27 GB
 Metadata Space Used: 1.094 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: active
 NodeID: 3s10hs46icv28mtmmpqc1vc3x
 Is Manager: true
 ClusterID: 027j57q6unskuijtz5kcf3otw
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.16.5.30
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.361 GiB
Name: *****
ID: ZEEC:XURK:6O2G:VOKS:XKJ5:5NJF:IWXP:KJ7G:QLE3:M7GL:FWKK:LVDK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure RM VM's running in swarm mode with Azure LB in front.

**Comment by thaJeztah** [comment] 2016-09-28 13:01
If your service already uses `registry:5000/app:latest` as image reference, then Swarm won't see it as being "changed" (it was `registry:5000/app:latest` before, and `docker service update` didn't change that). Pulling the image locally won't make a difference here, because each node keeps it's own image cache, and automatically pull images if the service is updated.

 To make sure that every replica of the service is running the same version, it's best to either "pin" a specific tag (e.g. version `:1.1.0`), or use a _digest_ for the _exact_ version of the image.

We're still discussing options to improve this, and I opened an issue for that a while back; see https://github.com/docker/docker/issues/24066. As a workaround, you can force Swarm to re-deploy the tasks, by updating another property (e.g. adding and removing a label)

I'll close this issue, because it's a duplicate of https://github.com/docker/docker/issues/24066, but thanks for reporting, and please continue the discussion over there.

**Closed by thaJeztah** 2016-09-28 13:01 UTC
