### ISSUE TITLE
Docker Container DNS resolving slow or timeout, when it's bridge net mode

### ISSUE THREAD

**Issue by huahuiyang** [docker/docker#11407] opened 2015-03-16 11:00 UTC
Use the bridge net mode(default setting --net="bridge"), add -v /etc/resolv.conf:/etc/resolv.conf when run a brand new container. 
Do a simple 'ping google.com' in container, and see "ping: unknown host google.com" error message occasionally. Most time it works well.
But It works well when use host net mode(--net="host") all the time as I test. 

My env is Ubuntu12.04+docker1.5.0+linux kernel3.2.0-70 + aufs

Detailed message:
docker info
Containers: 12
Images: 117
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 141
Execution Driver: native-0.2
Kernel Version: 3.2.0-70-virtual
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 8
Total Memory: 7.768 GiB

**Comment by phemmer** [comment] 2015-03-16 12:48
Can you provide the contents of your `/etc/resolv.conf`?
My guess is that you have an entry such as `nameserver 127.0.0.1` in there.

Is there any particular reason you're passing `/etc/resolv.conf` as a mount bind? Docker should already take care of creating `/etc/resolv.conf` inside the container.

**Comment by huahuiyang** [comment] 2015-03-18 04:47
@phemmer    
contents in my /etc/resolv.conf:
nameserver 10.16.99.87

just a inner dns server, my test script is as follows:
docker run busybox ping -c 1 www.google.com

about 1% rate, I will see error message "unknown host www.google.com".

**Comment by huahuiyang** [comment] 2015-03-18 04:49
@phemmer 
btw, it works well all the time when I run this script:
docker run --net="host" busybox ping -c 1 www.google.com

**Comment by huahuiyang** [comment] 2015-03-18 04:50
ping @jpetazzo

**Comment by huahuiyang** [comment] 2015-03-18 06:31
Can we fix this bug by upgrade some network module (without upgrade OS or kernel)?

**Comment by imleon** [comment] 2015-03-19 09:54
@huahuiyang Have you ever checked your DNS server log? 
It may be a query of www.google.com.example.com, where "example.com" is the search-domain of your system.

**Comment by huahuiyang** [comment] 2015-03-23 04:55
@imleon  thanks for comments.
It may not be the dns config error.
After adding an extra dns server(by --dns *** --dns ***), I found the dns resolving error rate has a significant reduction.

**Comment by imleon** [comment] 2015-03-23 06:03
@huahuiyang It may be two problems:
1. DNS server is encountering high pressure.
2. Docker container tries to query with extra (and incorrect) search domain.

**Comment by huahuiyang** [comment] 2015-03-30 03:03
@imleon  
yeah, I prefer to that dns server maybe in high pressure state. 
Because I override the search domain '.' in /etc/resolv.conf, also meet 'unknown host google.com' issue occasionally.

sudo docker run --dns=10.20.*.* --dns=10.16.*.* centos bash -c "echo 'domain .' >> /etc/resolv.conf && ping -c  1 google.com" 

Maybe I can get the dns log to figure out further informations.

**Comment by mavenugo** [comment] 2015-04-22 06:23
@huahuiyang We recently faced a similar TCP connection issue and it turned out to be an issue caused by LRO on the NICs. There is numerous article on the web that talks about this issue and how it impacts linux bridging and forwarding. Easiest way to check for this by using `ethtool -k ethX` & look for large-receive-offload. It can be disabled by `ethtool -K eth2 lro off`. This article gives some more info : http://support.citrix.com/article/CTX127400 on some NIC specific details.

**Comment by brudrafon** [comment] 2015-04-30 11:39
Bridge interface use smallest MAC adress of associated slaves as its own MAC address.
We found that changing MAC adrress can make Linux network stack unhappy, causing problems with packets going throught bridge interface for 10th of seconds (till some caches expire).
We add dummy interface with low MAC address (Linux veth link use MAC adresses starting with FE for all interfaces, so it was easy to find MAC address, which is always lower) as a slave to the bridge docker0 (same workaround is e.g. used in libvirt)

See http://backreference.org/2010/07/28/linux-bridge-mac-addresses-and-dynamic-ports/

**Comment by nathwill** [comment] 2015-05-27 21:26
thanks @brudrafon! i can confirm that we were able to address this issue following the steps outlined in the article you linked (setting the docker0 bridge interface to the same hwaddr as eth0).

**Comment by thaJeztah** [comment] 2015-05-31 18:16
ping @mavenugo is there anything useful for libnetwork in the linked article https://github.com/docker/docker/issues/11407#issuecomment-97746220 to improve this?

**Comment by etuttle** [comment] 2015-07-09 23:18
I followed the suggestions in the article linked by @brudrafon as well and looks like it fixed my failed health checks.

I posted a way to do this in /etc/sysconfig/docker (on RHEL systems) in a gist here: https://gist.github.com/etuttle/bc1cd3814b984ec694d6#file-gistfile1-sh-L18-L43

**Comment by aboch** [comment] 2015-08-06 20:49
@brudrafon @etuttle Please be aware the following [libnetwork vendoring](https://github.com/docker/docker/pull/15185) brought in the fix for the MAC change issue you reported. Correspondent fix in libnetwork can be found (here)[https://github.com/docker/libnetwork/pull/424]

Above fix would be in docker 1.8.0 version

**Comment by thaJeztah** [comment] 2016-02-01 11:46
Is anyone here still having this issue on the current release (1.9.1 / 1.10.0)?

**Comment by yhzhao** [comment] 2016-02-16 16:49
The issue is still there in 1.8.3.

Which version does the fix went in?

**Comment by netroby** [comment] 2016-02-22 02:57
Still have problem dns so slow

```
 $ docker exec docker-hhvm cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0

```

and 
```
 $ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

```

**Comment by netroby** [comment] 2016-02-22 03:01
```
Err http://httpredir.debian.org jessie InRelease                               
  
Err http://httpredir.debian.org jessie-updates InRelease                       
  
Err http://httpredir.debian.org jessie Release.gpg                
  Could not resolve 'httpredir.debian.org'
Err http://dl.hhvm.com jessie InRelease                           
  
Err http://httpredir.debian.org jessie-updates Release.gpg        
  Could not resolve 'httpredir.debian.org'
Err http://security.debian.org jessie/updates InRelease
  
Err http://dl.hhvm.com jessie Release.gpg
  Could not resolve 'dl.hhvm.com'
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Reading package lists... Done
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://dl.hhvm.com/debian/dists/jessie/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://dl.hhvm.com/debian/dists/jessie/Release.gpg  Could not resolve 'dl.hhvm.com'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by tantra35** [comment] 2016-06-08 12:48
In my case we use overlay network, and after some time(perhaps after intensive dns resolving) we also get very slow dns(dig working but very very slow(responce after 4 sec), but ping goog.com doesn't it report that host can't be resolved). No any records in docker.log. We use docker 1.11.2

**Comment by SeanZicari** [comment] 2016-06-22 17:02
@netroby I don't know if it's related, but I would often get those errors in my Debian containers if I don't run `apt-get update` first thing.

**Comment by lennartjuette** [comment] 2016-06-28 07:57
Same problem here:

```
root@wopr:~# docker exec -it  wopr_email  bash -c "time nslookup google.com"
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	google.com
Address: 216.58.214.110


real	0m10.166s
user	0m0.000s
sys	0m0.016s
```

```
root@wopr:~# docker --version
Docker version 1.11.2, build b9f10c9
```

```
root@wopr:~# docker exec -it  wopr_email  cat /etc/resolv.conf
search yourvserver.net
nameserver 127.0.0.11
options ndots:0
```

**Comment by alexbeletsky** [comment] 2016-07-05 08:26
With Docker for Mac, 

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Wed Jun 29 10:03:33 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

I experience slow down of network communication between containers, very likely caused by slow DNS resolution.

```
19root@b660ecd29a8e:/opt/iron# cat /etc/resolv.conf
search local
nameserver 127.0.0.11
options ndots:0
```

Can anyone suggest how to fix it?

**Comment by tantra35** [comment] 2016-07-05 08:59
At container startup we simple substitute resolve.conf, with resolve.conf in which listed real DNS servers

**Comment by alexbeletsky** [comment] 2016-07-05 09:51
@tantra35 but how it resolves internal container-names into ip addresses then?

**Comment by tantra35** [comment] 2016-07-05 10:23
@alexbeletsky in our enviroment we use consul for service discovery

**Comment by thaJeztah** [comment] 2016-07-06 23:13
@alexbeletsky I wonder if the issue is the search domain there; `.local` is used for Bonjour / mDNS https://en.wikipedia.org/wiki/.local, and is known to cause issues (delays) when resolving

**Comment by thaJeztah** [comment] 2016-07-06 23:16
Although I'm not able to reproduce the issue on Docker for Mac (also with a `local` search domain)

**Comment by domnulnopcea** [comment] 2016-08-17 12:46
when is this issue going to be addressed?

**Comment by dissipate** [comment] 2016-08-31 21:42
I'm getting similar issues with overlay networks on Swarm. At first the DNS works fine, then it gets really slow, and then stops working altogether. Never had an issue in bridge mode, though.

**Comment by dissipate** [comment] 2016-08-31 22:46
tantra35:
> In my case we use overlay network, and after some time(perhaps after intensive dns resolving) we also get very slow dns(dig working but very very slow(responce after 4 sec), but ping goog.com doesn't it report that host can't be resolved). No any records in docker.log. We use docker 1.11.2

Same thing is happening to me on docker 1.11.1. I spin up a container on an overlay network and execute dig one after another (waiting for each dig to finish). Eventually, after a number of dig requests, the DNS slows down and then after a certain number of dig requests after that, dig starts failing completely with `;; connection timed out; no servers could be reached`.

**Comment by dissipate** [comment] 2016-08-31 23:28
So far I am not having this issue in `Docker version 1.12.1, build 23cf638`

**Comment by lennartjuette** [comment] 2016-09-03 12:52
I just upgraded and will try it out for a few weeks.

*Before*
```
root@wopr:~# docker --version
Docker version 1.11.2, build b9f10c9
```

*After*
```
root@wopr:~# docker --version
Docker version 1.12.1, build 23cf638
```

**Comment by thaJeztah** [comment] 2016-09-14 16:25
@lennartjuette any results so far?

**Comment by lennartjuette** [comment] 2016-09-14 17:35
I had to reboot my host a few times the past week, so I have no long term results. But as far as I can tell there has been no noticeable delay in dns resolution anymore.

My stats still show some peaks, but the baseline its smoother and lower. Here are some before/after graphs.

![screenshot_2016-09-14-19-32-47](https://cloud.githubusercontent.com/assets/1701636/18522916/577816d2-7ab2-11e6-893a-48582cd371de.png)


![screenshot_2016-09-14-19-32-08](https://cloud.githubusercontent.com/assets/1701636/18522860/1dc95a5e-7ab2-11e6-96ea-418b146cc79e.png)

**Comment by lennartjuette** [comment] 2016-09-15 19:04
I drastically reduced the load on the host. Here are the results:
<img width="1142" alt="screen shot 2016-09-15 at 21 00 52" src="https://cloud.githubusercontent.com/assets/1701636/18563364/b2cc8f9c-7b87-11e6-9060-144f074c56ab.png">

Please keep in mind, that this graph only shows 24 hrs instead of ~150hrs. I'll keep on monitoring.

**Comment by thaJeztah** [comment] 2016-09-15 20:08
@lennartjuette looks hopeful, thanks!

**Comment by lennartjuette** [comment] 2016-09-21 13:12
I haven't had any more timeouts since the last spike 6 days ago. So far, so good. 
 
Upgrading definitely helped. But I also reduced the load on my system significantly 6 days ago and i don't have any spikes anymore, so this may also be (at least a part of) a solution

**Comment by FelikZ** [comment] 2016-10-04 12:55
Still an issue for me (1.12.1) on my working machine:
```
 uname -a
Linux tk9 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Resolving container names inside of containers is noticeably slow.

**Comment by thaJeztah** [comment] 2016-10-10 17:07
@FelikZ could you provide some additional information?

- full output of `docker version` and `docker info`
- are you using the default ("bridge") network, or a custom network?
- what DNS servers do you have configured on the daemon?
- what is "noticeably slow", and how do you test this? (preferably full steps to reproduce the issue)

**Comment by heidricha** [comment] 2016-10-26 15:34
similar problems here.

we use containers to simulate real life networks and hosts (kinda microservices environment)
5 nets (bridged) and 7 containers are created, containers should communicate over bridged networks

user@bt-controller:~$ traceroute central
traceroute to central (10.8.114.131), 30 hops max, 60 byte packets
 1  dev_central_1.dev_core.global.plains.eli-alps.local (10.8.114.131)  0.108 ms  0.041 ms  0.032 ms
user@bt-controller:~$ traceroute central
traceroute to central (10.8.114.131), 30 hops max, 60 byte packets
 1  dev_central_1.dev_core.global.plains.eli-alps.local (10.8.114.131)  0.093 ms * *

same happens to normal communication as well, starting the same app several times in sequence, sometimes works, sometimes cannot connect at all. server is listening normally, repeating the failed attempt again always helps.

**Comment by thaJeztah** [comment] 2016-10-29 05:49
I'm going to close and lock this issue, because this issue has become a collection of network related issues, some of which are not even related to DNS resolution. The original issue was reported with Docker 1.5, and the entire networking stack in docker has been replaced since, so issues in the current version of docker cannot be related.

Also note that if you're having issues on Docker for Mac, please report through https://github.com/docker/for-mac/issues, as those issues can be specific to Docker for Mac (and not the "engine").

If you're still having this issue, please open a new issue with all the relevant information, so that it can be looked into in detail.

Thanks in advance for doing so!

**Closed by thaJeztah** 2016-10-29 05:49 UTC
Labels: area/networking, status/more-info-needed, version/1.5
