### ISSUE TITLE
TestRunStdinPipe flaky after containerd integration

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#21439] opened 2016-03-23 18:40 UTC
Happens because containerd-shim closes the pipe fd before everything has been read out of the fifo and written to the pipe. #21418 does not fully fix the issue

**Comment by thaJeztah** [comment] 2016-03-23 23:16
ehm, duplicate of https://github.com/docker/docker/issues/21365?

**Comment by icecrime** [comment] 2016-03-24 02:16
Yes, closing this one.

**Closed by icecrime** 2016-03-24 02:16 UTC
Labels: kind/flakytest
