### ISSUE TITLE
Unison from mounted volume to another directory stops working after docker daemon restart

### ISSUE THREAD

**Issue by frodopwns** [docker/docker#27832] opened 2016-10-27 18:05 UTC
**Description**

I use unison and unison-fsmonitor to sync changes made to a mounted volume from outside the container. This works until the docker daemon gets restarted. Once this occurs unison will sync changes made to the volume inside the container but not outside. If I do a docker-compose restart at this point it starts to work again.

eg.

mount ./src:/src and unison sync from /src to /var/www/html

Then hit the restart button on Docker For Mac. When it comes back the stuff doesn't sync anymore.

**Steps to reproduce the issue:**
1. Create container with unison and unison-fsmonitor that mounts in a directory from host
2. Make unison and unison-fsmonitor start via supervisord or something
3. mkae unison sync from the mount to anotehr directory in the container
4. Add a file to the volume from outside the container...make sure it works
5. Restart docker daemon or computer
6. Create a new file in volume from outside the container...no longer works

**Describe the results you received:**

Have to restart containers very often to ensure file syncing is working

**Describe the results you expected:**

I expect the syncing to continue to work after the restart like all the other things running in supervisord

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 71
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.24-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.951 GiB
Name: moby
ID: GI52:CJMR:AOLA:66J3:GF2Y:ARVX:ONY7:EYVX:JY6J:WBCI:JFS7:R3UZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 39
 Goroutines: 60
 System Time: 2016-10-27T18:03:09.65185393Z
 EventsListeners: 1
Username: frodopwns
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is docker for mac. I'm using alpine 3.4 in the container. unison version 2.48.4

These are the binaries I'm using. Compiled on alpine 3.4.
1. https://storage.googleapis.com/drud/bin/unison
2. https://storage.googleapis.com/drud/bin/unison-fsmonitor

supervisor conf:

```
[program:unison]
command=/usr/bin/unison /src /var/www/html -batch -repeat watch -perms 0
autostart=true
autorestart=true
startretries=10
user=root
directory=/src
redirect_stderr=true
stdout_logfile=/var/log/supervisor/unison.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
```

**Comment by frodopwns** [comment] 2016-10-28 17:29
The only thing that seems to fix this is 

```
docker stop id && docker start id
```

`docker restart id` does not do the trick.

**Comment by cpuguy83** [comment] 2016-10-28 19:02
ping @dsheets

**Comment by frodopwns** [comment] 2016-10-28 21:11
Just found out that running gulp watch in the host directory that is mounted into the container seems to break the unison/fsmonitor setup.

**Comment by dsheets** [comment] 2016-10-30 13:18
I believe this is the same issue as docker/for-mac#681 which has the same essential cause as docker/for-mac#148. Unfortunately, due to the way file system event listening is connected into containers, file system events will not be delivered after automatic container restart, as a result of running a Docker service with a local bind mount, or via a local Docker volume. We are aware that this is a major issue for some use cases (i.e. it's just broken) and hope to have a complete container event delivery system in place soon.

I'm not sure what you mean about `gulp watch` in the host directory but I cannot conceive of why that would be related at this time.

**Comment by thaJeztah** [comment] 2016-10-30 21:05
Thanks for looking @dsheets 

@frodopwns I'll go ahead and close this issue, as this is already tracked through https://github.com/docker/for-mac/issues/681, and because  this issue is specific to docker for Mac, it's better to track over there.

Thanks for reporting!

**Closed by thaJeztah** 2016-10-30 21:05 UTC
Labels: platform/desktop, version/1.12

**Comment by frodopwns** [comment] 2016-10-31 15:08
@dsheets The `gulp` comment is relevant because its another event that breaks the file system events. My users want to use gulp in their projects so after the container they are using spins up and the volume is mounted they continue to work from the host using the directory that has been mounted in. If they cd to the mounted directory from outside the container and run `gulp` the file systems events are then broken until I `docker stop` and then `docker start`.

**Comment by dsheets** [comment] 2016-10-31 15:43
@frodopwns could you please open a new issue for this `gulp watch` on [docker/for-mac](https://github.com/docker/for-mac/issues) with the results of :whale: :arrow_right: `Diagnose & Feedback...` :arrow_right: `Diagnose & Upload` including the diagnostic ID? It would be fantastic if you could run that and submit a new issue immediately after you observe this `gulp watch` behavior as it will really help us to track down the cause. Thanks!
