### ISSUE TITLE
Cannot connect call api from host. 

### ISSUE THREAD

**Issue by mccormickma** [docker/docker#28123] opened 2016-11-07 11:10 UTC
I'm new to docker and have started with a standard test app, Web.Api. I have added docker support in Visual Studio and when I debug the app I get back the values from the GET method http://localhost:5000/api/values. 
My problem comes from accessing the api when I am not debugging. I can see the container is running and i can run it myself by using the following compose command

```bash
docker-compose -f "C:\Users\ton\MicroserviceStateZor\src\MicroserviceStateZor\docker-compose.yml" -f "C:\Users\ton\MicroserviceStateZor\src\MicroserviceStateZor\docker-compose.dev.debug.yml" -p "microservicestatezor" up -d
```
What I cant do is access the api, http://localhost:5000/api/values doesnt work

My dockerfile is as follows:

```Dockerfile
FROM microsoft/dotnet:latest
ENTRYPOINT ["dotnet", "MicroserviceStateZor.dll"]
ARG source=.
WORKDIR /app 
EXPOSE 5000
COPY $source .
```

My docker-compose.dev.debug.yml is as follows:

```yaml
version: '2'

services:
  microservicestatezordb:
    image: postgres 
    environment:
      - POSTGRES_PASSWORD=test123!
    networks:
      - zordbwebinternalst
  microservicestatezor:
    depends_on: 
      - microservicestatezordb 
    build:
      args:
        source: obj/Docker/empty/
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - POSTGRES_DB=microservicestatezordb
      - POSTGRES_PASSWORD=test123!
    ports:
      - 5000:5000
    networks:
      - zordbwebinternalst
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
networks:
  zordbwebinternalst:
    driver: bridge
```

My docker-compose.yml file is as follows:

```yaml
version: '2'

services:
  microservicestatezordb:
    image: postgres 
    environment:
      - POSTGRES_PASSWORD=test123!
    networks:
      - zordbwebinternalst
  microservicestatezor:
    depends_on: 
      - microservicestatezordb
    image: user/microservicestatezor${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
networks:
  zordbwebinternalst:
    driver: bridge
```

**Comment by thaJeztah** [comment] 2016-11-07 12:59
Given that we don't have the source code of your application, it'll be hard for anyone to reproduce your issue. Also keep in mind that GitHub is not a support forum, but for reporting bugs and feature requests in Docker. 

At a quick glance, I see that your "debug" compose file publishes port 5000 to a _fixed_ port 5000; `5000:5000`, whereas the `docker-compose.yml` file publishes port 5000 to a _random_ port on the host, so you'll have to find which port is published to using (e.g.) `docker inspect <container>` or `docker port <container>`.

Based on the fact that your _debug_ configuration works, but the other configuration doesn't, I don't think there's a bug here, but possibly a misconfiguration.

**Comment by mccormickma** [comment] 2016-11-07 17:47
Thanks for the response thaJeztah and apologies if this is the wrong place for such a question. Been frustrated by this issue for a few days now. I tried setting the port in compose to 5000 so its fixed and same result.

**Comment by thaJeztah** [comment] 2016-11-07 22:55
@mccormickma hm, best recommendation I can give then, is to try adding one setting at a time in your .dev version to see which difference causes the problem.

**Comment by thaJeztah** [comment] 2016-11-26 16:08
I'll close this issue because this does not look like a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-11-26 16:08 UTC
Labels: kind/question, status/more-info-needed
