### ISSUE TITLE
Docker MacVLAN in AWS fails!

### ISSUE THREAD

**Issue by agforte** [docker/docker#30772] opened 2017-02-06 23:30 UTC
**Description**

I am having some problems with Docker MacVLAN. When I create a network with Docker MacVLAN and two containers, the two containers can ping each other but neither one can ping any machine on the internet or even the gateway. The Internet is unreachable.

**Steps to reproduce the issue:**
I also tried this very simple example:
```
sudo docker network create -d macvlan --subnet=192.168.1.xx/26 --gateway=192.168.1.yy --aux-address="exclude_host=192.168.1.zz" -o parent=eth0 mynet

sudo docker run --net=mynet -it --rm image/centosbase:v1 ping -c 4 8.8.8.8
```
this also fails.

**Describe the results you received:**
Ping returns `Destination Host Unreachable`

**Describe the results you expected:**
Being able to ping a server on the internet or even the gateway.

**Additional information you deem important (e.g. issue happens only occasionally):**
When I do, from within a container, `ip a show eth1` I get:
```
35: eth1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UNKNOWN 
    link/ether 02:42:c0:a8:01:42 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.1.xx/26 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c0ff:fea8:142/64 scope link 
       valid_lft forever preferred_lft forever
```
Is it normal that the state is **UNKNOWN**? If I try to bring it UP with `ifconfig eth1 up`, I get `SIOCSIFFLAGS: Operation not permitted`.

Docker using the default bridge mode works with no problems.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 12
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.796 GiB
Name: ip-192-168-1-xx
ID: NF5W:J7P5:GNTP:JGEC:TJQJ:CSMA:QQMJ:6VSK:VTUH:65U3:37EG:54OF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running VMs on AWS with CentOS 7.

**Comment by justincormack** [comment] 2017-02-08 11:20
You cannot use macvlan on AWS. The physical network needs to support multiple Mac addresses on the wire, and cloud providers with virtualised networking do not support this. You need to be running on a network infrastructure you control, or a provider that supports it (I think packet.net for example will).

**Comment by agforte** [comment] 2017-02-08 19:48
OK thanks. And what about IPVlan? Would that work? I could not find any official documentation in the Docker website.

**Comment by thaJeztah** [comment] 2017-03-20 20:21
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-20 20:21 UTC
Labels: area/networking, kind/question, version/1.13

**Comment by MohanrajBabu** [comment] 2018-08-30 13:10
Just want to update here.
I have tried what agforte tried, could able to ping outside network such as google.com.
