### ISSUE TITLE
`docker run` in VirtualBox takes minutes

### ISSUE THREAD

**Issue by trestletech** [docker/docker#18491] opened 2015-12-08 05:02 UTC
I've been using Docker inside of VirtualBox very successfully for some time now. However, I'm now trying to leverage a very large image (Ubuntu + `apt-get install texlive-full` -> 3.6GB image) and am seeing unusably slow performance. I realize that with this many layers of storage obfuscation, I can't expect blazing speed, but I'm just hoping to get `docker run`s to a < 5 second startup time.

Previously `docker run` could execute in < 1 second, but when I create a container that uses the large image, it takes multiple minutes to run a simple `echo hi`.

I'm on a MacBook Pro, but using VirtualBox 5.0.10 to run Ubuntu 14.04: `Linux vagrant-ubuntu-trusty-64 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo docker info
Containers: 1
Images: 7
Server Version: 1.9.1
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 3
Total Memory: 2.939 GiB
Name: vagrant-ubuntu-trusty-64
ID: Y6HT:A2H7:2EWN:AZIU:N7SV:L45B:BOC7:ZOBB:DUDP:N2IW:M4QU:DTMJ
WARNING: No swap limit support
```

```
vagrant@vagrant-ubuntu-trusty-64:/connect$ sudo docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:08:59 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:08:59 UTC 2015
 OS/Arch:      linux/amd64
```

I've tested using using both the Unix Socket and TCP and both have the same problems. I am mounting a separate virtual disk to `/var/lib/docker`. I've tried creating a dynamically sized VDI image and a fixed-size VMDK and both have similar performance issues. To the best of my knowledge, no Docker data is being stored using the infamously slow VirtualBox shared drives, though I do have a couple of directories mounted elsewhere on the machine.

Anecdotally, it looks like this problem does not exist in VMWare. When using VMWare Fusion with the same provisioning scripts, I'm able to get docker to create a container from the large image in a fraction of a second.

Docker Daemon log with GC debugging enabled: https://www.dropbox.com/s/aj1rkgk8mp5g95w/daemon.log?dl=0
First 5,000 lines of strace of Docker daemon (~500kB): https://www.dropbox.com/s/ebwj0w8arfkwf21/strace.head.log?dl=0

The full strace is 7.2GB. I'll compress it and try to get it online somewhere should it be needed, but hopefully the head I included above can get things started.

Appeared similar to this issue: https://github.com/docker/docker/issues/5250, though I didn't notice any outlandishly slow fsyncs in my dump.

**Comment by thaJeztah** [comment] 2015-12-08 10:59
Looks like you're using `vfs` as a storage driver. The vfs driver is not a copy-on-write filesystem and really just there as a "last resort" if anything else is missing. Also see this stackoverflow question; http://stackoverflow.com/questions/24736778/why-is-the-docker-vfs-storage-backend-not-considered-suitable-for-production

I'd recommend to install the required packages for another storage driver. For Ubuntu, the default storage driver is aufs, which can be used if the linux-image-extra package is installed on your system; see the installation docs here; https://docs.docker.com/engine/installation/ubuntulinux/

For more information about all storage drivers, and deciding which storage driver may be best for your use case, see this section in the documentation: https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/. After installing and switching the storage driver, you may need to wipe your `/var/lib/docker` directory to remove the old images and containers.

I'm going to close this issue, because this is expected behavior with the vfs storage driver, but feel free to comment here after I've closed.

I hope you'll be able to solve your issue with the information above :+1:

**Closed by thaJeztah** 2015-12-08 10:59 UTC

**Comment by trestletech** [comment] 2015-12-08 15:54
Thanks so much! After reading up on it a bit that makes perfect sense. I'm reprovisioning now to confirm the fix. Perhaps my VMWare base image already had the linux-image-extra included.

It's possible that I completely missed it, but if I may humbly suggest promoting this "vfs doesn't count as a real storage system" tidbit more heavily in these docs, I suspect others might benefit. All the official docs I found were first to say that "each driver has its pros and cons," but I didn't understand that `vfs` was the outlier there, so I hadn't worried about it.

Thanks again.
