### ISSUE TITLE
Same IP adress attribution for 2 differents containers

### ISSUE THREAD

**Issue by mmicael1** [docker/docker#19086] opened 2016-01-05 14:16 UTC
Hi all,

I have an issue with multiples containers. if i run many containers, about 150, i have two containers with same ip adress

Container 1:

"Networks": {
            "bridge": {
                "EndpointID": "16b37d1ca29d14b7e790a70098c700d3cd809a96d0d2ad98447243bf0cbd548e",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.115",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:73"
            }
        }

Container 2:

"Networks": {
            "bridge": {
                "EndpointID": "dec22518804cf773477f8e1c68342b6977b8b57f1cc9fbbcd33b573adadd3a7f",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.115",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:73"
            }
        }

How can it be possible and how to fix it?

Thx

**Comment by thaJeztah** [comment] 2016-01-05 14:40
Thanks for reporting, I think this is a duplicate of https://github.com/docker/docker/issues/18535, and is resolved in the latest libnetwork (https://github.com/docker/docker/pull/18106), which will be in Docker 1.10, see https://github.com/docker/docker/issues/18535#issuecomment-164494430

You can already test this fix (not on a production server!) by downloading a master build from https://master.dockerproject.org

I'll close this issue, because this will be resolved in 1.10, but feel free to comment here if you're still able to reproduce this on the current master.

**Closed by thaJeztah** 2016-01-05 14:40 UTC

**Comment by mmicael1** [comment] 2016-01-05 15:21
Thanks for reply

I will wait for next release and test with stop & start workaround
