### ISSUE TITLE
Error pulling image (...) no space left on device

### ISSUE THREAD

**Issue by MitchK** [docker/docker#10613] opened 2015-02-06 09:32 UTC
Hi, I try to pull an image from a private corporate registry to a machine.

The image is a NodeJS image with some custom environment variables + a NodeJS application with npm dependencies.

The machine has 4GB of RAM.

```
user@machine:~$ docker pull my.private.registry.corp/org/image
Pulling repository my.private.registry.corp/org/image
a076dcf8de89: Pulling dependent layers 
511136ea3c5a: Download complete 
27d47432a69b: Download complete 
5f92234dcf1e: Download complete 
51a9c7c1f8bb: Download complete 
5ba9dab47459: Download complete 
1b5cb86bd8eb: Download complete 
e052bcc1b051: Download complete 
a076dcf8de89: Error pulling image (latest) from my.private.registry.corp/org/image, Untar exit status 1 open /tmp/app/node_modules/node-rest-client/node_modules/xml2js/node_modules/xmlbuilder/node_modules/lodash/utility/attempt.js: no space left on device odash/utility/attempt.js: no space left on device wnload complete 
9a7129a697b6: Download complete 
5a4df78f03f1: Download complete 
91e17b8f0ad0: Download complete 
27fd9249b530: Download complete 
21d10d188d73: Download complete 
95c43c63c917: Download complete 
875aec76aa78: Download complete 
a8ed7d8cb50f: Download complete 
300671eaa3d4: Download complete 
be9f77f4e0cb: Download complete 
4f58aff69463: Download complete 
de93133d1b6e: Download complete 
1965d5845989: Download complete 
cae34eb68397: Download complete 
dfcf337450ef: Download complete 
bf8c96846c44: Download complete 
e76410f1b8c1: Download complete 
644792e8361d: Download complete 
8a9b2274fed7: Download complete 
3fc11a89092f: Error downloading dependent layers 
FATA[0007] Error pulling image (latest) from my.private.registry.corp/org/image, Untar exit status 1 open /tmp/app/node_modules/node-rest-client/node_modules/xml2js/node_modules/xmlbuilder/node_modules/lodash/utility/attempt.js: no space left on device 
```

The strange thing is that there is space left on the device.
```
$ df -h
Filesystem                                          Size  Used Avail Use% Mounted on
/dev/mapper/packer--UBUNTU1204--BUILD--54--vg-root   39G   23G   15G  61% /
udev                                                2.0G   12K  2.0G   1% /dev
tmpfs                                               395M  244K  395M   1% /run
none                                                5.0M     0  5.0M   0% /run/lock
none                                                2.0G  188K  2.0G   1% /run/shm
/dev/sda1                                           228M   28M  189M  13% /boot
cgroup                                              2.0G     0  2.0G   0% /sys/fs/cgroup
```

**Comment by MitchK** [comment] 2015-02-06 09:33
@thojansen

**Comment by phemmer** [comment] 2015-02-06 13:38
Can you please provide `docker info` and `docker version`?

**Comment by morgante** [comment] 2015-02-06 18:00
You might want to see if you have free inodes left with `df -i`.

We've been having major issues (#9755) with Docker exhausting inodes.

**Comment by MitchK** [comment] 2015-02-10 18:14
Hi,

we needed a quick fix, so throwing away all images and containers helped. But I'm not sure I this will fix the actual issue.

I'll keep you posted.

**Comment by lamielle** [comment] 2015-02-12 22:09
I just ran into this same inode-exhaustion issue on a CoreOS instance running Docker 1.5 (alpha 591.0.0 showed up as a vagrant box today).

    core@core-01 ~ $ df -h
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/sda9        16G  5.4G  9.7G  36% /
    devtmpfs        991M     0  991M   0% /dev
    tmpfs          1004M     0 1004M   0% /dev/shm
    tmpfs          1004M  732K 1003M   1% /run
    tmpfs          1004M     0 1004M   0% /sys/fs/cgroup
    /dev/sda3       985M  308M  626M  33% /usr
    tmpfs          1004M     0 1004M   0% /media
    tmpfs          1004M     0 1004M   0% /tmp
    /dev/sda6       108M   88K   99M   1% /usr/share/oem


    core@core-01 ~ $ df -i
    Filesystem      Inodes   IUsed  IFree IUse% Mounted on
    /dev/sda9      1058720 1050693   8027  100% /
    devtmpfs        253694     309 253385    1% /dev
    tmpfs           256770       1 256769    1% /dev/shm
    tmpfs           256770     474 256296    1% /run
    tmpfs           256770      14 256756    1% /sys/fs/cgroup
    /dev/sda3       260096    5250 254846    3% /usr
    tmpfs           256770       1 256769    1% /media
    tmpfs           256770      10 256760    1% /tmp
    /dev/sda6        32768      19  32749    1% /usr/share/oem


    core@core-01 ~ $ docker info
    Containers: 22
    Images: 281
    Storage Driver: overlay
     Backing Filesystem: extfs
    Execution Driver: native-0.2
    Kernel Version: 3.18.6
    Operating System: CoreOS 591.0.0
    CPUs: 1
    Total Memory: 1.959 GiB
    Name: core-01
    ID: DOHI:P4U4:3EW2:6KZX:KXBT:P2E4:E4Z6:MQZK:73JF:ZGHD:37PX:WBHL
    Debug mode (server): true
    Debug mode (client): false
    Fds: 112
    Goroutines: 87
    EventsListeners: 1
    Init SHA1: ce0bed698ca2c3b90d2ecb50a7baa451459d8c30
    Init Path: /usr/libexec/docker/dockerinit
    Docker Root Dir: /var/lib/docker

    core@core-01 ~ $ docker version
    Client version: 1.5.0
    Client API version: 1.17
    Go version (client): go1.3.3
    Git commit (client): a8a31ef-dirty
    OS/Arch (client): linux/amd64
    Server version: 1.5.0
    Server API version: 1.17
    Go version (server): go1.3.3
    Git commit (server): a8a31ef-dirty

Short of giving up and building this host from scratch, is there anything I can do to free up inodes on this filesystem?

**Comment by crosbymichael** [comment] 2015-02-23 19:54
ping @dmp42 @jlhawn

**Comment by dmp42** [comment] 2015-02-23 22:17
@MitchK do you still have this issue?
Were you able to confirm whether this is an inode exhaustion issue, or purely disk space issue?

Thanks a lot!

**Comment by allinwonder** [comment] 2015-03-18 10:17
I hit the same problem and it is inode issue on the rootfs, created seperated volume for /var/lib/docker mount point to work around this issue

**Comment by bitliner** [comment] 2015-04-13 22:18
It is happening on my laptop with kernel Linux bitliner-laptop 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

ubuntu 14.04

docker-info

Containers: 0
Images: 691
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 691
Execution Driver: native-0.2
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.257 GiB
Name: bitliner-laptop
ID: VQZJ:63LB:7DUF:IF7Y:JEMF:VNKB:PXVJ:PA4A:6M5W:BUIH:633N:DHP7
Username: bitliner
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
docker version

Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

**Comment by dmp42** [comment] 2015-04-13 22:28
@bitliner is this a inode exhaustion issue? (see previous comments)
or purely disk space?

**Comment by bitliner** [comment] 2015-04-13 22:31
I have 8.8gb free, I guess it is inode exhaustion, I'll check it out

**Comment by xueshanf** [comment] 2015-04-14 23:09
I have a dedicated 100GB docker volume but  the system was running out of inode out of 6million!  I got "So space left on device error". 

I cleaned up some images, but not enough. Is it really using 6 million inodes? 
```
core@ip-10-42-2-93 /var/lib/docker/overlay $ df -i
Filesystem       Inodes   IUsed    IFree IUse% Mounted on
/dev/xvda9     12444032   22778 12421254    1% /
devtmpfs         954863     328   954535    1% /dev
tmpfs            957948       1   957947    1% /dev/shm
tmpfs            957948    1302   956646    1% /run
tmpfs            957948      14   957934    1% /sys/fs/cgroup
/dev/xvda3       260096    5258   254838    3% /usr
tmpfs            957948     638   957310    1% /tmp
tmpfs            957948       1   957947    1% /media
/dev/xvda6        32768      12    32756    1% /usr/share/oem
/dev/xvdb       6553600 6050368   503232   93% /var/lib/docker
```
```
core@ip-10-42-2-93 /var/lib/docker/overlay $ df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/xvda9     ext4       47G  882M   44G   2% /
devtmpfs       devtmpfs  3.7G     0  3.7G   0% /dev
tmpfs          tmpfs     3.7G     0  3.7G   0% /dev/shm
tmpfs          tmpfs     3.7G  3.6M  3.7G   1% /run
tmpfs          tmpfs     3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/xvda3     ext4      985M  309M  626M  34% /usr
tmpfs          tmpfs     3.7G   45M  3.7G   2% /tmp
tmpfs          tmpfs     3.7G     0  3.7G   0% /media
/dev/xvda6     ext4      108M   56K   99M   1% /usr/share/oem
/dev/xvdb      ext4       99G   22G   72G  24% /var/lib/docker
/dev/xvdc      ext4      158G  1.3G  149G   1% /opt/data
```
```
core@ip-10-42-2-93 /var/lib/docker/overlay $ docker info
Containers: 7
Images: 794
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.18.6
Operating System: CoreOS 607.0.0
CPUs: 2
Total Memory: 7.309 GiB
Name: ip-10-42-2-93.us-west-2.compute.internal
ID: UZW4:PCTF:C3KH:AZ62:3E4D:RBLN:66ZT:PTBQ:BNC2:7W2V:U4DZ:RGWR
```
```
core@ip-10-42-2-93 /var/lib/docker/overlay $ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef-dirty
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef-dirty
```

**Comment by lamielle** [comment] 2015-04-14 23:22
@xueshanf if you created this additional 100GB partition yourself, what parameters did you use when formatting the filesystem?  There was a fix in CoreOS 591.0.0 which tweaked the formatting parameters to tune for high numbers of small files (vs. fewer but larger files).  The workload for a volume that stores a registry is certainly the former.  I would suggest looking into the filesystem parameters of your /dev/xvdb partition.

**Comment by xueshanf** [comment] 2015-04-14 23:33
I build the file system with the following unit. I will look for the inode tuning tweak you mentioned. If you happen to have the reference, please post? 
```
[Unit]
Description=Formats the disk drive
[Service]
Type=oneshot
RemainAfterExit=yes
Environment="LABEL=var-lib-docker"
Environment="DEV=/dev/xvdb"
ExecStart=-/bin/bash -c "wipefs -a -f $DEV && mkfs.ext4 -F -L $LABEL $DEV && echo wiped"
```

**Comment by xueshanf** [comment] 2015-04-15 00:26
@lamielle I found the issue https://github.com/coreos/bugs/issues/264. Looks like I should use 4096 inode ration (mkfs.ext4 -T news) to increase inode size from current 6.5 million to 24million on the 100GB volume.

**Comment by lamielle** [comment] 2015-04-15 01:01
@xueshanf Yes!  That was what I was remembering.  Glad you found it.  Hope it helps!

**Comment by xueshanf** [comment] 2015-04-15 01:08
@lamielle Yup! I am up to 25 million inodes now.

**Comment by bitliner** [comment] 2015-04-15 15:04
@dmp42 yes, I think it is node exhaustation

![image](https://cloud.githubusercontent.com/assets/1301838/7161763/2047310c-e391-11e4-9c38-bbe952592c3c.png)

May you remember me how to change the location docker uses to store data?
I'll change that folder moving it to a bigger partition, given that other workarounds do not look to exist...

**Comment by xiaods** [comment] 2015-05-05 16:51
I am feel this issue can close.

**Comment by xueshanf** [comment] 2015-05-05 17:32
@xiaods yes please. thank you!

**Comment by MitchK** [comment] 2015-06-08 12:48
Is the inode issue something that can be changed or is this wanted behaviour? What is the best strategy to tackle this? Bigger partition? Can those inodes be removed?

**Comment by zenwanger** [comment] 2015-06-11 16:41
I have run into a similar error "INFO[0718] Untar exit status 1 write /tools.lnx86/psui/viplib/14.20/cdn_psif_top_fli.h.esv: no space left on device".  Any recommendation appreciated.

**[root@vlsj-djap1 docker]# df -i**

    /dev/mapper/docker-docker_lv
    Filesystem 	Inodes 	IUsed 	IFree 	IUse% 	Mounted on
    			9830400 77100 	9753300 1% 		/docker

[root@vlsj-djap1 docker]# df -i
/dev/mapper/docker-docker_lv
Filesystem               Inodes      IUsed      IFree IUse% Mounted on
                        9830400      77100    9753300    1% /docker 

**[root@vlsj-djap1 docker]# docker -D info**

    Containers: 2
    Images: 46
    Storage Driver: devicemapper
     Pool Name: docker-253:1-1966081-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: extfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 11.93 GB
     Data Space Total: 107.4 GB
     Data Space Available: 95.45 GB
     Metadata Space Used: 8.253 MB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.139 GB
     Udev Sync Supported: false
     Data loop file: /docker/devicemapper/devicemapper/data
     Metadata loop file: /docker/devicemapper/devicemapper/metadata
     Library Version: 1.02.82-git (2013-10-04)
    Execution Driver: native-0.2
    Kernel Version: 2.6.32-504.16.2.el6.x86_64
    Operating System: <unknown>
    CPUs: 1
    Total Memory: 3.743 GiB
    Name: vlsj-djap1
    ID: 4Y6P:2CKS:PQA2:ZKUI:MUEL:XOVS:7DCT:TXKB:HSW5:IMSH:45KD:OGQK
    Debug mode (server): false
    Debug mode (client): true
    Fds: 71
    Goroutines: 58
    System Time: Thu Jun 11 08:36:31 PDT 2015
    EventsListeners: 0
    Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
    Init Path: /usr/local/bin/docker
    Docker Root Dir: /docker


**[root@vlsj-djap1 Markdown_1.0.1]# docker -D images**

    REPOSITORY				TAG    IMAGE 			IDCREATED 		VIRTUAL SIZE
    <none>					<none>  0a655f60fd39	59 minutes ago  5.535 GB
    vd:5000/sa				latest  aa8544f6dbfe	42 hours ago	5.535 GB
    ubuntu  				latest  fa81ed084842	10 days ago 	188.3 MB
    vd:5000/ubuntu-local	latest  fa81ed084842	10 days ago 	188.3 MB
    registry				2.0 	b39a445085a6	2 weeks ago 	548.6 MB
    centos  				latest  fd44297e2ddb	7 weeks ago 	215.7 MB

**[root@vlsj-djap1 Markdown_1.0.1]# docker -D ps -a**

    CONTAINER ID	IMAGE 																	COMMAND				CREATED 				STATUS  PORTSNAMES
    eef5931f1355	0a655f60fd39b931f16fea293730c6529b50111080a8c41067ee355f220a365e:latest	"/bin/sh -c '#(nop)	About an hour ago				serene_bartik   
    1d84604438cf	registry:2.0  															"registry cmd/regist	5 days ago	Up 5 days   0.0.0.0:5000->5000/tcp   elated_perlman

**Comment by dmp42** [comment] 2015-06-11 17:53
@zenwanger 

Your kernel is very old (2.6.32).
I'm not sure what docker version you are running here, but it's likely unsupported, and I would advise you try upgrading.

**Comment by zenwanger** [comment] 2015-06-11 18:33
@dmp42 Thanks.  Will update to the latest.

**Comment by liquid-sky** [comment] 2015-07-08 18:01
Running latest Docker with one of the latest kernels and the inodes are consumed non-proportionally: 

Started to happen when I switched to OverlayFS.  

```
$ docker -v
Docker version 1.7.0, build 0baf609

$ uname -svr
Linux 3.19.0-21-generic #21~14.04.1-Ubuntu SMP Sun Jun 14 18:45:42 UTC 2015

$ df -h /mnt
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdb        30G  1.5G   27G   6% /mnt

$ df -i /mnt
Filesystem      Inodes  IUsed   IFree IUse% Mounted on
/dev/xvdb      1966080 308612 1657468   16% /mnt
```

**Comment by cpuguy83** [comment] 2015-07-08 19:39
@liquid-sky This is a known issue with overlay.

**Comment by whosthatknocking** [comment] 2015-07-17 05:43
In [overlay](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt) every directory gets duplicated increasing inode usage. In ext4 it's possible to optimize number of available inodes by reducing block size. If your default block size is 4K, you can try changing it to 2048 (double) or even 1024. You can also explore XFS or Btrfs filesystems that manage inodes differently.

**Comment by stevenschlansker** [comment] 2015-08-14 16:12
This may well be worth calling out prominently in the documentation, perhaps a "preparing to go to production" section or the like.  We just ran into this issue, even with 10M inodes our disks are inching towards 100% inode usage.  And since we built all our clusters unaware of this problem, we may end up having to rebuild every machine because the inode density can only be set at filesystem creation time...

**Comment by xiaods** [comment] 2015-09-12 14:28
@stevenschlansker  agree, we should be put some advice on documentation when user want to migrate fs to overlayfs. this is know issue.

**Comment by whosthatknocking** [comment] 2015-09-16 04:16
It's worth mentioning that overlay write performance inside of the container is slower. Any heavy writes should generally be done to a volume. Shortly, I would recommend one partition for docker overlay and separate one optimized for your application data.

**Comment by alex-dr** [comment] 2015-09-24 16:20
My team recently ran into a similar issue; a NodeJS with express.js and some other npm packages which contains ~100k files and creates, in a volume (inside `/var/lib/docker/volumes`), an additional ~100k files at runtime.

After updating the container a number of times we ran into this same issue; no space left on device during pull despite free space on disk. We discovered that we essentially had an inode leak; each container run would create many files in `/var/lib/docker/volumes` and they would never get cleaned up since Docker (or Ansible's docker module) doesn't clean up volumes automatically.

We have implemented a workaround by running https://github.com/chadoe/docker-cleanup-volumes after every container update and are looking into the root cause of lots of files since it impacts startup performance.

So if you are running into this, it might not have to do with your CoW filesystem backend of choice or how many inodes you have available. Make sure you are not writing many files to a volume and that your inode usage is constant as you update your image and re-run the container.

**Comment by lvarayut** [comment] 2015-11-07 04:33
I'm having the same issue. Is there any way to increase the volume of a VM?

**Comment by armicron** [comment] 2015-12-07 08:57
I can't pull `shippable/minv2` image.
```diff
-Error pulling image (latest) from docker.io/shippable/minv2, ApplyLayer exit status 1 stdout:  stderr: write /home/shippable/.gvm/gos/go1.2/src/pkg/go/scanner/scanner.go: no space left on device
```
```
$ docker -v
Docker version 1.9.1, build a34a1d5

$ uname -sr
Linux 4.1.12-gentoo

DOCKER_OPTS="-g /mnt/wd500_files/"
$ df -i  /mnt/wd500_files/
Filesystem       Inodes   IUsed    IFree IUse% Mounted on
/dev/sda2      15269888    3557 15266331    1% /mnt/wd500_files

$ df -h /mnt/wd500_files/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       230G   55G  163G  26% /mnt/wd500_files
```

**Comment by SamVerschueren** [comment] 2016-02-24 08:36
Had the same issue. Over 90% of my inodes where in use, couldn't even pull an image anymore. After running the following shell script, inode usage dropped to 7$%.

```sh
# remove stopped containers
docker rm $(docker ps -a -q)

# remove dangling images
docker rmi $(docker images -q --filter "dangling=true")
```

It removes not running containers first (remove if you don't want that). And afterwards, and removes all the dangling images which actually was the major factor in the inode usage drop.

**Comment by quinncomendant** [comment] 2016-03-01 18:16
I'm running CoreOS via [corectl](https://github.com/TheNewNormal/corectl) using its *[simple usage recipe](https://github.com/TheNewNormal/corectl/blob/golang/README.md#simple-usage-recipe-a-docker-and-rkt-playground)* setup instructions. I've taken the [suggestion](https://github.com/docker/docker/issues/10613#issuecomment-122182216) by @whosthatknocking and created a new disk image with 1024 byte blocks. The result is 16x more inodes. In case it's helpful to anyone, here's the command I used to format the disk image:

    mke2fs -b 1024 -i 1024 -t ext4 -m 0 -F ~/var_lib_docker.img

(I've [suggested](https://github.com/TheNewNormal/corectl/issues/68) this change in the instructions for the corectl project.)

**Comment by elabrc** [comment] 2016-03-23 20:44
Same issue here. @SamVerschueren 's suggestion regarding removing stopped containers/dangling images only gained about 8%. Not on coreos - just plain EC2 image (Amazon Linux 4.1.17-22.30.amzn1.x86_64) using ext4.

This is a CI/CD server that does a lot of builds.

```
docker info
Containers: 0
Images: 979
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.17-22.30.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.09
CPUs: 2
Total Memory: 3.862 GiB
```

Before:
```
df -i
Filesystem       Inodes    IUsed  IFree IUse% Mounted on
/dev/xvda1     14024704 14007626  17078  100% /
```

After:
```
df -i
Filesystem       Inodes    IUsed   IFree IUse% Mounted on
/dev/xvda1     14024704 12897618 1127086   92% /
```

rm -rf /var/lib/docker was basically the only way to fix. Took hours.

**Comment by xiaods** [comment] 2016-03-24 10:41
Pain.

**Comment by masonnl** [comment] 2016-03-31 16:03
If you're like me and have very few containers, @SamVerschueren solution might help. I am running OSX 10.11.3 with Docker version 1.9.1, build a34a1d5. Just by removing the dangling images I was able to build new containers without getting the 'no storage left on device' error. It would be helpful if Docker would clean up after itself, but I don't really understand the full scope of this issue so maybe I am wrong to wish that.

**Comment by KrishnaPG** [comment] 2016-05-05 14:07
New to docker and just trying to pull a new image (which is apparently large) and it failed with ` no space left on device` in the end.

The default VMDK size is around 19GB now. The question I have is:

Is it possible to create a new docker machine clean (instead of forcing it onto default machine, which seems ot be out of space) and avoid this problem?

How to specify docker (while pulling) to use a different machine (a brand new one) instead of default one?

**Comment by saada** [comment] 2016-08-29 15:19
Still a pain in Docker 1.12.
Shocked this is still an open issue.

**Comment by cpuguy83** [comment] 2016-08-29 15:22
@saada Can you explain what the pain is?

**Comment by dmcgowan** [comment] 2016-08-29 17:36
@saada we added `overlay2` to address this issue. The existing `overlay` driver cannot be updated to fix the inode overuse issue and maintain backwards compatibility since it was not designed to use the newer kernel feature for multiple lower directories. My preference is to keep this issue open until we are confident `overlay2` is a stable alternative to `overlay`.

**Comment by saada** [comment] 2016-08-30 00:59
@cpuguy83 @dmcgowan I know you guys are doing your best. Thanks for the effort. Looking forward for `overlay2` to solve resolve this issue.

**Comment by zagorulkinde** [comment] 2016-09-11 17:14
Same issue here.

Mac os 10.11.6

```
docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true

docker info 

Containers: 57
 Running: 3
 Paused: 0
 Stopped: 54
Images: 21
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 237
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.19-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.953 GiB
Name: moby
ID: ZJSN:HTDT:TZZM:5ZAO:VCNI:J6GS:LD5A:QXJ5:54WO:22PD:WY4M:ZM4G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 35
 Goroutines: 66
 System Time: 2016-09-11T17:14:01.448934038Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Comment by mbentley** [comment] 2016-09-11 19:03
@zagorulkinde - looks like you are running Docker for Mac. The VM is out of space.  There might be some useful suggestions here: https://forums.docker.com/t/consistently-out-of-disk-space-in-docker-beta/9438/9

**Comment by justincormack** [comment] 2016-09-19 21:57
`overlay2` seems fine for me, and would recommend anyone using `overlay` upgrades at this point if they are seeing this issue and they are using a recent kernel.

**Comment by whosthatknocking** [comment] 2016-09-21 17:39
Please keep in mind it's compatibility issues; Overlay doesn't fully implement the posix standards potentially impacting your application (`rename` system call) or platform (`open` system call, `yum install` on RH like systems).

**Comment by justincormack** [comment] 2016-09-24 16:44
@whosthatknocking `overlay` and `overlay2` are the same with respect to Posix. The issue here is inode exhaustion, which os only a problem with `overlay`. 

The fixes are
1. Use `overlay2` if you have a recent kernel that supports it. (4.x)
2. reformat the drive you are using if you use an old kernel to have more inodes.

I am going to close this issue as `overlay2` should be as stable as `overlay` now; feel free to continue to comment if there are still issues, or open a new issue if you have specific problems using `overlay2.

**Closed by justincormack** 2016-09-24 16:44 UTC
Labels: area/distribution, area/storage/overlay

**Comment by Paxxi** [comment] 2017-02-14 14:01
How come overlay2 is not the default when setting up docker 1.12/1.13? (ubuntu 16.04 on digitalocean droplet with docker from official ppa)

We recently set up a swarm cluster and it's seen light usage in dev/test for about 2 months and today we hit this issue on one of 3 nodes, the others are at 95% and 78% inode usage.

**Comment by antonin07130** [comment] 2017-02-24 18:33
+1 without overlay

**Comment by thaJeztah** [comment] 2017-02-24 19:52
docker uses a priority list, that automatically selects the first driver that is supported to get you going. The overlay2 and overlay drivers were given a higher priority in docker 1.13; https://github.com/docker/docker/pull/27932/files#diff-8517a02806afb5571ad3c11a52e431e6R55

If your machine supports aufs, that's used, if not, and your kernel supports it, overlay2, overlay or devicemapper is used

I suspect aufs is installed on the 16.04 machine, so it's selected, but you can configure the daemon to use a different driver using a daemon.json configuration file

**Comment by hgontijo** [comment] 2017-03-17 22:54
@thaJeztah et al, I followed all the steps to setup [direct-lvm](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production) and I'm still getting the _no space left on device_ even though there's enough space on the root/docker volumes and metadata/data.
Whenever I tried with overlay2 and everything running under root volume (no extra device), it worked fine.

The docker image size is 10 GiB. 

I appreciate if you can provide any clue on this issue.

### Issue
```
$ docker pull <image from ecr>
...
f0d0216c7ba3: Pull complete
73451a479100: Extracting [==================================================>] 741.1 MB/741.1 MB
80cf804cccf0: Download complete
344c7bbe11c9: Download complete
469d40f6eebd: Download complete
656132e1351f: Download complete
ef660b25f676: Download complete
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/oracle/oradata/EMERUNI/datafile/o1_mf_undotbs1_cztx6v2z_.dbf: no space left on device
```

### Environment
```

$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 14.76 GB
 Data Space Total: 102 GB
 Data Space Available: 87.24 GB
 Metadata Space Used: 1.958 MB
 Metadata Space Total: 1.07 GB
 Metadata Space Available: 1.068 GB
 Thin Pool Minimum Free Space: 10.2 GB
  Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.4.41-36.55.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.09
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: ip-10-60-1-188
ID: Q6O7:J7QA:AT2F:PA32:RCQO:HWPN:6T7A:CVEX:TEUJ:Z3D2:WGDW:CYFP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

$ df -i
Filesystem  Inodes IUsed   IFree IUse% Mounted on
devtmpfs       4116180   564 4115616    1% /dev
tmpfs          4118899     1 4118898    1% /dev/shm
/dev/xvda1     3276800 42235 3234565    2% /

$ df -h
Filesystem  Size  Used Avail Use% Mounted on
devtmpfs         16G  112K   16G   1% /dev
tmpfs            16G     0   16G   0% /dev/shm
/dev/xvda1   50G  2.8G   47G   6% /

lsblk --output NAME,TYPE,SIZE,FSTYPE,MOUNTPOINT,LABEL
NAME                    TYPE  SIZE FSTYPE      MOUNTPOINT LABEL
xvda                    disk   50G
└─xvda1                 part   50G ext4        /          /
xvdb                    disk  100G LVM2_member
├─docker-thinpool_tmeta lvm  1020M
│ └─docker-thinpool     lvm    95G
└─docker-thinpool_tdata lvm    95G
  └─docker-thinpool     lvm    95G
```

**Comment by whosthatknocking** [comment] 2017-03-17 23:35
@hgontijo Perhaps check xvdb not xvda1?

**Comment by mbentley** [comment] 2017-03-18 01:00
Check the `dm.basesize` option: https://docs.docker.com/engine/reference/commandline/dockerd/#storage-driver-options. The default is 10GB which is probably why you're hitting it while extracting your image that is 10GB.

**Comment by hgontijo** [comment] 2017-03-18 02:21
@mbentley super, it worked! Just for reference, here's how my Docker daemon looks like:

`
OPTIONS="--default-ulimit nofile=1024:4096 -H tcp://0.0.0.0:4243 -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --storage-driver=devicemapper --storage-opt=dm.thinpooldev=/dev/mapper/docker-thinpool --storage-opt=dm.use_deferred_removal=true --storage-opt=dm.use_deferred_deletion=true --storage-opt dm.basesize=50G"
`

**Comment by sivabudh** [comment] 2017-03-31 06:48
Just execute this command:
```
docker images --no-trunc | grep '<none>' | awk '{ print $3 }' | xargs -r docker rmi
```

**Comment by RajdeepSardar** [comment] 2017-08-23 06:25
We faced similar problem but Inode % seems fine (43% used). DiskSpace is used about 81%. It is pulling a docker image about 1.7 GB. Seems still about 2GB space would have left. But following error was found


```
+ /usr/local/bin/docker version
Client:
 Version:      17.05.0-ce

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5

+ /usr/local/bin/docker build --rm=true -f Dockerfile -t $VALUE . --pull=true
Sending build context to Docker daemon  1.677GB
.........
ee804876babe: Pull complete
225c66a863d8: Pull complete
2df5bb5034a3: Pull complete
96acbc28c73d: Pull complete
write /var/lib/docker/tmp/GetImageBlob194874586: no space left on device

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G   12K  3.9G   1% /dev
tmpfs           799M  520K  798M   1% /run
/dev/vda1        20G   16G  3.8G  81% /

$ df -i
Filesystem      Inodes  IUsed   IFree IUse% Mounted on
udev           1018557    415 1018142    1% /dev
tmpfs          1022081   1346 1020735    1% /run
/dev/vda1      1310720 523561  787159   40% /

```

**Comment by cpuguy83** [comment] 2017-08-23 15:27
@RajdeepSardar `no space left on device` comes directly from the kernel.
Note that you are both pulling an image and sending a massive build context.

**Comment by orodbhen** [comment] 2018-03-22 19:48
@mbentley and @hgontijo Note that changing `dm.basesize` won't work if the image already has layers cached on the system from before. You'll first need to prune all the existing layers, which may require removing some containers.

**Comment by jcheroske** [comment] 2018-12-01 03:45
Building off of @sivabudh's answer, I came up with this on my Mac development machine. It whacked all the downloaded images and got me back to work:
```
docker images --no-trunc |  awk '{ print $3 }' | xargs docker rmi --force
```

**Comment by ManjuShankar95** [comment] 2019-01-29 13:08
Finally, What is the solution for this?

**Comment by thaJeztah** [comment] 2019-01-29 13:16
@ManjuShankar95 not sure what you mean; the error is printed if the machine is out of disk space, so the solution is to make space on the machine (e.g., using `docker system prune` to remove images and containers that are no longer used)

**Comment by tapanbanker** [comment] 2019-11-11 04:58
The error is because of the mount volume , Execut efollowing commands 

``` 
df -h
```
In the docker check the overlay mount directory 
Filesystem                        Size  Used Avail Use% Mounted on
devtmpfs                          3.7G     0  3.7G   0% /dev
tmpfs                             3.7G   16K  3.7G   1% /dev/shm
tmpfs                             3.7G   33M  3.7G   1% /run
tmpfs                             3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/mapper/VolGroup00-rootVol     10G  2.3G  7.8G  23% /
/dev/nvme0n1p1                   1014M  334M  681M  33% /boot
/dev/mapper/VolGroup00-homeVol    3.0G   33M  3.0G   2% /home
/dev/mapper/VolGroup00-varVol     4.0G  3.5G  588M  86% /var
/dev/mapper/VolGroup00-tmpVol     2.0G   58M  2.0G   3% /tmp
/dev/mapper/VolGroup00-logVol     4.0G   36M  4.0G   1% /var/log
/dev/mapper/VolGroup00-auditVol   4.0G   98M  3.9G   3% /var/log/audit
/dev/mapper/VolGroup00-vartmpVol  2.0G   33M  2.0G   2% /var/tmp
tmpfs                             753M     0  753M   0% /run/user/1000
overlay                           4.0G  3.5G  588M  86% /var/lib/docker/overlay2/82b544ac4a868c7f3c0180c4751e73084f64785c379362bf0fcf6c07f36cb36e/merged
tmpfs                             753M     0  753M   0% /run/user/0

The answer is posted by Tapan Nayan Banker | Tapan Banker [www.tapanbanker.com](url)

**Comment by 1wpro2** [comment] 2019-12-06 06:21
I have just encountered the same issue. Having increased the disk size allocation sorted it out.
