### ISSUE TITLE
nginx cannot save file to mounted wordpress directory

### ISSUE THREAD

**Issue by projectxmaker** [docker/docker#18045] opened 2015-11-17 19:41 UTC
Hi everyone,

I spent a few days on following issue but cannot figure out the solution, plz give me some guides to settle it :(

#### Environment ####
```html
docker version: Docker version 1.9.0, build 76d6bc9

docker info: 
Containers: 2
Images: 27
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 31
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: WYKL:KPEW:G5HY:YOQ4:4555:YU33:UJBP:4YOB:RWFK:HQNL:OLLG:BVJD
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 38
 System Time: 2015-11-18T04:05:07.548898935Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

uname -a:
Darwin My-MacBook 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

#### Issue ####
1 "db" container for mysql
1 "web" container for nginx + php + /var/www/html/webapp is mounted to wordpress directory on host (/Users/www/wordpress)

Wordpress is installed normally, everything works fine (creating file from console of "web" container and save it to /var/www/html/webapp, check and find that that file exists on host too) but media upload feature of wordpress doesn't work, media files cannot be saved to /wp-content/uploads folder.

so I guessed that something wrong with permission on /var/www/html/webapp/wp-content/uploads, it could relate to www-data, then...

I checked /var/www/html/webapp on "web" container, found that owner of webapp directory is 1000 and group-owner is staff.

I tried to add www-data to staff group, but it doesn't work.

I tried to do "RUN chown -R www-data:www-data /var/www/html/webapp" in Dockerfile of "web" container but it also gives no effect because no change on owner of target folder is applied, it still is 1000:staff.

#### Expected ####
Media Upload feature of Wordpress works properly - Can save file to /var/www/html/webapp/wp-content/uploads folder

any help is much appreciated :(

regards,

**Comment by thaJeztah** [comment] 2015-11-26 21:39
This is a duplicate of https://github.com/boot2docker/boot2docker/issues/581 and a limitation of the way directories on the host (OS X) are shared with the boot2docker Virtual Machine using VirtualBox Sharing. Unfortunately there's no full solution for this currently, but the discussion on https://github.com/boot2docker/boot2docker/issues/581 contains a lot of workarounds / alternative approaches that may be helpful.

I'm going to close this issue here, and suggest to subscribe to https://github.com/boot2docker/boot2docker/issues/581 to follow progress.

Thanks for reporting, and I hope the linked issue helps you find a suitable workaround for your use case

**Closed by thaJeztah** 2015-11-26 21:39 UTC
