### ISSUE TITLE
I/O performance issues with extra process

### ISSUE THREAD

**Issue by robertoaloi** [docker/docker#13985] opened 2015-06-17 09:53 UTC
Given the following minimal Dockerfile, which installs the _erlang_ package on a centos6:

    FROM centos:centos6
    RUN yum update -y && \
        yum install -y https://www.rabbitmq.com/releases/erlang/erlang-17.4-1.el6.x86_64.rpm

There's a substantial difference in performance if I execute a "I/O heavy" operation from the process specified as the Docker "command" or via an extra process.

    (Docker 1.6.2)
    sudo docker build -t test .
 
    # The following is fast ~1s
    sudo docker run -it test erl
    {T, V} = timer:tc(os, cmd, ["grep -ir test /usr"]), T.
 
    # The following is slow ~10s
    sudo docker run -it test bash
    erl
    {T, V} = timer:tc(os, cmd, ["grep -ir test /usr"]), T.
 
Is this expected? I'm running Docker 1.6.2.

To make things more interesting, "sh" doesn't seem to suffer the same issue:

    # The following is fast ~1s
    sudo docker run -it test sh
    erl
    {T, V} = timer:tc(os, cmd, ["grep -ir test /usr"]), T.

Reference: https://gist.github.com/robertoaloi/9bb95c620803baef2d7f

**Comment by unclejack** [comment] 2015-06-18 15:25
@robertoaloi Can you please get rid of erlang from the example and try to reproduce without erlang? That would let us know if this is a problem caused by erlang on that system or if it's something else.

**Comment by robertoaloi** [comment] 2015-06-18 21:38
@unclejack It seems you get the same effect with the following:

````
# Takes ~0.6s
docker run -it centos:centos6 sh -c "time grep -ir test /usr > /tmp/foo"

# Takes ~6s
docker run -it centos:centos6 sh -c "bash"
[root@955e21cdb6a8 /]# time grep -ir test /usr > /tmp/foo
````

**Comment by dqminh** [comment] 2015-06-19 08:50
I think the problem is specifically with bash, not with number of processes, as running `sh` as the shell instead of bash is fast. Maybe bash has a different (slower?) implementation of pipe to a file ?

```
docker run -it centos:centos6 sh -c "sh"
sh-4.1# time grep -ir test /usr > /tmp/foo
```

**Comment by robertoaloi** [comment] 2015-06-19 09:28
You get the same performance degradation even if you exclude the "pipe to file" part. I only included that to reduce the output.

**Comment by unclejack** [comment] 2015-06-19 10:56
This is somehow related to CentOS and the bash version it's using. `docker run -it centos:centos6 sh -c "sh"` doesn't have this problem. Ubuntu images don't have this problem either.

I'm going to close this issue since it seems to be specific to the centos6 image.

ping @jperrin

**Closed by unclejack** 2015-06-19 10:56 UTC

**Comment by robertoaloi** [comment] 2015-06-22 10:50
@unclejack I believe you're right.
@jperrin I created a new issue about this: https://github.com/docker-library/official-images/issues/841 Do you think you could help?

**Comment by jperrin** [comment] 2015-06-22 13:14
If I can figure out why, and it's related to the build of the container, then yes. If it's something code related in centos6 itself, then it would need to be addressed upstream and we'd inherit the fix. I'm at DockerCon currently, so please ping me about it thursday to make sure I haven't forgotten about it.
