### ISSUE TITLE
could not change soft link from /lib to /usr/lib

### ISSUE THREAD

**Issue by yanxiaoliang** [docker/docker#31372] opened 2017-02-27 03:43 UTC
**Description**
I pulled a image from debian:sid, and try to install xfslib-dev, then found, apt gonna install a same file both in /lib and /usr/lib, then I found docker image linked /lib -> /usr/lib, does anyone know how to separate these two folder in docker image? Thanks.

**Steps to reproduce the issue:**
1. docker pull debian:sid
2. apt-get install xfslibs-dev

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment] 2017-02-27 04:15
Since sid is unstable, I suggest using `debian:jessie` instead.

If you need to use sid,  I suggest reporting this issue to the maintainer of the corresponding package of Debian.

A workaround will be as follows, but NOT recommended:
```console
$ apt-get install busybox-static
$ rm /lib
$ busybox cp -r /usr/lib /lib
```

Since this is not an issue of Docker, I suggest closing this issue

**Comment by thaJeztah** [comment] 2017-02-27 10:54
Agreed, this does not look like an issue related to _docker_ itself. Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-02-27 10:54 UTC
Labels: kind/question
