### ISSUE TITLE
'BTRFS_BUILD_VERSION' undeclared (first use in this function) -- btrfs-progs 3.19

### ISSUE THREAD

**Issue by prologic** [docker/docker#11487] opened 2015-03-19 01:41 UTC
Docker 1.5.0 no longer builds successfully against ``btrfs-progs 3.19``.

See build log:

```#!bash
=======> Building '/usr/ports/pkg/docker#1.5.0-5.pkg.tar.xz'.
cp /usr/ports/src/check-config.sh /usr/ports/work/docker/src
bsdtar -p -o -C /usr/ports/work/docker/src -xf /usr/ports/src/v1.5.0.tar.gz
cp docker /usr/ports/work/docker/src
cp docker.conf /usr/ports/work/docker/src
+ build
+ cd docker-1.5.0
+ export AUTO_GOPATH=1
+ AUTO_GOPATH=1
+ export DOCKER_GITCOMMIT=a8a31eff10
+ DOCKER_GITCOMMIT=a8a31eff10
+ unset CC
+ unset CXX
+ ./hack/make.sh dynbinary
# WARNING! I don't seem to be running in the Docker container.
# The result of this command might be an incorrect build, and will not be
#   officially supported.
#
# Try this instead: make all
#

---> Making bundle: dynbinary (in bundles/1.5.0/dynbinary)
Created binary: /usr/ports/work/docker/src/docker-1.5.0/bundles/1.5.0/dynbinary/dockerinit-1.5.0
# github.com/docker/docker/daemon/graphdriver/btrfs
37: error: 'BTRFS_BUILD_VERSION' undeclared (first use in this function)
=======> ERROR: Building '/usr/ports/pkg/docker#1.5.0-5.pkg.tar.xz' failed.
```

``btrfs-progs 3.18.2`` shipped with ``/usr/include/btrfs/version.h`` which contains:

```#!bash
$ grin BTRFS_BUILD_VERSION /usr/include/btrfs/version.h 
/usr/include/btrfs/version.h:
   14 : #define BTRFS_BUILD_VERSION "Btrfs v3.18.2"
```

Do we have a solution to this in master yet?

**Comment by prologic** [comment] 2015-03-19 01:42
ping @tianon I suspect Gentoo might have similar issues?

**Comment by tianon** [comment] 2015-03-19 01:45
This is a dupe of #11417. :wink:

**Closed by tianon** 2015-03-19 01:45 UTC

**Comment by prologic** [comment] 2015-03-19 01:47
Damnit I even searched before posting too :) *sigh* Thanks @tianon
