### ISSUE TITLE
docker load issue

### ISSUE THREAD

**Issue by arpanchaudhury** [docker/docker#25049] opened 2016-07-26 07:23 UTC
Hi,

I am trying to run the following command `docker load < project.tar` which gives me `invalid input` error.

```
[arpanch@hp-xplanner-1 ~]$ uname -a
Linux hp-xplanner-1 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
[arpanch@hp-xplanner-1 ~]$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

```
[arpanch@hp-xplanner-1 ~]$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:3-67114679-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 568.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 10.34 GB
 Metadata Space Used: 1.311 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.699 GiB
Name: hp-xplanner-1
ID: 56OZ:ZQZ3:ZHWZ:64XB:ZWX2:XBGF:3PXX:HRXR:44RY:RVNA:6ETE:TDYR
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by thaJeztah** [comment] 2016-07-26 10:22
How did you create the `project.tar` ? Can you provide steps to reproduce, otherwise there's not enough information to investigate this issue.

**Comment by thaJeztah** [comment] 2016-08-03 13:57
closing because more info is needed

**Closed by thaJeztah** 2016-08-03 13:57 UTC
Labels: status/more-info-needed, version/1.11
