### ISSUE TITLE
[libnetwork] libnetwork uses the default graph directory although another is graph is specified

### ISSUE THREAD

**Issue by luxas** [docker/docker#21156] opened 2016-03-12 16:20 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   590d5108-unsupported
 Built:        Fri Feb 12 16:35:07 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   590d5108-unsupported
 Built:        Fri Feb 12 16:35:07 2016
 OS/Arch:      linux/arm
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host
Kernel Version: 4.1.19-4-ARCH
Operating System: Arch Linux ARM
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 922.7 MiB
Name: pi4
ID: L7QR:ZUIR:K4HQ:QHIM:YFQT:BBUH:KQSY:4LJW:IWNX:E47G:4ZFC:KGT5
```

**Steps to reproduce the issue: (on amd64)**
```console
$ docker daemon -H unix:///var/run/system-docker.sock -s overlay --exec-opt native.cgroupdriver=cgroupfs -p /var/run/system-docker.pid --iptables=false --ip-masq=false --bridge=none --graph=/var/lib/system-docker
$ docker -H unix:///var/run/system-docker.sock run -d --net=host --privileged -v /dev/net:/dev/net quay.io/coreos/flannel:0.5.5
$ netstat -nlp | grep /var/lib/docker
unix  2      [ ACC ]     STREAM     LISTENING     2251937  27851/docker        /var/lib/docker/network/files/3f2cd329663e9b17f28168c1f0f6541d7684fb380224d26719e989c547b57986.sock
$ ps aux | grep 27851
root     27851  0.4  0.2 449324 43472 pts/12   Sl+  18:08   0:01 /usr/bin/docker daemon -H unix:///var/run/system-docker.sock -s overlay --exec-opt native.cgroupdriver=cgroupfs -p /var/run/system-docker.pid --iptables=false --ip-masq=false --bridge=none --graph=/var/lib/system-docker
$ ls -l /var/lib/docker/network/files
...
$ rm -rf /var/lib/docker/network/files
$ ls -l /var/lib/docker/network/files
(recreated with 1.10, not with 1.9)
```

**Describe the results you received:**

The custom daemon uses another graph, but puts network-related things in the default place anyway.
Noticed this when I ran a system-docker and `flannel` was started in `system-docker`

This seems quite hard-coded: https://github.com/docker/libnetwork/blob/master/datastore/datastore.go#L119

**Describe the results you expected:**

I expected `system-docker` to store its files in its own graph dir, so I may spin up my main docker without problems. Now I get the error `Error initializing network controller: Error creating default \"bridge\" network: failed to allocate gateway (10.1.0.0): Address already in use` when I'm trying to use the same `--bip` as `flannel` has allocated in my main docker daemon. (But that may be another thing)

Is this intentional?

**Comment by thaJeztah** [comment] 2016-03-12 16:33
Thanks for reporting; this is a duplicate of https://github.com/docker/docker/issues/18508 (also see the discussion on https://github.com/docker/libnetwork/pull/742 and https://github.com/docker/libnetwork/issues/747).

I'll close this issue in favor of https://github.com/docker/docker/issues/18508, please continue the discussion over there :+1:

**Closed by thaJeztah** 2016-03-12 16:33 UTC

**Comment by luxas** [comment] 2016-03-12 16:54
Ah, there it was
Searched for `graph` but the issue only used `-g`, well now it's found :smile:

**Comment by thaJeztah** [comment] 2016-03-12 16:56
Yes, I happened to know how to find it; no worries, we have a huge amount of issues (opened and closed), so finding isn't always easy :smile:
