### ISSUE TITLE
"ip already allocated" for IPv6 address

### ISSUE THREAD

**Issue by farcaller** [docker/docker#10774] opened 2015-02-13 19:00 UTC
I'm running my containers with `--mac-address` to have a persistent IPv6 address. I've noticed that one of the containers failed to restart with an error:

`FATA[0000] Error response from daemon: Cannot start container 1f7029fde7d996630381a9d03ec9214211dfe7ad829a32da7309ec7605764d17: ip already allocated`

Obviously, no one else could be using that specific IPv6 address. Restarting the daemon did help but it's hardly can be a workaround.

I'm running docker with `--fixed-cidr-v6` having /80 prefix.

**Comment by LK4D4** [comment] 2015-02-13 19:03
@farcaller Could you provide please exact commands for running daemon and container?

**Comment by farcaller** [comment] 2015-02-13 19:33
Daemon:
`/usr/bin/docker -d --insecure-registry registry:5000 --ipv6 --fixed-cidr-v6="PREFIX:2000::/80"`

Container:
```exec docker run -i --rm --name nginx --mac-address "02:42:ac:11:ff:01" --hostname "`hostname`-nginx" --volumes-from data.nginx -p 80:80 -p 443:443 registry:5000/nginx```

**Comment by LK4D4** [comment] 2015-02-13 19:47
@farcaller Thanks, I'll try to reproduce.

**Comment by friedrich** [comment] 2015-02-14 21:06
Same here running docker 1.5.0 on Fedora 21. Steps to reproduce:

`docker -d --ipv6 --fixed-cidr-v6=fc00::/64`

`A=$(docker run -di --mac-address="00:16:3e:00:00:01" debian:stable)`
`B=$(docker run -di --mac-address="00:16:3e:00:00:02" debian:stable)`
`docker restart $A`

**Comment by else** [comment] 2015-02-28 00:42
I can reproduce this as well.

**Comment by jfrazelle** [comment] 2015-02-28 01:28
ping @MalteJ

**Comment by else** [comment] 2015-03-10 19:54
When this happens, the to-be-created container also is not being removed despite `--rm=true`.

**Comment by LK4D4** [comment] 2015-03-16 22:05
It's superfun, because `A` on restarting releasing IP of `B` :) Tracking problem now

**Comment by DominicBoettger** [comment] 2015-07-06 23:36
Please fix this. Still an issue in 1.7.0.

**Comment by DominicBoettger** [comment] 2015-07-07 10:20
And why is this closed? In my opinion it must be possible to restart a container without restarting the whole Daemon.

**Comment by zargony** [comment] 2015-07-09 07:27
Same issue here. Docker version 1.7.0, build 0baf609

**Comment by mavenugo** [comment] 2015-07-09 09:25
@DominicBoettger it was automatically closed due to the fix https://github.com/LK4D4/docker/commit/491f8ab14493babb1c06e240c7a9de64f34827a0 . But 1.7.0 brought in networking overhaul via libnetwork. We have to check if the above patch made its way in its new form.
Will investigate and report in this issue.

**Comment by mavenugo** [comment] 2015-07-09 09:55
@DominicBoettger @zargony Yes. I see the issue in 1.7.0. We will fix this shortly.

**Comment by mavenugo** [comment] 2015-07-11 02:24
@calavera @DominicBoettger @zargony this issue is resolved in libnetwork. If we need this for 1.7.1, we can cherry-pick it in the bump branch. Please let us know.

**Comment by thaJeztah** [comment] 2015-07-11 13:57
@calavera @mavenugo I'll reopen this for now, feel free to close of you think that's incorrect

**Comment by mavenugo** [comment] 2015-07-19 02:48
@thaJeztah @DominicBoettger @zargony  this issue is resolved in docker master via https://github.com/docker/libnetwork/issues/371 and a recent vendor in process. Docker 1.8 release must include the fix.

**Comment by thaJeztah** [comment] 2015-07-19 11:28
Thanks for the ping @mavenugo 

This should be resolved by https://github.com/docker/docker/pull/14690, which contains the fix

**Closed by thaJeztah** 2015-07-19 11:28 UTC
Labels: exp/expert, system/networking

**Comment by JonasT** [comment] 2015-10-15 20:36
Is there any remedy for 1.7.1? Or are you just gonna let people sit it out until 1.8 is out? People are trying to run IPv6 in production environments.. why does everything related to IPv6 in docker always have to be horribly broken?? This is becoming really frustrating!
