### ISSUE TITLE
Is it safe that containers write log to the same file in shared volume

### ISSUE THREAD

**Issue by polym** [docker/docker#20652] opened 2016-02-24 13:22 UTC
Simple test is pass.

My Go app
```
package main

import (
	"fmt"
	"os"
)

func main() {
	fd, err := os.OpenFile("/tmp/log", os.O_WRONLY|os.O_APPEND, 0600)
	if err != nil {
		fmt.Println(err)
		return
	}

	defer fd.Close()

	id, err := os.Hostname()
	if err != nil {
		fmt.Println(err)
		return
	}
	for i := 0; i < 10000; i++ {
		fd.WriteString(fmt.Sprintf("%s-%d\n", id, i))
	}
}
```

Dockerfile

```
FROM golang:1.6

ADD test.go /root/test.go

WORKDIR /root/

EXPOSE 1001
CMD ["go", "run", "test.go"]
```

CMD

```
$ docker build -t test .
$ touch /tmp/log
$ for i in {1..10}; do docker run -d -v /tmp/:/tmp/ test& done
```

It seems safe?

**Comment by HackToday** [comment] 2016-02-24 13:49
it seems not concurrent write test

**Comment by thaJeztah** [comment] 2016-02-24 13:52
I don't think this is any different in docker as it is in other situations; docker doesn't change that; is it safe if multiple processes write to the same file? I think you may run into problems there.

Any reason you're not using the docker logging mechanisms, and write to stdout, so that you can use `docker logs` and/or logging plugins?

If you need to write to a file, perhaps use a dedicated volume for each container? 


Anyway this is a support question, and not a bug in docker, and the GitHub issue tracker is not meant for that (it is for reporting bugs and feature requests).

I'll close this issue, but feel free to continue the discussion here. In future, please consider either one of:

1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.
4) StackOverflow (https://stackoverflow.com)

1) and 2) should be better for longer conversations.

**Closed by thaJeztah** 2016-02-24 13:52 UTC

**Comment by polym** [comment] 2016-02-24 14:57
@thaJeztah  thank you
