### ISSUE TITLE
COPY still invalidates cache when no files have changed.

### ISSUE THREAD

**Issue by kojiromike** [docker/docker#21913] opened 2016-04-10 01:05 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Sat Mar 12 04:07:44 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 8
 Paused: 0
 Stopped: 3
Images: 94
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 149
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859 GiB
Name: boot2docker
ID: C3GY:3N5K:CDC5:KKPV:KGRB:EMTU:5L5X:VWJC:LBZE:NARH:DC4Y:KGDO
Debug mode (server): true
 File Descriptors: 80
 Goroutines: 107
 System Time: 2016-04-10T00:56:25.678982655Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=xhyve
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running with xhyve on a Mac

**Steps to reproduce the issue:**
1. Put a Dockerfile with a large number of build steps following a `COPY . /path` in a repo working dir. 
2. `docker build .`
3. Change only the `Dockerfile`
4. `docker build .` again.
5. Add `Dockerfile` to `.dockerignore`.
6. Repeat steps 3 and 4.

**Describe the results you received:**

In both steps 4 and 6 the build cache was invalidated after the COPY step.

**Describe the results you expected:**

The build cache should ignore changes to files in .dockerignore. The Dockerfile itself should never invalidate the build cache. If this is expected behavior, then searching for "Dockerfile COPY invalidates cache" should give me more clues than it does. (As in, I should be able to find documentation describing why the cache is being busted.)

**Additional information you deem important (e.g. issue happens only occasionally):**
Frankly, given #10336 and its related issues, all closed, I can only assume that this is something I don't understand. If that's the case, I would really appreciate seeing it documented so I understand what I can do in my Dockerfile to prevent changing _only_ the Dockerfile from invalidating the COPY cache.

**Comment by thaJeztah** [comment] 2016-04-11 11:09
Did you add the `.dockerignore` file to `.dockerignore` as well? I'm not able to reproduce this;

Contents of `.dockerignore`:

```
.dockerignore
Dockerfile
```

Contents of `Dockerfile`:

```Dockerfile
FROM alpine
COPY . /content/
COPY . /bla/
```

```
docker build -t foobar .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM alpine
latest: Pulling from library/alpine
420890c9e918: Pull complete
Digest: sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0
Status: Downloaded newer image for alpine:latest
 ---> d7a513a663c1
Step 2 : COPY . /content/
 ---> 49d85a8fb435
Removing intermediate container 7cd45417ae14
Step 3 : COPY . /bla/
 ---> c09e3edac95c
Removing intermediate container 2bd31dcb0c10
Successfully built c09e3edac95c
```

Updating `Dockerfile`, added a `RUN echo "foobar"`:

```
docker build -t foobar .
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM alpine
 ---> d7a513a663c1
Step 2 : COPY . /content/
 ---> Using cache
 ---> a82e4174d21a
Step 3 : COPY . /bla/
 ---> Using cache
 ---> 4f10c8314a30
Step 4 : RUN echo "foobar"
 ---> Running in f1b7996b95d7
foobar
 ---> e964aab759ff
Removing intermediate container f1b7996b95d7
Successfully built e964aab759ff
```

**Comment by kojiromike** [comment] 2016-04-11 13:53
Yes, my .dockerignore looks just like yours. What else could account for the difference? Did you try it from a Mac using xhyve? Do you have FDE on? (I do.) (I can't imagine how that would do it, but spitting in the dark.)

**Comment by deanrather** [comment] 2016-08-30 01:03
I suspect that unless you have `.git` in your `.dockerignore` file, trivial things like `git fetch` will cause the docker cache to invalidate.

Found this discussion attempting to find a way to see _which files_ caused the invalidation.
Any clues?

**Comment by thaJeztah** [comment] 2016-09-14 11:17
I'm closing this issue because we are not able to reproduce this issue, and it's most likely related to something changing in the context (like @deanrather mentions).

@deanrather no there's no feature in docker to check which files have changed, and implementing that would probably be difficult. Docker calculates a hash/checksum for the files that are sent, but does not keep track *which* files are changed.

**Closed by thaJeztah** 2016-09-14 11:17 UTC
Labels: area/builder, version/1.10
