### ISSUE TITLE
Docker 1.7.0 defaults to vfs storage driver on Ubuntu 14.04

### ISSUE THREAD

**Issue by Wattos** [docker/docker#14395] opened 2015-07-05 10:04 UTC
**Steps to reproduce**
1) Run the script at https://get.docker.io/ubuntu/
2) Execute docker info

**Expected behaviour**
Docker should use the same storage driver as 1.6.2 (on ubuntu that was vfs or devicemapper)

**Observed behaviour**
Docker uses vfs as the storage driver.

When I run docker info when installing docker 1.7 I get:
root@server-2:/var/lib/docker/vfs/dir# docker info
Containers: 6
Images: 29
**Storage Driver: vfs**
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: server-2
ID: ABVV:OCHL:KJ5Z:YKSO:TUGB:YDZZ:UIKF:XGKA:WGCN:HME5:SBUO:Q4Y2

After uninstalling docker 1.7.0 and installing docker 1.6.2 I get the following output:
root@server-2:~# sudo service docker start
docker start/running, process 4215
root@server-2:~# docker info
Containers: 0
Images: 0
**Storage Driver: devicemapper**
 Pool Name: docker-202:1-404460-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 15.75 GB
 Metadata Space Used: 733.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: server-2
ID: ABVV:OCHL:KJ5Z:YKSO:TUGB:YDZZ:UIKF:XGKA:WGCN:HME5:SBUO:Q4Y2

Since I did not freeze my docker dependencies, I got a surprise as docker ate up all the hdd space available on the machine

**Comment by thaJeztah** [comment] 2015-07-05 10:44
The script at https://get.docker.com/ubuntu will only perform a bare minimum install of Docker.

To perform a regular install (which will install AUFS on ubuntu), use https://get.docker.com/ (without the `/ubuntu/`);

    wget -qO- https://get.docker.com/ | sh

As described in the documentation; https://docs.docker.com/installation/ubuntulinux/

We are aware that some people run into this problem; See for additional discussion on this topic; https://github.com/docker/docker/issues/14232 and  https://github.com/docker/docker/pull/14343

**Comment by thaJeztah** [comment] 2015-07-05 10:50
I wonder though, how Docker decided to use vfs here; have you ran Docker using vfs in the past? If multiple "prior" storage drivers were detected, the default in 1.7 is to refuse to start and have the user manually provide the driver to use.

**Comment by cpuguy83** [comment] 2015-07-05 19:41
Hello, this is expected.
If your setup doesn't support any of the other drivers it will use vfs.
Devicemapper is no longer supported on installations that include a static docker binary (like as is provided via the get.docker.com repo).

There is talk of how to handle this more gracefully if the user was already using devicemapper before.
Today you have to set a flag to force the use of devicemapper... the idea being that you use that to migrate you stuff out as devicemapper is known to have many many issues when used with a static docker binary.

**Comment by Wattos** [comment] 2015-07-05 19:50
@cpuguy83 Why would docker not use aufs instead? What is the correct installation procedure to install docker without running into issues?

The instructions on https://docs.docker.com/installation/ubuntulinux/ seem to use the same installation method by calling: https://get.docker.com/

```
			set -x
				if [ "https://get.docker.com/" = "$url" ]; then
					$sh_c "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9"
				elif [ "https://test.docker.com/" = "$url" ]; then
					$sh_c "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 740B314AE3941731B942C66ADF4FD13717AAD7D6"
				elif [ "https://experimental.docker.com/" = "$url" ]; then
					$sh_c "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E33FF7BF5C91D50A6F91FFFD4CC38D40F9A96B49"
				else
					$sh_c "$curl ${url}gpg | apt-key add -"
				fi
				$sh_c "echo deb ${url}ubuntu docker main > /etc/apt/sources.list.d/docker.list"
				$sh_c 'sleep 3; apt-get update; apt-get install -y -q lxc-docker'
			)
```

**Comment by Wattos** [comment] 2015-07-05 19:51
@thaJeztah The installation was on a newly instantiated stack

**Comment by cpuguy83** [comment] 2015-07-05 20:43
@Wattos If you don't have the `linux-image-extra` package loaded, which includes the aufs kernel mods, docker can't use aufs.

**Comment by thaJeztah** [comment] 2015-07-05 20:49
> The installation was on a newly instantiated stack.

Ah, then that's expected yes, as @cpuguy83 explains. The other (regular) install script should take care of installing the required packages to get aufs running. (Based on your description, I though you were installing / upgrading an existing installation)

**Comment by thaJeztah** [comment] 2015-07-05 21:06
After the above discussion, it looks like there's no bug, but the "minimum" install script was used, which doesn't install the additional packages to run aufs.

I'm going to close this issue, because this is not a bug, but feel free to comment here after closing.

Thanks, @Wattos, I hope the above information will help you get Docker running correctly!

**Closed by thaJeztah** 2015-07-05 21:06 UTC
