### ISSUE TITLE
Support build-time variables in FROM instruction?

### ISSUE THREAD

**Issue by msabramo** [docker/docker#29101] opened 2016-12-03 17:21 UTC
Apologies if this has already been discussed before. I searched the GitHub issues and didn't see it but  might've overlooked it.

I'd like to be able to use build-time variables in the Dockerfile `FROM` instruction, as this would allow building many similar Docker images that are nearly identical except that they have different bases. For example:

```
$ docker build --build-arg bash_version=4.4.5 -t test-vault-bash-completion:4.4.5 -f tests/Dockerfile .
Sending build context to Docker daemon 245.8 kB
Step 1/7 : FROM bash:${bash_version}
Error parsing reference: "bash:${bash_version}" is not a valid repository/tag: invalid reference format

$ docker build --build-arg bash_version=3.2.57 -t test-vault-bash-completion:4.4.5 -f tests/Dockerfile .
Sending build context to Docker daemon 245.8 kB
Step 1/7 : FROM bash:${bash_version}
Error parsing reference: "bash:${bash_version}" is not a valid repository/tag: invalid reference format
```

**Comment by thaJeztah** [comment] 2016-12-03 23:30
Yup, I think this is a duplicate of https://github.com/docker/docker/issues/18119

I'll close this one, but please continue the conversation on the linked issue 👍

**Closed by thaJeztah** 2016-12-03 23:30 UTC
Labels: area/builder

**Comment by philippe-granet** [comment] 2017-05-08 09:37
You can now use build-time args (ARG) in FROM https://github.com/moby/moby/pull/31352
