### ISSUE TITLE
docker system df outputs weird numbers (docker 1.13.0

### ISSUE THREAD

**Issue by mbelang** [docker/docker#30409] opened 2017-01-24 16:26 UTC
After doing a `docker image prune -a`, doing `docker system df` displays weird numbers:

```
root@node02:~# docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              4                   4                   1.59 GB             -6.831e+08 B (-42%)
Containers          5                   5                   419 B               0 B (0%)
Local Volumes       3                   3                   227.7 MB            0 B (0%)
```
The number is close to 0 but not rounded to 0.

This is the first time I see that after doing multiple `docker image prune`.

**docker info**

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 52
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.907 GiB
Name: node02
ID: UUAE:LPNW:I4MD:FCVH:7XE2:GUWV:CPXV:I2TJ:X2I6:ZDDV:CIWZ:UPVR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by yongtang** [comment] 2017-01-24 16:49
I think this is a duplicate of #30257 and has already been fixed in #30378?

**Comment by dnephin** [comment] 2017-01-24 17:08
I think so. Going to close as duplicate of #30257

**Closed by dnephin** 2017-01-24 17:08 UTC

**Comment by mbelang** [comment] 2017-01-24 17:20
Oh ya sorry about that, I was looking for that and didn't found it...
