### ISSUE TITLE
`docker build` on macOS asks for keychain credentials if I include "alexwlchan" in the image tag

### ISSUE THREAD

**Issue by alexwlchan** [docker/docker#32440] opened 2017-04-07 17:52 UTC
**Description**

When I run `docker build` on my Mac and tag it with the string "alexwlchan", something within Docker is asking for access to entries in the system keychain.

**Steps to reproduce the issue:**

1. I have the following Dockerfile:

    ```dockerfile
    FROM alpine

    CMD ["echo", "hello"]
    ```

2. I run a `docker build` command and tag the image with a name that contains a subset of my username:

    ```console
    $ docker build -t alexwlchan/foo .
    Sending build context to Docker daemon 2.048 kB
    Step 1/2 : FROM alpine
     ---> 4a415e366388
    Step 2/2 : CMD echo hello
     ---> Using cache
     ---> 0542fdccd367
    Successfully built 0542fdccd367
    ```

**Describe the results you received:**

I get a popup from OS X:

> **docker-credential-osxkeychain wants to use your confidential information stored in "sync.omnigroup.com (alexwlchan)" in your keychain.**
>
> Do you want to allow access to this item? [Always Allow / Deny / Allow]

![screen shot 2017-04-07 at 18 39 44](https://cloud.githubusercontent.com/assets/301220/24812581/95002cd6-1bc2-11e7-95b1-79e6878850b9.png)

This is reproducible.

I've also seen it ask for PyPI credentials once, although I didn't get a screenshot that time.

**Describe the results you expected:**

Docker should build the image without trying to get credentials it doesn’t need. I’m not pushing the image to a remote repository, just doing a local build. And even if I was pushing remotely, my Omni Sync Server and PyPI credentials aren’t what you’d need.

**Additional information you deem important (e.g. issue happens only occasionally):**

My username on this machine is "alexwlchan":

```console
$ whoami
alexwlchan
```

That seems to be the problem string. The following names all hit the same issue:

* alexwlchan/foo
* foo/alexwlchan
* alexwlchan

These other names don't:

* alex/foo
* foo/alex
* alex

I also use that name for a lot of my online accounts – "alexwlchan" is the problem string, but whether that comes from my username or because it matches a lot of keychain entries, I’m not sure.

**Output of `docker version`:**

```console
$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```console
$ docker info
Containers: 42
 Running: 1
 Paused: 0
 Stopped: 41
Images: 25
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: Z4EI:56LI:OF5L:AGCF:OXT4:ANTZ:QX4A:CQKR:23YY:67ZA:NGHL:C4EY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 42
 System Time: 2017-04-07T17:52:00.32030131Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details:**

OS X 10.12.4 (16E195).

**Comment by thaJeztah** [comment] 2017-04-08 17:13
This is a duplicate of https://github.com/docker/for-mac/issues/1371, and should be fixed in the 17.03.1 version of Docker for Mac

I'll close this here, but let me know if you still have it after upgrading 👍

**Closed by thaJeztah** 2017-04-08 17:13 UTC
Labels: area/builder, version/17.03
