### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by hhzguo** [docker/docker#27330] opened 2016-10-12 22:13 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
I have two container images where are built from the same process, 
Container 1 consists of base image + binary A, EntryPoint: /bin/sh -c /usr/local/bin/binaryA
Container 2 consists of the same base image + binary B, EntryPoint: /bin/sh -s /usr/local/bin/BinaryB
Container 1 works fine, containers 2 return "127" error code, which is "Not found"
I use "docker exec -it container1 /bin/sh" and in the container,  BinaryA is there in /usr/local/bin and I can execute it in the container.
I use "docker run -it container2 /bin/sh" and in the container , BinaryB is also there in /usr/local/bin BUT I CAN NOT execute in the container and I got a "/bin/sh: ./BinaryB: not Found" , BinaryB has 'x" attribute set and I can even use vi to open it.

Other observation, if in /bin folder, I run "cp a b", "a" can run, but "b" can not,("applet not found") error.

Really confused here and can any one help me?

Thanks
Henry

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
 1.9.1

(paste your output here)
```

**Output of `docker info`:**
Containers: 15
Images: 29
Server Version: 1.9.1
Storage Driver: aufs
   Root Dir: /var/lib/docker/aufs
   Backing Filesystem: extfs
   Dirs: 59
   Dirperm1 supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 2
Total Memory: 3.839 GiB


```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by tonistiigi** [comment] 2016-10-12 22:23
Can you put together a reproducible testcase?

**Comment by hhzguo** [comment] 2016-10-12 22:36
tonistiigi:
    I am trying run kubemark in a kubernetes environment.  It doesn't have an easy repro.

Sorry about it.
Henry

**Comment by justincormack** [comment] 2016-10-12 23:24
"applet not found" is normally a busybox error. You do not however give enough information to be able to help. Basically you have a non executable binary, common causes are that it is missing shared libraries for example. If it is actually busybox, it looks at the name of the executable, so it matters what the bonary is called. Try renaming it to `busybox`.

**Comment by justincormack** [comment] 2016-10-12 23:25
I am going to close this as it is not a bug in Docker, but with some more information I expect we can work out what the issues is.

**Closed by justincormack** 2016-10-12 23:25 UTC
Labels: kind/question, status/more-info-needed
