### ISSUE TITLE
Windows: Incremental build mistakenly uses cache with large context

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#27755] opened 2016-10-25 22:35 UTC
I'm trying to build a windows image using a remote windows docker daemon, with a docker client running on a linux system.  It appears that if you have a large build context, something is going wrong with the detection logic and it thinks nothing has changed even when content has changed.

```
% docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:28:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

# Steps to reproduce
```bash
mkdir /tmp/repro && cd /tmp/repro
# Fill the context up with stuff - what doesn't matter really...
git clone git://github.com/docker/docker.git

cat << EOF > Dockerfile
FROM microsoft/nanoserver
ADD docker/hello.cmd /bin/hello.cmd
ENTRYPOINT ["/bin/hello.cmd"]
EOF

echo "echo 1 hello world" > docker/hello.cmd
docker build -t hello .
docker run --rm hello

echo "echo 2 hello world" > docker/hello.cmd
docker build -t hello .
docker run --rm hello
```

## Expected:
* The first `docker run` should say `1 hello world` and the second should say `2 hello world`

## Observed:
* Both report `1 hello world` and the `docker build` output on the second build command shows its still using the cache

I initially tried to repro this with a small build context, and it did not fail, so I believe the context has to be large(ish), although I'm not sure exactly how large it takes to trigger this behavior.

**Comment by friism** [comment] 2016-10-26 00:46
I can reproduce this cc @jhowardmsft

**Comment by jhowardmsft** [comment] 2016-10-26 00:56
That's a very old client. @friism does yours repro on master and with a Windows client? I can take a look but have at least half a dozen other issues in my backlog. May take a few days to get to it.

**Comment by dhiltgen** [comment] 2016-10-26 01:04
Client version doesn't seem to matter - I just tried with a 1.12.2 linux client and it still repro's the issue.

**Comment by friism** [comment] 2016-10-26 01:12
@jhowardmsft reproes with 1.12.2 on windows for me too

**Comment by jhowardmsft** [comment] 2016-10-26 02:34
Interesting, this doesn't seem to repro for me using WS2016 14393.rs1_release_inmarket.161004-2338 and current master, on a windowsservercore image. @friism, here's my repro steps to compare. All from a cmd prompt (not PS). Client and daemon both on Windows.

```
C:\temp>dir
 Volume in drive C has no label.
 Volume Serial Number is C821-3418

 Directory of C:\temp

10/25/2016  07:25 PM    <DIR>          .
10/25/2016  07:25 PM    <DIR>          ..
10/25/2016  07:15 PM                66 Dockerfile
10/25/2016  07:16 PM               146 doit.cmd
               2 File(s)            212 bytes
               2 Dir(s)  107,483,742,208 bytes free

C:\temp>type Dockerfile
FROM windowsservercore
ADD hello.cmd c:/
ENTRYPOINT c:\hello.cmd
C:\temp>type doit.cmd
echo echo 1 > hello.cmd
docker build -t hello .
docker run --rm hello

echo echo 2 > hello.cmd
docker build -t hello .
docker run --rm hello
C:\temp>
```

```
C:\temp>docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   77f4c30-jhoward-JHOWARD-Z420-Dynamic
 Built:        Wed Oct 26 01:44:01 UTC 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   77f4c30-jhoward-JHOWARD-Z420-Dynamic
 Built:        Wed Oct 26 01:44:01 UTC 2016
 OS/Arch:      windows/amd64
 Experimental: false

C:\temp>docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 1.345 GiB
Name: WIN-OSEVDRD9K24
ID: YHNN:5DSR:TO7A:YGXA:NMCU:FDGR:WOIL:J5SU:ZHTI:7Z57:TBLH:XPDL
Docker Root Dir: C:\control
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

C:\temp>
```

Make sure daemon is clear

```
C:\temp>docker ps -aq

C:\temp>docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
busybox                       latest              45c3d38f2fb6        4 days ago          7.24 GB
docker                        latest              2b1580f7b23e        6 days ago          8.4 GB
microsoft/windowsservercore   10.0.14393.321      01569f895bac        2 weeks ago         7.15 GB
microsoft/windowsservercore   latest              01569f895bac        2 weeks ago         7.15 GB
windowsservercore             latest              01569f895bac        2 weeks ago         7.15 GB
microsoft/nanoserver          10.0.14393.321      22738ff49c6d        2 weeks ago         686 MB
microsoft/nanoserver          latest              22738ff49c6d        2 weeks ago         686 MB
nanoserver                    latest              22738ff49c6d        2 weeks ago         686 MB

C:\temp>
```

Clone the sources `git clone https://github.com/docker/docker c:\temp\docker`, then run `doit.cmd`. First time, no cache as expected, and all working:

```
C:\temp>doit

C:\temp>echo echo 1  1>hello.cmd

C:\temp>docker build -t hello .
Sending build context to Docker daemon 150.4 MB
Step 1/3 : FROM windowsservercore
 ---> 01569f895bac
Step 2/3 : ADD hello.cmd c:/
 ---> 4e5644579fb4
Removing intermediate container e5f8c7ae099c
Step 3/3 : ENTRYPOINT c:\hello.cmd
 ---> Running in 8b713f33ebfa
 ---> 491777f46acd
Removing intermediate container 8b713f33ebfa
Successfully built 491777f46acd

C:\temp>docker run --rm hello

C:\>echo 1
1

C:\temp>echo echo 2  1>hello.cmd

C:\temp>docker build -t hello .
Sending build context to Docker daemon 150.4 MB
Step 1/3 : FROM windowsservercore
 ---> 01569f895bac
Step 2/3 : ADD hello.cmd c:/
 ---> 37cc12ea9156
Removing intermediate container c233797c4677
Step 3/3 : ENTRYPOINT c:\hello.cmd
 ---> Running in b8cb29dc55a0
 ---> 85f06759c030
Removing intermediate container b8cb29dc55a0
Successfully built 85f06759c030

C:\temp>docker run --rm hello

C:\>echo 2
2

C:\temp>
```

Then run doit.cmd a second time, with a 'hot' builder cache and still working the same as expected:
```
C:\temp>doit

C:\temp>echo echo 1  1>hello.cmd

C:\temp>docker build -t hello .
Sending build context to Docker daemon 150.4 MB
Step 1/3 : FROM windowsservercore
 ---> 01569f895bac
Step 2/3 : ADD hello.cmd c:/
 ---> Using cache
 ---> 4e5644579fb4
Step 3/3 : ENTRYPOINT c:\hello.cmd
 ---> Using cache
 ---> 491777f46acd
Successfully built 491777f46acd

C:\temp>docker run --rm hello

C:\>echo 1
1

C:\temp>echo echo 2  1>hello.cmd

C:\temp>docker build -t hello .
Sending build context to Docker daemon 150.4 MB
Step 1/3 : FROM windowsservercore
 ---> 01569f895bac
Step 2/3 : ADD hello.cmd c:/
 ---> Using cache
 ---> 37cc12ea9156
Step 3/3 : ENTRYPOINT c:\hello.cmd
 ---> Using cache
 ---> 85f06759c030
Successfully built 85f06759c030

C:\temp>docker run --rm hello

C:\>echo 2
2

C:\temp>
```

I then cleared the daemon down and repeated the same using the nanoserver image and it still worked. So it sounds like a bug that's been fixed in master unless you can repro on master too? Here's the nanoserver equivalent two runs, first with a cold cache, then with a hot cache.

```
C:\temp>doit

C:\temp>echo echo 1  1>hello.cmd

C:\temp>docker build -t hello .
Sending build context to Docker daemon 150.4 MB
Step 1/3 : FROM nanoserver
 ---> 22738ff49c6d
Step 2/3 : ADD hello.cmd c:/
 ---> 344afc57872c
Removing intermediate container c6479a770425
Step 3/3 : ENTRYPOINT c:\hello.cmd
 ---> Running in 24656c0b8e92
 ---> 3529580c5838
Removing intermediate container 24656c0b8e92
Successfully built 3529580c5838

C:\temp>docker run --rm hello

C:\>echo 1
1

C:\temp>echo echo 2  1>hello.cmd

C:\temp>docker build -t hello .
Sending build context to Docker daemon 150.4 MB
Step 1/3 : FROM nanoserver
 ---> 22738ff49c6d
Step 2/3 : ADD hello.cmd c:/
 ---> 65d14f7e2510
Removing intermediate container cb03cf016815
Step 3/3 : ENTRYPOINT c:\hello.cmd
 ---> Running in 3cb35eafd6d2
 ---> 7e8fa5edb113
Removing intermediate container 3cb35eafd6d2
Successfully built 7e8fa5edb113

C:\temp>docker run --rm hello

C:\>echo 2
2

C:\temp>doit

C:\temp>echo echo 1  1>hello.cmd

C:\temp>docker build -t hello .
Sending build context to Docker daemon 150.4 MB
Step 1/3 : FROM nanoserver
 ---> 22738ff49c6d
Step 2/3 : ADD hello.cmd c:/
 ---> Using cache
 ---> 344afc57872c
Step 3/3 : ENTRYPOINT c:\hello.cmd
 ---> Using cache
 ---> 3529580c5838
Successfully built 3529580c5838

C:\temp>docker run --rm hello

C:\>echo 1
1

C:\temp>echo echo 2  1>hello.cmd

C:\temp>docker build -t hello .
Sending build context to Docker daemon 150.4 MB
Step 1/3 : FROM nanoserver
 ---> 22738ff49c6d
Step 2/3 : ADD hello.cmd c:/
 ---> Using cache
 ---> 65d14f7e2510
Step 3/3 : ENTRYPOINT c:\hello.cmd
 ---> Using cache
 ---> 7e8fa5edb113
Successfully built 7e8fa5edb113

C:\temp>docker run --rm hello

C:\>echo 2
2

C:\temp>
```

**Comment by StefanScherer** [comment] 2016-10-26 06:54
Can reproduce the problem with both 1.12.2-cs2-ws-beta and latest 1.13-dev on Win2016.

```
C:\Users\vagrant\test27755> "echo hello world 1"  | Out-File -Encoding Ascii docker\hello.cmd
C:\Users\vagrant\test27755> docker build --no-cache -t hello .
Sending build context to Docker daemon 150.4 MB
Step 1/3 : FROM microsoft/nanoserver
 ---> e14bc0ecea12
Step 2/3 : ADD docker/hello.cmd /bin/hello.cmd
 ---> aeb38912251e
Removing intermediate container af851401b246
Step 3/3 : ENTRYPOINT /bin/hello.cmd
 ---> Running in d70f7decfe16
 ---> bedb446c7f55
Removing intermediate container d70f7decfe16
Successfully built bedb446c7f55
C:\Users\vagrant\test27755> docker run --rm hello

C:\>echo hello world 1
hello world 1
C:\Users\vagrant\test27755> "echo hello world 2"  | Out-File -Encoding Ascii docker\hello.cmd
C:\Users\vagrant\test27755> docker build -t hello .
Sending build context to Docker daemon 150.4 MB
Step 1/3 : FROM microsoft/nanoserver
 ---> e14bc0ecea12
Step 2/3 : ADD docker/hello.cmd /bin/hello.cmd
 ---> Using cache
 ---> aeb38912251e
Step 3/3 : ENTRYPOINT /bin/hello.cmd
 ---> Using cache
 ---> bedb446c7f55
Successfully built bedb446c7f55
C:\Users\vagrant\test27755> docker run --rm hello

C:\>echo hello world 1
hello world 1
C:\Users\vagrant\test27755> docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   a6dfab0
 Built:        Wed Oct 26 06:10:18 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   a6dfab0
 Built:        Wed Oct 26 06:10:18 2016
 OS/Arch:      windows/amd64
 Experimental: false
```

**Comment by StefanScherer** [comment] 2016-10-26 06:58
But this is reproducable with only the hello.cmd with any other files as well:

```
C:\Users\vagrant\test27755\mini> mkdir docker


    Directory: C:\Users\vagrant\test27755\mini


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/25/2016  11:55 PM                docker


C:\Users\vagrant\test27755\mini> "echo hello world 1"  | Out-File -Encoding Ascii docker\hello.cmd
C:\Users\vagrant\test27755\mini> docker build --no-cache -t hello .
Sending build context to Docker daemon 3.584 kB
Step 1/3 : FROM microsoft/nanoserver
 ---> e14bc0ecea12
Step 2/3 : ADD docker/hello.cmd /bin/hello.cmd
 ---> 6595c2407e1a
Removing intermediate container c5ed9e8e7e02
Step 3/3 : ENTRYPOINT /bin/hello.cmd
 ---> Running in 139cead7281b
 ---> 7c988e196f24
Removing intermediate container 139cead7281b
Successfully built 7c988e196f24
C:\Users\vagrant\test27755\mini> docker run --rm hello

C:\>echo hello world 1
hello world 1
C:\Users\vagrant\test27755\mini> "echo hello world 2"  | Out-File -Encoding Ascii docker\hello.cmd
C:\Users\vagrant\test27755\mini> docker build -t hello .
Sending build context to Docker daemon 3.584 kB
Step 1/3 : FROM microsoft/nanoserver
 ---> e14bc0ecea12
Step 2/3 : ADD docker/hello.cmd /bin/hello.cmd
 ---> Using cache
 ---> 6595c2407e1a
Step 3/3 : ENTRYPOINT /bin/hello.cmd
 ---> Using cache
 ---> 7c988e196f24
Successfully built 7c988e196f24
C:\Users\vagrant\test27755\mini> docker run --rm hello

C:\>echo hello world 1
hello world 1
C:\Users\vagrant\test27755\mini> dir .\docker\


    Directory: C:\Users\vagrant\test27755\mini\docker


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/25/2016  11:56 PM             20 hello.cmd


C:\Users\vagrant\test27755\mini> dir


    Directory: C:\Users\vagrant\test27755\mini


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/25/2016  11:56 PM                docker
-a----       10/25/2016  11:38 PM             97 Dockerfile
```

**Comment by friism** [comment] 2016-10-26 06:59
Ya, can confirm on master too

**Comment by jhowardmsft** [comment] 2016-10-26 19:47
Ah, yes, I have a repro. The simpler one to debug without the large number of files. Investigating....

**Comment by jhowardmsft** [comment] 2016-10-26 23:25
Worked it out. Some serious debugging 😓. Is a subtle bug in tarsum, and truly I'm astonished this hasn't been seen before. Will submit a PR shortly.

**Comment by StefanScherer** [comment] 2016-10-27 19:19
Thanks! OMG I can remember that I've seen that writing the Dockerfile.windows for docker/docker last year, modifying some code eg. switching branches and then hit the caching problem. Had to modify the Dockerfile a layer before, something like that. But was happy that it worked so good in these early days. Never encountered that problem since then so I forgot filing an issue :-(

**Closed** 2016-10-28 00:49 UTC
Labels: area/builder, kind/bug, platform/windows, version/1.12
