### ISSUE TITLE
Creating Bridge Fails is Route Table has RFC1918 'unreachable'

### ISSUE THREAD

**Issue by fukawi2** [docker/docker#6442] opened 2014-06-16 02:59 UTC
Platform: CentOS 6 x64

Installed docker but it won't start:

    [debug] driver.go:254 172.17.42.1/16 requested network overlaps with existing network
    [debug] driver.go:254 10.0.42.1/16 requested network overlaps with existing network
    [debug] driver.go:254 10.1.42.1/16 requested network overlaps with existing network
    [debug] driver.go:254 10.42.42.1/16 requested network overlaps with existing network
    [debug] driver.go:254 172.16.42.1/24 requested network overlaps with existing network
    [debug] driver.go:254 172.16.43.1/24 requested network overlaps with existing network
    [debug] driver.go:254 172.16.44.1/24 requested network overlaps with existing network
    [debug] driver.go:254 10.0.42.1/24 requested network overlaps with existing network
    [debug] driver.go:254 10.0.43.1/24 requested network overlaps with existing network
    [debug] driver.go:254 192.168.42.1/24 requested network overlaps with existing network
    [debug] driver.go:254 192.168.43.1/24 requested network overlaps with existing network
    [debug] driver.go:254 192.168.44.1/24 requested network overlaps with existing network

This appears to be because I have all RFC1918 addresses in my route table as "unreachable":

    # ip r s
    unreachable 192.168.0.0/16  metric 999
    unreachable 172.16.0.0/12  metric 999
    unreachable 10.0.0.0/8  metric 999

Deleting the route for 172.16.0.0/12 allows docker to start correctly:

     ~ # ip r d 172.16.0.0/12
     ~ # /etc/init.d/docker start
    Starting docker:	                                   [  OK  ]
     ~ # ps -ef | grep docker
    root      1199     1  8 12:57 pts/0    00:00:00 /usr/bin/docker -d -e lxc
    root      1262  1052  0 12:57 pts/0    00:00:00 grep docker

**Comment by jfrazelle** [comment] 2015-02-25 20:30
closing as duplicate of https://github.com/docker/docker/issues/10307 and you can express your concerns there

**Closed by jfrazelle** 2015-02-25 20:30 UTC
Labels: /system/networking
