### ISSUE TITLE
docker why can't operate

### ISSUE THREAD

**Issue by hanxy** [docker/docker#11283] opened 2015-03-10 13:07 UTC
I run 60 containers for some times, I found docker is dead, all docker commands can't used and they are always waiting and not show any information. And then I test the api operation, and also can't get anything.

**Comment by unclejack** [comment] 2015-03-10 15:26
@hanxy Please provide output of `docker info`, `docker version` and `uname -a`. All of this information is needed.

Please keep in mind that hardware problems, customized installs (custom kernel which isn't supported by the distribution), automated scheduled reboots and other external tools may interfere with Docker daemon's proper functioning.

**Comment by hanxy** [comment] 2015-03-11 01:02
@unclejack  
My kernel is 
   "Linux kvmnode7553 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64    x86_64 x86_64 GNU/Linux"

docker info:

    Containers: 65
    Images: 25
    Storage Driver: devicemapper
    Pool Name: docker-252:2-8803-pool
    Pool Blocksize: 65.54 kB
    Data file: /dev/docker_vg/lvm_direct_data
    Metadata file: /dev/docker_vg/lvm_direct_metadata
    Data Space Used: 6.084 GB
    Data Space Total: 2.199 TB
    Metadata Space Used: 19.92 MB
    Metadata Space Total: 5.369 GB
    Library Version: 1.02.82-git (2013-10-04)
    Execution Driver: native-0.2
    Kernel Version: 3.13.0-24-generic
    Operating System: Ubuntu 14.04 LTS
    Debug mode (server): true
    Debug mode (client): false
    Fds: 376
    Goroutines: 441
    EventsListeners: 0
    Init Path: /usr/bin/docker

    Client version: 1.3.2
    Client API version: 1.15
    Go version (client): go1.3.3
    Git commit (client): 39fa2fa
    OS/Arch (client): linux/amd64
    Server version: 1.3.2
    Server API version: 1.15
    Go version (server): go1.3.3
    Git commit (server): 39fa2fa

Currently We start contariner and run the contaiber by remote API. 
Unfortunately We run the containers for some days, and I can't do anything on docker.
include docker ps,docker info and others docker commands and found docker daemon api also can't access. So I am worry this problem.

**Comment by unclejack** [comment] 2015-03-12 08:34
@hanxy You need to install system updates and you also need to update Docker. Docker 1.3.2 is a rather old version and you should upgrade it to Docker 1.5.0. Kernel `3.13.0-24` is also very old and it should be updated to the latest kernel provided by Ubuntu on 14.04 (currently `3.13.0-46`).

**Comment by hanxy** [comment] 2015-03-16 01:14
@unclejack ok, thanks, I will try it.

**Comment by unclejack** [comment] 2015-04-06 14:07
@hanxy Please let us know if this is still a problem. I've got Docker running 24/7 and I'm not seeing any such problems on Ubuntu 14.04. Please ensure your system is fully updated by using `apt-get update && apt-get dist-upgrade -y` and reboot. You also need to make sure you're running the latest Docker version.

There are known bugs in 1.3.2 and older versions which can lead to crashes of the Docker daemon.

I'm going to close this issue now because it has been reported against an old kernel which is known to be broken (`3.13.0-24`, latest was `3.13.0-48` last time I checked) and against an old Docker version.

If anyone can reproduce this problem with the latest kernel provided by the Ubuntu repositories and the latest Docker version, please comment.

**Closed by unclejack** 2015-04-06 14:07 UTC
