### ISSUE TITLE
Support for "proxy" environment variables for building containers

### ISSUE THREAD

**Issue by jperville** [docker/docker#8533] opened 2014-10-13 08:02 UTC
I am looking for a way to specify "proxies" at `docker build`-time.

I know that injecting environment variables or volumes at build-time is frowned upon because it makes the build host-specific and non-reproducible (see #6822 for example) ; however when these environment variables are used to specify http proxies (or similar, that do not alter the files used to build the container) I feel this is legitimate use.

To give some context, I am living in Myanmar where the best Internet connection is spotty at best ; my main problem right now to pass the "bundle install" part of my `Dockerfile` without connection reset or DNS errors.

For non-https resources, I can work around the issue using a squid proxy and firewall rules. However, for `https://rubygems` I cannot because the source is https, so intercepting traffic to it would result in SSL certificate validation errors. When developing outside of Docker I can tell bundler to use a mirror using `bundler config. bundle config mirror.https://rubygems.org http://my.rubygems-mirror.example.org/` or setting an option in `~/.bundle/config` or exporting environment variables.

None of the above options are acceptable when using static Dockerfile because (ironically) mentioning the local rubygems proxy explicitly in the Dockerfile would make it host-specific and non-reproducible.

Is there a way to specify any of these at build time, other than not using `docker build` at all?
I would be totally OK if `docker build` accepted a `--I-know-what-I-m-doing-env` option (with no `-e` shortcut so that people who use that feature are forced to read the documentation and understand why it should be used carefully).

**Comment by thaJeztah** [comment] 2015-02-21 00:15
Also duplicate of https://github.com/docker/docker/issues/4962?

**Comment by jfrazelle** [comment] 2015-02-25 22:33
closing as dup of https://github.com/docker/docker/issues/4962

**Closed by jfrazelle** 2015-02-25 22:33 UTC
