### ISSUE TITLE
MacVlan driver does not appear in plugin list (docker info)

### ISSUE THREAD

**Issue by albers** [docker/docker#24798] opened 2016-07-19 15:12 UTC
According to the 1.12.0 RCX release notes, 

> MacVlan driver is out of experimental

The driver is indeed available and worksas described in the docs, e.g.

```bash
root@e45c52a3083f:~# docker network  create  -d macvlan --subnet=192.168.50.0/24 --gateway=192.168.50.1 -o parent=eth0.50 macvlan50
933b762feb5d11bf31f7dd89e1e91f79f7741f558ebdfd899a30302f1520a5a8
root@e45c52a3083f:~# docker network ls --filter type=custom
NETWORK ID          NAME                DRIVER              SCOPE
933b762feb5d        macvlan50           macvlan             local
root@e45c52a3083f:~# docker --version
Docker version 1.12.0-dev, build cf8f2a5
```

But I would expect the driver to appear in the plugins section of `docker info`:

```bash
root@e45c52a3083f:~# docker info
[snip]
Plugins:
 Volume: local
 Network: overlay null host bridge
[snip]
```
>expected:
 Network: overlay null host bridge macvlan
actual
 Network: overlay null host bridge

This is important for me because the bash completion for `docker network create -d` grabs the available drivers from `docker info`. Therefore, the driver is missing in that context.

**Comment by thaJeztah** [comment] 2016-07-20 14:37
Thanks @albers! This seems to be the same issue as https://github.com/docker/docker/issues/23619

basically the plugin only shows if it's actually in use by a network, so;

```
docker info
...
Plugins:
 Volume: local
 Network: null overlay bridge host
...
```

But after a network is created using that driver, it shows up in docker info;

```
docker network  create  -d macvlan --subnet=192.168.50.0/24 --gateway=192.168.50.1 -o parent=eth0.50 macvlan50

docker info

...
Plugins:
 Volume: local
 Network: macvlan overlay null bridge host
...
```

**Comment by albers** [comment] 2016-07-20 19:58
>But after a network is created using that driver, it shows up in docker info

Ah, you're right, I just checked this. Is this how it should work or is it a bug?

**Comment by cpuguy83** [comment] 2016-07-20 20:06
@albers It's as designed... but not ideal.
The new plugin system should handle this.

**Comment by albers** [comment] 2016-07-20 20:09
OK, then I will manually add macvlan to bash completion until the new plugin management is available.

**Comment by albers** [comment] 2016-07-20 20:22
@cpuguy83 Thanks for clarifying.

**Comment by justincormack** [comment] 2016-10-11 23:30
I am going to close this as it seems resolved, and work on the new plugin system is continuing.

**Closed by justincormack** 2016-10-11 23:30 UTC
