### ISSUE TITLE
autogen + go get?

### ISSUE THREAD

**Issue by bradrydzewski** [docker/docker#10922] opened 2015-02-20 22:46 UTC
for better or worse there are some projects out there that are linking to Docker packages, including term, stdcopy, archive, parsers, etc. Here is an example:
https://github.com/samalba/dockerclient/blob/master/dockerclient_test.go

By excluding the autogen folder from the repository it is no longer go gettable:

```
../../docker/docker/utils/utils.go:24:2: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/usr/src/go/src/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/go/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
Makefile:26: recipe for target 'build' failed
```

**Comment by brahmaroutu** [comment] 2015-02-21 00:09
I am sorry, I can do a "go get github.com/docker/docker/pkg/stdcopy" from command line and see the whole docker branch downloaded. 
I think the issue is when compiling the code. I am looking into ways to address this, please share any ideas you have.

**Comment by brahmaroutu** [comment] 2015-02-21 00:33
ping @tianon

**Comment by shawnzhu** [comment] 2015-02-21 04:17
@brahmaroutu is right since #10665 was merged which means additional build step need to be performed to get `github.com/docker/docker/autogen/` after fetching source (like the newly added make step in https://github.com/drone/drone/blob/master/Makefile#L11).

So far, the only additional step I performed is `bash $gopath/src/github.com/docker/docker/project/make/.dockerversion` to build [drone/drone](https://github.com/drone/drone). Wondering if there are any other steps?

**Comment by brahmaroutu** [comment] 2015-02-21 04:58
@shawnzhu If you are only dependent on "pkg" then the proposed fix above should work and you need not generate any files. If you are building Docker then you are right .dockerversion generates this file.

**Comment by shawnzhu** [comment] 2015-02-21 05:03
it depends on `github.com/docker/docker/utils` in project [drone/drone](https://github.com/drone/drone) so   it have to run `$gopath/src/github.com/docker/docker/project/make/.dockerversion` to generate `github.com/docker/docker/autogen/dockerversion/dockerversion`

**Closed** 2015-02-23 22:49 UTC

**Comment by vieux** [comment] 2015-03-03 20:12
This is really a pain

**Comment by deevus** [comment] 2015-03-04 10:58
I'm getting this error trying to compile the docker client on Windows.

**Comment by tianon** [comment] 2015-03-04 12:31
@vieux did #10925 not fix this for you? :disappointed:

@deevus to compile a Windows client natively on Windows, you'll need to use something like this from a Bash shell (like the one included in msysGit):
```console
$ DOCKER_CLIENTONLY=1 ./hack/make.sh dynbinary
```

**Comment by flmader** [comment] 2015-03-05 20:42
I am having problems compiling on Windows too. I tried to run ./project/make.sh project/make/dynbinary from Git Bash but it crashes too. After setting gopath correctly using export instead of set, make.sh crashes while creating a symbolic link:
ln: creating symbolic link `.gopath/src/github.com/docker/docker' to `../../../..': Permission denied

**Comment by vieux** [comment] 2015-03-05 20:50
@tianon do it didn't I still have issue if I want to vendor docker.

**Comment by flmader** [comment] 2015-03-05 21:13
I managed to build on Windows following @tianon 's advice.
Open Git Bash As Administrator
cd /c/gopath/src/github.com/docker/docker
export GOPATH=C:/gopath,C:/gopath/src/github.com/docker/docker/vendor
project/make.sh dynbinary

Then I switched back to the Windows Command Prompt and ran
set GOPATH=c:\gopath;c:\gopath\src\github.com\docker\docker\vendor
set DOCKER_CLIENTONLY=1
go build -v

**Comment by denverdino** [comment] 2015-03-06 09:59
@shawnzhu, Ke
After the commit of  https://github.com/docker/docker/commit/8625a281c66180af867f59a041560bf5035ae404

My work around this problem is to use following command to build docker package prior to my project in drone
```
cd $gopath/src/github.com/docker/docker
bash project/make/.go-autogen
```

**Comment by deevus** [comment] 2015-03-10 04:57
@denverdino That is the solution!

Thank you :)

**Comment by lbadams2** [comment] 2015-06-18 17:01
When I try to run bash .go-autogen I get "line 50: rsrc: command not found"

**Comment by messyOne** [comment] 2015-07-08 20:23
I got the same error: hack/make/.go-autogen: line 51: rsrc: command not found
