### ISSUE TITLE
docker build (1.12 dev) corrupting image? /bin/bash not found

### ISSUE THREAD

**Issue by tarunlalwani** [docker/docker#23010] opened 2016-05-26 05:42 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   cd159fb
 Built:
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   cd159fb
 Built:
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 21
Server Version: 1.12.0-dev
Storage Driver: devicemapper
 Pool Name: docker-253:2-268590534-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.214 GB
 Data Space Total: 107.4 GB
 Data Space Available: 67.66 GB
 Metadata Space Used: 11.91 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.6 GiB
Name: localhost.localdomain
ID: FFLC:YWLS:3BJJ:MIUS:OUDN:Y6UE:RCLS:D7CX:ZKXE:RURN:A6I2:GHM3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine with CentOS7.2.1511 + 128 GB RAM + 32 CORES

**Steps to reproduce the issue:**
1. Build the below Dockerfile

```
FROM centos:7.2.1511
RUN mkdir -p /root/automation
WORKDIR /root/automation
```
2. Run `docker build .`

```
Step 1 : FROM centos:7.2.1511
 ---> 38ea04e19303
Step 2 : RUN mkdir -p /root/automation
 ---> Running in dec21cc94aa3
 ---> 2c573d6e0459
Removing intermediate container dec21cc94aa3
Step 3 : WORKDIR /root/automation
 ---> Running in 63e42e01ec89
 ---> e6df6cdef6ee
Removing intermediate container 63e42e01ec89
Successfully built e6df6cdef6ee
```
3. 

[root@localhost automation]#  docker run -it e6df6cdef6ee
docker: Error response from daemon: Container command '/bin/bash' not found or does not exist.

**Describe the results you received:**
Error that /bin/bash. I am able to get bash in the 38ea04e19303 container

**Describe the results you expected:**
A bash terminal

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment] 2016-05-27 15:52
This is probably related to the reported issues with commit and diff on devicemapper.
Ping @rhvgoyal

**Comment by thaJeztah** [comment] 2016-05-27 23:18
We merged a PR to fix that, https://github.com/docker/docker/pull/23067, which will be in the 1.11.2 patch release; a release candidate for that should be available soon, so it would be great if you could test with that, and see if it resolves this issue

**Comment by rhvgoyal** [comment] 2016-05-31 14:26
Yes, I hope that shishir's fix solves the issues related to the build.

**Comment by thaJeztah** [comment] 2016-05-31 15:34
@tarunlalwani would you be able to test the 1.11.2 release-candidate?

**Comment by tarunlalwani** [comment] 2016-05-31 15:39
@theJeztah, yes I can

**Comment by tiborvass** [comment] 2016-06-27 18:55
Can't reproduce, must have been fixed already.

**Closed by tiborvass** 2016-06-27 18:55 UTC
Labels: version/master

**Comment by ifrh** [comment] 2016-07-27 17:48
@tiborvass, @thaJeztah  What happend if you change the Workdir forom outside Dockerfile with --workdir command?
On my maschine the option `--workdir` breaks *`docker run`*, see https://github.com/docker/docker/issues/25052
