### ISSUE TITLE
Override named container with -oc or --override-container parameter

### ISSUE THREAD

**Issue by lexandro** [docker/docker#22811] opened 2016-05-18 12:27 UTC
Named containers are cool, but you should provide --rm to make your run command repeatable, but deleting containers after stopping is not always the desired behavior because we want inspect them or tail their log, etc. During the development would be nice to use named containers and make possible their overriding with a parameter.

Suggested parameteres:
**-oc** or **--override-container** - Overriding the same named container if exists

**-f** or **--force**  - Force the override of the named container

Current situation:
Step 1: `docker run --name ubuntu ubuntu echo hello`
Step 2: repeating step 1 is not possible without --rm.

Suggested way:
Step 1: `docker run --name ubuntu ubuntu echo hello`
Step 2: `docker run -oc --name ubuntu ubuntu echo hello `

In step 2 the docker client calls an rm first on the image. 

Optional parameter: -f or --force for forced replacement
Step 2: `docker run -f -oc  --name ubuntu ubuntu echo hello `

**Comment by thaJeztah** [comment] 2016-05-18 14:07
You can already do so using `docker rename`, so I don't think we should implement something like this;

```
docker run -dit --name container ubuntu sh -c "echo hello"
docker rename container old-container \
&& docker run -dit --name container ubuntu sh -c "echo hello" \
&& docker stop old-container
```

**Comment by thaJeztah** [comment] 2016-05-18 14:12
I think this is a duplicate of https://github.com/docker/docker/issues/2733, so I'll close this issue, but feel free to comment here after I closed 👍

**Closed by thaJeztah** 2016-05-18 14:12 UTC

**Comment by lexandro** [comment] 2016-05-18 15:48
That's interesting, because --rm is also a hack that exists only in the client. Your solution is quite sophisticated especially, when you are just trying things :(

**Comment by jrichardsz** [comment] 2018-03-28 20:22
maybe this could help you :
# create image
docker build -t my_image .

# run image as container (remove before run)
docker rm "my_awesome_containter" -f && docker run --name "my_awesome_containter"  my_image

# more elegant
container_name="my_awesome_containter"
docker rm $container_name -f && docker run --name $container_name  my_image

# first call fails because container does not exist (coming soon)
