### ISSUE TITLE
Cannot control permissions of /dev/fuse device

### ISSUE THREAD

**Issue by leth** [docker/docker#10184] opened 2015-01-19 13:57 UTC
The device always ends up without permissions:

```
$ docker run --rm ubuntu:14.04 ls -l /dev/fuse 
c--------- 1 root root 10, 229 Jan 19 13:52 /dev/fuse

$ docker run --rm --device /dev/fuse:/dev/fuse:mrw ubuntu:14.04 ls -l /dev/fuse  
c--------- 1 root root 10, 229 Jan 19 13:50 /dev/fuse

docker run --rm --device /dev/fuse:/dev/fuse2:mrw ubuntu:14.04 ls -l /dev/fuse /dev/fuse2
c--------- 1 root root 10, 229 Jan 19 13:53 /dev/fuse
crw-rw-rw- 1 root root 10, 229 Jan 19 13:53 /dev/fuse2
```

I exepct it's something to do with this code: https://github.com/docker/docker/blob/487a417d9fd074d0e78876072c7d1ebfd398ea7a/vendor/src/github.com/docker/libcontainer/devices/defaults.go#L144

Here's some system info:

```
$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
 
$  docker info
Containers: 1
Images: 410
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 412
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 7.681 GiB
Name: kohlenstoff
ID: A2Z5:S5HC:B3ZL:AI4R:TSKW:3HTP:5K4D:22GZ:BTZL:AV4T:ZA73:BRKO
WARNING: No swap limit support
```

**Comment by phemmer** [comment] 2015-01-19 18:12
You need to start the container with `--privileged` mode.

**Comment by leth** [comment] 2015-01-19 21:27
That will work, but it's very heavy-handed. This is supposed to work; it's in the docs: http://docs.docker.com/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration

**Comment by thaJeztah** [comment] 2015-01-19 23:30
@leth reading that part of the docs;

> To mount a FUSE based filesystem, you need to combine both --cap-add and --device:

Could that be your problem here?

**Comment by leth** [comment] 2015-01-20 08:10
Ah, sorry. I was trying that originally, it made no difference. I simplified the command as far so I could after that. I'll verify and update once I get to work today.

**Comment by leth** [comment] 2015-01-20 11:36
Yep, doesn't fix it:
```
$ docker run --rm --cap-add SYS_ADMIN --device /dev/fuse:/dev/fuse:mrw ubuntu:14.04 ls -l /dev/fuse
c--------- 1 root root 10, 229 Jan 20 11:35 /dev/fuse

$ docker run --rm --cap-add SYS_ADMIN --device /dev/fuse:/dev/fuse2:mrw ubuntu:14.04 ls -l /dev/fuse /dev/fuse2
c--------- 1 root root 10, 229 Jan 20 11:36 /dev/fuse
crw-rw-rw- 1 root root 10, 229 Jan 20 11:36 /dev/fuse2
```

**Comment by thaJeztah** [comment] 2015-01-20 12:19
Thanks for trying. I don't have experience in this area, but with this added information, possibly someone else is able to see what the problem is here.

**Comment by robertabbott** [comment] 2015-01-29 21:22
I'm not totally clear on your objective. If your goal is to mount /dev/fuse from the host and keep the permissions it has on the host, you need to mount /dev/fuse with the -v option to override the default /dev/fuse.  

docker run --rm --device /dev/fuse:/dev/fuse:mrw -v /dev/fuse:/dev/fuse ubuntu:14.04 ls -l /dev/fuse
crw-rw-rw- 1 root root 10, 229 Jan 20 20:52 /dev/fuse

**Comment by leth** [comment] 2015-01-29 21:39
@robertabbott: My goal is to use fuse within a docker container, I don't really care how. The docs said it was possible, but their description no longer works.

What's the point of `--device` if it doesn't give you permissions to use devices, even if you ask?

My hunch is that this used to work, but was broken when the default created-but-not-allowed /dev/fuse was added. Shouldn't this locked-down /dev/fuse only be added when you're not already adding /dev/fuse manually?

I found the (part of libcontainer which creates `/dev/fuse`)[https://github.com/docker/libcontainer/blob/164cd807a16e63ed539cddda55ce3bbc32e1791e/devices/defaults.go#L146] which says "/dev/fuse is created but not allowed." and references #514 and #2393.

**Comment by robertabbott** [comment] 2015-01-29 22:46
I think you're right. I would expect --device to take precedence over the default option.

**Comment by timthelion** [comment] 2015-03-18 22:47
Being the author of the code in question, I can confirm that this is indeed a bug in Docker. I'm sorry about this. You can work around this issue by having a script in your container delete the device node and recreate it, or perhaps simply by chmoding the device node. The ultimate fix for this is to change this line here https://github.com/docker/docker/blob/master/daemon/container.go#L280 to a set union/merge function, which uses the device `path` as the id.

What I mean by that, is that there needs to be a loop there that builds `autoCreatedDevices` by adding one device at a time and that only adds devices to `autoCreatedDevices` from `configs.DefaultAutoCreatedDevices` if the `path` is not already represented in `userSpecifiedDevices`.

Please send a pull request.

**Comment by leth** [comment] 2015-03-19 10:26
@timthelion No problem, thanks for confirming!

FWIW I'm unlikely to get a chance to propose a fix for this any time soon, partly because I'm busy with other things and it's not blocking me directly, but also because I don't really know golang, so would have to have the time to dive into the language.

**Comment by thaJeztah** [comment] 2015-03-19 10:34
@jfrazelle could you label this as "bug"? (see https://github.com/docker/docker/issues/10184#issuecomment-83216360 above). I *think* "white belt", but you're probably better at determining that :)

**Comment by timthelion** [comment] 2015-03-19 11:25
Hm, now that I think about this, the line before https://github.com/docker/docker/blob/master/daemon/container.go#L278 also needs to be a union/merge. Definately a "white belt" fix though.

**Comment by davidrjenni** [comment] 2015-05-25 07:31
#dibs

**Closed** 2015-06-01 16:30 UTC
Labels: exp/novice, kind/bug, status/claimed
