### ISSUE TITLE
docker build returns "501 Not implemented" when using hash tag

### ISSUE THREAD

**Issue by tmds** [docker/docker#15326] opened 2015-08-05 08:13 UTC
A build like this works fine:

     docker build https://server/path/repo.git

A build like this doesn't:

     docker build https://server/path/repo.git#0.1

It returns:

     FATA[0005] Error response from daemon: Got HTTP status code >= 400: 501 Not Implemented

What part of the system is responsible for handling the hash tag? Do I need to upgrade it?

I am using docker on windows, executing via 'boot2docker ssh' returns the same error message.

Version information:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): windows/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

**Comment by Pensu** [comment] 2015-08-05 08:58
@tmds: You have posted it twice, this is a duplicate of #15325. Please close this.

**Comment by cpuguy83** [comment] 2015-08-05 15:14
This was not supported until docker 1.7.0

**Closed by cpuguy83** 2015-08-05 15:14 UTC
