### ISSUE TITLE
Container frozen, can not start, stop, kill

### ISSUE THREAD

**Issue by phanimahesh** [docker/docker#14845] opened 2015-07-22 04:23 UTC
The issue persists after rebooting docker or the entire machine. The container can not be started, stopped, or killed.

```
$ docker stop <container-name>
Post http:///var/run/docker.sock/v1.19/containers/<container-name>/stop?t=10: EOF. Are you trying to connect to a TLS-enabled daemon without TLS?
Error: failed to stop containers: [<container-name>]

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                      NAMES
2e251726fc6f        test                "/run.sh"           6 months ago        Up 2 days           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   <container-name>

$ docker kill <container-name>
Post http:///var/run/docker.sock/v1.19/containers/<container-name>/kill?signal=KILL: EOF. Are you trying to connect to a TLS-enabled daemon without TLS?
Error: failed to kill containers: [<container-name>]
```

BUG REPORT INFORMATION
```
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

$ docker info
Containers: 2
Images: 71
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 76
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 7.798 GiB
Name: <hostname>
ID: V5OX:H2QJ:IFHK:IO3S:AEXL:ERHF:L5SN:RTR4:3L2A:4H5K:7FUM:N57O
WARNING: No swap limit support

$ uname -a
Linux moodle 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Additional details: The host is running on a VMWare VM.

Steps to reproduce:
Absolutely no idea. This just happened. Attaching to the container caused the terminal to freeze, so I tried stopping it. That's when I discovered this. Rebooting was of no use.

I have seen similar but distinctly different issues #10589, #12738

**Comment by mountkin** [comment] 2015-07-22 11:39
Perhaps the docker daemon crashed when you ran `docker stop` or `docker kill`.
Please take a look at `/var/log/upstart/docker.log` and search "panic".

**Comment by phanimahesh** [comment] 2015-07-22 17:50
Thanks, I found these interesting lines in the log. They reflect my failed attempts at killing, stopping and attaching, and appear to have stacktraces.

On a sidenote, why on earth are colorcodes written to log? It was a mess, I had to clean it up with 
`sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"` to make it readable.

```
INFO[208799] POST /v1.19/containers/loving_shockley/stop?t=10
INFO[208809] Container 2e251726fc6fa080f4a6d15ca3a7886eae2d82ccc8b0d1ba4a7bdc08aa4108b2 failed to exit within 10 seconds of SIGTERM - using the force
INFO[208819] Container 2e251726fc6f failed to exit within 10 seconds of kill - trying direct SIGKILL
INFO[211817] GET /v1.19/containers/json
INFO[211825] POST /v1.19/containers/loving_shockley/stop?t=10
INFO[211825] Failed to send SIGTERM to the process, force killing
ERRO[211825] Handler for POST /containers/{name:.*}/stop returned error: Cannot stop container loving_shockley: [2] Container does not exist: container destroyed

ERRO[211825] HTTP Error                                    err=Cannot stop container loving_shockley: [2] Container does not exist: container destroyed
 statusCode=500
INFO[211834] GET /v1.19/containers/json?all=1
INFO[211840] POST /v1.19/containers/loving_shockley/stop?t=10
INFO[211840] Failed to send SIGTERM to the process, force killing
ERRO[211840] Handler for POST /containers/{name:.*}/stop returned error: Cannot stop container loving_shockley: [2] Container does not exist: container destroyed

ERRO[211840] HTTP Error                                    err=Cannot stop container loving_shockley: [2] Container does not exist: container destroyed
 statusCode=500
INFO[211886] Processing signal 'terminated'
INFO[211886] Failed to send SIGTERM to the process, force killing
ERRO[211886] Stop container 2e251726fc6fa080f4a6d15ca3a7886eae2d82ccc8b0d1ba4a7bdc08aa4108b2 with error: [2] Container does not exist: container destroyed
ERRO[211901] Force shutdown daemon
Waiting for /var/run/docker.sock
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
/var/run/docker.sock is up
INFO[0000] [graphdriver] using prior storage driver "aufs"
WARN[0001] Running modprobe bridge nf_nat failed with message: , error: exit status 1
WARN[0002] Your kernel does not support swap memory limit.
INFO[0002] Loading containers: start.
...ERRO[0002] Failed to load container c31bf1eabac9d25e4c4819baa76f2e58ea8227620fb57f3ccd028fed323b83ff: open /var/lib/docker/containers/c31bf1eabac9d25e4c4819baa76f2e58ea8227620fb57f3ccd028fed323b83ff/config.json: no such file or directory
...
INFO[0002] Loading containers: done.
INFO[0002] Daemon has completed initialization
INFO[0002] Docker daemon                                 commit=786b29d execdriver=native-0.2 graphdriver=aufs version=1.7.1
INFO[0003] GET /v1.19/containers/json
INFO[0017] GET /v1.19/containers/json?all=1
INFO[0017] GET /v1.19/containers/2e251726fc6fa080f4a6d15ca3a7886eae2d82ccc8b0d1ba4a7bdc08aa4108b2/json
INFO[0017] GET /v1.19/containers/31c334d2608001219120c50c89c3646cd340ae894df6db99de9027ff847b9b32/json
INFO[0017] GET /v1.19/containers/2e251726fc6fa080f4a6d15ca3a7886eae2d82ccc8b0d1ba4a7bdc08aa4108b2/json
INFO[0017] GET /v1.19/containers/loving_shockley/json
INFO[0017] POST /v1.19/containers/loving_shockley/resize?h=45&w=181
2015/07/22 02:31:38 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 49 [running]:
net/http.func·011()
        /usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/docker/daemon.(*Container).Resize(0xc2080ee1e0, 0x2d, 0xb5, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/container.go:516 +0x1cb
github.com/docker/docker/daemon.(*Daemon).ContainerResize(0xc2080a6ee0, 0xc2082666f7, 0xf, 0x2d, 0xb5, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/resize.go:9 +0x99
github.com/docker/docker/api/server.(*Server).postContainersResize(0xc208034740, 0xc2082666e7, 0x4, 0x7f860f211dc0, 0xc208260780, 0xc208237380, 0xc208257f50, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/server.go:1093 +0x2ca
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersResize)·fm(0xc2082666e7, 0x4, 0x7f860f211dc0, 0xc208260780, 0xc208237380, 0xc208257f50, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/server.go:1553 +0x7b
github.com/docker/docker/api/server.func·008(0x7f860f211dc0, 0xc208260780, 0xc208237380)
        /go/src/github.com/docker/docker/api/server/server.go:1501 +0xacd
net/http.HandlerFunc.ServeHTTP(0xc2081447c0, 0x7f860f211dc0, 0xc208260780, 0xc208237380)
        /usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080ab220, 0x7f860f211dc0, 0xc208260780, 0xc208237380)
        /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2080fb6e0, 0x7f860f211dc0, 0xc208260780, 0xc208237380)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2082605a0)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e
INFO[0017] POST /v1.19/containers/loving_shockley/attach?stderr=1&stdin=1&stdout=1&stream=1
INFO[0074] GET /v1.19/containers/json
INFO[0077] GET /v1.19/containers/json?all=1
INFO[0121] Processing signal 'terminated'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4e5d38]

goroutine 62 [running]:
github.com/docker/docker/daemon.(*containerMonitor).ExitOnNext(0x0)
        /go/src/github.com/docker/docker/daemon/monitor.go:70 +0x78
github.com/docker/docker/daemon.(*Container).KillSig(0xc2080ee1e0, 0xf, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/container.go:373 +0x32f
github.com/docker/docker/daemon.(*Container).killPossiblyDeadProcess(0xc2080ee1e0, 0xf, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/container.go:387 +0x58
github.com/docker/docker/daemon.(*Container).Stop(0xc2080ee1e0, 0xa, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/container.go:478 +0x93
github.com/docker/docker/daemon.func·020()
        /go/src/github.com/docker/docker/daemon/daemon.go:1006 +0x67
created by github.com/docker/docker/daemon.(*Daemon).Shutdown
        /go/src/github.com/docker/docker/daemon/daemon.go:1011 +0x3c0


goroutine 1 [select]:
main.shutdownDaemon(0xc2080a6ee0, 0xf)
        /go/src/github.com/docker/docker/docker/daemon.go:200 +0x386
main.mainDaemon()
        /go/src/github.com/docker/docker/docker/daemon.go:180 +0x10e5
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:93 +0x6b4

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 61 [runnable]:
sync.(*WaitGroup).Wait(0xc208262e60)
        /usr/local/go/src/sync/waitgroup.go:132 +0x169
github.com/docker/docker/daemon.(*Daemon).Shutdown(0xc2080a6ee0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:1014 +0x3ef
main.func·005()
        /go/src/github.com/docker/docker/docker/daemon.go:197 +0x33
created by main.shutdownDaemon
        /go/src/github.com/docker/docker/docker/daemon.go:199 +0x111

goroutine 11 [chan receive, 1 minutes]:
github.com/docker/docker/daemon.func·021()
        /go/src/github.com/docker/docker/daemon/debugtrap.go:17 +0x5c
created by github.com/docker/docker/daemon.setupSigusr1Trap
        /go/src/github.com/docker/docker/daemon/debugtrap.go:20 +0x18e

goroutine 36 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc20814f040)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c


goroutine 39 [chan receive]:
github.com/docker/docker/daemon.(*statsCollector).run(0xc208213380)
        /go/src/github.com/docker/docker/daemon/stats_collector.go:89 +0xb2
created by github.com/docker/docker/daemon.newStatsCollector
        /go/src/github.com/docker/docker/daemon/stats_collector.go:29 +0x116

goroutine 50 [chan receive, 1 minutes]:
github.com/docker/docker/daemon.(*Container).AttachWithLogs(0xc2080ee1e0, 0x7f860f212228, 0xc2080379c0, 0x7f860f211be8, 0xc2080379c0, 0x7f860f211be8, 0xc2080379c0, 0xc208270100, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/container.go:883 +0x36b
github.com/docker/docker/daemon.(*Daemon).ContainerAttachWithLogs(0xc2080a6ee0, 0xc2080ee1e0, 0xc208270390, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/attach.go:40 +0x42f
github.com/docker/docker/api/server.(*Server).postContainersAttach(0xc208034740, 0xc2082686c7, 0x4, 0x7f860f211dc0, 0xc208260960, 0xc208237450, 0xc2082701b0, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/server.go:1132 +0x614
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersAttach)·fm(0xc2082686c7, 0x4, 0x7f860f211dc0, 0xc208260960, 0xc208237450, 0xc2082701b0, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/server.go:1554 +0x7b
github.com/docker/docker/api/server.func·008(0x7f860f211dc0, 0xc208260960, 0xc208237450)
        /go/src/github.com/docker/docker/api/server/server.go:1501 +0xacd
net/http.HandlerFunc.ServeHTTP(0xc2080b46c0, 0x7f860f211dc0, 0xc208260960, 0xc208237450)
        /usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080ab220, 0x7f860f211dc0, 0xc208260960, 0xc208237450)
        /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2080fb6e0, 0x7f860f211dc0, 0xc208260960, 0xc208237450)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2082608c0)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 43 [chan receive]:
github.com/docker/docker/pkg/signal.func·002()
        /go/src/github.com/docker/docker/pkg/signal/trap.go:29 +0x8f
created by github.com/docker/docker/pkg/signal.Trap
        /go/src/github.com/docker/docker/pkg/signal/trap.go:55 +0x250

goroutine 51 [semacquire]:
sync.(*Cond).Wait(0xc2081d2c68)
        /usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).write(0xc2081d2c00, 0xc20828e000, 0x1, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:94 +0x244
io.(*PipeWriter).Write(0xc2080379e0, 0xc20828e000, 0x1, 0x8000, 0x1, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:161 +0x5b

io.Copy(0x7f860f2122b0, 0xc2080379e0, 0x7f860f211c10, 0xc2080379c0, 0x1, 0x0, 0x0)
        /usr/local/go/src/io/io.go:364 +0x278
github.com/docker/docker/daemon.func·008()
        /go/src/github.com/docker/docker/daemon/container.go:879 +0x10f
created by github.com/docker/docker/daemon.(*Container).AttachWithLogs
        /go/src/github.com/docker/docker/daemon/container.go:880 +0x2c6

goroutine 52 [semacquire, 1 minutes]:
sync.(*Cond).Wait(0xc2081d2cf0)
        /usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc2081d2cc0, 0xc208158000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc2080379f0, 0xc208158000, 0x400, 0x400, 0x98839b, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:134 +0x5b
github.com/docker/docker/pkg/ioutils.(*bufReader).drain(0xc2081d2d80)
        /go/src/github.com/docker/docker/pkg/ioutils/readers.go:116 +0x10e
created by github.com/docker/docker/pkg/ioutils.NewBufReader
        /go/src/github.com/docker/docker/pkg/ioutils/readers.go:86 +0x2f3

goroutine 53 [semacquire, 1 minutes]:
sync.(*Cond).Wait(0xc2081d2e70)
        /usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc2081d2e40, 0xc208158400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc208037a00, 0xc208158400, 0x400, 0x400, 0x98839b, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:134 +0x5b
github.com/docker/docker/pkg/ioutils.(*bufReader).drain(0xc2081d2f00)
        /go/src/github.com/docker/docker/pkg/ioutils/readers.go:116 +0x10e
created by github.com/docker/docker/pkg/ioutils.NewBufReader
        /go/src/github.com/docker/docker/pkg/ioutils/readers.go:86 +0x2f3

goroutine 54 [semacquire]:
sync.(*Cond).Wait(0xc2081d2968)
        /usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).write(0xc2081d2900, 0xc208296000, 0x1, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:94 +0x244
io.(*PipeWriter).Write(0xc208036e28, 0xc208296000, 0x1, 0x8000, 0x1, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:161 +0x5b
github.com/docker/docker/daemon.copyEscapable(0x7f860f2122b0, 0xc208036e28, 0x7f860f211b10, 0xc2080379d8, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/container.go:1014 +0x23f
github.com/docker/docker/daemon.func·010()
        /go/src/github.com/docker/docker/daemon/container.go:940 +0x260
created by github.com/docker/docker/daemon.attach
        /go/src/github.com/docker/docker/daemon/container.go:953 +0x457


goroutine 55 [semacquire]:
sync.(*Cond).Wait(0xc2081d2db0)
        /usr/local/go/src/sync/cond.go:62 +0x9e
github.com/docker/docker/pkg/ioutils.(*bufReader).Read(0xc2081d2d80, 0xc2081b4000, 0x8000, 0x8000, 0x0, 0x7f860f204f80, 0xc20802a0d0)
        /go/src/github.com/docker/docker/pkg/ioutils/readers.go:209 +0x158
io.Copy(0x7f860f211be8, 0xc2080379c0, 0x7f860f212328, 0xc2081d2d80, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:362 +0x1f6
github.com/docker/docker/daemon.func·012(0xda5fc0, 0x6, 0x7f860f211be8, 0xc2080379c0, 0x7f860f212280, 0xc2081d2d80)
        /go/src/github.com/docker/docker/daemon/container.go:970 +0x245
created by github.com/docker/docker/daemon.attach
        /go/src/github.com/docker/docker/daemon/container.go:980 +0x545

goroutine 56 [semacquire]:
sync.(*Cond).Wait(0xc2081d2f30)
        /usr/local/go/src/sync/cond.go:62 +0x9e
github.com/docker/docker/pkg/ioutils.(*bufReader).Read(0xc2081d2f00, 0xc208272000, 0x8000, 0x8000, 0x0, 0x7f860f204f80, 0xc20802a0d0)
        /go/src/github.com/docker/docker/pkg/ioutils/readers.go:209 +0x158
io.Copy(0x7f860f211be8, 0xc2080379c0, 0x7f860f212328, 0xc2081d2f00, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:362 +0x1f6
github.com/docker/docker/daemon.func·012(0xda5f80, 0x6, 0x7f860f211be8, 0xc2080379c0, 0x7f860f212280, 0xc2081d2f00)
        /go/src/github.com/docker/docker/daemon/container.go:970 +0x245
created by github.com/docker/docker/daemon.attach
        /go/src/github.com/docker/docker/daemon/container.go:981 +0x597

goroutine 57 [semacquire]:
sync.(*WaitGroup).Wait(0xc208282260)
        /usr/local/go/src/sync/waitgroup.go:132 +0x169
github.com/docker/docker/daemon.func·013(0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/container.go:984 +0x42
github.com/docker/docker/pkg/promise.func·001()
        /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x2f
created by github.com/docker/docker/pkg/promise.Go
        /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0xfb

goroutine 60 [chan receive]:
main.func·004()
        /go/src/github.com/docker/docker/docker/daemon.go:164 +0x6e
github.com/docker/docker/pkg/signal.func·001(0x7f860f204fa8, 0xc20825b428)
        /go/src/github.com/docker/docker/pkg/signal/trap.go:38 +0x1b6
created by github.com/docker/docker/pkg/signal.func·002
        /go/src/github.com/docker/docker/pkg/signal/trap.go:53 +0x13a
Waiting for /var/run/docker.sock
Waiting for /var/run/docker.sock
```

**Comment by mountkin** [comment] 2015-07-22 23:54
I noticed that if you try to resize a starting container it may panic because the "execConfig.ProcessConfig.Terminal" is a nil pointer. I'm able to reproduce the panic regarding to the "resize" API. Working on a patch to fix it.
I'll look into the other panic too.

**Comment by thaJeztah** [comment] 2015-08-09 21:55
@mountkin should this be closed now that https://github.com/docker/docker/pull/14600 was merged? And did the patch make it into the 1.8-rc?

**Comment by mountkin** [comment] 2015-08-10 02:45
@thaJeztah #14600 has nothing to do with this issue. Did you mean #14899 ?
#14899 fixed a panic that was caused by resizing a starting exec, which is shown in the backtrace of this issue, but it isn't in 1.8-rc.

In this issue  `docker stop`, `docker kill` all returned EOF, this might be related to #14199

**Comment by thaJeztah** [comment] 2015-08-10 06:04
@mountkin umf looks like I went through too many issues yesterday and had the wrong one on my clipboard. Yes, I meant that one 😙

**Comment by ChrisRut** [comment] 2015-09-14 00:55
Sorry for duplicate posting here, but I am not sure which ticket is more accurate for tracking this issue #14199 or this one?  Should these issues be merged?

Here are the details on my case:
```
$ docker stop af378d4a6c14
Post http:///var/run/docker.sock/v1.20/containers/af378d4a6c14/stop?t=10: EOF.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
Error: failed to stop containers: [af378d4a6c14]

$ docker kill af378d4a6c14
Post http:///var/run/docker.sock/v1.20/containers/af378d4a6c14/kill?signal=KILL: EOF.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
Error: failed to kill containers: [af378d4a6c14]
```

`docker -d` output:
```
$ docker -d
Warning: '-d' is deprecated, it will be removed soon. See usage.
WARN[0000] please use 'docker daemon' instead.
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] [graphdriver] using prior storage driver "aufs"
INFO[0000] Option DefaultDriver: bridge
INFO[0000] Option DefaultNetwork: bridge
WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.
, error: exit status 1
INFO[0000] Firewalld running: false
WARN[0000] Your kernel does not support swap memory limit.
INFO[0000] Loading containers: start.
............................
INFO[0000] Loading containers: done.
INFO[0000] Daemon has completed initialization
INFO[0000] Docker daemon                                 commit=0a8c2e3 execdriver=native-0.2 graphdriver=aufs version=1.8.2
INFO[0005] POST /v1.20/containers/af378d4a6c14/stop?t=10
2015/09/13 20:47:27 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 59 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/docker/daemon.(*containerMonitor).ExitOnNext(0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:73 +0x78
github.com/docker/docker/daemon.(*Container).KillSig(0xc2081410e0, 0xf, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:387 +0x3b5
github.com/docker/docker/daemon.(*Container).killPossiblyDeadProcess(0xc2081410e0, 0xf, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:405 +0x58
github.com/docker/docker/daemon.(*Container).Stop(0xc2081410e0, 0xa, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:498 +0x93
github.com/docker/docker/daemon.(*Daemon).ContainerStop(0xc2080a47e0, 0xc20822f697, 0xc, 0xa, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/stop.go:13 +0x12b
github.com/docker/docker/api/server.(*Server).postContainersStop(0xc2080a1180, 0xc20822f687, 0x4, 0x7f5af7a39ba0, 0xc2082e0fa0, 0xc20814fd40, 0xc2081eb1d0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:1087 +0x1e1
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersStop)·fm(0xc20822f687, 0x4, 0x7f5af7a39ba0, 0xc2082e0fa0, 0xc20814fd40, 0xc2081eb1d0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:1668 +0x7b
github.com/docker/docker/api/server.func·008(0x7f5af7a39ba0, 0xc2082e0fa0, 0xc20814fd40)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:1614 +0xc8f
net/http.HandlerFunc.ServeHTTP(0xc2081dc700, 0x7f5af7a39ba0, 0xc2082e0fa0, 0xc20814fd40)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208146910, 0x7f5af7a39ba0, 0xc2082e0fa0, 0xc20814fd40)
	/usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2081c8a80, 0x7f5af7a39ba0, 0xc2082e0fa0, 0xc20814fd40)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2082e0f00)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
INFO[0009] POST /v1.20/containers/af378d4a6c14/kill?signal=KILL
2015/09/13 20:47:32 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 60 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/docker/daemon.(*containerMonitor).ExitOnNext(0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:73 +0x78
github.com/docker/docker/daemon.(*Container).KillSig(0xc2081410e0, 0x9, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:387 +0x3b5
github.com/docker/docker/daemon.(*Container).killPossiblyDeadProcess(0xc2081410e0, 0x9, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:405 +0x58
github.com/docker/docker/daemon.(*Container).Kill(0xc2081410e0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container.go:463 +0xdb
github.com/docker/docker/daemon.(*Daemon).ContainerKill(0xc2080a47e0, 0xc20822fc57, 0xc, 0x9, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/kill.go:17 +0xda
github.com/docker/docker/api/server.(*Server).postContainersKill(0xc2080a1180, 0xc20822fc47, 0x4, 0x7f5af7a39ba0, 0xc2082e1360, 0xc20814fe10, 0xc2081eb710, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:300 +0x510
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersKill)·fm(0xc20822fc47, 0x4, 0x7f5af7a39ba0, 0xc2082e1360, 0xc20814fe10, 0xc2081eb710, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:1663 +0x7b
github.com/docker/docker/api/server.func·008(0x7f5af7a39ba0, 0xc2082e1360, 0xc20814fe10)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:1614 +0xc8f
net/http.HandlerFunc.ServeHTTP(0xc208181dc0, 0x7f5af7a39ba0, 0xc2082e1360, 0xc20814fe10)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208146910, 0x7f5af7a39ba0, 0xc2082e1360, 0xc20814fe10)
	/usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2081c8a80, 0x7f5af7a39ba0, 0xc2082e1360, 0xc20814fe10)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2082e12c0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
```

docker version/docker info/uname:
```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:16:50 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:16:50 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 11
Images: 277
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 299
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-40-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 31.12 GiB
Name: chris-lxc
ID: SZFA:FDZD:OLS6:7HZ7:XVFV:MXEJ:QGZQ:DRD6:RSCL:PGYY:PCTO:LTNY
WARNING: No swap limit support

$ uname -a
Linux chris-lxc 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by icecrime** [comment] 2016-09-10 02:44
Thank you for your report. I'm sorry the issue didn't get much attention recently: can you please test again with the latest version of Docker and let us know if this is still an issue? Thanks!

**Comment by phanimahesh** [comment] 2016-09-12 10:41
I've moved on and do not have that container around anymore. Feel free to close this if no one else can reproduce or follow up.

**Comment by cpuguy83** [comment] 2016-09-12 13:11
Going to go ahead and close since this has all been completely rewritten in 1.11 and the mentioned code doesn't exist anymore, or was fixed (`resize` fixed, `ExitOnNext` is re-written).

**Closed by cpuguy83** 2016-09-12 13:11 UTC
Labels: area/runtime, kind/bug, version/1.7
