### ISSUE TITLE
[1.11.0] Cannot start a container because of oci runtime error (exit status 1)

### ISSUE THREAD

**Issue by mattgiles** [docker/docker#22108] opened 2016-04-18 01:48 UTC
Copying the "[early-docker](https://github.com/coreos/coreos-overlay/blob/master/app-emulation/docker/files/early-docker.service)" pattern from CoreOS, I run two different docker daemons on each node in a docker swarm cluster. An "early" docker for things like swarm membership and log aggregation, and a "standard" daemon, which is exposed and advertised to the cluster.

Pattern has worked without modification through the last couple docker releases. When I bumped to version 1.11.0, the early docker daemon failed with an oci runtime error similar to the one outlined below. The other daemon continues to behave as expected.

I attempted to mend by running a separate, "early" containerd process. But the early docker daemon is still unable to run containers.

Behavior on the machine is: `docker ps` hangs, attempting to restart one of the stopped containers fails with:

```
Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exit status 1"
Error: failed to start containers: swarm-manager
```

Is this just a config error?

**Output of `docker -H unix:///var/run/early-docker.sock version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker -H unix:///var/run/early-docker.sock info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 3
Server Version: 1.11.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: null host
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: ip-10-112-1-109
ID: OCWX:T2C2:IDVK:4OYA:XZOV:2FRI:2ONQ:CSDS:DS7M:LWSZ:KOMQ:LOU5
Docker Root Dir: /var/lib/early-docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 40
 Goroutines: 57
 System Time: 2016-04-17T23:21:08.862878535Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Output of `cat /etc/systemd/system/early-containerd.service`:**
```
[Unit]
Description=Early Containerd Daemon
Documentation=https://containerd.tools
After=early-containerd.socket
Requires=early-containerd.socket

[Service]
Restart=on-failure
RestartSec=5
MountFlags=slave
LimitNOFILE=65536
LimitNPROC=65536
ExecStart=/usr/bin/docker-containerd --debug \
--listen /var/run/early-containerd.sock \
--runtime docker-runc \
--state-dir /run/early-containerd
```

**Output of `cat /etc/systemd/system/early-docker.service`:**
```
[Unit]
Description=Early Docker Application Container Engine
Documentation=http://docs.docker.com
After=early-docker.socket
Requires=early-docker.socket

[Service]
Restart=on-failure
RestartSec=5
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
ExecStart=/usr/bin/docker daemon --debug \
--bridge=none \
--containerd /var/run/early-containerd.sock \
--exec-opt native.cgroupdriver=systemd \
--graph=/var/lib/early-docker \
--host unix:///var/run/early-docker.sock \
--ip-masq=false \
--iptables=false \
--pidfile=/var/run/early-docker.pid \
--storage-driver overlay
```

**Output of `journalctl -u early-containerd`:**
```
-- Logs begin at Sun 2016-04-17 22:47:36 UTC, end at Sun 2016-04-17 22:52:05 UTC. --
Apr 17 22:50:03 ip-10-112-1-109 systemd[1]: Stopped Early Containerd Daemon.
Apr 17 22:50:03 ip-10-112-1-109 systemd[1]: Started Early Containerd Daemon.
Apr 17 22:50:03 ip-10-112-1-109 docker-containerd[1773]: time="2016-04-17T22:50:03Z" level=debug msg="containerd: read past events" count=0
Apr 17 22:50:03 ip-10-112-1-109 docker-containerd[1773]: time="2016-04-17T22:50:03Z" level=debug msg="containerd: supervisor running" cpus=2 memory=3950 runtime=docker-runc runtimeArgs=[] stateDir="/run/early-containerd"
Apr 17 22:50:03 ip-10-112-1-109 docker-containerd[1773]: time="2016-04-17T22:50:03Z" level=debug msg="containerd: grpc api on /var/run/early-containerd.sock"
Apr 17 22:50:11 ip-10-112-1-109 docker-containerd[1773]: time="2016-04-17T22:50:11Z" level=error msg="containerd: start container" error="oci runtime error: exit status 1" id=f878475e8aba051024b4ac4619967e44719cfe7347156a6adee
Apr 17 22:50:11 ip-10-112-1-109 docker-containerd[1773]: time="2016-04-17T22:50:11Z" level=error msg="containerd: start container" error="oci runtime error: exit status 1" id=0f25408c609efb0d138d3ae9812a675afc846b9f7efb776012c
Apr 17 22:50:11 ip-10-112-1-109 docker-containerd[1773]: time="2016-04-17T22:50:11Z" level=error msg="containerd: start container" error="oci runtime error: exit status 1" id=058eb8ba42da55557130f6c5178def323c29fc317fd8c677473
```

**Comment by mlaventure** [comment] 2016-04-18 16:40
From the journal it looks like containerd is failing to start 3 containers. Could you share their configurations?

**Comment by tonistiigi** [comment] 2016-04-18 16:45
`MountFlags=slave` could be causing this. Please try with `MountFlags=shared`. Other thing to try is resetting the `--exec-root` option also if you use different graph directory. If two docker daemons use same exec-root their event handling from containerd may not work correctly.

**Comment by mattgiles** [comment] 2016-04-18 20:34
Switching to `MountFlags=shared` and resetting `--exec-root` appears to have solved the first error, but revealed a new one:

```
Apr 18 20:02:02 ip-10-112-1-22 docker-containerd[4174]: time="2016-04-18T20:02:02Z" level=error msg="containerd: start container" error="oci runtime error: could not synchronise with container process: stat /sys/fs/cgroup/systemd/system.slice/early-containerd.service/system.slice: no such file or directory" id=0325d43095bbed3078a38ced3dca6a441005a63d2e7871ad2aaaa5914c1763e6
```

If I then remove the `--exec-opt` that specifies systemd for the cgroupdriver, everything appears to run correctly.

**Comment by mlaventure** [comment] 2016-04-18 21:54
@mattgiles since you're running the daemon in debug mode you should have a line akin to `createSpec: cgroupsPath: ...` in the log. Could you report it please?

**Comment by mlaventure** [comment] 2016-04-19 20:14
@mattgiles 

I figured it out.

Since you're using `systemd` **AND** starting `containerd` manually you also have to pass it (i.e. `containerd`) the following option for `runc` to correctly interpret the `cgroupsPath` generated by `docker`: `--runtime-args "--systemd-cgroup=true"`

**Comment by mattgiles** [comment] 2016-04-20 01:27
Beautiful. Will test it out. (Also: I didn't see a `createSpec: cgroupsPath` logline generated before).

**Comment by thaJeztah** [comment] 2016-04-20 13:37
ping @cyphar @runcom not sure if this affects you as well (since I think you were planning to put containerd in a separate unit-file)

**Comment by cyphar** [comment] 2016-04-20 13:42
We ship with `MountFlags=shared` on SUSE, because of a similar (but slightly different) issue. We haven't run into problems with `cgroupsPath` in our testing, which is a little bit worrying. I'll run some tests and update our packages. Thanks @thaJeztah!

**Comment by mlaventure** [comment] 2016-04-22 00:48
@mattgiles did it work for you? 

Closing this for now, assuming it did. Feel free to re-open if it didn't.

**Closed by mlaventure** 2016-04-22 00:48 UTC
Labels: priority/P2

**Comment by mattgiles** [comment] 2016-04-25 16:49
@miaventure took me a minute to come back to this, but all works: thanks kindly.

**Comment by trungdq88** [comment] 2016-08-28 03:06
I had this error. The cause was I have a wrong path in `docker-compose.yml` in `volumes` key:

```
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../build/main:/code # <-- ../build/main is not exists!
```

Correct the path and everything works again. Wish the error log was clearer.
