### ISSUE TITLE
Flaky Test: DockerSuite.TestKillWithStopSignalWithDifferentSignalShouldKeepRestartPolicy

### ISSUE THREAD

**Issue by tophj-ibm** [docker/docker#28033] opened 2016-11-03 15:57 UTC
Seen failing on master, and z

```sh
 ----------------------------------------------------------------------
 FAIL: docker_cli_kill_test.go:77: DockerSuite.TestKillWithStopSignalWithDifferentSignalShouldKeepRestartPolicy
 
 docker_cli_kill_test.go:89:
     // Restart policy should still be in place, so it should be still running
     c.Assert(waitRun(cid), check.IsNil)
 ... value *errors.errorString = &errors.errorString{s:"condition \"\"false\" == \"true\"\" not true in time"} ("condition \"\"false\" == \"true\"\" not true in time")
 
 
 ----------------------------------------------------------------------
```

**Comment by tophj-ibm** [comment] 2016-11-03 20:45
ping @michael-holzheu

**Comment by michael-holzheu** [comment] 2016-11-09 16:20
@tophj-ibm Thanks for hint. ping @ddingel

**Comment by tophj-ibm** [comment] 2016-11-09 16:42
It might be worth adding a zipped version of the test-integration-cli in bundles as an artifact for the jenkins build like is done on the other builds so then other people can look at them.

ping @mikedougherty, I don't want to change the jenkins scripts to upload things without your permission 😄

**Comment by michael-holzheu** [comment] 2016-11-09 17:46
The testcase DockerSuite.TestKillWithStopSignalWithDifferentSignalShouldKeepRestartPolicy confuses me:

```
func (s *DockerSuite) TestKillWithStopSignalWithDifferentSignalShouldKeepRestartPolicy(c *check.C) {
	// Cannot port to Windows - does not support signals int the same way as Linux does
	testRequires(c, DaemonIsLinux)
	out, _ := dockerCmd(c, "run", "-d", "--stop-signal=CONT", "busybox", "top")
	cid := strings.TrimSpace(out)
	c.Assert(waitRun(cid), check.IsNil)

	// Let's docker send a TERM signal to the container
	// It will kill the process, but not disable the restart policy
	dockerCmd(c, "kill", "-s", "TERM", cid)

	// Restart policy should still be in place, so it should be still running
	c.Assert(waitRun(cid), check.IsNil)
}
```

As the comment correctly says the init process "busybox top" is killed by SIGTERM. Isn't the container automatically killed when its init process dies?

And I don't understand the comment "Restart policy should still be in place". As we don't explicitly set a restart policy and the default policy is "no", the container should not be restarted.

So to me the testcase looks wrong.

ping @vdemeester Perhaps I am missing something? Could you explain since you commited d2e64247e6dfd3257a7d015890aa2f168ff643a0?

**Comment by michael-holzheu** [comment] 2016-11-09 18:25
After short discussion with @ddingel: Perhaps just a "restart=always" is missing for the testcase?

**Comment by tophj-ibm** [comment] 2016-11-09 18:42
Seems logically, but if that's the case I'm not sure how the test would be passing currently on everything else.

**Comment by ddingel** [comment] 2016-11-09 18:56
@tophj-ibm if I understand waitRun correctly it will return immediately on success.
So from my understanding there could be a small race window between delivering the signal with docker kill actually terminating the container. If in that window we check waitRun everything will look good, right?

@vdemeester maybe waitRun isn't the best option, so before checking the status of the container the test should wait for some time?

**Comment by tophj-ibm** [comment] 2016-11-09 19:27
@ddingel: good catch, I threw in a sleep statement between them and sure enough it failed without the restart policy active. 

I can think of a couple of ways to fix this, so I'll open up a PR for this unless one of you wanted to.

**Comment by ddingel** [comment] 2016-11-09 19:42
@tophj-ibm so there is:
- a fix so that this test case will fail reproducible
- some fixes for other test cases which might have the same underlying problem, maybe it is worth to introduce a function like waitRunAtLeast?
- a fix for this test case for restart policy

So depending on what you want to fix or take care of I would pick up the remaining. Also I have no problem if you decide to take care of all :).

**Comment by mikedougherty** [comment] 2016-11-09 19:52
> It might be worth adding a zipped version of the test-integration-cli in bundles as an artifact for the jenkins build like is done on the other builds so then other people can look at them.

on the [Docker-PRs](https://jenkins.dockerproject.org/job/Docker-PRs/) job (aka the "janky" status context), `bundles.tar.gz` is currently populated with files returned from this `find` command:

```
find bundles -name '*.log' -o -name '*.prof' -o -name integration.test
```

is there more that should archived? i think the entire directory was pretty large and we didn't want to give up the storage for stuff that would be rarely used (binaries probably).

---
> ping @mikedougherty, I don't want to change the jenkins scripts to upload things without your permission 😄

i don't care, they're not my scripts ;)

**Comment by tophj-ibm** [comment] 2016-11-09 19:55
@mikedougherty oh this would be just adding that command and uploading the results to the master z job.

**Comment by tophj-ibm** [comment] 2016-11-09 20:03
@ddingel yes I can get all of them.

**Comment by mikedougherty** [comment] 2016-11-09 20:04
@tophj-ibm oh i see. sorry, i didn't quite gather the entire context. that sounds reasonable and straightforward. IMO it would be appropriate if someone else took care of it (you, perhaps? not sure who's best) -- i'd rather empower people and not be a bottleneck. that being said, i can take the task if necessary.

**Comment by tophj-ibm** [comment] 2016-11-09 20:27
@mikedougherty yeah I can update it, I just wanted to double check it was fine with you.

**Comment by vdemeester** [comment] 2016-11-09 21:22
:scream_cat: you are right, I think a `--restart=always` is missing :scream_cat: How did I miss that :sweat_smile: This test is just plain wrong, my bad :scream: 
@tophj-ibm @ddingel feel free to open a PR to fix it, thanks a lot 👼

**Closed** 2016-11-10 09:51 UTC
Labels: area/testing
