### ISSUE TITLE
Inconsistent Size in image JSON

### ISSUE THREAD

**Issue by titanous** [docker/docker#5968] opened 2014-05-21 17:18 UTC
`Size` is capitalized and always `0`, but there is an `x-docker-size` header that is set.

```text
$ curl -vsH "Accept: application/json" -H "Authorization: Token signature=004020737ace8079d2c73bbed856c84e2df100de,repository="flynn/slugbuilder",access=read" https://cdn-registry-1.docker.io/v1/images/4a24a8c25c277462c7b7b7899c08875515ab0123333a822006ca232e7ab9da22/json | jq .
...
< HTTP/1.1 200 OK
< Server: cloudflare-nginx
< Date: Wed, 21 May 2014 17:15:43 GMT
< Content-Type: application/json
< Content-Length: 1507
< Connection: keep-alive
< Set-Cookie: __cfduid=daba9bb08762bf11d5b4b467c1e11c32d1400692542999; expires=Mon, 23-Dec-2019 23:50:00 GMT; path=/; domain=.docker.io; HttpOnly
< x-docker-checksum: sha256:47acabf396837d9960a32245b965d33f59620c269edbd6abf160123e5d5ad61b
< expires: Thu, 21 May 2015 17:15:43 GMT
< last-modified: Thu, 01 Jan 1970 00:00:00 GMT
< pragma: no-cache
< cache-control: public, max-age=31536000
< x-docker-size: 180
< x-docker-registry-version: 0.6.7
< x-docker-registry-config: prod
< CF-RAY: 12e26ae9b9e307d3-MIA

{
  "Size": 0,
  "os": "linux",
  "architecture": "amd64",
  "id": "4a24a8c25c277462c7b7b7899c08875515ab0123333a822006ca232e7ab9da22",
  "parent": "50b6a1e88daa593314f3369f1fd50f4cec9f8cc7bd709b5c5773579ed3f2b44d",
  "created": "2014-05-12T19:56:01.984015884Z",
  "container": "b4bc7059061c4becfb9fc37571d22f970a780f462a8cb16f50c564e049dba9bb",
  "container_config": {
...
```

**Comment by jfrazelle** [comment] 2015-02-11 00:13
@stevvooe is this fixed in registry v2 api 
re: https://github.com/docker/docker/issues/9015

**Comment by stevvooe** [comment] 2015-02-11 00:34
@jfrazelle Yes. The size is reported for all api responses as `Content-Length`, avoiding inconsistencies. This can be retrieved with HEAD request to the layer resource if its required before downloading.

We are also discussing the details of size reporting for manifest dependencies in docker/distribution#62, which I believe @titanous is familiar with.

**Comment by jfrazelle** [comment] 2015-02-11 00:38
so can I close this as a dupe of #9105?
if its ok w @titanous

**Comment by titanous** [comment] 2015-02-11 00:41
SGTM

**Closed** 2015-02-11 00:45 UTC
