### ISSUE TITLE
docker network list API doesn't contain containers on swarms overlay network

### ISSUE THREAD

**Issue by realityone** [docker/docker#29848] opened 2017-01-03 14:01 UTC
Hi there, 

I found network list API will miss `Containers` field on swarm overlay network.
But a bridge network has `Containers` field correctly.

![wx20170103-215752](https://cloud.githubusercontent.com/assets/4059040/21609854/b16de8ac-d1ff-11e6-9487-d3c6d17f7445.png)

And overlay network's `Containers` field will be viewed at `/networks/{id:.+}` API.

![2017-01-03 9 57 18](https://cloud.githubusercontent.com/assets/4059040/21609835/9ac37c34-d1ff-11e6-9df6-b79dbb362068.png)

I can reproduce on docker `1.12.5` and `1.13.0-rc4`.

Here is the docker info on the node I captured picture before.

```
[realityone@rEimu ~]$ docker info
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: 3mpw0by6khlj5sunilmydta0v
 Is Manager: true
 ClusterID: 06sovtbv2ccxmshefri8ymxlp
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.2.144
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.4 MiB
Name: dce2-dev-6
ID: UBPD:Q62O:BFAL:GHLC:P7G6:2PF3:2FMK:XHRD:KEEE:AVCJ:PAR5:JER7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8
```

**Comment by thaJeztah** [comment] 2017-01-03 14:21
Thanks for reporting. This is a known limitation currently for swarm mode overlay networks. There is an issue tracking this already (with some additional information); https://github.com/docker/docker/issues/24186

I'll close this issue, because it's a duplicate of https://github.com/docker/docker/issues/24186, but please subscribe to that issue to stay informed on updates

**Closed by thaJeztah** 2017-01-03 14:21 UTC
Labels: area/networking
