### ISSUE TITLE
Unable to start container on docker 1.9.0: container already connected to network bridge

### ISSUE THREAD

**Issue by delfuego** [docker/docker#17760] opened 2015-11-06 15:49 UTC
I have a simple Docker container (running the stock grafana/grafana image), and it ran perfectly on Docker 1.8.3; after upgrade to Docker 1.9.0, it will not start:

```
$ docker run --name grafana -v /data/grafana:/var/lib/grafana -e "GF_SERVER_ROOT_URL=https://fr-s-ccr-dock1.example.gov/grafana/" -e "GF_SECURITY_ADMIN_PASS=*********" -e "GF_USERS_ALLOW_SIGN_UP=false" -e "GF_AUTH_BASIC_ENABLED=false" -e "GF_SMTP_ENABLED=true" -e "GF_SMTP_HOST=mailfwd.example.gov:25" -e "GF_SMTP_FROM_ADDRESS=levineja@example.gov" --link statsd --restart always -d grafana/grafana:2.1.3
37ff3996556b3301316a6cf8ddf7090f5ffe4c2a0bcd890561ab6814df116579
Error response from daemon: Cannot start container 37ff3996556b3301316a6cf8ddf7090f5ffe4c2a0bcd890561ab6814df116579: container already connected to network bridge
```

I've tried to remove (`docker rm grafana`) and rebuild the container, to no avail; there's nothing I can figure out to do to get this container to start.

Thoughts? Do I just need to downgrade to 1.8.3 until this issue is fixed?

**Comment by delfuego** [comment] 2015-11-06 15:51
Oh, the output from `docker inspect`:

```
$ docker inspect grafana
[
{
    "Id": "37ff3996556b3301316a6cf8ddf7090f5ffe4c2a0bcd890561ab6814df116579",
    "Created": "2015-11-06T15:43:25.22652276Z",
    "Path": "/usr/sbin/grafana-server",
    "Args": [
        "--config=/etc/grafana/grafana.ini",
        "cfg:default.paths.data=/var/lib/grafana",
        "cfg:default.paths.logs=/var/log/grafana"
    ],
    "State": {
        "Status": "created",
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": 128,
        "Error": "container already connected to network bridge",
        "StartedAt": "0001-01-01T00:00:00Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "8892acd8f34d1e9273e5b4cde721c3ef3c4143028f366b90a6ecfda9762343f5",
    "ResolvConfPath": "",
    "HostnamePath": "",
    "HostsPath": "",
    "LogPath": "",
    "Name": "/grafana",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/data/grafana:/var/lib/grafana"
        ],
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {},
        "Links": [
            "/statsd:/grafana/statsd"
        ],
        "PublishAllPorts": false,
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "always",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [
        {
            "Source": "/data/grafana",
            "Destination": "/var/lib/grafana",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "c24a63d7f188ff1a19f6511225d0c74cf1acae79dc31226b8405dbd4998df32e",
            "Source": "/data/docker/volumes/c24a63d7f188ff1a19f6511225d0c74cf1acae79dc31226b8405dbd4998df32e/_data",
            "Destination": "/etc/grafana",
            "Driver": "local",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "572d33717c08a21d2779bd8e9d88841edd74656ed7c5e111b6a548514dee1615",
            "Source": "/data/docker/volumes/572d33717c08a21d2779bd8e9d88841edd74656ed7c5e111b6a548514dee1615/_data",
            "Destination": "/var/log/grafana",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "37ff3996556b",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "3000/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "GF_SERVER_ROOT_URL=https://fr-s-ccr-dock1.example.gov/grafana/",
            "GF_SECURITY_ADMIN_PASS=*********",
            "GF_USERS_ALLOW_SIGN_UP=false",
            "GF_AUTH_BASIC_ENABLED=false",
            "GF_SMTP_ENABLED=true",
            "GF_SMTP_HOST=mailfwd.example.gov:25",
            "GF_SMTP_FROM_ADDRESS=levineja@example.gov",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": null,
        "Image": "grafana/grafana:2.1.3",
        "Volumes": {
            "/etc/grafana": {},
            "/var/lib/grafana": {},
            "/var/log/grafana": {}
        },
        "WorkingDir": "/usr/share/grafana",
        "Entrypoint": [
            "/usr/sbin/grafana-server",
            "--config=/etc/grafana/grafana.ini",
            "cfg:default.paths.data=/var/lib/grafana",
            "cfg:default.paths.logs=/var/log/grafana"
        ],
        "OnBuild": null,
        "Labels": {},
        "StopSignal": "SIGTERM"
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": null,
        "SandboxKey": "",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "MacAddress": "",
        "Networks": {
            "bridge": {
                "EndpointID": "",
                "Gateway": "",
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": ""
            }
        }
    }
}
]
```

**Comment by mrjana** [comment] 2015-11-06 15:59
@delfuego Can you please provide your docker logs? Did this happen immediately after you upgraded to 1.9 or did you restart the daemon a few times and then run this container?

If you want to make progress the following can be used as a workaround:
1. Stop docker daemon
2. sudo rm /var/lib/docker/network/files/local-kv.db
3. Start docker daemon
4. Recreate your container

**Comment by delfuego** [comment] 2015-11-06 16:04
How do you want me to provide the logs? Happy to cut-and-paste the 200 lines of the most recent log here, or however you want.

I'll try your workaround now.

**Comment by delfuego** [comment] 2015-11-06 16:06
Workaround worked perfectly. Happy to provide the log from when the daemon was in the failing condition, however you'd prefer, if it's still useful.

**Comment by mrjana** [comment] 2015-11-06 16:08
@delfuego Glad you can make progress with the workaround. I would still like the logs to understand what went wrong and it would be preferable to see the whole logs. So if you can create a Gist document in github and post the link here that would be great.

**Comment by delfuego** [comment] 2015-11-06 16:20
@mrjana The log file is here: https://gist.github.com/delfuego/52bb982fb4d82cd6e93e

Let me know if you need anything more.

**Comment by hugoliv** [comment] 2015-11-07 16:59
+1 for the workaround. Thx.

**Comment by skyred** [comment] 2015-11-08 04:18
I can confirm the workaround in https://github.com/docker/docker/issues/17760#issuecomment-154447839 works.

**Comment by jebw** [comment] 2015-11-08 18:47
Just had this with a docker-machine created vm on a macbook, created as a conversion from boot2docker, after upgrading to docker 1.9.

Workaround solved the problem for me as well

**Comment by apeltzer** [comment] 2015-11-10 09:38
Same problem, here,  workaround solved the problem. Didn't even have to recreate the image or rebuild. Thanks man!

**Comment by benjamin-thomas** [comment] 2015-11-10 10:43
Same for me, workaround solved the problem.

Encountered the bug on an archlinux (dev) machine, after issuing a package update + restart.

Restarted the previously launched containers fine but couldn't create new ones.

**Comment by daddykotex** [comment] 2015-11-10 16:38
I was able to reproduce the error. Here are the steps I did to have the error:
```
create a container 'test'
create a container 'test-linked' that is linked to test with --link
start 'test-linked' before 'test', an error occur as 'test' is not started, this is normal
start 'test'
start 'test-linked', an error occur: container already connected to network bridge.
```

My stup is El Capitan with the newest stable release of docker and docker-machine:
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   76d6bc9
 Built:        Tue Nov  3 21:18:00 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment] 2015-11-10 16:51
Thanks @daddykotex I was able to reproduce on 1.9.0 with your steps

```
docker create --name test nginx
4d1cf6d36c930f2729803c47d0958a0dfb3f433b4e51aa125de13c3c9bb11130
docker run --name linked-container --link test nginx
Error response from daemon: Cannot start container 7d3a27f23f7f8655ad8430ec21f40ee3c7f8fc16c0d609a3734d2ad1137937c6: Cannot link to /test, as it does not belong to the default network
docker start test
test
docker start linked-container
Error response from daemon: Cannot start container linked-container: container already connected to network bridge
Error: failed to start containers: [linked-container]
```

**Comment by thaJeztah** [comment] 2015-11-10 16:52
ping @mrjana @mavenugo steps to reproduce this on 1.9.0 ^^

**Comment by daddykotex** [comment] 2015-11-10 16:53
Thanks to you and the whole team!

**Comment by mavenugo** [comment] 2015-11-10 17:39
@daddykotex @thaJeztah @delfuego I tried the docker master and I couldn't reproduce this issue. #17558 solved a related issue (but we didnt make it to 1.9.0 release).

Can you please try the master and confirm the behavior ?

**Comment by thaJeztah** [comment] 2015-11-10 17:53
@mavenugo confirmed, looks like this is resolved on master :+1:

**Comment by thaJeztah** [comment] 2015-11-10 18:02
@mavenugo do we need (or is there already) a test-case for the reproduction steps here? Given that https://github.com/docker/docker/pull/17558 solved another issue

**Comment by mavenugo** [comment] 2015-11-10 18:04
@thaJeztah we dont have test-case for this. but we could add one.

**Comment by mavenugo** [comment] 2015-11-10 21:19
Since this a dupe of #17558, shall we close this issue ?
@tiborvass @thaJeztah

**Comment by thaJeztah** [comment] 2015-11-10 21:29
A test would be nice, so that we don't regress at some point, but I'll give @tiborvass the final say here :smile:

**Comment by mavenugo** [comment] 2015-11-10 21:30
@thaJeztah yes. we can add a test. but that is not going to solve this problem :) or is the root-cause. they are unrelated to the issue I think.

**Comment by mavenugo** [comment] 2015-11-11 00:08
discussed with @tiborvass and we will close it now as it is resolved by #17558.
We will add test-cases to cover these scenarios.

**Closed by mavenugo** 2015-11-11 00:08 UTC
Labels: group/networking, kind/bug

**Comment by thaJeztah** [comment] 2015-11-11 00:31
Thanks @mavenugo

**Comment by zx1986** [comment] 2015-11-11 09:37
confirm the workaround in #17760 (comment) works in Ubuntu 14.04.3 LTS

**Comment by amirkrifa** [comment] 2016-09-20 08:15
Just had this issue after restarting the machine.

Here is the env:

- Ubuntu 14.04.3 LTS

Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

@mrjana Thx for this workaround. Works perfectly for me.

**Comment by thaJeztah** [comment] 2016-09-20 08:19
@amirkrifa as can be seen on this issue; this was a bug in 1.9.0 (which you're running), please update docker to 1.9.1 or higher

**Comment by Gcaufy** [comment] 2017-02-21 05:03
@thaJeztah 
still got the same issue in 1.9.1
```
$ ls /var/lib/docker/network/files/local-kv.db
ls: cannot access /var/lib/docker/network/files/local-kv.db: No such file or directory

$ docker-compose up
Starting legos_legosimage_1

ERROR: for legosimage  Cannot start service legosimage: Cannot start container 130db7da08243a038e23f8d5844fc40793bb2a43d2614332abf27cec278b144d: container already connected to network bridge
ERROR: Encountered errors while bringing up the project.

$ docker --version
Docker version 1.9.1, build db080c2
```

but this will work.
```
docker-compose --project-name test up
```

**Comment by thaJeztah** [comment] 2017-02-21 11:49
@Gcaufy hm. not sure what could cause that; problem is that docker 1.9.1 is EOL, and no longer maintained, so even if there's still an issue in docker 1.9.1, it won't be fixed in that release. I'd recommend upgrading to the current version.

**Comment by Gcaufy** [comment] 2017-02-21 12:11
k, thx
