### ISSUE TITLE
Getting error while removing untagged images

### ISSUE THREAD

**Issue by ravibhure** [docker/docker#21764] opened 2016-04-05 11:48 UTC
`docker version`:**

```
ravi@master:~$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64
```

** `docker info`:**

```
ravi@master:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 24
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 36
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.31 GiB
Name: master
ID: BNY3:YPBU:ZDLS:HPDC:4U52:K7XY:3PFD:JPXP:CQHK:UBBB:GMHV:36LB
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

Environment details: ```Physical```

```
ravi@master:~$ uname -a
Linux master 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
```

```
ravi@master:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.4 (jessie)
Release:        8.4
Codename:       jessie 
```

How reproducible: all the time.

Steps to Reproduce:
1) Build a images using Dockerfile 
2) docker images -a | awk '/^<none>/ {print $3}'
3) docker rmi $(docker images -a | awk '/^<none>/ {print $3}')

The above steps to reproduce the errors 

```
ravi@master:~$ docker images -a | awk '/^<none>/ {print $3}'
d6b8329d96a9
26883b9f3dda
bcbcc52f1cc5
b36c2e2616f5
f066d8737959
6c83ce080377
6e17ae4079c9
30c62d68ef0f
7ea015dcf6b1
aee6f3030942
c9945464bfba
ba4569b1ec8a
93f27912e9bf
52d2789dcd00
d23c706296ba
82088816eb97
8a1bb1abc10e
```

```
ravi@master:~$ docker rmi $(docker images -a | awk '/^<none>/ {print $3}')
Failed to remove image (d6b8329d96a9): Error response from daemon: conflict: unable to delete d6b8329d96a9 (cannot be forced) - image has dependent child images
Failed to remove image (26883b9f3dda): Error response from daemon: conflict: unable to delete 26883b9f3dda (cannot be forced) - image has dependent child images
Failed to remove image (b36c2e2616f5): Error response from daemon: conflict: unable to delete b36c2e2616f5 (cannot be forced) - image has dependent child images
Failed to remove image (bcbcc52f1cc5): Error response from daemon: conflict: unable to delete bcbcc52f1cc5 (cannot be forced) - image has dependent child images
Failed to remove image (f066d8737959): Error response from daemon: conflict: unable to delete f066d8737959 (cannot be forced) - image has dependent child images
Failed to remove image (aee6f3030942): Error response from daemon: conflict: unable to delete aee6f3030942 (cannot be forced) - image has dependent child images
Failed to remove image (6c83ce080377): Error response from daemon: conflict: unable to delete 6c83ce080377 (cannot be forced) - image has dependent child images
Failed to remove image (6e17ae4079c9): Error response from daemon: conflict: unable to delete 6e17ae4079c9 (cannot be forced) - image has dependent child images
Failed to remove image (7ea015dcf6b1): Error response from daemon: conflict: unable to delete 7ea015dcf6b1 (cannot be forced) - image has dependent child images
Failed to remove image (30c62d68ef0f): Error response from daemon: conflict: unable to delete 30c62d68ef0f (cannot be forced) - image has dependent child images
Failed to remove image (c9945464bfba): Error response from daemon: conflict: unable to delete c9945464bfba (cannot be forced) - image has dependent child images
Failed to remove image (52d2789dcd00): Error response from daemon: conflict: unable to delete 52d2789dcd00 (cannot be forced) - image has dependent child images
Failed to remove image (93f27912e9bf): Error response from daemon: conflict: unable to delete 93f27912e9bf (cannot be forced) - image has dependent child images
Failed to remove image (ba4569b1ec8a): Error response from daemon: conflict: unable to delete ba4569b1ec8a (cannot be forced) - image has dependent child images
Failed to remove image (d23c706296ba): Error response from daemon: conflict: unable to delete d23c706296ba (cannot be forced) - image has dependent child images
Failed to remove image (82088816eb97): Error response from daemon: conflict: unable to delete 82088816eb97 (cannot be forced) - image has dependent child images
Failed to remove image (8a1bb1abc10e): Error response from daemon: conflict: unable to delete 8a1bb1abc10e (cannot be forced) - image has dependent child images
```

I don't have any container running at the time
```
ravi@master:~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by ravibhure** [comment] 2016-04-05 11:55
Found the similar issues and it has been fixed,  but it won't

https://github.com/docker/docker/issues/18873 
https://github.com/docker/docker/pull/19266 
https://github.com/docker/docker/issues/20469

**Comment by HackToday** [comment] 2016-04-07 00:25
some untagged image did have `dependent child images`, I think you need inspect those images, and find if have dependent child images

**Comment by thaJeztah** [comment] 2016-04-07 07:09
Yes, this is not a bug; images can also be *intermediate layers* of an image; those layers/images are not tagged, but are still needed as parent for other images. To see untagged images that are no used by other images, use the "dangling" filter;

    docker images -a -f dangling=true

Or to remove those images;

    docker rmi $(docker images -aq -f dangling=true)

I'm going to close this issue, because this is not a bug, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-04-07 07:09 UTC

**Comment by epelc** [comment] 2016-09-29 17:47
I ran into this using docker version `1.12.1`.

I didn't have any dangling images, so @thaJeztah's suggestion did not work. But tagging the image and then trying to remove it worked.

**Comment by Sispheor** [comment] 2016-10-04 13:02
+1

**Comment by wnan42** [comment] 2016-11-21 20:52
I ran into the same problem in 1.12. The solution is pretty simple for me:

Instead of doing:
`docker rmi -f <imageID>`

just do:
`docker rmi -f <imageName>`
Then the output will be:
`Untagged: <imageName>`

Hope this can help.

**Comment by loretoparisi** [comment] 2017-03-29 09:46
@wnan42 If you try to force an image that has children you will get an error

```
Error response from daemon: conflict: unable to delete 3e4995471105 (cannot be forced) - image has dependent child images
```

**Comment by leenooks** [comment] 2017-04-21 03:18
I had images that I couldn't delete:
```
[root@shuttle ~]# docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
centos                                     <none>              970633036444        8 months ago        197MB

[root@shuttle ~]# docker rmi 970633036444
Error response from daemon: conflict: unable to delete 970633036444 (cannot be forced) - image has dependent child images
```

So I tagged the image:

```
[root@shuttle ~]# docker tag 970633036444 centos:del
```

And then deleted it:
```
[root@shuttle ~]# docker rmi centos:del
Untagged: centos:del
Untagged: centos@sha256:a66ffcb73930584413de83311ca11a4cb4938c9b2521d331026dad970c19adf4
```

This might help...

**Comment by truatpasteurdotfr** [comment] 2017-04-27 06:47
I had the same issue on:
```
docker-1.12.6-16.el7.centos.x86_64
...
[tru@hpe840g1-1 ~]$ sudo docker images
REPOSITORY                      TAG                            IMAGE ID            CREATED             SIZE
...
docker.io/ubuntu                <none>                         0ef2e08ed3fa        8 weeks ago         130 MB

[tru@hpe840g1-1 ~]$ sudo docker rmi  0ef2e08ed3fa
Error response from daemon: conflict: unable to delete 0ef2e08ed3fa (cannot be forced) - image has dependent child images
[tru@hpe840g1-1 ~]$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
<nothing>
[tru@hpe840g1-1 ~]$ sudo docker images -qf "dangling=true"
<nothing>
[tru@hpe840g1-1 ~]$ sudo docker tag 0ef2e08ed3fa ubuntu:del
[tru@hpe840g1-1 ~]$ sudo docker images
REPOSITORY                      TAG                            IMAGE ID            CREATED             SIZE
...
ubuntu                          del                            0ef2e08ed3fa        8 weeks ago         130 MB
docker.io/ubuntu                <none>                         0ef2e08ed3fa        8 weeks ago         130 MB

[tru@hpe840g1-1 ~]$ sudo docker rmi 0ef2e08ed3fa
Error response from daemon: conflict: unable to delete 0ef2e08ed3fa (cannot be forced) - image has dependent child images
[tru@hpe840g1-1 ~]$ sudo docker rmi ubuntu:del
Untagged: ubuntu:del
Untagged: docker.io/ubuntu@sha256:dd7808d8792c9841d0b460122f1acf0a2dd1f56404f8d1e56298048885e45535
[tru@hpe840g1-1 ~]$ sudo docker images
REPOSITORY                      TAG                            IMAGE ID            CREATED             SIZE
...
<gone!>
```

thanks

**Comment by thaJeztah** [comment] 2017-04-29 00:10
I'm locking the conversation on this issue, because this is not a bug, but have opened an issue to discuss a possible change to allow removing images with `--force`; https://github.com/moby/moby/issues/30722
