### ISSUE TITLE
Cannot interrupt via SIGINT (CMD+C Mac)

### ISSUE THREAD

**Issue by ronaldpetty** [docker/docker#25894] opened 2016-08-19 23:37 UTC
```
$ docker version
Client:
 Version:      1.12.1-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:35:53 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:35:53 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

```
docker version
Client:
 Version:      1.12.1-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:35:53 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7889dc7
 Built:        Fri Aug 12 18:35:53 2016
 OS/Arch:      linux/amd64
 Experimental: true
laptop:swagger-ui ronaldpetty$ docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 8
Server Version: 1.12.1-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.953 GiB
Name: moby
ID: BUAQ:BY63:IXPU:MMDP:Q4RQ:7S4F:HGER:DFM5:3YHI:4QVN:ZVBZ:SPTA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 35
 System Time: 2016-08-19T23:32:15.164398836Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: ronaldpetty
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

```
system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.6 (15G31)
      Kernel Version: Darwin 15.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Ronald’s MacBook Pro
      User Name: Ronald Petty (ronaldpetty)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 10 days 21:39
```

**Steps to reproduce the issue:**
1.  `docker run alpine:3.3 tail -f /dev/null`
2.  CMD+C or `docker kill --signal="SIGINT" <cid>`
3.  nothing happens (have to `docker stop` in another terminal.)

**Describe the results you received:**

Container does not stop.

**Describe the results you expected:**

Container stops.

**Comment by cpuguy83** [comment] 2016-08-22 16:09
This is expected behavior because `tail`, when run as pid 1, drops default signal handlers (as does most C programs).

Closing since this isn't a docker issue per-se, and is documented elsewhere.

**Closed by cpuguy83** 2016-08-22 16:09 UTC
Labels: version/1.12

**Comment by ronaldpetty** [comment] 2016-08-22 16:23
Thanks, I did not know that.
