### ISSUE TITLE
exec: "./bin/run.sh": stat ./bin/run.sh: no such file or directory

### ISSUE THREAD

**Issue by tomasmelin** [docker/docker#20432] opened 2016-02-18 07:41 UTC
When I have ran the following command:
>$ docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 -v /C/Users/tomme/docker-sonarqube:/opt/sonarqube sonarqube:latest

It does not start and once I attempt to start the container by using **docker start**
>$ docker start -a sonarqube
exec: "./bin/run.sh": stat ./bin/run.sh: no such file or directory
Error response from daemon: Container command not found or does not exist.

What is the problem here? 

**docker version:**
>$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      windows/amd64
>
Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

**docker info:**
>$ docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: NKSE:6GZL:N7AE:47Q5:HBAF:CERC:MHWZ:HWEC:QSVI:FTK5:P2E2:HRM3
Debug mode (server): true
 File Descriptors: 27
 Goroutines: 44
 System Time: 2016-02-18T07:42:34.839946757Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**Comment by thaJeztah** [comment] 2016-02-18 13:26
You're bind-mounting a volume over the `/opt/sonarqube` directory, and the image expects a `run.sh` to be present there; if there's no `run.sh` present in your `/C/Users/tomme/docker-sonarqube` directory, the image will fail to start.

See;
https://github.com/SonarSource/docker-sonarqube/blob/f13192265920c40f8a50ec55f7c2af7a412c4c88/5.3/Dockerfile#L5

and

https://github.com/SonarSource/docker-sonarqube/blob/f13192265920c40f8a50ec55f7c2af7a412c4c88/5.3/Dockerfile#L36-L38

I'm going to close this, because this is a support question, not a bug in Docker. I hope however, that the above information will help you further. Feel free to comment here after I've closed this issue

**Closed by thaJeztah** 2016-02-18 13:26 UTC

**Comment by tomasmelin** [comment] 2016-02-19 11:12
@thaJeztah Thank you for your response. Do you have a suggestion how I should write the command to avoid this issue?

**Comment by thaJeztah** [comment] 2016-02-19 13:03
@tomasmelin really depends; what's in your `sonarqube` directory that you need to bind-mount into the container? I don't have experience with sonarqube, but if you only need your `data` and/or `extensions` directories, you can use (multiple) more fine-grained volumes.

possibly something like;

```bash
docker run -d --name sonarqube -p 9000:9000 \
  -p 9092:9092 \
  -v /C/Users/tomme/docker-sonarqube/data:/opt/sonarqube/data \
  -v /C/Users/tomme/docker-sonarqube/extensions:/opt/sonarqube/extensions \
  sonarqube:latest
```

**Comment by tomasmelin** [comment] 2016-02-22 08:58
@thaJeztah I see what you mean. What I am trying to do is to "sync" the content in the container to the folders I have applied the *-v* flag upon, in order to be able to edit the files on the host which will then update the corresponding folders in the container, am I using the appropriate functionality of Docker?

**Comment by thaJeztah** [comment] 2016-02-22 09:15
@tomasmelin there's a difference between mounting "host" directories, and "volumes". When bind-mounting host-directories (i.e. `-v /some/path/on/my/host:/some/path/in/container`) you're telling Docker to use the files that are present on the host, and make them available inside the container. The files on the host take precedence here. Bind-mounting host-directories allows you to, for example, have a directory with configuration-files on the host, and use those inside the container.

By default, Docker will *not* copy files from inside the container to that directory, because you asked Docker for use the files that were present on the host.

If you're using a *volume* (yes, it's the same `-v` flag, so that can be confusing), for example, `-v a-name-for-my-volume:/some/path/in/container`, you're telling Docker to *create* a volume (or re-use the `a-name-for-my-volume` if it's been created before), and copy the files from `/some/path/in/container` to that volume the first time it's created.

With volumes, the files in the *container* will be used/copied.

**Comment by tomasmelin** [comment] 2016-02-22 10:21
I see, excellent explanation! 

Once I use your description (your 2nd approach since I find that is what I want) I receive the following output:

>"Mounts": [
   {
"Name": "docker-sonarqube-data",
"Source": "/mnt/sda1/var/lib/docker/volumes/docker-sonarqube-data/_data",
"Destination": "/opt/sonarqube/data",
"Driver": "local",
"Mode": "z",
"RW": true,
"Propagation": "rprivate"
},
{
    "Name": "docker-sonarqube-extensions",
    "Source": "/mnt/sda1/var/lib/docker/volumes/docker-sonarqube-extensions/_data",
    "Destination": "/opt/sonarqube/extensions",
    "Driver": "local",
    "Mode": "z",
    "RW": true,
    "Propagation": "rprivate"
},
{
    "Name": "docker-sonarqube-conf",
    "Source": "/mnt/sda1/var/lib/docker/volumes/docker-sonarqube-conf/_data",
    "Destination": "/opt/sonarqube/conf",
    "Driver": "local",
    "Mode": "z",
    "RW": true,
    "Propagation": "rprivate"
}
 ],

Is there a way I can change this path: `"/mnt/sda1/var/lib/docker/volumes/docker-sonarqube-data/_data"`?

Alternatively, go to it and view the files? As I understand it that path is on the Docker Virtual machine and my goal is to have that path in my /C/Users/tomme/ - folder.

**Comment by thaJeztah** [comment] 2016-02-22 10:52
@tomasmelin regular volumes are managed by docker, so not shared with your local machine. You *can* access/view them; the cleanest way is to start a one-off container that uses the same volumes, for example, 

    docker run -it --rm -v docker-sonarqube-extensions:/extensions ubuntu bash

that should give you an interactive session in a container, and you can see the files in `/extensions`.
if you really want the files to be available on your host machine, you could take a more creative approach, and share the volume using (e.g.) a samba server.

For example, have a look at https://hub.docker.com/r/svendowideit/samba/, and the instructions here; https://github.com/SvenDowideit/dockerfiles/tree/master/samba.

Also note that, If sonarqube initializes the "data" directory on first start (so it's able to run with an empty data-directory), you can still use a bind-mounted directory for the `data` directory, as I showed here; https://github.com/docker/docker/issues/20432#issuecomment-186205428

**Comment by jawadmadani** [comment] 2018-09-02 14:51
can someone help with this please, my pipeline that i created with BlueOcean is trying to create a container but getting the below error, appreciate it!


[alfalah_master-U5DW6VPJXH2DJ3S6ZSODLDXUFMGIFS3WD4P4KHD4QKDX6L2N2T6A@2] Running shell script
+ docker inspect -f . sonarqube
.
[Pipeline] withDockerContainer
Jenkins seems to be running inside container 3505b9b14522d0c335843a61dbe9b1fcc5ba03861b9bdf23f70da172925361f5
$ **`docker run -t -d -u 0:0 -w /var/jenkins_home/workspace/alfalah_master-U5DW6VPJXH2DJ3S6ZSODLDXUFMGIFS3WD4P4KHD4QKDX6L2N2T6A@2 --volumes-from 3505b9b14522d0c335843a61dbe9b1fcc5ba03861b9bdf23f70da172925361f5 -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** sonarqube cat`**
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified
**`java.io.IOException: Failed to run image 'sonarqube'. Error: docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./bin/run.sh\": stat ./bin/run.sh: no such file or directory": unknown.`**

**Comment by jawadmadani** [comment] 2018-09-02 14:54
@tomasmelin I am assuming you had a similar issue, I don't want to create the container manually as the pipeline doing that for me and deleting it afterwards. @thaJeztah thank you!

**Comment by DuffyScottC** [comment] 2019-09-26 16:12
After reading this thread, I've realized that I must have a fundamental misunderstanding of how the SonarQube docker container works. I would like all the analysis information that SonarQube stores to be persistent (i.e. when I shut down the docker container, it doesn't looks everything). Can anyone help me to understand how to accomplish this?
