### ISSUE TITLE
Container cannot send outbound traffic

### ISSUE THREAD

**Issue by djenriquez** [docker/docker#26023] opened 2016-08-25 19:28 UTC
**Output of `docker version`:**

```
Docker version 1.12.1, build 23cf638
```

**Output of `docker info`:**

```
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 54
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 483
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-93-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: ip-10-172-84-142
ID: C7P2:6MGV:YB4D:Q5VW:C6WM:DCKY:5TWT:CICU:RJSL:XVF5:QRZD:ACP5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- AWS EC2 instance

**Steps to reproduce the issue:**
1. SSH into the container
2. Run apt-get update

**Describe the results you received:**
We are finding containers that have no outbound traffic. For this issue specifically, we are using a private splunk-forwarder image that is run on a few hundred instances and we've thought to have been working flawlessly until recently, where we found a few that are not sending out logs.

We are able to ssh into the container and it shows that it is responsive, however we are unable to run any command that requires outbound traffic, like `apt-get update`. 

Running `apt-get update` gives:
```
root@applogs-eu-west-1-prod:/# apt-get update                                                                                                                                                                                          
0% [Connecting to archive.ubuntu.com]
```

We tried modifying the `/etc/hosts` file to resolve the DNS to a current good IP and that yields the same results:
```
root@applogs-eu-west-1-prod:/# apt-get update
0% [Connecting to archive.ubuntu.com (91.189.88.46)]
```

The kern.log on the container shows these logs repeating every 30 minutes since boot:
```
Aug 25 11:00:01 ip-10-172-84-142 kernel: [306067.586148] device veth6b577c7 entered promiscuous mode
Aug 25 11:00:01 ip-10-172-84-142 kernel: [306067.586301] IPv6: ADDRCONF(NETDEV_UP): veth6b577c7: link is not ready
Aug 25 11:00:01 ip-10-172-84-142 kernel: [306067.672648] IPv6: ADDRCONF(NETDEV_CHANGE): veth6b577c7: link becomes ready
Aug 25 11:00:01 ip-10-172-84-142 kernel: [306067.672689] docker0: port 3(veth6b577c7) entered forwarding state
Aug 25 11:00:01 ip-10-172-84-142 kernel: [306067.672694] docker0: port 3(veth6b577c7) entered forwarding state
Aug 25 11:00:01 ip-10-172-84-142 kernel: [306068.325639] docker0: port 3(veth6b577c7) entered disabled state
Aug 25 11:00:01 ip-10-172-84-142 kernel: [306068.326682] device veth6b577c7 left promiscuous mode
Aug 25 11:00:01 ip-10-172-84-142 kernel: [306068.326693] docker0: port 3(veth6b577c7) entered disabled state
Aug 25 11:30:01 ip-10-172-84-142 kernel: [307868.211348] device vethdf6be1f entered promiscuous mode
Aug 25 11:30:01 ip-10-172-84-142 kernel: [307868.211497] IPv6: ADDRCONF(NETDEV_UP): vethdf6be1f: link is not ready
Aug 25 11:30:01 ip-10-172-84-142 kernel: [307868.312699] IPv6: ADDRCONF(NETDEV_CHANGE): vethdf6be1f: link becomes ready
Aug 25 11:30:01 ip-10-172-84-142 kernel: [307868.312740] docker0: port 3(vethdf6be1f) entered forwarding state
Aug 25 11:30:01 ip-10-172-84-142 kernel: [307868.312746] docker0: port 3(vethdf6be1f) entered forwarding state
Aug 25 11:30:02 ip-10-172-84-142 kernel: [307868.996740] docker0: port 3(vethdf6be1f) entered disabled state
Aug 25 11:30:02 ip-10-172-84-142 kernel: [307868.999081] device vethdf6be1f left promiscuous mode
Aug 25 11:30:02 ip-10-172-84-142 kernel: [307868.999094] docker0: port 3(vethdf6be1f) entered disabled state
```

Other containers on the same instance are working just fine, its just the two that are running our splunk-forwarder private image. We thought about if it might be the image, but this same image runs and works 99% of the time on other instances built with the same overall configuration.

Stopping, removing, and recreating the container resolves the issue.

We are now, however, concerned that this behavior is repeating itself in other containers without our knowledge.

**Describe the results you expected:**
Network outbound traffic should be possible.

**Additional information you deem important (e.g. issue happens only occasionally):**
We are not sure if the container can receive inbound traffic either, but we can exec into it. The container is built minimalistically, so the tools are unavailable on the current image.

**Comment by justincormack** [comment] 2016-08-25 20:34
To get more tools you can do `docker run --net=container:xxxx debian bash` where `xxxx` is the container you want to investigate. Then you run in the same network namespace, which should have the same routing issues but you have more tools.

**Comment by djenriquez** [comment] 2016-08-25 20:54
Thanks @justincormack but the issue is not easily reproducible. It happens for reasons unknown at this point and we would need to have the tools as we `exec` into a problem container rather than running a new container with the tools because when we run the new container, changes are it wont have the same problem.

**Comment by justincormack** [comment] 2016-08-26 09:34
It should have the same problem if it is in the same network namespace.

Those logs normally mean a container has exited or been restarted. It would probably help to dump the state of the routing table in and outside of the container and iptables setup at the point where there is an issue.

**Comment by djenriquez** [comment] 2016-08-28 19:29
Hmm thats not the behavior we are seeing-- stopping, removing and recreating the same container with the same docker run command fixes the issue. 

This service was a pretty critical logging service for us, so we worked around the problem by running `--net=host` for these containers. If we see this happen again on another container, we'll try to grab the iptables setup. Depending on the image though, the container might not have iptables installed, however, on the host, we can definitely grab those.

**Comment by djenriquez** [comment] 2016-08-29 17:25
Hey @justincormack, found an old instance with the issue and ran the command you suggested. Can confirm that the new container is having the same trouble, since as you said, its running in the same network namespace. Awesome!

Host IPTables:
```
root@ip-10-172-10-197:/home/ubuntu# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-ISOLATION  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.17.0.3           tcp dpt:http-alt
ACCEPT     tcp  --  anywhere             172.17.0.4           tcp dpt:http-alt
ACCEPT     tcp  --  anywhere             172.17.0.6           tcp dpt:http
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:1508
ACCEPT     tcp  --  anywhere             172.17.0.7           tcp dpt:8082
ACCEPT     tcp  --  anywhere             172.17.0.8           tcp dpt:8082
ACCEPT     tcp  --  anywhere             172.17.0.10          tcp dpt:8082
ACCEPT     tcp  --  anywhere             172.17.0.12          tcp dpt:8082
ACCEPT     tcp  --  anywhere             172.17.0.14          tcp dpt:8082
ACCEPT     tcp  --  anywhere             172.17.0.15          tcp dpt:8082

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere
```
```
root@ip-10-172-10-197:/home/ubuntu# iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER -d 172.17.0.3/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8080 -j ACCEPT
-A DOCKER -d 172.17.0.4/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8080 -j ACCEPT
-A DOCKER -d 172.17.0.6/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 1508 -j ACCEPT
-A DOCKER -d 172.17.0.7/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8082 -j ACCEPT
-A DOCKER -d 172.17.0.8/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8082 -j ACCEPT
-A DOCKER -d 172.17.0.10/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8082 -j ACCEPT
-A DOCKER -d 172.17.0.12/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8082 -j ACCEPT
-A DOCKER -d 172.17.0.14/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8082 -j ACCEPT
-A DOCKER -d 172.17.0.15/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8082 -j ACCEPT
-A DOCKER-ISOLATION -j RETURN
```

Inside the container:
```
root@applogs-eu-west-1-prod-<REDACTED>:/# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
root@applogs-eu-west-1-prod-<REDACTED>:/# iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
root@applogs-eu-west-1-prod-<REDACTED>:/# 
```
Container nslookup:
```
root@applogs-eu-west-1-prod-<REDACTED>:/# nslookup www.google.com
;; connection timed out; no servers could be reached
```
Container dig:
```
root@applogs-eu-west-1-prod-<REDACTED>:/# dig www.google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.google.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```
Docker inspect:
```
ubuntu@ip-10-172-10-197:~$ docker inspect app-logs-splunk
[
    {
        "Id": "a210bb11c40e8b2d15f28d6903f01c6d6d9885744d4c7c5eeee85ba2ad469e44",
        "Created": "2016-08-17T23:32:42.910845641Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "/opt/splunkforwarder/bin/splunk set default-hostname ${APPNAME}_${AWS_REGION}_${TENANT}_${APP_ENV}_${INSTANCE_ID} -auth admin:changeme --accept-license \u0026\u0026 /opt/splunkforwarder/bin/splunk start --accept-license --nodaemon --no-prompt --answer-yes"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1642,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-08-24T20:59:52.974428313Z",
            "FinishedAt": "2016-08-24T20:59:52.647257773Z"
        },
        "Image": "sha256:e3d11faea163d6690b7657f5e6b5445acc036764a7bcd18ff3d081fce8838f95",
        "ResolvConfPath": "/var/lib/docker/containers/a210bb11c40e8b2d15f28d6903f01c6d6d9885744d4c7c5eeee85ba2ad469e44/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/a210bb11c40e8b2d15f28d6903f01c6d6d9885744d4c7c5eeee85ba2ad469e44/hostname",
        "HostsPath": "/var/lib/docker/containers/a210bb11c40e8b2d15f28d6903f01c6d6d9885744d4c7c5eeee85ba2ad469e44/hosts",
        "LogPath": "/var/lib/docker/containers/a210bb11c40e8b2d15f28d6903f01c6d6d9885744d4c7c5eeee85ba2ad469e44/a210bb11c40e8b2d15f28d6903f01c6d6d9885744d4c7c5eeee85ba2ad469e44-json.log",
        "Name": "/app-logs-splunk",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/log:/var/log:rw",
                "/etc/app-logs/splunk:/opt/splunkforwarder/etc/apps/DefaultConfig/default:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "provision_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Source": "/var/log",
                "Destination": "/var/log",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/etc/app-logs/splunk",
                "Destination": "/opt/splunkforwarder/etc/apps/DefaultConfig/default",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "applogs-eu-west-1-prod-<REDACTED>",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "INSTANCE_ID=i-0f6155<REDACTED>",
                "AWS_REGION=eu-west-1",
                "APP_ENV=prod",
                "TENANT=<REDACTED>",
                "APPNAME=applogs",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "/opt/splunkforwarder/bin/splunk set default-hostname ${APPNAME}_${AWS_REGION}_${TENANT}_${APP_ENV}_${INSTANCE_ID} -auth admin:changeme --accept-license \u0026\u0026 /opt/splunkforwarder/bin/splunk start --accept-license --nodaemon --no-prompt --answer-yes"
            ],
            "Image": "docker.<REDACTED>.com/splunk-forwarder:1.1.0",
            "Volumes": {
                "/opt/splunkforwarder/etc/apps/DefaultConfig/default": {},
                "/var/log": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "d1f6ae1724fafe0285c02b3ad936a507636a1371822014b846632365d9bc62e3",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "provision",
                "com.docker.compose.service": "app-logs-splunk",
                "com.docker.compose.version": "1.7.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e9cc94c0e0d4c771063da40dcba869bf76b14b099b16d1a9a843269c838b5cd6",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/e9cc94c0e0d4",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "provision_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "a210bb11c40e",
                        "app-logs-splunk"
                    ],
                    "NetworkID": "62118d8e0ef3c70bc987ee29ec36fdf9c7106e4288d8da495cd32bf65e84f449",
                    "EndpointID": "740417e60b730a55c94abf5b329bf9c4e209f949efe3f1c5e5d72c8a5d7b1641",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:02"
                }
            }
        }
    }
]
```

I have the instance quarantied, so we can continue to run additional tests on it as necessary.

Thoughts?

**Comment by mrjana** [comment] 2016-08-29 23:43
@djenriquez When the problem happens can we rule out DNS by pinging from inside the container to some external IP like say `8.8.8.8`? Also a `iptables -t nat -L` to see what the nat rules are would be helpful.

**Comment by djenriquez** [comment] 2016-08-31 18:17
@mrjana:
```
root@applogs-eu-west-1-prod-infospace:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
32 packets transmitted, 0 received, 100% packet loss, time 31020ms
```
```
root@applogs-eu-west-1-prod-infospace:/# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER_OUTPUT  all  --  anywhere             127.0.0.11          

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER_POSTROUTING  all  --  anywhere             127.0.0.11          

Chain DOCKER_OUTPUT (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             127.0.0.11           tcp dpt:domain to:127.0.0.11:42072
DNAT       udp  --  anywhere             127.0.0.11           udp dpt:domain to:127.0.0.11:53036

Chain DOCKER_POSTROUTING (1 references)
target     prot opt source               destination         
SNAT       tcp  --  127.0.0.11           anywhere             tcp spt:42072 to::53
SNAT       udp  --  127.0.0.11           anywhere             udp spt:53036 to::53 
```
The `iptables` command took a few seconds to complete, is that normal?

**Comment by mrjana** [comment] 2016-09-02 05:33
@djenriquez Sorry if I did not specify exactly where to dump the iptables. Can you dump `iptables -t nat -nvL` on the host namespace?

**Comment by djenriquez** [comment] 2016-09-06 17:55
@mrjana On the host:
```
root@ip-10-172-10-197:/home/ubuntu# iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 442K packets, 29M bytes)
 pkts bytes target     prot opt in     out     source               destination         
  72M 4339M DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
   37  2220 DNAT       tcp  --  *      *       0.0.0.0/0            169.254.170.2        tcp dpt:80 to:127.0.0.1:51679

Chain INPUT (policy ACCEPT 2 packets, 128 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 739K packets, 47M bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 821K packets, 53M bytes)
 pkts bytes target     prot opt in     out     source               destination         
 809K   50M MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.3           172.17.0.3           tcp dpt:8080
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.4           172.17.0.4           tcp dpt:8080
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.6           172.17.0.6           tcp dpt:80
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.7           172.17.0.7           tcp dpt:8082
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.8           172.17.0.8           tcp dpt:8082
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.10          172.17.0.10          tcp dpt:8082
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.12          172.17.0.12          tcp dpt:8082
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.14          172.17.0.14          tcp dpt:8082
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.15          172.17.0.15          tcp dpt:8082

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
  385 24921 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
 235K   14M DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:32769 to:172.17.0.3:8080
86172 5170K DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:32771 to:172.17.0.4:8080
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:32772 to:172.17.0.6:80
  13M  750M DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:32788 to:172.17.0.7:8082
4337K  260M DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:32789 to:172.17.0.8:8082
1342K   81M DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:32791 to:172.17.0.10:8082
1199K   72M DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:32793 to:172.17.0.12:8082
 423K   25M DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:32795 to:172.17.0.14:8082
 423K   25M DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:32796 to:172.17.0.15:8082
```

**Comment by djenriquez** [comment] 2016-09-06 17:57
And just incase you wanted me to run that in the container network namespace also:
```
root@applogs-eu-west-1-prod-<REDACTED>:/# iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 53000 packets, 4901K bytes)
 pkts bytes target     prot opt in     out     source               destination         
26496 2451K DOCKER_OUTPUT  all  --  *      *       0.0.0.0/0            127.0.0.11          

Chain POSTROUTING (policy ACCEPT 79496 packets, 7352K bytes)
 pkts bytes target     prot opt in     out     source               destination         
26496 2451K DOCKER_POSTROUTING  all  --  *      *       0.0.0.0/0            127.0.0.11          

Chain DOCKER_OUTPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            127.0.0.11           tcp dpt:53 to:127.0.0.11:42072
26496 2451K DNAT       udp  --  *      *       0.0.0.0/0            127.0.0.11           udp dpt:53 to:127.0.0.11:53036

Chain DOCKER_POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 SNAT       tcp  --  *      *       127.0.0.11           0.0.0.0/0            tcp spt:42072 to::53
    0     0 SNAT       udp  --  *      *       127.0.0.11           0.0.0.0/0            udp spt:53036 to::53
```

**Comment by djenriquez** [comment] 2016-09-07 21:16
@mrjana i think I've root caused the issue [here](https://github.com/docker/docker/issues/26391#issuecomment-245421784).

**Comment by thaJeztah** [comment] 2016-09-27 16:43
Closing as duplicate of https://github.com/docker/docker/issues/26391#issuecomment-245421784 per the above comment

**Closed by thaJeztah** 2016-09-27 16:43 UTC
