### ISSUE TITLE
`docker update --memory 4G` failed to update cgroup

### ISSUE THREAD

**Issue by jizhilong** [docker/docker#23157] opened 2016-06-01 04:18 UTC
**Brief description**
If a more-or-equal than 4G is supplied, `docker update --memory` succeed to update a container's hostconfig which could be checked by `docker inspect`, but failed to update the container's cgroup settings.
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 2                                                                                                                                                         
 Running: 1
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-194180-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.76 GB
 Data Space Total: 107.4 GB
 Data Space Available: 16.48 GB
 Metadata Space Used: 1.95 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: jzl-dev0010
ID: U4ZX:62TO:YRGL:CNDH:6UZN:VNYX:3R2W:ZCWF:4TJS:54BS:O4AK:NLYY
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Script to reproduce the issue:**

```
#!/bin/bash

function assertequal {
  if [ ! $1 -eq $2 ]; then
    echo "FAILED: \"$3\"" > /dev/stderr
  else
    echo "SUCCEED: \"$3\"" > /dev/stderr
  fi
}

let m128M="128*2**20"
let m2G="2*2**30"
let m4G="4*2**30"
let m4090M="4090*2**20"
let m8G="8*2**30"
name=test-docker-update

docker rm -f $name
cid=`docker run --name $name -td -m 128M --memory-swap -1 busybox sh`
sleep 2
cd /sys/fs/cgroup/memory/docker/$cid/

assertequal `cat memory.limit_in_bytes` $m128M "docker run -m 128M(cgroup)"
assertequal `docker inspect --format '{{.HostConfig.Memory}}' $cid` $m128M "docker run -m 128M(docker inspect)"
echo >/dev/stderr

docker update --memory 2G $name 
assertequal `cat memory.limit_in_bytes` $m2G "docker update -m 2G(cgroup)"
assertequal `docker inspect --format '{{.HostConfig.Memory}}' $cid` $m2G "docker update -m 2G(docker inspect)"
echo >/dev/stderr

docker update --memory 4G $name 
assertequal `cat memory.limit_in_bytes` $m4G "docker update -m 4G(cgroup)"
assertequal `docker inspect --format '{{.HostConfig.Memory}}' $cid` $m4G "docker update -m 4G(docker inspect)"
echo >/dev/stderr

docker update --memory 2G $name 
assertequal `cat memory.limit_in_bytes` $m2G "docker update -m 2G(cgroup)"
assertequal `docker inspect --format '{{.HostConfig.Memory}}' $cid` $m2G "docker update -m 2G(docker inspect)"
echo >/dev/stderr

docker update --memory 8G $name 
assertequal `cat memory.limit_in_bytes` $m8G "docker update -m 8G(cgroup)"
assertequal `docker inspect --format '{{.HostConfig.Memory}}' $cid` $m8G "docker update -m 8G(docker inspect)"
echo >/dev/stderr


docker update --memory $m4090M $name 
assertequal `cat memory.limit_in_bytes` $m4090M "docker update -m 4090M(cgroup)"
assertequal `docker inspect --format '{{.HostConfig.Memory}}' $cid` $m4090M "docker update -m 4090M(docker inspect)"
echo >/dev/stderr
```

**Results received:**

```
SUCCEED: "docker run -m 128M(cgroup)"
SUCCEED: "docker run -m 128M(docker inspect)"

SUCCEED: "docker update -m 2G(cgroup)"
SUCCEED: "docker update -m 2G(docker inspect)"

FAILED: "docker update -m 4G(cgroup)"
SUCCEED: "docker update -m 4G(docker inspect)"

SUCCEED: "docker update -m 2G(cgroup)"
SUCCEED: "docker update -m 2G(docker inspect)"

FAILED: "docker update -m 8G(cgroup)"
SUCCEED: "docker update -m 8G(docker inspect)"

SUCCEED: "docker update -m 4090M(cgroup)"
SUCCEED: "docker update -m 4090M(docker inspect)"
```

**Results expected:**

```
SUCCEED: "docker run -m 128M(cgroup)"
SUCCEED: "docker run -m 128M(docker inspect)"

SUCCEED: "docker update -m 2G(cgroup)"
SUCCEED: "docker update -m 2G(docker inspect)"

SUCCEED: "docker update -m 4G(cgroup)"
SUCCEED: "docker update -m 4G(docker inspect)"

SUCCEED: "docker update -m 2G(cgroup)"
SUCCEED: "docker update -m 2G(docker inspect)"

SUCCEED: "docker update -m 8G(cgroup)"
SUCCEED: "docker update -m 8G(docker inspect)"

SUCCEED: "docker update -m 4090M(cgroup)"
SUCCEED: "dockerupdate -m 4090M(docker inspect)"
```

**Causes I've found for this issue**
This should be caused by the mismatch of types to represent memory limit, while `container.HostConfig` uses `int64` and `libcontainerd.Resources` uses `uint32`

**Comment by thaJeztah** [comment] 2016-06-01 11:38
Thanks for a very detailed description and way to reproduce! 👍

**Comment by GuomeiQtl** [comment] 2016-06-02 09:07
:+1:

**Comment by boynux** [comment] 2016-06-07 16:44
#dibs

**Comment by thaJeztah** [comment] 2016-06-07 20:51
@boynux hm, GitHub web hooks seem to have some issues lately, let me add it manually :smile:

**Comment by boynux** [comment] 2016-06-09 19:30
With kernel 4.4.0 I had no problem to execute `docker update -m -1 <id>` 
Any idea?

**Comment by boynux** [comment] 2016-06-11 19:53
There is already an issue for this in Conrainerd. https://github.com/docker/containerd/issues/260
I'm not sure how to synchronize these two projects to avoid breaking other build?

What's the common practice here?
I checked both codes and changes are small in docker project and medium in cotainerd assuming that no other project actively using containerd, since these changes might break those as well.

Any thoughts?

**Comment by mlaventure** [comment] 2016-06-11 20:11
thanks for the link @boynux. I'll do the needed work to have containerd updated then vendored in here :)

**Comment by thaJeztah** [comment] 2016-06-27 18:39
thanks @mlaventure closing this as it should be fixed now

**Closed by thaJeztah** 2016-06-27 18:39 UTC
Labels: kind/bug, status/claimed, version/1.11
