### ISSUE TITLE
Docker CE version of the Mac, standby, The time in the container will stop, the newly created container time (UTC and Other) will not be correct.Right time after reboot system

### ISSUE THREAD

**Issue by 120011676** [docker/docker#32399] opened 2017-04-06 08:21 UTC
Docker CE version of the Mac, standby, The time in the container will stop, the newly created container time (UTC and Other) will not be correct.Right time after reboot system

----------------
Version 17.03.1-ce-mac5 (16048)
Channel: stable
B18e2a50cc

**Comment by thaJeztah** [comment] 2017-04-06 08:31
This is a Docker for Mac issue, so should be reported in the Docker for Mac issue tracker (https://github.com/docker/for-mac/issues)

This is a known issue however (see docker/for-mac#17) the time should be synced again after a couple of minutes, but see the linked issue for more information.

I'll close the issue here, because this is not a bug in the docker "engine" itself, but specific to Docker for Mac

**Closed by thaJeztah** 2017-04-06 08:31 UTC

**Comment by Rambo68** [comment] 2017-04-11 17:32
Greetings. I know Docker for mac now has a qcow2 image and it does not seem to work with Docker-machine. How is IP info gathered from the qcow2 image since docker-machine default is no longer used? 

Thanks
