### ISSUE TITLE
Potential race condition in createRootfs() for devmapper graphdriver

### ISSUE THREAD

**Issue by tylerharter** [docker/docker#13330] opened 2015-05-19 18:56 UTC
I believe there's a potential race condition in createRootfs() in daemon/daemon.go.  I've not observed any symptoms (perhaps it does not manifest frequently), but the code appears wrong (or I could be misunderstanding it).

The createRootfs() function (among other things) does four operations, in this order:
(A) mounts initID with Get
(B) modifies initId with SetupInitLayer
(C) creates container.ID from initID with Create
(D) unmounts initId with the defer'd Put

My concern is for some graphdrivers, the modifications of step B may or may not get copied to container.ID as a part of step C.

I don't believe there is a problem for graphdrivers such as aufs or vfs, but I believe doing step C before step D is problematic for devmapper and a similar backend that I'm writing.

In particular, for devmapper, SetupInitLayer (step B) makes changes to a file system tree that is backed by a dm image (formatted with ext4, xfs, or some other file system).  Step C snapshots the backing image (devmapper implements the Driver.Create call with a call to devicemapper.CreateSnapDevice).

My concern is that ext4 and other file systems may choose to buffer writes, so the FS-level changes of step B may or may not appear at dm-image level at the time of snapshot in step C.

Would it be better to unmount the dm image between steps B and C?  That should force any writes buffered by ext4 to the dm image.  I think this could be easily done by calling driver.Put (without the defer) after the call to SetupInitLayer (in other words, perform step D before step C).

**Comment by thaJeztah** [comment] 2015-05-24 00:28
ping @vbatts @rhvgoyal I think you're most familiar with this :)

**Comment by rhvgoyal** [comment] 2015-05-26 15:15
Ok, short answer. This is not a race. By default device mapper suspend operation will sync vfs.

Long answer:

- One has to suspend origin device, then take snapshot and then resume origin device.
- Docker does suspend the origin device.
- suspend operation by default ensures that fs is synced. (one can override it with a flag but I don't see docker using that flag).
- And snapshot taken after suspend, should have the data which had complete write before suspend operation.

So I don't think there is a race here w.r.t setupInitLayer().

**Comment by rhvgoyal** [comment] 2015-05-26 15:16
One can look at man page of "dmsetup" and look for description of subcommand "suspend" for details.

**Comment by tylerharter** [comment] 2015-05-26 15:53
Ah, that makes more sense (thanks!).  Even if we don't lose data, wouldn't a clean unmount still be better than just a suspend/sync?  As I understand it, an ext4 unmount will checkpoint metadata in place, whereas a sync can return success once the data is merely written to the journal.

In either case, the data is persisted, but to different places.  With the current approach, the data is persisted to the journal, forcing ext4 to perform crash recovery upon the next mount.  With the clean unmount approach, crash recovery wouldn't be necessary.

**Comment by rhvgoyal** [comment] 2015-05-26 16:58
@tylerharter 

What are the chances that crash will happen. And if it happened, then crash recovery will happen. What's so bad about it that we prefer unmount instead of sync.

I guess that you require it for the backend you are writing. In that case make an explicit case for that in a PR with details.

Atleast for existing backends we don't need to unmount origin.

**Comment by tylerharter** [comment] 2015-05-26 18:34
I'm not saying an actual crash will happen -- I agree that's not an important or likely case in this situation.  I'm suggesting the image state will appear as if a crash has happened, as we are copying the image state without giving ext4 a chance to cleanly unmount.

After sync (called by suspend) returns, but before metadata writeback (which sync does not trigger), the recently written metadata will be in the ext4 journal, but not written in place.  Right?

For my backend, I'll can follow dm's example with the syncfs call, so I don't think it's a special case.  It just seems ugly (and slow?) to make ext4 perform crash recovery for the common case, even if correctness is not effected.  

When the image is snapshot'ed by dm, the s_state field of the ext4 superblock (https://ext4.wiki.kernel.org/index.php/Ext4_Disk_Layout) will not be 0x0001 (cleanly unmounted), and crash recovery will be necessary, right?  Sorry if I'm missing something about the interactions between dm and ext4 (very possible)!

**Comment by rhvgoyal** [comment] 2015-05-26 18:44
I don't know enough of ext4. But this is what you seem to be saying.

- Create snapshot of image (say container1)
- Setup init layer in container 1
- Create snaphost of container 1 (say container 2)

Now when we start container 2 and mount it, ext4 will think that it needs to do crash recovery? Does it really happen? Do you have logs? 

And now

**Comment by rhvgoyal** [comment] 2015-05-26 18:47
Internally in kernel we call sync_filesystem() which in turn calls ext4_sync_fs(). It seems to be doing something with journal commit. So are you sure that after sync_filesystem() call is finished, fs is not considered clean.

**Comment by tylerharter** [comment] 2015-05-26 21:08
Yeah, that's what I'm worried is going to happen.  I have not collected logs, but from other work with ext4, I do know checkpointing does occur after a sync returns.

As I mentioned, I'm not experiencing any symptoms (probably because the journal enables crash recovery).  It's difficult to reason about what can be expected when an image is copied when a mounted file system is running over it.  Even if the FS is in a "clean" state for a particular version of ext4 (and neither of us seem to know whether we even have that guarantee now), you can't expect that behavior in general in the future.  For example, suppose an online defrag feature was added to ext4.  Even after the sync returned, the defrag could make the image dirty again.

If dm someday supports other file systems besides ext4 and XFS, will this issue be revisited, and will people reason about whether those images are clean or not after a sync?  At best, the current code seems not very future proof.

It seems the safe (and easy) thing to do would be to simply unmount before copying an image.  Are there disadvantages to doing it that way that I'm overlooking?  That said, you've convinced me there's not a correctness problem with ext4 given ext4's crash recovery capabilities.  Thanks!

**Comment by rhvgoyal** [comment] 2015-06-08 17:18
@vbatts Given that it is not a correctness issue, can we close this.

**Comment by vbatts** [comment] 2015-06-08 18:56
For now, this potential race is without a reproducer. I will close it. We can re-open once we have a reproducer to work with.

**Closed by vbatts** 2015-06-08 18:56 UTC
Labels: /system/devicemapper

**Comment by rhvgoyal** [comment] 2015-07-22 14:49
Unmounting init layer before using it as base image benefits XFS too. So I have generated a pull request here.
https://github.com/docker/docker/pull/14854
