### ISSUE TITLE
Failed to connect to bus: No such file or directoryin ubuntu docker Container

### ISSUE THREAD

**Issue by jooeji** [docker/docker#32616] opened 2017-04-14 03:05 UTC
base:(Ubuntu 14.04 host)(Ubuntu 16.04 container)
```
FROM ubuntu
RUN systemctl enable yeti_uwsgi.service
RUN systemctl enable yeti_oneshot.service
RUN systemctl enable yeti_feeds.service
RUN systemctl enable yeti_exports.service
RUN systemctl enable yeti_analytics.service
RUN systemctl enable yeti_beat.service
RUN systemctl daemon-reload
```
![3](https://cloud.githubusercontent.com/assets/12831513/25031838/34b8733e-2102-11e7-8bd6-ac2713cd4004.png)
```
$ uname -a
Linux ubuntu 4.4.0-72-generic #93~14.04.1-Ubuntu SMP Fri Mar 31 15:05:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment] 2017-04-15 01:07
This is expected; [containers are _not_ VM's](https://blog.docker.com/2016/03/containers-are-not-vms/) so there's no init system running in a container, unless you specify it as the container's main process.

In your case, you're trying to start systemd services but systemd is not present inside the container. Also; during build, each `RUN` is executed in a _new_ container, after which the container is stopped, and committed to a new image-layer. Starting services during build likely won't give you what you want, because when _running_ the image, those services are not running.

I really recommend learning the mechanics of docker, and containers; https://docs.docker.com/learn/

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to comment after I closed 👍

**Closed by thaJeztah** 2017-04-15 01:07 UTC
