### ISSUE TITLE
documentation — fail, empty reason, for PR #25203

### ISSUE THREAD

**Issue by lixiaobing10051267** [docker/docker#25206] opened 2016-07-29 04:09 UTC
documentation — fail, can't find reason, for PR #25203, are there anyone meeting this:

Build Errors:
Fix the path under windows for dockerimages.md: https://github.com/docker/docker/pull/25203
# Filtered (engine) Summary:
	Found: 852 files
	Found: 0 errors

**Comment by icecrime** [comment] 2016-07-29 04:35
Thanks for the report: I think that's a known (and temporary) issue with the documentation CI. Ping @thaJeztah and @SvenDowideit for confirmation!

**Comment by thaJeztah** [comment] 2016-07-29 06:15
Hm, the temporarily broken links are fixed now (still some broken links in others repos it seems), but it seems the end result is `UNSTABLE`

@SvenDowideit do you know what's the cause if that?

**Comment by thaJeztah** [comment] 2016-07-29 06:27
Got a reply from @SvenDowideit (he's traveling, so from his phone); and he suspects it's due to network instabilities during the test, so can be ignored

**Comment by thaJeztah** [comment] 2016-07-29 06:28
Link is https://jenkins.dockerproject.org/job/docs-docker-pr/11513/console

**Comment by lixiaobing10051267** [comment] 2016-07-29 06:45
I tried to re-test, result is unstable,  but it still display: documentation — fail

**Comment by thaJeztah** [comment] 2016-07-29 06:58
@SvenDowideit would have a look at the CI, possibly change some configuration

**Comment by SvenDowideit** [comment] 2016-08-01 23:08
yeah, every now and then jenkins is just mean to us :)

I think I've fixed a new issue that cropped up with the v1.12 GA release, so I'm going to close this - please kick me under the table if things go wonky again :)

**Closed by SvenDowideit** 2016-08-01 23:08 UTC
Labels: kind/docs, kind/flakytest
