### ISSUE TITLE
How to register a container to another container?

### ISSUE THREAD

**Issue by oopilot5** [docker/docker#22823] opened 2016-05-19 00:44 UTC
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by HackToday** [comment] 2016-05-19 04:52
hi @oopilot5 it seems question, not issue :0
maybe irc channel or docker forum or stackoverflow is better place for that.

Besides, what do you mean register one container to another?

**Comment by thaJeztah** [comment] 2016-05-19 11:47
If you mean "discovery", containers can find each other by using the container name as hostname (if they're on the same network), for example:

```bash
docker network create my-network
docker run -d --net=my-network --name=container-a nginx:alpine

docker run --net=my-network alpine sh -c "ping -c 3 container-a"
PING container-a (172.20.0.2): 56 data bytes
64 bytes from 172.20.0.2: seq=0 ttl=64 time=0.092 ms
64 bytes from 172.20.0.2: seq=1 ttl=64 time=0.143 ms
64 bytes from 172.20.0.2: seq=2 ttl=64 time=0.118 ms

--- container-a ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.092/0.117/0.143 ms
```

But as @HackToday mentioned, this looks like a question, not a bug-report, so I'll close this issue. But feel free to comment after I closed

**Closed by thaJeztah** 2016-05-19 11:47 UTC
