### ISSUE TITLE
Docker lockup + docker-proxy zombies on master

### ISSUE THREAD

**Issue by erikh** [docker/docker#7926] opened 2014-09-07 16:59 UTC
As of 38186084b3ade82049d03f4f83640a0d47c3040c:

Steps to reproduce:

1. docker run -p 8080:8080 -itd busybox nc -l localhost:8080
1. nc localhost 8080

At this point:
  * docker ps will not respond
  * docker-proxy, when killed, will go zombie

**Comment by jfrazelle** [comment] 2015-02-25 22:32
@erikh is this still an issue, bleh userland proxy

**Comment by jfrazelle** [comment] 2015-02-26 23:16
cant reproduce closing

**Closed by jfrazelle** 2015-02-26 23:16 UTC
