### ISSUE TITLE
[1.10-rc1] failed drivers makes container delete fail

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19679] opened 2016-01-25 20:53 UTC
Okay, here's the steps, I'm using the Convoy VFS driver, but I assume any volume driver will exhibit the same behavior.

1. Start Volume driver

```
./bin/convoy daemon --drivers vfs --driver-opts vfs.path /tmp/foo/
echo unix:///var/run/convoy/convoy.sock > /etc/docker/plugins/convoy.spec
````

1. Launch restart always container using driver

```
docker run -itd --restart=always --volume-driver convoy --name test -v test:/mnt ubuntu
```

1. Kill Docker daemon (not gracefully)
1. Kill volume driver
1. Start Docker daemon (container will not start because volume driver is not available)
1. Delete container

```
$ docker rm -fv 6dc2b5436bd1ee77021c8e34f874b321d1b8bac174e6340bb8439d44ed00ed6e
Failed to remove container (6dc2b5436bd1ee77021c8e34f874b321d1b8bac174e6340bb8439d44ed00ed6e): Error response from daemon: Driver overlay failed to remove root filesystem 6dc2b5436bd1ee77021c8e34f874b321d1b8bac174e6340bb8439d44ed00ed6e: readdirent: no such file or directory
```

**Comment by thaJeztah** [comment] 2016-01-26 02:41
Agreed; removal of a container should not be blocked by a missing driver

**Comment by thaJeztah** [comment] 2016-01-26 02:41
@ibuildthecloud is this a regression since 1.9?

**Comment by cpuguy83** [comment] 2016-01-26 03:04
I cannot reproduce this on master

**Comment by cpuguy83** [comment] 2016-01-26 03:04
At least, not with my own test volume driver.

**Comment by coolljt0725** [comment] 2016-01-26 03:19
I can reproduce this on master, I'll take a look

**Comment by coolljt0725** [comment] 2016-01-26 03:59
seems it's not related to the volume driver, I can reproduce without volume
<pre><code>$ docker run -itd --restart=always  ubuntu
c6bcc9fee3510f64ac1950af500155592e7b54ecf773b969eb7ef677bb67a150
$ sudo kill -9 $(cat /var/run/docker.pid)</code></pre>
And restart the daemon
<pre><code>$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                  PORTS               NAMES
c6bcc9fee351        ubuntu              "/bin/bash"         41 seconds ago      Up Less than a second                       angry_snyder
$ docker rm -f c6bcc9fee3510f64ac1950af500155592e7b54ecf773b969eb7ef677bb67a150
Failed to remove container (c6bcc9fee3510f64ac1950af500155592e7b54ecf773b969eb7ef677bb67a150): Error response from daemon: Driver overlay failed to remove root filesystem c6bcc9fee3510f64ac1950af500155592e7b54ecf773b969eb7ef677bb67a150: readdirent: no such file or directory</code></pre>

**Comment by coolljt0725** [comment] 2016-01-26 04:27
I think I found the reason, the daemon ungracefully stop will left the container filesystem still be mounted and daemon restart failed to unmount it, we can see this log
<pre><code>DEBU[0005] killing old running container 08b6c0a38af43634c4c4153c50544529e39c1ecb74921311e9c7c7aae0aa3163
ERRO[0005] Error unmounting container 08b6c0a38af43634c4c4153c50544529e39c1ecb74921311e9c7c7aae0aa3163: not mounted</code></pre>
And we can see the rootfs still be mount from `mount`, the layer id is `4604cdff2539247d1e0f73652d7f3ab04c76d1a87a14c63a52f54ee01adc8e06` for container `08b6c0a38af43634c4c4153c50544529e39c1ecb74921311e9c7c7aae0aa3163`
<pre><code>mount | grep 4604cdff2539247d1e0f73652d7f3ab04c76d1a87a14c63a52f54ee01adc8e06
overlay on /var/lib/docker/overlay/4604cdff2539247d1e0f73652d7f3ab04c76d1a87a14c63a52f54ee01adc8e06/merged type overlay (rw,relatime,seclabel,lowerdir=/var/lib/docker/overlay/e761944229043356e3121009205f4f5944ceeeda1c07cf641acb7533f6e2d9a4/root,upperdir=/var/lib/docker/overlay/4604cdff2539247d1e0f73652d7f3ab04c76d1a87a14c63a52f54ee01adc8e06/upper,workdir=/var/lib/docker/overlay/4604cdff2539247d1e0f73652d7f3ab04c76d1a87a14c63a52f54ee01adc8e06/work)
</code></pre>
so when we removing the container, it failed to remove the rootfs and umount the `/var/lib/docker/overlay/4604cdff2539247d1e0f73652d7f3ab04c76d1a87a14c63a52f54ee01adc8e06/merged` manually and rm the container will work.

**Closed** 2016-02-08 21:21 UTC
Labels: kind/bug
