### ISSUE TITLE
Fix to your installation listed on 

### ISSUE THREAD

**Issue by CaptTofu** [docker/docker#16327] opened 2015-09-15 22:06 UTC
https://docs.docker.com/installation/ubuntulinux/

"
For Trusty 14.04
There are no prerequisites for this version.
"

Actually, there is a problem if you install without the steps listed on this site:

https://meta.discourse.org/t/docker-install-module-aufs-not-found/18494

sudo apt-get update
sudo apt-get install lxc wget bsdtar curl
sudo apt-get install linux-image-extra-$(uname -r)
sudo modprobe aufs

I have verified this and updated my ansible playbooks:

- name: Install packages for 14.04x
  apt: pkg={{ item }}
  with_items:
    - lxc
    - wget
    - bsdtar
  when: ansible_distribution_release == 'trusty'

- name: Install kernel extras for 14.04x
  apt: pkg=linux-image-extra-{{ ansible_kernel }}
  when: ansible_distribution_release == 'trusty'

- name: Insert aufs kernel module
  modprobe: name=aufs state=present
  when: ansible_distribution_release == 'trusty'

**Comment by thaJeztah** [comment] 2015-09-15 23:10
Did you run into this after installing using `curl -sSL https://get.docker.com | sh`, or when using ansible?

**Comment by CaptTofu** [comment] 2015-09-16 17:27
After installing via curl. I would get the aufs error. This was stock 14.04.

**Comment by thaJeztah** [comment] 2015-09-16 22:43
Strange, because those steps are [part of the install script; [hack/install.sh#L255-L273](https://github.com/docker/docker/blob/master/hack/install.sh#L255-L273)

Are you installing on bare metal, or on a cloud provider? Just to be sure, could you;

- provide the output of `uname -a`, `uname -r`
- the output of the commands mentioned in https://github.com/docker/docker/pull/15001#issuecomment-125721830

I'll try to reproduce this as well

**Comment by thaJeztah** [comment] 2015-09-16 23:01
I spun up a fresh 14.04 droplet on DigitalOcean, but I'm unable to reproduce; docker installed successfully, with aufs.

this is the output of the relevant commands;

uname -a

    Linux issue-16327 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```
root@issue-16327:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

root@issue-16327:~# lsb_release -a -u
Usage: lsb_release [options]

lsb_release: error: no such option: -u
root@issue-16327:
```

**Comment by LK4D4** [comment] 2016-09-13 19:23
Closing as @thaJeztah was unable to reproduce. Feel free to open new issue if problem persist.

**Closed by LK4D4** 2016-09-13 19:23 UTC
