### ISSUE TITLE
PROPOSAL: docker readme

### ISSUE THREAD

**Issue by wyaeld** [docker/docker#8077] opened 2014-09-17 01:02 UTC
I've been thinking about a way to be able to easily, consistency self-document images.

There are various reasons why someone might not be using an automated build, or  the person consuming the image doesn't have access to where the Dockerfiles are kept.

Would it make sense to have `docker readme <imagename>` which behaves in a similar way to `man`, but where the maintainer can leave instructions for the people using the image, in the form of a `readme.{txt/md}` in the root path of the image?

**Comment by jfrazelle** [comment] 2015-02-25 23:04
closing as duplicate of https://github.com/docker/docker/issues/6805

**Closed by jfrazelle** 2015-02-25 23:04 UTC
