### ISSUE TITLE
cmd jamed  unregister_netdevice: waiting for lo to become free. Usage count = 1

### ISSUE THREAD

**Issue by xcl3721** [docker/docker#22289] opened 2016-04-25 09:15 UTC
**Output of `docker version`:**
version:1.9.0
go 1.4.2
76d6bc9
build: tue nov 3 18:00:05 utc 2015
os/arch: linux/amd64
```
(paste your output here)
```
dmesg will out put
[13064037.892855] INFO: task docker:102958 blocked for more than 120 seconds.
[13064037.893254] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[13064037.894046] docker          D ffff88203e6b3680     0 102958      1 0x00000080
[13064037.894051]  ffff88102526bd30 0000000000000086 ffff88102526bfd8 0000000000013680
[13064037.894056]  ffff88102526bfd8 0000000000013680 ffff8810253fc440 ffffffff819e1860
[13064037.894059]  ffffffff819e1864 ffff8810253fc440 00000000ffffffff ffffffff819e1868
[13064037.894062] Call Trace:
[13064037.894071]  [<ffffffff8160b039>] schedule_preempt_disabled+0x29/0x70
[13064037.894075]  [<ffffffff81608d65>] __mutex_lock_slowpath+0xc5/0x1c0
[13064037.894080]  [<ffffffff816081cf>] mutex_lock+0x1f/0x2f
[13064037.894085]  [<ffffffff814f5381>] copy_net_ns+0x71/0x130
[13064037.894090]  [<ffffffff8109c579>] create_new_namespaces+0xf9/0x180
[13064037.894093]  [<ffffffff8109c71e>] copy_namespaces+0x8e/0xd0
[13064037.894098]  [<ffffffff8106c775>] copy_process.part.25+0x925/0x14e0
[13064037.894102]  [<ffffffff8106d4ec>] do_fork+0xbc/0x360
[13064037.894105]  [<ffffffff8106d816>] SyS_clone+0x16/0x20
[13064037.894109]  [<ffffffff81614d79>] stub_clone+0x69/0x90
[13064037.894113]  [<ffffffff81614a29>] ? system_call_fastpath+0x16/0x1b
[13064038.886519] unregister_netdevice: waiting for lo to become free. Usage count = 1

cmd docker ps  will jamed

**Output of `docker info`:**
jamed

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
uname -a
centos 
Linux bx-docker008 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-04-25 21:58
Looks like a duplicate of https://github.com/docker/docker/issues/5618

**Comment by thaJeztah** [comment] 2016-05-12 17:48
Yeah, I think it's a duplicate, so closing as dup of https://github.com/docker/docker/issues/5618

**Closed by thaJeztah** 2016-05-12 17:48 UTC
Labels: kind/question
