### ISSUE TITLE
run fails with open /cpuset/docker/[newcontiainerid]/cpuset.cpus: no such file or directory 

### ISSUE THREAD

**Issue by nealmcb** [docker/docker#9654] opened 2014-12-13 17:42 UTC
I recently did an Ubuntu update manager "partial upgrade" (oops) and docker stopped working.  My existing container seems to have exited about that time.
Now when I try to run any image I get: FATA[0000] Error response from daemon: Cannot start container <newcontainerid>: open /cpuset/docker/[newcontiainerid]/cpuset.cpus: no such file or directory 

Doing clean apt-get update/upgrade and rebooting didn't help.  I'm running Docker 1.4.0 and lxc-docker-1.4.0 in an up-to-date Ubuntu Precise 12.04 with the 14.04 kernel HWE

**Comment by aurelien-minvielle** [comment] 2015-01-20 16:12
Same error here with docker 1.4.1.

FATA[0000] Error response from daemon: Cannot start container 45614dff9783564a5d14e7a636b09d8a47cd0d5429e6e110711003f1da4b010a: open /cpuset/docker/45614dff9783564a5d14e7a636b09d8a47cd0d5429e6e110711003f1da4b010a/cpuset.cpus: no such file or directory

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy

$ uname -a
Linux solo 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt2-1~bpo70+1 (2014-12-08) x86_64 GNU/Linux

Works fine with docker 1.3.1.

**Comment by JGiard** [comment] 2015-02-26 15:36
I have the same error on debian wheezy with docker 1.5.0 and kernel 3.16.

**Comment by mszabo** [comment] 2015-02-26 15:40
Hello,

I had this problem as well. I had to umount the cgroups fs and remove it
from fstab. After a dockerd restart it started to work.

Regards,
  Mark

**Comment by JGiard** [comment] 2015-02-26 15:53
thanks, removing the cgroup mount worked for me.

**Comment by ugurlu** [comment] 2015-03-24 15:53
same happens with ubuntu 14.04.2 and lxc-docker-1.5.0 works with lxc-docker-1.3.3

**Comment by unclejack** [comment] 2015-03-24 15:59
For those who are having problems, please provide the output from the following commands (a single comment for the output from all commands, not individual comments):
- full output form `docker info`
- full output from `docker version`
- `uname -a` output
- full output from `mount`

**Comment by ranjith19** [comment] 2015-03-31 12:01
```
$ sudo docker info
Containers: 67
Images: 667
Storage Driver: devicemapper
 Pool Name: docker-202:0-99219-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 35.17 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 59.99 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.18.5-x86_64-linode52
Operating System: <unknown>
CPUs: 6
Total Memory: 7.83 GiB
Name: li341-247
ID: ABRQ:2ELU:COYI:YN4P:FQXO:E4LZ:NKTU:64DM:CJLP:WZ3E:43VN:KHWH
Username: mammothdev
Registry: [https://index.docker.io/v1/]
WARNING: No memory limit support
WARNING: No swap limit support
```


```
$ sudo docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8/1.4.1
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8/1.4.1
```

```
$ uname -a
Linux li341-247 3.18.5-x86_64-linode52 #1 SMP Thu Feb 5 12:18:36 EST 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ mount
/dev/xvda on / type ext4 (rw,noatime,errors=remount-ro)
/proc on /proc type proc (rw)
sysfs on /sys type sysfs (rw)
devpts on /dev/pts type devpts (rw,gid=5,mode=620)
tmpfs on /dev/shm type tmpfs (rw,noexec,nosuid,nodev,mode=1777)
none on /cgroup type cgroup (rw)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw)
```

**Comment by LK4D4** [comment] 2015-03-31 15:38
@ranjith19 You have no cgroups mounted. Docker won't work without cgroups.

**Comment by nealmcb** [comment] 2015-04-08 22:26
Thanks to unclejack , LK4D4 et al. for helping track this down.  I've now got lxc-docker-1.5.0:amd64 installed and everything seems to be working well.  My original problem could have been the cgroups error or whatever, but it doesn't happen any more.

So this issue can be closed as far as I can see, unless it is possible to be clearer in terms of how to deal with this if people run across it and find this discussion, or perhaps by making the error message more helpful.

**Comment by thaJeztah** [comment] 2015-04-08 23:40
@nealmcb good to hear you were able to resolve your problem! I'm going to close this issue, feel free to ping me if you are able to reproduce the problem again, then I'll reopen.

**Closed by thaJeztah** 2015-04-08 23:40 UTC

**Comment by tmm1** [comment] 2015-04-22 02:45
I ran into this issue on an ubuntu precise 12.04 instance running a 3.13.0 trusty kernel, after upgrading from docker 1.0.0 to any one of: 1.4.1, 1.5.0, 1.6.0. The root cause was a missing `/sys/fs/cgroup/cpuset`, which I had to mount manually. The other cgroup subsystems were all mounted correctly.

cc http://stackoverflow.com/a/27479610/332798

**Comment by calavera** [comment] 2015-04-27 21:53
Libcontainer assumes that all cgroups are properly mounted or it fails. https://github.com/docker/libcontainer/pull/476 should fix the root of this issue.

There is also a new hard requirement in Docker that will ensure the necessary cgroups are mounted: https://github.com/docker/docker/pull/11882

**Comment by brbmendes** [comment] 2015-07-17 16:09
For me, it worked rebooting the machine.

**Comment by mortzu** [comment] 2015-09-29 00:57
```
# docker info                                                                                                                                     :(
Containers: 34
Images: 19
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 2.6.32-openvz-042stab111.11-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 2
Total Memory: 1 GiB
Name: ci-runner-2
ID: KFYJ:YWWS:RW5P:L6JE:PE7X:FBDB:5O4B:DBYB:UEB5:2WIV:PSVF:BJXS
```

```
# docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:08:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:08:05 UTC 2015
 OS/Arch:      linux/amd64
```

```
# mount
/dev/ploop40632p1 on / type ext4 (rw,relatime,barrier=1,data=ordered,balloon_ino=12)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,mode=755)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/cpu,cpuacct,cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu,cpuset,name=fairsched)
cgroup on /sys/fs/cgroup/freezer,devices type cgroup (rw,nosuid,nodev,noexec,relatime,freezer,devices,name=container)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio,name=beancounter)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
tmpfs on /tmp type tmpfs (rw)
mqueue on /dev/mqueue type mqueue (rw,relatime)
none on /run/shm type tmpfs (rw,relatime)
```

**Comment by willstudy** [comment] 2016-12-01 07:06
#### docker info
```
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 2
Server Version: 1.11.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0_2-0-0-0
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.6 GiB
Name: gzns-dumi-boss2.gzns.baidu.com
ID: MC6X:U5IG:KXI7:MPMB:SY6O:47FB:7ETP:XJWE:WCNS:7YZT:4BCY:XK46
Docker Root Dir: /home/work/docker/runtime_1.11
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```
#### docker version
```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
```
#### uname -a
```Linux  3.10.0_2-0-0-0 #1 SMP Tue Sep 20 17:18:54 CST 2016 x86_64 x86_64 x86_64 GNU/Linux```

#### mount
```
/dev/sda2 on / type ext2 (rw)
proc on /proc type proc (rw)
sysfs on /sys type sysfs (rw)
devpts on /dev/pts type devpts (rw,gid=5,mode=620)
tmpfs on /dev/shm type tmpfs (rw)
/dev/sda3 on /var type ext2 (rw)
/dev/sda4 on /noah type ext2 (rw)
/dev/sda5 on /tmp type ext2 (rw)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw)
/dev/sda8 on /home type ext4 (rw)
cgroup on /sys/fs/cgroup type tmpfs (rw,uid=0,gid=0,mode=0755)
```
But the docker daemon output 
```
time="2016-12-01T14:35:05.411511614+08:00" level=info msg="Loading containers: done."
time="2016-12-01T14:35:05.411538637+08:00" level=info msg="Daemon has completed initialization"
time="2016-12-01T14:35:05.411569669+08:00" level=info msg="Docker daemon" commit=4dc5990 graphdriver=overlay version=1.11.0
time="2016-12-01T14:35:05.431040369+08:00" level=info msg="API listen on [::]:2375"
time="2016-12-01T14:35:05.431138080+08:00" level=info msg="API listen on /var/run/docker.sock"
time="2016-12-01T14:35:05+08:00" level=error msg="containerd: start container" error="oci runtime error: open /cgroups/cpuset/sys/cpuset.cpus: no such file or directory" id=7fb87c09fbeabc352e2a3d6805917d2fd53e3783a9df1d65bf5698a191e26272
time="2016-12-01T14:35:05.964405392+08:00" level=error msg="Handler for POST /containers/7fb87c09fbeabc352e2a3d6805917d2fd53e3783a9df1d65bf5698a191e26272/start returned error: Container command '/pause' not found or does not exist."
time="2016-12-01T14:35:17+08:00" level=error msg="containerd: start container" error="oci runtime error: open /cgroups/cpuset/sys/cpuset.cpus: no such file or directory" id=b53db009afcae81d0bb5ba1241725017557a0953741b44674154569c1d507e44
time="2016-12-01T14:35:17.599451111+08:00" level=error msg="Handler for POST /containers/b53db009afcae81d0bb5ba1241725017557a0953741b44674154569c1d507e44/start returned error: Container command '/pause' not found or does not exist."
```
@unclejack   What's wrong with my docker daemon ? Thanks very much

**Comment by anasanjaria** [comment] 2017-03-30 12:06
Hi,
I am facing a similar issue when I tried to run docker image. Here is my error:

`container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"open /sys/fs/cgroup/docker/cpuset.cpus: no such file or directory\""
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"open /sys/fs/cgroup/docker/cpuset.cpus: no such file or directory\"".`

I found a solution but when I shutdown my system I need to all these steps again. 

**Solution**
```
mount /sys/fs/cgroup


mkdir -p /sys/fs/cgroup/systemd
mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
mkdir -p /sys/fs/cgroup/systemd/user
echo $$ > /sys/fs/cgroup/systemd/user/cgroup.procs 
dockerd
```
[Reference](https://github.com/docker/docker/issues/18922#issuecomment-167421092)

Can you please tell me whats the problem? 

docker info

`Containers: 20
 Running: 0
 Paused: 0
 Stopped: 20
Images: 11
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 64
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.244 GiB
Name: anjaria
ID: KQMV:J7L2:KY2S:SLIF:USQJ:H3YG:7CX7:5UJG:EAJ3:QVGU:3GEW:NKX3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

docker version

`Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
`

Modify `/etc/default/grub`
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash systemd.legacy_systemd_cgroup_controller=yes"`
