### ISSUE TITLE
Fedora 32: Failed to start docker.service: Unit docker.socket failed to load: No such file or directory.

### ISSUE THREAD

**Issue by nmvega** [docker/docker#25559] opened 2016-08-10 04:42 UTC
Hello friends:

I installed docker on Fedora-23 (the Fedora binaries from the Docker repository, not from the Fedora repository - FYI). Now, because I want to change the home directory (among other things) for where image are stored -- from the default of /home/user to /home/jdoe -- I had to create and populate the file: /etc/systemd/system/docker.service.d/docker.conf. I did this following various instructions from Fedora and Docker support sites (both of which differ slightly).

In the end, I keep getting this failure no matter what I try:

Failed to start docker.service: Unit docker.socket failed to load: No such file or directory.

See below. Is there something that I am missing, or that I have incorrect. Again, when one wants to customize docker parameters (such as change the home directory location), one needs to implement /etc/systemd/system/docker.service.d/docker.conf; but doing that is causing this issue for me. When I remove that file or comment every line out, the problem goes away, but then of course I cant customize things.

Any assistance appreciated! =:) Thank you! See information below.

```
jdoe@g750asus$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

jdoe@g750asus$ pwd; ls -1a
/etc/systemd/system/docker.service.d
-rw-r--r--   1 root root  613 Aug  9 22:42 docker.conf

jdoe@g750asus$ cat docker.conf
========================================================
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket
PartOf=docker.service

[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --graph="/home/jdoe/docker.d" -H tcp://192.168.0.15:4243 unix:///var/run/docker.socket --storage-driver=overlay
Type=notify
LimitNOFILE=1048576
LimitNPROC=1048576
TasksMax=1048576

[Socket]
ListenStream=/var/run/docker.socket
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
Also=docker.socket
WantedBy=sockets.target
========================================================

jdoe@g750asus$ ls -la ~jdoe/.docker/
jdoe@g750asus$

jdoe@g750asus$ ls -la /var/run/docker.socket
-rw-rw---- 1 root docker 0 Aug 10 00:20 /var/run/docker.socket

jdoe@g750asus$ sudo systemctl start docker
Failed to start docker.service: Unit docker.socket failed to load: No such file or directory.
```

**Comment by VRanga000** [comment] 2016-08-10 14:58
Seeing the same issue when provisioning a VM with centos7 using docker-machine

**Comment by thaJeztah** [comment] 2016-08-10 15:26
Docker 1.12.0 has an updated systemd unit file for rpm based installs (which includes Fedora, and CentOS); if you're upgrading from an older version and have;

1. modified the default unit file (`/usr/lib/systemd/system/docker.service`), or
2. created a drop-in file to override the default unit file

The upgrade to docker 1.12 may not have updated the unit file with the latest changes (1.), because yum/dnf does not replace files if it found that it contains local changes. Or (2.) the drop-in file contains an outdated `ExecStart` line, which still uses `-H fd://` (which only works in combination with socket-activation).

To resolve this:

- Backup your current version, and replace the `/usr/lib/systemd/system/docker.service` file with the version that's shipped with docker 1.12 (https://github.com/docker/docker/blob/v1.12.0/contrib/init/systemd/docker.service.rpm), or
- Remove the `Requires=docker.socket` directive from the `/usr/lib/systemd/system/docker.service` file
- Remove `-H fd:// ` from the `ExecStart` directive (both in the main unit file, and in any drop-in files you have)

After making those changes, run `sudo systemctl daemon-reload`, and `sudo systemctl restart docker` to reload changes and (re)start the docker daemon.

**Comment by thaJeztah** [comment] 2016-08-10 15:29
@VRanga000 provisioning with docker machine is fixed through https://github.com/docker/machine/pull/3624, but I'm not sure that's in a release already

**Comment by ghostsquad** [comment] 2016-09-01 18:41
@thaJeztah thanks - I can confirm that your instructions worked for me. The problem was that my dropin service file had the `-H fd://` and `Requires=docker.socket`

**Comment by thaJeztah** [comment] 2016-09-15 09:57
I'm closing this issue, because I think the question is answered, and the above instructions should help people that ended up in this situation.

**Closed by thaJeztah** 2016-09-15 09:57 UTC

**Comment by nmvega** [comment] 2016-10-14 00:06
Hello friends:

@thaJeztah came super close to the resolution for me. It turns out that the entries he referred to, to modify (more precisely, to remove) can also be found here, if you manually created this file (as I did):

/etc/systemd/system/docker.service.d/docker.conf

(... actually, it could be called anything ending in ".conf", and it will be picked up. I just happened to use the sensible name of "docker.conf").

I had created it manually, but don't remember when or why; probably during an earlier (pre-RPM) installation of docker). Oh actually, I remember why: I wanted to customize the image and container directories (but I took another route using a symlink, so that file became unnecessary).

Performing a "rpm -qf /etc/systemd/system/docker.service.d/docker.conf" showed that it was not owned by any RPM package, so I simply moved it elsewhere (/tmp). Then uninstalled and reinstalled the docker RPMs for good measure, and this worked to resolve the issue for me. I could have, instead, deleted the entries that @thaJeztah referred to, but I no longer needed the file at all.

The summary is to also look for a .conf file in "/etc/systemd/system/docker.service.d/" for entries that may be problematic. =:). I hope this additional information helps someone.

Thank you!

**Comment by nmvega** [comment] 2016-10-14 00:21
P.S. Here is the docker.conf file contents (in case anyone is curious). But I have remove it from my system.

```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket
PartOf=docker.service

[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --graph="/home/MyUserName/docker.d" -H tcp://192.168.0.15:4243 unix:///var/run/docker.socket --storage-driver=overlay
Type=notify
LimitNOFILE=1048576
LimitNPROC=1048576
TasksMax=1048576

[Socket]
ListenStream=/var/run/docker.socket
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
Also=docker.socket
WantedBy=sockets.target
```

**Comment by fabioporta** [comment] 2017-01-10 15:40
You can change the startup script to remove the folder for you:
