### ISSUE TITLE
Remote API /build method should accept Dockerfile content as part of the payload

### ISSUE THREAD

**Issue by proppy** [docker/docker#12494] opened 2015-04-17 18:28 UTC
Currently the `/build` endpoint of the API [accept](https://github.com/docker/docker/blob/d12a2d8aeb483870ae064f70308e6ec7109f2a06/api/client/build.go#L287) an additional query parameter `?dockerfile=` that specify the path to the `Dockerfile` relative to the context.

This introduce the following limitations:
a. when using `-f`, the client will [fail](https://github.com/docker/docker/blob/d12a2d8aeb483870ae064f70308e6ec7109f2a06/api/client/build.go#L148) a build if the Dockerfile is not  contained in the context directory
b. this prevent reusing the same Dockerfile between different context.

What about passing the `Dockerfile` *content* in the `POST /build` payload instead? We could optionally accept a multipart body with both the `Dockerfile` and the `context.tar` content.

Related #8418 #12072.

**Comment by cpuguy83** [comment] 2015-04-17 19:36
@proppy This is by design if I'm not mistaken.

**Comment by proppy** [comment] 2015-04-17 20:05
@cpuguy83 yes, I'd like to discuss the limitation of the current design and possible evolution in this issue :)

**Comment by tianon** [comment] 2015-04-17 20:16
"./some-script.sh | docker build -f - some/context" would be pretty cool
too (and possible if it were a separate payload), IMO :+1:

**Comment by tianon** [comment] 2015-05-01 20:33
This would also make it possible to use `-f` to point at a `Dockerfile` that is technically in the context, but lives in `.dockerignore` (which is currently not possible).

**Comment by tianon** [comment] 2015-05-01 20:44
Gonna have to rescind my most recent comment -- `-f` on a file in `.dockerignore` does in fact work today. :+1:

**Comment by calavera** [comment] 2016-03-03 23:07
I'm closing this issue since it looks like there have not been any discussion about it in a year. Please, don't start it now. :wink:

Thanks a lot for your comments.

**Closed by calavera** 2016-03-03 23:07 UTC
Labels: kind/feature
