### ISSUE TITLE
Error when docker run piped command 

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#16273] opened 2015-09-13 22:46 UTC
```
[root@ovh2 /]# docker run --rm --volumes-from adt-wp-nginx -v /backup:/backup busybox tar -chf - /usr/share/nginx/www /etc/s6 /etc/nginx/| pv -L 5m > /backup/volumes_adt_wp_nginx_test.tar
tar: removing leading '/' from member names                                                                                                                                                                        ]
^C02GiB 0:03:28 [5,27MiB/s] [                         <=>                                                                                                                                                          ]
Error deleting container: Error response from daemon: Cannot destroy container 13aca325fa4c7cab0dc64c5efff968c8050a9c4dd1152a1f545d363632aa10d4: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f
write /dev/stdout: broken pipe
[root@ovh2 /]# docker ps
CONTAINER ID        IMAGE                                     COMMAND                CREATED             STATUS              PORTS                                                            NAMES
13aca325fa4c        busybox                                   "tar -chf - /usr/sha   3 minutes ago       Up 3 minutes                                                                         thirsty_kowalevski 
```
-------------
was what i did then i hited control + c and as you see it leaves a ghost container.
this is reproduce able

**Comment by frank-dspeed** [comment] 2015-09-13 23:00
Its reproduce able on all systems and versions including all storage drivers greetings.

**Comment by cpuguy83** [comment] 2015-10-01 01:39
Define a "ghost container".
If I had to guess, the tar is running.
Note that the command you are doing is piping commands to the client's shell, not in the container.

**Comment by cpuguy83** [comment] 2015-10-01 01:39
Also, please provide output of `docker version` and `docker info`.

**Comment by thaJeztah** [comment] 2015-11-02 00:33
Closing because we need more info, but happy to reopen after that

**Closed by thaJeztah** 2015-11-02 00:33 UTC
Labels: status/more-info-needed

**Comment by bobrik** [comment] 2016-01-29 09:57
@thaJeztah, @cpuguy83 I can provide more details. Ghost container is a running container you don't expect to be running.

```
bobrik@whatever: ~
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

bobrik@whatever: ~
$ docker run --rm alpine:3.3 /bin/sh -c 'while true; do date; sleep 1; done'
Fri Jan 29 09:41:57 UTC 2016
Fri Jan 29 09:41:58 UTC 2016
Fri Jan 29 09:41:59 UTC 2016
^C
bobrik@whatever: ~
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

bobrik@whatever: ~
$ docker run --rm alpine:3.3 /bin/sh -c 'while true; do date; sleep 1; done' | head -n1
Fri Jan 29 09:42:07 UTC 2016
Error deleting container: Error response from daemon: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f
write /dev/stdout: broken pipe

bobrik@whatever: ~
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
035d59cce261        alpine:3.3          "/bin/sh -c 'while tr"   10 minutes ago      Up 3 seconds                            determined_khorana
```

```
bobrik@whatever: ~
$ docker info
Containers: 1
Images: 399
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 423
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 2
Total Memory: 1.956 GiB
Name: dev
ID: OMPX:6CDR:MV3Z:RGOF:DTBS:G25L:EIY5:JWBE:6RFB:UZTO:XLMO:PEAR
Debug mode (server): true
 File Descriptors: 19
 Goroutines: 33
 System Time: 2016-01-29T09:42:25.678309895Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=vmwarefusion

bobrik@whatever: ~
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   a34a1d5
 Built:        Sun Jan 17 16:14:45 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

I think this happens because from docker engine's point of view nothing is wrong. Client disconnected, but this is no big deal, no need to kill the container that might be doing something useful.

On the other side, containers that are run this way are probably meant to be killed when they don't have a connected endpoint. Since docker client observes this error, it can gracefully stop the container.

If we are going to keep things the way they are, I think it's worth to at least document this behavior.

**Comment by hai-ld** [comment] 2016-04-12 08:29
@thaJeztah @cpuguy83 I have this problem too. You can do a quick check by this command
```
$ docker run --rm python:3.4 pip list | docker run --rm python:3.4 wc -l
0
Error deleting container: Error response from daemon: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f
write /dev/stdout: broken pipe
```

The docker container that couldn't be deleted is the one running `pip list`.

Interestingly, this does not raise error but `wc -l` still returns 0
```
$ docker run --rm python:3.4 ls | docker run --rm python:3.4 wc -l
0
```

My docker information:
```
$ docker info
Containers: 12
 Running: 1
 Paused: 0
 Stopped: 11
Images: 515
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /media/data1/docker/aufs
 Backing Filesystem: extfs
 Dirs: 511
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.6 GiB
Name: valhalla
ID: TXEV:XA22:T4RJ:GSTQ:Q67I:XKJQ:CGVZ:E42W:U2FM:IEP2:R5BI:3VNC
WARNING: No swap limit support
```
```
$ docker version 
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64
```

**Comment by hai-ld** [comment] 2016-04-12 10:47
My apologies. The problem seems to be caused by me forgetting to specify `-i` for the second `docker run`

```
$ docker run --rm python:3.4 pip list | docker run --rm -i python:3.4 wc -l
You are using pip version 8.0.3, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2
```

However, I don't understand why docker behaves this way. Anyone cares to explain?

**Comment by frank-dspeed** [comment] 2016-04-12 12:32
interisting point with -i thx hai-id
