### ISSUE TITLE
removed 12G /var/lib/docker and df shows no space was returned

### ISSUE THREAD

**Issue by e40** [docker/docker#21887] opened 2016-04-08 15:42 UTC
Just what the summary says.

OK, so I ran out of space on / and it messed up things in docker, so I decided to just rebuild my images and start over.

    # df -hl
    Filesystem               Size  Used Avail Use% Mounted on
    /dev/mapper/rootvg-root   30G   20G   11G  66% /

I stopped the docker service, moved `/var/lib/docker` to `/var/lib/docker.removeme` and started the docker service, which created `/var/lib/docker` again:

    # du -sh docker*
    115M	docker
    12G	docker.removeme
    # rm -fr docker.removeme
    # df -hl
    Filesystem               Size  Used Avail Use% Mounted on
    /dev/mapper/rootvg-root   30G   21G  9.2G  70% /
 
So, why didn't I get 12G back in the "Avail" from `df`?

Btw, in between the first and second `df` I build new containers so that's why there's more used.
```
box[git:master]# docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 34
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-100663428-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 1.298 GB
 Data Space Total: 107.4 GB
 Data Space Available: 9.556 GB
 Metadata Space Used: 2.306 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.15 GiB
Name: box...
ID: Z42T:CTBG:YGF7:BOAY:JQZP:BPCQ:RXIN:55ST:QAS5:NPMY:JG2Y:WC3O
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
box[git:master]# 
```

**Steps to reproduce the issue:**
See above

**Describe the results you received:**
No more free space.

**Describe the results you expected:**
12G more of free space.

**Comment by programmerq** [comment] 2016-04-08 16:10
did you stop docker before running your `rm -rf /var/lib/docker`? I would suspect that the loopback file is still mounted, so the space won't be returned until the loopback file is closed. Try stopping docker, which should unmount the loopback device.

**Comment by e40** [comment] 2016-04-08 16:29
Yes, I stopped the docker service first.  As I said in my report.  I've rebooted the machine since doing the remove and the space is still missing.

**Comment by e40** [comment] 2016-04-09 17:42
I'd like to point out that the machine running these docker containers has an SSD of limited size.  This is a pretty huge deal for me.  At some point, it will become a deal killer for running docker at all.

**Comment by cpuguy83** [comment] 2016-04-09 19:42
ping @rhvgoyal

**Comment by unclejack** [comment] 2016-04-11 18:33
@e40 The devicemapper block devices were most likely still active when you've run that command and that means the files used for devicemapper weren't deleted from the disk.

The correct procedure to be followed when attempting something like this is as follows:
1. disable the Docker daemon to ensure it's not getting started on boot by default
2. reboot
3. `rm -rf /var/lib/docker`
4. check if space has been freed
5. enable Docker again to start on boot automatically

In your case, you probably want to disable the Docker daemon, reboot and try to run `rm -rf /var/lib/docker` again.

Please keep in mind that Docker still requires a bit of setup on devicemapper because of the disk space usage, even though it's easy to start using Docker.

Your setup is also using loopback mounted block devices for devicemapper. This is the default and you might want to set up devicemapper on a real block device for increased data safety and performance.

**Comment by unclejack** [comment] 2016-04-11 19:29
I'm closing this in favour of #21348. Please comment on that issue instead.

**Closed by unclejack** 2016-04-11 19:29 UTC
Labels: area/storage/devicemapper, kind/question

**Comment by e40** [comment] 2016-04-11 19:39
@unclejack the directory in question was removed already.  The machine has been rebooted.  So, it would seem I can't execute your suggestions.  What now?

**Comment by thaJeztah** [comment] 2016-04-11 20:24
If both the `/var/lib/docker.removeme` directory and `/var/lib/docker` are deleted, and no space is returned, then something else is wrong, for example, perhaps you have some backup software installed that backups /var/lib/docker? This doesn't sound like a bug in Docker to me

**Comment by HackToday** [comment] 2016-04-12 00:54
@e40  maybe you could try above and check if it works: disable docker to not start at boot, and then reboot and then remove /var/lib/docker, and check if spaces return ?

**Comment by e40** [comment] 2016-04-12 14:50
@unclejack Perhaps you can clear something up for me: if I'm using the devicemapper in the default configuration, why do I have a `docker-pool` lvm?

```
box[git:master]# lvs
  LV          VG     Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker-pool rootvg twi-a-t--- 30.19g             0.06   0.04                            
  root        rootvg -wi-ao---- 30.00g                                                    
  swap        rootvg -wi-ao----  8.00g                                                    
box[git:master]# 

```

**Comment by rhvgoyal** [comment] 2016-04-12 16:11
@e40 which distribution are you using? On fedora/rhel/centos we use docker-storage-setup service to automatically setup an lvm thin pool for docker use. By default 40% of free space in volume group backing rootfs is used for thin pool.

**Comment by e40** [comment] 2016-04-12 17:00
Using centos 7.2.  I never ran docker-storage-setup.  I only learned about it in the last few days.

If I switch to docker-lvm, which it seems I should, can I just use the existing docker-pool lv?

**Comment by rhvgoyal** [comment] 2016-04-12 18:07
@e40, yes you can just use docker-pool lv. Given you are already using loop devices you will have to first cleanup that state.

Also I am curious why docker is not using thin pool already. Can you please paste contents of /etc/sysconfig/docker-storage and /etc/sysconfig/docker-storage-setup files.

**Comment by e40** [comment] 2016-04-12 20:00
```
@box[git:master]$ ls -l /etc/sysconfig/docker*
/bin/ls: cannot access /etc/sysconfig/docker*: No such file or directory
@box[git:master]$ 
```
I don't know if these files not existing is expected, or not.

**Comment by rhvgoyal** [comment] 2016-04-12 20:13
what about "systemctl status docker-storage-setup -l"

**Comment by e40** [comment] 2016-04-12 20:14
@rhvgoyal 

```
box[git:master]# systemctl status docker-storage-setup -l
systemctl status docker-storage-setup -l
● docker-storage-setup.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
box[git:master]# 

```

**Comment by e40** [comment] 2016-04-12 20:15
@rhvgoyal 

and
```
Installed Packages
docker-engine.x86_64                            1.10.3-1.el7.centos  @dockerrepo
docker-engine-selinux.noarch                    1.10.3-1.el7.centos  @dockerrepo

```

**Comment by HackToday** [comment] 2016-04-13 00:22
try find what's your docker related configuration files in your machine.

like `sudo find / -name "docker*"` there should be something about your docker configuration, which can help you dig what's the issue is

**Comment by rhvgoyal** [comment] 2016-04-13 12:36
@e40 This is strange. You don't seem to have docker-storage-setup service file. That means it is not installed and then it should not have created thin pool.

If you don't have important data in thin pool, try deleting it, remove /var/lib/docker and restart docker and see if thin pool gets created again. Also check journal logs during startup and see if something is there.

**Comment by rhvgoyal** [comment] 2016-04-13 12:37
@e40 Also you seem to be running docker-engine package. For docker shipped with centos, we have created dependencies properly to run docker-storage-setup before docker so that it sets up thin pool properly. I have never tried docker-engine and I don't believe any such dependencies are there. So combination of two might not work well.

**Comment by thaJeztah** [comment] 2016-04-13 13:04
Yes, I think @e40 has the official Docker packages installed (not the Red Hat / CentOS packages); those don't ship with `docker-storage-setup`. But it still doesn't explain why removing `/var/lib/docker` doesn't return the disk space I think?

**Comment by e40** [comment] 2016-04-13 15:18
@thaJeztah is right, @rhvgoyal, I'm using the official Docker rpms not the CentOS ones since the latter are not as up-to-date as the Docker official ones.

@rhvgoyal you said:

> If you don't have important data in thin pool, try deleting it, remove /var/lib/docker and restart docker and see if thin pool gets created again. Also check journal logs during startup and see if something is there.

By "thin pool", do you mean the `docker-pool` lv?

**Comment by rhvgoyal** [comment] 2016-04-13 15:31
@e40 right. docker-pool lv. Again, make sure no important data is there. Once it is gone, all the data in there with it will be gone.
