### ISSUE TITLE
Docker daemon slow to start with 10k+ images

### ISSUE THREAD

**Issue by CBarraford** [docker/docker#9788] opened 2014-12-23 15:21 UTC
When you have 10k+ images, the docker daemon takes between 30-40 minutes to start (on ec2 c3.4xlarge instances).

```
[ ~]$ docker info
Containers: 37
Images: 10633
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 10708
Execution Driver: native-0.2
Kernel Version: 3.8.0-42-generic
Operating System: Ubuntu precise (12.04.2 LTS)
CPUs: 16
Total Memory: 29.4 GiB
Name: <hostname>
ID: YVYI:NOU7:EMEC:IQNQ:EAKM:34TU:QHHN:UUCP:WYHS:OO6T:5TLG:2GXT
Debug mode (server): true
Debug mode (client): false
Fds: 115
Goroutines: 87
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
[~]$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

**Comment by unclejack** [comment] 2015-01-27 16:56
@CBarraford `Kernel Version: 3.8.0-42-generic` - this kernel is no longer supported by Canonical: it's not getting any updates for security and severe bugs, it also has known data corruption bugs.
Please upgrade the kernel to the linux trusty lts kernel to get 3.13 and install system updates.

![Kernel support schedule](https://wiki.ubuntu.com/Kernel/Support?action=AttachFile&do=get&target=Ubuntu+Kernel+Release+Schedule.png)


I've tested to check if this is a real problem on a system with a 7200 RPM HDD and aufs with ~11k images, but didn't manage to reproduce the problem. The first start is indeed slower when the json image metadata isn't cached by the OS, but it's 10 times faster after that. The cold startup took around 20 seconds and about 2 seconds on a warm start.

The startup can be slow only if your storage is extremely slow, so you probably want to make sure you've got enough IOPS with the right latency provisioned. You can figure this out easily by restarting the Docker daemon after having already started it for the current OS boot and checking how long starting Docker takes on a cold fresh OS boot. This should help you figure out if this is a real problem or not.

Even though this is probably an issue with your disk, you most certainly want to update your kernel to something supported.

I'm going to close this issue now since I know we've merged patches which address this exact problem, I've also tested this to ensure it's no longer a problem and an unsupported kernel is involved.

Please feel free to comment.

**Closed by unclejack** 2015-01-27 16:56 UTC
