### ISSUE TITLE
Docker info on 1.5.0 not showing Data file and Metadata file after upgrade from 1.4.1

### ISSUE THREAD

**Issue by stefanberger** [docker/docker#10778] opened 2015-02-13 20:06 UTC
I upgraded a system from 1.4.1 (with a dyn. linked docker) to version 1.5.0 (with a dyn. linked docker) and now 'docker info' does not show the Datafile and Metadata file.

Both versions of docker were custom built from the tags v1.4.1 and v1.5.0 in git -- with the only difference that they are dynamically linked.

Here's the output of 1.4.1 (before upgrading and after downgrading):
<pre>
Containers: 50
Images: 28
Storage Driver: devicemapper
 Pool Name: docker-8:16-146145282-pool
 Pool Blocksize: 65.54 kB
 Data file: /openstack/docker/devicemapper/devicemapper/data
 Metadata file: /openstack/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1.498 GB
 Data Space Total: 10.62 TB
 Metadata Space Used: 46.25 MB
 Metadata Space Total: 16.11 GB
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 32
Total Memory: 125.9 GiB
Name: vizio-dev-host9
ID: KJSQ:FUCN:V3QB:RBA3:MCEK:SWSQ:CDOU:3KST:KI5J:LFPI:XGJP:MC6C
WARNING: No swap limit support
</pre>

Here's the output after the upgrade to docker 1.5.0:

<pre>
Containers: 51
Images: 28
Storage Driver: devicemapper
 Pool Name: docker-8:16-146145282-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 1.498 GB
 Data Space Total: 10.62 TB
 Metadata Space Used: 46.25 MB
 Metadata Space Total: 16.11 GB
 Udev Sync Supported: true
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 32
Total Memory: 125.9 GiB
Name: vvvvv-dev-host9
ID: SSUI:D6AN:PDDV:AHW4:IIRQ:3DCW:VNOS:4XKI:WODE:FCDF:P5XA:6WWN
WARNING: No swap limit support
</pre>

What could this be due to? The Data and Metadata file are actually being used by this docker 1.5.0 and after some quick checks nothing else seems to be wrong. 

One other thing to note is that this system may have been upgraded previously from possibly 1.3.x to 1.4.0 etc.

**Comment by jalmansor** [comment] 2015-02-16 15:54
I noticed this as well on CentOS 7 using the 1.5.0 binary. I stopped the daemon, wiped /var/lib/docker (my graph location), started the daemon again and it showed them fine after it recreated the directory.

**Comment by crosbymichael** [comment] 2015-02-23 19:08
ping @vbatts

**Comment by ptippett** [comment] 2015-03-03 18:59
@jalmansor Did you see any ill effects in your containers after doing this? Getting a fix is one thing, but if we can prove there are no side effects, perhaps we can deploy 1.5.0 with this issue for now.

**Comment by vbatts** [comment] 2015-03-20 20:32
@ptippett there are no side effects to this within the daemon. Though if there is tooling that is using the output of `docker info`, obviously that will not have the correct information.

I'm investigating this now.

**Comment by vbatts** [comment] 2015-03-23 19:08
From investigating this on Friday:
I was able to reproduce by starting a docker daemon, then a container, then `kill -9 PID` of the docker daemon. There may be other ways, but this did cause the data/metadata device to not be shown.

Symptom:
The logic that sets up a device or loopback file is not touched. During the initialization of the devicemapper driver, the dm pool name is checked for, and if present is reused.

Cause:
The cleanup/shutdown of the deviemapper driver did not unmount the prior container, therefore did not remove the container's device. Though now can not remove the device and directory, as the existing mount has the device as busy.


Proposed fix:
On initialization, check for existing dm devices with our prefix, and umount them since they ought not be in use.

**Comment by vbatts** [comment] 2015-03-23 19:08
@rhvogyal ^^

**Comment by rhvgoyal** [comment] 2015-03-23 19:16
@vbatts 

I guess you are referring to following where if pool exists, we simply use it.

        // If the pool doesn't exist, create it
        if info.Exists == 0 && devices.thinPoolDevice == "" {

So does that mean that 1.4.1 was not cleaning the pool? Why would I see this over an upgrade?

**Comment by vbatts** [comment] 2015-03-23 19:19
@rhvgoyal prior to the break out of showing the block device file separate of loopback file, there was logic that looked for the attached device. I'll need to revisit the source on the v1.4.1 tag.

**Comment by rhvgoyal** [comment] 2015-03-23 19:20
Or is it the case where docker was shutdown, and for some reason container device could not be deactivated (not sure why) and that's why pool could not be shutdown (docker tried though), Then upgrade happened and docker was started and docker found the pool active and it went ahead and used it.

**Comment by vbatts** [comment] 2015-03-23 19:29
correct. and the existing devices and mounts are not able to be cleaned up. so the Shutdown() will fail to deactivate the devices and pool.

**Comment by rhvgoyal** [comment] 2015-03-23 19:30
Then it is not a 1.5 problem. It should be visible in 1.4.1 too.?

**Comment by rhvgoyal** [comment] 2015-03-23 19:34
I guess we really should not be doing anything here. We just found an active pool and did not setup the loop devices ourselves. 

If pool could not be shutdown by 1.4.1, there is no reason that your call to shutdown pool will succeed in 1.5.0 either.

I guess we can just give a warning "Thin pool % is already active. A new pool will no be setup". That itself will make it clear that docker did not setup pool so it has no idea what devices/files have been 
used as data/metadata.

**Comment by vbatts** [comment] 2015-03-23 19:43
@rhvogyal fair. Though what about when the pool is still presently due to dangling mounts from prior containers, that the daemon will never be able to clean up?

**Comment by rhvgoyal** [comment] 2015-06-16 14:40
@vbatts 

Yes, if pool can't be cleaned up due to devices being busy then upon restart of docker, a new pool is not setup and exisitng pool is used. In that case docker docker does not know that loop devices are being used. Hence loop device data does not show up in "docker info".

I was looking into this issue and I need some kind of go language support to get equivalent of "makedev(), major() and minor()" functions of libc. So that I can convert information reported from
kernel into major and minor numbers and then compare that against being reported by pool and conclude it is same loop devices.

Alternative is to use external comands like "stat" to get major/minor number of a loop file. I am not sure how portable that is.

**Comment by vbatts** [comment] 2015-06-16 18:43
https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/deviceset.go#L760
right? that and `os.Stat(path).Sys()` and cast that to `syscall.Stat_t`,
you can derive this.

**Comment by rhvgoyal** [comment] 2015-06-16 18:49
Oh, nice. So we already have helper functions for major() and minor().  I will use these.

**Comment by rhvgoyal** [comment] 2015-06-18 17:59
I opened another issue and generated a PR. I think that should fix this issue too.

https://github.com/docker/docker/pull/14021

**Comment by cpuguy83** [comment] 2015-07-23 13:43
Closing since #14021 was merged.
Also tested the repro case and it seems to work just fine now.

**Closed by cpuguy83** 2015-07-23 13:43 UTC
Labels: exp/expert, system/devicemapper
