### ISSUE TITLE
Docker daemon not honoring "--iptables=false"

### ISSUE THREAD

**Issue by lenovouser** [docker/docker#19211] opened 2016-01-09 19:14 UTC
Our Docker daemon is not honoring `--iptables=false`. As soon as I start a container configured to open a port on the host system with e.g . `-p 2022:2022` it adds rules to **iptables**.

**docker version:**
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64
```

**docker info:**
```
Containers: 5
Images: 35
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 8
Total Memory: 31.18 GiB
```

**iptables -L:**
```
Chain DOCKER (1 references)
target       prot opt source      destination
ACCEPT       tcp   —  anywhere    172.17.0.2    tcp dpt:2022
```

**Comment by phenomax** [comment] 2016-01-09 20:28
Same problem here! :(

**Comment by mavenugo** [comment] 2016-01-09 20:31
@aboch can you PTAL ?

**Comment by thaJeztah** [comment] 2016-01-10 00:43
This is a duplicate of https://github.com/docker/docker/issues/19063 please subscribe to that issue to stay up to date

**Closed by thaJeztah** 2016-01-10 00:43 UTC
Labels: group/networking
