### ISSUE TITLE
Each section of a domain name only allows for 28 characters

### ISSUE THREAD

**Issue by polds** [docker/docker#18940] opened 2015-12-28 17:44 UTC
System 1
docker version: `Docker version 1.7.1, build 786b29d/1.7.1`
docker info:
```
Containers: 11
Images: 64
Storage Driver: devicemapper
 Pool Name: docker-202:1-264745-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.316 GB
 Data Space Total: 107.4 GB
 Data Space Available: 12.35 GB
 Metadata Space Used: 3.228 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-15.23.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.09
CPUs: 1
Total Memory: 3.679 GiB
Name: microservices-staging-i-6dd658db
ID: HEXZ:Z4IS:JWCM:KTWR:JTVG:Z7AG:TWAE:SNQM:EFHT:YQED:ABWI:LQA5
Username: ---
Registry: https://index.docker.io/v1/
```
uname -a: `Linux microservices-staging-i-6dd658db 4.1.7-15.23.amzn1.x86_64 #1 SMP Mon Sep 14 23:20:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

System 2:
docker version: `Docker version 1.8.3, build f4bf5c7`
docker info:
```
Containers: 14
Images: 481
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 509
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: V63O:M5ZO:ETVL:IXVQ:6RY5:5USD:MDKI:OPHV:LR42:UVPB:U3JZ:YWGB
Debug mode (server): true
File Descriptors: 23
Goroutines: 37
System Time: 2015-12-28T17:49:29.572882928Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: polds
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
uname -a: `Darwin Peters-MacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64`

I couldn't find this documented anywhere but ran into an issue where defining the hostname I kept receiving an `Invalid Argument` error when launching a container. After some exhaustive testing I found it was due to one of the parts of the hostname being longer than 28 characters. I have confirmed this both on Amazon Linux running Docker 1.7.1 and OSX running Docker 1.8.3.

So here is an example of things that won't work:

```
abcdefghijklmnopqrstuvwxyzabc.testing.my-example.com - First section is 29 characters
my-service-name.abcdefghijklmnopqrstuvwxyzabc.my-example.com - Second section is 29 characters
etc.
```

Doing one of the above as such yields the following result:

```
[#] docker run -d -h my-service-name.abcdefghijklmnopqrstuvwxyzabc.my-example.com mycontainer
316f7f
Error response from daemon: Cannot start container 316f7f: [8] System error: invalid argument
```

So it's literally each domain section is limited to the 28 characters. 

If this is documented somewhere please feel free to close. I could not find it documented anywhere.

**Comment by daehyeok** [comment] 2015-12-28 21:04
no problem in the master branch

```
docker --version
Docker version 1.10.0-dev, build a581fb9-dirty
```

```
docker run -i -t -h my-service-name.abcdefghijklmnopqrstuvwxyzabc.my-example.com ubuntu /bin/bash
root@my-service-name:/# hostname
my-service-name.abcdefghijklmnopqrstuvwxyzabc.my-example.com
```

**Comment by thaJeztah** [comment] 2015-12-30 13:51
I'm unable to reproduce this, I tried it on;

- docker 1.9.1, running on Ubuntu 14.04 (DigitalOcean)
- docker 1.9.1, running on boot2docker

I'll close this issue, because I'm unable to reproduce this on the current release, but please comment if you're still able to reproduce this on docker 1.9.1 or newer

**Closed by thaJeztah** 2015-12-30 13:51 UTC
