### ISSUE TITLE
Docker Error response from daemon: No such image even when the image exists

### ISSUE THREAD

**Issue by milosgajdos83** [docker/docker#10708] opened 2015-02-11 14:01 UTC
Description of problem:
When trying to run one of our images, docker crashes with ```Error response from daemon: No such image``` even though the image IS already downloaded and available on the host.

Command to run:
```
docker run -d --net=host -v $($SSH_AUTH_SOCK):/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent $ORGANIZATION/socat-ssh
```

Error:
```
Status: Image is up to date for myorg/socat-ssh:latest
FATA[0002] Error response from daemon: No such image: myorg/socat-ssh (tag: latest)
```

Docker images:
```
$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
myorg/socat-ssh   latest              721a612b5779        2 weeks ago         128.4 MB
```

`docker version`:
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

`docker info`:
Containers: 2
Images: 11
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 15
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 1
Total Memory: 994.1 MiB
Name: jenkins
ID: JJ7Y:U5VK:7HAS:275N:INPI:KVEB:HHAV:WPRC:CXHG:GSD4:HQAM:I2OY
Debug mode (server): true
Debug mode (client): false
Fds: 10
Goroutines: 12
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support

`uname -a`:
Linux jenkins 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Vagrant in Virtualbox.

How reproducible:
See above

**Comment by cpuguy83** [comment] 2015-02-11 14:25
Debugging with @milosgajdos83 on IRC.
This appears to be a parsing problem since the call to `$($SSH_AUTH_SOCK)` is not correct, but he also had the issue with the correct syntax `$SSH_AUTH_SOCK`, but $SSH_AUTH_SOCK was empty.

When this issue occurs Docker tries to re-download the image. If you supply a name, instead of Docker saying it can't find the image it says there is already a container with that name (even though there wasn't).

**Comment by cmbaron** [comment] 2015-03-11 18:09
I am experiencing the same symptoms today with boot2docker and Docker 1.5, was there ever a resolution or workaround for this?

$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

$ docker info
Containers: 22
Images: 112
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 156
Execution Driver: native-0.2
Kernel Version: 3.18.5-tinycore64
Operating System: Boot2Docker 1.5.0 (TCL 5.4); master : a66bce5 - Tue Feb 10 23:31:27 UTC 2015
CPUs: 8
Total Memory: 1.961 GiB
Name: boot2docker
ID: YIYY:NN5T:2WGO:UQVS:VODB:B4FR:2NGK:BHR4:M2KN:2FQ2:YHZ6:WXLH
Debug mode (server): true
Debug mode (client): false
Fds: 41
Goroutines: 38
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: cmbaron
Registry: [https://index.docker.io/v1/]

$ boot2docker info
{
	"Name": "boot2docker-vm",
	"UUID": "6781a87e-d3be-4d22-b9b7-5f8bf463632a",
	"Iso": "/Users/cbaron/.boot2docker/boot2docker.iso",
	"State": "running",
	"CPUs": 8,
	"Memory": 2048,
	"VRAM": 8,
	"CfgFile": "/Users/cbaron/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox",
	"BaseFolder": "/Users/cbaron/VirtualBox VMs/boot2docker-vm",
	"OSType": "",
	"Flag": 0,
	"BootOrder": null,
	"DockerPort": 0,
	"SSHPort": 2022,
	"SerialFile": "/Users/cbaron/.boot2docker/boot2docker-vm.sock"
}

**Comment by estesp** [comment] 2015-03-11 18:50
I think this could be one of several issues related to graph `IsNotExist()` processing going wrong (note that @LK4D4 mentions that has been the source of multiple issues lately in PR #11281).  It makes sense given the return from `/create` is probably a 404 for some reason, and so it tries an image pull.  If it's not related to the graph, it could be some other part of the path that gets a 404 which is wrongly being interpreted at the client as image doesn't exist during `/create` handling.

**Comment by cmbaron** [comment] 2015-03-12 18:19
From the logs below, it appears that create() claims that the image does not exist.  Although, I admit I am out of my depth interpreting this log.

time="2015-03-12T18:10:57Z" level="info" msg="-job pull(cmbaron/app, latest) = OK (0)" 
time="2015-03-12T18:10:57Z" level="debug" msg="Calling POST /containers/create" 
time="2015-03-12T18:10:57Z" level="info" msg="POST /v1.17/containers/create" 
time="2015-03-12T18:10:57Z" level="info" msg="+job create()" 
No such image: cmbaron/app (tag: latest)
time="2015-03-12T18:10:57Z" level="info" msg="-job create() = ERR (1)"

**Comment by cmbaron** [comment] 2015-03-20 15:04
FWIW, I finally got back to looking at this and with fresh eyes I spotted the cause of the failure. It's an empty value preceding the ':' in the argument to "-v"

$docker run -t -i --rm -v :/app cmbaron/app /bin/bash -l
FATA[0003] Error response from daemon: No such image: cmbaron/app (tag: latest) 

docker run -t -i --rm -v /home/cmbaron:/app cmbaron/app /bin/bash -l
e627596420be:/app$ echo "eureka"

**Comment by estesp** [comment] 2015-03-20 15:12
ah, yeah, so makes sense with what I mentioned before--we have had a rash of command line processing errors that end up coming back to the client side as "image not found" (because of the 404 response).  @coolljt0725 will your proposed #11281 fix this as well?

**Comment by coolljt0725** [comment] 2015-03-21 02:20
@estesp  I think #11281  will fix this. In this use case `daemon.Create(config, hostConfig, name)`
will return `no such file or directory` and ` if daemon.Graph().IsNotExist(err)` just check if the error contain `no such`, so the problem happen.  ` if daemon.Graph().IsNotExist(err)`  should check if the 
error contain `config.Image`, so I think #11281  can fix this.

**Comment by estesp** [comment] 2015-03-21 03:05
:+1:

**Comment by vineyugave** [comment] 2016-07-12 19:59
Solved it by doing this : 
$ VBoxManage list vms
"default" {f13e52ac-22f6-4171-a48a-f3c25578c764}
$ VBoxManage modifyvm f13e52ac-22f6-4171-a48a-f3c25578c651 --natdnshostresolver1 on

That did it

**Comment by thaJeztah** [comment] 2016-07-12 23:29
I think the original issue reported here was fixed by https://github.com/docker/docker/pull/11281, so I'll close this

**Closed by thaJeztah** 2016-07-12 23:29 UTC
Labels: version/1.4
