### ISSUE TITLE
Docker embarrasing slow on execution

### ISSUE THREAD

**Issue by zopyx** [docker/docker#10248] opened 2015-01-21 19:56 UTC
Running my own image on a CentOS 7 host, clean installation, no other jobs running is embarrassing slow.

docker run -p 12020:12020 zopyx/xmldirector-plone

takes in the range 5 to 10 minutes under Docker control.

Running the same code on same virtual machine usually takes less than one minute.

The image starts eXist-db, pre-allocates the CMS Plone and starts it.

The related Dockerfile is here

https://github.com/xml-director/xmldirector.plonecore/tree/master/docker

which uses this as base image

https://github.com/xml-director/xmldirector.plonecore/tree/master/docker/base

Also the load of the VM goes over the top and climbs up to 10

-------------

[ajung@docker ~]$ uname -a
Linux docker.zopyx.com 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[ajung@docker ~]$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
[ajung@docker ~]$ docker -D info
Containers: 3
Images: 62
Storage Driver: devicemapper
 Pool Name: docker-253:1-201327949-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 3.474 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 4.448 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 3
Total Memory: 3.704 GiB
Name: docker.zopyx.com
ID: 2CWZ:EWWZ:TNZT:NHN7:H4VE:JOEN:PQZG:XVJG:AJMH:2PVK:JYOX:E4UY
Debug mode (server): false
Debug mode (client): true
Fds: 23
Goroutines: 39
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: zopyx
Registry: [https://index.docker.io/v1/]

**Comment by crosbymichael** [comment] 2015-01-27 00:01
Do you have a way for us to create a similar VM as this is not typical and I'm scared that if we don't have an exact setup it will be super hard to reproduce and help on this issue.

A Vagrantfile or even a virtualbox backup would help.

**Comment by zopyx** [comment] 2015-01-27 07:52
According to other posts the problem seem to be the Devicemapper driver used on CentOS 6 and 7. There are numerous reports about similar behavior. I could reproduce the issue with two bare CentOS 6.6 and 7.0 installations running on the same box. Anyway...we moved these virtual machines to latest Ubuntu running AutFS and the user experience is as it should and how I would expect it.

**Comment by unclejack** [comment] 2015-01-27 13:58
@vbatts Have you seen anything like this?

**Comment by vbatts** [comment] 2015-01-27 17:36
From a clean install, it took 7 minutes just to download all the layers for `zopyx/xmldirector-plone`. 39 layers. That's not tiny.

The set up of the database and plone look to be huge IO hits, and yes the db allocate and plone setup took 4 minutes total.

The trouble here is that because docker is simple to run, does not mean that it is absolutely tuned for everyone's use-case, everywhere, all the time. Please consider the default assumption, what is going on, and what you need. Devicemapper is the most generic driver, largely because it is on most all linux's, and by default sets itself up on a loop back file to manage. 

If you loop at process table while this image is starting and setting up, you'll see that python is first, followed by the kernel traversing the loop back. 

```
15011 centos    20   0  303436 158016   6684 R 91.3  8.4   0:26.00 /home/plone/xmldirector.plonecore/../bin/python /home/plone/xmldirector.plonecore/parts/instance/bin/interpreter -c from Zope2 import configure; configure(r'/home/plone/x+
13056 root       0 -20       0      0      0 S  0.7  0.0   0:07.65 [loop0]
6 root      20   0       0      0      0 S  0.3  0.0   0:01.93 [kworker/u2:0]
```

If you are interested in a more fully established production runtime, or particularly high-IO, then _absolutely_ set up a dedicated block device for the devicemapper driver, and don't assume that because something works, that it is tuned to _you_. See https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/README.md

I'm closing this as it is not embarrassing on docker, but in assumptions that were made and due diligence wasn't taken to ensure settings were optimal for your use case.

**Closed by vbatts** 2015-01-27 17:36 UTC

**Comment by zopyx** [comment] 2015-01-27 17:52
Are you serious or just blind or ignorant or both of them?

The same odd behavior happened with CentOS 6.6 and 7 also with other more simple Dockerfile e.g. for installing BaseX or exists-sb. Your ongoing ignorance on serious issues and your works-for-me attitude sucks.

You receive $$$$$$$ of venture capital and work like tinkerers.

**Comment by vbatts** [comment] 2015-01-27 18:00
@zopyx please leave your aggression at the door. I do not work for docker.

**Comment by zopyx** [comment] 2015-01-27 18:13
Does it matter? The ignorance of the Docker devs are scary and your comment
is both stupid and wrong.

Basic operations like "useradd" or running "apt-get" are running 5-10 times
slower on CentOS 6.6 and 7.0.

What has this to do with my particular app installed after performing
common Dockerfile steps?

This is a *common* problem with *common* operations on  CentOS 6+7 with the
devicemapper and don't tell my that it is my Dockerfile.

And if I need special configuration for performing common operations on a
fresh CentOS 7 box then the installation of Docker should either provide a
reasonable configuration for that or simply communicate that Cent 6//7 +
Docker is out of the box a broken configuration.

Don't try to tell that I am an idiot, I am too long in the IT business in
order to know what is broken and working technology.

And Docker clearly falls into the category over-hyped, under-designed and
under-engineered bullshit.

2015-01-27 19:01 GMT+01:00 Vincent Batts <notifications@github.com>:

**Comment by crosbymichael** [comment] 2015-01-28 00:22
I'm sorry that you are having issues with Docker but we encourage a community of mutual respect between users, volunteers, and maintainers.

Though you’re free to share your opinions, please be respectful and follow the community guidelines outlined [here](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#docker-community-guidelines)
