### ISSUE TITLE
use docker exec to change /etc/hosts error

### ISSUE THREAD

**Issue by Jam-Lin** [docker/docker#15604] opened 2015-08-15 06:04 UTC
hello, i use ```docker exec 1ebea17823f3 echo test >> /etc/hosts ``` to change the container /etc/hosts,  but i find that the container hosts do not change. it change the vm /etc/hosts.

**Comment by thaJeztah** [comment] 2015-08-15 12:03
I think this is expected, and not a bug in docker; basically what your doing is;

```Bash
(docker exec 1ebea17823f3 echo test) >> /etc/hosts
```
(Added the parentheses to illustrate the problem) Basically, the `echo test` runs *inside* the container, but the *output* is returned to the host (vm) and added to `/etc/hosts` *of the VM*.

Try it this way, so that both the "echo" AND the `>> /etc/hosts` take place inside the container;

```Bash
docker exec 1ebea17823f3 /bin/sh -c "echo test >> /etc/hosts"
```

I'm going to close this issue, because it's not a bug, but I hope the above explanation helps you further!

**Closed by thaJeztah** 2015-08-15 12:03 UTC
