### ISSUE TITLE
Memory Stats stats "null" after upgrading to 1.11

### ISSUE THREAD

**Issue by CodingFabian** [docker/docker#22375] opened 2016-04-27 21:03 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 30
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/docker/aufs
 Backing Filesystem: extfs
 Dirs: 342
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 29.96 GiB
Name: ip-10-153-152-120
ID: DK42:EDNQ:Y6SG:7RR3:25VN:EMGH:XDH6:RIGU:EMRV:HSCD:V53O:PNTC
Docker Root Dir: /mnt/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Describe the results you received:**
 when performing 

    echo -ne "GET /containers/cc43cecb25b0195d740ae68e81451a5d7238a6db7d2bc1366c8bc6bb8b037144/stats HTTP/1.0\r\n\r\n" | sudo nc -q 5 -U /var/run/docker.sock

the memory_stats.stats section is empty:
```
{"read":"2016-04-27T21:00:33Z","precpu_stats":{"cpu_usage":{"total_usage":0,"percpu_usage":null,"usage_in_kernelmode":0,"usage_in_usermode":0},"system_cpu_usage":0,"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"cpu_stats":{"cpu_usage":{"total_usage":4341303184586,"percpu_usage":[1095363405711,1116566179332,1050078722879,1079294876664],"usage_in_kernelmode":1170440000000,"usage_in_usermode":2095430000000},"system_cpu_usage":118987410000000,"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"memory_stats":{"usage":2674970624,"max_usage":2747441152,"stats":null,"failcnt":0,"limit":32170233856},"blkio_stats":{"io_service_bytes_recursive":[{"major":202,"minor":4096,"op":"Read","value":0},{"major":202,"minor":4096,"op":"Write","value":73728},{"major":202,"minor":4096,"op":"Sync","value":0},{"major":202,"minor":4096,"op":"Async","value":73728},{"major":202,"minor":4096,"op":"Total","value":73728}],"io_serviced_recursive":[{"major":202,"minor":4096,"op":"Read","value":0},{"major":202,"minor":4096,"op":"Write","value":18},{"major":202,"minor":4096,"op":"Sync","value":0},{"major":202,"minor":4096,"op":"Async","value":18},{"major":202,"minor":4096,"op":"Total","value":18}],"io_queue_recursive":[],"io_service_time_recursive":[],"io_wait_time_recursive":[],"io_merged_recursive":[],"io_time_recursive":[],"sectors_recursive":[]},"pids_stats":{}}
{"read":"2016-04-27T21:00:34Z","precpu_stats":{"cpu_usage":{"total_usage":4341303184586,"percpu_usage":[1095363405711,1116566179332,1050078722879,1079294876664],"usage_in_kernelmode":1170440000000,"usage_in_usermode":2095430000000},"system_cpu_usage":118987410000000,"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"cpu_stats":{"cpu_usage":{"total_usage":4341472345867,"percpu_usage":[1095385054810,1116638571900,1050104815044,1079343904113],"usage_in_kernelmode":1170470000000,"usage_in_usermode":2095460000000},"system_cpu_usage":118991060000000,"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"memory_stats":{"usage":2674970624,"max_usage":2747441152,"stats":null,"failcnt":0,"limit":32170233856},"blkio_stats":{"io_service_bytes_recursive":[{"major":202,"minor":4096,"op":"Read","value":0},{"major":202,"minor":4096,"op":"Write","value":73728},{"major":202,"minor":4096,"op":"Sync","value":0},{"major":202,"minor":4096,"op":"Async","value":73728},{"major":202,"minor":4096,"op":"Total","value":73728}],"io_serviced_recursive":[{"major":202,"minor":4096,"op":"Read","value":0},{"major":202,"minor":4096,"op":"Write","value":18},{"major":202,"minor":4096,"op":"Sync","value":0},{"major":202,"minor":4096,"op":"Async","value":18},{"major":202,"minor":4096,"op":"Total","value":18}],"io_queue_recursive":[],"io_service_time_recursive":[],"io_wait_time_recursive":[],"io_merged_recursive":[],"io_time_recursive":[],"sectors_recursive":[]},"pids_stats":{}}
```

**Describe the results you expected:**
running the same for the same container on another instacne still running docker 1.9.0

```
{"read":"2016-04-27T20:25:57.848975794Z","precpu_stats":{"cpu_usage":{"total_usage":2836319781512,"percpu_usage":[1326177125488,527018532881,486271592733,496852530410],"usage_in_kernelmode":304660000000,"usage_in_usermode":1746480000000},"system_cpu_usage":21499257010000000,"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"cpu_stats":{"cpu_usage":{"total_usage":2836328515244,"percpu_usage":[1326180655922,527023151840,486272105286,496852602196],"usage_in_kernelmode":304660000000,"usage_in_usermode":1746480000000},"system_cpu_usage":21499260900000000,"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"memory_stats":{"usage":1300934656,"max_usage":1314185216,"stats":{"active_anon":1196941312,"active_file":35741696,"cache":103866368,"hierarchical_memory_limit":18446744073709551615,"inactive_anon":0,"inactive_file":68124672,"mapped_file":23048192,"pgfault":501671,"pgmajfault":437,"pgpgin":409404,"pgpgout":376962,"rss":1196941312,"rss_huge":1126170624,"total_active_anon":1196941312,"total_active_file":35741696,"total_cache":103866368,"total_inactive_anon":0,"total_inactive_file":68124672,"total_mapped_file":23048192,"total_pgfault":501671,"total_pgmajfault":437,"total_pgpgin":409404,"total_pgpgout":376962,"total_rss":1196941312,"total_rss_huge":1126170624,"total_unevictable":0,"total_writeback":0,"unevictable":0,"writeback":0},"failcnt":0,"limit":32170233856},"blkio_stats":{"io_service_bytes_recursive":[{"major":7,"minor":0,"op":"Read","value":0},{"major":7,"minor":0,"op":"Write","value":16384},{"major":7,"minor":0,"op":"Sync","value":0},{"major":7,"minor":0,"op":"Async","value":16384},{"major":7,"minor":0,"op":"Total","value":16384},{"major":252,"minor":0,"op":"Read","value":0},{"major":252,"minor":0,"op":"Write","value":16384},{"major":252,"minor":0,"op":"Sync","value":0},{"major":252,"minor":0,"op":"Async","value":16384},{"major":252,"minor":0,"op":"Total","value":16384},{"major":252,"minor":6,"op":"Read","value":92225536},{"major":252,"minor":6,"op":"Write","value":77824},{"major":252,"minor":6,"op":"Sync","value":0},{"major":252,"minor":6,"op":"Async","value":92303360},{"major":252,"minor":6,"op":"Total","value":92303360}],"io_serviced_recursive":[{"major":7,"minor":0,"op":"Read","value":0},{"major":7,"minor":0,"op":"Write","value":4},{"major":7,"minor":0,"op":"Sync","value":0},{"major":7,"minor":0,"op":"Async","value":4},{"major":7,"minor":0,"op":"Total","value":4},{"major":252,"minor":0,"op":"Read","value":0},{"major":252,"minor":0,"op":"Write","value":4},{"major":252,"minor":0,"op":"Sync","value":0},{"major":252,"minor":0,"op":"Async","value":4},{"major":252,"minor":0,"op":"Total","value":4},{"major":252,"minor":6,"op":"Read","value":5669},{"major":252,"minor":6,"op":"Write","value":19},{"major":252,"minor":6,"op":"Sync","value":0},{"major":252,"minor":6,"op":"Async","value":5688},{"major":252,"minor":6,"op":"Total","value":5688}],"io_queue_recursive":[],"io_service_time_recursive":[],"io_wait_time_recursive":[],"io_merged_recursive":[],"io_time_recursive":[],"sectors_recursive":[]}}
```

So something has changed for memory_stats.stats to be "null". and I could not find it in release notes for API 1.22 or 1.23

**Comment by thaJeztah** [comment] 2016-04-27 21:51
Looks like this changed in 1.11.0, as 1.10.3 still returns this through the API. Possibly an issue in containerd, as I think these are added here, https://github.com/docker/docker/blob/a0a6d031d76c1bf9d5581a8310b8a2d1df4b7b82/daemon/daemon_unix.go#L1095-L1102, which comes from here; 
https://github.com/docker/docker/blob/885e5eb5f7784f9e5d218d4446595609f83304a8/libcontainerd/client_linux.go#L247-L253

ping @tonistiigi @mlaventure any ideas?

**Comment by tonistiigi** [comment] 2016-04-28 01:44
I made a fix for it in containerd https://github.com/docker/containerd/pull/224 . Should we decide to do `1.11.2` and include this, the fix is a bit different (field name is `Stats`) because the stats code has changed a lot in containerd/runc.

**Comment by glasser** [comment] 2016-05-19 07:16
@tonistiigi Has this been ported to 1.11 yet? Running into this in production.

**Comment by tonistiigi** [comment] 2016-05-19 16:21
@glasser This should be fixed on master(#22511). There has been no `v1.11.x` versions released after this was reported.

**Comment by glasser** [comment] 2016-05-19 17:03
Yeah, I saw that. Is there likely to be a 1.11.2 any time soon? This regression is blocking upgrade for us and we install Docker from the dockerproject.org Ubuntu repo.

**Comment by tonistiigi** [comment] 2016-05-19 17:29
@glasser Atm, I think it looks unlikely that we will have `1.11.2` release. https://github.com/docker/docker/blob/master/project/PATCH-RELEASES.md#deciding-if-a-patch-release-should-be-done

**Comment by glasser** [comment] 2016-05-19 21:42
I mean, this means that Docker 1.11 fails to implement the stats API fully, and is a clear regression from 1.10.  It's P0 for our project (we can't upgrade without this).  @mlaventure Any chance of a 1.11.2 to allow us to upgrade and fix the stats API's memory_stats.stats section?

**Comment by mlaventure** [comment] 2016-05-19 22:19
@glasser unfortunately, this is quite unlikely.

Like @tonistiigi pointed out via the link on his previous comment, a new patch release is not going to be done unless we have a P0 issue reported and this is not the case atm.

**Comment by glasser** [comment] 2016-05-19 22:29
Accidentally dropping 29 documented fields from an API does not count as P0?  That surprises me.

Perhaps there could be an update to https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/ that deletes the 29 stats fields from the documentation of the stats API, since they are apparently not part of remote API 1.23?

**Comment by farcaller** [comment] 2016-05-19 22:56
I'm curious, given this doesn't have an explicit priority set, how important is it for docker to maintain the api guarantees? Is it something like ~P2 best-effort thing?

**Comment by redbaron** [comment] 2016-05-20 06:07
seriously, breaking documented compatibility in undocumented way (no mention in release notes, etc) and not rushing to fix it once discovered, that is laughable at best.

**Comment by icecrime** [comment] 2016-05-26 15:12
Bumping to P0: this will be fixed in an upcoming patch release.

**Comment by thaJeztah** [comment] 2016-05-27 15:47
fixed by https://github.com/docker/docker/issues/22955

**Closed by thaJeztah** 2016-05-27 15:47 UTC
Labels: area/api, kind/bug, priority/P0, version/1.11

**Comment by pcarrier** [comment] 2016-05-29 07:31
Great to hear!

In the meantime we've forked 1.11.1 here: https://github.com/meteor/docker/commit/41e813d2412a00a940e9a2e797eeba14e147e773
https://github.com/meteor/containerd/commit/13a0fee44bec5c22b6b62ac3210432fb3bb1d18f

**Comment by thaJeztah** [comment] 2016-05-29 08:54
@pcarrier docker 1.11.2-rc1 is available for testing through test.docker.com, release will be on tue or wed
