### ISSUE TITLE
BUG: New user specified overlay network is not available / not displayed on any other hosts (except the leader where it was created) on 1.12.0-rc4

### ISSUE THREAD

**Issue by ernestgwilsonii** [docker/docker#25004] opened 2016-07-25 11:19 UTC
New user specified overlay network is not available / not displayed on any other hosts (except the leader where it was created) on 1.12.0-rc4

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 11
Server Version: 1.12.0-rc4
Storage Driver: devicemapper
 Pool Name: docker-8:32-656935-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.973 GB
 Data Space Total: 107.4 GB
 Data Space Available: 9.919 GB
 Metadata Space Used: 5.452 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: active
 NodeID: 31umhnclg5g6g5ozj25jf8x3g
 IsManager: Yes
 Managers: 1
 Nodes: 25
 CACertHash: sha256:da6e36cb3aff7aa4f08046eb7cf34c9c816ce66627302d55edf41f6157746bef
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.699 GiB
Name: VA1EWTCENTDT01
ID: YPYV:5HXV:5VAG:XJP3:WGBK:H5PK:57LV:SHGZ:Y5B2:7TAO:RGKN:QWQT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
All CentOS7x OS fully patched in Swarm using 1.12.0-rc4

**docker node ls**

```
ID                           HOSTNAME        MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
0qf1vf3s04d8zgukjos4rdzte    VA1EWTCENTDT23  Accepted    Ready   Active
1f288gprvnp82m7qkqsua09dw    VA1EWTCENTDT09  Accepted    Ready   Active
1kavo01zxdgfmuxe285hjdns2    VA1EWTCENTDT24  Accepted    Ready   Active
29jkvlr77w2qrcbt56h4zo7ok    VA1EWTCENTDT20  Accepted    Ready   Active
2nxr3hajgn60ybjvj1ieaok6v    VA1EWTCENTDT11  Accepted    Ready   Active
2s6we11jakeetcteht983w5q3    VA1EWTCENTDT19  Accepted    Ready   Active
31umhnclg5g6g5ozj25jf8x3g *  VA1EWTCENTDT01  Accepted    Ready   Active        Leader
43y591vz3tytus099jto3dqa3    VA1EWTCENTDT04  Accepted    Ready   Active
6cpgzzy321uwg7s54zk6cvbai    VA1EWTCENTDT07  Accepted    Ready   Active
6fsfg1xhj941642qdc5trww6a    VA1EWTCENTDT18  Accepted    Ready   Active
6nertegcj4d5mtuce31udsezz    VA1EWTCENTDT12  Accepted    Ready   Active
79dskjmc0tttjl38977rqybvo    VA1EWTCENTDT22  Accepted    Ready   Active
8p1da9ujgdptjyi4j8mfbtrd3    VA1EWTCENTDT02  Accepted    Ready   Active
92y71snbrhpxx0oy35karj2qo    VA1EWTCENTDT16  Accepted    Ready   Active
ahtmzbwyao100enlk3vu4dhhl    VA1EWTCENTDT08  Accepted    Ready   Active
aluek8xscohnjdnutyw9xou2s    VA1EWTCENTDT14  Accepted    Ready   Active
b3p1nyewb08w2it85guu8qg1q    VA1EWTCENTDT10  Accepted    Ready   Active
bhwxs8df9rhblebxdwnaemwk0    VA1EWTCENTDT03  Accepted    Ready   Active
by10dadxjqx9e05r1q73v7fiy    VA1EWTCENTDT06  Accepted    Ready   Active
cu763jmr7vfdag5qpa533n91p    VA1EWTCENTDT13  Accepted    Ready   Active
cunc7yeh525i8tf76mocys7zt    VA1EWTCENTDT17  Accepted    Ready   Active
d0paugt5j5bm9ygpe9cfcwk7i    VA1EWTCENTDT15  Accepted    Ready   Active
dd0a9le6kwwyf0idxi4m1t3gm    VA1EWTCENTDT21  Accepted    Ready   Active
ditsbnd2kdjil68sqkxgp6t7d    VA1EWTCENTDT05  Accepted    Ready   Active
e5friyc946uu7fhcfbyj4rpcb    VA1EWTCENTDT25  Accepted    Ready   Active
```

**Steps to reproduce the issue:**
1.
I create an overlay network on the leader called "my-net"
```
docker network create --driver overlay --subnet=172.28.100.0/24 my-net
```

2.
I **see "my-net"** as overlay swarm on the leader:
```
[root@VA1EWTCENTDT01 ~]# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
9c0c78d1dce1        bridge              bridge              local
f11a222daa0d        docker_gwbridge     bridge              local
501a34d1538f        host                host                local
070ibdftaebg        ingress             overlay             swarm
26weem0k3yxt        my-net              overlay             swarm
2d891547a17a        none                null                local
```

3.
However on all other swarm members I **do not see "my-net"** (for example):
```
[root@VA1EWTCENTDT02 ~]# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
64ec321df5bb        bridge              bridge              local
fb0a741eca91        docker_gwbridge     bridge              local
3c9b7e9ab247        host                host                local
070ibdftaebg        ingress             overlay             swarm
25c0f463ba7a        none                null                local
```

**Describe the results you received:**
New user specified overlay network is not available / not displayed on any other hosts (except the leader where it was created) on 1.12.0-rc4

**Describe the results you expected:**
I was expecting to create a network (called "my-net" or "dev" for example) on the leader and then have / use that overlay network on all nodes in the swarm. Am I doing it wrong?

**Additional information you deem important (e.g. issue happens only occasionally):**
I assumed that the new overlay network in 1.112RC4 would allow me to create "--net-alias" or have some similar capability. 
For example, previously on a single host, I could bring up applications on a "dev" network like:
```
docker run --net dev -d --net-alias search elasticsearch
```
I was hoping to launch this demo application for example:
```
docker service create --replicas 1 --name trainingwheels -p:80:5000 --update-delay 10s --update-parallelism 1 jpetazzo/trainingwheels
docker service create --replicas 1 --name redis -p:6379:6379 --update-delay 10s --update-parallelism 1 redis
```
but I want this to live on the "my-net" overlay network and/or be able to specify which overlay network to use in the swarm. 
Right now, I am stuck,as you can see from the report above, I **can** indeed **create a new overlay network on the swarm leader** called for example "my-net" **but** that overlay network is **not propagated to any other nodes in the swarm** / other nodes do not display or list having "my-net".

Thank you all for the hard work and new feature in 1.12 - Can you please help steer me back on track?
Not sure if this is a bug or working as designed. The documentation is a bit light in this new area that 1.12 allows.
Either way, I am stuck and guidance is appreciated please. Thank you.

**Comment by rogaha** [comment] 2016-07-25 11:52
@ernestgwilsonii I had the same impression/expectations at first. But it seems that the `my-net` network will be propagated on the other nodes once you create a `service` that deploys tasks on them. Have you tried to create the `service` uses `my-net` from the same node you created the `my-net` overlay network?

**Comment by thaJeztah** [comment] 2016-07-25 11:59
I think this relates to the way swarm-scoped overlay networks work; currently it's not possible to use those networks for `docker run`, and only for `docker service create`; also see https://github.com/docker/docker/pull/24988

Swarm scoped networks work different, and are created *dynamically* on nodes when they are needed. On worker nodes, this means the network doesn't show up until a service that requires that network is deployed on that worker. On *manager* nodes, however, the network is directly visible.

For example, I just created a simple swarm with 4 nodes, three of those were managers. On a manager node, I created a `my-net` overlay network; on all *manager* nodes, I can directly see the `my-net` network;

```
docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
ac6d23b3f9cc        bridge              bridge              local
bbf233358de8        docker_gwbridge     bridge              local
cd163611f43b        host                host                local
2tyf879rlxlr        ingress             overlay             swarm
djjzmzxws7ly        my-net              overlay             swarm
2936ea141afd        none                null                local
```

However, on the *worker* node, the network doesn't appear;

```
docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
244296ab2b05        bridge              bridge              local
8a175c4da241        docker_gwbridge     bridge              local
4f85a015e0ca        host                host                local
2tyf879rlxlr        ingress             overlay             swarm
c1c5a6c61a24        none                null                local
```

Then, I created a service that uses the `my-net` network, and set it to use 4 replicas (making sure it's deployed on each node);

```
docker service create --network=my-net --name web --replicas=4 nginx:alpine
```

On the *worker* node, verify the service was deployed;

```
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
9177f1ac9950        nginx:alpine        "nginx -g 'daemon off"   13 seconds ago      Up 12 seconds       80/tcp, 443/tcp     web.4.6zzdihs2rr84o5uisgq0593q1
```

Checking the networks on that node, you can see that the `my-net` network is added to the list;

```
docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
244296ab2b05        bridge              bridge              local
8a175c4da241        docker_gwbridge     bridge              local
4f85a015e0ca        host                host                local
2tyf879rlxlr        ingress             overlay             swarm
djjzmzxws7ly        my-net              overlay             swarm
c1c5a6c61a24        none                null                local
```

**Comment by thaJeztah** [comment] 2016-07-25 12:11
(oh, just see @rogaha also replied (had this tab still open and GitHub didn't show it)).

Note that it *is* possible by joining the network namespace of an existing container, for example, if a  container that's part of a service is running on your host;

```
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
d35150c873c3        nginx:alpine        "nginx -g 'daemon off"   3 minutes ago       Up 3 minutes        80/tcp, 443/tcp     web.7.47qjzpufb2h3xnfy3g9dygm8d
780b4d4493cc        nginx:alpine        "nginx -g 'daemon off"   3 minutes ago       Up 3 minutes        80/tcp, 443/tcp     web.8.bik6pg5treletalg157wx9wjt
```

You can start a container, and join that container's network namespace, using `--network=container:...`;

```
docker run -it --network=container:d35150c873c3 --rm alpine sh
```

I'll close this issue, because this is not a bug, but we'll be looking into improving this, and see if it's possible to allow `docker run` to connect to swarm scoped networks (e.g. for debugging).

**Comment by ernestgwilsonii** [comment] 2016-07-25 12:12
OMG - Yes indeed. It turns out that "my-net" gets created on the worker node only as needed!
As soon as I scaled up the application:
```
docker service create --network=my-net --replicas 1 --name trainingwheels -p:80:5000 --update-delay 10s --update-parallelism 1 jpetazzo/trainingwheels
docker service create --network=my-net --replicas 8 --name redis -p:6379:6379 --update-delay 10s --update-parallelism 1 redis
```
I do now indeed see "my-net" get propagated to nodes that run a copy of that application (redis for example):
```
[root@VA1EWTCENTDT01 ~]# docker service tasks redis
ID                         NAME     SERVICE  IMAGE  LAST STATE                  DESIRED STATE  NODE
cvqeqy7ogsgtohb1c7bfx0mjj  redis.1  redis    redis  Running about a minute ago  Running        VA1EWTCENTDT19
9heiot0uu4a8k295qlcc5hian  redis.2  redis    redis  Running about a minute ago  Running        VA1EWTCENTDT02
0z9cqtpzomblvry5h0s2hqijs  redis.3  redis    redis  Running about a minute ago  Running        VA1EWTCENTDT22
24kaejhznfvcjzo59oxnjqnvk  redis.4  redis    redis  Running about a minute ago  Running        VA1EWTCENTDT25
272n87m3qc6uvpi33mxr8e7kn  redis.5  redis    redis  Running about a minute ago  Running        VA1EWTCENTDT24
bxzshbo2h1kr93neg42d9qia5  redis.6  redis    redis  Running about a minute ago  Running        VA1EWTCENTDT01
eszg80ou4eln6ivj25qpd1v82  redis.7  redis    redis  Running about a minute ago  Running        VA1EWTCENTDT08
9oxcxs6qtt4wwsa3mm00j8ls1  redis.8  redis    redis  Running about a minute ago  Running        VA1EWTCENTDT16
and
[root@VA1EWTCENTDT02 ~]# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
64ec321df5bb        bridge              bridge              local
fb0a741eca91        docker_gwbridge     bridge              local
3c9b7e9ab247        host                host                local
070ibdftaebg        ingress             overlay             swarm
26weem0k3yxt        my-net              overlay             swarm
25c0f463ba7a        none                null                local
``` 
and the application and overlay network "my-net" does indeed work correctly / as expected.

I was expecting the new overlay network to get propagated to every node in the swarm by default.
It turns out that only nodes that need to use that network have it configured.
Doh! (face palm) - Please consider this matter closed!
Thank you all!

**Closed by thaJeztah** 2016-07-25 12:11 UTC
Labels: version/1.12

**Comment by thaJeztah** [comment] 2016-07-25 12:18
@ernestgwilsonii no problem at all! I can see this being confusing, and you'll likely not be the last person asking this (so we probably need to pay some attention to this in the docs).

Although I've not been part of the design stage for this part, I assume this is done for performance; there's no need to create the network on each node, if it's not used, and only the *managers* need to be aware that the network exist (so that they can use it for services).

Ping @sfsmithcha do you know if we haven an issue for making this clearer in the documentation?

**Comment by sfsmithcha** [comment] 2016-07-25 16:15
@thaJeztah  this is a core feature of networking in Swarm mode, which is slated for documentation. I've filed an issue to track: https://github.com/docker/docker/issues/25011
