### ISSUE TITLE
docker should print meaningful "NAMES" column for interactive jobs

### ISSUE THREAD

**Issue by wkoszek** [docker/docker#16880] opened 2015-10-09 10:17 UTC
From 1st terminal I execute:

`docker run -t -i wkoszek-nginx /bin/bash`

from another I'm typing: `docker ps`. Repeat the sequence 2 times. Results:

```
root@labs:~# docker ps
CONTAINER ID        IMAGE                  COMMAND                CREATED              STATUS              PORTS                NAMES
81b662ff8dc2        wkoszek/nginx:latest   nginx -g 'daemon off   About a minute ago   Up About a minute   0.0.0.0:80->80/tcp   wkoszek-nginx
0e6b1b23bf75        web:latest             /bin/bash              2 minutes ago        Up 2 minutes        80/tcp               stoic_jones
root@labs:~# docker ps
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS                NAMES
fd8b3efb97c8        web:latest             /bin/bash              2 seconds ago       Up 2 seconds        80/tcp               kickass_hopper
81b662ff8dc2        wkoszek/nginx:latest   nginx -g 'daemon off   2 minutes ago       Up 2 minutes        0.0.0.0:80->80/tcp   wkoszek-nginx
```

Seems like docker is picking ephemeral names each time I start a different interactive job.

These names confused the great deal out of me, since I initially believed somebody else is playing with my machine. I'd prefer to see something meaningful here, for example: `<loginname>:pid=<pid>`.

**Comment by duglin** [comment] 2015-10-09 10:59
When you say "each time" its not clear if you mean for "each ps" or for "each container created".

Docker will not change the name of container for "each ps". In the example you've shown, the name
of the web:latest container changes because its a different container - see the containerID changes.

As for each container getting ephemeral names, Docker has no real way of knowing what's going on in the container or what information from the container might be useful to use as a name so it will just pick a name at random. Even "login" might not be very helpful since, as an example, in my case it would show "root" each time and showing names that are almost the same might actually be harder to distinguish/remember. If users want more helpful names it is recommended that they assign their own during the create/run step.

Going to close this since Docker is working as designed. If I missed something please feel free to reopen it.

**Closed by duglin** 2015-10-09 10:59 UTC

**Comment by wkoszek** [comment] 2015-10-11 17:58
I know Docker is working as designed, but I'm questioning this design here. What I do in loop is:

- Terminal 1: `docker run -t -i wkoszek-nginx /bin/bash`
- Terminal 2: `docker ps`

So I hear what you say, but picking random aliases that don't mean anything in the system context is not the greatest strategy. Having anything from within the OS / user would be better. Having `<unnamed>` would be better too.
