### ISSUE TITLE
Please add a way to discover the container ID from within the container

### ISSUE THREAD

**Issue by ademaria** [docker/docker#3506] opened 2014-01-08 14:18 UTC
Hi,

I would like to be able to discover the container ID when running from within the container itself.

I would use the $HOSTNAME but then it would be overwritten when using 

    docker run -h newdomainname

In general it would be able to expose an API to the internal container only, i.e. the way you can get metadata information on EC2 instances.

Regards
Alessandro

**Comment by jfrazelle** [comment] 2015-02-25 22:11
also related https://github.com/docker/docker/issues/8427

**Comment by jfrazelle** [comment] 2015-02-25 22:12
@ademaria if you think the issue I linked coveres your concerns you are more than welcome to close this so we can cleanup house a bit, otherwise no worries it can stay open

**Comment by jfrazelle** [comment] 2015-02-28 03:20
closing as duplicate of https://github.com/docker/docker/issues/8427

**Closed by jfrazelle** 2015-02-28 03:20 UTC
