### ISSUE TITLE
Docker Panic when executing a Post to /exec/<id>/start

### ISSUE THREAD

**Issue by chosenken** [docker/docker#19269] opened 2016-01-12 20:47 UTC
I am testing some ways of getting the file contents out of a running container using the remote api.  While testing I had the docker daemon panic on me and spit out a long stack trace.  The stack trace can be found at https://gist.github.com/chosenken/99b38d6353289fbf234b.

This happened in a docker-machine on my Mac.  Here is the docker info:

``` shell
Containers: 2
Images: 64
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 68
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 2
Total Memory: 996.1 MiB
Name: default
ID: FA6O:OVN6:OS6U:3KPI:3R2D:CLOZ:QG55:4VRD:6CCD:TRK3:MQQA:ULFR
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 19
 System Time: 2016-01-12T20:30:02.98559786Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: chosenken
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

And Docker version:

``` shell
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

This is what I was doing at the time that caused the panic:

In a new tab, execut

``` docker run -it ubuntu bash ```

In the container, execut

```
cd /tmp
apt-get update && apt-get install openssl
openssl rand -base64 741 > keyfile
echo "sed ':a;N;\$!ba;s/\n/\\\n/g' /tmp/keyfile" > getKeyFile
```

In another terminal window call the docker api:

```
$ curl --cacert $DOCKER_CERT_PATH/ca.pem --cert $DOCKER_CERT_PATH/cert.pfx --pass supersecret -H "Content-Type: application/json" -X POST -d '{"AttachStdin":false,"AttachStdout":true,"AttachStderr":true,"Tty":false, "Cmd":["sh", "/tmp/getKeyFile"]}' https://192.168.99.100:2376/containers/2ff117dd68ff/exec
{"Id":"500be8168d189652b35949a500700c5f8fa84131e51ce2584f350f8f532de03e"}
$ curl --cacert $DOCKER_CERT_PATH/ca.pem --cert $DOCKER_CERT_PATH/cert.pfx --pass supersecret -H "Content-Type: application/json" -X POST -d '{"Detach":false,"Tty":false}' https://192.168.99.100:2376/exec/500be8168d189652b35949a500700c5f8fa84131e51ce2584f350f8f532de03e/start
```

Note:  If you are wondering what the cert.pfx is, I got around the curl tls issue in osx by creating it using the following command [from here](https://opensolitude.com/2015/07/12/curl-docker-remote-api-os-x.html):
```openssl pkcs12 -export -in $DOCKER_CERT_PATH/cert.pem -inkey $DOCKER_CERT_PATH/key.pem -out $DOCKER_CERT_PATH/cert.pfx -password pass:supersecret```

**Comment by thaJeztah** [comment] 2016-01-16 08:52
thanks for reporting, @chosenken I think this may be a duplicate of https://github.com/docker/docker/issues/19362 (or the other way around, because this issue is older), and should be fixed by https://github.com/docker/docker/pull/19369


ping @cpuguy83 do you think this is fixed by https://github.com/docker/docker/pull/19369?

**Comment by cpuguy83** [comment] 2016-01-16 11:48
Yep, looks like it.

**Closed by cpuguy83** 2016-01-16 11:48 UTC
Labels: kind/bug
