### ISSUE TITLE
gnutls_handshake() failed while accessing apt.dockerproject.org

### ISSUE THREAD

**Issue by gionn** [docker/docker#28474] opened 2016-11-16 11:12 UTC
Since today, https mirror is failing on every node with:

    Err https://apt.dockerproject.org ubuntu-trusty/main amd64 Packages
    gnutls_handshake() failed: Handshake failed

Workaround is to switch to http mirror in sources.list

Found on twitter someone else writing about this: https://twitter.com/schulzbo/status/798791665464901632

**Comment by thaJeztah** [comment] 2016-11-16 11:19
Thanks for reporting @gionn, we are aware of this, and are still investigating. There looks to be an issue with our CDN (Cloudfront), and some mirrors are having this issue. Also see the discussion here; https://github.com/docker/docker/issues/16941#issuecomment-260877805

This IP address is known to work, so as a temporary measure you can add this to your `/etc/hosts`;

```
54.230.142.136 apt.dockerproject.org
```

**Comment by joelnb** [comment] 2016-11-16 11:44
Thanks @thaJeztah your workaround is working nicely for me.

**Comment by thaJeztah** [comment] 2016-11-16 12:35
A quick status update; the infra team is now working on this issue as well, and is currently in contact with AWS. So far it looks like the issue is not on our side, but I'll post more information when it becomes available

**Comment by The-Compiler** [comment] 2016-11-16 13:38
What about updating Travis-CI status in the meantime so people are aware of this?

**Comment by vdemeester** [comment] 2016-11-16 13:41
@The-Compiler I think you're on the wrong repository (it's `docker` here, we don't have anything to do with travis :angel:)

**Comment by shouze** [comment] 2016-11-16 13:50
@thaJeztah looks like from travis-ci if I force the DNS resolution to IP `54.230.142.136` it's not working, I have this message:
```
 Failed to connect to apt.dockerproject.org port 443: Connection refused
```

Can I spefify instead the IP `54.230.47.98`?

**Comment by thaJeztah** [comment] 2016-11-16 14:00
Status update: the team is still working together with AWS locating the problem.

**Comment by thaJeztah** [comment] 2016-11-16 15:23
Just got informed that AWS identified a possible cause and is rolling out updates. It may take some time for those to be available everywhere. Hopefully the issue will be resolved by that

For those that used my workaround; don't forget to remove the entry from your `/etc/hosts` :smile:

**Comment by BanzaiMan** [comment] 2016-11-16 15:58
@thaJeztah FYI, we are still seeing the issue from a GCE instance:

```sh-session
$ cat /etc/apt/sources.list.d/docker.list
deb https://apt.dockerproject.org/repo ubuntu-trusty main

$ sudo apt-get update | tail
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  Failed to connect to apt.dockerproject.org port 443: Connection refused

E: Some index files failed to download. They have been ignored, or old ones used instead.
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://ppa.launchpad.net trusty Release
Hit http://ppa.launchpad.net trusty Release
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Ign http://ppa.launchpad.net trusty/main Translation-en_US
Ign http://ppa.launchpad.net trusty/main Translation-en
Ign http://ppa.launchpad.net trusty/main Translation-en_US
Ign http://ppa.launchpad.net trusty/main Translation-en
Fetched 1,167 kB in 5s (220 kB/s)
```

**Comment by thaJeztah** [comment] 2016-11-16 16:04
@BanzaiMan I don't know how long the rollout of that update will take, but will post updates if I get more information. If may just take time 😢

**Comment by BanzaiMan** [comment] 2016-11-16 16:11
@thaJeztah Thanks. I will be patient. :-)

**Comment by spa-87** [comment] 2016-11-16 16:13
about 30 minutes ago AWS support answered to my request:
> We're investigating reports of intermittent TLS connection timeouts to CloudFront endpoints from certain Linux command-line tools that use the GnuTLS library. We are in the process of re-routing affected requests to minimize impact. 

Currently the issue seems to be resolved for us.

**Comment by aerialcarrot** [comment] 2016-11-16 16:15
This is now working for me.

**Closed** 2016-11-16 17:17 UTC
Labels: area/project
