### ISSUE TITLE
docker commit failing.

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#22992] opened 2016-05-25 20:02 UTC
I am not able to commit a new container on docker upstream binary.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   a41e823
 Built:        Wed May 25 15:46:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   a41e823
 Built:        Wed May 25 15:46:25 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.0-dev
Storage Driver: devicemapper
 Pool Name: docker-8:19-16121939-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 255.5 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.1 GB
 Metadata Space Used: 753.7 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.2-301.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.72 GiB
Name: dhcp-10-19-62-127.boston.devel.redhat.com
ID: M4W2:KN7L:WVHC:KGXZ:ZNAN:CJJJ:5PWS:V7VV:GPHO:65Y3:4UEP:MCUX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: shm32
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 23

**Steps to reproduce the issue:**
1. docker run -it  fedora /bin/bash
2. Inside the container shell: echo foobar > /home/foobar.txt
3.  docker ps (Get the container ID)
4.  docker commit {container_id} fedora_foobar

**Describe the results you received:**
Error response from daemon: Error: driver devicemapper is returning inconsistent paths for container ace09224bda2df50c9da884ebc5b2d01eed1c39321f73e73f3b02458d8ad2519 ('/var/lib/docker/devicemapper/mnt/824107f221e531a9e402602f5233f7cc9bc64a70dab127643b181c1012a8ab98/rootfs' then '/var/lib/docker/devicemapper/mnt/824107f221e531a9e402602f5233f7cc9bc64a70dab127643b181c1012a8ab98')

**Describe the results you expected:**
container should be committed successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-05-25 20:11
How did you start the daemon? With systemd? Did you use the docker.unit from this repository, or the Red Hat one? I seem to recall that mount-options could have an influence on this.

**Comment by shishir-a412ed** [comment] 2016-05-25 20:25
@thaJeztah I didn't started it using a systemd unit file.
Just started in manually by giving the path to my binary. `sudo /home/smahajan/docker/src/github.com/docker/docker/bundles/1.12.0-dev/dynbinary-daemon/dockerd -D`.

**Comment by thaJeztah** [comment] 2016-05-25 21:06
@shishir-a412ed ok, thanks!

@cpuguy83 I think you recently mentioned something like this? Not sure if it was on devicemapper though

**Comment by cpuguy83** [comment] 2016-05-25 21:08
I have not seen this, but it looks like something is wrong with the path caches for devmapper.
@shishir-a412ed Does this have the graphdriver restore patch in that was merged yesterday?

**Comment by shishir-a412ed** [comment] 2016-05-25 22:03
@cpuguy83 Yes it is completely up to date with upstream master branch.

@thaJeztah @cpuguy83 On closer look (git bisect), this {git commit} `1f8fbbc0d830ad9a887d04a25152ea344688903b` introduced the bug.
I tried to docker commit my container with the {git commit} before this, and I was able to successfully commit it.

Looking more into this now.

Shishir

**Comment by thaJeztah** [comment] 2016-05-25 22:12
For easier finding; this commit https://github.com/docker/docker/commit/1f8fbbc0d830ad9a887d04a25152ea344688903b (PR is https://github.com/docker/docker/pull/22966)

**Comment by shishir-a412ed** [comment] 2016-05-25 22:31
@thaJeztah yeah this is so strange ! On quick look this patch looks like nothing to do with the `docker commit` problem :).

The error message is related to `container.BaseFS != dir` (where dir is the mount point where the container rootfs is mounted). 

https://github.com/docker/docker/blob/master/daemon/daemon.go#L686

`container.BaseFS` has a value `/var/lib/docker/devicemapper/mnt/{ID}/rootfs`. IIRC container used to be mounted at rootfs directory i.e. rootfs used to be the mount point. Now when I do `docker run`, the container is mounted at `/var/lib/docker/devicemapper/mnt/{ID}` directory so the paths don't match and hence the error.

I checked it again, and before this {git commit} `1f8fbbc0d830ad9a887d04a25152ea344688903b` I am able to docker commit successfully. This commit just doesn't seem to be related, again the devil is always in the details !

**Comment by AkihiroSuda** [comment] 2016-05-26 09:18
https://github.com/docker/docker/commit/1f8fbbc0d830ad9a887d04a25152ea344688903b is mine..

@shishir-a412ed 
Can you deterministically reproduce the issue with 1f8fbbc0?
Maybe the issue is non-deterministic and `git bisect` happened to hit the issue when it was at 1f8fbbc0.

I'll try to reproduce the issue

**Comment by AkihiroSuda** [comment] 2016-05-26 09:47
Uh, I can 100% hit the issue as well with 1f8fbbc, but 0% with the previous commit 29dbcbad878483d9239d6a432c85620aced895c4 :cry:

**Comment by shishir-a412ed** [comment] 2016-05-26 17:44
@AkihiroSuda Just FYI both these bugs are only on devicemapper. Not on overlay. Haven't tested other storage drivers yet.

**Comment by runcom** [comment] 2016-05-26 17:48
ping @rhvgoyal

**Comment by LK4D4** [comment] 2016-05-26 20:40
It's really-really-really weird.

**Comment by thaJeztah** [comment] 2016-05-26 20:44
@LK4D4 should we revert https://github.com/docker/docker/pull/22966 for now?

**Comment by thaJeztah** [comment] 2016-05-26 20:44
Or does it expose a bug in device mapper that was already there?

**Comment by LK4D4** [comment] 2016-05-26 20:44
There is no rush in reverting anything now. I think we have time to investigate.

**Comment by AkihiroSuda** [comment] 2016-05-27 07:07
https://github.com/docker/docker/issues/22992#issuecomment-221826896
> Uh, I can 100% hit the issue as well with 1f8fbbc, but 0% with the previous commit 29dbcba :cry:

My previous comment is wrong, I can 100% hit the issue with commit 29dbcba + a clean graph directory (`dockerd -g ...`)
So #22966(1f8fbbc) is unrelated to the issue.

Perhaps the issue depends on the state of the graph directory, I think that is why both @shishir-a412ed and I could not hit the issue without #22966(1f8fbbc) at that time.

I confirmed I'm testing 29dbcba by running `docker version`:
```
docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   29dbcba
 Built:        Fri May 27 06:44:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   29dbcba
 Built:        Fri May 27 06:44:23 2016
 OS/Arch:      linux/amd64
```
----

@shishir-a412ed Could you please bisect the issue with a clean graph directory?

**Comment by shishir-a412ed** [comment] 2016-05-27 18:19
This issue was caused by the refcounts PR #22168.
I have opened a PR to fix this.

ping @thaJeztah @cpuguy83 @LK4D4

**Closed** 2016-05-27 22:06 UTC
Labels: area/storage/devicemapper, kind/bug, status/needs-attention, version/master
