### ISSUE TITLE
Push restarts from scratch after timeouts

### ISSUE THREAD

**Issue by fustbariclation** [docker/docker#27623] opened 2016-10-21 06:15 UTC
**Description**

Push restarts from scratch after timeouts. This means my pushes take several days to complete. If only, when it restarts, it could continue from where it was with a partially uploaded chunk, it would complete after only a few re-tries.

Even worse. With the example below, the chunk 92313c584362 often gets to the stage were it says 'Pushed'... but, when it restarts, it forgets this, and starts the push all over again.

The example below has been re-run repeatedly for about 10 hours. It times out after 19 minutes. Each time the load of 92313c584362 nearly gets to 177Mb, then the timeout happens. When it restarts, it starts all over again. If it could remember where it was and continue the push from there, this would have completed hours ago.

The push refers to a repository [docker.synapse.org/syn7364819/blue]
93d8703dde2a: Pushed 
934396e52c9d: Pushed 
8efaddf4ca67: Pushed 
0397e998d125: Pushed 
92313c584362: Pushing [===========================================>       ] 153.4 MB/177 MB
4a4f58055766: Pushing 1.536 kB
adb25476d2c1: Retrying in 1 second 
655a6c01124a: Retrying in 1 second 
0de3b0993fca: Pushing [==================================================>] 49.15 kB
2253b7eea5e6: Retrying in 1 second 
05b90b2afe02: Retrying in 1 second 
ec96d31f8eaf: Retrying in 1 second 
e3ac10d00c60: Retrying in 1 second 
2c2153fbd032: Retrying in 1 second 
d9a069c1d0fc: Retrying in 1 second 
a5eb0fc1decb: Retrying in 1 second 
b2ac5371e0f2: Retrying in 1 second 
142a601d9793: Retrying in 1 second 

**Steps to reproduce the issue:**
1. Docker push

**Describe the results you received:**
Each section restarts after the 19 minute time out.

**Describe the results you expected:**
It would be good if it remembers where it was, within chunks, and, if, say, it had pushed 100MB, it started from there the next time, with the 101st MB.

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens every time. It takes days for just one push to complete.
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 75
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 69
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-43-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 17.87 GiB
Name: govern
ID: U36Y:L74X:VLZA:MJIS:7I5S:SFOD:BDRG:AFYB:6WNQ:AWRR:M3LL:B7UY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: fustbariclation
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

Running on Ubuntu under Virtualbox on OS/X - latest versions of all

Linux govern 4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:48:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment] 2016-10-21 06:19
Thanks for reporting! This is a duplicate of https://github.com/docker/docker/issues/4872, you can subscribe to that issue to stay informed on updates

**Closed by thaJeztah** 2016-10-21 06:19 UTC
Labels: area/distribution, kind/enhancement
