### ISSUE TITLE
Docker (+AWS) very slow compared to localhost

### ISSUE THREAD

**Issue by ghost** [docker/docker#27824] opened 2016-10-27 10:26 UTC
# **Hello everyone,**

I'm working on a NodeJS app that is connected to a external database (Couchdb).
Some features of this app allow users to automatically Push code on Github repository (or heroku).When I'm running my app in **localhost**, this PUSH action takes approximately **1 minute**, but when I run on local **docker**, it takes **~3 minutes**... (extremely slow, 3x)

I read others post saying that **docker network is slow**. That can be the issue, because this NodeJS app request external DB and external services. I also tried to deploy my docker on **AWS EC2 servers**, I chose a **micro.T2** instance, and this PUSH action takes more than **5 minutes**, that's extremely long.

I don't know If i missconfigured something, or just doing something wrong.  

**DOCKERFILE**
`FROM debian:jessie`

RUN apt-get update \
&& apt-get -y install sudo \
&& apt-get -y install apt-utils  \
&& apt-get -y install curl \
&& curl -sL https://deb.nodesource.com/setup_5.x | bash -

RUN apt-get -y install nodejs \
&& apt-get -y install wget \
&& sudo wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh \
&& apt-get -y install git \
&& mkdir -p /usr/src/app \

WORKDIR /usr/src/app
COPY . /usr/src/app
RUN cat /usr/src/app/.heroku_cred | heroku login
RUN npm install
ENV NODE_ENV=production
RUN nodejs /usr/src/app/server/config/environment.js initialize

CMD [ "nodejs", "/usr/src/app/bin/www" ]`  

**COMMANDS I DID:**
`docker build -t joliejuke:app .`
`docker run -d -p 80:80 --name app joliejuke:app`

**AWS EC2 CONFIG:**
instance: micro.t2
region: eu-west-1 (Irelan)
(I'm from France)

Thx

**Comment by unclejack** [comment] 2016-10-27 10:31
@joliejuke Can you provide the output of the `docker info` from both hosts, please?

**Comment by joliejuke** [comment] 2016-10-27 10:50
@unclejack Here's the docker info for both host:

**AWS HOST**
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.1 MiB
Name: takofront
ID: SFN2:WOGJ:6VQC:M26U:J26F:VFVD:JCFH:3K3E:75WP:2QMN:7RR2:XNEW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Insecure Registries:
 127.0.0.0/8

**LOCAL DOCKER**
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 48
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 58
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: JEE6:2HVM:YXTJ:QTXB:CXMC:EDJJ:2BRE:DSET:3QRF:UGWN:K56G:BC46
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2016-10-27T10:48:57.676892185Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

**Comment by unclejack** [comment] 2016-10-27 10:58
@joliejuke The micro instance is most likely quite slow. Without the actual application and a way to reproduce this, I don't see how we could investigate this further.

It's very difficult to assess what happens with that particular setup. I don't think the Docker networking has something to do with this performance problem you've noticed. This seems to be related to that particular application and to the performance of those hosts.

It's very difficult to investigate issues without any way to reproduce. Can you provide something we could use to check if there's a potential performance issue of some kind, please?

**Comment by joliejuke** [comment] 2016-10-27 12:12
I can make a list of features of this application, but the fact is, even in a local docker, the app run slower than in my machine (localhost).

Micro instance is a potential actor of this slowness, that's why I will try other instances.
I know this is quite hard to investigate other people app.

There's a list of features: 

- Database request (on other docker)

- Execute git push (push ~10 Mo of code to github)

- Execute git push (same, but to heroku)

- Restful API

I noticed that when I'm pushing something, server is going extremely slow (Ajax request = 5seconds instead of 1s).

**Comment by unclejack** [comment] 2016-10-27 12:32
We need more bits of information in order to reproduce this. Can you reduce this to a set of steps to reproduce this problem without your application/proprietary code?

**Comment by IhostVlad** [comment] 2017-03-31 10:32
Perhaps I faced a similar problem. Specifically the 'npm install' command works in a docker-container very much slowly, by about 80 times more slowly than at the local machine. It would be interesting to investigate the reasons of such behavior, but meanwhile it is known that changeover of 'npm install' by 'yarn install' solves it a problem though it is unclear why. There is an impression that 'npm install' is incompatible with docker though it is improbable, there is a set of the known decisions with deployment where there is no such problem.

**Comment by thaJeztah** [comment] 2017-03-31 11:14
@IhostVlad your issue looks to be different from the issue reported here; IIUC "npm install" outside of a container for you is faster than "npm install" _inside_ a container, correct? There's a lot of things that can play a role there (the graph driver that is used, are you using a volume/bind-mount for the paths that npm installs its packages in, are you running on Linux, or Docker for Mac or Windows).

If it's on Docker for Mac or Docker for Windows, and you're using a bind-mount (`-v /foobar:/path-in-container`), that may be due to https://github.com/docker/for-mac/issues/77, which is actively being worked on. If not, feel free to open a new issue, but be sure to provide the details that are requested in the issue template.

I'm going to close this issue, because the original reporter did not provide sufficient information to reproduce and triage the issue. If you arrive here and have a similar issue, please open a new ticket with details (as described above). I'll lock the issue to prevent it from collecting possibly unrelated issues, which makes triaging the issue at hand difficult.

**Closed by thaJeztah** 2017-03-31 11:14 UTC
Labels: kind/question, status/more-info-needed
