### ISSUE TITLE
Run docker-node-hello failed

### ISSUE THREAD

**Issue by tezhao** [docker/docker#22405] opened 2016-04-29 02:53 UTC
**Output of `docker version`:**
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
Images: 14
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 22
Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 14.04.4 LTS
CPUs: 1
Total Memory: 2.995 GiB
Name: terry-VirtualBox
ID: SFHK:VFDL:VVPW:5T53:YYYY:DL6Y:BOLV:HJ2U:EJC5:MAIF:JOK6:YSGD
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Steps to reproduce the issue:**
1.start docker server
2.Run hello-image
3. The issue occurs

**Describe the results you received:**
root@terry-VirtualBox:/home/terry/docker-node-hello# docker run -d -p 8080:8080 example/docker-node-hello:latest
b8a67d3434d807cc7a5b6edaf3d0b29b1b6ef4b8404170c55cfcc2d121bdda6c
FATA[0000] Error response from daemon: Cannot start container b8a67d3434d807cc7a5b6edaf3d0b29b1b6ef4b8404170c55cfcc2d121bdda6c: [8] System error: exec: "supervisord": executable file not found in $PATH 

**Describe the results you expected:**
Successfully Run

**Additional information you deem important (e.g. issue happens only occasionally):**
I changed "CMD ["supervisord",-"n"]" to "CMD ["/usr/bin/supervisord","-n"]" in my dockfile and build image again.
When I ran the image,I got the following error message.
Error: statusCode=404 Cannot start container c2416fcf39379712c87402dce0fdd5ae8173e78bdda59ef1557272cb3a2f11bc: [8] System error: exec: "/usr/bin/supervisord": stat /usr/bin/supervisord: no such file or directory 

In /usr/bin directory I could find  "supervisord" execute command.
$PATH environment variable that I have checked contained /usr/bin directory.

**Comment by thaJeztah** [comment] 2016-04-29 11:37
> In /usr/bin directory I could find "supervisord" execute command.

Is that inside or outside of the container? How did you check?

Also, you're running a very old version of Docker, that we no longer maintain (current version is 1.11.1), so even if there's a bug in that version, there won't be a bug fix, unless the issue is still present in the current release.

@tezhao I don't mean to be rude here, but I explained in one of your previous issues that the GitHub issue tracker is not a support forum. This doesn't look like a bug, but something in your image. Please use either one of:

- forums.docker.com
- the #docker IRC channel
- StackOverflow

I'll close this issue

**Closed by thaJeztah** 2016-04-29 11:37 UTC
