### ISSUE TITLE
why does "docker run" not provide parameters to configure the ip address 

### ISSUE THREAD

**Issue by epiphyllum** [docker/docker#12141] opened 2015-04-07 12:16 UTC
some times, it is really inconvenient. although pipework'like tools can add ip address for the container, 
there is no tools to del the ip of the container.

**Comment by thaJeztah** [comment] 2015-04-07 12:20
Hi @epiphyllum I'm closing this, because I think this is a duplicate of https://github.com/docker/docker/issues/6743.

**Closed by thaJeztah** 2015-04-07 12:20 UTC
