### ISSUE TITLE
awslog driver not taking docker image name, ecs service name and task definition

### ISSUE THREAD

**Issue by rajasekaran07** [docker/docker#29840] opened 2017-01-03 07:35 UTC
Hello,

I am using awslogs driver to collect my ECS container logs but it is not taking ECS Service name, Container instance name, task definition and Docker image name.

The below are my log sample. Here I cant find docker image name, ECS Service name and task definition.

```
{
  "_index": "cwl-2017.01.03",
  "_type": "mytestloges",
  "_id": "33081504929870395169036308436466460047129742806680469507",
  "_score": 1,
  "_source": {
    "Message": 1482993472485,
    "Request": "request",
    "Rsponse": "request received",
    "Method": "GET",
    "Info": "INFO",
    "Information": "services-shelters",
    "URL": "/favicon.ico",
    "Plugin": "0|app      |",
    "@id": "33081504929870395169036308436466460047129742806680469507",
    "@timestamp": "2017-01-03T06:46:25.785Z",
    "@message": "\"0|app      |\" 1482993472485 INFO \"services-shelters\"  request \"GET\" \"/favicon.ico\" \"request received\"",
    "@owner": "855158544446",
    "@log_group": "mytestloges",
    "@log_stream": "nodejs-app/blue-green-task/9f158062-346b-4a07-b2d3-e6bdd9321dee"
  },
  "fields": {
    "@timestamp": [
      1483425985785
    ]
  }
}
```

Someone kindly suggest how to proceed further.

Regards,
Raja

**Comment by thaJeztah** [comment] 2017-01-03 13:04
Docker 1.13 will add more options to the AWS logging driver, and allow you to set a custom "tag". See the pull request that implemented this; https://github.com/docker/docker/pull/27707, and the related documentation; https://github.com/docker/docker.github.io/pull/380.

Please note that the GitHub issue tracker is intended for reporting bugs and feature requests. For questions about _running_ docker, consider using;

- https://forums.docker.com
- the Docker Community Slack channel (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- StackOverflow

I'll close this issue, because this is not a bug, but feel free to continue the conversation after I closed

**Closed by thaJeztah** 2017-01-03 13:04 UTC
