### ISSUE TITLE
docker build won't exit after run command 'java'

### ISSUE THREAD

**Issue by brianbolt** [docker/docker#18786] opened 2015-12-19 02:13 UTC
docker version
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

docker info

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
bbolt:docker-compose bbolt$ docker info
Containers: 9
Images: 200
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 218
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 7.79 GiB
Name: default
ID: VVJ7:OAFT:AOIU:FR7F:4QPL:WDPC:ZCEY:TZSL:SEFX:YGDP:NZ4N:MBXO
Debug mode (server): true
 File Descriptors: 59
 Goroutines: 138
 System Time: 2015-12-19T02:15:28.207065115Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: bbolt
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

uname -a
```
Darwin bbolt 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

docker-machine version
```
docker-machine version 0.5.3, build 4d39a66
```

cat Dockerfile

    FROM centos:centos6
    RUN yum install -y java-1.7.0-openjdk
    RUN java

When I try and build the above container, docker runs the first 2 steps successfully but after printing the output of `java` in the 3rd step, it does not exit the build, it just freezes at that point and I need I need to hit cntrl+c to exit the build.

Docker build .
```
Sending build context to Docker daemon 3.954 MB
Step 1 : FROM centos:centos6
 ---> 1a895dd3954a
Step 2 : RUN yum install -y java-1.7.0-openjdk
 ---> Using cache
 ---> 38facaf3a9c2
Step 3 : RUN java
 ---> Running in 00fb59934acc
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32	  use a 32-bit data model if available
    -d64	  use a 64-bit data model if available
    -server	  to select the "server" VM
                  The default VM is server.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A : separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.
```

**Comment by thaJeztah** [comment] 2015-12-19 16:16
Could indeed be a duplicate of https://github.com/docker/docker/issues/18180 or https://github.com/docker/docker/issues/18500

Perhaps we should close this one, to keep the discussion on a single place?

**Comment by brianbolt** [comment] 2015-12-19 16:19
Yes, I am digging deeper now into open issues and seems the same.

**Comment by thaJeztah** [comment] 2015-12-19 16:20
Alright, I'll close this one, but feel free to comment after that, or if you think it shouldn't be closed :+1:

**Closed by thaJeztah** 2015-12-19 16:20 UTC
