### ISSUE TITLE
Container port not exposed on the host with 1.6 rc4

### ISSUE THREAD

**Issue by vishh** [docker/docker#12130] opened 2015-04-07 00:15 UTC
A docker config that works on 1.5 fails with the latest 1.6 rc. The container that exposed the problem is running etcd built from scratch. Its exposes ports '2380' and '4001' on the host
```shell
        "NetworkMode": "container:4cff5d962ae7fb553fd7af413e06150bb9d0d9e527ae7951977b7d591e0cc42f",
        "PidMode": "",
        "PortBindings": {
            "2380/tcp": [
                {   
                    "HostIp": "",
                    "HostPort": "2380"
                }
            ],
            "4001/tcp": [
                {   
                    "HostIp": "",
                    "HostPort": "4001"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
```

The port does not show up on the host network
```shell
netstat -ntlp
(No info could be read for "-p": geteuid()=1002 but you should be root.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      -               
tcp        0      0 10.240.241.220:7080     0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      -               
tcp        0      0 10.240.241.220:6443     0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 :::4194                 :::*                    LISTEN      -               
tcp6       0      0 :::10250                :::*                    LISTEN      -               
tcp6       0      0 :::10255                :::*                    LISTEN      -   
```

Once I switch to 1.5 the ports show up on the host.

Complete inspect output:
```shell
$ sudo docker inspect 0ade0593b217
[{
    "AppArmorProfile": "",
    "Args": [
        "--addr",
        "127.0.0.1:4001",
        "--bind-addr",
        "127.0.0.1:4001",
        "--data-dir",
        "/var/etcd/data"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": [
            "/usr/local/bin/etcd",
            "--addr",
            "127.0.0.1:4001",
            "--bind-addr",
            "127.0.0.1:4001",
            "--data-dir",
            "/var/etcd/data"
        ],
        "Env": [
            "KUBE_DNS_SERVICE_HOST=10.0.0.10",
            "MONITORING_HEAPSTER_SERVICE_HOST=10.0.111.163",
            "KUBERNETES_RO_SERVICE_HOST=10.0.0.1",
            "KUBERNETES_RO_PORT_80_TCP=tcp://10.0.0.1:80",
            "KUBERNETES_PORT_443_TCP_PROTO=tcp",
            "MONITORING_GRAFANA_PORT_80_TCP_PROTO=tcp",
            "KIBANA_LOGGING_PORT_5601_TCP=tcp://10.0.55.106:5601",
            "MONITORING_HEAPSTER_PORT=tcp://10.0.111.163:80",
            "KUBERNETES_RO_PORT=tcp://10.0.0.1:80",
            "MONITORING_INFLUXDB_UI_SERVICE_PORT=80",
            "MONITORING_INFLUXDB_PORT_80_TCP_PROTO=tcp",
            "KUBE_DNS_PORT_53_UDP=udp://10.0.0.10:53",
            "MONITORING_HEAPSTER_PORT_80_TCP_ADDR=10.0.111.163",
            "MONITORING_GRAFANA_PORT_80_TCP_ADDR=10.0.110.242",
            "ELASTICSEARCH_LOGGING_PORT_9200_TCP_PROTO=tcp",
            "MONITORING_HEAPSTER_PORT_80_TCP_PORT=80",
            "KIBANA_LOGGING_PORT_5601_TCP_ADDR=10.0.55.106",
            "KUBE_DNS_SERVICE_PORT=53",
            "ELASTICSEARCH_LOGGING_SERVICE_HOST=10.0.94.161",
            "ELASTICSEARCH_LOGGING_SERVICE_PORT=9200",
            "KIBANA_LOGGING_PORT_5601_TCP_PROTO=tcp",
            "KUBERNETES_SERVICE_PORT=443",
            "KUBERNETES_PORT_443_TCP_PORT=443",
            "KUBERNETES_RO_PORT_80_TCP_ADDR=10.0.0.1",
            "KUBE_DNS_PORT_53_UDP_PROTO=udp",
            "MONITORING_INFLUXDB_UI_PORT_80_TCP_PROTO=tcp",
            "MONITORING_INFLUXDB_SERVICE_PORT=80",
            "KIBANA_LOGGING_PORT_5601_TCP_PORT=5601",
            "KUBE_DNS_PORT_53_UDP_ADDR=10.0.0.10",
            "MONITORING_HEAPSTER_PORT_80_TCP_PROTO=tcp",
            "MONITORING_GRAFANA_SERVICE_HOST=10.0.110.242",
            "MONITORING_INFLUXDB_UI_PORT_80_TCP=tcp://10.0.144.179:80",
            "KIBANA_LOGGING_PORT=tcp://10.0.55.106:5601",
            "MONITORING_GRAFANA_PORT_80_TCP_PORT=80",
            "KIBANA_LOGGING_SERVICE_PORT=5601",
            "KUBERNETES_PORT_443_TCP=tcp://10.0.0.2:443",
            "KUBERNETES_PORT_443_TCP_ADDR=10.0.0.2",
            "MONITORING_GRAFANA_PORT=tcp://10.0.110.242:80",
            "MONITORING_INFLUXDB_PORT_80_TCP=tcp://10.0.235.26:80",
            "KUBE_DNS_PORT_53_UDP_PORT=53",
            "KUBERNETES_RO_SERVICE_PORT=80",
            "MONITORING_INFLUXDB_UI_SERVICE_HOST=10.0.144.179",
            "MONITORING_INFLUXDB_PORT_80_TCP_PORT=80",
            "ELASTICSEARCH_LOGGING_PORT_9200_TCP_ADDR=10.0.94.161",
            "MONITORING_GRAFANA_PORT_80_TCP=tcp://10.0.110.242:80",
            "MONITORING_INFLUXDB_SERVICE_HOST=10.0.235.26",
            "KUBE_DNS_PORT=udp://10.0.0.10:53",
            "MONITORING_GRAFANA_SERVICE_PORT=80",
            "KIBANA_LOGGING_SERVICE_HOST=10.0.55.106",
            "MONITORING_HEAPSTER_PORT_80_TCP=tcp://10.0.111.163:80",
            "ELASTICSEARCH_LOGGING_PORT_9200_TCP=tcp://10.0.94.161:9200",
            "KUBERNETES_PORT=tcp://10.0.0.2:443",
            "MONITORING_INFLUXDB_UI_PORT_80_TCP_PORT=80",
            "ELASTICSEARCH_LOGGING_PORT=tcp://10.0.94.161:9200",
            "KUBERNETES_RO_PORT_80_TCP_PROTO=tcp",
            "KUBERNETES_SERVICE_HOST=10.0.0.2",
            "MONITORING_INFLUXDB_PORT=tcp://10.0.235.26:80",
            "ELASTICSEARCH_LOGGING_PORT_9200_TCP_PORT=9200",
            "MONITORING_HEAPSTER_SERVICE_PORT=80",
            "KUBERNETES_RO_PORT_80_TCP_PORT=80",
            "MONITORING_INFLUXDB_UI_PORT=tcp://10.0.144.179:80",
            "MONITORING_INFLUXDB_UI_PORT_80_TCP_ADDR=10.0.144.179",
            "MONITORING_INFLUXDB_PORT_80_TCP_ADDR=10.0.235.26",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "ExposedPorts": {
            "2380/tcp": {},
            "4001/tcp": {}
        },
        "Hostname": "e2e-test-vishnuk-master",
        "Image": "gcr.io/google_containers/etcd:2.0.8",
        "Labels": {},
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": null,
        "WorkingDir": ""
    },
    "Created": "2015-04-06T23:46:46.61424277Z",
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "ExecIDs": [
        "ff915b3d25aaa0cf9175d4e5368a7dfce44a641512c3557d4e55c457d503d937",
        "1b2b714d58966cf723126c6ef8abc4864becd05f699e62cece4bc43018a58656",
        "e024386fea75476daa99b8f002592bee1063df35a0edcd2871309de310984618"
    ],
    "HostConfig": {
        "Binds": [
            "/mnt/master-pd/var/etcd:/var/etcd",
            "/var/lib/kubelet/pods/160ec72a0805d5306a34deee7743e5b9/containers/etcd-container/0ade0593b217bffefe38b753c49d1b07f6efdaefc4686bf72d299833864b27e9:/dev/termination-log"
        ],
        "CapAdd": null,
        "CapDrop": null,
        "CgroupParent": "",
        "ContainerIDFile": "",
        "CpuShares": 0,
        "CpusetCpus": "",
        "Devices": null,
        "Dns": [
            "10.0.0.10",
            "169.254.169.254",
            "10.240.0.1"
        ],
        "DnsSearch": [
            "default.kubernetes.local",
            "kubernetes.local",
            "c.vishnuk-cloud.internal.",
            "454568409378.google.internal.",
            "google.internal."
        ],
        "ExtraHosts": null,
        "IpcMode": "container:4cff5d962ae7fb553fd7af413e06150bb9d0d9e527ae7951977b7d591e0cc42f",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkMode": "container:4cff5d962ae7fb553fd7af413e06150bb9d0d9e527ae7951977b7d591e0cc42f",
        "PidMode": "",
        "PortBindings": {
            "2380/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "2380"
                }
            ],
            "4001/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "4001"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "SecurityOpt": null,
        "Ulimits": null,
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/4cff5d962ae7fb553fd7af413e06150bb9d0d9e527ae7951977b7d591e0cc42f/hostname",
    "HostsPath": "/var/lib/docker/containers/4cff5d962ae7fb553fd7af413e06150bb9d0d9e527ae7951977b7d591e0cc42f/hosts",
    "Id": "0ade0593b217bffefe38b753c49d1b07f6efdaefc4686bf72d299833864b27e9",
    "Image": "7459fa04a08ca061a1ff8992a60d9364de2556aa2dd61ef2ee8c03500bddae0f",
    "LogPath": "",
    "MountLabel": "",
    "Name": "/k8s_etcd-container.1ab37454_etcd-server-e2e-test-vishnuk-master_default_160ec72a0805d5306a34deee7743e5b9_9838c56b",
    "NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "PortMapping": null,
        "Ports": null
    },
    "Path": "/usr/local/bin/etcd",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/4cff5d962ae7fb553fd7af413e06150bb9d0d9e527ae7951977b7d591e0cc42f/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 19987,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2015-04-06T23:46:46.761009987Z"
    },
    "Volumes": {
        "/dev/termination-log": "/var/lib/kubelet/pods/160ec72a0805d5306a34deee7743e5b9/containers/etcd-container/0ade0593b217bffefe38b753c49d1b07f6efdaefc4686bf72d299833864b27e9",
        "/var/etcd": "/mnt/master-pd/var/etcd"
    },
    "VolumesRW": {
        "/dev/termination-log": true,
        "/var/etcd": true
    }
}
]
```

cc @tiborvass @jfrazelle

**Comment by jfrazelle** [comment] 2015-04-07 00:18
what's the output of iptables-save

**Comment by vishh** [comment] 2015-04-07 00:20
The application, etcd in this case, works just fine from inside the container - verified via exec.

**Comment by vishh** [comment] 2015-04-07 00:22
iptables are disabled. Daemon is run as follows:
`/usr/bin/docker -d -p /var/run/docker.pid --bridge cbr0 --iptables=false --ip-masq=false`

**Comment by jfrazelle** [comment] 2015-04-07 00:22
Then how does kubernetes expose ports.

**Comment by jfrazelle** [comment] 2015-04-07 00:26
there must be some change in the information we are giving back to kubes when it sets up networking or something... because idk what else could have broken it, if docker is not handling iptables

**Comment by vishh** [comment] 2015-04-07 00:27
Makes sense. It runs a separate daemon (kube-proxy) that handles iptables. I can dig into the proxier code to see if there are any issues there.

**Comment by vishh** [comment] 2015-04-07 00:29
cc @thockin

**Comment by crosbymichael** [comment] 2015-04-07 00:48
Lookin around these parts
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/dockertools/docker.go#L306

**Comment by crosbymichael** [comment] 2015-04-07 00:54
@vishh how do we test any fix for something like this?

**Comment by crosbymichael** [comment] 2015-04-07 01:10
@vishh is the state here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/dockertools/docker.go#L163 used for anything proxy related?

**Comment by thockin** [comment] 2015-04-07 01:39
I am out right now, but can look later.

The kube-proxy has nothing at all to do with host ports.

Afaik, host port defs ONLY work on the container that actually hosts the
net namespace.  We explicitly do (or did) a pass through all containers in
a pod to aggregate host ports onto the pod container.  Maybe that broke
with recent changes?

The spec you posted, @vishh, looks to be both joining a pod namespace (net
= container) and defining host ports.  That has never worked.  I filed it
as a bug but it got closed as "working as intended".  I still think that's
wrong, but we worked around it.

I suspect kube code.  Can you repro as a set of command lines?

@vishh <https://github.com/vishh> is the state here
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/dockertools/docker.go#L163
used for anything proxy related?

—
Reply to this email directly or view it on GitHub
<https://github.com/docker/docker/issues/12130#issuecomment-90302206>.

**Comment by brendandburns** [comment] 2015-04-07 02:37
This is completely unrelated to the proxy.  The container in question runs with --net=host set, so any ports that it exposes, should just get exposed in the host network namespace.  No proxying, forwarding or iptables needed.

**Comment by brendandburns** [comment] 2015-04-07 02:38
and to answer @jfrazelle earlier question (in case she's curious):

We don't do port forwarding, we make the IP address of the container on the bridge routable from outside of the host node, so hostPorts and port forwarding are unnecessary.

**Comment by jfrazelle** [comment] 2015-04-07 02:42
Oh didn't realize --net host thanks

**Comment by thockin** [comment] 2015-04-07 04:25
I agree it's unrelated to the proxy, but the config that @vishh posted said:

        "NetworkMode":
"container:4cff5d962ae7fb553fd7af413e06150bb9d0d9e527ae7951977b7d591e0cc42f",

**Comment by brendandburns** [comment] 2015-04-07 04:54
That's because even in host mode, we use the pod-infra pod, so it looks like:

in pseudo-json:

```json
pod-infra-container {
  id: <foo>
  network: "host"
}
```
```json
etcd-container {
  id: <bar>
  // id from the pod-infra container above
  network: "container:<foo>"
}
```

**Comment by thockin** [comment] 2015-04-07 05:16
Ahh, right.   Of course.

Vish - can you try to boil this down to CLIs?  I don't understand what a
host port means in this context?

**Comment by coolljt0725** [comment] 2015-04-07 13:26
@brendandburns  I found this problem too. There something wrong when a container `<bar>` joining the network namespace of a container `<foo>` where the network namespace of `<foo> `is set to `--net=host`. I think https://github.com/docker/libcontainer/pull/512 can fix this.

**Comment by vishh** [comment] 2015-04-07 16:32
Here is a repro using docker cli
```shell
$ docker run -d --net=host --name=net_cont gcr.io/google_containers/pause:0.8.0
6bc00fd47d688e2eb6f75469fb07f6293417bae460c80e1f8c90a51bd2505797
$ docker run -d --net=container:net_cont --name=user_cont -p 4001:4001 gcr.io/google_containers/pause:0.8.0
bf42653cf3a9e54abb89b3d94903be740868b14e314244772a8dcea923d4bcf9
```
The port is not exposed with 1.6
```shell
$ netstat -ntlp
(No info could be read for "-p": geteuid()=1002 but you should be root.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      -               
tcp        0      0 10.240.241.220:7080     0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      -               
tcp        0      0 10.240.241.220:6443     0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 :::4194                 :::*                    LISTEN      -               
tcp6       0      0 :::10250                :::*                    LISTEN      -               
tcp6       0      0 :::10255                :::*                    LISTEN      - 
```

With 1.5 the port gets exposed.

**Comment by dchen1107** [comment] 2015-04-07 16:34
Here is the output with docker 1.5:

# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2207/sshd       
tcp        0      0 127.0.0.1:7001          0.0.0.0:*               LISTEN      5754/etcd       
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      4900/nginx      
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      5672/kubelet    
tcp        0      0 10.240.52.31:7080       0.0.0.0:*               LISTEN      4057/kube-apiserver
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      4151/kube-scheduler
tcp        0      0 10.240.52.31:6443       0.0.0.0:*               LISTEN      4057/kube-apiserver
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      5754/etcd       
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      4104/kube-controlle
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      4057/kube-apiserver
tcp6       0      0 :::22                   :::*                    LISTEN      2207/sshd       
tcp6       0      0 :::4001                 :::*                    LISTEN      5754/etcd       
tcp6       0      0 :::4194                 :::*                    LISTEN      5672/kubelet    
tcp6       0      0 :::10250                :::*                    LISTEN      5672/kubelet

**Comment by vishh** [comment] 2015-04-07 17:15
I think the problem is [here](https://github.com/docker/docker/blob/master/daemon/execdriver/native/create.go#L139).

**Comment by thockin** [comment] 2015-04-07 19:09
I feel dumb - what does it even mean to have a host port in --net=host
mode?

**Closed** 2015-04-07 23:18 UTC
