### ISSUE TITLE
Add on remote deamon doesn't unpack

### ISSUE THREAD

**Issue by tylerhi** [docker/docker#18774] opened 2015-12-18 18:59 UTC
We are using docker to build base images but would like to do so with a remote daemon. The only problem is that while this Dockerfile works locally it doesn't work remotely.

FROM scratch
ADD rootfs.tar.xz /
RUN \
  mkdir -p /var/volatile/log ; \
  mkdir -p /var/volatile/tmp ; \
  chmod 1777 /var/volatile/tmp

Locally: docker build test
Sending build context to Docker daemon 71.47 MB
Sending build context to Docker daemon 
Step 0 : FROM scratch
 ---> 
Step 1 : ADD rootfs.tar.xz /
 ---> Using cache
 ---> 373a54a268de
Step 2 : RUN mkdir -p /var/volatile/log ;   mkdir -p /var/volatile/tmp ;   chmod 1777 /var/volatile/tmp
 ---> Running in 3730b5d1f53b
 ---> 286bb5b770ff
Removing intermediate container 3730b5d1f53b
Successfully built 286bb5b770ff

Remotely: docker -H 192.168.220.160:5001 build test
Sending build context to Docker daemon 71.47 MB
Sending build context to Docker daemon 
Step 1 : FROM scratch
 ---> 
Step 2 : ADD rootfs.tar.xz /
 ---> Using cache
 ---> ec03d12b53a1
Step 3 : RUN mkdir -p /var/volatile/log ;   mkdir -p /var/volatile/tmp ;   chmod 1777 /var/volatile/tmp
 ---> Running in 472ce50a27c6
exec: "/bin/sh": stat /bin/sh: no such file or directory
INFO[0007] [8] System error: exec: "/bin/sh": stat /bin/sh: no such file or directory

We can see the problem looking at the resultant images

docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED              VIRTUAL SIZE
<none>                               <none>              286bb5b770ff        About a minute ago   149.1 MB

docker -H 192.168.220.160:5001 images
REPOSITORY                     TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                         <none>              ec03d12b53a1        About a minutes ago       71.46 MB

The problem being that when this is executed remotely the ADD magic never fires and rootfs.tar.xz never gets unpacked resulting in a image that is the same size as the original tar file. This should work since once the context is copied the archive should be local to the remote daemon.

Bug Report Information
docker -H 192.168.220.160:5001 version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.9.0
Server API version: 1.21
Go version (server): go1.5.1
Git commit (server): 76d6bc9
OS/Arch (server): linux/amd64

docker -H 192.168.220.160:5001 info
Containers: 18
Images: 16
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 52
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.1.8-yocto-standard
Operating System: Vecima Reference Distribution 2.0 ()
CPUs: 2
Total Memory: 1.95 GiB
Name: demo-cluster-master.novalocal
ID: TPR5:USD5:HFCA:SS4U:4G2G:4TZ6:QJO3:376V:YKO3:C52S:L7NI:NAA2
Http Proxy: 
Https Proxy: 
No Proxy: 

docker info
Containers: 11
Images: 16
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 38
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 11.54 GiB
Name: pc2167
ID: SX54:HUA6:MDS7:5MKJ:VKDF:QWKL:BRCN:BILP:MXGJ:EKGM:S6UP:PBZL
WARNING: No swap limit support

local: Linux pc2167 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

remote: Linux demo-cluster-master.novalocal 4.1.8-yocto-standard #1 SMP PREEMPT Thu Dec 10 06:53:15 UTC 2015 x86_64 GNU/Linux

**Comment by tonistiigi** [comment] 2015-12-21 18:09
Looks like a cache issue. Can you test what happens on `docker -H 192.168.220.160:5001 build --no-cache test`. Also, please provide `docker history 286bb5b770ff`, `docker -H 192.168.220.160:5001 history ec03d12b53a1`, `docker version`.

**Comment by tylerhi** [comment] 2015-12-21 19:05
I get the same failure.

docker -H 192.168.220.160:5001 build --no-cache test
Sending build context to Docker daemon 71.47 MB
Sending build context to Docker daemon 
Step 1 : FROM scratch
 ---> 
Step 2 : ADD rootfs.tar.xz /
 ---> bdbf32452b2d
Removing intermediate container 7a8a90a783f3
Step 3 : RUN mkdir -p /var/volatile/log ;   mkdir -p /var/volatile/tmp ;   chmod 1777 /var/volatile/tmp
 ---> Running in 54d0c83dba79
exec: "/bin/sh": stat /bin/sh: no such file or directory
INFO[0009] [8] System error: exec: "/bin/sh": stat /bin/sh: no such file or directory      

docker -H 192.168.220.160:5001 images
REPOSITORY                     TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                         <none>              bdbf32452b2d        5 minutes ago       71.46 MB


docker history 286bb5b770ff
IMAGE               CREATED             CREATED BY                                      SIZE
286bb5b770ff        3 days ago          /bin/sh -c mkdir -p /var/volatile/log ;   mkd   0 B
373a54a268de        3 days ago          /bin/sh -c #(nop) ADD file:a8ea32947e6af5e258   149.1 MB
docker -H 192.168.220.160:5001 history ec03d12b53a1
IMAGE               CREATED             CREATED BY                                      SIZE
ec03d12b53a1        3 days ago          /bin/sh -c #(nop) ADD file:216d483f3dc55d63bd   71.46 MB
docker -H 192.168.220.160:5001 history bdbf32452b2d
IMAGE               CREATED             CREATED BY                                      SIZE
bdbf32452b2d        6 minutes ago       /bin/sh -c #(nop) ADD file:216d483f3dc55d63bd   71.46 MB

docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

**Comment by greyltc** [comment] 2016-01-22 15:17
I had a similar issue (something has surely changed with the remote build process recently to cause this breakage). I managed to fix it by changing the file structure of my root file system archive.

Can those of you having the issue paste here the first few lines returned by `tar -tvf rootfs.tar.xz`?

**Comment by tonistiigi** [comment] 2016-01-22 17:27
@greyltc Let us know if there is a way to reproduce. The other reports here are using version `1.6.2` so it may be somthing different if you think something has broke recently.

**Comment by tylerhi** [comment] 2016-01-22 18:43
I just retested this after upgrading docker:
build>>docker -H 192.168.220.170:5001 version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   76d6bc9
 Built:        Tue Jan 19 21:50:10 UTC 2016
 OS/Arch:      linux/amd64
and i'm getting the same issue.

As for my tar output:

tar -tvf rootfs.tar.xz | head -n4
drwxr-xr-x root/root         0 2016-01-22 12:00 ./
drwxr-xr-x root/root         0 2016-01-22 12:00 ./etc/
-rw------- root/root       840 2016-01-22 12:00 ./etc/passwd-
drwxr-xr-x root/root         0 2016-01-22 12:00 ./etc/profile.d/

**Comment by greyltc** [comment] 2016-01-22 19:40
Ah ha! That's what my (previously working, but now) non-working rootfs archive looked like too. Notice how all the contents begin with `./`

I recreated my rootfs archive in the following way to solve the issue:
```
cd $ROOTFS
tar --numeric-owner --xattrs --acls -Jcf /tmp/rootfs.tar.xz *
```
now my contents look like:
```
$ tar -tvf rootfs.tar.xz | head -n4
lrwxrwxrwx 0/0               0 2015-09-30 20:17 bin -> usr/bin
drwxr-xr-x 0/0               0 2015-09-30 20:17 boot/
drwxr-xr-x 0/0               0 2016-01-22 18:32 dev/
crw-rw-rw- 0/0             1,3 2016-01-22 18:32 dev/null
```
and the container seems to operate okay. Although I am seeing some strange behavior that may or may not be related.

**Comment by thaJeztah** [comment] 2016-02-16 12:25
@tylerhi have you been able to resolve this with the hints above?

**Comment by ehazlett** [comment] 2016-09-19 14:45
@tylerhi I'm going to close this as it appears to be resolved.  If you still notice the strange behavior please comment or open a new issue.  Thanks!

**Closed by ehazlett** 2016-09-19 14:45 UTC
