### ISSUE TITLE
manifest for any images not found when docker pull

### ISSUE THREAD

**Issue by Schmetterling** [docker/docker#31430] opened 2017-02-28 20:31 UTC
Manifest for docker image not found when I trying to pull the docker image.

**Comment by cpuguy83** [comment] 2017-02-28 20:36
This is related to the s3 outage.

Closing.
Thanks!

**Closed by cpuguy83** 2017-02-28 20:36 UTC
Labels: area/distribution

**Comment by l15k4** [comment] 2017-04-14 20:08
I'm getting this too, a few times already. It took a long time recently

**Comment by l15k4** [comment] 2017-04-14 21:41
Guys this is rather a serious issue, I can see other services like Github or Travis CI unavailable because of this, would you pls consider making this more fault tolerant?

**Comment by thaJeztah** [comment] 2017-04-14 22:40
@l15k4 you commented on a closed issue, which may easily get overlooked; are you still having this issue? Could you open a new issue with details (exact issue you're seeing, is this on all images or just a single one? What region/country are you in? If you are able to consistently reproduce, may be worth contacting support@docker.com

**Comment by l15k4** [comment] 2017-04-16 15:59
It was my fault, I was trying to pull non-existent version/tag of a docker image and the error was : 
```
manifest for gwiq/saturator:0.0.2 not found
```
And pretty much all google results were about s3 outage or a docker hub problem.

Sorry for a false alarm.

**Comment by thaJeztah** [comment] 2017-04-16 17:21
no problem!

Let me lock this issue, to prevent people from commenting here, and a possible outage getting unnoticed. If you suspect there's a service interruption (which may be local to your area, therefore not picked up by automatic monitoring), please open a new issue. Do check https://status.docker.com first to see if it's not being worked on already :smile:
