### ISSUE TITLE
Error message says "You may want to check your internet connection or if you are behind a proxy." but docker just requires restart

### ISSUE THREAD

**Issue by samaimia** [docker/docker#20910] opened 2016-03-03 12:03 UTC
See

http://stackoverflow.com/questions/31990757/network-timed-out-while-trying-to-connect-to-https-index-docker-io

Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 33
 Running: 0
 Paused: 0
 Stopped: 33
Images: 225
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 304
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: N3J5:ZKS6:LH7J:3GXR:6ZXR:LSDK:WDZN:63AK:FLGU:JPVJ:4YFS:TSAW
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 21
 System Time: 2016-03-03T11:52:43.577824311Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:

See http://stackoverflow.com/questions/31990757/network-timed-out-while-trying-to-connect-to-https-index-docker-io

1. use docker on mac for a while
2. try to pull a new image (for me this was `docker pull sameersbn/mysql:latest`)
3. Get error message:

```
Pulling repository docker.io/sameersbn/mysql
Network timed out while trying to connect to https://index.docker.io/v1/repositories/sameersbn/mysql/images. You may want to check your internet connection or if you are behind a proxy.
```

4. Running `docker-machine restart default && eval $(docker-machine env default)` fixes docker.

Describe the results you received:

Error message about network

Describe the results you expected:

Error message asking to restart docker (or just fix docker so that it doesn't go into weird state)

Provide additional info you think is important:

**Comment by thaJeztah** [comment] 2016-03-03 13:18
Yes, this is a known issue with VirtualBox; after a while (and when switching networks, e.g. when you're connected to a different WiFi network), networking inside VirtualBox stops working correctly. The latest version of Docker Machine *should* have some improvements, but restarting the virtual machine sometimes is the only option.

See the discussion on https://github.com/docker/machine/issues/1857.

I'm going to close this issue here, because this is an issue with VirtualBox or Docker Machine / Toolbox, so unfortunately we cannot fix that in this repository. Feel free to comment here after I've closed

**Closed by thaJeztah** 2016-03-03 13:18 UTC

**Comment by ptica** [comment] 2016-03-16 05:57
hi, I understand the problem is with virtualbox, but please, the error message could suggest the machine restart if that is the recommended workaround right now, that would be possible?

**Comment by thaJeztah** [comment] 2016-03-16 06:13
@ptica that's only the solution for VirtualBox, but not for, e.g., a remote daemon running somewhere in the cloud. We try to avoid messages that only apply to a specific setup

**Comment by ptica** [comment] 2016-03-16 06:56
I thought that the original problem stems from changing the wifi networks (that happens on laptops usually :)

**Comment by vimniky** [comment] 2016-05-02 04:19
I have the same problem too when I try to pull ubuntu . But after I run `docker-machine restart default && eval $(docker-machine env default)`  ,  problem solved !!

**Comment by hollykunge** [comment] 2016-10-14 11:37
这问题应该怎么解决啊  还有eval $(docker-machine env default) 这个命令到底是什么鬼
