### ISSUE TITLE
docker pull does not bring in parent images tags

### ISSUE THREAD

**Issue by koyadume** [docker/docker#17676] opened 2015-11-04 04:56 UTC
I have an image B which uses image A as base image. However when I pull image B and then execute ```docker images``` command, it shows only B. Is it possible to pull all parent images of an image along with their tags so that ```docker images``` lists all the parent images too after pulling an image?

**Comment by koyadume** [comment] 2015-11-04 05:37
docker version
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
```

docker info
```
Containers: 4
Images: 52
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 993.7 MiB
Name: laptop-docker
ID: EBZX:RBBU:DFQG:26ON:Z4LB:I6EO:QXOZ:HRMR:IKBM:E2VI:OCSO:AOOB
Debug mode (server): true
 File Descriptors: 14
 Goroutines: 21
 System Time: 2015-11-03T22:17:32.792152246+05:30
 EventsListeners: 0
 Init SHA1: 787da34bb103f11fd6114d8782217bc4f7032e3e
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
Username: koyadume
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

uname -a
```
Linux laptop-docker 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by askb** [comment] 2015-11-04 14:33
Hi @koyadume Any image is already pulled previously, the parent image does not get pulled unless something has changed in the images and if its not available in your environment. 

Did you try looking up the image tree with `dockviz` or `docker images -a` to check if the parent image is already available ? Sorry, if I did not understand your issue properly, its best if you could provide more information with an example.  Thanks.

**Comment by thaJeztah** [comment] 2015-11-26 15:47
What actually happens, is that `Image B` will pull all the *layers* of `Image A`,
but does not download the "image" (which is basically a collection of layers).

If you've pulled `Image B` and after that pull `Image A`, you'll see that
docker doesn't need to *download* `Image B` (all layers are already there),
and the image will show up in `docker images`.

For example; pulling the "Worpress" image (which is based on `php:5.6-apache`);
```
docker pull wordpress
Using default tag: latest
latest: Pulling from library/wordpress
e85fa464954c: Pull complete
d4e26c83a4b5: Pull complete
bdbe0528b73b: Pull complete
ba8c77627e1a: Pull complete
55b9e838871e: Pull complete
1422bae79500: Pull complete
82d542bcd59f: Pull complete
9b57b1ae96e8: Pull complete
06158cd7dcd2: Pull complete
2eae55199fa8: Pull complete
fe829f6254e4: Pull complete
7eeec02aeb80: Pull complete
7dacbeb5cf16: Pull complete
527486d71979: Pull complete
5e243d878f8b: Pull complete
80d8d62b8b17: Pull complete
57d4305f39b7: Pull complete
fbb2b255681e: Pull complete
6427b5680c85: Pull complete
93161efe1466: Pull complete
a21892440e4e: Pull complete
ffc13ca8fd99: Pull complete
3db79e933af1: Pull complete
8d755f5b434d: Pull complete
8d35c4915fba: Pull complete
2b3b657ae7ee: Pull complete
a40836adf5d3: Pull complete
d7afaa080f7e: Pull complete
26c95620fb50: Pull complete
9f8866b49bfb: Pull complete
Digest: sha256:0ec87d4d44da406cb3d96a741a00c100926de46b97212f2f99baddbc07fa69d8
Status: Downloaded newer image for wordpress:latest
```

After that, pulling the "php:5.6-apache" image, will not *download* the image,
because all layers are already present;

```
docker pull php:5.6-apache
5.6-apache: Pulling from library/php
Digest: sha256:6a7f8ba6dc6a7136d79375d3fa0110ce3ee8edf53ea05577a8def5a9cbeff3c1
Status: Downloaded newer image for php:5.6-apache
```

After that, the "php:5.6-apache" will become visible in `docker images`
I hope this helps explaining what happens

I'm going to close this issue, because it's not a bug, but feel free to comment here after I've closed the issue :+1:

**Closed by thaJeztah** 2015-11-26 15:47 UTC

**Comment by koyadume** [comment] 2015-12-04 14:27
Thank you @thaJeztah for detailed explanation.
