### ISSUE TITLE
Questions about udev_sync_supported

### ISSUE THREAD

**Issue by ZYNCMA** [docker/docker#22781] opened 2016-05-17 08:24 UTC
I had read quite a lot discussions about the race between devicemapper and udev, but still couldn't understand it well.
I have a few questions and hope I can get some answers here.
1. There once was a [PR](https://github.com/docker/docker/pull/4067) make devicemapper race-free. Is docker 1.11 race-free?
2. How can I produce the race issue? Can any body detail more about the race between devicemapper and udev?
3. How can I verify whether `Udev Sync Supported: false` has an effect on my docker environment (using devicemapper as storage backend) or not? I had tested the run, kill, restart and rm methods of container hundreds of times (using scripts in this [discussion](https://github.com/docker/docker/issues/4036)) and got no error, is it convincing enough to say that `Udev Sync Supported: false` doesn't matter to me?

Any comment is appreciated. Thanks a lot!

**Comment by thaJeztah** [comment] 2016-05-17 08:58
> 1. There once was a PR make devicemapper race-free. Is docker 1.11 race-free?

Since you followed the discussion on https://github.com/docker/docker/issues/4036, those fixes were added before Docker 1.0, but there's still lots of reports of people running into it with later versions

> 2. How can I produce the race issue? Can any body detail more about the race between devicemapper and udev?

I don't have the details, but know it can be hard to reproduce, and that's the reason its highly discouraged to run without udev-sync support. Your installation can run for weeks (or months), seemingly without issues, and then you find out that you ran into the issue, and lost data (ending up in a broken setup). https://github.com/docker/docker/issues/4036#issuecomment-111174341

> 3. How can I verify whether Udev Sync Supported: false has an effect on my docker environment (using devicemapper as storage backend) or not?

See the answer below "2."


Is there a reason you don't have udev sync support? Have you installed a statically linked binary, or are you running on an outdated system? What distro and kernel are you running on?

**Comment by ZYNCMA** [comment] 2016-05-17 09:56
@thaJeztah Thanks for your reply!
For some reasons I have to run docker on a customized system based on centos 6.2 and the kernel is 3.10.90. Since my system doesn't satisfy the dependence docker engine requires, I have to use a statically compiled docker binary, and thus don't have udev sync support.
Any suggestion?

**Comment by thaJeztah** [comment] 2016-05-17 10:24
Tricky; we no longer support CentOS 6.x, and running it on a custom kernel is untested. If possible, I'd really consider upgrading that system to CentOS 7. Having said that, if you're on a RHEL kernel, it may be possible to use the overlay graph driver (I think they back ported changes to their kernels to support this), but YMMV, you're really in uncharted territory.

I'll close this issue, because this is a question, not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-05-17 10:24 UTC
Labels: area/storage/devicemapper, kind/question

**Comment by ZYNCMA** [comment] 2016-05-17 11:57
Yeah, it's really tricky. 
Unfortunately, I have to support centos 6.2 and centos 7.0 at the same time, and overlayfs doesn't meet our requirement since we need disk quota and formatting is forbidden.
By the way, may I ask why udev sync is only supported when the docker engine binary is dynamic linked?
Anyway, thanks for your help! Your explanation really helps a lot.

**Comment by thaJeztah** [comment] 2016-05-17 12:21
> By the way, may I ask why udev sync is only supported when the docker engine binary is dynamic linked?

I don't recall, it may be that it could not be statically compiled. The same question came up recently, but I don't recall what the answer was; @justincormack @mlaventure I think you looked into that?
