### ISSUE TITLE
Docker containers leaving /run/network/ifstate files behind on Ubuntu 14.04

### ISSUE THREAD

**Issue by CVTJNII** [docker/docker#22513] opened 2016-05-04 21:15 UTC
On Ubuntu 14.04.4 LTS with the Wily 4.2 kernel I'm seeing thousands of orphaned /var/run/ifstate.veth files from removed containers.  On the boxes where I'm seeing this containers are frequently run as short lived processes, so containers are constantly being created and removed.

Note the large discrepancy in ifstate files on a box which has an especially heavy container load:

```
$ ls /run/network/ | grep ifstate.veth | wc -l
315080
$ ifconfig | grep '^[^[:space:]]' | wc -l
5
```

The files appear to be orphaned after a container exits:

```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$ ls /run/network/ | grep ifstate.veth | wc -l
0
$ docker run --rm -ti debian:jessie echo "Hello, world"
Hello, world
$ ls /run/network/ | grep ifstate.veth | wc -l
2
$ docker run --rm -ti debian:jessie echo "Hello, world"
Hello, world
$ ls /run/network/ | grep ifstate.veth | wc -l
4
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

This is a problem as it causes /run to eventually run out of inodes leading to errors like the following:

> docker: Error response from daemon: Cannot start container a6e4f0baedb3b7620d74edd2047621538c7c44fcf1511228f18ff33d7260f726: [9] System error: mkdir /var/run/docker/execdriver/native/a6e4f0baedb3b7620d74edd2047621538c7c44fcf1511228f18ff33d7260f726: no space left on device.

System info:

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
$ dpkg --list | grep wily
ii  linux-headers-generic-lts-wily      4.2.0.35.28                      amd64        Generic Linux kernel headers
ii  linux-headers-virtual-lts-wily      4.2.0.35.28                      amd64        Transitional package.
ii  linux-image-extra-virtual-lts-wily  4.2.0.35.28                      amd64        Transitional package.
ii  linux-image-generic-lts-wily        4.2.0.35.28                      amd64        Generic Linux kernel image
ii  linux-image-virtual-lts-wily        4.2.0.35.28                      amd64        This package will always depend on the latest minimal generic kernel image.
ii  linux-virtual-lts-wily              4.2.0.35.28                      amd64        Minimal Generic Linux kernel and headers

$ sudo docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

$ sudo docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 15
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 47
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.86 GiB
Name: sensu1
ID: CGJ5:2CQO:EKHW:SXJE:SVQ7:R3CI:Y54D:PWVY:RMT3:KPK6:ZMB6:YIAO
WARNING: No swap limit support

**Comment by thaJeztah** [comment] 2016-05-04 22:35
Sounds like a duplicate of https://github.com/docker/docker/issues/22513, can you check if that's the same?

**Comment by CVTJNII** [comment] 2016-05-04 23:12
@thaJeztah This issue is #22513.

**Comment by thaJeztah** [comment] 2016-05-04 23:15
Oh! Fat finger and clipboard, I meant https://github.com/docker/docker/issues/22397

**Comment by CVTJNII** [comment] 2016-05-05 02:18
Haha, no worries, I assumed that was the case.

So while similar, I don't believe this is the same bug.  #22397 is about the interfaces themselves being intermittently behind, whereas this bug is about empty ifstate files consistently being left behind.  I believe I hit #22397 with Docker 1.8.2 and the failure mode and symptoms are different.

**Comment by thaJeztah** [comment] 2016-05-05 12:21
Thanks for checking!

ping @mavenugo is this a known issue?

**Comment by haches** [comment] 2016-05-21 08:50
I'm experiencing the same bug on version 1.11.0

Docker usage: constantly starting & removing short-lived containers.

Issue: After some time, I can't create new containers because all iNodes are used up.

Checking iNodes: **df -i**
~~~
udev            253883    422  253461    1% /dev
tmpfs           256065 256065       0  100% /run
/dev/sda       2944000 292182 2651818   10% /
none            256065     14  256051    1% /sys/fs/cgroup
none            256065      1  256064    1% /run/lock
none            256065      1  256064    1% /run/shm
none            256065      2  256063    1% /run/user
~~~

Docker info: **docker info**
~~~
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 50
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: ubuntu
ID: GXAS:AEID:DVDR:MWW3:6MFZ:XIDT:LBS4:YXOY:PXD4:EXBA:D7YT:UZOF
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
~~~

Kernel: **uname -a**
~~~
Linux ubuntu 4.4.0-21-generic #37~14.04.1-Ubuntu SMP Wed Apr 20 16:33:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
~~~

**Comment by thaJeztah** [comment] 2016-05-21 09:48
ping @mavenugo do you know if this is being looked into?

**Comment by CVTJNII** [comment] 2016-05-24 16:35
I'm seeing this on1.8.2 after a downgrade, and I previously did not see it with this Docker version.  I'm wondering if this is an Ubuntu bug which is now being triggered by Docker.

**Comment by thaJeztah** [comment] 2016-05-24 17:04
Thanks @CVTJNII, interesting

**Comment by aboch** [comment] 2016-05-25 06:19
I do not think it is docker related as I can reproduce manually on a ubuntu VM:

```
$ uname -r
3.19.0-60-generic
$
$ ls /run/network | wc -l
13
$ for i in {1..10};do sudo ip link add v1${i} type veth peer name v2${i};done
$ ls /run/network | wc -l
33
$ for i in {1..10};do sudo ip link del v1${i};done
$ ls /run/network | wc -l
33
$ ip link | grep v1
$ ip link | grep v2
```

**Comment by tiborvass** [comment] 2016-08-23 23:53
I have the same issue, with kernel 3.13 also on Ubuntu 14.04

**Comment by tiborvass** [comment] 2016-08-23 23:54
This is not docker related indeed.

**Closed by tiborvass** 2016-08-23 23:54 UTC
Labels: group/networking, kind/bug, version/1.10, version/1.11

**Comment by hryamzik** [comment] 2016-08-24 09:13
The bad thing is that this issue seem to be the only relevant result in google. Any ideas about a workaround?

**Comment by tiborvass** [comment] 2016-08-26 21:47
@mavenugo @aboch do you think we could add `rm -f /run/network/$veth` after calling `ip link del` ?

**Comment by thaJeztah** [comment] 2016-09-14 14:11
ping @mavenugo @aboch PTAL ^^

**Comment by aboch** [comment] 2016-09-14 17:07
It looks this issue no longer happens with recent kernel:

```
$ docker version | grep Version
 Version:      1.11.2
 Version:      1.11.2
$ uname -r
4.4.0-36-generic
$ ls /run/network | wc -l
2
$ for i in {1..10};do sudo ip link add v1${i} type veth peer name v2${i};done
$ ls /run/network | wc -l
2
$ for i in {1..10};do sudo ip link del v1${i};done
$ ls /run/network | wc -l
2  <-- same number of files, no stale ones
$ ip link | grep v1
$ ip link | grep v2
$ 
```

@tiborvass I'd prefer to avoid adding work-around in the code for os-specific issues. Not even sure if those files are there in all the distributions and versions. Given it is a os specific issue, I think it is better for user to clean up the stale files via script.

**Comment by thaJeztah** [comment] 2016-09-14 19:28
Perhaps this is something for a "known issues" section (was just discussing this earlier with @anusha-ragunathan)

**Comment by anusha-ragunathan** [comment] 2016-09-14 23:30
Yes, creating a "Known issues" section in the release file would help broadcast such issues and workarounds to our user case. Issues that are corner cases and outside the scope of docker should definitely be in this section. The alternate of bumping the minimum required kernel version for *all* Docker users for such corner cases would not be ideal.

**Comment by mjsalinger** [comment] 2016-09-19 10:58
Just to add some info to this for your known issues' list: I ran into the exact same issue (running out of inodes, empty, orphaned `/var/run/ifstate.veth*` files) when conducting a load test on Ubuntu 14.04 with the latest backported kernel (`4.4.0-36-generic`).  The load test scenario was starting and immediately removing 250k containers (using the `ubuntu:latest` image) with a concurrency of 25...  

Below is the `docker info` for the test instance.  

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 1
Server Version: 1.12.1
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.675 GiB
Name: <cleared>
ID: F5HN:AF4E:JJ3O:PROG:TPPF:LLF3:BCGC:QSHT:72AI:KCQF:46S7:J4FF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

I also ran the same load test on Ubuntu 16.04 with the same kernel and same Docker setup, and did not encounter the issue.  ifstate files were properly cleared, and inodes were plentiful.  

Docker info for the second instance:

```
Containers: 25
 Running: 0
 Paused: 0
 Stopped: 25
Images: 1
Server Version: 1.12.1
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.675 GiB
Name: <cleared>
ID: PFIM:E6O6:2MUS:UNVL:QWJ4:4DOU:SU35:QHXK:2CCU:4LNJ:BUPD:CBN5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by bprodoehl** [comment] 2016-10-24 16:42
I'm seeing the same leak as @mjsalinger with latest 4.4.0 kernel on 14.04.5 and Docker 1.12.1, but using AUFS rather than overlay.  Guess I'm stuck with a job to periodically clear out those files until I can make the jump to 16.04 in production.

**Comment by nikonyrh** [comment] 2017-01-10 17:07
As people might end up here from Google, here is how I deleted unnecessary ifstate.xxx files (run as root):

    find /run/network -name 'ifstate.*' | egrep -w -v -e `ifconfig | grep veth | cut -d' ' -f1 | xargs echo | tr ' ' '|'` | xargs -n1 rm

No guarantees that this won't cause any instability, at least it tries to preserve those which are printed by `ifconfig` on my system. I didn't try what would happen if I deleted them all while containers are running.

This happened on Ubuntu 14 kernel 3.13.0-48, but I haven't seen it happen on Ubuntu 12 kernel 3.11.0-26.

**Comment by bmcbm** [comment] 2017-05-23 09:03
@nikonyrh Thanks for the find command, however I think it is a little too thorough, since is also deletes  non-veth ifstate files like 

```
 /run/network/ifstate.docker0
 /run/network/ifstate.lo 
 /run/network/ifstate.eth0
```
To only delete `/run/network/ifstate.veth*`files use this command: 

```
find /run/network -name 'ifstate.veth*' | egrep -w -v -e $(ifconfig | grep veth | cut -d' ' -f1 | xargs echo | tr ' ' '|') | xargs -n1 rm
```

**Comment by RanHamada** [comment] 2017-06-21 08:52
@bmcbm I think it could not works well when there is no container running.

Try this:
```
find /run/network -name 'ifstate.*' | egrep -w -v -e `ifconfig | cut -d' ' -f1 | xargs echo | tr ' ' '|'` | xargs -n1 rm
```

**Comment by ChristianUlbrich** [comment] 2018-09-02 21:36
@RanHamada Thx for your script. Worked, but it took at least several minutes... :)
