### ISSUE TITLE
Docker Client Hang on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by MicahZoltu** [docker/docker#26889] opened 2016-09-25 03:49 UTC
**Description**
After downloading the docker client in WSL I am able to run most commands (`run`, `ps`, `images`, `rm`, etc.).  However, when I try to do a `docker build` it hangs while copying the context.

**Steps to reproduce the issue:**

1. Install Windows 10.
1. Install Docker for Windows.
1. Install Windows Subsystem for Linux.
1. Open a bash prompt.
1. `cd ~`
1. `wget https://get.docker.com/builds/Linux/x86_64/docker-1.12.1.tgz`
1. `tar -xzvf docker-1.12.1.tgz`
1. `export DOCKER_HOST=tcp://0.0.0.0:2375`
1. `~/docker/docker build .`
1. Wait indefinitely.

**Describe the results you received:**
```
$ ~/docker/docker build .
Sending build context to Docker daemon 12.81 MB
```
It sits here indefinitely.  I once let it sit for a while (not sure how long, maybe 30-60 minutes) and it never moved on.  The number of MB it gets to before failing varies slightly each time, though it is usually within a few MB of 12MB.  When running docker client in windows, it indicates a 53MB context.

**Describe the results you expected:**
I expected it to build my image.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 63
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.92 GiB
Name: moby
ID: ECNU:IX4N:E5BL:N5L3:J26P:U46U:WC2M:XVGM:H5PI:BJNL:L63P:LJ36
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 35
 System Time: 2016-09-25T03:47:53.810819Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Comment by thaJeztah** [comment] 2016-09-25 16:26
Yes, this hasn't been tested, so it doesn't surprise me it doesn't work fully. @justincormack @rneugeba any ideas here?

**Comment by rneugeba** [comment] 2016-09-25 17:54
@MicahZoltu I'm afraid that running `docker` from within WSL against Docker for Windows is not supported and is unlikely going to be supported for a number of reasons.

The environment WSL processes execute in is quite different to standard Windows processes, in particular when it comes to the filesystem. For example, symlinks "work" for WSL processes but only is special parts of the filesystem and they are not visible to Windows processes; or userid mapping is done more or less completely separately.  Also, the filesystem layout for WSL processes is different to the host file system.

Docker for Windows is primarily implemented as a native Windows application, and Microsoft does not really support WSL processes interacting with native Windows processes.

While some commands may work (as you reported), some functionality, like for example volume sharing, won't work properly because of the above.

**Comment by MicahZoltu** [comment] 2016-09-25 18:47
@rneugeba Does this mean that using a Linux or OSX docker client to communicate with a Docker for Windows host is also not supported?  I would assume that the interaction would be the same.

What about the inverse?  Is Docker for Windows client communicating with Linux/OSX docker host also not supported?

What about Docker client in WSL communicating with a Linux/OSX docker host?

What surprises me a little is that Docker for Windows still uses a MobiLinux VM under the hood for the docker host as I understood it.  I would have assumed that things would work *better* communicating from WSL to the underlying MobiLinux host, though I imagine I am missing some critical pieces of how Docker for Windows daemon actually works.

**Comment by rneugeba** [comment] 2016-09-25 21:09
@MicahZoltu sorry, I slightly mis-understood. The windows and mac (and linux) docker clients can all talk to linux docker daemons, provided that the daemon is listening on a network socket. There shouldn't be an issue with that and that's how `docker-machine` used to work. Note, that if you connect this way, some things, like the volume mounting (`-v`) may not work.

With Docker for Windows (and Mac) we try to integrate the `docker` CLI as good as we can, so that the user has the experience of everything running locally.  That means, amongst others, that on OSX we listen on a Unix domain socket (and not the network) for clients to connect to. Likewise, on Windows the "native" method for the client to connect to the daemon is via a Named Pipe (under the hood, we then proxy this into the VM, where the daemon is running). On Windows, we currently still support connecting via the network (`tcp://0.0.0.0:2375`), because some clients, like `docker-compose`, do not yet support connecting via the Named Pipe. But, we may disable network access in the future, just like on Docker for Mac.

BTW, I couldn't reproduce the issue you are seeing with the running the Linux docker client in WSL and connect via `tcp://0.0.0.0:2375`. I'm on Windows Insider build 14926. I don't know which which Windows 10 build you are on, but have noticed several updates to WSL since the official release. Another possibility is that your firewall prevents access.

We are indeed still using MobyLinux in a VM on Docker for Windows, but WSL actually makes it harder to integrate because the VM is a Hyper-V VM and certain communication paths to Hyper-V VMs (like Hyper-V sockets) are not available in WSL.

**Comment by MicahZoltu** [comment] 2016-09-25 21:15
I'm running on an up-to-date retail version of Windows 10 Enterprise N, 64-bit.  If you are unable to reproduce my issue, then perhaps something about my machine is broken or it will be fixed in an upcoming retail release, both of which are more promising then "doesn't work for anyone".  :)  For additional troubleshooting info, I did try completely uninstalling WSL and re-installing it.  I have not yet tried completely uninstalling Docker for Windows and re-installing it.

Out of curiosity @rneugeba, how big was the context that you were sending between WSL and the Docker daemon?  Mine is about 50MB, perhaps that plays a role?  As I mentioned, it usually stalls out at around 12MB (varies slightly).

**Comment by rneugeba** [comment] 2016-09-25 22:12
Hmm, this indeed seems to be an issue with WSL when the context is larger. Sending the same context (with the same Dockerfile) via powershell (from `C:\Users\<user>\AppData\Local\lxss\home\<user>`) works fine.

As mentioned, we don't really support this configuration...it just happens to work, kinda/kinda not. I personally don't consider WSL ready for prime time in any case...to many things don't quite work.

FWIW, the upload stalls on:
```
read(6, "\10H\211D$\20H\211T$\30H\211\\$ \350\253\315\362\377H\213L$(H\213\\$0H"..., 32768) = 32768
futex(0x1395f08, FUTEX_WAIT, 0, NULL
```
quite possibly an issue with the WSL Linux system call emulation

**Comment by justincormack** [comment] 2016-09-25 22:33
I recommend filing a bug at https://github.com/Microsoft/BashOnWindows with
how to reproduce, Microsoft have been fairly responsive there.

**Comment by justincormack** [comment] 2016-09-25 23:09
I am going to close this as it is not a supported platform, but please do continue to post here, and let us know when there is a fix, as you are not the first person to try this, just as far as I know the first to find an issue.

**Closed by justincormack** 2016-09-25 23:09 UTC
Labels: platform/desktop, platform/windows, version/1.12

**Comment by omarqureshi** [comment] 2017-01-26 23:36
FWIW if i build the images using docker-compose (by specifying ```build: .``` it does build.

The same image when built using ```docker build .``` fails as described by the other people here.

**Comment by MicahZoltu** [comment] 2017-01-26 23:54
It turned out the bug was with WSL, not Docker and the current status is reflect over at https://github.com/Microsoft/BashOnWindows/issues/1123 for anyone following along.

That being said, I would encourage the Docker team to get official WSL support somewhere on the roadmap (at least for the client libraries) as I suspect that WSL is going to play an increasingly important role in enterprise dev ops in the future.

**Comment by dashesy** [comment] 2017-03-15 21:00
@omarqureshi That is odd. docker-compose works fine but not docker build!

**Comment by friism** [comment] 2017-03-15 22:16
@dashesy please these links for details:

 * https://github.com/Microsoft/BashOnWindows/issues/1123
 * https://github.com/docker/for-win/issues/576#issuecomment-286811701
