### ISSUE TITLE
Impossible removal of non-empty directory after previous deletion by a rm command within a dedicated RUN directive

### ISSUE THREAD

**Issue by michelecardone** [docker/docker#29658] opened 2016-12-22 12:17 UTC
**Description**

I discovered an issue related to Docker but limited to a specific environment configuration.

The issue consists in the impossibility to delete a non-empty directory, both at build-time and run-time, when it was already deleted by a `rm` command within a dedicated `RUN` directive.
To make an example the following set of `RUN` directives leads to a build fail:

```
RUN cd /root && mkdir test && touch test/file.txt
RUN rm -rf /root/test && [ ! -e /root/test ]
RUN cd /root && mkdir test && touch test/file.txt
RUN rm -rf /root/test && [ ! -e /root/test ]  # This test fails!
```

But the following works:

```
RUN cd /root && mkdir test && touch test/file.txt && \
rm -rf /root/test && [ ! -e /root/test ]
RUN cd /root && mkdir test && touch test/file.txt && \
rm -rf /root/test && [ ! -e /root/test ]
```

I found this issue occurs with the following environment configuration:

```
Docker: 1.12.5
Storage Driver: aufs
Operating System: Debian 8 "Jessie" 
Kernel: 3.16.0-4-amd64
```

The issue doesn't occur with the following environment configurations:

```
Docker: 1.12.5
Storage Driver: devicemapper
Operating System: Debian 9 "Stretch" (testing)
Kernel Version: 4.8.0
```

```
Docker: 1.12.5
Storage Driver: aufs
Operating System: Alpine Linux 3.4
Kernel Version: 4.4.39-moby
```

It might be an issue related to the combination of an outdated Linux kernel and the `aufs` file system.

**Steps to reproduce the issue:**

```
FROM alpine

RUN cd /root && mkdir test && touch test/file.txt
RUN rm -rf /root/test && [ ! -e /root/test ]
RUN cd /root && mkdir test && touch test/file.txt
RUN rm -rf /root/test && [ ! -e /root/test ]
```

**Describe the results you received:**

```
Step 1 : FROM alpine
 ---> baa5d63471ea
Step 2 : RUN cd /root && mkdir test && touch test/file.txt
 ---> Running in caed4be9b143
 ---> 4157707493b5
Removing intermediate container caed4be9b143
Step 3 : RUN rm -rf /root/test && [ ! -e /root/test ]
 ---> Running in fc5a3220cc51
 ---> 33e29c42f53b
Removing intermediate container fc5a3220cc51
Step 4 : RUN cd /root && mkdir test && touch test/file.txt
 ---> Running in b9a8131f541a
 ---> 24d3056e7b1e
Removing intermediate container b9a8131f541a
Step 5 : RUN rm -rf /root/test && [ ! -e /root/test ]
 ---> Running in 6dc79a4eeecd
The command '/bin/sh -c rm -rf /root/test && [ ! -e /root/test ]' returned a non-zero code: 1
```

**Describe the results you expected:**

```
Step 1 : FROM alpine
 ---> baa5d63471ea
Step 2 : RUN cd /root && mkdir test && touch test/file.txt
 ---> Running in caed4be9b143
 ---> 4157707493b5
Removing intermediate container caed4be9b143
Step 3 : RUN rm -rf /root/test && [ ! -e /root/test ]
 ---> Running in fc5a3220cc51
 ---> 33e29c42f53b
Removing intermediate container fc5a3220cc51
Step 4 : RUN cd /root && mkdir test && touch test/file.txt
 ---> Running in b9a8131f541a
 ---> 24d3056e7b1e
Removing intermediate container b9a8131f541a
Step 5 : RUN rm -rf /root/test && [ ! -e /root/test ]
 ---> Running in 6dc79a4eeecd
 ---> xxx
Removing intermediate container 6dc79a4eeecd
Successfully built xxx
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:21:54 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:21:54 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.873 GiB
Name: labtech8
ID: YOSF:AJSF:NTMK:ALXN:7U7C:X5PC:T7O2:BBVA:ANHS:IDBA:XRGO:QOYD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The environment is a VMware vSphere virtual machine.

**Comment by thaJeztah** [comment] 2016-12-22 17:55
I suspect this is a duplicate of https://github.com/docker/docker/issues/24309, and an issue in `aufs`, not docker; @AkihiroSuda created a test-script for that case; perhaps you can try running that to verify it's the same problem; https://github.com/AkihiroSuda/test24309-without-docker

**Comment by michelecardone** [comment] 2016-12-23 14:46
I prepared a Dockerfile as @AkihiroSuda suggested in #24309.

For each one of my environments I respectively built the image and run it. The result are:

- In

  ```
  Docker: 1.12.5
  Storage Driver: devicemapper
  Operating System: Debian 9 "Stretch" (testing)
  Kernel Version: 4.8.0
  ```

  the following message has been printed:

  ```
  cat: can't open '/x/a': No such file or directory
  ```

  So, everything is OK.

- In
  
  ```
  Docker: 1.12.5
  Storage Driver: aufs
  Operating System: Debian 8 "Jessie" 
  Kernel: 3.16.0-4-amd64
  ```

  the string _"hey2"_ string has been printed, which is an error.

**Comment by thaJeztah** [comment] 2016-12-23 15:30
Thank you for testing! It looks like a duplicate of the linked issue indeed. Unfortunately, I don't have a direct solution for that, other than working around the problem in your docker files, or using a different storage driver. I see you're running `devicemapper` on the other machine, which "works", but overall performs a lot less than aufs, and to be suitable for production [requires manual setup](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/configure-direct-lvm-mode-for-production), otherwise performance will be very poor.

Depending on your use case, one of the other options (such as btrfs, or zfs) could work, but also require some setup.

If you are able to run on a more recent kernel (such as the "Debian 9 stretch" machine), have a look at the `overlay` storage drivers as well. The overlay and overlay2 drivers perform very well; The overlay2 driver resolves  the  "running out of inodes" issue that the `overlay` driver could have if you run a lot of containers (https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#/overlay-vs-overlay2). More info on those here; https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

I'll close this issue because this is a duplicate of https://github.com/docker/docker/issues/24309, but please subscribe to the linked issue to stay informed on updates. Also feel free to comment here after I closed

**Closed by thaJeztah** 2016-12-23 15:30 UTC
Labels: area/builder, area/storage/aufs, version/1.12

**Comment by michelecardone** [comment] 2016-12-23 15:55
My personal workaround is transforming this:

```
FROM alpine

RUN cd /root && mkdir test && touch test/file.txt
RUN rm -rf /root/test && [ ! -e /root/test ]
RUN cd /root && mkdir test && touch test/file.txt
RUN rm -rf /root/test && [ ! -e /root/test ]
```

into this:

```
FROM alpine

RUN cd /root && mkdir test && touch test/file.txt && \
rm -rf /root/test && [ ! -e /root/test ]
RUN cd /root && mkdir test && touch test/file.txt && \
rm -rf /root/test && [ ! -e /root/test ]
```

If the deletion commands are squashed with the respective creation ones the error is gone.
My teammate prepared a new Debian 9 _Stretch_ VM, just for emergency. Anyway the workaround seems sufficient at the moment.

Regarding _overlay2_, would it really be as performant as AUFS?

**Comment by thaJeztah** [comment] 2016-12-23 16:13
> Regarding overlay2, would it really be as performant as aufs?

It may depend on your use case, but it's definitely worth a try; perhaps if you have a test-system available
