### ISSUE TITLE
Linked docker container sometimes starts without host volumes

### ISSUE THREAD

**Issue by martinus32** [docker/docker#17612] opened 2015-11-02 16:25 UTC
Hello,

I link to containers together to exchange data (logfiles) between both containers. 

The first container is started with 
docker run --net=host -e env1=val1 -e env2=val2 --name server-dev docker-registry.test.net:5000/app/app-server:0.0.1
The second container is started with 
docker run --volumes-from server-dev --name sidekick-dev -e env1=val1,val2,val3 docker-registry.test.net:5000/app/sidekick:0.0.1 /bin/sh /opt/app/entrypoint.sh

In 1-2 of 10 starts the second container starts without host volumes. When the containers are started permanently (within a loop) the problem does not occur or does not occur so often. This means that if the time between last start and new start increases the number of problems also increases.

docker inspect shows the following output, when the problem occurs:
[
{
    "Id": "209f50bec5dca094ee0064dcdfbe434b72f1cd9a84d5a83efaa75194094534da",
    "Created": "2015-10-26T16:26:58.691345203Z",
    "Path": "/opt/app/entrypoint.sh",
    "Args": [],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 24246,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-10-26T16:26:58.834806454Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "a05199e4b8b2148dedfcb678248e00ff3654308ce03e5c1860736060d37b4915",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "9344951343b86a5f36c0369911002ebd743accbcd059a356d740afdf727edf24",
        "Gateway": "10.139.38.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "10.139.38.32",
        "IPPrefixLen": 24,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:0a:8b:26:20",
        "NetworkID": "88f0e150a640df5ce9a4074e774e1e9ae77c9734ca0644b1f5ff058b56d25270",
        "PortMapping": null,
        "Ports": {
            "6379/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/209f50bec5dc",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/209f50bec5dca094ee0064dcdfbe434b72f1cd9a84d5a83efaa75194094534da/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/209f50bec5dca094ee0064dcdfbe434b72f1cd9a84d5a83efaa75194094534da/hostname",
    "HostsPath": "/var/lib/docker/containers/209f50bec5dca094ee0064dcdfbe434b72f1cd9a84d5a83efaa75194094534da/hosts",
    "LogPath": "/var/lib/docker/containers/209f50bec5dca094ee0064dcdfbe434b72f1cd9a84d5a83efaa75194094534da/209f50bec5dca094ee0064dcdfbe434b72f1cd9a84d5a83efaa75194094534da-json.log",
    "Name": "/sidekick-test",
    "RestartCount": 0,
    "Driver": "overlay",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {},
    "VolumesRW": {},
    "AppArmorProfile": "",
    "ExecIDs": [
        "4a2d365f9b62cc06d986b117b137bc9e8cdc065b83cc885209b741c2cbb587a4"
    ],
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "Config": {
        "Hostname": "209f50bec5dc",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {
            "6379/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "env1=val1,val2,val3",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LT_PKG_NAME=logstash-1.5.4",
            "LS_HOME=/opt/ELK/logstash",
            "LS_CONFIG=/opt/ELK/logstash/conf",
            "LS_LOG=/opt/ELK/logstash/log/logstash.log",
            "JAVA_HOME=/usr/lib/jvm/jre-1.7.0-openjdk.x86_64"
        ],
        "Cmd": [
            "/opt/app/entrypoint.sh"
        ],
        "Image": "docker-registry.test.net:5000/app/sidekick:0.0.1",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "/data",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]

**Comment by martinus32** [comment] 2015-11-02 16:30
Additonal information:

 docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): df2f73d-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): df2f73d-dirty
OS/Arch (server): linux/amd64

docker info
Containers: 4
Images: 65
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-coreos
Operating System: CoreOS 766.4.0
CPUs: 2
Total Memory: 3.864 GiB
Name: s0001
ID: ZSVH:3NVM:AYM5:VM56:UH7B:FAX5:YZOT:KBWQ:E4PF:SXOY:6HBJ:E7OR

uname -a
Linux s0001 4.1.7-coreos #2 SMP Wed Sep 16 22:54:37 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz GenuineIntel GNU/Linux

**Comment by thaJeztah** [comment] 2015-11-12 00:40
Are you able to reproduce this on the current release (1.9.0)? Also, it looks like you're running a docker version that's build by CoreOS (`df2f73d-dirty`), those builds contain some patches that could potentially be of influence.

**Comment by LK4D4** [comment] 2016-09-14 00:19
Closing because it's old and code changed too much since.

**Closed by LK4D4** 2016-09-14 00:19 UTC
