### ISSUE TITLE
volume plugins not mount-able on services: not registering on swarm nodes

### ISSUE THREAD

**Issue by mnottale** [docker/docker#23619] opened 2016-06-16 09:45 UTC
Tested on e3ad63f.

I have a volume driver that appears in "docker info", but not in "docker node inspect -p self".  The result is that the PluginFilter check fails (plugin not in nodeInfo.Description.Engine.Plugins) when attempting to --mount a volume provided by this driver in "service create".

**Comment by icecrime** [comment] 2016-06-16 14:44
Thanks for the report! Cc @stevvooe FYI.

**Comment by stevvooe** [comment] 2016-06-16 18:11
@mnottale Could you provide the output of `docker info`, `docker node inspect -p self`, and `docker service inspect` on the service?

We'll need to figure out whether the node is not announcing the plugin or there is a bug in the matching logic.

**Comment by mnottale** [comment] 2016-06-16 19:26
Ok, I investigated a bit more, and the problem occurs only when dockerd is restarted and rejoins an existing swarm, as shown by this shell session
```
$ dockerd&
$ docker info |grep Volume                                                                            21:18:27
 Volume: local
$ docker volume ls
$ docker info |grep Volume                                                                            21:19:11
 Volume: local infinit
$ docker swarm init
$ docker node inspect self |grep -C 1 infinit                                                         21:20:06
                        "Type": "Volume",
                        "Name": "infinit"
                    },
$ killall dockerd && dockerd&
$ docker info |grep Volume                                                                            21:20:12
 Volume: local
$ docker volume ls
$ docker info |grep Volume                                                                            21:21:12
 Volume: local infinit
$ docker node inspect self |grep -C 1 infinit
 NOTHING
```

If I recreate the swarm (with leave --force then init), my driver becomes visible again.

Hope this helps,

**Comment by stevvooe** [comment] 2016-06-16 21:41
@mnottale Interesting. It looks like there is a bug in the volume reporting: https://github.com/docker/docker/blob/6381ed14d13b57873eb985380e52c9ff4fd94b98/daemon/info.go#L172. If `docker info` doesn't return it, the manager can't schedule on it.

How are you running the plugin?

@icecrime Any ideas?

**Comment by mnottale** [comment] 2016-06-16 22:10
The plugin advertises itself in /usr/lib/docker/plugins/infinit.json and exposes /run/docker/plugins/infinit.sock for communication as the volume driver doc stipulates. Should I be doing something else?

**Comment by stevvooe** [comment] 2016-06-16 22:26
@mnottale That all sounds correct. I was mostly wondering if the plugin was running in a docker container, and wasn't restarted with docker.

**Comment by mnottale** [comment] 2016-06-16 22:28
No, in this test the plugin is running on the host computer and stays on all the time.

**Comment by stevvooe** [comment] 2016-06-16 22:33
@mnottale Great. We should be able to track this down. Do you have a link to this particular plugin? We may need to check to see if is behaving correctly.

**Comment by thaJeztah** [comment] 2016-06-17 00:37
@stevvooe I think `docker info` only shows plugins that are actually used for a volume (don't ask me why), so if there's no volume that uses a plugin, `docker info` won't return it.

I stumbled upon that recently, but @tiborvass may know more

**Comment by tiborvass** [comment] 2016-06-17 01:00
@thaJeztah that's correct it's because they are lazily loaded. I believe we should consider it a bug. I'll see what i can do.

**Comment by stevvooe** [comment] 2016-06-17 19:44
> @stevvooe I think docker info only shows plugins that are actually used for a volume (don't ask me why), so if there's no volume that uses a plugin, docker info won't return it.

Sigh.

@tiborvass Let me know if you need help tracking this down.

**Comment by tiborvass** [comment] 2016-06-17 21:26
@stevvooe i'll figure out the `docker info` part, if the problem is still here I'll need your help on the service part.

**Comment by stevvooe** [comment] 2016-06-17 21:31
@tiborvass Thank you!

I think there are issues with the mount translation and maybe the transmission of the mount call to the driver. I'll investigate these issues, if you can take care of the reporting bug.

**Comment by hkvemuri** [comment] 2016-06-28 14:58
I see the same issue even though there are volumes available

$ docker volume ls
DRIVER              VOLUME
veritas             testvol
$

$ docker info 2>/dev/null | grep Volume
 Volume: local veritas
$

But still I am unable to use the volume to start a service.
$ docker service create --replicas 1 --name testsrv -m testvol=/var/lib/mysql -e MYSQL_ROOT_PASSWORD=test123 mysql
invalid argument "testvol=/var/lib/mysql" for m: unexpected key 'testvol' in '/var/lib/mysql'
See 'docker service create --help'.
$

**Comment by cpuguy83** [comment] 2016-06-28 15:39
@hkvemuri `--mount type=volume,source=testvol,target=/var/lib/mysql`

**Comment by cpuguy83** [comment] 2016-06-28 15:40
Note there is currently a bug where this won't work, though.

**Comment by hkvemuri** [comment] 2016-06-28 16:11
Thanks @cpuguy83 got it to work now
I could not find the correct syntax, so may be we can have it in the help message

**Comment by jtyberg** [comment] 2016-07-20 00:41
I believe I'm hitting this issue too.

I'm using the convoy plugin and running a convoy daemon on all manager and worker hosts, backed by NFS.

```
convoy info
{
"General": {
	"Root": "/var/lib/rancher/convoy",
	"DriverList": [
		"vfs"
	],
	"DefaultDriver": "vfs",
	"MountNamespaceFD": "",
	"IgnoreDockerDelete": false,
	"CreateOnDockerMount": false,
	"CmdTimeout": ""
},
"vfs": {
	"DefaultVolumeSize": "107374182400",
	"Path": "/mnt/nfs",
	"Root": "/var/lib/rancher/convoy/vfs"
}
}


cat /etc/docker/plugins/convoy.spec 
unix:///var/run/convoy/convoy.sock
```

On manager node, convoy plugin shows up using `docker info`:

```
docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 26
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 126
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local convoy
 Network: bridge null host overlay
Swarm: active
 NodeID: cqpetlbvst4fakxfucxhxe4f7
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:fe4479b3a8ab55cd4ca53ab500728d49ae7848ab0702e8a6841dde370916dbb2
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: swarm-manager1
ID: 57GC:NUNG:HOIV:GXIB:MNDN:PEAG:BV7C:LD4M:V6PG:GAS4:M4C7:ZPMH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=softlayer
Insecure Registries:
 127.0.0.0/8
```

But convoy does not show up when inspecting nodes. 

```
docker node inspect -p swarm-worker2
ID:			4yxx90ogjmdz3gx2kbgk071zc
Hostname:		swarm-worker2
Status:
 State:			Ready
 Availability:		Active
Platform:
 Operating System:	linux
 Architecture:		x86_64
Resources:
 CPUs:			4
 Memory:		15.67 GiB
Plugins:
  Network:		overlay, bridge, null, host, overlay
  Volume:		local
Engine Version:		1.12.0-rc4
Engine Labels:
```

When I create a service with a volume mount using `volume-driver=convoy`, no tasks start for the service.

```
docker service create --name hello --publish 80 --mount type=volume,source=www,target=/www,volume-driver=convoy tutum/hello-world
4g8ohfuu3oljeo5xbj3zrcr5g

docker service ls
ID            NAME              REPLICAS  IMAGE                                COMMAND
4g8ohfuu3olj  hello             0/1       tutum/hello-world                    

docker service tasks hello
ID                         NAME     SERVICE  IMAGE              LAST STATE                    DESIRED STATE  NODE
edp5e0fi0jambqp4y4gd5pisx  hello.1  hello    tutum/hello-world  Allocated about a minute ago  Running        

```

If I use `volume-driver=local`, it works fine.

On manager:

```
docker service create --name hello-local --publish 80 --mount type=volume,source=www,target=/www,volume-driver=local tutum/hello-world
7j6nze5u3d9wmqbital102tya

docker service tasks hello-local
ID                         NAME           SERVICE      IMAGE              LAST STATE              DESIRED STATE  NODE
akksphbansrztoc6sxt7mxbxz  hello-local.1  hello-local  tutum/hello-world  Running 15 seconds ago  Running        swarm-worker2
```

FWIW, I created my swarm before installing convoy on each node.

**Comment by tiborvass** [comment] 2016-07-25 23:42
Will be fixed by https://github.com/docker/swarmkit/pull/1224 once it's vendored.

**Closed** 2016-07-26 08:47 UTC
Labels: area/plugins, area/swarm, kind/bug, priority/P1

**Comment by mnottale** [comment] 2016-07-26 10:36
In the meantime I found a workaround, if your volume appears in "docker volume ls", you can mount it in a service by *not* setting the "volume-driver" option to "--mount". Hope it helps.

**Comment by stevvooe** [comment] 2016-07-26 18:47
@mnottale 

> you can mount it in a service by not setting the "volume-driver" option to "--mount". Hope it helps.

In fact, if you're willing to create volumes on the target machines, which is reasonable in some scenarios, omitting the volume-driver parameters should be considered best practice.

cc @sfsmithcha

**Comment by adityacs** [comment] 2017-05-28 09:01
@stevvooe @tiborvass I am still facing this issue in docker 17.05.0-ce.

**Comment by kerk1v** [comment] 2017-11-29 13:17
Same here with docker 17.09.0-ce. 
Only the master node (and I don' schedule service jobs on it) seems to be able to use convoy with NFS backed storage in the proper way. 
![screen shot 2017-11-29 at 14 14 13](https://user-images.githubusercontent.com/16302524/33376960-f9c9f4ec-d50f-11e7-8c94-8a706f477d4e.png)
