### ISSUE TITLE
/etc/hosts contains invalid entry when linked container gets destroyed and re-created

### ISSUE THREAD

**Issue by TomNussbaumer** [docker/docker#15811] opened 2015-08-25 10:35 UTC
Suppose you have two containers linked together. If the first one (the link source) gets destroyed and have to be recreated, the /etc/hosts file of the second container will still list an entry of the initial linked but now invalid container.

The problem here is that this old and invalid entry is ordered before the new entries. So a `ping <linkname>` will be resolved to the dead ip instead the new one. Only a `ping <linkname>.bridge` will reach the new container.

Is this behaviour intended?

**reported against: Release 1.8.1**

**How to reproduce:**
```shell
## in terminal 1: create link source test0
docker run -ti --rm --name=test0 busybox sh

## in terminal 2: create container referencing test0
docker run -ti --rm --link=test0 busybox sh

## in terminal 1: destroy and re-create test0
exit
docker run -ti --rm --name=test0 busybox sh

## in terminal 2: try to resolve link name via /etc/hosts
ping test0             # will not reach new container (will hit old ip)
ping test0.bridge  # works
```

-------

**docker version:**

Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

**docker info:**

Containers: 0
Images: 223
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 223
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 1.708 GiB
Name: XXXXXXXXXXX
ID: LTQV:FX2J:7YSF:RJ7G:A2GG:437K:WVA6:VQXC:GN5H:LEBR:R3XM:YW5B
Username: XXXXXXXXXXXX
Registry: https://index.docker.io/v1/

**uname -a:**

Linux tnussb-htpc 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Running native on physical host.

**Comment by thaJeztah** [comment] 2015-08-30 19:06
> Is this behaviour intended?

Yes, this is intended; links that are established between containers are created for a specific *instance* of the container, not based on the *name* of the container. When destroying the container that's linked to, the link is destroyed with it.

When creating a *new* container (even with the same name), docker will not automatically create a link to that container.

Because there's no longer a link, the `/etc/hosts` is also no longer updated.
The only enhancement we can make here, is to *remove* the entry from `/etc/hosts` when the link is destroyed. We talked about this some time ago in another issue

In future, "links" will be deprecated in favor of the new networking features, that can currently be found in the experimental build, and offer far more flexibility than the current linking model. For more information, see the description of the experimental features here; https://github.com/docker/docker/blob/master/experimental/networking.md

I'm going to close this issue, because this is by design, and it's a dup of https://github.com/docker/docker/issues/12067, https://github.com/docker/docker/issues/10066, and others

**Closed by thaJeztah** 2015-08-30 19:06 UTC
Labels: group/networking, system/networking

**Comment by mfischer-zd** [comment] 2015-10-26 20:15
How can users who need this functionality today (persistent links to containers having a particular name) attain it?

**Comment by thaJeztah** [comment] 2015-10-26 20:18
@mfischer-zd it's coming in the new networking functionality in docker 1.9, where containers can be dynamically added to/removed from a network

**Comment by mfischer-zd** [comment] 2015-10-26 20:22
@thaJeztah I'm testing RC2 - where can I find the docs on that?    The link above is broken.

**Comment by thaJeztah** [comment] 2015-10-26 20:26
@mfischer-zd docs are being worked on; you can find the PR here; https://github.com/docker/docker/pull/17161
