### ISSUE TITLE
Proposal: add log hook to docker daemon log

### ISSUE THREAD

**Issue by x1022as** [docker/docker#11170] opened 2015-03-05 07:43 UTC
Sometimes, we need to notify adminitrator about docker's running errors, thus they can perform proper reaction to the problem.

I think logrus's hook feature is a good solution. Logrus now supports  airbrake, papertrial, sentry and syslog. And it's easy to add hook to logrus. However, to complete this, maybe we need some more docker daemon parameters like "--log-hook="***" ...", to achieve a flexible setting :)

**Comment by cpuguy83** [comment] 2015-03-05 15:57
Why not capture the logs (since docker just sends them to stdout anyway) and forward to whatever service you like?

**Comment by x1022as** [comment] 2015-03-06 01:20
@cpuguy83 ,yes, it will satisfy this request. but in production scene, people may need this feature directly from docker, no more  third-party applications.

**Comment by phemmer** [comment] 2015-03-06 06:30
Logrus has major design issues, especially when it comes to the hooks system. Using its hook capabilities inside a production application, such as Docker, would be a bad idea.

I'm with cpuguy83. Log parsing is a very common practice when it comes to system monitoring. Any decent monitoring system (Nagios, SolarWinds, OpenView, etc) will have very extensive support for alerting based on log file conditions.

Personally, the only logging extension I might see being added is syslog support.

**Comment by x1022as** [comment] 2015-03-09 01:19
@phemmer 
`'Logrus has major design issues, especially when it comes to the hooks system. Using its hook capabilities inside a production application, such as Docker, would be a bad idea.'`
Thks, I am not aware of this. And, yes, I'd like syslog support as logging extension.

**Comment by burke** [comment] 2015-03-19 02:20
> Logrus has major design issues, especially when it comes to the hooks system. Using its hook capabilities inside a production application, such as Docker, would be a bad idea.

I agree that it would be wrong to expose these hooks in an open source application such as docker, but I'm curious what design issues you see that make them unsuitable for production applications in general.

**Comment by Sirupsen** [comment] 2015-03-19 13:43
> Logrus has major design issues, especially when it comes to the hooks system. Using its hook capabilities inside a production application, such as Docker, would be a bad idea.

Yeah, I'd like this explained in depth as well.

**Comment by phemmer** [comment] 2015-03-22 10:09
The number one issue is actually one I filed here: https://github.com/Sirupsen/logrus/issues/107
The root of the problem is that the entry formatter is global. Every single hook formats the entry in the same way. Where this becomes a problem is with the automatic formatting change when writing to a terminal, vs not terminal.
So lets say you send the output to syslog. Depending on whether the program had a TTY on it when it was launched, the syslog data format changes (and can include the color escape codes as well). This can be very bad if you rely on this data to be consistent.
The data also becomes highly redundant. Syslog has headers which include the time, and severity of the message. But because the formatter is global, it also adds time & level. So when viewing the syslog output, you see all this info twice.

The other major concern I have with the code is strictly my opinion. And I emphasize the opinion bit. But logrus has some significant spaghetti code. Instead of following the typical hierarchical design, the code jumps around a lot. For example, when an entry is logged, the entry object is created, and stores a reference to the logger object it was created from. The entry object then sends itself to the logger object's hooks object, which sends the entry to each hook. The entry then uses the formatter on the logger object to format itself, and then gets the output stream (IO writer) from the logger object, and sends itself to the stream.
This is a lot of jumping around that I think makes the code rather messy (again, my opinion), and leads to issues like the one above.

There are also other minor issues (such as locking, error handling, blocking execution, etc), but nothing that couldn't be easily fixed.

**Comment by Sirupsen** [comment] 2015-03-22 14:25
@phemmer I think those are valid opinions, thank you for compiling it into one comment. I'm not necessarily for using Logrus hooks inside Docker, I don't think this should be a concern of Docker at this point. 

Either way, I agree with you—there are definitely fundamental flaws to the current design of Logrus, as pointed out by cases like #107. The idea was to gather those use cases from the wild with an initial design, and then rebuild it based on the issues seen before 1.0. I think we're rapidly approaching that point, with 100s of production applications running Logrus.

**Comment by cpuguy83** [comment] 2015-07-22 03:11
Closing since it seems like this is not something we actually want to do.

**Closed by cpuguy83** 2015-07-22 03:11 UTC
