### ISSUE TITLE
Expose UDP not working

### ISSUE THREAD

**Issue by pjebs** [docker/docker#20895] opened 2016-03-03 03:39 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

NOTE: There are lots of duplicate issues but I'm pretty sure they are for super old versions of Docker.

In my Dockerfile I have:
`EXPOSE 3456`
`EXPOSE 3456/udp`

(Ideally I would like it to be possible in one line but not a big deal).

When I run `docker run -P ....`
it does not expose the udp port.

I need Docker's `-P` feature where it randomly selects an EXTERNAL PORT but I need it to expose that port to TCP AND UDP traffic.

i.e. if external port 12345 is selected it should allow TCP and UDP traffic and route it to my container's port 3456.

**Comment by pjebs** [comment] 2016-03-03 03:40
There are various ways of using lowercase `-p` argument to do that BUT that requires me to select the port myself.

**Comment by pjebs** [comment] 2016-03-03 09:36
-P creates 2 external ports that map to the one internal port.
`0.0.0.0:32789->3456/udp, 0.0.0.0:33359->3456/tcp`

**Comment by thaJeztah** [comment] 2016-03-03 14:45
Thanks for reporting! This is a duplicate of https://github.com/docker/docker/issues/4635, please continue the discussion there

**Closed by thaJeztah** 2016-03-03 14:45 UTC
