### ISSUE TITLE
Docker tag strict pattern disallows semver.

### ISSUE THREAD

**Issue by vromero** [docker/docker#27269] opened 2016-10-10 23:58 UTC
**Description**

Docker [tag](https://docs.docker.com/engine/reference/commandline/tag/) is enforcing a strict pattern on the tag names:

> A tag name may contain lowercase and uppercase characters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

This prevents users to tag with the de-facto standard: semver, as semver 2.0 can potentially use a '+' character to include [metadata](http://semver.org/#spec-item-10).

**Steps to reproduce the issue:**
1. 
`docker tag 1fa4b226ec62 1.0.0-alpha+001`

**Describe the results you received:**

`Error parsing reference: "1.0.0-alpha+001" is not a valid repository/tag`

**Describe the results you expected:**

Return code 0.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time.

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 81
Server Version: 1.12.2-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 79
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.22-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: GMUV:VFBH:VPNG:VPSB:HIZE:CV37:XVXC:QU22:VHLC:UEZF:AMSH:MUAA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 27
 System Time: 2016-10-10T23:57:23.513758787Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

MacOSX

**Comment by thaJeztah** [comment] 2016-10-11 18:14
Thanks for reporting, looks like this is a duplicate of https://github.com/docker/docker/issues/18168, which is being discussed in https://github.com/docker/distribution/issues/1201, and https://github.com/docker/distribution/pull/1202. I'll close this issue to keep the discussion central, but feel free to comment after I closed

**Closed by thaJeztah** 2016-10-11 18:14 UTC
Labels: kind/enhancement, version/1.12

**Comment by vromero** [comment] 2016-10-11 19:10
Apologies, I searched extensively but somehow I didn't find the previous issue although it has almost the exact same title :S

**Comment by thaJeztah** [comment] 2016-10-11 19:18
@vromero no need to apologize, GitHub search is notoriously bad
