### ISSUE TITLE
docker push to private registry on non standard port fails

### ISSUE THREAD

**Issue by onorua** [docker/docker#15048] opened 2015-07-27 18:58 UTC
what I have:
```
root@590e448faddf:/# docker version 
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

root@590e448faddf:/# docker info
Containers: 0
Images: 3
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu 14.04.2 LTS (containerized)
CPUs: 12
Total Memory: 62.89 GiB
Name: 590e448faddf
ID: GWWT:GQ6P:UZ4X:BC6A:ANVC:TDQ2:V6JV:QTG5:6HAN:YY2I:52NW:WZE5
WARNING: No swap limit support
```
what I do:
```
root@590e448faddf:/# docker -l debug push docker-registry.smctr.net:5000/busybox:latest
The push refers to a repository [docker-registry.smctr.net:5000/busybox] (len: 1)
8c2e06607696: Image push failed 
Error pushing to registry: Put https://docker-registry.smctr.net/v2/busybox/blobs/uploads/b7047031-ced6-4a10-abee-1e65e36f9451?_state=kW7NxcB2f0WVSh4NeDnEtYYcXh291XLrCCngQlNQr8Z7Ik5hbWUiOiJidXN5Ym94IiwiVVVJRCI6ImI3MDQ3MDMxLWNlZDYtNGExMC1hYmVlLTFlNjVlMzZmOTQ1MSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNS0wNy0yN1QxODo0OTozMi40MzMzMzQwNTlaIn0%3D&digest=sha256%3Aa3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4: dial tcp 195.12.14.249:443: connection timed out
```
registry is behind nginx proxy:
```
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;
    client_max_body_size 0;
    chunked_transfer_encoding on;

server {
   listen 443 ssl;
   server_name docker-registry.smctr.net;

   add_header Docker-Distribution-Api-Version: registry/2.0 always;

   ssl on;
   ssl_certificate /etc/nginx/ssl.crt;
   ssl_certificate_key /etc/nginx/ssl.key;

   proxy_set_header Host $host;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_set_header X-Original-URI $request_uri;
   proxy_set_header Docker-Distribution-Api-Version registry/2.0;

   location / {
     auth_basic "Restricted";
     auth_basic_user_file /etc/nginx/htpasswd;
     proxy_pass http://docker-registry-backend.infra:5000;
   }
}
```
in nginx logs I see:
```
10.116.160.1 - - [27/Jul/2015:18:49:31 +0000] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-37-generic os/linux arch/amd64" "-"
10.116.160.1 - - [27/Jul/2015:18:49:31 +0000] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-37-generic os/linux arch/amd64" "-"
10.116.160.1 - - [27/Jul/2015:18:49:32 +0000] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-37-generic os/linux arch/amd64" "-"
10.116.160.1 - ot [27/Jul/2015:18:49:32 +0000] "HEAD /v2/busybox/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 404 0 "-" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-37-generic os/linux arch/amd64" "-"
10.116.160.1 - ot [27/Jul/2015:18:49:32 +0000] "POST /v2/busybox/blobs/uploads/ HTTP/1.1" 202 0 "-" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.13.0-37-generic os/linux arch/amd64" "-"
```
config.json looks like:
```
{
        "auths": {
                "https://docker-registry.smctr.net:5000": {
                        "auth": "{deleted}",
                        "email": "test@test.com"
                }
        }
}
```
what am I doing wrong?

**Comment by onorua** [comment] 2015-07-27 19:38
interesting, when I've set port forwarding: 172.17.42.1:443 -> 195.12.14.249:5000
I've got push working without any problems... 
```
root@590e448faddf:~/.docker# docker push docker-registry.smctr.net/busybox
The push refers to a repository [docker-registry.smctr.net/busybox] (len: 1)
8c2e06607696: Image already exists 
6ce2e90b0bc7: Image successfully pushed 
6ce2e90b0bc7: Buffering to Disk 
Digest: sha256:cd8f82e67eed3529eb65d72fe2ea073f64205910c2878074f7217962a9b14789
```

**Comment by dmp42** [comment] 2015-07-27 21:04
cc @docker/distribution-maintainers

**Comment by stevvooe** [comment] 2015-07-29 18:03
@onorua It looks like nginx is running on port 443, but you've tagged the images as `docker-registry.smctr.net:5000/busybox:latest`. Just tag the image as `docker-registry.smctr.net/busybox:latest` and it should work.

**Comment by onorua** [comment] 2015-07-30 14:52
@stevvooe why would I use port 5000 if I have nginx on 433 directly available? :) 
The network flow is following:
Jenkins docker builder -> {internet} -> {port 5000 on ASA firewall} -> 443 port on registry -> prod clients

**Comment by stevvooe** [comment] 2015-07-30 19:14
@onorua I'm a little bit confused: what port is the registry accessible on externally? Is it now working with the proper port forwarding or are there still problems?

My guess is that the port forwarding is causing the registry to issue incorrect redirects. For example, based on the proxy, it thinks its running as `docker-registry.smctr.net`, so it will issue redirects to that. If the actual port is 5000, you'd have to configure the proxy to tell the registry that the port is 5000, so it can issue the proper redirect.

**Comment by onorua** [comment] 2015-08-09 14:50
Sorry for the late reply, was on vacation. 
Do you mean that registry for some reason doesn't go with relative path as stated in [RFC7231] (https://tools.ietf.org/html/rfc7231#section-7.1.2) but use full URI with port? Why would you do it that way?

**Comment by stevvooe** [comment] 2015-08-11 19:49
@onorua The issue is that you are exposing a registry on your firewall as `docker-registry.smctr.net:5000` but the registry sees `docker-registry.smctr.net` due to the way the proxy is configured. To fix this, either hard code `X-Forwarded-Host` to `docker-registry.smctr.net:5000` or expose the registry as port 443 on the firewall, such that `docker-registry.smctr.net` is valid.

It is not required to issue a relative URI in the `Location` header in [RFC7231](https://tools.ietf.org/html/rfc7231#section-7.1.2). If you dig into the grammar, you'll see `URI-reference` is either a `URI` or `relative-ref`. We issue a full URI so that clients don't need to calculate the correct location and avoid bugs in http libraries that may resolve references differently. This requires a little more configuration up front on the registry side but avoids bad redirects for 99.9% of configurations.

**Comment by thaJeztah** [comment] 2015-08-15 19:39
@onorua could you try with the suggestions @stevvooe gave? If this resolves your problem, please close the issue, thanks!

**Closed** 2015-08-17 05:56 UTC
Labels: group/distribution, kind/question
