### ISSUE TITLE
changing memory allowed on ubuntu command line

### ISSUE THREAD

**Issue by mtaivalmaa** [docker/docker#31465] opened 2017-03-01 21:49 UTC
Wondering if I can allocate memory when using Ubuntu command line.  

I have done this on my mac via the gui but can't find info regarding command line.

**Comment by thaJeztah** [comment] 2017-03-01 21:57
No, you can't; on Docker for Mac, the daemon runs on a minimal Linux distro, that runs in a hyperKit VM. If you specify the amount of memory, that controls how much memory the VM gets.

On Linux, docker runs directly on the host, so has all memory available that the host has. You can limit the amount of memory that a _container_ is allowed to use (see https://docs.docker.com/engine/admin/resource_constraints/)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-01 21:57 UTC

**Comment by mtaivalmaa** [comment] 2017-03-01 22:07
Awesome, I wanted it to have all of the memory available.. THANK YOU!
