### ISSUE TITLE
Docker cannot find image to pull yet image is already running in other containers

### ISSUE THREAD

**Issue by loe** [docker/docker#10085] opened 2015-01-14 02:46 UTC
I originally thought this was a Kubernetes bug (https://github.com/GoogleCloudPlatform/kubernetes/issues/3301) , but I believe it is with docker. 

Docker claims it cannot pull the image, however running `$ docker pull onehub/embassy:latest` succeeds.

Here is docker daemon's debug log:

```
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/json?all=1"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job containers()"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job containers() = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/json?all=1"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job containers()"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job containers() = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/bb0e015d1bd065d801c64e28ed9ac79d2e420c6e63dbe6fef7e85de8d14ceafc/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job container_inspect(bb0e015d1bd065d801c64e28ed9ac79d2e420c6e63dbe6fef7e85de8d14ceafc)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job container_inspect(bb0e015d1bd065d801c64e28ed9ac79d2e420c6e63dbe6fef7e85de8d14ceafc) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/ea6885abfa7bb05c5b9b6b468a119672e54091b066d9d4cd95db0f0e69b7d923/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job container_inspect(ea6885abfa7bb05c5b9b6b468a119672e54091b066d9d4cd95db0f0e69b7d923)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job container_inspect(ea6885abfa7bb05c5b9b6b468a119672e54091b066d9d4cd95db0f0e69b7d923) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /images/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /images/onehub/embassy:latest/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job image_inspect(onehub/embassy:latest)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job image_inspect(onehub/embassy:latest) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/f20c942e20adc68d5f12801391bd397865858b14290f8adf45bc04882d3e9f94/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job container_inspect(f20c942e20adc68d5f12801391bd397865858b14290f8adf45bc04882d3e9f94)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job container_inspect(f20c942e20adc68d5f12801391bd397865858b14290f8adf45bc04882d3e9f94) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job containers()"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job containers() = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/json?all=1"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job containers()"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job containers() = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/json?all=1"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job containers()"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job containers() = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/json?all=1"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job containers()"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job containers() = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/json?all=1"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job containers()"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job containers() = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/1b3495a20c0163cb7c88d36a689b54a07e45cd081f38f8b822858d39f5f694cb/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job container_inspect(1b3495a20c0163cb7c88d36a689b54a07e45cd081f38f8b822858d39f5f694cb)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job container_inspect(1b3495a20c0163cb7c88d36a689b54a07e45cd081f38f8b822858d39f5f694cb) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/9f19cedd787f2154aa36e91ea2aa9a7e028b2e7169a7ab92fa181513b2417357/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job container_inspect(9f19cedd787f2154aa36e91ea2aa9a7e028b2e7169a7ab92fa181513b2417357)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job container_inspect(9f19cedd787f2154aa36e91ea2aa9a7e028b2e7169a7ab92fa181513b2417357) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/ea6885abfa7bb05c5b9b6b468a119672e54091b066d9d4cd95db0f0e69b7d923/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job container_inspect(ea6885abfa7bb05c5b9b6b468a119672e54091b066d9d4cd95db0f0e69b7d923)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job container_inspect(ea6885abfa7bb05c5b9b6b468a119672e54091b066d9d4cd95db0f0e69b7d923) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/bb0e015d1bd065d801c64e28ed9ac79d2e420c6e63dbe6fef7e85de8d14ceafc/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job container_inspect(bb0e015d1bd065d801c64e28ed9ac79d2e420c6e63dbe6fef7e85de8d14ceafc)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job container_inspect(bb0e015d1bd065d801c64e28ed9ac79d2e420c6e63dbe6fef7e85de8d14ceafc) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/a05447e3eed3b576e7f2ef71872122613f2ad5158f548000828ed8856214143d/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job container_inspect(a05447e3eed3b576e7f2ef71872122613f2ad5158f548000828ed8856214143d)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job container_inspect(a05447e3eed3b576e7f2ef71872122613f2ad5158f548000828ed8856214143d) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/8441bcd13ca39b3ff9eda67fc4bfed16bf896835d6749a3907eb9459e1f13f04/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job container_inspect(8441bcd13ca39b3ff9eda67fc4bfed16bf896835d6749a3907eb9459e1f13f04)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job container_inspect(8441bcd13ca39b3ff9eda67fc4bfed16bf896835d6749a3907eb9459e1f13f04) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /images/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /images/onehub/embassy:latest/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job image_inspect(onehub/embassy:latest)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job image_inspect(onehub/embassy:latest) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/f20c942e20adc68d5f12801391bd397865858b14290f8adf45bc04882d3e9f94/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job container_inspect(f20c942e20adc68d5f12801391bd397865858b14290f8adf45bc04882d3e9f94)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job container_inspect(f20c942e20adc68d5f12801391bd397865858b14290f8adf45bc04882d3e9f94) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /containers/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /containers/json?all=1"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job containers()"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job containers() = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling GET /images/{name:.*}/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="GET /images/onehub/embassy:latest/json"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job image_inspect(onehub/embassy:latest)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job image_inspect(onehub/embassy:latest) = OK (0)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="Calling POST /images/create"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="POST /images/create?fromImage=onehub%2Fembassy&tag=latest"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="+job pull(onehub/embassy, latest)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="[registry] Calling GET https://index.docker.io/v1/repositories/onehub/embassy/images"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="https://index.docker.io/v1/repositories/onehub/embassy/images -- HEADERS: map[User-Agent:[docker/1.4.1 go/go1.3.3 git-commit/5bc2ff8-dirty kernel/3.18.1 os/linux arch/amd64]]"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="debug" msg="hostDir: /etc/docker/certs.d/index.docker.io"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: Error: image onehub/embassy:latest not found
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal docker[30940]: time="2015-01-14T00:59:14Z" level="info" msg="-job pull(onehub/embassy, latest) = ERR (1)"
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal kubelet[28612]: E0114 00:59:14.737280   28612 kubelet.go:914] Failed to pull image "onehub/embassy:latest": Error: image onehub/embassy:latest not found; skipping pod "embassy-471.default.etcd" container "embassy".
Jan 14 00:59:14 ip-10-3-0-185.ec2.internal kubelet[28612]: I0114 00:59:14.737318   28612 event.go:92] Event(api.ObjectReference{Kind:"BoundPod", Namespace:"default", Name:"embassy-471", UID:"050bcc19-9b84-11e4-8fa6-1248359f694e", APIVersion:"v1beta1", ResourceVersion:"", FieldPath:"spec.containers{embassy}"}): status: 'failed', reason: 'failed' Failed to pull image "onehub/embassy:latest"
```

Docker is 1.4.1 on CoreOS:
```
ore@ip-10-3-0-185 ~ $ docker --version
Docker version 1.4.1, build 5bc2ff8-dirty
```

**Comment by loe** [comment] 2015-01-14 02:48
The most interesting note is that this only happens for this specific job, I have 10s of containers running on the same host with the same image, I just cannot start my job "embassy-471". If I change the requested image to be onehub/embassy with no qualifying tag, it will start and run with no problem, but then I must manually pull on each kubernetes node when I rebuild my container, which is undesirable.

**Comment by tiborvass** [comment] 2015-01-14 18:14
@loe Would you be able to narrow down the problem into a reproducible case? That would help a lot, because I'm not sure how to debug your issue otherwise.

**Comment by loe** [comment] 2015-01-14 18:18
@tiborvass That is really the issue. I don't know how to narrow it down further. I would be happy to work with you and get you on my host that has the issue. For this job it outputs these same logs every 10 second (kubernetes loop time).

**Comment by tiborvass** [comment] 2015-01-14 19:34
After trying to debug with @loe, we couldn't fully reproduce.

I'm conservatively closing this issue for now, but @loe feel free to comment here if you have any news, we'll (not so) gladly reopen :)

**Closed by tiborvass** 2015-01-14 19:34 UTC
