### ISSUE TITLE
Disabling user namespace for a container ???

### ISSUE THREAD

**Issue by SergeyYakubov** [docker/docker#22223] opened 2016-04-21 10:04 UTC
Do I understand correct that one can now disable user namespace just by adding --userns=host to a run/exec command?

Does not it breaks the whole idea of having user namespaces? We were very happy to see them in version 1.10 where we could allow user bring their containers to our system in run them without worrying that they can get root rights.

Is there a way to force user namespaces and igonre --userns=host ???

**Comment by justincormack** [comment] 2016-04-21 11:31
There are a whole lot of ways in which users can elevate privileges through `docker run`, eg by using `--privileged`. You can stop this by either not directly providing access to the daemon in production, and using scripts, or by using an auth plugin (see https://docs.docker.com/engine/extend/plugins_authorization/) to disallow some options.

**Comment by SergeyYakubov** [comment] 2016-04-21 11:44
--privileged was not allowed when user namespaces were activated. I find it really strange idea to have --userns=host option that cancels everything.

I will try look at auth plugin, thanks, but it just worked before out of the box :(

**Comment by thaJeztah** [comment] 2016-04-21 11:51
User namespaces are for making the *containers* more secure, but not for limiting capabilities for users that have access to the Docker remote API. The general security measures still apply when enabling user namespaces https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface.

I'm going to close this issue, because this is not a bug, and user namespaces are not designed to make the remote API more secure.

**Closed by thaJeztah** 2016-04-21 11:51 UTC

**Comment by agilmor** [comment] 2016-06-20 14:34
I agree with @SergeyYakubov, but I also agree that this is a matter of preferences or scenarios...
(although I don't see any one? ;-)

Maybe a more specific options to the daemon could help?
```
docker daemon --userns-remap=$uid
```
and
```
docker daemon --userns-remap-forced=$uid
```

The second option should not allow `--privileged` nor `--userns=host`.
Does it have sense?

**Comment by niklas88** [comment] 2018-01-29 09:55
I had the same concern and felt that the existing authorization plugins were way overkill and overcomplicated for my simple use case. I thus created a very simple authorization [plugin](https://github.com/niklas88/docker-no-trivial-root) that does nothing except disallowing the obviously root-gaining options. As stated on the README this is highly experimental and a super simple quick hack so use with caution. Still I believe it at least doesn't make docker less secure than just enabling user namespaces without disallowing these options.

**Comment by SergeyYakubov** [comment] 2018-01-29 10:04
I solved this problem for us some time ago using authorization plugin. It is a bit more sophisticated as the one from @niklas88  in a way that it makes sure commands within the container can only be executed on behalf of the user who started it. 
https://sergeyyakubov.github.io/hpc/docker/2017/03/13/docker-noroot.html
