### ISSUE TITLE
docker kill/stop does not work after exec process

### ISSUE THREAD

**Issue by anandkumarpatel** [docker/docker#10059] opened 2015-01-13 02:43 UTC
docker stop/kill returns ` Cannot kill container`
if there is a running docker exec process. after running docker stop/kill the processes do exit (they do not show up in `ps aux`) however they remain in the `docker ps` 

repro script bug.sh:
```
#!/bin/bash
CONTAINER=`docker run -d ubuntu sleep 1000`
docker exec -d $CONTAINER sleep 1000
sleep 1
docker kill $CONTAINER
```
docker debug logs
```
DEBU[0012] Calling POST /containers/create
INFO[0012] POST /v1.16/containers/create
INFO[0012] +job create()
INFO[0012] +job log(create, 3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c, ubuntu:latest)
INFO[0012] -job log(create, 3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c, ubuntu:latest) = OK (0)
INFO[0012] -job create() = OK (0)
DEBU[0012] Calling POST /containers/{name:.*}/start
INFO[0012] POST /v1.16/containers/3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c/start
INFO[0012] +job start(3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c)
INFO[0012] +job allocate_interface(3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c)
INFO[0012] -job allocate_interface(3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c) = OK (0)
INFO[0012] +job log(start, 3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c, ubuntu:latest)
INFO[0012] -job log(start, 3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c, ubuntu:latest) = OK (0)
INFO[0012] -job start(3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c) = OK (0)
DEBU[0012] Calling POST /containers/{name:.*}/exec
INFO[0012] POST /v1.16/containers/3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c/exec
INFO[0012] +job execCreate(3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c)
INFO[0012] -job execCreate(3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c) = OK (0)
DEBU[0012] Calling POST /exec/{name:.*}/start
INFO[0012] POST /v1.16/exec/3b4774b8797c83639cfeebc72d0f2243d897b0cea3ab9fdcf557071d8bb9f858/start
INFO[0012] +job execStart(3b4774b8797c83639cfeebc72d0f2243d897b0cea3ab9fdcf557071d8bb9f858)
DEBU[0012] starting exec command 3b4774b8797c83639cfeebc72d0f2243d897b0cea3ab9fdcf557071d8bb9f858 in container 3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c
DEBU[0012] attach: all jobs completed successfully
INFO[0012] -job execStart(3b4774b8797c83639cfeebc72d0f2243d897b0cea3ab9fdcf557071d8bb9f858) = OK (0)
DEBU[0013] Calling POST /containers/{name:.*}/kill
INFO[0013] POST /v1.16/containers/3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c/kill?signal=KILL
INFO[0013] +job kill(3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c, KILL)
DEBU[0013] Sending 9 to 3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c
DEBU[0013] Exec task in container 3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c exited with code -1
INFO[0023] Container 3f9ebecbafc9 failed to exit within 10 seconds of kill - trying direct SIGKILL
Cannot kill container 3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c: no such process
INFO[0023] -job kill(3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c, KILL) = ERR (1)
ERRO[0023] Handler for POST /containers/{name:.*}/kill returned error: Cannot kill container 3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c: no such process
ERRO[0023] HTTP Error: statusCode=404 Cannot kill container 3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c: no such process
```
docker client logs
```
$ ./bug.sh
Error response from daemon: Cannot kill container 3f9ebecbafc98ad2526001abf8439a9caf8df4d569d71b10a17290514650102c: no such process
FATA[0010] Error: failed to kill one or more containers
```
ps aux
```
$ ps aux | grep sleep
root     14600  0.0  0.0  10464   920 pts/1    S+   02:41   0:00 grep --color=auto sleep
```
my system info
```
$ docker -D info
Containers: 697
Images: 1753
Storage Driver: aufs
 Root Dir: /docker/aufs
 Dirs: 3147
Execution Driver: native-0.2
Kernel Version: 3.13.0-29-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 32
Total Memory: 58.81 GiB
Name: docker
ID: HAXE:AABL:XLN7:SFAY:AAAA:AFAD:BAQC:ANF3:ASD4:D2AX:CKA3:IFAK
Debug mode (server): true
Debug mode (client): true
Fds: 16
Goroutines: 15
EventsListeners: 1
Init Path: /usr/bin/docker
Docker Root Dir: /docker
WARNING: No swap limit support

$ uname -a
Linux docker 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by LK4D4** [comment] 2015-01-13 04:24
@anandkumarpatel duplicate of #9699 
Thanks for report!

**Closed by LK4D4** 2015-01-13 04:24 UTC
