### ISSUE TITLE
USER namespaces aren't enabled in the kernel

### ISSUE THREAD

**Issue by beatscode** [docker/docker#22651] opened 2016-05-11 08:20 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 8
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-202:65-525626-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 4.396 GB
 Data Space Total: 107.4 GB
 Data Space Available: 7.88 GB
 Metadata Space Used: 7.733 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/100000.100000/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/100000.100000/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.389 GiB
Name: ABCV
ID: K3GB:UTQY:3E2D:KTZ4:QQ4W:VLHT:55ZQ:GPG5:GGQR:6ZZF:K4VD:DKRH
Docker Root Dir: /var/lib/docker/100000.100000
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
centos 7, AWS
````
uname -r : 3.10.0-229.14.1.el7.x86_64
````

**Steps to reproduce the issue:**
1. docker run hello-world
2.
3.

**Describe the results you received:**
````
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
4276590986f6: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:4f32210e234b4ad5cac92efacc0a3d602b02476c754f13d517e1ada048e5a8ba
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: USER namespaces aren't enabled in the kernel".
````
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
Running  grubby --info=/boot/vmlinuz-3.10.0-229.14.1.el7.x86_64 yields the following
````
index=0
kernel=/boot/vmlinuz-3.10.0-229.14.1.el7.x86_64
args="ro crashkernel=auto console=tty0 console=ttyS0,115200 net.ifnames=0 user_namespace.enable=1"
root=/dev/mapper/VolGroup00-lv_root
initrd=/boot/initramfs-3.10.0-229.14.1.el7.x86_64.img
title=CentOS Linux 7 (Core), with Linux 3.10.0-229.14.1.el7.x86_64
````

If I remove the --userns-remap directive on the daemon, docker runs as expected. 

On another aws(centos 7) machine I am successfully running docker with remap and user.namespaces enabled.

**Comment by justincormack** [comment] 2016-05-11 08:39
Hi, can you run the diagnostic script `https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh` it may give some more information about your setup. I see you have the `user_namespace.enable=1` set, but have you rebooted since? What does `cat /proc/cmdline` say?

**Comment by beatscode** [comment] 2016-05-11 11:10
Here's the check-config.sh logs

````
./check-config.sh
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-3.10.0-229.14.1.el7.x86_64 ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled
- CONFIG_NETPRIO_CGROUP: enabled (as module)
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled (as module)
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing
````

````
cat /proc/cmdline

BOOT_IMAGE=/vmlinuz-3.10.0-229.14.1.el7.x86_64 root=/dev/mapper/VolGroup00-lv_root ro crashkernel=auto console=tty0 console=ttyS0,115200 net.ifnames=0 user_namespace.enable=1
````

**Comment by justincormack** [comment] 2016-05-11 14:47
That is very odd, it looks fine. Can you spot any differences with the ones that work?

**Comment by beatscode** [comment] 2016-05-11 15:12
check-config diff

<img width="1429" alt="1ab69fe0-a2cf-4d33-aa5f-ac3a346bcf2d" src="https://cloud.githubusercontent.com/assets/1777648/15185433/25d1c758-1767-11e6-970e-47e1d9bd02de.png">

````
cat /proc/cmdline

BOOT_IMAGE=/boot/vmlinuz-3.10.0-327.13.1.el7.x86_64 root=UUID=ef6ba050-6cdc-416a-9380-c14304d0d206 ro console=tty0 console=ttyS0,115200n8 crashkernel=auto console=ttyS0,115200 LANG=en_US.UTF-8 user_namespace.enable=1
````

diff
<img width="1425" alt="97e5586e-9e10-44cd-8aba-c72c9860c5be" src="https://cloud.githubusercontent.com/assets/1777648/15185981/34cb3440-1769-11e6-9dfe-87b5514c9523.png">



Problem Server A is a managed AWS service 
Server B is a regular ec2 instance that I created using a vanilla Centos 7 ami.

I've since told the vendor to upgrade the kernel to the same as Server B. Hopefully that makes a difference.

**Comment by HackToday** [comment] 2016-05-12 08:31
did it have `/proc/self/ns/user` ?

**Comment by beatscode** [comment] 2016-05-12 15:40
On good server there is a link to Im not sure what
![96de26f4-c1f2-4c41-825b-5eac5afdfddf](https://cloud.githubusercontent.com/assets/1777648/15220655/378b7820-1836-11e6-9ca6-83403441e35e.png)

On the problem server there is no file at that location.

**Comment by justincormack** [comment] 2016-05-12 15:43
The top one is the correct output. If that file does not exist, the user namespaces are not enabled.

**Comment by thaJeztah** [comment] 2016-05-12 17:15
Looks like a configuration issue, not a bug, so I'll close this one, but feel free to comment here after i closed

**Closed by thaJeztah** 2016-05-12 17:15 UTC
Labels: status/more-info-needed

**Comment by hesamaseh** [comment] 2016-11-15 21:58
I had the same issue : 
I upgraded the kernel using yum upgrade and restarted the machine and it worked. It should be minimum 7.2 on redhat
