### ISSUE TITLE
Goroutine stacktraces after sending SIGQUIT to container

### ISSUE THREAD

**Issue by dchusovitin** [docker/docker#23170] opened 2016-06-01 17:22 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 33
 Running: 4
 Paused: 0
 Stopped: 29
Images: 79
Server Version: 1.11.1
Storage Driver: btrfs
 Build Version: Btrfs v4.5.1
 Library Version: 101
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.4-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.776 GiB
Name: nx-01
ID: PE22:UN2X:TFEO:76N2:HSI3:C6PW:6Y36:IUMI:NRKR:SMYH:JDR7:2SSG
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: dchusovitin
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine and server on DigitalOcean

**Steps to reproduce the issue:**
1. Run docker run -t busybox (any container with only "-t" flag)
2. Press CTRL + \

**Output:**
```
/ # ^\SIGQUIT: quit
PC=0x474443 m=2

goroutine 0 [idle]:
runtime.futex(0x22297f0, 0x0, 0x7f3575db5d38, 0x0, 0x0, 0x47424c, 0x3c, 0x0, 0x42247b, 0x22297f0, ...)
	/usr/lib/go/src/runtime/sys_linux_amd64.s:307 +0x23
runtime.futexsleep(0x22297f0, 0x0, 0xdf8475800)
	/usr/lib/go/src/runtime/os1_linux.go:57 +0xf0
runtime.notetsleep_internal(0x22297f0, 0xdf8475800, 0xc820000900)
	/usr/lib/go/src/runtime/lock_futex.go:174 +0x12b
runtime.notetsleep(0x22297f0, 0xdf8475800, 0x16af9e968801)
	/usr/lib/go/src/runtime/lock_futex.go:194 +0x6b
runtime.sysmon()
	/usr/lib/go/src/runtime/proc.go:3480 +0x487
runtime.mstart1()
	/usr/lib/go/src/runtime/proc.go:1098 +0xec
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1068 +0x72

goroutine 1 [chan receive]:
github.com/docker/docker/api/client.(*DockerCli).CmdRun(0xc82030d080, 0xc82000a220, 0x2, 0x2, 0x0, 0x0)
	/build/docker/src/docker/.gopath/src/github.com/docker/docker/api/client/run.go:243 +0x1042
reflect.callMethod(0xc8203c1e30, 0xc8201c1c28)
	/usr/lib/go/src/reflect/value.go:631 +0x1fc
reflect.methodValueCall(0xc82000a220, 0x2, 0x2, 0x1, 0xc8203c1e30, 0x0, 0x0, 0xc8203c1e30, 0x0, 0x47a3c4, ...)
	/usr/lib/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc8203c1a70, 0xc82000a210, 0x3, 0x3, 0x0, 0x0)
	/build/docker/src/docker/.gopath/src/github.com/docker/docker/cli/cli.go:89 +0x384
main.main()
	/build/docker/src/docker/docker/docker.go:63 +0x435

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 35 [chan receive]:
github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection(0xc82030d080, 0x1, 0x0, 0x0, 0x7f3577b14358, 0xc820028010, 0x7f3577b14358, 0xc820028010, 0x7f3577ad9418, 0xc82043a008, ...)
	/build/docker/src/docker/.gopath/src/github.com/docker/docker/api/client/hijack.go:48 +0x379
github.com/docker/docker/api/client.(*DockerCli).CmdRun.func2(0x0, 0x0)
	/build/docker/src/docker/.gopath/src/github.com/docker/docker/api/client/run.go:218 +0xd3
github.com/docker/docker/pkg/promise.Go.func1(0xc82042c2a0, 0xc82042c240)
	/build/docker/src/docker/.gopath/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x1d
created by github.com/docker/docker/pkg/promise.Go
	/build/docker/src/docker/.gopath/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x5d

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/usr/lib/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 20 [IO wait]:
net.runtime_pollWait(0x7f3577ada328, 0x72, 0xc82041a000)
	/usr/lib/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203d7cd0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203d7cd0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203d7c70, 0xc82041a000, 0x1000, 0x1000, 0x0, 0x7f3577b10050, 0xc82000e1d0)
	/usr/lib/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820308720, 0xc82041a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f3577adb210, 0xc820308720, 0xc8203ddf48, 0xc82041a000, 0x1000, 0x1000, 0xc820315e60, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc8203edaa0, 0xc82041a000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820315a40)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820315a40, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8203ddee0)
	/usr/lib/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:857 +0x10a6

goroutine 21 [select]:
net/http.(*persistConn).writeLoop(0xc8203ddee0)
	/usr/lib/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:858 +0x10cb

goroutine 38 [select, locked to thread]:
runtime.gopark(0x1a9ea90, 0xc820027728, 0x17671c0, 0x6, 0x1018, 0x2)
	/usr/lib/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820027728, 0x0, 0x18)
	/usr/lib/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820027728)
	/usr/lib/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/lib/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [IO wait]:
net.runtime_pollWait(0x7f3577ada268, 0x72, 0xc820448000)
	/usr/lib/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82042a290, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82042a290, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82042a230, 0xc820448000, 0x1000, 0x1000, 0x0, 0x7f3577b10050, 0xc82000e1d0)
	/usr/lib/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82043a008, 0xc820448000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc82042c1e0)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).WriteTo(0xc82042c1e0, 0x7f3577b14358, 0xc820028010, 0xc, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:481 +0x2e0
io.copyBuffer(0x7f3577b14358, 0xc820028010, 0x7f3577a90000, 0xc82042c1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:370 +0xd0
io.Copy(0x7f3577b14358, 0xc820028010, 0x7f3577a90000, 0xc82042c1e0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:350 +0x64
github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection.func1(0xc820208c01, 0x7f3577b14358, 0xc820028010, 0xc8202d2df0, 0xc8202f4320, 0x7f3577b14358, 0xc820028010, 0xc820208c60)
	/build/docker/src/docker/.gopath/src/github.com/docker/docker/api/client/hijack.go:18 +0x87
created by github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection
	/build/docker/src/docker/.gopath/src/github.com/docker/docker/api/client/hijack.go:24 +0x51e

goroutine 39 [chan receive]:
github.com/docker/docker/api/client.(*DockerCli).monitorTtySize.func2(0xc82042c6c0, 0xc82030d080, 0xc820426140, 0x40, 0xc8201c1700)
	/build/docker/src/docker/.gopath/src/github.com/docker/docker/api/client/utils.go:140 +0x4d
created by github.com/docker/docker/api/client.(*DockerCli).monitorTtySize
	/build/docker/src/docker/.gopath/src/github.com/docker/docker/api/client/utils.go:143 +0x1bf

rax    0xfffffffffffffffc
rbx    0x7f3575db5d38
rcx    0x474443
rdx    0x0
rdi    0x22297f0
rsi    0x0
rbp    0x0
rsp    0x7f3575db5d00
r8     0x0
r9     0x0
r10    0x7f3575db5d38
r11    0x246
r12    0x0
r13    0x7ffe43461abf
r14    0x0
r15    0x7f3577c7a000
rip    0x474443
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by thaJeztah** [comment] 2016-06-01 20:52
Confirmed, also reproducible on docker 1.11.2-rc1, and master (https://github.com/docker/docker/commit/cbccb19212c186e5baf5e09b130a7fcc1d58df4c)

**Comment by coolljt0725** [comment] 2016-06-02 09:30
@thaJeztah   this should not be a bug?  by default, `SIGQUIT` will causes the process to terminate and dump core, this is should be normal behavior. The `SIGQUIT` for go process will generate a complete stack dump of all running goroutines
correct me if I'm wrong :-)

**Comment by thaJeztah** [comment] 2016-06-02 10:30
@coolljt0725 oh! you may be right there; there's no `stdin` for the process in the container, so `SIGQUIT` is sent to the docker *client*, not the process in the container :blush:

This is not a bug 👍

**Comment by thaJeztah** [comment] 2016-06-02 10:31
closing, per the discussion above, but @dchusovitin feel free to comment after I closed, or if you think this shouldn't be closed

**Closed by thaJeztah** 2016-06-02 10:31 UTC
Labels: version/1.11
