### ISSUE TITLE
Docker service scale not utilizing credential helper or registry auth

### ISSUE THREAD

**Issue by jaredm4** [docker/docker#30982] opened 2017-02-13 18:51 UTC
**Description**

Scaling service with `docker service scale` does not support credential helper nor `--with-registry-auth` param. For my purposes, I used [Amazon ECR Credential Helper](https://github.com/awslabs/amazon-ecr-credential-helper).

**Steps to reproduce the issue:**
Steps assume you have a private registry with an image in it, and a Swarm with 1 manager and 1 worker. In my case, I have my images in ECR, and my instances have read only access to my ECR repo. Also note that the AWS ECR Credential Helper has a 12 hour expiry window, making this difficult to test since Docker caches authentication tokens. I didn't find a way to easily clear that cache.
It may help to ensure you have services running on your Manager node so that the Swarm will favor the worker when you launch the test service. I had the Swarm Visualizer and Redis running on the Manager.

1. Create service with 1 replica. `docker service create --name test --with-registry-auth url.to.private.repo:latest` Ensure that it loaded on the Worker and not the Manager.
2. You can verify that `service create` used the credential helper by looking at the Manager's ~/.erc/log/* files.
3. Wait for the ECR token to expire (12 hours), or the equivalent for your private registry of choice.
4. Scale up your service with `docker service scale test=5` I chose 5 to ensure the Manager would get at least 1 copy.
5. It should fail to launch any on Manager, eventually running all 5 on the Worker.

**Describe the results you received:**
All 5 containers run on the Worker, none on the Manager.
`docker service ps test --no-trunc` returns results similar to the following:
```
2xr04l2hj3666vtrkry7pf6wb   \_ test.2  url.to.private.repo:latest@sha256:re4c78df5997fc5e3e142b241e934e0f8f28c3850b10771c99e23b178b07c1dd  swarm1  Shutdown       Rejected 6 minutes ago    "No such image: url.to.private.repo:latest@sha256:re4c78df5997fc5e3e142b241e934e0f8f28c3850b10771c99e23b178b07c1dd"
```
You can verify that the Manager did *not* use the credential helper in the ~/.ecr/logs/* files.

**Describe the results you expected:**
Some of the containers to spawn on the Manager.
Manager to refresh credentials after verifying the cached version no longer works.
Docker to support `--with-registry-auth` on `docker service scale` so those refreshed credentials can be supplied to Workers. Or, `--with-registry-auth` should be saved as a part of the service definition so calling `service scale` or `service update` do not require it every time (if it is not already, I didn't dig too deep on this to determine if that is saved between updates/scales).

**Additional information you deem important (e.g. issue happens only occasionally):**
`docker service update --with-registry-auth --replicas 5 test` is a work-around, though I don't like how it rebuilds currently running containers. This could interfere with current processes/connections.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 43
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 2ipc3hqwq4zmhjjnqijc8lzpw
 Is Manager: true
 ClusterID: 36ljokxmcbzkb7lv8fs7ptzlv
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.10.151
 Manager Addresses:
  192.168.10.151:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.859 GiB
Name: swarm1-hq
ID: UPFD:CEXD:PKXZ:EYKM:4LLK:J4JE:7BZD:BZXR:FXHN:TVU3:B7EA:RKSW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
In this exact setup, I was using servers NOT in EC2, but had credentials stored in ~/.aws that have read-only access to the ECR repos. I expect the same results if the instances were in EC2 and using IAM Roles.
Docker was installed on Ubuntu using Docker's Ubuntu install instructions.

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
```

**Comment by thaJeztah** [comment] 2017-02-14 06:40
this is a duplicate of https://github.com/docker/docker/issues/24894 (also see https://github.com/docker/docker/pull/24897).

Using `--with-registry-auth` does not just _send_ the authentication information, but also updates the information in the services definition; since updating the definition is a separate action from only updating the number of replicas (which is what `scale` does), it was decided to not add this flag to `docker service scale`

> Or, --with-registry-auth should be saved as a part of the service definition so calling service scale or service update do not require it every time

`--with-registry-auth` sends, and stores the authentication information in the service definition. We don't want docker to _automatically_ send that information if the service was originally provided authentication, but keep it as a _deliberate_ action.

> docker service update --with-registry-auth --replicas 5 test is a work-around, though I don't like how it rebuilds currently running containers. This could interfere with current 

Hm, I don't think `docker service scale` or `docker service update` should make a difference here; `docker service scale` is basically just a shorthand for `docker service update`

Since this is a duplicate of https://github.com/docker/docker/pull/24897, which was rejected, I'll close close this issue, but I hope the information above helps understanding the reasons. Also feel free to continue the conversation after I closed 👍

**Closed by thaJeztah** 2017-02-14 06:40 UTC
Labels: area/swarm

**Comment by jaredm4** [comment] 2017-02-14 19:35
@thaJeztah That makes sense -- the `--with-registry-auth` on service create/update adds that as part of the definition and thus `docker service scale` does not need it. However that part of my original bug ticket was minor. The bug primarily revolves around this issue:

1. `docker service scale` does not re-use credential helpers in the event that the auth token has expired (it just states "No such image" on nodes that don't already have a copy of the image downloaded).
2. `docker service update --replicas X` (sans `--with-registry-auth`) has the same behavior as `scale`, as you mentioned, and still loads all replicas on nodes that already have the image downloaded (this isn't good). There is no record of the credential helper being used.
```
# On the manager:
~/.ecr/log$ docker service update --replicas 5 reporting-test
reporting-test
# NOTE that the credential helper didn't write any logs for Feb 14 (today)
~/.ecr/log$ ll
total 20
drwxrw-r-x 2 mixpo mixpo 4096 Feb 13 09:55 ./
drwxrw-r-x 3 mixpo mixpo 4096 Feb 13 09:55 ../
-rw-rw-r-- 1 mixpo mixpo  570 Feb 10 09:23 ecr-login.log.2017-02-10-09
-rw-rw-r-- 1 mixpo mixpo  415 Feb 10 10:12 ecr-login.log.2017-02-10-10
-rw-rw-r-- 1 mixpo mixpo  736 Feb 13 09:59 ecr-login.log.2017-02-13-09
~/.ecr/log$ docker ps
CONTAINER ID        IMAGE                                                                           COMMAND                  CREATED             STATUS              PORTS               NAMES
b247a3d53735        manomarks/visualizer:latest                                                     "npm start"              4 days ago          Up 4 days           8080/tcp            viz.1.zvjrjs8hsxdg3ehqofkhi23je
853308a8c27e        redis@sha256:afa4b429ef3ee08c8b198e50d684c5da0ffa43ae58631f61b08829bd6df3c500   "docker-entrypoint..."   4 days ago          Up 4 days           6379/tcp            redis.1.3tpd4gezu8dnqsfnukr8vieo3

# On the worker node:
mixpo@swarm2-hq:~$ docker ps
CONTAINER ID        IMAGE                                                                                                                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
e57b7991433c        redacted-test@sha256:redacted   "sh -c 'ln -s /run..."   4 seconds ago       Up 3 seconds                            reporting-test.1.mw4932m6eqff6wzcnwipdztci
049c4c00e371        redacted-test@sha256:redacted   "sh -c 'ln -s /run..."   4 seconds ago       Up 3 seconds                            reporting-test.3.rvhhq02scdtgm6bnwzvygih22
b1d2c0c79fc6        redacted-test@sha256:redacted   "sh -c 'ln -s /run..."   4 seconds ago       Up 3 seconds                            reporting-test.2.dp1wrzpc4qwc5rj5gzoljfwdm
36f8e307d87f        redacted-test@sha256:redacted   "sh -c 'ln -s /run..."   4 seconds ago       Up 3 seconds                            reporting-test.5.trp8l26x6htyp8q5ypdyzh189
522db2a9bc35        redacted-test@sha256:redacted   "sh -c 'ln -s /run..."   4 seconds ago       Up 2 seconds                            reporting-test.4.673lms7rag5jg1hre19zu2fz7

```
3. I then also ran `docker service update --with-registry-auth --replicas 6 reporting-test`, now the credential helper was touched, but it still ran all 6 containers on the worker node instead of balancing them with the Manager.
```
~/.ecr/log$ docker service update --with-registry-auth --replicas 6 reporting-test
reporting-test
~/.ecr/log$ ll
total 20
drwxrw-r-x 2 mixpo mixpo 4096 Feb 14 11:17 ./
drwxrw-r-x 3 mixpo mixpo 4096 Feb 14 11:17 ../
-rw-rw-r-- 1 mixpo mixpo  415 Feb 10 10:12 ecr-login.log.2017-02-10-10
-rw-rw-r-- 1 mixpo mixpo  736 Feb 13 09:59 ecr-login.log.2017-02-13-09
-rw-rw-r-- 1 mixpo mixpo  891 Feb 14 11:17 ecr-login.log.2017-02-14-11
~/.ecr/log$ docker service ps reporting-test
ID            NAME                  IMAGE                                                          NODE       DESIRED STATE  CURRENT STATE            ERROR  PORTS
mw4932m6eqff  reporting-test.1      redacted/reporting-test:7  swarm2-hq  Running        Running 15 minutes ago
dp1wrzpc4qwc  reporting-test.2      redacted/reporting-test:7  swarm2-hq  Running        Running 15 minutes ago
rvhhq02scdtg  reporting-test.3      redacted/reporting-test:7  swarm2-hq  Running        Running 15 minutes ago
673lms7rag5j  reporting-test.4      redacted/reporting-test:7  swarm2-hq  Running        Running 15 minutes ago
l17ud1i5m3qy   \_ reporting-test.4  redacted/reporting-test:7  swarm2-hq  Shutdown       Shutdown 15 minutes ago
trp8l26x6hty  reporting-test.5      redacted/reporting-test:7  swarm2-hq  Running        Running 15 minutes ago
gf42fz32n8ip  reporting-test.6      redacted/reporting-test:7  swarm2-hq  Running        Running 14 minutes ago
# The Manager still just has the 2 single container services running on it.
```

So my take away is that Swarm does not refresh credentials unless you pass --with-registry-auth (even if it was already defined in service creation), and that this may also cause Swarm to imbalance the running replicas, though that could be unrelated.

**Comment by jaredm4** [comment] 2017-02-15 23:22
I went ahead and opened new Issue https://github.com/docker/docker/issues/31063 that focuses primarily on the lack of credential helper usage.
