### ISSUE TITLE
Socket connect hang in 1.7.0

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#14037] opened 2015-06-19 08:37 UTC
This is extremely hard to reproduce.  While running validation tests for Rancher they randomly fail on Docker 1.7.  The behaviour is always the same in that we have a `curl` process that is hung on connect.  After a certain amount of time the connect times out and retries and then works.  It's quite random and I have not been able to narrow things down to a small failing test case.

@mavenugo @mrjana Can you think of anything that could possible be different between 1.6 and 1.7 in terms of network settings?  bridge options, iptables, MTU, etc?  Just looking for something I can go off of to start troubleshoot more.  Thanks.

**Comment by ibuildthecloud** [comment] 2015-06-19 09:01
My laptop is about to die and I have no power cord... but I just notice that in 1.7 the tx_queue_len is set to 1000 for the veth where as 1.6 is 0.  When I get power again I will test this theory.

**Comment by unclejack** [comment] 2015-06-19 09:49
@ibuildthecloud I'm seeing the veth in the container use a tx_queue_len of 0, but the other veth on the host is at 1000. 

On Docker 1.6, I was seeing both with a tx_queue_len of 0. This does indeed need to be fixed.

**Comment by thaJeztah** [comment] 2015-06-19 10:43
Tentatively added this to the 1.7.1 milestone

**Comment by ibuildthecloud** [comment] 2015-06-19 15:18
I'm still without a computer, but in a couple hours I should be able to test if tx_queue_len is the root of my issue.  If it is I really would suggest we do a 1.7.1 release today/tomorrow.  As it stands today my application is unstable on 1.7.

**Comment by unclejack** [comment] 2015-06-19 15:31
@ibuildthecloud This is probably not the underlying cause of the problem you're running into. It might be another problem entirely. This is still a regression requiring a fix, so there might actually be at least two problems related to this issue.

**Comment by ibuildthecloud** [comment] 2015-06-19 19:19
@unclejack You're right, this didn't fix my issue.  :disappointed:  Still debugging

**Comment by ibuildthecloud** [comment] 2015-06-19 19:33
@thaJeztah Okay, I reproduced my root issue on 1.6.  This means this bug should be fixed in 1.7 but is not really high priority from what I can see.

**Comment by thaJeztah** [comment] 2015-06-19 21:24
@ibuildthecloud thanks for adding that

@jfrazelle do you want to keep this on the 1.7.1 milestone, or move it to 1.8?

**Comment by unclejack** [comment] 2015-06-20 11:14
@ibuildthecloud These two problems should be fixed in 1.7.1 as they're regressions.

ping @mavenugo @mrjana

**Comment by jamshid** [comment] 2015-06-23 20:31
So glad I found this issue because I think I'm hitting the same difficult-to-pin-down problem described in @ibuildthecloud's initial comment. Sometimes (in my case after sending a SIGHUP to a container running dnsmasq, but I think I'm also seeing it when a container is started) there is a small window in which attempts to connect to a container from other containers fail. 

This problem started with docker 1.7.0, I wasn't seeing it on docker 1.6.2. What can I do to test if the problem is one of the two(?) problems mentioned in this issue?

**Comment by mrjana** [comment] 2015-06-26 22:57
@unclejack as per @ibuildthecloud the socket hang issue is seen even in 1.6. So why do you think this is a regression in 1.7? I do agree that the txqlen problem is a regression in 1.7 and hence it should be fixed in 1.7.1

**Comment by unclejack** [comment] 2015-06-28 11:10
@mrjana I was just saying it's a regression because @ibuildthecloud didn't run into it with older releases.

**Comment by calavera** [comment] 2015-07-01 17:09
This should be fixed on master and was merged into the release branch #/14264. Closing.

**Closed by calavera** 2015-07-01 17:09 UTC
Labels: /system/networking
