### ISSUE TITLE
Build docker without docker (i.e., on ARM and other architectures)

### ISSUE THREAD

**Issue by rcarmo** [docker/docker#14056] opened 2015-06-19 23:36 UTC
For those of us trying to use Docker on other architectures (like ARM), it would be excellent if Docker could be built with nothing more than a working Go setup - i.e., without a previous version of it, and without trying to pull anything from the Internet.

(This becomes even more aggravating when you manage to use a legacy Docker binary and the build process then tries to download a x64 binary image from the Docker hub...)

**Comment by tianon** [comment] 2015-06-19 23:38
You want to check out
https://github.com/docker/docker/blob/master/project/PACKAGERS.md :+1:

**Comment by rcarmo** [comment] 2015-06-19 23:42
I've had a look at it, but even if dependencies are vendored, it doesn't cover the case where I need to build Docker on an ARM board without any Intel machines around. I have the equivalent libraries and compilers under Ubuntu for ARM, so this doesn't make any sense.

**Comment by tianon** [comment] 2015-06-19 23:48
I'm not sure I follow what you mean?  I've just verified that this still works on an `armel` machine (specifically a Pogoplug running Debian Sid) I've got handy (which has the system-level dependencies of Docker installed):
```console
root@pogoplug:~/docker# AUTO_GOPATH=1 ./hack/make.sh dynbinary
# WARNING! I don't seem to be running in the Docker container.
# The result of this command might be an incorrect build, and will not be
#   officially supported.
#
# Try this instead: make all
#

---> Making bundle: dynbinary (in bundles/1.8.0-dev/dynbinary)
# github.com/docker/libcontainer/seccomp
vendor/src/github.com/docker/libcontainer/seccomp/filter.go:91: undefined: jumpEqualTo
vendor/src/github.com/docker/libcontainer/seccomp/filter.go:93: undefined: jumpNotEqualTo
vendor/src/github.com/docker/libcontainer/seccomp/filter.go:95: undefined: jumpGreaterThan
vendor/src/github.com/docker/libcontainer/seccomp/filter.go:97: undefined: jumpLessThan
vendor/src/github.com/docker/libcontainer/seccomp/filter.go:99: undefined: jumpMaskEqualTo
root@pogoplug:~/docker# 
```

So, there is currently a compiler error (https://github.com/docker/libcontainer/issues/636; `// +build linux,amd64` on `seccomp/jump_amd64.go` in libcontainer), but in general, this should work OK.

**Comment by tianon** [comment] 2015-06-20 00:02
With the following patch/rename, it builds successfully (although I can't say it'd actually work -- no idea why that file's locked to _just_ `linux,amd64`):
```patch
root@pogoplug:~/docker# git diff --find-copies-harder --staged
diff --git a/vendor/src/github.com/docker/libcontainer/seccomp/jump_amd64.go b/vendor/src/github.com/docker/libcontainer/seccomp/jump_linux.go
similarity index 99%
rename from vendor/src/github.com/docker/libcontainer/seccomp/jump_amd64.go
rename to vendor/src/github.com/docker/libcontainer/seccomp/jump_linux.go
index f0d0771..64ddbae 100644
--- a/vendor/src/github.com/docker/libcontainer/seccomp/jump_amd64.go
+++ b/vendor/src/github.com/docker/libcontainer/seccomp/jump_linux.go
@@ -1,5 +1,3 @@
-// +build linux,amd64
-
 package seccomp
 
 // Using BPF filters
```

```console
root@pogoplug:~/docker# AUTO_GOPATH=1 ./hack/make.sh dynbinary
# WARNING! I don't seem to be running in the Docker container.
# The result of this command might be an incorrect build, and will not be
#   officially supported.
#
# Try this instead: make all
#

bundles/1.8.0-dev already exists. Removing.

---> Making bundle: dynbinary (in bundles/1.8.0-dev/dynbinary)
Created binary: bundles/1.8.0-dev/dynbinary/dockerinit-1.8.0-dev
Building: bundles/1.8.0-dev/dynbinary/docker-1.8.0-dev
Created binary: bundles/1.8.0-dev/dynbinary/docker-1.8.0-dev

root@pogoplug:~/docker# 
```

**Comment by rcarmo** [comment] 2015-06-20 00:03
Thanks, the docs regarding dynbinary are confusing - within three paragraphs they go from mentioning a client-only build to a dynamically linked daemon and then back again, so one is left with the idea that you’re not getting the full monty.

(Note to self: see if I can contribute better wording after this is sorted out)

I’m going to try reverting to an older version (1.7.0 or 1.6, which seems to be the minimum I need for my purposes) and see if it that issue with libcontainer still happens.

**Comment by rcarmo** [comment] 2015-06-20 00:12
> On 20 Jun 2015, at 01:04, Tianon Gravi <notifications@github.com> wrote:
> 
> With the following patch/rename, it builds successfully (although I can't say it'd actually work -- no idea why that file's locked to just linux,amd64):
> 

There was a time when seccomp-BPF was not available on ARM for some reason - but I’ll give it a shot after a few hours’ sleep and report back - thanks again.

**Comment by rcarmo** [comment] 2015-06-20 09:22
I checked out 1.7.0 and 1.6.2 and got both to build (after excluding btrfs support), but the resulting binaries don't work (`docker -d -D` never finishes initialising and `docker info` freezes up). Going to see what I can do about this (if anything).

**Comment by unclejack** [comment] 2015-06-20 09:48
@rcarmo Can you provide the output of the daemon's log, please? We could at least figure out where it's getting stuck or crashing.

Knowing the kernel version, the exact steps you've taken to build Docker, the distribution you've used and the kernel's config is essential to figuring this out. https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh can be used to check the kernel's config. Having the output of this script would be useful as well.

**Comment by rcarmo** [comment] 2015-06-20 09:54
Kernel info:

<pre>
ubuntu@master:~$ bash check-config.sh
info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: nonexistent??
    (see https://github.com/tianon/cgroupfs-mount)
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: missing
    (note that cgroup swap accounting is not enabled in your kernel config, you can enable it by setting boot option "swapaccount=1")
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CFS_BANDWIDTH: missing
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled (as module)
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
    - CONFIG_EXT4_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
    - CONFIG_EXT4_FS_SECURITY: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

ubuntu@master:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
ubuntu@master:~$ uname -a
Linux master 3.18.0-23-rpi2 #24-Ubuntu SMP PREEMPT Sat May 23 20:04:29 UTC 2015 armv7l armv7l armv7l GNU/Linux
ubuntu@master:~$
</pre>

**Comment by rcarmo** [comment] 2015-06-20 09:57
Here's the daemon output, up to the point where it freezes:
<pre>
ubuntu@master:~/docker/bundles/1.7.0/binary$ sudo ./docker -d -D
DEBU[0000] Registering GET, /images/search
DEBU[0000] Registering GET, /images/get
DEBU[0000] Registering GET, /images/{name:.*}/get
DEBU[0000] Registering GET, /images/{name:.*}/history
DEBU[0000] Registering GET, /containers/ps
DEBU[0000] Registering GET, /containers/{name:.*}/top
DEBU[0000] Registering GET, /containers/{name:.*}/logs
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws
DEBU[0000] Registering GET, /_ping
DEBU[0000] Registering GET, /events
DEBU[0000] Registering GET, /images/json
DEBU[0000] Registering GET, /images/{name:.*}/json
DEBU[0000] Registering GET, /containers/json
DEBU[0000] Registering GET, /containers/{name:.*}/export
DEBU[0000] Registering GET, /containers/{name:.*}/json
DEBU[0000] Registering GET, /info
DEBU[0000] Registering GET, /version
DEBU[0000] Registering GET, /containers/{name:.*}/changes
DEBU[0000] Registering GET, /containers/{name:.*}/stats
DEBU[0000] Registering GET, /exec/{id:.*}/json
DEBU[0000] Registering POST, /images/{name:.*}/push
DEBU[0000] Registering POST, /images/{name:.*}/tag
DEBU[0000] Registering POST, /containers/{name:.*}/kill
DEBU[0000] Registering POST, /containers/{name:.*}/pause
DEBU[0000] Registering POST, /containers/{name:.*}/resize
DEBU[0000] Registering POST, /commit
DEBU[0000] Registering POST, /images/load
DEBU[0000] Registering POST, /containers/{name:.*}/copy
DEBU[0000] Registering POST, /exec/{name:.*}/resize
DEBU[0000] Registering POST, /build
DEBU[0000] Registering POST, /containers/{name:.*}/unpause
DEBU[0000] Registering POST, /containers/{name:.*}/start
DEBU[0000] Registering POST, /containers/{name:.*}/stop
DEBU[0000] Registering POST, /containers/{name:.*}/rename
DEBU[0000] Registering POST, /images/create
DEBU[0000] Registering POST, /containers/create
DEBU[0000] Registering POST, /containers/{name:.*}/wait
DEBU[0000] Registering POST, /containers/{name:.*}/attach
DEBU[0000] Registering POST, /containers/{name:.*}/exec
DEBU[0000] Registering POST, /exec/{name:.*}/start
DEBU[0000] Registering POST, /auth
DEBU[0000] Registering POST, /containers/{name:.*}/restart
DEBU[0000] Registering DELETE, /containers/{name:.*}
DEBU[0000] Registering DELETE, /images/{name:.*}
DEBU[0000] Registering OPTIONS,
DEBU[0000] docker group found. gid: 109
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] [graphdriver] using prior storage driver "aufs"
DEBU[0000] Using graph driver aufs
DEBU[0000] Using default logging driver json-file
DEBU[0000] Migrating existing containers
DEBU[0000] Creating images graph
DEBU[0000] Restored 0 elements
DEBU[0000] Creating repository list
</pre>

**Comment by rcarmo** [comment] 2015-06-20 10:03
The build steps were:
<pre>
git checkout v1.7.0
export DOCKER_BUILDTAGS='exclude_graphdriver_btrfs exclude_graphdriver_devicemapper'
AUTO_GOPATH=1 ./hack/make.sh dynbinary # or binary, same result
</pre>

**Comment by paralin** [comment] 2015-07-14 19:00
I have achieved this in Buildroot, here's the package definition file:

```
################################################################################
#
# lxcdocker
#
################################################################################

LXCDOCKER_VERSION = f8f912ac2a10ae81bbc6274dd1fb203269260263
LXCDOCKER_VERSION_ID = "1.7.1-rc1"
LXCDOCKER_SITE = $(call github,docker,docker,$(LXCDOCKER_VERSION))
LXCDOCKER_INSTALL_STAGING = NO
LXCDOCKER_INSTALL_TARGET = YES

# Perhaps suboptimal to let something in the tree clone subrepos.
# Not exactly sure what a better solution here would be.
# In Go, you need the source for these packages.
define LXCDOCKER_CONFIGURE_CMDS
	export GITCOMMIT=$(LXCDOCKER_VERSION) && \
	export VERSION=$(LXCDOCKER_VERSION_ID) && \
	export GOPATH=$(TARGET_DIR)/usr/src/go/ && \
	echo "clone git github.com/golang/protobuf ab974be44dc3b7b8a1fb306fb32fe9b9f3864b3d" >> $(@D)/hack/vendor.sh && \
	cd $(@D) && ./hack/vendor.sh
	ln -fs $(@D) $(@D)/vendor/src/github.com/docker/docker
endef

define LXCDOCKER_BUILD_CMDS
	export GOPATH="$(@D)/.gopath:$(@D)/vendor"; \
	export GOOS=linux; \
	export GOARCH=$(ARCH); \
	export CGO_ENABLED=1; \
	export CGO_NO_EMULATION=1; \
	export CGO_CFLAGS='-I$(STAGING_DIR)/usr/include/ -I$(TARGET_DIR)/usr/include -I$(LINUX_HEADERS_DIR)/fs/'; \
	export LDFLAGS="-X main.GITCOMMIT $(LXCDOCKER_VERSION) -X main.VERSION $(LXCDOCKER_VERSION_ID) -w -linkmode external -extldflags '-Wl,--unresolved-symbols=ignore-in-shared-libs' -extld '$(TARGET_CC_NOCCACHE)'"; \
	export CC="$(TARGET_CC_NOCCACHE)"; \
	export LD="$(TARGET_LD)"; \
	cd $(@D); \
 	mkdir -p bin; \
	bash ./hack/make/.go-autogen; \
	$(GOLANG) build -v -o "$(@D)/bin/docker" -a -tags "daemon" -ldflags "$$LDFLAGS" ./docker
endef

define LXCDOCKER_INSTALL_TARGET_CMDS
	cp -L $(@D)/bin/docker $(TARGET_DIR)/usr/bin/docker
endef

LXCDOCKER_DEPENDENCIES = lxc linux-headers btrfs-progs sqlite lvm2 host-golang

$(eval $(generic-package))
```
This should be pretty easy to transform to work in an actual ARM system as opposed to cross compiling.

**Comment by rcarmo** [comment] 2015-08-19 09:35
I had some time to tackle this, and while experimenting with the above I came across [this HOWTO](https://github.com/umiddelb/armhf/wiki/Installing,-running,-using-docker-on-armhf-%28ARMv7%29-devices) to build 1.7.1, which despite working for me doesn't address the issue fully (i.e., it relies on Docker 1.0.1 being available).

Given another stretch of available time (maybe next week) l intend to re-flash one of my boards and try adapting the buildroot recipe above for 1.8.x. Let's hope I don't get stuck on #15053 too.

**Comment by paralin** [comment] 2015-08-19 11:20
I can confirm it works on arm 32 or 64. It's really a pretty simple patch. 

https://github.com/paralin/buildroot

See package/lxcdocker

I link my fork because docker and several support packages haven't been merged upstream yet.

**Comment by alexellis** [comment] 2015-10-26 09:05
The paths have changed with 1.8.3 and newer, but I tried to apply the above patch manually - renaming jump_amd64.go to jump_linux.go and altering the build line to remove amd64. That got further but then failed at:

Created binary: bundles/1.8.1/dynbinary/dockerinit-1.8.1
Building: bundles/1.8.1/dynbinary/docker-1.8.1
# github.com/docker/docker/pkg/devicemapper
.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper_wrapper.go:191: Cdeps.device undefined (type *C.struct_dm_deps has no field or method device)

File in new location.

vendor/src/github.com/opencontainers/runc/libcontainer/seccomp/

I am on Arch linux which ships with 1.7.1 and gives no internet access after running up the first container so am looking to update.

**Comment by infidel** [comment] 2015-10-26 16:13
@alexellis same here, see #15279 
Arch Linux on x86_64 uses Docker 1.8.3 with Go 1.5.1 so the same patch might also work on ARM: https://projects.archlinux.org/svntogit/community.git/tree/docker/trunk

**Comment by justincormack** [comment] 2016-04-28 16:15
Are you still having issues here? Docker does build fine without docker. If there are specific arm issues still, maybe you could open another issue, as as far as I know the issues here are resolved.

**Closed** 2016-04-28 16:16 UTC

**Comment by drubanov** [comment] 2016-12-15 22:48
Sorry, but "build without self-dependency" has to be possible to enable any kind of security assurance.  A makefile or even a shell script which ensures all dependencies and doesn't depend on a binary which pulls things off the net should be enough.  

Otherwise, **there is an obvious vector of attack**.  Imagine a poisoned docker version pulling some of the packages from a poisoned package repository in addition to the standard one.  It would then inject code into the linked binary which does not use the "real" libs and binaries, but the ones which have hooks to do injection on any attempt to build a docker binary, but acts as normal otherwise (and, of course, adds some malicious behavior).

This would create a root of a poisonous tree.  There needs to be a path to building the binary without pulling necessary dependencies, but only checking them.  It can _optionally_  also give references to where the required versions can be obtained.

**Comment by thaJeztah** [comment] 2016-12-15 22:53
@drubanov following the discussion above, it's still possible to build docker without docker; is there something not working for you?

**Comment by nathanleclaire** [comment] 2016-12-15 22:54
> Imagine a poisoned docker version pulling some of the packages from a poisoned package repository in addition to the standard one. It would then inject code into the linked binary which does not use the "real" libs and binaries, but the ones which have hooks to do injection on any attempt to build a docker binary, but acts as normal otherwise (and, of course, adds some malicious behavior).

It's the usual dilemma though, isn't it ("What if the compiler is malicious")?

You have to start somewhere in a chain of trust and here the start is with the base image (BTW, I think these are cryptographically signed with https://github.com/docker/notary, so you have an assurance that they are what the original authors, the Docker team, intended you to receive).  Do you hand-assemble your C compiler, kernel, firmware, and so on?  Otherwise, couldn't this argument could be made about any of those pieces as well, since the integrity of the next step depends on them?

**Comment by drubanov** [comment] 2016-12-15 23:05
@nathanleclair, sorry, this is going to be slightly belligerent, but since security is in question, I believe a confrontational review is more justified than a good-will-forming benefit-of-the-doubt review.  

There is an ability to cross compile a compiler.  And then the "real" version of the compiler can be compiled by building the sources for the 2nd time with the results of the 1st compilation.  So, given the source code, a compiler audit can be performed without putting any trust in the source from which the source code came.  

Even if the image is signed, any dependency on a binary from the same source (not source code) is still only as trustworthy as the source itself.  And asking all IT in the world to trust the authors of docker without building the source code on your own, is as good as trusting closed source.

**Comment by drubanov** [comment] 2016-12-15 23:21
@thaJeztah, the gist of my comment was that an ability to build without a running docker has to be provided in the standard source or open audits will be extremely rare and less trusted.

**Comment by thaJeztah** [comment] 2016-12-15 23:50
@drubanov but it _is_ there; https://github.com/docker/docker/issues/14056#issuecomment-113674225, and a list of other packages to build can be found in the dockerfile; basically, those steps show exactly what has to be executed to build.

if someone wants to maintain a separate makefile for making those steps easier; it's all open source, and we accept contributions

**Comment by drubanov** [comment] 2016-12-16 00:13
@thaJeztah, well this is an issue tracker.  I guess I am advocating for this to be considered an issue.  Thank you very much for pointing out the comment which shows a good starting point.

**Comment by flaccid** [comment] 2016-12-16 00:58
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=docker-git

**Comment by paralin** [comment] 2016-12-16 01:59
https://github.com/paralin/buildroot/blob/master/package/docker-engine/docker-engine.mk

Buildroot maintains make files for docker builds without docker.

**Comment by drubanov** [comment] 2016-12-24 02:47
@thaJeztah  I tried it offline and it fails almost immediately.  hack/make.sh attempts to verify that the latest version on github is what we have.  This is despite the fact that the I was downloading 1.12.4 from github. And then it still tries to pull something off the network.  I basically ended up picking and choosing parts of the dockerfile and parts of the make.sh to built with all the networks disconnected (and daemon not running).  containerd and client built.  I haven't tried building registry yet.  Until I have a setup which can **build and run** registry, daemon and client completely offline, in my view, I have to treat this as closed-source software.

**Comment by paralin** [comment] 2016-12-24 04:14
@drubanov once again it's not very difficult to compile docker... I've linked you a makefile that contains every command you need to do it (quite minimal, about 5 lines in reality). I don't know why you would bother mucking around in the make.sh files that are obviously intended for a different type of build.
