### ISSUE TITLE
docker swarm mode overlay can't access external internet

### ISSUE THREAD

**Issue by fingermark** [docker/docker#27399] opened 2016-10-14 21:08 UTC
**Description**

I'm using swarm mode and a network overlay on AWS.  On the AWS created docker-machines I can access the external network.  Inside the docker container I cannot. 

It is likely that I'm doing something wrong.

**Steps to reproduce the issue:**

```
PC=...
REGION=...
SUBNET=...
ZONE=...

docker-machine create -d amazonec2 --amazonec2-vpc-id $VPC --amazonec2-region $REGION --amazonec2-zone $ZONE --amazonec2-instance-type t2.micro --amazonec2-subnet-id $SUBNET --amazonec2-security-group swarm-mode selenium-swarm-manager

# Get IP
docker-machine ssh selenium-swarm-manager ifconfig eth0

# Point docker client to the swarm manager
eval $(docker-machine env selenium-swarm-manager)

# Initialize the swarm
docker swarm init --advertise-addr <ip from above>
# Note the output to join nodes, as it will be used below

eval $(docker-machine env selenium-swarm-node1)
docker swarm join --token <token> from <ip from above>:2377

eval $(docker-machine env selenium-swarm-node2)
docker swarm join --token <token> from <ip from above>:2377

docker network create seleniumnet --driver overlay
docker service create --name hub --network seleniumnet -p 4444:4444 selenium/hub
# more docker service creates for same network

# connect to the container, wherever it was created
eval $(docker-machine env selenium-swarm-manager)
docker exec -it 9b299e486b0a bash
$ sudo apt-get update # note that it hangs
```

It now hangs.  Note that the container doesn't have access to ping or anything useful, which I don't get.

**Describe the results you received:**

Hang

**Describe the results you expected:**

External HTTP requests.  Note that this was tested other ways as well.  Same result.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Docker version 1.12.2, build bb80604, experimental
 
**Output of `docker info`:**
```
Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 5
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 79
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: active
 NodeID: 1dac0q4m0qh2hp3ug33p5rnyr
 Is Manager: true
 ClusterID: 9jmu7r5rh9gu5rq8qw5j2ky3m
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.0.127
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-18-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.1 MiB
Name: selenium-swarm-manager
ID: QXFU:53LD:SQKN:7SZM:VYOK:2GYG:KOMB:OFYU:STLS:R5CN:A4AA:QPYP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Insecure Registries:
 127.0.0.0/8
```

**Comment by fingermark** [comment] 2016-10-15 13:21
I think this may be related to:  https://github.com/docker/docker/issues/19298.

My VPC subnet is 10.0.0.0.  docker_gwbridge is configured to 172.18.0.0/16.  I'm not sure what I should do.  @mavenugo should I remove that network and run `docker network create --opt com.docker.network.bridge.enable_icc=false --subnet=10.0.0.0/24 docker_gwbridge`?

**Comment by herbrandson** [comment] 2016-10-15 14:28
Same issue here.

Docker Version:
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:24:45 2016
 OS/Arch:      linux/amd64
```

Docker Info:
```
Containers: 7
 Running: 5
 Paused: 0
 Stopped: 2
Images: 15
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 52
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: 2wjvx8xti9kak9aagfvqavl0z
 Is Manager: true
 ClusterID: 7v5pz9ku2x89hhq4u1cz9q9qp
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.11.202
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-18-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.1 MiB
Name: Stage-master-01
ID: RPVK:S4ME:NO6L:NHZY:BVZG:KHKU:3MLL:LKZ2:BMTF:HX5N:RZCO:6M3Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: herbrandson
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Insecure Registries:
 127.0.0.0/8
```

Docker network inspect
```
[
    {
        "Name": "docker_gwbridge",
        "Id": "dca75be41103848b77361c1a6e1507cdc8882360cba4bc9b07e9a5a1cd6916b5",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "32c933a42ed2e6017789369636e1372a0e8fe1b5ac75fe3927fa5da4885c1152": {
                "Name": "gateway_32c933a42ed2",
                "EndpointID": "84c5944805903056196f0404c4e5d466ba02c919c1cf2b6348fd2939f9e9fc82",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "740ee9bebd5c3f620f4dfb9c7f19a9181a66224cb6fe9813fda4588dfc2fb24a": {
                "Name": "gateway_740ee9bebd5c",
                "EndpointID": "026ba9c4fb06b31a494559ec0bff5ba227460f695ab4eef167751f6d4a654615",
                "MacAddress": "02:42:ac:12:00:05",
                "IPv4Address": "172.18.0.5/16",
                "IPv6Address": ""
            },
            "b9acafb093dc6f68f55dfa8dbd56bb27f412d87341c3d31277d137064b37260d": {
                "Name": "gateway_b9acafb093dc",
                "EndpointID": "1c3a09bd6be42621bc6eff855b497565aac55247a5c3444a8c77323a97aa8af3",
                "MacAddress": "02:42:ac:12:00:06",
                "IPv4Address": "172.18.0.6/16",
                "IPv6Address": ""
            },
            "e0c99aba691dc20daf50fd2ef5adfa449f6d9daa68683f66328e45b297d2811d": {
                "Name": "gateway_e0c99aba691d",
                "EndpointID": "4c54e8c5b9b42bf222bfc0ceb178fb4fe79bd34c086cf6918d0ab3e809db6a5c",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },
            "f8764a1982148c7a9570d3a2d9553826a07fb117f1cb6a15c67b5b45caa5827c": {
                "Name": "gateway_f8764a198214",
                "EndpointID": "9f2d492f0b73d719a23e333fb574f4538bc7fb93a7fff1f96b5889a87aa0b9b3",
                "MacAddress": "02:42:ac:12:00:07",
                "IPv4Address": "172.18.0.7/16",
                "IPv6Address": ""
            },
            "ingress-sbox": {
                "Name": "gateway_ingress-sbox",
                "EndpointID": "651299e1eedc6e334d0b2ebc7fa8e0f28ec6045c281f85c5a5e0ac87ebce625a",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.enable_icc": "false",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.name": "docker_gwbridge"
        },
        "Labels": {}
    }
]
```

and

```
[
    {
        "Name": "internal",
        "Id": "5fq38j1x76ev9covtez7qracw",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.0.0/16",
                    "Gateway": "10.0.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "32c933a42ed2e6017789369636e1372a0e8fe1b5ac75fe3927fa5da4885c1152": {
                "Name": "mongodb.1.7ojqju9xi2gpwnfjsg0cnvkue",
                "EndpointID": "d79ed89a5adf9401be9d34d41256ce4d8c0dbb4542cc387b63227ac4fc9704f1",
                "MacAddress": "02:42:0a:00:00:03",
                "IPv4Address": "10.0.0.3/16",
                "IPv6Address": ""
            },
            "740ee9bebd5c3f620f4dfb9c7f19a9181a66224cb6fe9813fda4588dfc2fb24a": {
                "Name": "geocode.2.2i6sf39tzlf5xqmqluobbq9v7",
                "EndpointID": "36d836a645bee10dde535f8974475a3362f834d99f35df347daf4c191162ab59",
                "MacAddress": "02:42:0a:00:00:14",
                "IPv4Address": "10.0.0.20/16",
                "IPv6Address": ""
            },
            "b9acafb093dc6f68f55dfa8dbd56bb27f412d87341c3d31277d137064b37260d": {
                "Name": "shotspottercollector.1.f2zd40okghs1vs8qwtde956e8",
                "EndpointID": "f6ef781ee714b5819ead4cae5bb07c6b0402b8e19bdf740adcd17ff3817b4d35",
                "MacAddress": "02:42:0a:00:00:16",
                "IPv4Address": "10.0.0.22/16",
                "IPv6Address": ""
            },
            "e0c99aba691dc20daf50fd2ef5adfa449f6d9daa68683f66328e45b297d2811d": {
                "Name": "billing.2.2bt50pwucx1m34bmcg4mor391",
                "EndpointID": "3a8d42e2c39108ecb809995246738fb680ee82fccdda66532cdf8c629e055cdd",
                "MacAddress": "02:42:0a:00:00:0b",
                "IPv4Address": "10.0.0.11/16",
                "IPv6Address": ""
            },
            "f8764a1982148c7a9570d3a2d9553826a07fb117f1cb6a15c67b5b45caa5827c": {
                "Name": "swagger.2.8zhtkhm7nqhi7abck8680hgp9",
                "EndpointID": "960fd0d730377a37e7de0a694d3ac289a01451838e07d80adc7397263396229a",
                "MacAddress": "02:42:0a:00:00:1d",
                "IPv4Address": "10.0.0.29/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "257"
        },
        "Labels": {}
    }
]
```

**Comment by fingermark** [comment] 2016-10-15 15:24
Maybe it would help if I described exactly what I was looking to achieve:

Using AWS EC2 t2.micro instances and AWS VPC with a private and public subnet.
How would I create the following using docker swarm mode:

## Requirements

### Hub Node (count: 1)
- On a publicly accessible IP
- Must be on same public IP every time
- Must be able to communicate with chrome nodes
- Run with:
  `docker service create --name hub --network seleniumnet -p 4444:4444 selenium/hub --replicas 1`

### Chrome Nodes (count: 50)
- On private IPs (without public IP)
- Must be able to make requests to outside internet
- Must be able to make requests to Hub Node
- Only one node per host
- Run with:
  `docker service create --network seleniumnet --endpoint-mode dnsrr --name chrome --mount type=bind,source=/dev/shm,target=/dev/shm -e HUB_PORT_4444_TCP_ADDR=hub -e HUB_PORT_4444_TCP_PORT=4444 --replicas 50 selenium/node-chrome:2.53.1-beryllium bash -c 'REMOTE_HOST=http://$HOSTNAME:5555 /opt/bin/entry_point.sh'`

## AWS VPC Details:

VPC (vpc-00000001):
- subnet: `10.0.0.0/16`

public subnet (subnet-00000001):
- subnet: `10.0.0.0/24`
- routes:
```
10.0.0.0/16 local
0.0.0.0/0 igw-id
```

private subnet (subnet-00000002):
- subnet: `10.0.1.0/24`
- routes:
```
10.0.0.0/16 local
0.0.0.0/0 nat-gateway-id
```

## Notes:

docker_gwbridge gets automatically created with:

```
"Config": [
    {
        "Subnet": "172.18.0.0/16",
        "Gateway": "172.18.0.1"
    }
```

**Comment by terpsho** [comment] 2016-10-16 18:47
Issue +1.
I didn't use AWS but my own lab. I encountered similar issue. After the containers were created in the swarm mode, I can only access it through 172.18.0.2 (docker_gwbridge interface). I intended to access the container through a public subnet at 192.168.209.x but cannot. 
I tried to re-create docker_gwbridge to be under the intended subnet as well as gateway but docker does not allow with an error message:
"Error response from daemon: network with name docker_gwbridge already exists".

**Comment by sanimej** [comment] 2016-10-17 06:21
@fingermark When the `docker_gwbridge` is created MASQUERADE rules are programmed in the iptables for external connectivity. This would be the same irrespective of EC2 instance being in a public subnet or a private subnet going through the nat-gw. I haven't tried myself yet. But may be the behavior is because of the way VPC connectivity is setup when using private subnet. 

Looks like from your experiment it works if you manually create the `docker_gwbridge` network manually with the same subnet as that of the private VPC subnet. Unfortunately its a work around that has to be applied on every node individually.

**Comment by herbrandson** [comment] 2016-10-17 17:26
@fingermark Per your comments above, I ran the following commands

```
docker network disconnect -f docker_gwbridge gateway_ingress-sbo
docker network rm docker_gwbridge
docker network create --opt com.docker.network.bridge.enable_icc=false --subnet=10.0.0.0/16 docker_gwbridge
```

However I'm still unable to launch services due to `failed to allocate gateway (1…`

Did I miss a step?

**Comment by fingermark** [comment] 2016-10-17 18:43
@herbrandson I wound up starting over.  I left the docker_gwbridge gateway alone and assigned my network overlay a subnet different from anything else:  `--subnet=192.168.1.0/24`.  I'm now able to access servers on the same network and externally.

**Comment by herbrandson** [comment] 2016-10-17 20:11
@fingermark That worked for me as well. Thanks a ton!

**Comment by westsouthnight** [comment] 2016-10-24 08:30
People how to convert Consul Values to IP?

I have troubles when update docker to latest version. 

Some containers on Docker Node (~50% of all connected to swarm network) not start after restart docker service. 

I got error - Error response from daemon: Cannot restart container cc8543c658dc: Address already in use.

Then i try to disconnect container from network 

 docker network disconnect swarm-production production-logging-storage-12

after then 

docker network connect --ip 10.21.2.4 swarm-production cc8543c658dc

and again got 

Error response from daemon: Address already in use

**Comment by sanimej** [comment] 2016-10-28 14:03
@fingermark Your observation that using `--subnet=192.168.1.0/24` for overlay fixes the problem is correct. The reason for the original problem is a bit involved though.

Within a container in an EC2 instance on a private subnet only the name resolution fails, but the external connectivity is just fine..

```
root@6ce46f8458c1:/# ping google.com
^C
root@6ce46f8458c1:/# ping 216.58.193.110
PING 216.58.193.110 (216.58.193.110) 56(84) bytes of data.
64 bytes from 216.58.193.110: icmp_seq=1 ttl=45 time=7.60 ms
64 bytes from 216.58.193.110: icmp_seq=2 ttl=45 time=7.25 ms
^C
--- 216.58.193.110 ping statistics ---
```
The address range in VPC by default is (10.0.0.0/16) and the DHCP server provisioned by AWS is 10.0.0.2. The default address range of overlay networks also start at 10.0.0.0/24. This is still fine because the docker overlay bridge is created inside a separate network namespace (this has a kernel version dependency though). But for DNS resolution, the queries from the container are sent to the Docker embedded DNS server, 127.0.0.11 (address in container's resolv.conf).

Though the DNS server runs as part of the docker daemon it tries to do the routing to the DNS name server address, `10.0.0.2` here, inside the container's name space. Since it conflicts with the overlay address range, packets will not be sent to the DNS server. That is the reason why external connectivity works but only the resolution is failing.

To work around this there are two options..
1) creating the overlay network in a different address range like you did
2) In the EC2 host, change the DNS server IP in the resolv.conf. for ex: if you change it to 8.8.8.8 it will work.

Since there is no fix required here I think this issue can be closed.

**Comment by thaJeztah** [comment] 2016-10-29 00:39
closing per the above comment, but let me know if you think this was closed by mistake

**Closed by thaJeztah** 2016-10-29 00:39 UTC
Labels: area/networking, area/swarm, version/1.12

**Comment by westtrade** [comment] 2017-03-24 21:44
I was have the very similar problem. I create container with bridge network and static IP and... have static IP without external internet in container, i solve this problem by attaching container to default (in docker-compose) network.

[Example gist](https://gist.github.com/westtrade/3c0e69ae47d9bf538ba9bd0a0e0c847d)

**Comment by pavlo** [comment] 2017-09-07 11:09
@fingermark - you rock, thanks!

**Comment by pgilad** [comment] 2017-10-18 10:44
@sanimej Awesome solutions! I fear that changing your resolv.conf might interfere with EC2 internal dns resolution, so the better resolution would be to change your docker swarm subnet. Still awesome reply! I learnt a lot! 💘

**Comment by zhaoyao91** [comment] 2017-11-03 07:30
@sanimej Can we change the default address range of overlay networks of docker swarm?

**Comment by sctse999** [comment] 2017-11-21 02:30
It would be great if this could be stated in docker swarm create network documentation. I spent several hours figuring this out ......

**Comment by mitsos1os** [comment] 2018-01-30 20:32
I also agree that this should be in docker docs...
Also @sanimej shouldn't the internal Docker DNS server know to route the DNS requests to the host's physical network, instead of trying to use the docker inner network in order to avoid this conflict?

**Comment by EvanBurbidge** [comment] 2018-06-21 20:45
@sanimej you are a my new sensei with this! I've been pulling my hair out all day and finally got the pings to work! Thanks for the detailed explanation, have to give a talk on Docker in work tomorrow and this was the first horrible pain point i've hit with it! Legend! For anyone using docker stacks, swarms / compose you can use this config
```
  interwebs:
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.1.0/24

```

**Comment by witsec** [comment] 2018-07-11 20:18
I'm having the same issue. When a container is attached to an overlay network, I can't access the network the host is connected to.

It works fine if I don't specify a network container (and so it's attached to bridge).

In my stack file, I gave my network a 192 subnet, as per @EvanBurbidge's post above, but that doesn't change anything unfortunately.

The containers are on a 10.* IP range, like others have mentioned.

It seems people here are/were having the same issue, but unfortunately so far the posted solutions don't work in my end.

Is setting the subnet the only thing that's needed for you guys to make this work?

If someone can post a step-by-step solution to how they fixed this, that could be helpful. Perhaps I'm overlooking something here...

Thanks!

**Comment by EvanBurbidge** [comment] 2018-07-11 21:45
@witsec how many networks are you defining on that container? I found in my case I had an issue whereby I had two networks on one container, both of type overlay and they were "contradicting" each other if that makes sense?

**Comment by witsec** [comment] 2018-07-12 05:39
Just one network. Here's the stack.yml I'm using to test this at the moment. Obviously it's been shortened for testing purposes:

```
version: '3'

services:

  ssh:
    image: rastasheep/ubuntu-sshd
    networks:
      - whatevs

networks:
  whatevs:
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.1.0/24
```

If I deploy this stack, I can't access the host's network.

However, if I do a `docker run -it rastasheep/ubuntu-sshd bash` and for example ssh to a host on the network, it works fine (because it's connected to bridge then).
