### ISSUE TITLE
"Cannot kill container: no such process" if exec is executing when exiting the container

### ISSUE THREAD

**Issue by mapio** [docker/docker#9885] opened 2015-01-03 22:10 UTC
I'm experiencing this with Docker version 1.4.1, build 5bc2ff8 (on OSX using boot2docker (Boot2Docker-cli version: v1.4.1 Git commit: 43241cb).

The step to reproduce it are:

1. start a test container with `docker run -it --name test_exec_bug busybox`

2. exec into it `docker exec -it test_exec_bug sh`

3. issue the `exit` command at the prompt of container run in 1.; the process started in 2. exits, but the container run in 1. seems to hang;

4. try to kill it with `docker kill test_exec_bug`, all I get is
```
Error response from daemon: Cannot kill container test_exec_bug: no such process
FATA[0000] Error: failed to kill one or more containers 
```

**Comment by LK4D4** [comment] 2015-01-03 22:35
Duplicate of #9699

**Closed by LK4D4** 2015-01-03 22:35 UTC
