### ISSUE TITLE
Basic volume mount fails with windows docker client against boot2docker 

### ISSUE THREAD

**Issue by skaegi** [docker/docker#12751] opened 2015-04-24 16:47 UTC
I'm just trying to do the most basic volume mount. Something like....

```bash
$ docker run -it -v /myvol debian:jessie /bin/bash
FATA[0000] Error response from daemon: cannot bind mount volume: C volume paths must be absolute.
```

Using docker 1.6
Windows Client / Boot2Docker Host
Git Bash with eval {boot2docker shellinit}

--
Using a host directory I get...

```bash
$ docker run -it -v /myvol:/myvol debian:jessie /bin/bash
invalid value "C:\\Program Files (x86)\\Git\\myvol;C:\\Program Files (x86)\\Git\\myvol" for flag -v: \Program Files (x86)\Git\myvol;C:\Program Files (x86)\Git\myvol is not an absolute path
See 'c:\Program Files\Boot2Docker for Windows\docker.exe run --help'.
```

--
I expected everything to run relative to the host. e.g. I expected the same behavior as if I was running these commands with ```boot2docker ssh```. Am I  missing something here?

**Comment by SirRagnar** [comment] 2015-04-25 20:22
+1

**Comment by thaJeztah** [comment] 2015-04-25 21:00
/ping @ahmetalpbalkan (haven't tested this myself yet)

**Comment by ahmetalpbalkan** [comment] 2015-04-25 22:19
@skaegi @SirRagnar  This is duplicate of #12590. It's happening due to msys, it converts unix paths to windows paths before passing them to docker.exe

See my comments in #12590 to run it correctly, or use cmd.exe or powershell to not to have this problem.

**Comment by thaJeztah** [comment] 2015-04-25 22:32
@ahmetalpbalkan do you think we should add something to the docs explaining this? I can imagine more people will run into this.


I'm going to close this issue, because of the reasons mentioned above https://github.com/docker/docker/issues/12751#issuecomment-96288101

Thanks for reporting @skaegi, it's appreciated

**Closed by thaJeztah** 2015-04-25 22:32 UTC
Labels: os/windows

**Comment by skaegi** [comment] 2015-04-27 14:26
I tried the path workarounds with no luck but indeed this is MSYS path conversion in action -- a few more details [here](http://www.mingw.org/wiki/Posix_path_conversion)

**Comment by phazei** [comment] 2015-06-04 19:16
The double slash at the beginning works in most cases.  But there's one in particular that won't work

    docker exec -it web rsync -rvul --exclude='/vendor' //var/www/files_remote/ //var/www/files

Problem bit is `--exclude='/vendor'` if I switch it to `--exclude='//vendor'` rsync doesn't match it properly so the vendor directory is included.  If I change it to `--exclude='vendor'` it excludes in sub dirs as well.

I've tried playing with the posix path conversion rules that @skaegi linked to, but couldn't find a combo that would work.  Any suggestions?

**Comment by ahmetalpbalkan** [comment] 2015-06-04 20:14
@phazei hmm actually if the argument starts with `'`, it doesn't do path conversion AFAIK as documented [here](http://www.mingw.org/wiki/Posix_path_conversion). So maybe `'--exclude=/vendor'` would just work?

**Comment by ktmswzw** [comment] 2016-03-03 11:43
docker run -d --name redis-server -p 6379:6379 -v /h/redis:/var/lib/redis anapsix/redis

/h/redis  =  H://redis

**Comment by Avinash-Setty** [comment] 2016-03-16 13:57
Recently I tried mounting using Docker Run command in Windows, still it doesn't work. Can anyone help me here?

```
avina@avinash-laptop MINGW64 ~
$ ll /c/development/phase2/Experiments/SimpleApp/src/SimpleApp
total 872
-rw-r--r-- 1 avina 197611    412 Mar 15 17:44 appsettings.json
-rw-r--r-- 1 avina 197611    207 Mar 15 17:43 bower.json
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Controllers/
-rw-r--r-- 1 avina 197611   1249 Mar 15 17:43 gulpfile.js
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Migrations/
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Models/
drwxr-xr-x 1 avina 197611      0 Mar 15 17:43 node_modules/
-rw-r--r-- 1 avina 197611    213 Mar 15 17:43 package.json
-rw-r--r-- 1 avina 197611   1809 Mar 15 17:44 project.json
-rw-r--r-- 1 avina 197611 840603 Mar 15 17:50 project.lock.json
-rw-r--r-- 1 avina 197611   7006 Mar 15 17:43 Project_Readme.html
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Properties/
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Services/
-rw-r--r-- 1 avina 197611   1332 Mar 15 17:43 SimpleApp.xproj
-rw-r--r-- 1 avina 197611    241 Mar 15 18:05 SimpleApp.xproj.user
-rw-r--r-- 1 avina 197611   3928 Mar 15 17:44 Startup.cs
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 ViewModels/
drwxr-xr-x 1 avina 197611      0 Mar 15 17:44 Views/
drwxr-xr-x 1 avina 197611      0 Mar 15 17:43 wwwroot/

avina@avinash-laptop MINGW64 ~
$ docker run -v /c/development/phase2/Experiments/SimpleApp/src/SimpleApp:/SimpleApp -p 5000:5000 -it microsoft/aspnet
root@112446af63af:/# cd SimpleApp/
root@112446af63af:/SimpleApp# ls -al
total 4
drwxr-xr-x  2 root root   40 Mar 16 13:36 .
drwxr-xr-x 60 root root 4096 Mar 16 13:36 ..
root@112446af63af:/SimpleApp# exit
```

**Comment by thaJeztah** [comment] 2016-03-16 14:44
By default, only the "c:\users\" directory is shared with the VirtualBox VM, so anything outside of that can't be used as a volume, unless you configured VirtualBox to share other directories

**Comment by mathiasconradt** [comment] 2016-03-17 12:56
I am having the problem on Windows 2016 Server TP4, without using boot2docker, since containers are supported there natively.
I try to mount a folder beneath C:\Users\myuser\.. as data volume, like this:

`docker run --name iisdemo2 -it -p 80:80 -v /c/Users/mlin/meinedaten:/c/meinedaten iis cmdclear`

but it fails with an error:

> docker : docker: Error response from daemon: Invalid bind mount spec "/c/Users/mlin/meinedaten:/c/meinedaten": volumeinvalid: Invalid volume specification: 
> '/c/Users/mlin/meinedaten:/c/meinedaten'.

Detailed issue report: http://superuser.com/questions/1051520/docker-windows-container-how-to-mount-a-host-folder-as-data-volume-on-windows

**Comment by thaJeztah** [comment] 2016-03-17 23:57
@mathiasconradt I think the "container" path for Windows containers needs to be a regular Windows-style path (forward slashes are accepted though), so

    -v /c/Users/mlin/meinedaten:/c:/meinedaten

(`c:/meinedaten` instead of `c/meinedaten`)

**Comment by mathiasconradt** [comment] 2016-03-18 11:37
@thaJeztah Thanks, you are right. I tried C: before but had left the trailing / in the front, which does not work. Not it's working, thanks a lot!

**Comment by SacredSkull** [comment] 2016-04-04 16:14
You can set an environmental variable to disable path conversion, but note this was ONLY added in Git for Windows. 

`MSYS_NO_PATHCONV=1 docker run -v ...`

It's still a very hacky fix.

http://stackoverflow.com/a/34386471/1160528

**Comment by adeelahmadch** [comment] 2017-01-08 14:38
**Error:** Invalid volume specification 
**Info:** 
Docker 1.12.5
docker-compose version 1.9.0
docker-machine.exe version 0.8.2
Terminal: git bash
OS: Windows 10

**Description:** 
I just want to share my experience here for windows users who use git bash and ran into volume mount issue. i had a similar problem but unlike other people i was facing issue with "docker-compose up" command. In my .yml file i was trying to mount volume like; 

```
volumes:
    - "/e/orchestration-workshop/dockercoins/webui/files/:files/"
``` 

i tried everything from // to ' but nothing worked for me. at the end i tried this workaround to make it work. 

```
volumes:
    - "/e/orchestration-workshop/dockercoins/webui/files/"
```

So when you don't specify volume it use the same name as of your source directory and it worked. now i can see my folder mounted under /files on my docker container. 
 
:-)

**Comment by mirasrael** [comment] 2017-01-12 14:05
@adeelahmadch I found Docker-compose has an option `COMPOSE_CONVERT_WINDOWS_PATHS` which solves this problem:=1 docker-compose up -d

**Comment by laltman2** [comment] 2017-01-18 06:36
@mirasrael thanks, this worked for me!

**Comment by SusrithaMunukutla** [comment] 2017-04-06 07:01
docker run -itd -p 7776:7776 -v C:/temp/test:C:/testdir  --name Test  inet-test

This worked for me (y)

Going into Container : 

docker exec -it <containerid> powershell   (for windows containers)

**Comment by DanJ210** [comment] 2017-05-04 19:04
I couldn't get `COMPOSE_CONVERT_WINDOWS_PATHS=1 docker-compose up -d` to work I get red errors.

I'm just trying to run a basic tutorial volume thing that gives the above error response from daemon, invalid bind spec or not a valid repository/tag... Maybe someone can tell me how paths are supposed to be typed in via powershell. Like this line below, what am I typing wrong? How would I type that path? Thanks.

`docker run -v /c:/Users:/data alpine ls /data`

**Comment by DanJ210** [comment] 2017-05-04 19:12
Or when I try to create a container like this,

`docker run -v $(pwd):/app -w /app node npm start` I get ":/app" is not a valid repository/tag: invalid reference format.

So I'm not sure what I'm doing wrong to get this to work. I've already got an express app installed and I'm in that directory, that's where the PWD comes in and seems to throw now error. Only the `:/app`

**Comment by hugokoka** [comment] 2017-10-02 17:04
I solved it!

Add a volume:

docker run -d -v my-named-volume:C:\MyNamedVolume testimage:latest
Mount a host directory:

docker run -d -v C:\Temp\123:C:\My\Shared\Dir testimage:latest

**Comment by hugokoka** [comment] 2017-10-02 17:05
I solved it!

Add a volume:

docker run -d -v my-named-volume:C:\MyNamedVolume testimage:latest

Mount a host directory:

docker run -d -v C:\Temp\123:C:\My\Shared\Dir testimage:latest

**Comment by mtpultz** [comment] 2017-11-28 03:40
@DanJ210 did you ever figure out why you were getting that error due to the working directory?  I've got the same issue and I can't figure out why it won't work.
