### ISSUE TITLE
Find volumes without containers and restore them

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#7811] opened 2014-08-30 20:16 UTC
i think recreate containers for all volumes that are there and got no container anymore will help a lot

so you can see them via docker ps and delet again with -v

**Comment by jfrazelle** [comment] 2015-02-25 22:22
@cpuguy83 i think this might be a duplicate of something but idk

**Comment by cpuguy83** [comment] 2015-02-26 01:25
Not explicitly no, but handled by #8484

**Comment by thaJeztah** [comment] 2015-02-28 23:37
@frank-dspeed I think #8484 (which implements https://github.com/docker/docker/issues/8363) covers your use case. If you agree, this issue can be closed, so that the discussion can be continued on #8484

**Closed** 2015-03-02 02:21 UTC
Labels: feature

**Comment by thaJeztah** [comment] 2015-08-26 20:30
For those following this; volume management is now implemented in https://github.com/docker/docker/pull/14242, which was just merged, and will be in **docker 1.9**

If you want to test it before that, nightly builds, build from master can be found at https://master.dockerproject.org
