### ISSUE TITLE
Docker daemon won't start. "Error starting daemon: timeout"

### ISSUE THREAD

**Issue by Sridarshan** [docker/docker#22970] opened 2016-05-25 05:03 UTC
I'm trying to get a docker setup up in my Ubuntu 14.04 which is running inside Virtualbox with bridged network setting. When I try to start the docker daemon through ```sudo service docker start```, it won't show any error but its apparent that the daemon is not running. When I run ```sudo docker daemon -D```, I get the following output,

**Edit** : I dont think it has anything do with Virtualbox, tried with a Ubuntu running on VMM on Ubuntu, got the same error. But I'm not ruling out the possibility of this issue having something to do with VMs.

```
$ sudo docker daemon -D
DEBU[0000] docker group found. gid: 999
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock)
INFO[0000] previous instance of containerd still alive (14663)
DEBU[0000] Using default logging driver json-file
DEBU[0000] Golang's threads limit set to 5130
DEBU[0000] containerd connection state change: READY
DEBU[0000] received past containerd event: &types.Event{Type:"live", Id:"", Status:0x0, Pid:"", Timestamp:0x57453085}
INFO[0000] [graphdriver] using prior storage driver "aufs"
DEBU[0000] Using graph driver aufs
DEBU[0001] Cleaning up old mountid : start.
FATA[0001] Error starting daemon: timeout

```
Any help fixing this?

**Output of `docker version`**
```
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

```

**Output of `docker info`:**

```
$ docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-05-25 19:55
Is this a fresh install, or did you have an older docker version (older than 1.10) installed on that machine?

**Comment by Sridarshan** [comment] 2016-05-25 20:53
Yes, this is a fresh install. I also tried installing on a fresh machine with Ubuntu 14.04 and got the same error. I followed the instructions on this page. [https://docs.docker.com/engine/installation/linux/ubuntulinux/](url)

**Comment by thaJeztah** [comment] 2016-05-25 22:09
This looks like a duplicate of https://github.com/docker/docker/issues/22507, Although I don't think we managed to find a cause there. Ubuntu 14.04 is a popular choice for installing Docker, so I wonder what's different in your setup that results in docker not starting.

Can you check if https://github.com/docker/docker/issues/22507 looks the same? If it does, can you close this issue, and continue the discussion over there (then we can keep the discussion central)

**Comment by HackToday** [comment] 2016-05-26 00:09
could we strace to find what cause that to timeout ?

**Comment by ajspencer** [comment] 2016-06-14 18:47
For anyone following this, I posted on #22507 with the same issue.

**Comment by Sridarshan** [comment] 2016-06-15 05:41
I just had to run docker commands as sudo and it worked.

**Closed** 2016-06-15 05:41 UTC

**Comment by BrickXu** [comment] 2016-12-19 03:15
I have the same issue with docker 1.12.1 in the CentOS 7. any suggestions or PR for this issue ?
