### ISSUE TITLE
 runtime: wrong goroutine in newstack

### ISSUE THREAD

**Issue by polym** [docker/docker#24992] opened 2016-07-25 04:45 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.6.0-1.el6.elrepo.x86_64
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.9 GiB
ID: PLY7:QPSP:UQDP:Q36K:FIEK:SU3Z:M7DS:ZFCX:7JET:GD2S:AF55:ELJM
Docker Root Dir: /disk/ssd1/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional information you deem important (e.g. issue happens only occasionally):**

```
runtime: newstack called from g=859530878464
        m=0xc8206e6000 m->curg=0x0 m->g0=0xc8206e8180 m->gsignal=0xc8206e8000
runtime.systemstack(0xc820046a30)
        /usr/local/go/src/runtime/asm_amd64.s:239 +0x3c
runtime.writebarrierptr_nostore1(0xc820046af8, 0x17da630)
        /usr/local/go/src/runtime/mbarrier.go:118 +0x71
runtime.writebarrierptr(0xc820046af8, 0x17da630)
        /usr/local/go/src/runtime/mbarrier.go:137 +0x4b
runtime.printstring(0x17da630, 0xd)
        /usr/local/go/src/runtime/print1.go:214 +0x194
runtime.throw(0x19b1840, 0x2c)
        /usr/local/go/src/runtime/panic.go:521 +0x22
runtime.badsystemstack()
        /usr/local/go/src/runtime/stubs.go:63 +0x2c
runtime.systemstack(0xc820046b60)
        /usr/local/go/src/runtime/asm_amd64.s:239 +0x3c
runtime.writebarrierptr_nostore1(0xc820046c28, 0x17da630)
        /usr/local/go/src/runtime/mbarrier.go:118 +0x71
runtime.writebarrierptr(0xc820046c28, 0x17da630)
        /usr/local/go/src/runtime/mbarrier.go:137 +0x4b
runtime.printstring(0x17da630, 0xd)
        /usr/local/go/src/runtime/print1.go:214 +0x194
runtime.throw(0x19b1840, 0x2c)
        /usr/local/go/src/runtime/panic.go:521 +0x22
runtime.badsystemstack()
        /usr/local/go/src/runtime/stubs.go:63 +0x2c
runtime.systemstack(0xc820046c90)
        /usr/local/go/src/runtime/asm_amd64.s:239 +0x3c
runtime.writebarrierptr_nostore1(0xc820046d58, 0x17da630)
        /usr/local/go/src/runtime/mbarrier.go:118 +0x71
runtime.writebarrierptr(0xc820046d58, 0x17da630)
        /usr/local/go/src/runtime/mbarrier.go:137 +0x4b
runtime.printstring(0x17da630, 0xd)
        /usr/local/go/src/runtime/print1.go:214 +0x194
runtime.throw(0x19b1840, 0x2c)
        /usr/local/go/src/runtime/panic.go:521 +0x22
runtime.badsystemstack()
        /usr/local/go/src/runtime/stubs.go:63 +0x2c
runtime.systemstack(0xc820046dc0)
        /usr/local/go/src/runtime/asm_amd64.s:239 +0x3c
runtime.writebarrierptr_nostore1(0xc820046e88, 0x17da630)
        /usr/local/go/src/runtime/mbarrier.go:118 +0x71
runtime.writebarrierptr(0xc820046e88, 0x17da630)
        /usr/local/go/src/runtime/mbarrier.go:137 +0x4b
runtime.printstring(0x17da630, 0xd)
        /usr/local/go/src/runtime/print1.go:214 +0x194
runtime.throw(0x19b2440, 0x2a)
        /usr/local/go/src/runtime/panic.go:521 +0x22
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.readgstatus(0x0, 0x227bc28)
        /usr/local/go/src/runtime/proc1.go:248 +0x2e
runtime.gopark(0x1adf6f0, 0xc8206e6000, 0x18da0a0, 0x12, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:174 +0x50
runtime.gcBgMarkWorker(0xc820026a00)
        /usr/local/go/src/runtime/mgc.go:1289 +0xf7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
fatal error: runtime: wrong goroutine in newstack
```

Install docker with official binary. What can I do more?

**Comment by thaJeztah** [comment] 2016-07-25 12:31
What distribution are you running on? And when did you run into this issue (what steps to reproduce?)

**Comment by polym** [comment] 2016-07-28 06:55
Sorry for delay. 

```
cat /etc/redhat-release
CentOS release 6.7 (Final)
```

**Comment by polym** [comment] 2016-07-28 07:02
Install Docker using this package https://get.docker.com/builds/Linux/x86_64/docker-1.11.2.tgz.

**Comment by thaJeztah** [comment] 2016-07-28 07:47
CentOS 6 is no longer supported, you need to upgrade to version 7.x.

I'm closing this issue because this is not on a supported platform, but comment if you're still able to reproduce this after upgrading to 7, and installing using the yum packages (see https://docs.docker.com/engine/installation/linux/centos/)

**Closed by thaJeztah** 2016-07-28 07:47 UTC
Labels: status/more-info-needed, version/1.11
