### ISSUE TITLE
[question] Is it possible to know if a script is running inside a docker container and, if that is the case, what is the container ID/NAME? 

### ISSUE THREAD

**Issue by ninrod** [docker/docker#26102] opened 2016-08-29 11:47 UTC
I have a script that can be run anywhere, but sometimes it is run inside a docker container. If the script is inside a docker container, I must know that and I must also know it's container name/ID to treat some edge case scenarios. 

Is that a way to query that information? 

thanks in advance.

**Comment by cpuguy83** [comment] 2016-08-29 13:49
Not really...

Realistically if you know your way around you could probably find out that it is being run in a container at the very least, but cannot find out container ID or name reliably.

In general though, being containerized should be transparent to the things running in the container, or else it is likely to cause problems... and likewise applications shouldn't care that they are in a container.

Closing because this is not really an issue.
If you'd like to discuss further, please see #docker on IRC or forums.docker.com

Thanks!

**Closed by cpuguy83** 2016-08-29 13:49 UTC

**Comment by ninrod** [comment] 2016-08-29 15:29
In my case I should care because I'd like to spin up a container from inside another sibling container. In this scenario, if I want to define mountpoint with the `-v` option, the correct folder path should be queried from the host, not from the container that is spinning up another container.

**Comment by cpuguy83** [comment] 2016-08-29 15:31
@ninrod In such a case that you need it (and I'd argue you should probably tell the script what it needs rather than trying to infer it), there is this issue: https://github.com/docker/docker/issues/8427

The issue is old, but is actively being worked on.

**Comment by ninrod** [comment] 2016-10-13 19:55
@cpuguy83 the problem is that I cannot pass just a relative folder to the docker command `-v` option, right? 

The problem I have is that I have directory where lies a docker-run script and a `scripts-folder`. I need to mount the scripts-foder using the `-v` option. But I can't just specify `./scripts-folder` because `./scripts-folder` is a relative path and docker only accepts full-paths as `-v` arguments, right? 

My problem arises because I have this folder gitcloned in different docker images and vagrant machines. So I never know what is the real absolute path of the `./scripts-folder`. 

Makes sense?

**Comment by LK4D4** [comment] 2016-10-13 19:57
@ninrod there is `/.dockerenv` file in each docker container. At least on linux.
