### ISSUE TITLE
New embedded DNS server doesn't answer (times out)

### ISSUE THREAD

**Issue by realulim** [docker/docker#20029] opened 2016-02-05 14:51 UTC
I have a setup with two containers and a user-defined network, which I create like this:
docker network create --driver=bridge my-net
Both containers run in this network via the "--net my-net --name my-name" command-line switch.
In Docker 1.9 they could see each other (via /etc/hosts), now in Docker 1.10 they can't (via the embedded DNS server).
When I log in to one of my containers I see this in resolv.conf:

search some.local.domain.com
nameserver 127.0.0.11
options ndots:0

I can ping 127.0.0.11, but it doesn't answer to DNS queries:

host www.google.com
;; connection timed out; no servers could be reached

It appears to have nothing to do with Google or Internet access, because it also times out when I look for "my-name", which is the containers own name that previously was listed in /etc/hosts, but isn't anymore.

**Comment by realulim** [comment] 2016-02-05 15:06
I'm sorry, but I'm a new user. Will try to fill out the template here:

`docker version`:
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:04:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:04:33 2016
 OS/Arch:      linux/amd64

`docker info`:
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 29
Server Version: 1.10.0
Storage Driver: devicemapper
 Pool Name: docker-253:1-399605-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.861 GB
 Data Space Total: 107.4 GB
 Data Space Available: 35.95 GB
 Metadata Space Used: 5.104 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.3.4-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58 GiB

`uname -a`:
Linux [deleted hostname for privacy] 4.3.4-200.fc22.x86_64 #1 SMP Mon Jan 25 13:37:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Physical Dell workstation.

How reproducible:
Always. My setup worked under Docker 1.9 and when I upgraded, it stopped working.

Steps to Reproduce:
1. docker network create --driver=bridge my-net
2. docker run -it --net my-net --name my-name fedora:22 /bin/bash
3. host my-name


Actual Results:
I am getting no answer and after a few seconds a timeout. Same happens with dig or other tools querying the DNS.

Expected Results:
Getting a DNS result.

Additional info:

**Comment by thaJeztah** [comment] 2016-02-05 16:53
This could be a duplicate of https://github.com/docker/docker/issues/20026; we've found an issue with the embedded DNS not working properly in combination with firewalld. Can you try if (temporarily) stopping firewalld solves this for you?

**Comment by mavenugo** [comment] 2016-02-05 17:00
@realulim @thaJeztah yes this is a duplicate of #20026.

**Comment by icecrime** [comment] 2016-02-05 17:21
Thanks a lot for filing a detailed issue @realulim! Let's close this one and continue the discussion on #20026.

**Comment by thaJeztah** [comment] 2016-02-05 17:21
Thanks @realulim for reporting; I'll go ahead and close this one in favor of https://github.com/docker/docker/issues/20026

**Closed by thaJeztah** 2016-02-05 17:21 UTC
Labels: group/networking, kind/bug
