### ISSUE TITLE
fork/exec /mnt/docker/init/dockerinit-1.5.0: cannot allocate memory

### ISSUE THREAD

**Issue by bmurphy1976** [docker/docker#10917] opened 2015-02-20 16:22 UTC
We are running into a problem on one of our servers.  We are frequently getting this error:

```
HTTP Error: statusCode=500 Cannot start container <<CONTAINER NAME>>: fork/exec /mnt/docker/init/dockerinit-1.5.0: cannot allocate memory
```

The problem may be related to us having 15 containers already created on this server and we run them as cron jobs every 1 or 5 minutes ("docker start --attach").  It takes about 18 hours before docker starts issuing memory errors.  At that point we have to restart the docker daemon to address the issue.  

Memory utilization on the instance does not appear to be a problem.  There's usually a couple hundred megabytes of ram available as reported by free.

This happens for both docker 1.4.1 and 1.5.0.  The host operating system is ubuntu 14.04 but the containers are ubuntu 12.04.

**Comment by phemmer** [comment] 2015-02-20 16:40
Couple hundred MB is fairly low, but this could also be a fragmentation issue. I'd look at `/proc/buddyinfo` and ensure you have some of the higher order page sizes available.

**Comment by bmurphy1976** [comment] 2015-02-20 16:46
At the moment free shows about 450mb available and 450mb available in cache so if I understand things correctly that should be able 1gb available for application use (this is on a server with 4gb/ram).

I'll check buddyinfo and memory usage the next time this occurs which should be sometime this evening based on past experience.

**Comment by jfrazelle** [comment] 2015-02-20 18:28
closing this was a duplicate of  #8539 and please see why solution here https://github.com/docker/docker/issues/8539#issuecomment-75291557

**Closed by jfrazelle** 2015-02-20 18:28 UTC
