### ISSUE TITLE
Timing Issue Starting Container

### ISSUE THREAD

**Issue by psycotica0** [docker/docker#8914] opened 2014-11-02 14:23 UTC
I'm sorry if this is a duplicate, but I haven't been able to find anything by searching.

I'm running Murmur, the mumble server, in a container and I found that if I ran it directly, it would never open the listening connections, and I couldn't connect to it from outside.
If, though, I instead ran

    sleep 2
    exec murmurd -ini /data/murmur.ini -fg -v

instead (the only difference being the `sleep`), then it would work.

This confuses me. Is it possible that the container is being started before things are ready or something?

I'm attaching my Dockerfile and murmur.ini, for people.

Dockerfile

    FROM ubuntu
    MAINTAINER Christopher Vollick <0@psycoti.ca>
    EXPOSE 6502
    EXPOSE 64738
    
    ADD . /stuff
    RUN /stuff/provision.sh
    
    
    CMD ["/usr/sbin/murmurd", "-ini", "/data/murmur.ini", "-fg", "-v"]

murmur.ini

    database=/data/murmur.sqlite
    uname=root

**Comment by jfrazelle** [comment] 2015-02-26 02:34
can you try with the latest version of docker @psycotica0

**Comment by jfrazelle** [comment] 2015-03-02 17:26
closing as duplicate of https://github.com/docker/docker/issues/6549

**Closed by jfrazelle** 2015-03-02 17:26 UTC
