### ISSUE TITLE
TAR bug: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gm42** [docker/docker#23368] opened 2016-06-08 08:56 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
Images: 59
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-264228-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.509 GB
 Data Space Total: 107.4 GB
 Data Space Available: 17.52 GB
 Metadata Space Used: 7.07 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.5-15.26.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
CPUs: 2
Total Memory: 7.8 GiB
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

It's AWS EC2, but does not matter for the reasons behind this bug.

**Steps to reproduce the issue:**

I guess it was the building of some image:
```
time="2016-06-08T08:08:44.303191509Z" level=info msg="POST /v1.21/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=quay.io%2Fsomething%2Fsomething2%3Av29.4&ulimits=null" 
```

**Describe the results you received:**

```
time="2016-06-08T08:08:44.303191509Z" level=info msg="POST /v1.21/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=quay.io%2Fsomething%2Fsomething2%3Av29.4&ulimits=null" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x9ff2df]

goroutine 2835 [running]:
archive/tar.mergePAX(0x0, 0xc20b4c81b0, 0x0, 0x0)
	/usr/lib/golang/src/archive/tar/reader.go:218 +0x8af
archive/tar.(*Reader).Next(0xc208d66000, 0xc209520000, 0x0, 0x0)
	/usr/lib/golang/src/archive/tar/reader.go:112 +0x521
github.com/docker/docker/pkg/tarsum.(*tarSum).Read(0xc20964cd00, 0xc20922c000, 0x8000, 0x8000, 0xc20b4c5358, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/pkg/tarsum/tarsum.go:221 +0x5d4
bufio.(*Reader).Read(0xc20c067ce0, 0xc20922c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:164 +0x13a
github.com/docker/docker/pkg/ioutils.(*readCloserWrapper).Read(0xc20a747760, 0xc20922c000, 0x8000, 0x8000, 0x800, 0x0, 0x0)
	<autogenerated>:1 +0x89
io.Copy(0x7fc44f7c93d8, 0xc208e36320, 0x7fc44cb31b18, 0xc20a747760, 0xab89600, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:362 +0x1f6
os/exec.func·002(0x0, 0x0)
	/usr/lib/golang/src/os/exec/exec.go:179 +0x93
os/exec.func·004(0xc20a7477a0)
	/usr/lib/golang/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/lib/golang/src/os/exec/exec.go:329 +0xb6d

goroutine 1 [chan receive, 82 minutes]:
main.(*DaemonCli).CmdDaemon(0xc2084ff2e0, 0xc20800a020, 0x2, 0x2, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/docker/daemon.go:308 +0x20a7
reflect.callMethod(0xc2084d5f50, 0xc208c23ce8)
	/usr/lib/golang/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0x2, 0x2, 0x1, 0xc2084d5f50, 0x0, 0x0, 0xc2084d5f50, 0x0, 0x4e169f, ...)
	/usr/lib/golang/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc2084d5e90, 0xc20800a010, 0x3, 0x3, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/cli/cli.go:89 +0x38e
main.main()
	/builddir/build/BUILD/docker-1.9.1/docker/docker.go:65 +0x418

goroutine 5 [syscall, 83 minutes]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 83 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [chan receive, 83 minutes]:
github.com/docker/docker/api/server.(*Server).ServeAPI(0xc20800b8c0, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/api/server/server.go:94 +0x1b6
main.func·007()
	/builddir/build/BUILD/docker-1.9.1/docker/daemon.go:255 +0x3b
created by main.(*DaemonCli).CmdDaemon
	/builddir/build/BUILD/docker-1.9.1/docker/daemon.go:261 +0x1571

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0xc208092f40, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208092f40, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208092ee0, 0x0, 0x7fc44f7c9500, 0xc20bf6c038)
	/usr/lib/golang/src/net/fd_unix.go:419 +0x40b
net.(*UnixListener).AcceptUnix(0xc208506260, 0xc20a747220, 0x0, 0x0)
	/usr/lib/golang/src/net/unixsock_posix.go:282 +0x56
net.(*UnixListener).Accept(0xc208506260, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/unixsock_posix.go:293 +0x4c
github.com/docker/docker/pkg/listenbuffer.(*defaultListener).Accept(0xc208506280, 0x0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:71 +0x67
net/http.(*Server).Serve(0xc2080526c0, 0x7fc44cb13490, 0xc208506280, 0x0, 0x0)
	/usr/lib/golang/src/net/http/server.go:1728 +0x92
github.com/docker/docker/api/server.(*HTTPServer).Serve(0xc208506420, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/api/server/server.go:113 +0x4d
github.com/docker/docker/api/server.func·006(0xc208506420)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/api/server/server.go:86 +0x163
created by github.com/docker/docker/api/server.(*Server).ServeAPI
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/api/server/server.go:90 +0x144

goroutine 11 [chan receive, 83 minutes]:
github.com/docker/docker/daemon.func·030()
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/daemon/debugtrap_unix.go:17 +0x5c
created by github.com/docker/docker/daemon.setupDumpStackTrap
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/daemon/debugtrap_unix.go:20 +0x18e

goroutine 16 [select]:
github.com/docker/libnetwork.(*controller).watchLoop(0xc2080a0790)
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/docker/libnetwork/store.go:398 +0x13f
created by github.com/docker/libnetwork.(*controller).startWatch
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/docker/libnetwork/store.go:412 +0xf0

goroutine 20 [IO wait, 83 minutes]:
net.(*pollDesc).Wait(0xc208011020, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011020, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readMsg(0xc208010fc0, 0xc208757a30, 0x10, 0x10, 0xc208767220, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/fd_unix.go:296 +0x54e
net.(*UnixConn).ReadMsgUnix(0xc208040620, 0xc208757a30, 0x10, 0x10, 0xc208767220, 0x1000, 0x1000, 0x51, 0xc2087577f4, 0x4, ...)
	/usr/lib/golang/src/net/unixsock_posix.go:147 +0x167
github.com/godbus/dbus.(*oobReader).Read(0xc208767200, 0xc208757a30, 0x10, 0x10, 0xc208767200, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/godbus/dbus/transport_unix.go:21 +0xc5
io.ReadAtLeast(0x7fc44cb14020, 0xc208767200, 0xc208757a30, 0x10, 0x10, 0x10, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:298 +0xf1
io.ReadFull(0x7fc44cb14020, 0xc208767200, 0xc208757a30, 0x10, 0x10, 0x51, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:316 +0x6d
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc208725d70, 0xc20874e420, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/godbus/dbus/transport_unix.go:85 +0x1bf
github.com/godbus/dbus.(*Conn).inWorker(0xc20873eea0)
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/godbus/dbus/conn.go:248 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/godbus/dbus/auth.go:118 +0xe84

goroutine 21 [chan receive, 83 minutes]:
github.com/godbus/dbus.(*Conn).outWorker(0xc20873eea0)
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/godbus/dbus/conn.go:370 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/godbus/dbus/auth.go:119 +0xea1

goroutine 22 [chan receive, 83 minutes]:
github.com/docker/libnetwork/iptables.signalHandler()
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/docker/libnetwork/iptables/firewalld.go:92 +0x57
created by github.com/docker/libnetwork/iptables.FirewalldInit
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/docker/libnetwork/iptables/firewalld.go:48 +0x185

goroutine 34 [IO wait, 83 minutes]:
net.(*pollDesc).Wait(0xc208763b80, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208763b80, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208763b20, 0x0, 0x7fc44f7c9500, 0xc20879a140)
	/usr/lib/golang/src/net/fd_unix.go:419 +0x40b
net.(*UnixListener).AcceptUnix(0xc20878cba0, 0x10, 0x0, 0x0)
	/usr/lib/golang/src/net/unixsock_posix.go:282 +0x56
net.(*UnixListener).Accept(0xc20878cba0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/unixsock_posix.go:293 +0x4c
github.com/docker/libnetwork.(*controller).acceptClientConnections(0xc2080a0790, 0xc208763ab0, 0x63, 0x7fc44cb12498, 0xc20878cba0)
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/docker/libnetwork/sandbox_externalkey.go:138 +0x87
created by github.com/docker/libnetwork.(*controller).startExternalKeyListener
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/docker/libnetwork/sandbox_externalkey.go:132 +0x295

goroutine 57 [chan receive, 83 minutes]:
database/sql.(*DB).connectionOpener(0xc208795180)
	/usr/lib/golang/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/lib/golang/src/database/sql/sql.go:452 +0x31c

goroutine 58 [chan receive]:
github.com/docker/docker/daemon.(*statsCollector).run(0xc20882f050)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/daemon/stats_collector_unix.go:93 +0xb2
created by github.com/docker/docker/daemon.newStatsCollector
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/daemon/stats_collector_unix.go:33 +0x116

goroutine 59 [chan receive, 2 minutes]:
github.com/docker/docker/daemon.(*Daemon).execCommandGC(0xc20806f180)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/daemon/exec.go:300 +0x8c
created by github.com/docker/docker/daemon.NewDaemon
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/daemon/daemon.go:827 +0x2dbc

goroutine 60 [chan receive, 82 minutes]:
github.com/docker/docker/pkg/signal.func·002()
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/pkg/signal/trap.go:29 +0x8f
created by github.com/docker/docker/pkg/signal.Trap
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/pkg/signal/trap.go:55 +0x250

goroutine 2836 [syscall]:
syscall.Syscall(0x0, 0x10, 0xc208cdd200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x10, 0xc208cdd200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x10, 0xc208cdd200, 0x200, 0x200, 0xc208c915a0, 0x0, 0x0)
	/usr/lib/golang/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc208e36340, 0xc208cdd200, 0x200, 0x200, 0xc208cdd200, 0x0, 0x0)
	/usr/lib/golang/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc208e36340, 0xc208cdd200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/os/file.go:95 +0x91
bytes.(*Buffer).ReadFrom(0xc20978ae00, 0x7fc44f7c94b0, 0xc208e36340, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bytes/buffer.go:169 +0x25a
io.Copy(0x7fc44cb136c0, 0xc20978ae00, 0x7fc44f7c94b0, 0xc208e36340, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:358 +0x13d
os/exec.func·003(0x0, 0x0)
	/usr/lib/golang/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc20a747800)
	/usr/lib/golang/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/lib/golang/src/os/exec/exec.go:329 +0xb6d

goroutine 505 [select]:
github.com/docker/libnetwork/osl.removeUnusedPaths()
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/docker/libnetwork/osl/namespace_linux.go:73 +0x48b
created by github.com/docker/libnetwork/osl.createBasePath
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/docker/libnetwork/osl/namespace_linux.go:58 +0xb1

goroutine 2834 [syscall]:
syscall.Syscall6(0x3d, 0x7886, 0xc209188b6c, 0x0, 0xc2097aa990, 0x0, 0x0, 0xc20bf6c8a0, 0x7fc43c2ec6e8, 0x1)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x7886, 0xc209188b6c, 0x0, 0xc2097aa990, 0x90, 0x0, 0x0)
	/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x7886, 0xc209188bb4, 0x0, 0xc2097aa990, 0x8, 0x0, 0x0)
	/usr/lib/golang/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc20a747980, 0x624964, 0x0, 0x0)
	/usr/lib/golang/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc20a747980, 0xc209188c88, 0x0, 0x0)
	/usr/lib/golang/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc20806eb40, 0x0, 0x0)
	/usr/lib/golang/src/os/exec/exec.go:364 +0x23c
github.com/docker/docker/pkg/chrootarchive.invokeUnpack(0x7fc44cb31b18, 0xc20a747760, 0xc20ca22ea0, 0x2b, 0xc2097aa750, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/pkg/chrootarchive/archive_unix.go:82 +0x810
github.com/docker/docker/pkg/chrootarchive.untarHandler(0x7fc44c0da780, 0xc20964cd00, 0xc20ca22ea0, 0x2b, 0xc2097aa750, 0x7fc44c0da701, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/pkg/chrootarchive/archive.go:61 +0x411
github.com/docker/docker/pkg/chrootarchive.Untar(0x7fc44c0da780, 0xc20964cd00, 0xc20ca22ea0, 0x2b, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/pkg/chrootarchive/archive.go:21 +0x67
github.com/docker/docker/builder.MakeTarSumContext(0x7fc44c0d6ef8, 0xc20df98e00, 0x0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/builder/tarsum.go:107 +0x36e
github.com/docker/docker/daemon/daemonbuilder.DetectContextFromRemoteURL(0x7fc44cb2c9b8, 0xc20df98e00, 0x0, 0x0, 0xc20978ac40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/daemon/daemonbuilder/builder.go:211 +0x12d
github.com/docker/docker/api/server/router/local.(*router).postBuild(0xc2088408a0, 0x7fc44cb23b68, 0xc20ca22cc0, 0x7fc44cb23b30, 0xc20a41e280, 0xc20964cb60, 0xc20ca22ba0, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/api/server/router/local/image.go:392 +0x15a5
github.com/docker/docker/api/server/router/local.*router.(github.com/docker/docker/api/server/router/local.postBuild)·fm(0x7fc44cb23b68, 0xc20ca22cc0, 0x7fc44cb23b30, 0xc20a41e280, 0xc20964cb60, 0xc20ca22ba0, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/api/server/router/local/local.go:124 +0x7b
github.com/docker/docker/api/server.func·004(0x7fc44cb23b68, 0xc20ca22cc0, 0x7fc44cb23b30, 0xc20a41e280, 0xc20964cb60, 0xc20ca22ba0, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/api/server/middleware.go:87 +0x7c7
github.com/docker/docker/api/server.func·003(0x7fc44f7c9a50, 0xc208032f28, 0x7fc44cb23b30, 0xc20a41e280, 0xc20964cb60, 0xc20ca22ba0, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/api/server/middleware.go:66 +0x10e
github.com/docker/docker/api/server.func·002(0x7fc44f7c9a50, 0xc208032f28, 0x7fc44cb23b30, 0xc20a41e280, 0xc20964cb60, 0xc20ca22ba0, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/api/server/middleware.go:49 +0x47c
github.com/docker/docker/api/server.func·001(0x7fc44f7c9a50, 0xc208032f28, 0x7fc44cb23b30, 0xc20a41e280, 0xc20964cb60, 0xc20ca22ba0, 0x0, 0x0)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/api/server/middleware.go:27 +0x1dc
github.com/docker/docker/api/server.func·007(0x7fc44cb23b30, 0xc20a41e280, 0xc20964cb60)
	/builddir/build/BUILD/docker-1.9.1/_build/src/github.com/docker/docker/api/server/server.go:156 +0x265
net/http.HandlerFunc.ServeHTTP(0xc2088d15e0, 0x7fc44cb23b30, 0xc20a41e280, 0xc20964cb60)
	/usr/lib/golang/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208836a00, 0x7fc44cb23b30, 0xc20a41e280, 0xc20964cb60)
	/builddir/build/BUILD/docker-1.9.1/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2080526c0, 0x7fc44cb23b30, 0xc20a41e280, 0xc20964cb60)
	/usr/lib/golang/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20a41e1e0)
	/usr/lib/golang/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:1751 +0x35e
```

**Comment by runcom** [comment] 2016-06-08 08:58
can you try out newer docker versions, it should have been fixed

**Comment by gm42** [comment] 2016-06-08 09:01
@runcom maybe not, as I need to run same version across the board..

but this is the default shipped with the AMI Linux distro

I could not find a bug with same error, @runcom do you by chance have an issue ref?

**Comment by gm42** [comment] 2016-06-08 09:04
Possibly related to #11168? Somebody will shed light I guess.

**Comment by justincormack** [comment] 2016-06-08 13:39
Do you have a way to replicate this?

**Comment by AkihiroSuda** [comment] 2016-06-14 04:23
The issue seems resolved in recent Go runtimes?
https://github.com/golang/go/issues/11168

**Comment by thaJeztah** [comment] 2016-06-14 08:54
Thanks @AkihiroSuda, looks to be resolved in Go indeed. I'll close this issue because we currently don't have a way to reproduce this, and it's likely that this was resolved in the current version, but happy to reopen of it's still reproducible on the current release

**Closed by thaJeztah** 2016-06-14 08:54 UTC
Labels: version/1.9
