### ISSUE TITLE
Docker 1.9.1 not mounting Volume files

### ISSUE THREAD

**Issue by digitaldavenyc** [docker/docker#18997] opened 2015-12-30 15:22 UTC
@thaJeztah as per your request here is a new ticket to track this issue. Let me know if there is any other information I can supply that would be helpful.

I'm trying to mount my source files to a directory in docker located at /var/dynamo. I'd like to be able to run Docker locally and use my local files as I am working.

with the run command: 

    docker run -v $(pwd):/var/dynamo -d -t -p 8001:8001 --name dynamo davesrepo/dynamo

my working directory is inside my Users directory.

with my  **Dockerfile** 

    FROM python:3.5.1
    WORKDIR /var/dynamo
    RUN pip3 install tornado
    EXPOSE 8001

However, when I bash into the container `docker exec -it dynamo /bin/bash` and run `ls -la` the directory **is empty!**

    root@7d3d338891aa:/var/dynamo# ls -la
    total 4
    drwxr-xr-x  2 root root   40 Dec 29 03:37 .
    drwxr-xr-x 24 root root 4096 Dec 29 03:36 ..

Running `docker inspect dynamo` shows the directory mounted properly

    [
    {
        "Id": "7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a",
        "Created": "2015-12-29T03:37:01.416445958Z",
        "Path": "python3",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1314,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2015-12-29T03:37:01.516253705Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "19697c9b5c7561b113d817821280971f063ea0187c82343c0832348fb6863c9a",
        "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a/resolv.conf",
        "HostnamePath": "/mnt/sda1/var/lib/docker/containers/7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a/hostname",
        "HostsPath": "/mnt/sda1/var/lib/docker/containers/7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a/hosts",
        "LogPath": "/mnt/sda1/var/lib/docker/containers/7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a/7d3d338891aae32e001a3bb31d6be17802d238526830396472b011599a97212a-json.log",
        "Name": "/dynamo",
        "RestartCount": 0,
        "Driver": "aufs",
        "ExecDriver": "native-0.2",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/Users/dave/Sites/davesrepo/dynamo:/var/dynamo"
            ],
            "ContainerIDFile": "",
            "LxcConf": [],
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "KernelMemory": 0,
            "CpuShares": 0,
            "CpuPeriod": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "CpuQuota": 0,
            "BlkioWeight": 0,
            "OomKillDisable": false,
            "MemorySwappiness": -1,
            "Privileged": false,
            "PortBindings": {
                "8001/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8001"
                    }
                ]
            },
            "Links": null,
            "PublishAllPorts": false,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "VolumesFrom": null,
            "Devices": [],
            "NetworkMode": "default",
            "IpcMode": "",
            "PidMode": "",
            "UTSMode": "",
            "CapAdd": null,
            "CapDrop": null,
            "GroupAdd": null,
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "SecurityOpt": null,
            "ReadonlyRootfs": false,
            "Ulimits": null,
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "CgroupParent": "",
            "ConsoleSize": [
                0,
                0
            ],
            "VolumeDriver": ""
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Source": "/Users/dave/Sites/davesrepo/dynamo",
                "Destination": "/var/dynamo",
                "Mode": "",
                "RW": true
            }
        ],
        "Config": {
            "Hostname": "7d3d338891aa",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8001/tcp": {}
            },
            "Tty": true,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "APP_ENV=development",
                "PYTHONPATH=$PYTHONPATH:/var/dynamo",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "PYTHON_VERSION=3.5.1",
                "PYTHON_PIP_VERSION=7.1.2"
            ],
            "Cmd": [
                "python3"
            ],
            "Image": "davesrepo/dynamo",
            "Volumes": null,
            "WorkingDir": "/var/dynamo",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {},
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "71d99a7d11908a9d1c0156fd33eb3f0ff5ef9f6697bb77103fe2caa1cf488530",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8001/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8001"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/71d99a7d1190",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "1cc99b0de89700368f31b43248c90ea45cec756712a2bd2ba2dc57293a5d0a72",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "EndpointID": "1cc99b0de89700368f31b43248c90ea45cec756712a2bd2ba2dc57293a5d0a72",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
    ]

Docker version is 1.9.1 and running on OSX 10.10.5

**Comment by digitaldavenyc** [comment] 2015-12-30 15:26
@GordonTheTurtle did I miss anything?

**Comment by thaJeztah** [comment] 2015-12-30 15:29
@digitaldavenyc can you add the output of `docker info` and `docker version`, just to be sure?

If I understood correctly, downgrading to docker 1.6 solved your issue?

**Comment by digitaldavenyc** [comment] 2015-12-30 15:38
@thaJeztah Correct downgrading to docker 1.6 fixed the issue.

Since I downgraded I'll have to uninstall and upgrade again. I will run this again later tonight when I'm back on the machine with the issue.

**Comment by thaJeztah** [comment] 2015-12-30 17:14
Thanks @digitaldavenyc!

**Comment by groovemaps** [comment] 2015-12-31 03:17
I did some additional testing and it seems that if you try to move the Virtualbox share folder outside of the /Users directory, it totally destroys Volume mounting, even reverting back to the /Users folder doesn't work. 

Steps to reproduce:

1. Install docker 1.9.1
2. `docker-machine create --driver virtualbox dev`
3. Change shared folder location to outside /Users directory in **Virtualbox**
4. `docker-machine restart dev`
5. `eval "$(docker-machine env dev)"`
6. `docker build -t davesrepo/dynamo -f ./Dockerfile .`
7. `docker run -v $(pwd):/var/dynamo -d -t -p 8001:8001 --env-file ./dynamo.env --name dynamo davesrepo/dynamo`
8. `docker exec -it dynamo /bin/bash`

    root@235196b7fcd6:/var/dynamo# ls
    root@235196b7fcd6:/var/dynamo#

Now this is sorta expected, I tried to move the share folder outside of the /Users directory, that didn't work. So let's try to revert it back to the /Users directory

1. `docker stop dynamo`
2. `docker rm dynamo`
3. Revert shared folder to /Users/dave directory
4. `docker-machine restart dev`
5. `eval "$(docker-machine env dev)"`
6. `docker build -t davesrepo/dynamo -f ./Dockerfile .`
7. `docker run -v $(pwd):/var/dynamo -d -t -p 8001:8001 --env-file ./dynamo.env --name dynamo davesrepo/dynamo`
8. `docker exec -it dynamo /bin/bash`

`root@235196b7fcd6:/var/dynamo# ls`
`root@235196b7fcd6:/var/dynamo#`

No files after reverting to /Users folder.

And this I think is the bug, if you try to move the /Users directory in Virtualbox, Docker Volume mounting doesn't work anymore, even if you try to revert. 

The only way to fix the issue is to delete the Docker machine and recreate it.

    Daves-MacBook-Pro:dynamo dave$ docker version
    Client:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.3
     Git commit:   a34a1d5
     Built:        Fri Nov 20 17:56:04 UTC 2015
     OS/Arch:      darwin/amd64
    
    Server:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.3
     Git commit:   a34a1d5
     Built:        Fri Nov 20 17:56:04 UTC 2015
     OS/Arch:      linux/amd64

 

    Daves-MacBook-Pro:dynamo dave$ docker info
    Containers: 1
    Images: 17
    Server Version: 1.9.1
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 19
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.1.13-boot2docker
    Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
    CPUs: 1
    Total Memory: 996.2 MiB
    Name: dev
    ID: Z32E:B2D3:HS74:KDSU:CQ5V:7Q5U:ZMUW:LHY7:KUJ7:S2XK:HHEZ:KZS2
    Debug mode (server): true
     File Descriptors: 15
     Goroutines: 28
     System Time: 2015-12-31T03:15:06.906277246Z
     EventsListeners: 0
     Init SHA1:
     Init Path: /usr/local/bin/docker
     Docker Root Dir: /mnt/sda1/var/lib/docker
    Labels:
     provider=virtualbox

**Comment by groovemaps** [comment] 2015-12-31 03:17
Steps to fix:

1. `docker-machine stop dev`
2. `docker-machine rm dev`
3. `docker-machine create --driver virtualbox dev`
4. `eval "$(docker-machine env dev)"
5. `docker build -t davesrepo/dynamo -f ./Dockerfile .`
6. `docker run -v $(pwd):/var/dynamo -d -t -p 8001:8001 --env-file ./dynamo.env --name dynamo davesrepo/dynamo`
7. `docker exec -it dynamo /bin/bash`
8. `ls`

`root@42f9e47fa2de:/var/dynamo# ls`
`Dockerfile  README.md  __init__.py  __pycache__  bin  config.ini  requirements.txt  seed.sql  tests `

Success!

**Comment by groovemaps** [comment] 2015-12-31 03:18
@thaJeztah I don't know if you consider this a bug or not. It seems to be at least partly an issue with Virtualbox.

**Comment by digitaldavenyc** [comment] 2015-12-31 04:59
I did some additional testing and it seems that if you try to move the Virtualbox share folder outside of the /Users directory, it totally destroys Volume mounting, even reverting back to the /Users folder doesn't work. 

Steps to reproduce:

1. Install docker 1.9.1
2. `docker-machine create --driver virtualbox dev`
3. Change shared folder location to outside /Users directory in **Virtualbox**
4. `docker-machine restart dev`
5. `eval "$(docker-machine env dev)"`
6. `docker build -t davesrepo/dynamo -f ./Dockerfile .`
7. `docker run -v $(pwd):/var/dynamo -d -t -p 8001:8001 --env-file ./dynamo.env --name dynamo davesrepo/dynamo`
8. `docker exec -it dynamo /bin/bash`

    root@235196b7fcd6:/var/dynamo# ls
    root@235196b7fcd6:/var/dynamo#

Now this is sorta expected, I tried to move the share folder outside of the /Users directory, that didn't work. So let's try to revert it back to the /Users directory

1. `docker stop dynamo`
2. `docker rm dynamo`
3. Revert shared folder to /Users/dave directory
4. `docker-machine restart dev`
5. `eval "$(docker-machine env dev)"`
6. `docker build -t davesrepo/dynamo -f ./Dockerfile .`
7. `docker run -v $(pwd):/var/dynamo -d -t -p 8001:8001 --env-file ./dynamo.env --name dynamo davesrepo/dynamo`
8. `docker exec -it dynamo /bin/bash`

`root@235196b7fcd6:/var/dynamo# ls`
`root@235196b7fcd6:/var/dynamo#`

No files after reverting to /Users folder.

And this I think is the bug, if you try to move the /Users directory in Virtualbox, Docker Volume mounting doesn't work anymore, even if you try to revert. 

The only way to fix the issue is to delete the Docker machine and recreate it.

    Daves-MacBook-Pro:dynamo dave$ docker version
    Client:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.3
     Git commit:   a34a1d5
     Built:        Fri Nov 20 17:56:04 UTC 2015
     OS/Arch:      darwin/amd64
    
    Server:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.3
     Git commit:   a34a1d5
     Built:        Fri Nov 20 17:56:04 UTC 2015
     OS/Arch:      linux/amd64

 

    Daves-MacBook-Pro:dynamo dave$ docker info
    Containers: 1
    Images: 17
    Server Version: 1.9.1
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 19
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.1.13-boot2docker
    Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
    CPUs: 1
    Total Memory: 996.2 MiB
    Name: dev
    ID: Z32E:B2D3:HS74:KDSU:CQ5V:7Q5U:ZMUW:LHY7:KUJ7:S2XK:HHEZ:KZS2
    Debug mode (server): true
     File Descriptors: 15
     Goroutines: 28
     System Time: 2015-12-31T03:15:06.906277246Z
     EventsListeners: 0
     Init SHA1:
     Init Path: /usr/local/bin/docker
     Docker Root Dir: /mnt/sda1/var/lib/docker
    Labels:
     provider=virtualbox

**Comment by digitaldavenyc** [comment] 2015-12-31 05:00
Steps to fix:

1. `docker-machine stop dev`
2. `docker-machine rm dev`
3. `docker-machine create --driver virtualbox dev`
4. `eval "$(docker-machine env dev)"`
5. `docker build -t davesrepo/dynamo -f ./Dockerfile .`
6. `docker run -v $(pwd):/var/dynamo -d -t -p 8001:8001 --env-file ./dynamo.env --name dynamo davesrepo/dynamo`
7. `docker exec -it dynamo /bin/bash`
8. `ls`

`root@42f9e47fa2de:/var/dynamo# ls`
`Dockerfile  README.md  __init__.py  __pycache__  bin  config.ini  requirements.txt  seed.sql  tests `

Success!

**Comment by digitaldavenyc** [comment] 2015-12-31 05:00
@thaJeztah I don't know if you consider this a bug or not. It seems to be at least partly an issue with Virtualbox. I do consider it a bug since the share folder cannot change, I think at a minimum a warning message should be shown to the user. Ideally there should be a way to change the virtualbox share folder location. Curious to hear your thoughts on it.

[EDIT]: Btw even using a symbolic link will cause volume mounting to fail

**Comment by cpuguy83** [comment] 2015-12-31 14:17
@digitaldavenyc Not sure if it's a bug or a limitation. But in either case, this is not related to Docker itself, but rather machine/boot2docker.

**Comment by digitaldavenyc** [comment] 2015-12-31 15:18
@cpuguy83 do you think it's more appropriate to open a ticket in a different docker repo?

**Comment by cpuguy83** [comment] 2015-12-31 20:16
Yep.

**Comment by digitaldavenyc** [comment] 2016-01-04 18:29
@thaJeztah I opened up another ticket in [docker/machine](https://github.com/docker/machine/issues/2736) since the issue seems to be more related to docker-machine then good ol' docker

**Comment by cpuguy83** [comment] 2016-01-04 18:31
Thanks! Closing.

**Closed by cpuguy83** 2016-01-04 18:31 UTC
Labels: kind/bug

**Comment by thaJeztah** [comment] 2016-01-04 18:42
Thanks @digitaldavenyc!
