### ISSUE TITLE
Docker different proxy based on registry - systemd

### ISSUE THREAD

**Issue by gaborbernat** [docker/docker#28242] opened 2016-11-10 15:50 UTC
Hello, 

According to the documentation here (https://docs.docker.com/engine/admin/systemd/) having different proxies for the official registry and a personal registry is not possible. 

Can you confirm that? And if so would it be possible to make add it? 

What I want is that when:

git pull ubuntu - (use proxy A)
git pull magic.local.address.network/ubuntu - (use proxy B)

Thanks!

**Comment by thaJeztah** [comment] 2016-11-10 16:11
These variables are handled by the Go runtime, as described in that section.

In the source code of the Go runtime, you can find that these env-vars are used through this function; https://golang.org/src/net/http/transport.go?s=9224:9281#L247, and only `NO_PROXY` accepts a comma-separated list of hosts/URLs; https://golang.org/src/net/http/transport.go?s=9224:9281#L1113

These env-variables are fairly standard, so I don't think it can be changed in the Go runtime, without breaking compatibility with other software.

I'll close this issue, because it's not a bug, but hope this answers your question

**Closed by thaJeztah** 2016-11-10 16:11 UTC

**Comment by gaborbernat** [comment] 2016-11-10 16:34
so basically this can't be achieved, thanks anyways!
