### ISSUE TITLE
Data Container volumes saved as images

### ISSUE THREAD

**Issue by owaaa** [docker/docker#7583] opened 2014-08-14 17:44 UTC
It seems that data containers can not be committed as images. This would be very useful for distributing data via a registry. It also seems odd that this class of container would work different than other containers.

**Steps to reproduce:**
`sudo docker run -v /data --name TEST_DATA ubuntu true`
`sudo docker -i -t -rm --volumes-from TEST_DATA ubuntu bash`
*then from container* `echo "test" >> /data/test.txt`
*Verify data is there in a new container* `sudo docker run -i -t -rm --volumes-from TEST_DATA ubuntu bash`
*then from container* `cat /data/test.txt` *//should see "test"*
`sudo docker commit TEST_DATA newtestdata` **//make a new image**
`sudo docker run --name TEST_DATA_NEW newtestdata true` //run the image
`sudo docker run -i -t -rm --volumes-from TEST_DATA_NEW ubuntu bash`
*then  from container* `ls /data/` **//No data is there**

**Environment Details**
$ sudo docker info
Containers: 10
Images: 43
Storage Driver: devicemapper
 Pool Name: docker-202:1-269113-pool
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 2552.6 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 3.8 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.10.42-52.145.amzn1.x86_64

$ sudo docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2
Git commit (client): d84a070/1.1.2
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2
Git commit (server): d84a070/1.1.2

$ uname -a
Linux ip-10-22-0-180 3.10.42-52.145.amzn1.x86_64 #1 SMP Tue Jun 10 23:46:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pykiss** [comment] 2015-01-30 12:12
At least it would be documented that volumes will not be commited

**Comment by devurandom** [comment] 2015-02-23 16:40
I assume all this implies that `docker push` also does not push any data from volumes?

**Comment by wyaeld** [comment] 2015-02-23 19:58
volumes are attached to containers

`docker push` sends images to a registry

The 2 aren't really related.  images != containers

**Comment by thaJeztah** [comment] 2015-02-26 23:25
Summarising the current state of this;

- `docker cp` now supports copying files from a container's volume to the host (https://github.com/docker/docker/pull/8509)
- work is in progress to allow copying between containers, which allows more easily copying the data to a new container and committed / pushed to distribute the data (https://github.com/docker/docker/pull/10198)
- work is in progress to improve volume-management, including exporting volumes (https://github.com/docker/docker/pull/8484 and named (remote) volumes: https://github.com/docker/docker/issues/7249#issuecomment-71203483)

As mentioned in this discussion, volumes are not part of the container, which is by design. There's room for improvement around handling volumes and their data, which is tracked by the issues mentioned above.

Perhaps this issue should be closed?

**Comment by larsks** [comment] 2015-06-17 02:32
We should update the documentation for `docker commit` to mention the fact that it does not save volume data.  I keep encountering people who are surprised by this behavior.

**Comment by thaJeztah** [comment] 2015-06-17 06:11
@larsks sounds reasonable, interested in creating a pull-request?

**Comment by vdemeester** [comment] 2015-08-03 14:42
@thaJeztah the PR #13987 was merged, should we close this issue then ? :blush:

**Comment by thaJeztah** [comment] 2015-08-03 14:48
@vdemeester oh! thx again, guess it didn't auto-close

**Closed by thaJeztah** 2015-08-03 14:48 UTC
Labels: kind/feature

**Comment by victort** [comment] 2017-02-15 23:12
lame. what i wouldn't give for data volume container commits. Simplifies SO MUCH. 😠

**Comment by engineerakki** [comment] 2017-02-24 09:28
Is this going to be in some future version of docker?
This will be a very useful feature for us.

**Comment by discordianfish** [comment] 2017-02-26 10:53
@cpuguy83  / @thaJeztah: Can you guys somehow auto-lock old issues? These comments are never useful and I don't want to go over every issue I'm still subscribed to and unsubscribe manually ;)

**Comment by thaJeztah** [comment] 2017-02-26 14:59
@discordianfish yes, it was actually discussed recently, and is on our list to have a bot auto-lock after issues are closed.

@engineerakki no, this is not on the roadmap, also see https://github.com/docker/docker/issues/7583#issuecomment-76297925

I'll lock the conversation on this issue, as commenting on old issues is not the best approach for opening feature requests.
