### ISSUE TITLE
--insecure-registry option being ignored

### ISSUE THREAD

**Issue by burhan** [docker/docker#17205] opened 2015-10-20 06:51 UTC
Docker version 1.8.3, build f4bf5c7

On this specific version of docker, when I modify `/etc/default/docker` and add `--insecure-registry foo.bar.zoo:5000`, this option is ignored when pushing images tagged for that registry:

```
The push refers to a repository [foo.bar.zoo:5000/mysql] (len: 1)
unable to ping registry endpoint https://foo.bar.zoo:5000/v0/
v2 ping attempt failed with error: Get https://foo.bar.zoo:5000/v2/: EOF
 v1 ping attempt failed with error: Get https://foo.bar.zoo:5000/v1/_ping: EOF
```

Well of course ping would fail, as the registry is only available over `http`. To confirm that the issue is only with this specific version; when I run the same command on another host, using docker version 1.7.1, build 446ad9b/1.7.1 - everything works as expected.

Sundry detail as required (on the host that's failing):
```
burhan@ubuntu:~$ uname -a
Linux ubuntu 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
burhan@ubuntu:~$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64
burhan@ubuntu:~$ docker info
Containers: 2
Images: 71
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 85
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 3.774 GiB
Name: ubuntu
ID: K2AE:MKI7:ZH43:S7DO:TR7L:5FNY:GAZI:WIE6:66JT:7VWQ:4R7Q:56B3
WARNING: No swap limit support
```

Here is `/etc/default/docker`:

```
burhan@ubuntu:~$ cat /etc/default/docker
# Docker Upstart and SysVinit configuration file

# Customize location of Docker binary (especially for development testing).
#DOCKER="/usr/local/bin/docker"

# Use DOCKER_OPTS to modify the daemon startup options.
DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --dns 172.22.1.100 --dns 172.22.1.101 --insecure-registry foo.bar.zoo:5000"

# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export TMPDIR="/mnt/bigdrive/docker-tmp"
```

**Comment by thaJeztah** [comment] 2015-10-20 07:20
Hi @burhan, the reason this isn't working is that Ubuntu 15.04 no longer uses upstart, but switched to SystemD. The `/etc/default/docker` file is only used for systems running upstart and sysvinit;

`# Docker Upstart and SysVinit configuration file`

To customize daemon options on systems running with SystemD, use drop-in files. This page in the documentation explains how to do this;
https://docs.docker.com/articles/systemd/#custom-docker-daemon-options

I hope this helps resolving your issue.

I'm going to close this issue, because this is not a bug, but feel free to comment here after I've closed this issue. :+1:

**Closed by thaJeztah** 2015-10-20 07:20 UTC

**Comment by burhan** [comment] 2015-10-20 08:01
@thaJeztah that makes sense, but I believe this should be mentioned in the [installation instructions for Ubuntu](https://docs.docker.com/installation/ubuntulinux/) where it mentions how to change the configuration options ("Configure a DNS server for use by Docker"), by using using `/etc/default/docker`.

As I was reading that page when I decided to edit the file.

**Comment by thaJeztah** [comment] 2015-10-21 02:57
@burhan hm, yes, I agree; we should make a distinction there between SystemD (14.10 and above) and non-systemD versions.

Could you open a new issue for that (i.e., that the docs need to be fixed)? :+1:
