### ISSUE TITLE
Change swarm mode ingress network

### ISSUE THREAD

**Issue by rmdashrfslash** [docker/docker#24220] opened 2016-07-01 14:24 UTC
Hi -

I'm am testing out swarm mode (1.12.0-rc2) on a couple of new centos 7 virtual machines (VMWare).  One issue I face is that the default network picked for the swarm ingress network (10.255.0.0/16) conflicts with a network in my organization.  Is it possible to change the network, or change the range on swarm creation?  

Otherwise, very sweet work :)

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0-rc2
Storage Driver: devicemapper
 Pool Name: docker-253:0-15237-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 265.1 MB
 Data Space Total: 107.4 GB
 Data Space Available: 4.03 GB
 Metadata Space Used: 950.3 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: active
 NodeID: 34hiak5m1kx7uoq21zvmuv0b3
 IsManager: Yes
 Managers: 3
 Nodes: 3
 CACertHash: sha256:ccaaea96f037886b08c96488e1bf57fba1e948e7a676a395665898601f7d539b
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
Name: XXXXXXXXXXX
ID: TJTI:I6MX:DX7R:CM4L:VH3M:FNNN:NKSO:4YFI:DPJX:TF2W:OISX:FAR5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

```

**Comment by mavenugo** [comment] 2016-07-01 14:40
I know there was a plan to add this configuration to `docker swarm init`. 
@mrjana will know about that.

**Comment by mrjana** [comment] 2016-07-01 17:08
@rmdashrfslash We are definitely thinking of adding the ability to configure the ingress network in the future. It just didn't make it into 1.12 code. 

But just to clarify, as long as you are using a kernel in all your nodes which is greater than or equal to 3.16 this would not cause any conflicts with the host network. In those kernels it is completely in a private namespace and doesn't get exposed outside at all. Even in kernels < 3.16 it is only a problem if the conflict is in the host itself. If the host itself doesn't participate in `10.255.0.0` network then there is no problem.

**Comment by Cas-pian** [comment] 2016-08-19 07:56
I met the same problem too, and curiously my kernel version is 4.2.0. Because I found that there are packets from 10.255.x.x(outside of the docker and my host) to the docker service port (publish 5001), but no packets back (and too much tcp retransmission).
Any suggestion is appreciated. Thanks very much!

**docker version info:**
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

**docker info:**
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /data/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: esq4g83ffhodq3wzox4hmfkzk
 Is Manager: true
 ClusterID: b312564hx4b92tkhmb4d3zwfs
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
:WARNING: No swap limit support
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 10.4.41.80
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: XXXXX-01
ID: CWWZ:XXY5:2GIW:WT46:OPUU:WK6Z:HGSL:J4U3:WBGH:KUFC:XXXX:XXXX
Docker Root Dir: /data/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by BretFisher** [comment] 2016-09-02 03:45
Couldn't a workaround to this be to create a custom overlay network and just not use the ingress for any services?

**Comment by fishnix** [comment] 2016-09-02 21:22
@BretFisher it seems like when you publish a port from a service, it's automatically assigned to the ingress network.  Is that correct?  I'm currently hitting this issue as well.

**Comment by BretFisher** [comment] 2016-09-02 22:12
Right it's assigned to the ingress network for incoming traffic to published ports only, which it sounds like @rmdashrfslash is saying is the same subnet as the source of an incoming packet to a published port... but @mrjana is saying it shouldn't matter.

@rmdashrfslash if  you can give me specifics on the source IP (what exactly is the conflict) then I can try to reproduce. FYI you should be pointing traffic to the host IP for published ports... I've never needed to care about the ingress network IP's.. they don't show up in containers or on host.

Ignore my above comment, as a overlay network wouldn't affect that scenario.

**Comment by se7enack** [comment] 2016-10-20 19:42
This is a show-stopper for our adoption. Our in-house network is 10.255.0.0/24 with subnets:
10.255.1.0/16, 10.255.2.0/16, 10.255.3.0/16, etc. Docker services work great when we ported over our product however nothing is routable from the swarm to our internal resources, such as our internal DBs, DNS, and internet gateway. There needs to be a way to change the ingress network. Is this on the roadmap?

**Comment by se7enack** [comment] 2016-10-20 20:02
It would be very helpful if there were an init option for ingress: 

docker swarm init --ingress 10.1.0.0/16

**Comment by mavenugo** [comment] 2016-10-22 10:01
Changing the subnet is just one configurable parameter of a network. We have a few other configuration options today for `docker network` and more will come in the future. Hence instead of identifying individual configurable parameters, we must make the `--ingress` network itself to be replaceable. one option (cc @mrjana & @aboch) would be `docker swarm init --ingress my-global-ingress-network`. Ofcourse there is a chicken and egg problem here that we will not be able to create a `my-global-ingress-network` before `swarm init` is complete and also by design `docker network` configurations are immutable (hence we cannot create this `my-global-ingress-network` prior to `swarm init` and update later). 

Hence the option would be to let the user `docker network create --ingress -d overlay my-global-ingress-network` after the `docker swarm init --ingress <my-global-ingress-network>`. Between these commands any `docker service -p` must fail. Also this `my-global-ingress-network` will be special due to `--ingress` flag (and there can be only one network with that flag in the swarm) and will have multiple restrictions imposed by the system.

@mrjana @al wdyt ?

**Comment by thaJeztah** [comment] 2016-10-22 22:07
I've seen requests for `docker network update` - if technically possible, would that be something to consider?

**Comment by pacoxu** [comment] 2016-10-24 12:50
same issue.

**Comment by se7enack** [comment] 2016-10-24 19:30
We really need this feature request. Any chance this will get on a release roadmap?

**Comment by daninthewoods** [comment] 2016-10-24 19:35
+1 really need to be able to change this setting.

**Comment by a09-capf** [comment] 2016-11-22 07:29
I face the same issue. We really need the ability to configure the ingress network.

**Comment by se7enack** [comment] 2016-11-28 18:27
Any chance this will get on a release roadmap? This is a huge problem for any infrastructure already using a 10.255.x.x network.

**Comment by aboch** [comment] 2016-11-28 18:33
@se7enack We are working on adding this feature.

**Comment by firesh** [comment] 2016-12-01 18:56
I meet the same issue.

**Comment by firesh** [comment] 2016-12-02 22:25
As mentioned by @mrjana, I think the best way to solve this issue instant is upgrade the kernels.
On my ubuntu server, docker working fine with 16.04 LTS version:
`apt-get install linux-generic-lts-xenial`
`init 6`
`root@iZm5effj2tm01xgnawt688Z:~# uname -a
Linux iZm5effj2tm01xgnawt688Z 4.4.0-52-generic #73~14.04.1-Ubuntu SMP Wed Nov 30 17:20:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by se7enack** [comment] 2016-12-08 14:05
@firesh I've tested this. It does not resolve the issue.

**Comment by hoswey** [comment] 2016-12-14 10:20
I face this same issue. but it is so curious that it seems the subnet is not not conflict.
```
 ifconfig | grep 10    
          inet addr:10.20.170.106  Bcast:10.20.170.255  Mask:255.255.255.0
```

any help?

**Comment by firesh** [comment] 2016-12-16 03:43
@se7enack After upgrade the kernels, you still can not use ingress. But you can create another overlay network with subnetwork(192.168.x.x or 172.16.x.x).  Need specify the network using --network: `docker service create --network YOURNETWORKNAME`

**Comment by se7enack** [comment] 2017-01-12 16:38
@aboch Any rough ETA on this?

**Comment by se7enack** [comment] 2017-01-14 18:51
@aboch @mrjana @mavenugo Any rough ETA on this?

**Comment by thaJeztah** [comment] 2017-01-16 15:38
@aboch will this PR help for the overlapping network range? https://github.com/docker/docker/pull/29376

**Comment by aboch** [comment] 2017-01-16 16:31
@se7enack 
The feature is targeted for docker 1.14

@thaJeztah 
Currently, the ingress network subnet is not auto selected. So that PR wouldn't help for this.

**Comment by zioalex** [comment] 2017-02-16 17:16
Hi guys,
I just want to share my experience with a similar problem:
The MTU between the docker bridge and your vpn should match.
If you do not do it you will get partial or no connectivity from the container to the outside world.

This can be even more tricky because small requests will be server properly; like a traceroute.
But then when a full request is done you will not get the proper response.
IE:
curl curl http://www.greens.org/about/software/editor.txt -vI
will work
while 
curl http://www.greens.org/about/software/editor.txt
will not work!

## How I found the "nice" problem
With tcpdump on the vpn interface and filtering for my test host I found:
tcpdump -i vpn0 'host 23.239.3.133'
17:46:58.851427 IP truncated-ip - 100 bytes missing! mail.greens.org.http > 4delbmiege.ad.here.com.47046: Flags [.], seq 1:1355, ack 104, win 227, options [nop,nop,TS val 2285110976 ecr 9183195], length 1354: HTTP: HTTP/1.1 200 OK

I tried to change the mtu in the interface showed in ifconfig or ip but nothing! The result didn't change.
So I checked the docker network:
    
    docker network ls

found out my bridge network

    docker network inspect NETWORD_ID

And i found that even if I changed the mtu to every interface of my system the docker inspect show to me:

    "com.docker.network.driver.mtu": "1500"

Now my VPN mtu is 1300.
Finally I found a good way to start docker with the right mtu.
Just add --mtu=1300 on the daemon on startup.

**Comment by ama2** [comment] 2017-02-22 14:30
i face same issue

**Comment by rnataraja** [comment] 2017-03-23 18:37
+1

**Closed** 2017-03-27 14:30 UTC
Labels: area/networking, area/swarm, version/1.12

**Comment by andriywzy** [comment] 2017-06-22 10:39
+1
