### ISSUE TITLE
Change the way the REST API is documented

### ISSUE THREAD

**Issue by mattapperson** [docker/docker#2583] opened 2013-11-07 01:45 UTC
I suggest that the REST API documentation be moved to a more machine readable format such as JSON, XML, or the new blueprint format (http://apiblueprint.org)

The reason is simple... The community maintained modules and libs are currently updated by hand and not always in sync with Dockers many and frequent changes. Having a format that can be used as a config or even used to compile new releases would drastically speed up the communities ability to utilize the latest versions of docker.

**Comment by dnephin** [comment] 2016-09-22 21:41
Duplicate of #22931 which has more recent discussion, so closing this

**Closed by dnephin** 2016-09-22 21:41 UTC
Labels: area/docs, exp/expert
