### ISSUE TITLE
docker panics decoding JSON

### ISSUE THREAD

**Issue by grobinson-blockchain** [docker/docker#25367] opened 2016-08-03 13:03 UTC
Aug  3 12:44:14 docker[19254]: 2016/08/03 12:44:14 http: panic serving @: reflect: slice index out of range
	Aug  3 12:44:14 docker[19254]: goroutine 543 [running]:
	Aug  3 12:44:14 docker[19254]: net/http.(*conn).serve.func1(0xc820c49130, 0x7fac4f197568, 0xc82115e478)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/net/http/server.go:1287 +0xb5
	Aug  3 12:44:14 docker[19254]: encoding/json.(*encodeState).marshal.func1(0xc820eeb0d8)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:265 +0x11f
	Aug  3 12:44:14 docker[19254]: reflect.Value.Index(0x11dcdc0, 0xc820cd2020, 0xd7, 0x9, 0x0, 0x0, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/reflect/value.go:847 +0x151
	Aug  3 12:44:14 docker[19254]: encoding/json.(*arrayEncoder).encode(0xc82011c8d8, 0xc8205e62c0, 0x11dcdc0, 0xc820cd2020, 0xd7, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:685 +0xd2
	Aug  3 12:44:14 docker[19254]: encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc8205e62c0, 0x11dcdc0, 0xc820cd2020, 0xd7, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:692 +0x51
	Aug  3 12:44:14 docker[19254]: encoding/json.(*sliceEncoder).encode(0xc82011c8e0, 0xc8205e62c0, 0x11dcdc0, 0xc820cd2020, 0xd7, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:662 +0xb0
	Aug  3 12:44:14 docker[19254]: encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc8205e62c0, 0x11dcdc0, 0xc820cd2020, 0xd7, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:671 +0x51
	Aug  3 12:44:14 docker[19254]: encoding/json.(*structEncoder).encode(0xc8208c9620, 0xc8205e62c0, 0x1568c80, 0xc820cd2018, 0xd9, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:582 +0x2c0
	Aug  3 12:44:14 docker[19254]: encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc8205e62c0, 0x1568c80, 0xc820cd2018, 0xd9, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:596 +0x51
	Aug  3 12:44:14 docker[19254]: encoding/json.(*structEncoder).encode(0xc8208c9440, 0xc8205e62c0, 0x150d800, 0xc820cd2018, 0xd9, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:582 +0x2c0
	Aug  3 12:44:14 docker[19254]: encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc8205e62c0, 0x150d800, 0xc820cd2018, 0xd9, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:596 +0x51
	Aug  3 12:44:14 docker[19254]: encoding/json.(*structEncoder).encode(0xc8208c9170, 0xc8205e62c0, 0x14e46e0, 0xc820cd2000, 0xd9, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:582 +0x2c0
	Aug  3 12:44:14 docker[19254]: encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc8205e62c0, 0x14e46e0, 0xc820cd2000, 0xd9, 0xc820cd2000)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:596 +0x51
	Aug  3 12:44:14 docker[19254]: encoding/json.(*ptrEncoder).encode(0xc82011ca58, 0xc8205e62c0, 0x118e640, 0xc820cd2000, 0x16, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:704 +0xea
	Aug  3 12:44:14 docker[19254]: encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc8205e62c0, 0x118e640, 0xc820cd2000, 0x16, 0xc820cd2000)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:709 +0x51
	Aug  3 12:44:14 docker[19254]: encoding/json.(*encodeState).reflectValue(0xc8205e62c0, 0x118e640, 0xc820cd2000, 0x16)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:297 +0x6b
	Aug  3 12:44:14 docker[19254]: encoding/json.(*encodeState).marshal(0xc8205e62c0, 0x118e640, 0xc820cd2000, 0x0, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/encode.go:270 +0xa9
	Aug  3 12:44:14 docker[19254]: encoding/json.(*Encoder).Encode(0xc820eeb3b0, 0x118e640, 0xc820cd2000, 0x0, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/encoding/json/stream.go:188 +0x94
	Aug  3 12:44:14 docker[19254]: github.com/docker/docker/daemon.(*Daemon).ContainerStats(0xc820109e00, 0xc82005ee16, 0xc, 0xc820e8f620, 0x0, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/stats.go:110 +0x9e5
	Aug  3 12:44:14 docker[19254]: github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersStats(0xc8208b9860, 0x7fac4f198f88, 0xc820e8f590, 0x7fac5321e1a0, 0xc820c49290, 0xc821169420, 0xc820e8f440, 0x0, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:82 +0x34d
	Aug  3 12:44:14 docker[19254]: github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersStats)-fm(0x7fac4f198f88, 0xc820e8f590, 0x7fac5321e1a0, 0xc820c49290, 0xc821169420, 0xc820e8f440, 0x0, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:37 +0x74
	Aug  3 12:44:14 docker[19254]: github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7fac4f198f88, 0xc820e8f590, 0x7fac5321e1a0, 0xc820c49290, 0xc821169420, 0xc820e8f440, 0x0, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
	Aug  3 12:44:14 docker[19254]: github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7fac4f198f88, 0xc820e8f500, 0x7fac5321e1a0, 0xc820c49290, 0xc821169420, 0xc820e8f440, 0x0, 0x0)
	Aug  3 12:44:14 docker[19254]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6b8
	Aug  3 12:44:14 docker[19254]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fac5321e1a0, 0xc820c49290, 0xc821169420)
	Aug  3 12:44:14 docker[19254]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:132 +0x138
	Aug  3 12:44:14 docker[19254]: net/http.HandlerFunc.ServeHTTP(0xc820119840, 0x7fac5321e1a0, 0xc820c49290, 0xc821169420)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/net/http/server.go:1422 +0x3a
	Aug  3 12:44:14 docker[19254]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc82063e640, 0x7fac5321e1a0, 0xc820c49290, 0xc821169420)
	Aug  3 12:44:14 docker[19254]: /usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
	Aug  3 12:44:14 docker[19254]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc82083b780, 0x7fac5321e1a0, 0xc820c49290, 0xc821169420)
	Aug  3 12:44:14 docker[19254]: /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
	Aug  3 12:44:14 docker[19254]: net/http.serverHandler.ServeHTTP(0xc82034b4a0, 0x7fac5321e1a0, 0xc820c49290, 0xc821169420)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/net/http/server.go:1862 +0x19e
	Aug  3 12:44:14 docker[19254]: net/http.(*conn).serve(0xc820c49130)
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/net/http/server.go:1361 +0xbee
	Aug  3 12:44:14 docker[19254]: created by net/http.(*Server).Serve
	Aug  3 12:44:14 docker[19254]: /usr/local/go/src/net/http/server.go:1910 +0x3f6

docker version:

	Client:
	 Version:      1.11.0
	 API version:  1.23
	 Go version:   go1.5.4
	 Git commit:   4dc5990
	 Built:        Wed Apr 13 18:17:17 2016
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.11.0
	 API version:  1.23
	 Go version:   go1.5.4
	 Git commit:   4dc5990
	 Built:        Wed Apr 13 18:17:17 2016
	 OS/Arch:      linux/amd64

**Comment by thaJeztah** [comment] 2016-08-03 13:49
This looks like a duplicate of https://github.com/docker/docker/issues/22030, and should be fixed through https://github.com/docker/docker/pull/22120 in docker 1.11.1

Can you update to update 1.11.2, and see if the problem is solved for you?

**Comment by thaJeztah** [comment] 2016-10-29 06:43
Closing as this should be resolved

**Closed by thaJeztah** 2016-10-29 06:43 UTC
Labels: status/more-info-needed, version/1.11
