### ISSUE TITLE
How to run GUI apps in containiers in osx? (docker for mac)

### ISSUE THREAD

**Issue by ganesshkumar** [docker/docker#24479] opened 2016-07-09 13:45 UTC
I have got docker for Mac and not using boot2docker.

I have read the guidelines to run GUI apps inside docker. But when it comes to Mac, all the guides rely on boot2docker or running docker inside a VM and forwarding the x11 using xquartz. #8710 

Since we have docker for mac now, is it possible to forward the video and audio directly without using xquartz or vnc? 

From @jfrazelle's blog, in docker run command these are the parameters I am interested in.
```
    -v /tmp/.X11-unix:/tmp/.X11-unix \ # mount the X11 socket
    -e DISPLAY=unix$DISPLAY \ # pass the display

    --device /dev/snd \ # so we have sound
```

**Comment by thaJeztah** [comment] 2016-07-09 19:49
@ganesshkumar could you post this question in the Docker for Mac feedback forum? https://forums.docker.com/c/docker-for-mac. This question is really related to Docker for Mac, and not a bug in the "docker engine".

I'll close this issue here, because this is not a bug or feature request for the docker engine, but for "Docker for Mac", so unfortunately we can't fix/answer that here

**Closed by thaJeztah** 2016-07-09 19:49 UTC
Labels: group/pinata
