### ISSUE TITLE
when docker daemon stop illegality, docker start `container_id` may failed

### ISSUE THREAD

**Issue by cc272309126** [docker/docker#8065] opened 2014-09-16 10:13 UTC
when docker daemon stop illegality, docker start `container_id` may failed, it will tell me like the follow
"Error: Cannot start container d36d2b5f32b2: Error getting container d36d2b5f32b225d91fae18e3fdded3c2c83fdc1a45b5acfaafbfca351ab01d2f from driver devicemapper: Error mounting '/dev/mapper/docker-253:0-2229360-d36d2b5f32b225d91fae18e3fdded3c2c83fdc1a45b5acfaafbfca351ab01d2f' on '/var/lib/docker/devicemapper/mnt/d36d2b5f32b225d91fae18e3fdded3c2c83fdc1a45b5acfaafbfca351ab01d2f': device or resource busy"

I can solve it by blkdeactivate command. so I think the docker should first blkdeactivate the device when docker start the container, if there can check the device is active or is mounted in the /proc/mounts. this code can i submit it ?

**Comment by vbatts** [comment] 2015-01-08 21:11
closing as a duplicate of https://github.com/docker/docker/issues/5684#issuecomment-69052334

**Closed by vbatts** 2015-01-08 21:11 UTC
Labels: /system/devicemapper, Runtime
