### ISSUE TITLE
How to define the status of a swarm mode service?

### ISSUE THREAD

**Issue by jimmycmh** [docker/docker#31033] opened 2017-02-15 07:06 UTC
Swarm mode continuously recreates new containers when a task fails to run.

But in some cases, it's necessarily to decide whether the service is ready or failed , for example when a service depends on another.

Ready: running containers == replicas is fine, but how about global service? 
Failed: hard to tell. The latest containers may not in failed or rejected state.  If by examing previous containers, what if there is service updating?

Maybe it's necessary for docker  to return the "service status", because it knows more information.

**Comment by thaJeztah** [comment] 2017-02-15 07:43
>  But in some cases, it's necessarily to decide whether the service is ready or failed , for example when a service depends on another.

You can specify [healthchecks](https://docs.docker.com/engine/reference/commandline/service_create/), which are considered when checking the status of individual tasks.

However, when designing your services, make sure to design them such, that they are resilient against failures. Services that a service depends on can become unavailable _at any time_, not just when first started. For example, if your application depends on a database server to be available, for example, by implementing a [retry-loop](https://github.com/docker-library/wordpress/blob/b807f1285869a220a5f72b935901603e5bde8822/php5.6/apache/docker-entrypoint.sh#L190-L201)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-02-15 07:43 UTC

**Comment by jimmycmh** [comment] 2017-02-15 08:17
Imagine i'm writing some code to deploy two services: db and web, and web should be deployed after db is ready.
But with the current apis, it's hard to determine whether db service is ready or not.
For example, if i specified a wrong image tag when creating db service, what i can get from docker apis is a series of tasks: there is a task in Preparing state and a bunch of tasks in Shutdown state.
It's hard to tell the service status by these tasks.

**Comment by thaJeztah** [comment] 2017-02-15 08:26
Correct, the order in which the services are deployed cannot be guaranteed; so your web application should take that into account; not just when deploying but for its entire lifecycle. See the example i linked from the official WordPress image; that image checks if it's able to connect to the database, and keeps retrying until it's able to connect.
