### ISSUE TITLE
docker service create or network create publish ports on specific interface only?

### ISSUE THREAD

**Issue by virtuman** [docker/docker#28693] opened 2016-11-22 03:40 UTC
We have multiple network interfaces in all of our servers (e.g. eth0 and eth1). Some servers are part of docker cluster, others run applications on hosts. We would like to be able to run memcached as a docker service and have it accessible from any server in our local network.

Is it possible to make service accessible within the server internal network only? 
Current implementation of `docker servuce create --publish 11211:11211 memcached` will make port 11211 available to the public internet.

Found an --internal flag on `docker network create -d overlay --internal caching` , but this still publishes port of the docker service on all interfaces.

Thank you

**Comment by thaJeztah** [comment] 2016-11-22 17:32
I think this is a duplicate of https://github.com/docker/docker/issues/24317, so I'll close this one, but let me know if you think it's not a dup.

**Closed by thaJeztah** 2016-11-22 17:32 UTC
Labels: area/networking, area/swarm
