### ISSUE TITLE
Resource usage of excess resources in Swarm mode

### ISSUE THREAD

**Issue by dvohra** [docker/docker#31707] opened 2017-03-09 19:51 UTC
_Version and other template information is not relevant as the question or comment is general._

Are excess resources (CPU and memory) in Swarm mode available to be used by services that are running? Kubernetes is flexible in resource availability and resources in excess of limits are available to be used. Or, does the Swarm mode have a limit that cannot be exceed as specified by `--limit-cpu`	and `--limit-memory`.

**Comment by thaJeztah** [comment] 2017-03-10 09:27
If you limit a service on `cpu` or `memory`, its resources are "capped" to that amount. If you want to specify that a service _requires_ a certain amount of memory/cpu, but want to allow if to take up more (or unlimited), specify a combination of `--reserve-cpu` / `--reserve-memory` to define what it _needs_ to run, and set a `--limit-cpu` / `--limit-memory` to specify what it's _allowed_ to use.

The `--reserve-cpu` / `--reserve-memory` options are taken into account when scheduling tasks (i.e. no other tasks are scheduled on a node if all resources are reserved), but "limits" are not.

Not all options that are available on `docker run` for limiting resources are available (yet) in service definitions (see https://github.com/docker/docker/issues/25303). These parts of the documentation may provide more information about limiting resources; https://docs.docker.com/engine/admin/resource_constraints/, and https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-10 09:27 UTC

**Comment by dvohra** [comment] 2017-03-10 17:52
Not a bug, but a feature suggestion to provide a resource quota for a namespace within which replicas may exceed their individual resource limits if the aggregate of resource consumption within the namespace does not exceed the resource quota.

**Comment by thaJeztah** [comment] 2017-03-10 21:48
I'm not sure that would be possible; what should happen if 2 tasks are on different nodes, and one task takes up 100% of the CPU assigned; should the other task be killed?

**Comment by dvohra** [comment] 2017-03-10 22:04
Wouldn't suggest to use the same resource quota feature as in Kubernetes, but Kubernetes provides Quality of Service (QoS) with scopes. The `BestEffort` scope  is used only for tracking number of  Pods in a resource quota namespace.  And, if excess resources are available on a node Pods in excess of the hard limit on the number of Pods (as specified by the resource quota) could get scheduled though the Pods (exceeding the hard limit) would be first to get terminated if resources are required for another object.
