### ISSUE TITLE
Cannot run containers, operation not permitted

### ISSUE THREAD

**Issue by Anonymooseable** [docker/docker#22305] opened 2016-04-25 16:47 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:22:26 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:22:26 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 27
Server Version: 1.11.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.59 GiB
Name: computer
ID: F64Q:TS3X:QKTD:H32K:FH7Z:GMHY:43VK:AQK5:EW6T:2TYX:L3XN:KGHG
Docker Root Dir: /home/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Laptop

**Steps to reproduce the issue:**
1. `docker run -ti debian bash`

**Describe the results you received:**
```
docker: Error response from daemon: open /home/docker/overlay/7662016b764f8c1198a77b3b0fa719017fd359a423cd8c02383ede22090ca4aa-init/merged/etc/hosts: operation not permitted.
See 'docker run --help'.
```

**Describe the results you expected:**
Shell running in a container

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens most of the time, but sometimes the container can be created successfully. The file that access fails on isn't always `/etc/hosts`, I've also seen it happening on `/etc/resolv.conf`. Does not affect containers created before I started having the issue at all.

**Comment by Anonymooseable** [comment] 2016-04-25 17:00
Actually, it seems that when the container does start successfully things don't work right either. Apt can't open `/var/lib/apt/lists/lock` for `apt update` (also Operation not permitted), `su` doesn't work with the cryptic message `su: pam_start: error 26`... I'm guessing there's more. Adding `--security-opt seccomp:unconfined` doesn't help, nor even `--privileged`.

**Comment by Anonymooseable** [comment] 2016-04-25 17:14
Everything works fine on kernel `4.4.0-1-amd64 #1 SMP Debian 4.4.6-1 (2016-03-17)`.

**Comment by Chili-Man** [comment] 2016-04-25 17:27
This is a known issue for kernel 4.5.0 - 4.5.1 . The latest stable kernel 4.5.2 fixes these issues

**Comment by thaJeztah** [comment] 2016-04-25 17:29
Yes, this is a duplicate of https://github.com/docker/docker/issues/20950

**Comment by Anonymooseable** [comment] 2016-04-25 17:30
Sorry for the dupe, just realised I only searched in open issues. Thanks for the info!

**Closed** 2016-04-25 17:29 UTC

**Comment by thaJeztah** [comment] 2016-04-25 17:32
no problem! there's a lot of issues (including closed ones), I just happened to know there was one already 👍
