### ISSUE TITLE
Add LastUsedAsContainerTime access time attribute for Images

### ISSUE THREAD

**Issue by docwhat** [docker/docker#20925] opened 2016-03-03 22:13 UTC
I'm writing a docker-image-clean up tool based.

One thing that would make this work really well is if I had a `time.Time` for when the image was last used as a container.

Example of part of `docker inspect`:

``` json
[
    {
        "Id": "e33e4f43a8d249513f34d80270b89c0f7a70e633883fcc05fdb464c194c64b31",
        "Created": "2016-03-02T15:42:42.683943071Z",
        "LastUsedAsContainer": "2016-03-02T16:42:42.683943071Z",
        ...
    }
]
```

I could then look for images that haven't been used by a container in the last day.

This value should be updated on container deletion (e.g. `docker rm`).  Possibly it should not update if the current value is in the last 5 or 10 minutes to handle the "1000 containers running the same image shutting down at once" case.

**Comment by thaJeztah** [comment] 2016-03-04 00:18
I think this is a duplicate of https://github.com/docker/docker/issues/4237

Although I see it was not commented on that issue, there were objections to implement this, because we don't want containers to modify the images properties. Instead of implementing this functionality as a core functionality, we try to provide features in docker to implement things like this as an external tool.

For example, Docker 1.10 introduced a far more advanced events system, containing meta data about the actors, and actions (see https://github.com/docker/docker/pull/18888, and the (API) documentation here https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#monitor-docker-s-events

Using this, you can have your tool listen to events you think should be counted as "used" (pull, container create, container start?) and keep track of that. 

I'm going to close this issue, because this is not something we're going to implement, but I hope that you'll be able to implement this using the hints I mentioned above :+1:

**Closed by thaJeztah** 2016-03-04 00:18 UTC

**Comment by docwhat** [comment] 2016-03-04 03:10
Awww... darn. I have code that would be easy to adapt to this change. All I needed was for you to implement the hard stuff. :stuck_out_tongue_winking_eye: 

_seriously_: Sound fair enough. As you point out, an event listener would be able to grok a lot more about what's going on and who is using what.  Making decisions about what to delete better.

**Comment by thaJeztah** [comment] 2016-03-04 08:52
@docwhat good luck on your implementation! Interested to hear how it worked out for you, and feedback / requests for improvements are welcome!

**Comment by docwhat** [comment] 2016-05-31 16:47
@thaJeztah So I have created [docker-gc](https://github.com/docwhat/docker-gc) which works using the events.

My only complaint (an optimization, doesn't impact performance) is that there isn't an `untag` event which would let me pro-actively delete tags from the recorder.

**Comment by thaJeztah** [comment] 2016-05-31 17:35
@docwhat hm, perhaps it makes sense to have such an event; can you open an issue for that?

**Comment by docwhat** [comment] 2016-06-01 18:26
@thaJeztah -- Done! #23174

**Comment by thaJeztah** [comment] 2016-06-01 19:01
Thanks!

**Comment by sharbov** [comment] 2018-03-05 14:15
Here's a little utility I use for monitoring images last usage time: 

https://github.com/Stratoscale/dim
