### ISSUE TITLE
How to clone private repositories from GitHub while building an image?

### ISSUE THREAD

**Issue by goloroden** [docker/docker#24489] opened 2016-07-10 05:47 UTC
Supposed I want to build a Docker image that runs my software, and to run my software I need to download code from a private repository from GitHub.

This means that I need an SSH key within the image at build-time.
But how do I get rid of this SSH key in a secure way? I don't want it to stay in the image and be available to the end user.

I have seen that there are lots of approaches which are all marked as not being secure, including build-time arguments. Even the documentation states that this feature should not be used for storing secrets.

But unfortunately, it does not tell what to do instead.

As far as I have seen, SSH forwarding is also not possible at build-time, so what to do?
Any hints?

**Comment by phemmer** [comment] 2016-07-10 07:32
See #6396 which has a very long history on this subject.

**Comment by thaJeztah** [comment] 2016-07-12 00:26
closing as duplicate of https://github.com/docker/docker/issues/6396

**Closed by thaJeztah** 2016-07-12 00:26 UTC
Labels: area/builder, kind/enhancement
