### ISSUE TITLE
Make docker auto-restart containers on reboot by default

### ISSUE THREAD

**Issue by jaequery** [docker/docker#9678] opened 2014-12-15 23:47 UTC
Hi all,

I just wanted to say that I strongly wish all the containers that were last running would restart on the next boot by default.
Yes, there is the auto restart flag, but would rather like them auto-restart as the "default" and not have to add the autorestart flag to run the containers. 
This has bitten me quite many times in the past and I just don't see how having auto-restart disabled as default makes Docker any more secure (I'd think this makes it more insecure due to being more accident prone).

**Comment by gdm85** [comment] 2015-01-02 14:28
@jaequery there is here #8821 a forgotten proposal of mine which tried to encompass same problem

**Comment by gdm85** [comment] 2015-01-22 21:27
@cnf I have covered such scenario (as well as reboots) in [docker-fw](https://github.com/gdm85/docker-fw), starting with v0.2.0: basically if you use docker-fw to start the containers, it will remember their HostConfig next time you start them again with docker-fw. Check out also the ``save-hostconfig`` option to save the current host configuration (in case they were started without my utility).

This means that also port bindings and everything else are preserved, restoring containers to their previous state (almost perfectly).

@erikh that is a very common scenario for development/staging/testing - without mentioning mistakes in production environment, and unsaved work would be lost.

**Comment by VynceMontgomery** [comment] 2015-03-04 02:11
whether or not it happens automatically, there is not currently (as far as I can tell) a way to specify "restart on reboot but not when docker crashes without a machine reboot".

**Comment by cpuguy83** [comment] 2015-08-18 02:43
Closing as I've actually attempted to implement this exact feature (setting the default at the daemon level) and it was rejected.

The problem is when you do something like so with a the default being `--restart=always`:
```
docker run busybox true
```

**Closed by cpuguy83** 2015-08-18 02:43 UTC
Labels: kind/feature, kind/proposal

**Comment by andrewb-ms** [comment] 2018-01-18 18:03
This seems like something that is (a) needlessly painful, and (b) solvable.  I agree there are problems here, but they can be solved.

**Comment by cpuguy83** [comment] 2018-01-18 18:08
@andrewb-ms You can always use services on swarm-mode if you want this behavior.
