### ISSUE TITLE
How to visually see the browser being automated on Multihost docker on windows 10 and Linux ?

### ISSUE THREAD

**Issue by nagaiah** [docker/docker#32308] opened 2017-04-03 06:13 UTC
Can any one of you help me on the following, How to visually see the browser being automated on Multihost docker(overlay networking with swarm mode) on windows 10 OS ? I know that VNC Viewer works for single docker host with debug mode, what about in mutli-host docker, is there a way using which i can visually see the browser being automated on Mutli-host docker containers on windows 10 OS. 

please find the below link that i already have raised on stackoverflow to get answer on this issue

https://stackoverflow.com/questions/43115687/how-to-visually-see-the-browser-being-automated-on-multihost-docker-on-windows-1

Thank You In Advance.

**Comment by friism** [comment] 2017-04-03 14:48
It seems like you also asked this question on the forums (in addition to here and on Stackoverflow). It's a little unclear what you're trying to do, but if you're trying to run browser tests in Windows containers, then note that Windows containers cannot currently run GUI apps so [automating Windows browsers tests is probably not possible](https://forums.docker.com/t/docker-multi-hosting/30474/2).

**Comment by nagaiah** [comment] 2017-04-04 04:56
Thanks for the reply, please find the following steps which i'm doing 
1. installed docker on windows 10 machine and enabled Hyper-V driver by restarting 
2. Created a new virtual switch as given here https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/connect-to-network
3. Created Manager node - >docker-machine create -d hyperv --hyperv-virtual-switch "External VM Switch" manager1
4. logged in to recently created VM i.e manager1 and Enabled the swarm mode(docker swarm init), the command generated a worker token which will be run on worker machine to join the swarm. 

5. On Another Windows 10 Insider Machine, installed docker and restarted to enable Hyper-V driver. Then create virtual switch as given step 2. and created nodes(workers) - docker-machine create -d hyperv --hyperv-virtual-switch "External VM Switch" worker1
6. logged in to the above VM i.e worker1
7. ran the worker token generated in manager machine(step4) to join swarm, it had joined correctly and i got the message "This node joined a swarm as a worker." 

8. On First windows 10 machine, Created an overlay network driver on hub machine with the name ‘selenium-grid’(docker network create -d overlay selenium-grid)
9. Deployed services on manager node(Hub and Node) - "docker service create --network selenium-grid --name hub -p 4444:4444 selenium/hub" and 
"docker service create --network selenium-grid --endpoint-mode dnsrr --name chrome --mount type=bind,source=/dev/shm,target=/dev/shm -e HUB_PORT_4444_TCP_ADDR=hub -e HUB_PORT_4444_TCP_PORT=4444 --replicas 2 selenium/node-chrome bash -c 'SE_OPTS="-host $HOSTNAME" /opt/bin/entry_point.sh'"
Able to launch the grid console and able to run the suite on the docker grid i.e on chrome and firefox containers. My question is, how to view the execution happening on containers (chrome and firefox) ? I want to visually see the execution happening on the browser containers. Is this possible in this MultiHost network ?

**Comment by friism** [comment] 2017-04-11 20:58
I think you're going to get better answers from the selenium community. Also see this: https://github.com/SeleniumHQ/docker-selenium#debugging

This issue tracker is for bugs or feature requests for the Docker open project. Please use the Docker Forums or Stackoverflow for questions about how to use Docker.

**Comment by thaJeztah** [comment] 2017-04-11 21:03
Hm, yes, I agree, this looks like a support question for using docker, not a bug report; let me go ahead and close this issue

**Closed by thaJeztah** 2017-04-11 21:03 UTC
