### ISSUE TITLE
Recreate / rerun command / inherit (or similar funcionality)

### ISSUE THREAD

**Issue by pocesar** [docker/docker#11095] opened 2015-03-01 18:04 UTC
There are some containers that have really lenghty command lines doing binds, links and setting environment variables. Right now, the only way (that I found) to re-run a container with different settings is to `docker stop` > `docker rm`, then `docker run` again with different settings. 

Perhaps an option called `docker run --inherit` will get the current container command line that was previously set, then replace any new ones you pass in, like:

Suppose you originally ran the following container:
```bash
docker run --link db:db -p 80:3000 --link mail:mail -e NGINX_SSL_CERT=/key/nginx.cert -e NGINX_SSL_KEY=/key/nginx.pem -v /etc/ssl/:/key/ -e NODE_ENV=production -v /var/log/nginx:/logs/nginx/ --volumes-from=deploy --volumes-from=Maildir --name=web
```
Now I want to add some more information to the already existing container:
```bash
docker run --inherit web -e NODE_ENV=staging -p 80:3000 web-staging
```
So, if `inherit` is used, it will grab all the information that was created using the original and replace conflicting ones (like the NODE_ENV environment variable and the port one).  

When in and out of SSH, or after sometime, it's hard to remember / keep track of all the command lines that were used when running containers

**Comment by thaJeztah** [comment] 2015-03-01 18:12
@pocesar what you're describing looks like a good job for `docker-compose`; https://docs.docker.com/compose/, with the added benefit that it would also be possible to define all containers you need in your 'stack' and the links/relations they have.

**Comment by pocesar** [comment] 2015-03-01 18:58
@thaJeztah looks nice, how can I get the current command line used for running the containers?

**Comment by thaJeztah** [comment] 2015-03-01 19:27
I'd say, first do a bit of testing to try out compose so that you get a 'feel' for it. You'd probably have to create new containers, or rename them (docker-compose uses a naming convention for the containers, based on the 'project' they're part of (e.g. `myproject_db_1`).

> does the YAML file respect the order?

It will create/start the containers in the right order based on 'links' and 'volumes-from', so if those relations are defined in your YAML, it will start them in the right order.

**Comment by jfrazelle** [comment] 2015-03-02 16:37
duplicate of https://github.com/docker/docker/issues/8446 https://github.com/docker/docker/issues/7232 https://github.com/docker/docker/issues/2733

**Closed by jfrazelle** 2015-03-02 16:37 UTC
