### ISSUE TITLE
Docker on macOS --net=host option isn't working.

### ISSUE THREAD

**Issue by m1ome** [docker/docker#26138] opened 2016-08-30 08:38 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.19-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.953 GiB
Name: moby
ID: 4J7U:GIXF:Z6MM:G5H6:VV6U:GZC3:33GB:ZX5W:OYT3:MEU3:TSFT:DGSN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 41
 System Time: 2016-08-30T08:34:22.13315714Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**   
macOS 10.11.5
MySQL server binded on `127.0.0.1:3306` (on host system)

**Steps to reproduce the issue:**
1. `docker run -it --net=host ubuntu /bin/bash`
2. `apt-get update && apt-get install -y telnet`
3.  `telnet 127.0.0.1 3306`

**Describe the results you received:**
```
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

**Describe the results you expected:**
```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```

**Comment by justincormack** [comment] 2016-08-30 10:51
This is a duplicate of #22753 so I am going to close it here.

**Closed by justincormack** 2016-08-30 10:51 UTC
Labels: version/1.12
