### ISSUE TITLE
How to share my printer from host to docker image?

### ISSUE THREAD

**Issue by BinhuaLiu** [docker/docker#12303] opened 2015-04-11 21:15 UTC
I deployed my GUI app on docker image, How to share my printer from host to docker image? Thanks very much

**Comment by thaJeztah** [comment] 2015-04-11 22:16
Hi, @BinhuaLiu, the GitHub issue tracker is intended for tracking bugs, feature requests and pull requests, and not really for questions.

Could you ask this question on https://forums.docker.com/, https://groups.google.com/forum/#!forum/docker-user or the #docker IRC channel on Freenode?

I'm going to close this issue, because it's not a bug. (You'll still be able to comment on this issue after it's closed), thanks!

**Closed by thaJeztah** 2015-04-11 22:16 UTC
