### ISSUE TITLE
Docker doesn't remove MASQUERADE nat rule when removing network

### ISSUE THREAD

**Issue by ssadler** [docker/docker#18169] opened 2015-11-23 16:15 UTC
Description of problem:

Docker doesn't remove MASQUERADE rule from iptables when network is rm'ed.

If the same network is created, removed, then created again, the rule
is duplicated in iptables. One result of this is that the **gateway address
is wrongly propagated as the source address of a connection**.

`docker version`:

    Client:
     Version:      1.9.0
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   76d6bc9
     Built:        Tue Nov  3 17:48:04 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.9.0
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   76d6bc9
     Built:        Tue Nov  3 17:48:04 UTC 2015
     OS/Arch:      linux/amd64

`docker info`:

    Containers: 41
    Images: 52
    Server Version: 1.9.0
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 134
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.19.0-33-generic
    Operating System: Ubuntu 15.04
    CPUs: 4
    Total Memory: 7.705 GiB
    Name: wackbook
    ID: VNVB:5RAY:RLCV:FJ4U:IHYI:T2V3:E7AD:KOTF:ZZAI:UB5X:LAA7:JCPA
    WARNING: No swap limit support

`uname -a`:

    Linux wackbook 3.19.0-33-generic #38-Ubuntu SMP Fri Nov 6 18:18:12 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

Physical laptop

How reproducible:

Easy?

Steps to Reproduce:
1. `docker network create --subnet=10.5.5.0/24 batman`
2. `docker network rm batman`
3. `docker network create --subnet=10.5.5.0/24 batman`
4. `iptables -t nat -L | grep 10.5.5`

Actual Results:

    MASQUERADE  all  --  10.5.5.0/24          anywhere
    MASQUERADE  all  --  10.5.5.0/24          anywhere

Expected Results:

    MASQUERADE  all  --  10.5.5.0/24          anywhere

Additional info:

Cross reference #7540 which may be related

**Comment by cpuguy83** [comment] 2015-11-23 17:32
ping @mavenugo

**Comment by WeiZhang555** [comment] 2015-11-23 22:28
I think this is also a dup of https://github.com/docker/libnetwork/issues/570, and the fix is ready.

**Comment by ssadler** [comment] 2015-11-24 01:15
Yep, sure is. @WeiZhang555 I had a look at your PR, looks good to me, though I'm sure a test would help it get merged :). Would be relatively easy too by the looks of it, just to make sure that the `natChain` and `filterChain` are the same before and after?

**Comment by icecrime** [comment] 2015-12-03 17:45
See #docker/libnetwork#591.

**Comment by aboch** [comment] 2015-12-03 18:54
@ssadler Just tested with a docker image containing @WeiZhang555's change and can confirm it fixes the issue you reported.

Next libnetwork vendoring in docker will bring the fix in. Thanks @WeiZhang555.

**Comment by ssadler** [comment] 2015-12-04 01:11
Thanks @WeiZhang555 @aboch

**Comment by WeiZhang555** [comment] 2015-12-04 01:34
Glad to help :smile:

**Comment by mavenugo** [comment] 2015-12-08 01:36
Closed via https://github.com/docker/libnetwork/pull/591. Vendoring-in via #18106

**Closed by mavenugo** 2015-12-08 01:36 UTC
Labels: group/networking, kind/bug, priority/P2

**Comment by Timoha** [comment] 2016-11-11 01:03
Still seeing this issue with 1.12.1 on coreos.
`docker version`:
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7a86f89
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7a86f89
 Built:
 OS/Arch:      linux/amd64
```
`docker info`:
```
...
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: selinux
Kernel Version: 4.7.3-coreos
Operating System: CoreOS 1192.0.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 62.95 GiB
Name: localhost
ID: HGO4:Z5FW:YF4I:B2TD:TZQ5:C6ZQ:MMSR:RHXA:QDEY:53P4:M2RV:FMPB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
...
```
`iptables --version`:
```
iptables v1.4.21
```

How reproducible:
It seems random, sometimes MASQUERADE nat rule is left behind. And other times it's cleaned up. 

Additional info:
The issue is also causing #7540

**Comment by thaJeztah** [comment] 2016-11-19 17:21
@Timoha the original issue reported here was fixed. If you're still seeing this on the current (1.12.3) release, open a new issue. Please take into account that we don't provide builds for CoreOS, and that their packages contain modifications both in source code, and configuration, which can be related

**Comment by sburnwal** [comment] 2017-01-18 22:38
Thanks for the prompt response! Indeed that was the issue.
