### ISSUE TITLE
docker cp copies /var/run from host filesystem

### ISSUE THREAD

**Issue by astopy** [docker/docker#22596] opened 2016-05-09 10:04 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 21
 Running: 20
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 203
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.661 GiB
Name: ip-10-45-47-19
ID: Q6MZ:7LDC:GKQ4:2ZOO:HAUJ:TFG3:TZZI:D3JT:OVM7:BF6R:IUDK:OJT3
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: zooniversedeployment
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS

**Steps to reproduce the issue:**

```
ubuntu@ip-10-45-47-19:~$ docker exec -it current_redis_1 bash
root@7df18990c43e:/data# ls /var/
backups  cache  lib  local  lock  log  mail  opt  run  spool  tmp
root@7df18990c43e:/data# ls /var/run/
lock  utmp
root@7df18990c43e:/data# exit
ubuntu@ip-10-45-47-19:~$ mkdir redis
ubuntu@ip-10-45-47-19:~$ docker cp current_redis_1:/var/ redis/
ubuntu@ip-10-45-47-19:~$ ls redis/var/
backups  cache  lib  local  lock  log  mail  opt  run  spool  tmp
ubuntu@ip-10-45-47-19:~$ ls redis/var/run
acpid.pid     containerd    dhclient.eth0.pid  initramfs     mount                       plymouth      runc             sshd      upstart-file-bridge.pid    utmp
acpid.socket  crond.pid     docker             lock          network                     pppconfig     screen           sshd.pid  upstart-socket-bridge.pid
atd.pid       crond.reboot  docker.pid         monit.pid     network-interface-security  resolvconf    sendsigs.omit.d  systemd   upstart-udev-bridge.pid
cloud-init    dbus          docker.sock        motd.dynamic  ntpd.pid                    rsyslogd.pid  shm              udev      user
ubuntu@ip-10-45-47-19:~$ ls /var/run/
acpid.pid     containerd    dhclient.eth0.pid  initramfs     mount                       plymouth      runc             sshd      upstart-file-bridge.pid    utmp
acpid.socket  crond.pid     docker             lock          network                     pppconfig     screen           sshd.pid  upstart-socket-bridge.pid
atd.pid       crond.reboot  docker.pid         monit.pid     network-interface-security  resolvconf    sendsigs.omit.d  systemd   upstart-udev-bridge.pid
cloud-init    dbus          docker.sock        motd.dynamic  ntpd.pid                    rsyslogd.pid  shm              udev      user
```

**Describe the results you received:**

/var/run is copied from the host filesystem.

**Describe the results you expected:**

/var/run should be copied from the container's volume

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-05-09 10:55
It looks like this is actually not a bug in `docker cp`. In the redis image, `/var/run` is a symlink to `/run`, and when copying the `/var` directory out, docker copies the *symlink*. If you navigate to `redis/var/run`, you'll end up at the `/run` directory if your host;

```bash
# start a redis container
docker run -d --name tester redis

# exec into it and ls `/var/run`
docker exec -it tester ls -ls /var/run
lrwxrwxrwx 1 root root 4 May  3 18:52 /var/run -> /run
```

When you copy that directory out, the symlink is copied;

```bash
docker cp tester:/var/ redis/

# it's still a symlink, but now it points to `/run` on the host;
ls -la redis/var/run
lrwxr-xr-x  1 sebastiaan  staff  4  9 mei 12:54 redis/var/run -> /run
```

**Comment by thaJeztah** [comment] 2016-05-09 10:56
I'll close this issue, because I don't think there's a bug here, but feel free to comment after I closed

**Closed by thaJeztah** 2016-05-09 10:56 UTC
Labels: area/runtime

**Comment by astopy** [comment] 2016-05-09 11:06
Oh of course. I'd like to think if it wasn't Monday morning I would have spotted that.

Thanks.

**Comment by thaJeztah** [comment] 2016-05-09 11:10
No worries, I had to look twice as well; then I spotted it :smile:
