### ISSUE TITLE
1.7 images taking up a lot more space than with 1.6.2 on Ubuntu 14.04

### ISSUE THREAD

**Issue by gaverhae** [docker/docker#14040] opened 2015-06-19 13:19 UTC
Description of problem: `docker build` and `docker pull` commands take up a lot more space, to the point that containers that fit comfortably on my machine cannot be built anymore because they fill the hard drive. It's also much slower, though I guess that can be attributed to all the additional writing.

I *think* this is because of a change of storage driver: 1.6.2 used `devicemapper`, while 1.7.0 seems to try to use `overlay` and falls back on `vfs`.

### docker version

```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

### docker info

```
Containers: 0
Images: 0
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 994 MiB
Name: vagrant-ubuntu-trusty-64
ID: LMK6:AMD2:2SSS:UBJV:TRUY:RIM4:6BWP:WHS7:SNUR:DCSN:FDRH:ADY2
WARNING: No swap limit support
```

### uname -a

```
Linux vagrant-ubuntu-trusty-64 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:32:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

## Environment details

Docker is running within VirtualBox, provisioned by a Vagrantfile using the ubuntu/trusty64 official Vagrant image:

```
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 \
                --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
    echo deb https://get.docker.io/ubuntu docker main >> /etc/apt/sources.list
    apt-get update
    #apt-get install -y lxc-docker-1.6.2
    apt-get install -y lxc-docker-1.7.0
    gpasswd -a vagrant docker
    service docker restart
  SHELL
end
```

Physical host is a MacBook Air (OS X 10.10.3).

## How reproducible

Any `docker build` or `docker pull` command is much slower and takes up much more space than with Docker 1.6.2. (This may be expected behavior for `vfs`; I knew absolutely nothing about docker Storage Drivers before encountering this issue, and know no more than they exist at this point.)

## Steps to Reproduce

```
vagrant up && vagrant ssh
docker run hello-world
docker info
```

## Actual Results

```
Containers: 1
Images: 2
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 994 MiB
Name: vagrant-ubuntu-trusty-64
ID: LMK6:AMD2:2SSS:UBJV:TRUY:RIM4:6BWP:WHS7:SNUR:DCSN:FDRH:ADY2
WARNING: No swap limit support
```

## Expected Results

I expected the same results as with Docker 1.6.2, mostly regarding the storage driver and the space taken up by the images:

```
$ docker info
Containers: 1
Images: 2
Storage Driver: devicemapper
 Pool Name: docker-8:1-262820-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 307.6 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.1 GB
 Metadata Space Used: 823.3 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: false
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 994 MiB
Name: vagrant-ubuntu-trusty-64
ID: NOFV:3M4L:232S:W2GX:D43H:46WX:GOYT:DUC4:ZFVV:IZJB:3IJL:F5PO
WARNING: No swap limit support
```

## Additional info

Docker 1.6.2 (which I use as a reference):

```
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

Additionally, here is the output of `docker -d` in both configurations:

```
vagrant@vagrant-ubuntu-trusty-64:~$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
vagrant@vagrant-ubuntu-trusty-64:~$ sudo service docker stop
docker stop/waiting
vagrant@vagrant-ubuntu-trusty-64:~$ sudo docker -d
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
ERRO[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option
ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded.
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1
WARN[0000] Your kernel does not support swap memory limit.
INFO[0000] Loading containers: start.

INFO[0000] Loading containers: done.
INFO[0000] Daemon has completed initialization
INFO[0000] Docker daemon                                 commit=0baf609 execdriver=native-0.2 graphdriver=vfs version=1.7.0
^CINFO[0001] Processing signal 'interrupt'
vagrant@vagrant-ubuntu-trusty-64:~$
```

```
vagrant@vagrant-ubuntu-trusty-64:~$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
vagrant@vagrant-ubuntu-trusty-64:~$ sudo service docker stop
docker stop/waiting
vagrant@vagrant-ubuntu-trusty-64:~$ sudo docker -d
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
WARN[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors
INFO[0000] +job init_networkdriver()
INFO[0000] -job init_networkdriver() = OK (0)
WARN[0000] Your kernel does not support cgroup swap limit.
INFO[0000] Loading containers: start.

INFO[0000] Loading containers: done.
INFO[0000] docker daemon: 1.6.2 7c8fca2; execdriver: native-0.2; graphdriver: devicemapper
INFO[0000] +job acceptconnections()
INFO[0000] -job acceptconnections() = OK (0)
INFO[0000] Daemon has completed initialization
^CINFO[0001] Received signal 'interrupt', starting shutdown of docker...
INFO[0001] -job serveapi(unix:///var/run/docker.sock) = OK (0)
vagrant@vagrant-ubuntu-trusty-64:~$
```

**Comment by j0hnsmith** [comment] 2015-06-19 13:38
I had this problem today with a fresh ec2 ubuntu machine, docker was installed with `curl -s https://get.docker.io/ubuntu/ | sh`, the storage driver was `Storage Driver: vfs` and pulling a 420mb image took around 21gb of disk space!

When I installed docker with (the current instructions) `wget -qO- https://get.docker.com/ | sh` on another fresh equivalent machine the storage driver was `Storage Driver: aufs` and the problem went away.

**Comment by jaitaiwan** [comment] 2015-06-19 13:38
I was working with @gaverhae on this and a couple other IRC fellows who were having the same issues. It seems like the new Volumes plugin is what is causing the issues although I haven't been able to pinpoint exactly what about it is the issues.

The common factor seems to be that its been an upgrade from an older version of docker to 1.7 although I haven't yet confirmed that a fresh docker install doesn't have the same issues.

Users seem to experience slightly different symptoms as far as error messages are concerned with the common factor being 1.7 and exhausted or huge disk space usage around a vfs.

Some of the IRC users reported that using the newer installation script as found in the docker documentation (the wget one) resolved their issues. So I recommend anyone having the same issues to try that first.

**Comment by jaitaiwan** [comment] 2015-06-19 13:39
I should also mention that @gaverhae was using the Ubuntu PPA for docker at first.

**Comment by ra120271** [comment] 2015-06-23 11:30
I can confirm the 1.7 new install has the same issue.  A build that took up 22% of 20GB EC2 system under 1.6.2 filled the disk and failed to complete under 1.7.  This was using a fresh EC2 instance using automated build systems that installed the "latest" docker so did not upgrade.

**Comment by j0hnsmith** [comment] 2015-06-23 11:33
@ra120271 can you paste the output you get from `docker info` on an affected system?

**Comment by cpuguy83** [comment] 2015-06-23 14:41
In Docker 1.7, docker will refuse to use devicemapper if you don't have the proper environment setup... so basically, you need a dynamically built docker binary and dynamically built devicemapper so that devicemapper can stay synced with udev... otherwise you are guaranteed to run into problems, data loss, etc.

The ordering of usage of drivers has not changed.
1. aufs
2. btrfs
3. zfs
4. devicemapper
5. overlay
6. vfs

VFS of course use tons and tons of space becaue there is no CoW functionality.

How to resolve?
1. Install the linux-image-extra package for your kernel, which includes AUFS support
2. Use a dynamically built docker binary so you can use devicemapper
3. Use a newer kernel so you can use overlay or btrfs
4. Setup ZFS

Closing since this isn't really an issue with docker itself.

**Closed by cpuguy83** 2015-06-23 14:41 UTC

**Comment by jaitaiwan** [comment] 2015-06-24 08:04
@cpuguy83 if the order hasn't changed, why is it that some upgrades break anyway? For instance, one person on IRC was using AUFS and after the upgrade docker defaulted to vfs. When changing back to aufs there were numerous errors.

I guess what I'm trying to understand is why its suddenly using vfs for people that weren't using vfs previously...

**Comment by cpuguy83** [comment] 2015-06-25 06:04
@jaitaiwan because they probably also did a kernel upgrade and didn't install the aufs modules for that kernel.
