### ISSUE TITLE
specific docker search request

### ISSUE THREAD

**Issue by bgrissin** [docker/docker#22557] opened 2016-05-06 14:52 UTC
Is there a way to perform a search of docker hub for official images only 

docker search image_name(s) --official-images

**Comment by bgrissin** [comment] 2016-05-06 14:55
Also might consider expanding to search specific private/public repos as well

**Comment by chiisaihayashi** [comment] 2016-05-07 08:50
I found similar issue.
You could refer this [link](https://github.com/docker/docker/issues/18980).

**Comment by thaJeztah** [comment] 2016-05-07 09:36
Yes, this is a duplicate of https://github.com/docker/docker/issues/18980
and is currently worked on in https://github.com/docker/docker/pull/22369 (which will be in docker 1.12)

**Closed by thaJeztah** 2016-05-07 09:36 UTC
