### ISSUE TITLE
Not overriding hosts file

### ISSUE THREAD

**Issue by 0x4139** [docker/docker#14180] opened 2015-06-25 11:30 UTC
I can't seem to be able to override the host file with the -v option 
```
docker run -v /etc/hosts.data:/etc/hosts -ti debian bash
````
Env info
```
vali@thrall ~ $ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2-dirty
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/amd64
vali@thrall ~ $ docker info
Containers: 19
Images: 27
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.5
Operating System: CoreOS 681.2.0
CPUs: 32
Total Memory: 62.88 GiB
Name: thrall
ID: DHOP:FF5E:SA27:YXHJ:ADYL:7MMH:AQNA:NRBI:AKM2:SSFL:YMZX:QAVH
vali@thrall ~ $ uname -a
Linux thrall 4.0.5 #2 SMP Thu Jun 18 08:53:45 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz GenuineIntel GNU/Linux
vali@thrall ~ $ 

```
can't figure out what i am doing wrong

**Comment by laijs** [comment] 2015-06-25 16:56
Some files (including /etc/hosts) are bound by docker run-time and conceal the users' binding.

From the `docker inspect <contianer id>`, you can see something like this:

    "ResolvConfPath": "/var/lib/docker/containers/47dfbac8ad30d1138dcc47c395c2ee0cf3b44e56ad7a9c9a7ebd5255ba2daef0/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/47dfbac8ad30d1138dcc47c395c2ee0cf3b44e56ad7a9c9a7ebd5255ba2daef0/hostname",
    "HostsPath": "/var/lib/docker/containers/47dfbac8ad30d1138dcc47c395c2ee0cf3b44e56ad7a9c9a7ebd5255ba2daef0/hosts",

IMHO, the users' config should have higher priority and shall not be concealed

**Comment by cpuguy83** [comment] 2015-06-26 03:37
Correct, Docker provides the /etc/hosts for the container.
We cannot accept a user file here, especially since this would break links.

Docker does provide an API to add custom hosts to the file, `docker run --add-host <alias>:<ip>`.
This file is also writable in the container as well.

Closing since this is the intended behavior.
If you need some additional help/have questions, feel free to hit me up on IRC.

Thanks!

**Closed by cpuguy83** 2015-06-26 03:37 UTC
