### ISSUE TITLE
ADD/COPY ignored

### ISSUE THREAD

**Issue by zopyx** [docker/docker#10345] opened 2015-01-26 07:53 UTC
The following lines are used to add a license file to the PDFreactor/lib director

RUN ls -la PDFreactor/lib
COPY licensekey.txt PDFreactor/lib
RUN ls -la PDFreactor/lib

However the licensekey.txt does not land inside the container. The lib folder does show the license file.

Why?

--------------

Step 12 : RUN ls -la PDFreactor/lib
 ---> Running in f5d26b729e8f
total 33200
drwxr-xr-x  3 root root     4096 Dec 18 15:48 .
drwxr-xr-x 10 root root     4096 Dec 18 15:48 ..
-rw-r--r--  1 root root     6215 Dec 18 15:48 README.txt
drwxr-xr-x  4 root root     4096 Dec 18 15:48 modular
-rw-r--r--  1 root root 33973514 Dec 18 15:48 pdfreactor.jar
 ---> 0648b3aea688
Removing intermediate container f5d26b729e8f
Step 13 : COPY licensekey.txt PDFreactor/lib
 ---> 6e675c7640c0
Removing intermediate container 0382c0df8c78
Step 14 : RUN ls -la PDFreactor/lib
 ---> Running in 5596826a179f
total 33200
drwxr-xr-x  3 root root     4096 Dec 18 15:48 .
drwxr-xr-x 10 root root     4096 Dec 18 15:48 ..
-rw-r--r--  1 root root     6215 Dec 18 15:48 README.txt
drwxr-xr-x  4 root root     4096 Dec 18 15:48 modular
-rw-r--r--  1 root root 33973514 Dec 18 15:48 pdfreactor.jar

docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
ajung@demo:~/src/onkopedia_buildout/docker/pp.server$ docker -D info
Containers: 53
Images: 345
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 453
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 5.829 GiB
Name: demo.xml-director.info
ID: LTA5:NIZF:ZRHM:V6GM:SPMV:GKDE:WKUN:NZC7:MYRF:IMHU:BZC3:G6NH
Debug mode (server): false
Debug mode (client): true
Fds: 42
Goroutines: 51
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: zopyx
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

**Comment by phemmer** [comment] 2015-01-26 08:23
I'm guessing you've got a `WORKDIR` command as a previous step in your dockerfile. Per [the documentation](https://docs.docker.com/reference/builder/#workdir), `WORKDIR` only affects `RUN`, `CMD` and `ENTRYPOINT`, not `COPY`.

If this is not the case, please provide the full dockerfile, or a simple reproducible test case, as I cannot reproduce.

**Comment by duglin** [comment] 2015-01-26 13:26
From my testing, and looking at the <a href="https://github.com/docker/docker/blob/master/builder/internals.go#L220">code</a>, it appears that WORKDIR is taken into account for COPY. 
@zopyx can you share your entire Dockerfile so we can try to reproduce it.
@phemmer I'll open a PR to fix the docs w.r.t. WORKDIR. thanks!

**Comment by phemmer** [comment] 2015-01-26 13:40
@duglin I'm curious how you tested this, as this is not the behavior I observe:

```
# cat Dockerfile
FROM busybox
RUN mkdir /test
RUN ls -la /test
WORKDIR /test
COPY bar foo
RUN ls -la /test /foo

# docker build --no-cache -t test . 
Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon 
Step 0 : FROM busybox
 ---> e72ac664f4f0
Step 1 : RUN mkdir /test
 ---> Running in e52a30b38530
 ---> 3d744923157f
Removing intermediate container e52a30b38530
Step 2 : RUN ls -la /test
 ---> Running in 7d95401a882a
total 0
drwxr-xr-x    1 root     root             0 Jan 26 13:39 .
drwxr-xr-x    1 root     root           182 Jan 26 13:39 ..
 ---> b41bcfb9ffc8
Removing intermediate container 7d95401a882a
Step 3 : WORKDIR /test
 ---> Running in cf74222ab16f
 ---> f7d0d5506498
Removing intermediate container cf74222ab16f
Step 4 : COPY bar foo
 ---> 1378597af325
Removing intermediate container 90d2b02a1096
Step 5 : RUN ls -la /test /foo
 ---> Running in 85bcb50a0f8a
-rw-r--r--    1 root     root             4 Jan 26 13:32 /foo

/test:
total 0
drwxr-xr-x    1 root     root             0 Jan 26 13:39 .
drwxr-xr-x    1 root     root           188 Jan 26 13:39 ..
 ---> e89df5d4980f
Removing intermediate container 85bcb50a0f8a
Successfully built e89df5d4980f

```

**Comment by duglin** [comment] 2015-01-26 13:43
Here's my dockerfile:
FROM ubuntu
WORKDIR tmp
COPY foo ./
RUN find / -name foo

foo is a text file.

Notice the / at the end of the COPY. @zopyx, please try with a / at the end of the target path.

**Comment by duglin** [comment] 2015-01-26 13:46
Also, when I don't use a / : 
FROM ubuntu
WORKDIR tmp
COPY foo bar
RUN find / -name bar

I get:
...
 ---> Running in 104d50251e33
/tmp/bar

**Comment by duglin** [comment] 2015-01-26 13:50
@phemmer what level of Docker are you on? I'm using 'master' and I actually get an error from your final "ls" due to it not finding the file at / . When I changed it to:
RUN find / -name foo
then I get back:
 ---> Running in 7be6c7f96647
/test/foo

**Comment by phemmer** [comment] 2015-01-26 14:30
@duglin 1.4.1
Looking at the blame log on that code you linked, it looks like this behavior was a recent change (by you nonetheless).
This also now concerns me, as it's apparently a breaking change.

**Comment by duglin** [comment] 2015-01-26 14:42
@phemmer yep - originally discussed in #7870 and I just finished it up for tianon.
I think its the right change tho since w/o this change it means that a leading / on the destination path would be meaningless.  I think people's natural expectation is that a path w/o a leading / is relative.

**Comment by duglin** [comment] 2015-01-26 14:43
Or let me phrase it this way.... I think the old behavior was a bug  :-)

**Comment by phemmer** [comment] 2015-01-26 14:50
![](http://i.imgur.com/Tm8LZ58.png)

**Comment by duglin** [comment] 2015-01-26 14:52
LOL

**Comment by duglin** [comment] 2015-01-29 02:00
@zopyx can you try again with a / at the end of the destination dir on the COPY?

**Comment by jfrazelle** [comment] 2015-02-28 01:15
@duglin @phemmer any resolution here?

**Comment by duglin** [comment] 2015-02-28 01:17
No word from @zopyx so I say close it and he can reopen it once he has more info

**Comment by duglin** [comment] 2015-03-01 20:12
@zopyx please reopen when you have the info requested.

**Closed by duglin** 2015-03-01 20:12 UTC
