### ISSUE TITLE
volume ownership based on -u user

### ISSUE THREAD

**Issue by ibukanov** [docker/docker#18825] opened 2015-12-21 14:38 UTC
Currently docker sets the ownership and permissions for -v volumes based on those in the image mount point. This is inflexible when the image is used to run several containers with different user ids based on the --user option. In such case one typically wants for the volume to be owned by user:group passed to --user, not the owner of the mount point in the image. In fact unless the mount point has world-writable permissions, that volume would not be useful in the container.

I can workaround this by providing, for example, a setuid command in the container to change ownership of the volume on startup before running the main application or by using a host volume with explicitly set permissions, but this brings rather considerable complexity.

So it would be ideal if docker provided an option to set the volume ownership based on -u user:group option. Note that this should not affect the host volumes. As currently, they should keep their host ownership.

**Comment by thaJeztah** [comment] 2015-12-21 14:52
Thanks for suggesting, I think this is a duplicate of https://github.com/docker/docker/issues/7198. Some attempts were made to implement this in this PR: https://github.com/docker/docker/pull/14632, however, doing so will change ownership of the files on the host (there is no good solution to that yet, and may need support in the kernel to dynamically rewrite ownership)

I'll close this issue, because it's a duplicate of https://github.com/docker/docker/issues/7198. Please subscribe to that issue (using the "subscribe" button) to stay informed on progress. Feel free to comment here after I've closed this

**Closed by thaJeztah** 2015-12-21 14:52 UTC

**Comment by ibukanov** [comment] 2015-12-21 15:06
@thaJeztah #7198 is very generic and little progress has been made. This bug is about volumes that docker creates when it creates the container, not the shared volumes on the host. There is already code that sets their ownership/permissions based on those from the mount point. This bug is about extending that to set the ownership of the newly created volume based on ---user=user:group.

**Comment by thaJeztah** [comment] 2015-12-21 16:02
Currently, volumes keep the permissions they have inside the image, so wondering; should that recursively change ownership of the volume's content?

For example;

```bash
docker build -t perms - << EOF
FROM ubuntu
RUN mkdir -p /foobar && touch /foobar/bla && chown -R 123:456 /foobar
EOF

docker run -v /foobar -t --rm perms sh -c 'ls -la /foobar'

total 8
drwxr-xr-x 2  123  456 4096 Dec 21 03:36 .
drwxr-xr-x 1 root root 4096 Dec 21 03:36 ..
-rw-r--r-- 1  123  456    0 Dec 21 03:34 bar
```

Would 

    docker run -v /foobar -t --rm -u 456:789 perms sh -c 'ls -la /foobar'

Result in:
```
total 8
drwxr-xr-x 2  456  789 4096 Dec 21 03:36 .
drwxr-xr-x 1 root root 4096 Dec 21 03:36 ..
-rw-r--r-- 1  456  789    0 Dec 21 03:34 bar
```

Or only the root-directory of the volume be owned by the user?

**Comment by ibukanov** [comment] 2015-12-21 19:19
The idea is to have an option that makes any directory or file created by the docker when it initializes a new volume to be owned by --user=user:group and copied from the image. So yes, the ownership should be applied recursively.

**Comment by thaJeztah** [comment] 2015-12-21 19:30
That could obviously have side effects as well, i.e. files owned by "foo", and files owned by "bar" will both be owned by "user:group" upon initialization.

Perhaps it's something that should be implemented as a volume plugin? @cpuguy83 wdyt?
