### ISSUE TITLE
"strconv.ParseInt: parsing "17\x1b[17": invalid syntax" when try install phpmyadmin on ubuntu (container)

### ISSUE THREAD

**Issue by slavapr** [docker/docker#17335] opened 2015-10-24 18:46 UTC
Hi,

I try install phpmyadmin on ubuntu (docker container). I use Windows 10.
```
PPP@PPP MINGW64 ~
$  winpty docker run -it ubuntu bash
root@215136960bba:/# dir
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@215136960bba:/# cd etc
root@215136960bba:/etc# dir
X11                     default          iproute2        mime.types     python3.4     shells
adduser.conf            deluser.conf     issue           mke2fs.conf    rc.local      skel
alternatives            depmod.d         issue.net       modprobe.d     rc0.d         subgid
apparmor                dhcp             kbd             modules        rc1.d         subgid-
apparmor.d              dpkg             kernel          mtab           rc2.d         subuid
apt                     environment      ld.so.cache     network        rc3.d         subuid-
bash.bashrc             fstab            ld.so.conf      networks       rc4.d         sudoers
bash_completion.d       fstab.d          ld.so.conf.d    newt           rc5.d         sudoers.d
bindresvport.blacklist  gai.conf         legal           nologin        rc6.d         sysctl.conf
blkid.conf              group            libaudit.conf   nsswitch.conf  rcS.d         sysctl.d
blkid.tab               gshadow          locale.alias    opt            resolv.conf   systemd
console-setup           host.conf        localtime       os-release     resolvconf    terminfo
cron.d                  hostname         logcheck        pam.conf       rmt           timezone
cron.daily              hosts            login.defs      pam.d          rpc           ucf.conf
cron.hourly             init             logrotate.conf  passwd         rsyslog.conf  udev
cron.monthly            init.d           logrotate.d     perl           rsyslog.d     update-motd.d
cron.weekly             initramfs-tools  lsb-release     ppp            securetty     upstart-xsessions
crontab                 inputrc          magic           profile        security      vim
dbus-1                  insserv          magic.mime      profile.d      selinux       vtrgb
debconf.conf            insserv.conf     mailcap         protocols      services
debian_version          insserv.conf.d   mailcap.order   python3        shadow
root@215136960bba:/etc# sudo apt-get install phpmyadmin
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package phpmyadmin
root@215136960bba:/etc# cd .
root@215136960bba:/# cd..
bash: cd..: command not found
root@215136960bba:/# sudo apt-get install phpmyadmin
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package phpmyadmin
root@215136960bba:/#
root@215136960bba:/# ^C
root@215136960bba:/#  sudo apt-get update
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [64.4 kB]
Get:2 http://archive.ubuntu.com trusty-security InRelease [64.4 kB]
Hit http://archive.ubuntu.com trusty Release.gpg
Get:3 http://archive.ubuntu.com trusty-updates/main Sources [301 kB]
Get:4 http://archive.ubuntu.com trusty-updates/restricted Sources [4513 B]
Get:5 http://archive.ubuntu.com trusty-updates/universe Sources [176 kB]
Get:6 http://archive.ubuntu.com trusty-updates/main amd64 Packages [799 kB]
Get:7 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [22.7 kB]
Get:8 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [421 kB]
Hit http://archive.ubuntu.com trusty Release
Get:9 http://archive.ubuntu.com trusty-security/main Sources [123 kB]
Get:10 http://archive.ubuntu.com trusty-security/restricted Sources [3230 B]
Get:11 http://archive.ubuntu.com trusty-security/universe Sources [35.4 kB]
Get:12 http://archive.ubuntu.com trusty-security/main amd64 Packages [448 kB]
Get:13 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [19.4 kB]
Get:14 http://archive.ubuntu.com trusty-security/universe amd64 Packages [151 kB]
Get:15 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:16 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:17 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:18 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:19 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:20 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Fetched 21.2 MB in 27s (773 kB/s)
Reading package lists... Done
root@215136960bba:/# sudo apt-get install phpmyadmin
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  apache2 apache2-bin apache2-data dbconfig-common fontconfig-config
  fonts-dejavu-core javascript-common libapache2-mod-php5 libapr1 libaprutil1
  libaprutil1-dbd-sqlite3 libaprutil1-ldap libasn1-8-heimdal libdbd-mysql-perl
  libdbi-perl libedit2 libfontconfig1 libfreetype6 libgd3 libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal
  libhx509-5-heimdal libjbig0 libjpeg-turbo8 libjpeg8 libjs-codemirror
  libjs-jquery libjs-jquery-cookie libjs-jquery-event-drag
  libjs-jquery-metadata libjs-jquery-mousewheel libjs-jquery-tablesorter
  libjs-jquery-ui libjs-underscore libkrb5-26-heimdal libldap-2.4-2 libmcrypt4
  libmysqlclient18 libroken18-heimdal libsasl2-2 libsasl2-modules
  libsasl2-modules-db libterm-readkey-perl libtiff5 libvpx1 libwind0-heimdal
  libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxml2 libxpm4 lsof
  mysql-client mysql-client-5.5 mysql-client-core-5.5 mysql-common openssl
  php-gettext php5-cli php5-common php5-gd php5-json php5-mcrypt php5-mysql
  php5-readline psmisc sgml-base ssl-cert xml-core
Suggested packages:
  www-browser apache2-doc apache2-suexec-pristine apache2-suexec-custom ufw
  apache2-utils php-pear libclone-perl libmldbm-perl libnet-daemon-perl
  libplrpc-perl libsql-statement-perl libgd-tools libjs-jquery-ui-docs
  libmcrypt-dev mcrypt libsasl2-modules-otp libsasl2-modules-ldap
  libsasl2-modules-sql libsasl2-modules-gssapi-mit
  libsasl2-modules-gssapi-heimdal ca-certificates php5-user-cache mysql-server
  sgml-base-doc openssl-blacklist debhelper
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data dbconfig-common fontconfig-config
  fonts-dejavu-core javascript-common libapache2-mod-php5 libapr1 libaprutil1
  libaprutil1-dbd-sqlite3 libaprutil1-ldap libasn1-8-heimdal libdbd-mysql-perl
  libdbi-perl libedit2 libfontconfig1 libfreetype6 libgd3 libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal
  libhx509-5-heimdal libjbig0 libjpeg-turbo8 libjpeg8 libjs-codemirror
  libjs-jquery libjs-jquery-cookie libjs-jquery-event-drag
  libjs-jquery-metadata libjs-jquery-mousewheel libjs-jquery-tablesorter
  libjs-jquery-ui libjs-underscore libkrb5-26-heimdal libldap-2.4-2 libmcrypt4
  libmysqlclient18 libroken18-heimdal libsasl2-2 libsasl2-modules
  libsasl2-modules-db libterm-readkey-perl libtiff5 libvpx1 libwind0-heimdal
  libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxml2 libxpm4 lsof
  mysql-client mysql-client-5.5 mysql-client-core-5.5 mysql-common openssl
  php-gettext php5-cli php5-common php5-gd php5-json php5-mcrypt php5-mysql
  php5-readline phpmyadmin psmisc sgml-base ssl-cert xml-core
0 upgraded, 74 newly installed, 0 to remove and 0 not upgraded.
Need to get 21.6 MB of archives.
After this operation, 118 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libroken18-heimdal amd64 1.6~git20131207+dfsg-1ubuntu1.1
[40.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libasn1-8-heimdal amd64 1.6~git20131207+dfsg-1ubuntu1.1 [
161 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libedit2 amd64 3.1-20130712-2 [86.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libhcrypto4-heimdal amd64 1.6~git20131207+dfsg-1ubuntu1.1
 [83.9 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libheimbase1-heimdal amd64 1.6~git20131207+dfsg-1ubuntu1.
1 [28.9 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libwind0-heimdal amd64 1.6~git20131207+dfsg-1ubuntu1.1 [4
7.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libhx509-5-heimdal amd64 1.6~git20131207+dfsg-1ubuntu1.1
[104 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libkrb5-26-heimdal amd64 1.6~git20131207+dfsg-1ubuntu1.1
[196 kB]
Get:9 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libheimntlm0-heimdal amd64 1.6~git20131207+dfsg-1ubuntu1.
1 [15.2 kB]
Get:10 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgssapi3-heimdal amd64 1.6~git20131207+dfsg-1ubuntu1.1
 [89.8 kB]
Get:11 http://archive.ubuntu.com/ubuntu/ trusty/main libsasl2-modules-db amd64 2.1.25.dfsg1-17build1 [14.9 kB]
Get:12 http://archive.ubuntu.com/ubuntu/ trusty/main libsasl2-2 amd64 2.1.25.dfsg1-17build1 [56.5 kB]
Get:13 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libldap-2.4-2 amd64 2.4.31-1+nmu2ubuntu8.2 [153 kB]
Get:14 http://archive.ubuntu.com/ubuntu/ trusty/main libxau6 amd64 1:1.0.8-1 [8376 B]
Get:15 http://archive.ubuntu.com/ubuntu/ trusty/main libxdmcp6 amd64 1:1.1.1-1 [12.8 kB]
Get:16 http://archive.ubuntu.com/ubuntu/ trusty/main libxcb1 amd64 1.10-2ubuntu1 [38.0 kB]
Get:17 http://archive.ubuntu.com/ubuntu/ trusty/main libx11-data all 2:1.6.2-1ubuntu2 [111 kB]
Get:18 http://archive.ubuntu.com/ubuntu/ trusty/main libx11-6 amd64 2:1.6.2-1ubuntu2 [560 kB]
Get:19 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libxml2 amd64 2.9.1+dfsg1-3ubuntu4.4 [570 kB]
Get:20 http://archive.ubuntu.com/ubuntu/ trusty/main sgml-base all 1.26+nmu4ubuntu1 [12.5 kB]
Get:21 http://archive.ubuntu.com/ubuntu/ trusty/main libapr1 amd64 1.5.0-1 [85.1 kB]
Get:22 http://archive.ubuntu.com/ubuntu/ trusty/main libaprutil1 amd64 1.5.3-1 [76.4 kB]
Get:23 http://archive.ubuntu.com/ubuntu/ trusty/main fonts-dejavu-core all 2.34-1ubuntu1 [1024 kB]
Get:24 http://archive.ubuntu.com/ubuntu/ trusty-updates/main fontconfig-config all 2.11.0-0ubuntu4.1 [47.4 kB]
Get:25 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libfreetype6 amd64 2.5.2-1ubuntu2.5 [304 kB]
Get:26 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libfontconfig1 amd64 2.11.0-0ubuntu4.1 [123 kB]
Get:27 http://archive.ubuntu.com/ubuntu/ trusty/main libjpeg-turbo8 amd64 1.3.0-0ubuntu2 [104 kB]
Get:28 http://archive.ubuntu.com/ubuntu/ trusty/main libjpeg8 amd64 8c-2ubuntu8 [2194 B]
Get:29 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libjbig0 amd64 2.0-2ubuntu4.1 [26.1 kB]
Get:30 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libtiff5 amd64 4.0.3-7ubuntu0.3 [143 kB]
Get:31 http://archive.ubuntu.com/ubuntu/ trusty/main libvpx1 amd64 1.3.0-2 [556 kB]
Get:32 http://archive.ubuntu.com/ubuntu/ trusty/main libxpm4 amd64 1:3.5.10-1 [38.3 kB]
Get:33 http://archive.ubuntu.com/ubuntu/ trusty/main libgd3 amd64 2.1.0-3 [147 kB]
Get:34 http://archive.ubuntu.com/ubuntu/ trusty-updates/main mysql-common all 5.5.44-0ubuntu0.14.04.1 [13.9 kB]
Get:35 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libmysqlclient18 amd64 5.5.44-0ubuntu0.14.04.1 [596 kB]
Get:36 http://archive.ubuntu.com/ubuntu/ trusty/main psmisc amd64 22.20-1ubuntu2 [53.2 kB]
Get:37 http://archive.ubuntu.com/ubuntu/ trusty/main lsof amd64 4.86+dfsg-1ubuntu2 [257 kB]
Get:38 http://archive.ubuntu.com/ubuntu/ trusty/main php5-json amd64 1.3.2-2build1 [34.4 kB]
Get:39 http://archive.ubuntu.com/ubuntu/ trusty-updates/main php5-common amd64 5.5.9+dfsg-1ubuntu4.13 [443 kB]
Get:40 http://archive.ubuntu.com/ubuntu/ trusty-updates/main php5-gd amd64 5.5.9+dfsg-1ubuntu4.13 [27.9 kB]
Get:41 http://archive.ubuntu.com/ubuntu/ trusty-updates/main php5-mysql amd64 5.5.9+dfsg-1ubuntu4.13 [63.0 kB]
Get:42 http://archive.ubuntu.com/ubuntu/ trusty-updates/main php5-cli amd64 5.5.9+dfsg-1ubuntu4.13 [2165 kB]
Get:43 http://archive.ubuntu.com/ubuntu/ trusty-updates/main php5-readline amd64 5.5.9+dfsg-1ubuntu4.13 [12.1 kB]
Get:44 http://archive.ubuntu.com/ubuntu/ trusty/main libsasl2-modules amd64 2.1.25.dfsg1-17build1 [64.3 kB]
Get:45 http://archive.ubuntu.com/ubuntu/ trusty-updates/main openssl amd64 1.0.1f-1ubuntu2.15 [489 kB]
Get:46 http://archive.ubuntu.com/ubuntu/ trusty/main xml-core all 0.13+nmu2 [23.3 kB]
Get:47 http://archive.ubuntu.com/ubuntu/ trusty/main libaprutil1-dbd-sqlite3 amd64 1.5.3-1 [10.5 kB]
Get:48 http://archive.ubuntu.com/ubuntu/ trusty/main libaprutil1-ldap amd64 1.5.3-1 [8634 B]
Get:49 http://archive.ubuntu.com/ubuntu/ trusty-updates/main apache2-bin amd64 2.4.7-1ubuntu4.8 [840 kB]
Get:50 http://archive.ubuntu.com/ubuntu/ trusty-updates/main apache2-data all 2.4.7-1ubuntu4.8 [160 kB]
Get:51 http://archive.ubuntu.com/ubuntu/ trusty-updates/main apache2 amd64 2.4.7-1ubuntu4.8 [87.6 kB]
Get:52 http://archive.ubuntu.com/ubuntu/ trusty/main dbconfig-common all 1.8.47+nmu1 [468 kB]
Get:53 http://archive.ubuntu.com/ubuntu/ trusty/main javascript-common all 11 [6066 B]
Get:54 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libapache2-mod-php5 amd64 5.5.9+dfsg-1ubuntu4.13 [2209 k
B]
Get:55 http://archive.ubuntu.com/ubuntu/ trusty/main libdbi-perl amd64 1.630-1 [879 kB]
Get:56 http://archive.ubuntu.com/ubuntu/ trusty/main libdbd-mysql-perl amd64 4.025-1 [99.3 kB]
Get:57 http://archive.ubuntu.com/ubuntu/ trusty/main libjs-jquery all 1.7.2+dfsg-2ubuntu1 [78.8 kB]
Get:58 http://archive.ubuntu.com/ubuntu/ trusty/universe libjs-jquery-cookie all 8-2 [6502 B]
Get:59 http://archive.ubuntu.com/ubuntu/ trusty/universe libjs-jquery-event-drag all 8-2 [11.2 kB]
Get:60 http://archive.ubuntu.com/ubuntu/ trusty/main libjs-jquery-metadata all 8-2 [6856 B]
Get:61 http://archive.ubuntu.com/ubuntu/ trusty/universe libjs-jquery-mousewheel all 8-2 [7076 B]
Get:62 http://archive.ubuntu.com/ubuntu/ trusty/main libjs-jquery-tablesorter all 8-2 [64.0 kB]
Get:63 http://archive.ubuntu.com/ubuntu/ trusty/universe libjs-jquery-ui all 1.10.1+dfsg-1 [458 kB]
Get:64 http://archive.ubuntu.com/ubuntu/ trusty/main libjs-underscore all 1.4.4-2ubuntu1 [45.6 kB]
Get:65 http://archive.ubuntu.com/ubuntu/ trusty/universe libmcrypt4 amd64 2.5.8-3.1ubuntu1 [61.9 kB]
Get:66 http://archive.ubuntu.com/ubuntu/ trusty/main libterm-readkey-perl amd64 2.31-1 [27.4 kB]
Get:67 http://archive.ubuntu.com/ubuntu/ trusty-updates/main mysql-client-core-5.5 amd64 5.5.44-0ubuntu0.14.04.1 [702
 kB]
Get:68 http://archive.ubuntu.com/ubuntu/ trusty-updates/main mysql-client-5.5 amd64 5.5.44-0ubuntu0.14.04.1 [1573 kB]

Get:69 http://archive.ubuntu.com/ubuntu/ trusty-updates/main mysql-client all 5.5.44-0ubuntu0.14.04.1 [12.1 kB]
Get:70 http://archive.ubuntu.com/ubuntu/ trusty/universe php-gettext all 1.0.11-1 [17.2 kB]
Get:71 http://archive.ubuntu.com/ubuntu/ trusty/universe php5-mcrypt amd64 5.4.6-0ubuntu5 [15.4 kB]
Get:72 http://archive.ubuntu.com/ubuntu/ trusty/main ssl-cert all 1.0.33 [16.6 kB]
Get:73 http://archive.ubuntu.com/ubuntu/ trusty/universe libjs-codemirror all 2.23-1 [210 kB]
Get:74 http://archive.ubuntu.com/ubuntu/ trusty/universe phpmyadmin all 4:4.0.10-1 [4224 kB]
Fetched 21.6 MB in 35s (616 kB/s)
Extracting templates from packages: 100%
Preconfiguring packages ...

*PURPURE SCREEN*

strconv.ParseInt: parsing "17\x1b[17": invalid syntax
```

**Comment by mitchcapper** [comment] 2015-10-24 19:46
Thanks slavapr for submitting a bug report!  In the future if you can try to make your test cases a bit more concise it would be great along with the system info (per Gordon above).     I ran two tests and were unable to reproduce the issue, currently running win10 and using powershell with docker and a linux docker host:
1) 
Dockerfile with contents of:
```
FROM ubuntu 
RUN apt-get update
RUN apt-get install -y phpmyadmin
```
docker  built the container without issue.

Then a dockerfile of:
```
FROM ubuntu 
RUN apt-get update
```
  docker build  -t "phpadm_test" .
then 
  docker run  --rm -t -i  phpadm_test bash -c 'DEBIAN_FRONTEND=noninteractive apt-get install -y phpMyAdmin'

Now with the error info you provided I am thinking it may be the ui that apache/web install tries to launch in interactive mode with your terminal handler.  Powershell is able to properly display this(so a full interactive install does work) but given when you are bailing out I am guessing that may be the issue.     If you continue to have the problem please let us know a bit more about your environment thanks!

**Comment by thaJeztah** [comment] 2015-10-24 19:53
This doesn't sound like a bug in Docker, but something with the installation process of phpmyadmin (as mentioned by @mitchcapper, some installers will default to an "interactive" install, which won't work if you perform an automated install in a Dockerfile.

I suggest to ask this question in the #docker IRC channel, the #Docker-users group on Google, or on https://forums.docker.com

I'm going to close this issue for the reasons above, but feel free to comment here after I've close this issue. Thanks!

**Comment by phemmer** [comment] 2015-10-24 20:37
I personally wouldn't buy that answer.

```
strconv.ParseInt: parsing "17\x1b[17": invalid syntax
```

`strconv.ParseInt` is golang

**Comment by thaJeztah** [comment] 2015-10-25 07:37
hm.. I may have been too fast closing, I'll reopen; couldn't reproduce though

**Comment by thaJeztah** [comment] 2015-10-25 07:38
Will try again later

**Comment by cpuguy83** [comment] 2015-10-25 11:55
I don't know, the `strconv.ParseInt` error seems like a bug with the ansi terminal emulator.

**Comment by thaJeztah** [comment] 2015-10-25 12:09
I'll add the Windows peeps, perhaps they're already tracking this

/cc @swernli @jhowardmsft

**Comment by jhowardmsft** [comment] 2015-10-25 17:27
What version of docker on Windows? There have been many fixes in the ansi emulator. Can you verify if this repros using docker master?

**Comment by mitchcapper** [comment] 2015-10-25 17:34
Yeah I can say the GUI for the selector I *think* he is crashing on works just fine for me on Git commit:   d2e7ba4 on win10 with powershell.

**Comment by jhowardmsft** [comment] 2016-05-24 22:19
It sounds like this is fixed. Closing.

**Closed by jhowardmsft** 2016-05-24 22:19 UTC
Labels: group/windows
