### ISSUE TITLE
cannot enable tty mode on non tty input Windows 10 x64 docker 1.11.0

### ISSUE THREAD

**Issue by vladtamas** [docker/docker#22107] opened 2016-04-17 18:55 UTC
Hi,

I installed latest docker and when I run docker run -it alpine /bin/sh I get the following error "cannot enable tty mode on non tty input"

**Comment by thaJeztah** [comment] 2016-04-18 11:25
Are you running docker toolbox? You didn't provide any information about your environment (`docker info`, `docker version`).

If you're running docker toolbox, I suspect this is a duplicate of https://github.com/docker/docker/issues/12469

**Comment by thaJeztah** [comment] 2016-09-19 23:46
closing because there's no activity, but happy to reopen if you're still having this issue, and have more information

**Closed by thaJeztah** 2016-09-19 23:46 UTC
Labels: status/more-info-needed
