### ISSUE TITLE
Containers with different docker internal network cannot be allocated on the same IP address, but theoritically their IPs could be the same.

### ISSUE THREAD

**Issue by KevinTHU** [docker/docker#28375] opened 2016-11-14 06:37 UTC
**Description**
Containers with different internal docker network cannot be allocated the same IP address, this will cause error "Address already in use"

**Steps to reproduce the issue:**
1.docker network create -d overlay --subnet 100.55.0.0/24 hx-100-55-net-0
2.docker network create -d overlay --subnet 100.55.0.0/24 hx-100-55-net-1
3.docker run -d --name=hx-net-0 --network=hx-100-55-net-0 --ip=100.55.0.10 centos ping www.baidu.com
4.docker run -d --name=hx-net-1 --network=hx-100-55-net-1 --ip=100.55.0.10 centos ping www.baidu.com

**Describe the results you received:**
docker: Error response from daemon: Address already in use.
(in log: level=error msg="Handler for POST /v1.24/containers/6d9cbaac2ac17866b812ba7f8afbcf793de8a7eb12ebb32cbd1fc1ac78fdfe0d/start returned error: Address already in use")

**Describe the results you expected:**
the container can be started

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 94
 Running: 12
 Paused: 0
 Stopped: 82
Images: 155
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 27.77 GB
 Data Space Total: 1.1 TB
 Data Space Available: 1.072 TB
 Metadata Space Used: 11.09 MB
 Metadata Space Total: 10.74 GB
 Metadata Space Available: 10.73 GB
 Thin Pool Minimum Free Space: 110 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge vlcp overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 251.6 GiB
Name: kvm-yz-dev-073-003-005
ID: C2SU:MF4K:ZWXH:IDN4:2YEN:DXAT:WIEL:HEC4:BUQD:XOPY:OFMT:MQ4L
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 328
 Goroutines: 1305
 System Time: 2016-11-14T14:35:46.429285918+08:00
 EventsListeners: 3
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Cluster Store: zk://100.73.3.4:2181,100.73.3.5:2181,100.73.3.6:2181
Cluster Advertise: 100.73.3.5:2375
Insecure Registries:
 jdocker.me
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
4 centos7.2 physical swarm stand-alone cluster

**Comment by justincormack** [comment] 2016-11-14 11:36
ping @mrjana 

I think this is a known issue, but not sure if it is currently documented and if there are any plans to fix.

**Comment by mavenugo** [comment] 2016-11-14 12:34
@KevinTHU @justincormack Yes. its a known behavior for kernels < 3.14 and this is documented under https://docs.docker.com/engine/swarm/networking/

```
The --subnet flag specifies the subnet for use with the overlay network. When you don’t specify a subnet, the swarm manager automatically chooses a subnet and assigns it to the network. On some older kernels, including kernel 3.10, automatically assigned addresses may overlap with another subnet in your infrastructure. Such overlaps can cause connectivity issues or failures with containers connected to the network.
```

**Comment by thaJeztah** [comment] 2016-11-14 14:58
Looks like this question was answered, and unfortunately not something we can fix for older kernels, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2016-11-14 14:58 UTC
Labels: area/networking, version/1.12

**Comment by KevinTHU** [comment] 2016-11-14 16:19
@mavenugo ok, overlay may have kernel problem with the same ipaddress used in two network issue, however we could setup an options for plugin networks which can have same ipaddress in different network, like sdn vxlan, or network with virtual router in different vlan, overlap IP address is allowed in this kind of network driver.

**Comment by aboch** [comment] 2016-11-14 17:22
@KevinTHU 

What you see, ipam driver refusing to dispense the same address from the same pool (`Address already in use`), is the expected behavior. Because you chose the same address pool from the same address space (default) for both networks.

Given the ipam is separated from network plumbing in docker, to satisfy your requirement you'd need to specify an address space when requesting the same address pool. 

The ipam api handle this, but the UX has not enabled this functionality yet. So all the address pool requests will happen on the default address space for the network's scope (global,local).
