### ISSUE TITLE
Docker sending network request to wrong containers

### ISSUE THREAD

**Issue by mutex007** [docker/docker#21699] opened 2016-03-31 20:02 UTC
I am just observing a very strange issue where say containers
1 --> port 2401
2 --> port 2402
3 --> port 2403

When i send an http request to 127.0.0.1:2401. Somehow the traffic goes to 127.0.0.1:2402

I then stop container 1 and then traffic goes to 2404 as requested. However after a few minutes, 

Container 1 starts itself again without any docker start request explicitly. When container 1 starts itself, it then accepts any incomming request.

Any thoughts on this?

**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 152
Images: 33
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 491
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 31.36 GiB
Name: buf460
ID: YFXS:R7GN:SAIB:F5Z3:TW24:H7QS:ELJP:5ENZ:2EP3:C7KW:RZSW:CK7H
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment] 2016-03-31 23:41
Please explain these steps, how the containers are setup, etc.

**Comment by mutex007** [comment] 2016-04-01 00:46
Containers are created running a light http server. I use the remote api although the request always originates from localhost to create the container. Each container has its assigned port say 2401:80. 80 is used in the container but 2401 is exposed on the host for the container. Now i noticed a very weird behavior this morning. I made a request to container on port 2402 and for some reason i received the response expected from container 2401. I was in disbelieve so i SSH into the server and curl using 127.0.01. To my surprise container 2402 appears to not be receiving the request but somehow goes to 2401. Just to ensure this is not a typo. i run docker stop crazy_hypatia to stop container on 2401. Now when i ping container 127.0.0.1:2402, it is responding as expected. I leave the host untouched and attend to something else. I then ping 2402 again, to my surprise it is returning the response of 2401 again. I quickly do a docker ps -a and i noticed container 2401 has started itself without an explicit docker start. There is nothing on the host that will start a container. Before this day when i stop containers they remain stopped until i start them explicitly. Now when container 2401 starts itself, the issue happens again where it somehow appears to be receiving request for container 2402. 

I have to mention only these two containers on the host are behaving this way. I even did docker rm to trash container 2401, But when i recreated it again with the 2401 port it is behaving the say way again.

The actual ports of the 2 containers are 2603 and 2617. That is in the above description 2401 actually is 2603 and 2402 is 2617 in my actual setup.

This issue just does not make sense to me in any regard.

**Comment by cpuguy83** [comment] 2016-04-01 00:56
It sounds like you've got something else starting these, perhaps systemd socket activation or something else.

**Comment by mutex007** [comment] 2016-04-01 01:03
I do not see systemd running as a process on the host. Unless there is another way to check. I used this commad: lsof -i -n | egrep 'COMMAND|LISTEN'

systemd is not running on the host.

**Comment by cpuguy83** [comment] 2016-04-01 01:10
@mutex007 That's just an example. Docker is not going to start a container unless you told it to (including if by chance it has a restart polocy assigned to it).

I really can't help troubleshoot without the full details of your setup, full repro steps, etc.

**Comment by mutex007** [comment] 2016-04-01 01:27
Hmm i guess i am on my own here. My setup has a daemon which receives a remote request to create a container and then makes an http request via local host to the docker daemon to create the container. It also receives a request to restart and also kill containers as well. It does so as expected for cpu and memory stats the daemon retrieves directly from /fs/cgroups. The remote api is not scalable for this since we talking 100+ containers here. This is exactly the setup. Oh and to check if the container is up. it does docker ps -a via process.start this is c# mono. Reads the output and parse it to get the container state. Previously this was done by using remote api again this also is unscalable and super slow to even if we make asynchronous calls to the docker daemon it can take almost 30 seconds to respond. This is all that is been done. Nothing fancy at all.

Hope this gives you a general idea of my setup

**Comment by mutex007** [comment] 2016-04-05 23:12
Issue just happened again today!

I just make a request to a container and it simply goes to the wrong container.

Any help much appreciated

**Comment by mutex007** [comment] 2016-04-06 00:54
Restart the docker daemon. Issue not happening. But i expect it in another week again.

**Comment by mutex007** [comment] 2016-04-16 02:26
Using host networking solves the problem for me now. Wierd!

**Comment by mutex007** [comment] 2016-05-01 00:11
By the way guys issue 22325 is exactly the problem i reported weeks ago. I spent days blaming myself this could never be a docker issue because somebody would have long reported it.

In my case i almost lost my job when a client opened his website and to his amazement another clients website was showing up, i had to beg to keep my job.

The only way out of this issue is to use host networking.

**Comment by anttiviljami** [comment] 2016-05-01 11:39
@mutex007: I believe we are both experiencing the same problem here. see: #22325 

A very similar thing happened to us in our production environment, where a wrong web service was being served via port used by another service. Thankfully our monitoring noticed this before any of our users did, which would have been absolutely catastrophic.

Although seemigly rare, this problem can be devastating as was in @mutex007's case.

I'm currently looking for a way to reliably reproduce this behaviour on the current docker stable version in a test environment, but have yet to observe this bug.  

@mutex007 can you tell anything else special about your environment, like are you running any other services that modify iptables rules e.g. ufw? Are you running the docker daemon with the `--bip` flag like us? The one thing that seems relevant here, seems to be that we are both running upwards of a 100 containers with host port mappings.

**Comment by herikx2k3** [comment] 2016-05-02 16:02
@anttiviljami : For our use case there are no services that will modify the iptables rules. We also only use the -g parameter with the docker daemon. Our setup uses the default bridge Ip. I was just the other day considering maybe changing the --bip will solve the problem as well but opted for host networking.

To add to this, it was also never an issue in our case for i believe 3 + weeks when we started using docker and had under 100 container, but after exceeding 100 containers on the host, i noticed this issue as well. I am unable to reproduce it even if i create 200 containers and rm then randomly. But if i was to switch back to bridge networking, within 4 days it will be an issue again as i have documented on this thread.

@cpuguy83  i am not trolling here, this is a legit issue. I still stand by my word, docker started containers i have stopped whenever this issue happens.

**Comment by shlomikushchi** [comment] 2016-10-26 09:58
Hello
I seem to experience the same issue.
I am using:
Docker version 1.12.2, build bb80604
docker-compose version 1.8.1, build 004ddae
docker-machine version 0.8.2, build e18a919

on a Windows 10 host. 
I am running 2 Django(v1.9.7) web services with this configuration:
backend server:
docker run --net="mynetwork" -v `pwd`/backend:/opt/project backend -p 8000:8000 python manage.py runserver 0.0.0.0:8000
frontend server:
docker run --net="mynetwork" -v `pwd`/frontend:/opt/project frontend -p 7777:7777 python manage.py runserver 0.0.0.0:7777

when trying to access my server I some of the times routed to the correct server and some of the times routed to the wrong server. 
it is reproducible and happen every time. 

a small video on youtube to demonstrate the issue:
https://www.youtube.com/watch?v=3iIstDEb8eY
when reaching the 404 in the video - it is the wrong django server.

@mutex007, @cpuguy83, @anttiviljami  is there a workaround to that issue?

I will be happy to provide more information to resolve this issue.

**Comment by mutex007** [comment] 2016-10-28 02:59
The only workaround i have found it to use **host networking**. I have tested with almost all docker versions starting from 1.9.1 on two linux distributions centos, and ubuntu and the issue persists for me.

**Comment by shlomikushchi** [comment] 2016-10-28 11:39
what exactly is host networking?
do you mean running the container like this:
docker run --net=host ... ?

that means we don't have network isolation, right?

and, since this issue was opened in March, do you know of any plans to fix it?
this is not a minor issue.

**Comment by aboch** [comment] 2016-10-28 21:50
@mutex007 I agree with @anttiviljami this looks the same as #22325.
Given 22325 gathered more attention and did not go through multiple steps to eventually identify the issue, I would close this issue as a dupe.

Also, for the sake of fixing this problem, it would be great if you and others could post over there if you can find a consistent way to reproduce this problem, better with latest docker 1.12.3. So far I was not able to reproduce.

Thanks

**Comment by thaJeztah** [comment] 2016-10-28 22:45
okay, lets close this one in favor of https://github.com/docker/docker/issues/22325, so that we can have the discussion in a single place

**Closed by thaJeztah** 2016-10-28 22:45 UTC
Labels: area/networking, version/1.9
