### ISSUE TITLE
docker cluster-advertise port seems not respect

### ISSUE THREAD

**Issue by HackToday** [docker/docker#22026] opened 2016-04-14 08:45 UTC
**Output of `docker version`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: overlay bridge null host
Kernel Version: 3.19.0-58-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: workone
ID: PJ4B:5XJT:QCLI:KI4Y:6ZFT:HNJQ:KIUH:ZTMH:QLEC:DR3M:6XRH:2BLY
WARNING: No swap limit support
Labels:
 com.function=worker01
Cluster store: consul://<consul ip>:8500
Cluster advertise: <node ip>:4000
```

**Output of `docker info`:**

```
1.10.3
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. install docker
2. configure docker with following

    DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --cluster-store=consul://<consul ip>:8500 --cluster-advertise=eth0:4000 --label=com.function=worker01"
**note**
    The above --cluster-advertise=eth0:4000 (port 4000 here)
3. create overlay network

**Describe the results you received:**
Docker overlay network can work, created

**Describe the results you expected:**
4000 port seems not needed, it sems it should be 2375, while 4000 still can work,  Seems it is not used here

**Comment by HackToday** [comment] 2016-04-14 14:46
ping @mavenugo

**Comment by cpuguy83** [comment] 2016-04-14 15:55
@HackToday Yes, networking doesn't need the specified port. This would be needed for swarm discovery, though.

Closing as this is as intended.

**Closed by cpuguy83** 2016-04-14 15:55 UTC

**Comment by HackToday** [comment] 2016-04-15 00:34
hi @cpuguy83 the issue is that I used swarm, I did not find wrong port have any issue in my swarm cluster.
Could you specify what's discovery used for ?

**Comment by HackToday** [comment] 2016-04-15 00:37
as swarm nodes join cluster use `swarm join --advertise=<ip>:2375`
I did not think that separate port is also for discovery, it was introduced for overlay network. Not for discovery nodes, I think.

**Comment by cpuguy83** [comment] 2016-04-15 00:40
@HackToday IIRC `swarm join` is optional.

**Comment by HackToday** [comment] 2016-04-15 02:16
from swarm code I could see

```
 29 
 30     addr := c.String("advertise")
 31     if addr == "" {
 32         log.Fatal("missing mandatory --advertise flag")
 33     }
 34     if !checkAddrFormat(addr) {
 35         log.Fatal("--advertise should be of the form ip:port or hostname:port")
 36     }
```

**Comment by HackToday** [comment] 2016-04-15 02:20
/cc @aboch  @vieux 

Could you tell me is cluster-advertise designed for overlay network or for swarm ?

I am confused by that.  Thanks

**Comment by cpuguy83** [comment] 2016-04-15 02:28
@HackToday it was designed for node discovery which both use.

**Comment by HackToday** [comment] 2016-04-15 03:11
still the question not confirmed,  @cpuguy83  the --cluster-advertise=eth0:4000 wrong port seems not have any issue
