### ISSUE TITLE
Problem:  RestartPolicy & stopped container

### ISSUE THREAD

**Issue by sunyc** [docker/docker#12626] opened 2015-04-22 08:03 UTC
Hi there,

I Discovered that if I have a container created with "RestartPolicy": always,  Then I use docker stop xxx on that container. After a reboot, docker daemon will still restart that container. 

This has caused some problem for me since whenever I update my software, I stop the previous container and start a new one, i was expecting that docker will not restart the stopped ones. 

There are several ways I see can solve the problem, please let me know which you prefer

A) Have a API to modify container restart policy on-the-fly, so I can tell docker to nolonger restart it.
B) Have a --no-restart in docker stop /API , that tells docker to change restartpoilcy for the container
C) Move RestartPolicy to start container API, and don't let docker remember it.

**Comment by phemmer** [comment] 2015-04-22 12:32
This looks like a dup of #11008

**Comment by cpuguy83** [comment] 2015-04-22 13:02
Yep, dup, closing.  Thanks for the report!

**Closed by cpuguy83** 2015-04-22 13:02 UTC

**Comment by thaJeztah** [comment] 2015-04-22 13:03
Thanks for looking up, @phemmer!

@sunyc, I'm going to close this issue, because this is a duplicate of https://github.com/docker/docker/issues/11008. Please continue the discussion on that issue. Thanks for reporting!
