### ISSUE TITLE
Volume over an existing file can't be declared unless bind is present in create-time host config

### ISSUE THREAD

**Issue by shin-** [docker/docker#12759] opened 2015-04-24 18:46 UTC
Originally reported here: https://github.com/docker/docker-py/issues/546

The following command fails:
```
$ curl -i localhost:8567/v1.18/containers/create -H 'Content-Type: application/json' -d '{"Volumes": {"/etc/issue": {}}, "Cmd": ["cat", "/etc/issue"], "HostConfig": null, "Image": "busybox"}
```

with

```
'HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
Date: Fri, 24 Apr 2015 18:37:46 GMT
Content-Length: 142

file exists at /var/lib/docker/aufs/mnt/599f79015b6b0bf1fa39e5660f22fc396b0d8c88d07771d2af91983f1220532f/etc/issue, can't create volume there
```

However, if I add a Binds entry in my `HostConfig` like such:
```
curl -i localhost:8567/v1.18/containers/create -H 'Content-Type: application/json' -d '{"Volumes": {"/etc/issue": {}},  "Cmd": ["cat", "/etc/issue"], "Image": "busybox", "HostConfig": {"Binds": ["/etc/issue:/etc/issue:ro"]}}'
```

this works

```
HTTP/1.1 201 Created
Content-Type: application/json
Date: Fri, 24 Apr 2015 18:40:41 GMT
Content-Length: 90

{"Id":"5c1cdf1ed70764a831fd43673ddde77eaf2d18964163870fa90741c472130c44","Warnings":null}
```

as expected

```
$ docker start 5c1cdf
5c1cdf
$ docker logs 5c1cdf
Ubuntu 14.04.2 LTS \n \l
```

This essentially means it is impossible to provide the `Binds` configuration to the `/containers/<name>/start` endpoint in that use-case, which is a bit confusing. Can this be explained/documented?

**Comment by cpuguy83** [comment] 2015-04-24 19:33
This is because the container would error out when trying to mount the dir over the file anyway, so instead we're catching beforehand.

**Comment by cpuguy83** [comment] 2015-07-22 14:12
Closing since this is expected behavior.
Note that there is no need to specify `/etc/issue` anywhere except in the `Binds` config.

**Closed by cpuguy83** 2015-07-22 14:12 UTC
