### ISSUE TITLE
Create container and connect multi-networks

### ISSUE THREAD

**Issue by baptistedonaux** [docker/docker#19413] opened 2016-01-18 16:52 UTC
Currently (1.9.1), I can create one container and associate it at one network.

Via ```docker network connect my_network my_container```, I can associate others networks at my container.

In the 1.10 milestone, I don't find issue which propose ```--net``` flag which takes multi-networks.

**Comment by mavenugo** [comment] 2016-01-18 16:55
this is a duplicate of https://github.com/docker/docker/pull/17796.

**Closed** 2016-01-18 16:58 UTC
