### ISSUE TITLE
Cannot mount file with number in name

### ISSUE THREAD

**Issue by mkurek** [docker/docker#13670] opened 2015-06-02 18:18 UTC
Description of problem:
Docker throw an error when trying to mount file with number at the end of the filename

`docker version`:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

`docker info`:
```
Containers: 21
Images: 293
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 335
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 4
Total Memory: 1.957 GiB
Name: boot2docker
ID: 245Y:APHH:XQNI:DUE6:S5RE:MHDE:6HML:TCZF:FQBY:MFR6:4OXA:2VCJ
Debug mode (server): true
Debug mode (client): false
Fds: 16
Goroutines: 24
System Time: Tue Jun  2 18:12:35 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```

`uname -a`:
```
Darwin mac-mk.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

Environment details (AWS, VirtualBox, physical, etc.):
Local environment (with boot2docker)

How reproducible:
Always

Steps to Reproduce:
1. `touch db.sqlite3`
2. `docker run -it -v $(pwd)/db.sqlite3:/root/db.sqlite ubuntu /bin/bash`

Actual Results:

```
Code: System error

Message: not a directory

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@29
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@29
---
6: main
Package: runtime
File: proc.go@63
---
7: goexit
Package: runtime
File: asm_amd64.s@2232
FATA[0000] Error response from daemon: Cannot start container 99392c205737fa025b32540628e4b79c3c9ecc2d8222b8d5f152e86eb1614ff1: [8] System error: not a directory
```

**Comment by thaJeztah** [comment] 2015-06-02 18:33
I'm unable to reproduce this on docker 1.7.0-rc1, running on Ubuntu.

Does the same case work without problems if the file does *not* end with a number?

Also, seeing you're running boot2docker, this can be related, because boot2docker uses VBox shares to share your hosts directory with the boot2docker virtual machine (and there are still quite some issues around that).

Which directory are you running the `docker run` from? Is it inside the `/Users` directory?

**Comment by mkurek** [comment] 2015-06-02 18:38
I'm also unable to reproduce it on Ubuntu (in AWS, docker 1.6.0).
Yes - if I change filename and it isn't ending with number (ex. `db.sqlite`) everything works fine. 
I'm running this inside my user directory (`/Users/<my-user-name>/...`).

**Comment by thaJeztah** [comment] 2015-06-02 18:46
Interesting. Doesn't really narrow down what's causing this. Hm lemme think. What happens if you ssh into the boot2docker VM and try to do the same from within the VM? If that also doesn't work, that should allow us to remove OS X and VBox share from the list.

**Comment by mkurek** [comment] 2015-06-02 18:53
After ssh'ing into boot2docker and following specified steps everything works correctly:
```
boot2docker ssh
(inside boot2docker)
docker@boot2docker:~$ touch db.sqlite3
docker@boot2docker:~$ docker run -it -v $(pwd)/db.sqlite3:/root/db.sqlite ubuntu /bin/bash
root@19bf4946d89d:/# (inside container)
```

So probably it's related to boot2docker. Should i close this issue and start a new one in boot2docker repo?

**Comment by thaJeztah** [comment] 2015-06-02 19:20
Could still be the docker client, running on OS X, or OS X itself
Hm, tough one

ping @tianon @SvenDowideit ever seen this?

**Comment by micahhausler** [comment] 2015-07-06 17:55
I'm able to reproduce this. It's a weird combination, but I am hitting it when it seems like I shouldn't. I'm glad to provide any more info if needed.

## Versions
```
$ boot2docker version
Boot2Docker-cli version: v1.7.0
Git commit: 7d89508

$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

$ uname -a
Darwin Micahs-MacBook-Pro.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
# Yosemite 10.10.4

$ docker-compose --version
docker-compose version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014
```

## `docker-compose.yml`
```yaml
zk1:
  image: micahhausler/docker-zookeeper:3.5.0
  hostname: zk1
  environment:
    SERVICE_NAME: zk
    SERVICE_TAGS: zk1
  volumes:
    - ./myid1:/tmp/zookeeper/myid
    - ./zoo1.cfg:/opt/zookeeper/conf/zoo.cfg
```

## `zoo1.cfg`
```cfg
tickTime=2000
initLimit=10
syncLimit=5
dataDir=/tmp/zookeeper
clientPort=2181
autopurge.snapRetainCount=4
autopurge.purgeInterval=1
server.1=zk1:2888:3888
```

## Steps to reproduce
### Setup
```
$ ls 
docker-compose.yml  # the one from above
zoo1.cfg
```
###  Reproduce
```
docker-compose up -d
docker-compose kill
rmdir myid1
echo 1 > myid1
docker-compose up
docker-compose kill
docker-compose rm -f
docker-compose up
# Creating zk_zk1_1...
# Cannot start container e9a456f5e1e6be2192800af24e673fabf65e1699100082530498c6631a24bac8: [8] System error: not a directory
```

```
$ docker logs e9a456f5e1e6be2192800af24e673fabf65e1699100082530498c6631a24bac8
Timestamp: 2015-07-06 17:53:45.426150632 +0000 UTC
Code: System error

Message: not a directory

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@37
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@228
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@30
---
6
```

**Comment by forsetia** [comment] 2015-07-20 11:11
Confirmed this issue using boot2docker as per above using hyphens.
Mount point destination mgmt-users.properties (fails) 
Mount point destination mgmtusers.properties (works).

**Comment by newhook** [comment] 2015-08-13 12:48
Using the following also causes issues:

deploy@vagrant-ubuntu-trusty-64:/etc/apt/sources.list.d$ docker run --rm -p 24224:24224 -v /home/deploy/deployed/fluentd/config/fluentd.conf:/fluentd/etc/    fluent/fluentd:latest
Error response from daemon: Cannot start container 379f47ffc3d63e9199f675c7929aafe4463e16c41a397348a7d0e36b1c6bf61c: [8] System error: not a directory

This is problemetic as it is the directions on https://docs.docker.com/reference/logging/fluentd/

**Comment by eleweek** [comment] 2015-08-31 18:02
I just had a similar problem on OS X with boot2docker, docker-machine 0.4.0 and docker 1.8.1. It seems that restarting the boot2docker VM helped.

My filepath didn't include any numbers though, and the issue was with a single specific filepath, but it seems like it may be related to this issue. After spending a couple of hours on this, I wasn't able to exactly pinpoint why it was happenning(not was I able to reproduce it).

**Comment by noderunner** [comment] 2015-09-03 13:13
Also saw this on docker 1.8.1. Same thing as eleweek. No numbers in path, restart of docker-machine fixed it.

**Comment by tomcoonen** [comment] 2015-09-10 06:47
Can also confirm this issue here, reboot of the docker-machine worked. I had a number in a directory of a volume.

**Comment by myyk** [comment] 2015-10-08 23:16
I had the same issue. It was also fixed with a reboot of the docker-machine.

    🍕: docker-machine --version
    docker-machine version 0.4.1 (HEAD)

    🍕: docker --version
    Docker version 1.8.2, build 0a8c2e3

**Comment by shuron** [comment] 2015-11-07 15:39
I don't have docker-machine even installed.. but i get this with `docker-compose up` on 
nginx:
  image: nginx
  volumes:
    - nginx.conf:/etc/nginx/nginx.conf
  ports:
    - 80:80

Version Compose:
```
docker-compose version: 1.5.0
```
Version Docker:
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64
```
Error i see:
```
ERROR: Cannot start container 39a095fd1243c766e9e8f39d2572855cb412d66d5f74846dcd5aed8c45cddf62: [8] System error: not a directory
```
It's very frustrating right now.

**Comment by Stephenitis** [comment] 2015-11-11 01:11
I'm seeing this issue on ubuntu 14.04 on amazon
```
root@ip-10-0-166-96:~# docker logs a68f88138bb7
Timestamp: 2015-11-11 00:59:50.210064418 +0000 UTC
Code: System error

Message: not a directory

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@242
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@63
---
7: goexit
Package: runtime
File: asm_amd64.s@2232
```

I'm using kubernetes to launch a docker pod.

```
apiVersion: v1
kind: Pod
metadata:
  name: flocker-pod-only-creation
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
          # name must match the volume name below
          - name: www-pod-only
            mountPath: "/usr/share/nginx/html"
  volumes:
    - name: www-pod-only
      flocker:
        datasetName: my-flocker-pod-only-vol
```

**Comment by thaJeztah** [comment] 2015-11-11 09:12
@Stephenitis are you able to reproduce your issue without using Kubernetes? Otherwise it's perhaps better to check with Kubernetes first

**Comment by dgmstuart** [comment] 2015-11-30 13:08
Escaping the dashes fixed this for me. This is very odd. Are filenames with dashes not recommended? (e.g `docker-compose-entrypoint.sh`)

**Comment by wangyumi** [comment] 2015-12-08 07:03
I ran into this error as well when I try to start a redis sentinel in docker

yuwang@SZX1000051675:~/consul_ha$docker run -d  --net=host --name redis-sentinel \
                -v `pwd`/resolv.conf:/etc/resolv.conf \
                -v `pwd`/sentinel.conf:/data/sentinel.conf \
                redis:3.0.5 redis-server /data/sentinel.conf --sentinel

yuwang@SZX1000051675:~/consul_ha$ docker logs sentinel
Timestamp: 2015-12-08 14:55:29.077877335 +0800 CST
Code: System error

Message: not a directory

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@242
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@63
yuwang@SZX1000051675:~/consul_ha$ docker logs sentinel
Timestamp: 2015-12-08 14:55:29.077877335 +0800 CST
Code: System error

Message: not a directory

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@242
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@63
---
7: goexit
Package: runtime
File: asm_amd64.s@2232

My env:

yuwang@SZX1000051675:~/consul_ha$ uname -a
Linux SZX1000051675 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
yuwang@SZX1000051675:~/consul_ha$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64


I guess it is related to mount local file into the container, and stop & rm container and run it again.

**Comment by johnjelinek** [comment] 2015-12-09 04:25
I'm having this error too. My mount name does not include a number.

**Comment by marcolinoas** [comment] 2015-12-14 17:47
I got this error on centos 7. Turns out one of the files I was trying to use was in fact an directory. Fixing the wrong argument to be a file fixed the problem

**Comment by ysde** [comment] 2015-12-20 15:24
I have the same problem when I want to mount a file to the contaner：
 docker run --name test -d -p 8888:8888 -v /tmp/test/nginx.conf:/usr/local/nginx/conf/nginx.conf some_image.

Error response from daemon: Cannot start container fb7a32649b98672e25f83fdfb22162690e68c0b70855c90b863837da7f11c735: [8] System error: not a directory.

Docker version 1.8.1, build d12ea79
docker-machine version 0.4.1 (e2c88d6)

By the way, does anyone know how to restart docker-machine on OSX ? 
I want to try the method metioned above to solve this error, but couldn't find the way to restart docker-machine on OSX.

Thank you

**Comment by johnjelinek** [comment] 2015-12-20 16:36
`docker-machinedocker-machine restart default`



—

**Comment by asdfsx** [comment] 2015-12-22 10:11
I got the same problem, when I try to mount a local file!
I'm using docker 1.9.1

**Comment by aldenpeterson-wf** [comment] 2016-02-29 20:10
This is reproduceable when using the -v flag and mounting a file, as well.

Docker version 1.10.1, build 9e83765

**Comment by balmoovel** [comment] 2016-03-01 11:36
confirmed that this happens (sometimes) when mounting a file on osx, confirmed that restarting the docker-machine solves the issue

**Comment by ror6ax** [comment] 2016-03-14 14:07
```
  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - app
      - elasticsearch
    volumes_from:
      - app
    volumes:
      - /var/lib/jenkins/jobs/integration_gamify/workspace/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - log stash
```

I have this error only on nginx container in a big compose file. Removing container, restarting does not help.

**Comment by ror6ax** [comment] 2016-03-14 14:20
Does anyone look into this? If it's open since summer 2015, I might as well plan to stop using nginx :)

**Comment by cpuguy83** [comment] 2016-03-14 14:33
The `not a directory` `SystemError` is because the path you've asked to mount in is a directory and the path in the container is a file.

**Comment by aldenpeterson-wf** [comment] 2016-03-14 14:41
@cpuguy83  is it a bug that you can some of the time directly mount files with `-v`?

I think I'm confused about expected functionality here. The more I think about it, the less mounting a file as a "volume" makes sense conceptually, yet it definitely is possible (and something I've definitely taken advantage of for config files) -- but only some of the time..

**Comment by cpuguy83** [comment] 2016-03-14 14:43
@aldenpeterson-wf Not a bug, but you can't mount a dir over a file, or a file over a dir.

**Comment by ror6ax** [comment] 2016-03-14 14:46
leaving files out:
```
      - /var/lib/jenkins/jobs/integration/workspace/nginx.conf:/etc/nginx/nginx.conf
```

```
2016/03/14 14:44:58 [crit] 1#0: pread() "/etc/nginx/nginx.conf" failed (21: Is a directory)
nginx: [crit] pread() "/etc/nginx/nginx.conf" failed (21: Is a directory)
```

**Comment by cpuguy83** [comment] 2016-03-14 14:47
@ror6ax You've mounted a dir to a place that nginx is expecting a file.

**Comment by ror6ax** [comment] 2016-03-14 14:53
So what is the right way? File-file does not work because docker, dir-dir does not work because nginx?

**Comment by cpuguy83** [comment] 2016-03-14 14:56
@ror6ax A file works just fine. There is no bug here, you just have to make sure that file exists before creating the container.
Likewise, dir-dir would be fine, but you can't mount a dir to where nginx is expecting to read a file.

**Comment by cpuguy83** [comment] 2016-03-14 14:59
Closing this since it is user error, not a bug.

By default Docker creates a dir on the host if it is missing. This can be problematic if you are expecting a file to be there. This is why we have deprecated this auto-creation logic, and will (should) be removed in Docker 1.11 in favor of explicit create flags.

Also remember the first part of the bind (e.g. `foo` in `/foo:/bar`) is relative to the docker daemon and _not_ the client.

**Closed by cpuguy83** 2016-03-14 14:59 UTC

**Comment by ror6ax** [comment] 2016-03-14 15:06
My file /var/lib/jenkins/jobs/integration/workspace/nginx.conf does exist. It does not mount to Docker for some magic reasons which is quite distressing. 
What is more distressing, though, is I'm a commenter on two totally unconnected Docker issues and in both you guys do not even care to read multiple bug reports. You won't have much of a user base with that approach.

**Comment by cpuguy83** [comment] 2016-03-14 15:16
@ror6ax I've read this entire thread.
I'm sorry you don't understand the issue here, but let me try and help some more:

if you `docker run -v /foo:/bar` and `/foo` doesn't exist, docker will create a dir at `/foo` on the docker host and mount that into the container, otherwise it will just mount `/foo` to `/bar` in the container.

If `/foo` is a file (which it won't be if it didn't exist already) and `/bar` is a dir, you will get an error.
If `/bar` is a file and `/foo` is not, you will get an error.

`/foo` and `/bar` much match types. You can't mount a file onto a dir, and you can't mount a dir onto a file.

`/foo` is on the docker daemon host, **not** necessarily where the client is.
If you are running with docker client inside a container talking to a docker daemon running on the host (e.g. with the docker daemon socket mounted into the container), the `/foo` path is still relative to the daemon on the host, **not** inside the container.

Possibilties for mounts:

- existing dir -> existing dir
- non-existing dir -> existing dir
- non-existing dir -> non-existing dir
- existing file -> existing file
- existing file -> non-existing file

**Comment by aldenpeterson-wf** [comment] 2016-03-14 15:26
I don't really see how this is "user error" either. Perhaps @ror6ax 's issue is, but that is different than the initial report here regarding the number in filename (which I also have on OSX).

Docker having different functionality for mounting a file based on whether the file is named config.conf vs config0.conf seems like a bug. 

My error was reproducible on OS:X with docker-machine simply by adding a single character to the config file name (as shown above). Adding the 0 --> error. Removing it --> no error.

The config file did not exist in the target container, in either name.

I'm sorry, but seeing a "not a directory error" based on a file _name_ (which is the initial bug report here) is definitely a weird problem that does not seem  correlated to your reason for closing the report.

**Comment by cpuguy83** [comment] 2016-03-14 15:58
@aldenpeterson-wf Also not seeing this with numbers (on either side of the bind specification).
Does it only happen with vbox? What version of vbox are you using? (for the record, I'm on a docker-machine created vbox VM)

**Comment by tloist** [comment] 2016-04-01 14:17
I think I experienced the same error, but in my case it was not directly related to having a number in the file name. I couldn't mount a file on the host over a file in the container. Regardless of whether it existed in the container before or not.

I could fix the problem by restarting the docker machine (`docker-machine restart default`).
What was odd was, that I was able to mount the file if I changed the filename on the host.
It doesn't matter if I included a number, it just had to be different.

Mounting `ldap.properties` -> `ldap.properties` failed.
`ldap.prop` -> `ldap.properties` or `foo.properties` -> `ldap.properties` worked, even before restarting the virtual machine.

Finally I am happy after restarting the docker machine, but it seems to me that there is a relation to the involved filename?
I am using `Docker version 1.10.2, build c3959b1`, `docker-machine version 0.6.0, build e27fb87` and `VirtualBox 5.0.8r103449`.

**Comment by Izhaki** [comment] 2017-07-04 14:12
Jumping in really late here, but like @ror6ax, the following configuration threw an error:

```
version: '3'
services:

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
```

This is when using a docker-machine, and everything @cpuguy83 makes sense if you understand that `./nginx/nginx.conf` is not a reference to your local machine, but to the docker-machine (so the file won't exist there, a directory will be created, and docker will complain).
