### ISSUE TITLE
CMD and ENTRYPOINT: shell form should print a warning

### ISSUE THREAD

**Issue by MichaelBitard** [docker/docker#12315] opened 2015-04-12 19:16 UTC
As you can see in this blog post: http://agileek.github.io/docker/2015/04/12/docker-cmd/

When we use the shell form for CMD, it's wrapped around a /bin/sh which doesn't forward signals (according to the documentation), leading to potential big data loss or file corruption on production environment.

Since the most intuitive syntax is the most dangerous one, we think a warning message should appear when building a docker file with this syntax. (Why not deprecate it by the way?)

**Comment by phemmer** [comment] 2015-04-12 19:50
The shell syntax can be perfectly safe (with regards to signals) if used properly:

    CMD exec java -jar docker-stop-test-0.1-SNAPSHOT.jar

**Comment by thaJeztah** [comment] 2015-04-12 20:13
I think a warning would be taking this too far. I understand that, without proper knowledge, people can shoot themselves in the foot with the shell notation. However, there are proper uses of the shell notation (as @phemmer showed), and there are many other things that people can shoot themselves in the foot with.

Perhaps some extra/better explanation and/or examples in the documentation?

**Comment by MichaelBitard** [comment] 2015-04-12 21:10
@phemmer Yes, i know that with the `exec` syntax it's safe, I was just pointing out that the intuitive syntax (the command you would run within your terminal) is not the right one in CMD or ENTRYPOINT and can lead to a lot of trouble. This is explained in the documentation: https://docs.docker.com/reference/builder/#entrypoint but it's not very accessible.

Is there a way to browse into the Dockerfiles of the hub? We could see if a lot of images use CMD in shell form without exec. It could be a good indicator.

**Comment by thaJeztah** [comment] 2015-04-12 21:18
> Is there a way to browse into the Dockerfiles of the hub? We could see if a lot of images use CMD in shell form without exec. It could be a good indicator.

No, but I know @duglin recently ran some tests against a long list of Dockerfiles collected from GitHub

**Comment by cpuguy83** [comment] 2015-09-15 15:05
Closing because this is expected behavior and is not different than writing something like an init script.
We can't throw a warning just because someone used the shell syntax. It should be expected to use exec here.

**Closed by cpuguy83** 2015-09-15 15:05 UTC
Labels: area/builder, kind/enhancement
