### ISSUE TITLE
docker rm succeeds even if underlying operations failed

### ISSUE THREAD

**Issue by rhvgoyal** [docker/docker#10955] opened 2015-02-23 19:40 UTC
Looks like docker rm does not care if any of the underlying operations needed to complete the remove operations succeeded or not. It goes on to remove the container anyway and leaving unrecoverable system resources if something failed.

For example, with device mapper backend, it can happen that device associated with rootfs of
container could not be removed. This can happen if device is busy. And device being busy can happen if somebody manually mounted the device somewhere else or for device mount point shows in some other process's namespace etc.

But docker removes the container from its data structures anyway. That means user can't see that container anymore in "docker ps -a" output. That means we left a device in device mapper thin pool which is consuming space in pool but we can't recover that space anymore.

This should be fixed. We should not remove container if any of the operations involved in removing
container fails. (I guess using --force should override this).

**Comment by rhvgoyal** [comment] 2015-02-23 19:48
I am looking at the removal code and it looks like that it might not be trivial to fix. The first thing we do is that remove the container from container store so that nobody can get access to this container and do any operations. 

        // Deregister the container before removing its directory, to avoid race conditions
        daemon.idIndex.Delete(container.ID)
        daemon.containers.Delete(container.ID)

Looks like it has been done to avoid races. But I am afraid that this is causing troubles with device mapper. 

We should instead mark the container as "BeingRemoved" and then fail any other operation on container if it is being removed.

And if any of the underlying operation fails, then move the container back to original state and fail the operation.

**Comment by estesp** [comment] 2015-02-24 15:17
See #10099 for prior discussion.  I would still like to make the whole deletion path more robust, but it is tricky to decide how to handle "rollback" or a new state.

**Comment by rhvgoyal** [comment] 2015-02-24 16:46
I liked the idea of coming up with a new state say "Remove Failed" and let user retry it later. 

I have run into situations where a device might leak into namespace of another container and hence removal of devicemapper device might fail. For example if one launches a privileged container with "-v /:/host", then any container which was running already their mount points become visible under /host/var/lib/docker/devicemapper/mnt/container_id/.

That means one can not remove a container till privileged container exits. It also means that if we remove the container from user view, then we have a leaked device which will be sitting in pool and never free space.

So I did not understand that what's wrong with giving a new state to a container which signifies container cleanup/deletion failed.  (Something like zombie process). And user should attempt to cleanup it later. Either problem would have resolved automatically (if it was device leaking into another namespace issue) or user will have to manually resolve the situation and then retry removal.

Removing container from user view without actually freeing the resources held by container sounds wrong to me.

@crosbymichael 

Can we please rethink about this issue. Why not leave the container in there with a special state if removal failed so that user can retry removal later.

**Comment by rhvgoyal** [comment] 2015-02-24 16:50
Also if device removal fails then we leave /var/lib/docker/devicemapper/metadata/<container_id> file in there. This is like docker bloating its own metadata while there is no way to reference it from top. So not only we left some resources which should have been freed, we have some stale docker metadata too and I will never promote a user manually fiddling with docker metadata. 

Keeping that in mind, it makes sense to me to create a new container state to represent failed removal and allow user to try it later.

In fact we have forced removal optoin "-f". Right now this stops a running container before removing. May be in case of -f, we could always remove container even if there were errors releasing the resources held by container.

**Comment by rhvgoyal** [comment] 2015-02-24 18:11
To give more details,  this is what I did with docker using devicemapper graph driver.

- Launch a container.
  docker run -ti fedora /bin/bash

- Launch another container with root mounted at /host.

   docker run -v /:/host -ti fedora /bin/bash

- Now try exiting first container. It takes 10 seconds as it keeps on trying to remove thin device but that device has not leaked into second container namespace so it can't be deactivated. And for that 10 seconds other docker operations like "docker ps -a" hang.

- Now try deleting first container.
  docker rm <first-container>

I get following error.

$ docker rm 98ba41570210
Error response from daemon: Cannot destroy container 98ba41570210: Driver devicemapper failed to remove root filesystem 98ba415702102c2fe075bf18a03af9a74cfbda8b27e90d445cea295de4f30d7b: Device is Busy
FATA[0010] Error: failed to remove one or more containers 

But when I do "docker ps -a " container is gone leaving behind leaked thin device. So on one hand docker tells me that "Failed to remove one or more containers", on the other hand it removed the container from its list. This is not a behavior consistent with the message.

**Comment by jfrazelle** [comment] 2015-02-28 03:21
duplicate of https://github.com/docker/docker/issues/6746

**Closed by jfrazelle** 2015-02-28 03:21 UTC
