### ISSUE TITLE
No caching for ADD instruction via HTTP

### ISSUE THREAD

**Issue by alexellis** [docker/docker#30401] opened 2017-01-24 10:51 UTC
**Description**

I've searched issues for "cache add http" but didn't find anything relevant. This may be a dupe.

Instructions like the following don't appear to be cached, but RUN instructions invoking `curl` do get cached.

`Step 4 : ADD https://storage.googleapis.com/golang/go1.7.4.linux-armv6l.tar.gz ./` 

The net effect is that this very useful way of downloading for a container becomes slow / repetitive / wasteful.

**Steps to reproduce the issue:**
1. Use `ADD http(s):// ./` in a Dockerfile

**Describe the results you received:**

No caching of instruction

**Describe the results you expected:**

Caching on subsequent runs similar to the use of `curl`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 19:06:36 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 19:06:36 2016
 OS/Arch:      linux/arm
```

Same behaviour on other Docker engine/CLI versions.

**Comment by thaJeztah** [comment] 2017-01-24 15:01
Looks like this is a duplicate of https://github.com/docker/docker/issues/15717; also see the issues linked from that issue (which contain some prior discussion)

I'll close this one 👍

**Closed by thaJeztah** 2017-01-24 15:01 UTC
Labels: area/builder, version/1.12
