### ISSUE TITLE
Illegal regex in generated apparmor profile

### ISSUE THREAD

**Issue by haco20292** [docker/docker#19018] opened 2015-12-31 14:17 UTC
docker version: Docker version 1.9.1, build a34a1d5
DEB package: docker-engine amd64 1.9.1-0~trusty

There's a bug in repository package for ubuntu-trusty. /etc/apparmor.d/docker generated by docker contains a line:
```
  deny @{PROC}/{*,**^[0-9*],sys/kernel/shm*} wkx,
```
But in github repository, it's
```
  deny @{PROC}/{*,**^[0-9]*,sys/kernel/shm*} wkx
```

**Comment by thaJeztah** [comment] 2015-12-31 14:53
Yes, this looks like a duplicate of  https://github.com/docker/docker/issues/17783, and is fixed in https://github.com/docker/docker/pull/18239, which will be in the upcoming 1.10 release.

I'll close this, because this will be fixed in 1.10

**Closed by thaJeztah** 2015-12-31 14:53 UTC

**Comment by haco20292** [comment] 2015-12-31 15:17
Sorry for duplicate.

**Comment by thaJeztah** [comment] 2015-12-31 16:40
@haco20292 no problem, thanks for finding the issue :)
