### ISSUE TITLE
Nested volumes

### ISSUE THREAD

**Issue by ls42** [docker/docker#26929] opened 2016-09-26 20:30 UTC
**Description**

When starting a container from inside a container, and the files are in a volume that's passed down from `Host OS -> First Container (VIM) -> Second Container (Python3)`, the I cannot access the files in the second container.

The call chain is like this:

* `docker run --rm -ti -v $sock_path:$sock_path -v $PWD:/src -w /src brauer/vim vim $1`
* `docker run --rm -v $PWD:/src -w /src brauer/python python $current_file_in_vim` (From Inside the VIM container like this: `autocmd FileType python set makeprg=docker\ run\ --rm\ -v\ $PWD:/src\ -w\ /src\ brauer/python\ python\ %`)

**Steps to reproduce the issue:**
1. Pull `brauer/vim`
2. `cd ~/path/to/python_project`
3.

    { 
        sock_path="/var/run/docker.sock";
        docker run --rm -ti -v $sock_path:$sock_path -v $PWD:/src -w /src brauer/vim vim $1
    }

4. `dvim pythonfile.py`
5. In VIM, enter `:make!` and Enter (or Press `\r`)

**Describe the results you received:**

Not being able to access the shared files inside the second level container. The message from python is:

`python: can't open file 'kpf.py': [Errno 2] No such file or directory`

**Describe the results you expected:**

Being able to access the files exactly as I am when running this in a non-containerized VIM.

**Output of `docker version`:**

$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

`$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 7
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.818 GiB
Name: moby
ID: CXSE:UE67:7WJE:5FGR:2H3U:WEE7:7LMF:JOUG:ATGN:GOYE:JOY6:TPRU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 43
 System Time: 2016-09-26T20:14:58.521669403Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: brauer
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Same issue on macOS, debian and ubuntu 16.04 (latest linux versions from dockerproject.org)

The auth.log on linux is not saying anything when spawning the second level container.

**Comment by dnephin** [comment] 2016-09-26 21:02
I've run into this before, the problem is with the paths you are using.

When  `docker run --rm -v $PWD:/src ...` is run from the container you're sending `-v /src:/src` to the docker daemon. The daemon tries to accept `/src/` on the host, but I believe you files are not in `/src` on the host, they are in some other directory.

The workaround that I've used is to always use the host working directory as the container path in the first docker container `-v $PWD:$PWD -w $PWD`.  That way when you run `docker run` from a container the paths will match the host paths, and you should see the files you expect.

A more complete solution is being tracked in #21622

**Comment by ls42** [comment] 2016-09-27 05:40
Well, this is a fine workaround, since it's working for me. I'm tracking #21622, it's okay for me if this is closed.

Thanks!

**Comment by dnephin** [comment] 2016-09-27 13:42
Great, I'm glad it's working. Going to close this issue since we have others for tracking a solution.

**Closed by dnephin** 2016-09-27 13:42 UTC
Labels: area/cli, kind/question, version/1.12
