### ISSUE TITLE
Error during Container Creation

### ISSUE THREAD

**Issue by brian-bason** [docker/docker#23184] opened 2016-06-02 00:55 UTC
I would like to report an issue on Docker during the creation of a container (extraction of downloaded images).

I was creating a new container in my Docker Host with a stack of images which were not on the host yet so they were downloaded from our private Docker Registry. During the extraction process of the images to the local hard drive I had a power failure and thus the creation of the container was interrupted. When I tried to restart the process again, after I powered the device, the process failed when it was trying to extract the images to local drive. The issue can be seen below.

d38575f188e0: Pull complete 
b04ea90f261c: Extracting [==================================================>] 71.48 kB/71.48 kB
40dc9cd44ffa: Download complete 
a3ed95caeb02: Download complete 
8e785886e18d: Download complete 
b07fa5f3bf49: Download complete 
f468d5b9f05f: Download complete 
794bd688a6d9: Download complete 
8bbe83ec74cb: Download complete 
1233bc44b903: Download complete 
085e07914846: Download complete 
failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/layer-389359348 /var/lib/docker/image/aufs/layerdb/sha256/68bad316357227af4d130e4e6b73a25b69984bdbdec8fc581990ac56aa04b3ca: directory not empty

How to replicate

Start a creation of an container with images that are not on the local drive yet (docker create --name example --restart=always --stop-signal=INT private-docker-registry/example:1.1.0)
During the extraction of the downloaded images interrupt the process with a power failure (or by killing the process)
Try to restart the creation of the container again issuing the same command as used in step one
When the process comes to the extraction step it will fail with the reported issue.

It would be great if the process can determine if the current folder that exists for the image is corrupted or incomplete and if so delete it to create the new folder again. This would make sure that the host doesn’t end in this limbo state where you have to SSH into the box to delete the folder manually before re-trying the command.

**Comment by HackToday** [comment] 2016-06-02 01:47
Not sure if I understand it correctly or not,

```
^Cubuntu@testdevstack:~/workplace/docker$ docker create --name example1 --restart=always mysql
Unable to find image 'mysql:latest' locally
latest: Pulling from library/mysql

a3ed95caeb02: Download complete 
260d7505d8f9: Download complete 
a65f47c75fe3: Waiting 
729d0217f8db: Waiting 
6dcf95bf56d1: Waiting 
e9e6fbca5bcb: Waiting 
6197f83904fb: Waiting 
fd7e3b75ae7f: Waiting 
fe9a3ecc0ca9: Waiting 
310227c7e00d: Waiting 
6eda8dacf10a: Waiting 
^Cubuntu@testdevstack:~/workplace/docker$ docker create --name example1 --restart=always mysql
Unable to find image 'mysql:latest' locally
latest: Pulling from library/mysql
51f5c6a04d83: Pull complete 
a3ed95caeb02: Pull complete 
260d7505d8f9: Pull complete 
a65f47c75fe3: Pull complete 
729d0217f8db: Pull complete 
6dcf95bf56d1: Pull complete 
e9e6fbca5bcb: Pull complete 
6197f83904fb: Pull complete 
fd7e3b75ae7f: Extracting [=======================>                           ] 32.31 MB/68.22 MB
fe9a3ecc0ca9: Download complete 
310227c7e00d: Download complete 
6eda8dacf10a: Download complete 
^Cubuntu@testdevstack:~/workplace/docker$ docker create --name example1 --restart=always mysql
Unable to find image 'mysql:latest' locally
latest: Pulling from library/mysql
51f5c6a04d83: Pull complete 
a3ed95caeb02: Pull complete 
260d7505d8f9: Pull complete 
a65f47c75fe3: Pull complete 
729d0217f8db: Pull complete 
6dcf95bf56d1: Pull complete 
e9e6fbca5bcb: Pull complete 
6197f83904fb: Pull complete 
fd7e3b75ae7f: Pull complete 
fe9a3ecc0ca9: Pull complete 
310227c7e00d: Pull complete 
6eda8dacf10a: Pull complete 
Digest: sha256:b2f400f4a5e003b0543decf61a0a010939f3fba07bafa226f11ed7b5f1e81237
Status: Downloaded newer image for mysql:latest
37301bc0a0d38e7f8d309731eab02168a72a124e51bf7443edb47839e2a8ae13
```

It seems can interrupt docker create and run again and again. I used docker 1.10.2

**Comment by brian-bason** [comment] 2016-06-02 04:22
I was using docker 1.11.0

Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Could it be that it was introduced an a recent release?

**Comment by brian-bason** [comment] 2016-06-16 12:11
Any feedback on this issue?

**Comment by thaJeztah** [comment] 2016-06-17 03:41
@tonistiigi any thoughts?

**Comment by tonistiigi** [comment] 2016-06-17 17:20
@dmcgowan Isn't the commit logic protecting against the target directory existing in an incomplete state. If not then maybe we should do some cleanup if `loadLayer` fails.

**Comment by dmcgowan** [comment] 2016-06-20 16:04
@tonistiigi: the commit logic is supposed to keep it from getting in this state. Either way it is probably helpful to attempt cleanup on a layer if `loadLayer` fails, if we can be certain the directory is in a corrupted state.

@brian-bason: to help us figure out what may be causing the bug can you send the daemon's debug logs during startup. I expect to see a "Failed to load layer: ....".  Sending the files from `/var/lib/docker/image/aufs/layerdb/sha256/68bad316357227af4d130e4e6b73a25b69984bdbdec8fc581990ac56aa04b3ca` may also be useful if you have not already removed that directory. I expect removing that directory will allow the operations to be completed successfully.

**Comment by brian-bason** [comment] 2016-06-23 02:03
@dmcgowan Unfortunately I have decommissioned that machine as I was using it only for testing and have since returned it to administration. But yes once I deleted the directory `/var/lib/docker/image/aufs/layerdb/sha256/68bad316357227af4d130e4e6b73a25b69984bdbdec8fc581990ac56aa04b3ca` and tried again the operation was successful.

**Comment by brian-bason** [comment] 2016-07-28 07:01
Any updates on this issue please

**Comment by dmcgowan** [comment] 2016-07-28 21:24
@brian-bason: have you seen this issue again? Unfortunately with this issue, since it represents a bad state on disk, I need to see more engine logs to understand how it got in this state. This would include engine logs before any possible ungraceful shutdown and any startup logs. We already have code in place to protect against this state in normal ungraceful shutdown scenarios, so we need to figure out what the anomalous condition was so we can test against it. If you are no longer reproducing this issue and it has been fixed on the current host, then I will just mark this issue as needs more information and leave it open for others who may encounter this error.

**Comment by xueshanf** [comment] 2016-08-04 21:40
@dmcgowan: you asked files on disk, I happened to have an issue opened in #23487 as well. The file list is like so:
```
# ls -l /var/lib/docker/image/overlay/layerdb/sha256/2d90fb8f617bf974548cbe33226ed5a677056637f02cc4196fcffac66debABCD

-rw-r--r-- 1 root root 0 Jun 24 00:01 cache-id
-rw-r--r-- 1 root root 0 Jun 24 00:01 diff
-rw-r--r-- 1 root root 0 Jun 24 00:01 parent
-rw-r--r-- 1 root root 0 Jun 24 00:01 size
-rw-r--r-- 1 root root 0 Jun 24 00:01 tar-split.json.gz
```
This seems happens after upgrading to docker 1.10.x. It's not easy to reproduce, but in my case, it seems happened after random reboot.

**Comment by tonistiigi** [comment] 2016-08-04 22:55
@dmcgowan All these https://github.com/docker/docker/blob/master/layer/filestore.go#L88-L112 writes should probably also do fsync.

@xueshanf Can you post your `cat /proc/1/mountinfo`? Only interested about the mountpoint where `/var/lib/docker` exists.

**Comment by xueshanf** [comment] 2016-08-05 06:36
@tonistiigi here is the mountinfo:
```
core@ip-10-x-x-x ~ $ cat /proc/1/mountinfo | grep docker
284 58 202:16 / /var/lib/docker rw,relatime shared:233 - ext4 /dev/xvdb rw,seclabel,data=ordered
```
Also:
```
$ mount  | grep docker
/dev/xvdb on /var/lib/docker type ext4 (rw,relatime,seclabel,data=ordered)
```
```

**Comment by kovalevsky** [comment] 2016-08-05 14:35
I faced the same issue on Debian 8. Conditions are similar. During the extraction of the downloaded images server was rebooted, sad but true. 

Image extracting log: 

    Pulling redis (redis:latest)...
    latest: Pulling from library/redis
    357ea8c3d80b: Already exists
    7a9b1293eb21: Pull complete
    f306a5223db9: Pull complete
    18f7595fe693: Pull complete
    a9a3bf83ed85: Pull complete
    bc38414eb438: Extracting [==================================================>]     98 B/98 B
    3ee3ab1b6aa1: Download complete
    ERROR: failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/layer-110300610 /var/lib/docker/image/aufs/layerdb/sha256/240c2fa17866a823d26d9eb7771e181a88b14a022449f0fc7b6d1f45cf9f4d73: directory not empty
    sk@p6:/u/docker/meta/sentry$ packet_write_wait: Connection to 144.76.140.144: Broken pipe

I posted details of the environment in another issue: https://github.com/docker/docker/issues/23487#issuecomment-237580615. If you will need any further information, please contact, I will be glad to provide it.

**Comment by dmcgowan** [comment] 2016-08-08 16:39
@tonistiigi: I will make a patch to do the fsync. Do you have any idea how doing multiple fsyncs in serial would impact performance? I could try and call them in goroutines and wait until they complete before doing the rename, but I don't see the benefit of that approach if we are just bound by waiting for them to be serially written to disk.

**Comment by tonistiigi** [comment] 2016-08-08 16:41
@dmcgowan 

> Do you have any idea how doing multiple fsyncs in serial would impact performance?

Don't know. I also expected `data=ordered` to help but I guess it doesn't help in this case because we are not renaming the same file the data is written into.

**Comment by marek-obuchowicz** [comment] 2016-10-28 11:18
What is status of this issue? Is there any information I could provide to help fixing it?
IT's happening on:
```
# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 36
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.63 GiB
Name: spryker-vm
ID: PFIB:WLOZ:ERM2:GTYV:UQD7:3GP7:CXG4:YYJF:BTTJ:3WDY:PUBH:XT4D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: siroopdeploy
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Comment by tonistiigi** [comment] 2016-11-08 22:51
@dmcgowan This was fixed with #25523, right?

**Comment by dmcgowan** [comment] 2016-11-08 23:01
@tonistiigi I think so, since we weren't able to get a dump of the files in this bad state it is hard to say that was the root clause. I would suggest we close this issue since the potential fix will go out in 1.13. If someone else has a similar issue we can ask that the `/var/lib/docker/image/` directory is kept to help root cause.

**Closed** 2016-11-08 23:02 UTC
Labels: area/distribution, kind/bug

**Comment by zhan849** [comment] 2017-01-18 06:18
@dmcgowan I just reproduced this issue in docker 1.11.2 I have `/var/lib/docker/image` information persisted. What do you need for debugging?

Error: failed to register layer: rename /mnt/ephemeral/docker/image/aufs/layerdb/tmp/layer-642760651 /mnt/ephemeral/docker/image/aufs/layerdb/sha256/acc1ad8cffe3a39d72dcdbfee470e19ac6af41eb864eb5d23f68fb3938e00e99: directory not empty

Docker info:
docker info
Containers: 49
 Running: 21
 Paused: 0
 Stopped: 28
Images: 7
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/ephemeral/docker/aufs
 Backing Filesystem: extfs
 Dirs: 185
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.51 GiB
Name: ip-10-144-7-114
ID: ETLC:B3BD:XIBX:HRW7:ENLE:EJOM:I755:N33H:Q6SJ:M3CX:QKIF:BRJQ
Docker Root Dir: /mnt/ephemeral/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Comment by dmcgowan** [comment] 2017-01-18 20:03
@zhan849 fix will be in 1.13.0

**Comment by adamgotterer** [comment] 2017-01-23 16:56
I just install 1.13.0 and I'm still seeing the issue

**Comment by tonistiigi** [comment] 2017-01-23 17:48
@adamgotterer Is this a new machine or upgrade to a machine that had the issue before on a specific image. The fix doesn't change the already corrupted data but fixes it so that new corruption should not appear.

**Comment by adamgotterer** [comment] 2017-01-24 01:08
This was an update to an existing machine with an existing issue. There was actually no way to recover from the issue, I tried blowing away all images and layers. Ended up having to factory reset docker. But the problem hasn't come back in 1.13.0.

**Comment by joeygibson** [comment] 2017-02-27 15:22
I'm seeing this on macOS Sierra (10.12.3), with Docker for Mac (Version 1.13.1-beta42 (15350) Channel: beta 2ffb2b4915), which I installed this morning. This was an upgrade from a previous install. I did a factory reset, and now it works.
