### ISSUE TITLE
How rebuild or re-init the nat rules after iptables -t nat -F?

### ISSUE THREAD

**Issue by lovemyliwu** [docker/docker#29323] opened 2016-12-12 09:39 UTC
googling seems only restart the engine by `sudo service docker restart` can do that.

**Comment by thaJeztah** [comment] 2016-12-12 09:44
Correct, the IPTables rules are set when starting the daemon.

Since this is not a bug report, but a support question I'll close this issue; the GitHub issue tracker is intended for bug-reports and feature requests; for other type of issues, please consider using;

- https://forums.docker.com
- the docker community slack channel; https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/

But feel free to comment after I closed

**Closed by thaJeztah** 2016-12-12 09:44 UTC
