### ISSUE TITLE
DOCKER_OPTS not working

### ISSUE THREAD

**Issue by sodre90** [docker/docker#24271] opened 2016-07-02 18:42 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:53:33 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:53:33 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Steps to reproduce the issue:**
1. install 1.12.0-rc3
2. modify /etc/default/docker (eg: DOCKER_OPTS="--storage-driver=overlay2")
3. docker daemon is not running with these additional arguments

**Additional information you deem important (e.g. issue happens only occasionally):**
Tested on Ubuntu 16.04 and CentOS 7

**Comment by miaoyq** [comment] 2016-07-03 01:36
@sodre90   Did you  restart the docker daemon,after modifying `/etc/default/docker`?   if not, please restart the docker daemon, try again.

**Comment by thaJeztah** [comment] 2016-07-03 05:47
The `/etc/default/docker` file is only used for systems using upstart or sysvinit; see the comment at the top of that file; https://github.com/docker/docker/blob/master/contrib/init/sysvinit-debian/docker.default#L1-L8. Both Ubuntu 16.04 and CentOS 7 use systemd, so don't use this file.

The easiest way to configure the daemon, is to use a `/etc/docker/daemon.json` configuration file; https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file

Alternatively, use a systemd drop-in file, as explained in [this section of the documentation](https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options)

I'll close this issue, because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-07-03 05:47 UTC
Labels: version/1.12
