### ISSUE TITLE
docker Error response from daemon: Unexpected status code [403]

### ISSUE THREAD

**Issue by asethia** [docker/docker#19397] opened 2016-01-17 16:08 UTC
I am not able to use docker login, I am getting following error on windows 7:

docker Error response from daemon: Unexpected status code [403] : <html><body><h1>403 Forbidden</h1> Request forbidden by administrative rules.

The docker info output as following:

Containers: 33
Images: 72
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 138
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: RC3R:5SO6:2GB2:WDVQ:OZAJ:Y3DQ:42G4:QJGA:6OWB:A6LV:3RBK:3R2N
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 19
 System Time: 2016-01-17T16:01:58.156840755Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: asethia
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

**Comment by asethia** [comment] 2016-01-17 16:09
WIndows 7
virtualbox - 4.3.34
docker toolbox - 1.9.1

**Comment by runcom** [comment] 2016-01-17 16:11
duplicate of #18019, fix should be in https://github.com/docker/docker/pull/19264
closing

**Closed by runcom** 2016-01-17 16:11 UTC
Labels: group/windows

**Comment by asethia** [comment] 2016-01-17 16:28
I tried these fixes, the login works after appying windows fixes but push still does not work

docker version:

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

docker info:

Containers: 33
Images: 72
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 138
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: WOYS:3DAK:LSU2:QLRD:W5MV:EUFF:URPS:QZYQ:WRN5:BCUM:MHSO:CZKD
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 19
 System Time: 2016-01-17T16:27:49.845319977Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

Provide additional environment details  : windows 7 64 bit desktop

**Comment by runcom** [comment] 2016-01-17 16:31
@asethia could you please report your findings to the linked PR?

**Comment by runcom** [comment] 2016-01-17 16:31
cool, you did thx

**Comment by asethia** [comment] 2016-01-17 16:34
Thanks. If I apply fix defined at https://github.com/docker/hub-feedback/issues/473 , the login works but push does not.
