### ISSUE TITLE
Unable to remove volume when container creation fails

### ISSUE THREAD

**Issue by mbentley** [docker/docker#22093] opened 2016-04-16 13:37 UTC
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:22:26 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:22:26 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.0
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 502.3 MB
 Data Space Total: 8.338 GB
 Data Space Available: 7.836 GB
 Metadata Space Used: 299 kB
 Metadata Space Total: 641.7 MB
 Metadata Space Available: 641.4 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.120 (2016-03-11)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.963 GiB
Name: localdev
ID: 2GH4:KUEP:Q5HH:I6T7:KZM6:2AOC:MA5S:QSVV:FJ72:IPR5:7ABX:4MR2
Docker Root Dir: /data/docker/devicemapper-thin
Debug mode (client): false
Debug mode (server): false
Username: mbentley
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Debian Sid running in VirtualBox

**Steps to reproduce the issue:**

1. Try to create a container with multiple volumes but try to mount them to the same location in the container (which will fail):

    ```
    $ docker run -d -v test:/data -v test2:/data alpine sh
    docker: Error response from daemon: Duplicate mount point '/data'.
    See 'docker run --help'.
    ```

2. Try to remove the volume that was created:

    ```
    $ docker volume ls
    DRIVER              VOLUME NAME
    local               test
    $ docker volume rm test
    Error response from daemon: Unable to remove volume, volume still in use: remove test: volume is in use - [ac641c4577bc210e6ed41c8a580074300de7d342e5f78332cbdd71532b11ab0c]
    ```

3. The mentioned container doesn't exist:

    ```
    $ docker ps -a
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
    ```

**Describe the results you received:**
```
$ docker volume rm test
Error response from daemon: Unable to remove volume, volume still in use: remove test: volume is in use - [60fb24fdee552e54d0b884592ee616277c7c14eb8c2f2d6e4b7e53c36f531c04]
```

**Describe the results you expected:**
Volume should be removable as it isn't in use by a container

**Additional information you deem important (e.g. issue happens only occasionally):**
If you restart the daemon, you can remove the volume but that should not be necessary

**Comment by icecrime** [comment] 2016-04-16 15:28
Thanks Matt! Any idea if this is a regression introduced by 1.11.0?

**Comment by mbentley** [comment] 2016-04-16 18:18
No problem!  Glad to accidentally do stuff one shouldn't ;)
Doesn't look like it is a regression; I am also able to reproduce in `1.10.3` and `1.9.1` as well.

**Comment by thaJeztah** [comment] 2016-04-16 19:50
ping @cpuguy83 could you have a look at this?

**Comment by coolljt0725** [comment] 2016-04-17 15:20
try a fix in #22103 , just wonder should we try to  remove the volume if failed to create the container?

**Comment by mbentley** [comment] 2016-04-20 13:05
Thanks! I'll give this a try as soon as I can. I would expect the volume to be removed only if it did not already exist.

**Comment by mbentley** [comment] 2016-04-25 16:23
@coolljt0725 - It looks like it is working as expected, thanks!

**Comment by crook** [comment] 2016-05-18 08:28
I met the same issue. Does this issue have been fixed??

~~~
docker info
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 4
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 44
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local flocker
 Network: host bridge null
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.798 GiB
Name: flocker-1
ID: XTQN:5P6P:MOAD:7GVK:6HMP:ZZRG:GMEP:QCUU:X5R7:TN27:WTD4:O67E
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

root@flocker-1:/#docker volume create --name RayDemo -d flocker
RayDemo
root@flocker-1:/# docker volume inspect RayDemo
[
    {
        "Name": "RayDemo",
        "Driver": "flocker",
        "Mountpoint": "",
        "Labels": {}
    }
]

root@flocker-1:/#docker run --name RayTest  -P --volume-driver=flocker  -v RayDemo:/data -t -i ubuntu /bin/bash
docker: Error response from daemon: Timed out waiting for dataset to mount..

root@flocker-1:/# docker volume rm RayDemo
Error response from daemon: Unable to remove volume, volume still in use: remove RayDemo: volume is in use - [ace515688bdb431c23a7db52048cc35ecc53f07bcd8bd84b5b4bc956028fce05]


~~~

**Comment by thaJeztah** [comment] 2016-05-18 08:35
@crook the linked PR was not merged yet (https://github.com/docker/docker/issues/22103)

**Comment by crook** [comment] 2016-05-19 03:13
@thaJeztah thanks for reply. BTW, do you have any comments about 'docker run' command failed?

```
root@flocker-1:/#docker run --name RayTest  -P --volume-driver=flocker  -v RayDemo:/data -t -i ubuntu /bin/bash
docker: Error response from daemon: Timed out waiting for dataset to mount..
```

**Comment by thaJeztah** [comment] 2016-05-19 08:33
@crook that looks like an error coming from the Flocker plugin; https://github.com/ClusterHQ/flocker/blob/6e670f13e892c92074074c41c867223b7d6a2a55/flocker/dockerplugin/_api.py#L343

**Comment by oleersoy** [comment] 2016-05-23 16:36
I'm also having issue with this although each volume was mounted to a separate / discrete directory.  Here's the output I get when trying to remove a volume:

        ole@MKI: docker volume rm v1
        Error response from daemon: Unable to remove volume, volume still in use: remove v1: volume is in use - [df378cd5af781b1d8b31867706acd45dee7dcedcef306551d6938899362c5839, a8c360868b90450c1e19ab7c8bd10128e76389f100d67176947463f8d2b40710, 12c484481efde354b90e74191a4a1918072b9bf5a988e579195d78cd72987211, d40e4a75e3e0df4be5b6f10e18ba4b11aaabc093cc1f1a23d313180b85b3d90d, 08f4a84d0ab0fd4936df63260ae44a756f2e6873dff84c73fff363a87732b912, 9cb5081d348aa4730c27113535704136784ce16c513a465eaf078d67ece77c46, 43926fe633dad45241af601b286bdb23c8d622cd11cbfa44596b2dd2aa79ffa4, 097f3a4a59c4f40475cead94ff91a777227e5108fb76072a158ef221f2cfff48, 4d0e4ce926f61632614d32dd7826be68c9049e4d08232e1035271cb620efb274, f3587db834cc8410bc7bb0ae62379f1bc65c34f42528351aac3ead783412631d, e80c389d1e8a53053a20e5aaba4f24010ad4465cb1753c5cbc237406e29ad355, a90e0857538b434d9c789c6661d8a2640520b516925db050a8504990ddef4823, b28f1b7c333bf034ab8c1acb467be2169e5db9f281b1287eb3a82ea2c295b865, 347d1953ad50a27b065559e9dbb24d58cbecab11ee2804757de7dc8af6f1775d, 16a97686bb965d57d388ebf4b65a0a0ed87a007049fc1c2f0437ed73d4f0c616, a6efbf2138596774f9c637ee0f5db17a27b24b8fda782f2ae1dbd606d82bc070, e6762c44a137de6af72678530b2d0f284687749ad0feb76638843c46286b7c7a, eaa5b745c45200667ffa52c71025642a7b5489ebe9f52e6b0d03b2e0a9e8297a, 3090d683046ca60bbc5ce5e644081011a30a5435f900423410f0d873f2167e29, 53d7ef9055eede3cdab91e597d3b154124c6fd32087e427fab414cf418771838, bad57c319c888010c506350ff88a0f11850e95a9b036ae4b2dd4d52d108cc86a, ead45085ce54fa3c2dc625f588bef530a6a08e63cf48e349afd24f47e4916579, c2b63265d565832c60f7d22629cf80757022c6edf895b66203435bc1627d3962, 5442ed12cd80c744128f676c9b3dbc7e9c1416980a52e635a89aadf77a704711, bd7e966dd594d932e8a1841b11e95a0fb71166131c581c66f80ca1cb20a09e3f, 95d8a3743e5c9b6b7a0b829a60f95175b5f8590e8f8a98429a7f1620db67be54, 18908247f965b66986f123875ac3d327282dd0c48ea67a793a6e72fe4d801a6c, 0a76e50ffa89c76c2a54c019d1f47e2ff9a14b639419b820bb33fe1721937c21, 663418fe367a610eb5fd8bf60e2701651db53b3dc00b997267818baeca0f3271, 087198df2f742329cb6d8cdabc1aae7b7d7c5fd247af2206faaa636a9b5e0832, 16422957b9ec4b5d479bf4f23147016c34e6405434cfbd29f9f991f616612927, fab6df1b4dc57330d12ec8f0cde3d95dcfa18a944efc14743ce136fa09e06f51, dd7b5dba2bb64778c0bd7903b3b19f2708dce6a0dd5f1e5c0db5b1ce6caf192d, ec0e26aebeb06b767e2662dab81af2686481b9cb93ecdd254b038d9172152e79, 8a2d96feb8ba4e492fbc831b3c496c271dcbee414fe60a2ba09efc62438c4842, f6f2cdaef5f44b01e0813beb863f6b536c7bc98312789961c81f6f427f11955f, a7eb839e7fb00e13023c102e830ec63a54e4328bdf2bfb4df8bbb4f216c5331d, 856373f6b269b26fac1b7234257897770b8b3daa87f9d358d5942703649f5551, 876c7c28880c267525f17635cf97b71bf9a017e05ef6633e8b4bb7517f2fa395, a0dfab0b451d815cda7419b5d75ae325669c8cd99a3b4d75243938b2ae98fc2f, c9baf3a0ed8d1062fdef9a7bdece066d537a815b47694f476b150a51b57a4715, 9b5ee7a78d1b8270dbc6b8605796360c0c95bd879742b464b39ef4cfb2256650, 8fb356426518ed1c8dedb42f487cc10da3e15724a60982249b300f231bb9ff2e, a78347189df96675def75bd54147f72fb04cef595a7db77c97150b3e49415209, b33c6df6793e930a307de8a1709147208944ceddb313094da363888004696d6e, 51cfcf7c8e2e638206cd1cc08c560fa7feedcc9d619945c5914a3f44e4af5a31, a5784689f4172b716ad372b6a339d024c2487226c20f322ee136c5c729566a4f, f7615388afa3231332998b35d898b13a8fcbd89aa3aad8598ab5201419805d47, ba8efafa65057c32b48a173d3b9ea963aed8465e8c1176609bd0a15050027457, 60e893f49311c330f9766945cd9f1b4670407234d69add6a9846c142cb3bc565, a00fb8dbf4471344c5d096472e1eb70f00e33fa2e6ce803966706752be619d78, c788076f994c6124593dd3d7b5cc75457a2945000ba07026e2c786fcb9d2e01e, 930b62771f8a6b401b423718f7a6c02ebd584a5c398a2a3b1ce37bf52c457950, 8597db45801a4d5a5d21a3ab504ead239b6c847935746969639bfdbcf1ee7d27, cb81e21d68406a36c366f9777595b06a9b6adbf3977ff456a25a728b7ef9ff66, 74a9bbaa9485e52a0f778136f09ba37be2d4b59e97e4fb51e8b4f5dda8990056, 30ceb2289aff59711b971946c253681b0a3fc426e2913664138b87e1e93d7c3f, 0aae897c182a9917e301342e54996a14d61a88093c424325235f08032db9b366, 201f55c5bb1a5a06817e38436990e8169a581ba52feda538da4192bbd54d3a35, a1e9fcf494c0d04a12d3ee06bf235b2e7ab7e703d2efd96839d0e6dad132c012, afba2dadd8538436e8e9f94f01652f24c402decd950c593310eab0ba65f30f70, 6a7b4c7c10849e61d0733e5141c2960b995e2e012867a63afbd15b288b7b9501, d06f76573e637d0be4757a5cad614865f0546657fc2b5e6d0cc200030823296a, 56faac610c184a69b5b8f7e32112b85d43130413a3bc152943a96a3dca51b80d, 9944f559fd4f192a15f175ed6d0ec62420593c615ad31776fb0ea7e80c36704d, 47733d469b3a6917db3f5c0accc13c475ffaae2b01d62d06f1a31aea241ca90c, 9be741d2924f90313c638596427402289d403490f33fef5d3733e7787c1be665, bf3553269838fc11283cc6d240c6e4349ac8acc9257c2559d67b746dec97c314, 6533ce54f0f9d136e1bbbbb2d498022cc0bc305535b27f48668a450023c03032, 701861ff8ada7f75378c350888656d22496064abce9b3d353a8b2ce6facc150c, bc19e0db0e08830ff66480d5bca19d1012595bb1fa2d2d0ec52f79859d227b3f, 05fa72d47073867b21f4d4dea16dc94b517da0fbdfbcef49dcf733fb82b7932f, d8da4b4e544b8132253ddf47748c3b2d828a96a0ba11462e7f20ae503b1e5a2f, bf156846a945714dfa9a432ee1d8937d6e3319a71a9ac321918c23b7d113a72e, a61e52bfb451dd2c4f28d82bb2fb607a7a33758c72b387255438ffce9b9d6677, 7c7b410a52ba001682301abe4ff43535acd974060dee250a6a94155a6fb78256, 1910d323ff4ec62929ec2efdc68d382ed8c3cc243e3f1a6d73f53856c7a7005f, 719f09636e388b7df9497f4dba406372848f03d6b03d4762ded21409a3322a07]

        ole@MKI: docker --version
        Docker version 1.11.1, build 5604cbe

**Comment by thaJeztah** [comment] 2016-05-23 18:30
@oleersoy that may not be a bug; it's docker telling you that there's still containers using it (and the list after that is the list of container-id's still using it)

**Comment by oleersoy** [comment] 2016-05-23 19:14
OK - Got it.  So I don't have any containers running, but I can grab one of the IDs and use it to start the container.  So I assume then that if a volume is mounted to a stopped container I cannot delete it?

**Comment by oleersoy** [comment] 2016-05-23 19:17
OK - Yup - I stopped and removed all the containers:
https://coderwall.com/p/ewk0mq/stop-remove-all-docker-containers

And the removed the volume and it worked.  Thanks for the heads up.

**Comment by thaJeztah** [comment] 2016-05-23 19:25
@oleersoy you're welcome!

**Closed** 2016-05-30 13:57 UTC
Labels: kind/bug, version/1.11

**Comment by nottrobin** [comment] 2016-09-05 10:07
Is there any way to detect which stopped containers are using the volume?

**Comment by thaJeztah** [comment] 2016-09-13 16:03
@nottrobin you can use the `--filter` option on `docker ps`, for example, this example shows all containers that are using the `foo` volume:

```
docker ps --filter volume=foo

CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
f13bc82248a8        busybox             "sh"                About a minute ago   Up About a minute                       dreamy_varahamihira
```

See the documentation here:
https://docs.docker.com/engine/reference/commandline/ps/#/volume
