### ISSUE TITLE
Docker in Debian 8 Jessie - half way working but have TLS issue.

### ISSUE THREAD

**Issue by daithi-coombes** [docker/docker#13029] opened 2015-05-06 19:30 UTC
Can't install docker in `Debian 8 Jessie`. The instructions here don't work: [Debian - Docker Documentation](https://docs.docker.com/installation/debian/#debian-jessie-80-64-bit) The package `docker.io` can't be found even with `backports` enabled.

I did eventually get the docker binary downloaded using the instructions [here](http://linuxconfig.org/package-docker-io-has-no-installation-candidate-debian-jessie).
```
$ docker -v
Docker version 1.6.0, build 4749651
$ uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux
```

But now there seems to be an issue with `TLS`, trying to run the `hello-world` container gives the following error:
```
$ docker run --rm hello-world
FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

Does docker need its own `certs`? I have noticed that there's no `~/.docker` folder in my home directory.

**Comment by daithi-coombes** [comment] 2015-05-06 19:36
viola... mins after posting, the docker daemon wasn't started (facepalm)
```
# service docker status
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; disabled)
   Active: inactive (dead)
     Docs: http://docs.docker.com
```

Solution:
```
# service docker start
```

Now running
```
$ docker run --rm hello-world
```
works!

But then, if the package mentioned in the `Debian - Docker Documentation` is actually non existent then I'd like to submit this a bug with the docs.

**Comment by schmunk42** [comment] 2015-05-08 09:27
$ docker run --rm hello-world
    FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

Just as a note: I get a similar error on some systems, when running docker without `sudo`. I am not sure if this is connected to the latest *jessie* release. Maybe it can be easily fixed by adding the current user to the `docker` group or did something change here?

**Comment by 3onyc** [comment] 2015-05-08 09:42
@schmunk42 correct, your user needs to be in the docker group to be able to access Docker, so try that first.

**Comment by daithi-coombes** [comment] 2015-05-08 11:29
Yeh, came across that. The issue I'm reporting though is that the documentation is wrong. In work atm but going to fork and do a `PR` on what worked for me when I get home, namely the instructions I found in this [article](http://linuxconfig.org/package-docker-io-has-no-installation-candidate-debian-jessie).

Documentation says to use `docker.io` package from `jessie backports` but this package doesn't exist. The above article says to install with `curl -sSL https://get.docker.com/ | sh` which works perfectly.

Also to add, that the article misses, is to start the docker daemon after install, or restart the machine `# service start docker`.

Hope to get working on PR in about 8hrs from now, prob won't get to finish it till tomorrow morn (gmt +0)

**Comment by schmunk42** [comment] 2015-05-08 17:57
> The above article says to install with curl -sSL https://get.docker.com/ | sh which works perfectly.

Since a few weeks I install all Linux (Ubuntu & Debian in my case) Docker-hosts with this command and not from the package manager. Because it works much more reliable than anything else so far, especially also for the aufs setup.

**Comment by daithi-coombes** [comment] 2015-05-08 22:19
Tried to create a `PR` on my fork but accidently created a merge request on `dockers`... sorry https://github.com/docker/docker/pull/13100

It would be great if the `get.docker.com` bash installer did work on all debian flavors, will try testing this in the morning

**Comment by vlcinsky** [comment] 2015-05-10 18:01
I have to confirm exactly the same problem: being on Debian Jessie 64bit I am unable to install docker.io following the instructions using jessie-backports, it does not find the package docker.io and complains "Package 'docker.io' has no installation candidate - Debian Jessie"

**Comment by thaJeztah** [comment] 2015-05-11 04:28
Turns out the docker.io package isn't in the back ports repo *yet*, see this discussion https://github.com/docker/docker/pull/13104 and this comment by the maintainer of the package https://github.com/docker/docker/pull/13104#issuecomment-100645071

The `curl -sSL https://get.docker.com/ | sh` should work though, and currently is the advised approach.

**Comment by kassanmoor** [comment] 2015-05-13 18:18
I try the curl aproach  but I get this error E: Unable to locate package apt-transport-htt any workaround? to install docker in jessie?

**Comment by vinceyuan** [comment] 2015-05-16 14:23
I followed @vlcinsky 's instructions to install Docker successfully on Debian Jessie 64bit.

**Comment by thaJeztah** [comment] 2015-05-16 18:16
The package should now (or very soon) be available in backports. See https://github.com/docker/docker/issues/13253#issuecomment-102660527

**Comment by thaJeztah** [comment] 2015-05-16 18:18
@daithi-coombes can you confirm if the issue has been resolved?

**Comment by andybarnes** [comment] 2015-05-19 08:11
I can confirm this is still not resolved as I have just opened a support ticket for this very problem. Fresh Debian 8 jessie install, added backports line, apt-get update and then apt-get install docker.io and it informs me there is no installation candidate.

`apt-get install docker.io`
`Reading package lists... Done`
`Building dependency tree`       
`Reading state information... Done`
`Package docker.io is not available, but is referred to by another package.`
`This may mean that the package is missing, has been obsoleted, or`
`is only available from another source`

`E: Package 'docker.io' has no installation candidate`

**Comment by DavidStaron** [comment] 2015-05-22 22:59
It might be useful to make a notice of this on the Docker download page?
( https://docs.docker.com/installation/debian/ )

Would save people time wondering/searching why it's not working...

**Comment by steveklabnik** [comment] 2015-06-05 10:00
It's still not in backports as of today.

**Comment by daithi-coombes** [comment] 2015-06-05 11:01
These instructions here worked for me: http://linuxconfig.org/package-docker-io-has-no-installation-candidate-debian-jessie

I made a `pr` to update the documentation but got stuck trying to follow their `git guidelines`...
https://github.com/docker/docker/pull/13100

Basically follow the the instructions [here](http://linuxconfig.org/package-docker-io-has-no-installation-candidate-debian-jessie), you may need to manually start the daemon afterwards:
```
sudo service docker start
```

**Comment by andybarnes** [comment] 2015-06-05 11:14
The way I got it on my system while I'm waiting was as follows:

`curl -sSL https://get.docker.com/ | sh`

**Comment by jfrazelle** [comment] 2015-07-10 21:48
it is now in backports

**Closed by jfrazelle** 2015-07-10 21:48 UTC
