### ISSUE TITLE
docker client how to select version?

### ISSUE THREAD

**Issue by torykit** [docker/docker#19724] opened 2016-01-26 15:08 UTC
![image](https://cloud.githubusercontent.com/assets/15373053/12584188/3e95d146-c481-11e5-9e02-e160c6d1cdee.png)

my docker server is in 192.168.1.2 and that api version is 1.20 , now I use a docker 1.21 client to visit.

but it return Error!  so can I select the api version?

**Comment by runcom** [comment] 2016-01-26 15:11
@torykit what version of docker are you using? I think from docker-1.10 you can prepend `DOCKER_API_VERSION=1.20` to docker commands, ping @duglin

**Comment by duglin** [comment] 2016-01-26 15:14
yup:
```
$ DOCKER_API_VERSION=1.18 docker version

Client:
 Version:      1.10.0-dev
 API version:  1.18
 Go version:   go1.5.3
 Git commit:   e5b5c0e
 Built:        Mon Jan 25 22:09:30 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   e5b5c0e
 Built:        Mon Jan 25 22:09:30 2016
 OS/Arch:      linux/amd64
```

**Comment by runcom** [comment] 2016-01-26 15:14
I'm closing this as it's not a bug btw, please come online on irc #docker, the forum or the mailing list to discuss this kind of things

**Closed by runcom** 2016-01-26 15:14 UTC
