### ISSUE TITLE
Do we have to mount cgroups when run Docker-in-Docker?

### ISSUE THREAD

**Issue by kiwenlau** [docker/docker#18960] opened 2015-12-29 12:47 UTC
I'm working on Docker-in-Docker. And I find that @LK4D4  removed the cgroups mounting in dind: [https://github.com/docker/docker/commit/81aa1b507f51901eafcfaad70a656da376cf937d](https://github.com/docker/docker/commit/81aa1b507f51901eafcfaad70a656da376cf937d)

Does this mean we don't have to mount cgroups when we want to run Docker-in-Docker?

However, according to @jpetazzo, we need to mount cgroups: [jpetazzo/dind](https://github.com/jpetazzo/dind)

I'm confused about this.

**Comment by thaJeztah** [comment] 2015-12-29 12:56
It was removed, because it should no longer be required to do this manually in recent versions of docker (see the comment that was removed in that commit: `"as of docker 1.8, cgroups will be mounted in the container"`).

However, depending on your use-case, this article may be of interest if you're planning to use docker-in-docker: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

I'm gonna close this issue because this is a question, not a bug-report or feature request, but feel free to comment here after I've closed

**Closed by thaJeztah** 2015-12-29 12:56 UTC

**Comment by kiwenlau** [comment] 2015-12-29 14:09
@thaJeztah Thank you. Very helpful.
