### ISSUE TITLE
Investigate gossip timeout issues

### ISSUE THREAD

**Issue by abronan** [docker/docker#24557] opened 2016-07-12 21:36 UTC
Using docker **master**

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Digital Ocean VMs:

*3 Managers*: 2 GB Memory / 40 GB Disk / Ubuntu 16.04 x64
*3 Agents*: 1 GB Memory / 30 GB Disk / Ubuntu 16.04 x64

**Steps to reproduce the issue:**

1. Just start a swarm cluster and schedule a few tasks

**Describe the results you received:**

Often, `memberlist` (gossip) will mark nodes as unhealthy even though they are healthy. **libnetwork** uses the default `timeout` value for the gossip which can be aggressive for some setups.

Error:

``` 
WARN[0442] 2016/07/12 17:19:52 [ERR] memberlist: Failed TCP fallback ping: read tcp X.X.X.X:54690->X.X.X.X:7946: i/o timeout
 
INFO[0448] 2016/07/12 17:19:58 [INFO] memberlist: Marking node06 as failed, suspect timeout reached
```

**Describe the results you expected:**

No error. Or at least very few false positives (which could happen in practice).

**Additional information you deem important (e.g. issue happens only occasionally):**

Making the timeout configurable should allow a user to configure this timeout according to their environment and get rid of those false positives.

**Comment by mrjana** [comment] 2016-07-14 16:42
@abronan Something weird is happening in this case. A TCP fallback ping failed with i/o timeout which is indicating some kind of underlying infrastructure issue or network congestion. We should never see TCP fallback ping failing unless there is severe problem in the infrastructure or the daemon is stuck in some weird state that it is not able to respond to the ping. We should debug it more to find the root cause of that.

**Comment by abronan** [comment] 2016-07-14 16:56
@mrjana I don't think the error on TCP is relevant, sometimes nodes are marked as failed even without those TCP errors (I'm on Digital Ocean btw). I think it's definitely network congestion as this can happen without doing any specific action but is definitely triggered when orchestrating tasks at a large scale (I have to debug this more but I suspect the orchestrator to be a resource hog as it is also blocking raft heartbeats after a `docker service scale` but I'll have to `pprof` to identify the true cause).

Looking at the code on libnetwork, I see that the `ProbeTimeout` is at `500ms` which is reasonable most of the time but when orchestrating a huge amount of tasks, this might crumble. And I'm not sure if the [AwarenessMaxMultiplier](https://github.com/hashicorp/memberlist/blob/cb98e9455b1dd02cd888d1e20175005e2e7f6d10/config.go#L114) is even used in this case.

Probe timeout should still be configurable and tunable I think as gossip largely depends on the Infrastructure and the default values may not be adapted. I'm catching up on libnetwork and looking into ways to tune the `ProbeTimeout` and `ProbeInterval`. If you also think it makes sense of course.

**Comment by thaJeztah** [comment] 2016-07-16 21:34
@tiborvass should we assign a priority to this one?

**Comment by aluzzardi** [comment] 2016-10-13 21:43
This issue hasn't happened in a long time - closing for now, will re-open if the problem occurs again

**Closed by aluzzardi** 2016-10-13 21:43 UTC
Labels: area/networking, area/swarm, priority/P2, version/master
