### ISSUE TITLE
Inconsistent source IPs in containers

### ISSUE THREAD

**Issue by discordianfish** [docker/docker#7540] opened 2014-08-12 12:16 UTC
Hi,

I'm running rsyslog in a container. Basically just an ubuntu image with rsyslogd installed and a template configuration like this:

    $template FILENAME,"/var/log/%fromhost-ip%/%hostname%/syslog.log"

Exposed ports in Dockerfile: `EXPOSE     514/tcp 514/udp`

Now this works in general just fine, but I discovered some strange behavior regarding the source IP of the syslog packets: Sometimes the messages for remote systems end up in `[remote-host-ip]/[container-hostname]/syslog.log`, then after some time, they end up in `[docker0-bridges-ip]/[container-hostname]/syslog.log`. This seems to flip around from now and then.

As far as I understand, the expected behavior is:

- If you connect to a exposed port from localhost, inside the container the source IP is the IP of the docker0 bridge
- If you connect to a exposed port from a remote system, the source IP is the IP of the remote system

But it seems somehow those packets get routed via the docker0 IP and sometimes not. This makes not only running a syslog server hard but also debugging request logs in general.

**Comment by grundleborg** [comment] 2015-04-11 19:10
I'm seeing this exact same behaviour with the source IP of packets reaching nginx inside a container. Sometimes they have 172.17.42.1 as the source address, and sometimes they have the actula remote address, and it seems to switch arbitrarily every few minutes. Is there any known workaround or fix for this, or is there any further investigation I can do that would help to find out what's wrong?

**Comment by discordianfish** [comment] 2015-04-11 20:08
@unclejack @jfrazelle I've heard we removed the userland proxy in 1.6? Is this the case or do we need more investigations into this issue here? @icecrime: If so, can we prioritize this somehow?

**Comment by grundleborg** [comment] 2015-04-11 20:20
FWIW I'm running docker 1.5.0 currently.

**Comment by jfrazelle** [comment] 2015-04-11 20:22
That's not until 1.7

**Comment by discordianfish** [comment] 2015-04-11 20:53
@jfrazelle I assume this solution to this issue is the removal of the userland proxy? Guess it doesn't make sense to spend resources on this until the userland proxy is removed.

**Comment by icecrime** [comment] 2015-04-12 15:09
@discordianfish Unfortunately we still cannot entirely remove userland proxy, but we have a PR under review to make it optional (we need to keep support for older RHEL). See PR #12165.

**Comment by discordianfish** [comment] 2015-04-13 10:00
@icecrime Okay, so if we still support this we should look into this problem here.

**Comment by grundleborg** [comment] 2015-04-19 21:29
I just noticed a pattern which may be relevant to this: I see the 172.17.42.1 source IP address when the connection from the remote host to the docker host is over IPv6. I'm not 100% about this, but it's a pattern that has held over a short spate of observations just now.

**Comment by discordianfish** [comment] 2015-04-20 10:53
@icecrime So can we get someone actively looking into this? I just removed the next service from docker because I suspect network problems.

**Comment by icecrime** [comment] 2015-04-20 22:40
@discordianfish I wish we could, we just don't have any spare minute... But I haven't forgotten about this.

**Comment by mavenugo** [comment] 2015-06-04 23:15
@discordianfish can you please confirm if you see this behavior only with userlandproxy mode enabled ?
https://github.com/docker/docker/pull/12165 brought in the support in the upcoming 1.7.0 release to make this an optional feature.

**Comment by discordianfish** [comment] 2015-06-04 23:38
@avinson: You see this currently with heka, right? Can you confirm this?

**Comment by avinson** [comment] 2015-06-12 00:35
i know it still affects heka logging as of 1.6 but i haven't tested 1.7 yet.. i'll do that asap

**Comment by avinson** [comment] 2015-06-12 00:36
@mavenugo what options should i run the heka (syslog equivalent) container with to disable userlandproxy mode?

**Comment by icecrime** [comment] 2015-06-12 02:28
@aaron 1.7.0 has the `--userland-proxy=false` daemon flag

**Comment by discordianfish** [comment] 2015-06-12 15:32
@icecrime Do we have documented what side effects that might have? Or does it simply require a recent kernel and things should just work?

**Comment by icecrime** [comment] 2015-06-12 16:43
@discordianfish There's no expected side effect that we know about.

**Comment by Insaned79** [comment] 2015-07-09 05:46
Using docker 1.7.0, kernel 3.13.0-48-generic.
Running container with such command:
docker ----userland-proxy=false run --name name - p 80:80 -d imagename 
I do not see the correct remote IP in the container. What am I doing wrong?

**Comment by ross-w** [comment] 2015-11-03 09:08
I'm not sure what's going on, but I'm seeing the same thing on Docker 1.8.3 with userland proxy disabled. Confirmed the userland proxy is not running, but I still only see eg 172.17.42.1 showing as the source IP inside the container for everything. Any pointers for how I might get the real IPs to show up?

**Comment by eskp** [comment] 2016-02-29 15:48
+1

**Comment by LK4D4** [comment] 2016-09-14 21:46
ping @mrjana @mavenugo @aboch @sanimej

**Comment by sanimej** [comment] 2016-09-15 23:45
@discordianfish I am running latest docker master (1.13 dev); I have a nginx running on default bridge network. With and without userland proxy (btw disabling userland proxy is not recommended) I see the right behavior. Accessing the published port from the localhost has the source IP is that of docker0 bridge (`172.17.0.1` in my case) and  from a remote host source IP is the remote IP.

Can you give it a try with 1.12.1 and confirm if it works ok ?

**Comment by discordianfish** [comment] 2016-09-16 08:09
@sanimej You're not using udp. See my initial description and try to reproduce with rsyslogd.
This issue is two years old, I stopped using Docker for anything udp long time ago.. So won't be able to test it.

**Comment by sanimej** [comment] 2016-09-16 16:24
@discordianfish Since the issue here is about the source IP the behavior should be the same for TCP and UDP. I verified for UDP as well. I will go ahead and close this issue.

Did you face any other UDP related issue with Docker ? If its something that is still seen in newer versions we can address it.

**Closed by sanimej** 2016-09-16 16:24 UTC
Labels: area/networking, exp/expert, kind/bug

**Comment by lliknart** [comment] 2016-09-29 08:48
Hi,

I have a rsyslogd container as well. All logs are sent in UDP. However, this issue appears for only one source.

```
# pid=`docker inspect -f '{{.State.Pid}}' rsyslog_container`
# nsenter -t $pid -n tcpdump -i eth0 -n

IP [remote1_ip].5815 > [rsyslog_container_ip].514: SYSLOG user.info, length: 110 # expected behavior
IP [remote2_ip].27403 > [rsyslog_container_ip].514: SYSLOG user.info, length: 110 # expected behavior
IP [docker_bridge_ip].44509 > [rsyslog_container_ip].1514: UDP, length 158 # issue
```

```
docker-compose ps
        Name                      Command               State                                             Ports                                            
----------------------------------------------------------------------------------------------------------------------------------------------------------
rsyslogd_container         rsyslogd -n                      Up      0.0.0.0:1514->1514/tcp, 0.0.0.0:1514->1514/udp, 0.0.0.0:514->514/tcp, 0.0.0.0:514->514/udp
```

Docker Version: 1.12.1

```
# docker-compose -v
docker-compose version 1.8.1
```

**Comment by Posnakidesd** [comment] 2021-07-02 10:37
This is old thread nonetheless still relevant.
`conntrack -D -p udp` after the container has started fixes the issue
moby/moby#16720
