### ISSUE TITLE
Error Getting a list of running containers

### ISSUE THREAD

**Issue by mindnuts** [docker/docker#26099] opened 2016-08-29 08:51 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   f1e1b83
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   f1e1b83
 Built:        
 OS/Arch:      linux/amd64
```
**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: selinux
Kernel Version: 4.7.1-coreos
Operating System: CoreOS 1151.0.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.801 GiB
Name: core-01
ID: 3D66:DYWJ:CZIL:ESFB:CW3S:UTSG:VFZY:YBLT:E234:H7L2:OIOT:Y7ZL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: easywebdeploy
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running CoreOS Alpha 1151.0.0 On Vagrant 1.8.5 Ubuntu 16.04

**Steps to reproduce the issue:**
1. Run a simple container and make sure its running
2. Run "curl -v --unix-socket /var/run/docker.sock http:/containers/json" to get a list of Containers

**Describe the results you received:**
```sh
*   Trying /var/run/docker.sock...
* Connected to containers (/var/run/docker.sock) port 80 (#0)
> GET /json HTTP/1.1
> Host: containers
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Date: Mon, 29 Aug 2016 08:48:02 GMT
< Content-Length: 29
< 
{"message":"page not found"}
* Connection #0 to host containers left intact
```

**Describe the results you expected:**
Expected is the JSON list of all running containers

**Additional information you deem important (e.g. issue happens only occasionally):**
Was working correctly on CoreOS with Docker version till 1.11.2

**Comment by vieux** [comment] 2016-08-29 18:16
@mindnuts hi, I get the exact same output

```
GET /json HTTP/1.1
Host: containers
```

when I use 2 `/` in  `http://`

It was to be only one, are you sure you didn't do a typo ? see:


```
$ curl -v --unix-socket /var/run/docker.sock http://containers/json
*   Trying /var/run/docker.sock...
* Connected to containers (/Users/victorvieux/Library/Containers/com.doc) port 80 (#0)
> GET /json HTTP/1.1
> Host: containers
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Length: 29
< Content-Type: application/json
< Date: Mon, 29 Aug 2016 18:14:56 GMT
<
{"message":"page not found"}
* Connection #0 to host containers left intact

$ curl -v --unix-socket /var/run/docker.sock http:/containers/json
*   Trying /var/run/docker.sock...
* Connected to http (/Users/victorvieux/Library/Containers/com.doc) port 80 (#0)
> GET /containers/json HTTP/1.1
> Host: http
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 3
< Content-Type: application/json
< Date: Mon, 29 Aug 2016 18:15:04 GMT
< Server: Docker/1.12.1 (linux)
<
[]
* Connection #0 to host http left intact
```

**Comment by mindnuts** [comment] 2016-08-30 06:56
@vieux No dice
```sh
core@core-01 ~ $ curl -v --unix-socket /var/run/docker.sock http://containers/json
*   Trying /var/run/docker.sock...
* Connected to containers (/var/run/docker.sock) port 80 (#0)
> GET /json HTTP/1.1
> Host: containers
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 30 Aug 2016 06:54:04 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host containers left intact

```

Did you use the same Docker version?:
```sh
core@core-01 ~ $ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4a6e2b1
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4a6e2b1
 Built:        
 OS/Arch:      linux/amd64
```

**Comment by vieux** [comment] 2016-08-30 16:57
@mindnuts no I didn't, I used 1.12

what's weird to me is that part: 

```
GET /json HTTP/1.1
Host: containers
```

**Comment by vieux** [comment] 2016-08-30 17:26
@mindnuts yeah I said you have to use one `/` only.

**Comment by dnephin** [comment] 2016-08-30 19:49
> GET /json HTTP/1.1

This url is wrong, the correct url is `/containers/json`. The issue is how curl is interpreting the url. 

I had to use: `curl -v --unix-socket /var/run/docker.sock http://localhost/containers/json` to get it to work (on alpine:3.4).  If this command is documented somewhere in the docker documentation, please link it here, and we will make sure to correct the documentation.

Closing this issue since there is nothing to be done in docker/docker.

**Comment by mindnuts** [comment] 2016-08-31 09:12
@dnephin Here you [go](https://docs.docker.com/engine/reference/api/docker_remote_api/#/docker-remote-api), link to Docker documentation

**Comment by earthquakesan** [comment] 2016-09-02 09:49
Still not fixed in the docs, why the issue is closed?

**Comment by dnephin** [comment] 2016-09-02 13:53
The url in the docs worked for @vieux above. I'm not sure which version of curl supports which form.

**Comment by earthquakesan** [comment] 2016-09-02 14:08
Mine works only with ```curl -v --unix-socket /var/run/docker.sock http://localhost/containers/json```. curl version is:
```
➜  ~ curl --version
curl 7.50.1 (x86_64-pc-linux-gnu) libcurl/7.50.1 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

**Comment by gerwim** [comment] 2016-09-06 16:27
This issue seems to have started since version 7.47.1 (so version higher than 7.47.1).

On 7.47.1:
```
 curl -v --unix-socket /var/run/docker.sock http:/containers/json
*   Trying /var/run/docker.sock...
* Connected to http (/var/run/docker.sock) port 80 (#0)
> GET /containers/json HTTP/1.1
> Host: http
> User-Agent: curl/7.47.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Server: Docker/1.12.1 (linux)
< Date: Tue, 06 Sep 2016 16:24:29 GMT
< Content-Length: 884
< 
[{"Id":"c6ccd147723dd414ca5fa582b8326752df8eb4ac9fe22e6ee8b743743366e669","Names":["/sleepy_franklin"],"Image":"alpine","ImageID":"sha256:4e38e38c8ce0b8d9041a9c4fefe786631d1416225e13b0bfe8cfa2321aec4bba","Command":"sh","Created":1473178577,"Ports":[],"Labels":{},"State":"running","Status":"Up 8 minutes","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"2cb5d0f6d1cf11f788919f66f5a30d55404897c88a0e4fb387c3acde4533ade4","EndpointID":"d6a2cba4167f43fa023cfbf97f59e9e26695658d5b3c93d26ffb2e1688194c64","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}},"Mounts":[{"Source":"/var/run/docker.sock","Destination":"/var/run/docker.sock","Mode":"","RW":true,"Propagation":"rprivate"}]}]
```
On 7.50.1:
```
curl -v --unix-socket /var/run/docker.sock http:/containers/json
* Unwillingly accepted illegal URL using 1 slash!
*   Trying /var/run/docker.sock...
* Connected to containers (/var/run/docker.sock) port 80 (#0)
> GET /json HTTP/1.1
> Host: containers
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Date: Tue, 06 Sep 2016 16:24:35 GMT
< Content-Length: 29
< 
{"message":"page not found"}
* Connection #0 to host containers left intact
```

The command which works on **both** versions is: `curl --unix-socket /var/run/docker.sock http://localhost/containers/json` so I suggest changing the documentation to this command.

**Comment by dnephin** [comment] 2016-09-06 18:19
@gerwim thanks for confirming and finding the version.  Would you be interested in creating a PR to fix this in the docs? I believe the file is `docs/reference/api/docker_remote_api.md`

**Comment by mstanleyjones** [comment] 2016-09-07 18:52
LGTM. @sfsmithcha PTAL

**Comment by cstpdk** [comment] 2016-10-28 09:46
I think this doc change is not enough to describe the issue for everybody. Double slash is not enough to fix this problem in all cases, as is pointed out earlier in this thread. Are we sure we are not breaking with the HTTP spec with this? Anyway, I think the doc should atleast reflect the possible issues that recent curl version can bring. Currently I see three working formats, only one of which works on version 7.50.3:

1) "Old way", 'http:/info' Gets accepted but corrected into 'http://info' by curl with warning `Unwillingly accepted illegal URL using 1 slash!`
2) The version we are now correcting the docs to `http://info`, gets accepted by curl, but it interprets it as a "proper" url, making "info" the host and "/" the path
3) My current hack, inserting anything in before the first slash, makes curl resolve with a hostname, but it gets ignored due to the unix socket, e.g. `curl --unix-socket /var/run/docker.sock http://john/info`

The way I read the HTTP [spec for urls](https://tools.ietf.org/html/rfc2616#section-3.2.2), I  think solution 3 is the only way to comply with it

**Comment by thaJeztah** [comment] 2016-10-29 01:27
docs were updated including both examples for 7.4x / 7.5x, see https://github.com/docker/docker/pull/27640

I'll go ahead and close this issue, but @cstpdk please check the linked PR if there's still something not right

**Closed by thaJeztah** 2016-10-29 01:27 UTC
Labels: area/docs, status/3-docs-review, status/claimed, version/1.12

**Comment by CarltonSemple** [comment] 2016-11-16 18:53
@thaJeztah 
Just so you know, on this page https://docs.docker.com/engine/reference/api/docker_remote_api/
It still says `curl --unix-socket /var/run/docker.sock http:/containers/json`. I had to come here to figure it out.

**Comment by thaJeztah** [comment] 2016-11-16 21:43
@CarltonSemple Thanks for reporting. I think these changes are not yet synced to the new docs repository, so not published yet. I'll see if we can get them published soon
