### ISSUE TITLE
Can't commit or export a container

### ISSUE THREAD

**Issue by djannot** [docker/docker#10488] opened 2015-01-31 20:55 UTC
When I try to commit or export a container of several GB, I have an EOF error:

docker commit hadoop1dn1.ad.forest djannot/hadoop1dn1.ad.forest:cloudera
FATA[0600] Post http:///var/run/docker.sock/v1.16/commit?author=&comment=&container=hadoop1dn1.ad.forest&repo=djannot%2Fhadoop1dn1.ad.forest&tag=cloudera: EOF. Are you trying to connect to a TLS-enabled daemon without TLS? 

docker export hadoop1dn1.ad.forest > hadoop1dn1.ad.forest.tar   
time="2015-01-31T21:49:33+01:00" level="fatal" msg="http: unexpected EOF reading trailer" 

ls -l
-rw-r--r-- 1 core core 4139384832 Jan 31 21:49 hadoop1dn1.ad.forest.tar

docker --version
Docker version 1.4.1, build 5bc2ff8-dirty

Running on CoreOS

It works with another (smaller) container.

**Comment by unclejack** [comment] 2015-02-05 14:22
@djannot Are you sure you've got enough free space to commit that container? If you've got a container which is 20 GB, you'll probably need around 20 GB + 2-5 GB of free space to make that an image. The extra space is needed for extra breathing room so the file system doesn't run into other problems (not being able to allocate space it needs for other operations, bugs, etc).

**Comment by jfrazelle** [comment] 2015-02-28 04:16
@djannot any update?

**Comment by djannot** [comment] 2015-02-28 21:37
Hi Jessie,

In fact, I have several issues with BTRFS on my CoreOS cluster and the new
CoreOS release is now using EXT4 + OverlayFS, so I've planned to reinstall
it and see if it solve this issue as well.
But the issue was definitively not due to the space available.

Thanks
Denis

**Comment by jfrazelle** [comment] 2015-02-28 21:54
@djannot do you think this is a duplicate of https://github.com/docker/docker/issues/8354

**Comment by djannot** [comment] 2015-02-28 22:09
@jfrazelle No, in my case I didn't have any space issue, but I wasn't able to commit large containers (few GB).

**Comment by jfrazelle** [comment] 2015-03-02 16:47
ok we need the output of docker version, docker info, daemon logs and how to reproduce

**Comment by djannot** [comment] 2015-03-15 21:05
@jfrazelle I've tried with the current version and CoreOS running on ext4 + OverlayFS. Everything is now working fine. So, I think the issue was due to BTRFS

**Comment by unclejack** [comment] 2015-03-18 16:17
@djannot This is indeed a duplicate of #8354. BTRFS can run into all sorts of problems when the file system is heavily fragmented, even though you have more than enough free space. The problem manifests itself just like when you don't have enough space left on disk.

I'm going to close this since it's been tracked down to BTRFS and it really looks like what I've also seen before on various systems.

**Closed by unclejack** 2015-03-18 16:17 UTC
Labels: need-more-info
