### ISSUE TITLE
Please support specifying minimum version in Dockerfile

### ISSUE THREAD

**Issue by edwintorok** [docker/docker#10854] opened 2015-02-17 14:52 UTC
Description of problem:

Docker 1.0.1 succeeds in building a Dockerfile that was developed/tested with Docker 1.3.{2,3}, but the image won't run correctly.
There seem to be major differences on how the image is run, for example
when you run docker 1.3.x with `-u` it sets `$HOME`, whereas 1.0.1 doesn't.

Environment details: Linux Mint 17.1 x64

Suggestion:

Please add a way to specify minimum docker version required to build/run a Dockerfile.
One may not be aware that the docker running on their host is considered too old for the image to work correctly.

**Comment by thaJeztah** [comment] 2015-02-17 18:35
I think this is a duplicate of https://github.com/docker/docker/issues/4907 if you agree, please close this issue. Thanks!

**Comment by jfrazelle** [comment] 2015-02-17 18:38
yep totally thanks so much @thaJeztah closing as a duplicate, please continue the conversation on that issue @edwintorok

**Closed by jfrazelle** 2015-02-17 18:38 UTC
