### ISSUE TITLE
docker pull reports "not found" when not authenticated to private registry

### ISSUE THREAD

**Issue by bmerry** [docker/docker#27281] opened 2016-10-11 09:24 UTC
When using a private registry (I haven't tested it on Docker Hub) and there are no credentials cached, running `docker pull` gives the error `not found`. Looking at the logs for the registry, it appears that the registry is returning HTTP status 401 (authorization required) for /v2, but Docker is then trying to fall back to the /v1 and is getting a 404 from there since the registry does not support the v1 API.

**Steps to reproduce the issue:**
1. Install a registry (I use the image registry:2.5) with htpasswd auth.
2. Log in to the registry and push an image
3. On another machine (or after logging out of the registry), run `docker pull <registry>:<port>/<image>`.

**Describe the results you received:**

Docker output:
```
Using default tag: latest
Pulling repository registry:5000/bmerry/abacuscm
Error: image bmerry/abacuscm:latest not found
```
Registry log file:
```
time="2016-10-11T09:14:34Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"Registry Realm\": invalid authorization credential" go.version=go1.6.3 http.request.host="registry:5000" http.request.id=2ec10df4-0f18-4d69-b69b-e017b720b5ea http.request.method=GET http.request.remoteaddr="172.17.0.1:32768" http.request.uri="/v2/" http.request.useragent="docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/4.4.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))" instance.id=be638723-6e27-43a5-a2d6-1fc5254d7b71 version=v2.5.0 
172.17.0.1 - - [11/Oct/2016:09:14:34 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/4.4.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))"
2016/10/11 09:14:34 http: TLS handshake error from 172.17.0.1:32772: tls: first record does not look like a TLS handshake
172.17.0.1 - - [11/Oct/2016:09:14:34 +0000] "GET /v1/_ping HTTP/1.1" 404 19 "" "docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/4.4.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))"
172.17.0.1 - - [11/Oct/2016:09:14:34 +0000] "GET /v1/repositories/bmerry/abacuscm/images HTTP/1.1" 404 19 "" "docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/4.4.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))"
```

**Describe the results you expected:**
Docker should report that authorization is required, and possibly the CLI should prompt for credentials when run interactively.

**Additional information you deem important (e.g. issue happens only occasionally):**
The symptoms are the same as described in #17721, but I was asked to open a separate issue.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 385
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 634
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.36 GiB
Name: kryton
ID: MFLN:XRFL:372N:VPKR:3AWK:USXB:3Q3E:EAH2:66ZK:T5U2:NEOP:TSCH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical box running Ubuntu 14.04.

**Comment by thaJeztah** [comment] 2016-10-11 18:02
ping @aaronlehmann @runcom @dmcgowan ptal

**Comment by runcom** [comment] 2016-10-12 10:32
This is expected behavior afaict and works like this for Docker Hub as well

**Comment by bmerry** [comment] 2016-10-12 10:43
Huh? The error message is incorrect and unhelpful. How is that expected behaviour?

**Comment by thaJeztah** [comment] 2016-10-14 00:36
> The error message is incorrect and unhelpful. How is that expected behaviour?

@bmerry the registry returns the same error for repositories that don't exist, or exist, but you don't have access to; this is done to not expose the _existence_ of a repository, as the name of a repository in itself may reveal confidential information. GitHub does the same for private repositories; if you don't have access, you get a 404. I wasn't sure if a 403 or a 404 was returned in those cases (therefore I pinged @runcom); either one is correct, as long as it's done consistently.

I'll close this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2016-10-14 00:36 UTC
Labels: area/distribution, kind/enhancement, version/1.12

**Comment by bmerry** [comment] 2016-10-14 06:05
@thaJeztah The registry doesn't return a 403 *or* a 404. It is returning a 401, as you can see from the server log in my original bug report. The relevant line again:
```
172.17.0.1 - - [11/Oct/2016:09:14:34 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/4.4.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))"
```
Why can't Docker Engine pass on this 401 error to the client? It doesn't make sense for Engine to keep this feedback secret, since the user can discover it by his/her own HTTP connection to the registry.

**Comment by runcom** [comment] 2016-10-24 12:18
> Why can't Docker Engine pass on this 401 error to the client? It doesn't make sense for Engine to keep this feedback secret, since the user can discover it by his/her own HTTP connection to the registry.

Because Docker is designed to fallback to v1, thus getting 404 from /v1, and your client just get the last error in the chain

**Comment by bmerry** [comment] 2016-10-24 12:34
Well, there are probably several ways this could be made more user-friendly. Let me know if it's worth filing a new bug for any of them:
1. Don't fall back to v1 on a 401 error. Are there any situations where this will actually succeed?
2. When falling back, print the error that happened on v2 and a warning that fallback is being attempted. That way, the user will get to see the real error.
3. If querying /v1 returns a 404 during fallback, print the original v2 error instead of the 404, since the 404 most likely indicates only that the registry doesn't support v1.

**Comment by runcom** [comment] 2016-10-24 13:02
> 3. If querying /v1 returns a 404 during fallback, print the original v2 error instead of the 404, since the 404 most likely indicates only that the registry doesn't support v1.

I'm not sure this is always the case and we can't act based on how likely this will be

**Comment by bmerry** [comment] 2016-10-25 09:07
> I'm not sure this is always the case and we can't act based on how likely this will be

What about if /v1/_ping returns 404 (as happens here)? Isn't that solid evidence that the v1 API isn't implemented?

**Comment by bmerry** [comment] 2016-10-25 18:15
On 24 October 2016 at 15:03, Antonio Murdaca <notifications@github.com>
wrote:

>
>    1. If querying /v1 returns a 404 during fallback, print the original
>    v2 error instead of the 404, since the 404 most likely indicates only that
>    the registry doesn't support v1.
>
> I'm not sure this is always the case and we can't act based on how likely
> this will be
>
​What about if /v1/_ping returns 404 (as indeed happens)?​ Surely that
indicates that the v1 API isn't implemented?
