### ISSUE TITLE
1.9: Possible CPU issue from libnetwork

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#16748] opened 2015-10-04 01:24 UTC
@mavenugo This may be the most useless bug report, but I have reason to believe the following gorouting is chewing up 100% CPU:

```
goroutine 182 [select]:
net/http.(*Transport).getConn(0xc20829d4d0, 0xc208974410, 0x0, 0xc20865bc20, 0x4, 0xc20865bc27, 0xe, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:525 +0x608
net/http.(*Transport).RoundTrip(0xc20829d4d0, 0xc208974410, 0xc20865bd10, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:228 +0x4d4
net/http.send(0xc208974410, 0x7f2acd81c5f0, 0xc20829d4d0, 0xe4, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc2082cb6b0, 0xc208974410, 0xe4, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc2082cb6b0, 0xc208974410, 0x1434ed0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0xc2082cb6b0, 0xc208974410, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:174 +0xa4
github.com/coreos/go-etcd/etcd.(*Client).SendRequest(0xc20829d440, 0xc20a44fd40, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-etcd/etcd/requests.go:238 +0x121f
github.com/coreos/go-etcd/etcd.(*Client).getCancelable(0xc20829d440, 0xc20a453860, 0x9e, 0xc20a44fc50, 0x0, 0x1a02fc0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-etcd/etcd/requests.go:51 +0x41a
github.com/coreos/go-etcd/etcd.(*Client).get(0xc20829d440, 0xc20a453860, 0x9e, 0xc20a44fc50, 0x4b1561, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-etcd/etcd/requests.go:62 +0x61
github.com/coreos/go-etcd/etcd.(*Client).RawGet(0xc20829d440, 0xc20a453860, 0x9e, 0x0, 0xc20a4537c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-etcd/etcd/get.go:31 +0x26c
github.com/coreos/go-etcd/etcd.(*Client).Get(0xc20829d440, 0xc20a453860, 0x9e, 0x0, 0x9d, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-etcd/etcd/get.go:11 +0x63
github.com/docker/libkv/store/etcd.(*Etcd).Get(0xc208038788, 0xc20a453680, 0x9d, 0xc20a4535e0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libkv/store/etcd/etcd.go:126 +0x86
github.com/docker/libnetwork/datastore.(*datastore).GetObject(0xc2082ea410, 0xc20a453680, 0x9d, 0x7f2acd831c38, 0xc2089f8480, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/datastore/datastore.go:188 +0x70
github.com/docker/libnetwork.func·042()
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/store.go:244 +0x58b
created by github.com/docker/libnetwork.(*network).watchEndpoints
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/store.go:253 +0x576
```

The situation is such that I started with an etcd backend, but then killed the server.  So Docker should be getting a connection refused right now.

To help troubleshoot, I pushed a tag to by github account because this is docker master + your two UX PR's. https://github.com/ibuildthecloud/docker/blob/cpu-issue/vendor/src/github.com/docker/libnetwork/store.go#L244

Right now Docker is using 100% CPU.  This is the full goroutine dump
```
INFO[84249] === BEGIN goroutine stack dump ===
goroutine 10 [running]:
github.com/docker/docker/pkg/signal.DumpStacks()
	/go/src/github.com/docker/docker/pkg/signal/trap.go:67 +0xa5
github.com/docker/docker/daemon.func·030()
	/go/src/github.com/docker/docker/daemon/debugtrap_unix.go:18 +0x6d
created by github.com/docker/docker/daemon.setupDumpStackTrap
	/go/src/github.com/docker/docker/daemon/debugtrap_unix.go:20 +0x18e

goroutine 1 [chan receive, 386 minutes]:
main.(*DaemonCli).CmdDaemon(0xc2080f9ed0, 0xc20800a020, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/docker/daemon.go:286 +0x1867
reflect.callMethod(0xc208068ae0, 0xc2082bfce8)
	/usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0x1, 0x1, 0x1, 0xc208068ae0, 0x0, 0x0, 0xc208068ae0, 0x0, 0x4dbc0f, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc208099170, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:89 +0x38e
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:65 +0x418

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 386 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 12 [IO wait, 386 minutes]:
net.(*pollDesc).Wait(0xc2080da7d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080da7d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readMsg(0xc2080da770, 0xc2082c8ef0, 0x10, 0x10, 0xc2082d6020, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:296 +0x54e
net.(*UnixConn).ReadMsgUnix(0xc208038478, 0xc2082c8ef0, 0x10, 0x10, 0xc2082d6020, 0x1000, 0x1000, 0x51, 0xc2082c8cb4, 0x4, ...)
	/usr/local/go/src/net/unixsock_posix.go:147 +0x167
github.com/godbus/dbus.(*oobReader).Read(0xc2082d6000, 0xc2082c8ef0, 0x10, 0x10, 0xc2082d6000, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:21 +0xc5
io.ReadAtLeast(0x7f2acd826e58, 0xc2082d6000, 0xc2082c8ef0, 0x10, 0x10, 0x10, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f2acd826e58, 0xc2082d6000, 0xc2082c8ef0, 0x10, 0x10, 0x51, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc2082a9210, 0xc2080f15c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/transport_unix.go:85 +0x1bf
github.com/godbus/dbus.(*Conn).inWorker(0xc2082a0c60)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:248 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:118 +0xe84

goroutine 13 [chan receive, 386 minutes]:
github.com/godbus/dbus.(*Conn).outWorker(0xc2082a0c60)
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/conn.go:370 +0x58
created by github.com/godbus/dbus.(*Conn).Auth
	/go/src/github.com/docker/docker/vendor/src/github.com/godbus/dbus/auth.go:119 +0xea1

goroutine 14 [chan receive, 386 minutes]:
github.com/docker/libnetwork/iptables.signalHandler()
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/iptables/firewalld.go:92 +0x57
created by github.com/docker/libnetwork/iptables.FirewalldInit
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/iptables/firewalld.go:48 +0x185

goroutine 26 [sleep, 6 minutes]:
github.com/docker/libkv/store/etcd.func·001()
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libkv/store/etcd/etcd.go:78 +0x4a
created by github.com/docker/libkv/store/etcd.New
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libkv/store/etcd/etcd.go:80 +0x329

goroutine 44 [IO wait, 386 minutes]:
net.(*pollDesc).Wait(0xc20800e3e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20800e3e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20800e380, 0xc208330000, 0x1000, 0x1000, 0x0, 0x7f2acd81c380, 0xc20838a6d8)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208038c18, 0xc208330000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f2acd82b7c8, 0xc208038c18, 0xc2080c5bd8, 0xc208330000, 0x1000, 0x1000, 0xf69f40, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20832c360, 0xc208330000, 0x1000, 0x1000, 0xc208010000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2081b9860)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2081b9860, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080c5b80)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 82 [IO wait, 386 minutes]:
net.(*pollDesc).Wait(0xc2083be530, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2083be530, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2083be4d0, 0x0, 0x7f2acd81c380, 0xc2083c84b8)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*UnixListener).AcceptUnix(0xc2083c25a0, 0x10, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:282 +0x56
net.(*UnixListener).Accept(0xc2083c25a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:293 +0x4c
github.com/docker/libnetwork.(*controller).acceptClientConnections(0xc20808e900, 0xc2083be460, 0x63, 0x7f2acd82bdc8, 0xc2083c25a0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox_externalkey.go:138 +0x87
created by github.com/docker/libnetwork.(*controller).startExternalKeyListener
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox_externalkey.go:132 +0x28f

goroutine 45 [select, 386 minutes]:
net/http.(*persistConn).writeLoop(0xc2080c5b80)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 99 [chan receive, 386 minutes]:
database/sql.(*DB).connectionOpener(0xc2083e1360)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 103 [chan receive, 1 minutes]:
github.com/docker/docker/daemon.(*Daemon).execCommandGC(0xc208065100)
	/go/src/github.com/docker/docker/daemon/exec.go:298 +0x8c
created by github.com/docker/docker/daemon.NewDaemon
	/go/src/github.com/docker/docker/daemon/daemon.go:794 +0x2a27

goroutine 102 [chan receive]:
github.com/docker/docker/daemon.(*statsCollector).run(0xc2083f9fb0)
	/go/src/github.com/docker/docker/daemon/stats_collector_unix.go:91 +0xb2
created by github.com/docker/docker/daemon.newStatsCollector
	/go/src/github.com/docker/docker/daemon/stats_collector_unix.go:31 +0x116

goroutine 129 [select]:
github.com/docker/libnetwork/osl.removeUnusedPaths()
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/osl/namespace_linux.go:73 +0x48b
created by github.com/docker/libnetwork/osl.createBasePath
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/osl/namespace_linux.go:58 +0xb1

goroutine 120 [IO wait, 72 minutes]:
net.(*pollDesc).Wait(0xc20847dfe0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20847dfe0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20847df80, 0x0, 0x7f2acd81c380, 0xc208ce5638)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*UnixListener).AcceptUnix(0xc20847fa60, 0xc20889fb00, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:282 +0x56
net.(*UnixListener).Accept(0xc20847fa60, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/unixsock_posix.go:293 +0x4c
github.com/docker/docker/pkg/listenbuffer.(*defaultListener).Accept(0xc20847fa80, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:71 +0x67
net/http.(*Server).Serve(0xc2084c8000, 0x7f2acd830898, 0xc20847fa80, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
github.com/docker/docker/api/server.(*HTTPServer).Serve(0xc20843ca20, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:114 +0x4d
github.com/docker/docker/api/server.func·006(0x7f2acd830b80, 0xc20843ca20)
	/go/src/github.com/docker/docker/api/server/server.go:86 +0x40
created by github.com/docker/docker/api/server.(*Server).ServeAPI
	/go/src/github.com/docker/docker/api/server/server.go:90 +0x6ac

goroutine 118 [chan receive, 386 minutes]:
github.com/docker/docker/pkg/signal.func·002()
	/go/src/github.com/docker/docker/pkg/signal/trap.go:29 +0x8f
created by github.com/docker/docker/pkg/signal.Trap
	/go/src/github.com/docker/docker/pkg/signal/trap.go:55 +0x250

goroutine 117 [chan receive, 386 minutes]:
github.com/docker/docker/api/server.(*Server).ServeAPI(0xc208467e00, 0xc20809a530, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:95 +0x74f
main.func·007()
	/go/src/github.com/docker/docker/docker/daemon.go:260 +0x5b
created by main.(*DaemonCli).CmdDaemon
	/go/src/github.com/docker/docker/docker/daemon.go:266 +0x170f

goroutine 140 [sleep, 6 minutes]:
github.com/docker/libkv/store/etcd.func·001()
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libkv/store/etcd/etcd.go:78 +0x4a
created by github.com/docker/libkv/store/etcd.New
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libkv/store/etcd/etcd.go:80 +0x329

goroutine 143 [runnable]:
github.com/docker/libnetwork/bitseq.func·001()
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/bitseq/store.go:99 +0x7a
created by github.com/docker/libnetwork/bitseq.(*Handle).watchForChanges
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/bitseq/store.go:111 +0x281

goroutine 159 [runnable]:
github.com/docker/libnetwork/bitseq.func·001()
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/bitseq/store.go:99 +0x7a
created by github.com/docker/libnetwork/bitseq.(*Handle).watchForChanges
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/bitseq/store.go:111 +0x281

goroutine 182 [select]:
net/http.(*Transport).getConn(0xc20829d4d0, 0xc208974410, 0x0, 0xc20865bc20, 0x4, 0xc20865bc27, 0xe, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:525 +0x608
net/http.(*Transport).RoundTrip(0xc20829d4d0, 0xc208974410, 0xc20865bd10, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:228 +0x4d4
net/http.send(0xc208974410, 0x7f2acd81c5f0, 0xc20829d4d0, 0xe4, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc2082cb6b0, 0xc208974410, 0xe4, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc2082cb6b0, 0xc208974410, 0x1434ed0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0xc2082cb6b0, 0xc208974410, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:174 +0xa4
github.com/coreos/go-etcd/etcd.(*Client).SendRequest(0xc20829d440, 0xc20a44fd40, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-etcd/etcd/requests.go:238 +0x121f
github.com/coreos/go-etcd/etcd.(*Client).getCancelable(0xc20829d440, 0xc20a453860, 0x9e, 0xc20a44fc50, 0x0, 0x1a02fc0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-etcd/etcd/requests.go:51 +0x41a
github.com/coreos/go-etcd/etcd.(*Client).get(0xc20829d440, 0xc20a453860, 0x9e, 0xc20a44fc50, 0x4b1561, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-etcd/etcd/requests.go:62 +0x61
github.com/coreos/go-etcd/etcd.(*Client).RawGet(0xc20829d440, 0xc20a453860, 0x9e, 0x0, 0xc20a4537c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-etcd/etcd/get.go:31 +0x26c
github.com/coreos/go-etcd/etcd.(*Client).Get(0xc20829d440, 0xc20a453860, 0x9e, 0x0, 0x9d, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/coreos/go-etcd/etcd/get.go:11 +0x63
github.com/docker/libkv/store/etcd.(*Etcd).Get(0xc208038788, 0xc20a453680, 0x9d, 0xc20a4535e0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libkv/store/etcd/etcd.go:126 +0x86
github.com/docker/libnetwork/datastore.(*datastore).GetObject(0xc2082ea410, 0xc20a453680, 0x9d, 0x7f2acd831c38, 0xc2089f8480, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/datastore/datastore.go:188 +0x70
github.com/docker/libnetwork.func·042()
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/store.go:244 +0x58b
created by github.com/docker/libnetwork.(*network).watchEndpoints
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/store.go:253 +0x576

goroutine 240 [select, 189 minutes]:
net.func·019()
	/usr/local/go/src/net/dnsclient_unix.go:241 +0x2f4
created by net.loadConfig
	/usr/local/go/src/net/dnsclient_unix.go:269 +0x20c

goroutine 284727 [runnable]:
net/http.func·019()
	/usr/local/go/src/net/http/transport.go:519
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:522 +0x335

=== END goroutine stack dump === 

```

**Comment by mavenugo** [comment] 2015-10-04 01:29
This is a dupe of https://github.com/docker/libnetwork/issues/408. closing it.

**Closed by mavenugo** 2015-10-04 01:29 UTC

**Comment by abronan** [comment] 2015-10-04 02:32
@mavenugo I suspect that this is not a duplicate as I'm seeing the same issue with a fresh new daemon running `libnetwork` (ie. without restarting the store). The daemon takes up 100% CPU no matter what :confused:

**Comment by abronan** [comment] 2015-10-04 02:42
This sounds like it's only an issue with `etcd`, just tested with Consul and it works fine. Will keep investigating (tested quickly with swarm and etcd and it doesn't take up the cpu so not sure if related to `libkv` or something here in `libnetwork`, I will dig into this).

**Comment by abronan** [comment] 2015-10-04 02:46
Comfirmed it's a duplicate after stopping and restarting the store for Consul too. I guess I restarted etcd without noticing and encountered that same issue :confused:
