### ISSUE TITLE
Get Docker script doesn't work on Amazon Linux

### ISSUE THREAD

**Issue by jacobtomlinson** [docker/docker#30707] opened 2017-02-03 11:33 UTC
**Description**
Running the get docker script from https://get.docker.com/ no longer works on amazon linux. 

**Steps to reproduce the issue:**
1. Launch new ec2 instance using a new amazon linux AMI (`amzn-ami-hvm-2016.09.1.20170119-x86_64-gp2 (ami-70edb016)` in `eu-west-1` for example)
2. Login to the server
3. run `curl -sSL https://get.docker.com/ | sh`

**Describe the results you received:**
Shows the error

```

	  Either your platform is not easily detectable, is not supported by this
	  installer script (yet - PRs welcome! [hack/install.sh]), or does not yet have
	  a package for Docker.  Please visit the following URL for more detailed
	  installation instructions:

	    https://docs.docker.com/engine/installation/
```

**Describe the results you expected:**
Installs docker as it did previously

**Additional information you deem important (e.g. issue happens only occasionally):**
Looks like amazon linux may have dropped `/etc/redhat-release` in favour of `/etc/os-release`.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Comment by yongtang** [comment] 2017-02-03 17:43
@jacobtomlinson I am not sure if Amazon Linux is officially supported by Docker's installation script or not.

Though Amazon Linux comes with docker (it is `1.12.6`) in the repo. You could install it with:
```
$ sudo yum install -y docker
$ sudo service docker start
$ sudo docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64
```

**Comment by tophj-ibm** [comment] 2017-02-03 18:14
Amazon Linux isn't supported by the install script as docker doesn't have any packages available for it, and was removed in #23480. 

The old script just installed docker from Amazon's repo anyway, so you should be able to do what @yongtang suggested.

**Comment by jacobtomlinson** [comment] 2017-02-03 19:11
Thanks for the update. It's a shame really as it was nice to have a consistent way to install docker across different distros. 

On Fri, 03 Feb 2017 at 18:15 Christopher Jones

<
mailto:Christopher Jones <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Amazon Linux isn't supported by the install script as docker doesn't have any packages available for it, and was removed in
https://github.com/docker/docker/pull/23480
.

The old script just installed docker from Amazon's repo anyway, so you should be able to do what
https://github.com/yongtang
suggested.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/docker/docker/issues/30707#issuecomment-277320661
, or

**Comment by thaJeztah** [comment] 2017-02-05 02:07
Correct, there's currently no official package for Amazon Linux. We decided to remove it from the install script, because installing third party packages may lead to the conclusion we _do_ support that distro, but we can't provide support for it, and support currently has to be handled by Amazon.

There's an open PR for adding support for Amazon Linux, but it's currently being held up, pending support for seccomp filtering. Seccomp filtering is an important security feature of docker, and we don't want to add support for new platforms that don't support this.

It's being worked on though, and you can follow progress on the PR https://github.com/docker/docker/pull/29957

I'll close this issue because it's not a bug, and being worked on, but feel free to continue the conversation

**Closed by thaJeztah** 2017-02-05 02:07 UTC
