### ISSUE TITLE
docker build fails with "readdirent: no such file or directory"

### ISSUE THREAD

**Issue by saintdev** [docker/docker#22592] opened 2016-05-09 07:00 UTC
When I attempt to build an image from the following simple Dockerfile, the build fails at the second step with "readdirent: no such file or directory".

**Dockerfile**

```
FROM alpine:latest
RUN apk add --update ncurses-terminfo
CMD ["/bin/sh"]
```

**Output of `docker build .`**

```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine:latest
 ---> 13e1761bf172
Step 2 : RUN apk add --update ncurses-terminfo
 ---> Running in 2e17dfff2fbc
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/2) Installing ncurses-terminfo-base (6.0-r6)
(2/2) Installing ncurses-terminfo (6.0-r6)
OK: 11 MiB in 13 packages
readdirent: no such file or directory
```

**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: f2fs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.2-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.751 GiB
Name: khopesh
ID: 2SFT:XOZX:27LT:HXTO:EIEK:XRIE:T2I7:6ILK:FOEG:J2QD:M5YB:OCCS
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. cd test/
2. docker build .
3.

**Describe the results you received:**
Fails to build image

**Describe the results you expected:**
Successfully built image

**Comment by thaJeztah** [comment] 2016-05-09 11:58
I'm not able to reproduce this on Docker for Mac (running kernel 4.4.6) or Ubuntu Xenial (kernel 4.4.0-22).

I do see you're running a version of Docker that's built and packaged by Arch, can you report this issue in the Arch Linux issue tracker?

**Comment by saintdev** [comment] 2016-05-10 06:32
Hi,

I looked into this further and created two identical virtual machines, with the only difference being the rootfs ext4 and f2fs. The ext4 rootfs works while the f2fs rootfs does not.

**`docker info` for ext4 rootfs virtual machine**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.5.2-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 997.2 MiB
Name: localhost
ID: O7NF:KAKS:XLXX:V2SQ:Z476:VZXM:UEDY:IBDC:UBNZ:CGKO:5OUQ:HGKE
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Output of `docker build` with ext4 rootfs**

```
Sending build context to Docker daemon 2.048 kB

Step 1 : FROM alpine:latest
 ---> 13e1761bf172
Step 2 : RUN apk add --update ncurses-terminfo
 ---> Using cache
 ---> 5b5c1cb5a0fd
Step 3 : CMD /bin/sh
 ---> Using cache
 ---> 10c106e6e6c9
Successfully built 10c106e6e6c9
```

**`docker info` for the f2fs rootfs virtual machine**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: f2fs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.5.2-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 997.2 MiB
Name: arch-vm-f2fs
ID: ENI2:56NV:A4K5:QGCA:PYZP:N4QS:E22C:S6OO:66BD:CNZK:FY2W:IMJU
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Output of `docker build` with f2fs rootfs**

```
Sending build context to Docker daemon 2.048 kB

Step 1 : FROM alpine:latest
 ---> 13e1761bf172
Step 2 : RUN apk add --update ncurses-terminfo
 ---> Running in 99e61df0937c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/2) Installing ncurses-terminfo-base (6.0-r6)
(2/2) Installing ncurses-terminfo (6.0-r6)
OK: 11 MiB in 13 packages
readdirent: no such file or directory
```

`docker version` is the same as the original comment above for both virtual machines. Would you like me to attempt to reproduce this with an Ubuntu virtual machine?

**Comment by thaJeztah** [comment] 2016-05-10 07:51
> Edit: accidentally used cached build for ext4

So is it failing on ext4 as well, or still only on f2fs? It's possible that overlay on f2fs doesn't work, I don't know if it's been tested; if there turns out to be an incompatibility we should probably look into that, and mark it as an "incompatible" combination while that's looked into

**Comment by saintdev** [comment] 2016-05-10 19:08
> So is it failing on ext4 as well, or still only on f2fs? It's possible that overlay on f2fs doesn't work, I don't know if it's been tested; if there turns out to be an incompatibility we should probably look into that, and mark it as an "incompatible" combination while that's looked into

ext4 does not fail only f2fs. Sorry for the confusion I just forgot to use --no-cache when I rebuilt the image on ext4 to capture the output to paste here.

**Comment by thaJeztah** [comment] 2016-05-10 19:17
Let me reopen this issue

**Comment by dmcgowan** [comment] 2016-05-10 19:44
Tested on Fedora and was not able to reproduce. Does this error happen every time?

`docker info`
```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: f2fs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.8-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.58 GiB
Name: m3800.drizz.net
ID: 2NMV:4JTA:DSQW:X6EP:WPET:BFM7:QJXI:B6J5:YBS7:COCT:4K2D:OCT6
Docker Root Dir: /home/docker/testmount
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 39
 System Time: 2016-05-10T12:38:17.207114123-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
```

`docker build .` output
```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine:latest
latest: Pulling from library/alpine
d0ca440e8637: Pull complete 
Digest: sha256:f655166f57d91bdfc8b3bc75a20391b7516de9f48ca761249c185fcb022124d2
Status: Downloaded newer image for alpine:latest
 ---> 13e1761bf172
Step 2 : RUN apk add --update ncurses-terminfo
 ---> Running in d66418080645
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/2) Installing ncurses-terminfo-base (6.0-r6)
(2/2) Installing ncurses-terminfo (6.0-r6)
OK: 11 MiB in 13 packages
 ---> 4eb6982156e2
Removing intermediate container d66418080645
Step 3 : CMD /bin/sh
 ---> Running in 1ae7238eb9d3
 ---> 5bbfe09d2d3a
Removing intermediate container 1ae7238eb9d3
Successfully built 5bbfe09d2d3a
```

`mount -l` information
```
/dev/loop0 on /home/docker/testmount type f2fs (rw,relatime,seclabel,background_gc=on,user_xattr,acl,inline_data,extent_cache,active_logs=6)
```

**Comment by saintdev** [comment] 2016-05-10 20:10
> Tested on Fedora and was not able to reproduce. Does this error happen every time?

Yes, every time. That's interesting...

Maybe this is a regression in f2fs? I just tried downgrading to a 4.4 kernel (4.4.5-1-ARCH) like the fedora kernel and the container builds just fine.

`docker info` output now

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: f2fs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 997.4 MiB
Name: arch-vm-f2fs
ID: ENI2:56NV:A4K5:QGCA:PYZP:N4QS:E22C:S6OO:66BD:CNZK:FY2W:IMJU
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

`docker build .` results

```
Sending build context to Docker daemon 2.048 kB

Step 1 : FROM alpine:latest
 ---> 13e1761bf172
Step 2 : RUN apk add --update ncurses-terminfo
 ---> Running in 1e3017da3c18
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/2) Installing ncurses-terminfo-base (6.0-r6)
(2/2) Installing ncurses-terminfo (6.0-r6)
OK: 11 MiB in 13 packages
 ---> 8e95564ecc58
Removing intermediate container 1e3017da3c18
Step 3 : CMD /bin/sh
 ---> Running in f355c8e95dd1
 ---> 00aeadf57390
Removing intermediate container f355c8e95dd1
Successfully built 00aeadf57390
```

**Comment by saintdev** [comment] 2016-05-14 00:43
I filed [Bug 117981](https://bugzilla.kernel.org/show_bug.cgi?id=117981) on the kernel bug tracker.

**Comment by runcom** [comment] 2016-05-16 09:25
Fixed upstream in kernel https://bugzilla.kernel.org/show_bug.cgi?id=117981#c1

**Comment by runcom** [comment] 2016-06-10 10:17
Fixed in kernel 4.5+

**Closed by runcom** 2016-06-10 10:17 UTC
Labels: area/kernel, area/storage/overlay, kind/bug, version/1.11

**Comment by saintdev** [comment] 2016-06-10 18:34
I think you mean 4.7+ (as soon as it is released, that is).

**Comment by jeremywu0127** [comment] 2017-04-17 05:44
I upgrade the kernel to `4.9.17`, and it works fine
