### ISSUE TITLE
Can not delete namespace after container is restarted

### ISSUE THREAD

**Issue by jeffrey4l** [docker/docker#27277] opened 2016-10-11 08:18 UTC
**Description**

when mounting the /var/run in one container, then create a new namespace and restart the container, the namespace can not be removed.

**Steps to reproduce the issue:**
1. `docker run -t -d --name test_netns --restart always -v /var/run:/var/run centos:7 bash`
2. `ip netns add a`
3. `docker restart test_netns`
4. `ip netns delete a`

**Describe the results you received:**

You will get following error in step 4

```
Cannot remove namespace file "/var/run/netns/a": Device or resource busy
```

And the namespace file become a normal file

```
# ls -alh /var/run/netns/a 
----------. 1 root root 0 Oct 11 04:11 /var/run/netns/a
```

After stop the container, this file can be removed by `rm`

```
docker stop test_netns
rm /var/run/netns/a
```

**Describe the results you expected:**

The namespace should be removed successfully

**Output of `docker version`:**

```
# docker --version
Docker version 1.12.1, build 23cf638
```

**Output of `docker info`:**

```
# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-67935215-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 244.1 MB
 Data Space Total: 107.4 GB
 Data Space Available: 17.37 GB
 Metadata Space Used: 753.7 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.2 MiB
Name: localhost.localdomain
ID: SWU5:TN6S:5X2Q:YEXC:IJTH:IOUI:SIBA:CQZ5:ELVU:C6XX:2AX2:6JDB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Comment by justincormack** [comment] 2016-10-11 18:21
Welcome to the complexities of shared mounts. You probably don't want to do that and if you do you want to investigate and or change the mount type, perhaps you might want to read https://lwn.net/Articles/689856/ it is a good introduction. 

I am going to close this as it is not a bug in Docker, if you share system mounts into containers you will break things, it is not recommended.

**Closed by justincormack** 2016-10-11 18:21 UTC
Labels: area/runtime

**Comment by jeffrey4l** [comment] 2016-10-11 18:24
please do not close this.

when using shared mount, this issue still exist.

**Comment by mty22** [comment] 2016-10-11 22:41
Please don't close this without giving it some consideration and testing. A lot of troubleshooting has been done here which may save you some time:

https://bugs.launchpad.net/kolla/+bug/1616268

**Comment by jeffrey4l** [comment] 2016-10-12 02:17
This is not related to the mount propagation.  Check the steps, the namespace is created out of the container.  we did nothing in the containers.
I think the root cause should be docker-engine handle the mount point with wrong.

**Comment by justincormack** [comment] 2016-10-15 09:03
I think you want private mounts not shared ones. The issue is because you are mounting `/var/run` which has the netns mountpoint underneath, which is nothing to do with docker. You can `strace` the process and see what the mount options are, and you can change them, but the issue is entirely due to this mount, not to anything docker does.

**Comment by jeffrey4l** [comment] 2016-10-16 15:17
fair enough.  i changed `/run:/run` to `/run:/run:shared` fixed this issue in kolla.

thanks a lot.
