### ISSUE TITLE
Cannot Install (dockers) for Collabora Online server on Ubuntu 16.04 [can anyone help me please?]

### ISSUE THREAD

**Issue by khanasif2** [docker/docker#31178] opened 2017-02-20 08:20 UTC
**Description**

my domain name is www.nextcloud-forum-asia.org 
and I am following this tutorial steps to install COLLABORA Online one my Ubuntu 16.04 https://www.linuxbabe.com/cloud-storage/integrate-collabora-online-server-nextcloud-ubuntu-16-04
**Steps to reproduce the issue:**
1. My domain name is www.nextcloud-forum-asia.org
2. So I use this command 
sudo docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=nextcloud\\nextcloud-forum-asia\\.org' --restart always --cap-add MKNOD collabora/code

or 

sudo docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=nextcloud\\.forum-asia\\.org' --restart always --cap-add MKNOD collabora/code

3.

**Describe the results you received:**
I get following error and I cannot continue to next step

docker: Error response from daemon: oci runtime error: process_linux.go:330: running prestart hook 0 caused "exit status 1: time=\"2017-02-20T01:43:35-05:00\" level=fatal msg=\"failed to add interface vethd6f3252 to sandbox: failed to get link by name \\\"vethd6f3252\\\": Link not found\"\n".

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-02-20 09:33
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to comment after I closed 👍

**Closed by thaJeztah** 2017-02-20 09:33 UTC
Labels: area/runtime

**Comment by khanasif2** [comment] 2017-02-22 07:54
Dear Sir, 

I follow the steps you told in 
    groupadd: Invalid configuration: SYS_GID_MIN (101), GID_MIN (100), SYS_GID_MAX (99
That looks odd, never seen that one. Actually; looks like a misconfiguration on your computer; see http://unix.stackexchange.com/questions/80277/whats-the-difference-between-a-normal-user-and-a-system-user.

but still when I try to install sudo apt install docker.io
I am getting this following error (I am using Ubuntu 16.0.4 LTS)
Errors were encountered while processing:
 docker-engine
E: Sub-process /usr/bin/dpkg returned an error code (1)
