### ISSUE TITLE
Docker logs from running container missing content

### ISSUE THREAD

**Issue by danielrowles-wf** [docker/docker#10617] opened 2015-02-06 14:18 UTC
Description of problem:
When connecting to a running container to fetch logs, it is possible to miss some output generated as you are connecting. This issue occurs inside ```daemon/logs.go```. There is a window between the EOF on the saved logs (https://github.com/docker/docker/blob/abdfb21e3a761efdd70614de42905ff7911c5372/daemon/logs.go#L94) , and the the call to ```container.StdoutLogPipe()``` (https://github.com/docker/docker/blob/abdfb21e3a761efdd70614de42905ff7911c5372/daemon/logs.go#L120) during which any output generated within the container will not be sent to the client.

`docker version`:
```
Client version: 1.4.1-dev
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): abdfb21-dirty
OS/Arch (client): linux/amd64
Server version: 1.4.1-dev
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): abdfb21-dirty
```

`docker info`: 
```
Containers: 51
Images: 59
Storage Driver: devicemapper
 Pool Name: docker-8:33-1835009-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 3.308 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 7.197 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-45-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 7.798 GiB
Name: dev2
ID: N35I:662K:TJUL:ECLU:CIJ2:P6FM:23Q6:W6DT:ZSGV:TWPE:TLFW:WGWG
Debug mode (server): true
Debug mode (client): true
Fds: 12
Goroutines: 14
EventsListeners: 0
Init Path: /home/rowlesd/workspaces/open-source/docker/bundles/1.4.1-dev/binary/docker-1.4.1-dev
Docker Root Dir: /mnt/docker-dm
WARNING: No swap limit support
```

`uname -a`:
```
Linux dev2 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment Details:
Ubuntu Trusty virtual machine running in virtualbox on OSX.
Using python 2.7.6-8 (shipped with ubuntu, installed via apt-get)
Using gevent 1.0.1, and docker-py 0.7.2.

Steps to reproduce:
Run the following script:
```python
from gevent import monkey
monkey.patch_all()

import gevent
import docker


def stream_logs(client, cont_id):
    params = {
        'stdout': 1,
        'stderr': 0,
        'timestamps': 0,
        'follow': 1,
    }
    url = client._url("/containers/{}/logs".format(cont_id))
    res = client._get(url, params=params, stream=True)
    res.raise_for_status()

    print 'STDOUT BEGIN'

    out = []
    for entry in res.iter_lines(chunk_size=1):
        print 'STDOUT: %s' % entry
        out.append(entry)

    print "STDOUT DONE"

    res.close()
    return out

def test(client, layer_id):
    container = client.create_container(
        layer_id, 'echo "PIES"', tty=True,
    )

    print 'Container id: %s' % container['Id']

    client.start(container)

    greenlet = gevent.spawn(stream_logs, client, container['Id'])

    code = client.wait(container)

    print "Exit code: <%s>" % code
    if code != 0:
        raise RuntimeError('Bad exit code')

    stdout = greenlet.get()

    if not stdout or stdout[0] != 'PIES':
        print "BAD LOGS: %s" % stdout
        raise RuntimeError('BAD LOGS')

    client.remove_container(container)

    print 'DONE'

def main():
    client = docker.Client(
        base_url='unix://var/run/docker.sock',
    )
    client.pull('ubuntu', 'trusty')
    layer = client.inspect_image('ubuntu:trusty')
    print 'Will run on layer: <%s>' % layer['Id']
    while True:
        test(client, layer['Id'])

main()
```

Sample output:
```
Will run on layer: <5ba9dab47459d81c0037ca3836a368a4f8ce5050505ce89720e1fb8839ea048a>
Container id: eacf5c181055807fad1e57d64a32f5adbc22b1d2b4a28fa020ea48223182a8dc
STDOUT BEGIN
STDOUT: PIES
STDOUT:
STDOUT DONE
Exit code: <0>
DONE
Container id: 0e1b9605c7b0c1d98353949f9d35f4c4a5f4fb059f7393c5159685b673bb71f4
STDOUT BEGIN
STDOUT DONE
Exit code: <0>
BAD LOGS: []
Traceback (most recent call last):
  File "poc.py", line 73, in <module>
    main()
  File "poc.py", line 71, in main
    test(client, layer['Id'])
  File "poc.py", line 52, in test
    raise RuntimeError('BAD LOGS')
RuntimeError: BAD LOGS
```

This script will (generally within 20 attempts on my local environment) exit having not seen any output from the container. Subsequent calls to fetch the container logs do, however, return the expected output (the string PIES).

To confirm the issue lies within docker (and not in the python client), I configured my local docker server to listen on tcp port 2375, used wireshark to watch the network traffic, and confirmed that docker did not return any data in response to the call to fetch logs when an error was reported by the python code, but did return data when no error was reported.

Actual Results:
Script crashes with RuntimeError('BAD LOGS')

Expected Result:
Script should run indefinitely without producing errors.

**Comment by LK4D4** [comment] 2015-02-06 16:44
Hmmm, only fix that I see - tailing file instead of copying pipes. This also should be less memory consuming.

**Comment by jfrazelle** [comment] 2015-07-10 21:29
are you still able to reproduce this on latest

**Comment by cpuguy83** [comment] 2015-07-11 02:21
#14442 will fix this.

**Comment by thaJeztah** [comment] 2015-08-16 00:00
closing because https://github.com/docker/docker/pull/14442 was merged, but feel free to comment if you're still able to reproduce

**Closed by thaJeztah** 2015-08-16 00:00 UTC
Labels: status/more-info-needed

**Comment by stefwalter** [comment] 2015-12-18 11:29
Still happens #18497
