### ISSUE TITLE
Runtime Panic While Building From Shared Folder Context with symlinks

### ISSUE THREAD

**Issue by techgaun** [docker/docker#8823] opened 2014-10-28 16:44 UTC
I am implementing dockerized uniform environment for a node.js application and am getting this particular issue for one team member. I am a full time linux user and it just works appropriately with *ubuntu server* on VM(that's how I tried to best replicate the windows setup with *boot2docker*). We also tested on another windows machine and were able to build the image and run the container successfully.

Environment:-
* Windows 7  64 bit,  8GB Intel Core i5-4300M CPU@2.60GHz 
* docker 1.2.0
* boot2docker install from https://github.com/boot2docker/windows-installer/releases/download/v1.2.0/docker-install.exe overridden with boot2docker.iso with guest additions
* Virtualbox 4.3.14
* Symlink enabled for the share

The context is around 30MB and does not include the node_modules. I have tested this with both normal user and root user inside the VM.

I also checked the [source code of utils.go] (https://github.com/docker/docker/blob/fa7b24f2c3948d1eb52453c609417a6bc7eba5dd/utils/utils.go) and can not relate anything for this issue since it is working on the other windows machine. I've played around with folder permission and security as well as security policies for local users too.

![stacktrace](https://cloud.githubusercontent.com/assets/1886670/4812238/47f87726-5ebf-11e4-87a1-ac67c86fccd2.png)

**Comment by jfrazelle** [comment] 2015-02-26 03:03
I can't reproduce a panic, closing

**Closed by jfrazelle** 2015-02-26 03:03 UTC
Labels: bug
