### ISSUE TITLE
Docker APIError: 500 Server Error

### ISSUE THREAD

**Issue by jaronoff97** [docker/docker#24512] opened 2016-07-11 18:33 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:09:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   876f3a7
 Built:        Tue Jul  5 02:20:13 2016
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 28
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 84
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.14-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: R66F:4TJ7:KDYG:LF7F:XJCE:A5KL:3BCF:PAOZ:ZRGX:LWTE:IHHJ:5FPB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 69
 System Time: 2016-07-11T18:30:13.210914606Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
Not sure how to reproduce on other machines. For me, it happens when trying to access a page on a local version of my company's portal. 

**Describe the results you received:**
```
portal_1  | [11/Jul/2016 18:02:10] "GET /api/company/91192/diligence-details/ HTTP/1.1" 200 1540654
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 439, in wait
  File "site-packages/docker/client.py", line 154, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("dial unix /Users/jacobaronoff/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused")

Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 439, in wait
  File "site-packages/docker/client.py", line 154, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("dial unix /Users/jacobaronoff/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused")
```

**Describe the results you expected:**
I expected to see the data populate

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens frequently but not all the time.

**Comment by thaJeztah** [comment] 2016-07-12 00:31
Looks like a duplicate of https://github.com/docker/docker/issues/24045; please continue the discussion there. Thanks for reporting!

**Closed by thaJeztah** 2016-07-12 00:31 UTC
Labels: group/pinata, version/1.12
