### ISSUE TITLE
Should update the alias of container(s) who had been linked by A container when A container is being renamed

### ISSUE THREAD

**Issue by ptptptptptpt** [docker/docker#23973] opened 2016-06-27 03:43 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        
 OS/Arch:      linux/amd64
```

**Steps to reproduce the issue:**
```
# docker run --name db1 -e MYSQL_ROOT_PASSWORD=abc -d mysql

# docker run --name app1 -d --link db1:/mysql nginx

# docker inspect app1/mysql
[
    {
        "Id": "4c1b5bf59e9570256adfd6f5d9e05f025d0f1d31b20469363bf410c1a010cf73",
        "Created": "2016-06-27T03:31:54.825661634Z",
        "Path": "docker-entrypoint.sh",
    ...
        "Name": "/db1",
    ...
    }
]

# docker rename app1 app2

# docker inspect app2/mysql
[]
Error: No such image, container or task: app2/mysql

# docker inspect app1/mysql
[
    {
        "Id": "4c1b5bf59e9570256adfd6f5d9e05f025d0f1d31b20469363bf410c1a010cf73",
        "Created": "2016-06-27T03:31:54.825661634Z",
        "Path": "docker-entrypoint.sh",
    ...
        "Name": "/db1",
    ...
    }
]
```

**Describe the results you received:**
When container "app1" was renamed to "app2", the alias "app1/mysql" was not updated to "app2/mysql". 

**Describe the results you expected:**
The alias "app1/mysql" should be updated to "app2/mysql".

**Comment by yongtang** [comment] 2016-06-27 15:14
The issue seems to be because `rename` does not update nameIndex and linkIndex. I can take a look at it. #dibs

**Comment by tiborvass** [comment] 2016-06-27 21:52
@thaJeztah @yongtang i wonder if this is a duplicate of an existing issue :S

**Comment by thaJeztah** [comment] 2016-06-27 21:57
@tiborvass yeah, was thinking. Anoother issue (which, I think @yongtang also opened a PR for) was for "unnamed" containers never becoming "named" containers (thus getting resolved). Not sure about this one, and I wonder if it's something new (given that it's in the "legacy" networking code)

**Comment by yongtang** [comment] 2016-06-28 02:01
Thanks @tiborvass @thaJeztah.

This issue is because docker daemon use `nameIndex` and `linkIndex` for storing indices that would be used to find the container based on the name. However, in case of `docker rename`, both` nameIndex` and `linkIndex` are not updated (with the new name). Therefore, the next time a client tries to query the name, it will not be able to find it through nameIndex.

I created a pull request #24020 to try to address this issue.

There was another issue #23720 related to `docker rename`. That issue was because `docker start` may last quite long (a whole session) yet it tries to use the container name (instead of container ID) at the end of the session. If the container has been renamed while the session is still on, docker will not be able to find the container with container name (container ID is fine in that case).

Please let me know if there are any issues.

**Closed** 2016-07-29 16:24 UTC
Labels: kind/bug, priority/P3, status/claimed, version/1.12
