### ISSUE TITLE
[1.10.1] docker daemon -b none creates a bridge named "none"

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#20297] opened 2016-02-13 05:49 UTC
I believe this issue has existed since 1.9 but I just noticed it.  If you launch the daemon with `-b none` you end up with a bridge interface named `none`.  Obviously if I want to disable bridge networking, I probably don't want a bridge created named `none`.

**Comment by HackToday** [comment] 2016-02-16 02:04
hi @ibuildthecloud  not quite understood this issue,

for 
```
 -b, --bridge                             Attach containers to a network bridge
```

When you use -b none, created a bridge named none, what do you think the expect result be?

**Comment by mYmNeo** [comment] 2016-03-01 07:52
I have the same problem.The situation is that our machine does not have module about nat, while we set `-b none`, the daemon did treat this setting as bridge disabled, but libnetwork still tried to initialize the bridge driver and it failed to initialize because lack of module nat, finally the daemon failed to start.To solve this problem I add a option to disable specific driver while libnetwork initialization,see [this](https://github.com/docker/libnetwork/pull/980)

**Comment by LK4D4** [comment] 2016-09-14 21:46
ping @mrjana @mavenugo @aboch @sanimej

**Comment by aboch** [comment] 2016-09-26 20:42
@ibuildthecloud 
I am not able to recreate this with 1.11.2, 1.12.0 or 1.12.1.
Probably this was fixed as part of some other changes. 
Can you reproduce with recent images ?

**Comment by mavenugo** [comment] 2016-10-22 17:58
ping @ibuildthecloud

**Comment by mavenugo** [comment] 2016-10-27 19:05
I will go ahead and close the issue. Please comment if this issue is still seen in 1.12.x.

**Closed by mavenugo** 2016-10-27 19:05 UTC
Labels: area/networking, kind/bug, status/more-info-needed
