### ISSUE TITLE
Go SetMaxThreads should be tunable

### ISSUE THREAD

**Issue by jeremyeder** [docker/docker#15256] opened 2015-08-03 16:49 UTC
Docker had better vertical scaling and density in earlier versions.

Docker 1.2 -> 4600 when we stopped trying
Docker 1.8 -> 2500 and Docker crashes [1]

A throttle called SetMaxThreads was added to Go 1.3 [2][3].  This limit is set to 10,000 by default.
10,000 is significantly lower than the limit that the operating system places on threads (which is generally in the hundreds-of-thousands range).

Please expose SetMaxThreads to the user via daemon option, with a limit less than /proc/sys/kernel/threads-max (90%?).

[1] https://github.com/docker/docker/pull/12159#issuecomment-125739702
[2] https://golang.org/pkg/runtime/debug/#SetMaxThreads
[3] https://github.com/golang/go/blob/master/src/runtime/debug/garbage.go#L125

**Comment by jeremyeder** [comment] 2015-08-03 16:53
@vbatts @rhatdan

**Comment by LK4D4** [comment] 2015-08-03 16:53
@jeremyeder What 4600 and 2500 means?

**Comment by jeremyeder** [comment] 2015-08-03 16:57
Number of running containers on a single OS image.

**Comment by jeremyeder** [comment] 2015-08-03 16:57
https://github.com/docker/docker/issues/15258

**Comment by bpradipt** [comment] 2015-10-13 13:16
@jeremyeder,  Is reaching the maxthreads limit an indication to problems in other areas, which is getting manifested due to stress on the system ?

The description of the SetMaxThreads function mentions this:
"A Go program creates a new thread only when a goroutine is ready to run but all the existing threads are blocked in system calls, cgo calls, or are locked to other goroutines due to use of runtime.LockOSThread. "

Btw, we also had to change the MaxThreads option when trying to create more than 5000 containers on a PowerPC system.  However the failure is not consistent. IOW, I have not been able to repeatedly create the failure with the original maxthreads value (10K) and creating 5001 containers.

**Comment by runcom** [comment] 2015-10-29 10:14
> @jeremyeder, Is reaching the maxthreads limit an indication to problems in other areas, which is getting manifested due to stress on the system ?

to me it seems with newer Docker versions, more things are blocking and requires another thread to be allocated (threads won't be deallocated in go runtime but kept to be reused iirc so someone, somewhere, is leaking). Understanding what it causing this would help fixing this for sure.

`SetMaxThreads` could be a workaround to this but given 10k is really low it could be autoset to 80-90% of `/proc/sys/kernel/threads-max` (but with a leak we could substantially end up waiting on sheduling 80-90% of the time)

**Comment by runcom** [comment] 2015-10-29 10:16
@jeremyeder how could I reproduce this to trigger the leak? a dump of the goroutines when it's almost at the limit could help finding a pattern and see what's happening

**Comment by jeremyeder** [comment] 2015-10-29 12:08
Create 2500 containers :-)

**Comment by unclejack** [comment] 2015-10-29 12:16
#11529 might be worth looking at if you want to improve things. Implementing #11529 would fix a lot of problems.

**Comment by estesp** [comment] 2016-04-06 21:41
Given #18362 was merged and will be available in Docker 1.11, is there still a need for a tunable? 90% of  threads-max is going to be a much higher limit than the Go-default 10k.

**Comment by LK4D4** [comment] 2016-04-06 21:44
@estesp it's probably not needed at all because so many syscalls went to runc.

**Comment by estesp** [comment] 2016-04-06 21:52
@LK4D4 that's one of the reasons I was looking at this..I assume thread "pressure" is greatly decreased with the process separation

**Comment by jeremyeder** [comment] 2016-04-06 21:59
Probably right.  @runcom as long as you agree, we can close this.

**Comment by runcom** [comment] 2016-04-06 22:13
Right, closing this

**Closed by runcom** 2016-04-06 22:13 UTC
Labels: kind/enhancement
