### ISSUE TITLE
Cannot ping the VIP of a container by its service name across multi-host in 1.12 swarm mode

### ISSUE THREAD

**Issue by twang2218** [docker/docker#25497] opened 2016-08-08 16:36 UTC
I cannot ping the container on another docker host by its service name if the `--endpoint-mode` is `vip`.

To reproduce the problem, I create a 2-node swarm cluster by following commands:

``` bash
docker-machine create -d virtualbox node-1
docker-machine create -d virtualbox node-2

ManagerIP=`docker-machine ip node-1`

docker-machine ssh node-1 docker swarm init --advertise-addr ${ManagerIP}

WorkerToken=`docker-machine ssh node-1 docker swarm join-token worker | grep token | awk '{ print $2 }'`

docker-machine ssh node-2 "docker swarm join --token ${WorkerToken} ${ManagerIP}:2377 --advertise-addr $(docker-machine ip node-2)"
```

Then, I created an `overlay` network:

``` bash
eval "$(docker-machine env node-1)"
docker network create -d overlay frontend
```

Then, I created 4 services

``` bash
docker service create \
    --name s1 \
    --constraint 'node.hostname == node-1' \
    --network frontend \
    nginx:latest

docker service create \
    --name s2 \
    --constraint 'node.hostname == node-2' \
    --network frontend \
    nginx:latest

docker service create \
    --name s3 \
    --constraint 'node.hostname == node-1' \
    --network frontend \
    --endpoint-mode dnsrr \
    nginx:latest

docker service create \
    --name s4 \
    --constraint 'node.hostname == node-2' \
    --network frontend \
    --endpoint-mode dnsrr \
    nginx:latest
```

`s1` and `s2` are `--endpoint-mode=vip` by default,
`s3` and `s4` are specified `--endpoint-mode=dnsrr`.

As the constraints setting, `s1` and `s3` will run on `node-1`, and `s2` and `s4` will run on `node-2`. 

Then, `ping` test matrix are:

|  | s1 | s2 | s3 | s4 |
| --- | --- | --- | --- | --- |
| s1 | ok | x | ok | ok |
| s2 | x | ok | ok | ok |
| s3 | ok | x | ok | ok |
| s4 | x | ok | ok | ok |

All `vip`s acrossed multi-host are not pingable.

For the failed pings, it returned the error `Destination Host Unreachable`, such as,

``` bash
root@ab79b97007a6:/# ping s1
PING s1 (10.0.0.2): 56 data bytes
92 bytes from ab79b97007a6 (10.0.0.7): Destination Host Unreachable
92 bytes from ab79b97007a6 (10.0.0.7): Destination Host Unreachable
92 bytes from ab79b97007a6 (10.0.0.7): Destination Host Unreachable
^C--- s1 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
```

I tried the command `ping tasks.{service-name}` mentioned in #24201, it's pingable in all cases.

**Comment by thaJeztah** [comment] 2016-08-08 18:12
could be a duplicate of https://github.com/docker/docker/issues/25340, or https://github.com/docker/docker/issues/24531

**Comment by voytoo** [comment] 2016-08-08 19:40
I have similar problem.

I have 3 master nodes and 3 worker nodes.
swarm-master-0
swarm-master-1
swarm-master-2

swarm-node-0
swarm-node-1
swarm-node-2

On _swarm-master-0_ I have executed following commands.

`sudo docker network create --driver overlay --subnet=172.20.0.0/16 test-network`

`sudo docker service create
          --network infra-network
          --name jenkins-master
          --mount type=volume,src=jenkins,dst=/var/jenkins_home,volume-driver=flocker
          --publish 8080:8080
          jenkins`

`sudo docker service create
          --replicas=3
          --name cloud-gateway
          --network test-network
          --publish 80:80 nginx`

Service jenkins-master is running on swarm-node-0.
Service cloud-gateway is running on swarm-node-0, swarm-node-1 and swarm-node-2

On _swarm-master-0_ getting following network inspect output.

```
[cadmin@swarm-master-0 ~]$ sudo docker network inspect test-network 
[                                                                   
    {                                                               
        "Name": "test-network",                                     
        "Id": "57x01w135p90cq2rvpypm0dcp",                          
        "Scope": "swarm",                                           
        "Driver": "overlay",                                        
        "EnableIPv6": false,                                        
        "IPAM": {                                                   
            "Driver": "default",                                    
            "Options": null,                                        
            "Config": [                                             
                {                                                   
                    "Subnet": "172.20.0.0/16",                      
                    "Gateway": "172.20.0.1"                         
                }                                                   
            ]                                                       
        },                                                          
        "Internal": false,                                          
        "Containers": null,                                         
        "Options": {                                                
            "com.docker.network.driver.overlay.vxlanid_list": "260" 
        },                                                          
        "Labels": null                                              
    }                                                               
]                            
```       

On _swarm-node-0_ getting following network inspect output.

```
[cadmin@swarm-node-0 ~]$ sudo docker network inspect test-network
[
    {
        "Name": "test-network",
        "Id": "57x01w135p90cq2rvpypm0dcp",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.20.0.0/16",
                    "Gateway": "172.20.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "7a8e95e7031f090ffb13914daa407126b6fc3b87c88e6a65ef8aae8b1c508859": {
                "Name": "jenkins-master.1.29chnw0bvlduxonrel1cbnwp8",
                "EndpointID": "e56364e31d2f24e098dd6c5e37a96a162f6bbda66f2b2ef3d526877347b7cd86",
                "MacAddress": "02:42:ac:14:00:03",
                "IPv4Address": "172.20.0.3/16",
                "IPv6Address": ""
            },
            "8f9b604486f7987b02c5e1bab997247251025acddc922b03e54a748b27eed476": {
                "Name": "cloud-gateway.3.daay3ihy61o574c2r3fot4pf4",
                "EndpointID": "963eda66ce96c5ed48b2b98d5df30bb89299304aeb70a670032b20949bf6f544",
                "MacAddress": "02:42:ac:14:00:07",
                "IPv4Address": "172.20.0.7/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "260"
        },
        "Labels": {}
    }
]
```

On _swarm-node-1_ getting following network inspect output.

```
[cadmin@swarm-node-1 ~]$ sudo docker network inspect test-network                                 
[                                                                                                 
    {                                                                                             
        "Name": "test-network",                                                                   
        "Id": "57x01w135p90cq2rvpypm0dcp",                                                        
        "Scope": "swarm",                                                                         
        "Driver": "overlay",                                                                      
        "EnableIPv6": false,                                                                      
        "IPAM": {                                                                                 
            "Driver": "default",                                                                  
            "Options": null,                                                                      
            "Config": [                                                                           
                {                                                                                 
                    "Subnet": "172.20.0.0/16",                                                    
                    "Gateway": "172.20.0.1"                                                       
                }                                                                                 
            ]                                                                                     
        },                                                                                        
        "Internal": false,                                                                        
        "Containers": {                                                                           
            "32596fb6d94ef74264721643e89b7b1130b7bafbe22c870f9354b42f0191bd5f": {                 
                "Name": "cloud-gateway.2.c379yq6qivnnvr1hk5smquncd",                              
                "EndpointID": "abcd0de1ace8be072ff9599484509113fc7b9429c47b218ef54bc28aa61a34e0", 
                "MacAddress": "02:42:ac:14:00:06",                                                
                "IPv4Address": "172.20.0.6/16",                                                   
                "IPv6Address": ""                                                                 
            }                                                                                     
        },                                                                                        
        "Options": {                                                                              
            "com.docker.network.driver.overlay.vxlanid_list": "260"                               
        },                                                                                        
        "Labels": {}                                                                              
    }                                                                                             
]   
```                                                                                              

On _swarm-node-0_ I am able to nslookup jenkins-master.

```
root@8f9b604486f7:/# nslookup jenkins-master
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   jenkins-master
Address: 10.255.0.2

root@8f9b604486f7:/# curl jenkins-master:8080
<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2F'/><script>window.location.replace('/login?from=%2F');</script></head><body style='background-color:white; color:white;'>

root@8f9b604486f7:/# ping jenkins-master
PING jenkins-master (10.255.0.2): 56 data bytes
64 bytes from 10.255.0.2: icmp_seq=0 ttl=64 time=0.217 ms
64 bytes from 10.255.0.2: icmp_seq=1 ttl=64 time=0.101 ms
64 bytes from 10.255.0.2: icmp_seq=2 ttl=64 time=0.164 ms
^C--- jenkins-master ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.101/0.161/0.217/0.047 ms
```



On _swarm-node-1_ I am NOT able to nslookup jenkins-master.

```
root@32596fb6d94e:/# nslookup jenkins-master
Server:         127.0.0.11
Address:        127.0.0.11#53

** server can't find jenkins-master: NXDOMAIN

root@32596fb6d94e:/# ping jenkins-master
ping: unknown host

root@32596fb6d94e:/# curl jenkins-master:8080
curl: (6) Could not resolve host: jenkins-master
```

**Comment by twang2218** [comment] 2016-08-10 03:16
@voytoo I'm not quite sure it's the same problem. In my case, the service discovery was ok. On any container, the DNS returned the VIP or DNSRR results correctly. But in your case, it seems the service discovery didn't work somehow.

**Comment by twang2218** [comment] 2016-08-10 03:40
@thaJeztah My case may not be duplicate of #25340 . I tested `curl` the service across hosts, it's ok.

For example, `s1` cannot ping `s2`:

```bash
root@56554ee16130:/# ping s2
PING s2 (10.0.0.4): 56 data bytes
92 bytes from 56554ee16130 (10.0.0.3): Destination Host Unreachable
92 bytes from 56554ee16130 (10.0.0.3): Destination Host Unreachable
92 bytes from 56554ee16130 (10.0.0.3): Destination Host Unreachable
^C--- s2 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
```

But, it's ok to `curl` the `s2`'s web service:

```bash
root@56554ee16130:/# curl s2
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

So, in my case, `ping` is the one not working across hosts, but TCP works fine across hosts.

**Comment by sanimej** [comment] 2016-08-10 04:39
@twang2218 The behavior you are seeing expected. VIP based services use Linux IPVS load balancing to route to the backend containers. This works only for TCP/UDP protocols. When you use DNS-RR mode services don't have a VIP allocated. Instead service names resolves to one of the backend container IPs randomly.

For VIP based services the reason ping works on the local node is because the VIP is added a 2nd IP address on the overlay network interface. @mrjana @sfsmithcha In the documentation I think we should add a specific note about this.

**Comment by twang2218** [comment] 2016-08-10 05:35
@sanimej I thought the pingable issue #24201, was solved, as it's closed by #24573.

If it's just a partially fix, is there anyway to make the VIP pingable across the hosts? As it's quite common to use `ping` to test the network connectivity, the `Destination Host Unreachable` quite confuse the people without the certain understanding of how IPVS works, especially some containers are pingable, some are not.

**Comment by sfsmithcha** [comment] 2016-08-10 21:09
@sanimej added a section on using ping w/ DNS/service discovery to this PR https://github.com/docker/docker/pull/25420

**Comment by RRAlex** [comment] 2016-08-18 15:54
Not sure if related, but I have a 2 VMs test swarm and doing something like this:

`docker service create --name swarm --network=mynet --replicas 8 --endpoint-mode vip -p 2048:2048 ubuntu:16.04 sleep 3600`

Ends up with 4 containers on each VM, but then within any node's container I'll only see the local containers getting resolved by DNS (via exec). If I get the IP or the long name from the other node, it's impossible to ping or even resolve from the first. It's as if the overlay network was completely dead.

Only difference is I used -o encrypted while creating the network.

**Comment by mackeyja92** [comment] 2016-08-22 19:34
I am experiencing the same issues.

I have a 3 node swarm and I am creating a global service on the same overlay network. When inspecting the network I only see the nodes from the same host. (which would be one). 

Some nodes aren't able to talk to each other either. Pretty much any container on node one cannot talk to containers on nodes 2 and 3. But those nodes can communicate just fine. 

```
root@docker1:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

Here are all the networks
```
root@docker1:~# docker network ls --no-trunc
NETWORK ID                                                         NAME                DRIVER              SCOPE
9a76de4ed7d8981f6fd4f5b6fcb6d73c6ff6638cebc290f624e2264f05a75d57   bridge              bridge              local
e46xnso3dnhjdm8m5fk0dplss                                          consul              overlay             swarm
92b77354895af4bccb5532bd3612098779f06a9d8ca166d9623556b4d2676b82   docker_gwbridge     bridge              local
f5bab053e1aa2d14a4f162bd2035daec67f55686d8eb646ac93094a14a09d005   host                host                local
3dp3c6txarfssaquv3yf8h9us                                          ingress             overlay             swarm
2fbfc31756d227eebef5e5862bf2fda467ad187b4b67f6c43ad8268d543dbe15   none                null                local
```
```
root@docker1:~# docker network inspect consul
[
    {
        "Name": "consul",
        "Id": "e46xnso3dnhjdm8m5fk0dplss",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.20.0.0/24",
                    "Gateway": "172.20.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "f586935891814623ab16360dff40c65a830a0354205600207504bc87e82cab30": {
                "Name": "consul-slave.0.1q27lfhkyaxg1r3joyjdfexft",
                "EndpointID": "e469f981d19c692e7f885ef890eb17c924922ef9d1888117ae198b93e4749fc5",
                "MacAddress": "02:42:ac:14:00:07",
                "IPv4Address": "172.20.0.7/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "258"
        },
        "Labels": {}
    }
]
```

But when inspecting that node from node3 it doesn't even see that it has that network.

```
root@docker3:~# docker node inspect docker1
[
    {
        "ID": "10kr5wkodh84d4vyrhxqdbtz9",
        "Version": {
            "Index": 10379
        },
        "CreatedAt": "2016-08-15T22:37:37.563789553Z",
        "UpdatedAt": "2016-08-22T18:30:24.12890603Z",
        "Spec": {
            "Role": "manager",
            "Availability": "active"
        },
        "Description": {
            "Hostname": "docker1",
            "Platform": {
                "Architecture": "x86_64",
                "OS": "linux"
            },
            "Resources": {
                "NanoCPUs": 40000000000,
                "MemoryBytes": 134952415232
            },
            "Engine": {
                "EngineVersion": "1.12.1",
                "Plugins": [
                    {
                        "Type": "Network",
                        "Name": "bridge"
                    },
                    {
                        "Type": "Network",
                        "Name": "host"
                    },
                    {
                        "Type": "Network",
                        "Name": "null"
                    },
                    {
                        "Type": "Network",
                        "Name": "overlay"
                    },
                    {
                        "Type": "Volume",
                        "Name": "local"
                    }
                ]
            }
        },
        "Status": {
            "State": "ready"
        },
        "ManagerStatus": {
            "Reachability": "reachable",
            "Addr": "10.10.10.131:2377"
        }
    }
]
```

**Comment by gten** [comment] 2016-08-29 12:07
I am also facing similar issues while having an overlay network. While beginning, I used ping to test the connectivity in within a six node docker swarm setup. (The nodes are azure machines/VMs). Then I shifted to curl because it will give me a `connection refused` message instead of `host unreachable` when the connectivity is present. The connectivity problem is very random. Initially it starts out fine, but as the age of the swarm increases, the connectivity issues prop up and my kafka/zookeeper cluster goes for a toss because it cannot find other nodes.

I would love it if anyone can help me with this.

**Comment by mailjainrahul** [comment] 2016-09-07 19:51
I am also facing the similar issue. I have 5 node swarm cluster and i have deployed 2 services on that. Whenever both service containers spawned on one node, the VIP is reachable but if they are on different nodes then the service VIP is not reachable.

````
docker-machine ls
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
Exanova1   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.1   
Exanova2   -        virtualbox   Running   tcp://192.168.99.101:2376           v1.12.1   
Exanova3   -        virtualbox   Running   tcp://192.168.99.102:2376           v1.12.1   
Exanova4   -        virtualbox   Running   tcp://192.168.99.103:2376           v1.12.1   
Exanova5   -        virtualbox   Running   tcp://192.168.99.104:2376           v1.12.1

$ docker swarm init --listen-addr 192.168.99.100 --advertise-addr 192.168.99.100

$ docker service ls
ID            NAME  REPLICAS  IMAGE                                             COMMAND
19rol4xy19va  ldap  2/2       ship.cenx.com/ldap                                
4ans3skrshds  pg    2/2       docker.cenx.localnet:5000/postgresql-rahul:11111

$ docker service ps ldap
ID                         NAME    IMAGE               NODE      DESIRED STATE  CURRENT STATE           ERROR
0ax0ftiirqzovjx7bbfjjsb84  ldap.1  ship.cenx.com/ldap  Exanova4  Running        Running 47 seconds ago  
570dmdmgta4nex0ns2ze1h9jk  ldap.2  ship.cenx.com/ldap  Exanova5  Running        Running 37 seconds ago 

$ docker service ps pg
ID                         NAME  IMAGE                                             NODE      DESIRED STATE  CURRENT STATE           ERROR
17l1hhhym0bb9zrp1gd3hd1ud  pg.1  docker.cenx.localnet:5000/postgresql-rahul:11111  Exanova3  Running        Running 43 seconds ago  
8psmdtc9xxg9f9cywpm0fsgs5  pg.2  docker.cenx.localnet:5000/postgresql-rahul:11111  Exanova1  Running        Running 27 seconds ago 
````

Now when i try to ping or nc the VIP of ldap (10.255.0.10) from inside any pg container it gives me host not reachable, however if i do the same thing on the IP of other container, the connection was successful.

````
bash-4.3# ping 10.255.0.10                                                                                                                                                              
PING 10.255.0.10 (10.255.0.10): 56 data bytes
^C
--- 10.255.0.10 ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
bash-4.3# nc 10.255.0.10 389 
bash-4.3# nc -v 10.255.0.10 389
nc: 10.255.0.10 (10.255.0.10:389): Host is unreachable
bash-4.3# nc -v 10.255.0.11 389
10.255.0.11 (10.255.0.11:389) open
^Cpunt!
````
 
But if i intentionally put one of the containers of both services on same host, the the VIP is reachable with both ping and NC command. Please guide me how to resolve this issue.

```
bash-4.3# ping 10.255.0.10                                                                                                                                                              
PING 10.255.0.10 (10.255.0.10): 56 data bytes
64 bytes from 10.255.0.10: seq=0 ttl=64 time=0.154 ms
64 bytes from 10.255.0.10: seq=1 ttl=64 time=0.091 ms
^C
--- 10.255.0.10 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.091/0.122/0.154 ms
bash-4.3# nc -v 10.255.0.10 389
10.255.0.10 (10.255.0.10:389) open
^Cpunt!

bash-4.3# nc -v 10.255.0.11 389 
10.255.0.11 (10.255.0.11:389) open
^Cpunt!
bash-4.3# 
```

````
$ docker service ls
ID            NAME  REPLICAS  IMAGE                                             COMMAND
5zwbpy1awirl  pg    1/1       docker.cenx.localnet:5000/postgresql-rahul:11111  
axtc0gs9cut9  ldap  1/1       ship.cenx.com/ldap                                
rahul-jainMBP:PG_Data rahuljain$ docker service ps pg
ID                         NAME  IMAGE                                             NODE      DESIRED STATE  CURRENT STATE          ERROR
a7apemhcz4jfo3j400ekmkfw4  pg.1  docker.cenx.localnet:5000/postgresql-rahul:11111  Exanova1  Running        Running 3 minutes ago  
rahul-jainMBP:PG_Data rahuljain$ docker service ps ldap
ID                         NAME        IMAGE               NODE      DESIRED STATE  CURRENT STATE          ERROR
e44wkc35srryy1wfhp6eze1m2  ldap.1      ship.cenx.com/ldap  Exanova1  Running        Running 3 minutes ago
````

````
$ docker service inspect pg
[
    {
        "ID": "6nhqocnposee7tlau78p1rqlh",
        "Version": {
            "Index": 143
        },
        "CreatedAt": "2016-09-07T19:17:39.886552497Z",
        "UpdatedAt": "2016-09-07T19:17:57.221791979Z",
        "Spec": {
            "Name": "pg",
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "docker.cenx.localnet:5000/postgresql-rahul:11111",
                    "Mounts": [
                        {
                            "Type": "bind",
                            "Source": "/opt/pgsql",
                            "Target": "/opt/pgsql/data"
                        }
                    ]
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "MaxAttempts": 0
                },
                "Placement": {}
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 2
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5432,
                        "PublishedPort": 5432
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5432,
                        "PublishedPort": 5432
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 5432,
                    "PublishedPort": 5432
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "41cww5x50wgtfvzdkufp6d2xx",
                    "Addr": "10.255.0.8/16"
                }
            ]
        },
        "UpdateStatus": {
            "StartedAt": "0001-01-01T00:00:00Z",
            "CompletedAt": "0001-01-01T00:00:00Z"
        }
    }
]
````

````
$ docker service inspect ldap
[
    {
        "ID": "bym4r8uuybxtuotjn863vzc43",
        "Version": {
            "Index": 136
        },
        "CreatedAt": "2016-09-07T19:17:43.770941802Z",
        "UpdatedAt": "2016-09-07T19:17:54.589359777Z",
        "Spec": {
            "Name": "ldap",
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "ship.cenx.com/ldap"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "MaxAttempts": 0
                },
                "Placement": {}
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 2
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 389,
                        "PublishedPort": 389
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 389,
                        "PublishedPort": 389
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 389,
                    "PublishedPort": 389
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "41cww5x50wgtfvzdkufp6d2xx",
                    "Addr": "10.255.0.10/16"
                }
            ]
        },
        "UpdateStatus": {
            "StartedAt": "0001-01-01T00:00:00Z",
            "CompletedAt": "0001-01-01T00:00:00Z"
        }
    }
]
````

````
docker@Exanova1:~$ docker info
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: 5ty3sfq4331cvaz3tzg77wgux
 Is Manager: true
 ClusterID: 40gvwvn1vti0fjuokgqqj42w2
 Managers: 1
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.100
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.463 GiB
Name: Exanova1
ID: WX57:UIDD:7RCV:4F5N:G6MD:7UL6:RPQH:HO7V:4F3H:3WZ2:P4JB:5R5F
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 54
 Goroutines: 178
 System Time: 2016-09-07T19:49:19.261810095Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 docker.cenx.localnet:5000
 127.0.0.0/8
````

**Comment by sanimej** [comment] 2016-10-11 15:59
@twang2218 [libnetwork PR #1501](https://github.com/docker/libnetwork/pull/1501)  adds the ping support for service VIP across hosts.

**Closed** 2016-11-03 21:35 UTC
Labels: area/networking, area/swarm, kind/bug, priority/P3, version/1.12

**Comment by twang2218** [comment] 2016-12-05 13:00
Just confirm the bug has been fixed. I did another test on `1.13.0-rc2`, all above services' VIPs are pingable across all hosts. Thank you. 😸

**Comment by thaJeztah** [comment] 2016-12-05 13:02
Thanks for testing @twang2218!
