### ISSUE TITLE
Install Docker 1.12 on ubuntu 14.04 TLS without connection to ISP 

### ISSUE THREAD

**Issue by RotemEmergi** [docker/docker#25371] opened 2016-08-03 14:46 UTC
Hi ,

There is a wato mabay to install Docker 1.12 on ubuntu 14.04 TLS without connection to ISP ?

Best regards

**Comment by thaJeztah** [comment] 2016-08-03 18:55
You can download the static binaries, or the `.deb` package, and upload that to the machine / use an USB stick. However, if no images are present locally, running docker without internet access also requires you to manually put images on the machine (e.g. through `docker load`)

I'll close this issue, because it's a question, not a bug (so better asked at forums.docker.com, or the #docker IRC channel), but I hope it helps

**Closed by thaJeztah** 2016-08-03 18:55 UTC

**Comment by thaJeztah** [comment] 2016-08-03 18:57
Oh, instructions for installing static binaries; https://docs.docker.com/engine/installation/binaries/

and the debs themselves can be found here; http://apt.dockerproject.org/repo/pool/main/d/docker-engine/

**Comment by RotemEmergi** [comment] 2016-08-04 12:55
How do I know what are the dependence between the deb.. I want to install the docker 1.12: 
I work with that one and it's still not work
docker-engine_1.12.0-0~trusty_amd64.deb

**Comment by thaJeztah** [comment] 2016-08-04 13:20
Try `dpkg -I docker-engine_1.12.0-0~trusty_amd64.deb`, which should show you the dependencies

**Comment by RotemEmergi** [comment] 2016-08-04 13:23
new debian package, version 2.0.
 size 19351362 bytes: control archive=5675 bytes.
      91 bytes,     4 lines      conffiles            
    1227 bytes,    21 lines      control              
    8473 bytes,   113 lines      md5sums              
    3396 bytes,    97 lines   *  postinst             #!/bin/sh
     878 bytes,    25 lines   *  postrm               #!/bin/sh
     815 bytes,    22 lines   *  preinst              #!/bin/sh
     201 bytes,     7 lines   *  prerm                #!/bin/sh
 Package: docker-engine
 Version: 1.12.0-0~trusty
 Architecture: amd64
 Maintainer: Docker <support@docker.com>
 Installed-Size: 98846
 Depends: iptables, init-system-helpers (>= 1.13~), sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), libapparmor1 (>= 2.6~devel), libc6 (>= 2.17), libdevmapper1.02.1 (>= 2:
1.02.63), libltdl7 (>= 2.4.2), libsystemd-journal0 (>= 201)
 Recommends: aufs-tools, ca-certificates, cgroupfs-mount | cgroup-lite, git, xz-utils, apparmor
 Conflicts: docker (<< 1.5~), docker-engine-cs, docker.io, lxc-docker, lxc-docker-virtual-package
 Section: admin
 Priority: optional
 Homepage: https://dockerproject.org
 Description: Docker: the open-source application container engine
  Docker is an open source project to build, ship and run any application as a
  lightweight container
  .
  Docker containers are both hardware-agnostic and platform-agnostic. This means
  they can run anywhere, from your laptop to the largest EC2 compute instance and
  everything in between - and they don't require you to use a particular
  language, framework or packaging system. That makes them great building blocks
  for deploying and scaling web apps, databases, and backend services without
  depending on a particular stack or provider.
