### ISSUE TITLE
Docker restart delay is not reset as described

### ISSUE THREAD

**Issue by priestlyemu** [docker/docker#22159] opened 2016-04-19 16:39 UTC
**Output of `docker version`:**

```
  root@buildmaster-ubuntu-6:~# docker version
  Client:
   Version:      1.11.0
   API version:  1.23
   Go version:   go1.5.4
   Git commit:   4dc5990
   Built:        Wed Apr 13 18:34:23 2016
   OS/Arch:      linux/amd64

  Server:
   Version:      1.11.0
   API version:  1.23
   Go version:   go1.5.4
   Git commit:   4dc5990
   Built:        Wed Apr 13 18:34:23 2016
   OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
  root@buildmaster-ubuntu-6:~# docker info
  Containers: 0
   Running: 0
   Paused: 0
   Stopped: 0
  Images: 0
  Server Version: 1.11.0
  Storage Driver: aufs
   Root Dir: /var/lib/docker/aufs
   Backing Filesystem: extfs
   Dirs: 10
   Dirperm1 Supported: true
  Logging Driver: json-file
  Cgroup Driver: cgroupfs
  Plugins:
   Volume: local
   Network: host bridge null
  Kernel Version: 4.2.0-27-generic
  Operating System: Ubuntu 14.04.4 LTS
  OSType: linux
  Architecture: x86_64
  CPUs: 8
  Total Memory: 7.696 GiB
  Name: buildmaster-ubuntu-6
  ID: GJXV:3SLH:VQXH:EABF:CH2E:KF2B:STL6:YOJS:J6CC:GVRO:4SUH:MI6H
  Docker Root Dir: /var/lib/docker
  Debug mode (client): false
  Debug mode (server): false
  Registry: https://index.docker.io/v1/
  WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

  Fresh install of ubuntu 14.04 and docker on physical hardware

  root@buildmaster-ubuntu-6:~# lsb_release -a
  No LSB modules are available.
  Distributor ID:          Ubuntu
  Description:     Ubuntu 14.04.4 LTS
  Release:         14.04
  Codename:        trusty

  root@buildmaster-ubuntu-6:~# uname -a
  Linux buildmaster-ubuntu-6 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri
  Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1. On machine with docker:

   docker run -d --restart=always -t --privileged -p 2020:2020 \
     --name nc-test ubuntu nc -l 2020

   # then run this to watch timing
   watch docker ps

2. From another window:

   echo foo | nc <docker-host> 2020

3. The docker ps output will show a restart, wait for it to be running
   for at least 10 seconds.

4. Repeat steps 2 and 3 and watch the restart time increase on each
   invocation.

**Describe the results you received:**

I do not observe the delay being reset.

**Describe the results you expected:**

I expected restart delay to always be 100ms after waiting 10+ seconds as per the documentation at:
  https://github.com/docker/docker/blob/master/docs/reference/run.md
which says:

  "If a container is successfully restarted (the container is started and
  runs for at least 10 seconds), the delay is reset to its default value
  of 100 ms."

**Additional information you deem important (e.g. issue happens only occasionally):**

consistently reproducible

**Comment by mlaventure** [comment] 2016-04-19 16:46
This will be fixed by #22125

**Comment by priestlyemu** [comment] 2016-04-19 16:51
Thanks for the quick response!

**Comment by icecrime** [comment] 2016-04-22 17:35
Closing as duplicate of #22113, thanks for reporting!

**Closed by icecrime** 2016-04-22 17:35 UTC
Labels: kind/bug, priority/P0

**Comment by priestlyemu** [comment] 2016-05-02 14:00
I just updated to 1.11.1 and the behavior is still incorrect (although in a different way).

Now if you follow the formula above, the container doesn't seem to restart at all (based on output of 'docker ps'), however the entrypoint command seems to be restarting (as I seem to be able to continue to connect to 'nc').

**Comment by thaJeztah** [comment] 2016-05-02 14:13
Is the process expected to fail? if I use `docker events` to see what happens, and `kill -9` the container's process, I see it being restarted;

```
2016-05-02T10:07:11.361422237-04:00 container start 55a8b4c948f2891f3a81ebe058b89548762e2fd7b6d173509d7d71123b4a2920 (image=ubuntu:14.04, name=nc-test)
2016-05-02T10:08:10.180377762-04:00 container die 55a8b4c948f2891f3a81ebe058b89548762e2fd7b6d173509d7d71123b4a2920 (exitCode=137, image=ubuntu:14.04, name=nc-test)
2016-05-02T10:08:10.537266927-04:00 container start 55a8b4c948f2891f3a81ebe058b89548762e2fd7b6d173509d7d71123b4a2920 (image=ubuntu:14.04, name=nc-test)
```

And the restart-counter increments with each kill;

``bash`
$ docker inspect --format "{{ json .RestartCount }}" nc-test
1
$ kill -9 14926
$ docker inspect --format "{{ json .RestartCount }}" nc-test
2
```

Can you explain what's not working? (perhaps I misunderstood)

**Comment by priestlyemu** [comment] 2016-05-02 15:10
If I run a container with restart-always, and the entrypoint command stops running, the previous behavior was for the entire container to restart (which is what I believe to be the correct behavior).

I would determine that the container restarted via 'docker ps', which listed the uptime. I used to see it get reset each time the entrypoint command got killed. Now it does not do that (via the recipe above - i.e. where you connect to the listening 'nc', which causes it to terminate.

Even if I inspect the counter, it does not increment. Also, if you run the command without the '-d', you don't see it restart.

If I use a 'kill', as you did, I do see it restart. But that is a different operation, so maybe it has something to do with the exit status?

Just to be clear, the recipe above launches a container with a command that has 'nc' listening on a port. Once something is sent to that port, the 'nc' command terminates, which should trigger a restart of the entire container. That isn't happening. The original problem was that it would restart, but the back-off timer wasn't being reset - but the container was restarting.

So now I can't tell if the back-off timer is reset because the container isn't actually restarting when the entrypoint command is terminating naturally.

I hope that is clearer (but I rambled quite a bit, so maybe not).

**Comment by mlaventure** [comment] 2016-05-02 21:44
@priestlyemu I can not reproduce the issue here. Well, I shorta can, but after checking with @justincormack it turns out that you need to use `nc -l 0.0.0.0 2222` in your container in order for it to be reachable. Docker will route the connection to the `172.17.0.x` ip it would have had assigned to the container.

By using `localhost`, nc never receive anything and thus never exits.

(Also, you don't need to run it with `--privileged`)

**Comment by priestlyemu** [comment] 2016-05-02 22:06
My bad - It looks like it is working. Sorry for the scare. PS: I used the --privilege just because I had stripped down my actual command line (so it's vestigial) :-)

Thanks.
