### ISSUE TITLE
docker 1.9 network bridge not found

### ISSUE THREAD

**Issue by jameBoy** [docker/docker#19043] opened 2016-01-04 08:24 UTC
Today, i encountered a strange problem. I write a Dockerfile and I want to build the Dockerfile.But it show me **"network bridge not found"** and build fail.My environment is "Ubuntu:14.04".

And I run ```sudo docker -d```
it show me:
```
WARN[0000] please use 'docker daemon' instead.          
INFO[0000] API listen on /var/run/docker.sock           
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] Firewalld running: false                     
WARN[0000] Could not get list of networks during endpoint cleanup: could not find endpoint count key docker/network/v1.0/endpoint_count/f1bb818c214be83487a247888a36e7973662e8043d5c9ed1edeaf49c0f99dfd3/ for network bridge while listing: Key not found in store 
ERRO[0000] could not find endpoint count key docker/network/v1.0/endpoint_count/f1bb818c214be83487a247888a36e7973662e8043d5c9ed1edeaf49c0f99dfd3/ for network bridge while listing: Key not found in store 
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.7/16. Daemon option --bip can be used to set a preferred IP address 
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: failed to allocate gateway (172.17.0.7): No available addresses on this pool 
```

`docker version`:
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```
`docker info`:
```
Containers: 8
Images: 184
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 200
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 15.61 GiB
Name: lxq-Aspire-TC-606
ID: BXSH:ZQIL:LJ4T:66LX:A6EZ:354R:BQSB:TT4A:B2TX:KKND:CPUY:AUGJ
Username: jameboy
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```
`uname -a`:

Linux lxq-Aspire-TC-606 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

So how do I solve this problem?

**Comment by thaJeztah** [comment] 2016-01-04 12:24
This looks like a duplicate of https://github.com/docker/docker/issues/18113. Have you also been able to reproduce this on the current version? The current version of docker is 1.9.1, not 1.9.0

**Comment by jameBoy** [comment] 2016-01-05 09:49
@thaJeztah  I have solved the problem . In my machine, the current version is 1.9.0. And Iwant to know why the problem happend? I don`t do some for the docker deamon. I just to build a jenkins images, and then it show me the "network bridge not found". so i want to know why it happend?

**Comment by thaJeztah** [comment] 2016-01-05 10:02
Not sure what the reason is. These are the changes that were made between 1.9.0 and 1.9.1; https://github.com/docker/docker/compare/v1.9.0...v1.9.1

How are you running jenkins? Are you running docker-in-docker, and if so, are you bind-mounting the `/var/lib/docker` directory inside the container? Because if you do, multiple docker daemons are using the same `/var/lib/docker` directory, which is asking for trouble.

**Comment by LK4D4** [comment] 2016-09-14 17:43
Closing for inactivity. Also it possibly was solved.

**Closed by LK4D4** 2016-09-14 17:43 UTC
Labels: status/more-info-needed
