### ISSUE TITLE
regarding docker-init usage

### ISSUE THREAD

**Issue by Namsulee** [docker/docker#32232] opened 2017-03-30 15:17 UTC
**Description**

I have been testing docker as init using systemd, but if I stop the container, it would be exited with (137)
I guess the exit code was affected by zombie processes. Because, systemd is like to create child processes but it will not be reaped for orphan process. If I stop container, it will be shown like Exited(137). By the way I saw the option docker-init from v1.13 and options like '--init' and '--init-path'
anybody know how to use the option when I run the image with systemd?

**Steps to reproduce the issue:**
1. put the command in shell, it was okie to bring up with systemd
$ docker run -it --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro dockerimages/docker-systemd
Failed to insert module 'autofs4'
systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to Ubuntu 15.04!

Set hostname to <baec4fe23930>.
Initializing machine ID from random generator.
Unit etc-hostname.mount is bound to inactive unit dev-sda1.device. Stopping, too.
[  OK  ] Created slice Root Slice.
         Unmounting /etc/hostname...
[  OK  ] Unmounted /etc/hostname.
[  OK  ] Created slice System Slice.
[  OK  ] Started Emergency Shell.
         Starting Emergency Shell...
Failed at step EXEC spawning /bin/plymouth: No such file or directory
Welcome to emergency mode! After logging in, type "journalctl -xb" to view
system logs, "systemctl reboot" to reboot, "systemctl default" or ^D to
try again to boot into default mode.
root@baec4fe23930:~# 

2. If I stop the container, can see the status with 137 exit code
baec4fe23930        dockerimages/docker-systemd   "/lib/systemd/syst..."   About a minute ago   Exited (137) 3 seconds ago                       condescending_mccarthy

3. If I run with the command,
$ docker run -it --privileged --init=true -v /sys/fs/cgroup:/sys/fs/cgroup:ro dockerimages/docker-systemd
Excess arguments.
$ docker run -it --privileged --init=true --init-path=/usr/bin/docker-init -v /sys/fs/cgroup:/sys/fs/cgroup:ro dockerimages/docker-systemd
Excess arguments.

4. If I copy docker-init into container image with dockerfile build and run.(made test:v3 image)
$ docker run -it --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro test:v3Trying to run as user instance, but the system has not been booted with systemd.

Please give me any advice or questions in order to be cleared

**Output of `docker version`:**
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
(paste your output here)
```

**Output of `docker info`:**

Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 28
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 75
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.763 GiB
Name: namsu-H81H3-M4
ID: 6VSX:3RD6:BYDG:HGXJ:YINK:RADA:E6K7:RPVV:SGXV:LI56:OEDH:7JTI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: namsulee
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 13.124.64.10:80
 127.0.0.0/8
Live Restore Enabled: false
```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-03-30 15:50
The `--init` option injects `docker-init` (which is a build of "tini" https://github.com/krallin/tini) into the container, and sets that as the main process of the container (PID1), if your container already wants to use `systemd` as its init process, that probably doesn't make a lot of sense to do, because you would be "stacking" init systems, and `systemd` requires to be run as PID1

Generally, we discourage running `systemd` if not strictly needed; it requires additional privileges, and  reduces the container security (in fact, when running with `--privileged`, theres _no protection at all_, processes in a `--privileged` container can break out of the container, and take control of the host.

Running systemd in a container _is_ possible, but there's a lot of corner-cases that make it fail (you can find some existing discussions on the issue tracker), but that's really out of scope of the issue tracker.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-30 15:50 UTC
Labels: area/builder
