### ISSUE TITLE
When  running my own docker container in mac os, it does not associating provided port with container. How to solve this issue?

### ISSUE THREAD

**Issue by suchetamandal** [docker/docker#29357] opened 2016-12-13 11:21 UTC
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2016-12-13 14:12
Please keep in mind that the GitHub issue tracker is not a support forum, but for reporting bugs of feature requests.

For questions about _running_ docker, please use https://forums.docker.com, or the community slack channel; https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/

Since this is not a bug of feature request, I'll close this issue, but feel free to comment after I closed

**Closed by thaJeztah** 2016-12-13 14:12 UTC
