### ISSUE TITLE
Dockerfile MAINTAINER command

### ISSUE THREAD

**Issue by kumavis** [docker/docker#14068] opened 2015-06-21 03:13 UTC
Why does the dockerfile `MAINTAINER` token run as a command? seems like it should just be skipped...
```
Step 1 : MAINTAINER kumavis
```

**Comment by kumavis** [comment] 2015-06-21 03:17
guess it labels the docker image file, thus producing a new image but it seems strange that it isnt taken in at the parsing phase, and not run in an order as a command

**Comment by thaJeztah** [comment] 2015-06-21 03:31
true, there are some commands that don't "need" to produce a new layer (e.g., `VOLUME`, `ENV`, ` USER`, and `LABEL`) this *might* change sometime in the future.

I'm going to close this issue, because this is a question, not a bug or feature request and I think this question was answered.

**Closed by thaJeztah** 2015-06-21 03:31 UTC

**Comment by kumavis** [comment] 2015-06-21 04:50
mkay, thanks for the response
