### ISSUE TITLE
docker daemon 1.4.1 will not start on RHEL 6.5

### ISSUE THREAD

**Issue by jtison** [docker/docker#11356] opened 2015-03-12 22:47 UTC
DESCRIPTION OF PROBLEM: Despite documentation claims that docker will run on RHEL 6.5 with a minimum kernel level of 2.6.32-431, the daemon will not start, citing a missing entry point in libdevmapper.so.1.02, as follows (from /var/log/docker):

time="2015-03-12T17:32:29-04:00" level="info" msg="WARNING: You are running linux kernel version 2.6.32-431.30.1.el6.x86_64, which might be unstable running docker. Please upgrade your kernel to 3.8.0." 
/usr/bin/docker: relocation error: /usr/bin/docker: symbol dm_task_get_info_with_deferred_remove, version Base not defined in file libdevmapper.so.1.02 with link time reference

Sure enough, readelf shows that the required symbol isn't present in libdevmapper.so

DOCKER VERSION: Docker version 1.4.1, build 5bc2ff8/1.4.1  (got from EPEL)

DOCKER INFO: FATAL[0000] Get http:///var/run/docker.sock/v1.16/info: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?
(the daemon did not start, hence no valid info data)

`uname -a`: Linux w520 2.6.32-431.30.1.el6.x86_64 #1 SMP Wed Jul 30 14:44:26 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

ENVIRONMENT DETAILS: Native RHEL Linux with bash 4.1.2(1), systemv init

HOW REPRODUCIBLE: sudo service start docker

STEPS TO REPRODUCE:
1.     Attempt to start the daemon. The init.d script will indicate success.
2.     'service docker status' will report: "docker dead but pid file exists"
3.     'rm /var/run/docker.pid', then repeat step 1. Same result (#2).

If kernel level 3.8.0 is really required, then the documentation should say so. If the RHEL 6.5 version of libdevmapper.so is not sufficient, then this should be exposed too. Thanks.

**Comment by LK4D4** [comment] 2015-03-12 22:50
ping @vbatts

**Comment by vbatts** [comment] 2015-03-12 23:36
Interesting. cc @lsm5

**Comment by lsm5** [comment] 2015-03-13 17:28
@jtison what does `rpm -q device-mapper-libs` on your system show?

See [rhbz#1173950](https://bugzilla.redhat.com/show_bug.cgi?id=1173950). You might need to manually update your device-mapper-libs to `1.02.90` as doing it via yum seems to cause a lot of trouble on 6.5 while it should work without any trouble on 6.6

I'll update the docs with this. Sorry about the pain.

**Comment by jtison** [comment] 2015-03-16 13:42
@lsm5 it says: device-mapper-libs-1.02.79-8.el6.x86_64

Your remarks about 6.6 give me a little hope, I'm about to be forced into an upgrade (this week?) to 6.6, so I'll just wait and see, unless you'd rather I confirm your advice to manually upgrade device-mapper-libs. My schedule is a little nuts this week; but if you need me to do this, I'll certainly give it a whirl. 

The pain, by the way, is quite minimal: I was hoping to take advantage of Docker for things I'd _like_ to do, not that I really _need_ to do yet. I appreciate your attention and advice. Thanks!

**Comment by jtison** [comment] 2015-03-25 13:00
@lsm5 Your remarks about the RHEL 6.6 upgrade were quite true. Docker works. Thank you. This is no longer a problem for me, but may still be a problem for certain RHEL 6.5 users, I'll leave this issue open for you guys to deal with at your pleasure. Thanks again.

**Comment by vbatts** [comment] 2015-03-25 13:08
@jtison thanks for reporting back. We'll close it and folks can reference this issue for the information.

**Closed by vbatts** 2015-03-25 13:08 UTC
Labels: /os/linux/rhel

**Comment by lsm5** [comment] 2015-03-26 00:03
@jtison thanks for circling back, guess we should reference this in the docs for 6.5

**Comment by yeroc** [comment] 2015-12-03 17:12
This is likely a dupe of #12108?  It looks like there's an issue with how the dependency on device-mapper is specified which also affected CentOS 7.  I just ran into this myself on CentOS 6.5 and doing a `yum upgrade device-mapper` resolved the issue.
