### ISSUE TITLE
Docker build that fails with overlay storage backend only?

### ISSUE THREAD

**Issue by lvangool** [docker/docker#12327] opened 2015-04-13 10:27 UTC
This Dockerfile doesn't seem to build with the **overlay** storage backend:
```
from ubuntu:trusty
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y build-essential g++ libblas-dev liblapack-dev gfortran python-dev python-pip
RUN pip install --upgrade numpy
RUN pip install --upgrade statsmodels
RUN pip install --upgrade flask
```

It ends up spitting out the below errors:
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1443, in install
    requirement.commit_uninstall()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 610, in commit_uninstall
    self.uninstalled.commit()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1860, in commit
    rmtree(self.save_dir)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 43, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/pip-dXgb99-uninstall/usr/lib/python2.7/dist-packages'
```

The *same* Dockerfile works with both **AUFS** and **DeviceMapper** storage backends (have not tried with BTRFS). 

docker version: 
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

docker info:
```
Debug mode (server): false
Debug mode (client): true
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.18.0-031800-generic
Fds: 10
Goroutines: 15
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

uname -a: 
```
Linux my_server 3.18.0-031800-generic #201412071935 SMP Mon Dec 8 00:36:34 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Any suggestions or additional info I can provide?

**Comment by cpuguy83** [comment] 2015-04-13 13:53
Can you try with either the master build or the latest 1.6 RC?
https://master.docker.com for master binary
https://github.com/docker/docker/pull/11635#issuecomment-90205104 for 1.6 RC

**Comment by lvangool** [comment] 2015-04-13 17:07
Tested, exact same problem I'm afraid.

docker version:
```
Client version: 1.6.0-rc5
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): fc4825d
OS/Arch (client): linux/amd64
Server version: 1.6.0-rc5
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): fc4825d
OS/Arch (server): linux/amd64
```

**Comment by LK4D4** [comment] 2015-04-13 17:50
Yup, I can confirm in master.

**Comment by vbatts** [comment] 2015-04-14 01:56
@LK4D4 what kernel version are you running and underlying filesystem (ext4?)?

**Comment by lvangool** [comment] 2015-04-14 16:28
@vbatts yes, ext4

**Comment by LK4D4** [comment] 2015-04-14 16:29
@vbatts mine is 4.0 with ext4

**Comment by rochacon** [comment] 2015-04-29 00:31
Not sure if this is related with the overlay driver. Installing pip with the [get-pip.py](https://bootstrap.pypa.io/get-pip.py) script, which installs the latest version, works fine on overlay.

## docker info


```
% docker info
Containers: 6
Images: 45
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.19.0
Operating System: CoreOS 633.1.0
CPUs: 1
Total Memory: 996.4 MiB
```


## fail


```
FROM ubuntu:14.04
RUN apt-get update && apt-get install -yq python-pip && apt-get clean
RUN pip install -U pip
```


```
% docker build -t pip-on-docker-test .
Sending build context to Docker daemon  12.8 kB
Sending build context to Docker daemon
Step 0 : FROM ubuntu:14.04
 ---> b7cf8f0d9e82
Step 1 : RUN apt-get update && apt-get install -yq python-pip && apt-get clean
 ---> Running in 296e47de116e
Ign http://archive.ubuntu.com trusty InRelease
Ign http://archive.ubuntu.com trusty-updates InRelease
Ign http://archive.ubuntu.com trusty-security InRelease
Hit http://archive.ubuntu.com trusty Release.gpg

...Ommited apt-get output...

Processing triggers for ca-certificates (20141019ubuntu0.14.04.1) ...
Updating certificates in /etc/ssl/certs... 173 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
 ---> d10860df49b9
Removing intermediate container 296e47de116e
Step 2 : RUN pip install -U pip
 ---> Running in 888281f1cea1
Downloading/unpacking pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-6.1.1-py2.py3-none-any.whl#md5=172eb5abab25a5e0f7a7b63c7a49378d
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Uninstalling pip:
      Successfully uninstalled pip
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1443, in install
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 610, in commit_uninstall
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1860, in commit
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 43, in rmtree
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/pip-ihvxTk-uninstall/usr/bin'

Storing debug log for failure in /root/.pip/pip.log
INFO[0079] The command [/bin/sh -c pip install -U pip] returned a non-zero code: 2
```


## success


```
FROM ubuntu:14.04
RUN apt-get update && apt-get install -yq curl python-dev && apt-get clean
RUN curl https://bootstrap.pypa.io/get-pip.py | python
RUN pip install -U pip
```


```
% docker build -t pip-on-docker-test .
Sending build context to Docker daemon 13.82 kB
Sending build context to Docker daemon
Step 0 : FROM ubuntu:14.04
 ---> b7cf8f0d9e82
Step 1 : RUN apt-get update && apt-get install -yq curl python-dev && apt-get clean
 ---> Running in ef5a019b1a59
Ign http://archive.ubuntu.com trusty InRelease
Ign http://archive.ubuntu.com trusty-updates InRelease
Ign http://archive.ubuntu.com trusty-security InRelease
Hit http://archive.ubuntu.com trusty Release.gpg

...Ommited apt-get output...

Processing triggers for ca-certificates (20141019ubuntu0.14.04.1) ...
Updating certificates in /etc/ssl/certs... 173 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
 ---> b0da48adf546
Removing intermediate container ef5a019b1a59
Step 2 : RUN curl https://bootstrap.pypa.io/get-pip.py | python
 ---> Running in cce7df197a0b
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1387k  100 1387k    0     0  4294k      0 --:--:-- --:--:-- --:--:-- 4282k
/tmp/tmphICD6N/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
Collecting pip
/tmp/tmphICD6N/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  Downloading pip-6.1.1-py2.py3-none-any.whl (1.1MB)
Collecting setuptools
  Downloading setuptools-15.2-py2.py3-none-any.whl (501kB)
Installing collected packages: pip, setuptools
Successfully installed pip-6.1.1 setuptools-15.2
 ---> 7eb57b6961c5
Removing intermediate container cce7df197a0b
Step 3 : RUN pip install -U pip
 ---> Running in 5221ea38472c
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
 ---> f3670b07fff6
Removing intermediate container 5221ea38472c
Successfully built f3670b07fff6
```

**Comment by vbatts** [comment] 2015-04-29 17:23
that would be nice to confirm. From my investigation, it seemed pretty murky in the failed example, that it made one of the egg info as a unix socket and failed to remove it from /tmp. Seemed like a bad file check somewhere, but I didn't feel like that was happening in the kernel...

**Comment by LK4D4** [comment] 2015-04-29 17:24
@vbatts unix-socket also mentioned in #12080

**Comment by vbatts** [comment] 2015-04-29 17:28
correct. Overlayfs and unix sockets do not play nice together yet. But why
would a pip install make an egg info as a socket? those egg info are
usually only regular file or directory.

On Wed, Apr 29, 2015 at 1:24 PM, Alexander Morozov <notifications@github.com

**Comment by dustinlacewell** [comment] 2015-08-05 18:37
Suffering from this exactly as above with Ubuntu 14.04 with 3.19.0-25-generic and Docker 1.7.1

**Comment by townsen** [comment] 2015-10-06 00:09
I have this too with Ubuntu 15.04 with 3.19.0-28-generic, Docker 1.8.2 configured with `overlayfs`:
```

Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3
 Built:        Sun Sep 13 08:20:28 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

Containers: 4
Images: 185
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 11.72 GiB
Name: lux15
ID: GE62:5TVK:2MAB:KGHS:KMXH:RHAH:XSHQ:ZRTS:GIOG:O3TD:UGZ7:NG6Y
WARNING: No swap limit support
```

I have a second machine on which I configured the same OS (it's a VM - I just copied it) with Docker using `aufs`. The first one fails, the second works. The error line occurs during a `pip install` as above:
```
 OSError: [Errno 39] Directory not empty: '/tmp/pip-LpFx0F-uninstall/usr/local/lib/python2.7/dist-packages/nose/plugins'
```

**Comment by zamf** [comment] 2015-10-07 16:07
Same problem here with `3.19.0-22-generic` on Ubuntu 14.04 and 

```

Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Containers: 4
Images: 360
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-22-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 48
Total Memory: 503.9 GiB
Name: luke2
ID: HCWS:FZUK:Q23O:45EU:HVJW:ST6O:BMW7:HSCA:GAYK:UVPM:5BAN:LQO4
WARNING: No swap limit support
```

**Comment by LK4D4** [comment] 2015-10-15 21:26
@vbatts @rochacon @lvangool I can confirm that patch-series from https://lkml.org/lkml/2015/10/9/620 fixes both issues.

**Comment by xdays** [comment] 2016-01-12 05:08
Hi @LK4D4  when will the patch being merged, I've updated my kernel to 4.4.0, and the problem still there.


```
[www:~]# docker info
Containers: 1
Images: 7
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 992.1 MiB
Name: www.xdays.me
ID: Q2NV:RAJE:LVY5:YZ4C:ZMUH:NJU2:6MZE:PFAT:XQRE:TAKN:2Y33:OSPI
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by grahamc** [comment] 2016-01-12 17:26
I have a similar issue, copied (and closed) from #19262:

The following Dockerfile fails to build on Overlay, but works on AUFS. I replicated this on two machines, docker-machine built and one running ubuntu trusty with linux kernel 4.2.

```Dockerfile
FROM python:3.4
RUN pip install flake8==2.5.1
RUN pip install flake8==2.5.0
```

Note it also fails with `python:3.5`, however changing it to the following works fine:

```Dockerfile
FROM python:3.4
RUN pip install flake8==2.5.1 && pip install flake8==2.5.0
```

**Note:** I know installing flake8 then installing a lesser version isn't great, but that doesn't change the fact that this is a bug. The problem is only exhibited on overlay, and not any other storage driver I've tried.

Build output on overlay:

```
➜  overlaybug  docker build --pull --no-cache  -t overlaybug .
Sending build context to Docker daemon 8.704 kB
Step 1 : FROM python:3.4
3.4: Pulling from library/python
523ef1d23f22: Pull complete
140f9bdfeb97: Pull complete
5c63804eac90: Pull complete
ce2b29af7753: Pull complete
5c2bdca41b86: Pull complete
b48f4076b06d: Pull complete
d6788afe8670: Pull complete
a81a1086b672: Pull complete
15b1f796b9f0: Pull complete
1efcb21adee7: Pull complete
d1dcef8ab76f: Pull complete
dd40266492e1: Pull complete
285252a442bf: Pull complete
Digest: sha256:19e0ba3b85f69233ab0d06954a58afa2672f659c6cb9bf86807d292c417a8dea
Status: Downloaded newer image for python:3.4
 ---> 285252a442bf
Step 2 : RUN pip install flake8==2.5.1
 ---> Running in 945cdf613f1c
Collecting flake8==2.5.1
  Downloading flake8-2.5.1-py2.py3-none-any.whl
Collecting pyflakes<1.1,>=0.8.1 (from flake8==2.5.1)
  Downloading pyflakes-1.0.0-py2.py3-none-any.whl (152kB)
Collecting pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 (from flake8==2.5.1)
  Downloading pep8-1.5.7-py2.py3-none-any.whl
Collecting mccabe<0.4,>=0.2.1 (from flake8==2.5.1)
  Downloading mccabe-0.3.1-py2.py3-none-any.whl
Installing collected packages: pyflakes, pep8, mccabe, flake8
Successfully installed flake8-2.5.1 mccabe-0.3.1 pep8-1.5.7 pyflakes-1.0.0
 ---> 25d407bf5a85
Removing intermediate container 945cdf613f1c
Step 3 : RUN pip install flake8==2.5.0
 ---> Running in 228cd950e051
Collecting flake8==2.5.0
  Downloading flake8-2.5.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): mccabe<0.4,>=0.2.1 in /usr/local/lib/python3.4/site-packages (from flake8==2.5.0)
Requirement already satisfied (use --upgrade to upgrade): pyflakes<1.1,>=0.8.1 in /usr/local/lib/python3.4/site-packages (from flake8==2.5.0)
Requirement already satisfied (use --upgrade to upgrade): pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 in /usr/local/lib/python3.4/site-packages (from flake8==2.5.0)
Installing collected packages: flake8
  Found existing installation: flake8 2.5.1
    Uninstalling flake8-2.5.1:
      Successfully uninstalled flake8-2.5.1
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/shutil.py", line 424, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'flake8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/lib/python3.4/site-packages/pip/req/req_set.py", line 657, in install
    requirement.commit_uninstall()
  File "/usr/local/lib/python3.4/site-packages/pip/req/req_install.py", line 729, in commit_uninstall
    self.uninstalled.commit()
  File "/usr/local/lib/python3.4/site-packages/pip/req/req_uninstall.py", line 152, in commit
    rmtree(self.save_dir)
  File "/usr/local/lib/python3.4/site-packages/pip/_vendor/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.4/site-packages/pip/_vendor/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.4/site-packages/pip/_vendor/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.4/site-packages/pip/_vendor/six.py", line 659, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/pip/_vendor/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.4/site-packages/pip/utils/__init__.py", line 90, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/local/lib/python3.4/shutil.py", line 468, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/lib/python3.4/shutil.py", line 406, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/lib/python3.4/shutil.py", line 406, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/lib/python3.4/shutil.py", line 406, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/lib/python3.4/shutil.py", line 426, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/lib/python3.4/site-packages/pip/utils/__init__.py", line 98, in rmtree_errorhandler
    if os.stat(path).st_mode & stat.S_IREAD:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-7imwu3vj-uninstall/usr/local/bin/flake8'
The command '/bin/sh -c pip install flake8==2.5.0' returned a non-zero code: 2
```

docker info:
```
➜  overlaybug  docker info
Containers: 16
Images: 37
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: overlaytest
ID: 4WVC:34GK:NLWL:3LFL:QIGK:J6LD:YZL5:DQ47:WL2J:XJRX:6MCZ:DQ6Z
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 20
 System Time: 2016-01-12T16:47:52.96032768Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

docker version:

```
➜  overlaybug  docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Sat Nov 21 00:49:19 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

created via:
```
docker-machine create --driver virtualbox --virtualbox-disk-size 5000 --engine-storage-driver overlay overlaytest
```

This also fails on another VM:

```
$ docker info
Containers: 7
Images: 154
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 16
Total Memory: 29.44 GiB
Name: ip-10-53-6-118
ID: 63LD:WH3H:LW4Y:S5FQ:UY5J:YMZE:U4WO:QPGE:A7L2:2JJW:CK2M:WYRF
Username: clarifyiodeploy
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

$ uname -a
Linux ip-10-53-6-118 4.2.0-23-generic #28~14.04.1-Ubuntu SMP Thu Dec 31 13:40:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Ubuntu 14.04.2 LTS \n \l
```

No interesting dmesg or docker.log output was found.

**Comment by pkout** [comment] 2016-01-14 01:38
For those who don't know, until this gets merged, you can bypass this problem by running the pip upgrade command together with apt-get install to avoid file system layering. Something like this:

    RUN apt-get install python-pip && pip install --upgrade pip

**Comment by LK4D4** [comment] 2016-01-14 06:27
@xdays Patch probably will never be merged.
@pkout Thanks for a workaround!

**Comment by xdays** [comment] 2016-01-15 03:53
That's a pity

**Comment by thaJeztah** [comment] 2016-01-17 04:04
> That's a pity

Couldn't agree more!

**Comment by thaJeztah** [comment] 2016-01-17 04:06
ping @vbatts do you think Red Hat has some entries on getting @LK4D4's patch reviewed and merged? It really makes me sad that a (possible) fix is present, but not getting any attention whatsoever

**Comment by vbatts** [comment] 2016-01-17 05:06
Let me check

**Comment by vbatts** [comment] 2016-01-19 17:54
I have forwarded the patchset, but have not heard back yet.

**Comment by thaJeztah** [comment] 2016-01-19 19:35
Thanks @vbatts :heart:, @LK4D4 informed me that others have tried as well. It really surprises me that a driver that all distros are regarding the "way forward", is maintained so badly :cry: `</complain-mode>`

**Comment by FragLegs** [comment] 2016-01-27 16:19
See the above pull request (https://github.com/pypa/pip/pull/3425) for another workaround if @pkout 's method is not available to you. Feel free to install from my fork while pip is deciding whether to merge it.

**Comment by bufke** [comment] 2016-02-03 21:10
Any other workarounds for this? `RUN apt-get install python-pip && pip install --upgrade pip` doesn't help me. I just get the same FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-v5k9752y-uninstall/usr/local/bin/pip3.5'

**Comment by bufke** [comment] 2016-02-03 21:38
I found this as a workaround for me. Running it before doing anything else with pip. I'm using the latest python:3.5 image. `wget https://bootstrap.pypa.io/ez_setup.py -O - | python`

**Comment by krvss** [comment] 2016-02-12 23:48
Same problem on alpine 3.3 image, fix from @bufke worked - thanks a lot!

**Comment by dreamcat4** [comment] 2016-02-16 12:11
Hi,
i'm on ubuntu 16.04 xenial image, with python 2.7, @bufke's suggested fix didnt help

https://gist.github.com/amercader/4432ed33a73d510b4a08

**Comment by dreamcat4** [comment] 2016-02-16 13:59
It seems that a workaround patch on pip was rejected by pip team:

https://github.com/pypa/pip/pull/3425

**Comment by dreamcat4** [comment] 2016-02-16 14:05
So is overlayfs bug causing this issue fixed yet? When can I upgrade my host kernel etc? Currently on this host:

```sh
$ cat /etc/lsb-release  ; uname -a
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
Linux emachines-e520 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
id@emachines-e520:~/docker-images$ docker info
Containers: 66
Images: 947
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
CPUs: 2
Total Memory: 3.791 GiB
Name: emachines-e520
ID: NG2B:QLY4:W2SH:6FQF:FYGU:TVLX:3IQL:CQ4S:N5DL:CTND:52ZD:GCDH
```

**Comment by thaJeztah** [comment] 2016-02-16 14:13
@dreamcat4 see the discussion above; looks like the maintainer for overlayfs in the kernel is not responding, so we cannot get the patch merged upstream :cry:

**Comment by dreamcat4** [comment] 2016-02-16 14:23
@thaJeztah

https://github.com/docker/docker/issues/12327#issuecomment-148525515 ?

**Comment by thaJeztah** [comment] 2016-02-16 14:28
@dreamcat4 yup, the patch is there, but without the overlayfs maintainer responding/reviewing/accepting that patch, it won't be fixed (see the comments below the one you linked to)

**Comment by dreamcat4** [comment] 2016-02-16 14:30
@thaJeztah Well maybe he has same problem as me then, when I goto that page can't see anything:

![Where is the patch?](https://i.imgur.com/FSoAdtw.png)

**Comment by thaJeztah** [comment] 2016-02-16 14:34
@dreamcat4 hm, weird; it's visible in the overview (https://lkml.org/lkml/2015/10/9/) the follow-up e-mails do show up properly; https://lkml.org/lkml/2015/10/9/621, https://lkml.org/lkml/2015/10/9/622

**Comment by dreamcat4** [comment] 2016-02-16 14:37
OK thanks! Appreciate it. And @LK4D4 too (for being generally awesome / unassailable at these things).

https://lkml.org/lkml/2015/11/23/935

So now we need the direct email address of the maintainer of overlayfs, don't we? Try to get things moving again.

**Comment by thaJeztah** [comment] 2016-02-16 14:40
> So now we need the direct email address of the maintainer of overlayfs, don't we? Try to get things moving again.

I think in general, that's a big no-no. Would be great if it was picked up though

**Comment by vbatts** [comment] 2016-02-16 14:48
We're still trying to get traction upstream on issues like this.

**Comment by dreamcat4** [comment] 2016-02-16 15:12
OK guys.
Well lets cross our fingers for now and hope that it gets picked up again by the right expert / experts. It's bound to be just a natural miscommunication as these things happen / can get lost easily. I'm sure they will look into it once aware of such bug / patches / whatever.

Many thanks to everybody involved with making a solution for this longstanding bug.

**Comment by jgoclawski** [comment] 2016-02-22 12:52
What works for me as a workaround is to force installing the package that needs to be updates in the same layer as the update itself.

Example: using `python` as base image and wanting to upgrade pip. But pip has been installed in `python` base image, so it gives an error.
```
FROM python:3.4.4
RUN pip install pip==8.0.2
```
Solution:
```
FROM python:3.4.4
RUN pip install --ignore-installed pip && pip install pip==8.0.2
```

The same goes for dependent packages.

Example: installing ipython which upgrades setuptools. Although it looks like an install, not an update, internally ipython tries to update setuptools, causing an error.
```
FROM python:3.4.4
RUN pip install ipython
```
Solution:
```
FROM python:3.4.4
RUN pip install --ignore-installed setuptools && pip install ipython
```

It's just a workaround, but it's pretty simple and effective. Of course, as everyone else, I'd love to see the patch for overlayfs merged.

**Comment by jgmize** [comment] 2016-02-23 07:29
I think this may be related to https://bugzilla.kernel.org/show_bug.cgi?id=109611.

**Comment by steinnes** [comment] 2016-02-25 18:35
I had the same issue, my workaround was to simply install my own custom python packages in a virtualenvironment.  That way pip never needed to attempt to uninstall any dist packages and the problem was worked around.

Here's my recipe for anyone interested and using ubuntu:14.04 as a base.

Before:
```
FROM ubuntu:14.04
MAINTAINER Takumi <steinn@takumi.com>
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /app
RUN apt-get update && apt-get upgrade -y &&\
    apt-get install -y\
        curl wget htop make build-essential rsync cron anacron ntp python-dev python-pip git\
        python-software-properties software-properties-common libpq-dev libssl-dev libffi-dev\
        postgresql-client libzmq-dev libxml2-dev libxslt-dev libmagickwand-dev runit
RUN pip install requests virtualenv virtualenv-tools uwsgi==2.0.12
ADD requirements.txt /app/
ADD test-requirements.txt /app/
RUN pip install -r /app/test-requirements.txt
COPY . /app/
RUN pip install -r /app/test-requirements.txt
EXPOSE 5000
CMD uwsgi --yaml /app/uwsgi.yaml
```

After:
```
FROM ubuntu:14.04
MAINTAINER Takumi <steinn@takumi.com>
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /app
RUN apt-get update && apt-get upgrade -y &&\
    apt-get install -y\
        curl wget htop make build-essential rsync cron anacron ntp python-dev python-pip git\
        python-software-properties software-properties-common libpq-dev libssl-dev libffi-dev\
        postgresql-client libzmq-dev libxml2-dev libxslt-dev libmagickwand-dev runit
RUN pip install requests virtualenv virtualenv-tools
RUN virtualenv /venv && /venv/bin/pip install --upgrade pip && /venv/bin/pip install uwsgi==2.0.12
ADD requirements.txt /app/
ADD test-requirements.txt /app/
RUN /venv/bin/pip install -r /app/test-requirements.txt
COPY . /app/
RUN /venv/bin/pip install -r /app/test-requirements.txt
EXPOSE 5000
CMD /venv/bin/uwsgi --yaml /app/uwsgi.yaml
```


As you can see the file is slightly messier, but the upside is that it works with my CI system now (codeship).

**Comment by strohel** [comment] 2016-07-27 11:40
Hi all, I've recently upgraded **Linux kerne**l to **4.6.4** (back from 4.1) and the problem seems to be gone! Do you have the same observation?

**Comment by thaJeztah** [comment] 2016-07-27 11:50
According to https://bugzilla.kernel.org/show_bug.cgi?id=109611, this is fixed in kernel 4.5 https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=45d11738969633ec07ca35d75d486bf2d8918df6

ping @LK4D4 can you verify if that's what solves this issue?

**Comment by justincormack** [comment] 2016-09-19 22:20
Seems to be fixed in 4.4.21 too.

**Comment by mkocikowski** [comment] 2016-10-03 17:01
This problem doesn't seem to be specific to python / pip. Running overlay fs on ext4, kernel 4.4 (info below) a simple `COPY foo /foo` will fail with "no such file or directory" error (error in the last line of the shell output below):
```shell
root@host:~# uname -a
Linux host 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@host:~# docker info
Containers: 25
 Running: 5
 Paused: 0
 Stopped: 20
Images: 28
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: host
ID: SMFL:O7UP:7O4O:RVSD:QIQ2:FMX5:EVF5:UY74:336S:3QWI:DSEU:2HME
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
root@host:~# ls
Dockerfile  foo
root@host:~# cat Dockerfile
FROM alpine
COPY foo /foo
root@host:~# docker build .
Sending build context to Docker daemon  21.5 kB
Step 1 : FROM alpine
 ---> ee4603260daa
Step 2 : COPY foo /foo
stat /var/lib/docker/overlay/78c71862cccbd03b4a5be0f44e21753c7fee96ecc37f6e8048497d6f14141ee1/merged/foo: no such file or directory
root@host:~#
```

**Comment by thaJeztah** [comment] 2016-10-10 11:27
### This issue is resolved in recent kernels

This issue is resolved in recent kernels; if possible, upgrade your kernel to a version that includes this fix, or contact your OS vendor to make sure they carry the fix that resolves this. For more information, read the comments above; https://github.com/docker/docker/issues/12327#issuecomment-235562816, and https://github.com/docker/docker/issues/12327#issuecomment-248145317.


**Note that this is _not_ a bug in Docker, so please don't comment that you're still having this on docker version x.y.z.**

**Closed by thaJeztah** 2016-10-10 11:27 UTC
Labels: area/kernel, area/storage/overlay, kind/bug, version/1.5
