### ISSUE TITLE
running multiple commands using docker exec api

### ISSUE THREAD

**Issue by abilash222** [docker/docker#21207] opened 2016-03-15 08:26 UTC
i am not able to use multiple commands in the docker exec api. it allows only single command to be executed.
Any solution for this.

i need to do something like below
curl -X POST -H "Content-Type: application/json" -d '{"AttachStdin": false, "AttachStdout": true, "AttachStderr": true, "Tty": false,"Cmd": ["cd /user/home && sh run.sh"]}' http://localhost:2375/containers/id/exec1

**Output of `docker version`:**

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
Images: 28
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 15.56 GiB
Name: abilash-1425
ID: 74TN:CKNP:KICQ:YKPX:URM7:VED4:XOEH:4LRZ:FYF7:PK5B:KFOT:7DNW
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
cd: cannot access : No such file or directory

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-03-15 09:16
Perhaps try

    ["sh", "-c", "cd /user/home && run.sh"]

Or make sure the `run.sh` is executable, and do 

     ["sh", "-c", "/user/home/run.sh"]


However, keep in mind that the issue tracker is not a general support forum, but for reporting bugs and feature requests. Since this is not a bug report, I'll close this issue. Please use one of the following to ask your question;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

**Closed by thaJeztah** 2016-03-15 09:16 UTC
