### ISSUE TITLE
overlayfs and user namespaces don't work together

### ISSUE THREAD

**Issue by gomatteo** [docker/docker#21935] opened 2016-04-11 18:35 UTC
I'm unable to get overlay and user namespace working together.

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-0.bpo.1-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.755 GiB
Name: nuc
ID: JDFU:S4IS:C6II:ECQZ:UQOR:4GEF:PCFA:HGPM:AEKZ:QX65:Y7LU:PY4M
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical, debian jessie amd64

**Steps to reproduce the issue:**

1. Enable overlay and user namespace support: ```/usr/bin/docker daemon --userns-remap=default --storage-driver=overlay -H fd://```
2. Build this Dockerfile:
```
FROM alpine:latest

RUN apk add --update git
RUN git clone --depth 1 --branch=v1.0.1 https://github.com/Yelp/dumb-init/ tmp/dumb-init
RUN rm -rf tmp/dumb-init
```

**Describe the results you received:**
A lot of files can't be deleted:
```
Step 4 : RUN rm -rf tmp/dumb-init
 ---> Running in b0a3a5431c2e
rm: can't remove 'tmp/dumb-init/tests/lib': Operation not permitted
rm: can't remove 'tmp/dumb-init/tests': Directory not empty
rm: can't remove 'tmp/dumb-init/debian/source': Operation not permitted
rm: can't remove 'tmp/dumb-init/debian': Directory not empty
rm: can't remove 'tmp/dumb-init/.git/hooks': Operation not permitted
rm: can't remove 'tmp/dumb-init/.git/refs': Operation not permitted
rm: can't remove 'tmp/dumb-init/.git/logs': Operation not permitted
rm: can't remove 'tmp/dumb-init/.git/objects/89': Operation not permitted
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens only with user namespace and overlay.

- userns-remap and overlay: don't work
- userns-remap and devicemapper: work
- no userns-remap, overlay: work

```
matteo@nuc:~$ sudo ls -la /var/lib/docker/1345184.1345184
totale 36
drwx------  9 1345184 1345184 4096 apr 11 20:03 .
drwx-----x  4 root    root    4096 apr 11 20:03 ..
drwx------  5 1345184 1345184 4096 apr 11 20:19 containers
drwx------  3 root    root    4096 apr 11 20:03 image
drwxr-x---  3 root    root    4096 apr 11 20:03 network
drwx------ 15 1345184 1345184 4096 apr 11 20:19 overlay
drwx------  2 1345184 1345184 4096 apr 11 20:19 tmp
drwx------  2 root    root    4096 apr 11 20:03 trust
drwx------  2 1345184 1345184 4096 apr 11 20:03 volumes
```

**Comment by runcom** [comment] 2016-04-11 20:49
This may be a dupe of https://github.com/docker/docker/issues/18151 where copy up fails to create the special char device, ping @estesp

**Comment by HackToday** [comment] 2016-04-12 03:17
according to comment in #18151, it seems it works in ubuntu, and I tried locally, it works in my ubuntu environment.

```
ubuntu@workone:~$ sudo docker build .
Sending build context to Docker daemon 278.9 MB
Step 1 : FROM alpine:latest
latest: Pulling from library/alpine
420890c9e918: Pull complete 
Digest: sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0
Status: Downloaded newer image for alpine:latest
 ---> d7a513a663c1
Step 2 : RUN apk add --update git
 ---> Running in 6bc0275326cd
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/7) Installing openssl (1.0.2g-r0)
(2/7) Installing ca-certificates (20160104-r2)
(3/7) Installing libssh2 (1.6.0-r1)
(4/7) Installing curl (7.47.0-r0)
(5/7) Installing expat (2.1.0-r2)
(6/7) Installing pcre (8.38-r0)
(7/7) Installing git (2.6.6-r0)
Executing busybox-1.24.1-r7.trigger
Executing ca-certificates-20160104-r2.trigger
OK: 22 MiB in 18 packages
 ---> 83af4e941914
Removing intermediate container 6bc0275326cd
Step 3 : RUN git clone --depth 1 --branch=v1.0.1 https://github.com/Yelp/dumb-init/ tmp/dumb-init
 ---> Running in 4c2e7d974cab
Cloning into 'tmp/dumb-init'...
Note: checking out '4f67cf84e5c5097893a8bf6cbe98ceff5ab8d028'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

 ---> e74dd3a4e86b
Removing intermediate container 4c2e7d974cab
Step 4 : RUN rm -rf tmp/dumb-init
 ---> Running in b32afdd68eb3
 ---> 4f6c5abcba53
Removing intermediate container b32afdd68eb3
Successfully built 4f6c5abcba53
ubuntu@workone:~$ sudo docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.11.0-rc3
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.19.0-58-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: workone
ID: PJ4B:5XJT:QCLI:KI4Y:6ZFT:HNJQ:KIUH:ZTMH:QLEC:DR3M:6XRH:2BLY
Docker Root Dir: /var/lib/docker/165536.165536
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Comment by runcom** [comment] 2016-04-12 07:50
seems like trusty is carrying some overlay patches to make this work https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/trusty/commit/?id=639277fc549d55520a186ea69bd0283926cb5aee

**Comment by HackToday** [comment] 2016-04-12 09:04
maybe,  BTW, as overlay need kernel >= 3.18 for ubuntu 14.04(trusty) you need update kernels, I update that kernel with this `sudo apt-get install -y --install-recommends linux-generic-lts-vivid`

**Comment by runcom** [comment] 2016-04-12 09:10
not sure how what you're writing helps cause the op is running kernel 4.4.0. Right now this specific issue is being *fixed* only in Ubuntu kernels.

**Comment by HackToday** [comment] 2016-04-12 09:48
yes @runcom  I knew that :)  just told that trusty related kernel include that patch. (which means >=3.18 :0)  Hope not make others misunderstood.

**Comment by runcom** [comment] 2016-04-13 11:03
closing in favor of https://github.com/docker/docker/issues/18151 (since I tested this and my kernel patch fix this as well)

**Closed by runcom** 2016-04-13 11:03 UTC
Labels: area/storage/overlay
