### ISSUE TITLE
docker deploy return only supported with experimental daemon

### ISSUE THREAD

**Issue by RotemEmergi** [docker/docker#30585] opened 2017-01-31 11:03 UTC
Hi ,

I am using docker 1.13.0 
`sudo docker version`

> Client:
>  Version:      1.13.0
>  API version:  1.25
>  Go version:   go1.7.3
>  Git commit:   49bf474
>  Built:        Tue Jan 17 09:58:26 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.13.0
>  API version:  1.25 (minimum version 1.12)
>  Go version:   go1.7.3
>  Git commit:   49bf474
>  Built:        Tue Jan 17 09:58:26 2017
>  OS/Arch:      linux/amd64
>  Experimental: false

I am trying to deploy my bundle with this command `sudo docker deploy test.deb` .
And from the command I get only supported with experimental daemon .

when I run `docker network create --driver overlay db-net
docker service create --name rs1 --network db-net mongo:3.2 mongod --replSet "rs0"
docker service create --name rs2 --network db-net mongo:3.2 mongod --replSet "rs0"
docker service create --name rs3 --network db-net mongo:3.2 mongod --replSet "rs0"
docker service create --name rs --network db-net --restart-max-attempts 10 lucj/mongor`
it's work fine.

Best Regards

**Comment by aluzzardi** [comment] 2017-01-31 22:30
Could you include the content of your file?

**Comment by adambarthelson** [comment] 2017-02-01 18:07
+1

**Comment by cpuguy83** [comment] 2017-02-02 02:40
I think only deploy via compose file is supported in non-experimental?

**Comment by thaJeztah** [comment] 2017-02-02 02:56
Correct, `.dab` files / `--bundle-file` is still experimental only; `--compose-file` files are available in stable. You can enable experimental features through the `--experimental` flag on `dockerd` or through  `daemon.json` configuration file.

I'll close this issue because it's not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-02-02 02:56 UTC
Labels: area/bundles, version/1.13

**Comment by ORESoftware** [comment] 2017-02-18 03:51
Not sure if this directly relates to this issue, but I am searching for answers-

```
oleg@xps:~$ docker service logs helloworld
only supported with experimental daemon
```

I am looking for info on how to run the appropriate daemon, all I get when I run that command is the one line response which leaves much wanting.

**Comment by thaJeztah** [comment] 2017-02-18 04:59
@ORESoftware you can enable features by setting the `--experimental` flag on the docker daemon (`dockerd`), or (the recommended approach), by using a daemon.json configuration file; https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file.

If you have not yet have a daemon.json configuration file, create a new file at `/etc/docker/daemon.json` on the host that the daemon runs, and add the following content to enable experimental features;

```json
{"experimental":true}
```

Then restart the daemon (e.g. `sudo systemctl restart docker`)

**Comment by thaJeztah** [comment] 2017-02-18 04:59
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

**Comment by the1mills** [comment] 2017-02-18 09:26
Thanks yeah I will happily post there instead, appreciate the info will hopefully be making use of it soon!

**Comment by harshjv** [comment] 2017-02-20 18:52
@thaJeztah 

> `--compose-file` files are available in stable.

As of `Docker version 1.13.1, build 092cba3`, it still says `only supported with experimental daemon`, even for `--compose-file`

**Comment by thaJeztah** [comment] 2017-02-20 22:56
@harshjv are you using `docker deploy` or `docker stack deploy`? The `docker deploy` alias is indeed still experimental, because we're trying to reduce the number of top-level commands to only the most used commands, and it wasn't decided yet if `deploy` earned that right

**Comment by RotemEmergi** [comment] 2017-02-22 12:21
I pass to work with : `sudo docker stack deploy -c docker-compose-stack.yml rotem`..that work gr8 :)
