### ISSUE TITLE
Dead container's without name

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker#18628] opened 2015-12-14 07:20 UTC
I have two questions:

1. How can I create a container with ``Dead`` status?
   For my test purpose.
   
2. Is it possible make Dead container's Name equals its ID?
   Cuz when I saw some Dead containers before, it always without a name.

**Comment by thaJeztah** [comment] 2015-12-14 09:42
I don't think there's a way to *create* a dead container, afaik, it's usually the result of a container failing to be stopped/removed, and therefore given a "dead" state, so that it can be cleaned up in a later stage. This is also the reason "dead" containers may have no name.

e.g. See https://github.com/docker/docker/blob/83d0a8647037954fafe646a4261ccfb427ea8ff9/daemon/delete.go#L106 and https://github.com/docker/docker/blob/ec1002db58e8f84fc6d8306a3dd580e5fa88872c/daemon/list.go#L319

However; this is a question, not a bug or a feature request, so I'm going to close this issue. If you have additional questions, please use one of these channels; https://docs.docker.com/opensource/get-help/

**Closed by thaJeztah** 2015-12-14 09:42 UTC
