### ISSUE TITLE
Mounting a non-existent file creates a directory and mounts it

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [docker/docker#22857] opened 2016-05-20 16:25 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
```

Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 175
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 101
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: ZEUM:GEUJ:33UD:BTIU:7Y5L:VCP5:GH47:Z3M7:4E4O:W5AD:JVET:IUIN
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 17
 Goroutines: 42
 System Time: 2016-05-20T15:53:06.105472733Z
 EventsListeners: 0
Username: jonlpercsol
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.  docker run -v "nonexistent file name":/mountpoint image

**Describe the results you received:**

The mount point was created and a directory with the non-existent file name was created as well.

I really ran into this issue because I was attempting to mount a file in Windows on the C drive in my user directory.  However, the boot2docker vm shares the C drive as /c instead of /C.  So my files kept being shared as a directory instead of as a file with no errors or explanation, even when running with the -D debug mode.

**Describe the results you expected:**

I would have expected some kind of error or warning that the file did not exist, not just silent creation of empty directories on the file system.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment] 2016-05-20 16:39
This is expected behavior. Unfortunately it's a behavior that we can't really change.
Best thing to do is make sure a file does exist before running your container.

Closing since this won't be fixed.

**Closed by cpuguy83** 2016-05-20 16:39 UTC
Labels: version/1.11

**Comment by jonl-percsolutions-com** [comment] 2016-05-20 17:41
If it's expected behavior, it should be documented more fully.  There appears to be documentation under mounting a host directory, but nothing under mounting a host file.  So can we add a blurb under [Mount a host file as a data volume](https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-host-file-as-a-data-volume) that says, "If the file does not exist, it will be treated as a directory".
