### ISSUE TITLE
An extra dangling image

### ISSUE THREAD

**Issue by HuKeping** [docker/docker#20931] opened 2016-03-04 01:38 UTC
When pull a image with DCT enabled, there will be an extra image, for example
```
docker pull notary-distribution:5678/hi:latest
```
and then `docker images | grep  notary-distribution:5678/hi`, the output is like:
```
notary-distribution:5678/hi                                          latest              0cb40641836c        2 weeks ago         1.114 MB
notary-distribution:5678/hi                                          <none>              0cb40641836c        2 weeks ago         1.114 MB
```

Is this intended?

We have discussed this in https://github.com/docker/notary/issues/547 and maybe it should be an issue of daemon. 

Output of `docker version`:

```
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   187a2fb
 Built:        Tue Mar  1 10:08:26 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   187a2fb
 Built:        Tue Mar  1 10:08:26 2016
 OS/Arch:      linux/amd64
```

/cc @riyazdf @diogomonica

**Comment by thaJeztah** [comment] 2016-03-04 10:26
Hi @HuKeping, I think this is a duplicate (or very closely related to) https://github.com/docker/docker/issues/15508. Point here is that DCT does a pull by digest, which doesn't propagate the "TAG" column, but you'll see that `docker images --digests` shows the `DIGEST` column filled for that image.

**Comment by thaJeztah** [comment] 2016-03-07 07:55
Closing as duplicate of https://github.com/docker/docker/issues/15508

**Closed by thaJeztah** 2016-03-07 07:55 UTC
