### ISSUE TITLE
Docker 1.12.0-rc4 - service can't pull an image from ECR using amazon-ecr-credential-helper

### ISSUE THREAD

**Issue by eran-totango** [docker/docker#24732] opened 2016-07-17 11:55 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:54:54 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:54:54 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 9
 Running: 2
 Paused: 0
 Stopped: 7
Images: 12
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 72
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: active
 NodeID: 5y8rsdk7mqaj6pkwh12rbmbby
 IsManager: Yes
 Managers: 1
 Nodes: 5
 CACertHash: sha256:33748d487d9e8c8ec86a07e1f8f01c1aaabc636cbbd4931ae92e039ce316c2f2
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-91-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: swarm-manager-test-18547
ID: DHTM:UNMY:D4JI:6QH2:J3EH:K6A6:IJVB:DV7N:WKME:BRWM:KAX4:HBSB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
We're using AWS EC2.

**Steps to reproduce the issue:**
1. create a swarm cluster.
2. configure aws-ecr-credential-helper 
(with the guide here : https://github.com/awslabs/amazon-ecr-credential-helper)
3. Create/Update a service in the swarm cluster (i created it with the --registry-auto flag).

**Describe the results you received:**
the image isn't pulled to the server, and gives the following errors:
```
time="2016-07-17T10:51:44.323180477Z" level=error msg="Error trying v2 registry: error parsing HTTP 403 response body: invalid character 'Y
' looking for beginning of value: \"Your Authorization Token has expired. Please run 'aws ecr get-login' to fetch a new one.\""
time="2016-07-17T10:51:44.323354345Z" level=error msg="Attempting next endpoint for pull after error: error parsing HTTP 403 response body:
 invalid character 'Y' looking for beginning of value: \"Your Authorization Token has expired. Please run 'aws ecr get-login' to fetch a ne
w one.\""
time="2016-07-17T10:51:44.323441397Z" level=error msg="pulling image failed" error="error parsing HTTP 403 response body: invalid character
 'Y' looking for beginning of value: \"Your Authorization Token has expired. Please run 'aws ecr get-login' to fetch a new one.\"" module=t
askmanager task.id=0abqao8q14e0k8es8sh8c2dn8
```

**Describe the results you expected:**
The image would be pulled successfully to the server.

**Additional information you deem important (e.g. issue happens only occasionally):**
I don't think there's a problem with the credential helper because when i try to pull the image using "docker pull" command it does pull the image like it should,
and creates the relevant files (cache.json to store the authorization key and a log file).
The problem only occurs when i try the image needs to be pulled when creating a service/updating a service.

**Comment by thaJeztah** [comment] 2016-07-17 21:45
This is a duplicate of https://github.com/docker/docker/issues/24372, and should be resolved if you pass the `--registry-auth` on `docker service update` as well, see https://github.com/docker/docker/issues/24372#issuecomment-231213033

I'll close this issue, but feel free to continue the discussion

**Closed by thaJeztah** 2016-07-17 21:45 UTC
Labels: version/1.12
