### ISSUE TITLE
docker for batch jobs/small jobs

### ISSUE THREAD

**Issue by kartikjoshi07** [docker/docker#25759] opened 2016-08-16 12:07 UTC
Is there any use case where docker is used for batch jobs/small jobs, and that requires a scheduler queue to schedule them ?? In swarm if we don't have enough resources, it rejects the request, and doesn't queue it. If we want to schedule batch jobs and services together, we will need a scheduler queue then. is there any support for such use cases in swarm. I'm new to docker swarm. Please help :)

**Comment by thaJeztah** [comment] 2016-08-16 15:10
Please keep in mind that the GitHub issue tracker is not a support forum, but for tracking bugs and feature requests. For questions like this, consider using;

- https://forums.docker.com
- the #docker IRC channel
- StackOverflow


I'll try to answer your question; Swarm mode orchestration uses "desired state reconciliation"; from the SwarmKit readme (which drives the Swarm mode orchestration);

> SwarmKit constantly compares the desired state against the current cluster state and reconciles the two if necessary. For instance, if a node fails, SwarmKit reschedules its tasks onto a different node.

This means that, if you create a service (`service create ....`), but at the time you *create* the service, there's not enough resources to deploy the service in your Swarm, the Swarm orchestrator will keep on trying to deploy the service until it succeeds. This could mean it has to try until more nodes are added, or other services are stopped / removed. Similarly, if you (update the configuration of a service (for example, you change the image that a service uses to a different version), then Docker will remove containers that still use the "old" image, and deploy new container to take their place; if will keep doing so until all containers are replaced with new ones (with the right image). 

You can read about Swarm mode in Docker 1.12 in this section of the documentation; https://docs.docker.com/engine/swarm/

Hope this helps! I'll close this issue, because this is not a bug, but feel free to continue the conversation after I closed.

**Closed by thaJeztah** 2016-08-16 15:10 UTC
Labels: area/swarm, kind/question

**Comment by kartikjoshi07** [comment] 2016-08-16 18:17
Thanks a lot :)
I have read the documentation. So in the new version i.e 1.12, if we don't have enough resources(ie. RAM or CPU) to schedule a container (ie. a batch job or service) , it will wait in the scheduler queue at docker manager and the job at front of the queue will be scheduled, if any container job gets finished or removed ??  My concern is how does swarm manage the scheduling of jobs if there are not enough resources to schedule them if we statically allocate resources(mem or cores) to each container. 
:)

**Comment by thaJeztah** [comment] 2016-08-16 22:14
If there's no resources available, there's not much Swarm can do, other than wait for resources to become available. In that case, more resources (nodes) need to be added to the swarm (which is really simple with swarm mode; just install docker engine, and run `docker swarm join --token=<join token as issued by a manager>`
