### ISSUE TITLE
unable to see folder files in volume mounted from windows host

### ISSUE THREAD

**Issue by calebx** [docker/docker#18419] opened 2015-12-04 02:48 UTC
uname -a
``` MINGW64_NT-10.0 DESKTOP-GCN3BNN 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys ```

docker --version
``` Docker version 1.9.1, build a34a1d5 ```

docker info
```
Images: 37
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: B6NL:OODO:BSAB:3V65:YHM6:GMXN:RPST:FPYP:RY7X:AXHW:ORU4:IBJP
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 20
 System Time: 2015-12-04T02:39:00.592315776Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

and my pc os is windows 10, D: driver is NTFS

### Steps to Reproduce:
in powershell run by as admin
``` PS D:\code> docker run --privileged -it --rm --name db --volume-driver=flocker -v /d/code:/code ubuntu:14.04 /bin/bash ```
and 
`` cd code & ls ```

i have many files in this folder in host, while in docker container's bash ls command result.
only got the folder name, while nothing in it.

i have tried:
without ``` --privileged ``` 
without ``` --volume-driver=flocker ``` 
change host folder to ``` //d/code ```, ``` //d ```, or some external hard disk.

some file or folder are able to read, some are not.

### Expected:
i need to load all files like bash in windows does.

### Question
need i install some additional driver? or plugins?

**Comment by cpuguy83** [comment] 2015-12-04 03:56
This is because your `/d` is not going to be mounted by boot2docker, which is running in a VM.
You are seeing the contents of `/d/code` on the VM, which is probably nothing unless you manually added stuff there.

**Comment by thaJeztah** [comment] 2015-12-04 14:50
Yes, this is because, by default, boot2docker only shares the "users" directory with Windows. You can find more information about that, and instructions on how to add additional directories, here: https://github.com/boot2docker/boot2docker#virtualbox-guest-additions

Alternatively, make sure the `code` directory is in a subdirectory of `C:\Users`, and it should work out of the box

I'm going to close this issue, because it's not a bug, but feel free to comment here after I've closed.

Thanks for reporting!

**Closed by thaJeztah** 2015-12-04 14:50 UTC
