### ISSUE TITLE
GELF logging driver saturates CPU for a loong time

### ISSUE THREAD

**Issue by bobrik** [docker/docker#19209] opened 2016-01-09 15:55 UTC
```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Sat Nov 21 00:49:19 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

My container does `fmt.Fprintf(os.Stdout, "howdy ho\n")` 10 million times. Gelf driver options look like this:

```
--log-driver=gelf --log-opt=gelf-address=udp://127.0.0.1:23010 --log-opt=gelf-tag=wtf
```

Endpoint does not respond, since nothing is running on port 23010.

* Just running my program in container and redirecting stdout to file: 22s — obviously good.
* Default log driver: 40s, CPU drops to zero after container exits — good-ish.
* Gelf log driver: 26s, CPU drops to zero after 5831s (!!!) — not good.

This makes docker pulls very sad. The more important thing: docker containers are slowing down too. I suspect that `fwrite()` to stdout blocks in containers, leading to code path blocking in programs.

cc @dqminh

**Comment by dqminh** [comment] 2016-01-15 18:20
So i looked at this. It's somewhat related to #19371

The problem in docker <= 1.9 is that we dont have a bounded buffer for logs, so application can write as fast as they can and then exits while the log driver cant keep up. #19731 makes it worse because it closed the udp connection, so logs were written to a closed connection and then flooded docker's own logging facility with errors.

In 1.10 things are a bit better, it has a bounded buffer for logs ( capped at 1MB, althought i would like it to be customizable as some applications might generate more logs than the daemon can send, and we want to minimize the blocking, while some might send very little and we can have a smaller buffer ). So application that sends too much will block, which i think is a more reasonable outcome.

ping @LK4D4 @aaronlehmann for opinions.

**Comment by bobrik** [comment] 2016-01-15 18:28
I'll add a benchmark with actually working gelf endpoint, things are pretty messy when it works too.

Good example: https://github.com/mesosphere/marathon/issues/2985 Another good example: I waited 30 minutes and `docker pull` did not print anything on a busy docker. Not sure if bound buffer alone can fix that.

I'll be happy to test master in docker machine with virtualbox/vmware driver, but can't find how to do it.

**Comment by bobrik** [comment] 2016-01-21 20:35
[TIL](http://stackoverflow.com/questions/4397195/udp-send-behaviour-after-connect) about errors on write to UDP socket.

This won't give any errors:

```
docker run -it --rm --log-driver gelf --log-opt gelf-address=udp://127.0.0.1:1234 alpine:3.3 /bin/sh -c 'date'
```

This will give one error:

```
docker run -it --rm --log-driver gelf --log-opt gelf-address=udp://127.0.0.1:1234 alpine:3.3 /bin/sh -c 'date && date'
```

**Comment by bobrik** [comment] 2016-01-22 21:29
Did some more testing with 1.10 (0b7e9ef910b91a0a8cb334db852ad143c4660155).

10 million messages written by the following script on `debian:jessie`:

```shell
#!/bin/bash -e

STARTED=$(date +%s)

for i in {1..1000000}; do
	echo OK
done

ELAPSED=$(($(date +%s) - $STARTED))

echo Done in $ELAPSED 1>&2
```

|driver     |real time|cpu time|max cpu usage|
|-----------|---------|--------|-------------|
|`json-file`|       4s|     10s|        ~200%|
|`gelf`     |      29s|     45s|        ~110%|
|`journald` |     987s|   7527s|        ~780%|

Crazy numbers are still there, so it's not errors that are making things terrible. With work from @dqminh merged I can optimistically expect `gelf` numbers to drop 40x (https://github.com/Graylog2/go-gelf/pull/2), making it at least comparable to `journald`.

Notes: 

* `json-file` cpu usage is not very accurate, but it's fast enough not to care about it.
* `journald` in my case was also saturated to 100%, it was sending data to syslog on the same box.
* `gelf` endpoint was listening on the same box: `nc -v -l -u -p 4343 > /dev/null`.

**Comment by bobrik** [comment] 2016-01-25 19:04
**UPDATE**: in previous version `journald` and `gelf` results were mixed up.

**Comment by thaJeztah** [comment] 2016-02-16 12:30
@dqminh I see https://github.com/Graylog2/go-gelf/pull/2 is merged; should we do a vendor-update?

**Comment by habelson** [comment] 2016-03-29 14:33
seeing this with 1.10.3 , the change form syslog driver to gelf driver has completely pegged our system. It is somewhat unusable in this state.

**Comment by jmreicha** [comment] 2016-06-09 05:18
Any update on this?  I'm hesitant to turn on the gelf driver in production on busy servers unless this is fixed now.

**Comment by AkihiroSuda** [comment] 2016-06-09 05:22
@jmreicha the issue is not yet fixed, but related things are under discussion: https://github.com/docker/docker/pull/23198

**Comment by dqminh** [comment] 2016-06-13 13:21
@jmreicha there're options to configure the gelf pipeline optimization (https://docs.docker.com/engine/admin/logging/overview/#gelf-options) i.e. gelf-compression-level and gelf-compression-type.

Disable the compression helps a lot if your collector is local or nearby.

**Comment by wkruse** [comment] 2016-06-16 10:57
After upgrade from Docker `1.8.3` to `1.10.3` `gelf` became **unusable**. A test with two machines (32 cores, 32 GB RAM, 2x10GE Network, SSD) writing 10 million messages on one machine:

```
seq 10000000 | parallel --jobs 0 -n0 echo '<some JSON message>';
```

And measuring the throughput on the other machine with:

```
pv -Wartl > /dev/null
```

driver | throughput
------------ | -------------
`gelf` | 700 /s
`json-file` | 28000 /s

To ship `json-file` logs to remote machine I was using [gliderlabs/logspout](https://github.com/gliderlabs/logspout).

**Comment by dqminh** [comment] 2016-06-16 11:58
> After upgrade from Docker 1.8.3 to 1.10.3 gelf became unusable.

What's the thoughput with gelf 1.8.3 that you get before ? Also can you compare CPU and memory usages going from 1.8.3 to 1.10.3 ?

json-file always perform better than gelf when it comes to benchmark like this.
Also there are many changes in the logging infrastructure of Docker coming from 1.8.3 to 1.10.3, which also includes the fixed buffer for logging which may make log flooding worse for driver that goes through the network compares to one that read/write locally ( from page cache ).

**Comment by cpuguy83** [comment] 2016-06-16 13:56
The docker side of the gelf driver is extremely simple, the issue must be in the vendored gelf package (and looking at it I can see at least one thing to fix).

The only tunable from the docker side seems to be disabling compression.

**Comment by cpuguy83** [comment] 2016-06-16 17:12
And doing some testing, the compression libs in go are just terribly slow. I would recommend disabling compression (default is enabled).

**Comment by cpuguy83** [comment] 2016-06-16 17:18
Closing this as there doesn't really seem to be anything actionable we can do. I couldn't really squeeze anything else out of the gelf package while trying to tune it.

I know we already have a separate issue discussing gzip performance (which is really a golang issue) here: #10181

**Closed by cpuguy83** 2016-06-16 17:18 UTC
Labels: area/logging, version/1.9

**Comment by wkruse** [comment] 2016-06-17 10:18
ping @mariussturm

**Comment by wkruse** [comment] 2016-06-17 10:31
@dqminh My `1.10.3` test didn't work with `1.8.3` and `1.9.1` due to #19371. I couldn't also disable compression as suggested by @cpuguy83 because the options were added in `1.11.0` (#19831). I'll switch to `logspout` for now and try again as soon as CoreOS with Docker `1.11` is available.

**Comment by sorenbs** [comment] 2016-12-12 16:48
As an outsider it's a little difficult to keep up to date. This issue was opened a year ago and we are still seeing poor performance on the GELF driver. Does anyone have any insight into when we might expect a resolution?

As an aside - Would it make sense to add a warning to the docker docs?

Thanks

**Comment by cpuguy83** [comment] 2016-12-12 16:56
@sorenbs If you can enable debug mode on the docker daemon and collect pprof metrics we could analyze what issues you are seeing.

Docker's implementation is doing very little itself other than converting a `[]byte` to `string`, so I suspect any issue is likely happening within the gelf library.
Both gzip compression and json marshalling in the gelf library could be contributing to high CPU usage but it would be difficult to tell without profile data.

**Comment by mariussturm** [comment] 2016-12-12 16:57
@sorenbs different compression levels was added in 1.11, should be up to you how many cpu cycles you want to invest into logging. If bandwith is no issue you can disable it.

**Comment by sorenbs** [comment] 2016-12-12 17:58
Thanks @cpuguy83 and @mariussturm We are running docker on aws ECS. I don't really know what it would take to enable debug mode and collect pprof metrics. From this and the linked issues I was under the impression that there is a known issue with ELK driver.

I am running with compression level 1. Changing it to level 9 has a small negative impact as expected.
