### ISSUE TITLE
Error pulling down image: "archive/tar: invalid tar header"

### ISSUE THREAD

**Issue by icecrime** [docker/docker#15561] opened 2015-08-13 14:05 UTC
## Reproduced with Docker 1.7.1:

Client:

```
$ docker pull rentabiliweb/debian:wheezy
wheezy: Pulling from rentabiliweb/debian

d355eee16831: Extracting [=======>                                           ] 5.505 MB/37.1 MB
d355eee16831: Error pulling image (wheezy) from rentabiliweb/debian, endpoint: https://registry-1.docker.io/v1/, ApplyLayer exit status 1 stdout:  stderr: archd355eee16831: Error pulling image (wheezy) from rentabiliweb/debian, ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header 
Error pulling image (wheezy) from rentabiliweb/debian, ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header
```

Daemon:

```
INFO[0002] POST /v1.19/images/create?fromImage=rentabiliweb%2Fdebian%3Awheezy 
DEBU[0002] pulling image from host "docker.io" with remote name "rentabiliweb/debian" 
DEBU[0002] pinging registry endpoint https://index.docker.io/v1/ 
DEBU[0002] attempting v1 ping for registry endpoint https://index.docker.io/v1/ 
DEBU[0002] pulling v2 repository with local name "rentabiliweb/debian" 
DEBU[0002] pinging registry endpoint https://registry-1.docker.io/v2/ 
DEBU[0002] attempting v2 ping for registry endpoint https://registry-1.docker.io/v2/ 
DEBU[0002] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0002] Getting authorization for rentabiliweb/debian [pull] 
DEBU[0002] Pulling tag from V2 registry: "wheezy"       
DEBU[0002] [registry] Calling "GET" https://registry-1.docker.io/v2/rentabiliweb/debian/manifests/wheezy 
DEBU[0002] Getting bearer token with map[realm:https://auth.docker.io/token service:registry.docker.io] for  
DEBU[0002] hostDir: /etc/docker/certs.d/auth.docker.io  
DEBU[0003] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0003] provided manifest reference "wheezy" is not a digest: invalid checksum digest format 
DEBU[0003] Key check result: no graph                   
DEBU[0003] pulling blob "sha256:30f2abf52cb8d89f08138078f27df527b08c39757622297933bcba539aa73c72" to V1 img d355eee1683142cfcf8f541034626147e6e6f74a4a88c6c91481740685876c5c 
DEBU[0003] [registry] Calling "GET" https://registry-1.docker.io/v2/rentabiliweb/debian/blobs/sha256:30f2abf52cb8d89f08138078f27df527b08c39757622297933bcba539aa73c72 
DEBU[0003] Using cached token for                       
DEBU[0003] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0004] hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net 
DEBU[0029] Downloaded d355eee1683142cfcf8f541034626147e6e6f74a4a88c6c91481740685876c5c to tempfile /var/lib/docker/tmp/GetV2ImageBlob669921889 
DEBU[0029] Start untar layer                            
ERRO[0029] Error from V2 registry: ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header 
DEBU[0029] image does not exist on v2 registry, falling back to v1 
DEBU[0029] pulling v1 repository with local name "rentabiliweb/debian" 
DEBU[0029] [registry] Calling GET https://index.docker.io/v1/repositories/rentabiliweb/debian/images 
DEBU[0029] hostDir: /etc/docker/certs.d/index.docker.io 
DEBU[0030] Retrieving the tag list                      
DEBU[0030] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0030] Got status code 200 from https://registry-1.docker.io/v1/repositories/rentabiliweb/debian/tags 
DEBU[0030] Registering tags                             
DEBU[0030] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0031] Ancestry: [d355eee1683142cfcf8f541034626147e6e6f74a4a88c6c91481740685876c5c] 
DEBU[0031] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0031] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0032] hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net 
DEBU[0032] server doesn't support resume                
DEBU[0032] Start untar layer
```

Relevant error:

    ERRO[0029] Error from V2 registry: ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header 

## Reproduced with Docker 1.8.1:

Client:

```
docker pull rentabiliweb/debian:wheezy
wheezy: Pulling from rentabiliweb/debian

d355eee16831: Extracting [=======>                                           ] 5.505 MB/37.1 MB
d355eee16831: Error pulling image (wheezy) from docker.io/rentabiliweb/debian, endpoint: https://registry-1.docker.io/v1/, ApplyLayer exit status 1 stdout:  std355eee16831: Error pulling image (wheezy) from docker.io/rentabiliweb/debian, ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header 
Error pulling image (wheezy) from docker.io/rentabiliweb/debian, ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header
```

Daemon:

```
INFO[0002] POST /v1.20/images/create?fromImage=rentabiliweb%2Fdebian%3Awheezy 
DEBU[0002] Trying to pull rentabiliweb/debian from https://registry-1.docker.io v2 
DEBU[0003] Pulling tag from V2 registry: "wheezy"       
DEBU[0004] Key check result: no graph                   
DEBU[0004] pulling blob "sha256:30f2abf52cb8d89f08138078f27df527b08c39757622297933bcba539aa73c72" to d355eee1683142cfcf8f541034626147e6e6f74a4a88c6c91481740685876c5c 
DEBU[0031] Downloaded d355eee1683142cfcf8f541034626147e6e6f74a4a88c6c91481740685876c5c to tempfile /var/lib/docker/tmp/GetImageBlob473826855 
DEBU[0031] Start untar layer                            
DEBU[0032] Error trying v2 registry: ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header 
DEBU[0032] Trying to pull rentabiliweb/debian from https://index.docker.io v1 
DEBU[0032] hostDir: /etc/docker/certs.d/docker.io       
DEBU[0032] [registry] Calling GET https://index.docker.io/v1/repositories/rentabiliweb/debian/images 
ERRO[0032] error copying from layer download progress reader: download canceled 
DEBU[0032] Retrieving the tag list                      
DEBU[0033] Got status code 200 from https://registry-1.docker.io/v1/repositories/rentabiliweb/debian/tags/wheezy 
DEBU[0033] Registering tags                             
DEBU[0034] Ancestry: [d355eee1683142cfcf8f541034626147e6e6f74a4a88c6c91481740685876c5c] 
DEBU[0035] server doesn't support resume                
DEBU[0035] Start untar layer                            
DEBU[0039] Not continuing with error: Error pulling image (wheezy) from docker.io/rentabiliweb/debian, ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header
```

Relevant error:

    ERRO[0032] error copying from layer download progress reader: download canceled 

Ping @rockyluke! :kiss:

**Comment by rockyluke** [comment] 2015-08-14 10:15
I'll give you extra information : 

I'm using the last version (1.8.1) :

```bash
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

I build the image with it 

```bash
$ docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
rentabiliweb/debian   wheezy              c50be2831e9f        32 seconds ago      100.3 MB
```

Locally, the image is working 

```bash
$  docker run rentabiliweb/debian:wheezy echo OK 
OK
```

Thanks.

**Comment by rockyluke** [comment] 2015-08-27 15:00
I'm sorry to bother you with that issue, but our base image used to build all the other and actually 80% are broken ;-(

Thanks.

**Comment by vito** [comment] 2015-08-28 15:12
We've started seeing this too. Seems to happen after pushing an image that was `import`ed. After removing the local copy so `pull` doesn't no-op, all `pull`s fail.

**Comment by dmcgowan** [comment] 2015-09-01 22:52
@rockyluke I am trying to reproduce this case on the push side. Do you have specific instructions for how this image was first created before push. Can you also include kernel version and graph driver.

@vito if you have a reproducible case it will help as well

**Comment by dmcgowan** [comment] 2015-09-01 22:55
@stevenschlansker if you have this information it will help as well. I want to know if you can describe the contents of the directory which is being imported, also graph driver information. Thanks!

**Comment by stevenschlansker** [comment] 2015-09-01 23:02
This script is what we use to generate our base images, and it 100% fails on Docker 1.8.1, works OK on Docker 1.7.1.

Kernel vanilla 4.0.4, Ubuntu 14.04.3, overlay driver

https://gist.github.com/stevenschlansker/ced13e249fa648a81227

**Comment by vbatts** [comment] 2015-09-02 21:46
this is fixed by https://github.com/docker/docker/pull/15492 which is already cherry-picked for 1.8.2 ...

**Comment by dmcgowan** [comment] 2015-09-02 21:47
confirmed fixed in master and will be in 1.8.2.

The bad images which are failing on pull will need to be repushed before pulling will succeed.

**Closed by dmcgowan** 2015-09-02 21:47 UTC
Labels: group/distribution

**Comment by vbatts** [comment] 2015-09-02 21:48
the `tar -c . | docker import -` approach is including GNU @LongLink.

This also means that images pushed from this will need to be re-`docker import`'ed and re-pushed, once updated to docker 1.8.2

**Comment by vbatts** [comment] 2015-09-02 21:48
like @dmcgowan  said

**Comment by rockyluke** [comment] 2015-09-03 00:09
Thanks a lot !

**Comment by Sicily-F** [comment] 2021-04-12 14:47
Can I ask what operating system everyone is using? I'm using Windows and getting these errors

**Comment by thaJeztah** [comment] 2021-04-12 19:15
@Sicily-F this is a 6 year old ticket; Docker was not yet available for Windows back then, and the cause of this issue was fixed; if you're running into an issue, it's very likely unrelated to this one. If you think it's a big and have details that may help triage the issue, please open a new ticket instead

**Comment by Sicily-F** [comment] 2021-04-13 12:34
thank you

> @Sicily-F this is a 6 year old ticket; Docker was not yet available for Windows back then, and the cause of this issue was fixed; if you're running into an issue, it's very likely unrelated to this one. If you think it's a big and have details that may help triage the issue, please open a new ticket instead

thankyou, I have asked the question in the Docker forum
