### ISSUE TITLE
Error on Ubuntu 14.04: client is newer than server (client API version: 1.23, server API version: 1.21)

### ISSUE THREAD

**Issue by dj-hedgehog** [docker/docker#23761] opened 2016-06-20 11:22 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.21)
```

**Output of `docker info`:**

```
Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.21)```

**Additional environment details (AWS, VirtualBox, physical, etc.):** physical


**Describe the results you received:** I upgraded on a 14.04 Ubuntu host from Docker 1.9 to 1.11.2 by following https://docs.docker.com/engine/installation/linux/ubuntulinux/
I can't use any commands like `docker info` or `docker ps` because I always get:
`Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.21)``

While I got a lot of information on this error, none of the solutions could have been useful for my use-case.

What do I need to do?

**Comment by thaJeztah** [comment] 2016-06-28 04:29
I suspect that the old docker version is still installed somewhere, possibly in a different path (e.g. old version installed in `/usr/bin`, and the new version installed in `/usr/local/bin`). How did you install the previous version?

Probably best to uninstall (`apt-get purge docker-engine`), then find where the other version is installed, and remove it. After that, reinstall using the instructions you used.


I'm going to close this issue, because this is a support question, not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-06-28 04:29 UTC

**Comment by dj-hedgehog** [comment] 2016-06-28 12:23
Thanks for your response. In fact after cleaning all the remains of the old Docker installation I was good to go.
Lesson learned. Never let anyone hit `apt-get install docker`!

**Comment by thaJeztah** [comment] 2016-06-28 14:13
Good to hear it's resolved!
