### ISSUE TITLE
`docker run` fails on missing aufs layer

### ISSUE THREAD

**Issue by kevinjqiu** [docker/docker#22343] opened 2016-04-26 20:33 UTC
This is possibly alpine Linux related.

**Output of `docker version`:**

```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 5eaaa01
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 5eaaa01
OS/Arch (server): linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
Images: 145
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 161
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu precise (12.04.2 LTS)
CPUs: 4
Total Memory: 7.798 GiB
Name: prod-builds-18
ID: 3SKS:SQB3:HTKQ:4AVW:YHQ5:CX2X:MA5U:RAL5:RL6K:CML2:URQA:44GG
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine.

**Steps to reproduce the issue:**
1. docker pull on an image, all the layers successfully downloaded, but pull resulted in a failure:
```
docker pull dev-docker.points.com:80/mountebank
latest: Pulling from dev-docker.points.com:80/mountebank
1348eb573a47: Pull complete 
bb7044f479ac: Pull complete 
f8c187edf56a: Pull complete 
4d4dccb42bd7: Pull complete 
74d53083ab47: Pull complete 
4725f8ca753f: Pull complete 
a91ec41f9117: Pull complete 
65fac5d2c1a0: Pull complete 
Pulling repository dev-docker.points.com:80/mountebank
Error: image mountebank:latest not found
```
2. immediately re-issue the pull command, this time, the pull succeeded:
```
docker pull dev-docker.points.com:80/mountebank
latest: Pulling from dev-docker.points.com:80/mountebank
1348eb573a47: Already exists 
bb7044f479ac: Already exists 
f8c187edf56a: Already exists 
4d4dccb42bd7: Already exists 
74d53083ab47: Already exists 
4725f8ca753f: Already exists 
a91ec41f9117: Already exists 
65fac5d2c1a0: Already exists 
Digest: sha256:f7cdb7a48e6c797f4898407c1b177de62b65d6d0cf2818d4e1cfcf017b3c652a
Status: Downloaded newer image for dev-docker.points.com:80/mountebank:latest
```

3. create a container from the image by using `docker run ...`

**Describe the results you received:**
```
docker run dev-docker.points.com:80/mountebank
Error response from daemon: open /var/lib/docker/aufs/layers/65fac5d2c1a0537a7b171da39ac04010aa642861ec24c583d476926e53666017: no such file or directory
```

and checking `/var/lib/docker/aufs/layers/` folder, and indeed the said folder does not exist.

**Describe the results you expected:**
A container is created from the image and is running.

**Additional information you deem important (e.g. issue happens only occasionally):**
The mountebank docker image is from: https://hub.docker.com/r/kevinjqiu/mountebank/
It's built from an alpine linux base. On switching to a debian based image, the problem does not occur.

**Comment by HackToday** [comment] 2016-04-27 01:40
used ubuntu 14.04 seems ok

```
ubuntu@testdevstack:~/workplace/docker$ docker run -it  kevinjqiu/mountebank sh
/ # 
```

you use very old version docker, did you have logs from daemon when you run such container ?

**Comment by ztetfger** [comment] 2016-04-27 04:31
Aufs did not join the Linux distributions, check whether the kernel version support for aufs?

**Comment by thaJeztah** [comment] 2016-04-28 14:20
I'm not able to reproduce this either; do you also run into this if you use the image from docker hub? And are you able to reproduce this on the current release (1.11.1)? We don't do patch-releases for older versions, so even if there's a bug in 1.7.1, we won't fix that

**Comment by kevinjqiu** [comment] 2016-04-28 14:26
@thaJeztah I'm not able to reproduce this on newer version of docker.  Feel free to close it.

**Comment by thaJeztah** [comment] 2016-04-28 14:28
Thanks for testing! I'll close this

**Closed by thaJeztah** 2016-04-28 14:28 UTC
Labels: area/storage/aufs, status/more-info-needed

**Comment by feliperazeek** [comment] 2016-05-11 04:15
In this case this helps anyone, I was on docker `1.7.x`, upgraded to `1.11` and started getting this error. I removed the image, did a pull and things started working again. Might be worth a shot if you are stuck.

**Comment by harishkadamudi** [comment] 2016-09-07 08:55
I still see this issue in Ubuntu 16.04.1 LTS with docker version 1.12

**Comment by dottgonzo** [comment] 2016-09-15 08:28
+1: 
16.04.1 LTS 
Docker version 1.12.1, build 23cf638

**Comment by thaJeztah** [comment] 2016-09-15 09:15
@harishkadamudi @dottgonzo if you remove the image and pull it again, does that resolve the issue? Wondering if it has been a one-off
