### ISSUE TITLE
WORKDIR not using cache

### ISSUE THREAD

**Issue by gorazio** [docker/docker#30076] opened 2017-01-11 20:08 UTC
**Description**

**Steps to reproduce the issue:**
```
1.sudo apt install docker-engine=1.13.0~rc5-0~ubuntu-xenial
2. docker build -f Dockerfile .
```
**Describe the results you received:**
 
Step 6/9 : RUN chmod -R u=rX,go= /root/.ssh
 ---> Using cache
 ---> 76cb739a2e98
Step 7/9 : WORKDIR /app
 ---> e59d60cd1e1c

**Describe the results you expected:**

Step 6/9 : RUN chmod -R u=rX,go= /root/.ssh
 ---> Using cache
 ---> 76cb739a2e98
Step 7/9 : WORKDIR /app
 ---> Using cache
 ---> e59d60cd1e1c

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 00:55:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc5
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 00:55:26 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 2217
Server Version: 1.13.0-rc5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.57 GiB
Name: gorazio-Lenovo-Z50-70
ID: QA7H:ZWH5:KDQA:AW37:HXBI:TAXT:UBBZ:SILQ:SHKY:LS5E:NYIG:5VBE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Live Restore Enabled: false

```

in rc4 all works properly

**Comment by justincormack** [comment] 2017-01-11 20:09
This is already fixed in master and will be in rc6 today

**Comment by justincormack** [comment] 2017-01-11 20:10
Duplicate of https://github.com/docker/docker/issues/29950

**Closed by justincormack** 2017-01-11 20:10 UTC
Labels: area/builder, version/1.13
