### ISSUE TITLE
Failing to pull

### ISSUE THREAD

**Issue by deathtrix** [docker/docker#23366] opened 2016-06-08 07:47 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 115
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-8:9-521228-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.652 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.5 GB
 Metadata Space Used: 6.885 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-coreos-r1
Operating System: CoreOS 1010.5.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.856 GiB
Name: linux-013
ID: GBFU:WCZP:STEH:2XLU:XP25:ZDWM:IX6R:KIPM:N6S4:FQV7:NY4F:2CQX
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM. Kubernetes worker.

**Steps to reproduce the issue:**
1. docker pull test

**Describe the results you received:**
```
Using default tag: latest
Error response from daemon: Error parsing HTTP response: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"
```

**Describe the results you expected:**
To pull the image

**Additional information you deem important (e.g. issue happens only occasionally):**
1. It started happening about 2-3 weeks ago. Before I had no problems and I didn't change anything to the OS. So I suspect CoreOS updated docker and the faulty behaviour is due to the new docker version.
2. I tried the MTU=1500 fix suggested on other sites but still didn't work.

**Comment by HackToday** [comment] 2016-06-08 14:55
Also not sure if some other same as this, I found some set MTU to lower number like this one
https://github.com/docker/docker/issues/20628

**Comment by thaJeztah** [comment] 2016-06-08 15:21
Yes, it may take some testing to get the proper MTU value. However, this is not a bug, but a configuration issue, so I'll close this issue. But feel free to continue the discussion

**Closed by thaJeztah** 2016-06-08 15:21 UTC
Labels: version/1.10

**Comment by deathtrix** [comment] 2016-06-09 06:42
I have just one question then: why did it work before, and then, not changing anything it stopped working? How is this a configuration issue?

**Comment by thaJeztah** [comment] 2016-06-09 08:47
@deathtrix older versions tried to "guess" the MTU by looking at the network interface, but this caused issues if a machine had multiple interfaces

**Comment by deathtrix** [comment] 2016-06-27 14:21
@thaJeztah ok. So, taking into account that on out setup the MTU is set by flannel (we use kubernetes) and docker takes it as a parameter, what should I do?
