### ISSUE TITLE
Can not import Docker code, fails to find autogen

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#11699] opened 2015-03-24 07:40 UTC
In other code outside Docker I import "github.com/docker/docker" and now with master that no longer works.  There is apparently some auto-generated code needed (that doesn't use go generate?).  The error I get is

```
utils/utils.go:22:2: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/usr/local/go/src/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/go/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/docker/autogen/dockerversion
```

**Comment by ibuildthecloud** [comment] 2015-03-24 07:42
I've worked around this with terrible hacks that make me feel sad inside.

**Comment by ibuildthecloud** [comment] 2015-03-24 08:08
Apparently this is a dup of #10922, but that issue is closed.  I don't think it should be.  This seems like odd behavior to have to run a separate random bash script after `go get`.

**Comment by thaJeztah** [comment] 2015-03-24 17:52
I think I saw some discussion on another issue regarding auto generated code. But I forgot which one (lots of activity because of the Docker Birthday Party)

I don't even know if it is related, but do remember @tianon was taking part in the discussion.

(Apologies if this is unrelated)

**Comment by pwaller** [comment] 2015-04-23 09:28
I'd like to comment that `.go-autogen` is a surprising place to put this code, it means it doesn't show up with `ag` or `grep`, so it's hard to find! I spent quite a while wondering where the heck dockerversion was generated from. [Why hide all of these files](https://github.com/docker/docker/tree/master/hack/make) and make them invisible to a command line search?

**Comment by tianon** [comment] 2015-04-24 17:29
They show up alright here, with both `git grep` and `grep`:
```console
$ git grep -n 'autogen/dockerversion'
api/client/hijack.go:18:	"github.com/docker/docker/autogen/dockerversion"
api/client/utils.go:23:	"github.com/docker/docker/autogen/dockerversion"
api/client/version.go:9:	"github.com/docker/docker/autogen/dockerversion"
api/server/server.go:23:	"github.com/docker/docker/autogen/dockerversion"
daemon/daemon.go:21:	"github.com/docker/docker/autogen/dockerversion"
daemon/info.go:10:	"github.com/docker/docker/autogen/dockerversion"
docker/daemon.go:13:	"github.com/docker/docker/autogen/dockerversion"
docker/docker.go:13:	"github.com/docker/docker/autogen/dockerversion"
graph/graph.go:19:	"github.com/docker/docker/autogen/dockerversion"
graph/graph_test.go:12:	"github.com/docker/docker/autogen/dockerversion"
hack/make/.go-autogen:5:mkdir -p autogen/dockerversion
hack/make/.go-autogen:6:cat > autogen/dockerversion/dockerversion.go <<EOF
integration-cli/docker_api_version_test.go:7:	"github.com/docker/docker/autogen/dockerversion"
registry/httpfactory.go:6:	"github.com/docker/docker/autogen/dockerversion"
utils/utils.go:18:	"github.com/docker/docker/autogen/dockerversion"
```
```console
$ grep -rn 'autogen/dockerversion'
integration-cli/docker_api_version_test.go:7:	"github.com/docker/docker/autogen/dockerversion"
graph/graph_test.go:12:	"github.com/docker/docker/autogen/dockerversion"
graph/graph.go:19:	"github.com/docker/docker/autogen/dockerversion"
utils/utils.go:18:	"github.com/docker/docker/autogen/dockerversion"
Binary file bundles/1.5.0-dev/binary/docker-1.5.0-dev matches
docker/daemon.go:13:	"github.com/docker/docker/autogen/dockerversion"
docker/docker.go:13:	"github.com/docker/docker/autogen/dockerversion"
hack/make/.go-autogen:5:mkdir -p autogen/dockerversion
hack/make/.go-autogen:6:cat > autogen/dockerversion/dockerversion.go <<EOF
registry/httpfactory.go:6:	"github.com/docker/docker/autogen/dockerversion"
daemon/info.go:10:	"github.com/docker/docker/autogen/dockerversion"
daemon/daemon.go:21:	"github.com/docker/docker/autogen/dockerversion"
api/server/server.go:23:	"github.com/docker/docker/autogen/dockerversion"
api/client/utils.go:23:	"github.com/docker/docker/autogen/dockerversion"
api/client/version.go:9:	"github.com/docker/docker/autogen/dockerversion"
api/client/hijack.go:18:	"github.com/docker/docker/autogen/dockerversion"
```

I'm not familiar with `ag`, but I'd definitely be surprised to learn of a "code/file search" tool that doesn't also search "dotfiles".

Even GitHub's search pulls up `.go-autogen` as the first result for `dockerversion`: https://github.com/docker/docker/search?utf8=%E2%9C%93&q=dockerversion

**Comment by ibuildthecloud** [comment] 2015-04-25 14:47
@tianon Any help with this issue would be greatly appreciated.  I maintain many programs that import Dockers code.  The problem with the autogen is that it breaks the godep flow.  I'm forced to fork Docker so that I can commit the auto generated code.  But then that git commit is in my fork and not the upstream.   This then make godep restore not work.

I have not had time to look into exactly what changed, I just k os previously importing docker code went fine and now I have to do a lot of manual steps.

**Comment by pwaller** [comment] 2015-04-28 07:34
Hm, that's unfortunate, it seems that ag is the only one which doesn't search hidden files out of grep, ack and ag. Still, why hide it? I didn't think to check for hidden files, since I didn't imagine one would want want to hide it :)

On another note, my use case for importing that I'm struggling with in particular right now is `github.com/docker/docker/opts`, which I want to import so that I can mimick docker's option parsing. Does there exist a good option for doing this? I'm writing my own orchestrator which needs to accept arguments as though to `docker run`, except I'm using `go-dockerclient` rather than invoking `/usr/bin/docker`.

It seems that `opts` uses `utils.ValidateEnv`, and utils imports autoversion for the function for `utils.DockerInitPath` and `utils.isValidDockerInitPath`. This makes it not go-get-able. Could those functions be moved out of `utils`, or into a sub-package? Or vice-versa with `ValidateEnv`..

**Comment by pwaller** [comment] 2015-04-28 08:35
Aha! please ignore my last message. It seems that this was already fixed in 4b9fe9c298c8778855c1d14e978c791496dd7c42.

**Comment by aluzzardi** [comment] 2015-05-07 21:10
+1

**Comment by aluzzardi** [comment] 2015-05-07 21:30
@tianon it can be reproduced with samalba/dockerclient#103

After importing `github.com/docker/docker/pkg/units` go test fails with:
```
go build github.com/docker/docker/autogen/dockerversion: no buildable Go source files in
FAIL	github.com/samalba/dockerclient [build failed]
```

**Comment by tianon** [comment] 2015-05-09 23:22
`dockerclient`'s import problem is fixed by https://github.com/samalba/dockerclient/pull/104 :+1:

**Comment by ibuildthecloud** [comment] 2015-05-10 19:09
@tianon isn't this a workaround just for samalba/dockerclient?  I have code that imports something from docker that has a transient dependency on util.

**Comment by tianon** [comment] 2015-05-26 19:19
@ibuildthecloud no, dockerclient was violating the "`pkg/` agreement" by importing `docker/docker/utils` directly -- only `pkg/` is considered safe for external use.

If any `pkg/` import leads to errors about `autogen`, that's definitely a bug.  If anything else does, that's the hazard you get to deal with by using Docker's internals which haven't been explicitly ported to be generally acceptable for external use.

**Comment by pwaller** [comment] 2015-05-26 21:22
Thanks for the clarification @tianon :)

**Comment by vdemeester** [comment] 2015-09-03 07:18
On the `autogen` notes, at least for `autogen/dockerversion`, there could be a way to not have this by using this on build https://www.atatus.com/blog/golang-auto-build-versioning/.

**Comment by tianon** [comment] 2015-09-04 00:26
We used to use `-X` actually, but because of `gccgo` not supporting it, we had to switch to autogenerated code. :disappointed:

**Comment by erikh** [comment] 2015-10-08 07:29
what about doing this, instead, as a placeholder? https://gist.github.com/erikh/e6f0c5e4b7b6c2483d52

you could leave this in the repository so it's still go-gettable, but then overwrite it during the build. how does this sound?

**Comment by ibuildthecloud** [comment] 2015-10-19 09:11
@erikh +1

I know people *shouldn't* import non-pkg code but I don't like that effectively docker makes it not possible.  If people want to import stuff at their own risk, just let them.

**Comment by cpuguy83** [comment] 2015-10-19 12:59
ping @tianon

**Comment by calavera** [comment] 2016-03-03 23:01
#17350 fixed this issue.

**Closed by calavera** 2016-03-03 23:01 UTC

**Comment by erikh** [comment] 2016-03-03 23:54
I think this was reverted by @jfrazelle in another ticket, but I'll 
verify later this is still an issue.
