### ISSUE TITLE
Allow for containers to mount files or paths from sibling containers

### ISSUE THREAD

**Issue by atrauzzi** [docker/docker#20708] opened 2016-02-26 00:34 UTC
If I'm running a container which has the following file/path of interest:

`/resources/someservice.config`

And I want to mount it to a path inside another container:

`/etc/service/config`

I haven't been able to find a clear indication if Docker is capable of doing something like this.  While there is the ability to mount all volumes from another container, there doesn't appear to be any way to map them individually.  It's all-or-nothing.

I'd love to see the ability to simply have two containers running on the same host be able to map files from each other.

**Comment by thaJeztah** [comment] 2016-02-26 00:58
Does this work for your use case?

```
docker run -v sharedvol:/resources --name containera foobar

docker run -v sharedvol:/somewhere --name containerb someimage
```

**Comment by thaJeztah** [comment] 2016-02-26 01:01
However, this is a support question, not a bug or feature request, and GitHub is not intended as a support forum; for these kind of questions, please use;

- forums.docker.com
- the docker-user Google group
- the #docker IRC channel on freenode
- StackOverflow

I'm going to close this issue, but feel free to continue the discussion

**Closed by thaJeztah** 2016-02-26 01:01 UTC

**Comment by atrauzzi** [comment] 2016-02-26 02:12
Possibly related to this at this point: https://github.com/docker/compose/issues/424

I'm able to create named volumes for directories, but not files.

**Comment by atrauzzi** [comment] 2016-02-26 13:05
Also, @thaJeztah, after trying your solution, it doesn't seem to work.  What ends up happening is the filesystem gets blanked out on the source (`containera`).  Not shared as a named volume.

I don't think this is a "support question" anymore.

**Comment by thaJeztah** [comment] 2016-02-26 13:09
> I'm able to create named volumes for directories, but not files.

This may be something that we can add to the documentation

> What ends up happening is the filesystem gets blanked out on the source (container)

The files that are present inside the container on that location should be copied to the volume, the first time the container is started; what version of docker are you running, and on what platform?

**Comment by atrauzzi** [comment] 2016-02-26 13:11
![image](https://cloud.githubusercontent.com/assets/115199/13353139/e4f57788-dc57-11e5-8352-c3f17b99ad7f.png)

![image](https://cloud.githubusercontent.com/assets/115199/13353164/025aa47e-dc58-11e5-88f9-30166e9b7d55.png)

In the most general of terms, I'd like one container to contain files that can be used by another.  But I have to be able to bind them on a file-by-file basis.  Not entire directories at a time.

**Comment by thaJeztah** [comment] 2016-02-26 13:22
You need to update to update to Docker 1.10 in order to have named volumes be propagated with the containers' content;

Build this dockerfile:

```Dockerfile
FROM ubuntu
RUN mkdir -p /config/ && echo "HELLO WORLD" > /config/config-file
```

```bash
$ docker build -t foo .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM ubuntu
 ---> 06ab2de020f4
Step 2 : RUN mkdir -p /config/ && echo "HELLO WORLD" > /config/config-file
 ---> Running in 156262dab99d
 ---> 1cd0db55d0d2
Removing intermediate container 156262dab99d
Successfully built 1cd0db55d0d2
```

To be sure, remove any existing `sharedconfig` volume
```bash
$ docker volume rm sharedconfig
sharedconfig
```

Start the first container (which contains the config-file), and create
a named volume, called `sharedconfig`

```bash
$ docker run --rm -it -v sharedconfig:/config/ foo cat /config/config-file
HELLO WORLD
```
Start another container (a standard `ubuntu` container), and use the `sharedconfig`
named volume:

```bash
$ docker run --rm -it -v sharedconfig:/config/ ubuntu cat /config/config-file
HELLO WORLD
```

**Comment by thaJeztah** [comment] 2016-02-26 13:25
Having named volumes for single files is not supported, and not actually sure we would be able to do that reliably; plugins may not support this, and there are various things that make this really tricky;

For example, if the file you want to make into a volume does *not* exist in the container, but created at runtime, a directory will be made, instead of a file.

For individual files, I think your best option is to  bind-mount that file, however, the file should be present on the host before doing so

**Comment by atrauzzi** [comment] 2016-02-26 13:29
Really, having the option would be nice as I'd be able to rely on my tools (docker-compose, rancher-compose) to ensure that all comes together nicely.

I still say it would be useful so that containers can ship preferred configurations for supporting containers (php-fpm, nginx).

**Comment by thaJeztah** [comment] 2016-02-26 13:46
Feel free to open a feature request (e.g. "add support for single-file volumes"). But i'm not sure it will be accepted and/or actually possible.

Mounting individual files (also bind-mounted) can produce really strange issues. For example, some tools/software never *update* a file, but write to a temp-file, then remove the original file, and put the updated file in its place. Doing so with mounted files doesn't work, so will lead to a lot of headaches.

I understand your use-case, but not sure we can help. Re-structuring the directory-structure of your application, so that files to be shared (between containers, or as a volume) are in separate directories, is probably the best solution.

**Comment by atrauzzi** [comment] 2016-02-26 14:04
Yeah, that makes sense.  I guess what makes that tricky is that I'm trying to do this so that I don't have to maintain my own customization of the public nginx container.  I just need to be able to configure it (not customize).

I'll open that ticket on the offchance that it does make sense to at least make available.

**Comment by thaJeztah** [comment] 2016-02-26 14:07
Thanks! It's not that we're not willing to, we just have to keep in mind having to *maintain* each feature as well, which is often the hard part :+1:

**Comment by ninja-pirate** [comment] 2016-02-29 10:05
guys, here:
https://hub.docker.com/_/nginx/
they use mounting files.
is the documentation wrong?

**Comment by thaJeztah** [comment] 2016-02-29 10:17
@ninja-pirate bind-mounting files is supported (i.e. `-v /some/file.cf:/in/container.cf`), but not for "named" volumes (I.e. `-v letsnameitfoo:/in/container.cf`). It can be tricky though, because if the mounted file doesn't exist, docker doesn't know you meant a *file*, so currently makes an empty directory. This will change in future, see https://github.com/docker/docker/pull/19953

**Comment by ninja-pirate** [comment] 2016-02-29 10:19
@thaJeztah, oh i see now, thank you!

**Comment by mostolog** [comment] 2016-06-17 15:45
Hi


@thaJeztah If I understand properly, starting from docker 1.11 according to https://github.com/docker/docker/issues/19304#issuecomment-171386745 files cannot be mounted with _**-v**_. Did I understand correctly?

Actually, we hare using -v /etc/localtime:/etc/localtime:ro to get our containers synced with host time.

Is [this](http://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes) [that](https://github.com/docker/docker/issues/3359) the only way to achieve it?

Am I wrong or this forces to deploy using an entrypoint script or custom images built from dockerfiles?
Couldn't a **--sync** parameter be added to docker?

Regards

**Comment by thaJeztah** [comment] 2016-06-17 19:52
@mostolog bind-mounting a file is supported, but (as https://github.com/docker/docker/issues/19304#issuecomment-171386745) mentions; if the file you're trying to bind-mount doesn't exist, docker assumes you want it to create a directory and bind-mount that. There's no change in that respect (compared to older versions of docker)

**Comment by mostolog** [comment] 2016-07-05 06:44
@thaJeztah Thanks. Clear as water now. Shouldn't this issue be closed?
