### ISSUE TITLE
"docker ps" reports deleted image name/tag

### ISSUE THREAD

**Issue by softboysxp** [docker/docker#13652] opened 2015-06-01 23:55 UTC
When an image has been "renamed" (e.g. give it a new tag then remove the old tag), "docker ps" reports the old image tag even though such tag does not exist any more.

I have reproduced this on 1.6.2 release and 1.7-dev but not 1.5.0 or earlier.

e.g.

```bash
# ./docker version
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 1f22676
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 1f22676
OS/Arch (server): linux/amd64
# ./docker run -d nginx
9728a4af7ed370106dddd36e843315ca057efa95782dc41c90b0c0969530d0f3
# ./docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
9728a4af7ed3        nginx               "nginx -g 'daemon of   7 seconds ago       Up 6 seconds                            hopeful_blackwell
# ./docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
nginx               latest              a785ba7493fd        5 days ago          132.8 MB
# ./docker tag a785ba7493fd foo
# ./docker rmi nginx
Untagged: nginx:latest
# ./docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
foo                 latest              a785ba7493fd        5 days ago          132.8 MB
# ./docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
9728a4af7ed3        nginx               "nginx -g 'daemon of   32 seconds ago      Up 31 seconds                           hopeful_blackwell
```

In 1.5.0 or earlier, "docker ps" will report image as "foo:latest" as expected.

**Comment by softboysxp** [comment] 2015-06-02 17:53
```bash
# ./docker version
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 1f22676
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 1f22676
OS/Arch (server): linux/amd64
# ./docker info
Containers: 1
Images: 12
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.18.13-1-ec2-lts
Operating System: Arch Linux
CPUs: 2
Total Memory: 7.306 GiB
Name: ip-172-31-20-7
ID: ZQ34:FFT4:TI2Q:MJIM:UHDI:46H3:WOC4:XIDB:VX2A:OAVI:WI4C:YIFS
# uname -a
Linux ip-172-31-20-7 3.18.13-1-ec2-lts #1 SMP Wed May 20 20:00:18 PDT 2015 x86_64 GNU/Linux
```

**Comment by runcom** [comment] 2015-06-18 18:05
This behavior was changed from about 1.5.+ at https://github.com/docker/docker/blob/v1.5.0/daemon/list.go#L126
From 1.6.+ and above now we get `Image` from `container.Config.Image`

I'm not really sure if this is a bug/regression cause I don't know the history tho
ping @tiborvass @duglin

**Comment by runcom** [comment] 2015-06-18 18:07
ok found

https://github.com/docker/docker/commit/e45deceb462351f841aa077819fdef3166381c50

and the associated issue https://github.com/docker/docker/issues/10599
So not a bug nor nothing I think

**Comment by runcom** [comment] 2015-06-18 18:10
@softboysxp to sum up, `docker ps` isn't going to change the Image name the container was started with

**Comment by duglin** [comment] 2015-06-18 18:28
IMO this is a bug since the name being shown might no longer even exist, which means we're showing bad/useless data.

I understand why we continue to show the name used when the container was created, but if that name is no longer correct (either because its been removed, or worse, points to some other image) then we're doing the user a disservice.

While this will probably be a breaking change, I think we should change it so that we ALWAYS show the image ID since that will never change and, I think, we won't allow it to be deleted while the container is still using it.

ping @tiborvass @LK4D4

**Comment by runcom** [comment] 2015-06-18 18:46
agree to have ImageID instead

**Comment by cpuguy83** [comment] 2015-06-18 19:19
This is a dup... of some other issue... in the pile of issues.

**Comment by duglin** [comment] 2015-06-18 20:01
might be this one: #12595

**Comment by thaJeztah** [comment] 2015-07-13 22:36
I'm closing this as a dup of https://github.com/docker/docker/issues/12595, please continue the discussion over there.

Thanks for reporting @softboysxp !

**Closed by thaJeztah** 2015-07-13 22:36 UTC
