### ISSUE TITLE
Incorrect entry in /etc/hosts updated when linked container is restarted

### ISSUE THREAD

**Issue by cdanielw** [docker/docker#19080] opened 2016-01-05 10:10 UTC
When /etc/hosts is updated after a linked container’s been restarted, entries prefixed with the restarted container name are updated with incorrect location.

How reproducible:
```
docker run \
    --name child \
    -d ubuntu:14.04 \
    /bin/sh -c "while true; do echo hello world; sleep 1; done"

docker run \
    --name child-another \
    -d ubuntu:14.04 \
    /bin/sh -c "while true; do echo hello world; sleep 1; done"

docker run \
    --name yet-another-child \
    -d ubuntu:14.04 \
    /bin/sh -c "while true; do echo hello world; sleep 1; done"

docker run \
    --name parent \
    --link child \
    --link child-another \
    --link yet-another-child \
    -d ubuntu:14.04 \
    /bin/sh -c "while true; do echo hello world; sleep 1; done"

docker exec -it parent cat /etc/hosts

docker restart child

docker exec -it parent cat /etc/hosts
```

Results:
```
> docker exec -it parent cat /etc/hosts
172.17.0.5	3140a59b2c38
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	child 87af5283f0ac
172.17.0.3	child-another a0b99361ea1d
172.17.0.4	yet-another-child b0b1f9c509a7
> docker restart child
child
> docker exec -it parent cat /etc/hosts
172.17.0.5	3140a59b2c38
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	child 87af5283f0ac
172.17.0.2	child-another a0b99361ea1d
172.17.0.4	yet-another-child b0b1f9c509a7
```

Expected: 
`172.17.0.3	child-another a0b99361ea1d` instead of `172.17.0.2	child-another a0b99361ea1d` after 'child' container has been restarted.

```
docker version: 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```
```
docker info:
Containers: 5
Images: 896
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-263518-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 32.6 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.79 GB
 Metadata Space Used: 54.9 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.093 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 3.861 GiB
Name: vagrant-ubuntu-trusty-64
ID: 7NIY:ZE4D:6CA5:HYJX:PWO6:OKVV:C4KT:ZDL4:ZZU4:BX5V:RZZP:AOOH
WARNING: No swap limit support
```

Running on VirtualBox

**Comment by thaJeztah** [comment] 2016-01-05 12:22
Thanks for reporting! If this is a test system, would you be able to check if you're able to reproduce this on the current master? Builds can be downloaded from https://master.dockerproject.org (but not intended for production, or use on critical data :-))

I'll add this to the 1.10 milestone, but will try to reproduce on master as well to check if it has already been resolved,

**Comment by thaJeztah** [comment] 2016-01-05 12:38
I was able to reproduce this on master;

```bash
root@69ed39370d16:/# docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   0439e03
 Built:        Tue Jan  5 12:17:56 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   0439e03
 Built:        Tue Jan  5 12:17:56 2016
 OS/Arch:      linux/amd64
 ```

```bash
root@69ed39370d16:/# docker exec -it parent cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.2	child 9c826d06f978
172.18.0.3	child-another 9fb1bc35820c
172.18.0.4	yet-another-child 8e2feffeb31f
172.18.0.5	17938b42eda1

root@69ed39370d16:/# docker restart child

root@69ed39370d16:/# docker exec -it parent cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.2	child 9c826d06f978
172.18.0.2	child-another 9fb1bc35820c
172.18.0.4	yet-another-child 8e2feffeb31f
172.18.0.5	17938b42eda1
```

Just to be sure;

```bash
docker inspect -f "{{ json .NetworkSettings.Networks.bridge.IPAddress }}" child
"172.18.0.2"

docker inspect -f "{{ json .NetworkSettings.Networks.bridge.IPAddress }}" child-another
"172.18.0.3"
```

**Comment by thaJeztah** [comment] 2016-01-05 12:40
ping @mavenugo I'll assign you to this one. Not sure though; if the DNS based discovery is implemented,  will "legacy" links still use `/etc/hosts`?

**Comment by thaJeztah** [comment] 2016-01-10 23:20
ping @sanimej perhaps you can have a look, given that you are working on changes in this area :+1:

**Comment by sanimej** [comment] 2016-01-10 23:31
@cdanielw @thaJeztah [libnetwork #619] (https://github.com/docker/libnetwork/pull/619) fixes this issue. Its ready to be merged.

**Comment by thaJeztah** [comment] 2016-01-10 23:34
@sanimej great! can you add the right `closes xxx` to the vendor update PR when it gets opened in this repo?

**Comment by sanimej** [comment] 2016-01-10 23:43
@thaJeztah Sure.

**Closed** 2016-01-13 12:09 UTC
Labels: group/networking, kind/bug
