### ISSUE TITLE
docker load does produce error on invalid tar

### ISSUE THREAD

**Issue by mspanc** [docker/docker#23961] opened 2016-06-25 22:13 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.42 GiB
Name: ubuntu-32gb-nyc2-01
ID: XX4F:MSRZ:S7W4:HDUK:PREQ:CTIJ:VY7K:WZ6K:G3MT:KGAZ:V7SK:KNS7
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: mspanc
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

digital ocean ubuntu 16.04 64-bit box

**Steps to reproduce the issue:**
1. Create a docker image
2. Squash it using docker-squash (with -from root option)
3. Try to load image using `docker load < image.tar`

**Describe the results you received:**

Nothing. Exit code 0, image does not show up in `docker images`, no error message.

**Describe the results you expected:**

Error or image being properly imported.

**Additional information you deem important (e.g. issue happens only occasionally):**

Contents of the image I am trying to load

```
# tar tvf windows2.tar
-rw-r--r-- root/root      7007 2016-06-25 11:32 08449d0f3899a82fe7d895b18d7231f0ef83f71f1f62649ea5520ab59bf65ae9.json
drwxr-xr-x root/root         0 2016-06-25 16:39 5be006b32f097f88f9b5023d5d06a88abf0e0bba7becb5983deb170eeaec149d/
-rw-r--r-- root/root         3 2016-06-25 16:36 5be006b32f097f88f9b5023d5d06a88abf0e0bba7becb5983deb170eeaec149d/VERSION
-rw-r--r-- root/root 3095306240 2016-06-25 16:39 5be006b32f097f88f9b5023d5d06a88abf0e0bba7becb5983deb170eeaec149d/layer.tar
-rw-r--r-- root/root        711 2016-06-25 16:36 5be006b32f097f88f9b5023d5d06a88abf0e0bba7becb5983deb170eeaec149d/json
drwxr-xr-x root/root          0 2016-06-25 16:39 e0cfe9979f3a52a40d477115a1d9957fe359265eb558ba876de14f1daef00528/
-rw-r--r-- root/root          3 2016-06-25 11:32 e0cfe9979f3a52a40d477115a1d9957fe359265eb558ba876de14f1daef00528/VERSION
-rw-r--r-- root/root  196853760 2016-06-25 11:32 e0cfe9979f3a52a40d477115a1d9957fe359265eb558ba876de14f1daef00528/layer.tar
-rw-r--r-- root/root        388 2016-06-25 11:32 e0cfe9979f3a52a40d477115a1d9957fe359265eb558ba876de14f1daef00528/json
-rw-r--r-- root/root       1008 1969-12-31 19:00 manifest.json
-rw-r--r-- root/root        133 2016-06-25 16:39 repositories
```

**Comment by mspanc** [comment] 2016-06-26 10:01
I have found out that this is probably an issue after upgrade from docker that was shipped with ubuntu 16.04.

I have removed /var/lib/docker, restarted docker and now docker info returns

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.42 GiB
Name: ubuntu-32gb-nyc2-01
ID: XX4F:MSRZ:S7W4:HDUK:PREQ:CTIJ:VY7K:WZ6K:G3MT:KGAZ:V7SK:KNS7
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: mspanc
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

Now images seem to be loaded but with an error:

```
# docker load -i windows2.tar
81a9ec52d927: Loading layer [==================================================>] 196.9 MB/196.9 MB
open /var/lib/docker/tmp/docker-import-231824058/201f276fb5296069166229149865da238c6060bf6a92e78f8e37211022a9b402/layer.tar: no such file or directory
```

I will try to figure out what went wrong with that but no error handling in post-upgrade case is a clear bug IMO.

**Comment by mspanc** [comment] 2016-06-26 10:22
I've recreated the squashed docker image and again nothing happens. I've enabled -D and -l debug and the only thing that appears in the syslog when I attempt to load the image is 

Jun 26 06:17:35 ubuntu-32gb-nyc2-01 docker[8957]: time="2016-06-26T06:17:35.669912991-04:00" level=debug msg="Calling POST /v1.23/images/load?quiet=0"

**Comment by thaJeztah** [comment] 2016-06-28 07:10
This is an issue with docker-squash not being compatible with the new content-addressable storage in docker 1.10 and newer, see https://github.com/jwilder/docker-squash/issues/45. This is not a bug in docker, so I'll close this issue, but feel free to comment after I closed

**Comment by mspanc** [comment] 2016-06-28 07:27
Regardless if docker-squash has bug or not, I would expect that docker
itself will throw an error and return non zero status code (think about
automation!) if image format is not valid. IMO the bug should not be closed.

**Comment by thaJeztah** [comment] 2016-06-28 18:22
would you be able to provide a minimal image to reproduce this?

**Comment by thaJeztah** [comment] 2016-10-29 06:51
Closing as we did not receive more information, but we can reopen once provided

**Closed by thaJeztah** 2016-10-29 06:51 UTC
Labels: kind/enhancement, status/more-info-needed, version/1.11
