### ISSUE TITLE
running systemd inside docker arch container hangs or segfaults

### ISSUE THREAD

**Issue by flokli** [docker/docker#3629] opened 2014-01-16 14:46 UTC
I tried running the `base/arch` image in "system container" mode.

However, `docker run -i -t base/arch /sbin/init` doesn't seem to work like it should.
I detach it (Ctrl-p, Ctrl-q), and with strace I see /sbin/init (which doesn't do anything), however it should normally spawn some other processes (like systemd-journald)

When I run `docker run -i -t base/arch /bin/bash`, and enter /sbin/init --system, I get the following output:

```
systemd 208 running in system mode. (+PAM -LIBWRAP -AUDIT -SELINUX -IMA -SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ)
Detected virtualization 'lxc'.
Failed to set hostname to <888e6c612435>: Operation not permitted
Failed to enable kbrequest handling: Operation not permitted
No control group support available, not creating root group.
Cannot add dependency job for unit display-manager.service, ignoring: Unit display-manager.service failed to load: No such file or directory.
Segmentation fault (core dumped)
```

In the same container (but with strace installed), running
```
# docker run -i -t 1cff36031b68 /bin/bash
[root@bef7f6801a3d /]# strace -fvv /sbin/init --system
```
segfaults, leaving the following output: https://gist.github.com/flokli/8456044

Do you have any idea whats wrong here? I'd really like to use docker in system container mode, and according to #223, this should already be possible...

Florian

**Comment by jfrazelle** [comment] 2015-01-14 21:20
closing as duplicate of #7395

**Closed by jfrazelle** 2015-01-14 21:20 UTC
