### ISSUE TITLE
Cannot pull an image pushed with docker 1.10 using docker 1.7.1

### ISSUE THREAD

**Issue by adbrowne** [docker/docker#20134] opened 2016-02-09 04:15 UTC
BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version (Push side):
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64

docker version (Pull side):
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

docker info (Push side):
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: QZG2:7B32:ZM2W:JTNS:4XW5:TKS7:GNUR:IDND:IW4X:IIUH:RGES:Y4SR
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 21
 System Time: 2016-02-09T04:03:37.934551172Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Http Proxy: http://172.31.5.131:8888
Labels:
 provider=virtualbox

docker info (Pull side):
Containers: 4
Images: 80
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 92
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-73-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 1.955 GiB
Name: vagrant-ubuntu-trusty-64
ID: YUPL:RGQD:WW3N:3UYB:TNDA:NF6S:WXXG:DRF2:GANI:CKBX:AJ7S:BCVJ
Debug mode (server): true
File Descriptors: 10
Goroutines: 14
System Time: 2016-02-09T04:07:29.917292212Z
EventsListeners: 0
Init SHA1: c8f59b9547b87a6d097a72404dc29cba4e3a196e
Init Path: /usr/lib/docker/dockerinit
Docker Root Dir: /var/lib/docker
Http Proxy: http://172.31.5.131:8888
WARNING: No swap limit support

Provide additional environment details (AWS, VirtualBox, physical, etc.): 
Push side is docker-machine with virtualbox on osx
Pull side is ubuntu 14.04 running under VirtualBox (vagrant), also replicated on AWS elastic beanstalk.

List the steps to reproduce the issue:
This issue appears when pushing from docker 1.10 and then pulling from docker 1.7.1
1. (1.10) - docker pull hello-world
2. (1.10) - docker tag hello-world v2privateregistry.internal/shared/hello-world
3. (1.10) - docker push v2privateregistry.internal/shared/hello-world
4. (1.7.1) - docker pull v2privateregistry.internal/shared/hello-world

Describe the results you received:
On the console:
Pulling repository v2privateregistry.internal/shared/hello-world
Error: image shared/hello-world:latest not found
From the docker logs:
DEBU[0544] provided manifest reference "latest" is not a digest: invalid checksum digest format
ERRO[0544] Error from V2 registry: error verifying manifest: verifying remote digest: verification against digest "sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf" failed
DEBU[0544] image does not exist on v2 registry, falling back to v1
DEBU[0544] pulling v1 repository with local name "v2privateregistry.internal/shared/hello-world"

Describe the results you expected:
I expected to be able to pull the image successfully.
We do not have a v1 registry so I don't expect the v1 fallback to work.

Provide additional info you think is important:

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by dmcgowan** [comment] 2016-02-10 00:14
Which version of the registry are you using?

**Comment by aaronlehmann** [comment] 2016-02-10 02:35
This may be related to https://github.com/docker/distribution/issues/1444

**Comment by bbdimitriu** [comment] 2016-02-10 10:23
I can confirm this behaviour with registry:2.3

**Comment by dmcgowan** [comment] 2016-02-10 16:08
Closing this issue here since this is a registry issue tracked by https://github.com/docker/distribution/issues/1444. There is also an open PR to fix this https://github.com/docker/distribution/pull/1445.

@bbdimitriu downgrading to the old python registry is not necessary, 2.2.x does not have this issue. If you are having issues with 2.2.x please open up an issue at https://github.com/docker/distribution/issues so we can investigate.

**Closed by dmcgowan** 2016-02-10 16:08 UTC
Labels: group/distribution, kind/bug
