### ISSUE TITLE
Editing files inside container

### ISSUE THREAD

**Issue by adyanthaya17** [docker/docker#15783] opened 2015-08-24 06:10 UTC
Hi,

Could any tell me how to edit the files inside a docker container? (I'm unable to use the vi editor)

**Comment by thaJeztah** [comment] 2015-08-24 06:26
You can use `docker exec` to start a second process in the container and use any editor that is installed in the container.

*However* the GitHub issue tracker is not a support forum, and meant for reporting bugs and feature requests;

please ask this question;

- in the #docker IRC channel
- in the "docker users" Google group
- on https://forums.docker.com
- on StackOverflow

I'm closing this issue because it's not a bug or feature request.

**Closed by thaJeztah** 2015-08-24 06:26 UTC
