### ISSUE TITLE
[Question] Is it possible to create an IPv6 network without specifying a subnet?

### ISSUE THREAD

**Issue by robbrockbank** [docker/docker#18607] opened 2015-12-11 17:37 UTC
I've written a network and IPAM plugin and am wondering if it is possible to create an IPv6 network without specifying a subnet.

I can't see a way to specify on the `docker network create` command that the network is IPv6 enabled without specifying an IPv6 subnet.  Compare this to the IPv4 case where it is not necessary to specify an IPv4 subnet.  Are there any plans to specify the IP version on the network create without actually needing to specify any addresses?

On a related note, are there plans to make it possible to create an IPv6-only subnet.  The current implementation of libnetwork seems to always invoke the IPv4 branches and then optionally invoke the IPv6 ones.

Thanks,

Rob

dev:~$ docker version
Client:
Version: 1.9.0
API version: 1.21
Go version: go1.4.3
Git commit: 76d6bc9
Built: Tue Nov 3 19:20:09 UTC 2015
OS/Arch: linux/amd64

Server:
Version: 1.9.0
API version: 1.21
Go version: go1.4.3
Git commit: 76d6bc9
Built: Tue Nov 3 19:20:09 UTC 2015
OS/Arch: linux/amd64
dev:~$ docker info
Containers: 4
Images: 102
Server Version: 1.9.0
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 118
Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 3.86 GiB
Name: dev
ID: H2E7:VK52:6P4T:A2X5:ZZPQ:CAPE:63GT:F2JB:QSG6:UDTQ:6GWN:BF4T
WARNING: No swap limit support
dev:~$ uname -a
Linux dev 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment] 2015-12-12 11:05
Thanks for reporting. Possibly this issue should be opened in the libnetwork issue tracker first, but I'll ping @mrjana @mavenugo to check if this is already on the roadmap.

**Comment by mavenugo** [comment] 2015-12-13 23:49
a related comment : https://github.com/docker/docker/pull/17513#issuecomment-164032291
And yes, today we use the ipv6 subnet configuration to determine if we have to enable ipv6 or not and Yes it is mandatory for the user to specify the ipv6 subnet (just like the legacy requirement for docker0 bridge).
@aboch would be able to add more to this topic.

**Comment by aboch** [comment] 2015-12-14 17:13
@robbrockbank 
Correct, what you and @mavenugo described is the current behavior.
But I do not see any reason why we cannot support the ipv6 only and auto-ipv6 allocations use cases you were asking for.

I think the default behavior should still be: (auto) ipv4 + (optional) ipv6, because it is the most common. 
I am suggesting to add something like `ipv6-only` network create explicit option, to cover the v6 only pools.

On the other side, on the backend, I think the ipam driver should let libnetwork know whether it can satisfy an auto ipv6 pool allocation. But as more design questions come up, as @thaJeztah suggested, can you please open an issue in libnetwork, so that we can discuss and rule out there the proper flags/behavior.

Also, should you be able to help with the code changes, don't hesitate and let us know.
Thanks.

**Comment by mavenugo** [comment] 2016-10-22 16:59
Thanks for the confirmation @aboch . I will close this issue. Pls feel free to comment here if you think it is not working as intended.

**Closed by mavenugo** 2016-10-22 16:59 UTC
Labels: area/networking, version/1.9
