### ISSUE TITLE
Containers exiting with code 127, device-mapper device busy

### ISSUE THREAD

**Issue by mikejholly** [docker/docker#8176] opened 2014-09-23 02:18 UTC
We're running into a pretty critical issue with our Docker container setup. Some containers appear to be arbitrarily exiting with 127 exit codes. The 127 exit code doesn't make sense since the containers appear to be running fine beforehand. From what I understand this exit code indicates that the command was not found.

When we try to restart or rm the containers in question we see the errors below. The two problems appear to be related since we only see the errors with the 127'd containers.

Please note we are running Docker with the flag `-g /ebs/docker` to use EBS for the Docker root. We're doing this because our images are quite large and they quickly outgrow the standard EC2 volumes.

When I try to restart the container: 

```bash
$ docker restart e2b28c2732ae
Error response from daemon: Cannot restart container e2b28c2732ae: Error getting container e2b28c2732ae212469df0d8f8d1d964d96549e0ea9fa5c795c9b42fb832ac9e8 from driver devicemapper: Error mounting '/dev/mapper/docker-202:16-2621442-e2b28c2732ae212469df0d8f8d1d964d96549e0ea9fa5c795c9b42fb832ac9e8' on '/ebs/docker/devicemapper/mnt/e2b28c2732ae212469df0d8f8d1d964d96549e0ea9fa5c795c9b42fb832ac9e8': device or resource busy
2014/09/23 02:04:26 Error: failed to restart one or more containers
```

When I try to remove the container:

```bash
$ docker rm e55
Error response from daemon: Cannot destroy container e55d46116006: Driver devicemapper failed to remove root filesystem e55d46116006b7232ae99b2aa8937b0e47f974df01cabd6cad0f277df194df6f: Device is Busy
```

But it seems like the container is actually removed:

```bash
$ docker rm e2b28c2732ae
Error response from daemon: No such container: e2b28c2732ae
2014/09/23 02:05:19 Error: failed to remove one or more containers
```

Other info:

```bash
DOCKER_OPTS="-g /ebs/docker -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"
```

```bash
$ uname -a
Linux ip-10-0-2-128 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f
```

```bash 
$ docker -D info
Containers: 78
Images: 1022
Storage Driver: devicemapper
 Pool Name: docker-202:16-2621442-pool
 Pool Blocksize: 64 Kb
 Data file: /ebs/docker/devicemapper/devicemapper/data
 Metadata file: /ebs/docker/devicemapper/devicemapper/metadata
 Data Space Used: 15093.7 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 47.7 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.13.0-29-generic
Operating System: Ubuntu 14.04.1 LTS
Debug mode (server): false
Debug mode (client): true
Fds: 109
Goroutines: 66
EventsListeners: 0
Init Path: /usr/bin/docker
WARNING: No swap limit support
```

**Comment by vbatts** [comment] 2015-01-07 17:11
going to close this as a duplicate of https://github.com/docker/docker/issues/5684#issuecomment-69052334

**Closed** 2015-01-07 19:03 UTC
Labels: /system/devicemapper
