### ISSUE TITLE
interconnect containers in an application using aliases.

### ISSUE THREAD

**Issue by hackndoes** [docker/docker#18843] opened 2015-12-22 08:01 UTC
The enhancement:
Add a mechanism to give containers aliases for other containers in a manner that is not linking. for example if I have an application with service A and service B. Service B consumes service A.
Using the new networking module service B can seamlessly connect to service A by it's container name. 
What I am suggesting is adding an alias to the networked A container inside container B's /etc/hosts to that same A container so I can use the alias instead of the container name.

It will look something like this:
/etc/hosts
1.1.1.1 B
1.1.1.2 A my-alias

Motivation:
Docker or Compose for that matter will assign a generated name for each container to be unique. for the same service if I launch more than one container, even on different networks, still each containers gets a generated name which is unknown at compile time. Therefore it is not possible to find out which container supplies the service for me. If I could add such alias I could use it to connect to my related A service by it's alias, and since we are on the same network I will always reach the correct service container.

Please I will be very happy with any reply including Tips on how I could achieve what I want differently.

**Comment by thaJeztah** [comment] 2015-12-22 10:22
@hackndoes please have a look at https://github.com/docker/docker/issues/18699, which is proposing exactly this. You can subscribe to that issue using the "subscribe" button to stay informed on progress.

I'll close this issue, because it's a duplicate of https://github.com/docker/docker/issues/18699, but feel free to comment here after I've closed

**Closed by thaJeztah** 2015-12-22 10:22 UTC
