### ISSUE TITLE
Dockermon - Javascript Web UI/angular implementation for Docker

### ISSUE THREAD

**Issue by lexandro** [docker/docker#14208] opened 2015-06-26 18:00 UTC
Hi!

I'd like to add another ui implementation based on javascript and angular:
https://github.com/lexandro/dockery

Also available as chrome app:
https://chrome.google.com/webstore/detail/dockery-light/cefhojablgaokgccloekpocgmffgecmm?utm_source=chrome-ntp-icon

docker version:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

docker info:
Containers: 9
Images: 153
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 171
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 31.38 GiB
Name: lexandro-linux
ID: LCZ4:UAF3:OR4A:7QA5:3VTG:SUAI:ZI6T:623G:KIV3:IYSS:DVAL:3NYK
Debug mode (server): true
File Descriptors: 22
Goroutines: 34
System Time: 2015-06-28T12:52:18.278829239+02:00
EventsListeners: 0
Init SHA1: 
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: lexandro
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

uname -a:
Linux lexandro-linux 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):
N/A

List the steps to reproduce the issue:
N/A

Describe the results you received:
N/A

Describe the results you expected:
N/A

Provide additional info you think is important:

**Comment by lexandro** [comment] 2015-06-28 11:36
Extra info added

**Comment by cpuguy83** [comment] 2015-07-07 17:21
@lexandro Please open a PR updating the relevant docs.
ping @moxiegirl for the right place to put this.

**Comment by crosbymichael** [comment] 2015-07-07 18:20
Looks cool but I'm going to close this issue as it is not a bug.

**Closed by crosbymichael** 2015-07-07 18:20 UTC
