### ISSUE TITLE
Containers name resolution timed out with embedded DNS

### ISSUE THREAD

**Issue by narqo** [docker/docker#20335] opened 2016-02-15 20:49 UTC
I have two docker containers started and linked via `docker-compose.yml` file:

~~~
version: '2'
services:
  srv1:
    image: test-net
    expose:
      - 8000
    command: python -m SimpleHTTPServer
    working_dir: /tmp

  srv2:
    image: test-net
    links:
      - srv1
    command: tail -f /var/log/dpkg.log

networks:
  default:
    driver: bridge
    driver_opts:
      'com.docker.network.enable_ipv6': 'true'
~~~

`test-net` is a simple Ubuntu image with some additional stuff preinstalled.

After I run `docker-compose up`, I can attach to **srv2** container (`testdockercompose_srv2_1` in my example) and it looks like everything is set properly:

~~~
# cat /etc/resolv.conf

search haze.yandex.net yandex.net yandex.ru
nameserver 127.0.0.11
nameserver <my:host:system:ipv6:dns::1>
options ndots:0

# ping -w 5 127.0.0.11

PING 127.0.0.11 (127.0.0.11) 56(84) bytes of data.
64 bytes from 127.0.0.11: icmp_seq=1 ttl=64 time=0.090 ms
64 bytes from 127.0.0.11: icmp_seq=2 ttl=64 time=0.086 ms

--- 127.0.0.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 3999ms
rtt min/avg/max/mdev = 0.065/0.081/0.090/0.011 ms

# ping -w 2 srv1

PING srv1 (172.19.0.2) 56(84) bytes of data.
64 bytes from testdockercompose_srv1_1.testdockercompose_default (172.19.0.2): icmp_seq=1 ttl=64 time=0.132 ms
64 bytes from testdockercompose_srv1_1.testdockercompose_default (172.19.0.2): icmp_seq=2 ttl=64 time=0.114 ms

--- srv1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.114/0.123/0.132/0.009 ms
~~~

But if I try to call name resolution for `srv1` directly via `host` of `nslookup` I get "connection timed out":

~~~
# host srv1

;; connection timed out; no servers could be reached

# nslookup srv1

;; Got recursion not available from 127.0.0.11, trying next server
;; connection timed out; no servers could be reached
~~~

At the same time name resolution works fine if I specify DNS server explicitly:

~~~
# nslookup srv1 127.0.0.11

Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	srv1
Address: 172.19.0.2
~~~

This leads to HTTP timeouts during calls to linked containers. A simple curl call to `http://srv1:8000` takes 15 secs, while call to `http://172.19.0.2:8000` is instant.

My host system is IPv6-only Linux with docker 1.10.1 installed.

~~~
› docker version

Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

› sudo docker info

Containers: 9
 Running: 2
 Paused: 0
 Stopped: 7
Images: 88
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 93
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.19.0-42-lowlatency
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: var01f.vsfront.yandex.net
ID: YYOZ:TMTI:UE6N:6DUW:S2GP:KGNN:TN3G:CEQO:F2CA:ODQE:FRQH:Q356
Debug mode (server): true
 File Descriptors: 33
 Goroutines: 54
 System Time: 2016-02-15T23:48:08.593476359+03:00
 EventsListeners: 0
 Init SHA1: e1042dbb0bcf49bb9da188176d9a5063cdb92a01
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
Labels:
 provider=generic
~~~

**Comment by thaJeztah** [comment] 2016-02-15 22:42
ping @sanimej  @mavenugo could you have a look at this?

**Comment by thaJeztah** [comment] 2016-02-15 22:43
(Thanks for an excellent bug report @narqo )

**Comment by mavenugo** [comment] 2016-02-16 01:28
@narqo I think this is due to the fact that there are multiple DNS servers in the /etc/resolv.conf (127.0.0.11 and the ipv6 entry). Could you please try removing the ipv6 DNS entry from the host's /etc/resolv.conf and restart the daemon ?

I understand that you are trying an ipv6 use-case, but to narrow down the issue, can you pls remove the `--ipv6` flag from the docker daemon and let us know if that has an impact ?

**Comment by narqo** [comment] 2016-02-16 08:57
@mavenugo hm, yes containers' name resolution works fine after I'd removed ipv6 named server

~~~
# cat /etc/resolv.conf
search haze.yandex.net yandex.net yandex.ru
nameserver 127.0.0.11
options ndots:0

# nslookup srv1
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	srv1
Address: 172.19.0.2
~~~

But unfortunately my HTTP calls are still very slow. 

~~~
# time nc srv1 8000

real	0m15.017s
user	0m0.000s
sys	0m0.002s

# time nc 172.19.0.2 8000

real	0m0.711s
user	0m0.001s
sys	0m0.000s
~~~

I tried to trace what was happening during this `nc srv1 8000` call:

~~~
# strace -e poll,select,connect,recvfrom,sendto,read nc srv1 8000

read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200,\0\0\0\0\0\0"..., 832) = 832
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320:\0\0\0\0\0\0"..., 832) = 832
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\37\2\0\0\0\0\0"..., 832) = 832
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
read(3, "# /etc/nsswitch.conf\n#\n# Example"..., 4096) = 475
read(3, "", 4096)                       = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240\"\0\0\0\0\0\0"..., 832) = 832
read(3, "# Network services, Internet sty"..., 4096) = 4096
read(3, "\t\t# IPX\nipx\t\t213/udp\nimap3\t\t220/"..., 4096) = 4096
read(3, "nessus\t\t1241/tcp\t\t\t# Nessus vuln"..., 4096) = 4096
read(3, "qmaster\t6444/tcp\tsge_qmaster\t# G"..., 4096) = 4096
read(3, "ion\nspamd\t\t783/tcp\t\t\t\t# spamassa"..., 4096) = 3174
read(3, "", 4096)                       = 0
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
read(3, "# The \"order\" line is only used "..., 4096) = 92
read(3, "", 4096)                       = 0
read(3, "search haze.yandex.net yandex.ne"..., 4096) = 82
read(3, "", 4096)                       = 0
read(3, "127.0.0.1\tlocalhost\n::1\tlocalhos"..., 4096) = 174
read(3, "", 4096)                       = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\21\0\0\0\0\0\0"..., 832) = 832
read(3, "search haze.yandex.net yandex.ne"..., 4096) = 82
read(3, "", 4096)                       = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, 16) = 0
poll([{fd=3, events=POLLOUT}], 1, 0)    = 1 ([{fd=3, revents=POLLOUT}])
poll([{fd=3, events=POLLIN}], 1, 5000)  = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "\7U\201\0\0\1\0\1\0\0\0\0\4srv1\0\0\1\0\1\4srv1\0\0\1\0\1"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, [16]) = 42
poll([{fd=3, events=POLLIN}], 1, 4998)  = 0 (Timeout)
poll([{fd=3, events=POLLOUT}], 1, 0)    = 1 ([{fd=3, revents=POLLOUT}])
sendto(3, "\7U\1\0\0\1\0\0\0\0\0\0\4srv1\0\0\1\0\1", 22, MSG_NOSIGNAL, NULL, 0) = 22
poll([{fd=3, events=POLLIN}], 1, 5000)  = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "\7U\201\0\0\1\0\1\0\0\0\0\4srv1\0\0\1\0\1\4srv1\0\0\1\0\1"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, [16]) = 42
poll([{fd=3, events=POLLOUT}], 1, 4998) = 1 ([{fd=3, revents=POLLOUT}])
sendto(3, "5\305\1\0\0\1\0\0\0\0\0\0\4srv1\0\0\34\0\1", 22, MSG_NOSIGNAL, NULL, 0) = 22
poll([{fd=3, events=POLLIN}], 1, 4998)  = 0 (Timeout)
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, 16) = 0
poll([{fd=3, events=POLLOUT}], 1, 0)    = 1 ([{fd=3, revents=POLLOUT}])
sendto(3, "\7U\1\0\0\1\0\0\0\0\0\0\4srv1\0\0\1\0\1", 22, MSG_NOSIGNAL, NULL, 0) = 22
poll([{fd=3, events=POLLIN}], 1, 5000)  = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "\7U\201\0\0\1\0\1\0\0\0\0\4srv1\0\0\1\0\1\4srv1\0\0\1\0\1"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, [16]) = 42
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, 16) = 0
poll([{fd=3, events=POLLOUT}], 1, 4998) = 1 ([{fd=3, revents=POLLOUT}])
sendto(3, "5\305\1\0\0\1\0\0\0\0\0\0\4srv1\0\0\34\0\1", 22, MSG_NOSIGNAL, NULL, 0) = 22
poll([{fd=3, events=POLLIN}], 1, 4998)  = 0 (Timeout)
connect(3, {sa_family=AF_INET, sin_port=htons(8000), sin_addr=inet_addr("172.19.0.2")}, 16) = -1 EINPROGRESS (Operation now in progress)
select(4, NULL, [3], NULL, NULL)        = 1 (out [3])
poll([{fd=3, events=POLLIN}, {fd=0, events=POLLIN}], 2, 4294967295
) = 1 ([{fd=0, revents=POLLIN}])
read(0, "\n", 2048)                     = 1
poll([{fd=3, events=POLLIN}, {fd=0, events=POLLIN}], 2, 4294967295) = 1 ([{fd=3, revents=POLLIN}])
read(3, "", 2048)                       = 0
+++ exited with 0 +++
~~~

but all I see are several `poll([{fd=3, events=POLLIN}], 1, 4998)  = 0 (Timeout)` after making this
```
recvfrom(3, "\7U\201\0\0\1\0\1\0\0\0\0\4srv1\0\0\1\0\1\4srv1\0\0\1\0\1"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.11")}, [16]) = 42
```
calls. Can't say if this actually means anything.

**Comment by sanimej** [comment] 2016-02-16 16:07
@narqo Since you have ipv6 enabled nc might be trying to resolve the name to AAAA record first before falling back to ipv4. Can you try nc -4 ... ?

**Comment by narqo** [comment] 2016-02-16 16:36
@sanimej confirm, both nc and curl works fine with `-4` sets

~~~
# time curl -4 http://srv1:8000

real	0m0.012s
user	0m0.002s
sys	0m0.004s
~~~

What do you think, is there any chance to have IPv6 local DNS, so services could work in IPv6-only containers?

**Comment by netroby** [comment] 2016-02-17 08:09
This is really a bug for me . 

```
w ~ # docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

```

DNS resolv so slow. can not afford it

**Comment by sanimej** [comment] 2016-02-25 00:20
@narqo The first issue you had (nslookup failure when resolv.conf has an IPv6 address as well) should be fixed by [libnetwork #894] (https://github.com/docker/libnetwork/pull/894)

For the v6 service discovery, ie: name resolution to IPv6, I have a PR open [libnetwork #870] (https://github.com/docker/libnetwork/pull/870). It should be available in the next release 

I am still not able to recreate the curl/nc delay issue though. Can you run the daemon in debug mode (-D option) and send the logs when you run nc comment (without -4) ? Is your docker host a virtualbox VM or in AWS or something else ?

**Comment by narqo** [comment] 2016-02-25 18:25
Hey @sanimej 

> Can you also confirm if ipv6 disabled in the daemon, docker network and in your host ?

I've turned off ipv6 from both docker daemon and docker network (see link to the gist with logs and confs below). My host system is a **IPv6-only** machine in our corporate OpenStack cloud (we use dns64, so I'm still able to ping6 ipv4-only resources like github.com from the host). 

I couldn't reproduce the issue locally with my virtualbox machine either.

> I am still not able to recreate the curl/nc delay issue though. Can you run the daemon in debug mode (-D option) and send the logs when you run nc command (without -4) ? Is your docker host a virtualbox VM or in AWS or something else ?

Here're my logs, docker daeon config and other stuff https://gist.github.com/narqo/0bb824eb776ae48ebed2 

What I really don't understand is why it tries to resolve `srv1` through the google's 8.8.8.8 dns.

**Comment by fangzhouxin** [comment] 2016-02-29 04:42
@narqo, I use docker v1.10.2 in macbookpro to develop python based web application, and encounter slow communication speed between projects(all in same docker network). It seems that 'it tries to resolve srv1 through the google's 8.8.8.8 dns' is also the cause for my slowness.

**Comment by narqo** [comment] 2016-02-29 10:51
@fangzhouxin I believe that my issue is not about google's dns. If I turn IPv6 on in both docker daemon and docker network there are no `Querying ext dns` calls in daemon logs. But name resolution is still very slow.

**Comment by sanimej** [comment] 2016-02-29 17:05
@narqo From your debugs..
```
DEBU[0080] To resolve: srv1 in
DEBU[0080] Lookup for srv1.: IP 172.19.0.2
DEBU[0080] Querying ext dns udp:8.8.8.8 for srv1.[28]
ERRO[0082] external resolution failed, read udp 169.254.6.11:54429->8.8.8.8:53: i/o timeout
DEBU[0082] Querying ext dns udp:8.8.4.4 for srv1.[28]
ERRO[0084] external resolution failed, read udp 169.254.6.11:45769->8.8.4.4:53: i/o timeout
```
Embedded DNS server correctly resolves srv1 to IPv4 address 172.19.0.2. But your container app also sends a v6 query (number 28 in the braces). Since your host is v6 only looks like it has no reachability to v4 google DNS servers. This will cause the delay because the embedded server has to wait for the timeout. It also looks your app uses v4 only after v6 query fails. Some resolvers have a different behavior, they try both and use whichever reply comes first.

Docker doesn't fully support a v6 mode yet. So if the user didn't provide a v4 DNS server we use the google servers by default. That is why you see the queries going to 8.8.8.8

I see couple of options here.. 
1) see if your apps has an option to use v4 and avoid the v6 query (similar to curl -4 which you confirmed to be working).
2) Make 8.8.8.8/8.8.8.4 accessible from your host.

In the next release we are planning to add the v6 service discovery which should help in your case.

**Comment by fangzhouxin** [comment] 2016-03-02 07:41
Sadly the 8.8.8.8 dns server is blocked by China's Great Firewall, so when I develop in local machine the communication speed between docker projects become slow.

**Comment by sanimej** [comment] 2016-03-02 07:54
@fangzhouxin 8.8.8.8 is used only if you don't pass a v4 DNS server using --dns and your host /etc/resolv.conf file also doesn't have any v4 DNS server. Can you try doing either one of the above ?

**Comment by fangzhouxin** [comment] 2016-03-02 08:00
@sanimej, I disabled ipv6 of my mac osx machine by command:
(Thanks: <http://osxdaily.com/2014/04/18/disable-ipv6-mac-os-x/>)
```
networksetup -setv6off Wi-Fi
```
enverything is ok now.

**Comment by jswann** [comment] 2016-03-07 03:44
I think i'm having the same issue. I'm running Docker v1.10.3 on a VMWare host. 

I have a docker network created, with an nginx proxy (web) and a node.js (service) container running. When I hit the nginx URL i the traffic resolves to the service container properly, however on the second attempt the service container is trying to be resolved externally, instead of by the Docker DNS server.

**Comment by fangzhouxin** [comment] 2016-03-10 01:48
@jswann, how do you see the debug logs?

**Comment by jswann** [comment] 2016-03-10 02:01
@fangzhouxin, If you're using boot2docker (OSX or Windows), then you'll be able to see them by tailing the log at /var/log/docker.log.

Otherwise, you'll have to turn on the -D flag on the docker daemon, and tail the same docker.log.

**Comment by fangzhouxin** [comment] 2016-03-10 02:14
@jswann, thank you for reply. I use docker-compose and find no -D flag option.

**Comment by narqo** [comment] 2016-03-10 05:52
@fangzhouxin if you're using docker-machine to run docker daemon on your OSX host, you can ssh to the underlying boot2docker host with `docker-machine <machine_name> ssh` command. After that you must be able to tail the logs at `/var/log/docker.log` as @jswann'd suggested.

**Comment by fangzhouxin** [comment] 2016-03-10 07:32
@narqo, thank you very much. I have read /var/log/docker.log. When the communication speed between containers was slow, I found something like this in docker.log:
```
time="2016-03-10T07:16:29.815620360Z" level=debug msg="To resolve: yzapi in "
time="2016-03-10T07:16:29.815660267Z" level=debug msg="Lookup for yzapi.: IP 172.18.0.7"
time="2016-03-10T07:16:29.815737752Z" level=debug msg="Querying ext dns udp:180.168.255.118 for yzapi.[28]"
time="2016-03-10T07:16:31.816573929Z" level=error msg="external resolution failed, read udp 10.0.2.15:42432->180.168.255.118:53: i/o timeout"
time="2016-03-10T07:16:31.816617384Z" level=debug msg="Querying ext dns udp:116.228.111.18 for yzapi.[28]"
time="2016-03-10T07:16:33.816936056Z" level=error msg="external resolution failed, read udp 10.0.2.15:48788->116.228.111.18:53: i/o timeout"
```
Then I cat my /etc/resolv.conf (I use macprobook now):
```
nameserver 192.168.30.1
```
I changed dns server in /etc/default/docker like this:
```
DOCKER_OPTS="--dns 192.168.30.1"
```
and restarted docker-machine, now the the communication speed between containers was fast, and I saw something like this in docker.log:
```
time="2016-03-10T07:23:04.577777938Z" level=debug msg="To resolve: yzapi in "
time="2016-03-10T07:23:04.577818955Z" level=debug msg="Lookup for yzapi.: IP 172.18.0.7"
time="2016-03-10T07:23:04.577992946Z" level=debug msg="Querying ext dns udp:192.168.30.1 for yzapi.[28]"
```

**Closed** 2016-03-22 22:09 UTC
Labels: group/networking

**Comment by Amit-Naudiyal** [comment] 2017-03-07 23:31
Hey Guys,
I face the same problem with Windows hosts. However doing nslookup even with the embedded dns, I still can't resolve them.

IP Configuration of container: 

```
Windows IP Configuration

   Host Name . . . . . . . . . . . . : testhost1
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : eu-central-1.compute.internal

Ethernet adapter vEthernet (Container NIC 9eb7e8be):

   Connection-specific DNS Suffix  . : eu-central-1.compute.internal
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #2
   Physical Address. . . . . . . . . : 00-15-5D-E6-08-57
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::1483:45f3:2479:a775%19(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.20.140.255(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.20.128.1
   DNS Servers . . . . . . . . . . . : 172.20.128.1
                                                  172.20.128.1 
                                                  10.0.0.2
   NetBIOS over Tcpip. . . . . . . . : Disabled
```

Connection from Windows host:

```
PS C:\Users\Administrator> nslookup testhost1
Server:  ip-10-0-0-2.eu-central-1.compute.internal
Address:  10.0.0.2

*** ip-10-0-0-2.eu-central-1.compute.internal can't find testhost1: Non-existent domain
PS C:\Users\Administrator>
PS C:\Users\Administrator> nslookup testhost1 172.20.128.1
Server:  UnKnown
Address:  172.20.128.1

*** UnKnown can't find testhost1: Server failed
```

**Comment by Amit-Naudiyal** [comment] 2017-03-08 23:19
Disabling the firewall worked for me. However the resolution is still very slow with 'nat' network.

**Comment by valentin2105** [comment] 2017-04-18 02:38
https://github.com/docker/docker/issues/32675
