### ISSUE TITLE
Starting a container with a previous-used name returns: a container has already joined the endpoint

### ISSUE THREAD

**Issue by pbitty** [docker/docker#15727] opened 2015-08-20 17:29 UTC
Hi,

This seems related to #14169.  In that issue, the conflict is between two containers with the same service name and is described as 'by design'.  In this case, I am not defining a service name, just a container name.

### Description of problem:
Container fails to start if it has the same name as an existing container, even if the existing container has been renamed to something else.

`docker version`:

    Client:
     Version:      1.8.1
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   d12ea79
     Built:        Thu Aug 13 02:35:49 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.8.1
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   d12ea79
     Built:        Thu Aug 13 02:35:49 UTC 2015
     OS/Arch:      linux/amd64

`docker info`:

    Containers: 2
    Images: 4
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 8
     Dirperm1 Supported: false
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.13.0-62-generic
    Operating System: Ubuntu 14.04.3 LTS
    CPUs: 1
    Total Memory: 1.955 GiB
    Name: vagrant-ubuntu-trusty-64
    ID: COWL:55FE:IHYG:AVJ6:AE7B:U4E2:H77K:E3ON:WKRS:CODI:6OM6:RJFR
    WARNING: No swap limit support

`uname -a`:

    Linux vagrant-ubuntu-trusty-64 3.13.0-62-generic #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### Environment details (AWS, VirtualBox, physical, etc.):

    Ubuntu Trusty 64-bit running in VirtualBox (via vagrant)

### How reproducible:  
100% of the time.

### Steps to Reproduce:

1. start container named `foo`:

        docker run -d --name=foo ubuntu:trusty bash -c 'while true; do sleep 1; done'

2. rename container to bar:

        docker rename foo bar

3. start another container named foo:

        docker run -d --name=foo ubuntu:trusty bash -c 'while true; do sleep 1; done'

### Actual Results:
New container `foo` gets created but an error occurs when trying to start it.

    $ docker run -d --name=foo ubuntu:trusty bash -c 'while true; do sleep 1; done'
    Error response from daemon: Cannot start container 27e3756a16d06c4c0172e52538d5046c584277a10429fab6bed53041e9fad25c: a container has already joined the endpoint

    $ docker ps -a

    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
    27e3756a16d0        ubuntu:trusty       "bash -c 'while true;"   2 seconds ago       Created                                 foo
    183810fd902f        ubuntu:trusty       "bash -c 'while true;"   13 seconds ago      Up 12 seconds                           bar

### Expected Results:
New container `foo` should be created and started with no errors.

### Additional info:

* docker.log output:

        DEBU[0195] Calling POST /containers/create
        INFO[0195] POST /v1.20/containers/create?name=foo
        DEBU[0195] Calling POST /containers/{name:.*}/start
        INFO[0195] POST /v1.20/containers/7ec6ad9b07af7e942248577d88394d791041874f0a454a9d8e576d18b883b121/start
        DEBU[0201] Calling POST /containers/{name:.*}/rename
        INFO[0201] POST /v1.20/containers/foo/rename?name=bar
        DEBU[0204] Calling POST /containers/create
        INFO[0204] POST /v1.20/containers/create?name=foo
        DEBU[0204] Calling POST /containers/{name:.*}/start
        INFO[0204] POST /v1.20/containers/35fb82ca807425dee3b809af98c64fd82e4d1d02ac6ee7c0d229b9ec2437ac05/start
        ERRO[0204] Leave all failed for  35fb82ca807425dee3b809af98c64fd82e4d1d02ac6ee7c0d229b9ec2437ac05: could not find sandbox for container id 35fb82ca807425dee3b809af98c64fd82e4d1d02ac6ee7c0d229b9ec2437ac05
        ERRO[0204] Handler for POST /containers/{name:.*}/start returned error: Cannot start container 35fb82ca807425dee3b809af98c64fd82e4d1d02ac6ee7c0d229b9ec2437ac05: a container has already joined the endpoint
        ERRO[0204] HTTP Error                                    err=Cannot start container 35fb82ca807425dee3b809af98c64fd82e4d1d02ac6ee7c0d229b9ec2437ac05: a container has already joined the endpoint statusCode=500

* `docker inspect` [output for both containers](https://gist.github.com/pbitty/e8c7782490421a1c4d5a)

**Comment by mavenugo** [comment] 2015-08-20 18:56
@pbitty the design is related to https://github.com/docker/docker/issues/14169, but not handling the renaming case is a bug. Added 1.9.0 milestone.

**Comment by mavenugo** [comment] 2015-09-01 15:36
@jfrazelle @icecrime is this a critical requirement for 1.8.2 ? with the support for multi-host networking in 1.9.0, there will be a few changes to the back-end implementation of using --name as endpoint name. I prefer not to add a patch now to fix this and redo it for 1.9.0. Since the rename feature is not being used much  I dont see the compelling need to force this fix into 1.8.2. WDYT ?

**Comment by jfrazelle** [comment] 2015-09-01 15:40
not critical for 1.8.2 i dont think because it has been broken since 1.7.0
and we just are hearing about it now

**Comment by mavenugo** [comment] 2015-09-01 15:41
Thanks @jfrazelle . Also, I confirmed that `docker rename` feature is not compatible with `link` in 1.6 & earlier. And that is exactly the service discovery issue that i was worried about for multi-host networking.
Is it a stretch to prevent `rename` for some conditions (such as multi-host service discovery or --link) ?

**Comment by calavera** [comment] 2015-09-01 15:46
I'd like to understand why changing the container name breaks networking. We should use IDs there for everything.

**Comment by mavenugo** [comment] 2015-09-01 15:50
@calavera its the same reason why `--link` fails when we rename a container. Its to update the /etc/hosts with the name to ip-address mapping.
When the container name is changed, all the linked containers need to be updated. It was never taken care of `--link` feature. But, in the new CNM model, we implicitly create an endpoint with the container name. a Rename doesnt rename the endpoint and hence when a new container reuses the name, it is unable to reuse the endpoint which is already being used.

A quick fix is to just rename the endpoint. But it will result in the same issue as in `--link`.

**Comment by calavera** [comment] 2015-09-01 16:38
@mavenugo why are endpoints using container names as IDs in the first place? This makes me think that if you rename a container and then remove it, the endpoint and net_ns will be leaked because we won't be able to find it, is this correct?

**Comment by tiborvass** [comment] 2015-10-27 20:48
Closed by #17390

**Closed by tiborvass** 2015-10-27 20:48 UTC
Labels: group/networking

**Comment by mc0** [comment] 2016-01-07 19:43
@tiborvass @calavera is there any chance of getting this backported to 1.8? We are using 1.8.3 and realized two of our servers weren't on docker 1.8. After upgrading those docker 1.6 boxes we noticed this bug (as you know a regression from docker 1.6). A bit outside of your control, but unfortunately coreOS still doesn't have docker 1.9 in stable and while I'd love to just upgrade it would prove a lot more difficult.
