### ISSUE TITLE
specify ip address range for docker containers, not working with compose

### ISSUE THREAD

**Issue by natarajanv** [docker/docker#25666] opened 2016-08-12 15:33 UTC
**Output of `docker version`:**

```
[venkat@r10a-docker-venkat ~]$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
[venkat@r10a-docker-venkat ~]$ docker info
Containers: 32
 Running: 3
 Paused: 0
 Stopped: 29
Images: 8
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:9-14680928-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/docker_dg/data
 Metadata file: /dev/docker_dg/metadata
 Data Space Used: 4.645 GB
 Data Space Total: 102 GB
 Data Space Available: 97.36 GB
 Metadata Space Used: 6.537 MB
 Metadata Space Total: 5.365 GB
 Metadata Space Available: 5.358 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 2.782 GiB
Name: r10a-docker-venkat
ID: LOKD:YIPG:QQ35:AW7S:OORD:2QHD:SCBL:E6JO:TWDK:FT5X:UEPU:MH6O
Http Proxy: gatekeeper.mitre.org:80
Https Proxy: gatekeeper.mitre.org:80
No Proxy: localhost,127.0.0.1,localaddress,.mitre.org,/var/run/docker.sock
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 mitre.environment=ECE
 mitre.pool=E
 mitre.f5=B0k103-dltm1.mitre.org

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Run the docker daemon with this flag: --bip=172.50.0.1/16  --fixed-cidr=172.100.0.0/16 
2.  Run a container using docker run, as well as docker-compose and do docker inspect to check the ip address
3.

**Describe the results you received:**
when I run a container using docker run, and do a inspect I see this:

 "Gateway": "172.50.0.1",
 "IPAddress": "172.50.0.2",
 
But, when I run the container using docker-compose and inspect I see this:

 "Gateway": "172.18.0.1",
 "IPAddress": "172.18.0.2",

**Describe the results you expected:**
I expect docker-compose to honor the ip address range

**Additional information you deem important (e.g. issue happens only occasionally):**
this is my compose file:
[venkat@r10a-docker-venkat tmp]$ cat busybox.yml
version: '2'
services:
 busy:
  image: busybox:latest
  command: /bin/sh

This is how I ran the command line docker run:
docker run --rm -it busybox /bin/bash

output from systemctl status
[venkat@r10a-docker-venkat tmp]$ systemctl status docker
â docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2016-08-09 12:35:36 EDT; 2 days ago
     Docs: https://docs.docker.com
 Main PID: 29043 (docker)
   CGroup: /system.slice/docker.service
           ââ29043 /usr/bin/docker daemon --bip=172.50.0.1/16 --fixed-cidr=172.100.0.0/16 --selinux-enabled --label=mitre.environment=ECE --label=mitre.pool=E --label=mitre.f5=B0k103-dlt...
           ââ29140 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8888 -container-ip 172.17.0.2 -container-port 8080

**Comment by thaJeztah** [comment] 2016-08-12 15:40
Thanks for reporting; `--bip` is only used for the default bridge network; docker compose with the `Version 2` format creates a custom network for each project, thus doesn't take those settings into account. You can, however specify a subnet/range for that network, see https://docs.docker.com/compose/compose-file/#/network-configuration-reference

I'll close this, because this is a duplicate of https://github.com/docker/docker/issues/21776, so please continue the discussion there

**Closed by thaJeztah** 2016-08-12 15:40 UTC
Labels: version/1.10
