### ISSUE TITLE
Docker image eating up my disk space that is not used by docker

### ISSUE THREAD

**Issue by ming-relax** [docker/docker#10021] opened 2015-01-10 09:21 UTC
I have setup docker and I have used  completely different block device to store docker's system data:

    [root@blink1 /]# cat /etc/sysconfig/docker
    # /etc/sysconfig/docker
    
    other_args="-H tcp://0.0.0.0:9367 -H unix:///var/run/docker.sock -g /disk1/docker"

Note that **`/disk/1`** is using a completely different hard drive **`/dev/xvdi`**

    Filesystem      Size  Used Avail Use% Mounted on
    /dev/xvda1      7.8G  5.1G  2.6G  67% /
    devtmpfs        1.9G  108K  1.9G   1% /dev
    tmpfs           1.9G     0  1.9G   0% /dev/shm
    /dev/xvdi        20G  5.3G   15G  27% /disk1
    /dev/dm-1       9.8G  1.7G  7.6G  18% /disk1/docker/devicemapper/mnt/bb6c540bae25aaf01aedf56ff61ffed8c6ae41aa9bd06122d440c6053e3486bf
    /dev/dm-2       9.8G  1.7G  7.7G  18% /disk1/docker/devicemapper/mnt/c85f756c59a5e1d260c3cdb473f3f4d9e55ac568967abe190eeaf9c4087afeac

The problem is that when I continue download docker images and run docker containers, it seems that the other hard drive **`/dev/xvda1`** is also used up.

I can verify this problem by remove some docker images. After I removed some docker images, **`/dev/xvda1`** has some more extra space now.

Am I missing something?

My docker version:

    [root@blink1 /]# docker info
    Containers: 2
    Images: 42
    Storage Driver: devicemapper
     Pool Name: docker-202:1-275421-pool
     Pool Blocksize: 64 Kb
     Data file: /disk1/docker/devicemapper/devicemapper/data
     Metadata file: /disk1/docker/devicemapper/devicemapper/metadata
     Data Space Used: 3054.4 Mb
     Data Space Total: 102400.0 Mb
     Metadata Space Used: 4.7 Mb
     Metadata Space Total: 2048.0 Mb
    Execution Driver: native-0.2
    Kernel Version: 3.14.20-20.44.amzn1.x86_64
    Operating System: Amazon Linux AMI 2014.09

**Comment by jfrazelle** [comment] 2015-01-14 19:39
ping @vbatts :)

**Comment by PlugIN73** [comment] 2015-01-16 09:01
I have the same issue. You can run images with --rm options. (https://docs.docker.com/reference/run/#clean-up-rm)

Now try to look up for exited containers and kill them

    docker ps  -a -f status=exited

and look up for dandling images and kill them too :)

    docker images --filter 'dangling=true'

**Comment by vbatts** [comment] 2015-01-20 22:12
@ming-relax honestly I am not able to reproduce this at all. Also, if you have the extra disk(s) that you can alllocate for docker's use, please consider using the `--storage-opt` flag to give devicemapper a dedicated data and metadata block device. This is what it accomplishes by default in the loopback files. Though direct block device will be much better performance. See https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/README.md

**Comment by thaJeztah** [comment] 2015-01-20 22:31
@PlugIN73 not sure if your case is the same here; this issue is about docker using up space in the wrong *location*, not "taking up space" *in general*. Bonus tip for your cleaning-up tasks; if you clean up containers that use "volumes", use `docker rm -v ...` to also delete the volumes, otherwise they will be left behind.

**Comment by jfrazelle** [comment] 2015-03-02 16:53
closing as dup of https://github.com/docker/docker/issues/9786

**Closed by jfrazelle** 2015-03-02 16:53 UTC
Labels: /system/devicemapper, bug
