### ISSUE TITLE
API does not properly check for repository name format when committing a container

### ISSUE THREAD

**Issue by christopherobin** [docker/docker#13821] opened 2015-06-09 07:07 UTC
## How to reproduce

First start a container:
`docker run --rm -t -i --name foobar ubuntu bash`

Then send the following curl to the docker daemon:
`curl -XPOST 'localhost:8080/commit?container=foobar&comment=foo&repo=test/foobar@foo:bar'`

See the repo name `test/foobar@foo:bar` which should raise an error as `foo:bar` is an invalid tag, but instead we get a nice reply from the server:
`{"Id":"7f8d4a8f7920c781abc94608f4e489f52152ca1e9524ddcb2def1ab55903b2a6"}`

From there things start to break as we can't reference the image by name, only by ID:
```bash
$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
test/foobar                 <none>              7f8d4a8f7920        16 minutes ago      215.7 MB
$ docker inspect test/foobar
Error: No such image or container: test/foobar
[]
$ docker inspect 7f8d4a8f7920
[{
  /* valid inspect data */
}
]
```

Trying to remove the image just fails in every cases:
```bash
$ docker rmi test/foobar
Error response from daemon: No such image: test/foobar
FATA[0000] Error: failed to remove one or more images   
$ docker rmi 7f8d4a8f7920
Error response from daemon: No such repository: test/foobar
FATA[0000] Error: failed to remove one or more images   
```

After inspecting `/var/lib/docker/repositories-devicemapper`:
```json
{
  "Repositories": {
    "test/foobar@foo:bar": {
      "latest": "7f8d4a8f7920c781abc94608f4e489f52152ca1e9524ddcb2def1ab55903b2a6"
    }
  }
}
```

## Docker version
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

## Docker info
```
Containers: 2
Images: 210
Storage Driver: devicemapper
 Pool Name: docker-8:7-8265223-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.503 GB
 Data Space Total: 107.4 GB
 Data Space Available: 97.7 GB
 Metadata Space Used: 11.4 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Kernel Version: 4.0.5-1-ARCH
Operating System: Arch Linux
CPUs: 4
Total Memory: 7.716 GiB
Name: crobin-linux
ID: 4IWV:LSNC:DVZH:SZAM:YBYF:H32V:54RB:ICX3:S2V3:TCRM:LHZH:IQMU
```

## uname
`Linux crobin-linux 4.0.5-1-ARCH #1 SMP PREEMPT Sat Jun 6 18:37:49 CEST 2015 x86_64 GNU/Linux`

**Comment by vdemeester** [comment] 2015-06-09 07:17
+kind/bug

It's a little bit related to the comment from @cpuguy83  in this issue : https://github.com/docker/docker/issues/10409#issuecomment-71928932.

> What we could do is have an actual validator that gets checked before a container is even attempted to be created, and make sure that validation happens for each user input (builder, api, cli), and that it's all the same validator, since right now it's all over the place.

There is some checks that are done in the client-side (``opts.go``, …) that should be handled by all (cli, api, builder).

**Comment by christopherobin** [comment] 2015-06-09 07:27
The issue seems to steam from [`docker.registry.NormalizeLocalName`](https://github.com/docker/docker/blob/2daede5a9cc6cc171f2f1f3aebcae561a2421d18/registry/config.go#L384-L390) as errors are not bubbled up when using an invalid repository name. I guess that the issue does not happen only with @, but actually any invalid repository name will work.

**Comment by runcom** [comment] 2015-06-09 07:30
@christopherobin right make sense

**Comment by christopherobin** [comment] 2015-06-09 07:46
Actually a better function would be [`docker.graph.validateRepoName`](https://github.com/docker/docker/blob/master/graph/tags.go#L377-L385), it is also called during the commit process and seems kinda... light as the moment

**Comment by christopherobin** [comment] 2015-06-09 08:16
I will try sending a PR this evening, probably just using the RegExp defined in [`registry/v2`](https://github.com/docker/docker/blob/274baf70bf806678d12adc1e1de2c8d7774de645/vendor/src/github.com/docker/distribution/registry/api/v2/names.go#L30-L38).
(Might have to copy it, just like the [other ones](https://github.com/docker/docker/blob/master/graph/tags.go#L30-L31))

**Comment by vdemeester** [comment] 2015-06-09 08:18
#dibs for @christopherobin then :wink:. (ps : if it's in vendor in the docker source, you should be able to use it, as it is exported)

**Comment by hqhq** [comment] 2015-06-09 09:11
@christopherobin I think you should just use `registry.ValidateRepositoryName` and `tags.ValidateTagName` for validation check for repo and tag. However there are bunch of work to do to resolve this problem completely, such as:
 - check both repo and tag on client side, including `docker tag`, `docker import`, `docker build` and `docker commit`;
 - check both repo and tag on daemon side to cover the REST api cases;
 - add cli test and api test for all above cases;

If it's a bit complicate for you, I can help do some work :)

**Comment by vdemeester** [comment] 2015-06-09 09:16
@hqhq For this issue only, the problem is only that ``validateRepoName`` and ``ValidateTagName`` are pretty simple and do not share code with the validation we do in the ``cli`` side. 

I personnaly think, we should fix this one the most simple way possible : i.e. add some integration-cli tests and fixe the methods. 
And then, start a refactor of validations so that we can share some of them between API, and CLI side (and have some *just* for cli side, some just for API side).

**Comment by christopherobin** [comment] 2015-06-09 09:39
Yeah right now validation is all over the place, part of it being in the graph library, part of it in the registry (and probably other places).

Having a lightweight common lib with the validation for all the types used in the docker source (repository, tags, container names, etc...) and using that everywhere would be the best solution imo, but like @vdemeester says I don't think it fits in the scope of that issue as it would involve a substantial refactoring that clearly needs some thoughts before being done.

**Comment by vdemeester** [comment] 2015-06-29 06:56
@christopherobin (still) working on this ?

**Comment by christopherobin** [comment] 2015-06-29 07:46
I have a quick fix ready that uses [ValidateRepositoryName@registry/config.go](https://github.com/docker/docker/blob/master/registry/config.go#L228) but was waiting a little to see if a better way would take form from the proposal in #13824

**Comment by runcom** [comment] 2015-12-13 15:09
```
curl -XPOST 'localhost:2375/commit?container=foobar&comment=foo&repo=test/foobar@foo:bar'
invalid reference format
```
this seems, as of master, fixed and you can't create an images with an invalid name
I'm going to close this, feel free to ping me if I'm not right and I'll reopen

**Closed by runcom** 2015-12-13 15:09 UTC
Labels: kind/bug
