### ISSUE TITLE
Privileged containers start with devicemapper, instead of overlay

### ISSUE THREAD

**Issue by euqen** [docker/docker#31918] opened 2017-03-17 13:42 UTC
I have docker running on `CentOS Linux release 7.0.1406 (Core)`. Also I'm using overlay instead of devicemapper loopback storage driver.

I run docker container in privileged mode, it starts fine, but when I try to proceed into started container, the `docker info` command shows me that this privileged container uses devicemapper, but host's docker runs using overlay. I assume that this is not correct behavior and how can I force my privileged containers run in my host storage driver or something different then devicemapper? I know that I can share docker socket as a volume to this container and do not use privileged mode at all, but I'm interesting in running exactly privileged containers.

Also there is another problem with the docker-in-docker thing. After some weeks of using the privileged container my machine was completely out of free disk space. I cleaned up all unused images, volumes and containers at host docker, and inside privileged container, but my disk space did not released back.
After that I tried to stop all my docker containers and stop docker daemon at all, and got only 4.3GB free disk space. Here is what df -h said me:
```bash
[root@m13 ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        59G   52G  4.3G  93% /
devtmpfs        2.0G     0  2.0G   0% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           2.0G  217M  1.8G  11% /run
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
tmpfs           395M     0  395M   0% /run/user/0
```
Then I tried to remove `/var/lib/docker` and got yet 3GB additional disk space. But I still had 53 GB occupied by something. And only after 10 hours of investigating I found that docker did not unmount the device mappings and this command helped me:

```bash
for dm in /dev/mapper/docker-*; do umount $dm; dmsetup remove $dm; done
```

I absolutely understand that devicemapper has issues with fs, that's why I switched to overlay, but the main question is can I use docker in docker with overlay in privileged mode which will not cause disk problems?

```bash
[root@m13 docker]# docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64
```

```bash
[root@m13 docker]# docker info
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.12.5
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-229.14.1.el7.centos.plus.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.856 GiB
Name: m13
ID: SMZF:64TM:BGWW:NU6U:M6TK:43F3:DHWW:RTFU:ZWIL:WDVV:MBRO:QAQQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Comment by thaJeztah** [comment] 2017-03-17 16:50
When running docker-in-docker, without using a volume for `/var/lib/docker`, most graph drivers (other than `vfs`) are troublesome. To run docker-in-docker with a different graph driver;

- ask yourself if you really _need_ docker-in-docker, or if giving the "privileged" container access to the host daemon (e.g. by bind-mounting `/var/run/docker.sock`) would give you what you need (see https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/). Docker-in-docker is a "use at your own risk" feature.
- make `/var/lib/docker` a volume
- manually specify the storage driver to use, using the `-s` / `--storage-driver` option or a `daemon.json` file.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-17 16:50 UTC
Labels: version/1.12
