### ISSUE TITLE
Push image's remote API response

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker#22352] opened 2016-04-27 03:19 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   6f36242-unsupported
 Built:        Fri Feb 26 11:59:13 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   6f36242-unsupported
 Built:        Fri Feb 26 11:59:13 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 132
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: trusty
ID: MBNO:UHUZ:QX3M:SYFQ:R6C7:3NLJ:4VBG:BTW7:3MLX:OL7G:UATE:ZTRP
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Steps to reproduce the issue:**
1. Push image to private registry
2. print out stream log in console
3. Sometimes it will get ``current`` is bigger than ``total``

**Describe the results you received:**
    {u'status': u'Pushing', u'progressDetail': {u'current': 190034944, u'total': 187764542}, u'id': u'c8528dddc096', u'progress': u'[==================================================>]   190 MB'}

**Describe the results you expected:**
current should not bigger than total. Right?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-04-28 12:28
Looks like a duplicate of https://github.com/docker/docker/issues/21536, so I'll close this one, but feel free to comment if you think it's not

**Closed by thaJeztah** 2016-04-28 12:28 UTC
