### ISSUE TITLE
Docker should allow for default (host-specific) environment variables

### ISSUE THREAD

**Issue by fyhuang** [docker/docker#8143] opened 2014-09-20 00:30 UTC
Hello, I have a situation in which I collaborate with several other team members on a project with a Dockerfile, but where we have very different networking setups. On their end, the standard network setup (NAT through docker0) works fine; on my end, iptables is fairly locked down and so I've resorted to using a proxy server on the host to provide network access to containers. I set the env variable http_proxy inside the container to accomplish this. I'm looking for a way to do this by default, for all containers on my machine, without disturbing the Dockerfile for others who don't need such a setup.

At the moment I have to edit the Dockerfile to include `ENV http_proxy http://...`, but I have to keep this change local because I don't want to break everybody else's network setup. It would be great to have an option (`-e`?) to pass to the Docker daemon that would apply an environment variable to all containers run by that daemon, which would allow a site-specific proxy setup without any changes to the Dockerfile. Apologies if the option already exists and I haven't found it, and I would love to hear about alternative ways to solve this as well. Thanks!

**Comment by jfrazelle** [comment] 2015-02-26 03:49
see https://github.com/docker/docker/pull/10748

**Comment by thaJeztah** [comment] 2015-02-26 06:38
Because this is about build-time environment variables, I think this is actually  a duplicate of https://github.com/docker/docker/issues/4962 (which will be resolved by https://github.com/docker/docker/pull/9176).

Feel free to discuss this further on those

**Closed** 2015-02-26 07:24 UTC
