### ISSUE TITLE
Updated Github, how to update Docker container

### ISSUE THREAD

**Issue by mateomorrison** [docker/docker#31761] opened 2017-03-12 02:34 UTC
Newbie question:

I don't find any way on how to update my Docker container after updating my GitHub repository. How to do it?

**Comment by necrose99** [comment] 2017-03-12 17:12
Add a hook on docker hub raw... url to files 
IF file changes then respawn build. If parent chages... ie from gentoo-amd64 , then rebuild my container..

**Comment by necrose99** [comment] 2017-03-12 17:12
Quay.io  also the same.

**Comment by thaJeztah** [comment] 2017-03-12 21:22
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-03-12 21:22 UTC
