### ISSUE TITLE
docker 1.10 syslog format issue

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#20053] opened 2016-02-05 23:31 UTC
Example syslog line:
`Feb 05 15:23:40 hostname org/image/sha256: 5a5e7/5c5f67d9e251[10876]: data...`

The hash of the image has changed to have the prefix `sha256:` and that messes up some syslog file readers because of the `: ` and also cuts off a lot of the bytes of the image hash.

```
docker version
Client:
 Version:      1.10.0-rc3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   08c24cc
 Built:        Tue Feb  2 23:01:16 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-rc3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   08c24cc
 Built:        Tue Feb  2 23:01:16 2016
 OS/Arch:      linux/amd64
```

I'm running an RC, but I didn't see any syslog related changes recently, so it's probably still an issue.

**Comment by calavera** [comment] 2016-02-08 22:02
@vikstrous any idea when we produce that log? I'm trying to reproduce but I'm running out of ideas.

**Comment by calavera** [comment] 2016-02-08 22:08
are you using a custom log tag?

**Comment by vikstrous** [comment] 2016-02-08 22:20
Oops, it looks like we use the following log option: `"tag": "{{.Name}}/{{.ImageID}}/{{.ID}}",`

**Comment by calavera** [comment] 2016-02-10 15:59
ImageIDs might be either names or digest tags. I wonder if we should not do anything about the ID but add an `ImageName` to make it more explicit. `ImageName` would always return the name, for example `ubuntu/latest`. I'm guessing that's what you really want. The parsing issue with syslog is unfortunate, but I don't think we should strip the prefix in the digest.

**Comment by calavera** [comment] 2016-02-10 17:45
Oh, I just realized that `ImageName` is already a thing in the logger context:

https://github.com/docker/docker/blob/master/daemon/logger/context.go#L18

Maybe you can use that to avoid the prefix.

**Comment by calavera** [comment] 2016-02-10 17:55
This is how the log looks like with `"{{.Name}}/{{.ImageName}}/{{.ID}}"`:

![image](https://cloud.githubusercontent.com/assets/1050/12956352/6c2c0434-cfdc-11e5-8fec-b6212338743e.png)

**Comment by icecrime** [comment] 2016-02-10 17:56
Thanks @calavera!

I think we can close this one? The new `ImageiD` format has an unexpected side effect on syslog, but at least there are good alternatives.

**Comment by vikstrous** [comment] 2016-02-10 17:57
Hmm... am I missing something or is the tag not in any of these fields? ContainerImageName doesn't uniquely identify an image. It's definitely better than the ImageID in this case, but still doesn't achieve the same goal.

**Comment by calavera** [comment] 2016-02-10 18:01
It shows the tag if you start the container with a tag, but you might end up with the same issue

```
Feb 10 13:00:18 docker-test-interactive docker/syslog-test-2/busybox:latest/07f40e2fa66f[29887]:     1     0 root     R     1196  0.0   7  0.0 top#015#033[H#033[JMem: 1296928K used, 15136988K free, 408K shrd, 211832K buff, 811988K cached
Feb 10 13:00:18 docker-test-interactive docker/syslog-test-2/busybox:latest/07f40e2fa66f[29887]: CPU:  0.0% usr  0.0% sys  0.0% nic  100% idle  0.0% io  0.0% irq  0.0% sirq
Feb 10 13:00:18 docker-test-interactive docker/syslog-test-2/busybox:latest/07f40e2fa66f[29887]: Load average: 0.00 0.01 0.05 1/150 11
Feb 10 13:00:18 docker-test-interactive docker/syslog-test-2/busybox:latest/07f40e2fa66f[29887]:
```

**Comment by vikstrous** [comment] 2016-02-10 18:21
Hmm.. this is probably why we were using the image id in the first place. Our containers are always started with a specific tag.

**Comment by tiborvass** [comment] 2016-02-11 16:30
@vikstrous so if we added ImageTag would that help? You could construct `{{.ImageName}}/{{.ImageTag}}` right?

**Comment by vikstrous** [comment] 2016-02-11 18:27
@tiborvass Just posting here what we talked about offline: having an ImageTag field is helpful, but I still can't use the ImageName field if it contains a colon.

**Comment by calavera** [comment] 2016-02-12 23:40
What about this?

`{{split .ImageName ":" | join "/"}}`

I'm almost joking, but having basic functions to manipulate strings might be more useful than adding more fields :laughing:

**Comment by vikstrous** [comment] 2016-02-13 02:30
Is this currently possible? If so, that's a great workaround. Otherwise it's much easier to just provide the extra fields than to force users to do string manipulation on the existing fields.

**Closed** 2016-03-10 16:08 UTC
Labels: area/logging, kind/bug, priority/P2
