### ISSUE TITLE
docker pull may return weird errors

### ISSUE THREAD

**Issue by errordeveloper** [docker/docker#31327] opened 2017-02-24 12:40 UTC
**Description**

**Steps to reproduce the issue:**
N/A, it's sounds like a Docker Hub flake.

**Describe the results you received:**

```
> docker pull weaveworks/scope:1.2.1
Pulling...
error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.
```

**Describe the results you expected:**

No error, or a more descriptive error, e.g. "Docker Hub may be down at the moment, sorry!".

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 49
 Running: 12
 Paused: 0
 Stopped: 37
Images: 259
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: K2QX:AQH2:WZEG:N7UQ:S57E:775X:PB3C:RH7T:3IYC:6RRJ:GUMP:447H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 112
 Goroutines: 99
 System Time: 2017-02-24T12:39:55.289728827Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: errordeveloper
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for Mac

**Comment by thaJeztah** [comment] 2017-02-24 13:04
ping @joegross ptal

**Comment by halldorh** [comment] 2017-02-24 14:30
We have seen that 10-15 times in the last 3 hours from VMs (droplets) in Amsterdam when pulling from docker hub. docker 1.13.0

```Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false```

**Comment by thaJeztah** [comment] 2017-02-24 14:44
@halldorh thanks for reporting; I encountered the same issue once yesterday. They suspected an issue with Amazon CloudFront, so it may be location specific. It's not a bug in the docker "engine", but I'll keep this issue open for visibility; please comment if the situation gets worse, I raised the issue internally. Haven't heard if they got more reports, but will post here if I get information.

**Comment by shouze** [comment] 2017-02-24 18:23
I have it everytime since about 1 hours (located in south of France). Is there a way to temporarly force some other DNS resolution to docker hub S3/Cloudfront servers? I'm stucked.

**Comment by thaJeztah** [comment] 2017-02-24 19:07
I'm not sure there's a way to do that, I guess it's automatically done based on location :disappointed:

Just checked with the team, and they're all hands on deck looking into the issue. I think they're in a support session with AWS / CloudFront

**Comment by shouze** [comment] 2017-02-24 19:09
Ok thx @thaJeztah it's back to normal for me for information.

**Comment by thaJeztah** [comment] 2017-02-24 19:57
Thanks for the update! That's part of the problem; they don't have a way to reproduce the issue; it occurs "sometimes"

**Comment by thaJeztah** [comment] 2017-02-28 18:16
Thanks for the ping @shouze, I heard the original issue was resolved; I _did_ see a message here http://status.aws.amazon.com, but that's a different region. I'll check if the team knows anything (can't upload a screenshot, because apparently GitHub uses S3 as well 😞

**Comment by Numblesix** [comment] 2017-02-28 20:15
Just upgraded to 1.13 and getting some weird errors any idea ? 

```bash
[root@claptrap-fritz-box haproxy-nodejs-docker]# docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: manifest for hello-world:latest not found.
See 'docker run --help'.
[root@claptrap-fritz-box haproxy-nodejs-docker]# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:41:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:41:33 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment] 2017-02-28 20:16
Yes, there's a full outage of s3, which results in Docker Hub having issues as well; see https://status.docker.com

**Comment by ripcurld0** [comment] 2017-03-05 21:44
@thaJeztah can we close it?

**Comment by thaJeztah** [comment] 2017-03-05 22:26
oh, yes, all issues should be resolved

**Closed by thaJeztah** 2017-03-05 22:26 UTC
Labels: area/distribution, platform/desktop, version/1.13
