### ISSUE TITLE
docker tmux vertical split separator

### ISSUE THREAD

**Issue by a93ushakov** [docker/docker#20043] opened 2016-02-05 18:24 UTC
docker 1.9.1, debian 8

It does not display properly the tmux  vertical separation line.

```sh
docker run -ti -e TERM=xterm-color debian /bin/bash -c "apt update && apt install -y tmux && tmux -2 new-session -d -s test && tmux split-window -d -t 0 -h && tmux attach -t test"
```

Can you help to fix it?

**Comment by a93ushakov** [comment] 2016-02-07 11:44
`docker version`
```sh
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

```

**Comment by thaJeztah** [comment] 2016-02-16 00:19
Is this similar to https://github.com/docker/docker/issues/15373?

**Comment by MHBauer** [comment] 2016-02-22 21:17
Yes, dup. Works on osx client -> linux server, not on linux client-> linux server.

**Comment by thaJeztah** [comment] 2016-02-23 00:43
closing this as a duplicate of https://github.com/docker/docker/issues/15373, please continue the discussion there

**Closed by thaJeztah** 2016-02-23 00:43 UTC
