### ISSUE TITLE
"failed to hande address change" on swarm manager reboot (5 nodes, 3 managers) - never recovers, causes: "grpc: the connection is unavailable"

### ISSUE THREAD

**Issue by ventz** [docker/docker#30455] opened 2017-01-25 22:24 UTC
**Description**
In a 5 node swarm cluster:
* 3 managers (Nodes: A, B, C)
* 2 workers (Nodes: D, and E)

All of the nodes are on rfc1918 space with 1-1 mapping externally.

When initing the swarm, on node A by:
```docker swarm init --advertise-addr A-PUBLIC-IP --listen-addr a-10x:2377```

When joining nodes (managers) B and C:
```
docker swarm join \
--token SWMTKN-manager-token \
--advertise-addr B-PUBLIC-IP --listen-addr 0.0.0.0:2377 A-PUBLIC-IP:2377

and

docker swarm join \
--token SWMTKN-manager-token \
--advertise-addr C-PUBLIC-IP --listen-addr 0.0.0.0:2377 A-PUBLIC-IP:2377
```

When joining nodes (workers) D, and E:
```
docker swarm join \
--token SWMTKN-worker-token \
--advertise-addr D-PUBLIC-IP --listen-addr 0.0.0.0:2377 A-PUBLIC-IP:2377

and

docker swarm join \
--token SWMTKN-worker-token \
--advertise-addr E-PUBLIC-IP --listen-addr 0.0.0.0:2377 A-PUBLIC-IP:2377
```

When you reboot any of the managers (including a non-leader), you get a message that:

```
level=warning msg="detected address change for 412c742ead14c77f (PUBLIC-IP-of-REBOOTED-NODE:2377 -> PRIVATE-GATEWAY-OF-NODES:2377)" raft_id=321d772168243d4b
```

**Steps to reproduce the issue:**
1. Follow steps above to create swarm
2. Reboot any manager.
3. On reboot, even though it comes back up, it will not join the swarm/will not do a "docker node ls" and will error out.

**Describe the results you received:**
```
level=warning msg="detected address change for 412c742ead14c77f (A-publicIP:2377 -> A-private-gateway:2377)" raft_id=321d772168243d4b
```

An example:
```
level=warning msg="detected address change for 412c742ead14c77f (104.281.24.14.23:2377 -> 10.10.10.1:2377)" raft_id=321d772168243d4b
```

**Describe the results you expected:**
Re-join/continue operation

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: eudw4ig52prutxf0dn0wv4209
 Is Manager: true
 ClusterID: y942ys43rlguyzenkv69naicc
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: PUB-IP-NODE-A
 Manager Addresses:
  PUB-IP-NODE-A:2377
  PUB-IP-NODE-B:2377
  PUB-IP-NODE-C:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859 GiB
Name: $hostname
ID: 4RZN:TIYL:SE4A:OLD6:MPOU:XGT7:7UYX:PRZ4:YXUT:BELD:Y24H:EHXE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 nfs=yes
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is running on a VMs on physical hardware at a datacenter. The VM is feeding rfc1918 space, and has 1-1 mapping with public IPs.

Due to some of the VMs being at other datacenters, the PUBLIC IP has to be used for the --advertise-addr.

2 of the nodes are are behind the same switch -- thus, they can reach each other directly on their 10x space, and this seems to be part of the issue that triggers this bug.

**Comment by ventz** [comment] 2017-01-25 22:33
This seems to be the case in a 5 node "all manager" swarm too.

If someone can confirm this, but it seems like a pretty bad bug.
I can reproduce it in different environments.

The key being joining 2 nodes that are on private IPs using their public (1-1 nat) IPs, since you have a 3rd (or Nth) node somewhere else that actually needs the public IPs to communicate.

**Comment by aaronlehmann** [comment] 2017-01-25 23:21
What is `A-private-gateway` here?

The log message means that the manager which emitted that log message got an incoming connection from `A-private-gateway`, which identified itself as the rebooted node. The next step this manager takes is to try connecting to `A-private-gateway:2377`, and issuing a health check. If this succeeds, the address of the node will be updated. Nothing should change if `A-private-gateway:2377` does not accept the connection.

You mentioned that two of the nodes can communicate using the private IPs, and the third needs to use public IPs. Perhaps the third one is the leader at first, but after the reboot, one of the other two becomes the leader, and it sees (and propagates) a private IP address that can't be used by all managers.

If it's at all possible to avoid having a setup where some managers see different source addresses than other managers, I'd highly recommend that. I'm curious why you are running one manager on a separate network from the others.

**Comment by ventz** [comment] 2017-01-25 23:48
@aaronlehmann  - Node A (call it: 10.10.101.11) and Node B (call it: 10.10.101.12) are in the same datacenter hanging off the same switch. So the "A-private-gateway" is "10.10.101.1" in this case.

I setup a few clusters just to test on. The leader is node A (i run init always on the 1st node). Then I join the B (second node - same DC), and then I join C (different DC). After that I join D (worker, 3rd DC), and then E (worker, 4th DC).

I tested the following:
* rebooting a manager, the leader
* rebooting a manager that's not the leader
* promoting the other 2 to managers in order to have 5 managers, in case the RAFT consensus with 3 was an issue.

^ all of these produced the same results.

What confuses me is that after announcing the advertise IP to the public, that sticks (if you inspect from the other nodes), and it clearly shows up everywhere. Why does it even attempt the private gateway? Also - upon demoting and promoting the rebooted node from any other manager, it fixes the issue instantly -- until the next reboot.

**Comment by aaronlehmann** [comment] 2017-01-26 00:05
It would be interesting to run tcpdump on the leader while rebooting one of the followers. I suspect you would see an incoming connection from `10.10.101.1` to `10.10.101.11:2377`. Perhaps there is some issue with the 1-to-1 NAT that only shows up after a reboot. If we can confirm that the leader is seeing a connection from `10.10.101.1`, we can start digging into why that happens.

**Comment by ventz** [comment] 2017-01-26 00:05
@aaronlehmann By the way - how would you join 3 or more nodes that are all accessible via public IPs, but at least 2 of them sit behind the same switch and are accessible via L2 (and direct local IP)?

I am assuming (will test next) that --advertise-addr on the local interface (instead of via IP) will not work because it seems that it will then submit the LOCAL IP address to the remote hosts, and they won't be able to connect?

**Comment by aaronlehmann** [comment] 2017-01-26 00:21
> By the way - how would you join 3 or more nodes that are all accessible via public IPs, but at least 2 of them sit behind the same switch and are accessible via L2 (and direct local IP)?

I remember dealing with a similar situation a long time ago, and I found a way to use the Linux networking settings to force packets through the gateway. I think turning off `accept_redirects` may have been part of it, but unfortunately I don't quite remember.

https://www.frozentux.net/ipsysctl-tutorial/chunkyhtml/theconfvariables.html

**Comment by ventz** [comment] 2017-01-26 00:24
@aaronlehmann Yep - and here's the issue when using the --advertise-addr on the local interface:

(on the remote DC node C) # docker info
...
# nodes in swarm
10.10.101.11:2377
10.10.101.12:2377
C-PUBLIC-IP:2377

So then the same error happens in reverse:

level=warning msg="detected address change for 103569a5fef9ee53 (10.10.101.11:2377 -> A-PUBLIC-IP:2377)"

Looking at the initial issue, I think there is a problem somewhere between the "ip change detection" vs the "advertised ip", and then handling leaves.

Open to any suggestions, and I can test any scenarios if this will help bring more light onto this.

## For the tcpdump, here's the info:
I created a new 3 node cluster (A, B, and just C)
```
ID                           HOSTNAME    STATUS  AVAILABILITY  MANAGER STATUS
4c2p6nvbj2mulvdza2uh1v826    nodeC         Ready   Active        Reachable
b9sbx2gunya4zg9ymkhlejwy1 *  nodeA  Ready   Active        Leader
na49pkcqv0dkujv6p5uxjd61i    nodeB  Ready   Active        Reachable
```

Actual tcpdump from the leader (nodeA in t his case):
```
NOTE:
A = 10.10.101.11 = PUBLIC-NODE-A
B = 10.10.101.12 = PUBLIC-NODE-B
C = some-private = PUBLIC-NODE-C (cloud provider)

19:23:08.966709 IP 10.10.101.1.48146 > 10.10.101.11.2377: Flags [P.], seq 2686169980:2686170067, ack 2395643929, win 340, options [nop,nop,TS val 2348986 ecr 1403783], length 87
19:23:08.967201 IP 10.10.101.11.2377 > 10.10.101.1.48146: Flags [P.], seq 1:65, ack 87, win 294, options [nop,nop,TS val 1405143 ecr 2348986], length 64
19:23:08.967263 IP 10.10.101.11.2377 > 10.10.101.1.48146: Flags [P.], seq 65:105, ack 87, win 294, options [nop,nop,TS val 1405143 ecr 2348986], length 40
19:23:08.967976 IP 10.10.101.1.48146 > 10.10.101.11.2377: Flags [.], ack 65, win 340, options [nop,nop,TS val 2348986 ecr 1405143], length 0
19:23:08.968104 IP 10.10.101.1.48146 > 10.10.101.11.2377: Flags [.], ack 105, win 340, options [nop,nop,TS val 2348986 ecr 1405143], length 0
19:23:09.091803 IP 10.10.101.11.47836 > PUBLIC-NODE-C.2377: Flags [P.], seq 951736426:951736537, ack 1021783734, win 251, options [nop,nop,TS val 1405174 ecr 61532597], length 111
19:23:09.092054 IP 10.10.101.11.53678 > PUBLIC-NODE-B.2377: Flags [P.], seq 319303231:319303349, ack 1973478186, win 251, options [nop,nop,TS val 1405174 ecr 2348767], length 118
19:23:09.093466 IP PUBLIC-NODE-B.2377 > 10.10.101.11.53678: Flags [P.], seq 1:55, ack 118, win 699, options [nop,nop,TS val 2349017 ecr 1405174], length 54
19:23:09.093529 IP 10.10.101.11.53678 > PUBLIC-NODE-B.2377: Flags [.], ack 55, win 251, options [nop,nop,TS val 1405175 ecr 2349017], length 0
19:23:09.093550 IP PUBLIC-NODE-B.2377 > 10.10.101.11.53678: Flags [P.], seq 55:95, ack 118, win 699, options [nop,nop,TS val 2349017 ecr 1405174], length 40
19:23:09.093579 IP 10.10.101.11.53678 > PUBLIC-NODE-B.2377: Flags [.], ack 95, win 251, options [nop,nop,TS val 1405175 ecr 2349017], length 0
19:23:09.093793 IP 10.10.101.1.48148 > 10.10.101.11.2377: Flags [P.], seq 1648619295:1648619401, ack 3733567878, win 317, options [nop,nop,TS val 2349017 ecr 1404925], length 106
19:23:09.094669 IP 10.10.101.11.2377 > 10.10.101.1.48148: Flags [P.], seq 1:55, ack 106, win 276, options [nop,nop,TS val 1405175 ecr 2349017], length 54
19:23:09.094855 IP 10.10.101.11.2377 > 10.10.101.1.48148: Flags [P.], seq 55:95, ack 106, win 276, options [nop,nop,TS val 1405175 ecr 2349017], length 40
19:23:09.095436 IP 10.10.101.1.48148 > 10.10.101.11.2377: Flags [.], ack 55, win 317, options [nop,nop,TS val 2349018 ecr 1405175], length 0
19:23:09.095498 IP 10.10.101.1.48148 > 10.10.101.11.2377: Flags [.], ack 95, win 317, options [nop,nop,TS val 2349018 ecr 1405175], length 0
19:23:09.103703 IP PUBLIC-NODE-C.2377 > 10.10.101.11.47836: Flags [P.], seq 1:55, ack 111, win 602, options [nop,nop,TS val 61532847 ecr 1405174], length 54
19:23:09.103760 IP PUBLIC-NODE-C.2377 > 10.10.101.11.47836: Flags [P.], seq 55:95, ack 111, win 602, options [nop,nop,TS val 61532847 ecr 1405174], length 40
19:23:09.103920 IP PUBLIC-NODE-C.47558 > 10.10.101.11.2377: Flags [P.], seq 3542833755:3542833861, ack 402946388, win 339, options [nop,nop,TS val 61532847 ecr 1404928], length 106
19:23:09.104062 IP 10.10.101.11.47836 > PUBLIC-NODE-C.2377: Flags [.], ack 95, win 251, options [nop,nop,TS val 1405177 ecr 61532847], length 0
19:23:09.104532 IP 10.10.101.11.2377 > PUBLIC-NODE-C.47558: Flags [P.], seq 1:55, ack 106, win 276, options [nop,nop,TS val 1405178 ecr 61532847], length 54
19:23:09.104798 IP 10.10.101.11.2377 > PUBLIC-NODE-C.47558: Flags [P.], seq 55:95, ack 106, win 276, options [nop,nop,TS val 1405178 ecr 61532847], length 40
19:23:09.116116 IP PUBLIC-NODE-C.47558 > 10.10.101.11.2377: Flags [.], ack 55, win 339, options [nop,nop,TS val 61532850 ecr 1405178], length 0
19:23:09.116370 IP PUBLIC-NODE-C.47558 > 10.10.101.11.2377: Flags [.], ack 95, win 339, options [nop,nop,TS val 61532850 ecr 1405178], length 0
19:23:10.091812 IP 10.10.101.11.53678 > PUBLIC-NODE-B.2377: Flags [P.], seq 118:229, ack 95, win 251, options [nop,nop,TS val 1405424 ecr 2349017], length 111
19:23:10.091923 IP 10.10.101.11.47836 > PUBLIC-NODE-C.2377: Flags [P.], seq 111:222, ack 95, win 251, options [nop,nop,TS val 1405424 ecr 61532847], length 111
19:23:10.093256 IP PUBLIC-NODE-B.2377 > 10.10.101.11.53678: Flags [P.], seq 95:149, ack 229, win 699, options [nop,nop,TS val 2349267 ecr 1405424], length 54
19:23:10.093304 IP 10.10.101.11.53678 > PUBLIC-NODE-B.2377: Flags [.], ack 149, win 251, options [nop,nop,TS val 1405425 ecr 2349267], length 0
19:23:10.093330 IP PUBLIC-NODE-B.2377 > 10.10.101.11.53678: Flags [P.], seq 149:189, ack 229, win 699, options [nop,nop,TS val 2349267 ecr 1405424], length 40
19:23:10.093352 IP 10.10.101.11.53678 > PUBLIC-NODE-B.2377: Flags [.], ack 189, win 251, options [nop,nop,TS val 1405425 ecr 2349267], length 0
19:23:10.093688 IP 10.10.101.1.48148 > 10.10.101.11.2377: Flags [P.], seq 106:212, ack 95, win 317, options [nop,nop,TS val 2349267 ecr 1405175], length 106
19:23:10.094204 IP 10.10.101.11.2377 > 10.10.101.1.48148: Flags [P.], seq 95:149, ack 212, win 276, options [nop,nop,TS val 1405425 ecr 2349267], length 54
19:23:10.094312 IP 10.10.101.11.2377 > 10.10.101.1.48148: Flags [P.], seq 149:189, ack 212, win 276, options [nop,nop,TS val 1405425 ecr 2349267], length 40
19:23:10.095059 IP 10.10.101.1.48148 > 10.10.101.11.2377: Flags [.], ack 149, win 317, options [nop,nop,TS val 2349268 ecr 1405425], length 0
19:23:10.095204 IP 10.10.101.1.48148 > 10.10.101.11.2377: Flags [.], ack 189, win 317, options [nop,nop,TS val 2349268 ecr 1405425], length 0
19:23:10.103934 IP PUBLIC-NODE-C.2377 > 10.10.101.11.47836: Flags [P.], seq 95:149, ack 222, win 602, options [nop,nop,TS val 61533097 ecr 1405424], length 54
19:23:10.104040 IP PUBLIC-NODE-C.2377 > 10.10.101.11.47836: Flags [P.], seq 149:189, ack 222, win 602, options [nop,nop,TS val 61533097 ecr 1405424], length 40
19:23:10.104051 IP PUBLIC-NODE-C.47558 > 10.10.101.11.2377: Flags [P.], seq 106:212, ack 95, win 339, options [nop,nop,TS val 61533097 ecr 1405178], length 106
19:23:10.104128 IP 10.10.101.11.47836 > PUBLIC-NODE-C.2377: Flags [.], ack 189, win 251, options [nop,nop,TS val 1405427 ecr 61533097], length 0
19:23:10.104627 IP 10.10.101.11.2377 > PUBLIC-NODE-C.47558: Flags [P.], seq 95:149, ack 212, win 276, options [nop,nop,TS val 1405428 ecr 61533097], length 54
19:23:10.104760 IP 10.10.101.11.2377 > PUBLIC-NODE-C.47558: Flags [P.], seq 149:189, ack 212, win 276, options [nop,nop,TS val 1405428 ecr 61533097], length 40
19:23:10.116103 IP PUBLIC-NODE-C.47558 > 10.10.101.11.2377: Flags [.], ack 149, win 339, options [nop,nop,TS val 61533100 ecr 1405428], length 0
19:23:10.116266 IP PUBLIC-NODE-C.47558 > 10.10.101.11.2377: Flags [.], ack 189, win 339, options [nop,nop,TS val 61533100 ecr 1405428], length 0
```

**Comment by ventz** [comment] 2017-01-26 00:42
Tried:
net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.all.accept_redirects=0

But it didn't seem to make a difference

@aaronlehmann  - This is the part that seems like a bug to me:

```
Jan 25 19:32:55 nodeA dockerd[5669]: time="2017-01-25T19:32:55.091721399-05:00" level=warning msg="detected address change for 64fc2ab23201d770 (PUBLIC-NODE-B:2377 -> 10.10.101.1:2377)" raft_id=14da52bea9767809
Jan 25 19:32:55 nodeA dockerd[5669]: time="2017-01-25T19:32:55.093542977-05:00" level=error msg="failed to hande address change" error="64fc2ab23201d770 failed health check at observed address 10.10.101.1:2377: rpc error: code = 14 desc = grpc: the connection is unavailable" raft_id=14da52bea9767809
```

When Node B reboots, after it comes back it should re-announce itself using the IP set in the --advertise-addr. That part I don't understand.

**Comment by aaronlehmann** [comment] 2017-01-26 00:57
Node B isn't announcing its IP address. It's just connecting to another node, and that other node sees that the connection came from a different IP address than it expected. In this case, it updates the IP address it has on file, because it's important that the managers know each others' current addresses at all times. This was intended to be a lightweight way to handle address changes, which doesn't need heavy coupling to the OS to detect that the IP address has changed.

If you can find a way to make sure packets are always routed through the NAT gateway, that should solve the problem. I believe this is possible, but unfortunately I don't know the steps offhand. I think some of the arp settings may be involved. The fact that VMs are involved may also make things more complex, since there is probably some switching magic going on at the hypervisor level.

**Comment by ventz** [comment] 2017-01-26 03:03
I guess at the end of the day I wish it would go one way or another. If it registered the IP it sees, it should work locally w/ the local IPs, and remotely with the NATed public IPs. It seems to be doing half and half right now -- where it's taking the private IP if you advertise with it/on it (as a negative when remote hosts are involved), but at the same time, it uses the local IP when you force public IPs locally -- again, as a negative. Would it be possible to add a flag to override "detected" ip with the "provided ip"?

**Comment by ventz** [comment] 2017-01-26 17:44
@aaronlehmann Funny solution (which feels "dirty" but it works) -- adding an alias interface on the systems with the PUBLIC IP of each 1-1 node, and then NOT advertising an IP when creating or joining the swarm fixes this.

It's cheating because you are essentially stapling the public IP on L2 and hopping the L2 will "route it" when you ask for it. But it works.

**Comment by ventz** [comment] 2017-01-28 23:06
@aaronlehmann Aaron, after debugging this with a team of people for a few days now, we are pretty certain that it's a bug.

We have noticed a similar issue with 3rd party cloud environments. You join multiple hosts as managers, and eventually the Nth+1 (usually 4th or so) will pick up the private IP of one of the previous managers, and since it can't route to it, everything starts failing.

Ex:

```
Jan 28 17:51:38 somehostname dockerd[1118]: time="2017-01-28T17:51:38.310312694-05:00" level=warning msg="detected address change for 3981dcdeb7d72b41 (PUBLIC-CLOUD-IP:2377 -> 10.49.51.12:2377)" raft_id=65245ceb035c2d77

time="2017-01-28T17:57:32.945785065-05:00" level=error msg="Failed to join memberlist [10.49.51.12] on retry: 1 error(s) occurred:\n\n* Failed to join 10.49.51.12: dial tcp 10.49.51.12:7946: getsockopt: no route to host"
```

That host joined swarm advertise only on its public IP.

I think this is a bigger issue on how docker seems to be detecting the address "changes".

**Comment by ventz** [comment] 2017-01-28 23:18
And here's the last piece of useful info:

If you join just Amazon nodes, on the 3rd one you get:
```
Node Address: PUB#3 <-- this node
 Manager Addresses:
  **0.0.0.0:2377** <--- this node also creates this!
  PUB#2:2377
  PUB#1:2377
  PUB#3:2377
```

This is simply by doing:
```
docker swarm join \
--token $token \
--advertise-addr PUB#3 PUB#1:2377
```
(and PUB#1 being where you initialized the swarm net)

This point, we are convinced that this is a bug.

**Comment by aaronlehmann** [comment] 2017-01-30 18:12
Hi again @ventz, thank again for providing detailed updates. It sounds like this is a real pain point, and we should try to provide some relief.

>  Manager Addresses:
>  0.0.0.0:2377 <--- this node also creates this!

I don't think this is related. This address is added for bootstrapping the first manager. We really shouldn't list it as a manager address. However, this should not have an impact on address changes. Also, starting from 1.14, Docker won't use 0.0.0.0 at all.

> We have noticed a similar issue with 3rd party cloud environments. You join multiple hosts as managers, and eventually the Nth+1 (usually 4th or so) will pick up the private IP of one of the previous managers, and since it can't route to it, everything starts failing.

The only explanation I can think of is that the cloud provider does the NAT in a way that exposes the private IP addresses when the source node can reach the destination over the private network. Are you able to disclose which cloud provider this is? I didn't notice similar problems when I tested on AWS.

Again, packet captures are helpful for figuring out what's actually happening. If node A actually receives a connection with node B's private IP as the source address, then swarm is behaving as expected (but unfortunately, not in a very usable way under the circumstances).

I'll chat with some of the other maintainers to come up with ideas of what we can change in the next version to avoid these problems.

**Comment by ventz** [comment] 2017-01-30 18:29
@aaronlehmann Thanks.

Is there a way to subscribe to more information about the plans around these components (swarm specifically)? I am very interested in learning more/staying on top of/trying out some of the upcoming changes in 1.14.

We are more than willing to contribute time and local resources in testing/debugging/trying experimental builds/etc.

Noticed another issue, but I think it's related 100% to the IP/manager part.

Here's the summary anyway:
When creating an encrypted overlay, it sometimes does not make the network available on every manager/worker (not that it doesn't show up on the workers -- that's normal until it's needed by a container/task). At first we thought it might be esp (proto 50) on the firewalls, but that was again any/any from and to the networks. It turned out to be related to the IPs published for the managers in the docker info. For example, that 0.0.0.0 was in the list depending on how you init and then join the swarm. I tried a few things:
1.) for the INIT: using the local IP (must) for the --listen-addr when creating it
2.) for the JOIN: using the local IP vs the interface name vs leaving it blank (which just uses 0.0.0.0 I think)

We noticed that for #1, you have to do it because otherwise it can't find the public advertise IP
However, for #2 - using the local IP or the interface is what actually caused the problems. Leaving it blank, and thus using 0.0.0.0 -- ends up pushing out that 0.0.0.0, but that causes less problems. If the swarm node will not respond/distribute the vxlan, rebooting it seems to fix the issue.

**Comment by aaronlehmann** [comment] 2017-01-30 18:41
> Is there a way to subscribe to more information about the plans around these components (swarm specifically)? I am very interested in learning more/staying on top of/trying out some of the upcoming changes in 1.14.

One way is to monitor the https://github.com/docker/swarmkit GitHub repository, where a lot of the swarm development takes place. Also, I believe there is a testers mailing list (cc @thaJeztah).

> We are more than willing to contribute time and local resources in testing/debugging/trying experimental builds/etc.

Thanks! We'd really appreciate that.

> Noticed another issue, but I think it's related 100% to the IP/manager part.

I'd recommend filing a separate issue for this to make sure it gets looked at.

**Comment by aaronlehmann** [comment] 2017-01-30 18:48
After some discussion, I think the best way forward with the address change issue is to disable automatic address change detection in the next Docker 1.13 patch release, and aim to reenable it in 1.14 with additional safeguards (perhaps, for example, allowing a manager to have multiple addresses associated with it). The address change handling is not particularly useful on its own, because dynamic addresses are not supported by overlay networking, but they were intended as a best-effort way to avoid losing quorum accidentally, and an incremental first step towards full dynamic addressing support. I'll be opening a PR in swarmkit to disable the feature for the moment.

**Comment by LK4D4** [comment] 2017-01-30 18:54
@ventz That's cool that you found this. Honestly,  I didn't even think about such possibility before :)

**Comment by ventz** [comment] 2017-01-30 19:08
@aaronlehmann that's awesome! (thanks!)

I remember seeing/reading something about the change from 1.12 -> 1.13 about the auto detection, and  I thought at the time that it sounded awesome to have intelligence around it. The one thing I would add is that --advertise-addr should really override all other IP announcements. If someone is specifying the --advertise-addr, it's usually because they want to utilize a different IP, and the only use case where that would work would be public/NAT/elastic/etc. In that case, if it doesn't get back to the manager, it's on them.

@LK4D4 From what we have seen, it's much more common in the enterprise environments -- a "hybrid" if you will between local resources and external/3rd party. Lately, more and more of the external/3rd party are "cloud" (specifically, AWS), but we still see a lot of places with their own remote datacenters. A lot of these people do not have site to site VPNs which is interesting. Similar for the smaller setups with AWS -- they rely on public path out. A lot of customers seem interested in the portability behind swarm too, that it allowing them to hop into a new/leased environment, and without having a complicated network setup -- be able to establish an overlay mesh on the fly, and back to resources they own.

**Comment by thaJeztah** [comment] 2017-01-30 19:29
@ventz if you're interested in being on the testers mailinglist, send me an e-mail at sebastiaan _at_ docker _dot_ com, and I'll add you there. Overall, reporting issues on GitHub would be still the same, but we occasionally reach out to individual testers (or companies) on the testers list.

If you can provide some background, the company you're working for, and how you're using docker, that'd be cool (if you're able to disclose of course)

**Comment by thaJeztah** [comment] 2017-03-02 16:44
Should be fixed by https://github.com/docker/docker/issues/30579, but didn't auto-close

**Closed by thaJeztah** 2017-03-02 16:44 UTC
Labels: area/swarm, version/1.13
