### ISSUE TITLE
Occasional failure to start container with failing to write to cgroup.procs error

### ISSUE THREAD

**Issue by delcypher** [docker/docker#31230] opened 2017-02-21 18:16 UTC
**Description**

I'm using a custom written python script that launches and destroys many docker containers using the [docker-py](https://github.com/docker/docker-py) interface. I am using quite an old version of docker-py (1.6.0) unfortunately but with a reasonably new version of Docker.

Very occasionally I get back errors from the Docker daemon when trying to start a container 

```
Traceback (most recent call last):

  File "/home/schemmel/venv/lib/python3.5/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()

  File "/home/schemmel/venv/lib/python3.5/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.24/containers/0eecc9b405968c12d7b1c16d16c39c3d0c174e23c75ee5720aff08c617d1203f/start


During handling of the above exception, another exception occurred:


docker.errors.APIError: 500 Server Error: Internal Server Error ("b'{"message":"oci runtime error: process_linux.go:258: applying cgroup configuration for process caused \\"failed to write 74341 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/0eecc9b405968c12d7b1c16d16c39c3d0c174e23c75ee5720aff08c617d1203f/cgroup.procs: invalid argument\\""}'")
```

**Steps to reproduce the issue:**

I can't provide this because I do not have a reliable way to reproduce the issue. It only happened once during the creation and destruction of 1376 containers. I know this is really unhelpful but the best I can do is document what I have observed in the hope that someone might know why this error occurred.

**Describe the results you received:**

Occasionally containers fail to start with the error 

```
oci runtime error: process_linux.go:258: applying cgroup configuration for process caused 
"failed to write 74341 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/0eecc9b405968c12d7b1c16d16c39c3d0c174e23c75ee5720aff08c617d1203f/cgroup.procs: invalid argument"
```

**Describe the results you expected:**

I expect the container to start without this error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.12.5, build 7392c3b0ce
```

**Output of `docker info`:**

```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 65
Server Version: 1.12.5
Storage Driver: btrfs
 Build Version: Btrfs v4.8.5
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.8.13-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 251.8 GiB
Name: sloth
ID: <redacted>
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Run on physical machine with Arch Linux host.

**Comment by dead10ck** [comment] 2017-02-23 19:08
Can confirm this is happening to me as well.

**docker info**
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 92
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.11-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.493 GiB
Name: opendns-arch-x1
ID: JHNX:UIB6:5FDK:MV7R:IKZS:H7LX:WOMN:QXR3:VF4B:EYJD:VVLX:WWXF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by sheuser** [comment] 2017-02-24 15:13
Same here using docker-compose on Arch Linux.
````
[...]
Step 15/21 : RUN berks vendor --berksfile ./Berksfile ./chef/cookbooks
 ---> Running in bde6e24943c9
container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"failed to write 30266 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/bde6e24943c973211009cf2af4983b2b74c1e218d0d9d35cd486bf2bd1237e74/cgroup.procs: invalid argument\""
````
**`docker version`**
````
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
````
**`docker info`**
````
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 249
Server Version: 1.13.1
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.11-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.683 GiB
Name: osmium
ID: 5VO2:WVBO:JED2:LMZL:WDSA:DDNP:QYSW:UFGG:236L:EGKS:RSMM:ZXKD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
````
**`docker-compose version`**
````
docker-compose version 1.11.2, build dfed245b
docker-py version: 2.1.0
CPython version: 3.6.0
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
````

**Comment by thaJeztah** [comment] 2017-02-24 15:33
Looks like all the failures here are with Arch linux. We currently don't support Arch linux, and don't have packages for that distro (Arch linux is a "bleeding edge" distro, and is known to break docker quite frequently).

Given that the docker packages for Arch linux are packaged, and maintained by Arch, I'll close this issue, and suggest to open an issue in their issue tracker

**Closed by thaJeztah** 2017-02-24 15:33 UTC
Labels: area/runtime

**Comment by sheuser** [comment] 2017-02-24 15:44
Actually, I was using the official Docker builds (AUR `docker-bin` package) – But I guess this may indeed stem from some Arch-specific quirk.
Let's just hope this does not come back to bite us when other distributions update their software.

**Comment by thaJeztah** [comment] 2017-02-24 15:47
Unfortunately, Arch can be a "running target", which is the reason we don't have packages for it

**Comment by gralamin** [comment] 2017-07-24 16:19
I have reproduced this issue once on a Ubuntu 16.04 VM on an ESX host:
**``uname -a``**
```
Linux tfm-qbrt-queue 4.8.0-54-generic #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**``cat lsb-release``**
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

**``docker version``**
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**``docker info``**
```
Containers: 13
 Running: 13
 Paused: 0
 Stopped: 0
Images: 145
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 625
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-54-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67GiB
Name: tfm-qbrt-queue
ID: BDWX:WVHB:7C3V:LWNR:T3JP:4SD5:ISWI:CLXI:6RLJ:3AOM:4RSD:35ZE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

I use a custom script to wrap docker, without using docker-py (for unimportant corporate reasons). In my case, the docker container was successfully created, but this error was hit when running 'docker exec'

```
        stdout = b'rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:262: starting container process caused "process_linux.go:86: adding pid 6663 to cgroups caused \\"failed to write 6663 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/591f3f2c9cea213cdb82ad9bde7c0b68c485ad3d2ec53b6423db6e57dcea1f5f/cgroup.procs: invalid argument\\""\n\r\n'
        retcode = 126
        popenargs = (['docker', 'exec', 'correct_container_name', 'ip', 'addr', 'add', '172.16.5.1/24', 'dev', 'IO01'],)
```

**Comment by shuaichang** [comment] 2017-08-23 23:49
We are seeing the same behavior

```
Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup configuration for process caused \\\"failed to write 16773 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/008225a5b1861e75443f40db05470a12b4b8aad4e0780b236c90700b38076341/cgroup.procs: invalid argument\\\"\"\n"
```

docker info Kernel Version is `Kernel Version: 4.11.4-1.el7.elrepo.x86_64`

**Comment by rlees85** [comment] 2017-08-28 17:56
Affecting me also. Arch user, but going to watch this thread for when other distros get broken too.

**Comment by Dolbager** [comment] 2017-09-13 16:32
Some times containers which many time restarts crashed with same error:
```
container_linux.go:262: starting container process caused "process_linux.go:261: applying cgroup configuration for process caused \"failed to write 15181 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/126c6401b691734ebde6c92179c6033a6c5b568d678c24338951d54f8f446806/cgroup.procs: invalid argument\""
```
**docker version**
```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**docker info**
```
Containers: 52
 Running: 52
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.12.9-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.68GiB
Name: proc
ID: XLQG:R3FF:34GN:H4BE:FZ2G:OEEM:QO6C:VCEJ:Y7RJ:YGXB:KORN:FRHU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**os**
```
centos 7 with mainline kernel
4.12.9-1.el7.elrepo.x86_64 #1 SMP Fri Aug 25 16:46:00 EDT 2017
4.12.8-1.el7.elrepo.x86_64 #1 SMP Thu Aug 17 09:11:11 EDT 2017
```

**Comment by FeepingCreature** [comment] 2017-11-16 15:05
Same issue on Ubuntu 4.13.0-16-lowlatency.

**Comment by vsuharnikov** [comment] 2017-11-29 08:10
Happens rarely on Ubuntu 16.04.3 LTS. Any workarounds?
```
Request error: POST unix://localhost:80/containers/1a282a6f2b717b6af6968d73b010380d49f277514b7e7e4080c027593c890565/start: 500, body: {"message":"oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup configuration for process caused \\\"failed to write 1297 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/1a282a6f2b717b6af6968d73b010380d49f277514b7e7e4080c027593c890565/cgroup.procs: invalid argument\\\"\"\n"}
```

**Comment by jwatte** [comment] 2018-11-12 16:49
Seeing this issue on Ubuntu 18.10.

This thread from another project seems to indicate the problem might have been caused by a new check in the kernel in 4.8, where it doesn't like trying to talk about threads that are newly created but haven't been scheduled yet.
https://github.com/opencontainers/runc/issues/1884

That project ended up working around it at the user level, but it really feels like a kernel problem, if their diagnostic is actually true. When the kernel returns a thread ID to userspace, that thread ID should be accepted back by the kernel.
