### ISSUE TITLE
docker stats reports wrong memory limit

### ISSUE THREAD

**Issue by bobrik** [docker/docker#13064] opened 2015-05-07 19:21 UTC
Container has memory limit set to 64mb, but `docker stats` reports full system memory. Happens for all my containers, [metrics](https://github.com/bobrik/collectd-docker) on memory usage are not very helpful now.

```
web165 ~ # docker inspect -f '{{ .Config.Memory  }}' collectd-mesos-tasks-web165
6.7108864e+07
web165 ~ # docker stats collectd-mesos-tasks-web165 | head -n2
CONTAINER                     CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
collectd-mesos-tasks-web165   0.00%               4.93 MiB/7.79 GiB   0.06%               12.77 MiB/2.472 MiB
```

```
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 4749651
OS/Arch (client): linux/amd64
dServer version: 1.6.0
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 4749651
OS/Arch (server): linux/amd64
web165 ~ # docker info
Containers: 13
Images: 136
Storage Driver: devicemapper
 Pool Name: docker-9:127-9961543-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 6.908 GB
 Data Space Total: 107.4 GB
 Data Space Available: 100.5 GB
 Metadata Space Used: 9.72 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: false
 Library Version: 1.02.88 (2014-08-05)
Execution Driver: native-0.2
Kernel Version: 3.14.18-gentoo
Operating System: Gentoo/Linux
CPUs: 8
Total Memory: 7.79 GiB
Name: web165
ID: WM3Z:52VB:7BAB:6TVK:JS4B:AFOV:FTXV:KEVF:VLHD:WLTZ:A5UV:NBSE
```

cc @crosbymichael

**Comment by dqminh** [comment] 2015-05-08 03:33
@bobrik this is weird. Does the system have memory cgroup mounted ?

**Comment by bobrik** [comment] 2015-05-08 06:52
@dqminh yes, cgroups are mounted and memory limits are enforced.

Looks like docker is using `HostConfig.Memory` as memory limit in stats API, but in problematic containers it is set to 0. At the same time `Config.Memory` is set to the correct value.

I'm using ansible to launch docker containers and it seems that docker-py is doing something that sets only `Config.Memory`, but not `HostConfig.Memory`.

When launching containers with docker cli both `HostConfig.Memory` and `Config.Memory` are set to equal value.

**Comment by bobrik** [comment] 2015-05-08 07:09
Here's create request from ansible:

```
POST /v1.17/containers/create?name=alpine-test HTTP/1.1
Host: localhost
Content-Length: 233
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.4.3 CPython/2.7.5 Linux/3.14.18-gentoo
Connection: keep-alive
Content-Type: application/json

{"Tty": false, "NetworkDisabled": false, "Image": "alpine:3.1", "Cmd": ["sleep", "600"], "StdinOnce": false, "AttachStdin": false, "MemorySwap": 0, "Memory": 67108864, "AttachStderr": false, "AttachStdout": false, "OpenStdin": false}
```

Here's create request from docker cli:

```
POST /v1.18/containers/create?name=alpine-test HTTP/1.1
Host: /var/run/docker.sock
User-Agent: Docker-Client/1.6.0
Content-Length: 931
Content-Type: application/json

{"Hostname":"","Domainname":"","User":"","Memory":67108864,"MemorySwap":0,"CpuShares":0,"Cpuset":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"PortSpecs":null,"ExposedPorts":{},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":[],"Cmd":["sleep","600"],"Image":"alpine:3.1","Volumes":{},"WorkingDir":"","Entrypoint":null,"NetworkDisabled":false,"MacAddress":"","OnBuild":null,"Labels":{},"HostConfig":{"Binds":null,"ContainerIDFile":"","LxcConf":[],"Memory":67108864,"MemorySwap":0,"CpuShares":0,"CpusetCpus":"","Privileged":false,"PortBindings":{},"Links":null,"PublishAllPorts":false,"Dns":null,"DnsSearch":null,"ExtraHosts":null,"VolumesFrom":null,"Devices":[],"NetworkMode":"bridge","IpcMode":"","PidMode":"","CapAdd":null,"CapDrop":null,"RestartPolicy":{"Name":"no","MaximumRetryCount":0},"SecurityOpt":null,"ReadonlyRootfs":false,"Ulimits":null,"LogConfig":{"Type":"","Config":null},"CgroupParent":""}}
```

`HostConfig` is missing from `docker-py`.

**Comment by cpuguy83** [comment] 2015-05-08 12:30
Hmm, yes this looks like something was missed in migrating the field to HostConfig.

**Comment by cpuguy83** [comment] 2015-05-08 12:39
Just an FYI, all the resource related fields were moved to HostConfig in 1.6.
If you try and set them in Config they'll just get set in HostConfig anyway.

@bobrik I assume the container existed before you upgraded to 1.6?

**Comment by bobrik** [comment] 2015-05-08 12:46
@cpuguy83 request dumps are from 1.6.0, most of my containers were recreated after migration. Can you point me to the PR where migration from Config to HostConfig happened?

**Comment by cpuguy83** [comment] 2015-05-08 12:48
#10298

**Comment by psviderski** [comment] 2015-05-08 17:17
@bobrik  The problem is that your memory limits are not set properly due to docker api changes: https://github.com/ansible/ansible-modules-core/pull/1208#issuecomment-97250044
`docker-py` sends `HostConfig` in `start` request and that `HostConfig` (without memory and cpu limits) is then used by the docker daemon.

**Comment by ottok** [comment] 2015-07-24 14:50
Is this solved or not?

I have one solution in mind unless this is done, and I can code it if somebody in this thread promises to help with testing/verifying.

api/client/stats.go might be reading the wrong value from
```
    "memory_stats": {
        "usage": 160657408,
        "max_usage": 224014336,
        "stats": {
            "active_anon": 40632320,
            "active_file": 9502720,
            "cache": 87175168,
            "hierarchical_memory_limit": 18446744073709552000,
            "inactive_anon": 93966336,
            "inactive_file": 16556032,
            "mapped_file": 60960768,
            "pgfault": 1044086,
            "pgmajfault": 2051,
            "pgpgin": 805698,
            "pgpgout": 770052,
            "rss": 73482240,
            "rss_huge": 14680064,
            "total_active_anon": 40632320,
            "total_active_file": 9502720,
            "total_cache": 87175168,
            "total_inactive_anon": 93966336,
            "total_inactive_file": 16556032,
            "total_mapped_file": 60960768,
            "total_pgfault": 1044086,
            "total_pgmajfault": 2051,
            "total_pgpgin": 805698,
            "total_pgpgout": 770052,
            "total_rss": 73482240,
            "total_rss_huge": 14680064,
            "total_unevictable": 0,
            "total_writeback": 0,
            "unevictable": 0,
            "writeback": 0
        },
        "failcnt": 0,
        "limit": 6259019776
```

**Comment by cpuguy83** [comment] 2015-09-15 15:31
Closing as this is fixed.

**Closed by cpuguy83** 2015-09-15 15:31 UTC
Labels: exp/intermediate, kind/bug

**Comment by ottok** [comment] 2015-09-15 20:24
Why was this closed? Please link to commit where it was fixed or something, otherwise I don't believe this is closed. Last time I checked from latest development source this was not yet fixed.

**Comment by cpuguy83** [comment] 2015-09-15 20:28
@ottok I couldn't point you at a commit, but testing locally even on 1.8, this works fine.

```
$ docker run -d -m 4M --name test busybox top
9d4eb4f14528756e3d68b9f4c8c90c5c0a3041320ca9780eb78aa5c4a14728f6
$ docker stats test
CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
test                0.00%               655.4 kB/4.194 MB   15.62%              648 B/738 B
```

**Comment by ottok** [comment] 2015-09-15 20:45
Hmm.. I am running Docker 1.8.2 on one machine and it shows:
```ipanainen_f044c2               0.04%               161.8 MB/8.373 GB   1.93%               96.8 MB/7.358 MB
ipanainen_b2544b               0.04%               210.4 MB/8.373 GB   2.51%               103.9 MB/11.51 MB
kehittamo-s_d53169             0.03%               306.9 MB/8.373 GB   3.67%               935 MB/969.3 MB
munkkiapteekki_4be989          0.03%               425.1 MB/8.373 GB   5.08%               1.455 GB/980 MB
```

..that is 8 GB RAM for all containers, not the memory count that has been allocated per container.

**Comment by cpuguy83** [comment] 2015-09-15 20:47
@ottok How did you start the containers?
Can you provide the output of `docker info` and `docker version`?

**Comment by ottok** [comment] 2015-09-17 17:17
Sorry for complaining, it turns out the machine where I checked did not employ memory limits for containers.

**Comment by KouLouYiMaSi** [comment] 2019-11-08 11:56
![image](https://user-images.githubusercontent.com/13957624/68474964-c3e6fd80-0261-11ea-8b4c-8e7f93609a93.png)

**Comment by KouLouYiMaSi** [comment] 2019-11-08 12:01
![image](https://user-images.githubusercontent.com/13957624/68475085-1b856900-0262-11ea-84c3-be437cd16722.png)
I use k8s start a pod limit memory 80G, but I use docker stats I see 74.51G.  my docker version is 18.06.1-ce.

**Comment by thaJeztah** [comment] 2019-12-11 17:06
@KouLouYiMaSi  looks to be difference between Gigabyte and Gibibyte: `80 Gigabyte` is `74,5058 Gibibyte`
