### ISSUE TITLE
NFS Volume Mounts - Stale File Handles

### ISSUE THREAD

**Issue by ryanborstelmann** [docker/docker#22891] opened 2016-05-22 16:14 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 10
 Paused: 0
 Stopped: 2
Images: 23
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 194
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local nfs
 Network: bridge null host
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 20
Total Memory: 23.54 GiB
Name: LennyR3-DockerV2
ID: BSOR:FQJY:LA2P:LFLX:546C:AAIW:YUKT:WF7T:AZ6P:LGKP:P6HX:63WP
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running inside a VM in a Hyper-V Host running Server 2012 R2. 

**Steps to reproduce the issue:**
1. Mount UnRAID NFS share to the docker host - /mnt/plex, in this case
2. Create and run several Docker containers that pass /mnt/plex as a volume. Example: `-v "/mnt/plex/TV Shows":/tv`. No containers share a volume folder - "TV Shows", in this example, is only used by the linuxserver/plex container and no others. 
- Example of the Plex `docker run` command:
```
docker run -d \
	--name=plex \
	--net=host \
	-e VERSION=latest \
	-e PUID=1000 -e PGID=1000 \
    -v "/mnt/plex/TV Shows":/tv \
    -v "/mnt/plex/Movies":/movies \
	-v /home/ryanb/docker/plex:/config \
	linuxserver/plex
```

**Describe the results you received:**
Everything would work great for some time, but eventually, seemingly at random, the mounted volume will be inaccessible by the container's application. In this example, the Plex server would report that the folder /tv is unavailable. If I open a bash shell in the container using `docker exec -it plex bash` and run `ls /tv`, and the shell will report `ls: cannot access /tv: Stale file handle`.

**Describe the results you expected:**
I'd expect no stale file handles from NFS and the containers work as expected.

**Additional information you deem important (e.g. issue happens only occasionally):**
A reboot of the container temporarily solves the issue, but like I said, it will happen 100% of the time, it's just a matter of when. Not sure why it happens. Let me know if there are any logs I can pull. Thanks!

**Comment by thaJeztah** [comment] 2016-05-22 16:53
Docker does nothing special with bind-mounts, it only mounts the directory inside the container and that's it. This error is probably related to the way NFS works, and you'd have the same error if plex was not running inside a container, and also using NFS. See http://www.cyberciti.biz/tips/nfs-stale-file-handle-error-and-solution.html

**Comment by ryanborstelmann** [comment] 2016-05-22 21:35
Ahh okay thanks for your help! I tried mounting NFS with `noac`, and while it helped, I still ran into the same issue eventually.

Is there a better way for me to do this? Volume plugins / CIFS, etc? I can't be the only one needing multiple containers using the same shared network volume. I'm open to try something else if there is a best practice that I'm not aware of.

**Comment by thaJeztah** [comment] 2016-05-22 22:09
I think using a volume plugin that is multi-host aware is probably the best, but even then, I know that NFS can be tricky https://docs.docker.com/engine/extend/plugins/#volume-plugins

I'll close this issue, because this is not a bug in Docker, but feel free to continue the discussion

**Closed by thaJeztah** 2016-05-22 22:09 UTC
Labels: version/1.11

**Comment by ryanborstelmann** [comment] 2016-05-22 23:13
I'm going to try using CIFS instead and see how things go, as SMB doesn't seem to have a lot of the issues that NFS has. The only issue I have is permissions with some containers using my UnRAID NAS, but that's a separate issue all together.

**Comment by thaJeztah** [comment] 2016-05-22 23:17
Cool, I hope it works!

**Comment by ryanborstelmann** [comment] 2016-05-23 19:14
Can report that CIFS/SMB is working flawlessly so far after about 20 hours of hitting the share pretty hard. No issues as of yet, unlike what I saw with NFS. Will report back here if I run into anything crazy, but all looks well as of now! Thanks @thaJeztah for your help.

**Comment by thaJeztah** [comment] 2016-05-23 19:27
Nice! Happy Plex time 🍿

**Comment by ebuildy** [comment] 2016-09-16 11:18
Hello, it looks like Docker related, I can mount the share, browse it fine, but if I run a new container with a volume to it, I don't see the same files:

![](http://b3.ms/aKb9LQBbA3RJ)

Restarting Docker is fine:

![](http://b3.ms/8Wj9ojWKMLKg)

Did you implement the window pattern CTRL+ATL+SUPPR ^^ ?

**Comment by shapeofarchitect** [comment] 2019-07-26 06:39
This is definitely a docker issue in old versions... docker when mounts this directory which is shared they don’t take care of how the inodes would play out as in my case I have that container which got “stale file error” now and my daemon won’t restart ! 

And I am sure it’s not NFS because I have no nfs Client running anywhere in my setup .

Thanks

**Comment by zziawan** [comment] 2022-04-28 03:33
> This is definitely a docker issue in old versions... docker when mounts this directory which is shared they don’t take care of how the inodes would play out as in my case I have that container which got “stale file error” now and my daemon won’t restart !
> 
> And I am sure it’s not NFS because I have no nfs Client running anywhere in my setup .
> 
> Thanks

i agree with you,  we meet the same error.(docker 1.13.1)   when happened all the pod mount the same nfs dirctory can not work,  even restart container.    the dirctory on the vm  host can still read and write，but  can not read  write in container。  if i mount it  again with "nocto", restart the container， it will be ok。 do you solve it?  thanks!
