### ISSUE TITLE
/etc/default/docker ignored

### ISSUE THREAD

**Issue by valentin2105** [docker/docker#32247] opened 2017-03-30 23:49 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
The file `/etc/default/docker` is ignored by systemctl while launching Docker (via service or init.d).

**Steps to reproduce the issue:**
1. Install Docker via the official way on Ubuntu 16.04 
2. Change something in `/etc/default/docker` (like enable IPv6)
3. Restart Docker

**Describe the results you received:**

The changes are not applied, I need to modify `/etc/systemd/system/multi-user.target.wants/docker.service` to enable my modifications.

**Describe the results you expected:**

Apply the change present on `/etc/default/docker` after rebooting the service. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 12
 Running: 2
 Paused: 0
 Stopped: 10
Images: 106
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 134
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.945 GiB
Name: runner02.srv.nautile.tech
ID: VSXG:WSWQ:QXDH:WZ57:GZKO:BEL6:VZ2B:BMLJ:NKVV:5OYY:CMGN:EFIZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Xen Ubuntu 16.04 virtual machine

**Comment by thaJeztah** [comment] 2017-03-31 00:46
That's expected; that file is only used for Sysvinit and upstart; https://github.com/docker/docker/blob/v17.03.1-ce/contrib/init/sysvinit-debian/docker.default#L1-L8

To specify daemon options;

- the recommended approach is to use a daemon.json configuration file (this works, irregardless of the init system in use (https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file)
- use systemd drop-in files (never directly modify the main unit file; doing so will prevent it from being updated when updating docker); https://docs.docker.com/v1.13/engine/admin/systemd/#/custom-docker-daemon-options

I'll close this issue, because this is not a bug, but feel free to comment after i closed

**Closed by thaJeztah** 2017-03-31 00:46 UTC
Labels: version/17.03

**Comment by valentin2105** [comment] 2017-03-31 02:16
@thaJeztah Thanks for your anwser. It's clear now. :smile:
