### ISSUE TITLE
Containers lost data  when host doesn't shutdown gracefully

### ISSUE THREAD

**Issue by JiaminWorld** [docker/docker#26762] opened 2016-09-20 23:19 UTC
**Description**
If I reboot the host gracefully, containers keep all the data as it before restart.
If I just power off the host , containers will lost the data like routing table setting and env. 
Should orchestration handle that case or docker will do that in the future?

**Steps to reproduce the issue:**
1. Run a simple container, set env or routing table
2. Power off the host 
3. 

**Describe the results you received:**
Env and routing table will be gone and ip of the containers will be different

**Describe the results you expected:**
Keep the data container has after restart

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Docker version 1.10.3, build 20f81dd

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2016-09-21 16:49
Can you provide the exact steps for reproducing? What commands do you run to start the container? Is the container run interactively, and changes made inside the container?

**Comment by JiaminWorld** [comment] 2016-09-21 17:53
Hi,

Here is the details.
I am trying to use docker container to build a simple demo case that
container A can send all the traffic through container B to container C. In
this case I need to create 3 containers and two networks.
docker run -itd --privileged --net mynet1 --name A image command
docker run -itd --privileged --net mynet1 --name B image command
docker run -itd --privileged --net mynet2 --name C image command
docker network connect mynet2 $(containerB id)

In containers, I will need to set routing rules or some other settings. Now
I am able to ping container C from container A.

But now, for some reason, my host power off. When I restart it, all the
containers are stop. After I restart them, I am not able to ping container
C since all the settings are gone.

My case is much more complex than it, so I need to manually set up again
and again if host powers off for some reason.

I am just wondering that why the settings in containers will be good if I
shutdown the host gracefully. What is the difference? Will docker do
something if it receive any shutdown signal?
In this case, should orchestrator handle it or docker will fix it?

Thanks,
Jiamin

**Comment by cpuguy83** [comment] 2016-09-22 01:43
Route settings in the container would not persist.
Likewise if you set routes on the host and reboot, the routes will be gone.

Closing as this looks like expected behavior.
Please feel free to discuss here, but these settings are not expected to persist in a container or outside.

**Closed by cpuguy83** 2016-09-22 01:43 UTC
Labels: status/more-info-needed, version/1.10
