### ISSUE TITLE
Docker 1.12.5 on raspberry pi 3

### ISSUE THREAD

**Issue by yamnicz3k** [docker/docker#29642] opened 2016-12-21 18:51 UTC
Docker version 1.12.5, build 7392c3b
Debian version: 8.0 (with latest updates)
Linux mraspi 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux

I was following [https://docs.docker.com/engine/installation/linux/debian/](url)

```
# dockerd -D -s devicemapper
DEBU[0000] docker group found. gid: 996                 
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] libcontainerd: new containerd process, pid: 17397 
DEBU[0000] libcontainerd: containerd connection state change: TRANSIENT_FAILURE 
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=4 memory=925 runtime=docker-runc runtimeArgs=[] stateDir=/var/run/docker/libcontainerd/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[0001] Using default logging driver json-file       
DEBU[0001] Golang's threads limit set to 13140          
DEBU[0001] [graphdriver] trying provided driver "devicemapper" 
DEBU[0001] Cleaning up old mountid : start.             
FATA[0001] Error starting daemon: error initializing graphdriver: driver not supported
```

Same thing with aufs.

Is there any issue with running current version on raspbian? If not, are there any other requirements?

**Comment by alexellis** [comment] 2016-12-21 19:45
There is no issue with Raspbian from my experience. I've not tested on Debian and I'm not certain whether it's fully supported. Have you tried overlay2? 

CC @justincormack

**Comment by justincormack** [comment] 2016-12-21 19:49
Not sure why `devicemapper` not supported if you can run this script https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh it would help to diagnose. But generally for Debian-like distros with new kernels would recommend `overlay2`. Not sure why it is defaulting to `devicemapper` either, I guess due to lack of `aufs` cc @thaJeztah

**Comment by yamnicz3k** [comment] 2016-12-21 21:04
Thanks @alexellis and @justincormack.

@justincormack, by default docker was using overlay. There is no aufs, and devicemapper (because we're using devicemapper in our dev/test/prod) is my choice.

@justincormack:
```info: reading kernel config from /boot/config.txt ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: missing
- CONFIG_NET_NS: missing
- CONFIG_PID_NS: missing
- CONFIG_IPC_NS: missing
- CONFIG_UTS_NS: missing
- CONFIG_CGROUPS: missing
- CONFIG_CGROUP_CPUACCT: missing
- CONFIG_CGROUP_DEVICE: missing
- CONFIG_CGROUP_FREEZER: missing
- CONFIG_CGROUP_SCHED: missing
- CONFIG_CPUSETS: missing
- CONFIG_MEMCG: missing
- CONFIG_KEYS: missing
- CONFIG_VETH: missing
- CONFIG_BRIDGE: missing
- CONFIG_BRIDGE_NETFILTER: missing
- CONFIG_NF_NAT_IPV4: missing
- CONFIG_IP_NF_FILTER: missing
- CONFIG_IP_NF_TARGET_MASQUERADE: missing
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: missing
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: missing
- CONFIG_NETFILTER_XT_MATCH_IPVS: missing
- CONFIG_IP_NF_NAT: missing
- CONFIG_NF_NAT: missing
- CONFIG_NF_NAT_NEEDED: missing
- CONFIG_POSIX_MQUEUE: missing
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: missing

Optional Features:
- CONFIG_USER_NS: missing
- CONFIG_SECCOMP: missing
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_SWAP: missing
- CONFIG_MEMCG_SWAP_ENABLED: missing
- CONFIG_MEMCG_KMEM: missing
- CONFIG_BLK_CGROUP: missing
- CONFIG_BLK_DEV_THROTTLING: missing
- CONFIG_IOSCHED_CFQ: missing
- CONFIG_CFQ_GROUP_IOSCHED: missing
- CONFIG_CGROUP_PERF: missing
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: missing
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: missing
- CONFIG_FAIR_GROUP_SCHED: missing
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_VS: missing
- CONFIG_IP_VS_NFCT: missing
- CONFIG_IP_VS_RR: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: missing
- CONFIG_EXT4_FS_POSIX_ACL: missing
- CONFIG_EXT4_FS_SECURITY: missing
    enable these ext4 configs if you are using ext4 as backing filesystem
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: missing
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: missing
      - CONFIG_CRYPTO_AEAD: missing
      - CONFIG_CRYPTO_GCM: missing
      - CONFIG_CRYPTO_SEQIV: missing
      - CONFIG_CRYPTO_GHASH: missing
      - CONFIG_XFRM: missing
      - CONFIG_XFRM_USER: missing
      - CONFIG_XFRM_ALGO: missing
      - CONFIG_INET_ESP: missing
      - CONFIG_INET_XFRM_MODE_TRANSPORT: missing
  - "ipvlan":
    - CONFIG_IPVLAN: missing
  - "macvlan":
    - CONFIG_MACVLAN: missing
    - CONFIG_DUMMY: missing
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: missing
    - CONFIG_BTRFS_FS_POSIX_ACL: missing
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: missing
    - CONFIG_DM_THIN_PROVISIONING: missing
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000```

**Comment by justincormack** [comment] 2016-12-21 21:47
Ok, well your kernel needs those two `DM` options if you want to use devicemapper.

**Comment by justincormack** [comment] 2016-12-21 22:11
If you ask the Raspbian kernel people nicely at https://github.com/raspberrypi/linux/issues they might add `CONFIG_BLK_DEV_DM` and `CONFIG_DM_THIN_PROVISIONING`. I am going to close this issue as that is the cause, but let us know if you have more questions.

**Closed by justincormack** 2016-12-21 22:11 UTC
Labels: area/kernel, platform/arm
