### ISSUE TITLE
Cannot pull image

### ISSUE THREAD

**Issue by pjullah** [docker/docker#14327] opened 2015-07-01 17:24 UTC
Hi, 

we're attempting to use Docker Swarm and running into a few issues (not Swarm related)

When I issue `docker pull swarm` i get the following output;
```bash
[root@master vagrant]# docker pull swarm
latest: Pulling from docker.io/swarm
55b38848634f: Extracting [==================================================>] 2.607 MB/2.607 MB
fd7bc7d11a30: Download complete
db039e91413f: Download complete
1e5a49ab6458: Download complete
5d9ce3cdadc7: Download complete
1f26e949f933: Download complete
e08948058bed: Download complete
```

It then just hang's indefinitely. I've read a few other posts which mention the device pool being full (or something like that) but don't have any experience of what that means. 

Any help would be really appreciated.

A little more info about my setup:

Machine (CentOS 7) is built using vagrant:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "master" do |master|
    master.vm.box = "jhcook/centos7"
    master.vm.hostname = "master"
    master.vm.network "public_network"
    master.vm.provision "shell", inline: "echo Master"
    master.vm.provision "shell", path: "bootstrap.sh"
  end
end
```

Docker installed:
```bash
sudo yum install -y docker-io
```
```bash
[root@master vagrant]# docker --version
Docker version 1.6.2, build ba1f6c3/1.6.2
```

```bash
[root@master vagrant]# uname -a
Linux master 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
[root@master vagrant]# sudo du -sh /var/lib/docker/*
0       /var/lib/docker/containers
16K     /var/lib/docker/devicemapper
0       /var/lib/docker/graph
7.8M    /var/lib/docker/init
8.0K    /var/lib/docker/linkgraph.db
4.0K    /var/lib/docker/repositories-devicemapper
2.7M    /var/lib/docker/tmp
4.0K    /var/lib/docker/trust
0       /var/lib/docker/volumes
```

```bash
[root@master vagrant]# ps -ef | grep docker
root      4329     1  0 18:01 ?        00:00:01 /usr/bin/docker -d --selinux-enabled -s devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/centos-docker--pool
```

Interestingly (aside), `docker info` also hangs.

Many thanks.

**Comment by jonbuffington** [comment] 2015-07-01 19:07
@pjullah We have seen 1.7.0 radically increase disk usage when pulling images. You may want to check the amount of disk space used/available. We notice the pull hang when disk space is zero.

**Comment by ankushagarwal** [comment] 2015-07-01 20:21
Lot of people have noticed problems with the `devicemapper` storage driver, which has a lot of problems. This issue is _probably_ a duplicate of  #14204

**Comment by pjullah** [comment] 2015-07-01 20:40
Thanks @jonbuffington, I've taken a look at disk utilisation on the VM (although I am running 1.6 not 1.7);

```bash
[root@master vagrant]# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root  6.7G 1015M  5.7G  15% /
devtmpfs                 488M     0  488M   0% /dev
tmpfs                    497M     0  497M   0% /dev/shm
tmpfs                    497M  6.6M  491M   2% /run
tmpfs                    497M     0  497M   0% /sys/fs/cgroup
/dev/sda1                497M  119M  379M  24% /boot
none                     233G   78G  156G  34% /vagrant
```

After having pulled the image on another machine, and issuing `docker images`, the size of the image looks insignificant;

```bash
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
swarm               0.3.0               e08948058bed        2 weeks ago         10.28 MB
swarm               latest              e08948058bed        2 weeks ago         10.28 MB
swarm               0.3.0-rc3           e08948058bed        2 weeks ago         10.28 MB
```

Presumably the virtual size is not the *actual* size of the image, is there a way to determine how much space the image takes up on disk?

@ankushagarwal, thank you too, I'll take a look at #14204

**Comment by pjullah** [comment] 2015-07-02 10:34
So, I'm a little confused. It turned out that disk space *was* the issue, **but** ...

I increased the size of the VMs HDD, from 6GB to 50GB (using this great link https://gist.github.com/christopher-hopper/9755310)

Then I did `df -h` prior to pulling the image.

```bash
[root@master ~]# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root   48G 1001M   47G   3% /
devtmpfs                 488M     0  488M   0% /dev
tmpfs                    497M     0  497M   0% /dev/shm
tmpfs                    497M  6.6M  491M   2% /run
tmpfs                    497M     0  497M   0% /sys/fs/cgroup
/dev/sda1                497M  119M  379M  24% /boot
```
Pulled the image, which worked this time, and then checked `df` again

```bash
[root@master ~]# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root   48G  1.3G   47G   3% /
devtmpfs                 488M     0  488M   0% /dev
tmpfs                    497M     0  497M   0% /dev/shm
tmpfs                    497M  6.6M  491M   2% /run
tmpfs                    497M     0  497M   0% /sys/fs/cgroup
/dev/sda1                497M  119M  379M  24% /boot
```

The increase in disk utilisation was only a few hundred Mb. 

What is confusing is that when I originally attempted to pull the image I had 5GB of free space, i.e. much more that the image seemed to have needed.

I'm glad I've managed to pull the image, but it would be nice to know why this happened.

Any ideas?

Thanks

**Comment by thaJeztah** [comment] 2015-08-16 10:21
I'm going to close this issue, because the original issue was resolved, but if anyone has ideas on this, feel free to comment here

**Closed by thaJeztah** 2015-08-16 10:21 UTC
