### ISSUE TITLE
INFO[0011] Cannot create container with more than 127 parents

### ISSUE THREAD

**Issue by thanizebra** [docker/docker#12624] opened 2015-04-22 07:21 UTC
INFO[0011] Cannot create container with more than 127 parents 

i am not able to delete intermediate images after upgrading to version 1.6.
i get this error when i tried to delete a intermediate image.
 
docker rmi ada7cae2d705
Error response from daemon: Conflict, ada7cae2d705 wasn't deleted
FATA[0000] Error: failed to remove one or more images  

yesterday i have updated docker to 1.6 from 1.5
my
docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64

i have build only 11 named images 
`docker images`  list all 11 named images.

but my my 
`docker images -a`  command 
give 200+ entries in which many are intermediate <none> images.

when i run `docker rmi $(docker images --filter dangling=true -q)`

then it removes 29 images 
but still my  `docker images -a`  command 
give 180+ entries 

when i build a image i got below error
INFO[0011] Cannot create container with more than 127 parents

how can i delete all intermediate images.
it seems like i have to downgrade 1.5 to solve my issue :)

**Comment by thanizebra** [comment] 2015-04-22 07:22
i am using supervisor package to manage sshd,apache2,postgresql,redis-server services

**Comment by SimonWang2014** [comment] 2015-04-24 07:59
Check that images are being used by containers

**Comment by thanizebra** [comment] 2015-04-24 08:18
not
docker ps -a 
give empty list

**Comment by cpuguy83** [comment] 2015-07-22 14:07
There is no such thing as an "intermediate" image. Images are comprised of layers, these layers are all required.

Closing since this is expected behavior:

1. That the max image size is 127
2. That you have a bunch of undeleteable images in `docker images -a` as they are parents to another image.

If you want to remove images that you _probably_ aren't using (because they are not part of a tagged image), you can use `docker rmi $(docker images --filter dangling=true)`

**Closed by cpuguy83** 2015-07-22 14:07 UTC

**Comment by kindule** [comment] 2015-07-30 04:48
hi, I found this error reproduce，in docker 1.7.1 

	[root@jinge-jekins ~]# cat /etc/redhat-release
	CentOS release 6.6 (Final)

	Containers: 0
	Images: 320
	Storage Driver: devicemapper
	 Pool Name: docker-252:16-2621444-pool
	 Pool Blocksize: 65.54 kB
	 Backing Filesystem: extfs
	 Data file: /dev/loop0
	 Metadata file: /dev/loop1
	 Data Space Used: 14.72 GB
	 Data Space Total: 107.4 GB
	 Data Space Available: 10.66 GB
	 Metadata Space Used: 35.82 MB
	 Metadata Space Total: 2.147 GB
	 Metadata Space Available: 2.112 GB
	 Udev Sync Supported: true
	 Deferred Removal Enabled: false
	 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
	 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
	 Library Version: 1.02.89-RHEL6 (2014-09-01)
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 2.6.32-504.el6.x86_64
	Operating System: <unknown>
	CPUs: 2
	Total Memory: 3.741 GiB
	Name: jinge-jekins
	ID: HOX4:6IGL:PQHD:AZXY:O4N4:W376:WADN:JD7Q:JWE5:OSP4:B2KP:IU3A


	[root@jinge-jekins ~]# docker --version
	Docker version 1.7.1, build 786b29d


	[root@jinge-jekins ~]# docker run -it b5f9a898d374  /bin/bash
	Error response from daemon: Cannot create container with more than 127 parents

**Comment by beetree** [comment] 2016-01-24 17:26
I understand this is the expected behavior, but I'm not fully clear on how to resolve it.

I'm doing:
```
# docker run -it localhost:81/container_11491
Error response from daemon: Cannot create container with more than 127 parents
```

System info:
```
# docker info
dContainers: 203
Images: 401
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-9:2-8390725-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 2.147 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 35.69 GB
 Data Space Total: 214.7 GB
 Data Space Available: 179.1 GB
 Metadata Space Used: 47.81 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.1 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.99 (2015-06-20)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.8-031908-generic
Operating System: Ubuntu 15.10
CPUs: 12
Total Memory: 125.9 GiB
Name: Ubuntu-1510-wily-64-minimal
ID: 5DRL:X4I7:25JN:ETAX:6RTA:4O7T:ULZ2:SE4C:7TY7:LVAA:DBYV:UVQW
WARNING: No swap limit support


# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64


# uname -a
Linux Ubuntu-1510-wily-64-minimal 3.19.8-031908-generic #201505110938 SMP Mon May 11 13:39:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

The image is built from a 3 line Dockerfile which is no more than `FROM ubuntu` and `ADD . /`.

Anyone can explain why I'm getting this error? If creating the image works, it seems to me like an unnatural behavior that an error is thrown on `docker run`, right?

/beetree

**Comment by linas** [comment] 2016-02-20 23:51
Here's a work-around:  https://forums.docker.com/t/how-to-flatten-an-image-with-127-parents/1600/4

**Comment by linas** [comment] 2016-02-21 00:21
<flame> One huge point of the Docker image caching system is that it allows you to build nice, fine-grained Dockerfiles, so that if you make a mistake in one step, you can fix it and rebuild without much work. Having to re-organize your Dockerfile to reduce the number of commands defeats this whole mechanism -- a minor modification results in long build times.  The time-wasters (for me) are usually `apt-get`, `git clone` and `make` and so I used to split these up into multiple lines. Mashing them down into fewer lines results in penalties for minor mistakes. Raising the limit, or finding some other solution, would be much better.</flame>

**Comment by thaJeztah** [comment] 2016-02-21 01:05
@linas putting `apt-get` or `git clone` in a separate line (separate layer), will also result in them *never* to be re-evaluated, so you'll end up with outdated packages, or an old git clone to be used.

Great care should be taken when splitting steps; for example, adding 100 megabyte in one layer, and removing 100 megabyte in another layer, will still produce an 100 megabyte image.

Having said that, my usual approach is to start with an interactive container; perform each step manually, to test if they work (or try/fail/try again), then copy those steps to a Dockerfile, optimizing them by combining logical steps to a `RUN` command.

**Comment by cpuguy83** [comment] 2016-02-21 01:10
@linas the limit is not set arbitrarily. The limit is due to technical limitations.

There is also a performance cost for every layer you create.

**Comment by linas** [comment] 2016-02-22 05:01
Thanks @cpuguy83 yes, I understand. It just .. came as a surprise.  Then, when I thought about it some more, it was even more surprising.  Until now, I was oblivious to the cost, the limit, or the need to even think about such things.

@thaJeztah  yes. The way we do things here is to sprinkle in an `ENV LAST_OS_UPDATE 2015-08-13` or similar line here and there, and then touching it every now and then, to rebuild the cache. I didn't invent this way of doing things; I assumed this is a common paradigm (err... pattern...)
