### ISSUE TITLE
Not able to re-mount volume after it has been deleted and created again

### ISSUE THREAD

**Issue by marc2905** [docker/docker#25326] opened 2016-08-02 11:52 UTC
**Output of `docker version`:**
Client:
  Version: 1.12.0
  API version: 1.24
  Go version: go1.6.3
  Git commit: 8eab29e
  Built: Thu Jul 28 21:15:28 2016
  OS/Arch: darwin/amd64

Server:
  Version: 1.12.0
  API version: 1.24
  Go version: go1.6.3
  Git commit: 8eab29e
  Built: Thu Jul 28 21:15:28 2016
  OS/Arch: darwin/amd64

**Steps to reproduce:**
- Create directory in the user home like /Users/user/runtime and create a file inside
- Create a docker container with a volume to that host directory like
docker create -t -i -v /Users/user/runtime:/rt alpine sh
- Start the container and go inside the /rt directory. Everything is ok.
- Delete the /Users/user/runtime directory. Create it again and also the file inside the directory
- Create a new docker container with a volume to that host directory like
docker create -t -i -v /Users/user/runtime:/rt alpine sh
- Start the container and go inside the /rt directory. The directory will be empty.

This worked fine with version 1.11.2

**Describe the results you received:**
Volumes are mounted fine but when you delete the host folder, create it again, the folder
cannot be mounted again, even if you create a new container.

**Describe the results you expected:**
With docker version 1.11.2 the folder could be mounted when you created a new container.

**Comment by cpuguy83** [comment] 2016-08-02 15:32
I'm not sure how this would ever worked...note to others looking, you must stay in `/rt` in the container while deleting it from outside the container and creating a new one.

I assume you are using docker4mac?

**Comment by thaJeztah** [comment] 2016-08-02 16:08
Made me think of https://github.com/docker/docker/issues/12317, but the last two bullets are strange, could be because the first container is still running?

ping @dhseets

**Comment by dsheets** [comment] 2016-08-03 10:25
This is a known issue with Docker for Mac. It was first reported at <https://forums.docker.com/t/directories-deleted-and-recreated-on-host-cause-mounted-volume-to-become-disconnected/16953> and the cause is known. A patch has been started but more critical bugs have taken priority. I expect the patch to make it into the next couple Docker for Mac beta releases if all goes well.

I'm sorry you've experienced this issue. My best advice right now is to avoid:

1. Removing a directory while some container holds a handle on that directory, and then
2. Recreating a directory with the same name.

Unfortunately, there may be circumstances where this is unavoidable. Do you require this functionality for your use case?

**Comment by marc2905** [comment] 2016-08-03 12:55
I’m working on the Intel System Studio for IoT Edition and we want to use Docker for cross compilation. The toolchains are in the Docker containers.
The Intel System Studio for IoT Edition is an eclipse based IDE and the workspaces are shared with the Docker containers.

Sometimes users might want to clean up their workspaces remove them and create a new workspace with the same name. We do this also often for developing.
For us it is a use case but not a show stopper. Anyway it would be nice if it gets solved in the next builds.

Unfortunately a beta  version is not a good solution for us as we cannot point our users to a beta version.

Thanks

**Comment by cpuguy83** [comment] 2016-08-03 15:47
If a container is mounting a dir, I feel like trying to `rm` that dir on the host system should result in a resource busy error.

**Comment by dsheets** [comment] 2016-08-03 16:01
Unless I misunderstand something, that is not the behavior of Linux bind mounts:

```sh
moby:~# mkdir foo
moby:~# touch foo/bar
moby:~# docker run --rm -v ~/foo:/foo alpine sh -c 'for i in $(seq 1 10); do ls
/foo; sleep 1; done' &
moby:~# bar
moby:~# rm -r foo
moby:~# ls -alh
total 4
drwx------    2 root     root          60 Aug  3 15:58 .
drwxrwxrwt   23 root     root         500 Aug  3 15:40 ..
-rw-------    1 root     root         656 Aug  3 15:58 .ash_history
moby:~# jobs
[1]+  Running                    docker run --rm -v ~/foo:/foo alpine sh -c "for i in \$(seq 1 10); do ls /foo; sleep 1; done"
```

This issue only reports the issue during removal of mountpoints but, unfortunately, the issue actually occurs when any directory with an active is removed in an `osxfs` mount.

**Comment by dsheets** [comment] 2016-09-01 10:39
This should now be resolved in Beta 24.

**Closed** 2016-09-14 14:12 UTC
Labels: platform/desktop, version/1.12
