### ISSUE TITLE
Counterintuitive behavior of nested volumes

### ISSUE THREAD

**Issue by hkjn** [docker/docker#16487] opened 2015-09-22 15:33 UTC
Description
====
If a container at runtime specifies a volume with less specific path than what's specified with `VOLUME` in the `Dockerfile` for the image, the volume acts in counterintuitive ways.

The issue described below occurred for us when using the `postgres` image to persist the backing data in a container, using a command like `docker run -v /some/host/path:/var/lib/postgresql postgres`, which against our expectations didn't put any data on the host directory (i.e. every time the `postgres` container restarted, the data in the DB was lost). The reason for this was the `VOLUME /var/lib/postgresql/data` statement in https://github.com/docker-library/postgres/blob/master/9.4/Dockerfile#L43.

Demo of issue
====
Build an image that specifies a `VOLUME`:
```
$ mkdir /tmp/demo && cd /tmp/demo
$ cat << EOF > Dockerfile
FROM debian
VOLUME /var/demo/inner
EOF
$ docker build -t demo .
```
Run a container with a host directory mounted into a less specific path than the `VOLUME` from the `Dockerfile`, which puts some data into the directory:
```
$ docker run -it --name demo1 -v $(pwd)/demo1:/var/demo demo touch /var/demo/inner/somefile
```
Actual results
=====
Despite specifying a host directory as a volume, changes inside the container do not propagate to the host:
```
$ ls demo1/inner/somefile
ls: cannot access demo/inner/somefile: No such file or directory
```
This was a confusing outcome for me/us, though I now understand why it happens. 

Expected results
=====
Either that the host directory is updated like with other, non-shadowed volumes. Or, if this can't be easily supported, an error message at `docker run` time shows that such a volume can't be created. (Is there a legitimate use case of having volumes nested inside each other?)

Explanation
=====
(Disclaimer: Might be wrong / incomplete!)
Without specifying further volumes to `docker run`, everything as act we'd expect. We have a volume, it can be used to share data, etc.
```
$ docker run --name demo0 demo touch /var/demo/inner/somefile
$ docker run --rm --volumes-from=demo0 demo ls /var/demo/inner
somefile
$ docker inspect demo0 | grep -A2 'Volumes\b'
    "Volumes": {
        "/var/demo/inner": "/var/lib/docker/volumes/0ab2ef88218a923420f899c54b8725e35310d342ad752a4af613f0e7599e0588/_data"
    },
--
        "Volumes": {
            "/var/demo/inner": {}
        },
```
In the counterintuitive case, we've (accidentally) created two separate volumes, and only the outer one is mapped to the named host path: 
```
$ docker inspect demo1 | grep -A2 'Volumes\b'
    "Volumes": {
        "/var/demo": "/tmp/dockervols/demo1",
        "/var/demo/inner": "/var/lib/docker/volumes/7a8194c3c4e863a9a0452fd8447bc89bf711876726ea58ad2f2e8b7f733fb6a1/_data"
--
        "Volumes": {
            "/var/demo/inner": {}
        },
```
If we specify a host volume that _exactly_ matches the `VOLUME` from the `Dockerfile`, we override the `VOLUME` from the `Dockerfile`, and things will also act as expected:
```
$ docker run --name=demo2 -v $(pwd)/demo2:/var/demo/inner demo touch /var/demo/inner/somefile
$ ls demo2/
somefile
$ docker inspect demo2 | grep -A2 'Volumes\b'                                                                                                                                                         
    "Volumes": {
        "/var/demo/inner": "/tmp/dockervols/demo2"
    },
--
        "Volumes": {
            "/var/demo/inner": {}
        },
```

Versions
====
```
$ uname -a
Linux test-1 4.1.7-coreos #2 SMP Wed Sep 16 22:54:37 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux
```
```
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): df2f73d-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): df2f73d-dirty
OS/Arch (server): linux/amd64
```
```
$ docker -D info
Containers: 12
Images: 247
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-coreos
Operating System: CoreOS 766.4.0
CPUs: 1
Total Memory: 995.7 MiB
Name: test-1
ID: QV5G:RMIE:GCUA:HL2V:MRCI:NOPA:D3SK:2V6V:5DUL:WT3M:OF4T:Z7OM
```

**Comment by calavera** [comment] 2015-09-22 20:33
Take a look at https://github.com/docker/docker/pull/16496. I think that should fix your issue, but I'm not sure of the implications of the change yet.

**Comment by hkjn** [comment] 2015-09-23 06:11
Thanks!

If I understand the changes in #16496 (as currently written), I believe they should resolve the issue as described here, i.e. "nothing surprising would happen" in this specific case.

It's difficult to trade-off fewer restrictions / special-cases vs less surprising behavior though, but I appreciate you looking into this regardless of whether the PR goes in or not.

**Comment by calavera** [comment] 2015-09-24 21:10
Hi @hkjn,

after a chat with @crosbymichael, we've decided that the code is working as intended, and we are not going to modify the current behavior. I understand that this is not what you expected, specially after seen that a "fix" might be possible, but changing the behavior might have other consequences.

As a way to solve your problem, I recommend you to bind mount `/var/lib/postgresql/data` inside your container with something like `--volume /some/host/path:/var/lib/postgresql/data`. That will put the postgresql data exactly where you want it. I'd like also remind you that the official images are also open source. Maybe it's possible to change the dockerfile to accommodate your suggestions. This is the postgresql repo: https://github.com/docker-library/postgres.

I'm closing this issue, thanks for the thoughtful report.

**Closed by calavera** 2015-09-24 21:10 UTC
