### ISSUE TITLE
build from url with local context of onbuild copy

### ISSUE THREAD

**Issue by tomdavidson** [docker/docker#22101] opened 2016-04-17 02:56 UTC
Building from URL could be very convenient with onbuild images, but it seems that the context is not the current working path. onbuild copy could not work as one might expect. 

Can can I build from url such as following but have onbuild copy context work against the local working directory?:
```
docker build https://github.com/repo.git#branch:folder
```
or
 ```
services:
  web:
    build: https://github.com/repo.git#branch:folder
    ports:
     - "80:80"
    env_file:
     - stage.env
```

**Comment by thaJeztah** [comment] 2016-04-17 10:19
When you build from an URL (e.g. `docker build github.com/foo/bar`), docker clones the git repository to a temp-directory, and uses that as the build context. Using any other build-context for that build, would probably not make sense, because the Dockerfile in that repository*expects* to be built using the files in that repository.

Also, be aware that `ONBUILD` only is used for images that *extend* the image that declares the `ONBUILD`. So, it's probably needed to create a Dockerfile with just;

    FROM that-image-with-onbuild

(See, for example, how to use the [official NodeJs image](https://hub.docker.com/_/node/))

Does that answer your question?

Please keep in mind that our GitHub issue tracker is for reporting bugs and feature requests, not a general support forum. For other questions, consider using;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

Since this is a question, not a bug, I'll close this issue, but feel free to comment after I closed :+1:

**Closed by thaJeztah** 2016-04-17 10:19 UTC

**Comment by tomdavidson** [comment] 2016-04-18 17:42
A slick way to implement this feature would be to support similar behavior in PATH as with URL. For example:
 - Wouldn't `docker build -f docker-files/Dockerfile .` use the working directly of the docker build command rather than 'docker-files/Dockerfile' as its context?
 - But `docker build -f https://github.com/repo.git#branch:folder .` Has different behavior, 'unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/.....:: no such file or directory'

Yes, it is understood a new downstream dockerfile that is as simple as `FROM that-image-with-onbuild` will get the job done. The point I am making is that if the upstream dockerfile is a PATH then I can modify the context but there is a very different context behavior when using URL. 

If there is validity to expecting the behaviors to be consistent lets make this a feature request, otherwise what am I misunderstanding?

**Comment by thaJeztah** [comment] 2016-04-18 18:17
If you build from a remote source, the repository itself provides the build context https://docs.docker.com/engine/reference/commandline/build/, basically, Docker clones the git repository, and then triggers a Docker build.

**Comment by tomdavidson** [comment] 2016-04-18 21:58
The current way docker build URL is understood. I had hopped there was undocumented feature of changing context as there is with docker build -f PATH. Apparently there is not and limitation is as designed. It does not need explained nor is a link to the docs needed.

Is this not the forum for a discussion concerning why the inconsistency or concerning the value of being able to have a local context when building with URL - a new feature?
