### ISSUE TITLE
 memberlist failed to receive message from remote node for EOF error

### ISSUE THREAD

**Issue by TheBeeMan** [docker/docker#26196] opened 2016-08-31 13:14 UTC
### Issue description:

> remote node failed to join to the swarm cluster after initialization, it shows EOF error from the manager debug info. I am very confused, why?

### Client:

> Version: 1.12.0-dev
> API version: 1.25
> Go version: go1.6.3
> Git commit: 9c1be54-unsupported
> Built: Tue Aug 23 16:07:13 2016
> OS/Arch: linux/amd64

### Server:

> Version: 1.12.0-dev
> API version: 1.25
> Go version: go1.6.3
> Git commit: 9c1be54-unsupported
> Built: Tue Aug 23 16:07:13 2016
> OS/Arch: linux/amd64
> Output of docker info:

> Containers: 3
> Running: 0
> Paused: 0
> Stopped: 3
> Images: 39
> Server Version: 1.12.0-dev
> Storage Driver: aufs
> Root Dir: /var/lib/docker/aufs
> Backing Filesystem: extfs
> Dirs: 40
> Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins: 
> Volume: local
> Network: overlay bridge null host
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Security Options: apparmor
> Kernel Version: 4.2.0-27-generic
> Operating System: Ubuntu 14.04.4 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 3.843 GiB
> Name: default
> ID: TIJL:TE7H:57V2:JT6F:PK6M:YO56:FRAX:C3YP:JZYD:NMON:FM34:Q4OK
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): true
> File Descriptors: 13
> Goroutines: 23
> System Time: 2016-08-26T17:20:27.014392209+08:00
> EventsListeners: 0
> Registry: https://index.docker.io/v1/
> Insecure Registries:
> 127.0.0.0/8

**Comment by ehazlett** [comment] 2016-09-01 17:17
This looks like an older dev build.  Can you try the latest 1.12 as well as some more info on how to reproduce (how many managers, nodes)?

**Comment by TheBeeMan** [comment] 2016-09-02 10:09
ok, it is ok now, maybe something about the network got wrong.

**Comment by thaJeztah** [comment] 2016-09-27 16:44
Thanks, let me close this one then

**Closed by thaJeztah** 2016-09-27 16:44 UTC
