### ISSUE TITLE
"pip install" failed on overlay driver

### ISSUE THREAD

**Issue by chennanfei** [docker/docker#13457] opened 2015-05-25 10:53 UTC
I changed to storage driver to overlay and ran "docker build" against my python project. But the build was terminated by one command in the Dockerfile "RUN pip install -r requirements.txt". I found it failed when a python module was uninstalled and going to be reinstall. I want to install module "requests" with version 2.4.3. but the version 2.2.1 already exists, so it will be uninstalled firstly, then an exception is thrown. I never got this issue on devicemapper.

## error output:
```
  Found existing installation: requests 2.2.1
    Uninstalling requests:
      Successfully uninstalled requests
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1443, in install
    requirement.commit_uninstall()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 610, in commit_uninstall
    self.uninstalled.commit()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1860, in commit
    rmtree(self.save_dir)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 43, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/pip-7RhvdD-uninstall/usr/lib/python2.7/dist-packages'

Storing debug log for failure in /root/.pip/pip.log
INFO[0013] The command [/bin/sh -c pip install -r ./requirements.txt] returned a non-zero code: 2
```

## docker version
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

## docker info
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
root@ip-172-31-38-97:~/jaina# docker info
Containers: 0
Images: 0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.19.8-031908-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 8
Total Memory: 29.4 GiB
Name: ip-172-31-38-97
ID: QVAM:LP7D:7ZZY:6PSA:57HX:26DF:S56J:3Z7N:N2ZL:CSDG:OJOW:D55H
WARNING: No swap limit support
```

## uname -a
```
Linux ip-172-31-38-97 3.19.8-031908-generic #201505110938 SMP Mon May 11 13:39:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment] 2015-05-25 12:50
Thanks for reporting, I'm going to close this issue, because I think this is a duplicate of https://github.com/docker/docker/issues/12327. Please continue the conversation on https://github.com/docker/docker/issues/12327

Feel free to comment here if you think this is not a duplicate and I closed this by mistake

**Closed by thaJeztah** 2015-05-25 12:50 UTC
Labels: /system/overlay
