### ISSUE TITLE
/var/volume returns Permission denied

### ISSUE THREAD

**Issue by trishnaguha** [docker/docker#22410] opened 2016-04-29 07:22 UTC
I am unable to do `ls` or `ll` or `ls -al` in `/var/volume` directory of the container. It returns Permission denied.  
But other contents of the root directory are working fine except `/var/volume`.

Here are the commands and the outputs.

<pre>[root@cfd01af8f49a /]# cd /var/volume
[root@cfd01af8f49a volume]# ls
ls: cannot open directory .: Permission denied
[root@cfd01af8f49a volume]# ll
ls: cannot open directory .: Permission denied
[root@cfd01af8f49a volume]# ls -al
ls: cannot open directory .: Permission denied
[root@cfd01af8f49a volume]# cat /etc/issue
CentOS release 6.7 (Final)
Kernel \r on an \m
</pre>
I am using CentOS6 image. I am not sure why I am having this.

**Comment by justincormack** [comment] 2016-04-29 11:40
Hi, there is no `/var/volume` in the default `centos:6` image, so you will have to give some more information about what you are doing.

**Comment by thaJeztah** [comment] 2016-04-29 11:41
Can you please provide the information that was requested in the template? Without more information we cannot help you further;

- the output of `docker version`
- the output of `docker info`
- steps to reproduce; e.g. the `docker run` arguments you used to start the container

**Comment by trishnaguha** [comment] 2016-04-29 12:00
@justincormack Yes `/var/volume` is not there in `centos:6` by defualt. 
I am uploading the screenshot what I am doing. 

![screenshot from 2016-04-29 17-23-51](https://cloud.githubusercontent.com/assets/13337039/14915323/9db8cf00-0e2f-11e6-96a8-8a687262c633.png)

**Comment by trishnaguha** [comment] 2016-04-29 12:04
@thaJeztah 
<pre>
trishna@Trishna:~$ docker --version
Docker version 1.8.2-fc22, build cb216be/1.8.2
trishna@Trishna:~$ docker info
Containers: 90
Images: 185
Storage Driver: devicemapper
 Pool Name: docker-253:1-2237478-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.057 GB
 Data Space Total: 107.4 GB
 Data Space Available: 28.07 GB
 Metadata Space Used: 17.15 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.13 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 3.757 GiB
Name: Trishna.localdomain
ID: NNEJ:7DAD:ZLLL:5WMY:6LWU:F7RO:HN3P:TXMF:WPN4:VHR3:U53S:2XPH
Username: trishnag
Registry: https://index.docker.io/v1/
trishna@Trishna:~$ docker run -t -i -v /home/trishna/myvolume:/var/volume centos:centos6 /bin/bash
[root@061c34257217 /]# 
</pre>

Also here is a link for the screenshot: http://img.susepaste.org/69591619

**Comment by trishnaguha** [comment] 2016-04-29 12:14
@thaJeztah @justincormack So my objective is to provide external resource to the container. So I mapped `/home/trishna/myvolume` to `/var/volume` of the container. But I am unable to access `/var/volume` in the container.

**Comment by thaJeztah** [comment] 2016-04-29 12:15
It looks like you're running a Red Hat build of Docker (https://github.com/projectatomic/docker/commit/cb216be), and those contain a lot of modifications that make docker run different. Can you try installing the official version? https://docs.docker.com/engine/installation/linux/fedora/

**Comment by trishnaguha** [comment] 2016-04-29 12:23
I have installed the official version months ago like given over here. https://docs.docker.com/engine/installation/linux/fedora/
I did this only `$ sudo dnf -y install docker` .

**Comment by thaJeztah** [comment] 2016-04-29 12:26
Running `sudo dnf -y install docker` will install the "docker" package from the Red Hat repository, not the "docker-engine" package from https://yum.dockerproject.org

**Comment by justincormack** [comment] 2016-04-29 12:27
@trishnaguha can you give the output of `ls -la /var` in the container? It may just be the uid or permissions are wrong.

**Comment by trishnaguha** [comment] 2016-04-29 12:31
@justincormack Sure.
<pre>
[root@d2e2a82ad986 /]# ls -la /var
total 72
drwxr-xr-x. 18 root root 4096 Apr 29 12:29 .
drwxr-xr-x. 22 root root 4096 Apr 29 12:29 ..
drwxr-xr-x.  4 root root 4096 Mar 31 18:34 cache
drwxr-xr-x.  2 root root 4096 Sep 23  2011 db
drwxr-xr-x.  2 root root 4096 Sep 23  2011 empty
drwxr-xr-x.  2 root root 4096 Sep 23  2011 games
drwxr-xr-x.  7 root root 4096 Mar 31 18:38 lib
drwxr-xr-x.  2 root root 4096 Sep 23  2011 local
drwxrwxr-x.  3 root lock 4096 Mar 31 18:34 lock
drwxr-xr-x.  2 root root 4096 Mar 31 18:38 log
lrwxrwxrwx.  1 root root   10 Mar 31 18:34 mail -> spool/mail
drwxr-xr-x.  2 root root 4096 Sep 23  2011 nis
drwxr-xr-x.  2 root root 4096 Sep 23  2011 opt
drwxr-xr-x.  2 root root 4096 Sep 23  2011 preserve
drwxr-xr-x.  6 root root 4096 Mar 31 18:38 run
drwxr-xr-x.  4 root root 4096 Mar 31 18:38 spool
drwxrwxrwt.  2 root root 4096 Mar 31 18:38 tmp
drwxrwxr-x.  2 1000 1000 4096 Apr 29 07:25 volume
drwxr-xr-x.  2 root root 4096 Sep 23  2011 yp
</pre>

**Comment by thaJeztah** [comment] 2016-04-29 12:34
Oh, actually, could this be an SELinux issue? What happens if you add `--security-opt=label:disable` to your `docker run` instruction?

**Comment by trishnaguha** [comment] 2016-04-29 12:38
@thaJeztah Ah It solved my issue. Thanks a lot :).

**Comment by justincormack** [comment] 2016-04-29 12:40
Ah I was wondering if it was that given the other things... SELinux is quite strict about where you can access files from by default on redhat...

**Comment by thaJeztah** [comment] 2016-04-29 12:45
Oh, great! Let me close this issue then 👍

**Closed by thaJeztah** 2016-04-29 12:45 UTC
Labels: status/more-info-needed
