### ISSUE TITLE
rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused "fork/exec /proc/self/exe: no such file or directory" after host reboot

### ISSUE THREAD

**Issue by pablitok** [docker/docker#25381] opened 2016-08-03 21:37 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 4
 Paused: 0
 Stopped: 3
Images: 502
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-202:1-133252-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 15.89 GB
 Data Space Total: 107.4 GB
 Data Space Available: 6.482 GB
 Metadata Space Used: 37.88 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.11 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.337 GiB
Name: ip-10-253-169-151
ID: 2OKP:CNUB:WQQ7:5RQ7:LRWT:F7CN:NW4N:M2ZQ:GSPA:3X6Q:OGVH:V4XD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Aws ec2 instance running Ubuntu 14.04 with kernel 3.13.0,
docker-compose version:

```
docker-compose version 1.7.1, build 0a9ab35
docker-py version: 1.8.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

**Steps to reproduce the issue:**
1. docker-compose up 
2. Reboot host
3. docker exec -it {container-name} bash

**Describe the results you received:**
The service in the container is running, but im getting this error:
`rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused "fork/exec /proc/self/exe: no such file or directory"`

**Describe the results you expected:**
Open a bash prompt, or execute some command

**Additional information you deem important (e.g. issue happens only occasionally):**
I'm using `restart: unless-stopped` in my docker-compose.yaml file
If I start a container after a `docker stop {container-name}`, everything works fine, the problem seems to be after rebooting the machine

**Comment by thaJeztah** [comment] 2016-08-03 21:55
Note: this looks similar to https://github.com/docker/docker/issues/22746, but that was resolved in. 1.11.2. Given that this is on 1.12. I asked @pablitok to open a new issue (https://github.com/docker/docker/issues/22746#issuecomment-237364346).

ping @mlaventure could you have a look?

**Comment by rhuddleston** [comment] 2016-08-04 04:51
I added my results to #22746 but I'm having this same issue on 1.11.2

**Comment by mlaventure** [comment] 2016-08-04 20:35
@pablitok could you provide us with the daemon logs please? If the daemon wasn't in debug mode, could you please put it in and then provide us with the logs next time it occurs? 

Thanks.

**Comment by alirezaDavid** [comment] 2016-08-07 05:38
+1
`rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused "fork/exec /proc/self/exe: no such file or directory"`
same issue here
But after restsart docker `systemctl restart docker` every things working like a charm!

**Comment by Spindel** [comment] 2016-08-09 08:17
We get this regularly on 1.12.0 as well:
`rpc error: code = 2 desc = oci runtime error: exec failed: process_linux.go:75: starting setns process caused "fork/exec /proc/self/exe: no such file or directory`

CentOS 7 /updated

```
[spider@front ~]$ docker info
Containers: 18
 Running: 18
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 29.1 GB
 Data Space Total: 32.64 GB
 Data Space Available: 3.532 GB
 Metadata Space Used: 33.71 MB
 Metadata Space Total: 339.7 MB
 Metadata Space Available: 306 MB
 Thin Pool Minimum Free Space: 3.263 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.939 GiB
Name: CENSORED
ID: UTRC:LXPI:RCDP:365H:26ZB:QS5H:3TM5:F4MO:3XN7:277X:7YOB:4EJQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Comment by mlaventure** [comment] 2016-08-09 15:41
@alirezaDavid @Spindel any chance you could provide us with the daemon logs? If it's not in debug mode, could you activate it and try to repro again? 

Thanks

**Comment by Spindel** [comment] 2016-08-09 15:58
How can I activate that without restarting containers?
(Sorry, doc's are readily accessible right now.)

**Comment by mlaventure** [comment] 2016-08-09 16:05
@Spindel you can add `"debug": true` to `/etc/docker/daemon.json` then do a `kill -HUP $(cat /var/run/docker.pid)`.

Assuming your `daemon.json` file is empty or doesn't exist, the full content would be:
```
{
	"debug": true
}
```

But that will only take effect from the moment you send the SIGHUP.

If the daemon is already stuck and assuming you're on `1.12.0`, you can also activate `live-restore` and restart it, the containers should keep on running:
```
{
	"debug": true,
	"live-restore": true
}
```

**Comment by Spindel** [comment] 2016-08-09 21:16
[docker.txt](https://github.com/docker/docker/files/409894/docker.txt)

**Comment by thaJeztah** [comment] 2016-08-09 21:32
@Spindel looks like your host is out of space (device mapper is complaining about that)

**Comment by Spindel** [comment] 2016-08-09 21:47
> [spider@front ~]$ docker images |awk '/<none>/ {print $3}' |xargs docker rmi
> $ docker exec ....
[docker.txt](https://github.com/docker/docker/files/409931/docker.txt)

And then attached file

**Comment by svdmitrij** [comment] 2016-08-16 11:22
Face same error. After ```service docker restart``` all works correctly.

**Comment by mlaventure** [comment] 2016-08-16 17:01
@Spindel could you try by using this version of `docker-runc`: https://gist.github.com/mlaventure/ebfeb1955fed2fe52a45727010575a3e/raw/473b77a67c6e338c10df052e394ba45c62e068c7/docker-runc

I've added a couple of debug messages to get what the kernel thinks the `/proc/self/exe` binary is. I can't really think of a reason this should fail aside `docker-runc` having changed in between

**Comment by sunshine69** [comment] 2016-08-18 00:36
I am not sure if it is the same bug but I hit that error
```
             "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 128,
            "Error": "oci runtime error: process_linux.go:334: running prestart hook 0 caused \"fork/exec /tmp/docker/dockerd (deleted): no such file or directory: \"",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },

```

This happen when I do a docker service update and increase the replicas from 1 to 2 for a logstash service. And teh service does not have enough instance running.

It run on a swarm of one node only with docker  1.12.1-rc1, build 7889dc7

**Comment by sunshine69** [comment] 2016-08-18 00:54
Unfortunately the behaviour is still exists.

**Comment by sunshine69** [comment] 2016-08-18 02:40
Sorry please ignore my posts, I think I did something wrong rather.

**Comment by mlaventure** [comment] 2016-08-18 14:55
@sunshine69 for your issue it seems that the original `dockerd` binary was deleted/replaced in between

**Comment by Spindel** [comment] 2016-08-18 15:03
@mlaventure I'll try that if I get the machine into that state again. It's currently working (a few reboots happened between reporting this and now)

**Comment by sunshine69** [comment] 2016-08-19 02:11
Thanks for comment, my issues is totally my mistake - in my ansible playbook I cleanup the images before stopping it so the binary got removed.

All good now with me.
Ta

**Comment by hdeadman** [comment] 2016-09-16 21:17
I got this error trying to exec into a container and it my case it was also a result of not having enough space in the thinpool. 

lvs showed there was some space in the thinpool on all the servers in the swarm but exec started working after I ran:

/usr/bin/docker rmi `/usr/bin/docker images -qa`

**Comment by rhuddleston** [comment] 2016-09-19 19:52
$ docker --version
Docker version 1.12.1, build 23cf638

See debug log attached. Let me know if there is anything else I can do to help track down this issue as it appears to be happening on all our servers.


[docker.debug.txt](https://github.com/docker/docker/files/480974/docker.debug.txt)

**Comment by rhuddleston** [comment] 2016-09-19 20:06
I also installed you patched docker-runc aattached are the logs from it
[docker.debug2.txt](https://github.com/docker/docker/files/480999/docker.debug2.txt)

**Comment by thaJeztah** [comment] 2016-09-19 23:01
ping @mlaventure ^^

**Comment by mlaventure** [comment] 2016-09-20 18:11
Still can't think of a reason or reproduce it, from the second log it expects `docker-runc` to be at `/usr/bin/docker-runc` which is the default install path.

@rhuddleston could you share your `docker info`? Also do you get the issue with every containers (e.g. even a `docker run -tid busybox top`) or just some specific one? Are you also using `docker-compose`?

**Comment by rhuddleston** [comment] 2016-09-21 03:55
I dug into this more and determined that this only happens after the nightly cronjob that cleans up docker containers/images etc runs:

for MOUNT in $(egrep 'var/lib/docker/(containers|devicemapper|aufs)' /proc/mounts | awk '{print $2}' | sort -r); do
  umount $MOUNT
done

for CONTAINER in $(docker ps -aq -f status=exited -f status=dead); do
  docker rm "${CONTAINER}"
done

USED_IMAGES=$(for IMAGE in $(docker ps -a | grep -v '^CONTAINER' | awk '{print $2}'); do docker history -q $IMAGE | head -1; done | sort | uniq)

for IMAGE in $(printf "$USED_IMAGES\n$(docker images -q | sort | uniq)" | sort | uniq -u); do
  docker rmi "${IMAGE}"
done

None of the above commands are throwing errors though. Digging in more it appears that the umount above is what is causing issues. This was introduced as docker was leaving around abandoned mount points preventing cleanup of containers/images no longer being used.

Any thoughts of how to determine which mount points are safe to unmount vs those that are necessary for running docker processes?

**Comment by mlaventure** [comment] 2016-09-21 12:56
oh, yes, you can't `umount` those outside of `docker` itself without causing issues with running containers.

Usually the one that can't be `umount` when stopping a container are the `shm` mount of the container. Those should be of the form `/var/lib/docker/containers/<container-id>/shm`. The other mounts have IDs that cannot be easily matched against a container.

If you really get a lot of mounts leak, if you could open a ticket with a reproducible scenario it'd be great.

Bear in mind that doing this (i.e. changing the state of `/var/lib/docker` outside of docker) is never going to be a supported scenario though.

**Comment by LooMaclin** [comment] 2016-10-18 06:49
After delete some images with "rmi" command i get error when execute "run" command or "build" command:
```
docker: Error response from daemon: oci runtime error: process_linux.go:334: running prestart hook 0 caused "fork/exec /usr/bin/dockerd (deleted): no such file or directory: ".
```

**Comment by mlaventure** [comment] 2016-10-18 15:49
@LooMaclin did your docker package got upgraded in between?

Deleting images wouldn't cause this kind of errors.

**Comment by pyros2097** [comment] 2016-11-03 07:45
@LooMaclin This happened to me when I upgraded docker package to the latest. I needed to restart the docker service using systemd and then it worked.

**Comment by LooMaclin** [comment] 2016-11-03 07:51
@mlaventure yep, it's upgraded.
@pyros2097 restart docker too and it worked for me.

**Comment by mlaventure** [comment] 2016-11-03 15:28
So the root cause is a docker upgrade that wasn't followed by a restart of the service as this will cause `/proc/self/exe` to refer to a now non existent file.

As such, I'm closing this for now.

Thanks for the report/help!

**Closed by mlaventure** 2016-11-03 15:28 UTC
Labels: area/runtime, kind/bug, version/1.12

**Comment by MUI-Fazy** [comment] 2016-12-20 13:10
@mlaventure 
I am getting this error with a new install of Docker 1.11.2, not with an upgrade.
Docker logs shows:
level=error msg="containerd: start container" error="oci runtime error: fork/exec /usr/bin/docker (deleted): no such file or directory: " 

While the docker run gives '/bin/bash' not found or does not exist'

First time I pull image and bring containers up, everything is fine.

I stop and remove the containers, try to bring up the problem comes. Though the restarting of Docker service resolves it but its not a feasible option for us, any advice ?

**Comment by mlaventure** [comment] 2016-12-20 16:10
@MUI-Fazy the output of the log suggests that `/usr/bin/docker` was deleted before that call though. Something in your system seems to have removed the docker binary.

You may want to reinstall docker.

**Comment by MUI-Fazy** [comment] 2016-12-20 16:15
@mlaventure 
```/usr/bin/docker``` still exists, I could do 'docker ps' 'docker images' this is happening on a new install of Docker.

**Comment by mlaventure** [comment] 2016-12-20 16:25
@MUI-Fazy can you check the path of the docker binary: `which docker`?

**Comment by MUI-Fazy** [comment] 2016-12-20 16:33
@mlaventure 
Following is the output
```bash-4.1# which docker
/usr/bin/docker```

**Comment by mlaventure** [comment] 2016-12-20 19:19
@MUI-Fazy can you reproduce it every time?

What are the exact steps in that case?

Re-reading your comments, it seems that upon start it works fine, but after you stop/remove containers the issue starts to appears, correct?

Could you share the exact commands you've been using (and the docker log if possible in debug mode)?

**Comment by MUI-Fazy** [comment] 2016-12-21 05:42
@mlaventure 
Yes I can reproduce on every machine I install Docker.

1. Install Docker Engine,
2. Pull Swarm Image and bring up swarm agent
``` 
docker run -d --name=swam-agent --restart=always swarm  join --advertise=<LocalHostName>:2375 consul://<Consul-hostname>:8500
```
4. Things would be fine for a day and perform
````
docker stop swam-agent
docker start swam-agent
```

Following error is seen while bringing up container, also after removing the container.
This is for all Images not particular to Swarm Image.
````
Error response from daemon: Container command '/swarm' not found or does not exist.
Error: failed to start containers: swarm_node
````

**Comment by thaJeztah** [comment] 2016-12-21 10:59
@MUI-Fazy could you please open a new issue, with all the details about your setup? (at least `docker version`, `docker info`). Also, be aware that docker 1.11 is no longer maintained, so installing the current (1.12) version may be advisable.

**Comment by MUI-Fazy** [comment] 2016-12-21 15:50
@thaJeztah @mlaventure 
I have opened a new issue #29640.

1.12 is not an option for us now because of the huge docker-compose orchestration we are maintaining and DAB being experimental

**Comment by thaJeztah** [comment] 2016-12-21 22:46
@MUI-Fazy `docker-compose` can still be used as usual, there are no changes in the regular functionality of docker, only swarm mode / services are _added_ as an option (but purely opt-in)

**Comment by thaJeztah** [comment] 2016-12-21 22:48
i.e. if you don't run `docker swarm init`, docker will do exactly the same things as docker 1.11, including the option to run "classic" swarm

**Comment by MUI-Fazy** [comment] 2016-12-22 12:38
@thaJeztah
It should also support Overlay networking ? , I was assuming that the Cluster Store option was no more with 1.12

**Comment by thaJeztah** [comment] 2016-12-22 13:05
@MUI-Fazy yes, you can still use overlay networking with an _external_ K/V store, but you cannot use overlay networking with an external K/V store if Swarm mode is enabled. Overlay networking with the built-in K/V store _does_ make things a lot easier though.

In docker 1.13 we are adding a feature to allow containers that are started through `docker run` (which is basically what "classic" swarm does) to use overlay networks that are created with the _internal_ k/v store. You need to create those overlay networks with the `--attachable` option.

**Comment by MUI-Fazy** [comment] 2016-12-23 08:13
@thaJeztah @mlaventure 
I tried using 1.12.3, and seeing same error.

```
ERROR: for swarm-node  Cannot start service swarm-node: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd (deleted): no such file or directory\\\"\"\n"
```

Docker Info:
```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 15
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-202:2-11665420-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 67.06 GB
 Data Space Total: 107.4 GB
 Data Space Available: 40.31 GB
 Metadata Space Used: 50.95 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.097 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /scratch/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /scratch/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.117-RHEL6 (2016-08-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.1.12-61.1.17.el6uek.x86_64
Operating System: Oracle Linux Server 6.8
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 16.49 GiB
Name: node1
ID: MSEU:AELX:FWZ3:VJUK:JHIS:6AVE:RILK:A3CP:3Q2I:JTO3:4JRZ:7KBY
Docker Root Dir: /home/node1/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://www-host.com:80
Https Proxy: http://www-host.com:80
No Proxy: localhost,docker-registry.local,/var/run/docker.sock
Registry: https://index.docker.io/v1/
Labels:
 group=test1
Cluster Store: consul://myconsul.host.com:8500
Cluster Advertise: node1.host.com:2375
Insecure Registries:
 127.0.0.0/8

```

**Comment by bizmate** [comment] 2016-12-28 00:35
I see a similar issue when running

```
$ docker run -d -v $PWD/www:/var/www php:fpm
207c334a645c0e4fd28822e5e90fff6ab35e32fa710acd0d1e8eff863d6d492d
docker: Error response from daemon: oci runtime error: no such file or directory.
```

My docker info
```
$ docker info
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 16
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 182
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.73 GiB
Name: bizmate-i7
ID: D4K6:B2ZE:7YOK:K676:EV6Q:POQR:P3SE:R6UV:5A56:SHA5:VHSF:U6LD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

Docker version
```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment] 2016-12-28 08:59
@bizmate looks like a different issue, most likely because you're bind-mounting source from your host, and possibly it doesn't have a `html` directory which the image is looking for; https://github.com/docker-library/php/blob/b66c0fa0286d0abbb8a36653e26e6992bb71b858/7.1/fpm/Dockerfile#L134

**Comment by MUI-Fazy** [comment] 2016-12-28 17:00
I think we can continue in the bug #29640

**Comment by mundimduy2506** [comment] 2017-10-04 20:20
I saw it just now and "sudo docker service stop" then  "sudo docker service start" does the trick.

**Comment by u007** [comment] 2018-07-09 08:08
im seing the same issue.
i have 2 similar service (with same image) running in docker-compose where 1 works, awhile another fail:
```
starting container process caused "process_linux.go:78: starting setns process caused \"fork/exec /proc/self/exe: no such file ...
```

```
docker exec -it app_web_1 bash
```
```
docker exec -it app_bg_1 bash
```

**Comment by vikasguptaanaplan** [comment] 2019-08-23 18:59
In case it helps someone, I was getting:

    rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:262: starting container process caused "process_linux.go:73: starting setns process caused \"fork/exec /proc/self/exe: no such file or directory\""

in my vagrant+docker setup.

Doing

      sudo systemctl restart docker

in the linux VM fixed it.
