### ISSUE TITLE
system time inside container gets desynchronized after laptop goes to sleep

### ISSUE THREAD

**Issue by markhilton** [docker/docker#32379] opened 2017-04-05 14:48 UTC
I am running Google Analytics API requests inside docker container and noticed that after my laptop goes to sleep when I wake it back up the system time inside docker container is desynchronized and GA API cannot properly refresh its OAuth2 token. 

I have to restart Docker Engine to make it work. I use OS X and docker container: 
Linux 4.9.13-moby #1 SMP x86_64 GNU/Linux

**Comment by thaJeztah** [comment] 2017-04-05 14:58
This is a Docker for Mac issue, so should be reported in the Docker for Mac issue tracker (https://github.com/docker/for-mac/issues)

This is a known issue however (see https://github.com/docker/for-mac/issues/17) the time should be synced again after a couple of minutes, but see the linked issue for more information.

I'll close the issue here, because this is not a bug in the docker "engine" itself, but specific to Docker for Mac

**Closed by thaJeztah** 2017-04-05 14:58 UTC
