### ISSUE TITLE
Error while pulling image: Get https://index.docker.io/v1/repositories/oracle/jdk/images: read tcp -> read: connection reset by peer

### ISSUE THREAD

**Issue by srinil** [docker/docker#28177] opened 2016-11-08 19:58 UTC
**Description**
Error while pulling image: Get https://index.docker.io/v1/repositories/oracle/jdk/images: read tcp  read: connection reset by peer
=====================
when trying to run docker 
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip: OK

Building image 'oracle/weblogic:12.2.1-developer' ...
Proxy  '' ...
Sending build context to Docker daemon 2.637 GB
Step 1 : FROM oracle/jdk:8
Pulling repository docker.io/oracle/jdk
Error while pulling image: Get https://index.docker.io/v1/repositories/oracle/jdk/images: read tcp  read: connection reset by peer
There was an error building the image.
its alwys giving error, this even   not working for hello world
**Steps to reproduce the issue:**
1.Download weblogic image dependencies 
2.execute sh buildDockerImage.sh -v 12.2.1 -d
3.

**Describe the results you received:**
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip: OK
=====================
Building image 'oracle/weblogic:12.2.1-developer' ...
Proxy  '' ...
Sending build context to Docker daemon 2.637 GB
Step 1 : FROM oracle/jdk:8
Pulling repository docker.io/oracle/jdk
Error while pulling image: Get https://index.docker.io/v1/repositories/oracle/jdk/images: read tcp : read: connection reset by peer
There was an error building the image

**Describe the results you expected:**
it should download the image

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
>docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   57bf6fd
 Built:        Fri May 13 01:38:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   57bf6fd
 Built:        Fri May 13 01:38:36 2016
 OS/Arch:      linux/amd64

```

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-67923214-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 31.7 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: Oracle Linux Server 7.2
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 19.45 GiB
Name: hostname
Http Proxy: http://hostname:2343
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2016-11-17 01:37
It looks like the oracle/jdk repository no longer exists on Docker Hub, IIRC it may have been deprecated by them (https://hub.docker.com/r/oracle/jdk is a 404);

```
docker pull oracle/jdk:8
Pulling repository docker.io/oracle/jdk
Error: image oracle/jdk:8 not found
```

Probably needs to be updated to https://hub.docker.com/r/oracle/openjdk/

I'll close this issue, because this is not a bug in docker, but due to changes made by Oracle. Feel free to comment after I closed

**Closed by thaJeztah** 2016-11-17 01:37 UTC
Labels: version/1.10
