### ISSUE TITLE
Can't open /proc/9368/status: No such file or directory

### ISSUE THREAD

**Issue by jiulongzaitian** [docker/docker#12835] opened 2015-04-28 02:52 UTC
This is Error in messages:

Apr 28 10:47:29 aaa abrt[50046]: Can't open /proc/9356/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50050]: Can't open /proc/9876/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50053]: Can't open /proc/63634/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50057]: Can't open /proc/9878/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50059]: Can't open /proc/63636/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50064]: Can't open /proc/9880/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50065]: Can't open /proc/9358/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50066]: Can't open /proc/63638/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50073]: Can't open /proc/9882/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50074]: Can't open /proc/63640/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50078]: Can't open /proc/9884/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50081]: Can't open /proc/63642/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50083]: Can't open /proc/9360/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50085]: Can't open /proc/9886/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50090]: Can't open /proc/63644/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50093]: Can't open /proc/9888/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50096]: Can't open /proc/63646/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50099]: Can't open /proc/9890/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50102]: Can't open /proc/9362/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50104]: Can't open /proc/63648/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50105]: Can't open /proc/9892/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50112]: Can't open /proc/63650/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50113]: Can't open /proc/9894/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50118]: Can't open /proc/63652/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50119]: Can't open /proc/9896/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50120]: Can't open /proc/9364/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50127]: Can't open /proc/63654/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50128]: Can't open /proc/9898/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50155]: Can't open /proc/9906/status: No such file or directory
Apr 28 10:47:30 aaa abrt[50157]: Can't open /proc/9368/status: No such file or directory

and Need more time to get **docker info** result：

#time docker info

Containers: 6
Images: 2173
Storage Driver: devicemapper
 Pool Name: docker-253:2-268436480-pool
 Data file: /srv/docker/devicemapper/devicemapper/data
 Metadata file: /srv/docker/devicemapper/devicemapper/metadata
 Data Space Used: 24040.9 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 80.4 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: lxc-0.9.0
Kernel Version: 2.6.32-925.431.23.3.letv.el6.x86_64

real    0m38.232s
user    0m0.007s
sys     0m0.006s

#time docker version
Client version: 1.0.0
Client API version: 1.12
Go version (client): go1.2
Git commit (client): 63fe64c/1.0.0
Server version: 1.0.0
Server API version: 1.12
Go version (server): go1.2
Git commit (server): 63fe64c/1.0.0

real    0m1.499s
user    0m0.011s
sys     0m0.008s

**Comment by LK4D4** [comment] 2015-04-28 02:53
@jiulongzaitian You're using very old docker version. Can you try to update?

**Comment by jiulongzaitian** [comment] 2015-04-28 02:59
@LK4D4  Because Somme online service is running On docker , I Can not update.

**Comment by LK4D4** [comment] 2015-04-28 06:22
@jiulongzaitian You really shouldn't rely on any service with such old version :/

**Comment by jiulongzaitian** [comment] 2015-04-28 07:23
@LK4D4  tks   ,I attempt to update.

**Comment by Silence2012** [comment] 2015-04-28 07:52
If you stop the container and restart it later , the pid of the process which is running in the container will change . Do you  verify that   those files  exists ?

**Comment by jiulongzaitian** [comment] 2015-04-28 08:53
@Silence2012  I Can not find those files in /proc .  But I do not know how to deal with it .

**Comment by ahmetalpbalkan** [comment] 2015-04-29 18:50
> Because Somme online service is running On docker , I Can not update.

@jiulongzaitian  you should probably design your system in a way that you can update the underlying infrastructure frequently.

**Comment by thaJeztah** [comment] 2015-06-08 06:40
@jiulongzaitian I'm going to close this issue for now, because this is a very old version of Docker, and the issue you're having could be fixed already in the current release.

I suggest to make sure you're system is fully up to date and see if you're still able to reproduce.

Feel free to comment here if you're still able to reproduce after updating and I'll reopen.

**Closed by thaJeztah** 2015-06-08 06:40 UTC
