### ISSUE TITLE
Release archive path prefix changed in 1.11 Linux tarballs

### ISSUE THREAD

**Issue by lox** [docker/docker#22491] opened 2016-05-04 01:05 UTC
```bash
curl -fL --silent "https://get.docker.com/builds/Linux/x86_64/docker-1.10.3.tgz" | tar -xvz
x usr/
x usr/local/
x usr/local/bin/
x usr/local/bin/docker
```

vs

```bash
curl -fL --silent "https://get.docker.com/builds/Linux/x86_64/docker-1.11.1.tgz" | tar -xvz
x docker/
x docker/docker
x docker/docker-containerd-shim
x docker/docker-containerd
x docker/docker-containerd-ctr
x docker/docker-runc
```

**Comment by HackToday** [comment] 2016-05-04 04:33
it seems it is not an issue. Please close it. It is docker 1.11.* new change

**Comment by lox** [comment] 2016-05-04 04:41
It seems like it's a bug to me. Docker 1.11 introduced new executables, I don't see why that should introduce a different directory prefix in the release archive.

**Comment by lox** [comment] 2016-05-04 04:43
Note the different prefixes: `docker/` and `usr/local/bin/`.

**Comment by justincormack** [comment] 2016-05-04 09:37
This was intentional, not a bug. The new executables are not all designed to be installed into `/usr/local/bin`, not that that was ever where people necessarily installed them anyway.

**Comment by thaJeztah** [comment] 2016-05-04 11:53
Yes, this was a deliberate change indeed, for example, the install location using the deb / yum packages is `/usr/bin`, and the decision was made remove the prefix to more clearly leave it to the "consumer" of those packages to decide where to install the binaries. The "docker" wrapper directory was kept to prevent inadvertently polluting the location where the archive is extracted.

**Closed by thaJeztah** 2016-05-04 11:53 UTC
