### ISSUE TITLE
does service create support docker option "privileged" or ":z" for -v?

### ISSUE THREAD

**Issue by hehailong5** [docker/docker#29120] opened 2016-12-05 09:03 UTC
version: 1.12.3

I will need to mount some privileged files on the host machine into the container, such as /root/.config/sth.
we can use --privileged or -v source:target:z in the docker run to achieve this, but is it possible when use docker service create?

**Comment by thaJeztah** [comment] 2016-12-05 13:13
No, `--privileged` is not supported, see https://docs.docker.com/engine/reference/commandline/service_create/, https://github.com/docker/docker/issues/25303, and  https://github.com/docker/docker/issues/24862.

Services do not have `-v` / `--volume`, but you _can_ specify these options using the `--mount` flag, again, see the documentation: https://docs.docker.com/engine/reference/commandline/service_create/#/add-bind-mounts-or-volumes

Please keep in mind that the GitHub issue tracker is not a general support forum, but for reporting bugs and feature requests. For other discussions, consider using https://forums.docker.com, or register for the Docker Community Slack channel; https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/

I'll close this issue because this is not a bug or feature request

**Closed by thaJeztah** 2016-12-05 13:13 UTC
Labels: area/swarm
