### ISSUE TITLE
ADD: Cache HTTP downloads for faster builds

### ISSUE THREAD

**Issue by mcandre** [docker/docker#18710] opened 2015-12-16 15:42 UTC
When an `ADD` http resource takes more than a few seconds to download, it really slows down the build. Could Docker cache these, e.g. in `~/.docker/downloads`, so that repeated builds are faster and Dockerfile experimentation becomes more enjoyable?

**Comment by thaJeztah** [comment] 2015-12-16 15:49
Thanks for suggesting, this looks like a duplicate of https://github.com/docker/docker/issues/15717, so I'll close this one. Please subscribe to that issue (using the "subscribe" button) to keep up to date on progress

**Closed by thaJeztah** 2015-12-16 15:49 UTC
