### ISSUE TITLE
Docker consumes all disk spaces

### ISSUE THREAD

**Issue by bangn** [docker/docker#23146] opened 2016-06-01 00:21 UTC
Hi,

I'm running docker beta on my OSX El Capitan.
I am not running any images or having any images in my machine.
However, docker has consumed all of my disk space.

```
~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
~$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
~$
```

```
~$ df -h
Filesystem      Size   Used  Avail Capacity  iused ifree %iused  Mounted on
/dev/disk1     112Gi  111Gi  188Mi   100% 29273639 48087  100%   /
devfs          188Ki  188Ki    0Bi   100%      650     0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%        0     0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%        0     0  100%   /home
```

```
~$ du | sort -rn | head
166833736       .
151191280       ./Library
146696152       ./Library/Containers
146560216       ./Library/Containers/com.docker.docker/Data
146560216       ./Library/Containers/com.docker.docker
146558216       ./Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux
58965984        ./Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/log
```
Any help would be greatly appreciated.

Cheers,
Bang

**Comment by thaJeztah** [comment] 2016-06-01 00:24
Can you check if you're running beta 13.1? There was a bug in beta 13 that made the log files to grow really big, but was resolved in a hotfix in beta 13.1

**Comment by bangn** [comment] 2016-06-01 00:36
Hi thaJeztah,

Thank you for your response

I'm running `Version 1.11.1-beta13 (build: 7975) 16dbe555c7dd4304521b21e8286d83fe4864c15c`

Cheers,
Bang

**Comment by haritnin** [comment] 2016-06-01 02:03
I deleted com.docker.driver.amd64-linux and updated my docker beta and it recreated the folder again.
Mine too was consuming close to 40G.

**Comment by thaJeztah** [comment] 2016-06-01 08:37
The hotfix should delete all log files automatically during update, so probably that'll fix it for you, but you can delete the directory yourself (this will also delete the VM's filesystem though, so if you decide to do that, you'll loose your containers and images). There's also a "reset to factory settings" button in the preference pane, that will do the same.

**Comment by justincormack** [comment] 2016-06-01 09:02
Yes the update to 1.13.1 or later should fix the issue by deleting the extra logs, apologies for the bug.

**Comment by justincormack** [comment] 2016-06-01 09:08
I am going to close this as the issue is fixed in the released version of docker for mac, but let us know if the space is not freed on upgrade.

**Closed by justincormack** 2016-06-01 09:08 UTC
Labels: group/pinata

**Comment by alairock** [comment] 2016-06-04 03:55
Not trying to story top anyone but.... 
<img width="304" alt="screen shot 2016-06-03 at 9 54 52 pm" src="https://cloud.githubusercontent.com/assets/1480236/15797448/e3f75b14-29d5-11e6-8286-6aa4e1d871bd.png">

**Comment by alairock** [comment] 2016-06-04 03:56
Even sadder: 
<img width="291" alt="screen shot 2016-06-03 at 9 56 10 pm" src="https://cloud.githubusercontent.com/assets/1480236/15797449/052c5eba-29d6-11e6-9136-7e36a07fbd3c.png">

**Comment by thaJeztah** [comment] 2016-06-04 11:02
@alairock are you running beta 13.1?

**Comment by alairock** [comment] 2016-06-04 13:38
Not sure. I've since upgraded to latest. Things seem better.
