### ISSUE TITLE
Another opaque EOF error from POST /containers/create

### ISSUE THREAD

**Issue by brandones** [docker/docker#10928] opened 2015-02-21 22:30 UTC
I have a Dockerized project I've successfully built and run on OSX (with boot2docker) and Ubuntu with no problems. I installed docker on Debian 7.8 with Kernel 3.16:
```
$ uname -a
Linux bitnami-jenkins 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt2-1~bpo70+1 (2014-12-08) x86_64 GNU/Linux
```

On that machine, I run the daemon:

    $ sudo killall docker
    $ sudo docker -D -d

In another terminal tab, I run a test:

    $ sudo docker run ubuntu:14.04 /bin/echo 'Hello world'
    FATA[0000] Error response from daemon: EOF  

All the daemon log reports is

    DEBU[0026] Calling POST /containers/create              
    INFO[0026] POST /v1.17/containers/create                
    INFO[0026] +job create()                                
    EOF
    INFO[0026] -job create() = ERR (1)                      
    ERRO[0026] Handler for POST /containers/create returned error: EOF 
    ERRO[0026] HTTP Error: statusCode=500 EOF  

Even if this error is somehow my fault, the fact that this problem is so completely opaque should be considered a bug. Any advice about how to proceed would be greatly appreciated. I'll comment with the complete daemon log.

**Comment by brandones** [comment] 2015-02-21 22:31
```
$ sudo docker -D -d
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Registering GET, /_ping                      
DEBU[0000] Registering GET, /events                     
DEBU[0000] Registering GET, /images/get                 
DEBU[0000] Registering GET, /images/{name:.*}/get       
DEBU[0000] Registering GET, /images/{name:.*}/history   
DEBU[0000] Registering GET, /containers/ps              
DEBU[0000] Registering GET, /containers/json            
DEBU[0000] Registering GET, /exec/{id:.*}/json          
DEBU[0000] Registering GET, /images/json                
DEBU[0000] Registering GET, /images/search              
DEBU[0000] Registering GET, /images/{name:.*}/json      
DEBU[0000] Registering GET, /containers/{name:.*}/json  
DEBU[0000] Registering GET, /version                    
DEBU[0000] Registering GET, /images/viz                 
DEBU[0000] Registering GET, /containers/{name:.*}/export 
DEBU[0000] Registering GET, /containers/{name:.*}/changes 
DEBU[0000] Registering GET, /info                       
DEBU[0000] Registering GET, /containers/{name:.*}/top   
DEBU[0000] Registering GET, /containers/{name:.*}/logs  
DEBU[0000] Registering GET, /containers/{name:.*}/stats 
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws 
DEBU[0000] Registering POST, /exec/{name:.*}/resize     
DEBU[0000] Registering POST, /images/load               
DEBU[0000] Registering POST, /containers/{name:.*}/pause 
DEBU[0000] Registering POST, /containers/{name:.*}/start 
DEBU[0000] Registering POST, /containers/{name:.*}/attach 
DEBU[0000] Registering POST, /exec/{name:.*}/start      
DEBU[0000] Registering POST, /containers/{name:.*}/exec 
DEBU[0000] Registering POST, /commit                    
DEBU[0000] Registering POST, /containers/create         
DEBU[0000] Registering POST, /containers/{name:.*}/kill 
DEBU[0000] Registering POST, /containers/{name:.*}/wait 
DEBU[0000] Registering POST, /containers/{name:.*}/resize 
DEBU[0000] Registering POST, /images/create             
DEBU[0000] Registering POST, /containers/{name:.*}/restart 
DEBU[0000] Registering POST, /containers/{name:.*}/stop 
DEBU[0000] Registering POST, /containers/{name:.*}/copy 
DEBU[0000] Registering POST, /containers/{name:.*}/rename 
DEBU[0000] Registering POST, /auth                      
DEBU[0000] Registering POST, /build                     
DEBU[0000] Registering POST, /images/{name:.*}/push     
DEBU[0000] Registering POST, /images/{name:.*}/tag      
DEBU[0000] Registering POST, /containers/{name:.*}/unpause 
DEBU[0000] Registering DELETE, /images/{name:.*}        
DEBU[0000] Registering DELETE, /containers/{name:.*}    
DEBU[0000] Registering OPTIONS,                         
DEBU[0000] docker group found. gid: 998                 
DEBU[0000] Using graph driver aufs                      
DEBU[0000] Migrating existing containers                
DEBU[0000] Creating images graph                        
DEBU[0000] Restored 70 elements                         
DEBU[0000] Creating repository list                     
DEBU[0000] Reloaded graph with 2 grants expiring at 2015-02-22 22:47:54.722420237 +0000 UTC 
INFO[0000] +job init_networkdriver()                    
DEBU[0000] /sbin/iptables, [-C POSTROUTING -t nat -s 172.17.42.1/16 ! -o docker0 -j MASQUERADE] 
DEBU[0000] /sbin/iptables, [-D FORWARD -i docker0 -o docker0 -j DROP] 
DEBU[0000] /sbin/iptables, [-C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [-C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [-C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0000] /sbin/iptables, [-t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [-t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /sbin/iptables, [-t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [-t nat -D PREROUTING -j DOCKER] 
DEBU[0000] /sbin/iptables, [-t nat -D OUTPUT -j DOCKER] 
DEBU[0000] /sbin/iptables, [-t nat -F DOCKER]           
DEBU[0000] /sbin/iptables, [-t nat -X DOCKER]           
DEBU[0000] /sbin/iptables, [-t nat -n -L DOCKER]        
DEBU[0000] /sbin/iptables, [-t nat -N DOCKER]           
DEBU[0000] /sbin/iptables, [-C -m addrtype --dst-type LOCAL] 
DEBU[0000] /sbin/iptables, [-t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [-C -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8] 
DEBU[0000] /sbin/iptables, [-t nat -A OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /sbin/iptables, [-t filter -n -L DOCKER]     
DEBU[0000] /sbin/iptables, [-C FORWARD -o docker0 -j DOCKER] 
INFO[0000] -job init_networkdriver() = OK (0)           
INFO[0000] WARNING: mountpoint for memory not found

DEBU[0000] Loaded container 11ef6f936b52d3e61fe8b6c906638eeb137376fb0b89de70a3ed73c028845077 
DEBU[0000] Loaded container 2d8570863bbdf7d8ca9e42dcb305e3cfbe402bad0d995d7183bf16cd2d0922a6 
DEBU[0000] Loaded container 449d97315bf3af770d4f07a9b1a37e389720223226b004c87d1673d43c711740 
DEBU[0000] Loaded container 5adb43fea6e1ea5c3deccc65a45287aa5b7e3a527b1ae93d1d3901af6ac5e46c 
DEBU[0000] Loaded container 5bf80eaed4fe51903238595790b81c4a94f910169fa22cdd6d68973627bf6af5 
DEBU[0000] Loaded container 5e3fdf82b505d88b7965bac16f442fb6da60288cd6a833c5069219284f03a55e 
DEBU[0000] Loaded container 653c8d54054bcab34d1e75094b18fa775fc0a84a4d3695c3d78fa7655510cf85 
DEBU[0000] Loaded container 7edb49c949769063317384cc8f5bb2f06d304a3500460603622fa7834ac38d73 
DEBU[0000] Loaded container 800f14c8e7bdc6de1aa99f1a9998c51d04e91974bcec6de1ef6247221c1ec16e 
DEBU[0000] Loaded container a2e3055e3089c1e0df3b4c411f3b816e2d4d2d9033cb3c9c95b6674824cbfd85 
DEBU[0000] Loaded container cd35db8ddb5d8a116b32ce3056810b00b9c62f14c210c77a42f837b44176aeb4 
DEBU[0000] Loaded container e838a2ea291a0b76e4b9be7160a042fe551253ae72d579fe762963c1ee70ec23 
DEBU[0000] Loaded container f7b1f8fa38ce355ca9e9705159ac3403431b7c792e9e9436b0e5d3064521b4af 
DEBU[0000] Restarting containers...                     
INFO[0000] docker daemon: 1.5.0 a8a31ef; execdriver: native-0.2; graphdriver: aufs 
INFO[0000] +job acceptconnections()                     
INFO[0000] -job acceptconnections() = OK (0)            
DEBU[0026] Calling POST /containers/create              
INFO[0026] POST /v1.17/containers/create                
INFO[0026] +job create()                                
EOF
INFO[0026] -job create() = ERR (1)                      
ERRO[0026] Handler for POST /containers/create returned error: EOF 
ERRO[0026] HTTP Error: statusCode=500 EOF 
```

**Comment by estesp** [comment] 2015-02-24 15:07
First of all, thanks for the logs, and it looks like this is Docker 1.5.0, but could you run `docker version` and `docker info` (with the daemon running) and add that content here?

The `docker run` command you posted should run fine--and I assume you can run that elsewhere? Are all `docker run` commands failing in this way, or just this one, or only intermittently?  Given I can't reproduce, it would help to understand the scenario as there are lots of functional pieces during the handling of `/containers/create` and nothing jumps out at me that would generate an `EOF` or has "bare output" like you see above (e.g. not using the log API).

**Comment by jgangemi** [comment] 2015-02-24 15:30
i see the same error if i try pushing to a docker regsitry and don't have the `X-Registry-Auth` set and/or its value is incorrect so some better handling around this case would be great.

happy to file a separate issue on this as well.

**Comment by estesp** [comment] 2015-02-24 15:54
@brandones can you try `docker pull ubuntu:14.04` before your Docker run?  It does seem that it could be registry related, although that may have been a transient failure--but it would be good to find where in the codepath it fails.  My only problem is that you should have seen a message on client side: **Unable to find image '..' locally** before it tried to contact the registry.

@jgangemi it could be the push/pull code isn't properly handling an unexpected response, but given yours is push, maybe it makes sense to open a separate issue.

**Comment by jgangemi** [comment] 2015-02-24 16:38
filed, thanks!

**Comment by brandones** [comment] 2015-02-24 17:20
```
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

$ docker info
Containers: 13
Images: 64
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 95
Execution Driver: native-0.2
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 1
Total Memory: 3.625 GiB
Name: bitnami-jenkins
ID: VGTH:LS7D:XVWH:KCUR:CDOY:25H2:3K74:KM3Z:35Z7:KYF4:LNLC:KRKQ
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 14
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No memory limit support
WARNING: No swap limit support
```

It was failing with the run command provided and also with building my project with `sudo docker build`, which has base image `ubuntu:14.04`. It would upload build context and then fail immediately after.

Running `docker pull ubuntu:14.04` fixed the problem -- both the run command and build command work fine now. Thank you so much for the support.

**Comment by estesp** [comment] 2015-02-24 17:25
ping @dmp42 @dmcgowan any thoughts on where a pull from within a "missing graph image" (from either `docker build` or `docker run` on a system without the image) might end up in `EOF` instead of doing the pull?  I assume this is some corner case or Hub connectivity issue, as 1.5.0 isn't broken on pulling images in general..

**Comment by dmp42** [comment] 2015-02-24 18:14
From https://github.com/docker/docker/issues/10928#issuecomment-75396690 I don't see anything related to hub/network communication...

@dmcgowan ?

**Comment by duglin** [comment] 2015-04-13 01:45
@brandones are you still seeing this? I just tried it and I don't see the issue.  Perhaps its been fixed and we can close it?

**Comment by dmcgowan** [comment] 2015-04-13 17:24
We added some better error logging since 1.5.0 which should help diagnose if there was a connectivity issue with the hub, however I also don't see any indication that a pull was being attempted.

**Comment by brandones** [comment] 2015-04-13 18:14
Just spun up a machine on which the failure occurred last time, was unable to repro.

**Comment by thaJeztah** [comment] 2015-04-13 19:15
Thanks for reporting back, @brandones I'm going to close this issue because you're no longer able to reproduce.

Feel free to "ping" me if you encounter this problem again, then I will re-open.

**Closed by thaJeztah** 2015-04-13 19:15 UTC
Labels: Distribution
