### ISSUE TITLE
Install NFS in docker container

### ISSUE THREAD

**Issue by teknowmics** [docker/docker#20430] opened 2016-02-18 06:30 UTC
Hello,

We are trying to install NFS service in docker container but getting following error message when trying to start the service.

[root@sweb ~]# service rpcbind start
Starting rpcbind:                                          [  OK  ]
[root@sweb ~]# service nfs start
FATAL: Could not load /lib/modules/3.10.0-327.el7.x86_64/modules.dep: No such file or directory
Starting NFS services:                                     [  OK  ]
Starting NFS mountd:                                       [  OK  ]
Starting NFS daemon: rpc.nfsd: Unable to access /proc/fs/nfsd errno 2 (No such file or directory).
Please try, as root, 'mount -t nfsd nfsd /proc/fs/nfsd' and then restart rpc.nfsd to correct the problem
                                                           [FAILED]
[root@sweb ~]#

[root@sweb ~]# cat /etc/issue
CentOS release 6.7 (Final)
Kernel \r on an \m
[root@sweb ~]# uname -a
Linux sweb 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

nfsd kernel module is loaded on host system.

[root@dockerhost ~]# lsmod | grep nfs
nfsd                  302418  1 
auth_rpcgss            59343  1 nfsd
nfs_acl                12837  1 nfsd
lockd                  93600  1 nfsd
grace                  13295  2 nfsd,lockd
sunrpc                300464  7 nfsd,auth_rpcgss,lockd,nfs_acl

Please advise.

**Comment by HackToday** [comment] 2016-02-18 14:04
Did this nfs need to access host resource ?  And how do you start this container ? Could you append your 
`docker run` specific commands you run ?

**Comment by thaJeztah** [comment] 2016-02-18 14:11
I suspect the nfs server may need more privileges, e.g. this example ("use at your own risk") needs to be run with `--privileged` https://hub.docker.com/r/cpuguy83/nfs-server/

**Comment by teknowmics** [comment] 2016-02-18 14:53
Thank you Sebastiaan for the comment.

I was able to start nfs service after running docker command with 
--privileged option

~]# docker run -dti --volumes-from storage-server -p 80:80 -p 111:111 -p 
443:443 -p 2049:2049 -p 3306:3306 -p 8983:8983 -p 2181:2181 -p 5672:5672 
-p 15672:15672 --hostname=sdweb --name=sdweb --privileged sdweb:v3  bash 
-c 'python /start-sd.py & bash'


[root@sweb ~]# /etc/init.d/rpcbind start
Starting rpcbind:                                          [  OK  ]
[root@sweb ~]# /etc/init.d/nfs start
FATAL: Could not load 
/lib/modules/3.10.0-327.4.5.el7.x86_64/modules.dep: No such file or 
directory
Starting NFS services:                                    [  OK  ]
Starting NFS mountd:                                     [  OK  ]
Starting NFS da                                              [  OK ]
Starting RPC idmapd:                                     [  OK  ]

What I'm achieving like as follows

I have data container 'storage-server' and application container 
'sdweb'. Data container hosts MySQL data directory and applications 
data. Volume of Data container is mounted in application container as 
mount point /storage. All data are located in this directory

[root@sweb ~]# df -h
Filesystem            Size  Used Avail Use% Mounted on
rootfs                 10G  1.6G  8.5G  16% /
/dev/mapper/docker-202:2-100791979-5514ecf6cdcc9aa513b40ae032d69bf7371974905b06901c6636f4d3145f4277
                        10G  1.6G  8.5G  16% /
tmpfs                 1.8G     0  1.8G   0% /dev
tmpfs                 1.8G     0  1.8G   0% /sys/fs/cgroup
/dev/xvda2             27G  7.6G   20G  29% /storage
/dev/xvda2             27G  7.6G   20G  29% /etc/resolv.conf
/dev/xvda2             27G  7.6G   20G  29% /etc/hostname
/dev/xvda2             27G  7.6G   20G  29% /etc/hosts
shm                    64M     0   64M   0% /dev/shm

I would like to export this directory '/storage' using NFS and would 
like to mount to another windows server. This /storage is actually a 
volume of data container. I'm trying to install NFS service in 
application container and export /storage directory since it is mounted 
from data container.

Somehow I'm still have problem with mounting it on windows server.

C:\Users\Administrator>mount 192.168.2.126:/storage H:
Network Error - 53

Type 'NET HELPMSG 53' for more information.

Where IP 192.168.2.126 is the static IP of host machine where docker 
daemon is running.

**Comment by thaJeztah** [comment] 2016-02-18 15:15
@teknowmics alright, that's a start. Ideally, you don't want to use `--privileged`, because that's giving far too many capabilities to the container, so you may want to look into `--cap-add` to see if you can give more fine-grained capabilities to the container https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

I'm going to close this issue, because this is not a bug in docker, but feel free to continue the discussion here.

**Closed by thaJeztah** 2016-02-18 15:15 UTC

**Comment by teknowmics** [comment] 2016-02-19 10:22
Thank you for the reply. Kindly allow me to continue the discussion regarding the issue I'm facing now.

I have a data container 'storage-server' and a application container 'sdweb'. Data container hosts MySQL data directory and applications data. Volume of Data container is mounted in application container as mount point /storage. All data are located in this directory

Data container created using the command

docker create -v /storage --hostname=storage-server --name=storage-server treasureboat/centos6 /bin/true

I would like to export this directory '/storage' using NFS and would like to mount it to another machine. This /storage is actually a volume of data container ( storage-server). I've installed NFS service in application container and exported /storage directory since it is mounted from data container.

When I try to mount the NFS share from another machine, it is showing following error message.

~]# mount 192.168.2.126:/storage /nfs
mount.nfs: access denied by server while mounting 192.168.2.126:/storage

Where IP 192.168.2.126 is the static IP of host machine where docker daemon is running.


NFS settings inside app container are below

 ~]# cat /etc/exports 
/storage     *(rw,sync,anonuid=500,anongid=500,no_subtree_check)

 ~]# showmount -e localhost
Export list for localhost:
/storage *

sdweb ~]# ifconfig 
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:02  
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8188 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4572 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:11807383 (11.2 MiB)  TX bytes:318550 (311.0 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:35068 errors:0 dropped:0 overruns:0 frame:0
          TX packets:35068 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:4542996 (4.3 MiB)  TX bytes:4542996 (4.3 MiB)

[root@sdweb ~]# rpcinfo -p 172.17.0.2
   program vers proto   port  service
    100000    4   tcp    111  portmapper
    100000    3   tcp    111  portmapper
    100000    2   tcp    111  portmapper
    100000    4   udp    111  portmapper
    100000    3   udp    111  portmapper
    100000    2   udp    111  portmapper
    100005    1   udp  39492  mountd
    100005    1   tcp  46623  mountd
    100005    2   udp  56478  mountd
    100005    2   tcp  41256  mountd
    100005    3   udp  59475  mountd
    100005    3   tcp  50161  mountd
    100003    2   tcp   2049  nfs
    100003    3   tcp   2049  nfs
    100003    4   tcp   2049  nfs
    100227    2   tcp   2049  nfs_acl
    100227    3   tcp   2049  nfs_acl
    100003    2   udp   2049  nfs
    100003    3   udp   2049  nfs
    100003    4   udp   2049  nfs
    100227    2   udp   2049  nfs_acl
    100227    3   udp   2049  nfs_acl
    100021    1   udp  40658  nlockmgr
    100021    3   udp  40658  nlockmgr
    100021    4   udp  40658  nlockmgr
    100021    1   tcp  33936  nlockmgr
    100021    3   tcp  33936  nlockmgr
    100021    4   tcp  33936  nlockmgr
    100024    1   udp  58339  status
    100024    1   tcp  32883  status

I run the container using following command

~]# docker run -dti --volumes-from storage-server -p 80:80 -p 111:111 -p 443:443 -p 2049:2049 -p 3306:3306 -p 8983:8983 -p 2181:2181 -p 5672:5672 -p 15672:15672 --hostname=sdweb --name=sdweb --privileged sdweb:v3  bash -c 'python /start-sd.py & bash'

I'm trying to mount the exported directory from a machine having IP 192.168.2.101 which is on same network of docker host ( IP 192.168.2.126 )

**Comment by marcwagner** [comment] 2016-10-16 07:13
Have you used the suggested --cap-add flag instead of --privileged? 
It looks like --cap-add=SYS_MODULE,NET_ADMIN should do the trick.

**Comment by thaJeztah** [comment] 2016-10-16 17:37
If you just want access to a NFS share; the built in volume driver supports doing this; https://docs.docker.com/engine/reference/commandline/volume_create/

**Comment by marcwagner** [comment] 2016-10-16 19:23
Actually, I want to run an nfs server. Such as this one: https://github.com/cpuguy83/docker-nfs-server
But i would rather do it without the --priveleged flag.

**Comment by jojoob** [comment] 2016-10-24 07:28
> Have you used the suggested --cap-add flag instead of --privileged? 
It looks like --cap-add=SYS_MODULE,NET_ADMIN should do the trick. Do you agree?

I tried it with SYS_MODULE and NET_ADMIN (actually it is `docker run --cap-add=SYS_MODULE --cap-add=NET_ADMIN imagename`) but it didn't work: same error.
For me it works with just the SYS_ADMIN privilege.

**Comment by k3a** [comment] 2018-11-11 16:45
FYI NFS server requires SYS_ADMIN capability because it does "/bin/mount -t nfsd nfsd /proc/fs/nfsd". Maybe pre-mounting it using --mount would avoid using SYS_ADMIN (not tested)
