### ISSUE TITLE
mupx - "docker: invalid hostname format for --hostname" while verifying deployment

### ISSUE THREAD

**Issue by YosBD** [docker/docker#23122] opened 2016-05-31 10:41 UTC
[ec2-52-51-239-208.eu-west-1.compute.amazonaws.com] - Uploading bundle
[ec2-52-51-239-208.eu-west-1.compute.amazonaws.com] - Uploading bundle: SUCCESS
[ec2-52-51-239-208.eu-west-1.compute.amazonaws.com] - Sending environment variables
[ec2-52-51-239-208.eu-west-1.compute.amazonaws.com] - Sending environment variables: SUCCESS
[ec2-52-51-239-208.eu-west-1.compute.amazonaws.com] - Initializing start script
[ec2-52-51-239-208.eu-west-1.compute.amazonaws.com] - Initializing start script: SUCCESS
[ec2-52-51-239-208.eu-west-1.compute.amazonaws.com] - Invoking deployment process
[ec2-52-51-239-208.eu-west-1.compute.amazonaws.com] x Invoking deployment process: FAILED
	
	-----------------------------------STDERR-----------------------------------
	Error response from daemon: No such container: gefen_cms
	Error response from daemon: No such container: gefen_cms-frontend
	docker: invalid hostname format for --hostname: ip-172-31-19-146-gefen_cms.
	See 'docker run --help'.
	-----------------------------------STDOUT-----------------------------------
	base: Pulling from meteorhacks/meteord
	4d690fa98655: Already exists
	a3ed95caeb02: Already exists
	0638f01c6191: Already exists
	086f3bb36259: Already exists
	Digest: sha256:684021facd5847f6a4ee2f0095fd26b4d7f5af2b776150531914d43fd0eb889b
	Status: Image is up to date for meteorhacks/meteord:base
	----------------------------------------------------------------------------

**Comment by thaJeztah** [comment] 2016-05-31 11:05
This is not a bug; it looks like you specified an invalid hostname. Docker validates if hostnames are RFC 1123 compliant (see https://tools.ietf.org/html/rfc1123). https://github.com/docker/docker/pull/20566

Removing the underscore in your hostname, and replacing it with a hyphen (`ip-172-31-19-146-gefen-cms`) should make this work.

I'll close this issue, because this is not a bug in Docker, but feel free to comment after I closed

**Closed by thaJeztah** 2016-05-31 11:05 UTC
