### ISSUE TITLE
Starting containers should not be considered for load balancing on service upscaling

### ISSUE THREAD

**Issue by dimw** [docker/docker#26067] opened 2016-08-27 00:28 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 58
 Running: 3
 Paused: 0
 Stopped: 55
Images: 41
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-524491-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.275 GB
 Data Space Total: 107.4 GB
 Data Space Available: 106.1 GB
 Metadata Space Used: 4.481 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: active
 NodeID: REDACTED
 Is Manager: true
 ClusterID: REDACTED
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: REDACTED
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.671 GiB
Name: REDACTED
ID: REDACTED
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 58
 Goroutines: 162
 System Time: REDACTED
 EventsListeners: 3
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VPS (KVM)

**Steps to reproduce the issue:**
1. Create a Dockerfile for a slow-starting container image, e.g. with `sleep` (or a Java + Spring application), with a running HTTP server, exposed port, and health check (picked _[dockercloud/hello-world](https://hub.docker.com/r/dockercloud/hello-world/)_ here):
   
   ```
   FROM dockercloud/hello-world
   
   RUN apk add --update curl && \
       rm -rf /var/cache/apk/*
   
   HEALTHCHECK --interval=1m --timeout=3s \
       CMD curl -f http://127.0.0.1:80/ || exit 1
   
   CMD sleep 20 && php-fpm -d variables_order="EGPCS" && (tail -F /var/log/nginx/access.log &) && exec nginx -g "daemon off;"
   ```
   
   ...and create the _slow-container_ image:
   
   ```
   # docker build -t slow-container .
   ```
2. Create a _slow-service_:
   
   ```
   # docker service create --publish 8080:80 --name slow-service --replicas=1 slow-container
   ev070x9sh8el7frmqw57v97ts
   ```
   
   You may want to ensure that the health check is working properly, which indicates container as _starting_ first:
   
   ```
   # docker ps
   CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                            PORTS               NAMES
   91cc5a672b24        slow-container:latest                       "/bin/sh -c 'sleep 20"   2 seconds ago       Up 1 seconds (health: starting)   80/tcp              slow-service.1.cqupqtrfeiw9xyhumr6q5za6w
   ```
   
   The status becomes _healthy_ after some time:
   
   ```
   # docker ps
   CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                    PORTS               NAMES
   91cc5a672b24        slow-container:latest                       "/bin/sh -c 'sleep 20"   2 minutes ago       Up 2 minutes (healthy)    80/tcp              slow-service.1.cqupqtrfeiw9xyhumr6q5za6w
   ```
3. Ensure service is responding properly to HTTP requests:
   
   ```
   # while true; do curl -s --show-error -I http://127.0.0.1:8080 | head -n 1; sleep 1; done
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   ^C
   ```
4. Scale the service to two nodes:
   
   ```
   # docker service scale slow-service=2
   slow-service scaled to 2
   ```
   
   Ensure the new container is in _starting_ state (`# docker ps`) and run the HTTP check against the _slow-service_ again:
   
   ```
   # while true; do curl -s --show-error -I http://127.0.0.1:8080 | head -n 1; sleep 1; done
   curl: (7) Failed connect to 127.0.0.1:8080; Connection refused
   HTTP/1.1 200 OK
   curl: (7) Failed connect to 127.0.0.1:8080; Connection refused
   HTTP/1.1 200 OK
   curl: (7) Failed connect to 127.0.0.1:8080; Connection refused
   HTTP/1.1 200 OK
   curl: (7) Failed connect to 127.0.0.1:8080; Connection refused
   HTTP/1.1 200 OK
   curl: (7) Failed connect to 127.0.0.1:8080; Connection refused
   HTTP/1.1 200 OK
   curl: (7) Failed connect to 127.0.0.1:8080; Connection refused
   HTTP/1.1 200 OK
   curl: (7) Failed connect to 127.0.0.1:8080; Connection refused
   HTTP/1.1 200 OK
   curl: (7) Failed connect to 127.0.0.1:8080; Connection refused
   HTTP/1.1 200 OK
   curl: (7) Failed connect to 127.0.0.1:8080; Connection refused
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   HTTP/1.1 200 OK
   ^C
   ```
   
   Finally, ensure the new container is _healthy_ now (`# docker ps`).

**Describe the results you received:**

Obviously, the new container (created due to upscaling) was considered for load balancing immediately after it was created. This behavior causes failures of every 2nd connection to the service on consumer side.

Accordingly, upscaling from 1 to 5 tasks would cause failures in 4 of 5 requests.

**Describe the results you expected:**

When `HEALTHCHECK` is defined in `Dockerfile`, new containers should not participate on load balancing as long as their status is _starting_.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue can be reproduced on every upscaling. Might be related to #25464.

**Comment by aaronlehmann** [comment] 2016-08-29 02:00
cc @dongluochen

**Comment by jhorwit2** [comment] 2016-08-29 13:11
Seems related to https://github.com/docker/swarmkit/issues/1328

**Comment by liweinan0423** [comment] 2016-09-27 17:31
+1. This issue also happens when updating a service with a new image version. I imagine the temporary work around is to set the `--endpoint-mode` to `dnsrr` and use a third-party load-balancer such as HAProxy or Nginx to do the health-check trick.

**Comment by thaJeztah** [comment] 2016-11-01 02:18
Looks like related / duplicate of https://github.com/docker/docker/issues/26067

**Comment by thaJeztah** [comment] 2016-11-01 02:19
Er, I meant https://github.com/docker/docker/issues/24092

**Comment by dimw** [comment] 2016-11-12 23:39
Great, seems to be fixed in 1.13.0-rc1. Will double check with final release once again and close the ticket. Thanks @dongluochen!

**Comment by PanJ** [comment] 2017-01-13 08:28
Tested with 1.13.0-rc6 and it works as expected!

**Comment by cpuguy83** [comment] 2017-01-14 13:51
Great, thanks all!

**Closed by cpuguy83** 2017-01-14 13:51 UTC
Labels: area/swarm, kind/bug, version/1.12

**Comment by krasi-georgiev** [comment] 2017-01-17 01:24
I just downloaded the master for linux

https://master.dockerproject.org/linux/amd64/docker

Docker version 1.14.0-dev, build a7c3389

when scaling containers with status starting are still shown with 
dig tasks.service

**Comment by dongluochen** [comment] 2017-01-17 22:01
@krasi-georgiev I cannot reproduce the issue you reported. Can you show how to reproduce your issue?

```
$docker service scale test2=8
test2 scaled to 8

$ docker service ps test2
ID            NAME     IMAGE                      NODE               DESIRED STATE  CURRENT STATE               ERROR  PORTS
qvcx08gd459a  test2.1  dongluochen/simpleweb:2.0  ip-172-19-147-51   Running        Running about a minute ago
fidf3dfc2wrc  test2.2  dongluochen/simpleweb:2.0  ip-172-19-241-146  Running        Running about a minute ago
lvtximi2juvt  test2.3  dongluochen/simpleweb:2.0  ip-172-19-241-146  Running        Starting 5 seconds ago
ui6qmz6s9lh0  test2.4  dongluochen/simpleweb:2.0  ip-172-19-241-145  Running        Starting 5 seconds ago
ue85v2fka8e9  test2.5  dongluochen/simpleweb:2.0  ip-172-19-147-51   Running        Starting 6 seconds ago
bx0wz4fn4yoc  test2.6  dongluochen/simpleweb:2.0  ip-172-19-241-145  Running        Running 38 seconds ago
r8fqnii28fel  test2.7  dongluochen/simpleweb:2.0  ip-172-19-241-146  Running        Starting 5 seconds ago
yl7vmbjglbdp  test2.8  dongluochen/simpleweb:2.0  ip-172-19-241-145  Running        Starting 5 seconds ago

-- docker exec on a different container in the same network
/ # nslookup tasks.test2
nslookup: can't resolve '(null)': Name does not resolve

Name:      tasks.test2
Address 1: 10.0.0.14 test2.6.bx0wz4fn4yoc77qgs0rgxye18.tnet1
Address 2: 10.0.0.9 test2.2.fidf3dfc2wrcine0b6lqj1pr3.tnet1
Address 3: 10.0.0.11 test2.1.qvcx08gd459axzw9rjtc2swe1.tnet1

$ docker service ps test2
ID            NAME     IMAGE                      NODE               DESIRED STATE  CURRENT STATE                   ERROR  PORTS
qvcx08gd459a  test2.1  dongluochen/simpleweb:2.0  ip-172-19-147-51   Running        Running about a minute ago
fidf3dfc2wrc  test2.2  dongluochen/simpleweb:2.0  ip-172-19-241-146  Running        Running about a minute ago
lvtximi2juvt  test2.3  dongluochen/simpleweb:2.0  ip-172-19-241-146  Running        Running 1 second ago
ui6qmz6s9lh0  test2.4  dongluochen/simpleweb:2.0  ip-172-19-241-145  Running        Running less than a second ago
ue85v2fka8e9  test2.5  dongluochen/simpleweb:2.0  ip-172-19-147-51   Running        Running 2 seconds ago
bx0wz4fn4yoc  test2.6  dongluochen/simpleweb:2.0  ip-172-19-241-145  Running        Running 43 seconds ago
r8fqnii28fel  test2.7  dongluochen/simpleweb:2.0  ip-172-19-241-146  Running        Running less than a second ago
yl7vmbjglbdp  test2.8  dongluochen/simpleweb:2.0  ip-172-19-241-145  Running        Running 1 second ago

/ # nslookup tasks.test2
nslookup: can't resolve '(null)': Name does not resolve

Name:      tasks.test2
Address 1: 10.0.0.12 test2.4.ui6qmz6s9lh0j3jmcijiiueqv.tnet1
Address 2: 10.0.0.9 test2.2.fidf3dfc2wrcine0b6lqj1pr3.tnet1
Address 3: 10.0.0.14 test2.6.bx0wz4fn4yoc77qgs0rgxye18.tnet1
Address 4: 10.0.0.13 test2.5.ue85v2fka8e9sg0q8509brjl9.tnet1
Address 5: 10.0.0.15 test2.7.r8fqnii28felg77o8cqyydavi.tnet1
Address 6: 10.0.0.11 test2.1.qvcx08gd459axzw9rjtc2swe1.tnet1
Address 7: 10.0.0.10 test2.3.lvtximi2juvt4l9r65eohhech.tnet1
Address 8: 10.0.0.16 test2.8.yl7vmbjglbdp7jsqcujicc7yz.tnet1
```

**Comment by krasi-georgiev** [comment] 2017-01-18 01:11
strange in my setup it does it every time

Linux debian8Dev 4.8.0-0.bpo.2-amd64 #1 SMP Debian 4.8.11-1~bpo8+1 (2016-12-14) x86_64 GNU/Linux

debian 8.6

look at the video

https://screencast.com/t/g0QPmB5CT1o

**Comment by thaJeztah** [comment] 2017-01-18 14:19
There _could_ be a difference between `dig` and `nslookup` though; http://unix.stackexchange.com/questions/93808/dig-vs-nslookup

**Comment by krasi-georgiev** [comment] 2017-01-18 14:36
ok I will test it with nslookup , 
dig +short is so convenient as it returns a clean output and no need to parse it.

**Comment by thaJeztah** [comment] 2017-01-18 14:52
There still may be an issue at hand, but it would be interesting to see if it occurs only with `dig` (and not with `nslookup` 👍

**Comment by dongluochen** [comment] 2017-01-18 19:48
I use `dig` and get the same result. Containers in `starting` state are not added to DNS rotation. I use a monitor on the same network as the target service to run `dig`, and scale my service up/down to validate. 

@krasi-georgiev Just want to validate that you run docker **daemon** at 1.14.0-dev, build a7c3389. You can find that with `docker version` and look at `Server`. If you are running 1.14.0-dev, can you send use output from `docker inspect #container-id#`, where `container-id` is a container in `starting` state but shown up in DNS rotation.

**Comment by krasi-georgiev** [comment] 2017-01-18 21:24
@dongluochen  thanks for the smart pointer , the problem was that I was following this tutorial and completely forgot that the docker daemon is now separate to only upgraded the docker client.

https://docs.docker.com/v1.5/contributing/devenvironment/

I will open a pull request to update the docs

**Comment by krasi-georgiev** [comment] 2017-01-18 21:46
just now I realised that I was looking at the wrong docs for the older docker version.
