### ISSUE TITLE
Docker fail to pull existing image with no such Id 

### ISSUE THREAD

**Issue by Vad1mo** [docker/docker#10241] opened 2015-01-21 16:33 UTC
Im using latest docker on our build server.
when running `docker pull java:8u40-jre` I get this error:
```
java:8u40-jre: The image you are pulling has been verified
511136ea3c5a: Extracting [==================================================>] 1.024 kB/1.024 kB
af26f221e0e7: Pulling fs layer 
af26f221e0e7: Download complete 
207e7f49222c: Download complete 
e6d5727a82ee: Download complete 
0ab7ad256ec0: Pulling fs layer 
0ab7ad256ec0: Download complete 
FATA[0051] no such id: 0ab7ad256ec0f9e219e4116e416d5ad90de11c5fd404444474647d61b35f0dfd 
```

The image exist and is download but after downloading there is the pop. It looks like there is not space to store but the server has over 100GB left. 

```
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-202:1-2163327-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 762.2 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 1.13 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.2.0-52-virtual
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 3.844 GiB
Name: abidjan.konik.io
ID: FNUO:7ZDG:M3QG:J32Q:2EGX:HVKT:OING:VRHJ:FZKW:XXUO:VLZF:EQZJ
Username: vad1mo
Registry: [https://index.docker.io/v1/]```

**Comment by thaJeztah** [comment] 2015-01-24 22:58
I don't know if this is the cause of your problem, but the *minimum* requirements for Docker is kernel 3.8 (see [check kernel dependencies](https://docs.docker.com/installation/binaries/#check-kernel-dependencies)). Besides that, Ubuntu 14.04 ships with [kernel version 3.13](https://docs.docker.com/installation/ubuntulinux/#ubuntu-trusty-1404-lts-64-bit); are you using a custom kernel? Because only the kernel provided with your distro is officially supported.

**Comment by jfrazelle** [comment] 2015-02-10 22:58
Can you curl and run https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh
it will cheack your kernel config for all the necessary things. But yes closing as your kernel on ubuntu is not supported

**Closed by jfrazelle** 2015-02-10 22:58 UTC
