### ISSUE TITLE
Logging in with cli options always prompts for email even though a blank email is specified

### ISSUE THREAD

**Issue by stephenbunch** [docker/docker#13727] opened 2015-06-03 22:47 UTC
Hey guys, I'm trying to write a script to login using the command options, except docker always prompts me for an email.

```bash
docker login -u someuser -p somepass -e "" myrepo.com
Email:
```

However, if I've logged in in the past, docker doesn't ask, even if I don't specify the email option.
```bash
docker login -u someuser -p somepass myrepo.com
Login Succeeded
````

## Bug Report

`docker version:`
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651

`docker info:`
Containers: 2
Images: 27
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 31
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 2
Total Memory: 7.324 GiB
Name: k8s-cluster-2-node-2
ID: 5PLF:3QPO:F3SU:LQZ4:5E2Z:KDOC:EAMV:K7IC:VGVP:JZEO:OPGF:JGSD
WARNING: No swap limit support

`uname -a`:
Linux k8s-cluster-2-node-2 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1~bpo70+1 (2015-04-27) x86_64 GNU/Linux

**Other notes:**
This is on Google Cloud Platform.

**Steps to reproduce problem:**
1. Run `docker login` specifying values for `-u`, `-p`, and an empty value for `-e`.

**Results received:**
Was prompted to provide an email.

**Results expected:**
Should not have been prompted for an email.

**Comment by thaJeztah** [comment] 2015-06-08 22:26
Thanks for reporting, I think this is a duplicate of https://github.com/docker/docker/issues/6400

I'm going to close this issue as a duplicate of https://github.com/docker/docker/issues/6400. Please continue the discussion on that issue, but feel free to comment here if you think I closed this by mistake.

**Closed by thaJeztah** 2015-06-08 22:26 UTC

**Comment by meetmatt** [comment] 2016-02-20 10:33
You can simulate empty email entry by using "yes" program like this:

yes | docker login -u username -p password private-registry

Works like a charm for in my deploy script :)
