### ISSUE TITLE
concourse (garden-linux) breaks docker: "oci runtime error: could not synchronize with container process: no such file or directory"

### ISSUE THREAD

**Issue by RoboPhred** [docker/docker#22307] opened 2016-04-25 17:37 UTC
Something goes wrong with docker when a Concourse worker (https://concourse.ci) is ran on the same server.  Existing containers will continue to run just fine, but all new containers will cause the docker client to report "Container command '...' not found or does not exist.." for any given entrypoint, and the docker logs to report "oci runtime error: could not synchronise with container process: no such file or directory".  This will occur even after concourse is fully shut down, and docker will not be usable until the server is restarted.

I am not really sure about all the moving parts involved here.  From what I can tell, concourse is using some other container platform called Garden Linux, which I think is using AUFS judging by the mounts that get created while the worker is running.

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 41
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 135
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-58-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.86 GiB
Name: DEV-01
ID: FJX7:N2J2:ZSM3:BIDB:NN42:7YWA:IWTV:XNQX:YXMM:AB3N:FBOI:MALF
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
I reproduced the issue off of my dev server by using VirtualBox:
- Install Ubuntu 16.04 64bit into a new box
- Install docker following the instructions at https://docs.docker.com/engine/installation/linux/ubuntulinux/
- Test that docker works: "sudo docker run --rm hello-world"
- Get the concourse binaries from https://concourse.ci/downloads.html.  I reproduced the issue with 1.0.0 and 1.1.0
- Run a postgres server for concourse

```
docker run --name concourse_postgres -e POSTGRES_PASSWORD=concourse -p 5432:5432 -d postgres
```
- Run "concourse web" as described in the first part of https://concourse.ci/binaries.html, using postgres on the "./concourse web" step with

```
--postgres-data-source postgres://postgres:concourse@127.0.0.1:5432?sslmode=disable
```
- [Issue Trigger] run "concourse worker" as described in the above site, let it run for 30 seconds or so, then shut it down
- [Issue Effect] run "sudo docker run --rm hello-world", and see "Container command '/hello' not found or does not exist", and check the daemon logs for the oci error.

**Describe the results you received:**
Concourse fails to run any new container after a concourse worker is started, even after it is shut down.

**Describe the results you expected:**
Docker should keep working regardless of concourse/garden-linux

**Additional information you deem important (e.g. issue happens only occasionally):**

I am not sure how well supported this use case is, given that garden-linux is also some sort of container tool.  In addition, the concourse worker might be running its own copy of docker inside that container (or its just using docker images through garden, I can't tell).  To top off this madness, the garden-linux repo indicates that running it outside of BOSH (which I have yet to look into) is unsupported.

I'm not sure how much support you are willing to give me on this, and wouldn't put this as a particularly high priority, but any help in tracing down the cause of this would be much appreciated.

Issue is also posted to the concourse/bin github at https://github.com/concourse/bin/issues/16

**Comment by bassmanitram** [comment] 2016-04-27 12:44
Hi - I'm getting the exact same symptoms but do not have concourse-ci running - can you tell me how you figured out that concourse was your problem?

**Comment by RoboPhred** [comment] 2016-04-27 16:34
Concourse may not be to blame for this, but it triggers the condition that causes the failure.  Docker will always stop working once a concourse worker has been launched.  I suspect the issue lies with garden-linux or https://github.com/cloudfoundry-incubator/garden in general

**Comment by bassmanitram** [comment] 2016-04-28 14:40
I actually found the cause in my case - apparmor was badly configured. Starting the Docker daemon from the command line in debug mode exposed the error and I was then able to fix apparmor.

**Comment by thaJeztah** [comment] 2016-11-30 15:42
looks like it's resolved so closing

**Closed by thaJeztah** 2016-11-30 15:42 UTC
Labels: kind/question, version/1.11
