### ISSUE TITLE
regression terminal drawing on 1.7.1

### ISSUE THREAD

**Issue by mcieslik-mctp** [docker/docker#15373] opened 2015-08-06 18:14 UTC
Description of problem:

Garbled emacs displayed when running inside a docker container (using -t -i) with multiple panes (windows). The corruption is fixed after resizing the terminal (or pressing ctrl+l). The bug was introduced with 1.7.0 and persists into 1.7.1. 

I should add that this makes emacs and possibly other console based applications unusable.

Broken (checked 1.7.0 and 1.7.1)
![broken](https://cloud.githubusercontent.com/assets/5831815/9119366/4b577f76-3c44-11e5-91dd-c84678746fdb.png)

Good (checked 1.3.2 and 1.6.2)
![good](https://cloud.githubusercontent.com/assets/5831815/9119328/2091e2b8-3c44-11e5-8542-55bacadf53e4.png)

`docker version`:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

`docker info`:
Containers: 1
Images: 247
Storage Driver: devicemapper
 Pool Name: docker-254:3-12587682-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 66.91 GB
 Data Space Total: 107.4 GB
 Data Space Available: 40.46 GB
 Metadata Space Used: 52.62 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.095 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.102 (2015-07-07)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.3-1-ARCH
Operating System: Arch Linux
CPUs: 8
Total Memory: 62.86 GiB
ID: XEB2:FX7X:USNE:7ZIE:X44P:NL2F:XS7B:MWY2:MOIF:VJ4C:2A6R:GXZL
Registry: https://index.docker.io/v1/

`uname -a`:
Linux  4.1.3-1-ARCH #1 SMP PREEMPT Wed Jul 22 20:37:12 CEST 2015 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical

How reproducible:
100%

Steps to Reproduce:
1. have ubuntu 04.14 container with emacs installed (emacs version does not matter)
2. run bash inside container with "-t -i"
3. start emacs
4. open new vertical pane: C-x 3
corruption happens
5. press Ctrl+l
corruption resolves

Actual Results:
Corruption

Expected Results:
No Corruption

Additional info:

**Comment by MHBauer** [comment] 2015-08-26 04:41
As an avid emacs user, I can confirm it not working in 1.7, but it looks like it's back to working in 1.8
<img width="1148" alt="screen shot 2015-08-25 at 21 40 12" src="https://cloud.githubusercontent.com/assets/13337345/9485675/e8de7d08-4b71-11e5-92c3-6f92600c8c13.png">

```
λ docker version
Client:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment] 2015-08-30 18:45
@mcieslik-mctp can you confirm this is fixed in docker 1.8.1?

**Comment by bk201doesntexist** [comment] 2015-09-05 11:14
[beekay201@rogue ~]$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Sat Aug 15 17:29:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Sat Aug 15 17:29:10 UTC 2015
 OS/Arch:      linux/amd64

![screenshot_2015-09-05_12-13-38](https://cloud.githubusercontent.com/assets/793358/9698985/99352c9e-53c7-11e5-999a-79f9c18cdbd2.png)

As you can see, Weechat is still affected by this terminal drawing issue.

**Comment by thaJeztah** [comment] 2015-09-05 12:11
@jfrazelle you run a lot of your stuff in containers; did you encounter something similar - any info that's needed to assist locating / resolving this?

**Comment by zferentz** [comment] 2015-09-21 19:56
I've just upgraded to 1.7.1  (using debian:7.8 and  debian:7.9) , and even with a simple command line "dialog --msgbox test 0 0" i can see that the cursor is mislocated . other "dialog" commands (mixed-form) are a complete mess.

**Comment by emma-borhanian** [comment] 2015-11-29 01:09
I am experiencing this issue as well with weechat:
$ sudo docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64

My setup is here: https://github.com/emma-borhanian/gcloud_weechat

**Comment by thaJeztah** [comment] 2015-11-29 11:21
Is someone able to test if this is still an issue on 1.9.1?

**Comment by emma-borhanian** [comment] 2015-11-29 18:49
Actually, I don't seem to have any problems on 1.9.1, I guess I'll just have to wait until that's what's on google cloud.

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

**Comment by MHBauer** [comment] 2015-11-30 16:08
I don't see any problems in `emacs` or with the `dialog` command mentioned [here](https://github.com/docker/docker/issues/15373#issuecomment-142092255).

**Comment by mcieslik-mctp** [comment] 2015-11-30 19:57
I tested 1.9.1, but emacs is still garbled (start emacs C-x 3 -> garbled)

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Sun Nov 22 00:15:15 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Sun Nov 22 00:15:15 UTC 2015
 OS/Arch:      linux/amd64

![image](https://cloud.githubusercontent.com/assets/5831815/11482717/5e02b9f4-9772-11e5-9970-54ff4fa64d6d.png)

**Comment by thaJeztah** [comment] 2015-11-30 20:50
I see "Git commit: a34a1d5-dirty", did you build docker yourself? Were changes made (just to check)

**Comment by mcieslik-mctp** [comment] 2015-11-30 21:03
I am using the official "Arch linux" build:

https://www.archlinux.org/packages/community/x86_64/docker/

They seem to apply two tiny patches:

https://projects.archlinux.org/svntogit/community.git/tree/trunk?h=packages/docker

**Comment by thaJeztah** [comment] 2015-11-30 21:23
> They seem to apply two tiny patches:

hm, however one of those patches seems to indicate they build docker 1.9 with golang 1.5, not 1.4, at least if I go by the name of that patch: https://projects.archlinux.org/svntogit/community.git/tree/trunk/01-golang15.patch?h=packages/docker

**Comment by thaJeztah** [comment] 2015-11-30 21:24
Oh, and the output of your docker info confirms that; `Go version: go1.5.1`

**Comment by mcieslik-mctp** [comment] 2016-01-27 17:14
The status of this bug mentions "more-info-needed" what other info would you need, the bug is a regression, 100% reproducible (on different host Linuxes), and present in all docker versions after 1.6.2. If providing a useful terminal is not important for Docker please close, I cannot keep using 1.6.2 forever, and need to find an alternative to my workflow.

**Comment by MHBauer** [comment] 2016-01-27 18:11
I'll give it another look. Emacs is important to me.

**Comment by MHBauer** [comment] 2016-01-27 20:13
I see it now. I can confirm it with linux to linux. OSX to linux everything looks okay. So it would seem to be a linux client thing at first look. I definitely missed the importance of the linux client the first time.

**Comment by thaJeztah** [comment] 2016-01-27 23:12
Thanks @MHBauer, do you think you're able to look into this issue?

**Comment by MHBauer** [comment] 2016-01-27 23:55
Not sure I have the confidence or the capability to debug the way the cli handles terms. I'm not even sure who I would ask for help, or where I would start looking in the code. I am certainly willing to give it a try, but it might end up taking a while.

**Comment by thaJeztah** [comment] 2016-01-28 03:25
np, let us know if you need help

**Comment by MHBauer** [comment] 2016-01-28 18:25
I might have something. I *really* **really** _**REALLY**_ do not want to be the one responsible for breaking everyone's terminals, so I am going to keep testing for a bit and then file a PR.

**Comment by mcieslik-mctp** [comment] 2016-01-28 18:39
:) Thanks @MHBauer - I will be happy to help with the testing.

**Comment by wirawan0** [comment] 2016-02-16 15:47
FYI. I am also experiencing this problem with Docker 1.9.1 and Emacs:

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64

Host OS: Debian 8, running xfce desktop. Docker binary package was obtained from official Docker repo. I tested this mess on both gnome-terminal and xterm, so it's not the terminal GUI that's the problem.

Today I also upgraded Docker software to version 1.10 and it's still showing messed up 2-column display; please see attached pic.

![afbee-emacs02-bad docker1 10](https://cloud.githubusercontent.com/assets/524650/13081346/8eec8bfc-d49a-11e5-8fd5-29acca770be4.png)

Version info of Docker 1.10:

$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:09:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:09:42 2016
 OS/Arch:      linux/amd64

.

**Comment by MHBauer** [comment] 2016-02-23 23:36
The test from #20043 is a nice oneliner to see if this is still a problem.

**Closed** 2016-03-01 16:37 UTC
Labels: kind/bug

**Comment by mcieslik-mctp** [comment] 2016-03-07 16:59
I can confirm that the terminal drawing issues seem resolved. Thanks!

**Comment by thaJeztah** [comment] 2016-03-07 17:05
Nice! Thanks for testing @mcieslik-mctp :+1:

**Comment by MHBauer** [comment] 2016-03-07 17:31
w00h00, it got merged. Thanks for the report @mcieslik-mctp !

**Comment by thaJeztah** [comment] 2016-03-07 17:42
Yes, it will be part of the 1.11 release (or nightly / experimental builds)
