### ISSUE TITLE
Build arguments invalidate cache on declaration, not on usage.

### ISSUE THREAD

**Issue by izaakschroeder** [docker/docker#20136] opened 2016-02-09 08:54 UTC
The [documentation](https://docs.docker.com/engine/reference/builder/#impact-on-build-caching) regarding `--build-arg` is a little misleading. It states that a "cache miss occurs upon [the variable's] first usage" – this appears to be a lie. If you look at the [source code](https://github.com/docker/docker/blob/master/builder/dockerfile/dispatchers.go#L343) the cache gets wiped for any build argument that changes. For example consider the simple docker file:

```Dockerfile
ARG FOO
RUN mkdir /test
```

This results in the following command being executed with `--build-arg FOO=xxx`:

```sh
sh -c "FOO=xxx mkdir /test"
```

Even though `FOO` is never used in that command. So every time `FOO` changes the cache gets blown. Every build argument wipes the cache from the point the `ARG` is defined, _NOT_ when it's first used. I feel like if the command doesn't use the variable it shouldn't be stuck in the environment, or the documentation should be change to reflect this behaviour. :smile:

**Comment by cpuguy83** [comment] 2016-02-09 20:14
This is not accurate.

1. The docs talk about the declaration of `ARG` in the Dockerfile, as each `--build-arg` must be coupled with an `ARG` statement.
2. In your example, changing the `--build-arg` does not affect the build cache since the build-arg is never taken into account since there is no `ARG` statement, notice that when you build it, you will always get `Usage cache`, and then at the end the build will be marked as a failure.
3. In your example, you are using a `RUN` statement, which is a shell command. Docker does not inspect the values of shell commands to determine what it should do with caching, just the text itself.

Perhaps the documentation is using a bad example since the `RUN` is specifically calling the arg even though the arg is injected even if it wasn't being called.

**Comment by duglin** [comment] 2016-02-10 04:24
@izaakschroeder the "usage" in this case is the RUN command not the ARG command.
See this output when I build the 2nd time changing FOO:
```
$ docker build --build-arg FOO=goo .
Sending build context to Docker daemon 40.09 MB
Step 1 : FROM ubuntu
 ---> 3876b81b5a81
Step 2 : ARG FOO
 ---> Using cache
 ---> 83ce3c01f387
Step 3 : RUN echo hi
 ---> Running in 0140fef42a3a
hi
 ---> a7c9ed29189a
Removing intermediate container 0140fef42a3a
Successfully built a7c9ed29189a
```
Notice for `ARG FOO` is says it used the cache, but on `RUN` it didn't.

As you noted all build-args/ARGs are passed to the RUN command as environment variables. Since the value of the ARG has changed, and as @cpuguy83 guy said, we don't know how the cmd will use the env vars (or if they will use them at all) we have to play it safe and assume they will - which means this usage (first usage) of FOO blows away the cache.

If you think the docs need to be clearer we can add more text but some suggestion as to what to add would be helpful.

**Comment by thaJeztah** [comment] 2016-02-10 10:14
looks like this behaves as expected indeed, but I'm open to suggestions if the docs need to be clearer on this. :+1:

**Comment by proppy** [comment] 2016-02-23 02:17
I've experience something similar, if I use the following `Dockerfile`:
```
FROM ubuntu
ARG CONT_IMG_VER
RUN echo before first usage
RUN echo $CONT_IMG_VER
RUN echo after first usage
```
And build two times with 2 different values for `--build-arg`, I get:
```
docker-build-test 🍙  docker build --build-arg CONT_IMG_VER=somevalue .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu
 ---> a853da072055
Step 2 : ARG CONT_IMG_VER
 ---> Using cache
 ---> 046604948188
Step 3 : RUN echo before
 ---> Running in 0bfe49c78e02
before
 ---> 98ba74681899
Removing intermediate container 0bfe49c78e02
Step 4 : RUN echo $CONT_IMG_VER
 ---> Running in 903e66528024
somevalue
 ---> 95a0e311b443
Removing intermediate container 903e66528024
Step 5 : RUN echo after
 ---> Running in bebd5450afc3
after
 ---> 4ebd1e0c3e7a
Removing intermediate container bebd5450afc3
Successfully built 4ebd1e0c3e7a
```
```
docker-build-test 🍊  docker build --build-arg CONT_IMG_VER=someothervalue .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu
 ---> a853da072055
Step 2 : ARG CONT_IMG_VER
 ---> Using cache
 ---> 046604948188
Step 3 : RUN echo before
 ---> Running in 53517a1e9a83
before
 ---> 9cb22be4c75e
Removing intermediate container 53517a1e9a83
Step 4 : RUN echo $CONT_IMG_VER
 ---> Running in 1fc686f1282d
someothervalue
 ---> 6523a6f7c758
Removing intermediate container 1fc686f1282d
Step 5 : RUN echo after
 ---> Running in 9dc888b16a6b
after
 ---> 642f74255757
Removing intermediate container 9dc888b16a6b
Successfully built 642f74255757
docker-build-test 🍙  
```

Notice that on the second build `RUN echo before` didn't get cached even though it's *before* the first usage of `CONT_IMG_VER`.

**Comment by duglin** [comment] 2016-02-23 12:55
@proppy that's expected because during a RUN we don't know which env vars will be used by the command being run - so since CONT_IMG_VER changed we have to invalidate the cache.

**Comment by duglin** [comment] 2016-02-23 12:56
I'm going to close this because it appears to be working as designed. If I'm mistaken we can reopen it.

**Closed by duglin** 2016-02-23 12:56 UTC

**Comment by thaJeztah** [comment] 2016-02-23 12:58
> Notice that on the second build RUN echo before didn't get cached even though it's before the first usage of CONT_IMG_VER.

@proppy this is expected (but I haven't checked the docs yet; they may be wrong here)

The build-args are prepended to each `RUN` statement, so changing the value of a build-time arg will invalidate subsequent `RUN` statements. Point is that the build-cache does not evaluate the actual instructions (take for example `RUN some-script.sh` - the build cache would not know if `some-script.sh` actually makes use of a build-time variable.

You can see this in the following output;

```bash
$ docker build -t args-example --build-arg CONT_IMG_VER=1 .
Sending build context to Docker daemon 2.048 kB
# ...
```

And check the history;

```bash
$ docker history --no-trunc args-example

IMAGE                                                                     CREATED             CREATED BY                                            SIZE                COMMENT
sha256:f1123fd307c23399d74671fb2d143d6b12cfff4dd9fff95e9f0160009cea52a3   54 seconds ago      |1 CONT_IMG_VER=1 /bin/sh -c echo after first usage   0 B
sha256:1e5ca59ebc9387cf44961c304e92305cd615c3b6243a1beff607422430146d3d   55 seconds ago      |1 CONT_IMG_VER=1 /bin/sh -c echo $CONT_IMG_VER       0 B
sha256:53dab19271921f2681b3e401a8949fd20e3d60eb7df059b3246d84204c6e2cce   56 seconds ago      |1 CONT_IMG_VER=1 /bin/sh -c echo before first usage  0 B
sha256:a292c11fad055bb1a9c51d64f91277164fb5ecee8ad5aa1e6cbdf35190ea9ba6   57 seconds ago      /bin/sh -c #(nop) ARG CONT_IMG_VER                    0 B
```

Another build + history:

```bash
$ docker build -t args-example --build-arg CONT_IMG_VER=2 .
Sending build context to Docker daemon 2.048 kB
# ...
```

```bash
$ docker history --no-trunc args-example

IMAGE                                                                     CREATED             CREATED BY                                            SIZE                COMMENT
sha256:a1a16f43e3fca965fbdddf100f5c425f560daeb47b649d1b2011c633e8bd4828   30 seconds ago      |1 CONT_IMG_VER=2 /bin/sh -c echo after first usage   0 B
sha256:c73f3a9202d1d1566c1147816feb2077adbe9029dc671c3ea9b99f11569e7ba7   31 seconds ago      |1 CONT_IMG_VER=2 /bin/sh -c echo $CONT_IMG_VER       0 B
sha256:cc1c54bcb5cba1b90656d350800ddb09a812d17067ec9f11b18cad4014576323   32 seconds ago      |1 CONT_IMG_VER=2 /bin/sh -c echo before first usage  0 B
sha256:a292c11fad055bb1a9c51d64f91277164fb5ecee8ad5aa1e6cbdf35190ea9ba6   3 minutes ago       /bin/sh -c #(nop) ARG CONT_IMG_VER                    0 B
```

You can see in the history that the build-arg is prepended, and will invalidate the cache if the value is different.

**Comment by proppy** [comment] 2016-02-23 18:32
Thanks for opening #20612, I feel that this need to be explicitly called out in the documentation.
