### ISSUE TITLE
Daemon fails to start

### ISSUE THREAD

**Issue by gvangool** [docker/docker#15626] opened 2015-08-17 11:25 UTC
Docker daemon fails to start after installation from new Yum repositories.

`docker version`:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:19:43 UTC 2015
 OS/Arch:      linux/amd64
Get http:///var/run/docker.sock/v1.20/version: read unix /var/run/docker.sock: connection reset by peer.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

`docker info`:
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

`uname -a`:
Linux app8.goose.weepee.net 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment: virtual machine on KVM on CentOS 6 (QEMU PC emulator version 0.12.1 (qemu-kvm-0.12.1.2), Copyright (c) 2003-2008 Fabrice Bellard)

So I'm starting from bare CentOS 7. And installed Docker from the new yum repo's. This should install docker v1.8.1

```bash
cat > /etc/yum.repos.d/docker.repo << EOF
[docker-repo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF
yum install -y docker-engine
```

The daemon fails to start.

```
$  systemctl start docker
Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
$  docker daemon --debug
DEBU[0000] Registering HEAD, /containers/{name:.*}/archive
DEBU[0000] Registering GET, /info
DEBU[0000] Registering GET, /containers/{name:.*}/top
DEBU[0000] Registering GET, /containers/{name:.*}/logs
DEBU[0000] Registering GET, /containers/{name:.*}/stats
DEBU[0000] Registering GET, /exec/{id:.*}/json
DEBU[0000] Registering GET, /_ping
DEBU[0000] Registering GET, /images/json
DEBU[0000] Registering GET, /images/{name:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws
DEBU[0000] Registering GET, /version
DEBU[0000] Registering GET, /containers/ps
DEBU[0000] Registering GET, /containers/{name:.*}/changes
DEBU[0000] Registering GET, /events
DEBU[0000] Registering GET, /images/search
DEBU[0000] Registering GET, /images/get
DEBU[0000] Registering GET, /images/{name:.*}/get
DEBU[0000] Registering GET, /images/{name:.*}/history
DEBU[0000] Registering GET, /containers/json
DEBU[0000] Registering GET, /containers/{name:.*}/export
DEBU[0000] Registering GET, /containers/{name:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/archive
DEBU[0000] Registering POST, /build
DEBU[0000] Registering POST, /containers/{name:.*}/unpause
DEBU[0000] Registering POST, /containers/{name:.*}/restart
DEBU[0000] Registering POST, /containers/{name:.*}/wait
DEBU[0000] Registering POST, /containers/{name:.*}/attach
DEBU[0000] Registering POST, /containers/{name:.*}/copy
DEBU[0000] Registering POST, /containers/{name:.*}/exec
DEBU[0000] Registering POST, /commit
DEBU[0000] Registering POST, /images/{name:.*}/tag
DEBU[0000] Registering POST, /containers/create
DEBU[0000] Registering POST, /containers/{name:.*}/kill
DEBU[0000] Registering POST, /containers/{name:.*}/pause
DEBU[0000] Registering POST, /containers/{name:.*}/stop
DEBU[0000] Registering POST, /containers/{name:.*}/resize
DEBU[0000] Registering POST, /auth
DEBU[0000] Registering POST, /exec/{name:.*}/start
DEBU[0000] Registering POST, /exec/{name:.*}/resize
DEBU[0000] Registering POST, /images/create
DEBU[0000] Registering POST, /images/load
DEBU[0000] Registering POST, /images/{name:.*}/push
DEBU[0000] Registering POST, /containers/{name:.*}/start
DEBU[0000] Registering POST, /containers/{name:.*}/rename
DEBU[0000] Registering PUT, /containers/{name:.*}/archive
DEBU[0000] Registering DELETE, /containers/{name:.*}
DEBU[0000] Registering DELETE, /images/{name:.*}
DEBU[0000] Registering OPTIONS,
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x525b17]

goroutine 1 [running]:
github.com/docker/docker/daemon.getDefaultRouteMtu(0xc208106190, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:983 +0xa7
github.com/docker/docker/daemon.setDefaultMtu(0xc208045600)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:968 +0x41
github.com/docker/docker/daemon.NewDaemon(0xc208045600, 0xc20803a688, 0x0, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:555 +0x7e
main.(*DaemonCli).CmdDaemon(0xc20809b9c0, 0xc20800a020, 0x1, 0x1, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/docker/daemon.go:256 +0xed7
reflect.callMethod(0xc20814c0f0, 0xc208111ce0)
        /usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0x1, 0x1, 0x1, 0xc20814c0f0, 0x0, 0x0, 0xc20814c0f0, 0x0, 0x450faf, ...)
        /usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc20814c030, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/cli/cli.go:89 +0x38e
main.main()
        /root/rpmbuild/BUILD/docker-engine/docker/docker.go:69 +0x428

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [runnable]:
main.func·007()
        /root/rpmbuild/BUILD/docker-engine/docker/daemon.go:241
created by main.(*DaemonCli).CmdDaemon
        /root/rpmbuild/BUILD/docker-engine/docker/daemon.go:248 +0xd51
```

**Comment by gvangool** [comment] 2015-08-17 11:45
Updated description withe new info

**Comment by mountkin** [comment] 2015-08-17 12:06
@gvangool  Can you please provide the outputs of `ip route` and `ip link` as well?

**Comment by GJean** [comment] 2015-08-17 12:25
I have the same problem : systemctl -l status docker.service
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled)
   Active: failed (Result: timeout) since lun. 2015-08-17 14:18:45 CEST; 1min 23s ago
     Docs: https://docs.docker.com
 Main PID: 11080

août 17 14:17:15 localhost.localdomain docker[11080]: time="2015-08-17T14:17:15.789390835+02:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
août 17 14:17:15 localhost.localdomain docker[11080]: time="2015-08-17T14:17:15.796342153+02:00" level=info msg="Option DefaultDriver: bridge"
août 17 14:17:15 localhost.localdomain docker[11080]: time="2015-08-17T14:17:15.796375172+02:00" level=info msg="Option DefaultNetwork: bridge"
août 17 14:17:15 localhost.localdomain docker[11080]: time="2015-08-17T14:17:15.799212475+02:00" level=warning msg="Running modprobe bridge nf_nat br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.\n, error: exit status 1"
août 17 14:18:45 localhost.localdomain systemd[1]: docker.service operation timed out. Terminating.
août 17 14:18:45 localhost.localdomain systemd[1]: Failed to start Docker Application Container Engine.
août 17 14:18:45 localhost.localdomain systemd[1]: Unit docker.service entered failed state.

**Comment by gvangool** [comment] 2015-08-17 12:28
@mountkin sure

```
$  ip route
default
        nexthop via 37.143.3.1  dev eth0 weight 1
        nexthop via 37.143.3.2  dev eth0 weight 1
        nexthop via 37.143.3.3  dev eth0 weight 1
        nexthop via 37.143.3.4  dev eth0 weight 1
unreachable 14.63.224.207
unreachable 27.75.96.19
37.143.3.0/24 dev eth0  proto kernel  scope link  src 37.143.3.108
unreachable 43.229.53.82
unreachable 45.112.47.110
unreachable 45.114.11.17
unreachable 45.114.11.21
unreachable 58.218.211.166
unreachable 80.120.249.235
unreachable 91.241.131.6
unreachable 91.241.152.175
unreachable 115.211.142.95
unreachable 123.151.22.194
unreachable 138.185.48.75
169.254.0.0/16 dev eth0  scope link  metric 1002
unreachable 178.253.205.28
unreachable 182.100.67.4
unreachable 182.100.67.59
unreachable 182.100.67.113
unreachable 183.155.189.27
unreachable 193.104.41.89
unreachable 193.201.224.143
unreachable 218.65.30.61
unreachable 218.65.30.92
unreachable 218.87.111.107
unreachable 218.87.111.110
unreachable 222.186.21.227
unreachable 222.186.21.251
unreachable 222.186.56.150
unreachable 222.186.56.168
unreachable 222.186.56.175
$  ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether aa:00:00:f2:54:9b brd ff:ff:ff:ff:ff:ff
```

**Comment by mountkin** [comment] 2015-08-17 12:43
@gvangool I think it's the unreachable routes that caused the panic. Could you delete the unreachable routes and try it again?

**Comment by gvangool** [comment] 2015-08-17 12:59
@mountkin error is the same

```
$ for i in $(ip ro li | grep unreachable | cut -f 2 -d " ") ; do ip ro del $i ; done
$  ip ro li
default
        nexthop via 37.143.3.1  dev eth0 weight 1
        nexthop via 37.143.3.2  dev eth0 weight 1
        nexthop via 37.143.3.3  dev eth0 weight 1
        nexthop via 37.143.3.4  dev eth0 weight 1
37.143.3.0/24 dev eth0  proto kernel  scope link  src 37.143.3.108
169.254.0.0/16 dev eth0  scope link  metric 1002
$  docker daemon --debug
DEBU[0000] Registering POST, /containers/{name:.*}/kill
DEBU[0000] Registering POST, /containers/{name:.*}/start
DEBU[0000] Registering POST, /containers/{name:.*}/stop
DEBU[0000] Registering POST, /containers/{name:.*}/resize
DEBU[0000] Registering POST, /containers/create
DEBU[0000] Registering POST, /build
DEBU[0000] Registering POST, /containers/{name:.*}/wait
DEBU[0000] Registering POST, /containers/{name:.*}/attach
DEBU[0000] Registering POST, /containers/{name:.*}/copy
DEBU[0000] Registering POST, /containers/{name:.*}/exec
DEBU[0000] Registering POST, /exec/{name:.*}/start
DEBU[0000] Registering POST, /auth
DEBU[0000] Registering POST, /images/create
DEBU[0000] Registering POST, /images/load
DEBU[0000] Registering POST, /images/{name:.*}/push
DEBU[0000] Registering POST, /images/{name:.*}/tag
DEBU[0000] Registering POST, /containers/{name:.*}/pause
DEBU[0000] Registering POST, /containers/{name:.*}/rename
DEBU[0000] Registering POST, /commit
DEBU[0000] Registering POST, /containers/{name:.*}/restart
DEBU[0000] Registering POST, /exec/{name:.*}/resize
DEBU[0000] Registering POST, /containers/{name:.*}/unpause
DEBU[0000] Registering PUT, /containers/{name:.*}/archive
DEBU[0000] Registering DELETE, /containers/{name:.*}
DEBU[0000] Registering DELETE, /images/{name:.*}
DEBU[0000] Registering OPTIONS,
DEBU[0000] Registering HEAD, /containers/{name:.*}/archive
DEBU[0000] Registering GET, /containers/{name:.*}/stats
DEBU[0000] Registering GET, /info
DEBU[0000] Registering GET, /version
DEBU[0000] Registering GET, /containers/ps
DEBU[0000] Registering GET, /containers/{name:.*}/top
DEBU[0000] Registering GET, /images/{name:.*}/get
DEBU[0000] Registering GET, /images/{name:.*}/history
DEBU[0000] Registering GET, /images/{name:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/archive
DEBU[0000] Registering GET, /_ping
DEBU[0000] Registering GET, /events
DEBU[0000] Registering GET, /images/json
DEBU[0000] Registering GET, /images/get
DEBU[0000] Registering GET, /containers/{name:.*}/changes
DEBU[0000] Registering GET, /containers/{name:.*}/logs
DEBU[0000] Registering GET, /exec/{id:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws
DEBU[0000] Registering GET, /images/search
DEBU[0000] Registering GET, /containers/json
DEBU[0000] Registering GET, /containers/{name:.*}/export
DEBU[0000] Registering GET, /containers/{name:.*}/json
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x525b17]

goroutine 1 [running]:
github.com/docker/docker/daemon.getDefaultRouteMtu(0x7f864b0a18a0, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:983 +0xa7
github.com/docker/docker/daemon.setDefaultMtu(0xc208045600)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:968 +0x41
github.com/docker/docker/daemon.NewDaemon(0xc208045600, 0xc20803a638, 0x0, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/daemon/daemon.go:555 +0x7e
main.(*DaemonCli).CmdDaemon(0xc208109470, 0xc20800a020, 0x1, 0x1, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/docker/daemon.go:256 +0xed7
reflect.callMethod(0xc2081540f0, 0xc208119ce0)
        /usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0x1, 0x1, 0x1, 0xc2081540f0, 0x0, 0x0, 0xc2081540f0, 0x0, 0x450faf, ...)
        /usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc208154030, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/cli/cli.go:89 +0x38e
main.main()
        /root/rpmbuild/BUILD/docker-engine/docker/docker.go:69 +0x428

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 9 [runnable]:
text/template/parse.lexText(0xc20808ee80, 0x11e68b0)
        /usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20808ee80)
        /usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /usr/local/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 10 [runnable]:
main.func·007()
        /root/rpmbuild/BUILD/docker-engine/docker/daemon.go:241
created by main.(*DaemonCli).CmdDaemon
        /root/rpmbuild/BUILD/docker-engine/docker/daemon.go:248 +0xd51
```

**Comment by gvangool** [comment] 2015-08-17 13:02
Your suggestion gave me an idea, if I remove the nexthop default routes. The daemon is able to start.

```
$ ip ro del default
$ ip ro add default via 37.143.3.2
$ docker daemon
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] [graphdriver] using prior storage driver "devicemapper"
INFO[0000] Option DefaultDriver: bridge
INFO[0000] Option DefaultNetwork: bridge
WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.
, error: exit status 1
INFO[0000] Firewalld running: false
INFO[0000] Loading containers: start.

INFO[0000] Loading containers: done.
INFO[0000] Daemon has completed initialization
INFO[0000] Docker daemon                                 commit=d12ea79 execdriver=native-0.2 graphdriver=devicemapper version=1.8.1
```

**Comment by GJean** [comment] 2015-08-17 13:07
I try to Delete default route and add default route and the daemon start too.

**Comment by gvangool** [comment] 2015-08-17 13:17
Manually specifying the MTU works as well: `docker daemon --mtu=1500`

**Comment by mountkin** [comment] 2015-08-18 06:38
@gvangool @GJean As #15632 is merged, could you test again with the latest binary built from master? https://master.dockerproject.org/linux/amd64/docker

The root cause of this problem is that the netlink package doesn't handle multipath default route attributes properly (https://github.com/opencontainers/runc/blob/master/libcontainer/netlink/netlink_linux.go#L1000). If the default route is a multipath route, the `Iface` field of the `netlink.Route` struct is not assigned so it's a nil pointer, which caused the panic.
I think to thoroughly fix the problem we have to select the smallest mtu from the interfaces of the multipath default route. But with the current data structure(https://github.com/opencontainers/runc/blob/master/libcontainer/netlink/netlink.go#L20) it's inconvenient to represent the multiple interfaces of a single route.  WDYT? @mavenugo @mrjana

**Comment by GJean** [comment] 2015-08-18 09:57
I put the new binary : when I use docker daemon command it's work, but when I try to use service docker start command or /etc/init.d/docker start command. And this two commands don't work.

**Comment by gvangool** [comment] 2015-08-18 11:29
@mountkin that fixed the startup issue indeed. If you have binaries to test with a new netlink package, let me know

**Comment by calavera** [comment] 2015-08-25 08:55
The fix for this going to be released as part of 1.8.2.

The PR to track changes is #15809

Closing, thank you!

**Closed by calavera** 2015-08-25 08:55 UTC
Labels: group/networking

**Comment by CaryGao** [comment] 2015-10-06 07:43
@calavera 1.8.2 still have the issue

[root@centos71 ~]# docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:08:45 UTC 2015
 OS/Arch:      linux/amd64

[root@centos71 ~]# uname -a
Linux centos71 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x
86_64 x86_64 GNU/Linux

[root@centos71 ~]# systemctl status docker.service -l
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled)
   Active: failed (Result: timeout) since Tue 2015-10-06 15:30:33 HKT; 4min 5s a
go
     Docs: https://docs.docker.com
 Main PID: 464

Oct 06 15:29:03 centos71 docker[464]: time="2015-10-06T15:29:03.631564032+08:00"
 level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
Oct 06 15:29:03 centos71 docker[464]: time="2015-10-06T15:29:03.632421486+08:00"
 level=info msg="Option DefaultDriver: bridge"
Oct 06 15:29:03 centos71 docker[464]: time="2015-10-06T15:29:03.632447130+08:00"
 level=info msg="Option DefaultNetwork: bridge"
Oct 06 15:29:03 centos71 docker[464]: time="2015-10-06T15:29:03.635649908+08:00"
 level=warning msg="Running modprobe bridge nf_nat br_netfilter failed with mess
age: modprobe: WARNING: Module br_netfilter not found.\n, error: exit status 1"
Oct 06 15:30:33 centos71 systemd[1]: docker.service operation timed out. Termina
ting.
Oct 06 15:30:33 centos71 systemd[1]: Failed to start Docker Application Containe
r Engine.
Oct 06 15:30:33 centos71 systemd[1]: Unit docker.service entered failed state.
Oct 06 15:30:42 centos71 systemd[1]: Stopped Docker Application Container Engine
.

**Comment by alexsimo** [comment] 2015-10-07 08:40
@CaryGao Any solution to your issue? Have same problem..

**Comment by CaryGao** [comment] 2015-10-07 09:52
yes
```
$ ip ro del default
$ ip ro add default via 192.168.25.15(your ip)
$ docker daemon
```

**Comment by CaryGao** [comment] 2015-10-13 07:53
@alexsimo Hi, finally I have found the solution，see [GitHub](https://github.com/docker/docker/issues/15498）  `yum install docker-io-selinux` would fix the problem if you have selinux enabled

**Comment by thaJeztah** [comment] 2015-10-13 18:40
@CaryGao good to hear you found the solution; that's a known issue indeed, and will be fixed in the upcoming 1.9 release, which will bundle our own selinux policy; see https://github.com/docker/docker/pull/15832 and https://github.com/docker/docker/pull/16550

**Comment by JustinLivi** [comment] 2015-10-17 18:33
Hi,

I'm running into this issue running RHEL 3.10.0-229.14.1.el7.x86_64

When I disable selinux it works fine, but I'd like to use the docker-selinux temporary workaround to avoid having to disable selinux entirely until the release of Docker 1.9 however, I cannot seem to find either the `docker-io-selinux` nor the `docker-selinux` packages referenced.

`yum search all docker` only reveals `docker-engine.x86_64 : The open-source application container engine`

Can anyone point me in the direction of how to add this package? Many thanks.

**Comment by thaJeztah** [comment] 2015-10-17 19:04
Don't have access to RHEL, but I can see it in the fedora packages; https://apps.fedoraproject.org/packages/docker-selinux and CentOS; http://fr2.rpmfind.net/linux/rpm2html/search.php?query=docker-selinux, but I think it's in "extras"

**Comment by JustinLivi** [comment] 2015-10-17 19:39
@thaJeztah ah that should have been obvious. Thanks very much though, confirmed docker-selinux fixed it.

**Comment by thaJeztah** [comment] 2015-10-17 19:43
@JustinLivi good to hear!
