### ISSUE TITLE
docker-compose with docker-swarm deploys all containers to same node

### ISSUE THREAD

**Issue by charlesmims** [docker/docker#23885] opened 2016-06-23 04:03 UTC
**Output of `docker version`:**

[22:39:30] cmims@MBP:~/dc-mesos$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      swarm/1.2.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   eaa53c7
 Built:        Fri May 27 17:25:03 UTC 2016
 OS/Arch:      linux/amd64
[22:39:34] cmims@MBP:~/dc-mesos$

This is on OSX el capitan, all recent updates applied.  Previously I was running docker-toolbox 1.10 or 1.11, and today I installed OSX native docker and the most recent docker-toolbox. 

**Output of `docker info`:**

[22:39:34] cmims@MBP:~/dc-mesos$ docker info
Containers: 9
 Running: 7
 Paused: 0
 Stopped: 2
Images: 17
Server Version: swarm/1.2.3
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 3
 swarm-demo-1: 192.168.99.103:2376
  └ ID: SGMI:VTIP:F5UD:AN4M:ADT7:GA5Y:DNDA:S362:LITZ:QAKG:MIEC:OAT6
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=, kernelversion=4.4.13-boot2docker, operatingsystem=Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016, provider=virtualbox, storagedriver=aufs
  └ UpdatedAt: 2016-06-23T03:40:09Z
  └ ServerVersion: 1.12.0-rc2
 swarm-demo-2: 192.168.99.102:2376
  └ ID: SVL3:FEDI:ZIEX:MD5F:TWSA:V34I:EHLZ:EURR:VVGV:S7L7:R2F3:CB5T
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=, kernelversion=4.4.13-boot2docker, operatingsystem=Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016, provider=virtualbox, storagedriver=aufs
  └ UpdatedAt: 2016-06-23T03:40:05Z
  └ ServerVersion: 1.12.0-rc2
 swarm-demo-3: 192.168.99.101:2376
  └ ID: SNXV:XMFE:KZXV:NVVX:3CM4:KK2F:H2U2:RV5B:TVVG:JCLI:5ORK:CWM4
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=, kernelversion=4.4.13-boot2docker, operatingsystem=Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016, provider=virtualbox, storagedriver=aufs
  └ UpdatedAt: 2016-06-23T03:40:09Z
  └ ServerVersion: 1.12.0-rc2
Plugins:
 Volume:
 Network:
Swarm:
 NodeID:
 IsManager: No
Security Options:
Kernel Version: 4.4.13-boot2docker
Operating System: linux
Architecture: amd64
CPUs: 3
Total Memory: 3.063 GiB
Name: d5f281428064
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support

**Steps to reproduce the issue:**

  1- create a file called "swaminate" with the following:
```
set -e

create() {
  echo Setting up kv store
  docker-machine create -d virtualbox kvstore > /dev/null && \
  docker $(docker-machine config kvstore) run -d --net=host progrium/consul --server -bootstrap-expect 1

  # store the IP address of the kvstore machine
  kvip=$(docker-machine ip kvstore)

  echo Creating cluster nodes
  docker-machine create -d virtualbox \
    --engine-opt "cluster-store consul://${kvip}:8500" \
    --engine-opt "cluster-advertise eth1:2376" \
    --swarm \
    --swarm-master \
    --swarm-discovery consul://${kvip}:8500 \
    swarm-demo-1 > /dev/null &

  for i in 2 3; do
    docker-machine create -d virtualbox \
      --engine-opt "cluster-store consul://${kvip}:8500" \
      --engine-opt "cluster-advertise eth1:2376" \
      --swarm \
      --swarm-discovery consul://${kvip}:8500 \
      swarm-demo-$i > /dev/null &
  done
  wait
}

teardown() {
  docker-machine rm kvstore &
  for i in 1 2 3; do
    docker-machine rm -f swarm-demo-$i &
  done
  wait
}

case $1 in
  up)
    create
    ;;
  down)
    teardown
    ;;
  *)
    echo "I literally can't even..."
    exit 1
    ;;
esac
```

  2- bring the cluster up

```
chmod +x swarminator
./swarminator up
```

  3- create docker-compose.yml with the following:

```
version: '2'
services:
  zookeeper:
    image: garland/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  mesosmaster:
    image: garland/mesosphere-docker-mesos-master
    ports:
      - "5050:5050"
    links:
      - zookeeper:zk
    environment:
      - MESOS_ZK=zk://zk:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_WORK_DIR=/var/lib/mesos
  marathon:
    image: garland/mesosphere-docker-marathon
    links:
      - zookeeper:zk
      - mesosmaster:master
    command: --master zk://zk:2181/mesos --zk zk://zk:2181/marathon
    ports:
      - "8080:8080"
  mesosslave:
    image: garland/mesosphere-docker-mesos-master
    ports:
      - "5051:5051"
    links:
      - zookeeper:zk
      - mesosmaster:master
    entrypoint: mesos-slave
    environment:
      - MESOS_HOSTNAME=192.168.99.100
      - MESOS_MASTER=zk://zk:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_LOGGING_LEVEL=INFO
```

  4- run the docker compose on the swarm

```
eval $(docker-machine env --swarm swarm-demo-1)
docker-compose up
```

**Describe the results you received:**

The above steps will create 4 containers all on the same node of the swarm.  Attempting to scale up mesos slaves with `docker-compose mesoslave=2` will give the following error:

```
[22:50:16] cmims@MBP:~/dc-mesos$ docker-compose scale mesosslave=2
WARNING: The "mesosslave" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating and starting dcmesos_mesosslave_2 ... error

ERROR: for dcmesos_mesosslave_2  Unable to find a node that satisfies the following conditions
[port 5051 (Bridge mode)]
[available container slots]
[--link=dcmesos_mesosmaster_1:dcmesos_mesosmaster_1 --link=dcmesos_mesosmaster_1:master --link=dcmesos_mesosmaster_1:mesosmaster_1 --link=dcmesos_zookeeper_1:dcmesos_zookeeper_1 --link=dcmesos_zookeeper_1:zk --link=dcmesos_zookeeper_1:zookeeper_1]
```

```
[22:50:18] cmims@MBP:~/dc-mesos$ docker-machine ls
NAME           ACTIVE      DRIVER       STATE     URL                         SWARM                   DOCKER        ERRORS
kvstore        -           virtualbox   Running   tcp://192.168.99.100:2376                           v1.12.0-rc2
swarm-demo-1   * (swarm)   virtualbox   Running   tcp://192.168.99.103:2376   swarm-demo-1 (master)   v1.12.0-rc2
swarm-demo-2   -           virtualbox   Running   tcp://192.168.99.102:2376   swarm-demo-1            v1.12.0-rc2
swarm-demo-3   -           virtualbox   Running   tcp://192.168.99.101:2376   swarm-demo-1            v1.12.0-rc2
```

```
[22:51:43] cmims@MBP:~/dc-mesos$ docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                                                                         NAMES
41b081c97fd4        garland/mesosphere-docker-mesos-master   "mesos-slave"            2 minutes ago       Up 2 minutes        192.168.99.101:5051->5051/tcp                                                                 swarm-demo-3/dcmesos_mesosslave_1
a648d51dc63d        garland/mesosphere-docker-mesos-master   "mesos-master"           2 minutes ago       Up 2 minutes        192.168.99.101:5050->5050/tcp                                                                 swarm-demo-3/dcmesos_mesosmaster_1
df8a8408daa2        garland/zookeeper                        "/opt/run.sh"            2 minutes ago       Up 2 minutes        192.168.99.101:2181->2181/tcp, 192.168.99.101:2888->2888/tcp, 192.168.99.101:3888->3888/tcp   swarm-demo-3/dcmesos_zookeeper_1
ef66edee029a        nginx                                    "nginx -g 'daemon off"   25 minutes ago      Up 25 minutes       443/tcp, 192.168.99.102:8080->80/tcp                                                          swarm-demo-2/silly_pasteur
c3f8eb723c9d        nginx                                    "nginx -g 'daemon off"   25 minutes ago      Up 25 minutes       443/tcp, 192.168.99.101:8080->80/tcp                                                          swarm-demo-3/amazing_lumiere
c4f01a22354c        nginx                                    "nginx -g 'daemon off"   25 minutes ago      Up 25 minutes       443/tcp, 192.168.99.103:8080->80/tcp                                                          swarm-demo-1/big_wing
```

As a counter example, I can run `docker run -d -p 8080:80 nginx` as many times as there are nodes in the swarm, and it will create <number of swarm nodes> containers all listening on port 8080, each running on its own node at its own IP address, as shown in the above `docker ps` output.

**Describe the results you expected:**

I expected the output of `docker ps` to show that `docker-compose up`  deployed the containers from dc-mesos/docker-compose.yml to each of the nodes of the swarm, such that I could scale up mesosslave to at least the number of nodes in my swarm.

**Additional information you deem important (e.g. issue happens only occasionally):**

This has happened consistently through half a dozen attempts in various iterations since I updated to OSX native docker and 1.12.0-rc toolbox.  I don't know if it worked on what I was on before.  I think it was docker-toolbox with docker version 1.10 or 1.11.  I included the examples that I think are most illustrative of the problem in the steps to reproduce and output of `docker ps`.  If there is anything I can do to help isolate this further, or if others are unable to reproduce, please let me know at charlesmims@gmail.com.

**Comment by kelseyhightower** [comment] 2016-06-23 14:34
Maybe this has something to do with bin packing by default for services, which in most cases is the right thing to do. In your case it seems there is a resource conflict around ports which must be accounted for. In other systems such as HashiCorp's Nomad, the port is considered a resource constraint, and if specified the Nomad scheduler will detect the conflict and prefer another node.

Another approach would be to explicitly handle this use case with something that is designed to run a single copy of a service on every node. Kubernetes calls these [DaemonSets](http://kubernetes.io/docs/admin/daemons) and Nomad calls these [System Jobs](https://www.nomadproject.io/docs/jobspec/schedulers.html).

**Comment by charlesmims** [comment] 2016-06-23 16:54
From the output of `docker info`, my swarm is configured to use spread strategy.  According to https://docs.docker.com/swarm/scheduler/strategy/, spread is the default.  Maybe there's something I'm missing with regard to services.

```
[22:39:34] cmims@MBP:~/dc-mesos$ docker info
...
Strategy: spread
...
```

I found this issue that may be related:  https://github.com/docker/compose/issues/3042
I'm trying the suggestions there.

**Comment by charlesmims** [comment] 2016-06-23 19:46
I haven't gotten it working yet but at this point I'm fairly convinced it's a problem with my docker-compose.yml and not something wrong with docker-swarm or docker-compose.  IOW, I'm doing it wrong.

**Comment by cpuguy83** [comment] 2016-06-24 14:41
@charlesmims This is because of your the `links`, which signals to the swarm scheduler that the containers need to be co-scheduled.
Use networks instead of links and this should resolve the issue.

IMO, ideally compose would not use the old style links but rather set network aliases when someone uses the `links` keyword.

**Comment by tiborvass** [comment] 2016-06-27 15:17
@cpuguy83 can we then close this issue or is there something else to do here?

**Comment by cpuguy83** [comment] 2016-06-27 15:19
@charlesmims can you confirm that this is your issue?

**Comment by thaJeztah** [comment] 2016-06-27 23:02
ping @dnephin @aanand ^^

**Comment by aanand** [comment] 2016-06-27 23:23
> IMO, ideally compose would not use the old style links but rather set network aliases when someone uses the `links` keyword.

This is already the case when you're using v2 of the Compose file format, and is in fact implemented at the Engine level (the API is identical - you set the `Links` key in the container config).

Old-style links are only used when containers are created with `"NetworkMode": "default"`, which Compose only does for v1 files (to preserve backwards compatibility). For v2 files, every container (by default) joins a network created especially for the Compose app.

I believe the issue is with Swarm. It should _only_ enforce co-scheduling if the container is using old-style links (i.e. if it's created with `"NetworkMode": "default"`), but it currently _always_ enforces it, regardless of network mode, if the `Links` key is set.

cc @abronan @amitshukla - is this correct?

**Comment by tiborvass** [comment] 2016-06-27 23:54
I opened https://github.com/docker/swarm/issues/2384 to track the issue @aanand mentioned. Closing this one as it is not an issue with engine.

**Closed by tiborvass** 2016-06-27 23:54 UTC
Labels: area/swarm, version/1.12

**Comment by thaJeztah** [comment] 2016-06-28 01:20
> This is already the case when you're using v2 of the Compose file format, and is in fact implemented at the Engine level (the API is identical - you set the Links key in the container config).

@aanand you're absolutely right, I thought about that after pinging you

**Comment by janbuj** [comment] 2016-06-29 08:25
I have exacly the same problem. I can spawn containers across whole all 1.12 rc2 swarm nodes with docker service but when I try to spawn lets say 3 nginx nodes (all listening on port 80) using docker-compose it only spawns 1 on the manager node and says that rest cannot be created due to port 80 being already used. I am using docker-compose 1.8.0.-rc1. There are no links or any stuff like that in it. I even tried just bare docker-compose.yml with only image and port settings in it.

**Comment by cpuguy83** [comment] 2016-06-29 11:42
docker-compose does not take advantage of swarm mode. It only runs containers on the specified host.
