### ISSUE TITLE
Is there a way to use docker with recently released Linux subsystem for Windows?

### ISSUE THREAD

**Issue by fastmuse** [docker/docker#25389] opened 2016-08-04 04:21 UTC

**Comment by friism** [comment] 2016-08-04 04:46
@fastmuse you can't run the Linux daemon in WSL, I think  because the relevant Linux kernel APIs are not (yet) emulated by WSL. You _can_ run the Linux CLI in WSL, targeting any daemon you'd like over TCP (using either `-H` or `DOCKER_HOST`.

**Comment by thaJeztah** [comment] 2016-08-04 11:16
Correct, it's not (currently) possible

I'll close this issue, because this is not a bug, and I think this question is answered

**Closed by thaJeztah** 2016-08-04 11:16 UTC
