### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by aliabbasjp** [docker/docker#20689] opened 2016-02-25 09:46 UTC
On running the docker command, I get following error:

 docker run hello-world

Pulling repository docker.io/library/hello-world
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy..

I am getting following CURL output:
<pre>
 curl -v https://index.docker.io
* Rebuilt URL to: https://index.docker.io/
* Hostname was NOT found in DNS cache
*   Trying 54.152.78.181...
* Connected to index.docker.io (54.152.78.181) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):

* Unknown SSL protocol error in connection to index.docker.io:443
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to index.docker.io:443
</pre>

So how will i pull my machines now?

Now getting following message:

Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
03f4658f8b78: Downloading
a3ed95caeb02: Downloading
docker: x509: certificate signed by unknown authority.

**Update(obfuscated keys):**

running following command gives output:
<pre>
~$ openssl s_client -connect index.docker.io:443
CONNECTED(00000003)
depth=1 C = US, O = GeoTrust Inc., CN = RapidSSL SHA256 CA - G3
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/OU=GT98568428/OU=See www.rapidssl.com/resources/cps (c)15/OU=Domain Control Validated - RapidSSL(R)/CN=*.docker.io
   i:/C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G3
 1 s:/C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G3
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIEpDCCA4ygAwIBAgIDAyF3MA0GCSqGSIb3DQEBCwUAMEcxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuLQYDVQQLEyZEb21haW4gQ29udHJvbCBW
YWxpZGF0ZWQgLSBSYXBpZFNTTChSKTEUMBIGA1UEAwwLKi5kb2NrZXIuaW8wggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDRyme75dbw9AxWZ8QFCwMWrrYY
SclZ6HCiEbxSNxHgg08rEfEYi46VrL+joBwlA0t5WIIxHF198NzzdXC4YeGzruY9
7osv5lPrcdeIi+Ad+fY6K0rBBOB3xdqSPPObrINZpDmWhCQjlsnM6a1Th0oSUCjI
345b84/8PH363YO+Qmnl8BWnaTcZoPzeywM9czQsMyF2bOH+dhxja/zim6iu8W34
yBhVQeQRd1QROuHcsQAX19DKTn6TXaAwIBY3xM1Bi5Zl6tueII4dOEoibw/ImR3c
H73Pk7j1Wx+rAXeeq7LwjkUCCSlKNrHFEQ2nbr0R7FH6cck1ppgM8ud1pHr9AgMB
AAGjggFOMIIBSjAfBgNVHSMEGDAWgBTDnPP800YINLvORn+gfFvz4gjLWTBXBggr
BgEFBQcBAQRLMEkwHwYIKwYBBQUHMAGGE2h0dHA6Ly9ndi5zeW1jZC5jb20wJgYI
KwYBBQUHMAKGGmh0dHA6Ly9ndi5zeW1jYi5jb20vZ3YuY3J0MA4GA1UdDwEB/wQE
AwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwIQYDVR0RBBowGIIL
Ki5kb2NrZXIuaW+CCWRvY2tlci5pbzArBgNVHR8EJDAiMCCgHqAchhpodHRwOi8v
Z3Yuc3ltY2IuY29tL2d2LmNybDAMBgNVHRMBAf8EAjAAMEEGA1UdIAQ6MDgwNgYG
Z4EMAQIBMCwwKgYIKwYBBQUHAgEWHmh0dHBzOi8vd3d3LnJhcGlkc3NsLmNvbS9s
ZWdhbDANBgkqhkiG9w0BAQsFAAOCAQEATYgwOYz/w9Qyh/YPZQDZ0BdwhkX6OCX0
Mz8pP/OO+E+1RM7ZoAGwHvIaidFqh3WeCLHjGO2IId7Ff5EZUwZhiwog0R7Y838x
OCLza/2shuvjM/FPiyXDQ6q0w4rvpwsNjmYVDdYD8bCH3b8IlO2ysjgdhRYprsdU
jg6h+zK11/tXf6S5vegrgV0F62DYx0tuTTZq/HMuXvbgY2uL1sQ5jiHlzQndV9oL
YMYqJP5MkuAKzDL5u0b8mD/EHtoPkfWOIsA5i9YrAAoWRVOJHwfFfgSY+EpXpFc4
AZUPmdZGh6q1YNavRoOL/1D5aP/VBBtofj54uMbKOK8q6vxIXSyzaw==
-----END CERTIFICATE-----
subject=/OU=GT98568428/OU=See www.rapidssl.com/resources/cps (c)15/OU=Domain Control Validated - RapidSSL(R)/CN=*.docker.io
issuer=/C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G3
---
No client certificate CA names sent
---
SSL handshake has read 2914 bytes and written 421 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 111E09F815E121C7EA7E7FD0C07C4AC31FFDE4E13AD9BA926AFF03A2E267130C
    Session-ID-ctx:
    Master-Key: 78A4ABC11BFCCA245F4B3FE8BDA0C0BC3A10D3E9BB447838B06D8BB16DA1553DBBCBFE03408AF34FB7D0CA5E3E7E8D40
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 57 92 4f 5c a0 41 ab d9-62 2c b1 05 66 b5 bc 79   W.O\.A..b,..f..y
    0010 - c8 32 a1 b0 f3 df 3d e7-c8 8d 0b 62 b2 6f 2b 99   .2....=....b.o+.
    0020 - 80 e1 60 73 19 67 bd c5-bf 4c 61 26 ca 3c 4d bd   ..`s.g...La&.<M.
    0030 - 5c 4b a2 e7 d7 2a 49 13-f7 b2 8d 6c f0 2e f5 7d   \K...*I....l...}
    0040 - 4b 7f c4 76 cd 9f e0 f0-c4 3c b2 1e 4c 32 e3 d4   K..v.....<..L2..
    0050 - 3a 62 10 d4 a7 76 d7 3d-3b 4a b9 d0 05 4b 03 5c   :b...v.=;J...K.\
    0060 - 81 a1 59 5c 24 ad 3a 82-66 b7 1b 20 c6 db 95 89   ..Y\$.:.f.. ....
    0070 - 39 98 b8 b6 0f 8d ea 2c-d7 bb 51 52 93 c5 db 18   9......,..QR....
    0080 - a1 bb f6 31 ec 58 59 d0-e3 63 8f 3e 69 8a c9 bd   ...1.XY..c.>i...
    0090 - ea ca 71 3e 9a 64 e8 23-dc f6 77 b4 6a 59 ac cd   ..q>.d.#..w.jY..
    Start Time: 1456385623
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
</pre>

I tried following commands but in vain:

sudo update-ca-certificates
sudo service docker restart

docker info
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 0
Server Version: 1.10.2
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 0
Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
Volume: local
Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.8 GiB
Name: Data-Server
ID: OUQ6:L64D:LVGG:FHTQ:IHJI:WDBV:7FH7:B53B:33CL:RGAK:LDQ7:N2OS
WARNING: No swap limit support

docker version
Client:
Version: 1.10.2
API version: 1.22
Go version: go1.5.3
Git commit: c3959b1
Built: Mon Feb 22 21:37:01 2016
OS/Arch: linux/amd64
Server:
Version: 1.10.2
API version: 1.22
Go version: go1.5.3
Git commit: c3959b1
Built: Mon Feb 22 21:37:01 2016
OS/Arch: linux/amd64

**Comment by HackToday** [comment] 2016-02-25 09:56
how did you come to this state?  Could you give some context instead of just say related issue here ?

and please append `docker info` and `docker version`

**Comment by aliabbasjp** [comment] 2016-02-25 10:02
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.8 GiB
Name: Data-Server
ID: OUQ6:L64D:LVGG:FHTQ:IHJI:WDBV:7FH7:B53B:33CL:RGAK:LDQ7:N2OS
WARNING: No swap limit support


 docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

**Comment by aliabbasjp** [comment] 2016-02-25 10:04
@HackToday  I have posted info version

**Comment by thaJeztah** [comment] 2016-02-25 10:22
@aliabbasjp are you using a proxy server?

Given that you're also not able to connect using cURL, this sounds like an issue in your machines configuration, or your network, not a bug in Docker

**Comment by aliabbasjp** [comment] 2016-02-25 10:26
No I am not behind any proxy server , I am perfectly able to access all other sites , even the images list is displayed . @thaJeztah

**Comment by thaJeztah** [comment] 2016-02-25 10:53
>  even the images list is displayed

What do you mean? Which images list?

The error message "unable to get local issuer certificate" really sounds like something is misconfigured on your host; at least, it's not an issue in the docker engine code, so I'm not sure what we can do here.

**Comment by aliabbasjp** [comment] 2016-02-25 11:24
@thaJeztah  
I mean 
03f4658f8b78: Downloading
a3ed95caeb02: Downloading

is dispalyed after retrying yet it throws error , similar issues are also discussed in other issue threads.

Everything is properly configured with all certificates in place, yet it fails.
During installation this command did not work:
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

**Comment by proligde** [comment] 2016-02-25 13:10
I stumbled over a similar problem at least on one of our Ubuntu 14.04 servers this morning:

@aliabbasjp you wrote:

openssl s_client -connect index.docker.io:443

returning "unable to get local issuer certificate". Actually it means exactly that: The server is not able to get the local ca-path. When I try

openssl s_client -CAfile /etc/ssl/certs/ca-certificates.crt -connect index.docker.io:443

instead it's returning code 0 (ok). That could mean something was messed up during an update regarding the default CA-Path location openssl uses, but I'm still investigating ATM.

make a check against www.google.com as well. If this returns an error as well (what I think it does) it's not a docker related problem.

Regards - max

**Comment by thaJeztah** [comment] 2016-02-25 13:41
Yeah, I'm closing this issue for now, but feel free to continue the discussion here; hope you're able to resolve your issue.

**Closed by thaJeztah** 2016-02-25 13:41 UTC

**Comment by proligde** [comment] 2016-02-25 13:49
I found out what the problem was: Something did change indeed regarding the location/handling of CA-Certificates which can cause this issue since the update did not restart all services relying on CA-Certificate locations. The classic turning-it-all-off-and-on-again fixed the issue here ;-)
