### ISSUE TITLE
Container ID and Hostname are not the same.

### ISSUE THREAD

**Issue by stylixboom** [docker/docker#29127] opened 2016-12-05 11:11 UTC
**Description**

I used to be able to access the current running **ContainerID** within the container itself by using an environment variable **HOSTNAME** (v. 1.12~)

However, in the current version 1.13.0-rc2, the good old behavior seemed strange, ContainerID and HOSTNAME are not the same anymore.
Also, it much worst as the different container (different ContainerID) got exactly the same **HOSTNAME** (e.g. "7103ce58678c") when I run it from the same image.

**Steps to reproduce the issue:**
---- Container 1 (id 3f6c14757a10) ----
```
$ docker run --rm -it image bash
root@3f6c14757a10: echo $HOSTNAME
7103ce58678c
```

---- Container 2 (id 684ff6a8e8dd) ----
```
$: docker run --rm -it image bash
root@684ff6a8e8dd: echo $HOSTNAME
7103ce58678c
```

**Describe the results you expected:**
I used to be able to access the ContainerID from **within** the container itself.
This is very useful when I need to dynamically modify the current running container from within the container, through a docker.sock.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 06:32:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 06:32:39 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 62
Server Version: 1.13.0-rc2
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay weavemesh
Swarm: active
 NodeID: dp6wemenqlux1kjo95p9aih53
 Is Manager: true
 ClusterID: 45hwgqkhb5mp5bbmc8ygfhexl
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.128.0.215
 Manager Addresses:
  10.128.0.215:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-51-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.953 GiB
Name: stylixvm
ID: NQTM:7MTH:3PXO:BL7T:7YYD:PDUU:LWMW:IOHT:QLW7:EUK4:E5NA:6Z76
Docker Root Dir: /mnt/data_disk/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://10.136.0.60:8080
Https Proxy: https://10.136.0.60:8080
No Proxy: localhost,127.0.0.0/8
Username: stylix
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2016-12-05 12:03
At first, I thought this was related to https://github.com/docker/docker/issues/28149, but I'm not able to reproduce your issue, I tried several scenarios;

Running from a "plain" ubuntu image;

```bash
$ docker run -it --rm ubuntu bash -c 'echo $HOSTNAME && hostname'
406538c1025a
406538c1025a

$ docker run -it --rm ubuntu bash -c 'echo $HOSTNAME && hostname'
a6ee2cc2cbab
a6ee2cc2cbab
```

Building a new image locally, and run containers from that;

```bash
$ cat > Dockerfile <<EOF
FROM ubuntu:latest
RUN echo "foo"
EOF

$ docker build -t foo .
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM ubuntu:latest
 ---> 4ca3a192ff2a
Step 2/2 : RUN echo "foo"
 ---> Running in 9407330c90b8
foo
 ---> 7457621f88ca
Removing intermediate container 9407330c90b8
Successfully built 7457621f88ca
```

```bash
$ docker run -it --rm foo bash -c 'echo $HOSTNAME && hostname'
4fc0ef8a07cd
4fc0ef8a07cd

$ docker run -it --rm foo bash -c 'echo $HOSTNAME && hostname'
934d23dc7551
934d23dc7551
```

The only way I _was_ able to pin the hostname is when explicitly setting it as an env-var in the docker file;

```bash
$ cat > Dockerfile <<EOF
FROM ubuntu:latest
RUN echo "foo"
ENV HOSTNAME foobar
EOF

$ docker build -t foobar .
Sending build context to Docker daemon 2.048 kB
Step 1/3 : FROM ubuntu:latest
 ---> 4ca3a192ff2a
Step 2/3 : RUN echo "foo"
 ---> Using cache
 ---> 7457621f88ca
Step 3/3 : ENV HOSTNAME foobar
 ---> Running in f0dd882c1c6b
 ---> 22020a0e388f
Removing intermediate container f0dd882c1c6b
Successfully built 22020a0e388f
```

```bash
$ docker run -it --rm foobar bash -c 'echo $HOSTNAME && hostname'
foobar
7946329da287

$ docker run -it --rm foobar bash -c 'echo $HOSTNAME && hostname'
foobar
1c0cd7bf0ba6
```


Would you be able to provide the exact steps to reproduce your issue?

**Comment by thaJeztah** [comment] 2016-12-05 12:25
To verify if it's due to something that changed in `docker build`, I also tried to build an image on a docker 1.10 daemon, then loading the built image into a docker 1.13-rc2 daemon, and running a container from that, but I was also not able to reproduce.

(note: for "introspection" of the container, you may be interested in https://github.com/docker/docker/pull/26331)

**Comment by stylixboom** [comment] 2016-12-05 13:27
Thanks @thaJeztah, introspection is a very interesting feature, I will try and wait for the stable release soon.

For the problem, it appears after I used the custom prebuild image (instead of building most of things from scratch).
So, I will check if that prebuild image contains an ENV HOSTNAME in any step.

Note: I'm actually out of my terminal, so I cannot try until tomorrow.

**Comment by thaJeztah** [comment] 2016-12-05 13:31
@stylixboom thanks in advance! It's possible there _is_ a bug somewhere, I just wasn't able to reproduce the issue, so if you can provide the steps to reproduce, the maintainers can look into it, and verify if it's a bug or not

**Comment by stylixboom** [comment] 2016-12-06 08:32
@thaJeztah Yes, I found that ENV HOSTNAME is in my bootstrapped image.
This is not an issue for docker anymore.

Thank you for this investigation.

Note: waiting for introspection :)

**Comment by thaJeztah** [comment] 2016-12-06 08:41
Thanks for checking! Glad to hear it's not a regression. I'll close this issue

**Closed by thaJeztah** 2016-12-06 08:41 UTC
Labels: area/networking, status/more-info-needed, version/1.13
