### ISSUE TITLE
docker container not writing to mounted volume on host

### ISSUE THREAD

**Issue by babatundebusari** [docker/docker#24508] opened 2016-07-11 16:32 UTC
I am having issue writing to the mounted volume on host filesystem from docker container

Is there some special thing i have to do when building the container to make the container write data to the mounted volume on host for persistency?

I have seen containers that write to host filesystem like the official mysql docker image and several others but when i build my own images, and i mount the volume on host, i find out it doesn't write to host, but only reads from the host.

Not sure what to add here code wise but if you guys need anything please ask and i will update my question.

Thanks

**Comment by Purple90** [comment] 2016-07-11 19:14
Can you post your run command? You are probably not mapping it correctly. You need to do something like

docker run -v /foo/bar:/containerfolder

That will then be written on the host

**Comment by babatundebusari** [comment] 2016-07-11 19:25
i am using docker-compose and yes i am mapping it properly, like i said it reads but does not write, so it won't be able to read either if am not mapping it well

Here is docker-compose of two images, grafana official image maps PROPERLY and writes ad reads, but the custom graphite image does NOT write but read only.

```
graphite:
    image: devsystem.com/graphite
    container_name: graphite
    restart: always
    ports:
        - "8080:80"
        - "2003:2003"
        - "2003:2003/udp"
        - "2004:2004"
        - "7002:7002"
        - "8125:8125"
        - "8126:8126"
    volumes:
        - "/data/var/lib/graphite/storage/whisper:/var/lib/graphite/storage/whisper"

grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
        - "80:3000"
    volumes:
        - "/data/var/lib/grafana:/var/lib/grafana"
    links:
        - graphite
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=whatever
```

**Comment by vdemeester** [comment] 2016-07-11 19:28
@babatundebusari can you give us more information about your setup ?

- `docker version`, `docker info`
- The OS/Plateform you're running on (windows, mac, linux — docker for mac, docker toolbox, etc…)
- Are you pointing to a remote engine ?

Thanks 👼

**Comment by babatundebusari** [comment] 2016-07-11 19:31
@vdemeester 

```
~# docker info

Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 116
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 144
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: complex-elk
ID: 34WC:25GN:4AMK:FJDZ:WNRN:FFRK:RWHW:BAOD:5OG4:LLBU:GTYU:MCO5
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```


```
~# docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

```
~# cat /etc/*release*

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
```


No it is mounting to host filesystem on the docker engine host from container

**Comment by babatundebusari** [comment] 2016-07-11 20:42
I am thinking there is something am doing wrong when building my custom images, because this always happen to my custom images

I also built an nginx-php-fpm image and it does not write to mounted volume on host filesystem as well, but reads.

So can someone tell me it there is anything i need to do apart from exposing that volume path to be mounted on Dockerfile, do i need to do anything else?

**Comment by vdemeester** [comment] 2016-07-11 20:44
@babatundebusari how does your `Dockerfile` looks like ? Note that you don't need to declare a `VOLUME` in your `Dockerfile` to use `-v` flag on it :wink:

**Comment by babatundebusari** [comment] 2016-07-11 20:54
@vdemeester 

looks like this

```
FROM ubuntu:14.04
MAINTAINER Babatunde Busari

ENV DEBIAN_FRONTEND noninteractive

RUN	echo 'deb http://us.archive.ubuntu.com/ubuntu/ trusty universe' >> /etc/apt/sources.list
RUN	apt-get -y update

RUN apt-get install -y software-properties-common && \
  add-apt-repository -y ppa:chris-lea/node.js && \
  apt-get update -y 
  
# Install required packages
RUN	apt-get -y install git python-ldap python-cairo python-django python-twisted python-django-tagging python-simplejson python-memcache python-pysqlite2 python-support python-tz python-pip gunicorn supervisor nginx-light nodejs build-essential curl
RUN	pip install whisper==0.9.15
RUN	pip install --install-option="--prefix=/var/lib/graphite" --install-option="--install-lib=/var/lib/graphite/lib" carbon==0.9.15
RUN	pip install --install-option="--prefix=/var/lib/graphite" --install-option="--install-lib=/var/lib/graphite/webapp" graphite-web==0.9.15


# install statsd
RUN git clone -b v0.7.2 https://github.com/etsy/statsd.git /opt/statsd

# ADD system service config
ADD	./nginx.conf /etc/nginx/nginx.conf
ADD	./supervisord.conf /etc/supervisor/conf.d/supervisord.conf
ADD ./statsd_config.js /etc/statsd/config.js


# ADD graphite config
ADD	./initial_data.json /var/lib/graphite/webapp/graphite/initial_data.json
ADD	./local_settings.py /var/lib/graphite/webapp/graphite/local_settings.py
ADD	./carbon.conf /var/lib/graphite/conf/carbon.conf
ADD	./storage-schemas.conf /var/lib/graphite/conf/storage-schemas.conf
RUN	mkdir -p /var/lib/graphite/storage/whisper
RUN	touch /var/lib/graphite/storage/graphite.db /var/lib/graphite/storage/index
RUN	chown -R www-data /var/lib/graphite/storage
RUN	chmod 0775 /var/lib/graphite/storage /var/lib/graphite/storage/whisper
RUN	chmod 0664 /var/lib/graphite/storage/graphite.db
RUN	cd /var/lib/graphite/webapp/graphite && python manage.py syncdb --noinput


# Setup Volume
VOLUME ["/var/lib/graphite/storage/whisper"]


# Nginx
EXPOSE	80
# Carbon line receiver port
EXPOSE	2003
# Carbon UDP receiver port
EXPOSE	2003/udp
# Carbon pickle receiver port
EXPOSE	2004
# Carbon cache query port
EXPOSE	7002
# StatsD UDP
EXPOSE 8125 
# StatsD Admin
EXPOSE 8126

CMD	["/usr/bin/supervisord"]
```

**Comment by thaJeztah** [comment] 2016-07-11 23:32
@babatundebusari can you try with a minimum example? For example;

```yaml
tester:
    image: alpine
    volumes:
        - "./hostmount/:/var/lib/graphite/storage/whisper"
    command: "sh -c 'echo hello >> /var/lib/graphite/storage/whisper/blabla'"
```

This will create a directory `hostmount` on the host, and write a "blabla" file in it, containing "hello";

```bash
$ docker-compose up
Creating repro24508_tester_1
Attaching to repro24508_tester_1
repro24508_tester_1 exited with code 0

$ cat hostmount/blabla
hello
```

**Comment by clhlc** [comment] 2016-07-12 03:57
You can test use -v in command line, and delete VOLUME in you dockerfile.

**Comment by babatundebusari** [comment] 2016-07-12 14:57
@thaJeztah 

Yes it worked and was able to write to my host when i used your docker-compose file. Like i said some containers write as well, so i am thinking there is something am doing wrong.

If you read my post i mentioned if there is anything i need to do to ensure this containers write to the host file system but most of my custom images are just not working

i think am going to create an image and put on dockerhub so people can just pull and test what am saying

**Comment by thaJeztah** [comment] 2016-07-12 15:51
@babatundebusari only advice I can give is to "strip back" your image, and try step-by-step, to see what the issue is.

Based on the above, this doesn't look to be a bug in Docker, but something in your image (configuration), so I'll close this issue, but feel free to continue the discussion here

**Closed by thaJeztah** 2016-07-12 15:51 UTC
Labels: status/more-info-needed

**Comment by babatundebusari** [comment] 2016-07-13 01:13
ok you can test with this apache-php-fpm docker image i made public

If you run the docker image without mounting volume you can see the index.php file and see output of phpinfo but when you mount volume to host, then that file is not there

This is the same issue i come across everytime

Here is link to github of the project and also the dockerhub for the image

github: https://github.com/babatundebusari/docker-apache-php-fpm
dockerhub image: https://hub.docker.com/r/babatundebusari/docker-apache-php-fpm/

Help will be greatly appreciated

Thanks

**Comment by thaJeztah** [comment] 2016-07-13 08:36
@babatundebusari there's two issue; first one is that you try to add files *after* defining a volume https://github.com/babatundebusari/docker-apache-php-fpm/blob/master/Dockerfile#L76-L80. During build, every build step is executed in a new container, and mounts a new volume; any change you make to the volume may get lost due to that (see https://docs.docker.com/engine/reference/builder/#/volume)

However, the actual issue is that you're bind-mounting a host directory into the container. Bind mounts are not volumes, and by using a bind-mount, you're telling docker to mount the files that are *on the host*, and mount those *in the comtainer*. If this host-directory is empty, docker bind-mounts an empty directory; so, the index.php will be there.

The comtainer is able to create *new* files in that directory, or modify files that are in there, but the contents of the container is not automatically copied to the host.

**Comment by babatundebusari** [comment] 2016-07-13 14:27
@thaJeztah 
How else should i mount volume on container to host?
Is there another way to mount other than the `-v` volume option?

**Comment by thaJeztah** [comment] 2016-07-13 14:57
@babatundebusari the usual approach is to have your source-files locally, and bind-mount them into the container during development, for example:

```Dockerfile
FROM somewhere
COPY . /app/
``

You can use a `docker-compose.yml` to build and run the image, but during development, you bind-mount your local source files "over" the files copied into the container, so that you can "live" edit those files, e.g.:

```yaml
version: '2'
services:
  web:
    build: .
    image: my app:1.0
    volumes:
      - ./webroot/:/app/webroot/
```

Once you're modifications are done, you can either `docker build` the image, and `docker push` it to the registry to deploy it, or use automated builds so that Docker Hub automatically builds the latest version of your code in a new image.

**Comment by babatundebusari** [comment] 2016-07-13 15:06
@thaJeztah 

I see what you recommend BUT my issue is i have seen docker images able to read and write and that is what i want to do and nothing more really. 

I just want the container to write files to my mount on host as well. This is not magic as i have seen docker images do this. Example? the mysql docker image does this, and reads files from mount on host and also write for new db data.

All i am trying to do.

**Comment by thaJeztah** [comment] 2016-07-13 15:23
@babatundebusari but my earlier example shows that it does exactly that: https://github.com/docker/docker/issues/24508#issuecomment-231896397

That example starts a docker container, which writes "hello" to a file named "blabla" *on the host*

**Comment by babatundebusari** [comment] 2016-07-13 15:25
So why isn't my docker image doing what i want?
That is why i posted my github and dockerhub 

If there is something am doing wrong.

**Comment by thaJeztah** [comment] 2016-07-13 15:26
Your Apache/PHP example doesn't work, because the image expects `index.php` to be there, which is not the case if you bind-mount an empty directory. The mysql image has an entrypoint script that checks if the mysql-data directory is present, and if not, creates it, and initializes the database; https://github.com/docker-library/mysql/blob/f7a67d7634a68d319988ad6f99729bfeaa84ceb2/5.7/docker-entrypoint.sh#L36-L129

If that script wouldn't be there, and an empty directory is bind-mounted, the mysql server would fail

**Comment by babatundebusari** [comment] 2016-07-13 15:33
@thaJeztah 

Ok got it, seeing that docker doesn't do that by default and comes from script; thanks for pointing that out

Now if i do put the files there so container can read from the bind-mount on host, if app needs to write files to that mount point, will the container be able to write files?

My container wasn't able to write files but it could read files on new docker runs

**Comment by thaJeztah** [comment] 2016-07-13 15:41
@babatundebusari basically, the container should be able to read and write to the bind-mounted directory, as if it's a directory in the container. Take into account that (e.g.) SELinux or AppArmor can deny access in some cases, and also that user that runs the process in the container (uid/gid) must have write permissions

**Comment by babatundebusari** [comment] 2016-07-13 15:47
@thaJeztah 

`also that user that runs the process in the container (uid/gid) must have write permissions`

can you please elaborate more on this? SO i have to create user on container on host or something?

**Comment by thaJeztah** [comment] 2016-07-13 15:50
by default, the container user is `root`, so should not be a problem, but you can run a container as a different user (e.g. `docker run -u 123:456`) in that case, user `123` must be given permissions on the files on your host

**Comment by babatundebusari** [comment] 2016-07-13 16:05
In my dockerfile i did not user another user, so am guessing that part of uid/gid does not apply to me?

**Comment by chrepl** [comment] 2016-07-13 16:20
@babatundebusari

The problem what you are trying and I hope I don't misunderstood you is basically, the container only be able to read and write with the root user or the same user/group of your owner of the hosted file.
What you are trying is, with Apache/PHP they are basically run under uid=gid=33 (alias http or www-data) to write/read file into a directory or file they are managed from other uid/gid.

In example, as you can see only root can read/write into the bind-mounted directory:
Here I'm trying to write a file to /app/test with the user "guest" instead "http" the same step that Apache/PHP trying with "http" or "www-data".
(I am using "su (user) -s (shell) -c (command) instead parameter -u for docker to better understand what I mean)

Example:
`$ docker run -it --rm -v /tmp/test:/app alpine su guest -s /bin/sh -c 'echo doesnt work cuz permission denied > /app/test'`
`sh: can't create /app/test: Permission denied`

`$ docker run -it --rm -v /tmp/test:/app alpine su root -s /bin/sh -c 'echo this will be work > /app/test'`

`$  ls -l /tmp/test `
`total 4`
`-rw-r--r-- 1 root root 34 13. Jul 17:54 test`

To fix this problem you have to change the owner of the host directory/file here the solution:
`$ docker run -it --rm -v /tmp/test:/app alpine su guest -s /bin/sh -c 'id'`
`uid=405(guest) gid=100(users) groups=100(users)`

`$ chown 405:100 /tmp/test # on host`

`$ docker run -it --rm -v /tmp/test:/app -u 405:100 alpine /bin/sh -c 'echo now it will be work > /app/test'`

`$ ls -l /tmp/test`
`total 4`
`-rw-r--r-- 1 405 users 20 13. Jul 18:09 test`

`$ docker run -it --rm -v /tmp/test:/app -u 405:100 alpine /bin/sh -c 'ls -ld /app'`
`drwxr-xr-x    2 guest    users           60 Jul 13 16:09 /app`

**Comment by babatundebusari** [comment] 2016-07-13 16:42
@chrepl 

Thanks for the detailed explanation; appreciate it 

Now here is what i have inside the running container

```
root@19c5a9d90938:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1  17960  2944 ?        Ss   16:35   0:00 /bin/bash /start.sh
root        10  0.0  0.8  60544 17016 ?        S    16:35   0:00 /usr/bin/python /usr/bin/supervisord -n -c /etc/supervisord.conf
root        13  0.0  1.4 444944 28808 ?        S    16:35   0:00 php-fpm: master process (/etc/php5/fpm/php-fpm.conf)
root        19  0.0  0.2  77696  4544 ?        Ss   16:35   0:00 /usr/sbin/apache2 -k start
www-data    20  0.0  0.1  77436  3232 ?        S    16:35   0:00 /usr/sbin/fcgi-pm -k start
www-data    21  0.0  0.3 432476  6604 ?        Sl   16:35   0:00 /usr/sbin/apache2 -k start
www-data    22  0.0  0.3 432452  6540 ?        Sl   16:35   0:00 /usr/sbin/apache2 -k start
www-data    77  0.0  0.4 444944  8908 ?        S    16:35   0:00 php-fpm: pool www
www-data    78  0.0  0.4 444944  8908 ?        S    16:35   0:00 php-fpm: pool www
www-data    79  0.0  0.4 444944  8908 ?        S    16:35   0:00 php-fpm: pool www
root        92  0.6  0.1  18140  3160 ?        Ss   16:37   0:00 bash
root       106  0.0  0.1  15568  2096 ?        R+   16:37   0:00 ps aux
```

```
root@19c5a9d90938:/# ls -lha /var/www/
total 8.5K
drwxr-xr-x  6 root root 4.0K Jul 13 15:02 .
drwxr-xr-x 25 root root 4.0K Jul 13 16:35 ..
drwxr-xr-x  2 root root   68 Jul 13 16:35 html
root@19c5a9d90938:/# ls -lha /var/www/html/
total 4.5K
drwxr-xr-x 2 root root   68 Jul 13 16:35 .
drwxr-xr-x 6 root root 4.0K Jul 13 15:02 ..
root@19c5a9d90938:/# ls -ld /var/www/html
drwxr-xr-x 2 root root 68 Jul 13 16:35 /var/www/html
```

and on my host the mounted volume /tmp/fpm1.com

```
babatunde:~ babatunde.busari$ ls -ld /tmp/fpm1.com
drwxr-xr-x  2 babatunde.busari  wheel  68 Jul 13 12:35 /tmp/fpm1.com
```

So i need to create user and group with same uid/gid on container on my host to make this work?

**Comment by chrepl** [comment] 2016-07-13 17:05
@babatundebusari 

This information are pretty well, next I need a little bit more information about your mounted volume can you run this command on your host machine:
`$ docker inspect -f '{{json .Mounts}}' containername | python -m json.tool`

**Comment by babatundebusari** [comment] 2016-07-13 17:20
@chrepl 

```
babatunde:~ babatunde.busari$ docker inspect -f '{{json .Mounts}}' apache-php-fpm1.com | python -m json.tool
[
    {
        "Destination": "/var/www/html",
        "Mode": "",
        "Propagation": "rprivate",
        "RW": true,
        "Source": "/tmp/fpm1.com"
    }
]
```

**Comment by chrepl** [comment] 2016-07-13 17:56
Ok well, you can see above the owner and group of your directory "html" is root and others has only read/execute and php-fpm is running under www-data and has also not any chance to write into them.
```
root@19c5a9d90938:/# ls -lha /var/www/
total 8.5K
drwxr-xr-x  6 root root 4.0K Jul 13 15:02 .
drwxr-xr-x 25 root root 4.0K Jul 13 16:35 ..
drwxr-x**r-x**  2 **root root**   68 Jul 13 16:35 html
```

To fix them you have 2 options:
1. You can change the current owner and group of your directory "/tmp/fpm1.com" to 33:33 (www-data:www-data) (http:http) on your **host machine** (You don't need to create the user on your host machine, basically it has a user with uid 33 it often call http or www-data, but you can change owner also without to create a user or group in example this will be also working "chown 77:77 /path/to/your/file" its important to use the id without a name if the user or groupname doesnt exists)
`babatunde:~ babatunde.busari$ chown 33:33 /tmp/fpm1.com`
- or -
`babatunde:~ babatunde.busari$ chown www-data:www-data /tmp/fpm1.com`
2. Is the same step like 1. but you change it into your container
`root@19c5a9d90938:/# chown www-data:www-data /var/www/html`

**Comment by chrepl** [comment] 2016-07-13 20:03
Also you are using docker client on mac and your docker host daemon runs on ubuntu or have you installed docker-toolbox and your docker host is running on boot2docker? This explains a lot.

**Comment by babatundebusari** [comment] 2016-07-13 20:06
@chrepl 

I was only running on my Mac for convenience and remember this is docker and should run any where ;)
By the way it is the `latest` Docker for Mac which does NOT use virtualbox
https://docs.docker.com/docker-for-mac/docker-toolbox/


BUT i will run all on ubuntu box now to removed all concerns.
Give me a sec

**Comment by babatundebusari** [comment] 2016-07-13 21:39
actually upon further tests, looks like it does write data even without need to create uid/gid
wasn't working before for whatever reason but it works now

thanks @chrepl @vdemeester @thaJeztah

**Comment by crossz** [comment] 2016-09-06 05:41
@babatundebusari As I tested, image based FROM alpine, will have the issues you got. However, those ones FROM ubuntu/centos, if the uid/gid are same, will have no the issues as you stated here.

Give this a try and let me know your results.

**Comment by karthickar** [comment] 2017-03-16 14:48
It was due to selinux in my case. So, disable SElinux using setenforce 0 and then copy the file you want.

**Comment by ketansoni79** [comment] 2017-03-17 06:56
@babatundebusari I am facing the same problem with my docker. How did you reslove it ?

**Comment by karthickar** [comment] 2017-03-17 10:40
If it is a CentOS box, try disabling selinux or run docker with sudo
privilege.

**Comment by SoberChina** [comment] 2018-02-02 05:10
This privileged: true parameter is very important.

**Comment by antass** [comment] 2018-08-15 14:15
Just in case someone else runs into a similar problem, I was able to solve it by providing a full path to the output file:

`docker run -v /path/on/host:/path/in/container -it IMAGE some_function /path/in/container/output.file`

The output file was lost when I used:

`docker run -v /path/on/host:/path/in/container -it IMAGE some_function output.file`

**Comment by tashrifbillah** [comment] 2020-07-14 20:40
> It was due to selinux in my case. So, disable SElinux using setenforce 0 and then copy the file you want.

@karthickar , how?

**Comment by tashrifbillah** [comment] 2020-07-14 20:56
Okay, for me the problem was-- I forgot `-v source:/path/to/docker/dest` creates `/path/to/docker/dest` in the docker `root/volumes` directory, the latter can be found by `docker info`. Forgetting that, I was looking for docker written files inside `PWD/source` which cannot be there at all.

As @antass noted, the solution would be to use an absolute path on the left of `:` with `-v`.

**Comment by alexgoryushkin** [comment] 2021-11-09 07:15
After adding the volume to docker-compose.yml, I did `docker-compose restart` and the new volume did not appear, but `docker-compose down` and then `docker-compose up` fixed that for me.
