### ISSUE TITLE
Docker build command not looking for local image

### ISSUE THREAD

**Issue by vandamon** [docker/docker#18909] opened 2015-12-25 09:11 UTC
I just upgraded to Docker 1.9.1 and now when I try to build an image using an image already created on local, Docker still tries to pull it from docker.io. It does not even prints out the usual message: unable to locate the image locally.

Is this intentional with this release? Or is something broken here?

#### Here is my Docker info:

* OS: ``` Windows 10```
* Docker version: 
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```
* Docker info: 
```
Containers: 5
Images: 67
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 77
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: SFRW:64QH:3A2A:USLG:GAH4:TYPN:DNQL:X7FX:6EJT:YK5M:CIIC:34QE
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 19
 System Time: 2015-12-25T08:58:44.088289644Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```
* uname -r: ```4.1.13-boot2docker```

**Comment by thaJeztah** [comment] 2015-12-25 11:38
Hm, I'm not able to reproduce;

```
root@testbox:~/18909-repro# docker build -t 18909-repro .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox:latest
 ---> e72ac664f4f0
Successfully built e72ac664f4f0
```

Would you be able to;

- check / provide the daemon logs from when that happened? Perhaps they show the reason it's pulling.
- provide the steps to reproduce?
- do you have content trust enabled? (See https://github.com/docker/docker/pull/16609)

**Comment by vandamon** [comment] 2015-12-26 07:58
Hi @thaJeztah,

No I don't have content trust enabled. I suppose it was added to version 1.8. I did not had it enabled then, nor I have it after upgrade.

I tried a few other things. I tried using the image ID, instead of name and tag. And I tried upgrading the default docker-machine, although I seem to already have the latest one.
 
Here are the details you asked for:

* Steps to reproduce are as follows:
```
- Setup Docker with the Windows installer - Successful
- Create a new image Ubuntu image with some basic packages installed from the Ubuntu image pulled from Docker Hub - Successful
- Then try to create another image based on the custom Ubuntu image created and available on local - Failing
```
* Daemon logs: attached

**Comment by itsdpk** [comment] 2015-12-31 11:51
may be you can try with docker run <image name>:<tag> else it defaults to <image name>:latest and hence tries to download from hub

**Comment by vandamon** [comment] 2016-01-01 10:36
I have been able to get Docker working again like normal, by completely uninstalling and reinstalling. Not exactly sure, but it seems this problem arose because I loaded the base image created using a previous version of Docker.

**Comment by thaJeztah** [comment] 2016-01-01 23:42
Thanks @vandamon, good to hear you resolved your issue. I'll close the issue here, but feel free to comment if you run into this again :+1:

**Closed by thaJeztah** 2016-01-01 23:42 UTC
