### ISSUE TITLE
IpamDriver.RequestPool is called in swam mode when start container

### ISSUE THREAD

**Issue by LipingMao** [docker/docker#32604] opened 2017-04-13 17:44 UTC
**Description**
I created a network with kuryr remote driver pluginv2 in swarm mode, when I start container in that network, IpamDriver.RequestPool is called in kuryr.
When I use non-swarm mode, this API only be called when I create network, it will not be called when start container. Is this action by design or bug in swarm mode?

**Steps to reproduce the issue:**
1. Enable kuryr pluginv2.
2. Create network.
```
docker network create --attachable --driver=limao/kuryr-libnetwork-v2plugin:latest --ipam-driver=limao/kuryr-libnetwork-v2plugin:latest --subnet 10.225.17.0/24  --gateway 10.225.17.1 --ip-range 10.225.17.0/24  -o neutron.net.uuid=55aec833-7838-482f-be9e-b205e5c6f2c4  limao
```
3. Start container in that network.
```
docker run --net=limao -itd busybox
```

**Describe the results you received:**
Both IpamDriver.RequestAddress and IpamDriver.RequestPool API is called when I run Step 3 .
Here is the log:
```
Apr 13 13:00:27 localhost dockerd: time="2017-04-13T13:00:27-04:00" level=info msg="[pid: 13|app: 0|req: 11/20] 0.0.0.0 () {26 vars in 364 bytes} [Thu Apr 13 17:00:27 2017] POST /IpamDriver.RequestAddress => generated 36 bytes in 726 msecs (HTTP/1.1 200) 2 headers in 71 bytes (2 switches on core 0)" plugin=fc90ae941c5a06e24ed58a92a83e55504379acf65f3fc62eaf33a2f6abe64974
Apr 13 13:00:28 localhost dockerd: time="2017-04-13T13:00:28-04:00" level=info msg="[pid: 13|app: 0|req: 12/21] 0.0.0.0 () {26 vars in 359 bytes} [Thu Apr 13 17:00:28 2017] POST /IpamDriver.RequestPool => generated 102 bytes in 74 msecs (HTTP/1.1 500) 2 headers in 128 bytes (3 switches on core 0)" plugin=fc90ae941c5a06e24ed58a92a83e55504379acf65f3fc62eaf33a2f6abe64974
```

**Describe the results you expected:**
I expected only IpamDriver.RequestAddress will be called when I start container.
IpamDriver.RequestPool will not be called.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
# docker version
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 21:13:52 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 21:13:52 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
# docker info
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 2
Server Version: 17.05.0-ce-rc1
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host limao/kuryr-libnetwork-v2plugin:latest macvlan null overlay
Swarm: active
 NodeID: uw603zd9v37ps9p4cmlib75cf
 Is Manager: true
 ClusterID: v3aj79fzoaz8i7e04ustmsgrg
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.225.17.184
 Manager Addresses:
  10.225.17.184:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.797GiB
Name: limao-rhel7-1.localdomain
ID: GE65:LDZT:RTFW:IYIH:AKKV:MYLT:HABO:V3LD:FOEM:M4PX:VKUJ:MQ57
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: limao
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM on Openstack

**Comment by aboch** [comment] 2017-04-13 19:40
Yes that is the expected behavior. Same thing happens for the default IPAM driver.
Swarm network are lazily created on the node once the first task/container is started there.

At swarm network creation, the pool allocation, from the IPAM driver's default _global_ address space will be done by the swarm allocator.
When the network will be created on the node, the pool allocation will be requested on the node from the IPAM driver's default _local_ address space.

**Comment by aboch** [comment] 2017-04-13 19:42
I am closing as this is by design.

But feel free to continue the discussion here.

**Closed by aboch** 2017-04-13 19:42 UTC
Labels: area/networking, version/17.05
