### ISSUE TITLE
Unable to expose TCP using DOCKER_OPTS

### ISSUE THREAD

**Issue by smalot** [docker/docker#19690] opened 2016-01-25 23:30 UTC
I can't perform to expose "tcp://127.0.0.1:4243" using "DOCKER_OPTS" in "/etc/default/docker".

Result for `docker version`
````sh
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64
````

Result for `docker info`
````sh
Containers: 6
Images: 99
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 111
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 8
Total Memory: 15.68 GiB
Name: docker3
ID: GGYW:KVBS:ELGL:PLTG:JDSX:E6NL:HUBK:6LSU:4REL:QIIQ:5DCU:WNDQ
WARNING: No memory limit support
WARNING: No swap limit support
````

Here is the content of "/etc/default/docker" file:

````
# Docker Upstart and SysVinit configuration file

# Customize location of Docker binary (especially for development testing).
DOCKER="/usr/bin/docker"

# Use DOCKER_OPTS to modify the daemon startup options.
#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"
DOCKER_OPTS="${DOCKER_OPTS} -D -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock"

# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export TMPDIR="/mnt/bigdrive/docker-tmp"
````

I tried to do `service docker restart`, I tried too to reboot the server, but nothing happend.
A `netstat -tulnp` didn't see any change.

Did someone else encountered such issue ? Quite strange !

Many thanks,

**Comment by calavera** [comment] 2016-01-26 00:43
Can you check what's in the log right after starting the daemon? there should be two lines like this:

```
INFO[0000] API listen on /tmp/docker.sock
INFO[0000] API listen on 127.0.0.1:2345
```

Are you sure your init system is reading that file?

**Comment by HackToday** [comment] 2016-01-26 01:36
hi, I think if you used systemctl related, you could check this
https://docs.docker.com/engine/articles/systemd/

**Comment by HackToday** [comment] 2016-01-26 01:37
aslo try find what your docker daemon really called about, it not necessary that configure file picked

**Comment by thaJeztah** [comment] 2016-01-26 02:19
Yes, Debian Jessie uses systemd, so the `/etc/default/docker` file is not used (see the comment at the top of that file; "Docker Upstart and SysVinit configuration file")

To configure docker on a system using systemd, you should use drop-in files; refer to this section in the documentation https://docs.docker.com/engine/articles/systemd/#custom-docker-daemon-options

I'm going to close this issue, because this is not a bug, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-01-26 02:19 UTC
