### ISSUE TITLE
Can't Ignore a directory for COPY

### ISSUE THREAD

**Issue by KaidenP** [docker/docker#29259] opened 2016-12-08 21:34 UTC
I can't seem to ignore an entire directory with .dockerignore, given the following

Dockerfile:
```
FROM node:latest
MAINTAINER Kaiden Prince <REDACTED>
ADD . /usr/src/app
CMD ["ls", "-lah", "./node_modules/"]
```

.dockerignore
```
node_modules/*
node_modules
node_modules/**/*
```

Output after build and run
```
./node_modules/:
total 16K
drwxr-xr-x 4 root root 4.0K Dec  8 21:33 .
drwxr-xr-x 6 root root 4.0K Dec  8 21:33 ..
drwxr-xr-x 2 root root 4.0K Dec  8 21:33 debug
drwxr-xr-x 2 root root 4.0K Dec  8 21:33 ms
```

**Comment by thaJeztah** [comment] 2016-12-09 00:30
I think there's an error in your example Dockerfile, because it tries to show the content of `/node_modules/` not `/usr/src/app/node_modules/`;

```
ls: cannot access ./node_modules/: No such file or directory
```

However, I am not able to reproduce this, using the following steps (I'm using a simplified `.dockerignore`, because you should only have to exclude `node_module`);

```
mkdir repro-29259 && cd repro-29259

mkdir -p node_modules/debug node_modules/ms
touch node_modules/file1 node_modules/debug/file2 node_modules/ms/file3

cat > Dockerfile <<EOF
FROM node:latest
ADD . /usr/src/app
CMD ["ls", "-lah", "/usr/src/app/node_modules/"]
EOF

cat > .dockerignore <<EOF
.dockerignore
Dockerfile
node_modules
EOF

docker build --no-cache -t foo .

docker run -it --rm foo
ls: cannot access /usr/src/app/node_modules/: No such file or directory
```

- Can you add the output of `docker version` and `docker info`?
- Could it be you're using a different base-image that has `/node_modules/` at the root? (`/`)
- Are you running the containers with additional flags/options? (e.g. `-v` to bind-mount local sources)?

**Comment by KaidenP** [comment] 2016-12-09 01:19
Oh pardon me, I forgot My `WORKDIR /usr/src/app/`

**Comment by KaidenP** [comment] 2016-12-09 01:23
```
Containers: 10
 Running: 1
 Paused: 0
 Stopped: 9
Images: 123
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 133
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.69 GiB
Name: Kaiden-PC
ID: LQYU:KDXN:FTNW:RYUJ:W3NM:NHJN:JCJY:WNBZ:ZCP3:SP6G:UJXG:PS4P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: kaidenp
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```
It cannot be the base image, because removing the `COPY` causes the cwd to be empty.

**Comment by KaidenP** [comment] 2016-12-09 01:33
Looking at your example it must be something I'm doing, because i was able to reproduce exactly what you did correctly.

**Comment by KaidenP** [comment] 2016-12-09 01:40
Further testing indicates that somehow my IDE (WebStorm) is screwing things up, and somehow is ignoring the dockerignore. I don't know where to go from here

**Comment by thaJeztah** [comment] 2016-12-09 09:12
If you're using the WebStorm Docker integration, I think WebStorm is doing more than just a `docker run`, but it's been a while since I last tried it. If you're only able to reproduce the issue with WebStorm, reporting it in their issue tracker would be a good start; https://youtrack.jetbrains.com/issues/WEB

Based on the above, I don't think this is a bug in docker, so I'll close this issue, but feel free to continue the discussion

**Closed by thaJeztah** 2016-12-09 09:12 UTC
Labels: area/builder, status/more-info-needed
