### ISSUE TITLE
Have "years ago" as a integer in output of docker ps

### ISSUE THREAD

**Issue by tomfotherby** [docker/docker#27726] opened 2016-10-25 09:51 UTC
**Description**

This is a v.v.v.v.v Minor issue but I've been running a _memcache_ container for a while on one of our hosts:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED              STATUS              PORTS                      NAMES
acbf82de3747        5a3c40e344ce        "/bin/sh -c '/usr/bi   2.007922 years ago   Up 2.004308 years   0.0.0.0:11211->11211/tcp   memcache
```

I think the "years ago" could be formatted as a integer or maybe 1 decimal place. 6 decimal places seems excessive :exclamation:

**Steps to reproduce the issue:**
1. Run a container for a couple of years. (:stuck_out_tongue_winking_eye: )
2. Do `docker ps`

**Describe the results you received:**

CREATED and STATUS shows time as "2.007922 years ago".

**Describe the results you expected:**

I think simply `2 years ago` would make a nice UX for `docker ps`.

**Output of `docker version`:**

```
Docker version 1.3.0, build c78088f
```

**Output of `docker info`:**

```
Containers: 1
Images: 44
Storage Driver: devicemapper
 Pool Name: docker-202:1-271321-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1.103 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 2.699 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.5 LTS
Username: xxxx
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS - c3.2xlarge.

(If anyone responds with "_Please re-test with a later version of docker_", I will laugh and get back to them in 2 years, ho ho ho.)

**Comment by justincormack** [comment] 2016-10-25 11:40
Rounding to whole years seems reasonable. Do you want to do a PR?

**Comment by tomfotherby** [comment] 2016-10-25 15:20
@justincormack
> Do you want to do a PR?

Sorry, My Go fu isn't up to it. I found where the code for `docker ps` is ([cli/command/container/list.go](https://github.com/docker/docker/blob/master/cli/command/container/list.go#L110)) but not where the `CREATED` table column is formatted. The `HumanDuration` function ([vendor/src/github.com/docker/go-units/duration.go](https://github.com/docker/docker/blob/master/vendor/src/github.com/docker/go-units/duration.go#L34)) already looks like years would output as a integer.

**Comment by justincormack** [comment] 2016-10-25 18:27
Does seem somewhat precise! Do you want to make a PR? I think whole years
is OK.

**Comment by thaJeztah** [comment] 2016-10-26 06:49
Looks like this was an issue in docker 1.3.0, but fixed since. Docker 1.3.0 used a float; https://github.com/docker/docker/blob/v1.3.0/pkg/units/duration.go#L30

This is a duplicate of https://github.com/docker/docker/issues/12852, and was fixed in https://github.com/docker/docker/pull/12888, so I'm closing this. Perhaps time to upgrade :smile:

**Closed by thaJeztah** 2016-10-26 06:49 UTC
