### ISSUE TITLE
[1.10] cgroup panic

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19329] opened 2016-01-14 10:17 UTC
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xb1a82f]

goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer/cgroups/fs.(*Manager).Freeze(0xc820c418e0, 0x16cdfd8, 0x6, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go:205 +0x2bf
github.com/opencontainers/runc/libcontainer.killCgroupProcesses(0x7f5fe456fc30, 0xc820c418e0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/init_linux.go:309 +0x8c
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Destroy(0xc820d88ea0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/opencontainers/runc/libcontainer/container_linux.go:331 +0x238
github.com/docker/docker/daemon/execdriver/native.(*Driver).Terminate(0xc820717840, 0xc8207e5c00, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/execdriver/native/driver.go:346 +0x2dd
github.com/docker/docker/daemon.(*Daemon).Register(0xc82000c840, 0xc820bfcfc0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:276 +0x4df
github.com/docker/docker/daemon.(*Daemon).restore(0xc82000c840, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:343 +0x11c5
github.com/docker/docker/daemon.NewDaemon(0xc820134c80, 0xc820028118, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:835 +0x335f
main.(*DaemonCli).CmdDaemon(0xc820648a30, 0xc82000a070, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/docker/docker/docker/daemon.go:227 +0x136a
reflect.callMethod(0xc820646d80, 0xc820d43c68)
	/usr/local/go/src/reflect/value.go:628 +0x1fc
reflect.methodValueCall(0xc82000a070, 0x3, 0x3, 0x1, 0xc820646d80, 0x0, 0x0, 0xc820646d80, 0x0, 0x473375, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc820646cf0, 0xc82000a060, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:89 +0x383
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:63 +0x43c
```

I had just upgraded a 1.9.1 environment to 1.10 and this panic was thrown on the first daemon start.  This is running off of 63525a6dc5f7be370736ec2905d40a8c8fdf1162

**Comment by cpuguy83** [comment] 2016-01-14 15:13
ping @LK4D4 @crosbymichael issue with libcontainer cgroup manager.

**Comment by mlaventure** [comment] 2016-01-14 19:12
root cause: libcontainer moved the cgroups settings inside an inner Resources type opencontainers/runc@55a49f2110f04a65f4196c0e32ed390e45d486ea . Hence when loading the old state.json the Resources pointer was set to nil as it isn't present in the previous format.

**Comment by hqhq** [comment] 2016-01-15 08:12
@ibuildthecloud Can you check if https://github.com/opencontainers/runc/pull/476 fixes the panic?

**Comment by thaJeztah** [comment] 2016-01-19 23:12
@hqhq https://github.com/opencontainers/runc/pull/476 is merged, so I think we need a vendor update now. Not sure if that's currently possible, pending https://github.com/opencontainers/runc/pull/470 ?

**Comment by thaJeztah** [comment] 2016-01-19 23:16
Just discussed with @crosbymichael and if might be cherry-picked into the release branch in RunC

**Comment by thaJeztah** [comment] 2016-01-19 23:43
Reopening, because GitHub was a bit trigger-happy

**Comment by jfrazelle** [comment] 2016-01-20 00:04
that was weird it closed it from my fork

**Comment by thaJeztah** [comment] 2016-01-20 00:11
Yah, that works because you have write access to both. Surprised me actually that that **didn't** happen from the RunC repo, possibly because it's a different organization

**Comment by thaJeztah** [comment] 2016-01-20 00:12
That doesn't make sense, because you're a different "org" as well, haha

**Closed** 2016-01-20 19:31 UTC
Labels: kind/bug, priority/P1
