### ISSUE TITLE
[Feature] Include a KV-store/metadata Service for Containers

### ISSUE THREAD

**Issue by daviddyball** [docker/docker#32260] opened 2017-03-31 11:11 UTC
I did a browse of the issues and couldn't find anything particular to this. Apologies if it has been answered before though.

I may be misunderstanding, but I believe Swarm mode currently uses a KV-store to share important state information amongst workers/masters and generally keep the cluster in a good state. I'm wondering if it's feasible to expose a "general" KV-store to all swarm nodes that could be used for storing configuration information and queried by applications running in containers on the cluster, sort of like Amazons EC2 metadata service, or a standalone implementation of etcd/consul.

Understandably this is kind of out-of-scope for docker, as you could run your own KV-store system in the cluster... but I guess it'd just be nice to have it built in to docker as a standard (but optional) feature.

Feasible? Out of scope?

Cheers.

**Comment by thaJeztah** [comment] 2017-03-31 11:21
This is a duplicate of https://github.com/docker/docker/issues/27977, and to some extend https://github.com/docker/docker/issues/25274 and https://github.com/docker/docker/issues/24664

At this moment, no, that's not supported, and not a primary goal of the swarm k/v store. There has been some research into storing other data (e.g., secrets have find their way in, possibly being extended to "configuration" at some point), but using it as a "generic" k/v store is currently out of scope.

I'll close this issue for the above, but feel free to continue the discussion

**Closed by thaJeztah** 2017-03-31 11:21 UTC
Labels: area/swarm, kind/feature

**Comment by daviddyball** [comment] 2017-03-31 11:36
Thanks @thaJeztah, reading through #27977 it makes sense not to destabilise the core mechanisms controlling swarm. Thanks!

**Comment by thaJeztah** [comment] 2017-03-31 12:10
You're welcome! It's certainly something that has been discussed, and I'm not excluding it being implemented in future, but at this point not :smile:
