### ISSUE TITLE
Feature Request: Dockerfile syntax -test

### ISSUE THREAD

**Issue by HariSekhon** [docker/docker#19593] opened 2016-01-22 20:43 UTC
Feature Request for ```docker build``` to add a switch to validate a Dockerfile's syntax is correct.

Since ```docker build``` has to parse the Dockerfile anyway, exposing a no op syntax test switch shouldn't be a big deal?

**Comment by bamarni** [comment] 2016-04-27 09:17
Interesting, should it even be the default (failing early in case the Dockerfile has syntax errors)?

**Comment by thaJeztah** [comment] 2016-04-28 14:49
duplicate of https://github.com/docker/docker/issues/19644?

**Comment by bamarni** [comment] 2016-04-28 15:24
I think so 👍  Just moved my comment there.

**Comment by thaJeztah** [comment] 2016-04-28 15:29
Thanks! closing this one

**Closed by thaJeztah** 2016-04-28 15:29 UTC
Labels: area/builder, kind/feature
