### ISSUE TITLE
Proposal: Support for user namespaces

### ISSUE THREAD

**Issue by dineshs-altiscale** [docker/docker#7906] opened 2014-09-05 17:24 UTC
The details of user namespace support have been discussed quite a bit under the following docker and libcontainer PRs.  However, there was never really a proposal to provide a space to discuss the big picture.  This issue is created to cover that purpose.

https://github.com/docker/docker/pull/4572
https://github.com/docker/libcontainer/pull/23
https://github.com/docker/libcontainer/pull/53

To summarize, docker support for user namespaces requires the backend exec driver to provide the necessary system interface.  Currently LXC supports it but libcontainer support is gated by Go (https://code.google.com/p/go/issues/detail?id=8447).

One of the questions to answer is whether the high level support in Docker (regardless of the backend) can be shepherded along based on LXC, while Go issues for libcontainer are being worked out in parallel.  If so, we can discuss approaches currently proposed in https://github.com/docker/docker/pull/4572 along with other potential alternatives.

**Comment by gdm85** [comment] 2015-02-01 23:55
Has the potential development of this feature come to a halt?

It would have been a great addition, from security/isolation perspective.

**Comment by LK4D4** [comment] 2015-02-02 01:14
@gdm85 There will be support in native driver in 1.6.

**Comment by jaybuff** [comment] 2015-02-02 16:54
@LK4D4 Where can we track the progress of that development work if not in this issue?

**Comment by fivetonsflax** [comment] 2015-02-16 17:39
What @jaybuff said.

**Comment by sammcj** [comment] 2015-03-04 09:56
Very excited about this - is it confirmed for docker 1.6?

**Comment by estesp** [comment] 2015-03-09 16:51
See PR #11253 for the user-facing proposal.  I can't confirm that all components will make it for 1.6, but work is ongoing.  The most important is to have the libcontainer version that has the support in the Docker vendor tree, and that PR (to update libcontainer in `vendor/` and use the new libcontainer API) is going through review at the moment.

**Comment by tphyahoo** [comment] 2015-03-17 22:58
Could this have label project/security added?

**Comment by pdonorio** [comment] 2015-04-13 08:17
Is this already available in the latest 1.6 rc?

**Comment by duglin** [comment] 2015-04-13 12:34
Not yet - plan is for v1.7

**Comment by afolarin** [comment] 2015-06-10 22:56
Do we know if this is going to make 1.7. I can't see it in the listed features https://github.com/docker/libnetwork/wiki/Docker-1.7-Project-Page

**Comment by duglin** [comment] 2015-06-10 23:02
Due to some issues that were exposed recently this has been push out to after v1.7.

**Comment by afolarin** [comment] 2015-06-10 23:09
@duglin i'd like to be able to track this progres on this freature. userns are quite important to my planning

**Comment by estesp** [comment] 2015-06-10 23:12
@afolarin we'll probably continue to use the open PR to track progress: #12648

At this point we have some work to resolve the order of namespace creation and some recently realized restrictions in the Linux kernel namespaces implementation.  With the inclusion of libnetwork in 1.7, this "surprise" was exposed and we had to keep user namespaces out of 1.7 until we resolve this.

**Comment by LK4D4** [comment] 2015-06-11 02:50
@estesp @afolarin I think we can do this pretty fast if we will have time.

**Comment by robertoandrade** [comment] 2015-08-28 12:35
Any projections as to when this will be available?

**Comment by cpuguy83** [comment] 2015-08-28 14:30
I'm going to close this one since most of the discussion is happening @ #15187
The plan is to have this in docker 1.9.
The PR which introduces this is here: #12648

**Closed by cpuguy83** 2015-08-28 14:30 UTC
Labels: kind/feature, kind/proposal
