### ISSUE TITLE
Unprotected pull from Docker Registry V2

### ISSUE THREAD

**Issue by mv012004** [docker/docker#17317] opened 2015-10-23 20:19 UTC
I have V1 registry with nginx reverse proxy. My configuration allows docker pull without login and for any push login is needed. This all is working great till I started migrating to V2. With migration to V2 version of registry, i found below issues. Anyone else facing similar issues with migration?

BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

Docker Registry Version - 2.1.1
NGINX Version - 1.8.0
docker version:
```
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-115.el7.x86_64
Go version (client): go1.4.2
Git commit (client): 446ad9b/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-115.el7.x86_64
Go version (server): go1.4.2
Git commit (server): 446ad9b/1.7.1
OS/Arch (server): linux/amd64
```
docker info:
```
Containers: 11
Images: 38
Storage Driver: devicemapper
 Pool Name: docker-202:18-67109019-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.111 GB
 Data Space Total: 107.4 GB
 Data Space Available: 9.423 GB
 Metadata Space Used: 3.162 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
CPUs: 2
Total Memory: 6.897 GiB
```
uname -a:
```
Linux <IP> 3.10.0-229.11.1.el7.x86_64 #1 SMP Wed Jul 22 12:06:11 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Provide additional environment details (AWS, VirtualBox, physical, etc.): Any Environment with docker client

List the steps to reproduce the issue:
1.Run Docker Registry V2 as per standard instructions.
2.Nginx in front of registry for authentication/authorization, using the below config file. Authentication config can be changed to htaccess instead of LDAP as per developers.

```
worker_processes  2;
error_log  /nginx01/error.log warn;
events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /nginx01/access.log main;
    sendfile        on;
    keepalive_timeout  65;

    upstream docker-registry-v2 {
        server <Docker Registry V2 Primary host:port>;
        server <Docker Registry V2 Backup host:port> backup;
    }
    ldap_server ldapserver {
        url "<LDAP URL>";
        binddn "<BINDDN>";
        binddn_passwd "<BINDDN_PASSWORD>";
        group_attribute member;
        group_attribute_is_dn on;
        satisfy any;
        require valid_user;
    }
    server {
        listen       <PORT>;
        proxy_set_header  Host              $http_host;   # required for docker client's sake
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Original-URI $request_uri;
        client_max_body_size 0; # disable any limits to avoid HTTP 413 for large image uploads
        # required to avoid HTTP 411: see Issue #1486 (https://github.com/dotcloud/docker/issues/1486)
        chunked_transfer_encoding on;

    location / {
          location /v2 {
                    add_header Docker-Distribution-Api-Version 'registry/2.0' always;
                        limit_except GET {
                                auth_ldap "Restricted Space";
                                auth_ldap_servers ldapserver;
                        }
                        proxy_pass http://docker-registry-v2;
                }
        }
        error_page  404              /errors/error.html;
    }
}
```
3. From the docker client try running following commands.
     i. docker pull registryhost:port/namespace/repository
     Result - Pull is a success.
     ii. docker login registryhost:registryport
     Result - Fails -> 
```
docker login abc:1234
Username: abcpqr
Password:
Email: abc@pqr.com
Error response from daemon: no successful auth challenge for https://abc:443 - errors: []
```
     iii. docker push registryhost:port/namespace/repository
     Result - Fails -> 
```
docker push abc:443/abc/pqr
The push refers to a repository [abc:443/abc/pqr] (len: 1)
8d9ee71c5ec9: Image already exists

Please login prior to push:
Username: abc
Password:
Email: abc@pqr.com
Error response from daemon: no successful auth challenge for https://abc:443 - errors: []
```

Describe the results you expected:
docker login and docker push should be successful. 

Provide additional info you think is important:
The above registry/nginx configuration works fine with the V1 registry.
For V1, if user does a docker push, the call for login is made with PUT/POST for /v1/users and as the same is protected the client gets 401 back and is prompted for login whereas for V2 the call is GET /v2/ which returns 200 as my config has unprotected pull and the docker client considers that it can start pushing manifests and the PUT fails with 401. If login/auth call is PUT/POST for docker-registry V2 I guess everything will work as expected.

My overall intention is to have unprotected pulls so that anyone can pull image run a container using the image from repository but any push/delete needs to be protected so that only authorized users are allowed for managing the images.

Hope this gives better understanding.

This is similar to the issue raised by @gauravbhandare in https://github.com/docker/distribution/issues/1028

This is more of a client issue than the registry issue.

This is a serious issue, with the docker client and this needs to be taken look at, i am not sure why there is no activity on this issue. Can some of the devs help look at this.

**Comment by mv012004** [comment] 2015-10-23 21:01
I have updated the initial description, i searched for issues and there were no similar issues i found which I can add this to, so raising a new one.

**Comment by gauravbhandare** [comment] 2015-10-23 21:06
Thanks @mv012004 for describing this issue in details. My problem is exactly same. I did some code debugging and the problem is the way V2 authentication mechanism is implemented on the client side.
All logic is based on the HTTP code 401 from the registry and the call is made with GET /v2/. We need a new end point in registry for login. Docker Registry V1 /v1/users POST method was explicitly used for exact this purpose. I can do the code changes for this new end point and the implementation but want to know if there is any possibility of that merging in registry and docker both. 

This issue may be faced by less folks as most work on either 100 secured or 100 unsecured registries but is a show stopper for cases like us where we are stuck with Registry V1 till the solution is accepted.

**Comment by gauravbhandare** [comment] 2015-10-29 13:15
I tried to do some configuration changes as mentioned in https://github.com/docker/distribution/issues/397 and got this working for docker 1.7.1 and below. For docker version 1.8.2 its still failing. Also tried the same with 1.9 rc but issue persists. Image exists in V2 registry with latest tag.

Nginx access logs when tried with docker 1.7.1 
```
[27/Oct/2015:21:40:48 -0400] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" "-"
[27/Oct/2015:21:40:48 -0400] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" "-"
[27/Oct/2015:21:40:48 -0400] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" "-"
[27/Oct/2015:21:40:49 -0400] "GET /v2/amit/jpetstore-demo2/manifests/latest HTTP/1.1" 200 57468 "-" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" "-"
```

Nginx access logs when tried with docker 1.8.3
```
[27/Oct/2015:21:29:09 -0400] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64" "-"
[27/Oct/2015:21:29:09 -0400] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64" "-"
[27/Oct/2015:21:29:10 -0400] "GET /v1/repositories/amit/jpetstore-demo2/images HTTP/1.1" 404 29 "-" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64" "-"
```

Anyone else facing the same issue after docker update?

**Comment by hjacobs** [comment] 2015-11-03 21:43
I have exactly the same problem with our own Docker Registry (Clojure microservice supporting v1 and v2 with S3 backend and OAuth, see https://github.com/zalando-stups/pierone). See https://github.com/zalando-stups/pierone/issues/57

Basically I want to allow public pulls (i.e. without authentication), but require authentication for pushes.

The Docker client handles the 401 response code not really well in all cases:

* Docker client first does GET /v2/
* It it returns status code 401 => the call is retried with basic auth (if WWW-Authenticate header is appropriately set)
* If it returns status code 200 => no authentication is performed and all following calls for push/pull (even if they return 401) will not be tried with credentials

Summary: Docker client only handles 401 for the "GET /v2/" call, but we don't know yet whether the next call will be a push (would require auth) or a pull (would not require auth).

I consider this a bug as the Docker client should handle "late" 401 response code (on attempted push) with a retry using credentials.

**Comment by hjacobs** [comment] 2015-11-03 21:56
Side note: I think it's quite sad that we now have a "spec" (https://docs.docker.com/registry/spec/api/), but it's pretty vague and authentication behavior is not well specified (neither is v1 fallback).
I mostly had to read Docker source code and use Wireshark to see what's going on :disappointed:

**Comment by megadeezl** [comment] 2015-11-08 23:23
I am trying to use token auth, but the client seems to stop after recieving the 401 with the header after ldap auth and first call with basic auth header:

015/11/08 23:13:58 [debug] 9#0: *11 http proxy header: "Date: Sun, 08 Nov 2015 23:13:58 GMT"
2015/11/08 23:13:58 [debug] 9#0: *11 http proxy header: "Content-Length: 87"
2015/11/08 23:13:58 [debug] 9#0: *11 http proxy header done
2015/11/08 23:13:58 [debug] 9#0: *11 HTTP/1.1 401 Unauthorized
Server: nginx/1.7.12
Date: Sun, 08 Nov 2015 23:13:58 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 87
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="http://*.*.*.*9000/authorize",service="Docker Registry"
Docker-Distribution-Api-Version: registry/2.0

no token is returned here so client responds back with:

Error response from daemon: no successful auth challenge for https://localhost:443/v2/ - errors: [basic auth attempt to https://localhost:443/v2/ realm "Restricted Space" failed with status: 401 Unauthorized]

**Comment by LK4D4** [comment] 2016-09-16 20:42
ping @aaronlehmann @stevvooe @dmcgowan

**Comment by dmcgowan** [comment] 2016-09-19 22:50
Closing this issue since it is already tracked here https://github.com/docker/distribution/issues/1028.

This is related to the registry client not supporting different HTTP authentication methods for read/write operations to the registry. Supporting different authentication methods is currently supported through token authentication.

**Closed by dmcgowan** 2016-09-19 22:50 UTC
Labels: area/distribution
