### ISSUE TITLE
ADD not the same as tar -xf

### ISSUE THREAD

**Issue by Jeansen** [docker/docker#22893] opened 2016-05-22 20:17 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```

Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 693
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-5375695-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 47.8 GB
 Data Space Total: 107.4 GB
 Data Space Available: 59.57 GB
 Metadata Space Used: 56.27 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.091 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.124 (2016-05-07)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-2-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.863 GiB
Name: debian8
ID: RSMS:2TI7:TEE4:N5YC:SSGG:7IBA:QY7S:OXUD:VPD3:H4T3:DOYT:PTUT
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit suppo
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS ist Debian stretch/sid

**Steps to reproduce the issue:**
1.Dockerfile:

```Dockerfile
FROM debian
RUN apt-get update && apt-get install -y \
openjdk-7-jdk \
xvfb \
cmake \
wget

RUN useradd -ms /bin/bash eclim
USER eclim
WORKDIR /home/eclim

#RUN wget -nv "http://ftp.halifax.rwth-aachen.de/eclipse//technology/epp/downloads/release/mars/1/eclipse-jee-mars-1-linux-gtk-x86_64.tar.gz"
ADD eclipse-jee-mars-1-linux-gtk-x86_64.tar.gz .
#RUN tar -xf eclipse-jee-mars-1-linux-gtk-x86_64.tar.gz

RUN DISPLAY=:1 ./eclipse/eclipse \
-consolelog \
-nosplash \
-debug \
-application org.eclipse.equinox.p2.director \
-repository http://download.eclipse.org/releases/mars/,\
https://dl-ssl.google.com/android/eclipse/,\
http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/,\
http://pydev.org/updates,\
http://download.scala-ide.org/sdk/lithium/e44/scala211/stable/site \
-installIU org.eclipse.cdt.feature.group,\
org.eclipse.dltk.core.feature.group,\
org.eclipse.dltk.ruby.feature.group,\
org.eclipse.jdt.feature.group,\
org.eclipse.php.feature.group,\
org.eclipse.wst.web_ui.feature.feature.group,\
com.android.ide.eclipse.adt.feature.feature.group,\
org.codehaus.groovy.eclipse.feature.feature.group,\
org.python.pydev.feature.feature.group,\
org.scala-ide.sdt.feature.feature.group

RUN wget -nv -O eclim_2.5.0.jar "http://downloads.sourceforge.net/project/eclim/eclim/2.5.0/eclim_2.5.0.jar?r=http%3A%2F%2Feclim.org%2Finstall.html&ts=1453820716&use_mirror=skylink"
RUN java -Dvim.files=/home/eclim/.vim -Declipse.home=/home/eclim/eclipse -jar eclim_2.5.0.jar install
```
2. docker build -t=eclim

**Describe the results you received:**
Last Step, Installation of eclim, fails with:
```
The following error occurred while executing this line:
jar:file:/home/eclim/eclim_2.5.0.jar!/installer.xml:231: Replace: source file /home/eclim/eclipse/plugins/org.eclim_2.5.0/bin/eclimd doesn't exist
```
**Describe the results you expected:**
Successfull build!

**Additional information you deem important (e.g. issue happens only occasionally):**
I already provided, what works. Changing ADD to COPY (or uncommenting the line with wget) and uncomenting the tar statement makes the whole thing work.

**Comment by thaJeztah** [comment] 2016-05-22 22:51
The problem here is that `ADD` and `COPY` always add files as "root", and don't follow the `USER`. Because of this, the installation fails, because the `RUN` instructions *are* executed as `USER eclim`.

To verify this, change the Dockerfile to this;

```Dockerfile
FROM debian
ARG APT_MIRROR=cdn-fastly.deb.debian.org
RUN sed -i s/httpredir.debian.org/$APT_MIRROR/g /etc/apt/sources.list
RUN apt-get update && apt-get install -y \
openjdk-7-jdk \
xvfb \
cmake \
wget

RUN useradd -ms /bin/bash eclim
#USER eclim
WORKDIR /home/eclim

#RUN wget -nv "http://ftp.halifax.rwth-aachen.de/eclipse//technology/epp/downloads/release/mars/1/eclipse-jee-mars-1-linux-gtk-x86_64.tar.gz"
ADD eclipse-jee-mars-1-linux-gtk-x86_64.tar.gz .
#RUN tar -xf eclipse-jee-mars-1-linux-gtk-x86_64.tar.gz

RUN DISPLAY=:1 ./eclipse/eclipse \
-consolelog \
-nosplash \
-debug \
-application org.eclipse.equinox.p2.director \
-repository http://download.eclipse.org/releases/mars/,\
https://dl-ssl.google.com/android/eclipse/,\
http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/,\
http://pydev.org/updates,\
http://download.scala-ide.org/sdk/lithium/e44/scala211/stable/site \
-installIU org.eclipse.cdt.feature.group,\
org.eclipse.dltk.core.feature.group,\
org.eclipse.dltk.ruby.feature.group,\
org.eclipse.jdt.feature.group,\
org.eclipse.php.feature.group,\
org.eclipse.wst.web_ui.feature.feature.group,\
com.android.ide.eclipse.adt.feature.feature.group,\
org.codehaus.groovy.eclipse.feature.feature.group,\
org.python.pydev.feature.feature.group,\
org.scala-ide.sdt.feature.feature.group

RUN wget -nv -O eclim_2.5.0.jar "http://downloads.sourceforge.net/project/eclim/eclim/2.5.0/eclim_2.5.0.jar?r=http%3A%2F%2Feclim.org%2Finstall.html&ts=1453820716&use_mirror=skylink"

# JUST FOR DEMO; chown the files, and -then- run the install as user "eclim"
RUN chown -R eclim /home/eclim
USER eclim
RUN java -Dvim.files=/home/eclim/.vim -Declipse.home=/home/eclim/eclipse -jar eclim_2.5.0.jar install
```

(This change is not really efficient, and just to demonstrate the issue at hand)

This is a known issue, but something we (so far) weren't able to change, because making `COPY` and `ADD` follow `USER` would break backward compatibility (see https://github.com/docker/docker/issues/6119 and https://github.com/docker/docker/issues/22749)

For now, the best approach would be to use a `RUN` + `wget` / `curl` to fetch the tar.gz and uncompress using `tar`.

I'm going to close this issue, because it's a duplicate of the issues I linked to, but feel free to comment after I closed.

**Closed by thaJeztah** 2016-05-22 22:51 UTC
Labels: version/1.11

**Comment by Jeansen** [comment] 2016-05-22 22:59
@thaJeztah I am sorry to have produced a duplicate. Thank you for the quick and detailed reply.

**Comment by thaJeztah** [comment] 2016-05-22 23:15
@Jeansen no need to apologize :) I wasn't sure either if it was the issue, so I had to do some testing myself to verify. And, yes, it's a bit of a PITA that it doesn't follow `USER`, and there's been a lot of discussion around that ("fixing" it versus breaking existing Dockerfiles)

**Comment by nikolyabb** [comment] 2016-10-12 08:26
You can use ADD somefile.tar.bz2 /somefolder
With this instruction ownership of files inside archive will pass through when it extracts. This is not good, but efficient way to solve that. And no need to get archive somewhere outside of context.
