### ISSUE TITLE
Docker 1.6.0 ubuntu package can not be authenticated

### ISSUE THREAD

**Issue by akafred** [docker/docker#12478] opened 2015-04-17 11:56 UTC
Same as issue #8605 (which was for Docker 1.3).
```
$ sudo apt-get install lxc-docker=1.6.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  aufs-tools cgroup-lite lxc-docker-1.6.0
The following NEW packages will be installed:
  aufs-tools cgroup-lite lxc-docker lxc-docker-1.6.0
0 upgraded, 4 newly installed, 0 to remove and 168 not upgraded.
Need to get 4,752 kB/4,849 kB of archives.
After this operation, 15.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
WARNING: The following packages cannot be authenticated!
  lxc-docker-1.6.0 lxc-docker
Install these packages without verification? [y/N]
```

**Comment by jfrazelle** [comment] 2015-04-17 12:00
curl -sSL https://get.docker.com | sh

Cannot reproduce

**Comment by akafred** [comment] 2015-04-17 12:07
Some details on my system:
```
$ cat /etc/apt/sources.list.d/docker.list
deb http://get.docker.io/ubuntu docker main

$ uname -a
Linux vm-ship 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```

**Comment by unclejack** [comment] 2015-04-17 12:17
This is a duplicate of #12461. Please look at that issue to see how to fix this problem.

If you run into this issue, please look at #12461 and don't comment here.

**Closed by unclejack** 2015-04-17 12:17 UTC
