### ISSUE TITLE
caused "not a directory"

### ISSUE THREAD

**Issue by bupy7** [docker/docker#27010] opened 2016-09-29 08:06 UTC
**Description**

I cannot mount the nginx config file:

**Steps to reproduce the issue:**
1. `$ docker run --rm -it -v $(pwd)/nginx/nginx.conf:/etc/nginx/conf.d/default.conf nginx:latest`

**Describe the results you received:**
```
docker: Error response from daemon: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/1d488c9f67c62b352ba91ca537bd72666b1b635d88e112a3ad4bf3cc63600a8a/etc/nginx/conf.d/default.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/1d488c9f67c62b352ba91ca537bd72666b1b635d88e112a3ad4bf3cc63600a8a" caused "not a directory".
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I checked that `/etc/nginx/conf.d/default.conf` exists on my host.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      darwin/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: CGKR:TU7N:QKJP:Q5JA:UWYX:KCKJ:KAMK:BWLV:EVMK:JQQZ:53PE:MNIJ
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2016-09-29T08:05:29.188232031Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS: OSX 10.9.5
Same problem for docker-compoe: https://github.com/docker/compose/issues/3978

**Comment by thaJeztah** [comment] 2016-09-29 11:14
This is most likely because you are using Docker Toolbox / Boot2docker, and are trying to bind-mount a directory _outside_ of the `/Users/` directory on your Mac.

Docker Toolbox uses VirtualBox Guest Additions to make the "Users" directory on the Mac with the VirtualBox VM in which the daemon runs.

Bind-mounting directories always works from the host that the _daemon_ runs on. In your case, that's the VirtualBox VM. When you specify a path to bind-mount into a container, the daemon checks if that path exists on the host, and if not, creates an empty directory at that path.

The daemon _assumes_ you want to bind-mount a directory here, as it has no way to know if you want to bind-mount a _file_ or a _directory_ based on just the name.

So what happens in your example;

You run;

    docker run --rm -it -v $(pwd)/nginx/nginx.conf:/etc/nginx/conf.d/default.conf nginx:latest

Which (`$(pwd)`) expands to

    docker run --rm -it -v /some/path/nginx/nginx.conf:/etc/nginx/conf.d/default.conf nginx:latest

The daemon (inside the VM);

- checks if `/some/path/nginx/nginx.conf` exists
- the path does not exist (because it's outside of `/Users`, so not shared with the VM
- it creates a _directory_ named `/some/path/nginx/nginx.conf`
- it creates a container from the `nginx:latest` image
- it bind-mounts the directory `/some/path/nginx/nginx.conf` at `/etc/nginx/conf.d/default.conf` in the container.

The last step fails, because inside the container, there's a _file_ named `/etc/nginx/conf.d/default.conf`, and bind-mounting a directory over a file is not possible in Linux, so the container fails to start.

To resolve:

If you want to stay on Docker Toolbox (and use VirtualBox / boot2docker);

- make sure the file you want to bind-mount is inside the `/Users` directory on OS X
- or share additional paths with the VM; this requires some manual steps, as explained here: https://github.com/boot2docker/boot2docker#virtualbox-guest-additions

_However_ if your Mac is capable of running a more recent version of OS X, and meets the other requirements; https://docs.docker.com/docker-for-mac/#/what-to-know-before-you-install, I suggest to give Docker for Mac a try. Docker for Mac resolves most of the limitations caused by VirtualBox, and is a lot easier to use.

I'll close this issue, because this is not a bug, but feel free to continue the discussion if you have questions

**Closed by thaJeztah** 2016-09-29 11:14 UTC

**Comment by settermjd** [comment] 2017-05-24 09:22
I was referred to this issue. I'm using Docker for Mac (macOS Sierra) and am trying to copy a file in my Docker configuration to a container located on DigitalOcean and receive the error. I was wondering whether the file had to be copied and not attempted to be mounted.

**Comment by thaJeztah** [comment] 2017-05-24 10:53
@settermjd if you are trying to use bind-mounted directories from your local machine to a remote DigitalOcean machine (`-v /my/local/dir:/container/dir`), that won't work; bind-mounts don't work with remote machines

Also, please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)
