### ISSUE TITLE
command failed with error "stdout: Broken pipe" in docker containers

### ISSUE THREAD

**Issue by tsingfu** [docker/docker#11565] opened 2015-03-22 14:15 UTC
- 1Description of problem:

When use docker to do my test, I found a issue: use rpmbuild to build binary package from source tarball failed in docker containers environment. the error message is: 
>[root@ganglia1 soft]# rpmbuild -tb ganglia-3.6.0.tar.gz 
>
>gzip: stdout: Broken pipe
>
>gzip: stdout: Broken pipe
>error: Failed to read spec file from ganglia-3.6.0.tar.gz
>[root@ganglia1 soft]# 

in vm of Virtualbox or vmware-server, rpmbuild works normally.

 - 2Environment 

OS: Mac OS X 10.10.2 (I remembered the issue ocurred in Ubuntu12.04.5, too.)
VirtualBOx + boot2docker

uname -a
>Darwin tsingfudeMacBook-Pro.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin

docker version
>Client version: 1.4.1
>Client API version: 1.16
>Go version (client): go1.3.3
>Git commit (client): 5bc2ff8
>OS/Arch (client): darwin/amd64
>Server version: 1.4.1
>Server API version: 1.16
>Go version (server): go1.3.3
>Git commit (server): 5bc2ff8

docker -D info
>Containers: 11
>Images: 24
>Storage Driver: aufs
> Root Dir: /mnt/sda1/var/lib/docker/aufs
> Dirs: 46
>Execution Driver: native-0.2
>Kernel Version: 3.16.7-tinycore64
>Operating System: Boot2Docker 1.4.1 (TCL 5.4); master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
>CPUs: 8
>Total Memory: 4.846 GiB
>Name: boot2docker
>ID: Z7PL:MIUK:7EEO:OXQU:BHJU:NXFK:4UBH:OKFP:7LEU:43LU:LDMD:AE56
>Debug mode (server): true
>Debug mode (client): true
>Fds: 59
>Goroutines: 51
>EventsListeners: 0
>Init Path: /usr/local/bin/docker
>Docker Root Dir: /mnt/sda1/var/lib/docker

 - 3How reproducible:

1) create a container
```
docker pull centos:6.6
docker run -i -t -d -P -h ganglia1 --name ganglia1 --volume=/Users/Users_datadir_docker:/docker_vol01 centos:6.6 /bin/bash
```

2) install rpm-build
```
yum install -y rpm-build.x86_64
```

3)download ganglia source tarball 
[ganglia-3.6.0.tar.gz](http://sourceforge.net/projects/ganglia/files/ganglia%20monitoring%20core/3.6.0/ganglia-3.6.0.tar.gz/download)

4)execute rpmbuild
```
rpmbuild -tb ganglia-3.6.0.tar.gz 
```

 - 4Actual Results:

>[root@ganglia1 soft]# rpmbuild -tb ganglia-3.6.0.tar.gz 
>
>gzip: stdout: Broken pipe
>
>gzip: stdout: Broken pipe
>error: Failed to read spec file from ganglia-3.6.0.tar.gz
>[root@ganglia1 soft]# 

 - 4Expected Results:

build binary package from source ball or return the dependency infos if exists missing dependencies.

I am new in docker and know little in debugging docker issue. Can any body look into the issue?

**Comment by visualphoenix** [comment] 2015-06-25 14:16
@tsingfu is this still an issue with the latest docker/boot2docker?

**Comment by thaJeztah** [comment] 2015-08-16 11:39
ping @tsingfu have you been able to reproduce this on the current version?

**Comment by tsingfu** [comment] 2015-08-19 01:49
@visualphoenix @thaJeztah  Sorry to reply after a long time, I will try to reproduce with new version of docker and update this issue later.

**Comment by calavera** [comment] 2015-09-11 23:28
Closing this since there are no more news about it. Please, feel free to reopen if there is any further investigation/evidence going on.

**Closed by calavera** 2015-09-11 23:28 UTC
