### ISSUE TITLE
simple answer

### ISSUE THREAD

**Issue by whwstar** [docker/docker#26132] opened 2016-08-30 06:08 UTC
yum reinstall cracklib-dicts

**Comment by vdemeester** [comment] 2016-08-30 07:58
hey @whwstar, I'm not sure what the issue is or if this is a mistyping thingy… Could you provide more detail (or close the issue if this is a mistype)

**Comment by duglin** [comment] 2016-08-30 11:55
I'm going with typo :-)

**Closed by duglin** 2016-08-30 11:55 UTC
