### ISSUE TITLE
modular build

### ISSUE THREAD

**Issue by josh-devops-center** [docker/docker#7664] opened 2014-08-21 18:28 UTC
Hi,

It would be nice if there was a modular build. For stacks which are composed of multiple containers, it is nice to keep them in a modular structure in git. As there are certain dependencies (e.g. as expressed by links), keeping a modular structure where the stack can be versioned and built as a single module makes things easier. Examples [1](https://github.com/amplab/docker-scripts) [2](https://github.com/wurstmeister/storm-docker) [3](https://github.com/devopscenter/docker-stack)

For those familiar with the Maven layout, being able to version and have dependencies which are submodules is a nice feature for large projects which are composed of smaller modules.

Is this a feature that can be added and also included on the dockerhub?

Thanks

**Comment by jfrazelle** [comment] 2015-02-25 22:10
closing as duplicate of https://github.com/docker/docker/issues/7115 and yes this would be cool, also for hub specific requests I would reach out to support@docker.com

**Closed by jfrazelle** 2015-02-25 22:10 UTC
