### ISSUE TITLE
Control-C while running `docker attach` should not terminate the Docker container

### ISSUE THREAD

**Issue by lhazlewood** [docker/docker#2855] opened 2013-11-25 23:10 UTC
Per this [Pull Request](https://github.com/dotcloud/docker/pull/2845) thread based on 0.6.5 to 0.6.7 functionality:

I believe most people feel that that if you run `docker attach` that `Control-C` should detach you and never shut down the container - in all cases. Stopping the container is what `docker stop` is for.  It is important to have feature symmetry and not surprise people:

IMO, end-users shouldn't be surprised by default behavior. When you `docker attach`, it is a surprise that `Ctrl-C` kills the container, because you expect the attachment to discontinue (i.e. 'detach'), not stop the container entirely - since that is what `docker stop` is for.

(now, if an end-user *wants* to terminate the container from attachment with `Control-C`, maybe that is supported by adding an explicit argument to the `docker run` command.  This just shouldn't be the default.  However, I presume that this extra feature wouldn't be worth working on  until people ask for it).

**Comment by jfrazelle** [comment] 2015-01-14 21:16
now that we have docker exec is this still an issue?

**Comment by jtmarmon** [comment] 2015-01-22 01:22
yes it is @jfrazelle. If I want to see active server logs I'll use `docker attach` to view the running process. exec won't do that for me

**Comment by cpuguy83** [comment] 2015-01-22 01:23
@jtmarmon That's what `docker logs` is for.

**Comment by tianon** [comment] 2015-01-22 01:24
but that's what "docker logs -f" is for :)

**Comment by jtmarmon** [comment] 2015-01-22 01:28
haha okay you got me, but my point still stands. there are other use cases for attaching to a running process. seems a bit odd to be able to kill a container process with absolutely no warning imo.

also man you guys are fast

**Comment by jfrazelle** [comment] 2015-02-26 23:11
I feel like we need to decide is this intentional or not (I am heavily leaning towards desired behavior) and document as so, so that people know.

**Comment by thaJeztah** [comment] 2015-02-27 00:00
Documentation has been already [been corrected](http://docs.docker.com/reference/commandline/cli/#attach). Although this is *by design*, https://github.com/docker/docker/issues/2855#issuecomment-56576213 nicely summarises *my* thoughts. Perhaps a similar approach as nodeJS would accommodate both "camps"?

    (press ^C again to quit or ^P ^Q to detach)

(my final suggestion on this. I'm too opinionated on this, think it's up to the maintainers to vote/make a decision)

**Comment by spullara** [comment] 2015-03-01 07:14
This was extremely surprising to me.

**Comment by izdi** [comment] 2015-07-07 15:06
Also ```docker run``` and cancelling (ctrl+c) the process won't kill, it instead it causes next operation to wait previous process to finish download image.

**Comment by jplandrain** [comment] 2015-11-13 13:07
+1 to @lhazlewood ^C should detach

**Comment by iwkse** [comment] 2015-12-03 00:12
+1 to @lhazlewood ^C should detach

**Comment by thaJeztah** [comment] 2015-12-03 00:16
There's currently a PR to make the key-combination configurable; https://github.com/docker/docker/pull/15666

**Comment by thaJeztah** [comment] 2015-12-15 15:18
Removing the "needs attention" label, there's now a PR

**Comment by thasmo** [comment] 2016-01-01 18:35
I've been surprised too, that `ctrl+c` *killed* the container/process instead of detaching.

**Comment by sebastianvilla** [comment] 2016-01-04 23:18
+1 to @lhazlewood ^C should detach

**Comment by cpuguy83** [comment] 2016-01-05 01:23
Well, good news, you can now do `--detach-keys ctrl-c` for this behavior, which can also be set in a config file under ~/.docker

Closing as the current behavior is the "correct" behavior and is in line with the how SSH handles detaching (albeit different key sequence), and also the detach sequence can be changed to use ctrl-c (or any other combination) people want.
This functionality will be in Docker 1.10, currently slated for early February.

**Closed by cpuguy83** 2016-01-05 01:23 UTC
Labels: kind/enhancement

**Comment by thaJeztah** [comment] 2016-01-05 08:20
For more info on the "configurable detach keys", see the pull request: https://github.com/docker/docker/pull/15666

**Comment by antoine-lizee** [comment] 2016-02-27 21:13
+1 for ^C should *detach* by default. `attach` is definitely different from `run`, and I end up using `exec ... bash` in part just because of this. I got so surprised when I killed my dokku the first time after doing some maintenance!

**Comment by cpuguy83** [comment] 2016-02-27 21:31
@antoine-lizee: this is not going to change. You can set this value yourself both per command with a flag as well as a default via config file.

**Comment by kevart** [comment] 2016-04-19 05:53
+1 to @lhazlewood ^C should detach

**Comment by rodionos** [comment] 2016-04-19 12:45
+1 to @lhazlewood ^C should detach

**Comment by thaJeztah** [comment] 2016-04-19 12:55
I'm locking this issue; the default key-combination is not going to change, and you can now set your own default using a configuration file https://github.com/docker/docker/pull/15666. I understand that for some people `^C` is the preferred combination and they are now able to do so.
