### ISSUE TITLE
Container crash leaves iptables DOCKER / POSTROUTING chain in unclean state

### ISSUE THREAD

**Issue by falschparker82** [docker/docker#15151] opened 2015-07-30 08:53 UTC
Hi there,

we observed an issue yesterday on Docker 1.6.2 (not sure if it's fixed by docker/libnetwork#301  docker/docker#13957 , but probably not), running on Ubuntu 14.04

A container mysteriously crashed, so I restarted it via `docker-compose up -d`. Container was configured to expose internal port 8080 as external port 1336. Now came the curious part: From the host, the container was reachable under localhost:1336, but NOT under $HOST_PRIVATE_IP:1336

This was a situation that "shouldn't ever happen" as we saw it and took us quite a few hours to find out. Finally, we found the culprit in the iptables:

```
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
[...]
MASQUERADE  tcp  --  ip-172-17-0-154.eu-west-1.compute.internal  ip-172-17-0-154.eu-west-1.compute.internal  tcp dpt:http-alt
[...]
MASQUERADE  tcp  --  ip-172-17-0-212.eu-west-1.compute.internal  ip-172-17-0-212.eu-west-1.compute.internal  tcp dpt:http-alt

Chain DOCKER (2 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             anywhere             tcp dpt:1336 to:172.17.0.154:8080
[...]
DNAT       tcp  --  anywhere             anywhere             tcp dpt:1336 to:172.17.0.212:8080
```

Docker apparently never cleaned up the old DNAT entry, so it was conflicting with the newer one and shadowing it.

The docker daemon was never restarted throughout the whole issue and investigation (mainly because we wanted to find the culprit). We could not find out what exactly crashed the container - but not the daemon - though.

If this is somehow still an issue, it seems rather easy to fix by always checking for duplicate external port configurations (which should never happen) when inserting the iptable rules. I'm unfortunately not too deep within the codebase, so I can't fix this and don't know if it's still an issue.

Best,

Dominik

**Comment by mrjana** [comment] 2015-07-30 19:54
@falschparker82 This most likely should not be a problem in 1.7.1 because we do remove all the port mapping iptable rules when the container stops. And from what you are saying it looks like your container  crashed while the daemon was still running. In that situation the daemon should always be able to detect the container going down(gracefully or ungracefully) and trigger the cleanup. Can you please try 1.7.1 and let us know?

**Comment by thaJeztah** [comment] 2015-08-09 19:11
@falschparker82 have you been able to test of this is resolved with 1.7.1? Thanks!

**Comment by w4-sjcho** [comment] 2015-08-11 02:02
I'm using AWS elastic beanstalk which runs docker 1.6.2, and seems like I'm also affected by this. Took me hours to figure out the problem.

As it's hard for us to update beanstalk's docker version, is there any workaround for this? What I can do is running some commands before starting up the docker containers.

Also is it safe to just manually remove all iptables forwarding entries that point to old docker containers?

**Comment by peterkuiper** [comment] 2015-08-14 15:13
I'm also seeing this issue (or something similar) with 1.8.1:

```
docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 19:47:52 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

I used `docker-compose up`. After stopping the containers the iptables entries are still there:

```
docker-compose up
```

```
root@dev:/etc# iptables -L -n -v
Chain INPUT (policy ACCEPT 149 packets, 14268 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 130 packets, 34005 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.17          tcp dpt:5000
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.17          172.17.0.16          tcp dpt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.16          172.17.0.17          tcp spt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.17          172.17.0.16          tcp dpt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.16          172.17.0.17          tcp spt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.17          172.17.0.16          tcp dpt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.16          172.17.0.17          tcp spt:6379
```

```
docker-test  docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

```
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS                            PORTS               NAMES
59dc811cc019        dockertest_web       "/bin/sh -c 'python a"   About a minute ago   Exited (137) 6 seconds ago                            dockertest_web_1
9f772dea80aa        redis                "/entrypoint.sh redis"   About a minute ago   Exited (0) 16 seconds ago                             dockertest_redis_1
```

Entries are still here:

```
iptables -L -n -v
Chain INPUT (policy ACCEPT 64 packets, 6578 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 42 packets, 9837 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.17          172.17.0.16          tcp dpt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.16          172.17.0.17          tcp spt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.17          172.17.0.16          tcp dpt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.16          172.17.0.17          tcp spt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.17          172.17.0.16          tcp dpt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.16          172.17.0.17          tcp spt:6379
```

Another `docker-compose up`:

```
iptables -L -n -v
Chain INPUT (policy ACCEPT 317 packets, 32548 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 283 packets, 58144 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.17          172.17.0.16          tcp dpt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.16          172.17.0.17          tcp spt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.17          172.17.0.16          tcp dpt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.16          172.17.0.17          tcp spt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.17          172.17.0.16          tcp dpt:6379
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.16          172.17.0.17          tcp spt:6379
    0     0 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.18          tcp dpt:3000
    0     0 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.21          tcp dpt:80
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.21          172.17.0.18          tcp dpt:3000
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.18          172.17.0.21          tcp spt:3000
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.21          172.17.0.18          tcp dpt:3000
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.18          172.17.0.21          tcp spt:3000
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.21          172.17.0.18          tcp dpt:3000
    0     0 ACCEPT     tcp  --  docker0 docker0  172.17.0.18          172.17.0.21          tcp spt:3000
```

I'm also not sure why icc=true by default on the docker daemon. It seems no isolation is being provided though the docker-compose docs state that: "Define the services that make up your app in docker-compose.yml so they can be run together in an isolated environment:". It seems that this is not true, or I am overlooking something.

I am running this on my Mac using virtualbox. I created the docker vm with docker-machine.

**Comment by retornam** [comment] 2015-09-16 22:54
@falschparker82 @peterkuiper I'm also running 1.6.2 and ran into this same issue twice this week.  Have you been able to figure out any workarounds for this? Thanks

**Comment by peterkuiper** [comment] 2015-09-17 06:52
@retornam No I haven't. I just removed the vm and started over. I'm not sure if this was a one-time thing or if I'm still having this problem. If I am I'm just ignoring it :) Have you tried running 1.8.x?

**Comment by mindscratch** [comment] 2015-09-30 16:33
I'm having similar issues with 1.7.1 on CentOS 7. I'm unable to update to docker 1.8.2 because we're running registry 2.1.1 (backed by NFS) and [this issue](https://github.com/docker/docker/issues/15833) is a blocker.

**Comment by carmstrong** [comment] 2015-11-20 20:06
We have a user seeing this on Docker 1.7.1 on CoreOS. Confirmed that restarting Docker resolves the issue.

**Comment by carmstrong** [comment] 2015-11-20 20:18
What repro steps does the Docker team need to investigate this? It seems pretty easy to have a running container crash and have the daemon not clean up its rules.

**Comment by thaJeztah** [comment] 2015-11-23 10:33
@carmstrong I'm not entirely sure a reproducible case for 1.7.x is helpful, unless it's still reproducible on 1.9.x, given that we don't perform back ports to older releases. However, if you're having a minimal test-case, perhaps someone is able to see if it's still reproducible on 1.9.x

**Comment by sempasha** [comment] 2016-01-14 10:55
`Docker version 1.9.1, build a34a1d5`
We have come into this issue right now. After some investigations we found exact the same - port forwarding rules still in iptables since container has been crashed hours ago.

**Comment by aboch** [comment] 2016-01-14 17:54
Yes I was able to reproduce this with latest master.
I closed the shell where the cotnainer with exposed ports was running and I see libnetwork is not being informed of the container going down. So no cleanup is happening.

The only logs showing are:
```
DEBU[0577] Closing buffered stdin pipe                  
DEBU[0577] attach: stdin: end                           
DEBU[0577] attach: stderr: end                          
DEBU[0577] attach: stdout: end
```

**Comment by LRancez** [comment] 2016-01-21 15:53
+1

**Comment by f-wong** [comment] 2016-05-11 23:39
Seeing the same issue on Docker 1.7.1 in CoreOS. Had to manually do a docker run and bind to different  IP/port pairs in order to figure out what was the issue. At the end, I backed up iptables and manually deleted the offending entries and it worked.

**Comment by aboch** [comment] 2016-09-14 19:56
This no longer happens in recent docker versions.
If the container crashes, containerd will notify the daemon which in turn will ask libnetwork to release the resources held by the container. 

Tested killing the container pid in 1.11.2 and 1.12.1 and the corresponding rules in the nat table are correctly removed.
I think this issue can now be closed.

**Comment by LK4D4** [comment] 2016-09-14 20:01
@aboch Nice, thank you!

**Closed by LK4D4** 2016-09-14 20:01 UTC
Labels: area/networking, status/more-info-needed
