### ISSUE TITLE
Invisible line when using ctrl-p in ubuntu interactive mode

### ISSUE THREAD

**Issue by sne4ky** [docker/docker#25062] opened 2016-07-26 12:33 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: HFB4:JJBA:N64N:A5NU:I6DM:MN5N:SKBD:JXBX:NKHS:BS5Y:AHGD:MSV5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2016-07-26T12:29:07.734971268Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Mac OS X El Capitan, version 10.11.5

**Steps to reproduce the issue:**
1. docker run -t -i --rm ubuntu /bin/bash
2. Input any command (example: ls -a)
3. Press Ctrl-P. No line will be shown in terminal, instead of the previous command.
4. Press Enter. The command will be reproduced.

**Comment by thaJeztah** [comment] 2016-07-26 12:53
This is because the default key-combination to detach from a container is `CTRL-p,q`, which captures the first `CTRL-p`

You can override the detach-key combination using the `--detach-keys` flag on `docker run`;

```
docker run -t -i --rm --detach-keys=ctrl-a,b ubuntu /bin/bash
```

Or by setting a custom default in a client configuration file;

https://docs.docker.com/engine/reference/commandline/cli/#/configuration-files

for example (in `~/.docker/config.json`):

```json
{
  "detachKeys": "ctrl-a,b"
}
```

I'm closing this issue, because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-07-26 12:53 UTC
Labels: version/1.12
