### ISSUE TITLE
UDP forwarded traffic gets lost occassionally

### ISSUE THREAD

**Issue by wagonza** [docker/docker#13318] opened 2015-05-19 09:24 UTC
The problem is quite similar to #11998 however in this environment its a Radius service which has its own IP address. The problem starts to occur and only for select random source hosts sending UDP traffic  (to port 1812) and at random times. Weeks can go by without the issue.

TCPDump shows the traffic being received and forwarded but no responses are sent for certain hosts.
The service continues to run fine and and respond to other hosts using the same port and IP address.

This happens on Docker v1.4.1 and v1.3 running on a  physical CentOS7.0.1406 (Linux AUTH-1 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux)

```
# docker info
Containers: 22
Images: 185
Storage Driver: devicemapper
 Pool Name: docker-253:1-68123918-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 18.38 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 17.76 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 12
Total Memory: 31.22 GiB
Name: AUTH-1
ID: N67L:3XDP:5BPC:TXKK:XOKL:FEDK:AEJW:BQWV:HTHZ:VA7J:4N2G:FUZR
```

**Comment by thaJeztah** [comment] 2015-05-25 19:37
May be similar to https://github.com/docker/docker/issues/8357 as well? I wonder if you are still able to reproduce this on the current version (1.6.2 at the time of writing)

This might be a hard one to track though, because it's not consistently failing :(

/cc @mavenugo @mrjana for networking.

**Comment by morcmarc** [comment] 2015-05-26 08:49
I'm running a Consul cluster inside docker containers (progrium/consul) and nodes keep losing connection to each other randomly. I suspect it is caused by docker dropping UDP packets but I'll monitor the network packages a bit more closely and see if I can report anything useful back here.

I'll also try upgrading docker.

**Comment by wagonza** [comment] 2015-05-27 02:18
@thaJeztah yeah similar to that but not as easy to replicate as that example. I did up date to 1.6.0 and still had the same result. I was a bit pressured for time so had to make a plan without docker to restore service.

However I did try do some trouble shooting with inside the container. Netstat (netstat -u) showed the Receive Queue values increasing with each udp packet received. netstat -su shows that there was a ton of receive errors and the value was just climbing. I figured then about adjusting some sysctls on the host however adjusting any of those udp related controls had no affect on the container. So the symptoms do lend itself to some buffer that is possibly not been cleaned up?

Just for some further information the container is CentOS 6.6 and the host is CentOS7.

**Comment by thaJeztah** [comment] 2015-05-27 07:09
@wagonza thanks for testing. There a a lot of changes coming in the 1.7 release (option to disable the userland proxy, integration of libnetwork). I'm no huge network expert here and, apart from being aware that there are some issues around UDP traffic getting lost, don't know if the coming release has improvements in that area. 

It's currently quite hectic with preparations of the 1.7 release, but I'll ping the "network" maintainers to have a look here as well, if they have time (feel free to ping me if this issue stalls :));

@mrjana @mavenugo perhaps you can have a look if improvements were made here, or are planned?

**Comment by cpuguy83** [comment] 2015-10-02 16:11
Closing since this looks like a dup of #11998, even though it's a different service.

Thanks!

**Closed by cpuguy83** 2015-10-02 16:11 UTC
Labels: group/networking
