### ISSUE TITLE
"Driver devicemapper failed to remove root filesystem" on docker rm error on v1.3 w/ devicemapper driver

### ISSUE THREAD

**Issue by parisk** [docker/docker#8712] opened 2014-10-22 16:22 UTC
I am using Docker 1.3 with Devicemapper storage driver on a server that runs multiple containers at a time and has many dead containers that need to be cleaned away. When I use `docker rm <container-id>` to remove some containers I get the following error pretty often.

```
Error response from daemon: Cannot destroy container 89bb8b0bb1c3: Driver devicemapper failed to remove root filesystem 89bb8b0bb1c3b005fdc77424c74ae1805b83d9e2ea18c4bc8803c4466d976257: Device is Busy
```

This server runs Ubuntu 14.04 and I use an external SSD drive separated in two physical volumes with LVM to store Docker data and metadata accordingly, using the Devicemapper Docker back-end.

The funny thing is that after I get these errors, these containers do not exist anymore. So am I stuck with these useless root file system volumes on my hard drive? How can I make sure they get away?

Basically any help with that would be really appreciated.

### uname -a
`Linux paris 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

### docker version
```
Client version: 1.3.0
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f
OS/Arch (client): linux/amd64
Server version: 1.3.0
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): c78088f
```

### docker -D info
```
Containers: 16
Images: 128
Storage Driver: devicemapper
 Pool Name: docker-202:1-525407-pool
 Pool Blocksize: 65.54 kB
 Data file: /dev/direct-lvm/data
 Metadata file: /dev/direct-lvm/metadata
 Data Space Used: 3.111 GB
 Data Space Total: 81.6 GB
 Metadata Space Used: 18.33 MB
 Metadata Space Total: 4.291 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
Debug mode (server): false
Debug mode (client): true
Fds: 43
Goroutines: 72
EventsListeners: 0
Init Path: /usr/bin/docker
```

**Comment by vbatts** [comment] 2015-01-07 19:01
closing as a duplicate of https://github.com/docker/docker/issues/5684#issuecomment-69052334

**Closed by vbatts** 2015-01-07 19:01 UTC
Labels: /system/devicemapper
