### ISSUE TITLE
Docker registry maintain/cleanup isssue

### ISSUE THREAD

**Issue by ppawlowski** [docker/docker#20166] opened 2016-02-09 21:20 UTC
Hello Gents,

I am using docker and docker-registry for some time. Currently I am facing a disk space issue on a server, where docker-registry is running. My question is quite simple - are there some 'best practices' regarding maintaining docker-registry server? Especially I would like to know which of the images could be safely removed without harming developers work.
I appreciate for any tip or trick how to correctly manage docker regostry.
Cheers!

**Comment by thaJeztah** [comment] 2016-02-09 21:47
Please keep in mind that the issue tracker is for reporting bugs and feature requests, not for general support questions;

This question is better asked at;

- forums.docker.com
- the docker-users Google Group (https://groups.google.com/forum/#!forum/docker-user)
- the #docker or #docker-distribution IRC channel on free node


I'm going to close this issue, because this is not a bug or feature request, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-02-09 21:47 UTC
