### ISSUE TITLE
https://get.docker.com/ | sh fails with invalid GPG

### ISSUE THREAD

**Issue by miqui** [docker/docker#21729] opened 2016-04-01 20:18 UTC
testing on ubuntu 14.04:

:~# curl -sSL https://get.docker.com/ | bash
apparmor is enabled in the kernel and apparmor utils were already installed
+ sh -c 'apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D'
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.OomvcJQbBE --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

**Comment by miqui** [comment] 2016-04-01 20:21
VM on OpenStack
no docker info since we cannot install docker

to reproduce as root:
curl -sSL https://get.docker.com/ | sh

**Comment by programmerq** [comment] 2016-04-01 21:03
Closing, as this is a duplicate of #21079.

Additionally, these changes have already been merged and are targeted to be released alongside the 1.11 release: https://github.com/docker/docker/commit/adac575dd33c48b19539c0f0660c5c3f344c7b75

**Closed by programmerq** 2016-04-01 21:03 UTC
