### ISSUE TITLE
A tool to workaround problems happened to docker

### ISSUE THREAD

**Issue by phuongnd08** [docker/docker#10581] opened 2015-02-05 07:12 UTC
I'm running a production cluster with docker 1.3.3 (CoreOS btw). And has been encountering serious issues. Currently docker on a machine in the cluster is throwing "invalid json" error.

Since docker is not quite stable we should introduce tools so that people could use to "heal" docker. Stuff like sanitize configuration file, free up disc space should be consolidate into a tool.

Thoughts?

**Comment by cpuguy83** [comment] 2015-02-05 13:09
@phuongnd08 I think I would completely disagree that docker is not stable.
Can you elaborate more on the problem you are having/what happened to cause it?

**Comment by phuongnd08** [comment] 2015-02-05 13:13
For example this: https://github.com/docker/docker/issues/10553
I didn't tried to hack docker in any way, just using its supported command.
But encountered various kinds of bugs: 
1. `docker ps` won't run
2. `docker run` won't run, throw json error

**Comment by cpuguy83** [comment] 2015-02-05 13:16
Have you checked the daemon logs? If nothing stands out, can you enable debug logging and try to run again?

**Comment by unclejack** [comment] 2015-02-05 13:32
@phuongnd08 This issue isn't about a bug. Please discuss actual problems you're running into. The issue you're seeing is already being discussed on #10553.

The actual cause might have something to do with your systems, not necessarily with Docker. Many problems we've seen are caused by configuration and by the environment.

I'm going to close this issue now. Please discuss on #10553 instead. I'm not going to lock this issue as with other duplicate issues in order to allow others to discuss ideas around debugging tools.

**Closed by unclejack** 2015-02-05 13:32 UTC
