### ISSUE TITLE
Docker in Docker no clean remove

### ISSUE THREAD

**Issue by obi12341** [docker/docker#8686] opened 2014-10-21 21:33 UTC
Hello ppl,

running a docker in docker will result in a not clean enviroment
```
vagrant@vagrant:~$ docker run -ti --privileged=true --rm ubuntu /bin/bash
root@9fd5f2312bfc:/# docker run -i -t --rm ubuntu /bin/bash
Unable to find image 'ubuntu' locally
ubuntu:latest: The image you are pulling has been verified
511136ea3c5a: Pull complete
97fd97495e49: Pull complete
2dcbbf65536c: Pull complete
6a459d727ebb: Pull complete
8f321fc43180: Pull complete
03db2b23cf03: Pull complete
9cbaf023786c: Pull complete
Status: Downloaded newer image for ubuntu:latest
root@d7b8bb517640:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  18168  2000 ?        Ss   21:27   0:00 /bin/bash
root        18  0.0  0.0  15568  1128 ?        R+   21:27   0:00 ps aux
root@d7b8bb517640:/# exit
exit
root@9fd5f2312bfc:/# docker version
Client version: 1.3.0
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f
OS/Arch (client): linux/amd64
Server version: 1.3.0
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): c78088f
root@9fd5f2312bfc:/# exit
exit
2014/10/21 23:28:08 Error response from daemon: Cannot destroy container 9fd5f2312bfc5642fc20fab2feb63b1b7a3d600ab45882872a09d2ddf55ff8e3: Driver aufs failed to remove root filesystem 9fd5f2312bfc5642fc20fab2feb63b1b7a3d600ab45882872a09d2ddf55ff8e3: rename /var/lib/docker/aufs/diff/9fd5f2312bfc5642fc20fab2feb63b1b7a3d600ab45882872a09d2ddf55ff8e3 /var/lib/docker/aufs/diff/9fd5f2312bfc5642fc20fab2feb63b1b7a3d600ab45882872a09d2ddf55ff8e3-removing: device or resource busy
vagrant@vagrant:~$ docker version
Client version: 1.3.0
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f
OS/Arch (client): linux/amd64
Server version: 1.3.0
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): c78088f
vagrant@vagrant:~$
```

**Comment by jfrazelle** [comment] 2015-02-26 05:05
closing as dupe of https://github.com/docker/docker/issues/9939

**Closed by jfrazelle** 2015-02-26 05:05 UTC
