### ISSUE TITLE
namespace creation reexec command failed: exit status 1

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#14985] opened 2015-07-25 05:17 UTC
Filing this before I forget, I have seen this on master and 1.7.1

```
root@build-box:~# uname -a
Linux build-box 3.19.0-22-generic #22-Ubuntu SMP Tue Jun 16 17:15:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@build-box:~# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
root@build-box:~# docker info
Containers: 1
Images: 87
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 89
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-22-generic
Operating System: Ubuntu 15.04
CPUs: 8
Total Memory: 15.67 GiB
Name: build-box
ID: 2OEW:PWQO:DQ4D:UUDB:JYAF:2UML:NM6Y:KCZ7:UEQN:6BSG:U4Y7:6BFK
WARNING: No swap limit support
```

Also have seen it w static binary and with the dynamic ones.

**Comment by jfrazelle** [comment] 2015-07-25 05:18
shouldn't block 1.8.0-rc but we should fix it

**Comment by jfrazelle** [comment] 2015-07-25 05:19
running containers w `--net host` will fix it, but builds will still error out this way

**Comment by jfrazelle** [comment] 2015-07-25 05:19
ping @mrjana who is already aware of it ;)

**Comment by jfrazelle** [comment] 2015-07-25 05:20
rebooting fixes as well for like a few runs, then it reappears

**Comment by timfallmk** [comment] 2015-07-26 07:18
@jfrazelle Hey Jess. +1 to this issue as well. No fix on restart for Ubuntu 15.04.

**Comment by timfallmk** [comment] 2015-07-26 07:22
Error log here:
```syslog
Jul 26 00:05:31 Desktop-3 docker[8116]: time="2015-07-26T00:05:31.469209464-07:00" level=error msg="Couldn't run auplink before unmount: exit status 13"
Jul 26 00:05:31 Desktop-3 docker[8116]: time="2015-07-26T00:05:31.673205335-07:00" level=info msg="POST /v1.20/containers/e3e4f7bf0135ff7d349aa586056290d8ef8e72e90311a08b593b616b6a3caeb
Jul 26 00:05:31 Desktop-3 docker[8116]: time="2015-07-26T00:05:31.676351894-07:00" level=info msg="POST /v1.20/containers/e3e4f7bf0135ff7d349aa586056290d8ef8e72e90311a08b593b616b6a3caeb
Jul 26 00:05:31 Desktop-3 docker[8116]: time="2015-07-26T00:05:31.698002160-07:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external serve
Jul 26 00:05:31 Desktop-3 docker[8116]: time="2015-07-26T00:05:31-07:00" level=fatal msg="permission denied"
Jul 26 00:05:31 Desktop-3 docker[8116]: time="2015-07-26T00:05:31.721273330-07:00" level=error msg="Leave all failed for  e3e4f7bf0135ff7d349aa586056290d8ef8e72e90311a08b593b616b6a3caeb
Jul 26 00:05:31 Desktop-3 docker[8116]: time="2015-07-26T00:05:31.736391797-07:00" level=error msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container e
Jul 26 00:05:31 Desktop-3 docker[8116]: time="2015-07-26T00:05:31.736460828-07:00" level=error msg="HTTP Error" err="Cannot start container e3e4f7bf0135ff7d349aa586056290d8ef8e72e90311a
Jul 26 00:05:31 Desktop-3 docker[8116]: time="2015-07-26T00:05:31.737343013-07:00" level=info msg="DELETE /v1.20/containers/e3e4f7bf0135ff7d349aa586056290d8ef8e72e90311a08b593b616b6a3ca
Jul 26 00:06:16 Desktop-3 docker[8116]: time="2015-07-26T00:06:16.600475647-07:00" level=info msg="GET /v1.20/containers/json?all=1"
Jul 26 00:06:24 Desktop-3 docker[8116]: time="2015-07-26T00:06:24.489484616-07:00" level=info msg="POST /v1.20/containers/create"
Jul 26 00:06:24 Desktop-3 docker[8116]: time="2015-07-26T00:06:24.652973172-07:00" level=info msg="POST /v1.20/containers/8adafb3471967ff9304d7795cda3a205dc8ad776f68d1a878e8b07ef674e8a9
Jul 26 00:06:24 Desktop-3 docker[8116]: time="2015-07-26T00:06:24.655465708-07:00" level=info msg="POST /v1.20/containers/8adafb3471967ff9304d7795cda3a205dc8ad776f68d1a878e8b07ef674e8a9
Jul 26 00:06:24 Desktop-3 docker[8116]: time="2015-07-26T00:06:24.660307092-07:00" level=warning msg="Failed adding service host entries to the running container: open /var/lib/docker/c
Jul 26 00:06:24 Desktop-3 docker[8116]: time="2015-07-26T00:06:24.660959980-07:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external serve
Jul 26 00:06:24 Desktop-3 docker[8116]: time="2015-07-26T00:06:24-07:00" level=fatal msg="permission denied"
```

**Comment by gtonic** [comment] 2015-07-27 08:50
+1

**Comment by dweomer** [comment] 2015-07-27 10:07
just started seeing this on my 15.04 workstation with 1.8.0-dev installed and even after reverting to 1.7.1. i did update my kernel a few hours ago, i wonder if that is related

**Comment by LK4D4** [comment] 2015-07-27 16:47
@jfrazelle @ewindisch Seems like related to apparmor changes.

**Comment by jfrazelle** [comment] 2015-07-27 16:50
I dunno? I don't even have apparmor on one of the machines I saw it on but idk

**Comment by ewindisch** [comment] 2015-07-27 16:58
A fix is already proposed in #14934

**Comment by jfrazelle** [comment] 2015-07-27 17:02
ah nice

**Comment by jfrazelle** [comment] 2015-07-27 17:03
I do not think that will totally fix the problem tho unless that was also in 1.7.1 because I also see this in that version

**Comment by ewindisch** [comment] 2015-07-27 17:08
@jfrazelle it could be a red herring on this issue, but @dweomer is indicating an apparmor problem in his logs.

**Comment by jfrazelle** [comment] 2015-07-27 17:09
ah ok, but i think there is something else as well, just making noise so its not over looked haha

**Comment by timfallmk** [comment] 2015-07-27 21:26
@dweomer Confirmed that this is related to veth accumulation. I can match their creation 1-to-1 with this error in my logs with 1.8.0-dev.

**Comment by dweomer** [comment] 2015-07-28 00:53
I just replaced my `/etc/apparmor.d/docker-engine` with the fixed file from #14934 followed by
```
sudo systemctl daemon-reload
sudo systemctl restart apparmor
sudo systemctl restart docker
```
... which seems to have solved the problem for me.

**Comment by dweomer** [comment] 2015-07-28 13:17
Now `docker stop` fails (/var/log/kern.log):
```
Jul 28 06:15:30 JLEBC-LWS kernel: [97412.645481] audit: type=1400 audit(1438089330.235:1517): apparmor="ALLOWED" operation="open" profile="/usr/bin/docker" name="/home/jacob/.docker/config.json" pid=4644 comm="docker" requested_mask="r" denied_mask="r" fsuid=0 ouid=1000
Jul 28 06:15:30 JLEBC-LWS kernel: [97412.646324] audit: type=1400 audit(1438089330.235:1518): apparmor="ALLOWED" operation="ptrace" profile="/usr/bin/docker" pid=12847 comm="docker" requested_mask="trace" peer="docker-default"
Jul 28 06:15:30 JLEBC-LWS kernel: [97412.646359] audit: type=1400 audit(1438089330.235:1519): apparmor="DENIED" operation="signal" profile="docker-default" pid=12847 comm="docker" requested_mask="receive" denied_mask="receive" signal=term peer="/usr/bin/docker"
Jul 28 06:15:30 JLEBC-LWS kernel: [97412.646402] audit: type=1400 audit(1438089330.235:1520): apparmor="ALLOWED" operation="ptrace" profile="/usr/bin/docker" pid=12847 comm="docker" requested_mask="trace" peer="docker-default"
Jul 28 06:15:30 JLEBC-LWS kernel: [97412.646426] audit: type=1400 audit(1438089330.235:1521): apparmor="DENIED" operation="signal" profile="docker-default" pid=12847 comm="docker" requested_mask="receive" denied_mask="receive" signal=kill peer="/usr/bin/docker"
```

I suppose if I knew anything about apparmor I could fix this myself =/

**Comment by timfallmk** [comment] 2015-07-29 05:51
@dweomer I've replaced my apparmor entry with that referenced in #15099 and seen no further problems aside from the AppArmor warnings in logs, which are expected.

**Comment by icecrime** [comment] 2015-07-29 17:43
Closed by #15099.

**Comment by icecrime** [comment] 2015-07-29 17:44
Thanks for the help and testing.

**Closed by icecrime** 2015-07-29 17:43 UTC

**Comment by lblackstone** [comment] 2016-03-04 18:12
Wanted to note that the
```
apparmor="DENIED" operation="mount" info="Failed name lookup - disconnected path" error=-13 profile="/usr/bin/docker" name="/run/docker/netns/2b1f6a8d74b5/" pid=8414 comm="exe" srcname="" flags="rw, bind"
```
error seen by @dweomer previously is related to an [open bug](https://bugs.launchpad.net/apparmor/+bug/1496430) in AppArmor.

The relevant fix has not yet made it into AppArmor, although Ubuntu distros have been [patched](https://lists.ubuntu.com/archives/kernel-team/2015-October/063471.html).

It appears that the reason this issue went away for you previously was due to Docker setting the AppArmor profile in "complain" mode rather than "enforce" mode (see https://github.com/docker/docker/pull/15099).
