### ISSUE TITLE
docker images cannot list repo with port

### ISSUE THREAD

**Issue by JiangZhaoYang** [docker/docker#20599] opened 2016-02-23 09:27 UTC
Hi, 
   When repo name with port, docker images cannot list the image.Can someone please let me know how I resolve this issue? 
 [docker@localhost ~]$ docker images nginx
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
nginx               latest              5328fdfe9b8e        9 weeks ago         133.8 MB
_**[docker@localhost ~]$ docker tag 5328fdfe9b8e localhost:8000/test1
[docker@localhost ~]$ docker images localhost:8000/test1
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE**_
[docker@localhost ~]$ docker tag 5328fdfe9b8e localhost/test1
[docker@localhost ~]$ docker images localhost/test1
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
localhost/test1     latest              5328fdfe9b8e        9 weeks ago         133.8 MB
[docker@localhost ~]$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

**Comment by HackToday** [comment] 2016-02-23 10:18
I used 1.10.1 docker. and it worked

```
[centos@centostest ~]$ docker tag e3317ea109cf  localhost:8000/test1
[centos@centostest ~]$ docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
docker-dev             master              cb416c0e0269        33 hours ago        2.064 GB
<none>                 <none>              0b3b9c2b4942        3 days ago          2.064 GB
ubuntu                 trusty              14b59d36bae0        5 days ago          187.9 MB
busybox                latest              3240943c9ea3        6 days ago          1.114 MB
jess/stress            latest              e3317ea109cf        10 days ago         125.3 MB
localhost:8000/test1   latest              e3317ea109cf        10 days ago         125.3 MB
hello-world            latest              690ed74de00f        4 months ago        960 B
[centos@centostest ~]$ docker images localhost:8000/test1
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
localhost:8000/test1   latest              e3317ea109cf        10 days ago         125.3 MB
```

**Comment by thaJeztah** [comment] 2016-02-23 17:29
Yes, looks like this is a duplicate of https://github.com/docker/docker/issues/18181, which was fixed in https://github.com/docker/docker/pull/17924 in Docker 1.10.

I'll close this issue, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-02-23 17:29 UTC
