### ISSUE TITLE
Issues Installing Docker on Mac OS X 10.11

### ISSUE THREAD

**Issue by BradRuderman** [docker/docker#17250] opened 2015-10-21 19:53 UTC
Description of problem:
When trying to run 
`docker run hello-world`
`Cannot connect to the Docker daemon. Is 'docker -d' running on this host?`
`docker version`: Docker version 1.8.3, build f4bf5c7

`docker info`:
```
➜  ~  docker info
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

`uname -a`:
Darwin Brads-MacBook-Pro.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.): 

VirtualBox Version 5.0.8 r103449

How reproducible:

Steps to Reproduce:
1. Visit this url https://docs.docker.com/installation/mac/
2. Follow instructions for installing + running toolbox
3. Opened virtualbox and made sure that the "default" machine is running

Actual Results:
➜  ~  docker info
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

Expected Results:
Docker will run correctly

Additional info:

**Comment by BradRuderman** [comment] 2015-10-21 19:55
Fixed by running
```
eval "$(docker-machine env default)"
```

**Comment by BradRuderman** [comment] 2015-10-21 20:21
Do I need to run this command every time I create a new session? Should it be included in my bash profile?

**Comment by thaJeztah** [comment] 2015-10-21 21:24
@BradRuderman it depends; if you have just one machine, you could add it to your profile, but otherwise running it is the best way. The "Docker Quickstart Terminal" should do that for you though, but if you're having issues with that, it's best to post those in the Docker Toolbox issue tracker; https://github.com/docker/toolbox/issues

I'm going to close this issue, because this is not a bug, but feel free to respond after I've closed

**Closed by thaJeztah** 2015-10-21 21:24 UTC
