### ISSUE TITLE
How to move just /var/lib/docker/volumn

### ISSUE THREAD

**Issue by workabyte** [docker/docker#25226] opened 2016-07-29 13:30 UTC
Sorry, still very new to all of this but cant find any documentation on it.
We are looking to move the location of the named volume storage to a separate drive.
Googled around a bit but with no luck.

**Comment by cpuguy83** [comment] 2016-07-29 13:48
@workabyte You'd have to set this up manually with a mount. Docker does not provide a way to move just the volume storage, only the entire `/var/lib/docker` dir.

**Comment by thaJeztah** [comment] 2016-07-29 14:00
I'm closing this issue, because this is a suppor question, not a bug, and forums.docker.com, or the #docker IRC are more suitable for that, but feel free to continue the discussion

**Closed by thaJeztah** 2016-07-29 14:00 UTC

**Comment by workabyte** [comment] 2016-07-29 14:05
@thaJeztah, being that there is no config in docker for setting location of these dir maybe this could be seen more as a feature request?

I could see value in having the ability to config the location of just the volumes dir.

To @cpuguy83 point, there are other ways around this and maybe that is the better approach as there is no modifications needed on dockers side.

Just a thought, thank you both :+1:
