### ISSUE TITLE
 how to  delete images in Docker registry，Please help me to solve this problem

### ISSUE THREAD

**Issue by zxlzh2015** [docker/docker#18988] opened 2015-12-30 10:00 UTC
how to  delete images in Docker registry，The use of "curl -x DELETE" DELETE isn't clean
I use the docker version is 1.6.2

**Comment by thaJeztah** [comment] 2015-12-30 11:35
I don't think its currently supported via the API, just in the UI of Docker Hub. See https://github.com/docker/hub-feedback/issues/496, https://github.com/docker/hub-feedback/issues/68#issuecomment-161839698

However, please keep in mind that the GitHub issue tracker is not a general support forum. This is an issue tracker for Docker bugs, features and pull requests. Please take this into account when opening an issue.

Use one of the below for support questions;

1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.

I'll close this issue, because this is a question, not a bug report, but feel free to comment after I've closed this.

**Closed by thaJeztah** 2015-12-30 11:35 UTC
