### ISSUE TITLE
Permissions problem on Docker 1.8 when reading from stdin

### ISSUE THREAD

**Issue by riklaunim** [docker/docker#15785] opened 2015-08-24 07:46 UTC
In my build scripts I have a line like so:

        tar c --mtime=2014-01-01 --exclude=__pycache__ --exclude=Dockerfile.template --mode="g=u,o=rX" --owner=root --group=root . | docker build --tag=$IMAGE_NAME:$BUILD_NUMBER -

It does work on Docker < 1.8 but on 1.8 it now throws:

    unable to prepare context: unable to extract stdin to temporary context direcotry: lchown /tmp/docker-build-context-183505935/run_entrypoints.sh: operation not permitted

I can change it to use sudo:

            tar c --mtime=2014-01-01 --exclude=__pycache__ --exclude=*.pyc --exclude=Dockerfile.template --mode="g=u,o=rX" . | sudo docker build --tag=$IMAGE_NAME:$BUILD_NUMBER -

and then it works, but I wonder if it's a bug or some change that affects permissions/users.

**Comment by riklaunim** [comment] 2015-08-24 07:50
docker version: 1.8.1, build d12ea79
docker info:
```
 Containers: 31
Images: 1038
Storage Driver: aufs
 Root Dir: /home/piotrm/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1100
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-21-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 15.67 GiB
```

uname -a: 

     Linux 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment] 2015-08-24 14:47
Yes there was a change in logic. The client is now extracting the tar to a tmp dir. Not sure why you don't have write perms on the temp dir... but in any case I'm not sure why we are extracting to disk here.
Ping @jlhawn who did this refactor.

**Comment by jlhawn** [comment] 2015-08-24 16:40
`docker build` in the 1.8 client now always prepares context in a local directory so that it can parse and rewrite the Dockerfile with resolved image digest references in `FROM` commands (it was part of the Docker Content Trust work).

**Comment by riklaunim** [comment] 2015-08-25 08:42
What could be the cause of those permission problems?

**Comment by colemickens** [comment] 2015-08-26 06:14
I'm hitting this as well, despite executing `chmod -R ugo+rwx [directoryname]` on the files before they're tar'd and piped into the `docker build` command.

This sort of breaks the "tar and output to standard out and take that as a new context" way of achieving nested builds. I'm not sure what else to do right now to workaround this.

**Comment by tomwys** [comment] 2015-08-26 10:20
It may be important that we run docker client as normal user added to `docker` group. This problem probably occurs only in `docker` group + tar combo. Adding sudo before docker command works as workaround.

**Comment by cpuguy83** [comment] 2015-08-26 13:10
This is 100% because you don't have write access to `/tmp`.

**Comment by riklaunim** [comment] 2015-08-26 13:20
I have full access to local /tmp

**Comment by colemickens** [comment] 2015-08-26 18:43
I also have full access to /tmp, and as described, already regranted permissions to user, group and others to the contents of the tar'd context.

**Comment by jlhawn** [comment] 2015-08-26 18:54
@cpuguy83 

> This is 100% because you don't have write access to /tmp.

It's not that, it's that the user doesn't have permission to `chown` and/or `chmod` things to preserve the permissions and ownership of files from the archive.

**Comment by loa** [comment] 2015-08-27 07:08
Seem to have same issue but on OSX with docker-machine

```
docker run builder | docker build -t test -
unable to prepare context: unable to extract stdin to temporary context direcotry: lchown /var/folders/0s/qt2_tt396pj5lm1cqbf82_y00000gn/T/docker-build-context-220503351/hello: operation not permitted
```

**Comment by cpuguy83** [comment] 2015-08-27 14:13
Oh right, I see lchown in the error now.

**Comment by colemickens** [comment] 2015-09-01 00:01
Any suggestions for workarounds besides downgrading docker?

**Comment by marcosnils** [comment] 2015-09-01 00:06
@colemickens the description on the issue gives a workaround by adding `sudo` to the `docker build` command.

**Comment by rednil** [comment] 2015-09-01 17:02
could it be this aufs specific permission bug (long read!): https://github.com/docker/docker/issues/783#issuecomment-76496911
solution would be to use the btrfs storage driver instead of aufs or (with kernel 3.19) the dirperm1 option to AUFS

**Comment by colemickens** [comment] 2015-09-01 19:21
I'm using `devicemapper` and hitting this issue.

**Comment by Kern3l** [comment] 2015-09-02 08:22
+1

**Comment by Kern3l** [comment] 2015-09-02 08:25
Awesome ;] My usecase is the same as Riklaunim's.

**Comment by kamkudla** [comment] 2015-09-19 11:17
What's the latest version that doesn't have this issue?

**Comment by riklaunim** [comment] 2015-09-19 12:05
1.7.X

**Comment by thaJeztah** [comment] 2015-10-03 12:22
@jlhawn @cpuguy83 what should be done here? Is this a documentation issue (i.e., change the ownership of the `tmp` dir), should docker create its own tmp dir?

**Comment by riklaunim** [comment] 2015-10-03 12:24
Either there should be a documented backward incompatible change with a new solution or the backward compatibility retained. (sudo is not the perfect solution)

**Comment by tomwys** [comment] 2015-10-03 13:54
This is bug, not documentation issue. `docker` client is user-space program and shouldn’t require root permissions to run. Feature of passing tar archive to `docker build` has been broken since 1.7, because it requires root access to be run in cases described above (no other feature of `docker` client requires root access).

`/tmp/` directory is not the problem and creating custom `/tmp/` dir will not solve this case. The problem is that `docker` client tries to extract archive preserving file ownership. This fails because non-root user can't change files ownership to arbitrary users.

The solution would be to:
* do not extract archive at all (for example you can work with archive in memory or extract only part of files),
* extract archive without file ownership  preservation, and handle file ownership by other means.

**Comment by thaJeztah** [comment] 2015-10-03 14:17
> /tmp/ directory is not the problem and creating custom /tmp/ dir will not solve this case. The problem is that docker client tries to extract archive preserving file ownership. This fails because non-root user can't change files ownership to arbitrary users.

Ah, you're right.

> docker build in the 1.8 client now always prepares context in a local directory so that it can parse and rewrite the Dockerfile with resolved image digest references in FROM commands (it was part of the Docker Content Trust work).

@jlhawn so, IIUC, all it needs is the *Dockerfile*, and being able to send the patched Dockerfile to the builder. Would it be an option to only extract the Dockerfile, and send that separately from the build-context?

**Comment by jlhawn** [comment] 2015-10-05 17:44
@thaJeztah 

> Would it be an option to only extract the Dockerfile, and send that separately from the build-context?

The Dockerfile has to be *in* the context, which means included in the tar archive which is uploaded. I think the best solution may be to special-case the situation where build context is read from `stdin` and *not* extract and then repackage it but instead modify the archive entry for the Dockerfile mid-flight to the daemon. It's kind of a hack that other maintainers are uncomfortable with but it would resolve the issue in this case. Unfortunately, a lot of work went into the build client to get this to work the way it does now and there's even more ongoing work to make builds completely client-driven (no context uploads at all). 

@tiborvass, as you are currently working on builder-related things, what is your opinion on this issue and how to best resolve it?

**Comment by tomwys** [comment] 2015-10-05 18:27
I don't know what tool/lib you use to work on archives, but can't you just replace single file rather that extracting and repacking whole archive?

For example standard GNU tar support such operations: https://www.gnu.org/software/tar/manual/html_section/tar_32.html

**Comment by colemickens** [comment] 2015-10-14 03:58
So, I take it that this isn't being fixed for 1.9.0 then?

**Comment by thaJeztah** [comment] 2015-10-14 04:03
@colemickens no, there wasn't time to look at this properly before the 1.9 code freeze.

**Comment by phemmer** [comment] 2015-10-16 01:35
`git bisect` shows #14546 is the cause of this issue.

**Comment by jlhawn** [comment] 2015-10-16 17:51
@phemmer yes, as mentioned here: https://github.com/docker/docker/issues/15785#issuecomment-134294159

The problem occurs because we no longer just forward your tar archive to the daemon but extract it locally first to modify the Dockerfile in case the `FROM <image name>` line needs to be modified for proper notary integration. This local extraction is then unable to preserve file ownership and permissions. I'd agree to special-casing this when you have `DOCKER_CONTENT_TRUST` disabled or just disabling notary integration when you build directly from an archive input from stdin (with a warning of course).

**Comment by phemmer** [comment] 2015-10-16 18:00
If the only purpose of this extraction is to modify the `Dockerfile` and convert the `FROM` into a container ID

1. Why is this modification not performed by the daemon? The client has to query the daemon anyway to resolve the reference.
2. The entire archive does not need to be extracted, just the one file. The tar format was designed to allow modifying the contents without modifying the tar stream itself. You simply append changes to the end of it. So, extract the `Dockerfile`, modify it, pass the original stream though untouched, and append a new `Dockerfile` to the stream.  
This has the added advantage that the tar file, nor its contents, need to be stored by the docker client.

**Comment by jlhawn** [comment] 2015-10-16 18:21
- The modification is to convert image tag references into image digest references (not container IDs).
- The daemon is not responsible for resolving an image tag references to a trusted SHA2 digest reference using notary, only the client has this capability because each user/client may want to configure Docker Content Trust differently (use different notary servers for example). The daemon is then responsible for pulling and verifying the content in the image using the digest reference. While you do not necessarily always need to pull the base image when performing a build, this ensures that you always have the latest image with that tag from the content publisher.
- I agree that modifying the tar archive mid-flight to the daemon could be a good idea. I originally made the commit in this way (pause upload of the tar just before it's about to send the Dockerfile content, rewrite it locally, send that instead, and continue uploading the rest of the archive). Appending it to the end could also work (this requires detecting the end of the archive which could either be abrupt or signaled with 1024 null bytes and inserting an extra entry). The reason it was changed was because the maintainers reviewing the PR were uncomfortable with so much tar archive magic. However if this is viewed as the best/simplest solution to this issue then I think they may be more willing to accept it. What was eventually agreed on was a similar solution that you can see here: https://github.com/dmcgowan/docker/commit/578b1521df85eae8a6205118131751c631323ba5#diff-3a1632a75e011091e0bae6f8c8435fd2R537 I don't think this needs to be modified all that much much to make it work the way you described, and we can just skip the local context preparation.

**Comment by thaJeztah** [comment] 2015-10-18 21:56
Alternatively, https://github.com/docker/docker/issues/9731 or https://github.com/docker/docker/issues/9844 should be reconsidered

**Comment by loa** [comment] 2015-10-20 08:35
Now also affects builds on Travis CI

```
unable to prepare context: unable to extract stdin to temporary context direcotry: lchown /tmp/docker-build-context-084386948/hello: operation not permitted
```

**Comment by phemmer** [comment] 2015-11-02 14:53
Can we get this tagged as **BUG**? Would also be nice to get it on a milestone.

**Comment by cpuguy83** [comment] 2015-11-02 15:15
+kind/bug

**Comment by cpuguy83** [comment] 2015-11-02 15:17
Evidently the bought isn't doing it's thing anymore?

**Comment by thaJeztah** [comment] 2015-11-04 10:18
ping @anusha-ragunathan I think you were looking into this; can you discuss with @tiborvass if this can be added to a milestone (and which one)? thanks!

**Comment by thaJeztah** [comment] 2015-11-04 21:31
I discussed this internally and, yes, this is a regression, but 1.9.1 is too soon to get this fixed, 1.10 is more realistic.

**Comment by karlgrz** [comment] 2015-11-18 19:55
+1, still present in 1.9. I can't upgrade until that's fixed.

**Comment by posita** [comment] 2015-11-21 00:17
FYI, this definitely kills Circle (they use 1.8+). :angry: I think Codeship is affected as well?

**Comment by lidel** [comment] 2015-12-11 19:39
A temporary workaround for Docker 1.8 / 1.9:
https://github.com/jamiemccrindle/dockerception#18-permissions-error

**Comment by icecrime** [comment] 2015-12-29 19:13
Ping @docker/security-team!

**Comment by posita** [comment] 2015-12-31 15:14
UPDATE: Circle has broken the ability to manually override Docker versions twice in the past two months. My aforementioned work-around can no longer be considered viable.

**Comment by posita** [comment] 2015-12-31 16:35
Having to do the kinds of gymnastics @lidel describes in his https://github.com/docker/docker/issues/15785#issuecomment-164030356 for a regression that has been identified since August does not seem reasonable, especially where the source of the problem appears to have been identified (see this https://github.com/docker/docker/pull/14546#issuecomment-148571518). Will a fix still be included in the next release? This appears to be frustrating `docker build -` builds on several CI platforms.

**Comment by calavera** [comment] 2016-01-05 21:20
Given that there is not a formal proposal to completely fix this issue, I think we should remove the context switch by default until we have a better solution.

I opened #19099 that fixes this issue for all builds with content trust disabled. Content Trust is not a completely supported feature yet, so we should be okay with having some issues there.

If #19099 is merged, all builds will work as expected as long as you don't have Content Trust enabled. This issue still remains if you have Content Trust enabled.

**Comment by phemmer** [comment] 2016-01-06 23:13
hehe, might want to reopen. Github tried to be smart.

> This PR does not fix #15785 but it mitigates its impact...

**Comment by thaJeztah** [comment] 2016-01-06 23:25
Hah, yes, I saw that one coming :-)

**Comment by thaJeztah** [comment] 2016-01-06 23:26
Hm, only might be confusing on the milestone, so perhaps we should remove the priority label now :/

**Comment by tonistiigi** [comment] 2016-01-12 02:49
I don't think #19099 changes this much because the problem doesn't seem to be the dockerfile rewriting but initial extraction from stdin or http to a temp directory. Extracting from URL isn't exactly safe as well so we should try to use the tar directly and modify the it on-the-fly(this is already done for dockerfile rewriting). The difficult thing about this seems to be handling `.dockerignore` as includes/excludes are currently built in features in the package we use to make tarballs. Either we need to reimplement all this logic with tar parsing as well or I think better alternative would be just not to support these features if user specifies the tar. I think trust path is the only modification we should support in the user specified tar as this is the only one user can't control.

**Closed** 2016-01-13 19:17 UTC
Labels: group/trust, kind/bug
