### ISSUE TITLE
Network called "none" when using "docker network ls"

### ISSUE THREAD

**Issue by florenthemmi** [docker/docker#30364] opened 2017-01-23 13:00 UTC
**Description**
I have noticed there is a network called "none" when listing all available networks. Is it normal?
I try to delete it but this cannot be remove because it is marked as a default one by docker.

**Steps to reproduce the issue:**
1. `docker network ls`
2. `docker network rm none`

Response: `Error response from daemon: none is a pre-defined network and cannot be removed`

**Describe the results you received:**
I try to inspect the network (`docker network inspect none`). The output:

```
[
    {
        "Name": "none",
        "Id": "674276f7558675d8cdf33dd92809e1af4ee3239171f6cea4e8c4e29ccd35b6a0",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "local",
        "Driver": "null",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
```

**Describe the results you expected:**
This network has no driver and the created date is not a valid one.
Is this network useful. Can I remove it?

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 15
 Running: 15
 Paused: 0
 Stopped: 0
Images: 100
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-2230280-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.966 GB
 Data Space Total: 107.4 GB
 Data Space Available: 39.13 GB
 Metadata Space Used: 9.527 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Kernel Version: 4.8.3-std-1
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: lancelot
ID: 3QM4:6TXA:JQWC:P6IY:ZH4C:WDAM:N77P:TJ6K:WLAY:5PMF:44X2:45TF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-01-23 14:04
> Is this network useful.

`docker run --network=none ...` creates a container without network access, which can be useful.

>  Can I remove it?

No, as the error message says; pre-defined networks cannot be removed

I'm closing this issue because this is not a bug, but feel free to comment after I closed.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

**Closed by thaJeztah** 2017-01-23 14:04 UTC
Labels: area/networking, version/1.13

**Comment by florenthemmi** [comment] 2017-01-23 14:06
Thanks for your quick reply. Is there is an article about this in the documentation?
When I see it, it was not clear it is a docker network without network access.

**Comment by thaJeztah** [comment] 2017-01-23 14:14
It's documented in the `docker run` reference; https://docs.docker.com/engine/reference/run/#/network-none

It should also be documented in the [`docker run` command-line reference]https://github.com/docker/docker/blob/v1.13.0/docs/reference/commandline/run.md); but that part has gone missing on docs.docker.com (perhaps you can open an issue about that in the documentation issue tracker; https://github.com/docker/docker.github.io/issues)?

```
      --network string              Connect a container to a network
                                    'bridge': create a network stack on the default Docker bridge
                                    'none': no networking
                                    'container:<name|id>': reuse another container's network stack
                                    'host': use the Docker host network stack
                                    '<network-name>|<network-id>': connect to a user-defined network
```

**Comment by bkline** [comment] 2020-04-10 11:41
The docs are still misleading:

```
$ docker network prune
WARNING! This will remove all networks not used by at least one container.
Are you sure you want to continue? [y/N] y
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
83381d6b7187        bridge              bridge              local
185280ce5366        host                host                local
f3352948d546        none                null                local
```

**Comment by thaJeztah** [comment] 2020-04-10 11:47
@bkline perhaps it should mention "custom networks"; let me open a PR

**Comment by thaJeztah** [comment] 2020-04-10 11:48
PR is up: https://github.com/docker/cli/pull/2432

**Comment by bkline** [comment] 2020-04-10 11:53
That was astounding! I don't think I've ever seen such a lightning-fast turnaround unless the developer involved was sitting at the next desk. 🥇

**Comment by thaJeztah** [comment] 2020-04-10 14:28
😂 I happened to have the code open in my editor, so thought I'd just as well make the change before I forget it 😊

**Comment by bkline** [comment] 2020-04-10 15:32
Brings "agile" to a completely new level. 💯

**Comment by Ruslan27032000** [comment] 2022-09-29 23:52
I found a solution. If you use Ubuntu you can change `/etc/docker/daemon.json` file following [this](https://danielbkr.net/amp/could-not-find-an-available-ip-address-pool/) article.
