### ISSUE TITLE
Control subnet choose by Docker when create bridge without subnet parameter

### ISSUE THREAD

**Issue by david-maumenee** [docker/docker#27818] opened 2016-10-27 08:13 UTC
**Description**

I'am facing ip conflict with my enterprise network, when i let Docker creating a network with it's default strategy.

By default :
1 - Docker0 IP configuration is 
```
Docker0
inet 172.17.0.1  netmask 255.255.0.0
```
2 - When an another bridge network is created (with command line **_docker network create_** or with docker compose) the "NEXT" available sub network is used : 
```
br-xxxxx
inet 172.18.0.1  netmask 255.255.0.0
```

Since 172.18.x.x is used on my company, there is an IP Conflict

I tried to solve my problem with Docker0 IP customization

**Steps to reproduce the issue:**
1 - customize Docker0 subnet with the deamon "bip" parameter with "192.170.0.1/24"
```
Docker0
inet 192.170.0.1  netmask 255.255.255.0
```
2 - create a new bridge network with docker network create mynetwork

**Describe the results you received:**
The new network characteristics are : 
```
br-xxxxx
inet 172.17.0.1  netmask 255.255.0.0
```

**Describe the results you expected:**
The subnet of "mynetwork" should be the next available subnet based on Docker0 configration.
```
br-xxxxx
inet 192.170.1.1  netmask 255.255.255.0
```

A another solution is to add a new daemon parameter to set the first subnet created with docker network create command. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64
```

**Comment by justincormack** [comment] 2016-10-27 09:51
You can specify the IP range when you do `docker network create` see https://docs.docker.com/engine/reference/commandline/network_create/

**Comment by david-maumenee** [comment] 2016-10-27 10:06
Thanks for your response
It's the workaround i have used.
But i would like to deploy many docker-compose application, and i don't want to have to manage the subnet of each network when i deploy a new app. But just specif the first subnet to use by the docker network creation strategy.
I agree it's more a feature request than a bug report.

**Comment by cpuguy83** [comment] 2016-10-27 14:00
This is certainly a dup of another request.
But the idea would be to specify the range to use (also the default subnet size) on the daemon config.

**Comment by aboch** [comment] 2016-10-27 20:16
This is dupe of #21776  (I already suggested its submitter to change the description).

**Comment by thaJeztah** [comment] 2016-10-28 00:25
Thanks for opening @david-maumenee, I'll close this one, but subscribe to https://github.com/docker/docker/issues/21776 to stay informed on updates

**Closed by thaJeztah** 2016-10-28 00:25 UTC
Labels: area/networking, kind/enhancement, version/1.12

**Comment by david-maumenee** [comment] 2016-10-28 06:25
Thanks for your reponses, it was very fast !
Hope that [#21776](https://github.com/docker/docker/issues/21776) wil be included in the next version, despite it is not yet planned.
