### ISSUE TITLE
Leader selection fails in swarm mode after 2 manager fails(out of 3)

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/docker#25275] opened 2016-08-01 04:35 UTC
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 1
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: active
 NodeID: 8n7vxcbcyaogpotofz0mdw775
 Error: rpc error: code = 2 desc = raft: no elected cluster leader
 Is Manager: true
 ClusterID:
 Managers: 0
 Nodes: 0
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot interval: 0
  Heartbeat tick: 0
  Election tick: 0
 Dispatcher:
  Heartbeat period: Less than a second
 CA configuration:
  Expiry duration: Less than a second
 Node Address: 192.168.99.102
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.16-boot2docker
Operating System: Boot2Docker 1.12.0 (TCL 7.2); HEAD : e030bab - Fri Jul 29 00:29:14 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: manager3
ID: WAX5:FKRO:JHDR:JGUL:DMWI:HAAJ:WJQZ:OXEE:Z6KO:LW2E:TRJ4:22CV
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 45
 Goroutines: 108
 System Time: 2016-08-01T02:29:51.067828385Z
 EventsListeners: 0
Http Proxy: http://proxy.rdh.ecl.ntt.co.jp:20066
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 7 and Virtualbox using docker-machine 8 (Docker toolbox-1.12)

**Steps to reproduce the issue:**

While trying to reproduce issue from https://gist.github.com/thaJeztah/1599b09b41e696837235f2509df5ade1

- Create 4 node swarm cluster

```
$ docker-machine ls
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
manager1   -        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.0
manager2   -        virtualbox   Running   tcp://192.168.99.101:2376           v1.12.0
manager3   -        virtualbox   Running   tcp://192.168.99.102:2376           v1.12.0
worker1    -        virtualbox   Running   tcp://192.168.99.103:2376           v1.12.0
```

-  3 manager nodes and 1 worker.

```
$ docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
6bium6j9vfakmbubvjbf4j66w    manager2  Ready   Active        Reachable
8n7vxcbcyaogpotofz0mdw775    manager3  Ready   Active        Reachable
bsrnkrlx8hq2mulelr7lgzz6d    worker1   Ready   Active
e1v6jgo7zurvievbd5d00g40m *  manager1  Ready   Active        Leader
```
3. Create 16 instances of service web

```
$ docker service create --name web --replicas 16 -p 80:80 nginx:alpine
9577ho994m0on115kcps1mlya

$ docker service ps web
ID                         NAME    IMAGE         NODE      DESIRED STATE  CURRENT STATE               ERROR
ag84if7d8il0smruu38w6r4ev  web.1   nginx:alpine  worker1   Running        Running about a minute ago
brqjb2lvns6qh6iho8p7tejh3  web.2   nginx:alpine  manager1  Running        Running about a minute ago
5eivlvn8tno0crpbakxkcnbjo  web.3   nginx:alpine  manager1  Running        Running about a minute ago
cti8o2opgde1fnk3346xm68ns  web.4   nginx:alpine  worker1   Running        Running about a minute ago
624ecy5rqqemc39rgxpigmr3z  web.5   nginx:alpine  manager2  Running        Running about a minute ago
2p67qlwmgu8jeta659dnjeeo1  web.6   nginx:alpine  manager1  Running        Running about a minute ago
2184u3b5xjkpzudg8pqbfgltf  web.7   nginx:alpine  manager2  Running        Running about a minute ago
c13yyi6mqx9njznpo0jvhgrv4  web.8   nginx:alpine  manager3  Running        Running about a minute ago
870tr5md5wuk1urbrdujd57ew  web.9   nginx:alpine  manager3  Running        Running about a minute ago
0c3668l5ftwxe5tc0p4zf71xl  web.10  nginx:alpine  manager2  Running        Running about a minute ago
f2e0w096omdimi1zc1povhdd5  web.11  nginx:alpine  worker1   Running        Running about a minute ago
anpzp22znwtkcal56uyjqnnqw  web.12  nginx:alpine  manager2  Running        Running about a minute ago
4mknfdetsgorc1cm2gil2o8k4  web.13  nginx:alpine  manager1  Running        Running about a minute ago
4oqnpqgfmauf7igc4jvw3k82x  web.14  nginx:alpine  manager3  Running        Running about a minute ago
96l3pf9iefcxhatk46cz66zc5  web.15  nginx:alpine  worker1   Running        Running about a minute ago
9b3g0o6faezwdhvcvfb38js0z  web.16  nginx:alpine  manager3  Running        Running about a minute ago
```

- Remove Leader of swarm

```
$ docker-machine rm manager1
About to remove manager1
Are you sure? (y/n): y
Successfully removed manager1

$  eval $(docker-machine env manager2)

$ docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
6bium6j9vfakmbubvjbf4j66w *  manager2  Ready   Active        Leader
8n7vxcbcyaogpotofz0mdw775    manager3  Ready   Active        Reachable
bsrnkrlx8hq2mulelr7lgzz6d    worker1   Ready   Active
e1v6jgo7zurvievbd5d00g40m    manager1  Down    Active        Unreachable
```

- Remove second leader of swarm

```
$ docker-machine rm manager2
About to remove manager2
Are you sure? (y/n): y
Successfully removed manager2
```
- No leader is selected.
```
$  eval $(docker-machine env manager3)

$ docker node ls
Error response from daemon: rpc error: code = 2 desc = raft: no elected cluster leader
$ docker-machine ls
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
manager3   *        virtualbox   Running   tcp://192.168.99.102:2376           v1.12.0
worker1    -        virtualbox   Running   tcp://192.168.99.103:2376           v1.12.0
```

**Describe the results you received:**
No Leader was elected, even with one manager in swarm.

**Describe the results you expected:**
The last manager should get selected as leader

**Additional information you deem important (e.g. issue happens only occasionally):**
I am able to reproduce on every-time on my machine.

**Comment by thaJeztah** [comment] 2016-08-01 09:52
This is not a bug but the way RAFT works; decisions can only be made if a majority of the managers reach consensus. In a three-node raft (three managers), that means 2/3. Of two managers are down, a majority can never be reached, so a leader cannot be selected (also see https://docs.docker.com/engine/swarm/admin_guide/)

In a situation with 3 managers, you have a fault tolerance of 1; one manager can go down without disrupting the swarm

**Comment by thaJeztah** [comment] 2016-08-01 09:54
Thanks for reproducing my issue though!

I'll close this issue, because this one is not a bug, but feel free to continue the discussion :+1:

**Closed by thaJeztah** 2016-08-01 09:54 UTC
Labels: version/1.12

**Comment by kunalkushwaha** [comment] 2016-08-02 04:30
Thanks for explanation :)

**Comment by gittycat** [comment] 2016-08-05 00:34
@thaJeztah I have a 3 node "swarm mode" under VMware fusion on my laptop for development. I've noticed that when the laptop comes back from sleep, I get the same "no elected cluster leader" even though all three nodes are shown as Running. Is this the desired behaviour? I would assume that whenever 3 nodes are running, the cluster should have a leader, no matter how it got started/restarted. Actually, the same goes to 2 nodes. The cluster should have a leader then.

All goes back to normal if I restart all three nodes.

**Comment by thaJeztah** [comment] 2016-08-05 09:59
@gittycat looks like a different issue; we are working on a number of improvements for leader election in case the leader goes down (or, as in your case, all nodes go down), however, make sure that you use the `--advertise-addr` when initializing the swarm; if the VM has multiple network interfaces, a different interface may be selected on reboot, which may be an issue then. Also be aware that managers must have a static IP, otherwise the workers are no longer able to connect if the IP address changes.

**Comment by blalagit** [comment] 2023-01-25 15:23
> This is not a bug but the way RAFT works; decisions can only be made if a majority of the managers reach consensus. In a three-node raft (three managers), that means 2/3. If two managers are down, a majority can never be reached, so a leader cannot be selected (also see https://docs.docker.com/engine/swarm/admin_guide/)
> 
> In a situation with 3 managers, you have a fault tolerance of 1; one manager can go down without disrupting the swarm

I understand it, but I did not understand how happen the election when leader master went dow. Because there are remaining two manager in reachable status. How the RAFT decide which one will be leader and which one stay reachable? Two nodes, no majority!

**Comment by thaJeztah** [comment] 2023-01-26 12:10
If you have 3 managers, and one went down, the cluster still has 3 managers registered (but one is unreachable). In that case the 2 remaining managers still have a majority (2/3).

**Comment by blalagit** [comment] 2023-01-26 12:13
Thank you!

Sebastiaan van Stijn ***@***.***> ezt írta (időpont: 2023.
jan. 26., Cs 13:10):
