### ISSUE TITLE
dockerd can't be compiled successfully for GOOS=linux GOARCH=ppc64

### ISSUE THREAD

**Issue by xiayuhai** [docker/docker#23894] opened 2016-06-23 07:22 UTC
> \# docker:master
> cd $GOPATH/src/github.com/docker/docker
> export GOPATH=$PWD/vendor:$GOPATH
> GOARCH=ppc64 go build ./cmd/dockerd

--------------------------------------------------
error：
> \# github.com/docker/docker/pkg/devicemapper
> pkg/devicemapper/devmapper.go:85: undefined: cdmTask
> \# github.com/docker/docker/pkg/loopback
> pkg/loopback/attach_loopback.go:21: undefined: LoNameSize
> pkg/loopback/attach_loopback.go:21: invalid array bound LoNameSize
> pkg/loopback/attach_loopback.go:22: undefined: LoNameSize
> pkg/loopback/attach_loopback.go:22: invalid array bound LoNameSize
> pkg/loopback/ioctl.go:25: undefined: loopInfo64
> pkg/loopback/ioctl.go:39: undefined: loopInfo64

-----------------------------------------------------
maybe it's a bug

**Comment by houstar** [comment] 2016-06-28 07:48
@xiayuhai  I have the same problem with you and following the information in here.
[root  ]# go version
go version go1.6.2 linux/ppc64

So I think maybe the root cause in here
 The go-1.6.2 compiler seems not fully supported ppc64 architecture. This needs to be check with golang upstream. Meanwhile, Have you tired with go-1.7.0-rc2 compiler on ppc64 ?

**Comment by houstar** [comment] 2016-06-28 08:07
Full build log.
>>> Emerging (1 of 1) app-emulation/docker-1.11.0::gentoo
>>> Downloading 'http://distfiles.gentoo.org/distfiles/docker-1.11.0.tar.gz'
--2016-06-28 15:32:17--  http://distfiles.gentoo.org/distfiles/docker-1.11.0.tar.gz
Resolving distfiles.gentoo.org (distfiles.gentoo.org)... 216.165.129.135, 64.50.233.100, 64.50.236.52, ...
Connecting to distfiles.gentoo.org (distfiles.gentoo.org)|216.165.129.135|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10637394 (10M) [application/x-gzip]
Saving to: '/usr/portage/distfiles/docker-1.11.0.tar.gz'

100%[======================================>] 10,637,394  2.08MB/s   in 5.1s   

2016-06-28 15:32:23 (2.01 MB/s) - '/usr/portage/distfiles/docker-1.11.0.tar.gz' saved [10637394/10637394]

 * docker-1.11.0.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                                                                [ ok ]
 * Determining the location of the kernel source code
 * Unable to find kernel sources at /usr/src/linux
 * Please make sure that /usr/src/linux points at your running kernel, 
 * (or the kernel you wish to build against).
 * Alternatively, set the KERNEL_DIR environment variable to the kernel sources location
 * Unable to calculate Linux Kernel version for build, attempting to use running version
 * 
 * There is a serious Docker-related kernel panic that has been fixed in 3.16+
 *   (and was backported to 3.15.5+, 3.14.12+, and 3.12.25+)
 * 
 * See also https://github.com/docker/docker/issues/2960
 * Unable to check for the following kernel config options due
 * to absence of any configured kernel sources or compiled
 * config:
 *  - NAMESPACES
 *  - NET_NS
 *  - PID_NS
 *  - IPC_NS
 *  - UTS_NS
 *  - DEVPTS_MULTIPLE_INSTANCES
 *  - CGROUPS
 *  - CGROUP_CPUACCT
 *  - CGROUP_DEVICE
 *  - CGROUP_FREEZER
 *  - CGROUP_SCHED
 *  - CPUSETS
 *  - MEMCG
 *  - KEYS - CONFIG_KEYS: is mandatory, see bug 581348
 *  - MACVLAN
 *  - VETH
 *  - BRIDGE
 *  - BRIDGE_NETFILTER
 *  - NF_NAT_IPV4
 *  - IP_NF_FILTER
 *  - IP_NF_TARGET_MASQUERADE
 *  - NETFILTER_XT_MATCH_ADDRTYPE
 *  - NETFILTER_XT_MATCH_CONNTRACK
 *  - NF_NAT
 *  - NF_NAT_NEEDED
 *  - POSIX_MQUEUE
 *  - MEMCG_KMEM - CONFIG_MEMCG_KMEM: is optional
 *  - MEMCG_SWAP - CONFIG_MEMCG_SWAP: is required if you wish to limit swap usage of containers
 *  - MEMCG_SWAP_ENABLED
 *  - BLK_CGROUP - CONFIG_BLK_CGROUP: is optional for container statistics gathering
 *  - IOSCHED_CFQ - CONFIG_IOSCHED_CFQ: is optional for container statistics gathering
 *  - CGROUP_PERF - CONFIG_CGROUP_PERF: is optional for container statistics gathering
 *  - CGROUP_HUGETLB
 *  - NET_CLS_CGROUP
 *  - CFS_BANDWIDTH - CONFIG_CFS_BANDWIDTH: is optional for container statistics gathering
 *  - FAIR_GROUP_SCHED
 *  - RT_GROUP_SCHED
 *  - RESOURCE_COUNTERS - CONFIG_RESOURCE_COUNTERS: is optional for container statistics gathering
 *  - NETPRIO_CGROUP
 *  - BLK_DEV_DM
 *  - DM_THIN_PROVISIONING
 *  - EXT4_FS
 *  - EXT4_FS_POSIX_ACL
 *  - EXT4_FS_SECURITY
 * You're on your own to make sure they are set if needed.
 * Adding group 'docker' to your system ...
 *  - Groupid: next available
/var/tmp/portage/app-emulation/docker-1.11.0/temp/environment: line 128: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
>>> Unpacking source...
>>> Source unpacked in /var/tmp/portage/app-emulation/docker-1.11.0/work
/var/tmp/portage/app-emulation/docker-1.11.0/temp/environment: line 128: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
>>> Preparing source in /var/tmp/portage/app-emulation/docker-1.11.0/work/docker-1.11.0 ...
 * Applying docker-containerd.patch ...                                                                                                                                                                     [ ok ]
>>> Source prepared.
/var/tmp/portage/app-emulation/docker-1.11.0/temp/environment: line 128: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
>>> Configuring source in /var/tmp/portage/app-emulation/docker-1.11.0/work/docker-1.11.0 ...
>>> Source configured.
/var/tmp/portage/app-emulation/docker-1.11.0/temp/environment: line 128: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
>>> Compiling source in /var/tmp/portage/app-emulation/docker-1.11.0/work/docker-1.11.0 ...
# WARNING! I don't seem to be running in a Docker container.
# The result of this command might be an incorrect build, and will not be
# officially supported.
#
# Try this instead: make all
#

---> Making bundle: dynbinary (in bundles/1.11.0/dynbinary)
Building: bundles/1.11.0/dynbinary/docker-1.11.0
# github.com/vishvananda/netns
vendor/src/github.com/vishvananda/netns/netns_linux.go:29: undefined: SYS_SETNS
# github.com/docker/docker/pkg/devicemapper
pkg/devicemapper/devmapper.go:85: undefined: cdmTask
# github.com/docker/docker/pkg/loopback
pkg/loopback/attach_loopback.go:21: undefined: LoNameSize
pkg/loopback/attach_loopback.go:21: invalid array bound LoNameSize
pkg/loopback/attach_loopback.go:22: undefined: LoNameSize
pkg/loopback/attach_loopback.go:22: invalid array bound LoNameSize
pkg/loopback/attach_loopback.go:119: undefined: loopInfo64
pkg/loopback/ioctl.go:11: undefined: LoopCtlGetFree
pkg/loopback/ioctl.go:19: undefined: LoopSetFd
pkg/loopback/ioctl.go:25: undefined: loopInfo64
pkg/loopback/ioctl.go:26: undefined: LoopSetStatus64
pkg/loopback/ioctl.go:39: undefined: loopInfo64
pkg/loopback/ioctl.go:26: too many errors
 * ERROR: app-emulation/docker-1.11.0::gentoo failed (compile phase):
 *   dynbinary failed
 * 
 * Call stack:
 *     ebuild.sh, line 133:  Called src_compile
 *   environment, line 3267:  Called die
 * The specific snippet of code:
 *       ./hack/make.sh dynbinary || die 'dynbinary failed';
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/docker-1.11.0::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/docker-1.11.0::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/app-emulation/docker-1.11.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-emulation/docker-1.11.0/temp/environment'.
 * Working directory: '/var/tmp/portage/app-emulation/docker-1.11.0/work/docker-1.11.0/src/github.com/docker/docker'
 * S: '/var/tmp/portage/app-emulation/docker-1.11.0/work/docker-1.11.0'
/var/tmp/portage/app-emulation/docker-1.11.0/temp/environment: line 128: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory

>>> Failed to emerge app-emulation/docker-1.11.0, Log file:

>>>  '/var/tmp/portage/app-emulation/docker-1.11.0/temp/build.log'

 * Messages for package app-emulation/docker-1.11.0:

 * Unable to find kernel sources at /usr/src/linux
 * Unable to calculate Linux Kernel version for build, attempting to use running version
 * 
 * There is a serious Docker-related kernel panic that has been fixed in 3.16+
 *   (and was backported to 3.15.5+, 3.14.12+, and 3.12.25+)
 * 
 * See also https://github.com/docker/docker/issues/2960
 * Unable to check for the following kernel config options due
 * to absence of any configured kernel sources or compiled
 * config:
 *  - NAMESPACES
 *  - NET_NS
 *  - PID_NS
 *  - IPC_NS
 *  - UTS_NS
 *  - DEVPTS_MULTIPLE_INSTANCES
 *  - CGROUPS
 *  - CGROUP_CPUACCT
 *  - CGROUP_DEVICE
 *  - CGROUP_FREEZER
 *  - CGROUP_SCHED
 *  - CPUSETS
 *  - MEMCG
 *  - KEYS - CONFIG_KEYS: is mandatory, see bug 581348
 *  - MACVLAN
 *  - VETH
 *  - BRIDGE
 *  - BRIDGE_NETFILTER
 *  - NF_NAT_IPV4
 *  - IP_NF_FILTER
 *  - IP_NF_TARGET_MASQUERADE
 *  - NETFILTER_XT_MATCH_ADDRTYPE
 *  - NETFILTER_XT_MATCH_CONNTRACK
 *  - NF_NAT
 *  - NF_NAT_NEEDED
 *  - POSIX_MQUEUE
 *  - MEMCG_KMEM - CONFIG_MEMCG_KMEM: is optional
 *  - MEMCG_SWAP - CONFIG_MEMCG_SWAP: is required if you wish to limit swap usage of containers
 *  - MEMCG_SWAP_ENABLED
 *  - BLK_CGROUP - CONFIG_BLK_CGROUP: is optional for container statistics gathering
 *  - IOSCHED_CFQ - CONFIG_IOSCHED_CFQ: is optional for container statistics gathering
 *  - CGROUP_PERF - CONFIG_CGROUP_PERF: is optional for container statistics gathering
 *  - CGROUP_HUGETLB
 *  - NET_CLS_CGROUP
 *  - CFS_BANDWIDTH - CONFIG_CFS_BANDWIDTH: is optional for container statistics gathering
 *  - FAIR_GROUP_SCHED
 *  - RT_GROUP_SCHED
 *  - RESOURCE_COUNTERS - CONFIG_RESOURCE_COUNTERS: is optional for container statistics gathering
 *  - NETPRIO_CGROUP
 *  - BLK_DEV_DM
 *  - DM_THIN_PROVISIONING
 *  - EXT4_FS
 *  - EXT4_FS_POSIX_ACL
 *  - EXT4_FS_SECURITY
 * You're on your own to make sure they are set if needed.
 * ERROR: app-emulation/docker-1.11.0::gentoo failed (compile phase):
 *   dynbinary failed
 * 
 * Call stack:
 *     ebuild.sh, line 133:  Called src_compile
 *   environment, line 3267:  Called die
 * The specific snippet of code:
 *       ./hack/make.sh dynbinary || die 'dynbinary failed';
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/docker-1.11.0::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/docker-1.11.0::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/app-emulation/docker-1.11.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-emulation/docker-1.11.0/temp/environment'.
 * Working directory: '/var/tmp/portage/app-emulation/docker-1.11.0/work/docker-1.11.0/src/github.com/docker/docker'
 * S: '/var/tmp/portage/app-emulation/docker-1.11.0/work/docker-1.11.0

**Comment by xiayuhai** [comment] 2016-06-30 06:23
@houstar 
the reason of undefined error is CGO_ENABLED=0 on ppc64, but CGO_ENABLED=1 on ppc64le and amd64;
> on ppc64 machine
> CGO_ENABLED=1 go build ./cmd/dockerd 

but the errror changed
> go version go1.7beta2 linux/ppc64
> link: $WORK/net.a(_go_.o): cannot use dynamic imports with -d flag
> ...

**Comment by houstar** [comment] 2016-06-30 09:35
@xiayuhai 

I'm sure that go-1.6 not support CGO_ENABLED=1 on ppc64. i.e. Can't external link with other library such as C/C++.  See further information in [link]https://github.com/golang/go/issues/13192

On Linux on little-endian 64-bit PowerPC (linux/ppc64le), Go 1.6 now supports cgo with external linking and is roughly feature complete. So you can built with CGO_ENABLED=1. Thanks.

**Comment by justincormack** [comment] 2016-10-11 23:35
We only support ppc64le at present; this works fine, and we do not any longer support cgo builds, so I am going to close this as there has been no activity.

**Closed by justincormack** 2016-10-11 23:35 UTC
