### ISSUE TITLE
ZFS failed to register layer dataset does not exist

### ISSUE THREAD

**Issue by chrishoage** [docker/docker#30993] opened 2017-02-14 00:20 UTC
**Description**
Trying to pull some images (I'm still unsure why some work and other do not) result in the following error 
```
failed to register layer: exit status 2: "/sbin/zfs zfs snapshot pond/docker/4522c1adffaf266062442dba2eb347084d774267a124d1bd7a04e6b3cb9634f0@371563767" => cannot open 'pond/docker/4522c1adffaf266062442dba2eb347084d774267a124d1bd7a04e6b3cb9634f0': dataset does not exist
usage:
	snapshot|snap [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
```

Not all images have this problem

```
› docker image pull nginx
Using default tag: latest
latest: Pulling from library/nginx
5040bd298390: Already exists
333547110842: Pull complete
4df1e44d2a7a: Pull complete
Digest: sha256:f2d384a6ca8ada733df555be3edc427f2e5f285ebf468aae940843de8cf74645
Status: Downloaded newer image for nginx:latest
```

```
› docker image pull nginx:alpine
alpine: Pulling from library/nginx
b7f33cc0b48e: Already exists
9a57e9207914: Pull complete
79f62f9c7236: Pull complete
50a2334db9bc: Pull complete
Digest: sha256:d34e2176dab830485b0cb79340e1d5ebf7d530b34ad7bfe05d269ffed20a88f4
Status: Downloaded newer image for nginx:alpine
```

But others do 

```
› docker image pull cantino/huginn
Using default tag: latest
latest: Pulling from cantino/huginn
c60055a51d74: Already exists
755da0cdb7d2: Already exists
969d017f67e6: Already exists
37c9a9113595: Already exists
a3d9f8479786: Already exists
d7d0c2c8ec3c: Extracting [==================================================>]    783 B/783 B
3480f3638ec5: Download complete
dc00c829c370: Download complete
52c5f6110241: Download complete
65f3a34b31c0: Download complete
4970b4c36b25: Download complete
df6da8726ead: Download complete
236e60444501: Download complete
94fb09e7b96d: Download complete
aac028a46934: Download complete
c78dd42f78d9: Download complete
failed to register layer: exit status 2: "/sbin/zfs zfs snapshot pond/docker/4522c1adffaf266062442dba2eb347084d774267a124d1bd7a04e6b3cb9634f0@371563767" => cannot open 'pond/docker/4522c1adffaf266062442dba2eb347084d774267a124d1bd7a04e6b3cb9634f0': dataset does not exist
usage:
	snapshot|snap [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
```

**Steps to reproduce the issue:**
1. Ensure you are using docker with the zfs driver
2. Pull an image (`cantino/huginn`)
3. Observe ZFS error

**Describe the results you received:**
A `dataset does not exist` error for trying to create a snapshot off a dataset that did not exist.

**Describe the results you expected:**
The dataset to be created correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**
The two images I've had this happen on so far are `plexinc/pms-docker:plexpass`, `plexinc/pms-docker:public`, `cantino/huginn`. As the output above shows, `nginx` and friends do not have this issue.

**Output of `docker version`:**

```
› docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
› docker info
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 1.13.1
Storage Driver: zfs
 Zpool: pond
 Zpool Health: ONLINE
 Parent Dataset: pond/docker
 Space Used By Parent: 1008901120
 Space Available: 501376187904
 Parent Quota: no
 Compression: lz4
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.32 GiB
Name: cortex
ID: ZHTI:AFNB:DZ56:WQ2P:VSZL:5EWB:NLLR:4Q3M:4YWV:NV4C:J52R:UFKK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Ubuntu 16.04 with ZFS on Linux

**Comment by chrishoage** [comment] 2017-02-18 19:19
Is it possible to move from the zfs drive back to whatever the default is? How might I do that? 

Or is there a way to work around this issue? The only way I've found so far is to manually build the `Dockerfile`s myself, which is becoming cumbersome.

**Comment by thaJeztah** [comment] 2017-03-06 21:43
There's no option to "migrate" between graph drivers. You can select a different driver but in that case the directory for the other storage driver is no longer used, so you won't see the images, and containers that are stored there.

You _can_ `docker save` / `docker load` images to/from a tar, but using a registry is probably better to use.

ping @Mic92 any hints/tips?

**Comment by Mic92** [comment] 2017-03-06 22:39
Is this error reproducible? What happens if you do

```
$ docker image rm cantino/huginn
$ docker image pull cantino/huginn
```

**Comment by chrishoage** [comment] 2017-03-06 22:42
Yes, it appears to be reproducible (for me, at least) 

```
root at cortex in ~
› docker image rm cantino/huginn
Error response from daemon: No such image: cantino/huginn:latest

root at cortex in ~
› docker image pull cantino/huginn
Using default tag: latest
latest: Pulling from cantino/huginn
c60055a51d74: Already exists
755da0cdb7d2: Already exists
969d017f67e6: Already exists
37c9a9113595: Already exists
a3d9f8479786: Already exists
384b3b4cb5cf: Extracting [==================================================>]    785 B/785 B
d98116afa534: Download complete
7bd4314eae67: Download complete
7ac46a036355: Download complete
d23c4848e4ca: Download complete
f769154fe27e: Download complete
23ccccfffa5b: Download complete
58e3e000926e: Download complete
c5fad6bc68fc: Download complete
a9a2dda200f2: Download complete
dd54a91f627c: Download complete
failed to register layer: exit status 2: "/sbin/zfs zfs snapshot pond/docker/4522c1adffaf266062442dba2eb347084d774267a124d1bd7a04e6b3cb9634f0@663369117" => cannot open 'pond/docker/4522c1adffaf266062442dba2eb347084d774267a124d1bd7a04e6b3cb9634f0': dataset does not exist
usage:
	snapshot|snap [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
```

**Comment by Mic92** [comment] 2017-03-06 23:00
Ok. In this case I would need the debugging output of the docker daemon. It can be enabled by adding `-D` to DOCKER_OPTS in `/etc/default/docker` as described here: https://docs.docker.com/engine/admin/#configuring-docker

You have seem to configured a different logging driver (`json-file`), so you probably know how to obtain it.

**Comment by thaJeztah** [comment] 2017-03-06 23:05
for ubuntu 14.04, that configuration file is not used. Using a daemon.json file is probably easiest; see https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file

the file just needs to look like this, if you have no other options set 
```json
{"debug":true}
```

**Comment by Mic92** [comment] 2017-03-06 23:06
Ubuntu 16.04.2 LTS is used here.

**Comment by chrishoage** [comment] 2017-03-06 23:07
> You have seem to configured a different logging driver (json-file), so you probably know how to obtain it.

I actually (at least not intentionally) didn't configure that logging driver myself. As far as I knew that was default. Is it not? 

I am working on obtaining logs at this moment.

**Comment by thaJeztah** [comment] 2017-03-06 23:12
> Ubuntu 16.04.2 LTS is used here

ugh, sorry, that's what I meant, 16.04, sorry, typing on phone

**Comment by Mic92** [comment] 2017-03-06 23:13
@chrishoage `journalctl -u docker.service` should work on your ubuntu version. `json-file` was for containers, which is not relevant here.

**Comment by chrishoage** [comment] 2017-03-06 23:23
Ok, I added `DOCKER_OPTS="-D"` to `/etc/default/docker`


I also added `"debug": true` to `/etc/docker/daemon.json` Just to be safe

Then I restarted docker with `service docker restart`

Then I collected the logs with `journalctl -u docker.service --no-pager > docker.log`

I have attached the logs below. 

Please let me know if there is any more data you would like me to collect. 
[docker.txt](https://github.com/docker/docker/files/822829/docker.txt)

**Comment by Mic92** [comment] 2017-03-06 23:42
Did you also trigger a `docker pull` after that?

**Comment by chrishoage** [comment] 2017-03-06 23:45
Yes I did 

```
Mar 06 15:17:08 cortex systemd[1]: Stopped Docker Application Container Engine.
Mar 06 15:17:08 cortex systemd[1]: Starting Docker Application Container Engine...

// .... then lots of debug logs 

Mar 06 15:18:02 cortex dockerd[17516]: time="2017-03-06T15:18:02.416817285-08:00" level=error msg="Error trying v2 registry: failed to register layer: exit status 2: \"/sbin/zfs zfs snapshot pond/docker/4522c1adffaf266062442dba2eb347084d774267a124d1bd7a04e6b3cb9634f0@372789632\" => cannot open 'pond/docker/4522c1adffaf266062442dba2eb347084d774267a124d1bd7a04e6b3cb9634f0': dataset does not exist\nusage:\n\tsnapshot|snap [-r] [-o property=value] ... <filesystem|volume>@<snap> ...\n\nFor the property list, run: zfs set|get\n\nFor the delegated permission list, run: zfs allow|unallow\n"
Mar 06 15:18:02 cortex dockerd[17516]: time="2017-03-06T15:18:02.416892052-08:00" level=error msg="Attempting next endpoint for pull after error: failed to register layer: exit status 2: \"/sbin/zfs zfs snapshot pond/docker/4522c1adffaf266062442dba2eb347084d774267a124d1bd7a04e6b3cb9634f0@372789632\" => cannot open 'pond/docker/4522c1adffaf266062442dba2eb347084d774267a124d1bd7a04e6b3cb9634f0': dataset does not exist\nusage:\n\tsnapshot|snap [-r] [-o property=value] ... <filesystem|volume>@<snap> ...\n\nFor the property list, run: zfs set|get\n\nFor the delegated permission list, run: zfs allow|unallow\n"
```

**Comment by chrishoage** [comment] 2017-03-07 00:40
@Mic92 Yeah I forgot to add a `,` the first time I added `"debug": true` to the json file. I fixed it then restarted the docker service. 

If you'd like me to clean the logs and re-run the tests with all the correct debug flags in place I am happy to do so. But I feel fairly confident I captured the debug logs during the event in question.

**Comment by Mic92** [comment] 2017-03-07 07:25
The error happens when zfs dataset was destroyed, without an update in the imagelayer of docker:

```
$ zfs destroy -R zroot/root/nixos/0368bc77be5e5db69270386d15137fb971a081590c5f436b21916da09d633c50
$ docker run nginx          
/nix/store/9glgvsw1i76lxzblwdlm659lv1bg065c-docker-1.13.1/libexec/docker/docker: Error response from daemon: exit status 2: "/nix/store/mddh2ffqi53f3sw96pj6v4f0mzn04lcd-zfs-user-0.6.5.9/bin/zfs zfs snapshot zroot/root/nixos/0368bc77be5e5db69270386d15137fb971a081590c5f436b21916da09d633c50@256866051" => cannot open 'zroot/root/nixos/0368bc77be5e5db69270386d15137fb971a081590c5f436b21916da09d633c50': dataset does not exist
usage:
        snapshot|snap [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow.
See '/nix/store/9glgvsw1i76lxzblwdlm659lv1bg065c-docker-1.13.1/libexec/docker/docker run --help'.
```

**Comment by chrishoage** [comment] 2017-03-07 16:29
is it possible to have docker re-create the dataset? 

Before I opened this ticket I tried to do a `zfs create` on the missing layer, but docker wouldn't repopulate it, it would just error. 

I very likely may have accidentally removed a dataset when cleaning up some auto-snapshots I didn't want to run. I just can't figure out how to recover from it.

**Comment by Mic92** [comment] 2017-03-07 20:13
@chrishoage at the moment you can only manually fix the inconsistencies in docker's image layer "database". The problem is, that docker thinks that this dataset exists as it is referenced in `/var/lib/docker/image/zfs/layerdb/sha256/<layer_sha256>/cache-id` in plain text. This directory (`/var/lib/docker/image/zfs/layerdb/sha256/<layer_sha256>/cache-id`) must be removed as well as all layers, where <layer_sha256> is the parent. All files in `layerdb` are json files or plain text so grep will work here. At last but not least you also need to remove any container file in `/var/lib/docker/containers/` which uses a layer you have just deleted as well as the corresponding mount in `/var/lib/docker/image/zfs/layerdb/mounts/`.

**Comment by chrishoage** [comment] 2017-03-07 20:53
> Update an alternative is to just build a new docker image, with different content. This will then get a different id.

That sounds like what I've been doing where I'm just building the `Dockerfile`, but I'd like to be able to use images from the docker hub. So it sounds like the images I have this problem with share a image/layer that was deleted. 

I'll try to follow your instructions above, hopefully I don't dig myself deeper into a hole.

**Comment by chrishoage** [comment] 2017-03-07 21:43
I have successfully pulled the images that I was having troubles with by following your steps. 

There was a step that I inferred from the fact that this all is referred to as a DB, which was `service docker restart`. 

I did this, deleted one more layer that was mis-referenced and it worked! 

Thank you so so very much for your help @Mic92 I'm not sure I would have solved this issue with out your guidance. 

At this point I am not sure if there is actionable for the ticket I have opened, so please feel free to close it if you desire. Clearly the problems I was experiencing were due to User Error.

**Comment by thaJeztah** [comment] 2017-03-08 00:50
That's good to hear! Thanks so much @Mic92 for assisting. I'll go ahead and close this issue, but feel free to continue the conversation if needed 👍

**Closed by thaJeztah** 2017-03-08 00:50 UTC
Labels: area/storage/zfs, kind/bug

**Comment by ManuelSchmitzberger** [comment] 2019-11-05 20:45
I had the same problem. This worked for me:
1) Stop docker service
2) Remove /var/lib/docker
3) Start docker service again

**Comment by toitzi** [comment] 2020-05-19 06:28
I get the following error message while trying to delete a docker container:

Error response from daemon: container `aec632519d964766878bd703c69b407320bb9f5883d5ffde47a5452b23f5cd85: driver "zfs" failed to remove root filesystem: exit status 1: "/usr/sbin/zfs fs destroy -r rpool/ROOT/ubuntu_50dmnj/var/lib/23d5a3ca6f8c3ce2a92f46ada48c2d1144864cca9e20ad65c00b02052f40583f" => cannot open 'rpool/ROOT/ubuntu_50dmnj/var/lib/23d5a3ca6f8c3ce2a92f46ada48c2d1144864cca9e20ad65c00b02052f40583f': dataset does not exis`

Already tried restarting docker and the host system...did not work...any guess?

**Comment by floppydisken** [comment] 2020-10-27 18:12
> I had the same problem. This worked for me:
> 
>     1. Stop docker service
> 
>     2. Remove /var/lib/docker
> 
>     3. Start docker service again

This has happened several times I did similar things I do find it a very obscure way to handle this situation. Does anyone know what is going on here?

**Comment by antanst** [comment] 2021-04-12 06:13
This worked for me.

```
1. Stop Docker service
2. Check the existence of Docker ZFS snapshots with something like `sudo zfs list -H -o name -t snapshot | grep docker`
3. Delete the aforementioned ZFS snapshots: `sudo zfs list -H -o name -t snapshot | grep docker | xargs -n1 sudo zfs destroy -R`
3. Start Docker service again
```

**Comment by nergdron** [comment] 2022-10-26 20:39
seems like the workaround for now, while upstream ponders implementing a proper fix, is to stop docker and destroy the `/var/lib/docker` zfs volume, and then start docker and recreate all the containers.

**Comment by milindpatel63** [comment] 2023-03-09 20:03
i also had to remove `/var/lib/containerd` in addition to `/var/lib/docker`.

**Comment by rhtenhove** [comment] 2024-01-07 14:57
A slightly less destructive operation which retains all volumes is the following:

Stop the docker service

```shell
sudo systemctl stop docker
```

Remove all ZFS legacy datasets

```shell
sudo zfs list -H -o name -t snapshot | grep "zpool-docker/"
```

> Replace `zpool-docker` with the name of your zpool. The `/` at the end ensures it only lists the legacy datasets which are the images/containers/etc.

Remove all files which reference these now removed datasets`

```shell
sudo rm -rf /var/lib/docker/image /var/lib/docker/container /var/lib/docker/network
```

Start the docker service again

```shell
sudo systemctl start docker
```

Now several Swarm services (not all, oddly enough) could not go up with the error `error creating vxlan interface: file exists`. [This comment](https://github.com/moby/libnetwork/issues/562#issuecomment-1155015141) helped in solving this, from which I created the following oneliner. This lists all the docker network links which are down and deletes them. The daemon then succesfully recreates them.

```shell
ip -d link show | grep vx- | cut -d":" -f2 | xargs -n1 ip link delete
```

Now I'll be more careful with which snapshots I delete :-)
