### ISSUE TITLE
How can I inspect a running container's file system

### ISSUE THREAD

**Issue by cxshun** [docker/docker#23336] opened 2016-06-07 08:59 UTC
I'm using **docker 1.11.0**.
In the past, I can find the running container's folder on /var/lib/docker or somewhere that I specify on the DOCKER_OPTS argument by -g, the folder's name just simply match the container's id.

But after **1.10**, docker has changed its security strategy, I can no longer find the running container's folder on the host file system simply by container's id.

### Now the problem is:

We have **many** running containers, many of them has grown too big for our disk, so we want to delete some of the files on the container. But there is no way for us to check the container's used disk size except using **docker attach** or **ssh**. 

> I'm using ways some kind of original by looking into the docker folder, like /var/lib/docker/aufs/mnt, then `du --max-depth=1 .` to find the folder that has bigger size, then delete some files that I don't need.

I was wondering if there is another way for me to find the running container's folder without attach or ssh cause it'll cause so much time and boring doing that.

Any help will appreciated. Thanks.

**Comment by thaJeztah** [comment] 2016-06-07 12:55
You can use `docker ps --size` to see how much space the container is using;

```
ps --size
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES               SIZE
e4224330f9af        busybox             "sh"                17 minutes ago      Up 17 minutes                           bla                 87 B (virtual 1.113 MB)
```

The important bit here is `87B`, which is the size of the container itself (not including the image it's based on). Additionally, you can use `docker diff <container>` to see which files are modified or created in the container's filesystem

However, I would discourage to directly removing files from the `/var/lib/docker` directory, if really needed, you could exec into the container (`docker exec -it <container> sh`) to remove files, but some things to consider;

- Why are these files growing? Are the log-files? If so, make sure your container logs to `stdout`, so that you can collect those logs through `docker logs`, and use `--log-opt max-size=` to limit the maximum size of the log file for a container (or use a different logging-driver)
- Consider putting the files that are growing in a *volume* to keep them outside of the container's filesystem (using the `-v` / `--volume` flag)


In general, you shouldn't really make changes to a container; containers should be disposable and don't keep state, so that you can replace a container with a "fresh" one if needed, and don't loose anything (i.e. in case you need to update the container to a newer version).

Also keep in mind that the GitHub issue tracker is for tracking bugs, and is not a general support forum. For these type of questions, consider using;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow


I'll close this issue, because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-06-07 12:55 UTC

**Comment by cxshun** [comment] 2016-06-08 01:13
Thanks @thaJeztah , It helps a lot.
