### ISSUE TITLE
docker network scope swarm Containers

### ISSUE THREAD

**Issue by yqguodataman** [docker/docker#24962] opened 2016-07-23 03:22 UTC
Hi:
 I use 1.12.0-rc4 docker swarm,create a new network scope is swarm, inspect this network, i find Containers option can only display the local machine container.I think should display all swarm cluster containers.

**Comment by ernestgwilsonii** [comment] 2016-07-24 11:59
I am also having a similar / possibly same issue.

I create an overlay network on the leader called "my-net"
docker network create --driver overlay --subnet=172.28.100.0/24 my-net

I see "my-net" as overlay swarm on the leader:
```
[root@VA1EWTCENTDT01 ~]# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
0d392afbf38f        bridge              bridge              local
f11a222daa0d        docker_gwbridge     bridge              local
501a34d1538f        host                host                local
070ibdftaebg        ingress             overlay             swarm
26weem0k3yxt        my-net              overlay             swarm
2d891547a17a        none                null                local
```

However on all other swarm members I do not see "my-net"
```
[root@VA1EWTCENTDT02 ~]# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
f4fb87043ae7        bridge              bridge              local
fb0a741eca91        docker_gwbridge     bridge              local
3c9b7e9ab247        host                host                local
070ibdftaebg        ingress             overlay             swarm
25c0f463ba7a        none                null                local
```

I am running 1.12RC4 on CentOS7

**Comment by yqguodataman** [comment] 2016-07-25 02:25
@ernestgwilsonii You send a application use network "my-net" and have one task running on worker node,you can find "my-net" network.I mean use "my-net" send a application, when inspect "my-net" can find use this netwok container only local machine,can't find all swarm containers.This option:
"Containers": {
            "bf1758b2a21dbe149d84ce0e941461026813cb661979ef193a5f95c6df4fc169": {
                "Name": "high_banach",
                "EndpointID": "1e68e238e3285ac8d19e6480722efa7fefca63deac1b9964d544c299a0afe5d2",
                "MacAddress": "02:42:ac:14:00:01",
                "IPv4Address": "172.20.0.1/16",
                "IPv6Address": ""
            }
        },

**Comment by thaJeztah** [comment] 2016-11-14 12:04
Looks like this is a duplicate of https://github.com/docker/docker/issues/24186, so I'll close this issue. Please subscribe to that issue to stay informed on updates

**Closed by thaJeztah** 2016-11-14 12:04 UTC
Labels: area/networking, area/swarm, kind/enhancement, version/1.12
