### ISSUE TITLE
1.9.0 Release: Unable to remove network "with active endpoints"

### ISSUE THREAD

**Issue by freeone3000** [docker/docker#17669] opened 2015-11-04 00:40 UTC
Docker daemon 1.9.0 failed to start when an autostart container, rancher-server, is already present.

Docker version:
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

docker info:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

uname -a:
Linux mordor 3.13.0-46-generic #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details:
Physical server

How reproducible: 100% of attempts with rancher-server

Steps to reproduce:
1. Install rancher-server:0.41.0 on docker 1.8.3
2. Upgrade to docker 1.9.0
3. Attempt to start docker

Actual results:
Docker failed to start. Error logs from docker.log: https://gist.github.com/freeone3000/07359934f33918d86f48

Expected results:
Docker daemon starts

Additional info:
Two other machines, running rancher-agent but not rancher-server, successfully started. After downgrading to 1.8.3-0 on the same machine, server successfully started.

**Comment by mrjana** [comment] 2015-11-04 00:50
@freeone3000 Did you run 1.9 rc code in the machine with rancher-server? Is this the first time you are starting 1.9 docker in that machine? If you ran 1.9 rc code in that machine can you try removing /var/lib/docker/network/files/local-kv.db and restart docker?

**Comment by WeiZhang555** [comment] 2015-11-04 01:48
This is a duplicate of #17555, there you can get more info.

**Comment by thaJeztah** [comment] 2015-11-04 13:16
This looks indeed like a duplicate of https://github.com/docker/docker/issues/17555

@freeone3000 I'm gonna close this issue; please continue the discussion on https://github.com/docker/docker/issues/17555. Thanks so much for reporting, and feel free to comment here if you think I closed this by mistake :+1:

**Closed by thaJeztah** 2015-11-04 13:16 UTC

**Comment by Helmi** [comment] 2018-10-16 06:18
Maybe worth backlinking this here https://forums.docker.com/t/containers-of-a-docker-stack-not-coming-up-after-host-reboot/52349/2

This does not seem to be fixed 3 years after.
