### ISSUE TITLE
EOF returned for all runs

### ISSUE THREAD

**Issue by teewhey** [docker/docker#14749] opened 2015-07-20 01:34 UTC
Hi, I just installed Docker to experiment with based on the Getting Started Docs.
I'm using Debian Wheezy 7.7 in a Vagrant environment.

Here is the output of "docker version" :

Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

root@vagrant-debian-wheezy:~# docker run ubuntu:14.04 /bin/echo 'Hello world'
Unable to find image 'ubuntu:14.04' locally
Pulling repository ubuntu
Get https://index.docker.io/v1/repositories/library/ubuntu/images: EOF

root@vagrant-debian-wheezy:~# docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository hello-world
Get https://index.docker.io/v1/repositories/library/hello-world/images: EOF

I did a manual curl to "https://index.docker.io/v1/repositories/library/ubuntu/images" and "https://index.docker.io/v1/repositories/library/hello-world/images" and are able to get the http response.

Did I miss out something ??

**Comment by teewhey** [comment] 2015-07-20 02:33
Docker info :
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 1
Total Memory: 494.2 MiB
Name: vagrant-debian-wheezy
ID: EX4Y:6KTC:WRYR:ZHTJ:FKNV:ZGEE:DUTA:BZ57:RI6G:JB3B:FJK2:AMKH
WARNING: No memory limit support
WARNING: No swap limit support

root@vagrant-debian-wheezy:~# uname -a
Linux vagrant-debian-wheezy 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1~bpo70+1 (2015-06-08) x86_64 GNU/Linux

ENvironment : Vagrant with Virtualbox
Steps to reproduce : Follow both the getting started docs from the docker site.

**Comment by jakirkham** [comment] 2015-07-20 19:40
Did you try `docker pull ubuntu:14.04` first?

**Comment by teewhey** [comment] 2015-07-21 02:46
Did that.

root@vagrant-debian-wheezy:~# docker pull ubuntu:14.04
Pulling repository ubuntu
Get https://index.docker.io/v1/repositories/library/ubuntu/images: EOF

**Comment by jakirkham** [comment] 2015-07-21 03:34
Is this on Linux? If so, prefix `docker` with `sudo`.

**Comment by teewhey** [comment] 2015-07-21 03:41
Yeah it is but I'm already running as a root user..

Anyhow i'm attaching the output here running as vagrant and root user, both using sudo :

root@vagrant-debian-wheezy:~# sudo docker pull ubuntu:14.04
Pulling repository ubuntu
Get https://index.docker.io/v1/repositories/library/ubuntu/images: EOF

vagrant@vagrant-debian-wheezy:~$ sudo docker pull ubuntu:14.04
Pulling repository ubuntu
Get https://index.docker.io/v1/repositories/library/ubuntu/images: EOF

**Comment by jakirkham** [comment] 2015-07-21 03:54
> Yeah it is but I'm already running as a root user..

Why are your running as root?

Also, try this `sudo services docker.io restart`.

**Comment by teewhey** [comment] 2015-07-21 03:58
Why not? It is a test instance that i want to rule out any privilege-induced issues. Plus the docker documentation didn't explicitly state that I have to run as a non-root user. So I did it with root user instead.

Anyhow I've tried your recommendation. It still does not work.

root@vagrant-debian-wheezy:~# service docker restart
[ ok ] Stopping Docker: docker.
[ ok ] Starting Docker: docker.

root@vagrant-debian-wheezy:~# docker pull ubuntu:14.04
Pulling repository ubuntu
Get https://index.docker.io/v1/repositories/library/ubuntu/images: EOF

vagrant@vagrant-debian-wheezy:~$ sudo docker pull ubuntu:14.04
Pulling repository ubuntu
Get https://index.docker.io/v1/repositories/library/ubuntu/images: EOF

**Comment by jakirkham** [comment] 2015-07-21 04:15
Could you try `sudo apt-get install -y libdevmapper-event1.02.1; service docker restart; docker pull ubuntu:14.04`?

**Comment by jakirkham** [comment] 2015-07-21 12:47
It would also be good to know the result of this `sudo /etc/init.d/docker status`.

**Comment by teewhey** [comment] 2015-07-21 17:33
There you go ....

vagrant@vagrant-debian-wheezy:~$ sudo apt-get install -y libdevmapper-event1.02.1; sudo service docker restart; sudo docker pull ubuntu:14.04
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  libdevmapper-event1.02.1
0 upgraded, 1 newly installed, 0 to remove and 50 not upgraded.
Need to get 32.6 kB of archives.
After this operation, 47.1 kB of additional disk space will be used.
Get:1 http://http.debian.net/debian/ wheezy/main libdevmapper-event1.02.1 amd64 2:1.02.74-8 [32.6 kB]
Fetched 32.6 kB in 2s (12.9 kB/s)
Selecting previously unselected package libdevmapper-event1.02.1:amd64.
(Reading database ... 32789 files and directories currently installed.)
Unpacking libdevmapper-event1.02.1:amd64 (from .../libdevmapper-event1.02.1_2%3a1.02.74-8_amd64.deb) ...
Setting up libdevmapper-event1.02.1:amd64 (2:1.02.74-8) ...
[ ok ] Stopping Docker: docker.
[ ok ] Starting Docker: docker.
Pulling repository ubuntu
Get https://index.docker.io/v1/repositories/library/ubuntu/images: EOF


vagrant@vagrant-debian-wheezy:~$ sudo /etc/init.d/docker status
[ ok ] Docker is running.
vagrant@vagrant-debian-wheezy:~$ uname -a
Linux vagrant-debian-wheezy 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1~bpo70+1 (2015-06-08) x86_64 GNU/Linux
vagrant@vagrant-debian-wheezy:~$ sudo docker -d
INFO[0000] [graphdriver] using prior storage driver "aufs"
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1
WARN[0000] Your kernel does not support cgroup memory limit: mountpoint for memory not found
WARN[0000] Your kernel does not support cgroup cfs period
WARN[0000] Your kernel does not support cgroup cfs quotas
INFO[0000] Loading containers: start.

INFO[0000] Loading containers: done.
INFO[0000] Daemon has completed initialization
INFO[0000] Docker daemon                                 commit=786b29d execdriver=native-0.2 graphdriver=aufs version=1.7.1


Still can't get it running...

**Comment by jakirkham** [comment] 2015-07-21 17:50
I would recommend that try using [`boot2docker`]( http://boot2docker.io ) if you just want to play around.

If you must persist with using this VM, take a look at this ( http://stackoverflow.com/questions/30132706/docker-service-does-not-start ).

**Comment by teewhey** [comment] 2015-07-21 18:16
I tried boot2docker a few days before this and getting a whole different set of problems.
I followed their documentation and boot2docker still says the client and server version mismatch. I'll leave that for another issue. For now, I'd prefer this to be fixed first

**Comment by jakirkham** [comment] 2015-07-21 18:53
This probably won't make a difference because I think the problem is the kernel that is used here. However, I will make an attempt anyways.

Just to confirm, when you did the `curl`, was it in the VM? Also, did you `curl` using `http` or `https`? You may need this `sudo apt-get install -y ca-certificates`.

**Comment by teewhey** [comment] 2015-07-21 18:59
ca-certificates is already installed in the VM. All curls are done in the VM using https

**Comment by jakirkham** [comment] 2015-07-21 19:03
Maybe so, but it may need an update.

**Comment by teewhey** [comment] 2015-07-21 19:23
It is already the newest version.

**Comment by unclejack** [comment] 2015-08-04 09:33
@teewhey Please provide the full output of this script: https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh

**Comment by teewhey** [comment] 2015-08-07 06:22
root@vagrant-debian-wheezy:~# bash check-config.sh
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-3.16.0-0.bpo.4-amd64 ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_KMEM: missing
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: missing
    (note that cgroup swap accounting is not enabled in your kernel config, you can enable it by setting boot option "swapaccount=1")
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_NETPRIO_CGROUP: missing
- CONFIG_CFS_BANDWIDTH: missing
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled (as module)
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled (as module)
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

**Comment by pchomik** [comment] 2015-10-15 18:30
Any update on this. I have same configuration output from Today's installation.

**Comment by thaJeztah** [comment] 2015-10-21 22:15
@pchomik are you consistently having this? Or occasionally? There have been some reports of similar issues that were related to Docker Hub

**Comment by pchomik** [comment] 2015-11-28 20:03
@thaJeztah I looked into output from config-check.sh script and I have the same errors. I did one more test with fresh installation and docker is working now ( output from check-config.sh is the same). It looks that I had different problem. Sorry for problem.

**Comment by thaJeztah** [comment] 2016-03-07 10:50
I'll close this issue, because the original report is now really old and may have been resolved in the current version, and we currently don't have a reproducible case to work on

**Closed by thaJeztah** 2016-03-07 10:50 UTC
