### ISSUE TITLE
docker autocompletion shows up .back files

### ISSUE THREAD

**Issue by zhenyulin** [docker/docker#31456] opened 2017-03-01 16:04 UTC
> /usr/local/etc/bash_completion.d  > (3) docker
docker                 docker-cloud           docker-compose         docker-compose.backup  docker-machine         docker-machine.backup  docker.backup

When I use tab to show hints of autocompletion, it seems the `.backup` is shown as well.

> /usr/local/bin  > (2) find /usr -iname "docker.backup"
/usr/local/bin/docker.backup

Related files are only found in the `usr/local/bin`, while I didn't find related directory in the docker completion bash script. 

Can you help me understand how this was implemented and what leads to the current situation?

**Comment by thaJeztah** [comment] 2017-03-01 16:15
That's the way autocompletion works, the `bash_autocompletion` package is a regular package (not created by docker) and automatically completes executables in your `PATH`. For example if you would have a copy of the `more` binary;


```
cp /bin/more /bin/more.backup
```

Then type `more <tab>`, you'll see the same;

```
more
more         more.backup
```

I'll close this issue, because this is not a bug, and not something we can fix, but feel free to comment after I closed

**Closed by thaJeztah** 2017-03-01 16:15 UTC

**Comment by thaJeztah** [comment] 2017-03-01 16:18
fwiw, the bash-completion package itself is maintained here; https://github.com/scop/bash-completion

**Comment by thaJeztah** [comment] 2017-03-01 16:33
Basically, the first bit (an executable) will be done by bash-completion "out of the box". Anything after that is done through our completion scripts

**Comment by thaJeztah** [comment] 2017-03-01 16:34
But @albers is the real expert there :smile:

**Comment by albers** [comment] 2017-03-01 17:29
Yes, @thaJeztah is right here. Nothing we can do here.
