### ISSUE TITLE
Docker swarm update the container gracefully

### ISSUE THREAD

**Issue by Renekton** [docker/docker#31174] opened 2017-02-20 01:38 UTC
**Description**

Hi, I am using the Swarm mode . I need to upgrade / downscale scale the service containers gracefully. That means I need the container to stop accepting new connections (= disable it on LB) and wait for all current connections to terminate. But, the stream of current connection has been break, that means the current request has not been handled successfully. After that the container can be stopped.

**Steps to reproduce the issue:**
1. docker swarm start with 2 nginx server container.
2. client send a keep-alive request to the server.
3. docker swarm update the server with the 'quit' signal. so the nginx server can stop gracefully.
4. but the stream of current connection is break by docker swarm. 

**Describe the results you received:**
1.the current connection is not handled successfully, because the client can not get the successful result from the server, so the connection between client and server is keep alive. due to docker swarm's timeout mechanism, container is forced to stopped by the docker swarm with errcode 137.

**Describe the results you expected:**
1. the docker swarm can not break the stream of current connection in timeout's limit. swarm can stop new connection of client. I want update the container gracefully. so it means the server have to handle the request successfully and send the result to the client successfully.

Thank you,  best regards.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-03-08 18:55
I think this is a duplicate of https://github.com/docker/docker/issues/30321, which is currently being discussed; please subscribe to that issue to stay informed on updates. I'll go ahead and close this issue so that the conversation doesn't diverge, but feel free to comment after i closed

**Closed by thaJeztah** 2017-03-08 18:55 UTC
Labels: area/swarm
