### ISSUE TITLE
docker push denied: Unable to determine the upload's size

### ISSUE THREAD

**Issue by DevOps-IT** [docker/docker#31812] opened 2017-03-14 06:29 UTC
I have created application image on google cloud and while trying to push through google cloud shell, getting following error:

08db9ff34fc6: Pushing [==================================================>] 73.38 MB
5313937c4c49: Pushing [==========================================>        ] 62.36 MB/73.37 MB
162f935b1198: Pushing [==========================>                        ] 84.09 MB/155.9 MB
dcf909146faa: Pushing [==================================================>] 6.787 MB
23b9c7b43573: Pushing [==================================================>]  4.23 MB
**denied: Unable to determine the upload's size.**

**I tried hard while searching for solutions but didn't find a single. Please help.**

**Comment by thaJeztah** [comment] 2017-03-14 07:32
Can you;

- add the output of `docker info` and `docker version`
- try if you're able to reproduce the same issue if you push to a different registry (e.g. to Docker Hub)

I could not find the error message "Unable to determine the upload's size" in the Docker source code, so this may well be an issue with Google Cloud. Have you tried contacting their support?

**Comment by thaJeztah** [comment] 2017-03-14 08:24
hm, I suspect this is an issue with the Google Cloud registry; also Docker 1.11.2 is no longer maintained, and we don't have official builds for Google's "Container-Optimized OS".

Could you try contacting Google Cloud support? I don't think we'd be able to help here

I'll close the issue here because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2017-03-14 08:24 UTC
Labels: area/distribution, status/more-info-needed
