### ISSUE TITLE
ADD and COPY does not work correctly with nested directory

### ISSUE THREAD

**Issue by sanemat** [docker/docker#7511] opened 2014-08-10 13:14 UTC
ADD nested directory does not work well.

This is reproduce step:

Directory:
```
.
├── Dockerfile
├── parent-dir
│   ├── child-dir
│   │   └── child.txt
│   └── parent.txt
└── reproduce.txt
```

This is Dockerfile:
https://github.com/sanemat/copy-example/blob/e4d6e6ea67ed9e9274830e0d23539ee6b3467f7d/Dockerfile

This is example repo https://github.com/sanemat/copy-example

How to reproduce:
$ git clone https://github.com/sanemat/copy-example.git
$ cd copy-example
$ chmod -R go-rwx .

$ ls -alR

```text
total 16
drwx------   7 sane  staff  238  8 10 21:27 .
drwxr-xr-x   5 sane  staff  170  8 10 21:16 ..
drwx------  12 sane  staff  408  8 10 21:27 .git
drwx------  10 sane  staff  340  8 10 21:27 .idea
-rw-------   1 sane  staff  265  8 10 21:24 Dockerfile
drwx------   4 sane  staff  136  8 10 21:17 parent-dir
-rw-------   1 sane  staff   29  8 10 21:27 reproduce.txt

(snip)

./parent-dir:
total 8
drwx------  4 sane  staff  136  8 10 21:17 .
drwx------  7 sane  staff  238  8 10 21:27 ..
drwx------  3 sane  staff  102  8 10 21:18 child-dir
-rw-------  1 sane  staff    7  8 10 21:17 parent.txt

./parent-dir/child-dir:
total 8
drwx------  3 sane  staff  102  8 10 21:18 .
drwx------  4 sane  staff  136  8 10 21:17 ..
-rw-------  1 sane  staff    6  8 10 21:18 child.txt
```

$ docker build -t sanemat/copy-example .
$ docker run -t -i sanemat/copy-example:latest /bin/bash

% ls -alR /code/parent/

```text
  /code/parent/:
  total 16
  drwxrwxrwx 4 root root 4096 Aug 10 12:49 .
  drwxrwxrwx 4 root root 4096 Aug 10 12:49 ..
  drwxrwxrwx 2 root root 4096 Aug 10 12:49 child-dir
  -rwxrwxrwx 1 root root    7 Aug 10 12:48 parent.txt
  ls: cannot open directory /code/parent/child-dir: Permission denied
```

% cd /code/parent/child-dir

```text
bash: cd: /code/parent/child-dir: Permission denied
```

My env:
```text
$ docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): d84a070

$ docker -D info
Containers: 44
Images: 157
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 247
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Debug mode (server): false
Debug mode (client): true
Fds: 29
Goroutines: 67
EventsListeners: 2
Init Path: /usr/bin/docker
Sockets: [unix:///var/run/docker.sock]
WARNING: No swap limit support

$  uname -a
Linux mouse.tachikoma.io 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mapio** [comment] 2015-01-08 13:54
I've the same issue with `docker version`

```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.4
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

and `docker info`

```
Containers: 1
Images: 403
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 405
Execution Driver: native-0.2
Kernel Version: 3.16.7-tinycore64
Operating System: Boot2Docker 1.4.1 (TCL 5.4); master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
CPUs: 8
Total Memory: 1.961 GiB
Name: boot2docker
ID: SJPB:GG7J:HGKR:C2H5:AC4O:VQMX:PA42:TUHZ:LRTE:4J2Z:ST6Z:NXJY
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 12
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: mapio
Registry: [https://index.docker.io/v1/]
```

I've setup an even simpler example: have this `Dockerfile`

```
FROM busybox
RUN adduser -D -g '' test
COPY ./dir /dir
RUN chown -R test:test -R /dir
USER test
```

and build the image with the following commands

```
rm -rf dir
mkdir dir
mkdir dir/subdir
touch dir/file.txt
touch dir/subfile.txt
chmod -R go= dir

docker build -t test .
```

Now, as expected

```
$ docker run --rm test ls -ld /dir/subdir
drwx------    2 test     test          4096 Jan  8 13:51 /dir/subdir
```

but, even if the permission and ownership seems ok,

```
$ docker run --rm test ls -l /dir/subdir/subfile.txt
ls: /dir/subdir/subfile.txt: Permission denied
```

**Comment by thaJeztah** [comment] 2015-01-08 19:09
@mapio could be related to `AUFS` issues; https://github.com/docker/docker/issues/783

**Comment by mapio** [comment] 2015-01-08 22:29
Maybe @thaJeztah… and if the culprit is the one in @jpetazzo https://github.com/docker/docker/issues/783#issuecomment-19237045 there is no hope that it will be fixed (at least in the near future); moreover I don't want to play with other storage drivers (mostly because  I use Docker in multiple setups/servers and I don't want to mess with all of them, or to introduce risky dependencies on storage drivers in my Dockerfiles).

I worked out this "solution" (just a dirt workaround, I admit), that I report here in case someone is stuck in a situation like mine: just `COPY` the content under `/tmp` and then `cp` it where it belongs (and fix its permissions and ownership). In the above example, just replace the `COPY` line with:

```
COPY ./dir /tmp/dir
RUN cp -r /tmp/dir /dir && chown -R test:test -R /dir && rm -rf /tmp/dir
```

and everything will work as expected!

**Comment by thaJeztah** [comment] 2015-01-08 22:46
@mapio happy to hear you managed to find a workaround (and, yes, it's nasty).

There's currently a PR open (https://github.com/docker/docker/pull/9934) that would allow setting the ownership when adding files with `COPY`. Currently, the PR is to discuss the possible syntax to use for that, but if it's implemented that *should* solve the issue you're having.

WRT storage drivers; I think some documentation should be added that compares the advantages and limitations (and known issues) of each driver, to make it easier to select the best driver for your needs.

**Comment by mapio** [comment] 2015-01-08 22:58
It would be very nice if that PR get accepted @thaJeztah!

**Comment by jfrazelle** [comment] 2015-02-26 23:48
can you reproduce on docker 1.5.0

**Comment by thaJeztah** [comment] 2015-02-27 00:19
@jfrazelle just tested the repro case and I can still reproduce on 1.5.0/AUFS

I think this is an AUFS issue and a dup of https://github.com/docker/docker/issues/783#issuecomment-19237045, which is mentioned in the [known issues](https://docs.docker.com/release-notes/#known-issues).

**Comment by jfrazelle** [comment] 2015-02-27 00:25
ah ok thanks

**Closed by jfrazelle** 2015-02-27 00:25 UTC
