### ISSUE TITLE
"/container/<id>/stats" does not return any response even an error when querying with an exited container.

### ISSUE THREAD

**Issue by ghmlee** [docker/docker#12529] opened 2015-04-20 05:14 UTC
"/container/<id>/stats" does not return any response even an error when querying with an exited container.

I found this function in /docker/api/server/server.go. It returns d.ContainerStats(...).
```go
func getContainersStats(eng *engine.Engine, version version.Version, w http.ResponseWriter, r *http.Request, vars map[string]string) error {
	if err := parseForm(r); err != nil {
		return err
	}
	if vars == nil {
		return fmt.Errorf("Missing parameter")
	}

	d := getDaemon(eng)

	return d.ContainerStats(vars["name"], utils.NewWriteFlusher(w))
}
```
I think this is the function in /docker/daemon/stats.go. I expected daemon.SubscribeToContainerStats() should return an error with an exited container.
```go
func (daemon *Daemon) ContainerStats(name string, out io.Writer) error {
	updates, err := daemon.SubscribeToContainerStats(name)
	if err != nil {
		return err
	}
	enc := json.NewEncoder(out)
	for v := range updates {
		update := v.(*execdriver.ResourceStats)
		ss := convertToAPITypes(update.Stats)
		ss.MemoryStats.Limit = uint64(update.MemoryLimit)
		ss.Read = update.Read
		ss.CpuStats.SystemUsage = update.SystemUsage
		if err := enc.Encode(ss); err != nil {
			// TODO: handle the specific broken pipe
			daemon.UnsubscribeToContainerStats(name, updates)
			return err
		}
	}
	return nil
}
```

in SubscribeToContainerStats(), it does not check a container status. 
```go
func (daemon *Daemon) SubscribeToContainerStats(name string) (chan interface{}, error) {
	c, err := daemon.Get(name)
	if err != nil {
		return nil, err
	}
	ch := daemon.statsCollector.collect(c)
	return ch, nil
}
```

What do you think about my opinion that it should return an error with an exited container? Please let me know your opinions. I always appreciate this great open source - Docker. :) Thank you.

**Comment by cpuguy83** [comment] 2015-04-20 18:09
This is by design currently.
If you start the container, you should see it's stats start to stream.

**Comment by ghmlee** [comment] 2015-04-20 23:19
@cpuguy83 Thank you. I didn't understand the design philosophy. If it is based on the important design, you can close my issue. :)

**Comment by ghmlee** [comment] 2015-04-20 23:52
@cpuguy83 It is not big deal on CLI but when I try to use this API on Docker Remote API, it is blocked. This connection is waiting.

**Comment by thaJeztah** [comment] 2015-05-18 10:24
> when I try to use this API on Docker Remote API, it is blocked. This connection is waiting.

Basically, that's the same; its a "streaming" endpoint, once the container is started, the remote API will start streaming those stats.

Also, there's now an option to disable "streaming", and only collect the stats "once", then close the connection (see https://github.com/docker/docker/pull/10766). This feature will be available as part of the next release.

I'm going to close this issue, because this is not a bug and implemented by design

**Closed by thaJeztah** 2015-05-18 10:24 UTC
