### ISSUE TITLE
in some scenario,  restarting a container does not update the /etc/hosts of the linked one

### ISSUE THREAD

**Issue by allan-simon** [docker/docker#13056] opened 2015-05-07 16:27 UTC
I'm using Docker version 1.6.0, build 4749651

here's my set up,  i have 5 container 

  * nginx_load_balancer 
  * nginx_blue
  * php_fpm_blue
  * nginx_green
  * php_fpm_green

they are linked like this :

```
                     +--------  nginx blue -------  php_fpm_blue
                     |
              load_balancer
                     |
                     +--------   nginx green ------ php_fpm_green
```

when the switch of my load balancer is on  nginx_green:

  * docker restart php_fpm_green  does NOT update the /etc/hosts  of nginx_green
  *  docker restart php_fpm_blue   DOES  update the /etc/hosts of nginx_blue 

and if i then change the switch  (changing the upstream of the load_balancer container)  it's the opposite which happens 

https://docs.docker.com/userguide/dockerlinks/#updating-the-etchosts-file  

according to the docs I don't see any reason why it should happen.

if necessary I can provide more information

### Docker info

```
Containers: 91
Images: 421
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 608
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.8.0-44-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 32
Total Memory: 15.49 GiB
Name: SMG
ID: 33F2:XUMX:VOVH:H256:3Q2Q:YVBA:2O3S:CAY6:F2MK:ZKPV:ZJDN:YSRR
WARNING: No swap limit support
```

### uname -a 

```
Linux SMG 3.8.0-44-generic #66~precise1-Ubuntu SMP Tue Jul 15 04:01:04 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

### Environment details:

```
  * physical server
  * ubuntu 12.04  
  * docker installed through ppa 
```

**Comment by thaJeztah** [comment] 2015-06-07 21:11
I can't tell if it's the cause, but you're using a kernel that's too old for running docker, and is unsupported.

For ubuntu 12.04, kernel 3.13 is the absolute minimum requirement for running docker, see http://docs.docker.com/installation/ubuntulinux/#for-precise-1204-lts.

I'm going to close this issue for now, because you're running an unsupported kernel version, but feel free to comment here if you're still having this problem after updating your system and I'll reopen.

**Closed by thaJeztah** 2015-06-07 21:11 UTC
