### ISSUE TITLE
--ipv6 flag not working after upgrade to v1.12.4

### ISSUE THREAD

**Issue by lenovouser** [docker/docker#29386] opened 2016-12-14 04:23 UTC
**Description**

`--ipv6` flag not working after upgrade to `v1.12.4`

```
level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: failed to parse pool request for address space \"LocalDefault\" pool \"\" subpool \"\": could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network"
```

(This did work before the upgrade)

**Steps to reproduce the issue:**

1. Upgrade to `v1.12.4`
2. Reload Docker Daemon or reboot

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Mon Dec 12 23:40:33 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical, Debian 8

**Comment by mavenugo** [comment] 2016-12-14 04:49
@lenovouser this is not a bug. This is the behavioral change introduced due to resolving https://github.com/docker/docker/issues/28055. The change requires the user to pass an explicit IPv6 subnet in the `--subnet` option in order to use `--ipv6` flag. Can you pls try that ?

cc @aboch

**Comment by aboch** [comment] 2016-12-14 05:58
That's correct. The previous behavior where the daemon would accept the `--ipv6` but no IPv6 subnet was actually being allocated to the network was wrong.

If user specifies an IPAM driver which can autoallocate an IPv6 subnet for the network, then this would work. The built in IPAM driver though does not support auto allocation for IPv6 subents, therefore docker fails the network creation, as it cannot satisfy the user's `--ipv6` configuration.

I am going to close this issue, as this is the expected behavior.

**Closed by aboch** 2016-12-14 05:58 UTC

**Comment by lenovouser** [comment] 2016-12-14 11:00
Oh, sorry. I forgot to mention that this is with the Docker Daemon. I don't want to enable it on a container. I actually am trying to get it working on the Daemon / Engine first.

**Comment by aboch** [comment] 2016-12-14 16:40
@lenovouser Thanks for providing more details.
The `--ipv6` docker daemon flag, as most of the other daemon networking options, has only relevance for the default `bridge` network, the one backed by `docker0` bridge.

In your case, you need to specify the IPv6 pool for the `bridge` network during daemon start. 
You would do that by using the `--fixed-cidr-v6` daemon option.

**Comment by lenovouser** [comment] 2016-12-16 01:07
@aboch yep, I now split my `/64` IPv6 network in parts and specified it in `--fixed-cidr-v6`. Now Docker does start - thank you! 👍  But when I want to create networks it also throws the same error, so I specified a different subnet there too. When I do `ping6 google.com` from inside containers that have joined the IPv6 enabled network it doesn't work. Is there any way to "help" IPAM auto-allocate the IPv6 addresses like it did before. Because it doesn't seem to work the way I am specifying them.

**Comment by aboch** [comment] 2016-12-16 05:46
@lenovouser That is probably a connectivity/routing issue. It is not related to the IPAM job.
Please refer to https://docs.docker.com/engine/userguide/networking/default_network/ipv6/
If it does not work, please open a separate issue.
