### ISSUE TITLE
Improve daemon restart with --restart

### ISSUE THREAD

**Issue by vieux** [docker/docker#12118] opened 2015-04-06 18:35 UTC
Hi,

Here is a story that happened to me a few hours ago, I wonder if we could improve the behaviour of docker when the daemon restarts.

One month ago I started a frontend container
`docker run -d --restart -p 80:80 --name web1 <image>`
Two weeks ago I had to do an update, so I stopped web1 and started a new one:
`docker stop web1`
`docker run -d --restart -p 80:80 --name web2 <new_image>`

I worked as expected.
Unfortunately, yesterday the docker daemon was restarted. Thanks to `--restart` docker tried to restart containers, but it started `web1` (and because of the -p 80:80, `web2` failed)

I know it might be tricky, but with such a configuration, I expected `web2` to be restarted first (and if possible not restart `web1`)

**Comment by xiaods** [comment] 2015-04-06 22:35
Proposal the ideal logic, if the container is stopped, then the host restart will not restart the container with "restart" flag.

**Comment by thaJeztah** [comment] 2015-04-06 22:56
I'm closing this as I think this is a duplicate of https://github.com/docker/docker/issues/11008, please continue the discussion on that issue, thanks!

Right now, to prevent a stopped container to be restarted, you'll have to stop *and remove* the container.

**Closed by thaJeztah** 2015-04-06 22:56 UTC

**Comment by vieux** [comment] 2015-04-06 23:01
thanks @thaJeztah
