### ISSUE TITLE
Containers cannot access public server from another container if not on the same network

### ISSUE THREAD

**Issue by metathink** [docker/docker#19879] opened 2016-02-01 09:11 UTC
Here a simple way to reproduce:

First we create a 'test' network:
```bash
docker network create test
```

Then we create a simple http server inside the test network, with exposed ports
```bash
docker run -d --net=test --name=pysrv -p 8033:8033 -w /usr python:2 python -m SimpleHTTPServer 8033
```

Now we can access the web page from any computer all over the world

```bash
wget -O- http://my.public.ip:8033/
http GET http://my.public.ip:8033/
```

We can also access the web page inside a container connected to the 'test' network:
```bash
docker run --net=test --rm clue/httpie GET http://my.public.ip:8033
```

But we can't access the web page inside a container not connected to the 'test' network, even if it is a public ip and the ports are exposed:
```
docker run --rm clue/httpie GET http://my.public.ip:8033
```
> http: error: Request timed out (30s).

Why ?

The same request also works in the same dedicated server outside a container. I wasn't expect these behaviours. Is docker aware of the dedicated server public ip and somehow translate it into a private ip and restrict the access because the container is not in the 'test' network ?

Docker version:
> Client:
>  Version:      1.9.1
>  API version:  1.21
>  Go version:   go1.4.2
>  Git commit:   a34a1d5
>  Built:        Fri Nov 20 12:59:02 UTC 2015
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.9.1
>  API version:  1.21
>  Go version:   go1.4.2
>  Git commit:   a34a1d5
>  Built:        Fri Nov 20 12:59:02 UTC 2015
>  OS/Arch:      linux/amd64

Docker info:
> Containers: 6
> Images: 89
> Server Version: 1.9.1
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 101
>  Dirperm1 Supported: true
> Execution Driver: native-0.2
> Logging Driver: json-file
> Kernel Version: 3.16.0-4-amd64
> Operating System: Debian GNU/Linux 8 (jessie)
> CPUs: 4
> Total Memory: 3.854 GiB
> Name: xxx
> ID: UAEQ:LNUV:2I7Y:PPTP:3TLX:YQOV:IEWA:ICYD:PO3S:VMVI:ET65:3EBR
> WARNING: No memory limit support
> WARNING: No swap limit support

**Comment by thaJeztah** [comment] 2016-02-01 12:26
This is a duplicate of https://github.com/docker/docker/issues/18354 (https://github.com/docker/docker/issues/18354#issuecomment-173929816). A workaround for now is provided here; https://github.com/docker/docker/issues/18354#issuecomment-174603932.

This is going to be worked on for docker 1.11

**Closed by thaJeztah** 2016-02-01 12:26 UTC

**Comment by metathink** [comment] 2016-02-01 12:49
Thank you and sorry for the duplicate.

**Comment by thaJeztah** [comment] 2016-02-01 13:26
no problem!

**Comment by mavenugo** [comment] 2016-02-01 22:57
@metathink @thaJeztah fyi, we found a simpler intermediate fix https://github.com/docker/docker/pull/19899 that will take care of the issue in 1.10.

**Comment by thaJeztah** [comment] 2016-02-01 23:04
@mavenugo oh, excellent, thanks!
