### ISSUE TITLE
Container route to service VIP cannot hairpin

### ISSUE THREAD

**Issue by mgoelzer** [docker/docker#24398] opened 2016-07-07 03:00 UTC
Scenario is a redis service with 1 replica.  `docker exec` into the task and do `redis-cli -h <redis service VIP>`.  Result:  "No route to host"

Expected result:  should work.

Environment:
```
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[root@node2 ~]# uname -a
Linux node2 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 9 10:09:10 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

@mavenugo

**Comment by mavenugo** [comment] 2016-07-07 03:30
This is a dupe of https://github.com/docker/docker/issues/24377

**Closed** 2016-07-07 03:30 UTC
Labels: area/swarm, group/networking
