### ISSUE TITLE
Make `inspect` use same conventions as `rm` - so we can use containers/images with same name

### ISSUE THREAD

**Issue by thedeeno** [docker/docker#4829] opened 2014-03-24 17:18 UTC
If I have containers and images with matching names I can work with them because docker treats them as semantically different. For instance I can't `docker start` an image. Or, as another example, its clear when I remove containers/images because there are two commands for it: `rm` and `rmi` respectively.

However, when I `docker inspect <name>`, I get an error saying: `conflict between containers and images`. This is surprising. I expect `inspect` to either work for containers or images, not both at once.

I suggest adding a command: `inspecti` to match the `rmi` semantics for inspecting images and make `inspect` only work for containers to keep things consistent.

**Comment by jfrazelle** [comment] 2015-02-25 21:47
closing as duplicate of https://github.com/docker/docker/issues/8069 hopefully will be resolved soon!

**Closed by jfrazelle** 2015-02-25 21:47 UTC
