### ISSUE TITLE
"Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"

### ISSUE THREAD

**Issue by rumatakira** [docker/docker#31863] opened 2017-03-15 18:05 UTC
![49](https://cloud.githubusercontent.com/assets/16696651/23963615/217b0244-09b2-11e7-8cbd-78a87724a09e.png)

**Comment by thaJeztah** [comment] 2017-03-15 18:25
Thanks for reporting. This relates to https://github.com/docker/docker/issues/30450, which was partly resolved in docker 1.13.0, but is being further addressed in https://github.com/docker/docker/pull/31705

/cc @cyli

**Comment by thaJeztah** [comment] 2017-03-21 18:18
https://github.com/docker/docker/pull/31705 was merged; @cyli should this issue be resolved by that?

**Comment by cyli** [comment] 2017-03-21 21:10
This will be resolved for the specific case reported `docker --version`, and `docker ps` etc. (connecting to a remote docker via mTLS) for master.  (not merged yet: https://github.com/docker/docker/pull/31977 would resolve it for 17.04)

If connecting to a remote content trust server using a custom CA, this message may appear, but it should be resolved for the majority of cases.

**Comment by laurencefass** [comment] 2017-03-28 14:39
i have the same issue. is there a resolution to this problem?

**Comment by cyli** [comment] 2017-03-28 22:22
@laurencefass #31977 has been merged, so it should make it into 17.04 (probably >=rc2)

**Comment by raiello** [comment] 2017-04-09 11:01
when is this fix going to be available and how do we implement the fix?

**Comment by laurencefass** [comment] 2017-04-09 11:08
also can you explain what is the problem cause?

**Comment by cyli** [comment] 2017-04-09 18:05
@raiello Should be in 17.04.  If you upgrade your client to 17.04 you should no longer see it.

@laurencefass Please see https://github.com/docker/docker/issues/30450#issuecomment-278852038

**Comment by cpuguy83** [comment] 2017-04-12 17:34
Closing since this is resolved in 17.04.

**Closed by cpuguy83** 2017-04-12 17:34 UTC
Labels: area/cli, version/17.03

**Comment by chetangandotra** [comment] 2017-04-13 18:27
When do we expect 17.04 to be available?

**Comment by cpuguy83** [comment] 2017-04-13 18:28
@chetangandotra It's out.

**Comment by g8tguy** [comment] 2017-04-14 07:19
the client is still 17.03 in the stable v17.04.0-ce for windows.  Use 17.05 beta in order to get rid of the message.

**Comment by patrickPDD** [comment] 2017-04-17 17:27
g8tguy how were you able to upgrade to that Beta version? tried 'docker-machine upgrade 17.05

**Comment by g8tguy** [comment] 2017-04-18 01:15
Just download the release binaries `https://test.docker.com/builds/Windows/x86_64/docker-17.05.0-ce-rc1.zip` and replace the currently installed `docker` client executable file at `C:\Program Files\Docker\Docker\resources\bin`

**Comment by OrysyaStus** [comment] 2017-04-20 17:18
how would I solve this with Docker Toolbox.

**Comment by vur102** [comment] 2017-04-20 19:27
Yes, how is this solved for Docker Toolbox?

**Comment by CarlosChocNST** [comment] 2017-04-20 21:39
I have the same issue with Docker Toolbox :(

**Comment by cpuguy83** [comment] 2017-04-20 21:45
Are you on the latest toolbox?

ping @nathanleclaire

**Comment by CarlosChocNST** [comment] 2017-04-20 21:50
yes I am I just downloaded it today and tried to run the example in the tutorial

**Comment by lachlangreenbank** [comment] 2017-04-22 08:58
i am also having this issue, downloaded toolbox from docker site today

**Comment by rajakamil4** [comment] 2017-04-23 11:38
i am also using docker toolbox, installed 2 days ago, and have the same issue, please help

**Comment by danielalejandrohc** [comment] 2017-04-24 00:18
Same here...out of the box it just giving me  ""Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows""

**Comment by Tasakafei** [comment] 2017-04-24 10:04
Same here, downloaded a few days ago. Windows 7

**Comment by electron0zero** [comment] 2017-04-25 06:25
I downloaded Docker toolbox just now
Here is what I got running `$ docker version`
```
$ docker version
time="2017-04-25T11:45:21+05:30" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Client:
Version: 17.03.1-ce
API version: 1.27
Go version: go1.7.5
Git commit: c6d412e
Built: Tue Mar 28 00:40:02 2017
OS/Arch: windows/amd64

Server:
Version: 17.04.0-ce
API version: 1.28 (minimum version 1.12)
Go version: go1.7.5
Git commit: 4845c56
Built: Wed Apr 5 18:45:47 2017
OS/Arch: linux/amd64
Experimental: false
```

**Comment by tjallingran** [comment] 2017-04-25 09:22
I have the same issue with Docker version 17.03.1-ce, build c6d412e on Windows 7.

I uninstalled Git for Windows and am using Cygwin instead, using the environment variables listed [here](https://unix.stackexchange.com/q/263250/). It works well, except for getting the certificate pool message after pretty much every command.

**Comment by ccrash** [comment] 2017-04-25 22:33
Same version, same error

**Comment by atiyou** [comment] 2017-04-26 15:13
got the same issue with Docker Toolbox version 17.03.1-ce on Windows 8 Pro
Please release the new version!

**Comment by friism** [comment] 2017-04-26 17:23
As mentioned above, you have to be on 17.04 or later. 17.03 is the latest stable release, but you can get 17.04 or 17.05-RC here: https://github.com/docker/toolbox/releases

**Comment by nathanleclaire** [comment] 2017-04-26 17:42
we've updated the main links to be 17.04 as well

**Comment by tjallingran** [comment] 2017-04-28 08:50
(Maybe superfluous, but) I can confirm that getting v17.04.0-ce solves the issue.

I haven't tried the main links, nor 17.05-RC

**Comment by tmcgee123** [comment] 2017-05-04 15:54
For those running Windows 10, I was having this problem because Docker itself was not running via Windows (making sure docker is running in the active tasks on the bottom right task bar).

Hope this helps someone. I was getting this error even on 17.03-ce. Cheers!

**Comment by electron0zero** [comment] 2017-08-03 05:29
I updated docker toolbox to `17.06.0-ce` and Virualbox to Version `5.1.26`
That solved this issue for me
```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
