### ISSUE TITLE
Can't pull on own server (no space left)

### ISSUE THREAD

**Issue by erperejildo** [docker/docker#32343] opened 2017-04-04 08:25 UTC
I'm running a pipeline on Gitlab every time I do a push to master. This pipeline is quite simple:
```
image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_IMG: myUSER/myAPP
before_script:
  - docker login --username="myUSER" --password="myPASS"
stages:
  - Pull
Pull:
  stage: Pull
  tags:
    - deploy # private runner on server
  script:
    - docker pull $DOCKER_IMG
```

This pull is a 1-2GB image from Docker Hub and it's connected with a private runner so this detects I want to pull on my server (no ssh connection required).

The issue that I get when I run this is that I don't have any more space on my server.
This is the available space that I've got:
```
recipic@recipic:/var/lib/docker$ sudo df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        20G  6.4G   13G  34% /
```

Here you can see further info:
https://forum.gitlab.com/t/pull-from-my-server/7264

I'm also talking with DigitalOcean staff and they told me that this is quite weird. Also previous link is on Gitlab forum to discard problems from them as well.

Am I doing something wrong?  :S

**Comment by thaJeztah** [comment] 2017-04-04 08:52
There's a number of possible causes for this, but without the information that was requested in the [issue template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md), it's hard to tell which one;

- if you're running with the device mapper graph driver, the [default "base size" is 10GB](https://docs.docker.com/engine/reference/commandline/dockerd/#storage-driver-options)
- if you're running with the overlay (not overlay2) graph driver, you may be running out of inodes (see https://github.com/docker/docker/issues/10613, and https://github.com/docker/docker/issues/10613#issuecomment-93105892) - if your system supports it (has a recent 4.x kernel), switch to the overlay2 graph driver

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, and more information is needed, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-04-04 08:52 UTC
Labels: area/distribution, kind/question

**Comment by erperejildo** [comment] 2017-04-04 09:21
I don't know what "mapper graph driver" or "overlay" is so I guess not.
Anyway, I'll move the post to docker forums then.

Thanks

**Comment by thaJeztah** [comment] 2017-04-04 10:24
> Storage Driver: vfs

If looks like you're running with the `vfs` storage ("graph") driver. That driver is really only intended for debugging purposes, and only used as a "last result" to get things working. The `vfs` driver basically does _not_use any copy-on-write / layered filesystem, and just makes a copy of all image layers for each layer that's downloaded. And does the same for each container that's run. (read about storage drivers here: https://docs.docker.com/engine/userguide/storagedriver/selectadriver/)

However, the `docker info` you posted looks to be from the "docker-in-docker" daemon, not the docker daemon that runs on the host itself; what distro, and docker version are you running on the host itself?

**Comment by erperejildo** [comment] 2017-04-04 11:03
Never heard about that before.
I just followed the steps to install docker on Ubuntu here: https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository
I'm using the CE version.

Also followed the other step about how to use the .yml fies for Gitlab and use the docker images directly from Docker Hub. The one I'm using is the latest one:
https://hub.docker.com/_/docker/

That `docker info` comes from the Gitlab pipeline. This one is the other on my server (the one I'm pulling from):
```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 3
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-71-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.4 MiB
Name: recipic
ID: FWZC:GWMY:BDRE:O5DZ:V4YX:VNHB:MNTZ:MTJW:5T4P:KDOP:K7JR:DUCM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: xiwi
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
the storage driver looks here different but again I didn't have the choice to configure this I understand this should be a common issue, it's the default configuration and just running a pull to my own server.

I didn't change anything else on my droplet (DigitalOcean image) just the swap memory with these commands but not sure if this could be related:
```
Make all swap off
sudo swapoff -a

Resize the swapfile
sudo dd if=/dev/zero of=/swapfile bs=1M count=1024

Make swapfile usable
sudo mkswap /swapfile

Make swapon again
sudo swapon /swapfile
```

**Comment by thaJeztah** [comment] 2017-04-04 12:16
The `docker pull` is done by the `docker in docker` daemon, or directly on the host? From the YAML file, I assume it's by the `docker-in-docker` daemon?

Can you define a _volume_ for the `docker-in-docker` container? The usual approach is to use `-v /var/lib/docker` (or `-v <volume-name>/var/lib/docker`). That prevents the docker storage to end up in the container's filesystem.

> I didn't have the choice to configure this I understand 

The docker daemon tries a the storage drivers that are available, and picks the first one that's supported by the host it runs on. From the output it looks like it selected the `aufs` storage driver, which is used if you installed the (for 16.04 optional) linux-image-extra package; https://docs.docker.com/engine/installation/linux/ubuntu/#recommended-extra-packages-for-trusty-1404. For ubuntu 16.04, the default now is "overlay2" on recent kernels - if the linux-image-extra package is not installed. However, you can configure the driver to use using [a daemon.json configuration file](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file)


It would be worth checking the daemon logs (`journalctl -xu docker`), and system logs as well to see if anything stands out. Possibly it's a different error resulting in docker showing "no space on disk", but the actual error is something different

**Comment by erperejildo** [comment] 2017-04-04 13:11
The pull runs on Gitlab pipelines but this directly affects to my own branch. This is because I'm using a private runner with a docker executor so if I run commands like pull or run this will be directly executed on my branch.

Yes, I can define volumes and create and run images on my server.

I'll try later on creating the json file but I think this is going too far: too many things to be aware of.

This is what I get with journalctl -xu docker:

> -- Logs begin at Mon 2017-04-03 04:44:02 UTC, end at Tue 2017-04-04 13:10:06 UTC. --
> Apr 03 22:05:37 recipic dockerd[1380]: time="2017-04-03T22:05:37.963788225Z" level=error msg="Handler for DELETE /v1.18/containers/runner-e5a2e604-project-2177477-concurrent-0-docker"

**Comment by erperejildo** [comment] 2017-04-04 13:22
I'm also trying to run `docker pull` from my server (without pipelines). I can download my image properly:

> Status: Downloaded newer image for xiwi/recipic:latest

If I have a look to my graph on DigitalOcean I can see that I've got less space but not as before, just 1-2GB more (10% less), which is correct.
