### ISSUE TITLE
docker unexpectedly creates non-existent host volumes

### ISSUE THREAD

**Issue by mgummelt** [docker/docker#16055] opened 2015-09-03 17:30 UTC
This:

`docker run -v /path/to/nonexistent/directory:/container-path ...`

Results in docker creating `/path/to/nonexistent/directory`.  I didn't expect this, and AFAICT, it's undocumented. 

`Linux mg-mesos 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:40:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:40:42 UTC 2015
 OS/Arch:      linux/amd64
```

```
Containers: 30
Images: 112
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 172
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-26-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 11.62 GiB
Name: mg-mesos
ID: 7AES:SDZ5:WNYM:NM33:3FKF:SQK6:KYMM:DBXJ:DLGK:MN6L:WYRR:EFTI
Username: mgummelt
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Comment by thaJeztah** [comment] 2015-09-06 22:21
This is not a bug, but the way this was designed to work; there have been discussions around this, but changing this will break backward compatibility.

I checked if this is documented, and it looks like it is; http://docs.docker.com/reference/run/#volume-shared-filesystems;

```
-v=[]: Create a bind mount with: [host-dir:]container-dir[:rw|ro].
       If 'host-dir' is missing, then docker creates a new volume.
       If neither 'rw' or 'ro' is specified then the volume is mounted
       in read-write mode.
```

And here; http://docs.docker.com/reference/commandline/run/#examples

> When the host directory of a bind-mounted volume doesn’t exist, Docker will automatically create this directory on the host for you


I'm going to close this issue, because this is expected behavior, and documented, but if you think docs around this can be improved, please create a pull request :+1:

**Comment by mgummelt** [comment] 2015-09-08 20:20
Thanks.

The website docs and the man page are inconsistent.  This isn't documented in the man page.

**Comment by thaJeztah** [comment] 2015-09-08 20:34
> The website docs and the man page are inconsistent. This isn't documented in the man page.

Good point, the man page doesn't seem to mention this; https://github.com/docker/docker/blob/master/man/docker-run.1.md

I'll reopen this, and add a `kind/writing` label, to indicate the docs (man pages) can be improved here.

Perhaps you're interested in contributing, and creating a PR to add that information?

**Comment by mikebrow** [comment] 2015-09-14 15:34
#dibs

**Comment by frconil** [comment] 2015-09-24 23:31
Without trying to sound contrary, is there somewhere where one can read the discussion around this behaviour?

We found that it leads to a few errors as instead of mentioning the lack of host dir/files, it just create one silently. This could lead to more problems down the road if someone introduce typos in their config, or try to mount sockets/files before they are present on the filesystem.

Would it be possible otherwise to have a flag to pass to the docker daemon that would gives the option to fail and exit if a host dir doesn't exist while trying to mount a volume?

**Comment by thaJeztah** [comment] 2015-09-24 23:38
@frconil please see the linked PR https://github.com/docker/docker/issues/16287  and https://github.com/docker/docker/issues/16349, because we're going to deprecate this behavior

**Comment by frconil** [comment] 2015-09-24 23:55
Awesome!

Thanks for the update @thaJeztah

**Comment by thaJeztah** [comment] 2015-11-02 08:17
closing, now that https://github.com/docker/docker/issues/16287 was merged, and https://github.com/docker/docker/pull/16349 marks the behavior as deprecated

**Closed by thaJeztah** 2015-11-02 08:17 UTC
Labels: exp/beginner, kind/docs, status/claimed
