### ISSUE TITLE
get.docker.com tries to install on ARM64 platform without having any package for this

### ISSUE THREAD

**Issue by nmaas87** [docker/docker#29713] opened 2016-12-26 17:40 UTC
**Description**
get.docker.com tries to install on ARM64 platform without having any package for this

root@pitest:~# curl -sSL https://get.docker.com/ | sh
apparmor is enabled in the kernel and apparmor utils were already installed
+ sh -c apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: /tmp/tmp.PakiRsG7SJ/gpg.1.sh --keyserver
hkp://ha.pool.sks-keyservers.net:80
--recv-keys
58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server ha.pool.sks-keyservers.net
gpg: key 2C52609D: "Docker Release Tool (releasedocker) <docker@docker.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
+ break
+ sh -c apt-key adv -k 58118E89F3A912897C070ADBF76221572C52609D >/dev/null
+ sh -c mkdir -p /etc/apt/sources.list.d
+ dpkg --print-architecture
+ sh -c echo deb \[arch=arm64\] https://apt.dockerproject.org/repo ubuntu-xenial main > /etc/apt/sources.list.d/docker.list
+ sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
Hit:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports xenial-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease
Hit:5 https://apt.dockerproject.org/repo ubuntu-xenial InRelease
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://apt.dockerproject.org/repo ubuntu-xenial InRelease' doesn't support architecture 'arm64'
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package docker-engine
root@pitest:~#

**Steps to reproduce the issue:**
1. curl -sSL https://get.docker.com/ | sh on an arm64 system

**Describe the results you received:**
Script tries to install docker-engine, but does stop after seeing that there is no package available

**Describe the results you expected:**
The script should stop before even changing apt files if the system is not supported

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Linux pitest.local.lan 4.4.0-38-generic #57-Ubuntu SMP Wed Sep 7 10:19:14 UTC 2016 aarch64 aarch64 aarch64 GNU/Linux
ARMv8 Server from Packet.net (Type-2A)

**Comment by tiborvass** [comment] 2016-12-27 19:05
Ping @andrewhsu

**Comment by alexellis** [comment] 2017-01-05 08:51
I have also tried this and had the same issue, I was told it is because there is no CI for the ARM64 platform. Maybe an error could be thrown in the script instead @justincormack @tianon ?

The version of Docker in the apt-get repository is recent if you use the Ubuntu image on Packet.net. You can use that to clone docker/docker and checkout a stable tag then run in `make tgz`.

Curious about the machine name though `pitest`?

**Comment by tophj-ibm** [comment] 2017-01-09 21:01
I just checked and this should be fixed in 1.13.0. The script at https://get.docker.com/ is updated during release, and the last release was 1.12.5, which didn't have this fix in. 

If you want to test 1.13.0-rc5 (and the updated script), you can do so with 
```curl -sSL https://test.docker.com/ | sh```

**Comment by alexellis** [comment] 2017-01-09 22:46
Thanks, I'll try this on Packet.net @tophj-ibm

**Comment by tophj-ibm** [comment] 2017-01-09 22:51
@alexellis sorry, by fixed I mean it should error out. aarch64 isn't in the docker apt repo, so there aren't any packages to find. However, it should abort immediately.

**Comment by alexellis** [comment] 2017-01-09 22:55
Confirmed fixed @tophj-ibm (as in gives error)

```
root@getdockercom113:~# curl -sSL test.docker.com |sh
Error: Docker doesn't officially support aarch64 and no Docker aarch64 repository exists.
root@getdockercom113:~# uname -a
Linux getdockercom113.local.lan 4.4.0-38-generic #57-Ubuntu SMP Wed Sep 7 10:19:14 UTC 2016 aarch64 aarch64 aarch64 GNU/Linux
root@getdockercom113:~# 
```

**Comment by alexellis** [comment] 2017-01-09 22:55
I would perhaps suggest that a build is available on the Releases page?

**Comment by tophj-ibm** [comment] 2017-01-10 15:16
@alexellis giving people a little direction here seems like a good idea, but I don't know where we would point them for the case of aarch64. I don't see a build on the releases page, and afaik to get the latest release you would have to build from source if the distro doesn't supply it, which isn't entirely helpful IMO.

**Comment by alexellis** [comment] 2017-01-10 15:23
I remembered it wrong.. you're right there is nothing there. But a link to "build Docker from source" may be useful. In fact Ubuntu 16.04 contains a working version of Docker for 64-bit ARM and you can build from source successfully. 

It sounds like the "end of the line" in the error message, but it's not true - it just becomes a lot harder. Maybe with a slightly more helpful message it could avoid issues being opened saying "where do I go now?"?

**Comment by vielmetti** [comment] 2017-01-11 07:05
Maybe the answer is CI for ARMv8? This blog post from Hypriot suggests how to do so (for ARMv7, but should be extendable for ARMv8) using QEMU on Travis. 

https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/

**Comment by tophj-ibm** [comment] 2017-01-11 17:19
@alexellis unfortunately I don't see a guide to building docker from source in the docker docs(would be nice to add one), but I wrote a patch to change the error message to suggest checking your distro's repo or installing for source which hopefully people will search for. You can check it out here #30067

**Comment by cpuguy83** [comment] 2017-01-11 17:41
I don't think we can do armv8 in CI yet (not enough capacity, IIRC).

How to build docker? `make binary`

**Comment by alexellis** [comment] 2017-01-14 10:53
@tophj-ibm this is my guide:

(Get started with Docker on 64-bit ARM)
http://blog.alexellis.io/get-started-with-docker-on-64-bit-arm/

But @cpuguy83 is right.. it's almost as simple as clone/checkout a tag and `make binary` - I used `make tgz` instead.

**Comment by tophj-ibm** [comment] 2017-01-17 15:45
Building from source isn't difficult, but you need docker installed to do ``make binary``, which is where it gets tricky. However, there are way too many platforms to have a definitive guide that is in any way up-to-date anyway, plus the community seems to be doing a good job of making them 😄 

#30067 should solve _this_ issue though, and hopefully make things a little clearer when trying to install on an unsupported platform.

**Comment by cpuguy83** [comment] 2017-01-17 19:29
You can build without docker, just that you need to make sure to have all the deps readily available.
`hack/make.sh binary`

**Comment by alexellis** [comment] 2017-01-17 20:11
Arch Linux uses hack/make.sh in PKGBUILD but my understanding that this wasn't a supported configuration. Most of the popular platforms have "a" Docker version which is usable to build the next. I.e. ARM64 has Docker 1.12.x in Ubuntu 16.04 (See packet.net for an example)

https://www.archlinux.org/packages/community/x86_64/docker/

> I don't think we can do armv8 in CI yet (not enough capacity, IIRC).

Hi @justincormack - is there any update on using a Linaro environment to run the armv8 CI?

**Comment by zsmith928** [comment] 2017-01-18 03:52
@andrewhsu @dmp42 should have some of the Packet Type2A's now and are working on some CI for this.  Just let us know if more machines are needed.  thanks!

**Comment by alexellis** [comment] 2017-02-18 18:17
Since there is now an appropriate error message can we close this issue @nmaas87 @tophj-ibm ? Issue will remain in archive for indexing from Google.

**Comment by alexellis** [comment] 2017-02-18 18:18
@zsmith928 that sounds great.. cc/ @andrewhsu

**Comment by nmaas87** [comment] 2017-02-18 18:19
@alexellis Completly fine by me 👍

**Comment by thaJeztah** [comment] 2017-02-18 18:20
I'll go ahead and close, but feel free to continue the conversation

**Closed by thaJeztah** 2017-02-18 18:20 UTC
Labels: platform/arm

**Comment by fredix** [comment] 2017-06-25 23:25
Hi, i'm using an ARM64v8 at scaleway https://blog.online.net/2017/06/22/armv8-scaleway-new-high-core-variants/

centos7 and Docker works fine but it's an older version 1.12.5 so I can't use docker stack. It would be great having an officiel version for ARM64.

**Comment by alexellis** [comment] 2017-06-26 06:45
This is a lot of work to support but I've seen a PR raised for Docker CE packaging repo. So keep an eye out for that. In the meantime you can clone docker/docker and checkout 17.05 for a full build. `make tgz`

**Comment by fredix** [comment] 2017-06-26 20:50
Hi @alexellis, ok i will try to build docker as you explain on your blog http://blog.alexellis.io/get-started-with-docker-on-64-bit-arm/

**Comment by alexellis** [comment] 2017-06-26 21:30
Good luck. Perhaps you can close the issue and move over to the Docker slack channel for further support? There is a channel #arm

**Comment by fredix** [comment] 2017-06-26 21:39
@alexellis So, all works fine after updated /usr/lib/systemd/system/docker.service and removed /var/lib/docker. thanks for your help.
