### ISSUE TITLE
Docker: Can't use Docker new image file after commiting running container

### ISSUE THREAD

**Issue by thinhduckhoi** [docker/docker#19869] opened 2016-02-01 02:41 UTC
First of all, i posted this problem on Stackoverflow and didn't get the right answer. So i think this place would be my help. Here's the deal.
So i created and run smoothly one Docker images with LAMP and WP installed from Dockerfile using port 1250. My image is called wordpress.

For instance, when access this address 52.192.1.x:1250, a install Wordpress page appeared.

Then, i tried to test a little bit. I login to bash environment with this command.

docker run -it wordpress /bin/bash
And created 1 folder called Testing.

I open one more windows at the same time and login and then commit the running container with this command.

docker commit ID-of-running-container wordpress3.
And when i was running this new images wordpress3 on another port, let's say 52.192.1.x:1251, nothing appeared except for error "can't connect"

Can you guys tell me the reason why?

**Comment by unclejack** [comment] 2016-02-01 10:56
This isn't a Docker bug. This issue is related to getting started with Docker and using a particular Docker image.

Please keep in mind the following:
- this issue tracker is dedicated to tracking bugs, proposals and pull requests to make changes to Docker; it's not a general support forum
- not getting an answer on StackOverflow or on the docker-user mailing list doesn't mean that an issue should be opened on this issue tracker
- support isn't provided for running and using individual Docker images
- opening issues to ask questions when getting started will make everyone who contributes to the project spend more time looking at issues

For everyone who's getting started, please consider the following:
- many questions can be answered by reading the documentation found at https://docs.docker.com/
- for those who wish to have a question answered quickly, connecting to Freenode and asking the question in the #docker channel is recommended
- many images have good documentation on how to use them directly on the Hub

This kind of question and general support questions are more adequate for the following:
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.
4) StackOverflow https://stackoverflow.com/questions/tagged/docker

I'm going to close this issue now because the discussion can continue even after the issue is closed. Please feel free to continue the discussion. There's no need to open a new issue on this topic.

**Closed by unclejack** 2016-02-01 10:56 UTC

**Comment by thinhduckhoi** [comment] 2016-02-02 01:28
OK, thank you for your answers.
