### ISSUE TITLE
Memory cgroup(s) not removed on container exit/dead

### ISSUE THREAD

**Issue by galexrt** [docker/docker#30909] opened 2017-02-10 10:38 UTC
**Description**

Container memory cgroups are not removed when the container exists/ends.
This seems to cause memory not being freed correctly and filling up, until the OOM killer is activated.

**Steps to reproduce the issue:**
1. Start container (doesn't matter if with or without a (memory) limit(s))
2. Check `num_cgroups` see num increased by one
3. Stop container
4. Check `num_cgroups` again, see all expect memory subsys num decreased.

**Describe the results you received:**
```
$ cat /proc/cgroups 
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	7	2	1
cpu	        5	51	1
cpuacct	5	51	1
blkio	        3	51	1
memory	2	52	1
devices	4	51	1
freezer	8	2	1
net_cls	6	2	1
pids	        9	55	1
$ docker run -d --memory 10M busybox sleep 10
__CONTAINER_ID_HERE__
$ cat /proc/cgroups                          
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	7	3	1
cpu	        5	52	1
cpuacct	5	52	1
blkio	        3	52	1
memory	2	53	1
devices	4	52	1
freezer	8	3	1
net_cls	6	3	1
pids	        9	56	1
# container exits
$ cat /proc/cgroups                          
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	7	2	1
cpu	        5	51	1
cpuacct	5	51	1
blkio	        3	51	1
memory	2	53	1
devices	4	51	1
freezer	8	2	1
net_cls	6	2	1
pids	        9	55	1
```
As can be seen above, the memory cgroups number does not decrease. It seems that this is a problem related to the Docker runtime.
Last /proc/cgroups output memory cgroups count:
```
[...]
memory	2	53	1
[...]
```

**Describe the results you expected:**
The `num_cgroups` to decrease back to before the container run, for the memory subsys cgroup.
```
$ cat /proc/cgroups                          
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	7	2	1
cpu	        5	51	1
cpuacct	5	51	1
blkio	        3	51	1
memory	2	52	1
devices	4	51	1
freezer	8	2	1
net_cls	6	2	1
pids	        9	55	1
```

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens to every containers that are started.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 19
 Running: 18
 Paused: 0
 Stopped: 1
Images: 39
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Kernel Version: 4.9.0-0.bpo.1-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.42 GiB
Name: [REMOVED]
ID: ODGO:UURI:37JX:ELFS:MRXE:CZQE:CGRV:QNGV:2M6W:LZ4X:ECGU:RGCR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: [USED - REMOVED]
Https Proxy: [USED - REMOVED]
No Proxy: localhost,127.0.0.0/8
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 [USED - REMOVED]
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The issue occurs on multiple servers (bare metal in this case, but occurs in VMs too).
The issue occurs on Debian 8.6 with kernel `Linux HOSTNAME 4.9.0-0.bpo.1-amd64 #1 SMP Debian 4.9.2-2~bpo8+1 (2017-01-26) x86_64 GNU/Linux` and on CentOS 7.3.1611 with kernel `Linux 4.9.5-1.el7.elrepo.x86_64 #1 SMP Fri Jan 20 11:34:13 EST 2017 x86_64 x86_64 x86_64 GNU/Linux` (with same Docker Engine version).

**Update 1**: This also occurs on Fedora 23 to 25.

**Update 2**: This issue has been found with at least Docker version 1.12 and up.

***

cc @axhoffmann

**Comment by BenHall** [comment] 2017-02-18 15:45
Thanks for the additional info. The problem is being discussed in https://github.com/docker/docker/issues/29638

**Comment by thaJeztah** [comment] 2017-02-18 21:39
Looks like the same issue yes; let me close this one so that the discussion doesn't diverge; please subscribe to the linked issue (https://github.com/docker/docker/issues/29638) to stay informed on updates

**Closed by thaJeztah** 2017-02-18 21:39 UTC
Labels: area/runtime, version/1.13
