### ISSUE TITLE
Remote API Stats - Return Empty Response From Netcat

### ISSUE THREAD

**Issue by jmmclean** [docker/docker#22813] opened 2016-05-18 13:38 UTC
Hello Docker Community,
I believe there may be an issue with the Docker Remote API for obtaining stats. Few things to note:

I cannot use curl 7.40 or greater as my customers may or may not have this version; As a fallback, I use netcat, similar to the below:

```
[root@localhost ~]# echo -e "GET /containers/fe47ba52b12a9c320569329aeb35a861aa87c68a7ffe9822d6d0314e40ee8a67/stats HTTP/1.0\r\n" |  nc -U /var/run/docker.sock 
HTTP/1.0 200 OK
Server: Docker/1.9.1 (linux)
Date: Wed, 18 May 2016 14:03:21 GMT
Content-Type: text/plain; charset=utf-8

[root@localhost ~]# 

```
You will notice that nothing is returned. Please also note that I have reviewed https://github.com/docker/docker/issues/16078 and this will not work as my netcat does not have a '-q' flag. I have tried, however, using -w in a last ditch effort w/ no avail. I'm really just hoping that there is a magical flag that I'm not utilizing correctly.

Also, to verify that stats IS working, `docker stats <container id>` yields:
```
CONTAINER                                                          CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O
fe47ba52b12a9c320569329aeb35a861aa87c68a7ffe9822d6d0314e40ee8a67   0.00%               22.65 MB / 2.098 GB   1.08%               3.674 kB / 848 B    16.7 MB / 0 B
```

**Output of `docker version`:**
```
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:           
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**
```
Containers: 4
Images: 9
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-451239-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 134.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 13.39 GB
 Metadata Space Used: 839.7 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.6.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 1.954 GiB
Name: localhost.localdomain
ID: 7XW7:N72J:LRPO:Q67C:LWJ3:M7XP:VD3W:IYNV:2DSZ:EJTV:2WUP:BACQ
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is running on 'CentOS Linux release 7.2.1511 (Core) ' having kernel '4.6.0-1.el7.elrepo.x86_64'. It is hosted on a VMWare ESXi 5.5 and has curl version '7.29.0 (x86_64-redhat-linux-gnu)'

**Describe the results you received:**
Receive blank response from API call.

**Describe the results you expected:**
Expected to receive a json block of data.

**More Info**
Also, I can verify that my API request are working:

```
[root@localhost ~]# echo -e "GET /version HTTP/1.0\r\n" |  nc -U /var/run/docker.sock HTTP/1.0 200 OK
Content-Type: application/json
Server: Docker/1.9.1 (linux)
Date: Wed, 18 May 2016 14:29:35 GMT
Content-Length: 211

{"Version":"1.9.1","ApiVersion":"1.21","GitCommit":"78ee77d/1.9.1","GoVersion":"go1.4.2","Os":"linux","Arch":"amd64","KernelVersion":"4.6.0-1.el7.elrepo.x86_64","PkgVersion":"docker-1.9.1-25.el7.centos.x86_64"}
```

**Comment by thaJeztah** [comment] 2016-05-18 15:46
I don't think there's much we can do about that; if you don't have tools to communicate with the API, that's not a bug in docker.

You could consider having them run cURL in a container;

```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock jess/curl curl -N --unix-socket /var/run/docker.sock http:/containers/web/stats
```

I'm closing this because this isn't a bug

**Closed by thaJeztah** 2016-05-18 15:46 UTC
Labels: version/1.9

**Comment by jmmclean** [comment] 2016-05-18 15:48
This doesnt work because it require curl v 7.40 to use --unix-socket.  I mentioned that in my original post.

**Comment by thaJeztah** [comment] 2016-05-18 16:06
> This doesnt work because it require curl v 7.40 to use --unix-socket. I mentioned that in my original post.

Have you tried? It's running cURL inside a container, so you can have any version you want.

```
docker run jess/curl curl --version
curl 7.42.1 (x86_64-alpine-linux-musl) libcurl/7.42.1 OpenSSL/1.0.2e zlib/1.2.8 libssh2/1.5.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

> To force users to upgrade items like cURL and kernels in order to consume metric APIs will really reduce your customer consumption

I don't really understand the issue; If you need to consume the API, you need something to consume it. In this case, it's a *streaming* endpoint, so you need a client that is capable of using that. Could be cURL, could be a simple go binary that connects to the API.

If you don't need "streaming", you can pass the `?stream=0` option, so that you can use polling to get stats;

```
echo -e "GET /containers/web/stats?stream=0 HTTP/1.0\r\n" |  nc -U /var/run/docker.sock
```

**Comment by jmmclean** [comment] 2016-05-18 16:16
In reference to your docker wrapping curl container, its too slow, especially if I had to monitor thousands of hosts with containers. Also, it did not work for me:

```
[root@localhost memory]# docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock jess/curl curl -N --unix-socket /var/run/docker.sock http:/containers/json
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
curl: (7) Couldn't connect to server
```


Yea, I would love to not have it streaming. but that still doesnt produce expected results

```
[root@localhost memory]# echo -e "GET /containers/fe47ba52b12a9c320569329aeb35a861aa87c68a7ffe9822d6d0314e40ee8a67/stats?stream=0 HTTP/1.0\r\n" |  nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Content-Type: application/json
Server: Docker/1.9.1 (linux)
Date: Wed, 18 May 2016 17:03:59 GMT
Content-Length: 0

[root@localhost memory]# 
```

The API should really be accessible from my remote machine without having to SSH into a box then running CLI. This may be possible, but to make it happen, you have to open a port to converse with this machine, thus introducing a security concern.

If using netcat works for pretty much all other commands but NOT stats endpoint, how is this not a bug?

Am I missing something with the above? For a successful monitoring solution, I should never force a client machine to do Change Requests to update. This isn't scalable, nor is it practical. Enterprises are very hesitant to force their IT resource to be on the "latest and greatest", it takes years.

**Comment by thaJeztah** [comment] 2016-05-18 16:56
> The API should really be accessible from my remote machine without having to SSH into a box then running CLI.

How are you accessing `/var/run/docker.sock` from your remote machine?

> If using netcat works for pretty much all other commands but NOT stats endpoint, how is this not a bug?

As I mentioned above; `/stats` is a streaming endpoint, I suspect this makes a difference here. Note that `nc` is notorious, in that its implementation differs a lot between distros. The endpoint is working as intended, but it looks like the version of `nc` on CentOS can't work with that, and exits directly.

**Comment by jmmclean** [comment] 2016-05-18 17:07
Really appreciate the feedback on this one! To access the `/var/run/docker.sock` I first SSH into my remote machine then do a CMD line call using paramiko package (python). Is there a better way to achieve successful API calls from a remote system?

I have a feeling that your intuition on CentUS `nc` is correct. I am in no way claiming to be a Docker expert, but I have interacted with other APIs for service like AWS, SoftLayer, Azure, and VMWare so I may be missing something foundational to my solution

**Comment by thaJeztah** [comment] 2016-05-18 17:14
Some ways to remotely access the API;

- make the daemon listen to `127.0.0.1:2375` (in addition to a socket), and use a SSH tunnel to connect. Note that port 2375 is an non-TLS port, so unprotected
- better is to protect the API with TLS (even if it's only accessible locally); https://docs.docker.com/engine/security/https/
- if you don't want to use a tunnel, you can expose the port on the public interface of the host, but ONLY do so if you properly set up TLS (see previous bullet)

**Comment by jmmclean** [comment] 2016-05-18 17:35
Curiosity, do you see majority of your customers forcing the daemon to listen to a designated port in order to issue remote APIs? The big kicker for me is that I do not have the ability to make changes to the clients running docker-engine, so I will require a Change Request to get this done. My solution is meant to be read-only, quick-to-use for my customers utilizing Docker in their IT space. If they have to do things like open up ports or manual ca-cert authentication, it just wont happen. Having the ability to quickly get information from Docker is a necessity, especially for larger SP and enterprises. 

Now, I am also not an architect, but is there any development to have a static endpoint to converse with customer docker instances? Something like how Cloudwatch works for AWS...where instances will publish metrics to a DB in a DMZ, and access to that endpoint will be controlled by an IAM service. Right now may just not be the right time to support Docker (for my use case) with large customers.

At first walk into Docker Management/monitoring, I was hoping there was something to get from the docker hub. I can create some hackery around SSH'ing to servers and cat'ing proc PIDs, but its getting messier ever step I take. 

Thanks again for all the help with the above!

**Comment by thaJeztah** [comment] 2016-05-18 18:45
I don't think it's right to compare Docker Engine with a hosted solution, such as AWS / Cloudwatch. AWS / Cloudwatch is a solution built *on top of* a lot of other technology. Depending on your use-case, Docker Engine can be *part* of a solution. By design, the Engine does not provide *all* possible features, but provides the tools/components to build those features (as there's never a one-size-fits-all solution).

There are various solutions that make use of the engine to give a more "feature complete" / "polished" experience. For example [Docker Cloud](https://www.docker.com/products/docker-cloud), or (if you want to have this on-premise) [Universal Control plane](https://www.docker.com/products/docker-universal-control-plane) / [Docker Datacenter](https://www.docker.com/products/docker-datacenter), or [Rancher](http://rancher.com). For metrics you can also  think of tools like [cAdvisor](https://blog.tutum.co/2014/08/07/using-cadvisor-to-monitor-docker-containers/).

**Comment by yoplait** [comment] 2017-03-09 19:26
Same story here ... but working with curl ... 


root@it-2:/home/knujuser# echo -e "GET /containers/342cd03d20d3/stats HTTP/1.0\r\n" |  nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Api-Version: 1.26
Docker-Experimental: false
Server: Docker/1.13.1 (linux)
Date: Thu, 09 Mar 2017 19:26:18 GMT
Content-Type: text/plain; charset=utf-8

root@it-2:/home/knujuser# echo -e "GET /containers/342cd03d20d3/stats?stream=0 HTTP/1.0\r\n" |  nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Api-Version: 1.26
Content-Type: application/json
Docker-Experimental: false
Server: Docker/1.13.1 (linux)
Date: Thu, 09 Mar 2017 19:26:21 GMT
Content-Length: 0

root@it-2:/home/knujuser# curl -s --unix-socket /var/run/docker.sock http::/containers/342cd03d20d3/stats?stream=false | jq ".cpu_stats"
{
  "cpu_usage": {
    "total_usage": 2498158388342,
    "percpu_usage": [
      603946008599,
      586343521310,
      631040813931,
      676828044502
    ],
    "usage_in_kernelmode": 256070000000,
    "usage_in_usermode": 2171460000000
  },
  "system_cpu_usage": 1117722180000000,
  "throttling_data": {
    "periods": 0,
    "throttled_periods": 0,
    "throttled_time": 0
  }
}
root@it-2:/home/knujuser#

**Comment by aleclarson** [comment] 2017-09-16 01:47
I found the solution: `nc -q 2 -U /var/run/docker.sock`

That will keep the connection open.

```sh
echo -e "GET /containers/342cd03d20d3/stats?stream=0 HTTP/1.0\r\n" | nc -q 2 -U /var/run/docker.sock
```
