### ISSUE TITLE
docker push skipping authentication on PUT requests if GET requests do not require authentication

### ISSUE THREAD

**Issue by w-p-pueschel** [docker/docker#22300] opened 2016-04-25 14:35 UTC
Hi all,

I'm trying to set up an nginx as a reverse proxy for my private docker registry. I want it to allow docker pull without authentication and require authentication for docker push/etc.. The nginx generally works as expected (please find the full nginx config, log and examples below).

If I run a docker pull, it works as expected:

```
$ docker pull localhost/ubuntu:14.4.03
14.4.03: Pulling from ubuntu
8387d9ff0016: Pull complete
3b52deaaf0ed: Pull complete
4bd501fad6de: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:a47804d268c600572aab1f564e38d1ef009bd7c7ce4bbd325be51973541e5431
Status: Downloaded newer image for localhost/ubuntu:14.4.03
```

When I run docker login and then try to push the image back, it gives me an authentication error:

```
$ docker login localhost
Username (usermeh): usermeh
Password:
Login Succeeded
$ docker push localhost/ubuntu:14.4.03
The push refers to a repository [localhost/ubuntu]
5f70bf18a086: Layer already exists
0d81735d8272: Layer already exists
982549bd6b32: Layer already exists
8698b31c92d5: Layer already exists
unauthorized: authentication required
```

It seems, that docker does a GET request before pushing (to get the registry version?), gets a HTTP 200 back instead of a 401 and then assumes, no authentication is needed for the subsequent  request(s), regardless of the http method. Is this the intended behavior?

If you need more information please let me know. Thanks in advance.

Cheers,
Willi

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
$ docker --version
Docker version 1.11.0, build 4dc5990
```

**Output of `docker info`:**

```
$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.11.0
Storage Driver: devicemapper
 Pool Name: docker-254:5-917508-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 790.1 MB
 Data Space Total: 107.4 GB
 Data Space Available: 93.26 GB
 Metadata Space Used: 1.765 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /home/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.120 (2016-03-11)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.7 GiB
Name: beholder
ID: I3U5:ETBE:374V:DTXU:MZCE:2IUS:2VDE:PJVO:RNVL:YAFG:MO7S:6ZI5
Docker Root Dir: /home/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```

**nginx log of docker push**

```
127.0.0.1 - - [25/Apr/2016:14:10:35 +0000] "GET /v2/ HTTP/1.1" 200 2 "-" "docker/1.11.0 go/go1.5.4 git-commit/4dc5990 kernel/4.4.0-1-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \x5C(linux\x5C))"
2016/04/25 14:10:35 [error] 6#0: *63 connect() to [::1]:5000 failed (101: Network is unreachable) while connecting to upstream, client: 127.0.0.1, server: , request: "HEAD /v2/ubuntu/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1", upstream: "http://[::1]:5000/v2/ubuntu/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4", host: "localhost"
127.0.0.1 - - [25/Apr/2016:14:10:35 +0000] "HEAD /v2/ubuntu/blobs/sha256:3b52deaaf0edb8a0282a08dd9c9e25da2050a75739b832ecc6e29941394933a6 HTTP/1.1" 200 0 "-" "docker/1.11.0 go/go1.5.4 git-commit/4dc5990 kernel/4.4.0-1-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \x5C(linux\x5C))"
127.0.0.1 - - [25/Apr/2016:14:10:35 +0000] "HEAD /v2/ubuntu/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 200 0 "-" "docker/1.11.0 go/go1.5.4 git-commit/4dc5990 kernel/4.4.0-1-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \x5C(linux\x5C))"
127.0.0.1 - - [25/Apr/2016:14:10:35 +0000] "HEAD /v2/ubuntu/blobs/sha256:4bd501fad6defc3af5638b82f7d760f0dc2f2c5f1bcd2cbfd59607b1631bc679 HTTP/1.1" 200 0 "-" "docker/1.11.0 go/go1.5.4 git-commit/4dc5990 kernel/4.4.0-1-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \x5C(linux\x5C))"
127.0.0.1 - - [25/Apr/2016:14:10:35 +0000] "HEAD /v2/ubuntu/blobs/sha256:8387d9ff0016d004777e511a55e21672e4b6de49e32db2544b8ac0e2ee01d5ed HTTP/1.1" 200 0 "-" "docker/1.11.0 go/go1.5.4 git-commit/4dc5990 kernel/4.4.0-1-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \x5C(linux\x5C))"
127.0.0.1 - - [25/Apr/2016:14:10:35 +0000] "HEAD /v2/ubuntu/blobs/sha256:3876b81b5a81678926c601cd842040a69eb0456d295cd395e7a895a416cf7d91 HTTP/1.1" 200 0 "-" "docker/1.11.0 go/go1.5.4 git-commit/4dc5990 kernel/4.4.0-1-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \x5C(linux\x5C))"
127.0.0.1 - - [25/Apr/2016:14:10:35 +0000] "PUT /v2/ubuntu/manifests/14.4.03 HTTP/1.1" 401 194 "-" "docker/1.11.0 go/go1.5.4 git-commit/4dc5990 kernel/4.4.0-1-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \x5C(linux\x5C))"
127.0.0.1 - - [25/Apr/2016:14:10:35 +0000] "PUT /v2/ubuntu/manifests/14.4.03 HTTP/1.1" 401 194 "-" "docker/1.11.0 go/go1.5.4 git-commit/4dc5990 kernel/4.4.0-1-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \x5C(linux\x5C))"
``` 

**curl test of GET/PUT**

```
GET:
$ curl -D - -X GET http://localhost/v2/
HTTP/1.1 200 OK
Server: nginx/1.8.1
Date: Mon, 25 Apr 2016 13:53:59 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 2
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff

PUT without auth:
$ curl -D - -X PUT http://localhost/v2/
HTTP/1.1 401 Unauthorized
Server: nginx/1.8.1
Date: Mon, 25 Apr 2016 13:54:17 GMT
Content-Type: text/html
Content-Length: 194
Connection: keep-alive
WWW-Authenticate: Basic realm="Registry realm"
Docker-Distribution-Api-Version: registry/2.0

PUT with auth:
$ curl -u usermeh -D - -X PUT http://localhost/v2/
Enter host password for user 'usermeh':
HTTP/1.1 200 OK
Server: nginx/1.8.1
Date: Mon, 25 Apr 2016 13:55:04 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 2
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff
```

**nginx.conf**

```
user  nginx;
worker_processes  1;

# error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
   upstream docker-registry {
      server localhost:5000;
   }

   include       /etc/nginx/mime.types;
   default_type  application/octet-stream;

   log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for"';

   sendfile        on;
   keepalive_timeout  65;
   client_max_body_size 0;

   map $upstream_http_docker_distribution_api_version $docker_distribution_api_version {
     'registry/2.0' '';
     default registry/2.0;
   }

   server {
      chunked_transfer_encoding on;

      location /v2/ {
         limit_except GET HEAD {
            auth_basic "Registry realm";
            auth_basic_user_file /etc/nginx/conf.d/nginx.htpasswd;
         }

         if ( $http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*\$" ) {
           return 404;
         }

         add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;

         proxy_pass                          http://docker-registry;
         proxy_set_header  Host              $http_host;   # required for docker client's sake
         proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
         proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
         proxy_set_header  X-Forwarded-Proto $scheme;
         proxy_read_timeout                  900;
      }
   }
}
```

**Comment by thaJeztah** [comment] 2016-04-25 16:07
Looks like this is a duplicate of https://github.com/docker/docker/issues/17317, please continue the discussion over there, but let me know if you think it's different.

**Closed by thaJeztah** 2016-04-25 16:07 UTC

**Comment by w-p-pueschel** [comment] 2016-04-25 16:13
Yes. Sorry for the duplicate and thanks!

**Comment by thaJeztah** [comment] 2016-04-25 17:07
No problem!
