### ISSUE TITLE
Same IP address for different containers

### ISSUE THREAD

**Issue by polonskiy** [docker/docker#18535] opened 2015-12-09 14:19 UTC
I don't know how to reproduce, but sometimes I get this:
```
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "5cf320101baed9b2326d71ca777c17eba8872465292d8b2754a82543a1813fb1",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "80/tcp": [
                {
                    "HostIp": "127.0.0.3",
                    "HostPort": "85"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/5cf320101bae",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "6a5df1a32364c0bb66525587585e05900ca9c67a2642381fd4b14471f9c74b49",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.119",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:77",
        "Networks": {
            "bridge": {
                "EndpointID": "6a5df1a32364c0bb66525587585e05900ca9c67a2642381fd4b14471f9c74b49",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.119",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:77"
            }
        }
    }
```

```
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "639dc0fca859a6bb3dc538671ab20048fa2d15aecb2f372ece58dfbbe798f19a",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/639dc0fca859",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "3e38035bd8b5fe66f48b6db284b17fd98e2d6825123265acaf102e66036c3075",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.119",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:77",
        "Networks": {
            "bridge": {
                "EndpointID": "3e38035bd8b5fe66f48b6db284b17fd98e2d6825123265acaf102e66036c3075",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.119",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:77"
            }
        }
    }
```

```
 docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

```
Containers: 307
Images: 1001
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1989
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 32
Total Memory: 251.9 GiB
Name: DS4488
ID: 5S4Z:BR7A:22PL:BHAR:GUOD:GVE4:NPA3:XODE:NOBA:35GL:ZWKF:WZAX
```

```
Linux DS4488 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by polonskiy** [comment] 2015-12-09 15:31
I have removed one of those containers:
```
docker rm -f con1
```
And then created it again:
```
docker run -d ...
```
It created with the same ip address (`172.17.0.119`)!

**Comment by polonskiy** [comment] 2015-12-09 16:01
```
$ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "e05692992835ee7c028bf07c0fd9051c38a969466d69080cf8464ac90caf03fd",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Config": [
                {
                    "Subnet": "172.17.0.1/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Containers": {
            ...
            "37e6820ad93b9a6503d66001fc067d304657128bdb329b605f6c563cd21d6074": {
                "EndpointID": "08de05854909539a395688aa0a06dfa3d511dfed44b2357404de33bdf950c98b",
                "MacAddress": "02:42:ac:11:00:77",
                "IPv4Address": "172.17.0.119/16",
                "IPv6Address": ""
            },
            "fad237b9100a9a35deec32feb5910d55061cf140e4aeaa3efae3699174f4917a": {
                "EndpointID": "3e38035bd8b5fe66f48b6db284b17fd98e2d6825123265acaf102e66036c3075",
                "MacAddress": "02:42:ac:11:00:77",
                "IPv4Address": "172.17.0.119/16",
                "IPv6Address": ""
            },
            ...
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        }
    }
]

```

**Comment by thaJeztah** [comment] 2015-12-09 16:20
Hm strange.

Can you tell me how you use docker? Thinking if there could be a race condition somehow; are you spinning up many containers, using docker-in-docker? Anything special in your setup?

**Comment by polonskiy** [comment] 2015-12-09 16:29
Looks like some collision. Does ip address based on on container name?
I have removed (`docker rm -f con1`) one of those containers, then started another container with the **same name** (`docker run --rm -it --name con1 ubuntu sleep 100`) and it got `172.17.0.119` address.

**Comment by polonskiy** [comment] 2015-12-09 16:39
140 containers on host system. One of them using host network and contains nginx as proxy.
Multiple users frequently create & destroy containers.

**Comment by polonskiy** [comment] 2015-12-09 16:42
Don't have any docker-in-docker.

**Comment by thaJeztah** [comment] 2015-12-09 16:51
Thanks for the additional information @polonskiy!

**Comment by thaJeztah** [comment] 2015-12-09 16:54
ping @mavenugo @aboch care to have a look here?

**Comment by mavenugo** [comment] 2015-12-09 17:36
@polonskiy thanks for the info. It does look strange.
When you remove and recreate the container, the IPAM reuses the freed IP. Its understandable that we see the same IP being used again. But, it is strange that IPAM is reusing an IP that is currently being used.  If you launch more containers, do they get newer ip-addresses properly ?

@aboch can you think of anything that could lead to this situation ? note : this is in 1.9.1.

**Comment by aboch** [comment] 2015-12-09 18:27
@polonskiy 
By any chance, are you starting your daemon with the `--fixed-cidr` flag ?

From the inspect o/p it does not seem this is the case, but do you remember if you did before moving to 1.9.1 ? (There is a related issue https://github.com/docker/docker/issues/18145 and the fix will be available in 1.9.2)

**Comment by polonskiy** [comment] 2015-12-09 19:52
@aboch
>  By any chance, are you starting your daemon with the --fixed-cidr flag ?

I have never used that feature.

@mavenugo

Experiment:

```
$ docker inspect --format '{{.NetworkSettings.IPAddress}}' service1 service2
172.17.0.119
172.17.0.119

$ docker rm -f service2
service2

$ docker inspect --format '{{.NetworkSettings.IPAddress}}' service1 service2
172.17.0.119
Error: No such image or container: service2

$ docker run -d --name=new1 ubuntu sleep infinity
e085230e4fd3e320cf238eeac0c8a95528f0cf3f38f7441b4878ed6746b5d245

$ docker inspect --format '{{.NetworkSettings.IPAddress}}' service1 new1
172.17.0.119
172.17.0.119

$ docker run -d --name=new2 ubuntu sleep infinity
55fc5ae4769ce61ef17d5ae692907a2fee1ae26d3d13f0407e1f77d77df12747

$ docker inspect --format '{{.NetworkSettings.IPAddress}}' service1 new1 new2
172.17.0.119
172.17.0.119
172.17.0.138

$ docker rm -f new1 new2
new1
new2

$ docker run -d --name=new3 ubuntu sleep infinity
8e677a0da2f2237b272dfcbdf737fa5225154df19b0b60184351589f3a2db10a

$ docker inspect --format '{{.NetworkSettings.IPAddress}}' service1 new3
172.17.0.119
172.17.0.119

$ docker rm -f new3
new3
```

**Comment by Soulou** [comment] 2015-12-10 20:08
You'll have more details here #18575, that's exactly the same issue, I've closed to other to centralize the discussion here, looks pretty serious to me.

**Comment by mavenugo** [comment] 2015-12-10 22:15
@polonskiy thanks for the details. From the info that you shared, the issue seems to be `119` is incorrectly seen as an available address even though its being used. Can you stop `service1` and start it again followed by other services ?
I would like to see if it was a one-time thing or a permanent issue ?
Also, do you know if there any daemon restarts and `--restart-policy` involved in the reproduction ?

**Comment by polonskiy** [comment] 2015-12-11 08:00
@mavenugo `--restart-policy` is not used.

I've removed both containers (`rm -f`), `run` them again and problem is gone. I've not tried to stop & start them.

**Comment by Soulou** [comment] 2015-12-11 09:27
In my case `--restart-policy` is no used either.

Stopping and starting them did resolve the problem. I had to remove the unreachable container, which is usually the first to get the IP

**Comment by Soulou** [comment] 2015-12-11 09:42
I've a server I've isolated where I can reproduce that any time, docker is just giving the same IPs again and again. If there are some additional information I can provide, please ask

**Comment by polonskiy** [comment] 2015-12-11 09:43
`stop` & `start` works!
I have got the same issue right now.

```
$ docker network inspect bridge | grep -A 2 -B 4 -F '0.107'
            },
            "62c9422010a467a237d65cda800aca8256571cf1ec063d3367e8c3aba3c7dbc5": {
                "EndpointID": "47fc08ae47cafe087fc5a7c2bce648ea2e0e110372ca5802c9164b9171cebb66",
                "MacAddress": "02:42:ac:11:00:6b",
                "IPv4Address": "172.17.0.107/16",
                "IPv6Address": ""
            },
--
            },
            "cc0cc1124da7812c18d9582942f3d553d552f384f9b8c679c5177db6a5df2957": {
                "EndpointID": "6c5d0fe2c48fbe3878fe34f237952a51804c0808712ec1f111221483219db970",
                "MacAddress": "02:42:ac:11:00:6b",
                "IPv4Address": "172.17.0.107/16",
                "IPv6Address": ""
            },


$ docker inspect --format '{{.NetworkSettings.IPAddress}}' 62c9422010a467a237d65cda800aca8256571cf1ec063d3367e8c3aba3c7dbc5 cc0cc1124da7812c18d9582942f3d553d552f384f9b8c679c5177db6a5df2957 
172.17.0.107
172.17.0.107

$ docker stop 62c9422010a467a237d65cda800aca8256571cf1ec063d3367e8c3aba3c7dbc5 cc0cc1124da7812c18d9582942f3d553d552f384f9b8c679c5177db6a5df2957 && docker start 62c9422010a467a237d65cda800aca8256571cf1ec063d3367e8c3aba3c7dbc5 cc0cc1124da7812c18d9582942f3d553d552f384f9b8c679c5177db6a5df2957
62c9422010a467a237d65cda800aca8256571cf1ec063d3367e8c3aba3c7dbc5
cc0cc1124da7812c18d9582942f3d553d552f384f9b8c679c5177db6a5df2957
62c9422010a467a237d65cda800aca8256571cf1ec063d3367e8c3aba3c7dbc5
cc0cc1124da7812c18d9582942f3d553d552f384f9b8c679c5177db6a5df2957

$ docker inspect --format '{{.NetworkSettings.IPAddress}}' 62c9422010a467a237d65cda800aca8256571cf1ec063d3367e8c3aba3c7dbc5 cc0cc1124da7812c18d9582942f3d553d552f384f9b8c679c5177db6a5df2957 
172.17.0.107
172.17.0.145
```

**Comment by Soulou** [comment] 2015-12-11 09:48
I confirm that stopping and starting (and not restarting) helps a little :-)

**Comment by mavenugo** [comment] 2015-12-11 12:44
@polonskiy @Soulou thanks again. since you reproduced it again, we would love to know more on the reproduction steps. Also it will help if you can run the daemon in debug mode (`-D`) and capture daemon logs.

**Comment by Soulou** [comment] 2015-12-11 12:46
Actually I can reproduce it on a server in production with lots of containers, not sure I'll be able if I empty the server and restart the daemon, as the first occurence of the problem has been kind of random (it was working ok for at least 1 week) Without debug mode, there absolutely nothing weird in the logs, that's sure :)

**Comment by aboch** [comment] 2015-12-11 17:02
It could be related to https://github.com/docker/docker/issues/18145

**Comment by aboch** [comment] 2015-12-14 16:59
@polonskiy @Soulou 
I was able to reproduce via unit test. I can confirm the issue is caused by the same bug that also caused #18145, which fix was brought in docker/docker via #18106.

Because of the bug, some specific address release patterns may corrupt the db which holds the allocated addresses.
I am not aware of a workaround, other than restarting the daemon after removing the /var/lib/docker/network/files/local-kv.db file.

Fix is in master and 1.9.2 will have it.

**Comment by polonskiy** [comment] 2015-12-14 17:35
:+1:

**Comment by polonskiy** [comment] 2015-12-14 17:36
Thanks!

**Comment by thaJeztah** [comment] 2015-12-14 17:50
Thanks @aboch!

I'll close this issue, for those interested, builds from master are available on https://master.dockerproject.org, but **don't** run those on production, they may contain bugs. Also note that master builds are for the upcoming 1.10 release, so contain lots of other changes :)

**Closed by thaJeztah** 2015-12-14 17:50 UTC
Labels: group/networking, kind/bug, priority/P1

**Comment by Soulou** [comment] 2015-12-15 09:37
That's great, thanks @aboch for this fix

**Comment by guentherjedenastik** [comment] 2018-02-07 09:59
I noticed the same issue today on a pretty new docker installation.

In `/etc/default/docker` i modified the docker opts like
`DOCKER_OPTS='--bip=172.17.0.1/16 --dns=172.17.0.1 --dns=8.8.8.8'`

and started a dnsdock and datadog agent:
`docker run --name dnsdock -d --restart=always -v /var/run/docker.sock:/var/run/docker.sock -p 172.17.0.1:53:53/udp tonistiigi/dnsdock --verbose`
`docker run -d --name dd-agent \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -v /proc/:/host/proc/:ro \
  -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
  -v /:/mnt/root_partition:ro \
  -v /PATH/datadog/conf.d:/conf.d:ro \
  -e API_KEY=SOMETHING \
  -e SD_BACKEND=docker \
  -e NON_LOCAL_TRAFFIC=false \
  --restart=always \
  datadog/docker-dd-agent:latest
`

Both containers received corret ip's 172.17.0.2 and 172.17.0.3.
Then i started a client project using a simple docker compose
and those two ip's got reassigned to the monogodb and redis container which are the first and third containers in the compose file.

I'll try to fix this later on with a new network for this composer file, but i just wanted to mention that the same ip problem still exists and restarting or removing didnt work.

```
Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.18.0, build 8dd22a9
```

**Comment by OsamaJBR** [comment] 2018-03-27 08:40
Hey, I'm still having this issue.

I'm using a network called proxy that is exposed to public (80,443) and default networks per stack. What I've notice that sometimes I get a totally wrong response from other services.

When I checked that I saw that the backend IP is common between multiple containers. I used the following script to check that.

```
# docker service ls | awk '{print $2}' | grep -v NAME| xargs -I% docker service ps % | awk '{print $1}' | grep -v ID | xargs -I% docker inspect % | jq '.[0]["NetworksAttachments"][] | select (.Network.Spec.Name == "proxy") | .Addresses[]' | sort | uniq -c  | sort -nr 
      4 "10.0.0.224/24"
      2 "10.0.0.17/24"
      1 "10.0.0.97/24"
      1 "10.0.0.93/24"
      1 "10.0.0.91/24"
      1 "10.0.0.89/24"
      1 "10.0.0.84/24"
      1 "10.0.0.8/24"
      1 "10.0.0.80/24"
      1 "10.0.0.79/24"
      1 "10.0.0.75/24"
      1 "10.0.0.73/24"
      1 "10.0.0.7/24"
      1 "10.0.0.72/24"
      1 "10.0.0.69/24"
      1 "10.0.0.66/24"
      1 "10.0.0.54/24"
```
I'm using Ubuntu 16, Docker version 17.12.1-ce.

**Comment by abhi** [comment] 2018-03-27 13:18
@OsamaJBR the latest ce 18.03 has all the fixes to address these issues.

**Comment by hoexter** [comment] 2018-10-24 15:48
@abhi Are you sure that is the case?
We're using 18.03.1~ce-0~debian and still see things like
``
for x in $(docker ps -q); do docker inspect --format "{{.NetworkSettings.IPAddress}}" $x; done|sort|uniq -c|grep -v '1 '
      2 172.17.0.35
``
