### ISSUE TITLE
Create a build tool file so application will run

### ISSUE THREAD

**Issue by Gmanweb** [docker/docker#26698] opened 2016-09-19 09:32 UTC
**Description**
I need to create build environment for my Application.
My Application no longer builds correctly due to old versions of software.
I need to create an environment where builds will run correctly

**The software I need installed :**

1. maven v3.2.2
2. Nodejs 4.4.7
3. git
4. Python 2.7.9
5. grunt
6. Protractor v1.6.1
7. npm install - grunt-cli

The whole build process is driven by Maven.

New to docker so I am just looking for advise on the best way to achieve this.

**Comment by thaJeztah** [comment] 2016-09-19 10:25
The GitHub issue tracker is not intended as a general support, and https://forums.docker.com or the #docker IRC channel is probably a better location to ask this question. Could you move this over there? I'll close this issue here because this is not a bug

**Closed by thaJeztah** 2016-09-19 10:25 UTC
