### ISSUE TITLE
Error response from daemon: Error looking up volume plugin flocker: Plugin not found

### ISSUE THREAD

**Issue by jonathan-kosgei** [docker/docker#18920] opened 2015-12-27 08:26 UTC
I have 2 centos 7.1 nodes and I'm trying to get flocker running on it. I've followed the installation steps exactly however when it comes to running the following command to test to see if flocker-docker-plugin works:

docker run -v apples:/data --volume-driver flocker busybox sh -c "echo hello > /data/file.txt"

I get the error:

Error response from daemon: Error looking up volume plugin flocker: Plugin not found

BUG REPORT INFORMATION
$ docker version

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

$docker info

Containers: 7
Images: 19
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-524072-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.011 GB
 Data Space Total: 107.4 GB
 Data Space Available: 24.55 GB
 Metadata Space Used: 2.331 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.3.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 1.638 GiB
Name: sc-test2
ID: AU3N:3GYD:Y6B5:5GE3:EKDX:4ZWR:SGMU:33IU:IWQQ:ELWG:OTXY:4FXC
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

$uname -a

Linux sc-test2 3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

STEPS TO REPRODUCE

Run"

 docker run -v apples:/data --volume-driver flocker busybox sh -c "echo hello > /data/file.txt" 

after following the manual install instructions for flocker.

Error:

Error response from daemon: Error looking up volume plugin flocker: Plugin not found

**Comment by thaJeztah** [comment] 2015-12-27 12:37
Looks like you're following the instructions here; https://docs.clusterhq.com/en/1.8.0/config/enabling-agent-service.html#enabling-agent-service, and support for using flocker is https://clusterhq.com/flocker/support/

Could you use one of the channels mentioned in that link? Given that this is an issue with Flocker, I think it's best to ask for support via ClusterHQ first (it could be an incorrect configuration/installation of the plugin)

I'll close this issue for the reasons above, but feel free to comment here after I've closed, thanks!

**Closed by thaJeztah** 2015-12-27 12:37 UTC

**Comment by jonathan-kosgei** [comment] 2015-12-27 12:55
Done. I'd assumed it was docker that wasn't picking up the plugin. The installation was very straightforward. But thanks.

**Comment by thaJeztah** [comment] 2015-12-27 13:03
@jonathan-kosgei if it turns out to be a bug in docker after you've checked with ClusterHQ please ping me here, then I'll reopen the issue

**Comment by jonathan-kosgei** [comment] 2015-12-27 13:06
Will do. Thanks :)

**Comment by fireking77** [comment] 2016-01-03 02:02
Hi Guys,

I do not want to bother you, but I have the exactly same issue with CentOS7 + flocker 1.8.0....
sorry but is this issue solved? somewhere? can you please point me to the right link...

thanks...
 Darvi

**Comment by jonathan-kosgei** [comment] 2016-01-03 06:08
Hey fireking,
It's no bother at all.
Unfortunately I have not found a solution to the issue. You can track new
info on the stackoverflow question here:
http://stackoverflow.com/questions/34472300/flocker-docker-plugin-doesnt-work?noredirect=1#comment56781501_34472300

**Comment by fireking77** [comment] 2016-01-03 08:07
thanks dude, i am going to follow it...
Darvi

**Comment by rongnguyen** [comment] 2016-02-03 02:45
Hi Guys,

I have the same issue with Jonathan. 
I am using 
  - Ubuntu 14.04
  - Docker 1.9.1
  - Flocker: 1.9.0
  - uname: 3.19.0-49-generic #55~14.04.1-Ubuntu SMP Fri Jan 22 11:24:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Is there anyway to solve "Error response from daemon: Error looking up volume plugin flocker: Plugin not found" issue?

Thank community!

**Comment by HibatAllah** [comment] 2017-01-13 18:44
Hi ,

I have the same issue of rongnguyen , 
the environnent description :

Ubuntu 14.04
Docker 1.12.3
  i use this documentation to install flocker with docker and swarm ; 
https://flocker-docs.clusterhq.com/en/latest/docker-integration/manual-install.html

Is there anyway to solve this error please :  "Error response from daemon: Error looking up volume plugin flocker: Plugin not found" 

Thanks ,

**Comment by zoechi** [comment] 2017-02-14 10:14
Just run into this with 
`Version:      1.11.2`
`3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux`

**Comment by thaJeztah** [comment] 2017-02-14 18:45
@zoechi `-d projects` will be looking for a driver named `projects`, if no such driver exists, it will fail.

**Comment by zoechi** [comment] 2017-02-14 19:30
@thaJeztah thanks a lot. Found it already, forgot to remove the comment.

**Comment by thaJeztah** [comment] 2017-02-14 21:47
Based on the comments above, this looks like a configuration issue (the driver is not installed, or not configured properly). Given that this is not a bug in the docker code base, I'm gonna lock the conversation here to prevent it from collecting random questions w.r.t. using volume drivers.

Since ClusterHQ unfortunately stopped to exist, I suggest going to the https://github.com/ScatterHQ/flocker repository for questions about using the flocker volume driver (a number of ex-ClusterHQ employees started that repository to maintain flocker 🙌 )

If you have other issues with volume drivers/plugins and suspect it's a bug in _docker_ not the plugin, please open a new issue with details
