### ISSUE TITLE
docker attach [container] hangs, requires input

### ISSUE THREAD

**Issue by tywkeene** [docker/docker#8521] opened 2014-10-12 13:28 UTC
Hi everyone,
When I `docker attach [container]` docker hangs for a second, but it's not *really* hanging, it just requires input to get to the container shell.

This doesn't seem so bad but it can be confusing if you're expecting the shell to just come up.

Figured I'd just get this up here, even if it's low priority and see what everyone says.

Cheers.

`docker version`
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3
Git commit (server): fa7b24f

`uname -a`
Linux phoenix 3.17.0-rc7 #1 SMP Sun Oct 12 01:35:13 MDT 2014 x86_64 Intel(R) Core(TM)2 Duo CPU E7400 @ 2.80GHz GenuineIntel GNU/Linux

**Comment by tsvetann** [comment] 2015-02-05 13:47
Same thing on Client version: 1.4.1

**Comment by MrMMorris** [comment] 2015-02-12 19:54
I am hitting a similar issue when attaching to a container. It just hangs and I can't do anything to stop it. I used to use docker exec so I guess I'll stick with that... 

version 1.5.0

**Comment by benjohnson77** [comment] 2015-03-26 01:36
same here.

**Comment by IngoS11** [comment] 2015-04-04 03:30
same here.

**Comment by IngoS11** [comment] 2015-04-04 03:37
docker exec -it [container-id] bash worked for me.

**Comment by singhvarinder** [comment] 2015-04-12 04:32
docker attach has still same hang issue with 1.5 version, "docker exec -i -t [cont-id] bash" worked for me too.

**Comment by floomy** [comment] 2015-05-27 07:33
+1, any updates on this?

**Comment by kylechadha** [comment] 2015-06-04 12:29
+1

**Comment by ViktorNova** [comment] 2015-08-06 22:39
+1 
Furthermore, it completely takes over the terminal while "waiting for input", and does not respond to ctrl+z, ctrl+z, etc, leaving me with the option of closing the entire teminal window on my end (which in my case also terminates the ssh session to the Docker server)

**Comment by cpuguy83** [comment] 2015-09-15 16:39
Hmm, I don't think this is actually something solvable since `attach` is not running a new process in the container, it's literally attaching you to the current process state, therefore not really a bug.

The API has support for attaching "with logs", which would replay everything that has happened in the container since it was created....the CLI can be extended to support this (should be super super simple to add if someone wants to take a crack at it).

**Comment by pydima** [comment] 2015-10-03 20:11
#dibs

**Comment by MrMMorris** [comment] 2015-10-04 00:55
My question is how did this become a feature if it doesn't work?

**Comment by pydima** [comment] 2015-10-04 08:02
As far as I understood, it works, but for some use cases the behavior is not really obvious. So it's a feature because the task is adding 'logs' parameter to the 'attach' command.

**Comment by pydima** [comment] 2015-10-06 20:02
@cpuguy83 I had a look on this issue and it seems to me that 'logs' parameter wouldn't help in this case. The problem is that we are reading container stdout with ```ReadBytes('\n')``` when writing data to a log file https://github.com/docker/docker/blob/master/daemon/logger/copier.go#L47, so in this case if we attach to container with running bash we wouldn't see the last bash prompt, because there is no '\n' byte at the end of the prompt. It'll look like this
```
root@ec51f1c959ef:/go/src/github.com/docker/docker# docker attach --logs=true af
root@af022be5e40f:/# echo true
true

```
 I thought about writing to log messages with a particular size, let say 200 bytes in one log message, but I don't think that it's a good idea, at least log will be unreadable in this case. 
So what do you think?

**Comment by cpuguy83** [comment] 2015-10-06 20:34
@pydima Yep, you're right.

**Comment by pydima** [comment] 2015-10-07 18:44
@cpuguy83 Do you think that adding 'logs' parameter would be useful in this case?

**Comment by cpuguy83** [comment] 2015-10-07 18:45
Not for fixing this particular problem.

**Comment by bosswissam** [comment] 2015-10-11 01:06
+1

**Comment by vijayviji** [comment] 2015-10-16 04:01
Hey guys. Is there any update on this?

**Comment by cpuguy83** [comment] 2015-10-16 15:23
@vijayviji See the discussion above...

**Comment by vijayviji** [comment] 2015-10-16 16:51
@cpuguy83 I read the discussion. I couldn't understand the conclusion. Are we going to add 'logs' parameter or not? Even though last bash prompt won't be there, it's still a useful feature since it won't look like the attach command is hanging at least as we'll see the output. Is it not possible to read last set of bytes without '\n'? I don't understand the code fully.

**Comment by cpuguy83** [comment] 2015-12-17 16:08
@pydima I bet we could output whatever is currently in the logger's buffer (which buffers until it reaches a '\n')

**Closed** 2016-02-10 14:32 UTC
Labels: exp/beginner, kind/enhancement, status/claimed

**Comment by stramel** [comment] 2016-03-20 20:10
I am having this issue on v1.10.3. Is the accepted way of doing this using `docker exec -it <container> bash`?

**Comment by cpuguy83** [comment] 2016-03-20 20:22
@stramel I don't understand the question.
But this is fixed and will be available in 1.11.

**Comment by jamshid** [comment] 2016-04-13 20:20
FWIW I'm having hella problems with `docker exec bash script.sh` sometimes hanging, seems to be related to the script redirecting a command's stdout/stderr to `tee`. I'm *still* having the problems with 1.11.0-rc3 (docker for mac), though I've also seen it on 1.9 and 1.10 in different environments. 

Sorry I haven't been able to narrow down to a reproducible test case (it's part of a jenkins job), just thought I'd share. Using `docker exec -it` instead seems to workaround it. `faketty docker exec -it` works if you don't have a tty.
```
# linux only, not compatible with OSX script
function faketty { script -qfc "$(printf "%q " "$@")"; } 
```

**Comment by GaretJax** [comment] 2016-07-08 08:23
@cpuguy83 could you point me to where/how this was fixed? I'm having the same issue with docker 1.11.2 and would like to dig into it, but I just found https://github.com/docker/docker/pull/21048 and it looks like only marginally related (my containers are all starting and running correctly).

**Comment by thaJeztah** [comment] 2016-07-08 08:27
@GaretJax this issue was fixed in https://github.com/docker/docker/issues/19835

**Comment by GaretJax** [comment] 2016-07-08 08:37
Thanks a lot @thaJeztah :)

**Comment by dszmaj** [comment] 2017-01-05 22:27
still getting this error on windows 10

**Comment by thaJeztah** [comment] 2017-01-06 10:24
@dszmaj most likely a different issue, but it's best to open a new issue with more details. Depending on "what" you're running, you may have to open that issue in another issue tracker; If you installed "Docker for Windows" (https://docs.docker.com/docker-for-windows/), please open an issue in the Docker for Windows issue tracker; https://github.com/docker/for-win/issues

**Comment by dszmaj** [comment] 2017-01-06 16:41
thanks @thaJeztah :) will do as you said

**Comment by ejholmes** [comment] 2017-03-10 08:54
fwiw, I'm still able to reproduce this issue on docker 1.12 with:

```
docker attach $(docker run -d -it ubuntu bash)
```

```console
$ docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64
```

```console
$ docker -D info
Containers: 167
 Running: 3
 Paused: 0
 Stopped: 164
Images: 1331
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1240
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.39-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.951 GiB
Name: moby
ID: 6IRC:XMEP:CVJR:NABO:GYOD:DSFW:FC2H:UTMH:ED52:RV6H:U5F2:HMKE
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 58
 System Time: 2017-03-10T08:52:36.46583267Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: ejholmes
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

```console
$ uname -a
Darwin Erics-MacBook-Pro.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

**Comment by thaJeztah** [comment] 2017-03-10 09:39
@ejholmes I'm not able to reproduce this on docker for mac (17.03), and docker 1.12.5 (running in a container). It's possible though that it's specific to that version of Docker for Mac (Docker for Mac uses a proxy to communicate with the daemon in the VM). If it's still an issue on the current version, could you open a new issue?

**Comment by japrogramer** [comment] 2017-07-17 02:35
I can still reproduce this issue 
Name            : docker
Version         : 1:17.06.0-1
4.11.9-1-ARCH
linux 4.11.9-1

**Comment by ATPNazlit** [comment] 2018-03-16 16:34
Same here, It happened to me twice . I was coding with vi and everything hung. Then i tried to attach, i did restart and stop start but nothing has changed.

**Comment by thaJeztah** [comment] 2018-03-16 16:45
@ATPNazlit if it's a reproducible case, please open a new issue with the full details that are requested in the issue template that shows when you open the issue. The issue reported here is close to four years old, and likely not related to any issue on current versions of Docker.

**Comment by isaacwalkercox** [comment] 2018-12-13 12:01
Still having this issue on the latest version of docker on a Ubuntu 18.04 host machine. Any ideas?

**Comment by madankumar-t** [comment] 2019-04-08 16:23
Awesome

**Comment by swalkersbw** [comment] 2020-01-24 04:09
I'm a newbie at docker (so plse don't rain-it-down on me if this isn't helpful) but I was having same issue as a lot of the peeps above and found that a 'docker inspect <container-id>' showed I had these three {{.Config}} configuration settings all set to false even though I started with 'docker run -it ...'
            "AttachStdin": false,
            "OpenStdin": false,
            "StdinOnce": false,
which might explain why when I try to 'docker attach' (to the running container) or 'docker start -a' (my stopped container) it appears to just 'hang' and no amount of commands or carriage-returns changes anything?
I'm using an image I didn't create myself so it's entirely possible these configurations are correct and there's a good reason for them so I'm just offering this information in case it helps anyone to understand possibly why they're seeing the same behaviour. 

Maybe someone who understands this a bit more than me can shed some light on the stdin settings in the image all being set to false ?

Thanks.
