### ISSUE TITLE
Docker 1.12.1 hanging at build step "Setting up ca-certificates-java"

### ISSUE THREAD

**Issue by amolsh** [docker/docker#26475] opened 2016-09-12 05:22 UTC
OS:
Operating System: Ubuntu 14.04.4 LTS
 Kernel: Linux 4.2.0-27-generic
Architecture: x86_64

Dockerfile:
FROM phusion/baseimage:0.9.19
ENV BAMBOO_HOME /home/bamboo/bamboo-agent-home
ENV BAMBOO_SERVER http://192.168.56.102:8085
RUN apt-get -y install software**-properties-common && \
    add-apt-repository -y ppa:openjdk-r/ppa && \
    apt-get update && \
    apt-get -y install openjdk-8-jdk
COPY bamboo-agent-*.jar ${BAMBOO_HOME}/bin/
COPY run /etc/service/bamboo_agent/
RUN useradd bamboo:bamboo && \
    chmod a+x /etc/service/bamboo_agent/run && \
    chown -R bamboo:bamboo /home/bamboo
VOLUME $BAMBOO_HOME/xml-data/build-dir

isuue:
image building stuck in  "Setting up ca-certificates-java" , tried several times.

Setting up openjdk-8-jdk:amd64 (8u91-b14-3ubuntu1~16.04.1) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/appletviewer to provide /usr/bin/appletviewer (appletviewer) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode
Setting up ca-certificates-java (20160321) ...

**Comment by AkihiroSuda** [comment] 2016-09-12 05:33
I guess this is a duplicate of https://github.com/docker/docker/issues/18180#issuecomment-193708192 , and it would be fixed by upgrading the kernel to 4.2.0-30.35 or later (Ubuntu 15.10?)

**Comment by amolsh** [comment] 2016-09-12 12:18
thanks, you are right

**Closed** 2016-09-12 12:18 UTC
