### ISSUE TITLE
default-ulimits seems broken in daemon.json

### ISSUE THREAD

**Issue by pcarrier** [docker/docker#22309] opened 2016-04-25 17:43 UTC
Docker 1.10.3, binary from https://get.docker.com/builds/Linux/x86_64/docker-1.10.3

```
# cat /etc/docker/daemon.json
{ "default-ulimits": { "nofile": "64000:64000" } }
# docker daemon
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: nofile
```

I expect this to work like `--default-ulimit nofile=64000:64000`.

**Comment by vdemeester** [comment] 2016-04-25 17:45
@pcarrier I would guess    `{ "default-ulimits": ["nofile=64000:64000"] }` would work though.

**Comment by pcarrier** [comment] 2016-04-25 17:46
@vdemeester it's documented as a map at https://docs.docker.com/engine/reference/commandline/daemon/

**Comment by pcarrier** [comment] 2016-04-25 17:48
with `{ "default-ulimits": [ "nofile=64000:64000" ] }`:

```
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: default-ulimits
```

**Comment by vdemeester** [comment] 2016-04-25 17:52
@pcarrier my bad :sweat_smile:. It's also definitely in 1.11 :sweat:.

**Comment by tiborvass** [comment] 2016-04-25 18:41
@calavera can you explain why configValuesSet in https://github.com/docker/docker/blob/28b7dc51aec6a237af187badfc1953eb9dbbb142/daemon/config.go#L274 flattens the settings? I don't remember why we did that and it seems to be the cause for this and #22311

**Comment by thaJeztah** [comment] 2016-06-27 18:22
ping @calavera ^^ PTAL

**Comment by allencloud** [comment] 2016-10-17 17:01
I think maybe we could close this issue since #25566 has been merged. WDYT @vdemeester @pcarrier

**Closed** 2016-10-17 17:02 UTC
Labels: kind/bug, priority/P3
