### ISSUE TITLE
To free disk space after removing a container

### ISSUE THREAD

**Issue by muchweb** [docker/docker#7758] opened 2014-08-27 12:34 UTC
1. I have run [mongo](https://registry.hub.docker.com/_/mongo/) container
2. Container requires about 4GB to run, which was reserved
3. I have stopped and removed a container using `docker stop` and `docker rm`
4. Disk space is still taken in `/var/lib/docker` and there is no obvious way to free it

**Comment by goloroden** [comment] 2015-01-15 08:54
Any update on this?

**Comment by cpuguy83** [comment] 2015-01-15 23:22
@goloroden I don't think we will automatically remove volumes when the container is removed, it's dangerous and a breaking change.

**Comment by unclejack** [comment] 2015-02-02 11:04
`docker rm -v` needs to be used in order to remove a container's volumes. These volumes can be looked up and removed by hand. However, @cpuguy83 will continue to work on volumes and managing volumes should be easier.

There are more issues like this one which are caused by leftover volumes. I'm going to close this issue now.

**Closed by unclejack** 2015-02-02 11:04 UTC

**Comment by muchweb** [comment] 2015-02-02 11:09
>These volumes can be looked up and removed by hand.

@unclejack, could you please specify the exact way of removing leftover volumes, once the container is deleted?

This issue was about the lack of _obvious_ way to fix it, thus not resolved.

**Comment by thaJeztah** [comment] 2015-02-02 15:15
@muchweb There's a proposal to add volume management in docker. That proposal would enable you to list (and delete) volumes, both "in use" and "orphaned" (left-over) volumes. The proposal can be found here: https://github.com/docker/docker/pull/8484.

However, that proposal isn't accepted yet, but the author of that proposal also created an external tool, called "docker-volumes" that offers the same functionality. Docker-volumes can be found here: https://github.com/cpuguy83/docker-volumes and the easiest way to run it is to download a binary from the [releases page](https://github.com/cpuguy83/docker-volumes/releases)

**Comment by muchweb** [comment] 2015-02-02 15:19
@thaJeztah, thank you! :+1: `docker-volumes` looks very handy.

**Comment by frank-dspeed** [comment] 2015-02-02 20:55
alternate is my more simply docker-volume-cleanup util from http://github.com/dockerimages/docker-tools

example output:

 >> Volumes (in use) <<
/
/opt/fileserver/adt-2/DATA/solr
/opt/fileserver/adt-wp/DATA
/opt/fileserver/adt-wp/DATA/config/default.vcl
/opt/fileserver/adt-wp/DATA/mysql
/opt/fileserver/adt-wp/DATA/www
/opt/fileserver/docker-registry/tmp
/opt/fileserver/gitlab/DATA/data/repositories

 >> Orphaned Volumes <<
/var/lib/docker/vfs/dir/029e03c746e4e7969852c4ae0e27d72d68f3f829a6d5d4e536bbe11ca04ac53d
/var/lib/docker/vfs/dir/02d477b9638de43fc992e31289e00de433031839d1bcc372bc4419eb1d528bc7
/var/lib/docker/vfs/dir/03b1fa68377931a87f320e1e08b4e2c83c2e718f96cbbb864974840dc521b51b
/var/lib/docker/vfs/dir/03db5c40a3ff0d0dfec3641eb7a76284858a7d3601e079b25e730fd624d24e23
/var/lib/docker/vfs/dir/04bdacfa87ee08d87994759d3116bca09b244c0be66a126203fd1686336eae0b
/var/lib/docker/vfs/dir/081a5b548408b020db4e52eb0a88e54e8b82ab76aa3cb276593da39822411d4b
/var/lib/docker/vfs/dir/09bc6ab2117e38de173e6a8217de582cde3578e0ddb060382b90362dc1ea1b2b
/var/lib/docker/vfs/dir/0a21126b56f7ae9e63e23943cdb945042227b1b96ce866d9bb704c00e57171c6
/var/lib/docker/vfs/dir/0bbe471ae2e0ec0e5cec84ba44e9c353b661a923d77931b1f1354b98304e33d7
/var/lib/docker/vfs/dir/0c515eee24a1f96dacc26bb6d40f20945a4c8e3033bb8d34076ede5cf978ca6e
/var/lib/docker/vfs/dir/0ce2a13a25e3ad3bf7e6f3489c65d964de5be62e280a78a9155990ced4ebc4ff
/var/lib/docker/vfs/dir/0e851ad03b6f82b4aacd75ad00b34ca97a436a9a926757e4af150d23cc2814c0
/var/lib/docker/vfs/dir/0ed66974fb24c447e5346a23d17aab8bc9dd3ed075ce31212a20fb8ed7068933

use docker-volume-cleanup -f to delet all orphaned volumes

**Comment by wattletimber** [comment] 2016-06-06 05:47
Hi Guys am ahving serios my docker container is increasing everyday by 1 gig how can i create space? see image below
<img width="748" alt="screen shot 2016-06-06 at 6 43 50 am" src="https://cloud.githubusercontent.com/assets/19662899/15812940/d552876e-2bba-11e6-8110-f0bd5cb979e5.png">

**Comment by thaJeztah** [comment] 2016-06-06 09:05
@wattletimber if that container does a lot of logging, it may be the JSON log file that keeps growing; make sure you start your container with `--log-opt max-size=[something]` (optionally with `--log-opt max-files=[something]`. See https://docs.docker.com/engine/admin/logging/overview/#json-file-options
