### ISSUE TITLE
Issue with -v flag in running a container

### ISSUE THREAD

**Issue by SurabhiBorgikar** [docker/docker#17432] opened 2015-10-28 10:35 UTC
Hi. I'm trying to do the following with Docker Quickstart terminal..  I get this error even though the path specified with -v flag is an unix path.

`$ winpty docker run -it -v /data --name mycontainer busybox`
`invalid value "C:\\Program Files\\Git\\data" for flag -v: \Program Files\Git\data is not an absolute path
See 'docker run --help'.`

**Comment by thaJeztah** [comment] 2015-10-28 12:23
@SurabhiBorgikar this is a duplicate of https://github.com/docker/docker/issues/12751 and https://github.com/docker/docker/issues/12590, and is caused by msys automatically converting paths to "windows" paths. 

You can prevent this from happening by using a *double* slash at the start of the path, i.e. `//data`. see this comment; https://github.com/docker/docker/issues/12751#issuecomment-96288101

I'm ging to close this issue, but feel free to comment here after I've closed

**Closed by thaJeztah** 2015-10-28 12:23 UTC
Labels: group/windows

**Comment by SurabhiBorgikar** [comment] 2015-10-29 05:34
Hi. Yes I've already seen those posts before posting mine. Even using *double slash* did not work for me. May be I should try using something else instead of Docker quickstart terminal for Volumes. Thanks!

**Comment by thaJeztah** [comment] 2015-10-29 18:10
@SurabhiBorgikar oh, that's unfortunate; I think I've seen using quotes `'` worked in other cases.

**Comment by krishna81m** [comment] 2016-01-26 19:32
This hack seems to work like a charm if you have downgraded to 1.9 from the AUFS issues in 1.9.1
```
docker create -v //c/Users/myuser:/myuser --name data hello-world
winpty docker run -it --rm --volumes-from data ubuntu
```
