### ISSUE TITLE
docker start does not map the exported port to host nic

### ISSUE THREAD

**Issue by langdead** [docker/docker#25738] opened 2016-08-16 00:40 UTC
After below chain of operation, exposed port of bridge network won't work. 

docker run => docker stop => docker start again.

**Output of `docker version`:**
Tried on both coreos and debian

```
core@core-01 ~ $ docker --version
Docker version 1.10.3, build 3cd164c
core@core-01 ~ $ uname -a
Linux core-01 4.6.3-coreos #2 SMP Mon Jul 18 06:10:39 UTC 2016 x86_64 Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz GenuineIntel GNU/Linux
core@core-01 ~ $


vagrant@jessie:~$ sudo docker --version
Docker version 1.12.0, build 8eab29e
vagrant@jessie:~$ uname -a
Linux jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
vagrant@jessie:~$
```

**Output of `docker info`:**

```
core@core-01 ~ $ docker info
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 27
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.3-coreos
Operating System: CoreOS 1068.8.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.942 GiB
Name: core-01
ID: 7RGV:V2PN:ADHL:Q3S6:NCKV:EJYF:DH7G:FLIQ:FYN3:ECFI:EYWQ:7F5C
core@core-01 ~ $


vagrant@jessie:~$ sudo docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 494.4 MiB
Name: jessie
ID: 4DBK:MVWG:O2OT:GFPJ:5EE5:XJFN:VMPU:PVIA:DTU4:U5RS:CRJZ:HO2L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
vagrant@jessie:~$
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**

```
docker run --name=gogs -p 10022:22 -p 10080:3000 -d gogs/gogs
curl host_ip:10080 #succeeds
docker stop gogs
docker start gogs
curl host_ip:10080 # fails saying "Connection refused"
curl docker_ip:10080 #succeeds
```

After several days' trial, I found `run --net=host *` will work, but with the cons that exporting port is not supported.

```
docker run --name=gogs --net=host -d gogs/gogs
curl host_ip:3000 #succeeds
docker stop gogs
docker start gogs
curl host_ip:3000 #succeeds
```

thx!

Regards
Langdead

**Comment by langdead** [comment] 2016-08-16 00:42
The issue here is not the same as #20918

**Comment by thaJeztah** [comment] 2016-10-11 22:59
Are you still able to reproduce this on the current release (1.12)?

**Comment by mavenugo** [comment] 2016-10-22 16:58
@aboch can you confirm if this can be closed ?

@langdead can you pls confirm if it is seen in 1.12.2 ?

**Comment by mavenugo** [comment] 2016-11-01 17:47
We couldnt reproduce this issue with 1.12.3. Closing this issue now. Pls comment if you see this issue also pls share the `iptables -nvL` & `iptables -t nat -nvL` before and after the container is started.

**Closed by mavenugo** 2016-11-01 17:47 UTC
Labels: area/networking, kind/bug, status/more-info-needed, version/1.10
