### ISSUE TITLE
Containers can't reach outside network randomly...

### ISSUE THREAD

**Issue by rrfeng** [docker/docker#14313] opened 2015-07-01 10:51 UTC
I don't know what happened or what I did cause this problem.

when problem comes, no container can reach outside, I used ping and tracepath, in containers, only can reach the HOST IP.

Restart the docker service can fix this.

- on EC2, AMI Linux

Is there anyone else who has this problem?

**Comment by LK4D4** [comment] 2015-07-01 17:35
I think it is duplicate of #14073

**Closed by LK4D4** 2015-07-01 17:35 UTC

**Comment by rrfeng** [comment] 2015-07-02 00:05
yes，thank you.
