### ISSUE TITLE
Can we sign our private images?

### ISSUE THREAD

**Issue by sourav82** [docker/docker#13958] opened 2015-06-16 06:32 UTC
As announced in Docker 1.3 release we should be able to sign our images before pushing it to registry.

Is this feature already implemented in latest version or still it is only with official images?

**Comment by sourav82** [comment] 2015-06-16 06:33
Specifically, I would like to sign my images and push to private registry (distribution).

**Comment by thaJeztah** [comment] 2015-06-16 07:20
No, signing isn't currently possible, but being worked on.

See for reference; https://github.com/docker/distribution/issues/632#issuecomment-112147360

I'm going to close this issue, because this is not a bug in Docker. It's a feature that's
still being worked on. Feel free to comment here after the issue is closed.

**Closed by thaJeztah** 2015-06-16 07:20 UTC
Labels: Distribution, kind/question
