### ISSUE TITLE
Docker daemon start with devicemapper can't get container file in another container.

### ISSUE THREAD

**Issue by nashasha1** [docker/docker#20904] opened 2016-03-03 09:32 UTC
Docker daemon start with devicemapper can't get container file in another container.

`docker version`:

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-19610-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.821 GB
 Data Space Total: 107.4 GB
 Data Space Available: 4.025 GB
 Metadata Space Used: 1.479 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-29-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 1
Total Memory: 1.954 GiB
Name: ip-172-31-44-158
ID: CW46:NU4H:RGYC:KRGE:I3VX:DDET:C7IY:ZXH3:RXZF:6XFC:7JKF:UALN
Username: sincera
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

`uname -a`:
Linux ip-172-31-44-158 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Run docker on AWS

List the steps to reproduce the issue:
1. docker run -d --name A  ubuntu:latest
2. docker run -d --name B -v /var/lib/docker/devicemapper/mnt:/docker ubuntu:latest
3. docker run -d --name C ubuntu:latest
4. docker exec -ti B /bin/bash

I can find all A's file in /docker/[A's container id]/, but /docker/[C's container id]/ is empty.

Then I found all container's file exist which start early than B, all container's file is not exist if it start after B.

Then I try start docker daemon with `aufs`. It is all right.(with diff dir. I write some when container start, so diff dir is not empty.)

Is that a devicemapper's bug?

**Comment by phemmer** [comment] 2016-03-03 13:29
No, that's not a bug. The files in /var/lib/docker are generally meant for docker to use, not for you to access directly.
To do what you want, take a look at https://docs.docker.com/engine/userguide/containers/dockervolumes/#creating-and-mounting-a-data-volume-container

**Comment by thaJeztah** [comment] 2016-03-03 17:14
Indeed, this is not a bug, `/var/lib/docker` is managed by the docker daemon, and should be an implementation detail. Working with those files directly is 100% at your own risk and not supported

I'll close this issue, but feel free to comment here

**Closed by thaJeztah** 2016-03-03 17:14 UTC

**Comment by nashasha1** [comment] 2016-03-07 03:38
Thanks.

Two questions.

1. Can I do sth like this? Mount different path in container.
    a. docker run -d --name BASEVOLUME -v /volume/:**/mnt_base/** ubuntu:latest
    b. docker run -d --name A --volumes-from BASEVOLUME:**/mnt_a/** ubuntu:latest
2. mount sub_dir to container
   a. docker run -d --name BASEVOLUME -v /volume/:/mnt/ ubuntu:latest
   b. docker run -d -name A --volumes-from** BASEVOLUME/a** ubuntu:latest
   c. docker run -d -name B --volumes-from **BASEVOLUME/b** ubuntu:latest
