### ISSUE TITLE
Container losing connection to internet

### ISSUE THREAD

**Issue by AstonJ** [docker/docker#14073] opened 2015-06-21 15:28 UTC
I am using Docker as per the Discourse set-up guide, however, the container keeps losing connection to the internet.

Sometimes restarting Docker works, sometimes, rebuilding the Discourse app.

My `/etc/resolv.conf` looks like:

```
nameserver 127.0.0.1
nameserver 213.133.98.98
nameserver 213.133.99.99
nameserver 213.133.100.100
nameserver 2a01:4f8:0:a0a1::add:1010
nameserver 2a01:4f8:0:a111::add:9898
nameserver 2a01:4f8:0:a102::add:9999
```
My ` /etc/sysconfig/docker` contains:
```
# /etc/sysconfig/docker
#
# Other arguments to pass to the docker daemon process
# These will be parsed by the sysv initscript and appended
# to the arguments list passed to docker -d

other_args=
DOCKER_CERT_PATH=/etc/docker
DOCKER_OPTS="--dns 208.67.222.222 --dns 208.67.220.220"


# Location used for temporary files, such as those created by
# # docker load and build operations. Default is /var/lib/docker/tmp
# # Can be overriden by setting the following environment variable.
# # DOCKER_TMPDIR=/var/tmp
```

I am using CentOS 6.5 with latest kernel installed and latest Docker version.

It appears this is a common problem - is there any way to verify a correct set-up? Anyone know how to fix this issue?

# BUG REPORT INFORMATION

**docker version**:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**docker info:**
```
Containers: 1
Images: 12
Storage Driver: devicemapper
 Pool Name: docker-9:2-38273681-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.207 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104.2 GB
 Metadata Space Used: 3.301 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 4.0.4-1.el6.elrepo.x86_64
Operating System: <unknown>
CPUs: 8
Total Memory: 47.16 GiB
Name: rock.unitepublishing.net
ID: HWMD:C72I:UFEA:BLEL:7WJE:JOZ7:KKTY:EHB3:IFG6:IJAW:X3SF:UVVN
WARNING: No swap limit support
```

**uname -a:**
```
Linux rock.unitepublishing.net 4.0.4-1.el6.elrepo.x86_64 #1 SMP Mon May 18 12:45:35 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**List the steps to reproduce the issue:**
1. n/a

**Describe the results you received:**
Container loses connection to internet sporadically 

**Describe the results you expected:**
Container able to access internet

**Provide additional info you think is important:**
I am using the publicly available Discourse image (in case you need to look at it)

**Comment by AstonJ** [comment] 2015-06-21 15:41
Hi @GordonTheTurtle sorry about that, I have updated the issue with the information required.

**Comment by unclejack** [comment] 2015-06-21 15:58
@AstonJ It seems your kernel is `4.0.4-1.el6.elrepo.x86_64`. Using this kernel on RHEL 6 / CentOS 6 is unsupported. Please use CentOS 7 if you want a newer kernel.

Please make sure you're not running a custom firewall (firewalld or something else).

You also need to make sure your system is fully updated using `yum update`.

**Comment by AstonJ** [comment] 2015-06-22 00:52
Hi @unclejack thanks for the reply.

I forgot to say I am running the CSF firewall (http://configserver.com/cp/csf.html) are there any considerations firewall-wise?

I have updated the system with `yum update`.

I am not sure how to go about upgrading to CentOS 7, would you know if this is easy enough to do? The server has several sites on it (I use HAProxy to divert traffic to the docker container or the other apache sites). If not, do you have any other suggestions I could try to try and resolve this issue please?

**Comment by AstonJ** [comment] 2015-06-23 13:19
Just a follow up to say this happened again, and this time I disabled the CSF firewall but it didn't make any difference (so I don't think it's CSF related).

Restarting Docker worked though.

It also seems this problem is fairly common, so I'm wondering if you can remember any other suggestions you might have posted previously? Could it be something to do with my `/etc/resolv.conf`?

**Comment by johnw188** [comment] 2015-06-24 07:53
I'm running into the same issue on Centos 6 with the following kernel:

`Linux 3.10.78-1.el6.elrepo.x86_64 #1 SMP Wed May 13 14:37:49 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux`

My images have connectivity for a while after the daemon is started up, but then they lose connectivity and the only way I've found of restoring it is to restart the docker daemon.

**Comment by AstonJ** [comment] 2015-06-24 12:24
@johnw188 Just out of interest, what does your `/etc/resolv.conf` and `/etc/sysconfig/docker` look like?

**Comment by johnw188** [comment] 2015-06-24 17:26
`/etc/resolve.conf` (pointing at our internal DNS:
```search [internal domain]

nameserver 10.52.9.20
nameserver 10.52.9.21

options timeout:2 attempts:2 rotate```

`/etc/sysconfig/docker`:

```# /etc/sysconfig/docker
#
# Other arguments to pass to the docker daemon process
# These will be parsed by the sysv initscript and appended
# to the arguments list passed to docker -d

other_args="--insecure-registry [internal docker registry]"
DOCKER_CERT_PATH=/etc/docker

# Resolves: rhbz#1176302 (docker issue #407)
DOCKER_NOWARN_KERNEL_VERSION=1

# Location used for temporary files, such as those created by
# # docker load and build operations. Default is /var/lib/docker/tmp
# # Can be overriden by setting the following environment variable.
# # DOCKER_TMPDIR=/var/tmp```

**Comment by johnw188** [comment] 2015-06-24 20:18
A bit more info - on the VM I'm working on right now it happens 13 minutes after the first request to an external ip address. Doesn't seem to matter how many requests are made, I've done one a second on one trial and one a minute on another, both die after around 13 minutes.

**Comment by johnw188** [comment] 2015-06-25 01:21
@AstonJ You can workaround the issue by passing `--net=host` to your run command. This will cause your containers to use their hosts network stack and will disable linking of containers, however (as docker can't/shouldn't update the `/etc/hosts` of the host machine)

**Comment by AstonJ** [comment] 2015-06-25 23:43
Thanks @johnw188. Do you know of any limitations or negatives associated with this? I wonder if @unclejack or @GordonTheTurtle or anyone else in the Docker team recommend this as an appropriate fix?

**Comment by johnw188** [comment] 2015-06-26 02:14
It's not really an appropriate fix but it depends on what you're doing. I think there are some security implications, and as I mentioned above it prevents you from linking containers. I'm using it on some internal CI machines that aren't exposed to the outside so I'm not super concerned but your mileage may vary.

**Comment by AstonJ** [comment] 2015-06-30 14:30
Thanks for your help @johnw188 but I don't want to compromise security in any way.

@unclejack and @GordonTheTurtle - What is the supported kernel version with my OS please? This issue is continuing, any help or advice you could offer would be appreciated.

**Comment by unclejack** [comment] 2015-06-30 21:35
@AstonJ You should upgrade to CentOS 7 or RHEL 7. The problem is most likely caused by your custom firewall which runs a script periodically and breaks the firewall. Please check if that's the case.

**Comment by johnw188** [comment] 2015-06-30 22:19
@unclejack I tried disabling iptables with a `sudo service iptables stop` and confirmed that the process was stopped, but hit the same exact issue.

More feedback - I can ping the IP of the host machine, but not others on the same network. See logs below (the machine is at `10.52.225.27`)

```
root@77d461257ebd:/# ping 10.52.225.27
PING 10.52.225.27 (10.52.225.27) 56(84) bytes of data.
64 bytes from 10.52.225.27: icmp_seq=1 ttl=74 time=0.032 ms
64 bytes from 10.52.225.27: icmp_seq=2 ttl=74 time=0.026 ms
64 bytes from 10.52.225.27: icmp_seq=3 ttl=74 time=0.023 ms
^C
--- 10.52.225.27 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.023/0.027/0.032/0.003 ms
root@77d461257ebd:/# ping 10.52.225.26
PING 10.52.225.26 (10.52.225.26) 56(84) bytes of data.
^C
--- 10.52.225.26 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms

root@77d461257ebd:/# 
```

Do you have any idea of what services to run in verbose mode/what to check? Something must change from the initial request working to the same request failing a few minutes later, but I just don't know where to look. I'm pretty sure docker's advanced networking options are powerful enough to work around whatever is causing the issue, but I can't figure out what to change.

It takes about 13 minutes from first executing `ping [other machine]` successfully, to that exact same command failing. It doesn't seem to matter how many requests are made, I've tried one a second and one a minute with the same results.

**Comment by johnw188** [comment] 2015-06-30 22:29
Also inbound connections are fine. I first noticed the issue with a Jenkins container - I had it running for a couple of days while I configured everything, first builds worked fine, but then a couple of builds in it was unable to connect to the source code repo to pull down the latest files. I could still connect to it on port 80 like I always did, the container just seemed to lose the ability to initiate requests. Restarting the docker daemon fixed the problem for 13 minutes, just like the above case of pinging another box.

**Comment by AstonJ** [comment] 2015-07-02 21:59
Looking at the iptables rules I've got this: https://gist.github.com/AstonJ/0bbff5d03cd900d46e2c 

Docker is mentioned a few times - can you see anything that might be causing the issue @unclejack?

*I've also posted a thread on CSF's forum, but nobody has replied yet.*

**Comment by unclejack** [comment] 2015-07-02 22:09
@AstonJ If you're running any kind of custom firewall which sets up custom rules, I'm not surprised to see that you're having problems. People have reported issues in the past with custom iptables based firewalls with cron jobs which would kill the rules set by Docker or which would insert conflicting rules.

My recommendation would be to set up a test host without that firewall you're using and figure out if you can reproduce the issue. This applies to everyone seeing this problem - please exclude all custom firewalling by trying to reproduce on a separate system without the custom firewall you're using.

**Comment by AstonJ** [comment] 2015-07-02 22:25
Thanks @unclejack. Could you give me an outline of the rules set by Docker please? I can pass these on to the CSF team and see if they can work out if there may be a conflict (and perhaps then update the Firewall to make it more Docker-friendly).

**Comment by AstonJ** [comment] 2015-07-06 16:49
I don't want to jinx it, and I don't know if this is just a coincidence (or whether it is actually having any affect) but since adding `DOCKER_OPTS="--iptables=false"` to my `/etc/sysconfig/docker` I haven't had any further issues.

(Anyone know if there are any downsides to this?)

**Comment by AstonJ** [comment] 2015-07-14 15:37
It happened again today - but that's about 10 days without any problems.

Can someone please let me know what the supported kernel is with CentOS 6.6 please? (I only upgraded the kernel as I thought it was recommended for Docker.)

Also, any ideas what the recommend Firewall settings are for the server? I'd be happy to drop the CSF firewall for APF & BFD if that would make things easier.

**Comment by AstonJ** [comment] 2015-07-15 12:06
Hi @unclejack, sorry to bother you, but would you know if Docker prefers Ubuntu 14.04 or CentOS 7?

I am going to reformat my box and can go with either distro. I'm hoping we'll make more use of Docker containers so am happy to go with which you think is the more stable/performant distro.

**Comment by cpuguy83** [comment] 2015-07-15 13:32
@AstonJ We provide packages for both platforms, so either one is fine.

**Comment by AstonJ** [comment] 2015-07-15 13:49
Thanks @cpuguy83 - do you (the Docker team) prefer one over the over? Specifically in terms of stability and performance?

If they are pretty much equal I will go with CentOS 7 as I have used CentOS for years.

**Comment by AstonJ** [comment] 2015-07-19 17:39
@cpuguy83 @unclejack  Sorry to keep bothering you both, but is CentOS 6.6 (with its standard kernel) supported?

I have tried both Ubuntu 14.04 and CentOS 7 on a test server but finding they are a little too quirky/unstable compared to CentOS 6 which has just been rock solid.

Are there any benefits to using CentOS 7 over 6 in terms of Docker performance or stability?

**Comment by thaJeztah** [comment] 2015-08-16 11:36
@AstonJ RHEL6/CentOS6 is no longer supported with Docker 1.8, see https://github.com/docker/docker/issues/14365. So definitely CentOS 7 if you're going for CentOS

**Comment by thaJeztah** [comment] 2015-10-05 10:30
I'm closing this issue, because this looks to be an issue with the setup. Also, we no longer support CentOS/RHEL 6.x platforms.

If you're still running into problems, please join the #docker IRC channel and ask there for assistance

**Closed by thaJeztah** 2015-10-05 10:30 UTC
Labels: group/networking

**Comment by AstonJ** [comment] 2015-10-05 13:27
Sorry, forgot to update - I upgraded (fresh installed) to Centos 7 and all issues disappeared (although Docker has to be restarted if the firewall is restarted).

**Comment by thaJeztah** [comment] 2015-10-05 13:33
Good to hear @AstonJ! I think that's a known "issue" (i.e., it's known that docker needs to be restarted after that)

**Comment by AstonJ** [comment] 2015-10-05 13:38
Yeah, and it's not actually much of a problem as you rarely restart FirewallD anyway. It's much nicer than IPtables imo :-) Thanks for the reply :+1:

**Comment by nilesh1013** [comment] 2016-02-02 14:15
https://github.com/docker/docker/issues/15172#issuecomment-178591819

**Comment by juliengk** [comment] 2016-03-21 18:51
Hey @AstonJ 

Try those scripts, that will help when csf is restarted.
https://github.com/juliengk/csf-pre_post_sh and https://github.com/juliengk/csf-post-docker

**Comment by AstonJ** [comment] 2016-03-21 18:59
HI @juliengk I ended up moving to FirewallD, however this was posted on the CSF forums as a fix:

>This issue affects any iptables reloads as the docker rules are lost.
>
To resolve this create the following in /etc/csf/csfpre.sh
>
iptables -t nat -N DOCKER
iptables -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
iptables -t nat -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
iptables -t nat -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
>
iptables -t filter -N DOCKER
iptables -t filter -A FORWARD -o docker0 -j DOCKER
iptables -t filter -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -i docker0 ! -o docker0 -j ACCEPT
iptables -t filter -A FORWARD -i docker0 -o docker0 -j ACCEPT
>
A csf -r will now reload the docker rules and networking inside the container should continue.

**Comment by juliengk** [comment] 2016-03-21 19:14
good to know.

The script add the nat rules for the expose ports of containers

**Comment by Mehrdad-Dadkhah** [comment] 2017-01-18 14:05
@AstonJ @juliengk 
use it to avoid error: Chain already exists! when you or lfd need restart csf


```
chain_exists()
{
    [ $# -lt 1 -o $# -gt 2 ] && { 
        echo "Usage: chain_exists <chain_name> [table]" >&2
        return 1
    }
    local chain_name="$1" ; shift
    [ $# -eq 1 ] && local table="--table $1"
    iptables $table -n --list "$chain_name" >/dev/null 2>&1
}

chain_exists DOCKER && iptables -X DOCKER
chain_exists DOCKER nat && iptables -t nat -X DOCKER

iptables -t nat -N DOCKER
iptables -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
iptables -t nat -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
iptables -t nat -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE

iptables -t filter -N DOCKER
iptables -t filter -A FORWARD -o docker0 -j DOCKER
iptables -t filter -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -i docker0 ! -o docker0 -j ACCEPT
iptables -t filter -A FORWARD -i docker0 -o docker0 -j ACCEPT
```

**Comment by klodoma** [comment] 2017-03-31 13:11
Is/will there be some official documentation for these setup? 
This issue(docker + firewall) caused many headaches out there. Imo docker team should support some basic setup for major firewalls (officially and not in issues)

**Comment by cpuguy83** [comment] 2017-03-31 13:30
The thing is, there is no such thing as "restarting iptables". iptables isn't started or stopped, it's not a process. It's a set of rules that get loaded into the kernel.
If someone goes mucking around with iptables there's not much that can be done. There's no way for Docker to know that an admin didn't intend to break Docker's rules.

We could poll iptables at some interval and re-inject rules, but this is both inefficient and runs afoul of potential intentional changes made by the admin.

Docker, for the most part (I can think of one case where this is not the true), does not assume it owns the firewall and tries to be a good citizen of other users of iptables.

If something is going around clearing out the iptables rules and not re-instating them that is a bug in that software.

@aboch Anything to add? Any ideas for work-arounds for this?

**Comment by aboch** [comment] 2017-03-31 23:27
Agree with @cpuguy83 comment, docker tries to do its best not to step on other iptables rules.

Consider that if firewalld is running when docker is started, all the iptables chains/rules docker programs on the host are deferred to [firewalld](https://github.com/docker/docker/blob/v17.03.1-ce/vendor/github.com/docker/libnetwork/iptables/iptables.go#L379). So that when firewalld refreshes, it should reapply the docker programmed stuff. (At least this is the theory, obviously this logic must have some hic hup given the number of issues reported)
