### ISSUE TITLE
Docker re-pushing layers that already exist

### ISSUE THREAD

**Issue by ahawkins** [docker/docker#21563] opened 2016-03-28 05:56 UTC
**Output of `docker version`:**

```
Docker version 1.10.3, build 20f81dd
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 18
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 36
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: nomad
ID: X2GW:QDJA:C5TA:JVIA:GFGF:7JQ3:TAD7:AUDZ:4MXB:3AGQ:7CRD:BBTF
Debug mode (server): true
 File Descriptors: 24
 Goroutines: 74
 System Time: 2016-03-28T05:48:48.120102054Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: ahawkins
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Steps to reproduce the issue:**
1. push an image
2. push the same image again

See the push logs below.

```
--- Pushing docker image
docker tag saltside/kpi-collector saltside/kpi-collector:dfc2764
docker push saltside/kpi-collector:dfc2764
The push refers to a repository [docker.io/saltside/kpi-collector]
9bacd71114e5: Pushed
3794c15d11df: Pushed
b8bcfc8384a2: Pushed
b71bdca960dc: Pushed
697744b2f42a: Pushed
5f70bf18a086: Pushed
1e31ca6be1c6: Pushed
2926d01a2ccc: Pushed
7a2764f609e7: Pushed
f5b219c22487: Pushed
35a0078b4d2e: Pushed
fb49515ec5d8: Pushed
bd750002938c: Pushed
917c0fc99b35: Pushed
dfc2764: digest: sha256:5c7b3e780e123a3e920eb832cac5c804ee5639bb85c650fe7a7296ae44cf01f4 size: 17481
--- Pushing docker image
docker tag saltside/kpi-collector saltside/kpi-collector:dfc2764
docker push saltside/kpi-collector:dfc2764
The push refers to a repository [docker.io/saltside/kpi-collector]
9bacd71114e5: Layer already exists
3794c15d11df: Layer already exists
b8bcfc8384a2: Layer already exists
b71bdca960dc: Layer already exists
697744b2f42a: Pushing 2.048 kB
5f70bf18a086: Layer already exists
697744b2f42a: Pushed
2926d01a2ccc: Pushing 1.385 MB
7a2764f609e7: Pushing 2.201 MB/117.6 MB
1e31ca6be1c6: Pushed
2926d01a2ccc: Pushed
7a2764f609e7: Pushed
f5b219c22487: Pushed
35a0078b4d2e: Pushed
fb49515ec5d8: Pushed
bd750002938c: Pushed
917c0fc99b35: Pushed
dfc2764: digest: sha256:5c7b3e780e123a3e920eb832cac5c804ee5639bb85c650fe7a7296ae44cf01f4 size: 17481
```

As you can see the layer ID are the same and the final SHA is the same as well. 

**Describe the results you received:**

Docker is pushing layers when it does not need to. 

**Describe the results you expected:**

To not push layers that already exist in the remote registry

**Additional information you deem important (e.g. issue happens only occasionally):**

This seeminly started last week at one point. Was there a change to the registry in production? I've since deleted the repo in our company's docker hub account and tried with a new docker machine (given I'm on OSX). This same behavior is happening on other machines with other docker versions.

**Comment by dmcgowan** [comment] 2016-03-28 21:49
@ahawkins: do you continue to see this issue? We are having trouble reproducing and trying to figure out if it was a intermittent failure. How long have you been experiencing this issue and which versions of Docker have you also seen the problem with.

**Comment by icecrime** [comment] 2016-03-30 16:33
I'm removing this one from the milestone as we have difficulty reproducing.

Ping @aaronlehmann @tonistiigi: now you're subscribed in case something comes up :wink:

**Comment by Viknet** [comment] 2016-04-19 10:08
Docker version 1.10.3 on my OS X also had this issue. It's gone after update to 1.11 and pushed layers are detected correctly as "Layer already exists".

**Comment by thaJeztah** [comment] 2016-04-19 14:45
thanks @Viknet 

@ahawkins I'll close this issue, because we are unable to reproduce this, but feel free to comment if you're still seeing this issue

**Closed by thaJeztah** 2016-04-19 14:45 UTC
Labels: group/distribution, status/more-info-needed
