### ISSUE TITLE
aws cloudwatch logs awslogs-stream markup

### ISSUE THREAD

**Issue by ajohnstone** [docker/docker#19158] opened 2016-01-07 09:59 UTC
When specifying a fluentd-tag value, you can use the following markup tags:

{{.ID}}: short container id (12 characters)
{{.FullID}}: full container id
{{.Name}}: container name

It would be ideal to apply this to the awslogs-stream property.

**Comment by thaJeztah** [comment] 2016-01-07 10:55
ping @samuelkarp :)

**Comment by thaJeztah** [comment] 2016-01-07 11:02
oh, and, for reference, that feature was added/improved in https://github.com/docker/docker/pull/15384

(note that `fluentd-tag` was deprecated in favor of `tag`)

**Comment by ajohnstone** [comment] 2016-01-07 14:12
tag is not valid for the aws logs driver, I tried that already :)

**Comment by thaJeztah** [comment] 2016-01-07 14:18
@ajohnstone sorry if I wasn't clear; I meant that the `fluentd-tag` shouldn't be used for fluentd now, but the `tag`. You're correct that aws logs doesn't support it currently

**Comment by samuelkarp** [comment] 2016-01-07 18:37
This looks like a duplicate of https://github.com/docker/docker/issues/17747 to me.

**Comment by thaJeztah** [comment] 2016-01-08 00:06
Oh you're right! @ajohnstone I'll close this one, because it's a duplicate, but please continue the discussion in https://github.com/docker/docker/issues/17747

**Closed by thaJeztah** 2016-01-08 00:06 UTC
Labels: area/logging, kind/feature
