### ISSUE TITLE
When running with -t only one /dev/tty

### ISSUE THREAD

**Issue by jachin** [docker/docker#27765] opened 2016-10-26 05:45 UTC
**Description**

When I fire up a docker container in interactive move `-t -i` bash launches just fine, but when I try to do something else (in my case running `salt-ssh`) I get:

> Failed to spawn the VT: out of pty devices

I'm guessing the issue is related to the fact that when I run `ls /dev/tty*` I only see one result:

> /dev/tty

In the previous version of Docker (that I was running) everything worked fine.

**Output of `docker version`:**

```
Docker version 1.12.3-rc1, build bad4d12, experimental
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 1.12.3-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.951 GiB
Name: moby
ID: 4HIY:WAIQ:MOJG:HYAR:SEU7:KVVR:VQUD:NWYJ:7DVF:JR72:SVSB:E2VE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 29
 System Time: 2016-10-26T05:42:33.932139828Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Comment by justincormack** [comment] 2016-10-26 11:37
Hi, this appears to be a bug in 1.12.3-rc1, it is the `/dev/pts/ptmx` device that is missing (symlinked from `/dev/ptmx`). This is the multiplexor device for `pty`s.

**Comment by justincormack** [comment] 2016-10-26 13:43
Hi, this appears to only be an issue on docker for mac/win, so we will fix it there with a patch release as soon as possible.

**Comment by justincormack** [comment] 2016-10-26 13:53
I am actually unclear as to the cause yet, it may need fixes in both places.

**Comment by justincormack** [comment] 2016-10-26 16:01
We are about to release a patch release for Docker for Mac and Windows.

As there is no upstream issue, I am closing this here.

**Closed by justincormack** 2016-10-26 16:01 UTC
Labels: platform/desktop

**Comment by justincormack** [comment] 2016-10-26 18:17
The updated versions of Docker for Mac and Windows are out now, please upgrade, apologies for the issue.

**Comment by jachin** [comment] 2016-10-26 19:03
Way to knock that out. Nice work!
