### ISSUE TITLE
Dockerfile: rm can't remove xxx Directory not empty (CentOS 7, overlayfs)

### ISSUE THREAD

**Issue by discostur** [docker/docker#27214] opened 2016-10-07 14:54 UTC
**Description**

I'm running docker on CentOS 7 and when i change the storage driver vom Devicemapper to overlay i'm not able to delete files while building a docker-image.

**Steps to reproduce the issue:**
1. yum install docker
2. systemctl stop docker docker-storage-setup
3. rm -rf /var/lib/docker/
4. sed -i '/OPTIONS=/s/--selinux-enabled//' /etc/sysconfig/docker
5. echo "STORAGE_DRIVER=overlay" >> /etc/sysconfig/docker-storage-setup
6. systemctl start docker-storage-setup docker
7. git clone https://github.com/42wim/matterbridge.git
8. docker build -t matterbridge:test .

**Describe the results you received:**

```
rm: can't remove '/go/src/github.com/42wim/matterbridge/.git/hooks': Directory not empty
rm: can't remove '/go/src/github.com/42wim/matterbridge/.git/info': Directory not empty
```

**Describe the results you expected:**

The docker-build command should simply delete the files inside the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

As i wrote with storage-driver "devicemapper" this works as expected but with "overlayfs" i can't remove directories while the remove command is part of another layer then the files were created. If i put the remove (rm) command within the same layer (docker-command) i can remove the files:

for example:

instead of

```
COPY . /go/src/github.com/42wim/matterbridge
RUN apk update && apk add go git gcc musl-dev ca-certificates \
        && rm -rf /go \
```

this works:

```
COPY . /go/src/github.com/42wim/matterbridge \
        && rm -rf /go \
```

**Output of `docker version`:**

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 6
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: xfs
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.28.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 5.671 GiB
Name: hostname
ID: xxx
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
CentOS Linux release 7.2.1511 (Core) 
```

Thanks
Kilian

**Comment by LK4D4** [comment] 2016-10-07 15:35
ping @justincormack I think this was fixed in kernel, but not sure.

**Comment by discostur** [comment] 2016-10-10 06:27
Running the following one:

```
Linux 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by justincormack** [comment] 2016-10-11 10:23
Yes, this is fixed in later kernels, and may be backported to some earlier ones. Building your container works fine for me (4.4.24). It may be that you have to wait until Centos 7.3 before it is fixed, if you are on the latest kernel for 7.2, I am not sure.

**Comment by justincormack** [comment] 2016-10-11 10:24
I am going to close this as there is nothing we can do in Docker as it is a kernel bug.

**Closed by justincormack** 2016-10-11 10:24 UTC
Labels: area/builder, area/kernel, area/storage/overlay, version/1.10

**Comment by szmi** [comment] 2016-10-14 13:47
@justincormack: any idea which kernel change is required to fix this?

**Comment by m4ce** [comment] 2017-02-21 13:36
Does anyone know if this was fixed in CentOS 7.3?

**Comment by marcoreni** [comment] 2017-02-21 14:15
`rm -rf` works for us (slowly) when the xfs fs is formatted with `ftype = 1` option. 

Reference here: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html

**Comment by m4ce** [comment] 2017-02-21 19:29
@marcoreni, thanks for the tip, that solves it indeed!

**Comment by murrayju** [comment] 2017-07-13 18:23
Does anyone have any idea what kernel version(s) this is fixed in? This is bringing my Docker builds to a halt, with `rm -rf anydir` returning `ENOTEMPTY`.

```
$ uname -a
Linux machine 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)

$ docker --version
Docker version 17.06.0-ce, build 02c1d87
```

I'd love to hear about any sort of workaround!

**Comment by murrayju** [comment] 2017-07-13 19:58
I finally found a solution by digging though the mess of related issues. Commenting here since this was my starting point, and maybe it will help someone else.

I installed the latest 4.12 kernel, and it didn't make a difference. This is actually a problem with the overlay fs in centos. The solution was to reformat the filesystem where the docker config is stored (`/var/lib/docker`) with some flags: `mkfs -t xfs -n ftype=1 /PATH/TO/DEVICE`

The problem is better described in #27358, but the solution is best explained in #29873.
[More details from RedHat](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html)

**Comment by xieqihui** [comment] 2019-06-04 10:46
I encountered the same issue with the following `docker info`:
```
Server Version: 18.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
```

The cause for my case was that the kernel version was too old. The problem got sovled after I upgrade kernel version to `3.10.0-957.12.1.el7`

**Comment by alswl** [comment] 2020-03-17 10:28
Confirm which storage driver you are using.
`overlay2` required kernel 4.1, which CentOS/ RHEL using 3.10.0-514 or higer.

You can switch to `devicemapper` storage by this:

```
cat /etc/docker/daemon.json
{
  "storage-driver": "devicemapper"
}

```

Reference:

> Version 4.0 or higher of the Linux kernel, or RHEL or CentOS using version 3.10.0-514 of the kernel or higher. If you
> use an older kernel, you need to use the overlay driver, which is not recommended.

> devicemapper is supported, but requires direct-lvm for production environments, because loopback-lvm, while zero-
> configuration, has very poor performance. devicemapper was the recommended storage driver for CentOS and RHEL, as
> their kernel version did not support overlay2. However, current versions of CentOS and RHEL now have support for
> overlay2, which is now the recommended driver.
