### ISSUE TITLE
Unclear error messages creating Swarm service with image from local library

### ISSUE THREAD

**Issue by alexellis** [docker/docker#29205] opened 2016-12-07 09:30 UTC
**Description**

unauthorized: authentication required when creating service with attachable network access.

This is using the ARM 32-bit release from: https://github.com/docker/docker/releases/tag/v1.13.0-rc3

**Steps to reproduce the issue:**
```
docker network create --attachable -d overlay funker
mrythowxwse3ocwo92l5k80hl

docker service create --name add --network funker add
unable to pin image add to digest: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

tgpvi3qvcafui6tuh7evrykbr
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
pi@pi2swarm7:~ $ docker version
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:48:38 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:48:38 2016
 OS/Arch:      linux/arm
 Experimental: false

Linux pi2swarm7 4.4.19-v7+ #906 SMP Tue Aug 23 15:53:06 BST 2016 armv7l GNU/Linux
```

**Output of `docker info`:**

Slightly redacted:

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 17
Server Version: 1.13.0-rc3
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 Is Manager: true
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.0.34
 Manager Addresses:
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Kernel Version: 4.4.19-v7+
Operating System: Raspbian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 925.5 MiB
Name: pi2swarm7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: alexellis2
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpuset support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2016-12-07 13:55
ping @mavenugo

**Comment by thaJeztah** [comment] 2016-12-07 13:56
actually; `add:latest` does not seem like a valid image on hub?

**Comment by alexellis** [comment] 2016-12-07 13:58
@thaJeztah it's an image in my local library.

**Comment by thaJeztah** [comment] 2016-12-07 14:04
@alexellis is this on a single node swarm?

**Comment by alexellis** [comment] 2016-12-07 14:06
Yes - single node swarm with this node being the manager.

```
pi@pi2swarm7:~ $ docker service create --name add --network funker add
unable to pin image add to digest: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

gnrm0ujk564zzxao5xezn6m0v
pi@pi2swarm7:~ $ docker service ps add
NAME                IMAGE  NODE       DESIRED STATE  CURRENT STATE         ERROR  PORTS
add.1.n83lowkmp1oq  add    pi2swarm7  Running        Running 1 second ago         
pi@pi2swarm7:~ $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
a3b4662060a5        add:latest          "npm start"         6 seconds ago       Up 4 seconds        9999/tcp            add.1.n83lowkmp1oqvr8xqvuej83xh
pi@pi2swarm7:~ $ 
```

**Comment by alexellis** [comment] 2016-12-07 14:11
@thaJeztah when pushing the image to the hub first this doesn't give the error, but prior to 1.13 this never gave the three errors included in this report. from a UX point of view I have no idea what they mean.

```
pi@pi2swarm7:~ $ docker service create --name add --network funker alexellis2/pi_add_func:latest
tx3u5dqqxrogq9e018m4m21gl
```

Also - it is useful to be able to test services which are not pushed to the Docker hub even in a single-node swarm. Case in point would be the serverless work Justin and Ben are putting together. It's the readme file I was following and they aren't pushing their image to the hub:

https://github.com/bfirsh/funker

>  And building it:
> $ docker build -t add .
> To run the function, you create a service:
> $ docker network create --attachable -d overlay funker
> $ docker service create --name add --network funker add

**Comment by thaJeztah** [comment] 2016-12-07 14:29
did this work on docker 1.12 (which also performed a pull when deploying a service)?

docker 1.13 pins images by digest to ensure all instances of a service run exactly the same version of the image; this resolution is handled through the registry. I suspect the error is due to this.

@nishanttotla could you have a look?

**Comment by mavenugo** [comment] 2016-12-07 14:31
@alexellis 

1. Pls confirm if this is a confusing error message issue (or) the service isnt being created.
2. This cannot be an "--attachable" network only issue. This should happen for a regular `service create` even without any `--network` option.

**Comment by alexellis** [comment] 2016-12-07 14:32
I get the same without specifying a network, so I've altered the name of the issue.

```
pi@pi2swarm7:~ $ docker service create --name add2 add
unable to pin image add to digest: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

vf6p4da988czw6v7f6ng4r7fl
```

I have done this many times before with 1.12 and I'm sure this error is new.

**Comment by justincormack** [comment] 2016-12-07 15:55
I also got similar messages with rc3 but not previously. Not with
attachable networks. The services were created though.

**Comment by nishanttotla** [comment] 2016-12-07 18:45
@alexellis @justincormack Starting 1.13, Docker tries to pin service images to a specific image digest at the time of creation. This happens by contacting the registry to retrieve the digest (#28173). If the digest pinning fails, a warning is returned, but the service is still created because of precisely this use case of local images. The reason you aren't seeing warnings when you push to the registry is for the same reason.

From the description above, I see that the service was successfully created, but it does seem like the UX is a little confusing in that case. I'll think about how we can make this better.

cc @aaronlehmann 

P.S. These warnings were introduced in #28421 (and follow-up to #28173), so you've correctly noticed that they weren't present before 1.13-rc3.

**Comment by alexellis** [comment] 2016-12-07 19:47
Hi @nishanttotla - I appreciate you following up on this, thanks for the detailed response. Let me know if you raise something to track this so I can re-visit at that point.

**Comment by nishanttotla** [comment] 2016-12-07 19:59
@alexellis sure thing! Quick question though -- have you tried providing the digest for your local image, instead of just the name? If you did that, you won't see this warning (as per #28265).

I'm not sure if it makes sense to get rid of the warnings when the image is present locally but without a digest, because in a larger cluster, it will result in local images being used on nodes that already had them, while (potentially different digest) images being downloaded on others.

**Comment by thaJeztah** [comment] 2016-12-08 12:14
> From the description above, I see that the service was successfully created, but it does seem like the UX is a little confusing in that case. I'll think about how we can make this better.

I just checked this issue (was AFK when I commented above), and can confirm that the service is created as usual and a `0` exit code is returned, so there's no regression since 1.12, purely cosmetic / UX

Maybe the error should include "how" docker proceeded (creating service using local image cache)?

**Comment by subfuzion** [comment] 2017-01-01 12:59
I can confirm that the service is successfully created on a single node swarm (1.13.0-rc4-beta34.1), but also get the same message.

**Comment by mostolog** [comment] 2017-01-10 11:23
Hi.

Also happening with rc5, and -as others- also though it was an error.

My two cents:
**Should this message be printed only when a registry is configured?** (--with-registry-auth)
```
unable to pin image myImage:myTag to digest: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

Can image field include tag and shortened digest on default _docker ps_? (IMHO, more user friendly)
> publicimage:tag@sha256:34bca633b63b91643...
(I can create an issue for that)

Regards

**Comment by nishanttotla** [comment] 2017-01-11 16:41
@mostolog pinning to digest isn't related to `--with-registry-auth`. This would show up also for non-private registry.

Also, I'm going to submit a PR to suppress digest in default `docker ps` output, will get it done before 1.13.

**Comment by mostolog** [comment] 2017-01-12 08:48
Thanks @nishanttotla 

Regarding the "warning" message: as many others I was confused with it...
As you stated: "_This happens by contacting the registry to retrieve the digest (#28173). If the digest pinning fails, a warning is returned_"

IIUC:
Docker image picking process checks locally first (before looking on any registry). According to that, -as I provided image:tag- it should match and use it without any warning or checking any registry.
At most, it should check local image digest without problems.

So, I don't understand what the message means. Could you elaborate a bit to better understand what's going on and improve/remove/whatever the message behavior?
Thanks

**Comment by subfuzion** [comment] 2017-01-21 05:46
Hi @nishanttotla. The [explanation](https://github.com/docker/docker/issues/29205#issuecomment-265556245) behind the warning makes perfect sense, but it is not an ideal solution right now since it causes needless anxiety during a typical development scenario, i.e., working with images that haven't been assigned digests because they haven't yet been pushed to any registry. `Errors`, `denied` and `unauthorized` appearing in message sound sinister because they should be taken seriously and not ignored -- which is of course what you want in a cluster scenario as you noted (but even then the current phrasing doesn't quite make it clear what's going on if you don't already understand the issue).

I don't know how to phrase it best, but a naive verbose attempt is something like the following:

    Warning: unable to pin image pinger to digest because it wasn't found in the registry.
    This can lead to problems in a cluster because the image on each node might not be identical
    (even though they might have the same tag).

    Warning: unable to pin image pinger to digest because authentication is required to access
    the registry. This can lead to problems in a cluster because the image on each node might not
    be identical (even though they might have the same tag).

Wording stuff is hard!  ;)

**Comment by natemurthy** [comment] 2017-02-10 05:39
I'm also observing this authentication warning with `Docker version 1.13.1, build 092cba3`. I recall not having this issue with `Docker version 1.12.3, build 6b644ec` however.

**Comment by alexellis** [comment] 2017-02-11 10:55
@nishanttotla wording this concisely looks like it could be difficult. Another option might be to go with the initial text plus error code / link to Docs where you can elaborate on this. I think the error will appear _a lot_ during most developer workflows, so the error should not be overly verbose and possibly with a "magic" env var to suppress spam. 

```
Warning: unable to pin image to digest because it wasn't found in the registry. See https://docs.docker.com/nishants_detailled_explanation_here
```

**Comment by mostolog** [comment] 2017-02-13 08:03
According to https://github.com/docker/docker/pull/28173
> NOTE: It is by choice that the operation won't fail if the digest retrieval fails for some reason. It will only print a warning and move on. This is to make sure that the use case where a locally built image might be used to create a service still works.

So, when using a local image, it could omit this message, isnt it?

**Comment by nishanttotla** [comment] 2017-02-13 08:17
@alexellis @mostolog thanks for your suggestions. This is a little tricky and I see all your points. I'm currently working on a PR to make an attempt to make this warning system better, stay tuned.

**Comment by mostolog** [comment] 2017-02-13 08:19
Glad to hear

**Comment by sandys** [comment] 2017-02-18 16:07
@mostolog @nishanttotla im having this exact same issue with local images.

**Comment by laxmanlax** [comment] 2017-02-18 16:57
I am also getting the same issue 

```docker@mgmt1:~$ docker service create --network prom --name prom --publish 9090:9090 my-prometheus
unable to pin image my-prometheus to digest: errors:
denied: requested access to the resource is denied
unauthorized: authentication required```

**Comment by alexellis** [comment] 2017-03-06 20:48
If anyone else lands here and if not sure what this means, I'll try to paraphrase:

This is just a warning and not an error which translated means "we could not find your image on the internet (Hub) or another registry, so we'll use your local image instead".

* You won't be able to scale your image over multiple hosts unless they have the exact matching image

**Comment by nishanttotla** [comment] 2017-03-13 22:18
#31713 fixes the warnings received, by making them more concise and explanatory.

**Comment by thaJeztah** [comment] 2017-03-22 21:40
let's close this issue now that that PR is merged :+1: 

please open a new issue if you have something related that's not covered by that PR

**Closed by thaJeztah** 2017-03-22 21:40 UTC
Labels: area/swarm, kind/enhancement, version/1.13

**Comment by bitsmaestro** [comment] 2018-09-25 08:33
I also got same issue on RHEL, workaround may help others also
```
$ docker service create --name testweb -p 80:80 --replicas 3 httpd
unable to pin image httpd to digest: unknown: Not Found
```

was able to **workaround** this by giving complete image path
```
$ docker service create --name testweb -p 8080:80 --replicas 3 docker.io/httpd
hy1ove6b16e07cdw0e6h4rb0m
```
reason looks like this, multiple registries 
```
$ docker info | grep Registries
Insecure Registries:
Registries: registry.access.redhat.com (secure), docker.io (secure)
```

here is the docker version
```
$ docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-63.git94f4240.el7.x86_64
 Go version:      go1.9.2
 Git commit:      94f4240/1.13.1
 Built:           Mon Apr 30 15:45:42 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-63.git94f4240.el7.x86_64
 Go version:      go1.9.2
 Git commit:      94f4240/1.13.1
 Built:           Mon Apr 30 15:45:42 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Comment by thaJeztah** [comment] 2018-09-25 14:18
@bitsmaestro the linked PR (https://github.com/moby/moby/pull/31713) is part of Docker 17.04, so won't be in Docker 1.13.1, which is an older version. Also note that you're running the Red Hat fork of Docker, which has a lot of modifications that are not in the official Docker packages, and is not maintained here.
