### ISSUE TITLE
ServeAPI error: is a directory

### ISSUE THREAD

**Issue by etcook** [docker/docker#15912] opened 2015-08-28 15:38 UTC
New docker nodes that I bring up are getting this error. Any suggestions or ideas?

I've tried it now on two completely fresh boxes. This is Docker 1.7.1

Note: because Linode uses custom kernels, I've always fallen back to devicemapper since aufs support isn't possible without a bootloader.

```
root@localhost:~# docker -d
WARN[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option
ERRO[0000] ServeAPI error: is a directory
INFO[0000] [graphdriver] using prior storage driver "devicemapper"
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1
WARN[0000] Your kernel does not support swap memory limit.
INFO[0000] Loading containers: start.
......ERRO[0000] Error unmounting device 90562e5df6b554a1bc41196f6c24f1d9bdd452818377913773b475d940839897: UnmountDevice: device not-mounted id 90562e5df6b554a1bc41196f6c24f1d9bdd452818377913773b475d940839897
ERRO[0000] error locating network id f4428f1834021aaba328334c1dd2d56279cf04f9c88215658111e15ce84d725a: network f4428f1834021aaba328334c1dd2d56279cf04f9c88215658111e15ce84d725a not found
ERRO[0000] Error unmounting device 90562e5df6b554a1bc41196f6c24f1d9bdd452818377913773b475d940839897: UnmountDevice: device not-mounted id 90562e5df6b554a1bc41196f6c24f1d9bdd452818377913773b475d940839897

INFO[0000] Loading containers: done.
INFO[0000] Daemon has completed initialization
INFO[0000] Docker daemon                                 commit=786b29d execdriver=native-0.2 graphdriver=devicemapper version=1.7.1
ERRO[0001] Error during graph storage driver.Cleanup(): device or resource busy
ERRO[0001] remove /var/run/docker.pid: no such file or directory
FATA[0001] Shutting down due to ServeAPI error: is a directory
```

**Comment by etcook** [comment] 2015-08-28 15:39
docker version:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64

docker info:
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

uname -a:
Linux localhost 4.1.5-x86_64-linode61 #7 SMP Mon Aug 24 13:46:31 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment] 2015-08-28 15:48
@etcook If I had to guess, I'd bet `/var/run/docker.sock` is a directory.

**Comment by etcook** [comment] 2015-08-28 15:57
@cpuguy83 You were 100%. I deleted the directory, did a `touch` on docker.sock, and now Docker loads up fine. Any idea why this is happening? This happened on two completely fresh servers. Thanks again!

**Comment by cpuguy83** [comment] 2015-08-28 15:58
What is setting up your servers?

**Comment by etcook** [comment] 2015-08-28 16:03
@cpuguy83 I used the Tutum installation scripts, which installs 1.7.1. Is this possibly a Tutum issue rather than Docker? Wouldn't the socket be created with the Docker install? Thanks!

**Comment by cpuguy83** [comment] 2015-08-28 16:05
Definitely not docker. cc @fermayo

**Comment by etcook** [comment] 2015-08-28 16:08
@fermayo @cpuguy83 - Looks like somehow the sock file that I created got deleted and a directory placed back in its place, so once again it is failing.

**Comment by etcook** [comment] 2015-08-28 16:08
understood, @cpuguy83 thanks for your help

**Comment by calavera** [comment] 2015-08-28 16:25
Closing this since it looks like it's not an issue. :tada:

**Comment by pchico83** [comment] 2015-09-02 11:46
@calavera @cpuguy83 @etcook 
I have spent some time on this issue and it looks like a RC in the docker daemon. The RC condition happens when there is a running container `A` mounting the host folder `/var/run/docker.sock` (for example `weaveworks/weave:1.0.1`). If the docker daemon is restarted, it happens that the container `A` is restarted before  `/var/run/docker.sock` is created by the docker daemon and then, `/var/run/docker.sock` is created as a folder (the default behavior for docker volumes).

Steps to reproduce
-------------------------
Install docker 1.7.1 in Ubuntu 14.04 with AUFS (t2.micro)
```
root@ip-172-31-3-84:/home/ubuntu# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

root@ip-172-31-3-84:/home/ubuntu# docker info
Containers: 25
Images: 9
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 59
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 992.5 MiB
Name: ip-172-31-3-84
ID: WGBZ:Y3ET:QM6F:7M2Y:CNYV:6FLQ:ZF56:RFRE:VKKS:W23K:22QD:TE7V
WARNING: No swap limit support
```

Create several containers mounting `/var/run/docker.sock`:
```
docker run --restart=always --privileged -v /var/run/docker.sock:/var/run/docker.sock -d alpine tail -f /dev/null
docker run --restart=always --privileged -v /var/run/docker.sock:/var/run/docker.sock -d alpine tail -f /dev/null
docker run --restart=always --privileged -v /var/run/docker.sock:/var/run/docker.sock -d alpine tail -f /dev/null
docker run --restart=always --privileged -v /var/run/docker.sock:/var/run/docker.sock -d alpine tail -f /dev/null
```

Modify `/etc/default/docker`:
```
DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --tlscert /path_to_cert.pem --tlskey /path_to_key.pem --tlscacert /path_to_ca.pem --tlsverify"
```

Execute this script:
```
#!/bin/bash

while true
do
   service docker restart
   if [[ -d "/var/run/docker.sock" ]]; then
      echo "RC creating /var/run/docker.sock"
      exit 1
   else
      docker ps
   fi  
done
```

And you will get the RC error is a few iterations.

Note that I am able to reproduce this error only if using TLS and using the exact `DOCKER_OPTS` parameter order shown above. For example, switching `-H tcp://0.0.0.0:2375` and  `-H unix:///var/run/docker.sock` I am not able to reproduce the error (probably because this way the docker daemon creates `/var/run/docker.dock` faster) which is the workaround we are using in Tutum for now.

Thanks!

**Comment by fermayo** [comment] 2015-09-02 11:52
@cpuguy83 definitely it's docker ;-)

**Comment by cpuguy83** [comment] 2015-09-02 12:57
Thanks! Re-opening

**Comment by mikebrow** [comment] 2015-09-02 19:41
#Investigating   
FYI... not reproducing on:
mike@ubuntuMikeBrown:~$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

mike@ubuntuMikeBrown:~$ docker info
Containers: 15
Images: 570
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 600
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 3.86 GiB
Name: ubuntuMikeBrown
ID: I5RH:OQVQ:Q2FC:GYRT:THGN:LM64:SCTA:QILK:5R54:UIWU:2CSC:XNUW

**Comment by mikebrow** [comment] 2015-09-08 16:48
I think you might have been attempting to use and restart docker before the container had finished restarting...  I was having problems running your script as the docker container had not finished restarting before the docker ps command was executed. So I used the script below and all seems fine now.  Was the docker ps successful on your run? Or did it report a failure?  Can you try this?  

#!/bin/bash

while true
do
   service docker restart
   
  
   if [[ -d "/var/run/docker.sock" ]]; then
      echo "RC creating /var/run/docker.sock"
      exit 1
   else
      while [ ! -e "/var/run/docker.sock" ] ; do
        inotifywait -t 2 -e create $(dirname "/var/run/docker.sock")
      done
      
      docker ps
   fi  
done

**Comment by pchico83** [comment] 2015-09-08 17:40
Yes, that script also fails for me. It is not related to the `docker ps` command, it also fails if using  `sleep 1` instead of `docker ps`. I can repro this consistently in fresh `t2.micro` machines. I am installing docker like this:

    https://gist.github.com/parente/025dcb2b9400a12d1a9f

**Comment by mikebrow** [comment] 2015-09-08 18:01
Thx.. I was trying to reproduce on docker not lxc-docker.

**Comment by pchico83** [comment] 2015-09-09 00:38
I have been able to repro this by installing:

```
   apt-get install docker-engine=1.7.1-0~trusty
```

but not in the latest 1.8.1 version.

**Comment by mikebrow** [comment] 2015-09-09 13:45
Thx.. for the update.

**Comment by tianon** [comment] 2015-10-02 21:02
I'm getting this again on a freshly compiled master with a `--restart=always` container that mounts the Docker socket.  I know we fixed this once by moving the initialization of container mounts to after the point where the daemon creates the socket, but I don't know whether the problem is exactly the same this time (although the symptoms are definitely 100% identical).

If I `sudo rm -rf /var/run/docker*` before restarting the daemon, the daemon itself recreates the socket location as a directory.

**Comment by LK4D4** [comment] 2015-10-02 21:08
Pretty sure it was latest @calavera refactoring. Shouldn't be hard to fix.

**Comment by LK4D4** [comment] 2015-10-04 23:41
Also now container can take daemon port too.

**Comment by LK4D4** [comment] 2015-10-05 05:26
@tianon ok, I fixed it and found that last time I wrote false-positive test. Will post PR tomorrow.

**Comment by tianon** [comment] 2015-10-05 06:15
You're a hero, @LK4D4! :heart:

**Closed** 2015-10-05 18:48 UTC

**Comment by setiseta** [comment] 2016-01-02 10:39
it seems this problem is still alive?
I'm getting this on Fedora 23 and docker version 1.9.1-fc23
If i have restart=always and mounted the docker.sock.
my workaround at the moment:
- Add this line to the systemd unit file docker.service:
- ```ExecStartPre=/usr/bin/touch /var/run/docker.sock```

Am I wrong in this thread?

**Comment by appelgriebsch** [comment] 2016-01-19 08:59
Have had the same issue on Fedora 23 today. It was working the other day but stopped after a restart was triggered. 

After removing the mentioned directory /var/run/docker.sock/ it was working again.

**Comment by setiseta** [comment] 2016-01-19 11:01
Yes but it stopps always after a restart is triggerd, or is this not the case on your system?

**Comment by runcom** [comment] 2016-01-19 11:13
@setiseta @appelgriebsch that's because the systemd unit file doesn't contain Requires=docker.s octet. Check https://bugzilla.redhat.com/show_bug.cgi?id=1289851 for a workaround also. Luckily this will be fixed in docker-1.10.

**Comment by sepiroth887** [comment] 2016-07-22 04:01
Just hit this issue on a few nodes with CoreOS 1068.8.0 Docker 1.10.3 :(

**Comment by phobologic** [comment] 2016-08-17 18:34
We are seeing this in docker 1.11.2 in Ubuntu 14.04 as well, this definitely isn't resolved.  Any chance we can get this bug re-opened or should a new issue be opened? @vdemeester

**Comment by keontang** [comment] 2016-10-27 09:25
I am also seeing this issue in docker 1.11.2:
```
root@v33:/etc/kubernetes# docker --version
Docker version 1.11.2, build b9f10c9
```

My docker logs:
```
time="2016-10-27T08:41:10.295693965Z" level=error msg="Force shutdown daemon"
^[[34mINFO^[[0m[8687] stopping containerd after receiving terminated
/var/run/docker.sock is up
time="2016-10-27T08:41:11.412032150Z" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
time="2016-10-27T08:41:11.412350909Z" level=fatal msg="can't create unix socket /var/run/docker.sock: is a directory"
/var/run/docker.sock is up
time="2016-10-27T08:41:11.474388358Z" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
time="2016-10-27T08:41:11.474725541Z" level=fatal msg="can't create unix socket /var/run/docker.sock: is a directory"
/var/run/docker.sock is up
time="2016-10-27T08:41:11.544669430Z" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
time="2016-10-27T08:41:11.545003676Z" level=fatal msg="can't create unix socket /var/run/docker.sock: is a directory"
/var/run/docker.sock is up
time="2016-10-27T08:41:11.622237395Z" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
time="2016-10-27T08:41:11.622626839Z" level=fatal msg="can't create unix socket /var/run/docker.sock: is a directory"
/var/run/docker.sock is up
time="2016-10-27T08:41:11.692162127Z" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
time="2016-10-27T08:41:11.692471660Z" level=fatal msg="can't create unix socket /var/run/docker.sock: is a directory"
/var/run/docker.sock is up
time="2016-10-27T08:41:11.762300718Z" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
time="2016-10-27T08:41:11.762604081Z" level=fatal msg="can't create unix socket /var/run/docker.sock: is a directory"
```

**Comment by keontang** [comment] 2016-10-27 10:26
I found after stopped docker service, docker.sock may be changed to directory:
```
root@v34:/etc/kubernetes# ls -al /var/run/docker.sock
srw-rw---- 1 root docker 0 Oct 27 10:17 /var/run/docker.sock
root@v34:/etc/kubernetes# service docker stop
docker stop/waiting
root@v34:/etc/kubernetes# ls -al /var/run/docker.sock
total 0
drwxr-xr-x  2 root root  40 Oct 27 10:18 .
drwxr-xr-x 28 root root 940 Oct 27 10:18
```

**Comment by keontang** [comment] 2016-10-27 10:40
Now, I solved this problem temporily just by add `rm -rf /var/run/docker.sock` in pre-start script of docker.conf:
```
pre-start script
	# see also https://github.com/tianon/cgroupfs-mount/blob/master/cgroupfs-mount
	if grep -v '^#' /etc/fstab | grep -q cgroup \
		|| [ ! -e /proc/cgroups ] \
		|| [ ! -d /sys/fs/cgroup ]; then
		exit 0
	fi
	if ! mountpoint -q /sys/fs/cgroup; then
		mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
	fi
	(
		cd /sys/fs/cgroup
		for sys in $(awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
			mkdir -p $sys
			if ! mountpoint -q $sys; then
				if ! mount -n -t cgroup -o $sys cgroup $sys; then
					rmdir $sys || true
				fi
			fi
		done
	)
	rm -rf /var/run/docker.sock
end script
```
