### ISSUE TITLE
Error response from daemon: container already connected to network NET_NAME

### ISSUE THREAD

**Issue by zhaoxpZTE** [docker/docker#18257] opened 2015-11-26 09:24 UTC
Description of problem:
I create an overlay network "net1" for host VM1 and VM2, run container "con1" on VM1 and connect it to network "net1", then run the same name "con1" container on VM2. When I want to connect the "con1" to "net1" on VM2, it shows "Error response from daemon: container already connected to network net1".

docker version
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```
docker info
```
Containers: 8
Images: 30
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 53
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 3.86 GiB
Name: user11
ID: I5MJ:ANLS:EUGF:H7FV:4E3K:3KOJ:L4CD:P6LF:V3HD:AWXT:YL5E:23TJ
WARNING: No swap limit support
Cluster store: etcd://192.168.122.10:4001
Cluster advertise: 192.168.122.11:2376
```
uname -a
```
Linux user11 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

`docker network inspect net1` after `docker network connect net1 con1` on VM1:
```
[
    {
        "Name": "net1",
        "Id": "359d25c7e342e367b5e0971078ced2ceb4b3a5a1d9cba903ff98adcf084fc728",
        "Scope": "global",
        "Driver": "overlay",
        "IPAM": {
            "Driver": "default",
            "Config": [
                {
                    "Subnet": "10.10.11.0/24",
                    "Gateway": "10.10.11.100"
                }
            ]
        },
        "Containers": {
            "6fe1a9f6ad994b220975f975a7ee4e6f5cee76785eaee57d4c58a90333660536": {
                "EndpointID": "0769068522cc70c35008a656699500ad71c7adce9e3ba4fc760638e5474ae636",
                "MacAddress": "02:42:0a:0a:0b:01",
                "IPv4Address": "10.10.11.1/24",
                "IPv6Address": ""
            }
        },
        "Options": {}
    }
]
```
Expected:
When `docker network connect net1 con1` , the con1 on VM2 can connect to net1.

Actual Results:
`docker network connect net1 con1` on VM2:
```
Error response from daemon: container already connected to network net1
```

`docker network connect net1 0d294016a6ef` even if I use the container's ID:
```
Error response from daemon: container already connected to network net1
```

`docker network inspect net1` on VM2
```
[
    {
        "Name": "net1",
        "Id": "359d25c7e342e367b5e0971078ced2ceb4b3a5a1d9cba903ff98adcf084fc728",
        "Scope": "global",
        "Driver": "overlay",
        "IPAM": {
            "Driver": "default",
            "Config": [
                {
                    "Subnet": "10.10.11.0/24",
                    "Gateway": "10.10.11.100"
                }
            ]
        },
        "Containers": {},
        "Options": {}
    }
]
```

I think that this problem is related to https://github.com/docker/docker/blob/v1.9.1/daemon/container_unix.go:
```
func (container *Container) getEndpointInNetwork(n libnetwork.Network) (libnetwork.Endpoint, error) {
	endpointName := strings.TrimPrefix(container.Name, "/")
	return n.EndpointByName(endpointName)
}
```
We' better use `container.ID` rather than `container.Name`?

**Comment by WeiZhang555** [comment] 2015-11-26 13:47
This is designed behavior not a bug, you can't join containers with same name into one overlay network.
If it allows so, how can containers belonging to same overlay network visit each other with service name?

**Comment by thaJeztah** [comment] 2015-11-26 16:53
Perhaps we should improve the error-message, e.g. "a container with this name is already connected to this network"?

**Comment by zhaoxpZTE** [comment] 2015-11-27 04:02
Thanks @WeiZhang555 and @thaJeztah for your reply.
Maybe users want more prompt from the error-message, e.g. "container CONTAINER_NAME already connected to network NETWORK_NAME, please check other hosts whether they have a container with this name being already connected to this network." 
Would it be better if `docker network inspect NETWORK_NAME` shows all containers belonged to the overlay network, even if the containers are not created on this host? If so, the command may need to give more information of containers, such as name and host.

**Comment by zhaoxpZTE** [comment] 2015-11-27 04:23
@WeiZhang555 I saw your #17615 that made docker network inspect print container names. Please check if the suggestion in my last reply is practicable. Thanks!

**Comment by WeiZhang555** [comment] 2015-11-27 06:50
@zhaoxpZTE 
>Maybe users want more prompt from the error-message, e.g. "container CONTAINER_NAME already connected to network NETWORK_NAME, please check other hosts whether they have a container with this name being already connected to this network." 

More meaningful prompt looks reasonable, but you hint seems too long, maybe we need to find a better prompt sentence...

> Would it be better if docker network inspect NETWORK_NAME shows all containers belonged to the overlay network, even if the containers are not created on this host? If so, the command may need to give more information of containers, such as name and host.

I might be wrong, but I don't think this is workable, container is a running instance only meaningful in its host, maybe we can mark it as "remote container" in docker network inspect result, but I doubt that docker network team will accept this.

**Comment by thaJeztah** [comment] 2015-11-27 07:37
> Would it be better if docker network inspect NETWORK_NAME shows all containers belonged to the overlay network, even if the containers are not created on this host? If so, the command may need to give more information of containers, such as name and host.

That was discussed, and should be something to implement in Swarm, not engine see: https://github.com/docker/docker/issues/18163#issuecomment-158941813 and the related issue https://github.com/docker/swarm/issues/1373

**Comment by zhaoxpZTE** [comment] 2015-11-27 07:42
Thanks @WeiZhang555 @thaJeztah 
If users, such as me, are new to docker, the result of `docker network connect` or `docker network inspect` with more information will help them to know what exactly happens.

**Comment by thaJeztah** [comment] 2015-11-27 07:48
@zhaoxpZTE I understand, but in a multi-host setup, you'd already be using docker swarm, and doing `docker network inspect` would use the Swarm API, so containers from all nodes would be visible (once it's implemented in Swarm)

**Comment by zhaoxpZTE** [comment] 2015-12-01 09:18
@WeiZhang555 @thaJeztah 
There is another question, would you please help me to check it ? In my env, I create an overlay network and connect containers to it. I can ping outer IP from containers successfully. But it fails when I ping the container's IP which the overlay network assigned to them. Do I need to make more settings for the connectivity, or is that a bug or also a designed behavior? Thanks!

**Comment by thaJeztah** [comment] 2015-12-01 14:35
@zhaoxpZTE could you open a separate issue for that, and add a simple example to show what you're trying to do and what you expected to happen? Let's try not to mix different issues, otherwise this will be confusing :smile:

**Comment by thaJeztah** [comment] 2015-12-01 14:36
@WeiZhang555 are you interested in creating a PR to improve the error message?

**Comment by WeiZhang555** [comment] 2015-12-01 14:48
@thaJeztah Sure, I'm always happy to help :smile:  I'll take care of this.

@zhaoxpZTE as @thaJeztah said, you can add one more example to illustrate what you're expecting, that will help a lot for improving :laughing:

**Comment by thaJeztah** [comment] 2015-12-01 14:51
Thanks!

**Comment by zhaoxpZTE** [comment] 2015-12-02 03:02
I'm a newbie to github and docker, thanks for your guidance. @thaJeztah @WeiZhang555 
I have already opened a new issue of my last question. #18357

**Comment by aboch** [comment] 2015-12-03 18:40
@zhaoxpZTE 
It looks like @WeiZhang555 and @thaJeztah (thanks guys) addressed all your questions and pointed to new (or existing) more specific PR for the issues you reported.

If I have not missed anything, please let me know, do you think it is appropriate to close this issue now ?

**Comment by zhaoxpZTE** [comment] 2015-12-04 01:27
@aboch Yes, please! Thanks!

**Comment by thaJeztah** [comment] 2015-12-04 10:58
Thanks for reporting @zhaoxpZTE!

**Closed by thaJeztah** 2015-12-04 10:58 UTC
Labels: group/networking, kind/enhancement
