### ISSUE TITLE
No network access from container with 1.7 and Linux 4.0.5

### ISSUE THREAD

**Issue by dpgeekzero** [docker/docker#14185] opened 2015-06-25 13:54 UTC
Since I upgraded to 1.7.0, none of my containers can access the network.  I haven't modified any of my Docker configuration files, so I'm not sure what else to do.

I have rebooted the box to ensure that it wasn't iptables related.

I'll attach the requested Docker info in a second comment.

```
-> ping -c2 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=54 time=24.0 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=54 time=23.9 ms

--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 23.938/23.971/24.004/0.033 ms

-> docker run -it debian /bin/bash
root@37992e4fc610:/# ping -c2 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss

-> ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
11: eth0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:c0:a8:32:05 brd ff:ff:ff:ff:ff:ff
    inet 192.168.50.5/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c0ff:fea8:3205/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by dpgeekzero** [comment] 2015-06-25 13:54
```
-> docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

-> docker info
Containers: 22
Images: 879
Storage Driver: devicemapper
 Pool Name: docker-8:2-24909302-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 25.21 GB
 Data Space Total: 107.4 GB
 Data Space Available: 82.17 GB
 Metadata Space Used: 46.12 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.101 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.97 (2015-05-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-1-ARCH
Operating System: Arch Linux
CPUs: 8
Total Memory: 15.58 GiB
Name: dougdev
ID: TOIW:WU7N:I7X2:5S5R:Y6UF:QEUV:LQLL:HIZN:W5CR:NN6K:7644:7AXP

-> uname -a
Linux dougdev 4.0.5-1-ARCH #1 SMP PREEMPT Sat Jun 6 18:37:49 CEST 2015 x86_64 GNU/Linux

```

**Comment by mrjana** [comment] 2015-06-25 14:22
@dpgeekzero Can you dump iptables rules(both filter rules and nat rules) after the container is started and post it here? Also `lsmod` output would be helpful

**Comment by dpgeekzero** [comment] 2015-06-25 14:36
iptables output
```
-> sudo iptables -L -t nat                                                          master!
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  192.168.50.0/24      anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination 
```

lsmod output
```
-> lsmod
Module                  Size  Used by
veth                   16384  0 
xt_conntrack           16384  1 
ipt_MASQUERADE         16384  1 
nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
iptable_nat            16384  1 
nf_conntrack_ipv4      20480  2 
nf_defrag_ipv4         16384  1 nf_conntrack_ipv4
nf_nat_ipv4            16384  1 iptable_nat
xt_addrtype            16384  2 
iptable_filter         16384  1 
br_netfilter           20480  0 
nf_nat                 24576  2 nf_nat_ipv4,nf_nat_masquerade_ipv4
nf_conntrack           90112  5 nf_nat,nf_nat_ipv4,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_ipv4
bridge                106496  1 br_netfilter
stp                    16384  1 bridge
llc                    16384  2 stp,bridge
dm_thin_pool           61440  1 
dm_persistent_data     57344  1 dm_thin_pool
dm_bio_prison          16384  1 dm_thin_pool
dm_bufio               24576  1 dm_persistent_data
libcrc32c              16384  1 dm_persistent_data
loop                   28672  4 
dm_mod                 98304  5 dm_persistent_data,dm_bufio,dm_thin_pool
fuse                   90112  3 
rfcomm                 65536  14 
ecb                    16384  1 
ctr                    16384  2 
ccm                    20480  2 
bnep                   20480  2 
joydev                 20480  0 
mousedev               20480  0 
hid_logitech_hidpp     20480  0 
nls_iso8859_1          16384  1 
nls_cp437              20480  1 
vfat                   24576  1 
fat                    65536  1 vfat
hid_multitouch         20480  0 
hid_generic            16384  0 
hid_logitech_dj        20480  0 
cdc_mbim               16384  0 
cdc_wdm                20480  1 cdc_mbim
cdc_ncm                28672  1 cdc_mbim
usbhid                 49152  0 
uvcvideo               86016  0 
usbnet                 36864  2 cdc_mbim,cdc_ncm
videobuf2_vmalloc      16384  1 uvcvideo
videobuf2_memops       16384  1 videobuf2_vmalloc
mii                    16384  1 usbnet
videobuf2_core         40960  1 uvcvideo
v4l2_common            16384  1 videobuf2_core
videodev              135168  3 uvcvideo,v4l2_common,videobuf2_core
hid                   110592  7 hid_multitouch,hid_generic,usbhid,hid_logitech_dj,hid_logitech_hidpp
snd_usb_audio         151552  2 
snd_usbmidi_lib        28672  1 snd_usb_audio
snd_rawmidi            28672  1 snd_usbmidi_lib
media                  20480  2 uvcvideo,videodev
snd_seq_device         16384  1 snd_rawmidi
intel_rapl             20480  0 
iosf_mbi               16384  1 intel_rapl
btusb                  40960  0 
x86_pkg_temp_thermal    16384  0 
bluetooth             442368  32 bnep,btusb,rfcomm
intel_powerclamp       20480  0 
coretemp               16384  0 
kvm_intel             155648  0 
arc4                   16384  2 
kvm                   446464  1 kvm_intel
snd_hda_codec_realtek    65536  1 
snd_hda_codec_hdmi     53248  1 
snd_hda_codec_generic    65536  1 snd_hda_codec_realtek
snd_hda_intel          28672  6 
snd_hda_controller     28672  1 snd_hda_intel
crct10dif_pclmul       16384  0 
iwlmvm                229376  0 
mac80211              655360  1 iwlmvm
psmouse               110592  0 
dell_laptop            16384  0 
led_class              16384  2 iwlmvm,dell_laptop
crc32_pclmul           16384  0 
crc32c_intel           24576  1 
serio_raw              16384  0 
snd_hda_codec         114688  5 snd_hda_codec_realtek,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_hda_intel,snd_hda_controller
snd_hwdep              16384  2 snd_usb_audio,snd_hda_codec
snd_pcm                90112  6 snd_usb_audio,snd_hda_codec_hdmi,snd_hda_codec,snd_hda_intel,snd_hda_controller
ghash_clmulni_intel    16384  0 
iwlwifi               172032  1 iwlmvm
dcdbas                 16384  1 dell_laptop
atkbd                  24576  0 
aesni_intel           172032  5 
cfg80211              483328  3 iwlwifi,mac80211,iwlmvm
pn544_mei              16384  0 
mei_phy                16384  1 pn544_mei
pn544                  20480  1 pn544_mei
hci                    24576  2 pn544,mei_phy
nfc                    90112  2 hci,pn544
aes_x86_64             20480  1 aesni_intel
libps2                 16384  2 atkbd,psmouse
lrw                    16384  1 aesni_intel
snd_timer              28672  1 snd_pcm
iTCO_wdt               16384  0 
dell_wmi               16384  0 
i8k                    16384  0 
gf128mul               16384  1 lrw
rfkill                 24576  8 nfc,cfg80211,bluetooth,dell_laptop
sparse_keymap          16384  1 dell_wmi
nouveau              1314816  1 
ttm                    81920  1 nouveau
iTCO_vendor_support    16384  1 iTCO_wdt
rtsx_pci_ms            20480  0 
evdev                  24576  19 
i915                 1024000  13 
snd                    69632  27 snd_hda_codec_realtek,snd_usb_audio,snd_hwdep,snd_timer,snd_hda_codec_hdmi,snd_pcm,snd_rawmidi,snd_hda_codec_generic,snd_usbmidi_lib,snd_hda_codec,snd_hda_intel,snd_seq_device
memstick               16384  1 rtsx_pci_ms
mxm_wmi                16384  1 nouveau
mac_hid                16384  0 
i8042                  20480  2 libps2,dell_laptop
glue_helper            16384  1 aesni_intel
drm_kms_helper        102400  2 i915,nouveau
ablk_helper            16384  1 aesni_intel
cryptd                 20480  3 ghash_clmulni_intel,aesni_intel,ablk_helper
thermal                20480  0 
serio                  20480  6 serio_raw,atkbd,i8042,psmouse
drm                   282624  17 ttm,i915,drm_kms_helper,nouveau
soundcore              16384  2 snd,snd_hda_codec
fan                    16384  0 
int3403_thermal        16384  0 
battery                20480  0 
intel_gtt              20480  1 i915
i2c_algo_bit           16384  2 i915,nouveau
ie31200_edac           16384  0 
edac_core              49152  1 ie31200_edac
shpchp                 36864  0 
mei_me                 20480  0 
mei                    77824  3 pn544_mei,mei_phy,mei_me
i2c_i801               20480  0 
i2c_core               53248  8 drm,i915,i2c_i801,drm_kms_helper,i2c_algo_bit,v4l2_common,nouveau,videodev
ac                     16384  0 
video                  24576  2 i915,nouveau
lpc_ich                24576  0 
button                 16384  2 i915,nouveau
processor_thermal_device    16384  0 
int3402_thermal        16384  0 
int3400_thermal        16384  0 
acpi_thermal_rel       16384  1 int3400_thermal
int340x_thermal_zone    16384  3 int3402_thermal,processor_thermal_device,int3403_thermal
dell_smo8800           16384  0 
wmi                    20480  3 dell_wmi,mxm_wmi,nouveau
processor              28672  0 
vboxnetflt             28672  0 
vboxnetadp             28672  0 
vboxdrv               356352  4 vboxnetadp,vboxnetflt
ip_tables              28672  2 iptable_filter,iptable_nat
x_tables               28672  5 ip_tables,ipt_MASQUERADE,xt_conntrack,iptable_filter,xt_addrtype
ext4                  512000  1 
crc16                  16384  2 ext4,bluetooth
mbcache                20480  1 ext4
jbd2                   90112  1 ext4
sd_mod                 36864  4 
rtsx_pci_sdmmc         24576  0 
mmc_core              110592  1 rtsx_pci_sdmmc
ahci                   36864  3 
libahci                28672  1 ahci
libata                184320  2 ahci,libahci
xhci_pci               16384  0 
xhci_hcd              155648  1 xhci_pci
ehci_pci               16384  0 
ehci_hcd               73728  1 ehci_pci
scsi_mod              147456  2 libata,sd_mod
rtsx_pci               45056  2 rtsx_pci_ms,rtsx_pci_sdmmc
usbcore               200704  13 btusb,snd_usb_audio,uvcvideo,snd_usbmidi_lib,ehci_hcd,ehci_pci,usbhid,usbnet,cdc_mbim,cdc_ncm,cdc_wdm,xhci_hcd,xhci_pci
usb_common             16384  1 usbcore
```

**Comment by dpgeekzero** [comment] 2015-06-26 16:00
@mrjana FYI: I downgraded to Docker version 1.6.2, build 7c8fca2 this morning so I can get some work done.  All works fine after a reboot.

**Comment by eb-dteixeira** [comment] 2015-06-26 18:13
:+1: 

@dpgeekzero Having exactly the same problem. Reverted to both 1.6.2 (1.5 on my older machines) and everything started working.

Host can access every container and their services but I'm not able to ping any linked containers from another.

**Comment by LK4D4** [comment] 2015-07-01 17:36
probably duplicate of #14073 
WDYT @mrjana ?

**Comment by mrjana** [comment] 2015-07-01 18:22
@LK4D4 not sure at the moment. I did try Arch Linux with 4.0.5 kernel and did a simple test and everything seems to work fine. So it doesn't look like as simple as Arch Linux on 4.0.5 is fundamentally broken. Could be something to do with the user's other configurations. Will keep investigating

**Comment by dpgeekzero** [comment] 2015-07-18 14:31
FYI: @mrjana Exact same behavior with Docker 1.7.1 on Linux 4.1.2-2-ARCH

Any further suggestions?

**Comment by cles** [comment] 2015-07-22 18:33
just dropping by because I had this exact same problem and just figured it out, maybe it's the same situation and I can help:

systemd-network has started setting forwarding to off for specific interfaces configured on it since 219/220, so setting sysctl net.ipv4.conf.all.forwarding=1 is not enough anymore, it will not work.

check sysctl net.ipv4.conf.<physical interface>.forwarding, mine was set to 0

if you want systemd-network to keeps its paws off it, add IPForward=kernel on the interface.network definition file at /etc/systemd/network/

If it wasn't that... oh well, I guess it was just me, sorry!

**Comment by dpgeekzero** [comment] 2015-07-25 02:57
@cles That seems to have fixed it!

Not sure why it matters what version of Docker I have installed, but when I set that value in my network definition file, docker 1.7 works!!

So, this appears to be a combination of Docker + systemd-networkd.

**Closed** 2015-07-25 02:57 UTC
Labels: system/networking

**Comment by thaJeztah** [comment] 2015-07-25 19:49
@dpgeekzero @cles I'm not very familiar with Systemd, but is this something that you think should be documented? Is this something that people might/will run into after a clean install of Docker?

**Comment by cles** [comment] 2015-07-25 20:17
I'd say so, yes, since this behavior it's the new default for systemd-network apparently. Whoever uses it and is on the bleeding edge (which is quite a good description for arch incidentally...) is going to get bit I think.

A note at https://docs.docker.com/installation/archlinux/ would've helped me quite, it was the first place I went to I'd say (outside of arch docs, that is)

I feel in an ideal world, docker would've set the flag for the specific ethernet interface... but as to how it finds out which interface that is, I've no clue, so perhaps competely unfeasible.

**Comment by thaJeztah** [comment] 2015-07-25 20:33
@cles would you be interested in contributing, and creating a pull request? The documentation is part of this repository (the page you referred to is here; https://github.com/docker/docker/blob/master/docs/installation/archlinux.md). That would be really great (and I'm afraid I'll mess up trying to describe what the steps are :wink:)

**Comment by cles** [comment] 2015-07-25 21:07
@thaJeztah oh didn't realize the docs were right here! Sure, I'll give it a shot tomorrow :smile:

**Comment by thaJeztah** [comment] 2015-07-25 21:11
@cles awesome, thanks in advance!

**Comment by hookenz** [comment] 2015-09-09 21:59
I'm getting this on the latest stable CoreOS 766.3.0.  But in my case, all the interfaces are set to forward.  I checked them. 

And the networking is now otherwise working.

**Comment by rajatprogrammer** [comment] 2018-08-29 06:00
my docker container is not able to access internet with docker version 1.7 on redhat 6 and I try all IP forward rules and check all think it work fine the error is on aws redhat image.
[devops_admin@UAT-Matrix-DevOps-AP-1a ui]$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:79:f8:ad:dc:b2 brd ff:ff:ff:ff:ff:ff
    inet 10.100.242.231/24 brd 10.100.242.255 scope global eth0
    inet6 fe80::79:f8ff:fead:dcb2/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/ether 72:97:55:49:c6:ff brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
    inet6 fe80::7097:55ff:fe49:c6ff/64 scope link
       valid_lft forever preferred_lft forever
my docker0  setting is not up and i try to set all the thinks the ip forwarding rule is set to 1 but unable to get internet on my container not abel to ping 

this is iptable rule for docker
sudo iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination

I am try on redhat 6  and docker version 1.7

**Comment by rajatprogrammer** [comment] 2018-08-29 06:02
my iptabels for nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  anywhere             anywhere            ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  ip-172-17-0-0.ap-south-1.compute.internal/16  anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  anywhere            !loopback/8          ADDRTYPE match dst-type LOCAL

Chain DOCKER (2 references)
target     prot opt source               destination
