### ISSUE TITLE
using lxc-conf options when running the native exe-driver doesn't error

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#10376] opened 2015-01-27 06:09 UTC
This means the user doesn't get told that their commands are being quietly ignored.

see https://forums.docker.com/t/interface-doesnt-come-up-in-docker-run/619

```
[sven@t440s ~]$ docker run --net=none --lxc-conf="lxc.network.type=veth" --lxc-conf="lxc.network.ipv4=10.0.0.100/24" --lxc-conf="lxc.network.ipv4.gateway=10.0.0.1" --lxc-conf="lxc.network.link=br0" --lxc-conf="lxc.network.name=eth0" --lxc-conf="lxc.network.flags=up" -i -t --rm busybox sh
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
Segmentation fault (core dumped)
/ # 
/ # 
/ # [sven@t440s ~]$ docker info
Containers: 4
Images: 1371
Storage Driver: devicemapper
 Pool Name: docker-8:1-6293870-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 56.08 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 74.14 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.17.7-200.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)
CPUs: 4
Total Memory: 11.43 GiB
Name: t440s
ID: D6XY:G3H3:VXPP:WB3J:UPVH:TYD6:BDBK:DSNB:IA4B:7RUB:MB3L:EUDC
Username: svendowideit
Registry: [https://index.docker.io/v1/]
[sven@t440s ~]$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): 7e803ba
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): 7e803ba
```

**Comment by jfrazelle** [comment] 2015-02-26 01:18
we should throw an error if the user is using the native driver and trying to user --lxc-conf, this should be an easy fix for any newcomer who whats to contribute

**Comment by superseb** [comment] 2015-04-17 11:19
@jfrazelle This can be closed by #11401 ? Duplicate of #11385

**Comment by jfrazelle** [comment] 2015-04-17 11:20
Yep yep looks like it to me

**Comment by thaJeztah** [comment] 2015-04-17 11:27
Well spotted, @superseb!

I'm going to close this, because this is a duplicate of https://github.com/docker/docker/issues/11385 and should be resolved by https://github.com/docker/docker/pull/11401

**Closed by thaJeztah** 2015-04-17 11:27 UTC
Labels: /system/lxc, exp/beginner, kind/enhancement
