### ISSUE TITLE
Mechanism to protect (data-only) containers against removal

### ISSUE THREAD

**Issue by mpeterson** [docker/docker#5742] opened 2014-05-12 18:01 UTC
As a docker administrator I'd like to have a way to protect (data-only) containers against accidental removal since deleting one container could lead to serious data loss (all the information the container has since the last backup), as this would make containers usage more secure for a production server.

**Comment by jfrazelle** [comment] 2015-02-26 00:43
also see https://github.com/docker/docker/issues/9878

**Comment by coolljt0725** [comment] 2015-02-26 01:03
+1

**Comment by jfrazelle** [comment] 2015-02-26 23:50
this is a duplicate of https://github.com/docker/docker/issues/9878

**Closed by jfrazelle** 2015-02-26 23:50 UTC
Labels: feature
