### ISSUE TITLE
Start container feature: Ignore CMD directives

### ISSUE THREAD

**Issue by dev-guy** [docker/docker#13114] opened 2015-05-10 14:59 UTC
I'm using an image that runs a script upon container start-up via a CMD directive in the Dockerfile. This script runs a web application. I recently broke the config files accidentally and the web application failed to start. The result was a container that I had to throw away. Could you imagine if it contained something that I couldn't replace? I'd be a very unhappy whale. Is there a way to get the container's OS to start and ignore the CMD scripts so I can fix the problem via exec -it bash? I searched for such a feature at the docker command-line but obviously wasn't successful.

**Comment by thaJeztah** [comment] 2015-05-10 15:09
You could `docker commit` the existing container as an image and start a new container from that, overriding the cmd to use from the command line (`docker run -it my-committed-container bash`

**Comment by runcom** [comment] 2015-05-10 15:19
@dev-guy can't you just `docker run --entrypoint /bin/sh yourwebappcontainer` to start your image and play with it with a shell?

**Comment by dev-guy** [comment] 2015-05-10 15:26
@thaJeztah Yes, thank you for the workaround. I hope the Docker team adds this as a real 'start' option, however. @runcom - Docker run creates a new container, right? My existing container is special (different from image) so I need to get that started.

**Comment by thaJeztah** [comment] 2015-05-10 15:29
> My existing container is special (different from image) so I need to get that started.

In that case, committing is the sane way to do. I don't think re-starting an existing container with a new command is something we want (containers should be reproducible, so in general there's no need to)

I'm going to close this issue, because the question was answered, but feel free to continue the discussion.

**Closed by thaJeztah** 2015-05-10 15:29 UTC

**Comment by dev-guy** [comment] 2015-05-10 15:42
I don't think regular humans could figure that out. Perhaps this issue will become the documentation that Docker users find when they do facepalm stuff to their start scripts.
