### ISSUE TITLE
Docker 1.8.x push to private v2 registry fails with Method Not Allowed, works fine with <1.8

### ISSUE THREAD

**Issue by jnsaff** [docker/docker#15636] opened 2015-08-17 15:54 UTC
Below happens with 1.8 and 1.8.1. Versions 1.7.1 and below have no problems.

This happens with all images we have tested.

When trying to push to private v2 registry we get: 

~ $ docker push pri.va.te/zookeeper-exhibitor-test:3.4.6_1.5.4_check_3000
The push refers to a repository [pri.va.te/zookeeper-exhibitor-test] (len: 1)
3e684eeb219c: Pushing [==================================================>]     32 B/32 B
Error parsing HTTP response: invalid character 'M' looking for beginning of value: "Method not allowed\n"
~ $

Server side logs say: 

time="2015-08-17T15:17:03.812891449Z" level=debug msg="authorizing request" environment=development http.request.host=pri.va.te http.request.id=597dd7af-f44e-4a67-aa88-9cd2ae8122ba http.request.method=PATCH http.request.remoteaddr=172.16.5.126 http.request.uri="/v2/zookeeper-exhibitor-test/blobs/uploads/0608d7aa-b09e-42a1-b4de-e5b4dca5002c?_state=vLJnc9BF9MnHvNsVwKtNqsOMd23PLKOMnjO9lAmBApd7Ik5hbWUiOiJ6b29rZWVwZXItZXhoaWJpdG9yLXRlc3QiLCJVVUlEIjoiMDYwOGQ3YWEtYjA5ZS00MmExLWI0ZGUtZTViNGRjYTUwMDJjIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTA4LTE3VDE1OjE3OjAzLjc3NDE2MzM1NFoifQ%3D%3D" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/4.0.9-boot2docker os/linux arch/amd64" instance.id=f98ff6a2-c368-49b3-a7e9-25ed51901ffc service=registry vars.name=zookeeper-exhibitor-test vars.uuid=0608d7aa-b09e-42a1-b4de-e5b4dca5002c version=v2.0.0-79-g5e9bda2.m
time="2015-08-17T15:17:03.81307256Z" level=debug msg="(*layerStore).Resume" environment=development http.request.host=pri.va.te http.request.id=597dd7af-f44e-4a67-aa88-9cd2ae8122ba http.request.method=PATCH http.request.remoteaddr=172.16.5.126 http.request.uri="/v2/zookeeper-exhibitor-test/blobs/uploads/0608d7aa-b09e-42a1-b4de-e5b4dca5002c?_state=vLJnc9BF9MnHvNsVwKtNqsOMd23PLKOMnjO9lAmBApd7Ik5hbWUiOiJ6b29rZWVwZXItZXhoaWJpdG9yLXRlc3QiLCJVVUlEIjoiMDYwOGQ3YWEtYjA5ZS00MmExLWI0ZGUtZTViNGRjYTUwMDJjIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTA4LTE3VDE1OjE3OjAzLjc3NDE2MzM1NFoifQ%3D%3D" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/4.0.9-boot2docker os/linux arch/amd64" instance.id=f98ff6a2-c368-49b3-a7e9-25ed51901ffc service=registry vars.name=zookeeper-exhibitor-test vars.uuid=0608d7aa-b09e-42a1-b4de-e5b4dca5002c version=v2.0.0-79-g5e9bda2.m
time="2015-08-17T15:17:03.847676386Z" level=info msg="s3.GetContent(\"/docker/registry/v2/repositories/zookeeper-exhibitor-test/_uploads/0608d7aa-b09e-42a1-b4de-e5b4dca5002c/startedat\")" trace.duration=34.5249ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=39cf350a-33a8-43ec-898d-59878f645e9f trace.line=55
time="2015-08-17T15:17:03.872130209Z" level=info msg="s3.Stat(\"/docker/registry/v2/repositories/zookeeper-exhibitor-test/_uploads/0608d7aa-b09e-42a1-b4de-e5b4dca5002c/data\")" trace.duration=24.380155ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=4d995a71-4850-40c7-8f06-f90fd1409aee trace.line=111
time="2015-08-17T15:17:03.935810068Z" level=info msg="s3.PutContent(\"/docker/registry/v2/repositories/zookeeper-exhibitor-test/_uploads/0608d7aa-b09e-42a1-b4de-e5b4dca5002c/hashstates/sha256/0\")" trace.duration=61.216969ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent" trace.id=dbd170b0-05a5-4599-9222-42fc61c442c5 trace.line=67
time="2015-08-17T15:17:03.935881997Z" level=info msg="response completed" environment=development http.request.host=pri.va.te http.request.id=597dd7af-f44e-4a67-aa88-9cd2ae8122ba http.request.method=PATCH http.request.remoteaddr=172.16.5.126 http.request.uri="/v2/zookeeper-exhibitor-test/blobs/uploads/0608d7aa-b09e-42a1-b4de-e5b4dca5002c?_state=vLJnc9BF9MnHvNsVwKtNqsOMd23PLKOMnjO9lAmBApd7Ik5hbWUiOiJ6b29rZWVwZXItZXhoaWJpdG9yLXRlc3QiLCJVVUlEIjoiMDYwOGQ3YWEtYjA5ZS00MmExLWI0ZGUtZTViNGRjYTUwMDJjIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTA4LTE3VDE1OjE3OjAzLjc3NDE2MzM1NFoifQ%3D%3D" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/4.0.9-boot2docker os/linux arch/amd64" http.response.contenttype="text/plain; charset=utf-8" http.response.duration=124.109742ms http.response.status=405 http.response.written=19 instance.id=f98ff6a2-c368-49b3-a7e9-25ed51901ffc service=registry version=v2.0.0-79-g5e9bda2.m

Client Side:
uname -a 
Darwin imac.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

 docker  info
Containers: 1
Images: 51
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 53
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: fusion
ID: 
Debug mode (server): true
File Descriptors: 11
Goroutines: 18
System Time: 2015-08-17T15:42:47.680490872Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=vmwarefusion

docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

registry version=v2.0.0-79-g5e9bda2.m

**Comment by dmp42** [comment] 2015-08-17 16:16
@jnsaff 

Weird. Are you using S3?

Any chance you can test upgrading to registry 2.1.1?

**Comment by jnsaff** [comment] 2015-08-17 16:28
Yes we are using S3, also redis. I will see into whether we can spin up a test instance with 2.1.1 tomorrow.

**Comment by albertsj1** [comment] 2015-08-17 17:25
I'm seeing the same issue pushing from a docker 1.8.1 client to a docker 2.0.0 registry.  Unfortunately, I don't have an easy way to test pushing to a 2.1.1 registry.

**Comment by dmcgowan** [comment] 2015-08-17 18:07
Please upgrade to at least registry 2.0.1 and try again, 2.0.0 had a bug in the implementation of one of the defined registry endpoints which is used by 1.8.

**Comment by dmp42** [comment] 2015-08-17 18:10
Thanks @dmcgowan

**Comment by lmesz** [comment] 2015-08-19 11:42
Hello,

We used docker 1.6.2 with docker-registry 2.0.0 it worked perfectly but we needed the new features and bugfixes that come with docker 1.8.x so we decided to upgrade to 1.8.1. Unfortunatelly we experienced the same that @jnsaff. Upgraded registry to 2.1.1 solved the issue for us. We can push to the registry.

**Comment by cpuguy83** [comment] 2015-08-19 13:17
Awesome, looks like we know the issue is specifically in talking to the 2.0.0 reg with docker 1.8.x.

@jnsaff Let us know if we can close this.

**Comment by ybogdanov** [comment] 2015-08-19 13:25
Same issue with docker 1.8.1 and registry 2.1.1. The problem is that docker sends PATCH request with over HTTP but not HTTPS while pushing image. Seems like a docker bug.

Our nginx proxy is tuned to redirect any HTTP requests to HTTPS. That's why docker receives an empty response. Allowing HTTP requests to our private registry is a temporary working solution.

```
$ docker push my_registry/imagename
The push refers to a repository [my_registry/imagename] (len: 1)
39c504f63f9d: Image successfully pushed
375e50261215: Pushing [==================================================>] 2.894 MB/2.894 MB
Put http://my_registry/v2/imagename/blobs/uploads/a96ed196-1d7a-4b33-8707-ab09544f39cc?_state=STATE&digest=DIGEST: EOF
```

Question: why is it using HTTP?

**Comment by dmp42** [comment] 2015-08-19 17:39
@ybogdanov top of the head: your proxy does not set X-Forwarded-Proto.

**Comment by dmp42** [comment] 2015-08-19 17:42
Everybody: it's strongly advised to not use registry 2.0.0 no matter what. You can absolutely upgrade to registry 2.0.1 with no change required on your side (or even better, to 2.1.1, but that may require reviewing your config).

**Comment by ybogdanov** [comment] 2015-08-19 18:00
@dmp42 yes, it helped, thanks!

**Comment by dmp42** [comment] 2015-08-19 18:55
@ybogdanov you are welcome

**Comment by dmp42** [comment] 2015-08-19 18:56
Since the issues listed in this thread are:

 * using registry 2.0.0, which contains a known bug fixed in >= 2.0.1
 * nginx config issues

I'm going to close this for bookkeeping.

If one of you is still experiencing issues with registry >= 2.0.1, please open a new ticket with details and ping me on it so we can help.

Thanks!

**Closed by dmp42** 2015-08-19 18:56 UTC
Labels: group/distribution

**Comment by asaf400** [comment] 2016-11-10 07:18
**Note for future reference:**
Docs have been moved to a general docs git: https://github.com/docker/docker.github.io/

**How to fix headers for apache httpd:** https://github.com/docker/docker.github.io/blob/master/registry/recipes/apache.md

**How to fix headers for nginx:** 
https://github.com/docker/docker.github.io/blob/master/registry/recipes/nginx.md

Short way for supporting Registry V2 with httpd proxy
(If you already know to setup a proper proxy for Registry V1 as I do)

`Header always set "Docker-Distribution-Api-Version" "registry/2.0"
Header onsuccess set "Docker-Distribution-Api-Version" "registry/2.0"
RequestHeader set X-Forwarded-Proto "https"`

**Comment by takuya-o** [comment] 2017-08-29 06:37
Thanks, @asaf400.
> RequestHeader set X-Forwarded-Proto "https"
Resolved my long time unresolved problem.
