### ISSUE TITLE
API error (500): Attempt to write a readonly database

### ISSUE THREAD

**Issue by ted-jung** [docker/docker#18816] opened 2015-12-21 05:07 UTC
We've got below error messages one of worker nodes.
the containers just got spawned. but, didn't come up properly with this messages.
    > kubelet.log
    E1221 11:51:25.464235   48701 manager.go:1864] Failed to create pod infra container: API error (500): Attempt to write a readonly database: attempt to write a readonly database
    E1221 11:51:25.470104   48701 pod_workers.go:112] Error syncing pod 80453525-a78d-11e5-a096-ac162d7b6ab8, skipping: API error (500): Attempt to write a readonly database: attempt to w                                       rite a readonly database
    W1221 11:51:53.948359   48701 container_gc.go:206] Failed to remove dead container "/k8s_cm.3a81a27b_cm-sstdt_farm-10_9523857f-a77a-11e5-a096-ac162d7b6ab8_ce07ebf1": API error (500):                                       rite a readonly database
    E1221 11:51:54.264240   48701 manager.go:1864] Failed to create pod infra container: API error (500): Attempt to write a readonly database: attempt to write a readonly database
    E1221 11:51:54.269985   48701 pod_workers.go:112] Error syncing pod 80453525-a78d-11e5-a096-ac162d7b6ab8, skipping: API error (500): Attempt to write a readonly database: attempt to w                                       rite a readonly database
    I1221 11:52:35.461238   48701 kubelet.go:2756] Query container info for pod "cm-dzydb_farm-10" failed with error (dial unix /var/run/docker.sock: no such file or directory)
tried to access

    > docker.log
    ERRO[595203] Handler for DELETE /containers/{name:.*} returned error: Cannot destroy container 8fcbb06587ff7b5e01255fb6c1b55e405f2c20abf0a5f6e58c28c2586574c4e5: Driver aufs failed to remove root filesystem 8fcbb06587ff7b5e01255fb6c1b55e405f2c20abf0a5f6e58c28c2586574c4e5: rename /data/docker/aufs/mnt/8fcbb06587ff7b5e01255fb6c1b55e405f2c20abf0a5f6e58c28c2586574c4e5 /data/docker/aufs/mnt/8fcbb06587ff7b5e01255fb6c1b55e405f2c20abf0a5f6e58c28c2586574c4e5-removing: read-only file system
    ERRO[595203] Handler for POST /containers/create returned error: Attempt to write a readonly database: attempt to write a readonly database
    ERRO[595203] Handler for POST /containers/create returned error: Attempt to write a readonly database: attempt to write a readonly database
    ERRO[595204] Handler for POST /containers/create returned error: Attempt to write a readonly database: attempt to write a readonly database

root@lxc5:/var/lib/docker# docker version
    Client:
     Version:      1.8.3
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   f4bf5c7
     Built:        Mon Oct 12 05:37:18 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.8.3
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   f4bf5c7
     Built:        Mon Oct 12 05:37:18 UTC 2015
     OS/Arch:      linux/amd64

root@lxc5:/var/lib/docker# docker info
     Containers: 27
     Images: 442
     Storage Driver: aufs
      Root Dir: /data/docker/aufs
      Backing Filesystem: extfs
      Dirs: 496
      Dirperm1 Supported: false
     Execution Driver: native-0.2
     Logging Driver: json-file
     Kernel Version: 3.13.0-24-generic
     Operating System: Ubuntu 14.04 LTS
     CPUs: 16
     Total Memory: 125.8 GiB
     Name: lxc5.p03.tst.use
     ID: XQPN:NIVY:VCEZ:3SNT:HESM:BRC3:6IAR:MPDS:EFIR:BRB3:6OE3:PME4
     WARNING: No swap limit support

 root@lxc5:/var/lib/docker# uname -a
    Linux lxc5.p03.tst.use 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environments : Physical

How reproducible:
    Steps to Reproduce:
    1. Kubectl create -f XXX.yaml

Actual Results:
    root@lxc1:~# kubectl get pods --all-namespaces
    NAMESPACE     NAME                READY     STATUS    RESTARTS   AGE
    default       kube-dns-v9-mgss9   4/4       Running   0          6d
    farm-10       caf-7xf3g           1/1       Running   0          3h
    farm-10       caf-c64fn           1/1       Creating  0          3h
    farm-10       caf-dyvmj           1/1       Running   0          3h
    farm-10       caf-f3q9a           1/1       Running   0          3h

Expected Results:
    we expect that the number of containers has spawned on the worker nodes
    but, it hanged on the nodes

Additional info:
    I requested to check hardware fault(like a disk) to operator.
    Let you guys know...the status once i got from my side

**Comment by thaJeztah** [comment] 2015-12-21 10:49
Looks like this is a duplicate of https://github.com/docker/docker/issues/13122, https://github.com/docker/docker/issues/6110, and https://github.com/docker/docker/issues/2987

I'll close this issue, but feel free to add more information to the existing issue

**Closed by thaJeztah** 2015-12-21 10:49 UTC
Labels: status/more-info-needed

**Comment by ted-jung** [comment] 2015-12-21 16:14
does it solved? i read the past history related with this symptom.
this issue is continuously reported from the early version of docker(0.11*) 
and i met the same one on version 1.8.2.
I'm not sure...whether it is fixed of not.
what is the right solution and treatment if it is happened again.
