### ISSUE TITLE
add option to run to control source ip to be same as that used with -p

### ISSUE THREAD

**Issue by gearoidt** [docker/docker#5931] opened 2014-05-20 11:51 UTC
With docker run -p I can have a container listening on a host interface but afaik the source of the ip traffic is the hosts "primary" interface/gateway.

For example host has a 10.132.168.10 (primary) and 192.168.1.10 interfaces.
docker run -p 192.168.1.10 ... 
The traffic routed will show up as coming from 10.132.168.10.

I've used POSTROUTING to get this to show up as coming from the interface using with -p.  
As described herehttp://blog.codeaholics.org/2013/giving-dockerlxc-containers-a-routable-ip-address/
In my ip tables looks like:
iptables -t nat -L
...
SNAT       all  --  172.17.0.3           anywhere            to:192.168.1.10
MASQUERADE  all  --  172.17.0.0/16       !172.17.0.0/16

But this is messy and restarting docker puts docker's MASQUERADE at the top of the chain so my POSTROUTING stop working.

I'd like docker to be able to manage this for me so the source of the container's ip traffic is the same as the interface specified with run -p

**Comment by YoussefKababe** [comment] 2015-01-28 01:09
+1

**Comment by medyo** [comment] 2015-01-28 14:19
+1

**Comment by jfrazelle** [comment] 2015-02-28 00:45
duplicate of https://github.com/docker/docker/issues/6743

**Closed by jfrazelle** 2015-02-28 00:45 UTC
