### ISSUE TITLE
Proposal:Add a static ip option which can persist the docker network

### ISSUE THREAD

**Issue by cc272309126** [docker/docker#8939] opened 2014-11-04 09:51 UTC
Hi,
How about add static ip option which can persist the docker network? the command like 

"docker run -i -t --static image_id /bin/bash,". 

the docker's ip is allocated by random or dhcp firsttime. but among the whole container lifecycle. the ip will not change. it just like the port mapping if i specify the port mapping like 80:8080, it will not changed among the whole container lifecycle. 

I know there is much issue about the static ip. but maybe this issue is simple enough.

**Comment by jfrazelle** [comment] 2015-01-14 21:47
closing as duplicate of https://github.com/docker/docker/issues/4952

**Closed by jfrazelle** 2015-01-14 21:47 UTC
