### ISSUE TITLE
Error about missing rootfs when attempting to start container on AWS.

### ISSUE THREAD

**Issue by sfitts** [docker/docker#26546] opened 2016-09-13 21:28 UTC
NOTE -- there are definitely other issues that mention what appears to me to be a very similar error, however, in those threads there seemed to be a preference expressed for posting new issues instead of using the existing ones.

**Description**

On AWS when I attempt to start a container I receive the error:

```
> rpc error: code = 2 desc = "oci runtime error: rootfs (\"/var/lib/docker/devicemapper/mnt/5de32f0b43fa2acc69843bfd8bdf14a6bab50885cc466ae104303bd2eeba8f25/rootfs\") does not exist"
```

**Steps to reproduce the issue:**
1. Create a new EC2 instance from an AMI which includes Docker installed (the user data for the instance creation mounts a new volume and performs a restart of the Docker service).
2. Log into the new instance and pull the image "mongo:latest" from Docker Hub.
3. Create a container from that image doing a bind mount to 2 directories on the host (/data/db and /data/configdb (these are on the newly mounted volume).
4. Attempt to start the container.

**Describe the results you received:**

The container is created, but I receive the following error when I attempt to start the container:
```
> rpc error: code = 2 desc = "oci runtime error: rootfs (\"/var/lib/docker/devicemapper/mnt/5de32f0b43fa2acc69843bfd8bdf14a6bab50885cc466ae104303bd2eeba8f25/rootfs\") does not exist"
```

**Describe the results you expected:**

I expect the container to start normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue is intermittent (though any given run of my scripts gives me about a 50% chance of hitting it).  Restarting the docker service appears to make it go away.

The details of the container being created:

```
[
    {
        "Id": "72bb9216251eb303a7c37293973975087fc03e76a07aba521c256ee9f3061e7d",
        "Created": "2016-09-13T21:11:33.505301319Z",
        "Path": "/entrypoint.sh",
        "Args": [
            "--config",
            "/data/configdb/mongod.conf"
        ],
        "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 128,
            "Error": "rpc error: code = 2 desc = \"oci runtime error: rootfs (\\\"/var/lib/docker/devicemapper/mnt/5de32f0b43fa2acc69843bfd8bdf14a6bab50885cc466ae104303bd2eeba8f25/rootfs\\\") does not exist\"",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:48b8b08dca4d307feb5b560650be81d8e5cba8e9849dbf6a21df41b48dcf340c",
        "ResolvConfPath": "/var/lib/docker/containers/72bb9216251eb303a7c37293973975087fc03e76a07aba521c256ee9f3061e7d/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/72bb9216251eb303a7c37293973975087fc03e76a07aba521c256ee9f3061e7d/hostname",
        "HostsPath": "/var/lib/docker/containers/72bb9216251eb303a7c37293973975087fc03e76a07aba521c256ee9f3061e7d/hosts",
        "LogPath": "",
        "Name": "/mongodb",
        "RestartCount": 0,
        "Driver": "devicemapper",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/data/db:/data/db:rw",
                "/data/configdb:/data/configdb:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "27017/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "27017"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "StorageOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "BlkioIOps": 0,
            "BlkioBps": 0,
            "SandboxSize": 0
        },
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "15",
                "DeviceName": "docker-202:1-415715-5de32f0b43fa2acc69843bfd8bdf14a6bab50885cc466ae104303bd2eeba8f25",
                "DeviceSize": "10737418240"
            }
        },
        "Mounts": [
            {
                "Source": "/data/db",
                "Destination": "/data/db",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/data/configdb",
                "Destination": "/data/configdb",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "72bb9216251e",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "27017/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "GPG_KEYS=DFFA3DCF326E302C4787673A01C4E7FAAAB2461C \t42F3E95A2C4F08279C4960ADD68FA50FEA312927",
                "MONGO_MAJOR=3.2",
                "MONGO_VERSION=3.2.9"
            ],
            "Cmd": [
                "--config",
                "/data/configdb/mongod.conf"
            ],
            "Image": "mongo:latest",
            "Volumes": {
                "/data/configdb": {},
                "/data/db": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "8caec236e413c9d16dfcadd2ae3207bd830591fc6eac3e51b181c8d6fe93dcb6",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "/var/run/docker/netns/8caec236e413",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "b5218f8a4a5db2a5c7bcd2edbb6b6c2085160d04352138a089f2077d1f896e32",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]
```

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64

```

NOTE -- I'm running a vanilla installation of docker just as configured by the RPM.

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-202:1-415715-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 439.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 13 GB
 Metadata Space Used: 1.122 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.19-29.55.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.4 MiB
Name: ip-172-31-7-209
ID: 5Y5M:7ZNI:5KQO:YBBR:NJRG:D4IF:6QS6:PNPH:BD6D:PIC7:CBKW:M2XL
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS running AWS Linux

**Comment by cpuguy83** [comment] 2016-09-14 18:09
ping @mlaventure

**Comment by mlaventure** [comment] 2016-09-14 21:05
@sfitts can you provide the rest of the docker logs please?

Also, is there any devicemapper related error in your syslog?

**Comment by sfitts** [comment] 2016-09-15 00:27
The next time I encounter it I'll get that info.  By "the rest of the docker logs" which one(s) do you mean?  Just the daemon log or is there something else?

**Comment by mlaventure** [comment] 2016-09-15 01:05
@sfitts just the daemon log, if you can put the daemon in debug mode even better!

**Comment by sfitts** [comment] 2016-09-17 00:39
Here's the docker log (sorry, no debug mode on this one).  I don't see any devicemapper errors in the syslog.

```
\nSat Sep 10 16:43:09 UTC 2016\n
time="2016-09-10T16:43:09.631169679Z" level=info msg="New containerd process, pid: 8366\n"
time="2016-09-10T16:43:11.280777387Z" level=warning msg="devmapper: Usage of loopback devices is str
ongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker`
to refer to dm.thinpooldev section."
time="2016-09-10T16:43:11.877384813Z" level=info msg="devmapper: Creating filesystem xfs on device d
ocker-202:1-415715-base"
time="2016-09-10T16:43:12.994759574Z" level=info msg="devmapper: Successfully created filesystem xfs
 on device docker-202:1-415715-base"
time="2016-09-10T16:43:13.086546012Z" level=info msg="Graph migration to content-addressability took
 0.00 seconds"
time="2016-09-10T16:43:13.899242019Z" level=info msg="Firewalld running: false"
time="2016-09-10T16:43:14.052456345Z" level=info msg="Default bridge (docker0) is assigned with an I
P address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2016-09-10T16:43:14.192816984Z" level=warning msg="Your kernel does not support cgroup blkio w
eight"
time="2016-09-10T16:43:14.192844879Z" level=warning msg="Your kernel does not support cgroup blkio w
eight_device"
time="2016-09-10T16:43:14.192981012Z" level=warning msg="mountpoint for pids not found"
time="2016-09-10T16:43:14.193174616Z" level=info msg="Loading containers: start."

time="2016-09-10T16:43:14.193205867Z" level=info msg="Loading containers: done."
time="2016-09-10T16:43:14.193214900Z" level=info msg="Daemon has completed initialization"
time="2016-09-10T16:43:14.193224415Z" level=info msg="Docker daemon" commit="b9f10c9/1.11.2" graphdr
iver=devicemapper version=1.11.2
time="2016-09-10T16:43:14.214209100Z" level=info msg="API listen on /var/run/docker.sock"
time="2016-09-12T19:11:38.741106645Z" level=info msg="Processing signal 'terminated'"
time="2016-09-12T19:11:38Z" level=info msg="stopping containerd after receiving terminated"
\nTue Sep 13 17:30:10 UTC 2016\n
time="2016-09-13T17:30:16.913603260Z" level=info msg="New containerd process, pid: 2514\n"
\nTue Sep 13 17:30:20 UTC 2016\n
time="2016-09-13T17:30:20.265924148Z" level=info msg="previous instance of containerd still alive (2
514)"
time="2016-09-13T17:30:22.492921984Z" level=warning msg="devmapper: Usage of loopback devices is str
ongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker`
to refer to dm.thinpooldev section."
time="2016-09-13T17:30:22.500201650Z" level=warning msg="devmapper: Base device already exists and h
as filesystem xfs on it. User specified filesystem  will be ignored."
time="2016-09-13T17:30:22.508796872Z" level=info msg="[graphdriver] using prior storage driver \"dev
icemapper\""
time="2016-09-13T17:30:22.675921108Z" level=info msg="Graph migration to content-addressability took
 0.00 seconds"
time="2016-09-13T17:30:23.158731955Z" level=info msg="Firewalld running: false"
time="2016-09-13T17:30:24.130851254Z" level=info msg="Default bridge (docker0) is assigned with an I
P address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2016-09-13T17:30:24.330600300Z" level=warning msg="Your kernel does not support cgroup blkio w
eight"
time="2016-09-13T17:30:24.330633947Z" level=warning msg="Your kernel does not support cgroup blkio w
eight_device"
time="2016-09-13T17:30:24.330755181Z" level=warning msg="mountpoint for pids not found"
time="2016-09-13T17:30:24.331420155Z" level=info msg="Loading containers: start."

time="2016-09-13T17:30:24.331743963Z" level=info msg="Loading containers: done."
time="2016-09-13T17:30:24.331756170Z" level=info msg="Daemon has completed initialization"
time="2016-09-13T17:30:24.331772456Z" level=info msg="Docker daemon" commit="b9f10c9/1.11.2" graphdr
iver=devicemapper version=1.11.2
time="2016-09-13T17:30:24.353948062Z" level=info msg="API listen on /var/run/docker.sock"
time="2016-09-13T17:46:15.130636182Z" level=info msg="Processing signal 'terminated'"
time="2016-09-13T17:46:15Z" level=info msg="stopping containerd after receiving terminated"
\nTue Sep 13 17:51:49 UTC 2016\n
time="2016-09-13T17:51:59.268492738Z" level=info msg="New containerd process, pid: 2563\n"
time="2016-09-13T17:52:04.932340015Z" level=warning msg="devmapper: Usage of loopback devices is str
ongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker`
to refer to dm.thinpooldev section."
time="2016-09-13T17:52:04.980035294Z" level=warning msg="devmapper: Base device already exists and h
as filesystem xfs on it. User specified filesystem  will be ignored."
time="2016-09-13T17:52:04.992630932Z" level=info msg="[graphdriver] using prior storage driver \"dev
icemapper\""
time="2016-09-13T17:52:05.354095531Z" level=info msg="Graph migration to content-addressability took
 0.00 seconds"
time="2016-09-13T17:52:05.681347793Z" level=info msg="Firewalld running: false"
time="2016-09-13T17:52:06.151755446Z" level=info msg="Default bridge (docker0) is assigned with an I
P address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2016-09-13T17:52:06.414478622Z" level=warning msg="Your kernel does not support cgroup blkio w
eight"
time="2016-09-13T17:52:06.414505543Z" level=warning msg="Your kernel does not support cgroup blkio w
eight_device"
time="2016-09-13T17:52:06.414625924Z" level=warning msg="mountpoint for pids not found"
time="2016-09-13T17:52:06.415290339Z" level=info msg="Loading containers: start."

time="2016-09-13T17:52:06.415714648Z" level=info msg="Loading containers: done."
time="2016-09-13T17:52:06.415740765Z" level=info msg="Daemon has completed initialization"
time="2016-09-13T17:52:06.415757229Z" level=info msg="Docker daemon" commit="b9f10c9/1.11.2" graphdr
iver=devicemapper version=1.11.2
time="2016-09-13T17:52:06.433143530Z" level=info msg="API listen on /var/run/docker.sock"
time="2016-09-13T17:57:40.605690558Z" level=info msg="Processing signal 'terminated'"
time="2016-09-13T17:57:40Z" level=info msg="stopping containerd after receiving terminated"
\nWed Sep 14 00:16:46 UTC 2016\n
time="2016-09-14T00:16:55.966314984Z" level=info msg="New containerd process, pid: 2501\n"
time="2016-09-14T00:17:02.773288999Z" level=warning msg="devmapper: Usage of loopback devices is str
ongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker`
to refer to dm.thinpooldev section."
time="2016-09-14T00:17:02.845738322Z" level=warning msg="devmapper: Base device already exists and h
as filesystem xfs on it. User specified filesystem  will be ignored."
time="2016-09-14T00:17:02.854850314Z" level=info msg="[graphdriver] using prior storage driver \"dev
icemapper\""
time="2016-09-14T00:17:03.014830072Z" level=info msg="Graph migration to content-addressability took
 0.00 seconds"
time="2016-09-14T00:17:03.252527960Z" level=info msg="Firewalld running: false"
time="2016-09-14T00:17:03.769525273Z" level=info msg="Default bridge (docker0) is assigned with an I
P address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2016-09-14T00:17:04.097124215Z" level=warning msg="Your kernel does not support cgroup blkio w
eight"
time="2016-09-14T00:17:04.097151916Z" level=warning msg="Your kernel does not support cgroup blkio w
eight_device"
time="2016-09-14T00:17:04.097246252Z" level=warning msg="mountpoint for pids not found"
time="2016-09-14T00:17:04.097904960Z" level=info msg="Loading containers: start."

time="2016-09-14T00:17:04.098351741Z" level=info msg="Loading containers: done."
time="2016-09-14T00:17:04.098364333Z" level=info msg="Daemon has completed initialization"
time="2016-09-14T00:17:04.098374796Z" level=info msg="Docker daemon" commit="b9f10c9/1.11.2" graphdr
iver=devicemapper version=1.11.2
time="2016-09-14T00:17:04.116184462Z" level=info msg="API listen on /var/run/docker.sock"
time="2016-09-14T00:23:27.157847407Z" level=info msg="Processing signal 'terminated'"
time="2016-09-14T00:23:27Z" level=info msg="stopping containerd after receiving terminated"
\nSat Sep 17 00:26:41 UTC 2016\n
time="2016-09-17T00:26:52.648694518Z" level=info msg="New containerd process, pid: 2564\n"
\nSat Sep 17 00:26:57 UTC 2016\n
time="2016-09-17T00:26:57.310071329Z" level=info msg="previous instance of containerd still alive (2
564)"
time="2016-09-17T00:26:58.440373552Z" level=warning msg="devmapper: Usage of loopback devices is str
ongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker`
to refer to dm.thinpooldev section."
time="2016-09-17T00:26:58.447044435Z" level=warning msg="devmapper: Base device already exists and h
as filesystem xfs on it. User specified filesystem  will be ignored."
time="2016-09-17T00:26:58.456103225Z" level=info msg="[graphdriver] using prior storage driver \"dev
icemapper\""
time="2016-09-17T00:26:58.790211294Z" level=info msg="Graph migration to content-addressability took
 0.00 seconds"
time="2016-09-17T00:26:59.093566129Z" level=info msg="Firewalld running: false"
time="2016-09-17T00:27:00.338623510Z" level=info msg="Default bridge (docker0) is assigned with an I
P address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2016-09-17T00:27:00.518751160Z" level=warning msg="Your kernel does not support cgroup blkio w
eight"
time="2016-09-17T00:27:00.518777884Z" level=warning msg="Your kernel does not support cgroup blkio w
eight_device"
time="2016-09-17T00:27:00.518869335Z" level=warning msg="mountpoint for pids not found"
time="2016-09-17T00:27:00.519597768Z" level=info msg="Loading containers: start."

time="2016-09-17T00:27:00.520061115Z" level=info msg="Loading containers: done."
time="2016-09-17T00:27:00.520072210Z" level=info msg="Daemon has completed initialization"
time="2016-09-17T00:27:00.520082302Z" level=info msg="Docker daemon" commit="b9f10c9/1.11.2" graphdr
iver=devicemapper version=1.11.2
time="2016-09-17T00:27:00.538185238Z" level=info msg="API listen on /var/run/docker.sock"
time="2016-09-17T00:32:43Z" level=error msg="containerd: start container" error="oci runtime error:
rootfs (\"/var/lib/docker/devicemapper/mnt/4fb78bd16b81183b27137163f76f748b9ef39bce68b861f019399aaea
c03ff03/rootfs\") does not exist" id=0da5a37cc344a4569c6226e61a7b327a92f546f31eaa500b31880a55ba26ce7
a
time="2016-09-17T00:32:43.887050427Z" level=error msg="Handler for POST /containers/mongodb/start re
turned error: rpc error: code = 2 desc = \"oci runtime error: rootfs (\\\"/var/lib/docker/devicemapp
er/mnt/4fb78bd16b81183b27137163f76f748b9ef39bce68b861f019399aaeac03ff03/rootfs\\\") does not exist\"
"
```

**Comment by sfitts** [comment] 2016-09-17 00:40
Here is what's in the kernel log around the same time:

```
Sep 17 00:32:40 ip-172-31-23-91 kernel: [  433.199563] device veth2528969 entered promiscuous mode
Sep 17 00:32:40 ip-172-31-23-91 kernel: [  433.202258] IPv6: ADDRCONF(NETDEV_UP): veth2528969: link
is not ready
Sep 17 00:32:43 ip-172-31-23-91 kernel: [  436.762464] docker0: port 1(veth2528969) entered disabled
 state
Sep 17 00:32:43 ip-172-31-23-91 kernel: [  436.765035] device veth2528969 left promiscuous mode
Sep 17 00:32:43 ip-172-31-23-91 kernel: [  436.766841] docker0: port 1(veth2528969) entered disabled
 state
Sep 17 00:32:43 ip-172-31-23-91 kernel: [  436.792099] XFS (dm-1): Unmounting Filesystem
```

**Comment by mlaventure** [comment] 2016-09-19 15:23
@sfitts unfortunately the logs are pretty sparse without them being in debug mode.

When the error occurs, does the path given in the error actually missing? Or can you find it on your filesystem?

**Comment by sfitts** [comment] 2016-09-19 20:53
I'm getting this just about every time a deploy a new server, so at some point I'll set up an AMI with the debugging turned on and get you that log (may be a day or 2 however).

In terms of the path given, it doesn't exist.  The directory above `rootfs` exists, but it is empty:

```
$ sudo ls /var/lib/docker/devicemapper/mnt/7f38dcf86c75b027151be006574eed569c19371588eb7053f2665de2db9af805/rootfs
ls: cannot access /var/lib/docker/devicemapper/mnt/7f38dcf86c75b027151be006574eed569c19371588eb7053f2665de2db9af805/rootfs: No such file or directory

$ sudo ls -ld /var/lib/docker/devicemapper/mnt/7f38dcf86c75b027151be006574eed569c19371588eb7053f2665de2db9af805
drwxr-xr-x 2 root root 4096 Sep 19 20:49 /var/lib/docker/devicemapper/mnt/7f38dcf86c75b027151be006574eed569c19371588eb7053f2665de2db9af805
```

**Comment by mlaventure** [comment] 2016-09-23 18:29
This looks to be the same error as #25382

**Comment by sfitts** [comment] 2016-09-23 18:35
Yep -- does look like the same issue.  BTW -- I've been a bit tied up getting our production environment up and running, but with that done I will likely have time to configure an AMI with debugging this weekend and see if I can't get that log for you (assuming life doesn't intervene).

**Comment by thaJeztah** [comment] 2016-10-29 03:43
Let me close this issue as a duplicate of https://github.com/docker/docker/issues/25382, so that we can have the discussion in a single place. Please add extra information you found to that issue

**Closed by thaJeztah** 2016-10-29 03:43 UTC
Labels: area/runtime, version/1.11
