### ISSUE TITLE
Containers can't connect to each other over overlay network - swarm 1.12

### ISSUE THREAD

**Issue by liyaka** [docker/docker#28799] opened 2016-11-24 11:24 UTC
I have 4 machines Ubuntu 14.04.2 trusty on running on AWS with docker 1.12.4
I run spark master and worker using swarm, as follows:
1. on the manager:
docker swarm init --advertise-addr \<manager ip\>
get worker token and
on other nodes:
docker swarm join <manager_ip>:2377 --token <token>

2. I create my overlay network:
docker network create --driver overlay mynet

3. I run my services:
_master:_
docker service create --name master --network mynet -e NODE_TYPE=master -p 50070:50070 -p 10001:10001 -p 8088:8080 -p 9000:9000 -p 4040:4040 <my spark image:version>
 
_worker:_
docker service create --name worker --network mynet -e NODE_TYPE=slave -p 8081 <my spark image:version>

Worker can not connect to master, and from what I see it looks like it is looking for the wrong internal ip:
_Running on the node with **master**:_
$ docker inspect master.1.xny6c314lhjc26j992j7ljzve | grep IPAddress
    "SecondaryIPAddresses": null,
     "IPAddress": "",
     "IPAddress": "10.255.0.8",
      "IPAddress": "**10.0.0.5**",

_Running on swarm manager:_
$ docker service inspect **master** -format="{{.Endpoint.VirtualIPs}}"

ormat=[{mc2f98vfwzye27cjak7qj93k2 10.255.0.7/16} {spzz8n70x8d4byha7tpqjis74 **10.0.0.4**/24}]

_I see in the worker log:_
Failed to connect to master/10.0.0.4:7077

_from inside worker container:_
nslookup master
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	master
Address: 10.0.0.4

It looks like master has an ip 10.0.0.5 on mynet network, while worker is looking ofr master it gets ip 10.0.0.4 - what am I missing here?? Isn't it suppose to work by definition of the overlay network that containers "see" each other inside the same network? 

_Note_: I succeeded to make it work with docker 1.13.0-rc1 on the same machines and with the same configuration using **--hostname master** for master service. Without --hostname flag it didn't work with 1.13.0.-rc1 as well..
The problem is I can not use docker RC version (or a new released version if it will be released very soon) for production...
_Another Note:_ with docker 1.11.x and swarm using docker run for both services and overlay network it also worked fine.

**Comment by liyaka** [comment] 2016-11-24 11:41
_Another Note:_ with docker 1.11.x and swarm using docker run for both services and overlay network it also worked fine.

**Comment by thaJeztah** [comment] 2016-11-25 00:49
Looks like this is a duplicate of https://github.com/docker/docker/issues/24637. There is a workaround mentioned in that issue; https://github.com/docker/docker/issues/24637#issuecomment-251189102 (Note that you should never "publish" ports that should not be accessible externally. There is no need to publish ports that have to be accessed by other containers on the same network)

Fix for this issue is in https://github.com/docker/docker/pull/26659, and is indeed part of 1.13. At this point there is no patch release scheduled for 1.12, but if one is scheduled, I can discuss if that patch can be included safely (I see the diff is quite big)

I'm closing this issue, because it is a duplicate, and will be fixed in 1.13, but feel free to comment after I closed

**Closed by thaJeztah** 2016-11-25 00:49 UTC
Labels: area/networking, area/swarm

**Comment by liyaka** [comment] 2016-11-26 11:27
Thank you. 
The workaround is not valid in my case since there is no option not to publish ports for worker. I also have more components that run on the cluster and see each other and some of them need to publish ports..
Note that in 1.13 it works only if I use "--hostname master" when running master service, so it looks like the bug is not really fixed, but at least there is a workaround that works. When 1.13.0 is planned to be released?

**Comment by thaJeztah** [comment] 2016-11-26 15:33
> Note that in 1.13 it works only if I use "--hostname master" when running master service

I'm not too familiar with spark; is the hostname used by the master as "advertise address"?

**Comment by liyaka** [comment] 2016-11-26 20:10
The hostname is "master" in this case. I can of cause configure spark to work with external ip ("advertise address"), but this will miss the whole idea of internal network..

**Comment by yogeek** [comment] 2016-11-29 17:10
@liyaka Hello, I have the same problem trying to run Spark master and workers on Docker 1.12 swarm mode cluster. Indeed, without publishing ports, it works with 1.12.3 version. 
I want to make it work with the port publication but I do not understand the "--hostname master" you mention : where do you add this option please ? Can you post the commands to launch the spark services successfully with this option ?

**Comment by liyaka** [comment] 2016-11-29 19:11
@yogeek It's a new addition in docker 1.13 -> see https://github.com/docker/docker/pull/27857
 I'm using docker v1.13.0-rc2, and I'm running master like this:
docker service create --name master --hostname master \
      --network <my network name>  --constraint 'engine.labels.role==master' \
           -e NODE_TYPE=master \
            -p 10001:10001 -p 8088:8080 -p 9000:9000 -p 4040:4040  \
           --mount type=bind,source=<my base dir>/spark/logs,destination=/usr/local/spark/logs \
           <my spark image>:<version>
and worker like this:
docker service create --name worker --network <my network> \
           --constraint 'engine.labels.role==worker' \
           --replicas 3 \
           -e NODE_TYPE=slave \
           -p 8081 \
           --mount type=bind,source=<my base dir>/spark/logs,destination=/usr/local/spark/logs \
          <my spark image>:<version>

**Comment by yogeek** [comment] 2016-11-30 16:48
@liyaka Thank you for the details. If I want to install docker v1.13.0-rc2 version with docker-machine on a cloud provider, what is the must efficient way to do it ? 
I tried to use the script mentionned in the 1.13.0-rc2 "Download" section (https://github.com/docker/docker/releases) with  the "--engine-install-url" option of docker-machine but it points to "https://test.docker.com/" and it installs a 1.12.3 version...
I also tried "https://experimental.docker.com/" but it is also a 1.12.3 (experimental i guess) version. 
Do you know any way to test this RC version with docker-machine ? 
Or any other automatic way to install it ? Thanks

**Comment by liyaka** [comment] 2016-12-02 16:49
@yogeek I don't use docker-machine - left a few months ago, too buggy, - I deploy everything with ansible.. From what you saying it looks like a bug...

**Comment by yogeek** [comment] 2016-12-02 17:19
@liyaka ok. So to install v1.13.0-rc2 with Ansible, I guess you download the tar.gz and install it manually on your nodes, right ?
Thank you for your help btw !

**Comment by liyaka** [comment] 2016-12-04 07:41
@yogeek actually tar.gz didn't work so well for me, probably because I was upgrading from 1.12.3.
I had to apt-get remove docker-engine and then: https://docs.docker.com/engine/installation/linux/ubuntulinux/#/install-a-pre-release-version

**Comment by yogeek** [comment] 2016-12-04 15:49
@liyaka Ok I get it. Finally, removing the previous version was the trick ! After 'apt remove' the 1.12.3 version, the installation through "curl0 https://test.docker.com/ | sh" worked like a charm and give me a brand new v1.13.0-rc2 c version ! Thans you again for your help 👍
