### ISSUE TITLE
Non-Experimental mode hides `--bundle-file`

### ISSUE THREAD

**Issue by albers** [docker/docker#29112] opened 2016-12-04 22:10 UTC
In experimental mode, `docker stack deploy --help` output contains both `--compose-file` and `--bundle-file`.
In non-experimental mode, only `--compose-file` is shown. Since `--compose-file` is a recent addition, I suppose it is or was experimental and that the visibility of the flags got confused.

```bash
$ docker version --format '{{.Server.Experimental}}'
false
$ docker stack deploy --help | grep -e -file
  -c, --compose-file string   Path to a Compose file
# restart daemon in experimental mode
$ docker version --format '{{.Server.Experimental}}'
true
$ docker stack deploy --help | grep -e -file
      --bundle-file string    Path to a Distributed Application Bundle file
  -c, --compose-file string   Path to a Compose file
```
ping @thaJeztah PTAL. If any of these options is experimental, I'd like to take this into account in bash completion.

**Comment by AkihiroSuda** [comment] 2016-12-05 06:03
`--bundle-file` is intentionally marked as experimental, and `--compose-file` is marked as non-experimental
 https://github.com/docker/docker/issues/28960#issuecomment-264063845

**Comment by vdemeester** [comment] 2016-12-05 07:33
As @AkihiroSuda, it is by design. ´--bundle-file´ is meant to stay experimental.

**Closed** 2016-12-05 07:34 UTC
Labels: kind/experimental, kind/question

**Comment by albers** [comment] 2017-01-10 17:08
Thanks a lot for clarification!
