### ISSUE TITLE
docker cannot stop or kill a container

### ISSUE THREAD

**Issue by tugberkugurlu** [docker/docker#22357] opened 2016-04-27 09:15 UTC
> originated from https://github.com/docker/docker/issues/10589 and opening this one based on @thaJeztah's request (https://github.com/docker/docker/issues/10589#issuecomment-214859917).

docker cannot `rm`, `stop` or `kill` the container:

```
➜  app git:(master) ✗ docker info  
Containers: 91
 Running: 2
 Paused: 0
 Stopped: 89
Images: 296
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 490
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-49-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.844 GiB
Name: ubuntu
ID: 2HH2:BL4I:ZPYE:BIXT:656Y:R7FQ:I6RQ:7H7U:YHLI:BO6K:TY2Z:6FGB
WARNING: No swap limit support

➜  app git:(master) ✗ docker logs zleek-neo4j
Starting Neo4j Server...process [139]... waiting for server to be ready............ OK.
http://localhost:7474/ is ready.
Stopping Neo4j Server [139].... done
Starting Neo4j Server console-mode...
2016-03-03 21:48:25.629+0000 INFO  Successfully started database
2016-03-03 21:48:25.719+0000 INFO  Starting HTTP on port 7474 (4 threads available)
2016-03-03 21:48:26.301+0000 INFO  Enabling HTTPS on port 7473
2016-03-03 21:48:26.510+0000 INFO  Mounting static content at /webadmin                                                                [22/1813]
2016-03-03 21:48:26.711+0000 INFO  Mounting static content at /browser
2016-03-03 21:48:29.938+0000 INFO  Remote interface ready and available at http://0.0.0.0:7474/
2016-03-03 21:59:29.931+0000 INFO  Neo4j Server shutdown initiated by request
2016-03-03 21:59:30.035+0000 INFO  Successfully shutdown Neo4j Server
2016-03-03 21:59:30.125+0000 INFO  Successfully stopped database
2016-03-03 21:59:30.126+0000 INFO  Successfully shutdown database
Starting Neo4j Server...process [142]... waiting for server to be ready........... OK.
http://localhost:7474/ is ready.
Stopping Neo4j Server [142].... done
Starting Neo4j Server console-mode...
2016-03-03 22:02:14.884+0000 INFO  Successfully started database
2016-03-03 22:02:14.927+0000 INFO  Starting HTTP on port 7474 (4 threads available)
2016-03-03 22:02:15.295+0000 INFO  Enabling HTTPS on port 7473
2016-03-03 22:02:15.431+0000 INFO  Mounting static content at /webadmin
2016-03-03 22:02:15.529+0000 INFO  Mounting static content at /browser
2016-03-03 22:02:17.219+0000 INFO  Remote interface ready and available at http://0.0.0.0:7474/
Starting Neo4j Server...process [141]... waiting for server to be ready.................. OK.
http://localhost:7474/ is ready.
Stopping Neo4j Server [141].... done
Starting Neo4j Server console-mode...
2016-03-04 14:17:36.572+0000 INFO  Successfully started database
2016-03-04 14:17:36.611+0000 INFO  Starting HTTP on port 7474 (4 threads available)                                                     [0/1813]
2016-03-04 14:17:37.014+0000 INFO  Enabling HTTPS on port 7473
2016-03-04 14:17:37.133+0000 INFO  Mounting static content at /webadmin
2016-03-04 14:17:37.209+0000 INFO  Mounting static content at /browser
2016-03-04 14:17:38.582+0000 INFO  Remote interface ready and available at http://0.0.0.0:7474/
2016-03-04 14:24:48.444+0000 INFO  Neo4j Server shutdown initiated by request
2016-03-04 14:24:48.519+0000 INFO  Successfully shutdown Neo4j Server
2016-03-04 14:24:48.592+0000 INFO  Successfully stopped database
2016-03-04 14:24:48.592+0000 INFO  Successfully shutdown database
Starting Neo4j Server...process [141]... waiting for server to be ready.......... OK.
http://localhost:7474/ is ready.
Stopping Neo4j Server [141].... done
Starting Neo4j Server console-mode...
2016-03-04 14:25:42.498+0000 INFO  Successfully started database
2016-03-04 14:25:42.541+0000 INFO  Starting HTTP on port 7474 (4 threads available)
2016-03-04 14:25:42.916+0000 INFO  Enabling HTTPS on port 7473
2016-03-04 14:25:43.043+0000 INFO  Mounting static content at /webadmin
2016-03-04 14:25:43.126+0000 INFO  Mounting static content at /browser
2016-03-04 14:25:44.578+0000 INFO  Remote interface ready and available at http://0.0.0.0:7474/
2016-03-04 14:30:23.639+0000 INFO  Neo4j Server shutdown initiated by request
2016-03-04 14:30:23.688+0000 INFO  Successfully shutdown Neo4j Server
2016-03-04 14:30:23.763+0000 INFO  Successfully stopped database
2016-03-04 14:30:23.763+0000 INFO  Successfully shutdown database

➜  app git:(master) ✗ docker --version
Docker version 1.10.2, build c3959b1

➜  app git:(master) ✗ uname -a
Linux ubuntu 3.19.0-49-generic #55~14.04.1-Ubuntu SMP Fri Jan 22 11:24:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Some suggested that it might be related to https://github.com/docker/docker/issues/18180 but I seem to have kernel `3.19.0-49-generic` but still having this issue for `neo4j/neo4j:2.3.2` image from official docker registry.

```
➜  ~ docker info 
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 69
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 155
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-49-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.844 GiB
Name: ubuntu
ID: 2HH2:BL4I:ZPYE:BIXT:656Y:R7FQ:I6RQ:7H7U:YHLI:BO6K:TY2Z:6FGB
WARNING: No swap limit support
```

It is stuck and `docker-compose stop` gives below info:

```
➜  foo git:(master) ✗ docker-compose stop
Stopping foo-neo4j ... 

ERROR: for foo-neo4j  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70) 
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

`docker kill {container-id}` also doesn't work.

## Repro Steps

I am not entirely sure as this doesn't happen all the time. Let me know if there is anything I can do moire to narrow it down.

**Comment by chromerobv** [comment] 2016-05-02 20:25
this has been happening to me recently. it is so bad that stoping docker does not fix the problem. i have to reboot the whole server. the weird thing is this problem just started happening and nothing on the box has changed.

#docker info
Containers: 20
Images: 185
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 24
Total Memory: 125.7 GiB



# docker version
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-115.el7.x86_64
Go version (client): go1.4.2
Git commit (client): 446ad9b/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-115.el7.x86_64
Go version (server): go1.4.2
Git commit (server): 446ad9b/1.7.1
OS/Arch (server): linux/amd64

**Comment by jeacott1** [comment] 2016-05-05 08:02
same problem with  "image": "percona/percona-server-mongodb" with --storageEngine=rocksDB
its fine if nothing uses the  database,  but after the database has been used the container cannot be stopped, killed, removed in any way I can find without rebooting the server.

host ubuntu
3.19.0-49-generic

**Comment by BenHall** [comment] 2016-05-06 13:10
Also seeing this behaviour on a few of our servers

![screenshot 2016-05-06 14 06 11](https://cloud.githubusercontent.com/assets/82614/15073935/1a2f6bc0-1394-11e6-9c35-20d9210e14e3.png)

![screenshot 2016-05-06 14 09 47](https://cloud.githubusercontent.com/assets/82614/15073961/38d8302a-1394-11e6-8724-ccd19cdeab82.png)

**Comment by tugberkugurlu** [comment] 2016-05-31 16:37
Is this related? https://github.com/docker/docker/issues/10589#issuecomment-222468296

Can anyone update this issue? I am seeing more hangs on other images and even docker service restart doesn't work :disappointed:

**Comment by thaJeztah** [comment] 2016-05-31 16:54
@tugberkugurlu no, that comment is about a container that didn't remove properly, so still showing as "removal in progress". This issue is about a process that hangs, and cannot be killed (for some reason).

@BenHall could your issue be https://github.com/docker/docker/issues/18180#issuecomment-193708192 ? Looks like you're running a 4.2 kernel that does not have that fix


@tugberkugurlu actually, your issue may also be related to https://github.com/docker/docker/issues/18180#issuecomment-193708192, if it is, then your issue should be fixed when upgrading to kernel 3.19.0-51.57 or later

**Comment by BenHall** [comment] 2016-05-31 17:01
@thaJeztah I spoke with @cpuguy83 at OSCON and he suggested it was an AUFS problem. I've upgraded to Docker 1.11, _4.2.0-36-generic_ and _overlay_ and everything appears to be happy.

**Comment by thaJeztah** [comment] 2016-05-31 17:23
@BenHall cool, yes that sound really like you ran into https://github.com/docker/docker/issues/18180

**Comment by tugberkugurlu** [comment] 2016-05-31 21:32
You are the man @BenHall :fireworks: :tada: updated the storage driver to overlay and everything is happy as you also indicated.

Exact steps I have followed for anyone having the same issue:

- After a while of research on OverlayFS as a n00b, I ended up [here](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/#configure-docker-with-the-overlay-storage-driver). I verified with `lsmod | grep overlay` that I don't have overlay kernel module loaded which made me end up [here](http://blog.dustinkirkland.com/2012/08/introducing-overlayroot-overlayfs.html) and I followed the instructions and installed the module.
- After a VM restart, I ran `lsmod | grep overlay` again to confirm overlay kernel module is loaded. After seeing it there, I added `--storage-driver=overlay` flag to the `DOCKER_OPTS` line inside my [docker config file](https://docs.docker.com/engine/admin/configuring/) (`/etc/default/docker`) and ran the below commands to restart docker:

    ```
    sudo /etc/init.d/docker stop
    sudo /etc/init.d/docker start
    ```

- Now I have docker up and running and I ran `docker info` which confirmed that overlay is configured as the storage driver:

	```
	Containers: 0
	 Running: 0
	 Paused: 0
	 Stopped: 0
	Images: 9
	Server Version: 1.11.1
	Storage Driver: overlay
	 Backing Filesystem: extfs
	Logging Driver: json-file
	Cgroup Driver: cgroupfs
	Plugins: 
	 Volume: local
	 Network: bridge null host
	Kernel Version: 3.19.0-49-generic
	Operating System: Ubuntu 14.04.4 LTS
	OSType: linux
	Architecture: x86_64
	CPUs: 4
	Total Memory: 3.844 GiB
	Name: ubuntu
	ID: 2HH2:BL4I:ZPYE:BIXT:656Y:R7FQ:I6RQ:7H7U:YHLI:BO6K:TY2Z:6FGB
	Docker Root Dir: /var/lib/docker
	Debug mode (client): false
	Debug mode (server): false
	Registry: https://index.docker.io/v1/
	```

At the end, I have run the build command (`docker build -t foo1 .`) for [this sample](https://github.com/tugberkugurlu/hwdotnet-rc2/tree/65d03f7e4699c1c76adaae2f8e8ecae837021dd8) which was hanging on `dotnet restore` and it worked smoothly :sparkles: :sparkles: :sparkles:

**Comment by thaJeztah** [comment] 2016-06-01 15:41
Alright, following the discussion above, I think this is resolved, and this appears to be a duplicate of https://github.com/docker/docker/issues/18180, so I'll close this issue. Feel free to comment here though 👍

**Closed by thaJeztah** 2016-06-01 15:41 UTC
Labels: area/runtime

**Comment by TheRubble** [comment] 2016-06-08 06:38
@tugberkugurlu Hi, that works a treat now, need to understand why though.

**Comment by vladkras** [comment] 2018-04-28 14:14
only server reboot helped me. I was able to stop docker with `sudo systemctl stop docker` but could not start it back.

Client&server: 17.12.1-ce

**Comment by bmodra** [comment] 2018-07-19 23:18
I had the same problem, container was running, it listed in docker ps, but did not list in docker service ls.
If I tried to kill or stop or get info on it, the command hung.
I tried shutting down docker.
That seemed to hang, so I used kill -9 on docker processes, and then restarted. All was good thereafter.

$ docker -v
Docker version 18.03.0-ce, build 0520e24
$ uname -a
Linux Brian 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

**Comment by arogozhnikov** [comment] 2018-08-14 09:32
Same problem here
```
$ sudo docker exec -it aa90c3c6c2c9 bash
OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused "process_linux.go:86: executing setns process caused \"exit status 21\"": unknown
$ sudo docker kill aa90c3c6c2c9
(hangs)
$ sudo docker stop aa90c3c6c2c9
(hangs)
$ sudo docker rm aa90c3c6c2c9
Error response from daemon: You cannot remove a running container aa90c3c6c2c9e1af1fbb4da692bd55aeec8d1e89d5958635286ca67238654560. Stop the container before attempting removal or force remove
```

```
$ docker -v
Docker version 17.12.0-ce, build c97c6d6
$ uname -a
Linux DL4 3.16.0-41-generic #57~14.04.1-Ubuntu SMP Thu Jun 18 18:01:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by zhan849** [comment] 2019-04-03 17:20
@arogozhnikov saw exactly same issue with much later docker versions. @thaJeztah can we reopen the issue and start investigation?

```bash
# docker info
Containers: 73
 Running: 42
 Paused: 0
 Stopped: 31
Images: 23
Server Version: 18.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: efs local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: nvidia
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
......
```

```
# uname -a
Linux node-k8s-use1-prod-shared-001-kubecluster-3-0a0c5466 4.15.0-15-generic #16~16.04.1-Ubuntu SMP Thu Apr 5 12:19:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Barsonax** [comment] 2019-04-30 12:42
We are experiencing the same issues on select machines where docker stop, kill or rm with force just hang without doing anything.

**Comment by PavelShalahai** [comment] 2019-07-10 10:14
Have same issue with stuck container.

:~# docker -v                                                                                                                                                                                               Docker version 18.09.7, build 2d0083d                                                                                                                                                                                                      

:~# uname -a                                                                                                                                                                                                Linux ubuntu-s-4vcpu-8gb-nyc1-01 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by canhnt** [comment] 2019-07-11 13:31
It failed to remove/stop container on docker v18.9.2. The docker errors logs is:
```
Jul 11 15:25:23 host1.example.org dockerd[1147]: time="2019-07-11T15:25:23.436401398+02:00" level=info msg="Container 8c1303015ff17c14dbafdff4a195a996a6e5116d1bca77d978e4178680746c92 failed to exit within 30 seconds of signal 15 - using the force"
Jul 11 15:25:33 host1.example.org dockerd[1147]: time="2019-07-11T15:25:33.463295747+02:00" level=info msg="Container 8c1303015ff1 failed to exit within 10 seconds of kill - trying direct SIGKILL"
Jul 11 15:25:35 host1.example.org dockerd[1147]: time="2019-07-11T15:25:35.149114816+02:00" level=info msg="Container 8c1303015ff17c14dbafdff4a195a996a6e5116d1bca77d978e4178680746c92 failed to exit within 10 seconds of signal 15 - using the force"
Jul 11 15:25:45 host1.example.org dockerd[1147]: time="2019-07-11T15:25:45.182192845+02:00" level=info msg="Container 8c1303015ff1 failed to exit within 10 seconds of kill - trying direct SIGKILL"
Jul 11 15:27:23 host1.example.org dockerd[1147]: time="2019-07-11T15:27:23.511022711+02:00" level=info msg="Container 8c1303015ff17c14dbafdff4a195a996a6e5116d1bca77d978e4178680746c92 failed to exit within 30 seconds of signal 15 - using the force"
Jul 11 15:27:33 host1.example.org dockerd[1147]: time="2019-07-11T15:27:33.538558552+02:00" level=info msg="Container 8c1303015ff1 failed to exit within 10 seconds of kill - trying direct SIGKILL"

...
Jul 11 15:29:42 host1.example.org dockerd[1147]: time="2019-07-11T15:29:42.860284771+02:00" level=error msg="stream copy error: reading from a closed fifo"
Jul 11 15:29:42 host1.example.org dockerd[1147]: time="2019-07-11T15:29:42.860351793+02:00" level=error msg="stream copy error: reading from a closed fifo"
Jul 11 15:29:42 host1.example.org dockerd[1147]: time="2019-07-11T15:29:42.951998169+02:00" level=error msg="Error running exec ef53f250f059e61d3dd9416d2a5ec488e3e6c2279485e1c2572ea9986556a53c in container: OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused \"process_linux.go:91: executing setns process caused \\\"exit status 21\\\"\": unknown"
Jul 11 15:29:47 host1.example.org dockerd[1147]: time="2019-07-11T15:29:47.854320125+02:00" level=error msg="stream copy error: reading from a closed fifo"
Jul 11 15:29:47 host1.example.org dockerd[1147]: time="2019-07-11T15:29:47.854412467+02:00" level=error msg="stream copy error: reading from a closed fifo"

```

## Docker Info
```
Containers: 146
 Running: 143
 Paused: 0
 Stopped: 3
Images: 70
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 10
Total Memory: 58.82GiB
Name: 829k8apdmain4.cloudnl.digital.kpn.org
ID: V47Y:CNUU:QHGU:VTHT:LCUK:KXRO:6I65:EAXV:HQ3I:32E6:BHLK:DLGP
Docker Root Dir: /u02/docker_graph/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by Cloudmersive** [comment] 2019-08-11 20:14
Same problem... wtf

**Comment by ameeno** [comment] 2019-08-13 09:07
yep facing the same problem, but on windows with windows containers.

**Comment by ki11roy** [comment] 2019-08-18 11:25
Same problem for Windows. Docker had not helped. The only thing that worked is the removal of folder with the container from "containers" (and "windowsfilter"). After some panic docker started without that container.

**Comment by Felix-Indoing** [comment] 2019-10-28 09:53
Same problem here, I don't mind clearing the local data, what is the fastest way to stop all the un-stoppable containers on Windows?

**Comment by noemu** [comment] 2019-11-28 07:07
Same here: mostly with the pgadmin image:
```
Docker version 18.09.9, build 1752eb3
Linux 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by shlomiken** [comment] 2019-11-28 15:51
Why is this not being reopened - i have the same issue with latest docker (and like others have overlay2 storage driver).

**Comment by cpuguy83** [comment] 2019-11-28 16:37
Because this is an issue that was closed 3.5 years ago that is almost certainly unrelated. Commenting on a closed issue is generally going to go unoticed.

If you are having a new problem, please open an new issue with all the details.
Also please make sure you are on the latest version of Docker (19.03.5).

There are a number of fixes for deadlocks wherein API endpoints for a container become unresponsive.
If you are on 19.03.5 and seeing such issues, please make sure to also include stack dumps from dockerd (`curl --unix-socket /var/run/docker.sock http://./debug/pprof/goroutine?debug=2`).
If you can also get a stack dump from containerd this will almost certainly be needed as well: `curl --unix-socket /run/containerd/containerd-debug.sock http://./debug/pprof/goroutine?debug=2`

**Comment by orgads** [comment] 2019-12-23 06:48
Happens to me occasionally with mongo. Here's the log: [docker.log](https://github.com/moby/moby/files/3993907/docker.log)

**Comment by thaJeztah** [comment] 2019-12-23 13:40
@orgads from that log, I suspect you've installed the `docker.io` package, which is built by the Debian/Ubuntu packagers. Those packaging use a packaging method that uses different versions of dependencies than is tested against in this repository (which could be problematic). Are you able to reproduce the problem on the official packages? (https://docs.docker.com/install/linux/docker-ce/ubuntu/)

**Comment by orgads** [comment] 2019-12-23 13:41
@thaJeztah: You're right. I'll install the official packages and report if it reproduces.

**Comment by orgads** [comment] 2019-12-23 17:45
There you go: [docker.log](https://github.com/moby/moby/files/3995779/docker.log)

**Comment by orgads** [comment] 2020-01-02 11:42
Anything?

**Comment by cpuguy83** [comment] 2020-01-02 17:44
As I requested, please open a new issue and include the stack dump and all the other requested details (from the issue template).

**Comment by danielehrhardt** [comment] 2020-01-06 00:27
Same here!

**Comment by orgads** [comment] 2020-01-06 07:34
I discovered that it only happens when I use fluentd logging driver. I'm trying to create a minimal example, then I'll file a new bug.

**Comment by orgads** [comment] 2020-01-06 08:08
Finally found it! #40063.

**Comment by loretoparisi** [comment] 2020-01-07 10:44
@orgads how did you solve it?

**Comment by orgads** [comment] 2020-01-07 10:45
I didn't, read the last comment on #40063. He suggest sticking with Docker 18.09 for now.

There are several pending potential fixes.

**Comment by loretoparisi** [comment] 2020-01-07 10:45
@thaJeztah this happens to me too, please have a look at https://github.com/moby/moby/issues/40352
Thank you!

**Comment by loretoparisi** [comment] 2020-01-07 10:50
@orgads thank you, I don't know if I'm using the `fluentd` logging driver, in my understanding I'm not, but I'm facing the same issue...

**Comment by Semicolon10** [comment] 2020-02-08 12:07
https://stackoverflow.com/questions/60109465/kill-docker-container-permission-denied
I have faced similar question does anyone have answer for this?

**Comment by daveisfera** [comment] 2020-02-21 16:39
Here's the output:
```
> docker kill 4691404a3536_transformationrunner
4691404a3536_transformationrunner
> docker rm 4691404a3536_transformationrunner  
Error response from daemon: You cannot remove a running container 4691404a353682d084ac4cf48142177a77fceef988a2eaab6658b017f836a404. Stop the container before attempting removal or force remove
```

C18223FD-44DC-4ACD-B197-B660FC33917F/20200221163606

**Comment by tnatanael** [comment] 2020-06-19 01:36
2020 and for those who are facing this problem:
sudo service docker stop && sudo killall dockerd && sudo service docker start

**Comment by amancioandre** [comment] 2020-07-02 18:48
Hanging with docker kill here as well:

```bash
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS                              NAMES
00ecc6875de3        0bd13774a10b        "python server.py"       16 minutes ago      Restarting (1) 13 minutes ago                                      dashboard
a77be03b6123        postgres:11.5       "docker-entrypoint.s…"   16 minutes ago      Up 16 minutes                   5432/tcp, 0.0.0.0:5432->5433/tcp   db
2d6da0d955b7        redis:alpine        "docker-entrypoint.s…"   16 minutes ago      Up 16 minutes                   0.0.0.0:6379->6379/tcp             dash_starter_redis_1
```

And after a while, with docker-compose down I get the following message:
```bash
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

Any fix?

**Comment by snowinmars** [comment] 2020-09-03 08:09
Same story. I had a container that was updating local psql db. The container freezes at some point. I made no real changes to psql at the point.

I can't `stop`/`kill --signal=9` or `rm` the container.
I can reboot docker service using `systemctl` but it changes nothing.
I can kill the container by killing one of the `ps ax | grep docker` process.

The bug is extremely rare for me, but it's just weird.

**Comment by nodermann** [comment] 2020-10-28 13:57
docker start container-id
docker stop container-id

**Comment by nodermann** [comment] 2020-10-28 13:57
```
docker start container-id
docker stop container-id
```

**Comment by TKumar8866** [comment] 2020-12-22 08:51
If you are using Docker Desktop application. Stop the Docker app and restart.
It worked for me on Mac Docker Desktop.

**Comment by deepio** [comment] 2021-06-10 12:15
This happens to me with the grafana loki log driver. So I usually update it, but turning it off and back on again might work too. 

```
docker plugin disable loki -f
docker plugin upgrade loki --grant-all-permissions
docker plugin enable loki
```

**Comment by Flute7** [comment] 2022-03-10 12:27
Why is this closed? Its not resolved at all. I continue to deal with this issue on a regular basis (monthly) and none of the posted solutions are consistently effective.

Can this issue be re-opened and addressed properly please?

**Comment by tarantelot** [comment] 2023-09-29 07:30
> This happens to me with the grafana loki log driver. So I usually update it, but turning it off and back on again might work too.
> 
> ```
> docker plugin disable loki -f
> docker plugin upgrade loki --grant-all-permissions
> docker plugin enable loki
> ```
> 
> After that I can stop the hung service if it didn't do it automatically

Is this some sort of a memory leak?
