### ISSUE TITLE
Docker client: tlsverify flag misses value

### ISSUE THREAD

**Issue by bergtwvd** [docker/docker#17951] opened 2015-11-12 22:43 UTC
See also https://github.com/docker/machine/issues/2257

On Windows 7 I installed Docker Toolbox 1.9.0b and ran through the multi-host networking example.

Step 1:
 docker-machine create -d virtualbox mh-keystore
 OK

Step 2:
 docker $(docker-machine config mh-keystore) run -d -p "8500:8500" -h "consul" progrium/consul -server -bootstrap

docker client complains about --tlsverify flag:

PS C:\Users\bergtwvd> docker $(docker-machine config mh-keystore) run -d -p "8500:8500" -h "consul" progrium/consul -ser
 ver -bootstrap
 flag provided but not defined: --tlsverify --tlscacert
 See 'C:\Program Files\Docker Toolbox\docker.exe --help'.
 PS C:\Users\bergtwvd>
 PS C:\Users\bergtwvd> echo $(docker-machine config mh-keystore)
 --tlsverify --tlscacert="C:\Users\bergtwvd\.docker\machine\certs\ca.pem" --tlscert="C:\Users\bergtwvd\.docker\
 \machine\certs\cert.pem" --tlskey="C:\Users\bergtwvd\.docker\machine\certs\key.pem" -H=tcp://192.168.99.100:237
 6
 PS C:\Users\bergtwvd>

When I set --tlsverify==true it works:

docker --tlsverify=true --tlscacert="C:\Users\bergtwvd\.docker\machine\certs\ca.pem" --tlscert="C:\Users\bergtwvd\.docker\machine\certs\cert.pem" --tlskey="C:\Users\bergtwvd\.docker\machine\certs\key.pem" -H=tcp://192.168.99.100:2376 run -d -p "8500:8500" -h "consul" progrium/consul -server -bootstrap

**Comment by crosbymichael** [comment] 2015-11-16 23:56
This is an issue with flags on the docker windows client.  Are we sure this is not a powershell issue with how you provide flags?   some type of escaping needed?  Sorry, i don't know much about powershell.

**Comment by nazar-pc** [comment] 2015-11-29 19:05
The same on Ubuntu 16.04 x64:
```
$ docker-machine create -d virtualbox mh-keystore
Running pre-create checks...
Creating machine...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Provisioning created instance...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
To see how to connect Docker to this machine, run: docker-machine env mh-keystore
$ docker (docker-machine config mh-keystore) run -d -p "8500:8500" -h "consul" progrium/consul -server -bootstrap
flag provided but not defined: --tlsverify --tlscacert
See 'docker --help'.
```

While:
```
$ docker-machine config mh-keystore
--tlsverify --tlscacert="/home/nazar-pc/.docker/machine/certs/ca.pem" --tlscert="/home/nazar-pc/.docker/machine/certs/cert.pem" --tlskey="/home/nazar-pc/.docker/machine/certs/key.pem" -H=tcp://192.168.99.100:2376
```
And all files are present where they specified.

**Comment by aperepel** [comment] 2016-02-11 18:35
This is an issue on Mac as well, a regression. My scripts stopped working because `docker-machine config` outputs `--tlsverify` and for whatever reason docker is no longer liking it.

**Comment by cpuguy83** [comment] 2016-02-11 19:38
@aperepel please explain.
`--tlsverify` is still a flag, and is on OSX client.

**Comment by LK4D4** [comment] 2016-09-14 18:53
@cpuguy83 do you know what's going on?

**Comment by cpuguy83** [comment] 2016-09-15 13:50
let's close this because this does not appear to be an issue.

@aperepel @bergtwvd Please explain more if you can. `--tlsverify` is a flag on the client defined for all platforms.
We need more info to be able to troubleshoot this.

**Closed by cpuguy83** 2016-09-15 13:50 UTC
Labels: area/cli, platform/windows
