### ISSUE TITLE
Mount data volume to docker with read&write permission, while do not corrupt date in host folder.

### ISSUE THREAD

**Issue by XiaokunHou** [docker/docker#12867] opened 2015-04-29 09:30 UTC
I need to share some data in containers, so I added volumes to container. Some manipulations need read & write permissions, and at the same time, the host data should not be corrupted, otherwise, it will affect other containers.
I can imagine one solution that mount two volumes to the same folder, one has read only permission and the other has read & write permission, just like AUFS does.
```bash
docker run -ti --name build_cent1 -v /codebase/:/code:ro -v /temp:/code:rw centos6:1.0 bash
```
But it doesn't work in docker, the later one will overwrite the former one. Anyone has such problem?
Or this is a valid enhancement for docker?

**Comment by coolljt0725** [comment] 2015-04-29 10:51
what the version of your docker? I think your use case should show an error `Error response from daemon: Duplicate volume mount /code`

**Comment by cpuguy83** [comment] 2015-04-29 13:29
You can't mount two different dirs to the same location.
I also don't really see the point in doing one ro and one rw in the same container, there is no security there.

Maybe I don't understand your use case?

**Comment by XiaokunHou** [comment] 2015-04-29 16:21
What I want is to make several container share one data source. It can do manipulations in it, in my case it to do compilation. But every container would not corrupt the source data, otherwise it would affect other containers.
What I posted is just the way AUFS can do with it? Read data from data source one and write date to temp source two.
@coolljt0725 This command do not have an error, it seems that only the later one works.

**Comment by nixun** [comment] 2015-04-30 08:58
you can simply use overlayfs to fix this:
mount -t overlay overlay -olowerdir=/codebase,upperdir=/temp,workdir=/workdir /codebase_new
docker run -ti --name build_cent1 -v /codebase_new:/code:rw centos6:1.0 bash

**Comment by XiaokunHou** [comment] 2015-05-03 15:14
@nixun I will try it! It seems what I want！

**Comment by XiaokunHou** [comment] 2015-05-06 06:55
My "Storage Driver" for docker is devicemapper, because I am using red hat 6. It seems not possible to use overlayfs or aufs. How should I handle it with devicemapper?

I think docker should support union mount features for end users.

**Comment by thaJeztah** [comment] 2015-07-05 21:44
I'm going to close this issue because this is a question, not a bug or feature request. Feel free to comment here after the issue is closed.

**Closed by thaJeztah** 2015-07-05 21:44 UTC
