### ISSUE TITLE
Unit test TestOverlayCreateSnap fails (on Fedora)

### ISSUE THREAD

**Issue by runcom** [docker/docker#21686] opened 2016-03-31 11:48 UTC
This test is consistently failing on my host with:

```
--- FAIL: TestOverlayCreateSnap (0.00s)
        graphtest_unix.go:122: stat /var/tmp/docker-graphtest-723995303/overlay/Snap/merged/a subdir: no such file or directory
FAIL
coverage: 31.9% of statements
```

docker info
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 167
Server Version: 1.11.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.6-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.44 GiB
Name: localhost.localdomain
ID: JQDM:ZDU3:BYSR:SIMJ:QGDH:GBGW:MF7Q:VYLQ:UYFD:W5KY:H4WG:PIMF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 48
 System Time: 2016-03-31T13:47:54.765083779+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
```

docker version
```
Client:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   47fa54a
 Built:        Thu Mar 31 13:44:02 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   47fa54a
 Built:        Thu Mar 31 13:44:02 2016
 OS/Arch:      linux/amd64
 Experimental: true
```
I don't have any clue about this - might be kernel version (?), this fails on 4.2.x kernel also
ping @LK4D4 @estesp @calavera @icecrime

**Comment by dmcgowan** [comment] 2016-04-05 20:26
This test is failing for me on Fedora as well, I tracked it down to this commit https://github.com/docker/docker/pull/21454/commits/57ca2a210108d31f8cbe9660bcd6cd469a937ff7.

The graphdriver `Get` is returning a non-mounted merge directory since the mounted check is reporting that  `merged` is already an overlay mount since the underlying FS at `/var/tmp` is overlay.

```
root@596305fc2593:/go/src/github.com/docker/docker# ls -l /var
total 36
drwxr-xr-x.  2 root root  4096 Jan  6 15:18 backups
drwxr-xr-x.  7 root root  4096 Apr  5 19:52 cache
drwxr-xr-x. 20 root root  4096 Apr  5 19:52 lib
drwxrwsr-x.  2 root staff 4096 Jan  6 15:18 local
lrwxrwxrwx.  1 root root     9 Feb 16 17:56 lock -> /run/lock
drwxr-xr-x.  4 root root  4096 Apr  5 19:52 log
drwxrwsr-x.  2 root mail  4096 Feb 16 17:56 mail
drwxr-xr-x.  2 root root  4096 Feb 16 17:56 opt
lrwxrwxrwx.  1 root root     4 Feb 16 17:56 run -> /run
drwxr-xr-x.  2 root root  4096 Apr  5 19:52 spool
drwxrwxrwt.  2 root root  4096 Jan  6 15:18 tmp
root@596305fc2593:/go/src/github.com/docker/docker# df -h
Filesystem                     Size  Used Avail Use% Mounted on
overlay                        174G  145G   21G  88% /
tmpfs                          7.8G     0  7.8G   0% /dev
tmpfs                          7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/mapper/fedora_m3800-home  174G  145G   21G  88% /etc/hosts
shm                             64M     0   64M   0% /dev/shm
none                           7.8G     0  7.8G   0% /tmp
root@596305fc2593:/go/src/github.com/docker/docker# stat /var/tmp
  File: '/var/tmp'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 35h/53d	Inode: 20119275    Links: 2
Access: (1777/drwxrwxrwt)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-04-05 17:54:33.559879519 +0000
Modify: 2016-01-06 15:18:10.000000000 +0000
Change: 2016-04-05 19:52:28.203706316 +0000
 Birth: -
```

Not sure if test should be updated or overlay logic. Mounting overlay on overlay should be allowed though.

Ping @anusha-ragunathan @tonistiigi @cpuguy83

**Comment by cpuguy83** [comment] 2016-04-05 20:37
:( ok, adding this to 1.11 milestone

**Comment by tonistiigi** [comment] 2016-04-05 20:52
> Mounting overlay on overlay should be allowed though.

Maybe we should disable it. It's not good for performance and there are some known limitations in https://github.com/docker/docker/pull/18560#issuecomment-172309851. You can(should) always create a volume for dind. We already disable it for other similar cases. Not sure if this is the full fix for the issue though as @runcom doesn't seem to have 2 levels of overlay.

**Comment by dmcgowan** [comment] 2016-04-05 21:05
@tonistiigi I partially agree with you, I am not advocating for supporting overlay on overlay and I agree there should also be a volume when doing dind. But having the graphdriver perform incorrectly (returning a non-mounted directory on `Get`) still seems wrong and if that is to be disallowed should be enforced on graphdriver creation. 

I only experienced this while running inside the dev container `make shell` or running as `make test`. Running the test directly on my host works fine, so I was assuming that @runcom was likely also in the same situation but I will let him confirm that.

**Comment by tonistiigi** [comment] 2016-04-05 21:07
@dmcgowan If you do `make shell` then `/var/lib/docker` should be a volume and not be backed by main overlay.

**Comment by dmcgowan** [comment] 2016-04-05 21:10
@tonistiigi the problem is that the unit test uses `/var/tmp` which is not

**Comment by anusha-ragunathan** [comment] 2016-04-07 01:17
If we truly want to support overlay on overlay, then the graphdriver.Mounted() call (also used by aufs, overlay and zfs) can be updated to use the mountpoint binary or /proc parsing to determine if mergedDir is mounted.

**Comment by cpuguy83** [comment] 2016-04-07 01:21
I think we'd only need to do this on overlay (not sure about zfs) since we don't support aufs on aufs.

**Closed** 2016-04-07 08:07 UTC
Labels: area/storage/overlay, kind/flakytest
