### ISSUE TITLE
Availablity to have --no-cache=true for a single instruction in Dockerfile

### ISSUE THREAD

**Issue by melezhik** [docker/docker#22832] opened 2016-05-19 11:51 UTC
Hi! First of all - thanks for great tool guys!

I base on https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#build-cache

Is it possible to have `--no-cache=true` for a single instruction in Dockerfile? 

Thanks

**Comment by thaJeztah** [comment] 2016-05-19 12:48
No that's not possible (at least, not directly). Ideally, you want a Dockerfile to be reproducible, so that each time you build the Dockerfile with the same "context" (files that are added to the image, through `COPY` or `ADD`) you get *exactly* the same result. Docker evaluates each step in the Dockerfile and determines if the cache can be used, or not (because something changed); if the cache cannot be used, each step after that won't use the cache either.

There are some things that can complicate this, and that's mainly if your Dockerfile makes use of remote content (e.g. downloads something, installs a package, clones a git repository). If that remote content is added through a `ADD` step, Docker *always* downloads that content, then compares it to the cache to check if something changed.

However, if you download remote content through a `RUN` step (e.g. `curl https://somewhere`, or you `git clone` a repository and use "master"), docker has no way to determine if something changed, because it compares the literal *text* of the `RUN` instruction to determine if the cache should be used.

For that reason, it's important to be specific in your Dockerfile if you want them to be reproducible (e.g. use `apt-get install some-package=<version>`, to specify the exact version you want to install, and `git checkout <commit-hash>` to get  a specific version of your source code).

*However*, there are some things to make this easier;

Use `docker build --no-cache`, and split your Dockerfile into a "base" image, containing content that doesn't change much, and a "regular" image (that uses `FROM my-base-image`). You can build that "base" image once, and build the regular image using `--no-cache` so that it never uses the cache

To forcibly break the cache, you can use "build-time arguments" (`ARG`); changing the value of that argument breaks the cache, and every step after it, for example:

```Dockerfile
FROM something
RUN apt-get update && apt-get install foo bar baz ......

ARG CACHE_DATE=2016-01-01

# steps below will always be executed if `CACHE_DATE` is changed to a unique value
RUN blablabla
```

And set a new date for `CACHE_DATE` during build:

```bash
docker build --build-arg CACHE_DATE=$(date) ....
```

For a (long) discussion on this subject, see https://github.com/docker/docker/issues/1996


Hope this helps! I'll close this issue, because it's a question, not a bug, and theres a long discussion already in  https://github.com/docker/docker/issues/1996, but feel free to comment here after I closed

**Closed by thaJeztah** 2016-05-19 12:48 UTC

**Comment by melezhik** [comment] 2016-05-19 13:09
HI @thaJeztah ! Thanks for detailed explanation of docker cache. I am docker newbie , so some things could be "unusual" for me.

And yes, forcefully skipping some instruction and forcefully re-excuting other ones would give me more grained control when dealing with time consuming builds ... Splitting things on base ( none changing ) / and changing parts is good idea, but sometimes you know it is not proper, as even my changing part has some time consuming instructions and   some fast instructions , so I'd be good to take control over it.

But that's ok. :smile: if I came up with any ideas, will let you know!

**Comment by thaJeztah** [comment] 2016-05-19 13:21
Yes, planning your Dockerfile may take some time; always put things that change often at the end of the file (if possible), such as `COPY my-source-code`, use a `.dockerignore` file to prevent "busting" the cache on changes that don't affect your actual build (and it may save some time). 

Also, during development, you can bind-mount files that don't need compiling into your container (particularly useful for people doing web-development), e.g.

The Dockerfile is built to *deploy* the site;
```Dockerfile
FROM webserver-of-your-liking
COPY public_html /somewhere/public_html
...
```

But during development, run a container from it, and bind-mount your local files in the container, to allow "live editing" of the files (and viewing the results), without having to re-build the image each time;

```bash
docker run -d -p 8080:80 -v $(pwd)/public_html:/somewhere/public_html myproject-image
```

**Comment by melezhik** [comment] 2016-05-19 13:29
Ahh, note sure it this helps me a lot, I am running kinda black box installer which beyond my control , as example please take a look at https://github.com/melezhik/docker-projects/tree/master/gitprep - this is Dokerfile to install GitPrep application.

**Comment by melezhik** [comment] 2016-05-19 13:31
`RUN sparrow plg run gitprep` instruction is quite slow, as under the hood it relies on internal installer ( something like `carton install` I guess ) with manages files right on the image, so they can't be attached externally . Sometimes I need to have `--no-cache=true` for other instuctions in my Dockerfile, but not for this quite slow one. :smile:

**Comment by melezhik** [comment] 2016-05-19 13:35
Ahh, sorry , you meant `docker run` , not `docker build` phase ? This won't help me too, as I for example run Debian image , still having Ubuntu at my host, so I can't add  `Bind mount a volume` for compiled perl modules for the possible incompatibility ...

**Comment by thaJeztah** [comment] 2016-05-19 13:41
You have the `sparrow plg run gitprep` as your command now; but you mention it does an "install" step too. Does that have to be executed each time the image is run? Is there some option to split the "install" step, so that that can be done inside a `RUN`? And only do the actual "sparrow run" inside the `CMD`?

**Comment by melezhik** [comment] 2016-05-19 13:50
Sorry, can't understand you ...

`sparrow plg run` command behaves differently depends on whether it has input arguments. For example:


* `RUN sparrow plg run gitprep` - installs GitPrep server ( time consuming )
* `CMD sparrow plg run gitprep --param action=start --param start_mode=foreground` - runs GitPrep server ( which is installed by previous instruction ) - takes a seconds

> Does that have to be executed each time the image is run?

I am a bit confused  here. I thought that Dockerfile instructions are only executed during `docker build` ,  not `docker run`?

**Comment by thaJeztah** [comment] 2016-05-19 13:57
Ah, that's what confused be, because you had both `RUN sparrow plg run gitprep` *and* `CMD sparrow plg run gitprep ...`. I thought that `CMD sparrow plg run gitprep ...` would also *install* GitPrep each time. Ignore my comment then :)

**Comment by melezhik** [comment] 2016-05-19 13:57
Yes, I see :)

**Comment by melezhik** [comment] 2016-05-19 14:10
BTW, sorry if this one is off-topic , but this is how and why I use docker to install GitPrep - http://blogs.perl.org/users/melezhik/2016/05/playing-with-docker-and-sparrow.html

**Comment by thaJeztah** [comment] 2016-05-19 14:19
Oh, you can simplify the steps; there's no need to manually check out your git repo; this works;

```bash
sudo docker build -t melezhik/gitprep https://github.com/melezhik/docker-projects.git#:gitprep
```
(see https://docs.docker.com/engine/reference/commandline/build/)

**Comment by melezhik** [comment] 2016-05-19 14:59
Hi!
Thanks for pointing this. Good thing. It works!

```

melezhik@melezhik-pc:~/projects/docker-projects/gitprep$ sudo docker build -t melezhik/gitprep https://github.com/melezhik/docker-projects.git#:gitprep
[sudo] password for melezhik: 
Sending build context to Docker daemon 3.584 kB
Step 1 : FROM perl:5.20
 ---> bbe5a82c1dbe
Step 2 : RUN apt-get update
 ---> Using cache
 ---> 84c188610df1
Step 3 : RUN apt-get install sudo
 ---> Using cache
 ---> e7354ab9667b
Step 4 : RUN cpanm Sparrow
 ---> Using cache
 ---> bc66080368e8
Step 5 : RUN sparrow index update
 ---> Using cache
 ---> 0f6d2173ddf4
Step 6 : RUN sparrow index summary
 ---> Using cache
 ---> ba1d47d2fcfc
Step 7 : RUN sparrow plg install gitprep
 ---> Using cache
 ---> 42292b5e3b70
Step 8 : RUN sparrow plg run gitprep
 ---> Using cache
 ---> 421342a1dffe
Step 9 : CMD sparrow plg run gitprep --param action=start --param start_mode=foreground
 ---> Running in 1c9bb87bde33
 ---> 629cf023ee1f
Removing intermediate container 1c9bb87bde33
Successfully built 629cf023ee1f

```

**Comment by melezhik** [comment] 2016-05-19 15:06
Hi! FIY, http://blogs.perl.org/users/melezhik/2016/05/playing-with-docker-and-sparrow.html see my comment. Thanks again.

**Comment by thaJeztah** [comment] 2016-05-19 16:00
👍

**Comment by MaRuifeng** [comment] 2016-07-08 07:20
Referring to the above solution which uses a build-time argument to break the cache, 

    docker build --build-arg CACHE_DATE=$(date) ....

it might be helpful to use `$(date +%Y-%m-%d:%H:%M:%S)`, as `$(date)` simply gives output like `Fri Jul 8 15:16:08 SGT 2016`, which makes docker think there are multiple arguments given. Instead `$(date +%Y-%m-%d:%H:%M:%S)` just outputs `2016-07-08:15:20:10`, a string without space.

**Comment by schollii** [comment] 2018-10-27 00:55
@MaRuifeng you should be able to do CACHE_DATE="$(date)"

**Comment by krichter722** [comment] 2019-01-22 14:37
This is a duplicate of https://github.com/moby/moby/issues/1996

**Comment by filipbekic01** [comment] 2019-08-15 12:41
> No that's not possible (at least, not directly). Ideally, you want a Dockerfile to be reproducible, so that each time you build the Dockerfile with the same "context" (files that are added to the image, through `COPY` or `ADD`) you get _exactly_ the same result. Docker evaluates each step in the Dockerfile and determines if the cache can be used, or not (because something changed); if the cache cannot be used, each step after that won't use the cache either.
> 
> There are some things that can complicate this, and that's mainly if your Dockerfile makes use of remote content (e.g. downloads something, installs a package, clones a git repository). If that remote content is added through a `ADD` step, Docker _always_ downloads that content, then compares it to the cache to check if something changed.
> 
> However, if you download remote content through a `RUN` step (e.g. `curl https://somewhere`, or you `git clone` a repository and use "master"), docker has no way to determine if something changed, because it compares the literal _text_ of the `RUN` instruction to determine if the cache should be used.
> 
> For that reason, it's important to be specific in your Dockerfile if you want them to be reproducible (e.g. use `apt-get install some-package=<version>`, to specify the exact version you want to install, and `git checkout <commit-hash>` to get a specific version of your source code).
> 
> _However_, there are some things to make this easier;
> 
> Use `docker build --no-cache`, and split your Dockerfile into a "base" image, containing content that doesn't change much, and a "regular" image (that uses `FROM my-base-image`). You can build that "base" image once, and build the regular image using `--no-cache` so that it never uses the cache
> 
> To forcibly break the cache, you can use "build-time arguments" (`ARG`); changing the value of that argument breaks the cache, and every step after it, for example:
> 
> ```dockerfile
> FROM something
> RUN apt-get update && apt-get install foo bar baz ......
> 
> ARG CACHE_DATE=2016-01-01
> 
> # steps below will always be executed if `CACHE_DATE` is changed to a unique value
> RUN blablabla
> ```
> 
> And set a new date for `CACHE_DATE` during build:
> 
> ```shell
> docker build --build-arg CACHE_DATE=$(date) ....
> ```
> 
> For a (long) discussion on this subject, see #1996
> 
> Hope this helps! I'll close this issue, because it's a question, not a bug, and theres a long discussion already in #1996, but feel free to comment here after I closed

="$(date)" instead of =$(date)

**Comment by thaJeztah** [comment] 2019-08-15 17:53
> ```
> ="$(date)" instead of =$(date)
> ```

Ah, thanks; yes, it was just to illustrate the idea. I updated my comment and added quotes
