### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by iCHAIT** [docker/docker#20966] opened 2016-03-04 20:49 UTC
I am trying to set up a python-django application on my local machine and keep getting this error. I built all the containers and images using the Docker set up file. Consequently, when I try to run `docker-compose up` and try to access my `DOCKER_HOST:8000` I get the following TRACEBACK - 

```
web_1   | Traceback (most recent call last):
web_1   |   File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
web_1   |     self.result = application(self.environ, self.start_response)
web_1   |   File "/usr/lib64/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
web_1   |     return self.application(environ, start_response)
web_1   |   File "/usr/lib64/python2.7/site-packages/django/core/handlers/wsgi.py", line 206, in __call__
web_1   |     response = self.get_response(request)
web_1   |   File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 196, in get_response
web_1   |     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
web_1   |   File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 234, in handle_uncaught_exception
web_1   |     if resolver.urlconf_module is None:
web_1   |   File "/usr/lib64/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
web_1   |     self._urlconf_module = import_module(self.urlconf_name)
web_1   |   File "/usr/lib64/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
web_1   |     __import__(name)
web_1   |   File "/opt/pgd/pgd/urls.py", line 7, in <module>
web_1   |     admin.autodiscover()
web_1   |   File "/usr/lib64/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
web_1   |     import_module('%s.admin' % app)
web_1   |   File "/usr/lib64/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
web_1   |     __import__(name)
web_1   |   File "/usr/lib/python2.7/site-packages/registration/admin.py", line 3, in <module>
web_1   |     from django.contrib.sites.requests import RequestSite
web_1   | ImportError: No module named requests
```

In the browser when I access `DOCKER_HOST:8000` it gives me - 

`A server error occurred.  Please contact the administrator.`

When I typescripted the output of the docker setup file it clearly indicates that it downloads and installs the request module - 

```
Collecting requests<2.6,>=2.2.1 (from docker-compose==1.2.0->-r requirements.txt (line 11))
  Downloading requests-2.5.3-py2.py3-none-any.whl (468kB)
```

But throws me this error when I run `docker-compose up`.

#### Docker Version:

```
Docker version 1.10.1, build 9e83765
```

#### docker-compose Version: 

```
docker-compose version 1.6.0, build d99cad6
```

#### docker Info:

```
Containers: 20
 Running: 0
 Paused: 0
 Stopped: 20
Images: 20
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: LHWD:TNXY:BDXI:R642:BEWW:K6OC:PEA5:O42G:4HQY:GMHU:AX5Y:QWUF
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 21
 System Time: 2016-03-04T20:41:52.194636342Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by cyphar** [comment] 2016-03-04 21:02
The error doesn't look like it's from `docker-compose` (which installs all of its dependencies **on your host**). It looks like it's from your container.

**Comment by calavera** [comment] 2016-03-04 21:12
Thanks for opening this @iCHAIT. As @cyphar mentions, your log shows that the `requests` package is being installed **on your host**. That doesn't mean that's inside the container. You must install that dependency when you build the container.

I'm going to close this issue because it doesn't look like the problem is in docker itself but in your container built process. Please, feel free to comment if this is not correct and we'll reopening it.

Cheers.

**Closed by calavera** 2016-03-04 21:12 UTC
