### ISSUE TITLE
Containers get duplicate bridged IPs after docker daemon is restarted

### ISSUE THREAD

**Issue by dpeters** [docker/docker#27404] opened 2016-10-14 23:47 UTC
**Description**
We are encountering containers with duplicate bridged IP addresses. This occurs when the docker daemon is restarted while containers remain running, as the docker daemon will begin handing out the same IP addresses to new containers.

**Steps to reproduce the issue:**
1. start a couple of containers
2. restart the docker daemon
3. start a couple more containers

**Describe the results you received:**
The containers started after the docker daemon restart are given the same IP address as the already running containers.

**Describe the results you expected:**
The containers started after the docker daemon restart should get unique IP addresses.

**Additional information you deem important (e.g. issue happens only occasionally):**

Before restarting the docker daemon

```
$ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "a6452e05c0654362670f81b448c6bd9172ce90d5993d7d0c21a5439484d45747",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.35.1/24",
                    "Gateway": "172.16.35.1"
                }
            ]
        },
        "Containers": {
            "1f95533c5dd7d065db14f01a73990e68c6cfa1c58d759274436dfde391f91479": {
                "Name": "thing1",
                "EndpointID": "01142a5dcfaea4fd9c0a285faf144c88c8c6740506d7debab0bc3d387f458e8b",
                "MacAddress": "02:42:ac:10:23:02",
                "IPv4Address": "172.16.35.2/24",
                "IPv6Address": ""
            },
            "20bc5a8a85003161e3ad0af4e5bc0e668b0b64cab7645757098241c91bbbb604": {
                "Name": "thing2",
                "EndpointID": "9b45180d6f9a6e877e3cc1b483637c039c5e54cebe74658d4d04adfde5da8e34",
                "MacAddress": "02:42:ac:10:23:03",
                "IPv4Address": "172.16.35.3/24",
                "IPv6Address": ""
            },
            "71fc924c7ad8fc5f552991a64f924b39d1100c75c8133342cb7087d63bc2e56c": {
                "Name": "thing3",
                "EndpointID": "7ed97bc62eccf341cb17dd5fc681ac3ac713e31a49d6047fe3b14f11813b5107",
                "MacAddress": "02:42:ac:10:23:04",
                "IPv4Address": "172.16.35.4/24",
                "IPv6Address": ""
            },
            "f42c9c8095a9392ea1f556ef4ebd0a0dc28a53f9e8e2ed192ed315f84a3d1251": {
                "Name": "jolly_elion",
                "EndpointID": "d3a90ce26c98e1b8115ea01244434ca91f9ceaa17b0abf97679916887f646140",
                "MacAddress": "02:42:ac:10:23:05",
                "IPv4Address": "172.16.35.5/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1450"
        }
    }
]
```

Then after restarting the docker daemon:

```
$ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "a6452e05c0654362670f81b448c6bd9172ce90d5993d7d0c21a5439484d45747",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.35.1/24",
                    "Gateway": "172.16.35.1"
                }
            ]
        },
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1450"
        }
    }
]
```

Then after starting a new container:

```
core@iseb00303 ~ $ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "a6452e05c0654362670f81b448c6bd9172ce90d5993d7d0c21a5439484d45747",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.35.1/24",
                    "Gateway": "172.16.35.1"
                }
            ]
        },
        "Containers": {
            "ca506f31c40e1b11d9d876c4b46b031aeef22b16d22bbd08c9b5843006921036": {
                "Name": "tiny_hawking",
                "EndpointID": "0e9a5566e27b3325b23ba246996569ff40ada126cc3f04b787c07b5268db98d8",
                "MacAddress": "02:42:ac:10:23:02",
                "IPv4Address": "172.16.35.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1450"
        }
    }
]
```

Meanwhile, all containers from both before and after restarting the daemon are still up.

**Output of `docker version`:**

```
Docker version 1.12.0, build 8eab29e
```

**Output of `docker info`:**

```
Containers: 21
Running: 7
Paused: 0
Stopped: 14
Images: 412
Server Version: 1.12.0
Storage Driver: overlay
Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.5.0-coreos-r1
Operating System: CoreOS 1010.1.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 141.6 GiB
Name: iseb00303
ID: ECKH:TYVA:7CPL:TRPP:OYPP:GRDW:VN2S:KTDB:XNYA:S77A:CQY3:JWFI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Observed on physical servers, and in AWS.

**Comment by thaJeztah** [comment] 2016-10-15 00:31
Are you still able to reproduce this on the current version (1.12.2)?

**Comment by aboch** [comment] 2016-10-15 02:29
@dpeters 
Trying to understand the issue: The `bridge` network does not contain any container after you restarted the daemon. I am referring to the o/p after the line `Then after restarting the docker daemon:`.

Can you confirm the running container do not show as connected after daemon restart, or was a mistake in posting the output.

Then you start a new container, and only that one shows in the o/p of `docker network inspect bridge`.

From network db point of view, things are consistent.

Are you sure the previously run containers `thing1`, `thing2`,... are running ?

**Comment by dpeters** [comment] 2016-10-17 16:30
@thaJeztah - I'll give that a try today and report back.

@aboch - I didn't paste `docker ps` output, but the initial containers were all still running. I'll add `docker ps` output to the info I grab from the 1.12.2 testing I do shortly.

**Comment by dpeters** [comment] 2016-10-17 18:16
I was able to reproduce this with 1.12.2.

Status before restarting the docker daemon:
```
core@node3 ~ $ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "2b2d3e4c2927c6d7b509cbede697101dfd86378ce8340bfbbc5133b31098c979",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.35.1/24",
                    "Gateway": "172.16.35.1"
                }
            ]
        },
        "Containers": {
            "1b96d01845e921596ba733e003bba919d47effd59200d07a022d375d00fb3d71": {
                "Name": "thing2",
                "EndpointID": "60d9e648f30afd239ebc37ab0da2e15317b4e53f3a84058da16dda372cc11dc0",
                "MacAddress": "02:42:ac:10:23:04",
                "IPv4Address": "172.16.35.4/24",
                "IPv6Address": ""
            },
            "9a35b57fdbdf2e7394faa9749e938374ff91fa3c9875950f33bb9926247fe134": {
                "Name": "k8s_POD.b0a42b27_dd-agent-iseb00303_default_93df18fd6f185f45b26686365f51291c_6eada28c",
                "EndpointID": "63713eefdb1fd7f676a521cfcd1fedd440127543fd57134fb9de5e3620a399fc",
                "MacAddress": "02:42:ac:10:23:02",
                "IPv4Address": "172.16.35.2/24",
                "IPv6Address": ""
            },
            "bc16f754120df34ca968618a95bfa54c4d444aa327c26f59f80e71fdeafa4b73": {
                "Name": "thing1",
                "EndpointID": "44c7a614ee815b339ff6792f3219c87d2926433711523576fdd0bc7c1e24512b",
                "MacAddress": "02:42:ac:10:23:03",
                "IPv4Address": "172.16.35.3/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1450"
        }
    }
]
core@node3 ~ $ docker ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                    NAMES
1b96d01845e9        docker.place/iaas/gogo           "nginx -g 'daemon off"   14 seconds ago      Up 10 seconds       80/tcp, 443/tcp          thing2
bc16f754120d        docker.place/iaas/gogo           "nginx -g 'daemon off"   23 seconds ago      Up 19 seconds       80/tcp, 443/tcp          thing1
09748d8f106e        docker.io/datadog/docker-dd-agent:kubernetes   "/entrypoint.sh super"   47 minutes ago      Up 47 minutes                                k8s_dd-agent.681a0d7e_dd-agent-node3_default_93df18fd6f185f45b26686365f51291c_ae925d1b
c7a12d891eba        gcr.io/google_containers/exechealthz:1.0       "/exechealthz '-cmd=n"   47 minutes ago      Up 47 minutes                                k8s_healthz.c34509c2_dd-agent-node3_default_93df18fd6f185f45b26686365f51291c_9c091662
b0ed112ca94e        gcr.io/google_containers/hyperkube:v1.3.3      "/bin/sh -c '/hyperku"   47 minutes ago      Up 47 minutes                                k8s_kube-proxy.204446a5_kube-proxy-node3_default_220120ac36df4e8bbd6c590d2413b27f_5a08d4aa
3c1f7755b99c        gcr.io/google_containers/pause-amd64:3.0       "/pause"                 47 minutes ago      Up 47 minutes                                k8s_POD.d8dbe16c_kube-proxy-node3_default_220120ac36df4e8bbd6c590d2413b27f_38c7087b
9a35b57fdbdf        gcr.io/google_containers/pause-amd64:3.0       "/pause"                 47 minutes ago      Up 47 minutes       0.0.0.0:8125->8125/udp   k8s_POD.b0a42b27_dd-agent-node3_default_93df18fd6f185f45b26686365f51291c_6eada28c
```


The state after restarting the docker daemon:
```
core@iseb00303 ~ $ docker ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                    NAMES
1b96d01845e9        docker.place/iaas/gogo           "nginx -g 'daemon off"   49 seconds ago      Up 46 seconds       80/tcp, 443/tcp          thing2
bc16f754120d        docker.place/iaas/gogo           "nginx -g 'daemon off"   58 seconds ago      Up 55 seconds       80/tcp, 443/tcp          thing1
09748d8f106e        docker.io/datadog/docker-dd-agent:kubernetes   "/entrypoint.sh super"   48 minutes ago      Up 48 minutes                                k8s_dd-agent.681a0d7e_dd-agent-node3_default_93df18fd6f185f45b26686365f51291c_ae925d1b
c7a12d891eba        gcr.io/google_containers/exechealthz:1.0       "/exechealthz '-cmd=n"   48 minutes ago      Up 48 minutes                                k8s_healthz.c34509c2_dd-agent-node3_default_93df18fd6f185f45b26686365f51291c_9c091662
b0ed112ca94e        gcr.io/google_containers/hyperkube:v1.3.3      "/bin/sh -c '/hyperku"   48 minutes ago      Up 48 minutes                                k8s_kube-proxy.204446a5_kube-proxy-node3_default_220120ac36df4e8bbd6c590d2413b27f_5a08d4aa
3c1f7755b99c        gcr.io/google_containers/pause-amd64:3.0       "/pause"                 48 minutes ago      Up 48 minutes                                k8s_POD.d8dbe16c_kube-proxy-node3_default_220120ac36df4e8bbd6c590d2413b27f_38c7087b
9a35b57fdbdf        gcr.io/google_containers/pause-amd64:3.0       "/pause"                 48 minutes ago      Up 48 minutes       0.0.0.0:8125->8125/udp   k8s_POD.b0a42b27_dd-agent-node3_default_93df18fd6f185f45b26686365f51291c_6eada28c
core@node3 ~ $ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "2b2d3e4c2927c6d7b509cbede697101dfd86378ce8340bfbbc5133b31098c979",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.35.1/24",
                    "Gateway": "172.16.35.1"
                }
            ]
        },
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1450"
        }
    }
]
```

Then starting a couple containers to get some duplicate IP addresses:
```
core@node3 ~ $ docker run --name thing3 -d docker.place/iaas/gogo
7ea0cabdb4017f2955e123e91621ca163c7031c6966c4d3745baa0db71177c39
core@node3 ~ $ docker run --name thing4 -d docker.place/iaas/gogo
3f68284ff76b7540a75c97e8edf1d6437d85bd4b83c1906968a15f27de562b69
core@node3 ~ $ docker ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED              STATUS              PORTS                    NAMES
3f68284ff76b        docker.place/iaas/gogo           "nginx -g 'daemon off"   5 seconds ago        Up 1 seconds        80/tcp, 443/tcp          thing4
7ea0cabdb401        docker.place/iaas/gogo           "nginx -g 'daemon off"   13 seconds ago       Up 10 seconds       80/tcp, 443/tcp          thing3
1b96d01845e9        docker.place/iaas/gogo           "nginx -g 'daemon off"   About a minute ago   Up About a minute   80/tcp, 443/tcp          thing2
bc16f754120d        docker.place/iaas/gogo           "nginx -g 'daemon off"   About a minute ago   Up About a minute   80/tcp, 443/tcp          thing1
09748d8f106e        docker.io/datadog/docker-dd-agent:kubernetes   "/entrypoint.sh super"   48 minutes ago       Up 48 minutes                                k8s_dd-agent.681a0d7e_dd-agent-node3_default_93df18fd6f185f45b26686365f51291c_ae925d1b
c7a12d891eba        gcr.io/google_containers/exechealthz:1.0       "/exechealthz '-cmd=n"   49 minutes ago       Up 49 minutes                                k8s_healthz.c34509c2_dd-agent-node3_default_93df18fd6f185f45b26686365f51291c_9c091662
b0ed112ca94e        gcr.io/google_containers/hyperkube:v1.3.3      "/bin/sh -c '/hyperku"   49 minutes ago       Up 49 minutes                                k8s_kube-proxy.204446a5_kube-proxy-node3_default_220120ac36df4e8bbd6c590d2413b27f_5a08d4aa
3c1f7755b99c        gcr.io/google_containers/pause-amd64:3.0       "/pause"                 49 minutes ago       Up 49 minutes                                k8s_POD.d8dbe16c_kube-proxy-node3_default_220120ac36df4e8bbd6c590d2413b27f_38c7087b
9a35b57fdbdf        gcr.io/google_containers/pause-amd64:3.0       "/pause"                 49 minutes ago       Up 49 minutes       0.0.0.0:8125->8125/udp   k8s_POD.b0a42b27_dd-agent-node3_default_93df18fd6f185f45b26686365f51291c_6eada28c
core@node3 ~ $ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "2b2d3e4c2927c6d7b509cbede697101dfd86378ce8340bfbbc5133b31098c979",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.35.1/24",
                    "Gateway": "172.16.35.1"
                }
            ]
        },
        "Containers": {
            "3f68284ff76b7540a75c97e8edf1d6437d85bd4b83c1906968a15f27de562b69": {
                "Name": "thing4",
                "EndpointID": "5d00bee93fdff2d3a280a871372793e6785786a79b0c6a37e1419b270b3b921b",
                "MacAddress": "02:42:ac:10:23:03",
                "IPv4Address": "172.16.35.3/24",
                "IPv6Address": ""
            },
            "7ea0cabdb4017f2955e123e91621ca163c7031c6966c4d3745baa0db71177c39": {
                "Name": "thing3",
                "EndpointID": "b3d056a3a65cc2e655b58a2819e7c90ea14c31536740e069576e58205796262b",
                "MacAddress": "02:42:ac:10:23:02",
                "IPv4Address": "172.16.35.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1450"
        }
    }
]
```

An example of one of the conflicts:
```
core@node3 ~ $ docker inspect 3f68284ff76b|grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "172.16.35.3",
                    "IPAddress": "172.16.35.3",
core@node3 ~ $ docker inspect bc16f754120d|grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "172.16.35.3",
                    "IPAddress": "172.16.35.3",
core@node3 ~ $
```

**Comment by aboch** [comment] 2016-10-17 18:24
Thanks @dpeters for the extra logs.
Which options are you passing when you strat/restart  the daemon (`--live-restore` ?), how do you start the containers (restart policy, ...)

**Comment by aboch** [comment] 2016-10-17 18:27
At first glance, the issue seems that at restart somehow libnetwork is not programmed for the running containers, or that the containers are not supposed to be running.

**Comment by aboch** [comment] 2016-10-17 18:56
@dpeters I see from your logs the containers are not started with any restart policy.
Still, can you please let us know if the daemon is started with the `--live-restore` flag.
Also, do you see any error/warning in the daemon logs.
Just to make sure, you are running only one daemon on the host?

**Comment by dpeters** [comment] 2016-10-18 22:12
@aboch - We do pass --live-restore to the daemon:

```
$ ps -ef|grep dockerd
root     18377     1  4 Oct17 ?        01:22:16 /opt/bin/dockerd --live-restore --storage-driver=overlay --iptables=false --log-driver=journald --bip=172.16.35.1/24 --ip-masq=false --mtu=1450
core     33545 33283  0 22:06 pts/0    00:00:00 grep --colour=auto dockerd
$
```

I didn't notice any errors, but will rerun the tests, and validate this.


There is another docker daemon running, using a different socket, and a different binary (1.10.3 bundled with coreos):
```
$ ps -ef|grep early
root      1135     1  0 Oct17 ?        00:04:02 docker daemon --host=fd:// --bridge=none --iptables=false --ip-masq=false --graph=/var/lib/early-docker --pidfile=/var/run/early-docker.pid --exec-opt native.cgroupdriver=systemd --selinux-enabled
core     33827 33283  0 22:09 pts/0    00:00:00 grep --colour=auto early
$
```

**Comment by aboch** [comment] 2016-10-19 00:47
Thanks @dpeters for the extra info.
I have not been able to reproduce yet.
If you get a chance to try the test again, can you check if it makes a difference if you have only one daemon running. Thanks.

**Comment by aboch** [comment] 2016-10-28 17:58
ping @dpeters

**Comment by jeanpralo** [comment] 2016-11-11 02:09
We have seen this happening in production with docker 1.12.1, unfortunately so far unable to reproduce. We run only one docker daemon per server and no live-restore is enabled.

Will keep trying and monitor the situation and feed that ticket if we find anything else.

**Comment by aboch** [comment] 2016-11-17 17:27
This issue is about libnetwork not being informed about running containers at docker boot in a `--live-restore=true` context. On docker 1.12.0.

Please do comments here only if your issue happens in the same context above.

Current suspicious are about this happening because of a second daemon running, and submitter was asked to check if he can reproduce with only one daemon.

@dpeters final ping

**Comment by dpeters** [comment] 2016-11-17 21:07
@aboch - Sorry about the silence for so long on this. It's still occurring for us, and I haven't had the chance to attempt anything with it until now.

While testing out a few things today, I found that on systems where we are running a newer CoreOS release, with docker 1.12 by default, we do not see this issue. On older releases with 1.11.x, we add a 1.12.x binary and modify the systemd unit to use it, and that is where we see this issue. At this point I believe the issue is likely in how we're configuring the systemd unit, and will look into that a bit more...

On the older CoreOS release, I was able to duplicate the issue with only a single 1.12 daemon running:

Ensure only one daemon is running:
```
# ps -ef|grep docker
root     18308 17407  0 20:43 pts/0    00:00:00 grep --colour=auto docker
# systemctl start docker.service
# ps -ef|grep docker
root     18322     1  0 20:43 ?        00:00:00 /opt/bin/dockerd --live-restore --storage-driver=overlay --iptables=false --log-driver=journald --bip=172.16.50.1/24 --ip-masq=false --mtu=8951
root     18342 18322  0 20:43 ?        00:00:00 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc
root     18378 17407  0 20:43 pts/0    00:00:00 grep --colour=auto docker
# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
#
```

Start a few containers, and check the bridge:
```
# docker run -d nginx
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
386a066cd84a: Pull complete
7bdb4b002d7f: Pull complete
49b006ddea70: Pull complete
Digest: sha256:9038d5645fa5fcca445d12e1b8979c87f46ca42cfb17beb1e5e093785991a639
Status: Downloaded newer image for nginx:latest
ce24b81ff5985f291b088568139ad46f3d9606a0a54b2814625ec6650d671406
# docker run -d nginx
32f8b0ccc5a66338eda4abf4b5e2a32b6e690267fe23087be386a35a8f8f8802
# docker run -d nginx
2526320c57af16481345413b4512d61e7f58fa04405c2f60ba8443bdb86ebe7d
# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
2526320c57af        nginx               "nginx -g 'daemon off"   2 seconds ago       Up 1 seconds        80/tcp, 443/tcp     berserk_payne
32f8b0ccc5a6        nginx               "nginx -g 'daemon off"   3 seconds ago       Up 2 seconds        80/tcp, 443/tcp     drunk_stonebraker
ce24b81ff598        nginx               "nginx -g 'daemon off"   7 seconds ago       Up 6 seconds        80/tcp, 443/tcp     naughty_meninsky
# docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "a77abb56e2f6a829bfc009e96417a6f2da4b20d2fa94ededd5093b0a271ca196",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.50.1/24",
                    "Gateway": "172.16.50.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "2526320c57af16481345413b4512d61e7f58fa04405c2f60ba8443bdb86ebe7d": {
                "Name": "berserk_payne",
                "EndpointID": "114fe73c8ae9d17a86e8ec9d575374a57fbf33d429b990b8e4119ed79ceeeda1",
                "MacAddress": "02:42:ac:10:32:04",
                "IPv4Address": "172.16.50.4/24",
                "IPv6Address": ""
            },
            "32f8b0ccc5a66338eda4abf4b5e2a32b6e690267fe23087be386a35a8f8f8802": {
                "Name": "drunk_stonebraker",
                "EndpointID": "fab1a9ca49b2c1e86ae1ea43da106cf411b943274e4bff9d51012a4391e4e6f1",
                "MacAddress": "02:42:ac:10:32:03",
                "IPv4Address": "172.16.50.3/24",
                "IPv6Address": ""
            },
            "ce24b81ff5985f291b088568139ad46f3d9606a0a54b2814625ec6650d671406": {
                "Name": "naughty_meninsky",
                "EndpointID": "19828fcdfd037b45337d5e9f38615e71582e3522372441dbb46e4564384ab2cd",
                "MacAddress": "02:42:ac:10:32:02",
                "IPv4Address": "172.16.50.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "8951"
        },
        "Labels": {}
    }
]
#
```

Restart the daemon, see the containers, and re-check the bridge (and see the entries missing):
```
# systemctl restart docker.service
# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
2526320c57af        nginx               "nginx -g 'daemon off"   About a minute ago   Up About a minute   80/tcp, 443/tcp     berserk_payne
32f8b0ccc5a6        nginx               "nginx -g 'daemon off"   About a minute ago   Up About a minute   80/tcp, 443/tcp     drunk_stonebraker
ce24b81ff598        nginx               "nginx -g 'daemon off"   2 minutes ago        Up About a minute   80/tcp, 443/tcp     naughty_meninsky
# docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "a77abb56e2f6a829bfc009e96417a6f2da4b20d2fa94ededd5093b0a271ca196",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.50.1/24",
                    "Gateway": "172.16.50.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "8951"
        },
        "Labels": {}
    }
]
#
```

Start a few more containers and see the IPs get re-used:
```
# docker run -d nginx
f68adbf7cbe55c1380606921a2bfe33b9509e1b0564b28447fd3524e42705408
# docker run -d nginx
bf19799644ab454367480bb3b41e4e1c1a54896d568d341e054e55637071ba69
# docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "a77abb56e2f6a829bfc009e96417a6f2da4b20d2fa94ededd5093b0a271ca196",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.50.1/24",
                    "Gateway": "172.16.50.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "bf19799644ab454367480bb3b41e4e1c1a54896d568d341e054e55637071ba69": {
                "Name": "evil_hamilton",
                "EndpointID": "fbf0acc6a1555904c83c0ec02cc66cf5fef6fbdff1a2bef11d69fe4a0354a3f0",
                "MacAddress": "02:42:ac:10:32:03",
                "IPv4Address": "172.16.50.3/24",
                "IPv6Address": ""
            },
            "f68adbf7cbe55c1380606921a2bfe33b9509e1b0564b28447fd3524e42705408": {
                "Name": "reverent_sinoussi",
                "EndpointID": "e09601de479f800b98e97e5148d6ad6adda6eddb8d5f7895213ec418e452f4d2",
                "MacAddress": "02:42:ac:10:32:02",
                "IPv4Address": "172.16.50.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "false",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "8951"
        },
        "Labels": {}
    }
]
#
```

**Comment by aboch** [comment] 2016-11-18 18:58
Thanks @dpeters for the extra triage, that helps.

> On older [CoreOs] releases with 1.11.x, we add a 1.12.x binary and modify the systemd unit to use it, and that is where we see this issue.  At this point I believe the issue is likely in how we're configuring the systemd unit, and will look into that a bit more...

Based on the above let's still keep this issue open, so that you can update after your future experiments, for the sake of others who may have performed similar steps.

From my side one extra log it would be nice to collect and check in the 1.11.x=>1.12.x updated use case, is to start the daemon with the `-D` flag and attach them here if the issue is hit.

Thanks!

**Comment by mavenugo** [comment] 2016-11-28 21:06
Closing this based on the extra info. Please feel free to re-open if a genuine issue is identified.

**Closed by mavenugo** 2016-11-28 21:06 UTC
Labels: area/networking, status/more-info-needed

**Comment by David-Crty** [comment] 2016-12-20 22:59
We are having the same issue here (production server) after a reboot.
Now i have two containers that are always taking the same ip all the time.
I'm obligated to put them in two different network...

Pleas re-open this i'm on Ubuntu 16.04. I can give log.

**Comment by thaJeztah** [comment] 2016-12-20 23:13
@David-Crty can you open a new issue with more information about your situation (see the bug report template); this thread is already quite lengthy, may be better to start fresh, but please add a link to this issue for reference

**Comment by dmrub** [comment] 2017-06-30 22:35
I have this issue (duplicate IPs after restarting docker daemon) on CentOS 7.3.1611,

live-restore option is enabled:
```
# cat /etc/docker/daemon.json:
{
    "live-restore": true
}
```
```
# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-28.git1398f24.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      1398f24/1.12.6
 Built:           Fri May 26 17:28:18 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-28.git1398f24.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      1398f24/1.12.6
 Built:           Fri May 26 17:28:18 2017
 OS/Arch:         linux/amd64
```
