### ISSUE TITLE
Docker compatibility with Debian Jessie (8.5)

### ISSUE THREAD

**Issue by dbareiro** [docker/docker#24453] opened 2016-07-08 16:41 UTC
Dear Docker team,

I am trying to install Docker Engine 1.11 on Debian GNU/Linux Jessie (8.5). From what I read in the documentation [1], Debian Jessie is a supported distribution. However, I am having some problems installing:

```
# aptitude install docker-engine
The following NEW packages will be installed:
  aufs-tools{a} cgroupfs-mount{a} docker-engine libnih-dbus1{a} libnih1{a} mountall{a} plymouth{a} 
0 packages upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/14.8 MB of archives. After unpacking 74.1 MB will be used.
Do you want to continue? [Y/n/?] Y
Selecting previously unselected package plymouth.
(Reading database ... 177196 files and directories currently installed.)
Preparing to unpack .../plymouth_0.9.0-9_amd64.deb ...
Unpacking plymouth (0.9.0-9) ...
Selecting previously unselected package libnih1.
Preparing to unpack .../libnih1_1.0.3-4.3_amd64.deb ...
Unpacking libnih1 (1.0.3-4.3) ...
Selecting previously unselected package libnih-dbus1.
Preparing to unpack .../libnih-dbus1_1.0.3-4.3_amd64.deb ...
Unpacking libnih-dbus1 (1.0.3-4.3) ...
Selecting previously unselected package mountall.
Preparing to unpack .../mountall_2.54_amd64.deb ...
Unpacking mountall (2.54) ...
Selecting previously unselected package aufs-tools.
Preparing to unpack .../aufs-tools_1%3a3.2+20130722-1.1_amd64.deb ...
Unpacking aufs-tools (1:3.2+20130722-1.1) ...
Selecting previously unselected package cgroupfs-mount.
Preparing to unpack .../cgroupfs-mount_1.1_all.deb ...
Unpacking cgroupfs-mount (1.1) ...
Selecting previously unselected package docker-engine.
Preparing to unpack .../docker-engine_1.11.2-0~jessie_amd64.deb ...
Unpacking docker-engine (1.11.2-0~jessie) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u4) ...
Processing triggers for dbus (1.8.20-0+deb8u1) ...
Setting up plymouth (0.9.0-9) ...
update-initramfs: deferring update (trigger activated)
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Setting up libnih1 (1.0.3-4.3) ...
Setting up libnih-dbus1 (1.0.3-4.3) ...
Setting up mountall (2.54) ...
Setting up aufs-tools (1:3.2+20130722-1.1) ...
Setting up cgroupfs-mount (1.1) ...
Setting up docker-engine (1.11.2-0~jessie) ...
Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-engine (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for initramfs-tools (0.120+deb8u2) ...
update-initramfs: Generating /boot/initrd.img-3.16.0-4-amd64
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for systemd (215-17+deb8u4) ...
Errors were encountered while processing:
 docker-engine
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to perform requested operation on package.  Trying to recover:
Setting up docker-engine (1.11.2-0~jessie) ...
Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-engine (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 docker-engine
```

Checking the syslog, I think this is because the version of Debian Jessie for Systemd does not support the "Delegate" option used in the Unit that brings the package.

```
Jul  8 13:33:08 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:08 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:08 orion docker[20716]: time="2016-07-08T13:33:08.607373846-03:00" level=info msg="New containerd process, pid: 20721\n"
Jul  8 13:33:09 orion docker[20716]: time="2016-07-08T13:33:09.614783897-03:00" level=info msg="[graphdriver] using prior storage driver \"aufs\""
Jul  8 13:33:09 orion docker[20716]: time="2016-07-08T13:33:09.654605062-03:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul  8 13:33:09 orion docker[20716]: time="2016-07-08T13:33:09.663921318-03:00" level=info msg="Firewalld running: false"
Jul  8 13:33:09 orion docker[20716]: time="2016-07-08T13:33:09.755517105-03:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: failed to parse pool request for address space \"LocalDefault\" pool \"\" subpool \"\": could not find an available predefined network"
Jul  8 13:33:09 orion systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul  8 13:33:09 orion docker[20716]: time="2016-07-08T13:33:09-03:00" level=info msg="stopping containerd after receiving terminated"
Jul  8 13:33:09 orion systemd[1]: Unit docker.service entered failed state.
Jul  8 13:33:11 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:11 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:11 orion docker[20833]: time="2016-07-08T13:33:11.362902918-03:00" level=info msg="New containerd process, pid: 20838\n"
Jul  8 13:33:12 orion docker[20833]: time="2016-07-08T13:33:12.367640712-03:00" level=info msg="[graphdriver] using prior storage driver \"aufs\""
Jul  8 13:33:12 orion docker[20833]: time="2016-07-08T13:33:12.412478036-03:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul  8 13:33:12 orion docker[20833]: time="2016-07-08T13:33:12.416935483-03:00" level=info msg="Firewalld running: false"
Jul  8 13:33:12 orion docker[20833]: time="2016-07-08T13:33:12.482378152-03:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: failed to parse pool request for address space \"LocalDefault\" pool \"\" subpool \"\": could not find an available predefined network"
Jul  8 13:33:12 orion systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul  8 13:33:12 orion docker[20833]: time="2016-07-08T13:33:12-03:00" level=info msg="stopping containerd after receiving terminated"
Jul  8 13:33:12 orion systemd[1]: Unit docker.service entered failed state.
Jul  8 13:33:24 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:24 orion systemd[1]: Cannot add dependency job for unit docker.socket, ignoring: Unit docker.socket failed to load: No such file or directory.
Jul  8 13:33:54 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:55 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:55 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:58 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:58 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:59 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:59 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:59 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:59 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:33:59 orion docker[27108]: time="2016-07-08T13:33:59.565988487-03:00" level=info msg="New containerd process, pid: 27113\n"
Jul  8 13:34:00 orion docker[27108]: time="2016-07-08T13:34:00.573373728-03:00" level=info msg="[graphdriver] using prior storage driver \"aufs\""
Jul  8 13:34:00 orion docker[27108]: time="2016-07-08T13:34:00.611489695-03:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul  8 13:34:00 orion docker[27108]: time="2016-07-08T13:34:00.620256969-03:00" level=info msg="Firewalld running: false"
Jul  8 13:34:00 orion docker[27108]: time="2016-07-08T13:34:00.712048816-03:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: failed to parse pool request for address space \"LocalDefault\" pool \"\" subpool \"\": could not find an available predefined network"
Jul  8 13:34:00 orion systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul  8 13:34:00 orion docker[27108]: time="2016-07-08T13:34:00-03:00" level=info msg="stopping containerd after receiving terminated"
Jul  8 13:34:00 orion systemd[1]: Unit docker.service entered failed state.
Jul  8 13:34:08 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:34:10 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:34:10 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  8 13:34:10 orion docker[31336]: time="2016-07-08T13:34:10.231196129-03:00" level=info msg="New containerd process, pid: 31341\n"
Jul  8 13:34:11 orion docker[31336]: time="2016-07-08T13:34:11.237789729-03:00" level=info msg="[graphdriver] using prior storage driver \"aufs\""
Jul  8 13:34:11 orion docker[31336]: time="2016-07-08T13:34:11.260716164-03:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul  8 13:34:11 orion docker[31336]: time="2016-07-08T13:34:11.267884687-03:00" level=info msg="Firewalld running: false"
Jul  8 13:34:11 orion docker[31336]: time="2016-07-08T13:34:11.333223225-03:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: failed to parse pool request for address space \"LocalDefault\" pool \"\" subpool \"\": could not find an available predefined network"
Jul  8 13:34:11 orion systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul  8 13:34:11 orion docker[31336]: time="2016-07-08T13:34:11-03:00" level=info msg="stopping containerd after receiving terminated"
Jul  8 13:34:11 orion systemd[1]: Unit docker.service entered failed state.
```

Kindly confirm.

Thanks in advance.

Kind regards,
Daniel

[1] https://docs.docker.com/v1.11/engine/installation/linux/debian/

**Comment by thaJeztah** [comment] 2016-07-08 23:57
The "Delegate" warning is (afaik) just a warning, the actual error is:

```
Error initializing network controller: Error creating default \"bridge\" network: failed to parse pool request for address space \"LocalDefault\" pool \"\" subpool \"\": could not find an available predefined network"
```

Which is a duplicate of https://github.com/docker/docker/issues/22204 and https://github.com/docker/docker/issues/21170

For Jessie, also make sure to have kernel 3.10 or higher installed, because docker won't run on lower versions

I'm closing this issue because I think it's a duplicate, but feel free to comment after I closed

**Closed by thaJeztah** 2016-07-08 23:57 UTC

**Comment by dbareiro** [comment] 2016-07-09 13:55
Hi, Sebastiaan.

Here I am using Linux 3.16 from Debian standard repositories.

Thanks for your reply and references.

Yes, it seems that this has to do with the network configuration. In this notebook where I am trying to install Docker I had at that time an active OpenVPN connection. It seems that this issue was mentioned in [#779 for libnetwork](https://github.com/docker/libnetwork/issues/779).

A workaround was: stop OpenVPN, install Docker, start OpenVPN (*)

Curiously, may think that if I uninstall Docker while the VPN is active and then I install it again, I should have the same problem; but it was not the case. It seems that once having performed the procedure referred in (*), it was sufficient. Do you know why can this be?

On the other hand, I rechecked the syslog:

```
# grep docker /var/log/syslog
Jul  9 09:06:55 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  9 09:06:55 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  9 09:06:55 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  9 09:06:55 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  9 09:06:55 orion docker[18248]: time="2016-07-09T09:06:55.898384570-03:00" level=info msg="New containerd process, pid: 18253\n"
Jul  9 09:06:56 orion docker[18248]: time="2016-07-09T09:06:56.906426875-03:00" level=info msg="[graphdriver] using prior storage driver \"aufs\""
Jul  9 09:06:56 orion docker[18248]: time="2016-07-09T09:06:56.963054171-03:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul  9 09:06:56 orion docker[18248]: time="2016-07-09T09:06:56.973795286-03:00" level=info msg="Firewalld running: false"
Jul  9 09:06:57 orion docker[18248]: time="2016-07-09T09:06:57.199871766-03:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Jul  9 09:06:57 orion docker[18248]: time="2016-07-09T09:06:57.361765943-03:00" level=warning msg="Your kernel does not support cgroup memory limit"
Jul  9 09:06:57 orion docker[18248]: time="2016-07-09T09:06:57.361826389-03:00" level=warning msg="Your kernel does not support cgroup cfs period"
Jul  9 09:06:57 orion docker[18248]: time="2016-07-09T09:06:57.361849359-03:00" level=warning msg="Your kernel does not support cgroup cfs quotas"
Jul  9 09:06:57 orion docker[18248]: time="2016-07-09T09:06:57.362083818-03:00" level=warning msg="mountpoint for pids not found"
Jul  9 09:06:57 orion docker[18248]: time="2016-07-09T09:06:57.362585153-03:00" level=info msg="Loading containers: start."
Jul  9 09:06:57 orion docker[18248]: time="2016-07-09T09:06:57.362654336-03:00" level=info msg="Loading containers: done."
Jul  9 09:06:57 orion docker[18248]: time="2016-07-09T09:06:57.362671858-03:00" level=info msg="Daemon has completed initialization"
Jul  9 09:06:57 orion docker[18248]: time="2016-07-09T09:06:57.362750229-03:00" level=info msg="Docker daemon" commit=b9f10c9 graphdriver=aufs version=1.11.2
Jul  9 09:06:57 orion docker[18248]: time="2016-07-09T09:06:57.383146130-03:00" level=info msg="API listen on /var/run/docker.sock"
Jul  9 09:07:04 orion systemd[1]: [/lib/systemd/system/docker.service:19] Unknown lvalue 'Delegate' in section 'Service'
Jul  9 09:08:26 orion kernel: [1121922.054721] aufs au_opts_verify:1570:docker[18265]: dirperm1 breaks the protection by the permission bits on the lower branch
```
Do you think the messages about "Delegate" of systemd has to do with the three warnings for cgroups (memory limit / cfs period / cfs quotas)?

In addition ```docker info``` shows other warnings:

```
# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.524 GiB
Name: orion
ID: CG3E:U4KT:WT7F:275W:RAON:PN56:SMVY:KI3N:5R36:JDCO:W4CE:NT5V
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

Do you think this or the following messages could bring any problems when create containers?

```
Jul  9 09:06:57 orion docker[18248]: time="2016-07-09T09:06:57.362083818-03:00" level=warning msg="mountpoint for pids not found"
(...)
Jul  9 09:08:26 orion kernel: [1121922.054721] aufs au_opts_verify:1570:docker[18265]: dirperm1 breaks the protection by the permission bits on the lower branch
```
Thanks for your time.

Kind regards,
Daniel
