### ISSUE TITLE
[Feature Request] Not enough options for `docker build` 

### ISSUE THREAD

**Issue by zaufi** [docker/docker#31025] opened 2017-02-15 01:38 UTC
I'm trying to build a docker image (Gentoo) using `docker build`, and found that there is no way to pass additional options which is possible to pass to `create` or `run`... Particularly it is vital to add `--cap-add=` (otherwise [glibc won't build in Gentoo](https://forums.gentoo.org/viewtopic-t-1035728-start-0.html)).

**Comment by cpuguy83** [comment] 2017-02-15 01:40
Closing since this is a dup of #1916 (and sorry yes, the issue is very old!)

**Closed by cpuguy83** 2017-02-15 01:40 UTC
Labels: area/builder
