### ISSUE TITLE
Confusing `docker system prune` interaction

### ISSUE THREAD

**Issue by elibarzilay** [docker/docker#32234] opened 2017-03-30 19:58 UTC
The prompt for `docker system prune` says `[y/N]` which seems like it's
saying "`N` is the default", but if I just hit enter, nothing happens.
Yes, I then guessed that it's waiting for some non-whitespace character
and if it's not "y" then it aborts.

This is unlike the usual way such prompts are implemented, where hitting
enter is the same as entering the default ("n" in this case).

**Comment by ffoysal** [comment] 2017-03-31 02:48
I was trying to reproduce in my development container but no luck. It happens in my host though. any ideas how to reproduce it development container.

**Comment by vdemeester** [comment] 2017-03-31 09:31
@ffoysal it seems to be fixed in recent version : i.e. starting from 17.04.0 👼 (rc2 currently, soon to be released 😉)

**Comment by thaJeztah** [comment] 2017-03-31 09:34
Yes this is fixed by https://github.com/docker/docker/pull/30769, which will be in 17.04 (if you're on "edge") or 17.06 (if you're on the "stable" channel)

**Closed** 2017-03-31 09:33 UTC
Labels: area/cli, kind/enhancement
