### ISSUE TITLE
[Question] Can I clear logs in `docker logs`?

### ISSUE THREAD

**Issue by gyliu513** [docker/docker#24998] opened 2016-07-25 08:16 UTC
**Output of `docker version`:**

```
root@kvm-002605:~# docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
 
Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@kvm-002605:~# docker info
Containers: 17
 Running: 11
 Paused: 0
 Stopped: 6
Images: 15
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 165
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.42 GiB
Name: kvm-002605
ID: Q4FJ:W4OR:UCQG:YN4X:6DKC:IYBU:BWHF:ET4B:SUIY:YXLU:TL6E:HMXK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Http Proxy: http://9.21.62.135:8123/
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Start up a container
2. The container run a long time
3. `docker logs` will print out quite a lot of logs and it is difficult to find the log that I was interested in even with grep.

**Describe the results you received:**
Does there are some ways to clear `docker logs`?

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-07-25 12:38
No, there's no way to *clear* the logs (at least, not without manually truncating the files), but you can set `--log-opt max-file=...` and `--log-opt max-size=...` options for a container to make it rotate logs (see https://docs.docker.com/engine/admin/logging/overview/#/json-file-options)

Also, you can `--tail=...` to get only the latest `n` lines from a container's logs, for example;

```
docker logs --tail=500 my-container
```

only shows the latest 500 log entries for the `my-container` container

I'm closing this issue, because this is not a bug, but a question, but feel free to continue the conversation here

**Closed by thaJeztah** 2016-07-25 12:38 UTC
Labels: version/1.11

**Comment by gyliu513** [comment] 2016-07-25 13:40
Thanks @thaJeztah , very clear! You are always trying to answer my question at first time, really appreciated!

**Comment by thaJeztah** [comment] 2016-07-25 14:26
@gyliu513 you're welcome, glad I could help!

**Comment by milewski** [comment] 2018-07-24 09:07
@thaJeztah 2018 your answer still up to date? has any new options emerged since then?

**Comment by adnapster** [comment] 2018-09-11 05:00
@thaJeztah Is there any way available to clean up the log of docker container without stopping the container

**Comment by thaJeztah** [comment] 2018-09-11 12:44
No; no such option; best to configure the max-file / max-size options when creating containers

**Comment by lassaadbaati** [comment] 2019-09-29 06:32
Hi, 
If I remove the json log file manually, is it safety, or it will impact the docker processes ?
thanks
