### ISSUE TITLE
failed to create container with device mapper

### ISSUE THREAD

**Issue by helenxu1221** [docker/docker#10413] opened 2015-01-28 15:35 UTC
I have docker 1.5.0 rc1 installed with logic volume as the storage. "--storage-opt dm.datadev=/dev/direct-lvm/data --storage-opt dm.metadatadev=/dev/direct-lvm/metadata" . I created a script which starts 10 containers in a roll with this command "docker run -d -i -t busybox /bin/sh"

I got the following error for two containers out of ten

FATA[0000] Error response from daemon: Cannot start container 60420bd54729a8ed7b0ec066889b8bb3a3c2fdabfbb38b90ca2520862bf3672d: Error getting container 60420bd54729a8ed7b0ec066889b8bb3a3c2fdabfbb38b90ca2520862bf3672d from driver devicemapper: Error mounting '/dev/mapper/docker-202:2-4072516-60420bd54729a8ed7b0ec066889b8bb3a3c2fdabfbb38b90ca2520862bf3672d' on '/var/lib/docker/devicemapper/mnt/60420bd54729a8ed7b0ec066889b8bb3a3c2fdabfbb38b90ca2520862bf3672d': no such file or directory

this problem also happened on docker 1.4.1

**Comment by unclejack** [comment] 2015-01-29 06:32
This is an exact duplicate of #4036.

I'm going to close and lock this issue so that the discussion continues on #4036. We're seeing a lot of duplicates for this issue and it makes keeping track of new devicemapper related issues difficult. That's why I'm locking it as well.

Please comment on #4036 if you get the "no such file or directory" error with devicemapper.

**Closed by unclejack** 2015-01-29 06:32 UTC
Labels: /system/devicemapper
