### ISSUE TITLE
[1.12-rc3] tasks fail with "Address already in use"

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#24553] opened 2016-07-12 20:26 UTC
After running several services, on the same port, tasks start failing with `"Err": "starting container failed: Address already in use"`.

I am able to reproduce on this on 1.12-rc3 on Docker for Mac with the following:

1. Start a service with several instances.
2. Put the laptop to sleep.
3. Kick off an update -> tasks fail with described error.

Services will not run again until completely resetting the docker instance.

The following appears in the logs around the time tasks start failing:

```
time="2016-07-12T20:21:45Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.4.14-moby`, error: exit status 1"
```

It is not clear that this is related.

cc @mavenugo @mrjana @thaJeztah @mgoelzer

**Comment by thaJeztah** [comment] 2016-07-12 20:29
ping @justincormack in case this is related to piñata

**Comment by rneugeba** [comment] 2016-07-12 20:30
could you upload the diagnostics and let us know the diagnostic ID (Whale menu -> Diagnosis and Feedback -> Upload diagnostics)

**Comment by abronan** [comment] 2016-07-12 21:01
FYI this seems to be a duplicate of #24486

Or at least related.

**Comment by justincormack** [comment] 2016-07-12 21:07
The modprobe warning is unrelated

**Comment by mavenugo** [comment] 2016-07-12 21:34
Yes. the modprobe is unrelated to the issue. But I do think it is a dupe of #24486

**Comment by thaJeztah** [comment] 2016-07-12 21:38
@stevvooe let me close this issue in favor of #24486, which also contains additional information. I'll copy the labels to that issue

**Closed by thaJeztah** 2016-07-12 21:38 UTC
Labels: area/swarm, group/networking, kind/bug, priority/P2
