### ISSUE TITLE
docker image can't find when i restart my pc

### ISSUE THREAD

**Issue by 625096233** [docker/docker#26126] opened 2016-08-30 01:19 UTC
dear everyone:
           my pc is window10 ,when i restart my pc, i run the ( Docker Quickstart Terminal) then Kitematic (Alpha),  last when i run docker images,there nothing,but before there has ,such su zookeep,redis ....and so on

**Comment by unclejack** [comment] 2016-09-01 08:20
Can you provide the output of `docker info` and the version of the Docker for windows app, please?

**Comment by 625096233** [comment] 2016-09-02 00:57
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: RZTS:J7SC:3FIH:27N7:QPUI:XJER:MYR5:4QQJ:NR6G:KSMO:FJWL:BBOI
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2016-09-01T08:25:25.865668761Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

**Comment by 625096233** [comment] 2016-09-02 00:57
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: RZTS:J7SC:3FIH:27N7:QPUI:XJER:MYR5:4QQJ:NR6G:KSMO:FJWL:BBOI
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2016-09-01T08:25:25.865668761Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

**Comment by thaJeztah** [comment] 2016-10-29 07:37
Based on these symptoms, I suspect that upgrading Docker Toolbox created a new Virtual Machine, causing your old images to disappear. This is not a bug in docker (engine), but if you're still running into this, please open an issue in the Docker Toolbox issue tracker https://github.com/docker/toolbox/issues

I'll close this issue here, but feel free to comment

**Closed by thaJeztah** 2016-10-29 07:37 UTC
Labels: status/more-info-needed
