### ISSUE TITLE
Not able to delete the service named 'help' or 'create' in Docker swarm mode although you can create the service with those names. 

### ISSUE THREAD

**Issue by junaid18183** [docker/docker#24833] opened 2016-07-20 09:50 UTC
**Output of `docker version`:**

```
[root@tiber ~]# docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
[root@tiber ~]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 19
Server Version: 1.12.0-rc4
Storage Driver: devicemapper
 Pool Name: docker-253:0-3139777-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.652 GB
 Data Space Total: 107.4 GB
 Data Space Available: 38.89 GB
 Metadata Space Used: 2.462 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: active
 NodeID: bk6rbuivjcyjoznspi29cegyt
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:ce71b541ba8f63588d1e4ed5d2b89ef95f9c377b29b8bf12f9261fdcdba4db70
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.5 GiB
Name: tiber
ID: DPJN:5LZA:JAV3:HKEZ:4LGN:VWSI:C2UW:7PGR:JPWI:P4YA:LMS7:UVWZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on Physical Box on Centos 7

**Steps to reproduce the issue:**
1. Create the service named help or create ( I accidentally created it ) 
2. Confirm that the service are created. 
3. Try to delete the service using name ( help/create ) it wont work. The only way to get rid of them is use their ID to delete them.

**Describe the results you received:**
[root@tiber ~]# docker service create help
bzbf6n87g7bv4ndvjv2ek43nm
[root@tiber ~]# docker service create create
dltuxz5rlkwhdnx2ct264bp8l
[root@tiber ~]# docker service ls
ID            NAME                REPLICAS  IMAGE   COMMAND
bzbf6n87g7bv  jolly_bell          0/1       help
dltuxz5rlkwh  backstabbing_jones  0/1       create
[root@tiber ~]# docker service rm help
Error response from daemon: service help not found
[root@tiber ~]# docker service rm create
Error response from daemon: service create not found
[root@tiber ~]# docker service rm bzbf6n87g7bv
bzbf6n87g7bv
[root@tiber ~]# docker service rm dltuxz5rlkwh
dltuxz5rlkwh

**Describe the results you expected:**
I know those can be reserved words and no one will bring service with those names, but I accidentally  created them, and I should be able to delete them seamlessly 

**Additional information you deem important (e.g. issue happens only occasionally):**
NA

**Comment by thaJeztah** [comment] 2016-07-20 10:03
Nice catch! Yes, this should be fixed (either disallowing those names if there's a reason to, or make sure that deleting them works)

**Comment by dperny** [comment] 2016-07-20 18:03
Not a bug. OP ran 

`docker service create create`

This creates a service with a randomly generated name with the image set to `create`. Same goes for help. `create` and `help` aren't the names of the services, just the names of the images. The services can be removed normally by using their names. (`jolly_bell` and `backstabbing_jones`)

**Comment by thaJeztah** [comment] 2016-07-20 18:19
oh! thanks @dperny, you're absolutely right! I was thinking the wrong endpoints would be called, and already was thinking how "help" could affect this (as there's no API endpoint named "help")

@junaid18183 see @dperny's comment above. I'll close this issue as this is not a bug indeed 👍

**Closed by thaJeztah** 2016-07-20 18:19 UTC
Labels: area/swarm, kind/bug, priority/P3, version/1.12

**Comment by junaid18183** [comment] 2016-07-28 08:03
Thanks for the explanation @dperny
