### ISSUE TITLE
inspect service return data can't find mount readonly

### ISSUE THREAD

**Issue by yqguodataman** [docker/docker#25123] opened 2016-07-27 11:46 UTC
like this json:
Mounts can't find ReadOnly field,

```
{
    "ID": "5rdctxoczjlirkezynocxtw1l",
    "Version": {
        "Index": 1178
    },
    "CreatedAt": "2016-07-21T18:40:23.837962145Z",
    "UpdatedAt": "2016-07-21T18:40:23.839925409Z",
    "Spec": {
        "Name": "000_redis",
        "Labels": {
            "com.docker.stack.namespace": "000",
            "key": "value"
        },
        "TaskTemplate": {
            "ContainerSpec": {
                "Image": "redis",
                "Dir": "/a",
                "Mounts": [
                    {
                        "Type": "bind",
                        "Source": "/a",
                        "Target": "/b"
                    }
                ],
                "StopGracePeriod": 1
            },
            "Resources": {},
            "RestartPolicy": {
                "Condition": "none",
                "Delay": 1,
                "MaxAttempts": 1,
                "Window": 1
            },
            "Placement": {
                "Constraints": [
                    "key=value"
                ]
            }
        },
        "Mode": {
            "Replicated": {
                "Replicas": 1
            }
        },
        "Networks": [
            {
                "Target": "7r25r7r828cwo95d8ne8ygfe4",
                "Aliases": [
                    "redis"
                ]
            },
            {
                "Target": "1sous41w064vmm7fvx4hgpqza",
                "Aliases": [
                    "redis"
                ]
            }
        ],
        "EndpointSpec": {
            "Mode": "vip",
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 80,
                    "PublishedPort": 8888
                }
            ]
        }
    },
    "Endpoint": {
        "Spec": {
            "Mode": "vip",
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 80,
                    "PublishedPort": 8888
                }
            ]
        },
        "Ports": [
            {
                "Protocol": "tcp",
                "TargetPort": 80,
                "PublishedPort": 8888
            }
        ],
        "VirtualIPs": [
            {
                "NetworkID": "dij6a67mnzjisho35cglvvujv",
                "Addr": "10.255.0.2/16"
            },
            {
                "NetworkID": "7r25r7r828cwo95d8ne8ygfe4",
                "Addr": "10.0.5.2/24"
            },
            {
                "NetworkID": "1sous41w064vmm7fvx4hgpqza",
                "Addr": "10.0.8.2/24"
            }
        ]
    }
}
```

**Comment by thaJeztah** [comment] 2016-07-27 11:59
Can you add the output of `docker version` and `docker info`, and also provide the steps to reproduce? (i.e. what options did you use for the `--mount` flag)

**Comment by thaJeztah** [comment] 2016-07-27 12:03
Note that the service inspect does not show `ReadOnly` if it's not set (or the default), i.e.;

```
docker service create --mount type=volume,target=/foo --name web nginx:alpine
```

results in:

```
                    "Mounts": [
                        {
                            "Type": "volume",
                            "Target": "/foo"
                        }
                    ]
```

But setting readonly to true, gives:

```
docker service create --mount type=volume,target=/foo,readonly=true --name web nginx:alpine
```

```
                  "Mounts": [
                        {
                            "Type": "volume",
                            "Target": "/foo",
                            "ReadOnly": true
                        }
                    ]
```

**Comment by yqguodataman** [comment] 2016-07-28 06:33
@thaJeztah this is Mount struct:
type Mount struct {
    Type     MountType `json:",omitempty"`
    Source   string    `json:",omitempty"`
    Target   string    `json:",omitempty"`
    ReadOnly bool      `json:",omitempty"`

    BindOptions   *BindOptions   `json:",omitempty"`
    VolumeOptions *VolumeOptions `json:",omitempty"`
}
inspect service there is no return ReadOnly option.

**Comment by thaJeztah** [comment] 2016-07-28 07:21
It's because of the `omitempty`, see my explanation above

**Comment by thaJeztah** [comment] 2016-10-29 06:44
Closing as this is not a bug (see explanation above), but feel free to comment after I closed

**Closed by thaJeztah** 2016-10-29 06:44 UTC
Labels: status/more-info-needed
