### ISSUE TITLE
Replace docker 1.8.1 with docker 1.11.0-dev run would failed to run container

### ISSUE THREAD

**Issue by HackToday** [docker/docker#20855] opened 2016-03-02 10:33 UTC
I have old environment with Fedora 21 Atomic (integrated with docker 1.8.1).

Since I am helping debug the issue https://github.com/docker/docker/pull/20829
I need to compier the docker code into 1.11.0-dev binary, and then replace that 1.8.1 daemon with 1.11.0-dev to verify if that #20829 fix the volume plugin issue.

I found the new binary would not run simple containers
[**Note: I did not use volume-driver here]

The following is about when run  `docker-1.11.0-dev info`
```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 10
Server Version: 1.11.0-dev
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 245.4 MB
 Data Space Total: 2.147 GB
 Data Space Available: 1.902 GB
 Metadata Space Used: 147.5 kB
 Metadata Space Total: 8.389 MB
 Metadata Space Available: 8.241 MB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.82 (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: rexray local
 Network: null host bridge
Kernel Version: 3.17.4-301.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal
ID: YG5J:AFK2:E7OI:ALFE:PQUV:FOG2:ZX4K:SZQZ:GTOG:QP2Q:E2GE:HN3N
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 22
 System Time: 2016-03-02T09:51:20.613804637Z
 EventsListeners: 0
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. Compier docker master branch code into binary
2. Replace systemd service bin start to use the new binary( for example 1.11.0-dev)
as following 
```
ExecStart=/home/fedora/docker-1.11.0-dev daemon -D -H fd:// \
          -H tcp://0.0.0.0:2375 \
          $OPTIONS \
          $DOCKER_STORAGE_OPTIONS \
          $DOCKER_NETWORK_OPTIONS \
          $INSECURE_REGISTRY
LimitNOFILE=1048576
```
3. And then start docker.

4. Just run  `docker run -it busybox sh`

It would failed with

```
Mar 02 10:00:00 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T10:00:00.633076264Z" level=debug msg="Client and server don't have the same version (client: 1.8.1.fc21, server: 1.11.0-dev)"
Mar 02 10:00:00 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T10:00:00.631870148Z" level=debug msg="GET /v1.20/images/json"
Mar 02 10:00:00 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T10:00:00.616856128Z" level=debug msg="Calling GET /v1.20/images/json"
Mar 02 09:56:55 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T09:56:55.185038887Z" level=error msg="Handler for POST /v1.23/containers/eedf7d2a7afcb8313ed9c7a8bf7034048993a3b964182b3c31d7ead3f5d69848/start returned error: devmapper: Error mounting '/dev/mapper/docker-253:0-4202207-c800ec8253154755d449fa8189b3bcc70db270d0a9a42fe5e3274a42f4f6b740' on '/var/lib/docker/devicemapper/mnt/c800ec8253154755d449fa8189b3bcc70db270d0a9a42fe5e3274a42f4f6b740': no such file or directory"
Mar 02 09:56:55 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T09:56:55.183696354Z" level=error msg="Error unmounting container eedf7d2a7afcb8313ed9c7a8bf7034048993a3b964182b3c31d7ead3f5d69848: invalid argument"
Mar 02 09:56:55 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T09:56:55.175278808Z" level=error msg="devmapper: Error unmounting device c800ec8253154755d449fa8189b3bcc70db270d0a9a42fe5e3274a42f4f6b740: invalid argument"
Mar 02 09:56:55 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T09:56:55.174295362Z" level=debug msg="devmapper: UnmountDevice(hash=c800ec8253154755d449fa8189b3bcc70db270d0a9a42fe5e3274a42f4f6b740) END"
Mar 02 09:56:55 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T09:56:55.173728081Z" level=debug msg="devmapper: Unmount(/var/lib/docker/devicemapper/mnt/c800ec8253154755d449fa8189b3bcc70db270d0a9a42fe5e3274a42f4f6b740)"
Mar 02 09:56:55 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T09:56:55.172077400Z" level=warning msg="devmapper: Mount count of device went negative. Put() called without matching Get(). Resetting count to 0"
Mar 02 09:56:55 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T09:56:55.171592162Z" level=debug msg="devmapper: UnmountDevice(hash=c800ec8253154755d449fa8189b3bcc70db270d0a9a42fe5e3274a42f4f6b740)"
Mar 02 09:56:55 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T09:56:55.161107759Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/eedf7d2a7afcb8313ed9c7a8bf7034048993a3b964182b3c31d7ead3f5d69848/shm: no such file or directory"
Mar 02 09:56:54 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T09:56:54.838224332Z" level=debug msg="devmapper: activateDeviceIfNeeded(c800ec8253154755d449fa8189b3bcc70db270d0a9a42fe5e3274a42f4f6b740)"
Mar 02 09:56:54 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T09:56:54.658059181Z" level=debug msg="POST /v1.23/containers/eedf7d2a7afcb8313ed9c7a8bf7034048993a3b964182b3c31d7ead3f5d69848/start"
Mar 02 09:56:54 sw-s5lcdlw5ktj-0-jserl73ppvan-swarm-node-lscjkrmyn6rx.novalocal docker-1.11.0-dev[2999]: time="2016-03-02T09:56:54.645789098Z" level=debug msg="Calling POST /v1.23/containers/eedf
```

Describe the results you received:
 the new binary could not start containers

Describe the results you expected:
I would expect new docker binary  can start containers

Provide additional info you think is important:
nothing else

**Comment by HackToday** [comment] 2016-03-02 10:34
ping @thaJeztah  if you know about it :)   Thanks

**Comment by thaJeztah** [comment] 2016-03-02 10:46
I think you should try to build a dynamic binary; `Udev Sync Supported: false` is probably the cause here, due to a really old version of device mapper. Running without Udev Sync is known to result in data-loss and corruption on devmapper.

(Also note that Fedora 21 is EOL'd and we no longer build binaries for that, but that shouldn't be an issue if you're building yourself)

**Comment by HackToday** [comment] 2016-03-02 14:04
@thaJeztah I used `make BINDDIR=. binary` ways, I did not know when you talked about `dynamic binary` 

Could you tell me what's way for that to build ?

Also for `Udev Sync Supported: false`, I searched a similar issue, but what I want was to verify #20829 fix, So it is needed to have docker binary running on atomic. Or else, it can not guarantee, it fixed that issue.

**Comment by HackToday** [comment] 2016-03-03 00:08
ping @thaJeztah  if you know how to build a dynamic binary. (as comments above) :)

**Comment by thaJeztah** [comment] 2016-05-19 13:07
@HackToday oh! I meant to answer that; you can build deb or rpm packages using `make deb` / `make rpm`. By default, all supported distros are built (see https://github.com/docker/docker/tree/master/contrib/builder/rpm/amd64 and https://github.com/docker/docker/tree/master/contrib/builder/deb/amd64).

If you want to build only for specific distro, use the `DOCKER_BUILD_PKGS` env-var, for example, to build a `deb` package for Ubuntu Xenial;

```bash
DOCKER_BUILD_PKGS=ubuntu-xenial make deb
```

Those builds are run in a container (so you should have docker running), but the results are put in the `bundles` directory on your host;

```
tree bundles/
bundles/
├── 1.12.0-dev
│   ├── build-deb
│   │   ├── docker.log
│   │   ├── test.log
│   │   └── ubuntu-xenial
│   │       ├── Dockerfile.build
│   │       ├── docker-engine_1.12.0~dev~git20160518.202625.0.1691fe6-0~xenial.dsc
│   │       ├── docker-engine_1.12.0~dev~git20160518.202625.0.1691fe6-0~xenial.tar.gz
│   │       ├── docker-engine_1.12.0~dev~git20160518.202625.0.1691fe6-0~xenial_amd64.changes
│   │       └── docker-engine_1.12.0~dev~git20160518.202625.0.1691fe6-0~xenial_amd64.deb
│   ├── dynbinary
│   ├── dynbinary-client
│   │   ├── docker -> docker-1.12.0-dev
│   │   ├── docker-1.12.0-dev
│   │   ├── docker-1.12.0-dev.md5
│   │   └── docker-1.12.0-dev.sha256
│   └── dynbinary-daemon
│       ├── dockerd -> dockerd-1.12.0-dev
│       ├── dockerd-1.12.0-dev
│       ├── dockerd-1.12.0-dev.md5
│       └── dockerd-1.12.0-dev.sha256
└── latest -> 1.12.0-dev
```

**Comment by thaJeztah** [comment] 2016-05-19 13:09
Given that Fedora 21 is not longer supported, you may need to add a docker file for that in the "builder" directory, similar to https://github.com/docker/docker/blob/master/contrib/builder/rpm/amd64/fedora-22/Dockerfile

I'll close this issue, because I think your question is answered, but feel free to comment after I closed 👍

**Closed by thaJeztah** 2016-05-19 13:09 UTC
