### ISSUE TITLE
Run Docker without Daemon

### ISSUE THREAD

**Issue by sivaswami** [docker/docker#27645] opened 2016-10-21 21:28 UTC
Hi I exported docker image from my HOST machine (say image.tar)
I don't want to run docker  daemon service in my target machine. I can copy client (/usr/bin/docker) file and want to launch the docker container locally. 
Please note that using DOCKER_HOST environment option is not applicable as the target machine is in different network.
Any suggestions?

**Comment by thaJeztah** [comment] 2016-10-23 20:34
`usr/bin/docker` is only the client. Without a runtime, you cannot run the container. If you want to manually construct and run containers, you may want to look at runC https://github.com/opencontainers/runc

Anyway this issue tracker is for tracking bugs and feature requests for docker, and not a general support forum. For questions like this, https://forums.docker.com is probably a better location.

I'll,close this issue as it's not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-10-23 20:34 UTC

**Comment by exfly** [comment] 2023-03-25 03:05
I would like to recommend a project - https://github.com/exfly/bmc, which seems to be able to satisfy your needs for directly running Docker saved tar files.
