### ISSUE TITLE
Container MAC address changes on reboot

### ISSUE THREAD

**Issue by aderouineau** [docker/docker#15781] opened 2015-08-23 23:12 UTC
When using a static IPv6 CIDR, Docker uses the MAC address of the container to set up its global IPv6.

Not being able to specify the IP when running "docker run" is one thing, but the MAC address is changed each time the container is restarted. I do not see why a MAC address cannot be kept across restarts. The other issue is that there does not seem to be a way for a container to get an IPv6 that is kept across restarts.

```bash
> docker inspect -f '{{.NetworkSettings.GlobalIPv6Address}}' ntpd
2001:470:c841:3002:1:242:ac11:3
> docker restart ntpd
> docker inspect -f '{{.NetworkSettings.GlobalIPv6Address}}' ntpd
2001:470:c841:3002:1:242:ac11:4
```

```bash
> docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

```bash
> docker info
Containers: 1
Images: 24
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 7.816 GiB
Name: citadel
ID: JE3Z:MSXI:4V4O:GFSH:LA32:JKH4:JUAZ:OCWB:BVWP:MPIH:4W7E:3QDK
WARNING: No swap limit support
```

```bash
> uname -a
Linux citadel 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

**Comment by coolljt0725** [comment] 2015-08-24 09:02
From what I know, currently, this is by design, if user didn't specified a mac address on container creation use option `--mac-address`, docker will generate a random mac address on container start.
If you want a static mac address, I think you can try `--mac-address`.

**Comment by aderouineau** [comment] 2015-08-27 00:36
That is my issue: why change the MAC address on a restart when there does not seem to be a logical reason for it? VM NICs keep the same MAC addresses across restarts...

**Comment by mavenugo** [comment] 2016-10-22 17:02
@aderouineau `docker run` now supports both `--ip` (for user-defined networks) and `--mac-address`. Setting either 1 will guarantee static address on restarts. I will close this issue.

**Closed by mavenugo** 2016-10-22 17:02 UTC
Labels: area/networking, version/1.7
