### ISSUE TITLE
no such option as --update-max-failure-ratio in docker service create

### ISSUE THREAD

**Issue by dvohra** [docker/docker#30655] opened 2017-02-02 00:09 UTC
**Description**
The documentation for `docker service create` lists a` --update-max-failure-ratio `option, but the `docker service create --help` does not list any such option.
https://docs.docker.com/engine/reference/commandline/service_create/

**Steps to reproduce the issue:**
1. Create a EC2 instance from CoreOS Stable
2. Create a Docker Swarm cluster with 1 manager and 2 worker nodes
3. The `docker service create --help` does not list the `--update-max-failure-ratio` option

**Describe the results you received:**
No such option as `--update-max-failure-ratio`

**Describe the results you expected:**
The `--update-max-failure-ratio` option listed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
core@ip-10-0-0-238 ~ $ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Tue Jan 31 07:56:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Tue Jan 31 07:56:17 2017
 OS/Arch:      linux/amd64


```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS EC2, CoreOS Stable

**Comment by cpuguy83** [comment] 2017-02-02 02:02
Did you try 1.13.0?

**Comment by thaJeztah** [comment] 2017-02-02 02:14
Yes, this feature was added in https://github.com/docker/docker/pull/26421, which is part of the 1.13 release. Try updating to the latest version, and you should be able to use this feature.

I'm closing this issue because it's not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-02-02 02:14 UTC
Labels: area/swarm, version/1.12

**Comment by dvohra** [comment] 2017-02-02 03:36
Thanks. CoreOS has Docker pre-installed and CoreOS AMI on AWS has 1.2.6 installed.

**Comment by thaJeztah** [comment] 2017-02-02 03:47
There are no official docker packages for CoreOS, so it's best to report that in their issue tracker

**Comment by dvohra** [comment] 2017-02-02 18:23
Thanks thaJeztah. The issue may be closed.
