### ISSUE TITLE
running a container mounting a host drive overwrites container contents.

### ISSUE THREAD

**Issue by laurencefass** [docker/docker#32203] opened 2017-03-29 15:22 UTC
platform: docker toobox for windows 17.0.03

When running a container with a mount from a host drive, the docker host folder contents overwrites the container's folder contents entirely. There is no overlay of data as detailed in the docs.

my ubuntu container command: 

> docker run -d -P --name MYCONTAINER -v /c/Users/drupal8_www:/var/www/html MY:IMAGE

by stopping and starting this i can clearly see and repeat the effect describe above.

thanks

**Comment by thaJeztah** [comment] 2017-03-30 01:32
This is working as expected; bind-mounting a host-directory does a regular "mount" at the target location in the container; see https://github.com/docker/docker/issues/4361#issuecomment-167156818

I see the wording [in this section is a bit confusing](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-directory-as-a-data-volume);

> This command mounts the host directory, /src/webapp, into the container at /webapp. If the path /webapp already exists inside the container’s image, the /src/webapp mount overlays but does not remove the pre-existing content. Once the mount is removed, the content is accessible again. This is consistent with the expected behavior of the mount command.

Can you open an issue in the documentation issue tracker? https://github.com/docker/docker.github.io/issues (or perhaps you're interested in opening a pull request - you can find an "edit this page" button on the documentation)

I'll close this issue here, because this is not a bug in the source-code, but in the documentation, but feel free to continue the discussion.

**Closed by thaJeztah** 2017-03-30 01:32 UTC
Labels: area/docs, area/volumes, kind/enhancement

**Comment by laurencefass** [comment] 2017-03-30 07:56
ok thanks. can you please confirm for clarity: this command IS MEANT TO overwrite the contents of the target (container) folder with the source (docker host). i will open a doc issue...
