### ISSUE TITLE
need to restart docker daemon after every reboot/start

### ISSUE THREAD

**Issue by k0377** [docker/docker#16673] opened 2015-09-30 08:48 UTC
Whenever I turn on my laptop or reboot, I've to restart docker daemon first with `sudo systemctl restart docker.service`. I'm on Arch Linux. Otherwise, my lamp containers are not accessible from localhost in the browser.

```
Docker version 1.8.1, build d12ea79
docker-compose version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

**Comment by Pensu** [comment] 2015-09-30 11:00
Not much familiar with Arch Linux, but don't you have any init script or something, where you can just put the service and it's already started on boot?

**Comment by mavenugo** [comment] 2015-09-30 12:50
@k0377 @Pensu 
Thanks for reporting the issue. But this is a dupe of https://github.com/docker/docker/issues/15630. pls use 1.8.2.
Closing this.

**Closed by mavenugo** 2015-09-30 12:50 UTC
