### ISSUE TITLE
Running container causes docker daemon to restart with "ERRO[0127] error getting events from daemon: EOF"

### ISSUE THREAD

**Issue by dannylui** [docker/docker#30724] opened 2017-02-03 18:49 UTC
I have created a container to run chrome protractor tests, but at random points during running the tests, I would encounter a failure that seems to indicate the docker daemon restarted.  When this happens, all my running containers fail with the same error.  Try as I may, I cannot find any find any info on this error: ERRO`[0127] error getting events from daemon: EOF `

```
<starting the protractor tests>
[13:19:08] I/launcher - Running 1 instances of WebDriver
Started
....ERRO[0127] error getting events from daemon: EOF   

<checking ps seems to indicate the docker daemon is being restarted>
$> docker ps -a
Error response from daemon: Bad response from Docker engine

$> docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                       PORTS               NAMES
34edc11ba79d        dxng-test           "docker/docker-tes..."   2 minutes ago       Exited (255) 5 seconds ago                       dxng-test
```

**Steps to reproduce the issue:**
1. This appears to only happen when I run this particular container (running protractor tests)
2. Same container runs completely fine on centos VM, and on colleague's macbook.  That colleague actually had the same issue, but the failure went away after he rebooted his macbook.

**Describe the results you received:**
Container stopped abruptly with error message:`ERRO[0127] error getting events from daemon: EOF `

**Describe the results you expected:**
I did not expect the container to stop, nor the daemon to restart regardless of what the resource usage is within the container

**Additional information you deem important (e.g. issue happens only occasionally):**
Another important thing to note is that I'm running with --privileged to allow chrome running with sandbox mode.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 43
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 249
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: LU37:WYI5:H4LX:FNXA:ZWZW:YSGY:FJKV:LKKT:VC3K:I6RT:PFEO:UOTV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2017-02-03T18:35:56.980608295Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: dannylui
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-02-05 03:57
Can you provide a minimal Dockerfile or image, and the exact steps to reproduce?

**Comment by dannylui** [comment] 2017-02-05 13:03
I think I figured out the issue, partially.  Running chrome headlessly used to require --privileged mode due to chrome's need to run in a sandbox.  But I've found that chrome has a --no-sandbox optional argument.  With that, I don't need --privileged mode.  Without privileged mode, the container runs perfectly fine.  My guess is that privileged mode allows the container to access things it shouldn't on the host and thus somehow manages to cause a fault on the docker daemon.

**Comment by thaJeztah** [comment] 2017-02-05 21:09
> running with --privileged mode is dangerous, avoid at all costs.

Yes, `--privileged` effectively turns off all protection that containers give, and give the process inside the container full root access to your host.

Good to hear you managed to get it working; let me close this issue as it looks to be resolved

**Closed by thaJeztah** 2017-02-05 21:09 UTC
Labels: status/more-info-needed, version/1.13

**Comment by dannylui** [comment] 2017-02-06 14:27
Thanks @thaJeztah

**Comment by garciasa** [comment] 2017-02-16 19:19
Hi guys, 
I´ve the same issue.
I´m in version Version 1.13.1-beta42 (15350) OSX.
I´m using tensorflow docker container, and when I´m training my network with images, I get this
<img width="981" alt="screen shot 2017-02-16 at 19 16 14" src="https://cloud.githubusercontent.com/assets/1852069/23036925/823d9b46-f47c-11e6-85a4-207d2b0285b1.png">

Sometimes I get error earlier, or later, there is no defined pattern.
The container is running on 8GB and 2 processors, any feedback is appreciated.

Cheers

**Comment by thaJeztah** [comment] 2017-02-16 23:45
@garciasa can you open a new issue with the information that's requested in the issue template (including `docker version`, `docker info`, steps to reproduce? It _can_ be an issue specific to Docker for Mac (but hard to tell without more information), in which case we may ask you to reopen in the docker for mac issue tracker (https://github.com/docker/for-mac/issues)

Logfiles would probably be needed, as this looks like the daemon stopped responding at some point (which can have numerous reasons)

**Comment by thaJeztah** [comment] 2017-02-16 23:46
I am locking the conversation on this issue, because the original issue was resolved, and there's many reasons for the `EOF` issue to occur. If you are running into this issue, please open a new issue
