### ISSUE TITLE
Public Docker downloads page w/ checksums

### ISSUE THREAD

**Issue by ecnahc515** [docker/docker#7974] opened 2014-09-10 18:15 UTC
You guys have get.docker.io and github for releases of docker, but I think it would be really nice to have a public downloads page where you can just find the binary/tarball for your system and click on it to download docker. In addition to this, it would be nice if every download contained a sha1 checksum on that page to verify the binary.

I was thinking something along the lines of how http://golang.org/dl/ looks.

**Comment by cpuguy83** [comment] 2015-02-21 03:19
There is get.docker.com/builds/<OS>/<platform>/docker-<version>
Also for master builds master.dockerproject.com

ping @jfrazelle

**Comment by thaJeztah** [comment] 2015-02-21 09:46
Adding a download page with all released binaries to dockerproject.com (releases.dockerproject.com ?) would be really helpful.

Recently, I tried to reproduce an issue that someone reported, for which I needed an older version of docker. I think I managed to "deduct" the download link by following the script on get.docker.com, but having an overview of all releases would have saved me a lot of time.

**Comment by ankushagarwal** [comment] 2015-04-08 19:02
:+1:

**Comment by ankushagarwal** [comment] 2015-04-08 19:07
It would be nice to have client binaries for Windows/OS X downloadable directly instead of going through the whole boot2docker install process.

**Comment by jfrazelle** [comment] 2015-04-08 19:36
Yes they are today but nobody knows the url because we don't have a nice
index page :) contributions welcome!!! Especially for some pretty css or
something

**Comment by cpuguy83** [comment] 2015-04-08 19:38
@jfrazelle Contribution should go do where?

**Comment by thaJeztah** [comment] 2015-04-08 19:38
@jfrazelle where's the repo for dockerproject.com?

**Comment by jfrazelle** [comment] 2015-04-08 19:40
Here! I mean there is nothing now :) maybe a new dir in project/. Where is
really an implementation detail but we have nothing lol

**Comment by thaJeztah** [comment] 2015-04-08 19:57
For inspiration on what's needed (but then per-release) https://master.dockerproject.com

**Comment by ankushagarwal** [comment] 2015-04-08 20:15
Not sure if this is the best idea, but (for now) can the old release binaries be linked from the Github [releases page](https://github.com/docker/docker/releases/tag/v1.5.0)? Currently it only lists links to download the source.

I think it's important that we link them from somewhere instead of waiting for a nice CSS design(which can always be updated later). Even [this](https://master.dockerproject.com/) looks like a decent design for a binary release page for now.

**Comment by ankushagarwal** [comment] 2015-04-08 20:28
I know that currently `dockerproject` subdomain is used for downloads, but it would be nice to use `downloads.docker.com` subdomain to release the binaries. Something like `https://downloads.docker.com/docker/1.5.0/linux/386/docker`. Probably involves a little bit of work, but *it feels right* for the long term.

**Comment by thaJeztah** [comment] 2015-04-08 20:51
Well, I added the link so that people would know which links should be included (so, also md5/sha256)

Thinking of this, I think no design is really required; if we're okay with adding a page to the docs, then a simple Markdown document could suffice for now; e.g.

| Platform | Architecture | Release | Download |
| --- | --- | --- | --- |
| OS X (client only) | amd64 | 1.6 | [binary](#) [md5](#) [sha256](#) |
| OS X (client only) |  i386 | 1.6 | [binary](#) [md5](#) [sha256](#) |

Perhaps separate tables for client-only downloads and client+daemon, separate sections per release, so that that can anchor-links can be included in the left-hand menu.

I'm thinking out loud here, so;

/cc @moxiegirl (for docs)

**Comment by jfrazelle** [comment] 2015-04-08 20:57
I kinda like the idea of a release.dockerproject.com or something but of
course this could be later :)

**Comment by jfrazelle** [comment] 2015-04-08 20:57
We could always make that redirect to the docs page \o/

**Comment by thaJeztah** [comment] 2015-04-08 21:02
Yes, adding to the docs is definitely not the ultimate goal, but it *is* something that's actionable right now and (if we explain how the links can be found), should even be suitable for beginning contributors.

Bonus point for a simple shell script that can generate the tables after a new release :smile:

**Comment by moxiegirl** [comment] 2015-04-09 22:16
This feels like a pretty extreme edge case for docs.docker.com especially as I'm hearing we have to manually maintain it. Also, I'm a bit concern including older binaries in the "docs.docker.com" section might confuse the majority of people who don't care or need them.  I can see adding a page at the root of the repo adding the the list @ankushagarwal pointed out https://master.dockerproject.com/

**Comment by thaJeztah** [comment] 2015-04-09 22:58
Well, the obvious problem is that the main www.docker.com website is not maintained here, and I wonder how many people will find the dockerproject.com website.

It could be part of the https://docs.docker.com/installation/binaries/ document , and, since there's already a "version" dropdown, only the "latest" would be required.

I agree that manually maintaining the links is a problem; it could be part of the release checklist (or automatically updated, using the [VERSION](https://github.com/docker/docker/blob/master/VERSION) file.

**Comment by ankushagarwal** [comment] 2015-04-09 23:01
I don't see why the binaries can't be linked from the github releases page

**Comment by thaJeztah** [comment] 2015-04-09 23:14
Yes, the releases page could be an option (but would also have to be maintained manually)

Thinking a bit further on automating this; would it be problematic to enable autoIndex on get.docker.com for the `/builds/` path (and below)? Then (e.g.) http://download.docker(project).com can be redirected to https://get.docker.com/builds/

And I see there's a module that allows skinning; http://wiki.nginx.org/NgxFancyIndex

(Alternatively, Looks like [NGINX allows outputting as JSON](http://nginx.org/en/docs/http/ngx_http_autoindex_module.html#autoindex_format), which could be used as an API to dynamically create a website somewhere else :))

**Comment by tianon** [comment] 2015-04-09 23:19
"get.docker.com" is direct S3 :cry:

**Comment by jfrazelle** [comment] 2015-04-09 23:21
ya this would need to be an html page, generated by releases etc and then
would deploy to a certain domain

**Comment by ankushagarwal** [comment] 2015-04-09 23:22
I am not saying that we should not have a downloads page, I am completely up for that, but *for now* releases page can at least link to the binaries which currently have no references *anywhere*

About the manual process and maintenance, it takes a one line Find Replace to create a new release entry eg: (⌘F 1.5.0, ⌘R 1.6.0).

**Comment by ankushagarwal** [comment] 2015-04-09 23:23
A simple Markdown table(which is easy to maintain) in the releases page can suffice, something which @thaJeztah created above
![image](https://cloud.githubusercontent.com/assets/796949/7079067/c03c14dc-ded4-11e4-9580-514461e58b03.png)

**Comment by tiborvass** [comment] 2015-04-09 23:24
@tianon better than CloudFront nightmare

**Comment by thaJeztah** [comment] 2015-04-09 23:31
> "get.docker.com" is direct S3

Ah, shucks

**Comment by moxiegirl** [comment] 2015-04-10 01:16
+1 for the releases page @ankushagarwal  is suggesting. That's where I went first --- *isn't it already there* was the thought.

**Comment by ankushagarwal** [comment] 2015-04-18 17:53
Since the release binary locations have not been documented in the releases page, I have added a section in the `installation/binaries.md` page which documents the URL of these binaries since the are literally not documented anywhere.

Here is the PR : https://github.com/docker/docker/pull/12512/

Here is the edit to the section

![image](https://cloud.githubusercontent.com/assets/796949/7216579/0fa77562-e5b9-11e4-8209-9f9b326543a1.png)

**Comment by tiborvass** [comment] 2015-07-31 13:39
Closing in favor of #15035

**Closed by tiborvass** 2015-07-31 13:39 UTC
Labels: exp/expert, kind/feature
