### ISSUE TITLE
Daemon memory leak in image load when called from go dockerclient

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#19177] opened 2016-01-08 03:24 UTC
When using the samalba docker client, loading a large image can cause the daemon in 1.10 to become extremely large.  In my testing, using a 714M image (selenium/standalone-firefox:2.47.1 in my case, but any large image should do) and the following example program, 1.9 stays small (~50-60MB rss) but 1.10 grows to 1.8G

```go
package main

import (
	"fmt"
	"os"
	"github.com/samalba/dockerclient"
)

func main() {
	c, err := dockerclient.NewDockerClient("unix:///var/run/docker.sock", nil)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to connect: %s\n", err)
		os.Exit(1)
	}
	if err := c.LoadImage(os.Stdin); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to send image: %s\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "finished the load\n")
}
```

Loading the same image with the docker CLI doesn't cause the massive memory growth (it stays in the 50-60MB range rss).

**Comment by HackToday** [comment] 2016-01-08 05:12
hi @dhiltgen  Could you specify what docker CLI do you use to load that image ?


And for  samalba docker client, you got memory grow to 1.8G, How do you get that data ? from top or any linux commands ?

**Comment by dhiltgen** [comment] 2016-01-08 15:44
I was testing with a developer build from an engine tree built within the last couple days.

To see the size, `top`, or `ps -eo pid,rss,vsz,sz,args`

**Comment by thaJeztah** [comment] 2016-01-10 02:09
ping @aaronlehmann @tonistiigi could you have a look at this?

**Comment by aaronlehmann** [comment] 2016-01-11 18:34
I can reproduce this. The requests look very similar except for some differences in the URI and headers:

Standard client:
```
POST /v1.22/images/load HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: Docker-Client/1.10.0-dev (linux)
Transfer-Encoding: chunked
Content-Type: text/plain
Accept-Encoding: gzip
```

samalba dockerclient:
```
POST /v1.15/images/load HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: Go-http-client/1.1
Transfer-Encoding: chunked
Content-Type: application/json
Accept-Encoding: gzip
```

**Comment by aaronlehmann** [comment] 2016-01-11 18:39
I suspect this is related to #18878. Since `github.com/samalba/dockerclient` incorrectly sets the content type to `application/json`, the engine is trying to decode the tar stream as JSON.

ping @calavera

**Comment by aaronlehmann** [comment] 2016-01-11 18:49
Indeed, changing the `Content-Type` header added by `github.com/samalba/dockerclient` seems to solve this. But I actually don't think it's #18878, because that's a client side change dealing with the responses from the load endpoint.

**Comment by tonistiigi** [comment] 2016-01-11 22:02
Regression should be at #17266 (ping @cpuguy83) . Not sure if there is any point to trying to fix this though because it clearly seems a client bug.

**Comment by cpuguy83** [comment] 2016-01-11 22:04
Oh yes, that's probably it.
If the content-type is application/json + debug is enabled we'll dump the body to the logs.

**Comment by cpuguy83** [comment] 2016-01-11 22:07
Also likely an issue with authz plugins as well, which forwards the request body to plugins if the content-type is text/plain or application/json.

**Comment by tonistiigi** [comment] 2016-01-13 06:57
@dhiltgen You ok with closing this?

**Comment by dhiltgen** [comment] 2016-01-13 15:30
Aren't there a lot of clients out there in the wild that use the samalba docker client library?  Clearly we should fix the library to send the expected header but until apps ship a new version, those apps can cause a pretty substantial leak in the daemon.  That seems to me like something we should harden for and fix.

**Comment by dhiltgen** [comment] 2016-01-13 15:30
...particularly since this is a regression in 1.10.

**Comment by tonistiigi** [comment] 2016-01-13 15:37
@cpuguy83 maybe we could detect the size of the Body and skip logging if it's too big. We wouldn't want to log it anyway if it is more than a couple of KB, even if it is JSON.

**Comment by cpuguy83** [comment] 2016-01-13 16:16
@tonistiigi How do you suppose we detect the size? I wouldn't want to rely on the http header since it's technically already wrong.
I'm thinking `io.CopyAtLeast`, set the size to some max size and if it finishes without getting EOF we don't dump the request.

We do need to handle this with authz plugins as well.

**Comment by tonistiigi** [comment] 2016-01-13 17:56
@cpuguy83 `bufio.Peek` should also work. I think authz isn't that important as this is a new feature that users must start using to be affected.

**Closed** 2016-01-14 14:06 UTC
Labels: kind/bug, priority/P3

**Comment by dhiltgen** [comment] 2016-01-14 16:25
I can confirm that my test code no longer causes the memory leak with top-of-tree.  Thanks!

**Comment by tiborvass** [comment] 2016-01-14 16:26
@dhiltgen yayyy! thanks for verifying!

**Comment by cpuguy83** [comment] 2016-01-14 16:28
@dhiltgen Thanks for finding this!

**Comment by dhiltgen** [comment] 2016-01-14 16:30
no prob :-)
