### ISSUE TITLE
run with "--device", docker report /sys/fs/cgroup/devices/docker/containerID/.. ‘write error: Operation not permitted’

### ISSUE THREAD

**Issue by mayujsw** [docker/docker#12985] opened 2015-05-05 05:53 UTC
When i run docker with below command:
docker run --name 123 --device "/dev/bus/usb/002/048"  ubuntu adb devices
it reports error as below:
 /sys/fs/cgroup/devices/docker/xxx/device.allow.. ‘write error: Operation not permitted’

my intention is to launch a docker container with the access permission to one of my android devices (whose node name is /dev/bus/usb/002/048), but --device option does not work.

This is NOT a 100% reproducible issue, but when i met this, what i have to do is shutdown the host, and reboot, then it works, and i have the permission to add/remove device node in /sys/fs/cgroup/devices/docker/containerID/

does anyone knows at what circurmtence this error will happen, and how can i make it right without reboot my host...

Thanks

**Comment by mayujsw** [comment] 2015-05-05 09:51
----------------------------------
Description of problem:
docker run -dit --name 123 --device "/dev/bus/usb/002/048" ubuntu, it reports
"/sys/fs/cgroup/devices/docker/contiainerID/device.allow" : operation not permitted
-----------------------------------
`docker version`:
Docker version 1.6.0, build 4749651
-----------------------------------
`docker info`:
Containers: 3
Images: 100
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 106
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 4
Total Memory: 15.6 GiB
Name: pnp-docker03
ID: OCDX:ZSC3:5GBH:CUR4:3UR4:GBLA:TOOP:TTW7:WB6O:PB3V:QDSA:2A3J
WARNING: No swap limit support
---------------------------
`uname -a`:
Linux pnp-docker03 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

--------------------------
How reproducible:
This is NOT a 100% reproducible issue, but when it happens, it can only be recovered through rebooting host, after reboot, i run the same docker run command, then it has permission to add through device.allow in /sys/fs/cgroup/devices/docker/containerID/
---------------------------
Steps to Reproduce:
have no idea what need to do to make sure the issue can be reproduced, but what we have done, is:
1. launch a container with the permission to the node defined in --device
2. add/remove the node permission in this container though /sys/fs/cgroup/devices/docker/containerID/device.allow (device.deny for remove)
3. repeat step 2 for several times

------------------------
Actual Results:
FATA[0000] Error response from daemon: Cannot start container 4de9ba1e4987e744d1da83510b98a6a6242ad2bfc66e1069ae922dd88b351edf: write /sys/fs/cgroup/devices/docker/4de9ba1e4987e744d1da83510b98a6a6242ad2bfc66e1069ae922dd88b351edf/devices.allow: operation not permitted

Expected Results:
the container can be launched with the access permission to the defined node name "/dev/bus/usb/002/048"

Additional info:
This is NOT a 100% reproducible issue, but when it happens, it can only recovered from rebooting host

does anyone know at what circurmtence this error will happen, and how can i make it right without reboot my host...

**Comment by thaJeztah** [comment] 2015-06-02 18:09
No idea :smile:. I *do* see you're running on an outdated kernel for Ubuntu 14.04 (and that you system is not up-to-date). I strongly suggest to make sure you're system is fully up-to-date because we have seen issues because of that.


/ping @jfrazelle I think you did some Willy Wonka with devices in containers. Perhaps you have some additional thoughts or suggestions?

**Comment by LK4D4** [comment] 2015-06-02 18:11
I think it is some sort of race in libcontainer.

**Comment by jfrazelle** [comment] 2015-07-10 21:55
are you still able to reproduce on latest

**Comment by ibuildthecloud** [comment] 2015-07-12 04:56
@jfrazelle @LK4D4  I have a container doing the below on start.  I can't start it anymore.

```
Error response from daemon: Cannot start container bd6b01baed26: [8] System error: write /sys/fs/cgroup/devices/docker/bd6b01baed26da2908c6b676c41060e63717007a647de6e6139846e7a89f4990/devices.allow: invalid argument
Error: failed to start containers: [bd6b01baed26]
```

**Comment by ibuildthecloud** [comment] 2015-07-12 05:08
@LK4D4 Oh.... probably not the same issue but fun none the less.  I think this is caused by docker in docker.  Here's what I did.  Start container, start docker in there, start some more nested fun.  Now kill -3 the daemon (was troubleshooting something else).  On daemon restart it failed to clean up the cgroups because I had something like `cpuset/docker/bd6b01baed26da2908c6b676c41060e63717007a647de6e6139846e7a89f4990/docker/ea530a3d6b4c1db55dba6c9c8815eafdb0c4acbd475cefb32102a8fef43865a4`.

Now Docker can't start the container because these cgroups are left behind.  I just deleted the cgroups and now the container starts fine.  Is this something new in 1.7?  I thought before docker in docker didn't in fact nest cgroups, but I could be making that up.  It seems like Docker should look for nested cgroups and delete them too on cleanup.

**Comment by thaJeztah** [comment] 2015-07-12 08:31
@ibuildthecloud I think read another issue with docker-in-docker on 1.7.x, but (hmf) cannot find it right now

**Comment by thaJeztah** [comment] 2015-07-12 11:18
@ibuildthecloud found it; take a look here: https://github.com/docker/docker/issues/14543

**Comment by cpuguy83** [comment] 2015-08-17 14:35
Closing, @mayujsw if you can repro with docker 1.8 (or master binary) please ping here and we can take a look.
Thanks!

**Closed by cpuguy83** 2015-08-17 14:35 UTC
Labels: status/more-info-needed
