### ISSUE TITLE
Bridge network runs out of IPv4 Addresses (1.9 networking)

### ISSUE THREAD

**Issue by rncry** [docker/docker#17939] opened 2015-11-12 11:49 UTC
uname -a
Linux lon134 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

docker info
Containers: 3
Images: 21
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-253:2-47841284-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.116 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.3 GB
 Metadata Space Used: 2.228 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/tmp/doNotRemove/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/tmp/doNotRemove/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 8
Total Memory: 31.19 GiB
Name: lon134
ID: 62YK:STAU:TCS3:GUDE:UOOM:DVAJ:V4IE:QYTX:2HCD:KSB7:JHJI:TSAZ

This issues occurs when running a docker in docker image and mounting the host docker graph (as explained in the excellent tutorial):

docker run -d --privileged -v /var/tmp/doNotRemove/docker:/var/lib/docker docker:dind
382c309034b60f5135bc8ce2489dcf77682efdba6cb647d0e2032a9956997e0a

After this, all following docker commands fail as there as no addresses available:
eg: 

docker run -it ubuntu
Error response from daemon: Cannot start container a21aa1d4f4db6952bde77807eeaed65ba1dfc5f8950dc86bf6395725741a2b19: no available IPv4 addresses on this network's address pools: bridge (c4c9c6c7c4af2f0f997c37e0f0903f0209232b74a1a906385d0f476511e89630)

**Comment by aboch** [comment] 2015-11-12 17:08
There is a condition which may cause the ipam driver to return a "no available ip" error, while instead the inner erro is different, likely datastore related.
(I have a patch in libnetwork to return the proper error, but I need to confirm this is what you are hitting)

So far I was not able to reproduce following your steps. If you happen to remember any other steps done before, which would make the reproduction consistent, please let me know.

**Comment by rncry** [comment] 2015-11-12 17:10
Thanks for taking a look. I haven't needed to take any other steps to reproduce, but I suspected it might be down to the storage driver.. let me know if there's anything else I can try?

**Comment by mavenugo** [comment] 2015-11-13 17:28
@rncry it is not very clear on which tutorial you are referring to.
Also, it is not very clear if the issue is seen on the docker running inside the dind container.
Can you please post the exact commands that you are trying (both the docker daemon cmd and configs) and the dind container run.

**Comment by rncry** [comment] 2015-11-16 17:17
Hi @mavenugo thanks for taking a look :) It's the tutorial here: https://hub.docker.com/_/docker/

The issue is with the docker daemon running on the host (not inside the dind container)

The host docker is running as follows:
/usr/bin/docker daemon -g /var/tmp/doNotRemove/docker -H fd://

The other two commands in my first post are how I can reproduce the issue

**Comment by mavenugo** [comment] 2015-11-16 19:06
@rncry thanks for the info. and I can reproduce the problem as well. this is happening because there are 2 Docker Daemons sharing the same root directory. (`-g`). Its typically recommended to run multiple daemons with its own `-g` directory so that the data is not corrupted. Could you please try bind-mounting a different directory via `-v` for the dind container ? Is there a specific reason why you have to share the same ROOT ?

**Comment by rncry** [comment] 2015-11-17 16:04
Ahhh I see.. I was under the impression I could use the same root to share the containers created on the host with the dind daemon. Thanks for clearing that up!

**Comment by cpuguy83** [comment] 2015-11-18 13:37
Closing since it seems like this is not an issue.

Let me know if I'm mistaken.
Thanks!

**Closed by cpuguy83** 2015-11-18 13:37 UTC
Labels: group/networking

**Comment by beetree** [comment] 2016-02-13 07:45
Confirmed. This is truly fixed in 1.10. Been running it for weeks now and haven't seen this error a single time.

/beetree
