### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by iangelov** [docker/docker#13013] opened 2015-05-06 07:15 UTC
Hello guys,

For some reason docker daemon's process memory grows indefinitely to a point it can't even fork an external process -

[e4030cd3.allocate_port(d074af1bcecf15adb584c7059dd6099008631f5f6ee24e29233e623c630b3c97)] Failed to allocate and map port 31000: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 31000 ! -i docker0 -j DNAT --to-destination 172.17.0.165:8080:  (fork/exec /sbin/iptables: cannot allocate memory)
iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 31000 ! -i docker0 -j DNAT --to-destination 172.17.0.165:8080:  (fork/exec /sbin/iptables: cannot allocate memory)

The way I'm using it: few long-lived containers, few ephemeral containers started with docker wait.

I see nothing obvious in the log - perhaps I should raise the error level to debug?

The setup (I've experienced the same with 1.5, too):
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

Containers: 23
Images: 337
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 383
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-51-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 14.94 GiB
ID: KJ42:KSHI:IWYN:H7UG:UV36:VIMZ:QGRT:H7MH:CWHR:NFI6:V564:HFHC
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

**Comment by jfrazelle** [comment] 2015-05-06 07:20
This is a duplicate of a lot of other issues about memory leaks please search next time before creating a new one

**Closed by jfrazelle** 2015-05-06 07:20 UTC

**Comment by iangelov** [comment] 2015-05-06 07:50
Sorry - I did try to search, but I didn't find anything like it (I was actually surprised to see that). Nevertheless - thanks, I'll have a look again.

**Comment by unclejack** [comment] 2015-05-06 07:55
@iangelov Please look at at and comment on https://github.com/docker/docker/issues/12848

**Comment by iangelov** [comment] 2015-05-06 08:15
Thanks, I'm experiencing the exact same problem (I'm outputting loads of data to stdout). Right now I can't really disable logging (I'm actually using docker's logging feature to facilitate centralised logging), but I'll work around it by restarting docker (oh, well), hoping that docker 1.7.0 comes out sooner than later :)
