### ISSUE TITLE
Change kernel parameters failed in container

### ISSUE THREAD

**Issue by hustcat** [docker/docker#9890] opened 2015-01-04 07:52 UTC
```sh
# docker run -it --rm --privileged=true centos /bin/bash
[root@2f1d9b6f675c /]# echo 4194304 >  /proc/sys/net/core/rmem_max
bash: /proc/sys/net/core/rmem_max: Permission denied

# docker --version
Docker version 1.3.1, build 4e9bbfa
# uname -a
Linux yinye 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jfrazelle** [comment] 2015-02-26 23:57
cannot reproduce on docker 1.5 closing but let me know if you are still able to see this problem and how to reproduce

**Closed by jfrazelle** 2015-02-26 23:57 UTC

**Comment by msecrist** [comment] 2015-05-14 02:17
I'm running into a similar situation with a variant of the centos 6 image. What I'm seeing is that, while installing a software module (using yum install as root), it appears to modify /etc/sysctl.conf and then attempts to execute /sbin/sysctl -p when it returns :
error: permission denied on key 'net.core.rmem_max'
error: permission denied on key 'net.core.wmem_max'
