### ISSUE TITLE
Machine stuck running DinD on CentOS 6.5

### ISSUE THREAD

**Issue by kashyap-parikh** [docker/docker#11072] opened 2015-02-28 01:51 UTC
I am trying to run DinD on CentOS 6.5 VM + Docker Version 1.3.2 running in virtualbox on a mac.
Using /fedora example I was able to build dind image. The only change I had to make was replacing CGROUP=/sys/fs/cgroup with CGROUP=/cgroup in wrapdocker.

When I try to start dind it freezes the host VM. Just before the freeze I see that mkfs.ext4 is using 100% cpu.

To reproduce:
```
vagrant box centos65 https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box
vagrant box init centos65
vagrant up
vagrant ssh
$ git clone git@github.com:jpetazzo/dind.git
$ cd dind/fedora
Change Dockerfile "FROM centos:6"
Change wrapdocker "CGROUP=/cgroup"
$ sudo ./build.sh
$ docker run --privileged -t -i -e DOCKER_DAEMON_ARGS="-D" dind
```
Here's the console log with last few lines before VM freezes. The only way to recover is shutdown and start.

**Comment by jfrazelle** [comment] 2015-02-28 03:07
I think you forgot the link :/

**Comment by jfrazelle** [comment] 2015-02-28 03:08
can you try with the latest version of docker also we need the output of docker version, docker info, uname -a

**Comment by kashyap-parikh** [comment] 2015-03-02 18:10
Below is uname and screenshot. Latest docker version for CentOS 6.5 is [1.4.1](http://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/docker-io.html) and it has another issue #9856 that forced me to revert to 1.3.2.

[vagrant@vagrant-centos65 ~]$ uname -a
Linux vagrant-centos65.vagrantup.com 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

![screen shot 2015-02-25 at 2 32 39 pm](https://cloud.githubusercontent.com/assets/6559072/6446937/6e46f450-c0c3-11e4-9d11-c210420e5cd5.png)

**Comment by kashyap-parikh** [comment] 2015-03-02 18:12
docker info
```
[vagrant@vagrant-centos65 ~]$ sudo docker info
Containers: 1
Images: 30
Storage Driver: devicemapper
 Pool Name: docker-8:17-666002-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 7.581 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 5.005 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-431.3.1.el6.x86_64
Operating System: <unknown>
```
docker version
```
[vagrant@vagrant-centos65 ~]$ sudo docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2
[vagrant@vagrant-centos65 ~]$ 
```

**Comment by jfrazelle** [comment] 2015-03-02 18:15
ping @vbatts 

thanks for the info @kashyap-parikh

**Comment by unclejack** [comment] 2015-03-04 08:57
@kashyap-parikh Please run `yum update` to update your CentOS system and reboot it afterwards.

**Comment by unclejack** [comment] 2015-04-06 14:13
I'm going to close this issue now because it's been reported against Docker 1.3.2 and kernel 2.6.32-431. There are newer kernels available for CentOS 6.x and they can be easily installed via `yum update` and they can be used by running `reboot` to start using them.

If you can reproduce this with a fully updated system, please comment on this issue.

**Closed by unclejack** 2015-04-06 14:13 UTC
Labels: /ecosystem/centos, /system/devicemapper
