### ISSUE TITLE
<none> tag on trusted images

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#23895] opened 2016-06-23 09:06 UTC
Creating issue from this comment so it doesn't get lost:

https://github.com/docker/docker/pull/20844#issuecomment-203832875

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-88-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.32 GiB
Name: jessfraz0.mtv.corp.google.com
ID: BPTB:U7XD:VW52:AJAW:XBCR:SG2X:SUPL:JJMW:G4UI:LRAC:NQZH:NVGV
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
```
jessfraz at jessfraz0 in ~/go on 16156-parse-empty-template-twice
$ export DOCKER_CONTENT_TRUST=1

jessfraz at jessfraz0 in ~/go on 16156-parse-empty-template-twice
$ docker pull alpine
Using default tag: latest
Pull (1 of 1): alpine:latest@sha256:ea0d1389812f43e474c50155ec4914e1b48792d420820c15cab28c0794034950
sha256:ea0d1389812f43e474c50155ec4914e1b48792d420820c15cab28c0794034950: Pulling from library/alpine
fae91920dcd4: Pull complete 
Digest: sha256:ea0d1389812f43e474c50155ec4914e1b48792d420820c15cab28c0794034950
Status: Downloaded newer image for alpine@sha256:ea0d1389812f43e474c50155ec4914e1b48792d420820c15cab28c0794034950
Tagging alpine@sha256:ea0d1389812f43e474c50155ec4914e1b48792d420820c15cab28c0794034950 as alpine:latest

jessfraz at jessfraz0 in ~/go on 16156-parse-empty-template-twice
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              latest              f70c828098f5        2 weeks ago         4.799 MB
alpine              <none>              f70c828098f5        2 weeks ago         4.799 MB
```

**Describe the results you received:**
`<none>` tag, double images listed

**Describe the results you expected:**
Pretty 1 image

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by aaronlehmann** [comment] 2016-06-23 21:11
This is fixed in 1.12 by #23549.

**Comment by jfrazelle** [comment] 2016-06-23 21:35
dammit my bad i realize i wasnt on master now... sorry

On Thu, Jun 23, 2016 at 2:12 PM, Aaron Lehmann <notifications@github.com>
wrote:

> This is fixed in 1.12 by #23549
> <https://github.com/docker/docker/pull/23549>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/issues/23895#issuecomment-228185015>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbJc3GU7LqbUygxCFZtnX2wFPlikvks5qOvbHgaJpZM4I8mS9>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Closed** 2016-06-23 21:35 UTC
Labels: version/1.11

**Comment by aaronlehmann** [comment] 2016-06-23 21:39
No worries... appreciate that you made it clear it was a 1.11.2 bug report :).

**Comment by jfrazelle** [comment] 2016-06-23 21:48
LOL WOW

On Thu, Jun 23, 2016 at 2:41 PM, Aaron Lehmann <notifications@github.com>
wrote:

> No worries... appreciate that you made it clear it was a 1.11.2 bug report
> :).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/issues/23895#issuecomment-228192606>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbJBZi921QzuNCgkV7bKfEWDdw2fLks5qOv19gaJpZM4I8mS9>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thaJeztah** [comment] 2016-06-28 05:27
@jfrazelle perhaps we should switch from SemVer to Epoch for versioning? :trollface:

**Comment by jfrazelle** [comment] 2016-06-28 05:35
Oh greetings sure 0:)

On Monday, June 27, 2016, Sebastiaan van Stijn <notifications@github.com>
wrote:

> @jfrazelle <https://github.com/jfrazelle> perhaps we should switch from
> SemVer to Epoch for versioning? [image: :trollface:]
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/issues/23895#issuecomment-228951819>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbCEgoib5NbixIq1LD9lr2PLM5Bo_ks5qQLEZgaJpZM4I8mS9>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thaJeztah** [comment] 2016-06-28 05:41
"You're version is more than 3600 seconds old, that like sooooooo last hour"

**Comment by lucasvc** [comment] 2016-12-20 09:17
I've reproduced this issue with:
````
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64
````
But I wanted to delete those '<none>' tagged images, without having to delete the original one, but I can't. Tested

    $ docker rmi my-image:<none>
    bash: syntax error near unexpected token `newline'

    $ docker rmi "my-image:<none>"
    Error response from daemon: Error parsing reference: "my-image:<none>" is not a valid repository/tag

    $ docker rmi my-image:\<none\>
    Error response from daemon: Error parsing reference: "my-image:<none>" is not a valid repository/tag

**Comment by thaJeztah** [comment] 2016-12-20 10:14
@lucasvc the `<none>` tag is not an actual tag, and only there to show that there's no tag present. This can also happen if you pull an image by "digest", for example;

```
docker pull alpine@sha256:1354db23ff5478120c980eca1611a51c9f2b88b61f24283ee8200bf9a54f2e5c
```

After pulling that image, it will appear as;

```
REPOSITORY                 TAG                                    IMAGE ID            CREATED             SIZE
alpine                     <none>                                 baa5d63471ea        2 months ago        4.8 MB
```

But if you add the `--digests` option, you'll see that a digest ("immutable identifier") is present;

```
$ docker images --digests

REPOSITORY                 TAG                                    DIGEST                                                                    IMAGE ID            CREATED             SIZE
alpine                     <none>                                 sha256:1354db23ff5478120c980eca1611a51c9f2b88b61f24283ee8200bf9a54f2e5c   baa5d63471ea        2 months ago        4.8 MB
```

You can remove these images through their `ID`;

```
$ docker rmi baa5d63471ea

Untagged: alpine@sha256:1354db23ff5478120c980eca1611a51c9f2b88b61f24283ee8200bf9a54f2e5c
Deleted: sha256:baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3
```

Or through the digest;

```
$ docker rmi alpine@sha256:1354db23ff5478120c980eca1611a51c9f2b88b61f24283ee8200bf9a54f2e5c
Untagged: alpine@sha256:1354db23ff5478120c980eca1611a51c9f2b88b61f24283ee8200bf9a54f2e5c
Deleted: sha256:baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3
```

**Comment by lucasvc** [comment] 2016-12-20 12:36
The problem is that I was seeing:
````
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
my-image                  latest              75726c5c212d        3 hours ago         915.4 MB
my-image                  <none>              75726c5c212d        3 hours ago         915.4 MB
````
After upgrading my docker client to the last version, I don't see anymore those `<none>` images.
