### ISSUE TITLE
docker swarm fails to retrive node details. Throws  "404 page not found"

### ISSUE THREAD

**Issue by tarinidash** [docker/docker#29085] opened 2016-12-02 20:28 UTC
I am able to perform most of the commands on swarm except node. Not sure what I am missing here.

*docker -H :4000 pull, stop, start, rmi, rm, ps, network, commands works perfectly fine , without any issue.* 

uname -a
=======
*Linux <hostname> 3.10.0-327.18.2.el7.x86_64 #1 SMP Fri Apr 8 05:09:53 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux*

docker -H :4000 node ls
==================
*Error response from daemon: 404 page not found*

docker version
===========
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

docker -H :4000 info
===============
Containers: 26
 Running: 26
 Paused: 0
 Stopped: 0
Images: 41
Server Version: swarm/1.2.5
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 7
 host1: 10.138.128.43:2375
  └ ID: OVAQ:A73R:ALFQ:7HAM:PQYI:VA5Z:322Y:BLOO:QSPV:ZYW7:7PFT:6GHG
  └ Status: Healthy
  └ Containers: 3 (3 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.29 GiB
  └ Labels: kernelversion=3.10.0-327.18.2.el7.x86_64, operatingsystem=Red Hat Enterprise Linux Server 7.2 (Maipo), storagedriver=devicemapper
  └ UpdatedAt: 2016-12-02T20:20:23Z
  └ ServerVersion: 1.12.3
 host2: 10.138.128.45:2375
  └ ID: PPQL:BNMR:S7UH:6X5L:ZRU7:B6S2:AW7M:DMCU:KMNW:OZVJ:PBOO:AGV3
  └ Status: Healthy
  └ Containers: 4 (4 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.29 GiB
  └ Labels: kernelversion=3.10.0-327.18.2.el7.x86_64, operatingsystem=Red Hat Enterprise Linux Server 7.2 (Maipo), storagedriver=devicemapper
  └ UpdatedAt: 2016-12-02T20:20:25Z
  └ ServerVersion: 1.12.3
 host3: 10.138.128.49:2375
  └ ID: RLR6:VPVQ:KEO5:ZSEN:VTHF:A34Y:236R:DLGL:PZ6N:4U5B:6CI7:IGQB
  └ Status: Healthy
  └ Containers: 3 (3 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.29 GiB
  └ Labels: kernelversion=3.10.0-327.18.2.el7.x86_64, operatingsystem=Red Hat Enterprise Linux Server 7.2 (Maipo), storagedriver=devicemapper
  └ UpdatedAt: 2016-12-02T20:20:29Z
  └ ServerVersion: 1.12.3
 host4: 10.138.128.52:2375
  └ ID: IWO3:ZTZT:A22D:PHMU:UDMV:QSFK:GII7:GP64:6PR4:7MPS:EPAY:6TBV
  └ Status: Healthy
  └ Containers: 3 (3 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.29 GiB
  └ Labels: kernelversion=3.10.0-327.18.2.el7.x86_64, operatingsystem=Red Hat Enterprise Linux Server 7.2 (Maipo), storagedriver=devicemapper
  └ UpdatedAt: 2016-12-02T20:20:05Z
  └ ServerVersion: 1.12.3
 host5: 10.138.128.53:2375
  └ ID: LLQS:223T:LZUT:LZGZ:BVNV:TIS7:LK3O:GUGA:EWBZ:BLZ6:2LXL:3RAV
  └ Status: Healthy
  └ Containers: 3 (3 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.29 GiB
  └ Labels: kernelversion=3.10.0-327.18.2.el7.x86_64, operatingsystem=Red Hat Enterprise Linux Server 7.2 (Maipo), storagedriver=devicemapper
  └ UpdatedAt: 2016-12-02T20:20:35Z
  └ ServerVersion: 1.12.3
 host6: 10.138.128.54:2375
  └ ID: KT5I:7JEF:LQ5W:QCBH:NY7X:S3FA:C6UD:QXDY:C4AB:7RXO:XCZQ:CXLG
  └ Status: Healthy
  └ Containers: 5 (5 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.29 GiB
  └ Labels: kernelversion=3.10.0-327.18.2.el7.x86_64, operatingsystem=Red Hat Enterprise Linux Server 7.2 (Maipo), storagedriver=devicemapper
  └ UpdatedAt: 2016-12-02T20:20:43Z
  └ ServerVersion: 1.12.3
 host7: 10.138.128.55:2375
  └ ID: THDB:T5EC:C7JF:XYGH:ZV7Q:X47S:OTNT:DZUI:JXGM:NMQX:DXFO:SFPK
  └ Status: Healthy
  └ Containers: 5 (5 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.29 GiB
  └ Labels: kernelversion=3.10.0-327.18.2.el7.x86_64, operatingsystem=Red Hat Enterprise Linux Server 7.2 (Maipo), storagedriver=devicemapper
  └ UpdatedAt: 2016-12-02T20:20:13Z
  └ ServerVersion: 1.12.3
Plugins:
 Volume:
 Network:
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Security Options:
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: linux
Architecture: amd64
CPUs: 28
Total Memory: 114 GiB
Name: c7ef56122f88
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support

http-proxy.conf
===========
[Service] Environment="HTTP_PROXY=http://proxy-domain.com:port" "HTTPS_PROXY=https://proxy-domain.com:port"

docker.conf
========
[Service] ExecStart= ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -g /docker --cluster-store=consul://consul-server:8500 --cluster-advertise eth0:2375

echo -e "GET /images/json HTTP/1.0\r\n" | nc -U /var/run/docker.sock
===================================================

HTTP/1.0 200 OK
Content-Type: application/json
Server: Docker/1.12.3 (linux)
Date: Fri, 02 Dec 2016 20:36:27 GMT
Content-Length: 1764

Goal
===
assign node labels on swarm, however docker -H :4000 node * fails.

**Comment by allencloud** [comment] 2016-12-03 13:35
I think your command is again docker swarm which is different  from swarm mode in docker engine.

**Comment by thaJeztah** [comment] 2016-12-03 22:33
Yes, it looks like you're mixing "classic" swarm (https://docs.docker.com/swarm/), with the new swarm mode that was introduced in docker 1.12 (https://docs.docker.com/engine/swarm/)

I'll close this issue because this is not a bug, but happy to answer questions you may have

**Closed by thaJeztah** 2016-12-03 22:33 UTC
Labels: area/swarm, version/1.12

**Comment by tarinidash** [comment] 2016-12-04 02:32
Thank you all . I think its answers my question. I will upgrade my infrastructure to new swarm mode and update my findings here.

**Comment by tarinidash** [comment] 2016-12-07 19:05
Confirm docker node * works on swarm mode.
