### ISSUE TITLE
Cannot docker kill the contain

### ISSUE THREAD

**Issue by zh19970205** [docker/docker#19829] opened 2016-01-29 10:29 UTC
when i run ```rm -rf / --no-preserve-root``` in the container
then i cannot ```docker kill``` the container neither ```kill``` the process ```rm```
PS : the process ```rm``` keep the state "R" according to ```ps aux```
and the CPU usage keep 50%

**Comment by qq690388648** [comment] 2016-02-03 06:31
What is the version of your docker and os?
My docker 1.9.1 on Ubuntu 12.04 worked well with your operation.

**Comment by unclejack** [comment] 2016-03-04 19:33
@zh19970205 Please provide the output of `docker info` and `docker version`.

**Comment by ehazlett** [comment] 2016-09-26 16:35
I cannot reproduce this either.  I'm going to close this.  Please open a new issue if you continue to experience this behavior.  Thanks!

**Closed by ehazlett** 2016-09-26 16:35 UTC
Labels: status/more-info-needed
