### ISSUE TITLE
Feature Request: Allow a container to start in multiple networks

### ISSUE THREAD

**Issue by erkules** [docker/docker#22314] opened 2016-04-25 19:00 UTC
It would be good to be able to start a container in more than one (named) network.
Like:

`docker run --net one --net two container `

So the process in the container starts with the two (or more) additional interfaces. 
A `docker network connect` breaks most workflows and the additional interface is often ignored by the process;

In the beginning `--name --net-alias` would be the same in all networks. 
If wanted a way to set i.e. a different `--net-alias` following could be done.
`--net-alias` of every `--net` sets the default alias.
This default can be overwritten, when `--net-alias` is set after `--net`

Examples:

Same alias in all networks:
`
docker run --net-alias ahab --net one --net two --net three ..
`
Change the default alias in network two only:
`
docker run --net-alias ahab --net one --net two --net-alias moby  --net three ..
`

**Comment by thaJeztah** [comment] 2016-04-25 22:02
Thanks for suggestion, but this is a duplicate of https://github.com/docker/docker/issues/17289 and  https://github.com/docker/docker/issues/17750. unfortunately, this is not possible, as explained in https://github.com/docker/docker/pull/17796#issuecomment-162612624, so I'll have to close this, but feel free to comment after I closed.

**Closed by thaJeztah** 2016-04-25 22:02 UTC
Labels: group/networking
