### ISSUE TITLE
[1.12.0-rc3] docker swarm mode supprt HA

### ISSUE THREAD

**Issue by liuliuzi** [docker/docker#24577] opened 2016-07-13 06:41 UTC
Does docker swarm mode supprt high availability?  could be multi-manager in one cluster?

**Comment by vitan** [comment] 2016-07-13 07:13
sure. Plz join your node into the cluster as **manager** role

```bash
docker swarm join --manager --listen-addr $(hostname -i):2377 $FIRST_MANAGER_IP:2377
```

**Comment by thaJeztah** [comment] 2016-07-13 12:56
initial docs for Swarm mode is here; https://docs.docker.com/engine/swarm/, but a section on high-availability and multiple managers is not yet there

ping @sfsmithcha

**Comment by sfsmithcha** [comment] 2016-07-13 18:18
This is a dupe of https://github.com/docker/docker/issues/24109

Like all docs, this is a WIP. Docs for adding manager nodes to a swarm are specifically blocked by acceptance policy UX.

While that is being sorted out, here is a basic draft summary of running multiple managers:

```
If you require fault-tolerance in case of a manager failure, you should maintain
an odd number of managers. Docker recommends either three or five manager nodes
according to your organizations high-availability requirements:

* A three-manager swarm tolerates a maximum loss of one manager.
* A five-manager swarm tolerates a maximum simultaneous loss two manager nodes.
* In general, an `N` manager cluster will tolerate the loss of at most `N/2`
managers.
* Seven is the maximum possible number of manager nodes for a swarm.
```

**Closed by sfsmithcha** 2016-07-13 18:18 UTC
Labels: area/swarm, kind/docs, kind/question
