### ISSUE TITLE
Downgrade from 1.7 to 1.6 doesn't work

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#13695] opened 2015-06-03 07:46 UTC
Before going into exactly what is failing I have to first ask the question whether this is supported.  If a user upgrades to 1.7 and then downgrade to 1.6, should things still work?  I would say yes they should as that has always seemed to work in the past.  With 1.7 I'm getting errors now.  Basically after reverting back to 1.6 I get errors like:

```time="2015-06-03T07:43:11Z" level=fatal msg="reflect: call of reflect.Value.Type on zero Value" ```

**Comment by ibuildthecloud** [comment] 2015-06-03 07:52
So, just to throw this out there.  Not being able to downgrade from 1.7 to 1.6 breaks CoreOS and RancherOS.  I have a slightly vested interest in this working in RancherOS :)

The reason it breaks these OSs (I assume same applies RHEL atomic, Ubuntu Snappy, VMware Photon) is that they are all based on the idea of seamless atomic upgrade and downgrade.  But If I upgrade to a new OS version that includes 1.7 and then decide I want to downgrade to the previous, thinks won't work because the `/var/lib/docker` state has been migrated to a format that is incompatible with 1.6.

**Comment by thaJeztah** [comment] 2015-06-03 13:17
ping @vieux @jfrazelle for regression in 1.7

**Comment by cpuguy83** [comment] 2015-06-03 13:48
I could definitely see this being an issue with volumes as well...

**Comment by jfrazelle** [comment] 2015-06-03 16:30
thanks for breaking shit darren, we always appreciate it :D (not sarcastic, totally serious)

**Comment by duglin** [comment] 2015-06-03 16:50
@ibuildthecloud how can I reproduce this? I switch between 1.7 and 1.6 a lot (usually when my 1.7 build fails to build) and I've never seen this.  What command were you running to see that error msg?

**Comment by ibuildthecloud** [comment] 2015-06-03 17:29
@duglin I'll send work on test case to reproduce.  Honestly, when I put Docker 1.7 into a lot of my environments stuff blows up and then chaos ensues so I haven't had controlled tests.  Didn't know if you guys cared about this one.

**Comment by calavera** [comment] 2015-06-03 17:44
A test to reproduce this would be lovely. So far, I've only found issues with missing volumes because the json document didn't include the old structures. But I haven't seen that value error yet.

**Comment by duglin** [comment] 2015-06-03 17:46
@ibuildthecloud does it blow up during daemon startup or only once you start to do something?

**Comment by calavera** [comment] 2015-06-03 18:13
@crosbymichael pointed out on IRC that this has never been guaranteed:

![image](https://cloud.githubusercontent.com/assets/1050/7967810/76d17e4e-09e1-11e5-8716-a22a6eee0264.png)

I'm okay with merging the volumes PR. I'm also okay with not merging it. But it's worth to keep in mind that this is not a regression then.

**Comment by duglin** [comment] 2015-06-03 18:19
I wouldn't mind a little bit of investigation to see why things are breaking - just to make sure its not exposing a hidden bug.

**Comment by calavera** [comment] 2015-06-03 18:34
I don't think the cause of that `time="2015-06-03T07:43:11Z" level=fatal msg="reflect: call of reflect.Value.Type on zero Value"` error is related with volumes, fwiw. Downgrading containers with bind mounts from 1.7 to 1.6 doesn't raise it.

**Comment by icecrime** [comment] 2015-06-03 20:35
As discussed on IRC, it's worth going down the rabbit hole and understand when this error comes from. However, downgrading being not guaranteed, I'm going to remove this from the milestone (not a regression).

**Comment by ibuildthecloud** [comment] 2015-06-03 22:33
fyi, still getting to reproducting this.  i've got a queue of other bugs been working through this afternoon.  it would be really nice if this worked

**Comment by ibuildthecloud** [comment] 2015-06-04 22:38
Okay, I got to the bottom of this.  Basically I was doing an `inspect -f '{{...}}'` on a volume field that is null after downgrade.  So basically with 1.7 downgrade is 100% not supported.  If you were to do 1.6, upgrade to 1.7, downgrade to 1.6 containers don't work because the Volume info is missing/wrong.  If you then upgrade again 1.7 they still don't work because the Volume metadata is forever lost.

**Comment by ibuildthecloud** [comment] 2015-06-04 22:47
@icecrime I'd reconsider supporting downgrades.  As Docker enters the enterprise seemingly stupid and annoying requirements like this are important to a lot of people.  Basically what you are telling ops teams now is that before rolling out a Docker upgrade you must backup the entire /var/lib/docker on every server before doing the upgrade because there is no rollback.  And, as I mentioned before, you are breaking the concept of atomic upgrades for OS.  CoreOS and RHEL Atomic exist largely because of Docker, and you are now essentially breaking the mode you helped create.

Trust me, I absolutely know how much it sucks to support this.  But.... If you want to be a critical part of enterprise infrastructure you have to support annoying things like this.

**Comment by thaJeztah** [comment] 2015-06-05 07:04
Sounds like a valid concern to me

**Comment by duglin** [comment] 2015-06-05 12:52
> Okay, I got to the bottom of this. Basically I was doing an inspect -f '{{...}}' on a volume field that is null after downgrade. 

Which field?  Perhaps this null-ing out is a bug.

**Comment by duglin** [comment] 2015-06-05 13:53
Also, do you have a testcase (or steps) I can follow to try to reproduce it?

**Comment by calavera** [comment] 2015-06-05 16:42
@duglin, @ibuildthecloud I'm pretty sure #13699 fixes that issue.

**Comment by icecrime** [comment] 2015-06-10 02:51
Closed by #13699.

**Closed by icecrime** 2015-06-10 02:51 UTC
