### ISSUE TITLE
Working directory appended before path

### ISSUE THREAD

**Issue by sascha-andres** [docker/docker#24680] opened 2016-07-15 11:22 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 40
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: STE4:UZYU:RW6Y:ZQKO:BP4E:6CZF:MAK4:YQTZ:WE5B:5TXL:CUGH:LPEV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical Windows 10

**Steps to reproduce the issue:**
I created an image on linux where I mount a folder to the /configs folder. I created a shell script on linux that basically does this"

```
#! /bin/bash

HOST=`hostname`
MQ_USER=user
MQ_PASS=pass
CONFIG_PATH=$PWD/configs

docker pull registry/berlitz/generator:latest
docker run -v /$CONFIG_PATH://configs registry/berlitz/generator:latest -config /configs/dev.yml -type rabbitmq -host $HOST -user $MQ_USER -password $MQ_PASS
```

Running on linux this works. On Windows I am using the bash installed by git. On Linux I do see the expected output from the program within the docker image on Windows I get an error

**Describe the results you received:**

Instead of the program working correctly, I get the following error:
```
2016/07/15 11:19:33 stat C:/Program Files/Git/configs/dev.yml: no such file or directory
```
It seems the program within the container has the working path of the bash which called the wrapper script

**Describe the results you expected:**

The program finding the mounted directory

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens reproducible

**Comment by sascha-andres** [comment] 2016-07-15 12:43
Just more information. I have Shared my C drive in settings. And I have tried to run the provided sample:
```
docker run -v c:/Users:/data alpine ls /data
```
The output of this command is:
```
$ docker run -v c:/Users:/data alpine ls /data
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
e110a4a17941: Pull complete
Digest: sha256:3dcdb92d7432d56604d4545cbd324b14e647b313626d99b889d0626de158f73a
Status: Downloaded newer image for alpine:latest
ls: C:/Program Files/Git/data: No such file or directory
```

**Comment by thaJeztah** [comment] 2016-07-15 12:48
That's a known issue ("feature") of mingw. mingw is trying to be smart. See https://github.com/docker/docker/issues/13741#issuecomment-128893740, and http://www.mingw.org/wiki/Posix_path_conversion

you can try using `-config //configs/dev.yml` (double slash)

**Comment by thaJeztah** [comment] 2016-07-15 12:51
Anyway, this is not a bug in docker, and not something we can change, so I'll close this issue, but feel free to comment after I closed

**Closed by thaJeztah** 2016-07-15 12:51 UTC
Labels: group/windows, version/1.12
