### ISSUE TITLE
Named and portable volumes

### ISSUE THREAD

**Issue by mxbossard** [docker/docker#8424] opened 2014-10-06 20:14 UTC
I think volumes need to be portable. Why not offering the possibility to name volumes and mount it on a container, instead of having to use de --volumes-from option to mount all volumes of a particular container ?

If volumes was named, we could easilly snapshot it (see https://github.com/docker/docker/issues/7127), migrate it on other host if needed, and mount it on freshly rebuild containers.

I think it would be a more elegant and portable solution than the data container pattern. Indeed, we are currently forced to build not running data container, to share volumes between other containers. Eventually, this data container is not portable because we cannot move it to another host keeping its volumes attached.

**Comment by jfrazelle** [comment] 2015-02-26 00:34
closing as duplicate of https://github.com/docker/docker/issues/8363

**Comment by jfrazelle** [comment] 2015-02-26 00:35
also see #7249

**Closed by jfrazelle** 2015-02-26 00:34 UTC
