### ISSUE TITLE
When mapping too many ports then daemon failed

### ISSUE THREAD

**Issue by xczh** [docker/docker#22614] opened 2016-05-09 19:08 UTC
I wonder that if docker has limit on the max number of port-mapping.

when I exec this:
```sh
docker run -p 51000-52000:51000-52000 hello-world
```
then, the output is:

>docker: Error response from daemon: driver failed programming external connectivity on endpoint jovial_fermat (5d77c1cc0c4866dc8266ee2dfecf576703397179a2ec481f0cba4807ed5f5908): fork/exec /proc/self/exe: resource temporarily unavailable.

sometime is:
>docker: Error response from daemon: driver failed programming external connectivity on endpoint grave_roentgen (9418647aba299043fba3b1b52ecc44d8561e49c95c857f5befed83bd6677bff5): Error starting userland proxy:.

And what's worse is, this issue happened unscheduled on my workstation, which runs about 20 containers. It cause `HTTP 502 Bad GateWay` Error, but I cannot exec into the container, and also cannot start or restart the crashed container. The only way to resolve this is to restart docker daemon, and maybe few hours later, the error occur again.

I have run this command on docker 1.9.0:
```sh
docker run -p 51000-52000:51000-52000 hello-world
```
and It works out find, no error occur.
I feel really confused, and hope to find out why. 
Thanks a lot!

**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 49
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-8:66-8913761-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.18 GB
 Data Space Total: 107.4 GB
 Data Space Available: 96.2 GB
 Metadata Space Used: 14.29 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.133 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.122 (2016-04-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.4 GiB
Name: NAME
ID: ZCBT:7XES:7S67:TVRR:BEJE:G7FY:DMP3:BN3D:76P5:7IDZ:PNQ4:TV26
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
(mentioned above)

**Describe the results you received:**
Error message (mentioned above)

**Describe the results you expected:**
The container start successfully, and won't crashun scheduled.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-05-09 19:17
There's no limit on the number of ports exposed, however the user land proxy can use a lot of RAM in this case (see https://github.com/docker/docker/issues/11185). It's possible to disable the userland proxy using the [`--userland-proxy=false`](http://docs.docker.com/reference/commandline/daemon/) daemon option, or by setting this option in a [`daemon.json`](https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file) configuration file, however, it's known to result in some stability issues with some kernels, so YMMV.

**Comment by xczh** [comment] 2016-05-10 07:12
@thaJeztah
Thanks for your suggestion. You mean the error previously mentioned is because of userland-proxy use too much memory? But the total memory is 31.4 GiB...

And why I can do this on `docker-1.9.1` without error? It's default behavior is user-land proxy disabled?

```sh
docker run -p 51000-52000:51000-52000 hello-world
```

Thanks for your help again!

**Comment by thaJeztah** [comment] 2016-05-10 09:31
>  But the total memory is 31.4 GiB...

Oh! Yes, I don't assume it will take *that much* memory. Let me see if I can reproduce. Did you also run Docker 1.10 in between upgrading from 1.9 to 1.11? Wondering if this is a regression since 1.10, or was already an issue in that version.

**Comment by xczh** [comment] 2016-05-10 11:02
Yes, I have also run `Docker 1.10` indeed. And this problem never occur until we upgrade Docker 1.10. From `1.10` version this problem start to appear. Could you give me the issue link about "already an issue in that version" ?

**Comment by thaJeztah** [comment] 2016-05-10 11:06
Alright, I spun up a fresh Ubuntu 16.04 droplet with 2GB RAM on DigitalOcean.

First run indeed gave me `/sbin/iptables: resource temporarily unavailable`;

```bash
docker run -p 51000-52000:51000-52000 hello-world
docker: Error response from daemon: driver failed programming external connectivity on endpoint elated_goldberg (b6654c313baa441caa407bb48a1f53764d560265590ab19a9d13965ce3b378dd): iptables failed: iptables --wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 51911 -j MASQUERADE:  (fork/exec /sbin/iptables: resource temporarily unavailable).
```

Given that Ubuntu 16.04 uses systemd 229, this may be due to systemd setting a
really low "TasksMax", so I created a drop-in file to override this default:

```bash
sudo mkdir -p /etc/systemd/system/docker.service.d/

sudo tee /etc/systemd/system/docker.service.d/tasksmax.conf <<-'EOF'
[Service]
TasksMax=infinity
EOF


sudo systemctl daemon-reload
sudo systemctl restart docker
```

Trying again, this time it got further, but ran out of memory; `/sbin/iptables: cannot allocate memory`;

```bash
docker run -p 51000-52000:51000-52000 hello-world
docker: Error response from daemon: driver failed programming external connectivity on endpoint stupefied_booth (6329026e7613c28d46240b89a61ad565bc69a28a44e5a4b2cfc314eac57b3ef1): iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 51671 -j ACCEPT:  (fork/exec /sbin/iptables: cannot allocate memory).
```

Disabling the userland-proxy resolves that;

```bash
echo "{\"userland-proxy\":false}" > /etc/docker/daemon.json
sudo systemctl restart docker
```


Downgrading docker to 1.10.3 (using the Wily package, because there's no 1.10 package for Xenial);

```bash
docker run -p 51000-52000:51000-52000 hello-world
docker: Error response from daemon: failed to create endpoint distracted_hoover on network bridge: Timed out proxy starting the userland proxy.
```

Downgrading docker to 1.9.1 gave me the same result. The userland-proxy clearly uses up
all memory.


**Memory footprint in each release**

To see if the memory footprint of the userland-proxy changed between versions, I
upgraded the Droplet to a 32GB machine. I used `nginx:alpine` for this, and just
looked at `htop`, subtracting the memory used in "idle" state so it's really a "rough" estimation;

    docker run -d --name=bench -p 51000-52000:51000-52000 nginx:alpine


docker version | max memory | no proxy | --net=host
---------------|------------|----------|------
1.9.1 | 6.6GB | ~10MB | < 10MB
1.10.3 | 10.5GB | ~10MB | < 10MB
1.11.1 | 6.0GB | ~10MB | < 10MB


Interestingly, there's a bump in memory usage in Docker 1.10, but 1.11 is actually
more memory efficient here. Still it's clear that the userland-proxy is a memory
hog when publishing a large port range.


**Concluding**

- If you're running systemd > 226, set `TasksMax=infinity`
- The userland-proxy is a memory hog. Avoid it, if possible
- If possible, use `--userland-proxy=false` (YMMV)
- Even faster, use `--net=host` but be aware of the consequences (you're using
  the host's network stack), and you probably need to add a custom IPtables rule
  to expose the ports.

**Comment by thaJeztah** [comment] 2016-05-10 11:07
ping @mavenugo @aboch perhaps you have other recommendations here?

**Comment by xczh** [comment] 2016-05-10 11:38
@thaJeztah 
Thank you very much !!!

As you said, I used `systemd 229`, and TaskMax default is 512. This may too low for running 30+ containers. And follow your steps, now I can expose many ports.

About the problem of the unscheduled crash of the container, I will observe a period of time to see if problem reappears.

**Comment by thaJeztah** [comment] 2016-05-10 12:26
Glad I could help!

t.b.h., I knew the userland-proxy was a memory hog, but these numbers surprised me as well. We really would like to get rid of it, and for many users `--userland-proxy=false` works without issues. For some situations, it causes issues (depending on kernel version and distro), so we cannot make it the default.

Using `--net=host` may be a good alternative for this case, but as mentioned, there are some risks involved (e.g. doing `reboot` inside a container will actually signal the host to reboot :wink:).

I'll close this issue, because we are aware of the "userland-proxy" issue in general, and track if through https://github.com/docker/docker/issues/11185, but if you think additional documentation would be useful, I'm happy to hear. Also, feel free to continue the discussion after I closed.

**Closed by thaJeztah** 2016-05-10 12:26 UTC
Labels: group/networking
