### ISSUE TITLE
DfW: all my images are gone

### ISSUE THREAD

**Issue by rlpowell** [docker/docker#29164] opened 2016-12-06 05:54 UTC
**Description**

I rebooted, and all my images are gone

**Steps to reproduce the issue:**

I'm sorry, I have no idea; I've been hacking on Docker For Windows every day for months, and this is a first.

**Describe the results you received:**

I was having trouble deleting files shared from my Windows disks to my Linux docker instance, and so I rebooted.  When I finished, "docker images -a" shows only d4w/nsenter

**Describe the results you expected:**

To have a bunch of images available.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.0-rc2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.10-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.407 GiB
Name: moby
ID: HA37:CLED:52XW:XN4W:CW2C:DKM6:Z6BU:SESN:YWFW:R3G6:ZCPF:OAJI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2016-12-06 09:24
Since this is specific to docker for Windows, can you report this in the d4w issue tracker? https://github.com/docker/for-win/issues

> I was having trouble deleting files shared from my Windows disks to my Linux docker instance, and so I rebooted. When I finished, "docker images -a" shows only d4w/nsenter

It may be worth explaining what you did and what exactly you tried to do. Note that files shared from your how (using, e.g. `-v c:\Users\myname:/somewhere`) are not _copied_ to the VM, so you don't have to clean those up.


I'll close this issue here, because this is not a bug in docker "engine", so is best reopened in the docker for Windows issue tracker

**Closed by thaJeztah** 2016-12-06 09:24 UTC
Labels: platform/desktop, version/1.13

**Comment by rneugeba** [comment] 2016-12-06 09:36
@rlpowell there is https://github.com/docker/for-win/issues/290
we can't reproduce it but others have reported it.

If you have a concrete repro, that would be appreciated

**Comment by rlpowell** [comment] 2016-12-06 15:49
Ah, sorry, I couldn't find the for-win tracker, thanks.

**Comment by rlpowell** [comment] 2016-12-06 15:51
WRT the disk file clean up: it frequently occurs that files in the shared disk space become undeletable, even in windows, until I reboot.  I assumed this was a known side effect of however the file sharing works, since it happens to me almost daily, so I didn't bother to report it, because I don't think you guys have control over the file sharing layer.  If I should report it, though, let me know.
