### ISSUE TITLE
Volume data synchronization lost when host time is changed

### ISSUE THREAD

**Issue by JaviSabalete** [docker/docker#26962] opened 2016-09-27 19:35 UTC
**Description**

Volume data synchronization lost when host time is changed.

**Steps to reproduce the issue:**
1. Start container with volume data between container and host.
2. Check if changes on shared folder on host are ready on container, should be fine.
3. Change host time (e.g. 10:35AM (real time) to 8:00AM)
4. Do some changes on shared folder on host
5. Check if changes on shared folder on host are ready on container

**Describe the results you received:**

The changes realized after the time changed aren't ready on container.

**Describe the results you expected:**
Works independently if host time is changed.

**Additional information you deem important (e.g. issue happens only occasionally):**
Tt happens always when host time is changed.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 25
 Running: 23
 Paused: 0
 Stopped: 2
Images: 13
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 693
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.773 GiB
Name: jsabalete
ID: RATL:WLNB:U4UQ:V5XX:JG77:D4HJ:HBBM:HJU2:CHNZ:U6B5:JAMG:ZN4L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical computer.

**Fix:**

Just after time is changed, restart containers. This problem just happens when containers aren't restarted.

**Comment by thaJeztah** [comment] 2016-09-27 20:10
Which commands do you use to check if "The changes realized after the time changed aren't ready on container."? Do you `docker exec` into the container? Can you provide the exact steps to reproduce?

When running docker on linux, using a bind-mounted directory, to share a directory on the host with the container, there's basically _nothing_ in between the files and the container, it literally is the host-directory mounted inside the container, so file changes from both sides (container/host) should be picked up immediately.

**Comment by JaviSabalete** [comment] 2016-09-27 21:07
> Which commands do you use to check if "The changes realized after the time changed aren't ready on container."? Do you docker exec into the container? Can you provide the exact steps to reproduce?

Yes. I execute this command exactly:
```docker exec -ti ID_CONTAINER bash```

Into container, go to /var/www/html to check changes. This is the mounted directory.

> When running docker on linux, using a bind-mounted directory, to share a directory on the host with the container, there's basically nothing in between the files and the container, it literally is the host-directory mounted inside the container, so file changes from both sides (container/host) should be picked up immediately.

I can try to explain better

We are using docker to execute web project with same os, software versions, etc that production environment. 

So container has apache2 running and I test web from host (http://containerip)
Works fine, we work on host with php ides like netbeans or php storm and test it on docker. 
In fact, apache2 container mount shared-storage volume as a data volume and this last one mount the host directory as a data volume.
So the final container schema is:
apache2 container -> mount shared-storage on /var (/var/www)
shared-storage container -> mount host directory on /var/www (e.g. /var/www/html)

This is an example:

```
"Mounts": [
            {
                "Name": "7925d0021826046fdc88634ba00cca60d5c19d08fdc0f34e451d5f40ec8a592c",
                "Source": "/var/lib/docker/volumes/7925d0021826046fdc88634ba00cca60d5c19d08fdc0f34e451d5f40ec8a592c/_data",
                "Destination": "/var/www",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Source": "/media/javi/HDD/web",
                "Destination": "/var/www/html",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

I have links to another containers like mysql from apache2 but I think isn't relevant now.

The problem:
When time on host is changed and I changed some file in host directory (/media/javi/HDD/web) and I refresh browser (http://containerip) changes aren't ready. I can enter to container with command at the top and read files in /var/www/html but changed files are different than files in /media/javi/HDD/web on host, they haven't changes.

Sorry for my english, isn't my mother tongue

**Comment by thaJeztah** [comment] 2016-09-27 21:24
> Sorry for my english, isn't my mother tongue

Absolutely no need to apologize, native is not my mother tongue either, and so far you're doing fine!

I see two possible issues here;

First of all, I see that the container has _two_ volumes; one "anonymous" volume, mounted at `/var/www` in the container, and one bind-mounted volume, mounted at `/var/www/html`. Because those volumes overlap, it's possible that one volume is mounted over the other volume, and you may actually be looking at the files that are in the "anonymous" volume, not in the bind-mounted directory from the host.

The `/var/www` volume is probably defined in your Dockerfile / image, which makes it a bit harder to disable that. If the image you're using is one you created yourself, you can remove the `VOLUME` instruction from the Dockerfile (and set the volume at runtime, with `-v /var/www` when needed.

Alternatively, you can change the directory structure on your host (i.e., so that the files are in `/media/javi/HDD/web/html`, and bind-mount it at `/var/www`; (`-v /media/javi/HDD/web:/var/www`).


The _second_ (possible) issue could be if `sendfile` is enabled in your Apache configuration. Usually, that caused issues with boot2docker installs, but it's worth a try if disabling it makes a difference (see the discussion on https://github.com/docker/docker/issues/15793)

**Comment by thaJeztah** [comment] 2016-10-29 07:51
Closing as I think the question is answered, but feel free to comment if you still have an issje

**Closed by thaJeztah** 2016-10-29 07:51 UTC
Labels: status/more-info-needed, version/1.12
