### ISSUE TITLE
using docker client 1.8.3 to run `exec` against a docker daemon built from master fails

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#17288] opened 2015-10-23 01:06 UTC
Client: 1.8.3

Daemon built from: 37da495d4cf30bebb17397dd9e103e6d3e74fe08

Command: `docker exec -it name bash`

Error:
```
Content-Type specified (text/plain) must be 'application/json'
```

**Comment by thaJeztah** [comment] 2015-10-23 02:25
Looks like that's caused by https://github.com/docker/docker/pull/17125

@tibor @calavera should this behavior be versioned?

**Comment by thaJeztah** [comment] 2015-10-23 02:36
Adding this to the milestone for now

**Comment by cpuguy83** [comment] 2015-10-23 02:45
This is not an issue in 1.9 afaict

**Comment by thaJeztah** [comment] 2015-10-23 02:55
Thanks @cpuguy83 oh, good catch, it was merged after 1.9rc.

**Comment by calavera** [comment] 2015-10-23 16:35
The only reason why you can use a docker 1.8.3 client to talk with a daemon build from master is because we don't bump the api version in master until the release. We have a middleware in the api that prevents from using old docker cli versions with new api versions. The cli in master works as expected with the api in master, you should use that cli if you want to talk with a daemon build from master.

Thanks for reporting it, but this is not an issue. Closing.

**Comment by cpuguy83** [comment] 2015-10-23 16:40
No, that's not right. We block newer clients from talking to old daemons.

**Comment by cpuguy83** [comment] 2015-10-23 16:40
And the api version should be bumper already from 1.8 to master

**Comment by calavera** [comment] 2015-10-23 16:51
okay, versioning in #17313

**Closed** 2015-10-26 20:32 UTC
Labels: kind/bug
