### ISSUE TITLE
Trouble running docker in a lxc container created with lxd

### ISSUE THREAD

**Issue by benschw** [docker/docker#13054] opened 2015-05-07 15:04 UTC
Description of problem:

When trying to run Docker in an ubuntu trusty lxc container created with lxd (cli, not openstack) on an ubuntu vivid host (created with vagrant from a cloud-images.ubuntu.com image) I get the following error:

	# docker -d --exec-driver=lxc
	INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
	INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
	FATA[0000] Shutting down daemon due to errors: error intializing graphdriver: permission denied 

From VirtualBox host:

`docker version`:

	Client version: 1.6.0
	Client API version: 1.18
	Go version (client): go1.4.2
	Git commit (client): 4749651
	OS/Arch (client): linux/amd64
	Server version: 1.6.0
	Server API version: 1.18
	Go version (server): go1.4.2
	Git commit (server): 4749651
	OS/Arch (server): linux/amd64

`docker info`:

	Containers: 0
	Images: 0
	Storage Driver: aufs
	 Root Dir: /var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 0
	 Dirperm1 Supported: true
	Execution Driver: native-0.2
	Kernel Version: 3.19.0-15-generic
	Operating System: Ubuntu 15.04
	CPUs: 1
	Total Memory: 489.1 MiB
	Name: vagrant-ubuntu-vivid-64
	ID: LF2T:DNN2:JF5H:IMQS:S7LK:7WDA:CETE:ABRV:LLKH:APKY:75UI:AT2B
	WARNING: No swap limit support

`uname -a`:

	Linux vagrant-ubuntu-vivid-64 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

From `lxc` container

`docker version`:

	Client version: 1.6.0
	Client API version: 1.18
	Go version (client): go1.4.2
	Git commit (client): 4749651
	OS/Arch (client): linux/amd64
	FATA[0000] Get http:///var/run/docker.sock/v1.18/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 

`docker info`:

	FATA[0000] Get http:///var/run/docker.sock/v1.18/info: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 

`uname -a`:

	Linux test 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

- VirtualBox host (Ubuntu Vivid from cloud-images.ubuntu.com) running `lxd` 
- the `lxc` guest is running Ubuntu Trusty

How reproducible:

Steps to Reproduce:

1. Boot ubuntu vivid vm in VirtualBox
2. Install Docker on host (to make sure kernel has everything)
	1. wget -qO- https://get.docker.com/ | sh
3. Install Lxd Container 
	1. sudo apt-get install -y lxd
	2. sudo service lxd start
	3. sudo lxd-images import lxc ubuntu trusty amd64 --alias trusty
	4. sudo lxc launch trusty test
	5. sudo lxc exec test -- /bin/bash
4. Install Docker on lxc guest
	1. apt-get install wget
	2. wget -qO- https://get.docker.com/ | sh
5. Try to start Docker
	1. service docker start (fails)
	2. docker -d --exec-driver=lxc (fails)
	3. docker -d (fails)

Actual Results:

	docker -d --exec-driver=lxc
	INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
	INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
	FATA[0000] Shutting down daemon due to errors: error intializing graphdriver: permission denied

Expected Results:
	
	docker -d --exec-driver=lxc
	...
	INFO[0000] Daemon has completed initialization          

Additional info:

I have tried this without docker installed on the host and with it installed but not running in addition to the above "steps to reproduce." 

My thoughts were that any kernel dependencies docker needs would get sucked in on the virtualbox host by installing docker there and would be made available to the lxd guest where I actually want to run docker from.

**Comment by benschw** [comment] 2015-05-07 17:35
sorry about that, I've updated the decription

**Comment by benschw** [comment] 2015-05-08 00:24
Is this a use case docker should be concerned with? Or is it better left to the implementor to figure out.

Obviously there are any number of things that could go wrong running one opinionated lxc impl inside another, but does lxd have a critical mass such that this is a docker problem too?

**Comment by cpuguy83** [comment] 2015-05-08 00:38
@benschw Docker at the very least needs to be able to mount filesystems and manipulate networks... probably other caps as well, and need to not be confined by SELinux or AppArmor.

Docker itself already supports docker-in-docker, whoever else wants to run docker in a contained environment needs to look at that and make sure docker has the right privileges to run.

**Comment by jfrazelle** [comment] 2015-05-08 00:58
closing  as this is not a bug with docker itself

**Closed by jfrazelle** 2015-05-08 00:58 UTC
