### ISSUE TITLE
[1.12rc5] Unreliable inter-service communication after scaling down and up

### ISSUE THREAD

**Issue by Stehsegler** [docker/docker#25130] opened 2016-07-27 15:25 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 3
Server Version: 1.12.0-rc5
Storage Driver: devicemapper
 Pool Name: vg--docker-data
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 1.974 GB
 Data Space Total: 52.61 GB
 Data Space Available: 50.64 GB
 Metadata Space Used: 2.101 MB
 Metadata Space Total: 532.7 MB
 Metadata Space Available: 530.6 MB
 Thin Pool Minimum Free Space: 5.261 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: active
 NodeID: xxx
 Is Manager: true
 Managers: 3
 Nodes: 3
 Node Address: xxx
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.64 GiB
Name: xxx
ID: xxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: xxx
No Proxy: xxx
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Red Hat 7 on VMware, Swarm Mode Cluster with three Manager nodes

**Steps to reproduce the issue:**
1. `docker network create -d overlay overlay`
2. `docker service create --name nginx --network overlay nginx`
3.  Verify startup of the task corresponding to the service has completed with `docker service ls`
4. Exec into another container connected to the `overlay` network and run `curl nginx` (repeat if you run into a timeout; it may take some time after changes to the service configuration that everything is set up correctly.)
5. `docker service scale nginx=0`
6. Verify task corresponding to the service has been stopped with `docker service ls`
7. `docker service scale nginx=1`
8. Repeat from step 3 onwards

**Describe the results you received:**
In step 4, `curl` sometimes errors out with `Failed connect to nginx:80; Connection refused` (maybe in approximately one third of the times) or `Could not resolve host: nginx; Name or service not known` (occasionally). Sometimes there are also timeouts; however they usually disappear in the next retries, which then most of the times fail with `Connection refused`. When trying to connect to the running `nginx` task directly via its IP address obtained with `docker inspect` while `curl`ing the service results in `Connection refused`, you also run into a timeout.

**Describe the results you expected:**
`curl` should always be able to connect to the `nginx` service.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-07-27 16:05
could this be a duplicate of https://github.com/docker/docker/issues/24234? Can you check if that looks the same?

**Comment by Stehsegler** [comment] 2016-07-27 17:26
#24234 is about reaching the containers from outside (i.e. via published ports), while this is about communication within the overlay network. So it's two different issues (although the technical root cause might be related, of course).

**Comment by thaJeztah** [comment] 2016-07-27 17:31
ping @mrjana PTAL

**Comment by dperny** [comment] 2016-07-27 20:46
Cannot replicate on first attempt with Debian VMs in Virtualbox.

**Comment by justincormack** [comment] 2016-07-28 03:23
There were some issues around internal name resolution which were also closed very recently as well as the external ones, cant't find the PRs right now, so it would be good to re-check on master/1.12.0 to see if this can still be replicated.

**Comment by Stehsegler** [comment] 2016-07-28 09:02
I don't think the issue is directly related to DNS, apart from the comparatively rare cases where you really get name lookup errors. The timeout and connection refused errors rather seem to me like a communication problem in the overlay network, since they occur after the DNS name has been resolved and also when using the IP address directly.

Interesting point to check would also be if it plays a role whether the containers trying to communicate are running on the same host or not. I may look into this, but not before the beginning of next week.

**Comment by Stehsegler** [comment] 2016-08-01 15:22
I am still able to reproduce faulty behaviour in 1.12.0 final.

Some new findings:
- You may have to repeat the scaling up and down various times (sometimes >20) until errors occur for the first time.
- The `could not resolve hostname` type errors indeed seem to have disappeared, at least I did not get one so far.
- The `connection refused` type errors still occur, no matter if client and service containers run on the same host or on different ones. In this case, however, the target container is still reachable on the overlay network via its IP address (as opposed to 1.12rc5, where a timeout occured when trying this).

I also watched the daemon logs during my tests. There are various types of error messages that are logged regularly or occasionally, however I was not able to figure out any direct relationship between when messages are logged and when the described malfunctions are observed. Nevertheless, here is an overview of the error messages I encountered:
- each time when scaling the service down to zero, I get something like `time="2016-08-01T15:57:52.945113444+02:00" level=error msg="container status unavailable" error="context canceled" module=taskmanager task.id=5cqnemkq1z38srtl4w0lyy3k4`
- occasionally on both hosts (the one with the client container and the one with the service container): `time="2016-08-01T15:36:25.211058382+02:00" level=info msg="Failed to delete real server 10.0.0.7 for vip 10.0.0.5 fwmark 267: no such file or directory"`
- occasionally on the service hosts (only client and service containers run on different hosts): 
`peerdbupdate in sandbox failed for ip 10.255.0.2 and mac 02:42:0a:ff:00:02: couldn't find the subnet "10.255.0.2/16" in network "e8x334g5cwq8c8t0ninyz8ema"`
- occasionally: `time="2016-08-01T16:01:31.409906990+02:00" level=error msg="Invalid broadcastQ encountered while gossiping for network e8x334g5cwq8c8t0ninyz8ema"`

Moreover, when scaling the service up to 1 instance the created tasks sometimes fail in the first place and are re-scheduled multiple times before the startup finally succeeds. This is most likely a different issue though.

From my point of view, this problem with overlay networking and other issues like #25055 prevent usage of Swarm mode for anything different than a playground. All in all, Swarm mode does not seem to be stable yet, which it IMHO should be as a massivly advertised functionality of a final release of Docker. Especially in a cluster manager which is often used to ensure availability of services, the reliability of the underlying software is really a major concern.

**Comment by Stehsegler** [comment] 2016-08-02 07:02
Another two findings:
- After scaling up and down a few times, even if the service is reachable via its VIP immediately after a scale-up, this often ceases to work after some time during which the system is not touched (approximately a minute). Then you once again get `connection refused` errors.
- For services with published ports, if the service is not reachable via its VIP internally on the overlay network, it is not accessible from the outside via the exposed ports on the host either - trying this also results in `connection refused`.

**Comment by dariko** [comment] 2016-08-02 07:30
I'm noticing this problem too. I'm unable to build a stable swarm because taking down a node often creates the same symptoms: the service is reachable by the container addresses but not from the VIP.

I suspect this could be linked to #25219

**Closed** 2016-08-11 13:39 UTC
Labels: area/swarm, group/networking, priority/P1, version/1.12

**Comment by kevlar1818** [comment] 2018-03-02 19:56
I'm seeing this on 18.02. I can create a service just fine, but scaling it up always results in a few containers being unable to communicate with the swarm. 

```# docker version
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.4
 Git commit:	fc4de447b5
 Built:	Tue Feb 13 17:04:16 2018
 OS/Arch:	linux/arm
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	fc4de447b5
  Built:	Tue Feb 13 17:06:01 2018
  OS/Arch:	linux/arm
  Experimental:	false
```

An excerpt from `journalctl -u docker`:
```
Mar 02 19:43:36 cluster_52 dockerd[257]: time="2018-03-02T19:43:36.311855588Z" level=error msg="agent: session failed" error="rpc error: code = Internal desc = transport is closing" module=node/agent node.id=6jy197047jcl1sid16gwwy70e
Mar 02 19:44:25 cluster_52 dockerd[257]: time="2018-03-02T19:44:25.482434052Z" level=error msg="agent: session failed" error="rpc error: code = Internal desc = transport is closing" module=node/agent node.id=6jy197047jcl1sid16gwwy70e
Mar 02 19:44:25 cluster_52 dockerd[257]: time="2018-03-02T19:44:25.482895129Z" level=error msg="agent: session failed" error="rpc error: code = Internal desc = transport is closing" module=node/agent node.id=6jy197047jcl1sid16gwwy70e
Mar 02 19:44:30 cluster_52 dockerd[257]: time="2018-03-02T19:44:30.737873218Z" level=error msg="agent: session failed" error="session initiation timed out" module=node/agent node.id=6jy197047jcl1sid16gwwy70e
```
