### ISSUE TITLE
Enhancement: Add --all-tags (-a) argument to docker search

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#24483] opened 2016-07-09 21:00 UTC
Docker Version: `Docker version 1.12.0-rc3, build 91e29e8, experimental`
OS Version: `Windows 10.0.10586`

1. The `docker pull` command supports an `--all-tags` parameter / argument
2. The `docker search` command does not supports an `--all-tags` parameter / argument, or equivalent functionality
3. As a result of this, the user experience (UX) for searching vs. pulling images is inconsistent, and requires the user to separately visit the Docker Hub in a web browser, in order to find specific tag(s) that they want to `pull` (or `run`).

# Proposed Fix

I would propose a user experience something similar to the following, with no changes to existing functionality:

```
docker search redis # (current behavior) Pick a Redis image to use 
docker search zer0c00l/redis --all-tags # (new behavior) Pick a tag from the specific image
docker pull zer0c00l/reds:tag123 # (current behavior) Pull the image:tag combo
```

Let me know if you have any questions about this feedback. Thanks!

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
Docker Captain
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by alexellis** [comment] 2016-07-09 21:03
👍 

I have found myself needing to use the HTTP API for /tags/list/ - having this built into the CLI would be a great addition.

Is there any history behind not implementing this yet?

**Comment by thaJeztah** [comment] 2016-07-12 00:22
looks like this is a duplicate of https://github.com/docker/docker/issues/11903, please continue the discussion on that issue

**Closed by thaJeztah** 2016-07-12 00:22 UTC
Labels: group/distribution, kind/enhancement

**Comment by pcgeek86** [comment] 2016-07-12 00:26
Thanks @thaJeztah -- sorry I missed that one. It's hard to know which terms to search for, when looking for a duplicate, since many others are approaching the same thing from different angles. :) Cheers!

**Comment by thaJeztah** [comment] 2016-07-12 00:29
@pcgeek86 I know, no worries :smile:
