### ISSUE TITLE
Execution driver lxc problems

### ISSUE THREAD

**Issue by jimonreal** [docker/docker#14499] opened 2015-07-09 14:52 UTC
When using the lxc driver instead of native, I am not able to build images. I get the following errors:

>Sending build context to Docker daemon 134.1 kB
Sending build context to Docker daemon 
Step 0 : FROM alpine:3.2
 ---> 31f630c65071
Step 1 : MAINTAINER Jose Monreal <jmonreal@gmail.com>
 ---> Running in 25d9e540161a
 ---> 2f7f869b9e69
Removing intermediate container 25d9e540161a
Step 2 : COPY inc/tmp/install.sh /tmp/
 ---> 487fc20660b2
Removing intermediate container cd993008b5d5
Step 3 : COPY inc/tmp/test.sh /tmp/
 ---> 79126ef719ed
Removing intermediate container eacbdf4ddb7b
Step 4 : WORKDIR /tmp
 ---> Running in 31875d7ce9e1
 ---> 0bdf8fd773f9
Removing intermediate container 31875d7ce9e1
Step 5 : RUN sh install.sh
 ---> Running in 77809a644883
The command '/bin/sh -c sh install.sh' returned a non-zero code: 255

The docker log:

>time="2015-07-09T10:38:53.690657795-03:00" level=info msg="POST /v1.19/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&nocache=1&rm=1&t=consul%3A0.5.2" 
time="2015-07-09T10:39:27.729012562-03:00" level=warning msg="Your kernel does not support OOM notifications: open /sys/fs/cgroup/memory/lxc/77809a644883816e84fffa5ecb0737b862273cfe001ca6c20afb3b178596253d/memory.oom_control: no such file or directory"

This is my docker conf:

 >DOCKER_OPTS="-e lxc"

docker info:

>docker info
Containers: 0
Images: 27
Storage Driver: devicemapper
 Pool Name: docker-8:1-266842-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 382 MB
 Data Space Total: 107.4 GB
 Data Space Available: 6.642 GB
 Metadata Space Used: 1.323 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.88 (2014-08-05)
Execution Driver: lxc-1.1.0
Logging Driver: json-file
Kernel Version: 4.0.0-gentoo
Operating System: Gentoo/Linux
CPUs: 4
Total Memory: 7.597 GiB
Name: Turing-LAN
ID: REJB:BAZJ:QK6P:H7CE:MOYB:ROPC:3C2X:SWY6:MS72:VILC:4DWQ:FDPM

**Comment by jimonreal** [comment] 2015-07-09 15:00
I could not find an issue related to the lxc driver on docker.

>docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

>docker info
Containers: 0
Images: 27
Storage Driver: devicemapper
 Pool Name: docker-8:1-266842-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 382 MB
 Data Space Total: 107.4 GB
 Data Space Available: 6.641 GB
 Metadata Space Used: 1.323 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.88 (2014-08-05)
Execution Driver: lxc-1.1.2
Logging Driver: json-file
Kernel Version: 4.0.0-gentoo
Operating System: Gentoo/Linux
CPUs: 4
Total Memory: 7.597 GiB
Name: Turing-LAN
ID: REJB:BAZJ:QK6P:H7CE:MOYB:ROPC:3C2X:SWY6:MS72:VILC:4DWQ:FDPM

>uname -a
Linux Turing-LAN 4.0.0-gentoo #3 SMP Wed Jul 8 14:51:03 CLT 2015 x86_64 Intel(R) Core(TM) i3 CPU M 380 @ 2.53GHz GenuineIntel GNU/Linux


I was expecting to be able to build my images without a problem.

What I got was the error showed in the first post.

**Comment by LK4D4** [comment] 2015-07-09 15:57
@jimonreal and all is okay with native execdriver?

**Comment by jimonreal** [comment] 2015-07-09 16:04
Yes, but I think it's an issue with my lxc and kernel modules. I'm checkin to be certain

**Comment by jimonreal** [comment] 2015-07-09 20:43
With the native works, but with lxc driver it does not work. I can not build images nor run them.

**Comment by thaJeztah** [comment] 2015-08-15 23:48
Be aware that the LXC driver is marked deprecated and will be removed in a future version. Is there a specific reason for using the LXC driver?

**Comment by jimonreal** [comment] 2015-08-17 01:45
I was playing with blockade(https://github.com/dcm-oss/blockade) and it needs to do some changes using lxc-conf that's why.

Is it possible to limit net, disk, cpu, ram, among others using the native driver?

**Comment by cpuguy83** [comment] 2015-09-15 17:50
@jimonreal cpu, ram, blkio.

So the issue is with needing to set some extra lxc configs?
What does your `install.sh` look like?

**Comment by icecrime** [comment] 2015-11-06 17:53
As notified in our [deprecation notice](https://github.com/docker/docker/blob/d023d5a8a24c18e912162c2f4c724cfb21028301/docs/misc/deprecated.md#lxc-built-in-exec-driver), Docker 1.10.0 will drop support for the LXC exec driver (#17700).

Thank you for the report, I'm now closing this.

**Closed by icecrime** 2015-11-06 17:53 UTC
Labels: area/runtime/lxc, status/more-info-needed
