### ISSUE TITLE
The client package's import URL is 404

### ISSUE THREAD

**Issue by lwhhhh** [docker/docker#27678] opened 2016-10-24 07:08 UTC
Example:
> client/client.go

` import (`
`         ......`
`    	 "github.com/docker/go-connections/sockets"`
`	 "github.com/docker/go-connections/tlsconfig"`
`) `

 The urls is 404

**Comment by thaJeztah** [comment] 2016-10-24 07:28
These are not URLs, but import paths, in these examples;

https://github.com/docker/docker/tree/master/vendor/src/github.com/docker/go-connections/sockets
https://github.com/docker/docker/tree/master/vendor/src/github.com/docker/go-connections/tlsconfig

See https://golang.org/doc/code.html#ImportPaths for the Go documentation describing this.

I'll close this issue because this is not a bug, but feel free to comment after I closed

**Closed by thaJeztah** 2016-10-24 07:28 UTC

**Comment by lwhhhh** [comment] 2016-10-24 08:06
@thaJeztah 
I am new to Go. 
If I access the "github.com/docker/go-connections/sockets" but get a 404 page, does it means I couldn't get this package by use "go get" command ?

**Comment by thaJeztah** [comment] 2016-10-24 17:03
You can `go get github.com/docker/go-connections` and `sockets` is just part of that repository. I strongly suggest to read the Go documentation, this is not the right location to ask for help on learning Go
