### ISSUE TITLE
Mysql exits after docker-compose up

### ISSUE THREAD

**Issue by ninjasilicon** [docker/docker#15625] opened 2015-08-17 10:08 UTC
Hello everybody, I'm trying to run docker un Ubuntu, and I have a problem with MysqL. Always I get this: "/usr/bin/mysqld_safe"   5 seconds ago       Exited (0). I have installed this docker image without problems in two machines, but in this one doesn't work. 

DOCKER VERSION:

Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

DOCKER INFO:

Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

UNAME -A

Linux xps 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Any idea? Thanks!!

**Comment by thaJeztah** [comment] 2015-08-17 10:24
@ninjasilicon The GitHub issue tracker is not a general support forum. It's used for reporting bugs and feature requests in Docker.

Could you ask this question on [one of the following locations](https://github.com/docker/docker#talking-to-other-docker-users-and-contributors);

- the `#docker` IRC channel on freenode
- the [docker-user](https://groups.google.com/forum/#!forum/docker-user) Google Group
- https://forums.docker.com
- on [StackOverflow](https://stackoverflow.com/search?tab=newest&q=docker)

I'm going to close this issue, because this is not a bug-report or a feature-request, but feel free to comment here after I've closed.

**Closed by thaJeztah** 2015-08-17 10:24 UTC

**Comment by ninjasilicon** [comment] 2015-08-17 10:40
Sorry, thank you so much

**Comment by thaJeztah** [comment] 2015-08-17 11:10
No problem! Thanks!
