### ISSUE TITLE
Docker stuck after changing host

### ISSUE THREAD

**Issue by IAmJulianAcosta** [docker/docker#27256] opened 2016-10-10 16:13 UTC
**Description**

I changed docker host variable to `tcp://0.0.0.0:2376`, and after that docker commands doesn't work, are stuck, and I have to `SIGINT` in order to exit

**Steps to reproduce the issue:**
1. Modify docker host
2. Run docker images

**Describe the results you received:**
Process frozen until `ctrl+c`

**Describe the results you expected:**
"Cannot connect to docker daemon....."

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 71
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 129
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
ID: JLOJ:L5A3:RX2B:5OAY:JDBT:XAPK:PYXM:MWDL:DDTD:4RQW:7PP3:MWPJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Ubuntu 16.04 on virtualbox
- `etc/default/docker`:
```
# Docker Upstart and SysVinit configuration file
DOCKER_OPTS="-H tcp://0.0.0.0:2376"
```
- `/etc/systemd/system/docker.service` 
```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
EnvironmentFile=-/etc/default/docker
Type=notify
ExecStart=
ExecStart=/usr/bin/dockerd $DOCKER_OPTS
ExecReload=/bin/kill -s HUP $MAINPID

LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

TasksMax=infinity
TimeoutStartSec=0

Delegate=yes

KillMode=process

[Install]
WantedBy=multi-user.target
```

**Comment by thaJeztah** [comment] 2016-10-11 14:34
I see a couple of issues; 

- first of all, _never_ modify the default docker.service; doing so prevents future upgrades to update the unit-file, and may result in fixes in the unit file not being installed on your system. If you want to make customizations to the unit-file, always use a drop-in file, as is described in https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options
- If you're already using a drop-in file, I'd recommend setting the options there, instead of using a `/etc/default/docker` file to set environment variables
- It looks like you're exposing the remote API _without_ using TLS to protect this; if the machine you're running on is publicly accessible, this give _anyone_ that can access the machine root access on your host. Please read https://docs.docker.com/engine/security/https/ when making the API accessible over tcp/ip


When you tried to run docker commands, did you provide a `-H` flag (or set the `DOCKER_HOST` environment variable) to let the client know how to connect to the daemon? If you don't provide this, the client will still try to connect using a socket connection (`/var/run/docker.sock`), and fail.

I don't suspect there's a bug here, but a configuration issue, but please provide some more information

**Comment by IAmJulianAcosta** [comment] 2016-10-11 14:51
I'm confused, because I did what the manual said (drop-in file), but didn't work. I had to create docker.service and then it worked.

If I provided `-H` flag, it worked, but if I didn't provide it, I didn't get an error, just a frozen process.

**Comment by thaJeztah** [comment] 2016-10-11 15:11
Did you `sudo systemctl daemon-reload` after adding the drop-in file?

I tried to reproduce your issue, but without specifying the `-H` on the client, it just directly shows 

    Cannot connect to the Docker daemon. Is the docker daemon running on this host?

But does not hang; is your client connecting to a _remote_ daemon, or on the same host?

**Comment by thaJeztah** [comment] 2016-10-30 07:48
closing, because we were not able to reproduce, and need more information (as requested), but happy to reopen once provided

**Closed by thaJeztah** 2016-10-30 07:48 UTC
Labels: status/more-info-needed, version/1.12
