### ISSUE TITLE
[1.12.0-rc2] Cannot pull nor login to `quay.io` server

### ISSUE THREAD

**Issue by pietv** [docker/docker#23792] opened 2016-06-21 01:54 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: 76DC:HOIL:KELK:2A35:XW3A:BUJ5:G3DB:6IZL:24DK:FAGG:VKVJ:MNOE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 28
 System Time: 2016-06-21T01:45:47.450682972Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
Freshly installed Docker for Mac version 0.12.0-rc2.
Logging in to the quay.io hub server doesn't work:
  ```
$ docker login quay.io
Username (pietv): 
Password: 
Error response from daemon: Get https://quay.io/v1/users/: dial tcp: lookup quay.io on 192.168.65.1:53: read udp 192.168.65.2:37176->192.168.65.1:53: i/o timeout
  ```
Pulling public images from quay.io doesn't work:
```
$ docker pull quay.io/eris/data
Using default tag: latest
Error response from daemon: Get https://quay.io/v1/_ping: dial tcp: lookup quay.io on 192.168.65.1:53:   read udp 192.168.65.2:44125->192.168.65.1:53: i/o timeout 
```

(Both operations do work with docker 1.11.2 on Mac.)

/etc/hosts:
```
127.0.0.1        localhost
255.255.255.255  broadcasthost
::1              localhost
```
/etc/resolv.conf:
```
nameserver 8.8.4.4
nameserver 8.8.8.8
```

**Comment by vdemeester** [comment] 2016-06-21 10:17
Hum… I cannot reproduce (works fine for me with the RC)

**Comment by pietv** [comment] 2016-06-21 10:27
What do you recommend how to overcome the issue?

I have a Docker client 1.11.2 installed on the same machine which (with DOCKER* settings) + Docker daemon set up using the Docker Machine. It pulls the images successfully, so this is likely not a host networking issue.

When Docker client 1.11.2 communicates with the native Docker server 1.12.0-rc2, it can't pull images as well.

**Comment by vdemeester** [comment] 2016-06-21 10:30
@pietv ah… I though the client and server were both 1.12-rc2… I'll take a look with a 1.11.2 client then

**Comment by pietv** [comment] 2016-06-21 10:36
@vdemeester no, no, they were both 1.12.0-rc2. The thing that it doesn't work with 1.11.2 client as well is just a side note.

**Comment by dflower-rms** [comment] 2016-06-22 00:41
I have the same issue when trying to private Artifactory docker repository. Same versions of Docker, and same version of Go (not sure if that might affect this).

**Comment by VoR0220** [comment] 2016-06-24 18:11
I too am having this problem. Running on OS X El Capitan.

**Comment by christianparpart** [comment] 2016-06-27 15:37
Hey Guys, :+1: I unfortunately run into the very same issue. I just had a fresh install of Docker for Mac (no docker for mac before ever installed - but Docker Machine)

**Comment by VoR0220** [comment] 2016-06-27 17:49
I got around this problem by simply restarting the docker machine.

**Comment by pietv** [comment] 2016-07-01 07:00
@VoR0220 i've tried restarting one of the docker machines (version 7.0, DigitalOcean driver) which I incidentally have alongside native Docker, but it didn't make a difference — native Docker's `docker pull` fails with the same error (`read udp ... timeout`).

**Comment by pietv** [comment] 2016-07-01 07:11
With the just updated “beta17”, the error remains.

![about](http://i.imgur.com/ViDbzCg.png)

**Comment by pietv** [comment] 2016-07-06 14:06
The same for “beta”:

```
Version 1.12.0-rc3-beta18 (build: 9996)
ec40b14c72adc0bff3b01fa8886dae7f2eee1541
```

**Comment by SeanEire** [comment] 2016-07-10 12:16
I'm also experiencing the same issue with both client and server running 1.12.0-rc3. Seeing the i/o timeout error on login or pull attempt.

Anybody have a workaround for this?

**Comment by pietv** [comment] 2016-07-14 17:16
Docker log output: http://pastebin.com/jE0zKa9u
(`~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/log/docker.log`)

Command:
```
$ docker pull quay.io/eris/data
Using default tag: latest
Error response from daemon: Get https://quay.io/v1/_ping: dial tcp: lookup quay.io on 192.168.65.1:53: read udp 192.168.65.2:38086->192.168.65.1:53: i/o timeout
```

Version:
```
Version 1.12.0-rc4-beta19 (build: 10258)
c84feba3aa680f426b8fa66f688388611267cd53
```

**Comment by FrenchBen** [comment] 2016-07-14 17:39
@pietv I'm also on `Version 1.12.0-rc4-beta19 (build: 10258)`
No issues pulling the data. 
```
$ docker pull quay.io/eris/data
Using default tag: latest
latest: Pulling from eris/data

0f4cd5c119fc: Pull complete
4e45e9290acd: Pull complete
c6f6c496e7c7: Pull complete
4fcab26aaa4b: Pull complete
3403eec742e6: Pull complete
10bc7cbdf6ea: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:8026f720481cc06222cf26d5efc71d4268787b7d3d9c2a4a31c055f95ab9a1ea
Status: Downloaded newer image for quay.io/eris/data:latest

$ docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by pietv** [comment] 2016-07-15 10:48
@FrenchBen thanks! replacing my ISP DNS with 8.8.8.8 solved the issue for me.

**Comment by thaJeztah** [comment] 2016-07-15 12:52
Looks like this is resolved, so I'll go ahead and close this, but feel free to comment after I closed

**Closed by thaJeztah** 2016-07-15 12:52 UTC
Labels: group/networking, group/pinata, version/1.12

**Comment by pkokoshnikov** [comment] 2018-02-07 09:54
Reproduced on
Mac OS Sierra 10.12.6 
Docker version
Engine: 17.12.0-ce
Compose: 1.18.0
Machine: 0.13.0
Credential Helper: 0.6.0
Notary: 0.4.3

Request error: POST unix://localhost:80/images/create?fromImage=quay.io%2Fnatera%2Firis-report&tag=0.0.1-CON-1331-M11-QA-SNAPSHOT: 500, body: {"message":"Get https://quay.io/v2/: Service Unavailable"}

Workaround: restarting docker

**Comment by TheMrZZ** [comment] 2020-05-19 16:09
Reproduced the issue on Windows 10 Pro edition. I was using Cloudfare's DNS. Changing my DNS to Google's ones solved the issue.
