### ISSUE TITLE
Bash completion for commands within an image

### ISSUE THREAD

**Issue by ferdy-galema** [docker/docker#13647] opened 2015-06-01 21:30 UTC
This is probably pretty to hard to accomplish, but would it be possible to implement a feature that completes commands that are actually in the image.

So i.e. `docker run -it myimage git ` followed by Tab Tab would show completion suggestions that are actually done on the image. (Maybe by spinning up containers for every Tab Tab command?).

Is there any current work on this?

**Comment by thaJeztah** [comment] 2015-06-01 21:41
Haven't actually tried to run autocompletion that way (perhaps @albers tried)

If it's possible, it's really something that is part of the *containter*, not Docker.

For that reason, I'm going to close this issue, because this is not a bug and not something to be implemented in Docker itself.

Feel free to continue the discussion after closing.

**Closed by thaJeztah** 2015-06-01 21:41 UTC

**Comment by albers** [comment] 2015-06-03 20:44
Hmm, it might be possible to a certain degree. Sticking to your example, if you had git installed on the host, maybe completion could be delegated to git's completion (on the host). But that would only be helpful for commands and options. File- and dirnames would complete to the host filesystem, which would be very confusing.
