### ISSUE TITLE
Received unexpected HTTP status: 500 Internal Server Error

### ISSUE THREAD

**Issue by sunil3s3** [docker/docker#25166] opened 2016-07-28 09:19 UTC
**Output of `docker version`:**

```
(paste your output here)
```Docker version 1.10.3, build 57bf6fd



**Output of `docker info`:**

```
(paste your output here)
```Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 6
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-251:0-41156611-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.683 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104.7 GB
 Metadata Space Used: 4.891 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /scratch/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /scratch/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.1.12-32.2.3.el7uek.x86_64
Operating System: Oracle Linux Server 7.2
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 251.6 GiB
Name: xxxxxx..com
ID: DKRO:COZA:MLEU:PMNM:3RJZ:LYME:XC6R:ER4B:PZ7J:G5PB:2LEG:YSGN
Http Proxy: http://www-xxx.xxx.com:80/
Https Proxy: http://www-xxxx.xxx..com:80/


**Additional environment details (AWS, VirtualBox, physical, etc.):**
using object storage Swift


**Steps to reproduce the issue:**
1.Installed docker/distribution registry
distribution/registry                                   latest              6d263fc92047        7 months ago        666.4 MB

2. started private registry with SETTINGS_FLAVOR=swift
3.docker push is failing


**Describe the results you received:**

#docker push xxxxxxx.com:5000/internal/oraclelinux:7u2
The push refers to a repository [xxxxxx.com:5000/internal/oraclelinux]
5f70bf18a086: Pushing 1.024 kB
472062da526a: Pushing [==================================================>] 276.1 MB/276.1 MB
Received unexpected HTTP status: 500 Internal Server Error

and docker logs show below error

time="2016-07-28T06:03:26.357702532Z" level=error msg="response completed with error" environment=development err.code=UNKNOWN err.detail="parsing time \"Thu, 28 Jul 2016 06:02:20 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" err.message="unknown error" 

**Describe the results you expected:**


**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-07-28 09:25
Do you have logs from that registry as well? Looks like this may be an issue with docker/distribution, not docker (engine)

**Comment by sunil3s3** [comment] 2016-07-28 09:33
I have started container with the docker image "distribution/registry" . Do you need that logs from that container?

these logs I found in /var/log/messages 

docker[18158]: time="2016-07-28T05:44:41.380564107Z" level=info msg="API listen on /var/run/docker.sock"
docker[18158]: time="2016-07-28T05:45:17.968880651Z" level=error msg="Upload failed: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<!D
docker[18158]: time="2016-07-28T05:45:22.630771408Z" level=error msg="Error in LookupRemoteImage: HTTP code 404"
docker[18158]: time="2016-07-28T05:45:22.666236609Z" level=error msg="Error in LookupRemoteImage: HTTP code 404"
docker[18158]: time="2016-07-28T05:45:22.667421542Z" level=error msg="Error in LookupRemoteImage: HTTP code 404"
docker[18158]: time="2016-07-28T05:55:45.252723240Z" level=warning msg="cannot serialize hook of type configs.FuncHook, skipping"
docker[18158]: time="2016-07-28T05:55:45.369808336Z" level=warning msg="cannot serialize hook of type configs.FuncHook, skipping"
docker[18158]: time="2016-07-28T05:56:30.317110740Z" level=warning msg="cannot serialize hook of type configs.FuncHook, skipping"
docker[18158]: time="2016-07-28T05:56:30.381321703Z" level=warning msg="cannot serialize hook of type configs.FuncHook, skipping"
docker[18158]: time="2016-07-28T05:58:00.701021415Z" level=error msg="Upload failed, retrying: Received unexpected HTTP status: 500 Internal Server Error"
docker[18158]: time="2016-07-28T05:59:11.910953779Z" level=error msg="Upload failed, retrying: Received unexpected HTTP status: 500 Internal Server Error"
docker[18158]: time="2016-07-28T06:00:24.538162970Z" level=error msg="Upload failed, retrying: Received unexpected HTTP status: 500 Internal Server Error"
docker[18158]: time="2016-07-28T06:01:57.819531823Z" level=error msg="Upload failed, retrying: Received unexpected HTTP status: 500 Internal Server Error"
docker[18158]: time="2016-07-28T06:03:26.394562275Z" level=error msg="Upload failed: Received unexpected HTTP status: 500 Internal Server Error"
docker[18158]: time="2016-07-28T06:17:32.131702541Z" level=error msg="Upload failed: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<!D
docker[18158]: time="2016-07-28T06:25:52.123610307Z" level=error msg="Upload failed: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<!D
docker[18158]: time="2016-07-28T06:25:52.155950410Z" level=error msg="Upload failed: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<!D
docker[18158]: time="2016-07-28T06:32:21.719592550Z" level=error msg="Upload failed: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<!D
docker[18158]: time="2016-07-28T06:33:55.819264403Z" level=error msg="Upload failed: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<!D
docker[18158]: time="2016-07-28T06:54:35.728736978Z" level=error msg="Upload failed: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<!D
docker[18158]: time="2016-07-28T06:56:22.986724252Z" level=error msg="Upload failed: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<!D

**Comment by thaJeztah** [comment] 2016-07-28 09:36
Looks like it's receiving a HTML page (but the logs are truncated); I suspect an issue with your proxy settings, causing some requests to be blocked, and returning a 403

**Comment by sunil3s3** [comment] 2016-07-28 09:39
but I can see some file under swift storage.


# swift list
REGISTRY
## swift list REGISTRY
files/docker/registry/v2/repositories/oraclelinux/_uploads/010a09f7-68d5-4d7f-a769-c0f6b552b688/data
files/docker/registry/v2/repositories/oraclelinux/_uploads/010a09f7-68d5-4d7f-a769-c0f6b552b688/hashstates/sha256/0
files/docker/registry/v2/repositories/oraclelinux/_uploads/010a09f7-68d5-4d7f-a769-c0f6b552b688/hashstates/sha256/97837850
files/docker/registry/v2/repositories/oraclelinux/_uploads/010a09f7-68d5-4d7f-a769-c0f6b552b688/startedat
files/docker/registry/v2/repositories/oraclelinux/_uploads/174eb931-e7e7-42d5-b607-f6e9c4530f45/data
files/docker/registry/v2/repositories/oraclelinux/_uploads/174eb931-e7e7-42d5-b607-f6e9c4530f45/hashstates/sha256/0
files/docker/registry/v2/repositories/oraclelinux/_uploads/174eb931-e7e7-42d5-b607-f6e9c4530f45/hashstates/sha256/97837850
files/docker/registry/v2/repositories/oraclelinux/_uploads/174eb931-e7e7-42d5-b607-f6e9c4530f45/startedat
files/docker/registry/v2/repositories/oraclelinux/_uploads/22ec2a70-418d-4c6a-9127-ae7619584987/data
files/docker/registry/v2/repositories/oraclelinux/_uploads/22ec2a70-418d-4c6a-9127-ae7619584987/hashstates/sha256/0
files/docker/registry/v2/repositories/oraclelinux/_uploads/22ec2a70-418d-4c6a-9127-ae7619584987/hashstates/sha256/97837850
files/docker/registry/v2/repositories/oraclelinux/_uploads/22ec2a70-418d-4c6a-9127-ae7619584987/startedat
files/docker/registry/v2/repositories/oraclelinux/_uploads/d11f211c-e42c-4d62-9c10-18fc3d209338/data
files/docker/registry/v2/repositories/oraclelinux/_uploads/d11f211c-e42c-4d62-9c10-18fc3d209338/hashstates/sha256/0
files/docker/registry/v2/repositories/oraclelinux/_uploads/d11f211c-e42c-4d62-9c10-18fc3d209338/hashstates/sha256/97837850
files/docker/registry/v2/repositories/oraclelinux/_uploads/d11f211c-e42c-4d62-9c10-18fc3d209338/startedat
files/docker/registry/v2/repositories/oraclelinux/_uploads/d8721f47-4adf-4e67-be6b-862e4b02bbe9/data
files/docker/registry/v2/repositories/oraclelinux/_uploads/d8721f47-4adf-4e67-be6b-862e4b02bbe9/hashstates/sha256/0
files/docker/registry/v2/repositories/oraclelinux/_uploads/d8721f47-4adf-4e67-be6b-862e4b02bbe9/hashstates/sha256/97837850
files/docker/registry/v2/repositories/oraclelinux/_uploads/d8721f47-4adf-4e67-be6b-862e4b02bbe9/startedat

**Comment by sunil3s3** [comment] 2016-07-28 09:43
this is how .. I'm starting the docker registry container

docker run --restart=always --privileged=true -d --name pdit-registry1 -p 5000:5000 -e "REGISTRY_STORAGE=swift" 
-e "REGISTRY_STORAGE_SWIFT_USERNAME=Storage-xxxxxx:xxxxx.Storageadmin" -e "REGISTRY_STORAGE_SWIFT_PASSWORD=xxxxxx" 
-e "REGISTRY_STORAGE_SWIFT_AUTHURL=https://xxxxxxx.corp.com/auth/v1.0" -e "REGISTRY_STORAGE_SWIFT_CONTAINER=REGISTRY"  distribution/registry

**Comment by sunil3s3** [comment] 2016-08-02 08:43
any help on this will be appreciated.

**Comment by thaJeztah** [comment] 2016-08-02 09:09
Perhaps @dmp42 has some suggestions, but this issue may be really specific to your setup; keep in mind that the GitHub issue tracker is not a general support forum; you can try forums.docker.com as well

**Comment by dmp42** [comment] 2016-08-03 18:56
First thing, please don't use `distribution/registry`, just use the official image `registry`.

Also, like @thaJeztah pointed out, your logs contain html. The registry does not return html, so, it's likely whatever proxy you have setup in between that's causing the issue.

I would suggest you try again with:

 * the official image `registry`
 * no proxy in between

**Comment by sunil3s3** [comment] 2016-08-04 06:02
@dmp42 .. Appreciate for the inputs.

Even with offical image registry , Im getting the same error. I will check with proxy settings and see.
# docker images
REPOSITORY                                              TAG                 IMAGE ID            CREATED             SIZE
registry                                                latest              c6c14b3960bd        5 days ago          33.28 MB
registry                                                2                   8ff6a4aae657        7 weeks ago         171.5 MB

**Comment by thaJeztah** [comment] 2016-10-29 07:45
Closing, because this is likely not a bug, but a configuration / network setup issue

**Closed by thaJeztah** 2016-10-29 07:45 UTC
Labels: area/distribution, status/more-info-needed

**Comment by somashekarg** [comment] 2017-03-16 09:43
somashekar@somashekar:~/Desktop/mssql$ heroku container:push --app mssql-test
Sending build context to Docker daemon   371 MB
Step 1/7 : FROM heroku/heroku:16
 ---> cc0caac6a5c5
Step 2/7 : FROM microsoft/mssql-server-linux:latest
 ---> aa104c338ea3
Step 3/7 : EXPOSE 1433
 ---> Using cache
 ---> 3e89f2aabd0b
Step 4/7 : ARG user
 ---> Using cache
 ---> 80b32c2af42e
Step 5/7 : WORKDIR /var/opt/mssql
 ---> Using cache
 ---> 869aa05a0587
Step 6/7 : VOLUME /var/opt/mssql/data /var/opt/mssql/data
 ---> Using cache
 ---> 6add8a1f42f3
Step 7/7 : CMD /opt/mssql/bin/sqlservr
 ---> Using cache
 ---> 68537ddb86c3
Successfully built 68537ddb86c3
The push refers to a repository [registry.heroku.com/mssql-test/web]
02d9d2901297: Retrying in 1 second 
588e319013ef: Retrying in 1 second 
7e20a5da50cf: Retrying in 5 seconds 
3da04e6301f6: Retrying in 5 seconds 
f1e60b0cfe77: Retrying in 1 second 
cc31aa8aca7d: Waiting 
668724d35c59: Waiting 
d7c22be21371: Waiting 
c1bd37d01c89: Waiting 
943edb549a83: Waiting 
bf6751561805: Waiting 
f934e33a54a6: Waiting 
e7ebc6e16708: Waiting 
received unexpected HTTP status: 500 Internal Server Error
 !    Error: docker push exited with 1
While pushing to heroku private space i am getting this error

**Comment by thaJeztah** [comment] 2017-03-16 10:10
@somashekarg have you also contacted heroku? The 500 error could come from their registry

**Comment by somashekarg** [comment] 2017-03-16 10:19
Actual i tried pushing the docker image to personal app in heroku it is pushing successfully and while starting the sql server in heroku app it is giving 
This is an evaluation version.  There are [153] days left in the evaluation period.
RegQueryValueEx HADR for key "Software\Microsoft\Microsoft SQL Server\MSSQL\MSSQLServer\HADR" failed.
2017-03-14 13:26:14.93 Server      Microsoft SQL Server vNext (CTP1.3) - 14.0.304.138 (X64) 
	Feb 13 2017 16:49:12 
	Copyright (C) 2016 Microsoft Corporation. All rights reserved.
	on Linux (Ubuntu 16.04.1 LTS)
2017-03-14 13:26:14.93 Server      UTC adjustment: 0:00
2017-03-14 13:26:14.94 Server      (c) Microsoft Corporation.
2017-03-14 13:26:14.94 Server      All rights reserved.
2017-03-14 13:26:14.94 Server      Server process ID is 4116.
2017-03-14 13:26:14.94 Server      Logging SQL Server messages in file 'C:\var\opt\mssql\log\errorlog'.
2017-03-14 13:26:14.95 Server      Registry startup parameters: 
	 -d C:\var\opt\mssql\data\master.mdf
	 -l C:\var\opt\mssql\data\mastlog.ldf
	 -e C:\var\opt\mssql\log\errorlog
2017-03-14 13:26:14.96 Server      Error: 17113, Severity: 16, State: 1.
2017-03-14 13:26:14.96 Server      Error 3(The system cannot find the path specified.) occurred while opening file 'C:\var\opt\mssql\data\master.mdf' to obtain configuration information at startup. An invalid startup option might have caused the error. Verify your startup options, and correct or remove them if necessary.
2017-03-14 13:26:14.97 Server      SQL Server shutdown has been initiated


so i tired pushing the same-thing in private space where all the ports are opened
anybody help me in this issue?

**Comment by thaJeztah** [comment] 2017-03-16 10:23
@somashekarg the GitHub issue tracker is not the best place for that;  it's not intended as a general support forum for using docker. Consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)
