### ISSUE TITLE
how to push an existing docker image to artifactory 

### ISSUE THREAD

**Issue by amy201988** [docker/docker#22697] opened 2016-05-12 13:55 UTC
I have a docker image for logspout which is getting pulled from gliderlabs . Can  i push the same image to artifactory which we are using . If so how to push the image ?

**Comment by thaJeztah** [comment] 2016-05-12 14:14
```
docker tag some-image my-repository.com/foobar/baz:latest
docker push my-repository.com/foobar/baz:latest
```

Please keep in mind that the issue tracker is not a general support forum, but for tracking bugs and feature requests. For other type of questions, consider using;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

Or the support team for artifactory.

I'll close this issue, because this is not a bug

**Closed by thaJeztah** 2016-05-12 14:14 UTC

**Comment by amy201988** [comment] 2016-05-12 14:52
whats /foobar/baz:latest?

**Comment by thaJeztah** [comment] 2016-05-12 15:00
That's just a name I came up with to give the image, so `/foobar/baz:latest` = `repo-name/image-name:tag-name`
