### ISSUE TITLE
bash: words: bad array subscript - Docker autocomplete script

### ISSUE THREAD

**Issue by gauravgoyal** [docker/docker#15246] opened 2015-08-03 07:08 UTC
`Description:` I am using docker autocomplete script for autocompletition. It gives me error when I press tab for command completition. I am using boot2docker for docker.

Error: bash: words: bad array subscript

`docker version:`

* Client version: 1.7.1
* Client API version: 1.19
* Go version (client): go1.4.2
* Git commit (client): 786b29d
* OS/Arch (client): darwin/amd64
* Server version: 1.7.1
* Server API version: 1.19
* Go version (server): go1.4.2
* Git commit (server): 786b29d
* OS/Arch (server): linux/amd64

`docker info`:

```
Containers: 1
Images: 75
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 77
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.7-boot2docker
Operating System: Boot2Docker 1.7.1 (TCL 6.3); master : c202798 - Wed Jul 15 00:16:02 UTC 2015
CPUs: 4
Total Memory: 1.955 GiB
Name: boot2docker
ID: ABC3:HCO6:6JGF:KXW7:SW7H:7YF5:55C6:EAMJ:TW4Y:UH6B:7XRJ:JDHB
Debug mode (server): true
File Descriptors: 54
Goroutines: 64
System Time: 2015-08-03T07:17:54.067046299Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: gauravgoyal
Registry: https://index.docker.io/v1/
```
`uname -n`:
* Gauravs-MacBook-Air.local

`Step to reproduce`:

* Run docker <tab>
* For e.g., docker bu <tab>

Error: bash: words: bad array subscript

Expected result: docker build

**Comment by albers** [comment] 2015-08-03 07:48
Which version of bash do you use?
Does this error occur on all completions?

**Comment by gauravgoyal** [comment] 2015-08-03 07:52
@albers 

* Which version of bash do you use?
```
bash version:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
```

* Does this error occur on all completions?
No, this occurs only with the docker autocomplete. I am also using docker compose autocomplete which works fine.

**Comment by albers** [comment] 2015-08-03 07:57
Thanks for the hint that the compose completion works for you. This might be helpful. Sadly, I do not have access to a mac, so I cannot reproduce.

Does the problem with docker completion occur on all subcommands? Do you also get it when completing `docker ` or `docker -`?

**Comment by gauravgoyal** [comment] 2015-08-03 08:04
@albers 

It happens only for the first argument, i.e. in the name of the command. Below are the examples:
* While completing docker <tab>
* While completing docker ima<tab>

It works fine for the below completions:

* docker images <tab> - Works fine.
* docker rm <tab> - Works fine.

Let me know if I can be of some help.

**Comment by albers** [comment] 2015-08-03 08:57
Seems that bash 3.2 doesn't like negative array indexes:
```shell
# number=()
# echo ${number[1]}

# echo ${number[-1]}
-bash: number: bad array subscript

# bash --version
GNU bash, version 3.2.39(1)-release (i486-pc-linux-gnu)
```
Bash 4.3. wouldn't choke here, it would just print an empty string.

I still got no idea why you get a negative index here.
@tianon can you help? Got a mac?

**Comment by albers** [comment] 2015-08-03 09:18
@gauravgoyal Can you find out what version of bash-completion you have installed?

**Comment by gauravgoyal** [comment] 2015-08-03 09:23
@albers 

```
bash-completion
Version: 1.3
```

**Comment by radk0s** [comment] 2015-08-04 11:58
I had the same problem on Mac. Bash upgrade is the easiest fix.
`brew update && brew install bash` 
It should install bash in version 4 and docker autocomplete works without errors.

**Comment by albers** [comment] 2015-08-04 13:46
@gauravgoyal Please do not upgrade your bash yet. I'm currently trying to assemble an environment with the exact versions you use in order to reproduce the issue.

**Comment by albers** [comment] 2015-08-04 13:48
Is this bash / autocompletion constellation the default that you get when using a current macbook?

**Comment by gauravgoyal** [comment] 2015-08-04 13:53
@albers Yes, this version came with current macbook.

**Comment by albers** [comment] 2015-08-04 13:56
OK, then completion should really work with it.

**Comment by gauravgoyal** [comment] 2015-08-04 13:59
Sorry, I didnt get you. Should I try upgrading the bash?

**Comment by albers** [comment] 2015-08-04 15:05
@gauravgoyal Please do **not** upgrade. As I do not have a mac I need someone to verify my results.

**Comment by AlexZeitler** [comment] 2015-08-15 22:58
I'm facing the same issue.

**Comment by albers** [comment] 2015-08-16 12:36
@gauravgoyal What's the name/version of the operating system?

**Comment by albers** [comment] 2015-08-16 12:37
@AlexZeitler Please tell me the version of
* bash
* bash-completion
* the OS.

**Comment by AlexZeitler** [comment] 2015-08-16 12:44
@albers 

* 3.2
* 1.3
* OS X 10.10.5

**Comment by albers** [comment] 2015-08-16 12:47
@AlexZeitler What's the exact version of bash?

**Comment by AlexZeitler** [comment] 2015-08-16 12:50
@albers 
````
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
````

**Comment by thaJeztah** [comment] 2015-08-16 12:52
I think all OS X versions will stay on that version, because IIRC, after 3.2, Bash switched to a different license, which was incompatible with the OS X licensing

**Comment by albers** [comment] 2015-08-16 12:54
@AlexZeitler Thanks for reporting.
@thaJeztah Wow, that's interesting!

**Comment by albers** [comment] 2015-08-17 14:45
@gauravgoyal 
I found and fixed a problem. Could you please check whether this fixes the issue for you?

Please download the updated completion with
`curl -L https://raw.githubusercontent.com/albers/docker/completion-log-opt-fix/contrib/completion/bash/docker > docker-completion`,
load it with
`. ./docker-completion`
and check if completion now works as expected.

**Comment by AlexZeitler** [comment] 2015-08-17 14:55
@albers Works fine here :+1:

**Comment by albers** [comment] 2015-08-17 15:10
@AlexZeitler Thanks for testing!
Another potential issue:
What happens if you complete `docker run --log-opt ` on a mac?

**Comment by AlexZeitler** [comment] 2015-08-17 15:41
```
docker run --l
--label       --label-file  --link        --log-driver  --log-opt     --lxc-conf
```

```
docker run --log-
--log-driver  --log-opt
```
```
docker run --log-opt <tab-here>-bash: compopt: command not found
```

**Comment by albers** [comment] 2015-08-17 15:44
Ah, yes. Another feature that's not supported by the ancient bash version. Thanks for testing, Alex!

**Comment by thaJeztah** [comment] 2015-08-17 15:47
Oh, just for the background on the old version of bash on OS X; here's an article: [Apple’s great GPL purge](http://meta.ath0.com/2012/02/05/apples-great-gpl-purge/)

**Comment by albers** [comment] 2015-08-17 16:00
Thanks @thaJeztah! Very enlightening.

**Comment by AlexZeitler** [comment] 2015-08-17 16:02
@albers Thanks for fixing!

**Comment by gauravgoyal** [comment] 2015-08-18 04:26
@albers https://github.com/docker/docker/issues/15246#issuecomment-131847010 , Works for me too. Thanks a lot for fixing.
 
```
docker run --log-opt -bash: compopt: command not found
```
Above command gives error.

**Comment by everdark** [comment] 2015-08-18 06:26
I got exactly the same trouble and the patched script works for me as well. The testing results of `docker run --log-opt` are also aligned with @AlexZeitler

**Comment by albers** [comment] 2015-08-18 07:01
Thanks for sharing this, @everdark.
I will create a PR with this fix.

**Comment by albers** [comment] 2015-08-18 07:20
#dibs

**Comment by AlexZeitler** [comment] 2015-08-18 09:01
@albers :+1:

**Comment by albers** [comment] 2015-08-18 12:56
For reference: I posted an image with bash 3.2.57 and bash-completion 1.3. to the Docker Hub: [bash-completion-mac](https://hub.docker.com/r/albers/bash-completion-mac/).

**Comment by cpuguy83** [comment] 2015-08-18 20:27
Closing as #15653 is merged

**Closed by cpuguy83** 2015-08-18 20:27 UTC
Labels: status/claimed

**Comment by albers** [comment] 2015-08-18 20:41
The fix will be included in the next release.

Until then, you can replace the completion script with the fixed version:

> curl -L https://raw.githubusercontent.com/albers/docker/18381faee685c6d28dd7438a183bf7a441e8c9a1/contrib/completion/bash/docker > /usr/local/etc/bash_completion.d/docker
