### ISSUE TITLE
docker 1.6.2 takes 20 minutes to start

### ISSUE THREAD

**Issue by shapiroj** [docker/docker#14705] opened 2015-07-17 12:56 UTC
Occasionally my docker server takes upward of 20 minutes to start.  This does not happen every time, even with the same set of images active.  

docker version:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

docker info:
Containers: 28
Images: 387
Storage Driver: aufs
 Root Dir: /ghostcache/docker/aufs
 Backing Filesystem: extfs
 Dirs: 444
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.14.39-3.14.2.1-amd64-15541224
Operating System: Ubuntu precise (12.04.2 LTS)
CPUs: 8
Total Memory: 15.68 GiB
Name: a198
ID: HHQ2:EHCP:IOJI:IVTC:CCXZ:QVOR:HHJ2:TJP3:SOE4:OXXA:2YLC:5GMO

uname -a:
Linux a198 3.14.39-3.14.2.1-amd64-15541224 #1 SMP Wed Jun 24 14:09:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):
physical

List the steps to reproduce the issue:
1. stop the docker daemon
2. start the docker daemon

Describe the results you received:
Occasionally there is a 10-20 minute delay start the docker process
time="2015-07-16T18:57:40Z" level=info msg="+job serveapi(unix:///var/run/docker.sock)"
time="2015-07-16T18:57:40Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
time="2015-07-16T19:16:44Z" level=info msg="+job init_networkdriver()"
time="2015-07-16T19:16:45Z" level=info msg="-job init_networkdriver() = OK (0)"
time="2015-07-16T19:16:45Z" level=info msg="Loading containers: start."
time="2015-07-16T19:16:45Z" level=info msg="Loading containers: done."
time="2015-07-16T19:16:45Z" level=info msg="docker daemon: 1.6.2 7c8fca2; execdriver: native-0.2; graphdriver: aufs"

Describe the results you expected:
Other times the docker server starts immediately:
time="2015-07-17T10:39:12Z" level=info msg="+job serveapi(unix:///var/run/docker.sock)"
time="2015-07-17T10:39:12Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
time="2015-07-17T10:39:17Z" level=info msg="+job init_networkdriver()"
time="2015-07-17T10:39:17Z" level=info msg="-job init_networkdriver() = OK (0)"
time="2015-07-17T10:39:17Z" level=info msg="Loading containers: start."
time="2015-07-17T10:39:17Z" level=info msg="Loading containers: done."
time="2015-07-17T10:39:17Z" level=info msg="docker daemon: 1.6.2 7c8fca2; execdriver: native-0.2; graphdriver: aufs"

**Comment by unclejack** [comment] 2015-07-22 08:57
Your system is set up with a custom kernel on Ubuntu 12.04. Canonical doesn't support such custom setups and the Docker project doesn't support that either.

Regarding the specific problem you've reported, it's most likely a problem with your disk IO. I've seen this before and it can be reproduced easily.

**Comment by unclejack** [comment] 2015-08-04 09:37
I'm going to close this issue as it seems to be related to slow disk IO. On my dev box, I've got 432 images right now and the daemon starts in less than 2 seconds.

Please feel free to comment if you're seeing this problem and you've confirmed that your disk IO isn't the bottleneck.

**Closed by unclejack** 2015-08-04 09:37 UTC
