### ISSUE TITLE
Can't add O_APPEND to fd with fcntl()

### ISSUE THREAD

**Issue by sirainen** [docker/docker#20199] opened 2016-02-10 19:01 UTC
Test C program, which works outside Docker but not inside. The end result is supposed to be that the foo file contains "foofoo", but inside Docker it only contains "foo" because O_APPEND is silently ignored. It works if open() flags directly contain O_APPEND. This bug causes Dovecot server to corrupt files when running it in Docker.

Version: 1.10.0-0~jessie

```
// gcc test.c -o test && ./test
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>

int main(int argc, char *argv[]) {
    unlink("foo");
    if (fork() < 0)
        return 1;

    int fd = open("foo", O_RDWR | O_CREAT, 0600);
    if (fd == -1) {
        perror("open()");
        return 1;
    }
    if (fcntl(fd, F_SETFL, O_APPEND) < 0)
        perror("fcntl()");
    write(fd, "foo", 3);
    return 0;
}
```

$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 131
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 147
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.818 GiB
Name: docker-01
ID: SOBD:O3GA:ZLIW:5SPC:LF6Y:UIDE:HNGI:D5KB:IVIG:D5I2:OZCB:CGKR
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Comment by cpuguy83** [comment] 2016-02-10 20:49
Does this only happen on 1.10?
What about if you add `--security-opt seccomp:unconfined` to your `docker run`?

**Comment by cmouse** [comment] 2016-02-10 20:50
This would appear to be a bug in AUFS kernel driver on 3.16.0 on debian jessie.

**Comment by AkihiroSuda** [comment] 2016-02-11 04:01
I can also reproduce this with 4.2.0-27-generic (Ubuntu 15.10).

This bug seems to have been reported 5 years ago (kernel 2.6.39): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=627782

**Comment by AkihiroSuda** [comment] 2016-02-11 05:28
Improved the test code:
 * Verified that `fork()` is not related
 * Verified that `write()` is not returning an error
 * Verified that `st_size` is not set to zero after `open()` without `O_APPEND`.

### Code
```c
// gcc test.c -o test && ./test
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>

void check_error(int rc, const char *s)
{
        if (rc < 0) {
                perror(s);
                exit(EXIT_FAILURE);
        }
}

void cat(const char *fname)
{
        char buf[128];
        int rc;
        printf("--- cat begin ---\n");
        rc = snprintf(buf, sizeof(buf), "cat %s", fname);
        check_error(rc, "snprintf");
        rc = system(buf);
        printf("--- cat end(rc=%d) ---\n", rc);
}

void print_stat(int fd, const char *s)
{
        int rc;
        off_t pos;
        struct stat st;
        pos = lseek(fd, 0, SEEK_CUR);
        check_error(pos, "lseek");
        printf("pos(%s)=%ld\n", s, pos);
        rc = fstat(fd, &st);
        check_error(rc, "fstat");
        printf("st_size(%s)=%ld\n", s, st.st_size);
}

int main(int argc, char *argv[])
{
        int rc;
        int i;
        char *fname = "foo";
        rc = unlink(fname);
        if (rc < 0 && errno != ENOENT) {
                check_error(rc, "unlink");
        }
        for (i = 0; i < 2; i++) {
                int fd;
                printf("=== i=%d begin ===\n", i);

                /*** open ***/
                fd = open(fname, O_RDWR | O_CREAT, 0600);
                check_error(fd, "open");
                print_stat(fd, "after open");

                /*** fcntl ***/
                rc = fcntl(fd, F_SETFL, O_APPEND);
                check_error(rc, "fcntl");
                print_stat(fd, "after fcntl");

                /*** write ***/
                char *s = i == 0 ? "foo\n" : "bar\n";
                rc = write(fd, s, strlen(s));
                check_error(rc, "write");
                print_stat(fd, "after write");

                /*** close ***/
                rc = close(fd);
                check_error(rc, "close");
                printf("=== i=%d end ===\n", i);

                /*** cat ***/
                cat(fname);
        }
        return 0;
}
```
### Actual
```
=== i=0 begin ===
pos(after open)=0
st_size(after open)=0
pos(after fcntl)=0
st_size(after fcntl)=0
pos(after write)=4
st_size(after write)=4
=== i=0 end ===
--- cat begin ---
foo
--- cat end(rc=0) ---
=== i=1 begin ===
pos(after open)=0
st_size(after open)=4
pos(after fcntl)=0
st_size(after fcntl)=4
pos(after write)=4
st_size(after write)=4
=== i=1 end ===
--- cat begin ---
bar
--- cat end(rc=0) ---
```
### Expected
```
=== i=0 begin ===
pos(after open)=0
st_size(after open)=0
pos(after fcntl)=0
st_size(after fcntl)=0
pos(after write)=4
st_size(after write)=4
=== i=0 end ===
--- cat begin ---
foo
--- cat end(rc=0) ---
=== i=1 begin ===
pos(after open)=0
st_size(after open)=4
pos(after fcntl)=0
st_size(after fcntl)=4
pos(after write)=8
st_size(after write)=8
=== i=1 end ===
--- cat begin ---
foo
bar
--- cat end(rc=0) ---
```

**Comment by AkihiroSuda** [comment] 2016-02-11 06:01
O_APPEND is implemented in `mm/filemap.c:generic_write_checks()`.
http://lxr.free-electrons.com/source/mm/filemap.c?v=4.2#L2300

However, `fs/aufs/f_op.c:aufs_write_iter()` seems not calling `mm/filemap.c:generic_write_checks()`.
https://github.com/sfjro/aufs4-linux/blob/0f27010bee7f7fdf1b9e690c350ac2c482ce5acc/fs/aufs/f_op.c#L349

I'll look on this.

**Comment by AkihiroSuda** [comment] 2016-02-11 16:30
This quick workaround seems working with my Ubuntu kernel 4.2.0-27.32 (underlying fs is ext4).

In this workaround, all the write operations are handled by `aufs_write_iter` rather than `aufs_write`.
`aufs_write_iter` calls ext4's `write_iter`, and the `write_iter` calls `generic_write_checks()`.

```patch
diff --git a/fs/aufs/f_op.c b/fs/aufs/f_op.c
index 2c34864..efc46bc 100644
--- a/fs/aufs/f_op.c
+++ b/fs/aufs/f_op.c
@@ -708,8 +708,8 @@ const struct file_operations aufs_file_fop = {
 
        .llseek         = default_llseek,
 
-       .read           = aufs_read,
-       .write          = aufs_write,
+       //      .read           = aufs_read,
+       //      .write          = aufs_write,
        .read_iter      = aufs_read_iter,
        .write_iter     = aufs_write_iter,
```

**Comment by AkihiroSuda** [comment] 2016-02-12 07:07
Posted to aufs-users: http://permalink.gmane.org/gmane.linux.file-systems.aufs.user/5388

**Comment by thaJeztah** [comment] 2016-02-13 13:42
Thanks @AkihiroSuda!

**Comment by AkihiroSuda** [comment] 2016-03-02 02:18
The new AUFS release supported `fcntl(F_SETFL,..)`.
https://sourceforge.net/p/aufs/mailman/message/34896006/

cc @tianon

**Comment by AkihiroSuda** [comment] 2016-04-14 03:14
I confirmed Boot2Docker v1.10.0 (AUFS v20160301) has resolved the issue, using my test code (note that I didn't test dovecot) https://github.com/docker/docker/issues/20199#issuecomment-182719550

Is this issue closable?
Or should we ping Canonical, Debian, and perhaps other distributors to merge AUFS v20160301 and then close this issue?

I believe this issue is not specific to dovecot.
(I didn't test, but [polymake/polymake](https://github.com/polymake/polymake/blob/V2.14/lib/core/src/pipestream.cc#L69) seems hitting this issue)
I fear someone maybe facing this corruption without knowing this issue, that is why I think it's worth pinging distributors.

**Comment by cmouse** [comment] 2016-04-14 05:16
I concur it is not dovecot specific and the test case provided is sufficient. From dovecot side you can close the issue.

**Comment by thaJeztah** [comment] 2016-04-14 11:02
ping @tianon wdyt? should we try and get this fix into Debian/Ubuntu?

**Comment by tianon** [comment] 2016-04-18 19:50
I think Ubuntu would probably be up for doing so (since it fixes known bugs), but I don't know whether Debian would.  If someone wants to champion the cause and poke the downstreams, I think there might be some success to be had, but otherwise it's likely just worth adding this to the list of errata for AUFS (especially since it's fixed in later versions of AUFS, so there is at least some recourse available, even if the distros haven't picked up the update).

@AkihiroSuda what are your thoughts?  You've made those prods downstream before, and are familiar with the issue here -- do you think it's severe enough to warrant prodding downstreams and/or to have them accept and apply a bump?

**Comment by AkihiroSuda** [comment] 2016-04-19 03:04
@tianon Thank you for the comment.
I think this issue is not so severe because only a few app is known to be affected, although potentially other apps can be affected as well.

So my thought is to close the issue right now, and then poke distributors (with a middle priority).

I know there has been a tracker for Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=627782
I'll test the patch with Debian kernel and poke Debian maintainers.

Do you know there is a corresponding tracker for Ubuntu?
If not, do you know who in Canonical is aware of the issue?

**Comment by AkihiroSuda** [comment] 2016-12-05 09:38
Ubuntu 16.10 uses AUFS 20160912.

I'm closing this issue, but please reopen if you have different opinion

@thaJeztah @tianon

**Closed by AkihiroSuda** 2016-12-05 09:38 UTC
Labels: area/kernel, area/storage/aufs, version/1.10

**Comment by thaJeztah** [comment] 2016-12-05 13:01
@AkihiroSuda do you know if this was also fixed for LTS versions? (e.g. ubuntu 16.04)?
