### ISSUE TITLE
Set static ip-address inside docker box

### ISSUE THREAD

**Issue by lalkrishnak** [docker/docker#9362] opened 2014-11-26 17:33 UTC
How can we set manual ip-address inside docker box?

Thanks,
Lal Krishna

**Comment by unclejack** [comment] 2015-01-05 16:22
This is a duplicate of #4952. I'm going to close this issue in favor of that.

I'm also going to lock this issue to make sure the discussion continues only on #4952.

**Closed by unclejack** 2015-01-05 16:22 UTC
