### ISSUE TITLE
[RFE] default detach key sequence isn't optimal 

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#16679] opened 2015-09-30 14:35 UTC
Description of problem:
docker detach ^P is a reserved command for bash [emacs mode--the default] and for emacs in a terminal

How reproducible:
Always

Actual results:
^P is eaten by the prefix command for the detach ^P ^Q.

Expected results:
^P is previous in emacs or in bash
^P should cursor up or go back in bash history one item.
 
So you have to type ^P ^P to move back in bash history and ^P ^P to move up one line.

uname -a 
Linux dhcp-25-141.bos.redhat.com 4.0.4-303.fc22.x86_64 #1 SMP Thu May 28 12:37:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Docker Version:
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   31b882e
 Built:        Wed Sep 30 14:20:38 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   31b882e
 Built:        Wed Sep 30 14:20:38 UTC 2015
 OS/Arch:      linux/amd64

Docker Info:
Containers: 3
Images: 52
Engine Version: 1.9.0-dev
Storage Driver: devicemapper
 Pool Name: docker-8:3-2097606-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.198 GB
 Data Space Total: 107.4 GB
 Data Space Available: 33.68 GB
 Metadata Space Used: 5.411 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.4-303.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 11.72 GiB
Name: dhcp-25-141.bos.redhat.com
ID: NODU:OCAV:EOZD:CWD3:EEKS:AJCL:ZCKH:B6S7:7247:UVAC:2EAK:3FC2

**Comment by vdemeester** [comment] 2015-09-30 15:06
@shishir-a412ed I think this could be considered a duplicate of #3519 and there is a *new* proposition on that #15666 to make it configuration.

But we can still have discussion on what would be the default though :cat: (but I'm not sure there would be a consensus :sweat_smile:).

**Comment by cpuguy83** [comment] 2015-10-02 13:49
Yeah, this is a dup. Please see #3519

**Closed by cpuguy83** 2015-10-02 13:49 UTC
