### ISSUE TITLE
Docker logs --follow leaks goroutines/memory

### ISSUE THREAD

**Issue by jakolehm** [docker/docker#13014] opened 2015-05-06 09:04 UTC
It seems that each `docker logs -f <container>` adds 5 new goroutines to docker daemon. If this command (or request to docker remote api) is repeated constantly, docker starts to leak goroutines and memory. Somehow these goroutines are not cleaned up even after waiting for over 30 minutes.

Docker version: 1.3.3 - 1.6.0

Steps to reproduce:
1. run `docker logs -f <container>` multiple times 

Actual results:
Docker daemon goroutines (and memory) keeps going up.

Expected results:
Docker daemon cleans up goroutines

**Comment by cpuguy83** [comment] 2015-05-06 16:38
Confirmed that at least the goroutine leak is on master.
After logs logs have stopped streaming there is a net of +4 goroutines that doesn't seem to go away.

Just some initial investigation, the goroutine copying stderr is never closing, but stdout is.

**Comment by cpuguy83** [comment] 2015-05-06 16:39
Also if you remove the container that you've called logs against, goroutines drop back down, and all those stderr streams also get closed.

**Comment by LK4D4** [comment] 2015-05-06 16:43
Probably because there is nothing in `StderrPipe`.

**Comment by cpuguy83** [comment] 2015-05-06 16:45
Ah yes, good point.

**Comment by cpuguy83** [comment] 2015-05-06 16:47
Yep, that's it. Sending stuff to both pipes there is no leak.

**Comment by LK4D4** [comment] 2015-05-06 16:48
There are not so much streams in logs. We can get rid of `wg.Wait` and just select on two channels. If one erroring - close another. Following containers with empty logs still will be a problem.

**Closed** 2015-05-12 20:52 UTC
