### ISSUE TITLE
Non-deterministic TestExecStartFails test

### ISSUE THREAD

**Issue by icecrime** [docker/docker#16598] opened 2015-09-26 00:41 UTC
See [this log](https://jenkins.dockerproject.org/job/Docker-PRs/16646/console):

```
FAIL: docker_cli_exec_test.go:615: DockerSuite.TestExecStartFails

docker_cli_exec_test.go:622:
    c.Fatal("exec error message not received. The daemon might had crashed")
... Error: exec error message not received. The daemon might had crashed
```

**Comment by icecrime** [comment] 2015-09-26 06:03
Ping @vdemeester if interested :panda_face:

**Comment by mountkin** [comment] 2015-09-26 12:55
It's weird. I find that when this test fails, the exit status of the command is 255 and the error message is empty.
The expected behavior when the command is not found is that the exit status is 1 and the error message is something like `exec: "no-such-cmd": executable file not found in $PATH`

**Comment by vdemeester** [comment] 2015-09-26 13:21
@mountkin naively I would think that, when it fails, the container had not yet started when doing exec, and thus.. the error is different -_-

**Comment by mountkin** [comment] 2015-09-26 13:54
@vdemeester If the container had not yet started then the error message should not be empty. But in fact it's an empty string.
Furthermore, the error message in the docker log is as the following:
```
time="2015-09-26T13:47:38.182787915Z" level=error msg="Error running command in existing container e45c2b3695b44e44fc19f1d74364da0ec8a669715659092dc44033d10f205f36: [8] System error: exec: \"no-such-cmd\": executable file not found in $PATH"
time="2015-09-26T13:47:38.182836924Z" level=debug msg="Exec task in container e45c2b3695b44e44fc19f1d74364da0ec8a669715659092dc44033d10f205f36 exited with code -1"
```

I just curious that why the error message and the exit status is not received by the client correctly.

**Comment by mountkin** [comment] 2015-09-26 13:59
Perhaps the HTTP connection was closed by this line https://github.com/docker/docker/blob/master/daemon/container.go#L845, which caused the client not received the error message.

**Comment by cpuguy83** [comment] 2015-09-29 02:11
This is fixed in #16641.... hopefully.

**Comment by cpuguy83** [comment] 2015-09-30 17:48
Going to re-open because I just saw this fail again on CI...
And as discussed with @duglin on IRC, there does seem to be some raciness on whether or not we get any output on the exec failure at all.

**Comment by duglin** [comment] 2015-09-30 17:57
What's odd is that I **think** I see cases where the output is sent over the wire but not shown to the CLI, and I **think** I see cases where its not sent on the wire at all.  But I'm still trying to track it down....

**Comment by vdemeester** [comment] 2015-09-30 21:13
We can add `DockerSuite.TestExecInteractiveStdinClose` to the list :sweat:.

**Comment by LK4D4** [comment] 2015-09-30 21:18
And `TestEventsTimestampFormats`

**Comment by vdemeester** [comment] 2015-09-30 21:18
:sob:

**Comment by cpuguy83** [comment] 2015-10-05 14:59
This looks like it's always been racey, but the test just didn't exist until recently.

Something interesting...
When the output doesn't show up, we get a warning message in the daemon logs (from libcontainer): `signal: killed`

When the output does show up, the warning message in the daemon logs is: `exit status 1`

These messages are coming from here: https://github.com/docker/docker/blob/189d2c79858d08a4cf3454bd7367989a005a4e3b/vendor/src/github.com/opencontainers/runc/libcontainer/container_linux.go#L110

**Comment by cpuguy83** [comment] 2015-10-05 15:49
This log is changing due to different responses from the `Wait()` call here: https://github.com/docker/docker/blob/189d2c79858d08a4cf3454bd7367989a005a4e3b/vendor/src/github.com/opencontainers/runc/libcontainer/process_linux.go#L134-L136

This is of course just some clues as to where this raciness might be occurring.

**Comment by cpuguy83** [comment] 2015-10-05 23:54
opencontainers/runc#316

**Closed** 2015-10-09 02:09 UTC
