### ISSUE TITLE
cant run exec on a container

### ISSUE THREAD

**Issue by galtet** [docker/docker#22881] opened 2016-05-21 12:37 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 47
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 123
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-58-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.507 GiB
Name: galt-tp
ID: DKCR:ZB6N:PW4O:76PF:UZPU:HVZO:XHL4:SRPM:6ACQ:M6T5:AZXN:KVPQ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Steps to reproduce the issue:**
1. sudo docker run -d -t tyrion 
2. sudo docker exec -it dfe8e0ad4c8422256aef03d5ea6d3e4473983dd75ef0dd757bd5a07321ee307d ls

**result output**
rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1"

this issue happens every time i run exec.

**Comment by thaJeztah** [comment] 2016-05-21 12:50
Is this happening with any image? Is the image you started still running?

Given that I don't have access to your "tyrion" image, can you try running;

```
docker run -dt --name foobar alpine sh
docker exec -it foobar ls
```

**Comment by galtet** [comment] 2016-05-21 13:49
ok, i reproduced it with a simple example from docker's user guide:

sudo docker run -d -P training/webapp python app.py
Unable to find image 'training/webapp:latest' locally
latest: Pulling from training/webapp
e190868d63f8: Pull complete 
909cd34c6fd7: Pull complete 
0b9bfabab7c1: Pull complete 
a3ed95caeb02: Pull complete 
10bbbc0fc0ff: Pull complete 
fca59b508e9f: Pull complete 
e7ae2541b15b: Pull complete 
9dd97ef58ce9: Pull complete 
a4c1b0cb7af7: Pull complete 
Digest: sha256:06e9c1983bd6d5db5fba376ccd63bfa529e8d02f23d5079b8f74a616308fb11d
Status: Downloaded newer image for training/webapp:latest
19cc6644d90a46269971fbaa63b132415d6c8558204b3c47ff2bb1c1eb7fe904
galt@galt-tp:~/dev/ops/kai/server/snow$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                     PORTS                     NAMES
19cc6644d90a        training/webapp     "python app.py"     About a minute ago   Up About a minute          0.0.0.0:32768->5000/tcp   suspicious_brahmagupta
f825190b0e97        centos:centos7      "/bin/bash"         5 minutes ago        Exited (0) 5 minutes ago                             prickly_chandrasekhar
galt@galt-tp:~/dev/ops/kai/server/snow$ 
galt@galt-tp:~/dev/ops/kai/server/snow$ 
galt@galt-tp:~/dev/ops/kai/server/snow$ sudo docker exec -it 19cc6644d90a ls
rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1"

**Comment by galtet** [comment] 2016-05-24 00:08
**docker logs**:
`time="2016-05-24T03:05:52.815069217+03:00" level=error msg="Error running exec in container: rpc error: code = 2 desc = \"oci runtime error: exec failed: exit status 1\"\n" 
time="2016-05-24T03:05:52.815131560+03:00" level=error msg="Handler for POST /v1.23/exec/e77ba2ce4f846557c53cb3f964938847783d0f5a0c78a011d9ac20ef2f36587b/start returned error: rpc error: code = 2 desc = \"oci runtime error: exec failed: exit status 1\"" 
2016/05/24 03:05:52 http: response.WriteHeader on hijacked connection
2016/05/24 03:05:52 http: response.Write on hijacked connection
time="2016-05-24T03:05:52.817660809+03:00" level=error msg="Handler for POST /v1.23/exec/e77ba2ce4f846557c53cb3f964938847783d0f5a0c78a011d9ac20ef2f36587b/resize returned error: rpc error: code = 2 desc = \"containerd: processs not found for container\""`

**Comment by agyanttiwari** [comment] 2016-05-24 07:57
I am getting the same problem.

**Comment by thaJeztah** [comment] 2016-05-25 13:53
closing as duplicate of https://github.com/docker/docker/issues/22909

**Closed by thaJeztah** 2016-05-25 13:53 UTC
Labels: status/more-info-needed, version/1.11
