### ISSUE TITLE
multiple "create service" and "service rm" leave orphan containers 

### ISSUE THREAD

**Issue by ezrasilvera** [docker/docker#25225] opened 2016-07-29 13:15 UTC
1) Create many services by looping a "docker service create" (I created 200 services with replica=1)
2) Delete all services   I used:   docker service rm $(docker service list | awk '{print $1 }' )  
repeat (1) and (2) few times.

After that I was ended up with no services (docker service list returned empty list) but many containers in "Created" state (Need to ps -a in order to list them)

Note that in this test "service rm" can be received before the service actually started and then a "service create" with the same name can be received

**Comment by thaJeztah** [comment] 2016-07-29 14:04
Thanks for reporting! This looks like a duplicate of https://github.com/docker/docker/issues/24244, so please continue the discussion over there; feel free to add this description as a comment, as it may contain some information to reproduce the issue

**Closed by thaJeztah** 2016-07-29 14:04 UTC
