### ISSUE TITLE
[1.12rc4] Exposed service ports not accessible via localhost

### ISSUE THREAD

**Issue by Stehsegler** [docker/docker#24847] opened 2016-07-20 15:46 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 34
Server Version: 1.12.0-rc4
Storage Driver: devicemapper
 Pool Name: vg--docker-data
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 2.314 GB
 Data Space Total: 437.8 GB
 Data Space Available: 435.5 GB
 Metadata Space Used: 4.293 MB
 Metadata Space Total: 440.4 MB
 Metadata Space Available: 436.1 MB
 Thin Pool Minimum Free Space: 43.78 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: xxx
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: xxx
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.63 GiB
Name: xxx
ID: xxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://xxx
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Server with CentOS 7

**Steps to reproduce the issue:**
1. `docker service create -p 80:80 nginx`
2. … wait until the corresponding container has started …
3. `curl localhost`

**Describe the results you received:**
Timeout in step 3.

**Describe the results you expected:**
Default page of nginx is retrieved in step 3.

**Additional information you deem important (e.g. issue happens only occasionally):**
`curl`-ing the IP of the physical network interface of the Docker host works, even from the host itself. When exposing the port conventionally during a `docker run`, it is accessible via localhost.

**Comment by vdemeester** [comment] 2016-07-20 15:47
I think it's a duplicate of #24830

**Comment by Stehsegler** [comment] 2016-07-20 15:51
Don't think so. #24830 is about ports exposed during a `docker run`. This issue is about ports exposed during a `docker service create`.

**Comment by justincormack** [comment] 2016-07-20 15:55
Can you re check on master, there have been some changes vs rc4?

**Comment by Stehsegler** [comment] 2016-07-20 17:05
Seems to work in master (tried the binaries from https://master.dockerproject.org/ - Git commit 2a78789 - on an Ubuntu 16.04 VM, as they do not work on CentOS due to the devicemapper storage driver).

Thus closing this issue. Thank you!

**Comment by Stehsegler** [comment] 2016-07-27 11:20
Reopening and ping @justincormack, as this still does not work for me in 1.12.0-rc5 on CentOS 7. Shouldn't this be fixed before 1.12 GA?

**Comment by Stehsegler** [comment] 2016-08-02 07:05
Still not working for me on RHEL 7 in 1.12.0 final.

**Comment by thaJeztah** [comment] 2016-08-02 13:03
I'm able to reproduce this; this works on an Ubuntu 16.04 host, but doesn't work on CentOS. Tested on a fresh CentOS 7.2 Droplet on DigitalOcean

ping @mrjana @aboch PTAL

**Comment by sanimej** [comment] 2016-08-02 15:21
@thaJeztah @Stehsegler Can you try curl -4 localhost ?

You might have an entry for localhost in the /etc/hosts with a ipv6 loopback. In that case curl will default to IPv6.

**Comment by thaJeztah** [comment] 2016-08-02 15:23
@sanimej good call, let me give that a try; spinning up a new box

**Comment by thaJeztah** [comment] 2016-08-02 15:27
@sanimej spot on!

```
curl localhost
^C
[root@centos-2gb-ams3-01 ~]# curl -4 localhost
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by Stehsegler** [comment] 2016-08-03 06:37
Indeed, `curl -4 localhost` or alternatively removing the IPv6 entry for localhost in `/etc/hosts` is working. I think this issue is a duplicate of #24379 then, so I'm closing it. Thank you for your help!

**Comment by sanimej** [comment] 2016-08-03 20:31
@thaJeztah @Stehsegler Thanks for confirming. #24379 is not the same issue though.

**Comment by Stehsegler** [comment] 2016-08-04 05:42
@sanimej Where exactly do you see the difference between this issue and #24379? In the end, they're both about exposed service ports not reachable via IPv6 addresses of the hosts. Do you think we should reopen?

**Comment by sanimej** [comment] 2016-08-04 06:18
#24379 is for service to be available over IPv6. Its not supported yet for overlay networks. My interpretation of this issue was that its filed for curl localhost not working. We have clarified why it wasn't working and `curl -4` can be used. If you are also looking for service to be reachable over ipv6 then yes, its a duplicate of #24379.

**Comment by Stehsegler** [comment] 2016-08-04 06:38
Yes, of course, when viewn from this perspective, you are correct.

**Comment by sanimej** [comment] 2016-08-04 06:53
@Stehsegler Not sure why you reopened this issue. As I explained earlier IPv6 overlay is not supported yet. `curl localhost` will try ipv6 if localhost resolves to v6 address. You can use `curl -4` to use IPv4. If you are expecting the service to work over IPv6 its a duplicate of #24379. Either way we can close this issue.

**Closed by sanimej** 2016-08-04 06:53 UTC
Labels: area/swarm, group/networking, kind/bug, version/1.12

**Comment by Stehsegler** [comment] 2016-08-04 07:30
Okay, sorry, was based on a misunderstanding then.
