### ISSUE TITLE
arm builds missing from regular apt repo (1.12.1)

### ISSUE THREAD

**Issue by withinboredom** [docker/docker#25879] opened 2016-08-19 14:30 UTC
However, it is present in test, and experimental.

Expect:
`curl -fsSL https://get.docker.com/ | sh` to install docker 1.12.1 as `curl -fsSL https://test.docker.com/ | sh` installed 1.12.1-rc2

Current script output:

``` shell
$ curl -fsSL https://get.docker.com/ | sh
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
modprobe: FATAL: Module aufs not found.
Warning: current kernel is not supported by the linux-image-extra-virtual
 package.  We have no AUFS support.  Consider installing the packages
 linux-image-virtual kernel and linux-image-extra-virtual for AUFS support.
+ sleep 10
+ sudo -E sh -c apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.QXDupgA82l --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server ha.pool.sks-keyservers.net
gpg: key 2C52609D: "Docker Release Tool (releasedocker) <docker@docker.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
+ break
+ sudo -E sh -c apt-key adv -k 58118E89F3A912897C070ADBF76221572C52609D >/dev/null
+ sudo -E sh -c mkdir -p /etc/apt/sources.list.d
+ dpkg --print-architecture
+ sudo -E sh -c echo deb \[arch=armhf\] https://apt.dockerproject.org/repo debian-jessie main > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
Hit http://archive.raspberrypi.org jessie InRelease
Hit http://mirrordirector.raspbian.org jessie InRelease
Hit https://apt.dockerproject.org debian-jessie InRelease
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages
Hit https://apt.dockerproject.org debian-jessie/main armhf Packages
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Get:1 https://apt.dockerproject.org debian-jessie/main Translation-en_US [454 B]
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages
Get:2 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Hit https://packagecloud.io jessie InRelease
Hit https://packagecloud.io jessie InRelease
Hit https://packagecloud.io jessie/main armhf Packages
Get:3 https://packagecloud.io jessie/main Translation-en_US [162 B]
Ign http://archive.raspberrypi.org jessie/main Translation-en_US
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Get:4 https://apt.dockerproject.org debian-jessie/main Translation-en_US [454 B]
Get:5 https://packagecloud.io jessie/main Translation-en [162 B]
Get:6 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]
Get:7 https://apt.dockerproject.org debian-jessie/main Translation-en_US [454 B]
Get:8 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]
Get:9 https://apt.dockerproject.org debian-jessie/main Translation-en_US [454 B]
Hit https://packagecloud.io jessie/main armhf Packages
Get:10 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]
Get:11 https://packagecloud.io jessie/main Translation-en_US [162 B]
Get:12 https://apt.dockerproject.org debian-jessie/main Translation-en_US [454 B]
Ign https://apt.dockerproject.org debian-jessie/main Translation-en_US
Get:13 https://packagecloud.io jessie/main Translation-en [162 B]
Get:14 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]
Ign https://apt.dockerproject.org debian-jessie/main Translation-en
Get:15 https://packagecloud.io jessie/main Translation-en_US [162 B]
Get:16 https://packagecloud.io jessie/main Translation-en [162 B]
Get:17 https://packagecloud.io jessie/main Translation-en_US [162 B]
Get:18 https://packagecloud.io jessie/main Translation-en [162 B]
Get:19 https://packagecloud.io jessie/main Translation-en_US [162 B]
Get:20 https://packagecloud.io jessie/main Translation-en [162 B]
Get:21 https://packagecloud.io jessie/main Translation-en_US [162 B]
Get:22 https://packagecloud.io jessie/main Translation-en [162 B]
Get:23 https://packagecloud.io jessie/main Translation-en_US [162 B]
Get:24 https://packagecloud.io jessie/main Translation-en [162 B]
Get:25 https://packagecloud.io jessie/main Translation-en_US [162 B]
Get:26 https://packagecloud.io jessie/main Translation-en [162 B]
Get:27 https://packagecloud.io jessie/main Translation-en_US [162 B]
Ign https://packagecloud.io jessie/main Translation-en_US
Get:28 https://packagecloud.io jessie/main Translation-en [162 B]
Ign https://packagecloud.io jessie/main Translation-en
Get:29 https://packagecloud.io jessie/main Translation-en_US [162 B]
Ign https://packagecloud.io jessie/main Translation-en_US
Get:30 https://packagecloud.io jessie/main Translation-en [162 B]
Ign https://packagecloud.io jessie/main Translation-en
Reading package lists... Done
Reading package lists...
Building dependency tree...
Reading state information...
docker-engine is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ sudo -E sh -c docker version
Client:
 Version:      1.12.1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   236317f
 Built:        Wed Aug 17 05:04:46 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.12.1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   236317f
 Built:        Wed Aug 17 05:04:46 2016
 OS/Arch:      linux/arm

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker <user>

Remember that you will have to log out and back in for this to take effect!
```

**Comment by thaJeztah** [comment] 2016-08-20 12:56
ping @mlaventure

**Comment by tiborvass** [comment] 2016-08-22 17:24
@withinboredom We decided to only release raspbian jessie for now, because of issues we discovered during rc2. So this issue is unfortunately expected. I'll leave this open to track it.

**Comment by flixr** [comment] 2016-08-30 15:30
@tiborvass what are the remaining relevant issues? All the ones I could find were already fixed:
 #25124 #25591
Anything I can help out with?

**Comment by thom-nic** [comment] 2016-09-23 17:40
I just discovered this while attempting to install on a debian/armhf device.  In my case I was following instructions at https://docs.docker.com/engine/installation/linux/debian/ and took me a while to figure out the package isn't in the repo (well, it is in jesse/main/armhf but it's being filtered out because I'm not on raspbian from the sound of it...)

**Comment by flixr** [comment] 2016-10-10 16:43
@tiborvass any updates here?

**Comment by mlaventure** [comment] 2016-10-10 16:59
Until we figure out a way to avoid the artifacts to override themselves, the `raspbian-jessie` artifacts should work on all debian-based `armhf` machine (just update the source.list to force it to use `raspbian-jessie` distro)

You can also use the static binaries directly (unfortunately, the generated tar is only complete since `1.12.2-rc3`): https://test.docker.com/builds/Linux/armel/docker-1.12.2-rc3.tgz

**Comment by flixr** [comment] 2016-10-11 16:11
`raspbian-jessie` doesn't work for me on Ubuntu 14.04...
Is there an issue about this "artifacts overriding themselves" that I can track and maybe help out with?

**Comment by mlaventure** [comment] 2016-10-11 16:39
@flixr do the static binaries work?

I don't think we have a specific issue tracking the problem otherwise, @tiborvass ?

**Comment by flixr** [comment] 2016-10-12 16:08
Didn't test the static binaries, I would assume they work... it's just the deb from jessie that has wrong dependencies for ubuntu trusty...

**Comment by mlaventure** [comment] 2016-10-12 16:27
@flixr unfortunately the static binaries will be the easiest way for you to go for now then

**Comment by flixr** [comment] 2016-10-12 16:37
I still don't understand what the issue is why it can't be packaged for the other distris...
If I would understand the problem, I could spend a bit of time and try to find a fix...

**Comment by mlaventure** [comment] 2016-10-12 16:42
When generated the deb packages, both `debian-jessie` and `raspbian-jessie` end up naming their `.deb` the same and overwriting each other.

So I guess we could still generate the `ubuntu-trusty` one without conflict. I'm not sure why both `debian-jessie` and `ubuntu-trusty` were removed as a result.

@tiborvass ?

**Comment by tiborvass** [comment] 2016-10-12 17:12
@mlaventure It had something to do with different versions of ARM I believe. cc @DieterReuter

**Comment by DieterReuter** [comment] 2016-10-12 19:32
@mlaventure as we (@tiborvass and I) discovered this problem with overwriting debian/raspbian .deb in 1.12.1 we run out of time and had to play it save. So we decided to keep the raspbian .deb which is able to run on Raspbian and Debian (it's built for ARMv6). Ubuntu wasn't tested at all to that time and we decided to skip it, too.

Best way would be to fix the issues with overwriting debian/raspbian .debs and to test the Ubuntu .deb. Any additional steps or thoughts, @tiborvass?

**Comment by flixr** [comment] 2016-10-12 19:39
I'm running the older ubuntu deb and it's working fine.
If needed I can probably build 1.12.2 on my nvidia tegra and re-test...

Probably all armhf deb builds should be updated to have the RUNC buildtags as well, as in #27327

**Comment by calston** [comment] 2016-11-01 11:43
@tiborvass But raspbian jessie is also broken

```W: Failed to fetch https://apt.dockerproject.org/repo/dists/debian-jessie/main/binary-armhf/Packages  Hash Sum mismatch
```

**Comment by calston** [comment] 2016-11-01 11:57
Seems if lsb_release is not installed the script can't detect if you're on raspbian

**Comment by tophj-ibm** [comment] 2016-11-02 15:26
@calston how are you trying to install docker? Using a fresh version of raspbian-lite and the install script from above I've been unable to recreate that issue

**Comment by DieterReuter** [comment] 2016-11-02 16:05
A fresh Raspbian Lite just works! @calston, in your repo the "debian/jessie" causes the problems because there is no package for Debian available!

**Comment by calston** [comment] 2016-11-03 03:16
Yeah, my non-fresh several times upgraded from who knows what Raspbian image just doesn't have lsb_release by default. Instead of throwing an error or something the install script mistakenly choses Debian.

**Comment by mlaventure** [comment] 2016-11-03 14:48
The script is technically not the recommended way of installing, but I see that specifics instructions for raspbian is missing from the [docs](https://docs.docker.com/engine/installation/linux/). I'll make a PR to add them.

**Comment by justincormack** [comment] 2016-12-21 15:50
I think this is resolved now, there are now several versions for different Arm distros. Going to close this now, if the distro you want is still missing please open a pull request.

**Closed by justincormack** 2016-12-21 15:50 UTC
Labels: kind/enhancement, platform/arm, version/1.12
