### ISSUE TITLE
Docker: invalid tar header

### ISSUE THREAD

**Issue by kroeliebuschie** [docker/docker#14022] opened 2015-06-18 18:28 UTC
I've created an image for docker on my Ubuntu 14.04 with the latest version of Docker (1.6.2):
```bash
sudo docker save 'something' > something-image.tar
```
On a mac I installed the latest Boot2docker and run this
```bash
docker load < something-image.tar
```
Which gives this error:
```bash
FATA[0489] Error response from deamon: Untar exit status 1 archive/tar: 
invalid tar header
```
Getting the same error in Windows Boot2docker.
But if I try to load this image in Ubuntu, everything works just fine.

**Comment by vtolstov** [comment] 2015-06-26 14:21
+1 using latest docker release.

**Comment by thaJeztah** [comment] 2015-08-02 16:06
ping @vbatts I know you've been busy on archives (although not this particular issue), perhaps you have an idea on this?

**Comment by vbatts** [comment] 2015-08-02 19:18
I can't reproduce, but it sounds like a b2d issue.

**Comment by thaJeztah** [comment] 2015-08-02 21:34
Thanks for looking, @vbatts (sorry for reeling you in :smile:)

I don't remember seeing this reported in boot2docker, but it's possible I missed.

@kroeliebuschie Wondering, if you ssh into the virtual machine, and do the docker load from *inside* the virtual machine, do you get the same result, or only when doing the docker load from the Windows or Mac client?

**Comment by kroeliebuschie** [comment] 2015-09-24 09:03
issue did not occur in the new docker version.

**Comment by thaJeztah** [comment] 2015-09-24 09:23
Thanks for reporting back @kroeliebuschie, I'll close this issue, but feel free to comment if you run into this again

**Closed by thaJeztah** 2015-09-24 09:23 UTC
Labels: kind/bug

**Comment by piranna** [comment] 2015-10-29 12:56
I've got this same problem on Ubuntu 15.10 both with Docker 1.6.2 and latest 1.8.3. I'm trying to initialice a Docker container with a tar file of NodeOS using `import - barebones < out/latest` and get

```
Error response from daemon: Untar re-exec error: exit status 1: output: archive/tar: invalid tar header
```

I'm not fully sure if it's related, but the tar file is converted from a `cpio` file generated with Linux kernel `gen_init_cpio` by using [tar-stream](https://github.com/mafintosh/tar-stream) Node.js module. The same tar file give errors listing its content with the `tar` command and a core-dump trying to open it with file-roller, but works correctly with [vagga](https://github.com/tailhook/vagga) (another LXC containers administrator).

You can read more info at https://github.com/mafintosh/tar-stream/issues/44. As you can see there, seems to be related to the usage of symlinks, but I've been checking the generated tar file content with an hex editor and didn't found any diference with working ones... :-/

**Comment by vbatts** [comment] 2015-10-29 15:23
@piranna can you test with the docker 1.9 release candidate?

**Comment by piranna** [comment] 2015-10-29 16:20
Same problem with Docker version 1.9.0-rc3, build 2100b94

**Comment by vbatts** [comment] 2015-10-30 00:15
@piranna how can i easily reproduce the steps you're doing?

**Comment by piranna** [comment] 2015-10-30 00:36
The easiest way is to try to use the generated tar file, you can download it from https://dropfile.to/ZGsPn (link expire in 24 hours).

The long path would be generate a cpio file with some symlinks using the `gen_init_cpio` tool included in the Linux kernel and later convert it to a tar file using `cpio-stream` and `tar-stream` modules, for example with a script like [cpio2tar](https://github.com/NodeOS/NodeOS/blob/vagga/node_modules/nodeos-barebones/scripts/cpio2tar).

**Comment by piranna** [comment] 2015-10-30 00:40
By the way, I'm trying to create a container filesytem from that tar file using `docker import - barebones < barebones.tar`, if that matter.

**Comment by vbatts** [comment] 2015-10-30 14:36
I'm going to say this is an issue with the tooling before it ever reaches docker.
```bash
$ tar tvf barebones.tar 
tar: Substituting `.' for empty member name
d--x--x--x 0/0               0 2015-10-29 08:18 
dr-xr-xr-x 0/0               0 2015-10-29 08:18 bin
d--------- 0/0               0 2015-10-29 08:18 dev
d--x--x--x 0/0               0 2015-10-29 08:18 lib
crw------- 0/0             3,1 2015-10-29 08:18 dev/console
-r-xr-xr-x 0/0          651800 2015-10-29 08:18 lib/libc.so
lr-xr-xr-x 0/0               8 2015-10-29 08:18 lib/ld-musl-x86_64.so.1 -> libc.so
tar: Skipping to next header
-r--r--r-- 0/0         1250352 2015-10-29 08:18 lib/libstdc++.so.6.0.17
lr--r--r-- 0/0              20 2015-10-29 08:18 lib/libstdc++.so.6 -> libstdc++.so.6.0.17
tar: Skipping to next header
l--x------ 0/0               9 2015-10-29 08:18 init -> bin/node
tar: Exiting with failure status due to previous errors
```
That is GNU `tar` failing on the archive you provided.

**Comment by piranna** [comment] 2015-10-30 18:41
Yes, I put that on the tar-stream repo too, seems to be a problem related
to the symlinks, but since vagga can use that files I'm not sure if it's a
problem of tar-stream not generating the tar files correctly or docker not
parsing them... :-/

**Comment by vbatts** [comment] 2015-10-30 18:44
like I said, the problem is _outside_ of docker. If some other tooling is parsing them, then perhaps they made a workaround, but the tar archive is malformed.

**Comment by piranna** [comment] 2015-10-30 18:51
Sh*t :-( Any clue why it would be malformed? I've only be able to identify
the bad/skipped entries are the ones after a symlink... :-/

**Comment by mickours** [comment] 2016-02-19 12:53
I have the same error on a tar.gz file using ``docker import``. The command ``tar -xf`` on the same file is working fine.

**Comment by thaJeztah** [comment] 2016-02-19 12:57
@mickours is that on docker 1.10.0/1.10.1? Because we identified an issue in docker 1.10, where compressed images aren't decompressed. This issue is fixed in this PR https://github.com/docker/docker/pull/20367. Also see https://github.com/docker/docker/issues/20296

**Comment by mickours** [comment] 2016-02-20 09:36
Yes it was 1.10.1. I downgrade to 1.9.1 and it works.

Thanks

**Comment by thaJeztah** [comment] 2016-02-20 10:17
@mickours we'll be releasing a 1.10.2 patch release soon; if you want to test if it resolves your issue; a release candidate is available; https://github.com/docker/docker/releases/tag/v1.10.2-rc1

**Comment by amobdlp** [comment] 2016-03-20 22:07
I have the same (it seems to be..) problem with docker 1.10.3:
sudo docker --version
Docker version 1.10.3, build 20f81dd
>In my docker file i have the line:
ADD ftpserver-1.0.5.tar.gz /usr/local/bin/
and the docker build command fails with
Step 3 : ADD ftpserver-1.0.5.tar.gz /usr/local/bin/
Untar re-exec error: exit status 1: output: archive/tar: invalid tar header
Surely I am doing a mistake... Of course the ftpserver-1.0.5.tar.gz is expanded normaly with a tar -xvfz command...
My DockerFile:
>
FROM centos
MAINTAINER  amobdlp
ADD ftpserver-1.0.5.tar.gz /usr/local/bin/
VOLUME /var/apache-ftp/res
ENTRYPOINT [ "/usr/local/bin/apache-ftpserver-1.0.5/bin/ftpd.sh" ]
CMD [ "/var/apache-ftp/res/conf/ftpd-typical.xml" ]
EXPOSE 2121
Thanks

**Comment by fredriksvensson** [comment] 2016-05-11 19:43
I have what seem to be the same problem with:
Docker version 1.11.1, build 5604cbe

**Comment by piranna** [comment] 2016-05-11 22:42
GNU tar requires symbolic links has set their sizes to zero, that's why it didn't worked with Docker but it did with vagga.

**Comment by j2gl** [comment] 2016-06-02 14:19
+1 @fredriksvensson, I got the same problem with ADD and tar.gz file.

I'm using ```FROM ubuntu:16.04``` in MacOS environment

```
Step 3 : ADD apache-activemq-5.2.0-bin.tar.gz /opt
Untar re-exec error: exit status 1: output: archive/tar: invalid tar header
```
Docker version info:
```
Client:
 Version:      1.11.1
 Git commit:   5604cbe

Server:
 Version:      1.11.1
 Git commit:   5604cbe
```

**Comment by akatrevorjay** [comment] 2017-02-03 07:13
I'm having this issue with `docker-compose` `1.10.1` and `docker` `1.13.0`

**Comment by thaJeztah** [comment] 2017-02-03 07:28
@akatrevorjay please open a new issue with more details and steps to reproduce; the original issue reported here was resolved

**Comment by chepchepcirkus** [comment] 2017-02-10 13:39
Docker version 1.13
I reproduce this issue when i save my image by this way: 
`docker save image > image.tar`
if you use the --output argument as follow
`docker save --output=image.tar image`
Archive seems to be valid

**Comment by thaJeztah** [comment] 2017-02-10 18:56
@chepchepcirkus I'm not able to reproduce your issue, please open a new issue with details if `docker save image > image.tar` does not work

**Comment by thaJeztah** [comment] 2017-02-10 18:57
I'm locking the discussion on this issue because the original issue was resolved; if you're still seeing this please open a new issue
