### ISSUE TITLE
docker-machine wont connect to manager node in jenknis script

### ISSUE THREAD

**Issue by pavel1860** [docker/docker#27245] opened 2016-10-09 22:56 UTC
hi
I'm trying to create jenkins script to deploy services to swarm cluster. I'm using docker-machine to control the cluster from the jenkins machine. everything is working fine if I execute it from bash command line with jenkins user, but when I trying to do the same from jenknis pipeline it issues me the following 
`Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.`

the script that I'm using is:
`node('master'){
stage 'test'
        sh 'docker-machine ls'
        sh 'eval $(docker-machine env manager0)'
        sh 'sudo docker node ls'
}
`

the `sudo docker node ls` creates the error. from bash the same commands work fine.

**Comment by ehazlett** [comment] 2016-10-10 16:04
Docker Machine does not manage Swarm mode clusters only Swarm.  See the difference here: https://docs.docker.com/engine/swarm/.

**Comment by thaJeztah** [comment] 2016-10-11 14:36
Looks like this is not a bug, and the question is answered, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2016-10-11 14:36 UTC
Labels: kind/question
