### ISSUE TITLE
[1.10.0-rc1] VOLUME /any/dir hangs docker build

### ISSUE THREAD

**Issue by imikushin** [docker/docker#19762] opened 2016-01-27 03:30 UTC
Tested to happen with client on Linux and OS X. 
```
$ cat Dockerfile

FROM alpine
VOLUME /usr/local/bin
```

```
$ docker build -t qq .

Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine
 ---> 14f89d0e6257
Step 2 : VOLUME /usr/local/bin
```
The build hangs here.
When sent `kill -3` it logs the following: 
```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine
 ---> 14f89d0e6257
Step 2 : VOLUME /usr/local/bin
SIGQUIT: quit
PC=0x60b9b m=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0x107, 0xc8202fc780, 0x60, 0x30, 0x60f620, 0x958820, 0x53869, 0xffffffffffffffff, 0x30, 0x7fff5fbff52c, ...)
	/usr/local/go/src/runtime/sys_darwin_amd64.s:407 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x30)
	/usr/local/go/src/runtime/os1_darwin.go:395 +0xe5
runtime.semasleep.func1()
	/usr/local/go/src/runtime/os1_darwin.go:411 +0x29
runtime.systemstack(0x7fff5fbff530)
	/usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
	/usr/local/go/src/runtime/os1_darwin.go:412 +0x36
runtime.notesleep(0x9590f0)
	/usr/local/go/src/runtime/lock_sema.go:169 +0x100
runtime.stopm()
	/usr/local/go/src/runtime/proc1.go:1136 +0x112
runtime.findrunnable(0xc82001d500, 0x0)
	/usr/local/go/src/runtime/proc1.go:1538 +0x69e
runtime.schedule()
	/usr/local/go/src/runtime/proc1.go:1647 +0x267
runtime.park_m(0xc820001680)
	/usr/local/go/src/runtime/proc1.go:1706 +0x18b
runtime.mcall(0x7fff5fbff6b0)
	/usr/local/go/src/runtime/asm_amd64.s:204 +0x5b

goroutine 1 [IO wait]:
net.runtime_pollWait(0xbf05b0, 0x72, 0xc82000e1f0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202f3d40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202f3d40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202f3ce0, 0xc820374400, 0x400, 0x400, 0x0, 0xbe6050, 0xc82000e1f0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820356010, 0xc820374400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820350150, 0xc260c8, 0xc820356010, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc820366000, 0x76fa17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc820366000, 0xc820359000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0xc2a630, 0xc820366000, 0xc82032e268, 0xc820359000, 0x1000, 0x1000, 0x4c1d40, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82041a9c0, 0xc820359000, 0x1000, 0x1000, 0x7300000035, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820411b60)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820411b60, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x21a
net/http/internal.readLine(0xc820411b60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/internal/chunked.go:110 +0x4b
net/http/internal.(*chunkedReader).beginChunk(0xc820454060)
	/usr/local/go/src/net/http/internal/chunked.go:47 +0x39
net/http/internal.(*chunkedReader).Read(0xc820454060, 0xc820480002, 0x5fe, 0x5fe, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/internal/chunked.go:77 +0xb7
net/http.(*body).readLocked(0xc82043a100, 0xc820480002, 0x5fe, 0x5fe, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:632 +0x98
net/http.(*body).Read(0xc82043a100, 0xc820480002, 0x5fe, 0x5fe, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:624 +0x110
net/http.(*bodyEOFSignal).Read(0xc82043a140, 0xc820480002, 0x5fe, 0x5fe, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1296 +0x26a
encoding/json.(*Decoder).refill(0xc820472000, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc820472000, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc820472000, 0x57a160, 0xc820452240, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:57 +0x159
github.com/docker/docker/pkg/jsonmessage.DisplayJSONMessagesStream(0xc66190, 0xc82043a140, 0xbea330, 0xc820030010, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go:161 +0x19e
github.com/docker/docker/api/client.(*DockerCli).CmdBuild(0xc820204c00, 0xc82000a250, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/build.go:253 +0x2c5d
reflect.callMethod(0xc8203020f0, 0xc820145c28)
	/usr/local/go/src/reflect/value.go:628 +0x1fc
reflect.methodValueCall(0xc82000a250, 0x3, 0x3, 0x1, 0xc8203020f0, 0x0, 0x0, 0xc8203020f0, 0x0, 0x667d4, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc820261860, 0xc82000a240, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:89 +0x383
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:63 +0x43c

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 18 [select]:
net/http.(*persistConn).readLoop(0xc82032e210)
	/usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 19 [select]:
net/http.(*persistConn).writeLoop(0xc82032e210)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

rax    0xe
rbx    0x107
rcx    0x7fff5fbff4b8
rdx    0x7fff5fbff530
rdi    0x107
rsi    0x958820
rbp    0x958fe0
rsp    0x7fff5fbff4b8
r8     0x958fe0
r9     0x4
r10    0x67ac08bc
r11    0x286
r12    0x124ae648bc0
r13    0xe602d8a0408
r14    0x142d2a6843067400
r15    0x8
rip    0x60b9b
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
```

`docker info`:
```
Containers: 15
 Running: 4
 Paused: 0
 Stopped: 11
Images: 197
Server Version: 1.10.0-rc1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.2.0-25-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.63 GiB
Name: ivan-machine-packet
ID: MUL2:IBSJ:UTMR:O4IL:QXIK:2NFO:5DUW:A76Z:QR3S:NPCR:3YKB:7ZKS
Username: imikushin
Registry: https://index.docker.io/v1/
Labels:
 provider=packet
```

**Comment by imikushin** [comment] 2016-01-27 03:32
`docker version`:
```
Client:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:17:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:50:07 2016
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment] 2016-01-27 03:41
Haven't been able to reproduce so far; for me it just builds, but I'll try some more.

I'll add this to the milestone so that we don't loose sight

**Comment by coolljt0725** [comment] 2016-01-27 03:47
I can't reproduce both on `master` and `1.10.0-rc1`

**Comment by coolljt0725** [comment] 2016-01-27 03:48
@imikushin  Can you show the daemon log?

**Comment by ibuildthecloud** [comment] 2016-01-27 04:05
@imikushin I can't reproduce this either.

**Comment by HackToday** [comment] 2016-01-27 04:53
Not sure if system related issue, I found it run on Ubuntu 15.10
Could you show your upstart docker logs which enablev -D debug level logs ?

**Comment by thaJeztah** [comment] 2016-01-27 16:57
@imikushin I'll remove this from the milestone for now, happy to add it back if we have a way to reproduce

**Comment by thaJeztah** [comment] 2016-01-27 17:05
Alright, @mavenugo just informed me that he reproduced this on OS X; awaiting more info

**Comment by tiborvass** [comment] 2016-01-27 17:15
@imikushin can you show `docker info` please

**Comment by mavenugo** [comment] 2016-01-27 17:29
@thaJeztah its a red herring. am not able to reproduce this issue.

**Comment by imikushin** [comment] 2016-01-27 18:01
@tiborvass my `docker info` is here, just below the docker client stacktrace. Looks like this bug occurs when using overlay (instead of aufs) on Ubuntu 15.10: I was stupid enough to try.

**Comment by tiborvass** [comment] 2016-01-27 18:03
@imikushin so assuming you're able to consistently reproduce it, does it happen with other graphdrivers?

**Comment by imikushin** [comment] 2016-01-27 18:04
@tiborvass only tried w/ overlay and aufs

**Comment by tiborvass** [comment] 2016-01-27 18:05
@imikushin so you dont see it with aufs, only overlay?

**Comment by imikushin** [comment] 2016-01-27 18:06
@tiborvass yeah, aufs is fine.

**Comment by imikushin** [comment] 2016-01-27 18:07
I'm going to try it on RancherOS as well (it uses overlay by default)

**Comment by imikushin** [comment] 2016-01-27 18:12
@tiborvass Any other drivers that I can try relatively easily on Ubuntu 15.10?

**Comment by runcom** [comment] 2016-01-27 18:14
Can't reproduce this on `overlay`:
```
Status: Downloaded newer image for docker.io/alpine:latest
 ---> 14f89d0e6257
Step 2 : VOLUME /usr/local/bin
 ---> Running in 1498d769100c
 ---> 0d9a4dbaf0a7
Removing intermediate container 1498d769100c
Successfully built 0d9a4dbaf0a7
```

**Comment by tiborvass** [comment] 2016-01-27 18:15
@runcom make sure you're testing rc1 like the OP

**Comment by tiborvass** [comment] 2016-01-27 18:15
@imikushin you could try devicemapper too.

**Comment by runcom** [comment] 2016-01-27 18:18
RC1 works fine for me on overlay:
```
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM alpine
 ---> 14f89d0e6257
Step 2 : VOLUME /usr/local/bin
 ---> Running in a4df1af14980
 ---> 82da915172c3
Removing intermediate container a4df1af14980
Successfully built 82da915172c3
```

**Comment by imikushin** [comment] 2016-01-27 18:54
I hate to say it, but on a fresh Ubuntu 15.10 (on DigitalOcean), RC1 works fine with overlay. I guess it's something in my environment then.

**Comment by tiborvass** [comment] 2016-01-27 18:56
@imikushin thanks for that information. I'll remove this from milestone. We're still interested to understand what the issue is. Is the fresh 15.10 using the same kernel version as your environment?

**Comment by ehazlett** [comment] 2016-09-26 15:48
I'm going to close this. @imikushin if you continue to notice issues or get a reproduce case please re-open or open a new one.  Thanks!

**Closed by ehazlett** 2016-09-26 15:48 UTC
Labels: area/storage/overlay, status/more-info-needed
