### ISSUE TITLE
rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1" by a lot of zombie process

### ISSUE THREAD

**Issue by rainforc** [docker/docker#22650] opened 2016-05-11 07:35 UTC
Output of docker version:

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

Output of docker ps

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
3b6c36fe48f4        ubuntu_hadoop       "/bin/bash -c 'while "   4 hours ago         Up 4 hours                              vm833
6813e701e732        ubuntu_hadoop       "/bin/bash -c 'while "   4 hours ago         Up 4 hours                              vm817
cd0d56e1b1b0        ubuntu_hadoop       "/bin/bash -c 'while "   4 hours ago         Up 4 hours                              vm803
1b0bff15f582        ubuntu_hadoop       "/bin/bash -c 'while "   21 hours ago        Up 20 hours                             vm783
0dc7ce0a0540        ubuntu_hadoop       "/bin/bash -c 'while "   21 hours ago        Up 20 hours                             vm767
9a10db4bc112        ubuntu_hadoop       "/bin/bash -c 'while "   5 days ago          Up 27 hours                             vm692
fb443ca313bb        ubuntu_hadoop       "/bin/bash -c 'while "   5 days ago          Up 27 hours                             vm674
183c29ae212c        ubuntu_hadoop       "/bin/bash -c 'while "   3 weeks ago         Up 27 hours                             vm656
0b8e23457d87        ubuntu_hadoop       "/bin/bash -c 'while "   3 weeks ago         Up 27 hours                             vm640
```

Output of  top
```
top - 15:35:08 up 1 day,  4:07,  5 users,  load average: 577.11, 577.25, 576.02
Tasks: 1998 total,   2 running, 1420 sleeping,   0 stopped, 576 zombie
Cpu(s):  0.1%us, 62.2%sy,  0.0%ni, 37.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  131375560k total, 11136312k used, 120239248k free,   739488k buffers
Swap:  7813116k total,        0k used,  7813116k free,  1959828k cached
```
Output of  `ps -ef  | grep defunct | wc -l`
```
577
```

All of defunct(zombie) process generated by java webapp in the tomcat of the container vm656.

Steps to reproduce the issue:

1. Run  `docker exec -it vm656  /bin/bash`

2、Run `docker kill vm656` is blocked all the way, there is no any output.

Describe the results you received:

```
rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1
```

**Comment by thaJeztah** [comment] 2016-05-11 10:54
Can you provide;

- the output of `docker -D info`
- some information about the image you're running; can you share the Dockerfile and/or the repository that is used to build it? Or can you provide a minimum test-case for us to reproduce?

Without this, it'll be difficult to reproduce your situation to look into this

**Comment by rainforc** [comment] 2016-05-12 10:14
the output of  docker -D info 
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-77-generic
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.3 GiB
Name: yi2
ID: 4OQP:GQ2T:3ZU4:EDFD:A4BC:JWPO:WSEH:6M7F:SZFZ:626S:AJBG:VZSB
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

 the output of ps -ef | grep docker
root     10507     1  0 10:28 ?        00:00:00 auplink /var/lib/docker/aufs/mnt/586aba1e4ea03ff51d8aba1a93bad07918a2f77603d831b882d8c7dba75a3c57 flush
root     13861     1  0 10:30 ?        00:00:00 [docker] <defunct>
root     21141     1  0 10:36 ?        00:00:00 [docker] <defunct>
root     21147 21141  0 10:36 ?        00:00:00 [docker-containe] <defunct>
root     29901 29036  0 11:42 pts/0    00:00:00 grep --color=auto docker

the output of nohup ./docker daemon -b=br0 &
time="2016-05-12T11:42:45.584422116+08:00" level=info msg="previous instance of containerd still alive (21147)"

I can not start docker and can not kill the process of 21147.

Sorry, The image is about 1G size, upload it too slow...

I guess the reason is 

According to the Unix process model, the init process -- PID 1 -- inherits all orphaned child processes and must reap them. Most Docker containers do not have an init process that does this correctly, and as a result their containers become filled with zombie processes over time.

Furthermore, docker stop sends SIGTERM to the init process, which is then supposed to stop all services. Unfortunately most init systems don't do this correctly within Docker since they're built for hardware shutdowns instead. This causes processes to be hard killed with SIGKILL, which doesn't give them a chance to correctly deinitialize things. This can cause file corruption.

**Comment by thaJeztah** [comment] 2016-05-12 11:57
> I guess the reason is (...)

No, I think this is a duplicate of https://github.com/docker/docker/issues/18180, and the reason here is most likely a bug in aufs in kernel 3.13. 

You need to upgrade your kernel to 3.13.0-79.123 or later to get the fix for that aufs bug (see https://github.com/docker/docker/issues/18180#issuecomment-187583209).

Can you try upgrading your kernel to an up-to-date version, and see if you're still having this issue?

**Comment by rainforc** [comment] 2016-05-19 03:29
After upgrade my kernel to 3.13.1-031301, i fixed that aufs bug. Thank you very much!

**Comment by thaJeztah** [comment] 2016-05-19 11:37
Cool, I'll close this issue then! 👍

**Closed by thaJeztah** 2016-05-19 11:37 UTC
Labels: status/more-info-needed, version/1.11

**Comment by loveai88** [comment] 2016-07-24 15:51
I have a same problem but I use device-mapper,it is also the kernel problem ?
```
Linux solrtest75 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-1975369-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 536.6 MB
 Data Space Total: 107.4 GB
 Data Space Available: 51.45 GB
 Metadata Space Used: 1.774 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 251.6 GiB
Name: solrtest75
ID: SQD6:BLZ2:WLR4:H36X:5B4I:VTFR:2T7L:53TW:H5BU:QBPA:ULGR:JW5E
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by thaJeztah** [comment] 2016-07-24 16:54
@loveai88 nope, not the same issue

**Comment by raghu999** [comment] 2017-03-08 16:23
+1

**Comment by thaJeztah** [comment] 2017-03-08 16:40
@raghu999 leaving a random `+1` on a closed issue is not helpful. If you are having this issue, or think you have the same issue, and suspect it's a bug, please open a new issue with details.

I'm locking the conversation on this issue; open a new issue with details
