### ISSUE TITLE
Container name resolution not working

### ISSUE THREAD

**Issue by rajitha-wijayaratne** [docker/docker#11847] opened 2015-03-27 00:16 UTC
I am using Docker 1.5 on CoreOS alpha (626.0.0).  I have created 2 containers. 

```
CONTAINER ID        IMAGE               COMMAND					PORTS		NAMES
db13a5290f39        ubuntu:latest       "/bin/sh -c '/opt/h		9000/tcp    hive1                                            
345cad5bf140        mysql:v1            "mysqld"							db  
```

When I try to enter the container named ***db*** for example using the command.
```
docker exec -ti db /bin/bash
```
It wrongly opens the first i.e. ***hive1*** container.   Clearly the container name lookup table is corrupt.  How do I fix this please?

Thanks

**Comment by Piste** [comment] 2015-03-27 00:33
+kind/question

**Comment by hqhq** [comment] 2015-03-27 02:05
Hi, I can't reproduce this with 1.5.0-release and latest 1.5.0-dev, can you show how to reproduce it?

**Comment by dqminh** [comment] 2015-03-27 03:07
This should be fixed in latest / 1.6. You can find the merged patch here https://github.com/docker/docker/pull/9705

**Comment by rajitha-wijayaratne** [comment] 2015-03-31 05:18
I have been trying to figure out how to build from a non-master branch. In this case its 1.6. However I  cannot find information anywhere.  The dry-run-test only produces 1.5 version from the main branch.

In addition, the docker is installed in /var/lib/docker.   How can I choose an alternate location to build and install the files.  i.e.  something like

./configure --prefix=/user/local/docker

I am now testing on ubuntu btw.

Thank you

**Comment by thaJeztah** [comment] 2015-04-07 21:02
@rajitha-wijayaratne the easiest way to get master builds (without building yourself) is downloading them from http://master.dockerproject.com. Also, the release-candidates for docker-1.6 can be found here; https://github.com/docker/docker/pull/11635#issuecomment-90205104

If you *do* want to build yourself, instructions can be found here https://docs.docker.com/project/set-up-dev-env/. Those instructions will build a binary that you can install where you like by copying/moving the binary.

You're right that these instructions (currently) produce a `1.5-dev` build; at this moment uses this (slightly confusing) numbering, where `x.x-dev` is actually *more recent* than `x.x`. This will change after the upcoming `1.6` release.

I'm closing this issue, because I am unable to reproduce this on 1.6-rc5. Feel free to comment after that or ping me if you are able to reproduce this on docker 1.6

**Closed by thaJeztah** 2015-04-07 21:02 UTC
Labels: kind/question

**Comment by efunneko** [comment] 2015-05-08 20:35
I suspect the problem is that your hash value for the first image starts with 'db' and presumably docker is checking the hash for a prefix match before the name. It really should first look for exact matches of the name before looking at the image hash. You should give the image a longer name than 'db' (or use characters that aren't hexidecimal) and you will be good to go.

**Comment by thaJeztah** [comment] 2015-05-08 22:13
@efunneko I think this particular issue is also fixed on master, so no workaround is needed anymore for that.
