### ISSUE TITLE
Network is not registering swam services

### ISSUE THREAD

**Issue by adawolfs** [docker/docker#31520] opened 2017-03-03 14:39 UTC
**Description**

I'm creating a swam services but when I attach them to a network it's not displaying the attached services

**Steps to reproduce the issue:**
Command to create network
**sudo docker network create  --driver overlay --subnet 10.0.9.0/24  --attachable myNetwork** 
Command to create service
**sudo docker service create --replicas 1 --name percona --env-file percona.env --network myNetwork percona** 

**sudo docker network inspect myNetwork**
```
[
    {
        "Name": "myNetwork",
        "Id": "rfmxdr4nuufren6uyag3gc7ir",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.9.0/24",
                    "Gateway": "10.0.9.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Containers": null,    **<===== Not in list**
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": null
    }
]

```
But when I execute the inspect command over the service
**sudo docker service inspect --format='{{json .Endpoint.VirtualIPs}}' percona**

`[{"NetworkID":"rfmxdr4nuufren6uyag3gc7ir","Addr":"10.0.9.4/24"}]`

I'm following this documentation 
[Attach services to an overlay network](https://docs.docker.com/engine/swarm/networking/)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by thaJeztah** [comment] 2017-03-03 15:12
Thanks for reporting; looks like this is a duplicate of https://github.com/docker/docker/issues/24186.

Currently `docker network inspect` only shows _local_ task connected to the network, and not tasks in the whole network. The linked issue contains some more information

**Closed by thaJeztah** 2017-03-03 15:12 UTC
Labels: area/networking, area/swarm, version/1.13
