### ISSUE TITLE
[1.12.0-rc2 Swarm] Single node Swarm Cluster, nginx service not responding to localhost

### ISSUE THREAD

**Issue by BenHall** [docker/docker#23812] opened 2016-06-21 11:37 UTC
I expected that creating a service and exposing the ports would have the same results as `docker run -p 80:80`. However it looks like it doesn't expose the ports on the host. I imagine this could be something to do with the new load balancer approach, but it's hard to understand what's happening and which IP to call as a result.

```
> docker service create --name badnginx --replicas 1 -p 80:80 nginx:alpine
> docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
05771889ebc5        nginx:alpine        "nginx -g 'daemon off"   2 minutes ago       Up 2 minutes        80/tcp, 443/tcp     badnginx.1.6pmctqv0n2uydkezlunmyiyag
> curl localhost
<no response>
> curl 127.0.0.1
HTTP/1.1 200 OK
> docker service rm badnginx
badnginx
>  docker run -p 80:80 -d nginx:alpine
f14e7d4b87e63b36205b1c0165deab7bd876c19dd3cf326d816ba866ab3b5248
> curl localhost
HTTP/1.1 200 OK
```

I can see a lot of users getting confused by trying to access localhost and it not responding.

**Comment by jhorwit2** [comment] 2016-06-21 21:47
Did you happen to already have something on port 80?

I noticed I can run 
```
docker service create --replicas 3 --name nginx --publish 8081:80 nginx:latest
```

and it works fine but if i run another service that binds to port 8081 like 
```
docker service create --replicas 3 --name nginx2 --publish 8081:80 nginx:latest
```
it fails silently and stays 0.
```
ID            NAME    REPLICAS  IMAGE         COMMAND
5n1bppxuvboq  nginx2  0/3       nginx:latest
b7k4b2p1opfz  nginx   3/3       nginx:latest
```

**Comment by jhorwit2** [comment] 2016-06-21 21:52
That or you probably need to run sudo and it will work which again shouldn't fail silently.

**Comment by BenHall** [comment] 2016-06-21 22:09
Via 127.0.0.1 Docker overrides existing containers running on port 80.

Via localhost the mapped container processes the request. Something fun
happening as both processes can be mapped to same port.

**Comment by tiborvass** [comment] 2016-06-27 15:53
@BenHall can you provide more information `docker info` and can you verify with netstat or lsof that you really have nothing running on port 80 ?

**Comment by cpuguy83** [comment] 2016-07-14 02:12
ipvs does not route to localhost, we'd have to setup an iptables rule to handle this.
@mavenugo What do you think?

**Comment by jhorwit2** [comment] 2016-07-14 04:19
@cpuguy83 is swarm using ipvs nat?

**Comment by mavenugo** [comment] 2016-07-14 04:33
@BenHall @cpuguy83 well... i tried with docker master & ubuntu 14.04 (3.13 kernel) & it works fine :

```
 $ sudo docker service create --name badnginx --replicas 1 -p 80:80 nginx:alpine
7dz58lscpynhqxxk066pwjhtn

 $ sudo docker service ls
ID            NAME      REPLICAS  IMAGE         COMMAND
7dz58lscpynh  badnginx  1/1       nginx:alpine

 $ curl localhost
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

Is this a kernel 3.16+ thing ? I can check on an upgraded kernel and confirm.

**Comment by sanimej** [comment] 2016-07-14 08:57
@mavenugo `curl localhost` works just fine with 3.19 (ubuntu 14.04) as well. I doubt there is anything kernel specific here.

@BenHall Are you able to recreate this with rc4 ?

**Comment by tiborvass** [comment] 2016-07-15 22:40
I'm tempted to say this is a duplicate of #24134

**Comment by sanimej** [comment] 2016-07-26 17:46
@BenHall One possibility is that when you do `curl localhost`, curl resolves localhost to V6 IP but the port is bound only to the v4 address. In some hosts I see localhost has both v4 and v6 mapping in the /etc/hosts file. Can you try `curl -4 localhost` ?

**Comment by sanimej** [comment] 2016-08-05 17:42
@BenHall Closing this issue since its very likely to be because of `curl localhost` defaulting to ipv6. Give it a try with `curl -4` and if you still see the issue we can reopen.

**Closed by sanimej** 2016-08-05 17:42 UTC
Labels: group/networking, priority/P2, version/1.12

**Comment by danidee10** [comment] 2017-05-10 15:21
@BenHall That was indeed the problem for me!. I've been on this for over 4 hours (checked through every possible place i could think of) 

Thanks a lot 😄
