### ISSUE TITLE
Docker restart doesn't pick updated env-file

### ISSUE THREAD

**Issue by tarunlalwani** [docker/docker#25160] opened 2016-07-28 05:48 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 19
 Running: 7
 Paused: 0
 Stopped: 12
Images: 217
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:2-1948846187-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 26.41 GB
 Data Space Total: 107.4 GB
 Data Space Available: 80.96 GB
 Metadata Space Used: 33.82 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.114 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/payu/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /home/payu/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.43 GiB
Name: localhost.localdomain
ID: KBJJ:34JM:EFHG:P2OO:I773:FBO7:W34N:B7AP:QGXX:JXQU:QSBP:VYTT
Docker Root Dir: /home/payu/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Steps to reproduce the issue:**

1. Create env.sh file

     ```
      ENV1=V1
     ```
2. execute `docker run -d --name os --env-file=$PWD/env.sh centos:6.7 top -b`
3. execute `docker exec os env`

    ```
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    HOSTNAME=b2d3d4eefaf5
    ENV1=V1
    HOME=/root
    ```
4. Update the `env.sh` file as below

    ```
    ENV1=V2
    ```
5. Restart the docker container using `docker restart os`
6. execute `docker exec os env`

**Describe the results you received:**

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=b2d3d4eefaf5
ENV1=V1
HOME=/root
```

**Describe the results you expected:**
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=b2d3d4eefaf5
ENV1=V2
HOME=/root
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-07-28 08:20
That's expected; `docker restart` does not create a new container; the `env-file` is only a convenience alternative to set multiple `-e` / `--env` flags, not a file that is added to the container.

I'll close this issue, because this is not a bug, but feel free to continue the discussion

**Closed by thaJeztah** 2016-07-28 08:20 UTC
Labels: version/1.11
