### ISSUE TITLE
Unable to remove container

### ISSUE THREAD

**Issue by tonicbupt** [docker/docker#7481] opened 2014-08-08 09:15 UTC
see also #2714 .

I'm using CentOS 7 and kernel is 3.10.0

    $ uname -r
    3.10.0-123.6.3.el7.x86_64

docker information is

    $ docker version
    Client version: 1.1.2
    Client API version: 1.13
    Go version (client): go1.2.1
    Git commit (client): d84a070
    Server version: 1.1.2
    Server API version: 1.13
    Go version (server): go1.2.1
    Git commit (server): d84a070

the problem mention in #2174 did occur again. 
here's the message:

> Aug  8 17:09:49 kili0 docker: 2014/08/08 17:09:49 GET /v1.13/containers/json
> Aug  8 17:09:49 kili0 docker: [1fa20b28] +job containers()
> Aug  8 17:09:49 kili0 docker: [1fa20b28] -job containers() = OK (0)
> Aug  8 17:09:51 kili0 docker: 2014/08/08 17:09:51 GET /v1.13/containers/json?all=1
> Aug  8 17:09:51 kili0 docker: [1fa20b28] +job containers()
> Aug  8 17:09:51 kili0 docker: [1fa20b28] -job containers() = OK (0)
> Aug  8 17:10:01 kili0 systemd: Starting Session 11 of user root.
> Aug  8 17:10:01 kili0 systemd: Started Session 11 of user root.
> Aug  8 17:10:10 kili0 docker: 2014/08/08 17:10:10 POST /v1.13/containers/create
> Aug  8 17:10:10 kili0 docker: [1fa20b28] +job create()
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 0 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 1 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 2 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 3 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 4 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 5 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 6 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 7 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 8 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 9 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 10 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 11 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 12 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: device-mapper: thin: Creation of new snapshot 13 of device 23 failed.
> Aug  8 17:10:10 kili0 kernel: bio: create slab <bio-2> at 2
> Aug  8 17:10:10 kili0 kernel: EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: discard
> Aug  8 17:10:10 kili0 systemd-udevd: conflicting device node '/dev/mapper/docker-8:2-134226242-0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb-init' found, link to '/dev/dm-1' will not be created
> Aug  8 17:10:10 kili0 systemd-udevd: conflicting device node '/dev/mapper/docker-8:2-134226242-0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb-init' found, link to '/dev/dm-1' will not be created
> Aug  8 17:10:10 kili0 docker: [1fa20b28] -job create() = OK (0)
> Aug  8 17:10:10 kili0 docker: 2014/08/08 17:10:10 POST /v1.13/containers/0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb/start
> Aug  8 17:10:10 kili0 docker: [1fa20b28] +job start(0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb)
> Aug  8 17:10:10 kili0 kernel: bio: create slab <bio-2> at 2
> Aug  8 17:10:10 kili0 docker: [1fa20b28] +job allocate_interface(0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb)
> Aug  8 17:10:10 kili0 docker: [1fa20b28] -job allocate_interface(0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb) = OK (0)
> Aug  8 17:10:10 kili0 kernel: EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: discard
> Aug  8 17:10:10 kili0 systemd-udevd: conflicting device node '/dev/mapper/docker-8:2-134226242-0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb' found, link to '/dev/dm-1' will not be created
> Aug  8 17:10:10 kili0 systemd: Starting docker container 0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb.
> Aug  8 17:10:10 kili0 systemd: Started docker container 0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb.
> Aug  8 17:10:10 kili0 kernel: netlink: 1 bytes leftover after parsing attributes.
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth2fad): carrier is OFF
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth2fad): new Veth device (driver: 'unknown' ifindex: 15)
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth2fad): exported as /org/freedesktop/NetworkManager/Devices/14
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth2fad): device state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth2fad): link connected
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth2fad): preparing device
> Aug  8 17:10:10 kili0 systemd-sysctl: Overwriting earlier assignment of kernel/sysrq in file '/etc/sysctl.d/99-sysctl.conf'.
> Aug  8 17:10:10 kili0 systemd-sysctl: Overwriting earlier assignment of kernel/shmmax in file '/etc/sysctl.d/99-sysctl.conf'.
> Aug  8 17:10:10 kili0 systemd-sysctl: Overwriting earlier assignment of kernel/shmall in file '/etc/sysctl.d/99-sysctl.conf'.
> Aug  8 17:10:10 kili0 systemd-sysctl: Overwriting earlier assignment of kernel/sysrq in file '/etc/sysctl.d/99-sysctl.conf'.
> Aug  8 17:10:10 kili0 systemd-sysctl: Overwriting earlier assignment of kernel/shmmax in file '/etc/sysctl.d/99-sysctl.conf'.
> Aug  8 17:10:10 kili0 systemd-sysctl: Overwriting earlier assignment of kernel/shmall in file '/etc/sysctl.d/99-sysctl.conf'.
> Aug  8 17:10:10 kili0 kernel: device veth0670 entered promiscuous mode
> Aug  8 17:10:10 kili0 NetworkManager[1226]: ifcfg-rh:     read connection 'Wired connection 1'
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth2fad): created default wired connection 'Wired connection 1'
> Aug  8 17:10:10 kili0 kernel: IPv6: ADDRCONF(NETDEV_UP): veth0670: link is not ready
> Aug  8 17:10:10 kili0 avahi-daemon[1219]: Withdrawing workstation service for veth2fad.
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): link connected
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): carrier is ON
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): new Veth device (driver: 'unknown' ifindex: 16)
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): exported as /org/freedesktop/NetworkManager/Devices/15
> Aug  8 17:10:10 kili0 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth0670: link becomes ready
> Aug  8 17:10:10 kili0 kernel: docker0: port 1(veth0670) entered forwarding state
> Aug  8 17:10:10 kili0 kernel: docker0: port 1(veth0670) entered forwarding state
> Aug  8 17:10:10 kili0 NetworkManager[1226]: ifcfg-rh:     read connection 'veth0670'
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): device state change: unmanaged -> unavailable (reason 'connection-assumed') [10 20 41]
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (docker0): link connected
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): device state change: unavailable -> disconnected (reason 'connection-assumed') [20 30 41]
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) starting connection 'veth0670'
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) Stage 1 of 5 (Device Prepare) scheduled...
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth2fad): device state change: unavailable -> unmanaged (reason 'removed') [20 10 36]
> Aug  8 17:10:10 kili0 NetworkManager[1226]: init_link: assertion `rtnl_link_get_name (rtnllink)' failed
> Aug  8 17:10:10 kili0 NetworkManager[1226]: file platform/nm-linux-platform.c: line 1026 (to_string_link): should not be reached
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <error> [1407489010.579443] [platform/nm-linux-platform.c:1841] link_change(): Netlink error changing link (invalid link 0x7ff04798e090): No such device
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) Stage 1 of 5 (Device Prepare) started...
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): device state change: disconnected -> prepare (reason 'none') [30 40 0]
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) Stage 2 of 5 (Device Configure) scheduled...
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) Stage 1 of 5 (Device Prepare) complete.
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) Stage 2 of 5 (Device Configure) starting...
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): device state change: prepare -> config (reason 'none') [40 50 0]
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) Stage 2 of 5 (Device Configure) successful.
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) Stage 3 of 5 (IP Configure Start) scheduled.
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) Stage 2 of 5 (Device Configure) complete.
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) Stage 3 of 5 (IP Configure Start) started...
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): device state change: config -> ip-config (reason 'none') [50 70 0]
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (docker0): attached bridge port veth0670
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) connection 'veth0670' enslaved, continuing activation
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) Stage 3 of 5 (IP Configure Start) complete.
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): device state change: ip-config -> secondaries (reason 'none') [70 90 0]
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): device state change: secondaries -> activated (reason 'none') [90 100 0]
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> Activation (veth0670) successful, device activated.
> Aug  8 17:10:10 kili0 dbus[1244]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
> Aug  8 17:10:10 kili0 dbus-daemon: dbus[1244]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
> Aug  8 17:10:10 kili0 systemd: Starting Network Manager Script Dispatcher Service...
> Aug  8 17:10:10 kili0 dbus-daemon: dbus[1244]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
> Aug  8 17:10:10 kili0 dbus[1244]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
> Aug  8 17:10:10 kili0 systemd: Started Network Manager Script Dispatcher Service.
> Aug  8 17:10:10 kili0 docker: [1fa20b28] -job start(0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb) = OK (0)
> Aug  8 17:10:10 kili0 docker: [1fa20b28] +job release_interface(0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb)
> Aug  8 17:10:10 kili0 docker: [1fa20b28] -job release_interface(0d47d59a250ea2d8bbf6d8d368b5498e8964e3108f8c05b0900a1b00a4360cdb) = OK (0)
> Aug  8 17:10:10 kili0 avahi-daemon[1219]: Withdrawing workstation service for veth0670.
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): device state change: activated -> unmanaged (reason 'removed') [100 10 36]
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (veth0670): deactivating device (reason 'removed') [36]
> Aug  8 17:10:10 kili0 NetworkManager[1226]: init_link: assertion `rtnl_link_get_name (rtnllink)' failed
> Aug  8 17:10:10 kili0 NetworkManager[1226]: file platform/nm-linux-platform.c: line 1026 (to_string_link): should not be reached
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <error> [1407489010.641837] [platform/nm-linux-platform.c:1841] link_change(): Netlink error changing link (invalid link 0x7ff047989c50): No such device
> Aug  8 17:10:10 kili0 NetworkManager[1226]: init_link: assertion `rtnl_link_get_name (rtnllink)' failed
> Aug  8 17:10:10 kili0 NetworkManager[1226]: file platform/nm-linux-platform.c: line 1026 (to_string_link): should not be reached
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <error> [1407489010.642472] [platform/nm-linux-platform.c:1841] link_change(): Netlink error changing link (invalid link 0x7ff047989c50): No such device
> Aug  8 17:10:10 kili0 NetworkManager[1226]: <info> (docker0): detached bridge port veth0670 (success 0)
> Aug  8 17:10:10 kili0 NetworkManager[1226]: (devices/nm-device.c:985):nm_device_release_one_slave: runtime check failed: (success)
> Aug  8 17:10:10 kili0 kernel: docker0: port 1(veth0670) entered disabled state
> Aug  8 17:10:10 kili0 kernel: device veth0670 left promiscuous mode
> Aug  8 17:10:10 kili0 kernel: docker0: port 1(veth0670) entered disabled state
> Aug  8 17:10:11 kili0 NetworkManager[1226]: <info> (docker0): link disconnected (deferring action for 4 seconds)
> Aug  8 17:10:15 kili0 NetworkManager[1226]: <info> (docker0): link disconnected (calling deferred action)

**Comment by vbatts** [comment] 2015-01-07 17:37
is this a sporadic failure or immediate and consistent? I'm attempting to reproduce and have not yet. 
```
[root@rhel7 ~]# docker info
Containers: 4
Images: 6
Storage Driver: devicemapper
 Pool Name: docker-8:17-262145-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1.312 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 1.528 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.84-RHEL7 (2014-03-26)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.13.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Workstation 7.0 (Maipo)
[root@rhel7 ~]# docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.1
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.1
Git commit (server): 39fa2fa/1.3.2
```

**Comment by vbatts** [comment] 2015-01-07 19:22
okay, so two notable fixes were included in docker 1.3 to address udevwait and devicemapper
https://github.com/docker/docker/commit/edc6df256d21eb1d1aa36b241dcc6d4b83d58d75 and https://github.com/docker/docker/commit/cef27e1d6c0bd302e1c58e9478a0fba99fd3a2d0

right now, RHEL-extras is docker-1.3.2-4.el7.

I'm thinking this issue is a race with udev, and may have been fixed now. Can you retest with latest rpms?

**Comment by jeremyeder** [comment] 2015-01-14 17:08
@vbatts Still an issue in the latest builds.

**Comment by wjiangjay** [comment] 2015-01-15 09:32
Got this issue on fedora 20 too.
$ sudo docker info 
Containers: 1
Images: 50
Storage Driver: devicemapper
 Pool Name: docker-8:3-1975909-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1.611 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 2.72 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.85 (2014-04-10)
Execution Driver: native-0.2
Kernel Version: 3.17.7-200.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)



$dmesg
......
[ 2264.969539] device-mapper: thin: Creation of new snapshot 38 of device 22 failed.
[ 2264.969567] device-mapper: thin: Creation of new snapshot 39 of device 22 failed.
[ 2264.969600] device-mapper: thin: Creation of new snapshot 40 of device 22 failed.
[ 2264.969633] device-mapper: thin: Creation of new snapshot 41 of device 22 failed.
[ 2264.969660] device-mapper: thin: Creation of new snapshot 42 of device 22 failed.
[ 2264.969704] device-mapper: thin: Creation of new snapshot 43 of device 22 failed.
[ 2264.969743] device-mapper: thin: Creation of new snapshot 44 of device 22 failed.
[ 2264.969784] device-mapper: thin: Creation of new snapshot 45 of device 22 failed.
[ 2264.969815] device-mapper: thin: Creation of new snapshot 46 of device 22 failed.
[ 2264.969869] device-mapper: thin: Creation of new snapshot 47 of device 22 failed.
[ 2264.969903] device-mapper: thin: Creation of new snapshot 48 of device 22 failed.
[ 2264.969938] device-mapper: thin: Creation of new snapshot 49 of device 22 failed.
[ 2264.969979] device-mapper: thin: Creation of new snapshot 50 of device 22 failed.
[ 2264.970019] device-mapper: thin: Creation of new snapshot 51 of device 22 failed.
[ 2264.970055] device-mapper: thin: Creation of new snapshot 52 of device 22 failed.
[ 2342.198628] device-mapper: thin: Creation of new snapshot 55 of device 22 failed.
[ 2342.198688] device-mapper: thin: Creation of new snapshot 56 of device 22 failed.
[ 2436.929999] device-mapper: ioctl: unable to remove open device docker-8:3-1975909-pool

**Comment by rhvgoyal** [comment] 2015-06-08 19:52
thin_check should be run only on metadata device and not data device. So "bad checksum in superblock" is not a problem.

Other errors about "device-mapper: thin: Creation of new snapshot 56 of device 22 failed" used to happen in the past because we were not properly keeping track of device ids which have already been
used in the pool.

Some of the issues methioned in the beginning of the thread are related to udev sync.

So can reporter please take the latest docker, do a dynamic binary build and see if problem is still reproducible or not. If not, lets close this.

And BTW, please use lvm thin pool on real block devices. loop devices can be problematic.

**Comment by rhvgoyal** [comment] 2015-06-12 13:29
Is this issue reproducible with latest docker? If yes, please give me exact steps. Otherwise let us close this issue and open whenever the problem happens on latest docker or we have more details. Keeping it open does not help.

**Comment by grossws** [comment] 2015-06-15 10:43
In my case it was rare issue, without stable way to reproduce it. I haven't dm-based installation on CentOS7 anymore (because of other docker-related issue, which seemed related to dm).

**Comment by unclejack** [comment] 2015-06-15 10:55
As per @rhvgoyal's comment, I'm going to close this now.

**Closed by unclejack** 2015-06-15 10:55 UTC
Labels: /system/devicemapper, exp/expert, kind/bug

**Comment by JonasT** [comment] 2016-09-08 12:31
This is also happening on Fedora 24, kernel 4.6.7, BTRFS formatted SSD, docker 1.12.0-rc4.

**Comment by daikaixian** [comment] 2016-09-18 07:57
+1
centos 7
docker 1.10

**Comment by tonylit** [comment] 2016-09-28 01:10
+1 
centos7

Containers: 18
 Running: 18
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0-rc4
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 94.18 GiB
Name: localhost.localdomain
ID: QQVQ:PM77:NFOO:RLXX:EW2V:M4PD:PL5Z:VIYC:OSKP:RYBG:L5BD:JKKX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false

**Comment by laithrafid** [comment] 2016-10-04 13:39
+1

**Comment by smirnp** [comment] 2017-04-24 16:08
+1 
CentOS 3.10.0-327.3.1.el7.x86_64
Docker version 1.12.3, build 6b644ec

**Comment by rhvgoyal** [comment] 2017-04-24 17:02
Your thin pool is full. Don't let it get full.
