### ISSUE TITLE
Segfaulting (I think?) on Linux 4.7

### ISSUE THREAD

**Issue by frioux** [docker/docker#23378] opened 2016-06-08 16:42 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 152
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.7.0-040700rc2-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.37 GiB
Name: zfp
ID: WWAV:EBRG:XQKU:LLZ7:JUMU:MDR4:BPJ4:C7T3:XKVQ:WFUT:3DAP:6ZHU
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical, kernel says Linux zfp 4.7.0-040700rc2-generic #201606051831 SMP Sun Jun 5 22:33:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1. Install Linux 4.7
    * `wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.7-rc2-yakkety/linux-headers-4.7.0-040700rc2-generic_4.7.0-040700rc2.201606051831_amd64.deb http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.7-rc2-yakkety/linux-headers-4.7.0-040700rc2_4.7.0-040700rc2.201606051831_all.deb http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.7-rc2-yakkety/linux-image-4.7.0-040700rc2-generic_4.7.0-040700rc2.201606051831_amd64.deb`
    * `sudo dpkg -i linux-headers-4.7.0-040700rc2_4.7.0-040700rc2.201606051831_all.deb linux-headers-4.7.0-040700rc2-generic_4.7.0-040700rc2.201606051831_amd64.deb linux-image-4.7.0-040700rc2-generic_4.7.0-040700rc2.201606051831_amd64.deb`
2. reboot into new kernel
3. `docker run --rm --name w.pl -v ~/tmp:/tmp -u "$(id -u)" frew/w.pl`
4. Cry

**Describe the results you received:**

The client exited 139 (no core file that I can find anywhere)

**Describe the results you expected:**

I expected the container to run and write files to ~/tmp

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens with every single container.  I just used the simplest one I know of to show the issue.

**Comment by justincormack** [comment] 2016-06-08 17:11
Can you run https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh to see if there is anything odd about kernel setup. Is there anything in system logs? Can you try `docker run --privileged ...` and see if it makes a difference. And can you just do something simpler like `docker run busybox ls` so no volume mounts or anything. Just to narrow down where the issue might be...

**Comment by frioux** [comment] 2016-06-08 17:46
Output of check-config.sh:

```
info: reading kernel config from /boot/config-4.7.0-040700rc2-generic ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: missing
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: missing
    (note that cgroup swap accounting is not enabled in your kernel config, you can enable it by setting boot option "swapaccount=1")
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000
```

I think dmesg may have made it clear what the problem is though!

Check this out:

```
$ docker run --rm alpine ls
zfp 💀 [15873] ~ <139> 
$ dmesg | tail -n 20
[ 7561.806609] docker0: port 1(veth0dbe2c0) entered disabled state
[ 7561.808315] device veth0dbe2c0 left promiscuous mode
[ 7561.808317] docker0: port 1(veth0dbe2c0) entered disabled state
[ 7600.641203] docker0: port 1(veth0d8a32e) entered blocking state
[ 7600.641205] docker0: port 1(veth0d8a32e) entered disabled state
[ 7600.641248] device veth0d8a32e entered promiscuous mode
[ 7600.641316] IPv6: ADDRCONF(NETDEV_UP): veth0d8a32e: link is not ready
[ 7600.641318] docker0: port 1(veth0d8a32e) entered blocking state
[ 7600.641320] docker0: port 1(veth0d8a32e) entered forwarding state
[ 7600.641662] docker0: port 1(veth0d8a32e) entered disabled state
[ 7600.720975] eth0: renamed from vetha91207e
[ 7600.737169] IPv6: ADDRCONF(NETDEV_CHANGE): veth0d8a32e: link becomes ready
[ 7600.737207] docker0: port 1(veth0d8a32e) entered blocking state
[ 7600.737209] docker0: port 1(veth0d8a32e) entered forwarding state
[ 7600.764682] ls[89456]: segfault at 0 ip 00007fa82da33f8e sp 00007ffd16ea1648 error 4 in ld-musl-x86_64.so.1[7fa82da14000+88000]
[ 7600.817584] vetha91207e: renamed from eth0
[ 7600.840887] docker0: port 1(veth0d8a32e) entered disabled state
[ 7600.874615] docker0: port 1(veth0d8a32e) entered disabled state
[ 7600.876814] device veth0d8a32e left promiscuous mode
[ 7600.876818] docker0: port 1(veth0d8a32e) entered disabled state
```

and

```
$ docker run busybox ls
bin
dev
etc
home
proc
root
sys
tmp
usr
var
```

So it looks like musl is broken on 4.7?  Should I reach out to the musl people?

**Comment by justincormack** [comment] 2016-06-08 17:51
Ping @ncopa

**Comment by richfelker** [comment] 2016-06-08 19:08
This is almost surely a kernel bug, but it's hard to diagnose further without having an environment to test on, and I'm not really familiar with what the procedures would be for debugging stuff inside Docker. Any idea if the binaries crash the same on the main host (outside Docker)? Do they crash if invoked via the dynamic linker as a command?

**Comment by frioux** [comment] 2016-06-08 19:24
They do crash when I use a simple chroot. I'll try directly running ash
outside of a chroot after lunch.

-- 
sent from a rotary phone, pardon my brevity

**Comment by frioux** [comment] 2016-06-08 20:18
Chatting with #musl about this.  People who know more than I do believe it's a kernel bug.  I'll let someone else close the issue but I can repro outside of docker so I think we can all agree this is not a docker issue (though dockerinc might be worried that musl based images will be broken for 4.7-rc2.)

**Comment by thaJeztah** [comment] 2016-06-08 20:31
We recently got some help from @sforshee, who (I think) is on the kernel team for Canonical; @sforshee is this a known issue? (Also let me know if it's not appreciated to ping you for these kind of issues :heart:)

**Comment by richfelker** [comment] 2016-06-08 20:43
From further discussion on #musl, it's almost surely vdso-related. The crash seems to be in code processing the traditional (sysv) ELF symbol hash table, probably for the vdso provided by the kernel. It's likely that the kernel is providing an invalid vdso, probably with invalid/corrupt sysv hashtable. But I don't see any related changes in the kernel git log for v4.7-rc2 vs v4.6, so perhaps a new version of binutils used to build the kernel image you're using introduced the problem.

**Comment by justincormack** [comment] 2016-06-09 10:30
Thanks @richfelker sounds like it is an Ubuntu toolchain issue or a kernel issue, but @frioux could you file a bug against them as a broken vdso is going to be a big performance issue as well as a problem running Musl code... Will close this issue but please keep posting here as interested in the resolution.

**Closed by justincormack** 2016-06-09 10:30 UTC
Labels: area/kernel, version/1.11

**Comment by sforshee** [comment] 2016-06-09 13:54
@thaJeztah Yes, I do work on Canonical's kernel team, and if there are problems with our kernels affecting Docker I'm happy to help.

In this case we're talking about our mainline builds, which are unpatched upstream kernel builds provided  _for testing purposes only_. I'll still try to help, but these kernels will never receive the same amount of testing or support as the official Ubuntu kernels.

I was able to reproduce this with the specified kernel build but not in another 4.7-rc2 based build that I had built myself on a xenial machine. Seems likely that it is a problem with the toolchain in yakkety then, I'll do some tests to confirm this.

**Comment by frioux** [comment] 2016-06-09 15:56
I have reported the issue to kernel devs directly, in the hopes that builds like this will not be able to complete in the future (https://www.spinics.net/lists/kernel/msg2274264.html) and as @sforshee knows about it (and presumably the people in my [original issue](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1576764)) I think everyone who needs to know, knows.

**Comment by thaJeztah** [comment] 2016-06-09 16:36
Thanks @sforshee, much appreciated!

**Comment by amluto** [comment] 2016-06-09 17:41
Hi @sforshee: could you patch your kernel with:

https://git.kernel.org/cgit/linux/kernel/git/luto/linux.git/commit/?h=x86/vdso&id=6436d4c1a83cbe083e54c53bb2b16efaab9b62f4

and see what happens?  I.e. does it build?  If it doesn't build, could you poke around a bit and see what intermediates in arch/x86/entry/vdso look bad, if any?  The full command line and version of the tools that link vdso64.so.dbg might be helpful, too.

**Comment by sforshee** [comment] 2016-06-09 18:27
@amluto, sure.

Also, here's what I know about this so far. We had an update to gcc which enabled PIE by default and caused our kernel builds to fail. This patch was added to fix the build:

http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.7-rc2-yakkety/0002-disable-pie-when-gcc-has-it-enabled-by-default.patch

It's this patch that causes the problems - the same kernel built with the same toolchain is fine without the patch but with the patch causes the segfault.

**Comment by amluto** [comment] 2016-06-09 18:39
Hmm, indeed:

vdso64.so: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=496e9db3f494533ffaaf39737eb1023938861349, not stripped

It built the vdso as an executable, not a shared library.  Wtf?

Did you see any problems outside the vdso?

**Comment by amluto** [comment] 2016-06-09 18:46
I can't reproduce this with my gcc even with -pie explicitly set:

`gcc -pie -nostdlib -o arch/x86/entry/vdso/vdso64.so.dbg -fPIC -shared  -Wl,--hash-style=both  -Wl,--build-id -Wl,-Bsymbolic  -m64 -Wl,-soname=linux-vdso.so.1 -Wl,--no-undefined -Wl,-z,max-page-size=4096 -Wl,-z,common-page-size=4096  -Wl,-T,arch/x86/entry/vdso/vdso.lds arch/x86/entry/vdso/vdso-note.o arch/x86/entry/vdso/vclock_gettime.o arch/x86/entry/vdso/vgetcpu.o`

Is your command line somehow different?  Is Ubuntu's gcc patch extra special buggy?

**Comment by sforshee** [comment] 2016-06-09 18:56
We haven't (yet) seen any problems apart from the vsdo as far as I know.

The `-no-pie` patch isn't to address vsdo problems specifically, the build will fail well before that.

**Comment by richfelker** [comment] 2016-06-09 19:12
I believe in the gcc options framework -pie and -shared are mutually exclusive and the last one overrides the other, so perhaps somehow -no-pie also overrides -shared and yields a default as if neither was specified. This probably depends on how your GCC is patched. Is it using the --enable-default-pie stuff that went upstream in 6.0, or the Gentoo ESP stuff?

**Comment by sforshee** [comment] 2016-06-09 20:20
@richfelker, that does seem to be the issue. After getting more background on the patch, we were aware of that problem and the intention was that -no-pie was intended to always be placed placed at the start of the flags so a -shared anywhere else would override it. However in the vdso makefile a mistake was made and -no-pie appears after -shared.

Thanks for the help everyone. I'll make sure this gets fixed.

**Comment by frioux** [comment] 2016-06-09 22:02
@sforshee could you comment here when you guys have a fixed build?

**Comment by sforshee** [comment] 2016-06-10 12:28
@frioux all the mainline builds are now fixed. None of our released kernels ever contained this bug.

**Comment by kung-foo** [comment] 2016-07-12 10:19
FWIW, I saw the same thing on a 4.6.3-xanmod5. Rolling back to 4.4.9-xanmod14 fixed it (didn't try any kernels in between).

**Comment by amluto** [comment] 2016-07-12 14:59
@kung-foo, can you provide details about the environment in which you
triggered it?  Useful things include:

* /proc/cpuinfo (as seen by crashing process on bad kernel)
* /sys/devices/system/clocksource/clocksource0/current_clocksource
* what hypervisor was in use, if any
* glibc version in use by crashing process
* the output from dump-vdso (
http://git.kernel.org/cgit/linux/kernel/git/luto/misc-tests.git/) run
inside the bad environment.

So far, I don't have a clear enough understanding of what the reporters are
doing when they trigger this to even know where to look.

**Comment by kung-foo** [comment] 2016-07-25 12:17
@amluto sorry for the late response.

* various output: https://gist.github.com/kung-foo/d0bca92b07b8ed39efa4c2d13fc95a1d
* no hypervisor
* [vdso.bin.gz](https://github.com/docker/docker/files/381421/vdso.bin.gz)
* not sure _which_ process is crashing
* kernel 4.6.3-xanmod5 from https://xanmod.org/
* verified _not_ working by running `docker run --rm -it alpine ls` (no output)

**Comment by kung-foo** [comment] 2016-07-26 08:51
updated to 4.7.0 (xanmod), seems to be working.

```
$ file vdso*
vdso-4.6.3.bin: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0ca2d2d9051c7d1e6a2e155340d98bdf050759ca, stripped
vdso-4.7.0.bin: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=5203b8735bc67df5ff9d4dadbdc7f48a9302f2b9, stripped
```

`docker run --rm -it alpine ls` works!

**Comment by thaJeztah** [comment] 2016-07-26 09:21
Thanks @kung-foo, good to hear
