### ISSUE TITLE
How to force RUN use `/bin/bash`

### ISSUE THREAD

**Issue by eromoe** [docker/docker#30964] opened 2017-02-13 05:58 UTC
On ubuntu:14.04 docker
I meet some error as below:
```
Step 14 : RUN python /tmp/get-pip.py
 ---> Running in f1c248dd501b
/bin/sh: 1: python: not found
The command '/bin/sh -c python /tmp/get-pip.py' returned a non-zero code: 127


Step 15 : RUN pip install -U pip setuptools
 ---> Running in 9ed6ca11ea5d
/bin/sh: 1: pip: not found
The command '/bin/sh -c pip install -U pip setuptools' returned a non-zero code: 127


Step 15 : RUN mv /usr/bin/python /usr/bin/python.old && ln -sf /usr/bin/python3.5 /usr/bin/python
 ---> Running in 4139e20b3f91
mv: cannot stat ‘/usr/bin/python’: No such file or directory
The command '/bin/sh -c mv /usr/bin/python /usr/bin/python.old && ln -sf /usr/bin/python3.5 /usr/bin/python' returned a non-zero code: 1
```

I think maybe it because 
> RUN <command> (shell form, the command is run in a shell, which by default is /bin/sh -c on Linux or cmd /S /C on Windows)

and ubuntu 's default `/bin/sh` is `dash` .

--------------

`RUN` works with build-in command
```
RUN bash /tmp/update_source.sh
RUN mkdir -p /root/.jupyter/
```

But I have to change 

```
RUN python /tmp/get-pip.py
RUN pip install -U pip setuptools
```

to 

```
CMD python /tmp/get-pip.py
CMD pip install -U pip setuptools
```

I'd like just use `RUN`, what should I do?

**Comment by thaJeztah** [comment] 2017-02-13 07:01
You can use;

    RUN ["/bin/bash", "-c", "python", "..... etc"]

However, `python: not found` may actually mean it's not installed; without knowing what other steps are in your Dockerfile there's no way to tell.

However, please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-02-13 07:01 UTC

**Comment by eromoe** [comment] 2017-02-13 08:06
Sorry, I foget to include below

1. `RUN ["/bin/bash", "-c", "python /tmp/get-pip.py"]`

2. `RUN /bin/bash -c python /tmp/get-pip.py` 

both not work.

Only `CMD` works, so I think it maybe some bug.

Docker detail:
```
[root@localhost python3]# docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment] 2017-02-13 08:10
```
CMD python /tmp/get-pip.py
```

Is executed when you _start_ the container, whereas `RUN` is a step during building the container, so those cannot be compared.
