### ISSUE TITLE
Docker exec commands leak memory in docker daemon

### ISSUE THREAD

**Issue by briangough** [docker/docker#12899] opened 2015-04-30 12:28 UTC
## Please read the following comment: https://github.com/docker/docker/issues/12899#issuecomment-97816048

This looks like an issue with data structures which aren't being freed.

____________________________________________________

### original issue report

We have long running containers which we access with docker exec commands periodically (e.g. every minute) to run scripts.  When the scripts produce output we see the docker daemon growing in size until it consumes all available memory.  

The problem is reproducible with a simple script that starts a container and calls docker exec repeatedly with a command that generates output .  With 10000 exec calls each producing 100KB of output on stdout we see the docker daemon memory usage grow by ~2.5GB.

![memusage](https://cloud.githubusercontent.com/assets/7457354/7412041/857a7024-ef36-11e4-8500-4371dd201e36.png)

Here's the script that produced the data above

```
sudo restart docker
pid=$(pgrep -f '/usr/bin/docker')  # pid of docker daemon
container=$(docker run -d ubuntu sleep 1d)

rm -f size.log

function log_memory {
    ps --no-headers -o size -p $pid >> size.log
}    

log_memory
for i in $(seq 1 10000) ; do
    docker exec $container dd if=/dev/zero bs=100k count=1
    log_memory
done

docker kill $container
log_memory
```

The memory growth increases with the amount of stdout from the command, so may be related to https://github.com/docker/docker/issues/7757#issuecomment-97716769

If the command has no output then the leak is negligible in comparison, only 20MB for 10000 exec calls.

I've tried with and without log-driver=none and the results were the same.  Removing the container after the test above has finished does not reduce the memory usage of the daemon either.

We use the docker-1.6 Ubuntu packages from docker.com

Test system details:

$ uname -a
Linux Lenovo-H530s 3.13.0-51-generic #84-Ubuntu SMP Wed Apr 15 12:08:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

$ docker -D info
Containers: 467
Images: 405
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1339
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-51-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.715 GiB
Name: Lenovo-H530s
ID: 7TYM:DIRX:YWLF:SPT5:S2AK:F7WS:3MU2:G2TT:W2PE:CBMA:JRPA:JK4L
Debug mode (server): false
Debug mode (client): true
Fds: 11
Goroutines: 15
System Time: Thu Apr 30 12:58:22 BST 2015
EventsListeners: 0
Init SHA1: 9145575052383dbf64cede3bac278606472e027c
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support

**Comment by cpuguy83** [comment] 2015-04-30 13:35
Wow great detail!
Thanks for all the effort! Don't listen to the silly turtle.

**Comment by cpuguy83** [comment] 2015-04-30 13:37
ccing @unclejack who's done a bunch of work around memory growth.

**Comment by jpallen** [comment] 2015-04-30 14:22
It look this is improved on the master branch (possibly by 5550a46946a2e6e1be8844d78a78122b333fae26). I'm still seeing a ~87MB increase after ~1200 requests (same test script as @briangough), which is a lot less than on 1.6.0.

It looks like the execConfig object have a lifetime as long as the container, which may be the source of this leak? If we have a long running container with lots of exec calls into it, then any memory used by these exec calls will not be released until the container is cleared (c.f. https://github.com/docker/docker/blob/d2f0b9ed976987576483387bc919cb7ffbfa38e8/daemon/container.go#L722 and https://github.com/docker/docker/blob/62a85fe2026f3f5114f19638baf53d19a51d39c0/daemon/exec.go#L212). Would it be possible to do a partial clean up of the execConfig data, but still leave the necessary info like exitCode, etc?

**Comment by LK4D4** [comment] 2015-04-30 17:15
Hmm, yeah. Don't know, I think we need remove them from cli at least. It is really awful.

**Comment by unclejack** [comment] 2015-05-04 13:52
The logging related memory allocation problem has been fixed on master. Docker 1.7.0 won't have these problems any more. There are still some allocations being done for the output, but for 99% of the use cases it shouldn't be a problem of any kind any more and it shouldn't have any kind of impact.

Those weren't leaks per se, they were just a lot of memory allocations the Go GC had to deal with. Obviously, this was less than ideal and it has been fixed.

I'm going to edit the original post and the title to make sure that the investigation is only about not holding onto data structures which are no longer needed.

**Comment by prepor** [comment] 2015-06-15 13:58
With --log-driver=syslog and Docker from master (Docker version 1.7.0-dev, build a63c7c7) there are leaks in daemon with many execs. Docker 1.6.2 and master are unusable if you use exec feature now (we use it for health checks)

**Comment by prepor** [comment] 2015-06-15 14:11
My size.txt (generated by bash-script from issue's body) with 1000 iterations https://www.refheap.com/e51d377c9637b453ba7d2eded

**Comment by icecrime** [comment] 2016-09-10 02:01
Please let us know if this is reproducible with a recent Docker version. I'll close this in the meantime, but feel free to ping me if it needs reopening!

**Closed by icecrime** 2016-09-10 02:01 UTC
Labels: kind/bug, version/1.6
