### ISSUE TITLE
docker stats function requires cat in docker images

### ISSUE THREAD

**Issue by sols1** [docker/docker#22882] opened 2016-05-21 15:19 UTC
In docker 1.11.1

https://github.com/docker/libnetwork/blob/master/osl/interface_linux.go#L185

err := nsInvoke(path, func(nsFD int) error { return nil }, func(callerFD int) error {
    // For some reason ioutil.ReadFile(netStatsFile) reads the file in
    // the default netns when this code is invoked from docker.
    // Executing "cat <netStatsFile>" works as expected.
    data, err := exec.Command("cat", netStatsFile).Output()

This obviously does not work for containers that have no cat

**Comment by thaJeztah** [comment] 2016-05-21 15:32
Can you give an example where this is failing? Using the [traefik](https://hub.docker.com/_/traefik/) image from Docker Hub, which contains only a static binary, nothing else (see the [Dockerfile](https://github.com/containous/traefik-library-image/blob/0b0c26da8cb7abc1190d95acbfc5c5e1f986f685/Dockerfile));

```
docker run -d --name foobar traefik

docker stats foobar
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
foobar              0.01%               3.871 MB / 2.099 GB   0.18%               648 B / 648 B       0 B / 0 B           6
```

**Comment by sols1** [comment] 2016-05-21 18:16
I get this message when running https://github.com/bobrik/collectd-docker under kubernetes:

> time="2016-05-20T21:23:26.713369575Z" level=error msg="collecting stats for 92665ae0d1c58b76c837ec66693777451202e648efdd33751f3cd07238db2732: failed to retrieve the statistics for eth0 in netns /var/run/docker/netns/a1f3e62fe31b: failure opening /proc/net/dev: exec: \"cat\": executable file not found in $PATH" 

The container is https://github.com/hopsoft/docker-graphite-statsd

GetContainerStats() (https://github.com/docker/docker/blob/master/daemon/daemon.go#L1519) is called which calls network stats function and eventually hits this issue.

It's not clear yet if the issue is in the environment or namespace or something else.

In any case the code above is a hack and it won't work in general either because cat is not present in the image or the environment is not set up.

**Comment by thaJeztah** [comment] 2016-05-22 02:01
I actually think `cat` is called on the *host* but executed inside the container's namespace. Is `cat` present on the host you're running docker on?

If you don't run on kubernetes, but directly using docker (see my earlier example), does it work? I know that kubernetes is not yet compatible with docker 1.11, also kubernetes may be interfering with the docker networking.

/cc @aboch any suggestions?

**Comment by sols1** [comment] 2016-05-23 06:43
If cat is called on the host, then it would either work for all containers running on the host or for none.

Unfortunately, it works for some containers but not for others. So, your theory is wrong.

And it doesn't work if I start container directly, not through kubernetes.

I have to use 1.11.1 with the patch #https://github.com/docker/docker/pull/21904 because of another stats bug #https://github.com/docker/docker/issues/21848

**Comment by AkihiroSuda** [comment] 2016-05-23 07:03
@sols1 
```
> The container is https://github.com/hopsoft/docker-graphite-statsd
```

The container seems to contain `cat`...
```
$ docker run -it --rm hopsoft/graphite-statsd ls -l /bin/cat
-rwxr-xr-x 1 root root 47904 Mar 10 19:10 /bin/cat
```

**Comment by sols1** [comment] 2016-05-23 07:09
@AkihiroSuda 

Yes, but it still does not work.

Even if /bin/cat is present, PATH might not be set.

**Comment by thaJeztah** [comment] 2016-05-23 08:27
I'm not able to reproduce this either. Not sure if I started these containers correctly, but tried this;

```
docker network create test
docker run -d --name graphite --restart=always --net test -p 8080:80 hopsoft/graphite-statsd
docker run -d -v /var/run/docker.sock:/var/run/docker.sock -e GRAPHITE_HOST=graphite -e COLLECTD_HOST=graphite --net test --name  collectd  bobrik/collectd-docker


docker stats graphite collectd

CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O             PIDS
graphite            0.02%               70.82 MB / 2.098 GB   3.38%               1.944 kB / 648 B    0 B / 159.7 kB        34
collectd            0.24%               8.069 MB / 2.098 GB   0.38%               648 B / 648 B       1.507 MB / 65.54 kB   19
```

@sols1 can you also provide the output of `docker version`, `docker info`, and options that are used to start the daemon?

**Comment by sols1** [comment] 2016-05-23 17:39
`docker version      
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   70fc693
 Built:        Tue May 17 21:34:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   70fc693
 Built:        Tue May 17 21:34:04 2016
 OS/Arch:      linux/amd64
`

`docker info      
Containers: 40
 Running: 17
 Paused: 0
 Stopped: 23
Images: 64
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: tmpfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.8-ckt3-rancher
Operating System: <unknown> (containerized)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 251.9 GiB
Name: re75-t5-17c
ID: R4ZH:CRQ4:KJZ4:B3EH:W6DA:FM3A:4Y6L:QZ63:OIQY:46MK:FC2P:ZVOY
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
`

Options:
`/usr/bin/docker daemon --log-opt max-size=25m --log-opt max-file=2 -s overlay -b docker-sys --fixed-cidr 172.18.42.1/16 --restart=false -g /var/lib/docker
 -G root -H unix:///var/run/docker.sock --userland-proxy=false`

**Comment by thaJeztah** [comment] 2016-05-23 18:02
From the kernel version, I suspect you're running on RancherOS; is the docker version you're running also a rancher version? It looks like we don't have that commit in our repository https://github.com/docker/docker/commit/70fc693

ping @ibuildthecloud is this perhaps a known issue? I'm having trouble reproducing it

**Comment by sols1** [comment] 2016-05-23 18:24
There is no special version of docker for RancherOS. RancherOS build just downloads docker binary from the docker web-site.

There is 70fc693 commit in docker repository. It is the same commit as in #https://github.com/docker/docker/pull/21904. Are you familiar with how to use git and github?

> git log -2
> commit 70fc6936efb63548ac057a204d8f615237bb2ebe
> Author: Yong Tang <yong.tang.github@outlook.com>
> Date:   Sat Apr 9 06:57:04 2016 +0000
> 
>     Docker stats is not working when a container is using another container's network.
>     
>     This fix tries to fix the issue in #21848 where `docker stats` will not correctly
>     display the container stats in case the container reuse another container's
>     network stack.
>     
>     The issue is that when `stats` is performed, the daemon will check for container
>     network setting's `SandboxID`. Unfortunately, for containers that reuse another
>     container's network stack (`NetworkMode.IsConnected()`), SandboxID is not assigned.
>     Therefore, the daemon thinks the id is invalid and remote API will never return.
>     
>     This fix tries to resolve the SandboxID by iterating through connected containers
>     and identify the appropriate SandboxID.
>     
>     A test case for `stats` remote API has been added to check if `stats` will return
>     within the timeout.
>     
>     This fix fixes #21848.
>     
>     Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
> 
> commit 5604cbed50d51c4039b1abcb1cf87c4e01bce924
> Merge: 7ef1cfd 4146b8b
> Author: Tibor Vass <tiborvass@users.noreply.github.com>
> Date:   Mon Apr 25 23:35:31 2016 -0400
> 
>     Merge pull request #22267 from mlaventure/1.11.1-changelog
>     
>     Add changelog for v1.11.1

**Comment by thaJeztah** [comment] 2016-05-23 18:52
that's weird, not sure why it didn't show up on GitHub

**Comment by nvachhar** [comment] 2016-05-27 21:41
I think `cat` was missing on the host. Things worked for containers where `--net=host` was used. If I'm tracing the code correctly, in that case a default OS network sandbox gets used and it has no interfaces added to it, so the code that exec's cat never gets invoked.

**Comment by justincormack** [comment] 2016-05-27 21:58
Ok, looks like that explains the case of the missing `cat` then and why it worked with `--net=host`, so I will close this issue.

**Closed by justincormack** 2016-05-27 21:58 UTC
Labels: status/more-info-needed

**Comment by sols1** [comment] 2016-05-27 22:41
Note that to fix this issue in RancherOS cat must be copied into initrd which is a "host" namespace in RancherOS. It's a strange requirement for initrd, IMHO.

**Comment by thaJeztah** [comment] 2016-05-27 22:47
Work is in progress to change this https://github.com/docker/libnetwork/pull/1174

**Comment by sols1** [comment] 2016-07-15 21:19
When #https://github.com/docker/libnetwork/pull/1174 will be in docker?

**Comment by thaJeztah** [comment] 2016-07-15 21:31
@sols1 looks like it was vendored in https://github.com/docker/docker/commit/44793049ce1ad364720b4be915a92291d1f808c2, which will be in 1.12

**Comment by sols1** [comment] 2016-07-15 21:37
When is 1.12 supposed to happen?

**Comment by thaJeztah** [comment] 2016-07-15 21:41
if all goes well, in roughly two weeks, but release candidates are available for testing; https://github.com/docker/docker/releases
