### ISSUE TITLE
Multicast between 2 container in 2 host

### ISSUE THREAD

**Issue by rivallu** [docker/docker#10978] opened 2015-02-24 10:48 UTC
Hi,
I have 2 ElasticSearch containers (based on Ubuntu 14.04) and I use the multicast protocol to discover all ES' nodes. It's work when i ran all container on the same host but no multicast packets are foward between the docker network to my local network. I saw some issue about the multicast and docker and I just want to know if it's normal, if it's a bug or if I miss some configuration ?
my docker version is 1.5.0 (build a8a31ef).

**Comment by jfrazelle** [comment] 2015-02-28 00:09
duplicate of https://github.com/docker/docker/issues/3043, please check out the comments there

**Closed by jfrazelle** 2015-02-28 00:09 UTC
