### ISSUE TITLE
Exec for Swarm

### ISSUE THREAD

**Issue by arvenil** [docker/docker#31548] opened 2017-03-05 03:17 UTC
**Description**

When I run containers by hand I was able to run afterwards `docker exec` to run some special setup scripts. Currently this doesn't seem to be possible as if container is run at different node, I would need to ssh to that node and run command.

**Describe the results you expected:**

There should be an option to run `docker exec` on a service, and upon doing it the command would get propagated to all containers distributed on different nodes.

~~Another option that could solve the problem would be to allow prepend `Command` in docker-compose.yml. Currently you can only overwrite cmd which makes it really complicated.~~ (edit: after re-thinking such change in compose wouldn't solve much as you still wouldn't be able to run commands with local context. However this still could be useful in some cases where only guest env is needed)

**Comment by thaJeztah** [comment] 2017-03-05 17:35
Thanks for opening this feature request. It looks like this is a duplicate of https://github.com/docker/docker/issues/27552, so i'll close this one to prevent the discussion from diverging. Please subscribe to the linked issue, or add your use case there. Thanks!

**Closed by thaJeztah** 2017-03-05 17:35 UTC
Labels: area/swarm, kind/feature
