### ISSUE TITLE
rm -rf won't delete files in subdirectories in Docker 1.13

### ISSUE THREAD

**Issue by mburke2dev** [docker/docker#31717] opened 2017-03-10 01:24 UTC
I have an existing Dockerfile that has been building images successfully for some time.  The customer recently upgraded to Docker 1.13, and my builds are suddenly failing on the following line:

`RUN rm -rf ./clients/*`

The error that comes back is:

```Step 12/30 : RUN rm -rf ./clients/*
 ---> Running in d265f4bf6802
[91mrm: cannot remove `./clients/path/launcher/css': Directory not empty
The command '/bin/sh -c rm -rf ./clients/*' returned a non-zero code: 1
```

The remove command should be able to remove directories containing files when the parameters r and f are being passed.

I tried changing it to `rm -r -f` in case separating the parameters would succeed, but the result was the same.

**Steps to reproduce the issue:**
1. Create a dockerfile that expands a gzip file and operates on it, then removes the expanded file structure.
2. Verify that dockerfile builds successfully in Docker version 1.12.0, (specifically build 8eab29e)
3. Upgrade Docker to version 1.13.
4. Make an inocuous change so that a difference is detected.
5. Run docker build again on the dockerfile.

**Describe the results you received:**
Build fails on `RUN rm -rf` line.

**Describe the results you expected:**
Continued success and happiness.

**Additional information you deem important (e.g. issue happens only occasionally):**
Failure 5/5 attempts.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1-cs2
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   ad32da7
 Built:        Thu Feb 23 16:40:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1-cs2
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   ad32da7
 Built:        Thu Feb 23 16:40:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1-cs2
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.388 GiB
Name: ip-10-12-3-111.corp.gxicloud.com
ID: IYKN:QKFG:ST6B:AAG5:NZCZ:JX6J:WQ4X:ONOC:2NWC:D6GS:DNSB:Q4PZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Jenkins build run.  Client owned machine, could be AWS.

**Comment by AkihiroSuda** [comment] 2017-03-10 02:15
This is a dupe of https://github.com/docker/docker/issues/27358 , and expected behavior without d_type.

>  Supports d_type: false

You need to recreate XFS with d_type: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html

**Comment by AkihiroSuda** [comment] 2017-03-10 02:16
I'm closing this issue, but please feel free to reopen if needed.

**Closed by AkihiroSuda** 2017-03-10 02:16 UTC
Labels: area/builder, version/1.13
