### ISSUE TITLE
names are inconsistent in JSON responses/objects across API calls

### ISSUE THREAD

**Issue by posita** [docker/docker#13240] opened 2015-05-15 03:18 UTC
Here's what I've noticed so far with v1.6.0 (via boot2docker):

* `ParentId` (e.g., `/images/{image_id}/inspect`) vs. `Parent` (e.g., `/images/json`) vs. `parent` (e.g., in the `{image_id}/json` files present in the `x-tar` stream from `/images/{image_id}/get`)
* `/images/{image_id}/get` has lower case keys in the resulting `{image_id}/json` files for pretty much every top level element except `Size`
* `Comment` and `VirtualSize` are present in `/images/{image_id}/inspect`, but missing from the `{image_id}/json` files

There might be others. Those are just what I found at a quick glance.

Are there any plans to make these consistent across all interfaces?

**Comment by posita** [comment] 2015-05-15 03:35
I checked for duplicates before filing and updated my original comment with the version I'm using. More detail:

```sh
Boot2Docker version 1.6.0, build parallels-custom : 9fb6ff9 - Sun Apr 19 11:11:50 UTC 2015
Docker version 1.6.0, build 4749651
% docker info
Containers: 14
Images: 17
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.18.11-tinycore64
Operating System: Boot2Docker 1.6.0 (TCL 5.4); parallels-custom : 9fb6ff9 - Sun Apr 19 11:11:50 UTC 2015
CPUs: 2
Total Memory: 5.832 GiB
Name: boot2docker
ID: YRIA:7RD3:FRDL:QBO2:D52X:EK2Y:NZ3D:CSSH:226F:N6GM:KOIA:GOYO
Debug mode (server): true
Debug mode (client): false
Fds: 12
Goroutines: 16
System Time: Fri May 15 03:24:44 UTC 2015
EventsListeners: 0
Init SHA1: 9145575052383dbf64cede3bac278606472e027c
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
% docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): darwin/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
% uname -a
Linux boot2docker 3.18.11-tinycore64 #1 SMP Sun Apr 19 08:39:18 UTC 2015 x86_64 GNU/Linux
```

I would expect JSON object names to be consistent across API calls, but they're not. Case, spelling, and absence/presence is inconsistent. I don't have a comprehensive list, but my original comment lists what I've seen so far.

**Comment by ahmetalpbalkan** [comment] 2015-05-15 08:20
Sort of dupe: #7671, I bet @thaJeztah can find a few of other similar issues reported.

**Comment by posita** [comment] 2015-05-15 11:50
@ahmetalpbalkan, it's related at the very least. #7671 seems to track path inconsistencies. #8829 seems to track command line argument inconsistencies. I did not find a corresponding issue that tracked response inconsistencies, although maybe this deserves to be consolidated into one of those?

**Comment by runcom** [comment] 2015-05-15 11:53
@posita I think it's better to treat them separately

**Comment by posita** [comment] 2015-05-15 11:57
@runcom, I thought so too, which is why I filed this as a new issue rather than appending it as a comment to one or more of those. I didn't find a duplicate of this particular issue, but I may have missed something?

**Comment by runcom** [comment] 2015-05-15 12:02
to my very best knowledge this isn't a dupe of any other, but @thaJeztah may come up with something if it's not :)

**Comment by zoechi** [comment] 2015-05-15 13:18
I think #5893 contains this.

**Comment by thaJeztah** [comment] 2015-05-15 13:25
@runcom just read this issue, and I think there are other issues that mention the JSON keys, will search.

Oh, looks like @zoechi just found one (could be the one I had in mind)

**Comment by posita** [comment] 2015-05-15 13:30
@zoechi, it looks like #5893 captures most of it. What I don't see in a cursory examination of that issue (or its cited sub-issues) is:

* `ParentId` vs. `Parent` (only case convention is discussed, not different names representing the same information across contexts)
* an explicit call out for consistency to expand to the `.../json` files in the `x-tar` archives from the various `.../get` methods (which seems to be the most overlooked in these discussions)
* inconsistent presence/absence of certain names (e.g., `Comment`, `VirtualSize`) in some contexts (again, I've only observed this in the `x-tar` archives)

**Comment by runcom** [comment] 2015-05-15 13:31
@thaJeztah thanks for having a look! @zoechi thanks for the finding (and blame on me for not searching better :)) I think we can close this since #5893

To sum up, @posita could you comment on #5893 to add your proposal here?

**Comment by posita** [comment] 2015-05-15 13:35
@runcom, done.

**Closed** 2015-05-15 13:35 UTC

**Comment by thaJeztah** [comment] 2015-05-15 13:38
Thanks @posita !
