### ISSUE TITLE
Dockerfile: accessing to service name

### ISSUE THREAD

**Issue by Fabryprog** [docker/docker#31725] opened 2017-03-10 09:01 UTC
hello,
I am using docker swarm and I would like to have the ability to access to service name into dockerfile

Today using an enviroment variable but it is very dirty

example:

`docker service create  --name myCoolService -e SERVICE_NAME=myCoolService ......
`

thanks

**Comment by thaJeztah** [comment] 2017-03-10 09:48
Thanks for opening this feature request. Looks like this  a duplicate of https://github.com/docker/docker/issues/24110, and https://github.com/docker/docker/issues/8427.

There's currently a pull request being discussed that implements this; https://github.com/docker/docker/pull/26331

I'm closing this issue because we are already tracking this in the linked issues (and some other ones), but feel free to comment after I closed.

**Closed by thaJeztah** 2017-03-10 09:48 UTC
Labels: area/builder, area/swarm
