### ISSUE TITLE
Cannot access the docker container via OpenVPN

### ISSUE THREAD

**Issue by phlegx** [docker/docker#23298] opened 2016-06-06 07:57 UTC
I have a docker (version 1.11.1) `openvpn_client` container running that connects the host to my VPN network. This is working just fine. 
However, when I start my `munin` container and bind it to the VPN IP `172.18.5.9:8080` then I cannot access the container from my remote (local host). 
I tried via telnet to access 172.18.5.9 on port 8080 but no luck. I can however access to my hosts 'native' SSH server via VPN (172.18.5.9 port 22) just fine.

Here is my docker-compose file just to make my setup clear.

```
version: "2"
services:
    munin:
      build: munin
      ports:
        - "172.18.5.9:8080:8080"

    openvpn_client:
      build: ../openvpn_client
      environment:
        CLIENT_CONFIG: server01.example.com.conf
      network_mode: host
      devices:
        - /dev/net/tun:/dev/net/tun
      cap_add:
        - NET_ADMIN
```

Maybe someone can give me a hint! Thanks!

PS: 

Actually I now also tried to simply map the port `8080` to ``0.0.0.0` so that it listens on all interfaces, but also that is not working. I'm out of ideas actually... 

As already stated the VPN works as expected and the iptable routes are ok. I can access the port 8080 via public IP just fine. Via VPN it is not working.

---

**docker version**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**docker info**

```
Containers: 22
 Running: 8
 Paused: 0
 Stopped: 14
Images: 528
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 633
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.16.0-70-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.69 GiB
Name: machine.example.com
ID: QYQV:YBR4:WAQQ:ONCC:VRCU:3COL:ZT72:G4ZW:236F:BGDZ:5HT2:QFSL
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**iptables -t nat -L -nv**

See: https://gist.github.com/phlegx/de09ddd55091da486a021021823fc8e9

**Comment by thaJeztah** [comment] 2016-06-06 12:57
Please keep in mind that the GitHub issue tracker is for tracking bugs and feature requests, not a general support forum. Can you ask this question on either one of;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

I'll close this issue, because of the above, but feel free to comment here after I closed, thanks!

**Comment by phlegx** [comment] 2016-06-06 13:14
Thank you @thaJeztah! The thing is I think it is a bug. I don't see any reason why this shouldn't work the way I set it up. The VPN itself works just fine. It seems to be a problem with docker somehow. But this is of course just my assumption.

Thank you very much!

**Comment by thaJeztah** [comment] 2016-06-06 14:42
@phlegx can you provide the output of `docker version` and `docker info`, and add that to your original comment? Also any options you set on the daemon / related environment vars (such as `http_proxy`)

**Comment by phlegx** [comment] 2016-06-06 14:54
@thaJeztah I've updated the original comment. Please let me know if you need something in addition!

**Comment by thaJeztah** [comment] 2016-06-06 16:01
Thanks, let me reopen, perhaps someone of the network team can have a look at this. It's quite busy though at the moment, due to preparations for DockerCon and the upcoming release, so it may take slightly longer than usual

**Comment by phlegx** [comment] 2016-06-06 17:00
Thank you @thaJeztah! If someone might want to test/reproduce it via OpenVPN itself, I can only point to this image: https://github.com/kylemanna/docker-openvpn/ which makes setting up a VPN extremely easy and fast.

**Comment by Peaches491** [comment] 2016-09-16 04:32
@phlegx: Did you ever figure out the root cause for this? I'm running into a similar issue. I'm hosting an openvpn server in a docker container, and I can't access any of the other ports from the other docker containers.

**Comment by phlegx** [comment] 2016-09-16 07:04
@Peaches491 Hi! Unfortunately no. I wanted to wait for a new docker version  and then try it out again, but haven't had time yet. I hope I can come back to this soon.

**Comment by phlegx** [comment] 2016-10-06 09:53
I tried it now locally via KVM machines with docker ```1.12``` and it seems to work just fine now. Awesome! Probably this got resolve in this newest docker version. I think since Openvpn didn't change, this was indeed a docker issue then. 

I still have to deploy everything to production and see if it also working there.I'll let you know if no further issues appear there!

**Comment by thaJeztah** [comment] 2016-10-06 11:54
Thanks @phlegx

**Comment by phlegx** [comment] 2017-01-13 15:39
Only now I managed to test it on the new server. All is working fine with docker version ```Docker version 1.12.6, build 78d1802```. This can be closed @thaJeztah  Thank you very much!

**Comment by thaJeztah** [comment] 2017-01-14 00:50
thanks @phlegx, good to hear it's resolved!

**Closed by thaJeztah** 2017-01-14 00:50 UTC
Labels: area/networking, version/1.11
