### ISSUE TITLE
Docker Start Error

### ISSUE THREAD

**Issue by Kekko991** [docker/docker#21570] opened 2016-03-28 09:41 UTC
Hi, hi have a OpenVZ VPS server... i installed docker (Debian 7)
but when i try to start docker i receive this error... and if i type 

**sudo service docker status**

i receive:

root@dask1:~# sudo service docker status
[**FAIL**] Docker is not running ... failed!

The Output Error:

root@dask1:~# sudo service docker start
mount: wrong fs type, bad option, bad superblock on cgroup,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

mount: wrong fs type, bad option, bad superblock on cgroup,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

mount: wrong fs type, bad option, bad superblock on cgroup,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

mount: wrong fs type, bad option, bad superblock on cgroup,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

mount: wrong fs type, bad option, bad superblock on cgroup,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

mount: wrong fs type, bad option, bad superblock on cgroup,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

mount: wrong fs type, bad option, bad superblock on cgroup,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

mount: wrong fs type, bad option, bad superblock on cgroup,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

[ **ok** ] Starting Docker: docker.
root@dask1:~#

Thanks for support. please help me

**Comment by Kekko991** [comment] 2016-03-28 09:46
root@dask1:~# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:48:06 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?



root@dask1:~# docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?




Steps.

1. root@dask1:~# sudo service docker start
2. Receive a message of start + errors
3. root@dask1:~# sudo service docker status
4. Receive Fail Error

**Comment by HackToday** [comment] 2016-03-28 13:13
It said errors like

```
mount: wrong fs type, bad option, bad superblock on cgroup,
missing codepage or helper program, or other error
(for several filesystems (e.g. nfs, cifs) you might
need a /sbin/mount. helper program)
In some cases useful info is found in syslog - try
dmesg | tail or so
```

Have you followed above suggestions?

**Comment by Kekko991** [comment] 2016-03-29 13:57
i installed the software for mount... etc... i bought another vps from another provider (mydigital ocean) and seem work

**Comment by thaJeztah** [comment] 2016-03-30 00:59
Thanks @Kekko991 let me close this issue then, good to hear you got it working!

**Closed by thaJeztah** 2016-03-30 00:59 UTC
Labels: status/more-info-needed

**Comment by eeluve** [comment] 2016-04-20 12:04
nice solution. you do realise, you it in fact isn't solved at all? still not possible to run under openvz

**Comment by thaJeztah** [comment] 2016-04-20 13:00
@eeluve afaik, OpenVZ is still at kernel 2.6 (which is not supported for Docker), and only supports `vfs` as a graph-driver (which is *strongly* discouraged, and basically only useful for testing, but nothing other than that); https://openvz.org/Docker_inside_CT

I see there's some work going on to move to kernel 3.10 https://openvz.org/Download/kernel, but nothing stable yet.

In the current situation, running Docker under OpenVZ is *not* a supported setup

**Comment by eeluve** [comment] 2016-04-20 13:23
Ye, that's kind of what I said. So, as far as I understood, docker waits for parallels to move openvz to 3.10, which is logical ofc but may take forever.

**Comment by thaJeztah** [comment] 2016-04-20 13:25
Yes, don't think there's much we can do here, unless there's lots of demand from OpenVZ users to "push" Parallels

**Comment by eeluve** [comment] 2016-04-21 11:54
Hi, just because you answer quickly and I couldn't get any help in docker IRC and there's no docker channel in slack .. I will try to ask here. Deployed private registry v2 and issued self-signed certificate. Can login just fine from debian-based machines with 1.11 client, but from ones(atomic-host: rh-based) with 1.8 and 1.9 it also requests for "mail" during docker login procedure and then fails. Also can not, by any means, find directory where images gets stored in v2. Can't execute search against the repo as well. Official manual claims "GET /v2/" should be enough, but neither this neither other versions like /v2/_catalog or /v2/search or /v2/search?q=request are working for me. Curl -X returns unreadable rectangles to the console and docker search returns 404.

**Comment by thaJeztah** [comment] 2016-04-21 12:15
In registry "V1", search was part of the registry; in V2, a registry is (by design), only a *registry*, but does not have indexing / search capabilities (see the documentation here; https://docs.docker.com/registry/spec/api/). Docker Hub, and [Docker Trusted Registry](https://docs.docker.com/docker-trusted-registry/overview/) add this capability.

What versions of docker 1.8 and 1.9 do you have installed on your Atomic hosts? The version of docker as distributed by Red Hat / Atomic contains a lot of modifications that affect working with registries (and Docker Hub).  Have you tried installing the official packages from our repository? https://docs.docker.com/engine/installation/linux/centos/

**Comment by eeluve** [comment] 2016-04-21 13:24
Ok, thanks for your answer even tho my post was against the rules. May I invite you to #atomic channel @freenode IRC. There are several RH devs right now and we sort of struggle of not having any in-depth docker specialist. Only if that's possible. And should you decide to join, just address any post to ansyeblya/aweiteka/dustymabe.

**Comment by thaJeztah** [comment] 2016-04-21 13:33
@eeluve I think @runcom would be the best person for that; he's both a Docker maintainer, and employed by Red Hat (so knows of all the differences there)

**Comment by eeluve** [comment] 2016-04-22 09:37
Ok, "your people" in IRC helped me and I started several registries on various OS. Yet everything works fine. Locally querying the registry with docker_registry list and remotely with: curl -k -u user:pass -X GET https://domain.local:5000/v2/_catalog. Actually figured myself, somehow missed this part in API part of the manual, it's so huge. May make sense to cut abit to prevent TL issues ;)

**Comment by thaJeztah** [comment] 2016-04-25 13:21
The https://github.com/docker/distribution/issues issue tracker is for issues around the OSS docker registry; you can try the #docker-distribution IRC channel (but I think most people are in San Francisco, so may not be online yet)

**Comment by eeluve** [comment] 2016-04-25 14:52
Ye, I've tried distribution channel already. Will try again in couple hours. So far collected several questions about registry 2.4 and container issues in general: http://stackoverflow.com/questions/36841599/several-issues-regarding-registry-2-4 . If you could possibly link this to someone with clues, that would be great.
