### ISSUE TITLE
`docker cp` blocking `docker exec`

### ISSUE THREAD

**Issue by tusharmakkar08** [docker/docker#30665] opened 2017-02-02 06:50 UTC
I am using docker 1.12.3. When I am trying to `docker cp` a file, I can't access the container until the copy is completed. 

Please let me know if you need more information (or if you want this kind of issues to be formatted differently / reported in a different place).

**Comment by thaJeztah** [comment] 2017-02-02 07:01
ping @jlhawn

**Comment by thaJeztah** [comment] 2017-02-02 07:07
actually, just remembered that we have an issue for this. This is a duplicate of https://github.com/docker/docker/issues/29058; you can find some explanation there. Please subscribe to that issue to keep informed about updates

I'll close this issue because it's a duplicate, but feel free to comment after I closed

**Closed by thaJeztah** 2017-02-02 07:07 UTC
