### ISSUE TITLE
Inconsistent mount order of tmpfs directories

### ISSUE THREAD

**Issue by noidi** [docker/docker#22327] opened 2016-04-26 07:28 UTC
**Description of problem:**

When passing multiple `--tmpfs` switches to `create` or `run`, the mount order of the `tmpfs` directories is unpredictable. This causes random failures when mounting one `tmpfs` within another: if the parent directory is mounted after its child, it shadows the child. Restarting the container usually fixes the issue (but not always).

One example where nested `tmpfs` directories are needed is running Ubuntu's `systemd` in an unprivileged container. Ubuntu's `systemd` requires both `/run` and `/run/lock` to be `tmpfs` mounts. If `/run` is mounted after `/run/lock`, `systemd` fails to start with the following error: `Failed to mount tmpfs at /run/lock: Permission denied`.

Here's an example of two consecutive container starts where the mount order has changed.

    $ docker run --rm -it --tmpfs /run --tmpfs /run/lock ubuntu:16.04 bash -c 'mount | grep /run && find /run'
    tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
    tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
    /run
    /run/lock

    $ docker run --rm -it --tmpfs /run --tmpfs /run/lock ubuntu:16.04 bash -c 'mount | grep /run && find /run'
    tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
    tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
    /run

This test gives us some kind of an idea of how often the issue occurs on my machines (a Linux laptop and a Windows PC):

    $ for i in $(seq 200); do docker run --rm -it --tmpfs /run --tmpfs /run/lock ubuntu:16.04 bash -c 'test -d /run/lock && echo -n . || echo -n F'; done
    .....F..........FF...F....F...F..F....................F..............F........................F.................FF..........F........F...FF.F.........F..................F.................FF....FF.....

That's 23 failures in 200 container starts, or ~10%. Swapping the order of the `tmpfs` switches makes no difference to the ratio of successes and failures.

`docker version`:

    Client:
     Version:      1.11.0
     API version:  1.23
     Go version:   go1.5.4
     Git commit:   4dc5990
     Built:        Wed Apr 13 18:34:23 2016
     OS/Arch:      linux/amd64

    Server:
     Version:      1.11.0
     API version:  1.23
     Go version:   go1.5.4
     Git commit:   4dc5990
     Built:        Wed Apr 13 18:34:23 2016
     OS/Arch:      linux/amd64

`docker info`:

    Containers: 91
     Running: 12
     Paused: 0
     Stopped: 79
    Images: 132
    Server Version: 1.11.0
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 320
     Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins: 
     Volume: local
     Network: null host bridge
    Kernel Version: 3.16.0-38-generic
    Operating System: Ubuntu 14.04.3 LTS
    OSType: linux
    Architecture: x86_64
    CPUs: 4
    Total Memory: 15.38 GiB
    Name: melanthos
    ID: YCTG:5OWP:HBAG:CUER:NTRR:4GDN:SZBZ:5RCN:HPVC:4XEE:5VNL:VJXM
    Docker Root Dir: /var/lib/docker
    Debug mode (client): false
    Debug mode (server): false
    Registry: https://index.docker.io/v1/

`uname -a`:

    Linux melanthos 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Environment details (AWS, VirtualBox, physical, etc.):**

The information above is from a native Docker on a laptop running Linux Mint 17.3. I've reproduced the issue with the same failure rate on a Windows 7 PC with the latest Docker Toolbox and boot2docker running in VirtualBox.

**How reproducible:**

Keep starting containers created with the following options:

    $ docker run --rm -it --tmpfs /run --tmpfs /run/lock ubuntu:16.04 bash -c 'mount | grep /run && find /run'

**Actual Results:**

Occasionally `/run` is mounted after `/run/lock`, causing `/run/lock` to disappear from the file system.

**Expected Results:**

The `tmpfs` directories should be mounted in a fixed order: either the order in which the `--tmpfs` switches were given, or sorted by path length from shortest to longest (so parents are always mounted before their children).

**Additional info:**

This issue is probably related #21916, but does not involve volume mounts.

**Comment by runcom** [comment] 2016-04-26 07:47
right, that should be because tmpfs is a map which isn't consistent when looping

**Comment by noidi** [comment] 2016-04-26 08:03
I'm pinging @rhatdan for two reasons:

1. He's the author of the `--tmpfs` switch (#13587), so he might be interested in this issue.

2. Now that I'm bothering Dan anyway, I'd like to thank him for the great work he's done to make `systemd` work in an unprivileged Docker container. With `systemd`, containers are "server-like" enough to make them useful for testing our Ansible-based deployment and provisioning scripts. Thanks, Dan! (And of course, thanks to the whole Docker team, but you're too many to mention!)

**Comment by runcom** [comment] 2016-04-26 08:29
reproduced and proposed a fix #22329

**Comment by rhatdan** [comment] 2016-04-26 13:25
Thanks @noidi 

I like @runcom fix for this.

**Closed** 2016-04-27 00:23 UTC
Labels: kind/bug
