### ISSUE TITLE
Build Docker source behind proxy

### ISSUE THREAD

**Issue by NanXiao** [docker/docker#24627] opened 2016-07-14 08:47 UTC
I am trying to build `Docker` behind proxy, and add proxy environment variables at the beginning of [Dockerfile](https://github.com/docker/docker/blob/master/Dockerfile):  

```
FROM debian:jessie
ENV http_proxy http://web-proxy.corp.xxxxxx.com:8080/
ENV https_proxy https://web-proxy.corp.xxxxxx.com:8080/
```

From  the comment of this [post](http://nknu.net/running-docker-behind-a-proxy-on-ubuntu-14-04/), I think I should adding the following code at the end of [Dockerfile](https://github.com/docker/docker/blob/master/Dockerfile):
```
ENV http_proxy ""
ENV https_proxy ""
```
Like this:   

```
# Wrap all commands in the "docker-in-docker" script to allow nested containers
ENTRYPOINT ["hack/dind"]

# Upload docker source
COPY . /go/src/github.com/docker/docker

ENV http_proxy ""
ENV https_proxy ""
```

My question is whether this method is right? Will it introduce any side-effect? Or whether there is some idiomatic method to build `Docker` from source behind proxy?

Thanks very much in advance!

**Comment by thaJeztah** [comment] 2016-07-14 08:56
There's no need to create environment variables for those, you can use build time arguments to pass proxy env-vars; see https://docs.docker.com/engine/reference/builder/#/arg

**Comment by thaJeztah** [comment] 2016-07-14 08:59
However, please consider that the GitHub issue tracker is not a support forum, please use;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

I'll close this issue, because this is not a bug, but feel free to comment after that

**Closed by thaJeztah** 2016-07-14 08:59 UTC
