### ISSUE TITLE
Often got 504 response code when push or pull images on docker hub

### ISSUE THREAD

**Issue by vankhoa011** [docker/docker#13968] opened 2015-06-16 13:59 UTC
Please check the error on docker hub. I think docker hub got problem at this time.
We run Jenkins on AWS, We have two jobs to pull and push images.
We often got 504 response code from 7:00 AM to 11:00 AM UTC.

push images
```
fc5a9be8d6f6: Pushing
fc5a9be8d6f6: Image already pushed, skipping
21f61a4da26f: Pushing
21f61a4da26f: Image already pushed, skipping
372958da6262: Pushing
372958da6262: Image already pushed, skipping
ee7645ded957: Pushing
time="2015-06-16T16:24:49+07:00" level="fatal" msg="HTTP code 504 while uploading metadata: unexpected end of JSON input" 
Build step 'Execute shell' marked build as failure
```

pull images

```
a617de590f54: Error pulling image (latest) from XXXX, endpoint: https://registry-1.docker.io/v1/, Server error: Status 504 while fetching image layer (afb0205be543455461a56519db19ce6d324b8b0370864d56157e3b0e9051f683)
a617de590f54: Error pulling image (latest) from XXX, Server error: Status 504 while fetching image layer (afb0205be543455461a56519db19ce6d324b8b0370864d56157e3b0e9051f683)
```

More information:
docker version
```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

uname -a
```
ubuntu@ip-10-0-0-17:~$ uname -a
Linux ip-10-0-0-17 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ferrants** [comment] 2015-06-16 15:20
Yeah, I get this all the time, too.

**Comment by geeknam** [comment] 2015-06-17 02:01
:+1:

**Comment by yanivomc** [comment] 2015-06-17 06:52
Same goes here.
we got the same problem.

**Comment by bacheson** [comment] 2015-06-17 13:55
same problem here

**Comment by thaJeztah** [comment] 2015-06-17 17:05
Issues related to Docker Hub are not handled in this issue tracker and should be reported via https://support.docker.com, so could you open a ticket there? Thanks!

I'm going to close this issue as this looks to be an issue with Docker Hub, not Docker, but feel free to comment here if you think I closed this by mistake.

**Closed by thaJeztah** 2015-06-17 17:05 UTC
Labels: Distribution

**Comment by ferrants** [comment] 2015-06-17 18:30
What version of docker is everyone using? I was experiencing this issue on docker 1.4.1. I am testing with 1.5.0 now and have not run into the issue yet.

**Comment by anshuljoshi** [comment] 2015-07-13 07:02
I too was facing the same problem while pushing the image with Docker version 1.7.0, build 0baf609.
Simply doing:
{% highlight sh %}
sudo docker push my/test
{% endhighlight %}
resolved it. So, I suppose "sudo" is needed because of some permission issue.

**Comment by levilovelock** [comment] 2015-07-16 01:33
Also experiencing this with 1.7.0 against a private repo.

**Comment by thaJeztah** [comment] 2015-07-16 06:26
@levilovelock this issue is about pushing to Docker Hub, so possibly not related to your issue. Docker 1.7.1 was just released; could you test if you're still able to reproduce on 1.7.1?

**Comment by levilovelock** [comment] 2015-07-16 07:39
Yeah I actually think the issue is completely related to registry connection flakiness. I highly doubt running the command with sudo makes a difference. Cannot confirm 1.7.1 makes a difference unfortunately!

**Comment by mave99a** [comment] 2015-12-06 00:41
This problem still exist as of today. :(

**Comment by thaJeztah** [comment] 2015-12-06 01:04
@mave99a please see my earlier comment; https://github.com/docker/docker/issues/13968#issuecomment-112878547
