### ISSUE TITLE
docker push fails with 400 trying to push manifest

### ISSUE THREAD

**Issue by yagey** [docker/docker#13143] opened 2015-05-12 02:12 UTC
I'm trying to follow the guide at:
https://docs.docker.com/userguide/dockerimages/#building-an-image-from-a-dockerfile

no matter what docker container I build, it fails to upload to docker hub.

docker version:
[ec2-user@ip-172-31-1-170 sinatra]$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 4749651/1.6.0
OS/Arch (client): linux/amd64
DEBU[0674] Calling GET /version
INFO[0674] GET /v1.18/version
INFO[0674] +job version()
INFO[0674] -job version() = OK (0)
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 4749651/1.6.0
OS/Arch (server): linux/amd64

docker info:
 sudo docker info
DEBU[1192] Calling GET /info
INFO[1192] GET /v1.18/info
INFO[1192] +job info()
INFO[1192] +job subscribers_count()
INFO[1192] -job subscribers_count() = OK (0)
INFO[1192] +job registry_config()
INFO[1192] -job registry_config() = OK (0)
DEBU[1192] libdevmapper(6): ioctl/libdm-iface.c:1768 (4) dm status docker-202:1-263663-pool  OF   [16384] (*1)
INFO[1192] -job info() = OK (0)
Containers: 3
Images: 11
Storage Driver: devicemapper
 Pool Name: docker-202:1-263663-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.201 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.742 GB
 Metadata Space Used: 1.753 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.14.35-28.38.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.03
CPUs: 4
Total Memory: 7.308 GiB
Name: ip-172-31-1-170
ID: Z56D:AUKP:RB25:GRBI:W64X:Z2N4:FLV7:CKMJ:VU7K:ODZF:E6HT:PNOK
Debug mode (server): true
Debug mode (client): false
Fds: 18
Goroutines: 18
System Time: Tue May 12 02:17:38 UTC 2015
EventsListeners: 0
Init SHA1: 85f0bb535c2cc3b9818b73a39a69b6ffc691cc19
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker
Username: hack14
Registry: [https://index.docker.io/v1/]

uname -a:
 uname -a
Linux ip-172-31-1-170 3.14.35-28.38.amzn1.x86_64 #1 SMP Wed Mar 11 22:50:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Basic AWS instance with docker installed.

docker push debug logs (last lines):
DEBU[1489] Pushing layer: a82efea989f94b1d9fac76e26e37b0bbde11047a3afcaa47064949dfa3b3209b
37bea4ee0c81: Image already exists
DEBU[1489] [registry] Calling "HEAD" https://registry-1.docker.io/v2/hack14/sinatra/blobs/sha256:909cd34c6fd77d398af1d93e9d4f7f76104903f237be3d4db7b345a19631f291
DEBU[1489] https://registry-1.docker.io/v2/hack14/sinatra/blobs/sha256:909cd34c6fd77d398af1d93e9d4f7f76104903f237be3d4db7b345a19631f291 -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.3.3 kernel/3.14.35-28.38.amzn1.x86_64 os/linux arch/amd64]]
DEBU[1489] Using cached token for hack14
DEBU[1489] hostDir: /etc/docker/certs.d/registry-1.docker.io
DEBU[1489] Pushing layer: e9e06b06e14c2f7d8df0251e3bb852c3a10a70639498163d4f180a823c18fdfc
a82efea989f9: Image already exists
DEBU[1489] [registry] Calling "HEAD" https://registry-1.docker.io/v2/hack14/sinatra/blobs/sha256:e190868d63f8f8b85b026e53b5724c3c2a4548e1d642953442559cfa5f79b2c9
DEBU[1489] https://registry-1.docker.io/v2/hack14/sinatra/blobs/sha256:e190868d63f8f8b85b026e53b5724c3c2a4548e1d642953442559cfa5f79b2c9 -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.3.3 kernel/3.14.35-28.38.amzn1.x86_64 os/linux arch/amd64]]
DEBU[1489] Using cached token for hack14
DEBU[1489] hostDir: /etc/docker/certs.d/registry-1.docker.io
DEBU[1490] Pushing hack14/sinatra:latest to v2 repository
e9e06b06e14c: Image already exists
INFO[1490] Signed manifest for hack14/sinatra:latest using daemon's key: Z56D:AUKP:RB25:GRBI:W64X:Z2N4:FLV7:CKMJ:VU7K:ODZF:E6HT:PNOK
DEBU[1490] [registry] Calling "PUT" https://registry-1.docker.io/v2/hack14/sinatra/manifests/latest
DEBU[1490] https://registry-1.docker.io/v2/hack14/sinatra/manifests/latest -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.3.3 kernel/3.14.35-28.38.amzn1.x86_64 os/linux arch/amd64]]
DEBU[1490] Using cached token for hack14
DEBU[1490] hostDir: /etc/docker/certs.d/registry-1.docker.io
DEBU[1490] Unexpected response from server: "{\"errors\":[{\"code\":\"DIGEST_INVALID\",\"message\":\"provided digest did not match uploaded content\",\"detail\":\"error unmarshalling public key: JWK EC Public Key ID does not match: Z56D:AUKP:RB25:GRBI:W64X:Z2N4:FLV7:CKMJ:VU7K:ODZF:E6HT:PNOK\"}]}\n" http.Header{"Docker-Distribution-Api-Version":[]string{"registry/2.0"}, "Date":[]string{"Tue, 12 May 2015 02:22:36 GMT"}, "Content-Length":[]string{"238"}, "Content-Type":[]string{"text/plain; charset=utf-8"}, "Strict-Transport-Security":[]string{"max-age=31536000"}}
Error pushing to registry: Server error: 400 trying to push hack14/sinatra:latest manifest
INFO[1490] -job push(hack14/sinatra) = ERR (1)
FATA[0071] Error pushing to registry: Server error: 400 trying to push hack14/sinatra:latest manifest

any ideas please?

**Comment by dmp42** [comment] 2015-05-12 02:34
Hi @yagey 

Are you using a RedHat packaged docker?

**Comment by yagey** [comment] 2015-05-12 03:42
Yes, the Amazon AMI is apparently RHEL based, why do you ask, is there a known issue I can address?  I can try with a different distro tomorrow if needed.

**Comment by thaJeztah** [comment] 2015-05-12 04:01
@dmp42 https://github.com/docker/docker/commit/47496519da9664202d900d3635bb840509fa9647 is "our" 1.6.0 release, it's not the patched RH release (if that's what you were thinking of)

**Comment by yagey** [comment] 2015-05-12 18:09
FYI, retried the same steps with Ubuntu and it worked.

**Comment by kyriesent** [comment] 2015-05-12 20:00
+1 on Amazon AMIs; if I'm seeing this should I switch off of an RHEL based instance on EC2?

My details below. Thanks for all the hard work! :sunny: 

`docker version`:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 4749651/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 4749651/1.6.0
OS/Arch (server): linux/amd64

`docker info`:
Containers: 0
Images: 26
Storage Driver: devicemapper
 Pool Name: docker-202:96-1577515-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.92 GB
 Data Space Total: 107.4 GB
 Data Space Available: 38.84 GB
 Metadata Space Used: 2.74 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Data loop file: /mnt/docker/devicemapper/devicemapper/data
 Metadata loop file: /mnt/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.14.35-28.38.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.03
CPUs: 1
Total Memory: 3.68 GiB
Name: ip-11-0-0-119
ID: GX6U:EOSO:66Q7:MX3L:SZYW:VEQM:HQEG:AJXI:QZQU:JAMQ:CM36:TDKB
Username: kyriesent
Registry: [https://index.docker.io/v1/]

`uname -a`:
Linux ip-11-0-0-119 3.14.35-28.38.amzn1.x86_64 #1 SMP Wed Mar 11 22:50:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
AWS Amazon Linux AMI (ami id: ami-1ecae776)

How reproducible:
Any image I try to push to dockerhub gives the same error

Steps to Reproduce:
1. `docker run -it --name=pushtest debian:wheezy`
2. `exit container`
3. `docker commit pushtest <name>/pushtest`
4. `docker push <name>/pushtest`

Actual Results:
```
a9f682ad9919: Image already exists
b3d362b23ec1: Image successfully pushed
21e4345e9035: Image successfully pushed
FATA[0090] Error pushing to registry: Server error: 400 trying to push seelio/pushtest:latest manifest
```

Expected Results:
Successful push to Docker Hub

Additional info:
None

**Comment by yagey** [comment] 2015-05-12 21:05
@kyriesent using an ubuntu EC2 image has allowed to workaround this.

**Comment by pbecotte** [comment] 2015-05-13 23:18
FYI- I was getting this repeatedly today with a specific image.  I just got my stuff working again, I don't have any debug logs, but I want to explain the situation.

I have jenkins slaves running ubuntu 14.04 with docker 1.6.1 installed using aufs.  They build and push my images.  These have been successful consistently.

I was deploying to an Amazon Linux AMI running 1.5.0 for my dev environment.  Today, this started failing.  It runs docker-compose pull; docker-compose up -d; with a templated docker-compose.yml file.  Every failure showed pull working on each image, then it would start creating containers.  When it got to my fluentd image, it would start pulling again, and fail with an io error.  (is this a bug with compose that docker-compose pull can fail silently?)  I had already moved my slaves to ubuntu 14.04 with 1.6.1, so I just updated my dev box to use that AMI and it resolved the issue.

A little while ago, someone pointed out that our staging environment in AWS ECS didn't have the latest version.  I looked and saw that the fluentd container wasn't starting.  With manual intervention, I logged into the instances and found that I could not pull my fluentd image, and I also could not push the older versions of the same image I already had on that machine.  The same commands worked sucessfully from my local ubuntu machine.  Pushing failed with the error in this bug ticket, pulling failed with FATA[0065] Get https://registry-1.docker.io/v1/repositories/bamx/fluentd/tags: read tcp 162.242.195.84:443: i/o timeout

I was not up for trying to create an ECS enabled AMI tonight.  I found that the docker hub page for my organization couldn't even give me a list of tags for that repo.  I wound up deleting our bamx/fluentd repo and then recreating it.  I pushed the latest version again after doing so, and my ECS deployments finally updated to the new version.

**Comment by euank** [comment] 2015-05-15 20:47
This issue should be fixed now! If you are running Amazon Linux AMI or the ECS Optimized AMI, you should update the docker package (`sudo yum install docker` or just `sudo yum update`) to pick up the fix. The fixed version (`rpm -q docker` will show the version) is `1.6.0-1.5.amzn1`. Despite the `1.6.0` version, this does include `1.6.1`'s security patches (see [here](https://alas.aws.amazon.com/ALAS-2015-522.html)).

This issue was caused by how Docker was packaged for Amazon Linux (and by extension the ECS Optimized AMI). Specifically, the Docker package on Amazon Linux used an older version of libtrust than Docker recommends and caused this problem. [This AWS forum post](https://forums.aws.amazon.com/thread.jspa?messageID=623772) goes into a little more depth.

Sorry for the inconvenience this issue caused.

**Comment by calavera** [comment] 2015-05-15 21:18
Thanks for the explanation @euank.

@yagey I'm going to close this issue since it looks like it's solved. Thanks for reaching out!

**Closed by calavera** 2015-05-15 21:18 UTC
Labels: Distribution
