### ISSUE TITLE
odd "no such file or directory" error with overlay backend

### ISSUE THREAD

**Issue by jmtd** [docker/docker#11012] opened 2015-02-25 15:37 UTC
I'm getting a very odd "no such file or directory" situation with a simple image, built using

    FROM jmtd/debian:buildd
    MAINTAINER Jonathan Dowland <jmtd@debian.org>
    RUN apt-get update     && apt-get build-dep -y --no-install-recommends squishyball     && apt-get clean
    CMD ["/bin/bash"]

as follows:

    $ sudo docker build ./
    …
    INFO[0044] lstat /var/lib/docker/overlay/2d582b61ed2f858de066e550b5750fae2fdd142cf85280a19f6c0b3e9fb24cfb/merged/var/lib/apt/lists/http.debian.net_debian_dists_sid_Release: no such file or directory 

The exact file that is complained about varies from build to build. The container is still available, and the error reproducible:

    $ sudo docker diff elated_franklin 
    FATA[0000] Error response from daemon: lstat /var/lib/docker/overlay/fd47fb7583498a36c779f009ad116621658664f29f3b190eaa2f65f2fc92b78e/merged/var/lib/apt/lists/http.debian.net_debian_dists_sid_Release: no such file or directory 

This is with

    # docker version| sed 's/^/    /'
    Client version: 1.5.0-dev
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): eb88fa7-dirty
    OS/Arch (client): linux/amd64
    Server version: 1.5.0-dev
    Server API version: 1.18
    Go version (server): go1.4.2
    Git commit (server): eb88fa7-dirty

(this is `cd9769c55e3c0c405854b84c2c4bd273be79b23d` + [this patch](https://git.centos.org/blob/rpms!docker/c7/SOURCES!secrets.patch), which I've pushed [here](https://github.com/jmtd/docker/tree/docker-1.5.0-dev%2Bsecrets) for convenience). I'm using the overlay storage backend, on top of Linux `3.18.7-200.fc21.x86_64`, with `/var/lib/docker` a distinct XFS partition.

Any clues much appreciated ☺

**Comment by jmtd** [comment] 2015-02-26 10:04
Managed to build the same thing fine using

    Containers: 1
    Images: 7
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Dirs: 9
    Execution Driver: native-0.2
    Kernel Version: 3.14.0-2-amd64
    Operating System: Debian GNU/Linux 7 (wheezy)

Also, exported that via `save` and importing on the buggy system with `load` works fine.

**Comment by jfrazelle** [comment] 2015-02-26 20:04
hmmm maybe @vbatts has an idea? or @unclejack

**Comment by jmtd** [comment] 2015-02-27 10:21
Reproduced with a minimal `Dockerfile` as follows

    FROM jmtd/debian:wheezy
    MAINTAINER Jonathan Dowland <jmtd@debian.org>

yields

    Sending build context to Docker daemon 20.26 MB
    Sending build context to Docker daemon 
    Step 0 : FROM jmtd/debian:wheezy
     ---> f50abd82b67f
    Step 1 : MAINTAINER Jonathan Dowland <jmtd@debian.org>
    INFO[0000] mkdir /var/lib/docker/overlay/1ab52808edb8c8905d1ff6a02ee5348c255b83806e58694a3797d7b3d2d407f5-init/merged/dev/shm: invalid argument

**Comment by coolljt0725** [comment] 2015-02-27 11:23
@jmtd @jfrazelle I also can reproduce this use the default `Docker Root Dir: /var/lib/docker`, but when I change the Docker Root Dir  to `/home/tmp`  use `-g ` when start the docker daemon, I can't reproduce

**Comment by vbatts** [comment] 2015-04-10 14:01
perhaps related to #10294
`overlay` currently only supports ext4 as the underlying fs, but xfs progress is being made

**Comment by jmtd** [comment] 2015-04-13 08:25
Very likely, thanks — I'll try it with ext4 today and see how I get on.

**Comment by thaJeztah** [comment] 2015-04-13 23:41
(I added the "overlay" label again, but I see that it has been added/removed a few times, so if there's a particular reason to **not** have this label, please leave a comment :))

**Comment by stevenschlansker** [comment] 2015-05-15 19:44
We switched to overlay yesterday and are already seeing non-deterministic problem like this, across multiple containers and teams:

```
++ cut -d . -f 1
./../otpl-deploy-scripts/bin/otpl-deploy: line 218: cut: command not found
```

```
[Step 2/5] jetbrains.buildServer.agent.runner.CannotBuildCommandLineException: Unable to find java executable at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
	at jetbrains.buildServer.agent.runner.JavaCommandLineBuilder.buildPath2Java(JavaCommandLineBuilder.java:155)
	at jetbrains.buildServer.agent.runner.JavaCommandLineBuilder.build(JavaCommandLineBuilder.java:107)
```

**Comment by stevenschlansker** [comment] 2015-05-15 20:15
I can confirm something is seriously fucked up:
```
root@mesos-slave8-qa-uswest2:~# docker exec -it 0adffe3c5da6 /bin/bash
bash-4.3# ls
bash: ls: command not found
bash-4.3# echo *
*
bash-4.3# pwd
/
bash-4.3# /bin/ls
bash: /bin/ls: No such file or directory
bash-4.3# /bin/*
bash: /bin/*: No such file or directory
bash-4.3# find .
.
bash-4.3# bash  # NOTE HOW THIS SUCCEEDS
bash-4.3# exit
bash-4.3# ps
bash-4.3# find /bin/bash
/bin/bash
bash-4.3# find /bin
/bin
```

Looking from the outside in:
```
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay# cd 0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls
lower-id  merged  upper  work
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls merged/
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls upper/
dev  etc  home  mnt  run  tmp  var
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find work
work
work/work
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find merged
merged
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find merged/
merged/
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls merged/
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# find upper
upper
upper/.dockerenv
upper/.dockerinit
upper/etc
upper/etc/hosts
upper/etc/mtab
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls -lh merged/bin/bash
-rwxr-xr-x 0 root root 998K Oct  7  2014 merged/bin/bash
root@mesos-slave8-qa-uswest2:/mnt/docker/overlay/0adffe3c5da6dca485194ed26135361ee6ea46fbec841ef6a1750997a5673d83# ls -lh merged/bin/
total 0
```

**Comment by calavera** [comment] 2015-07-16 22:33
I'm going to close this issue since it looks like it's related to the xfs support and therefore duplicated. Please, feel free to reopen if that's not the case.

**Closed by calavera** 2015-07-16 22:33 UTC
Labels: exp/expert, kind/bug, system/overlay, system/storage

**Comment by maiasmith** [comment] 2017-07-06 18:26
I had a similar error
`failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/...: no such file or directory`

and fixed it thanks to @cptaffe's [comment](https://github.com/docker/for-mac/issues/1396#issuecomment-284471057)

Steps to resolve

1. Screen into the Docker VM
2. Remove /var/lib/docker
3. Restart Docker via the widget

```
$ screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
$ umount /var/lib/docker/overlay2
$ rm -rf /var/lib/docker
```

**Comment by badamsbb** [comment] 2018-05-30 08:53
@zhangxiansheng do you have any idea as to why this happens?

**Comment by thaJeztah** [comment] 2018-05-30 09:38
If you are running `overlay` or `overlay2` on top of XFS, make sure you don't see this warning in the output of `docker info`:

```
The backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
Reformat the filesystem with ftype=1 to enable d_type support.
```

You can also check the `Supports d_type` field in the storage-driver section in the output of `docker info`; 

```
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
```

If you _do_ see that warning, the problem may be related to that.

Running overlay (or overlay2) on XFS without `d_type` is known to cause issues. Docker currently "allows" it for backward-compatibility on existing installations, but will not use the overlay/overlay2 driver on fresh installations.

Also see these issues, which contain some information https://github.com/moby/moby/issues/10294, https://github.com/moby/moby/issues/29873.

The RHEL release notes mentions this; https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html

> Note that XFS file systems must be created with the `-n ftype=1` option enabled for use as an overlay. With the rootfs and any file systems created during system installation, set the `--mkfsoptions=-n ftype=1` parameters in the Anaconda kickstart. When creating a new file system after the installation, run the `# mkfs -t xfs -n ftype=1 /PATH/TO/DEVICE` command. To determine whether an existing file system is eligible for use as an overlay, run the `# xfs_info /PATH/TO/DEVICE | grep ftype` command to see if the `ftype=1` option is enabled.
> 
> Note that OverlayFS provides a restricted set of the POSIX standards. Test your application thoroughly before deploying it with OverlayFS.
