### ISSUE TITLE
aws log driver should be able to assume role (get sts tokens)

### ISSUE THREAD

**Issue by freefood89** [docker/docker#23698] opened 2016-06-17 20:59 UTC
The aws log driver times out when calling AWS APIs. Looking at the source I don't seem to be able to find anything that assumes role (fetching an sts token) prior to making AWS CloudWatch API calls.

Since the log driver already contacts the metadata service to obtain the instance's region information I would recommend that the same be done to obtain the instance profile ARN [metadata docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) and assume role prior to making AWS API calls in the log driver

**Output of `docker version`:**

```
Version:      1.9.1
API version:  1.21
Go version:   go1.4.2
Git commit:   a34a1d5
Built:        Fri Nov 20 13:25:01 UTC 2015
OS/Arch:      linux/amd64

Server:
Version:      1.9.1
API version:  1.21
Go version:   go1.4.2
Git commit:   a34a1d5
Built:        Fri Nov 20 13:25:01 UTC 2015
OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
Images: 29
Server Version: 1.9.1
Storage Driver: devicemapper
Pool Name: docker-202:2-75559822-pool
Pool Blocksize: 65.54 kB
Base Device Size: 107.4 GB
Backing Filesystem: 
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 983.1 MB
Data Space Total: 107.4 GB
Data Space Available: 18.04 GB
Metadata Space Used: 2.523 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.145 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
CPUs: 2
Total Memory: 7.389 GiB
Name: --------
ID: --------
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS

**Steps to reproduce the issue:**
1. `sudo docker run --log-driver=awslogs --log-opt awslogs-region=us-east-1 --log-opt awslogs-group=awslogs-groupname --privileged imagename`

**Describe the results you received:**
Error response from daemon: Cannot start container --giant-hash--: Failed to initialize logging driver: RequestError: send request failed4:26:25 PM
caused by: Post https://logs.us-east-1.amazonaws.com/ : dial tcp 72.21.203.180:443: i/o timeout"

**Describe the results you expected:**
I expected the log group to be created

**Comment by thaJeztah** [comment] 2016-06-18 02:47
Thanks for suggesting, this looks like a duplicate of the discussion in https://github.com/docker/docker/pull/19617

**Comment by freefood89** [comment] 2016-06-20 02:04
Hi @thaJeztah 

I'm not sure that this is a duplicate of your pull request. My issue is primarily regarding the use of the awslogs driver in AWS without a permanent AWS secret and AWS key. Everytime an instance (ECS host machine) calls an AWS API it must checkout a token (AWS secret, key, and session token) that is valid for only one hour.

Unless I'm mistaken the golang SDK for aws does not assume role by default unlike the AWS CLI, which looks into ~/.aws/config to see if there's an ARN for an instance role [[reference]](http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html). This means that if a role ARN is specified in ~/.aws/config and if the AWS secret/key is not provided, then the awslogs driver should assume role (IAM API call) prior to calling the CloudWatch logs APIs.

**Comment by thaJeztah** [comment] 2016-06-20 03:21
let me ask @samuelkarp for input here 👍

**Comment by thaJeztah** [comment] 2016-06-20 03:22
(but I saw he's at DockerCon, so could take longer to respond)

**Comment by samuelkarp** [comment] 2016-06-23 18:12
@thaJeztah, thanks for pinging me (and it was great to meet you in person at DockerCon!)

@freefood89, it looks like there are a few different things going on here, so let me see if I can answer this piece-by-piece.

> Since the log driver already contacts the metadata service to obtain the instance's region information I would recommend that the same be done to obtain the instance profile ARN metadata docs and assume role prior to making AWS API calls in the log driver

The awslogs driver already uses the [credentials from instance metadata](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials) for making calls to the CloudWatch Logs API.  You can see the code that does this [here](https://github.com/docker/docker/blob/v1.11.2/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go).  You'll want to make sure you've added the [required permissions](https://docs.docker.com/engine/admin/logging/awslogs/#credentials) to the [instance profile](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html).

```
Error response from daemon: Cannot start container --giant-hash--: Failed to initialize logging driver: RequestError: send request failed4:26:25 PM
caused by: Post https://logs.us-east-1.amazonaws.com/ : dial tcp 72.21.203.180:443: i/o timeout"
```

This looks to me like the Docker daemon failed to reach the CloudWatch Logs endpoint at https://logs.us-east-1.amazonaws.com/ rather than a failure to retrieve credentials.  You'll want to make sure you have network connectivity on your instance and that you can actually reach the endpoint.

> I expected the log group to be created

I think this is the part that @thaJeztah thought was related to #19617.  As you'll see in that discussion, the awslogs driver relies on the log group already being created, but will automatically create the log stream for you.

**Closed** 2016-06-24 15:31 UTC
Labels: area/logging, version/1.9

**Comment by thaJeztah** [comment] 2016-06-24 16:31
Thanks @freefood89, and good to hear it's resolved for you
