### ISSUE TITLE
Overlay Network fails to forget exited images

### ISSUE THREAD

**Issue by sourcejockey** [docker/docker#22772] opened 2016-05-16 20:22 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.0
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   a6c1f14
 Built:        Wed Apr 13 05:58:31 UTC 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 6
 Paused: 0
 Stopped: 5
Images: 11
Server Version: swarm/1.2.0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 [REDACT GUID]: [REDACT IP]:[REDACT PORT]
  └ Status: Healthy
  └ Containers: 11
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 4.2 GiB
  └ Labels: com.docker.network.driver.overlay.bind_interface=eth1, executiondriver=native-0.2, kernelversion=3.18.21-2-rackos, operatingsystem=Debian GNU/Linux 7 (wheezy) (containerized), storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-16T20:17:40Z
  └ ServerVersion: 1.10.3
Plugins:
 Volume:
 Network:
Kernel Version: 3.18.21-2-rackos
Operating System: linux
Architecture: amd64
CPUs: 12
Total Memory: 4.2 GiB
Name: [REDACT GUID]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Carina

**Steps to reproduce the issue:**
1. Run some containers within an overlay network (restart=always)
2. Have some host issues that stop/otherwise mess up those containers.
3. rm -f exited containers, re-run

**Describe the results you received:**
500 Internal Server Error: service endpoint with name [NAME REDACTED] already exists.

**Describe the results you expected:**
A container running

**Additional information you deem important (e.g. issue happens only occasionally):**
To FIX this, I:
docker network disconnect -f <NETWORK> <CONTAINER>
(credit to idnar on that)

**Comment by thomasem** [comment] 2016-05-16 20:25
This appears to be the scenario described here: https://github.com/docker/docker/blob/master/docs/userguide/networking/work-with-networks.md: "There are certain scenarios such as ungraceful docker daemon restarts in multi-host network, where the daemon is unable to cleanup stale connectivity endpoints."

Wondering if this is a hard limitation, or something that could be handled by the docker daemon to essentially clean up orphaned endpoints?

**Comment by mavenugo** [comment] 2016-05-16 21:30
We resolved an issue recently https://github.com/docker/libnetwork/pull/1157 which addresses this issue. This fix is brought into docker/docker via https://github.com/docker/docker/pull/22582.

**Comment by thaJeztah** [comment] 2016-05-18 09:04
https://github.com/docker/docker/issues/22582 Was merged, so this should be fixed on master, and will be in docker 1.12

**Closed by thaJeztah** 2016-05-18 09:04 UTC

**Comment by franktranhb** [comment] 2017-05-31 04:10
I still counter the problem today.
```docker: Error response from daemon: endpoint with name APP already exists in network bridge.
```

Here is my docker version:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment] 2017-05-31 09:18
@franktranhb this issue is about overlay networking using an external k/v store, and only used if you're using "standalone swarm". If you are still having this issue, and have steps to reproduce, please open a new issue instead

**Comment by thaJeztah** [comment] 2017-05-31 09:18
I'll lock the conversation on this issue, because the original issue reported here was resolved
