### ISSUE TITLE
Add --dns and --dns-search to docker build

### ISSUE THREAD

**Issue by cognitiaclaeves** [docker/docker#22678] opened 2016-05-11 22:56 UTC
I'm unable to pip3 install a package from our local git repository.  I'd like an option to pass on the build command line that enables the dns and dns-search flags for the one-time purpose of the build.

It looks like I'm going to end up working around this by hacking the /etc/resolv.conf file for the host where the Dockerfile is built for the purpose of the contents getting copied into the container at build-time.

This has a few draw backs. First, it seems silly to touch the host to get the desired contents into the container. Second, it results in permanent nameservers that won't make sense after the container is deployed in another environment.

But it gets me to the point where I can provide a single script that only mangles a temporary file on the host that can be run to build the Dockerfile.

This does not appear to be the case with the other solutions I've seen suggested when this request has been submitted before.

The use-case is that I'd like any developer to be able to build the Dockerfile in a corporate data-center without changing their docker server settings. The Dockerfile will be deployed in a different environment, where its default nameserver implementation should work fine at run-time.

**Comment by justincormack** [comment] 2016-05-12 15:04
Why can't you set the `--dns` options on the daemon for this on the build machine? https://docs.docker.com/engine/reference/commandline/daemon/#daemon-dns-options

**Comment by thaJeztah** [comment] 2016-05-12 15:18
I agree with @justincormack here. If internal hostnames are used, the docker daemon should be configured to use the internal DNS server. So I'm -1 on adding this feature

**Comment by 13josh** [comment] 2016-07-27 18:52
I'm trying to figure out how to do this on the Docker for Mac Beta and can't find a way.  And I tried to modify the resolv.conf file as part of the build but it looks like it gets blown before each intermediate image.

**Comment by justincormack** [comment] 2016-10-13 11:36
@13josh you can open an issue on https://github.com/docker/for-mac/issues but we are switching to use local host information, so you can try to change it on your Mac.

You need to modify the resolv.conf on each build line, yes.

**Comment by thaJeztah** [comment] 2016-10-14 00:47
Looks like this is a duplicate of https://github.com/docker/docker/issues/24928, which contains some more information; and an issue on docker for mac was opened in https://github.com/docker/for-mac/issues/179

I'll close this issue

**Closed by thaJeztah** 2016-10-14 00:47 UTC
Labels: area/builder, kind/feature
