### ISSUE TITLE
service docker restart error 

### ISSUE THREAD

**Issue by wenxueliu** [docker/docker#10060] opened 2015-01-13 03:57 UTC
`uname -a`

Linux wenxueliu 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

` sudo /etc/init.d/docker.io restart`

 * Docker is managed via upstart, try using service docker.io restart

`service docker.io restart`

stop: Unknown job: docker.io
start: Unknown job: docker.io

**Comment by HuKeping** [comment] 2015-01-13 08:47
check your log of docker.io 

`$ cat /var/log/upstart/docker.io.log`

**Comment by jfrazelle** [comment] 2015-01-14 19:29
when you check the logs can you give the out put here because this is not enough information for us to debug

**Comment by unclejack** [comment] 2015-02-03 15:50
It seems you're actually using a version of Docker which is extremely old.

Please follow the instructions from the "Docker-maintained package Installation" section to install a newer Docker version.

This bug report isn't an actual problem. Discussing this on the forums or on the #docker IRC channel on Freenode would be better.

I'm going to close this issue now as there's no reason to keep this issue open. The discussion can continue even while the issue is closed.

**Closed by unclejack** 2015-02-03 15:50 UTC
