### ISSUE TITLE
setcap breaks docker build: "Untar exit status 1 operation not supported"

### ISSUE THREAD

**Issue by pwaller** [docker/docker#12839] opened 2015-04-28 08:02 UTC
Steps to reproduce:

```
$ cat > Dockerfile <<EOF
FROM scratch
COPY . /foo
EOF

$ touch foo && sudo setcap 'cap_net_bind_service=+ep' foo 

$ docker build .

Sending build context to Docker daemon 4.096 kB
Sending build context to Docker daemon 
Step 0 : FROM scratch
 ---> 
Step 1 : COPY . /foo
INFO[0000] Untar exit status 1 operation not supported  
```

Nothing useful in the docker daemon log either. This was rather confusing when `COPY .` was actually copying a large tree of files with the setcap'd file buried in it!

**Comment by thaJeztah** [comment] 2015-06-08 07:04
I was able to reproduce this on 1.7.0-rc2, with a slightly different error; `Untar re-exec error: exit status 1: output: operation not supported`

**Comment by vdemeester** [comment] 2015-06-08 07:15
I remember seeing stuff about *capabilities* when working on ``pkg/archive`` test. Does it fail for any *cap* set or just some (like the ``cap_net_bind_service``, or …) ?

**Comment by thaJeztah** [comment] 2015-06-08 07:18
Thanks @vdemeester, also wondering; @pwaller is this a specific use-case or just an error you encountered would [`--cap-add`](https://docs.docker.com/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration) (updated docs for the current release candidate: (Runtime privilege, Linux capabilities, and LXC configuration)[http://docs.master.dockerproject.org/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration]) give you what you need here?


Doesn't take away that the error-message is non-descriptive :)

**Comment by vdemeester** [comment] 2015-06-08 07:26
@thaJeztah hum that could be something as the [Runtime privilege, Linux capabilities, and LXC configuration](http://docs.master.dockerproject.org/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration) is for the ``run`` command, there is no such thing when building an image, which is what @pwaller does.

**Comment by thaJeztah** [comment] 2015-06-08 07:33
@vdemeester Correct, if it's needed during build (but cannot see if that's what's the exact use-case based on just the repro-code), which would bring us to; https://github.com/docker/docker/issues/1916.

**Comment by pwaller** [comment] 2015-06-08 07:34
@thaJeztah I had such a binary lying around in the directory, and I expected it to work or give a descriptive error message. I don't have a particular use case for this right now, though I can imagine some, such as starting a test server listening on a privileged port (to avoid the need to configure the port by default).

**Comment by thaJeztah** [comment] 2015-06-08 07:47
Thanks for the extra info, fyi, here's a discussion on binding to priviledged ports in a container as a non-priviledged user; https://github.com/docker/docker/issues/8460 (especially https://github.com/docker/docker/issues/8460#issuecomment-87123934).

**Comment by pwaller** [comment] 2015-06-08 09:16
Yeah, so for #8460 to work as expected, the process also needs to be setcap'ed, if I understand correctly. So this needs to work, too.

**Comment by pwaller** [comment] 2015-06-08 09:17
Yeah, so for #8460 to work as expected, the binary also needs to be setcap'ed in addition to `--cap-add` if I understand correctly. So this needs to work, too.

(I edited this message by deleting the previous one, apologies for people who get this twice).

**Comment by Jaykah** [comment] 2015-06-12 22:05
Having the same issue on build:

```
Step 14 : RUN mkdir /opt/postfix
 ---> Running in b722732fe40c
 ---> 8465f3c0bd20
Removing intermediate container b722732fe40c
Step 15 : ADD postfix /opt/postfix
time="2015-06-12T21:58:07Z" level=info msg="Untar exit status 1 operation not supported" 
Build step 'Docker Build and Publish' marked build as failure
```

Seems to be host-specific, since I only started getting it on new slave builds that were previously built on Jenkins master.

**Comment by pwaller** [comment] 2015-06-12 22:17
@Jaykah yours sounds like it could be an interesting separate issue. The one I reported above is due to setcap'd files, but I don't see how changing a line from `ADD foo /foo` to `ADD foo/* /foo/` should relate to this.

**Comment by Jaykah** [comment] 2015-06-12 22:36
@pwaller the thing is that I am building inside of a docker container (sorry, forgot to mention that) that is running --privileged=true. I am wondering whether something could have changed setcap in a way that would cause a Client version: 1.6.2 fail, while Client version: 1.5.0 (also --privileged), would build just fine

**Comment by Jaykah** [comment] 2015-06-19 01:19
Update: Now on Docker 1.7 I can no longer build using DIND. 

```
Untar re-exec error: exit status 1: output: operation not supported
```
at the beginning of every build. 

Would be glad to help isolate the issue.


```
docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

```
docker info
Containers: 0
Images: 0
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS (containerized)
CPUs: 4
Total Memory: 6.807 GiB
Name: Logstash1
ID: ZILV:PDZ6:NS2H:VAU4:5CYL:VHBZ:CCWG:N2DH:WBR5:LZS4:HTVM:VXRX
WARNING: No swap limit support
```

P.S. I am wondering if it would be better to open a new issue, or if this belongs here.

**Comment by pwaller** [comment] 2015-10-14 17:24
Ping this thread. Status update:

I just tried this on docker 1.8.3, and my original issue as stated is fixed. However, the capabilities aren't inside the image. I guess this is not surprising. Since I don't need that and my original issues is fixed, closing.

**Comment by thaJeztah** [comment] 2015-10-14 17:32
Thanks @pwaller

**Comment by pwaller** [comment] 2015-10-28 10:22
I just hit this again on 1.8.3, so I think I closed it incorrectly. Not sure why my minimum reproduce case didn't hit it.

**Comment by vdemeester** [comment] 2016-05-23 11:48
Cannot reproduce on 1.11 (and probably 1.10 and some others too). @pwaller I'll close this, but feel free to comment if you feel I should have not :angel:

**Closed by vdemeester** 2016-05-23 11:48 UTC
