### ISSUE TITLE
Client is Newer than Server

### ISSUE THREAD

**Issue by sivaswami** [docker/docker#27106] opened 2016-10-03 06:15 UTC
Hi, 
I have client on a different machine than HOST(server daemon). 
I get the below message "
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.19)
Do I need to upgrade server  each and every time for latest version of client ?

**Comment by thaJeztah** [comment] 2016-10-03 06:48
Ideally, yes; otherwise, the client will try to perform API calls that are not known by the daemon (for example, your try to use the swarm mode commands that were introduced in 1.12, but the daemon is still 1.11).

For _debugging_ purposes, you can override the API version that's used by the client through the `DOCKER_API_VERSION` environment variable, see https://docs.docker.com/engine/reference/commandline/cli/#/environment-variables

We are working on improvements in this area, and have the client negotiate the API version to use when connecting to an older version of the daemon.

I'll close this issue, because this is not a bug, and the GitHub issue tracker is not intended as a support forum (consider using https://forums.docker.com, or the #docker IRC channel), but feel free to continue the conversation

**Closed by thaJeztah** 2016-10-03 06:48 UTC
