### ISSUE TITLE
Docker default bridge network makes networking very slow

### ISSUE THREAD

**Issue by mustafaakin** [docker/docker#11911] opened 2015-03-29 21:39 UTC
Hi, I made these experiments: (native hardware, no virt)

Native:
```
$ time redis-benchmark -t set -n 1000000 -p 6379
264270.62 requests per second
```

Default bridged network mode: 

```
$ docker run -v /home/mustafa/redis-data:/data -d -p 9000:6379 dockerfile/redis
66058a4b3cdf6e2307cce43742b93c65c90575061d19f0a9cf8424790e3b642e
$ redis-benchmark -t set -n 1000000 -p 9000
117744.02 requests per second
````

Using directly host network: 

```
$ service stop redis-server
$ docker run -v /home/mustafa/redis-data:/data -d --net host dockerfile/redis
55591b69009a1cbcaabbc2a2cdbac5f8e8c626b1c3d1456c5dc2d120568299b6
$ time redis-benchmark -t set -n 1000000 -p 6379
260920.84 requests per second
```

So, my question is this a problem that cannot be solved? I do not know how to tune bridges, but almost 2.25x slow down is not acceptable. I know this benchmark is synthetic however it gives an idea. Is the NAT causing this?

**Comment by mustafaakin** [comment] 2015-03-29 21:45
Additinoal tests from other host:

```
mustafa@server1:~$ time redis-benchmark -t set -n 1000000 -p 6379 -h server2
^CT: 80703.47
mustafa@server1:~$ time redis-benchmark -t set -n 1000000 -p 9000 -h server2
^CT: 79326.52
```

It is not a problem in another host, since it is not enough to cause a bottlekneck, however on the same host the performance drops in a sad way.

**Comment by phemmer** [comment] 2015-03-30 05:44
Your tests don't make much sense to me.

First lets look at this one: 

```
$ docker run -v /home/mustafa/redis-data:/data -d -p 9000:6379 dockerfile/redis
66058a4b3cdf6e2307cce43742b93c65c90575061d19f0a9cf8424790e3b642e
$ time redis-benchmark -t set -n 1000000 -p 6379
264270.62 requests per second
```

You started the container, and forwarded port 9000, yet it appears you're telling the `redis-benchmark` utility to connect to localhost port 6379. This is not the container you just started.

----

Next lets look at your "native" and "--net host" metrics:

Native:

    117744.02 requests per second

`--net host`:

    260920.84 requests per second

Your native numbers are less than half the containerized numbers. This doesn't support the theory that it's the bridge which is slowing things down if native is so slow.


----

So, I'm going to completely ignore the metrics you provided and answer why this test would perform so slow in that one scenario.
The reason actually has nothing to do with the bridge, or NAT. The issue is likely that your `redis-benchmark` utility is connecting to localhost. When using container port forwarding, connecting to localhost from the docker host goes through the docker proxy. Meaning it does not use the iptables port redirection. The docker proxy is a userspace utility which forwards the TCP connection on to the container. Userspace utilities are inefficient when compared to the kernel.

There is an open issue to make it possible to disable the docker proxy, but it has unfortunately been idle for quite some time: #8356

**Comment by mustafaakin** [comment] 2015-03-30 05:49
Sorry, I have copied the tests wrongly from another issue I opened in Dockerfile/redis. https://github.com/dockerfile/redis/issues/3

**Comment by unclejack** [comment] 2015-03-30 08:05
This is a duplicate of #7857.

I'm going to close this issue now. Please continue the discussion on #7857.

**Closed by unclejack** 2015-03-30 08:05 UTC
