### ISSUE TITLE
can the Bridge interface be shown in the JSON, is that data available within container?

### ISSUE THREAD

**Issue by rhatdan** [docker/docker#8042] opened 2014-09-15 17:09 UTC
For a running container's json,
 "NetworkSettings": {
        "IPAddress": "172.17.0.2",
        "IPPrefixLen": 16,
        "Gateway": "172.17.42.1",
        "Bridge": "docker0",
        "PortMapping": null,
        "Ports": {}
---->  "interface": "veth4d43"
    },

better provide the interface element that shows by the "brctl show"now

# brctl show
bridge name	bridge id		STP enabled	interfaces
docker0		8000.56847afe9799	no		veth4d43

https://bugzilla.redhat.com/show_bug.cgi?id=1102561

**Comment by jfrazelle** [comment] 2015-02-26 01:29
closing as duplicate of https://github.com/docker/docker/issues/3909

**Closed by jfrazelle** 2015-02-26 01:29 UTC
