### ISSUE TITLE
PoolID missing in libnetwork api, /NetworkDriver.CreateNetwork call to remote driver

### ISSUE THREAD

**Issue by vikaschoudhary16** [docker/docker#23025] opened 2016-05-26 18:31 UTC
Please consider a scenario where two docker networks are created with subnets having same cidr.
The problem is we dont have any ways of associating an ip pool with a subnet. The calls to IPAM driver have no info on the network. the calls to the remote driver have no info on IP pools.

**Comment by aboch** [comment] 2016-05-26 23:30
>  The calls to IPAM driver have no info on the network.

This is by design. Please check https://github.com/docker/libnetwork/issues/489.


> the calls to the remote driver have no info on IP pools

This is not correct. The call to CreateNetwork() on the remote driver carries the pool information:

https://github.com/docker/docker/blob/v1.11.1/vendor/src/github.com/docker/libnetwork/driverapi/driverapi.go#L19

https://github.com/docker/docker/blob/v1.11.1/vendor/src/github.com/docker/libnetwork/driverapi/driverapi.go#L121

> Please consider a scenario where two docker networks are created with subnets having same cidr.

If you want two networks to be assigned identical address pool, but not share the same, I think you are looking for the address space:

https://github.com/docker/docker/blob/v1.11.1/vendor/src/github.com/docker/libnetwork/ipamapi/contract.go#L72


Looks like you need the ability to specify the address space when you are creating the network.

**Comment by mbanikazemi** [comment] 2016-05-27 03:40
@aboch Is the support for specifying the address space added to the cli? if not, is it in the works?

**Comment by vikaschoudhary16** [comment] 2016-05-27 07:37
@aboch  I tried setting address space from network create command using:
> --ipam-opt AddressSpace=myspace

What my ipam driver received in `/IpamDriver.RequestPool` : 
> {u'V6': False, u'Options': **{u'AddressSpace': u'myspace'}**, u'Pool': u'200.200.0.0/16', **u'AddressSpace': u'local_scope'**, u'SubPool': u'200.200.200.0/24'}

and what network driver receives in subsequent call `/NetworkDriver.CreateNetwork` call is this: 
>{u'NetworkID': u'c15e357f8aec36a6e2a9e47095e36a6ac71cc244bba0f118d5965e285a5a76fb', u'IPv4Data': [{u'Pool': u'200.200.200.0/24', u'Gateway': u'23.23.23.1/24', **u'AddressSpace': u''**}], u'IPv6Data': [], u'Options': {u'com.docker.network.enable_ipv6': False, u'com.docker.network.generic': {}}} 

**u'AddressSpace': u'local_scope'** is the one which ipam_driver is returning to libnetwork in `/IpamDriver.GetDefaultAddressSpaces`


**What is the syntax for setting addressspace per network? So that whatever addressSpace is passed at pool_creation to ipam driver, same addressSpace will be received at network creation call by network driver?**

**Comment by vikaschoudhary16** [comment] 2016-05-28 05:17
@aboch ,
Thanks for your pointers. It makes more sense to go with `address-spaces`. For that, I feel there should be UI support also, to enable user to configure address space per network using options for eg. `--address-space`. I have opened an issue, #23076. Does this make sense?

Regarding this issue, Can we take forward this issue as an enhancement to `network inspect`? 

Looking forward for your responses. 
Thanks.

**Comment by thaJeztah** [comment] 2016-08-04 19:09
Closing this, now that https://github.com/docker/docker/issues/23076 was opened

**Closed by thaJeztah** 2016-08-04 19:09 UTC
Labels: group/networking, kind/enhancement
