### ISSUE TITLE
Release 1.10.3?

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#20874] opened 2016-03-02 18:12 UTC
There are a number of issues found that are fixed post-1.10.2

In the past we've only really done a patch release for major issues (and cherry-picked minor fixes along with it).
Some of these relatively minor issues however can be a show-stopper for many users to upgrade, and waiting for 1.11 is not really feasible since 1.11 will absolutely have new bugs that also need to be worked out.

List of changes fixed after 1.10.2 is here: https://github.com/docker/docker/issues?utf8=%E2%9C%93&q=is%3Aclosed+milestone%3A1.10.3+

Number of open issues still pending with 1.10.2:
https://github.com/docker/docker/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.10.3

**Comment by jfrazelle** [comment] 2016-03-02 18:22
+1 if @tiborvass is up for another round

**Comment by calavera** [comment] 2016-03-02 18:23
SGTM

**Comment by thaJeztah** [comment] 2016-03-02 18:23
SGTM, was thinking of this earlier today

**Comment by icecrime** [comment] 2016-03-02 19:14
We have a [release process](https://github.com/docker/docker/blob/master/project/PATCH-RELEASES.md) for this, I don't think this is the right approach.

**Comment by stevenschlansker** [comment] 2016-03-02 19:23
Hi, for us in particular #19950 is killing us.  We either need a 1.10.3 release within the next couple of days or we will have to downgrade to 1.9.x

(Is it even possible to downgrade after the content migration?)

**Comment by cpuguy83** [comment] 2016-03-02 19:24
@StefanScherer yes it's possible. I doubt 1.10.3 would happen in in the next couple of days.

**Comment by AaronDMarasco-VSI** [comment] 2016-03-02 19:39
@icecrime How do we petition to have #19550 re-triaged from P2 to P0 to have that process kick in? I would think that a library not being able to properly handle concurrency (#20706) is a pretty big deal. For me personally, it's a Jenkins build system that has a ton of stuff going to stdout and stderr; on the order of 60-70MB each run.

**Comment by stevenschlansker** [comment] 2016-03-02 21:16
+1, at least for us, that bug looks a lot more like a P0 than a P2 (it can cause silent data corruption in end-user applications, if old deployments of old code versions silently coexist with newer ones, imagine there is a schema change or access to a singleton resource or the like)

I didn't see any guidelines on how to characterize P0 vs P2 in the release process doc, is that spelled out somewhere?  Or is it a maintainer judgment call?

**Comment by duglin** [comment] 2016-03-02 22:43
Would we want to consider a PR to change the Host header to address: https://github.com/docker/docker/issues/20865 ?

**Comment by cpuguy83** [comment] 2016-03-02 22:46
@duglin the issue there is (assuming that is indeed an issue, I haven't tested it out myself), that is a compatibility issue with all prior versions of Docker client due to the upgrade to go 1.6, is it not?

**Comment by duglin** [comment] 2016-03-02 22:49
I'd have to double-check, and will try to do so tonight, but I suspect that setting the Host header to "" when we're talking over a unix socket should be compatible - meaning no daemon changes should be needed.  And since we don't support newer clients talking to old server, I think we'd just need to test v1.10.x daemons.

**Comment by duglin** [comment] 2016-03-02 22:50
I'm assuming we'll compile v1.10.3 with golang 1.5, right?

**Comment by thaJeztah** [comment] 2016-03-02 23:02
@duglin yes, if it's going to be release (not decision yet) it'll be 1.5, but you can open a PR for the header, now, we can always close if it's not needed :innocent:

**Comment by duglin** [comment] 2016-03-03 00:57
just did some testing and it appears that a v1.10 client is ok talking to a v1.11 daemon. I was using a v1.9 client earlier and I just re-confirmed that a v1.9 client does fail with a v1.11 daemon.  So no need for any v1.10.3 fix for this.

**Comment by drewrobb** [comment] 2016-03-03 06:55
+1 for a 1.10.3 release with #19950/#20706 if possible. It is a very critical issue for us.

**Comment by duereg** [comment] 2016-03-04 00:56
+1 for a 1.10.3 release with #19950/#20706. Critical for us as well

**Comment by icecrime** [comment] 2016-03-04 03:38
I'm sorry but this is not how our release process works, and we unfortunately don't have the bandwidth to do a patch release so close to the next code freeze.

**Closed by icecrime** 2016-03-04 03:38 UTC

**Comment by stevenschlansker** [comment] 2016-03-04 19:11
How does the release process work then?  Clearly, multiple users are affected by a serious bug.  I'm sure there's 10x as many users affected than actually realize / bother to report it.

If we upgrade to 1.11.0 on release day, I'm sure we will discover yet more issues -- we just got bit hard with the 1.10 series (found bugs in every single one of 1.10.0, 1.10.1, 1.10.2) and I don't see why we should be any more confident about 1.11.0 :(

I respect that the Docker team has finite bandwidth to fix bugs, but I personally feel that if time is limited, the new features should be pushed back and critical bugs in existing features should take priority.  I suspect I'm not the only end user that feels that way -- a broken Docker is a serious problem.

**Comment by bjaglin** [comment] 2016-03-04 19:19
I hate to +1, but we are still stuck on 1.8.3 because of https://github.com/docker/docker/issues/18527, and it seems that the same situation repeats, so a patch release would be very welcome.

**Comment by icecrime** [comment] 2016-03-04 19:50
The amount of users of Docker implies that some amount of users at any point in time will always be affected by some amount of bugs. Trust me, I'd be very happy to ship more often, but we simply cannot afford to do so given how much energy it takes to follow the activity on this repository alone :disappointed:

The release process is described in [this document](https://github.com/docker/docker/blob/master/project/PATCH-RELEASES.md), in particular [this paragraph](https://github.com/docker/docker/blob/master/project/PATCH-RELEASES.md#deciding-if-a-patch-release-should-be-done) about the decision making for triggering a release.

Looking at the current issues on the [1.10.3 milestone](https://github.com/docker/docker/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A1.10.3+), nothing so far qualifies as a `P0`. **However**, this priority is established on maintainers best judgement, and as any other humans, we make mistakes :wink: So really, if you feel that one of these issues should be qualified as P0, please comment on them and we can reconsider.

Sounds good?

**Comment by stevenschlansker** [comment] 2016-03-04 19:56
In particular, there's no definition of what differentiates a P0 from P1 or lower...
We did comment on the issue, starting here: https://github.com/docker/docker/issues/19950#issuecomment-191723168

**Comment by AaronDMarasco-VSI** [comment] 2016-03-04 20:02
@stevenschlansker Also [above](https://github.com/docker/docker/issues/20874#issuecomment-191391603) I noted that #20706 is a pretty big deal.

**Comment by AaronDMarasco-VSI** [comment] 2016-03-09 15:50
Is there an open/updated version of this ticket now that #19550 is bumped to P0? My team is getting upset with the repeated "Jenkins is failing" emails they are getting...

**Comment by dsampath** [comment] 2016-03-14 21:19
I think this ticket needs closing. 
I assumed there wasn't a 1.10.3 until I saw this - https://github.com/docker/docker/releases/tag/v1.10.3

**Comment by vdemeester** [comment] 2016-03-14 21:25
@AaronDMarasco-VSI 1.10.3 has been released : https://github.com/docker/docker/releases/tag/v1.10.3

**Comment by AaronDMarasco-VSI** [comment] 2016-03-15 11:14
@vdemeester Yes, thanks, I installed it about an hour after the RPMs were up and had commented over on #19550. :+1:
