### ISSUE TITLE
reserving more than one IP address for container from docker0 bridge

### ISSUE THREAD

**Issue by dp-farm** [docker/docker#22257] opened 2016-04-22 16:43 UTC
Hi,

I am working on a container where there should be one management IP and one IP to manage data traffic. Is there any way I can get two IP addresses from docker from same bridge?

thanks
Devesh

**Comment by thaJeztah** [comment] 2016-04-25 09:23
hi @dp-farm, the issue tracker is for tracking bugs, and not a support forum, can you ask this question on either one of;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

I'll close this issue here, because this is not a bug report

**Closed by thaJeztah** 2016-04-25 09:23 UTC
Labels: group/networking, kind/question
