### ISSUE TITLE
[Packages] Ubuntu Xenial 1.13.0~rc3 package not in Packages file on repo

### ISSUE THREAD

**Issue by techninja1008** [docker/docker#29252] opened 2016-12-08 14:52 UTC
I won't use the the issue template as it isn't relevant.

To simply put it, 1.13.0~rc3 isn't showing up on my server configured for `ubuntu-xenial testing`, after an `apt update`. I can also confirm that it isn't in [https://apt.dockerproject.org/repo/dists/ubuntu-xenial/testing/binary-amd64/Packages](https://apt.dockerproject.org/repo/dists/ubuntu-xenial/testing/binary-amd64/Packages), however it *is* located in the pool at [https://apt.dockerproject.org/repo/pool/testing/d/docker-engine/docker-engine_1.13.0~rc3-0~ubuntu-xenial_amd64.deb](https://apt.dockerproject.org/repo/pool/testing/d/docker-engine/docker-engine_1.13.0~rc3-0~ubuntu-xenial_amd64.deb).

**Comment by liyaka** [comment] 2016-12-08 15:13
#29249

**Comment by thaJeztah** [comment] 2016-12-08 18:52
This is a duplicate of https://github.com/docker/docker/issues/29249 indeed, I'll close this one so that the discussion doesn't diverge

**Closed by thaJeztah** 2016-12-08 18:52 UTC
