### ISSUE TITLE
DNS resolution only with delay or timeout after a few hours

### ISSUE THREAD

**Issue by lennartjuette** [docker/docker#24604] opened 2016-07-13 22:04 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:36:47 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:36:47 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 26
 Running: 24
 Paused: 0
 Stopped: 2
Images: 230
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 657
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.844 GiB
Name: wopr
ID: FWZC:TPJX:T7XV:FPR2:GUBY:WM3D:ZX5L:FSG5:KGDV:SCGC:ASXW:G4ZG
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The host is running on a Virtual Server (VKM). Different containers are affected. The host itself has no problems

**Steps to reproduce the issue:**
1. start a container
2. wait a few hours
3. dig google.com

**Describe the results you received:**
Calling `dig google.com` takes multiple seconds or times out.

**Describe the results you expected:**
Calling `dig google.com` should return a result after a few ms.

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue occurs a few hours after starting the container.

/etc/resolv.conf of host:

```
domain yourvserver.net
search yourvserver.net
nameserver 46.38.225.230
nameserver 46.38.252.230
```

/etc/resolv.conf of conainer:

```
search yourvserver.net
nameserver 127.0.0.11
options ndots:0
```

**Comment by nathanleclaire** [comment] 2016-07-13 22:06
cc @mavenugo @mrjana

**Comment by mavenugo** [comment] 2016-07-13 22:28
@sanimej can you pls take a look at this along with the other DNS timeout issue ?

**Comment by lennartjuette** [comment] 2016-07-13 22:29
Here's a screenshot of some recorded query durations (in ms):
![stats](https://cloud.githubusercontent.com/assets/1701636/16821957/a7de9662-4959-11e6-8bf4-7fcd56230713.png)

I collected these numbers by running namebench (`namebench -q 8 -S -i /tmp/namebench.hosts -y 25`) with a fixed set of 8 hosts in namebench.hosts. This is repeaded every two minutes and recorded in an elasticsearch index. The drop at the right side of the graph can be explained by the container being recreated and restarted.

**Comment by sanimej** [comment] 2016-07-14 11:23
@lennartjuette This could be a duplicate of https://github.com/docker/docker/issues/22185. I haven't been able to recreate this issue though. Is your docker app DNS intensive ? When you see the DNS failures can you please capture the daemon logs (daemon should be running in debug mode, `-D flag`).

**Comment by lennartjuette** [comment] 2016-07-14 21:15
@sanimej There's an MTA (exim) + IMAP Server running in this container. But the traffic and the resulting DNS lookups are negligible - just a handful of lookups per minute. I haven't read all of #22185, but i guess i'm not hitting any rate limits here. I have enabled debug mode and i'm waiting for the next occurrence of the problem to gather some more logs.

I also updated the container (Ubuntu 14.04 > 16.04). Let's see if this helps a bit.

**Comment by lennartjuette** [comment] 2016-07-15 15:58
Everything is running fine since i enabled debug mode. Great... :-/

I created another container that only runs my namebench testscript periodically to reproduce the problem. It's using the same base image as my MTA container. There has been just one single occurrence of long DNS query times since i enabled debug mode.

FYI: When i did manual tests with dig before, while the problem was hitting my container, the tool it always showed very reasonable query times (0-10ms). That is despite the fact, that the real execution time was somewhere in the region of 15 seconds or more.

**Comment by lennartjuette** [comment] 2016-07-21 21:15
@sanimej : It took quite a while until the problem reappeared, but right now i'm experiencing delays. Here's a graph of my current situation. You can see the maximum response time for dns requests (excuted every minute, 25000ms timeout):
<img width="800" alt="screen shot 2016-07-21 at 23 07 49" src="https://cloud.githubusercontent.com/assets/1701636/17038895/20d5bd5e-4f98-11e6-83c3-99af77af84d6.png">

My docker debug log is filled up with dns requests and response events. Here's one, that took quite long (Look at lines 1+2 and the last line):

```
Jul 21 22:21:19 wopr docker[30122]: time="2016-07-21T22:21:19.370662337+02:00" level=debug msg="Query public.pyzor.org.[1] from 172.23.0.22:35233, forwarding to udp:46.38.225.230"
Jul 21 22:21:19 wopr docker[30122]: time="2016-07-21T22:21:19.370696110+02:00" level=debug msg="client dns id 38129, changed id 58098"
Jul 21 22:21:19 wopr docker[30122]: time="2016-07-21T22:21:19.370879945+02:00" level=debug msg="dns msg id 42778, client id 20703"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.365970710+02:00" level=debug msg="Query juette.eu.[28] from 172.21.0.4:58550, forwarding to udp:46.38.225.230"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.366005530+02:00" level=debug msg="client dns id 14125, changed id 38038"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.366214320+02:00" level=debug msg="Query juette.eu.[1] from 172.21.0.4:58550, forwarding to udp:46.38.225.230"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.366233518+02:00" level=debug msg="client dns id 13685, changed id 65153"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.366854912+02:00" level=debug msg="dns msg id 38038, client id 14125"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.367011595+02:00" level=debug msg="dns msg id 65153, client id 13685"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.440432237+02:00" level=debug msg="Query mailinator.com.[15] from 172.23.0.8:40647, forwarding to udp:46.38.225.230"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.440540450+02:00" level=debug msg="client dns id 42997, changed id 14382"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.446133484+02:00" level=debug msg="dns msg id 14382, client id 42997"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.446632661+02:00" level=debug msg="Query mail2.mailinator.com.[1] from 172.23.0.8:40647, forwarding to udp:46.38.225.230"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.446659558+02:00" level=debug msg="client dns id 33803, changed id 34337"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.452052253+02:00" level=debug msg="dns msg id 34337, client id 33803"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.452473948+02:00" level=debug msg="Query mail.mailinator.com.[1] from 172.23.0.8:40647, forwarding to udp:46.38.225.230"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.452497422+02:00" level=debug msg="client dns id 51493, changed id 22746"
Jul 21 22:21:23 wopr docker[30122]: time="2016-07-21T22:21:23.458800797+02:00" level=debug msg="dns msg id 22746, client id 51493"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.350679688+02:00" level=debug msg="Query juette.eu.[1] from 172.21.0.4:58550, forwarding to udp:46.38.225.230"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.350721165+02:00" level=debug msg="client dns id 23887, changed id 55127"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.351085197+02:00" level=debug msg="Query juette.eu.[28] from 172.21.0.4:58550, forwarding to udp:46.38.225.230"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.351115550+02:00" level=debug msg="client dns id 36040, changed id 11047"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.351567211+02:00" level=debug msg="dns msg id 55127, client id 23887"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.351895142+02:00" level=debug msg="dns msg id 11047, client id 36040"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.809389246+02:00" level=debug msg="Query juette.eu.[1] from 172.21.0.4:58550, forwarding to udp:46.38.225.230"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.809425439+02:00" level=debug msg="client dns id 9088, changed id 47478"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.810333583+02:00" level=debug msg="dns msg id 47478, client id 9088"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.811577844+02:00" level=debug msg="Query juette.eu.[1] from 172.21.0.4:58550, forwarding to udp:46.38.225.230"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.811620029+02:00" level=debug msg="client dns id 7427, changed id 65484"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.813665254+02:00" level=debug msg="Query juette.eu.[28] from 172.21.0.4:58550, forwarding to udp:46.38.225.230"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.813695063+02:00" level=debug msg="client dns id 41120, changed id 40435"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.813868041+02:00" level=debug msg="dns msg id 65484, client id 7427"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.814185072+02:00" level=debug msg="Query juette.eu.[28] from 172.21.0.4:58550, forwarding to udp:46.38.225.230"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.814224007+02:00" level=debug msg="client dns id 15868, changed id 17446"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.819107410+02:00" level=debug msg="dns msg id 40435, client id 41120"
Jul 21 22:21:24 wopr docker[30122]: time="2016-07-21T22:21:24.819321151+02:00" level=debug msg="dns msg id 17446, client id 15868"
Jul 21 22:21:26 wopr docker[30122]: time="2016-07-21T22:21:26.677555761+02:00" level=debug msg="Query www.cerstin-juette.de.[28] from 172.24.0.3:44830, forwarding to udp:46.38.225.230"
Jul 21 22:21:26 wopr docker[30122]: time="2016-07-21T22:21:26.677631997+02:00" level=debug msg="client dns id 17206, changed id 16826"
Jul 21 22:21:26 wopr docker[30122]: time="2016-07-21T22:21:26.678022879+02:00" level=debug msg="Query www.cerstin-juette.de.[1] from 172.24.0.3:44830, forwarding to udp:46.38.225.230"
Jul 21 22:21:26 wopr docker[30122]: time="2016-07-21T22:21:26.678066251+02:00" level=debug msg="client dns id 41474, changed id 62881"
Jul 21 22:21:26 wopr docker[30122]: time="2016-07-21T22:21:26.680889670+02:00" level=debug msg="dns msg id 16826, client id 17206"
Jul 21 22:21:26 wopr docker[30122]: time="2016-07-21T22:21:26.681183702+02:00" level=debug msg="dns msg id 62881, client id 41474"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.172554614+02:00" level=debug msg="Query jetpack.wordpress.com.[28] from 172.24.0.3:44830, forwarding to udp:46.38.225.230"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.172673247+02:00" level=debug msg="Query jetpack.wordpress.com.[1] from 172.24.0.3:44830, forwarding to udp:46.38.225.230"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.173608447+02:00" level=debug msg="client dns id 27638, changed id 34953"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.173840420+02:00" level=debug msg="client dns id 48106, changed id 62240"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.176400648+02:00" level=debug msg="dns msg id 34953, client id 27638"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.177998182+02:00" level=debug msg="dns msg id 62240, client id 48106"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.827788055+02:00" level=debug msg="Query pixel.wp.com.[28] from 172.24.0.3:44830, forwarding to udp:46.38.225.230"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.827823342+02:00" level=debug msg="client dns id 57261, changed id 21221"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.828478186+02:00" level=debug msg="dns msg id 21221, client id 57261"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.829788582+02:00" level=debug msg="Query pixel.wp.com.[1] from 172.24.0.3:44830, forwarding to udp:46.38.225.230"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.830172221+02:00" level=debug msg="client dns id 64837, changed id 59363"
Jul 21 22:21:27 wopr docker[30122]: time="2016-07-21T22:21:27.832242515+02:00" level=debug msg="dns msg id 59363, client id 64837"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.676964953+02:00" level=debug msg="Query 22.17.227.212.in-addr.arpa.[12] from 172.23.0.8:40647, forwarding to udp:46.38.225.230"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.676997571+02:00" level=debug msg="client dns id 64990, changed id 20609"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.678476046+02:00" level=debug msg="dns msg id 20609, client id 64990"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.678993252+02:00" level=debug msg="Query mout.gmx.net.[1] from 172.23.0.8:40647, forwarding to udp:46.38.225.230"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.679014379+02:00" level=debug msg="client dns id 40304, changed id 42822"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.680022609+02:00" level=debug msg="dns msg id 42822, client id 40304"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.780599613+02:00" level=debug msg="Query 22.17.227.212.bl.blocklist.de.[1] from 172.23.0.8:40647, forwarding to udp:46.38.225.230"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.780642058+02:00" level=debug msg="client dns id 33490, changed id 59691"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.785049857+02:00" level=debug msg="dns msg id 59691, client id 33490"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.785624958+02:00" level=debug msg="Query 22.17.227.212.zen.spamhaus.org.[1] from 172.23.0.8:40647, forwarding to udp:46.38.225.230"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.785666523+02:00" level=debug msg="client dns id 11093, changed id 27291"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.909008102+02:00" level=debug msg="dns msg id 27291, client id 11093"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.909800823+02:00" level=debug msg="Query 22.17.227.212.bl.spamcop.net.[1] from 172.23.0.8:40647, forwarding to udp:46.38.225.230"
Jul 21 22:21:36 wopr docker[30122]: time="2016-07-21T22:21:36.909839864+02:00" level=debug msg="client dns id 60996, changed id 19215"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.032508044+02:00" level=debug msg="dns msg id 19215, client id 60996"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.033463424+02:00" level=debug msg="Query 22.17.227.212.b.barracudacentral.org.[1] from 172.23.0.8:40647, forwarding to udp:46.38.225.230"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.033503720+02:00" level=debug msg="client dns id 17486, changed id 64561"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.149635193+02:00" level=debug msg="dns msg id 64561, client id 17486"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.150630600+02:00" level=debug msg="Query 22.17.227.212.spamrbl.imp.ch.[1] from 172.23.0.8:40647, forwarding to udp:46.38.225.230"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.150658857+02:00" level=debug msg="client dns id 39697, changed id 20775"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.164450639+02:00" level=debug msg="dns msg id 20775, client id 39697"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.165427472+02:00" level=debug msg="Query 22.17.227.212.ix.dnsbl.manitu.net.[1] from 172.23.0.8:40647, forwarding to udp:46.38.225.230"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.165461897+02:00" level=debug msg="client dns id 65221, changed id 4172"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.166478772+02:00" level=debug msg="dns msg id 4172, client id 65221"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.234993986+02:00" level=debug msg="Query posteo.de.multi.uribl.com.[1] from 172.23.0.22:35233, forwarding to udp:46.38.225.230"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.235025162+02:00" level=debug msg="client dns id 20591, changed id 9787"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.235209151+02:00" level=debug msg="dns msg id 36330, client id 20703"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.238530416+02:00" level=debug msg="Query posteo.de.multi.surbl.org.[1] from 172.23.0.22:35233, forwarding to udp:46.38.225.230"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.238553696+02:00" level=debug msg="client dns id 63913, changed id 47951"
Jul 21 22:21:37 wopr docker[30122]: time="2016-07-21T22:21:37.238718973+02:00" level=debug msg="dns msg id 58098, client id 38129"
```


Is there anything i should look for specifically?

**Comment by thaJeztah** [comment] 2016-07-24 11:14
@mavenugo @sanimej https://github.com/docker/docker/issues/23927 is most likely a duplicate, and may contain some information as well

**Comment by aleemb** [comment] 2016-07-24 16:38
It happens to me in production so I am in a bad spot. Happens randomly, like after a month or so. Recently I upgraded the host (14.04) and to docker v1.11.2. Since then the issue happens after a few minutes instead of a few weeks.

Some other issues suggests passing in the dns and so in my docker-compose I tried adding dns 8.8.8.8. However, the issue still persisted.

I suspect it might have to do with the rate limiter mentioned in some other issues. The reason I suspect this might be because my PHP app layer resolves a database service and once I added this to my `etc/hosts` the issues hasn't returned from other lookups. Just a guess.

**Comment by PierreF** [comment] 2016-09-07 14:43
If it's a duplicate of https://github.com/docker/docker/issues/22185#issuecomment-220508523, I found an easy way to reproduce (Docker 1.11.2):

Assuming the external DNS used by Docker is reachable though interface wlan0, run on host:
```
# tc qdisc add dev wlan0 root netem duplicate 100%
```

Do one dig in the container:
```
$ time dig google.fr
[...]
```

You could disable the tc rule on your host:
```
# tc qdisc del dev wlan0 root
```

Now expect the first run, dig in container is slow:
```
$ time dig google.fr
[...]
real    0m0.053s

$ time dig google.fr
[...]
real    0m5.019s
```

This does not occur with Docker 1.12.1

**Comment by timoreimann** [comment] 2016-12-14 14:12
@lennartjuette Have you been able to resolve the issue somehow?

**Comment by lennartjuette** [comment] 2016-12-14 14:22
I'm working on 1.12.3 currently without any problems. So no, i didn't actively resolve the problem but it went away at some point after upgrading.

**Comment by cpuguy83** [comment] 2016-12-14 15:08
Excellent I'm going to close this. I think this was related to response caching gone horribly wrong (and subsequently removed) in libnetwork.

If anyone has other issues on 1.12.4 or 1.13-rc please open a new issue.
Thanks!

**Closed by cpuguy83** 2016-12-14 15:08 UTC
Labels: area/networking, version/1.11

**Comment by sanimej** [comment] 2016-12-14 17:32
Just to clarify, embedded DNS doesn't cache the responses. But in 1.11 the UDP socket to the external servers were getting reused across multiple queries which somehow led to this issue and it has been removed in 1.12
