### ISSUE TITLE
Docker image prune misses some dangling images

### ISSUE THREAD

**Issue by kkeane** [docker/docker#30583] opened 2017-01-31 07:42 UTC
**Description**
In Docker 1.13.0, 
```
docker image prune
```
will miss images that
```
docker images -f dangling=true
```
will list. I would expect that both commands should affect the same images.

**Steps to reproduce the issue:**

1. Build a number of images from dockerfiles.
2. Make a change to a dockerfile to ensure the image will be rebuilt
3. Build the images again.
4. You should now have one, or a few, images with the repository/tag <none>:<none>
5. Run docker images -f dangling=true
6. Note which images are listed.
7. Run docker image prune -f
8. Note which images where deleted
9. Run docker image prune -f again. This should report 0B deleted.
10. Run docker images -f dangling=true again

**Expected Result**
docker image prune -f should report that some images were deleted.
No images should be returned in step 10

**Actual Result**
Sometimes - not always - docker images -f dangling=true will still list some images that docker image prune missed.

**Additional information you deem important (e.g. issue happens only occasionally):**
I am not sure exactly how to reproduce the issue, although I did notice a pattern. The above steps are based on that pattern, but I am not sure if this is the only scenario.

I also have a feeling, although I am not certain, that docker image prune will find all but one such images if there are multiple. However, I have also seen docker image prune miss two dangling images, so this is not quite consistent.

Sorry about being so vague.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 147
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-253:2-4759149-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.905 GB
 Data Space Total: 107.4 GB
 Data Space Available: 47.6 GB
 Metadata Space Used: 11.4 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.548 GiB
Name: <redacted>
ID: WYRM:QCVN:CJYN:JTFA:Q44S:4L3V:FDFM:Z3YS:47EE:2T23:SUS5:KEA3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical system. This is a development workstation, not a production system.

**Comment by rheinwein** [comment] 2017-02-03 10:31
Hi @kkeane -- I'm unable to reproduce this issue on Docker 1.13. Could you run through steps again, and then include the output of these commands in this issue?

Here's `docker image prune` working as expected with 1.13.0. I get the same results with `docker image prune -f` as you noted in the issue.

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
prune-test          latest              471595e59ad8        20 seconds ago      1.11 MB
<none>              <none>              4ccaee738b80        30 seconds ago      1.11 MB
<none>              <none>              72c81e6c6d45        40 seconds ago      1.11 MB
<none>              <none>              73ecd2b29912        58 seconds ago      1.11 MB
busybox             latest              7968321274dc        2 weeks ago         1.11 MB
$ docker images -f dangling=true
REPOSITORY          TAG                 IMAGE ID            CREATED              SIZE
<none>              <none>              4ccaee738b80        35 seconds ago       1.11 MB
<none>              <none>              72c81e6c6d45        45 seconds ago       1.11 MB
<none>              <none>              73ecd2b29912        About a minute ago   1.11 MB
$ docker image prune
WARNING! This will remove all dangling images.
Are you sure you want to continue? [y/N] y
Deleted Images:
deleted: sha256:4ccaee738b807cf92c8f6ce65f80a2571afacee27a20e273580e94c968c83073
deleted: sha256:73ecd2b29912697ae06371b8cddc25498e98bd7414b011cb82605c6827472762
deleted: sha256:72c81e6c6d45456231e00c04e62dd036d934d2d457867be84eb27dbf90c6a744

Total reclaimed space: 0 B
$ docker images -f dangling=true
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
prune-test          latest              471595e59ad8        43 seconds ago      1.11 MB
busybox             latest              7968321274dc        2 weeks ago         1.11 MB
```

**Comment by kkeane** [comment] 2017-02-03 10:59
I wish I knew exactly how to reproduce it. I have built and re-built quite a few images today, and made a point of using docker image prune to see when this issue happened. Unfortunately, today it always worked reliably. One difference is that a few days ago, after reporting the issue, I did a "docker image prune -a" so now I have a very clean store.

Bottom line, I don't know how to reproduce this.

I will add to this issue if I see it happening again and know more.

Sorry for sending you on a wild goose chase!

**Comment by rheinwein** [comment] 2017-02-03 11:11
Thanks! I'll close this issue for now. If you do see this behavior again and can reproduce reliably, feel free to reopen.

**Closed by rheinwein** 2017-02-03 11:11 UTC
Labels: area/runtime, status/more-info-needed, version/1.13

**Comment by tianon** [comment] 2017-02-03 23:08
Sounds like this was probably a similar issue to https://github.com/docker/docker/issues/30307, and thus fixed by https://github.com/docker/docker/pull/30330. :smile: :+1:

**Comment by kkeane** [comment] 2017-02-05 22:04
I just saw it happen again, and it indeed seems to be the same as #30307 .

After rebuilding an image, the old one was tagged with repositoryname:<none>. docker image prune missed this image but docker images -f dangling=true found it as dangling.
