### ISSUE TITLE
Add "Managed by docker" comment to all iptables rules

### ISSUE THREAD

**Issue by anderskvist** [docker/docker#28880] opened 2016-11-28 13:32 UTC
I'm currently using docker in a puppet environment, where puppet handles all firewall-rules and this conflicts with docker generating it's own firewall rules. Puppet can handle this by adding an ignore list for which rules NOT to purge from the different chains - but it's very hard to identify the rules created by docker from puppet. But adding a comment saying "Managed by docker", will make this a piece of cake.

I've created this untested patch - hopefully it will inspire someone with the ability to test and run docker from source to create this feature :)

```
diff --git a/vendor/github.com/docker/libnetwork/iptables/iptables.go b/vendor/github.com/docker/libnetwork/iptables/iptables.go
index 3884257..e9422b5 100644
--- a/vendor/github.com/docker/libnetwork/iptables/iptables.go
+++ b/vendor/github.com/docker/libnetwork/iptables/iptables.go
@@ -281,6 +281,7 @@ func (c *ChainInfo) Link(action Action, ip1, ip2 net.IP, port int, proto string,
 // rule is not already present in the chain. Reciprocally,
 // it removes the rule only if present.
 func ProgramRule(table Table, chain string, action Action, args []string) error {
+       args = append(args, "-m comment --comment 'Managed by docker'")
        if Exists(table, chain, args...) != (action == Delete) {
                return nil
        }
```

It may be best to add it as an option to docker, so it will be 100% backward compatible and up to the user to use it.

**Comment by thaJeztah** [comment] 2016-11-28 13:40
Some prior discussion on this; https://github.com/docker/docker/pull/12437#issuecomment-93854813

**Comment by thaJeztah** [comment] 2016-11-28 13:41
note that this is a change in libnetwork, so possibly best to be discussed there (https://github.com/docker/libnetwork) /cc @aboch

**Comment by aboch** [comment] 2016-11-28 16:32
A PR for the same reason was pushed to libnetwork (https://github.com/docker/libnetwork/pull/1096) but there were concerns about failures to check the rule existence on system with old iptables which do not support the `-C` option. One option is to not add the comments on those systems. Will review again.

**Comment by thaJeztah** [comment] 2016-11-28 16:50
Ah, thanks! I thought there was an issue already. Looks like this is a duplicate of https://github.com/docker/docker/issues/18908

@anderskvist I'll close this issue, because it's a duplicate of https://github.com/docker/docker/issues/18908, so please subscribe to that issue / continue the conversation over there

**Closed by thaJeztah** 2016-11-28 16:50 UTC
Labels: area/networking, kind/enhancement
