### ISSUE TITLE
Assign IP statically or via DHCP to a container 

### ISSUE THREAD

**Issue by smkkannan** [docker/docker#4952] opened 2014-04-01 10:29 UTC
We have our own ISC DHCP server for corporate and our network has multiple VLANs. 
Our users are using docker to create containers. The containers are assigned with non routing private IPs provided by the docker running in each user machine. 
Now the problem is, these IPs are not reachable from other machines in our network. 

         We want the IPs to be assigned only by our own corporate DHCP server. All the DHCP broadcast request from docker needs to be addressed by our DHCP RELAY agent. 

     Already we are using ethernet as bridge mode. So, this doesn't help. 

  In simple,  How to make containers to get IP from external DHCP running in the LAN. 

Regards,
Kamal

**Comment by yeasy** [comment] 2015-01-11 08:45
Seems the only way today, is still to assign static IP manually by creating veth pair, or reconfig the container after it's booted.

**Comment by brpaz** [comment] 2015-02-08 22:47
+1

**Comment by Kokonoe** [comment] 2015-02-08 23:16
+1

**Comment by jfrazelle** [comment] 2015-02-26 00:54
closing as duplicate of https://github.com/docker/docker/issues/6743

**Closed by jfrazelle** 2015-02-26 00:54 UTC
Labels: /system/networking

**Comment by dikerboyz** [comment] 2015-05-27 11:04
Hi, could you tell me how to use pipework to assign docker container IP Address?

**Comment by aanm** [comment] 2015-05-29 15:20
@dikerboyz There's a good explanation in https://github.com/jpetazzo/pipework

**Comment by huwei88** [comment] 2015-09-17 05:26
I want to know the workflow of docker ip allocation.
Someone can help give me a doc or link about how docker or libcontainer assign ip address to container? 
Thanks.

**Comment by thaJeztah** [comment] 2015-10-07 14:22
@huwei88 I think you'll have to look in the libnetwork repo for that, e.g, [docker/libnetwork/ipallocator/](https://github.com/docker/libnetwork/blob/dbe6172d8ca9faf1cd37d0864d4ac09895804a98/ipallocator/allocator.go)

Work is in progress to make the IPAM pluggable, see https://github.com/docker/libnetwork/issues/489, and a PoC DHCP driver;  https://github.com/erikh/dhcpd

**Comment by pdxjohnny** [comment] 2015-10-07 20:05
+1 for dhcp

**Comment by huwei88** [comment] 2015-10-09 09:45
@thaJeztah, thanks. I'll appreciate that if you can give me another doc or link about how the container get ip address, e.g. by dhcpclient? or write the configurations into network configuration files(e.g. interfaces).

Thanks.

**Comment by thaJeztah** [comment] 2015-10-09 10:19
@huwei88 it's probably better to ask those questions to @mrjana or @mavenugo. You can try asking in the #docker-network or #docker-dev IRC channel, or the [docker-dev](https://groups.google.com/forum/#!forum/docker-dev) Google Group

**Comment by huwei88** [comment] 2015-10-09 10:22
Yeah. Thanks. I'll have a try in docker-dev google groups. :)

**Comment by mavenugo** [comment] 2015-10-14 03:55
@huwei88 @pdxjohnny, others, #16910 brings in pluggable IPAM to docker containers. We have a simple built-in ipam driver that comes out of the box in docker that behaves similar to the ipallocator today. But much more flexible to work across various network plugins.

But, if you are interested in DHCP, one can write a simple DHCP plugin which can interact with the dhcp server and assign ip-addresses to the containers. 
Pls refer to the IPAM API reference : https://github.com/docker/libnetwork/blob/master/docs/ipam.md that can be used by plugin developers.

**Comment by pdxjohnny** [comment] 2015-10-14 15:45
Sweet I'll try that out

**Comment by Hostile** [comment] 2016-03-11 14:36
any update ?

**Comment by pdxjohnny** [comment] 2016-03-11 14:40
https://blog.jessfraz.com/post/ips-for-all-the-things/ pretty sure this is similar

**Comment by shenliuyang** [comment] 2017-03-17 03:21
+n
