### ISSUE TITLE
Docker stats showing container names (optionally?)

### ISSUE THREAD

**Issue by aanisimov** [docker/docker#22246] opened 2016-04-22 08:48 UTC
What do you think of adding _container name_ to the output of docker stats command?

Adding a container name could be more informative to user and there will be no need to use workarounds like:
```
docker stats $(docker ps | awk '{if(NR>1) print $NF}')
```

```
docker --version
Docker version 1.11.0, build 4dc5990
```

**Comment by cpuguy83** [comment] 2016-04-22 13:34
I think there's an open issue to add a `--format` to `docker stats` specifically for this.

**Comment by thaJeztah** [comment] 2016-04-25 18:54
Looks like a duplicate of https://github.com/docker/docker/issues/20973, so I'll close this one

**Closed by thaJeztah** 2016-04-25 18:54 UTC

**Comment by faunus** [comment] 2017-07-26 04:53
docker ps | awk '{if(NR>1) print $NF}' | xargs docker stats

**Comment by thaJeztah** [comment] 2017-09-28 19:25
I opened a new PR for changing the default format to show `CONTAINER ID` (truncated) and `NAME` by default, and add a `--no-trunc` flag to docker stats. The PR was just merged, so will be in an upcoming Docker release (17.10 or 17.11); https://github.com/docker/cli/pull/565
