### ISSUE TITLE
Containers are created with ExitCode=0

### ISSUE THREAD

**Issue by dpgeekzero** [docker/docker#21186] opened 2016-03-14 14:51 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 80
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-8:2-25297148-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.483 GB
 Data Space Total: 107.4 GB
 Data Space Available: 98.89 GB
 Metadata Space Used: 13.79 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.134 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.119 (2016-03-04)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.58 GiB
Name: dougdev
ID: TOIW:WU7N:I7X2:5S5R:Y6UF:QEUV:LQLL:HIZN:W5CR:NN6K:7644:7AXP

```

**Steps to reproduce the issue:**
1. docker create --name test debian
2. docker ps -a --filter exited=0

**Describe the results you received:**

The newly created container is in the list

**Describe the results you expected:**

The newly created container should not be in the list.
The ExitCode attribute of a newly created container should be NULL.

**Comment by dpgeekzero** [comment] 2016-03-14 14:53
This caused an issue in our environment where our cleanup job which is designed to delete old, exited containers would occasionally delete a container between it's **create** & and **start** events.

**Comment by thaJeztah** [comment] 2016-03-14 15:05
ping @calavera possibly due to changes in engine-api?

**Comment by HackToday** [comment] 2016-03-15 00:09
It seems it existed in 1.9.0~  ,

if you use `docker inspect <container>` the ExitCode is 0, not sure if it was by design or old bug :)

**Comment by cpuguy83** [comment] 2016-03-15 00:14
I'd consider this a bug, personally.
We should set ExitCode with a pointer instead of an int so it can be nil.
There was a similar issue with Execs.

**Comment by AndrewGuenther** [comment] 2016-03-21 18:56
I agree with @cpuguy83

dibs

**Comment by HackToday** [comment] 2016-03-22 00:49
@AndrewGuenther  FYI, you should use `#dibs`

**Comment by AndrewGuenther** [comment] 2016-03-22 01:01
@HackToday, I knew I was forgetting something

**Comment by vieux** [comment] 2016-04-06 18:37
@AndrewGuenther are you still working on this one ?

**Comment by AndrewGuenther** [comment] 2016-04-06 20:49
@vieux I haven't gotten around to it unfortunately. I can re-dibs later if no one grabs it and you want to take me off.

**Comment by boynux** [comment] 2016-04-10 13:59
@vieux, @AndrewGuenther I tried to see how much effort needed to change ExitStatus to pointer instead of int. And it seems to be a lot of changes in multiple files. If you think that's the way to go I can probably do it. Otherwise I suggest another approach (with less impact) if there is any.

**Comment by AndrewGuenther** [comment] 2016-04-11 16:49
@boynux Changing it to a pointer is the correct fix. Anything with less impact would likely just be a workaround.

**Comment by boynux** [comment] 2016-04-11 16:56
@AndrewGuenther if you are busy I can have a look into that. And probably fix it.

**Comment by AndrewGuenther** [comment] 2016-04-11 17:04
@boynux All yours!

**Comment by boynux** [comment] 2016-04-11 21:59
@vieux I decided to do a targeted change instead of going for a broader change since I realized that the change will be unnecessarily large for this small issue. The other problem with the pointer approach is that it will be inconsistent with current State struct since it only uses non-pointer fields.

**Comment by AndrewGuenther** [comment] 2016-04-11 22:21
> the change will be unnecessarily large for this small issue

For **this** issue. But this is only a symptom. You're not fixing the root cause which is that a container which has not been started should not have an exit code.

**Comment by boynux** [comment] 2016-04-12 04:26
@AndrewGuenther that's right, I understand that this might be the case, but looking at the code there are at least two more parameters that comes with `ExitCode` to identify the container state. They are `Running` and `StartedAt`. In `State` struct `String` method reports different container state by utilizing those parameters.

For instance if the state is created it checks `StartedAt` field to `0` and that's the pattern I exactly followed. Although I clearly understand your point and it totally makes sense, I'm not sure whether I should introduce such a big change to several parts of the code to solve this issue or not. Since I could address this problem by changing only one line of the code.

I prefer to have someone else's comment on this too, just to make sure your proposed change is desired as I'm not really into docker way of changing the code. :)

**Closed** 2016-05-04 13:21 UTC
Labels: kind/bug, status/claimed
