### ISSUE TITLE
Expose service information in log context

### ISSUE THREAD

**Issue by omallo** [docker/docker#27065] opened 2016-09-30 11:26 UTC
Right now, the [logging context](https://github.com/docker/docker/blob/master/daemon/logger/context.go) includes information about the container like its name and ID. It would be nice if information regarding Swarm services would also be exposed.

Docker already sets the following container labels which make the service information available:
- "com.docker.swarm.service.name"
- "com.docker.swarm.service.id"

Having e.g. the service name available is handy for log analysis purposes since it allows you to group the logs of all containers belonging to the same service without having to rely on the image name.

**Comment by thaJeztah** [comment] 2016-09-30 12:31
Thanks for opening this issue; I think this is a duplicate of https://github.com/docker/docker/issues/26808 (although that is about "journald", the discussion on that issue is more "in general"; the last comment may be relevant here; https://github.com/docker/docker/issues/26808#issuecomment-250033796

I'll close this issue, as I think https://github.com/docker/docker/issues/26808 is already tracking this, but feel free to comment

**Closed by thaJeztah** 2016-09-30 12:31 UTC
Labels: area/logging, kind/enhancement

**Comment by omallo** [comment] 2016-09-30 13:03
@thaJeztah , you're totally right, it looks like I haven't searched for existing issues good enough. Thanks for pointing this out.
