### ISSUE TITLE
daemon crashing on invalid ports directive

### ISSUE THREAD

**Issue by spacediver** [docker/docker#14621] opened 2015-07-14 10:23 UTC
Hi folks,

Consider the following docker-compose.yml

    test:
        image: spacediver/python
        ports:
          - "127.0.0.180:80"

Notice the error in ports, originally I meant  to say "127.0.0.1:80:80"

Trying to start it we may see (with docker 1.7.0, docker-compose 1.3.0) this:

    root@17934123d4d1:~# docker-compose up                 
    Creating root_test_1...
    Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
    
Why would this happen? 

Running docker with -D reveals (http://pastebin.com/caDWGW8Q) that there's an exception in daemon that happens at parsing invalid ports directive ("127.0.0.180:80")

Trying to run the same with docker CLI would validate ports directive well before sending to daemon:

    root@17934123d4d1:~# docker run --rm -ti -p 127.0.0.180:80 spacediver/python 
    docker: Invalid hostPort: 127.0.0.180.
    See 'docker run --help'.

Should the daemon check input data and do not crash on parsing error?

Here is my environment information: http://pastebin.com/3LaAh4YT

**Comment by spacediver** [comment] 2015-07-14 10:29
Just confirmed this with docker-experimental (git commit 15f9766)

**Comment by runcom** [comment] 2015-07-14 10:33
cause is https://github.com/docker/docker/blob/master/pkg/nat/nat.go#L60 we should refactor that and I recall some pr about this as well

**Comment by thaJeztah** [comment] 2015-07-14 10:43
I think this is the PR you are refering to: https://github.com/docker/docker/pull/14231 and that is cherry-picked into 1.7.1

@spacediver could you test this with 1.7.1-rc3 and see if you're still able to reproduce? You can find 1.7.1-rc3 here: https://github.com/docker/docker/pull/14264#issuecomment-120132694

**Comment by runcom** [comment] 2015-07-14 18:10
#14231 indeed fixed this issue in parsing PortBindings. Also that patch should go in 1.7.1 so should be really soon and you can grab to test the latest rc here https://github.com/docker/docker/pull/14264#issuecomment-120132694 (as @thaJeztah suggested :))

**Comment by thaJeztah** [comment] 2015-07-14 18:36
Thanks @runcom, I was a bit confused by you earlier comment and thought there was still an issue remaining on master.

I'll close this issue, because this should be resolved, but feel free to ping me if you're still able to reproduce this on 1.7.1 (or a recent experimental build)

Thanks for reporting, @spacediver !

**Comment by spacediver** [comment] 2015-07-14 22:58
I've reproduced it at 1.7.1-rc3, with the very same result.

**Comment by thaJeztah** [comment] 2015-07-14 23:12
Thanks @spacediver I'll reopen.

Just to be sure; did you remove the old container and created a new one after updating docker?

**Comment by spacediver** [comment] 2015-07-14 23:55
Yep. Just re-checked it with no containers, see transcript and log: http://pastebin.com/raw.php?i=Qh6tYMjD

**Comment by duglin** [comment] 2015-07-15 00:06
@spacediver what's the best way to reproduce this w/o using compose?

**Comment by spacediver** [comment] 2015-07-15 00:20
Here is docker-compose --verbose output, it might help to reconstruct direct requests (you can see jsons dumped in python format). http://pastebin.com/raw.php?i=vEmrp0jv

It may be seen that container gets created with wrong port binding, and then crashes on starting.

**Comment by duglin** [comment] 2015-07-15 21:13
#dibs

**Closed** 2015-07-21 22:48 UTC
Labels: kind/bug, status/claimed
