### ISSUE TITLE
docker  host network model cause command "su" execute problem in container

### ISSUE THREAD

**Issue by hanwoody** [docker/docker#5899] opened 2014-05-19 02:31 UTC
When I run with ubuntu 14.04 or centos 6.4,
docker run -it  --net=host -v /dev:/dev ubuntu:latest /bin/bash     or
docker run -it --net=host centos:6.4 /bin/bash

 then attach into container, execute su - user -s /bin/sh ....., system throw error like the following:
System error 
detailed log in /var/log/syslog  (in hostOS):
May 18 07:53:44 i-ikneuftx su[10]: PAM audit_log_acct_message() failed: Operation not permitted 
May 18 07:53:44 i-ikneuftx su[10]: pam_authenticate: System error 
May 18 07:53:44 i-ikneuftx su[10]: FAILED su for root by root May 18 07:53:44 i-ikneuftx su[10]: - /dev/pts/9 root:root

Many linux scripts contain "su" to run some service in non root user, such as initscript of  mysql5.6 in ubuntu:
su - mysql -s /bin/sh -c "/usr/bin/mysqld_safe > /dev/null 2>&1 &"

When I run docker in bridged network, all are OK.

I think this is bug of docker host network

**Comment by belogrudov** [comment] 2015-04-21 11:34
sudo also fails for the same reason:
# sudo bash
sudo: unable to send audit message: Operation not permitted

**Comment by MichaelDrogalis** [comment] 2015-08-13 00:54
Hit this one. Incredibly frustrating to work through. Any status here?

**Comment by md5** [comment] 2015-08-14 05:24
@MichaelDrogalis Using `--net host` is seldom the right solution. I don't think it makes much sense at all unless you're containerizing a network analysis tool, in which case it should probably run as `root`. If not, you may want to look at changing the process user with `gosu` or `chpst` instead of `su`. You're better off trying to figure out a better way to solve your problem.

**Comment by MichaelDrogalis** [comment] 2015-08-14 14:32
@md5 To be fair, it doesn't make sense to support a feature, have it be broken, then say not to use it when the bug is reported. :) Sometimes I do want to turn off the network stack for higher performance.

**Comment by MichaelDrogalis** [comment] 2015-08-14 14:37
Also FYI, I ran into this using while someone else's Docker image. Sometimes the problem is out of your hands. :/

**Comment by mbert** [comment] 2015-08-14 14:38
For what I do ``--net host'' is just right. I get my services available on a known address. If I run more than one service on the same host, they can all talk to each other via localhost. I don't waste performance. Of course, I need to keep track of ports used on my host again, but that's more than worth it.

**Comment by cpuguy83** [comment] 2015-08-14 14:55
@MichaelDrogalis It's hardly broken.
This is 100% a host-level issue.
Note that this works just fine on boot2docker.

Being that setting `--privileged` does not seem to fix it, it would seem that AppArmor is not likely the cause here either.
Doing `--pid=host` does work in this case and indeed seems to fit the issue mentioned by the referenced sequenceiq post above.

If you are using `--net=host` purely for performance reasons, it may be good to look at alternative solutions (e.g., macvlan) and see if they fit the bill.
@mbert You can also do `--net=container:<name>` to get exactly what you describe (except host-level performance for external things, and in such cases, see above).

I am inclined to close this as this does not appear to be something that Docker can fix, other than adding some updated documentation around it.

**Comment by MichaelDrogalis** [comment] 2015-08-14 15:01
@cpuguy83 That's fine -- to most people, myself included, it's not obvious where the problem is because of how confusing the issue is. When I drop in here and see that there's a big, long open ticket against Docker describing the same problem, it makes me think there's still work to be done here. Thanks for the explanation.

**Comment by liviubalan** [comment] 2015-12-04 14:09
If you want learn how to switch to another user on Ubuntu using the su command you can checkout <a href="http://www.liviubalan.com/switch-user-on-ubuntu-using-su-command">Switch user on Ubuntu using su command (video tutorial)</a>.

**Comment by lphuberdeau** [comment] 2016-02-12 15:55
cap_add: AUDIT_WRITE solves the issue

**Comment by conradkleinespel** [comment] 2016-03-10 14:30
@lphuberdeau : Thanks a lot ! :+1:  I also found `pid: host` to fix the issue as explained in other issues above.

**Comment by michaeljs1990** [comment] 2016-04-22 17:49
@lphuberdeau can you post an example of the command you are using. I tried what you said and im still getting the same issue on ubuntu 14.04 host. 

```
docker run --privileged=true --cap-add=AUDIT_WRITE --net=host core
```

**Comment by icecrime** [comment] 2016-09-10 00:37
I'm closing this issue as it appears it's not a Docker issue per-se. Thanks all!

**Closed by icecrime** 2016-09-10 00:37 UTC
Labels: exp/expert, kind/bug

**Comment by sebmoule** [comment] 2016-09-10 12:33
Hi all, on my side I fix the issue by upgrading my old 3.13 kernel to a recent one 4.4. No pb further

**Comment by joequery** [comment] 2017-10-20 20:18
@allamand 's recommendation worked for me. On ubuntu I upgraded my kernel via

```
$ sudo apt-get install linux-generic-lts-xenial
```

followed by a restart.

**Comment by BinitaBharati** [comment] 2018-05-25 11:36
su command will work if you use Ubuntu Xenial instead of Trusty. I faced the same issue, and the eror went away, once I upgraded my Ubuntu version to Xenial.
