### ISSUE TITLE
Why  log json-file driver not have tag option??

### ISSUE THREAD

**Issue by yeruisen** [docker/docker#28544] opened 2016-11-17 07:44 UTC

**Comment by cpuguy83** [comment] 2016-11-17 15:15
Because nobody has asked for it or coded it up?

**Comment by ripcurld00d** [comment] 2016-11-17 18:57
#dibs

**Comment by thaJeztah** [comment] 2016-11-17 18:59
@yeruisen @ripcurld00d this is a duplicate of https://github.com/docker/docker/issues/19803, so let's use that one for tracking

**Closed by thaJeztah** 2016-11-17 18:59 UTC
Labels: area/logging, kind/enhancement
