### ISSUE TITLE
 Error: Start container failed: Cannot start container [containerID]: [8] System error: exchange full

### ISSUE THREAD

**Issue by anandkumarpatel** [docker/docker#14718] opened 2015-07-17 22:47 UTC
after 2 days and creating/destroying of ~11,000 containers I see 
```
 Error: Start container failed: Cannot start container [containerID]: [8] System error: exchange full
```
based on ifconfig I have 1044 veth interfaces. I know only 1024 interfaces are allowed, however I only have 30 containers running and 132 containers total. For some reason docker is not cleaning up veth interfaces. 

let me know if there is any additional data that would be helpful.
```
root@articuno:/home/ubuntu# docker -D info
Containers: 126
Images: 2430
Storage Driver: aufs
 Root Dir: /docker/aufs
 Backing Filesystem: extfs
 Dirs: 2682
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 32
Total Memory: 58.81 GiB
Name: articuno
ID: AAAA:RRRR:TTTT:IIII:CCCC:UUUU:NNNN:OOOO:RAB4:NIZW:DOA7:RNUL
Debug mode (server): false
Debug mode (client): true
Fds: 7170
Goroutines: 38744
System Time: Fri Jul 17 22:32:56 UTC 2015
EventsListeners: 1
Init SHA1: 7f9c6798b022e64f04d1aff8c75cbf38a2779493
Init Path: /usr/bin/docker
Docker Root Dir: /docker
WARNING: No swap limit support
```
```
root@articuno:/home/ubuntu# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```
```
root@articuno:/home/ubuntu# uname -a
Linux articuno 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
AWS EC2 box

How reproducible:
not very, saw it once after 2 days and once after 11 days

Steps to Reproduce:
1. create/start/remove 1000's of containers

Actual Results:
```
 Error: Start container failed: Cannot start container [containerID]: [8] System error: exchange full
```

Expected Results:
container just starts fine

Additional info:
based on ifconfig I have 1044 veth interfaces. I know only 1024 interfaces are allowed, however I only have 30 containers running and 132 containers total. For some reason docker is not cleaning up veth interfaces.

**Comment by anandkumarpatel** [comment] 2015-07-29 02:07
just saw this again, what other information can I provide?

**Comment by anandkumarpatel** [comment] 2015-07-29 02:33
referencing similar issue here https://github.com/docker/docker/issues/1320

**Comment by thaJeztah** [comment] 2015-08-09 22:44
ping @mrjana @mavenugo is this a libnetwork issue?  And something being worked on?

**Comment by mavenugo** [comment] 2015-08-10 01:22
@thaJeztah @anandkumarpatel libnetwork didnt get integrated with docker till 1.7.0. Since this issue is seen in 1.6.2, it is certainly not related to libnetwork. Having said that, we had also seen a few veth leak cases in 1.7.x releases and we have resolved a few in 1.8.0 RC images. Please give it a try and give feedback.

**Comment by thaJeztah** [comment] 2015-08-10 06:10
umf late night, sorry, @mavenugo

**Comment by vlerenc** [comment] 2015-10-02 09:49
I hit the same issue. After creating and deleting hundreds of containers, I ran into:
```
Error response from daemon: Cannot start container 32b5cd641aaf47ed487adb3fda71ce6eb743b686333ec337c6d8643555dda5ee: adding interface veth302f259 to bridge docker0 failed: exchange full".
```

I was using:
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

`ifconfig | grep veth | wc -l` returns `1023` (not sure why not 1024, but anyway) although I have only a few containers running. Docker daemon process restart doesn't help.

When I `watch` `docker ps --all | wc -l && ip link ls | wc -l && ifconfig | grep veth | wc -l` while I delete a container, I see:
```
e.g. 12->11
2052 (doesn't change anymore)
1023 (doesn't change anymore)
```
As said, also after process restart of the Docker daemon the second and third numbers remain the same, bridges are not collected with Docker version 1.8.1.

**Comment by vlerenc** [comment] 2015-10-02 11:00
Addendum: I restarted the machine and everything was OK again. Then I created and deleted a single container and the network bridges behaved normally, i.e. after removal of the container I immediately saw one bridge less, so now I am wondering whether a failure in creation (when I reached the limit in the load test and continuously tried to create new containers which failed) doesn't properly clean up resources that were created in the process?

**Comment by mrjana** [comment] 2015-10-02 15:45
@vlerenc Can you please upgrade to 1.8.2 which has some very important fixes for networking?

**Comment by vlerenc** [comment] 2015-10-05 13:13
Great, the same test now works with 1.8.2. I can create up to 1024 containers, run into the same "exchange is full" error (as expected), can delete one container and create a new one again/instead. That test wasn't working before. Thank you!

**Comment by thaJeztah** [comment] 2015-10-05 13:31
Thanks @vlerenc, good to hear it's resolved for you.

@anandkumarpatel have you been able to test this on 1.8.2? Docker 1.6.2 is quite an old version and will not get patch-updates.

**Comment by anandkumarpatel** [comment] 2015-10-08 16:52
Will be a while before I can test out 1.8.2. I am ok with closing this
issue since @vlerenc <https://github.com/vlerenc> has verified it working.

**Comment by thaJeztah** [comment] 2015-10-08 19:03
Thanks @anandkumarpatel, I'll close this, but comment here if you're still able to reproduce in 1.8.x

**Closed by thaJeztah** 2015-10-08 19:03 UTC
Labels: group/networking, status/more-info-needed

**Comment by ismareth** [comment] 2016-07-21 18:38
Hi, 
how can i check the number of containers running when i am logged into the Kubernetes-minion node on aws : 
admin@ip-172-20-0-19:~$  ifconfig | grep veth | wc -l
-bash: ifconfig: command not found

admin@ip-172-20-0-19:~$ uname -a
Linux ip-172-20-0-19 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux

Thanks.

**Comment by thaJeztah** [comment] 2016-07-21 18:40
@ismareth this is not the right place to ask that question, forums.docker.com, or the #docker IRC channel are better for that

**Comment by ismareth** [comment] 2016-07-21 18:41
Thanks @thaJeztah , will do that
