### ISSUE TITLE
Fails to install on Debian testing/unstable

### ISSUE THREAD

**Issue by ndarilek** [docker/docker#15136] opened 2015-07-29 20:44 UTC
A stock Debian stable install works, though lacks some kernel features. So I tried switching to testing/unstable.

On a stock Debian install with nothing done other than:

```
s/stable/testing/g /etc/apt/sources.list
apt-get update
apt-get dist-upgrade -y
shutdown -r now
apt-get install -y curl
curl https://get.docker.com |sh
```

I get:

+ sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
Hit http://ftp.us.debian.org stretch InRelease
Get:1 http://ftp.us.debian.org stretch/main amd64 Packages/DiffIndex [7876 B]
Get:2 https://apt.dockerproject.org debian- InRelease [162 B]
Ign https://apt.dockerproject.org debian- InRelease
Get:3 https://apt.dockerproject.org debian- Release.gpg [162 B]
Ign https://apt.dockerproject.org debian- Release.gpg
Get:4 https://apt.dockerproject.org debian- Release [162 B]
Ign https://apt.dockerproject.org debian- Release
Get:5 http://ftp.us.debian.org stretch/main Translation-en/DiffIndex [7876 B]
Get:6 https://apt.dockerproject.org debian-/main amd64 Packages [162 B]
Get:7 https://apt.dockerproject.org debian-/main Translation-en [162 B]
Get:8 https://apt.dockerproject.org debian-/main amd64 Packages [162 B]
Get:9 https://apt.dockerproject.org debian-/main Translation-en [162 B]
Get:10 https://apt.dockerproject.org debian-/main amd64 Packages [162 B]
Get:11 https://apt.dockerproject.org debian-/main Translation-en [162 B]
Get:12 https://apt.dockerproject.org debian-/main amd64 Packages [162 B]
Get:13 https://apt.dockerproject.org debian-/main Translation-en [162 B]
Get:14 https://apt.dockerproject.org debian-/main amd64 Packages [162 B]
Err https://apt.dockerproject.org debian-/main amd64 Packages
  HttpError404
Get:15 https://apt.dockerproject.org debian-/main Translation-en [162 B]
Ign https://apt.dockerproject.org debian-/main Translation-en
Fetched 15.8 kB in 1s (12.3 kB/s)
W: Failed to fetch https://apt.dockerproject.org/repo/dists/debian-/main/binary-
amd64/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used
 instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package docker-engine

Tried with both stretch/testing and unstable in my sources.list, no difference.

Thanks.

**Comment by ndarilek** [comment] 2015-07-29 20:55
Figured it out. The repository was listed as `debian-`, needed to be
`debian-stretch`. Seems https://get.docker.com doesn't work on Debian
versions that aren't stable.

Thanks.

**Comment by Evalle** [comment] 2015-07-31 07:12
Hello @ndarilek, could you please close this issue ?

**Comment by ndarilek** [comment] 2015-07-31 11:16
Why? Is there a better place to file installer issues? Happy to refile,
but it is still an issue that needs a fix even though I discovered the
cause, so I'd only prefer to close it if there's a better place to file it.

Thanks.

**Comment by thaJeztah** [comment] 2015-08-02 15:12
@ndarilek there's currently work in progress on improving distro-detection in the install script; although I'm not sure this particular case is covered, perhaps you could check if it does; the work-in-progress PR can be found here; https://github.com/docker/docker/pull/15001

In the meantime, you could manually add the right apt repo, see the blog post for more information; http://blog.docker.com/2015/07/new-apt-and-yum-repos/

**Comment by jfrazelle** [comment] 2015-09-02 04:43
I run debian testing and cannot reproduce

**Closed** 2015-09-02 04:43 UTC
