### ISSUE TITLE
multiple volumes don't work when all of them are on same storage...

### ISSUE THREAD

**Issue by nuved** [docker/docker#20311] opened 2016-02-14 13:38 UTC
for example,  we have three folders on three different storages: 

/mnt/sda/a
/mnt/sdb/b
/mnt/sdc/c

and then the following command is working well. 
```
docker run  -v /mnt/sda/a:/tmp -v /mnt/sdb/b:/var/log/mysql --volume /mnt/sdc/c:/var/lib/mysql/  -v /etc/my.cnf:/etc/my.cnf  --name mariadb10.1 -it   ubuntugalera bash
```
 In container we access to all of these folders.

but when all folders are in the same storage like: 

/mnt/sda/a
/mnt/sda/b
/mnt/sda/c

by running this command, I just see the first folder! in other word, just /tmp directory is  mounted to /sda
 ```
docker run  -v /mnt/sda/a:/tmp -v /mnt/sda/b:/var/log/mysql --volume /mnt/sda/c:/var/lib/mysql/  -v /etc/my.cnf:/etc/my.cnf  --name mariadb10.1 -it   ubuntugalera bash
```
```
root@node42642 ~ # docker info
```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 33
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 54
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.35 GiB
Name: node42642
ID: DRQE:NZXR:QOJX:3ZXY:3KMK:HC2L:AIG2:QIMZ:3LY5:4QRD:UA3I:WQ3D
WARNING: No swap limit support

**Comment by qq690388648** [comment] 2016-02-15 04:37
My docker 1.10.1 on Ubuntu 12.04 worked well in your case, so your result may caused by another reason, for example, your <code>/mnt/sda/b</code> and <code>/mnt/sda/c</code> may be empty?

**Comment by nuved** [comment] 2016-02-15 06:31
I tested it again on ubuntu 12.10... it is ok!!! but on  Ubuntu 14.04.3 LTS and latest Debian  version, I still have this problem !! there is some files in all of directories...  
what's wrong with Ubuntu 14.04.3?

**Comment by thaJeztah** [comment] 2016-02-15 11:34
Can you check `docker inspect` of that container, to see if the mounts have been applied? e.g.

    docker inspect --format "{{ json .Mounts }}" my-container

**Comment by nuved** [comment] 2016-02-15 11:50
```
root@node42642 ~ # docker inspect --format "{{ json .Mounts }}" mariadb10.1
```

[{"Source":"/root/docker-entrypont.sh","Destination":"/docker-entrypoint.sh","Mode":"","RW":true,"Propagation":"rprivate"},{"Source":"/mnt/b/novid","Destination":"/var/lib/mysql","Mode":"","RW":true,"Propagation":"rprivate"},{"Source":"/etc/my.cnf","Destination":"/etc/my.cnf","Mode":"","RW":true,"Propagation":"rprivate"},{"Source":"/dev/log","Destination":"/dev/log","Mode":"","RW":true,"Propagation":"rprivate"}]

but from inside container, I can't see any mounted partition
```
root@node42642:/# df -h
 ```
Filesystem      Size  Used Avail Use% Mounted on
none            591G   91G  476G  16% /
tmpfs            32G     0   32G   0% /dev
tmpfs            32G     0   32G   0% /sys/fs/cgroup
/dev/dm-1       591G   91G  476G  16% /etc/hosts
tmpfs           6.3G  9.1M  6.3G   1% /dev/log
shm              64M     0   64M   0% /dev/shm

**Comment by HackToday** [comment] 2016-02-16 01:37
I did not have ubuntugalera  image, I tried ubuntu,

Did you check other images work ?

And what about other host directory when use with -v ?

**Comment by nuved** [comment] 2016-02-16 06:32
As I mentioned, I have this problem with ubuntu14.04 and above versions and Debian jessie ... there is not any problem with ubuntu 12.10 
```
root@node42642 /mnt/b/novid # docker run --volume /root/:/var/log/mysql   --dns=8.8.8.8 --rm -it  ubuntu:14.04 bash
```
from inside container: 
```
root@79aa9dfdb789:/# df -h
```
Filesystem      Size  Used Avail Use% Mounted on
none            591G   91G  475G  17% /
tmpfs            32G     0   32G   0% /dev
tmpfs            32G     0   32G   0% /sys/fs/cgroup
__/dev/dm-1       591G   91G  475G  17% /var/log/mysql__
shm              64M     0   64M   0% /dev/shm

with two volumes:
```
root@node42642 /mnt/b/novid # docker run --volume /root/:/var/log/mysql -v /home:/home   --dns=8.8.8.8 --rm -it  ubuntu:14.04 bash
```
from container:
```
root@e139b6d0fa12:/# df -h
```
Filesystem      Size  Used Avail Use% Mounted on
none            591G   91G  475G  17% /
tmpfs            32G     0   32G   0% /dev
tmpfs            32G     0   32G   0% /sys/fs/cgroup
__/dev/dm-1       591G   91G  475G  17% /home__
shm              64M     0   64M   0% /dev/shm

and without any volume option,only dns option is working .
root@node42642 /mnt/b/novid # docker run  --dns=8.8.8.8 --rm -it  ubuntu:14.04 bash
root@5bef448e572d:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
none            591G   91G  475G  17% /
tmpfs            32G     0   32G   0% /dev
tmpfs            32G     0   32G   0% /sys/fs/cgroup
__/dev/dm-1       591G   91G  475G  17% /etc/hosts__
shm              64M     0   64M   0% /dev/shm


but in ubuntu 12.10 seems everything are ok! 
```
root@node42642 /mnt/b/novid # docker run  --volume /root/:/var/log/mysql -v /home:/home --dns=8.8.8.8 --rm -it  ubuntu:12.10 bash
```
```
root@68c294ba1de1:/# df -h
```
Filesystem      Size  Used Avail Use% Mounted on
none            591G   91G  475G  17% /
tmpfs            32G     0   32G   0% /dev
tmpfs            32G     0   32G   0% /sys/fs/cgroup
__/dev/dm-1       591G   91G  475G  17% /home
/dev/dm-1       591G   91G  475G  17% /var/log/mysql
/dev/dm-1       591G   91G  475G  17% /etc/resolv.conf
/dev/dm-1       591G   91G  475G  17% /etc/hostname
/dev/dm-1       591G   91G  475G  17% /etc/hosts__
shm              64M     0   64M   0% /dev/shm
tmpfs            32G     0   32G   0% /proc/kcore
tmpfs            32G     0   32G   0% /proc/timer_stats


can anyone reproduce this problem?  please help me :(

**Comment by thaJeztah** [comment] 2016-02-16 10:04
I see the same differences in `df -h`, *however* running `ls -l /var/log/mysql` does show the bind-mounted volume the same in both cases, so I'm wondering if it's just a difference in the way `df` is handled inside a ubuntu 12.10 or 14.04 image

**Comment by nuved** [comment] 2016-02-16 10:53
thanks man :) you saved me from troubles! so there is just a little bug  with df command?

**Comment by nuved** [comment] 2016-02-16 10:53
thanks man :) you saved me from troubles! so there is just a little bug  with df command?

**Comment by thaJeztah** [comment] 2016-02-16 10:56
I don't know, actually, this is the first time I compared it between versions. Is this currently blocking something in your use case?

**Comment by ehazlett** [comment] 2016-09-19 14:41
@nuved I'm going to close this as it appears to be resolved.  Please comment or open a new issue if you continue to have trouble.  Thanks!

**Closed by ehazlett** 2016-09-19 14:41 UTC

**Comment by Krishnababu505** [comment] 2019-07-30 12:43
@thaJeztah @nuved @ehazlett 
Hello All

I am facing same issue when i was trying to use volumes i can able to mount them but i can't see by using df command, but using ls i can see them i am using Ubuntu 16.04.6 LTS container
could you please help me what causing this issue.


docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 22
**Server Version: 18.09.0**
Storage Driver: xyzrfs
 Build Version: xyzrfs v4.9.1
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d5ce216b9817463c29fb
runc version: 425e105d5a06fabd737a128ad93d62a9eeede87f
init version: fec3683
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: Oracle Linux Server 7.6
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26GiB
Name: xyz012345
ID: NODM:PX2E:SRWT:Q6DP:DOAS:VLNP:CZNJ:FGPQ:7TSV:6GFS:VOZA:ELSR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Labels:
Experimental: false
 Live Restore Enabled: false
Product License: Community Engine

docker verison

Client:
 Version:           **18.09.7**
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     false

docker inspect 

[{"Type":"bind","Source":"/**opt/gitlab/config**","Destination":"/**etc/gitlab**","Mode":"","RW":true,"Propagation":"rprivate"},{"Type":"bind","Source":"/**opt/gitlab/logs**","Destination":"/**var/log/gitlab**","Mode":"","RW":true,"Propagation":"rprivate"},{"Type":"bind","Source":"/**opt/gitlab/data**","Destination":"**/var/opt/gitlab**","Mode":"","RW":true,"Propagation":"rprivate"}]

df output

/dev/sda                300G   70G  208G  26% /
tmpfs                    64M     0   64M   0% /dev
tmpfs                    16G     0   16G   0% /sys/fs/cgroup
/**dev/mapper/rootvg-opt  4.0G  1.1G  3.0G  26% /etc/gitlab**
/dev/sda                300G   70G  208G  26% /etc/hosts
shv                      64M  444K   64M   1% /dev/shv
