### ISSUE TITLE
[Docker Swarm mode] Not really fault-tolerant

### ISSUE THREAD

**Issue by samber** [docker/docker#26491] opened 2016-09-12 15:23 UTC
Hi guys,

I would mention some issue and dead-lock of Swarm Managers when nodes go up and down often (especially in cloud environment !).

### Problem 1:

- Start 3 Docker Swarm managers
- Then kill 2
- Then create a new 1 
- You get stuck because the quorum has been lost

Need to execute ```docker swarm init --force-new-cluster``` ([currently not working](https://forums.docker.com/t/how-to-kill-a-broken-swarm/19352/6)) :trollface:

If I lost an AZ in an AWS region, hosting 2 managers of a 3 managers cluster, I cannot start new nodes in my ASG.

I'm not very familiar with RAFT and Etcd implementation, but what about allowing a manager to join/leave a cluster by just (un-)following the leader, without being stuck by a quorum ?

### Problem 2:

If I upgrade my AWS IAM and deploy 3 other managers, my quorum will be set to 4 (6 nodes). After shutting down my 3 old managers, I will lost the quorum (3 instances left).

What about using an ```--expected-managers=3``` flag in ```docker swarm init```, to "hard-code" the quorum in a cluster ? Consul and Etcd are based on that method.

### Problem 3:

Removing/demoting "unreachable" Swarm managers to get a single-manager cluster (without using ```--force-new-cluster```) is not allowed when Swarm does not reach quorum... (see problem 1)

**Comment by dperny** [comment] 2016-09-12 17:00
I'm not saying this can't be done or that it doesn't need work, but adding and removing nodes is always going to be a sticky, fragile situation. 

For problem 1, the issue is really evident: shutting down a manager does not remove it from a cluster. The cluster doesn't know (or care) whether a manager comes down of its own accord or whether it crashes; it just sees that the manager goes offline. If you needed to, say, upgrade managers, you gotta do them one at a time so that you don't lose quorum. 

This is deliberate. We're trying to avoid the problem of "split-brain", where two sets of managers think they form a complete swarm. If you don't respect the quorum rules at every step, you could end up in a case where two sets of managers is each running in the same cluster. Imagine the case where your network splits. One manager will see that the other two have disappeared, and so it shouldn't do any work; the other managers (which still have quorum) are still in charge! Who knows what would happen if the lone manager started altering the cluster state? 

The `--force-new-cluster` flag is an escape route if you bork your cluster, but it has to be used carefully or you can end up creating a split brain. It shouldn't be broken though, I don't know why it isn't working for you.

The idea of hardsetting a quorum size doesn't really solve the problem you're talking about, either. It can help with bootstrapping a cluster but wouldn't really be useful past the initial bootstrap. 

The last problem is the same as the first: adding and removing manager is a kind of work that requires a quorum.

Czech out http://thesecretlivesofdata.com/raft/, which should only take about 15 minutes, and give you a better base understanding of Raft and maybe of why the system is built like it's built. If you have any other questions, feel free to raise them.

**Comment by jpetazzo** [comment] 2016-09-12 17:04
Hi,

If you kill 2 managers in a group of 3, you are losing [quorum](https://en.wikipedia.org/wiki/Quorum_(distributed_computing)), and the system *must* stop accepting commands.

In a distributed system with strong consistency (like [Raft](https://raft.github.io/), which is used by 
SwarmKit under the hood), you *cannot* restore quorum just by adding a fresh node.

(Sorry if you already knew that; but it's not very clear from your bug report, so please don't be offended if you already know how quorum works :))

Can you provide the following clarifications re/ problem 1:
- what did you expect?
- how did you "kill" the nodes? (Clean shutdown, hard shutdown with SysRq, terminate instance from EC2 console, kill -9 docker process?)
- on which node did you do the `--force-new-cluster` ?

Re/ problem 2: what do you call "AWS IAM" ? Out of context, to me AWS IAM is the identity management service, but in this context, it's obviously something else; can you please clarify?

I'd suggest to explore `docker node demote` for this scenario.

Re/ problem 3: my answer will be the same as for problem 1; _this is the definition of a distributed system quorum_. You cannot accept writes (including updating membership) if you don't have quorum.

Consider the following scenario: your two "killed" nodes are not really dead, but fenced (split brain scenario). Following the rules defined by Raft, those two nodes will continue to operate, and your isolated node *should not* continue to accept commands. What, according to you, should be the mode of operation in that case?

Thank you!

**Comment by tonistiigi** [comment] 2016-09-12 17:14
@samber I tried to reproduce the `--force-new-cluster` issue by starting 3 managers and killing 2 of them but couldn't get  `swarm init --force-new-cluster` to fail like you did. If you can reproduce, can you send `SIGUSR1` signal to the daemon process after receiving this error(or while the init command is running) and send us the stack trace printed to the logs. Also, can you send us the raft state directory located in `/var/lib/docker/swarm`. If this is not a one-off test cluster then please send it privately to avoid leaking certificate keys and tokens.

**Comment by xiaods** [comment] 2016-09-20 05:52
any update?

**Comment by thaJeztah** [comment] 2016-10-15 01:23
ping @samber

**Comment by xiaods** [comment] 2016-10-24 10:50
any update?

**Comment by thaJeztah** [comment] 2016-10-24 17:01
I'm closing this issue, because OP did not provide feedback, but feel free to comment if you think this is still an issue

**Closed by thaJeztah** 2016-10-24 17:01 UTC
Labels: area/swarm, kind/bug, status/more-info-needed

**Comment by xiaods** [comment] 2016-10-25 03:43
@thaJeztah thanks for udpate.
