### ISSUE TITLE
Docker Swarm: Using constraint and affinity with replicas and scale

### ISSUE THREAD

**Issue by pascalandy** [docker/docker#28393] opened 2016-11-14 16:02 UTC
**The good** - I know how to use *constraint* or *affinity* flags to ensure two containers are not living on the same node. From the [docs](https://docs.docker.com/swarm/scheduler/filter/#/use-an-affinity-filter):

```
affinity:container!=~redis* schedule a new redis5 container to a node without a container that satisfies redis*
```

**The challenge** - When using `docker service scale redis=3`, I don't see how can I make sure there is only one container per node ??? Looks like Swarm scales ignores the constrait of the negative affinity flag.

For an HA setup, I want to deploy 2 instances of a service and having Swarm to never deploy the service on the same node. IMHO this should this should works:

```
ENV_NET_STATIC=net_static
ENV_DOMAIN1=iamfoo.pascalandy.com
ctn1_NAME=iamfooA

docker service create \
--name $ctn1_NAME \
--network $ENV_NET_STATIC \
--restart-condition any \
--replicas 2 \
--constraint node.labels.apps_accepted==yes \
--env affinity:container!=~$ctn1_NAME* \
--label traefik.frontend.rule=Host:$ENV_DOMAIN1 \
--label traefik.docker.network=$ENV_NET_STATIC \
--label traefik.backend.loadbalancer.sticky=true \
--label traefik.port=80 \
katacoda/docker-http-server
```

The key here is `--env affinity:container!=~$ctn1_NAME*`, which is the same logic provided by the docs above.

Thanks in advance for your help!
Pascal

**Comment by thaJeztah** [comment] 2016-11-14 16:21
The docs you linked are for standalone swarm, not for swarm _mode_ (which was introduced in docker 1.12). swarm mode does not have an option to have anti-affinity based on other services/containers (see https://docs.docker.com/engine/reference/commandline/service_create/#/specify-service-constraints---constraint). 

Also see https://github.com/docker/docker/issues/24649, https://github.com/docker/docker/issues/26259, and https://github.com/docker/docker/issues/24115

IIRC, this is currently by design, as there were quite some issues around this functionality in "standalone swarm", and they did not want to implement this functionality without properly designing the behavior.

I'll close this issue, because I think it's already covered by the issues I linked above, but feel free to comment on those to describe your use-case as it may help in the design/discussion

**Closed by thaJeztah** 2016-11-14 16:21 UTC
Labels: area/swarm

**Comment by pascalandy** [comment] 2016-11-14 16:27
Thanks for the references :)

**Comment by thaJeztah** [comment] 2016-11-14 16:30
Also note the new HA Scheduler in docker 1.13; https://github.com/docker/docker/issues/26259#issuecomment-245472484, which may address your use case
