### ISSUE TITLE
Something wrong with exposed UDP ports

### ISSUE THREAD

**Issue by pjebs** [docker/docker#22440] opened 2016-05-01 08:38 UTC
I am using Docker to create a container running "iperf3" which is an internet connection speed test program. It can perform a UDP or TCP test.

The udp and tcp ports are both exposed as you can see from `docker ps -a`
The IP address of server is 104.131.128.139.
I can connect to the container for a tcp test but not a udp test.

Ubuntu ufw is off so all ports should be open. I can only assume something is wrong with Docker.
The udp test (iperf client) replies back `error - unable to read from stream socket: Connection refused`.
The tcp test works perfectly.

![27d8977c-0b0d-11e6-9c82-41bf6c6da9a8](https://cloud.githubusercontent.com/assets/5377970/14940906/4d71995c-0fcc-11e6-962b-9da93ecd2666.png)

**Comment by pjebs** [comment] 2016-05-01 08:42
Connecting is via: https://github.com/esnet/iperf/issues/380

**Comment by pjebs** [comment] 2016-05-01 08:43
I connect using ip4 version of ip address? Does that matter? eg. `104.131.128.139`

**Comment by thaJeztah** [comment] 2016-05-01 14:05
Possibly a duplicate of https://github.com/docker/docker/issues/2174

**Comment by pjebs** [comment] 2016-05-02 23:32
What should I do about this problem?

**Comment by justincormack** [comment] 2016-05-03 13:27
I cannot replicate anything like this, perhaps you could add a full way to replicate this, including all the commands, and a public container for testing.

**Comment by pjebs** [comment] 2016-05-11 23:05
@justincormack can you send me a email address and I'll send you the Dockerfile.

**Comment by justincormack** [comment] 2016-05-12 10:41
@pjebs justin.cormack@docker.com

**Comment by pjebs** [comment] 2016-05-18 12:24
@justincormack I sent the email.  Looking forward to finding out if it's a docker issue or my issue. I'm leaning towards docker issue.

**Comment by pjebs** [comment] 2016-05-25 00:27
@justincormack I didn't get a reply so I did some more tests. I ran iPerf (alongside the docker host, and **not** inside a container), and was able to connect to it for a udp test so it is almost certainly a docker issue.

**Comment by thaJeztah** [comment] 2016-05-25 11:42
sorry for the delay, @pjebs. @justincormack has been traveling this week, so possibly missed it

ping @justincormack 😇

**Comment by pjebs** [comment] 2016-06-03 05:03
I haven't heard anything back yet.

**Comment by justincormack** [comment] 2016-06-03 07:21
Sorry, can you resend the mail, I didn't see it.

**Comment by pjebs** [comment] 2016-06-03 07:41
resent

**Comment by pjebs** [comment] 2016-06-07 14:51
did you receive email? I didn't get confirmation.

**Comment by pjebs** [comment] 2016-06-21 03:59
Any news on this?

**Comment by pjebs** [comment] 2016-07-05 04:07
@justincormack I think you're a bad representative of the Docker company. Representing that you are going to help and then first pretending you didn't receive email and then ignoring email.

Prob better to not make politician's promises in the first place whilst representing Docker.

Perhaps employment at Yahoo is better suited.

**Comment by justincormack** [comment] 2016-07-05 12:40
I am sorry you feel you need to be rude. I have been away. `iperf3` does not support udp server, you can use `iperf` instead. I recommend you log into the container with `docker exec` and use `netstat` to check if the server is actually listening on udp.

**Closed by justincormack** 2016-07-05 12:40 UTC
Labels: status/more-info-needed

**Comment by pjebs** [comment] 2016-07-05 12:59
"iperf3 does not support udp server" - nonsense. More lies.

I got it working when iperf3 was running alongside the docker host instead of through container.

**Comment by thaJeztah** [comment] 2016-07-05 21:06
@pjebs please watch your language. I understand the reply took longer than expected, but keep in mind that the maintainers have a lot of issues to track, and PR's to review, next to their daily work (which may be on different projects, or completely unrelated to Docker).

Your reply really is inappropriate, so consider this your first warning;
https://github.com/docker/docker/blob/master/CONTRIBUTING.md#guideline-violations--3-strikes-method

**Comment by pjebs** [comment] 2016-07-05 23:33
It's unfortunate I had to be rude to magically get a response.
