### ISSUE TITLE
Unable to run any containers on Windows 10, client hangs

### ISSUE THREAD

**Issue by pbering** [docker/docker#27017] opened 2016-09-29 09:53 UTC
**Description**

On a clean installed Windows 10 Enterprise Anniversary Update with Container and Hyper-V features installed I'm not able to run any containers (nano or WindowsServerCore). Looks like networking problem (see log output)

**Steps to reproduce the issue:**

1. Follow install instructions: [https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10)
2. Run `docker pull microsoft/windowsservercore`, works...
3. Run `docker run microsoft/windowsservercore hostname`, hangs for ever until dockerd is restarted....
4. CTRL+C to stop and try to run any client command like `docker ps` and that also hangs.

**Describe the results you received:**

It hangs, for ever it seems...

**Describe the results you expected:**

Container runs and outputs the hostname

**Additional information you deem important (e.g. issue happens only occasionally):**

**dockerd output from startup**

```
PS C:\WINDOWS\system32> dockerd --log-level debug
time="2016-09-29T11:34:44.448047300+02:00" level=debug msg="Listener created for HTTP on npipe (//./pipe/docker_engine)"
time="2016-09-29T11:34:44.448047300+02:00" level=debug msg="Stackdump - waiting signal at Global\\docker-daemon-7868"
time="2016-09-29T11:34:44.449046900+02:00" level=info msg="Windows default isolation mode: hyperv"
time="2016-09-29T11:34:44.449046900+02:00" level=debug msg="Using default logging driver json-file"
time="2016-09-29T11:34:44.449046900+02:00" level=debug msg="WindowsGraphDriver InitFilter at C:\\ProgramData\\docker\\windowsfilter"
time="2016-09-29T11:34:44.449046900+02:00" level=info msg="[graphdriver] using prior storage driver: windowsfilter"
time="2016-09-29T11:34:44.449046900+02:00" level=debug msg="Using graph driver windowsfilter"
time="2016-09-29T11:34:44.450047100+02:00" level=debug msg="Max Concurrent Downloads: 3"
time="2016-09-29T11:34:44.450047100+02:00" level=debug msg="Max Concurrent Uploads: 5"
time="2016-09-29T11:34:44.476043300+02:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-09-29T11:34:44.476043300+02:00" level=info msg="Loading containers: start."
time="2016-09-29T11:34:44.477043200+02:00" level=debug msg="Option DefaultDriver: nat"
time="2016-09-29T11:34:44.477043200+02:00" level=debug msg="Option DefaultNetwork: nat"
time="2016-09-29T11:34:44.501042700+02:00" level=debug msg="Network Response : [ { \"CurrentEndpointCount\" : 0, \"Degraded\" : true, \"ExternalInterfaceAddress\" : \"78-2B-CB-AB-55-C1\", \"ID\" : \"7513a9bb-9415-4b21-ad06-6fe68b702a4f\", \"MacPools\" : [ { \"EndMacAddress\" : \"00-15-5D-A9-1F-FF\", \"StartMacAddress\" : \"00-15-5D-A9-10-00\" } ], \"MaxConcurrentEndpoints\" : 0, \"NATName\" : \"H7513a9bb-9415-4b21-ad06-6fe68b702a4f\", \"Name\" : \"nat\", \"Policies\" : [  ], \"Subnets\" : [ { \"AddressPrefix\" : \"172.16.0.0/12\", \"GatewayAddress\" : \"172.16.0.1\" } ], \"SwitchGuid\" : \"898932a5-3b9f-4fb4-8511-6cd515ee1708\", \"TotalEndpoints\" : 0, \"Type\" : \"nat\", \"Version\" : 4294967297 } ]"
time="2016-09-29T11:34:44.502044800+02:00" level=debug msg="Launching DNS server for network%!(EXTRA string=none)"
time="2016-09-29T11:34:44.507044200+02:00" level=debug msg="Network Response : [ { \"CurrentEndpointCount\" : 0, \"Degraded\" : true, \"ExternalInterfaceAddress\" : \"78-2B-CB-AB-55-C1\", \"ID\" : \"7513a9bb-9415-4b21-ad06-6fe68b702a4f\", \"MacPools\" : [ { \"EndMacAddress\" : \"00-15-5D-A9-1F-FF\", \"StartMacAddress\" : \"00-15-5D-A9-10-00\" } ], \"MaxConcurrentEndpoints\" : 0, \"NATName\" : \"H7513a9bb-9415-4b21-ad06-6fe68b702a4f\", \"Name\" : \"nat\", \"Policies\" : [  ], \"Subnets\" : [ { \"AddressPrefix\" : \"172.16.0.0/12\", \"GatewayAddress\" : \"172.16.0.1\" } ], \"SwitchGuid\" : \"898932a5-3b9f-4fb4-8511-6cd515ee1708\", \"TotalEndpoints\" : 0, \"Type\" : \"nat\", \"Version\" : 4294967297 } ]"
time="2016-09-29T11:34:44.507044200+02:00" level=error msg="Resolver Setup/Start failed for container none, \"json: cannot unmarshal array into Go value of type hcsshim.HNSNetwork\""
time="2016-09-29T11:34:44.538047600+02:00" level=debug msg="releasing IPv4 pools from network nat (7d7da1d843a49a009b08f065f119458341bd519729143deade09169e48fd1507)"
time="2016-09-29T11:34:44.538047600+02:00" level=debug msg="ReleaseAddress(172.16.0.0/12, 172.16.0.1)"
time="2016-09-29T11:34:44.538047600+02:00" level=debug msg="ReleasePool(172.16.0.0/12)"
time="2016-09-29T11:34:44.609047000+02:00" level=debug msg="Allocating IPv4 pools for network nat (369a70c47fffa7dbb14cf8c7b86a5767e631adb8280afd2213c40a0b398d3d6a)"
time="2016-09-29T11:34:44.609047000+02:00" level=debug msg="RequestPool(LocalDefault, 172.16.0.0/12, , map[], false)"
time="2016-09-29T11:34:44.610053700+02:00" level=debug msg="RequestAddress(172.16.0.0/12, 172.16.0.1, map[RequestAddressType:com.docker.network.gateway])"
time="2016-09-29T11:34:44.610053700+02:00" level=debug msg="Launching DNS server for network%!(EXTRA string=nat)"
time="2016-09-29T11:34:44.614043000+02:00" level=debug msg="Network Response : { \"CurrentEndpointCount\" : 0, \"Degraded\" : true, \"ExternalInterfaceAddress\" : \"78-2B-CB-AB-55-C1\", \"ID\" : \"7513a9bb-9415-4b21-ad06-6fe68b702a4f\", \"MacPools\" : [ { \"EndMacAddress\" : \"00-15-5D-A9-1F-FF\", \"StartMacAddress\" : \"00-15-5D-A9-10-00\" } ], \"MaxConcurrentEndpoints\" : 0, \"NATName\" : \"H7513a9bb-9415-4b21-ad06-6fe68b702a4f\", \"Name\" : \"nat\", \"Policies\" : [  ], \"Subnets\" : [ { \"AddressPrefix\" : \"172.16.0.0/12\", \"GatewayAddress\" : \"172.16.0.1\" } ], \"SwitchGuid\" : \"898932a5-3b9f-4fb4-8511-6cd515ee1708\", \"TotalEndpoints\" : 0, \"Type\" : \"nat\", \"Version\" : 4294967297 }"
time="2016-09-29T11:34:44.615043200+02:00" level=debug msg="Binding a resolver on network nat gateway 172.16.0.1"
time="2016-09-29T11:34:44.615043200+02:00" level=error msg="Resolver Setup/Start failed for container nat, \"error in opening name server socket listen udp 172.16.0.1:53: bind: The requested address is not valid in its context.\""
time="2016-09-29T11:34:44.666042500+02:00" level=info msg="Loading containers: done."
time="2016-09-29T11:34:44.666042500+02:00" level=info msg="Daemon has completed initialization"
time="2016-09-29T11:34:44.666042500+02:00" level=info msg="Docker daemon" commit=601004e graphdriver=windowsfilter version=1.13.0-dev
time="2016-09-29T11:34:44.666042500+02:00" level=debug msg="Registering routers"
time="2016-09-29T11:34:44.666042500+02:00" level=debug msg="Registering HEAD, /containers/{name:.*}/archive"
time="2016-09-29T11:34:44.667043000+02:00" level=debug msg="Registering GET, /containers/json"
time="2016-09-29T11:34:44.667043000+02:00" level=debug msg="Registering GET, /containers/{name:.*}/export"
time="2016-09-29T11:34:44.667043000+02:00" level=debug msg="Registering GET, /containers/{name:.*}/changes"
time="2016-09-29T11:34:44.667043000+02:00" level=debug msg="Registering GET, /containers/{name:.*}/json"
time="2016-09-29T11:34:44.667043000+02:00" level=debug msg="Registering GET, /containers/{name:.*}/top"
time="2016-09-29T11:34:44.667043000+02:00" level=debug msg="Registering GET, /containers/{name:.*}/logs"
time="2016-09-29T11:34:44.667043000+02:00" level=debug msg="Registering GET, /containers/{name:.*}/stats"
time="2016-09-29T11:34:44.668042300+02:00" level=debug msg="Registering GET, /containers/{name:.*}/attach/ws"
time="2016-09-29T11:34:44.668042300+02:00" level=debug msg="Registering GET, /exec/{id:.*}/json"
time="2016-09-29T11:34:44.669043100+02:00" level=debug msg="Registering GET, /containers/{name:.*}/archive"
time="2016-09-29T11:34:44.669043100+02:00" level=debug msg="Registering POST, /containers/create"
time="2016-09-29T11:34:44.669043100+02:00" level=debug msg="Registering POST, /containers/{name:.*}/kill"
time="2016-09-29T11:34:44.670042700+02:00" level=debug msg="Registering POST, /containers/{name:.*}/pause"
time="2016-09-29T11:34:44.670042700+02:00" level=debug msg="Registering POST, /containers/{name:.*}/unpause"
time="2016-09-29T11:34:44.671042600+02:00" level=debug msg="Registering POST, /containers/{name:.*}/restart"
time="2016-09-29T11:34:44.671042600+02:00" level=debug msg="Registering POST, /containers/{name:.*}/start"
time="2016-09-29T11:34:44.671042600+02:00" level=debug msg="Registering POST, /containers/{name:.*}/stop"
time="2016-09-29T11:34:44.672042800+02:00" level=debug msg="Registering POST, /containers/{name:.*}/wait"
time="2016-09-29T11:34:44.672042800+02:00" level=debug msg="Registering POST, /containers/{name:.*}/resize"
time="2016-09-29T11:34:44.672042800+02:00" level=debug msg="Registering POST, /containers/{name:.*}/attach"
time="2016-09-29T11:34:44.673042700+02:00" level=debug msg="Registering POST, /containers/{name:.*}/copy"
time="2016-09-29T11:34:44.673042700+02:00" level=debug msg="Registering POST, /containers/{name:.*}/exec"
time="2016-09-29T11:34:44.674044100+02:00" level=debug msg="Registering POST, /exec/{name:.*}/start"
time="2016-09-29T11:34:44.674044100+02:00" level=debug msg="Registering POST, /exec/{name:.*}/resize"
time="2016-09-29T11:34:44.674044100+02:00" level=debug msg="Registering POST, /containers/{name:.*}/rename"
time="2016-09-29T11:34:44.675043100+02:00" level=debug msg="Registering POST, /containers/{name:.*}/update"
time="2016-09-29T11:34:44.679045100+02:00" level=debug msg="Registering PUT, /containers/{name:.*}/archive"
time="2016-09-29T11:34:44.680043500+02:00" level=debug msg="Registering DELETE, /containers/{name:.*}"
time="2016-09-29T11:34:44.682043900+02:00" level=debug msg="Registering GET, /images/json"
time="2016-09-29T11:34:44.682043900+02:00" level=debug msg="Registering GET, /images/search"
time="2016-09-29T11:34:44.683043500+02:00" level=debug msg="Registering GET, /images/get"
time="2016-09-29T11:34:44.683043500+02:00" level=debug msg="Registering GET, /images/{name:.*}/get"
time="2016-09-29T11:34:44.684043300+02:00" level=debug msg="Registering GET, /images/{name:.*}/history"
time="2016-09-29T11:34:44.684043300+02:00" level=debug msg="Registering GET, /images/{name:.*}/json"
time="2016-09-29T11:34:44.685043200+02:00" level=debug msg="Registering POST, /commit"
time="2016-09-29T11:34:44.685043200+02:00" level=debug msg="Registering POST, /images/load"
time="2016-09-29T11:34:44.686043100+02:00" level=debug msg="Registering POST, /images/create"
time="2016-09-29T11:34:44.686043100+02:00" level=debug msg="Registering POST, /images/{name:.*}/push"
time="2016-09-29T11:34:44.687043000+02:00" level=debug msg="Registering POST, /images/{name:.*}/tag"
time="2016-09-29T11:34:44.687043000+02:00" level=debug msg="Registering DELETE, /images/{name:.*}"
time="2016-09-29T11:34:44.696045400+02:00" level=debug msg="Registering OPTIONS, /{anyroute:.*}"
time="2016-09-29T11:34:44.697042800+02:00" level=debug msg="Registering GET, /_ping"
time="2016-09-29T11:34:44.703045900+02:00" level=debug msg="Registering GET, /events"
time="2016-09-29T11:34:44.710048600+02:00" level=debug msg="Registering GET, /info"
time="2016-09-29T11:34:44.713045100+02:00" level=debug msg="Registering GET, /version"
time="2016-09-29T11:34:44.713045100+02:00" level=debug msg="Registering POST, /auth"
time="2016-09-29T11:34:44.716044800+02:00" level=debug msg="Registering GET, /volumes"
time="2016-09-29T11:34:44.716044800+02:00" level=debug msg="Registering GET, /volumes/{name:.*}"
time="2016-09-29T11:34:44.717048400+02:00" level=debug msg="Registering POST, /volumes/create"
time="2016-09-29T11:34:44.717048400+02:00" level=debug msg="Registering DELETE, /volumes/{name:.*}"
time="2016-09-29T11:34:44.718042700+02:00" level=debug msg="Registering POST, /build"
time="2016-09-29T11:34:44.718042700+02:00" level=debug msg="Registering POST, /swarm/init"
time="2016-09-29T11:34:44.721042400+02:00" level=debug msg="Registering POST, /swarm/join"
time="2016-09-29T11:34:44.727047300+02:00" level=debug msg="Registering POST, /swarm/leave"
time="2016-09-29T11:34:44.728044700+02:00" level=debug msg="Registering GET, /swarm"
time="2016-09-29T11:34:44.734046500+02:00" level=debug msg="Registering POST, /swarm/update"
time="2016-09-29T11:34:44.741061000+02:00" level=debug msg="Registering GET, /services"
time="2016-09-29T11:34:44.743045200+02:00" level=debug msg="Registering GET, /services/{id:.*}"
time="2016-09-29T11:34:44.744044500+02:00" level=debug msg="Registering POST, /services/create"
time="2016-09-29T11:34:44.747045100+02:00" level=debug msg="Registering POST, /services/{id:.*}/update"
time="2016-09-29T11:34:44.747045100+02:00" level=debug msg="Registering DELETE, /services/{id:.*}"
time="2016-09-29T11:34:44.748042800+02:00" level=debug msg="Registering GET, /nodes"
time="2016-09-29T11:34:44.748042800+02:00" level=debug msg="Registering GET, /nodes/{id:.*}"
time="2016-09-29T11:34:44.749043000+02:00" level=debug msg="Registering DELETE, /nodes/{id:.*}"
time="2016-09-29T11:34:44.750048800+02:00" level=debug msg="Registering POST, /nodes/{id:.*}/update"
time="2016-09-29T11:34:44.750048800+02:00" level=debug msg="Registering GET, /tasks"
time="2016-09-29T11:34:44.758042600+02:00" level=debug msg="Registering GET, /tasks/{id:.*}"
time="2016-09-29T11:34:44.765053400+02:00" level=debug msg="Registering GET, /networks"
time="2016-09-29T11:34:44.765053400+02:00" level=debug msg="Registering GET, /networks/"
time="2016-09-29T11:34:44.774044600+02:00" level=debug msg="Registering GET, /networks/{id:.+}"
time="2016-09-29T11:34:44.776049100+02:00" level=debug msg="Registering POST, /networks/create"
time="2016-09-29T11:34:44.777046100+02:00" level=debug msg="Registering POST, /networks/{id:.*}/connect"
time="2016-09-29T11:34:44.779044100+02:00" level=debug msg="Registering POST, /networks/{id:.*}/disconnect"
time="2016-09-29T11:34:44.780047400+02:00" level=debug msg="Registering DELETE, /networks/{id:.*}"
time="2016-09-29T11:34:44.781044800+02:00" level=info msg="API listen on //./pipe/docker_engine"
time="2016-09-29T11:34:44.781044800+02:00" level=debug msg="Config reload - waiting signal at Global\\docker-daemon-config-7868"
```

Most interesting is `Resolver Setup/Start failed for container nat, \"error in opening name server socket listen udp 172.16.0.1:53: bind: The requested address is not valid in its context.\""`

**dockerd output from when using docker run**
```
docker run microsoft/windowsservercore hostname

time="2016-09-29T11:35:19.044052100+02:00" level=debug msg="Calling POST /v1.25/containers/create"
time="2016-09-29T11:35:19.045053900+02:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":[\"hostname\"],\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":false,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[39,193],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"microsoft/windowsservercore\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}"
time="2016-09-29T11:35:19.055052500+02:00" level=debug msg="hcsshim::GetLayerMountPath Flavour 1 ID 9110335f73e5bdc017a06ab65ea47b59f1ac522705aa0fa18e74402e69f2f750"
time="2016-09-29T11:35:19.057052900+02:00" level=debug msg="Calling proc (1)"
time="2016-09-29T11:35:19.059067300+02:00" level=debug msg="Calling proc (2)"
time="2016-09-29T11:35:19.059067300+02:00" level=debug msg="hcsshim::GetLayerMountPath succeeded flavour=1 id=9110335f73e5bdc017a06ab65ea47b59f1ac522705aa0fa18e74402e69f2f750 path=C:\\ProgramData\\docker\\windowsfilter\\9110335f73e5bdc017a06ab65ea47b59f1ac522705aa0fa18e74402e69f2f750"
time="2016-09-29T11:35:19.059067300+02:00" level=debug msg="hcsshim::CreateSandboxLayer layerId b3573267e424025846483cf60b5a3a5a7323d5b0624fea6b0195999964693616 parentId C:\\ProgramData\\docker\\windowsfilter\\9110335f73e5bdc017a06ab65ea47b59f1ac522705aa0fa18e74402e69f2f750"
time="2016-09-29T11:35:19.060051300+02:00" level=debug msg="hcsshim::NameToGuid Name 9110335f73e5bdc017a06ab65ea47b59f1ac522705aa0fa18e74402e69f2f750"
time="2016-09-29T11:35:19.068053800+02:00" level=debug msg="hcsshim::CreateSandboxLayer - succeeded layerId=b3573267e424025846483cf60b5a3a5a7323d5b0624fea6b0195999964693616 parentId=C:\\ProgramData\\docker\\windowsfilter\\9110335f73e5bdc017a06ab65ea47b59f1ac522705aa0fa18e74402e69f2f750"
time="2016-09-29T11:35:19.068053800+02:00" level=debug msg="hcsshim::ExpandSandboxSize layerId=b3573267e424025846483cf60b5a3a5a7323d5b0624fea6b0195999964693616 size=0"
time="2016-09-29T11:35:19.073052300+02:00" level=debug msg="hcsshim::ExpandSandboxSize - succeeded layerId=b3573267e424025846483cf60b5a3a5a7323d5b0624fea6b0195999964693616 size=0"
time="2016-09-29T11:35:19.150052200+02:00" level=debug msg="Calling POST /v1.25/containers/b3573267e424025846483cf60b5a3a5a7323d5b0624fea6b0195999964693616/attach?stderr=1&stdout=1&stream=1"
time="2016-09-29T11:35:19.150052200+02:00" level=debug msg="attach: stdout: begin"
time="2016-09-29T11:35:19.150052200+02:00" level=debug msg="attach: stderr: begin"
time="2016-09-29T11:35:19.154057100+02:00" level=debug msg="Calling POST /v1.25/containers/b3573267e424025846483cf60b5a3a5a7323d5b0624fea6b0195999964693616/start"
time="2016-09-29T11:35:19.154057100+02:00" level=debug msg="Calling GET /v1.25/events?filters=%7B%22container%22%3A%7B%22b3573267e424025846483cf60b5a3a5a7323d5b0624fea6b0195999964693616%22%3Atrue%7D%2C%22type%22%3A%7B%22container%22%3Atrue%7D%7D"
time="2016-09-29T11:35:19.159052200+02:00" level=debug msg="Assigning addresses for endpoint elegant_heisenberg's interface on network nat"
time="2016-09-29T11:35:19.159052200+02:00" level=debug msg="RequestAddress(172.16.0.0/12, <nil>, map[])"
```
Hangs on last line...

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   601004e
 Built:        Wed Sep 28 12:46:56 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   601004e
 Built:        Wed Sep 28 12:46:56 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.187.amd64fre.rs1_release_inmarket.160906-1818)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.88 GiB
Name: DK-PMB2
ID: AJK3:IBTZ:DBII:YNWW:CAFG:OXZS:YBZZ:DIQB:V2QA:NR5M:K3HT:L2LY
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by StefanScherer** [comment] 2016-09-29 10:31
Looks like https://github.com/Microsoft/Virtualization-Documentation/issues/395, there will be a Windows Update the next few days that should fix the problem for Windows 10.
Docker 4 Windows Beta 26++ is the only working constellation I know for Windows 10 1607 right now.

**Comment by cpuguy83** [comment] 2016-09-29 12:49
Great, thanks @StefanScherer!

Going to close this since it's tracked over there and seems to be a Windows bug.
Thanks all!

**Closed by cpuguy83** 2016-09-29 12:49 UTC
Labels: platform/windows, version/master

**Comment by tutukar** [comment] 2016-09-29 16:06
I am running into the same issue running docker in Server 2016 eval vm inside Virtual Box. Is this update applicable to Server 2016 as well?
Error during start up: cannot unnmarshal array into GO value of type hcsshim.HSNNetwork

**Comment by PatrickLang** [comment] 2016-10-05 00:34
Yes - both Windows 10 Anniversary Update and the Windows Server 2016 evaluation need updates applied.

**Comment by frjaraur** [comment] 2016-10-08 19:05
Thanks God :D, Same issue here and getting mad about that, trying on both, Windows 10 Pro updated to anniversary edition and Server 2016 Evaluation.....
Is there any fix that we can apply or there isn't any yet?

Many Thanks,
Javier R.

**Comment by frjaraur** [comment] 2016-10-09 07:58
I can confirm that it works after installing update KB3194496.
Many Thanks,
Javier R.

**Comment by renerchen** [comment] 2016-12-01 07:59
Does KB3194496 works for windows server 2016?
