### ISSUE TITLE
Support editing configurations of an existing container

### ISSUE THREAD

**Issue by ilcic** [docker/docker#29053] opened 2016-12-02 07:19 UTC
In current version of docker, the settings of a container is fixed whenever it is created. For example, when I do `docker run -dit -p 5566:7788 ubuntu`, the port-forwarding settings is fixed. There seems no way that I can edit this setting except recreating a new container. Is it possible to support this feature?

**Comment by thaJeztah** [comment] 2016-12-02 15:26
This is a duplicate of https://github.com/docker/docker/issues/2045, and related to https://github.com/docker/docker/issues/3285 / https://github.com/docker/docker/pull/15078.

For the `docker update` command, changes that can be made to a container are currently restricted to changes to "resources". There is no real consensus on changing ports yet, but it could be worth describing your use case (i.e. why you need to add / remove a port from a _running_ container, and your use case is not resolved by starting a new container to replace the existing one) in https://github.com/docker/docker/issues/2045.

fwiw docker services in swarm mode _do_ have the option to add/remove ports, but instead of updating a container, replace the containers backing the service with new ones.

I'll close this issue here because it's a duplicate, but as mentioned above, describing your use case would be welcome (as it may give insight as to why it's needed, and cannot be resolved with the current options)

**Closed by thaJeztah** 2016-12-02 15:26 UTC
Labels: area/runtime, kind/enhancement
