### ISSUE TITLE
Docker service rm does not clean properly the published ports

### ISSUE THREAD

**Issue by nyanloutre** [docker/docker#26530] opened 2016-09-13 13:32 UTC
**Description**

When I remove a service, the ports that were published by it are not properly removed from the iptables

**Steps to reproduce the issue:**
1. docker service create --name spark-proxy --network spark-net -p 8080:8080 -p 50070:50070 nyanloutre/spark-proxy (it's just nginx with custom config file)
2. curl http://localhost:8080 return the page
3. docker service rm spark-proxy

**Describe the results you received:**
```sudo iptables -t nat -L```
```
...
Chain DOCKER-INGRESS (2 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             anywhere             tcp dpt:50070 to:172.18.0.2:50070
DNAT       tcp  --  anywhere             anywhere             tcp dpt:http-alt to:172.18.0.2:8080
RETURN     all  --  anywhere             anywhere
```

**Describe the results you expected:**
```sudo iptables -t nat -L```
```
...
Chain DOCKER-INGRESS (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue is coming randomly on my 6 hosts.
For example the last time I tried it happened on 3 of my 6 hosts.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 78
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: active
 NodeID: f308skpi0pxi41dujetjsot64
 Is Manager: true
 ClusterID: a94pihw2derc4wnf6dzcphcaz
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 130.79.128.186
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58 GiB
Name: cds-stage-ms4
ID: WMUK:RVW6:IULI:5MWL:XIV5:3SDT:A62G:TQHK:7NK7:3RG3:LZKG:O7ES
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker is installed on 6 physical computers

**Comment by nyanloutre** [comment] 2016-09-13 14:42
The consequence is that if I try to recreate the same service afterward, the ports will not be accessible (impossible to access to nginx)

**Comment by aaronlehmann** [comment] 2016-09-13 21:21
ping @mrjana

**Comment by mrjana** [comment] 2016-09-14 06:05
@nyanloutre Is it possible to attach daemon logs when the problem happened?

**Comment by ascora** [comment] 2016-09-14 07:54
I can confirm this bug

**Comment by ascora** [comment] 2016-09-14 09:13
@nyanloutre Did you find a workaround for this?
@mrjana I got this issue in a swarm of 5 physical servers with Ubuntu 16.04 and again in a swarm of 3 servers also using Ubuntu 16.04. As far as I can see the demo above also happened with Ubuntu 16.04 (could be a coincidence of course)

**Comment by nyanloutre** [comment] 2016-09-14 09:24
I already looked in the logs but there is nothing related to this. Should I tell Docker to output logs in debug verbosity ?

**Comment by ascora** [comment] 2016-09-14 09:51
As a follow up information: 
In additoion to the NAT rules in iptables, docker also seems to be listening to the port. In my case I had a service on port 8080, which I removed using _docker service rm nginx_. Aftzerward, the 
`sudo iptables -t nat -L`
shows
`Chain DOCKER-INGRESS (2 references)`
target     prot opt source               destination
```
...
DNAT       tcp  --  anywhere             anywhere             tcp dpt:http-alt to:172.18.0.2:8080
...
```

and 
`netstat --tcp --udp --listening --program | grep docke
`shows
```
...
tcp6       0      0 [::]:http-alt           [::]:*                  LISTEN      3603/dockerd
...
```

**Comment by ascora** [comment] 2016-09-14 10:21
I am able to reproduce this everytime I do a cervice create... servide rm ... service create chain. I filed in a new entry as I'm not sure how this is related and to add the details:

https://github.com/docker/docker/issues/26563

**Comment by vingrad** [comment] 2016-09-14 19:39
Please fix asap.

**Comment by tnbeatty** [comment] 2016-09-15 01:14
I can confirm this as well, and have a swarm (3 managers, 3 workers) running on Ubuntu 14.04. I also faced the issue on Ubuntu 16.04 but downgraded in a test environment to see if I continued to encounter the error as @ascora described. I will reproduce in a clean environment and post any differences I find in logs / version / system setup asap.

**Comment by sanimej** [comment] 2016-09-16 16:47
@nyanloutre I don't have a bunch of physical machines. But with VMs I am not able to recreate this issue. Are you using stock Ubuntu 16.04 or are there any changes ? Are you running any additional network utilities (ufw etc.) ?

**Comment by nyanloutre** [comment] 2016-09-19 07:08
@sanimej I am using stock Ubuntu with just iptables and no other firewall utilities

**Comment by dtmistry** [comment] 2016-09-22 17:00
I'm seeing this issue as well. But, I'm able create to recreate the 'docker service' on the same ports. The problem is, if I try to start a process which requires that port on the host/vm, it fails since dockerd is stilling listening on that port

**Steps to reproduce**

`docker service create --name nginx -p 80:80 -p 443:443 --mode global nginx`

`docker service rm nginx`

`netstat -ln --program`

```
tcp6       0      0 :::80                   :::*                    LISTEN      796/dockerd
tcp6       0      0 :::8500                 :::*                    LISTEN      796/dockerd
tcp6       0      0 :::22                   :::*                    LISTEN      4214/sshd
tcp6       0      0 :::8600                 :::*                    LISTEN      796/dockerd
tcp6       0      0 ::1:25                  :::*                    LISTEN      3037/master
tcp6       0      0 :::443                  :::*                    LISTEN      796/dockerd
```

Creating the service again works

`docker service create --name nginx -p 80:80 -p 443:443 --mode global nginx`

`docker service ls`

```
ID            NAME   REPLICAS  IMAGE  COMMAND
0qwaiu29vgiw  nginx  global    nginx

```

Remove the service again - 

`docker service rm nginx`

Try to start container outside of swarm and it fails

`docker run -d -p 80:80 -p 443:443 nginx`

```
6c060ddb77a4474fcf90284feff8cb47c58c1e622436f467366cc343912bb35f
docker: Error response from daemon: driver failed programming external connectivity on endpoint tiny_archimedes (a7cdffaa9507f8f47996d55277e93fb466bd0137ad12d6fad39f9547b00c4d9b): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use.
```

**Comment by daviddyball** [comment] 2016-09-23 13:08
Just to add I can recreate this by doing the following on an empty cluster running on top of Ubuntu 16.04 with `1.12.1` every time if I do the following:

```
docker network create -d overlay swarm_cluster
docker service create --name myservice --publish 80:80 --network swarm_cluster --replicas 0 myimage
docker service update myservice --replicas 2
...
# Wait for service to come online and confirm ports are bound using netstat
...
docker service update myservice --replicas 0
docker service rm myservice

# Now recreate it
docker service create --name myservice --publish 80:80 --network swarm_cluster --replicas 0 myimage
docker service update myservice --replicas 2
```

After doing this the two nodes that previously had the service running on them won't bind to to `80` (as visible by `netstat`). I've also noted that after the containers get removed this shows in the logs:

```
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.144187852Z" level=debug msg="Sending 15 to 53f86b3613e5af0983cfdc29de9cb4314128a0ee7477754cf3c4d60487340a72"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.211703206Z" level=debug msg="containerd: process exited" id=53f86b3613e5af0983cfdc29de9cb4314128a0ee7477754cf3c4d60487340a72 pid=init status=143 systemPid=23974
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.219168105Z" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"exit\", Id:\"53f86b3613e5af0983cfdc29de9cb4314128a0ee7477754cf3c4d60487340a72\", Status:0x8f, Pid:\"init\", Timestamp:(*timestamp.Timestamp)(0xc8211fd6a0)}"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.219578596Z" level=debug msg="checkEncryption(3fkurpy, <nil>, 0, true)"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.278513755Z" level=debug msg="Releasing addresses for endpoint benchmark-search.1.2jmn26u4hgset59jphmkmhfli's interface on network ingress"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.278549616Z" level=debug msg="ReleaseAddress(LocalDefault/10.255.0.0/16, 10.255.0.6)"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.342775516Z" level=debug msg="checkEncryption(3fkurpy, 192.168.30.79, 0, false)"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.342773956Z" level=debug msg="miss notification for dest IP, 10.255.0.7"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.434524742Z" level=debug msg="checkEncryption(f350kx4, <nil>, 0, true)"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.463241747Z" level=debug msg="Revoking external connectivity on endpoint gateway_53f86b3613e5 (fcc12f8bbebdf51c5a4c599ffba478353c85973e86b86102a5bc0496a8b45d8c)"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.535718269Z" level=debug msg="Releasing addresses for endpoint gateway_53f86b3613e5's interface on network docker_gwbridge"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.535752620Z" level=debug msg="ReleaseAddress(LocalDefault/172.18.0.0/16, 172.18.0.3)"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.550527922Z" level=debug msg="Releasing addresses for endpoint benchmark-search.1.2jmn26u4hgset59jphmkmhfli's interface on network swarm_cluster"
Sep 23 12:57:17 ip-192-168-31-112 dockerd[23212]: time="2016-09-23T12:57:17.550556601Z" level=debug msg="ReleaseAddress(LocalDefault/10.0.0.0/24, 10.0.0.3)"
```

When I stop/delete the service the first time there are extra calls to `iptables` to remove the port 80 rules before any of the above is output to the logs:

```
Sep 23 12:44:37 ip-192-168-31-112 dockerd[21058]: time="2016-09-23T12:44:37.941385304Z" level=debug msg="/sbin/iptables, [--wait -t nat -L DOCKER-INGRESS]"
Sep 23 12:44:37 ip-192-168-31-112 dockerd[21058]: time="2016-09-23T12:44:37.944090943Z" level=debug msg="/sbin/iptables, [--wait -t nat -D DOCKER-INGRESS -p tcp --dport 80 -j DNAT --to-destination 172.18.0.2:80]"
```

**Comment by daviddyball** [comment] 2016-10-06 11:11
Surprised this still has no traction ☹️ 

Anyway... I just wanted to update that `1.12.2-rc2` didn't fix this issue either.

**Comment by mrjana** [comment] 2016-10-06 15:52
@daviddyball I think this is not a common issue. To debug further, can you please provide the outputs of:
* `docker info`
* `iptables -t nat -nvL` before and after removing the service
* `netstat -tnap` before and after removing the service

Are you saying that these ports are not released even after restarting docker?

**Comment by daviddyball** [comment] 2016-10-06 16:12
Hi @mrjana, yes even after a restart of the service the iptables rules remain. Oddly enough, deleting the rules manually still won't allow creation of any new services with the ports I'm using and restarting `docker` puts the same rules back in the NAT table after it restarts.

In the bellow output ports `8983` and `2181` belong to Solr and Zookeeper and are services that I'm trying to remove/recreate. 

`docker info`
```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 5.578 GB
 Data Space Total: 53.04 GB
 Data Space Available: 47.46 GB
 Metadata Space Used: 2.298 MB
 Metadata Space Total: 557.8 MB
 Metadata Space Available: 555.5 MB
 Thin Pool Minimum Free Space: 5.304 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: 1mfzyqe9nu90ykl1hcdkrq3v7
 Is Manager: false
 Node Address: 192.168.30.249
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-192-168-30-249
ID: 4652:2EKN:ERQC:U4P6:XHSJ:AA7U:WQIH:AF6X:BLFL:2QIM:PYTV:GOJI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 com.amazon.aws.ec2.type=m4.large
 com.artfinder.swarm.worker=true
Insecure Registries:
 127.0.0.0/8
```

`iptables -t nat -nvL` **before** service removal
```
Chain PREROUTING (policy ACCEPT 12470 packets, 836K bytes)
 pkts bytes target     prot opt in     out     source               destination
 891K   93M DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
 891K   93M DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 1677 packets, 101K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 1725 packets, 107K bytes)
 pkts bytes target     prot opt in     out     source               destination
   46  2760 DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 1725 packets, 107K bytes)
 pkts bytes target     prot opt in     out     source               destination
   29  1740 MASQUERADE  all  --  *      docker_gwbridge  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match src-type LOCAL
1079K   86M MASQUERADE  all  --  *      !docker_gwbridge  172.18.0.0/16        0.0.0.0/0
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  docker_gwbridge *       0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-INGRESS (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:2181 to:172.18.0.2:2181
    6   360 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8983 to:172.18.0.2:8983
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:6432 to:172.18.0.2:6432 <-- This is valid
```

`iptables -t nat -nvL` **after** service removal (it is the same after `docker` daemon restart)
```
Chain PREROUTING (policy ACCEPT 12539 packets, 840K bytes)
 pkts bytes target     prot opt in     out     source               destination
 891K   93M DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
 892K   93M DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 1692 packets, 102K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 1738 packets, 108K bytes)
 pkts bytes target     prot opt in     out     source               destination
   46  2760 DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 1738 packets, 108K bytes)
 pkts bytes target     prot opt in     out     source               destination
   29  1740 MASQUERADE  all  --  *      docker_gwbridge  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match src-type LOCAL
1079K   86M MASQUERADE  all  --  *      !docker_gwbridge  172.18.0.0/16        0.0.0.0/0
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  docker_gwbridge *       0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-INGRESS (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:2181 to:172.18.0.2:2181
    6   360 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8983 to:172.18.0.2:8983
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:6432 to:172.18.0.2:6432
```

`netstat -tnap`
```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1249/sshd
tcp        0    224 192.168.30.249:22       90.152.40.250:58067     ESTABLISHED 28587/sshd: ubuntu
tcp        0      0 192.168.30.249:48006    192.168.21.13:2377      ESTABLISHED 10576/dockerd
tcp        0      0 192.168.30.249:57828    192.168.32.250:7946     TIME_WAIT   -
tcp        0      0 192.168.30.249:34466    54.239.34.141:443       ESTABLISHED 10576/dockerd
tcp        0      0 192.168.30.249:22       90.152.40.250:58064     ESTABLISHED 28475/sshd: ubuntu
tcp        0      0 192.168.30.249:51888    54.239.36.132:443       ESTABLISHED 10576/dockerd
tcp        0      0 192.168.30.249:57840    192.168.32.250:7946     TIME_WAIT   -
tcp        0      0 192.168.30.249:54892    192.168.21.13:7946      TIME_WAIT   -
tcp6       0      0 :::6432                 :::*                    LISTEN      10576/dockerd
tcp6       0      0 :::2181                 :::*                    LISTEN      10576/dockerd
tcp6       0      0 :::7946                 :::*                    LISTEN      10576/dockerd
tcp6       0      0 :::22                   :::*                    LISTEN      1249/sshd
tcp6       0      0 :::8983                 :::*                    LISTEN      10576/dockerd
tcp6       0      0 192.168.30.249:7946     192.168.32.250:54240    TIME_WAIT   -
tcp6       0      0 192.168.30.249:7946     192.168.21.13:33716     TIME_WAIT   -
tcp6       0      0 192.168.30.249:7946     192.168.20.49:43634     TIME_WAIT   -
tcp6       0      0 192.168.30.249:7946     192.168.31.77:33478     TIME_WAIT   -
```

**Comment by mrjana** [comment] 2016-10-06 16:16
@daviddyball I think you are having some issue with the gossip channel. Can you attach docker daemon logs on the node where you are having this issue?

**Comment by mrjana** [comment] 2016-10-06 16:18
BTW, are you still seeing the following even after docker restart:
```
0      0 :::6432                 :::*                    LISTEN      10576/dockerd
tcp6       0      0 :::2181                 :::*                    LISTEN      10576/dockerd
tcp6       0      0 :::7946                 :::*                    LISTEN      10576/dockerd
tcp6       0      0 :::22                   :::*                    LISTEN      1249/sshd
tcp6       0      0 :::8983                 :::*                    LISTEN      10576/dockerd
```

**Comment by daviddyball** [comment] 2016-10-06 16:18
Debug logging isn't enabled on this node. I can enable it, restart and try the process again if you like.

Here are the logs so far:
```
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.474266013Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.492873093Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.602009738Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.674156133Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.674192675Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.873596559Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.874127973Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.874151970Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.874168030Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.891512593Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.891542760Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.892511433Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.892535387Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:10 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:10.892551107Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:11 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:11.092583231Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:11 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:11.801778235Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:11 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:11.892701751Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 11:38:12 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T11:38:12.091607815Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:20:58 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:20:58.873568268Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:20:58 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:20:58.892013696Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:20:59 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:20:59.001504564Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:20:59 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:20:59.073655221Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:20:59 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:20:59.273695345Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:20:59 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:20:59.673688521Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:20:59 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:20:59.690984849Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:20:59 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:20:59.890970211Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:21:00 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:21:00.001409590Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:21:05 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:21:05.291043641Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:21:05 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:21:05.473729540Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:21:05 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:21:05.491086541Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:21:05 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:21:05.673745574Z" level=error msg="ip-192-168-30-249: unknown message type 6"
Oct 06 14:40:41 ip-192-168-30-249 dockerd[10576]: time="2016-10-06T14:40:41.872685078Z" level=info msg="2016/10/06 14:40:41 [INFO] memberlist: Suspect ip-192-168-22-81-f0211d7d3de7 has failed, no acks received\n"
```

**Comment by daviddyball** [comment] 2016-10-06 16:20
RE: Still seeing the same `netstat -tnap` ouput... yes. It remains.

**Comment by mrjana** [comment] 2016-10-06 16:26
Ok the logs suggest that you have some other service using memberlist protocol and also using port 7946 in another node (may be the node is 192.168.22.81). Can you run `netstat -tnap` on that node? Are you running `consul` or `serf` on any of these nodes in the cluster?

**Comment by daviddyball** [comment] 2016-10-06 16:38
Strange 192.168.22.81 is the first of 3 manager-only nodes. These nodes are running with `availability` set to `drain`.

The node that I've been providing info for is one of the workers in the swarm.

**Comment by daviddyball** [comment] 2016-10-06 16:39
Here's the output from that master node:

```
tcp6       0      0 :::2377                 :::*                    LISTEN      28866/dockerd
tcp6       0      0 :::7946                 :::*                    LISTEN      28866/dockerd
tcp6       0      0 :::22                   :::*                    LISTEN      16314/sshd
tcp6       0      0 :::8983                 :::*                    LISTEN      28866/dockerd
tcp6       0      0 :::25                   :::*                    LISTEN      14726/master
tcp6       0      0 :::6432                 :::*                    LISTEN      28866/dockerd
tcp6       0      0 :::2181                 :::*                    LISTEN      28866/dockerd
```

**Comment by mrjana** [comment] 2016-10-06 16:59
@daviddyball Are you running a different version in the manager node by any chance?

**Comment by daviddyball** [comment] 2016-10-06 17:02
No, I updated all nodes to use `1.12.2-rc2` hoping that would fix the issue.

**Comment by mrjana** [comment] 2016-10-06 17:09
I don't think the logs from `192.168.30.249` are reflecting that (i.e that it is running 1.12.2-rc2) since it did not recognize the new message type added to 1.12.2-rc2. Are you sure the logs posted emitted after you upgraded docker in that node then?

**Comment by daviddyball** [comment] 2016-10-06 17:15
Ahh you are right that node wasn't running the RC2. I've updated it now, but the issue still remains. I'm going to teardown the cluster tomorrow and rebuild from scratch with pure RC2 and test again.

I really appreciate your help on this. I'll report back once I have new data.

**Comment by daviddyball** [comment] 2016-10-07 09:29
@mrjana Initial tests this morning on a fresh swarm running `1.12.2-rc2` are promising. I can create/destroy services and no ports are left orphaned. I will continue running this configuration and report back if anything comes up. Thank you again for your assistance.

**Comment by mrjana** [comment] 2016-10-12 23:18
Since we believe this is fixed in 1.12.2 I am going to close this. @daviddyball Please feel free to reopen if this is not the case.

**Closed by mrjana** 2016-10-12 23:18 UTC
Labels: area/networking, area/swarm, kind/bug, version/1.12

**Comment by blaketmiller** [comment] 2016-11-21 17:27
I don't have the availability right to submit a full report, but I'm seeing this behavior in 1.12.3, supposedly after this was fixed.

**Comment by Noodle05** [comment] 2017-07-08 23:40
This randomly happened to me in 1.13.1 as well.
