### ISSUE TITLE
copy from host to docker 

### ISSUE THREAD

**Issue by laithrafid** [docker/docker#27043] opened 2016-09-29 19:18 UTC
how to build into the docker file  a cmd to copy from the host file system to the container file system 

FROM centos
MAINTAINER laith
RUN yum -y update
WORKDIR /
RUN mkdir /dev/mx/
COPY /mx/lib/ /lib/
COPY /dev/mx  /dev/mx

i'm getting this error
lstat mx/lib/: no such file or directory

**Comment by thaJeztah** [comment] 2016-09-29 19:54
`COPY` is relative to the _build context_, usually, this is the location that the Dockerfile is in, so if you run `COPY /foo/bar baz`, then docker looks for a directory named `foo` in the same directory as your Dockerfile.

This is by design, and out of security, as that will prevent a Dockerfile from copying random files from your host into the image that's produced.

Also read https://docs.docker.com/engine/tutorials/dockerimages/, and https://docs.docker.com/engine/reference/builder/

I'll close this issue, because this is not a bug, and the GitHub issue tracker is not intended as a general support forum. Consider using https://forums.docker.com, the #docker IRC channel, or StackOverflow for questions about using docker.

**Closed by thaJeztah** 2016-09-29 19:54 UTC

**Comment by laithrafid** [comment] 2016-09-29 19:58
thanks @thaJeztah
