### ISSUE TITLE
Docker in Docker - failed to find the cgroup root

### ISSUE THREAD

**Issue by STOIE** [docker/docker#8791] opened 2014-10-27 03:21 UTC
Hi all,

I am running 1.3 on RHEL7 with a priv container running ubuntu 14:04 and 1.3 under it.
Everything is running, however, in jenkins (the container running docker within), I am getting the following:

```
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:latest
 ---> 5506de2b643b
Step 1 : MAINTAINER Aaron Nicoli <aaronnicoli@gmail.com>
 ---> Running in 88aa05a47854
 ---> 23620994a830
Removing intermediate container 88aa05a47854
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in 8462b83bec13
 ---> 6aa5870a3b2d
Removing intermediate container 8462b83bec13
Step 3 : RUN rm -f /etc/localtime
 ---> Running in 0f2bcc9197b8
Removing intermediate container 0f2bcc9197b8
2014/10/27 14:12:23 failed to find the cgroup root
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

Any thoughts?
I can't see any issues, but, then again.. I am no expert.

```
root@02eff186c45b:/# df -h
Filesystem                                                                                        Size  Used Avail Use% Mounted on
/dev/mapper/docker-8:49-1310721-02eff186c45bd6dd568a909b7fb7e86cd92a8599b2921c6e558ad21627a705cf  9.8G  735M  8.5G   8% /
tmpfs                                                                                             3.9G     0  3.9G   0% /dev
shm                                                                                                64M     0   64M   0% /dev/shm
/dev/sdd1                                                                                          40G  3.6G   34G  10% /etc/hosts
/dev/sdc1                                                                                          16G  491M   15G   4% /var/jenkins_home
cgroup                                                                                            3.9G     0  3.9G   0% /sys/fs/cgroup
```

I have /var/lib/docker listed as a volume in the Dockerfile (that the jenk container was built from).

Aaron.

**Comment by jaybuff** [comment] 2015-01-16 06:39
I had this issue with docker 1.3.0

I went through the code and I think I understand what is happening.  At *startup time* the docker daemon reads  /proc/self/mountinfo to determine where your cgroups are mounted:

    [jaybuff@host ~]$  cat /proc/self/mountinfo |grep cpu$
    24 21 0:18 / /cgroup/cpu rw,relatime - cgroup cgroup rw,cpu

Docker parses that line and, in this case, it would be "/cgroup"

cgconfig is what creates those mounts for you.  In RHEL it's this file, which is part of the libcgroup package:

    [jaybuff@host ~]$ rpm -qf /etc/rc.d/init.d/cgconfig
    libcgroup-0.37-7.el6.x86_64

My issue was that I was starting cgconfig to create those mount points after I started docker.

This bug was introduced in libcontainer's commit 2531fba when the code to read /proc/self/mountinfo was moved into an init() function which happens at start up time.  Previous to that commit it was in a regular function, so it the mountinfo was read on each call.

IMHO, the fix for this is to fail to start the docker daemon if you can't determine the cgroup root rather than waiting until the getCgroupData() function is called.

**Comment by jaybuff** [comment] 2015-01-16 06:47
Sorry, the real issue was caused by https://github.com/docker/libcontainer/commit/3cbe3eb3f693876d6c94c0e4d72d627df05a95ae

**Comment by mbentley** [comment] 2015-01-17 13:11
For anyone who may be having or is still having this issue on a RHEL server, would you be able to verify if the `libcgroup` package is installed using `sudo yum list installed libcgroup`?  If it isn't try installing it (`sudo yum install libcgroup`).

Assuming it is installed already, first of all, check the status:
```
$ sudo /etc/init.d/cgconfig status
Running
```

If it is stopped, start it:
```
$ sudo /etc/init.d/cgconfig start
Starting cgconfig service:                                 [  OK  ]
```

If it is already running, restart it:
```
$ sudo /etc/init.d/cgconfig restart
Stopping cgconfig service:                                 [  OK  ]
Starting cgconfig service:                                 [  OK  ]
```

The docker init script `/etc/init.d/docker` requires that the `cgconfig` service be started but it sounds like one (or more) of the cgroup filesystems becomes unconfigured for whatever reason after the service is started so restarting it ought to resolve the issues.

If it doesn't, could someone post their `/etc/cgconfig.conf` and check to see if there are any files in `/etc/cgconfig.d`?

**Comment by dmichel1** [comment] 2015-01-18 16:52
as a workaround on Ubuntu install cgroups and ensure it's started. 

```
apt-get install cgroup-lite
service cgroup-lite start
```

**Comment by jaybuff** [comment] 2015-01-19 17:32
@dmichel1 you must start cgroup-lite to create the proper mounts *before* docker starts.

**Comment by jaybuff** [comment] 2015-02-04 23:55
ping @vmarmol 

Your commit 
https://github.com/docker/libcontainer/commit/3cbe3eb3f693876d6c94c0e4d72d627df05a95ae is the root cause of this bug.  Can you move the cgroup root check in cgroups/fs/apply_raw.go to run during startup time rather than runtime?

**Comment by vmarmol** [comment] 2015-02-06 16:59
@jaybuff would be happy to, but the proper response to an init failure is to panic. Is that the intended behavior?

**Comment by jaybuff** [comment] 2015-02-06 17:13
Before docker/libcontainer@3cbe3eb the cgroup root was located on every "docker run" call.  That meant that you could mount ```/cgroup``` after starting dockerd.  That check is expensive, so now it only makes that check at start up time.  The problem is that it doesn't fail until ```docker run``` time and mounting ```/cgroup``` after dockerd starts won't resolve the issue.  Now we have to have start up script code that refuses to start the docker daemon until the cgroup root is mounted.  

There are two ways to address this an not reintroduce the performance issues you resolved in 3cbe3eb.  

If the cgroup root is not mounted:

    * dockerd should fail to start with an error message and a non zero exit code.  
    * if the start up time check had failed, rerun the check at ```docker run``` time.

I like the second option because it mirrors the docker 1.2 behavior.

**Comment by vmarmol** [comment] 2015-02-06 17:22
The second options sounds good. I'll go ahead and send a PR. Thanks for reporting and debugging!

**Closed** 2015-02-06 20:25 UTC
Labels: /project/helpwanted

**Comment by johanhaleby** [comment] 2015-03-13 19:47
Should this be fixed in Docker 1.5.0? I'm getting the same error when using Docker in Docker, both the host and container (also running docker) is using 1.5.0.

**Comment by bmwertman** [comment] 2015-04-11 13:42
When I run `sudo /etc/init.d/cgconfig status` as @mbentley suggested it says stopped.

Running `sudo /etc/init.d/cgconfig start` errors with;

`Starting cgconfig service: Error: cannot mount hugetlb to /cgroup/hugetlb: No such file or directory
/sbin/cgconfigparser;` 
`error loading /etc/cgconfig.conf: Cgroup mounting failed
Failed to parse /etc/cgconfig.conf`

**Comment by zhouyangchao** [comment] 2017-09-06 03:24
Wow, it works for me.
