### ISSUE TITLE
How to access EC2 from multiple host machine?

### ISSUE THREAD

**Issue by Yotakoio** [docker/docker#29326] opened 2016-12-12 13:50 UTC
Hi,
I created a new EC2 instance using docker-machine, and it could be great if other members of the development team could access the instance to build/run etc..

**Is it possible to share a docker-machine? How to do this?**
I guess I need to share the .pem?

Docker machine infos:
```
{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "52...",
        "MachineName": "aws-0.1.0",
        "SSHUser": "ubuntu",
        "SSHPort": 22,
        "SSHKeyPath": "C:\\Users\\Jimmy\\.docker\\machine\\machines\\aws-0.1.0\\id_rsa",
        "StorePath": "C:\\Users\\Jimmy\\.docker\\machine",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": "",
        "Id": "979...",
        "AccessKey": "AKI...",
        "SecretKey": "ybk...",
        "SessionToken": "",
        "Region": "eu-west-1",
        "AMI": "ami-8aa67cf9",
        "SSHKeyID": 0,
        "KeyName": "aws-0.1.0",
        "InstanceId": "i-0ce5d9e8ba0b250cd",
        "InstanceType": "t2.micro",
        "PrivateIPAddress": "172...",
        "SecurityGroupId": "",
        "SecurityGroupIds": [
            "sg-ac1adfca"
        ],
        "SecurityGroupName": "",
        "SecurityGroupNames": [
            "docker-machine"
        ],
        "Tags": "",
        "ReservationId": "",
        "DeviceName": "/dev/sda1",
        "RootSize": 16,
        "VolumeType": "gp2",
        "IamInstanceProfile": "",
        "VpcId": "vpc-04721460",
        "SubnetId": "subnet-c0c5bfa4",
        "Zone": "a",
        "RequestSpotInstance": false,
        "SpotPrice": "0.50",
        "PrivateIPOnly": false,
        "UsePrivateIP": false,
        "UseEbsOptimizedInstance": false,
        "Monitoring": false,
        "SSHPrivateKeyPath": "",
        "RetryCount": 5
    },
    "DriverName": "amazonec2",
    "HostOptions": {
        "Driver": "",
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "ArbitraryFlags": [],
            "Dns": null,
            "GraphDir": "",
            "Env": [],
            "Ipv6": false,
            "InsecureRegistry": [],
            "Labels": [],
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsVerify": true,
            "RegistryMirror": [],
            "InstallURL": "https://get.docker.com"
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Agent": false,
            "Master": false,
            "Host": "tcp://0.0.0.0:3376",
            "Image": "swarm:latest",
            "Strategy": "spread",
            "Heartbeat": 0,
            "Overcommit": 0,
            "ArbitraryFlags": [],
            "ArbitraryJoinFlags": [],
            "Env": null,
            "IsExperimental": false
        },
        "AuthOptions": {
            "CertDir": "C:\\Users\\Jimmy\\.docker\\machine\\certs",
            "CaCertPath": "C:\\Users\\Jimmy\\.docker\\machine\\certs\\ca.pem",
            "CaPrivateKeyPath": "C:\\Users\\Jimmy\\.docker\\machine\\certs\\ca-key.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "C:\\Users\\Jimmy\\.docker\\machine\\machines\\aws-0.1.0\\server.pem",
            "ServerKeyPath": "C:\\Users\\Jimmy\\.docker\\machine\\machines\\aws-0.1.0\\server-key.pem",
            "ClientKeyPath": "C:\\Users\\Jimmy\\.docker\\machine\\certs\\key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "ClientCertPath": "C:\\Users\\Jimmy\\.docker\\machine\\certs\\cert.pem",
            "ServerCertSANs": [],
            "StorePath": "C:\\Users\\Jimmy\\.docker\\machine\\machines\\aws-0.1.0"
        }
    },
    "Name": "aws-0.1.0"
}
```

**Comment by thaJeztah** [comment] 2016-12-12 14:14
Please keep in mind that the GitHub issue tracker is for reporting bugs and feature requests, and not a general support forum. For other types of questions/discussions, consider using;

- https://forums.docker.com
- the docker community slack channel (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)

This question looks to be related to Docker Machine, which is a separate project, and has its own issue tracker. I think this is a duplicate of https://github.com/docker/machine/issues/23, or https://github.com/docker/machine/issues/1328; you can subscribe to those issues using the "subscribe" button to keep up to date.

I'll close this issue here, because this is related to Docker Machine, not the "docker engine", but feel free to comment after I closed.

**Closed by thaJeztah** 2016-12-12 14:14 UTC

**Comment by Yotakoio** [comment] 2016-12-12 14:23
Thanks sorry for the duplicate ;)
