### ISSUE TITLE
Cannot create containers with --net=host without specific network files (e.g. /etc/hosts)

### ISSUE THREAD

**Issue by tomdee** [docker/docker#16948] opened 2015-10-12 16:22 UTC
This is running on CoreOS, and might be CoreOS specific.

```
$ ./docker-1.9.0-dev run --net=host busybox
INFO[0050] POST /v1.21/containers/create
INFO[0050] POST /v1.21/containers/e98959a118279142f605b0d07655bf42e3035eb4c76a413fa0d8b4e8eb516552/attach?stderr=1&stdout=1&stream=1
INFO[0050] POST /v1.21/containers/e98959a118279142f605b0d07655bf42e3035eb4c76a413fa0d8b4e8eb516552/start
ERRO[0050] Handler for POST /v1.21/containers/e98959a118279142f605b0d07655bf42e3035eb4c76a413fa0d8b4e8eb516552/start returned error: Cannot start container e98959a118279142f605b0d07655bf42e3035eb4c76a413fa0d8b4e8eb516552: chown /var/lib/docker/containers/e98959a118279142f605b0d07655bf42e3035eb4c76a413fa0d8b4e8eb516552/hosts: no such file or directory
ERRO[0050] HTTP Error                                    err=Cannot start container e98959a118279142f605b0d07655bf42e3035eb4c76a413fa0d8b4e8eb516552: chown /var/lib/docker/containers/e98959a118279142f605b0d07655bf42e3035eb4c76a413fa0d8b4e8eb516552/hosts: no such file or directory statusCode=500
Error response from daemon: Cannot start container e98959a118279142f605b0d07655bf42e3035eb4c76a413fa0d8b4e8eb516552: chown /var/lib/docker/containers/e98959a118279142f605b0d07655bf42e3035eb4c76a413fa0d8b4e8eb516552/hosts: no such file or directory
```

```
$ ./docker-1.9.0-dev version
INFO[0039] GET /v1.21/version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   d7177c1
 Built:        Mon Oct 12 15:49:30 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   d7177c1
 Built:        Mon Oct 12 15:49:30 UTC 2015
 OS/Arch:      linux/amd64

$ uname -a
Linux calico-01 4.1.6-coreos-r1 #2 SMP Sat Aug 29 01:28:29 UTC 2015 x86_64 Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz GenuineIntel GNU/Linux

$ ./docker-1.9.0-dev info
INFO[0181] GET /v1.21/info
Containers: 2
Images: 13
Engine Version: 1.9.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.6-coreos-r1
Operating System: CoreOS 789.0.0
CPUs: 1
Total Memory: 997.5 MiB
Name: calico-01
ID: FN4C:HBIS:XT4Y:XRTC:65FN:UIAE:X4AL:Q6ON:HOY3:F2R4:SPH4:JP7Q
```

**Comment by cpuguy83** [comment] 2015-10-12 17:25
Can't repro here. Anything special here other than CoreOS?

**Comment by estesp** [comment] 2015-10-12 17:38
@tomdee does your host OS not have an `/etc/hosts` file?  If so, that's a case not expected in the code, but is fixable.

**Comment by tomdee** [comment] 2015-10-12 18:51
Yes, CoreOS doesn't have a /etc/hosts file.

**Comment by estesp** [comment] 2015-10-12 18:52
Ok, I'll fix this. Thanks.

**Comment by estesp** [comment] 2015-10-12 19:53
So, this is a regression from 1.8.x because of a change in **libnetwork**; specifically, the move from `endpoint` -> `sandbox` for the responsibility to handle `/etc/hosts`, which introduced proper handling of host networking, rather than the prior vendored libnetwork, which created a default `hosts` file no matter what, with the default entries encoded in the `etchosts.Build` function.

Maybe because of the understanding that some distros might have a non-existing `/etc/hosts`,  the following line ignores the "file doesn't exist" error on copying the source `/etc/hosts` to the container metadata -> https://github.com/docker/docker/blob/master/vendor/src/github.com/docker/libnetwork/sandbox.go#L447)

The problem however is that by not failing there, the rest of the Docker daemon container setup code allows the `hosts` network file mount to be added to the list of bind mounts, which then fails for various reasons of course (chown is a recent failure because of userns being merged, but fixing that lets the actual mountpoint fail in libcontainer's root FS setup code).

So, to support a non-existing `/etc/hosts`, we have to filter the network mounts by which files actually exist in the container metadata directory after libnetwork has performed its setup.  @mavenugo does that sound right to you?  I don't think libnetwork needs to change here, as it seems to already support non-existing `/etc/hosts`, although it would fail if `/etc/resolv.conf` didn't exist because the check is different on `copyFile()`.

**Comment by estesp** [comment] 2015-10-12 19:55
FYI @icecrime , @tiborvass ; adding to 1.9.0 as this is a behavior regression from 1.8.x releases.  Should be a simple fix, but I assume it should be included.

**Comment by icecrime** [comment] 2015-10-12 20:04
Awesome, thanks @estesp (cc @mavenugo)

**Closed** 2015-10-12 22:38 UTC
Labels: group/networking, kind/bug, status/claimed
