### ISSUE TITLE
build failed with device mapper error

### ISSUE THREAD

**Issue by helenxu1221** [docker/docker#10415] opened 2015-01-28 15:42 UTC
I have docker 1.5.0 rc1 installed and device mapper configured to use logic volume directly. I hit the following error when I have two build running at the same time

Removing intermediate container 2b6891532aec
INFO[0060] Error getting container 2b6891532aecb0c7c21b19511be7a1933ee01f05b39ea47f419bd3948b411bdb from driver devicemapper: open /dev/mapper/docker-202:2-4072516-2b6891532aecb0c7c21b19511be7a1933ee01f05b39ea47f419bd3948b411bdb: no such file or directory

this problem happened in docker 1.4.1 as well.

**Comment by helenxu1221** [comment] 2015-01-28 15:51
debug message: 
^[[34mINFO^[[0m[0357] +job release_interface(2b6891532aecb0c7c21b19511be7a1933ee01f05b39ea47f419bd3948b411bdb) ^M
No network information to release for 2b6891532aecb0c7c21b19511be7a1933ee01f05b39ea47f419bd3948b411bdb^M
^[[34mINFO^[[0m[0357] -job release_interface(2b6891532aecb0c7c21b19511be7a1933ee01f05b39ea47f419bd3948b411bdb) = ERR (1) ^M
^[[31mERRO^[[0m[0357] Warning: error unmounting device 2b6891532aecb0c7c21b19511be7a1933ee01f05b39ea47f419bd3948b411bdb: UnmountDevice: device not-mounted id 2b6891532aecb0c7c21b19511be7a1933ee01f05b39ea47f419bd3948b411bdb ^M
^[[31mERRO^[[0m[0357] Warning: error unmounting device 2b6891532aecb0c7c21b19511be7a1933ee01f05b39ea47f419bd3948b411bdb: UnmountDevice: device not-mounted id 2b6891532aecb0c7c21b19511be7a1933ee01f05b39ea47f419bd3948b411bdb ^M
Error getting container 2b6891532aecb0c7c21b19511be7a1933ee01f05b39ea47f419bd3948b411bdb from driver devicemapper: open /dev/mapper/docker-202:2-4072516-2b6891532aecb0c7c21b19511be7a1933ee01f05b39ea47f419bd3948b411bdb: no such file or directory^M
^[[34mINFO^[[0m[0357] -job build() = ERR (1)

**Comment by unclejack** [comment] 2015-01-29 06:33
This is an exact duplicate of #4036.

I'm going to close and lock this issue so that the discussion continues on #4036. We're seeing a lot of duplicates for this issue and it makes keeping track of new devicemapper related issues difficult. That's why I'm locking it as well.

Please comment on #4036 if you get the "no such file or directory" error with devicemapper.

**Closed by unclejack** 2015-01-29 06:33 UTC
Labels: /system/devicemapper
