### ISSUE TITLE
[1.12.0-rc2] Can not connect remote docker instance to running swarm cluster (rpc error: code = 4 desc = context deadline exceeded)

### ISSUE THREAD

**Issue by jnoller** [docker/docker#23782] opened 2016-06-20 22:28 UTC
**Output of `docker version`:**

Client (laptop, OSX)
```
$> docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

Server:

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:21:56 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:21:56 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

Client:
```
Containers: 78
 Running: 0
 Paused: 0
 Stopped: 78
Images: 51
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 344
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: AX3N:B5KC:6TY6:V5UW:5MAH:JSD3:PXBN:HC3H:GF3L:GC7L:Z35R:KAIW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 95
 System Time: 2016-06-20T22:09:37.819574454Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

Server (swarm cluster):
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.1 MiB
Name: docker1
ID: LOR7:TUJW:PXCF:SGKX:L5LU:GQCT:UTRN:G72M:JU32:I24J:JN3R:BN34
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Configuration is a group of 4 swarm nodes running ubuntu 16.04. My 'client' is the Docker for Mac beta running on a different network (home). 

From the swarm node leader:

```
docker swarm inspect
[
    {
        "ID": "bp450a0g3jbapw0wdsmhkrv3s",
        "Version": {
            "Index": 55
        },
        "CreatedAt": "2016-06-20T20:22:10.831316894Z",
        "UpdatedAt": "2016-06-20T20:43:20.317168481Z",
        "Spec": {
            "Name": "default",
            "AcceptancePolicy": {
                "Policies": [
                    {
                        "Role": "worker",
                        "Autoaccept": true
                    },
                    {
                        "Role": "manager",
                        "Autoaccept": false
                    }
                ]
            },
            "Orchestration": {
                "TaskHistoryRetentionLimit": 10
            },
            "Raft": {
                "SnapshotInterval": 10000,
                "LogEntriesForSlowFollowers": 500,
                "HeartbeatTick": 1,
                "ElectionTick": 3
            },
            "Dispatcher": {
                "HeartbeatPeriod": 5000000000
            },
            "CAConfig": {
                "NodeCertExpiry": 7776000000000000
            }
        }
    }
]
```

4 nodes total talking on a private network:

```
ID                         NAME     MEMBERSHIP  STATUS   AVAILABILITY  MANAGER STATUS
09y7cdu03xmuwhta0ykvd72gb  docker4  Accepted    Ready    Active        Reachable
1jkzrkblwbdig3l5u29997n00  docker1  Accepted    Ready    Active        Leader
41znz1ntskwvvvea8up52wu0m  docker2  Accepted    Ready    Active        Reachable
5bt1bcak4tuzm9a39a7ou9upz  docker3  Accepted    Ready    Active
```

**Steps to reproduce the issue:**
1. Configure swarm 1.12 as above - the cluster has four total nodes using a private eth1 network to connect to one another.
2. Now, using the docker for mac beta, perform a `docker swarm join --manager publicIP:2377` you should see the following on the leader:
```
ID                         NAME     MEMBERSHIP  STATUS   AVAILABILITY  MANAGER STATUS
09y7cdu03xmuwhta0ykvd72gb  docker4  Accepted    Ready    Active        Reachable
1jkzrkblwbdig3l5u29997n00  docker1  Accepted    Ready    Active        Leader
41znz1ntskwvvvea8up52wu0m  docker2  Accepted    Ready    Active        Reachable
5bt1bcak4tuzm9a39a7ou9upz  docker3  Accepted    Ready    Active        
ai6cie5sw35rucks3kfeojdw8           Pending     Unknown  Active     
```
you can then run `docker node accept ai6cie5sw35rucks3kfeojdw8` and we can see the node (the laptop) approved:

```
Node ai6cie5sw35rucks3kfeojdw8 accepted in the swarm.
```

3. Type `docker node ls` on the leader:

```
ID                         NAME     MEMBERSHIP  STATUS   AVAILABILITY  MANAGER STATUS
09y7cdu03xmuwhta0ykvd72gb  docker4  Accepted    Ready    Active        Reachable
11ghb0yx7ir8ada8wyptmnu0r           Pending     Unknown  Active        
1jkzrkblwbdig3l5u29997n00  docker1  Accepted    Ready    Active        Leader
41znz1ntskwvvvea8up52wu0m  docker2  Accepted    Ready    Active        Reachable
5bt1bcak4tuzm9a39a7ou9upz  docker3  Accepted    Ready    Active        
ai6cie5sw35rucks3kfeojdw8  moby     Accepted    Ready    Active        Unreachable
```

You can see it's in 'unreachable' state. 

4. Swap back to the client (laptop):
```
$> docker node ls
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```

**Describe the results you received:**

the Swarm cluster goes into an odd state throwing:
```
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```
Additionally, I can not demote / rm on the leader:

```
root@docker1:~# docker node demote ai6cie5sw35rucks3kfeojdw8
Manager ai6cie5sw35rucks3kfeojdw8 demoted in the swarm.
root@docker1:~# docker node rm ai6cie5sw35rucks3kfeojdw8
Error response from daemon: rpc error: code = 9 desc = node ai6cie5sw35rucks3kfeojdw8 is not down and can't be removed
```

in order to get out of that state you must run this on the client, then do the rm from the leader

```
docker swarm leave --force
``` 

**Describe the results you expected:**
I expected the client on my remote laptop to be able to join as a manager to be able to deploy services / run cluster administration commands (it seems 'manager' mode is the only way to do this). The documentation doesn't make it clear if you can connect the docker client on one network / system remotely to the full swarm cluster without `joining` as a master.

**Additional information you deem important (e.g. issue happens only occasionally):**

If you join the `client` as a default worker in a fresh cluster with only 1 manager, and then promote the remote client, all managers will begin throwing `Error response from daemon: rpc error: code = 4 desc = context deadline exceeded` effectively going offline. See issue https://github.com/docker/docker/issues/23784

**Comment by shenshouer** [comment] 2016-06-21 07:18
I have the same issue when promote the node with docker 1.12-rc2:

```
[vagrant@centos01 ~]$ docker node promote centos02
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
[vagrant@centos01 ~]$ docker node promote centos03
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
[vagrant@centos01 ~]$ docker node ls
ID                           NAME      MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS  LEADER
8i07v3mx5ogdz1z68iide3yrn    centos03  Accepted    Ready   Active
cioe124z1315ucs5rwd8n2mdv *  centos01  Accepted    Ready   Active        Reachable       Yes
dfsp35af3tvt1ztf6ffcehtko    centos02  Accepted    Ready   Active        Unreachable
```

log:
```
...
un 20 10:47:39 centos01 dockerd[2511]: time="2016-06-20T10:47:39.835138541-04:00" level=error msg="Error trying v2 registry: context canceled"
Jun 20 10:47:39 centos01 dockerd[2511]: time="2016-06-20T10:47:39.835189275-04:00" level=error msg="Not continuing with pull after error: context canceled"
Jun 20 10:47:39 centos01 dockerd[2511]: time="2016-06-20T10:47:39.835229668-04:00" level=error msg="fatal task error" error="context canceled" module=taskmanager task.id=2d6vttb3oaxav9ea28nyclhnm
Jun 20 10:47:39 centos01 dockerd[2511]: time="2016-06-20T10:47:39.835257222-04:00" level=error msg="container status unavailable" error="context canceled" module=taskmanager task.id=2d6vttb3oaxav9ea28nyclhnm
Jun 20 10:47:39 centos01 dockerd[2511]: time="2016-06-20T10:47:39.836652306-04:00" level=warning msg="task updates not yet supported" module=taskmanager task.id=2d6vttb3oaxav9ea28nyclhnm
Jun 20 10:47:39 centos01 dockerd[2511]: time="2016-06-20T10:47:39.887494900-04:00" level=warning msg="task updates not yet supported" module=taskmanager task.id=2d6vttb3oaxav9ea28nyclhnm
Jun 20 11:07:30 centos01 dockerd[2511]: time="2016-06-20T11:07:30.211748038-04:00" level=error msg="Error updating node 8i07v3mx5ogdz1z68iide3yrn: rpc error: code = 4 desc = context deadline exceeded"
Jun 20 11:07:30 centos01 dockerd[2511]: time="2016-06-20T11:07:30.213148405-04:00" level=error msg="Handler for POST /v1.24/nodes/8i07v3mx5ogdz1z68iide3yrn/update returned error: rpc error: code = 4 desc = context deadline exceeded"
...
```

**Comment by tonistiigi** [comment] 2016-06-22 01:20
@jnoller This seems to be very similar to #23784, starting a manager that can't be connected back. If that's the case then lets close this and continue discussion in #23784.

**Comment by tiborvass** [comment] 2016-06-27 17:47
Closing as dupe of #23784 feel free to object in comments to have us reevaluate.

**Closed by tiborvass** 2016-06-27 17:47 UTC
Labels: kind/bug, version/1.12
