### ISSUE TITLE
docker commit data container with VOLUME

### ISSUE THREAD

**Issue by winggundamth** [docker/docker#6999] opened 2014-07-13 09:33 UTC
I'm not sure anyone has a way or requesting this but this is my use case.

I knew that there's a way to backup data container with --volumes-from, bind mount with host with tar as describe [here](https://docs.docker.com/userguide/dockervolumes/#backup-restore-or-migrate-data-volumes). But it should be good if Docker have a way to commit data container to image with data in Volumes. So I can use it for snapshot/backup data and push/pull it to transfer data across server.

Use case example

Dockerfile
```
VOLUME /home/web/app/uploads
```

On host
```
docker run -d app
docker run -d --volumes-from app app-data
docker commit --with-volumes=true app-data app-backup:201407131628
docker push app-backup #this will push only diff
```

On dev or another host
```
docker pull app-backup:201407131628
docker run --with-volumes=true -d app-data
docker run -d --volumes-from app-data app
```

Do you have a plan for this feature or any work around to do snapshot on volume?
I know this will be very complicated but it will be the very nice to have feature for sure :)

**Comment by Georges0013** [comment] 2015-03-30 14:16
there a proposal about it right here, but it's closed now : https://github.com/docker/docker/pull/8484

**Comment by kojiromike** [comment] 2015-03-31 01:42
**+1** I take it the black-belt label means this is going to be harder than breaking boards with one's chin?

**Comment by ain** [comment] 2015-06-22 22:23
:+1:

**Comment by soupdiver** [comment] 2015-06-26 10:59
+1

**Comment by graemian** [comment] 2015-06-26 11:08
+1

**Comment by thaJeztah** [comment] 2015-06-28 18:17
ping @icecrime @calavera wondering what the current position is on this proposal, also in light of the volume-drivers etc.

**Comment by Matvey-Kuk** [comment] 2015-07-08 13:54
+1!!!

**Comment by crosbymichael** [comment] 2015-07-08 16:43
I think going forward the work on top level volume objects will replace data containers and allow more advanced management of volumes with things like export.  

@cpuguy83 should have a PR somewhere or it is already merged in the experimental branch.

**Comment by cpuguy83** [comment] 2015-07-08 16:51
#14242 for top-level volumes.

**Comment by jfrazelle** [comment] 2015-07-10 20:34
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Closed by jfrazelle** 2015-07-10 20:34 UTC
Labels: exp/expert, kind/enhancement

**Comment by rakesh-james** [comment] 2015-08-10 09:46
Is this Fixed ? Still need to work round? Any one please update...

**Comment by sbrennion** [comment] 2016-01-22 11:43
I would also appreciate such a feature. Docker is flexible and there is not only one way to use it.
I want also being able to seperate the data in a volume, but perhaps at some point push the container with volume data in it , and deploy it

**Comment by moylop260** [comment] 2016-03-05 04:11
:+1:

**Comment by NZhuravlev** [comment] 2016-04-06 21:57
> Hello!
> We are no longer accepting patches to the Dockerfile syntax as you can read about here:
> Then from there, patches/features like this can be re-thought. Hope you can understand.

Well.. why would you even mention Dockerfile syntax? The issue is about **run** command. 

There is now direct answer to this issue, no merged PR, no opened PR, no info about why you can't do that, nothing.

@thaJeztah reopen this issue, maybe?

**Comment by omorillo** [comment] 2016-06-11 13:22
:+1:

**Comment by silviupanaite** [comment] 2016-06-16 17:44
+1

**Comment by cromat** [comment] 2016-06-27 13:49
:+1::

**Comment by flasheryu** [comment] 2016-07-26 08:01
+1... many thanks!

**Comment by Jackalx** [comment] 2016-08-05 15:58
+1 Will be great to have it

**Comment by SantoDE** [comment] 2016-08-20 07:29
+1 would really love to have it as well

**Comment by debbabi** [comment] 2016-10-21 10:02
+1

**Comment by snie2012** [comment] 2016-10-31 15:35
+1

**Comment by Ohmen** [comment] 2016-11-16 14:31
+1

**Comment by sujeetv** [comment] 2016-11-19 19:28
+1 This will very helpful with data science use cases to persist model related info and data.

**Comment by bronek89** [comment] 2016-11-26 20:00
+1

**Comment by FromZeus** [comment] 2017-01-13 21:56
+3

**Comment by likegun** [comment] 2017-02-09 09:46
+1

**Comment by zambotn** [comment] 2017-02-24 15:56
+1

**Comment by cvrod** [comment] 2017-02-27 14:49
+1

**Comment by linshenqi** [comment] 2017-03-08 02:17
+1

**Comment by ropnom** [comment] 2017-04-12 13:32
+1

**Comment by paulz1** [comment] 2017-04-18 14:35
+1

**Comment by neocortical** [comment] 2017-04-28 17:11
+1

**Comment by hmdhasani** [comment] 2017-05-13 08:46
+1

**Comment by rikvermeer** [comment] 2017-05-16 19:06
+1

**Comment by tabbi89** [comment] 2017-06-09 14:56
+1

**Comment by eeezyy** [comment] 2017-07-18 13:09
+1

**Comment by blachawk** [comment] 2017-07-29 14:26
+1

**Comment by lavvy** [comment] 2017-08-14 15:30
+1. How else can we snapshot volumes

**Comment by pokapow** [comment] 2017-08-28 14:39
+1

**Comment by qinshulei** [comment] 2017-09-01 03:33
+1

**Comment by evanfchan** [comment] 2017-09-03 21:12
+1

**Comment by farokojil** [comment] 2017-09-12 15:23
+1

**Comment by vguna** [comment] 2017-09-16 12:55
+1

**Comment by cdaringe** [comment] 2017-09-25 06:41
woo wee, that took forever to figure out why my `commit`s weren't "working" as expected.

@thaJeztah, or anyone else really, i am not necessarily seeking to commit a volume, but _remove_ the volume declaration, and perhaps recreate it later?

for instance, [couchdb ships with a VOLUME declared](https://github.com/klaemo/docker-couchdb/blob/29ed69965ed616a9d0df9a6ffa081773d86c78bc/1.6.1/Dockerfile#L100).  my objective is to ship a container with some _prebaked data in it_, but i can't run any migrations and recommit them because of this volume.

if there is a recipe for the operation, i'd love to hear it.

**Comment by taskinosman** [comment] 2017-10-15 11:49
+1

**Comment by thaJeztah** [comment] 2017-10-16 09:15
While I commented to be "positive" on this issue in the past, I've since gotten more insight into the complexity and design problems this feature would bring, and implementing this as a feature would be very problematic.

A _volume_ is really separate from a container that's using it; commiting that data into an image will unlikely be implemented. Let me first try to illustrate what's happening when using a volume;

If an image declares a `VOLUME`, or a `--volume` is used on `docker run`;

- docker creates a volume (if a non-existing volume is specified)
- if the volume is empty (and the `nocopy` option is not set), the data from the path inside the container (where the volume is mounted) is copied from the container to the volume.
- the container is started, and the volume is mounted inside the container (masking the files that are there)

When commiting a container to an image, only changes to the container's filesystem are committed; because the volume is not part of that, those files are not committed. This is the intended behavior for most use-cases; volumes are designed to;

- decouple data from the application (see bullets below)
- persist data beyond the container's lifecyle; this allows you to replace/upgrade a container, reuse the volume from before upgrading, and continue working with the data that was there
- similar; when deleting a container, your important data isn't lost (it's still in the volume)
- volumes prevent the overhead that copy-on-write filesystems cause (volume data is not using a copy-on-write filesystem)

#### Complexity

Implementing this feature would introduce a lot of additional complexity;

- Before the container is committed, it _must_ be stopped, otherwise data may still be written to the volume. Not only does this stop the container itself, this will likely affect other containers depending on it.
- The volume must be unmounted (this can cause a race condition; at this moment, the volume is no longer marked as "in use", thus can be deleted, for example when running `docker volume prune`)
- The data from the volume must be copied back into the container (how to deal with the existing files? Should those be _merged_, _deleted_?)
- Comitting a container now actually _modifies_ the container; starting the container again after committing is effectively starting a _different_ container than was stopped.
- When starting, the volume has to be attached/mounted again.
- Restarting a container leads to new ports to be assigned (in case of "random" published ports - `-p 80` or `-P`)


#### What use-case would be resolved by this feature?

The main use-case mentioned in this thread is to be able to ship an image that contains (default) data to use at runtime. There's a number of ways to realize this;

- As an example, the official MySQL image allows you to automatically intialize the database by providing scrips or SQL dumps in the `docker-entrypoint-initdb.d` directory (see the readme at https://hub.docker.com/_/mysql/). Other images  offer this feature as well
- Change the configuration of the software running inside the container to use a data-path outside of a path that's using a volume. At runtime, you can still use a volume through the `-v` or `--mount` flag.
- Consider using a separate image containing just the data to put in the volume; you can use that image to populate the volume. The advantage of this approach is that the data is decoupled from the image (so it's easier to upgrade the software running, without having to update the data)

There _are_ improvements to be made, for example: allow a `VOLUME` that was defined in a parent image to be unset; see https://github.com/moby/moby/issues/3465

With the information above, I think it'll be very unlikely this feature will get enough support among the maintainers to be implemented.

**Comment by gudge25** [comment] 2019-01-04 17:31
so  is there a way to commit docker image with files from volumes?

**Comment by eaglet3d** [comment] 2019-05-24 17:22
These manual overview steps might work:
Let's say you have an image (i.e. source image), and volume that mounts to a specific directory for the containers of that image.

1. Run a container 'WithVol' from the source image with the volume mounted.
2. Exec to create tar file of the volume directory on the container 'WithVol'
3. Copy the tar file locally
4. Run a container 'NoVol' from the same source image without the volume mounted.
5. Copy the tar file to the container 'NoVol'
6. Exec to extract the tar file to the target directory on the container 'NoVol'
7. Commit the container 'NoVol' to a target image
8. Create a new container from the target image
9. Exec to ls the files in the target directory on the new container
10. Confirm that all of the files are there.

Let me know how you make out.

**Comment by hemangjoshi37a** [comment] 2020-09-05 11:55
Is this already solved? Can we commit now with persistent data to a image?
Please help.

**Comment by lamba** [comment] 2020-11-08 17:10
Not solved. See the workaround described in the Jan 4, 2019 comment.

**Comment by sungaok** [comment] 2023-07-24 05:36
+1， could provide this feature, and leave users to decide how to use it.

**Comment by sungaok** [comment] 2023-07-24 05:46
could you provide me any idea, how to modify this feature in my own git code, I will try my own environment.
thks
@eaglet3d

**Comment by b4shtirk1n** [comment] 2023-10-18 12:07
+1

**Comment by CatIIIIIIII** [comment] 2023-11-23 10:40
+1
