### ISSUE TITLE
docker commit influxdb - no changes in result image

### ISSUE THREAD

**Issue by velocius** [docker/docker#31509] opened 2017-03-03 08:36 UTC
I have big problem with influxdb docker image. I want to save data, databases and tables to file, move file to another host and then restore container with full configuration and data. I tied:

1. `docker save / load`
2. `docker export / import`
3. `docker commit / run`
For influxdb official docker image commands above don't save changes... Everytime container was "clean" with only initial configuration. I have no idea what is wrong... command:

`docker diff`
only confirms that no changes was saved.

```
~# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
```~# docker info
Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 10
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 43
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-65-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.851 GiB
Name: ubuntuiw
ID: S6TZ:S7XE:GURF:GL55:OA6S:QLUI:YQLE:AV55:ZLVF:LT3B:T254:4HDE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-03-03 13:15
This is expected, and by design. The influxdb image uses a volume to store data that should persist beyond the container's lifecycle. The data itself is thus not stored in the container's filesystem, and won't be committed.

From the description of the image; https://hub.docker.com/_/influxdb/

> The InfluxDB image exposes a shared volume under /var/lib/influxdb

Having the data in a _volume_ separates the data from the actual container, which allows you to (for example) upgrade the container to a newer version, without loosing your data.

If you did not explicitly specify a volume for the container's data, an anonymous volume is created; to find the name of that volume, use `docker inspect`, and look in the `Mounts` section of the output, or (to output just that section);

```
docker inspect --format '{{json .Mounts}}' foo
[
  {
    "Type": "volume",
    "Name": "354341a0a01e9702b359e8787f46bd0130f44f4a59f1f85d38b54eb35eefc222",
    "Source": "/var/lib/docker/volumes/354341a0a01e9702b359e8787f46bd0130f44f4a59f1f85d38b54eb35eefc222/_data",
    "Destination": "/var/lib/influxdb",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  }
]
```

The name of the anonymous volume in this case is `354341a0a01e9702b359e8787f46bd0130f44f4a59f1f85d38b54eb35eefc222`, and will show up in `docker volume ls`;

```
DRIVER              VOLUME NAME
local               354341a0a01e9702b359e8787f46bd0130f44f4a59f1f85d38b54eb35eefc222
```

You can get the data from that volume by attaching a container to it, for example, see this issue https://github.com/docker/docker/issues/31417

For more information about volumes and persistent data, read this section of the documentation; https://docs.docker.com/engine/tutorials/dockervolumes/

I'll close this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-03-03 13:15 UTC
Labels: version/1.13
