### ISSUE TITLE
Can container and host share network namespace?

### ISSUE THREAD

**Issue by huikang** [docker/docker#17887] opened 2015-11-10 23:43 UTC
Hi,
I would like to create a network namespace from a container and then allow the network namespace available on the host. 

My container is started as
# docker run -it --cap-add=ALL --net=host --privileged --pid=host -v "/run:/run"  ubuntu bash

Then in the container I run "ip netns add net0"
From the host, I can see the network namespace, however, can not exec
in the network namespace.

[host #] ip netns exec net0 ip route
             setting the network namespace "net0" failed: Invalid argument

Does docker support this? If so, how can I achieve this? Thanks in advance.

- Hui

**Comment by huikang** [comment] 2015-11-11 00:04
@mavenugo could you help to take a look at this issue? Thanks.

**Comment by thaJeztah** [comment] 2015-11-12 21:44
@huikang perhaps this is a question that's better asked in the #docker-network IRC channel

**Comment by thaJeztah** [comment] 2015-11-12 21:45
I'm going to close this issue, because this is not a bug, but feel free to continue the discussion here after I've closed

**Closed by thaJeztah** 2015-11-12 21:45 UTC
