### ISSUE TITLE
command `tty` returns incorrect result  in `docker exec -t` 

### ISSUE THREAD

**Issue by laijs** [docker/docker#21766] opened 2016-04-05 12:46 UTC
```
[root@sbox ~]# docker exec -t $(docker run -d ubuntu sleep 1) tty
not a tty
```

**Output of `docker version`:**

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 28
 Running: 3
 Paused: 0
 Stopped: 25
Images: 2
Server Version: 1.10.1
Storage Driver: overlay
 Backing Filesystem: xfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.694 GiB
Name: sbox
ID: X3HY:KHO6:CAFD:R4D6:QIFV:MS5H:HLXS:4QT7:MYIR:4PM3:OJZV:JJEZ
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. docker exec -t $(docker run -d ubuntu sleep 1) tty
2.
3.

**Describe the results you received:**
not a tty

**Describe the results you expected:**
THE PATH OF THE TTY

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment] 2016-04-05 18:00
Looks like a duplicate of https://github.com/docker/docker/issues/8755. Please continue the discussion over there, but feel free to comment here if you think it's not a duplicate

**Closed by thaJeztah** 2016-04-05 18:00 UTC
