### ISSUE TITLE
Unable to start docker host on Mac with xhyve driver

### ISSUE THREAD

**Issue by mgcvnrpj** [docker/docker#32324] opened 2017-04-03 15:49 UTC
**Description**
I have used the xhyve to install the docker machine on mac laptop. The docker was up and running but once the laptop restarted the docker is not working. 

**Steps to reproduce the issue:**
1. brew install docker docker-compose docker-machine xhyve docker-machine-driver-xhyve
2. docker-machine create myDocker --driver xhyve --xhyve-experimental-nfs-share
3. eval "$(docker-machine env myDocker)"
4. restart the laptop

**Describe the results you received:**
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Describe the results you expected:**
docker host running and pull the image

**Additional information you deem important (e.g. issue happens only occasionally):**
docker was up and running till the restart of laptop.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.8
 Git commit:   c6d412e
 Built:
 OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
xhyve docker-machine-driver-xhyve
mac laptop - OS 10.12.3

**Comment by thaJeztah** [comment] 2017-04-03 15:54
This looks to be an issue with the `xhyve` driver for docker-machine, which should be reported in the that repository; https://github.com/zchee/docker-machine-driver-xhyve

However, I would recommend looking at Docker for Mac instead, which also uses xhyve (HyperKit), and should work out of the box, and give a much better experience; https://www.docker.com/docker-mac

I'll close this issue here, because this is not a bug in docker, but feel free to continue the conversation if you have questions

**Closed by thaJeztah** 2017-04-03 15:54 UTC
