### ISSUE TITLE
Unable to run certain images - issue with supervisord

### ISSUE THREAD

**Issue by ghost** [docker/docker#14166] opened 2015-06-24 19:49 UTC
# BUG REPORT INFORMATION

docker version:
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

docker info:
Containers: 9
Images: 230
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.19.3-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 3.41 GiB
Name: ip-10-89-12-242.eu-west-1.compute.internal
ID: 4PJ3:U5FE:Q3ZK:7LVO:KCJU:63AF:ARY2:PXTM:ZFR7:5DVK:HKPW:DRJ5

uname -a:
Linux  3.19.3-1.el7.elrepo.x86_64 #1 SMP Thu Mar 26 10:57:36 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):
AWS

List the steps to reproduce the issue:
1. docker run siomiz/chrome
2.
3.

Describe the results you received:
exec: "/usr/bin/supervisord": stat /usr/bin/supervisord: no such file or directoryFATA[0000] Error response from daemon: Cannot start container 71c44656160c5ed757a0aaa9aede5e613ff530b5a99a458aeb47a68939d5f620: exec: "/usr/bin/supervisord": stat /usr/bin/supervisord: no such file or directory 

Describe the results you expected:
Container runs

Provide additional info you think is important:

I am running into issues with supervisord, shows up a  few different images, an example below is from the registry called siomiz/chrome

[root@steve]# docker run siomiz/chrome
exec: "/usr/bin/supervisord": stat /usr/bin/supervisord: no such file or directoryFATA[0000] Error response from daemon: Cannot start container 71c44656160c5ed757a0aaa9aede5e613ff530b5a99a458aeb47a68939d5f620: exec: "/usr/bin/supervisord": stat /usr/bin/supervisord: no such file or directory 
[root@steve]# docker run siomiz/chrome

**Comment by thaJeztah** [comment] 2015-07-26 14:42
I was unable to reproduce this on 1.7.1, using the AUFS graph driver on Ubuntu. It's possible that this relates to overlay driver being used (which has some known issues around unix sockets)

Are you still able to reproduce this on an up to date docker release (currently, 1.7.1)?

**Comment by cpuguy83** [comment] 2015-09-15 15:35
Or 1.8.
There was an issue with being able to remove layers that should not be which is fixed in 1.8 as well.

Closing as this seems to have gone cold and is likely resolved already.
If you still have an issue, please ping.

**Closed by cpuguy83** 2015-09-15 15:35 UTC
