### ISSUE TITLE
[Flaky Test] TestPluginTrustedInstall

### ISSUE THREAD

**Issue by vdemeester** [docker/docker#31724] opened 2017-03-10 08:46 UTC
`DockerTrustSuite.TestPluginTrustedInstall` tends to be flaky on janky and experimental.

```
01:48:39 ----------------------------------------------------------------------
01:48:39 FAIL: docker_cli_plugins_test.go:302: DockerTrustSuite.TestPluginTrustedInstall
01:48:39 
01:48:39 docker_cli_plugins_test.go:320:
01:48:39     c.Assert(err, checker.IsNil)
01:48:39 ... value *errors.errorString = &errors.errorString{s:"\nCommand: /go/src/github.com/docker/docker/bundles/17.04.0-dev/binary-client/docker plugin enable 127.0.0.1:5000/dockercli/trusted-plugin-install:latest\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: error setting up propagated mount dir: invalid argument\n\n\nFailures:\nExitCode was 1 expected 0\nExpected no error\n"} ("\nCommand: /go/src/github.com/docker/docker/bundles/17.04.0-dev/binary-client/docker plugin enable 127.0.0.1:5000/dockercli/trusted-plugin-install:latest\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: Error response from daemon: error setting up propagated mount dir: invalid argument\n\n\nFailures:\nExitCode was 1 expected 0\nExpected no error\n")
01:48:39 
01:49:02 
01:49:02 ----------------------------------------------------------------------
```

/cc @anusha-ragunathan @tiborvass @vieux

**Comment by anusha-ragunathan** [comment] 2017-03-10 17:26
https://github.com/docker/docker/blob/master/plugin/manager_linux.go#L53 errors due to `mount --make-rshared` throwing  "invalid argument". It is flaky given that regular plugin installs (not trusted) works and even this test on CI passes majority of the time.

**Comment by anusha-ragunathan** [comment] 2017-03-10 17:48
Not sure if this is specific to a host. I found only one occurrence of this failing test on Docker-PRs CI. https://jenkins.dockerproject.org/job/Docker-PRs-experimental/31517/console

@vdemeester : Can you provide links to other failures, so we can see if there's a common host sympton?

**Comment by thaJeztah** [comment] 2017-03-15 19:58
Anusha https://github.com/docker/docker/pull/31862 https://jenkins.dockerproject.org/job/Docker-PRs/40395/console

**Comment by anusha-ragunathan** [comment] 2017-03-16 22:29
@thaJeztah : I think the fix I have will work for this issue. Once the PR is merged, lets wait atleast a week to ensure there are no more test failures on CI (I couldnt reproduce the issue locally)

**Closed** 2017-03-17 18:37 UTC
Labels: area/plugins, area/testing
