### ISSUE TITLE
docker swarm ,Can I update a specific container?

### ISSUE THREAD

**Issue by bimedu** [docker/docker#30270] opened 2017-01-19 08:51 UTC
docker swarm ,Can I update a specific container?
For example,：
```
[root@test1 ~]# docker service ps hello
ID            NAME     IMAGE       NODE   DESIRED STATE  CURRENT STATE          ERROR  PORTS
5ndkwic6uhpw  hello.1  alpine:3.2  test1  Running        Running 4 seconds ago         
qmn22gw9mbm2  hello.2  alpine:3.2  test1  Running        Running 3 seconds ago         
jp43yctpro4d  hello.3  alpine:3.2  test4  Running        Running 5 seconds ago         
u8uttd6qx2au  hello.4  alpine:3.2  test4  Running        Running 4 seconds ago         
5rsyu3qw534o  hello.5  alpine:3.2  test2  Running        Running 5 seconds ago         
01jeti2cy3gy  hello.6  alpine:3.2  test2  Running        Running 5 seconds ago
```

Now， the update operation is :
`docker service update hello --image alpine:3.3 `
but,After this operation, all nodes are upgraded to alpine:3.3
I  only want to update node:test1 to alpine:3.2,Is there a solution？thank you !

**Comment by thaJeztah** [comment] 2017-01-23 20:47
No, you can't update a single task, however, docker 1.13 adds a failure threshold and rollback option (see https://github.com/docker/docker/pull/26421), which allow you to (automatically) rollback an update if the update results in failures. In addition, the `--update-delay` ([and other `--update` flags](https://github.com/docker/docker/blob/v1.13.0/docs/reference/commandline/service_update.md)) allow you to control the amount of tasks that are updated simultaneously, and the time between tasks being updated

You may also be interested in https://github.com/stevvooe/sillyproxy, which describes how a blue/green deployment could look like in swarm mode.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation, or to open a feature request if you think improvements are needed in this area 👍

**Closed by thaJeztah** 2017-01-23 20:47 UTC
Labels: area/swarm
