### ISSUE TITLE
docker cp CONTAINER:/etc/resolv.conf returns an empty file

### ISSUE THREAD

**Issue by emsi** [docker/docker#9998] opened 2015-01-09 09:29 UTC
I wanted to check if a given container has made any changed to its own resolv.conf so I tried simple 
```docker cp CONTAINER:/etc/resolv.conf  .```
however this command produces an empty file.

To some degree I understand the special nature of the way the resolv.conf file is being treated under docker however returning an empty file without any message is a bit confusing.

**Comment by LK4D4** [comment] 2015-01-09 16:45
ping @cpuguy83
I think this was fixed by you? Or this is still impossible to cp /etc/resolv.conf?
@emsi You can use `docker exec CONTAINER cat /etc/resolv.conf` as workaround.

**Comment by cpuguy83** [comment] 2015-01-09 17:25
@lk4d4 no, since it's not in the container volume map.
We could keep a list of all the special mounts we do (like /etc/resolv.conf and /etc/hosts) and take that into account on the cp command. Probably would need to go with it after jlhawn's "cp" changes.

**Comment by apheleia** [comment] 2015-01-11 21:58
What should be the intended behavior if using `cp` for a special mount? Error or generating the file and then copying it to the host?

Would the following work?
- starting the container
- copying the file
- stopping the container

Or is it possible to generate the file with the same logic the container would use without actually starting the container?

**Comment by emsi** [comment] 2015-01-13 10:04
Preferably it should produce the actual file but an error with description and a workaround would be fine for now :)

**Comment by jfrazelle** [comment] 2015-02-27 00:40
ping @estesp sorry I see resolv.conf and automatically think of you

**Comment by cpuguy83** [comment] 2015-02-27 00:58
This is because /etc/resov.conf and /etc/hosts are mounted in. Definitely fixable.

**Comment by jfrazelle** [comment] 2015-02-27 01:09
wooohoo white-belt it is

**Comment by l0rd** [comment] 2015-03-26 19:19
#dibs

**Comment by nhsiehgit** [comment] 2015-03-27 18:17
Hi @l0rd 
Please remember to add a `closes` or `fixes` keyword once youve submitted your PR to help make tracking fixes easier. Thanks!

**Comment by vdemeester** [comment] 2015-03-29 11:07
I was working on this wiht @l0rd, so I did the pull request #11896.

**Closed** 2015-03-30 20:15 UTC
Labels: exp/beginner, kind/bug, status/claimed
