### ISSUE TITLE
Cannot delete files from wwwroot with Dockerfile

### ISSUE THREAD

**Issue by anthonychu** [docker/docker#22855] opened 2016-05-20 15:48 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 29
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1016.amd64fre.rs1_release_svc.160428-1819)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1.423 GiB
Name: WIN-CCH6NOM9R5L
ID: REUT:4Z3Z:JFDG:ENK6:2LSA:MBU2:TUSB:KCJO:UN27:3HDO:HF5G:YVDL
Docker Root Dir: C:\ProgramData\docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Windows Server Core 2016 TP5 in local Hyper-V VM

**Steps to reproduce the issue:**
1. Build this dockerfile
```
FROM microsoft/iis
RUN powershell remove-item c:\inetpub\wwwroot\iisstart.*
```

**Describe the results you received:**
If I run a container with this image, the `iisstart.*` files are still inside `c:\inetpub\wwwroot`

**Describe the results you expected:**
`iisstart.*` files should be removed from `c:\inetpub\wwwroot`

**Additional information you deem important (e.g. issue happens only occasionally):**
StackOverflow question: http://stackoverflow.com/q/37336884/3199781

cc: @jhowardmsft

**Comment by thaJeztah** [comment] 2016-05-20 16:05
Would it be possible that the wildcard is already picked up by `CMD.exe` (which is the shell in which `RUN` commands are executed.

Can you try using JSON notation, to make `powershell` the actual shell that's used? Something like

    RUN ["powershell", "remove-item", "c:\inetpub\wwwroot\iisstart.*"]

(untested)

**Comment by friism** [comment] 2016-05-20 16:21
I can reproduce with straight-up `cmd`:

```
FROM microsoft/iis
RUN del /Q /F c:\inetpub\wwwroot\*
RUN dir c:\inetpub\wwwroot
```

```
docker build --no-cache -t iis-delete .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM microsoft/iis
 ---> c26f4ceb81db
Step 2 : RUN del /Q /F c:\inetpub\wwwroot\*
 ---> Running in 70cb0fe8f76f
 ---> 78f0ff3ba824
Removing intermediate container 70cb0fe8f76f
Step 3 : RUN dir c:\inetpub\wwwroot
 ---> Running in aa5df71d8300
 Volume in drive C has no label.
 Volume Serial Number is C24E-29EB

 Directory of c:\inetpub\wwwroot

05/20/2016  09:20 AM    <DIR>          .
05/20/2016  09:20 AM    <DIR>          ..
05/05/2016  03:27 PM               703 iisstart.htm
05/05/2016  03:27 PM            99,710 iisstart.png
               2 File(s)        100,413 bytes
               2 Dir(s)  21,271,203,840 bytes free
 ---> 488d14766db2
Removing intermediate container aa5df71d8300
Successfully built 488d14766db2
```

**Comment by knom** [comment] 2016-05-31 14:10
+1

I've also tried things like..

RUN "rmdir C:\inetpub\wwwroot\ /S /Q"

Is IIS blocking this somehow?

**Comment by darrenstahlmsft** [comment] 2016-05-31 17:41
This was caused by a bug in hcsshim legacyLayerReader. It is fixed in https://github.com/Microsoft/hcsshim/pull/43. I'll revendor an updated hcsshim with the fix today.

**Closed** 2016-06-02 20:09 UTC
Labels: area/builder, group/windows, kind/bug, version/master
