### ISSUE TITLE
System freeze with docker and virtualbox and network bridge

### ISSUE THREAD

**Issue by rottmann** [docker/docker#10031] opened 2015-01-11 17:53 UTC
Fresh new installed Linux Mint 17.1
Kernel 3.13
Docker 1.4.1
Virtualbox 4.3.20 r96996

When start Virtubalbox the complete host system freeze.

When change the virtualbox network adapter from Bridge to NAT, everything work fine.

I dont know if it is a virtualbox or docker specific problem.

**Comment by jfrazelle** [comment] 2015-01-14 23:53
can you give us any logs, its hard to tell from just this information what exactly is the problem

**Comment by unclejack** [comment] 2015-01-16 18:56
@rottmann What's the host operating system? This doesn't sound like a Docker bug, it seems to be a  problem with your host.

**Comment by rottmann** [comment] 2015-01-16 19:46
Host Linux Mint
Client Windows, but the client did not boot. I change virtualbox to NAT and have no problem.

**Comment by rd-o** [comment] 2015-01-19 19:55
Same problem here.
Ubuntu 14.04
Virtualbox 4.3.10
Docker version 1.4.1, build 5bc2ff8

**Comment by mikaelhg** [comment] 2015-01-20 17:07
My colleague is hitting the same issue, on Ubuntu 14.04.

When he has Docker containers running, and then starts a VirtualBox Windows VM, his whole system freezes, and requires a hard reset with the power button. I haven't yet had the opportunity to reproduce.

**Comment by briceo** [comment] 2015-01-28 14:25
I am running into the same problem.  It seems like the VirtualBox guest doesn't really matter.

Host: Ubuntu 14.04
VirtualBox Guest: Empty System (was attempting to load a CoreOS system via PXE) with a bridged adapter
Docker Container: busybox

If I start the docker container first, followed by starting the VirtualBox VM, then the host system will freeze (can't switch to any terminal; only option: hit the reset button on host).

However, if I start the VirtualBox VM first, and then start the docker container, the host system does not freeze (while the VirtualBox VM is using a bridged adapter).

Additionally, if I set the VirtualBox VM to not have a bridged adapter (say NAT for example), then it does not matter what order the VM or docker container is started, the host system does not freeze.

**Comment by cpinkerton** [comment] 2015-02-19 14:56
I'm also seeing this problem.

Host: Ubuntu 14.04
Virtualbox: 4.3.20 (Windows 7 guest)
Docker: 1.0.1

If I start a Docker contains then try to boot a VM with Virtualbox my who system freezes up.

**Comment by vivia** [comment] 2015-02-26 11:10
Same problem here. Debian stable with backports kernel 3.16, but tried also 3.2. Virtualbox 4.3.22 but tried also 4.2.28. Docker version 1.5.0, build a8a31ef

Workaround: start virtualbox VM and then container.

Logs: http://paste.debian.net/hidden/fcd0f2ef/ http://paste.debian.net/hidden/4f5aae8b/

**Comment by jfrazelle** [comment] 2015-02-26 22:32
closing as dup of https://github.com/docker/docker/issues/4329

**Comment by mbentley** [comment] 2015-03-28 01:34
There is also a ticket here with VirtualBox:  https://www.virtualbox.org/ticket/13795

I hadn't realized that switching the networking from bridged to NAT prevents the problem from occurring.  That probably explains why I couldn't get someone else to reproduce it.  To add something else to what is going on, if I start a docker container with `--net=host` (e.g. - `docker run -d --net=host busybox:latest ping google.com`) and then start a VirtualBox VM, it works just fine.  It seems like there is a networking conflict that is causing the lockups.

**Comment by mbentley** [comment] 2015-03-30 16:19
When having someone else test, they attempted to use bridged networking and set it to be bridged over their wireless interface and it did not lock up.  He then switched to being bridged over eth0 and it locked up as expected.  He's running Debian Jessie with the default kernel `3.16.0-4-amd64`.  I was wondering if it was maybe something with specific hardware but that doesn't seem to be the case from what I can tell.

**Comment by bladedoyle** [comment] 2015-04-13 05:08
Seems like there is only a problem if docker is already using the interface that VBox tries to create the bridge on.  Based on the comments by @mbentley I installed a second interface and (as a workaround until this is fixed) am able to use one interface for Docker and the other for VBox.

**Comment by granteagon** [comment] 2015-05-03 03:50
I had this issue on Yosemite.

My solution:
- get latest virtual box app
- clear any invalid settings warnings from the settings menu

The cause of my problem was that all my ram 2GB was allocated to the VM by default and I also had to select the ICH9 chipset for my mac.

**Comment by mbentley** [comment] 2015-05-03 13:25
I don't think that was the same issue because this is when the host is running both VirtualBox and Docker containers.  Since Yosemite can't run the docker engine, it would likely be a different issue.

**Comment by Kryten0807** [comment] 2015-05-13 19:05
For what it's worth... my system (Ubuntu 14.04) experiences the same issue.

**However**: if you set the virtual box network to the `docker0` adapter, the system does NOT crash. Unfortunately, the VM can't connect to the host network that way. I also discovered that if you start the VM with the `docker0` adapter, then switch to `eth0`, it doesn't crash and does appear to work.

**Comment by diocles** [comment] 2015-06-10 10:36
Yesterday I sorted out kdump to get a log of the kernel panic, and filed it against virtualbox here:

- https://www.virtualbox.org/ticket/14188

**Comment by KDGundermann** [comment] 2015-06-27 10:39
I updated my system to latest release:
HP DL-380 G7
Ubuntu 14.04.2 LTS   
Kernel 3.13.0.55
Virtualbox 4.3.10-dfsg-1ubuntu5  r93012
lcx-docker-1.7.0

System completly hangs starting an VirtualBox machine when a docker image is running.

**Comment by jbogatay** [comment] 2015-06-30 18:20
Same Issue

**Comment by unclejack** [comment] 2015-06-30 18:24
Please keep in mind this is most certainly a VirtualBox problem. If that's not the case, it's VirtualBox triggering a kernel bug.

**Comment by jbogatay** [comment] 2015-06-30 19:13
Agreed, but I can 'track' the issue much easier here.   Also, the quick fix for me when I need virtualbox (which is rarely) is a simple 'systemctl stop docker' and it works.   I don't really want to reconfigure my network.

**Comment by nwknu** [comment] 2015-07-09 14:46
Same issue

Ubuntu 15.04
Docker version 1.7.0, build 0baf609
Virtualbox version 4.3.28
Kernel 3.19.0-22-generic

System freeze when starting a virtual machine with bridged networking if a container is running.

**Comment by Saschlong** [comment] 2015-07-09 16:58
Same here on two Workstations (almost identical hardware)

Ubuntu 14.04 LTS
Docker 1.0.1
Virtualbox 4.3.28
Kernel 3.13.0-57-generic

System freezes when Containers are running and a VM (Win7) with bridged networking (and PXE) start. It has to be bridged as we need to use Outlook and stuff. The Bridge goes to a different network card.

Seems to be related with PXE as I have some other VM (also Win7) with bridged networking which doesn't freeze the system. This one goes to the default network card.

When the PXE VM get's started before the Containers there is no freeze.

**Comment by jwalton** [comment] 2015-07-23 13:22
Same issue here.

**Comment by jwalton** [comment] 2015-07-23 14:25
Didn't notice until after a power failure, then when I couldn't get things to start, I re-imaged the entire box, only to run into the exact same problem.

Linux: 3.16.0-44-generic #59~14.04.1-Ubuntu SMP Tue Jul 7 15:07:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Docker version 1.7.1, build 786b29d
Virtualbox: 4.3.30r101610

**Comment by subzero79** [comment] 2015-07-28 03:10
Happens to me also, Debian 7.8 Linux nazbox 3.16.0-0.bpo.4-amd64,
Virtualbox 4.3.28-100309~Debian~wheezy

Workaround, Virtualbox is not able to pick virtual interface but is able to pick vlan interfaces, if you have a capable router, pick a vlan interface with eth0 as parent.

**Comment by diocles** [comment] 2015-07-30 16:16
Oracle have fixed the issue in Virtualbox trunk: https://www.virtualbox.org/ticket/13795 links to a test build of virtualbox 5.0 which I can confirm solves the problem. The fix will be in the next release of virtualbox 4.3.x and 5.x (probably 4.3.31 and 5.0.1 or 5.1?)

So this issue should be closed, as it's not a docker problem.

**Comment by jwalton** [comment] 2015-07-30 16:50
![](http://i.imgur.com/MlfBimB.jpg)

**Comment by thaJeztah** [comment] 2015-08-09 20:04
Thanks @diocles!  I'll close this issue (but feel free to comment if you thin I closed this by mistake)

**Closed by thaJeztah** 2015-08-09 20:04 UTC
Labels: exp/expert, kind/bug, system/networking
