### ISSUE TITLE
Docker trace on 1.12.1

### ISSUE THREAD

**Issue by freeseacher** [docker/docker#26361] opened 2016-09-07 04:40 UTC
**Output of `docker version`:**

```
% docker version
Client:
 Version:      1.12.1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   236317f
 Built:        Wed Aug 17 04:53:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   236317f
 Built:        Wed Aug 17 04:53:17 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 25
 Running: 22
 Paused: 0
 Stopped: 3
Images: 27
Server Version: 1.12.1-rc2
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: active
 NodeID: 884zsivfyq7al0o6ir445a7a2
 Is Manager: true
 ClusterID: 6xs12pbfkmbg98uehncund98r
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.1.46
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-21-generic
Operating System: Linux Mint 18
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.1 GiB
Name: shirokih-laptop
ID: N7R7:MH7D:AHH2:AHT2:24F6:T57V:OE27:YF4S:PNN2:EDWL:YXHM:6QYJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: freeseacher
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
just generic laptop with 
```
% lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah

Linux laptop 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I got laptop-mode-tools
```
ii  laptop-mode-tools                 1.68-3ubuntu1         all                   Tools for Power Savings based on battery/AC status
```

**Steps to reproduce the issue:**
1. launch docker. 
2. wait for 150 seconds

**Describe the results you received:**
everything works fine

**Describe the results you expected:**
sometimes docker dies with the following trace

**Additional information you deem important (e.g. issue happens only occasionally):**
[docker_trace.txt](https://github.com/docker/docker/files/458281/docker_trace.txt)

i got that issue at least three times a day.

**Comment by crosbymichael** [comment] 2016-09-07 17:06
Are you running out of memory on your laptop?  Do you have swap enabled?

**Comment by freeseacher** [comment] 2016-09-07 17:51
No. i have enough memory. 
some screenshots from local prometheus exporter

![pic_b2089b2089b2089](https://cloud.githubusercontent.com/assets/289277/18322687/f61eacf6-7544-11e6-9b8a-f2d084cb436b.png)
![pic_844f5844f5844f5](https://cloud.githubusercontent.com/assets/289277/18322691/fa0bb5ca-7544-11e6-9373-9b6ff5fa60d8.png)

**Comment by LK4D4** [comment] 2016-09-13 17:02
@freeseacher The message indicates that panic happened during malloc. I wonder if all your traces were about malloc and all points to same place. Also maybe makes sense to try released version of docker.

**Comment by thaJeztah** [comment] 2016-09-23 13:28
@freeseacher were you still able to reproduce this on the released version of 1.12.1?

**Comment by freeseacher** [comment] 2016-09-23 14:39
ou. sorry i'd missed the fact i am using beta channel. 
will try to reproduce that bug shortly.

**Comment by freeseacher** [comment] 2016-09-23 15:03
yep. after reinstalling i got 
```
сен 23 17:40:33 laptop systemd[1]: Reloaded Laptop Mode Tools.
сен 23 17:41:12 laptop wpa_supplicant[2399]: wlp4s0: WPA: Group rekeying completed with xxxxxxx [GTK=CCMP]
сен 23 17:43:06 laptop docker[20029]: panic: runtime error: slice bounds out of range
сен 23 17:43:06 laptop docker[20029]: goroutine 7358 [running]:
сен 23 17:43:06 laptop docker[20029]: panic(0x1a80320, 0xc82000e050)
сен 23 17:43:06 laptop docker[20029]:         /usr/local/go/src/runtime/panic.go:481 +0x3e6
сен 23 17:43:06 laptop docker[20029]: bytes.(*Buffer).grow(0xc82199bd80, 0x135, 0xc821d3c0c0)
сен 23 17:43:06 laptop docker[20029]:         /usr/local/go/src/bytes/buffer.go:112 +0x141
сен 23 17:43:06 laptop docker[20029]: bytes.(*Buffer).Write(0xc82199bd80, 0xc82311e000, 0x135, 0x8000, 0x75, 0x0, 0x0)
сен 23 17:43:06 laptop docker[20029]:         /usr/local/go/src/bytes/buffer.go:134 +0x4b
сен 23 17:43:06 laptop docker[20029]: github.com/docker/docker/daemon.(*limitedBuffer).Write(0xc82199bd80, 0xc82311e000, 0x135, 0x8000, 0x135, 0x0, 0x0)
сен 23 17:43:06 laptop docker[20029]:         /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/health.go:283 +0xae
сен 23 17:43:06 laptop docker[20029]: io.copyBuffer(0x7fc5e8030540, 0xc82199bd80, 0x7fc5e802b448, 0xc821c5ad40, 0xc82311e000, 0x8000, 0x8000, 0x8, 0x0, 0x0)
сен 23 17:43:06 laptop docker[20029]:         /usr/local/go/src/io/io.go:382 +0x2c9
сен 23 17:43:06 laptop docker[20029]: io.Copy(0x7fc5e8030540, 0xc82199bd80, 0x7fc5e802b448, 0xc821c5ad40, 0xc821c5ad40, 0x0, 0x0)
сен 23 17:43:06 laptop docker[20029]:         /usr/local/go/src/io/io.go:350 +0x64
сен 23 17:43:06 laptop docker[20029]: github.com/docker/docker/container.AttachStreams.func2(0x1d66410, 0x6, 0x7fc5e8030540, 0xc82199bd80, 0x7fc5e802b418, 0xc821c5ad40)
сен 23 17:43:06 laptop docker[20029]:         /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:433 +0x1cc
сен 23 17:43:06 laptop docker[20029]: created by github.com/docker/docker/container.AttachStreams
сен 23 17:43:06 laptop docker[20029]:         /usr/src/docker/.gopath/src/github.com/docker/docker/container/container.go:451 +0x3e0
сен 23 17:43:06 laptop systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
сен 23 17:43:06 laptop systemd[1]: docker.service: Unit entered failed state.
сен 23 17:43:06 laptop systemd[1]: docker.service: Failed with result 'exit-code'.
```
on 
```
% docker info 
Containers: 46
 Running: 0
 Paused: 0
 Stopped: 46
Images: 50
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: 884zsivfyq7al0o6ir445a7a2
 Is Manager: true
 ClusterID: 6xs12pbfkmbg98uehncund98r
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.1.46
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-21-generic
Operating System: Linux Mint 18
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.1 GiB
Name: shirokih-laptop
ID: N7R7:MH7D:AHH2:AHT2:24F6:T57V:OE27:YF4S:PNN2:EDWL:YXHM:6QYJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: freeseacher
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

just after 4 minutes after start

**Comment by thaJeztah** [comment] 2016-09-23 15:08
ping @mlaventure ^^

**Comment by cpuguy83** [comment] 2016-09-23 15:14
The panic on `limitedBuffer` is fixed on master.

**Comment by mlaventure** [comment] 2016-09-23 15:49
@cpuguy83 do you remember in which PR it was fixed?

**Comment by cpuguy83** [comment] 2016-09-23 15:51
#26596

**Comment by mlaventure** [comment] 2016-09-23 16:04
@cpuguy83 thanks!

Since this is already tracked by #26384, I'm closing this.

**Closed by mlaventure** 2016-09-23 16:04 UTC
Labels: area/runtime, kind/bug, version/1.12
