### ISSUE TITLE
aufs cannot start container

### ISSUE THREAD

**Issue by thenakliman** [docker/docker#9926] opened 2015-01-06 16:10 UTC
I had memory issue in my root partition therefor i moved content of /var/lib/docker in other partition and changed entry into /etc/default/docker but it did not work for me. I moved content back to /var/lib/docker but now i can not start any container from previous images but i can use images pulled after contents back to /var/lib/docker. Can you please help me. If their is any reference please provide.

[info] POST /v1.15/containers/create
[27c0cca9] +job create()
[27c0cca9] +job log(create, c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5, ubuntussh:14.04)
[27c0cca9] -job log(create, c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5, ubuntussh:14.04) = OK (0)
[27c0cca9] -job create() = OK (0)
[debug] server.go:1181 Calling POST /containers/{name:.*}/attach
[info] POST /v1.15/containers/c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5/attach?stderr=1&stdin=1&stdout=1&stream=1
[27c0cca9] +job container_inspect(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5)
[27c0cca9] -job container_inspect(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5) = OK (0)
[27c0cca9] +job attach(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5)
[debug] attach.go:137 attach: stdin: begin
[debug] attach.go:176 attach: stdout: begin
[debug] attach.go:215 attach: stderr: begin
[debug] attach.go:263 attach: waiting for job 1/3
[debug] server.go:1181 Calling POST /containers/{name:.*}/start
[info] POST /v1.15/containers/c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5/start
[27c0cca9] +job start(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5)
[info] No non localhost DNS resolver found in resolv.conf and containers can't use it. Using default external servers : [8.8.8.8 8.8.4.4]
[27c0cca9] +job allocate_interface(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5)
[27c0cca9] -job allocate_interface(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5) = OK (0)
[27c0cca9] +job log(start, c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5, ubuntussh:14.04)
[27c0cca9] -job log(start, c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5, ubuntussh:14.04) = OK (0)
no such file or directory[27c0cca9] +job release_interface(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5)
[27c0cca9] -job release_interface(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5) = OK (0)
[debug] attach.go:193 attach: stdout: end
[debug] attach.go:233 attach: stderr: end
[debug] attach.go:268 attach: job 1 completed successfully
[debug] attach.go:263 attach: waiting for job 2/3
[debug] attach.go:268 attach: job 2 completed successfully
[debug] attach.go:263 attach: waiting for job 3/3
[debug] attach.go:95 Closing buffered stdin pipe
[debug] attach.go:165 attach: stdin: end
[debug] attach.go:268 attach: job 3 completed successfully
[debug] attach.go:270 attach: all jobs completed successfully
[27c0cca9] -job attach(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5) = OK (0)
[27c0cca9] +job release_interface(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5)
[27c0cca9] -job release_interface(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5) = OK (0)
[27c0cca9] +job log(die, c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5, ubuntussh:14.04)
[27c0cca9] -job log(die, c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5, ubuntussh:14.04) = OK (0)
Cannot start container c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5: no such file or directory
[27c0cca9] -job start(c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5) = ERR (1)
[error] server.go:1207 Handler for POST /containers/{name:.*}/start returned error: Cannot start container c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5: no such file or directory
[error] server.go:110 HTTP Error: statusCode=500 Cannot start container c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5: no such file or directory
2015/01/06 21:34:02 Error response from daemon: Cannot start container c244ad33f08d1e67a3eac712030824abc49746170771896fe2fda3665abe2aa5: no such file or directory

**Comment by vbatts** [comment] 2015-01-08 19:34
@thenakliman `docker info` and `docker version` please. This could be a duplicate of https://github.com/docker/docker/issues/4036#issuecomment-69210353

**Comment by thenakliman** [comment] 2015-01-09 01:22
# docker info
Containers: 2
Images: 216
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 221
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
Username: thenakliman
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

#docker version
Client version: 1.3.0
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f
OS/Arch (client): linux/amd64
Server version: 1.3.0
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): c78088f

**Comment by jfrazelle** [comment] 2015-02-27 00:28
dup of https://github.com/docker/docker/issues/7554

**Closed by jfrazelle** 2015-02-27 00:28 UTC
Labels: /system/aufs
