### ISSUE TITLE
Change updated timezone of docker because of daylight

### ISSUE THREAD

**Issue by caneraydinbey** [docker/docker#28107] opened 2016-11-06 12:43 UTC
I did this in my local and for my local ubuntu, time is correct

> java -jar tzupdater.jar -l file:///home/Downloads/tzdata2016g.tar.gz

We have an app that has multiple containers.

> jhipster/jhipster-alerter  
> jhipster/jhipster-console   
> jhipster/jhipster-registry   
> mongo rabibtmq, 
> vimagick/pure-ftpd 
> and our company image about 1.8 gb.

Tİme is not correct for them. I couldnot manage to change jre of this app.

**Comment by justincormack** [comment] 2016-11-07 14:12
This is not a bug in docker, so I am going to close this issue. You might get better support on the docker forums https://forums.docker.com/ than here, as this is specifically for issues in the docker engine, while you want to update your containers.

**Closed by justincormack** 2016-11-07 14:12 UTC

**Comment by cpuguy83** [comment] 2016-11-07 14:18
@caneraydinbey Time is always handled in the kernel.
Containers get the time from the kernel, and then the userspace will apply a TZ offset from `/etc/timezone`. If the TZ offset is not correct then you would need to modify it via `/etc/timezone` (typically).
This should be handled the same way in a container or out.
