### ISSUE TITLE
question: how do you refresh the stdout when downloading images?

### ISSUE THREAD

**Issue by blacktop** [docker/docker#19253] opened 2016-01-12 05:36 UTC
I am writing some code to pull images via Go via the Docker API and am streaming the stdout, but it streams all the way down the stream and doesn't look as beautiful as when I use docker directly.

Thank you.

**Comment by thaJeztah** [comment] 2016-01-17 04:24
Thanks for opening @blacktop but this looks like a support question to me, not a bug or feature request.

Can you ask this question;

1. in the forums: https://forums.docker.com/
2. On StackOverflow https://stackoverflow.com/questions/tagged/docker
3. the docker-dev mailing list https://groups.google.com/forum/#!forum/docker-dev
4. in the #docker IRC channel on Freenode.

Make sure you add more information (some sample code, and a better description what's not working, because "not as pretty" may not be enough to understand what you're trying to achieve)

I'm going to close this issue, because this is not a bug or a feature request, but feel free to comment here after I've closed

**Closed by thaJeztah** 2016-01-17 04:24 UTC
