### ISSUE TITLE
ADD vs COPY causes ghost files

### ISSUE THREAD

**Issue by tiaanl** [docker/docker#26238] opened 2016-09-01 08:07 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 107
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 237
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-172-22-45-247
ID: JP75:CAYC:MIOQ:BB6C:XZHE:T26V:ROJG:WQXJ:DWJA:W4EE:QA5U:W3FS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on an EC2 instance in AWS.  Upgraded 14.04 to 16.04.

**Steps to reproduce the issue:**
1.  Bundle large amount of files into .tar and use ADD to copy and extract the files into the image.

The running apache or nginx inside the container doesn't see some of the files.  After I `exec` into the container and do a `find` or `ls` command over the files, then they become visible and get served normally.

I solved this problem by using `COPY` in stead to get the .tar file into the image and then just manually extracting the contents to where it should be.

As mentioned above, the image is being built on an Ubuntu EC2 instance in AWS, but then I build the same image on my local machine using Docker for Mac, it works perfectly.

**Comment by justincormack** [comment] 2016-09-01 16:48
Can you give a way to reproduce this? eg can you push an image with the problem?

**Comment by thaJeztah** [comment] 2016-10-29 07:43
Closing, because we need more info, but happy to reopen when provided

**Closed by thaJeztah** 2016-10-29 07:43 UTC
Labels: area/builder, kind/bug, status/more-info-needed, version/1.12
