### ISSUE TITLE
Ability to make container configuration changes on (running) containers

### ISSUE THREAD

**Issue by jorisvddonk** [docker/docker#3285] opened 2013-12-19 19:49 UTC
I'd like to be able to make configuration changes to a container (running or stopped). Specifically, any setting that can be set when starting a container with `docker run` should be able to be changed after-the-fact easily.

Rationale: 
When working with containers, it's inevitable that at one point you find yourself in a situation where you've spent an hour fiddling with a running container so that you can start using it (e.g. setting up a job system in a Jenkins container), only to realize that you forgot to make a certain configuration change way back when you ran the container using `docker run`. This tends to happen a lot with badly-documented images on the Index; if the image documentation doesn't tell me that I need to expose port 443 on my host system, I'm probably going to forget that.

In such cases, it would be great if I could make container configuration changes whilst the container is running, or after I've stopped the container manually. 

Unfortunately, docker doesn't currently seem to support this. Since you can't re-run a stopped container with `docker run`, you would need to commit the container to an image and then re-run it.

Unfortunately, `docker commit` clears the container's configuration, so you need to explicitly set a startup configuration using the -run commandline argument, unless you don't mind manually specifying the entrypoint/cmd et cetera each time you run this new image with `docker run` (which I don't think is very user friendly). As a workaround, you can inspect the container, copy the Config, and paste the config into the -run parameter of `docker commit`, but this isn't really user-friendly either.

**Comment by acollign** [comment] 2015-01-03 07:57
+1

**Comment by buptwangzhe** [comment] 2015-01-04 02:01
+1

**Comment by mbejda** [comment] 2015-01-04 02:53
+1

**Comment by jstrehan** [comment] 2015-01-04 03:18
+1

**Comment by nazar-pc** [comment] 2015-01-04 03:37
Even changing ports binding without need to create intermediate image and start new container would be great.

**Comment by blackfader** [comment] 2015-01-04 03:48
+1

**Comment by jinchizhong** [comment] 2015-01-05 11:21
+1

**Comment by jinchizhong** [comment] 2015-01-05 11:23
I want to change a container's base image. And keep all other settings.
It will be very very useful. When you have an new image.

**Comment by thaJeztah** [comment] 2015-01-05 23:37
@jinchizhong changing the base-image of a (running) container is *not* possible (even if this proposal is implemented). This proposal is only for changing a limited number of settings of a running container (for example, *rename* the container, expose/publish ports, add a link to a container)

**Comment by jstrehan** [comment] 2015-01-06 02:57
@thaJeztah  Would also like to have a flag while commit to copy settings of running container and bake it to image

**Comment by ds82** [comment] 2015-01-07 07:26
+1

**Comment by sspreitzer** [comment] 2015-01-09 16:19
+1

**Comment by LukeSwart** [comment] 2015-01-09 22:26
+1

**Comment by code-guru** [comment] 2015-01-18 18:00
+1
Need to add new volume and publish new ports after running a container

**Comment by windlessuser** [comment] 2015-01-22 17:23
+1

**Comment by IanWizard** [comment] 2015-02-04 19:22
I think it's safe to stop with the +1s.  I too find myself wanting this almost daily, but am some how able to divine the strength and serenity to not pollute the internet with yet another +1.  There's no doubt it's a desired and useful feature.  If you're not contributing to the conversation, please keep it to yourself.

**Comment by Mulkave** [comment] 2015-02-04 19:31
@IanWizard totally agree, the Subscribe button is right there for this specific reason.

**Comment by toby-griffiths** [comment] 2015-02-05 11:16
Thank you @IanWizard Was getting a little frustrated with all the email (he says, triggering another one)

**Comment by thefosk** [comment] 2015-04-28 21:05
+1

**Comment by IanWizard** [comment] 2015-04-28 23:53
I will slap the next person to +1 this...

**Comment by Nijikokun** [comment] 2015-04-29 00:13
+1....

**Comment by isanych** [comment] 2015-05-13 16:16
container renaming would be nice

**Comment by cpuguy83** [comment] 2015-05-13 16:41
@isanych container renaming was introduced in docker 1.5

**Comment by isanych** [comment] 2015-05-13 16:47
@cpuguy83, thanks, will ask to upgrade docker on server

**Comment by keshy** [comment] 2015-05-14 08:57
+1!!

**Comment by alasarr** [comment] 2015-05-14 10:10
+1!

**Comment by soupdiver** [comment] 2015-05-17 12:45
+1 I'm specifically want to change the restart policy of a running container

**Comment by kiorky** [comment] 2015-05-17 15:02
dup of my former #2045

**Comment by wiwiwa** [comment] 2015-05-26 05:10
+1!!

**Comment by hqhq** [comment] 2015-05-26 05:44
Dup of https://github.com/docker/docker/issues/6323, to all guys interested in this feature, I sent an approach #11442 months ago, it would be the first step to archive this goal. But sadly it's rejected and closed. I'm still trying to convince maintainers to reopen this.

**Comment by leisore** [comment] 2015-06-03 10:15
+1

**Comment by wufeifei** [comment] 2015-06-10 15:25
+1

**Comment by bradleypeabody** [comment] 2015-06-13 06:03
Would this be significantly easier to implement if the "running" requirement were removed?  Obviously I can't speak for the other people commenting here but for me it would be totally workable to only be able to modify the configuration of a stopped instance.  Adding another --link or -p or the restart policy - these are very common things when you are tweaking how you want a container set up.  But having to do this while it is running is probably significantly more difficult to implement and not needed in the majority of cases.  (For many (not all, but many) pieces of server software you can't change things like which database it uses or which ports it listens on without restarting it anyway.)

One other note on this: It sounds dumb but if you could reproduce the command line used to create a container, that would actually help a lot and would alleviate some of the pain of not having the functionality mentioned in this issue; i.e. while it would be great to be able to say run a command to say "add --link ... to this container"; the next best thing would be "show me the command i used to create this container, so i can commit and run it again with whatever changes".  I'm sure you guys are tired of hearing on this issue after so long, but I figured I'd offer those two cents as food for thought.

**Comment by rloomba** [comment] 2015-06-24 20:44
+1

**Comment by grubin1989** [comment] 2015-06-26 08:57
+1

**Comment by ierceg** [comment] 2015-06-28 14:05
+1

**Comment by cxshun** [comment] 2015-06-29 06:36
+1

**Comment by kunalkushwaha** [comment] 2015-06-30 02:58
+1

**Comment by anvaughan** [comment] 2015-07-03 14:18
+1

**Comment by jas99** [comment] 2015-07-04 15:27
+1

**Comment by sinchb** [comment] 2015-07-13 14:21
＋1

**Comment by osharav** [comment] 2015-07-16 06:50
+1

**Comment by lifei** [comment] 2015-07-17 08:28
+1

**Comment by MarcEtienneDery** [comment] 2015-07-20 14:51
+1

**Comment by aryounce** [comment] 2015-07-20 19:32
+1

**Comment by fizzy33** [comment] 2015-07-23 00:40
+1

**Comment by lamersons** [comment] 2015-07-28 12:21
+1

**Comment by charlesfg** [comment] 2015-07-29 18:23
+1

**Comment by IanWizard** [comment] 2015-07-29 18:26
Even the political threads don't hurt this much.

**Comment by charlesfg** [comment] 2015-07-29 18:34
I agree with @bradleypeabody .... The requirement of 'running' could be removed if this would make the implementation easier.  Would not be a great deal to stop the container.

**Comment by dpavlos** [comment] 2015-07-31 19:31
+1

**Comment by njd5475** [comment] 2015-08-01 00:33
+1

**Comment by dhilipkumars** [comment] 2015-08-13 13:56
+1

**Comment by oneasteriskone** [comment] 2015-08-17 17:22
+1

**Comment by simonrajan** [comment] 2015-08-20 06:26
+1

**Comment by ourway** [comment] 2015-08-22 21:53
+1

**Comment by cnaize** [comment] 2015-08-31 14:49
Hello!
What about progress in this issue?
Can I help to implement this?

**Comment by cpuguy83** [comment] 2015-08-31 14:51
There is an implementation here: #15078

**Comment by f3l1x** [comment] 2015-11-14 17:06
:+1:

**Comment by reduardo7** [comment] 2015-11-18 12:37
+1

**Comment by omerh** [comment] 2016-02-10 21:22
+1 
This command will be great:  docker remove -p 443:443 container_id

**Comment by cpuguy83** [comment] 2016-02-16 19:04
@omerh see `docker update` command in docker 1.10
It currently only supports modifying container resource constraints.
I'm not sure it will be expanded to support changing exposed ports... probably best to open as a specific issue.

I believe we should close this generic issue since `docker update` exists now for this purpose and anything it doesn't specifically support yet should be opened as separate issues.

ping @thaJeztah Do you agree?

**Comment by thaJeztah** [comment] 2016-02-16 19:12
I agree, each property that's added to `docker update` should be looked at separately, so there's no reason to keep a "general" issue open now that `docker update` is there.

**Closed by thaJeztah** 2016-02-16 19:12 UTC
Labels: kind/feature

**Comment by carloscarcamo** [comment] 2016-03-08 06:24
+1

**Comment by davbizz** [comment] 2017-01-28 15:30
+1

**Comment by yanislavb** [comment] 2017-02-09 13:17
+1
Are you think this configuration commands will enough for make changes?
I would like to change volume settings (such as "-v" arg), but I doesn't find it.
For make this change, I will create new persistent container, move all volumes to new container, and remove old.

Usage:  docker update CONTAINER [CONTAINER...]

Update configuration of one or more containers

  --blkio-weight          Block IO (relative weight), between 10 and 1000
  -c, --cpu-shares        CPU shares (relative weight)
  --cpu-period            Limit CPU CFS (Completely Fair Scheduler) period
  --cpu-quota             Limit CPU CFS (Completely Fair Scheduler) quota
  --cpuset-cpus           CPUs in which to allow execution (0-3, 0,1)
  --cpuset-mems           MEMs in which to allow execution (0-3, 0,1)
  --help                  Print usage
  --kernel-memory         Kernel memory limit
  -m, --memory            Memory limit
  --memory-reservation    Memory soft limit
  --memory-swap           Swap limit equal to memory plus swap: '-1' to enable unlimited swap
  --restart               Restart policy to apply when a container exits


Adressed for @cpuguy83 also for all Docker contributors. I think you fix this. Thanks :)

**Comment by thaJeztah** [comment] 2017-02-10 02:48
@yanislavb no `-v` is not supported on `docker update`. See my comment before this issue was closed; https://github.com/docker/docker/issues/3285#issuecomment-184836101

w.r.t `-v`, chances are little that that would be implemented; swapping a volume in a container, at runtime can have quite some side-effects, and creating a new container with a new volume / different volume is likely the best approach.

**Comment by yanislavb** [comment] 2017-02-10 20:48
Can I modify container configuration file?
If yes, where are these files located?

**Comment by thaJeztah** [comment] 2017-02-10 21:06
The container configuration file is in `/var/lib/docker/containers/<container-id>`, but I discourage editing those, as they are really designed as "internal" to docker. Updating the configuration will have no effect on a running container, and not sure what'll happen after updating those files.

If your container itself does not contain any stateful data, replacing a container is really the way to go (instead of updating the existing one).

**Comment by yanislavb** [comment] 2017-02-11 17:40
On my way, that's not really

**Comment by ngtuna** [comment] 2017-02-28 04:16
Hi there, I am curious if we can support `docker update` command to update the mapped ports to the running container. That would be really helpful.

**Comment by thaJeztah** [comment] 2017-02-28 11:39
@ngtuna see https://github.com/docker/docker/issues/21282

**Comment by thaJeztah** [comment] 2017-02-28 11:43
I am going to lock the conversation on this issue, to repeat my earlier comment https://github.com/docker/docker/issues/3285#issuecomment-184836101;

A `docker update` command has been implemented, but additional options that can be updated on a _running_ container should be looked at separately. If you think something should be added to the `docker update` command, please open a separate issue if it doesn't exist, and explain the use case (this is important to understand the reason why it's needed, and recreating the container is not an option).

Also note that docker services (in swarm mode) allow you to update service definitions, but mechanics are slightly different, because updating a service recreates containers.
