### ISSUE TITLE
[v1.10] slice bounds out of range

### ISSUE THREAD

**Issue by ColinHebert** [docker/docker#20299] opened 2016-02-13 10:58 UTC
I got this panic while starting a container:
```
time="2016-02-13T11:23:53.309234344Z" level=debug msg="POST /containers/20e994ce90ae4c160fc577e3022d356ee0f2a273293291297a6746796876c517/start" 
time="2016-02-13T11:23:53.309314735Z" level=debug msg="form data: {\"Binds\":[\"transmission:/docker:ro\"],\"LogConfig\":{\"Type\":\"json-file\"},\"PortBindings\":{\"873/tcp\":[{\"HostPort\":\"873\"}]},\"RestartPolicy\":{\"Name\":\"no
\"}}" 
time="2016-02-13T11:23:53.309374408Z" level=warning msg="DEPRECATED: Setting host configuration options when the container starts is deprecated and will be removed in Docker 1.12" 
2016/02/13 11:23:53 http: panic serving 192.168.99.1:53163: runtime error: slice bounds out of range
goroutine 725 [running]:
net/http.(*conn).serve.func1(0xc820bffb80, 0x7f5764286078, 0xc820e6eb00)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/docker/docker/volume/store.(*VolumeStore).Dereference(0xc82013f160, 0x7f5764240af8, 0xc820e62a00, 0xc82085c340, 0x40)
        /go/src/github.com/docker/docker/volume/store/store.go:301 +0x62b
github.com/docker/docker/daemon.(*Daemon).registerMountPoints(0xc820001c80, 0xc8210aec40, 0xc821500c00, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/volumes.go:148 +0xf26
github.com/docker/docker/daemon.(*Daemon).setHostConfig(0xc820001c80, 0xc8210aec40, 0xc821500c00, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:1356 +0x51
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc820001c80, 0xc8206a8731, 0x40, 0xc821500c00, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/start.go:38 +0x342
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStart(0xc820744990, 0x7f576428a998, 0xc820f1b350, 0x7f5764286868, 0xc820829ef0, 0xc820e537a0, 0xc820f1b050, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/router/container/container_routes.go:182 +0x114
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersStart)-fm(0x7f576428a998, 0xc820f1b350, 0x7f5764286868, 0xc820829ef0, 0xc820e537a0, 0xc820f1b0
50, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/router/container/container.go:50 +0x74
github.com/docker/docker/api/server.versionMiddleware.func1(0x7f576428a998, 0xc820f1b350, 0x7f5764286868, 0xc820829ef0, 0xc820e537a0, 0xc820f1b050, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/middleware.go:155 +0x83a
github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7f5764ad4068, 0xc82000f720, 0x7f5764286868, 0xc820829ef0, 0xc820e537a0, 0xc820f1b050, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/middleware.go:134 +0xfa
github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7f5764ad4068, 0xc82000f720, 0x7f5764286868, 0xc820829ef0, 0xc820e537a0, 0xc820f1b050, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/middleware.go:117 +0x4be
github.com/docker/docker/api/server.debugRequestMiddleware.func1(0x7f5764ad4068, 0xc82000f720, 0x7f5764286868, 0xc820829ef0, 0xc820e537a0, 0xc820f1b050, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/middleware.go:65 +0x969
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5764286868, 0xc820829ef0, 0xc820e537a0)
        /go/src/github.com/docker/docker/api/server/server.go:169 +0x2ad
net/http.HandlerFunc.ServeHTTP(0xc8207dfcc0, 0x7f5764286868, 0xc820829ef0, 0xc820e537a0)
        /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8207373b0, 0x7f5764286868, 0xc820829ef0, 0xc820e537a0)
        /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc82063fa70, 0x7f5764286868, 0xc820829ef0, 0xc820e537a0)
        /go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc82064daa0, 0x7f5764286868, 0xc820829ef0, 0xc820e537a0)
        /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820bffb80)
        /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by ColinHebert** [comment] 2016-02-13 11:00
Docker version:
```
core@MakkhBox ~ $ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   e21da33
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   e21da33
 Built:        
 OS/Arch:      linux/amd64
```

docker info:
```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 1.10.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.1-coreos
Operating System: CoreOS 955.0.0
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 493.4 MiB
Name: hostname
ID: EQW4:JUOZ:4UG2:RTLQ:2WLV:44AF:BIXX:WMHA:ZIGY:WWAQ:BOYB:OY3D
```

**Comment by ColinHebert** [comment] 2016-02-13 11:29
I updated the issue with more info (and reproduced within boot2docker and coreos alpha)

**Comment by sillyousu** [comment] 2016-02-14 11:40
I would like to fix this.
at https://github.com/docker/docker/blob/v1.10.1/volume/store/store.go#L301
When this `ref` is the last ref in the slice, `s.refs[v.Name()][i+1:]` cause a `slice bounds out of range`
```golang
	for i, r := range refs {
		if r == ref {
			s.refs[v.Name()] = append(s.refs[v.Name()][:i], s.refs[v.Name()][i+1:]...)
		}

```
#dibs

**Comment by thaJeztah** [comment] 2016-02-15 12:58
@ColinHebert do you have the steps to reproduce?

**Comment by cpuguy83** [comment] 2016-02-17 01:30
Looks like this is the same as #20378
Closing this since the other has a bit more info.

**Closed by cpuguy83** 2016-02-17 01:30 UTC
Labels: kind/bug, status/claimed
