### ISSUE TITLE
add documentation: Ubuntu installation 

### ISSUE THREAD

**Issue by d3netxer** [docker/docker#12002] opened 2015-04-01 19:32 UTC
I was following this page: https://docs.docker.com/installation/ubuntulinux/

After I installed docker but and ran the command: $ sudo docker run hello-world

It returned:

FATA[0000] Get http:///var/run/docker.sock/v1.17/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

can you please add a step in the instructions to run: service docker restart

This fixed the issue for me.

**Comment by ankushagarwal** [comment] 2015-04-02 01:03
Which ubuntu version are you using?
After I ran the instructions on ubuntu-14.04, docker daemon was automatically started after Step 3 : `$ wget -qO- https://get.docker.com/ | sh` and `sudo docker run hello-world` ran normally for me.

**Comment by ankushagarwal** [comment] 2015-04-02 01:10
Towards the end of the output of `wget -qO- https://get.docker.com/ | sh` do you see something like 

```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```
?

**Comment by Pensu** [comment] 2015-04-02 06:36
I am also having the same issues with vivid (ubuntu-15.04). docker service/daemon doesn't start automatically. You have to start it manually to get it working.

**Comment by ronthepanda** [comment] 2015-04-23 21:36
Same here for me. Docker service/daemon doesn't start automatically. I have to start it manually to get it working. I'm also on a clean Ubuntu 15.04

' docker --version` displays only `Docker version 1.6.0, build 4749651`

**Comment by thaJeztah** [comment] 2015-04-23 23:03
> docker --version displays only Docker version 1.6.0, build 4749651. On Ubuntu 14.04.2 LTS there were a lot more information. :)

Probably need to try `docker version` (not `--version`), which gives more output

**Comment by ronthepanda** [comment] 2015-04-23 23:07
Oh gosh my fault! you're right @thaJeztah :)

**Comment by thaJeztah** [comment] 2015-04-23 23:11
You're welcome! It *is* confusing, so nothing to be ashamed about :)

**Comment by asmaps** [comment] 2015-04-27 15:28
I seem to have the same problem with Ubuntu 15.04 (fresh installation). Probably it has something to do with the change from upstart to systemd as init system. I assume some startup scripts have to get adjusted to fix it.

Some info about my system:
```
asmaps@asmaps-x240 ~ % cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"

asmaps@asmaps-x240 ~ % docker ps
FATA[0000] Get http:///var/run/docker.sock/v1.18/containers/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

asmaps@asmaps-x240 ~ % sudo service docker status
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: http://docs.docker.com
```

After `sudo service docker start`:
```
% sudo service docker start
asmaps@asmaps-x240 ~ % sudo service docker status
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
   Active: active (running) since Mo 2015-04-27 17:25:44 CEST; 2s ago
     Docs: http://docs.docker.com
 Main PID: 7788 (docker)
   Memory: 324.0K
   CGroup: /system.slice/docker.service
           ├─7788 /usr/bin/docker -d -H fd://
           └─7867 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3141 -container-ip 172.17.0.1 -container-port 3141

Apr 27 17:25:45 asmaps-x240 docker[7788]: time="2015-04-27T17:25:45+02:00" level=info msg="-job allocate_interface(dbc101d4ec384ff26cd597ba34350adad8e842ae3697a3fbccd6c9bfb394947a) = OK (0)"
Apr 27 17:25:45 asmaps-x240 docker[7788]: time="2015-04-27T17:25:45+02:00" level=info msg="+job allocate_port(dbc101d4ec384ff26cd597ba34350adad8e842ae3697a3fbccd6c9bfb394947a)"
Apr 27 17:25:45 asmaps-x240 docker[7788]: time="2015-04-27T17:25:45+02:00" level=info msg="-job allocate_port(dbc101d4ec384ff26cd597ba34350adad8e842ae3697a3fbccd6c9bfb394947a) = OK (0)"
Apr 27 17:25:45 asmaps-x240 docker[7788]: time="2015-04-27T17:25:45+02:00" level=info msg="+job log(start, dbc101d4ec384ff26cd597ba34350adad8e842ae3697a3fbccd6c9bfb394947a, scrapinghub/devpi:latest)"
Apr 27 17:25:45 asmaps-x240 docker[7788]: time="2015-04-27T17:25:45+02:00" level=info msg="-job log(start, dbc101d4ec384ff26cd597ba34350adad8e842ae3697a3fbccd6c9bfb394947a, scrapinghub/devpi:latest) = OK (0)"
Apr 27 17:25:45 asmaps-x240 docker[7788]: time="2015-04-27T17:25:45+02:00" level=info msg="Loading containers: done."
Apr 27 17:25:45 asmaps-x240 docker[7788]: time="2015-04-27T17:25:45+02:00" level=info msg="docker daemon: 1.6.0 4749651; execdriver: native-0.2; graphdriver: aufs"
Apr 27 17:25:45 asmaps-x240 docker[7788]: time="2015-04-27T17:25:45+02:00" level=info msg="+job acceptconnections()"
Apr 27 17:25:45 asmaps-x240 docker[7788]: time="2015-04-27T17:25:45+02:00" level=info msg="-job acceptconnections() = OK (0)"
Apr 27 17:25:45 asmaps-x240 docker[7788]: time="2015-04-27T17:25:45+02:00" level=info msg="Daemon has completed initialization"

asmaps@asmaps-x240 ~ % docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

asmaps@asmaps-x240 ~ % docker ps
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS              PORTS                    NAMES
dbc101d4ec38        scrapinghub/devpi:latest   "/run.sh"           55 minutes ago      Up About a minute   0.0.0.0:3141->3141/tcp   devpi
```

**Comment by jjcomer** [comment] 2015-04-28 08:41
:+1: I'm seeing the same results as @asmaps on my fresh 15.04 install (also installed docker with the script)

**Comment by triptec** [comment] 2015-05-04 07:48
+1. I need to sudo service docker restart after every reboot

**Comment by vkorenev** [comment] 2015-05-04 13:34
I'm having the same issue on Ubuntu 15.04. After "sudo service docker restart" it starts working.

**Comment by echernyavskiy** [comment] 2015-05-10 01:19
Docker service won't start automatically for me either:

    > cat /etc/lsb-release 
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=14.04
    DISTRIB_CODENAME=trusty
    DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"


    > docker version
    Client version: 1.6.0
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): 4749651
    OS/Arch (client): linux/amd64
    FATA[0000] Get http:///var/run/docker.sock/v1.18/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

**Comment by thaJeztah** [comment] 2015-05-10 02:16
@tianon @jfrazelle are there still known issues with the install script? Given it's a mish-mash of versions reported above, I'm not sure all reporters are having the same issue. Anything you think could be worthy to check in order to debug?

**Comment by thaJeztah** [comment] 2015-05-10 02:16
@tianon @jfrazelle are there still known issues with the install script? Given it's a mish-mash of versions reported above, I'm not sure all reporters are having the same issue. Anything you think could be worthy to check in order to debug?

**Comment by jfrazelle** [comment] 2015-05-10 12:01
Seems to me it is the same problem. People need to run systemctl enable
docker for it to restart on 15.04 because it is systemd
This will be fixed in our new install script which uses the new rpms and
debs we have been working on.

**Comment by innovia** [comment] 2015-05-14 09:04
for me looking into /var/log/upstart/docker.io.log hint me in the direction apparmor was missing

so i did apt-get install apparmor followed by

sudo service docker restart

and it worked

**Comment by vkorenev** [comment] 2015-05-14 13:03
@innovia the issue with Ubuntu 15.04 is another one. Apparmor is installed. Systemd is used instead of Upstart.

**Comment by liquid** [comment] 2015-05-21 09:05
I am not familiar with the docker internals but it is clear to me that either docker itself sort one of its dependencies has a dependency on `apparmor` itself. Now, obviously having to manually install a package is non-ideal. If I could, I'd open a pull request and patch the debian/ubuntu package dependencies but I'm afraid I am not so great (at least not yet).

What I'm trying to say is, maybe instead of updating the documentation, the dependency tree should be fixed somehow.

**Comment by michielbdejong** [comment] 2015-05-29 09:40
Talking only about 15.04 (The [Ubuntu install instructions](https://docs.docker.com/installation/ubuntulinux/) do not describe how to install on 15.04, and just doing `wget -qO- https://get.docker.com/ | sh` will work only untill you reboot. So here is the solution for 15.04:

* Ubuntu 15.04 uses systemd, and the get.docker.com install script does not support this yet.
* After running `wget -qO- https://get.docker.com/ | sh`, run `docker version` to check that it's running. This should be the case.
* Now check if it is configured to run at startup, with `systemctl is-enabled docker`. If this shows 'disabled', then you need to run `systemctl enable docker`
* Reboot the server and run `docker version` again, to check that your `systemctl enable docker` fixed the problem.

**Comment by CristianCantoro** [comment] 2015-05-29 16:42
There is a fix for this problem for Ubuntu 15.04:
`sudo systemctl enable docker`
([source](http://blog.qax.io/how-to-fix-autostart-of-docker-on-ubuntu-1504/))

**Comment by jasonmendes** [comment] 2015-05-30 03:49
Wow, glad to found this issue, but ```sudo systemctl enable docker``` doesn't work for me, as it shows:

```
Synchronizing state for docker.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d docker defaults
Executing /usr/sbin/update-rc.d docker enable
Failed to execute operation: Operation not supported
```

and ```sudo systemctl is-enabled docker``` shows ```masked```.

**Comment by jasonmendes** [comment] 2015-05-30 04:06
Doh, so I unmasked both docker.service and docker.socket, but still trouble:

```
chronos@peppy:~$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
FATA[0000] Get http:///var/run/docker.sock/v1.18/version: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS? 
```

**Comment by jamespercy** [comment] 2015-05-30 05:25
sudo apt-get install apparmor and restarting the docker service worked for me

**Comment by thaJeztah** [comment] 2015-05-30 11:17
> sudo apt-get install apparmor and restarting the docker service worked for me

@jfrazelle ^^ I think you were working on that part as well (apparmor)?

**Comment by amarcionek** [comment] 2015-06-04 18:34
Ubuntu 15.04 comes with Docker 1.5 and worked out of the box. But after `wget -qO- https://get.docker.com/ | sh` it not longer did.  But `sudo systemctl enable docker` worked for me.

**Comment by vadviktor** [comment] 2015-06-06 16:38
I had this very issue -though remembered to solve it this way back from a while ago- I'd too recommend someone expert on Ubuntu and debian installs to fix up (at least warning users) to install Apparmor as a dependency, please. I am not keen on understanding high level bash scripts that's why I cannot create a PR myself, sorry.

**Comment by Jean85** [comment] 2015-06-25 08:22
`sudo systemctl enable docker` fixed it for me too.
I was on a clean 15.04 installation, I installed docker from get.docker.com
Thanks @michielbdejong

**Comment by greg0ire** [comment] 2015-06-26 16:39
Personally, I had to manually edit the `/lib/systemd/system/docker.service` and get rid `-H fd://` option. I have no idea what I am doing though.

**Comment by Jean85** [comment] 2015-06-26 16:44
I also had to edit `/lib/systemd/system/docker.service`, but just to edit the options.
That's because upstart implementations uses `/etc/default/docker.conf` to inject options as `DOCKER_OPTS`. Systemd implementations instead lacks something alike, but I think it merits an other issue about it.

**Comment by ankushagarwal** [comment] 2015-06-26 20:07
This is not a `docs/only` issue. This is an issue with the `docker-lxc` package for 15.04. The package install should take care of enabling docker daemon in systemd

**Comment by montanaflynn** [comment] 2015-07-02 22:36
I also ran into this issue on Ubuntu mate based on 15.04 although I actually prefer to not have docker run on startup so I just turn it on and off with `sudo service docker start` and `sudo service docker stop` as needed.

**Comment by JustKain** [comment] 2015-07-13 06:29
all so simple, first of all try to write ¨sudo docker run hello-world¨, daemon answer only to root user >_< i spend so many time read about this problem, try so many different methods to fix this, and after all I enter into var/run/docker/docker.socket and see ther daemon user is root, that´s why I try to write sudo before docker word and it´s work >_< 14.04 Ubuntu

**Comment by michielbdejong** [comment] 2015-07-15 12:49
Just confirmed that `systemctl enable docker` is still missing from the https://get.docker.com/ script when run on Ubuntu 15.04. Is someone working on this?

**Comment by ankushagarwal** [comment] 2015-07-15 13:38
@michielbdejong : Related discussion here : https://github.com/docker/docker/pull/14217

**Comment by thaJeztah** [comment] 2015-07-15 14:19
Also, changes are coming to the installation process; https://github.com/docker/docker/pull/13680

**Comment by ankushagarwal** [comment] 2015-07-15 14:28
@thaJeztah : I did not follow that PR, but does it address the issue of docker not starting automatically on Ubuntu 15.04 and above?

**Comment by thaJeztah** [comment] 2015-07-15 16:30
@ankushagarwal not fully sure; iiuc, updating the install scripts is part of that plan, and it's possible that automatic starting is part of that rewrite. *However*, I think I also read that making Docker start automatically on boot was intended to be a change/decision made by the user.

Erm, so in short: I don't know (yet) :blush:

**Comment by srcspider** [comment] 2015-07-21 08:15
Running 15.04, the `sudo systemctl enable docker` solution worked fine for me. No errors.

Restarted to make sure it worked and there's no problems.

@thaJeztah the [docs](http://docs.docker.com/linux/step_one/) should be updated to reflect the choice, if it's intended as a choice. It would also probably help to add to the docs the official instructions for making the docker command run with out `sudo`

**Comment by thaJeztah** [comment] 2015-07-21 17:28
@srcspider agreed!

**Closed** 2015-07-22 15:56 UTC
Labels: kind/writing

**Comment by PositiveAlex** [comment] 2015-09-28 13:50
on redhat

`chkconfig docker on'
`service docker restart`

'''
Stopping docker:                                           [FAILED]
Starting cgconfig service:                                 [  OK  ]
Starting docker:                                           [  OK  ]
'''

'''

[root@tmp]# docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from hello-world

535020c3e8ad: Pull complete
af340544ed62: Pull complete
hello-world:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:02fee8c3220ba806531f606525eceb83f4feb654f62b207191b1c9209188dedd
Status: Downloaded newer image for hello-world:latest

Hello from Docker.
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/userguide/

[root@tmp]#


'''
