### ISSUE TITLE
/etc/hosts not consistently populated when using --x-networking

### ISSUE THREAD

**Issue by kenjones-cisco** [docker/docker#18174] opened 2015-11-23 19:08 UTC
Description of problem:

When starting a small cluster of consul server nodes using docker-compose, the /etc/hosts file is not being populated with the containers in the compose file in docker v1.9.1 but in docker v1.9.0 it works with no issues.

`docker version`:
**works**
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

**does not work**
Client:
Version:      1.9.1
API version:  1.21
Go version:   go1.4.2
Git commit:   a34a1d5
Built:        Fri Nov 20 13:12:04 UTC 2015
OS/Arch:      linux/amd64

Server:
Version:      1.9.1
API version:  1.21
Go version:   go1.4.2
Git commit:   a34a1d5
Built:        Fri Nov 20 13:12:04 UTC 2015
OS/Arch:      linux/amd64

`docker info`:
**works**
Containers: 12
Images: 267
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 291
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 1.961 GiB
Name: entcon-dev
ID: 36BW:5BP7:WN6J:KRNT:WVUO:IG7I:7X3J:SCCU:ZLA5:MUI2:TV3Y:U4ES
WARNING: No swap limit support

**does not work**
Containers: 0
Images: 203
Server Version: 1.9.1
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 203
Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-62-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 1.961 GiB
Name: entcon-dev
ID: FI5A:ABI5:2UXI:LSID:OS76:FP5F:SI3H:IKUV:ENDV:CBIB:Z3UH:YN4N
WARNING: No swap limit support

`uname -a`:
Linux entcon-dev 3.13.0-65-generic #105-Ubuntu SMP Mon Sep 21 18:50:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Virtualbox v5

How reproducible:

Using the following docker-compose.yml file:

```
consul1:
  container_name: consul1
  build: .
  command: "agent -join consul3 -config-dir=/config"
  ports:
    - "8301"
    - "8302"
    - "8400"
    - "8500"
    - "8600"

consul2:
  container_name: consul2
  build: .
  command: "agent -join consul3 -config-dir=/config"
  ports:
    - "8301"
    - "8302"
    - "8400"
    - "8500"
    - "8600"

consul3:
  container_name: consul3
  build: .
  command: "agent -bootstrap-expect 3 -config-dir=/config"
  ports:
    - "8301"
    - "8302"
    - "8400"
    - "8500"
    - "8600"
```

Dockerfile:
```
FROM alpine:3.2

ENV CONSUL_VERSION 0.5.2
ENV GOMAXPROCS 2

RUN apk --update add curl ca-certificates \
   && curl -Ls https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-2.21-r2.apk > /tmp/glibc-
2.21-r2.apk \
   && apk add --allow-untrusted /tmp/glibc-2.21-r2.apk \
   && curl -Ls https://dl.bintray.com/mitchellh/consul/${CONSUL_VERSION}_linux_amd64.zip > /tmp/consul.zip \
   && cd /bin \
   && unzip /tmp/consul.zip \
   && chmod +x /bin/consul \
   && rm -rf \
       /tmp/glibc-2.21-r2.apk \
       /tmp/consul.zip \
       /var/cache/apk/*

EXPOSE 8300 8301 8301/udp 8302 8302/udp 8400 8500 8600 8600/udp
ENV DNS_RESOLVES consul
ENV DNS_PORT 8600

ENTRYPOINT ["/bin/consul"]

COPY consul.json /config/
```

config.json
```
{
 "data_dir": "/data",
 "server": true,
 "dns_config": {
       "allow_stale": true,
       "max_stale": "1s"
   }
}
```
Steps to Reproduce:
1. docker-compose build
2. docker-compose --x-networking up -d
3.

Actual Results:

on Docker v1.9.0:
```
Creating network "consul" with driver "None"
Creating consul3
Creating consul2
Creating consul1

 Name                Command               State                                                                                  Ports
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
consul1   /bin/consul agent -join co ...   Up      8300/tcp, 0.0.0.0:32782->8301/tcp, 8301/udp, 0.0.0.0:32781->8302/tcp, 8302/udp, 0.0.0.0:32780->8400/tcp, 0.0.0.0:32779->8500/tcp, 0.0.0.0:32778->8600/tcp, 8600/udp
consul2   /bin/consul agent -join co ...   Up      8300/tcp, 0.0.0.0:32777->8301/tcp, 8301/udp, 0.0.0.0:32776->8302/tcp, 8302/udp, 0.0.0.0:32775->8400/tcp, 0.0.0.0:32774->8500/tcp, 0.0.0.0:32773->8600/tcp, 8600/udp
consul3   /bin/consul agent -bootstr ...   Up      8300/tcp, 0.0.0.0:32772->8301/tcp, 8301/udp, 0.0.0.0:32771->8302/tcp, 8302/udp, 0.0.0.0:32770->8400/tcp, 0.0.0.0:32769->8500/tcp, 0.0.0.0:32768->8600/tcp, 8600/udp
```

on Docker v1.9.1:
```
Creating network "consul" with driver "None"
Creating consul3
Creating consul2
Creating consul1

                 Name                                   Command                                   State                                    Ports
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
consul1                                  /bin/consul agent -join co ...           Exit 1
consul2                                  /bin/consul agent -join co ...           Exit 1
consul3                                  /bin/consul agent -bootstr ...           Up                                       8300/tcp, 0.0.0.0:32772->8301/tcp,
                                                                                                                          8301/udp, 0.0.0.0:32771->8302/tcp,
                                                                                                                          8302/udp, 0.0.0.0:32770->8400/tcp,
                                                                                                                          0.0.0.0:32769->8500/tcp,
                                                                                                                          0.0.0.0:32768->8600/tcp, 8600/udp

Attaching to consul1
consul1 | ==> Starting Consul agent...
consul1 | ==> Starting Consul agent RPC...
consul1 | ==> Joining cluster...
consul1 | ==> lookup consul3: no such host
Attaching to consul2
consul2 | ==> Starting Consul agent...
consul2 | ==> Starting Consul agent RPC...
consul2 | ==> Joining cluster...
consul2 | ==> lookup consul3: no such host
vagrant@entcon-dev:~/entcon/authstore/consul$ sudo cat /var/lib/docker/containers/7a893027b200b11b33051f41c42e4e5f895d6bd2ff83941e10b255437b534e70/hosts
172.18.0.4      7a893027b200
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
vagrant@entcon-dev:~/entcon/authstore/consul$ sudo cat /var/lib/docker/containers/3e9caf3414c60d5bd0a8428f8a66b84ec0f3469949171d6e4c74c8f1a719bf0b/hosts
172.18.0.3      3e9caf3414c6
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Expected Results:

```
Creating network "consul" with driver "None"
Creating consul3
Creating consul2
Creating consul1

 Name                Command               State                                                                                  Ports
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
consul1   /bin/consul agent -join co ...   Up      8300/tcp, 0.0.0.0:32782->8301/tcp, 8301/udp, 0.0.0.0:32781->8302/tcp, 8302/udp, 0.0.0.0:32780->8400/tcp, 0.0.0.0:32779->8500/tcp, 0.0.0.0:32778->8600/tcp, 8600/udp
consul2   /bin/consul agent -join co ...   Up      8300/tcp, 0.0.0.0:32777->8301/tcp, 8301/udp, 0.0.0.0:32776->8302/tcp, 8302/udp, 0.0.0.0:32775->8400/tcp, 0.0.0.0:32774->8500/tcp, 0.0.0.0:32773->8600/tcp, 8600/udp
consul3   /bin/consul agent -bootstr ...   Up      8300/tcp, 0.0.0.0:32772->8301/tcp, 8301/udp, 0.0.0.0:32771->8302/tcp, 8302/udp, 0.0.0.0:32770->8400/tcp, 0.0.0.0:32769->8500/tcp, 0.0.0.0:32768->8600/tcp, 8600/udp
```

Additional info:

**Comment by kenjones-cisco** [comment] 2015-11-23 19:11
#https://github.com/docker/compose/issues/2445

**Comment by thaJeztah** [comment] 2015-11-23 21:57
ping @aboch @mavenugo @mrjana PTAL, possible regression in 1.9.1

**Comment by mavenugo** [comment] 2015-11-23 22:22
@kenjones-cisco can you please also provide the docker logs ?

**Comment by kenjones-cisco** [comment] 2015-11-23 22:34
@mavenugo  Just to clarify, are you referring to the docker daemon logs?

**Comment by mavenugo** [comment] 2015-11-24 00:19
@kenjones-cisco this seems very specific to the way compose launches the containers and the way consul expects the /etc/hosts resolution to have happened when it boots up.
Since we have 3 containers with 2 of them depending on `consul3` container and expects the /etc/hosts of consul1 and consul2 to be populated with consul3., It must be compose's responsibility to launch consul3 first before consul1 & consul2 so that the docker engine knows the availability of the container named consul3.

Also, consul's behavior on failing if /etc/hosts update is not done is very random and timing related.

the reproduction is completely random & I need to understand how Compose sequentialize the containers starts. With links, it is evident. But with the new networking feature, it isnt clear.

Lets have the discussion in the compose project as I dont see this as engine specific nor it seems like 1.9.1 related.

**Comment by mavenugo** [comment] 2015-11-24 00:24
I will close this for now and discuss the issue in compose project.
We can reopen this if we learn more.

**Closed by mavenugo** 2015-11-24 00:24 UTC
Labels: group/networking
