### ISSUE TITLE
init-system-helpers (>= 1.18~) but 1.14 is to be installed

### ISSUE THREAD

**Issue by nmarasoiu** [docker/docker#17063] opened 2015-10-15 13:59 UTC
Hi,

When trying to install docker-engine on ubuntu:

sudo apt-get install docker-engine
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker-engine : Depends: init-system-helpers (>= 1.18~) but 1.14 is to be installed
                 Depends: lsb-base (>= 4.1+Debian11ubuntu7) but 4.1+Debian11ubuntu6 is to be installed
                 Depends: libdevmapper1.02.1 (>= 2:1.02.99) but 2:1.02.77-6ubuntu2 is to be installed
                 Recommends: aufs-tools but it is not going to be installed
                 Recommends: cgroupfs-mount but it is not installable or
                             cgroup-lite but it is not going to be installed
                 Recommends: git

**Comment by phemmer** [comment] 2015-10-15 15:01
please provide information such as what distro & version you are using and what apt repo you are installing from (including which branches of the repo).

Using ubuntu trusty & the apt.dockerproject.org main & testing branches, I am unable to reproduce.

**Comment by thaJeztah** [comment] 2015-10-17 19:59
Did you uninstall the old packages and select the right repository? This sounds like the same issue as mentioned in this comment; https://github.com/docker/docker/pull/13680#issuecomment-122369631

**Comment by MaxPleaner** [comment] 2016-01-24 21:52
Got this too. Maybe a Linux installer script that does everything on the installation page would be helpful.

**Comment by justincormack** [comment] 2016-10-11 23:23
There is insufficient information to work out what is going on here, so I am closing this issue, which is very old. If you have trouble with the install scripts, please file a detailed issue report.

**Closed by justincormack** 2016-10-11 23:23 UTC
Labels: status/more-info-needed
