### ISSUE TITLE
Docker-hub: Automated build to follow tags from source repo

### ISSUE THREAD

**Issue by fruitl00p** [docker/docker#9561] opened 2014-12-08 10:56 UTC
Currently the docker hub allows following a single gittag to automatically build new images based on that tag. What i'd like to propose is that the hub follows not only a single tag, but _all_ tags. Thus if i push a new 'tag' to my repo, that tag is used for a new tag in my automatic built image.

This would allow far easier tag usage in automated builds since my public images have the same versions automatically as my source repo.

**Comment by jfrazelle** [comment] 2015-01-27 17:23
Hi all this is a great idea. But since it is hub specific and not a bug with anything in this repo I am going to close this, but feel free to email support@docker.com with your requests!

**Closed by jfrazelle** 2015-01-27 17:23 UTC

**Comment by wyaeld** [comment] 2015-01-27 20:21
Have already raised issues with support@docker.com over problems with automated builds.  Gets replies but no action.

**Comment by fakewaffle** [comment] 2015-04-10 03:47
Excellent idea. I emailed support too.

**Comment by wyaeld** [comment] 2015-04-10 05:08
@fakewaffle have had very little success with asking for any improvements to hub.  Seems like a waste of time, with little/no change or fixes delivered to automated building in over a year.  We got sick of waiting and have moved onto other infrastructures for build management.

**Comment by jpillora** [comment] 2015-05-05 05:39
:+1: on this

**Comment by pbelmann** [comment] 2015-05-13 09:29
:+1:  for this

**Comment by jpillora** [comment] 2015-05-13 11:44
@pbelmann Doesn't look like this will happen, I'm in the process of moving my repos over to https://quay.io by the CoreOS guys, much nicer Docker image repo, and with git tag -> docker tag tracking. Only change will be prepending `quay.io/` to `author/project`.

**Comment by pbelmann** [comment] 2015-05-13 12:04
@jpillora thanks for reporting this. Maybe I will switch to quay.io too.

**Comment by fakewaffle** [comment] 2015-05-13 16:29
Thanks @jpillora!

**Comment by jakirkham** [comment] 2015-06-02 03:08
They mention having added an internal issue related to this ( https://forums.docker.com/t/auto-builds-for-all-tags/682 ).

**Comment by mcortinas** [comment] 2015-06-14 19:24
:+1: +1 mailed to support@docker.com
