### ISSUE TITLE
"graph ID does not exist" after upgrading to Docker 1.10.0

### ISSUE THREAD

**Issue by rutsky** [docker/docker#20147] opened 2016-02-09 13:19 UTC
After upgrade from Docker 1.9.1 to 1.10.0 docker daemon fails to start with:

```
DEBU[0000] docker group found. gid: 999                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Using default logging driver json-file       
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] could not get checksum for "11421c362701030998085de69fbef501e4c16f91c2f008d820124808a4ddfe48" with tar-split: "open /var/lib/docker/graph/11421c362701030998085de69fbef501e4c16f91c2f008d820124808a4
ddfe48/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "061ea850f8e9bb47a04edf49c745c94a21dbb1a8bbced6bcd857c5fc699bc9a7" with tar-split: "open /var/lib/docker/graph/061ea850f8e9bb47a04edf49c745c94a21dbb1a8bbced6bcd857c5fc69
9bc9a7/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "139b1e2bbc4a79b9c26243c8e87dade698c0e96968ca27ab11d96b2599def1b9" with tar-split: "open /var/lib/docker/graph/139b1e2bbc4a79b9c26243c8e87dade698c0e96968ca27ab11d96b2599
def1b9/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "16dff810564c38f3197482e0300b4464ef737b1ff1280da8aca28fa4dc7e1d42" with tar-split: "open /var/lib/docker/graph/16dff810564c38f3197482e0300b4464ef737b1ff1280da8aca28fa4dc
7e1d42/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "2103b00b3fdf1d26a86aded36ae73c1c425def0f779a6e69073b3b77377df348" with tar-split: "open /var/lib/docker/graph/2103b00b3fdf1d26a86aded36ae73c1c425def0f779a6e69073b3b7737
7df348/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "29460ac934423a55802fcad24856827050697b4a9f33550bd93c82762fb6db8f" with tar-split: "open /var/lib/docker/graph/29460ac934423a55802fcad24856827050697b4a9f33550bd93c82762f
b6db8f/tar-data.json.gz: no such file or directory" 
DEBU[0000] could not get checksum for "0e57c609ffa9cf52d8e508554c2ca1e9af5a5dea226615ff58c421abfd4622d0" with tar-split: "stat /var/lib/docker/overlay/0e57c609ffa9cf52d8e508554c2ca1e9af5a5dea226615ff58c421ab
fd4622d0: no such file or directory" 
ERRO[0000] could not calculate checksum for "0e57c609ffa9cf52d8e508554c2ca1e9af5a5dea226615ff58c421abfd4622d0", "stat /var/lib/docker/overlay/0e57c609ffa9cf52d8e508554c2ca1e9af5a5dea226615ff58c421abfd4622d0:
 no such file or directory" 
DEBU[0000] layer 0e57c609ffa9cf52d8e508554c2ca1e9af5a5dea226615ff58c421abfd4622d0 took 0.00 seconds 
DEBU[0000] could not get checksum for "2daa80c72053337852233976b180d7aed5bc663c16d752156db428ead492073a" with tar-split: "open /var/lib/docker/graph/2daa80c72053337852233976b180d7aed5bc663c16d752156db428ead4
92073a/tar-data.json.gz: no such file or directory" 
ERRO[0000] could not calculate checksum for "2daa80c72053337852233976b180d7aed5bc663c16d752156db428ead492073a", "stat /var/lib/docker/overlay/2daa80c72053337852233976b180d7aed5bc663c16d752156db428ead492073a:
 no such file or directory" 
DEBU[0000] layer 2daa80c72053337852233976b180d7aed5bc663c16d752156db428ead492073a took 0.00 seconds 
DEBU[0000] could not get checksum for "306f4c89df6c1a547a4956cceeb070d838f5130190db70786ab55fa73ac83d03" with tar-split: "open /var/lib/docker/graph/306f4c89df6c1a547a4956cceeb070d838f5130190db70786ab55fa73a
c83d03/tar-data.json.gz: no such file or directory" 
ERRO[0000] could not calculate checksum for "306f4c89df6c1a547a4956cceeb070d838f5130190db70786ab55fa73ac83d03", "stat /var/lib/docker/overlay/306f4c89df6c1a547a4956cceeb070d838f5130190db70786ab55fa73ac83d03:
 no such file or directory" 

...

ERRO[0000] could not calculate checksum for "a26ec929cf27ba58caeb03672e0df9f20cbba6d3ae4fda4b77142eba38f300c9", "stat /var/lib/docker/overlay/a26ec929cf27ba58caeb03672e0df9f20cbba6d3ae4fda4b77142eba38f300c9:
 no such file or directory" 
DEBU[0000] layer a26ec929cf27ba58caeb03672e0df9f20cbba6d3ae4fda4b77142eba38f300c9 took 0.01 seconds 
ERRO[0000] could not calculate checksum for "9c33ab3dcc5c4e77ddfe08514232726758946c99a54f0609b9cf2919a16cacf8", "stat /var/lib/docker/overlay/9c33ab3dcc5c4e77ddfe08514232726758946c99a54f0609b9cf2919a16cacf8:
 no such file or directory" 
DEBU[0000] layer 9c33ab3dcc5c4e77ddfe08514232726758946c99a54f0609b9cf2919a16cacf8 took 0.01 seconds 
ERRO[0000] migration failed for f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 76b658ecb5644a4aca23b35de695803ad2e223da087d4f8015016021bd970169, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 4faa69f72743ce3a18508e840ff84598952fc05bd1de5fd54c6bc0f8ca835884, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 2103b00b3fdf1d26a86aded36ae73c1c425def0f779a6e69073b3b77377df348, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 51d14176e2627d70c2b15c7eb383119400bd095f2a866963c9daba104881fb5e, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 061ea850f8e9bb47a04edf49c745c94a21dbb1a8bbced6bcd857c5fc699bc9a7, err: open /var/lib/docker/graph/f0dde87450ec8236a64aebd3e8b499fe2772fca5e837ecbfa97bd8ae380c605e/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 72893ec31c4c6e0f7cbaa186c60fb624721ef4137aeeac56caf83bb2745dbc63, err: open /var/lib/docker/graph/72893ec31c4c6e0f7cbaa186c60fb624721ef4137aeeac56caf83bb2745dbc63/.migration-d
iffid: no such file or directory 

...

ERRO[0000] migration failed for b20334cbcde19e825e48cec618a8be745e253e3c59df013ff1cf8eedf4c382e3, err: open /var/lib/docker/graph/83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 139b1e2bbc4a79b9c26243c8e87dade698c0e96968ca27ab11d96b2599def1b9, err: open /var/lib/docker/graph/83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for 9c33ab3dcc5c4e77ddfe08514232726758946c99a54f0609b9cf2919a16cacf8, err: open /var/lib/docker/graph/83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4/.migration-d
iffid: no such file or directory 
ERRO[0000] migration failed for f9dc6fc192ce12a2a77fa13624554795af97e8b5031ca9e31fc2e9e2a85c283c, err: open /var/lib/docker/graph/83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4/.migration-d
iffid: no such file or directory 
ERRO[0000] migrate container error: open /var/lib/docker/containers/07369a90b03c3a2abf4f567b7b51a22eab45ec6b00d7320b6843a0d52abc839b/config.json: no such file or directory 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
FATA[0000] Error starting daemon: graph ID does not exist
```
(complete log: https://gist.github.com/rutsky/f8ed4e04b79063f1c7db)

First start of Docker after upgrading to 1.10.0 were terminated several times using `service stop docker`/`service start docker`.

I'm using Ubuntu 14.04 64-bit, with Linux 4.2.0 and `--storage-driver=overlay`.
Docker version: `Docker version 1.10.0, build 590d5108`
Docker info: unavailable (daemon fails to start)

Any idea why this happens and how this can be fixed?

**Comment by PAStheLoD** [comment] 2016-02-09 14:59
Hello!

Although I'm using btrfs backend, this looks like the same issue.


docker version:
```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64
```

```
ExecStart=/usr/bin/docker daemon -g /mnt/Brahma/docker -s btrfs --exec-opt native.cgroupdriver=cgroupfs -H fd://
```

Output via journalctl:
```
febr 09 15:54:36 strange systemd[1]: Starting Docker Application Container Engine...
febr 09 15:54:36 strange systemd[1]: Starting Docker Application Container Engine...
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.237217146+01:00" level=error msg="could not calculate checksum for \"0e3324cba82d3db34c7b1ea14bddb2ea65dd0ef39f901238ac2fb8f892f19b8c\", \"stat /mnt/Brahma/docker/btrfs/subvolumes/0e3324cba82d3db34c7b1ea14bddb2ea65dd0ef39f901238ac2fb8f892f19b8c: no such file or directory\""
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.237322929+01:00" level=error msg="could not calculate checksum for \"3226f261f1af5ce7c595a21bc04b0cdd56f2dae5c510f247c595f1913597b293\", \"stat /mnt/Brahma/docker/btrfs/subvolumes/3226f261f1af5ce7c595a21bc04b0cdd56f2dae5c510f247c595f1913597b293: no such file or directory\""
...
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.238505483+01:00" level=error msg="could not calculate checksum for \"fe0f25a3896a7ab6ff8e1c7a308b6206b6b46ac7033233a65543a00e60eaa3ec\", \"stat /mnt/Brahma/docker/btrfs/subvolumes/fe0f25a3896a7ab6ff8e1c7a308b6206b6b46ac7033233a65543a00e60eaa3ec: no such file or directory\""
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.238901118+01:00" level=error msg="could not calculate checksum for \"1054444c079138bc4271aa1cba4abb3bcc62fff4d17ab1cf576271ecf0e37a27\", \"stat /mnt/Brahma/docker/btrfs/subvolumes/1054444c079138bc4271aa1cba4abb3bcc62fff4d17ab1cf576271ecf0e37a27: no such file or directory\""
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.238901118+01:00" level=error msg="could not calculate checksum for \"1054444c079138bc4271aa1cba4abb3bcc62fff4d17ab1cf576271ecf0e37a27\", \"stat /mnt/Brahma/docker/btrfs/subvolumes/1054444c079138bc4271aa1cba4abb3bcc62fff4d17ab1cf576271ecf0e37a27: no such file or directory\""
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.241867487+01:00" level=error msg="migration failed for ed0fd609d9d4722e7a129d13dd84d516e8087c975858712c275af047b702816f, err: open /mnt/Brahma/docker/graph/ed0fd609d9d4722e7a129d13dd84d516e8087c975858712c275af047b702816f/json: no such file or directory"
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.241867487+01:00" level=error msg="migration failed for ed0fd609d9d4722e7a129d13dd84d516e8087c975858712c275af047b702816f, err: open /mnt/Brahma/docker/graph/ed0fd609d9d4722e7a129d13dd84d516e8087c975858712c275af047b702816f/json: no such file or directory"
...
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.262118006+01:00" level=error msg="migration failed for 0e62ff3150961aa4cb0083c0ee1df3cc33fed347a78dd358c625d40023d0876e, err: open /mnt/Brahma/docker/graph/ed0fd609d9d4722e7a129d13dd84d516e8087c975858712c275af047b702816f/json: no such file or directory"
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.262128331+01:00" level=error msg="migration failed for f3935edf3ec7858a7f908e6fa089862091384f9f1400660b0d1505548e12381e, err: open /mnt/Brahma/docker/graph/ed0fd609d9d4722e7a129d13dd84d516e8087c975858712c275af047b702816f/json: no such file or directory"
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.262138511+01:00" level=error msg="migration failed for fe0f25a3896a7ab6ff8e1c7a308b6206b6b46ac7033233a65543a00e60eaa3ec, err: open /mnt/Brahma/docker/graph/ed0fd609d9d4722e7a129d13dd84d516e8087c975858712c275af047b702816f/json: no such file or directory"
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.263375182+01:00" level=error msg="image not migrated "
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.263507550+01:00" level=error msg="image not migrated "
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.263645062+01:00" level=error msg="image not migrated "
...
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.268026136+01:00" level=error msg="image not migrated "
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.268130002+01:00" level=error msg="image not migrated "
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.268259356+01:00" level=error msg="image not migrated "
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.269112601+01:00" level=info msg="migrated container fb573f677073375e8444440591fe143bbec689268d3d2818d9c22380fce7f611 to point to sha256:7f72b25c8ab50a4300f4b6af8059fa3de15f12667f411776bc0a4f3dceeb988f"
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.267937697+01:00" level=error msg="image not migrated "
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.268026136+01:00" level=error msg="image not migrated "
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.268130002+01:00" level=error msg="image not migrated "
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.268259356+01:00" level=error msg="image not migrated "
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.269112601+01:00" level=info msg="migrated container fb573f677073375e8444440591fe143bbec689268d3d2818d9c22380fce7f611 to point to sha256:7f72b25c8ab50a4300f4b6af8059fa3de15f12667f411776bc0a4f3dceeb988f"
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.284426227+01:00" level=fatal msg="Error starting daemon: graph ID does not exist"
febr 09 15:54:36 strange docker[23447]: time="2016-02-09T15:54:36.284426227+01:00" level=fatal msg="Error starting daemon: graph ID does not exist"
febr 09 15:54:36 strange systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
febr 09 15:54:36 strange systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
febr 09 15:54:36 strange systemd[1]: Failed to start Docker Application Container Engine.
```

Expected result:
* docker starts, unmigrated containers are unaccessible
* if docker does not start, steps to resolve the issue should be provided (delete this, edit that, etc.)

**Comment by thaJeztah** [comment] 2016-02-09 15:13
ping @tonistiigi, ptal

**Comment by tiborvass** [comment] 2016-02-09 16:25
@rutsky @PAStheLoD do you have instructions for reproducing easily ?

**Comment by cpuguy83** [comment] 2016-02-09 16:27
I have a feeling this is for images that got "device or resource busy" when trying to remove them at some point.

**Comment by tonistiigi** [comment] 2016-02-09 16:36
@rutsky If you still have your old graph dirs can you send me all files in `/var/lib/docker/containers/07369a90b03c3a2abf4f567b7b51a22eab45ec6b00d7320b6843a0d52abc839b` and check if you have directories `/var/lib/docker/overlay/07369a90b03c3a2abf4f567b7b51a22eab45ec6b00d7320b6843a0d52abc839b` and ``/var/lib/docker/overlay/07369a90b03c3a2abf4f567b7b51a22eab45ec6b00d7320b6843a0d52abc839b-init`. Can you also check the next ID in `/var/lib/docker/containers` after `07369...`.

@cpuguy83 The error comes from migrating a container configuration, when the rwlayer does not exists for the container. The btrfs case also seems to have container configuration that points to a non-existing image.

@rutsky @PAStheLoD Is it possible you manually deleted some files under `/var/lib/docker` in the past. For example layer data under `overlay/btrfs` or image configurations under `graph/`.

**Comment by rutsky** [comment] 2016-02-09 18:49
> @rutsky @PAStheLoD Is it possible you manually deleted some files under /var/lib/docker in the past. For example layer data under overlay/btrfs or image configurations under graph/.

Some time ago I "switched" from `aufs` to `overlay` storage driver by adding `--storage-driver=overlay` and reimporting my old images. My old containers/images were vanished at this point, but some info from them are most probably were left (looks like this is a point when I shoot myself in a foot, but according to available on the Internet articles of how to do switch from one storage driver to another I'm not the only one and definitely not the last one).

> @rutsky If you still have your old graph dirs can you send me all files in `/var/lib/docker/containers/07369a90b03c3a2abf4f567b7b51a22eab45ec6b00d7320b6843a0d52abc839b`
Here you go: http://filebin.ca/2WOt1R8ankd5/graph.tar.gz

> check if you have directories `/var/lib/docker/overlay/07369a90b03c3a2abf4f567b7b51a22eab45ec6b00d7320b6843a0d52abc839b` and `/var/lib/docker/overlay/07369a90b03c3a2abf4f567b7b51a22eab45ec6b00d7320b6843a0d52abc839b-init`

No, I don't have them. But I have `aufs/layers/07369a90b03c3a2abf4f567b7b51a22eab45ec6b00d7320b6843a0d52abc839b-init` --- looks like this is a leftover of my "switching" to `overlayfs`.

**Comment by tonistiigi** [comment] 2016-02-09 18:54
@rutsky Thanks for the extra info. I can reproduce with switching the graph driver.

**Comment by rutsky** [comment] 2016-02-09 19:10
Looks like I "fixed" issue in my env: Docker daemon now starts.
What I have done:

1. I noticed that these folders were empty in `/var/lib/docker/containers`:

    `07369a90b03c3a2abf4f567b7b51a22eab45ec6b00d7320b6843a0d52abc839b`,
    `5c399f7720fee95b8220d23574d1360f9feaeef6d3c05991ac27cfd22064fa7e`
    `ce5dd2c55ad70a6785bd2f7e1b53f077d83d365adef742e18969b06691078b44`
    `d3a699d5c81778ceb3826ca075d44cb1a4d71133e3eeb6f974b373d0228fd274`

    I removed them.

2. These ids were referenced in `/var/lib/docker/linkgraph.db`, I removed them from it:

    ```
sqlite3 linkgraph.db "delete from edge where entity_id like '07369a90b03c3a2abf4%'"
sqlite3 linkgraph.db "DELETE from entity where id like '07369a90b03c3a2abf4%'"
sqlite3 linkgraph.db "delete from edge where entity_id like '5c399f7720fee95b8220d23574d1%'"
sqlite3 linkgraph.db "DELETE from entity where id like '5c399f7720fee95b8220d23574d1%'"
sqlite3 linkgraph.db "delete from edge where entity_id like 'ce5dd2c55ad70a6785bd%'"
sqlite3 linkgraph.db "DELETE from entity where id like 'ce5dd2c55ad70a6785bd%'"
sqlite3 linkgraph.db "delete from edge where entity_id like 'd3a699d5c81778ceb3%'"
sqlite3 linkgraph.db "DELETE from entity where id like 'd3a699d5c81778ceb3%'"
```

3. Removed id `'0'` from `linkgraph.db` (I assumed that this is an error to have such, but actually it was recreated after Docker daemon were restarted):

    ```
sqlite3 linkgraph.db "DELETE from entity where id = '0'"
sqlite3 linkgraph.db "delete from edge where entity_id = '0'"
```

4. During steps above I tried to start Docker daemon multiple times and at some point it just started. I think it's not really related to previous steps, but probably with each daemon start attempt more containers were migrated, until all containers were finally migrated.
Here is log after Docker daemon started: https://gist.github.com/rutsky/cdbbc4caf313b2561c92

**Comment by PAStheLoD** [comment] 2016-02-10 00:45
Ah, sorry for the late reply, but yes, I switched from overlay to btrfs. However, I thought I wiped /var/lib/docker clean during that change. (Or probably I just deleted the overlay folder, because even though I copied the docker folder from ext4 to btrfs docker understandably did not find/migrate the layers to subvolumes.)

Thanks for the quick patch.

**Comment by tiborvass** [comment] 2016-02-10 00:47
Github should have closed this when the patch was merged... so closing.

**Closed by tiborvass** 2016-02-10 00:47 UTC
Labels: kind/bug, priority/P0

**Comment by rutsky** [comment] 2016-02-10 02:33
@tonistiigi can you confirm, that to workaround this issue on 1.10.0 it's enough to just restart Docker daemon N times, until it will finally start?

**Comment by tonistiigi** [comment] 2016-02-10 20:49
@rutsky Yes, for this case it seems to work. The error appears after the new container record has already been created so next time the container that previously generated the error is skipped.

**Comment by ReSearchITEng** [comment] 2016-03-09 14:03
I have simply upgraded (manually changed docker binary on a RH 7.2) from the default (latest RH) 1.8.2 to 1.10.2, build c3959b1 (which I manually downloaded today from docker website)
Note: I use lvms. Also everything was working fine for many months, till now, when I upgraded.

First start of docker (after upgrade) took ~1+ hours and was apparently rehashing all layers, and afterwards it crashed. This is the error in the logs whenever I try to systemctl start docker:

```
/usr/bin/docker daemon --selinux-enabled --storage-opt dm.basesize=40G --storage-opt dm.datadev=/dev/vg_graph/data --storage-opt dm.metadatadev=/dev/vg_graph/metadata --storage-opt dm.basesize=40G [......... not relevant .......]
Mar 09 15:55:46 x systemd[1]: Starting Docker Application Container Engine...
Mar 09 15:55:46 x docker[29351]: time="2016-03-09T15:55:46.488530210+02:00" level=warning msg="devmapper: Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option"
Mar 09 15:55:46 x docker[29351]: time="2016-03-09T15:55:46.554050675+02:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
Mar 09 15:55:47 x docker[29351]: time="2016-03-09T15:55:47.543427724+02:00" level=error msg="could not calculate checksum for \"1a0621b25a59608a6de053efbb889f4bf36e696af21e412533b426fc029c3c2f\", \"open /dev/mapper/docker-253:1-135510678-1a0621b25a59608a6de053efbb889f4bf36e696af21e412533b426fc029c3c2f: no such file or directory\""
```

I followed the steps above, and I did a delete the specific layer from linkgraph.db (before even trying to select). I bounced, and same thing.
Now I did select, and for sure there is no such entry in linkgraph.db.

(no results returned by either of these 2 commands:)
sqlite3 linkgraph.db "select * from edge where entity_id like '%1a0621b25a59608a6de053%'"
sqlite3 linkgraph.db "select * from entity where id like '%1a0621b25a59608a6de053%'"

I have restarted the daemon multiple times, always stops exactly in same place (it takes ~1 min to print the error and exit)

**Comment by thaJeztah** [comment] 2016-03-09 15:37
@ReSearchITEng looks like you downloaded a static binary. The static binary contains an old version of the devmapper library, which does not have Udev sync (see the warning `devmapper: Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option`. 

Running without Udev sync support is really dangerous and *will* lead to data corruption. I'm not sure if there's irreversible damage to the image store, but the recommended way is to install from our yum repository, using the steps described in the installation manual: https://docs.docker.com/engine/installation/linux/rhel/

Be sure to first uninstall the old version (that was installed from the Red Hat yum repository)
