### ISSUE TITLE
<Feature Request> : For Docker Swarm Mode, each Node can specify the port range which are available for nodes instead of Default ports

### ISSUE THREAD

**Issue by hmpurwar** [docker/docker#24927] opened 2016-07-22 09:27 UTC
This is Feature Request for Docker Swarm, where each node can specify port Ranges which can be open from the firewall, instead of default port options fro the node.

**Comment by thaJeztah** [comment] 2016-07-22 12:33
Could you provide some more information on your use case? Is this so that services / tasks are only scheduled on a node that can expose the ports that the service needs?

**Comment by cpuguy83** [comment] 2016-07-22 13:22
If I'm reading correctly, you want to be able to specify the port range used to allocate dynamic ports?
Docker gets it's port range from `/proc/sys/net/ipv4/ip_local_port_range`
An issue is already open to track customizing this beyond changing the ephemeral port range host-wide: #13322

**Comment by hmpurwar** [comment] 2016-07-25 01:48
For Container deployed on the docker swarm, Default port Range is 30000-32667.
If host ports are not assigned to the running container, This port Range might not be available to the system, because of networking issues (sort of compliance issue , such that u can't specify ports other than specifics ports range due of security concerns imposed by system). If each docker swarm node can specify what are port-Range available to user, while starting docker daemon.

**Comment by hmpurwar** [comment] 2016-07-25 01:49
@cpuguy83 , I have read the issue, seems similar to me

**Comment by thaJeztah** [comment] 2016-07-25 09:05
Thanks for looking @hmpurwar, let me close this issue as a duplicate of https://github.com/docker/docker/issues/13322; please continue the discussion over there

**Closed by thaJeztah** 2016-07-25 09:05 UTC
Labels: area/swarm, group/networking, kind/feature
