### ISSUE TITLE
Proposal: INCLUDE syntax for specifying multiple images per context

### ISSUE THREAD

**Issue by aigarius** [docker/docker#7277] opened 2014-07-28 18:39 UTC
Multiple use cases call for an ability to build several Docker images from a single context. An example would be a set of microservices that reside in a shared repository, because they also share common libraries. The common folder layout looks like this:

```
/README.md
/bar-service/...
/foo-service/...
/common/...
```

An ideal solution would: 
* allow to specify one (or more) image to be built for each service
* co-locate the Dockerfile(s) of the service inside the folder of the corresponding service
* have a default build action that would build all images
* have an option to only build one specific image

This proposal is to introduce a new verb in the Dockerfile that would look like this:
```INCLUDE /bar-service/Dockerfile.foo AS bar-service``` and a CONTEXT verb to be used in the included Dockerfiles.

The INCLUDE verb can be used multiple times. If there is an INCLUDE in a Dockerfile, it must come before the FROM verb in that file and FROM verb becomes optional.

If such line is included in the root Dockerfile and a user runs ```docker build -t aigarius/xyz .``` then this verb would have the following effects:
* docker build specified in the file /bar-service/Dockerfile.foo would be build and tagged as aigarius/xyz/bar-service.foo;
* the included Dockerfile may optionally use the new CONTEXT verb to shift the context up to the parent folder, such as if /bar-service/Dockerfile.foo includes a line ```CONTEXT ..```, then the ADD/COPY commands will work in the context of the parent folder. If such verb is not used, then the context of the included build is the folder containing the included file;
* after this line in the root Dockerfile or in any subsequently included Dockerfiles the invocation of ```FROM bar-service:included``` would use the newly built bar-service image as a base.

In addition it should be possible for a user to run ```docker build -t aigarius/xyz --images=bar-service,foo-service .``` to only build images of those two services.

Tag ":included" should be considered to be equivalent to ":latest" (possibly with a warning) if there is no build with such name in the current build set.

CONTEXT verb shifts the context for a Docker build relative to the Dockerfile. This can be used to only have a subfolder of the original context be uploaded to the daemon. It can also be used to shift the context folder up, but only if the Dockerfile is included in another Dockerfile higher in the path and only up to the folder of the top level Dockerfile.

**Comment by jfrazelle** [comment] 2015-02-25 21:57
closed as duplicate of https://github.com/docker/docker/issues/7115, trying to consolidate so we can get cool stuff like this is

**Closed by jfrazelle** 2015-02-25 21:57 UTC
Labels: feature
