### ISSUE TITLE
The requested URL was not found on this server.  

### ISSUE THREAD

**Issue by MangeshK3007** [docker/docker#30432] opened 2017-01-25 05:22 UTC
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true

docker info:

Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 2
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: 3L6X:DVUE:6JLA:GFKE:ER5C:7R6Z:DGMJ:Q5WA:ODMX:HEIB:SM52:R2RV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 26
 System Time: 2017-01-25T05:27:03.6687576Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Got Error:

The requested URL /test.php was not found on this server.

Apache/2.4.10 (Debian) Server at localhost Port 8080

How can I map my www folder with docker.
I am using lioshi/lamp image

**Comment by thaJeztah** [comment] 2017-01-25 09:00
During development, you can bind-mount a directory from your host into the container through the `-v` / `--volume` option on `docker run`. For example, to bind-mount the `/Users/myname/mywebsite` directory from your computer into the container;


    docker run -d -v /Users/myname/mywebsite/:/data/lamp/www -p 8080:80 lioshi/lamp

I had a quick look at the `lioshi/lamp`, and it doesn't look very well developed (the Dockerfile is highly unoptimised). Also, that image is running a full LAMP stack, which is _really_ not recommended; when running containers, it's recommended to put a single "service" in a container, for example, a separate container for MySQL, and a separate container for Apache (and PHP) - [containers are not VMs](https://blog.docker.com/2016/03/containers-are-not-vms/), and keeping services in separate containers not only makes them more flexible, but also increases security. To run services in multiple containers, you can use [docker-compose](https://docs.docker.com/compose/) to define how those containers should be started, and start them with a single command.

I would recommend looking at the official images for [PHP](http://hub.docker.com/_/php/) and [MySQL](http://hub.docker.com/_/mysql/) instead, and read the introduction to docker, to learn about containerising your application; https://docs.docker.com/learn/

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-01-25 09:00 UTC
