### ISSUE TITLE
CredsStore fails with private repositories

### ISSUE THREAD

**Issue by slank** [docker/docker#22910] opened 2016-05-23 15:44 UTC
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   8b63c77
 Built:        Tue May 10 10:39:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.9-moby
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: QBXC:V2FI:A2VA:V7ZG:R5V4:Q5PW:PNNP:EDH6:2QV3:WBT7:NCTH:MUDD
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 38
 System Time: 2016-05-23T15:31:47.048310555Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using Docker for Mac beta.

**Steps to reproduce the issue:**
1. Enable a credsStore via config.json
2. Log into a private registry using a full url, e.g. https://my-registry.blah
3. Try to push an image to the registry

**Describe the results you received:**

The repository credentials are not retrieved. The following error is returned:
```
<layer hash>: Image push failed 
no basic auth credentials
```

**Describe the results you expected:**

Successful image push

**Additional information you deem important (e.g. issue happens only occasionally):**

When logging in, the credsStore is given the full registry URL as a ServerURL. When performing image operations (push, pull), the scheme is omitted and the credsStore can't find the matching credentials.

**Comment by thaJeztah** [comment] 2016-05-23 16:00
Does it work if you omit the protocol when logging in? i.e. `docker login my-registry.blah`?

**Comment by slank** [comment] 2016-05-23 16:14
Yes, actually, it does.

Another example I just tested was to add a port to the registry (my-registry.blah:443). Login succeeds, push fails.

**Comment by thaJeztah** [comment] 2016-05-23 16:42
Hm, yes, so it stores the exact URL it used when logging in

ping @dmcgowan @calavera wdyt?

**Comment by runcom** [comment] 2016-05-23 16:59
I'll take a look at it (I've fixed some bugs with cred store in the past)

**Comment by thaJeztah** [comment] 2016-05-23 17:07
thanks @runcom

**Comment by runcom** [comment] 2016-05-26 18:01
@slank why are you using a full URL with https in front of the registry?

**Comment by slank** [comment] 2016-05-26 18:18
This issue surfaced while using the Amazon ECR CLI. It provides a `get-login` command that returns expiring credentials in the form of a `docker login` command. The registry URL is passed in full (including the scheme). It works fine with the default store.

**Comment by runcom** [comment] 2016-05-26 18:24
I tried with the official docker hub and if you prepend https you can login but of course pull fails. Let me try with a private registry

**Comment by runcom** [comment] 2016-05-30 10:05
I chased it down - I believe this is expected behavior with the new external credentials store. The default store (the `.docker/config.json` so to speak) could be in a legacy format where registries where saved with the scheme. This is, however, legacy, and only the default store is converting registries string to strip the scheme part and do the math to give back the correct credentials. The external stores (everyone) instead don't do this conversion. This is documented at https://github.com/docker/docker/blob/master/cliconfig/credentials/file_store.go#L33
I can fix this by doing the same logic (but trickier) for the external stores though. I'm removing the bug label for now.
ping @thaJeztah @icecrime

**Comment by runcom** [comment] 2016-05-30 10:15
I believe also we need to fix this since we're letting users to login using http|https prefix :(

**Comment by runcom** [comment] 2016-05-30 10:41
I'll need to rework my patch which fixes this also after https://github.com/docker/docker/pull/22988

**Comment by friism** [comment] 2016-08-28 20:01
@runcom I wanted to check in to see if you have had a chance to look at this?

Users are still encountering the problem: https://forums.docker.com/t/docker-pull-from-aws-registry-fails/17808/2

**Comment by runcom** [comment] 2016-08-28 20:56
@friism, I've already sent a PR #23100, I'll try to rebase and fix it this week but it needs discussion also.

**Comment by runcom** [comment] 2016-09-07 16:56
#23100 merged. Closing this.

**Closed by runcom** 2016-09-07 16:56 UTC
Labels: kind/bug, version/1.11
