### ISSUE TITLE
Build Time Mount Option

### ISSUE THREAD

**Issue by fatherlinux** [docker/docker#14251] opened 2015-06-29 13:28 UTC
I would like something like a -v option for builds because I would like to bind mount the puppet client, and manifests during build time. The end result would be a pristine container image that would be configured with Puppet (et. al.) but would contain none of the bloat. Make sense?

I get why you guys don't want to put it in the Dockerfile, but why limit it from the build command? These are two different things. People share Docker files, but I am not sure they need to share ALL build hosts?

I see the build command as something that IS specific to the build host, which is fine... I am sure I can imagine other use cases where a pristine docker image would be really nice... 

For example, I would love to bind mount test data from a database or application, that I don't want embedded in the image layer. I might need hundreds of megs or gigs of data for a database to run through automated testing of the image, but I wouldn't want it embedded in the image. Without a bind mount during build, I would be forced to fully build the image, then pull the image down, then run the image, then rebuild if it fails, etc, etc...

Best Regards
Scott M

**Comment by thaJeztah** [comment] 2015-08-16 10:38
Hi @fatherlinux, it looks like this is a duplicate of https://github.com/docker/docker/issues/14080, so I'm going to close this one. Please join the discussion on https://github.com/docker/docker/issues/14080

**Closed by thaJeztah** 2015-08-16 10:38 UTC

**Comment by fatherlinux** [comment] 2015-08-16 22:19
No worries, I have been discussing it there. Somebody asked me to create a separate ticket, but I can't remember who/why.

**Comment by thaJeztah** [comment] 2015-08-16 22:30
:+1: trying to make sure we don't have too many dupes, otherwise the discussions tend to be spread all over :smile:. Thanks!

**Comment by fatherlinux** [comment] 2015-08-16 23:19
Totally understand brother!
