### ISSUE TITLE
Iptables : bad rules or no chain/target/match by that name

### ISSUE THREAD

**Issue by ouafnico** [docker/docker#26494] opened 2016-09-12 15:51 UTC
Hello

Using CentOS 7, I've got a lot of errors when using firewalld.
Starting Docker after firewalld give a lot of iptables errors on /var/log/firewalld.
Starting docker before firewalld works, but then the containers can't start because of iptables errors.
To resolve I had to restart docker again after starting firewalld.

docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-667492-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop1
 Metadata file: /dev/loop2
 Data Space Used: 1.319 GB
 Data Space Total: 107.4 GB
 Data Space Available: 9.473 GB
 Metadata Space Used: 2.245 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.551 GiB
Name: shiva.shivaserv.fr
ID: J7E4:MV4S:L6WO:DFLS:PMN3:RIPX:67S5:OUZK:RAUV:SMKH:443J:MUQY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

My environnment is a physical server, CentOS 7.2 x64.

**Steps to reproduce the issue:**

FIRST EXAMPLE:

1. Start firewalld then docker. See the errors on /var/log/firewalld:

2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER' failed: iptables v1.4.21: Couldn't load target `DOCKER':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER' failed: iptables v1.4.21: Couldn't load target `DOCKER':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -D PREROUTING' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -D OUTPUT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -F DOCKER' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -X DOCKER' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -F DOCKER' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -X DOCKER' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -F DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -X DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -n -L DOCKER' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -n -L DOCKER' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -n -L DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -C DOCKER-ISOLATION -j RETURN' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -C DOCKER -i docker0 -j RETURN' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -C FORWARD -o docker0 -j DOCKER' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -C FORWARD -j DOCKER-ISOLATION' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE' failed: iptables: No chain/target/match by that name.
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t nat -C DOCKER -i docker0 -j RETURN' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).
2016-09-12 17:46:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -C FORWARD -o docker0 -j DOCKER' failed: iptables: No chain/target/match by that name.

OR, SECOND EXAMPLE:

1. Start docker, then firewalld : OK
2. Start a container: 
docker start docker-transmission-vpn
Error response from daemon: driver failed programming external connectivity on endpoint docker-transmission-vpn (1811de91fd48689cb7963c6ae574282ca08b578b1c60b49c74d076b70f833eb1): iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.17.0.2:9091 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)
Error: failed to start containers: docker-transmission-vpn
(no more logs on /Var/log/firewalld)

3. So, restart docker (same errors on /var/log/firewalld than first example), then restart container : OK

If I stop the container, I will have to restart docker to restart the container without errors.

Same issue with older version on CentOS 7 official repos (1.10).

**Comment by mlaventure** [comment] 2016-09-12 21:29
ping @mavenugo

**Comment by jshin47** [comment] 2016-09-13 00:57
I'm experiencing a similar issue when trying to start docker-bind:

```
# docker run --name bind -d --restart=always   --publish 53:53/tcp --publish 53:53/udp --publish 10000:10000/tcp --security-opt seccomp=unconfined   --volume /srv/docker/bind:/data   sameersbn/bind:latest
7bcb75a86cec4f5d187939208104e32b83419a6b11eabf655be97b69befb246c
docker: Error response from daemon: driver failed programming external connectivity on endpoint bind (14e1a51512de042991a14eab288fa25d20be36ef0d49235270617c9d61e19910): iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 10000 -j DNAT --to-destination 172.17.0.2:10000 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1).
[root@base log]# ^C
```

**Comment by thaJeztah** [comment] 2016-09-23 14:41
This is a duplicate of https://github.com/docker/docker/issues/16137 or https://github.com/docker/docker/issues/16816, and the discussion on those issues may give more information or workarounds.

**Closed by thaJeztah** 2016-09-23 14:41 UTC
Labels: area/networking, version/1.12
