### ISSUE TITLE
Mounting /proc/1/ns/net:/hostroot/proc/1/ns/net fails with "Command not found or does not exist"

### ISSUE THREAD

**Issue by adityats** [docker/docker#31530] opened 2017-03-03 20:31 UTC
Running a privileged container with one of the volume mount as "-v /proc/1/ns/net:/hostroot/proc/1/ns/net" results in "Command not found or does not exist" error.

[root@ip-10-144-16-86 ~]# docker run -d -it --name=avise -v /var/run/docker.sock:/var/run/docker.sock -v /proc/1/ns/net:/hostroot/proc/1/ns/net avinetworks/se
dc4f80f01526ed71fb93aad6cbe3b563cdc50e75813569410071aad96a9f7654
docker: Error response from daemon: Container command not found or does not exist..

**Describe the results you expected:**
docker container to start

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens with docker 1.10.3 version only, we tried it with newer 1.11+ versions and the container comes up fine.

**Output of `docker version`:**
[root@ip-10-144-16-86 ~]# docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64

**Output of `docker info`:**
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-202:1-16876846-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.138 GB
 Data Space Total: 107.4 GB
 Data Space Available: 23.17 GB
 Metadata Space Used: 1.311 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-514.6.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 3.451 GiB
Name: ip-10-144-16-86.us-west-2.compute.internal
ID: VSUT:3L74:HUK2:ZWBN:D342:A4GV:EAX5:ITF2:5SRH:LDZK:Y3G3:WDUB
Registries: docker.io (secure)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Currently this is on an AWS EC2 instance, but it happens on any system with docker version 1.10.3

**Comment by justincormack** [comment] 2017-03-03 20:46
Hi, the version "3999ccb-unsupported" is not a build that we support, and the 1.10 release of Docker is no longer supported. As the Problem is fixed on more recent versions, I would recommend you upgrade, see the install instructions for Centos here https://docs.docker.com/engine/installation/linux/centos/

**Closed by justincormack** 2017-03-03 20:46 UTC
Labels: version/1.10
