### ISSUE TITLE
How to detect and mitigate DDOS attacks or agggressive scraping with swarm services

### ISSUE THREAD

**Issue by virtuman** [docker/docker#31046] opened 2017-02-15 15:37 UTC
When using docker swarm and realip doesn't seem to be available - what should the steps be to block unwanted traffic?

We used to have haproxy route traffic to Nginx servers and nginx applied lots of filtering and recorded access logs that continuously were processed by something like fail2ban to prevent future access. 

With docker swarm - since public ip isn't available - is there way to identify or prevent things like DDOS? 

With docker swarm I already tried dockercloud-haproxy and jwilder's nginx proxy to no avail 

Or should we have non-dockerized nginx running as a reverse proxy for all incoming traffic on web ports and apply all filtering prior to sending traffic to something like dockercloud? Seems a little convoluted but possibly viable. 

Thank you.

**Comment by sevoma** [comment] 2017-02-15 15:50
I don't think it's supported by Swarm load balancing, but if you're using a proxy, you're looking for adding the X-Forwarded-For header.

https://github.com/jwilder/nginx-proxy/issues/130#issuecomment-86855662

**Comment by thaJeztah** [comment] 2017-03-09 20:46
Thanks for reporting @virtuman. This actually is a duplicate of https://github.com/docker/docker/issues/25526, which contains more information, and some approaches that may work for you.

I'm closing this issue, because it's a duplicate, and to prevent the discussion from diverging; please subscribe to the linked issue to keep informed on updates 👍

**Closed by thaJeztah** 2017-03-09 20:46 UTC
Labels: area/swarm
