### ISSUE TITLE
Thin pool option is specified both as a flag and in the configuration file

### ISSUE THREAD

**Issue by Suncatcher** [docker/docker#30726] opened 2017-02-03 20:41 UTC
**Description**

Docker daemon cannot be started. This is follow-up of [this error](#30631). In the [provided guide](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/configure-direct-lvm-mode-for-production) I reached p.16

**Steps to reproduce the issue:**
1. Modify daemon.json (according [this guide](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/configure-direct-lvm-mode-for-production)) like this to add thin pool option
```
{
   "storage-opts": [
     "--storage-opt dm.thinpooldev=/dev/mapper/docker-pool0-tpool"
   ]
}
```
2. Try to start docker via `sudo service docker (re)start` and get FAIL.
3. running `docker info` or any other command returns 
**Cannot connect to the Docker daemon. Is the docker daemon running on this host?**

Docker log contains following info

    level=fatal msg="unable to configure the Docker daemon with file /etc/docker/daemon.json: the
    following directives are specified both as a flag and in the configuration file: storage-opts: (from 
    flag:[dm.thinpooldev=/dev/mapper/docker-docker--pool dm.use_deferred_removal=true
    dm.use_deferred_deletion=true dm.fs=ext4], from file: [--storage-opt
    dm.thinpooldev=/dev/mapper/docker-pool0-tpool])\n" 

**Describe the results you received:**
Docker fails to start and I get
`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Describe the results you expected:**
Successful start of Docker daemon.

**Additional information you deem important (e.g. issue happens only occasionally):**
If I remove `docker.json` then the error in log is exactly the same as described [here](#30631) 

      level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper: Non existing device docker-docker--pool"

**Output of `docker version`:**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host

**Output of `docker info`:**

`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS t2.micro AMI Linux 2016.09d

**Comment by thaJeztah** [comment] 2017-02-05 03:40
First of all, your `daemon.json` looks to be invalid; the `--storage-opt` should not be in there; it should look like;

```json
{
     "storage-opts": [
        "dm.thinpooldev=/dev/mapper/docker-pool0-tpool"
    ]
}
```

The error message, however, is that you provided storage-opt settings through a _flag_ as well; probably in a systemd unit file / drop-in file. Daemon settings are not allowed to be provided by _both_ a flag and the daemon.json file 

To find out where it's set, temporarily rename or remove your daemon.json and use `systemctl cat docker.service` to view your unit files to check where it's configured.

I'll close this issue, because this is not a bug, but feel free to continue the conversation if you need help

**Closed by thaJeztah** 2017-02-05 03:40 UTC

**Comment by Suncatcher** [comment] 2017-02-05 13:09
Yes, I am definitely need help!
AMI linux is on initd not on systemd, so it has NO systemctl. What should I do then?

**Comment by Suncatcher** [comment] 2017-02-05 13:29
Well, I found probably the thing. initd options are stored in `/etc/sysconfig/docker` and there is only

     OPTIONS="--default-ulimit nofile=1024:4096"

no thin pools or whatever. What should I do?

**Comment by thaJeztah** [comment] 2017-02-05 21:57
In not familiar with how that AMI is configured; Amazon Linux is not supported yet, and I assume that AMI is managed by Amazon. From what I see in your reports, either that AMI is incorrectly configured, or something went wrong during deployment.

The daemon should not require any storage-opts set to start up (although you'd be running on loop devices, so not recommended for production - at least it should get you going)

Try to find where the storage options are set; possibly there's an `/etc/default/docker` file, but as mentioned, I'm not familiar with these AMI's

**Comment by Suncatcher** [comment] 2017-02-05 22:30
> Try to find where the storage options are set; possibly there's an /etc/default/docker

No, there is nothing in /etc/default/docker. The only conf-file I found is in /etc/sysconfig/docker.
So you recommend to switch to another OS. They have in the marketplace

- Debian 8
- Ubuntu Server 12/14/16
- CentOS 6/7
- openSUSE
Which of them suits best for Docker?
Is systemd is a must? CentOS 6 (and probably others) lacks it too.

**Comment by thaJeztah** [comment] 2017-02-05 22:45
systemd is not a must, but it's by now the default init system on recent distros. Ubuntu 16.04 is a LTS version, and should be fine.

Installation instructions for ubuntu can be found here; https://docs.docker.com/engine/installation/linux/ubuntu/

Those instructions mention installing aufs as a storage driver, but on modern kernels (4.4, for example), `overlay2` may be a good choice
