### ISSUE TITLE
centos7 docker boot other_args not use

### ISSUE THREAD

**Issue by woshihaoren** [docker/docker#15627] opened 2015-08-17 11:58 UTC
I install docker-engine in centos7,and edit /etc/sysconfig/docker .
other_args="--storage-opt dm.basesize=200G --storage-opt dm.loopdatasize=2500G -H unix:///var/run/docker.sock --insecure-registry dl.dockerpool.com:5000 --insecure-registry 10.255.33.19:5000"

systemctl start docker.service 
but docker info DATA space was not 2500G.
[root@localhost ~]# docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:0-4299301548-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.821 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.6 GB
 Metadata Space Used: 1.483 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 24
Total Memory: 62.71 GiB
Name: localhost
ID: J4JT:RKUB:UFYP:245F:THZV:FCQI:DTP5:IUQA:ZISO:YRHP:FTZC:BULT

**Comment by thaJeztah** [comment] 2015-08-17 12:18
The systemd service by default doesn't use custom options specified in `/etc/sysconfig/docker`. If you want to set custom daemon options, use drop-in files, following the instructions in [Custom Docker daemon options](http://docs.docker.com/articles/systemd/#custom-docker-daemon-options)

I'm going to close this issue, because this is not a bug. I hope these instructions help you make these configuration changes. Feel free to comment here after I've closed the issue.

**Closed by thaJeztah** 2015-08-17 12:18 UTC
