### ISSUE TITLE
1.6.0 : docker push pushes same image(s) to registry repeatedly

### ISSUE THREAD

**Issue by gramakri** [docker/docker#12808] opened 2015-04-27 08:07 UTC
With docker 1.6.0, docker push keeps repushing the same images repeatedly. Not sure what is happenning here but this is very easy to reproduce here (and in many of our machines).

docker 1.5
------------------
```
root@dog:~/bgg# cat Dockerfile
FROM girish/base:0.1.0

ADD start.sh /home/git/start.sh

CMD [ "/home/git/start.sh" ]
root@dog:~/bgg# docker build -t girish/1234:5678 .
Sending build context to Docker daemon  2.56 kB
Sending build context to Docker daemon
Step 0 : FROM girish/base:0.1.0
 ---> 5bc35abf06b1
Step 1 : ADD start.sh /home/git/start.sh
 ---> 98ee4b8ace19
Removing intermediate container 1c5e0621d283
Step 2 : CMD /home/git/start.sh
 ---> Running in 6c8ef504499b
 ---> f1f199ed5336
Removing intermediate container 6c8ef504499b
Successfully built f1f199ed5336
root@dog:~/bgg# docker push girish/1234:5678
The push refers to a repository [girish/1234] (len: 1)
Sending image list
Pushing repository girish/1234 (1 tags)
5bc35abf06b1: Image already pushed, skipping
98ee4b8ace19: Image successfully pushed
f1f199ed5336: Image successfully pushed
Pushing tag for rev [f1f199ed5336] on {https://cdn-registry-1.docker.io/v1/repositories/girish/1234/tags/5678}
root@pig:~/bgg# docker info
Containers: 0
Images: 3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: pig
ID: IB3C:7O4N:FP3R:M6MH:3JDE:7GYJ:W5YO:EHOD:DENH:HPPT:ATF6:24TG
Username: girish
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
root@pig:~/bgg# docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

On the very same machine, immediately after the above, I installed 1.6.
```
apt-get remove lxc-docker-1.5.0
apt-get install lxc-docker-1.6.0
```

docker 1.6
--------------
```
root@dog:~/bgg# docker build -t girish/1234:5678 .
Sending build context to Docker daemon  2.56 kB
Sending build context to Docker daemon
Step 0 : FROM girish/base:0.1.0
 ---> 5bc35abf06b1
Step 1 : ADD start.sh /home/git/start.sh
 ---> Using cache
 ---> 98ee4b8ace19
Step 2 : CMD /home/git/start.sh
 ---> Running in b64799ceb121
 ---> 03b24ff89e04
Removing intermediate container b64799ceb121
Successfully built 03b24ff89e04
root@dog:~/bgg# docker push girish/1234:5678
root@pig:~/bgg# docker push girish/1234:5678
The push refers to a repository [girish/1234] (len: 1)
03b24ff89e04: Image already exists
98ee4b8ace19: Image successfully pushed
5bc35abf06b1: Buffering to Disk <---------- This is already in registry but it keeps getting repushed
^Croot@pig:~/bgg# docker info
Containers: 0
Images: 4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: pig
ID: IB3C:7O4N:FP3R:M6MH:3JDE:7GYJ:W5YO:EHOD:DENH:HPPT:ATF6:24TG
Username: girish
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
root@pig:~/bgg# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

**Comment by gramakri** [comment] 2015-04-27 08:10
It's easy to test this using a Digital Ocean droplet that has Docker 1.6.0 installed.

**Comment by kenden** [comment] 2015-04-29 12:13
We're seeing the same behavior.
Possible duplicate of https://github.com/docker/docker/issues/12489

**Comment by jfrazelle** [comment] 2015-04-29 20:53
closing as dup of https://github.com/docker/docker/issues/12489 please comment there so we dont have 2 threads

**Closed by jfrazelle** 2015-04-29 20:53 UTC
