### ISSUE TITLE
mounting "/proc" to rootfs cannot be mounted because it is located inside \"/proc\""

### ISSUE THREAD

**Issue by kindermoumoute** [docker/docker#26651] opened 2016-09-16 23:33 UTC
**Description**
I'm trying to mount the `/proc` folder from a container _A_, into the folder `/proc_host` another container _B_. I'm using a named volume to do that, but it looks like doing it overwrites the `/proc` folder on my container _A_.

In the example:
- Container _A_: docker:dind.
- Container _B_: ubuntu:xenial.

**Steps to reproduce the issue:**
1. Create this `docker-compose.yml`
```
version: '2'
services:
  main:
    container_name: runner
    image: ubuntu:xenial
    volumes:
      - proc:/proc_host
  docker:
    container_name: docker
    image: docker:dind
    volumes:
      - proc:/proc
volumes:
  proc:
```
2. run `docker-compose up -d` in the same folder.

**Describe the results you received:**
> Creating docker
> Creating runner
> 
> ERROR: for docker  Cannot start service docker: oci runtime error: rootfs_linux.go:53: mounting "/proc" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/23590746b9ae30a36ab4ae13c70447d5bc540ad5727fcebdf9639c66c662ab54" caused "\"/mnt/sda1/var/lib/docker/aufs/mnt/23590746b9ae30a36ab4ae13c70447d5bc540ad5727fcebdf9639c66c662ab54/proc\" cannot be mounted because it is located inside \"/proc\""
> ERROR: Encountered errors while bringing up the project.

**Describe the results you expected:**
No error.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 44
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 79
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: R3DM:DAJ3:D7RD:NEDJ:GLE4:ES3O:DA57:ARC3:4OYM:XO2E:2LIC:5PON
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 42
 System Time: 2016-09-16T23:21:39.406611739Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Comment by michelvocks** [comment] 2016-09-17 08:01
Hello @kindermoumoute 
Following sentence is described in the [docs](https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume):

> This command mounts the host directory, /src/webapp, into the container at /opt/webapp. If the path /opt/webapp already exists inside the container’s image, the /src/webapp mount overlays but does not remove the pre-existing content. Once the mount is removed, the content is accessible again. This is consistent with the expected behavior of the mount command.

You should use the `volumes-from` functionality: https://docs.docker.com/engine/tutorials/dockervolumes/#/creating-and-mounting-a-data-volume-container

**Comment by cpuguy83** [comment] 2016-09-17 12:00
You can't mount to `/proc`. Why are you trying to do this?
Closing since this is expected behavior.

**Closed by cpuguy83** 2016-09-17 12:00 UTC
Labels: version/1.12

**Comment by aeronwang** [comment] 2024-05-17 19:05
mount (or bind mount) a dir to /proc does not make any sense because /proc should represent kernel's memory. Instead doing that, you can do: # mount -t proc proc /proc (for example this should be done for container or chroot).
