### ISSUE TITLE
Dockerfile: RUN over multiple lines without && \

### ISSUE THREAD

**Issue by d2xdt2** [docker/docker#16058] opened 2015-09-03 19:22 UTC
It is very common to see Dockerfile's which uses `RUN` over several lines like so

```
RUN cd / && \
    git clone https://github.com/ && \
    cd /fileadmin/ && \
    bundle install && \
    rake db:migrate && \
    bundle exec rails runner "eval(File.read 'createTestUser.rb')" && \
    mkdir /pending && \
    mkdir /live && \
    chmod 777 /pending && \
    chmod 777 /live
```

where `&& \` is used many times.

The problem is that it is tedious to read and write.

**Proposal**

`RUN` should by itself add `&& \` at end of line, and terminate at the first blank line. The above example would become
```
RUN cd /
    git clone https://github.com/
    cd /fileadmin/
    bundle install
    rake db:migrate
    bundle exec rails runner "eval(File.read 'createTestUser.rb')"
    mkdir /pending
    mkdir /live
    chmod 777 /pending
    chmod 777 /live
```
Much easier to read and write.

**Comment by duglin** [comment] 2015-09-03 19:29
I'm not a fan of implicit things like this. If people want to continue a line they should let us know it with a \\. Leading spaces (or blank lines) are too indeterminate to mandate that it means "continue previous line".

**Comment by cpuguy83** [comment] 2015-09-03 20:01
Agree with @duglin

**Comment by tianon** [comment] 2015-09-03 20:33
@duglin what about heredoc support? :smile:
```Dockerfile
RUN <<EOR
    cd /
    git clone https://github.com/
    cd /fileadmin/
    bundle install
    rake db:migrate
    bundle exec rails runner "eval(File.read 'createTestUser.rb')"
    mkdir /pending
    mkdir /live
    chmod 777 /pending
    chmod 777 /live
EOR

**Comment by duglin** [comment] 2015-09-03 20:43
@tianon if we were allowed to make changes to the builder, then heck yea!!

**Comment by d2xdt2** [comment] 2015-09-05 09:03
heredoc would be a great solution, as many now have a `RUN` for each line, just to avoid having to type and look at `&& \`. Many official images on Docker Hub does it right now.

**Comment by thaJeztah** [comment] 2015-09-06 00:09
heredoc was proposed/discussed a few times before (e.g. https://github.com/docker/docker/issues/1554, https://github.com/docker/docker/issues/1799)

However, there's currently a freeze on the Dockerfile syntax, pending moving the builder to the client; https://github.com/docker/docker/issues/14298. It looks like @jlhawn's POC builder does support heredoc; https://github.com/jlhawn/dockramp

**Comment by thaJeztah** [comment] 2015-11-24 21:14
I'm going to close this issue, following the discussion above; supporting heredoc is probably a nicer solution to this problem, however, cannot currently be implemented due to the Dockerfile syntax currently being frozen; https://github.com/docker/docker/blob/master/ROADMAP.md#2-frozen-features

**Comment by thaJeztah** [comment] 2015-11-24 21:14
Thanks for suggesting this though @d2xdt2! It's much appreciated to get feedback and feature suggestions.

**Closed by thaJeztah** 2015-11-24 21:14 UTC

**Comment by pierreozoux** [comment] 2016-03-03 12:57
@thaJeztah is it still frozen? Is there a chance that will see this landing one day? (It is indeed ugly :) )

**Comment by AlJohri** [comment] 2016-11-16 07:56
my multiline commands gets rendered like this (with large amounts of spaces between commands) when docker runs it. is there any interest in fixing this part?

<img width="803" alt="screen shot 2016-11-16 at 2 55 14 am" src="https://cloud.githubusercontent.com/assets/2790092/20338989/2b521e96-aba8-11e6-9aad-911811816d16.png">

**Comment by thaJeztah** [comment] 2016-11-16 08:59
@AlJohri that's the way the shell sees it, that's no different from using line-continuation in your shell. Try this in your shell;

```bash
echo "hello-world" && \
    echo "foo-bar"
```

then press the "up" arrow to get the command from your history, and it'll show;

```bash
echo "hello-world" &&     echo "foo-bar"
```


The "gaps" are probably because you aligned the lines in your Dockerfile, taking `RUN ` into account (four spaces) when aligning.

**Comment by AlJohri** [comment] 2016-11-16 09:03
@thaJeztah yup!

<img width="349" alt="screen shot 2016-11-16 at 4 01 25 am" src="https://cloud.githubusercontent.com/assets/2790092/20340841/8ab1d74c-abb1-11e6-8e96-b99550c72d15.png">

I was mostly just curious if it were possible to render without the spaces by regexing them out or something

**Comment by thaJeztah** [comment] 2016-11-16 09:14
@AlJohri No, that won't be possible without fully replicating the shell and "interpreting" the steps. Sure, it's easy to strip out multiple consecutive white-spaces in the output, but that would not be the right thing to do, because white-space can have (and in most cases _has_) meaning. For example, in the following you _want_ the whitespace to be preserved in the output of `docker build`;

```bash
echo "hello \
            world"
```

**Comment by AlJohri** [comment] 2016-11-16 09:15
Figured as much, thanks for explaining!

**Comment by gukoff** [comment] 2017-09-01 08:34
> I'm not a fan of implicit things like this. If people want to continue a line they should let us know it with a . Leading spaces (or blank lines) are too indeterminate to mandate that it means "continue previous line".

It is perfectly explicit. There are a lot of successful examples of the whitespace indentation, e.g. Python, YAML, Haskell. Te proposal isn't about 'continuing a line', it is about combining the lines.

**Comment by inf3rno** [comment] 2017-09-14 00:46
I support heredoc too. Just wondering why it is so hard to add a feature requested by many ppl...

**Comment by thaJeztah** [comment] 2017-09-14 00:52
@inf3rno see https://github.com/moby/moby/issues/34423

**Comment by piotrminkina** [comment] 2017-10-05 06:26
My own Dockerfile coding standard:

```Dockerfile
# Example with apt-get update, install and clean it's cache
RUN apt-get update -yq \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -yq pkg1 pkg2 pkg3 \
 && find /var/cache/apt/archives /var/lib/apt/lists -not -name lock -type f -delete

# Example with many packages to install at one time
RUN apt-get update -yq \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -yq \
    pkg1 \
    pkg2 \
    pkg3 \
    ... \
    pkg10 \
 && find /var/cache/apt/archives /var/lib/apt/lists -not -name lock -type f -delete

# Example untar with pipes
ARG WEBSOCKIFY_VERSION="v0.8.0"
RUN mkdir -p /opt/websockify \
 && curl -sSL https://github.com/novnc/websockify/archive/${WEBSOCKIFY_VERSION}.tar.gz \
  | tar -zx -C /opt/websockify --strip 1

# Example call command with many arguments at one time (my propose is use long parameters names)
RUN some-command1 \
    --some-option1=some-value1 \
    --some-option2=some-value2 \
    --some-option2=some-value2 \
    --some-option2=some-value2 \
 && some-command2 \
    --some-option1=some-value1 \
    --some-option2=some-value2 \
    --some-option2=some-value2 \
    --some-option2=some-value2
```

**Comment by jen-soft** [comment] 2019-05-03 14:33
Using *pydocker* ( https://github.com/jen-soft/pydocker )

[ Dockerfile.py ]
```python
from pydocker import DockerFile  # sudo pip install -U pydocker

d = DockerFile(base_img='debian:8.2', name='jen-soft/custom-debian:8.2')

d.RUN_bash_script('/opt/set_repo.sh', r'''
cat >/etc/apt/sources.list <<EOL
deb     http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main
EOL
apt-get clean && apt-get update
''')

d.EXPOSE = 80
d.WORKDIR = '/opt'
d.CMD = ["python", "--version"]

# d.generate_files()
d.build_img()

```
```bash
# sudo wget -qO- https://get.docker.com/ | sh

python Dockerfile.py
docker images
```

**Comment by whirlwin** [comment] 2020-02-11 11:44
What should be the expected behaviour be when omitting `&&`?

Should the commands in the chain only be executed one after another on success (like with `&&`). Or should they be independent, so that one command does not halt the next commands.

This is not perfectly clear clear. Why `&&` and not `||`?

**Comment by thaJeztah** [comment] 2020-02-11 11:52
The `&&` is mainly used if you want all commands to complete successfully (e.g. `do something && do something else if the previous command completed sucessfully`). You can use different approaches (e.g., `set -eux; some command; some other command;`).

By default (in a Linux Dockerfile), `RUN <shell commands>` is equivalent to `sh -c '<shell commands>`, and `docker build` will execute that step, and commit the results once the `sh -c` terminates successfully. If the `sh -c` exits with a non-zero exit code, the build is marked "failed"

**Comment by chapmanjacobd** [comment] 2020-02-17 05:53
`&&` is when you want to execute next command only if previous command exits with `exit code 0`. a single `&` means run the command after previous command regardless of previous exit code (whether the previous command was successful or not).

a trick I learned recently is that you can use subshells to run multiple commands and you don't need to use `\` to put multiple lines. I think this should work with docker run but I didn't test it yet:

```
docker run {CONTAINER_TAG} /bin/bash -c "(
    cd /
    git clone https://github.com/
    cd /fileadmin/
    bundle install
    rake db:migrate
    bundle exec rails runner "eval(File.read 'createTestUser.rb')"
    mkdir /pending
    mkdir /live
    chmod 777 /pending
    chmod 777 /live
    ) &"
```

or 

```
RUN (cd /
    git clone https://github.com/
    cd /fileadmin/
    bundle install
    rake db:migrate
    bundle exec rails runner "eval(File.read 'createTestUser.rb')"
    mkdir /pending
    mkdir /live
    chmod 777 /pending
    chmod 777 /live
    ) & <----- this & should be optional. if you want docker to wait before doing other stuff in your dockerfile then you should remove the & here and I think it should still work
```

**Comment by Danilo-Araujo-Silva** [comment] 2021-04-22 16:38
@thaJeztah How about to reopen the issue, so we can actually have the heredoc approach implemented and not forgotten?

**Comment by piotrminkina** [comment] 2021-04-22 17:19
@chapmanjacobd Your example is unsafe. See the following code and its execution result.

```bash
/bin/sh -c "(cd /
    true
    echo 'this line should be printed...'
    false
    echo 'this line MUST NOT be printed!'
    )"
```

```
this line should be printed...
this line MUST NOT be printed!
```

**Comment by d2xdt2** [comment] 2021-04-23 10:41
I have solved the problem by migrating to Podman and Buildah. From https://www.redhat.com/en/blog/say-hello-buildah-podman-and-skopeo . Notice the `set -e`.

```
#!/bin/bash

# Define script constants
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Change directory to code location
set -e
pushd $SCRIPT_DIR
trap popd EXIT INT TERM

# Test code
go test ./...

# Build Go binary
time GOOS=linux CGO_ENABLED=0 go build

# Build container
docker build -t saharshsingh/taskmaster .
```

**Comment by gVien** [comment] 2021-07-17 00:05
@piotrminkina 

you can force it to exit if a command exists a non-zero status by adding `set -e`, which in most cases you should include it in your script anyway.

```
/bin/sh -c "(
    set -e
    cd /
    true
    echo 'this line should be printed...'
    false
    echo 'this line MUST NOT be printed!'
    )"
```
```
this line should be printed...
```

and also

```
/bin/bash -c '( (
    set -e
    cd /
    true
    echo "this line should be printed..."
    false
    echo "this line MUST NOT be printed!"
    ) &) &'
```
```
this line should be printed...
```



> @chapmanjacobd Your example is unsafe. See the following code and its execution result.
> 
> ```shell
> /bin/sh -c "(cd /
>     true
>     echo 'this line should be printed...'
>     false
>     echo 'this line MUST NOT be printed!'
>     )"
> ```
> 
> ```
> this line should be printed...
> this line MUST NOT be printed!
> ```
> 
> Your example with subshells is also unsafe.
> 
> ```shell
> /bin/bash -c '( (
>     cd /
>     true
>     echo "this line should be printed..."
>     false
>     echo "this line MUST NOT be printed!"
>     ) &) &'
> ```
> 
> ```
> this line should be printed...
> this line MUST NOT be printed!
> ```

**Comment by thaJeztah** [comment] 2021-07-17 13:43
If you have buildkit enabled (`DOCKER_BUILDKIT=1`), you can now use HEREDOC in your Dockerfile if you use the [`docker/dockerfile:1-labs` syntax](https://docs.docker.com/engine/reference/builder/#syntax). (Will be included by default in a future version of the standard Dockerfile syntax). See https://github.com/moby/buildkit/pull/2132 for more details, and the proposal in https://github.com/moby/moby/issues/34423

EDIT: the [`docker/dockerfile:1-labs`](https://hub.docker.com/r/docker/dockerfile) has not yet been updated (should probably be soon), but is already available on [`docker/dockerfile-upstream`](https://hub.docker.com/r/docker/dockerfile-upstream)


For example:

```dockerfile
# syntax=docker/dockerfile-upstream:1-labs
FROM alpine
RUN apk add --no-cache git

RUN <<-EOF
	set -x
	cd /
	git clone https://github.com/moby/sys.git /somedir/
	cd /somedir/
	echo "do some things" > foo.txt
	echo "do more things" > foo.txt
	echo "do more things" > foo.txt
EOF
```

And building with BuildKit enabled (I'm using `--progress=plain` to make the output visible);

```bash
DOCKER_BUILDKIT=1 docker build --progress=plain -t myimage .
```

```bash
#1 [internal] load build definition from Dockerfile
#1 sha256:382077b46454c3e0d90f251191b8033a7d6513c4387bfe0cce93534af67b8631
#1 transferring dockerfile: 323B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:2d73eacac64f0f432e6edc3a22fc17382ea3f78a668243e12af2a95738fa1033
#2 transferring context: 2B done
#2 DONE 0.0s

#3 resolve image config for docker.io/docker/dockerfile-upstream:1-labs
#3 sha256:cef82919fd34f32c88fcbc931c5413a5d24a84baa144c97ef3bf966e07bf938f
#3 DONE 0.5s

#4 docker-image://docker.io/docker/dockerfile-upstream:1-labs@sha256:03ca0e50aa4b6e76365fa9a5607c3f988bc9284de6a82672eab5ad627324e1fe
#4 sha256:bcf3cdc3ab3e9376b3a3819b5c625387be694c9c52536475ae4395cfd5df3610
#4 CACHED

#6 [internal] load .dockerignore
#6 sha256:2f2df4ab214a9c9c631680918c91190c0a4b8ff3504a1e455843be8d11d63715
#6 DONE 0.0s

#5 [internal] load build definition from Dockerfile
#5 sha256:03aca6c9f5e08bb110335776f8d8ecd0eca4081823ed8462905276c6afbd3db3
#5 DONE 0.0s

#7 [internal] load metadata for docker.io/library/alpine:latest
#7 sha256:d4fb25f5b5c00defc20ce26f2efc4e288de8834ed5aa59dff877b495ba88fda6
#7 DONE 0.0s

#8 [1/3] FROM docker.io/library/alpine
#8 sha256:665ba8b2cdc0cb0200e2a42a6b3c0f8f684089f4cd1b81494fbb9805879120f7
#8 DONE 0.0s

#9 [2/3] RUN apk add --no-cache git
#9 sha256:dd026a106d0ccbd6ec0cb1717e9d682e2a8c8d659501396199214332abc87143
#9 CACHED

#10 [3/3] RUN <<-EOF (set -x...)
#10 sha256:d542ce19f0dcb0ad060701aec434981383aec28da818e7bd1dc6c6ac75c99a7a
#10 0.235 + cd /
#10 0.235 + git clone https://github.com/moby/sys.git /somedir/
#10 0.237 Cloning into '/somedir'...
#10 1.007 do some things
#10 1.007 do more things
#10 1.007 do more things
#10 1.007 + cd /somedir/
#10 1.007 + echo 'do some things'
#10 1.007 + echo 'do more things'
#10 1.007 + echo 'do more things'
#10 DONE 1.0s

#11 exporting to image
#11 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#11 exporting layers 0.0s done
#11 writing image sha256:1dabb9c7b89b838f531901ad7199231bda6084db0c6e32f5b0070646e6f06aec done
#11 naming to docker.io/library/myimage done
#11 DONE 0.1s
```
