### ISSUE TITLE
Swarm mode DNS lookup resolves only IPs from the same host

### ISSUE THREAD

**Issue by burdiyan** [docker/docker#26747] opened 2016-09-20 17:39 UTC
**Description**

I have 3 hosts in swarm mode cluster and a service replicated between those hosts. Doing DNS lookup by service name only resolves IP addresses of the containers running on the same host. All hosts are connected to the same custom overlay network (not ingress).

**Steps to reproduce the issue:**
1. Create a Swarm Mode cluster with multiple hosts.
2. Create an overlay network on the manager. (E.g. `services`).
3. `docker service create --name nginx --replicas 3 --network services nginx`.
4. Go to one of the hosts and do `docker exec -it [container] bash` to one of the containers.

**Describe the results you received:**
Running `dig tasks.nginx` in one of the nginx containers resolves only IP addresses for the containers from the same host, not from the whole network.

**Describe the results you expected:**
DNS resolving for all the containers in the network by service name.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Thu Aug 18 22:32:50 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: active
 NodeID: 52nwzxa2zd9taqjebqxgmwuy4
 Is Manager: true
 ClusterID: 49kqkimxo9qw4nifexpxeb9kh
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 188.166.146.6
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: swarm1
ID: X4IS:6MJB:MHIU:I4TX:DURB:JBGZ:DOPW:DNSQ:3B7X:CHYI:H5FR:ZBOR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: burdiyan
Registry: https://index.docker.io/v1/
Labels:
 provider=digitalocean
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I was trying that with 3 hosts in DigitalOcean created with Docker Machine. Creating the service with dnsrr endoint mode gave me the same results.

**Comment by Vanuan** [comment] 2016-09-20 17:55
Same here. Was running fine for two weeks. Started today.
Can resolve services that have containers located on this host, but not containers that are located on other hosts.

**Comment by Vanuan** [comment] 2016-09-20 18:18
I see this in dmesg approximately at the time this happened:
```
[Tue Sep 20 12:59:25 2016] IPVS: __ip_vs_del_service: enter
```

Does it mean that there's some bug in IPVS?

I have the same kernel: `4.4.0-36-generic`

**Comment by LK4D4** [comment] 2016-09-20 18:20
ping @mrjana @aboch

**Comment by Vanuan** [comment] 2016-09-20 18:32
I'm using DigitalOcean's private network for swarm. Maybe there was an outage and Docker couldn't restore its mesh routing? Though https://status.digitalocean.com/ doesn't show any outage.

@burdiyan can you check `dmesg` to see if this has happened at the same time as to me? When did you create swarm mode? Before or after 13:00 UTC?

**Comment by Vanuan** [comment] 2016-09-20 19:11
It looks like it's not DNS, it's traffic is not going between containers.
As far as I understrand LVS/IPVS, all containers appear to be on the same network.
So when I ping container that is on another host, but on the same overlay network, it should work.
But for some reason it doesn't.

I suspect that if I recreate swarm it would work. But I want to debug the issue so that it wouldn't happen again.

**Comment by Vanuan** [comment] 2016-09-20 19:18
Docker does see the other node as alive (using virtual ip address). If it didn't, it would've created containers on the manager node, right? So it's only the overlay network that doesn't work.

**Comment by Vanuan** [comment] 2016-09-20 20:02
Restarting docker daemon on both hosts resolved the issue.
Don't know how to reproduce and what was the cause.
I expect it to return in a few weeks. Would use suggestions how to troubleshoot it.

**Comment by Vanuan** [comment] 2016-09-20 20:17
Pinging container still doesn't work, though connect works. Looks like my troubleshooting wasn't correct.

**Comment by mrjana** [comment] 2016-09-20 20:59
@burdiyan @Vanuan If you see any state related issues please check the daemon logs to see if there are any gossip related errors (which starts with memberlist)

**Comment by burdiyan** [comment] 2016-09-20 22:06
I just tried the same thing with virtualbox on a local machine. Everything works as expected. My Swarm Mode in DigitalOcean was created 15 days ago, and until now I didn't try any load balancing features.

**Comment by burdiyan** [comment] 2016-09-20 22:07
I think a found some sort of path. In DigitalOcean I had a cluster of 3 nodes, and all 3 were managers. I demoted two of them, and now DNS resolving works as expected.

**Comment by xiaods** [comment] 2016-09-21 10:23
so this bug is present in v1.12?

**Comment by Vanuan** [comment] 2016-09-21 16:45
@xiaods why you're asking? have you seen something similar in previous versions?

@burdiyan would you mind checking `dmesg -T` and copying the lines at the time it wasn't working?

**Comment by burdiyan** [comment] 2016-09-21 16:52
I have to recreate the cluster and try again, because I accidentally removed it today :( Will try to do this these days.

**Comment by Vanuan** [comment] 2016-09-21 16:55
Have you removed the droplet? I mean you can run `dmesg -T` and scroll up to the September 20th

**Comment by burdiyan** [comment] 2016-09-21 17:15
I removed the Droplet. `docker-machine rm` was too easy to mistype.

**Comment by burdiyan** [comment] 2016-09-21 22:04
I'm unable to reproduce the issue. Was playing around with new droplets, but everything works as expected. How the heck I could remove those droplets before :(

**Comment by Vanuan** [comment] 2016-09-22 01:19
Let's wait for two weeks to see if it's reproducible. I've sent a support ticket to DO with a question whether they have any clue what's happened at that time.

**Comment by navinSing** [comment] 2016-09-22 08:23
facing same problem

**Comment by Vanuan** [comment] 2016-09-22 08:37
@navinSing Are you using DigitalOcean? Can you please show `dmesg -T` output? Is there something interesting at  Sept 20th 13:00 UTC?

**Comment by navinSing** [comment] 2016-09-22 08:43
Not using digital ocean, but i am not able to ping the tasks by VIPs from another host .. thus "Swarm mode DNS lookup resolves only IPs from the same host", fails to ping VIP from another host.

**Comment by navinSing** [comment] 2016-09-22 10:59
>> trying using either using task names or directly using task IP

neither of them work ? 

For:  directly using task IP
i just went into task on one host with : docker exec -it  463a4e611092 bash
and then pinged a task on another host : ping 10.0.0.5
and it din't worked, while pinging task on same host works.


For : task name ( `docker service ps servicea` : just shows task id )
```
docker service ps -a servicea
unknown shorthand flag: 'a' in -a
See 'docker service ps --help'.
 
```
cannot get the Name from /tasks endpoint

docker -v 
Docker version 1.12.1, build 23cf638

**Comment by Vanuan** [comment] 2016-09-22 12:08
AFAIK, ping is not supposed to work. Docker does some magic, so that only servicename:port works.

**Comment by thaJeztah** [comment] 2016-09-22 12:15
@navinSing I commented here; https://github.com/docker/docker/issues/26316#issuecomment-248880933

**Comment by navinSing** [comment] 2016-09-22 12:23
@Vanuan @thaJeztah 
there is no magic, everything works by law of nature(code)
ping only worked for same host

**Comment by xiaods** [comment] 2016-09-25 09:20
this is not bug?

**Comment by Vanuan** [comment] 2016-09-26 08:09
Just happened again.

@mrjana Seeing a log of errors:

```
Sep 26 07:28:21 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:21.013134762Z" level=warning msg="2016/09/26 07:28:21 [WARN] memberlist: Refuting a suspect message (from: docker-512mb-fra1-01)\n"
...
Sep 26 07:28:21 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:21.013502184Z" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=5bc08l132tu14zo9dbqd5v90y node.session=7o49rx6q4vpnvgsvcctf6npni task.id=40r0vc2zbgs2pmlb2op3m1vnb
...
Sep 26 07:28:21 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:21.046679436Z" level=error msg="task unavailable" method="(*Dispatcher).processTaskUpdates" module=dispatcher task.id=9f1irm3u17vuxpwohbt6t71ef
...
Sep 26 07:28:21 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:21.071709065Z" level=warning msg="cannot find target task in store" method="(*Dispatcher).UpdateTaskStatus" node.id=5bc08l132tu14zo9dbqd5v90y node.session=7o49rx6q4vpnvgsvcctf6npni task.id=5mym9sxrc01elttm43j6cp6s2
...
Sep 26 07:28:21 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:21.173004321Z" level=error msg="task unavailable" method="(*Dispatcher).processTaskUpdates" module=dispatcher task.id=2ldhufcvc6o2u96tnnqx06o3x

```

Few seconds after that:

```
Sep 26 07:28:31 ubuntu-1gb-fra1-01 dockerd[8954]: message repeated 4 times: [ time="2016-09-26T07:28:31Z" level=info msg="Firewalld running: false"]
Sep 26 07:28:32 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:32.012348902Z" level=info msg="Failed to delete real server 10.0.9.17 for vip 10.0.9.8 fwmark 259: no such process"
Sep 26 07:28:32 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:32.014198365Z" level=error msg="Failed to delete a new service for vip 10.0.9.8 fwmark 259: no such process"
Sep 26 07:28:32 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:32Z" level=info msg="Firewalld running: false"
Sep 26 07:28:32 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:32Z" level=info msg="Firewalld running: false"
Sep 26 07:28:32 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:32Z" level=error msg="setting up rule failed, [-t mangle -D OUTPUT -d 10.0.9.8/32 -j MARK --set-mark 259]:  (iptables failed: iptables --wait -t mangle -D OUTPUT -d 10.0.9.8/32 -j MARK --set-mark 259: iptables: No chain/target/match by that name.\n (exit status 1))"
Sep 26 07:28:32 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:32.148111672Z" level=error msg="Failed to add firewall mark rule in sbox /var/run/docker/netns/cdfd92d4c9aa: reexec failed: exit status 5"
```


```
Sep 26 07:28:32 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:32.562165354Z" level=error msg="fatal task error" error="task: non-zero exit (1)" module=taskmanager task.id=a5hvxn9n9gvppga8vz9ymdjqx
```

```
Sep 26 07:28:50 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:50.735572920Z" level=error msg="fatal task error" error="task: non-zero exit (1)" module=taskmanager task.id=6f1yxji780zt3jcri173yeuo0
Sep 26 07:28:50 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:50.840528650Z" level=error msg="Error getting node : node  is ambiguous (2 matches found)"
Sep 26 07:28:50 ubuntu-1gb-fra1-01 dockerd[8954]: time="2016-09-26T07:28:50.840996509Z" level=error msg="Handler for GET /v1.24/nodes/ returned error: node  is ambiguous (2 matches found)"
```


And several minutes later:

```
Sep 26 07:43:43 ubuntu-1gb-fra1-01 dockerd[25127]: time="2016-09-26T07:43:43.862848689Z" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"start-container\", Id:\"25701af3e82eb95c4b847b7da781092661ec2658ca76391467858bb0fea9e873\", Status:0x0, Pid:\"\", Timestamp:(*timestamp.Timestamp)(0xc821e21db0)}"
Sep 26 07:43:43 ubuntu-1gb-fra1-01 dockerd[25127]: time="2016-09-26T07:43:43.866623689Z" level=debug msg="Name To resolve: edr-static."
Sep 26 07:43:43 ubuntu-1gb-fra1-01 dockerd[25127]: time="2016-09-26T07:43:43.866988652Z" level=debug msg="Query edr-static.[1] from 172.18.0.6:35366, forwarding to udp:8.8.8.8"
Sep 26 07:43:43 ubuntu-1gb-fra1-01 dockerd[25127]: time="2016-09-26T07:43:43.867286854Z" level=debug msg="Name To resolve: edr-static."
Sep 26 07:43:43 ubuntu-1gb-fra1-01 dockerd[25127]: time="2016-09-26T07:43:43.867537395Z" level=debug msg="Query edr-static.[28] from 172.18.0.6:35813, forwarding to udp:8.8.8.8"
```

**Comment by Vanuan** [comment] 2016-09-26 08:22
This time restarting docker didn't help.

**Comment by Vanuan** [comment] 2016-09-26 08:54
Now it can resolve domain names, but resolved ips don't seem to match container ips.

**Comment by Vanuan** [comment] 2016-09-26 10:01
Trying to reinitialize the swarm. Seeing this:

```
Error response from daemon: could not choose an IP address
to advertise since this system has multiple addresses on interface eth0
(139.59.x.x and 10.19.x.x) - specify one with --advertise-addr
```

But I want to use eth1 (10.135.x.x).

**Comment by Vanuan** [comment] 2016-09-26 10:26
I'm starting to suspect that it has never worked and the times it worked it was because all critical containers were on the same host.

**Comment by Vanuan** [comment] 2016-09-26 10:39
Maybe it's because I'm using only one manager?

**Comment by Vanuan** [comment] 2016-09-26 10:44
I'll try 2-node configuration with both to be managers and see if it'll reproduce.

**Comment by xiaods** [comment] 2016-09-26 12:24
OMG! are u sure the host's ntp is sync?

**Comment by JettJones** [comment] 2016-09-26 20:28
I saw similar lack of DNS resolution across two swarm hosts, running on AWS.   `date` showed times within 10 seconds between the hosts, but I setup ntp and restarted both docker services anyway based on recommendations here. Afterward resolution is working again.

Aside: `docker network ls` only shows services on the current host - not sure if that's intended, but it at least helped identify and explain two sets of working / non-working hosts while I was debugging.

**Comment by mrjana** [comment] 2016-09-26 20:40
@Vanuan Can you start you swarm with the correct `--advertise-addr` option and see how it goes? It seems like your gossip channel was never bootstrapped properly. If possible the next time you are having issues please attach daemon logs from the problem node.

**Comment by Vanuan** [comment] 2016-09-27 09:04
@mrjana I'm using ip address from eth1. Isn't it correct?

```
ip addr show eth0
...
    inet 46.101.x.x/20 brd 46.101.111.255 scope global eth0 <-- public ip
    inet 10.19.x.x/16 scope global eth0 <-- not sure what it is, maybe Digital Ocean's admin network?
...
ip addr show eth1
...
    inet 10.135.x.x/16 brd 10.135.255.255 scope global eth1 <-- user's private network
...
```

My public network is eth0, my private network is eth1. Should I only use public interface for advertise-addr? Is there an option to choose a specific ip on a specific interface?

I tried both private and public interfaces. It's 100% reproducible. Containers on one node can't connect to containers on another node. It's the same with both nodes.

It looks like the DNS issue is a separate thing. Should I create another issue or this one is fine? It looks to be also related to a typical DigitalOcean configuration.

Here are the repro steps with timestamps related to the log attached:

```
docker swarm init  --advertise-addr 10.135.x.x
# 10:48:33 +0200
# join on other node
# 10:49:02 +0200
docker network create \
  --driver overlay \
  --subnet 10.0.9.0/24 \
  --opt encrypted \
  testnetwork
# 10:50:17 +0200 
docker service create --replicas 1 --name nginx1 --network testnetwork nginx:1.10-alpine
docker service create --replicas 1 --name nginx2 --network testnetwork nginx:1.10-alpine
# 10:50:46 +0200
# From worker (other) node
docker exec -ti nginx2.1.a39gdqqk3mbrxmqogdfr9zeii /bin/sh
# trying to telnet...
telnet nginx1 80
# telnet hangs
# 10:53:02 +0200
# The same from manager node
# 10:54:22 +0200
```

[syslog.txt](https://github.com/docker/docker/files/495007/syslog.txt)

**Comment by Vanuan** [comment] 2016-09-27 09:53
Isn't it a IPVS problem? Here's some configuration:

```
root@ubuntu-1gb-fra1-01:/var/run/docker/netns# nsenter --net=1ab3896944ab sh
# iptables -nvL -t mangle
Chain PREROUTING (policy ACCEPT 12 packets, 720 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 12 packets, 720 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 70 packets, 3584 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   28  1372 MARK       all  --  *      *       0.0.0.0/0            10.0.9.4             MARK set 0x132
    0     0 MARK       all  --  *      *       0.0.0.0/0            10.0.9.2             MARK set 0x133

Chain POSTROUTING (policy ACCEPT 42 packets, 2212 bytes)
 pkts bytes target     prot opt in     out     source               destination         
# ipvsadm
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
FWM  306 rr
  -> 10.0.9.5:0                   Masq    1      0          0         
FWM  307 rr
  -> ubuntu-1gb-fra1-01:0         Masq    1      0          0         
```

DNS resolution:
```
resolved nginx1: 10.0.9.2 <-- is this a load balancer?
real nginx1: 10.0.9.3
resolved nginx2: 10.0.9.4 <-- is this a load balancer?
real nginx2: 10.0.9.5
```

What these servers are (10.0.9.2 and 10.0.9.4)? Are they load balancers?

**Comment by Vanuan** [comment] 2016-09-27 11:43
Got it working by creating another overlay network.
But it would be helpful to know how to debug those things in the future.

**Comment by colinmollenhour** [comment] 2016-09-27 13:54
I have had similar issues and don't even have docker in production yet.. Currently 3 nodes on bare metal at packet.net. php-fpm running on nodes 1 and 3, mysql on node 2. php-fpm on node 3 can connect to mysql, node 1 cannot. Sometimes it is node 1 that can connect and node 3 cannot. Occasionally they both work but I log back in the next day and then something is broken.. Sometimes it is just DNS that is broken, sometimes I can't connect (not using ping, using mysql client) using the direct IP (either the VIP or the container IP). Overall it seems overlay networks just aren't stable.. Would love to know how to debug further though.

**Comment by Vanuan** [comment] 2016-09-28 11:51
Just happened again when I've run a container with some heavy processing.

```
2016/09/28 10:32:54 [DEBUG] memberlist: Potential blocking operation. Last command took 1.975834125s
2016/09/28 10:32:54 [INFO] memberlist: Suspect ubuntu-1gb-fra1-02 has failed, no acks received
...
2016/09/28 10:33:02 [INFO] memberlist: Marking ubuntu-1gb-fra1-02 as failed, suspect timeout reached
...
2016-09-28T10:33:08.580613845+02:00" level=error msg="agent: session failed" error="rpc error: code = 4 desc = context deadline exceeded" module=agent
...
2016-09-28T10:33:13.024207504+02:00" level=error msg="error reestabilishing connection to leader" error="raft: no elected cluster leader"
...
2016/09/28 10:33:16 [WARN] memberlist: Refuting a suspect message (from: ubuntu-1gb-fra1-02)
...
[INFO] memberlist: Suspect ubuntu-1gb-fra1-02 has failed, no acks received
...
error reestabilishing connection to leader" error="raft: no elected cluster leader
...
2016/09/28 10:33:29 [INFO] memberlist: Marking ubuntu-1gb-fra1-02 as failed, suspect timeout reached
...
error reestabilishing connection to leader" error="raft: no elected cluster leader
...
[DEBUG] memberlist: Failed UDP ping: ubuntu-1gb-fra1-02 (timeout reached)
```

And then I've got the out of memory:

```
Sep 28 08:34:09 ubuntu-1gb-fra1-01 kernel: [2490528.239936] java invoked oom-killer: gfp_mask=0x24280ca, order=0, oom_score_adj=0
Sep 28 08:34:09 ubuntu-1gb-fra1-01 kernel: [2490528.239941] java cpuset=a873e9ffc886ae0ce0ff742aa99b357d10375b8dc0e2e828c11ccf0f2ff8b052 mems_allowed=0
Sep 28 08:34:09 ubuntu-1gb-fra1-01 kernel: [2490528.239948] CPU: 0 PID: 26237 Comm: java Not tainted 4.4.0-36-generic #55-Ubuntu
Sep 28 08:34:09 ubuntu-1gb-fra1-01 kernel: [2490528.239949] Hardware name: DigitalOcean Droplet, BIOS 20160425 04/25/2016
Sep 28 08:34:09 ubuntu-1gb-fra1-01 kernel: [2490528.239951]  0000000000000286 00000000a293fd51 ffff88003dacfb08 ffffffff813f13b3
Sep 28 08:34:09 ubuntu-1gb-fra1-01 kernel: [2490528.239954]  ffff88003dacfd00 ffff88003ca29b80 ffff88003dacfb78 ffffffff8120959e
Sep 28 08:34:09 ubuntu-1gb-fra1-01 kernel: [2490528.239956]  ffffffff81ccf5c7 0000000000000000 ffffffff81e66760 0000000000000206
Sep 28 08:34:09 ubuntu-1gb-fra1-01 kernel: [2490528.239959] Call Trace:
Sep 28 08:34:09 ubuntu-1gb-fra1-01 kernel: [2490528.239967]  [<ffffffff813f13b3>] dump_stack+0x63/0x90
```

So it seems like that default DigitalOcean configuration doesn't have any swapping. And it causes some vital processes to die.

So I need to dedicate some about of memory for each service and add monitoring to see which service is a memory hog and dedicate a separate machine for it (or fix a memory leak if any)

Shouldn't docker be able to restore in such an event?

Shouldn't the default resource limit setting prevent memory to be exhausted?

**Comment by mavenugo** [comment] 2016-09-28 12:10
@Vanuan @colinmollenhour we have resolved a bunch of issues in the upcoming 1.12.2 release and the RC build is available for trying : https://github.com/docker/docker/releases/tag/v1.12.2-rc1. Could you pls give it a try ? am not sure if this will solve the problems you were facing. But atleast it will make it easy to troubleshoot from a stable point.

**Comment by Vanuan** [comment] 2016-09-28 12:22
Thanks. So it might actually be the recovery after failure on both nodes. [Documentation suggests](https://docs.docker.com/engine/swarm/admin_guide/#/run-manager-only-nodes) that assigning resource unconstrained tasks to manager is risky. Now I see why.

**Comment by Vanuan** [comment] 2016-09-28 15:12
@colinmollenhour Well, it might be one of the most reliable ways to reproduce this issue.

**Comment by xiaods** [comment] 2016-10-13 02:20
Does anyone reproduce steps to check if the bug is fixed in upstream branch?

**Comment by mavenugo** [comment] 2016-10-17 20:16
This is resolved in 1.12.2. Closing the issue. please re-open this if the issue is still seen in 1.12.2

**Closed by mavenugo** 2016-10-17 20:16 UTC
Labels: area/networking, area/swarm, kind/bug, version/1.12

**Comment by cdstelly** [comment] 2017-01-13 01:40
I'm having this exact issue in 1.12.6.

**Comment by YouriT** [comment] 2017-01-18 14:19
@mavenugo could you elaborate on what was exactly the problem to enable people to see if theirs is related to this or not? Or link the PR of this or something?

**Comment by saabeilin** [comment] 2017-03-24 21:05
Seems I'm having same/related problem. Containers running on different nodes are not resolved at all.
`Docker version 17.03.0-ce` on all nodes.

**Comment by mavenugo** [comment] 2017-03-24 22:56
@saabeilin can you please get the output for `docker network inspect <network-name>` and make sure the Peers are properly learnt ?

**Comment by saabeilin** [comment] 2017-03-24 23:15
@mavenugo They are not. Each host only lists itself as peers, stating, though, the correct IPv6 address. Btw, when creating the swarm, I used the IPv6 as advertise address. It might be a related to the issue I just posted on SO: http://stackoverflow.com/questions/43010097/docker-swarm-over-ipv6

**Comment by mavenugo** [comment] 2017-03-24 23:32
@saabeilin I havent tried ipv6 as `advertise-address` since overlay driver doesn't support ipv6 vtep yet. Can you paste the actual error with the proper ipv6 address mentioned ? It seems the error is originating from memberlist library and failing on parsing the ipv6 address.

**Comment by luciantuce** [comment] 2017-12-11 09:55
I have exactly the same issue with 17.05.0-ce. Containers attached to the same network are only reachable from the same host.
