### ISSUE TITLE
Corrupted images due to disk full cannot be deleted with fatal error

### ISSUE THREAD

**Issue by akram** [docker/docker#11178] opened 2015-03-05 17:01 UTC
it seems that am some point, I got a full disk and this probably corrupted one of my downloaded images.
if if do
```
[root@172 ~]# docker pull openshift/origin-pod:v0.3.2
Pulling repository openshift/origin-pod
62e681937222: Download complete
7802f45d9ac0: Download complete
FATA[0001] unexpected end of JSON input
```

If I have a look at my imagesm here is what I have:
```
REPOSITORY                            TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                                <none>              a196bdc4d310        22 hours ago        292 MB
openshift/origin-pod                  v0.3.2              62e681937222        11 days ago         957.9 kB
```

and If I try to delete the image , I got an error:

```
[root@172 ~]# docker rmi 62e681937222
Error response from daemon: No such image: 62e681937222
FATA[0000] Error: failed to remove one or more images
[root@172 ~]#
```

does an integrety check exists for images ?
can I force the re-pull of an image? such an option does not seem to exists

**Comment by vperron** [comment] 2015-07-28 09:31
I can confirm, had the same issue on a server and had to entirely wipe the /var/lib/docker folder to get started again :(

**Comment by cpuguy83** [comment] 2015-09-15 15:42
Is this still an issue.
What graph driver are you using?
Can you provide the output of `docker info` and `docker version`?

If using devicemapper with a static docker binary, this is known to cause corruption issues and is no longer supported.

**Comment by thaJeztah** [comment] 2015-10-20 05:22
closing because there was no feedback

**Closed by thaJeztah** 2015-10-20 05:22 UTC
Labels: status/more-info-needed
