### ISSUE TITLE
Docker stack Error response from daemon: network *_default not found

### ISSUE THREAD

**Issue by mostolog** [docker/docker#31226] opened 2017-02-21 17:21 UTC
**Description**

Docker is unable to deploy a simple stack, reporting "Error response from daemon: network _myapp_\_default not found"

**Steps to reproduce the issue:**
1. Create overlay attachable network mynet
```
$docker network create --attachable --driver overlay mynet
kc9u8lgi1yugpudo5qk6o2g58
$docker network inspect mynet
[
    {
        "Name": "mynet",
        "Id": "kc9u8lgi1yugpudo5qk6o2g58",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": true,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4098"
        },
        "Labels": null
    }
]
```
2. Write stack.yml compose-file
```
$cat stack.yml
version: "3"
networks:
  default:
    external:
      name: mynet
services:
  elasticsearch:
    command: "elasticsearch -E cluster.name=myapp -E node.name=elasticsearch -E discovery.zen.ping.unicast.hosts=elasticsearch"
    #hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    image: "elasticsearch:5.2.1"
    #ulimits:
    #  memlock: -1
    #  nofile: 65536
    #  nproc: 2048
```

3. Run docker stack deploy command
```
$docker stack deploy --compose-file stack.yml myapp
Creating service myapp_elasticsearch
Error response from daemon: network myapp_default not found
```

**Describe the results you received:**

> Creating service myapp_elasticsearch
> Error response from daemon: network myapp_default not found

**Describe the results you expected:**

A simple elasticsearch stack being deployed

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 42
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 116
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ph56dmuj9xyp7v0mxngpi4wmg
 Is Manager: true
 ClusterID: jmdwt0h7bwcobihnfignepzwr
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 155.54.212.5
 Manager Addresses:
  155.54.212.5:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.4 GiB
Name: computer
ID: E4N3:47NS:3QGR:EWSK:L4ZR:RWXL:JJXE:U53F:4NIU:N6XK:6OVD:WY4C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by g0t4** [comment] 2017-02-22 16:20
I've had this issue too when removing a stack, with docker stack rm, the network lingers for about 10 seconds before its finally removed. So, if I call docker stack deploy in that timeframe I get the above error too.

**Comment by mostolog** [comment] 2017-02-23 09:01
@g0t4 That's seems another issue: https://github.com/docker/docker/issues/29293

**Comment by g0t4** [comment] 2017-02-23 14:34
@mostolog Same error message either way. If the network already exists this error occurs. As soon as the network is cleaned up from a `docker stack rm` then the error doesn't happen.

**Comment by thaJeztah** [comment] 2017-03-20 15:32
This looks like a duplicate of https://github.com/docker/docker/issues/31228, and should be fixed by https://github.com/docker/docker/pull/31258, which is part of 17.03.1 (release candidate is currently available for testing, but GA should be released later this week)

**Comment by mostolog** [comment] 2017-03-20 16:14
Thanks @thaJeztah I'll let you know if it still have issues ;)

**Comment by thaJeztah** [comment] 2017-03-22 12:27
Let me go ahead and close this for housekeeping, but let me know if it's still an issue, then I'll reopen 👍

**Closed by thaJeztah** 2017-03-22 12:27 UTC
Labels: area/bundles, area/networking, version/1.13

**Comment by evgenyfadeev** [comment] 2017-09-08 14:23
I have the same issue on Docker version 17.06.2-ce, build cec0b72
It is not reproducible - sometimes the stack deploys, some other times not.

When it deploys, the network is brought up first; on other tries a docker container is brought up before the network and it all fails with the message that network is not found.

**Comment by cazacugmihai** [comment] 2017-10-22 18:14
HI,

I'm still having this issue after running:
```
docker stack rm ${STACK_NAME}
docker swarm leave --force
```
The network is still there for a few seconds. To solve this, I have to run:

```
docker network rm ${NETWORK_NAME}
```
Docker:
```
docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:02:56 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
Thanks!

**Comment by DBLaci** [comment] 2017-12-05 15:27
I encounter this error with docker-17.11 with a really simple stack deploy. The deploy not even declares network.

    "starting container failed: No such network: logspout_default"

```
# docker network ls
NETWORK ID          NAME                    DRIVER              SCOPE
ff549dece2ca        bridge                  bridge              local
0e5d3fff5cad        docker_gwbridge         bridge              local

... 7 other local scope network

a87e9c85fcef        host                    host                local
6f8558ifs981        ingress                 overlay             swarm
sp6jai4grfrt        logspout_default        overlay             swarm
c1a69addad32        none                    null                local
```

**Comment by oppianmatt** [comment] 2018-01-19 12:43
This is still happening and pretty much all the time now. I'm not deleting any network but just trying to update a stack from a compose file on a swarm. Did just upgrade docker versions.

```
> docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false

```

```
cmd: docker-compose config | docker stack deploy --prune --compose-file - --with-registry-auth pitchup

start: 2018-01-19 04:09:33.999066

end: 2018-01-19 04:09:38.357076

delta: 0:00:04.358010

msg: non-zero return code

stdout: Creating network pitchup_esnet
Creating network pitchup_traefiknet
Creating network pitchup_redisnet
Creating network pitchup_solrnet
Creating network pitchup_gunicornnet
Creating network pitchup_varnishnet
Creating service pitchup_traefik
Creating service pitchup_celery_payments
Creating service pitchup_vstatd

stderr: Some services (celery_beat, celery_default, celery_payments, elasticsearch1, elasticsearch2, filebeat, gunicorn, kibana, kibana_auth, logstash, memcached, nginx, nonadc, redis, solr, static, traefik, vac, vac_mongo, varnish_agent, varnish_plus, varnishncsa, vstatd, vstatdprobe) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
failed to create service pitchup_vstatd: Error response from daemon: network pitchup_default not found
```

Note that the vstatd service had some `ports` exposed. But didn't need them so removed the ports and the error went away (until a later service).

```
cmd: docker-compose config | docker stack deploy --prune --compose-file - --with-registry-auth pitchup

start: 2018-01-19 12:41:08.051568

end: 2018-01-19 12:41:09.271136

delta: 0:00:01.219568

msg: non-zero return code

stdout: Creating service pitchup_redis

stderr: Some services (celery_beat, celery_default, celery_payments, elasticsearch1, elasticsearch2, filebeat, gunicorn, kibana, kibana_auth, logstash, memcached, nginx, nonadc, redis, solr, static, traefik, vac, vac_mongo, varnish_agent, varnish_plus, varnishncsa, vstatd, vstatdprobe) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
failed to create service pitchup_redis: Error response from daemon: network pitchup_default not found
```


Thing is, there is a network called pitchup_default:

```
> docker network ls
NETWORK ID          NAME                  DRIVER              SCOPE
6bad06a20b35        bridge                bridge              local
9bd7bf7768a1        docker_gwbridge       bridge              local
53ed711d74fa        host                  host                local
qfdndr8bc0yx        ingress               overlay             swarm
3b9e758a8874        none                  null                local
q1bfpokriztp        pitchup_default       overlay             swarm
n7ugooy26htg        pitchup_esnet         overlay             swarm
i99vsh93ut9k        pitchup_gunicornnet   overlay             swarm
oxhet5sk5faw        pitchup_redisnet      overlay             swarm
iqjnn6kgrpbh        pitchup_solrnet       overlay             swarm
t4ph5fg4l94m        pitchup_traefiknet    overlay             swarm
e09q59wua6z7        pitchup_varnishnet    overlay             swarm

```

This is a swarm cluster of 1 host

**Comment by thaJeztah** [comment] 2018-01-19 13:25
@oppianmatt could you provide an as-minimal-as-possible docker-compose file to reproduce the issue? (e.g., just a compose file with one or two services that use a standard image, such as `nginx:alpine`)

**Comment by oppianmatt** [comment] 2018-01-21 22:11
Sorry can't really. This seems to happen when I rm the stack and then try bring it back. Even when bringing it back is hours later. When adding and removing networks in the compose file and running docker stack deploy --prune it seems to have issues with the networks. Unable to create them like in this case. Or the name resolution of hosts on the networks stops resolving (if they use dnsrr it resolves, but the vip default way doesn't).

All in all it feels like swarm and stack deploy has issues when the networks change.

I don't even have any containers running and I get that stack deploy error with the network.

If I delete the `pitchup_default` network and try running stack deploy again it gives the error that `pitchup_gunicornnet` doesn't which you can see it does above. It's like the stack doesn't think all those networks are part of the stack.

Perhaps it's the attachable part? networks are defined like so:

```
networks:
  esnet:
    driver: overlay
    attachable: true
  traefiknet:
    driver: overlay
    attachable: true
  solrnet:
    driver: overlay
    attachable: true
  redisnet:
    driver: overlay
    attachable: true
  gunicornnet:
    driver: overlay
    attachable: true
  varnishnet:
    driver: overlay
    attachable: true
  varnishnet:
    driver: overlay
    attachable: true
  default:
    driver: overlay
    attachable: true
```

I know in swarm the default is `overlay` and no need to specify, but if you don't specify overlay and then you run a `docker-compose run`  command that needs the network, it defaults to non overlay and creates a conflict with the network name. By having the network named defined as `overlay` also lets docker-compose run and attach to the networks.

To fix the original issue I have to run `docker system prune --force` to delete all those networks. Then I can redeploy the stack.

**Comment by oppianmatt** [comment] 2018-01-21 23:40
Actually typing that up got me thinking and I think I can reliably reproduce it. If I delete the stack with `stack rm` and then run a `docker-compose run` command which creates the networks. Later on when I go to create the stack it has an error because it can't create the network(s) since some already exist with the same name.

**Comment by soar** [comment] 2018-03-10 21:34
Today I've got same issue. I had stack deployed on node1 (leader) and I was logged in on node3 (reacheable, but not actually leader). Then I called `docker stack rm` on node3 and tried to create stack on `node1` again - and got same error. I've tried several times - nothing happens. And now I see:

on `node3`:

```
# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
27ed4ce9de56        bridge              bridge              local
617cf866d5bd        docker_gwbridge     bridge              local
3db70865c2ac        host                host                local
s3v2c7xmavsx        ingress             overlay             swarm
3ba25f9b4a70        none                null                local
```

on `node1`:

```
# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
slcw3alrpqtu        mystack_default    overlay             swarm
ccef8f87d4ab        bridge              bridge              local
86aae063b4c6        docker_gwbridge     bridge              local
3f70609d196c        host                host                local
s3v2c7xmavsx        ingress             overlay             swarm
b5b9248ca12b        none                null                local
```

**Comment by w7089** [comment] 2018-04-30 16:50
Having the same issue with _17.10.0-ce_
Another issue was some containers in output of:

> docker ps -a 

were in status:

> Removal In Progress

So restarting each docker daemon in the swarm helped:
```
sudo systemctl stop docker
sudo systemctl start docker
```

**Comment by wyqydsyq** [comment] 2018-06-07 05:20
The issue is caused by attempting to start the stack before the old network has finished removing, you can work around this by explicitly polling and waiting for the network to be removed: https://github.com/moby/moby/issues/29293#issuecomment-318852549

**Comment by romash1408** [comment] 2018-09-21 07:20
> So restarting each docker daemon in the swarm helped:
> 
> ```
> sudo systemctl stop docker
> sudo systemctl start docker
> ```

@w7089, thank you, your answer helped to me.
Just want to point that systemctl have command ```restart```, so
```
sudo systemctl restart docker
```
is enough :)

**Comment by aryashreep** [comment] 2018-12-16 16:05
> > So restarting each docker daemon in the swarm helped:
> > ```
> > sudo systemctl stop docker
> > sudo systemctl start docker
> > ```
> 
> @w7089, thank you, your answer helped to me.
> Just want to point that systemctl have command `restart`, so
> 
> ```
> sudo systemctl restart docker
> ```
> is enough :)

Thank you @w7089 & @romash1408 it helps me a lot.

**Comment by biske** [comment] 2019-12-12 09:13
> > So restarting each docker daemon in the swarm helped:
> > ```
> > sudo systemctl stop docker
> > sudo systemctl start docker
> > ```
> 
> @w7089, thank you, your answer helped to me.
> Just want to point that systemctl have command `restart`, so
> 
> ```
> sudo systemctl restart docker
> ```
> 
> is enough :)

This solved issue for me.

**Comment by antitrustx** [comment] 2020-03-01 14:09
I had the same issue. Its happens when use docker stack rm, and then quick deploy before network removed from stack.
How to fix: systemctl restart docker - fix this problem
How to prevent issue: if you want to use docker stack rm, you shall wait, until docker remove all neccecary networks of your stacks. You can watch it by running after docker stack, this command: watch -n.1 docker network ls. and just wait unitil networks deletes, and just after this run new deploy.

**Comment by ams45** [comment] 2020-04-02 10:47
`systemctl restart docker` does not worked for me. I removed the swarm and re-initiated it again. After that `docker network ls` was not showing me the network.

**Comment by antitrustx** [comment] 2020-04-03 08:20
you shall check in all nodes `docker network ls` and restart docker only thouse nodes where is network wont delete !

**Comment by adarshpk** [comment] 2020-06-01 06:14
Any idea on the root cause of this?
`systemctl restart docker` isn't really a scalable solution.
