### ISSUE TITLE
Docker can't resolve anymore during build unless service restarted

### ISSUE THREAD

**Issue by aijanai** [docker/docker#29588] opened 2016-12-20 10:46 UTC
**Description**
Building process can't reach Internet anymore and thus can't download new packages.
The problem is temporarily solved if I restart Docker service; for a single build, it allows going out to Internet. Then, after a while, it restart negating external access. 

**Steps to reproduce the issue:**
1. build a container with `docker build -t somename .` (where a local Dockerfile is present)
2. hang at first encountered `apt-get update` or `bundle install` or `npm install` or such
3. restart Docker with `sudo service docker restart`
4. successfully build a container 

I expect the container to be able to build every time with network access  without having to reset docker server each time

It's happening since 19/12/2016

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 86
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 140
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.707 GiB
Name: aiMacBookPro
ID: BEFQ:LYRP:E22V:X3WB:5EMX:34AB:OPFP:7ITH:YAPQ:KGQD:I5RM:ORLT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Local PC

**Comment by aijanai** [comment] 2016-12-20 10:57
Update:

I can't even reach started containers unless I restart docker daemon.

**Steps to reproduce**
1. start fresh container
2. can't curl to it
3. destroy container; restart docker; start new container
4. now I can reach it as long as it is up
5. destroy container; repeat from step 1.

**Comment by marcbradshaw** [comment] 2016-12-22 00:42
We are having similar random resolver failures after updrading to 1.12.5 from 1.12.3.  An already running container is unable to resolve for a time, however resolving works when tested some time later.

**Comment by aijanai** [comment] 2016-12-27 14:08
so? Ideas?

**Comment by thaJeztah** [comment] 2016-12-27 15:31
Have you checked if IPTables rules were modified/removed by another process? Docker creates IPTables rules when it starts; if another process removes those rules while docker is running, it's possible you get such problems.

**Comment by aijanai** [comment] 2017-01-02 09:33
Nope. Here are my rules after the restart:

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-ISOLATION  all  --  0.0.0.0/0            0.0.0.0/0           
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

```

**Comment by thaJeztah** [comment] 2017-01-02 09:47
ping @sanimej any ideas?

**Comment by aijanai** [comment] 2017-01-02 12:39
BTW, rolling baclk to 1.12.3 didn't restore the normal behaviour :/
Is this thing happening in 1.13 too?

**Comment by thaJeztah** [comment] 2017-01-02 13:49
fwiw, the iptables rules after "restart" look correct _if_ no container with published ports is running; are iptables rules correctly updated when a container is started that publishes ports? Also, what do the iptables rules look like in a situation where it _doesn't_ work correctly?

**Comment by aijanai** [comment] 2017-01-02 14:16
This is the chain DOCKER after first docker-compose up, working good

```
Chain DOCKER (2 references)
target     prot opt source               destination         
ACCEPT     tcp  --  0.0.0.0/0            172.18.0.2           tcp dpt:27017
ACCEPT     tcp  --  0.0.0.0/0            172.18.0.3           tcp dpt:6379
ACCEPT     tcp  --  0.0.0.0/0            172.18.0.4           tcp dpt:8008
ACCEPT     tcp  --  0.0.0.0/0            172.18.0.7           tcp dpt:5000
ACCEPT     tcp  --  0.0.0.0/0            172.18.0.8           tcp dpt:3000
```

It stays the same even during malfunctions, so I'd exclude iptables

**Comment by aijanai** [comment] 2017-01-02 14:22
Ok, maybe we got it: upon malfunction, **docker0 interface loses IP address**.

AFTER RESTART:
```
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:0e:7a:5b:7e brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:eff:fe7a:5b7e/64 scope link 
       valid_lft forever preferred_lft forever
```

UPON MALFUNCTION:
```
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:0e:7a:5b:7e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::42:eff:fe7a:5b7e/64 scope link 
       valid_lft forever preferred_lft forever
```

AFTER NEW RESTART:
```
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:0e:7a:5b:7e brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:eff:fe7a:5b7e/64 scope link 
       valid_lft forever preferred_lft forever
```

and it builds good.

So, what now? :)

**Comment by thaJeztah** [comment] 2017-01-02 14:59
Could this be NetworkManager interfering? Do you have NetworkManager installed and running? (`systemctl status network-manager`). I think network manager is known to cause issues in some situations; also see https://github.com/docker/docker/issues/4453 (this post may be helpful; http://support.qacafe.com/knowledge-base/how-do-i-prevent-network-manager-from-controlling-an-interface/)

**Comment by aijanai** [comment] 2017-01-02 15:28
Yes, I do have it.
I'll disable it and try

**Comment by aijanai** [comment] 2017-01-02 19:33
Nope. I've blacklisted docker0 from NM, as per screenshot:

```
ai_ja_nai@aiMacBookPro:~/wd-frontend$ nmcli dev status
DEVICE   TIPO      STATO        CONNESSIONE 
wlp3s0   wifi      collegato    LeonesWiFi  
docker0  bridge    non gestito  --          
lo       loopback  non gestito  --          
```

But docker0 still loses the IP address

**Comment by sanimej** [comment] 2017-01-04 21:55
@aijanai Can you try with NM completely disabled ?

**Comment by aijanai** [comment] 2017-01-09 07:42
I've disabled it (I thought it would have been easier, Ubuntu is too coupled to it) but nothing, same story. Even during the same build it breaks (first time you install npm/yarn for node.js and it goes ok, the second time it tries to actually install packages with npm/yarn and hangs in there).

Network manager doesn't seem to be the culprit.

**Comment by telegrapher** [comment] 2017-01-11 15:41
Hello,

I've found the same error. I'm running CentOS 7.2 and Docker 1.12.5.

I have Network Manager uninstalled.

It seems I'm triggering it also with docker compose ( 1.9.0 )

**Comment by telegrapher** [comment] 2017-01-11 15:49
I'm also observing my docker0 interface in the NO-CARRIER state.

**Comment by nickhsine** [comment] 2017-01-12 05:28
Hello,
I encountered the same problem for a while.
And I guess this problem might be fixed by using kernel version 4.x.

BTW, my kernel version of instances encountered that problem is 3.10.0-327.13.1.el7.x86_64.

**Comment by sanimej** [comment] 2017-01-12 17:38
@aijanai Is `docker0` losing the IP address randomly but it happens only if you do docker build ? Can you run the daemon with some containers but no build and see if the problem still happens ? You can also check if the kernel messages have anything about docker0 state change or IP removal.

**Comment by aijanai** [comment] 2017-01-16 12:12
Please note that the aforementioned does not happen in Ubuntu 14.04:

```
ubuntu@ip-172-30-2-185:~$ docker-compose version
docker-compose version 1.8.0, build 94f7016
docker-py version: 1.10.6
CPython version: 2.7.6
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014


ubuntu@ip-172-30-2-185:~$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64
```

**Comment by aijanai** [comment] 2017-01-20 20:20
After upgrading (see below versions), I can't reproduce the issue anymore; in other words, looks like the problem is gone.
Any aknowledgements from the other people affected?

```
ai_ja_nai@aiMacBookPro:~$ docker-compose version
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

ai_ja_nai@aiMacBookPro:~$ docker version 
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

ai_ja_nai@aiMacBookPro:~$ docker info 
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 69
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 132
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.707 GiB
Name: aiMacBookPro
ID: BEFQ:LYRP:E22V:X3WB:5EMX:34AB:OPFP:7ITH:YAPQ:KGQD:I5RM:ORLT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by sanimej** [comment] 2017-01-23 07:30
@aijanai The problem you had was because of IP getting removed from `docker0` bridge. That is very likely something specific to your environment. Definitely there is no change between 1.12.5 and 1.12.6 that could make any difference here.

**Comment by thaJeztah** [comment] 2017-01-23 12:12
Let me go ahead and close this issue, but happy to hear from @telegrapher if the issue is resolved after upgrading to 1.12.6

**Closed by thaJeztah** 2017-01-23 12:12 UTC
Labels: area/builder, version/1.12

**Comment by telegrapher** [comment] 2017-01-26 12:22
I'm upgrading all machines to Docker to 1.13.0 and CentOS to 7.3 the latest version. I will confirm if it works or reopen instead.

**Comment by telegrapher** [comment] 2017-01-30 17:22
The issue doesn't happen anymore with Docker 1.13.0. Thanks to everyone involved!!

**Comment by thaJeztah** [comment] 2017-01-30 18:16
Thanks for the update, and good to hear!

**Comment by fraviemor** [comment] 2020-02-24 23:54
This issue has been reproduced for me in last docker version (19.03.6).
I downgrade to 19.03.5 and still fails.

When i run a 'docker build' script, container and networks are created but docker0 interface lost ipv4 address and build fails with "getaddrinfo EAI_AGAIN" error.

Any idea?
