### ISSUE TITLE
Docker service restart

### ISSUE THREAD

**Issue by frimdo** [docker/docker#27551] opened 2016-10-19 17:10 UTC
### Feature idea
I belive docker service is missing a way to restart all replicas of service. 

The reason is, that if you want to for example reload config file you updated in volume, you have to restart whole container. Without this feature you have to remove the service and create new, which cause downtime...

**Steps to reproduce the issue:**
```
docker service update --restart ...
```
This command would send HUP command to all replicas of service. `--update-parallelism` and `update-delay` would affect parallelism and delay of this action

**Comment by thaJeztah** [comment] 2016-10-22 19:51
Oh! Actually, this looks like a duplicate of https://github.com/docker/docker/issues/24413, sorry for that; I'll close this issue, but let me know if you think it's not a duplicate

**Closed by thaJeztah** 2016-10-22 19:51 UTC
